### ISSUE TITLE
Feature request: Open Language Mode picker for new file

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#110330]
One thing we've consistently seen with students and beginners using VS Code is they don't realize they need a language extension or they create a new file from the Welcome Page but don't realize they need to save it to get colorization, recommendations, etc. 

So a suggestion is from the Welcome Page, when a user clicks on New File, they are taken to a new untitled file, but we also trigger the language mode quick pick. They can choose a language mode, and based on [this](https://github.com/microsoft/vscode/issues/102823), they will get a toast prompt to install the corresponding extension.

Repl.it does a similar thing when you choose to create a new file, they prompt you to choose the language and name the repl
![image](https://user-images.githubusercontent.com/9721254/98710566-d2269880-2351-11eb-92cd-f2a88c5b1d9a.png).

**Comment by chrmarti** [comment]
I wonder if letting the user pick a filename would be more natural than the mode picker. We would loose the simplicity of 'New Untitled File'.

**Comment by sana-ajani** [comment]
We've heard that new users and students are not sure what to do after they create a new file and start writing their code. Letting them pick a filename is also a good idea, which would allow them to save their file too (we saw in user studies, people didn't realize they had to explicitly do this).

**Comment by chrmarti** [comment]
We could open the untitled file and then immediately trigger the save dialog.

**Comment by chrmarti** [comment]
Just found that 'New File' in the Explorer also works when triggered while the Explorer does not have focus. Trying that for non-empty windows, empty windows (no folder open) will open an untitled file and immediate save - asking for a filename. The save dialog is a little heavy, so please give that a try in the next Insiders build. /cc @misolori

**Comment by chrmarti** [comment]
@sana-ajani Reverting for now as I'm not convinced by how this works / looks. Insiders might not give us the feedback we need because they more often use the keyboard shortcut. We could run an experiment in a stable release, but I don't think we have the numbers to do so from the Welcome page alone.

**Comment by aeschli** [comment]
Verified that `New File` from the welcome page opens the mode quick pick
