### ISSUE TITLE
Terminal encode

### ISSUE THREAD

**Issue by perlsky** [microsoft/vscode#110321]
Issue Type: <b>Bug</b>

With Remote - WSL extension.
In spite of the environment value as export LANG=ja_JP.eucJP, the integrated terminal shows wrong letters.
This issue reproduces on VSC for OSX even without the extension.

Extension version: 0.42.3
VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.19577

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
You can set `"terminal.integrated.detectLocale": "off"` to make sure we're not changing the value. We need to add support to not change this euc format.
