### ISSUE TITLE
Display members of a file in explorer

### ISSUE THREAD

**Issue by jnegron357** [Microsoft/vscode#11036]
It would be great to drill down to members of a component within the explorer tree or in an outline view of the selected file. This is extremely useful when you have many objects in one file and you're struggling to find that one function that you need to finish a task. See below for example from VS:
![image](https://cloud.githubusercontent.com/assets/3504712/18017173/4275f9de-6b9e-11e6-8b65-0143b5143fc9.png)

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
