### ISSUE TITLE
markdown.smartSelect tests disabled

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110365]
Disabled some `markdown.smartSelect` tests after seeing this failure

https://dev.azure.com/vscode/VSCode/_build/results?buildId=57510&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0&l=680

I tried some markdown smart select scenarios and it seemed ok.

**Comment by meganrogge** [comment]
[fixed ](https://github.com/microsoft/vscode/commit/b2eca1fd4de7fa7bd798ce545bd6126b8554c44e)
