### ISSUE TITLE
Codelens screen cheese 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110332]
- VSCode Version: 1.52 Insiders
- OS Version: macOS

<img width="771" alt="image" src="https://user-images.githubusercontent.com/876920/98711118-7223f800-2339-11eb-9dae-63ca7ab50ed4.png">

After some refactoring, the codelens are messed up. The view zone behind the codelens is disposed (as they are gone) but the codelens is still there.

It's an interesting issue that occurred to me multiple times per month (I remember I reported similar issue before). I'm wondering if we should have some better troubleshooting helper in the editor, similar to the keybindings troubleshoot command.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
I have made some changes to code lens yesterdays and also saw this today. Tho, no good steps

> The view zone behind the codelens is disposed (as they are gone) but the codelens is still there.

I don't think so. In your screen capture there is blank space between line (like above 737) but it seems that the content widget is misaligned.

**Comment by jrieken** [comment]
regression from https://github.com/microsoft/vscode/issues/16038
