### ISSUE TITLE
Searching within files causes windows defender (antimalware.exe) to run and takes over my computer for 30 minutes

### ISSUE THREAD

**Issue by ericmaier** [Microsoft/vscode#11037]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Bring up search (Ctrl + Shift + F)
2. Search
3. Antimalware.exe process starts and computer cpu goes to 100%. Search never completes and progress indicator stops updating at 90%.

**Comment by bpasero** [comment]
We just changed search a lot, maybe you could try to reproduce from our insiders build?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by ericmaier** [comment]
I thought this was just ported with VSIX from VS-SDK. I will update my install and see what happens. I'm having to perform project searching with a 3rd party text editor (sublime). Not the ideal development environment.

**Comment by ericmaier** [comment]
Updated my VS Code install and performed search like normal and experienced a new behavior. I initiated a search from the VS Code search GUI and in my task monitor window I watched Antimalware Service Executable kicked off like it has been. But then for the first time, search completed with results and the Antimalware Service went from 100% CPU to back down to <5% CPU as its normal state. The entire search process, including the antimalware service bloating to 100% CPU and back down to <5% utilization, took less than 2 seconds. It feels like someone put in a catch or a "on error resume next" statement somewhere, lol. But it works better than before, thanks for building a nice lightweight IDE with breakpoints. Very nice.

**Comment by bpasero** [comment]
Ok great to hear. My feeling is that your OS configuration just protects access to file resources. We made search a lot faster so you notice it less, but I think the issue still persists.

Leaving for @chrmarti to decide how to continue with this issue.

**Comment by ericmaier** [comment]
Thanks and yes this makes sense now the way you explained it. Im on a surface pro 4 i7 that I just picked up for the project and its running on off-the-shelf configuration. 

This IDE beats the pants off of IntelliJ IDEA. I'm a 14 year c# developer and couldnt find a decent IDE for nodejs development until I found VS Code. Thank you for making my job easier.

**Comment by ericmaier** [comment]
Wanted to let you know that my problem came back and everytime I performed a search Windows Defender Antimalware Service took over and made search in VS Code impossible. I turned off Windows Defender with a edit to the machine registry and everything is working as expected.

**Comment by chrmarti** [comment]
We backed out the use of 'dir' to quickly get at the list of files. So we're back to the old performance and behavior.

**Comment by roblourens** [comment]
For anyone else seeing this, one easy workaround is to add a Defender exclusion for "Code.exe"

**Comment by roblourens** [comment]
This may be better than it used to be, but there isn't necessarily anything we can do about Defender. When searching a local disk, it often will run during the first search in a folder, then results will be cached for later searches.
