### ISSUE TITLE
No Show Local option when saving workspace

### ISSUE THREAD

**Issue by Chillifish** [microsoft/vscode#110311]
- VSCode Version: 1.51.0
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. Open new window
2. Open remote folder via SSH
3. Add folder to workspace
4. Choose "Save Workspace As…" from file  menu.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
This appears to have been intentional: e5d104b3a8aeb80400361713f735f5665a11d5f5

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/109713
