### ISSUE TITLE
Change color of window per instance

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode#110308]
It is not unusual that I have multiple copies of Visual Studio Code open while I am working. Sometimes it is not immediately clear which window I am, especially if the folders that are open have the same name. For example, it's not unusual for me to have a the `master` version of a project open in one window, and have a working PR version of the same project open in a second window. When this is the case it is easy to get confused which is which.

If I could instead set the border color of one window to be blue, and the other to be yellow, this would immediately signal to me which was which.

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock

**Comment by aeschli** [comment]
https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock is the answer!
