### ISSUE TITLE
Multiroot WS Source Control Repository View Shows Full Path

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#110367]
- VSCode Version: 1.52.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a multi root workspace in which all of them are git repo

![image](https://user-images.githubusercontent.com/15051871/98770048-54bd5f80-2407-11eb-8839-cb5f9fbb2fe1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Are these symlinks?

**Comment by stagefright5** [comment]
> Are these symlinks?

No

![image](https://user-images.githubusercontent.com/15051871/98795428-36b82500-2430-11eb-8e50-d5cfcba85a06.png)

**Comment by stagefright5** [comment]
Also, the `.code-workspace` file contents

![image](https://user-images.githubusercontent.com/15051871/98795666-7848d000-2430-11eb-8674-3b7f6d973686.png)

**Comment by joaomoreno** [comment]
I can reproduce this on yesterday's Insiders, but no longer on today's, so I'm guessing @jrieken or @isidorn have fixed something here.
