### ISSUE TITLE
Large Visual Glitches running on Debian (Xfce Deskop Environment)

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#110368]
Issue Type: <b>Bug</b>

1. Launch VS Code on a system running Debian Linux with the Xfce desktop environment.
2. Use the software normally and observe.

Some of the most noticable visual glitches:
 - Rapid changes to positions of elements in UI causes tearing, with not all pixels updating at the same time (noticable whilst typing this in Issue Reporter window, or when scrolling through long files). This usually is fixed in a few frames.
 - Drop down menus (such as file, edit and view menus, as well as right-click menus) have white lines all across them. The position of these lines seems to be random, and changes when the mouse is moved.
 - Editing text (particularly in text boxes such as the Issue Reporter window) causes similar lines to those in drop down menus.

I'm not used to Linux so I can't figure out how to screenshot. I'll comment on this issue later with some photos from my phone.

Note that these glitches occur regardless of theme.

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:44:48.716Z)
OS version: Linux x64 4.19.0-0.bpo.12-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 4093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.26GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d2fdf864-5dc4-47d9-bded-bc3859946198|
|Screen Reader|no|
|VM|67%|
|DESKTOP_SESSION|default|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
bracket-pair-colorizer-2|Coe|0.2.0
cpptools|ms-|1.1.1
vscode-open|san|0.1.0

(1 theme extensions excluded)

</details>

**Comment by MiguelGuthridge** [comment]
Sorry I'm late, these are the images of the issue taking place.

![image](https://user-images.githubusercontent.com/31365175/99016542-7a836980-25ab-11eb-8e5d-4a13615d62b8.png)
![image](https://user-images.githubusercontent.com/31365175/99016551-8111e100-25ab-11eb-9f09-9601791361bf.png)
![image](https://user-images.githubusercontent.com/31365175/99016846-ba4a5100-25ab-11eb-8267-3a3709bf3f5e.png)
![image](https://user-images.githubusercontent.com/31365175/99017378-dea62d80-25ab-11eb-8a9c-1a29d7ad5723.png)

**Comment by deepak1556** [comment]
Does the issue happen when you start with `--disable-gpu` ?

**Comment by MiguelGuthridge** [comment]
> 
> 
> Does the issue happen when you start with `--disable-gpu` ?

Sadly I can't test this since the issue occurs on my university's systems, which I can't access currently since the term has just ended. I'll send some emails and see if I can get a tutor to give it a go. Otherwise, testing may need to wait until next year, sadly.

**Comment by deepak1556** [comment]
Closing for now as there is nothing actionable, can reopen once there is followup info. Thanks!
