### ISSUE TITLE
Quick pick API broken when quickpick.buttons option is set to true

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#110432]
### THIS IS NOT A PYTHON EXTENSION ISSUE

This only happens starting from VSCode `1.51`. `1.50` works fine. Process picker in the Python extension is broken because of this: https://github.com/microsoft/vscode-python/issues/14678

Version: 1.52.0-insider (user setup)
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Execute the following code to display quickpick
```typescript
const refreshButton = {
    iconPath: 'getIcon(REFRESH_BUTTON_ICON)'
};
const quickPick = vscode.window.createQuickPick();
quickPick.items = [{ label: 'some label' }];
quickPick.buttons = [refreshButton];
quickPick.show();
```
2. No quickpick is displayed. Remove the `.buttons` assignment, or empty it.
```typescript
const refreshButton = {
    iconPath: 'getIcon(REFRESH_BUTTON_ICON)'
};
const quickPick = vscode.window.createQuickPick();
quickPick.items = [{ label: 'some label' }];
quickPick.buttons = [];
quickPick.show();
```
Quickpick is displayed. The original code which failed is [here](https://github.com/microsoft/vscode-python/blob/61b179b2092050709e3c373a6738abad8ce581c4/src/client/debugger/extension/attachQuickPick/picker.ts#L20-L80).

3. **Another workaround**: Add another `quickPick.show()` line at the end.
```typescript
const refreshButton = {
    iconPath: 'getIcon(REFRESH_BUTTON_ICON)'
};
const quickPick = vscode.window.createQuickPick();
quickPick.items = [{ label: 'some label' }];
quickPick.buttons = [refreshButton];
quickPick.show();
quickPick.show();
```
Quickpick is displayed. But refresh icon isn't displayed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
The `iconPath` must be a URI, the type has been like that since the introduction of QuickInputButton, our implementation happened to tolerate strings until recently. I'll add a fallback, but recommend to use `Uri.file` to convert the strings to URIs on the extension side to adhere to the `vscode.d.ts`. (This might have slipped through on your side because until recently ThemeIcon did not have any required properties, this changed with https://github.com/microsoft/vscode/commit/cb1dce0ef30d48c4259eb7d0a923926b3e6e16af.)

**Comment by karrtikr** [comment]
Ok gotcha, thanks. Although I think that even if one of properties is invalid, the entire quickpick shouldn't fail to show. Instead that property should just be ignored.

**Comment by karrtikr** [comment]
Just pointing out that the `iconPath` property in almost other places does allows string: https://code.visualstudio.com/api/references/vscode-api
Perhaps since is something that can be improved.

**Comment by karrtikr** [comment]
Interestingly `iconPath` property in almost other places does allows string: https://code.visualstudio.com/api/references/vscode-api
Perhaps since is something that can be improved.
