### ISSUE TITLE
Add ability to use --no-verify as default (⌘+Enter) commit

### ISSUE THREAD

**Issue by doplumi** [microsoft/vscode#110452]
**Reason**: Hooks can be quite time-consuming, even on powerful machines.
What I like to do, in order to wait less, is to skip the verification most of the time and only do it before I know I need to push, or when I am committing a bigger chunk. That way I can avoid to wait 3-5s for the linter to analyse the whole project, if I am just updating some default config.

I'm not sure how popular this is, but I found another user [on stackoverflow] asking for the same feature.

[on stackoverflow]: https://stackoverflow.com/questions/52986809/how-to-configure-options-for-the-version-controls-git-commit-command

Thanks!

**Comment by joaomoreno** [comment]
Once you enable`git.allowNoVerifyCommit`, a bunch of commands will be available:

![image](https://user-images.githubusercontent.com/22350/98923649-38d3bf80-24d4-11eb-955a-5c9560dfbf76.png)
