### ISSUE TITLE
Text cursor stops blinking in integrated terminal if you run external command

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode#11049]
- VSCode Version: 1.4.0, 1.5.0-insider 2016-08-26T08:02:25.854Z
- OS Version: Ubuntu 16.04

**Steps to Reproduce:**

user setting: `"terminal.integrated.cursorBlinking": true`

1. Open integrated terminal - the text cursor is blinking :white_check_mark:
2. Run `less file.txt` or `man awk` or `mc`
3. Quit the external command ("q" or F10)

**Expected result**
* the text cursor is blinking

**Expected result**
* the text cursor is not blinking

**Workound**
* restart the terminal window

**Comment by faustinoaq** [comment]
I have the same issue.

* VSCode Version: 1.4.0
* OS Version: Manjaro KDE Linux
