### ISSUE TITLE
The git commit message field is cropped with negative zoom

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#110441]
Issue Type: <b>Bug</b>

Here's what I get with `"window.zoomLevel": -0.71,`:

![Snipaste_2020-11-11_22-09-14](https://user-images.githubusercontent.com/2473545/98882433-fb871780-246a-11eb-8a3c-b8e19fe9a2bb.png)

I know there are some bugs with non integer zoom levels, but this is a regression! It used to display correctly in previous versions. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.27GB free)|
|Process Argv|--crash-reporter-id f21ed382-d472-4360-9cb5-a6e51078377b|
|Screen Reader|no|
|VM|0%|

(4 theme extensions excluded)

</details>

**Comment by chenjigeng** [comment]
The reason it's cropped is because the parent node is set `overflow: Hidden`.
![image](https://user-images.githubusercontent.com/14784326/101940425-6de14800-3c21-11eb-889c-13dbb74de1e0.png)

To not affect other nodes of the same type, I only set `overflow: unset` for the .scm-input. just like the  PR. please help check that @joaomoreno 
.
![image](https://user-images.githubusercontent.com/14784326/101940572-aaad3f00-3c21-11eb-8801-85c398d926b2.png)

**Comment by joaomoreno** [comment]
Yes, that's related to the fact that it's hidden. But the real problem here is CSS unit rounding. The contents of that div should never escape its bounding box and when zomming out that is happening. We should not change the overflow rule.

**Comment by chenjigeng** [comment]
Yes, you are right. I try to change margin to padding. And it work. @joaomoreno Please see if that's ok
![image](https://user-images.githubusercontent.com/14784326/102073409-3d2a2a00-3e3e-11eb-83c3-42827c9e1a01.png)
