### ISSUE TITLE
Run Custom Commands (filter)

### ISSUE THREAD

**Issue by W4RH4WK** [Microsoft/vscode#11045]
There already a couple of extensions available doing a very similar thing, running a custom command. I am not talking about something like the Task runner which is already part of vscode, but of extensions like these:

- [vscode-filtertext](https://github.com/yhirose/vscode-filtertext)
- [vscode-shell](https://github.com/bbenoist/vscode-shell)
- [LaunchTerminal](https://marketplace.visualstudio.com/items?itemName=testingtestingtesting.launchterminal)
- [OpenVim](https://marketplace.visualstudio.com/items?itemName=mattn.OpenVim)
- [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave)
- ...

My proposal is to add these features to the vscode so people don't have to rely on extensions for these things. I am thinking about a *more generic version* which lets you:

- Execute a custom commands
- Execute a custom commands in the integrated terminal
- Pre-configure commands in the user's config
- Bind custom keyboard shortcuts to (pre-configured) commands
- Have variables available which get replaced with things like the current filepath, filename, working directory, line number, preferred line length (for [`par`])
- Pass selected text to command
- Filter selected text with command (like `sort -r`)
- Read in output of a command

Maybe even:

- Attach triggers like *onSave* to a command

[`par`]: <http://vimcasts.org/episodes/formatting-text-with-par/>

Let me know what you think about integrating this directly into vscode. Keep in mind that vi's `:!` covers  a lot of these cases and has been a feature right from the start.

**Comment by faustinoaq** [comment]
Maybe a plugin that puts it all together. XD

**Comment by sandy081** [comment]
@W4RH4WK Main goal of VS Code is to be simple, fast and light weight. We made it open to the community to extend and customize it based on the needs. Those who are using it as a simple editor might not need this functionality.

Above requirement is a perfect example of customizing it and using it as required.  

Thanks.

**Comment by geddski** [comment]
I wrote an extension for running custom series of commands (aka macros). Feedback welcome.

https://marketplace.visualstudio.com/items?itemName=geddski.macros
