### ISSUE TITLE
"Initialise Repository" message won't go away

### ISSUE THREAD

**Issue by drawcard** [microsoft/vscode#110445]
- VSCode Version: 

Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- OS Version: MacOS Catalina 10.15.7

This message won't go away, even if the repository has been initialised:

![image](https://user-images.githubusercontent.com/1435638/98895199-75b0ae00-24f6-11eb-94a6-26c859cdd287.png)

![image](https://user-images.githubusercontent.com/1435638/98895328-c7f1cf00-24f6-11eb-9519-95def224b70d.png)

Steps to Reproduce:

1. Create a new project
2. Initialise the repository
3. Wait a few moments

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
What does `Git: Show Git Output` show?

**Comment by drawcard** [comment]
Thanks @joaomoreno - the problem seems to have gone away, but I will report back if I notice it again.
