### ISSUE TITLE
Frequently asked to select cell language twice

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#110427]
Often the first time I change the cell language, I get a second quick pick to change the language immediately afterwards. 

![recording (20)](https://user-images.githubusercontent.com/8586769/98859320-d9fc4080-2416-11eb-8087-04d92fbb91eb.gif)

**Comment by rebornix** [comment]
@JacksonKearl do you have detailed steps or you are seeing all the time? I tried your omnikernel sample but didn't reproduce.

**Comment by JacksonKearl** [comment]
Hm... if you select the entry with `Enter` it seems to reproduce all the time. Maybe the enter is double dispatching to both select the item and trigger the picker?

**Comment by DonJayamanne** [comment]
@rebornix 
I can see this everytime myself.
Click on language bottom left of cell & in the quick pick select something & hit `Enter` key.

**Comment by rebornix** [comment]
What happens:

* Click the language status item
* Quick pick shows up
* Enter to pick one language
  * `keydown` for enter, quick pick dismisses, focus goes back to the language status item
  * `keyup` for enter, which triggers the language picker to activate again

fix is listening to `keydown` other than `keyup`, which aligns with workbench status bar item. cc @roblourens
