### ISSUE TITLE
my windows going to sleep whenever i open visual studio code

### ISSUE THREAD

**Issue by Ahana0** [microsoft/vscode#110419]
My window's is going to sleep very unexpectedly whenever im opening visual studio. I've checked all the settings in my pc and turn sleeping mode to never and all. this is only happening to visual studio. what can i do?

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide info required by issue template (VS Code version, OS version etc.)

And most importantly: does this  happen when you start it with `--disable-extensions` CLI flag, like `code --disable-extensions`?
