### ISSUE TITLE
Typo on IME Test Wiki

### ISSUE THREAD

**Issue by azu** [microsoft/vscode#110443]
Hello.
I can not edit the wiki. Instead of it, I file this issue.

I found a typo on IME-Test wiki.
https://github.com/microsoft/vscode/wiki/IME-Test

>  konnichiha should result in "こんいちは"

should be

> `konnnichiha` should result in `"こんにちは"`

```diff
- konnichiha
+ konnnichiha
- こんいちは
+ こんにちは
```

`ko-nn-ni-chi-ha` will be `こんにちは`.

```
ko-nn-ni-chi-ha
こ-ん-に-ち-は
```

Also, I found same typo on test file.

https://github.com/microsoft/vscode/blob/40a54b0e33fb46312b79df4387c41ba1fc6fd9f9/src/vs/editor/test/browser/controller/imeTester.ts#L168

```diff
-	{ description: 'Japanese IME 2', in: 'konnichiha [Enter]', out: 'こんいちは' },
+	{ description: 'Japanese IME 2', in: 'konnnichiha [Enter]', out: 'こんにちは' },
```

![Nov-12-2020 10-25-18 2020-11-12 10_26_07](https://user-images.githubusercontent.com/19714/98883341-80a51780-24d1-11eb-9731-a6e00b648f5b.gif)

📝 Note

"こん**い**ちは" is common misspelling of "こん**に**ちは"

- "こんにちは" is correct word in japanese
- "こんにちは" pronunciation is "ko-n-ni-chi-**wa**" in japanese
- "こんにちは" spelling is "ko-n-ni-chi-**ha**" in [Romanization of Japanese](https://en.wikipedia.org/wiki/Romanization_of_Japanese)
- "こんにちは" typing is "ko-**nn**-ni-chi-ha" in IME(Romaji input mode. It is default behavior in almost IME)

IME transform "nn" to "ん" for avoiding typo.
Also, some IME auto correct "こん**い**ちは" to "こん**に**ちは", because "こん**い**ちは" is common misspelling.
"こんにちは" is difficult word…

**Comment by alexdima** [comment]
Resolved via https://github.com/microsoft/vscode-wiki/pull/158
