### ISSUE TITLE
VS code will creat a new folder in D disk

### ISSUE THREAD

**Issue by Tongxulee** [microsoft/vscode#110486]
Issue Type: <b>Bug</b>

each time I open VS code , in D disk will creat a new folder,the name is < ͬ��>,and the directory tree is ͬ��->TEMP1->loose->2166136261 ,
there are 3 files in the final folder:  
.browse.VC.db   .browse.VC.db-shm .browse.VC.db-wal
I've set sync,but in another computer don't happen this.
So I ask for your help,thanks!

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.04GB free)|
|Process Argv|--crash-reporter-id 0817a075-4dc8-4f3c-9243-c5360d078310|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
code-runner|for|0.11.1
vscode-language-pack-zh-hans|MS-|1.51.2
python|ms-|2020.11.358366026
cpptools|ms-|1.1.1
markdown-preview-enhanced|shd|0.5.13
vscode-icons|vsc|11.0.0
vim|vsc|1.17.1
material-theme|zhu|3.9.3

</details>

each time I open VS code , in D disk will creat a new folder , the name is < ͬ��>,and the directory tree is ͬ��->TEMP1->loose->2166136261 ,
there are 3 files in the final folder:  
.browse.VC.db   .browse.VC.db-shm .browse.VC.db-wal
I've set sync,but in another computer don't happen this.
So I ask for your help,thanks!
![image](https://user-images.githubusercontent.com/57761655/98955778-44f26800-253a-11eb-8fee-2b18e91bd901.png)

**Comment by alexdima** [comment]
I don't think we would write there. `.db-shm` usually belongs to SQLite, I think we use SQLite for some global storage or workspace storage, otherwise Chromium/Electron might be writing these.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Tongxulee** [comment]
First of all , thank you ！ 
I updated C/C++ extension yesterday , then I could delete the folder while VS code was running ,and it didn’t appear again when I open VS code . Maybe it’s the extension causes the problem.  

发送自 Windows 10 版邮件应用

发件人: Alexandru Dima
发送时间: 2020年11月13日 21:57
收件人: microsoft/vscode
抄送: Tongxu; Author
主题: Re: [microsoft/vscode] VS code will creat a new folder in D disk(#110486)

I don't think we would write there. .db-shm usually belongs to SQLite, I think we use SQLite for some global storage or workspace storage, otherwise Chromium/Electron might be writing these.
