### ISSUE TITLE
Cannot set locale in terminal

### ISSUE THREAD

**Issue by Galaxy0419** [microsoft/vscode#110491]
Showing ```bash: warning: setlocale: LC_ALL: cannot change locale (en-US)``` when opening a terminal window

- VSCode Version: code 1.51.1
- OS Version: Arch Linux

Steps to Reproduce:
1. Open terminal using ctrl + shift + `

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Did you try to set the locale or do anything that could have caused this?

If not, you can set` "terminal.integrated.detectLocale": "off"`

**Comment by jorgelaranjo** [comment]
The problem is at electron level: https://github.com/microsoft/vscode/issues/110322 and https://github.com/electron/electron/issues/26443

**Comment by jorgelaranjo** [comment]
Downgrading Electron sorts it until an update for it is available
https://github.com/microsoft/vscode/issues/110322#issuecomment-726426703

**Comment by Souravgoswami** [comment]
I also have this issue running any command, look at the terminal, it just breaks:

![image](https://user-images.githubusercontent.com/37468605/99141190-c0553600-266e-11eb-9d2a-835f4590331c.png)

This started happening after I upgraded electron9 without upgrading code. I received code version 1.51.1 (ArchLinux) and I still have the same problem. I  also saw this problem on reddit...

**Comment by XO490** [comment]
> Showing `bash: warning: setlocale: LC_ALL: cannot change locale (en-US)` when opening a terminal window
> 
> * VSCode Version: code 1.51.1
> * OS Version: Arch Linux
> 
> Steps to Reproduce:
> 
> 1. Open terminal using ctrl + shift + `
> 
> Does this issue occur when all extensions are disabled?: Yes

I have the same problem
![2020-11-16_20-23](https://user-images.githubusercontent.com/39729159/99257644-f00c6580-2849-11eb-8f96-4971d2809767.png)
![2020-11-16_20-21](https://user-images.githubusercontent.com/39729159/99257662-f7337380-2849-11eb-8dff-9e5f22c87487.png)
![2020-11-16_20-20](https://user-images.githubusercontent.com/39729159/99257685-fdc1eb00-2849-11eb-9348-133e273051c2.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/110322

**Comment by ricardozv** [comment]
I have the same problem.

**Comment by iqido-systems** [comment]
I have this problem too

**Comment by ricardozv** [comment]
This solution 
telmotrooper commented 9 days ago • 
For anyone having this issue on Arch Linux, downgrade package electron9 from 9.3.4 to 9.3.3.

curl -O https://archive.archlinux.org/packages/e/electron9/electron9-9.3.3-1-x86_64.pkg.tar.zst
sudo pacman -U electron9-9.3.3-1-x86_64.pkg.tar.zst
You'll probably want to add electron9* to IgnorePkg in /etc/pacman.conf, so the next time you update your packages you won't accidentally update this one as well. When a fix has been deployed you can remove this setting...

**Comment by SparK-Cruz** [comment]
Electron 9.3.5-1 is available for Arch.
`pacman -Sy electron9` should do the trick

**Comment by djmittens** [comment]
manjaro does not have this this version yet, what can i do in the interim?
