### ISSUE TITLE
Debugger breakpoints do not work in nodeJS when the code folder is a symbolically linked over WSL2

### ISSUE THREAD

**Issue by alanosman** [microsoft/vscode#110436]
- VSCode Version: 1.51.1
- OS Version: W10 10.0.19041 

Steps to Reproduce:

1. Open a bash command prompt and create a local folder called `debug-test` from your home directory.
2. create a new code file called `app.js`
3. paste this code and put a breakpoint on the first var

```
'use strict';

var express = require('express');
var app = express();

app.get ('/', (req, res) => {
    res.send('Hello world');
});

app.listen(3600, () => {
    console.log('example port');
});
```

4. At the terminal, in the test folder run `npm install express`
5. Go to the debugger (SHIFT+CTRL+D) and click the gear to create a new `launch.json`
6. Paste this:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Test",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/app.js"
        }
    ]
}
```

7. Press F5 to test and make sure the debug stops execution.
8. Exit the app, close Visual Code
9. At the bash prompt make a new symbolic link folder `ln -s debug-test debug-test-broken`
10. cd into `debug-test-broken` and start code `code .`
11. Set a breakpoint in `app.js` on the first `var express=..` and press F5

You will see that the breakpoint is never met. 

This problem had me baffled all day, and after widdling out the rest of my app, I finally was able to reliably reproduce the issue. I also tested with Visual Code Preview build. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
For this you need to [`--preserve-symlinks-main`](https://nodejs.org/api/cli.html#cli_preserve_symlinks_main) ([docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks)), but Node.js does not behave very well when the entire path is symlinked. 

I want to add behavior to automatically reconcile symlinks, follow this for updates: https://github.com/microsoft/vscode-js-debug/issues/776

**Comment by alanosman** [comment]
@connor4312 I actually went down that path and `--preserve-symlinks-main` did not help at all.

**Comment by alanosman** [comment]
@connor4312 I just want to make sure you really see the issue.  This is related to symbolicly linked directories under WSL2, maybe - I don't know exactly what causes the debugger to fail but it goes away when I use a regular folder.  Is there a way you can test this before you decide to close it?

**Comment by connor4312** [comment]
Yea, that's part of what I referenced in

> but Node.js does not behave very well when the entire cwd is symlinked.

In this case, Node.js' --preserve-symlinks flags don't work, so it reports different files are loaded than the paths that VS Code things exist on disk.

**Comment by alanosman** [comment]
@connor4312 ok - thanks for the clarification.  Much appreciated.
