### ISSUE TITLE
 Cannot read property 'length' of null while opening vscode terminal

### ISSUE THREAD

**Issue by SidWorks** [microsoft/vscode#110467]
We have written the needed data into your clipb
Issue Type: <b>Bug</b>

open vscode 
press ctrl+' to open terminal
terminal come blank, if you press + icon to open new terminal it gives error Cannot read property 'length' of null
![image](https://user-images.githubusercontent.com/51191127/98932776-ca0f5a00-2505-11eb-9668-9a7f1ba83f7f.png)

please help

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.10GB free)|
|Process Argv|-n --crash-reporter-id 817d42cb-f27e-4eee-876a-2253c27a84e6|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
turbo-console-log|Cha|2.0.4
bracket-pair-colorizer|Coe|1.0.61
markdown-julia|col|0.0.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.3
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.2
vscode-vibrancy|eyh|1.0.9
code-runner|for|0.11.1
beautify|Hoo|1.5.0
sublime-babel-vscode|jos|0.2.10
language-julia|jul|1.0.8
theme-monokai-pro-vscode|mon|1.1.17
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
prettify-symbols-mode|sie|0.4.2
indenticator|Sir|0.7.0
vscode-scheme|sjh|0.4.0
code-spell-checker|str|1.9.3
ayu|tea|0.20.1
learn-vim|vin|0.0.23
JavaScriptSnippets|xab|1.8.0
city-lights-icon-vsc|Yum|1.1.3

(6 theme extensions excluded)

**Comment by meganrogge** [comment]
I think this is caused by one of your extensions because we do not have that error message anywhere within the VSCode base. Can you try to reproduce this with your extensions disabled?

**Comment by meganrogge** [comment]
Thanks for the issue. I'm not able to reproduce this. Could you pls create a [GIF](https://gifcap.dev/) ?

**Comment by SidWorks** [comment]
Thank you for your response, i figured it out!
There was some issue in the settings json file, value of something was set
to null, it was expecting a color code in form of string when i changed it
to "#ffffff" the error got corrected that i got corrected !
