### ISSUE TITLE
Search Function (tools in the right toolbar) searchs files by name

### ISSUE THREAD

**Issue by gigimignon** [microsoft/vscode#110456]
It's possible to add file name search in the global search?
When types for example toto.json, the result shows all files that contains toto.json

**Comment by gjsjohnmurray** [comment]
Do you know about Quick Open (Ctrl/Cmd+P) ?

**Comment by gigimignon** [comment]
Thanks, the function is a part of the solution.

Sometimes, we needs the list of files (ex: all files .json) and modify something on each files.
the view "memorize" the last files opened.
The Ctrl+P only used to go to 1 file.

PS: Why shortcut is the "default" shortcut of printing element?

**Comment by gjsjohnmurray** [comment]
If you use the right-arrow key on an item in the Quick Open list it opens that file, removes it from the list, and leaves you in the list ready to do the same for another entry.

**Comment by gigimignon** [comment]
Thanks
