### ISSUE TITLE
%load does not work in .py or .ipynb

### ISSUE THREAD

**Issue by EconoBen** [microsoft/vscode#110404]
<img width="664" alt="Screenshot 2020-11-11 095006" src="https://user-images.githubusercontent.com/45580612/98833149-5127d980-2403-11eb-927e-d8d300df9c02.png">

- VSCode Version: 1.51.0
- OS Version: 10.0.17763

Steps to Reproduce:

1. Open a fresh .ipynb or .py file. 
2. enter the following code: %load myfile.py
3. Additionally this code does not work: ```from IPython import get_ipython
ipython = get_ipython()
ipython.magic("load myfile.py")```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Please report directly against the python extension at https://github.com/Microsoft/vscode-python/issues
