### ISSUE TITLE
Show pinned tabs in a separate row

### ISSUE THREAD

**Issue by kenpalmer** [microsoft/vscode#110477]
In Visual Studio Code, please add the ability to pin (or put) tabs in separate rows.  In Visual Studio 2019 we have this capability, and I love using this feature to organize files while I write code. Thank you.

Here is an example from Visual Studio 2019.
![image](https://user-images.githubusercontent.com/71081312/98946908-23519c00-24ba-11eb-83c4-23810c9293e9.png)

And in Visual Studio 2019, the pinned tabs option appears in Tools > Options > Environment > Tabs and Windows.
![image](https://user-images.githubusercontent.com/71081312/98946502-93abed80-24b9-11eb-86a6-8c0a6109fc75.png)

**Comment by kenpalmer** [comment]
That thread devolved into an argument from a Microsoft engineer who essentially asked customers to defend their request for a new row of tabs. Give developers a chance to upvote a simple request.

The October 2020 VS Code release (1.51.1) offered a "Workbench" enhancement to make pinned tabs more prominent. This is what prompted me to post this straightforward request.

Since someone at Microsoft already had their head(s) wrapped around extending tabs, ask them to look into enabling us to add a second row.  It's not like we're asking for strange behavior; you're already doing it with Visual Studio 2019 (and previous versions).

**Comment by misolori** [comment]
@kenpalmer I closed this issue because it's asking for the same thing as the issue I linked to. Are they not the same?

**Comment by kenpalmer** [comment]
It's similar, but it opens with "vs what we do today" and the original poster follows up with "VSCode are always the first tabs of the row and never scroll out of view, does that still require a secondary row then?"

After reading that post, I received the impression that the original poster began by trying to show "what we do today" with a helpful animation as a useful alternative to presenting a second row of tabs in the IDE.  But that post turned into multiple requests from customers for a second row.

When presented with the counterpoint of a second row enhancing "visibility and speed of access," the engineer responds with "yeah understood, assume you have a setting to show the name of a tab even when pinned. Would that be sufficient **to not add** another row of tabs?" (emphasis mine)

Essentially, the OP shows an alternate workaround for not presenting pinned tabs in a second row. Then he proceeds to argue with customers who request that feature.

It devolved into a thread where customers (developers) are arguing with a Microsoft engineer who essentially has all the power because he has the final say in determining if this feature will be added to Visual Studio Code.

Another example, "To be clear: I would only suggest a solution that makes pinned tabs shrink too so that you can have many pinned tabs side by side without starting to scroll." Shrinking the font is great if you have perfect vision. Not all developers can say that.

Again, "I am trying to find a design alternative that does not require a second row of tabs which I personally find very heavy visually." Then make it optional, and turn it off by default.

That's why I said this, "That thread devolved into an argument from a Microsoft engineer who essentially asked customers to defend their request for a new row of tabs. Give developers a chance to upvote a simple request."

To be clear, my intent isn't to attack the OP, who's a smart person and cares about design. I get it. But that post is junked up with resistance to making a change. What should a developer upvote? The original post?  No, that's just agreeing with the OP (a Microsoft engineer) who clearly does NOT want to add additional tab rows.  I upvoted some of the requests by customers who asked for a second row of tabs.

Again, I think that thread is so junked up with arguments that it's worthwhile to start a new thread from a customer who holds a different view.

**Comment by gjsjohnmurray** [comment]
@kenpalmer the title of the issue @misolori pointed you to when closing this as a dup seems pretty unambiguous to me:

> Pinned tabs: show them in a secondary tab row above others

If you 👍 that, you're indicating that you want to be able to show pinned tabs in a secondary row above others.

Upvotes only count if they're on the original post. See [here](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request).

**Comment by kenpalmer** [comment]
Thank you, John.
