### ISSUE TITLE
Issues auto guessing file with UTF8 encoding

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode#110415]
- VSCode Version: 1.51.0
- OS Version: 10.15.7

版本: 1.51.0
提交: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
日期: 2020-11-05T18:14:40.758Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1、enable `files.autoGuessEncoding`
2、UTF8
```

# Process 10259 resuming
# [0;1;31merror: [0munknown argument: '-masm-verbose'[0m
# [0;1;31merror: [0munknown argument: '-dwarf-column-info'[0m
# [0;1;31merror: [0munknown argument: '-fmessage-length'[0m
# [0;1;31merror: [0munknown argument: '-fstack-check'[0m
# [0;1;31merror: [0munknown argument: '-mdarwin-stkchk-strong-link'[0m
# [0;1;31merror: [0munknown argument: '-fdiagnostics-show-option'[0m 

# # + echo ' 🍺 清理结束v
# #  🍺 清理结束
```
![image](https://user-images.githubusercontent.com/7285119/98839427-79a1e900-2480-11eb-89f6-23f87b5f667c.png)

3、

![image](https://user-images.githubusercontent.com/7285119/98839193-3778a780-2480-11eb-860e-ec3a6621136b.png)
![image](https://user-images.githubusercontent.com/7285119/98839334-5c6d1a80-2480-11eb-8aca-b14f49070a82.png)

**Comment by bpasero** [comment]
@sunbohong well, that file does not seem to be valid UTF8?

![image](https://user-images.githubusercontent.com/900690/98912973-16877500-24c7-11eb-9eaa-8b7a1fb9252e.png)

**Comment by sunbohong** [comment]
It contains a special character -  `esc`

**Comment by bpasero** [comment]
Can you attach it as raw file here, as zip?

**Comment by sunbohong** [comment]
[strip.sh.zip](https://github.com/microsoft/vscode/files/5555407/strip.sh.zip)

**Comment by bpasero** [comment]
I reported this as https://github.com/aadsm/jschardet/issues/64
