### ISSUE TITLE
Make comment editor expandable

### ISSUE THREAD

**Issue by mcamou** [microsoft/vscode#110403]
Sometimes when adding a comment you need more than 4 lines (e.g. when adding a suggestion). In this case, browsing the code in your suggestion 4 lines at a time is really not practical, so I end up submitting the comment to see it whole, then editing it again.

It would be nice to be able to "grow" the comment field, either with the mouse (click and drag the bottom-right corner of the field) or if it automatically grew depending on the length of the comment.

**Comment by nilehmann** [comment]
Any updates on this? the small box is almost unusable
