### ISSUE TITLE
In my completion extention, I want to get the index in the suggestion panel when the user  accepts a completion item?

### ISSUE THREAD

**Issue by garygao12580** [microsoft/vscode#110476]
![image](https://user-images.githubusercontent.com/24784430/98944841-a6abd580-252c-11eb-9edf-fe5aab108f19.png)

like the picture shows, I want to get the index of fouced item in the suggestion panel, here is 3. But I can't get this info from my custom CompletionItem.command arguments.

If I got this, I could easily figure out the Top-N info whitch the user prefer to aceept my code suggestion.

There is two ways to get this I think:
1. in the callback of the custom command with `CompletionItem.command`,  it's very useful that it has some parameters like the index of completion item in the suggestion panel. like following:
```ts
vscode.commands.registerTextEditorCommand(
		'xxxxCommand',
		(index, ...args) => {
		xxxx
		}
	);
```
But I think it's hard because it should be updated every time  the user editing.

2. an API is good which I could get  the index of completion item in the suggestion panel at any time.

 I'd appreciate it if anyone can give me some advice.

**Comment by HaoboGu** [comment]
I had the same problem. 

The extension doesn't know the index of completion item provided by itself, because there might be completion suggestion from other extensions.
