### ISSUE TITLE
python intelliSence by Pylance not rendered AS IS.

### ISSUE THREAD

**Issue by sirlis** [microsoft/vscode#110447]
- VSCode Version: 1.51.1
- OS Version: windows 10

Steps to Reproduce:

1. install pylance
2. define a class, or import a 3rd party package (e.g. pytorch) and then use a class
3. hover your mouse on the class name
4. the provided comment doc strings is not rendered AS IS

Does this issue occur when all extensions are disabled?: Yes

I'm using VSCode to write python, and using Pylance to provide intelliSence. I think that comment doc strings should be rendered **AS IS**. No markup interpretation. If the author makes an effort to format the string it look good.

user defined class:

![1](https://user-images.githubusercontent.com/12960298/98900906-b5bf6300-24ed-11eb-96cb-7a463a5a9bac.png)

pytorch class:

![2](https://user-images.githubusercontent.com/12960298/98900912-b952ea00-24ed-11eb-9291-4f418d1b26dd.png)

 I tried the `-` (minus) method and it worked more reasonable than plain text. But I also faced with `_` problems in variable names as is shown. Since I can add `-` in my user defined classes, I cannot edit comments in 3rd party packages like PyTorch, whose comments are shown in the images above and are rendered as plain text by Pylance.

![3](https://user-images.githubusercontent.com/12960298/98900932-c40d7f00-24ed-11eb-8a9f-b2e685767cfd.png)

**Comment by alexdima** [comment]
Please report this directly against the extension at https://github.com/microsoft/pylance-release/issues
