### ISSUE TITLE
Terminal line wrapped state is not cleared properly when navigating shell history that contains wrapped lines (up/down)

### ISSUE THREAD

**Issue by b4git** [microsoft/vscode#110446]
- VSCode Version:1.51.1
- OS Version:Windows 10 2004 and WSL Ubuntu 20.04

Steps to Reproduce:

1. Set the integrated terminal to WSL bash, and type a long command in one line like the following and press enter.
```echo "VSCode integrated terminal for WSL bash fails to position the cursor correctly when previous command is edited using [up/down] and [left/right] arrow keys. For example if you press the [home] key then instead of placing the cursor at the beginning, it is placed few characters later. "```

2. Now, press UP arrow key to access that previous command, and try to edit it. For example, try to add another echo at the beginning of that command like: `echo adding this &&  ` and try to add another command at the end of it using arrow keys and home or end keys.  Try to go back and forth to the beginning and end of the command being edited. And press enter to run this newly edited command.

3. Repeat the step 2 until you are able to reproduce the full set of related issues or until your terminal gets messy! 

An example screenshot with `wrong cursor position and texts appearing out of place`:

![image](https://user-images.githubusercontent.com/63267629/98900302-1f505a80-2477-11eb-93e0-aed94fd5f380.png)

Does this issue occur when all extensions are disabled?: Yes

** Note : This issue doesn't occur with the normal (non-integrated) terminal shell. It only occurs with the VSCode Integrated Terminal proving the fact that it is a VSCode related bug! **

**Comment by meganrogge** [comment]
Does this happen if you use bash?

**Comment by b4git** [comment]
Yes, that's what the title is referring to -- `WSL bash`. I don't see any other `bash` except `git-bash` in my system, so I am not sure which `bash` you tried to reproduce with, but the title clearly mentions this issue was reproduced with `WSL bash` and has not been tested with `git-bash`, and it was also listed in the original issue above the platform `OS Version:Windows 10 2004 and WSL Ubuntu 20.04`. Please see the screenshot below if you need more clarification.

There are only four shells in the screenshot, and `WSL bash` is the one this issue is related to. 

![image](https://user-images.githubusercontent.com/63267629/99009060-f7133b00-250c-11eb-92ea-4ed6f4c9b0b0.png)

**Comment by meganrogge** [comment]
thanks for clarifying. still not able to reproduce the issue.
![recording (38)](https://user-images.githubusercontent.com/29464607/99104591-08ecf080-2596-11eb-8dc1-1a3d140bc41c.gif)

**Comment by wuyudi** [comment]
This also happened on git-bash

![GIF](https://user-images.githubusercontent.com/30024051/104818021-e27e5680-585f-11eb-8a95-46b48e2a5734.gif)

At first, it's ok, but after some move and space, cursor missed its position.

**Comment by sabotagebeats** [comment]
same issue here, very annoying.

**Comment by mtene** [comment]
Just wanted to confirm that this has been an issue for a long time in VSCode. I see the upstream issues are closed, yet the problem persists. There might be something else at play here.

**Comment by Tyriar** [comment]
I don't think we can do anything else here, any additional problems are with the shell or conpty.
