### ISSUE TITLE
Support opening files passed as file descriptors similar to stdin

### ISSUE THREAD

**Issue by septatrix** [microsoft/vscode#110425]
What I mean by file descriptors are `/proc/self/fd/11` (and `/dev/fd/63`) which are generated by `zsh` (and bash respectively) when executing commands like `code <(echo Hello World)`.
As writing to these descriptors is not possible AFAIK these would have to be handled similar to stdin, i.e. generating a temporary file which gets filled with the content read.

Initially I was going to report `--diff` not supporting these (`code --diff <(echo hello) <(echo world)`) but I found out that vscode does not support these at all. I will open a separate issue for the diff tool as it does not even seem to support `stdin`.

**Comment by kingbuzzman** [comment]
Yes please! I was just trying to do this: `code --diff <(git show origin/master:some/path/file.py) <(git show HEAD:some/path/file.py)` and was deeply annoyed it didn't work. Nothing works when its a file descriptor it seems `code <(git show origin/master:some/path/file.py)`
