### ISSUE TITLE
comment widget display in left side editor in inline view

### ISSUE THREAD

**Issue by hacke2** [microsoft/vscode#110449]
- VSCode Version: 1.51.0
- OS Version: mac 10.15.7

Steps to Reproduce:

1. open github extension, open a pull request
2. toggle inline view

![image](https://user-images.githubusercontent.com/6399899/98903326-53b52c80-24f2-11eb-829b-3e4bb2a6ba5b.png)

comment widget display exception in left editor

Does this issue occur when all extensions are disabled?: No(But I don't think this bug has anything to do with extensions)

**Comment by rebornix** [comment]
@alexdima do you have any suggestion for how we can "smartly" hide comment widget when it's rendered on the left side of the inline editor?

**Comment by alexr00** [comment]
Tried to fix this here, but didn't get it quite right: https://github.com/microsoft/vscode/issues/164729

Issue tracking the remaining fixing is https://github.com/microsoft/vscode/issues/167733
