### ISSUE TITLE
why ${fileDirname} in tasks.json with wrong replacement?

### ISSUE THREAD

**Issue by tuduweb** [microsoft/vscode#110454]
I configure g++ in vscode tasks.json, with args -o "${fileDirname}\\${fileBasenameNoExtension}.exe".

Then I compiled my cpp file named "test.cpp" on "M://project/myfolder/", but the file was compiled to "M://project/test.exe" not "M://project/myfolder/test.exe".

maybe  the predefined variable "${fileDirname}" was replaced to wrong replacement -- "M://project/" not "M://project/myfolder"?

My vscode project on "M://project/".

Can anyone help me how to fix it? pls!

my tasks.json
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "D:\\mingw-w64\\x86_64-8.1.0-release-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${workspaceFolder}"//"D:\\MinGW\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Generated task by Debugger"
        }
    ],
    "version": "2.0.0"
}
```

![image](https://user-images.githubusercontent.com/30559085/98910913-c5937300-24fe-11eb-9587-c42b461656b4.png)

![image](https://user-images.githubusercontent.com/30559085/98911075-fecbe300-24fe-11eb-9cfa-216a4f437e67.png)

**Comment by tingroger** [comment]
same problems，only fix it by thse : (
`
        {
            "type": "shell",
            "label": "g++ in windows",
            "command": "rm ${fileDirname}\\${fileBasenameNoExtension}.exe ; mv ${workspaceFolder}\\${fileBasenameNoExtension}.exe ${fileDirname}",
            "group": "build",
            "dependsOn": [
                "win_gcc"
            ]
        }
`

**Comment by sean-mcmanus** [comment]
This is bug microsoft/vscode-cpptools#6386 with the C/C++ extension -- we're looking at shipping a patch update tomorrow.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.2
