### ISSUE TITLE
Jupyter code stopped working

### ISSUE THREAD

**Issue by mike-duran-mitchell** [microsoft/vscode#110438]
Issue Type: <b>Bug</b>

Just updated and it was working yesterday. Now, when i click shift+enter on a single line I no longer get my python executing in the Python Interactive window, instead it runs the line(s) in the terminal window. That obviously doesn't work.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.48GB free)|
|Process Argv|--crash-reporter-id 15de0bc0-9d47-4be6-9522-0d19c72bb473|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.13
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.13
json-tools|eri|1.0.2
prettier-vscode|esb|5.7.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
vscode-yaml|red|0.12.0
open-in-browser|tec|2.0.0

</details>

**Comment by Santosh-Gupta** [comment]
Stopped working for me too. The UI is different, and I don't see an option to connect to an URI

It says 

>Failed to connect to remote Jupyter notebook.
Check that the Jupyter Server URI setting has a valid running server specified.
http://cascade-salt:8000/
Error: Kernel Python 3 is not usable. Check the Jupyter output tab for more information.

Even though I have python3 enabled. 

https://snipboard.io/dnYCKH.jpg

I am using VSCode insiders for Mac

**Comment by kieferrm** [comment]
\extPython
