### ISSUE TITLE
文件和文件夹重名引发的异常

### ISSUE THREAD

**Issue by zhuzeyu22** [microsoft/vscode#110471]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.download python source code
2.compile python
3.the direction  Python and the file python has the same name
4.can not found the Python direction

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Can you edit the issue title to be also in English? That will make this issue more discoverable.

Also please fill in your OS and Code version.
