### ISSUE TITLE
Feature Request: Option to close files without saving

### ISSUE THREAD

**Issue by NicholasTuttle** [microsoft/vscode#110433]
Issue Type: <b>Feature Request</b>

I use Visual Studio Code for SQL Server programming. I am constantly opening and closing new tabs. I would like to see an option which allows me to close an unsaved file without be prompted to save it. That would save me quite a bit of time.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

**Comment by NicholasTuttle** [comment]
I could be wrong, but I think you're severely underestimating the practicality of this request, particularly for SQL users.  SQL developers frequently need to open a new tab to look at a database table. They often have many of these tabs open at once. I think it would be very useful to have an option (in the settings) that will allow a user to close these tabs without being prompted to save them.

**Comment by me-nkr** [comment]
I do use vscode rest client extension to get a response, and I too think a shortcut to force close a file will be a useful one
