### ISSUE TITLE
I strongly recommend to remove the "drag and move folder" feature.

### ISSUE THREAD

**Issue by yaxinlx** [Microsoft/vscode#11046]
- VSCode Version:

1.4

- OS Version:

debian 8

Steps to Reproduce:

For many times, I didn't intend to drag and move a folder, but for whatever reason, maybe my mouse is too sensitive, a folder was moved. The moving process is so fast that I didn't notice it.
Some time later, I found the folder was missing. Ok, you know how confusing I am. ...

**Comment by bpasero** [comment]
As a workaround you can configure `explorer.enableDragAndDrop: false` to disable drag and drop.
