### ISSUE TITLE
paste in terminal only working when sidebar is toggled

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#110463]
- VSCode Version: 1.52.0-insider 050a123750e4ef4009930d0da1ff7a1a6441d4f3 x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Set setting `"terminal.integrated.localEchoLatencyThreshold": 0,`
1. Open Terminal and SideBar
1. Paste `git checkout feature/enc-1646-career-page-component-joblist6` into the terminal
1. It only shows `gtjbit etr/n-66cre-aecmoe`
1. Move the SideBar then it shows the full text

![bug](https://user-images.githubusercontent.com/23744935/98925923-e942c300-24d6-11eb-8808-0acdb8b371df.gif)
`

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
what happens if you set` "terminal.integrated.localEchoLatencyThreshold": -1`?

**Comment by meganrogge** [comment]
Thanks for the issue. I'm not able to reproduce it
![recording (37)](https://user-images.githubusercontent.com/29464607/98985774-e648d200-24d8-11eb-87fe-e636d570af9f.gif)

**Comment by connor4312** [comment]
Thanks for the issue. What shell are you using?

**Comment by connor4312** [comment]
Nevermind, I was able to repro this on plain bash

**Comment by SimonSiefke** [comment]
Well, that was fast. Thank you!
