### ISSUE TITLE
I want to delete completely

### ISSUE THREAD

**Issue by ViktorGalinger** [microsoft/vscode#110487]
Issue Type: <b>Bug</b>

Good day, my name is Victor. And I use your Visual Studio Code product very heavily. I have a problem on my Macbook Pro 2017. I want to completely (completely, with all the extra files that VSC created) delete VSC in order to re-configure it. Tell me how to delete all files.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|-psn_0_1769904 --crash-reporter-id b24aa117-dcaa-4257-98c7-e449be83e04c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color|ans|0.4.5
All-Autocomplete|Ati|0.0.23
bemhelper|Box|1.2.1
toggle-format-on-save|cbr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
jshint|dba|0.11.0
vscode-eslint|dba|2.1.13
ecsstractor-port|diz|0.0.3
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.2
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
beautify|Hoo|1.5.0
svg|joc|1.4.1
vscode-gutter-preview|kis|0.26.2
vscode-github|Kni|0.30.4
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.9.0
vscode-language-pack-ru|MS-|1.51.2
material-icon-theme|PKi|4.4.0
vscode-css-navigation|puc|1.9.0
vscode-scss-formatter|sib|2.0.2
vscode-multiclip|sle|0.1.5
sass-indented|syl|1.8.13
vscode-import-cost|wix|2.12.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.9.3

(5 theme extensions excluded)

</details>

**Comment by ACoderGuy23** [comment]
Do you have a folder that you keep your files in?

**Comment by ViktorGalinger** [comment]
> У вас есть папка, в которой вы храните файлы?

No. I want to uninstall and reinstall this application. Every time I delete an application, my data (extensions and settings) remains.

**Comment by usernamehw** [comment]
I think you can use commands that open folders and go up a directory a few levels and remove the `Code` and `.vscode` folders after running from Command Palette:

* `Developer: Open Logs Folder`
* `Extensions: Open Extensions Folder`

**Comment by ViktorGalinger** [comment]
> I think you can use commands that open folders and go up a directory a few levels and remove the `Code` and `.vscode` folders after running from Command Palette:
> 
> * `Developer: Open Logs Folder`
> * `Extensions: Open Extensions Folder`

Do I need to open Terminal? If so, what commands can you use to find these files?

**Comment by usernamehw** [comment]
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-palette

<kbd>F1</kbd> / <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>

**Comment by ViktorGalinger** [comment]
> https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_command-palette
> 
> F1/ Cmd+ Shift+P

Thank you so much. That helped!
