### ISSUE TITLE
VScode closes remembered tabs after timeout from SSH passphrase key prompt

### ISSUE THREAD

**Issue by zl0ty** [microsoft/vscode#110451]
- VSCode Version: 1.51.1 but it happened in 2 previous major releases
- OS Version: Windows 10

Steps to Reproduce:

1. Configure remote SSH host to use SSH key with passphrase
2. Open connection, type passhprase
3. Open couple of files in editor
4. Close editor
5. Open editor - it has your tabs opened and tries to establish connection, prompting for SSH key passhprase
6. Wait 2 minutes
7. Type passhprase
8. Error should appear: 'Could not establish connection to "<hostname>" The process tried to write to nonexistent pipe
9. Opened tabs are gone
10. Click retry button, type passhprase, tabs are still gone

Does this issue occur when all extensions are disabled?: No, because it requires remote-ssh  extension

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/110062
