### ISSUE TITLE
Jumping to the file in Explorer is not working after VS Code update

### ISSUE THREAD

**Issue by Delagardi** [microsoft/vscode#110409]
Issue Type: <b>Bug</b>

After updating to the new VS Code version, jumping to the open file in Explorer is not working. 

I checked `explorer.autoReveal` setting option and it sets to `true`. 

No any additional settings/extensions were added. 

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (3.02GB free)|
|Process Argv|--crash-reporter-id c67212d6-dacb-4b3e-87f2-c135c85e9069|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
swagger-viewer|Arj|3.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|10.2.3
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
vscode-graphql|Gra|0.3.11
plantuml|jeb|2.13.14
vscode-dbml|mat|0.3.4
dotenv|mik|1.0.1
vscode-csscomb|mrm|5.3.2
vscode-docker|ms-|1.7.0
remote-wsl|ms-|0.51.3
sqltools|mtx|0.23.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.4.0
vscode-yaml|red|0.12.0
LiveServer|rit|5.6.1
vscode-multiclip|sle|0.1.5
autoimport|ste|1.5.3
vsfire|tob|1.4.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.12.0

(1 theme extensions excluded)

</details>
 because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Maybe #110188 which is due to be fixed in upcoming recovery release

**Comment by Delagardi** [comment]
> For users coming to this issue to find more details: we will ship a fix for this issue in vscode stable this or next week.

Thanks a lot. 
If there are some way to roll up to the previous version of my VS Code for now?

**Comment by gjsjohnmurray** [comment]
> If there are some way to roll up to the previous version of my VS Code for now?

Download links are at the top of https://code.visualstudio.com/updates/v1_50

**Comment by gjsjohnmurray** [comment]
You'll also need to disable autoupdate, otherwise you'll soon be back on 1.51

**Comment by PhadesAlmaguer** [comment]
> > If there are some way to roll up to the previous version of my VS Code for now?
> 
> Download links are at the top of https://code.visualstudio.com/updates/v1_50

That works for me, thanks a lot

**Comment by gjsjohnmurray** [comment]
1.51.1 is now released, so I suggest you try that.
