### ISSUE TITLE
Timeline: investigate using `vscode.open` and `vscode.diff` as commands

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110496]
Similar to https://github.com/microsoft/vscode/issues/110397, would be great if our built-in timeline providers could use `vscode.open` and `vscode.diff` as commands if possible.

Once we did that, we need to do a similar change as `treeView` does here:

https://github.com/microsoft/vscode/blob/630e706ad2de99e255a18bf77f72d569e9fc0e49/src/vs/workbench/contrib/views/browser/treeView.ts#L468-L475

The fact that this is currently hardcoded inside `treeView` is a bit of a hack, but I am open for ideas how to make this cleaner once we use it in more places.

**Comment by bpasero** [comment]
Looks like the changes need to be made here:

https://github.com/microsoft/vscode/blob/0ac9d25b81e2a8afdfcd0511758beaf4cf859302/extensions/git/src/timelineProvider.ts#L171-L171

https://github.com/microsoft/vscode/blob/0ac9d25b81e2a8afdfcd0511758beaf4cf859302/extensions/git/src/timelineProvider.ts#L192-L192

https://github.com/microsoft/vscode/blob/0ac9d25b81e2a8afdfcd0511758beaf4cf859302/extensions/git/src/timelineProvider.ts#L210-L210

to use `vscode.open` and `vscode.diff`.

**Comment by bpasero** [comment]
@jrieken your change in https://github.com/microsoft/vscode/pull/110455/files to get the actual workbench command (`_workbench.open`) was not specific to custom trees right? It should work for any extension command that travels to the main side right?

**Comment by jrieken** [comment]
Yes, the `CommandConverter#toInternal`-function is doing this and believe every proper implementation uses that
