### ISSUE TITLE
SCM panel shows full directory path

### ISSUE THREAD

**Issue by jeffberry** [microsoft/vscode#110430]
Issue Type: <b>Bug</b>

After the latest Insiders update I am no longer able to see repository names in my Workspace because the SCM panel is now showing the full path to the git repository instead of just the repository (directory) name. This change requires the side panel to be obnoxiously wide in order to view the repository names and distinguish them from each other.

<img width="375" alt="Screen Shot 2020-11-11 at 12 49 52 PM" src="https://user-images.githubusercontent.com/3323635/98863497-52660000-241d-11eb-8f3b-0b6eefecac0e.png">

VS Code version: Code - Insiders 1.52.0-insider (40558fc8e13dbdceee5f4a9ad3fc661b9f8dae15, 2020-11-11T16:49:20.394Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.58-37.125.amzn2int.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.80GB free)|
|Process Argv|-psn_0_1397077|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 5.4.58-37.125.amzn2int.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (8 x 2719)|
|Memory (System)|59.86GB (15.30GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|2.0.0
emmet-jss|car|1.0.0
javascript-ejs-support|Dig|1.3.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
auto-rename-tag|for|0.1.5
vscode-react-typescript|inf|1.3.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
mdx|sil|0.1.0
jest-snapshot-language-support|tle|1.1.1
vscode-icons|vsc|11.0.0
jinja|who|0.0.8
material-theme|zhu|3.9.3
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
vscode-npm-script|eg2|0.3.13
vscode-brazil|mar|0.34.0
vscode-language-babel|mgm|0.0.30

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Is this remote SSH?

**Comment by jeffberry** [comment]
@joaomoreno yes, this is using Remote-SSH through the vscode-remote extension

**Comment by joaomoreno** [comment]
Even worse, this is in WSL:

![image](https://user-images.githubusercontent.com/22350/99059307-b49a3e80-259e-11eb-8ca1-1f39eb9de421.png)

**Comment by jeffberry** [comment]
This is working as expected now, thanks @joaomoreno!
