### ISSUE TITLE
Organize Imports Source Action is not an option

### ISSUE THREAD

**Issue by 72L** [microsoft/vscode#110424]
I am trying to use this documented feature called Organize Imports Source Action: https://vscode-eastus.azurewebsites.net/docs/languages/javascript#_organize-imports

However, the Source Action does not appear to be a menu option. When I search commands (cmd + shift +p, then search "organ") there are no search results that match.

- VSCode Version: 1.51.0
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Open a .js file
2. Right click anywhere (I clicked near the top, where I was importing)
3. See that there is no Source Action menu:
![image](https://user-images.githubusercontent.com/5567899/98857198-a3461a80-2456-11eb-8818-a3ccd33c0959.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by 72L** [comment]
I seem to have fixed it in the process of posting this Issue by disabling and then enabling all extensions. Steps:
1. Go to extensions pane
![image](https://user-images.githubusercontent.com/5567899/98857774-6fb7c000-2457-11eb-8608-39a1f49aae62.png)

2. Click on three dots > disable all extensions
![image](https://user-images.githubusercontent.com/5567899/98857866-9249d900-2457-11eb-8290-196d01cba7f0.png)

3. Reload

4. Click on three dots > enable all extensions
![image](https://user-images.githubusercontent.com/5567899/98857924-a8579980-2457-11eb-841e-5eb83376dedc.png)



Even though it's fixed this presents a buggy experience and should probably be addressed.

**Comment by mjbvz** [comment]
Do you have steps to reproduce the original problem?
