### ISSUE TITLE
After version 1.51.1 was updated, CPU usage gets higher

### ISSUE THREAD

**Issue by Ztachi** [microsoft/vscode#110448]
- VSCode Version:1.51.1
- OS Version:windows 1909

I just updated the version
![image](https://user-images.githubusercontent.com/6995332/98903134-f0c39580-24f1-11eb-82eb-e1b4371e0e48.png)
![image](https://user-images.githubusercontent.com/6995332/98903021-b954e900-24f1-11eb-9ca7-47da84e33322.png)

**Comment by alexdima** [comment]
Please follow the steps in https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu to provide additional details.

**Comment by Ztachi** [comment]
> Please follow the steps in https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu to provide additional details.


CPUs | Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.89GB (2.76GB free)
Process Argv | --crash-reporter-id 2d56c0a2-f5e1-475e-855d-36600566f5fd
Screen Reader | no
VM | 0%


CPU %	Mem MB	   PID	Process
    1	   100	 12980	code main
    0	    22	  6644	   utility
   13	    64	 11028	   shared-process
    1	   104	 14968	   gpu-process
    0	    25	 15516	   "C:\Program Files (x86)\SogouInput\9.6.0.3568\SGTool.exe" -daemon
    0	   237	 17520	   window (index.vue - code - Visual Studio Code [管理员] [不受支持])
    0	    24	  8588	     searchService
    0	    66	 15592	     watcherService 
    0	     4	  7092	       console-window-host (Windows internal process)
    0	   478	 15764	     extensionHost
    0	    22	  4956	       electron_node serverMain.js 
    0	    23	 14840	       electron_node server.js 
    0	   127	 15492	       electron_node tsserver.js 
    0	    40	 21428	         electron_node typingsInstaller.js typesMap.js 
    0	    28	 16680	       electron_node tsserver.js 
    0	    19	 16760	       electron_node server.js 
    0	    26	 20388	       "C:\Users\legen\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\legen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=15764
    0	    21	 20592	       "C:\Users\legen\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\legen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=15764
    0	    29	 20980	       electron_node server.js 
   47	  3754	 21240	       electron_node vueServerMain.js 
    0	     9	 19432	   crashpad-handler
    1	    62	 22064	   window (问题报告程序)


|  Window (index.vue - code - Visual Studio Code [管理员] [不受支持])
|    Folder (code): more than 20907 files
|      File types: svn-base(5675) png(3325) js(1702) java(833) css(610)
|                  jpg(420) html(393) class(374) xml(297) vue(273)
|      Conf files: package.json(30) grunt.js(4) launch.json(2) gulp.js(2)
|                  webpack.config.js(2) settings.json(1) tasks.json(1)
|                  jsconfig.json(1)
|      Launch Configs: node(4) chrome


Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
vscode-color | ans | 0.4.5
vscode-ant-design-vue-helper | ant | 1.0.6
All-Autocomplete | Ati | 0.0.23
path-intellisense | chr | 2.3.0
cocos-debug | Chu | 0.0.1
cocos-debug | Chu | 0.0.1
bracket-pair-colorizer | Coe | 1.0.61
vue-peek | dar | 1.0.2
githistory | don | 0.6.13
vscode-babel-coloring | dza | 0.0.4
vscode-html-css | ecm | 0.2.3
vsc-material-theme | Equ | 33.0.0
vsc-material-theme-icons | equ | 1.2.0
auto-close-tag | for | 0.5.9
auto-rename-tag | for | 0.1.5
vscode-nginx-conf-hint | han | 0.1.0
svgeditor | hen | 2.9.0
canvas-snippets | hol | 0.3.2
beautify | Hoo | 1.5.0
svg | joc | 1.4.1
vscode-pugbeautify | mrm | 1.0.2
vscode-language-pack-zh-hans | MS- | 1.51.2
debugger-for-chrome | msj | 4.12.11
awesome-flutter-snippets | Nas | 2.0.4
tslint-vue-tsx | nob | 1.0.0
korofileheader | OBK | 4.7.10
vetur | oct | 0.30.0
indent-rainbow | ode | 7.4.0
material-icon-theme | PKi | 4.4.0
nginx-formatter | ray | 0.0.11
any-rule | rus | 0.3.6
vue-vscode-snippets | sdr | 2.1.5
background | sha | 1.1.26
code-settings-sync | Sha | 3.4.3
vscode-nginx | sha | 0.6.0
markdown-preview-enhanced | shd | 0.5.13
html5-boilerplate | sid | 1.1.1
indenticator | Sir | 0.7.0
code-spell-checker | str | 1.9.3
open-in-browser | tec | 2.0.0
vscode-icons | vsc | 11.0.0
vscode-nginx | wil | 0.7.2
vscode-import-cost | wix | 2.12.0
JavaScriptSnippets | xab | 1.8.0

**Comment by alexdima** [comment]
@Ztachi I see a lot of CPU usage in:
 ```
47	  3754	 21240	       electron_node vueServerMain.js 
```

Does this high CPU usage reproduce when disabling all extensions (`F1 > Disable all installed extensions`)?

**Comment by Ztachi** [comment]
@alexdima 
Thanks for your answer. After investigation, I have found the reason.
If I disable [Vetur](https://github.com/vuejs/vetur), then CPU usage is normal.But this was an important extension, so I decided to temporarily reinstall VScode1.50.0

**Comment by Ztachi** [comment]
I think [Vetur](https://github.com/vuejs/vetur) should make some changes

**Comment by alexdima** [comment]
@Ztachi Thank you for tracking this down. Please open an issue directly against vetur.
