### ISSUE TITLE
Extension Host crashes on launch (with no enabled extensions)

### ISSUE THREAD

**Issue by hmelender** [microsoft/vscode#110465]
- VSCode Version: 1.51.1
- OS Version: Linux x64 4.19.0-11-amd64 (Debian)

Extension host crashes on launch (with no enabled extensions).

Steps to Reproduce:

1. Start VSCode

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Dev tools log hints at segmentation fault and/or memory leak.
[-1605175951244.log](https://github.com/microsoft/vscode/files/5529802/-1605175951244.log)

**Comment by alexdima** [comment]
@hmelender Could you please try with our [insiders version](https://code.visualstudio.com/insiders/)? Did VS Code ever work on this machine? Did you do something recently to your environment that might be causing this crash?
