### ISSUE TITLE
Hover Tooltip Menu are Blank

### ISSUE THREAD

**Issue by vintzl** [microsoft/vscode#110457]
- VSCode Version: 1.51.1
- OS Version: Debian x64

Since version 1.50.0-1602051089

Steps to Reproduce:

1. Hover menu
2. See the issue

![Peek 2020-11-12 08-01](https://user-images.githubusercontent.com/44751088/98914514-11c3c080-24c9-11eb-805c-c4218e0df40b.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
can you try launching vs code with the `--disable-gpu` flag?

**Comment by vintzl** [comment]
It is worst
![Peek 2020-11-12 19-39](https://user-images.githubusercontent.com/44751088/98986567-609f4380-2525-11eb-83de-84260b21635a.gif)

**Comment by sbatten** [comment]
ouch, i see. since @deepak1556 is not available right now, @bpasero anything with the electron upgrades?

**Comment by bpasero** [comment]
I don't think we updated Electron last release, but Deepak is back on Monday.

**Comment by vintzl** [comment]
Any news???
Now the issue is closed :s

**Comment by sbatten** [comment]
sorry for the automatic closure

**Comment by deepak1556** [comment]
Is vscode launched via remote X11 server ? Can you try launching with `--no-xshm` ?

**Comment by vintzl** [comment]
No, vscode  is launched via LXC containers.

Thanks, it works again with `--no-xshm`.

But why it is broken **only since** 1.50.0-1602051089

**Comment by deepak1556** [comment]
Its because of runtime upgrade, more context here https://github.com/microsoft/vscode/issues/101069#issuecomment-662150152

Merging to https://github.com/microsoft/vscode/issues/101069
