### ISSUE TITLE
HTML file is deleting indents and returns 

### ISSUE THREAD

**Issue by allanrivers** [microsoft/vscode#110484]
Issue Type: <b>Performance Issue</b>

Hello,

VS code is doing something weird in my HTML file. 

Whenever I press the tab key or space bar to indent or seperate children in internal css it's deleting the whitespace. It's working fine in CSS and JS files.

I basically can't use the tab or space bar to indent at all in any html file.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
prettier-vscode|esb|5.7.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details>

**Comment by aeschli** [comment]
Do you have `editor.formatOnType` or `editor.formatOnSave` enabled?

**Comment by allanrivers** [comment]
Yes, I had _editor.formatOnSave_ enabled. I ended up fixing it by factory resetting vs code. 
I then used the exact same settings and it worked perfectly fine.
