### ISSUE TITLE
Test: Open Editor sorting

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#110482]
Refs: https://github.com/microsoft/vscode/issues/12453

- [x] anyOS @RMacfarlane
- [x] anyOS @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23110482%0A%0A)

---

We have introduced a new setting `explorer.openEditors.sortOrder`: `editorOrder`, `alphabetical`
The sorting would only be done within editor groups. The sorting will only have an effect on the OPEN EDITORS view. It will not "move tabs" in any way. The default would be editorOrder and that is the current behavior.

Open quite some editors in multiple groups and verify:
* Open Editors view behaves as before and it always reflects the "truth" as seen in the tab order. 
* Change the `explorer.openEditors.sortOrder` to be `alphabetical`. Make sure that editors are sorted alphabetically in each group. Opening new editors sorts them in the appropriate order
* Actions in the Open Editors view behave as expected (context menu, `x` action)
* Drag and Drop in the Open Editors behaves as expected

**Comment by RMacfarlane** [comment]
Really nice!

**Comment by isidorn** [comment]
Thanks!
