### ISSUE TITLE
Collapse node_modules automatically

### ISSUE THREAD

**Issue by aamirafridi** [microsoft/vscode#110480]
Issue Type: <b>Feature Request</b>

In typescript projects we command click something and it opens the defination file. You move back to your source but the node_modules folder keeps opened. When you scroll on the files side bar, you have to scroll a lot to the top to collapse node_modules folder. Ideally it should collapse itself somehow

VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
We will not collapse node_modules automatically. This should be handled via https://github.com/microsoft/vscode/issues/87956

Thus closing as duplicate

**Comment by aamirafridi** [comment]
@isidorn  so what's the solution? explorer.autoReveal applys to all folders. How can I just make node_modules not expandable
comments on [this](https://stackoverflow.com/questions/51450945/typescript-in-visual-code-and-node-modules) suggests that it's not possible

**Comment by gjsjohnmurray** [comment]
> When you scroll on the files side bar, you have to scroll a lot to the top to collapse node_modules folder. Ideally it should collapse itself somehow

@aamirafridi if you first click on the focused entry in Explorer, then press your left-arrow key enough times, you will close node_modules without having to scroll.

**Comment by aamirafridi** [comment]
that's good to know but I wish there was a permanent feature for that. i.e. do not expand node_modules folder unless I click to expand it.
