### ISSUE TITLE
Cannot scroll above first line after switching tab with Find widget open

### ISSUE THREAD

**Issue by Simran-B** [microsoft/vscode#110470]
- **Version**: 1.52.0-insider
- **Commit**: 050a123750e4ef4009930d0da1ff7a1a6441d4f3
- **Date**: 2020-11-12T05:43:04.852Z
- **Electron**: 9.3.3
- **Chrome**: 83.0.4103.122
- **Node.js**: 12.14.1
- **V8**: 8.3.110.13-electron.0
- **OS**: Windows_NT x64 10.0.19041

This is a minor inconvenience I discovered when testing the fix for #40713, but I can observe this behavior in the 1.51.0 release version too.

Steps to Reproduce:

1. You need two arbitrary files or two unsaved documents.
2. Make sure word wrap is on by default or that the lines are short enough to not cause a horizontal scrollbar.
3. Make sure the Find widget is closed
4. Open the first file / activate the tab of the first document
5. Ctrl+F to open the Find widget
6. You can now scroll further up to potentially uncover text hidden behind the Find widget
7. Open the second file / active the tab of the second document
8. The Find widget is still open, but one cannot scroll above the first line of text
9. Scroll down, then up as well as closing and re-opening the Find widget or toggling its replace mode cause an update which then lets you scroll further up

Does this issue occur when all extensions are disabled?: Yes

![vscode_110470](https://user-images.githubusercontent.com/7819991/98934993-26ad4d80-24e3-11eb-81d2-6d25b6f5b0d1.gif)

**Comment by amunger** [comment]
this appears to be fixed
