### ISSUE TITLE
New extension API function for reloading file from disk

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#110493]
I'm writing an extension that performs some actions on the save chain process automatically. Some of the actions run external commands which edit the files outside of VSCode editor itself.

Because of that, VSCode warns the user that the file was changed in the disk and therefore stops the Save process. In my extension, the change of the file on disk was expected thus I indeed wanted VSCode to reload the file during its execution.

It seems that currently there is no API we can use to make VSCode reload the changes/accept the changes made in the external process.

![dhBDM1eRSZ](https://user-images.githubusercontent.com/29582865/98747718-d923ca00-2396-11eb-8497-f35b17d22bb4.gif)

References https://github.com/microsoft/vscode/issues/109500#issuecomment-725038446.

**Comment by bpasero** [comment]
Would this workaround help: https://github.com/microsoft/vscode/issues/7532#issuecomment-460158858

Just closed it as out of scope, so don't expect API anytime soon.

**Comment by felipecrs** [comment]
I had tried that workaround but it sadly does not help. It does not seem to make any difference.

**Comment by felipecrs** [comment]
It seems that the following snippet can work around the issue:

```typescript
const document = vscode.window.activeTextEditor?.document;
if (document) {
  await vscode.window.activeTextEditor?.edit((edit) => {
    edit.replace(
      new vscode.Range(
        document.lineAt(0).range.start,
        document.lineAt(document.lineCount - 1).range.end
      ),
      fs.readFileSync(document.fileName).toString()
    );
  });
}
```

**Comment by bpasero** [comment]
`workbench.action.files.revert` should work. It will force the active editor to read the contents from disk again and update the UI. It will not work for dirty files.

What you suggested as snippet is not ideal imho.

**Comment by felipecrs** [comment]
For some reason, `workbench.action.files.revert` does not work when running a `CodeActionsKind.Source` during the `editor.codeActionsOnSave` flow.
