### ISSUE TITLE
Ubuntu snap updates reset workspace

### ISSUE THREAD

**Issue by madprops** [microsoft/vscode#110442]
- Have vscode snap package installed
- It automatically/silently updates to new vscode version occasionally
- Open a new file through the command line, it opens a new vscode instance since it's a new version
- It's an instance with only 1 tab (the file I opened)

The problem is that the workspace is removed, the tabs and the workspace itself is gone.
So every time the snap updates I have to re-import the workspace and open tabs.
The recently open files is also gone so I can't easily restore relevant files.
The workspace is behind a symlink, in case that matters.

I know this is probably out of scope for vscode, but it shouldn't happen.

**Comment by joaomoreno** [comment]
Can you reproduce this reliably?

**Comment by joaomoreno** [comment]
This is https://github.com/microsoft/vscode/issues/15949
