### ISSUE TITLE
bug on visual code

### ISSUE THREAD

**Issue by neelgundelli** [microsoft/vscode#110406]
Issue Type: <b>Bug</b>

so I wanted to fix a error and a light bubble was there and clicked it and then I click the fix and cant undo it. So I was trying to fix it and still doesn't work.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     E7300  @ 2.66GHz (2 x 2660)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.85GB free)|
|Process Argv|--crash-reporter-id 528d87ff-7ffe-4e2c-9e93-ad2ccbee0f5c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
stories|ben|2.20.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.10.332292344
cpptools|ms-|1.1.1
vscode-yaml|red|0.12.0

</details>

**Comment by alexdima** [comment]
@neelgundelli  Can you please provide clear reproducible steps?
