### ISSUE TITLE
[Feature request] Add support for self defintion of file type group in 'Find in files'

### ISSUE THREAD

**Issue by DOGSHITD** [microsoft/vscode#110458]
Issue Type: <b>Feature Request</b>

Hello guys,

I suggest to add the feature that we can define file type group  in 'find in files', which is just like the function 'search project' in source insight. Then we can select the file type gourp by options box.
For example, there are c/c++/h/vfr/hfr files in my project(BIOS), c/c++/h is class c, vfr/hfr is class vfr, so I can define C group and vfr group, when i wan to find keyword in C group, i just need select it in options box in 'fines to include' of 'find in files'.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20530
