### ISSUE TITLE
In a multi-root workspace, cannot start two launch configs with the same name in different project folders simultaneously

### ISSUE THREAD

**Issue by mwpenny** [microsoft/vscode#110429]
- VSCode Version: 1.51.0 (also occurs on insiders)
- OS Version: Windows 10 (OS Build 17763.1518)

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create two new folders, `Project1` and `Project2`, each with the following launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug App",
            "type": "node",
            "program": "${workspaceFolder}/app.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ]
        }
    ]
}
```

it doesn't matter what the launch config is, but for the sake of this example, also create the following `app.js` in the root of each project folder so that it is valid:
```js
// Keep alive
setInterval(() => {}, 1 << 30);
```

2. Create a multi-root workspace and add both `Project1` and `Project2` to it.
3. Launch "Debug App (Project1)". Wait until the debugger attaches.
4. Try to launch "Debug App (Project2)". Nothing will happen.
5. If you rename the launch config in `Project2/.vscode/launch.json` to something else then you will be able to start it at the same time as Project1's launch config.

It seems that VSCode is comparing the names to check if a launch config has already been started, but it is not taking the project folder into account.

**Comment by isidorn** [comment]
Good catch. VS Code insiders will have the fix from tomorrow so you can try it out and let us know how it goes. Thanks

**Comment by mwpenny** [comment]
I tried out the latest insiders and the issue is fixed. Thanks for the quick response!

**Comment by isidorn** [comment]
Great, thanks for letting us know, adding verified label.
