### ISSUE TITLE
vscode

### ISSUE THREAD

**Issue by lvlvturancao** [microsoft/vscode#110466]
Issue Type: <b>Bug</b>

After the program is opened, the interface displays a mess, and prompts Your Code installation appears to be corrupt. Please reinstall, but it cannot be used normally after repeated reinstallation.
As is shown in the picture.
![image](https://user-images.githubusercontent.com/12148260/98928291-9851bf80-2514-11eb-95b5-789d22b3845a.png)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (2.79GB free)|
|Process Argv|--crash-reporter-id df529470-b2c5-42be-ae91-bafd3871bf8a|
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by lvlvturancao** [comment]
> 感谢您创建此问题！
> 
> 然而，由于您没有使用英语，我们很难进行处理。如果可能，请您将此问题描述修改为英文。请您直接编辑此问题，不要提交回复或新问题。
> 
> 请注意，机器翻译服务通常无法处理用于讨论软件问题所需的技术性语言，所以我们推荐您寻找一位熟悉相关技术的人来协助翻译。
> 
> 如果您无法做到，没有关系。此问题已经被标记为需要翻译，等待社区成员志愿进行翻译。
> 
> Thanks for creating this issue!
> 
> Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
> 
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
> 
> Otherwise, we have marked this as needing translation and a community member may be able to help out.

I have translated it into English. Please help.

**Comment by alexdima** [comment]
@lvlvturancao This looks like you have an installation problem. Please uninstall vscode and install it again. Do you have any antivirus that would be interfering with the vscode files ?

**Comment by lvlvturancao** [comment]
@alexdima  Thx for your answer, but I have repeated uninstalling and installing too many times， including trying x86 , x64，and even many sofrware  versions. I even cleaned the installation files and registy manually for many times during the time. Actually, It totally didn't work.
As for antivirus software，I use Huorong.VSCode could run well ago with it, and I have checked  logs, I think it's not the antivirus software's fault.

**Comment by alexdima** [comment]
@lvlvturancao This looks like a certain file `resources/app/out/vs/workbench/workbench.desktop.main.css` is corrupt on your machine. There is a process or some piece of software on your computer that is changing the contents of that file.

You can try getting the zip version and using a zip program compare the contents of the file on disk if it really matches with the contents of the file inside the zip.

@joaomoreno Do you have other ideas?

**Comment by joaomoreno** [comment]
You probably have an extension installed which does this. Can you check your `~/.vscode/extensions` folder? What extensions are in there?

**Comment by lvlvturancao** [comment]
> You probably have an extension installed which does this. Can you check your `~/.vscode/extensions` folder? What extensions are in there?

@joaomoreno  I had deleted all of the extentions and other related files as  I could see，including C:/Progarm files, Program files(x86),  ~/.vscode,  ~/AppData/Local, Roaming...
And then I reinstalled it,but didn't help.I also used CCleaner to clean the registries.
Too stange, but I really don't want to restore my computer.

**Comment by lvlvturancao** [comment]
> @lvlvturancao This looks like a certain file `resources/app/out/vs/workbench/workbench.desktop.main.css` is corrupt on your machine. There is a process or some piece of software on your computer that is changing the contents of that file.
> 
> You can try getting the zip version and using a zip program compare the contents of the file on disk if it really matches with the contents of the file inside the zip.
> 
> @joaomoreno Do you have other ideas?

It makes some sense. Ok, I will try to compare them and response you two days later ...

**Comment by lvlvturancao** [comment]
![image](https://user-images.githubusercontent.com/12148260/99209822-0e00a880-27ff-11eb-9e0d-8411f583db10.png


> @lvlvturancao This looks like a certain file `resources/app/out/vs/workbench/workbench.desktop.main.css` is corrupt on your machine. There is a process or some piece of software on your computer that is changing the contents of that file.
> 
> You can try getting the zip version and using a zip program compare the contents of the file on disk if it really matches with the contents of the file inside the zip.
> 
> @joaomoreno Do you have other ideas?

![image](https://user-images.githubusercontent.com/12148260/99209844-1d7ff180-27ff-11eb-8387-589d99e06601.png)
I have compared the two files and they are the same.

**Comment by joaomoreno** [comment]
Do you have issues with any other applications in your system? Other Electron apps for example?

**Comment by lvlvturancao** [comment]
> Do you have issues with any other applications in your system? Other Electron apps for example?

Nope，I  don't  use other electron apps. Actually I am not familiar with Electron apps...

**Comment by joaomoreno** [comment]
Are you in an enterprise environment?

**Comment by lvlvturancao** [comment]
> Are you in an enterprise environment?

@joaomoreno yep.

**Comment by joaomoreno** [comment]
Do your colleagues have similar issues? Can you ask your systems administrator to look into it?

**Comment by lvlvturancao** [comment]
> Do your colleagues have similar issues? Can you ask your systems administrator to look into it?

It works well in their computers...

**Comment by joaomoreno** [comment]
Got it. Is formatting your machine an option?
