### ISSUE TITLE
I'm a iMac OS X Yosemite and Visual Studio novice. Why can't I seem to install the VSCode app on this Mac?

### ISSUE THREAD

**Issue by JPRock** [Microsoft/vscode#11042]
- VSCode Version: VSCode-darwin-stable.zip
- OS Version: OS X Yosemite

Steps to Reproduce:
1. Download file.
2. Unzip file.
3. When the app icon is created, I drop it into Applications.
4. When I launch the app, I can briefly see it start on the Dock for a moment and then it's gone.

**Comment by rambul** [comment]
+1

For me it only shows is the taskbar but doesn't show the actual VS Code window :(

**Comment by JPRock** [comment]
@rambul When you refer to the “taskbar” are you referring to the MS Windows Taskbar or Mac OS X Dock? Is your issue a Windows or OS X one?

**Comment by joaomoreno** [comment]
@JPRock Can you simply double click the app before moving it into `Applications`?

**Comment by JPRock** [comment]
@joaomoreno When I download the "VSCode-darwin-stable.zip” file from Microsoft’s server, it goes into the “Downloads” folder by default. Then I extract the contents of the archive and a "Visual Studio Code.app" file is created.

I can double click the .app file from the Downloads folder and I’ll briefly see the icon appear and bounce a couple of times in the Dock. But from what I’ve read from online resources, you’re supposed to drag the *.app file to the “Applications” folder. I’ve tried so many combinations and have re-downloaded the original .zip file numerous times to no avail.

I’ve also posted this issue on the support.msdn.microsoft.com forum.

Perhaps I’m doing something wrong.

**Comment by joaomoreno** [comment]
Try running it from the Terminal. Open the `Terminal` application and execute the application from the command line:

```
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code --verbose
```

**Comment by JPRock** [comment]
@joaomoreno Thanks. I copied the command from your post and pasted it into the `Terminal` and nothing happened. How bizarre.

**Comment by JPRock** [comment]
@joaomoreno Furthermore, I `cd` to the `Applications` directory and then `ls` and can see all the apps installed including `Visual Studio Code.app`. I suspect Microsoft’s version of VS Code for Mac OS X is not complete.

**Comment by joaomoreno** [comment]
Can you [re-download](http://code.visualstudio.com/download), extract and double click that?
