### ISSUE TITLE
Adopt `vscode.open` or `vscode.diff` in built-in extensions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110497]
With https://github.com/microsoft/vscode/issues/85636 landed, it is now recommended that an extension sets the `TreeItem` command to `vscode.open` or `vscode.diff` if the resource is know upfront.

Example from ref view:

https://github.com/microsoft/vscode-references-view/blob/730800271aa5ef52b1c49608d68f14ee585f7821/src/calls/model.ts#L176-L186

List of extensions with custom views we ship:
* [x] JavaScript Debugger @connor4312 
* [x] JavaScript Perf View @connor4312 
* [x] NPM @alexr00 
* [x] References View @jrieken already did that to my knowledge

Git support is tracked in https://github.com/microsoft/vscode/issues/110397 and timeline in https://github.com/microsoft/vscode/issues/110496

//cc @isidorn @weinand not sure if debug has custom views where we should support this as well?

**Comment by isidorn** [comment]
Debug had loaded scripts view, but it is now in the vscode core. So we should be covered there.

**Comment by connor4312** [comment]
We have some views but don't open sources from them.

**Comment by alexr00** [comment]
NPM involves opening package.json files and finding specific scripts in them. Adopting `vscode.open` there should wait until https://github.com/microsoft/vscode/issues/110498

**Comment by bpasero** [comment]
@alexr00 can you clarify? at the time I have expanded the NPM tree to see scripts, we should have already resolved everything, no?

**Comment by alexr00** [comment]
The view uses `fetchTasks` to populate the tree view, which gives no information about where in the package.json file the task is coming from. The code can always be refactored to not do this, but it isn't just a simple adoption then.

**Comment by alexr00** [comment]
It probably should be refactored that way since it will be more efficient then.

**Comment by bpasero** [comment]
After a quick check, I think the only blocker is this code:

https://github.com/microsoft/vscode/blob/7b5849b123de0dbf1d0c7a21e3cc10cfa550746f/extensions/npm/src/npmView.ts#L198-L198

If the position was known upfront, this could be changed from:

https://github.com/microsoft/vscode/blob/7b5849b123de0dbf1d0c7a21e3cc10cfa550746f/extensions/npm/src/npmView.ts#L82-L86

to something like:

```ts
'open': {
	title: 'Edit Script',
	command: 'vscode.open',
	arguments: [uri, selection]
}
```

**Comment by alexr00** [comment]
That is correct.

**Comment by alexr00** [comment]
@connor4312 and @jrieken FYI I have made a test plan item for NPM scripts, but we will still need test items for the other extensions.

**Comment by jrieken** [comment]
I have a verificated-needed item for this

**Comment by bpasero** [comment]
I had this for my https://github.com/microsoft/vscode/issues/111417 already spelled out:

![image](https://user-images.githubusercontent.com/900690/100628576-a67f4880-3328-11eb-9ede-70e30cb5a79d.png)

Maybe I leave my thing in for SCM at least (@joaomoreno fyi)

**Comment by joaomoreno** [comment]
@bpasero I have this for Git/SCM: https://github.com/microsoft/vscode/issues/111519

**Comment by bpasero** [comment]
Ok good then I will simply remove that part from my test plan item, thanks for covering it in other issues 👍
