### ISSUE TITLE
How to open untitled file and add text content in it

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#11048]
There should be a small example to do this.
I also want to open the untitled file and add text content on it.

I have opened the JSON file by using this code

`var setting: vscode.Uri = vscode.Uri.file(en.APP_SETTINGS); vscode.workspace.openTextDocument(setting).then((a: vscode.TextDocument) => { vscode.window.showTextDocument(a, 1, false); });`

I get error 
>  cannot open 
untitled:c:/Users/shana/AppData/Roaming/Code/User/summary.txt. Detail: expected URI 
untitled:c:/Users/shana/AppData/Roaming/Code/User/summary.txt BUT GOT 
untitled:c:\Users\shana\AppData\Roaming\Code\User\summary.txt

How to open the untitled file and add text content in it ?

Please give the simplest code as example of provider is difficult to understand at first.

**Comment by faustinoaq** [comment]
You can try to analyze [this code](https://github.com/dkundel/vscode-new-file/blob/master/src/extension.ts#L13), looks pretty simple.
Also you can look inside some code beautifiers that already exist :-)
