### ISSUE TITLE
Terminal Height resizes when resizing editor

### ISSUE THREAD

**Issue by davidysoards** [microsoft/vscode#110499]
- VSCode Version: 1.51.1
- OS Version: Mac OS 10.15.7

Steps to Reproduce:

1. Add Keybindings for "workbench.action.increaseViewSize" and "workbench.action.decreaseViewSize"
I use the following:
```
    {
        "key": "ctrl+=",
        "command": "workbench.action.increaseViewSize",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+-",
        "command": "workbench.action.decreaseViewSize",
        "when": "editorFocus"
    },
```
2. Open 2 or more files/tabs and Split Left or Split Right.
3. Toggle Open the Terminal
4. Use keybindings to increase/decrease the focused editor

Prior to v1.51.1 resizing the editor did NOT affect the height of the terminal.
Using v1.51.1 or Insiders v1.52.0 the terminal now resizes instead of behaving like a fixed overlay like before.

Here is a screenshot using the latest insiders build with no extensions.

![viewsize-bug](https://user-images.githubusercontent.com/26875701/98967035-fa410380-24d9-11eb-8bf6-f8769ffa4ed4.gif)

possible related to this recently closed issue? #102954

Desired behavior is that the terminal does NOT resize.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@davidysoards with the new functionality of increasing width and height separately, you can use the commands:

```
    {
        "key": "ctrl+=",
        "command": "workbench.action.increaseViewWidth",
        "when": "editorFocus"
    },
    {
        "key": "ctrl+-",
        "command": "workbench.action.decreaseViewWidth",
        "when": "editorFocus"
    },
```

**Comment by davidysoards** [comment]
PERFECT! Thanks so much for the rapid response @sbatten !
