### ISSUE TITLE
NLS: Settings HTML indent option text illegible in german

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#110489]
- VSCode/OS Version:
   - Version: 1.51.1 (user setup)
   - Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
   - Datum: 2020-11-10T23:34:32.027Z
   - Electron: 9.3.3
   - Chrome: 83.0.4103.122
   - Node.js: 12.14.1
   - V8: 8.3.110.13-electron.0
   - Betriebssystem: Windows_NT x64 10.0.18363

Apparently, there must be some text in the Indent Inner HTML option description that's not correctly escaped:

![Option impaired](https://user-images.githubusercontent.com/9283914/98957886-fb862680-2501-11eb-8165-a72546996e04.png)

I guess, the same is true for the English language?

It reads: "Use to indent blocks of - and -."

**Comment by danyeh** [comment]
Following up. [336311]

**Comment by danyeh** [comment]
Fixed in v1.52.
