### ISSUE TITLE
Font color issue

### ISSUE THREAD

**Issue by robertoclavijob** [Microsoft/vscode#11043]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Create a .js file
2. Add multiple lines
3. Verify font colors

Expected result
The color font should be preserved

Actual result 
In some point all the fonts come in a same white color, if set all the code in a single line the colors are preserved

Some screenshots

![520_544](https://cloud.githubusercontent.com/assets/8324592/18025073/d2930578-6beb-11e6-83af-2ac4aa633868.jpg)
![544_568](https://cloud.githubusercontent.com/assets/8324592/18025074/d2935d3e-6beb-11e6-9a20-9ea278488d28.jpg)

**Comment by faustinoaq** [comment]
Cute [callback hell](http://callbackhell.com/) in the first screenshot XD

I have the same issue just when I scroll too fast large files, but after a seconds, looks ok again.
Maybe a performance issue?

**Comment by robertoclavijob** [comment]
when I checkout the code in other enviroment, xubuntu, I open the same file and had the same issue

**Comment by faustinoaq** [comment]
#9937

**Comment by sandy081** [comment]
@robertoclavijob This looks pretty similar to #9937. I am marking this as dup of #9937. I would suggest to subscribe to the original issue to be in loop. Thanks.

Duplicates #9937

**Comment by robertoclavijob** [comment]
ok thanks @sandy081 @faustinoaq
