### ISSUE TITLE
Case sensitive branch name not honoured

### ISSUE THREAD

**Issue by MC-8** [microsoft/vscode#110405]
- VSCode Version: 1.51.0
- OS Version: Window 10 (build 19041.572)

Steps to Reproduce:

1. Create branch with name "Branch" on GitLab
2. Create branch with name "branch" on GitLab
3. In VSCode, checkout branch "branch"
4. In VSCode, try to checkout branch "Branch"
5. The following error should appear:
fatal: A branch named 'Branch' already exists.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
This is because branches in git are stored as files on disk and you're on a case insensitive file system (windows). This is a git limitation, nothing to do with VS Code.
