### ISSUE TITLE
Debug widget shadow is very extreme

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110422]
![image](https://user-images.githubusercontent.com/323878/98854239-26dc1900-240f-11eb-9545-f3c27aa4d05a.png)

It seems like this doesn't show up in the screenshot that well? But in the Monokai theme, the shadow is much darker than usual...

**Comment by roblourens** [comment]
Insiders on top, stable on bottom

![image](https://user-images.githubusercontent.com/323878/98854389-59861180-240f-11eb-97bf-99e93ee1d2c4.png)

**Comment by isidorn** [comment]
@misolori also assigning to you just to check if you have changed the shadows a bit (which I know you did for quick pick)

**Comment by misolori** [comment]
I tweaked the shadow properties and made the shadow a bit more transparent for the monokai theme:

![image](https://user-images.githubusercontent.com/35271042/98973743-ff498700-24c8-11eb-9583-b65a024af340.png)
