### ISSUE TITLE
Default python interpreter is syncing between devices, which it shouldn't

### ISSUE THREAD

**Issue by mjbeyeler** [microsoft/vscode#110490]
- VSCode Version: 1.51.1
- OS Version: OS X Catalina / Ubuntu 20.04 LTS

Steps to Reproduce:

1. Turn on syncing all settings
2. change default python interpreter in one OS, and it will also change on the other

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
You can manually ignore this setting to sync if you want, otherwise file an issue against python extension to make that setting machine scoped.

**Comment by mjbeyeler** [comment]
> You can manually ignore this setting to sync if you want, otherwise file an issue against python extension to make that setting machine scoped.

OK great! But there are only 5 boxes to check or uncheck in the option "Settings Sync: Configure..."

How would I uncheck something as specific as "default python interpreter"?

**Comment by sandy081** [comment]
Please refer - https://code.visualstudio.com/docs/editor/settings-sync#_configuring-synced-data

**Comment by mjbeyeler** [comment]
Okay, thanks! I have just disable sync on this device for now. Seems the less complicated.
