### ISSUE TITLE
Add variable to tasks.json for filename without extension

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1104]
Like `${fileBasename}`, but without the extension. Use case is I want to write a task configuration to run JUnit tests in Java (besides other tasks). My tasks.json:

``` json
{
    "version": "0.1.0",
    "isShellCommand": true,
        "suppressTaskName": true,
    "linux": {
        "command": "sh",
        "args": ["-c"]
    },
    "windows": {
        "command": "cmd",
        "args": ["/C"]
    },
    "tasks": [
        {
            "taskName": "JUnit Test",
            "args": ["java org.junit.runner.JUnitCore ${fileBasename}"],
            "isTestCommand": true
        }
    ]
}
```

(I'm using the workaround described in #981, but this is unrelated)
The task is supposed to run JUnit test for the currently opened file. The problem is, JUnit expects a class name, not a file name. So instead of MyTest.java I need to pass just MyTest. Please add a variable like `${fileBasenameWithoutExtension}`.

**Comment by felixfbecker** [comment]
I found a temporary workaround: 
```powershell
$class = [System.IO.Path]::GetFileNameWithoutExtension('${fileBasename}'); java org.junit.runner.JUnitCore $class
```

**Comment by isidorn** [comment]
We have introduced `${fileBasenameNoExtension}`
@gregvanl could you please document this in our docs for subsitituting variables?

**Comment by felixfbecker** [comment]
This is still not documented: https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution

**Comment by isidorn** [comment]
@felixfbecker just created https://github.com/Microsoft/vscode-docs/issues/690
