### ISSUE TITLE
Git commit message box hitbox does not match cursor

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/vscode#110473]
Issue Type: <b>Bug</b>

Recently, when trying to edit a git commit message, I often find myself entering a search filter in the tree view instead of entering the commit message itself.
I think the problem is best shown in a short clip:

![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/17641229/98940622-8c9dd300-24eb-11eb-8f7e-8f3d103e1ec2.gif)

Notice how the cursor switches to the textbox caret, but clicking does not actually select the textbox.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (13.94GB free)|
|Process Argv|--crash-reporter-id 334f021d-210d-4760-a7f9-f7e771ce0905|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.15.1
RunOnSave|eme|0.2.0
json-tools|eri|1.0.2
prettier-vscode|esb|5.7.2
vscode-pull-request-github|Git|0.21.0
vscode-test-explorer|hbe|2.19.3
rest-client|hum|0.24.4
template-string-converter|meg|0.2.8
compare-folders|mos|0.18.0
vscode-docker|ms-|1.7.0
vscode-language-pack-de|MS-|1.51.2
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.3
hexeditor|ms-|1.3.0
vscode-js-profile-flame|ms-|0.0.13
vsonline|ms-|1.0.3075
hide-gitignored|npx|1.1.0
vscode-jest|Ort|3.2.0
typescript-mono-repo-import-helper|q|0.0.6
project-snippets|reb|0.5.0
java|red|0.70.0
vscode-sort-json|ric|1.18.1
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-icons|vsc|11.0.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/108160
