### ISSUE TITLE
Can't download extension:c/c++ for vsc

### ISSUE THREAD

**Issue by rotaercl** [Microsoft/vscode#11054]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by rotaercl** [comment]
always remain downloading

**Comment by faustinoaq** [comment]
Can you show us the installation logs?

I'm using C/C++ extension in Manjaro Linux KDE and works well.

Can you try to install manually on Windows via git?

**Comment by joaomoreno** [comment]
Are you behind a proxy?
