### ISSUE TITLE
Only auto-open release notes for major releases

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#110511]
As far as I learned so far, recovery releases trigger opening the release notes. The notes are the same as before but with a newly added line about the minor version bump and a link to github issues.

For the [August release](https://code.visualstudio.com/updates/v1_49), this meant that occasional users got to see the release notes 4 times.

To avoid making the release notes a nuisance and ensuring that are a monthly positive occasion, I propose to limit them to major releases.

**Comment by roblourens** [comment]
Is it even possible to verify this in insiders? Maybe with package/product.json hacks?

**Comment by joaomoreno** [comment]
Absolutely! Change the version in `package.json` ;)

**Comment by roblourens** [comment]
I can do that and I get release notes in that case, but I think I can't simulate a minor-version update to verify that I don't get release notes

**Comment by roblourens** [comment]
By minor in this case I mean x.y.0 -> x.y.1

**Comment by joaomoreno** [comment]
Oh because we are on 0. 😆 

In that case just code review, please.
