### ISSUE TITLE
Files exclude not being read by intellephense

### ISSUE THREAD

**Issue by publiclass1** [microsoft/vscode#110557]
We have written the needed data into your clipboard 
Issue Type: <b>Bug</b>

I am working with php laravel project when I exclude the vendor folder just to get rid it in the sidebar view. The intelliphense not working and it was labelled all classes from vendor `red`.

# To Reproduce
- Add files exclude vendor folder
- Close vscode and see the read marks error even not autocomplete

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.57GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/publi/Documents/Commonality/commonality-native-app --crash-reporter-id 20aa41eb-fc99-4ebe-b27a-fb54c7eafdc3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
yet-another-phpunit|dan|1.1.1
gitlens|eam|10.2.3
EditorConfig|Edi|0.15.1
code-runner|for|0.11.1
phpcs|ika|1.0.5
vscode-docker|ms-|1.7.0
remote-wsl|ms-|0.51.3
color-highlight|nau|2.3.0
vetur|oct|0.30.1
vscode-jest|Ort|3.2.0
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.3

</details>
because it was too large to send. Please paste.

**Comment by alexdima** [comment]
Please report directly against intelliphense .
