### ISSUE TITLE
Recent open folders list reset after every restart in Mac

### ISSUE THREAD

**Issue by ayush987goyal** [microsoft/vscode#110542]
Issue Type: <b>Bug</b>

1. Open some folders in vs code.
2. Restart the device.
3. Most of the folders are removed from the recently opened folders list.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 11, 6|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|-psn_0_151589 --crash-reporter-id 5c993764-e398-4e5a-9ed9-c3a25817d635|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.4.3
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
EditorConfig|Edi|0.15.1
debugger|eff|1.3.42
prettier-vscode|esb|5.7.2
auto-rename-tag|for|0.1.5
vscode-styled-components|jpo|1.2.0
vscode-language-babel|mgm|0.0.30
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.7.0
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vscode-yaml|red|0.12.0
LiveServer|rit|5.6.1
rust|rus|0.7.8
crates|ser|0.5.3
svg-preview|Sim|2.8.3
svelte-vscode|sve|102.5.1
rust-pack|Swe|0.2.29
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by ayush987goyal** [comment]
This is not a duplicate of the above mentioned issue.

**Comment by ayush987goyal** [comment]
Hi, any update on this issue? I am seeing this constantly after every restart.

**Comment by sbatten** [comment]
@ayush987goyal I have not seen this or other reports of it. is there anything additional you can share that might make your setup unique? e.g. you say most of the recent folders, but not all? also, do you have VS Code installed in you applications folder?

**Comment by ayush987goyal** [comment]
Yes VS Code is installed in the applications folder. Is that a concern?

What more information do you need from my side (which is not already a part of the issue template)

**Comment by sbatten** [comment]
Can you provide more details on which folders disappear and which do not?
