### ISSUE TITLE
Visuals keep freezing, but app works & can save

### ISSUE THREAD

**Issue by lilithebowman** [microsoft/vscode#110582]
Issue Type: <b>Bug</b>

In PopOS I can save but not see anything on the screen. It is only recently that this seems to happen.

The visuals will crash, and if I move the window it corrupts the display.

If I close and re-open the application it works again for a while, and then freezes the visuals.

I am using PopOS inside VirtualBox using the extensions & VMSVGA adapter.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.8.0-7625-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (4 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|7.77GB (0.67GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6bd2b1d7-a71b-4d68-94ef-524c6af6d3aa|
|Screen Reader|no|
|VM|29%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|0.2.3
prettier-vscode|esb|5.7.2
phpcs|ika|1.0.5
vscode-docker|ms-|1.7.0
csharp|ms-|1.23.5
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
cpptools|ms-|1.1.1
prettier-vscode|Sim|2.0.7
twig|wha|1.0.2

</details>

**Comment by deepak1556** [comment]
Can you see if the issue goes away by disabling gpu acceleration following https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by lilithebowman** [comment]
I did disable acceration and it works fine for now. Why is it failing for PopOS clients?

**Comment by lilithebowman** [comment]
Oh sorry I disabled acceleration in the VM not VSCode

**Comment by deepak1556** [comment]
Not sure, gpu support comes from chromium. There are cases where some drivers won't work well and chromium would blocklist them by default. This is just a missing blocklist case. Closing as mitigated.
