### ISSUE TITLE
The C/Cpp Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by wuzhijiexia** [Microsoft/vscode#11059]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Install C/C++ extension
2. Started the extension then the error appear
3. Can't go to definition and declaration

**Comment by mrmlnc** [comment]
Please move this issue into repository of C/C++ extension: https://github.com/Microsoft/vscppsamples/issues.

![chrome_2016-08-29_01-11-18](https://cloud.githubusercontent.com/assets/7034281/18037142/a827bcd4-6d85-11e6-960a-74ffe90ad745.png)

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscppsamples#178
