### ISSUE TITLE
Release notes should have a visible way to opt-out

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110507]
Since we open release notes (by default) on each release, there should be a visible way to opt-out. Either a checkbox similar to the Welcome experience, or a markdown command link.

re: https://twitter.com/seldo/status/1326224452472860673

**Comment by misolori** [comment]
I think having a setting to toggle this would be best. The release notes is just a markdown preview so we can't add any UI elements to it, unlike the Welcome page which is different.

**Comment by eamodio** [comment]
We do have a setting already `update.showReleaseNotes`, but we have LOTS of settings. Even though it is markdown, we could still add a command link to the text that would run a new command to toggle the setting.

**Comment by misolori** [comment]
I don't know, this seems pretty obvious:

![image](https://user-images.githubusercontent.com/35271042/98978884-7124cf00-24cf-11eb-92cb-93dea4b274c4.png)

**Comment by eamodio** [comment]
Its friction -- if the release notes pops up and aggravates me, I have to take much extra energy to go looking for the setting (even though it is an easy one to find)

**Comment by misolori** [comment]
I could see maybe adding a menu item in the ... in the top right, but doubt that is discoverable. Placing it inside of the preview feels a bit odd like an unsubscribe link.

**Comment by digitarald** [comment]
On the constrain of adding UI to the notes: The relnotes manager output already has a patch that runs to [change keybinding codes](https://github.com/microsoft/vscode/blob/2db5a355bc355ca7f1bea4078ea2f0d4263d71e3/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L153) and handles [clicks](https://github.com/microsoft/vscode/blob/2db5a355bc355ca7f1bea4078ea2f0d4263d71e3/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L182-L186). Might the same be used to inject an opt-out checkbox or link inside the header?

A common UX to test would be a "Don't show again" link/button we have in notifications (and elsewhere?).

**Comment by connor4312** [comment]
One heuristic could be that if we see the release notes are closed within 5 seconds of them opening, we show a notification asking the user if they want to hide them in the future.

The downside is that it trades release note fatigue for notification fatigue 😛

**Comment by joaomoreno** [comment]
I totally agree. Just not sure of the right UX here.

**Comment by misolori** [comment]
Here's a simple option that shows the text + action at the top:

> Don't want to see release notes after an update? You can always [disable them]() in your user settings.

![image](https://user-images.githubusercontent.com/35271042/100131068-66a3f700-2e38-11eb-95fa-5fa0a88264c4.png)

**Comment by joaomoreno** [comment]
I like the checkbox since it's a pretty standard way of doing this... Maybe at the top (2) is best?

**Comment by digitarald** [comment]
When #110511 lands, a wording could be *"Show release notes for monthly updates."* to indicate the monthly frequency to set expectations.

**Comment by eamodio** [comment]
I prefer # 2

**Comment by sana-ajani** [comment]
Another tweet about this: https://twitter.com/diracdelta/status/1333206472864382976

I prefer #3 because it aligns with how we show the checkbox for the welcome page too.

**Comment by ItalyPaleAle** [comment]
I prefer # 3 too because it does not interrupt the flow for people reading the release notes

**Comment by Eskibear** [comment]
Currently `update.showReleaseNotes` is of "application" scope ([HERE](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/platform/update/common/update.config.contribution.ts#L47-L52)), meaning that I cannot set it to "false" in `settings` section of a [devcontainer.json](https://code.visualstudio.com/docs/remote/devcontainerjson-reference) file. Can it be `window` scope?

It's slightly different from the original topic. Let me know if you want me to open a separate issue for it.

**Comment by joaomoreno** [comment]
👀 

![Recording 2022-12-09 at 16 13 06](https://user-images.githubusercontent.com/22350/206733319-c2f01ad8-4f03-4042-953a-8e805fb7b12b.gif)

**Comment by daviddossett** [comment]
IMO it should at least be under the `h1` or under the first paragraph. Agreed that it feels like it breaks the layout.

**Comment by joaomoreno** [comment]
👀 

![image](https://user-images.githubusercontent.com/22350/207614060-dee4a90e-c0c8-4fab-817c-2a778b0c6482.png)

**Comment by isidorn** [comment]
This looks better to me. Thanks 👏
