### ISSUE TITLE
Using Shift + Alt + Arrow for box select

### ISSUE THREAD

**Issue by kevlut** [microsoft/vscode#110596]
I was used to Notepad++ box select feature using Shift + Alt + Arrow buttons.  In VS Code, you are required to use the mouse to create the box.  This is not expert user friendly IMO.  Can there be an option/feature added so I can alternatively use my arrow keys instead of mouse?

**Comment by alexdima** [comment]
By default, you can use `Ctrl + Shift + Alt + Arrow` buttons. If you don't like that default, you are free to create keybindings rules that suit your need, e.g.:

```
{ "key": "shift+alt+down", "command": "cursorColumnSelectDown", "when": "textInputFocus" },
{ "key": "shift+alt+left", "command": "cursorColumnSelectLeft", "when": "textInputFocus" },
{ "key": "shift+alt+pagedown", "command": "cursorColumnSelectPageDown", "when": "textInputFocus" },
{ "key": "shift+alt+pageup", "command": "cursorColumnSelectPageUp", "when": "textInputFocus" },
{ "key": "shift+alt+right", "command": "cursorColumnSelectRight", "when": "textInputFocus" },
{ "key": "shift+alt+up", "command": "cursorColumnSelectUp", "when": "textInputFocus" },
```
