### ISSUE TITLE
Connecting to a git remote repository

### ISSUE THREAD

**Issue by mwberlindeu** [microsoft/vscode#110500]
I am trying to add a remote git repo within the Git: Add Remote function in VS Code.

The following output is generated:
git remote add origin/master https://[some URL]
...
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '**--**' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]

It appears that "origin/master" may not be picked correctly and that the '**--**' are not set internally by VS Code which may be required. Although I could not confirm this syntax on git-scm / github.

If I use another name, e.g. "test", I get the same error message with "master" as name. Thus it seems that I cannot override the "master" name.

**Comment by joaomoreno** [comment]
> git remote add origin/master https://[some URL]

Can you show me a screenshot of that exact output?

**Comment by mwberlindeu** [comment]
The remote name is "master" (but I have also tried others. Iam getting the following output:

> git remote add master 	 https://something/git/something
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template

Note that "master" is indeed a valid branch.
