### ISSUE TITLE
Partial performance of Intellisense in the workspace

### ISSUE THREAD

**Issue by AquariusStar** [microsoft/vscode#110591]
Translate.
First, I created a workspace. Then I added three project directories to the workspace, one of which connects to two projects. The problem is this. Intellisense only works in one workspace directory. And according to the list in JSON, it is the last one. But if you don't open the workspace, but only the directory where the three project directories themselves are located, then Intellisense works in all directories, and they see each other.

**Comment by AquariusStar** [comment]
All three directories with separate projects. They are located in the General directory. The shared directory has a .code-workspace file, where these three directories are added to "folders". And Intellisense only works in one of them. I assumed that this is an error in the work of add-ons or incorrect operation of components. But the problem remained on the other computer.

`"folders": [
    {
        "path": "Service.TCP" // intellisense not working (main)
    },
    {
        "path": "Service.IO.UART" // intellisense not working
    },
    {
        "path": "Service.Device.Control" // intellisense working
    }
],`

**Comment by mjbvz** [comment]
Fill in the issue template and provide steps to reproduce the issue. For example, you never said what language this is in

**Comment by AquariusStar** [comment]
I write in C# / .NET Core (it doesn't depend on the version). Using a Microsoft C# add-on with the latest version of omnisharp loaded. VS Code latest version.
To reproduce the problem, you just need to create two different dotnet projects. The first project is created as a library. And the second one is a program that connects to the library. Each project is located in its own directory. And the two directories will be in the shared directory. And the shared directory contains the .code-workspace file (an example is shown in the previous comment), these two projects will be connected to the shared workspace.
In my implementation: two projects ("Service. IO. UART" and " Service.Device.Control") are libraries for the "Service.TCP" project.

**Comment by mjbvz** [comment]
Thanks. Please file this against the c# extension

 /extC#
