### ISSUE TITLE
Intellisense menu only shows one option at a time

### ISSUE THREAD

**Issue by EOussama** [microsoft/vscode#110554]
- VSCode Version: 1.51.1
- OS Version: Windows_NX x64 10.0.19041

Steps to Reproduce:

1. Trigger Intellisense

Does this issue occur when all extensions are disabled?: Yes
Yes

![image](https://user-images.githubusercontent.com/22644543/99047652-caa30180-2594-11eb-9b64-6229a13cfdfa.png)

**Comment by jrieken** [comment]
Did you by any chance resize the widget while it was showing a single suggestion? Can you try "F1 > Reset Suggest Widget Size" and check if the widget size is back to normal?

**Comment by EOussama** [comment]
> Did you by any chance resize the widget while it was showing a single suggestion? Can you try "F1 > Reset Suggest Widget Size" and check if the widget size is back to normal?

Yes, it was a resizing problem, after all, however, this seemed to have been the case ever since the last update this past couple of days. I do not recall resizing it manually at all.

**Comment by oodavid** [comment]
I've been having the same issue over the past week.

The `Reset Suggest Widget Size` fix has worked for me.

From the about menu:

```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:14:40.758Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by ruaanvds** [comment]
So, `Reset Suggest Widget Size` does fix the issue, but just like @EOussama I didn't resize the widget manually - this just happened after a recent release.

**Comment by jrieken** [comment]
Ok, I found this way to reproduce this

* run the `Reset Suggest Widget Size` command or start with fresh user data dir
* trigger suggest so that it shows a single suggestion
* resize the width (or, alternatively, single click the bottom sash)
* :bug: bad size is being stored

**Comment by jrieken** [comment]
I am pushing a change for the aforementioned scenario. This will be in next insiders. Please try it out and let me know if you have another scenario in which an unwanted height is stored.
