### ISSUE TITLE
False Errors

### ISSUE THREAD

**Issue by Kanishk951** [microsoft/vscode#110547]
Issue Type: <b>Bug</b>

I am a game dev student using Unity Game Engine. I was not using VS Code for a long time because of its weird issue. I was working on a console application just to practice my C# skills. While editing that I found that wierd issue where the errors shown are false. Then i ignored it and started working on my game project, then I saw that the issue persists here. I tried reinstalling vs code and switching to an old version but nothing solved it. And I also see most of the time intellisense not working. The intellisense starts working after 10 to 15 minutes but its kinda frustrating to wait 15 minutes just to see intellisense work. I am not a single person facing this issue. You can search on internet and can see thousands of people suffering from this issue. Because of such issues people are shifting to rider and visual studio. Visual Studio is very heavy that is why I am tring to shift to vs code but these issues always force me to change my code editor. 

THESE ERRORS SHOULD BE ASAP TO SAVE PEOPLE TO CHANGE THEIR CODE EDITOR.

Sometimes I feel that even notepad is better than VS CODE.

Good luck !
Kanishk

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.06GB free)|
|Process Argv|K:/Kanishk Main Folder/Kanishk Dhindsa/games/RPG Project -g K:\Kanishk Main Folder\Kanishk Dhindsa\games\RPG Project\Assets\Scripts\Attributes\HealthDisplay.cs:1:0 --crash-reporter-id 5083839c-66d7-42db-9246-b4bc7bbb2210|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.21.0
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.5
unity-debug|Uni|3.0.2
vscode-icons|vsc|11.0.0

</details>

**Comment by Chokoretto** [comment]
Disabling the extension, reloading the editor and reenabling the extension fixed it for me.
