### ISSUE TITLE
Terminal links that contain a space break the markdown link handling

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110509]
![image](https://user-images.githubusercontent.com/641685/98978544-282d4480-24e8-11eb-8b58-55c2ea25b201.png)

**Comment by rzhao271** [comment]
@eamodio On stable when I try typing `git log`, the underline only shows up under `log`.

**Comment by Tyriar** [comment]
@rzhao271 you would need to create a link provider extension that creates a link out of "git log". I can verify this one.
