### ISSUE TITLE
API commands debt

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#110583]
VS Code has API commands like `vscode.open` or `vscode.executeCompletionItemProvider`. We call them "API commands" because they accept and return types from the API, like `vscode.TextDocumentShowOptions` etc. Know that in theory all our commands are API - keybindings, executeCommandApi, or menus depend on them but the most don't accept arguments and are therefore simpler to handle. 

API commands (those with arguments/return-types from the API) are usually defined inside `src/vs/workbench/api/common/extHostApiCommands.ts` and they usually have a counter part in the renderer. The counter part is doing the actual work while api command transforms api-types to internal-types and back. For instance the `vscode.executeDocumentHighlights`-command transforms `vscode.Uri` and `vscode.Position` into `URI` and `IPosition` before calling `_executeDocumentHighlights` and then transforms the result `modes.DocumentHighlight[]` into `vscode.DocumentHighlight[]`. Because of these transformations api commands are implemented in the extension host which has full access to the API types. 

There also exists `src/vs/workbench/api/common/apiCommands.ts` which is for commands that are implemented in the extension host _and_ in the renderer. This is due to a specific bug fix where some API command references would escape the extension host, namely when command-links are used in markdown. We are now in a state where we can fix this bug better but it appears that `apiCommands` became popular and needs to be clean-up first. 

Ask yourself the following questions and act accordingly

#### Does my API command use types from the API?

* `YES` 👉 use [`ExtHostCommands#registerApiCommand`](https://github.com/microsoft/vscode/blob/f3efe70c9a061955ffb50c61fd5ec5801b614910/src/vs/workbench/api/common/extHostCommands.ts#L99) to register your command. A popular place is still `extHostApiCommands.ts` but in fact you can (and likely should) use it from anywhere, like within your feature area. 

* `NO` 👈 register your command in the renderer via [`ICommandRegistry#registerCommand` ](https://github.com/microsoft/vscode/blob/18945092df3d0c16af75ff9befc62eff70d80129/src/vs/platform/commands/common/commands.ts#L54) (just like any other command). Be nice and add command description and validate ([sample](https://github.com/microsoft/vscode/blob/f3efe70c9a061955ffb50c61fd5ec5801b614910/src/vs/workbench/api/common/extHostCommands.ts#L99)). 

---

- [x] OpenFolderAPICommand @bpasero 
- [x] NewWindowAPICommand @aeschli 
- [x] OpenWithAPICommand @mjbvz 
- [x] RemoveFromRecentlyOpenedAPICommand @aeschli 
- [x] OpenIssueReporter @RMacfarlane 
- [x] SetEditorLayoutAPICommand @bpasero 
- [x] MoveViewsAPICommand @eamodio 
- [x] OpenAPICommand @jrieken 
- [x] DiffAPICommand @jrieken

**Comment by jrieken** [comment]
> Does my API command use types from the API?

Answer this question with `NO` when yous command expects arguments but when those are outside the APIs, like primitives or simple object literals

**Comment by bpasero** [comment]
@jrieken to clairfy, both my `SetEditorLayoutAPICommand` and `OpenFolderAPICommand` already use `CommandsRegistry.registerCommand`. Do I still need to do anything? Move them to a different file?

**Comment by jrieken** [comment]
Yes - remove [this](https://github.com/microsoft/vscode/blob/f3efe70c9a061955ffb50c61fd5ec5801b614910/src/vs/workbench/api/common/extHostApiCommands.ts#L385) then and move the command metadata into "the one" place. Also, consider to move the command into its feature layer

**Comment by bpasero** [comment]
Ok I have changes in https://github.com/microsoft/vscode/pull/110714, please let me know if that is what you had in mind

**Comment by jrieken** [comment]
ping @eamodio

**Comment by jrieken** [comment]
ping @eamodio

**Comment by eamodio** [comment]
Fixed mine in https://github.com/microsoft/vscode/commit/a6e6e1f70b3276e5c555c47153ff59aae9830cc2

**Comment by jrieken** [comment]
Last round for `_extensionTests.getLogLevel` and `_extensionTests.setLogLevel`. @bpasero please move those command into a more domain-specific place, after that we can delete `apiCommands.ts`

**Comment by bpasero** [comment]
@joaomoreno I also had to move your `_workbench.fetchJSON` command, so please check that out:

https://github.com/microsoft/vscode/blob/0804afd00ee8e993494386ab32b2c15719bc1749/src/vs/workbench/services/request/browser/requestService.ts#L48-L59

(from https://github.com/microsoft/vscode/commit/d60dbbf646ae6a1affe0de44538a9a294e7a3399#diff-9bc927a30b92207292bb17a10e58c2ffe05cc22d5ea5ddcd7595cb19dbe50696)
