### ISSUE TITLE
Color Themes Not Working On Big Sur

### ISSUE THREAD

**Issue by exitfish** [microsoft/vscode#110578]
Issue Type: <b>Bug</b>

After updating to Big Sur, all of my color themes are not working, and all code is black. I have tried restarting VS Code and restarting my machine, but neither has made a difference.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 3|
|Memory (System)|16.00GB (3.79GB free)|
|Process Argv|--crash-reporter-id d9c5e1c5-67e2-4b90-814a-3b9c69d40cca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
html-slim-scss-css-class-completion|gen|1.7.7
vue|jcb|0.1.5
forcecode|Joh|3.22.9
change-string-case|max|1.1.2
theme-monokai-pro-vscode|mon|1.1.17
vscode-react-native|msj|1.1.1
language-liquid|nei|0.1.1
nunjucks|ron|0.3.0
salesforcedx-vscode-core|sal|50.5.0
salesforcedx-vscode-visualforce|sal|50.5.0
material-theme|zhu|3.9.3

(5 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Are you using Source Code Pro by any chance? (#100840)

**Comment by exitfish** [comment]
> Are you using Source Code Pro by any chance? (#100840)

@alexdima yes I am!

**Comment by exitfish** [comment]
I found the problem. It was in the settings.json file:
`"editor.autoIndent": false,`
was showing an error. 

After changing this to:
`"editor.autoIndent": "none",`
everything works.

**Comment by exitfish** [comment]
I also had to switch to font other than Source Code Pro.

**Comment by davelaser2** [comment]
Anyone still having this issue, I uninstalled the font, re-downloaded, then installed both regular and medium weights & set `"editor.fontWeight": "500"` and it's back!

**Comment by andyd0** [comment]
That didn't seem to do it for me so switched to Hack for now

**Comment by zhboner** [comment]
I switched from source code variable (which causes this issue) to source code pro, and solve this problem. 

You may consider using the latest version. The link to the latest version is [https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro/1.052R-it/1.012R-VAR](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro/1.052R-it/1.012R-VAR)
