### ISSUE TITLE
On MacOS Big Sur the title bar looks ugly

### ISSUE THREAD

**Issue by coderdiaz** [microsoft/vscode#110544]
- VSCode Version: 1.51.1
- OS Version: MacOS 11.0.1

Steps to Reproduce:

1. Go to user settings.
2. Change the `Title Bar Style` to `custom`.
3. The title bar looks ugly.

![twitter_95e7305ff648ba935937c704a5d72f84](https://user-images.githubusercontent.com/1901273/99033675-0d3aee80-2541-11eb-9416-f32dfab5acf4.jpeg)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aaronfulkerson** [comment]
I'm also seeing this issue on a totally fresh install of Big Sur and Code.
