### ISSUE TITLE
Large text output kills the notebook

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#110581]
Issue Type: <b>Bug</b>

1) Open the attached notebook using the Jupyter preview editor

[loop17MBoutput.ipynb.zip](https://github.com/microsoft/vscode/files/5537750/loop17MBoutput.ipynb.zip)

VS Code version: Code - Insiders 1.52.0-insider (40558fc8e13dbdceee5f4a9ad3fc661b9f8dae15, 2020-11-11T16:49:20.394Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|-psn_0_8189903 --crash-reporter-id d4b72415-0109-45b3-a1a7-967fdd12f0f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.2
git-branch|ale|1.6.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3
tsl-problem-matcher|eam|0.3.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
graphviz-markdown-preview|gee|0.0.8
vscode-pull-request-github-insiders|Git|2020.11.15362
mdmath|goe|2.5.1
crazy|kie|0.0.2
svgpreview|kis|0.2.0
rainbow-csv|mec|1.7.1
theme-monokai-pro-vscode|mon|1.1.17
vscode-docker|ms-|1.7.0
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.149.0
remote-ssh-edit-nightly|ms-|2020.11.15361
remote-ssh-nightly|ms-|2020.11.15361
remote-wsl|ms-|0.51.3
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2020.11.1117
vscode-github-issue-notebooks|ms-|0.0.58
vscode-js-profile-flame|ms-|0.0.13
vscode-markdown-notebook|ms-|0.0.13
vsonline|ms-|1.0.3075
material-icon-theme|PKi|4.4.0
ruby|reb|0.27.0
vscode-xml|red|0.14.0
vscode-ruby|win|0.27.0

(4 theme extensions excluded)

</details>

**Comment by rebornix** [comment]
The slowness is caused by browser attempting to render large DOM nodes or too many DOM nodes. To mitigate this issue, we can build up some heuristics about when to truncate the outputs.
 
**_Single large text output_**, size limit 65535 bytes:

```
"outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "01234567891011121314......",
     ]
  }
]
```

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/876920/99310669-3218b580-2810-11eb-8215-8f11f4c5a383.png">

**_Single text output with too many lines_**, line limit 500:

```
"outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0",
      "1",
      "2",
      "3",
...
      "10000",
     ]
  }
]
```

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/876920/99310861-8328a980-2810-11eb-9b14-adeb201bdab6.png">

**Comment by rebornix** [comment]
Currently when users click "show more...", it opens an untitled editor. We can improve this experience once we get some feedback.
