### ISSUE TITLE
processId is not captured for python

### ISSUE THREAD

**Issue by Alexandros1987** [microsoft/vscode#110563]
Issue Type: <b>Bug</b>

Using the following json, processId cannot be picked anymore after updating to version 1.51 for python:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ]
}

Inserting an hardcoded process ID value like "processId": "3000" instead of "processId": "${command:pickProcess}" debugger is able to work as usual.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (6.58GB free)|
|Process Argv|W:\software --crash-reporter-id 2b341085-cb34-4f0f-8279-eac05d2ec306|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
cpptools|ms-|1.1.1
notepadplusplus-keybindings|ms-|1.0.5

</details>

**Comment by weinand** [comment]
"pickProcess" is the Python process picker.
