### ISSUE TITLE
[Request] ViewColumn value of ExistingOrActive

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#110537]
In the C/C++ Extension, we have a feature "Switch Header/Source".  If in a source file, it will navigate to a header of the same name but different extension, or vice versa.

We've had a number of issues reported due to the behavior of this feature when both of these files are already open, in different 'columns'.  If not visible (topmost) in a column, we cannot find it, as it's not in the list of `visibleTextEditors`, so we do not know what `ViewColumn` to pass to `showTextDocument`.  As a result, the user winds up with an additional instance of the file open, in the active column.

This request is for an additional enum value in `ViewColumn` of `ExistingOrActive`, which will bring the file to the foreground in the column it is already open in, or fall back to opening a new instance of the file in the active column.  (Or some comparable feature that might address this issue, such as access to arrays of file URIs associated with each column).

**Comment by jrieken** [comment]
Know tabs (active and inactive) will be part of https://github.com/microsoft/vscode/issues/15178. 

closing as duplicate
