### ISSUE TITLE
Allow the option of auto-sorting the open files name in tabs and open files list by name (and other attributes e.g. location, size, type,...)

### ISSUE THREAD

**Issue by arabed** [microsoft/vscode#110530]
Allow the option of auto-sorting the open files name in tabs and open files list by name (and other attributes e.g. location, size, type,...).
This is going to be a very useful feature when you are working in C/C++ and any other languages which need to see the relevant files close to each other. As an example in C/C++ this will keep the source (e.g. foo.cpp) and header file (e.g. foo.hpp) next to each other both in open files tabs and open files list.

**Comment by gjsjohnmurray** [comment]
Sorting of the Open Editors list is coming. See #110482
