### ISSUE TITLE
Typing a comment sentence ending with a period activates intellisense

### ISSUE THREAD

**Issue by martinduo** [microsoft/vscode#110502]
Issue Type: <b>Bug</b>

I'm working on a node v12 js project. Whenever I type a comment and end it with a period and 'Enter', I get unwanted characters appended. For example:

// this is a sentence.

Ends up like this:

// this is a sentence.abs

How can I stop this?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.09GB free)|
|Process Argv|--crash-reporter-id f5f038f7-3efb-4ff4-be89-497ca282d4cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
vscode-rbxlua|Ama|0.5.0
jest-snippets|and|1.8.0
snapshot-tools|asv|0.4.0
markdown-checkbox|bie|0.1.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.13
vscode-quick-select|dba|0.2.9
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.7.2
vscode-rojo|eva|1.12.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
JavaScriptSnippetsStandard|jms|1.8.0
vscode-styled-components|jpo|1.2.0
vscode-icon-theme|jtl|1.6.6
roblox-lua-autofills|Kam|1.7.1
selene-vscode|Kam|1.0.2
node-module-intellisense|lei|1.5.0
git-graph|mhu|1.27.0
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-scss|mrm|0.9.0
vscode-azurefunctions|ms-|1.0.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.0
vscode-dotnet-runtime|ms-|0.2.0
azure-account|ms-|0.9.3
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.2.3
azurerm-vscode-tools|msa|0.13.0
debugger-for-chrome|msj|4.12.11
reload|nat|0.0.6
lua-indent|rin|0.0.1
code-settings-sync|Sha|3.4.3
vscode-stylelint|sty|0.85.0
lua|sum|1.0.3
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
roblox-lua|Und|1.0.4
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
gitdoc|vsl|0.0.6
wallaby-vscode|Wal|1.0.248
disable-eslint-rule|Woo|0.0.2
vscode-wrap-console-log-simple|woo|1.6.9
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by martinduo** [comment]
No, it does not happen using VSC insiders, with all extensions still
enabled. When will that fix appear in the normal release?

**Comment by mjbvz** [comment]
It's likely one of your extensions then since we haven't changed anything related to intellisense triggering recently.

Try tracking own which one is causing this and file the issue against them
