### ISSUE TITLE
Text are not displayed appropriately in macOS 11.0.1 if font family was "Source Han Code JP"

### ISSUE THREAD

**Issue by yudai1202** [microsoft/vscode#110552]
Issue Type: <b>Bug</b>

It's my first time to make an bug report, so I'm sorry if the place is wrong.

I updated my MacOS to version 11.0.1.

I opened vscode and my screen looks like the image below.

![image](https://user-images.githubusercontent.com/22557372/99043724-fb555c00-25d1-11eb-918b-d9a683520444.png)

The settings for'font family'at this time are as follows.
```
"editor.fontFamily": "'Source Han Code JP', Menlo, Monaco, 'Courier New', monospace"
```

When I deleted the part of'Source Han Code JP', it was displayed well.

![image](https://user-images.githubusercontent.com/22557372/99043793-16c06700-25d2-11eb-94f2-143056db45cd.png)

```
"editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace"
```

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 5|
|Memory (System)|32.00GB (2.10GB free)|
|Process Argv|--crash-reporter-id ea582d33-1edd-4cf6-bd14-268196ade0bd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.2
whitespace-plus|dav|0.0.5
vscode-eslint|dba|2.1.13
githistory|don|0.6.13
gitlens|eam|10.2.3
prettier-vscode|esb|5.7.2
vscode-firefox-debug|fir|2.9.1
vscode-drawio|hed|1.0.3
marp-vscode|mar|0.16.0
git-graph|mhu|1.27.0
zenkaku|mos|0.0.3
vscode-docker|ms-|1.7.0
vscode-language-pack-ja|MS-|1.51.2
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
remote-wsl|ms-|0.51.3
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
markdown-preview-enhanced|shd|0.5.13

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Related - #100840

**Comment by alexdima** [comment]
@yudai1202 Is "Source Han Code JP" related in some way to "Source Code Pro" ?

**Comment by yudai1202** [comment]
Yes.
Source Han Code JP seems to be based on Souce Code Pro.

Below is a quote from README from Source Han Code JP repository.
> Source Han Code JP is a derivative of Source Han Sans that replaces its proportional Latin glyphs with fixed-width 667-unit glyphs from Source Code Pro. 

https://github.com/adobe-fonts/source-han-code-jp#source-han-code-jp

**Comment by alexdima** [comment]
Let's track in #100840
