### ISSUE TITLE
R file icon for file explorer

### ISSUE THREAD

**Issue by xmha97** [microsoft/vscode#110512]
I use R lang on a daily basis. I want to have an icon for the R file type (.r) visible in the file explorer.
![image](https://user-images.githubusercontent.com/23485114/98984415-6b62d400-2537-11eb-9f29-3a9f10b18fd1.png)

Please check the below file: 👇
[fix.zip](https://github.com/microsoft/vscode/files/5532760/fix.zip)

**Comment by misolori** [comment]
Thanks for the suggestion but we're currently not adding any new system file icons, please see https://github.com/microsoft/vscode/issues/60699#issuecomment-429208011.
