### ISSUE TITLE
Problems without column information are always shown as column 1,1

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#110561]
VSCode Version: 1.15.0

Steps to Reproduce:

1. Run with any problemmatcher that does not provide a specific column 8but file and line)
2. ProblemPane shows the File, and underneath all Problems for that, all with the position [line, 1]
3, the editor renders the error as underlined of col 0.

Does this issue occur when all extensions are disabled?: Yes

Expected behavior:

1. ProblemPane shows only "Problem [line]", instead of "Problem [line, 1]"
2. Editor underlines the complete line (ideally from first to last non-space)

**Comment by alexr00** [comment]
> 1. ProblemPane shows only "Problem [line]", instead of "Problem [line, 1]"

A column always shown in the problems panel, so have the column shown there is by design. 

> 2. Editor underlines the complete line (ideally from first to last non-space)

This is currently possible! Simple set the `location` of your problem matcher to be the same value as the `line`: 
```json
    "problemPatterns": [
      {
        "name": "tsc",
        "regexp": "^([^\\s].*)[\\(:](\\d+)[,:](\\d+)(?:\\):\\s+|\\s+-\\s+)(error|warning|info)\\s+TS(\\d+)\\s*:\\s*(.*)$",
        "file": 1,
        "line": 2,
        "severity": 4,
        "code": 5,
        "message": 6,
        "location": 2
      }
    ],
```

**Comment by GitMensch** [comment]
Good to see that `location` works and from git blame the part was also in the docs when I've created that issue back in 2020. Thanks for pointing that out - I'm adjusting a bunch of definitions now :-)

To be specific: in this case `line` should be _replaced_ by `location` if there is no separate `column` or it matches the common location:

> - If the problem `location` is line or `line,column` or `startLine,startColumn,endLine,endColumn`, then our generic location match group can be used.

Still - the "column 1" (what the issue is about) is confusing

> A column is always shown in the problems panel, so have the column shown there is by design.

Hm, then I suggest to not default the column to 1 but to zero - and in the UI consider a design change "if column is zero don't show it". Even without the design change a column zero is much more clear "is related to the whole line", then the 1.

@alexr00 Would you consider reopening this issue for that part?

**Comment by alexr00** [comment]
@sandy081 for the problems view: would you consider not rendering a start column in the view if the start column of the marker is 0?

**Comment by sandy081** [comment]
Not inclined to do as it causes inconsistency in UI and I think its good to show what the model has instead of hiding it. If data is invalid, probably it shall not be allowed in to the model.

**Comment by GitMensch** [comment]
> if data is invalid, probably it shall not be allowed in to the model.

The point here is that currently a not-correct column 1 is inserted into the model and of course the UI shows what the model has. The idea is to change the model to get a not-wrong column zero inserted - and the question is: What could the UI show in this case?
To me it would be ideal if in this case no column would be rendered at all leaving only the correct line in the model to be rendered.

**Comment by sandy081** [comment]
> The idea is to change the model to get a not-wrong column zero inserted - and the question is: What could the UI show in this case?

IMO UI shall show what the model has especially we have multiple UIs rendering diagnostics. 

CCing @jrieken for model change

**Comment by sandy081** [comment]
> The idea is to change the model to get a not-wrong column zero inserted - and the question is: What could the UI show in this case?

IMO UI shall show what the model has especially we have multiple UIs rendering diagnostics. 

CCing @jrieken for model change
