### ISSUE TITLE
Only extensions that are available to vscodium are visible

### ISSUE THREAD

**Issue by Twiggeh** [microsoft/vscode#110599]
- VSCode Version: 1.50.1-1
- OS Version: manjaro 5.8

Steps to Reproduce:

1. Install it after using vscodium

Does this issue occur when all extensions are disabled?: No

Can be solved if I find out where the product.json is

**Comment by tamuratak** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by Twiggeh** [comment]
The solution to this would be to say whether there is a product.json and where its located to set the stores url and not a "please ask microsoft nicely to release their packages on the OpenVSX"
