### ISSUE TITLE
The snap should use its own packaged libgl drivers rather than those from the system

### ISSUE THREAD

**Issue by MarcusTomlinson** [microsoft/vscode#110564]
- VSCode Version: 1.51.1 (snap)
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install Flutter and create a test app:
```
snap install flutter --classic
flutter channel dev
flutter upgrade
flutter config --enable-linux-desktop
flutter create my_app
```
2. Install the [Dart Code extension](https://github.com/Dart-Code/Dart-Code).
3. Open the `my_app` directory you created in step 1.
4. Navigate to `/lib/main.dart`, and click "Run" above `void main()`.
5. Error:
```
libEGL warning: MESA-LOADER: failed to open xxxxx (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
@MarcusTomlinson On thing I don't understand: that warning comes from Code itself, or the flutter app?

**Comment by MarcusTomlinson** [comment]
> @MarcusTomlinson One thing I don't understand: that warning comes from Code itself, or the flutter app?

Definitely from Code, otherwise [this](https://github.com/microsoft/vscode/pull/110565/files) would have no effect.

**Comment by joaomoreno** [comment]
What I am wondering is why is that warning coming up when you click `Run` above `void main()`. What happens when you do that? Does Dart open up some special UI inside VS Code that makes VS Code load up libgl?

**Comment by MarcusTomlinson** [comment]
We're talking about the snap here right, because the application is launched with Code as it's host process, it's launched within its environment.

The issue here stems from the fact that the snap is built from Ubuntu 16.04 packages, and is being run unconfined on 20.04+, where the newer drivers are now incompatible. When Code attempts to use those drivers is crashes (as described above), so we need to ensure that it doesn't use those system-provided drivers, but its own instead.

**Comment by joaomoreno** [comment]
> When Code attempts to use those drivers is crashes

My question was rather: what in your repro steps exactly makes code use those drivers?

**Comment by MarcusTomlinson** [comment]
It's the Flutter application that requires those drivers. Because the application is launched within Code's runtime environment, it's looking for the dependancies it needs from there.

I do see the issue though - why is Flutter using the old GTK libs from within Code in the first place, when really it should be using _its_ own... I'll dig deeper to see if this really is a Code issue and not a Flutter one. So sorry for the misunderstanding.

**Comment by joaomoreno** [comment]
Yeah I really don't think it's correct that Flutter should use the libs from inside Code's snap, that doesn't sound right.

**Comment by joaomoreno** [comment]
@MarcusTomlinson Any findings?

**Comment by MarcusTomlinson** [comment]
Hi sorry yes, I managed to get the flutter snap to behave by fiddling with its environment. Still need to clean it up and publish, but anyway it’s apparently not a VS Code issue.
