### ISSUE TITLE
Extension installation fails with ETIMEDOUT/ECONNREFUSED on 1.51.1

### ISSUE THREAD

**Issue by EricHripko** [microsoft/vscode#110574]
- VSCode Version: 1.51.1 / e5a624b788d92b8d34d1392e4c4d9789406efe8f / x64
- OS Version: MacOS 10.15.3

Steps to Reproduce:

1. Place computer behind a firewall that blocks direct connections to the Internet 
2. Run `code --install-extension ~/Downloads/extension.vsix --disable-telemetry` to install an extension from a local file

Previously, this command succeeded:
```
$ code --install-extension ~/Downloads/extension.vsix --disable-telemetry
Installing extensions...
Extension 'extension.vsix' was successfully installed.
```

On the latest version, this command fails:
```
$ code --install-extension ~/Downloads/extension.vsix --disable-extensions --disable-telemetry
Installing extensions...
(node:12020) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'extension.vsix' was successfully installed.
connect ETIMEDOUT 13.107.42.18:443
```

The extension appears to be installed successfully, but the command still exits with non-zero return code due to that connection failure. Based on #98496, https://marketplace.visualstudio.com appears to correspond to `13.107.42.18:443` address. I believe it should be possible to install local `.vsix` extensions without VSC trying to reach MS services.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Leletir** [comment]
Hi, thank your for the fix !
Do you know in which release this fix is going to be deployed ?
