### ISSUE TITLE
The text in VScode cannot be copied to other software

### ISSUE THREAD

**Issue by LayTonQ** [microsoft/vscode#110538]
- VSCode Version:1.51.0
- OS Version:Windows 10 10.0.18363 （1909）

Steps to Reproduce:

1. Copy the text from VScode to VScode, it can copy successfully, there is no content in the system clipboard.
![image](https://user-images.githubusercontent.com/37096930/99021023-b3ffa900-259a-11eb-861c-00e81d67d3f1.png)

2. Copy the text from Vscode to Notepad, it can copy successfully, there is no content in the system clipboard.
![image](https://user-images.githubusercontent.com/37096930/99022381-92ec8780-259d-11eb-8822-1febbe3e94cf.png)

3. Copy the text from Notepad to VScode, it can copy successfully, there is content in the system clipboard.
![image](https://user-images.githubusercontent.com/37096930/99022534-dfd05e00-259d-11eb-81cd-9b57329f55f1.png)

4. Copy the text from VScode to all other software, such as: Word, Excel, Chrome, Edge, copy is unsuccessful, there is no content in the system clipboard.
When the text was copied from VSCode, Excel was unable to operate for about 15 seconds and was stuck.
![image](https://user-images.githubusercontent.com/37096930/99022811-4a819980-259e-11eb-8858-ae47fb4a0438.png)

5. Copy text from other software into VScode, it can be copied successfully. There is content in the system clipboard.
![image](https://user-images.githubusercontent.com/37096930/99022992-a0564180-259e-11eb-8de1-9386669313f2.png)

6. This issue only appears on this computer, not on other computers.

Uninstall VSCode and reinstall, but the issue still exists.

Uninstall VSCode and install the previous version of VSCode, the issue still exists.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
This might be about the HTML clipboard content, perhaps we write an empty content to the clipboard?

**Comment by LayTonQ** [comment]
Secure encryption software causes this problem
