### ISSUE TITLE
Cannot copy/paste from Ubuntu VSCode into virtual machine guests

### ISSUE THREAD

**Issue by SomeGuy54321** [Microsoft/vscode#11051]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Get a Ubuntu 16.04 PC
2. Install VSCode
3. Setup two VMware Player (v12.1.1 build-3770994) machines
   - OSX 10.11
   - Windows 10
   - install VMware Tools in both
4. Open a guest
5. Copy something from the editor of the Ubuntu VSCode
6. Try to paste it anywhere in the guest (won't work)
7. Go back to host
8. Paste the text somewhere (will work, i.e. the text is in the clipboard)
9. Copy that SAME text from wherever you pasted it in the host
10. Paste it anywhere in the guest (will work this time, oddly)

Steps 9-11 show the simple workaround: Copy the text from VSCode, paste in a text editor, copy that, paste in the guest machine.

A very minor but odd issue.

Probably worth listing my VSCode extensions:
- Visual Studio Code Settings Sync 2.0.6
- Python 0.3.21
- C/C++ 0.8.1
- C# 1.3.0
- vscode-icons 1.8.1

**Comment by faustinoaq** [comment]
Can you try to copy/paste with chromium?

I'm using VSCode in VirtualBox with Archlinux and the clipboard works fine.

**Comment by alexandrudima** [comment]
I'm also suspecting this is a Chromium / Electron issue

**Comment by alexandrudima** [comment]
@SomeGuy54321 Can you please try Copy/Pasting in Chrome or Chromium so we can determine if it is a Chromium issue?

**Comment by SomeGuy54321** [comment]
Sorry about the delay here, I just downloaded and installed `code_1.5.2-1473686317_amd64.deb`, updated all my extensions, and the issue's still exactly as I described. Copy/paste from Chromium is fine (Chrome as well FWIW).

**Comment by alexandrudima** [comment]
@SomeGuy54321 Can you also try with a clean installation of vscode. `vscode-icons` has been causing many issues and grief for us.
