### ISSUE TITLE
Missing lookup references/implementations on variable in tsx file inconsistently

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#110524]
Creating this issue on behalf of @alcheim

- VSCode Version: VSCode 1.51.1
- OS Version: Windows 10 build 19042.630

Steps to Reproduce: (bug is not consistent)

"I'm in a tsx file and sometimes when I right click a variable, the context menu only gives me option to change occurrences and not look up the references and implementations. I have to restart vscode to get the correct context menu back."

1. Open up a tsx file
2. Right click on a variable. Context menu missing options to see references or implementations.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/12758612/98998424-f79ada00-24ea-11eb-9aed-94158768f18b.png)

3. Restart vscode to see the options appear again.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/12758612/98998452-ff5a7e80-24ea-11eb-9b2b-431ec03fd47f.png)

4. Inconsistent behavior that happens frequently.

Does this issue occur when all extensions are disabled?: Yes/No

Unsure

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by alchiem** [comment]
The repro is pretty inconsistent and I don't have the repro steps

**Comment by mjbvz** [comment]
Did you test on insiders with extensions disabled?
