### ISSUE TITLE
File Browser Disappears

### ISSUE THREAD

**Issue by adunham95** [microsoft/vscode#110523]
Issue Type: <b>Bug</b>

Sometimes the file browser will disappear from the side.
When I switch to any other item on the sidebar the file browser icon disappears.
If I quit the program and restart it will come back. 

VS Code version: Code - Insiders 1.52.0-insider (050a123750e4ef4009930d0da1ff7a1a6441d4f3, 2020-11-12T05:43:04.852Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.64GB free)|
|Process Argv|--crash-reporter-id 9e63c5ec-74d9-4263-89d5-aedf1e3ebc2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.13
githistory|don|0.6.13
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.2
vscode-graphql|Gra|0.3.11
beautify|Hoo|1.5.0
vscode-jetbrains-keybindings|isu|0.1.9
search-node-modules|jas|1.3.0
vscode-styled-components|jpo|1.2.0
rainbow-csv|mec|1.7.1
dotenv|mik|1.0.1
remote-wsl|ms-|0.51.3
vsliveshare|ms-|1.0.3121
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
code-settings-sync|Sha|3.4.3
snipsnap-vscode|sni|1.1.0
autoimport|ste|1.5.3
code-spell-checker|str|1.9.3
open-in-browser|tec|2.0.0
gitblame|wad|6.0.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details>

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/99019959-84e83800-2598-11eb-99af-61ae9e57c1bc.png)

Right click the activity bar, and make sure "explorer" is checked.

**Comment by isidorn** [comment]
Exactly. Also I can not reproduce this. Make sure to disable all your extensions.
Thus closing
