### ISSUE TITLE
Refactoring option: Move function (variable, etc.)

### ISSUE THREAD

**Issue by HolgerSeith** [microsoft/vscode#110551]
I think there should be a refactoring option in VSCode to move a function (variable, etc.) to a different existing file.
In my case: For JavaScript. 
IMHO such refactoring options are essential for an efficient development.

(it looks like webstorm has such an option: https://www.jetbrains.com/help/webstorm/specific-javascript-refactorings.html#javascript_move_refactorings)

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/29988
