### ISSUE TITLE
VSCode v1.51.1 User for Window. Intellisense only show 1 suggestion.

### ISSUE THREAD

**Issue by gdheller42** [microsoft/vscode#110513]
- VSCode Version: 1.51.1
- OS Version: Window 7 64bit

Steps to Reproduce:

1.Open Angular 8 or 10 typescript file
2. In a method type this.  Only one suggestion shows up.

This works fine on version 1.50.1.
 I have uninstalled v1.51.1 and reinstalled v1.50.1 intellisense working as expected

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by mjbvz** [comment]
Is there only one suggestion or is there only one visible suggestion? Have you tried [resizing the suggestions](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions)?

**Comment by ember91** [comment]
This happened to me. Only one intellisense suggestion. It turned out the window had been resized to only show one item, as mjvbz mentioned.

**Comment by gdheller42** [comment]
> Is there only one suggestion or is there only one visible suggestion? Have you tried [resizing the suggestions](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions)?

Thanks that was what it was. Suggest setting a reasonable default size to start!
Thanks Again.. (I Love VSCode)
-Greg

**Comment by gdheller42** [comment]
Solution was resize suggestion. Closing

**Comment by ethicalduty** [comment]
> Is there only one suggestion or is there only one visible suggestion? Have you tried [resizing the suggestions](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions)?

Life savior!
