### ISSUE TITLE
vscode doesn't start with ulimits

### ISSUE THREAD

**Issue by graph** [microsoft/vscode#110535]
- VSCode Version: 1.50
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. set ulimits, I have it set to 7GB. I have the following set in limits.conf.
```
*                hard    nproc           1000
*                hard    as              7340032
```
2. in terminal run `code`

and I get

```
➜  ~ code


#
# Fatal error in , line 0
# Fatal process out of memory: Failed to reserve memory for new V8 Isolate
#
#
#
#FailureMessage Object: 0x7ffd8c89ab30Illegal instruction (core dumped)

```

Does this issue occur when all extensions are disabled?: Can't start vscode

**Comment by meganrogge** [comment]
does [this](https://github.com/Microsoft/vscode/issues/57231#issuecomment-416228161) help?

**Comment by graph** [comment]
That doesn't help as I want to limit vscode itself. After a google it seems that this might be a V8 problem, and chrome also doesn't work under ulimits.
