### ISSUE TITLE
mywindows

### ISSUE THREAD

**Issue by EthelEleanor** [Microsoft/vscode#11058]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more details and reproduce steps.

**Comment by dbaeumer** [comment]
Closing. Haven't received any response. @EthelEleanor please ping if the issue is still reproducible with steps that demo the problematic behavior.

**Comment by EthelEleanor** [comment]
this was a 32 windows issue when my computer windows 10 64 mg 1 terabyte
