### ISSUE TITLE
Can't download extension:c/c

### ISSUE THREAD

**Issue by rotaercl** [Microsoft/vscode#11053]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by faustinoaq** [comment]
#11054

**Comment by sandy081** [comment]
Duplicates #11054
