### ISSUE TITLE
[rename on type] Should on-type-rename work across files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#110517]
When thinking of notebooks, I start to wonder if on-type-rename should support multiple documents? With notebooks multiple documents show in one "logical" editor I now that I have been dabbling with this feature I think it might be cool to be able to type-rename across multiple cells. 

This kinda relates to my wish of having mark occurrences work across multiple editors - that'll be useful for notebooks or side-by-side editors.

**Comment by aeschli** [comment]
Right now it's designed as a single file feature.

**Comment by jrieken** [comment]
I know that it's design like that but it means that it won't ever work well in notebooks

**Comment by aeschli** [comment]
We can change the API from `Range` to `Location`, but we will have to spec in the doc that the location uri should match the input document and that edits to other locations might not be honored, unless the other location is open in the same 'notebook'.

The feature is currently implemented in an `IEditorContribution` and I don't know if changes to other models and decorations on other models are possible.

**Comment by jrieken** [comment]
Maybe it should the in both directions: the request will says this is the current document and position and also what other editors/files are open. Then, the rename-on-type can make a decision if the symbol can be "quick renamed" - which IMO is if the symbol is "visible" in only those files/editors

**Comment by aeschli** [comment]
We renamed the feature to make clear this is not a rename but an editing feature. Working across files is (currently) not intended.
