### ISSUE TITLE
unpin hotkey not working on Release Notes tab

### ISSUE THREAD

**Issue by zcfan** [microsoft/vscode#110545]
- VSCode Version:1.51
- OS Version:macOS 10.15.7

Steps to Reproduce:

1. open Release Notes tab
2. use `⌘K ⇧Enter` pin this tab
3. use `⌘K ⇧Enter` again should unpin it, but nothing happens
4. same hotkey works fine on other normal tabs

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Duplicate of #100953
