### ISSUE TITLE
Add "Run-to" in debugger

### ISSUE THREAD

**Issue by timcanham** [microsoft/vscode#110598]
Did a search on "run to" with no hits

In the debugger, allow the user to click on a line and run to that line. I use this a lot on Eclipse but didn't see it for VSC.

**Comment by connor4312** [comment]
This exists in the `Run to Cursor` command

![](https://memes.peet.io/img/20-11-a8ab17ca-5224-446b-9a9c-82971b988cc5.png)

It's also available in the command palette, and if you use it a lot you can set up a [keybinding for it](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor)
