### ISSUE TITLE
References icon can disappear in ssh remote

### ISSUE THREAD

**Issue by smcdef** [microsoft/vscode#110546]
- VSCode Version: 1.51.1
- OS Version: macOS 10.15 Catalina

Steps to Reproduce:

1. remote machine with a SSH server
2. 1-2 days. I don't know how to reproduce.

<img width="411" alt="reference" src="https://user-images.githubusercontent.com/26999519/99037621-03f06700-25bf-11eb-9600-7bc79506fe81.png">

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by alexdima** [comment]
@smcdef Is there any information shown in the developer tools (Help > Developer Tools). How about in the logs (F1 > Show Logs) ? Could you please share some of those with us?
