### ISSUE TITLE
auto-complete context menu resets on its own

### ISSUE THREAD

**Issue by mago0** [microsoft/vscode#110587]
Issue Type: <b>Bug</b>

My auto-complete menu will snap back to the first entry after a brief period of time. For example, say there are 20+ entries and I'm interested in the 20th entry, I'll scroll or key down to the 20th entry. As I'm scrolling or while I'm reading the entry, the selection will snap back to the first entry on its own.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.24GB free)|
|Process Argv|-psn_0_176171 --crash-reporter-id 12c62479-3df6-4ea5-ad6f-6b28dca8a5d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|11.3.1
auto-add-brackets|ali|0.11.0
interactive-scala|als|1.3.0
god|bas|0.0.99
vscode-intelephense-client|bme|1.5.4
solargraph|cas|0.21.1
node-snippets|chr|1.2.2
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-mysql-client2|cwe|2.7.3
git-extension-pack|don|0.1.3
githistory|don|0.6.13
gitlens|eam|10.2.3
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
terraform-autocomplete|erd|0.0.8
auto-rename-tag|for|0.1.5
go|gol|0.18.1
cloudcode|goo|1.7.0
todo-tree|Gru|0.0.188
php-awesome-snippets|hak|1.1.3
vscode-systemd-support|han|0.1.1
terraform|has|2.3.0
rest-client|hum|0.24.4
kubernetes-snippets|ipe|0.1.9
vscode-edit-csv|jan|0.5.0
endwise|kai|1.4.2
json2csv|kha|0.0.1
node-module-intellisense|lei|1.5.0
kubernetes-templates|lun|1.1.1
git-graph|mhu|1.27.0
vscode-docker|ms-|1.7.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
vscode-typescript-next|ms-|4.2.20201112
vsliveshare|ms-|1.0.3121
prettier-standard-vscode|num|0.8.1
material-icon-theme|PKi|4.4.0
aws-actions|Ple|1.0.0
ruby|reb|0.27.0
java|red|0.70.0
vscode-yaml|red|0.12.0
php-debug|rob|1.14.0
mongo-snippets-for-node-js|roe|1.3.5
vscode-javascript-booster|sbu|14.0.1
scala|sca|0.4.5
prettier-plus|svi|4.2.2
vcl|tho|0.1.2
serverless-ide-vscode|Thr|0.5.26
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vim|vsc|1.17.1
whichkey|VSp|0.8.2
vscode-go-autotest|win|1.6.0
vscode-ruby|win|0.27.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
Repro steps?
