### ISSUE TITLE
Support F5 to launch web app in the webview in improve debugging experience

### ISSUE THREAD

**Issue by jayzhang** [microsoft/vscode#110556]
I'd like to develop the Teams app. Currently, after F5, VS code launch a web browser and I have to switch between VS code and the chrome browser to debug my code, it not convenient. Can VS code support such feature that I can directly debug in VS code and preview the page in VS code's webview without context switching.

**Comment by connor4312** [comment]
You might like the [Edge Devtools](https://marketplace.visualstudio.com/items?itemName=ms-edgedevtools.vscode-edge-devtools) which do _something_ like this. More is on the plan in the future, but this is not yet well defined and far from committed.
