### ISSUE TITLE
[Performance] Extremely slow (20-30s) start up time

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#110548]
- VSCode Version: 1.52.0-insiders
- OS Version: Windows 10

Steps to Reproduce:

1. run `code-insiders.cmd --disable-extensions`
2. wait

This happens even if I open an new empty window

Does this issue occur when all extensions are disabled?: Yes

PS: Any help for getting the relevant log is much appreciated. Thanks.

**Comment by stagefright5** [comment]
I just ran this command to get this start up logs: `code-insiders.cmd --disable-extensions --verbose`

[vscode-startup.log](https://github.com/microsoft/vscode/files/5535328/vscode-startup.log)

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by stagefright5** [comment]
@jrieken , I am unable to reproduce this issue anymore. It happened continuously for me just till now.  But, here is the log that I managed to grab before "it fixed itself".

> I just ran this command to get this start up logs: `code-insiders.cmd --disable-extensions --verbose`
> 
> [vscode-startup.log](https://github.com/microsoft/vscode/files/5535328/vscode-startup.log)

**Comment by frederikhors** [comment]
Same here! It is unusable!

Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by stagefright5** [comment]
@frederikhors , the problem, in my case was, I could not reproduce it consistently. If you provide the log specified above, that would be great!

**Comment by frederikhors** [comment]
How to reproduce? Simply after auto upgrade today I restarted vscode insiders and it is slow as hell!
