### ISSUE TITLE
On-type-rename and Enter

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#110518]
While playing with TS on-type-rename I kept hitting Enter as a "I am done" gesture and while it would stop renaming it also inserts enter (at the primary cursor). I wonder if Enter should simply stop rename and not insert a new line?

**Comment by aeschli** [comment]
The current behavior is intended, enter should insert a new line. The idea is that edit your code as you normally do, and the smartness is all in the background without changing the editing flow.

But you can configure enter to cancel the rename-type mode:

```
{ "key": "enter",                "command": "cancelOnTypeRenameInput",
                                 "when": "editorTextFocus && onTypeRenameInputVisible" },
```
