### ISSUE TITLE
Changing Extension Activity Bar Icon Takes Two Runs

### ISSUE THREAD

**Issue by dsanders11** [microsoft/vscode#110525]
Issue Type: <b>Bug</b>

If you change the acitivty bar icon for an extension in `package.json`, it seems to need to be run twice for it to take effect. The first run will continue to show the old icon if it still exists on disk, otherwise nothing will be shown. The second run will show the correct icon.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by dsanders11** [comment]
This happens both in development and release. Updated my extension via the extension marketplace, it said reload required, clicked to reload, old icon still shown. Exited VS Code, reopened, new icon showed.

**Comment by sandy081** [comment]
Can you please provide me the versions of your extension with old and new icons, so that I can try to repro and invesitage?

**Comment by dsanders11** [comment]
@sandy081, [here's the extension](https://marketplace.visualstudio.com/items?itemName=dsanders11.vscode-electron-build-tools), version 0.2.1 had the old icon, 0.2.2 has the new icon. It's only a small difference with the icon (the lines are a little thicker in the new one) so best to pay close attention.
