### ISSUE TITLE
Enable Ctrl+Tab to automatically switch to next recently used tab rather than wait for me to release ctrl key in VScode

### ISSUE THREAD

**Issue by rajeevriitm** [microsoft/vscode#110593]
Currently when I press ctrl+tab , the popup appears with files in the order of recently used. I can keep pressing tab untill i am on the desired file on the popup. But the tab is switched to new file only when I release the ctrl key.

I would prefer the the tab to switch to next recent file whenever I press tab key again without having to release ctrl key.

**Comment by rajeevriitm** [comment]
Can you please tag the issue which this is duplicate of?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/8939
