### ISSUE TITLE
Disambiguation when two or more snippets conflict

### ISSUE THREAD

**Issue by ornithocoder** [Microsoft/vscode#11050]
- VSCode Version: 1.4.0
- OS Version: OS X El Capitan 10.11.6

Since two or more extensions can use the same ``prefix`` to register different snippets, it would be nice if Visual Studio Code could show which extension the snippet belongs to.

I created the gif below showing how the disambiguation could work - a label placed on the right side showing which extensions is responsible for that snippet.

![snippets](https://cloud.githubusercontent.com/assets/19753339/18026826/ac9948a2-6c52-11e6-8b20-0b216ed34cdc.gif)

Thank you.

**Comment by faustinoaq** [comment]
I have the same problem with Java.
Would be fine to implement something like *enable* Atom keybindings for each package.
![disable-keybinding](http://i.imgur.com/VYHbbHQl.png)

**Comment by jrieken** [comment]
@aeschli Apart from the file names what should we use there? The key in the object literal which stores all snippets? Do we always have that?

**Comment by aeschli** [comment]
@jrieken Yes always there, but not used by VSCode. It's to stay compatible with other snippet syntaxes that use it as as the description.

**Comment by jrieken** [comment]
I have change two things
* when two snippets have the same prefix I have added their name for disambiguation ala`prefix - name`
* when a snippet is selected its source is shown - either `User Snippet` or the name of the extension

![sep-07-2016 12-43-37](https://cloud.githubusercontent.com/assets/1794099/18309287/eeb81eee-74f8-11e6-83f8-36a0ea282e50.gif)

**Comment by ornithocoder** [comment]
That's awesome! Thank you @jrieken!

**Comment by ornithocoder** [comment]
@octref @jrieken Will this be added to the Release Notes as a new feature?

**Comment by jrieken** [comment]
Nah - I have treated it has a *bug-feature* and didn't document it. Feel free to add a PR here tho: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md
