### ISSUE TITLE
Provide an option to hide the activity bar

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#1105]
I'd like to be able to hide the workspace button bar on the left side of the window to gain some more screen real estate and have a more text-focused experience.  Users of Sublime Text and Atom may also be interested in this setting.

cc @guillermooo

**Comment by bpasero** [comment]
@daviwil you can hide it already from the View menu or do you mean a permanent option? How would you then be using search, git, debug etc?

**Comment by daviwil** [comment]
I was actually referring to the workspace buttons themselves:

![image](https://cloud.githubusercontent.com/assets/79405/11664450/b3a00900-9d96-11e5-8004-f3e265c80367.png)

Sorry for not being more clear!  If they're not visible I'd just use key combinations to navigate to them.

**Comment by ristomatti** [comment]
+1 for this. I would say that being able to hide any distracting/unused UI elements being one of the appeal factors with the highly configurable non-IDE code editors (which I presume is the category Code is targeting).

As a side note, is there any way to vote on the feature requests? I'm pretty sure this is not the way to do it. I tried to look for tips on the submitting bugs and feature requests page but didn't find any guidelines on this.

**Comment by egamma** [comment]
Here are our [guidelines](https://github.com/Microsoft/vscode/wiki/Feedback-Channels) which are work in progress, to be honest we haven't fully settled on how to separate a discussion inside github issues and usevoice

**Comment by ristomatti** [comment]
@egamma Thanks! I didn't previously notice the User Voice header being a link. I've now registered there and will vote for the issues there as it seems to make more sense than commenting here.

Maybe it would be a good idea to try to settle on one service that could be used for both feature requests (voting etc.) and bugs/issues? That could greatly simplify managing these.

**Comment by Xiltch** [comment]
My Band-Aid was opening the developer tools every time I open the editor and deleting the parent div (ID: workbench.parts.activitybar ) then just toggle the side-bar on and off to let the UI re-align the div positions. The long term solution would be a bar button similar to the "Show Desktop button on a Windows taskbar" on the far left of blue status bar in the editor next to the extensions icon or a workspace settings you can force in the settings.json file ("window.activitybar" : false)?

**Comment by kendaleiv** [comment]
Implementation suggestion: Now that there's an option under the **View** menu to **Toggle Status Bar**, add another option for **Toggle Activity Bar** or similar to match.

**Comment by wallverb** [comment]
Looking forward to this feature. Would love to use this space for something more important :)

Maybe it could be also configurable via settings:

```
workbench.editor.actvitiyBar.location = "left" | "sideBar" | "statusBar" | "hidden"
```

where 
* `left` - as it is now
* `sideBar` - small icons in top part of side bar
* `statusBar` - small icons in status bar
* `hidden` - hidden

**Comment by dilijev** [comment]
To add to this: I think it would also be nice to be able to right-click on the bar to see the option to hide it (with the hotkey listed so you can remember how to quickly bring it back).

**Comment by BladeMight** [comment]
So, is it going to be implement?

**Comment by mrlami** [comment]
+1 option to hide this would be super...

**Comment by LiPengfei19820619** [comment]
+1.  I hope there is an option to allow to hide the view bar.
Thanks.

**Comment by cybertim** [comment]
👍  Because with multiple open windows the bar takes a lot of real-estate of my screen, an example:
![screen shot 2016-09-23 at 12 26 02](https://cloud.githubusercontent.com/assets/5379564/18782964/6568727c-8189-11e6-8438-192942543533.png)
With three windows/projects open next to each other almost 20% of editor space is filled with a grey area, i'd rather use this for more code  ;-)

**Comment by LiPengfei19820619** [comment]
I expect this feature to be implemented as soon as possible.
Thanks.

**Comment by frizadiga** [comment]
I need more space for my code, so I hope this feature can be implemented ASAP

**Comment by samal84** [comment]
This issue might seem superficial, but I fear that the activity bar is giving a very bad first impression for many curious new users, who are searching for an unobtrusive and minimal code editor experience.

I mean, it's so big, and it does so little... why has it been given so much visual focus? What else in this editor might get weirdly in my way?

**Comment by wallverb** [comment]
Hopefully it will not become ~25px wider (without ability to hide) https://github.com/Microsoft/vscode/issues/12377

**Comment by golf1052** [comment]
I poked around a bit and attempted to implement this.

![2016-11-03_03-28-54](https://cloud.githubusercontent.com/assets/1903871/19958932/40de6226-a179-11e6-81bb-d7aa142993e6.gif)

Probably a bunch of other things I need to look at or test but the code is [here](https://github.com/golf1052/vscode/tree/hide-activity-bar)

**Comment by BladeMight** [comment]
> I poked around a bit and attempted to implement this.

Quite impressive, looking forward to implement this into main release.
P.S. Also will be good if add an hotkey to that.

**Comment by golf1052** [comment]
Did another pass through making sure that the setting is reflected correctly and fixed a few bugs.

![2016-11-03_17-23-12](https://cloud.githubusercontent.com/assets/1903871/19986206/215f9348-a1ec-11e6-8d8f-fe13de162988.gif)

**Comment by nikhildaga** [comment]
The sidebar icons and bottom bar are the only things stopping me from using vscode instead of atom

**Comment by renier** [comment]
@golf1052 Will you submit a PR from your fork?

**Comment by dilijev** [comment]
@nikhildaga You can change the visibility of the bottom bar by going to View > Show/Hide Status Bar or by setting `"workbench.statusBar.visible": false`

**Comment by niallobrien** [comment]
Looking forward to seeing this feature being implemented. Thanks all.

**Comment by bpasero** [comment]
This landed with the new setting `"workbench.activityBar.visible"`.

Thanks @golf1052 👍

**Comment by nikhildaga** [comment]
That's great news! Thanks so much!

@dilijev : I was talking about : https://github.com/Microsoft/vscode/issues/1884

**Comment by wallverb** [comment]
Could we also get Toggle Activity Bar menu option (and ability to set keyboard shortcut) ?

![image](https://cloud.githubusercontent.com/assets/1723815/20180127/1f743fbc-a727-11e6-996b-e6874cfd331d.png)

**Comment by cybertim** [comment]
I would suggest to add the setting (like it's working now) but when you set `workbench.activityBar.visible` to `false` the `CMD-B` will hide/show the activityBar together with the Side Bar.

**Comment by bpasero** [comment]
@wallverb there is an entry in the menu as well as a command to toggle 👍 

@cybertim I like the idea but I think this needs another option because not everyone might want to ever see the activity bar?

**Comment by cybertim** [comment]
@bpasero that is true, but isn't 'coupling' the activitybar from the sidebar making the sidebar less functional, since it also shows a quick overview of what other activities need attention (like updates for the extensions).
But I agree, maybe have three settings for the `workbench.activityBar.visible` ? `never` `always` and `combined` ?

**Comment by bpasero** [comment]
@cybertim I do not know how people see the activity bar. For many it may just be a toolbar or menu that they want to turn off. That is totally valid (like turning off the top level menu).

I like your suggestion though with having multiple settings, though the toggle action would probably still just hide it for good.

**Comment by cybertim** [comment]
@bpasero I can only speak for myself, but I see the activityBar as a whole, like tabs, for the SideBar. That is why I thought it would feel more natural to hide/show the activityBar combined with the sideBar.

**Comment by wallverb** [comment]
If we could have something like

`workbench.editor.actvitiyBar.location = "sideBar"`

![image](https://cloud.githubusercontent.com/assets/1723815/20181965/2f70c88e-a72e-11e6-8cee-bd02de245c54.png)

then @cybertim use case would be handled

**Comment by bpasero** [comment]
I suggest to open individual issues for requests that are now coming up. They are otherwise lost in this closed work item.

**Comment by shaharido1** [comment]
+1

**Comment by magneticz** [comment]
is the workbench.activityBar.visible available in the latest stable release. I can't get it working, so maybe i am doing something wrong

**Comment by kaiwood** [comment]
@magneticz Its only in Insiders currently, but will be available in the next stable release this month.

**Comment by rafaelbdb** [comment]
Should have an "auto-hide" option (shows on mouse hover)

**Comment by BladeMight** [comment]
@rafaelbdb an 1px wide sidebar with resize on mouse hover would be great, something like that might help:
```css
.sidebar {
  width: 1px;
  transition: width 0.5s ease; /* for smooth show/hide */
}
.sidebar:hover {
  width: 25px;
}
```
or in js so:
```js
sidebar.onmouseover = _widen;
sidebar.onmouseout = _shrink;
function _widen(event) {
    sidebar.style.width = 25;
}
function _widen(event) {
    sidebar.style.width = 1;
}
```

**Comment by desmond-dsouza** [comment]
Since the activity-bar and side-bar are closely related, what about using a single command "Toggle Side-Bar" or "Switch Side-Bar", with a single shortcut like Cmd-B, which cycled through either (a) Both on or Both off (my preference) or (b) the 4 combinations: off-off, off-on, on-off, on-on?
