### ISSUE TITLE
PHP not recognized as a language anymore since 1.51.0 - *.php files are detected as plain text.

### ISSUE THREAD

**Issue by ErnestoBorio** [microsoft/vscode#110527]
- VSCode Version: 1.51.1
- OS Version: MacOS 10.13.6

This happened since 1.51.0

**Steps to Reproduce:**

1. Start with extensions disabled _(or don't, it doesn't matter)_
2. `*.php` files are detected as `plain text` files and thus have no syntax coloring or intellisense.  

This is my [settings.json](https://gist.github.com/ErnestoBorio/82527ab5d48add23d9f69ce43fda6720).  

Adding `{"files.associations": { "*.php": "PHP" }}` doesn't help.  

Adding PHP extensions like [felixfbecker.php-intellisense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) doesn't help either.  

The `Select language mode` menu doesn't display PHP so I guess it's not even recognized as a language anymore.

Does this issue occur when all extensions are disabled?: Yes

### Full VSCode version:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 day ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

**Comment by phillystafford** [comment]
I'm having the same issue with `.tsx` and `.jsx` files being displayed as plain text files.

Files that are still working properly with colour highlighting are

```
.js
.json
.svg
.env
.ts
.yaml
.md
.mdx
.ejs
```
 

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

**Comment by phillystafford** [comment]
I'm after tracking my problem down to the [TabNine Autocomplete](https://github.com/codota/tabnine-vscode) extension

**Comment by boaz-codota** [comment]
We've released a new version with a fix: https://github.com/codota/tabnine-vscode/pull/206

Sorry for anyone who is affected by this.

**Comment by ErnestoBorio** [comment]
Ok, I reinstalled VSCode, after removing all extensions and just kept the entries at settings.json that I was still making use of, and the problem was solved.

PHP back again detected as a language.

_**PS:** Hadn't installed or used tabnine ever._
