### ISSUE TITLE
[rename on type] Disable quick suggestion during on-type-rename

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#110520]
See attached gif

* type-on-rename for TS (`joh/tsQuickRename` branch)
* type at the end of an identifier
* :bug: quick suggestion shows the identifier you are typing (and also likely other suggestions)

![Nov-12-2020 21-06-16](https://user-images.githubusercontent.com/1794099/98990632-ff7a6e80-252a-11eb-9d72-eb0907ff188f.gif)

**Comment by jrieken** [comment]
@aeschli I can help you with disabling this

**Comment by aeschli** [comment]
It's the same when editing HTML tags and type-on-rename enabled.

Can you elaborate why this is a problem? I personally don't think there's anything wrong to show quick suggestions while 'rename on type' works in the background. Completions work and are applied to all linked ranges.
The idea of 'rename on type' is to not impact the normal edit flow. 

But if you want, we could add an setting. We have a context `onTypeRenameInputVisible` that could be helpful.

**Comment by jrieken** [comment]
> Can you elaborate why this is a problem? 

Try this with a non html sample and you see how nonsense it is (the word I am typing)

**Comment by aeschli** [comment]
Guessing what you mean...
- If the connected ranges include the declaration as well, then proposals for other existing variables don't make much sense. You'd end up with two declarations of the same kind. if if the ranges do not include the declaration, then the proposals could be useful. Or if the proposals are classic word proposal, then they would make sense.
- Suggesting the same what you already have also doesn't seem to be helpful, but that's what we do. I believe we do it to provide more information on the symbol.

**Comment by jrieken** [comment]
> if if the ranges do not include the declaration, then the proposals could be useful.

But isn't the declaration needed when renaming a variable?

**Comment by aeschli** [comment]
> But isn't the declaration needed when renaming a variable?
It can be in a different file
