### ISSUE TITLE
Need ${workspaceFolderParentBasename} predefined variable

### ISSUE THREAD

**Issue by weisun76** [microsoft/vscode#110681]
Hi VScode development team,

We are using VScode on a big software project development. There are several groups and we each created a sub-folder under the big project. Since each group uses different development software/configuration, the .vscode configuration is saved under each sub-folder. Perforce is used as the version control software for the whole project. We face a challenge to set Perforce client automatically. Here is the situation:
1. Let us assume that we create a perforce workspace named /my_workspace. For group A, the code is under /my_workspace/group_A.
2. When group A team member open group_A in vscode, the ${workspaceFolderBasename} is pointed to "group_A". This is per-design. However, since Perforce is set to whole project, it expects to have "my_workspace" as Perforce client.
3. We can not find a way to set this value in .vscode configurations. We hope to have something like "${workspaceFolderParentBasename}".

This situation should be common for a big software project. Hope you will consider this feature. For now, we need to manually set up the Perforce client every time when we switch workspace.

Thank you in advance!

**Comment by sandy081** [comment]
May I know for which setting you would like to use this variable?

**Comment by weisun76** [comment]
Hi Sandeep,

Thank you so much for your prompt reply!

I need this variable in "settings.json" file, where perforce and
environment is configured.

Please let me know if you have any further questions.

Best regards,
Wei

**Comment by sandy081** [comment]
Can you please name the settings ?

**Comment by weisun76** [comment]
Hi Sandeep,

Thanks again!

Here is my current settings.json file:

{
    "env":{
        "TOPDIR": "${workspaceFolder}/..",
        "PSDTOP": "${workspaceFolder}",
        "PATH":
"${env:PATH}:${workspaceFolder}/../mb/bin:${workspaceFolder}/bin"
    },

    "perforce.activationMode": "always",
    "perforce.compatibilityMode": "perforce",
    "perforce.port": "ssl:helix.engops.health.ge.com:2668",
    "perforce.editOnFileModified": true,
    "perforce.editOnFileSave": true,
    "perforce.addOnFileCreate": true,
    "perforce.annotate.enable": true,

    "terminal.integrated.env.linux": {
        "TOPDIR": "${workspaceFolder}/..",
        "PSDTOP": "${workspaceFolder}",
        "PATH":
"${env:PATH}:${workspaceFolder}/../mb/bin:${workspaceFolder}/bin"
    },
    "terminal.integrated.cwd": "${fileDirname}",

    "files.associations": {
        "*.e":"cpp",
        "*.in":"cpp",
    }
}

My working directory is
"~/Perforce/wei.sun_GH3Q9YY2E_PsdCommonVirtual_6549/psd". My
${workspaceFolder} is "psd" but my Perforce client is "
wei.sun_GH3Q9YY2E_PsdCommonVirtual_6549". So I need a
${workspaceParentFolder}.

Thanks,
Wei

**Comment by sandy081** [comment]
@weisun76 Thanks for providing the settings. Can you please be specific about the single **"setting"** in which you want to use `${workspaceParentFolder}`.  

I am also unsure which extension needs the following entry from the settings file?

```
"env":{
        "TOPDIR": "${workspaceFolder}/..",
        "PSDTOP": "${workspaceFolder}",
        "PATH":
"${env:PATH}:${workspaceFolder}/../mb/bin:${workspaceFolder}/bin"
    },
```

**Comment by weisun76** [comment]
Hi Sandeep,

I want to use "${workspaceParentFolder}" for Perforce for VS Code
(mjcrouch.perforce) plugin. It has a perforce.client parameter but does not
take pre-defined variable yet. However, it takes the environment variable
"P4CLIENT". I am planning to use it in env settings similar to "TOPDIR" and
"PSDTOP". They are needed for our project.

Please let me know if you have any further questions.

Thanks,
Wei

**Comment by sandy081** [comment]
Thanks for info. Since the extension owns the settings you mentioned, please file the request against the extension to accept env variables.

**Comment by weisun76** [comment]
Hi Sandeep,

The environment variable is set from VScode itself instead of extension.

Regards,
Wei

**Comment by weisun76** [comment]
I hope the have the following:

"env": {
    "P4CLIENT": "${workspaceParentFolder}"
}

**Comment by sandy081** [comment]
I do not think VS Code owns this env setting and does any replacement of env variables. It should be the extension owning this property handling it. Please reach out to the extension so that they can analyse first.

**Comment by weisun76** [comment]
Who create ${workspaceFolder}? Is it VS code or other extensions? I thought predefined values are created by VScode and other extensions just use them. Am I wrong?

**Comment by sandy081** [comment]
VS Code does not create/own any such variables in settings. It is extensions who own and resolve them at present.
