### ISSUE TITLE
Allow libraries to recommend extensions

### ISSUE THREAD

**Issue by justinfagnani** [microsoft/vscode#110616]
I maintain a library, lit-html, where the developer experience within VS Code is *greatly* improved by an extension that provides syntax highlighting, linting, intellisense, etc. Unfortunately many people aren't aware of the extension, and don't get those benefits.

It would be great for our users if we could include some configuration in the package so that when a user imports our library they get a recommendation similar to what you see if you edit a file type that you don't have an extension for.

**Comment by usernamehw** [comment]
You can make your extension depend on another (in `package.json`).

`extensionDependencies` - An array with the ids of extensions that this extension depends on. These other extensions will be installed when the primary extension is installed. The id of an extension is always `${publisher}.${name}`. For example: `vscode.csharp`.

https://code.visualstudio.com/api/references/extension-manifest#fields

**Comment by justinfagnani** [comment]
@usernamehw I don't see how that helps.

I don't want my library to depend on the extension, since not every user of the library uses VS Code, and not every install of the library will be for users who are directly using it. We don't want to incur that download cost.

Then, there's only one extension in play here. There isn't another extension to depend on.

What I'm looking for is a way to add something like:

```json
{
  "recommendations": ["runem.lit-plugin"]
}
```
(similar to [workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions))

to my library's *`package.json`*, and have that extension be recommended to users who import modules from that package, and thus would benefit from the extension.

**Comment by usernamehw** [comment]
I delete the comment after reading the issue the second time.
