### ISSUE TITLE
Broken syntax highlighting in for loops in JavaScript

### ISSUE THREAD

**Issue by sklivvz** [Microsoft/vscode#11061]
Repro:

![generator js - steven - visual studio code 2016-08-28 10 16 04](https://cloud.githubusercontent.com/assets/750257/18032771/b0903a54-6d08-11e6-8c41-8dbc2c7f0c07.png)

- VSCode Version: 1.4.0
- OS Version: WIn 8.1

Steps to Reproduce:

1.  create a js file
2.  type

```
for(var j=0; (j<rows && l<num); j++) {
  for(var k = 0; (k<cols && l<num); k++){
    output.push( {h, w, x: k*w, y: h*j, file: file.file});
    l++;
  }
}
```

**Comment by alexandrudima** [comment]
Moved to Microsoft/TypeScript-TmLanguage#251
