### ISSUE TITLE
crash on content delete

### ISSUE THREAD

**Issue by pungggi** [Microsoft/vscode#11063]
- VSCode Version: Code - Insiders 1.5.0-insider (31f1acb8c82b8a19256d5d56127d3f81edce3745, 2016-08-26T08:00:03.472Z)
- OS Version: Windows_NT ia32 10.0.14393

vsc crash!

Steps to Reproduce:
1. delete a lot of content inside a md file
2. in git tab try to discard the changes..

**Comment by joaomoreno** [comment]
Can you provide a video recording of this? Also, the contents of that md file?
