### ISSUE TITLE
I can only one dropdown option when i type in an extension's shorthand or snippet

### ISSUE THREAD

**Issue by udabasili** [microsoft/vscode#110625]
So basically let's say I type in the shorthand or snippet for an extension in a file, I only see one option to choose from even if multiple extensions might use the same shortcut or snippet. In some cases things built from visual code such as options like value or onChange in a jsx file dont even show up I noticed this started happening this week and i literally uninstalled and installed all plugins

![Screenshot (1)](https://user-images.githubusercontent.com/33573587/99144823-815bbc00-263f-11eb-989f-4c850549e840.png)

In the above screenshot you would notice only one option when i type rf even though i have multiple extensions that use the same shortcut

**Comment by gjsjohnmurray** [comment]
That list is now resizable. Please try dragging the lower right corner.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest+label%3Aux
