### ISSUE TITLE
Unable to open VSCode without Mac Crashing

### ISSUE THREAD

**Issue by Vidsify** [microsoft/vscode#110634]
- VSCode Version: MacOS 10.10+
- OS Version: Big Sur Version 11.0.1

Steps to Reproduce:

1. Reinstalled VSC for MacOS and removed all old files as explained here https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019
2. Upon opening the application it freezes and my MacBook crashes

Does this issue occur when all extensions are disabled?: Received an error
`zsh: command not found: code`

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
