### ISSUE TITLE
Git Push asking for Git hub credentials and says logon failed

### ISSUE THREAD

**Issue by maxx-808** [microsoft/vscode#110620]
Issue Type: <b>Performance Issue</b>

Never had this, git push asking for git hub user and password, when i enter it, terminal says logon failed, changed password and still did not work. I always had pushed with no problems so I am not sure what has changed.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.27GB free)|
|Process Argv|C:\Users\max96\OneDrive\Desktop\Homework assignment\7 Project 1 yoda astro --crash-reporter-id 7c18b9d1-fb60-4d4b-a545-95193b92450a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    72	 18356	code main
    0	    18	  1960	   crashpad-handler
    0	    28	  7228	   utility
    0	   282	 11388	   window (Settings - 7 Project 1 yoda astro - Visual Studio Code)
    0	    90	 18240	     extensionHost
    0	   114	  5092	       electron_node tsserver.js 
    0	    31	 16016	         electron_node typingsInstaller.js typesMap.js 
    0	    88	  7592	       electron_node tsserver.js 
    0	    49	 11460	       "C:\Users\max96\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\max96\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=18240
    0	    46	 14916	       "C:\Users\max96\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\max96\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=18240
    0	    13	 18384	     watcherService 
    0	     3	 15572	       console-window-host (Windows internal process)
    0	     8	 21996	     console-window-host (Windows internal process)
    0	    72	 22448	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    57	 17572	   shared-process
    0	    78	 17624	   window (Issue Reporter)
    0	   111	 17744	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - 7 Project 1 yoda astro - Visual Studio Code)
|    Folder (7 Project 1 yoda astro): 50 files
|      File types: png(13) js(6) md(5) html(3) DS_Store(2) jpg(2) gitkeep(1)
|                  css(1) dxf(1) pdf(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.13
gitlens|eam|10.2.3
code-runner|for|0.11.1
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4
json|Zai|2.0.2

</details>

**Comment by eamodio** [comment]
Are you still experiencing this on the latest version? If so, can you provide any more details? Also, if things don't even work on the command line, I don't think this is really a VS Code issue, and you might want to ask a question on StackOverflow about it or open a Git issue.
