### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by stinghz** [Microsoft/vscode#11065]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.0.0

Steps to Reproduce:

1. search for something 
2.always no result found

**Comment by stinghz** [comment]
was not working, reopen the IDE and it is working now

**Comment by stinghz** [comment]
still not working

**Comment by mrmlnc** [comment]
Please, provide more details. Also try reproduce your problem without extensions (`code . --disable-extensions`).

**Comment by sandy081** [comment]
@stinghz As requested, please provide more details. It could be a specific case/scenario if you as it is working in general for us.

**Comment by mysticman** [comment]
I have also not working the search. It happens quite often I don't know what is the problem. Sometimes working sometimes not. 

There was some error in the devtools windows but after delete and search again no error occurred.

![vscode error search](https://cloud.githubusercontent.com/assets/2445639/18045017/ec6d0a70-6dd0-11e6-9d90-1495ff359de7.png)

**Comment by mrmlnc** [comment]
@mysticman, In your case the search is enabled on the selected text.

![chrome_2016-08-29_11-29-18](https://cloud.githubusercontent.com/assets/7034281/18045543/f93303c6-6ddb-11e6-9162-15ae9d68a720.png)

**Comment by mysticman** [comment]
And how did you know that. I cannot find the button or option that search just in the text. I am coming from the VS world and for CTRL + F always searched in the current doc. Am I doing something wrong?

**Comment by sandy081** [comment]
@mysticman Is Find not working only with this search term or do you observe with other terms? Also can you provide us the error you see in the devtools?

**Comment by bgse** [comment]
@mysticman It is a little hard to notice, the little "text lines" buttons is active when it searches only in current selection, see screenshot.

![search_selection](https://cloud.githubusercontent.com/assets/8385202/18050435/d8621e80-6dee-11e6-8f26-3866d3a590f3.png)

**Comment by dbaeumer** [comment]
Assuming that this is actually caused by the selected line setting outlined by @mrmlnc and @bgse.

 @stinghz please ping if the issue is cause by something different with steps that demo the problematic behavior.
