### ISSUE TITLE
Spelling mistake in trailing space option

### ISSUE THREAD

**Issue by richfi** [microsoft/vscode#110661]
Issue Type: <b>Bug</b>

1. from editing C++ file go to settings (command-, on Mac)
2. search for the word "trailing" (no quotes)
3. note that for Editor>Smart Select: Select Leading And Trailing Whitespace option, description says "Weather...". Should read "Whether..."

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id a6c46ca5-3ba7-4700-9341-a7d7c6c9bb0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.21.0
better-cpp-syntax|jef|1.15.5
csharp|ms-|1.23.6
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
cmake-tools|ms-|1.5.2
cpptools|ms-|1.1.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3121
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3075
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@richfi This looks OK for me. Maybe it was fixed in the meantime:
![image](https://user-images.githubusercontent.com/5047891/99231810-6a5ccb80-27f1-11eb-9ea8-c378686f2f6f.png)

**Comment by jrieken** [comment]
Yep, already fixed
