### ISSUE TITLE
Weird UI rendering performance

### ISSUE THREAD

**Issue by neoacevedo** [microsoft/vscode#110601]
- VSCode Version: 1.51
- OS Version: openSUSE Tumbleweed 20201111

Steps to Reproduce:

1. Open VSCode
2. Edit any file

Does this issue occur when all extensions are disabled?: Yes

I have openSUSE TW in a VM iside Windows 10 with VMWare.

![Screenshot_20201112_174349](https://user-images.githubusercontent.com/438372/99125273-b16c7600-25d1-11eb-9ff2-76de7abc8b97.png)
![Screenshot_20201113_165348](https://user-images.githubusercontent.com/438372/99125415-fe504c80-25d1-11eb-9da0-62719a538490.png)

As you can see in the pictures, once opened a rendering problem is present, doing the editor is uncompfortable to be used.

**Comment by deepak1556** [comment]
Can you follow these steps to disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if that resolves the issue ?

**Comment by neoacevedo** [comment]
Thank you @deepak1556 , at the moment this works for me.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/91895
