### ISSUE TITLE
Attaching VSCode to running container disconnect remote session

### ISSUE THREAD

**Issue by leungi** [microsoft/vscode#110688]
Issue:
- When attaching VSCode to running container, remote session always disconnect and unable to reconnect
- Attaching VSCode to shell of container works, though

System Info:

- VSCode Version: 1.50.1
- OS Version: Windows 10 x64 build 17134

Steps to Reproduce:

1. SSH to remote using Remote-SSH: Connect to Host
2. In VSCode container extension, right click on existing, running container and "Attach Visual Studio Code"
![vsc-error](https://user-images.githubusercontent.com/30273868/99200272-ee6b7080-2769-11eb-89b1-b6454a69c80a.gif)

Does this issue occur when all extensions are disabled?: Yes/No
N/A. To reproduce, extensions are required.

**Comment by chrmarti** [comment]
/duplicate https://github.com/microsoft/vscode-remote-release/issues/2994
