### ISSUE TITLE
 terminal letters disappear randomly

### ISSUE THREAD

**Issue by IncognitaDev** [microsoft/vscode#110685]
- VSCode Version: 1.51.1
- OS Version: Linux Mint 20

I use zsh along with oh-my-szh with the Agnoster theme and the Jetbrains mono font

When opening the integrated vscode terminal some letters are missing, when opening a new integrated terminal, all letters appear, but when puttin terminal in focus or typing some command, some letters desapear and sometimes all letters desapear

some screen shots to exemplify:

when I opening the first terminal:
![image](https://user-images.githubusercontent.com/48053804/99196569-0643f400-276c-11eb-983e-a065973ef87a.png)

when I opening the second or third terminal: 
![image](https://user-images.githubusercontent.com/48053804/99196424-0abbdd00-276b-11eb-9d05-047bd1a1d7dd.png)

when I run any command: 
![image](https://user-images.githubusercontent.com/48053804/99196438-1e674380-276b-11eb-8b46-f7d05bb6a72a.png)

when I do zoom in/out:
![image](https://user-images.githubusercontent.com/48053804/99196453-36d75e00-276b-11eb-9a76-47c9bfda02c9.png)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
if you change the font does that help? also, have you tried changing the renderer type, IE `terminal.integrated.rendererType`

**Comment by IncognitaDev** [comment]
thanks for atention 
I use the Jetbrains mono font, but I test with Fira code and with a monospace font without ligatures and powerline and in all tests the letters disappear randoly.

I d'ont tried change the render type, which are the values I can pass to tis property?

**Comment by IncognitaDev** [comment]
I change the value os `terminal.integrated.rendererType` to  `"terminal.integrated.rendererType": "dom"` and Work, apparently the error has been resolved. 

Tank you.
