### ISSUE TITLE
License Agreement Issue

### ISSUE THREAD

**Issue by DenitsaAGeorgieva** [microsoft/vscode#110611]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

I installed everything i need and it keeps saying i haven't agreed to the license' agreement which is unusual. It won't let me compile my program, run it, debug it or anything at all. I find this very unusual, i am new to programming and i don't know what exactly i need to do in order to agree to this agreement. I went on the website and i can see it there but that's about it. Any advise?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id d71c9f75-f940-4f77-a4dd-72021a10f2ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.1.1

</details>

**Comment by joaomoreno** [comment]
>  it keeps saying i haven't agreed to the license' agreement which is unusual

Can you show me a screenshot?

**Comment by DenitsaAGeorgieva** [comment]
Hi, i sorted this one out. Do you know if someone can help me configure vs
code properly as per my course's specifications, i can pay as well, as long
as i am abke to finally start working?
When i try ti launch json, it keeps saying cannot read "property" of
undefined..

**Comment by joaomoreno** [comment]
> as per my course's specifications

You can very likely just ask for help to your course teacher.

> When i try ti launch json, it keeps saying cannot read "property" of undefined..

Can you show me a screenshot?

**Comment by DenitsaAGeorgieva** [comment]
Hi, i asked the teacher and the forum of the course, no helpful at all been
stuck on it for days now and im starting to give up... I will send you all
screenshots once i am on the computer if that's okay?
Thanks so much for your help!!!

**Comment by joaomoreno** [comment]
Is your problem this maybe? https://stackoverflow.com/questions/31384994/how-to-accept-xcode-license

**Comment by DenitsaAGeorgieva** [comment]
Hi i sorted this one out after days of trying...
Now i have a different one when doing the settings (json)
The tutor has only done a tutorial for windows and i use mac... I am
waiting for a reply from him hopefully he tells me the mac tutorial...
