### ISSUE TITLE
Provide word wrap setting for diff editor

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#110603]
I'm using word wrapping in normal editors but I do not find word wrap helpful in the diff editor.
For me it is very difficult to understand the changes within a line if that line is wrapped into multiple visual lines.
I prefer to use horizontal scrolling to review changes in long lines.

I'm aware of the "toggle word wrap in diff editor" feature (which currently doesn't work #110468), but I would prefer a more permanent setting.

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by alexdima** [comment]
The setting is `diffEditor.wordWrap: 'on' | 'off' | 'inherit'`

**Comment by alexdima** [comment]
Will be tested via #111544
