### ISSUE TITLE
Workbench: navigate active view by simple "next/previous" as well as existing "up/down/left/right"

### ISSUE THREAD

**Issue by timbertson** [microsoft/vscode#110619]
Coming from vim, I like using the `<c-w w>` and `<c-w W>` commands (next / previous view) to cycle between visible views (I remap the actual keys, but those are the default keybindings).

I can get half of this with vscode, by binding keys to:
```
{ "key": "alt+shift+j",         "command": "workbench.action.navigateDown" },
{ "key": "alt+shift+k",         "command": "workbench.action.navigateUp" },
{ "key": "alt+shift+h",         "command": "workbench.action.navigateLeft" },
{ "key": "alt+shift+l",         "command": "workbench.action.navigateRight" }
```

However that forces me to have 4 keybindings, and to navigate by direction. I would much prefer to have just two keybindings, for `next` / `previous`. That way I can cycle through my views without having to think too hard about where I'm going - I just tap the `next` shortcut until the one I want is active. The order doesn't need to be 100% intuitive, a rough algorithm which is stable is sufficient (i.e. running `next` then `previous` should always bring me back to the same place)

I started coding this as an extension, but I'm fairly new to vscode and it doesn't look like there's enough access. I'd need information about: all visible editors + panes, as well as the ability to see which one is in focus (and focus a particular one).

There's some pieces of this in e.g. `vscode.window.visibleTextEditors`, but it's not really enough to get a full view of what views are visible / active.

I think this would mostly just affect https://github.com/microsoft/vscode/blob/8fcf778ba251131780f2a110d311161f39b97b03/src/vs/workbench/browser/actions/navigationActions.ts#L40-L72

**Comment by isidorn** [comment]
Feels like a fair feature request.
fyi please note that we have Focus Next Part `F6` and Focus Previous Part `shift+F6` for a top level view navigation (editor -> panel -> status bar -> activity bar -> side bar -> editor).

As for you exact ask it personally feels to me a bit more intuitive than the current navigate down, left, up, right. Though leaving this up to @sbatten to decide since he introduced the inital actions.

**Comment by sbatten** [comment]
to clarify, given the `F6` navigation suggested by @isidorn, is this request simply to have the same type of navigation for editor panes?

**Comment by timbertson** [comment]
@sbatten I think so, but the question is a little ambiguous so so I'll try to be more explicit:

There's already the same type of navigation for _only_ editor panes ("Focus next/prev editor group"), I want a next/previous action that extends this to cover both editor groups and views. i.e. when I press it from the last editor group, it continues on to the next view (for me this is usually the terminal).

If you're proposing extending "parts" (as focussed by `F6`) to include editor panes, that's not quite what I want since it seems a bit too granular - e.g. the strip of buttons to the left of the sidebar and the bottom statusbar are both distinct parts, but I wouldn't want this feature to include those.

**Comment by sbatten** [comment]
@timbertson would the following keybinds meet your description?

```
    {
        "key": "f6",
        "command": "workbench.action.focusNextGroup",
        "when": "editorFocus"
    },
    {
        "key": "shift+f6",
        "command": "workbench.action.focusPreviousGroup",
        "when": "editorFocus"
    },
    {
        "key": "f6",
        "command": "workbench.action.focusNextPart",
        "when": "!editorFocus || activeEditorGroupLast"
    },
    {
        "key": "shift+f6",
        "command": "workbench.action.focusPreviousPart",
        "when": "!editorFocus || activeEditorGroupIndex == 1"
    },
    {
        "key": "shift+f6",
        "command": "workbench.action.focusLastEditorGroup",
        "when": "panelFocus"
    },
    {
        "key": "f6",
        "command": "workbench.action.focusFirstEditorGroup",
        "when": "sideBarFocus"
    },
```


I used f6 here but you can replace as you like.

**Comment by timbertson** [comment]
Ah, very clever thanks. This is very close to what I want, and is certainly a good workaround for now.

The only problem being that it still cycles through the bottom sidebar and strip of buttons to the left of the folder view, which (imo) shouldn't be included in this enumeration (I already have different keyboard shortcuts for activating various sidebar modes, and I never really interact with the botto status panel).

**Comment by sbatten** [comment]
my hesitation is that the functionality you mention that should differ here is not something I can say should be universal. If I were to implement such a command, I would expect that it hits those 2 parts you mention you'd like to skip.

**Comment by timbertson** [comment]
True, but the set of things I want it to go through exactly matches what the "View: navigate up/down/left/right" commands do, so I'm just wanting a different way to cycle through that same set of items.
