### ISSUE TITLE
VSCode does not start tsserver and does not recognize `typescript.*` config options

### ISSUE THREAD

**Issue by mradamczyk** [microsoft/vscode#110602]
Issue Type: <b>Bug</b>

When opening any typescript project VSCode does not start tsserver - does not compile the code. I

I've also noticed that in settings vscode does not recognize any `typescript.*` config option - e.g. for `typescript.tsdk` it shows "Unknown Configuration Setting". I also do not see any dropdown with typescript version in the bottom bar:
<img width="530" alt="Screen Shot 2020-11-13 at 3 13 02 PM" src="https://user-images.githubusercontent.com/2982247/99129765-79b6fb80-25dc-11eb-83a5-ccc533fbf697.png">

I don't see TypeScript task in the dropdown and don't see tsserver trying to start either:
<img width="1290" alt="Screen Shot 2020-11-13 at 7 27 12 PM" src="https://user-images.githubusercontent.com/2982247/99133054-66a92900-25e6-11eb-9edb-39aec3b7ab12.png"> 

I can run `tsc --v` in the VSCode terminal and it works fine. I'm on `4.0.5` version.

This happens on Catalina, but i had that already working - stopped working either with vscode upgrade to 1.51.1 (although later i downgraded to 1.50.1 and didnt work either) or with upgrade of node-gyp.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|32.00GB (2.34GB free)|
|Process Argv|--crash-reporter-id 4288811b-6925-4fc5-ac93-57b72d662e6d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sass-index-creator|q|1.0.2
vim|vsc|1.17.1

</details>

**Comment by mradamczyk** [comment]
I also tried to uninstall completely vscode and install again. Didn't help.

But when i installed a fresh copy of "VSCode Insiders" everything seems to work!
<img width="1409" alt="Screen Shot 2020-11-13 at 7 24 48 PM" src="https://user-images.githubusercontent.com/2982247/99133105-96583100-25e6-11eb-802e-70bc07f9dae5.png">

Not sure what is blocking normal vscode app from starting tsserver.

**Comment by mjbvz** [comment]
Is the built-in JavaScript and TypeScript extension disabled? Search `@builtin` in the extensions view and check if `TypeScript and JavaScript Language Features` is disabled

**Comment by mradamczyk** [comment]
This makes so much sense now! Yes, i had `TypeScript and JavaScript Language Features` disabled :/ Not sure how i got there, but must have clicked it by mistake. Thank you!
