### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by jcval94** [microsoft/vscode#110689]
Issue Type: <b>Bug</b>

I have tried:

pip install scikit-learn
pip3 install scikit-learn

I always get the same response from the console:

Requirement already satisfied...

Then I run my ".py" file and it says:

ModuleNotFoundError: No module named 'sklearn'

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600S CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (1.62GB free)|
|Process Argv|--crash-reporter-id e57cece8-b171-4dfb-acf3-57ac9671c4a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.7.2
rainbow-csv|mec|1.7.1
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
vscode-xml|red|0.14.0
salesforce-vscode-slds|sal|1.4.0
salesforcedx-vscode|sal|50.5.0
salesforcedx-vscode-apex|sal|50.5.0
salesforcedx-vscode-apex-debugger|sal|50.5.0
salesforcedx-vscode-apex-replay-debugger|sal|50.5.0
salesforcedx-vscode-core|sal|50.5.0
salesforcedx-vscode-lightning|sal|50.5.0
salesforcedx-vscode-lwc|sal|50.5.0
salesforcedx-vscode-visualforce|sal|50.5.0

</details>

**Comment by alexdima** [comment]
This does not appear to be a problem with vscode. Please search for or create a new question on StackOverflow.
