### ISSUE TITLE
Double clicking on an item in Outline does not highlight occurrences.

### ISSUE THREAD

**Issue by rbtyod** [microsoft/vscode#110613]
Issue Type: <b>Bug</b>

Double clicking on an item in Outline does NOT highlight occurrences while directly clicking any occurance in the editor DOES highlight occurrences.  This seems inconsistent.

I found this while editing a python file.

...Bob

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (22.07GB free)|
|Process Argv|--crash-reporter-id 25d5146f-f41b-4131-9f51-4991f3fdae56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gather|ms-|2020.11.0
python|ms-|2020.11.358366026
vscode-pylance|ms-|2020.11.1
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
vsliveshare|ms-|1.0.3121

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by rbtyod** [comment]
![Screenshot 2020-11-13 180935](https://user-images.githubusercontent.com/69878765/99136723-838c2f00-25db-11eb-8727-e2167ce4bf26.png)

**Comment by rbtyod** [comment]
![Screenshot 2020-11-13 180935](https://user-images.githubusercontent.com/69878765/99136764-d36af600-25db-11eb-9053-b8ba0b81d6a2.png)

**Comment by jrieken** [comment]
Please clarify what highlight means. What happens is that a single click selects the item and double selects the item AND puts focus into the editor

**Comment by rbtyod** [comment]
>> Please clarify what highlight means. What happens is that a single click
[in the outline] selects the item and double click [in the outline] selects
the item AND puts focus into the editor

What I mean by "highlight" is that when I click on an item in the editor
the background color changes on that occurrence as well as marking all
other occurrences in the file. I think that double clicking an object in
the outline should do a similar thing for occurances of the object.

I think that you should also consider:

1. Make subsequent  double clicks in the outline advance to the next
occurrence of the object.
2. Make an RMB click in the outline bring up the same menu that it does
when right clicking that object in the editor window.

I hope this helps.
...Bob

**Comment by jrieken** [comment]
Closing this as designed. It's also likely that the extension providing your outline return non-empty ranges (leading the selection highlight). Generally, once the editor has focus and is active then it's editor rules and they make sense
