### ISSUE TITLE
Activity bar will be great if it looks small.

### ISSUE THREAD

**Issue by chosenprogram** [microsoft/vscode#110658]
The activity bar is really not good, most of the developers don't like its big width or size. I am not talking about just decrease the font size. Most people don't like its UI design. It will be great if the activity bar looks like this below. It looks great and also takes a small space.

![Capture](https://user-images.githubusercontent.com/68645164/99178384-c31e5c80-273c-11eb-9136-e8ba534c044c.PNG)

**Comment by yume-chan** [comment]
> most of the developers don't like its big width or size.
> Most people don't like its UI design.

Source?

**Comment by misolori** [comment]
We've received similar requests in the past with little activity so will close this as out of scope https://github.com/microsoft/vscode/issues/82996 https://github.com/microsoft/vscode/issues/73713
