### ISSUE TITLE
Indent using TABs by default

### ISSUE THREAD

**Issue by Rhitt01** [microsoft/vscode#110621]
# Indent using `TABs` instead of `SPACEs` by `default`
I find `TAB` indentations quite convenient. I don't have to press the left arrow key multiple times. But, unfortunately, I have to set it up every single time I create a new file in VS Code. I can't think of any situation where I would indent using `spaces`, and I'm sure a lot of people would agree.

**Comment by alexdima** [comment]
> But, unfortunately, I have to set it up every single time I create a new file in VS Code

That is not accurate. You can configure that by default new files are indented with tabs using the setting `editor.insertSpaces`:

![image](https://user-images.githubusercontent.com/5047891/99233164-2965b680-27f3-11eb-9bfc-660f5be1f220.png)
