### ISSUE TITLE
variable substitution issue

### ISSUE THREAD

**Issue by Overthat** [microsoft/vscode#110665]
- VSCode Version: 1.51.1
- OS Version: Windows 10 Home 64bits 1909

Steps to Reproduce:

1. Using GCC with MinGW.  I created a tasks.json file to tell VS Code how to build (compile) the program. 
    In the sentences:
    "args": ["-g", "${file}", "-o", "${fileDirname}\\${fileBasenameNoExtension}.exe"],
    the predefined variable "${fileDirname}" didn't work, and its value was just the same as "${workspaceFolder}"
2. I'm really annoy about that, please fix it.

Does this issue occur when all extensions are disabled?: No

**Comment by ArturoDent** [comment]
May be the same issue:  https://github.com/microsoft/vscode/issues/110665

**Comment by alexr00** [comment]
Can you please provide your full task from tasks.json?

**Comment by sean-mcmanus** [comment]
This is bug https://github.com/microsoft/vscode-cpptools/issues/6386 with the C/C++ extension -- we're looking at shipping a patch update tomorrow.

**Comment by sean-mcmanus** [comment]
@ArturoDent https://github.com/microsoft/vscode/issues/110655 seems different since it repros without the C/C++ extension and the "cppbuild" task type.

**Comment by alexr00** [comment]
Thanks @sean-mcmanus I think it is probably a dupe of microsoft/vscode-cpptools#6386, just waiting to confirm that the task type is `cppbuild` for this one. 

For #110655, I am thinking that the tasks.json provided in the bug is incorrect, which is why it doesn't have the `cppbuild` task type.

**Comment by sean-mcmanus** [comment]
If the task type is "cppbuild", then this is fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/1.1.2

**Comment by sean-mcmanus** [comment]
@alexr00 FYI, we found more tasks bugs that could affect VS Code users with "shell" type tasks, and 5 task variables were unhandled with cppbuild tasks, see https://github.com/microsoft/vscode-cpptools/pull/6539 .
