### ISSUE TITLE
Please bring link preview on hovering on the link

### ISSUE THREAD

**Issue by Shoban-Chiddarth** [microsoft/vscode#110659]
I need link previews when I hover my mouse on the link because sometimes I use a lot of images with `<img src=` and I also sometimes us a `<a>` link and I may get confused about the link I pasted so I again open the link and see what it is. Link previews when I hover my mouse helps to save that time and also to know what the link is without leaving VS Code. Please bring this feature. Thanks.

**Comment by mjbvz** [comment]
Please share an example of what this would look like

/needsMoreInfo

**Comment by Shoban-Chiddarth** [comment]
But I sent a recording of the issue and it is not there now. I will send it again
https://www.loom.com/share/781978be7f374a4796d7698c41ae34a9?sharedAppSource=personal_library
https://www.loom.com/share/ee0435ed01204f29b76f1e0bffa74d56?sharedAppSource=personal_library

**Comment by Shoban-Chiddarth** [comment]
It looks something like [this](#image1) when I hover my mouse over the image links 
<span id="image1"> !["On hover.png"](https://user-images.githubusercontent.com/68191453/99347509-51b9e780-28bd-11eb-9793-0f7fc5eaed7a.png) </span>
and like [this](#image2) when I hover my mouse over articles like [this](https://en.wikipedia.org/wiki/Visual_Studio_Code) 
<span id="image2"> !["On hover Wikipedia.png"](https://user-images.githubusercontent.com/68191453/99347575-6c8c5c00-28bd-11eb-8783-2271f466350f.png)</span>
<br>
<br>
All files available in [this folder](https://drive.google.com/drive/folders/1uWwAA6Qbur44H2bpeJH-NQ0yLP-v9tRD?usp=sharing)

#### Please bring it. Thank you!
