### ISSUE TITLE
WSL - Manipulating files - Crashes remote to WSL

### ISSUE THREAD

**Issue by andersakerberg** [microsoft/vscode#110642]
- VSCode Version:
1.51.1
- OS Version:
Windows 10 pro 1903 build 18362.1139
Steps to Reproduce:

1. open terminal as wsl
2. rm -rf node_modules in a node project
3. freeze and dissconnect from wsl
4. hafto force shutdown pc with power button

Does this issue occur when all extensions are disabled?: Yes/No
Well cant really use vscode without extensions now can I?

**Comment by meganrogge** [comment]
I'm not able to reproduce this issue. Can you pls provide a [gif](https://gifcap.dev/) of this happening?
