### ISSUE TITLE
Syntax Highlighting Stops when editor can't find the Font. (fonts need to be reinstalled)

### ISSUE THREAD

**Issue by pmkary** [microsoft/vscode#110640]
- VSCode Version: Version: 1.51.1
- OS Version: macOS Big Sur 11.0.1 (20B29)

Steps to Reproduce:

After installing Big Sur, I noticed that viscose no longer renders any syntax highlighting. I stopped all the extensions and nothing changed. Then I cleaned up all the installation files with

```bash 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/
```

And reinstalled vscode. It worked okay. Once I signed in and had my settings synced it started to not render anything so it was obvious that it has to do something with the settings. I tried all the settings till I found out it's about not finding the font name you write which is pretty strange:

![font-vscode](https://user-images.githubusercontent.com/2157285/99151871-5d39c280-26b3-11eb-9352-d1c843609756.gif)

_I'm sure you already have noticed the different themes on the windows..._

So this is one strangely odd occurrence. I don't know how to generate you more logs or information. Feel free to ask me on anything that you find can help you.

<br><br>

Does this issue occur when all extensions are disabled?: Yes

**Comment by pmkary** [comment]
Update: I noticed that when you write the `Hasklig-Medium` font, it actually finds the font and renders it, but does not render it with the highlighting.

**Comment by andrew-dixon** [comment]
Had this same issue with 'Source Code Pro'. The font was still showing as installed under Font Book. I removed it from Font Book and reinstalled it, restarted VSCode and everything is working again now.

**Comment by Aurelien-Bertrand** [comment]
Hey! I get almost the same but for java. For some reason, I get some errors with my import... I tried everything (uninstall VS, java, ...) and I still get all those errors. This is annoying since I have to code for school and I can't anymore... I don't want to switch to another editor since I am really used to VS and I love it. Any idea?

Thanks in advance,

Aurélien

PS: I am only on Mac OS Big Sur, java version 15

**Comment by dburles** [comment]
@andrew-dixon that solved the problem for me, (Programma font). Thanks!

**Comment by alexdima** [comment]
Let's track in #100840 . The current known workaround is to reinstall the fonts 🤷

**Comment by Nattapong-Tou** [comment]
It work , Thank you.
