### ISSUE TITLE
Migrate to the latest Emmet

### ISSUE THREAD

**Issue by Mister-Hope** [microsoft/vscode#110697]
VSCode is still using emmet 2.0, but emmet has a few bug fixes and update in the past year. I am running into these bugs.

I just tested on the newest emmt and the issue is gone.

So I would like to request updating vscode emmet version to the newest 2.2.1

**Comment by rzhao271** [comment]
Yep, see https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aemmet-revamp+is%3Aopen+ for a list of issues that should be fixed during the migration or shortly after

**Comment by rzhao271** [comment]
I migrated to the latest Emmet in dc5a3da, but I'll keep this issue open because that dependency is not from the actual emmetio/emmet branch, but from a branch of my own that contains an unmerged PR.

**Comment by rzhao271** [comment]
Verify by code review
