### ISSUE TITLE
"Go to definition" command show wrong file.

### ISSUE THREAD

**Issue by magpier84** [Microsoft/vscode#11064]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.2
- C/C++: 0.8.1

Steps to Reproduce:

1. Select header file of some class in workspace file browser.
2. Go to definition of some its methods.
3. Cpp file is opened but its path isn't relative to root of the workspace. In "Open Editors" section it is displayed as path from root of the drive (cut on left side: "t/subfolder/file.cpp") with hint  "/Users/admin/project/subfolder/file.cpp". The hint of tab shows "/Users/admin/project/subfolder/file.cpp"
4. Breakpoints can not be set if file was opened in above described way.
5. Two instances of the same file can be shown in tabs.

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscppsamples#177
