### ISSUE TITLE
[Feature request] Supporting Vash (expressjs view-engine)

### ISSUE THREAD

**Issue by MehdiDehghani** [Microsoft/vscode#11068]
Hello,

I know there is tones of Feature requests, but because I love `vscode`, I want to this editor support everything !

If is possible please add syntax highlighting and intellisense for `.vash` files.

Thank you !

**Comment by mrmlnc** [comment]
Great idea to create the extension.

**Comment by mrmlnc** [comment]
@MehdiDehghani, I see that the syntax highlighting in the Sublime is outdated and, I think, that I'm able to write his own. You can provide any real file with Vash syntax?

**Comment by MehdiDehghani** [comment]
As you know `Vash` engine offers `Razor like syntax`, so if you want something official, I think you need to take a look on Razor example in `ASP.NET MVC`, here is screenshot of a Razor file in `VS2015`:

![untitled](https://cloud.githubusercontent.com/assets/9152330/18050507/43775bda-6e04-11e6-91d4-73583eaf7b02.jpg)

The very important feature that you should care about in your extension, is mixing `Vash + HTML` in `.vash` files. and `intellisense ` would be great too.

I'm looking forward to hear about your extension !

**Comment by mrmlnc** [comment]
@MehdiDehghani, 

First, sorry for delay, this is my first tmLanguage file and I need to understand how it works.

I published a preview version of extension to the VS Code marketplace. Now this extension support only syntax highlighting (HTML and JS in `@keyword()` and `@{}`) and Emmet (VS Code 1.5+).

About `intellisense`, please create an issue in the repository with a detailed description of what is meant by this term in the Vash.

https://github.com/mrmlnc/vscode-vash

**Comment by MehdiDehghani** [comment]
@mrmlnc, Don't worry, thanks for that, I just checked the preview and looks like you made it !!
I'm sorry, in your post, you mentioned `VS Code +1.5`, but current version of `VS Code` is 1.4, that was a mistyping or means I should wait for v1.5 for using the extension? =p

**Comment by mrmlnc** [comment]
@MehdiDehghani, nope. Just Emmet will work only in version 1.5+. it's related to #9500.
