### ISSUE TITLE
Show/hide sidebar hotkey no longer functioning

### ISSUE THREAD

**Issue by olingern** [microsoft/vscode#110653]
- VSCode Version:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (4 days ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```
- OS Version: OSX 10.15.6

Steps to Reproduce:

1. Open a `.go` file
2. Click on a line of code
3. Hit ⌘+b

You should see that vscode attempts to navigate to a Go type definition instead of toggling the sidebar.

<img src="https://user-images.githubusercontent.com/1470297/99161741-469b6780-26c3-11eb-955d-3d1590e74c29.png" height=200 />

If you open the file search (⌘+p), and then hit ⌘+b you'll see that you're able to toggle again. 

It looks like there is an issue with the context of the keybinding.

___

### Small demo of issue

![no_sidebar](https://user-images.githubusercontent.com/1470297/99162037-a0516100-26c6-11eb-8e3e-cf50e41fbd3e.gif)

**Comment by gjsjohnmurray** [comment]
Please check your keybindings in case that combination has been bound to more than one command.

See https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by olingern** [comment]
@gjsjohnmurray 

Indeed it has. It looks like the source is a default setting as well

![image](https://user-images.githubusercontent.com/1470297/99192027-8ce1dc80-273e-11eb-8d5c-e9b612147b66.png)

**Comment by olingern** [comment]
I'm not very familiar with this code, but it looks like `CMD+B` should not be the default here and it appears to have been overwritten somehow

https://github.com/microsoft/vscode/blob/35ff2c0df8d1705af11310b004824348b8c6b32b/src/vs/editor/contrib/gotoSymbol/goToCommands.ts#L227

**Comment by alexdima** [comment]
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press your desired keybinding and check what keyboard shortcut VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and we can help decipher it for you.

**Comment by olingern** [comment]
@alexdima Not sure if you seen the screenshot [here](https://github.com/microsoft/vscode/issues/110653#issuecomment-727606572), but that conditional will always evaluate to `true` since Go has definition providers and I am in the text editor area. 

I've removed it on my machine, so it now works as it should — but this looks like a mistake in the default keybindings.

**Comment by alexdima** [comment]
@olingern That keybinding is not in our default core keybindings. Perhaps you have installed an extension that contributes that keybinding?

![image](https://user-images.githubusercontent.com/5047891/99282637-3eaf0500-2834-11eb-8c6d-c435638c348b.png)

**Comment by olingern** [comment]
@alexdima it's possible, but I'm not sure why the source would be `Default` then. Can extensions also claim `Default`?

**Comment by alexdima** [comment]
Yes, unfortunately the values are Default and User.

Default covers the core, built-in extensions and user installed extensions.

I agree that this is confusing. FYI @sandy081

**Comment by olingern** [comment]
@meganrogge @alexdima thanks for making this fix! 🙇
