### ISSUE TITLE
issue occurs when set font of text editor

### ISSUE THREAD

**Issue by limall** [microsoft/vscode#110676]
- VSCode Version:1.51
- OS Version:macOS 11.0.1

Steps to Reproduce:

1.In Settings,I set font family to Source Code Pro
2.Then my code is show in font of Source Code Pro successfully,but all my code is shown in black.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/100840#issuecomment-671267067
