### ISSUE TITLE
#ifdef conditional processing

### ISSUE THREAD

**Issue by marinehero** [microsoft/vscode#110674]
In languages such as C++, would be nice if a #define is not active that VSCode automatically collapses the code as follows:

`#ifdef _PROF_ [...] #endif`

Maybe we can configure "conditional formatting lists for pre-processor defines" ?

BONUS: Control->Collapse on `_PROF_` conditionals collapses all `#ifdef _PROF_` in current file.

see attached:
![SetValueCollapsed](https://user-images.githubusercontent.com/711872/99185792-0d570c00-2744-11eb-9de0-4627bc6a1840.png)

![SetValue](https://user-images.githubusercontent.com/711872/99185793-0e883900-2744-11eb-990c-556b22abb64e.png)

**Comment by alexdima** [comment]
@marinehero Could you please create an issue directly against the C++ extension at https://github.com/Microsoft/vscode-cpptools/issues
