### ISSUE TITLE
Snippets: Same Tabstop, Different Placeholder

### ISSUE THREAD

**Issue by PHLAK** [microsoft/vscode#110604]
I'd like to create a snippet where there's a "shared" tabstop between two different placeholders. The main reason for this is I'd like to be able to delete two (related) pieces of code simultaneously if that code isn't needed or to proceed with the tabstops as usual if those linked tabstops aren't deleted.

#### Example

```
"Class Constructor": {
	"prefix": "con",
	"body": [
		"${1:public} function __construct(${2:${3:Type} \\$${4:parameter}})",
		"{",
		"    ${2:\\$this->${4:parameter} = \\$${4:parameter};}",
		"}${0}"
	]
},
```

I would like this to produce the following code

```php
private function __construct(Type $parameter)
{
    $this->parameter = $parameter;
}
```

In which I'd like to select `Type $parameter` and `$this->parameter = $parameter;` at the same tabstop so they can be deleted together if they're not needed.

However, the actual resulting code is

```php
public function __construct(Type $parameter)
{
    Type $parameter
}
```

This is duplicating the placeholder of the first `${2:...}` tabstop.

**Comment by jrieken** [comment]
This is very unlikely to happen because it would be a "non-standard" feature - standard defined by Textmate. Did you try to tackle your challenge with snippet tranformations?

**Comment by PHLAK** [comment]
Yeah, I tried to use transformations and got close but there were some other oddities when using transformations that popped up.

**Comment by jrieken** [comment]
Namely?
