### ISSUE TITLE
VSCode laggy when not run as administrator

### ISSUE THREAD

**Issue by JoseluGames** [microsoft/vscode#110600]
Issue Type: <b>Bug</b>

When I run VSCode (Normal or Insiders), the behaviour is very laggy (Scrolling in files with even just 130 lines is a pain).

Previous reported issues have pointed at the window resolution (My screen is 3440x1440, I usually have it on one half of the screen) and making the window smaller seems to mitigate the issue, but for that I have to make the screen REALLY small (Like only seeing 3-4 lines at a time). I've tried to run it with `--disable-gpu` and with the built in GPU but nothing makes a notable difference.

Then I tried to run it as administrator and everything runs smoother than ever. 

What can be causing this? Running it as an administrator is not a viable option as I use it with Unity and trying to open a file from it always shows the admin prompt.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jordanmsllvn** [comment]
I am also having this issue. After updating, there is a *very* noticeable drop in performance which makes working in any code frustrating.
 
The issue is especially noticeable when using keyboard cursor navigation between lines.

As the OP suggests, running as administrator seems to eliminate the lag.

**Comment by alexdima** [comment]
This sounds like a duplicate of #107016 . If you close all instances of vscode and run `code --disable-renderer-accessibility` does the slowness disappear ?

**Comment by JoseluGames** [comment]
Yes! That did it, I'll close the ticket and follow the other one. Sorry for the duplication 😅 and thanks a lot for the help!
