### ISSUE TITLE
Interactive window doesn't let me type

### ISSUE THREAD

**Issue by xenidegracia** [microsoft/vscode#110687]
Issue Type: <b>Bug</b>

The interactive window doesn't let me type anything.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.77GB free)|
|Process Argv|--crash-reporter-id 5f6028d1-806b-4fa1-a0bf-65bcff8731d6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065

</details>

**Comment by alexdima** [comment]
Please report directly against the python extension at https://github.com/Microsoft/vscode-python/issues
