### ISSUE TITLE
clear terminal issue in vscode 

### ISSUE THREAD

**Issue by sysnasri** [microsoft/vscode#110677]
I have a weird behavior in vscode terminal and vi/vim. After I run clear or ctrl+l to clean my terminal, as soon as I open a file with vi/vim all previous commands which have been cleaned by clear shows up after closing vi/vim.

How can fix this issue?

https://i.stack.imgur.com/YAJSd.png

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
