### ISSUE TITLE
Keyboard shortcut to hide the F8 problems/warning popup

### ISSUE THREAD

**Issue by SwiftWinds** [microsoft/vscode#110609]
![image](https://user-images.githubusercontent.com/12981958/99132475-356f2f80-25cb-11eb-9c37-0e093264d4e7.png)

^^^ could you please consider adding a keyboard shortcut to hide the F8 warning panel popup? The ESC key doesn't do anything.

Many thanks for considering my request. :)

**Comment by sandy081** [comment]
`ESC` key closes it for me. Please check if ESC is triggering a different command for you - Use command `Developer: Toggle Keyboard Shortcuts Troubleshooting` to check the command.

**Comment by SwiftWinds** [comment]
For posterity's sake, I fixed it by changing the when statement of `vscode-neovim.escape` to `editorTextFocus && neovim.init && !markersNavigationVisible`, which was clashing with the keybind to the `closeMarkersNavigation` command. Future visitors, if you have the Neovim on your editor, consider trying this fix before creating a new issue. :)
