### ISSUE TITLE
Console corrupts non-latin output encoding

### ISSUE THREAD

**Issue by kirillta** [Microsoft/vscode#11067]
Tests, programm output, etc.

```
[<Theory>]
    [<InlineData("キ", "Ки")>]
    let ``Should transcribes words from Japanese to Russian with D-form normalization``(input, output) = 
        let container = Utils.getContainer dicPath
        let ming = new Floxdc.Ming.Control.Ming(container)

        let result = ming.Transcribe(input, "d")

        Assert.Equal(output, input)
```

```
Tests.Integration.Japanese.Should transcribes words from Japanese to Russian with D-form normalization(input: "?", output: "��") [FAIL]
      Assert.Equal() Failure
                 (pos 0)
      Expected: ��
      Actual:   ?
                 (pos 0)
```

- VSCode Version: Code - Insiders 1.5.0-insider (31f1acb8c82b8a19256d5d56127d3f81edce3745, 2016-08-26T08:00:03.472Z)
- OS Version: Windows_NT ia32 10.0.14393

**Comment by kirillta** [comment]
![image](https://cloud.githubusercontent.com/assets/19779590/18035042/ac580fdc-6d55-11e6-914c-819763228001.png)

**Comment by sandy081** [comment]
@kirillta May I know if the above log is coming through any extension?

**Comment by kirillta** [comment]
Current log is xunit, but I got same issues with F# console app, even when I tried to override Console.OutputEncoding property.

**Comment by isidorn** [comment]
Debug console has limitations in this area, dup of #6845
