### ISSUE TITLE
Click Position Issue

### ISSUE THREAD

**Issue by PallaviChapla** [microsoft/vscode#110656]
Issue Type: <b>Bug</b>

Greetings !!

After recent update there is an click position issue i have noticed, When I am clicking somewhere it's not click on that place/position only, it clicks on top position(around top 5px).

At the same time I check same issue on other applications like chrome, it's working fine. so resolve asap. it is very big issue.

Thank & Regards,
Pallavi Chapla | Web Developer

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.26GB free)|
|Process Argv|--crash-reporter-id ac08dd50-b134-46b3-a5b1-e38d7add23c6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexdima** [comment]
@PallaviChapla Does this happen after dragging vscode across screens with different DPI / zoom options or does this happen all the time?

**Comment by PallaviChapla** [comment]
@alexdima I have checked this issue today and it is working properly, but before today it happens all the time. But now it's working perfectly !!!

**Comment by alexdima** [comment]
@PallaviChapla Thank you for your reply. Please let me know if you find any reproducible steps.
