### ISSUE TITLE
PERCENT ALWAYS RED

### ISSUE THREAD

**Issue by Nekyt** [microsoft/vscode#110636]
Issue Type: <b>Bug</b>

IN C PERCENT SIGN ALWAYS RED. THIS IS NOT CORRECT. IT SHOULD BE IN RED ONLY IN PRINTF STATEMENT!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.00GB free)|
|Process Argv|--crash-reporter-id 539a6842-683d-4932-a423-6e6a8952b316|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|Memory (System)|15.88GB (9.00GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.51.3
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
cpptools|ms-|1.1.1
epitech-c-cpp-headers|nic|1.14.0
psi-header|psi|1.14.1
clang-format|xav|1.9.0

</details>

**Comment by alexdima** [comment]
@Nekyt Please report directly against the C++ extension at https://github.com/Microsoft/vscode-cpptools/issues
