### ISSUE TITLE
autocomplete failed on mac big sur

### ISSUE THREAD

**Issue by yxqiao** [microsoft/vscode#110614]
- VSCode Version:1.51.1
- OS Version:big sur 11.0.1

Steps to Reproduce:

1.autocomplet failed 
![1605320050957](https://user-images.githubusercontent.com/59404295/99136807-32893480-25f5-11eb-9f8b-296dca4eca1e.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
@jrieken Looks like a potential rendering issue with suggestions

**Comment by jrieken** [comment]
@yxqiao Do you have any suggestion font settings configured? Please check for `editor.suggestFontSize` or `editor.suggestLineHeight`

**Comment by yxqiao** [comment]
> @yxqiao Do you have any suggestion font settings configured? Please check for `editor.suggestFontSize` or `editor.suggestLineHeight`

Solved! Thank you!

**Comment by jrieken** [comment]
Interesting... Today, I have pushed a change that disallows line heights that are smaller than 8 pixel. That change change should prevent things like this from happening again
