### ISSUE TITLE
Provide a way to autocomplete things inside of comments as an extension

### ISSUE THREAD

**Issue by RDambrosio016** [microsoft/vscode#110686]
Hello, i am working on a javascript and typescript linter which has an LSP written in Rust, i would like to provide autocomplete for directives (commands through comments), however, what i have found is that vsc does not trigger the complete request if the item is inside of a comment, therefore we cannot autocomplete things such as `// rslint-ignore no-`. I tried using a work-around with trigger_characters but that does not seem to work either. It would be great if there was a way to ask vsc to trigger autocomplete despite it being a comment for your extension. I searched a lot of places to see if this could be done, i did not find anything, if there is indeed something then feel free to mention it, i may have missed it 🙂

**Comment by RDambrosio016** [comment]
It appears using all ascii letters as trigger characters does work, however, it would still be great to have a dedicated way to do this since this is a pretty big hack

**Comment by mjbvz** [comment]
Take a look at the `editor.quickSuggestions` setting. Quick suggestions are disabled in comments by default
