### ISSUE TITLE
don`t accept "font-weight" in css

### ISSUE THREAD

**Issue by fatsamuel** [microsoft/vscode#110660]
Issue Type: <b>Bug</b>

Hello, in the Visual Studio Code doesn't accept in css the command font-weight.

Best regards

Miguel

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:35:47.374Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.65GB free)|
|Process Argv|--crash-reporter-id 948881ce-5281-474d-b571-1019a7786787|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xd|ado|1.0.7
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065

</details>

**Comment by ArturoDent** [comment]
You'll have to explain the issue more.  Do you mean in a css file?  Please show your code that isn't working.  

I see the numbers in intellisense in a css file.
