### ISSUE TITLE
Tasks variables not being resolved correctly 

### ISSUE THREAD

**Issue by MorrieG** [microsoft/vscode#110655]
We have
Issue Type: <b>Bug</b>

create workspace folder
create source subfolder
create multiple .cpp  and .h files
create tasks.json 
configure command section using args
[ "-g", "-v", "${fileDirname}\\*.cpp" etc ...
${fileDirname} resolves as ${workspaceFolder} as follows;
(partial path removed)\VSCodeProjects\CaveOfProgramming\multi_file\*.cpp
if configuration is changed to\
[ "-g", "-v", "${fileDirname}\\${relativeFileDirname}\\*.cpp" etc ..
(partial path removed)\VSCodeProjects\CaveOfProgramming\multi_file\${relativeFileDirname}\*.cpp

using ${workspaceFolder} results in the same  as above.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.66GB free)|
|Process Argv|--crash-reporter-id e625b950-c642-49bd-9a30-ea432e3e5386|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gcode-syntax|app|0.4.0
scad|efb|1.0.1
Python-autopep8|him|1.0.2
AWK|lug|0.0.2
vscode-3dviewer|md2|1.0.0
dotenv|mik|1.0.1
csharp|ms-|1.23.6
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
cpptools|ms-|1.1.1
platformio-ide|pla|2.2.1
vscode-yaml|red|0.12.0
markdown-preview-enhanced|shd|0.5.13
python|tht|0.2.3
pdf|tom|1.1.0
vscode-arduino|vsc|0.3.3

</details>
<!-- generated by issue reporter -- written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled?

Also see https://code.visualstudio.com/docs/editor/variables-reference#_how-can-i-know-a-variables-actual-value for a tip about testing variable evaluation.

**Comment by MorrieG** [comment]
Hi John, Thanks for the quick update; Using the echo task, I get; Executing task in folder multi_file: echo wsp = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file; fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes; rfdn = Classes < wsp = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file;fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes; rfdn = Classes Using a key binding to alt+q defined as;[    {        "key": "alt+q",        "command": "workbench.action.terminal.sendSequence",        "args": {            "text": "fileDirname = ${fileDirname}; workspaceFolder = ${workspaceFolder}; relativeFileDirName = ${relativeFileDirname}"        },    }] I get; C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file>fileDirname = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes; workspaceFolder = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file; relativeFileDirName = Classes Building by shift+ctrl+B, with ${fileDirname}\\${relativeFileDirname}\\*.cpp results in the following error; g++.exe: error: c:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\${relativeFileDirname}\*.cpp: No such file or directory Building by shift+ctrl+B, with ${fileDirname}\\*.cpp results in the following error; g++.exe: error: c:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\*.cpp: Invalid argument instead of; c:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes\*.cpp  disabling all extensions has no effect. Tasks.json is  {            "version": "2.0.0",            "tasks": [                        {                                    "type": "process",                                    "label": "g++_build_file",                                    "command": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe",                                    "args": [                                                "-g",                                                "-v",                                                "${fileDirname}\\**.cpp",                                                "-o",                                                "${fileDirname}${fileBasenameNoExtension}.exe",                                                "-IC:\\Users\\Morri.000\\Documents\\VSCodeProjects\\CaveOfProgramming\\libs\\SDL2-2.0.12\\i686-w64-mingw32\\include\\SDL2",                                                "-LC:\\Users\\Morri.000\\Documents\\VSCodeProjects\\CaveOfProgramming\\libs\\SDL2-2.0.12\\i686-w64-mingw32\\lib",                                                "-lmingw32",                                                "-lSDL2main",                                                "-lSDL2"                                    ],                                    "options": {                                                "cwd": "C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin"                                    },                                    "problemMatcher": [                                                "$gcc"                                    ],                                    "group": {                                                "kind": "build",                                                "isDefault": true                                    },                                    "detail": "compiler: \"C:\\Program Files (x86)\\mingw-w64\\i686-8.1.0-posix-dwarf-rt_v6-rev0\\mingw32\\bin\\g++.exe\""                        },                        {                                    "label": "echo",                                    "type": "shell",                                    "command": "echo wsp = ${workspaceFolder}; fdn = ${fileDirname}; rfdn = ${relativeFileDirname}"                        }            ]} Regards,  Morrie   Sent from Mail for Windows 10 From: John MurraySent: Sunday, 15 November 2020 5:02 PMTo: microsoft/vscodeCc: mozza; AuthorSubject: Re: [microsoft/vscode] Tasks variables not being resolved correctly (#110655) Does the problem also happen if you reload with all extensions disabled?Also see https://code.visualstudio.com/docs/editor/variables-reference#_how-can-i-know-a-variables-actual-value for a tip about testing variable evaluation.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alexr00** [comment]
@MorrieG thanks for the additional information. Would it be possible for you to improve the formatting of your response? I'll be able to get to looking at this issue a bit sooner if it's easier to read.

**Comment by MorrieG** [comment]
Hi Alex, Sorry about the mess, I did not realise that replying to the email would be so messy. I have edited the item on GitHub, inserted line breaks etc to make it more readable  and removed all the extraneous bits. Regards,  Morrie. Sent from Mail for Windows 10 From: Alex RossSent: Monday, 16 November 2020 8:28 PMTo: microsoft/vscodeCc: mozza; MentionSubject: Re: [microsoft/vscode] Tasks variables not being resolved correctly (#110655) @MorrieG thanks for the additional information. Would it be possible for you to improve the formatting of your response? I'll be able to get to looking at this issue a bit sooner if it's easier to read.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alexr00** [comment]
@MorrieG thanks for making the update!

> Executing task in folder multi_file:
echo
wsp = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file;
fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes;
rfdn = Classes

These are the values you would expect, correct?

**Comment by MorrieG** [comment]
Not sure if you received my email reply to this query;
Executing task in folder multi_file:
echo
wsp = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file;
fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes;
rfdn = Classes

These are the values you would expect, correct?

Yes the values are correct when the echo task is run or the alt+q key binding, however when the key sequence shift+ctrl+B is used the folder Classes is missing from  the following;
fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file\Classes
**the result using the shift+ctrl+B key sequence the result is;**
fdn = C:\Users\Morri.000\Documents\VSCodeProjects\CaveOfProgramming\multi_file

**Comment by alexr00** [comment]
Can you please share the full output of the task when you run the task with ctrl+shift+B ?

**Comment by alexr00** [comment]
It also seems that you have the C++ extension installed. Can you disable that extension and see if the same issue happens?

**Comment by MorrieG** [comment]
Hi Alex, After reviewing the issue and checking all the files closely, I have to admit that I am at fault. The problem is that I omitted some path separator slashes in the task.json file. I had “${fileDirname}${fileBaseNameNoExtension}.exe” Instead of “${fileDirname}\\${fileBaseNameNoExtension}.exe” Thank you for your time and please accept my apologies for any inconvenience I have caused. Please close this issue.  Regards,  Morrie.    Sent from Mail for Windows 10 From: Alex RossSent: Wednesday, 18 November 2020 9:35 PMTo: microsoft/vscodeCc: mozza; MentionSubject: Re: [microsoft/vscode] Tasks variables not being resolved correctly (#110655) It also seems that you have the C++ extension installed. Can you disable that extension and see if the same issue happens?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
