### ISSUE TITLE
Changes can get lost when application crashes with dirty files open

### ISSUE THREAD

**Issue by rpanjwani** [Microsoft/vscode#1106]
VS Code froze and I lost all my changes.

**Comment by egamma** [comment]
Did you have auto save (File>Autosave) turned on?

**Comment by bpasero** [comment]
@rpanjwani can you clarify what happened to your changes? was the file empty when you reopened it after restart?

**Comment by rpanjwani** [comment]
There was no file. I had just been coding into a file for a while without saving it. I turned on auto-save feature afterwards, but I think it should be on by default.

**Comment by rpanjwani** [comment]
@bpasero I had just been coding on a file for a while without saving it. I think auto-save should be on by default.

**Comment by bpasero** [comment]
Makes sense. The only solution I can see is to frequently perform backups of the file so that a state can be restored later.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1161 is related and having a backup solution would fix both things.

**Comment by bpasero** [comment]
Closing as duplicate of #1161
