### ISSUE TITLE
auto suggestion order is reset after using custom snippet..Last used snippet is not on the top

### ISSUE THREAD

**Issue by MehbubRashid** [microsoft/vscode#110666]
- VSCode Version: 1.51.1
- OS Version: windows 10

Steps to Reproduce:

1. in a php file, lets say i am using a custom snippet extension..when i type if and it shows me suggestions (all of them triggers with "if"). These suggestions both come from the external extension snippets and vscode default language snippets. From that, i choose if block from  vscode default language snippet and if block is rendered nicely.

2. when i again type if, now my last used one is on the top, which is perfect. This should be the correct behaviour.

3. Now when i use any other snippet (not necessarily "if") lets say i used a snipped using "for"....after using this, i again try to use "if" but now, the previous one i used, is not on the top. It gets reset to the state of very first time i used "if"..so again i have to use down arrow key to go to my desired "if" snippet. This is not giving a good user experience. Should not the last used one always stay on top?

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
please add a specific sample and your snippets. thanks

**Comment by MehbubRashid** [comment]
@jrieken you can see in the gif image, when i first try to get the `if block` snippet, i had to go bottom by pressing down arrow key, because it was not on the top..but the second time, the snippet was on top because recently i have used that..third time i tried another snippet and fourth time, i again tried the `if block` snippet and now it is not on the top. again i had to find it by pressing down arrow keys multiple time...i think the latest used one should always stay on top..it only works second time..but like i said, it gets reset after trying any other snippet..
![vserror](https://user-images.githubusercontent.com/34944930/99233714-cf2e1b00-281d-11eb-9c80-b1b0e9cbe9ac.gif)

**Comment by jrieken** [comment]
What's you setting value for `editor.suggestSelection`?

**Comment by MehbubRashid** [comment]
@jrieken its recentlyused..the default one.i have not changed that
![def](https://user-images.githubusercontent.com/34944930/99234542-dc97d500-281e-11eb-8db3-1f1fefc83980.PNG)

**Comment by MehbubRashid** [comment]
hi @jrieken any update on this?

**Comment by jrieken** [comment]
Yeah, I was able to reproduce and I will push a fix

**Comment by MehbubRashid** [comment]
Great..thanks
