### ISSUE TITLE
"Format Code" command fails to format Angular2 template file

### ISSUE THREAD

**Issue by hhubik** [Microsoft/vscode#11069]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1.  Open the test file in the attached [zip archive](https://github.com/Microsoft/vscode/files/441345/test.zip) in VS Code.
2. Execute "Formate Code" command (Alt-Shift-F).
3. Lines 68 and 79 are **not** properly indented as shown in this snapshot ![snapshot](https://cloud.githubusercontent.com/assets/14813201/18036602/08b98b70-6d3d-11e6-9b77-0cd0a4297b09.png)

**Comment by aeschli** [comment]
We're using the html beautifier from beautify-web/js-beautify.
Trying the example on http://jsbeautifier.org/ shows that the issue is with formatter.

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1010

**Comment by bitwiseman** [comment]
I would expect you to keep this issue open until that one is fixed.
