### ISSUE TITLE
[Settings Sync] Rewriting syncing.json every few seconds is bad for SSDs

### ISSUE THREAD

**Issue by nchevsky** [microsoft/vscode#110606]
Issue Type: <b>Performance Issue</b>

When _Settings Sync_ is turned on, VS Code rewrites file `%APPDATA%\Code\User\syncing.json` every few seconds. This is bad for SSD longevity, since it contributes to flash media wear.

During a **35-minute** trace, I observed this file being written nearly **200 times**.

The rewriting seems to be largely gratuitious—the same unchanged data is being written over and over again.

# Steps to reproduce:
1. Turn on Settings Sync.
2. Using Process Monitor (`procmon`) or a similar utility, run a trace for `WriteFile` operations filtered by process and/or path.
3. Observe file `%APPDATA%\Code\User\syncing.json` being rewritten every few seconds.

**VS Code version:** Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
**OS version:** Windows_NT x64 10.0.19042

**Comment by sandy081** [comment]
I do not think VS Code is performing this operation. Can you please disable your extensions and try?
