### ISSUE TITLE
Font ligatures for terminal

### ISSUE THREAD

**Issue by wyz23x2** [microsoft/vscode#110630]
- VSCode Version: 1.51.1
- OS Version: Windows 10 2004 (19041.610)

Steps to Reproduce:

1. Select a font family that has ligatures.
2. Open settings.json and enter ``editor.fontLigatures: <some ligatures>``.
3. The ligatures are implemented in the editor, but not the terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by wyz23x2** [comment]
It seems that it's only for editors because of ``editor.``, but it should be able to implement it for terminals, either something like ``terminal.fontLigatures`` or include it in the original setting.

**Comment by yume-chan** [comment]
Duplicate of #34103
