### ISSUE TITLE
Delay and lag when typing in files after upgrading to Big Sur 

### ISSUE THREAD

**Issue by findtravishere** [microsoft/vscode#110683]
- VSCode Version: 1.51.1
- OS Version: Darwin x64 20.1.0

Steps to Reproduce:
**EDIT:**
1. Did a little digging around, switch on automatic graphics switching in Mac settings and type normally in VSCode for about 20 seconds or a few sentences, slight but noticeable delays will be experienced. 

Similar to issue #105446, it's happening within the files as well and not just the integrated terminal. 
Switching off automatic graphics switching fixes the issue. Not too sure if it's a Big Sur software issue throughout the system that can only be fixed by Apple but it's much more noticeable in VSCode. 

Does this issue occur when all extensions are disabled?: Yes

- I have tried reinstalling the stable build and the insiders build of VSCode and the issue persists on both versions. 
- I'm using a 2019 Macbook Pro 16" running Big Sur 11.0.1.

**Comment by karlhorky** [comment]
@findtravishere does [the solution in #105446](https://github.com/microsoft/vscode/issues/105446#issuecomment-722264044) help?

**Comment by findtravishere** [comment]
@karlhorky I tried that out and if my eyes aren't playing tricks on me, it fixed the issue within the terminal but not when typing in the files.

**Comment by augustocdias** [comment]
I'm having the same issue. The editor is freezing from time to time. Plus there's something in the system overriding the `cmd+shift+k` shortcut that I couldn't figure out what yet.

**Comment by lenineto** [comment]
I also have a Macbook Pro 16" 2019 and this typing lag is happening everywhere. A few apps (like text editor) are less noticeable but on most applications is really bad.

**Comment by pmuens** [comment]
Experiencing the same issue running Big Sur (11.0.1) and VSCode Version: 1.51.1 (Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f) on a 2016 MacBook Pro 13".

**Comment by JakeTheCorn** [comment]
experiencing the same fwiw

Big Sur: 11.0.1
VS Code: 1.51.1
MacBook Pro 13" 2020

**Comment by lenineto** [comment]
Guys, just in case this helps anyone, I got rid of my problem. 
I use an apple wireless keyboard (bluetooth) and I noticed when the keyboard was not in use, there was no more lag.
So I did a bluetooth reset (click on the bluetooth icon on the menu bar while holding SHIFT and OPTION, then select "Reset Bluetooth Module"). If that doesn't do the trick, repeat it and this time select "Factory reset all connected Apple devices".

After resetting the bluetooth module, I connected my keyboard back and everything is fine...

Hope it helps!

**Comment by nimerfarahty** [comment]
I have the same issue , I do rest all bluetooth without any success

**Comment by dreambit** [comment]
I have stable keyboard lag for 2 seconds in a terminal or editor when i do any git operation like git stash and vscode updates source control pane
![Screen Recording 2020-12-07 at 19 34 12](https://user-images.githubusercontent.com/1479661/101378038-a43a6280-38c3-11eb-8553-6f7c3478bd12.gif)
In mac terminal all works well.

**Comment by alexdima** [comment]
@deepak1556 Do you have any ideas what could be stalling the keypress events? My best guess would be that there is something going on in the main process.

**Comment by krewllobster** [comment]
@findtravishere I tried toggling automatic graphics switching, but quickly found out that mine is one of a special family of macbooks that only has a single gpu core ([according to this](https://everymac.com/systems/apple/macbook_pro/macbook-pro-retina-display-faq/macbook-pro-retina-display-how-to-manually-switch-graphics.html)) and cannot switch at all. I've still got awful keyboard lag, so I'm hoping some actual fix comes down the line soon.

**Comment by deepak1556** [comment]
Does the issue repro on latest insiders which has newer electron runtime `11.0.3` ? 


If it does can you provide the performance profile following

```
  * Open devtools
  * Choose `Performance` tab
  * Hit the reload and record button
  * Perform the steps to slowdown and stop recording
  * Attach the generated trace
```

**Comment by deepal** [comment]
This is a painful issue, luckily there's a workaround for the lagging integrated terminal as mentioned here: https://github.com/microsoft/vscode/issues/105446#issuecomment-722264044

**Comment by richardsimko** [comment]
Removing the code signature worked up until the release of the latest version (Version: 1.52.1). Now nothing helps and the built in terminal is completely unusable as a result. The lag only happens after running a command.

@deepak1556 It's better on the insiders build (~500 ms freeze vs 1.5 s on the released version) but it's still unusable.

I'm not sure how to export properly but here's a screenshot of the stack. It's exactly the same in the insiders build as the released.

![image](https://user-images.githubusercontent.com/1245031/102891924-5c890e80-445f-11eb-81be-d186e226b7f2.png)

**Comment by akshajmody** [comment]
So currently my VScode terminal lags as well in the sense that if I type in a command, i'll see a freeze but then after the 1 to 2 second freeze, what I was typing actually appears. Essentially there is a visual lapse. Is this still an issue? Is there any word of an update. Is this on VScode's side, terminal issue, or Big Sur issue??

**Comment by deepak1556** [comment]
Thanks for the profile, the lag in terminal is tracked under https://github.com/microsoft/vscode/issues/105446, please follow that for updates.

The root issue is change in behavior with how `fork` works on big sur for certain calls, the fix is being worked on in upstream as mentioned in https://github.com/electron/electron/issues/26143

**Comment by iokacha** [comment]
Hello everyone.
I'm experiencing the same lags since my upgrade to **MacOS BigSur** 
I tried disabling Hardware acceleration on argv.json but it made things worse.

My Vscode is : 
> Version: 1.52.1
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-16T16:30:02.420Z (1 mo ago)
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Darwin x64 20.2.0

**Comment by deepak1556** [comment]
This should be fixed in our latest insiders, please verify https://code.visualstudio.com/insiders

**Comment by deepak1556** [comment]
\closedWith ff85144fdd3244ffe4a5da08354667c7e57e45ef

**Comment by epiccoderjit** [comment]
Dear Mr.Okacha,
The problem happens in macOS 11.0 public beta. You should try:

1.Open terminal.
2. Press enter then continuously type anything.
3. Experience a long stutter.

P.S: I got this from this guy Integrated Terminal Lags Intermittently ·
Issue #105446 · microsoft/vscode (github.com)
<https://github.com/microsoft/vscode/issues/105446>
Probably has something to do with the OS.
Stay healthy,
SJ

**Comment by findtravishere** [comment]
I downgraded back to Catalina since this issue was raised, could anyone else on Big Sur with the Insiders build check this for me before i reupgrade back to Big Sur?

**Comment by iokacha** [comment]
> This should be fixed in our latest insiders, please verify https://code.visualstudio.com/insiders

I have just checked the insider vscode version and there is no more lags for me :)

**Comment by findtravishere** [comment]
Upgraded to Big Sur and tested it with automated graphics turned on, feels much smoother compared to 3 months ago.
Thank you to the VSCode team for fixing the issue, cheers!

/verified

**Comment by findtravishere** [comment]
\verified

**Comment by arrrrny** [comment]
/verified fixed hope to see it on vscode very soon.

**Comment by BezukhovA** [comment]
The code-insider seems ok in my case.
