### ISSUE TITLE
Can't format my codes

### ISSUE THREAD

**Issue by JannatulAdon** [microsoft/vscode#110675]
Issue Type: <b>Bug</b>

I can't format my codes by using Shift+Alt+F or any key

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (4.10GB free)|
|Process Argv|--crash-reporter-id 1e9d3987-828c-4fb1-b909-7ea2196f365c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-tester|Aka|0.0.6
competitive-programming-helper|Div|4.5.1
prettier-vscode|esb|5.7.1
code-runner|for|0.11.1
cpptools|ms-|1.1.1
clang-format|xav|1.9.0

</details>

**Comment by alexdima** [comment]
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press your desired keybinding and check what keyboard shortcut VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and we can help decipher it for you.
