### ISSUE TITLE
VS Code doesn't show amount of found matches anymore!

### ISSUE THREAD

**Issue by KathRains** [microsoft/vscode#110615]
Please return it back!!!

![image](https://user-images.githubusercontent.com/6174408/99137896-f56b7500-25e9-11eb-8dfc-08801d870f89.png)

**Comment by KathRains** [comment]
Ok, it doesn't show the amount for markdown preview. But it would be nice ot have it here too.

**Comment by edgycoder** [comment]
![](https://lolisafe.kawaaii.moe/e7XRLtCA.png)
I don't seem to have that problem, maybe you changed something in your settings?

**Comment by ArturoDent** [comment]
@edgycoder The OP is apparently only referring to the find widget in a markdown preview - the number of find references do not show there.
