### ISSUE TITLE
[Question] How to get filesystem access if running in browser (yarn run web)

### ISSUE THREAD

**Issue by qupfer** [microsoft/vscode#110680]
Hi,

can anybode give me a few hints how to access a (persistant) filesystem if running vscode in the brwoser via

```
yarn install
yarn compile
yarn run web
```

On a clean run `yarn run web --host 172.16.0.2 --port 8089` its complaining about a non exisiting filesystemprovier for MemFs.
If I add a (the?) memfs Extension "jrieken.vscode-memfs-0.0.3.vsix" via `yarn run web --host 172.16.0.2 --port 8089 --extention /path/to/the/vsix` it works in-memory.

What is the correct approach to access a persistent filesystem (at the moment, regardless its on the host or client, but preferable on the host)? 

Thanks a lot

**Comment by bpasero** [comment]
Thanks but we are currently giving L1 support for running VSCode for Web. The yarn web support is for testing purposes only.
