### ISSUE TITLE
When i open 1 thing it opens the other program i have saved

### ISSUE THREAD

**Issue by PhoenixxYT** [microsoft/vscode#110623]
Issue Type: <b>Bug</b>

I just started on this app so i have 2 programs but when i try and open 1 it opens the one i dont want it to open.
First make a program with anything in it
Second make another program
Third save the first program to your desktop
Fourth try and open the first program
If this dosent open the second program for you then i just dont know how to open my first program because it just opens the second one
Thank you for reading this. i hope (if this is a bug and not my stupidity) that it gets fixed or i can be told how to open the first program

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (7.12GB free)|
|Process Argv|C:\Users\Antma\Desktop\Program.cs --crash-reporter-id 1f8e2563-e296-4876-9a4a-9b5307bcde21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.6
vscode-icons|vsc|11.0.0

</details>

**Comment by tshaiman** [comment]
I agree , there is a bug in CTRL + P.
when you click CTRL +P it will first show the "recent used" files , and if the file you are looking for (lets say startup.sh) was also presented in another project/folder , that file will be presented and not the one located in your current directory.
you may contact me for more information : tshaiman@microsoft.com
