### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Huffman-cotdom** [microsoft/vscode#110705]
在编写python过程中出现编译错误，然后在修正了错误之后编译运行依然显示错误（事实上已经没有错误了），只有关闭vs code然后从行打开才能正常编译！

**Comment by yume-chan** [comment]
Translation:

> ## Compilation error
>
> Got an compilation error while writing Python, compile again after fixing the problem but it still shows errors (in fact there is  no error), only after closing and restarting vs code it works correctly.

**Comment by yume-chan** [comment]
1. Please file issues using template
2. Looks like caused by Python extension. Please [file issues to the extension](https://github.com/microsoft/vscode-python/issues).
