### ISSUE TITLE
Show .vscode folder even if all folders starting with a . are hidden

### ISSUE THREAD

**Issue by Nicolas1188** [microsoft/vscode#110771]
Is it possible to include a setting that allows you to show the .vscode folder even if "files.exclude" is hiding all files and directories starting with a dot . ?

Maybe a "files.alwaysShow"?

**Comment by isidorn** [comment]
Thanks for the suggestoin but we will not add this setting.
I suggest to either have a better fine tuned `files.exclude` setting
Or in the future we might add API so extensions can control what gets hidden in the explorer and then extension could implement this 
Thus closing as wont-fix for now
