### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:6000

### ISSUE THREAD

**Issue by sevenam** [microsoft/vscode#110789]
- VSCode Version: 1.52.0-insider
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Debug in Firefox (using Debugger for Firefox)
2. Randomly get popup:  "connect ECONNREFUSED 127.0.0.1:6000". Also breakpoints do not seem to hit.
![image](https://user-images.githubusercontent.com/11931091/99370667-44512d00-28be-11eb-821d-57b6b6487dc0.png)

Does this issue occur when all extensions are disabled?: No

**Comment by thunder-coding** [comment]
This error is probably happening because you habe not configured Firefox as a launch configuration in launch.json


launch.json is located in your "project root file/.vscode" folder.

Here is a sample launch.json for Firefox

```
{
    "configurations": [
        {
            "type": "firefox",
            "request": "launch",
            "reAttach": true,
            "name": "Launch localhost",
            "url": "http://localhost:8080/",
            "webRoot": "${workspaceFolder}",
            "firefoxExecutable": "C:\\Program Files\\Firefox Nightly\\firefox.exe"
        }
    ]
}
```

**Comment by sevenam** [comment]
Got this after installing new version of insiders and thought it was related to new version.
Then found this: [https://stackoverflow.com/questions/36783068/cannot-connect-to-the-target-connect-econnrefused-127-0-0-19222/36845875](https://stackoverflow.com/questions/36783068/cannot-connect-to-the-target-connect-econnrefused-127-0-0-19222/36845875)

Rebooted PC and everything was fine. Breakpoints working again too.
