### ISSUE TITLE
Double-clicking in Source Control commit message box may open a file in the changes list

### ISSUE THREAD

**Issue by vaindil** [microsoft/vscode#110751]
Issue Type: <b>Bug</b>

### Reproduction

1. Open a Git repository in VS Code so that the Source Control window/tab is active.
2. Change at least one file and save it so that it appears in the Source Control changes list.
3. Single-click the file in that list so it opens and displays the before/after like normal.
4. Close the file, observe that the file is still selected/active in the Source Control tab.
5. Start entering a commit message in the box at the top of the Source Control tab.
6. Double-click a word you typed in that box (as if you wanted to highlight the whole word to delete it).

### Expected Behavior
The word is selected in the input box like normal when double-clicking a word in any input box, and nothing else happens.

### Actual Behavior
The word is selected, but the file that was clicked in step 3 also opens as if you had double-clicked it.

### System Info

VS Code version: Code - Insiders 1.52.0-insider (8f9aeb83da26902e21ca41f8d17d204d2ac216cf, 2020-11-16T11:24:42.172Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.29GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a705106d-83f5-430f-bc96-f3ab88b46638|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by Trezorro** [comment]
+1

This gets annoying while editing your commit message, and then you find you've been modifying a file at the spot of the first change.

**Comment by pentatiby** [comment]
+1 
Also reproducible on MacOS.
![image](https://user-images.githubusercontent.com/68325794/101949490-593e8900-3bfc-11eb-9a48-a8f04e0622d8.png)

**Comment by vaindil** [comment]
I just tested and I can no longer reproduce in 1.53.0-insiders.

**Comment by eamodio** [comment]
Going to call this one fixed now.
