### ISSUE TITLE
Warning: Expected min height of view on Big Sur

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110755]
- VSCode Version: OSS
- OS Version: macOS Big Sur

Steps to Reproduce:

* Run OSS
* Open a notebook
* Focus an editor inside a cell
* `2020-11-16 12:47:47.126 Electron[42819:2580112] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7ff5ddfab010>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.` error from the command line

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jwentao** [comment]
same issue

**Comment by deepak1556** [comment]
@rebornix can you attach a video demo ? I am unable to repro on master with the steps provided.

**Comment by rebornix** [comment]
@deepak1556 I was not able to reproduce this issue with latest OSS, I'm wondering if it's because we upgraded Electron

**Comment by deepak1556** [comment]
Closing for now, can reopen if we see the issue again.

**Comment by boxerxing** [comment]
The same issue in my macOS with vscode;
OSX :11.1
VSCODE:1.52.1
VUE product: debug setting file `{    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}",
            "breakOnLoad": true,
            "trace":true,
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*",
                "webpack:///./src/*": "${webRoot}/*"
            }
        },
    ]

}`
and then run debug mode the warning blow:
`Verbose logs are written to:
/var/folders/b2/x1c3nbw17n5ds8c3p9dvbq980000gn/T/vscode-debugadapter-bb3d5375.json.gz
2020-12-21 15:28:25.931 Google Chrome[58092:2058531] Warning: Expected min height of view: (<NSButton: 0x7fb50d9ea170>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.` could you give me some suggestions?
