### ISSUE TITLE
Image in different folder is not accesible in html as well as css

### ISSUE THREAD

**Issue by vighneshboga** [microsoft/vscode#110736]
The image is not printing on the screen.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PRDXN - Attempt-5</title>
    <link rel="stylesheet" href="style_attempt5.css">
</head>
<body>
    <div class="show">
        
    </div>
</body>
</html>
```
```
/* CSS - style_attempt5.css*/

.show {
    background: url("../bg/01-1.png");
    height: 100vh;
    width: 100vw;
    border: 2px solid red;
}
```

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify how exactly this is related to Editor itself?
If you are using some extensions to launch/preview your results - please report this issue in extension repo.
If it's related to editor itself - provide all info required by issue template (OS, versions, extensions, reproducible without extensions etc.)
