### ISSUE TITLE
Typescript crash

### ISSUE THREAD

**Issue by berhalak** [microsoft/vscode#110788]
Issue Type: <b>Bug</b>

Leave vscode for the night

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.64GB (5.22GB free)|
|Process Argv|--crash-reporter-id 9404496a-a422-42e3-81cc-1e7ced5f14bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
toggle-format-on-save|cbr|0.2.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
postcss|css|1.0.9
vue-peek|dar|1.0.2
dart-code|Dar|3.16.0
vscode-eslint|dba|2.1.13
make-hidden|dev|3.0.3
dotup-vscode-override-typescript|dot|1.0.4
gitlens|eam|11.0.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.2
todo-tree|Gru|0.0.188
vscode-pegjs-live|joe|0.0.2
code-beautifier|mic|2.3.3
sort-typescript-imports|mic|1.4.1
vscode-antlr4|mik|2.2.4
csharp|ms-|1.23.6
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
js-debug-nightly|ms-|2020.11.1117
debugger-for-chrome|msj|4.12.11
reload|nat|0.0.6
back-n-forth|nic|3.1.0
vetur|oct|0.30.2
vscode-scss-formatter|sib|2.0.2
svg-preview|Sim|2.8.3
pegjs-language|Sir|1.0.3
code-spell-checker|str|1.9.4
vscode-pegjs|tam|0.1.2
lorem-ipsum|Tyr|1.2.0
windows-terminal|Tyr|0.6.0
vscode-icons|vsc|11.0.0

</details>

**Comment by thunder-coding** [comment]
This issue needs more information for reproduction.

Are you talking about TypeScript Intellisense not working if left for a long time? Or some issue with the TypeScript Compiler?

**Comment by mjbvz** [comment]
Not actionable without more information
