### ISSUE TITLE
Add ability to ignore specific JavaScript suggestions to improve JavaScript first steps, onboarding

### ISSUE THREAD

**Issue by riverar** [microsoft/vscode#110783]
The `File is a CommonJS module [...] ts(80001)` suggestion that immediately appears after the first few lines of JavaScript are written is forcing users to [turn the entire feature off](https://github.com/Microsoft/vscode/issues/47299#issuecomment-381349944). Users are potentially missing out on more helpful suggestions as a result.

Feature request was made a few years back during #47299 discourse. @mjbvz mentioned the team would consider but I don't see an issue tracking such (https://github.com/Microsoft/vscode/issues/47299#issuecomment-379335075). Apologies if I missed it in search.

**Comment by mjbvz** [comment]
Tracked by https://github.com/microsoft/TypeScript/issues/28825

**Comment by riverar** [comment]
Thanks a bunch @mjbvz
