### ISSUE TITLE
Mulitselect + delete has very unexpected results

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110743]
In this video, I multiselected the contents of the `.vscode-clean` folder, and then unselected the `Code Cache` folder (using Ctrl+Click), and then when I pressed `del` it prompted for me to delete the `Code Cache` folder and not all the others, except the `Code Cache` folder as I would expect (and want).

This behavior is very dangerous, as the first time I hit this, I didn't read the confirm dialog and all of a sudden the 1 folder I didn't want deleted was the only one that was.

![delete](https://user-images.githubusercontent.com/641685/99287121-d6e2c500-2807-11eb-8e56-8d8cdfaa60b0.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/108885
We always behave like this. Though I do agree it is not the best
