### ISSUE TITLE
Add new variable for tasks/debug `execDirname` similar to `execPath`

### ISSUE THREAD

**Issue by nicolazeni-uni** [microsoft/vscode#110746]
On Windows, using VsCode portable, and setting git and mingw paths by using variable ${execPath} is impossible.  
${execPath} variable includes also Code.exe literal. 
Would it be possible to leave out "Code.exe" literal?
Or add an extra variable.

NiIcola

**Comment by joaomoreno** [comment]
What exact variable are you looking for? Is this for debug or tasks?

**Comment by nicolazeni-uni** [comment]
Well, I've a portable version of VsCode + portable git + portable mingw. 
in settings.json by using "git.path": "${execPath}\\..\\PortableGit\\bin\\git.exe", is not working properly.
the same happens in c_cc_properties.json "compilerPath": "${execPath}..\..\mingw\bin\gcc.exe"
Because ${execPath} includes also "Code.exe", it would be helpful to remove such extra info, or a new variable with simply the path.

**Comment by joaomoreno** [comment]
You probably want a new variable: `execDirname`.

**Comment by nicolazeni-uni** [comment]
Thank you!
