### ISSUE TITLE
Shorten the editor labels for git changes diff editor

### ISSUE THREAD

**Issue by devoncarew** [Microsoft/vscode#11075]
- VSCode Version: 1.4 (latest stable)
- OS Version: MacOS

The title for the git comparison editor can be very long and doesn't leave a lot of room for displaying other tab titles:

<img width="715" alt="screen shot 2016-08-28 at 6 37 09 pm" src="https://cloud.githubusercontent.com/assets/1269969/18038591/e5c45f20-6d4e-11e6-9a1b-150e71403ace.png">

Perhaps the tab text can be shortened a bit? Instead of `foo.txt ↔ foo.text (HEAD)`, perhaps something like `↔ foo.txt (HEAD)`? For long file names, this could cut the length of the tab title nearly in half.

**Comment by bpasero** [comment]
Not anymore using these labels.
