### ISSUE TITLE
Overflowing decorations

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110769]
Live Share extension currently uses the decoration API to render a name tag near the cursor

<img width="519" alt="image" src="https://user-images.githubusercontent.com/876920/99329032-2b029f00-2832-11eb-8ed3-a6993cf81685.png">

It works fine when the decoration is in the middle of the viewport (also when there are more than one line in the editor). When it's at the first line and top set to `-1rem`, the decoration will be cut off as the ViewLines/ScrollableElement has `overflow: hidden`. 

LS work arounds this issue by rendering the name tag under the line when the cursor is on the first line. While this doesn't work for notebook as often the cell input only has one line (you can also reproduce this issue with Text Editor)

<img width="550" alt="image" src="https://user-images.githubusercontent.com/876920/99329533-4de18300-2833-11eb-9f92-34b11ddcdf79.png">

I'm wondering what's the best way to mitigate this issue, maybe some floating (overflowing) decorations? It sounds crazy so I'd like to know @alexdima 's suggestion on this.

**Comment by alexdima** [comment]
The name appears to almost fit in the last screenshot.

Is it possible to do something pragmatic and just add padding to the editor when there is a live share session going on?  (The editor option is literally called [`padding`](https://github.com/microsoft/vscode/blob/f255e3e00e4aded27a855c1c5b398b150d62b6a6/src/vs/editor/common/config/editorOptions.ts#L394))

**Comment by rebornix** [comment]
> Is it possible to do something pragmatic and just add padding to the editor when there is a live share session going on

It's an interesting idea. We can try this to simply add a new pixels more for editor padding (we are already using that but they are half `em`)
