### ISSUE TITLE
Navigating back after a 'go to declaration' might leave the cursor in a slightly different spot

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11078]
Say you have this code -
```
function f() {



}

setInterval(f, 1000);
```

1. Click in the middle of `setInterval`, then next to `f`
2. Press F12 to go to the declaration
3. Press ctrl+- to navigate back
4. The cursor will be in the middle of `setInterval`, not where it was when pressing F12.

Looks like we don't save cursor position changes unless they are somewhat far from the previous position, so when navigating back, we end up somewhere near where we came from, but not the exact spot. Maybe when doing a navigation like for pressing F12, we should save the original position of the cursor in the history stack?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/62
