### ISSUE TITLE
Align the `install` buttons in the recommendations dialog with the extensions viewlet

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#110721]
The recommendations dialog currently shows 3 buttons 
![image](https://user-images.githubusercontent.com/172399/99244403-4fdf1e00-2802-11eb-897c-034e6c732c6c.png)

Suggest to change the Install button to be a drop down with the option to not sync as in the Extensions Viewlet 
![image](https://user-images.githubusercontent.com/172399/99244679-b6643c00-2802-11eb-95ab-77f3bccf3bf3.png)

**Comment by sandy081** [comment]
@bpasero Thinking of having the action with dropdown action in the notification action, what do you think?

**Comment by bpasero** [comment]
Yes makes sense to me, I like everything that reduces the number of buttons in notifications.

**Comment by sandy081** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/10746682/99833683-b47fdd00-2b62-11eb-98dc-a2c2049870bd.png">

FYI @misolori - any feedback?

**Comment by misolori** [comment]
@sandy081 looks good to me. 

related: makes me wonder if we should align the extension install button in the extension view to be the same blue color? not sure why it was ever green.

**Comment by sandy081** [comment]
Sure, we can make it blue. I do not know why it was green. @joaomoreno Any memories 😄 ?

**Comment by joaomoreno** [comment]
Since at least August 2016!!! https://code.visualstudio.com/updates/v1_5#_extension-sorting

The idea was that green was the primary button color, while the other buttons were lighter. But notifications appeared and all of a sudden every button is blue. 🤷

**Comment by sandy081** [comment]
To verify:

Tip: Use fresh user data dir and extensions dir

- Turn on Settings Sync
- Open a folder that has workspace recommendations
- Wait until workspace recommendation notification appears
- Verify that Install button has a drop down with `Install (Do not sync)` action
- Verify that these actions are working as expected
- Verify that notification is closed after performing an action
