### ISSUE TITLE
Editor Management Bug

### ISSUE THREAD

**Issue by reckigit** [microsoft/vscode#110773]
Issue Type: <b>Bug</b>

Keyboard Shortcuts Ctrl + KF does not work to "close folder"

VS Code version: VSCodium 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-12T00:31:42.540Z)
OS version: Linux x64 5.8.0-29-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU        P6100  @ 2.00GHz (2 x 1133)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|4.50GB (1.92GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by yume-chan** [comment]
Make sure you release the <kbd>Ctrl</kbd> key before press the <kbd>F</kbd> key, or it will become <kbd>Ctrl + K</kbd> <kbd>Ctrl + F</kbd>.

If it still doesn't work, please take a screenshot of your keyboard shortcuts editor (<kbd>F1</kbd>, 'Preferences: Open Keyboard Shortcuts') when filtering "ctrl+k f", should look like:

![image](https://user-images.githubusercontent.com/1330321/99355734-cb64cc00-28e3-11eb-8591-2a4f5fb4b762.png)
