### ISSUE TITLE
Can't debug frontend in chrome devtools, sourcemap timeout

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#110777]
- Launch codespace
- Open devtools
- Wait a bit, see `DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/8f9aeb83da26902e21ca41f8d17d204d2ac216cf/core/vs/workbench/workbench.web.api.js.map: Load canceled due to load timeout`

Devtools has a 30s timeout for loading sourcemaps, which has not made it to our Electron version, but will. It can take 2 minutes or more to download our giant sourcemap, which is many MBs

**Comment by roblourens** [comment]
This has made it to Insiders now. @deepak1556 will we be able to get a patch to disable this timeout or something?

**Comment by deepak1556** [comment]
We will be taking out Electron 11 for November release, will be fixed in the next insiders release after endgame.

**Comment by roblourens** [comment]
Still an issue in Insiders, is there a fix that we are expecting to get for this?

![image](https://user-images.githubusercontent.com/323878/102249745-8a96ad80-3eb7-11eb-90dc-d74d60ee5058.png)

**Comment by DK-2013** [comment]
is way to add source map manual?

**Comment by MatteoPossamai** [comment]
HI. Can I work on this problem? Can you help me with a pointer and some more instructions?

**Comment by jiang-zhong-xi** [comment]
have same issue

**Comment by deepak1556** [comment]
Closing as not actionable.
