### ISSUE TITLE
[json] show already defined properties too

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110790]
I very often type a settings name in the JSON settings editor only to not see it because I had it already defined. It would be great if the suggest widget could show all setting keys to me, even the ones I already had defined. Probably when completing an already defined key, it should move my cursor to the location where I have it defined:

![image](https://user-images.githubusercontent.com/900690/99372494-89765e80-28c0-11eb-85a2-a655bb6ff93b.png)

**Comment by sandy081** [comment]
@aeschli Is this a JSON language feature? Can the suggest widget show all properties even if they are defined already?
