### ISSUE TITLE
Use the same dialog for searching across all files and across a single file

### ISSUE THREAD

**Issue by kaba2** [microsoft/vscode#110742]
## Suggestion

Unify all searches under the same spacy dialog used for searching across multiple files. 

## Weaker suggestion

Make it an option to do so.

## Background

Searches across multiple files (Ctrl+Shift+F/H) are currently performed in a separate spacy dialog, which is great. It shows you the places where the match was found. If replace is enabled, you will also see the result. And you can remove matches by hand.

Searches across a single file (Ctrl+F/H) on the other hand are performed in a tiny box with limited functionality. There is no preview nor other nice properties of the spacy dialog. I don't understand the value of this tiny simplified search over the spacy one.

**Comment by roblourens** [comment]
I think the use cases between these two are different, and would like to keep separate UIs
