### ISSUE TITLE
IntelliSense 

### ISSUE THREAD

**Issue by popiter** [microsoft/vscode#110754]
- VSCode Version:  1.51
- OS Version: windows 10

Steps to Reproduce:

When writing a letter, hints of 2 or more lines are usually shown, now they are shown in one line, which is not very convenient to look at and choose between them, this bug appeared not long ago, did not change any settings in the program

Does this issue occur when all extensions are disabled?: Yes

**Comment by popiter** [comment]
Hello

**Comment by popiter** [comment]
![image](https://user-images.githubusercontent.com/49988109/99309537-ad0eba00-286a-11eb-8885-0c88445abc83.png)

**Comment by gjsjohnmurray** [comment]
See if https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206 helps

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Asuggest
