### ISSUE TITLE
Editors: consider to allow name/description for file based editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110738]
Currently we ignore label+description for file inputs, but some custom file system providers may be able to provide a better label/description compared to what we do (e.g. Git). This is to investigate if we can allow that, probably only for custom contributed schemes, not our core ones.

**Comment by gjsjohnmurray** [comment]
Apparently related to #2351

**Comment by bpasero** [comment]
Virtual documents already support label+description though. We only did not support them for normal editors so far with the rationale that we did not want to allow an extension to override the name+description for a file on disk. I would probably still not allow that, but open this up in case the editor resource is not a built-in one.
