### ISSUE TITLE
#8536 and #57317 (auto closing / wrap with) are closed since 2018, but the feature is not available yet

### ISSUE THREAD

**Issue by Niko-O** [microsoft/vscode#110709]
Issues #8536 and #57317 are closed since 2018. #57317 mentions the new setting "editor.autoWrapping". I have downloaded the currently latest version of VS Code, which is 1.51.1, added `"editor.autoWrapping": "never"` to the settings (does not seem to be recognized because it's displayed in lighter colors), but text still gets wrapped in parentheses.
So did this feature really not make it into release since it was implemented more than two years ago?
If so, please consider this a feature request.

**Comment by usernamehw** [comment]
Maybe it was renamed? `editor.autoSurround` & `editor.autoClosingBrackets` & `editor.autoClosingQuotes` sound like what you're looking for.

**Comment by Niko-O** [comment]
@usernamehw 
Thanks. Setting editor.autoSurround to "never" seems to work in a few rudimentary test.
