### ISSUE TITLE
Sometimes folder cannot be selected in VS Code Explorer

### ISSUE THREAD

**Issue by alexandis** [microsoft/vscode#110727]
Issue Type: <b>Bug</b>

Sometimes - when copy-pasting folder with subfolder - the copied top-level folder cannot be selected with mouse... Then, in some moment, selection works normally.. In the screenshot below - I've copied folder with subfolder and the file inside this subfolder. Then I renamed the copied file, then - its folder. But I cannot rename top-level folder, because I cannot select it with mouse.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.46GB free)|
|Process Argv|--crash-reporter-id 10753073-7d26-46ab-b788-80a3c2efbd9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.0
githistory|don|0.6.14
prettier-vscode|esb|5.7.2
csharp|ms-|1.23.6
vscode-typescript-tslint-plugin|ms-|1.2.3
vscodeintellicode|Vis|1.2.10

</details>

![image](https://user-images.githubusercontent.com/6149843/99257820-482e7200-2820-11eb-8c40-ac9128779d80.png)

**Comment by isidorn** [comment]
Seems like this https://github.com/microsoft/vscode/issues/107263
Anyways a bug in the file-explorer, no plans to tackle it right away thus assigning to backlog.

**Comment by isidorn** [comment]
No plans to fix -> closing
