### ISSUE TITLE
Swapping escape with tilde using xmodmap is not respected by VSCode

### ISSUE THREAD

**Issue by lbrande** [microsoft/vscode#110722]
- VSCode Version: 1.51.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Use `xmodmap` to swap escape with tilde (or any other character generating key).
2. Use `ctrl+f` to open find, then press tilde (nothing happens).

The original escape still works as an escape while the original tilde does not generate a tilde. I've tried both with and without `"keyboard.dispatch": "keyCode",`. The issue only occurs when a text field is focused and only in VSCode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeisner** [comment]
I have the same problem.

**Comment by jeisner** [comment]
I was previously able to fix the issue in the rest of VSCode by setting `keyboard.dispatch` to `keyCode` in settings, as recommend on a couple of other tickets, such as #23991.  But it still seems to be a problem with Jupyter.
