### ISSUE TITLE
Find / replace in selection seems to be buggy

### ISSUE THREAD

**Issue by alexandis** [microsoft/vscode#110731]
Issue Type: <b>Bug</b>

Not all occurences of the text to replace are found in the selected area. Please see attached - you can see there are several occurences of word "module" - but only 1 is found, i.e. I cannot replace all occurences of a word in selected area. I've tried to unselect and select the area again, but to no avail. But sometimes everything works properly, so it's kind of random issue.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.40GB free)|
|Process Argv|--crash-reporter-id 10753073-7d26-46ab-b788-80a3c2efbd9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.0
githistory|don|0.6.14
prettier-vscode|esb|5.7.2
csharp|ms-|1.23.6
vscode-typescript-tslint-plugin|ms-|1.2.3
vscodeintellicode|Vis|1.2.10

</details>

![image](https://user-images.githubusercontent.com/6149843/99266592-98f79800-282b-11eb-8067-a8ead1262c74.png)

**Comment by SergeyBeloglazov** [comment]
+1
Replace in selection doesn't work in intuitive way, like in Notepad++ and any other text editor.
There is no way to change selection, when replace window is opened. You have to make a selection before starting replacement.
**A case:**
I copy a string, I want to be a replacer to buffer. 
Then I select a string I want to be replaced;
I press a key for replace dialog. It puts selected string to 1st line. It's good, it's expected.
Then ever I press "Find a selection" button, then select, or sect at first - it doesn't matter - it keeps selected only that line, that was selected when I press a key for replacing.
The solution:
1. Copy 1st value to buffer
2. Select lines
3. Summon the replace dialog
4. Press "Find in selection". You selection is now FIXED!
5. Now find 2nd value, copy to buffer, insert in dialog.
Enjoy :)
