### ISSUE TITLE
not able to write on editor

### ISSUE THREAD

**Issue by Mohit-Sharma1** [microsoft/vscode#110785]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

please check whats the issue

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.60GB free)|
|Process Argv|--crash-reporter-id 05bf6a46-1e94-4f77-a4d7-133c3eef636c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|2.0.0
vscode-django|bat|1.0.0
open-html-in-browser-ml|cml|0.0.6
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
opencv-intellisense|did|0.0.4
python-extension-pack|don|1.6.0
vscode-npm-script|eg2|0.3.13
vscode-flutter-files|gor|2.2.0
opencv-snippets|gsG|1.2.2
simply-view-image-for-python-opencv-debugging|joh|0.0.6
flutter-intl|loc|1.13.0
MagicPython|mag|1.1.0
python|ms-|2020.10.332292344
vscode-pylance|ms-|2020.11.0
cpptools|ms-|1.1.0
awesome-flutter-snippets|Nas|2.0.4
autodocstring|njp|0.5.3
vscodeintellicode|Vis|1.2.10
vim|vsc|1.17.1
jinja|who|0.0.8

</details>

**Comment by thunder-coding** [comment]
Any steps to reproduce?

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
