### ISSUE TITLE
Frequent prompt update

### ISSUE THREAD

**Issue by liqianglai** [Microsoft/vscode#11074]
- VSCode Version: July 2016 (version 1.4)
- OS Version: win10
1. Update is complete, open again, and prompt update

**Comment by joaomoreno** [comment]
What's your current commit hash version?

![image](https://cloud.githubusercontent.com/assets/22350/18045520/7a1067bc-6dd3-11e6-84a6-c2501204c087.png)

**Comment by liqianglai** [comment]
![_20160922153554](https://cloud.githubusercontent.com/assets/7068847/18740116/7f64b3d4-80da-11e6-8d6c-752a8a05b4fc.png)

**Comment by joaomoreno** [comment]
You still have this problem? If you download a fresh setup and install it, does it keep happening? If you uninstall & install, does it keep happening?

**Comment by liqianglai** [comment]
I have installed the new version, restart several times, did not appear this situation
thank you !

**Comment by liqianglai** [comment]
I have uninstall  & installed the new version, restart several times, did not appear this bug.
thank you.

**Comment by joaomoreno** [comment]
Thank you!
