### ISSUE TITLE
Notebook renderer should give preference to mimetypes which can be renderred

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#110750]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
2. Select a Python kernel (bottom left)
3. Install boken from cell
	`!pip install bokeh`
4. In the next cell run
```python
# Standard imports 

from bokeh.io import output_notebook, show
output_notebook()
```
**VS Code displays the following in an output**
* `No renderer could be found for MIME type: application/vnd.bokehjs_exec.v0+json`
* As a user i don't know what this is & I ignore it.

5. In the next cell run
```python
# Plot a complex chart with interactive hover in a few lines of code

from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.sampledata.autompg import autompg_clean as df
from bokeh.transform import factor_cmap

df.cyl = df.cyl.astype(str)
df.yr = df.yr.astype(str)

group = df.groupby(by=['cyl', 'mfr'])
source = ColumnDataSource(group)

p = figure(plot_width=800, plot_height=300, title="Mean MPG by # Cylinders and Manufacturer",
           x_range=group, toolbar_location=None, tools="")

p.xgrid.grid_line_color = None
p.xaxis.axis_label = "Manufacturer grouped by # Cylinders"
p.xaxis.major_label_orientation = 1.2

index_cmap = factor_cmap('cyl_mfr', palette=['#2b83ba', '#abdda4', '#ffffbf', '#fdae61', '#d7191c'], 
                         factors=sorted(df.cyl.unique()), end=1)

p.vbar(x='cyl_mfr', top='mpg_mean', width=1, source=source,
       line_color="white", fill_color=index_cmap, 
       hover_line_color="darkgrey", hover_fill_color=index_cmap)

p.add_tools(HoverTool(tooltips=[("MPG", "@mpg_mean"), ("Cyl, Mfr", "@cyl_mfr")]))

show(p)
```

**VS Code displays the following in an output**
`No renderer could be found for MIME type: application/vnd.bokehjs_exec.v0+json`

Change the mime type to `application/javascript` in the first cell & second cell, & now you get output.

**Suggestion**
* VS Code should use mime types for which renderers are availabl
* In this example if there is no renderer for mime type` applciation/vnd.bokehjs...`, then why display it when we can render `application/javascript`.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
@DonJayamanne it's currently controlled by the notebook content provider https://github.com/microsoft/vscode-jupyter/blob/cff6406f7d942b13fdc8dd16688ff9c376aa43da/src/client/datascience/notebook/helpers/helpers.ts#L172-L186, which says `application/vnd.* ` has higher order than others. 

However I think our current behavior is not friendly as notebook content providers don't know what renderers users have installed on their machine. I'm going to change the behavior to find the best available notebook renderer other than always always the first one.
