### ISSUE TITLE
无法勾选Go: Install\Update tools 

### ISSUE THREAD

**Issue by tabii-817** [microsoft/vscode#110706]
Issue Type: <b>Bug</b>

VScode中按F1，找到Go: Install\Update tools后，点击没有可勾选的工具包，尝试点击该命令多次没有后续反应。

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.60GB free)|
|Process Argv|--crash-reporter-id 15c49039-91f6-4e7c-baf4-8e248b134b52|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
python-preview|don|0.0.4
go|gol|0.18.1
vsc-python-indent|Kev|1.12.0
python-path|mge|0.0.11
vscode-language-pack-zh-hans|MS-|1.51.2
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
autodocstring|njp|0.5.3
vscode-yaml|red|0.12.0
python|tht|0.2.3
python-extended-snippets|tus|0.0.1

</details>

**Comment by yume-chan** [comment]
Translation:

> ## Can't check Go: Install/Update tools
>
> Press F1, find Go: Install/Update tools, click, there is no available packages to check, tried many times and nothing happens.

**Comment by yume-chan** [comment]
Caused by the Go extension, please [file an issue to the extension](https://github.com/golang/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=)
