### ISSUE TITLE
Подсказки

### ISSUE THREAD

**Issue by popiter** [microsoft/vscode#110752]
при написании кода, подсказки показываются в одну линию, раньше показывались списком из 4-5 строк

**Comment by popiter** [comment]
![image](https://user-images.githubusercontent.com/49988109/99305174-746be200-2864-11eb-8592-af9d48637119.png)

**Comment by popiter** [comment]
when writing code, hints are shown in one line, previously they were shown as a list of 4-5 lines

**Comment by popiter** [comment]
IntelliSense
When writing a letter, hints of 2 or more lines are usually shown, now they are shown in one line, which is not very convenient to look at and choose between them, this bug appeared not long ago, did not change any settings in the program

**Comment by mkhoussid** [comment]
Нужно сдвинуть рамку вниз

![dLayW](https://user-images.githubusercontent.com/44326107/99546487-81edad00-29c7-11eb-8fe8-181c492eb087.gif)

[Stackoveflow issue](https://stackoverflow.com/questions/64789393/visual-studio-code-intellisense-showing-one-suggestion-at-any-time#:~:text=VS%20Code%201.51%20made%20the,the%20number%20of%20visible%20suggestions.)
