### ISSUE TITLE
git changes sometimes not visible Code-Insiders edition

### ISSUE THREAD

**Issue by rcrooks** [microsoft/vscode#110734]
Issue Type: <b>Bug</b>

This is intermittent, and I haven't been able to find a pattern of steps to reproduce it. In the Source Control panel (again, this is the Code Insiders edition only), the list of changed files do not appear - the panel is blank. Git operations still work normally.

VS Code version: Code - Insiders 1.52.0-insider (8f9aeb83da26902e21ca41f8d17d204d2ac216cf, 2020-11-16T11:18:46.350Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|64.00GB (21.26GB free)|
|Process Argv|--crash-reporter-id 06bed51c-0413-4152-bfcc-97f311ddef5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-openapi|42C|3.8.0
format-selection-as-html|adr|2.3.0
auto-add-brackets|ali|0.11.0
vs-redoc-viewer|Ati|0.0.3
auto-alignment|Aut|1.1.2
shell-syntax|bma|1.0.1
htmltagwrap|bra|0.0.7
json-tree-view|Cha|2.6.0
path-intellisense|chr|2.3.0
textpad-icon-theme|dam|1.19.20
jshint|dba|0.11.0
vscode-great-icons|emm|2.1.60
indent-switcher|eph|1.2.1
json-tools|eri|1.0.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
duplicate|gee|1.0.1
ginfuru-vscode-jekyll-syntax|gin|0.1.1
gruvbox-ish|Gra|0.5.2
docthis|joe|0.7.1
vscode-colorize|kam|0.8.17
string-manipulation|mar|0.4.3
rainbow-csv|mec|1.7.1
openapi-lint|mer|1.2.0
git-graph|mhu|1.27.0
compare-folders|mos|0.18.0
rose-pine|mvl|0.3.20
file-and-folder-icons|nex|1.0.4
vscode-json-editor|nic|0.2.3
prettier-standard-vscode|num|0.8.1
indent-rainbow|ode|7.4.0
color-tabs-vscode-ext|ore|0.12.1
vscode-yaml-sort|Pas|2.7.2
openapi-designer|phi|0.3.0
material-icon-theme|PKi|4.4.0
htmlescape-vscode-extension|ray|0.0.7
vscode-yaml|red|0.12.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.9.4
json2yaml|tux|0.2.0
alphabetical-sorter|ue|2.0.1
remove-empty-lines|use|0.0.6
terminal-all-in-one|yas|1.11.13

(30 theme extensions excluded)

</details>

**Comment by eamodio** [comment]
If you hit the refresh button when you experience the issue does it fix it?

**Comment by waxidiotic** [comment]
> If you hit the refresh button when you experience the issue does it fix it?

I've been experiencing the same thing off and on between Insider builds and no, the refresh button has no effect.

![CleanShot 2020-11-19 at 09 01 30](https://user-images.githubusercontent.com/8037469/99676007-ee0ef600-2a45-11eb-97a5-a18c37cda568.jpeg)

**Comment by rcrooks** [comment]
I'm still seeing this. But it's odd:

- only on Code Insiders, not the current release
- only for one repository (others are fine): https://github.com/BrightcoveLearning/apis 

Here's what the git log shows:
`Open repository: /Users/rcrooks/GitHub/apis
> git status -z -u
> git symbolic-ref --short HEAD
> git check-ignore -v -z --stdin
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :.gitignore
> git ls-files --stage -- /Users/rcrooks/GitHub/apis/.gitignore
> git cat-file -s 84310cefc4ce1af2c93d335890ff25d151d06c92
> git config --local branch.master.github-pr-owner-number
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /Users/rcrooks/GitHub/apis/.gitignore
> git cat-file -s 84310cefc4ce1af2c93d335890ff25d151d06c92
> git show --textconv :.gitignore
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
`

**Comment by rcrooks** [comment]
ps. I've also tried the refresh button -- no effect

**Comment by eamodio** [comment]
Hrm, is ` /Users/rcrooks/GitHub/apis` the exact casing of those folders on disk? Is there anything else different about this folder/repo? Is it still reproducible if you clone that repo into a new folder?

**Comment by rcrooks** [comment]
@eamodio I'll try that. We have another couple of dozen repos with nearly identical structures. But that's why this one is all the more puzzling....

**Comment by rcrooks** [comment]
no problem for new repo with same files copied over. Think I'll try removing my local copy of the problem one and re-cloning it to see if that fixes everything.

**Comment by rcrooks** [comment]
@eamodio and yes, removing and re-cloning the repo fixed it. Thanks!
