### ISSUE TITLE
Typescript: How to highlight all words like the current word ( Irrespective of token type )

### ISSUE THREAD

**Issue by rbadapanda** [microsoft/vscode#110772]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. open a typescript react file with the following code
```
                               onClick={() => {
                                    this.props.openSideBar(); // openSideBar
                                }}
```
2. in settings 
editor.occurrencesHighlight = true, and 
editor.semanticHighlighting.enabled=false

Does this issue occur when all extensions are disabled?: Yes
can't repro this with vscode.typescript-language-features extension disabled

**Comment by yume-chan** [comment]
I still don't understand what you want.

Do you want all text to be in same color like in notepad?

**Comment by rbadapanda** [comment]
> I still don't understand what you want.
> 
> Do you want all text to be in same color like in notepad?

Yes all text to be highlighted but with the ones which are recognized by the syntax system, should syntax highlight

In markdown file, the code renders like this:
![image](https://user-images.githubusercontent.com/6469237/99419108-968b5180-28b0-11eb-8947-8daecb266ff8.png)

In typescript react file, it does not highlight the words inside the comments
![image](https://user-images.githubusercontent.com/6469237/99419254-c33f6900-28b0-11eb-9d3e-05827b8804c3.png)

I want all the four instances of the word 'openSideBar' to be highlighted. If function names could still be syntax highlighted that is better.

**Comment by mjbvz** [comment]
This is the expected behavior currently. Occurrence highlighting uses semantic knowledge when it is available, otherwise it falls back to simple text matches

@jrieken Assigning you for a potential feature request on disabling semantic occurrence highlights and always using text based highlighting
