### ISSUE TITLE
Remote debug nodejs app in docker container not working

### ISSUE THREAD

**Issue by reyisaacm** [microsoft/vscode#110786]
- VSCode Version: 1.51.1
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Set breakpoint
2. Run the app and the breakpoint will not be hit

Does this issue occur when all extensions are disabled?: Yes

hi,
after upgrading to 1.51.1 from 1.50.1 suddenly the breakpoint is not triggering.
I've tested it by setting the same breakpoint on 1.50.1 and 1.51.1, the former triggered the breakpoint while the latter didn't.

i have no idea where is the error but i've attached both the trace log from version 1.50.1 and 1.51.1. Hope this helps

For v1.50.1
[debugv1.50.1.json.gz](https://github.com/microsoft/vscode/files/5552328/debugv1.50.1.json.gz)

For v1.51.1
[debugv1.51.1.json.gz](https://github.com/microsoft/vscode/files/5552333/debugv1.51.1.json.gz)

Following launch.json configuration
```js
        {
            "type": "node",
            "request": "attach",
            "name": "Local Docker",
            "address": "127.0.0.1",
            "port" : 5858,
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/src/app",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "trace":true
        },
```

thanks for your help

**Comment by connor4312** [comment]
Can you try the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) to see if things work better there?

**Comment by connor4312** [comment]
Thanks for the issue. It looks like your source file is at

```
/Users/reynhart/Desktop/Work/developer-portal/src/core/plugin.js
```

And it's also at that same path within the docker container (or you have a compilation step that adds a `//# sourceURL=file:///Users/reynhart/Desktop/Work/developer-portal/src/core/plugin.js` comment to the file). So therefore the remoteRoot, which tells the debugger that the expected path is `/src/app/src/core/plugin.js`, is incorrect.

Let us know if you run into any more issues after fixing that.

**Comment by reyisaacm** [comment]
hi Connor thanks for replying,

can you suggest on how to fix the path?

the same source code and compilation step is used both in vscode version 1.50.1 and vscode version 1.51.1, yet only version 1.51.1 fail to trigger the breakpoint

thanks for your help

**Comment by connor4312** [comment]
It looks like just removing the localRoot and remoteRoot would make it work

**Comment by reyisaacm** [comment]
hi Connor,
it's finally working :D
anyway do you have any idea why on version 1.50.1 it still works when we still have the localRoot and remoteRoot set?

by the way, thank you very much for your help 👍 
you can close this issue for now

**Comment by connor4312** [comment]
Thanks for confirming. In 1.51 we changed how some breakpoints were bound. I'm not sure why your scenario worked before with the incorrect path mapping.
