### ISSUE TITLE
ステータスバーのリポジトリの表示が増える

### ISSUE THREAD

**Issue by maetada** [microsoft/vscode#110717]
リポジトリの更新をクリックしてコミットしてエラーになった場合リポジトリの情報がステータスに増える。

<img width="410" alt="image" src="https://user-images.githubusercontent.com/52196135/99243023-60fc4f00-2843-11eb-9ef8-4c511de8e56a.png">

**Comment by yume-chan** [comment]
Duplicate of #110718

**Comment by yume-chan** [comment]
Anyway a translation:

> # Repository display in status bar multiplied
>
> Clicked "update repository", committed, errored out, then the information of repository in the status bar multiplied.
