### ISSUE TITLE
Click on item in References view doesn't navigate to reference in editor

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#110724]
Issue Type: <b>Bug</b>

Tried only on JS/TS, but most likely same for other languages because Copy from context menu returns correct positions for each item.

Steps to reproduce:
1. Open JS/TS file and wait when TS will finish initialization (tried 
1. Call Find All References on function/method/variable that is referenced in other files.
1. Click on any reference item from other file in References view.
1. File preview opens in first line for new files previews or on previous cursor position in already opened editors (not on reference).
(Sometimes it opens not on the first line, but still not on reference position)

If I use Copy from context menu on same item - it copies correct line/column for reference in file.
No problems with Peek view for Find references - click shows preview on correct line, double click navigates to reference.

Looks like Call Hierarchy has same problem - opens first line of the file, or opens somewhere in the file, but not on function/method reference.

VS Code version: Code - Insiders 1.52.0-insider (46ff33b6b6ec2db5906f52c236c7f712988516ff, 2020-11-16T07:22:48.113Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.25GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
Already fixed

**Comment by IllusionMH** [comment]
Yep, works as expected now. Thanks!
Not sure why I haven't found related issue/PR/commit

**Comment by jrieken** [comment]
No worries, that's the one https://github.com/microsoft/vscode/issues/110707. Kinda obscure
