### ISSUE TITLE
VSCode will not launch on MacOS 10.15.7

### ISSUE THREAD

**Issue by cooperchall** [microsoft/vscode#110761]
- VSCode Version: 1.51.1
- OS Version: macOS 10.15.7

Process:               Electron [598]
Path:                  /Applications/Visual Studio Code.app/Contents/MacOS/Electron
Identifier:            com.microsoft.VSCode
Version:               1.51.1 (1.51.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Electron [598]
User ID:               503

Date/Time:             2020-11-17 09:21:45.198 +1100
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Anonymous UUID:        7971D466-6BF6-548D-FE45-E3C1031D7828

Time Awake Since Boot: 170 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Visual Studio Code.app/Contents/MacOS/Electron
  Reason: no suitable image found.  Did find:
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Visual Studio Code.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x108c07000 -        0x108c2fff7 +com.microsoft.VSCode (1.51.1 - 1.51.1) <4F31D697-6E27-3F29-A5AF-64158B52D8E6> /Applications/Visual Studio Code.app/Contents/MacOS/Electron
       0x108dcf000 -        0x108e60f47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld
    0x7fff366de000 -     0x7fff36795ff7  com.apple.MediaPlayer (1.0 - 1.0) <FE739C02-1000-36C8-9FAD-26FF3D8240CB> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer

Model: iMac18,2, BootROM 428.0.0.0.0, 4 processors, Quad-Core Intel Core i5, 3 GHz, 8 GB, SMC 2.40f1
Graphics: kHW_AMDRadeonPro555Item, Radeon Pro 555, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x16E), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.2)
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: iPhone, Ethernet, en6
Serial ATA Device: APPLE HDD HTS541010A9E632, 1 TB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: iPhone
Thunderbolt Bus: iMac, Apple Inc., 41.4

Steps to Reproduce:

1.Download zip file
2.Unzip and copy .app to applications folder

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
what software are you using to unzip ?

what is the output of `zipinfo -m <path-to-zip>`

**Comment by cooperchall** [comment]
I am using iZip :( 
And I tried to unzip uising RAR and same result. Sorry but I can't even interpret what the line of code is supposed to do or how to use it

**Comment by deepak1556** [comment]
Can you try using `unzip` utility , the original error message is due to invalid library contents which is very likely a side effect of the archive extractor you are using.
