### ISSUE TITLE
Pressing enter in the command palette will run the previously focused button in the toolbar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#110745]
![Kapture 2020-11-16 at 09 53 02](https://user-images.githubusercontent.com/35271042/99290383-12bf5f80-27f3-11eb-9c02-481dfda49514.gif)

Steps to Reproduce:

1. Place focus on add new cell buttons
2. Open command palette and hit enter on any item
3. :bug: New cell is added

**Comment by rebornix** [comment]
This applies to all toolbars, and all vs code components.

I guess it shares the same root cause as https://github.com/microsoft/vscode/issues/110427#issuecomment-726994727
