### ISSUE TITLE
[Feature request] Make it possible to create a new GUID in a snippit.

### ISSUE THREAD

**Issue by guidorobben** [microsoft/vscode#110704]
Make it possible to create a new GUID in a snippit. Maybe use the Variable option. something like "${NEWGUID}" or something?

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Afeature-request+label%3Asnippets
