### ISSUE TITLE
Deleting a folder freezes VS Code

### ISSUE THREAD

**Issue by vinitshahdeo** [microsoft/vscode#110816]
Deleting a folder (containing few files inside it) freezes VS Code which results in sudden hike in RAM consumption. It seems like delete action enters to deadlock condition.

- VSCode Version: `v1.47.0`
- OS Version: macOS Catalina `v10.15.7` (Darwin x64 19.6.0)

**Steps to Reproduce:**

1. Open a folder containing subfolder (with some files inside it) in VS Code
2. Try to delete the subfolder using VS Code editor UI.
3. And here you go!

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Please update to latest vscode. Your are using a 4 months old version.
If you can still repro double check with VS Code insiders https://code.visualstudio.com/insiders/
Let us know and we can reopen this if needed
