### ISSUE TITLE
Investigate file system provider changes in opened editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#110854]
I do think it is fishy that editor don't update/change when the filesystem provider goes (and returns). Adding @bpasero what the semantics are supposed to be. I think unregistering a file system provider is similar to cases where files are deleted on disk, when a new provider for the same scheme return the editor should probably update. 

For readonly-ness we also have https://github.com/microsoft/vscode/issues/73122 which is about readonly-ness on the level of a file

_Originally posted by @jrieken in https://github.com/microsoft/vscode/issues/109527#issuecomment-729533106_

**Comment by jrieken** [comment]
👏
