### ISSUE TITLE
"workbench.settings.openDefaultKeybindings": false doesn't work with useSplitJSON

### ISSUE THREAD

**Issue by ggilles** [microsoft/vscode#110860]
- VSCode Version: 1.51.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Use these workbench settings:
```
    "workbench.settings.openDefaultSettings": false,
    "workbench.settings.openDefaultKeybindings": false,
    "workbench.settings.useSplitJSON": true,
    "workbench.settings.editor": "json",
```

2.  Open settings. I expect to get a split json window, and the default user settings should not be opened.

3. The "default user settings" is still visible: 

<img width="690" alt="Capture d’écran 2020-11-18 à 12 46 55" src="https://user-images.githubusercontent.com/1478233/99526997-615c2d80-299c-11eb-9586-54482e9e6c87.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
By definition, the "split json" editor shows the default settings, and also that mode is deprecated
