### ISSUE TITLE
Change functionality of split window command to move active focus window to the new pane

### ISSUE THREAD

**Issue by brunzefb** [microsoft/vscode#110879]
I would like a changed behavior for the split command (icon looks like a flat open book, right before ... on the right.

**Current functionality:**
1. Editor is open and focused to FileA, with FileB also present, but not active tab
2. User clicks the split icon

We have a split window
[FileB][FileA] |(split)| FileA

**Desired functionality** (this could be controlled by an option if people really love the current behavior)
1. Editor is open and focused to FileA, with FileB also present, but not active tab
2. User clicks the split icon

We have a split window
[FileB] |(split)| FileA

Note that FileA is no longer open in the left pane -- it has moved instead of being copied.

Reasoning:
99.9% of the time, when I split I need to delete the duplicate
While it is possible to just drag the FileA using the mouse and 'move' the pane as desired above -- this feature (move pane by mouse)is less discoverable for end users than the split pane command.

**Comment by ArturoDent** [comment]
This can be accomplished by moving fileA to next/last group via a keybinding.  Not as convenient as the split icon, but splitting files has a long history so that the same file is side-by-side.

**Comment by brunzefb** [comment]
I agree that there is more than one way to do this.  However, I also assert
that the default behavior of the split button is non-intuitive/annoying for
beginners, that is why I created the issue, not for my benefit.
