### ISSUE TITLE
Have `--max-memory` also be applied to the extension host

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#110885]
Extracted from https://github.com/microsoft/vscode/issues/107950#issuecomment-729885866

**Comment by MJimitater** [comment]
Hi @alexdima, thanks for opening this issue!
I seem to have the same problem as in #107950. Is there any news so far in having `--max-memory` be applied to extension host?

**Comment by alexdima** [comment]
To verify, use `ps` to find the extension host process and look at the command line arguments.

**Comment by dbaeumer** [comment]
<img width="410" alt="capture" src="https://user-images.githubusercontent.com/1931590/112179170-bcc45380-8bfa-11eb-8e4b-e44ba9938171.png">
