### ISSUE TITLE
Please support setting keyboard shortcut for refreshing all repositories in a workspace.

### ISSUE THREAD

**Issue by kaiyu-pony** [microsoft/vscode#110829]
For some reason, I have to disable git auto-refresh and rely on manually triggered git refresh.

I found that it is supported to set a keyboard shortcut for refreshing a single repository (`git.refresh`), but not for refreshing all the repositories. Would be great if that could be supported as well.

System: Ubuntu 16.04
VSCode version: 1.50.1

**Comment by eamodio** [comment]
FYI, this feature exists in GitLens today.
