### ISSUE TITLE
Console ignores ipython output

### ISSUE THREAD

**Issue by jwiszowata** [microsoft/vscode#110810]
Issue Type: <b>Bug</b>

I use VSCode to connect to a remote machine using ssh. The issue appeared after the last upadate.

1. Open VSCode Console Ctr + `
2. Go to the terminal tab
3. run ipython 7.14.0
> ipython
4. type print("a")
In [1]: print("a")
5. press Enter
---------------------------------------
expected:
In [1]: print("a")
a
In [2]
---------------------------------------
seen:
In [2]:
---------------------------------------
Scroling up and down usually shows the output

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 3.10.0-1062.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.99GB free)|
|Process Argv|--crash-reporter-id ce9faf2e-ed1a-422d-87fb-c5a182c855d8|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: plwarvlpdaiap01|
|OS|Linux x64 3.10.0-1062.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz (16 x 2593)|
|Memory (System)|62.76GB (4.75GB free)|
|VM|7%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
vscode-postgres|cko|1.1.14
githistory|don|0.6.14
jupyter|don|1.1.6
git-graph|mhu|1.27.0
vscode-docker|ms-|1.8.0
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
gitblame|wad|6.0.0

</details>

**Comment by meganrogge** [comment]
Thanks for the issue. If you resize the terminal window after entering line 1, does it display the a? 

Also, does changing `terminal.integrated.rendererType` help?
