### ISSUE TITLE
Please display the current absolute character cursor position (in the entire document)

### ISSUE THREAD

**Issue by Emasoft** [Microsoft/vscode#11086]
Sometimes instead of getting errors relative to the lines (i.e. line 5, position 14),  you get errors relative to the absolute position of the character in the entire file. Errors messages like this:

```
ParsingException: Unexpected character encountered while parsing value at position 116
```

It would be useful to be able to know what the 116th character of the entire file is. Currently there is no way to know that in Visual Studio Code.

The only information displayed in the bottom bar is the Row and Column. So I can know the character at a certain position in a line, but I don't know what is the absolute character number (including hidden formatting characters like new line, eof, etc).

It would be awesome to be able to see instead of this:

> row 1, col 5

This:

> row 1, col 5, chr 116

It should also be useful to be able to programmatically move the cursor to a new position using the absolute position of the character instead of the line, column coordinates. So that instead of being able to do just this:

> var newPosition = position.with(position.line, 5);

You would be also able to do this:

> var newPosition = position.with(116);

In this way when a compiler log will give you an absolute character number position for an error in you file, your code extension can immediately position the cursor in that exact place, hilighting the right character that rised the exception.

**Comment by alexandrudima** [comment]
The model already supports (offset,len) <-> (line,col) conversions.

This feature request asks for:
* adoption in go to line @bpasero
* adoption in status bar @bpasero 
* adoption in API @jrieken

**Comment by bpasero** [comment]
@Emasoft I suggest to file separate issues for the 3 components of this one.

**Comment by bpasero** [comment]
@Emasoft please file separate issues for separate requests, there can be different owners and different priorities for each of them. 

See also https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests

**Comment by ramya-rao-a** [comment]
I've been wanting this feature as well. So created an extension for it.

https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset

- Shows the offset in the status bar
- Command `Showoffset: Go to offset` to navigate to offset just like "Go to line.."

@Emasoft As of your request for programmatically getting position given offset you can use `document.positionAt()` which takes in offset.

**Comment by kletkeman** [comment]
@ramya-rao-a -- I just ran into the issue with an enormous file and your extension saved me. There are not enough thanks.
