### ISSUE TITLE
Rollback insiders update

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11084]
Is it possible to rollback insiders version update?

**Comment by egamma** [comment]
@whitecolor insiders update only go forward. Our approach is to fix an issue on the same day. The development team is using the insider channel for all the development work. If the insiders build is broken then users can fallback on the stable version.

The icon extension depends an internals and is always at risk of being broken, we cannot keep all internal stable. To fix this we have added an API for contributing icons to the explorer. We are working with the author of the vscode-icons extension (@robertohuertasm) on the adoption of this API. Please see https://github.com/robertohuertasm/vscode-icons/issues/177.

**Comment by whitecolor** [comment]
Ok just wanted to make sure if it is possible.
