### ISSUE TITLE
the TypeScript language service died 5 times right after it got started. The service will not be restarted.

### ISSUE THREAD

**Issue by mixalezhnev** [microsoft/vscode#110802]
Issue Type: <b>Bug</b>

Open editor with any .ts file and get error message
After the message it's impossible to go to definitions neither implementations.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|. --crash-reporter-id b37a8ed8-f871-407f-9c20-6965c2d3c28e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.1
vscode-html-css|ecm|0.2.3
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
auto-rename-tag|for|0.1.5
go|gol|0.18.1
todo-tree|Gru|0.0.188
rest-client|hum|0.24.4
plantuml|jeb|2.13.16
spellcheck|Jul|1.1.4
vscode-docker|ms-|1.8.0
remote-containers|ms-|0.148.1
vscode-typescript-next|ms-|4.2.20201116
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.0
language-plantuml|qho|0.0.3
missinglineendoffile|ric|0.3.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.13
tech-debt-tracker|Ste|0.27.5
code-spell-checker|str|1.9.4
code-spell-checker-russian|str|0.2.9
vim|vsc|1.11.3
wallaby-vscode|Wal|1.0.250

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mixalezhnev** [comment]
@mjbvz, this doesn't reproduce in the latest VS Code insiders build. But why should this reproduce in regular VS Code?

**Comment by cdtapay** [comment]
I'm getting this a lot, 7 out of 10 restarts end with this error.

**Comment by mjbvz** [comment]
@mixalezhnev It could be one of your extensions. Have you tested with extensions disabled?
