### ISSUE TITLE
Cannot run Vscode from command line

### ISSUE THREAD

**Issue by MakiWolf** [microsoft/vscode#110801]
- VSCode Version: current master branch
- OS Version: Ubuntu 20.10

Steps to Reproduce:

1. yarn
2. yarn watchd
3. ./scripts/code.sh

![grafik](https://user-images.githubusercontent.com/73300633/99391237-33161980-28da-11eb-8289-a849a9de737e.png)
In the master Branch I got the message: "Failed to get crash dump id"

I also tried the Branch "electron-11.x.y"

![grafik](https://user-images.githubusercontent.com/73300633/99391401-6fe21080-28da-11eb-9408-9711b8ce583d.png)
There I got the message: "(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron"

**Comment by deepak1556** [comment]
Can you launch with `./scripts/code.sh --crash-reporter-directory /tmp/vscode-crash` and attach the generated dumps.

**Comment by MakiWolf** [comment]
on Fedora 33 it worked
But on Ubuntu 20.10 there is the Problem with Segmentation fault (core dumped)

**Comment by deepak1556** [comment]
Can you attach the .dmp files following the steps from previous comment. They will be generated once the segfault happens.

**Comment by MakiWolf** [comment]
Can't upload the file here, because the file type is not supported here
![grafik](https://user-images.githubusercontent.com/73300633/99726026-4251be80-2ab6-11eb-9e38-371c76d32eb2.png)

**Comment by deepak1556** [comment]
You can compress and upload the zip

**Comment by MakiWolf** [comment]
[crash.zip](https://github.com/microsoft/vscode/files/5569905/crash.zip)

**Comment by deepak1556** [comment]
Symbolicated trace

```
Symbolicating...
Operating system: Linux
                  0.0.0 Linux 5.8.0-29-generic #31-Ubuntu SMP Fri Nov 6 12:37:59 UTC 2020 x86_64
CPU: amd64
     family 23 model 24 stepping 1
     4 CPUs

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_ACCERR
Crash address: 0x5579a4e739c3
Process uptime: not available

Thread 0 (crashed)
 0  libnode.so.72 + 0x714c72
    rax = 0x00005579a4e73990   rdx = 0x0000000000000000
    rcx = 0x0000000000000202   rbx = 0x00007f2aebf41400
    rsi = 0x0000000000000000   rdi = 0xe40ecc528cbb412c
    rbp = 0x00007fff425b07f0   rsp = 0x00007fff425b07f0
     r8 = 0x0000000000000000    r9 = 0x000011df7cd41c80
    r10 = 0x0000000000061d8c   r11 = 0x00007fff425d8080
    r12 = 0x00007fff425b4b18   r13 = 0x000011df7c482b40
    r14 = 0x00007f2aebf41f90   r15 = 0x0000000000000000
    rip = 0x00007f2aea3eac72
    Found by: given as instruction pointer in context
 1  ld-linux-x86-64.so.2 + 0x11dbe
    rsp = 0x00007fff425b0800   rip = 0x00007f2aff287dbe
    Found by: stack scanning
 2  ld-linux-x86-64.so.2 + 0x11ea8
    rsp = 0x00007fff425b0830   rip = 0x00007f2aff287ea8
    Found by: stack scanning
 3  libc.so.6 + 0x15a505
    rsp = 0x00007fff425b0870   rip = 0x00007f2afd69d505
    Found by: stack scanning
 4  ld-linux-x86-64.so.2 + 0x15840
    rsp = 0x00007fff425b0888   rip = 0x00007f2aff28b840
    Found by: stack scanning
 5  spdlog.node + 0x4948
    rsp = 0x00007fff425b08c0   rip = 0x00007f2aebfff948
    Found by: stack scanning
 6  0x7f2aebffb000
    rsp = 0x00007fff425b08e8   rip = 0x00007f2aebffb000
    Found by: stack scanning
 7  spdlog.node + 0xd2dc
    rsp = 0x00007fff425b08f0   rip = 0x00007f2aec0082dc
    Found by: stack scanning
 8  spdlog.node + 0x10a8
    rsp = 0x00007fff425b08f8   rip = 0x00007f2aebffc0a8
    Found by: stack scanning
 9  spdlog.node + 0x10ff8
    rsp = 0x00007fff425b0900   rip = 0x00007f2aec00bff8
    Found by: stack scanning
10  spdlog.node + 0xd938
    rsp = 0x00007fff425b0918   rip = 0x00007f2aec008938
    Found by: stack scanning
11  spdlog.node + 0xfac8
    rsp = 0x00007fff425b0938   rip = 0x00007f2aec00aac8
    Found by: stack scanning
12  ld-linux-x86-64.so.2 + 0x16505
    rsp = 0x00007fff425b0990   rip = 0x00007f2aff28c505
    Found by: stack scanning
13  code-oss!bool std::__1::__function::__policy_invoker<bool (node::binding::DLib*)>::__call_impl<std::__1::__function::__default_alloc_func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, bool (node::binding::DLib*)> >(std::__1::__function::__policy_storage const*, node::binding::DLib*) [node_binding.cc : 324 + 0x5]
    rsp = 0x00007fff425b09f8   rip = 0x00005579ab4b5639
    Found by: stack scanning
14  libc.so.6 + 0x15a4a8
    rsp = 0x00007fff425b0a10   rip = 0x00007f2afd69d4a8
    Found by: stack scanning
15  ld-linux-x86-64.so.2 + 0x16150
    rsp = 0x00007fff425b0a28   rip = 0x00007f2aff28c150
    Found by: stack scanning
16  code-oss!bool std::__1::__function::__policy_invoker<bool (node::binding::DLib*)>::__call_impl<std::__1::__function::__default_alloc_func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, bool (node::binding::DLib*)> >(std::__1::__function::__policy_storage const*, node::binding::DLib*) [node_binding.cc : 324 + 0x5]
    rsp = 0x00007fff425b0a70   rip = 0x00005579ab4b5639
    Found by: stack scanning
17  code-oss!v8::internal::IsIdentifierStartSlow(unsigned int) [char-predicates.cc : 22 + 0xa]
    rsp = 0x00007fff425b0aa0   rip = 0x00005579a689dab2
    Found by: stack scanning
18  code-oss!v8::internal::DeclarationScope::DeclareArguments(v8::internal::AstValueFactory*) [scopes.h : 615 + 0x1c]
    rsp = 0x00007fff425b0ae0   rip = 0x00005579a63e6c59
    Found by: stack scanning
19  ld-linux-x86-64.so.2 + 0x15b5d
    rsp = 0x00007fff425b0b30   rip = 0x00007f2aff28bb5d
    Found by: stack scanning
20  code-oss!bool std::__1::__function::__policy_invoker<bool (node::binding::DLib*)>::__call_impl<std::__1::__function::__default_alloc_func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, bool (node::binding::DLib*)> >(std::__1::__function::__policy_storage const*, node::binding::DLib*) [node_binding.cc : 324 + 0x5]
    rsp = 0x00007fff425b0b78   rip = 0x00005579ab4b5639
    Found by: stack scanning
21  code-oss!<name omitted> [allocation.h : 38 + 0xf]
    rsp = 0x00007fff425b0bb0   rip = 0x00005579a6759da7
    Found by: stack scanning
22  libdl.so.2 + 0x134c
    rsp = 0x00007fff425b0bf0   rip = 0x00007f2afed7a34c
    Found by: stack scanning
23  libc.so.6 + 0x15a4a8
    rsp = 0x00007fff425b0c10   rip = 0x00007f2afd69d4a8
    Found by: stack scanning
24  libdl.so.2 + 0x12f0
    rsp = 0x00007fff425b0c28   rip = 0x00007f2afed7a2f0
    Found by: stack scanning
25  code-oss!v8::internal::Parser::ParseFunction(v8::internal::ScopedList<v8::internal::Statement*, void*>*, v8::internal::AstRawString const*, int, v8::internal::FunctionKind, v8::internal::FunctionSyntaxKind, v8::internal::DeclarationScope*, int*, int*, bool*, int*, int*, v8::internal::ZoneList<v8::internal::AstRawString const*>*) [parser.cc : 2830 + 0x38]
    rsp = 0x00007fff425b0c40   rip = 0x00005579a676ee05
    Found by: stack scanning
26  code-oss!v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer(v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*) [bytecode-register-optimizer.cc : 324 + 0x9]
    rsp = 0x00007fff425b0cc0   rip = 0x00005579a660e0db
    Found by: stack scanning
27  code-oss!v8::internal::interpreter::BytecodeArrayBuilder::LoadAccumulatorWithRegister(v8::internal::interpreter::Register) [bytecode-register-optimizer.h : 49 + 0x5]
    rsp = 0x00007fff425b0d10   rip = 0x00005579a65e5630
    Found by: stack scanning
28  libc.so.6 + 0x15a573
    rsp = 0x00007fff425b0d30   rip = 0x00007f2afd69d573
    Found by: stack scanning
29  libdl.so.2 + 0x12f0
    rsp = 0x00007fff425b0d68   rip = 0x00007f2afed7a2f0
    Found by: stack scanning
30  libdl.so.2 + 0x1b89
    rsp = 0x00007fff425b0d70   rip = 0x00007f2afed7ab89
    Found by: stack scanning
31  libdl.so.2 + 0x13d8
    rsp = 0x00007fff425b0d90   rip = 0x00007f2afed7a3d8
    Found by: stack scanning
32  code-oss!bool std::__1::__function::__policy_invoker<bool (node::binding::DLib*)>::__call_impl<std::__1::__function::__default_alloc_func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, bool (node::binding::DLib*)> >(std::__1::__function::__policy_storage const*, node::binding::DLib*) [node_binding.cc : 324 + 0x5]
    rsp = 0x00007fff425b0db0   rip = 0x00005579ab4b5639
    Found by: stack scanning
33  code-oss!bool std::__1::__function::__policy_invoker<bool (node::binding::DLib*)>::__call_impl<std::__1::__function::__default_alloc_func<node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)::$_0, bool (node::binding::DLib*)> >(std::__1::__function::__policy_storage const*, node::binding::DLib*) [node_binding.cc : 324 + 0x5]
    rsp = 0x00007fff425b0dd0   rip = 0x00005579ab4b5639
    Found by: stack scanning
34  code-oss!v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer(v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*) [bytecode-register-optimizer.cc : 324 + 0x9]
    rsp = 0x00007fff425b0e00   rip = 0x00005579a660e156
    Found by: stack scanning
35  code-oss!v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister(v8::internal::interpreter::Register) [bytecode-register-optimizer.h : 53 + 0x5]
    rsp = 0x00007fff425b0e50   rip = 0x00005579a65e578d
    Found by: stack scanning
36  code-oss!v8::internal::interpreter::RegisterTransferWriter::EmitStar(v8::internal::interpreter::Register) [bytecode-array-builder.cc : 173 + 0x5]
    rsp = 0x00007fff425b0ec0   rip = 0x00005579a65f0733
    Found by: stack scanning
37  code-oss!v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterTransfer(v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*, v8::internal::interpreter::BytecodeRegisterOptimizer::RegisterInfo*) [bytecode-register-optimizer.cc : 324 + 0x9]
    rsp = 0x00007fff425b0f00   rip = 0x00005579a660e0db
    Found by: stack scanning
38  code-oss!v8::internal::interpreter::RegisterTransferWriter::EmitStar(v8::internal::interpreter::Register) [bytecode-array-builder.cc : 173 + 0x5]
    rsp = 0x00007fff425b0f90   rip = 0x00005579a65f0733
    Found by: stack scanning
39  code-oss!v8::internal::String::SlowEquals(v8::internal::String) [utils.h : 302 + 0x12]
    rsp = 0x00007fff425b0fb0   rip = 0x00005579a67464e3
    Found by: stack scanning
40  code-oss!v8::internal::Object::GetProperty(v8::internal::LookupIterator*, bool) [objects.cc : 1124 + 0xa]
    rsp = 0x00007fff425b1050   rip = 0x00005579a670e19f
    Found by: stack scanning
41  code-oss!v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, bool*) [runtime-object.cc : 44 + 0xa]
    rsp = 0x00007fff425b10a0   rip = 0x00005579a68311c5
    Found by: stack scanning
42  code-oss!v8::internal::interpreter::BytecodeArrayBuilder::CallProperty(v8::internal::interpreter::Register, v8::internal::interpreter::RegisterList, int) [bytecode-array-builder.cc : 0 + 0x1f]
    rsp = 0x00007fff425b10b0   rip = 0x00005579a65edc4a
    Found by: stack scanning
43  code-oss!v8::internal::StackGuard::PopInterruptsScope() [isolate.h : 2000 + 0x8]
    rsp = 0x00007fff425b1130   rip = 0x00005579a64c70fe
    Found by: stack scanning
44  code-oss!v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const [string_fortified.h : 34 + 0xb]
    rsp = 0x00007fff425b1160   rip = 0x00005579a63a243b
    Found by: stack scanning
45  code-oss!tc_malloc [thread_cache.h : 219 + 0x5]
    rsp = 0x00007fff425b11e0   rip = 0x00005579ab6c5cc5
    Found by: stack scanning
46  code-oss!node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [functional : 2203 + 0x3]
    rsp = 0x00007fff425b1230   rip = 0x00005579ab4b4902
    Found by: stack scanning
47  code-oss + 0x77875e0
    rsp = 0x00007fff425b1288   rip = 0x00005579ab4b55e0
    Found by: stack scanning
```

**Comment by deepak1556** [comment]
Weird that there is `libnode.so` involved in the trace, node should be statically linked with code-oss.

Can you provide the output of `ldd .build/electron/code-oss`

**Comment by MakiWolf** [comment]
linux-vdso.so.1 (0x00007ffd90f86000)
	libffmpeg.so => /home/markus/vscode1/vscode/.build/electron/libffmpeg.so (0x00007fca74adf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fca74ac7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fca74aa5000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fca74a9a000)
	libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fca74a3f000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fca7490d000)
	libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fca74724000)
	libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007fca745d0000)
	libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007fca7459e000)
	libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x00007fca7456e000)
	libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007fca7452e000)
	libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007fca74504000)
	libatk-bridge-2.0.so.0 => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0 (0x00007fca744ca000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fca7438c000)
	libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fca74387000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fca7435d000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fca7430b000)
	libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007fca742e3000)
	libgtk-3.so.0 => /lib/x86_64-linux-gnu/libgtk-3.so.0 (0x00007fca73b15000)
	libgdk-3.so.0 => /lib/x86_64-linux-gnu/libgdk-3.so.0 (0x00007fca73a0b000)
	libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fca739f9000)
	libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fca739a6000)
	libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fca73883000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fca73734000)
	libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007fca7372d000)
	libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fca73728000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fca73713000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fca7370b000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fca736fe000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fca736d0000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fca736ba000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fca73678000)
	libgbm.so.1 => /lib/x86_64-linux-gnu/libgbm.so.1 (0x00007fca73666000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007fca7356b000)
	libcups.so.2 => /lib/x86_64-linux-gnu/libcups.so.2 (0x00007fca734d0000)
	libatspi.so.0 => /lib/x86_64-linux-gnu/libatspi.so.0 (0x00007fca73498000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fca7347b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fca73291000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fca7cf72000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007fca73285000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fca73212000)
	libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fca7320c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fca731ef000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fca7318f000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fca73164000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fca73149000)
	libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007fca73142000)
	libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007fca7313d000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fca73135000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fca7312d000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fca73079000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fca73067000)
	libcairo-gobject.so.2 => /lib/x86_64-linux-gnu/libcairo-gobject.so.2 (0x00007fca7305b000)
	libepoxy.so.0 => /lib/x86_64-linux-gnu/libepoxy.so.0 (0x00007fca72f28000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007fca72f09000)
	libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fca72eef000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fca72e0e000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fca72dc7000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fca72d04000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fca72cfd000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fca72cf0000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fca72ce5000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fca72ce0000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fca72ccf000)
	libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007fca72cc4000)
	libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fca72c1b000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fca72be2000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fca72bdd000)
	libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fca72bce000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fca729c4000)
	libwayland-server.so.0 => /lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007fca729ac000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fca7295e000)
	libavahi-common.so.3 => /lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007fca72950000)
	libavahi-client.so.3 => /lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007fca7293c000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fca72776000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fca72721000)
	libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fca72691000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fca72677000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fca7264e000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007fca7257e000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fca7255b000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fca7243d000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fca72410000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fca72407000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fca723f9000)
	libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fca723ef000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fca72310000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fca722df000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fca722d8000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fca722c9000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fca72190000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fca7216c000)
	libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fca71fea000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fca71fd4000)
	libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007fca71f95000)
	libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007fca71f4d000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fca71eca000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fca71ea1000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fca71e7e000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fca71e77000)
