### ISSUE TITLE
Extensions Marketplace not working

### ISSUE THREAD

**Issue by hugodanielpereira** [microsoft/vscode#110877]
Issue Type: <b>Bug</b>

It seems that the Extensions Marketplace is offline or isn't working for some reason. I can't connect to it through VS Code nor through it's website.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx   (8 x 2196)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|22.95GB (11.01GB free)|
|Process Argv|--crash-reporter-id c2e5d829-de85-40f8-bd69-98fdb02f0363|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.8
deepcode|dee|2.2.1
es7-react-js-snippets|dsz|2.8.3
gitlens|eam|10.2.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.1.3
vscode-docker|ms-|1.5.0
mssql|ms-|1.9.0
remote-containers|ms-|0.134.1
remote-ssh|ms-|0.51.0
remote-ssh-edit|ms-|0.51.0
remote-wsl|ms-|0.44.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|0.29.0
vscode-typescript-tslint-plugin|ms-|1.2.3
team|ms-|1.161.0
material-icon-theme|PKi|4.2.0
vscode-yaml|red|0.9.1
LiveServer|rit|5.6.1
highlight-matching-tag|vin|0.9.9

</details>

**Comment by roblourens** [comment]
It's fine for me. Try again a little later and let us know if it's still down.

**Comment by hugodanielpereira** [comment]
The message that I get is this:

![imagem](https://user-images.githubusercontent.com/37424599/99599036-72378e00-29f2-11eb-87c9-09eac8078c43.png)

I don't know how to debug it better, but I really wanted it to work.

Thanks

**Comment by hugodanielpereira** [comment]
I found a workaround, clicking on the menu for the Marketplace Extensions and then choosing the "**_Check for Extension Updates_**" option, established the connection again and after reloading the updates, everything went back to normal. This never happened to me before, but now it seems everything is fine.
