### ISSUE TITLE
crashing vs code

### ISSUE THREAD

**Issue by anas-koraspond** [microsoft/vscode#110862]
Issue Type: <b>Bug</b>

Steps to reproduce:
1.Open two terminals two terminals
2.Run a command in first terminal 
3.try to run another command in second terminals 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.15GB free)|
|Process Argv|--crash-reporter-id 1af713a0-a81d-44f6-9caf-b042dcb6cd14|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ACF-Snippet|ant|1.9.0
es7-react-js-snippets|dsz|3.0.0
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.0.0
prettier-vscode|esb|5.7.2
beautify|Hoo|1.5.0
ftp-simple|hum|0.7.5
vscodefy|iag|0.0.11
cmderrunner|jus|0.1.2
vscode-docker|ms-|1.8.0
mssql|ms-|1.9.0
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
sublime-keybindings|ms-|4.0.7
vsliveshare|ms-|1.0.3206
vscode-react-native|msj|1.1.1
markdown-preview-enhanced|shd|0.5.13
mdx|sil|0.1.0
wordpress-toolbox|wor|1.3.8
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.6

(4 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/confirmationPending

Does the problem also occur after you run the Cpmmand Palette command to reload with all extensions disabled?

If yes, what is the simplest command you can run in the terminals to reproduce it?

**Comment by roblourens** [comment]
What commands are you running? What does the crash look like?

**Comment by anas-koraspond** [comment]
![image](https://user-images.githubusercontent.com/68539953/99628838-0849d380-2a48-11eb-98bb-c09ab413e2fa.png)
i just run in first the webpack dev enivronment command- it works fine
and in the other terminal i ran just the ls command
<b>NB: sometimes it crashes, sometime it not, after the latest updates am facing the issues</b>

**Comment by meganrogge** [comment]
@anas-koraspond sorry you're having issues and thanks for the info.

can you please try disabling all extensions and reloading the window as suggested above? 

also, a [gif](https://gifcap.dev/) is always handy.

**Comment by anas-koraspond** [comment]
❣Thanks..!! now its working fine i have updated all the plugins.
