### ISSUE TITLE
Proxy Authentication appears twice

### ISSUE THREAD

**Issue by skyvogt** [microsoft/vscode#110841]
- VSCode Version: 1.52.0-insider
- OS Version: Windows 10 Enterprise

**Steps to Reproduce:**

1. Close all instances of VSC
2. Open VSC in a Network with Proxy

Does this issue occur when all extensions are disabled?: Yes

**Observed**
Proxy Authentication appears twice

![image](https://user-images.githubusercontent.com/74182077/99493382-6787e500-296f-11eb-9ac3-b5ac7499e3c6.png)

**Expected**
1. Single appearance of the authentication dialogue.

**Optimization**
2. Store Proxy Account Data in the authentication -> ok to confirm.
3. Store Proxy-Authentication for all future instances -> Proxy Authentication appears only when pass changed.

**Comment by gjsjohnmurray** [comment]
Maybe try this setting

https://code.visualstudio.com/updates/v1_51#_remember-proxy-credentials

**Comment by skyvogt** [comment]
Not reproducable with latest insider build => solved, thank you and greetings.
