### ISSUE TITLE
False positive of hangs and ESC key reboot vscode unexpectedly.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#11080]
- VSCode Version:
    - 1.5.0-insider
    - 31f1acb8c82b8a19256d5d56127d3f81edce3745
    - 2016-08-26T08:00:03.472Z
    - Shell: 0.37.6
    - Renderer: 49.0.2623.75
    - Node: 5.10.0
- OS Version:
    - Windows 7 Pro

Steps to Reproduce:

1. Show context menu in file explorer of vscode.
2. Keep showing 30s. Then VSCode shows hang up dialog unexpectedly.
   ![false-positive](https://cloud.githubusercontent.com/assets/1937871/18042217/8ad7d8ec-6dfa-11e6-86d6-f9709ad04bb8.gif)
3. Press **ESC key**. I expected that I can continue my work, but VSCode does rebooting. I had lost my works... I think ESC key should do nothing.

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by mysticatea** [comment]
@bpasero I'm sorry, I could not find the issue. I used keywords: `context menu false positive`, `false positive`, `context menu`, `context menu esc`, `context menu hang`.

Chould you tell me the issue, please?
I'd like to track the issue.

**Comment by bpasero** [comment]
@mysticatea [Leaving a right-click menu open for about 30 seconds causes a This Window Is No Longer Responding error](https://github.com/Microsoft/vscode/issues/6414)

**Comment by mysticatea** [comment]
Thank you very much!
