### ISSUE TITLE
Having a huge performance hit when working with React or Frameworks in general

### ISSUE THREAD

**Issue by Ntshembo-Hlongwane1** [microsoft/vscode#110890]
Issue Type: <b>Performance Issue</b>

So this has been an ongoing problem that I have been having whenever I work with Frameworks I have my VSCode freezing out of nowhere, but I get a different response when I just writing plain old JavaScript or some plain Java nothing hectic no Spring.

So I have been googling and searching on what could be causing the performance hit when working with Frameworks, at first I thought maybe it had to do with server being up but over past weeks tried working with servers down and I still get the same performance hit.

Hoping to hear from you guys soon

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU 4205U @ 1.80GHz (2 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|3.73GB (0.11GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id eb6dc386-ec41-492a-b65d-3e7cc2f6f221|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   122	  4947	code main
    0	    38	  5477	   zygote
    0	    95	  5781	     gpu-process
    0	    38	  5478	   zygote
    0	    57	  5799	   utility
    0	   221	  5980	   window (● Header.jsx - Shipment-Tracking-App - Visual Studio Code)
    0	   137	  6114	     extensionHost
    0	   122	  6966	       electron_node tsserver.js 
    0	   149	  6967	       electron_node tsserver.js 
    0	    95	  6985	         electron_node typingsInstaller.js typesMap.js 
    0	    57	  6132	     watcherService
    0	    57	  6319	     searchService
    0	   114	  6074	   shared-process
    0	     0	  7484	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  7485	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   103	  7466	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● Header.jsx - Shipment-Tracking-App - Visual Studio Code)
|    Folder (Shipment-Tracking-App): 28 files
|      File types: jsx(4) json(3) png(2) js(2) jpg(2) gitignore(1) md(1)
|                  ico(1) html(1) txt(1)
|      Conf files: package.json(2);
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|11.3.1
vscode-django|bat|1.0.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
git-extension-pack|don|0.1.3
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.1
prettier-vscode|esb|5.7.2
todo-tree|Gru|0.0.188
MagicPython|mag|1.1.0
dotenv|mik|1.0.1
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
cpptools|ms-|1.1.2
nodejs-snippets|piy|0.0.2
material-icon-theme|PKi|4.4.0
java|red|0.70.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Ntshembo-Hlongwane1** [comment]
I am using the current VSCode everything is up to date, so could it be the extension being a lot that I have to cut them?

**Comment by mjbvz** [comment]
Did you test with extensions disabled?

**Comment by mjbvz** [comment]
Also, insiders is a different build that you have to install. Test using it: https://code.visualstudio.com/insiders/

**Comment by Ntshembo-Hlongwane1** [comment]
Okay let me give it check and I will update on Monday so I can assess the performance and all, thanks for now

**Comment by Ntshembo-Hlongwane1** [comment]
Hey there, so from the past few days I have been having  great performance from my VSCode and went through cutting down on extension's that I have plus looked into the insider's build and I am loving it thanks a lot...
