### ISSUE TITLE
Exploration: Report Issue doesn't work

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110805]
Version: 1.52.0-exploration (user setup)
Commit: aaaead3835f722f023abc3de44d729f7d5fb1797
Date: 2020-11-17T07:04:49.800Z
Electron: 11.0.0-beta.20
Chrome: 87.0.4280.40
Node.js: 12.18.3
V8: 8.7.220.10-electron.0
OS: Windows_NT x64 10.0.19042

---

Clicking Help > Report Issue does nothing.

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/99398785-1d5a2180-28e5-11eb-83ee-e1434e5d9a2e.gif)

Anything you do different? Anything in devtools?

**Comment by joaomoreno** [comment]
I use the same actions. Nothing comes up. Nothing in dev tools. This appears in the `--verbose` window when I click it:

```
[11956:1117/150345.008:INFO:CONSOLE(1764)] "%cTRACE color: #888 CommandService#executeCommand workbench.action.openIssueReporter", source: file:///C:/Users/jomo/AppData/Local/Programs/Microsoft VS Code Exploration/resources/app/out/vs/workbench/workbench.desktop.main.js (1764)
```

**Comment by bpasero** [comment]
How about process explorer?

**Comment by joaomoreno** [comment]
OK seems to work now. The problem was that https://github.com/microsoft/vscode/issues/110806 caused runaway processes after crashing, which prevented this from working somehow.
