### ISSUE TITLE
Intelisense not working at all

### ISSUE THREAD

**Issue by Nani-Sore-0** [microsoft/vscode#110871]
Issue Type: <b>Bug</b>

It was working one moment, the next it wasn't. I tried all the usual (restarting VS/PC, no extensions). I can't find anyone having a similar issue. It doesn't work in JS, CSS and HTML. After using it a bit it seems that somethings work. For example console and some HTML tag will complete. But things like a for loop will not. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.56GB free)|
|Process Argv|--crash-reporter-id ba346591-d5d0-43a1-a701-9825d4b5ca8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.7.2
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
azure-account|ms-|0.9.4
cpptools|ms-|1.1.2
color-highlight|nau|2.3.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-autohotkey|sle|0.2.2
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Nani-Sore-0** [comment]
> 
> 
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

No. It works fine. I wish I can provide more info but, but I don't know what to say. It was just working and then I wasn't. I guess I'll reinstall VS.
