### ISSUE TITLE
<tab></tab> inserted on Tab in .js file

### ISSUE THREAD

**Issue by lborgman** [microsoft/vscode#110804]
Issue Type: <b>Bug</b>

This is an intermittent issue. I have seen it many times, but it happens less often now. As far as I understand this is a race condition.

I just hit the Tab-key and then "&lt;tab>&lt;/tab>" is inserted. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU N4200 @ 1.10GHz (4 x 1094)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (0.42GB free)|
|Process Argv|--crash-reporter-id 2db228e7-570f-43a0-b1bf-75f2af041a44|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.3
cursor-charcode|but|0.9.2
firecode|ChF|1.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.0.1
vscode-sort|hen|0.2.5
beautify|Hoo|1.5.0
svg|joc|1.4.1
powershell|ms-|2020.6.0
material-icon-theme|PKi|4.4.0
partial-diff|ryu|1.4.1
vim|vsc|1.17.1
json|Zai|2.0.2

</details>

**Comment by lborgman** [comment]
![vscode-tab-display-bug 2020-11-17 142427](https://user-images.githubusercontent.com/23482/99396022-8770c780-28e1-11eb-8643-473c29703f5d.png)

**Comment by mjbvz** [comment]
Those come from emmet suggestions. See [the documentation](https://code.visualstudio.com/docs/editor/emmet) on disabling them
