### ISSUE TITLE
Git - disable autocommit after (unconflicted) merge

### ISSUE THREAD

**Issue by Frimlik** [microsoft/vscode#110850]
Hello,

is it possible in Git with VSCode to disable autocommit after merge/revert and be able to see/modify the merged files and changes before commit like it is possible e.g. in Visual Studio?
My UseCases:
- Merge from master - I'd like to see all changes other users have done and commit them myself (with the same comment) after review.
- Revert after commit wrong files - I accidentally added to my commit some files that shouldn't be there and after revert wanted to unstage them, but haven't found an option to do this.

Thanks for response.

*EDIT*
I found there is an option of "Undo last commit" that cancels the commit and shows all the files, but is there any more straightforward way?

**Comment by eamodio** [comment]
For the revert case, I think _Undo Last Commit_ is the best way. What would be more straightforward? 

As for merge -- we could probably think about adding a merge without commiting command, if enough people feel it is warranted

Although I will likely add this merge option to GitLens: https://github.com/eamodio/vscode-gitlens/issues/1178
