### ISSUE TITLE
Support embedded modes for TextMate grammars

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#11081]
With TextMate grammars we no longer support embedded modes which control the behaviour of smart editing (brackets, comments).

Text mate scopes can be used for that, but we should fix the flattening of scopes first (#3008)

**Comment by alexandrudima** [comment]
IMHO each and every one of the linked issues needs to be verified independently, as the generation of mode transitions from TM tokens depends heavily on the TM grammar (i.e. if the grammar does not use top-level scope names in the embedded portions, it will not help one bit). It works however for HTML, which uses `source.css.embedded.html` for embedded css, etc.

The relevant plan item is #14136

![comment-line](https://cloud.githubusercontent.com/assets/5047891/19654548/096b42b2-9a19-11e6-895c-4b4dbe879119.gif)

**Comment by chjtx** [comment]
I hate TextMate, and how can I remove it?

**Comment by wxs77577** [comment]
still not work, how to fix?
