### ISSUE TITLE
Source Control Tab Top bar is counter intutive

### ISSUE THREAD

**Issue by prashanthc97** [microsoft/vscode#110813]
Issue Type: <b>Feature Request</b>

Before when we click on Source Control Tab in left menu bar
A source countrol window used to open and had only one heading called Source Control

Now there is duplication of headings one after the other
Both serve different purposes, but for git push and git pull, we are used to pressing the three dots in the top right of that window

Now the option bar does not have any dialog which shows to push to repo

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by prashanthc97** [comment]
![image](https://user-images.githubusercontent.com/25387999/99414929-51e9cf80-291d-11eb-9e60-d913018623a6.png)
Two bars one below other with same name makes work difficult

If only the Source Control bar with the actual Git Features is present, it would makes the whole UX easier.

**Comment by dherran** [comment]
100%. This duplicated bar is annoying. Can this change be rolled back?

**Comment by zoultrex** [comment]
Also an issue for me, specially annoying that now all the buttons in all the sub panel categories tab bar are hidden when you focus other panels specially the text editor, this makes me click on the main source control tab bar, on their three dots (which are the only ones that are always visible now) looking for the push command all the time and it's not there. I really wish there was a setting to make those buttons in each sub panel to be visible all the time, not just on focus or hover.

I felt like it was more intuitive and a better user experience before when each title/tab bar had their own buttons showing all the time

**Comment by dherran** [comment]
This is unrelated to VSCode I think. It turns out that GitLens moved things around and now all of their settings appear under the Source Control tab.

If you go to the command palette and type "GitLens: Set Views Layout", then select "GitLens Layout", everything will go back to the way it was.

**Comment by prashanthc97** [comment]
> This is unrelated to VSCode I think. It turns out that GitLens moved things around and now all of their settings appear under the Source Control tab.
> 
> If you go to the command palette and type "GitLens: Set Views Layout", then select "GitLens Layout", everything will go back to the way it was.

Cheers!
Got the old layout back.
