### ISSUE TITLE
Blank window when run inside a lxd container

### ISSUE THREAD

**Issue by greenpdx** [microsoft/vscode#110845]
- VSCode Version: code_1.51.1-1605051630_amd64.deb
- OS Version: ubuntu

Steps to Reproduce:

1. on a ubuntu 20.04, install lxd
2. create a lxc container. 
3. ssh into the container with -X
4: $ sudo dpkg -i code_1.51.1-1605051630_amd64.deb
5. $ sudo apt-get install -f     # to fix the dependencies 
6 $ code

Does this issue occur when all extensions are disabled?: Yes

A window displays but it is empty. If is click where I think the "file" menu is faint outline of the menu is seen. I click the bottom where exit should be and it exits.  The widgets are not being displayed

I expect to see the editor

**Comment by thunder-coding** [comment]
Try running

`$ code --disable-gpu`

instead of

`$ code`

**Comment by greenpdx** [comment]
That does not work, still a blank white window.

**Comment by sweettyler** [comment]
try "code --no-xshm"

**Comment by greenpdx** [comment]
That fixed the problem.
