### ISSUE TITLE
Accounts does not load

### ISSUE THREAD

**Issue by namsnath** [microsoft/vscode#110809]
Issue Type: <b>Bug</b>

Clicking the Accounts on the sidebar results in a menu that just shows `loading`

VS Code version: Code - OSS 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-12T10:54:25.653Z)
OS version: Linux x64 5.9.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|7.66GB (1.70GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|bspwm|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.8
gitlens|eam|10.2.1
EditorConfig|Edi|0.15.1
material-theme|zhu|3.9.6

</details>

![Code_Accounts](https://user-images.githubusercontent.com/14910957/99403070-109ef300-2910-11eb-8ad0-e90c789b56af.png)

**Comment by RMacfarlane** [comment]
@namsnath Is this right after VS Code has started? Can you check what output is available in the "GitHub Authentication" and "Microsoft Authentication" channels in the output panel?

**Comment by namsnath** [comment]
Yes, it shows the same loading menu after I start VSCode, and doesn't resolve into a full menu even after ~2 hours. Restarting it or my machine didn't help. 

I'll check out the authentication tabs when I get back to my system and update you

**Comment by tw4452852** [comment]
I encountered the same issue on void linux.

**Comment by namsnath** [comment]
@RMacfarlane I can't seem to find the Authentication channels in the output. These are all I see:
![image](https://user-images.githubusercontent.com/14910957/99497137-7d130400-299b-11eb-8a90-a02f553dde07.png)

**Comment by RMacfarlane** [comment]
OK, so those extensions seem to not be activating. Can you run the `Developer: Toggle Developer Tools` and see if there are any errors in the console?

**Comment by namsnath** [comment]
There's this one:
![image](https://user-images.githubusercontent.com/14910957/99634058-e65f4980-2a65-11eb-98f3-afef67b24f9b.png)

**Comment by thefoxie** [comment]
They don't support OSS builds which we use.

https://github.com/microsoft/vscode/issues/110668

**Comment by RMacfarlane** [comment]
Thanks, closing this as out-of-scope.
