### ISSUE TITLE
Inline diff view adding blank lines

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#110897]
- VSCode Version: 1.52.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Make an edit to a file under source control
2. Bring up the diff view
3. Switch to inline diff mode

There are extra empty lines after each file line. The pattern seems to be that a line is added for each character in the preceeding line. For example: `---` results in three empty lines.

![image](https://user-images.githubusercontent.com/12818376/99597917-96bd4700-29ad-11eb-9741-d3b8d7eb0d71.png)

This reproduces for any file type (tested Markdown and JavaScript).
Side by Side view seems to be fine.

This started with Insiders build f11635ef1199ba5c43d9b83bb8b33036ea26d5b1

**Comment by gregvanl** [comment]
Assigning to @alexdima as this is likely due to recent diff view word wrap changes.

**Comment by alexdima** [comment]
Sorry about this!
