### ISSUE TITLE
Can't change subpixel order to BGR

### ISSUE THREAD

**Issue by Mikhail22** [microsoft/vscode#110864]
- VSCode Version: 1.50.1
- OS Version: Windows_NT x64 10.0.18363

Issue: 

Subpixel font rendering does not follow the system setting for the subpixel orientation (RGB vs BGR).
When rotating the display 180 degrees, the subpixel order needs to be BGR (can use registry setting or an external tool to set this setting). VS Code however stays in RGB mode regardless, and this causes blurred text.
There is no option to set this manually in VS Code either and no option to disable subpixel in VS Code.

Steps to Reproduce:

1. Set subpixel order to BGR in Windows (via registry or with a tool like "Better ClearType Tuner" directly).
2. See that in VS Code text rendering does not change.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
@Mikhail22 does this issue occur for you on the latest Insiders (v1.53.0)?

I used Better ClearType Tuner, changed from RGB -> BGR, then restarted my computer.
VS Code seems to be BGR for me:
![bgr-zoom](https://user-images.githubusercontent.com/7199958/104074977-67190700-51c6-11eb-87c6-aa2dcf05ade0.PNG)

**Comment by Mikhail22** [comment]
@rzhao271 I have checked and there is something strange - on the machine I use with a rotated display, it works, and VS Code respects the order in the Cleartype setting (need to restart VS Code). On another machine (display not rotated) it does not work so - in VS Code is always RGB order, regardless of the Cleartype setting. I can't  figure out how is that. Both machines are Windows 10, and I set the order via Better ClearType Tuner. Might be that VS  Code tries to read the orientation info from several places? This need more testing.

**Comment by doodhout** [comment]
I have the reverse problem: I use two external displays and a laptop screen, all of them set to RGB cleartype rendering, but despite this Visual Studio Code decided on using BGR cleartype rendering, making the text seem _very_ jaggy and fuzzy.

Is there a setting to override cleartype rendering in Visual Studio Code?

**Comment by deepak1556** [comment]
Font rendering is controlled by the runtime, closing as not actionable.

**Comment by gthrow** [comment]
Subpixel order is correct in all my other applications, only Code has this problem. As I understand it Code uses Electron, which uses Chrome. I pixel peeped text rendered by Chrome and Code; Chrome is correct (RGB) but Code is not (BGR). Changing ClearType settings to BGR had no change on Code but instead made text worse in all applications, as I would expect.

@deepak1556 Is this a Code or Electron issue? Is Electron what you referred to by "controlled by runtime", or what does runtime mean in this context?

In the meantime I had to disable antialiasing with the startup flag `--disable-lcd-text` (from  #195256), not optimal but much better.
