### ISSUE TITLE
git clone should not ask for login

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110886]
Issue Type: <b>Bug</b>

Not sure if it's a coincidence as I have GitHub Issue Notebook installed on a remote machine and didn't connect to it for a while. Today I remote ssh into it, and run `git clone` and then I saw

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/876920/99581868-2d7e0980-2996-11eb-8e3c-7a4af7a6cabd.png">

VS Code version: Code - Insiders 1.52.0-insider (78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2, 2020-11-18T12:39:33.450Z)
OS version: Darwin x64 20.1.0
Remote OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.18GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: penlv-imac|
|OS|Darwin x64 19.4.0|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|32.00GB (21.43GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
tsl-problem-matcher|eam|0.3.1
vscode-pull-request-github-insiders|Git|2020.11.25442
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-language-pack-zh-hans|MS-|1.51.2
remote-containers|ms-|0.150.0
remote-ssh-edit-nightly|ms-|2020.11.24164
remote-ssh-nightly|ms-|2020.11.24164
vscode-github-issue-notebooks|ms-|0.0.58
vsonline|ms-|1.0.3075
debugger-for-chrome|msj|4.12.11
kuskus-kusto-syntax-highlighting|ros|1.1.8
vsc-nwjs|rua|1.0.18
notebook-editing|vsc|1.0.0
markdown-preview-github-styles|bie|0.1.6
vscode-pull-request-github-insiders|Git|2020.11.25442
vscode-github-issue-notebooks|ms-|0.0.58
rust|rus|0.7.8
vscode-lldb|vad|1.6.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by joaomoreno** [comment]
The repo you're cloning seems to be private. So Git asks VS Code to get some credentials from the user. Not sure I understand what the problem is here. 🤔
