### ISSUE TITLE
Provide an mechanism for durable notifications

### ISSUE THREAD

**Issue by brianredbeard** [microsoft/vscode#110893]
As a user with a learning disability it's challenging to engage in context switching.  I often find myself accidentally dismissing the notifications and then finding that I can never retrieve them.  As such, the use of an IDE is actually decreasing my level of productivity rather than increasing it.  It forces me to stay hyper vigilant for notifications so that I'm not then worried about "missing anything".

In the past a number of individuals have cited problems with recalling/reviewing notifications:
  - #96838
  - #95901
  - #44123
  - [#22388](https://github.com/microsoft/vscode/issues/22388#issuecomment-367303794)

Furthermore, there are a contingent of users expressing a congruent annoyance with the current behavior:
  - #46676
  - #103153
 
To be clear I'm able to _deal_ with the current level of notifications.  It's that I presently have no mechanism for **reviewing** them _later_ which _leads_ to anxiety. This means VSCode is dictating what will be consuming my attention/time rather than myself. Knowing that the content is not lost forever would allow me to use the software with lower cortisol levels.  

In the issues previously cited there are a number of proposed changes.  Any of them would (seemingly) work fine.  For the purpose of making things easier on other users the two most common are:

  - A log file containing previous notifications
  - A "notification history" dialog

In the case of the former, I could imagine a number of useful benefits.  Having the logging occur in a structured manner would provide the flexibility for users to search for content easily (In my head I imagine the ability to take an `inotify`/watch on the defined log path and then having external utilities be able to provide users the flexibility to integrate with their system notification settings or only alert on notifications from certain extensions).

**Comment by bpasero** [comment]
@brianredbeard clicking on the bell icon in the status bar bottom right should always show you all notificiation toasts that you have missed, no?

**Comment by brianredbeard** [comment]
@bpasero.... Tragically... no.

For example... Right now there was _something_ about Flutter/Dart that popped up earlier with regards to setting "recommended settings".  It gave me three options:

  - ?
  - ?
  - View information in browser

I of course clicked "view information in browser".  It popped up a link which I looked at.  Unfortunately I don't recall everything the notification said and trying to pull it up results in the following:


![image](https://user-images.githubusercontent.com/57542/99891697-a349d580-2c21-11eb-9d91-6a1131cc4095.png)

Sure... I understand that the notification wasn't "new" but it perfectly illustrates _**why**_ using VScode is making me anxious.  I'm now at a loss and cannot even answer _your_ questions accurately to provide a detailed bug report.

-------------------------

I'll also add the caveat: I understand that there are problems a number of ways (hell, probably dozens if not hundreds of ways) that I'm "not using the IDE _correctly_"... at the same time Microsoft is not providing me efficient mechanisms of resolving this without sitting through dozens of videos explaining how I can "get started" with Javascript development with Azure functions.

**Comment by bpasero** [comment]
@brianredbeard once you have interacted with a notification it will hide and you cannot open it again, are you suggesting to have a setting to keep it open permanently until you click the X?

**Comment by brianredbeard** [comment]
Dear god no.  That would be the absolute opposite of my personal need.  I'm not trying to have _more_ things polluting the screen _**demanding**_ my attention be taken away from the task at hand (the reason I'm using the IDE in the first place).   Let me repeat the first sentence of this report:

> As a user with a learning disability it's challenging to engage in context switching.

I need some durable place for these messages so that I can review them _later_ when I have the attention to _spend_.

**Comment by bpasero** [comment]
> I need some durable place for these messages so that I can review them later when I have the attention to spend.

@brianredbeard yeah that is what I was suggesting: when you interact with the notification it disappears as today but clicking the bell icon in the status bar shows all of them still until you remove them with a X button click.

**Comment by brianredbeard** [comment]
I think there's some misunderstanding.

This isn't an "important" example (based on the contents of the notification), but let's go with it:

![image](https://user-images.githubusercontent.com/57542/100168320-e2706480-2e75-11eb-9397-149413bc8185.png)

Given the structure of the pop-up above I presently have ~three~ four options:
  - Configure notification
  - Collapse Notification
  - Clear Notification
  - Endlessly leave that dialog up to continue using a combination of color, words, and pictograms _just barely in my peripheral vision_ to keep drawing my attention

What I _think_ you're proposing is that I:
  - carefully navigate down to the popup
  - cross my fingers
  - hope that in the attempt to get that dialog out of my peripheral vision that don't stray _too far_ to the right (the natural place to end up when I wildly swing the mouse over to the side of the screen)
  - click the icon which measures **3mm x 3mm** without accidentally missing the mark and dismissing the dialog
  - repeat this workflow every time spurious notifications show up 

Is that correct?

**Comment by bpasero** [comment]
@brianredbeard maybe it would be easier if you would explain to me very detailed what you expect and I stop trying to interpret something? Let's start from 0, and please explain to me what you expect. Please assume I am not familiar with anything around notifications.

**Comment by brianredbeard** [comment]
Just to be clear, this entire interaction was demoralizing.  It wasn't until after investing almost a week into trying to provide copious amounts of context that I got a response containing more than one sentence.

It's this terseness which exacerbated the situation.

> @brianredbeard once you have interacted with a notification it will hide and you cannot open it again, are you suggesting to have a setting to keep it open permanently until you click the X?

I've re-read this probably a dozen times trying to understand why I would desire a setting which will keep make the notification a **_permanent_** distraction (keeping "it" open permanently). I've come to the conclusion that (potentially) due to the large number of issues you need to work through, @bpasero, you _meant_:

> @brianredbeard once you have interacted with a notification it will hide and you cannot open it again. It sounds like you are suggesting to have a setting which will allow a user to:
>  - dismiss a notification from the screen
>  - leave the notification in the notification dialog accessed via the bell icon
>  - permanently remove the notification when you click the X
> 
> Is that correct?

In the event that's what was _intended_, I can live with that though it would still leave unresolved many of the issues cited in the first comment in this issue.
