### ISSUE TITLE
Show cell toolbar when navigating via keyboard

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#110883]
With the recent changes I introduced (the toolbar only appearing on hover) it would be great if we could show the toolbar when the mouse is outside of the notebook area but still focused on a cell. When you tab into the cell, since the toolbar isn't visible you don't see the tab stops. I couldn't get this fixed but maybe one you can figure it out.

![Kapture 2020-11-18 at 11 23 45](https://user-images.githubusercontent.com/35271042/99577819-babe5f80-2990-11eb-9c73-bc1cd441c119.gif)

Views have the same behavior of only showing actions on hover, but when you focus the title they are shown:

![image](https://user-images.githubusercontent.com/35271042/99578231-610a6500-2991-11eb-8cac-a5104e267144.png)

**Comment by rebornix** [comment]
![tree-actions](https://user-images.githubusercontent.com/876920/99582317-d0368800-2996-11eb-89f1-5849c872edaa.gif)

@misolori I guess I'm seeing the same thing in the tree view ?

**Comment by misolori** [comment]
@rebornix that's when they are collapsed. Try it while they are open:

<img width="500" src="https://user-images.githubusercontent.com/35271042/99585110-bdbe4d80-299a-11eb-943b-619441550747.gif">

**Comment by misolori** [comment]
I was able to fix this by making the focused item visible when the rows are not hovered `.monaco-list-rows:not(:hover)`

![Kapture 2020-11-18 at 12 51 26](https://user-images.githubusercontent.com/35271042/99586601-d0398680-299c-11eb-9b08-c17993670827.gif)

It would be great if we could set this as well when someone moves away from keyboard focus but not sure how to do that.

**Comment by misolori** [comment]
Verifiers, please check that:
- Cell toolbar appears only on hover (when mouse is inside the notebook file)
- Cell toolbar appears when mouse is outside of notebook (sidebar, titlebar, etc.)
- When mouse is outside notebook, toolbar appears on focused item
