### ISSUE TITLE
All terminals have invisible text

### ISSUE THREAD

**Issue by grahamm78** [microsoft/vscode#110832]
Issue Type: <b>Bug</b>

I can't see text in all my terminal windows which were open for a while.  I can see a cursor but no text.  I have Cmd, "Restore Dependencies" and a WAVE Razzle terminal.  Closing and recreating a terminal (Razzle) fixes that terminal but the other ones still open are still broken.

I have a second VSCode instance open and both of them have the problem.  The windows have been open a couple of days and I'm connecting to the system running VSCode via terminal services - but I don't have any graphics issues with any other windows.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.21262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (6.42GB free)|
|Process Argv|--crash-reporter-id 7dd2d561-081d-4b47-a2b0-2e055dd17a8e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
git-tree-compare|let|1.10.0
syntax-project-pbxproj|mar|0.1.3
devinsights|Mic|2020.10.15-1
tdpcode|Mic|1.6.3
vscode-nmake-tools|Mic|3.0.201105003
sarif-viewer|MS-|3.0.2
remote-wsl|ms-|0.51.3
cpptools|ms-|1.1.1
source-depot|sup|0.0.2
gitblame|wad|6.0.0

</details>

**Comment by meganrogge** [comment]
Thanks for the issue. Are you using WSL/ remote when this happens?

**Comment by grahamm78** [comment]
Thanks Megan - no, I am using local source /  WAVE

Cheers,
Graham

**Comment by meganrogge** [comment]
What happens if you scroll up in those cases?

**Comment by grahamm78** [comment]
It would scroll up but still blank.

I've since restarted and haven't been able to repro.  anything you'd like
me to do if I repro again?

**Comment by meganrogge** [comment]
Thanks so much for asking. If you see this again, please enable logging of the data being sent to the emulator from the shell process by running the "Terminal: Toggle Escape Sequence Logging" command from the command palette (F1), the logs can then be viewed in the devtools console (Help > Toggle Developer Tools). Closing this for now.

**Comment by grahamm78** [comment]
sounds good, thanks

Cheers,
Graham

**Comment by grahamm78** [comment]
hi @meganrogge - the issue just repro'ed again.  Could we reopen this?  
In this case I was actively using the IDE, using razzle window as well as a static analysis plugin (C/C++ Code Analysis), and all of a sudden all text in all of the terminals disappeared.  I could scroll up and down by holding the mouse button and dragging - and actually, doing this on the code analysis terminal , I'd see some sparse characters in certain parts - mostly the letter 'G' but also other characters.  Attaching screen shot.

![image](https://user-images.githubusercontent.com/6295566/100157383-4e939e00-2e5f-11eb-976d-82f825efde3b.png)

- If I create a new terminal, the new terminal looks OK.  The other terminals are still broken.
- tried toggling Escape Sequence Logging but cannot open the DevTools console.  Help -> Toggle Developer Tools or CTRL+SHIFT+I doesn't seem to be doing anything.
- One note, I am running vscode as admin

Log (Window)

[2020-11-24 14:17:25.870] [renderer1] [error] Object has been destroyed: TypeError: Object has been destroyed
    at WebContents._.send (electron/js2c/browser_init.js:185:2149)
    at IpcMainImpl.<anonymous> (C:\Users\grahamm\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:562:646)
[2020-11-24 14:19:26.716] [renderer1] [error] Object has been destroyed: TypeError: Object has been destroyed
    at WebContents._.send (electron/js2c/browser_init.js:185:2149)
    at IpcMainImpl.<anonymous> (C:\Users\grahamm\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:562:646)

Log (Main) had the same source lines but just prefixed with [main] instead of [renderer1]

I turned up Developer:Set Log Level and I see log entries typing into a terminal (Razzle / cmd)

[2020-11-24 14:40:34.460] [renderer1] [trace] IPty#resize 258 22
[2020-11-24 14:40:34.460] [renderer1] [trace] IPty#resize 258 22
[2020-11-24 14:40:34.461] [renderer1] [trace] IPty#resize 258 22
[2020-11-24 14:40:34.472] [renderer1] [trace] IPty#resize 258 22
[2020-11-24 14:40:35.470] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:35.615] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:35.736] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:35.883] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:36.000] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:36.125] [renderer1] [trace] IPty#write 1 characters
[2020-11-24 14:40:37.627] [renderer1] [trace] CommandService#executeCommand setContext
[2020-11-24 14:40:37.627] [renderer1] [trace] CommandService#executeCommand setContext

I've unblocked myself while keeping the repro by closing and reopening the razzle window while leaving the others in their blank state.

**Comment by grahamm78** [comment]
@meganrogge - I found that the "Toggle Developer Tools" works when not running as admin so I've launched this way and will continue to attempt to repro.

**Comment by meganrogge** [comment]
I've actually seen this repro recently

**Comment by phinate** [comment]
from [this stackoverflow post](https://stackoverflow.com/questions/53004732/vscode-bash-terminal-text-turns-invisible), I found that this can be resolved for me by setting `terminal.integrated.gpuAcceleration` in settings to `off`
