### ISSUE TITLE
Add command palette entry to allow access to "scoped" commands

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#110820]
If you are in "command" mode `>` in the command palette, you can't easily access scoped commands by their scope _task_, _edt_, etc.

![image](https://user-images.githubusercontent.com/641685/99437092-d9f0ba80-28c6-11eb-9ca7-7a21867cee74.png)

I often end up in the command palette and forget to remove the `>` and type `task ` or `edt ` and then can't find what I am looking for, and then have to remove the `>`. Maybe we can add an entry (if one doesn't exist) or an alias (if an entry already exists) so that this flow would be less problematic.

**Comment by bpasero** [comment]
In theory each provider can already do that today by registering a command to F1. But we could also automatically just do that by creating a command for each quick open provider that exists.

**Comment by bpasero** [comment]
@eamodio have something working in https://github.com/microsoft/vscode/tree/ben/110820

Result:

![image](https://user-images.githubusercontent.com/900690/99635099-cb7ade00-2a41-11eb-9d68-bdce74250038.png)

I cannot know if a quick open provider already registered for the F1 list so you may end up with duplicates.

Maybe some UX thoughts would help, @misolori ?

**Comment by bpasero** [comment]
Already seeing some duplicates appear:

![image](https://user-images.githubusercontent.com/900690/99635454-4ba14380-2a42-11eb-8905-58589fe7795d.png)

**Comment by bpasero** [comment]
Some feedback from UX call:
* not very discoverable either and potentially many duplicates
* you cannot continue to type, e.g. when you are at `>edt ` and want to type the name of an editor it would not work
* should we guide the user to the help entries when no command was found while typed?
* should we make the existing commands available when you type it's prefix (e.g. `edt` finding the right one)
