### ISSUE TITLE
Allow setting editor.fontWeightBold

### ISSUE THREAD

**Issue by eggman314** [microsoft/vscode#110863]
Recently it's been possible to set `terminal.integrated.fontWeightBold`. A similar setting `editor.fontWeightBold` should be available for the editor, partly to allow disabling use of bold fonts, partly because if you usually prefer a light or extra light font, bold text will stand out too much and even be hard to read. This picture is a good example.

![image](https://user-images.githubusercontent.com/3087751/99533890-7df96500-299e-11eb-85dc-bd9816dee774.png)

`editor.fontWeightBold` should take a number in the same range as `editor.fontWeight`, at a minimum, but I feel it should also be possible to give a relative value, e.g. "+200". This would make it a lot more convenient for those who switch fonts frequently, as different fonts look good at different weights. The last could maybe be given a separate setting like `editor.fontWeightBold.relative` instead?

**Comment by 54696d21** [comment]
I really want this feature

**Comment by toothbrush7777777** [comment]
Are any mentoring instructions available? I'd be happy to implement this.

**Comment by alexdima** [comment]
@toothbrush7777777 You can follow all the places where `editor.fontWeight` is used (or `editor.lineHeight` or `editor.letterSpacing`).
