### ISSUE TITLE
Char array should be shown as string, not as nornal array

### ISSUE THREAD

**Issue by PatrickChen83** [Microsoft/vscode#11085]
- VSCode Version: 1.3.1
- OS Version: Linux 4.7.1

As title, character array is shown as a normal array everywhere, which can be annoying when watching on a very long string.

![normal array](http://imgur.com/rTOwqeH.jpg)

Steps to Reproduce:

1. Install C/C++ plugin
2. Set up `launch.json` and start debugging.
3. Set an breakpoint to view variables.

**Comment by isidorn** [comment]
This is an issue with the C++ extension, since this knowledge is coming from the C++ debug adapter, vscode is just displaying it.
Can you please move this issue to https://github.com/Microsoft/vscppsamples/issues
Thanks!
