### ISSUE TITLE
Problems view with "active file filter" does not show marker in side-by-side comparison view

### ISSUE THREAD

**Issue by HolgerSeith** [microsoft/vscode#110844]
Issue Type: <b>Bug</b>

The problems view with "Show Active File Only" option does not show marker in side-by-side comparison view (comparing current file with latest from repository). 
This is especially useful to check the changed files for ESLint problems before committing into the repository.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonviewer|cci|1.2.2
npm-intellisense|chr|1.3.1
jsrefactor|cms|2.20.6
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.2
vscode-mocha-test-adapter|hbe|2.8.1
vscode-test-explorer|hbe|2.19.3
vscode-drawio|hed|1.1.0
vscode-styled-components|jpo|1.2.0
vsliveshare|ms-|1.0.3206
debugger-for-chrome|msj|4.12.11
vscode-react-refactor|pla|1.0.5
psi-header|psi|1.14.1
code-spell-checker|str|1.9.4
vscode-icons|vsc|11.0.0
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by sandy081** [comment]
To verify:

- Have some problems in a file and make sure they are visible in problems views
- Enable the filter - Show Active File Only - in problems view
- Open the diff editor for the above file
- Make sure the problems are visible for that file in the problems view
