### ISSUE TITLE
Legacy Settings Editor does not support markdownEnumDescriptions well

### ISSUE THREAD

**Issue by hudcap** [microsoft/vscode#110840]
Issue Type: <b>Bug</b>

The `markdown-all-in-one` extension adds markdown to the settings.json file, but vscode throws syntax errors for all of it, and some of the settings seem to be missing.
I don't fully understand it, but according to @Lemmingh in https://github.com/yzhang-gh/vscode-markdown/issues/847, "the legacy Settings Editor does not support `markdownEnumDescriptions` well," and it should be reported here.

I'm a little out of my depth here, but @Lemmingh sounds like he knows what he's talking about.

Screenshots:
![image](https://user-images.githubusercontent.com/4990645/99432392-1679e180-28da-11eb-84df-e62f99b87255.png)
![image](https://user-images.githubusercontent.com/4990645/99432622-69539900-28da-11eb-82e9-0c291ae249dd.png)
![image](https://user-images.githubusercontent.com/4990645/99432680-7bcdd280-28da-11eb-8cb2-27cd5d1e7070.png)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-markdownlint|Dav|0.37.2
todo-tree|Gru|0.0.188
reg|ion|1.0.1
latex-workshop|Jam|8.14.0
vscode-home-assistant|kee|1.11.0
stata-enhanced|kyl|1.6.1
git-graph|mhu|1.27.0
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
vscode-data-preview|Ran|2.2.0
vscode-autohotkey|sle|0.2.2
code-spell-checker|str|1.9.4
latex-utilities|tec|0.3.7
vscode-icons|vsc|11.0.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by Lemmingh** [comment]
The source of those configuration properties:

* `markdown.extension.list.indentationSize`
  * https://github.com/yzhang-gh/vscode-markdown/blob/ff79b2e7a69dcbfd04d5c289999c1a09ef784e61/package.json#L244-L257
  * https://github.com/yzhang-gh/vscode-markdown/blob/ff79b2e7a69dcbfd04d5c289999c1a09ef784e61/package.nls.json#L20-L22

* `markdown.extension.toc.orderedList`
  * https://github.com/yzhang-gh/vscode-markdown/blob/ff79b2e7a69dcbfd04d5c289999c1a09ef784e61/package.json#L365-L369
  * https://github.com/yzhang-gh/vscode-markdown/blob/ff79b2e7a69dcbfd04d5c289999c1a09ef784e61/package.nls.json#L43

They look good in the Settings UI. So, the problem should come from the Settings Editor.

**Comment by roblourens** [comment]
This editor is deprecated and I normally wouldn't fix it but this looks pretty bad and it's an easy fix.
