### ISSUE TITLE
Unable to recover all the synced data properly because of an internet connection problem

### ISSUE THREAD

**Issue by mohamedbasyouni** [microsoft/vscode#110824]
- VSCode Version: 1.51
- OS Version: windows 10 x64 bit october 2020 version

Steps to Reproduce:

1. Install a brand new vscode and sign in with my account to sync my previous data from the cloud
2. An internet corruption for a moment (out of my hand) happened while syncing the extensions
  -> Can't restore the rest of the synced data after restoring the internet connection
3. Sign out and sign in again and merge the data
  ->  it seems that the rest of the data was overwritten by the default data which was surprisingly synced when I signed in again

#### I can't restore my proper data which was synced before

Does this issue occur when all extensions are disabled?: It doesn't relate to any extension as it was in loading the extensions stage then a bad internet connection happened in the middle of the process.

**Comment by sandy081** [comment]
You can restore your old data from the synced data view. Please follow this link - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data
