### ISSUE TITLE
Hidden menu bar stays shown when mnemonics are used

### ISSUE THREAD

**Issue by Azorlogh** [microsoft/vscode#110822]
- VSCode Version: 1.51.1
- OS Version: Linux x64 5.4.77-1-lts

Steps to Reproduce:

1. Set window.menuBarVisibility to "hidden"
2. Set window.enableMenuBarMnemonics to true
→ menu is now hidden
3. Press Alt + F
→ menu is now show and File is deployed
4. press Esc twice to close menu bar
➜ menu bar stays open

The menu bar should close as it is set to "hidden".

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@deepak1556  in the hidden case, mnemonics should not bring up the menu it all, but electron still brings them up

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.74`
