### ISSUE TITLE
Creating a file/folder doesn't bring VSC into focus

### ISSUE THREAD

**Issue by drunkenplatypus** [microsoft/vscode#110872]
## Description
If you have VSC out of focus and you create a file/folder by right-clicking in the explorer, it doesn't bring VSC into focus so that you can type the name.

## Steps to reproduce
1. Have VSC in the foreground, but not in focus.
2. Right-click in the explorer and create a new file/folder
3. As VSC is still out of focus, you'll still be typing in the application you currently have in focus instead of VSC.

## Expected
I'd expect that by creating a file/folder in the explorer you'd would bring VSC into focus and you'd be ale to type out the name of the file/folder.

**Comment by isidorn** [comment]
Dup of context menu should focus App. You can search for it. Might be an electron issue.
