### ISSUE TITLE
My managed workspace won't start

### ISSUE THREAD

**Issue by francoisprudhomme** [microsoft/vscode#110876]
Issue Type: <b>Bug</b>

Steps to reproduce are pretty straight forward: 
- sign in to code space. 
- log into my  codespace  ("dev-tester").  which is manage by codespace (not custom created by me)
- then we go this error below:  

Failed to connect to the remote extension host server (Error: Command 'docker ps -aq --filter label=Type=codespaces --filter status=running' failed with message Error: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json?all=1&filters=%7B%22label%22%3A%7B%22Type%3Dcodespaces%22%3Atrue%7D%2C%22status%22%3A%7B%22running%22%3Atrue%7D%7D: dial unix /var/run/docker.sock: connect: permission denied , return code 1)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|--crash-reporter-id 47f0320f-8c79-4200-9fc0-cbfcbbd23d4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.15.0
vscode-intelephense-client|bme|1.5.4
githistory|don|0.6.14
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
go|gol|0.18.1
vscode-github|Kni|0.30.4
vscode-language-babel|mgm|0.0.30
dotenv|mik|1.0.1
azure-account|ms-|0.9.4
cpptools|ms-|1.1.2
vsliveshare|ms-|1.0.3206
vsonline|ms-|1.0.3075
codebucket|pst|0.2.0
html-preview-vscode|tht|0.2.5

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Please create a topic at https://github.community/c/codespaces-beta/45, thanks!
