### ISSUE TITLE
Weird on-type-rename-decoration

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110878]
Issue Type: <b>Bug</b>

Right now I can see the on-type-rename-decoration always when moving cursors in a typescript file and it renders a red border at the end of every occurrence.

![on-type-rename](https://user-images.githubusercontent.com/876920/99571586-57303400-2988-11eb-93d4-61caf38056db.gif)

VS Code version: Code - Insiders 1.52.0-insider (f11635ef1199ba5c43d9b83bb8b33036ea26d5b1, 2020-11-18T08:43:18.204Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nrayburn-tech** [comment]
I am having the same issue.  Not sure if you tested, but mine is performing the rename functionality, it isn't just the decoration.

VS Code version: Code - Insiders 1.52.0-insider (78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2, 2020-11-18T12:39:33.450Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.72GB free)|
|Process Argv|--crash-reporter-id 03f31147-8ebd-457f-9df0-cdf4b9cd93d5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by aeschli** [comment]
@nrayburn-tech Please file a separate issue if you feel the beahviour is not right. Let's keep this issue about the decoration.
