### ISSUE TITLE
Search Enhancement

### ISSUE THREAD

**Issue by pxf3** [microsoft/vscode#110895]
Issue Type: <b>Feature Request</b>

Enable to Search (Ctrl-Shift-F)  to  get back to a previous search.
Possible solutions
1- provide a list (dropdown) of previous search strings (maybe 8-10 max) 
2- back and next buttons to cycle through search strings
I find myself searching often for something only to have to search for something else and would like to go back to the previous search. 

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Cursor up keystroke in the input field already does this.

**Comment by pxf3** [comment]
Awesome, thanks John for such a quick reply. Just tried works great.

**Comment by gjsjohnmurray** [comment]
Glad to help. Please close this issue.
