### ISSUE TITLE
[Remote SSH] code-insiders from command line does not open folder

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110887]
Issue Type: <b>Bug</b>

`code-insiders .` does nothing when executed in the integrated terminal

VS Code version: Code - Insiders 1.52.0-insider (78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2, 2020-11-18T12:39:33.450Z)
OS version: Darwin x64 20.1.0
Remote OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.18GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: penlv-imac|
|OS|Darwin x64 19.4.0|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|32.00GB (21.43GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
tsl-problem-matcher|eam|0.3.1
vscode-pull-request-github-insiders|Git|2020.11.25442
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-language-pack-zh-hans|MS-|1.51.2
remote-containers|ms-|0.150.0
remote-ssh-edit-nightly|ms-|2020.11.24164
remote-ssh-nightly|ms-|2020.11.24164
vscode-github-issue-notebooks|ms-|0.0.58
vsonline|ms-|1.0.3075
debugger-for-chrome|msj|4.12.11
kuskus-kusto-syntax-highlighting|ros|1.1.8
vsc-nwjs|rua|1.0.18
notebook-editing|vsc|1.0.0
markdown-preview-github-styles|bie|0.1.6
vscode-pull-request-github-insiders|Git|2020.11.25442
vscode-github-issue-notebooks|ms-|0.0.58
rust|rus|0.7.8
vscode-lldb|vad|1.6.0

(5 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
What is `which code-insiders`?

Does your bashrc mess with the PATH?

**Comment by roblourens** [comment]
Assuming you cd'd into a different folder when running that

**Comment by rebornix** [comment]
I'm in an empty workspace and then cd into one folder and run `code-insiders -r `. I can only reproduce once yesterday. I'll check my `code-insiders` if I see it again.
