### ISSUE TITLE
Syncing stopped when I was testing different color themes

### ISSUE THREAD

**Issue by leniel** [microsoft/vscode#110817]
Issue Type: <b>Bug</b>

Just try to apply different color themes... one after the other. The error message informed it was making too many requests.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (2.13GB free)|
|Process Argv|--crash-reporter-id 27fff4c0-d1c7-4f4b-b987-099f71106590|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|0.1100.0
vscode-color|ans|0.4.5
aadb2c|Azu|1.2.93
spellright|ban|3.0.52
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
transformer|dak|1.9.0
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.0.1
EditorConfig|Edi|0.15.1
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.2
git-project-manager|fel|1.7.1
dotnet-test-explorer|for|0.7.4
vscode-test-explorer|hbe|2.19.3
minify|Hoo|0.4.3
githd|hui|2.2.4
latex-workshop|Jam|8.14.0
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
vscode-peacock|joh|3.8.0
wordcounter|kir|2.3.0
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.6
mssql|ms-|1.9.0
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.1.1
angular2-inline|nat|0.0.17
color-highlight|nau|2.3.0
angular-console|nrw|14.0.1
indent-rainbow|ode|7.4.0
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
git-merger|sha|0.4.1
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
code-spell-checker|str|1.9.4
vscode-lldb|vad|1.6.0
highlight-matching-tag|vin|0.10.0
gitblame|wad|6.0.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.9.6

(10 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
If you save settings often you will hit rate limit which is intended. You should be able to restart VS Code and start sync again.

I guess debounce should improve situation with frequent saves #91286.
