### ISSUE TITLE
Add an option to disable the new interactive rebase UI

### ISSUE THREAD

**Issue by idoberko2** [microsoft/vscode#110819]
I'm using VS Code as my git editor, i.e. my git config contains the following line:
```
core.editor=code --wait
```
I'm use to benefit from VS Code's great editing features to perform various git operations.

The latest update introduced a new feature: a UI for the interactive git rebase: [https://code.visualstudio.com/updates/v1_51#_git-rebase-command](https://code.visualstudio.com/updates/v1_51#_git-rebase-command). There's currently no way to disable this feature which forces me to use other editors for git.

I think a disable feature in the settings (turned off by default) could benefit all users: both users that wish to use the new UI, alongside users that wish to use a text editor.

**Comment by eamodio** [comment]
The new UI for rebasing isn't from VS Code, it is from GitLens. And it can be disabled by adding the following to your `settings.json`

```json
	"workbench.editorAssociations": [
		{
			"viewType": "default",
			"filenamePattern": "git-rebase-todo"
		}
	],
```
