### ISSUE TITLE
Formatting Stops After 20,000 Characters

### ISSUE THREAD

**Issue by haverland389** [microsoft/vscode#110818]
Issue Type: <b>Bug</b>

If you have a line that is greater than 20,000 characters, the formatting does not work. I found this when working with JSON. I had a tag with an extremely long value. The line had all white formatting, even the tag, instead of multiple colors. I figured at first it was an issue with the value, but once i reduced the line to 20,000 characters (including spaces) the formatting returned (various colors).

For example if you have a single line like ["server": {"stderr": "\"Allow\",\r\n" }] you will see multiple colors. If you make the value "\"Allow\",\r\n" long enough so that the whole line (no just the data) has 20,001 characters, the formatting switched to all white.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
compareit|in4|0.0.2
vscode-nuget-package-manager|jmr|1.1.6
powershell|ms-|2020.6.0
code-spell-checker|str|1.9.4

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do I understand correctly that under "formatting" you mean syntax highlighting?

In this case 20000 is default value for performance reasons, but you should be able to increase it with `editor.maxTokenizationLineLength` setting.

**Comment by haverland389** [comment]
That is correct. Thank you for your response!

Andrew
________________________________

**Comment by AryanBeezadhur** [comment]
@haverland389 if your issue was solved, please close this issue
