### ISSUE TITLE
Git: Allow option to "fetch --all" on autofetch

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#110811]
VScode has a "git.autofetch" option which periodically fetches from upstream. However, when forking a project (which a lot of us do) you will only ever fetch from `origin`. In my case I want to periodically fetch from upstream too so I can have up-to-date changes from others working on the same project.

On the command line the change would be adding `--all`.  In terms of the built-in extension the change would be here:
https://github.com/microsoft/vscode/blob/master/extensions/git/src/autofetch.ts#L102

Today `fetchDefault` is always called. [`fetchAll`](https://github.com/microsoft/vscode/blob/master/extensions/git/src/repository.ts#L1310-L1312) exists and could be called instead if an option is set to true.

## Example Config
It would make sense for autoFetch to take a series of options like, `"all", "current", "off"`. But im assuming we can't modify this option now as it's being used.

```json
  "git.autofetch": true, // Most likely can't change this now
  "git.autofetchAll": true, // fetchAll when fetching (overriding above)
```

**Comment by jasonwilliams** [comment]
@joaomoreno what do you think about this?

**Comment by jasonwilliams** [comment]
After some though I think fetchAll makes a better default than fetchDefault because then extensions like `gitlens` would work out the box on remote views. If a developer is working from a fork it would mainly just work. If you work on a central repository (no forks) you would only have 1 remote anyway so fetchAll would continue to work as normal.

**Comment by eamodio** [comment]
I think we can probably get away with adding an `all` option to `git.autofetch`.

**Comment by jasonwilliams** [comment]
So the options for `git.autofetch` would be `true` | `false` | `“all”` ?

**Comment by jasonwilliams** [comment]
> I think we can probably get away with adding an `all` option to `git.autofetch`.

"autofetch" is `"type": "boolean"` so i don't know how that will be possible https://github.com/microsoft/vscode/blob/master/extensions/git/package.json#L1647

**Comment by jasonwilliams** [comment]
@eamodio I had a go at this here: https://github.com/microsoft/vscode/pull/111090
What do you think?

**Comment by eamodio** [comment]
Verify that setting `"git.autofetch": 'all'` fetches all remotes, and still that `false` stop auto-fetching, and that `true` fetches the default remote
