### ISSUE TITLE
Horizontal scrolling in output cells

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#110825]
**Ask:** Horizontal scrolling for output cells in the core notebook. Or max height of cells for plain text that's vertically scrollable after.

When there's a big block of text, it's hard to read it all with no text wrapping. And if to help with wrapping, you choose to use plain text instead then for really large text like the source for a website, it doesn't collapse any of it and the block of text is way too long.

Both scenarios currently:
![image](https://user-images.githubusercontent.com/12758612/99457286-93f42080-28df-11eb-9055-1b803e285b2c.png)

**Comment by claudiaregio** [comment]
+1 from customer: https://github.com/microsoft/vscode-jupyter/issues/4471

**Comment by ldorigo** [comment]
Just my two cents, but is this really a feature request (that needs 20 upvotes for being approved, knowing that only a small fraction of users are on the insiders edition)? 

Not having any way to view what's in my outputs if the line is longer than  VS code's window seems more like a bug (or a major usability issue) to me. It makes it almost impossible to do text analysis/processing in the new notebooks.

Either way, hope to see this fixed soon!

**Comment by ldorigo** [comment]
To add on to this, it looks like it isn't even possible to select the output and copy-paste it somewhere else, as that copies the cell (code) instead. So there is currently effectively no way to know what the output of a cell was, other than saving that output to file...
