### ISSUE TITLE
Shift+Alt+O does not organize imports into single line (regression)

### ISSUE THREAD

**Issue by GintV** [microsoft/vscode#110888]
- VSCode Version: **1.51.1**
- OS Version: **Windows 10 2004**

Steps to Reproduce:

1. Have npm project TS
2. Split single import into 2 lines
![image](https://user-images.githubusercontent.com/17436829/99582382-b45cd180-29ea-11eb-8cb2-62cde83ec1f0.png)
![image](https://user-images.githubusercontent.com/17436829/99582412-c0489380-29ea-11eb-8a51-36c8bef92a76.png)

3. Hit shift+alt+o

**Previous expected behaviour**: import is organized into single line
**Actual behaviour**: import is organized through multiple lines
![image](https://user-images.githubusercontent.com/17436829/99582473-d2c2cd00-29ea-11eb-8751-a07f33f3fdcc.png)

Does this issue occur when all extensions are disabled?: **Yes**

Strange thing is, I only noticed this after update to 1.51.1 (from 1.48.2). I tried reinstalling 1.48.2 only to find out that it has exact same behaviour. I then tried 1.45.1 and it was back to how I used to.

Event stranger thing is that I have another laptop (**Windows 10 1909**) with 1.48.2 installed and shift+alt+o would organize imports into **single line**. I then updated to 1.51.1 and it would still do **single line organize**.

I am not sure what is going on, but I asked a few colleagues about this and they too noticed that after recent update imports are not organized into single line.

All behaviours were observed with and without extensions.

**Comment by mjbvz** [comment]
Please share a project that demonstrates this issue

**Comment by GintV** [comment]
It is not project specific, reproduced on this very repo:

v1.45.1
![vscode-1 45 1](https://user-images.githubusercontent.com/17436829/99889278-24be5980-2c5c-11eb-931b-c4245d25717d.gif)
v1.51.1
![vscode-1 51 1](https://user-images.githubusercontent.com/17436829/99889277-238d2c80-2c5c-11eb-91ae-d3f4815284b2.gif)

**Comment by mjbvz** [comment]
Please share a minimal project that demonstrates this issue

**Comment by GintV** [comment]
@mjbvz 

Repro steps as steps are in the issue description. I am using VSCode because this issue is about it. Issue is reproducible in any project, as example you can repro it in VSCode project codebase.

**Comment by mjbvz** [comment]
This looks expected to me. If you disagree, please file an issue against typescript: https://github.com/microsoft/TypeScript/issues/

**Comment by GintV** [comment]
Not sure how it is related to typescript directly rather than vscode
