### ISSUE TITLE
Exploration: Switching keyboard layout on Windows crashes VS Code

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#110806]
Version: 1.52.0-exploration (user setup)
Commit: aaaead3835f722f023abc3de44d729f7d5fb1797
Date: 2020-11-17T07:04:49.800Z
Electron: 11.0.0-beta.20
Chrome: 87.0.4280.40
Node.js: 12.18.3
V8: 8.7.220.10-electron.0
OS: Windows_NT x64 10.0.19042

---

On Windows, with at least 2 configured keyboard layouts:

1. Open VS Code Exploration
2. Press <kbd>Win+Space</kbd> to switch keyboard layout

💥 VS Code crashes. This is the only thing that comes when it crashes with `--verbose`:

```
[26132:1117/144105.973:ERROR:node_bindings.cc(144)] Fatal error in V8: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
```

**Comment by joaomoreno** [comment]
Other steps:

1. Open VS Code Exploration
2. <kbd>Alt Tab</kbd> to another app
3. Switch keyboard layout
4. <kbd>Alt Tab</kbd> back to VS Code

💥 Crash

**Comment by bpasero** [comment]
Nice catch, possibly a missing adoption in `native-keymap`?

//cc @alexdima

**Comment by alexdima** [comment]
@deepak1556 Please LMK if there's something I can help with. We are consuming the latest `native-keymap@2.2.0` in vscode, after some PRs to help with Electron crashes went in -- https://github.com/microsoft/node-native-keymap/pull/22 , https://github.com/microsoft/node-native-keymap/pull/23 . But those PRs only touched the mac code, maybe there is still a problem on windows?

**Comment by deepak1556** [comment]
@alexdima yup thats correct, missing a handlescope here https://github.com/microsoft/node-native-keymap/blob/master/src/keyboard_win.cc#L421

**Comment by deepak1556** [comment]
Should be fixed in todays' release.

**Comment by alexdima** [comment]
\closedWith 58be98a0aa64e70e2dc524e06cc69e193bbaf872
