### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by rapastranac** [microsoft/vscode#110968]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

VSCode is freezing with mutlthreading. It does not respond well when debugging and it does not even show variables values.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|15.49GB (7.41GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 89b24ae1-9aaa-4024-952a-ea5cd361c49a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   143	  3962	code main
    0	    32	  3967	   zygote
    0	    95	  4032	     gpu-process
    0	    32	  3968	   zygote
    0	    48	  4051	   utility
    0	   301	  4062	   window (BranchHandler.hpp - mvc - Visual Studio Code)
    0	     0	  4135	     /bin/bash
    0	   143	  4142	     extensionHost
    0	    79	  4206	       /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools
    0	   206	  4489	         /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/bin/cpptools-srv 4206 6
    0	     0	  5332	       bash /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/debugAdapters/OpenDebugAD7
    0	    48	  5337	         /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/debugAdapters/mono.linux-x86_64 --config /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/debugAdapters/framework/config.linux /home/andres/.vscode/extensions/ms-vscode.cpptools-1.1.2/debugAdapters/bin/OpenDebugAD7.exe
    0	    95	  4171	     watcherService
    0	    63	  4187	     searchService
    0	     0	  5387	     /bin/bash
    0	     0	  5396	       /bin/sh /tmp/Microsoft-MIEngine-Cmd-cfusaxqf.alo
    8	    79	  5398	         /usr/bin/gdb --interpreter=mi --tty=/dev/pts/1
    0	     0	  5409	           /home/andres/Documents/github/mvc/Sources/a.out
    0	   111	  4281	   shared-process
    0	     0	  5682	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  5683	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    95	  5556	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (BranchHandler.hpp - mvc - Visual Studio Code)
|    Folder (mvc): 4707 files
|      File types: less(71) cc(30) dat(25) csv(25) txt(24) h(22) cmake(13)
|                  hpp(12) js(12) py(12)
|      Conf files: cmake(13) makefile(2) launch.json(1) settings.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
mpi-snippets|ada|0.6.0
shell-format|fox|7.0.1
gc-excelviewer|Gra|3.0.40
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.2
cmake|twx|0.0.17

</details>

**Comment by weinand** [comment]
Please provide reproducible steps.
