### ISSUE TITLE
Settings Sync throttling unnecessarily

### ISSUE THREAD

**Issue by jspiro** [microsoft/vscode#110907]
Issue Type: <b>Bug</b>

When you are scrolling through your themes, apparently it saves the current theme you're testing before you've hit return to save it. If you do this for a while, settings sync discontinues syncing due to rate limit (which is understandable).

<img width="645" alt="Screenshot 2020-11-18 at 7 12 38 PM" src="https://user-images.githubusercontent.com/232896/99616408-0e04d200-29d2-11eb-8e2e-3a9205566dac.png">

1) Themes shouldn't be saved until the dialog is dismissed or you hit return, solving the issue
2) Settings Sync should have a button to resume syncing or try again, or at least tell you how and when you can resume

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (10.48GB free)|
|Process Argv|--crash-reporter-id f4ee93fd-4d43-48b8-b803-42688ee2a82e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (91)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.4.0
spectrum-vscode-icons|ale|0.1.0
angitignored|AnA|1.2.18
atlascode|atl|2.8.4
coffeescript-jsdoc|bam|0.2.2
theme-verdandi|be5|2.0.1
vscode-custom-css|be5|4.0.0
touch-bar-display|bla|1.4.1
better-toml|bun|0.3.2
nebula-theme|Chi|1.3.2
path-intellisense|chr|2.3.0
regex|chr|0.2.0
gitignore|cod|0.6.0
disableligatures|Coe|0.0.10
log-and-return|dar|0.0.1
vscode-markdownlint|Dav|0.37.2
vscode-coffeescript-snippets|din|0.0.2
xml|Dot|2.5.1
vscode-coffeescript-preview|dre|1.0.1
gitlens|eam|11.0.1
vscode-coffeescript-eval|ehe|1.0.0
vscode-great-icons|emm|2.1.61
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.7.2
font-switcher|eva|3.1.0
filter-line|eve|2.0.1
vscode-open-in-finder|fab|1.1.8
php-intellisense|fel|2.3.14
file-icons|fil|1.0.27
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.21.0
go|gol|0.18.1
terraform|has|2.3.0
toml-formatter|ice|0.0.3
jenkinsfile-support|ivo|1.1.0
search-editor-apply-changes|jak|0.1.1
vscode-codeowners|jas|1.1.1
vscode-peacock|joh|3.8.0
vscode-colorize|kam|0.8.17
voodoo|lia|0.10.0
coffeelinter|lky|1.4.0
vscode-smart-column-indenter|lmc|0.0.13
fish-ide|lun|0.4.0
bash-ide-vscode|mad|1.11.0
code-groovy|mar|0.1.2
rainbow-csv|mec|1.7.1
vscode-easy-coffeescript|mkl|1.2.0
vscode-docker|ms-|1.8.0
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
atom-keybindings|ms-|3.0.9
mono-debug|ms-|0.16.2
vsliveshare|ms-|1.0.3206
back-n-forth|nic|3.1.0
vscode-groovy-lint|Nic|1.3.0
vscode-yaml-sort|Pas|2.7.2
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.0
coffeescript-formatter|prp|1.0.1
java|red|0.70.0
vscode-yaml|red|0.12.0
synthwave-vscode|Rob|0.1.8
fish-vscode|sky|0.2.1
vscode-iced-coffeescript-preview|sta|1.0.6
code-spell-checker|str|1.9.4
tabnine-vscode|Tab|3.1.11
ayu|tea|0.20.1
shellcheck|tim|0.12.1
sort-lines|Tyr|1.9.0
sensitive-replace|vil|0.1.1
learn-vim|vin|0.0.23
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.14.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vim|vsc|1.17.1
CoffeeScript-extension-pack|wal|0.0.1
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
FilterText|yhi|0.0.15
coffeescript-support|yor|0.3.0
markdown-all-in-one|yzh|3.4.0
file-size|zh9|1.0.0
html-css-class-completion|Zig|1.19.0

(80 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/110817
https://github.com/microsoft/vscode/issues/91286
