### ISSUE TITLE
Pinned tabs on dragged tabs

### ISSUE THREAD

**Issue by Brixbrax** [microsoft/vscode#110935]
If I drag a normal tab to the place of a pinned tab, the dragged tab gets pinned too (while the original tab keeps its pinned state but moves right).

**Comment by bpasero** [comment]
yeah, works as designed.

**Comment by Brixbrax** [comment]
Thank you for your answer. 
To be more precise e.g. I have 4 unpinned, normal tabs:
tab1, tab2, tab3, tab4
I set tab1 pinned. Great. But if I drag tab2 to the first place, tab2 changes to pinned, too. Tab1 moves right and keeps the pinned state, so I have two pinned tabs now. Then I drag tab3 to the first place as well as tab4. I will have four pinned tabs finally but I want only one to be pinned.

**Comment by bpasero** [comment]
Yeah I understand, but that is intentional. I think the only way to fix this is to allow for dropping the tab precisely before or after the pinned tab. 

/duplicate https://github.com/microsoft/vscode/issues/8544
