### ISSUE TITLE
Very fast touch scrolling

### ISSUE THREAD

**Issue by SilantevDenis** [microsoft/vscode#110929]
Very fast scrolling (vertical and horizontal) in any window when using the touchpad (mouse wheel is fine). Deleted all data, reinstalled the vscode, did not help.
https://drive.google.com/file/d/1BobyakWu7CQ9mT_joc7ofyL-8nxv0xGS/view?usp=sharing

- VSCode Version: all version (1.51, 1.48, 1.42, insiders, user and system)
- OS Version: windows 10 x64
- PC: L340-15IRH Gaming Laptop (ideapad) - Type 81LK

Steps to Reproduce:
1. Scroll any window

Does this issue occur when all extensions are disabled?: Yes

**Comment by SilantevDenis** [comment]
this does not work

**Comment by alexdima** [comment]
@SilantevDenis We have a setting called `editor.mouseWheelScrollSensitivity`, can you try to tweak that?

**Comment by SilantevDenis** [comment]
> @SilantevDenis We have a setting called `editor.mouseWheelScrollSensitivity`, can you try to tweak that?

I set 0.01. That helped. Thank you
