### ISSUE TITLE
Ability to reposition the quick access icons in the bottom bar.

### ISSUE THREAD

**Issue by sujit510** [microsoft/vscode#110947]
I recently installed Bitbucket and JIRA plugins in my VSCode, it added quick access icons for them in the bottom of the editor as highlighted in red rectangle below:

![image_2020_11_19T13_23_36_403Z](https://user-images.githubusercontent.com/6594612/99672063-e593db00-2a98-11eb-9774-3314c72a6dca.png)

This has shifted the shortcut to open terminal to the right (highlighted in yellow rectangle) of those newly added JIRA/Bitbucket shortcuts. Since I was used to look for the shortcut of terminal in the left, it sometimes irritates to find it.
Can those shortcuts be made draggable or any other means to reposition?

**Comment by gjsjohnmurray** [comment]
AFAIK there's currently no ability for end-user reordering of these. The extensions you added must be specifying the `priority` of their `StatusBarItem`(s) as greater than 50, which is the fixed value used by the panel you marked in yellow on your screenshot:

https://github.com/microsoft/vscode/blob/83246704d4a035f667902ed2d5b0f1d954ad9a88/src/vs/workbench/contrib/markers/browser/markers.contribution.ts#L376

I suggest you contact the extension author(s) and ask for that value to be user-configurable.
