### ISSUE TITLE
Bad user experience while searching

### ISSUE THREAD

**Issue by ChrisEelmaa** [microsoft/vscode#110944]
The new feature where you can remove searched result from the code (by pressing x) is very annoying, I keep clicking on it accidentally from time to time, and it is creating havoc on my code base, need to be really careful before deploying/commiting anything, as well check that nothing that was added has not been removed.

Hopefully this will get reverted or a way to get rid of it with some setting.

https://imgur.com/a/wWdNOaB

**Comment by gjsjohnmurray** [comment]
Would `"search.actionsPosition": "right"` help avoid the accidents?

**Comment by roblourens** [comment]
Not a new feature, but I did just change the default of this setting, you can set that yourself to try it out as well. That should help with this confusion that comes up fairly often.

**Comment by roblourens** [comment]
By the way, that button does not change or delete anything from your code, only the result list.

**Comment by ChrisEelmaa** [comment]
I've changed the setting, hopefully will be better now. Actually, its not the "pressing x" functionality, its the "pressing replace" button which causes the issue (code gets randomly replaced with emptiness) I was having
