### ISSUE TITLE
Lost All My Work

### ISSUE THREAD

**Issue by issa24** [microsoft/vscode#110940]
We have written the needed 
Issue Type: <b>Bug</b>

Apparently, Jupyter Notebook on VS Code is not a reliable tool to do my job. I lost my work even after I set my file to autosave and I'm not happy with this tool. Please fix this issue. This is not the first time this happened to me. Take care. Thanks!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.70GB free)|
|Process Argv|--crash-reporter-id aef9002b-5eac-4704-aa5e-dd917c7a00c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-class-suggestions|And|1.0.7
vscode-jupyter-qtconsole|and|1.0.0
vscode-browser-preview|auc|0.6.7
vscode-database|baj|2.2.3
vscode-django|bat|1.0.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
my-nbpreviewer|col|1.2.2
python-extension-pack|don|1.6.0
vscode-firefox-debug|fir|2.9.1
gc-excelviewer|Gra|3.0.40
live-html-previewer|hdg|0.3.0
r|Iku|1.5.2
nbpreviewer|jit|1.2.2
vsc-python-indent|Kev|1.12.0
kite|kit|0.134.0
MagicPython|mag|1.1.0
auto-save|mcr|1.0.3
vscode-docker|ms-|1.8.0
gather|ms-|2020.11.0
python|ms-|2020.11.367453362
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
cpptools|ms-|1.1.2
powershell|ms-|2020.6.0
vscode-markdown-notebook|ms-|0.0.13
vsliveshare|ms-|1.0.3206
sqltools|mtx|0.23.0
live-server-preview|neg|0.1.4
neuron-IPE|neu|1.0.4
VSNotebooks|pav|1.4.4
regexp-saver|phi|1.0.0
LiveServer|rit|5.6.1
datapack|rya|0.0.4
jupyter-notebook-vscode|sam|0.0.2
html5-boilerplate|sid|1.1.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
html-snippets|wge|0.1.5
jinja|who|0.0.8
local-history|xyz|1.8.1
tabkeeper|Y0K|0.0.3
commandlist|yam|1.0.3
html-css-class-completion|Zig|1.19.0

(31 theme extensions excluded)

</details>
data into your clipboard because it was too large to send. Please paste.

**Comment by xsoheilalizadeh** [comment]
You need to file this issue at  https://github.com/Microsoft/vscode-jupyter.
