### ISSUE TITLE
IntelliSense not working with @typedef

### ISSUE THREAD

**Issue by tnorlund** [microsoft/vscode#110980]
I'd like to use IntelliSense to use @typedef or be able to show given parameters.

![IntelliSense](https://user-images.githubusercontent.com/26452518/99723111-9634b700-2a66-11eb-9e4b-1cfe89c85157.png)

- VSCode Version: 1.51.1
- OS Version: Mac OS 11.0.1

```js
/**
 * @typedef {Object} ParsedUser
 * @param {String} name The name of the user.
 * @param {String} email The email of the user.
 * @param {Number|String} userNumber The number of the user.
 */

/**
 * Gets the useful user data from the current Cognito user session.
 * @param {Object} CognitoUserSession The current cognito user session.
 * @returns {ParsedUser} The parsed user data.
 */
export function parseUser( CognitoUserSession ) {
  const { name, email, ...restOfUser } = CognitoUserSession.idToken.payload
  return {
    name: name, email: email, userNumber: restOfUser[`custom:UserNumber`]
  }
}
```

**Comment by mjbvz** [comment]
What is the issue?

**Comment by tnorlund** [comment]
The issue is that the returns from Intellisense does not show the information in the type definition.

**Comment by mjbvz** [comment]
It has the correct type so this is the currently the designed behavior .

Expanding typedefs like you want is tracked by https://github.com/microsoft/TypeScript/issues/25784
