### ISSUE TITLE
VSCode instantly crashes when attempting to clone a git repo.

### ISSUE THREAD

**Issue by royalPanic** [microsoft/vscode#110996]
Issue Type: <b>Bug</b>

**Reproduction Steps:**
1. Install the VSC Insiders Edition `.deb`.
2. Use command palette to attempt to clone git repo.
3. Paste repo's  `.git` URL in the command palette box.

**Expected Result:**
VSC opens my file browser and asks me where I'd like to clone the git repo, and then clones it there.

**Actual Result:**
VSC either instantly crashes when I press enter on the git clone command, or it hands for a few seconds *and then* crashes.

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:43:25.118Z)
OS version: Linux x64 5.8.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (8 x 2182)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|5.79GB (2.77GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 896d10a6-52ec-4c73-8baa-e98e4dd83546|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
remote-ssh-edit|ms-|0.56.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30222199
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30226749
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Native-Crash-Issues for how to provide extra information.
