### ISSUE TITLE
scrolling feels sticky after upgrade mac to  Big Sur

### ISSUE THREAD

**Issue by jihgao** [microsoft/vscode#110997]
- VSCode Version: 1.51.1
- OS Version: macOS Big Sur 11.0.1

Steps to Reproduce:

1. Open vscode
2.try to use mouse wheel scroll quickly serval times

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@jihgao Do you use `editor.smoothScrolling`? Does scrolling feel sticky when scrolling with the trackpad or only with the mouse wheel?

**Comment by monisnap-julien** [comment]
Hello ! I have the same issue. It often happens when there is a long message printed (for example when there is an error stack trace).

I'm running on MacOS Catalina 10.15.7

**Comment by alexdima** [comment]
@monisnap-julien Does it help to run with `code --disable-gpu`? I also don't quite think you suffer from the same issue, since the OP complains about the slowness appearing after upgrading to Big Sur.

**Comment by jihgao** [comment]
> smoothScrolling

Thanks, the problem has gone now, it seems to be the new MAC OS's problem as it happened with browser as well.
