### ISSUE TITLE
Fall back to read contributes.configuration?

### ISSUE THREAD

**Issue by formulahendry** [Microsoft/vscode#11097]
- VSCode Version: 1.4
- OS Version: Windows 10

I have an [extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner) which will read the contributes.configuration called "code-runner.executorMap". (GitHub repo: https://github.com/formulahendry/vscode-code-runner)
By default, it is like below:
```json
"code-runner.executorMap": {
    "javascript": "node",
    "php": "php",
    "python": "python",
    "perl": "perl",
    "ruby": "ruby",
    "go": "go run",
    "lua": "lua",
    "groovy": "groovy",
    "powershell": "powershell -ExecutionPolicy ByPass -File",
    "bat": "",
    "shellscript": "bash",
    "fsharp": "fsi",
    "csharp": "scriptcs",
    "vbscript": "cscript //Nologo"
}
```
After I remove the `"javascript": "node"` in User Settings or Workspace Setting, the extension could still read the `"javascript": "node"`. I am not sure if I read config incorrectly?
Code snippet is like below:
```javascript
this._config = vscode.workspace.getConfiguration('code-runner');
let executorMap = this._config.get<any>('executorMap');
let executor = executorMap['javascript'];
```
Actual:
The value of 'executor' is still 'node'
Expect:
The value of 'executor' should be 'undefined'

**Comment by jrieken** [comment]
`getConfiguration` is a mirror of the equivalent method in the service. unsure why the value is still there but my guess is that it's a default value

**Comment by bpasero** [comment]
Yup thats it: https://github.com/formulahendry/vscode-code-runner/blob/master/package.json#L80

**Comment by formulahendry** [comment]
I could not understand the design and behavior. 
If I have a default config as below:
```json
"graph": {
    "type": "circle",
    "radius": "10"
}
``` 
Then I want to overwrite in User Settings or Workspace Setting as below:
```json
"graph": {
    "type": "rectangle",
    "height": "6",
    "width": "8"
}
``` 
So what the result if I this._config.get<any>('graph') ?
The result is as below?:
```json
"graph": {
    "type": "rectangle",
    "height": "6",
    "width": "8",
    "radius": "10"
}
``` 
But how could a rectangle have radius?

**Comment by bpasero** [comment]
@formulahendry here is how settings work:
* take the default value configured in package.json
* take the value configured in settings.json (User Settings) and add each key to the default value from step 1, overwriting any existing value
* take the value configured in settings.json (Workspace Settings) and add each key to the User Settings value from step 2, overwriting any existing value

Hope that helps.

**Comment by formulahendry** [comment]
Thanks @bpasero for the detailed description of the implementation, though I still think it better to overwrite the whole object not just the key-value pairs. Anyway, it is the design issue. If possible, it would be better to clarify this clearly in documentation to avoid confusion. :smile:

**Comment by bpasero** [comment]
@formulahendry I see what you mean though I do not think we can change this behaviour to not break people expecting it to work as it is now.
