### ISSUE TITLE
Disable launching integrated Terminal

### ISSUE THREAD

**Issue by pradeepbansal00** [microsoft/vscode#110921]
Issue Type: <b>Bug</b>

For God sake tell me the setting to disable launching Terminal, when I open any folder. This is highly irritating.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by meganrogge** [comment]
Can you pls provide me with steps to reproduce this? Opening folders for me does not launch the terminal unless I select `Open in Integrated Terminal`
