### ISSUE TITLE
Notebook navigation flow

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#110962]
Extracted from #109549

> @kieferrm: I repeatedly tried to use ArrowDown to go from a cell editor to the output below

@isidorn has a similar ask for using Arrow keys to navigate through input/output. Our current flow is partially inspired by Jupyter's mode system, in which you can use Edit mode to navigate/edit cell inputs and Command mode to manipulate cells and execution.

Our current flow is

* Enter/Escape to focus the cell editor or the cell container (list view)
* When the focus is on the cell editor
  * Arrow key will move to previous/next cell editor (if it's markdown cell, it will then switch to editing mode)
* When the focus in on the cell container / list view
  * Arrow key will move to previous/next cell container
* To navigate to outputs
  * you might press Tab multiple times (alt+tab in the editor otherwise it will only insert a `\t`)
  * or use `cmd+ctrl+down` (Focus in Active Output), (I just figured out this today)

We may want to see how to improve the default experience and also allow customization.

**Comment by rebornix** [comment]
We currently have enough info about where the cursor is so we can add keybindings like below to support arrow down to outputs directly

```
  {
    "key": "down",
    "command": "notebook.cell.focusInOutput",
    "when": "notebookCellHasOutputs && notebookEditorFocused && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top'"
  },
```

**Comment by roblourens** [comment]
I'm not a fan of this, I like the way it works currently, but I think that users can configure their own keybindings if they want.
