### ISSUE TITLE
Incomplete Git warning when dealing with unmerged files

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#110904]
Version: 1.52.0-insider (user setup)
Commit: 78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2
Date: 2020-11-18T12:38:39.842Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Go to source control viewlet, select "Pull, Push" -> "Pull from..."
2. Select a remote end point and then a branch
3. Get incomplete message text

![image](https://user-images.githubusercontent.com/25310137/99611282-3a1b5580-29c8-11eb-8950-cf4f6846eeec.png)

When I "Open Git Log," I can see the complete warning message here (it seems to have just gotten cut off in the pop up). When I scroll further, I can see the true error:

![image](https://user-images.githubusercontent.com/25310137/99611774-24f2f680-29c9-11eb-910c-eddfa80cbf03.png)

Should we print the error rather than the warning to the user? Or if we'd like to print the warning, we'd probably want it to be complete.

In case it matters, I am connected to a Codespace via the GitHub Codespaces extension.

**Comment by joaomoreno** [comment]
This is the classic problem of parsing raw git output. @eamodio we can write a `/^error:/.match(stderr)` heuristic for this specific operation and try to distill the message further, what do you think>

**Comment by eamodio** [comment]
Yeah, makes sense to me -- Handing git errors via message parsing is always tricky, as messages have/do change between git versions (so it can make it harder to pin things down).
