### ISSUE TITLE
macOS Big Sur: once in a while I see a "Shipit" crash

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#110937]
Issue Type: <b>Bug</b>

Every second day I see a "Shipit" crash on macOS Big Sur:

![2020-11-19_11-54-05](https://user-images.githubusercontent.com/1898161/99657391-641f5700-2a5e-11eb-8df9-b44ebce1273b.png)

Here is the full dump: 
[shipit_crash.txt](https://github.com/microsoft/vscode/files/5566275/shipit_crash.txt)

---

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:38:14.978Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 785023c0-aeb7-4708-b29f-2c6aa9e59a8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
tsl-problem-matcher|eam|0.3.1
codespaces|Git|0.1.0
vscode-pull-request-github|Git|0.21.0
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.150.0
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.3.0
vscode-github-issue-notebooks|ms-|0.0.58
vscode-typescript-tslint-plugin|ms-|1.2.3
gitblame|wad|6.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by kirbybirby** [comment]
i had this same issue today suddenly for the first time. any insight is appreciated

**Comment by deepak1556** [comment]
This should be fixed with latest insiders that carries electron 11 update. Please check with it.

**Comment by weinand** [comment]
Yes, with the electron 11 update I'm no longer seeing this.
