### ISSUE TITLE
VSCode no more show selected characters length & column number of the cursor in status bar(ProgressLocation.Window)

### ISSUE THREAD

**Issue by pmahend1** [microsoft/vscode#110955]
It used to show number of selected characters and also the cursor position in the column in the status bar 
I think it changed in last (1.51.1) or last but one release(1.51.0) , 

- VSCode Version: 1.51.1
- OS Version: Windows 10
- Last Good version : 1.51.0 or below
```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
Steps to Reproduce:

1. Create a file
2. Select text 
3. Move cursor to different places
![image](https://user-images.githubusercontent.com/21352870/99691537-56b29e80-2a57-11eb-9116-b8c2a7ae4846.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you see it in list and checked if you trigger context menu on Status Bar?
![image](https://user-images.githubusercontent.com/1312662/99700419-d7938980-2a9b-11eb-975c-2bbd888e0131.png)

**Comment by pmahend1** [comment]
@IllusionMH Dint know those options. It was turned off for some reason.
Fixed now.
