### ISSUE TITLE
Provide option to hide "Discard Changes" (and consider making it default?)

### ISSUE THREAD

**Issue by jspiro** [microsoft/vscode#110914]
Issue Type: <b>Feature Request</b>

IMO: This button is way too potentially dangerous, easy to click, and the icon is way too subtle (it looks like refresh)–I feel it should be in the context menu only by default.

<img width="112" alt="Screenshot 2020-11-18 at 8 44 29 PM" src="https://user-images.githubusercontent.com/232896/99623136-48756b80-29e0-11eb-84cc-38ab7fe0aaa3.png">

Personal experience: I've lost changes before thanks to this UI and it really should not be prominently sandwiched between two commonly used buttons. I swore off the VSCode Git UI as a result and have been suggesting to less-experienced coworkers to also stay away.  We use gitX for UI, and otherwise CLI.

This one change would make it much safer to return to using.

I'm an advanced user of git, I know the internals, and I know how to avoid losing things. I saw another bug indicating there may not have been a warning once? That may be when I lost it–but I still feel this is not the right place to put this button.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

**Comment by eamodio** [comment]
@jspiro I'm unclear as to how you would lose changes here -- as the discard button always prompts you to confirm. Given the confirmation, I feel that is is quite safe as it is today.

**Comment by jspiro** [comment]
It would have been nice to maybe give me a moment to respond before closing my request?

As-designed doesn't mean designed well, and certainly not for everyone. I am requesting an option to hide this UI since no extension can do it. Every month VSCode adds a ton of new hidden flags and options to customize things, why is UI that can delete work unintentionally exempt from this?

Haven't you ever misclicked through a dialog and said "oh ****!" to yourself afterward? A dialog is not sufficient. That's why GitHub, for instance, requires you to retype the repo name or `delete` when you take certain actions.

**Comment by eamodio** [comment]
While I appreciate where you are coming from, every setting comes with a cost -- and a setting like what you are suggesting isn't something that we would turn on by default. As it would break the experience for current users, and IMO is not warranted. So, since it wouldn't be on by default, it would only help the (imo) tiny subset of users who would find and enable this setting. And therefore not something, we would likely implement.

**Comment by jspiro** [comment]
I read all dozens of pages of the release notes *every* month and there are TONS of new settings that control microscopic things that are not the default. October was the first month I didn't find a single thing useful to me–that's fine, probably useful to someone else, right?

I agree there is a cost, but a) there is at _least_ a "tiny subset" of users of which I am a member who would benefit from it, and b) it's only toggling the visibility of a button using CSS. And I guess you'd have to also mention it in the release notes.

I didn't say it had to be the default, I _suggested_ it be considered. VSCode does not only add new settings if they are going to be the default. New settings are added just to make it comfortable and accessible for everyone. I can go through the release notes and find examples, but you know it's true.

Please think of the tiny subset of users. We're your customers too.

**Comment by gjsjohnmurray** [comment]
There was a recent change that made the warning dialogue stronger

https://github.com/microsoft/vscode/issues/108348#issuecomment-706212506

@jspiro are you seeing that?
