### ISSUE TITLE
Subdirectory Code Search

### ISSUE THREAD

**Issue by andrew-zaydak** [microsoft/vscode#110970]
Issue Type: <b>Feature Request</b>

I use the seach feature all the time. It seems that it will only search in 1) the base directory of the project and 2) any other files opened in the editor.  It will not search subdirectories. for example, if i have a project called Test and it is saved in ~/Test and have most of the source code in ~/Test/src and open Code in ~/Test it will not search any files in ~/Test/src unless I already have all of them open in the editor. Not sure if this is a bug report or a feature request.
Thanks
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/wiki/Search-Issues
