### ISSUE TITLE
Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.

### ISSUE THREAD

**Issue by tongyuchan** [microsoft/vscode#110926]
Issue Type: **Bug**

Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue.

- VSCode Version:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- OS Version: macOS Catalina 10.15.6

Steps to Reproduce:

1.  my typescript extension project is similar to [vscode-eslint](https://github.com/Microsoft/vscode-eslint) 
2. Then press F5 to run Extension Development Host, but this error occurred:
![image](https://user-images.githubusercontent.com/26242440/99641731-a4de9680-2a85-11eb-85c9-722cddea7b13.png)

run code --verbose
![image](https://user-images.githubusercontent.com/26242440/99643964-4ebf2280-2a88-11eb-880d-6343e5ca7a6f.png)

Developer Tools & Console
![image](https://user-images.githubusercontent.com/26242440/99642281-4960d880-2a86-11eb-9b99-95445acaf605.png)

I found lots of issues(like #81471, #72607), but it seems not solved...

**Comment by connor4312** [comment]
It looks like we couldn't connect to the port the extension host is reported to be listening on. Do you have any firewall, antivirus, or other programs/policy that could prevent connections on localhost?

**Comment by tongyuchan** [comment]
> It looks like we couldn't connect to the port the extension host is reported to be listening on. Do you have any firewall, antivirus, or other programs/policy that could prevent connections on localhost?
Thank you for your reply.

I haven’t seen any firewall, antivirus or other programs/policy that could prevent connection on localhost, actually it’s been running properly before I update the version of vscode. I’m very confused since it can run quite smoothly on my colleague’s laptop, under the same system environment (same version of Macbook system and vscode and firewall installed)
