### ISSUE TITLE
Extract the colors defined by editor as vs code custom settings in themes

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11095]
Currently editor has feature contributions those define some colors which does not go well with different themes. Extract those colors as vs code custom settings (non standard) in TM themes. This will allow theme writers to provide an appropriate matching color for these features.

### Range highlight (Find, Go to line, Go to symbol)
- [x] rangeHighlight

### Find / Replace
- [x] findMatch
- [x] currentFindMatch

### Selection
- [x] selectionHighlight

### Words
- [x] wordHighlight
- [x] wordHighlightStrong

**Comment by alexandrudima** [comment]
@sandy081 `findSelection` and `findSelectionHighlight` look funny, maybe better names would be `findMatchHighlight`, `currentFindMatchHighlight` ?
