### ISSUE TITLE
Add explorer enableSwitchToEditorDragAndDrop setting

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#110954]
I often create a copy of a file by drag and drop in explorer to preserve some code that I do not want to lose, but also do not want to commit. When the drag and drop is complete, the copied file is enabled in editor. The enabled file should not switch to the copied version. I am proposing an additional setting to Drag And Drop, as described below.

Explorer: Enable Drag And Drop
Controls whether the explorer should allow to move files and folders via drag and drop.

> "explorer.enableDragAndDrop": true

> **Additional setting for Drag And Drop**

> Explorer: Enable Drag And Drop Switch To Editor
> Controls whether the drag and drop operation should allow to switch to file in editor.
> 
> "explorer.enableSwitchToEditorDragAndDrop": true

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
