### ISSUE TITLE
request for new system variable of ${worskpaceRootFolderName}

### ISSUE THREAD

**Issue by visualperception** [Microsoft/vscode#11094]
- VSCode Version: 1.4.0
- OS Version: Windows 7

currently there is the system variable ${workspaceRoot}. This returns the full path to the workspace root so if your open folder is:

c:\folder1\folder2 then that is what ${workspaceRoot} returns.

that is fine if you want the full path returned but if you are developing a website and want to use tasks to intiate running the open file in a browser on local webserver, then you don't want the full path returned. You want the website root foldername returned so in above example you want just the foldername returned which would be "folder2". This has the benefit of greatly simplifying building a url to run in browser without resorting to coding.
For example you could build a url as 

${workspaceRootFolderName}/${relativeFile}

and pass that to your web browser with a task or key definition.

currently you would need to strip the foldername from ${workspaceRoot} and you can't do that in tasks.json file.

So please, please could we have an additional system variable with just the workspaceRoot folder name in it ( NOT the full path to it.)

I'm suggesting calling it ${workspaceRootFolderName}

(unless there is already some system variable I don't know about which could be used without needing to edit it).

Thanks

**Comment by dbaeumer** [comment]
@visualperception a good opportunity for a PR.

**Comment by visualperception** [comment]
Thanks muchly.
And I would its just the folder name without any slashes. Slashes are easy to add in arguments but not easy to take out of variables in json

**Comment by visualperception** [comment]
just installed the insider daily build and it seems the new system varaible ${workspaceRootFolderName} is there and is working exactly as I had hoped. I'll check again when next release comes out.
So thanks all for implementing this.

**Comment by dbaeumer** [comment]
Great. Closing as verified.

**Comment by AntonKrug** [comment]
I apologise for bit off-topic comment, but I'm wondering if there is a list of all the implemented system variables?

**Comment by dbaeumer** [comment]
https://code.visualstudio.com/docs/editor/tasks#_variable-substitution

**Comment by AntonKrug** [comment]
Thank you very much.
