### ISSUE TITLE
Emmet Expand Abbreviation should support expanding selection only

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#110901]
Version: 1.52.0-insider (user setup)
Commit: 78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2
Date: 2020-11-18T12:38:39.842Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

0. Have `emmet.triggerExpansionOnTab` set to true
1. Open an HTML file in VS Code, type `testdiv+span`
2. Select `div+span` and explicitly run the command `Emmet: Expand Abbreviation`
3. The abbreviation doesn't expand, instead, the selection is cleared and a tab is input instead

Does this issue occur when all extensions are disabled?: N/A

Also verified that this issue occurs on stable.
If the user merely presses tab, then the behaviour is understandable.
The confusing part is that the user is explicitly running the command, and a tab is inserted.

**Comment by t7yang** [comment]
I found another issue, when click [tab] on snippet tabstop wouldn't move to next tabstop instead trigger emmet expand (if `emmet.triggerExpansionOnTab` on).

Is this same problem?

**Comment by rzhao271** [comment]
@t7yang does that issue still occur for you on the latest Insiders? I'm unable to reproduce it. If it does, can you paste an example abbreviation for me to use?

**Comment by t7yang** [comment]
@rzhao271 No, fixed now.

**Comment by abhiajju** [comment]
@rzhao271 I am unable to repro this issue. I tried to do an explicit Emmet: expand abbreviation and it worked fine for me. Can you please confirm ?
I did the exact steps as u have mentioned in the bug description

**Comment by abhiajju** [comment]
Oops!! I missed the first step in the repro - Have `emmet.triggerExpansionOnTab` set to true.
I can repro it now and what I also oberved is when this setting is false( which is by default) and if we explicitly run the command `Emmet: Expand Abbreviation`, the expansion works fine. 
Looking into the issue

**Comment by abhiajju** [comment]
I found this piece of code in `abbreviationAction.ts`, inside the function `expandEmmetAbbreviation()` - 
```
// When tabbed on a non empty selection, do not treat it as an emmet abbreviation, and fallback to tab instead
	if (vscode.workspace.getConfiguration('emmet')['triggerExpansionOnTab'] === true && editor.selections.find(x => !x.isEmpty)) {
		return fallbackTab();
	}
```
Seems like when the setting `triggerExpansionOnTab `is turned **On**, and we have a non-empty selection, we fallback to **default Tab behavior**

@rzhao271 can you please help me understand why we have this check in place, as I am uanble to comprehend any scenario that needs this.
I also verified that if we remove this code piece, we get the right behavior

**Comment by rzhao271** [comment]
Thanks for the update!
It seems Ramya added in that exact part of the code over 3 years ago but didn't link it to an issue: https://github.com/microsoft/vscode/commit/78809b70fb56f60f46561b01528ba5787f3091f6
I'll change this issue to a Backlog Candidate feature. That way, we can see whether the community wants to enable Emmet tab expansions on selections.

**Comment by abhiajju** [comment]
Thanks @rzhao271 . My only concern here is that for cases where we have `emmet.triggerExpansionOnTab === false` (which is by default), we can still **expand the selection by explicitly running the command** `Emmet: Expand Abbreviation`.
So , I don't see much utility of the above mentioned check. 
Please let me know if I am missing something here
