### ISSUE TITLE
useState in JavaScript is undefined.

### ISSUE THREAD

**Issue by Jeskalana** [microsoft/vscode#110960]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I tried to make a webpage in React using the The Studio and it returned "useState undefined from my code," but not on my friend's computer and we used the exact same code and set up.  So what does this mean?  Do you know how I can fix it?
Thanks!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.12GB free)|
|Process Argv|--crash-reporter-id b82a7703-3cb6-43eb-bdb1-6f679a147066|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
xd|ado|1.0.7
code-gnu-global|aus|0.2.2
xml|Dot|2.5.1
vscode-html-css|ecm|0.2.3
php-intellisense|fel|2.3.14
xd-theme|jef|0.1.150
csharp|ms-|1.23.6
vscode-edge-devtools|ms-|1.1.1
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
cpptools|ms-|1.1.2
java|red|0.71.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
html-css-class-completion|Zig|1.19.0

</details>

**Comment by roblourens** [comment]
Sorry but this sounds like an issue with your app, not with vscode
