### ISSUE TITLE
The '$msCompile' problem matcher does not match Visual Studio Clang front end

### ISSUE THREAD

**Issue by emmenlau** [microsoft/vscode#110946]
Issue Type: <b>Bug</b>

Compile a project with Visual Studio clang-cl (ClangCl) front end. The problem matcher does not match any of the errors.

Example for an error generated by ClangCl:
```
C:\Source\thrift\lib\cpp\src\thrift\transport\SocketCommon.cpp(65,50): error: member access into incomplete type 'apache::thrift::transport::sockaddr_un'
    if (addr_len > sizeof(((sockaddr_un*)nullptr)->sun_path)) {
```

Example for a warning generated by ClangCl:
```
clang-cl: warning: argument unused during compilation: '/MP' [-Wunused-command-line-argument]
C:\Source\thrift\compiler\cpp\src\thrift\main.cc(547,15): warning: 'strdup' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details. [-Wdeprecated-declarations]
    doctext = strdup(docstring.c_str());
              ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\string.h(531,20): note: 'strdup' has been explicitly marked deprecated here
    _Check_return_ _CRT_NONSTDC_DEPRECATE(_strdup)
                   ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt.h(414,50): note: expanded from macro '_CRT_NONSTDC_DEPRECATE'
        #define _CRT_NONSTDC_DEPRECATE(_NewName) _CRT_DEPRECATE_TEXT(             \
                                                 ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\vcruntime.h(306,47): note: expanded from macro '_CRT_DEPRECATE_TEXT'
#define _CRT_DEPRECATE_TEXT(_Text) __declspec(deprecated(_Text))
                                              ^
1 warning generated.
```

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (24.17GB free)|
|Process Argv|thrift.code-workspace --crash-reporter-id de57cb80-6fb1-4bd0-948c-e5e12ce76375|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.0.1
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.21.0
vscode-test-explorer|hbe|2.19.3
latex-workshop|Jam|8.14.0
autoconf|mae|0.1.0
vscode-catch2-test-adapter|mat|3.6.5
vscode-docker|ms-|1.8.0
csharp|ms-|1.23.6
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.148.1
cpptools|ms-|1.1.2
bash-debug|rog|0.3.9
rewrap|stk|1.13.0
code-spell-checker|str|1.9.4
shellcheck|tim|0.12.1
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by alexr00** [comment]
You'll need to use a different problem matcher for that. Perhaps there is an extension which provides one?

**Comment by emmenlau** [comment]
> You'll need to use a different problem matcher for that. Perhaps there is an extension which provides one?

Sadly, there is currently no extension that provides the a matcher for that.

I understand that VSCode can not necessarily provide matchers for all possible compilers. But ClangCl is now a standard front end that is shipped directly with Visual Studio. Would this not qualify as being part of the MSVC matcher?
