### ISSUE TITLE
Extensions list gone

### ISSUE THREAD

**Issue by Rukato** [microsoft/vscode#110956]
Issue Type: <b>Bug</b>

After the last two update the extension shelve is empty and there's no way to manage your extensions

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:38:14.978Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv|-psn_0_340051 --crash-reporter-id aee79c6a-72ab-413c-827e-4cc64ca28553|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (68)</summary>

Extension|Author (truncated)|Version
---|---|---
cypress-snippets|and|1.2.0
scratchpads|bue|0.0.7
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.1
vscode-spring-boot|ecm|0.0.10
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.1
docker-explorer|for|0.1.7
kotlin|fwc|0.2.18
vscode-lombok|Gab|1.0.1
vscode-test-explorer|hbe|2.19.3
vscode-test-explorer-liveshare|hbe|1.0.5
search-node-modules|jas|1.3.0
vscode-peacock|joh|3.8.0
vscode-jest-test-adapter|kav|0.7.4
node-module-intellisense|lei|1.5.0
code-groovy|mar|0.1.2
Kotlin|mat|1.7.1
git-graph|mhu|1.27.0
vscode-docker|ms-|1.8.0
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-containers|ms-|0.150.0
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
vscode-remote-extensionpack|ms-|0.20.0
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
gradle-language|nac|0.2.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.23.0
vscode-manifest-yaml|Piv|1.23.0
vscode-spring-boot|Piv|1.23.0
java|red|0.71.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
git-mob|Ric|1.10.1
vscode-gradle|ric|3.5.2
vscode-gradle-extension-pack|ric|0.0.2
vscode-checkstyle|she|1.3.3
sonarlint-vscode|Son|1.18.0
vscodeintellicode|Vis|1.2.10
liquibase|voi|0.1.1
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.6.1
vscode-icons|vsc|11.0.0
gitblame|wad|6.0.0
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by jtsom** [comment]
Yep. Reported this yesterday - https://github.com/microsoft/vscode/issues/110870 - waiting for someone to comment or acknowledge .

**Comment by sandy081** [comment]
Please provide if there are any errors in the following logs

- Help -> Toggle Developer Tools -> Console
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

**Comment by Rukato** [comment]
Help -> Toggle Developer Tools -> Console
<img width="546" alt="Screen Shot 2020-11-19 at 2 01 44 PM" src="https://user-images.githubusercontent.com/20954967/99711663-0f84d780-2a70-11eb-951f-bf257b20d70f.png">

View -> Command Pallette... -> Toggle Shared Process -> Console
<img width="545" alt="Screen Shot 2020-11-19 at 2 02 20 PM" src="https://user-images.githubusercontent.com/20954967/99711680-13b0f500-2a70-11eb-98f6-4f935c774113.png">

View -> Open View… -> Log (Shared)
<img width="879" alt="Screen Shot 2020-11-19 at 2 03 00 PM" src="https://user-images.githubusercontent.com/20954967/99711684-16abe580-2a70-11eb-95bb-b4e1c4122d70.png">

View -> Open View… -> Log (Window)
<img width="899" alt="Screen Shot 2020-11-19 at 2 03 17 PM" src="https://user-images.githubusercontent.com/20954967/99711696-1ad80300-2a70-11eb-946f-a508a44921a7.png">

**Comment by sandy081** [comment]
/duplicate

#110870
