### ISSUE TITLE
Emmet feature

### ISSUE THREAD

**Issue by theskyblockman** [microsoft/vscode#110957]
Hey,

we ne help to use the Emmet feature [here](https://code.visualstudio.com/updates/v1_51#_emmet) i created the file like this else i can't find where to set the file
![image](https://user-images.githubusercontent.com/63855457/99696123-a2346f00-2a8e-11eb-9bc2-96cd3f82def8.png)

**Comment by rzhao271** [comment]
Hi @theskyblockman 
Firstly, Emmet applies only to HTML, CSS, or JSX files, not Python. If you want to use snippets in VS Code in general, see https://code.visualstudio.com/docs/editor/userdefinedsnippets
Secondly, `emmet.extensionsPath` can be accessed by first typing `Ctrl+,` to go into 
the settings, then searching for the setting `emmet.extensionsPath`.
