### ISSUE TITLE
changes to files reverted on Jekyll build

### ISSUE THREAD

**Issue by rcrooks** [microsoft/vscode#110975]
Issue Type: <b>Bug</b>

This is only happening on Code-Insiders.
1. open a file (it's a page in a site)
2. make changes and save
3. run Jekyll build to rebuild the site

Result: Jekyll runs, but the changes in the source file are reverted, so nothing really happened.

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:38:14.978Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (13.27GB free)|
|Process Argv|--crash-reporter-id 06bed51c-0413-4152-bfcc-97f311ddef5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-openapi|42C|3.8.0
format-selection-as-html|adr|2.3.0
auto-add-brackets|ali|0.11.0
vs-redoc-viewer|Ati|0.0.3
auto-alignment|Aut|1.1.2
shell-syntax|bma|1.0.1
htmltagwrap|bra|0.0.7
json-tree-view|Cha|2.6.0
path-intellisense|chr|2.3.0
textpad-icon-theme|dam|1.19.20
jshint|dba|0.11.0
vscode-great-icons|emm|2.1.61
indent-switcher|eph|1.2.1
json-tools|eri|1.0.2
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
duplicate|gee|1.0.1
ginfuru-vscode-jekyll-syntax|gin|0.1.1
gruvbox-ish|Gra|0.5.2
docthis|joe|0.7.1
vscode-colorize|kam|0.8.17
string-manipulation|mar|0.4.3
rainbow-csv|mec|1.7.1
openapi-lint|mer|1.2.0
git-graph|mhu|1.27.0
compare-folders|mos|0.18.0
rose-pine|mvl|0.3.20
file-and-folder-icons|nex|1.0.4
vscode-json-editor|nic|0.2.3
prettier-standard-vscode|num|0.8.1
indent-rainbow|ode|7.4.0
color-tabs-vscode-ext|ore|0.12.1
vscode-yaml-sort|Pas|2.7.2
openapi-designer|phi|0.3.0
material-icon-theme|PKi|4.4.0
htmlescape-vscode-extension|ray|0.0.7
vscode-yaml|red|0.13.0
LiveServer|rit|5.6.1
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.0
json2yaml|tux|0.2.0
alphabetical-sorter|ue|2.0.1
remove-empty-lines|use|0.0.6
terminal-all-in-one|yas|1.11.13

(35 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?
