### ISSUE TITLE
FileSystemWatcher.onDidDelete doesn't fire event when the folder containing watched file is deleted directly

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#110923]
Hi Python extension dev here 👋

Version: 1.52.0-insider (user setup)
Commit: 050a123750e4ef4009930d0da1ff7a1a6441d4f3
Date: 2020-11-12T05:43:04.852Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a workspace folder in extension host while debugging your extension .
2. Use the following code in your extension.
```typescript
const globPatern = new RelativePattern(vscode.workspace.workspaceFolders[0].uri.fsPath, '*/Scripts/python.exe');
const fsWatcher = this.workspaceService.createFileSystemWatcher(globPatern);
fsWatcher.onDidCreate((e) => {
    console.log('Old code create', e.fsPath);
});
fsWatcher.onDidDelete((e) => {
    console.log('Old code delete', e.fsPath);
});
```
2. Use command `python -m virtualenv .virtualenv` to create a virtual environment. Notice `Old code create...` is printed.
3. Now delete the `.virtualenv` folder created, you'll notice nothing is printed no longer how long I wait. However, if you repeat the same steps and delete the file directly, `Old code delete` is printed as expected.

**Additional note:** [Original code.](https://github.com/microsoft/vscode-python/blob/3d61063785c90e3a854f55a4f383f6dd65b039be/src/client/pythonEnvironments/discovery/locators/services/workspaceVirtualEnvWatcherService.ts#L60-L69) This prevents us from updating the interpreter list with updated environments. I used chokidar directly, and things work as expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Is this the limitation #110858 is documenting?

**Comment by bpasero** [comment]
Yes, thanks! A limitation with out file watcher that https://github.com/microsoft/vscode/pull/110858 now documents.
