### ISSUE TITLE
Files not saving

### ISSUE THREAD

**Issue by yebowhatsay** [microsoft/vscode#110913]
Issue Type: <b>Performance Issue</b>

Created a file with touch command. 
added some code into the file. 
Tried saving using Ctrl S
Taking a few minute for the file to be saved. 
Happening on Windows.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-5600K APU with Radeon(tm) HD Graphics    (4 x 3591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.46GB (2.79GB free)|
|Process Argv|--crash-reporter-id c19d2c2f-fc75-4a8a-b311-670d05edd6d3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    74	  9852	code main
    1	    57	  5172	   window (Issue Reporter)
    0	    12	  6472	   utility
    8	   130	  9076	   window (bpappointments.go - go-alphadoc-oauth2-server - Visual Studio Code)
    0	    33	  1368	     extensionHost
    0	   294	 13060	       D:\Go\bin\gopls.exe -mode=stdio
    8	    17	  1180	         go list -modfile=C:\Users\merso\AppData\Local\Temp\go.f176a14d91590f04c28ba9dce036768b4e0526c8ebd834c25f4f2426557f7764.761469549.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -- net/http go-alphadoc-oauth2-server/models encoding/json
    0	     6	 12688	         console-window-host (Windows internal process)
    3	    23	 13260	         go list -modfile=C:\Users\merso\AppData\Local\Temp\go.f176a14d91590f04c28ba9dce036768b4e0526c8ebd834c25f4f2426557f7764.611198184.mod -e -json -compiled=true -test=true -export=false -deps=true -find=false -- go-alphadoc-oauth2-server go-alphadoc-oauth2-server/models go-alphadoc-oauth2-server/models/bpappointments go-alphadoc-oauth2-server/models/bpusers
    0	     9	 16692	       electron_node languageserver.js 
    0	    14	  2552	     watcherService 
    0	     6	  2884	       console-window-host (Windows internal process)
    0	    19	  8352	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	 11908	     console-window-host (Windows internal process)
    5	    84	 10772	   gpu-process
    0	    40	 11948	   window (handlers_resources.go - go-alphadoc-oauth2-client - Visual Studio Code)
    0	     5	 12544	     console-window-host (Windows internal process)
    0	    13	 13364	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    16	 13468	     extensionHost
    0	    15	  5828	       electron_node languageserver.js 
    0	    11	 11032	       "D:\Users\merso\AppData\Local\Programs\Microsoft VS Code\Code.exe" "d:\Users\merso\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=13468
    0	   149	 11340	       D:\Go\bin\gopls.exe -mode=stdio
    0	     5	  8792	         console-window-host (Windows internal process)
    0	    12	 14016	     watcherService 
    0	     5	  6920	       console-window-host (Windows internal process)
    0	    12	 12956	   crashpad-handler
    0	    38	 15568	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (bpappointments.go - go-alphadoc-oauth2-server - Visual Studio Code)
|  Window (handlers_resources.go - go-alphadoc-oauth2-client - Visual Studio Code)
|    Folder (go-alphadoc-oauth2-server): 175 files
|      File types: go(86) gohtml(10) css(6) html(4) pem(3) md(3) png(3)
|                  gitignore(1) db(1) crt(1)
|      Conf files:
|    Folder (go-alphadoc-oauth2-client): 134 files
|      File types: go(77) md(3) gitignore(1) pem(1) crt(1) key(1) mod(1)
|                  sum(1) yml(1) db(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
vscode-intelephense-client|bme|1.5.4
gotemplate|cas|0.4.0
bracket-pair-colorizer-2|Coe|0.2.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
go|gol|0.18.1
yii2-snippets|ima|0.1.2
vscode-phpfmt|kok|1.0.30
vscode-JS-CSS-HTML-formatter|lon|0.2.3
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
vscode-duplicate|mrm|1.2.1
mssql|ms-|1.9.0
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-wsl|ms-|0.51.3
vs-keybindings|ms-|0.2.0
go-doc|msy|1.0.1
sqltools|mtx|0.23.0
php-docblocker|nei|2.1.0
go-critic|nev|0.1.0
vscode-php-getters-setters|php|1.2.3
vscode-go-autotest|win|1.6.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen if you run the command to reload with all extensions disabled?

**Comment by yebowhatsay** [comment]
John

Thanks for having a look at this.

There were three files in total that took about 2-3 minutes to save, but
can't reproduce this.

The files are now saving just fine. So, not sure whether it was
interference from the antivirus or not.

Merson

**Comment by gjsjohnmurray** [comment]
That's good to hear. Please close the issue here on GitHub.
