### ISSUE TITLE
<script>if(true) {}</script> breaks HTML parsing/highlighting

### ISSUE THREAD

**Issue by Clonkex** [microsoft/vscode#110985]
Issue Type: <b>Bug</b>

A script tag containing `if(true) {}` breaks subsequent HTML parsing/highlighting. Removing the space between the parentheses and curly braces (like `if(true){}`) unbreaks it.

Broken:

![image](https://user-images.githubusercontent.com/4530775/99741184-9dba9580-2b24-11eb-9f4e-c65df79d521e.png)

Not broken:

![image](https://user-images.githubusercontent.com/4530775/99741199-a8752a80-2b24-11eb-94e2-5b5c9038283b.png)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (16.57GB free)|
|Process Argv|C:\Users\\[user]\ownCloud\Projects\Prodify\productEditor.css --crash-reporter-id b60bb506-cf2d-4c4b-afc9-f3ba657a567b|
|Screen Reader|no|
|VM|57%|
</details>Extensions: none

**Comment by alexr00** [comment]
@Clonkex can you please provide a full copy/pastable example?

**Comment by Clonkex** [comment]
@alexr00 Yes of course. Sorry, I should have thought to do that from the start.

```
<body>
	<script>if(true) {}</script>
	<!--
		<div id="commentedDiv">
		</div>
	-->
</body>
```

[test.zip](https://github.com/microsoft/vscode/files/5655426/test.zip)

**Comment by alexr00** [comment]
@aeschli FYI in case you know exactly how to fix this. I will need to do some more learning.

**Comment by alexr00** [comment]
@aeschli I'm not sure why it's happening, but it seems that something might be wrong with the grammar patching. 
![image](https://user-images.githubusercontent.com/38270282/103363521-8ffd1600-4abb-11eb-8348-cc27dd694b74.png)

**Comment by aeschli** [comment]
It's a dup of fhttps://github.com/microsoft/vscode/issues/70614.
