### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by brianpham93** [microsoft/vscode#110993]
Issue Type: <b>Performance Issue</b>

I disabled all extensions but startup still took several seconds to fully render the window

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 6|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id f91ca8d6-c552-465c-adc2-26b3148b8c60|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    98	 91245	code main
    6	    66	 91248	   gpu-process
    0	    33	 91250	   utility
    4	   262	 91251	   window (Startup Performance)
    0	    82	 91542	     extensionHost
   95	    82	 91543	   shared-process
    0	     0	 91559	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    8	    66	 91557	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by gjsjohnmurray** [comment]
Is #105446 relevant?

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by joaomoreno** [comment]
The most likely culprit is the largest service in the shared process: the extension management service.

**Comment by sandy081** [comment]
I think its not just extensions but mainly due to clean ups and updates being done by shared process:
- extensions
- localizations
- language packs
- storage data
- logs

**Comment by brianpham93** [comment]
[prof-7a86.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/5596802/prof-7a86.extHost.cpuprofile.txt)
Attach profile files collected
[prof-7a86.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/5596804/prof-7a86.main.cpuprofile.txt)
[prof-7a86.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/5596805/prof-7a86.renderer.cpuprofile.txt)

**Comment by jrieken** [comment]
no actionable information. closing
