### ISSUE TITLE
activeEditorGroupIndex and activeEditorGroupLast are wrong

### ISSUE THREAD

**Issue by tommyalatalo** [microsoft/vscode#110984]
- VSCode Version: 1.51.1
- OS Version: Arch Linux, latest

Steps to Reproduce:

1. Split the view into two groups, open 3 editors in one of them, and 1 in the other
2. Use the `Inspect Context Keys` function and click on the last tab on the side with 3 tabs
3. View the results for `activeEditorGroupIndex` and `activeEditorGroupLast`

According to the [documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) `activeEditorGroupLast` should be `True when the active editor in an group is the last one.` and `activeEditorGroupIndex` should be the `Index of the active editor in an group (beginning with 1).`. 

Neither of the above are correct, `activeEditorGroupLast` should be true when the last **editor** is active but it is in fact only true when the last **group** is active. The same goes for `activeEditorGroupIndex` - it doesn't show the index of the active editor, but of the active group. I tested this by adding more than one editor to the last group, and regardless of which editor is active in that group `activeEditorGroupLast` is always true when checking the context, the same goes for `activeEditorGroupIndex`.

The documentation seems to be wrong for these variables, which also means that **there are no variables to use for determining the active editor index and/or if the active is the last editor in the group or not.**

**Suggested solution:**
Update the documentation for activeEditorGroupLast and activeEditorGroupIndex.
Add the corresponding variables for the active editor index and "isLast" state.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode-docs/commit/ad983a5f3b6aff86535645c0bf534cf4a15f3334
