### ISSUE TITLE
Please suppress duplicate threads requests

### ISSUE THREAD

**Issue by polinasok** [microsoft/vscode#110927]
Threads requests can be expensive (e.g. https://github.com/microsoft/debug-adapter-protocol/issues/159), so it would be great if the editor avoided sending duplicate ones when the program is stopped and the state is not changing. Please see issue https://github.com/golang/vscode-go/issues/940 for details on when dups can occur. It would be great if requests issued on stopped events and not just on thread events were checked for duplication. Even if we avoid pulling duplicate information from the debug backend in the debug adapter, we would still need to send the duplicate responses back, which could be a performance hit. Getting to the root of the duplication on the editor end would be most efficient.

**Comment by weinand** [comment]
@polinasok agreed, VS Code should not request threads unnecessarily.

**Comment by isidorn** [comment]
Agreed.

@polinasok can you please create a reproducible steps using Mock debug or js debugging so I can reproduce this on my machine.
If that is not convenient we also accept PRs that would potentially fix this on the VS Code side.
You can put a breakpoint [here](https://github.com/microsoft/vscode/blob/4b5dc2fcbc2d6b33064fe36081d485558982d127/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L453) and check when the `threads` is called duplicated.

Thanks
