### ISSUE TITLE
VSCode Insiders - Extensions Not Loading

### ISSUE THREAD

**Issue by sleblang** [microsoft/vscode#110978]
- VSCode Version: 
    Version: 1.52.0-insider
    Commit: a36c68b9ec3d6a0aca9799d7a10be741a6658a51
    Date: 2020-11-19T05:38:14.978Z
    Electron: 9.3.3
    Chrome: 83.0.4103.122
    Node.js: 12.14.1
    V8: 8.3.110.13-electron.0
    OS: Darwin x64 18.7.0
- OS Version: macOS Mojave v 10.14.6

Steps to Reproduce:

1. Click on Extensions Icon on Sidebar
2. Extensions should load in Sidebar. They are not loading. 

Does this issue occur when all extensions are disabled?: N/A

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/110870

**Comment by thunder-coding** [comment]
#110956
