### ISSUE TITLE
Code formatting stopped working

### ISSUE THREAD

**Issue by arte0s** [microsoft/vscode#110950]
Code formatting stopped working after I click ALT+SHIFT+F...

It work:
```
class Test  {
    constructor() {
        this.value = true;
    }
}

Test    .run = function () {
    return true;
};
```

It does't work:
```
class Test {
    constructor() {
        this.value = true;
    }
}

Test.prototype    .run = function () {
    return true;
};
```

PS: I use "Beautify" code formatter.

**Comment by IllusionMH** [comment]
If you have Beautify configured as formatter for JS/TS and you see this error - you should report this issue in Beautify extension repo.

/needsMoreInfo

Please provide all info required by issue template (OS, versions, etc,).

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Just tried with built-in formatter (but on VS Code insiders and TS nightly) everything works as expected.

**Comment by arte0s** [comment]
@IllusionMH Built-in formatter works fine! Thanks for the advice!
