### ISSUE TITLE
terminal wsl failed to launch 

### ISSUE THREAD

**Issue by aca-pulco** [microsoft/vscode#110949]
**Error** : The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 1).

- VSCode Version: 1.51
- OS Version: Windows
- Wsl 2 version

**Solution for me**
in setting.json file add following : 
`"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\wsl.exe",`
 `"terminal.integrated.shellArgs.windows":  [
        "-d",
        "Ubuntu-20.04"
    ],`

**Comment by amlcodes** [comment]
was this fixed? running into the same issue
