### ISSUE TITLE
Support for top-level await operators

### ISSUE THREAD

**Issue by SalmonMode** [microsoft/vscode#110951]
This is a followup to #38316, so I'll mostly be copying the details from there. #38316 was closed in March, but yesterday a project member of Chromium commented on the [linked Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=833928) to say that there are no plans to work on this, so I wanted to followup here and see if something could be done outside of Chromium, or if an alternate solution already exists.

- VSCode Version: 1.51.1
- OS Version: Mac OS Catalina 10.15.6

Steps to Reproduce:

1. Open the attached code in VSCode. Set a debug break point at line 7.
2. Click Debug then Start Debbuging. In the debug console type "await testFunction(); " then press enter. SyntaxError: Unexpected identifier appears in the Debug Console.
3. In the debug console, type "(async () => { await testFunction();} )();" then press enter. Promise { pending } appears.

```javascript
async function testFunction() {
    return new Promise((resolve) => {
        resolve('test');
    });
}

testFunction().then((res) => {
    console.log(res);
});
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
> Click Debug then Start Debbuging. In the debug console type "await testFunction(); " then press enter. SyntaxError: Unexpected identifier appears in the Debug Console.

I'm not able to reproduce this. Can you confirm that `debug.javascript.usePreview` is *not* false. If that's already the case, please collect logs

/jsDebugLogs

> Promise { pending } appears.

There's not a workaround for this. The runtime is paused which does not allow the tasks and microtasks associated with the promise to run. I cannot say I expected anything other than the author's last reply on that chromium issue, as making this would work require a whole lot of work and special casing on V8's side of things.

**Comment by SalmonMode** [comment]
My bad, I should have read the original ticket's steps more carefully. It no longer throws an error, and now produces `Promise {<pending>}`. It sounds like there's nothing that can be done for now, and if so, this can probably be closed. Thanks for your time!

**Comment by connor4312** [comment]
no worries, thanks for the issue

/duplicate
