### ISSUE TITLE
On ChromeOS/Crostini, Chrome can't re-launch VS Code after authenticating with GitHub

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode#110909]
- VSCode Version: 1.51
- OS Version: ChromeOS on ARM64

Steps to Reproduce:

1. Start the flow to authenticate with GitHub (haven't tested with Microsoft Accounts)
2. The browser is launched automatically
3. Follow the steps in the browser
4. In the last step, where the auth token is shown, Chrome can't send users back to VS Code and the error below appears

![Screenshot 2020-11-18 at 19 17 05](https://user-images.githubusercontent.com/43508/99617100-6d171680-29d3-11eb-993c-3868e40995c1.png)

Does this issue occur when all extensions are disabled?: No extension installed

**Comment by RMacfarlane** [comment]
I don't think we can change anything here, the page Chrome is trying to open is a redirect to a `vscode` protocol handler. There are instructions on what to do if the redirect fails that should allow completing the sign in process
