### ISSUE TITLE
Apple silicon(m1) version run node cause err: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by vast-z** [microsoft/vscode#110931]
- VSCode Version: insider(apple arm experience)
- OS Version: mac os big sur

Steps to Reproduce:

1. write a js script
2. press F5 run with Nodejs,then cause this error

Does this issue occur when all extensions are disabled?: Yes.

**Comment by weinand** [comment]
Please provide reproducible steps:
- How does the JS program and your launch.json look like?
- Screenshot of the error.

**Comment by vast-z** [comment]
Thank you very much for your reply. After I restart vscode, "Extension host terminated unexpectedly" will no longer pop up in the lower right corner, but the js program still cannot be executed, auto exit. It also cannot be used for debugging. The terminal is running well.
![image](https://github.com/vast-z/pic/blob/master/m1-vscode-node1.png)
![image](https://github.com/vast-z/pic/blob/master/m1-vscode-node2.png)
![image](https://github.com/vast-z/pic/blob/master/m1-vscode-node3.png)

**Comment by connor4312** [comment]
Can you collect some logs? That should show us the complete error which is truncated in the call stack view.

/jsDebugLogs

**Comment by vast-z** [comment]
Thank you very much for your reply. Is this the debug information?
![debug trace](https://github.com/vast-z/pic/blob/master/vscode-debugadapter-0.json)

**Comment by connor4312** [comment]
Indeed, unfortunately not many more details there

>Error: hash.bundle.js process unexpectedly exited
>at t.Hasher.send (extension.js:22:34881)
>at t.Hasher.verifyFile (extension.js:22:34710)
>at Object.t.checkContentHash (extension.js:1:58595)
>at new I (extension.js:1:61505)
>at F.addSource (extension.js:1:69494)

I don't have an Apple Si device to test on but will see if I can find one to remote into

**Comment by vast-z** [comment]
thank you for your help. If necessary, I can provide the device remotely for debugging..

**Comment by richiksc** [comment]
This might have been fixed by nodejs/node#35986. Many people were reporting issues with wasm causing crashes on Apple Silicon, V8 released some fixes, and Node cherry-picked them and merged them into `master` on Nov 12. They haven't published these changes as a release yet, however, even as of v15.2.1 which was released on November 16th. VSCode could either wait for an upstream release or cherry-pick these changes from upstream Node for the debugger.

**Comment by vast-z** [comment]
I found that in the latest version, this problem seems to have been solved, thank you very much for the people who worked on this

**Comment by deepak1556** [comment]
Yes latest update with newer electron runtime fixes loading of wasm modules. Thanks for confirming.
