### ISSUE TITLE
task list support

### ISSUE THREAD

**Issue by DanielChuDC** [microsoft/vscode#110911]
Hi I am not sure this is the right place to ask. 

I would like to request for task list support.

Now when I using `vscode` with `docs-markdown` and `docs-preview` extension, vscode does not render and show the task list.

### Current preview
<img width="686" alt="Screenshot 2020-08-30 at 6 04 47 PM" src="https://user-images.githubusercontent.com/52316624/91656449-586d6580-eaeb-11ea-894d-c3fc39a5d4bf.png">
<img width="640" alt="Screenshot 2020-08-30 at 6 04 51 PM" src="https://user-images.githubusercontent.com/52316624/91656451-5b685600-eaeb-11ea-82ee-a4fa4e711fa0.png">

### Expected output
<img width="387" alt="Screenshot 2020-08-30 at 6 01 57 PM" src="https://user-images.githubusercontent.com/52316624/91656384-ea28a300-eaea-11ea-86b2-0df8e486f3e1.png">

**Comment by mjbvz** [comment]
See https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox
