### ISSUE TITLE
c# code with #region, "" and / formatting issue

### ISSUE THREAD

**Issue by ruchanb** [Microsoft/vscode#11098]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/11032047/18050645/97367156-6e0f-11e6-81fe-bbce94bd8000.png)

The formatting goes bad when the `#region` has `""` and `/` on it.

**Comment by ruchanb** [comment]
I think this issue is to posted to csharp plugin provider

**Comment by dbaeumer** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#731
