### ISSUE TITLE
relative include paths in search much slower than absolute paths

### ISSUE THREAD

**Issue by shuffle2** [microsoft/vscode#110924]
Issue Type: <b>Performance Issue</b>

I have opened vscode in a directory containing "many" subdirectories and files. (output of `find . -type f -print | wc -l` is 896037).
Often, I want to "search in files" (ctrl+shift+f) and limit the scope to a subdirectory under the root which is open in vscode by specifying the subdirectory in "files to include". I've noticed that if the subdirectory path is absolute (e.g. `c:\root\some\sub\directory`), opposed to relative (`some\sub\directory`), the search completes much more quickly ( ~1 second vs. > 30 seconds).

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3990X 64-Core Processor  (64 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.87GB (161.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
arm|dan|1.4.0
xml|Dot|2.5.1
gc-excelviewer|Gra|3.0.40
python|ms-|2020.11.367453362
jupyter|ms-|2020.11.358541065
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.3
cpptools|ms-|1.1.2
rust|rus|0.7.8
crates|ser|0.5.3
fpga-support|ste|0.1.10
rust-pack|Swe|0.2.29

</details>

**Comment by roblourens** [comment]
`some\sub\directory` actually searches `**\some\sub\directory`, you can anchor it to the root by prefixing with `./`
