### ISSUE TITLE
QuickOpen - disabling preview mode not working

### ISSUE THREAD

**Issue by EightArmCode** [microsoft/vscode#110952]
- VSCode Version: 1.51.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. User Settings > Workbench > **Uncheck** Quick Open: Close On Focus Lost > Restart (I have it disabled in both User and Workspace)
2. CMD+P to quick open a file. The filename is italicized and closes when focus is lost.

Does this issue occur when all extensions are disabled?: Yes

_Discovered a nice workaround until this is fixed - Use CMD+P to quick open, and instead of hitting return after highlighting the needed file, open with ALT+Enter or Option+Enter (depending on your config/OS)_

**Comment by gjsjohnmurray** [comment]
You are confusing "Quick Open" (`Cmd+P` quickpick) with "[Preview Mode](https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode)".

Though I don't recall a preview-mode file (tab label _italicized_) automatically closing just because focus is lost.

**Comment by EightArmCode** [comment]
Could you elaborate?

**Comment by EightArmCode** [comment]
My understanding is that Quick Open (CMD+P) will open in Preview Mode, unless you uncheck this box. I've unchecked the box in settings, and it still opens them in preview mode.

**Comment by gjsjohnmurray** [comment]
Do you mean this one?
```
"workbench.editor.enablePreviewFromQuickOpen": false
```

**Comment by gjsjohnmurray** [comment]
In the GUI Settings editor:

![image](https://user-images.githubusercontent.com/6726799/99695061-04887200-2a85-11eb-99b8-14695b2bb138.png)

**Comment by EightArmCode** [comment]
Wow. Yep that's the one! I now see what you mean about "quick open". Is the just the palette where you select the file?

**Comment by EightArmCode** [comment]
That's really confusing
<img width="716" alt="Screenshot 2020-11-19 at 21 12 05" src="https://user-images.githubusercontent.com/7226801/99718949-f6018100-2aab-11eb-96aa-14b0ba66ce54.png">
