### ISSUE TITLE
How to make sure colorizer only work on special outputChannel?

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#110918]
own extension will run mocha test by nodejs spawn function , and append the output to an outputChannel . we create a colorizer 
 for the outputChanel by the same way as [vscode-log-output-colorizer](https://github.com/IBM-Cloud/vscode-log-output-colorizer), Is there any way to specify this colorizer to only work on the outputChannel created by our extension, not affectting other outputChannel .

**Comment by gjsjohnmurray** [comment]
Not currently possible AFAIK. @jrieken maybe #11005 could be reconsidered. A PR offer from @seanpoulter there got no response.
