### ISSUE TITLE
`editor.renameOnType` causes unwanted renaming outside of HTML tags

### ISSUE THREAD

**Issue by DanielHZhang** [microsoft/vscode#110983]
Version: 1.52.0-insider (user setup)
Commit: a36c68b9ec3d6a0aca9799d7a10be741a6658a51
Date: 2020-11-19T05:37:52.577Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
WSL2
Remote-WSL: 0.51.3

**Steps to Reproduce:**

1. Enable `"editor.renameOnType": true` in settings.
2. Create a Typescript file with the contents below:
```typescript
function foo(object: Record<string, any>): void {
  const bar = '';
  if (bar === '') {
    bar.toLowerCase();
  }
  
}
```

3. Put the cursor on line 6 and type `bar`.
4. Wait momentarily for the `renameOnType` handler to select all occurrences of `bar`.
5. Backspace `bar` on line 6.

**Expected:**
Only `bar` on line 6 is deleted, as it is not an HTML tag. 

**Issue:**
All instances of `bar` are deleted.

See: 
![typed-array-buffer-schema-_WSL_-Ubuntu_-test ts-2020-11-19-17-09-52](https://user-images.githubusercontent.com/30360288/99730708-e756a200-2a8a-11eb-863c-5b315b9ee507.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by napei** [comment]
Am experiencing something similar, but more annoyingly in Typescript with `this` which makes it disappear from pretty much everywhere in the document.

**Comment by tlgreg** [comment]
Same with typescript generic types.

**Comment by jrieken** [comment]
That's how the feature is meant to work and you should be using `"editor.renameOnType": false` then

**Comment by IllusionMH** [comment]
@jrieken in JS rename on type will be very useful in the same way as in HTML - edit JSX tags.
If I put
```json
// "[typescript]" or
"[javascript]": { 
    "editor.renameOnType": false
}
```

it obviously disables it in all areas and won't be possible in JSX as well.
Are there plans to have option to disable them in regular code (mostly hurts + problems with 1 character generic types in TS) but leave available for JSX #85707 ?

**Comment by jrieken** [comment]
We will nuke the current TS implementation and rework the API and setting. This isn't about rename (in the sense of the rename refactoring) but about "linked cursors". See https://github.com/microsoft/vscode/issues/109923#issuecomment-733034227 as related discussion

**Comment by IllusionMH** [comment]
> We will nuke the current TS implementation and rework the API and setting

@jrieken thank you for clarification. Will look for new implementation/settings, in the meantime will disable it for specific languages.
