### ISSUE TITLE
python interactive interactive window does not let type

### ISSUE THREAD

**Issue by rmarinbe** [microsoft/vscode#110916]
when running a cell inside vscode (shift-enter) the interactive output runs fine but the command interactive window does not let to type again when switching from code file (left file) and interactive window (right at the bottom). 

![image](https://user-images.githubusercontent.com/50396949/99624025-0275d300-29f3-11eb-985c-b8cb15b99b9b.png)

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
