### ISSUE TITLE
Code crashes if you exit the launching process

### ISSUE THREAD

**Issue by latkin** [Microsoft/vscode#1109]
- Start cmd
- Launch VS Code from prompt
- Close cmd

**Expected:** VS Code continue to run
**Actual:** Just before closing, cmd displays `[VS Code]: render process crashed`, and both cmd and Code exit

Screencap from right after X-ing out of cmd:

![image](https://cloud.githubusercontent.com/assets/5943573/11665470/77b729cc-9d9c-11e5-8e12-fe514497a4c7.png)

```
Version 0.10.3
Commit 783ecf841a2b21edca6d86853670cae89b4c244f
Date 2015-11-26T14:06:31.538Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by bpasero** [comment]
This might be fixed with future versions of Electron, I saw something...

**Comment by latkin** [comment]
Likely related, also strange:

 - Launch Code via code.exe from the terminal
 - Go about your business
 - At some point, break out of any other action in that terminal via <kbd>Ctrl</kbd> + <kbd>C</kbd>

Code will mysteriously exit. Somehow it's listening for <kbd>Ctrl</kbd> + <kbd>C</kbd> from the parent process?

![ctrlc](https://cloud.githubusercontent.com/assets/5943573/11916664/401e3378-a695-11e5-9ce2-a2d2825b1100.gif)

**Comment by bpasero** [comment]
Please reopen if this still happens with our latest cli work.
