### ISSUE TITLE
Josh

### ISSUE THREAD

**Issue by runyanjc** [microsoft/vscode#111051]
Issue Type: <b>Bug</b>

1. Click on angular.json file 
2. VSCODE freezes (happens in less than a second, based on not being able to move mouse pointer more than 1/8" on screen)
3. Computer automatically restarts

(I can open the above json file with other editors. I tried to open other json files with VSCODE same problem as above - these included files from sources that were edited with VSCODE and json files that were not edited in VSCODE or associated with project using VSCODE.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|29, 7, 3|
|Memory (System)|16.00GB (7.76GB free)|
|Process Argv|--crash-reporter-id 70f6be8a-5381-49ff-b89e-0d4cad5986ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.1
vscode-browser-preview|auc|0.6.7
npm-intellisense|chr|1.3.1
vscode-npm-script|eg2|0.3.13
code-runner|for|0.11.1
Angular2|joh|9.1.2
mongodb-vscode|mon|0.2.1
debugger-for-chrome|msj|4.12.11

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by runyanjc** [comment]
> /needsMoreInfo
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`

IllusionMH - I can access the the file when all extension are disabled. I guess now I need to figure out which extension it is. This issue began two days ago. Besides looking fro recently updated extensions, is there another way to do this?

**Comment by IllusionMH** [comment]
It doesn't look like you have many of them. I usually either disable all one by one and see if problem is gone and recheck with only that extension enabled to confirm.

I saw there is issue tracking implementation for extensions bi-sect, but not sure if it is implemented already.
