### ISSUE TITLE
Ubuntu system got stuck there occasionally till you reboot the OS

### ISSUE THREAD

**Issue by SG-Yang** [microsoft/vscode#111075]
- VSCode Version: 
1.51.1
- OS Version:
Linux cyd 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Steps to Reproduce:

ERROR: apport (pid 6786) Sat Nov 21 10:18:33 2020: executable: /snap/code/50/usr/share/code/code (command line "/snap/code/50/usr/share/code/code\ --type=gpu-process\ --field-trial-handle=12147598567779703302,8330911992171983918,131072\ --enable-features=WebComponentsV0Enabled\ --disable-features=SpareRendererForSitePerProcess\ --disable-color-correct-rendering\ --no-sandbox\ --enable-crash-reporter=a5ad7e08-f86c-47b2-afc6-d36d2450cada,no_channel\ --global-crash-keys=a5ad7e08-f86c-47b2-afc6-d36d2450cada,no_channel,_companyName=Microsoft,_productName=VSCode,_version=1.51.1\ --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAAAAAAAAAA=\ --shared-files")
ERROR: apport (pid 6786) Sat Nov 21 10:18:33 2020: executable does not belong to a package, ignoring

Does this issue occur when all extensions are disabled?: Yes/No
Not sure.

**Comment by deepak1556** [comment]
It is worth checking if the issue repros when you have gpu acceleration disabled https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
