### ISSUE TITLE
messages in the console when starting code-exploration

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#111046]
Issue Type: <b>Bug</b>
cc: @isidorn 
I am receiving the following messages in the console when I run code-exploration.

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
(node:161619) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bash: warning: setlocale: LC_ALL: cannot change locale (en-US)
(node:161678) Electron: Loading non-context-aware native module in renderer: '/backup/homefiles/Downloads/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:161678) Electron: Loading non-context-aware native module in renderer: '/backup/homefiles/Downloads/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:161619) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:161778) Electron: Loading non-context-aware native module in renderer: '/backup/homefiles/Downloads/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

The messages are displayed even if I disabled all extensions.

I am running code-exploration using orca as my screen reader.
I don't know if the messages are displayed if orca is not active.

VS Code version: Code - Exploration 1.52.0-exploration (7af7d1c0c5af759c0e5bee5139491b3524a2ec8d, 2020-11-19T10:23:11.014Z)
OS version: Linux x64 5.9.8-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2526)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.68GB (0.83GB free)|
|Process Argv|-n --disable-extensions|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30226749
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by jvesouza** [comment]
Messages are also displayed even when I am not using orca.

**Comment by roblourens** [comment]
I think that these are all known warnings and can be ignored.

**Comment by jvesouza** [comment]
What caught my attention were these messages:

bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

**Comment by roblourens** [comment]
I think these are probably produced by the shell process we spawn internally to probe the user's environment. I wouldn't worry about it unless you are seeing an issue

**Comment by isidorn** [comment]
@jvesouza thanks for reporting.
@deepak1556 just fyi

**Comment by jvesouza** [comment]
When I run code-insiders using terminal the terminal is released and I can type new commands using the same terminal used to run code-insiders.
When I run code-exploration in the terminal the terminal is not released and I can not type new commands using the terminal.
This is a difference between code-insiders and code-exploration.

**Comment by isidorn** [comment]
@jvesouza thanks for letting us know. Let's reopen this so @deepak1556 can comment
also fyi @bpasero 

Gist is in the last comment from @jvesouza

**Comment by zlondrej** [comment]
I'm more worried about this one and it causes some issues.
```
bash: warning: setlocale: LC_ALL: cannot change locale (en-US)
```
1) `en-US` is not a valid Linux locale, that's `en_US` (underscore instead of dash).
2) It breaks a functionality of this extension https://marketplace.visualstudio.com/items?itemName=valderman.ctagsymbols, when using `hasktags`, because `hasktags` doesn't work properly with locale that doesn't specify correct system encoding (it requires `en_US.UTF-8`).

**Comment by jvesouza** [comment]
It seems that the messages I received were caused by the way I activated code-exploration.
Instead of running the code-exploration from the bin folder, I ran the code-exploration present in the VSCode-linux-x64 folder.

I thought it was indifferent to run from one place or another but I was wrong.

Please forgive me for all the noise I made about it.
For me this issue can be closed.
Thanks and again sorry for the noise.
