### ISSUE TITLE
the sync doesn't work with new arm mac, the error message is very clear about the cause

### ISSUE THREAD

**Issue by jason919** [microsoft/vscode#111072]
Issue Type: <b>Bug</b>

Writing login information to the keychain failed with error 'dlopen(/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node, 1): no suitable image found. Did find: /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: mach-o, but wrong architecture /Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: mach-o, but wrong architecture'.

VS Code version: Code - Exploration 1.52.0-exploration (88c7381b77df9601914ca914f80c700fee35825a, 2020-11-20T09:15:28.497Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.0
vscode-titanium|Axw|0.10.0
bracket-pair-colorizer|Coe|1.0.61
LogFileHighlighter|emi|2.10.0
prettier-vscode|esb|5.8.0
vscode-lombok|Gab|1.0.1
material-icon-theme|PKi|4.4.0
vscode-p3c|Rec|0.1.2
java|red|0.71.0
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
vscode-spring-initializr|vsc|0.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry914:30226749
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by philipp-tailor** [comment]
Similar issue occurs when trying to log into the "Live Share" extension. The [iMazing Silicon app](https://github.com/DigiDNA/Silicon) specifically shows that at least the "Live Share" extension is not yet an universal binaries. Probably that's a compatibility issue when running VSCode with ARM compile target?

**Comment by deepak1556** [comment]
This should be fixed with latest builds, please update to commit a31f124319
