### ISSUE TITLE
Support syntax highlighting for LaTeX in the preview

### ISSUE THREAD

**Issue by gaochenyi** [microsoft/vscode#111024]
A LaTeX fenced code block in markdown does not have syntax highlighting in the preview of the markdown file.

Actually I first report [this issue][link] to the extension 'Markdown All in One'. But a developer there tells me that this is a feature lacked in the core and should be reported to the upstream VS Code. So I post this issue here.

The solution mentioned there is to upgrade `highlight.js` to the latest version 10. Would this be possible in the near future?

[link]: https://github.com/yzhang-gh/vscode-markdown/issues/849

**Comment by gaochenyi** [comment]
##yzhang-gh/vscode-markdown/issues/849

**Comment by mjbvz** [comment]
Should be fixed by #111262

**Comment by mjbvz** [comment]
Verify using the following markdown:

~~~
```tex
\TeX
```

```latex
\TeX
```
~~~
