### ISSUE TITLE
Unable to run scripts in Editor if folders in explorer or workspace

### ISSUE THREAD

**Issue by baldieavenger** [microsoft/vscode#111047]
Issue Type: <b>Bug</b>

Hi team,

Im new to Code from ISE so apologies for the lack of knowledge around it but trying to figure things out. Other than this.

When adding a local directory folder to my saved workspace, when I try to use F5 to run the script in my editor, Im given this error: 

PS C:\LOCALPATH> C:serssernameocumentsindowsPowerShellicrosoft.VSCode_profile.ps1
The term 'C:serssernameocumentsindowsPowerShellicrosoft.VSCode_profile.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
    + CategoryInfo          : ObjectNotFound: (C:serssername...ode_profile.ps1:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

Looks like its trying to run my already run and loaded Microsoft.VSCode_profile.ps1 which contains my 365 modules and I have no idea why or how to start to figure it out. 

Can anyone assist please?

Thanks!

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
powershell|ms-|2020.6.0
vscode-icons|vsc|11.0.0

</details>

**Comment by baldieavenger** [comment]
Ok, been digging more and its only when I pin the same folder my current powershell directory is set to. If I dont pin that folder, even with multiple other folders pinned then its fine! 

I thought maybe a file ext in there tying it up so deleted most but still have the issue.

I tried changing my directory to something else and pinning the folder again but when I hit F5, it changes my directory back to that pinned location with the same error ( I use "CD C:\Etc\Etc" to set my directory on log in in Microsoft.VSCode_profile.ps1.) but now at a loss as to whats causing it.

**Comment by weinand** [comment]
Please file this issue against the PowerShell extension.

**Comment by baldieavenger** [comment]
Hi @weinand, how would I go about doing that?

Also, I have a colleague with the same extensions, theme and all and he doesn't have this problem which makes me wonder if it's not the extension? Happy too if that's where you think it is and if that's the next step though

**Comment by weinand** [comment]
In VS Code's "Issue Reporter" you can select the PowerShell extension:

<img width="700" alt="2020-11-20_22-18-16" src="https://user-images.githubusercontent.com/1898161/99851014-ab9d0480-2b7e-11eb-9481-f3055b470f6e.png">

(instead of "Jupyter" you should see "PowerShell")
