### ISSUE TITLE
Please make "Open Folder Context Menus" a default feature

### ISSUE THREAD

**Issue by m-ghaoui** [microsoft/vscode#111004]
Please add the ability to open a folder in a new VS Code instance, or in the existing VS Code instance, by using the context menu in the file explorer.

As implemented in this plugin:

https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance

![image](https://user-images.githubusercontent.com/481297/99769787-2aeef180-2b07-11eb-9254-281942da77a0.png)

Although I would personally not call it "Workbench" but:

1. Open Folder
2. Open Folder in New Instance 

And I would put the two menu items under "New Folder" and above "Reveal in File Explorer".

**Comment by isidorn** [comment]
We will not do this in VS Code core sorry. We try to make the context menu minimal, and who wants this can install that extension.
