### ISSUE TITLE
references.preferredLocation -> View doesn't seem to work (Typescript)

### ISSUE THREAD

**Issue by dougleville** [microsoft/vscode#111032]
- VSCode Version: 1.50.1
- OS Version: Windows 10 2004

Steps to Reproduce:

1. change references.preferredLocation from "peek" to "view"
2. go to a typescript definition and click on codelens references 
3. peek window still appears
![image](https://user-images.githubusercontent.com/30697943/99814969-b7091500-2b17-11eb-9328-c9db751d7c4b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Already fixed for 1.51
