### ISSUE TITLE
Crash when reloading window on M1 Mac

### ISSUE THREAD

**Issue by kynrai** [microsoft/vscode#111091]
Issue Type: <b>Bug</b>

Install latest insiders build on apple silicon mac, download and apply github theme dark, this causes a crash.
Same thing happens with if install and apply the material icon pack

VS Code version: Code - Exploration 1.52.0-exploration (88c7381b77df9601914ca914f80c700fee35825a, 2020-11-20T09:15:28.497Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.18.1
material-icon-theme|PKi|4.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30226747
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by kynrai** [comment]
An easier way to trigger likely the same crash is to cause a auto UI reload, for example change the settings editor mode from ui->json and that causes a reload which crashes the window

**Comment by deepak1556** [comment]
Can you start with `--crash-reporter-directory /tmp/vscode-crash` and attach the generated dmp files when crash happens.

**Comment by kynrai** [comment]
Interestingly I cannot cause this to crash any longer with all my previous steps to generate the crash report, Ive not changed any other settings but something has stabilised it. If anyone else gets this issue maybe they can post a crash report, ill keep trying though

**Comment by ItalyPaleAle** [comment]
This seems to be happening to me when extensions are installed that could cause the window to reload. For example, after enabling settings sync for the first time (so my extensions are re-installed) or after connecting to a new Remote Container, when new extensions need to be re-installed.

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/106770, some of the crash paths should be fixed in the next release
