### ISSUE TITLE
PHP: Dollar symbol is somehow in a different color

### ISSUE THREAD

**Issue by finn-matti** [microsoft/vscode#111035]
- VSCode Version: 1.51.1
- OS Version:mac OS 10.15.6

Steps to Reproduce:

In the method `runInternal` the dollarsign (`$`) next to callback is white, even though it should be light blue:

```php
<?php
namespace app\tests\unit\tasks\behaviors;

use app\tasks\Task;
use app\tests\unit\tasks\TestTaskTrait;

class TempTableBehaviorTestTask extends Task
{
    use TestTaskTrait {
        TestTaskTrait::runInternal as baseRunInternal;
    }

    public $runInternalCallback;

    public $tempTableConfig;

    /**
     * @inheritdoc
     */
    public function runInternal()
    {
        if (is_callable($this->runInternalCallback)) {
            $callback = $this->runInternalCallback;
            $callback($this);
        }
        return $this->baseRunInternal();
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['tempTable']['enabled'] = true;
        $behaviors['tempTable']['tableConfig'] = $this->tempTableConfig;
        return $behaviors;
    }
}
```

Screenshot:

<img width="494" alt="Screenshot 2020-11-20 at 15 11 31" src="https://user-images.githubusercontent.com/56148301/99803783-ad48d700-2b42-11eb-95fe-1abd2e770dcb.png">

Does this issue occur when all extensions are disabled?: Yes

It also does occur in vs code insiders:

<img width="787" alt="Screenshot 2020-11-20 at 17 38 19" src="https://user-images.githubusercontent.com/56148301/99818680-2eaa6480-2b57-11eb-94d9-948a0d8b7c4e.png">

The user @kanlukasz has also confirmed this behavior on Windows 10 with WSL2 env on the original issue https://github.com/bmewburn/vscode-intelephense/issues/1520

**Comment by roblourens** [comment]
Thanks, filed upstream https://github.com/atom/language-php/issues/403
