### ISSUE TITLE
Always start a workspace in Welcome Page

### ISSUE THREAD

**Issue by newtoniumx3** [microsoft/vscode#111056]
- VSCode Version: 1.5.11 (portable)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a workspace and add a directory
2. Create a file in the directory
3. Open from vscode (while being in the workspace)
4. Close vscode
5. Re-open the workspace

The issue is it remembers the last opened file when I would like it to always go to the "Welcome Page"

I searched the settings and previous issues and used the settings but it's still not working. In my case the workspace re-opens in the exact same state. 

Ideally I would love for all the open tabs to close and the workspace to reopen with 0 tabs open or just with the Welcome page.

```
"workbench.editor.restoreViewState": false,
"workbench.startupEditor": "welcomePage",
"window.restoreWindows": "none",
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
I don't see a setting for not restoring all editors. Alternatively we could add another option to `"workbench.startupEditor"`.
