### ISSUE TITLE
Getting message "Permission Denied" in VS Code while running a program

### ISSUE THREAD

**Issue by ash1198-CP** [microsoft/vscode#111010]
I already defined path of the compiler in the Environment variable and my antivirus is showing threat dedected whenever I try to run the  code 

- VSCode Version: 1.51
- OS Version: Windows 10, 64 bit

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: No

**Comment by ash1198-CP** [comment]
![Screenshot (7)](https://user-images.githubusercontent.com/74723365/99783084-f4819880-2b3f-11eb-93e1-9a1b785acf4c.png)

**Comment by gjsjohnmurray** [comment]
> my antivirus is showing threat dedected whenever I try to run the code

That is outside VS Code's control. Sounds like you need to add an exception to your AV config.

**Comment by ash1198-CP** [comment]
> > my antivirus is showing threat dedected whenever I try to run the code
> 
> That is outside VS Code's control. Sounds like you need to add an exception to your AV config.

Yeah. I turned of auto protection of antivirus and again ran the program. It ran once and showed the same message.

**Comment by weinand** [comment]
The problem seems to occur when compiling the program, not when running (the loader "ld" cannot write the executable).
Do you have write access to the OneDrive?

**Comment by roblourens** [comment]
Sorry, this is probably not an issue with VS Code
