### ISSUE TITLE
Debug Auto Attach: introduce an option to disable without hiding status bar item

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#111021]
Currently we have these Auto Attach settings:

<img width="665" alt="2020-11-20_12-06-45" src="https://user-images.githubusercontent.com/1898161/99793563-26d3cb80-2b29-11eb-8b9f-7307a13f4bce.png">

What I think is missing is a setting that disables Auto Attach but continues to show it in the status bar.
Sometimes I just want to disable Auto Attach temporarily but since the status bar item is gone, I forget to enable it again...

I think we have two options to achieve this:
- we just add a new value "Off" (or "Never" if we want to match "Always") for the Auto Attach setting and leave the "Disabled" untouched, or
- we change the semantics of the existing "Disabled" setting to not hide the status bar item. In this case we'd rely on the item's context menu to show/hide status bar items.

/cc @egamma

**Comment by connor4312** [comment]
This has been on my mine for a little while, thus done. There's a new option that disables auto attach for the "current session", which doesn't require a reload (and will only be in effect until the window is reloaded).

![recording(9)](https://user-images.githubusercontent.com/2230985/99861269-7080de00-2b4a-11eb-8ca8-4bd4bcb96601.gif)

**Comment by weinand** [comment]
There is a new "Temporarily Disable" option in the QuickPick.
The fact that it is only visible if auto attach is already shown in the status bar surprised me a bit. But I think the logic behind that is ok.

**Comment by weinand** [comment]
This works fine now. 

But I've filed https://github.com/microsoft/vscode/issues/111890

**Comment by connor4312** [comment]
Agree, I've had to point that out to users a few times.

Thanks for verifying!
