### ISSUE TITLE
Selection Highlight stops after 1000 matches

### ISSUE THREAD

**Issue by latkin** [microsoft/vscode#1110]
I don't see any setting to control this, so the behavior seems unexpected/unintuitive.
- Create text file with the line `oh hai` > 1000 times
##### Scenario 1
- Single-click `hai` on line 1

Expected: All instances of `hai` are highlighted
Actual: Only the first 500 are highlighted (markers on scrollbar indicate similar)

![image](https://cloud.githubusercontent.com/assets/5943573/11665991/05ccc59e-9d9f-11e5-98b5-a3fa849860a2.png)
##### Scenario 2
- Double-click `hai` on line 1

Expected: All instances of `hai` are highlighted
Actual: First 500 instances are bright-highlighted, the next 500 are dim-highlighted, and the rest are un-highlighted.

![image](https://cloud.githubusercontent.com/assets/5943573/11666004/169ccb4e-9d9f-11e5-88b9-9b5190ab5a28.png) ![image](https://cloud.githubusercontent.com/assets/5943573/11666020/29a17f78-9d9f-11e5-8d87-4ab18dd0599e.png)

```
Version 0.10.3
Commit 783ecf841a2b21edca6d86853670cae89b4c244f
Date 2015-11-26T14:06:31.538Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by alexandrudima** [comment]
This is intentionally capped at 1000 to prevent slowness / lagging.

**Comment by yisibl** [comment]
@alexandrudima There is no better way to solve it?

**Comment by alexandrudima** [comment]
Sure there is, currently the decorations are implemented to take quite a lot of memory, plus the painting code has at least one O(N) where N is the number of lines instead of O(viewport). Especially in this case where they are computed on each keystroke, the decorations don't need to be tracked.

**Comment by gulshan** [comment]
Can ripgrep be useful here also?

**Comment by dijonkitchen** [comment]
Sounds like this can be closed after #36410!

**Comment by ToMakeSense** [comment]
After latest release v-1.58.0, a new setting search.maxResults was added via PR #126762, but when the selection is more than 10000, below warning notification still shows up
> The number of cursors has been limited to 10000.

**Comment by amunger** [comment]
this issue is about selection highlighting, rather than highlighting from the find widget, and still seems to be capped at 1000 for most cases.
I'm going to close this as the trade-off for performance/complexity is too high for the amount of votes this issue has.
