### ISSUE TITLE
Cannot download VS Code

### ISSUE THREAD

**Issue by reboozah** [microsoft/vscode#111060]
Hello, 

I am operating through Ubuntu on a flash drive as a VM. I downloaded the .deb file but I am getting the error "Failed to Install: Not supported". 
I am new at all of this so I am sure I am doing something wrong. I am not logged in to any VPN, I am my other OS is Windows 10. 

Thanks in advance!

**Comment by sean-mcmanus** [comment]
I'm hitting the same/similar issue "Failed to install file: not supported" on Ubuntu 20 aarch64.

**Comment by minchinchang0825work** [comment]
I met the same problem.

**Comment by sean-mcmanus** [comment]
I worked around the issue via installing the Raspbian/Debian 10 arm OS instead.

**Comment by Tyriar** [comment]
We only recently started supporting other architectures in the apt repo.
