### ISSUE TITLE
[themes] wait applying settings until user data initialization is completed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111009]
User settings can refer to themes that are not yet installed and are coming in through settings sync

**Comment by misolori** [comment]
@aeschli can you provide verification steps? Unsure how I should verify and what to look for. Thanks.

**Comment by aeschli** [comment]
- set a color theme that comes from an marketplace extension
- create a new codespace
- when the codespace is up, verify that the new theme is applied right away, no default theme first.

**Comment by meganrogge** [comment]
![recording (59)](https://user-images.githubusercontent.com/29464607/100924555-a9e41280-3495-11eb-8cf4-b9438adcb1bc.gif)
@aeschli is this how it should look? still a flash of white from the default color theme, but does get applied quickly thereafter.

**Comment by aeschli** [comment]
@meganrogge All looks good in the screencast.

**Comment by legomushroom** [comment]
Also verified this on the latest insiders 👍
