### ISSUE TITLE
Problem matcher with type "shell" randomly fails to match on Linux when the terminal is not "reused"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#111068]
- VSCode Version: 1.52.0-insider (also repros with 1.51.0)
- OS Version: Ubuntu 20 (via Windows/WSL)

Steps to Reproduce:

0. You may need to install gcc (sudo apt-get install gcc).
1. Open folder.
2. Create a test.c file with

```
int main(void) {
    int i;
    &printf("Hello");
    &printf("Hello");
    &printf("Hello");
    return 0;
}
```
3. Create a tasks.json with
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "build",
                        "type": "shell",
			"command": "/usr/bin/gcc",
			"args": [
				"-Wall",
				"${workspaceFolder}/test.c",
				"-o",
				"helloWorld"
			],
			"problemMatcher": {
				"owner": "cpp",
                               "source": "gcc",
				"fileLocation": [
					"autoDetect",
					"${workspaceFolder}"
				],
				"pattern": {
					"regexp": "^(.*?):(\\d+):(\\d*):?\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
					"file": 1,
					"line": 2,
					"column": 3,
					"severity": 4,
					"message": 5
				}
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
  }
```
If you're on VS Code non-Insiders, you'll need to save and Reload Window due to a bug that's fixed in Insiders.
4. Use Configure Default Build Task (I didn't originally think this was required because the tasks.json was already marked as isDefault).
5. Ctrl+Shift+B (Run Build Task).
6. You can repeat the repro via enter a key in the Terminal window and using Ctrl+Shift+B again (or doing a Reload Window, which is slower). Another alternative to repeat the repro is to use Ctrl+Shift+B quickly 2 times in a row (one time won't work).

Bug: The problem matcher gives random results 0-5.
![image](https://user-images.githubusercontent.com/19859882/99863071-55659c80-2b51-11eb-9ce4-2993646128fd.png)
![image](https://user-images.githubusercontent.com/19859882/99863052-3830ce00-2b51-11eb-8654-cf5d13d6605a.png)
![image](https://user-images.githubusercontent.com/19859882/99863160-bc835100-2b51-11eb-9adb-bff6d48408ec.png)
![image](https://user-images.githubusercontent.com/19859882/99863062-47178080-2b51-11eb-9f2a-eb0d8f38c753.png)

Note: Screenshot uses test2.c instead of test.c (it doesn't matter).

Does this issue occur when all extensions are disabled?: Yes
Repros with the C/C++ disabled or enabled. With the C/C++ extension disabled with the "cppbuild" task, the bug repros still and also doesn't require step 6 to "reset" the repro (i.e. you can just use Ctrl+Shift+B repeatedly).

**Comment by alexr00** [comment]
@sean-mcmanus thank you for the comprehensive repro steps. I'm not able to repro, but it sounds like it could be a terminal output/line-wrapping issue. 

Can you try setting `"terminal.integrated.windowsEnableConpty": false` and see if it still repros?

I've also just pushed a "fix" that could impact this. Could you try with the next (24 November) insiders build?

Finally, what version of Windows are you using?

**Comment by sean-mcmanus** [comment]
The bug is random, so you may need to repeat step 6 multiple times. I'm remoting to WSL 2 (Ubuntu 20.04), not sure if that's required (so I have the remote WSL extension and all other extensions are disabled). I tried all the repro steps again with the latest VS Code (1.51.1 and 1.52.0) and it still repros. I'm not sure if I have the build with your fix, but I'll try again tomorrow. My Windows version is show below.

Version: 1.52.0-insider (user setup)
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:56:29.761Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Also, I'm using `    "terminal.integrated.shell.linux": "/bin/bash",`

It still repros with `"terminal.integrated.windowsEnableConpty": false` too.

I added step 4 (Configure Default Build Task).

If you still can't repro it I could ask other people on my team if they're able to repro it.

**Comment by sean-mcmanus** [comment]
I also repro the bug on my Raspberry Pi 4 (Rasbian/Debian 10) with VS Code 1.51.1 running Linux ARM64/aarch64.

**Comment by alexr00** [comment]
@sean-mcmanus I'm still unable to repro. Can you try with the latest insiders, which has the fix I mentioned?

**Comment by sean-mcmanus** [comment]
Yeah, it's fixed with the latest Insiders, thanks (it repros with non-Insiders).

**Comment by sean-mcmanus** [comment]
But I hit another bug in the "same" scenario: https://github.com/microsoft/vscode/issues/111538
