### ISSUE TITLE
C color coding stops after line with specific syntax

### ISSUE THREAD

**Issue by sVathis** [Microsoft/vscode#11107]
[foo.zip](https://github.com/Microsoft/vscode/files/442500/foo.zip)

- VSCode Version: Code - Insiders 1.5.0-insider (92d3324e3d05a6d2b765c08651d89e9ec1d19f4c, 2016-08-29T06:09:51.858Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Unzip attached file
2. Open included foo.c
3. Goto line 93. All code after that line is not colored.

All extensions were disabled

Same behavior also occurs with standard Visual Studio Code Version 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679)

**Comment by sVathis** [comment]
Possibly related to #9937 or #11043?

**Comment by aeschli** [comment]
This works now again in the August build (to be release in the coming days)
