### ISSUE TITLE
[javascript].editor.tabSize not respected in workspace settings

### ISSUE THREAD

**Issue by taymonbeal** [microsoft/vscode#111083]
Issue Type: <b>Bug</b>

To reproduce:
1. Don't have any kind of `tabSize` in user settings.
2. Add to `.vscode/settings.json`:
```json
  "[javascript]": {
    "editor.tabSize": 2
  }
```
3. Save.
4. Open a `.js` file.

Expected behavior: Tab size is two spaces.

Actual behavior: Tab size is four spaces.

Note: Python doesn't have this problem; it is JavaScript-specific. (I am working around it by setting the non-language-specific `tabSize` to 2, which is respected in JavaScript, and then setting it to 4 for Python.)

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.7.17-1rodete4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 1900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|15.41GB (4.10GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 2f40d3aa-8368-4cda-9292-4b4e492e330b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.0.2
vscode-pull-request-github|Git|0.21.2
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
debugger-for-chrome|msj|4.12.11

</details>

**Comment by mjbvz** [comment]
Have you also set `"editor.detectIndentation": false`?

**Comment by taymonbeal** [comment]
I think that resolved the issue.
