### ISSUE TITLE
Documentation missing for extensionKind = web

### ISSUE THREAD

**Issue by joelspadin-garmin** [microsoft/vscode#111043]
- VSCode Version: 1.51.1
- OS Version: Windows 10 build 1809

In https://github.com/joelspadin-garmin/vscode-private-extension-manager/issues/26, we are trying to get an extension to run on web versions of VS Code. I see in https://github.com/microsoft/vscode/blob/master/src/vs/workbench/services/extensions/common/extensionsUtil.ts#L38-L41 I that the package manifest's `extensionKind` supports a value of `"web"`, so we added that to the end of the array and the extension appears to work when installed from a .vsix. However, in the issue linked above it was reported that trying to install the extension from the marketplace in a LiveShare browser session gives an error: "Cannot install 'Private Extension Manager' because this extension is not a web extension."

https://code.visualstudio.com/api/references/extension-manifest#fields does not document "web" as a possible value for `extensionKind`. Is the documentation for web extensions missing or is this intentionally undocumented?

**Comment by sandy081** [comment]
Yes, web kind is not officially support yet and is work in progress.
