### ISSUE TITLE
Native Notebooks - Hover Add Cell Target Too Small 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#111063]
We are still seeing feedback that hovering to add cells is tricky. (GitHub + Survey) 

https://github.com/microsoft/vscode-jupyter/issues/3997

There was an action item after our API sync to increase the target size for the hover add code cell/markdown cell icons. 
Is there an update on the status of that?

**Comment by kieferrm** [comment]
We should think about whether we want to show it at the same time when we show the cell menu. Deepnote is using this approach and it feel quite intuitive. Noisiness might be an issue though.

**Comment by roblourens** [comment]
I did make it bigger last time we were talking about it. We can make it bigger again or try what Kai suggests.

**Comment by misolori** [comment]
Add new cell toolbar is now visible on hover + focus

https://user-images.githubusercontent.com/35271042/102549477-fff9ae00-4070-11eb-9377-35ba367d4dd7.mp4
