### ISSUE TITLE
Test: ESLint

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11100]
Test for https://github.com/Microsoft/vscode-languageserver-node/issues/79
Complexity: 3

- [x] any OS - **@isidorn**
- [x] any OS - **@roblourens**

The module resolving algorithm to load the eslint library has been re-implemented. It now looks for the eslint module in the parent folder of the workspace folder as well. Frist install this ESLint extension 
[vscode-eslint-1.0.1.zip](https://github.com/Microsoft/vscode/files/443428/vscode-eslint-1.0.1.zip) as a side extension (**Note** you have to the zip to vsix). Then test from a workspace folder:

- that the eslint is correctly loaded from the workspace folder or any parent folder.
- that the eslint library is correctly loaded from a global npm location as well.
- install eslint lib at a custom location and point the setting eslint.nodePath value to it (if installed in a node_modules folder the node_modules name must be part of the path). Ensure that the eslint library can be loaded.
- install an eslint plugin and configure it in the .eslintrc.json file accordingly. Ensure that the eslint plugin gets loaded correctly as well as long as it is installed at the same 'location' (e.g. node_modules folder) as eslint library itself.

**Comment by isidorn** [comment]
@dbaeumer I would suggest this item is tackled by one more tester

**Comment by roblourens** [comment]
I tried setting `eslint.nodePath` to `.../node_modules/eslint` and `.../node_modules/.bin/eslint` before setting it to `.../node_modules`. I don't know if there's some way it could be flexible enough to work with the first one at least?

**Comment by dbaeumer** [comment]
@roblourens thanks for testing it. the nodePath variable works like the NODE_PATH env variable. So the correct path in your example would have been ../node_modules without the eslint. The reason being is that eslint could refer to plugins which are installed side by side with eslint itself.
