### ISSUE TITLE
Debugger does not show object property value 0

### ISSUE THREAD

**Issue by BuZZ-dEE** [microsoft/vscode#111030]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Datum: 2020-11-12T10:54:25.653Z
Electron: 9.3.4
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Linux x64 5.9.9-zen1-1-zen

Steps to Reproduce:

1. Inspect an object with property that has a number value of 0.

Screenshot:

![vscode_debugger_object_inspect_missing_property_value](https://user-images.githubusercontent.com/125954/99812534-dff4ce80-2b46-11eb-8f52-19351f426dba.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
I'm not able to reproduce this

![](https://memes.peet.io/img/20-11-1a9ffed0-1ab3-4450-9a2c-d5a6149e30b1.png)

Can you share a small sample repro case?

**Comment by BuZZ-dEE** [comment]
Maybe the order is relevant? In my screenshot, `id` is shown as first property.

```
0: {position: Object, groupId: null}
1: {id: 1, position: Object, groupId: null}
```

**Comment by connor4312** [comment]
That doesn't seem to make a difference for me
