### ISSUE TITLE
PROXY problem

### ISSUE THREAD

**Issue by hedgemaster29** [microsoft/vscode#111067]
"net::ERR_PROXY_CONNECTION_FAILED" message is displayed if I clicking update menu.
And also not able to use extensions. "We cannot connect to the extensions marketplace at this time, ..." This message is showed, when I search extensions.
At this time, I have checked error messages on console from toggle developer tool. "workbench.desktop.main.js:490 POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery net::ERR_PROXY_CONNECTION_FAILED"

It seems the reason is proxy. But I don't use any proxy. And also there is no proxy setting on visual studio code setting.

How could I solve this?
![image](https://user-images.githubusercontent.com/74005892/99863220-7d501100-2be0-11eb-8a06-c666b6cb7298.png)

**Comment by chrmarti** [comment]
This looks like you have a proxy configured in your OS. Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by hedgemaster29** [comment]
> This looks like you have a proxy configured in your OS. Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

Thank you for your replying.
I have attached some captures and netlog.json.

[netlog.zip](https://github.com/microsoft/vscode/files/5601107/netlog.zip)
![capture1](https://user-images.githubusercontent.com/74005892/100320369-6f492880-3004-11eb-9e6c-2456bb4de6bb.png)
![capture2](https://user-images.githubusercontent.com/74005892/100320372-7112ec00-3004-11eb-832b-6dfe7fc47d12.png)

Best Regards,
Eric./

**Comment by chrmarti** [comment]
@hedgemaster29 The log doesn't show any requests, could you capture another log and while you are capturing it try searching for extensions. That should give us some more output in the log. Thanks.
