### ISSUE TITLE
language specific file icons are not showing in explorer

### ISSUE THREAD

**Issue by nikhilpatel0** [microsoft/vscode#111079]
- VSCode Version: 1.51.1
- OS Version:  Windows 10 20H2 OS build 19042.630

Issue: File icons are not showing in explorer. before it was showing nice python icon but now its just blank white icon. I mean icon for different languages.
I tried installing latest 1.51.1 version in my other computer too (vs code never been installed in this computer before, this was first time) and I got same issue of No icon. here OS is Windows 10 1903

Edit: I uninstalled latest version completely by deleting user/'.vscode' folder and user/appdata/roaming/code and uninstalling VSCode and installed older version 1.50.1 and tried 1.49.3 versions. Both Issues are still there. plus second issue got resolved so editing it out.

![icon_issue](https://user-images.githubusercontent.com/74089733/99869402-c6a85c80-2bf0-11eb-88d4-2681dff64726.png)

Steps to Reproduce:

1. Just install latest version of VS Code and set it as always open with .py file

Does this issue occur when all extensions are disabled?: Yes

**Comment by nikhilpatel0** [comment]
![icon_issue](https://user-images.githubusercontent.com/74089733/99869387-a1b3e980-2bf0-11eb-9dc8-8cff53f5de7a.png)
![open_with_vscode_issue](https://user-images.githubusercontent.com/74089733/99869388-a2e51680-2bf0-11eb-9d2d-fe432ffd825b.png)

**Comment by nikhilpatel0** [comment]
Don't how and why but its working again. Issue resolved.

**Comment by isidorn** [comment]
Lovely
