### ISSUE TITLE
C++ debug session fails to use the GCC compiler argument -std=c++20 as specified in tasks.json

### ISSUE THREAD

**Issue by bshoshany** [microsoft/vscode#111048]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19042

**Overview: Launching a C++ debug session with F5 fails to use the correct compiler arguments as specified in `tasks.json`. However, launching the build tasks itself without debugging does work as intended.**

Steps to Reproduce:

1. Install GCC v10.2.0 via MSYS2.
2. Create a new workspace in an empty folder.
3. Create a file `hello.cpp` with a standard "Hello, World!" program:

```cpp
#include <iostream>

int main()
{
    std::cout << "Hello, World!\n";
}
```

4. Press F1, choose "C/C++: Edit Configurations (UI)", choose `g++` as the compiler, `gcc-x64` for IntelliSense mode, and `c++20` for C++ standard. A new `c_cpp_properties.json` file will be created. On my system, the automatically-generated contents of the file are as follows:

```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.18362.0",
            "compilerPath": "C:/Users/barak/MSYS2/mingw64/bin/g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

5. Go to Terminal > Configure Default Build Task and choose `g++.exe`. A new `tasks.json` file will be created. On my system, the automatically-generated contents of the file are as follows:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:/Users/barak/MSYS2/mingw64/bin/g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:/Users/barak/MSYS2/mingw64/bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "compiler: C:/Users/barak/MSYS2/mingw64/bin/g++.exe"
        }
    ]
}
```

6. Go to `hello.cpp` and press F5, choose "C++: GDB/LLDB" and `g++`. A new `launch.json` file will be created. On my system, the automatically-generated contents of the file are as follows:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Users\\barak\\MSYS2\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
```

7. "Hello, World!" will be printed successfully.

**Okay, so now let's introduce the bug:**

8. Add any C++20-only statements to the code. For example, I will add the "spaceship operator" `<=>` to the "Hello, World!" program:

```cpp
#include <iostream>

int main()
{
    if ((0 <=> 1) < 0)
        std::cout << "Hello, C++20!\n";
}
```

9. Press Ctrl+Shift+B to compile the program. The task will fail, as it should, since we have not given the argument `-std=c++20` to the compiler.
10. Add `-std=c++20` to the "args" section of `tasks.json`, i.e.:

```
"args": [
    "-g",
    "${file}",
    "-o",
    "${fileDirname}\\${fileBasenameNoExtension}.exe",
    "-std=c++20"
],
```

11. Go back to `hello.cpp` and press Ctrl+Shift+B to compile the program. Now it will compile successfully. Type "hello" in the integrated terminal and the string "Hello, C++20!" will appear.
12. Go to `hello.cpp` and press F5. **The pre-launch build task will now fail, even though `tasks.json` is configured correctly.**

The solution I found is to replace `"type": "cppbuild"` with `"type": "shell"` in `tasks.json`. To my understanding, `shell` indicates that the task should be treated as a generic shell command, while `cppbuild` is a task type specific to the C/C++ extension. Thus `shell` just takes the arguments as I wrote them, while `cppbuild` might be adding or removing arguments on its own, so perhaps for some reason it overrides the `-std=c++20` argument with something else. However, I explicitly specified in the C/C++ extension configuration (step 4) that the C++ standard should be C++20. So I assume this is actually a bug in the implementation of a `cppbuild` task. 

This seems to be specific to the `-std=c++20` compiler argument; other arguments I tried seem to work as intended for both building and debugging.

Possible temporary fix: **change the default type of automatically-generated tasks to `shell` instead of `cppbuild`.**

Does this issue occur when all extensions are disabled?: When disabling all extensions except the C/C++ extension (which is required to reproduce the issue), the issue still occurs.

**Comment by PookyFan** [comment]
I actually found a similar bug to yours and was just looking around to check if someone reported it already. But in my case, I found out that changing task name to some other than the default one would solve the issue. I wonder if it's caused by the same faulty implementation, or are these separate issues...?

**Comment by bshoshany** [comment]
Interesting... Indeed, I changed both `label` in `tasks.json` and `preLaunchTask` in `launch.json` to something else, and now it works without issues. Literally any label other than the default "C/C++: g++.exe build active file" works, as far as I can tell. Definitely seems like it's closely related to the bug I described.

**Comment by PookyFan** [comment]
I wonder if it makes sense to treat it as one issue, then. Definitely looks like some problem with executing tasks with default names.
My theory is that there are "built-in" tasks that are identified with default generated tasks names (try to remove task with default name from `task.json` but leave its name in `preLaunchTask` and see for yourself to see what I mean - it still will be launched). And most probably such built-in task has higher priority on lookup. Chances are that this weird lookup behavior applies only with `"type": "cppbuild"`, so that would explain why changing it to `"type": "shell"` solves it as well.

**Comment by bshoshany** [comment]
I think your theory is correct! Perhaps it could be fixed by allowing the user-created task in `tasks.json` to override any default tasks with the same name. Hopefully one of the developer can provide further insight.

**Comment by bshoshany** [comment]
I created microsoft/vscode-cpptools#6558 for this issue. This bug seems to be fixed in the latest Insiders build.
