### ISSUE TITLE
Disable cpuprofile files

### ISSUE THREAD

**Issue by thegamerx1** [microsoft/vscode#111038]
option to disable the creation of `.cpuprofile` files when unresponsive extension.
I already have 8 files in 2 days

![image](https://user-images.githubusercontent.com/34986564/99821583-85fa0600-2b52-11eb-98ef-56dccc4d188c.png)
![image](https://user-images.githubusercontent.com/34986564/99821778-bc378580-2b52-11eb-8cc1-54f6659577df.png)

2020/11/21: 11 files (3,22mb)
2020/11/23: 22 files (7.11mb)

**Comment by roblourens** [comment]
Would be great if you could file issues for these slow extensions as well! 😉

**Comment by jrieken** [comment]
That's like saying "disable error logging". When CPU profiling for the extension host happen then that's your smallest problem because it basically means your extension host is unresponsive for seconds.

**Comment by thegamerx1** [comment]
Disabling error logging would be disabling the console not disabling a useless file creation that the only thing that does is wasting drive writes
