### ISSUE TITLE
Reindent Lines does nothing if indentationRules do not exist

### ISSUE THREAD

**Issue by andycraig** [microsoft/vscode#111088]
Issue Type: <b>Bug</b>

Hi, command `Reindent Lines` seems to do nothing when a language configuration does not include `indentationRules`. This is a little bit surprising because 'If there is no indentation rule set for the programming language, the editor will indent when the line ends with an open bracket and outdent when you type a closing bracket' (from https://code.visualstudio.com/api/language-extensions/language-configuration-guide ). So there is default indentation as you type, but no default indentation using the `Reindent Lines` command. Perhaps this is intentional rather than being a bug, in which case it might be good to document it at https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Examples**

To demonstrate this, I made a couple of small examples by modifying https://github.com/microsoft/vscode-extension-samples/tree/master/language-configuration-sample

1. Download https://github.com/andycraig/vscode-extension-samples/tree/language-with-indentationRules then open 'language-configuration-sample' and 'Start Debugging' (<kdb>F5</kbd>)
1. Create a file 'temp.abcdef' with the following content:

    ```
    x {
    1
    }
    ```

1. Run command `Reindent Lines`. Note that the '1' is indented.
1. Now download https://github.com/andycraig/vscode-extension-samples/tree/language-without-indentationRules (which has no `indentationRules`) then open 'language-configuration-sample' and 'Start Debugging' (<kdb>F5</kbd>)
1. Create the same file 'temp.abcdef' as above
1. Run command `Reindent Lines`
    **Expected:** The '1' is indented
    **Actual:** Nothing happens

VS Code version: Code - Insiders 1.52.0-insider (caf01baa45b9816e2e1d8a2de22b40cf89459c03, 2020-11-20T07:26:12.345Z)
OS version: Linux x64 4.15.0-123-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (0.61GB free)|
|Process Argv|--disable-extensions --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30226747
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by andycraig** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> Reindent Selected Lines command bug? (#51458)

Not the same issue.

**Comment by rebornix** [comment]
Thanks for the feedback, it's intentional that we don't perform any operation when there is no indentation rules for command "Reindent Lines" as that would lead to more bugs than goodness.
