### ISSUE TITLE
Hovers from other extension not shown while in debug mode

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#111085]
vscode 1.51.1

1. Having installed an extension that shows hovers.
2. Go into debug mode.
3. Hover

The hover results from the installed extension are not shown. Only the debug hovers.

This is most probably by design. But is there a way to show the hovers.
Maybe an option or something that the extension needs to define.

**Comment by gjsjohnmurray** [comment]
What happens if you hold the Alt key down when hovering?

**Comment by maziac** [comment]
Aah, that's a good one. Didn't know about that.
Is it documented somewhere? I tried to search the internet but didn't find it. Maybe you can point me to somewhere that documents it. I guess there is also more interesting stuff :-)

And: is there maybe an option to enable it by default in the preferences. To show both hovers.

**Comment by isidorn** [comment]
Now we have added a tip in the latest vscode insiders.
For now we will not add the option. We want to have the tip in stable for a couple of milestones so users discover this more easily. Thus for now closing this. Thanks

![image](https://user-images.githubusercontent.com/1926584/99943320-642a9a00-2d71-11eb-9602-9c0e4f263730.png)
