### ISSUE TITLE
[VS Code 1.52 Insider ] - Editor Title Menu does not update/change icon

### ISSUE THREAD

**Issue by L13** [microsoft/vscode#111034]
Issue Type: <b>Bug</b>

Hi,

I found a bug which is easy to reproduce but difficult to explain. The bug is not in VS Code 1.51.1 and before.

**Steps to reproduce**

1. Download and install my extension Diff Folders https://marketplace.visualstudio.com/items?itemName=L13RARY.l13-diff
2. Open the webview panel with Ctrl+L Ctrl+L on Windows/Linux or Cmd+L Cmd+L on macOS. Or click the first icon (Diff Folders) in the favorites view.
3. In the top right corner you will see 5 icons (left to right):
	1. Add to Favorites
	2. Ignore End of Line
	3. Trim Leading/Trailing Whitespace
	4. Split Editor Right
	5. More Actions...
4. Press the 3rd icon (Trim Leading/Trailing Whitespace) multiple times and it changes.
5. Press the 2nd icon (Ignore End of Line) multiple times and it changes once or none. <- This is an unexpected behaviour

The weird part is the behaviour. If the config for `l13Diff.ignoreEndOfLine` is `false` and you press the 2nd icon (Ignore End of Line) the value changes to `true` (see settings) but the icon doesn't. If you now quit VS Code and start the app again, the right icon appears. If you press the icon it changes. If you press it again, it doesn't.

**Expected behaviour**

The 2nd icon should also toggle like the 3rd one. This bug is not in VS Code 1.51.1 and before.

**Additional information**

The commands and when clauses for the 2nd icon to toggle `l13Diff.ignoreEndOfLine` are

```json
{
	"contributes": {
		"menus": {
			"editor/title": [
				{
					"command": "l13Diff.ignoreEndOfLine",
					"when": "l13DiffFocus && !config.l13Diff.ignoreEndOfLine",
					"group": "navigation@3"
				},
				{
					"command": "l13Diff.compareEndOfLine",
					"when": "l13DiffFocus && config.l13Diff.ignoreEndOfLine",
					"group": "navigation@3"
				}
			]
		}
	}
}
```

The commands and when clauses for the 3rd icon to toggle `l13Diff.ignoreTrimWhitespace` are

```json
{
	"contributes": {
		"menus": {
			"editor/title": [
				{
					"command": "l13Diff.ignoreWhitespace",
					"when": "l13DiffFocus && config.l13Diff.ignoreTrimWhitespace == 'default' && !config.diffEditor.ignoreTrimWhitespace",
					"group": "navigation@4"
				},
				{
					"command": "l13Diff.ignoreWhitespace",
					"when": "l13DiffFocus && config.l13Diff.ignoreTrimWhitespace == 'off'",
					"group": "navigation@4"
				},
				{
					"command": "l13Diff.compareWhitespace",
					"when": "l13DiffFocus && config.l13Diff.ignoreTrimWhitespace == 'default' && config.diffEditor.ignoreTrimWhitespace",
					"group": "navigation@4"
				},
				{
					"command": "l13Diff.compareWhitespace",
					"when": "l13DiffFocus && config.l13Diff.ignoreTrimWhitespace == 'on'",
					"group": "navigation@4"
				}
			]
		}
	}
}
```

It seems that the change of `config.l13Diff.ignoreEndOfLine` to `true` is not recognized, but `config.diffEditor.ignoreTrimWhitespace` works?

VS Code version: Code - Insiders 1.52.0-insider (caf01baa45b9816e2e1d8a2de22b40cf89459c03, 2020-11-20T07:35:38.417Z)
OS version: Darwin x64 19.6.0

**Comment by mjbvz** [comment]
Please provide a minimal example extension that reproduces this issue

**Comment by L13** [comment]
Hi, I created an example extension which you can checkout here https://github.com/L13/vscode-bugs (master branch)

**Description**

After the extension has started the source of the extension will be opened in an editor. In the top right corner you will see 2 additional icons like in the image below. If you click the left one (Ignore End of Line) multiple times it will toggle once or none. The right one (Ignore Leading/Trailing Whitespace) will toggle always. But the left one should also toggle always but it doesn't. This issue was not in version 1.51.1 and before. I recognized the bug on November 13th for the first time and it did not appear in the insider version on November 11th.

![Editor Title Menu](https://raw.githubusercontent.com/L13/vscode-bugs/master/images/editor-title-menu.png)

**Additional information**

* If the group `navigation@1` will be changed to `navigation@3` the bug does not appear.
* Or if `config.l13Bug.ignoreTrimWhitespace == 'default'` will be removed in the when clause the bug does also not appear.

**Comment by L13** [comment]
Hi, let me know if you need more details or if you have any questions.

The simplified example I have created in the message above shows what the issue causes. The exact order of these two when clauses are breaking the update of the icons in the editor title menu.

Thank you in advance.

**Comment by L13** [comment]
Hi, the bug does not appear anymore. It seems someone fixed it. Thank you. So I will close the ticket.
