### ISSUE TITLE
Python raw_input and input

### ISSUE THREAD

**Issue by Qiudays** [Microsoft/vscode#11103]
- VSCode Version:1.4.0
- OS Version:win7 x64

Steps to Reproduce:

1. Python 的 raw_input 和 input 函数没法交互执行。

**Comment by dbaeumer** [comment]
@Qiudays can you please provide more context about what is not working. I don't understand what `Python 的 raw_input 和 input 函数没法交互执行。` means.

**Comment by dbaeumer** [comment]
@Qiudays  Closing since I haven't received any response. Please ping if you can still reproduce the issue with steps that demonstrate the problematic behavior.

**Comment by hawkerm** [comment]
Think they mean that by default in the integrated debug console or even the integrated terminal raw_input with Python debugging behaves differently than running in the Python interpreter itself.

For instance if you have a Python 2 program with donjayamanne.python extension such as:
````
x = raw_input()
print x
````

By default hitting F5 and running in the Debug Console will never get past the raw_input statement as the Debug Console doesn't seem to forward the input from the > prompt to the program.

If you change your launch.json config to change 'console' to 'integratedTerminal' than it works better but if you look at the output of raw_input it has an added '\r' to the end of it which you don't see in the normal Python interpreter.
