### ISSUE TITLE
Colorization Broken - Cannot disable Code Lens References 

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/vscode#111036]
Issue Type: <b>Bug</b>

When the Code Lens References annotation shows 0 references, it causes the colorization of my code to appear grey. Very ugly.
Not having found a way to prevent this, other than turning off Code Lens in the Editor, which I don't wish to do, I am attempting to disable References settings.

"java.referencesCodeLens.enabled": false

However, it remains Enabled. 
1. Go to Settings and search for References
2. Choose Java and uncheck Enable/Disable the references code lens. 
3. Notice It remains Enabled. 

Here you see java colorization is normal.
![image](https://user-images.githubusercontent.com/20051/99820712-fdee0f00-2b05-11eb-9c44-23a2cd02afde.png)

After scrolling up where the 0 references annotation appears, the colorization turns ugly.
![image](https://user-images.githubusercontent.com/20051/99820868-2ece4400-2b06-11eb-83e8-bfdf0841e037.png)

Notice in the settings screen on the right that References is **Enabled**, even though the checkbox is off.

---

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (2.24GB free)|
|Process Argv|--crash-reporter-id 161e5da9-f592-4143-baa2-0a9d01a1bfab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
atlascode|atl|2.8.5
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
quick-html-previewer|dai|1.0.1
vscode-dotnet-auto-attach|Den|1.1.1
githistory|don|0.6.14
gitlens|eam|11.0.2
vscode-html-css|ecm|0.2.3
tslint|eg2|1.0.44
LogFileHighlighter|emi|2.10.0
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|5.8.0
vscode-firefox-debug|fir|2.9.1
text-transform|flo|0.1.0
auto-close-tag|for|0.5.9
go|gol|0.18.1
gc-excelviewer|Gra|3.0.40
gitflow4code|Gre|1.2.3
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.1
intellij-idea-keybindings|k--|0.2.41
dotnet-core-essentials|Kis|0.0.8
typelens|kis|1.9.6
csharpfixformat|Leo|0.0.84
git-graph|mhu|1.27.0
vscode-docker|ms-|1.8.0
csharp|ms-|1.23.6
mssql|ms-|1.9.0
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.1.2
js-debug-nightly|ms-|2020.11.1117
sublime-keybindings|ms-|4.0.7
vscode-typescript-next|ms-|4.2.20201119
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
vetur|oct|0.30.2
vscode-jest|Ort|3.2.0
vsnotes|pat|0.7.1
material-icon-theme|PKi|4.4.0
typescript-hero|rbb|3.0.0
toggle|reb|0.0.1
java|red|0.71.0
vscode-yaml|red|0.13.0
vs-code-prettier-eslint|rve|0.3.2
preview-vscode|sea|2.2.5
vscode-hexdump|sle|1.8.1
msbuild-project-tools|tin|0.3.10
vscode-workspace-explorer|tom|1.5.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
gitblame|wad|6.0.0
material-theme|zhu|3.9.6

</details>

**Comment by dfdumaresq** [comment]
The actual problem is that the colorization seems broken when there are zero references to the code item, so I have changed the title.

**Comment by roblourens** [comment]
Please file this issue in the repo for the Java extension

**Comment by dfdumaresq** [comment]
Hi Rob

The issue is not specific to Java or the file type. I can reproduce it with a .tsx file.
IMO, It is an issue with code lens and how it colors methods that have zero references.
However, I should be able to disable this setting but cannot.
Should I provide you with an example of another file type?
---
Dave

On Nov 21, 2020, at 11:32 AM, Rob Lourens <notifications@github.com> wrote:

﻿

Please file this issue in the repo for the Java extension

**Comment by roblourens** [comment]
Sure, it would be easier for me to follow with a TS example. I wouldn't think that codelens affects colorization

**Comment by dfdumaresq** [comment]
Here's an example with a TS file, in which I invalidated the exported interface (IInstitutionDetails) by adding a 1 causing it to have zero references. It previously had 27 and each of its properties have been greyed out.

![image](https://user-images.githubusercontent.com/20051/99925304-7fa29000-2cf2-11eb-876a-5b971ad59ddd.png)

Turn on/off with Code Lens in Settings
![image](https://user-images.githubusercontent.com/20051/99925482-356dde80-2cf3-11eb-8ef9-2d4581773efa.png)

Code Lens Off
![image](https://user-images.githubusercontent.com/20051/99925550-6e0db800-2cf3-11eb-9a6c-79dbfa527e2d.png)

**Comment by alexdima** [comment]
This is the graying out caused by "unused symbols". I don't know why the graying out is so strong in this case, but it could be caused by some specific theme or by some color customization.

**Comment by dfdumaresq** [comment]
At this point, I would just like to disable References in Code Lens. 
From Settings, search term "code lens references"
![image](https://user-images.githubusercontent.com/20051/100048415-98ca4000-2dc9-11eb-9551-3c1554f2e49c.png)
For any language, the References Code Lens state always says **Enabled**
With TypesScript for example, if I check the checkbox on or off and copy the setting as JSON, I see the correct JSON. 
Off
- "typescript.referencesCodeLens.enabled": false
On
- "typescript.referencesCodeLens.enabled": true
Off
- "typescript.referencesCodeLens.enabled": false

But the Code Lens 'References' annotation in the code is always is shown. So the Enabled state in the Settings cannot be trusted. Unless I uncheck this one: Editor: Code Lens (Controls whether the editor shows CodeLens)
![image](https://user-images.githubusercontent.com/20051/100048725-5c4b1400-2dca-11eb-981e-24e4850eabd5.png)

**Comment by mjbvz** [comment]
@alexdima Unused code makes the text more transparent. We have't greyed out code for a long time (only was in one or two releases when the unused feature first rolled out)

@dfdumaresq I can't reproduce the reference code lens settings not working. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by dfdumaresq** [comment]
@mjbvz - it does work correctly with the latest VC Code insiders build.

Here you can see I've renamed the IInstitution interface by adding 1 and 0 references shows up as grey while the actual code remains colourized.
![image](https://user-images.githubusercontent.com/20051/100142883-5a746580-2e49-11eb-92ea-7ac098049819.png)

**Comment by dfdumaresq** [comment]
Ok - I have found the culprit. After disabling TypeLens (kisstkondoros.typelens) I have a clean colourized file with 0 references.
![image](https://user-images.githubusercontent.com/20051/100148906-3f5a2380-2e52-11eb-8973-eb362cdfc4d3.png)

**Comment by alexdima** [comment]
@dfdumaresq Please report the issue also to `kisstkondoros.typelens`.
