### ISSUE TITLE
selecting text highlights match only if the length is less than or equal to 200

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#111002]
Issue Type: <b>Bug</b>

steps to reproduce:
1. create a string with more than 220 characters and copy it to next line a couple of times
2. select the text from first string from 1st character upto 200th character
3. upto 200th character the selection gets highlighted.
![image](https://user-images.githubusercontent.com/9264813/99767421-0572df80-2b29-11eb-9ec6-08fb4276354d.png)

4. once you select char 201 the selection highlight will vanish.
![image](https://user-images.githubusercontent.com/9264813/99767388-f724c380-2b28-11eb-894e-4cd55ef7610c.png)

expected result:
the selection highlight should have a limit >200 or user should be able to configure it to some value.

when selecting text in vscode matches for the selected text gets highlighted and are distinctly visible. this is very useful when comparing between large string data. however i found out this only works if the selection is 200 characters or less. this 200 character limit is enough for most of the cases however ever so often i run into string which are way more than 200 char threshold. can this limit be configured in some way?

VS Code version: Code - Insiders 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51, 2020-11-19T05:37:52.577Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.82GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.1
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.1
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.7.2
output-colorizer|IBM|0.1.2
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-next|ms-|4.2.20201119
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vscode-jest|Ort|3.2.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
sonarlint-vscode|Son|1.18.0
code-spell-checker|str|1.10.0
vscode-stylelint|sty|0.85.0
vscodeintellicode|Vis|1.2.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30222199
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244cf:30226748
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by alexdima** [comment]
At this time this is a hard coded limit to protect against UI freezes -- https://github.com/microsoft/vscode/blob/acfd724aacb10e81ca71e1d49ee9025c24a595b3/src/vs/editor/contrib/multicursor/multicursor.ts#L923-L926
