### ISSUE TITLE
PDF Preview in VS Code

### ISSUE THREAD

**Issue by septatrix** [microsoft/vscode#111125]
I know a corresponding issue already exists: #110989.
The issue however way locked and moved into the backlog.

While I think the decision was correct at the time (the PDF plugin did not work in electron > 3) I vote to reopen this issue.
My reasoning is that newer electron versions ([changelog v9](https://www.electronjs.org/blog/electron-9-0)) enabled the PDF plugin again.
Current extensions providing a PDF viewer have to ship PDF.js or a similar solution.
Providing this natively should yield better performance and a better out-of-the-box experience while only needing small changes to the code.

**Comment by septatrix** [comment]
I kindly disagree. I have already pointed out what benefits native support for the PDF plugin brings with it. The only required change would be to pass `plugins: true` in the options object to BrowserWindow and then extensions would be able to use the native PDF viewer which has multiple benefits in comparison to pure js-based pdf viewers.

**Comment by septatrix** [comment]
@mjbvz would you mind explaining your decision?

**Comment by mjbvz** [comment]
> We try to keep VS Code lean and we think the functionality 

Pretty much this... plus the inevitable long tail of pdf related bugs

**Comment by septatrix** [comment]
As far as I know it would not require any changes beside adding the above flag. The PDF viewer is bundled by electron anyhow so it would not make the executable bigger. All PDF related bugs (of which there are only a rarely some inside the electron repo) could instantly be labeled as an upstream issue and do not need to bother VSCode directly. Implementing any handling of PDF files and an optional nice UI would still be the task of extension developers. However they would not need to bundle pdf.js or a similar library anymore but would instead be able to use the PDF viewer which electron provides but is only disabled - the reasons of which were only relevant for electron < 3 and are not applicable anymore.

**Comment by septatrix** [comment]
Sadly I am not sure you understood the goal of the feature request... :/
