### ISSUE TITLE
WSL2: vscode can't open files when called with vscode://vscode-remote/wsl+dist/path/file[:line] , but does open folders

### ISSUE THREAD

**Issue by circulosmeos** [microsoft/vscode#111188]
- VSCode Version: 1.51.1 (commit e5a624...) (user setup) with WSL-remote 0.51.4
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1a. Use symfony in a distro under WSL2, with "xdebug.file_link_format=vscode://vscode-remote/wsl+distro/%f" line in php.ini
1b. or just paste vscode://vscode-remote/wsl+distro/file_path on firefox browser from Windows
2. vscode opens, attach correctly to WSL Ubuntu-20.04 with Remote-WSL plugin, but file is silently not opened
   without any output on popup or to "problems", "output", "debug" or "terminal" windows.
3. if instead of a file, **a folder path is indicated, then the folder is correctly opened**
4. if a **file with a line number (.../%f:%l in php.ini or .../file:# in browser) is indicated, an error is raised**:
	Unable to open 'file:10': Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/user/file:10' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/home/user/file:10').

Note that last comment in https://github.com/microsoft/vscode/issues/99691 indicates that this should work:
	> To open a remote window, don't use file but vscode-remote. Please try
	> vscode://vscode-remote/wsl+distro/path/to/file

- VSCode Version: 1.52.0-insider (commit 6026ab...) (user setup) with WSL-remote 0.51.4
- OS Version: Windows_NT x64 10.0.19042

On same steps, 1.52.0-insider DOES NOT correctly connect to WSL environment and opens an empty file because of this.

Without using WSL-remote integration, paths like "vscode://file//wsl$/distro/path/to/file"
do correctly open the file (two slashes after "*vscode://file*"!),
and also "vscode://file//wsl$/distro/path/to/file:line" goes to that line number.

Does this issue occur when all extensions are disabled?: WSL-remote **must** be enabled

**Comment by aeschli** [comment]
Sorry, opening remote files is currently not supported. https://github.com/microsoft/vscode/issues/108257 is the issue for it.
