### ISSUE TITLE
VSCODE crashes

### ISSUE THREAD

**Issue by oneplusdash** [microsoft/vscode#111112]
Issue Type: <b>Bug</b>

When compiling a large VUE project, once VSCODE is operated, it will crash (OOM)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.13GB free)|
|Process Argv|--crash-reporter-id 4ee9cf09-5581-4e4c-a83f-1a1e15a5a562|
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-ant-design-vue-helper|ant|1.0.6
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.8.0
vscode-language-pack-zh-hans|MS-|1.51.2
vsliveshare|ms-|1.0.3206
vetur|oct|0.30.2
LiveServer|rit|5.6.1

</details>

**Comment by roblourens** [comment]
Please give more details about what you are doing and what you see. It sounds like this might be related to your compile task or your machine more than vscode

**Comment by oneplusdash** [comment]
At the time I was compiling my Vue project, and some computers with the same configuration would crash when running the same project, while others would not. The memory and CPU usage of all computer memory before running are the same

**Comment by ericis** [comment]
I can replicate:

Using Windows 10 **with WSL 2 and Ubuntu 20**...

_Crashes with 32 GB of RAM!_

1. Clone https://github.com/ourchitecture/panda
2. Open in VS Code
3. Open terminal to WSL2 bash prompt
4. `cat .yarn/releases/yarn-berry.cjs` _1.56 Mb_
5. "oom" Crash! 💥

Here is a timeline of the memory issue. The slow increase occurs after the `cat` command above. The crash is obviously where VS Code gives up and crashes itself as "oom".

![image](https://user-images.githubusercontent.com/974919/107408506-13595080-6ad9-11eb-94dc-f6a6c93e7d4c.png)

**Comment by deepak1556** [comment]
1) Do you see this issue when you start with `--disable-extensions` ?

2) Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and provide the crash dumps.

3) If you see the issue even after disabling extensions, can you follow these steps to get a memory profile.

* Toggle developer tools
* Go to `Memory` tab
* Check `Allocation Instrumentation on Timeline` along with `Record allocation stacks`
* Capture for a few seconds as you see the memory increase in the process explorer
* Attach the profile.
