### ISSUE TITLE
Add an option to prevent copying an empty selection

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#11112]
Like the title says, when nothing is selected, copying shouldn't copy a blank character.

**Comment by ramamurthynagaraj** [comment]
@alexandrudima @ivancuric 
As of now, cmd+c without any selection, copies the entire line. Sublime also does the same. 
Are we suggesting to change this behavior as part of this issue? I really like the current functionality.
Or are we suggesting one more option/flag which user can enable to have the new functionality?

**Comment by alexandrudima** [comment]
@ramamurthynagaraj Yes, it would be behind an option

**Comment by soljohnston777** [comment]
Can we have the option for this behavior or disable it?   I don't like the auto copy of a blank line and would like to disable that feature.    I agree it can be annoying especially in the type of coding I do (debugging).

**Comment by soljohnston777** [comment]
Was a setting added for this?

**Comment by alexandrudima** [comment]
@soljohnston777 it is `editor.emptySelectionClipboard`

**Comment by AlexLomm** [comment]
`"editor.emptySelectionClipboard": false` disables the line copying entirely. Is there a way to have line copying enabled, **while simultaneously** ignoring the empty lines?

**Comment by TashaRolland** [comment]
This doesn't disable the copying within my VS Code at all - anyone else had any luck? :)
