### ISSUE TITLE
Test lazy WorkspaceSymbolProvider

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11113]
- [x] any **@joaomoreno**

tests #890

Test that you can now implement a 'lazy' workspace symbol provider. That is one that returns incomplete symbol information but offering a `resolve` method that is invoked when a symbol is selected in the UI.

**Comment by jrieken** [comment]
FYI - to test against the latest API do the following:

* open your extensions `package.json` file
* change the `engine.vscode` property to `*`
* run `npm run postinstall` (assuming you have the `vscode` module as dev-dependency)
* undo the engine-version change from step 2

**Comment by joaomoreno** [comment]
Thanks for the tip on the `engine` change!
