### ISSUE TITLE
Support multiple cursors across multiple code editors

### ISSUE THREAD

**Issue by SalsaGal** [microsoft/vscode#111120]
If I have two windows open at once and I option-click in seperate windows to make multiple cursors, it just defocuses the first window and makes only one cursor in the second window. I think it should allow this multiple selection so that you can edit large stretches of text across several files.

**Comment by roblourens** [comment]
Do you mean separate vscode windows or separate editors within one vscode window? Which OS?

**Comment by SalsaGal** [comment]
I'm on Mac, and yeah several editors in the one window.
