### ISSUE TITLE
Windows - Taskbar entry context menu is empty

### ISSUE THREAD

**Issue by NCC1701M** [microsoft/vscode#111177]
The "Jump List" context menu doesn't work correctly. The recent folders / files are missing and won't be added and also the other short cuts like "New Window" is missing.

![grafik](https://user-images.githubusercontent.com/7260053/99970287-e465f500-2d9b-11eb-8f2f-86b4cc1417d0.png)

Windows: 
- Window 10 (x64)
- Version 1909
- Build 18363.1198

VSCode:
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by egamma** [comment]
/needsMoreInfo

By 'JumpList' do you refer to the menu shown in the taskbar for VS Code. Pls provide steps for what you do in VS Code and what you expect to be shown in this menu.

**Comment by NCC1701M** [comment]
> 
> 
> /needsMoreInfo
> 
> By 'JumpList' do you refer to the menu shown in the taskbar for VS Code. Pls provide steps for what you do in VS Code and what you expect to be shown in this menu.

Well I do nothing in VSCode. I right click on the Icon and there is only that what you see in the screen shot above. There are no more project folders listed I recently opened and there are no more tasks like "New Window" which was always there.

Attached you'll find a screenshot of the windows insider context menu where the Task still exists.

![grafik](https://user-images.githubusercontent.com/7260053/100056472-0441fb00-2e26-11eb-8c90-d85558fcadee.png)

**Comment by bpasero** [comment]
If it works in insiders but not in stable this is probably a configuration problem with windows. I suggest to file a bug report against wondoofs.

**Comment by NCC1701M** [comment]
@bpasero 
This is an old insiders version! So I wouldn't be sure that it is a Windows problem. Please reopen for further investigation.

Version of Insiders:
Version: 1.41.0-insider (user setup)
Commit: 0d728c31ebdf03869d2687d9be0b017667c9ff37
Date: 2019-11-12T05:39:58.193Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by bpasero** [comment]
So why can't you update your versions of VSCode to latest?

**Comment by NCC1701M** [comment]
I have the latest Code version! At least Code doesn't show me that there is an update. So I guess, as far as there is noc problem with Codes update functionallity I have the latest Code version.

Only the Insiders version is an old one - as I mentioned above because I've installed it for some test reasons some months ago and didn't used it since then. I only used the Screensho to show what's missing at "normals" code context menu!

**Comment by bpasero** [comment]
Can you install latest insiders then and check if the issue persists?

**Comment by bpasero** [comment]
Also maybe completly uninstall and reinstall the stable one.

**Comment by NCC1701M** [comment]
> 
> 
> Can you install latest insiders then and check if the issue persists?

I have installed latest insider. It's still working
Version: 1.52.0-insider (user setup)
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:56:29.761Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363



> 
> 
> Also maybe completly uninstall and reinstall the stable one.

Done, but no changes

**Comment by bpasero** [comment]
So it works in insiders but not in stable? Then I guess we fixed it?

**Comment by NCC1701M** [comment]
🤷‍♂️ This can only be answerd when insider becomes stable.

Maybe some settings are corrupt. Where does the "New Window" entry comes from? Is it set up in the registry or any config file?

**Comment by bpasero** [comment]
@NCC1701M we use Electron API for that, so even if it is still broken, I do not see how we can fix it. https://github.com/electron/electron/blob/7-0-x/docs/api/app.md#appsetjumplistcategories-windows

**Comment by NCC1701M** [comment]
@bpasero As far as I understand this API call, you have to feed it with the categories (and additional entries?) Where is this happen? Where did you geht the entries/categories from? Are they hard coded? Are they from some kind of config file?

**Comment by bpasero** [comment]
We do it here:

https://github.com/microsoft/vscode/blob/ca4dd67abe11321dc977f8396616ff5e5714dfee/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L388-L388

**Comment by NCC1701M** [comment]
So, as a Workaround: When I delete all "openedPathsList" entries of your storage.json so that it looks like that:
```json
{
// ...
    "openedPathsList": {
        "workspaces3": [],
        "files2": []
    },
// ...
}
```

Then it works. All recently opened files and folders are gone but the tasks are back.

![grafik](https://user-images.githubusercontent.com/7260053/100315388-dccf6780-2fb8-11eb-93ba-e58c95894cc3.png)

And when I open files and folders the will be added again.

![grafik](https://user-images.githubusercontent.com/7260053/100315666-4ea7b100-2fb9-11eb-99ca-9676036629cd.png)

My guess is, that somewhere in your code an unhandled exception occurs in the code before
https://github.com/microsoft/vscode/blob/ca4dd67abe11321dc977f8396616ff5e5714dfee/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L387-L391

Maybe you should extend your try catch to the whole method and when an exception is catched you should still add ad least the default task(s).

https://github.com/microsoft/vscode/blob/ca4dd67abe11321dc977f8396616ff5e5714dfee/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L317-L330

So please reopen this bug

**Comment by bpasero** [comment]
@NCC1701M good findings, can we please verify your theory by checking the logs and finding the `#setJumpList` entry in the electron main logs? Should be accessible when you open the this log file from the output panel:

![image](https://user-images.githubusercontent.com/900690/100317084-063dc280-2fbc-11eb-831e-297da9aab216.png)

If we find out that the error is hit, we can continue to look into a fix.

**Comment by bpasero** [comment]
Btw at least when I try with WSL (which is also somewhat a remote container), my JumpList shows the entries still properly:

![image](https://user-images.githubusercontent.com/900690/100317339-78160c00-2fbc-11eb-87a0-ceb0ae2c06f6.png)

**Comment by NCC1701M** [comment]
> Btw at least when I try with WSL (which is also somewhat a remote container), my JumpList shows the entries still properly:
> 
> ![image](https://user-images.githubusercontent.com/900690/100317339-78160c00-2fbc-11eb-87a0-ceb0ae2c06f6.png)
> 

For some time, it worked for me as well and suddenly all was gone. Maybe the vscode-remote uri is corrupt or something like this.

**Comment by bpasero** [comment]
OK let's keep an eye open and let me know when this comes back, for now I am not going to push any changes because I am not sure this error case is actually triggered after all.

**Comment by NCC1701M** [comment]
> @NCC1701M good findings, can we please verify your theory by checking the logs and finding the `#setJumpList` entry in the electron main logs? 

I couldn't find the entry. So I think I might be right, that it happens before the try...catch block

**Comment by bpasero** [comment]
Ok too bad, I fear there is not a lot we can do then from our code.

**Comment by NCC1701M** [comment]
> 
> 
> Ok too bad, I fear there is not a lot we can do then from our code.

Well, at least putting the try to the top of the method could help, maybe it happens in `getRecentlyOpened` or some other methods which will be called within this method.

**Comment by bpasero** [comment]
Sounds good, added via https://github.com/microsoft/vscode/commit/5e6a2779f63c3a1a5d770498c4ead5fd8f34859a. Closing this issue but please give it a try starting tomorrow from our insider build, curious if you find any error in the logs.

**Comment by NCC1701M** [comment]
> Sounds good, added via https://github.com/microsoft/vscode/commit/5e6a2779f63c3a1a5d770498c4ead5fd8f34859a. Closing this issue but please give it a try starting tomorrow from our insider build, curious if you find any error in the logs.

Until now, the last insider update was from yesterday around 7am UTC so I'll test it on Monday

**Comment by bpasero** [comment]
Should try with https://github.com/microsoft/vscode/pull/111545#issuecomment-739791422

**Comment by bpasero** [comment]
I am able to reproduce and filed https://github.com/electron/electron/issues/26862 which is the underlying issue in Electron. In VSCode we should be able to workaround this by truncating the description part.
