### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by dhairyak-20** [microsoft/vscode#111174]
Issue Type: <b>Bug</b>

The code which I run and view on chrome is showing a favicon from my personal images but I have not set any favicon in my code so it should not show any favicon

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (2.44GB free)|
|Process Argv|C:\Users\C2IN\Desktop\Complete Web Dev Bootcamp --crash-reporter-id 9419fbc7-1c16-4b5e-a20e-77788afe9f2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by binyamin** [comment]
@dhairyak-20 how does vs code contribute to this error? (Also, the favicon might just be cached).

**Comment by misolori** [comment]
Fairly certain this is a local browser cache issue that is unrelated to VS Code or Live Server. Here's an example where I was running a react app on the same port earlier today and then running a node app again:

![image](https://user-images.githubusercontent.com/35271042/100013917-7b29b600-2d8a-11eb-8961-7bd904ae898e.png)
