### ISSUE TITLE
Active indent lines do not render in High Contrast theme

### ISSUE THREAD

**Issue by surajs02** [microsoft/vscode#111137]
- VSCode Version: 1.51.0 (user setup)
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Enable high contrast mode on Windows 10
1. Ensure VSCode's theme is set to high contrast
1. Ensure indents are rendered in settings: `"editor.renderIndentGuides": true`
1. Ensure active indents are rendered in settings: `"editor.highlightActiveIndentGuide": true`
1. Click inside an indented code block to activate the active indent line and compare with another indented block's inactive indent line

Screenshot: Active indent line vs inactive indent line (High Contrast theme):
![image](https://user-images.githubusercontent.com/11654341/99910101-1ddb2980-2ce4-11eb-97e8-f5002f2eeccb.png)

Screenshot: Active indent line vs inactive indent line (Dark+ theme):
![image](https://user-images.githubusercontent.com/11654341/99910115-2fbccc80-2ce4-11eb-8d85-78610e394a88.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@aeschli I don't understand what is wrong. The HC theme [defines these colors](https://github.com/microsoft/vscode/blob/efd8b0141ecdcd4a8c499fd0c1f65b62ed3cc996/extensions/theme-defaults/themes/hc_black_defaults.json#L7-L8) but they do not appear in the `colorMap`, so when the colors are read they end up getting the defaults.

**Comment by aeschli** [comment]
I created #111877 to clean up the default color themes
