### ISSUE TITLE
VS Code hangs for awhile when attempting various ui tasks

### ISSUE THREAD

**Issue by dlgombert** [microsoft/vscode#111197]
- VSCode Version: 1.51.1 (system setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.   The only guaranteed way I can reproduce it is by trying to drag a tab to reorder.  It happens other times, but this is the only guarantee - happen every time, reproducible way.
2.   VS Code will hang for upwards of 15-30 seconds.  

Does this issue occur when all extensions are disabled?: **YES**

I've attached a screen capture.

**NOTE:** *when watching the gif below, it is in real time.  As soon as I touch the tab bar with my mouse, everything is frozen.  Then I tap the editor a bunch of times to pull up the windows `not responding` modal*.  I know it will seem like the video is done  because my mouse isn't moving, but it actually has an ending.  The time my mouse is just sitting there is real time how long it is frozen.

attachments:
![ezgif com-resize](https://user-images.githubusercontent.com/34715597/100013780-6574ba80-2da3-11eb-86cd-1086c6ea39b3.gif)

**Comment by deepak1556** [comment]
Does launching with `code --disable-renderer-accessibility` repro the issue ?

**Comment by dlgombert** [comment]
@deepak1556 `Warning: 'disable-renderer-accessibility' is not in the list of known options, but still passed to Electron/Chromium.`

**Comment by dlgombert** [comment]
One more detail about this.  It seems tied to my  mouse touching something outside of the text editor.  For example, the extensions pane; the tabs; etc.  It happens about once an hour, randomly - and other than trying to drag a tab, I'm never quite sure what I did to cause it.

**Comment by dlgombert** [comment]
Okay - I updated windows to 10.0.19042 and the problem seems to be resolved.  Hurrah!  Will mark closed.
