### ISSUE TITLE
Running 'HTML Language Features' Formatter: FormatOnSave is extremely slow

### ISSUE THREAD

**Issue by mxshapira** [microsoft/vscode#111181]
I use FormatOnSave for all my files. Lately, I'm encountering a major delay when saving my files. Here an example of an attempt to save a quick fix in an HTML file using `HTML Language Features` Formatter (it happens frequently with ESLint and Prettier as well):

<img width="1440" alt="Screen Shot 2020-11-23 at 08 25 44" src="https://user-images.githubusercontent.com/48856190/99977130-e1eaa780-2d69-11eb-983a-0d526f72cdb1.png">

VS Code Version: 1.51.1

**Comment by aeschli** [comment]
To investigate I need sample files that reproduce the issue...

**Comment by mxshapira** [comment]
@aeschli 
https://github.com/mxshapira/todo-js
