### ISSUE TITLE
"Go to Next Problem in Files" does not respect "files.exclude" patterns

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#111195]
Issue Type: <b>Bug</b>

I use the "Go to Next Problem in Files" option quite regularly, but it appears that it doesn't respect `files.exclude` or `search.exclude` patterns. I'm not sure if this is intentionally or not, so I'm filing this as a bug. Personally, I would expect that this command wouldn't search through files that I'm intentionally excluding.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|-psn_0_106522 --crash-reporter-id c6914155-166f-4175-88b3-886232e620cd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (159)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|11.4.0
project-manager|ale|12.0.0
vscode-bazel|Baz|0.4.0
search-crates-io|bel|1.2.1
color-info|bie|0.5.1
emojisense|bie|0.8.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-fish|bma|1.0.20
file-browser|bod|0.2.10
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.5.0
language-hugo-vscode|bud|1.2.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gotoanything|Cma|0.4.1
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
disableligatures|Coe|0.0.10
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
transformer|dak|1.9.0
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
vscode-dash|dee|2.4.0
confluence-markup|den|0.1.8
vscode-deno|den|2.3.3
xml|Dot|2.5.1
viml|dun|0.1.7
gitlens|eam|11.0.4
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.13
LogFileHighlighter|emi|2.10.0
vscode-great-icons|emm|2.1.61
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
vscode-go-test-adapter|eth|0.1.3
copy-relative-path-and-line-numbers|ezf|0.3.1
vscode-git-history|fab|2.0.5
vscode-open-in-github|fab|1.2.3
file-icons|fil|1.0.27
vscode-firefox-debug|fir|2.9.1
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.9
code-runner|for|0.11.1
shell-format|fox|7.0.1
sort-json-array|fvc|2.0.3
nightswitch|gha|1.1.0
vscode-sublime-merge|gio|1.2.0
vscode-pull-request-github|Git|0.21.2
go|gol|0.18.1
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.188
terraform|has|2.3.0
vscode-test-explorer|hbe|2.19.3
npm-dependency-links|her|1.2.0
headwind|hey|1.7.0
vscode-settings-cycler|hoo|1.0.1
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
customize-ui|ioc|0.1.49
monkey-patch|ioc|0.1.11
path-autocomplete|ion|1.15.0
fuzzy-search|jac|0.0.3
RelativePath|jak|1.4.0
TypeScriptImport|kev|1.17.0
json2csv|kha|0.0.1
vscode-gutter-preview|kis|0.26.2
vscode-format-context-menu|lac|1.0.4
rpm-spec|Lau|0.3.1
vscode-simple-icons|Lau|1.13.5
vscode-fix-checksums|leh|1.1.0
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
vscode-python-test-adapter|lit|0.6.3
bash-ide-vscode|mad|1.11.0
rust-analyzer|mat|0.2.392
Lisp|mat|0.1.11
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.7.1
HTMLHint|mka|0.10.0
mongodb-vscode|mon|0.2.1
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.8.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.372831992
cpptools|ms-|1.1.2
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.11
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.3.0
autodocstring|njp|0.5.4
indent-rainbow|ode|7.4.0
vscode-nunjucks-formatter|oki|0.1.3
fix-json|oli|0.1.2
markdown-checkbox|PKi|1.7.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.0
text-power-tools|qcz|1.17.0
ruby|reb|0.27.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
explorer-exclude-vscode-extension|Red|1.2.0
shellman|Rem|4.7.0
vscode-sort-json|ric|1.18.1
synthwave-vscode|Rob|0.1.8
bash-debug|rog|0.3.9
zsh-debug|rog|0.1.3
nunjucks|ron|0.3.0
codeui|rya|0.3.0
partial-diff|ryu|1.4.1
multi-command|ryu|1.4.0
vscode-javascript-booster|sbu|14.0.1
crates|ser|0.5.3
code-settings-sync|Sha|3.4.3
vscode-brewfile|sha|1.0.0
trailing-spaces|sha|0.3.1
mdx|sil|0.1.0
vscode-fileutils|sle|3.4.2
snipsnap-vscode|sni|1.1.0
control-snippets|svi|1.9.1
vscode-markdown-paste-image|tel|0.12.3
shellcheck|tim|0.12.1
alex-linter|tla|0.6.5
go-to-method|tri|0.2.0
sort-lines|Tyr|1.9.0
errorlens|use|3.2.4
remove-empty-lines|use|0.0.6
vscode-lldb|vad|1.6.0
vscode-icons|vsc|11.0.0
vim|vsc|1.17.1
gistfs|vsl|0.1.9
vspacecode|VSp|0.8.3
whichkey|VSp|0.8.2
file-icons-mac|way|1.0.1
vscode-icons-mac|way|7.25.3
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
vscode-ruby|win|0.27.0
change-case|wma|1.0.0
better-align|wwm|1.1.6
clang-format|xav|1.9.0
vs-code-wiki|Yun|0.5.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.7
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(13 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
These commands do not respect exclude settings. Problems are filtered only in problems view and not at other places.
