### ISSUE TITLE
For example, I'd like to do something like this...

### ISSUE THREAD

**Issue by talmax1124** [microsoft/vscode#111165]
For example, I'd like to do something like this...

![framer-vscode@2x](https://user-images.githubusercontent.com/806104/58577722-b63a4000-820c-11e9-80c8-d57a4cc5b40c.jpg)

_Originally posted by @austincondiff in https://github.com/microsoft/vscode/issues/74488#issuecomment-497031832_

What theme is this and how you achieved custom icons

**Comment by aeschli** [comment]
I guess you are talking about the view icons? See https://code.visualstudio.com/api/extension-guides/product-icon-theme

**Comment by talmax1124** [comment]
Was that theme created by you?

**Comment by aeschli** [comment]
No, I don't know this theme not where the screenshot comes from. I think it's not VSCode but a lookalike.

**Comment by austincondiff** [comment]
@talmax1124 @aeschli this was a mock up I did for these issues https://github.com/microsoft/vscode/issues/74488, https://github.com/framer/syntax/issues/11.

I'd love for this amount of flexibility in theming.￼ To achieve this I had to modify several system files that yielded VS code "corrupt".￼

**Comment by aeschli** [comment]
@talmax1124 Can you update the description to describe what exactly your feature request is? As for the images, see [my link](https://code.visualstudio.com/api/extension-guides/product-icon-theme) to product icons. Product icons are still in proposed state and user feedback is most welcome.
