### ISSUE TITLE
Editor report "react-jsx" as a problem when setting it as the "jsx" value in tsconfig

### ISSUE THREAD

**Issue by djake** [microsoft/vscode#111194]
- VSCode Version: 1.51.1
- OS Version: macOS Catalina 10.15.7

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create tsconfig.json
2. Add `"jsx": "react-jsx"`

Does this issue occur when all extensions are disabled?: Yes

<img width="732" alt="image" src="https://user-images.githubusercontent.com/6454660/100010722-ae764000-2d9e-11eb-8719-da5235c969d4.png">

<img width="862" alt="image" src="https://user-images.githubusercontent.com/6454660/100010780-ca79e180-2d9e-11eb-96e4-5f5babd58cfe.png">

**Comment by nithishj** [comment]
I am facing the same issue in vscode when using the latest versions of react and typescript and with the jsx setting as ` "jsx": "react-jsx"` in **ts-config.js**
![image](https://user-images.githubusercontent.com/7048218/100056312-7b3dba80-2e4b-11eb-8c89-30c48adac6c7.png)

**Comment by alazypig** [comment]
I have got this problem too.
![2020-11-24 15-29-10屏幕截图](https://user-images.githubusercontent.com/22055633/100061993-db435980-2e69-11eb-8c1f-8ddc37e3eff4.png)

**Comment by mjbvz** [comment]
The warnings in the tsconfig come from the tsconfig schema. Please file an issue against schemastore where the tsconfig schema is defined: https://github.com/SchemaStore/schemastore/issues

For IntelliSense, if you use `"jsx": "react-jsx"` you need to [switch your workspace to use TS 4.1+](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)

**Comment by ahuglajbclajep** [comment]
You can also solve this problem by adding `"typescript.tsdk": "node_modules/typescript/lib",` to `.vscode/settings.json`.

**Comment by karltaylor** [comment]
If you are seeing this issue after running `create-react-app` with Typescript, simply go down to the blue task bar and select the Typescript version, then select `Select TypeScript Version`.

<img width="647" alt="Screenshot 2020-11-30 at 10 02 26" src="https://user-images.githubusercontent.com/6763109/100595764-428e5d00-32f3-11eb-8f3b-74b045acb74f.png">

Then select `Use Workspace Version version` which should reference `node_modules/typescript/lib`

<img width="622" alt="Screenshot 2020-11-30 at 10 02 34" src="https://user-images.githubusercontent.com/6763109/100595827-59cd4a80-32f3-11eb-8f5e-a28a426ceab5.png">
