### ISSUE TITLE
Why there's always a `.cargo-ok` in git status(changes)?

### ISSUE THREAD

**Issue by AurevoirXavier** [microsoft/vscode#111173]
Steps to Reproduce:
1. `cargo check`

![2020-11-23_19-07](https://user-images.githubusercontent.com/16152305/99955380-3704d880-2dbf-11eb-8137-cba035aa5296.png)

**Comment by AurevoirXavier** [comment]
And this path: `~/.cargo` is totally wrong. My project(.git) is under `~/Documents/xxx`

**Comment by egamma** [comment]
pls see also https://github.com/rust-lang/cargo/issues/6340

**Comment by AurevoirXavier** [comment]
> pls see also [rust-lang/cargo#6340](https://github.com/rust-lang/cargo/issues/6340)

But it shouldn't appear here.

And the git status works well.  But vscode's integrate git not. Even I add it into the `.gitignore`, It still there
