### ISSUE TITLE
源代码管理器

### ISSUE THREAD

**Issue by hello-hansir** [microsoft/vscode#111117]
macbook pro   在装完git 后   在桌面新建文件夹，文件夹在vscode中打开，源代码管理器自动扫面电脑的5000多个文件，无法取消，无法隐藏

**Comment by TheColdPot** [comment]
macbook pro 在装完git 后 在桌面新建文件夹，文件夹在vscode中打开，源代码管理器自动扫面电脑的5000多个文件，无法取消，无法隐藏

After MacBook Pro installed git, create a directory in the desktop and open it in VSCode, Source Code Controller scanning 5,000 files in computer automatic, but not able to cancel or hide.

*Is this helpful?*

**Comment by roblourens** [comment]
Sorry, I can't do anything about this without more details.
