### ISSUE TITLE
Independent zoom for each editor instance

### ISSUE THREAD

**Issue by rekna1** [microsoft/vscode#111171]
When I have 2 instances of vsode, zoom view changes both instances. I would like to control them separately.
My use case : I have one instance of vscode on my laptop monitor and one instance on separate big size monitor .
Laptop screen text is much smaller then separate monitor so I  want to zoom in only on the instance on the laptop monitor.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/108661#issuecomment-708964134
