### ISSUE TITLE
Quick open: resolveHandler() being called often and complicated?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11114]
I am a bit puzzled why we call `resolveHandler` in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts many more times than we used to and why there is such a complicated logic to handle this.

As a reference here is how it used to work: https://github.com/Microsoft/vscode/blob/1.4.0/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L835

**Comment by bpasero** [comment]
@chrmarti ping

**Comment by chrmarti** [comment]
I added onOpen to the handlers and added logic that makes sure that is called exactly once and alternates with onClose. I'll review that to make sure it's not unnecessarily complex.

**Comment by bpasero** [comment]
@chrmarti but isn't onOpen called from the widget when the handler is opened? If we need a new event for when a handler is instantiated we should introduce a new thing imho.

**Comment by chrmarti** [comment]
The reason I did it this way is that both show() and onType() can be the first to know which handler will be used and I wanted to give the handler a head-start by calling onOpen as soon as possible.

There is one call to resolveHandler() in each of show() and onType() just to trigger the loading and eventual call to onOpen on the handler as soon as possible. Later handleDefaultHandler() and handleSpecificHandler() use resolveHandler() to retrieve and use the handler.

Some complexity comes from this open-close lifecycle potentially being run through for each handler more than once and onType() switching between handlers without closing.

**Comment by bpasero** [comment]
@chrmarti we can get rid of this call though (https://github.com/Microsoft/vscode/blob/ben/electron-update/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L644) because it gets called in the code right after, no?

Another thing which is not good is that in https://github.com/Microsoft/vscode/blob/ben/electron-update/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts#L498 you are not handling the returning promise at all, so any error will be swallowed. Maybe it should be hooked up with the promise that gets returned.

**Comment by chrmarti** [comment]
Didn't find the time to follow up, next milestone.
