### ISSUE TITLE
Multicursor `Enter` issue with indentation (gif attached)

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#111128]
- VSCode Version: 1.51.1 / 1.52.0-insider
- OS Version: Ubuntu 20.04 / Windows 10

Steps to Reproduce:

1. insert 4x spaces at the beginning of a line
2. place multiple cursors on that line
3. Press enter

Expected: Insert newline at each of the positions where cursor is present
Actual Behavior: Inserts newline only at the first (NOT the left most) cursor position

_(Let me know the relevant settings values required)_

Addiditional info: 

- I use tabs (width of 4 spaces) for indentation for formatting

![vscode-multicursor-bug](https://user-images.githubusercontent.com/15051871/99904700-c0020e00-2cf2-11eb-99e0-f5b5e2ec90c1.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@stagefright5 I think this might be caused by one of your installed extensions. Here it is on my machine:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/100986459-82e91780-354d-11eb-8504-03c911cdbead.gif)

To validate this, could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command Developer: Toggle Keyboard Shortcuts Troubleshooting
  * This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* You can then press <kbd>Enter</kbd> and check what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can help decipher it for you.

**Comment by stagefright5** [comment]
Here is the render log:

[renderLog4.log](https://github.com/microsoft/vscode/files/5640664/renderLog4.log)

Also, the settings.json:

[settings.zip](https://github.com/microsoft/vscode/files/5640671/settings.zip)

**Comment by stagefright5** [comment]
It is also not exclusive to the multi cursors created using keybinding. I can reproduce this by placing mulitple cursors created using the `Alt + Mouse-Left-Click` too.

**Comment by alexdima** [comment]
@stagefright5 From the keyboard log, I can confirm that nobody is "stealing" Enter via keybindings. But there is another way that extensions can intercept that, via our `type` command. That is the way in which `vim` intercepts Enter. 
Does this reproduce when disabling all extensions? Press `F1` and then choose `Developer: Reload Window with Extensions Disabled`

![Kapture 2020-07-20 at 15 28 23](https://user-images.githubusercontent.com/5047891/87943040-c3b02a80-ca9d-11ea-847d-5f850fae8f05.gif)

**Comment by stagefright5** [comment]
Hey @alexdima , In all of my previuos posts I have made sure that I have disabled all the extensions (by running the command that you have mentioned) and also, at the end of each of my posts I have explicitly stated that I had disabled the extensions.
Can it have anything to do with my settings related to tabs?
May be, inspect my settings here: [settings.zip](https://github.com/microsoft/vscode/files/5640671/settings.zip) (which has settings.json) and, try to reproduce the issue by applying the exact same settings (copy paste my settings.json).

**Comment by stagefright5** [comment]
Also, @alexdima , Please carefully go through each of the above posts. It seems like you are not reading all the comments. It will save me from repeating the same thing again and again.
Thanks.

**Comment by alexdima** [comment]
Thank you for your patience, with your settings, I could finally reproduce. I missed the fact that the editor is configured to use tabs and I believed you might be using vim due to the block cursor in the GIF.

You can workaround by using `"editor.autoIndent": "advanced"`.
