### ISSUE TITLE
Reduce Line numbers panel width

### ISSUE THREAD

**Issue by imdad** [microsoft/vscode#111167]
Currently, the width of the panel where the line number is displayed is more than it should have I believe. Mainly because it has 3 columns first one is for toggling breakpoints, second one is for line number and third one is for displaying collapse/expand icon. The first 2 features could be done in one column and for the third feature could be done with less space by using smaller icon. 

Here is how I believe it could be achieved:

1. When breakpoint is active on a line then the line number will be highlighted with a highlight colour and the font colour will 
contrast the highlight colour. So, we won't need a separate marker for breakpoint toggle.

![line_number_breakpoint_example](https://user-images.githubusercontent.com/1075113/99954838-63155f00-2da9-11eb-8e78-d90628b93175.png)

2. When the user hovers on the line number which is a start of a block then the collapse icon should display like:

![collapse_exand_style](https://user-images.githubusercontent.com/1075113/99954893-74f70200-2da9-11eb-81a1-5672e268cf75.jpg)
It allows us utilizing the space used for padding.

**Comment by weinand** [comment]
@imdad I cannot access the links to the picture. Please paste the pictures directly into your comment. There is no need to link them to an external site.

**Comment by isidorn** [comment]
This is a feature request against the editor to reduce the glyph margin width. Thus forwarding to @alexdima

**Comment by imdad** [comment]
> @imdad I cannot access the links to the picture. Please paste the pictures directly into your comment. There is no need to link them to an external site.

Done!
