### ISSUE TITLE
menuBar is hidden

### ISSUE THREAD

**Issue by brit45** [microsoft/vscode#111150]
Issue Type: <b>Bug</b>

menuBar is not visible and is not possible to back her is value default

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-52-generic

**Comment by ArturoDent** [comment]
What is your `Window: Menu Bar Visibility` setting?  Are you saying that it is set to `default`?

**Comment by brit45** [comment]
my settings.json:
```json
{
     "workbench.iconTheme": "material-icon-theme",
     "window.menuBarVisibility": "visible",
     "terminal.integrated.allowMnemonics": true,
     "window.customMenuBarAltFocus": false,
     "workbench.colorTheme": "Dark + Material",
     "editor.suggestSelection": "first",
     "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
     "editor.rulers": [
    
     ]
}
```

however even restarting and pressing Alt nothing happens.

**Comment by sbatten** [comment]
@brit45 If you remove all settings in you settings.json and restart the app, does this help your issue? Also, was this working before on this machine? Curious if you have had any recent OS updates/changes.

**Comment by brit45** [comment]
I did have a system update recently. for the configuration I removed everything and I completely uninstalled vscode before reinstalling, but the problem is still there.

**Comment by sbatten** [comment]
@brit45 Can you share your distro information?

**Comment by brit45** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by brit45** [comment]
After removing the configuration and reinstalling vscode, I restart the system before launching the application. The menu bar is visible again.

**Comment by sbatten** [comment]
@brit45 sorry I could not debug it, thanks for getting back. I tried to get a repro myself on that distro but no success.
