### ISSUE TITLE
Titlebar missing

### ISSUE THREAD

**Issue by sholtoarmstrong-iot** [microsoft/vscode#111123]
My title bar went missing after a vscode upgrade. I am only able to access the minimise, fullscreen and close buttons if i change the setting "window.titleBarStyle" from "native" to "custom". However, I prefer using the native settings.
![Screenshot from 2020-11-22 13-38-17](https://user-images.githubusercontent.com/65215432/99902648-02622580-2cc8-11eb-997f-536407ecb09f.png)

- VSCode Version: 1.51.1
- OS Version: Pos!_OS 20.10

Steps to Reproduce:

1. Upgraded VSCode to newest version
2. Opened it up and the titlebar was missing.
3. I tested this on a clean install of the insiders build (1.52.0-insider) and the issue is still there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by septatrix** [comment]
My guess is that it has to do with wayland as it does not support server side decorations. In chrome e.g. the option "Use system title bar and borders" is disabled when running under a wayland compositor and with the wayland ozone backend disabled. I do not know why this already exists in vscode (as this only exists in the newest electron) but I firmly believe it is related.

**Comment by sholtoarmstrong-iot** [comment]
I recently discovered that another application was experiencing the same issue (VLC Media Player) and that it isn't only VS Code. Therefore, I think the issue may lie elsewhere in my system. I appreciate the time and fast response. I am closing the issue if that is okay?
