### ISSUE TITLE
class_alias undefined type

### ISSUE THREAD

**Issue by no-matter-0** [microsoft/vscode#111159]
Issue Type: <b>Feature Request</b>

Hi
PHP 7
I declare :

require_once 'Helper.php';
class_alias('ysHelper', 'ys');

using in a class code : 

public function setCustomFields(){
		return ys::getCustomFields($this->article);
	}

I get an orange line under ys:: undefined type

thanks

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 16.7.0

**Comment by roblourens** [comment]
Please file this on the repo for whichever PHP extension you are using.
