### ISSUE TITLE
code snippet on terminal

### ISSUE THREAD

**Issue by qdoomdh** [microsoft/vscode#111118]
I think if code snippets work on terminal specially for python and Django, the project become amazing.

**Comment by adierebel** [comment]
this is the feature i was looking for

Maybe it will place on terminal context menu. So, when user right click on terminal, it will show available command snippets.
| New Terminal    |               |
|-----------------|---------------|
| Copy            |               |
| -               |               |
| Split           |               |
| Paste           |               |
| Select All      |               |
| -               |               |
| **Snippets**      > | **_Configure_**     |
| -               | -             |
| Clear           | _**activate venv**_ |
| -               | _**cd to /**_       |
| Kill Terminal   | _**start lampp**_   |
|                 | _**...**_           |

**Comment by emsuryadi** [comment]
@adierebel your idea is quite interesting, +1 for this feature

**Comment by adierebel** [comment]
@emsuryadi thanks. Previously I used Terminal Deepin, there are command snippets features there. I thought it would be great if VSCode had one too

**Comment by Tyriar** [comment]
In the interest of keeping lightweight I don't think we should go forward with this. However, there are options available now and in the future that could solve this:

- A keybinding could be set up using the `workbench.action.terminal.sendSequence` command to do this
- An extension could expose a command that shows a quick pick with a set of snippets
- After https://github.com/microsoft/vscode/issues/79034, an extension will be able to create context menu entries in the terminal
- There's an existing macro feature request which could potentially be used for this https://github.com/microsoft/vscode/issues/4490
