### ISSUE TITLE
echo -e '\a' should beep in the terminal?

### ISSUE THREAD

**Issue by kandel3** [microsoft/vscode#111151]
Would be cool if `echo -e '\a'` produced a beep in the terminal like on other platforms.

**Comment by ArturoDent** [comment]
`echo -e '\a' works to make the Windows10 Default Beep sound for me.  You are on what platform?

**Comment by kandel3** [comment]
I'm using MacOS

**Comment by GeekerSu** [comment]
Definitely cool idea!
