### ISSUE TITLE
Space beneath notification bar at the bottom

### ISSUE THREAD

**Issue by leegee** [microsoft/vscode#111170]
Issue Type: <b>Bug</b>

Open code and scroll downwards whilst hovering over the notification bar. A strange space appears. Can also happen when clicking items in the browser/search results.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.80GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/mnt/l/src/nta --remote=wsl+Debian --crash-reporter-id dfed0d24-a546-44c2-b56b-c29c9fe0ceb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3401)|
|Memory (System)|15.94GB (6.80GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
vsc-material-theme-icons|equ|1.2.0
mysql-syntax|jak|1.3.1
dotenv|mik|1.0.1
remote-wsl|ms-|0.51.4
vscode-sql-formatter|adp|1.4.4
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|11.4.0
vscode-color|ans|0.4.5
vscode-intelephense-client|bme|1.5.4
vscode-perl|cfg|1.18.0
jsrefactor|cms|2.20.6
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
EditorConfig|Edi|0.15.1
beautify|Hoo|1.5.0
markdown-formatter|mer|0.8.9
vetur|oct|0.30.2
vscode-xml|red|0.14.0
html-preview-vscode|tht|0.2.5
markdown-all-in-one|yzh|3.4.0
simple-perl|zhi|0.0.4

(2 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/512816/99951346-4283df80-2d7e-11eb-9a4e-645a411e5c71.png)

**Comment by bpasero** [comment]
I have not tried to reproduce but the workbench itself should not be scrollable, this sounds like a layout issue to me.

**Comment by sbatten** [comment]
@leegee are you using a device that has a touch screen? If so, this may be an issue with Windows + Electron. I have seen this many times where Windows acts like it might open the on screen keyboard and you end up with this. I could not reproduce with just the steps above.

**Comment by sbatten** [comment]
@leegee is this something you can reproduce 100% of the time?

**Comment by leegee** [comment]
> @leegee is this something you can reproduce 100% of the time?

No it's not, but I can't find a patter yet. I'll open a new ticket if I can find a pattern.
