### ISSUE TITLE
Debugger fails to connect OSX 10.11.6 - ReactNative Project

### ISSUE THREAD

**Issue by pelicanenglw** [Microsoft/vscode#11116]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Press Green play button.
2. Get Error - Cannot launch debug target (spawn node ENOENT).

Node - v4.2.1
ESLint - v3.4.0

VSCode extension versions
![screen shot 2016-08-29 at 12 42 31 pm](https://cloud.githubusercontent.com/assets/1039491/18057360/1335fbfc-6de6-11e6-9fda-97b89da9b2a2.png)

**Comment by pelicanenglw** [comment]
Target is iOS.  Have not tried Android.

**Comment by pelicanenglw** [comment]
Updated node to v6.5.0 no change

**Comment by isidorn** [comment]
This seems like an issue with the react native extension. Can you please create an issue in this repo  https://github.com/Microsoft/vscode-react-native

Thank you
