### ISSUE TITLE
"NPM Scripts" explorer tab has no icon

### ISSUE THREAD

**Issue by lllopo** [microsoft/vscode#111168]
Version: 1.52.0-insider (user setup)
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:56:29.761Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Drag the "npm scripts" explorer to the sidebar, so it becomes a standalone tab on the sidebar.

Expected behavior :
The tab should appear with an icon.

What happens :
The tab appears and works fine, but there is no icon

![Screenshot 2020-11-23 114505](https://user-images.githubusercontent.com/5485902/99948245-d7d4a300-2d81-11eb-81a3-d1cd2e3af0f9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@sandy081 it seems that https://github.com/Microsoft/vscode/commit/b5cd02f178cc0a528fb70f8e8ba9dd48d57cb395
isn't working.

**Comment by alexr00** [comment]
Thank you @lllopo !
