### ISSUE TITLE
Cannot stash single file

### ISSUE THREAD

**Issue by salos1982** [microsoft/vscode#111164]
Issue Type: <b>Bug</b>

Open source control tab
Select one file with changes
In the context menu select "Stash Changes"
Input name of stash
Press "Enter"

Result
input field disappears and nothing else happened
Expected: File disappear from Source Control tab and stash is created

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3438)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.24GB (8.68GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id dff2a1bc-4a46-4657-8614-931eaa3781bd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
gitlens|eam|10.2.3

</details>

**Comment by salos1982** [comment]
after rebooting, stash becomes working

**Comment by eamodio** [comment]
Stash changes is provided by GitLens, so if there is an issue please report it there. Thanks!
