### ISSUE TITLE
Untitled file name extended by 1st line type-in

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#111145]
Issue Type: <b>Bug</b>

When I select File > New File and start typing the first line, I don't want the feature of having the suggested file name be what I'm typing in + "Untitled-n".  I will choose the name on Save  or Save As.  I'm going to change it anyway since I don't want "Untitled" to be part of the name.  This is help that is a burden.

VS Code version: Code - Insiders 1.52.0-insider (8f9aeb83da26902e21ca41f8d17d204d2ac216cf, 2020-11-16T11:24:42.172Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.90GB free)|
|Process Argv|--crash-reporter-id 7c6de294-4532-45d5-9935-df9c636e4365|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.12.360617350-dev
jupyter|ms-|2020.11.372831992

</details>

**Comment by bpasero** [comment]
This can be turned off via `workbench.editor.untitled.labelFormat` setting.
