### ISSUE TITLE
Tab completion not working

### ISSUE THREAD

**Issue by khoilr** [microsoft/vscode#111119]
Tab completion not working although I turned on "editor.tabCompletion" when I update last version of Visual Studio Code Insiders.
Thanks for reading my report

**Comment by sebaguse** [comment]
Same here, update to: 

Version: 1.52.0-insider (system setup)
Commit: caf01baa45b9816e2e1d8a2de22b40cf89459c03
Date: 2020-11-20T07:41:44.570Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

and TAB completion no longer works.

**Comment by krokofant** [comment]
It feels so broken now. 😢

**Comment by krokofant** [comment]
Funnily enough, if you copy and take the default keybinding for `acceptSelectedSuggestion`
![image](https://user-images.githubusercontent.com/5908498/99951326-3a2ba480-2d7e-11eb-90d1-7327c1e6c6dd.png)

And put it into your own keybindings:
```json
  {
    "key": "tab",
    "command": "acceptSelectedSuggestion",
    "when": "suggestWidgetVisible && textInputFocus"
  }
```

It starts to work again, independent on the tab completion setting.
![image](https://user-images.githubusercontent.com/5908498/99951505-84ad2100-2d7e-11eb-937b-4b2671b57a3f.png)

**Comment by krokofant** [comment]
@rzhao271 Could this be related to your latest emmet changes?

**Comment by rzhao271** [comment]
Thanks for the mention @krokofant 
I just verified that what is happening is that the acceptSuggestion shortcut became lower precedence than the expandAbbreviation shortcut.
Marked the issue as a regression

**Comment by rzhao271** [comment]
\closedWith 4c55c7264ff66fcd15faecfd1c52016a337efa9e
