### ISSUE TITLE
"Tasks.presentation.revealProblems": "never" doesn't seem to work

### ISSUE THREAD

**Issue by rlabrecque** [microsoft/vscode#111114]
Issue Type: <b>Bug</b>

1. Clone https://github.com/rlabrecque/rl-diablo-2-hack/tree/ea690b09fd4c4fb55a7f043b9a7e59c40b215644
2. Open as folder in VSCode with the rust-analyzer plugin enabled, run the build.

Unclear if this is a VSCode or rust-analyzer problem thus far.

Attached video just to confirm that it was directly happening from the task.
![2020-11-21_22-51-24](https://user-images.githubusercontent.com/2047188/99897380-ddc96780-2c4d-11eb-9e24-05152b022b5f.gif)

VS Code version: Code - Insiders 1.52.0-insider (caf01baa45b9816e2e1d8a2de22b40cf89459c03, 2020-11-20T07:41:44.570Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (3.68GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 06d2912f-ada6-4918-990b-7d922cade057|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry244cf:30226748
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by alexr00** [comment]
I tested this and can't repro. Do you by chance have this setting set? `debug.onTaskErrors`?

**Comment by rlabrecque** [comment]
Yep, that was exactly it, thanks @alexr00!

I wish this property were in the task api documentation, I think a note about debug.onTaskErrors in there would be useful.

https://github.com/microsoft/vscode/issues/73840
