### ISSUE TITLE
Allow the new WebView to be placed next to the Terminal

### ISSUE THREAD

**Issue by xxKarina** [microsoft/vscode#111130]
This request is similar to #46585 but I feel it is different enough to warrant this request.

 I would equally love it if a webview could be hosted in a (bottom) panel next to the terminal.
For my use case I would like to host a WebView as a Bottom Panel instead of sideBar pannel. Think of the scenario where a user is submitting SQL from the editor and wants to see the results (ideally in the bottom panel).
![image](https://user-images.githubusercontent.com/22519837/99907654-fd799200-2d18-11eb-823e-492f11fea504.png)

We are also desperately looking for this capability for a feature we added in our VScode extension. Initial comments from our customers are indicating that they would like the web view as a bottom panel next to the terminal.

When the webview is hosted in a "panel" how can we force it to be visible with registerWebviewPanelSerializer?

It feels like I should have a reference to the hosting panel (so I can show it and change its title etc.)

Is there any indication on if/when this will be possible?

**Comment by xxKarina** [comment]
I hope that vscode can allow the new WebView to be placed next to the terminal through programming.

**Comment by mmmyddd** [comment]
Finally somebody mentioned this issue! It is the feature I expect for a long time~~

I hope vscode can create new webviews and place them both in the sidebar and in the panel area (beside terminal / output panels ...)

some features such as a monitor or profiler would be most suitable to be placed in the bottom panel area of the vscode window
and make vscode a good base for more complex toolbox and work shop ^_^

I will be glad and looking forward to the coming update include this improvement :)

**Comment by mmmyddd** [comment]
At this time, the webview only can be created and drag to the panel

**Comment by jarodium** [comment]
Yes. I would like the ability to create a panel right beside terminal. xD

**Comment by mjbvz** [comment]
@sandy081 Is there a way for extensions to contribute a view to the terminal? (or to any of our default panel view containers?)

**Comment by sandy081** [comment]
Contributing views to builtin panels is not supported and currently extensions can contribute views to only following builtin view containers

- explorer
- scm
- debug

It is up to respective panels to support it and it is fairly easy to do it  - Add the builtin view container here: https://github.com/microsoft/vscode/blob/357fc9d16b43cf44f3cb7c38449fa39920f62a07/src/vs/workbench/api/browser/viewsExtensionPoint.ts

**Comment by mmmyddd** [comment]
> Contributing views to builtin panels is not supported and currently extensions can contribute views to only following builtin view containers
> 
> * explorer
> * scm
> * debug
> 
> It is up to respective panels to support it and it is fairly easy to do it - Add the builtin view container here: https://github.com/microsoft/vscode/blob/357fc9d16b43cf44f3cb7c38449fa39920f62a07/src/vs/workbench/api/browser/viewsExtensionPoint.ts

Not contribute webviews to buildin panels, I think what we need is to create new webviews, and place it next to buildin panels like terminal/output/debug console/problems in the  "panel area".

currently what only we can do is create a webview in the activity view containers and "drag" to the panel area.

Please consider this requirement, thanks.

**Comment by xxKarina** [comment]
Glad to receive your reply !
Maybe I can accept to create the webview in the allowed panel, but I am eager to specify the webview location on the panel where the terminal is located when my extension is activated.

So that the users who use my extension can see my webview on the panel where the terminal is located for the first time.

**Comment by sbatten** [comment]
If I understand correctly, you want to contribute a custom view container to the panel and then contribute your webview to that viewcontainer. https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers

**Comment by mmmyddd** [comment]
> If I understand correctly, you want to contribute a custom view container to the panel and then contribute your webview to that viewcontainer. https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers

Exactly what I want, thanks a lot.

**Comment by mjbvz** [comment]
Thanks @sbatten! Closing this since it sounds like the original question has been answered
