### ISSUE TITLE
out to lunch

### ISSUE THREAD

**Issue by gideony2** [microsoft/vscode#111109]
Trying to add MS's C# extensions. I keep getting the enclosed (for 3 days running):

??
<img width="877" alt="Screen Shot 2020-11-21 at 4 15 41 PM" src="https://user-images.githubusercontent.com/5395623/99890557-64ae1e00-2c15-11eb-8e5e-849be3dae394.png">

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you try installing a different extension? For example, maybe my trivial one called "The Folding Stuff".

**Comment by gideony2** [comment]
Other extensions installed; yours gives the enclosed -- but not a 404

Hope this helps

Gideon

**Comment by gideony2** [comment]
The enclosed *did* get installed. I tried #3 there *afte*r the regular C#
install failed, in case it would work for me. So things do load.

**Comment by gideony2** [comment]
full text of gripe enclosed.

**Comment by gideony2** [comment]
uninstalled VS code, reinstalled; I now have other problems; but C# loads OK

**Comment by gideony2** [comment]
On a yet fresher reinstall, I get the enclosed

??

Thanks

Gideon

**Comment by gideony2** [comment]
finally got it all working (i.e. a tiny F# program under debugger)

**Comment by roblourens** [comment]
Your attachments are not included through email. Sounds like it is working now?

**Comment by gideony2** [comment]
Yes, all working now ("Hello world" under the debugger)

Thanks

Gideon
