### ISSUE TITLE
Test: Extension details view

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11118]
- [x] Windows **@stevencl**
- [x] macOS **@waderyan**
- [x] Linux **@gregvanl**

Complexity 2
Tests #10366

--

When viewing extensions in the Marketplace, you should now be able to see [which contributions](https://github.com/Microsoft/vscode/issues/10366#issuecomment-239848685) they bring in.

**Comment by stevencl** [comment]
I was able to verify that I could see configuration, commands, menus, keybindings, languages, debuggers, grammars, themes, snippets and json validation for a number of extensions from the marketplace.

Couldn't find any bugs though...

**Comment by waderyan** [comment]
Really like this. 

And stoked to find this! Sort Bys are great. 

![image](https://cloud.githubusercontent.com/assets/2449568/18098073/7025a54c-6e95-11e6-84d1-8b875786182c.png)
