### ISSUE TITLE
Extra characters added in terminal

### ISSUE THREAD

**Issue by ShubhankarKG** [microsoft/vscode#111127]
- VSCode Version: 1.51.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Set VSCode width to half of screen size.
2. Toggle Explorer and see the terminal.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Everytime there's a toggle in the explorer, the terminal adds **1;2c**.

Screenshots

![Screenshot from 2020-11-22 16-59-48](https://user-images.githubusercontent.com/50791000/99904437-c42d2c00-2cf0-11eb-9771-50ea119b6544.png)
![Screenshot from 2020-11-22 16-59-40](https://user-images.githubusercontent.com/50791000/99904438-c68f8600-2cf0-11eb-8cd3-4474043ab700.png)
![Screenshot from 2020-11-22 18-30-53](https://user-images.githubusercontent.com/50791000/99904450-e4f58180-2cf0-11eb-8b26-21763f9d94fe.png)

**Comment by meganrogge** [comment]
thanks for the issue. what key-bindings are you using to toggle the explorer?

**Comment by ShubhankarKG** [comment]
I was able to reproduce this just by manually toggling as well as _Ctrl + Shift + E_

**Comment by meganrogge** [comment]
I'm unable to reproduce this. Toggling the explorer should move the focus from the terminal to the explorer. Yet it seems the focus remains on the terminal for you. Can you pls include a [gif](https://gifcap.dev/) with screen cast mode on?

**Comment by ShubhankarKG** [comment]
Unfortunately, I myself couldn't reproduce this anymore, so I'm closing this issue :shrug: If at all I could come up with a screencast, I'll reopen this.

Thanks for the time though! Really appreciate it.
