### ISSUE TITLE
Recording Button

### ISSUE THREAD

**Issue by ishwish2008** [microsoft/vscode#111153]
maybe like a start, stop, pause, etc...

**Comment by ArturoDent** [comment]
What do you want to record?

**Comment by ishwish2008** [comment]
> What do you want to record?

something to record the editor, terminal and sidebar

**Comment by egamma** [comment]
@ishwish2008 please explain your feature request in more detail. What exactly do you want to record? Can you illustrate this with an example please.

**Comment by ishwish2008** [comment]
nevermind i can do it with other software
