### ISSUE TITLE
Deleting a folder causes Windows to BSOD

### ISSUE THREAD

**Issue by dend** [microsoft/vscode#111192]
- VSCode Version: 1.51.1
- OS Version: 20H2 (19042.630)

Steps to Reproduce:

1. Open the explorer in Visual Studio Code.
2. Delete any folder.
3. Visual Studio Code crashes the system with a BSOD (`SYSTEM_SERVICE_EXCEPTION` in `cldflt.sys`)

I am suspecting that _Cloud Files Mini Filter Driver_ from OneDrive is causing the issue (the folder I am operating with is hosted in OneDrive on Windows 10), but it only occurs if I delete the folder from VSCode. If I delete the folder from Windows Explorer or any other app, it works as expected.

Does this issue occur when all extensions are disabled?: **Yes**

Something to consider - running an unprivileged PowerShell session and attempting to delete the same folder, I get:

![image](https://user-images.githubusercontent.com/1389609/100008567-75c86d80-2d82-11eb-9799-3dc5b751b6a7.png)

**Comment by rzhao271** [comment]
Potentially related https://github.com/electron/electron/issues/26707

**Comment by berkdemir** [comment]
Same here.

**Comment by SolasArd** [comment]
facing the same issue

**Comment by sandint2011** [comment]
Just discovered I'm having this issue as well. Any solutions yet?
Also mine happens when deleting from Explorer which OP says worked fine for them.

**Comment by dend** [comment]
@deepak1556 - do you happen to have any updates on the issue? This is now going on an entire year without a solution.

**Comment by deepak1556** [comment]
Nope I haven't looked into this, will check next milestone.

**Comment by rzhao271** [comment]
Is this issue occurring for anyone on the latest VS Code, still?

**Comment by deepak1556** [comment]
Upstream issue has been closed https://github.com/electron/electron/issues/26707, closing as not actionable.
