### ISSUE TITLE
Adding a new file tells me the file name is invalid but not why

### ISSUE THREAD

**Issue by StingyJack** [microsoft/vscode#111199]
Issue Type: <b>Bug</b>

open a folder
add a new file
call the file "git-hub-comments.ps1"

Expected: Either the file is created (since its a legitimate file), or VSC tells me what is not legitimate about the file.

Actual: VSC tells me the file name is invalid. 

Note: If I change the filename to ghcomments.ps1 I'm able to save it. Subsequent attempts to create the file with the original name work as well. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
This works fine for me.
Can you reproduce using vscode insiders https://code.visualstudio.com/insiders/


![Screenshot 2020-11-24 at 09 53 43](https://user-images.githubusercontent.com/1926584/100071096-f5b20e80-2e3a-11eb-828f-12ede652a107.png)
