### ISSUE TITLE
Shows duplicate identifier error when compiled file open in split editor window 

### ISSUE THREAD

**Issue by bunny3025** [microsoft/vscode#111224]
- VSCode Version: 1.51.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a TS file 
2. Open Compiled (use **tsc** from CLI) JS file in the same editor
3. Now split window and now compiled JS should be opened in right. 
4. You can see error makers in the TS file. added screenshot below.

![image](https://user-images.githubusercontent.com/1892377/100080981-805f3180-2e6c-11eb-956c-d2ffa7d2f360.png)

These are not the compiled errors, when you will run the TS file it will run, but due to JS and TS have opened in the same scope, will create this illusion for the developer.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Try creating a [tsconfig](https://code.visualstudio.com/docs/typescript/typescript-compiling#_tsconfigjson) to explicitly define your project
