### ISSUE TITLE
Emmet suggestions are too aggressive on tsx files

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111245]
![image](https://user-images.githubusercontent.com/22350/100141441-bb745b80-2e92-11eb-859c-743c1349d27a.png)

I keep hitting emmet suggestions in suggest, when editing .tsx files. 😢

**Comment by rzhao271** [comment]
Emmet support on jsx/tsx right now has been lacking for a while and I think we can continue the discussion here:
https://github.com/microsoft/vscode/issues/51537
