### ISSUE TITLE
`tsec` is not version locked

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#111289]
Every `yarn` could potentially install a different version of `tsec`. This is contrary to all other dependencies, where we use versions locked in `yarn.lock`. In the past, when we consumed a npm module from github, we included the git sha in the dependency.

**Comment by jrieken** [comment]
@engelsdamien would it be possible for you to publish tsec to npm? The current form causes this issue and also some headaches when not explicitly using `yarn upgrade tsec --latest`
