### ISSUE TITLE
Peek definition stops working after one/two use/s

### ISSUE THREAD

**Issue by rhish9h** [microsoft/vscode#111275]
- VSCode Version:1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64
- OS Version:Ubuntu 20.04.1 LTS

I am working on C code in Vscode. It has extension C/C++ (C/C++ IntelliSense, debugging, and code browsing.).

The option - peek definition works fine for the first one/two times but then goes away.

Steps to Reproduce:
1. Open C code (qmail-1.03) (part of company code base)
2. Right click on a function -> click Peek -> click Peek Definition - works fine
3. Repeat step 2 -> gives error - No definition found for 'ldaplookup'

Screenshot of peek definition when working:

![Screenshot from 2020-11-24 13-07-03](https://user-images.githubusercontent.com/51257654/100195411-50239b80-2f1d-11eb-8293-6da7fd298f50.png)

Screenshot of peed definition on second attempt - not working:

![Screenshot from 2020-11-24 13-07-25](https://user-images.githubusercontent.com/51257654/100195497-6cbfd380-2f1d-11eb-9121-6f01c0cb08bc.png)

Does this issue occur when all extensions are disabled?: No (cannot use peek without extensions)

**Comment by egamma** [comment]
Please report the issue against the C++ extension.
