### ISSUE TITLE
"Go to Definition" Should Navigate to an Existing Tab in Another "Editor Group" by Default

### ISSUE THREAD

**Issue by MBetters** [microsoft/vscode#111236]
I have the definition of a symbol (a C struct in a header file) open in one "Editor Group" on the left. When I do a "Go to Definition" (F12 or Ctrl+Click) on that symbol in the other Editor Group I have on the right, I'd like it to navigate to that definition over in the Editor Group on the left where that header file is already open, instead of opening that header file again in the group on the right. I believe this to be the most intuitive default behavior.

After fishing through the settings for a while, I found that changing `workbench.editor.revealIfOpen` (which defaults to `false`) to `true` did the trick. I propose either renaming this setting to something more intuitive, or having an alias for it called something like `workbench.editor.goToDefinitionAllowedToCrossEditorGroups`.

**Comment by jrieken** [comment]
> or having an alias for it called something like workbench.editor.goToDefinitionAllowedToCrossEditorGroups.

I don't think that's a good name and I also dislike the idea of config aliases.

**Comment by jrieken** [comment]
Passing to @bpasero to tweak the description of the setting to be more generic or include more words about when this the setting is picked up

**Comment by bpasero** [comment]
> I propose either renaming this setting to something more intuitive

Sorry, but how is `workbench.editor.goToDefinitionAllowedToCrossEditorGroups` more intuitive than what we have today? This setting applies to everything, not just "Goto definition"?

**Comment by MBetters** [comment]
What about `workbench.editor.revealIfOpenInAnyGroup`?

**Comment by bpasero** [comment]
@MBetters but the setting description should be more than enough to understand it no?

![image](https://user-images.githubusercontent.com/900690/100190757-39665000-2eef-11eb-98a5-e9270e44e9e1.png)

**Comment by MBetters** [comment]
I think it would be a little clearer if the title of the setting mentioned Editor Groups, but it's not a big deal. It just took me a while to spot since I didn't know what I was looking for. I figured it might take other people a little while as well.
