### ISSUE TITLE
text's color is error when open a properties file

### ISSUE THREAD

**Issue by xiaoma20082008** [microsoft/vscode#111217]
- VSCode Version: 1.51.1
- OS Version: Darwin x64 19.6.0
- Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- Date: 2020-11-11T01:11:34.018Z (1 wk ago)
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0

Steps to Reproduce:

1. create a file, name is `abc.properties`
2. write follow text into it
```
ECHO001=EM: Can't read configuration from '{0}'
ECHO002=EM: Not a JIT shared lib: '{0}'
ECHO032=java version "1.5.0" \npre-alpha : not complete or compatible\nsvn = r{0}, ({1}), {2}/{3}/{4}, {5} build\nhttp://harmony.apache.org
ECHO033=Apache Harmony HEAD
ECHO034=Negative or invalid heap size. Default value will be used!
ECHO035={0}can't find starter class: java.lang.VMStart.
ECHO036={0}can't find java.lang.VMStart.initialize() method.
ECHO037={0}java.lang.VMStart.initialize() method completed with an exception.
ECHO038={0}can't find java.lang.System class.
ECHO039={0}can't find java.lang.System.execShutdownSequence() method.
ECHO040={0}java.lang.System.execShutdownSequence() method completed with an exception.
ECHO042=Verifier: {0}: null pointer for free

# DIE messages
# ============

LDIE001=no handling for pin overflow
LDIE002=Can't create heap_L
LDIE003=not enough reserved space for roots
LDIE004=ldc instruction: unexpected type ({0}) of constant pool entry [{1}]
LDIE005=non-constant type is requested from constant pool : {0}
LDIE006=Class {0} has no 'Object referent' field
LDIE007=Fatal GC error: compressed references are not supported.
LDIE008=Fatal GC error: managed pointers are not supported.
LDIE009=Cannot initialize properties pool
LDIE010=Cannot initialize properties table mutex
LDIE011=Cannot lock properties table
LDIE012=Cannot unlock properties table
```

the text's color is error, Theme is Dark+(default)

![image](https://user-images.githubusercontent.com/10076393/100072197-e8b31080-2e76-11eb-97ce-13fbbf52978d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I think the format of your file just isn't supported by our `ini` grammar. Maybe there is an extension you can install that will provide useful syntax highlighting?

**Comment by xiaoma20082008** [comment]
> I think the format of your file just isn't supported by our `ini` grammar. Maybe there is an extension you can install that will provide useful syntax highlighting?

@alexr00 

Maybe it's a bug in the vscode's `ini` grammar on the handle of character `'`.
if one line has two quote `''`, then the next line's color is correct , but if it only has one quote `'`, the next line's color is error.

**Comment by xiaoma20082008** [comment]
@alexr00 
Here is a pr that fixed the bug, maybe any of you can accept it. 
https://github.com/textmate/ini.tmbundle/pull/1
