### ISSUE TITLE
Emoji characters in col 40 of an empty file causes crash

### ISSUE THREAD

**Issue by inbn** [microsoft/vscode#111235]
- VSCode Version: 1.51.1
- OS Version: MacOS Mojave 10.14.6

Steps to Reproduce:

1. Open a new empty file
2. Paste the string "123456789012345678901234567890123456789🌞" (I think it only happens when the emoji appears in col 40)
3. The tab for the file shows the replacement character (� ) at the end of the label (screenshot below) and VSCode freezes
4. 'VSCode quit unexpectedly' dialog appears

<img width="523" alt="Screenshot 2020-11-24 at 14 54 57" src="https://user-images.githubusercontent.com/9019720/100110792-48082500-2e65-11eb-951a-a418f2c9d796.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@bpasero The untitled editor title cut-off logic should use `strings.getCharContainingOffset` to avoid splitting a grapheme. Here are other interesting graphemes you can use for testing:
```
ãããããã
辻󠄀辻󠄀辻󠄀
பு
```

**Comment by bpasero** [comment]
@alexdima I hope I am using it right:

https://github.com/microsoft/vscode/blob/84ce1317819a05f87e7d57cd27dbbc910b063383/src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts#L374-L377

**Comment by alexdima** [comment]
:+1: Looks good

**Comment by inbn** [comment]
/verified
👍 👍 
all fixed, thanks a lot!
