### ISSUE TITLE
opening project

### ISSUE THREAD

**Issue by vivekpaghadar** [microsoft/vscode#111270]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

I clicked the folder which i want to open in visual studio but it can't show in vs code

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (3.14GB free)|
|Process Argv|--crash-reporter-id 3cb5186d-5fe9-40a4-a63e-d8390301417e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   103	 13360	code main
    0	    12	  2100	   crashpad-handler
    1	    60	  8616	   window (Issue Reporter)
    1	   190	 12284	   gpu-process
    0	    24	 16016	   utility
    0	    65	 16404	   shared-process
    0	   135	 18108	   window (playground - Visual Studio Code)
    0	    30	  9304	     searchService
    0	    68	  9408	     extensionHost
    0	    16	  4024	       c:\Users\vivek\.vscode\extensions\tabnine.tabnine-vscode-3.1.12\binaries/3.2.22/x86_64-pc-windows-gnu/TabNine.exe --client=vscode --no-lsp=true --client-metadata clientVersion=1.51.1 pluginVersion=3.1.12 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 ide-restart-counter=0
    0	    12	  4180	         "c:\Users\vivek\.vscode\extensions\tabnine.tabnine-vscode-3.1.12\binaries/3.2.22/x86_64-pc-windows-gnu/TabNine.exe" --client=vscode --no-lsp=true --client-metadata clientVersion=1.51.1 pluginVersion=3.1.12 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 ide-restart-counter=0 --no_bootstrap
    0	   500	  9816	           "c:\Users\vivek\.vscode\extensions\tabnine.tabnine-vscode-3.1.12\binaries/3.2.22/x86_64-pc-windows-gnu/TabNine.exe" --client=vscode --no-lsp=true --client-metadata clientVersion=1.51.1 pluginVersion=3.1.12 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 ide-restart-counter=0 --no_bootstrap --inner
    0	    11	 17604	         console-window-host (Windows internal process)
    0	    25	 12444	       "C:\Users\vivek\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\vivek\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9408
    0	    11	 12352	     watcherService 
    0	    11	 17716	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (playground - Visual Studio Code)
|    Folder (playground): 6 files
|      File types: js(5) json(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.1.12

</details>

**Comment by ryanmagoon** [comment]
having the same issue in MacOS Big Sur 11.0.1

**Comment by gjsjohnmurray** [comment]
> I clicked the folder which i want to open

Where did you do this? Windows Explorer? Somewhere else?

**Comment by ryanmagoon** [comment]
> having the same issue in MacOS Big Sur 11.0.1

Turns out I had a full screen vs code window open and for some reason that was causing new windows to open with no project even though I was opening them from the terminal, and going through the open file dialog caused a no-op

exiting from my full screen session and restarting fixed it for me.
