### ISSUE TITLE
Pass objects with commands.executeCommand when remote

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#111238]
I have the Docker extension installed remotely in Remote-SSH and am invoking a command in the local Remote-Containers extension with the context menu in a view of the Docker extension with a single object as the selection. Currently the selected object is not passed along. Is there anything we can do here? Maybe allow sufficiently simple objects?

**Comment by jrieken** [comment]
> Currently the selected object is not passed along.

I assume that a custom tree, right? That should always pass the corresponding element around

**Comment by chrmarti** [comment]
Placing a breakpoint in CommandService.executeCommand shows a handle:
![image](https://user-images.githubusercontent.com/9205389/100198702-797fff80-2efc-11eb-9420-dc60ce820afe.png)

**Comment by jrieken** [comment]
So, just to make sure I am seeing the whole picture: The tree data provider is in one extension host and the command (implementation) in another. Is that right?

**Comment by chrmarti** [comment]
Correct, the Docker extension runs on the remote extension host and provides the tree data. The command is from the Remote-Containers extension running on the local extension host.

**Comment by jrieken** [comment]
Very trick, maybe not possible, because the objects never leave the extension host. Only identifiers/placeholders are send to the renderer and then looked up for command dispatch.

**Comment by chrmarti** [comment]
Maybe if the objects have a `toJSON()` (or some other name to disambiguate) method?

**Comment by jrieken** [comment]
What would we do if these objects are huge? The motivation from them staying in the extension host is 

* performance, like don't send data that isn't needed in the UI
* data must be serializable
* data isn't needed

I see how the last two aren't always valid (can be worked around) but I am not a big fan of us holding arbitrary amount of data in the UX.

**Comment by chrmarti** [comment]
We could set an upper-bound to the stringified size. If we require the extension to support it with `toJSON()` or similar the extension can tune it to be minimal. And we would only do this for commands that are on a different extension host.

**Comment by alexr00** [comment]
Let's see how often anyone actually wants this. Right now we have exactly one real use case and there are several downsides.

**Comment by mrmachine** [comment]
I am trying to use remote-containers and remote-ssh together, to do work inside a container running on a remote host. When I first open VS Code on the remote host via SSH, then view the container list in the Docker extension, then right click and `Attach Visual Studio Code` (to a specific container), VS Code brings up a list of ALL containers on the remote host which I must then further type to narrow and scroll to select from, even though I have already selected the container to which I want to attach (by right click).

**Comment by chrmarti** [comment]
This currently limits functionality when connected with Remote-WSL/-SSH. Affected commands:
- Attach to container from Docker viewlet.
- Inspect volume from Docker viewlet.
- Attach to container from Kubernetes viewlet.

Reopening for consideration.

**Comment by stardiviner** [comment]
upvote this issue.

**Comment by CoopTang** [comment]
Any idea on a fix for this? This disrupts my workflow and requires me to use my Mac when I need to debug a pod, and it would be nice to not have to constantly switch back and forth when developing.

**Comment by chrmarti** [comment]
There was some concern about serializing large objects. Maybe the receiving extension could declare (statically or dynamically) which properties on the selected objects it needs?

**Comment by jmarandet** [comment]
Thanks for your great job, very appreciated. I'm upvoting this issue, and also this one https://github.com/microsoft/vscode-remote-release/issues/5849 
any news about it ?
