### ISSUE TITLE
Disable all breakpoints except one

### ISSUE THREAD

**Issue by chiragpaliwal** [microsoft/vscode#111228]
Sometimes while debugging we may have loads of breakpoints; It would be convenient to disable all other breakpoints except the one that we clicked on.
Let's say while holding Alt or Ctrl if we press the breakpoint it disables all others except that one.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by matte-esse** [comment]
**I disagree and feel this issue is crucial**

**Comment by johncolvin-og** [comment]
I also feel this issue is crucial.  It seems like low-hanging fruit: very basic functionality, and easy to implement.  I would be very grateful if someone took a stab at it.  It's important enough to me that if no one else is up to it, I might try it myself when I have time outside of work (though tbh, I probably won't have the time to do it for a few months).

**Comment by weinand** [comment]
@johncolvin-og feel free to submit a PR that implements the feature, since we have the same problem: we won't have the time to do this anytime soon.

**Comment by TalKirsh** [comment]
I don't feel like this is suppose to be an addition but a day-1 mechanism.
A scenario, a custom common allocator for millions of different objects that i don't want to hit every single time, only when I get to a specific place in my project.
It's handy to just have this breakpoint set but disabled and then from the breakpoint windows just to enable it when needed.
I done this many time while working in Visual Studio.
All or nothing approach is never the solution. Suppose I'd want to close a file or stage/destage in Git and it'd be all or nothing.
Disable individual breakpoints will help a lot.
Thanks.

**Comment by GentilsTo** [comment]
Any update on this ? As other mentionned this is a must have for me. When debugging/dev long running process, you might setup numerous of breakpoint that you want to keep, but at some point you just want to rush to the latest (or specific one), without having to F5 countless of time
