### ISSUE TITLE
on macOS, find fails to use the shared find clipboard

### ISSUE THREAD

**Issue by akrabat** [microsoft/vscode#111286]
- VSCode Version: `Version: 1.51.1, Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f`
- OS Version: `macOS Catalina 10.15.7 (19H15)`
- Also tested VSCode Insiders: `Version: 1.52.0-insider, Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5`
Steps to Reproduce:

1. In Safari (or BBEdit, Sublime Text, TextEdit, Firefox or Chrome) select some text and press `cmd+e`.
2. In VS Code, press `cmd+g`
3. Note that the selected text from Safari is not used to "find next". I expected VS Code to find the text I had added to the find clipboard in Safari.
4. Similarly, if I use `cmd+e` or `cmd-f` to find some text in VS Code, I cannot use `cmd+g` in Safari to find the next occurrence of the string that I just used for finding in VSCode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
Please try to set `editor.find.globalFindClipboard` to true.

**Comment by akrabat** [comment]
Aha! Thank you.
