### ISSUE TITLE
Debugger Environment Variables Bleed Between Extension Host Launch Configs

### ISSUE THREAD

**Issue by dsanders11** [microsoft/vscode#111279]
- VSCode Version: 1.51.1
- OS Version: Windows 10

`launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run Extension A",
      "type": "extensionHost",
      "request": "launch",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}"
      ],
      "outFiles": [
        "${workspaceFolder}/out/**/*.js"
      ],
      "preLaunchTask": "${defaultBuildTask}"
    },
    {
      "name": "Run Extension B",
      "type": "extensionHost",
      "request": "launch",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}"
      ],
      "outFiles": [
        "${workspaceFolder}/out/**/*.js"
      ],
      "env": {
        "FOO": "BAR"
      },
      "preLaunchTask": "${defaultBuildTask}"
    }
  ]
}

```

Steps to Reproduce:

1. Use the above `launch.json` to debug an extension
2. Use "Run Extension A", observe that `process.env.FOO` is undefined. End debugger.
3. Use "Run Extension B", observe that `process.env.FOO` is defined. End debugger.
4. Use "Run Extension A" again, observe that `process.env.FOO` is still defined, when that's unexpected.

It seems that the environment variables are being set in a persistent way, so once it is set in one configuration, it will also be set when another is run. Unsetting them by using `null` has no effect, so it's likely at a level below that. My only work around is to set it on both configurations with different values.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dsanders11** [comment]
Ugh, I did try searching first. Sorry about that.

**Comment by weinand** [comment]
@dsanders11 no problem.
