### ISSUE TITLE
Add option to open file without source control

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#111216]
Usually, when I open a single file directly, I am not interested in having it's project added to my source control view or my explorer view. For example, I want to compare a file in my working tree to the same file in a colleagues working tree. As soon as I open the file, it adds his git root to my source control, and after I close it I have to go closing the extra source control, and sometimes also a new root in the explorer view.

It would be nice to have an option (in my opinion, it should be the default) to just open a file without it causing anything to be added to any of the sidebar views.

**Comment by joaomoreno** [comment]
You can set `git.autoRepositoryDetection` to `subFolders`.
