### ISSUE TITLE
vscode change remot file owner when saving

### ISSUE THREAD

**Issue by inkquery** [microsoft/vscode#111219]
I don't know why, but for a particular file always the same on every server where it's located owner is modified when saving it.

Of course all files have same persmissions.

Before editing file owner is 'apache' then owner is set to 'root'.
That behavior occurs only for that file, others keep 'apache' as owner on saving.

I tried another IDE, problem not occurs.

**Comment by bpasero** [comment]
What kind of remote setup is this?
