### ISSUE TITLE
I cant find MKS BOARDS and don't know the problem and forgot githup username

### ISSUE THREAD

**Issue by cdscd** [microsoft/vscode#111200]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\sgen\Marlin-2.0.x> platformio run -e LPC1768
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; board: nxp_lpc1768; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
ModuleNotFoundError: No module named 'platformio.managers.package':
  File "C:\users\account\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 168:
    env.SConscript(item, exports="env")
  File "C:\Users\ACCOUNT\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
  File "C:\Users\ACCOUNT\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\sgen\Marlin-2.0.x\buildroot\share\PlatformIO\scripts\common-dependencies.py", line 12:
    from platformio.managers.package import PackageManager
=========================================================== [FAILED] Took 0.95 seconds ===========================================================
Environment    Status    Duration
-------------  --------  ------------
LPC1768        FAILED    00:00:00.953
===================================================== 1 failed, 0 succeeded in 00:00:00.953 ===================================================== 
PS C:\sgen\Marlin-2.0.x> echo "done" >C:\Users\ACCOUNT\AppData\Local\Temp\ipc
PS C:\sgen\Marlin-2.0.x>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
