### ISSUE TITLE
Apple Silicon: error with keychain

### ISSUE THREAD

**Issue by ItalyPaleAle** [microsoft/vscode#111271]
Version: 1.52.0-exploration
Commit: 88c7381b77df9601914ca914f80c700fee35825a
Date: 2020-11-20T09:15:28.497Z (4 days ago)
Electron: 11.0.2
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0

Steps to Reproduce:

1. On a fresh install, enable settings sync (using the Stable channel)
2. Sign in with a GitHub account
3. After logging in on the browser, go back to VS Code Exploration
4. The error below appears:
![image](https://user-images.githubusercontent.com/43508/100183894-fd060600-2e94-11eb-835d-bda3321f6c16.png)

Despite the error, settings to start syncing. And then the window crash multiple times... until it works! (probably connected to #111091?)

Does this issue occur when all extensions are disabled?: Fresh install w/ no extensions

**Comment by deepak1556** [comment]
Oh weird the keytar module is built for x64, looks like cross-compiling didn't work.

**Comment by deepak1556** [comment]
I am currently using electron-prebuild to cross-compile native modules, and it looks like the package doesn't rebuild prebuilt modules from source https://github.com/electron/electron-rebuild/blob/master/src/module-rebuilder.ts#L296. Keytar is the only prebuilt module we have now, I will add a separate rebuild step for it.

**Comment by roblourens** [comment]
@deepak you will probably have to verify this one yourself...

**Comment by ItalyPaleAle** [comment]
@roblourens I can confirm that it is working on the latest Exploration build

**Comment by roblourens** [comment]
Thanks!
