### ISSUE TITLE
Extensions tab not loading

### ISSUE THREAD

**Issue by BearJere** [microsoft/vscode#111266]
- VSCode Version: 1.51.1
- OS Version: Mac OS X 11.0

Steps to Reproduce:

1. I don't know, I just opened vsc for the first time on this computer. Nothing appears when I attempt to search for an extension. I can't download any from the website or from VSIX.

Does this issue occur when all extensions are disabled?: No
<img width="1388" alt="Screen Shot 2020-11-24 at 11 17 32 PM" src="https://user-images.githubusercontent.com/48743034/100182698-3ea1ab80-2eab-11eb-99b4-4b802cd1c844.png">

**Comment by sandy081** [comment]
Please share the logs from the following locations
- Help -> Toggle Developer Tools -> Console
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

Also check if there are network request failures
- Help -> Toggle Developer Tools -> Network

**Comment by BearJere** [comment]
Help -> Toggle Developer Tools -> Console:
`ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.`

View -> Command Pallette... -> Toggle Shared Process -> Console:
`Uncaught (in promise) Error: There is an instance already running.
    at sharedProcessMain.ts:296
    at /Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/async file:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:639
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/applicationinsights.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Logging.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/initialization.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Console.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Exceptions.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Performance.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Util.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/RequestResponseHeaders.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Constants.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/AvailabilityData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Domain.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Base.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ContextTagKeys.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Data.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPointType.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPoint.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Envelope.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/EventData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MessageData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionDetails.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MetricData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/PageViewData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RemoteDependencyData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RequestData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/SeverityLevel.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/StackFrame.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/TelemetryType.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/RequestParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/CorrelationIdManager.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpRequestParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpRequests.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/NodeClient.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/TelemetryClient.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Config.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Context.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Channel.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/TelemetryProcessors/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/TelemetryProcessors/SamplingTelemetryProcessor.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Sender.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/EnvelopeFactory.js.map: Unknown error`

View -> Open View… -> Log (Shared):
Doesn't seem to be one, only Log (Main), Log (Extension Host) and Log (Window)

View -> Open View… -> Log (Window):
`[2020-11-25 08:03:33.799] [renderer3] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
[2020-11-25 08:04:54.135] [renderer3] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.`

No network request failures, it seems.

**Comment by sandy081** [comment]
> View -> Open View… -> Log (Shared):
Doesn't seem to be one, only Log (Main), Log (Extension Host) and Log (Window)

Seems shared process connection issues as shared process log is not available. I do not know why the shared process console could be opened.

**Comment by BearJere** [comment]
I'll try that, but I seemed to have installed an extension using the terminal, even though the extensions tab is still not working.

**Comment by BearJere** [comment]
I tried again and it worked. Fixed itself I guess?
