### ISSUE TITLE
Pasted Chinese characters shown as unrecognized characters 

### ISSUE THREAD

**Issue by elegracer** [microsoft/vscode#111272]
- VSCode Version: 1.51.1
- OS Version: Arch Linux

vscode's help->about content
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.10-arch1-1
```

Steps to Reproduce:

1. Create 2 files whose names are respectively `一个普通的文件` and `另一个普通的文件` inside my home directory
2. Select both of them in Dolphin (File Manager of KDE)
3. Copy them using `ctrl + c`
4. Paste them inside vscode

The pasted text will be
```
file:///home/MY_USERNAME/ä¸€ä¸ªæ™®é€šçš„ç©ºæ–‡ä»¶
file:///home/MY_USERNAME/å¦ä¸€ä¸ªæ™®é€šçš„ç©ºæ–‡ä»¶
```

Additional information:

When they are pasted to another electron-based app, the same thing will happen.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Heesz** [comment]
Same with cyrillic symbols

**Comment by deepak1556** [comment]
Is this issue present with latest stable `1.85` ?

**Comment by elegracer** [comment]
Sorry, I'm not using Arch Linux anymore. Now I'm not able to check this out.

**Comment by deepak1556** [comment]
Thanks for confirming, closing as not actionable.
