### ISSUE TITLE
Implement interface is not working (Typescript)

### ISSUE THREAD

**Issue by grapevinegizmos** [microsoft/vscode#111267]
Issue Type: <b>Bug</b>

(Typescript)
I have an interface I defined call DataService, and I am creating a class called MockDataService for testing purposes.  For some reason the UI refuses to implement interface with the usual stubs.

Here is code for DataService interface:

```
export interface DataService {
  currencyPipe: CurrencyPipe;
  http: HttpClient;
  _fs: AngularFirestore;
  _afAuth: AngularFireAuth;
  auth : AuthService;
  budget : BudgetService;
  project : ProjectService;
  assets : AssetCatalogService;
  expressions : NamedExpressionService;
  fringes : FringeService;
  lastId: string;
  createId() : string;
  getTimestampNow() : number;
  account : AccountService;
  lineItem : DetailRowService;
  currency : CurrencyService;
  _auth : AuthServiceClass;
  _budget : BudgetServiceClass;
  _project : ProjectServiceClass;
  _account : AccountServiceClass;
  _lineItem : DetailRowServiceClass;
  _currency : CurrencyServiceClass;
  _expression : NamedExpressionServiceClass;
  _fringe : FringeServiceClass;
  openBudgetId : string;
  createBatch() : firestore.WriteBatch;
  isAuthenticated : boolean;
  assertAuthenticated() : boolean;
  assertAuthenticatedUserId(userId: string, source?: string): boolean;
  getDocument(path: string): Promise<any>;
 _count: number;
  counter : number;
  putDocument(collectionPath: string, object: HasId): Promise<boolean>;
  updateDocument(collectionPath: string, object: HasId): Promise<boolean>;
  deleteDocument(collectionPath: string, documentId: string): Promise<boolean>;
  getCollection(collectionPath: string, orderByFieldName?: string): Promise<object[]>;
  getFilteredOrderedCollection<T extends HasId>(collectionPath: string, filterField: string, filterValue: string, orderByField: string, descending?: boolean): Promise<T[]>;
  getFilteredCollection(collectionPath: string, fieldName: string, value: string): Promise<object[]>;
  deleteCollection(path: string): Promise<boolean>;
  validateDocOwner(path: string): Promise<boolean>;
  assertHasId(object: any): boolean;
  checkIdAndCreate(obj: HasId): void;
}

```
Here are images of the UI where I am attempting to implement by highlight 1MockDataService` and pressing cmd .

![image](https://user-images.githubusercontent.com/8684037/100181944-4142d780-2e90-11eb-8341-359794482ca0.png)

Here is the code where I am trying to implement the interface.

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 18.7.0
![image](https://user-images.githubusercontent.com/8684037/100182356-3fc5df00-2e91-11eb-9990-6edeef1462d1.png)

As you can see, I'm not offered the option to implement the interface, only to move to a new file and "learn more".
This has worked at other times I've used it.  I've tried reloading the windows, as well and no joy.  The app is compiling normally and tests are passing.

Thoughts, suggestions?

:
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id a2566247-d7b6-4b99-a270-ab36a18a985b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Please share a self contained project that demonstrates this issue

**Comment by grapevinegizmos** [comment]
Hm.  not so easy.  usually it works fine.   my current application is too big to easily stuff into a small package and i can't figure out what causes this not work to demo in a small standalone.

i'll just work around it for now.  thanks

**Comment by mjbvz** [comment]
Unfortunately without steps to reproduce, we cannot investigate or fix this issue.

Closing but please share a self contained example if you have a chance
