### ISSUE TITLE
VS Code catch system hot key used by File Manager

### ISSUE THREAD

**Issue by BackMountainDevil** [microsoft/vscode#111273]
- VSCode Version: 1.51.1
- OS Version: Linux Deepin 20 Commiunity amd64

Steps to Reproduce:

1. Install VS Code
2. Press " Win + E ", then the system will start VS Code instead of File Manager.

Same situation on [deepin commiunity](https://bbs.deepin.org/post/206172?id=206172&limit=20&offset=0&postId=1161380):  The hot key  " Win + E " shoule open File Manager, when VS Code come, it changed. Although I change the hot key(such as win+tab) to start File Manager in my system setting, it still open VS Code. And before, it is ok with VS Codium. Then I come for VS Code for there are few extensions in VS Codium's market

Does this issue occur when all extensions are disabled?: Yes ( Only "Language pack extension for Chinese (Simplified)" can not be disabled, others are disalbed)

**Comment by joaomoreno** [comment]
> Press " Win + E ", then the system will start VS Code instead of File Manager.

I believe this is a problem of configuration of your Linux Deepin OS. VS Code doesn't add any global shortcuts to the OS like that.

**Comment by BackMountainDevil** [comment]
> > Press " Win + E ", then the system will start VS Code instead of File Manager.
> 
> I believe this is a problem of configuration of your Linux Deepin OS. VS Code doesn't add any global shortcuts to the OS like that.

Thank you, I have reported that to the Deepin Community. And I find a [solution](https://github.com/microsoft/vscode/issues/109807).
And I find that I never search issue in 'close'. Just search in 'open'. apology for my mistake.
