### ISSUE TITLE
Is there any way to extend vscode's default typescript language service?

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#111285]
Hello, 

I'm developing an extension which extends typescript's intelliSense completion. Does vscode's default typescript language service expose APIs to external extension to 

  1. get valid variables in current scope
  2. get completion result at given position
  3. get all imported names

I found typescript's default language service provides plugin: https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin, but I have no idea about how to implement a plugin to overwrite vscode's typescript language service. If you have any suggestions, please comment here. Thanks very much!

**Comment by egamma** [comment]
Please see https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin.

**Comment by HaoboGu** [comment]
> Please see https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin.

I have read this, but it seems that it requires users to set a complier plugin under their own project, not the extension writers.
