### ISSUE TITLE
Searches for files with a specific suffix under a specific path

### ISSUE THREAD

**Issue by xinxuantt** [microsoft/vscode#111204]
For example, if I search for.c file in my project directory in the search menu, I write it as"./Project/,*.c", and it works normally.But if the path is too long, you can't search, so let's say I write "./Project/aaa/bbb/ccc/ddd/,*.c",It will find .c .h .mak, and so on

**Comment by roblourens** [comment]
You can search with patterns like `project/**/*.c`. Comma-separated patterns are independent
