### ISSUE TITLE
Divs in html don't make match

### ISSUE THREAD

**Issue by FructuosoRobles** [Microsoft/vscode#11121]
- VSCode Version: 1.4.0
- OS Version:

HTML tags not matching I cannot see where my div ends in a large html, Im using .ejs engine

**Comment by aeschli** [comment]
You can see the location of the closing tag in the overview ruler.
![image](https://cloud.githubusercontent.com/assets/6461412/18325258/bd1b0a02-7540-11e6-8ce8-820f6dde92e2.png)

That's HTML files. 
Does that not work for you?

**Comment by FructuosoRobles** [comment]
Yes I can see that. But I have hundreds of divs and when I point one all of
the rest flash and I dont know where is the one I am looking for

El 7 sept. 2016 2:20 PM, "Martin Aeschlimann" <notifications@github.com>
escribió:

You can see the location of the closing tag in the overview ruler.
[image: image]
<https://cloud.githubusercontent.com/assets/6461412/18325258/bd1b0a02-7540-11e6-8ce8-820f6dde92e2.png>

That's HTML files.
Does that not work for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/11121#issuecomment-245387458>,
or mute the thread

**Comment by aeschli** [comment]
In the HTML editor, we only highlight the corresponding div. What's your editor mode?
![image](https://cloud.githubusercontent.com/assets/6461412/18338885/4943a09c-759c-11e6-9662-3570f711f327.png)

**Comment by FructuosoRobles** [comment]
Ejs

**Comment by aeschli** [comment]
Oh, so that's probably provided by an extension. You have to file the issue there.

**Comment by FructuosoRobles** [comment]
thank you


2016-09-08 1:25 GMT-05:00 Martin Aeschlimann <notifications@github.com>:

**Comment by druellan** [comment]
Hi! I can reproduce the problem on the PHP editor. The HTML editor seems to work fine, but the PHP editor is not matching the tag pair, but all instances of the tag, including comments:

![2016-12-09_09h47_34](https://cloud.githubusercontent.com/assets/6965667/21049586/84e18678-bdf4-11e6-9dff-4a430440433d.png)

**Comment by druellan** [comment]
Related to #2915
