### ISSUE TITLE
Autofix for ts(1308) on save yields invalid code

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/vscode#111298]
- VSCode Version: 1.51.1
- TypeScript Version: 4.0.5
- OS Version: Pop!_OS 20.04

Steps to Reproduce:

1. Open VSCode
1. Create a TypeScript file
1. Add the following content:
   ```ts
   function foo() {
     await bar();
     await bar();
   }
   ```
1. Run the `Fix all` quick action
1. Notice the file contents have changed to:
   ```ts
   async async function foo() {
     await bar();
     await bar();
   }
   ```

An `async` keyword is prepended to the function for each `await` instance inside the function body.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Needs proper support from TS: https://github.com/microsoft/TypeScript/issues/29452
