### ISSUE TITLE
Launching VSC from startmenu Source Control do not ask for passphrase

### ISSUE THREAD

**Issue by MaKaNu** [microsoft/vscode#111295]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Starting ```code``` from gitbash
1. Enter passphrase for ssh-key
1. push/pull a repo with Source Control
1. Enter passphrase for ssh-key again
1. close vscode

1. Starting VSCode from startmenu
1. No passphrase question
1. push/pull a repo with Source Control
1. getting error message:
1. Open Git Log:

```bash
> git pull --tags origin main
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
> git ls-files --stage -- D:\Mitarbeiter\Kaupenjohann\09_GIT\MSA\latex_report_template-matti\Dissertation.tex
> git cat-file -s d272c0e70eef6b3827b58c71e7d3187bb4843f20
> git show --textconv :latex_report_template-matti/Dissertation.tex
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse main
> git rev-parse --symbolic-full-name main@{u}
> git rev-list --left-right main...refs/remotes/origin/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname)
> git remote --verbose
> git config --get commit.template
```

1. Testing all these commands in CMD
1. realizing all works fine and also asks if needed for passphrase
1. Source Control still doesn't ask for passphrase

The Problem seems to be that, if VSC is launched over the startmenu the source control is not checking for the configurations. Also implemented sshCommands inside the git config are ignored.

Does this issue occur when all extensions are disabled?: Yes with launching from CMD No with launching from gitbash

**Comment by liquidcms** [comment]
I have same issue with:
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

VSC does not request passphrase and then fails authentication without it.

**Comment by lszomoru** [comment]
@MaKaNu, @liquidcms this issue has completed fallen off our radar.  
Are you still experiencing the same issue with the latest version of VS Code?

**Comment by MaKaNu** [comment]
I need to test this again. I switched in the meantime back to gitkraken for source control. I might be able to test it tomorow.

**Comment by MaKaNu** [comment]
Sorry many things at the moment. I was now able to test this again and can confirm this problem still exists. I repeat the test Workflow because I am unsure if my today test procedure fits the original completly but the results are similar:

1. open gitbash
2. create new key with password
3. add ssh-github-config
```
Host github.com                                                                         
    HostName github.com
    User git
    IdentityFile C:\\Users\\User\\.ssh\\github
```

4. clone repo
5. enter passphrase
6. open vscode from gitbash
7. apply changes & push
8. enter passphrase
9. close vscode
10. open vscode from startmenu
11. apply changes & push

result:

```
[2022-03-22T15:21:41.960Z] > git ls-files --stage -- G:\TEST\PytorchLabs\README.md [66ms]
[2022-03-22T15:21:42.028Z] > git cat-file -s 824acb1862331dfe4d9673626015f1e1da10e23b [65ms]
[2022-03-22T15:21:50.680Z] > git log --oneline --cherry master...master@{upstream} -- [73ms]
[2022-03-22T15:21:51.551Z] > git pull --tags origin master [868ms]
[2022-03-22T15:21:51.551Z] git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by lszomoru** [comment]
We have added support for SSH keys with a passphrase in the [September 2022 release](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase). 
I will go ahead and optimistically close this issue but please feel free to reopen it in case you are still seeing issues. Thank you very much!
