### ISSUE TITLE
Slow VSCode lagging while scrolling / highlighting

### ISSUE THREAD

**Issue by NaturalFigurehead** [microsoft/vscode#111248]
Issue Type: <b>Performance Issue</b>

A couple months ago I started noticing slow performance on VSCode particularly when scrolling or highlighting a file or switching between files. Restarting VSCode or closing all other apps besides VSCode didn't help. Restarting the computer did fix the issue for a short time but after an hour or so the slow performance would return. 

The problem persists after disabling all extensions. Insiders version is laggy as well. If I scroll up and down repeatedly the CPU% spikes according to the Process Explorer. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|62.10GB (42.66GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Oliver/source/repos/vizfly/vizfly/Vizfly.WebApplication/ClientApp --crash-reporter-id 68109aca-2f1b-47d6-b866-c06bccd2d738|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 20096	code main
    0	   213	  9628	   window (WaveCircle.js - ClientApp - Visual Studio Code)
    0	    12	  3812	     watcherService 
    0	    11	 28120	       console-window-host (Windows internal process)
    0	     5	 18892	     "C:\Program Files\Git\bin\bash.exe"
    0	    10	 22268	       "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    94	 21784	     extensionHost
    0	   104	  3360	       electron_node tsserver.js 
    0	   174	 35280	       electron_node tsserver.js 
    0	    80	 33016	         electron_node typingsInstaller.js typesMap.js 
    0	     6	 33388	     console-window-host (Windows internal process)
    0	    36	 10596	   utility
    0	    80	 17396	   window (Issue Reporter)
    0	    88	 28152	   shared-process
    0	   104	 28684	   gpu-process
    0	    23	 29164	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (WaveCircle.js - ClientApp - Visual Studio Code)
|    Folder (ClientApp): 290 files
|      File types: js(94) jsx(91) ttf(31) json(7) png(3) gitignore(1)
|                  code-workspace(1) ico(1) mp4(1) svg(1)
|      Conf files: package.json(1);
```

</details>
Extensions: none

**Comment by egamma** [comment]
Please provide a performance profile when you observe the slow down following this guide: https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

**Comment by NaturalFigurehead** [comment]
Here's a screenshot of the process explorer that occurs as I'm highlighting.

![proexp (3)](https://user-images.githubusercontent.com/7815878/100158476-dbdfee00-2e71-11eb-9a2b-f7fdfc853439.png)

**Comment by egamma** [comment]
@NaturalFigurehead thank you for the screenshot from the process explorer. To understand the details of the performance problem we need a performance profile. It is straightforward to produce such a profile by following the steps described here https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process.

**Comment by NaturalFigurehead** [comment]
Ok here's the profile.

[CPU-20201125T081113.txt](https://github.com/microsoft/vscode/files/5597223/CPU-20201125T081113.txt)

**Comment by alexdima** [comment]
@NaturalFigurehead I have looked at the CPU profile, but there is nothing that appears to originate from our JS on the UI thread. I do see an entry for `(program)`, which indicates that the profiler did not hit a JS stack, so perhaps the renderer process is busy doing something Electron. Does it help to close all vscode instances and execute `code --disable-gpu` or `code --disable-renderer-accessibility`

Also cc @deepak1556 if you have any ideas.

**Comment by NaturalFigurehead** [comment]
@alexdima `code --disable-renderer-accessibility` resolved the issue.

**Comment by deepak1556** [comment]
thanks for testing, merging to https://github.com/microsoft/vscode/issues/107016
