### ISSUE TITLE
vscode do not support big number well, which passed in launch.json

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#111203]
- VSCode Version:1.51.1
- OS Version:win10 18363.1198

Steps to Reproduce:

my extension  registers a DebugAdapter.

1. config big number in project launch.json

```
  {
      "type": "scrypt",
      "request": "launch",
      "name": "Debug Demo",
      "program": "${workspaceFolder}/contracts/demo.scrypt",
      "constructorParams": [
        182152777611009147713961771110418164117488507161007978051976495741490223813325323875256303997022886706984087636507589369803363244783178649156051633951688639959604528889695,
        30
      ],
      "entryMethod": "add",
      "entryMethodParams": [
        42
      ]
    }
```
2. start my debuger , but I got "1.8215277761100915e+170" in a DebugProtocol launchRequest as below ， which cannot be accurately converted to "182152777611009147713961771110418164117488507161007978051976495741490223813325323875256303997022886706984087636507589369803363244783178649156051633951688639959604528889695"

```
{
   "command":"launch",
   "arguments":{
      "type":"scrypt",
      "request":"launch",
      "name":"Debug Demo",
      "program":"C:\\\\Users\\\\myland\\\\code\\\\boilerplate/contracts/demo.scrypt",
      "constructorParams":[
         1.8215277761100915e+170,
         30
      ],
      "entryMethod":"add",
      "entryMethodParams":[
         42
      ],
      "__configurationTarget":5,
      "__sessionId":"f00ed20d-4dcc-4de7-a0c3-50c0e40d6e0e"
   },
   "type":"request",
   "seq":2
}
```

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
JSON (which is part of JavaScript) has only limited precision. See https://www.w3schools.com/js/js_numbers.asp:
> ... Integers (numbers without a period or exponent notation) are accurate up to 15 digits.

If you want to avoid errors related to precision, you'll have to serialize  large numbers as strings and handle then in Javascript using libraries like bignumber.js
