### ISSUE TITLE
Test Scrolling and Folding API commands

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11127]
Test for #9609 and #9786

- [x] Any OS **@weinand**

Complexity 4

## Set up

- Clone the repository [VS Code Extension Samples](https://github.com/Microsoft/vscode-extension-samples)
- Go to the folder **vim-sample** and do npm install
- Open VS Code on **vim-sample**
- Run the extension using Launch Extension. 

This will run Vim sample extension and is referred as Vim editor from here after. Verify following scenarios on this. 

## Good to know

- Vim editor has basically 3 modes: `Normal`, `Visual`, `Edit`.

### Mode change
- Press `i` for edit mode when in normal or visual mode.
- Press `esc` for normal node when in edit mode.
- Press `v` for visual mode when in normal mode.

### Line vs wrapped line
A line is a complete line that can consists of one or more wrapped lines in the screen.

**Note**: All of these scenarios have to be tested in **non-edit mode**
**Note**: When window scrolls downwards, cursor/lines move upwards and vice-versa

### Test up and down scrolling
- <kbd>ctrl</kbd> + <kbd>e</kbd> Scroll window 1 line downwards
- 🔢 <kbd>ctrl</kbd> + <kbd>e</kbd> Scroll window N lines downwards
- <kbd>ctrl</kbd> + <kbd>d</kbd> Scroll half window lines downwards
- 🔢 <kbd>ctrl</kbd> + <kbd>d</kbd> Scroll N half window lines downwards 
- <kbd>ctrl</kbd> + <kbd>f</kbd> Scroll one window lines downwards
- 🔢 <kbd>ctrl</kbd> + <kbd>f</kbd> Scroll N window lines downwards

- <kbd>ctrl</kbd> + <kbd>y</kbd> Scroll window 1 line upwards
- 🔢 <kbd>ctrl</kbd> + <kbd>y</kbd> Scroll window N lines upwards
- <kbd>ctrl</kbd> + <kbd>u</kbd> Scroll half window lines upwards
- 🔢 <kbd>ctrl</kbd> + <kbd>u</kbd> Scroll N half window lines upwards
- <kbd>ctrl</kbd> + <kbd>b</kbd> Scroll one window lines upwards
- 🔢 <kbd>ctrl</kbd> + <kbd>b</kbd> Scroll N window lines upwards

Make sure during scrolling, cursor is always revealed in the current window.

### Test revealing current line
- <kbd>z</kbd> + <kbd>t</kbd> Reveals current line at top of window
- <kbd>z</kbd> + <kbd>z</kbd> Reveals current line at center of window
- <kbd>z</kbd> + <kbd>b</kbd> Reveals current line at bottom of window

### Test folding / unfolding
- <kbd>z</kbd> + <kbd>c</kbd> Close one fold under the cursor.
- 🔢 <kbd>z</kbd> + <kbd>c</kbd> Close N folds deep under the cursor.
- <kbd>z</kbd> + <kbd>o</kbd> Open one fold under the cursor.
- 🔢 <kbd>z</kbd> + <kbd>o</kbd> Open N folds deep under the cursor.

**Comment by rebornix** [comment]
As VSCodeVim is doing differently as Vim example, I'd like to test against latest VSCode Vim bits as well. The only difference is the setup steps

- [ ] any OS

* Clone the repository [VSCodeVim](https://github.com/VSCodeVim/Vim)
* Install dependencies by following https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md#first-time-setup
* Open VS Code on VSCodeVim
* Run the extension using Launch Extension.

Complexity-4 as well.

**Comment by aminroosta** [comment]
@sandy081 As you know i'm not a fan of `cursorMove` at all 😄 

But i found a bug while working around every single principle in VsCodeVim to get things done.

```js
      await vscode.commands.executeCommand("cursorMove", {
        to: "up",
        by: "wrappedLine",
        select: false,
        noOfLines: noOfLines
      });
```

`noOfLines` has no effect, none! It just gets ignored.
