### ISSUE TITLE
#newFeature how to sync all extensions and setting to another machine

### ISSUE THREAD

**Issue by sandeep100690** [Microsoft/vscode#11125]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by joaomoreno** [comment]
https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by michaeljota** [comment]
Hi! I already use that extension, but I think it would be better if this is integrated into the VS. It maybe beyond the scope that another extension can provide. Microsoft have already a great ecosystem with the Microsoft Account.

I know that some folk may not be willing to use one of those, but at least it would be great to have the option to do it, even if it is not the default behavior. 

PS: Yes, I know about the other extension that use other services like OneDrive, on Google Drive, but again, it would be better if this is integrated in the editor. Anyone who use the editor in more than one machine would appreciate this. 

Thanks you! Amazing editor. I really don't use anything else right not. (Well... I use Android Studio, but just for Android native dev :wink: )
