### ISSUE TITLE
Multiple cursors enabled unintentionally with nested snippets

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#111284]
Multiple cursors enabled unintentionally with nested snippets. Related to #87226. I can reproduce the issue easily although it is labeled as `wont-fix`.

Version: 1.52.0-insider
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:40:30.987Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

Steps to Reproduce:

1. Set the following snippet and shortcut.
```json
{
	"paren": {
		"prefix": "paren",
		"body": "( $1 )$0"
	}
}
```

```json
    {
        "key": "alt+a",
        "command": "editor.action.insertSnippet",
        "args": { "name": "paren" }
    }
```

2. Enter `Alt+a` several times.
3. Multiple cursor enabled.

![Nov-25-2020 18-38-51](https://user-images.githubusercontent.com/10665499/100209864-b4f6ea00-2f4d-11eb-9513-8c12ddb39541.gif)

It is better for us to have an easy reproducible step anyway.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
> I can reproduce the issue easily although it is labeled as wont-fix.

Won't fix means an issue is reproducible and acknowledged but the effort to fix an issue isn't in proportion to the negative impact it has. 

Closing this issue as duplicate
