### ISSUE TITLE
source control - discard all changes button

### ISSUE THREAD

**Issue by buffalus** [microsoft/vscode#111263]
My whole project was deleted when accidentally click the discard all changes button.

There is no comitt before. How can I recover the all files?

This discard all changes button is designed so poor because it does not give hint to user for the disastrous effect. The better way should be using command line with hint.

Thanks

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including VSCode version and platform.

You should have been given a warning dialog including some UPPERCASE TEXT. Did this not happen. 

Sorry to hear about your code loss.
