### ISSUE TITLE
Support changing default Symbol icons based on symbol information.

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode#111256]
Hi i would like the change the default symbol icons that are shown for certain symbols in my extension for my language server. It would be really useful if there is a optional extension point where i can inspect the symbol info and provide my own icon instead of the default one.

Some background is that my language server returns symbols as interface kind. But based on the symbol information i want to provide different icons. The symbol name has a specific naming convention to decide this.

**Comment by dbaeumer** [comment]
This is IMO unrelated to LSP. VS Code itself has no API to change the icon of a symbol. Assigning to @jrieken
