### ISSUE TITLE
keybord shotcuts editor to show the commands when it exists

### ISSUE THREAD

**Issue by kahsa** [microsoft/vscode#111276]
When editing "Add keybinding" it is helpful if it shows what the commands are that already exits.
otherwise going back to the previous seletion requires doing the same thing again...

for example
![Keyboard Shortcuts_002](https://user-images.githubusercontent.com/52106048/100197230-62adcd00-2f3d-11eb-882c-7a214c2c5d30.png)

or after clicking and showed that existing command,  make going back to previous state easily, for exaple dropdown box of input history stuff like that.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/99530
