### ISSUE TITLE
Can't Change User Font Family

### ISSUE THREAD

**Issue by AbdianRizky** [microsoft/vscode#111247]
- VSCode Version: 1.51.1
- OS Version: Windows 10 10.0.19041.508

Steps to Reproduce:

1. reinstall the font 
2. uninstall the font
3. install another font
4. use another font
5. reload vscode
6. Change editor.fontFamily in settings.json
7. Restart VSCode
8. Editor font remains the default

I'm trying to use **Jetbrains Mono** font and didn't work. but default font is no problem at all

Does this issue occur when all extensions are disabled?: Yes

![error](https://user-images.githubusercontent.com/62763773/100140505-9d731f00-2ec3-11eb-9097-91e8a501d482.png)

**Comment by alexdima** [comment]
@AbdianRizky This appears to be an installation problem. Can you use the font correctly in other applications?

**Comment by AbdianRizky** [comment]
Yes, i can use the font in other code editor.

And all done well when i restart the computer. I'm sorry, my bad
