### ISSUE TITLE
When replacing with regexes, there's no way to append digits to the end of a match group

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#111213]
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
You can find the steps here: https://stackoverflow.com/questions/64981403/when-replacing-with-regexes-how-do-i-append-digits-to-the-end-of-a-match-group/64981553#64981497

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Javascript now supports named capture groups, we should support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

**Comment by ArturoDent** [comment]
Related with more examples: https://github.com/microsoft/vscode/issues/102221
