### ISSUE TITLE
Editor Settings Typo - "weather"

### ISSUE THREAD

**Issue by belzecue** [microsoft/vscode#111239]
Issue Type: <b>Bug</b>

In editor settings, search for setting "trailing". Observe that setting "Editor > Smart Select: Select Leading and Trailing Whitespace" is described as "Weather leading and trailing whitespace should always be selected."  The correct spelling is "whether," not "weather."

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Silver J5005 CPU @ 1.50GHz (4 x 2695)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.23GB (7.38GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 1c95e316-ec99-481a-9b7e-af63f3a1e11d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-tools|gee|1.1.2
csharp|ms-|1.23.6

</details>

**Comment by belzecue** [comment]
![Screenshot at 2020-11-25 00-13-25](https://user-images.githubusercontent.com/1931303/100121083-afe55c80-2eb3-11eb-8a4e-0c808aa18487.png)

**Comment by jrieken** [comment]
<img width="490" alt="Screenshot 2020-11-24 at 17 52 13" src="https://user-images.githubusercontent.com/1794099/100126055-c96bb180-2e7d-11eb-92f0-eca229bc6734.png">

Already fixed
