### ISSUE TITLE
Support cancellation in bulk edit service

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111281]
The bulk edit service should support cancellation. Cancellation should be on the level of a file operation, e.g when moving 10 files and cancel happens after the 3rd then the operation simply stops

**Comment by isidorn** [comment]
Benefit of this: explorer will adopt this so all multi file operations will be cancelable via global silent notifications -> user clicks on status bar entry -> notification appears with a Cancel button.

Also cancelation when clicked should just stop, not undo what is done already. Native finders behave like that

**Comment by jrieken** [comment]
I have pushed a first change that allows to pass a cancellation token to the bulk edit service (via its options). The token is check in-between operations can will then simply stop. What's not yet done is to pass the token down the working copy service. I believe that's needed because the working copy service manages cancellation for onWill-event handler. fyi @bpasero for other ideas

**Comment by bpasero** [comment]
I think Isi wanted to adopt the token in working copy land. Note that this is mostly all bogus unless file system providers support cancellation, which currently is not the case.

**Comment by jrieken** [comment]
> Note that this is mostly all bogus unless file system providers support cancellation, which currently is not the case.

As said above - it is needed to propagate cancellation of onWill-handlers

**Comment by isidorn** [comment]
Thanks for pushing this. I will adopt this on the Explorer side and let you know how it goes.

**Comment by jrieken** [comment]
I have pushed another change that adds cancellation token to the working copy service and hooks those up with the file participants. Tho, no further cancellation of actual operations yet

**Comment by isidorn** [comment]
I have hooked in Cancellation in the Explorer and it seems to work fine. I tried the scenario of copying 2 large files and I can nicely cancell the other one.
You can play around with it from Master.

If you want the progress to appear with a shorter dealy you can fine tune it here https://github.com/microsoft/vscode/blob/e287b8c9d3859d5a8bd434a4a3970087b16e13f6/src/vs/workbench/contrib/files/browser/explorerService.ts#L100

**Comment by isidorn** [comment]
Thinking about the UI I will only allow Cancellation if `ResourceFileEdits.length > 1`.
Since for only one resource there is no point in user pressing Cancel - it will have no effect.

**Comment by isidorn** [comment]
Here's the test plan item for this issue https://github.com/microsoft/vscode/issues/111250
@jrieken feel free to edit it as we might get more features from this work that I am missing...
