### ISSUE TITLE
npm.fetchOnlinePackageInfo with private registry

### ISSUE THREAD

**Issue by ahippler** [microsoft/vscode#111254]
npm.fetchOnlinePackageInfo does only work for `registry.npm.org` or `registry.bower.org`.

packages from a private registry are not supported.
the urls for the registry should be configureable or use the url of `.npm.rc`

**Comment by aeschli** [comment]
If the `npm` command is on the path, we use it to find packages. The npm command willl use the `.npmrc` files

Only the `npm` command  is not available, we use `registry.npm.org` or `registry.bower.org`.

Closing as dup of #54248.
