### ISSUE TITLE
Python mode ignores my configured intellisense delay

### ISSUE THREAD

**Issue by dgh1000** [microsoft/vscode#111278]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Install ms-python.python extension. Configure Editor: Suggestions Delay to 1000 milliseconds. Start typing a Python file. Quick suggestions pop up immediately.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.05GB free)|
|Process Argv|--crash-reporter-id 43abe92c-7633-4a98-bac5-a440c7358e00|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|0.1100.1
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.16.1
vscode-npm-script|eg2|0.3.13
elm-ls-vscode|elm|1.5.3
prettier-vscode|esb|5.8.0
html-snippets|gey|0.2.3
haskell|has|1.2.0
vscode-picture|Jak|1.0.0
angular-essentials|joh|9.0.1
Angular2|joh|9.1.2
language-haskell|jus|3.3.0
chat|kar|0.35.0
csound-vscode-plugin|kun|0.2.3
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
eclipse-new-java-project|mel|1.0.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
azure-account|ms-|0.9.4
cpptools|ms-|1.1.2
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-purty|mva|0.6.0
printcode|nob|3.0.0
angular-console|nrw|14.0.1
ide-purescript|nwo|0.23.3
language-purescript|nwo|0.2.4
material-icon-theme|PKi|4.4.0
ghci-helper|rco|0.0.9
java|red|0.71.0
LiveServer|rit|5.6.1
html5-boilerplate|sid|1.1.1
rewrap|stk|1.13.0
ejs-snippets|Tao|0.1.0
java-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.11.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.25.0
HTML5-extension-pack|wal|0.0.3
html-snippets|wge|0.1.5

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
