### ISSUE TITLE
Explore view does not refresh on outside changes to the source tree

### ISSUE THREAD

**Issue by ardan-bkennedy** [Microsoft/vscode#1113]
I have been making changes to the source tree that is open in explore from outside the editor. It has happened twice where changes that occur outside of the editor do not show up in the explore view in the editor. It has happened twice and I wish I could reproduce it. I have to stop and restart the editor.

**Comment by egamma** [comment]
You do not have to restart the editor. The explorer view has a refresh button in its tool bar for such situations.

There is still a bug in that the explorer should refresh automatically, but without reproducable steps are some hints when this happens we cannot fix this issue. Please reopen if you have more steps or context.
