### ISSUE TITLE
Clicking "Accounts" menu does not open the menu instantly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111398]
**Update:** reproduces in web + desktop

Steps to Reproduce:

1. open a Codespace
2. wait until it is loaded
3. try various activity bar items that open menus (gear menu, accounts, main menu, home indicator)

=> 🐛  somehow the accounts menu only opens for me after a delay, as if something was resolved when clicking?

![Kapture 2020-11-27 at 08 42 56](https://user-images.githubusercontent.com/900690/100423627-93504c80-308c-11eb-953a-a57af3345431.gif)

**Comment by bpasero** [comment]
This still reproduces @RMacfarlane @sbatten

**Comment by sbatten** [comment]
does this still repro? maybe its imperceptible to me?

**Comment by gjain-7** [comment]
This issue has existed since 2 years!
But only recently have I encountered this.
