### ISSUE TITLE
Does install from vsix api command support force flag?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#111323]
Trying to install `.vsix` from extension api fails when extension has version lower than installed one

```js
await commands.executeCommand('workbench.extensions.command.installFromVSIX', [vscode.Uri.file(vsixPath)]);
```

But it shows success notification which is confusing:

![Screenshot (387)](https://user-images.githubusercontent.com/9638156/100277762-c1426d80-2f74-11eb-8934-ebb6b7691846.png)

**Comment by sandy081** [comment]
Yes, this command overrides the existing extension - this is newly introduced workbench command which is used to install VSIXs from editor (Extensions view, Drag n Drop etc.,). This is nothing to do with the CLI commands.

**Comment by usernamehw** [comment]
@sandy081 That's the thing, it doesn't override and shows success notification when your installed version is `0.0.2` and you're trying to install `0.0.1`.
