### ISSUE TITLE
search toggle button: focus box is broken up

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111351]
![image](https://user-images.githubusercontent.com/6461412/100334494-28433f00-2fd4-11eb-8d7c-78e7d91cbddb.png)

The problem is caused by the rule

```
.monaco-button {
	outline-offset: 2px !important;
}

```

added by https://github.com/microsoft/vscode/commit/a0b7c2310f4f77b801d185a65f3488953c80508b

**Comment by rzhao271** [comment]
The issue still occurs for me depending on the zoom level.

**Comment by sandy081** [comment]
@rzhao271 Thanks for checking.

Can you please check if you can repro the same in stable?

**Comment by rzhao271** [comment]
@sandy081 it does not repro in stable 1.51.1.

**Comment by sandy081** [comment]
I cannot repro it on insiders either - which version of insiders are you on?

**Comment by rzhao271** [comment]
I'm on the latest, 

Version: 1.52.0-insider (user setup)
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:36:22.965Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sandy081** [comment]
Ok, I see. Latest insiders that has the fix is frozen because of a bug. The insiders version which you are on does not have the fix. So please wait for next insiders to verify.
