### ISSUE TITLE
Text wrap positively does not work

### ISSUE THREAD

**Issue by tscottslater** [microsoft/vscode#111364]
Issue Type: <b>Bug</b>

Hi, I'm really wanting to dive into VScode, but this text wrap thing is too much of an obstacle. 

Brand new Big Sur OS install. Fresh VS install (after MANY uninstalls). Still, cannot toggle the text wrap feature. Way too much horizontal scrolling to do!

Hope you can suggest a fix? Thanks so much!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (19.46GB free)|
|Process Argv|--crash-reporter-id c4e6ddc7-f6f7-4517-be91-fe176164139d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.8.0
ftp-simple|hum|0.7.5
vim|vsc|1.17.1

</details>

**Comment by egamma** [comment]
Please provide detailed steps for how we can reproduce the behaviour that annoys you and describe the behaviour that you expect. I assume you have found the command to toggle the text wrap: `View>Toggle Wordwrap`.
