### ISSUE TITLE
[VS Code Insiders] Nodejs and npm not working!

### ISSUE THREAD

**Issue by whippingdot** [microsoft/vscode#111356]
- VSCode Version: 1.52.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Downloaded VS Code insider
2. Downloaded Node through [this website](https://nodejs.org/en/download/)
3. Created a .js file
4. Tried
```js
var msg = 'Hello World';
console.log(msg);
```
5. Got an error saying
```
node: The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Extra note: In CMD when I type ```node -v``` it works but in the terminal in vs code insiders when I type ```node -v``` it doesn't work. This is the same for ```npm -v```

Does this issue occur when all extensions are disabled?: Yes(note: Code Runner is still there)

**Comment by yume-chan** [comment]
Did you sign out or restart your computer after installing Node.js? Environment variables won't change for already running programs (and programs launched by them).

**Comment by whippingdot** [comment]
No I haven't, I will restart my comp now.

**Comment by whippingdot** [comment]
> Did you sign out or restart your computer after installing Node.js? Environment variables won't change for already running programs (and programs launched by them).

Thanks a ___ton___ @yume-chan. I restarted my computer jn and it worked. Really, thanks a LOT.

BTW jn means just now
