### ISSUE TITLE
Flashing, Glitching, crazy polygons on Linux

### ISSUE THREAD

**Issue by d3-worgan** [microsoft/vscode#111387]
- VSCode Version: 1.51.1
- OS Version: Lubuntu LXQt 0.15.0 - But this has also happened before on standard Ubuntu 18

VS Code progressivly gets worse through the session until its unusable. It starts with some small glitches like a line next to the scroll bar or characters from the text in the terminal missing (covered?) Eventually VS Code has loads of crazy colourful shapes so I cant see what I'm doing. 

It is a fresh install of Lubuntu, with only the python add on and Linter added top VS Code. It has happened before as well on a different machine and standard installation of Ubuntu 18. I ignored it before but thought I would report it here, couldnt see any other issues describing the same problem however - or I wasnt sure what to type??

![vs_glitch](https://user-images.githubusercontent.com/56825720/100399766-ee158400-304b-11eb-96ed-57a4a4161662.jpg)

Steps to Reproduce:

1. Launch code 
2. Make a python file and write some code for a few minutes
3. Click the play button to run some python code in the terminal
4. The terminal outputs but is all funny
5. Weird polygons and shapes start flashing everywhere, sometimes linked to the scroll bar on the right.

Does this issue occur when all extensions are disabled?: I dont think so, but the problem appears to get worse over time?? Or after something happens...

**Comment by meganrogge** [comment]
I think this is caused by an extension. Pls try disabling them and let me know if it persists.

**Comment by yume-chan** [comment]
Do you mean the "crazy polygons" only appear after opening the terminal?

Can you try setting `"terminal.integrated.rendererType": "dom"` or launch `code` with `--disable-gpu` flag?

**Comment by d3-worgan** [comment]
@meganrogge I disabled the add on and yes it has stopped. It looks like the problems start after clicking the 'play' button to run the python code

**Comment by d3-worgan** [comment]
@yume-chan  @meganrogge Actually the play button or terminal doesnt appear to have any effect. It only needs python add on enabled for the problem to occur.
