### ISSUE TITLE
Ordering guarantees for vscode.workspace.applyEdit and vscode.workspace.onDidChangeTextDocument

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#111331]
Is there an ordering guarantee that if I have a `vscode.workspace.onDidChangeTextDocument` listener that it will get called with the change triggered by a call to `vscode.workspace.applyEdit` before the `Thenable` returned by `vscode.workspace.applyEdit` resolves?

This seems to be the case from my testing, but it'd be nice to have a guarantee, and some assurance that this is behavior that can be depended upon (and expected not to change).

(Use case is for ignoring those changes caused by `vscode.workspace.applyEdit`, but responding to other changes).

**Comment by daytonellwanger** [comment]
Related question: is there a guarantee that the edits produced by the call to `vscode.workspace.applyEdit` will result in no more than one call to the `vscode.workspace.onDidChangeTextDocument` listener?

**Comment by jrieken** [comment]
"Yes" for the first question, it "depends" for the second but usually it is also "yes"

**Comment by daytonellwanger** [comment]
@jrieken do you happen to know in what situations `vscode.workspace.applyEdit` will result in multiple edits being raised?

**Comment by jrieken** [comment]
> situations vscode.workspace.applyEdit will result in multiple edits being raised?

Whenever text edits for a file are interleaved with resource edits, like creating a resource or so. When applying workspace edits the order in which an edit has been build is [honoured](https://github.com/microsoft/vscode/blob/818174d4e868db11cac25d71e0b1d29d852b4a90/src%2Fvs%2Fworkbench%2Fcontrib%2FbulkEdit%2Fbrowser%2FbulkEditService.ts#L57), esp text edits interleaved by resource edits are applied in that order. Sample:

* edit text in file A
* rename file B to C
* edit text in file A

In that cause you have two doc change event for file A

**Comment by daytonellwanger** [comment]
Thank you!
