### ISSUE TITLE
Wrong `StartupWMClass` property in desktop file on Manjaro Linux leads to generic Electron icon in dock

### ISSUE THREAD

**Issue by thomaseizinger** [microsoft/vscode#111327]
Issue Type: <b>Bug</b>

1. Install vscode through official Manjaro repositories
2. Launch vscode
3. Observe generic electron icon in dock

VS Code version: Code - OSS 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-12T10:54:25.653Z)
OS version: Linux x64 5.7.19-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2474)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.11GB (21.70GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.4
gitlens|eam|10.2.1
intellij-idea-keybindings|k--|0.2.41
rust-analyzer|mat|0.2.392
code-spell-checker|str|1.10.0
even-better-toml|tam|0.9.1
pdf|tom|1.1.0
latex-support|tor|3.2.0

</details>

Steps to fix:

1. Open `/usr/share/applications/code-oss.desktop` in editor
2. Change value of `StartupWMClass` from `Code` to `code-oss`
3. Restart vscode
4. Observe correct icon being used

I believe this issue occurs because the version distributed in the Manjaro repositories is some sort of OSS flavor and not the regular version of vscode and therefore the `@@NAME_SHORT@@` variable in [this](https://github.com/microsoft/vscode/blob/master/resources/linux/code.desktop) file expands to the wrong value?

**Comment by joaomoreno** [comment]
> Install vscode through official Manjaro repositories

Sorry but we can't provide any support of stuff we don't control. I suggest you file an issue to the Manjaro repo.
