### ISSUE TITLE
Using the feedback tweet UI to tweet "sad" feedback results in an incorrect query parameter 

### ISSUE THREAD

**Issue by Pikachu920** [microsoft/vscode#111324]
The query parameter for "ref_src" when submitting "sad" feedback is "nullref_src" instead of just "ref_src" because null is erroneously concatenated.

- VSCode Version: 1.51.1 (user setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open the tweet feedback UI using the button in the bottom right of code.
2. Click the sad face
3. Enter some tweet content
4. Hit tweet
5. The resulting URL will be something like https://twitter.com/intent/tweet?nullref_src=twsrc%5Etfw&related=twitterapi,twitter&text=123&tw_p=tweetbutton&via=code

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Up for grab.

**Comment by rzhao271** [comment]
It's still nullref for me:

https://twitter.com/intent/tweet?nullref_src=twsrc^tfw&related=twitterapi,twitter&text=Testing&tw_p=tweetbutton&via=code

**Comment by bpasero** [comment]
@rzhao271 not for me when I update insiders to latest, what's your insiders version?

**Comment by rzhao271** [comment]
It works for me now too, after updating again.
/verified
