### ISSUE TITLE
"Archive" dropdown menu appears on screen 2

### ISSUE THREAD

**Issue by RafaelLinux** [microsoft/vscode#111308]
Issue Type: <b>Bug</b>

1 - Opens VSC
2 - Maximize VSC (in not maximized) on screen 1
3 - Click on "Archive" (Files)
The  dropdown menu appears on left monitor instead than in right monitor (where VSC is maximized).

Configuration:
KDE Plasma
Two monitors. Monitor 1 at left (secondary monitor) Monitor 2 at right side (primary monitor). VSC code in opened and maximized on Monitor 2. 

I tried with other GTK based applications (Chorme, Inkscape, Opera ...) and no problems like this at all. Dropdown menus appears is same monitor.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.3.18-lp152.50-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 2582)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (0.50GB free)|
|Process Argv|--no-sandbox --unity-launch /home/rafael/.cache/kioexec/krun/8092_0/cont_subscripcion_fomento.inc.php --crash-reporter-id 2ace93db-d4f2-4e01-b308-fccb644a463c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
prettier-vscode|esb|5.8.0
php-intellisense|fel|2.3.14
vscode-language-pack-es|MS-|1.51.2
vscode-icons|vsc|11.0.0

(2 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Can you download and run https://www.electronjs.org/fiddle, check if the issue repros. Thanks!

**Comment by RafaelLinux** [comment]
I got to install "fiddle" (libxcb library is installed but not the version that it needs) and as you figured out, the same issue: "File" drop-down menu appears on wrong screen.

**Comment by deepak1556** [comment]
Can you open an issue in https://github.com/electron/electron/issues with steps to repro by using fiddle as an example. Also attach some screenshots. Thanks!

**Comment by chnavarro** [comment]
The issue is not solved on 
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.19.4-200.fc36.x86_64

**Comment by RafaelLinux** [comment]
And will never be, as it is going.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/110162

**Comment by RafaelLinux** [comment]
Which version will be implement the fix? Latest openSUSE Tumbleweed still have issue

![imagen](https://github.com/microsoft/vscode/assets/13048959/b86026c7-839e-4a9c-acc7-90a2b466ba16)
