### ISSUE TITLE
black-only tooltip windows (when running vscode from an ssh session)

### ISSUE THREAD

**Issue by rhaschke** [microsoft/vscode#111372]
All tooltip windows just show a black rectangle, like this when vscode is run from within an ssh session to localhost:
![image](https://user-images.githubusercontent.com/5376030/100368687-2db87d80-3004-11eb-8d8b-e8ac961a5a3a.png)

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Xubuntu 18.04, Linux x64 5.4.0-54-generic

I'm using color theme Dark+, but the issue occurs in all color themes.

Does this issue occur when all extensions are disabled?: Yes (see screenshot above)
I remember having seen this issue in other applications as well: somehow the desktop theme cannot be retrieved in an ssh session.

**Comment by rhaschke** [comment]
I just noticed that this issue only occurs when running from an ssh session. I augmented the main comment appropriately.

**Comment by rhaschke** [comment]
Xubuntu 20.04 is even worse: there, vscode just shows a uniformly greyish window when starting from an ssh session - no content at all.

**Comment by deepak1556** [comment]
Does the issue occur when you start with `--no-xshm` ?

**Comment by rhaschke** [comment]
Thanks, with that option the issue is gone on Xubuntu 20.04, but gives a warning:
```
$ code --no-xshm
Warning: 'xshm' is not in the list of known options, but still passed to Electron/Chromium.
```
Need to test on Xubuntu 18.04 as well. Would it be possible to auto-detect when this option is needed?

**Comment by rhaschke** [comment]
Xubuntu 18.04 works as well. Thanks a lot. Would be great to have that option auto-enabled though. I'm sure I will have forgotten about this the next time I need it.

**Comment by deepak1556** [comment]
You can ignore the command warning, the option was needed because of how chromium changed its detection for MIT-SHM, the issue is tracked in https://github.com/microsoft/vscode/issues/101069#issuecomment-662150152. I haven't looked much into this issue on how to auto-enable this switch, pull request is welcome. Merging to https://github.com/microsoft/vscode/issues/101069.

**Comment by rhaschke** [comment]
I have configured a workaround for me that configures an alias when in a ssh environment:
`[[ $SSH_AUTH_SOCK == /tmp/ssh-* ]] && alias code='code --no-xshm'`

This assumes that ssh-agent forwarding is enabled.
