### ISSUE TITLE
VS Code Is Pasting Garbage on Save

### ISSUE THREAD

**Issue by ShawnDietrich** [microsoft/vscode#111333]
- VSCode Version: 1.51.1
- OS Version: Windows 10.0.19041

Every time I save my HTML document when I open it again I get the following.  I have no extensions installed and I've tried completely uninstalling and reinstalling.  I've installed on two different machines and I get the same problem.  It doesn't matter if I delete the garbage code and save when I close and open the document again the garbage appears. 

Before save
![image](https://user-images.githubusercontent.com/75051081/100295668-2b98e500-2f58-11eb-94c3-4dc435ae6747.png)

after I save
![image](https://user-images.githubusercontent.com/75051081/100295708-3eabb500-2f58-11eb-948f-ec5bedf6c3d7.png)

**Comment by aeschli** [comment]
You said you tried on two different machines. Is the file stored on a network drive?
Or do you see it with two different files of the same content? If yes, can you attach the file?

**Comment by ShawnDietrich** [comment]
It is stored on a networked drive.  Would having the file on a network
drive cause the issue?

**Comment by ShawnDietrich** [comment]
When I work on the file locally it doesn't happen even with extensions installed.  I guess that's the problem.
