### ISSUE TITLE
Feature Request: Multiple Folder Selection to open a lot of instances, instead of creating a workspace

### ISSUE THREAD

**Issue by DouglasMarq** [microsoft/vscode#111318]
Hello,

Currently, File -> Open and select multiple folders creates a workspace. It would be nice to have a settings to swap between creating workspaces and instances (for each folder) when selecting multiple folders.

Edit: I'm trying to add a feature request label, i'm kinda new into making issues.

**Comment by isidorn** [comment]
This is the file > open dialog, thus forwarding to @bpasero
There is probably already a request for this
