### ISSUE TITLE
Problem with HTML syntax highlighter

### ISSUE THREAD

**Issue by vismodo** [microsoft/vscode#111394]
Issue Type: <b>Bug</b>

Create a new  HTML file in Visual Studio Code and type this:
```html
<input type="button" onclick="window.location.href='https://vismaya.us/"
```
You will notice that the `=` inside the `onclick` parameter is not the same colour as the rest of the parameter. Also, the `:` after `https` is red in color.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by ashtongao** [comment]
![image](https://user-images.githubusercontent.com/45849828/100496781-cc261980-3191-11eb-9fb2-29af02d13a27.png)

**Comment by vismodo** [comment]
![image](https://user-images.githubusercontent.com/62926183/100497309-988ec380-3180-11eb-8308-96185e6f64da.png)

The same happens even with the correct syntax. The `https` is in a different color too. Only that the `=` inside the `onclick` parameter is white in color.

**Comment by alexr00** [comment]
Moved to owning repo: https://github.com/microsoft/TypeScript-TmLanguage/issues/845
