### ISSUE TITLE
Search: using IWorkspaceFolder is fishy

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111348]
I noticed how `QueryBuilder.file` is accepting `folders: IWorkspaceFolderData[]`, which seems to imply that only workspace root folders can be searched. In reality though, any folder can be passed in, even children of workspace folders.

I am not sure this is causing any issues but thought I would report this anyway. You can see for example how here we seem to convert any `URI` to a workspace folder, even if it is none:

https://github.com/microsoft/vscode/blob/3c77120d88b57b302e86c84cd65e33be7e8433e9/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L142-L142

**Comment by roblourens** [comment]
I think the reason for this is because you can reference the workspace folder's configured name from a search (only from the search view) and this gets resolved in QueryBuilder. But yeah it should be possible to just pass a URI into this without creating a fake workspace folder.
