### ISSUE TITLE
e. is replaced to eval. when typing the dot

### ISSUE THREAD

**Issue by nitti87** [microsoft/vscode#111374]
Issue Type: <b>Bug</b>

When a function returns an event: `element.addEventListener('click', e => {  })` and you want to write `e.something`. When you type the dot ( `.` ) after `e`, the `e` is replaced to `eval`

VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:36:22.965Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.04GB free)|
|Process Argv|--crash-reporter-id cd7405a1-4997-42c2-abbd-a29c4b00bc6b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Actually, this is just the behavior of commit characters (see the `editor.acceptSuggestionOnCommitCharacter` setting)

**Comment by nitti87** [comment]
I disabled `editor.acceptSuggestionOnCommitCharacter` and the problem is gone. Thanks
