### ISSUE TITLE
Rename on click

### ISSUE THREAD

**Issue by Armaldio** [microsoft/vscode#111349]
- VSCode Version: 
```
Version: 1.52.0-insider (user setup)
Commit: 6026ab576dc6a4fbb8e255241a364816f42464c5
Date: 2020-11-23T05:56:29.761Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
- OS Version: W10 20H2

Steps to Reproduce:

1. Open a javascript file
2. Click on a variable that is referenced multiple times
3. Type something

> What is happening

All the references appear red when clicked and update as you type

> What is expected

Not all references are "selected" and only the clicked one is used

It's like I've hit F2 to start refactoring
Is it a new setting ? I don't remember this to be a thing before.

Does this issue occur when all extensions are disabled?: **Yes**

Here is a video of what happen with extensions disabled

![KJ0KVDqBUr](https://user-images.githubusercontent.com/3089715/100327736-f0d09480-2fcb-11eb-9ae8-f63405a3e427.gif)

**Comment by IllusionMH** [comment]
You can also try to update VS Code to latest Insiders build - this prototype implementation should be removed https://github.com/microsoft/vscode/commit/bd40e2555b3d3119d78cb1c383d1b14d7f1ab30a
