### ISSUE TITLE
Rendering issues with terminal while running in a linux VM

### ISSUE THREAD

**Issue by philAZtest** [microsoft/vscode#111322]
Issue Type: <b>Bug</b>

Every time i begin typing in the terminal it becomes impossible to see/corrupted within a few keystrokes, starting with a kinda big blue triangle and then just general jumbled pixels that are unintelligible. This has a now, as i write this report, expanded to include the entire application flipping upside down and zooming in, both in the main window and this bug report window. I cannot do anything in the app without it becoming inoperable.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.8.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (4 x 2591)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|3.81GB (0.44GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id c30bb873-929f-4a50-9461-fe7fda4ed32e|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azureappservice|ms-|0.20.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
azure-account|ms-|0.9.4

</details>

**Comment by meganrogge** [comment]
see https://code.visualstudio.com/docs/editor/integrated-terminal#_why-is-my-terminal-showing-a-multicolored-triangle-or-a-completely-black-rectangle
