### ISSUE TITLE
skipFiles has no effect on tslib.js

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#111301]
Issue Type: <b>Bug</b>

1. Add `tslib.js` into the `skipFiles` of a debug configuration and start debugging.
2. At some point you'll step right into `tslib.js`, even though it should be skipped.

This could be https://github.com/microsoft/vscode/issues/104421 in case it still hasn't been fixed. But the nightly has other major issues right now and is unusable.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (40.04GB free)|
|Process Argv|--file-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3/core.code-workspace --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (38.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (38.30GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (38.30GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.2.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.0.0
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.13
eslint-disable-snippets|drK|1.2.0
gitlens|eam|11.0.5
EditorConfig|Edi|0.16.1
prettier-vscode|esb|5.8.0
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.3.0
vscode-esformatter|how|1.6.0
template-string-converter|meg|0.3.3
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.8.1
vscode-js-profile-flame|ms-|0.0.13
vscode-paste-image|mus|1.0.4
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
lit-plugin|run|1.2.1

(2 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
I sent you an email with the log.

**Comment by connor4312** [comment]
Thanks, fixed in today's [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension)
