### ISSUE TITLE
Test file icons themes (user experience)

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#11130]
- [x] OSX  **@bpasero**
- [x] Linux **@isidorn**
- [x] Windows **@dbaeumer**

Test the new file icon theme from a user perspective
- Install the Seti icon theme from https://github.com/Microsoft/vscode-theme-seti

User experience:
- Test the icon theme picker at `File > Preferences > File Icon Theme`
  - test that you see a preview while browsing through the themes, but only in the current window
- Test the 'Icon Theme' command (F1)
- test that when you select a theme it is applied to all windows
- test that the selected icon theme is persisted over restarts  
- test the Standard and Seti theme in light, dark and high contrast theme
   - verify that the Standard theme shows icons for open and closed folder as well as a single icon for files
  - verify that the Seti theme does not show folder icons, but many different icons for various file types.
- verify that the rename dialog in the file explorer is correctly positioned

**Comment by Gama11** [comment]
>https://github.com/Microsoft/vscode-theme-seti

That link seems dead? (getting a 404 page not found)

**Comment by aeschli** [comment]
@Gama11 It's currently only internal...
