### ISSUE TITLE
bash.exe起動時にエラーが発生する

### ISSUE THREAD

**Issue by konno01** [microsoft/vscode#111347]
新しいターミナルを押下すると以下エラーが発生します。

ターミナル プロセス "C:\Program Files\Git\bin\bash.exe '-NoExit', 'chcp', '65001'" が終了コード 2 で終了しました。

何か解決方法を探しているのですが、特に解決方法が見つからず・・・
何かご存じの方はいらっしゃいますでしょうか？
お手数おかけしますがよろしくお願いいたします。

**Comment by yume-chan** [comment]
Translation:

> ## Error when starting bash.exe
> 
> Click "New Terminal" results the following error:
>
> Terminal process "C:\Program Files\Git\bin\bash.exe '-NoExit', 'chcp', '65001'" exited with code 2.
>
> I tried to search for solution, but got nothing...
>
> Does anyone know how to solve this?
>
> I'm sorry to trouble you.

**Comment by konno01** [comment]
> yume-chan
Thank you translation!

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
