### ISSUE TITLE
Ctrl-C and Ctrl-V doesn't work in the Find widget

### ISSUE THREAD

**Issue by OneMoreSecond** [microsoft/vscode#111390]
Issue Type: <b>Bug</b>

This is a issue appeared recently

1. Copy something
2. Press Ctrl-F to open the Find widget
3. "Right click -> Cut/Copy/Paste" works
4. "Ctrl-X/Ctrl-C/Ctrl-V" doesn't work (but "Ctrl-Z/Ctrl-Y/Ctrl-A" can work)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.14393
Remote OS version: Linux x64 5.4.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.89GB free)|
|Process Argv|D:\TextToSpeechMain\private\dev\speech\tts\shenzhou\tools\Offline\src\Framework\Microsoft.Tts.Offline --crash-reporter-id e562f803-0647-49e2-8b05-490928911d2f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TTS-GPU-1|
|OS|Linux x64 5.4.0-45-generic|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 800)|
|Memory (System)|62.57GB (1.33GB free)|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
unique-lines|bib|1.0.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.2
xml|Dot|2.5.1
gc-excelviewer|Gra|3.0.40
kite|kit|0.135.0
vscode-idl|kur|0.1.2
bash-ide-vscode|mad|1.11.0
rainbow-csv|mec|1.7.1
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.6
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.372831992
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
cpptools|ms-|1.1.2
powershell|ms-|2020.6.0
team|ms-|1.161.1
vscode-yaml|red|0.13.0
trailing-spaces|sha|0.3.1
vscode-hexdump|sle|1.8.1

</details>

**Comment by yume-chan** [comment]
Looks like #109874

Can you try [the advice there](https://github.com/microsoft/vscode/issues/109874#issuecomment-721990594)?

**Comment by OneMoreSecond** [comment]
@yume-chan I'm sorry that I have closed the VSCode window with this issue. Just like what's mentioned in #109874, it seems a random issue. I will try the advice the next time I meet it.
