### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by WRBKOR23** [microsoft/vscode#111302]
Issue Type: <b>Feature Request</b>

my version of vscode is 1.45. everytime i open vscode it always make me restart to update new version (1.51) but when i reopen vscode, it go back to version 1.45 and require update to version 1.51. really annoying. i dont know what wrong with my computer or my vcode
sorry for my bad Eng =]]

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
Does it keep happening if you fully uninstall VS Code and reinstall it?

**Comment by WRBKOR23** [comment]
> Does it keep happening if you fully uninstall VS Code and reinstall it?

it does, i cleared all file related to vscode and reinstalled but it doesnt help any at all ~~

**Comment by joaomoreno** [comment]
Once you uninstall VS Code, can you do a full disk search for `Code.exe`? I believe you have two installations of VS Code on your machine.

**Comment by WRBKOR23** [comment]
> Once you uninstall VS Code, can you do a full disk search for `Code.exe`? I believe you have two installations of VS Code on your machine.

You're right. but i regonized it after i reset my pc :V 
Thanks you!
