### ISSUE TITLE
How to find the current word under cursor in files?

### ISSUE THREAD

**Issue by leira** [Microsoft/vscode#11138]
I know ⇧⌘F can start find in files, but is there a short cut can take the current word under cursor and start search, rather than select, copy, find in files, paste and enter?

**Comment by sandy081** [comment]
@leira There is not a single action to do the complete workflow, but, you can select the word and type ⇧⌘F. This will open Search view and pastes the word in Search text box. Now Enter will trigger your search.

**Comment by zhiyuxia** [comment]
E
