### ISSUE TITLE
Junk UTF-8 hidden by VS Code, but still written to file

### ISSUE THREAD

**Issue by AsgeirOutland** [microsoft/vscode#111380]
- VSCode Version: 1.51.1-1605051630
- OS Version: Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

Steps to Reproduce:

1. Make sure you're in UTF-8 mode.
2. Copy and paste a string with hidden/junk UTF-8 characters into VS Code, (show in pictures, Google Merchant Center sales price effective date definition from support google com).
3. Save file and view it with hexdump or other software that displays "junk" UTF-8 to verify content.

Expected behavior, VS Code should clearly display hidden/junk UTF-8 both inside and outside of strings.

This is mostly a issue that will affect people learning to code, they might never find out what's wrong and give up.

Attached images: lines shown in VS code, and then in VIM.

Does this issue occur when all extensions are disabled?: Yes
![file_displaied_utf8](https://user-images.githubusercontent.com/52995876/100380151-8c86f280-3016-11eb-9757-0a338d46a704.png)
![file_displaied_utf8_vim](https://user-images.githubusercontent.com/52995876/100380157-901a7980-3016-11eb-8c81-c8642e16c85f.png)

**Comment by alexdima** [comment]
There are a number of extensions that will highlight such characters e.g. https://marketplace.visualstudio.com/items?itemName=nachocab.highlight-dodgy-characters
