### ISSUE TITLE
comparers tests fail on big sur

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111368]
* macOS Big Sur or Safari Technology Preview
* yarn run test-browser
* there are failures in `vs/base/test/browser/comparers.test`

**Comment by isidorn** [comment]
Thanks for diabling the test. I think we are fine without that line for now.

@leilapearson I believe you introduced these tests, might you have time to look into this? In case you have macOS Big Sur? In case you do not or you do not have time let me know and I can investigate furhter. 
Just before running tests, make sure to uncomment the two line @jrieken commented out
