### ISSUE TITLE
Unable to run a detached (forked) process in the background using `fork` from an extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#111332]
As an extension author I would like to:
* Launch a node process from extension
* The process must be alive even after closing vs code
* User should need not have node on their machine.

Basically using `fork` with `detached` option.

I have tried using
```javascript
const {fork} = require('child_process');

fork('<path ot js>', { detached: true, env: {...process.env, ELECTRON_RUN_AS_NODE: '1'})
```

However, when i close or restart VS Code, the forked process also dies.
I have tried initializing `execArgv` to `[]` to no avail.
& also tried clearing some of the VSC env variables as follows:
```javascript
env: {
	...process.env,
	VSCODE_IPC_HOOK: undefined,
	VSCODE_IPC_HOOK_EXTHOST: undefined,
	VSCODE_NLS_CONFIG: undefined,
	VSCODE_PID: undefined,
	VSCODE_HANDLES_UNCAUGHT_ERRORS: undefined,
	VSCODE_LOG_STACK: undefined
}
```

I have also tried
```javascript
const proc = spawn(process.execPath, ['<path to js>'], {detached: true, env : <same as previous>}, stdio:'ignore');
proc.unref();
```

The issue seems to be the fact that `detached` is not being respected here.

**Comment by DonJayamanne** [comment]
Works when not in debug mode, the process dies only when debugging extensions.
Closing for now.

**Comment by weinand** [comment]
@DonJayamanne when forking a process, the new process automatically inherits command line arguments from the parent (accessible via `process.execArgv`). This includes the debug arguments. See https://github.com/microsoft/vscode/issues/27665#issuecomment-305444891

You can remove or modify debug arguments in the `process.execArgv` property before calling "fork"..
