### ISSUE TITLE
lag and consuming a lot of CPU and RAM

### ISSUE THREAD

**Issue by RaulOn18** [microsoft/vscode#111397]
Issue Type: <b>Performance Issue</b>

why my vscode is so slow and heavy on my laptop?... My friend uses vscode too but it's not slow and heavy even though my friend's laptop doesn't have too high a spec compared to me

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.42GB (0.25GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    88	  8304	code main
    0	    59	  3664	   window (Issue Reporter)
    0	    12	  4360	   crashpad-handler
    0	   115	  7236	   gpu-process
   12	    70	  8468	   shared-process
    0	   191	  9004	   window (script.js - Learn Programming - Visual Studio Code)
    0	    13	  3060	     watcherService 
    0	    10	  4400	       console-window-host (Windows internal process)
    0	    29	  6180	     searchService
    0	    89	  8952	     extensionHost
    0	    67	  1548	       electron_node tsserver.js 
    0	    51	  5052	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=8952
    0	   128	  6888	       electron_node tsserver.js 
    0	    40	  8856	         electron_node typingsInstaller.js typesMap.js 
    0	    25	  9168	       "C:\Program Files\Microsoft VS Code\Code.exe" "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8952
    0	    25	  9160	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (script.js - Learn Programming - Visual Studio Code)
|    Folder (Learn Programming): 8613 files
|      File types: py(2949) pyc(2310) html(285) download(218) png(179)
|                  css(163) pyd(155) mp4(120) jpg(83) DS_Store(82)
|      Conf files: settings.json(4);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.0
python-extension-pack|don|1.6.0
beautify|Hoo|1.5.0
MagicPython|mag|1.1.0
theme-monokai-pro-vscode|mon|1.1.18
python|ms-|2020.11.371526539
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8

</details>

**Comment by egamma** [comment]
Please follow this guide to provide us with more information about the performance problem https://github.com/microsoft/vscode/wiki/Performance-Issues
