### ISSUE TITLE
Cannot replaced 

### ISSUE THREAD

**Issue by tomoyukikino** [microsoft/vscode#111310]
- VSCode Version:1.51.1
- OS Version:macOS Catalina 10.15.7

Steps to Reproduce:

1.select any text
2.command + shift + f
3.insert replaced text
4.command + option + enter
5.click [YES]
6.all text is changed. but, bit off.

Does this issue occur when all extensions are disabled?: No

I record screenshot. please check below zip.
[crap.mp4.zip](https://github.com/microsoft/vscode/files/5594933/crap.mp4.zip)

**Comment by roblourens** [comment]
Is it possible that your files have CR line endings? (not CRLF or LF)

Can you share that file with me?

**Comment by tomoyukikino** [comment]
> Is it possible that your files have CR line endings? (not CRLF or LF)
> 
No

> Can you share that file with me?
Thank you, but I cant. This file is private repositories.

Today, I tried it again. but I wasn't able to reproduce the problem.
