### ISSUE TITLE
Feature Request: Expose language server as data variable for extension development

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#111362]
I would like to access default language server as an variable in my extension development. This is very useful to get basic and default hover tooltips and do specific actions on them.

**Comment by alexanderniebuhr** [comment]
This is needed for extension which need direct access to language server features, such as Hover Tooltips, code analyze and code completion suggestions (I have attached some screenshots).

I request this feature to allow to get access to language server of current file, for example if the developer uses a custom shortcut, I wish to get raw data of current available interpreted data at cursor position e.g code completion and jsdoc tooltip data, so I can use the data and show it somewhere else, like in an extra window/panel (not as "pop-up") or on external touchbar.

This will futher allow more customization for themes and developer workflow, as themes could allow to place this features e.g. in an extra tab at the sidebar.
My thoughts about this, the data has to exist in some kind of variable or js object, because VS Code is rendering it and working with it itself. It just needs an option to get this data with the VS Code extensibility API, e.g. implement some kind of getter. I do not want to add data, so writing own HoverProvider does not help.


![example3](https://user-images.githubusercontent.com/45965090/100355660-723b1d80-2ff2-11eb-9e25-9cd3a76dd69f.png)
![example2](https://user-images.githubusercontent.com/45965090/100355667-736c4a80-2ff2-11eb-9c90-b5b7371b0341.png)
![example1](https://user-images.githubusercontent.com/45965090/100355668-736c4a80-2ff2-11eb-9bc2-86cfe91bdede.png)

**Comment by jrieken** [comment]
check this out: https://code.visualstudio.com/api/references/commands
