### ISSUE TITLE
images with relative paths in extension's README.md aren't shown in the extension manager

### ISSUE THREAD

**Issue by nadako** [Microsoft/vscode#11136]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:
1. Have an extension which has a README with images with relative path, e.g. https://raw.githubusercontent.com/vshaxe/vshaxe/master/README.md
2. Open extension manager, click on that extension - images aren't shown:

![](http://i.imgur.com/iqmry3h.png)

Note that those images are shown in Marketplace, on Github and when using VSCode's Markdown Preview feature.

**Comment by joaomoreno** [comment]
This issue was moved to Microsoft/vscode-vsce#120

**Comment by joaomoreno** [comment]
Moving the issue back here due to:

> @nadako:
> Actually, I just checked - images are shown in the UI when installing (or already installed) a package from the marketplace, but they aren't shown if your extension is in development mode (i.e. simply cloned into `.vscode/extensions`). This is inconvenient if you want to check how it'll look in the extension manager before packaging.

**Comment by eppz** [comment]
Can be worked around by put images to `localhost` somewhere.

**Comment by joaomoreno** [comment]
This appears to be fixed now.
