### ISSUE TITLE
Go to symbol in editor, open to side should reset scroll position in original editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#111346]
Issue Type: <b>Bug</b>

**Repro**
1. In a JS file
1. Use `go to symbol in editor`
1. Arrow through the list to a symbol that causes the editor to scroll
1. Hold down ctrl and press ednter to open it to the side

**Bug**
A new editor is opened to the side however the original editor also remains scrolled to the symbol's position. The results is two editors that are both scrolled to the same location in the file. The cursor is not moved in the original file

In this case, I expect that the original editor behave as if the user had pressed escape and reset the scroll to where the user triggered go to symbol from

VS Code version: Code - Insiders 1.52.0-insider (6026ab576dc6a4fbb8e255241a364816f42464c5, 2020-11-23T05:40:30.987Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (3.91GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
Needs to be verified with both "Go to Symbol" and "Go to Line". In both cases we support to open to the side and then should restore the original editor view state.
