### ISSUE TITLE
Scrolling is slower since the update to Big Sur

### ISSUE THREAD

**Issue by qq173972819** [microsoft/vscode#111399]
Issue Type: <b>Performance Issue</b>

升级新系统macOS Big Sur 上下滑动卡顿没有以前丝滑了

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|23, 18, 17|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 2edce59b-b1e3-449d-9b80-78ddf711f146|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    8	    74	   420	code main
    1	    25	   500	   gpu-process
    0	     8	   507	   utility
    0	    90	   521	   window (whj_tscp_zwlist.html — tiantang)
    0	    16	   647	     extensionHost
    0	    16	   709	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=647
    0	     8	   710	       electron_node serverMain.js 
    0	     8	   858	       electron_node eslintServer.js 
    0	    16	  3418	       electron_node server.js 
    0	     8	   678	     watcherService
    0	     8	   740	     searchService
   91	    33	   539	   shared-process
    0	     0	  3687	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     8	   646	   utility
    1	    66	  3675	   window (问题报告程序)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (whj_tscp_zwlist.html — tiantang)
|    Folder (tiantang): 657 files
|      File types: png(289) html(149) jpg(45) gif(36) js(31) jpeg(21) mp4(19)
|                  DS_Store(16) css(14) mp3(4)
|      Conf files:;
```

</details>
<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
stylus|Ala|0.0.4
regex|chr|0.2.0
cocos-creator|Chu|0.0.1
cocos-debug|Chu|0.0.1
vscode-jq|dan|1.2.0
vbscript|Dar|1.0.4
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
jquerysnippets|don|0.0.1
vscode-code-runner|dor|1.0.11
auto-rename-tag|for|0.1.5
vue-snippets|hol|0.1.12
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
path-autocomplete|ion|1.15.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.3.3
easy-less|mrc|1.6.3
vscode-language-pack-zh-hans|MS-|1.51.2
sublime-keybindings|ms-|4.0.7
vetur|oct|0.30.3
subtitles-editor|pep|1.1.2
vscode-css-peek|pra|4.0.2
rainbow-fart|sae|1.4.0
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.1.1
html-css-class-completion|Zig|1.19.0
miniprogram|zsh|0.1.3

(1 theme extensions excluded)

</details>

**Comment by TheColdPot** [comment]
升级新系统macOS Big Sur 上下滑动卡顿没有以前丝滑了
After upgrading the system **macOS Big Sur**, sliding is stuck and not as smooth as before

**Comment by egamma** [comment]
@TheColdPot what is meant by 'sliding' is this 'scrolling'?

**Comment by TheColdPot** [comment]
> @TheColdPot what is meant by 'sliding' is this 'scrolling'?

OK I knew, I think it means scroll scroll-bar and not slide and I edited my comment

**Comment by deepak1556** [comment]
@qq173972819 is this still an issue with latest stable `1.56.2` ? The original issue would be a side-effect of https://github.com/microsoft/vscode/issues/105446

**Comment by TheColdPot** [comment]
@qq173972819 
Some question will help Microsoft solve this problem:
1. Is it affect after you disabled all extensions?
2. Will it affected after you open it a long time?

One point you need attention is scrollbar of VSCode is hacked, which is it not the scrollbar from electron official directly

---

请回答以下问题，以便微软处理
1. 问题是否在禁用所有插件后存在（Yes/No）
2. 在开启VSCode一段时间后此问题是否还存在（Yes/No）

有一点您需要注意，VSCode滚动条经过hack，即非原生滚动条

---

> 不是微软的员工，无法保证
> Not from Microsoft, no promise
