### ISSUE TITLE
Python Kernal connection timeout

### ISSUE THREAD

**Issue by Re6urse** [microsoft/vscode#111382]
Connection to python kernel times out with error:

``` Timed out waiting to get a heartbeat from the kernel process.```

Issue Type: <b>Bug</b>

1. Install Jupyter (code-insiders)
2. Install Python 3.7.9 (64-bit) within a local conda environment (./conda-env)
3. Configure settings.json as     "python.pythonPath": "_path to conda env_/conda-env/bin/python"
4. Create a new jupyter notebook
5. Run the notebook. The kernel will not connect.

VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:22:59.162Z)
OS version: Darwin x64 19.6.0

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992

**Comment by egamma** [comment]
Please report the issue against the Python extension.
