### ISSUE TITLE
"Load All Stack Frames" action becomes unreadable when selected

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#111359]
If the "Load All Stack Frames" action at the bottom of the CALL STACK is pressed, it becomes selected which results in unreadable label if the selection color matches the action text color: 

![2020-11-26_12-36-21 (1)](https://user-images.githubusercontent.com/1898161/100346527-487afa00-2fe4-11eb-83c6-d18a6b7fed75.gif)

I think the action should only be shown as selected when pressed, and in this case the label text color must change in a similar way as done for the stack frames.
And when not pressed the action should not be shown as selected anyway.

**Comment by isidorn** [comment]
Good catch. I pushed a fix. However I was not able to actually select it and have it still visible, since when I click on it, it goes away immediatly as expected.
So I am just wondering how you got into a state that it is stable?

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/commit/cfe2e99ad894212e577cb1f9f32da6373f1f7a09

**Comment by weinand** [comment]
@isidorn 
>However I was not able to actually select it and have it still visible, since when I click on it, it goes away immediatly as expected. So I am just wondering how you got into a state that it is stable?

In Mock Debug enable the 4th variant:
```js
  //no totalFrames: 			// VS Code has to probe/guess. Should result in a max. of two requests
  //totalFrames: stk.count 		// stk.count is the correct size, should result in a max. of two requests
  //totalFrames: 1000000 		// not the correct size, should result in a max. of two requests
  totalFrames: endFrame + 20 		// dynamically increases the size with every requested chunk, results in paging
```
and have a breakpoint on a long line with about 60 words in your readme. This will result in a stacktrace with 60 frames.

**Comment by isidorn** [comment]
Thanks for claryfing!

**Comment by weinand** [comment]
Here my proposals for the descriptions of the DAP `stackTrace` request and its `totalFrames` property:

Request `stackTrace`:

The request returns a stacktrace from the current execution state of a given thread.
A client can request all stack frames by omitting the `startFrame` and `levels` arguments. For performance conscious clients stack frames can be retrieved in a piecemeal way with the `startFrame` and `levels` arguments. The response of the `stackTrace` request may contain a `totalFrames` property that hints at the total number of frames in the stack. If a client needs this total number upfront, it can issue a request for a single (first) frame and depending on the value of `totalFrames` decide how to proceed. In any case should a client be prepared to receive less frames than requested, which is an indication that the end of the stack has been reached.

Property `totalFrames`:

The total number of frames available in the stack. If omitted or if `totalFrames` is larger than the available frames, a client is expected to request frames until a request returns less frames than requested (which indicates the end of the stack). Returning monotonically increasing `totalFrames` values for subsequent requests can be used to enforce paging in the client.
