### ISSUE TITLE
[vscode-remote] indication should always be next to recent list entries

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#111350]
From @alexdima:

I oftentimes work with remote from source without a resolver. To do this, I execute:
```
resources\server\bin-dev\server.bat
scripts\code.bat --folder-uri=vscode-remote://localhost:8000/c%3a/Alex/src/working_dir
```
this works fine because `localhost:8000` is not going through a resolver because it doesn't contain a +
In the remoted window, in the recent list I see the following entries:

![image](https://user-images.githubusercontent.com/1926584/100332431-ace08e00-2fd1-11eb-9dc0-f5bbb0b21595.png)

So you can see how `C:\Alex\src\working_dir` appears multiple times, once normally and once through the remote
This is good because it allows me to differentiate between them
But if I open a new `script\code.bat` window, that is not remoted, the very same list looks like this:

![image](https://user-images.githubusercontent.com/1926584/100332487-bd910400-2fd1-11eb-8f6f-5545319b2207.png)

This is super inconvenient because I often work locally (non-remoted) and when I go to the recent list I click on one of those remoted by accident, since now there is no indication.
My question is: could we please have the `[vscode-remote]` indication next to recent list entries all the time, even when the window is not remoted

**Comment by isidorn** [comment]
@sbatten is it possible that you first investigate from the recently opened list side?
What exactly do you store on your side? Do you store the full label? Does what you store include the `[vscode-remote]`suffix.

**Comment by bpasero** [comment]
@isidorn you might want to connect with @aeschli who I think added support for `label` which I think we prefer over computing a label ourselves:

https://github.com/microsoft/vscode/blob/25673682f81f4c69e6fe603ace1c10ac14cc7eb7/src/vs/platform/workspaces/common/workspaces.ts#L60-L60

My understanding is that if this label is present, we can show it.

**Comment by isidorn** [comment]
@sbatten friendly ping regarding this

**Comment by sbatten** [comment]
This is what is returned by the workspaces service for recently opened in each case.
The label service is returning the differing labels given the workspace object.

**When in local workspace**
```json
{
	"workspaces": [
		{
			"remoteAuthority": "localhost:8000",
			"folderUri": {
				"$mid": 1,
				"path": "/c:/Users/username/source/folder",
				"scheme": "vscode-remote",
				"authority": "localhost:8000"
			}
		}
	],
	"files": []
}
```
**When in remote workspace**
```json
{
	"workspaces": [
		{
			"folderUri": {
				"$mid": 1,
				"external": "vscode-remote://localhost:8000/c%3A/Users/username/source/folder",
				"path": "/c:/Users/username/source/folder",
				"scheme": "vscode-remote",
				"authority": "localhost:8000"
			}
		}
	],
	"files": []
}
```

**Comment by isidorn** [comment]
@aeschli thanks for verifying but this is not yet fixed :D
Let's assign to next milestone so I investigate more in this

**Comment by aeschli** [comment]
Sorry, I must have gone to the wrong tab...

**Comment by isidorn** [comment]
The issue was that we were not registering a general `vscode-remote` formatter when you are not remote.
I have changed this and this seems to fix the issue.
Sorry about the slow response.

**Comment by isidorn** [comment]
@alexdima can you please verify this?

**Comment by alexdima** [comment]
Looks very good. Thank you!

![image](https://user-images.githubusercontent.com/5047891/116557356-a8acf980-a8fe-11eb-80ee-602750b63a9b.png)

**Comment by isidorn** [comment]
Great, thanks for verifying.
