### ISSUE TITLE
Test: Integrated terminal scroll bar

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11134]
Test for #10320

- [x] Windows **@ramya-rao-a**
- [x] Linux **@rebornix**
- [x] Mac **@kieferrm**

---

A scroll bar was added to the integrated terminal, try to break it! Some suggestions:

- Scroll one page at a time (ctrl+shift+pg up/down)
- Scroll one line at a time (see https://github.com/Microsoft/vscode/commit/7c734490c7ae54a217f7390a2a888f94ef3653e0, #10302)
- Scroll using mouse wheel/trackpad, fiddle with OS settings to make it scroll at different speeds (you can configure some OS' to scroll by pixel, line or page)
- Use different shells
- Enter and exit applications such as `vim` and make sure it still works

**Comment by dbaeumer** [comment]
@Tyriar Please assign the test plan items to a milestone. Otherwise they don't show up in queries.

**Comment by kieferrm** [comment]
For those who are looking: <kbd>PgUp</kbd> on the Mac is <kbd>Fn+ArrowUp</kbd> and <kbd>PgDown</kbd> on the Mac is <kbd>Fn+ArrowDown</kbd>. So in order to scroll by page in the integrated terminal you need to use <kbd>Ctrl+Shift+Fn+ArrowUp</kbd> and <kbd>Ctrl+Shift+Fn+ArrowDown</kbd> respectively.

**Comment by Tyriar** [comment]
@kieferrm if it doesn't scroll like iterm does then feel free to create an issue.
