### ISSUE TITLE
[css] support comma less color format

### ISSUE THREAD

**Issue by tylr-r** [microsoft/vscode#111337]
- VSCode Version: 1.51.1
- OS Version: MacOS 11.0.1

Steps to Reproduce:

1. Open a CSS file in VS Code.
2. Use an HSL color using the new HSL format i.e. `color: hsl(0 0% 100% / 20%);`

[CSS color level 4](https://www.w3.org/TR/css-color-4/#the-hsl-notation) has since dropped the need for commas, the "a" in HSLA, as well as other formatting changes. 

Does this issue occur when all extensions are disabled?: Yes

<img width="372" alt="No support for Color Level 4" src="https://user-images.githubusercontent.com/9301411/100298081-0b135f80-2f45-11eb-94a9-9a0eb89c96e0.png">

**Comment by lachieh** [comment]
I can confirm this does not work with any of the [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/#resolving-color-values) color-functions.

**Comment by glen-84** [comment]
Related: #43111.

**Comment by glen-84** [comment]
I agree with @mathiasbynens:

> - consider being opinionated w.r.t. how to represent alpha values. IMHO using percentage notation is most readable, as it clarifies the range: e.g. 70% vs 0.7
> - consider being opinionated about using the deg suffix where applicable, e.g. in the first parameter for hsl() and the last non-alpha parameter for lch(). Again, because this clarifies that the range lies between 0-360.

i.e. Use percentages for alpha, and always include the `deg` suffix.

This also matches the syntax displayed in Chrome developer tools (probably not a coincidence 😄).

(see https://github.com/stylelint/stylelint/issues/4718#issuecomment-619336037)

**Comment by secf4ult** [comment]
IMHO this feature is needed to be in compliance with modern browsers.

**Comment by WhiteMac** [comment]
For me personally, I'd like support for the `rgb(0 0 0 / 50%)` CSS Color Module Level 4 format. Changing color values in Chrome DevTools has seemed to favor this format over `rgba(0, 0, 0, .5)` for some time now, so I think Code ought to implement it. Hope this is the correct issue to upvote.

**Comment by aeschli** [comment]
Verify that you can use the comma less formats for `rgb` and `hla`, including alpha
e.g. `rgb(0 0 0 / 50%)`
and that the color decorator is shown
