### ISSUE TITLE
VSCode Jupyter is incompatible with Miniforge (Apple ARM) conda

### ISSUE THREAD

**Issue by leh08** [microsoft/vscode#111336]
Hi Team,

- Issue Type: **Bug**
- VSCode Version: 1.51.1
- OS Version: MacOS 11.0.1

I would like to report **Jupyter** in VSCode is **incompatible** with `conda` from `miniforce` community supporting native ARM (incl. Apple Chip)
I get this error when **starting** `Python Interactive Window` Or `Create a New Jupyter Notebook`

Could our team help to solve this bug? Thanks.

https://github.com/conda-forge/miniforge
[osx-arm64 (Apple Silicon)](https://github.com/conda-forge/miniforge)

![uP8Fr1](https://user-images.githubusercontent.com/37028078/100303263-fd231480-3000-11eb-94a0-a6389458cc7e.png)

But I can still start **Jupyter lab** or **notebook** as a **standalone server** outside VSCode.

Kind regards
Giang

**Comment by egamma** [comment]
Please report the issue against the python extension.
