### ISSUE TITLE
Reload and Install actions are using same button colour now

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111321]
Before, Install action was using blue and Reload action was using green. But now both are using same colour 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/10746682/100272619-c3e49900-2f5b-11eb-8885-0ef1b521414f.png">

Shall we use green for Reload?

**Comment by misolori** [comment]
I think the main point in removing the green was to make all buttons the same for consistency, so I'd prefer to keep it blue.

**Comment by sandy081** [comment]
Ok, please feel free to close it if there is no action to be taken.
