### ISSUE TITLE
Works on Pycharm, and not on Vscode

### ISSUE THREAD

**Issue by SirCodesAIot** [microsoft/vscode#111335]
VSCode Version and OS Version: LATEST

Details:
Sooo, I have been making a discord bot lately, and I wanted to use vscode for my project. The thing is though when I tried to run the same code on my Vscode (as to Pycharm), and there is going to be an error:
``` python
Traceback (most recent call last):
  File "file_name", line 15, in <module>
    client.run(TOKEN)
  File "file_name", line 708, in run
    return future.result()
  File "file_name", line 687, in runner
    await self.start(*args, **kwargs)
  File "file_name", line 650, in start
    await self.login(*args, bot=bot)
  File "file_name", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
AttributeError: 'NoneType' object has no attribute 'strip'
```

I think that this is an error that Vscode definitely should fix ASAP pls :3 THANKS 👍  :DDDDDDDDDDD

**Comment by SirCodesAIot** [comment]
I don't think I duplicated a issue btw.... if I did, then plssssssssss fix it, I know that making Vscode is a lot of work 👍:3

**Comment by SirCodesAIot** [comment]
There is another thing, it is that you can't access a csv file (or any other file type) from a py file for instance. It just doesn't let me 'access the info inside the csv file from the py file.

**Comment by Tyriar** [comment]
Looking at the error my guess is that it's using a different version of Python or it's a bug in your code. Also python-related issues are typically related to the python extension here: https://code.visualstudio.com/docs/languages/python
