### ISSUE TITLE
please add a new icon short cut to toggle pannel for mouse user

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#111395]
when hide pannel ,for mouse user,thre are very tedious steps to show panel again.
please add an icon to state bar for mouse user to toggle panel 
thanks

**Comment by egamma** [comment]
Please illustrate your feature request with screen shots.

**Comment by MartinGC94** [comment]
I like this idea. I've previously added buttons for this in the Powershell extension: https://github.com/PowerShell/vscode-powershell/pull/2704

So if this doesn't get added you could always create your own tiny extension by just taking the icons and code I wrote in that pull request.

**Comment by heartacker** [comment]
> Please illustrate your feature request with screen shots.

thanks
![image](https://user-images.githubusercontent.com/1876302/100559326-2091dc00-32ed-11eb-974d-18198191b208.png)

**Comment by sbatten** [comment]
@heartacker it is already possible to drag the panel out from the status bar using the mouse. hover over the editor-status bar border and drag upward.

**Comment by heartacker** [comment]
> @heartacker it is already possible to drag the panel out from the status bar using the mouse. hover over the editor-status bar border and drag upward.

thanks for your remind.but without your remind, Very few people konws this. so i think vscode team should re-think about that.
