### ISSUE TITLE
Test: True integrated terminal keybinding support

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11137]
Test #7269

- [x] Mac **@gregvanl**
- [x] Windows **@gregvanl**
- [x] Linux **@octref**

---

The new setting `terminal.integrated.commandsToSkipShell` was added that specifies a list of commands whose keybindings will not be processed by the shell first and instead propogate up to the vscode keybinding handler. For example the default is:

```json
  "terminal.integrated.commandsToSkipShell": [
	  "editor.action.toggleTabFocusMode",
	  "workbench.action.quickOpen",
	  "workbench.action.showCommands",
	  "workbench.action.terminal.copySelection",
	  "workbench.action.terminal.focus",
	  "workbench.action.terminal.focusNext",
	  "workbench.action.terminal.focusPrevious",
	  "workbench.action.terminal.kill",
	  "workbench.action.terminal.new",
	  "workbench.action.terminal.paste",
	  "workbench.action.terminal.runSelectedText",
	  "workbench.action.terminal.scrollDown",
	  "workbench.action.terminal.scrollUp",
	  "workbench.action.terminal.toggleTerminal"
  ]
```

This ensures that all terminal commands are handled to the keybinding handler in addition to accessibility tab focus mode, quick open and the command palette.

Some things to test:

- Whether it works as expected
- Whether the default list of commands makes sense, think whether the default keybindings for these commands would conflict with command terminal programs
- Whether any more commands should be added to the default list of commands

**Comment by dbaeumer** [comment]
@Tyriar Please assign the test plan items to a milestone. Otherwise they don't show up in queries.

**Comment by octref** [comment]
Tested on Win 10 and Ubuntu 16.04. The functionality is fine, but as mentioned in @gregvanl 's two issues, the config doesn't fine-control the behavior precisely. I was able to repro his problems on Win 10 and Ubuntu.

Something else: `Ctrl-Tab` should also be handled, but I feel it should bring up a switcher for all terminals, just like the one for editors.

**Comment by Tyriar** [comment]
@octref you can actually set up keybindings to do that:

```json
{ "key": "ctrl+tab",          "command": "workbench.action.terminal.focusNext",
                              "when": "terminalFocus" },
```

You will probably need to unbind ctrl+tab and rebind it with `"when": "!terminalFocus"` though.

**Comment by octref** [comment]
@Tyriar 
Thanks for the tip!
