### ISSUE TITLE
Unexpected label cropping in ports view

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111378]
* use @egamma's express sample
* run the start script
* check the ports view
* 😕 the actual link shouldn't be cropped, esp not when there is so much space

<img width="1301" alt="Screenshot 2020-11-26 at 18 28 55" src="https://user-images.githubusercontent.com/1794099/100379601-6f9def80-3015-11eb-974a-6a391e5b029b.png">

**Comment by alexr00** [comment]
@jrieken I have gotten specific feedback from many sources that this link **must** be shortened! What do you gain by having the uuid visible?

**Comment by jrieken** [comment]
I wanna know what the uri is and it shouldn't be hidden. Today, I need to either open it or copy/paste - both not very friendly. Also, there is now enough space to show a long'ish url so I don't know how much of the "old" feedback is still valid

**Comment by alexr00** [comment]
The old feedback wasn't that the url was too long, it was that it was too scary. I personally am not afraid of long urls, but I do not feel like I need to know what the whole url is (I'm not going to do anything with the knowledge of what the url is), which means that it is a lot of meaningless characters to show.

**Comment by alexr00** [comment]
That said, I'll make some screenshots of both and share them around.

**Comment by alexr00** [comment]
Further discussion showed that most people want to have the whole URL when the view is in the panel.

**Comment by rzhao271** [comment]
Wondering whether the cropping should only occur when it's in the panel (compared to the sidebar)?

![express-example](https://user-images.githubusercontent.com/7199958/109057298-6b29b700-7696-11eb-9b9a-830167ebadab.PNG)

**Comment by alexr00** [comment]
All address cropping has been removed. Only regular overflow behavior with the ellipse is done (as shown in the screen shot).
