### ISSUE TITLE
paneview defines css for .twisties

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111357]
paneview.css defines rules for twistes, but they are only used in the sub class ([viewPaneContainer](https://github.com/microsoft/vscode/blob/b01183bda2466199047bd59a9dd96f9ba7359f37/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L299)).
https://github.com/microsoft/vscode/blob/75c71b49cc25554adc408e63b876b76dcc984bc1/src/vs/base/browser/ui/splitview/paneview.css#L41

Should the rules move up, or should the twisty be part of the pane?

I came across this as I made the viewPaneContainer twisties themable: a6a53198f6cdea4e3abb1a2aec964b80e402129d and had to remove a twisty related rule.

**Comment by joaomoreno** [comment]
This came from https://github.com/microsoft/vscode/commit/fa8083bb322fa819a6ea8774cc83e80464b4c568

**Comment by misolori** [comment]
Removed the references to `.twisties` to be consistent, fyi @sbatten

**Comment by misolori** [comment]
For verification:
- Create a split view in the panel
- Inspect the folding chevron w/ dev tools
- Ensure the icon does not use `twisties` in either expanded or collapsed views
![image](https://user-images.githubusercontent.com/35271042/100646270-a95f4680-32f2-11eb-9ebf-2dd50ef74cca.png)
