### ISSUE TITLE
Support real-time OutputChannel

### ISSUE THREAD

**Issue by YitongFeng-git** [microsoft/vscode#111481]
Currently, if I run a cmd command and want to log to the OutputChannel, the steps are
1. Run command, and get stdout
2. outputChannel.appendLine(stdout)
3. outputChannel.show( )

But, what if the command execution time is very long, and I want to see the real-time output ? Currently I can only wait for it finished and then append to outputChannel. Or anyother VSCode APIs can support my scenario?

Thanks!

**Comment by isidorn** [comment]
Basically as the commend is spiiting out output you should be abble to call appendLIne thus getting the output in real time
