### ISSUE TITLE
Settings Sync with Github OAuth is failing

### ISSUE THREAD

**Issue by sairaghavak** [microsoft/vscode#111468]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19042

Straight from **VSCode Help**
```Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
Steps to Reproduce:

1. Start vscode and see the console log from `Output` tab
	> [2020-11-29 23:49:19.185] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
	> [2020-11-29 23:49:19.185] [userDataSync] [info] Auto Sync is enabled.
	> [2020-11-29 23:49:19.185] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
2. Sign in to Sync Settings
3. Sign in with Github
	> https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate%253FwindowId%253D1&scope=user:email&state=24e1d69a-8e3f-4fe4-9ed0-adddc7a83b58&responseType=code&authServer=https://github.com
4. Login to github and authorize vscode
5.https://vscode-auth.github.com/?browser_session_id=94cd7bad381ce161b12701f21d7a083672e9da19bb6ba95d1239e427f00fa5f1&code=09898cd41a1cf59e3a5e&state=iIL8P-bW03Mo_Y41OhwrSiiEXYw%2FeyJhdXRoU2VydmVyIjoiaHR0cHM6Ly9naXRodWIuY29tIiwiY2FsbGJhY2tVcmkiOiJ2c2NvZGU6Ly92c2NvZGUuZ2l0aHViLWF1dGhlbnRpY2F0aW9uL2RpZC1hdXRoZW50aWNhdGU_d2luZG93aWQ9MSIsInJlc3BvbnNlVHlwZSI6ImNvZGUiLCJzdGF0ZSI6IjM2N2MwMmRhLWQ3OTYtNDEyMi05MTc0LWQ2YWU0OWVkOTRiYiIsImlkIjoiOjpmZmZmOjEwLjk5LjIwOS4xMTYifQ
6. It's gonna redirect back to vscode and see the log from `Output`	
	> [2020-11-29 23:52:23.017] [userDataSync] [info] Auto Sync: Started
	> [2020-11-29 23:52:23.019] [userDataSync] [info] Auto Sync: Triggered by Interval
	> [2020-11-29 23:52:23.040] [userDataSync] [info] Auto Sync: Suspended until auth token is available.
	> [2020-11-29 23:52:23.041] [userDataSync] [info] Auto sync: Cancelled sync that is in progress
	> [2020-11-29 23:52:23.041] [userDataSync] [info] Auto Sync: Stopped
7. Otherwise, copy the authcode and paste in the status bar of SignIn flow
	> vscode://vscode.github-authentication/did-authenticate?windowid=1&code=&lt;your-auth-code&gt;

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@sairaghavak Can you copy the log from the "GitHub Authentication" output channel?

**Comment by sairaghavak** [comment]
Sure, here it is
![image](https://user-images.githubusercontent.com/16429828/100662102-7365a500-337a-11eb-978a-7d7af44657ff.png)

**Comment by sairaghavak** [comment]
Any update on this

**Comment by TylerLeonhardt** [comment]
Hi @sairaghavak 👋

I recently gained ownership of the auth feature and so I'm getting ramped up!

It's been few versions now... Can you confirm if you're still seeing this issue?

Thanks!

**Comment by sairaghavak** [comment]
@TylerLeonhardt 

Looks like it is working this time

Here is my VSCode version details where I have verified
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
```
GitHub Authentication log
![image](https://user-images.githubusercontent.com/16429828/118388767-01d99480-b644-11eb-93c9-80c12e555e36.png)

Settings Sync log
![image](https://user-images.githubusercontent.com/16429828/118388811-3d745e80-b644-11eb-87f7-9da4d4e96748.png)

Please share the link to the release notes/version in which this fix is pushed for reference.

**Comment by TylerLeonhardt** [comment]
I've just gained ownership of this space so I'm not entirely sure when this was fixed for you but in the future I'll be able to assist better being more involved with the actual code.

Anyway, glad it's fixed for you. I'll close this now. Thanks!
