### ISSUE TITLE
Open Keyboard Shortcuts Reference shows everytime welcome screen from Edge

### ISSUE THREAD

**Issue by MakiWolf** [microsoft/vscode#111470]
- VSCode Version: 1.51.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Click on Keyboard Shortcuts Reference
![grafik](https://user-images.githubusercontent.com/73300633/100550809-c8bb8c80-327c-11eb-8d19-d77b0f6d452d.png)
2. It opens with Microsoft Edge Browser, but every time the welcome screen from Edge is shown before (Edge Version 87.0.664.47)

**Comment by chrmarti** [comment]
I would expect the Welcome screen to open only once. There appears to be a way to turn it off completely: https://techcommunity.microsoft.com/t5/discussions/prevent-first-time-run-screen-on-edge-beta/m-p/1098825/highlight/true#M20928. Hope that helps.
