### ISSUE TITLE
there is an issue in search

### ISSUE THREAD

**Issue by mnr73** [microsoft/vscode#111494]
- VSCode Version: 1.51.1
- OS Version: windows 10 x64 10.0.18.363

Steps to Reproduce:

1. I search in my damaged file directory same thing in VScode and Brackets
2. in brackets find 15 files
3. in VScode find 7 files

![2020-11-30_13-19-53](https://user-images.githubusercontent.com/23061025/100595507-395fb900-3310-11eb-840c-c23a0a056101.jpg)

![2020-11-30_13-20-43](https://user-images.githubusercontent.com/23061025/100595514-3c5aa980-3310-11eb-84e6-f729af8f74e2.jpg)

**Comment by mnr73** [comment]
I checked all settings there is no exclude and I checked with different search settings

but brackets found all my lost file that I need them

**Comment by IllusionMH** [comment]
/needsMoreInfo

What do you mean under "damaged directory"?

Also VS Code might exclude ignored/excluded files.
Make sure that you have this toggle unchecked (no background)
![image](https://user-images.githubusercontent.com/1312662/100602866-226b9780-330d-11eb-807b-d83f811a9c33.png)

**Comment by mnr73** [comment]
I find why this happened
my files are damaged and some of them have some not binary data like image below

![2020-11-30_14-46-36](https://user-images.githubusercontent.com/23061025/100604203-754c4b80-331b-11eb-9d95-bcd71794d7f2.jpg)
![2020-11-30_14-47-12](https://user-images.githubusercontent.com/23061025/100604222-7aa99600-331b-11eb-9760-d55f3255d14f.jpg)

and VScode don't search in them

**Comment by mnr73** [comment]
My files were lost by mistake
and I recovered them but they were damaged like picture

**Comment by roblourens** [comment]
Glad you figured out the problem, we don't search in files that look like binary files, doing this would make search slower.
