### ISSUE TITLE
Turn off tokenization for specific files or file types

### ISSUE THREAD

**Issue by chiragpaliwal** [microsoft/vscode#111409]
Sometimes we are dealing with some files which need not require tokenization, for example, while working with Apex (Salesforce) debug logs (.log) files do not require tokenization but it takes a significant amount of time to just load up the file in VSCode; The tokenization skims past 23K lines of code which provides no value to the developer. 

**Hence the feature request, it would be nice to allow users to skip tokenization for certain file types/directories/files which will boost performance and developer productivity.**

Cheers ✌

**Comment by IllusionMH** [comment]
/needsMoreInfo

Have you tried to mark these files as `plaintext`?
```json
"files.associations": {
    "**/logs/**": "plaintext",
    // or more detailed
   "**/logs/**/*.log": "plaintext"
}
```

Does it improve load time in your case?

**Comment by chiragpaliwal** [comment]
> /needsMoreInfo
> 
> Have you tried to mark these files as `plaintext`?
> 
> ```json
> "files.associations": {
>     "**/logs/**": "plaintext",
>     // or more detailed
>    "**/logs/**/*.log": "plaintext"
> }
> ```
> 
> Does it improve load time in your case?

This is a neat workaround to avoid tokenization. Thanks for the suggestion. 👌
