### ISSUE TITLE
After changing case of a file, the filename appears twice in search results and replaces are currupt in that file

### ISSUE THREAD

**Issue by Polfo** [microsoft/vscode#111407]
#12448 is closed, and should be solved in `1.49` but I still have the issue in Version 1.51.1 Dated 2020-11-10.
https://github.com/microsoft/vscode/issues/12448#issuecomment-655002802

(https://user-images.githubusercontent.com/10303392/100438543-948c7400-30a2-11eb-9f75-52031e0684b4.JPG)

Applying @benlesh workaround wiped my workspace content, but it also solved the double files issue.
https://github.com/microsoft/vscode/issues/12448#issuecomment-655001292

**Comment by Polfo** [comment]
#12448 is closed, and should be solved by now, but I still have the issue in Version 1.51.1 Dated 2020-11-10.
Applying @benlesh solution wiped my workspace content, but it also solved the double files issue.

**Comment by Polfo** [comment]
Meanwhile I found a much easier workaround;
rename the file to a different name (not only different case), then rename it back to the desired name.

**Comment by roblourens** [comment]
Was one of those open in an editor when you ran this search?
