### ISSUE TITLE
cannot connect to the extensions marketplace

### ISSUE THREAD

**Issue by Raihanyx** [microsoft/vscode#111466]
Issue Type: <b>Bug</b>

When i try to open the extention marketplace, i can't open it and it says "we cannot connect to the extensions marketplace at this time". Please fix this as soon as possible because this is really bothering me and i cannot install an extention to do my work

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (9.69GB free)|
|Process Argv|--crash-reporter-id 78f89258-6c6c-4b8b-82eb-8175724c7d7d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992

</details>

**Comment by sandy081** [comment]
Please provide logs from following locations:

- Help -> Toggle Developer Tools -> Console
- Help -> Toggle Developer Tools -> Network (any failed requests)
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

Are you bending any network proxy settigns?
