### ISSUE TITLE
Align more keybindings with Mac conventions

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode#11148]
I know I can override my keybindings, but this bug is about sensible defaults.

Take the simple <kbd>Cmd+{</kbd>. iTerm2 is sitting beside vscode, and I <kbd>Cmd+Tab</kbd> to it and use this keybinding. When I <kbd>Cmd+Tab</kbd> back to vscode, this key combination suddenly does folding. I'm supposed to use <kbd>Ctrl+$digit</kbd> to switch between tabs here. And <kbd>Cmd+$digit</kbd> means something else entirely! This is unacceptable.

I come from the Emacs world, so I'm used to hitting <kbd>Ctrl+g</kbd> to cancel any operation (equivalent to vscode's <kbd>Esc</kbd>). In vscode, this key combination is goto-line! goto-lie is a fairly common operation, so this is fine; I can choose to either re-train my muscle memory or override.

I come from the Atom world as well, and <kbd>Cmd+b</kbd> switches buffers. This in itself isn't so bad, but the alternative chosen for <kbd>Cmd+b</kbd> is terrible! Why is hiding the left-pane such a common operation that we need to provide a toplevel keybinding for it? In the absence of a better suggestion, we can alias it to <kbd>Cmd+p</kbd>.

<kbd>Cmd++</kbd> being replaced with <kbd>Cmd+=</kbd> is an unnecessary source of confusion.

**Comment by bpasero** [comment]
Until then, you can change keybindings as you like in settings.

**Comment by artagnon** [comment]
In the Human Interface Guidelines for OS X, we need to pay attention to this section: https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/

I can help with the effort, once we decide which keybindings need to be changed.
