### ISSUE TITLE
No typescript version, intelisense and autoimport on VsCode

### ISSUE THREAD

**Issue by rogerio3** [microsoft/vscode#111483]
Issue Type: <b>Bug</b>

No any typescript commands on pallete.
<img width="835" alt="Captura de Tela 2020-11-30 às 01 33 01" src="https://user-images.githubusercontent.com/58600118/100572186-a8f38b00-32b3-11eb-965e-7264fd9a6ce0.png">

On settings.json all typescript configurations are enabled but commands are ignored, and on mouseover it shows [ Unknown Configuration Setting
No quick fixes available ]

- tried reinstall vscode no success
- tried update, install, uninstall, reinstall my typescript globally with yarn and npm.. no success.
- tried load VsCode extensions disabled, no success 
- typescript version  not detected on status bar when typescript file selected.
- tried vscode typescript.tsdk config but command are not recognized.
- when prompt command:  tsc -v returns "Version 4.1.2"

<img width="697" alt="Captura de Tela 2020-11-30 às 02 25 06" src="https://user-images.githubusercontent.com/58600118/100572216-bad52e00-32b3-11eb-95e8-756562b0916f.png">

<img width="444" alt="Captura de Tela 2020-11-30 às 02 31 17" src="https://user-images.githubusercontent.com/58600118/100572419-2ddea480-32b4-11eb-8087-7280483666d0.png">

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id f5102694-9b06-41f2-a0f3-843a17b7ce3b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
vscode-sqlite|ale|0.10.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
json2ts|Gre|0.0.6
vscode-edit-csv|jan|0.5.0
vscode-peacock|joh|3.8.0
vscode-styled-components|jpo|1.3.0
json2csv|kha|0.0.1
rainbow-csv|mec|1.8.0
vscode-filesize|mkx|2.1.4
vscode-docker|ms-|1.8.1
mssql|ms-|1.9.0
jupyter|ms-|2020.11.372831992
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|4.2.20201128
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.4.0
tsimporter|pmn|2.0.1
vscode-data-preview|Ran|2.2.0
typescript-hero|rbb|3.0.0
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
autoimport|ste|1.5.3
rewrap|stk|1.13.0
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vim|vsc|1.17.1
vscode-import-cost|wix|2.12.0
editorconfig-vscode-snippet|zgu|0.2.0

(3 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Looks like you've disabled the built-in JS/TS extension. In the extensions view, search`@builtin typescript` and make sure `TypeScript and JavaScript Language Features` is enabled
