### ISSUE TITLE
Indent symbols in Go To Symbol editor in markdown instead of # symbol

### ISSUE THREAD

**Issue by vwkd** [microsoft/vscode#111477]
In a Markdown document, the Go To Symbol window shows the headings. This is very useful and I often use this as a built-in table of contents to get an overview of the document.

However, I find the preceding # signs before every heading distracting. I think it would be much better, if the headings would be indented just like they would be in a TOC.

This is a quick and dirty photoshop of how it could look like.

before:
<img width="1026" alt="before" src="https://user-images.githubusercontent.com/33468089/100558491-fcafa580-32ae-11eb-8c3f-fe46f2d59fe6.png">

after:
<img width="1026" alt="after" src="https://user-images.githubusercontent.com/33468089/100558488-fb7e7880-32ae-11eb-9ca4-039f875d44be.png">

Notice, I didn't remove the # signs for the light-grey annotation of the parent heading for each entry. But this could certainly be considered, since with a visual hierarchy the # signs wouldn't add much value anymore.

**Comment by mjbvz** [comment]
Not in favor of this since leading spaces look strange once you start filtering down the list
