### ISSUE TITLE
VS Code should detect end of stack if returned number of frames is smaller than requested number

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#111413]
Setting `StackTraceResponse.totalFrames` to a huge value (e.g. 100000) is supported by the DAP spec, because it helps debug adapters that have a hard time determining the exact number of frames in an efficient way.

VS Code already supports large (bogus) values for `StackTraceResponse.totalFrames` but it always shows the "Load All Stack Frames" action at the bottom of the stack. 

I suggest that VS Code tries to detect the end of the stack as soon as the returned number of frames is smaller than the requested number.

This will still result in a unnecessary "Load All Stack Frames" action link in case the returned number of frames is identical to the requested number, but IMO we can swallow that...

You can reproduce this bug by enabling the `totalFrames: 100000` assignments here:
https://github.com/microsoft/vscode-mock-debug/blob/0090320aa62becfdb255c2aaf204e5b48136be12/src/mockDebug.ts#L284

**Comment by weinand** [comment]
This works fine:
- if totalFrames = 1000000
- totalFrames is missing
- totalFrames: startFrame + maxLevels + 20

But funnily it does not work if totalFrames contains the correct number of frames.
In this case the second (and final batch) still shows the "Show all frames" action.

**Comment by weinand** [comment]
It could very well be that you are not able to detect the case that totalFrames contains the correct number of frames which results in the unnecessary action. If this is the case I suggest that you remove the action as soon as it was pressed and no additional frames were received.

**Comment by isidorn** [comment]
That is fair. Moving this to next week to tackle it in debt week.

**Comment by isidorn** [comment]
Good catch, I have pushed a fix for this case.

**Comment by weinand** [comment]
Great, now all 4 cases work fine!
