### ISSUE TITLE
Debugger displaying the wrong variables inside a callback called by a module

### ISSUE THREAD

**Issue by danielpassy** [microsoft/vscode#111419]
- VSCode Version: 1.51.1 (user setup)
- OS Version: Windows_NT x64 10.0.1863
- Node: 12.14.1

Steps to Reproduce:

1. create a JS file
2. Install package node-schedule
npm i node-schedule
3. copy the following code
```js
var schedule = require('node-schedule');
class Scheduler {
    constructor() {
        this.jobList = []
    }

    onHandler() {
        schedule.scheduleJob("11 11  *  *  *",
            async () => {
                console.log(this)
            }
        )
    }
}
```
4 - set a break point on console.log(this)
5 - Change the cron time to the next minute, otherwise it wont start:
 ("11 11  *  *  *" =  (min hour * * * * *
6 - start debug mode with Node 
7 - inspect Variables, see local this: 
![image](https://user-images.githubusercontent.com/20033745/100458248-33fd3700-30a2-11eb-885f-639fe03c06af.png)
compare with the printed value:
![image](https://user-images.githubusercontent.com/20033745/100458372-6a3ab680-30a2-11eb-8ace-9a310ccf43cb.png)

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by weinand** [comment]
If you pass a structured object ("this") to console.log while debugging, the object is shown in the debug console as an expandable object (hence the '>').

This works as designed.

**Comment by danielpassy** [comment]
Yes, I didn't make myself clear.
Those 2 this are different: one is a "Job" instance, that was created inside the "schedule.scheduleJob" function, and the other is "Scheduler" instance, the class instance.

**Comment by weinand** [comment]
Your code does not seem to be complete.
Neither is your class Scheduler instantiated, nor is the "onHandler" method called.
