### ISSUE TITLE
Multiple ports forwarded of same app?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111400]
I setup once @egamma express app in codespaces and ran it. Then I reloaded and ran it again and I find 2 ports forwarded:

![image](https://user-images.githubusercontent.com/900690/100425588-cd6f1d80-308f-11eb-8715-ad28b2f05273.png)

**Comment by alexr00** [comment]
For some reason codespaces is forwarding some of those ports. It probably shouldn't do that.

I will get rid of the duplication though.
