### ISSUE TITLE
 Suggestion/highlights on componentDidUpdate()

### ISSUE THREAD

**Issue by heyshak** [microsoft/vscode#111458]
- VSCode Version: October 2020 (version 1.51)
- OS Version:

Steps to Reproduce:
1.Any method which accepts/takes some kind of argument, VSCode shows some suggestion/highlight for this.
3.Same way componentDidUpdate() in Reactjs take three-argument such as **prevProps**,**prevState** and **snapshot**.
4.Actualy in accepting the argument, there is the serialization I mean to say which argument comes first and which comes later.
5.Actual behavior is **componentDidUpdate(prevState: any, prevProps: any, snapshot: any)**

Expected Behavior
1.**componentDidUpdate(prevProps, prevState, snapshot)** according to Reactjs docs.

**I hope this will help to counter the problem**

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share steps to reproduce this issue and describe the expected behavior in more detail

**Comment by mjbvz** [comment]
Closing as it's not clear to me what the expected behavior is
