### ISSUE TITLE
Accounts menu says "Loading..." on brand new oss launch

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111497]
Out of dev:

![image](https://user-images.githubusercontent.com/22350/100597258-838b6f00-32fd-11eb-8808-b8c9156d16d2.png)

**Comment by AldsTan** [comment]
Happy New Year! I'm experiencing the same. Details:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-19T14:42:39.893Z
Electron: 9.4.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.3-arch1-1

**Comment by wyhgoodjob** [comment]
Same issue too, my details:
version:1.52.1.1
Date:2021-01-26
OS:manjaro
Desktop:KDE

I install it from the official application manager(GUI), and get "Loading" from account menu.
When I download a package from the VSCode official website, it works and can sync my account data, but when I use pacman or application manager(GUI) to install Code OSS, it still shows "Loading" at account menu

**Comment by Heikrana** [comment]
> Same issue too, my details:
> version:1.52.1.1
> Date:2021-01-26
> OS:manjaro
> Desktop:KDE
> 
> I install it from the official application manager(GUI), and get "Loading" from account menu.
> When I download a package from the VSCode official website, it works and can sync my account data, but when I use pacman or application manager(GUI) to install Code OSS, it still shows "Loading" at account menu

Any binary build like Code - OSS doesn't include accounts functionality and many extensions. Try installing [code-marketplace](https://aur.archlinux.org/packages/code-marketplace), it will enable all those extensions found in MS VSCode and you can then use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) from Shan Khan which uses private github gist linked to your account for syncing.

The Settings sync which comes with VSCode doesn't work because of the same above mentioned issue, you can use snap to install that build.

Cheers.

**Comment by dupr0n** [comment]
> > Same issue too, my details:
> > version:1.52.1.1
> > Date:2021-01-26
> > OS:manjaro
> > Desktop:KDE
> > I install it from the official application manager(GUI), and get "Loading" from account menu.
> > When I download a package from the VSCode official website, it works and can sync my account data, but when I use pacman or application manager(GUI) to install Code OSS, it still shows "Loading" at account menu
> 
> Any binary build like Code - OSS doesn't include accounts functionality and many extensions. Try installing [code-marketplace](https://aur.archlinux.org/packages/code-marketplace), it will enable all those extensions found in MS VSCode and you can then use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) from Shan Khan which uses private github gist linked to your account for syncing.
> 
> The Settings sync which comes with VSCode doesn't work because of the same above mentioned issue, you can use snap to install that build.
> 
> Cheers.

I tried this solution, but the settings sync seems broken when I try to download the settings from github. It opens the browser and shows login success, but when I go back to VSCode, it shows a broken layout saying no gists exist, with no button to click.

**Comment by miho87** [comment]
I had the same issues on manjaro when using the package "Code - OSS (code)" from the official repository, but the AUR package visual-studio-code-bin works fine for me.

**Comment by dupr0n** [comment]
> I had the same issues on manjaro when using the package "Code - OSS (code)" from the official repository, but the AUR package visual-studio-code-bin works fine for me.

Yeah, that's microsoft's commercial version of VSCode. Not open source.

**Comment by arduinka55055** [comment]
same
but it worked until now
broken after manjaro update

**Comment by RMacfarlane** [comment]
Closing as I'm not able to repro in OSS based on the current main

**Comment by EFanZh** [comment]
I am still having this problem with the [code](https://archlinux.org/packages/community/x86_64/code/) package from Arch Linux.

**Comment by dupr0n** [comment]
Same

> I am still having this problem with the [code](https://archlinux.org/packages/community/x86_64/code/) package with version 1.56.2-2 from Arch Linux.

Same. Maybe this is an arch linux based problem? I've had this issue everytime. Be it code OSS or vscodium. I just use my account to sync, so instead of this, I use the "Settings Sync" extension.

**Comment by mozart27** [comment]
I am having this issue with v 1.57.0

```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.895Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-74-generic
```
