### ISSUE TITLE
PHP executable not found. Install PHP 7 and add it to your PATH or set the php.executablePath setting

### ISSUE THREAD

**Issue by aruanalucena** [microsoft/vscode#111433]
Issue Type: <b>Feature Request</b>

PHP executable not found. Install PHP 7 and add it to your PATH or set the php.executablePath setting

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by lcarboneto** [comment]
In my case, I have XAMPP installed ...
I opened the VSCode
I went to Settings
I searched for "php.validate.executablePath"
and in the setting.json link I typed:
"C: /xampp/php/php.exe" in "php.validate.executablePath": "",

**Comment by lcarboneto** [comment]
> Issue Type: Feature Request
> 
> PHP executable not found. Install PHP 7 and add it to your PATH or set the php.executablePath setting
> 
> VS Code version: Code 1.51.1 ([e5a624b](https://github.com/microsoft/vscode/commit/e5a624b788d92b8d34d1392e4c4d9789406efe8f), 2020-11-10T23:34:32.027Z)
> OS version: Windows_NT x64 10.0.18363

In my case, I have XAMPP installed ...
I opened the VSCode
I went to Settings
I searched for "php.validate.executablePath"
and in the setting.json link I typed:
"C: /xampp/php/php.exe" in "php.validate.executablePath": "",
