### ISSUE TITLE
Double click in commit edit box moves focus away

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#111496]
Issue Type: <b>Bug</b>

When double clicking on a word in the commit edit box the keyboard focus goes back to the diff editor. This is painful because subsequent editing does not change the commit message but modifies the diff editor's contents.

Please note: I'm on macOS Big Sur

![2020-11-30_11-05-06 (1)](https://user-images.githubusercontent.com/1898161/100596716-c567e580-32fc-11eb-8d1c-f2479278a8a1.gif)

VS Code version: Code - Insiders 1.52.0-insider (f47aae014cf8567f648e68369d66b4106ae89f08, 2020-11-30T05:42:34.551Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 785023c0-aeb7-4708-b29f-2c6aa9e59a8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
tsl-problem-matcher|eam|0.3.1
codespaces|Git|0.2.0
vscode-pull-request-github|Git|0.21.3
jupyter|ms-|2020.11.372831992
remote-containers|ms-|0.151.0
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.3.0
vscode-github-issue-notebooks|ms-|0.0.58
vscode-typescript-tslint-plugin|ms-|1.2.3
gitblame|wad|6.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30226749
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt859:30228413

```

</details>

**Comment by joaomoreno** [comment]
This is **really** strange.

**Comment by weinand** [comment]
seems to be fixed now, great!
