### ISSUE TITLE
Import Jupyter Notebook Error

### ISSUE THREAD

**Issue by dudeacough** [microsoft/vscode#111437]
Issue Type: <b>Bug</b>

when attempting to import a jupyter notebook it errors without opening.  The error says 

Unable to import jupyter notebook.  Repeateadly says:

rror 2020-11-27 21:54:04: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
	at u.getExportInterpreter (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:32:528426)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async _.export (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:256389)
	at async /Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:428961
	at async u.waitWithStatus (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:803142)
	at async C.importNotebook (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:428831)
	at async C.listenForErrors (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:424173)]

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 072441f4-4214-4e90-8117-4ae76d335ed3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.0.0
gitlens|eam|11.0.5
vscode-docker|ms-|1.8.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
remote-containers|ms-|0.148.1
vscode-fileutils|sle|3.4.2
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.10

</details>

**Comment by lcarboneto** [comment]
> Issue Type: Bug
> 
> when attempting to import a jupyter notebook it errors without opening. The error says
> 
> Unable to import jupyter notebook. Repeateadly says:
> 
> rror 2020-11-27 21:54:04: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
> at u.getExportInterpreter (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:32:528426)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:94:5)
> at async _.export (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:256389)
> at async /Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:428961
> at async u.waitWithStatus (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:803142)
> at async C.importNotebook (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:428831)
> at async C.listenForErrors (/Users/paulromano/.vscode/extensions/ms-toolsai.jupyter-2020.11.372831992/out/client/extension.js:49:424173)]
> 
> VS Code version: Code 1.51.1 ([e5a624b](https://github.com/microsoft/vscode/commit/e5a624b788d92b8d34d1392e4c4d9789406efe8f), 2020-11-11T01:11:34.018Z)
> OS version: Darwin x64 19.6.0
> 
> System Info
> Extensions (9)

Did you install the Jupyter extension on the VSC?
I have installed ms-toolsai.jupyter and it works fine.

**Comment by dudeacough** [comment]
Yes I have the Jupiter extension installed, It installed automatically with the python extension.  I have attempted to uninstall and then reinstall both extensions, but the issue still comes up.  ~Paul
