### ISSUE TITLE
Extension installations failing

### ISSUE THREAD

**Issue by adedaporh** [microsoft/vscode#111464]
Issue Type: <b>Bug</b>

1. Open _Extesnions_ tab
2. Search for extension to install
3. Click on _Install_
4. Status showing _downloading_
5. Error message pops up: "Failed to install 'octref.vetur'."
6. And also "Unable to open 'Extension: Vetur': XHR timeout: undefinedms."

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
dotenv|mik|1.0.1
remote-containers|ms-|0.148.1
remote-wsl|ms-|0.51.4
vscode-docker|ms-|1.8.1
subtle-brackets|raf|3.0.0

(1 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please provide following logs?

- Help -> Toggle Developer Tools -> Console
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

**Comment by vincentbudianto** [comment]
I have also encountered this problem (Windows 10, vscode version 1.51.1).

Logs:
- Developer Tools Console
![image](https://user-images.githubusercontent.com/42698353/100607361-6ececb80-333d-11eb-92b5-97cc801afccf.png)

- Shared Process Console
![image](https://user-images.githubusercontent.com/42698353/100607300-5a8ace80-333d-11eb-9e70-07454ca9d7ca.png)

- Log (Window)
![image](https://user-images.githubusercontent.com/42698353/100607157-17c8f680-333d-11eb-8d28-e5621c9b6820.png)

- Log (Shared)
![image](https://user-images.githubusercontent.com/42698353/100607013-dcc6c300-333c-11eb-91ec-16faf27ba307.png)

**Comment by sandy081** [comment]
Seems you are not able to connect to Marketplace - can you please check if you can access Marketplace from browser?

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

**Comment by vincentbudianto** [comment]
> Seems you are not able to connect to Marketplace - can you please check if you can access Marketplace from browser?
> 
> https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

I can access it from the browser

**Comment by sandy081** [comment]
@deepak1556 Passing it on to you - as the underlying request is returning with timeout.

**Comment by deepak1556** [comment]
Can you launch code with `--log-net-log=netlog.json` , perform the extension search and attach the generated log once you quit the app.

**Comment by vincentbudianto** [comment]
It's functioning properly now (can update and install extension). Thank you
