### ISSUE TITLE
Add argument to `workbench.action.alternativeAcceptSelectedQuickOpenItem` to configure direction

### ISSUE THREAD

**Issue by typoon** [microsoft/vscode#111476]
Currently when one wants to create a keybinding for the `QuickOpen` dialog to open a file in a split editor that can be done using the command `workbench.action.alternativeAcceptSelectedQuickOpenItem`. Issue with this is that this will only open the file in a vertical split to the right. 

The feature I am requesting is for `workbench.action.alternativeAcceptSelectedQuickOpenItem` to accept an argument that allows specifying the direction in which to open the new editor (Up, Down, Left, Right).

Thanks!

**Comment by bpasero** [comment]
Not a big fan because this command is not talking about editors currently. We have a generic setting `workbench.editor.openSideBySideDirection` that controls the default opening location for split editors.

**Comment by typoon** [comment]
Supposing I want to add a <Ctrl+s> to the quick open context to open a new
editor below the current one and a <Ctrl+v> to open one to the left and a
<Ctrl+h> to open above. How would one do that using that setting?

I don't think there is a way to set that setting, execute
the `workbench.action.alternativeAcceptSelectedQuickOpenItem` action and
then restore the setting back to what it was.
