### ISSUE TITLE
Scrolling stops after switching desktops

### ISSUE THREAD

**Issue by validatedev** [microsoft/vscode#111434]
Issue Type: <b>Bug</b>

1. Open VS Code.
2. Open a file that is scrollable.
3. Scroll the file via Precision touchpad then quickly switch (back-forth) the desktops using the touchpad then immediately scroll again.
4. You can see that scrolling with the touchpad doesn't work (works with mouse).

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.91GB free)|
|Process Argv|--crash-reporter-id 4efbe4cd-986d-4672-b94c-9156570b1db0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
doxdocgen|csc|1.1.0
gitlens|eam|11.0.5
prettier-vscode|esb|5.8.0
lex-flex-yacc-bison|fau|0.0.3
vscode-pull-request-github|Git|0.21.2
gc-excelviewer|Gra|3.0.40
better-cpp-syntax|jef|1.15.5
language-julia|jul|1.0.10
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.372831992
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.4
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.2
cpptools-extension-pack|ms-|1.0.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vsonline|ms-|1.0.3075
tabnine-vscode|Tab|3.1.13
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by validatedev** [comment]
Video about reproducing the issue: https://youtu.be/Z-LBmWaX4-s

**Comment by validatedev** [comment]
It also happens with Google Chrome and Microsoft Edge. It may be a Chromium bug.

**Comment by alexdima** [comment]
@validatedev If it reproduces with both Chrome and Edge, this definitely sounds like a Chromium issue. Could you please create an issue directly at https://bugs.chromium.org/p/chromium/issues/list ?

**Comment by validatedev** [comment]
@alexdima Thanks for the response btw!
Ok, I will immediately open a new issue, while keeping this issue open.

**Comment by validatedev** [comment]
Here's the bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1153456

**Comment by alexdima** [comment]
> We have found that this occurs due to a bug in the Windows DirectManipulation API, and affects devices that use a Precision touchpad. An OS fix has been issued and will be public in the Jan/Feb timeframe. We believe that no changes need to be made in Chromium, so no need for the bisect :)

https://bugs.chromium.org/p/chromium/issues/detail?id=1134605#c6

Closing as this is an OS bug that will ship soon.

**Comment by validatedev** [comment]
Oh forgot to close that issue. I’m aware of that fix. Thanks.
