### ISSUE TITLE
VSCode Error: Input(): lost sys.stdin

### ISSUE THREAD

**Issue by AadiSahni** [microsoft/vscode#111416]
When trying to run the following code, VS returns with an error "Input(): lost sys.stdin"
`Input17H = input()`
Searching online, didn't help, as none of the methods worked.

- VSCode Version: 1.51.1
- OS Version: Windows 10 Pro 20H2 Build Version 19042.630  

Steps to Reproduce:

1.
2.

Extensions:
1. Python v2020.11.371526539
2. Juypter v2020.11.372831992

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by egamma** [comment]
Please file the issue against the Python extension or even better ask on StackOverflow
