### ISSUE TITLE
Ability to refresh problems

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode#111443]
Hi. Wanted to suggest a small but significant improvement to displaying problems with VSCode.

VSCode currently shows problems like this. The thing is that, while all the problems were valid before, they are no longer valid (eg. I fixed the problem, renamed/moved/deleted a file and so on).

<img width="776" alt="1" src="https://user-images.githubusercontent.com/1165845/100519688-9730bb80-31bf-11eb-95ec-9097589155cf.png">

Now, to my knowledge, I don't find a way to refresh/recheck my workspace for problems easily (I have to either wait for the problems to automatically disappear at some point or restart VSCode to manually recheck the problems).

A refresh option in the problems pane would be nice to have when clicked rechecks the workspace for problems.

**Comment by sandy081** [comment]
Problems view gets updated automatically when an error is added/removed/updated. In your case, it means the corresponding extension is not updating. So please file issue against the extension.

**Comment by tvvignesh** [comment]
@sandy081 I agree that it refreshes automatically as you rightly said, but my issue was to allow triggering the refresh manually from a single place which will trigger the rechecking across all extensions. Isn't that possible?

**Comment by sandy081** [comment]
I do not think so and such command/task shall be contributed by extensions so that they can rebuild / reconcile the problems.
