### ISSUE TITLE
"Go To Definition" sometimes takes long time to load on JS React

### ISSUE THREAD

**Issue by appar-sc** [microsoft/vscode#111493]
## Env
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

## Steps to Reproduce

Please check instant replay video: [QAReplay Link](https://qareplay.com/replay?id=JnUzcFzhQbZrONF8ihPrQqA7m), can start from 00:09

1. ```Cmd + P``` to find the certain class A file
2. ```Cmd + left click``` on the certain class B to see the definition of it
3. ```Crtl + -``` to go back to the previous cursor
4. Double click on the class A filename on the top
4. ```Cmd + left``` click again on class B

Then you should be able to see that it's taking a long time to load the definition of class B now

[UPDATE 2020-1201]
Does this issue occur when all extensions are disabled?: Happen occasionally

**Comment by mjbvz** [comment]
So disabling extensions fixes this issue?

**Comment by appar-sc** [comment]
After disabling all extensions, this issue still happens

**Comment by mjbvz** [comment]
Do you know which extension in particular causes the issue?
