### ISSUE TITLE
Malware Scan returned password stealer?

### ISSUE THREAD

**Issue by arcad3luke** [microsoft/vscode#111432]
I recently ran a system scan through Malwarebytes, and it is returning the path to Visual Studio Code (specifically the file csc.exe). The path from the install directory is Visual Studio\Shared\Packages\Microsoft.Net.Compilers.2.6.1\tools\csc.exe. I don't know if that file is in fact malicious, or my A/V is reporting falsely.

**Comment by IllusionMH** [comment]
> The path from the install directory is Visual Studio\Shared\

This is repo for VS Code editor, not VS 201X IDE. 
Are you sure that you are reporting in correct place?

**Comment by joaomoreno** [comment]
Yeah this seems to be about Visual Studio, not Code.
