### ISSUE TITLE
.gitignored files removed by "Clean All" action

### ISSUE THREAD

**Issue by xirzec** [Microsoft/vscode#11149]
- VSCode Version: 1.4.0
- OS Version: Windows 10 (1607 / build 14393.82)

If you select "Clean All" while you have changes staged, then a .gitignored `.vscode/launch.json` file will be unexpectedly removed. 

Steps to Reproduce:
1. Create an empty folder
2. Open the folder in VS Code
3. Switch to the git tab
4. Initialize the git repository
5. Hit F5
6. Select "Node.js" to create a launch.json
7. Create a .gitignore file with the contents `.vscode/launch.json`
8. Stage the .gitignore file
9. Create a new file `foo.js`
10. Select "clean all" from the Changes section of the Git tab
11. Confirm the dialog

Expected:
- `foo.js` is removed
- `.vscode/launch.json` still exists

Actual:
- `foo.js` is removed
- `.vscode/launch.json` is removed

This is super annoying, because my launch.json contains secret values in the environment settings, so I can't check it in.

**Comment by joaomoreno** [comment]
Unfortunately that is just how git operates. We use the `clean -d` command to undo, which pays attention to the `.gitignore` file. Problems happen with folders though, especially when they are not listed in that file.

This is how it behaves:

```
bug → git init
Initialized empty Git repository in /Users/joao/Desktop/bug/.git/
bug master* → mkdir foo
bug master* → touch foo/bar
bug master* → echo 'foo/bar' > .gitignore
bug master* → git add .gitignore && git commit -m 'ignore'
[master (root-commit) 7c6f493] ignore
 1 file changed, 1 insertion(+)
 create mode 100644 .gitignore
bug master → git clean -di
Would remove the following item:
  foo/
*** Commands ***
    1: clean                2: filter by pattern    3: select by numbers    4: ask each             5: quit
    6: help
What now> q
Bye.
```

On the other hand, if the `foo` folder is listed in `.gitignore`, everything behaves:

```
bug master* → echo 'foo' > .gitignore
bug master* → git clean -di
```

So I suggest to ignore the full `.vscode` folder in the `.gitignore` file.

PS: Hey there! 👋

**Comment by xirzec** [comment]
Hm why do `clean -d` instead of a bare `clean`? Since folders don't show up in the git widget, I don't think it's obvious that they are removed when performing a Clean All action.

I realize it's a silly edge case because 99% of the time you'd see the untracked files *inside* of the untracked directory, but I can imagine other scenarios where this could create unexpected behavior, such as an output directory that is expected to exist, but contains only file types that are ignored. This is the first time in many years that the git widget did something different than what I would have done with manual commands, so it's a weird feeling.

PS: It's been a while :wave:

**Comment by joaomoreno** [comment]
You make a good point there... I was just hardcoded into thinking the directories must go too. Let's remove `-d` and see how it goes.

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
