### ISSUE TITLE
Test: extensions can provide label for custom file based editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111421]
Refs: https://github.com/microsoft/vscode/issues/110738

- [x] anyOS @mjbvz
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111421%0A%0A)

---

With your own custom filesystem provider from an extension (e.g. https://github.com/microsoft/vscode-extension-samples/tree/master/fsprovider-sample), execute the `vscode.open` command on one of your custom files and pass in `label` as last argument. This label should appear in the tab of the editor. If you do the same with a normal file, the label should not be yours (we do not allow to override the label for native schemes provided from us).

**Comment by dbaeumer** [comment]
Works as advertised :-)
