### ISSUE TITLE
Test: Should allow adjusting font weight

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11143]
Test for #381 (came in via PR #10515)

- [x] Any OS **dbaeumer**

Complexity 1

Adds two new settings `editor.fontWeight` and `terminal.integrated.fontWeight`. If `terminal.integrated.fontWeight` is missing, `editor.fontWeight` will be picked up by the terminal.

Please check that you can change the editor's and the terminal's font weight.

**Comment by Tyriar** [comment]
@alexandrudima please let me know when adding to `terminal.integrated`, first I heard of it was a bug that was filed https://github.com/Microsoft/vscode/issues/11198

**Comment by Tyriar** [comment]
I'm actually not particularly for this in the terminal. This would override the ANSI bold values which communicate/highlight information.

**Comment by alexandrudima** [comment]
@Tyriar It came in via PR #10515 (I wrote above in the description). I was surprised that it adds the terminal option as well, but then I noticed the terminal has all the other font-related settings from the editor and thought it was a good change. We can definitely remove the `terminal.integrated.fontWeight` and its influence in the integrated terminal.
