### ISSUE TITLE
vscode.workspaces[0].uri.path on windows returns a path with a forward slash in the beginning

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#111440]
`vscode.workspaces[0].uri.path` on windows is returning a path with a forward slash in the beginning, but this is not a valid path. Could you remove it if node is running on Windows?

![image](https://user-images.githubusercontent.com/55927613/100515992-7abd6080-3178-11eb-8976-70aacf30773c.png)

If it can't be removed is there a probem if I use the private prop `_fsPath` ? I'm asking it because that one is right.

- VSCode Version: 1.46.0 this is the package version I'm currently using
- OS Version: Windows 10

Steps to Reproduce:

1. Just call `vscode.workspaces[0].uri.path` on Windows

Does this issue occur when all extensions are disabled?: NA

**Comment by AllanOricil** [comment]
I solved my problem using the getter `fsPath`. But I would like to understand when I should use the `path` attribute.

**Comment by GustavoASC** [comment]
I had this same problem and solved it using fsPath as you said. I am also confused about when one should use path instead of fsPath...

**Comment by jrieken** [comment]
The `path`-component of uris always uses forward slashes, when accessing the file system you can use `fsPath` (which takes UNC paths into account). However, it is advised to use `vscode.workspace.fs` to read/write files because that can be used in other contexts as well

**Comment by AllanOricil** [comment]
@GustavoASC I found tests to help us understand how to use vscode.workspace.fs https://github.com/microsoft/vscode/blob/master/extensions/vscode-api-tests/src/singlefolder-tests/workspace.fs.test.ts
