### ISSUE TITLE
Test: proposed API for status item background color

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111423]
Refs: https://github.com/microsoft/vscode/issues/110214

- [x] anyOS @sbatten
- [x] anyOS @dbaeumer

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111423%0A%0A)

---

[Release Notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_52.md#statusbar-entry-background-color-api)

Write a simple extension with proposed API enabled and create a status bar entry with `backgroundColor` applied. Refer to the JSDoc comment to see which color is supported (currently only error). If you are using an invalid color, no background color should be applied.

**Note:** Use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`.

**Comment by sbatten** [comment]
not sure what I am doing wrong here. I'm simply adding a single line to the status bar sample along with getting the proposed api setup. 

```
	myStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
	myStatusBarItem.command = myCommandId;
	myStatusBarItem.backgroundColor = 'statusBarItem.errorBackground';
	subscriptions.push(myStatusBarItem);
```

I don't see any effect. The status bar entry does show so it is activating.

**Comment by sbatten** [comment]
Ah, its because I use a string literal, that should work right?

**Comment by bpasero** [comment]
No, it has to be `ThemeIcon`.
