### ISSUE TITLE
IDE doesn't send DAP 'setDataBreakpoints' request

### ISSUE THREAD

**Issue by awto** [microsoft/vscode#111426]
- VSCode Version: 1.51.1
- OS Version: OSX, Windows

Steps to Reproduce:

1. Run the official [vscode-mock-debug](https://github.com/microsoft/vscode-mock-debug.git) sample
2. Try to set a data breakpoint to any global variable (Right Click + "Break When Value Changes")

As a result no breakpoints are created, and the last messages in the log (with `"trace":true` in launch.conf) are:

```
From client: dataBreakpointInfo({"name":"global_f","variablesReference":1001})
To client: {"seq":0,"type":"response","request_seq":17,"command":"dataBreakpointInfo","success":true,"body":{"dataId":"global_f","description":"global_f","accessTypes":["read"],"canPersist":true}}
```

So `dataBreakpointInfo` is sent and succeed, but the IDE doesn't send `setDataBreakpoints`  after. This worked well in earlier versions.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
This has been fixed in Insiders.
