### ISSUE TITLE
file not displayed

### ISSUE THREAD

**Issue by madhushubhi** [microsoft/vscode#111431]
Issue Type: <b>Feature Request</b>

i m getting the issue in opening the sound file in vs code .the issue is 
file is not displayed  in editor because either binary or uses an unsupported text encoding

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by egamma** [comment]
/needsMoreInfo what is the behaviour you are expecting? What is the file type you are trying to open? Have you searched for an extension that supports this file type?
