### ISSUE TITLE
"Search -> Files to include" is erroneously case-sensitive

### ISSUE THREAD

**Issue by sandersaares** [microsoft/vscode#111438]
Issue Type: <b>Bug</b>

1. Use the Search sidebar to search within workspace files.
2. In "files to include" specify a pattern that should produce a result.
3. Observe expected result.
4. Now change the case of one of the letters in "files to include"
5. Observe that the match disappears from results.

Expected behavior: file filtering is case-insensitive (at least on Windows, and really, I would probably desire it everywhere)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.71GB (103.45GB free)|
|Process Argv|C:\Source\xxxxxxxxxxx --crash-reporter-id 5cdcf844-6784-433b-9f08-acce045cca1d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
markdown-table-formatter|fcr|2.1.3
plantuml|jeb|2.13.16
vscode-dotnet-runtime|ms-|0.2.0
remote-wsl|ms-|0.51.4
powershell|ms-|2020.6.0
azurerm-vscode-tools|msa|0.14.0
cmake|twx|0.0.17

</details>

**Comment by JacksonKearl** [comment]
@roblourens Not sure if we want this to be case insensitive, but ripgrep does support `--iglob` instead of `-g`, to be used here https://github.com/microsoft/vscode/blob/5afc5cd1601dced3413ffa9a420daa12c80a30aa/src%2Fvs%2Fworkbench%2Fservices%2Fsearch%2Fnode%2FripgrepTextSearchEngine.ts#L390.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/10633
