### ISSUE TITLE
Test: Option to wrap at specified column only when window is larger than the specified number of columns

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11141]
Test for #1490 (came in via PR #7029)

- [x] Any OS **gregvanl**

Complexity 1

There is a new setting `editor.wordWrap` that interacts with `editor.wrappingColumn`:

| wrappingColumn  | wordWrap | Effect                                                                                                      | New? |
| --------------------------- | ----------------------------- | ------------------------------------------------------------------------------------- | -------- |
| 0                                  | false                              | Viewport Wrapping.                                                                         | No |
| -1                                 | false                              | No Wrapping.                                                                                     | No |
| 80                                | false                              | Wraps at 80 columns.                                                                    | No |
| 0                                   | true                               | Viewport Wrapping.                                                                        | No |
| -1                                  | true                               | No Wrapping.                                                                                    | No |
| 80                                | true                                | If viewport > 80 cols Wrap at 80 columns; else Viewport Wrapping. | Yes |

Please check that `editor.wrappingColumn` works as before when `editor.wordWrap` is false.
Please check that if `editor.wrappingColumn > 0` and `editor.wordWrap` is true, the view wraps at `min(editor.wrappingColumn, viewportColumnWidth)`.

**Comment by gregvanl** [comment]
> tyriar
