### ISSUE TITLE
Write integration test for new option bag in `TextEditor.test`

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11145]
This is so we don't need to manually test #8096

**Comment by rebornix** [comment]
Currently we are implementing the undo feature from scratch ourselves so it's a big move to leverage this new `edit` command instead. So for this sprint, this feature can not be tested as it requires a rewrite of the undo feature of VSCode Vim. I'll write a prototype which leverages this API to do `undo`.
