### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#111492]
- [x] Windows @meganrogge
- [x] macOS @isidorn
- [x] Linux @jrieken 
- [x] web @isidorn 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111492%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by isidorn** [comment]
Looks good. I made sure to run the smoke test with new Electron 9 builds
@lszomoru nobody is assigned to the web smoketest. If you would like I can also run that one.

![Screenshot 2020-12-01 at 11 11 45](https://user-images.githubusercontent.com/1926584/100727054-08da5680-33c6-11eb-8612-1d3bb8424532.png)

**Comment by lszomoru** [comment]
@isidorn, yes please. Thank you!

**Comment by isidorn** [comment]
Web looks good.

![Screenshot 2020-12-01 at 12 25 57](https://user-images.githubusercontent.com/1926584/100734727-62478300-33d0-11eb-8166-4ab6683d27d0.png)

**Comment by lszomoru** [comment]
Awesome! Thank you @isidorn!
