### ISSUE TITLE
[FR] Type definition display @ statusbar on cursor touch

### ISSUE THREAD

**Issue by kiprasmel** [microsoft/vscode#111424]
(Doom) emacs has this feature where once your cursor (not the mouse pointer, but the cursor) touches some sort of variable - it shows that variable's type in the statusbar -- see a quick demo:

https://youtu.be/AGW45CnnYvo

(I'm not pressing any additional keys - I'm just putting my cursor on top of the variable and emacs does the rest)

I wanted to implement something like this myself in vscode - probably with an extension. I've dug through both the docs and source code of vscode, and it seems like this would be very similar to `TypeScriptHoverProvider`, the difference being that instead of a hover popup on mouse hover, there'd be a statusbar item on cursor touch.

https://github.com/microsoft/vscode/blob/01bbb81052086edf3398e599f218e189c44b0658/extensions/typescript-language-features/src/languageFeatures/hover.ts#L16-L17

The upcoming issues I foresee are:

1. Indicated in the `IStatusBarEntry` type definition -- I'm pretty sure it can only display text - not markdown / other way to colorize the type definition like emacs does:

https://github.com/microsoft/vscode/blob/01bbb81052086edf3398e599f218e189c44b0658/src/vs/workbench/services/statusbar/common/statusbar.ts#L22-L29

2. The type definition may not fit into the statusbar. How emacs does it - they actually display the type definition either bellow or above the statusbar, and it can expand up to some amount of lines if there's a deeper definition / object with multiple properties etc.

How likely would it be for the vscode team to implement this (described in `2.`) additional [view container](https://code.visualstudio.com/api/extension-capabilities/extending-workbench#views-container) so that one could use it to create i.e. the feature I described?

This is probably the underlying feature request of the original one - feel free to change the title of the issue if it makes more sense.

Sadly, I feel like this will be out of scope. If so - is there anything else I can do? Thanks.

**Comment by mjbvz** [comment]
This should already be possible using an extension. See https://marketplace.visualstudio.com/items?itemName=bierner.docs-view as an example

No plans to allow the status bar to be expanded to multiple lines

**Comment by kiprasmel** [comment]
Oh yeah that's what I was looking for -- thanks Matt!

I was just wondering if there's any way to detach the panel somehow so that one can toggle between e.g. their terminal efficiently and probably with bigger size, while still having the documentation panel available.

It works if you put it to one place and e.g. terminal to the other, but I'd prefer to have them both at the bottom. I guess not for now.

Thanks anyway:)
