### ISSUE TITLE
Test Scrolling and Folding API commands within VSCodeVim

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11147]
As VSCodeVim is doing differently as Vim example, I'd like to test against latest VSCode Vim bits as well, all test scenarios are the same as #11127. The only difference is the setup steps

- [x] any OS **@alexandrudiam**

* Clone the repository [VSCodeVim](https://github.com/VSCodeVim/Vim)
* Install dependencies by following https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md#first-time-setup
* Open VS Code on VSCodeVim
* Run the extension using Launch Extension.

Complexity 4 as well.

**Comment by alexandrudima** [comment]
Basically it appears to me that out of that list the following work correctly:
* `z` + `z`
* `z` + `c` (without counts)
* `z` + `o` (without counts)
