### ISSUE TITLE
VS code is not showing the attribute list as a dropdown (multiple itens)

### ISSUE THREAD

**Issue by gabrielibernardi** [microsoft/vscode#111414]
Issue Type: <b>Bug</b>

When typing an HTML tag VS code won't show the attribute list as a dropdown (multiple itens). It only show one item of the list.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz (4 x 1700)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|9, 14, 7|
|Memory (System)|4.00GB (0.45GB free)|
|Process Argv|--crash-reporter-id 39209e1c-9af8-4c20-afb5-dece1c3198c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
LiveServer|rit|5.6.1

![Captura de Tela 2020-11-27 às 10 35 01 (2)](https://user-images.githubusercontent.com/74473908/100454735-470d0880-309c-11eb-8ad2-08fa89d45af6.png)

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Could you please provide screenshot with problem?
Can you resize suggestion box (if this is dropdown that you are talking about)?

**Comment by gabrielibernardi** [comment]
> /needsMoreInfo
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> 
> Could you please provide screenshot with problem?
> Is it possible to resize suggestion box (if this is dropdown that you are talking about)?

It was just to resize! Thank you
I had already desistalled all the extensions.

**Comment by Inori-Lover** [comment]
> > /needsMoreInfo
> > Is it reproducible with all extensions disabled?
> > You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> > Could you please provide screenshot with problem?
> > Is it possible to resize suggestion box (if this is dropdown that you are talking about)?
> 
> It was just to resize! Thank you
> I had already desistalled all the extensions.

i also meet this issue. it can reproducible even all extensions disabled

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by gabrielibernardi** [comment]
Resolved
