### ISSUE TITLE
[Bug] After 1.52.0-insider, cannot input Chinese in the terminal

### ISSUE THREAD

**Issue by ddzy** [microsoft/vscode#111453]
Issue Type: <b>Bug</b>

**After updated VS Code 1.52.0-insider, cannot input Chinese in the terminal.**

VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:36:22.965Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.69GB free)|
|Process Argv|--crash-reporter-id df459147-fe5d-44a6-8af9-17ed34ccf1b1|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|12.0.0
markdown-preview-github-styles|bie|0.1.6
file-positioning|ddz|1.0.4
vscode-great-icons|emm|2.1.61
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
comment-translate|int|1.4.2
vscode-language-pack-zh-hans|MS-|1.51.2
azure-account|ms-|0.9.4
vetur|oct|0.30.3
java|red|0.71.0
language-stylus|sys|1.11.0
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
Also, please try disabling all extensions and let me know if it persists.
/label "needs more info" integrated-terminal
