### ISSUE TITLE
Running `code file.ext` from the command line, then saving, prompts that this file already exists

### ISSUE THREAD

**Issue by AndersenTobias** [microsoft/vscode#111469]
Issue Type: <b>Bug</b>

1. Change directory to your favorite/arbitrary directory, `cd /some/dir`.
2. Open this directory in VS Code via `code .`
3. Change directory to somewhere else completely.
4. Run `code some_file.txt` from the command line. (Assumption: File does not already exist.)
5. Save the file.

We get a prompt that says that this file already exists.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|. --crash-reporter-id 1710ea2b-7fcf-4d53-9484-6535956bb330|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by egamma** [comment]
I cannot reproduce this given the steps provided. Can you reproduce this with extensions disabled? By running `code --user-data-dir`(then you run with fresh settings)? By using code-insiders?

**Comment by AndersenTobias** [comment]
@egamma I've tried several times to invoke the same behavior but cannot reproduce it myself. Sorry!
