### ISSUE TITLE
"Toggle Editor Type" creates corrupted new view that cannot be opened

### ISSUE THREAD

**Issue by JannisX11** [microsoft/vscode#111474]
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file in a custom editor (I tested with third party extensions and with the "PawDraw" and "CatScratch" extension samples)
2. Run "View: Toggle editor type" from the command palette
3. Try and switch between the new and old tab

The command will create a new tab, even though it should replace the original tab, and the new tab cannot be selected properly.

Does this issue occur when all extensions are disabled?: No, the issue applies to functionality that is only exposed by custom editors.

**Comment by mjbvz** [comment]
@rebornix I also see this happening for notebooks.

@rebornix and @bpasero  For custom editors, I used to have logic that replaced the existing editors with the newly opened one:

https://github.com/microsoft/vscode/blob/f0bb23ca02f320816219017234e412caa425851e/src%2Fvs%2Fworkbench%2Fcontrib%2FcustomEditor%2Fbrowser%2FcustomEditors.ts#L280

This code path is no longer hit in our shared `open with` command. Should I look into making this behavior part of openWith / the reopenWith command?

**Comment by bpasero** [comment]
I would find it easier to argue/test this in a PR maybe.
