### ISSUE TITLE
Test: improved editor "preview" behaviour

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111417]
Refs: https://github.com/microsoft/vscode/issues/109779 https://github.com/microsoft/vscode/issues/85636

- [x] anyOS @alexdima
- [x] anyOS @eamodio

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111417%0A%0A)

---

[Release Notes](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_52.md#better-handling-of-preview-editors)

Preview editors are enabled by default e.g. when you just click on a file from the explorer and appear with italic font. The idea of preview editors is that the next editor replaces the previous preview editor so that you don't accumulate tabs. An editor turns into a non-preview editor based on many conditions (e.g. making it dirty). In this milestone we tweaked this functionality to put an editor into non-preview mode right from the beginning or guide the user how to change the settings.

**Note:** if you have preview editors typically disabled, please enable them for testing.

**Verify:**
* `workbench.editor.enablePreviewFromQuickOpen` is `false` by default
* `workbench.editor.enablePreview` appears in "Commonly Used" section of settings editor and is easy to understand
* you find a action in the top right "..." editor overflow menu to always keep editors and this turns off editor preview
* when you trigger "Goto definition" and that brings you to another file, the editor you start from gets out of preview automatically

**Comment by eamodio** [comment]
While this is outside the scope of this, when I went looking for the `workbench.editor.enablePreview` setting in the _Commonly Used_ section it took me a bit to find it at first because for I wasn't looking for the "Workbench" part.

![image](https://user-images.githubusercontent.com/641685/100790186-70ec6500-33e5-11eb-8b53-21cb509e4c2b.png)

**Comment by eamodio** [comment]
All looks good to me!
