### ISSUE TITLE
Three dots appearing and disappearing in Editor annoying

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode#111472]
Version: 1.52.0-insider (user setup)
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:36:22.965Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.19042Steps to Reproduce:

1. Install C/C++ for Visual Studio Code 1.1.2
2. Create an hpp file
3. Hit Enter on some line. After 2 seconds three dots appear on some empty lines and disappear after 2 seconds.
   Please see my screenshot.

![dotsProblem](https://user-images.githubusercontent.com/4497675/100552063-11774380-3285-11eb-886d-fe704d81bd66.jpg)

The dots are marked with a red circle. It is very hard to work with the file when lines keep on popping up and disappearing all the time.
Is there a way to get rid of these dots?

**Comment by egamma** [comment]
Please report the issue against the C++ extension.

**Comment by DaveRainbowin** [comment]
i have a similar problem but instead the dots are in between every newline in my markdown files and at the start of every file i open

**Comment by ankitjain-1** [comment]
> Version: 1.52.0-insider (user setup)
> Commit: [0a80aac](https://github.com/microsoft/vscode/commit/0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d)
> Date: 2020-11-26T07:36:22.965Z
> Electron: 11.0.2
> Chrome: 87.0.4280.63
> Node.js: 12.18.3
> V8: 8.7.220.24-electron.0
> OS: Windows_NT x64 10.0.19042Steps to Reproduce:
> 
>     1. Install C/C++ for Visual Studio Code 1.1.2
> 
>     2. Create an hpp file
> 
>     3. Hit Enter on some line. After 2 seconds three dots appear on some empty lines and disappear after 2 seconds.
>        Please see my screenshot.
> 
> 
> ![dotsProblem](https://user-images.githubusercontent.com/4497675/100552063-11774380-3285-11eb-886d-fe704d81bd66.jpg)
> 
> The dots are marked with a red circle. It is very hard to work with the file when lines keep on popping up and disappearing all the time.
> Is there a way to get rid of these dots?

This is happening because of GitLens extension in my case, if you have installed it, try uninstalling it and check if you are still having this issue.

**Comment by ankitjain-1** [comment]
This is happening because of GitLens extension in my case, if you have installed it, try uninstalling it and check if you are still having this issue.

**Comment by DaveRainbowin** [comment]
you don't need to uninstall, you can disable some part of the extension

**Comment by ankitjain-1** [comment]
How will I know which part of the extension is creating issue?
and how can I disable some part of an extension.
