### ISSUE TITLE
Process explorer accesibility

### ISSUE THREAD

**Issue by MakiWolf** [microsoft/vscode#111498]
![grafik](https://user-images.githubusercontent.com/73300633/100597485-cfd6af00-32fd-11eb-9ef4-b2a56880dd42.png)
![grafik](https://user-images.githubusercontent.com/73300633/100597552-e250e880-32fd-11eb-92a2-19ebff16341b.png)
Process explorer is not accesibility with the keyboard. It would be great when it also is accesibility with the keyboard and not only with the computer mouse.

**Comment by RMacfarlane** [comment]
Closing this issue in favor of https://github.com/microsoft/vscode/issues/121851
