### ISSUE TITLE
Syncronize failed

### ISSUE THREAD

**Issue by thadjbullet** [microsoft/vscode#111478]
Issue Type: <b>Bug</b>

Just install several extensions in a row - sync failed. Expected - sync works fine.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (13.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (77)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
output-colorizer|IBM|0.1.2
better-comments|aar|2.1.0
Bookmarks|ale|12.0.0
atlascode|atl|2.8.5
vscode-custom-css|be5|4.0.1
vscode-toggle-quotes|Bri|0.3.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
vscode-eslint|dba|2.1.13
vscode-dash|dee|2.4.0
vscode-docker-syntax|dun|0.1.5
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.3
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
vscode-open-in-finder|fab|1.1.8
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
github-actions|for|0.0.1
vscode-pull-request-github|Git|0.21.2
gitlab-workflow|Git|3.6.2
go|gol|0.19.0
todo-tree|Gru|0.0.188
debug-visualizer|hed|2.0.6
vscode-trello-viewer|Ho-|0.6.0
openvpn|idl|0.2.2
pubspec-assist|jer|2.2.1
vscode-peacock|joh|3.8.0
vscode-styled-components|jpo|1.3.0
auto-comment-blocks|kev|1.0.1
kite|kit|0.135.0
vscode-github|Kni|0.30.4
vscode-github-actions|me-|3.0.1
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.8.1
vscode-language-pack-ru|MS-|1.51.2
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.372831992
remote-containers|ms-|0.148.1
remote-wsl|ms-|0.51.4
vscode-github-issue-notebooks|ms-|0.0.58
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3206
debugger-for-chrome|msj|4.12.11
docker-compose|p1c|0.3.5
colorful-comments|Par|0.6.0
polacode|pnp|0.3.4
bitbucket-pull-requests|Ram|0.3.10
vscode-yaml|red|0.13.0
vscode-sort-json|ric|1.18.1
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
music-time|sof|2.0.23
swdc-vscode|sof|2.3.21
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
language-stylus|sys|1.11.0
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vim|vsc|1.17.1
babelrc|wad|1.0.0
jinja|who|0.0.8
bracket-lens|wra|1.4.2
vscode-surround|yat|1.0.2
propertylist|zho|0.0.2
material-theme|zhu|3.9.11

(3 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please elaborate what failed? If you got any errors? Can you please open Settings Sync Log in Output view in the bottom and let me know if there are any errors in the log?

**Comment by thadjbullet** [comment]
> Can you please elaborate what failed? If you got any errors? Can you please open Settings Sync Log in Output view in the bottom and let me know if there are any errors in the log?

It shows error "request limit exceeded"

**Comment by sandy081** [comment]
/duplicate

#91286
