### ISSUE TITLE
minimap and editor code are not in sync.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#111499]
Issue Type: <b>Bug</b>

steps to reproduce:
1. create a long typescript file with codelens enabled.  
2. try to scroll using the minimap

observed output:
the minimap focus area and the text shown in the editor do not match.
the mismatch grows rapidly when you have a large file.

expected output:
minimap selection should match properly with the editor visible text.

VS Code version: Code - Insiders 1.52.0-insider (f47aae014cf8567f648e68369d66b4106ae89f08, 2020-11-30T06:08:34.438Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.1
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
output-colorizer|IBM|0.1.2
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-next|ms-|4.2.20201128
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vscode-jest|Ort|3.2.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
sonarlint-vscode|Son|1.18.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.85.0
vscodeintellicode|Vis|1.2.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244cf:30226748
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by alexdima** [comment]
@sanket-bhalerao What are your `editor.minimap.*` settings?

**Comment by alexdima** [comment]
I could reproduce with using `"editor.minimap.size": "fill"`. The root problem here is that the slider height is constant sized in this case, while the viewport contains a variable amount of lines, based on the number of visible codelenses.

**Comment by sanket-bhalerao** [comment]
@alexdima minimap settings

 ```
"editor.minimap.enabled": true,
  "editor.minimap.maxColumn": 50,
  "editor.minimap.size": "proportional",
  "editor.minimap.showSlider": "always",
```
for the minimap size option I have already tried 'fit' and 'fill' option, however, the results are the same.
i noticed these changes after yesterdays update, prior to that minimap was working as expected.

**Comment by sanket-bhalerao** [comment]
> I could reproduce with using `"editor.minimap.size": "fill"`. The root problem here is that the slider height is constant sized in this case, while the viewport contains a variable amount of lines, based on the number of visible codelenses.

I'm able to observe the issue with ```"editor.minimap.size": "proportional",``` option as well.

**Comment by alexdima** [comment]
:+1: I could also reproduce even with `proportional`. 

Settings:
```
"editor.codeLens": true,
"typescript.referencesCodeLens.enabled": true,
"editor.minimap.showSlider": "always",
```

Open `charCode.ts`:
![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/101087389-6fbc6300-35b2-11eb-9639-b5334b619b86.gif)
