### ISSUE TITLE
Overly faded font in text editor in Arch distro

### ISSUE THREAD

**Issue by YVEF** [microsoft/vscode#111460]
- VSCode Version: 1.51
- OS Version: Linux 5.4.79
- Distro: Arch
- Theme: Dark+ (Default dark)

Does this issue occur when all extensions are disabled?: Yes

The issue is reproducible with any theme.
I tested insider version and the fort problem is the same.

![Screenshot from 2020-11-29 12-42-38](https://user-images.githubusercontent.com/44643054/100539912-6776c780-3242-11eb-945c-40e8409f30c6.png)

**Comment by deepak1556** [comment]
Can you check if launching with `--force-device-scale-factor=1` fixes the issue ?

**Comment by YVEF** [comment]
Nope. Nothing changed.
Just to clarify on Windows I have more bright and thick fonts.

**Comment by deepak1556** [comment]
Can you also check with `--force-color-profile srgb`

**Comment by YVEF** [comment]
Nothing:)

**Comment by deepak1556** [comment]
Can you test with our exploration build that has a newer runtime https://az764295.vo.msecnd.net/exploration/a31f124319d43aef2e9d8b875015d11a53c6f541/code-exploration-x64-1606458313.tar.gz

**Comment by YVEF** [comment]
Hi again.
I just prepare some examples of VSCode font rendering on Windows and Arch.
![win2](https://user-images.githubusercontent.com/44643054/103032577-0e603200-4569-11eb-962c-4225c36c8517.png)
![arch2](https://user-images.githubusercontent.com/44643054/103032588-16b86d00-4569-11eb-87f6-dee8c15f8929.png)

on windows it looks more bright.
Btw, I used provided exploration build of vscode.

**Comment by YVEF** [comment]
Btw, I noticed, if I zoom+ windows using "window.zoomLevel", on some step there are no differences between Win and Arch.
