### ISSUE TITLE
Test extension bisect

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111495]
Refs: https://github.com/microsoft/vscode/issues/109841

- [x] anyOS @JacksonKearl
- [x] anyOS @meganrogge

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111495%0A%0A)

---

There is a new extension bisect feature which allows to identify an extension causing an issue/annoyance 

* use the attached extension [fresh-0.0.1.vsix.zip](https://github.com/microsoft/vscode/files/5615250/fresh-0.0.1.vsix.zip) or another extension that you are having trouble with
* start extension bisect via F1 > Start Extension Bisect and follow the flow
* make sure that each step is easy to follow and understand
* make sure you can always early exist bisect
* make sure that the bad extension is identified and that the issue reporter comes up

**Comment by JacksonKearl** [comment]
Neat trick! Only a couple polish items, then a bigger question of it being potentially cool to generate a list of extensions rather than a single one.

**Comment by meganrogge** [comment]
Really nice idea and execution. I agree with Jackson that the wording could be improved and that multiple extensions could be causing issues for a user.
