### ISSUE TITLE
Snippet not showing for local extension

### ISSUE THREAD

**Issue by zyllus17** [microsoft/vscode#111456]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
 I am trying to create a snippet extension, I have added the snippet in the json but IntelliSense doesn't shows me the snippet for testing them. 

![flutter-snippets-1606632005163](https://user-images.githubusercontent.com/50977126/100535413-ac006400-323e-11eb-943a-18e4418d4457.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by egamma** [comment]
@zyllus17 Please share a repository with the code in source form so that we can try to reproduce the problem.

**Comment by zyllus17** [comment]
@egamma Here is the project repo https://github.com/zyllus17/flutter-snippets

**Comment by jrieken** [comment]
Your steps, esp the changes in package.json, are for add snippets to an extension. E.g snippets that are available after installing that extension, not while authoring that extension. 

Are you authoring an extension or just want to consume a snippet?

**Comment by zyllus17** [comment]
@jrieken I am authoring an extension. I wanted to create a snippet extension for Flutter, something like the [Flutter Widgets Snippets](https://marketplace.visualstudio.com/items?itemName=alexisvt.flutter-snippets). I read the documentation on VSCode and watched some videos and created a snippet and wanted to test the snippet if its working or not, but I didn't get any result as you can see in the gif above.

**Comment by jrieken** [comment]
You need to run (or bundle and install) you extension for the package.json information to be picked up

**Comment by zyllus17** [comment]
> You need to run (or bundle and install) your extension for the package.json information to be picked up

Do I need to bundle it everytime I add a new snippet, if I add 10 snippets one by one, do I need to bundle it ten times to test if its working or not?

Also for testing I added it to ```.vscode/extensions```, do I need to update the ```snippet.json``` file each time there as well to test it?

**Comment by jrieken** [comment]
> Do I need to bundle it everytime I add a new snippet, if I add 10 snippets one by one, do I need to bundle it ten times to test if its working or not?

You need to bundle (re-publish) your extension whenever you are making a change to it

**Comment by zyllus17** [comment]
> > Do I need to bundle it everytime I add a new snippet, if I add 10 snippets one by one, do I need to bundle it ten times to test if its working or not?
> 
> You need to bundle (re-publish) your extension whenever you are making a change to it

That is for everyone on VSCode to use it, but while authoring it and testing if it works properly or not, do I need to bundle it as well?

**Comment by jrieken** [comment]
No, when developing you need run/debug your extension
