### ISSUE TITLE
VS Code sync settings merge conflict between Windows and Linux

### ISSUE THREAD

**Issue by harshlavingia** [microsoft/vscode#111482]
Issue Type: <b>Feature Request</b>

Currently, VS code supports sign in to Microsoft account and sync all the setting. Now I am using VS Code in Windows and Linux and once I sign in to both account, it creates merge conflict in setting file. Please improve and make it easier for developer. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sandy081** [comment]
Merge conflict is shown because your windows and linux machines have different values for some of the settings which cant merge automatically. In this case you have to merge manually and continue sync.

May I know what improvements you are thinking of?

**Comment by harshlavingia** [comment]
Since windows and linux machines have different values, during the sync, it should maintain separate setting files that allow me to sync Windows VS code version and Linux VS Code version seperately.

**Comment by sandy081** [comment]
/duplicate

Ok, seems you need platform specific settings - https://github.com/microsoft/vscode/issues/5595
