### ISSUE TITLE
Redo action is not working

### ISSUE THREAD

**Issue by cicerolourenco** [microsoft/vscode#111418]
Edit >> Redo is not working as well as keyboard shortcut CTRL + Y

**Comment by SturmB** [comment]
I'm experiencing the exact same problem.

Furthermore, each undo requires _two_ presses of the shortcut (<kbd>CTRL</kbd>-<kbd>Z</kbd>, <kbd>CTRL</kbd>-<kbd>Z</kbd>) or _two_ executions of the menu item (Edit -> Undo) in order for the action to be performed.

Version Info:
---
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Screencast: https://www.dropbox.com/s/wcrmxb5uffcupqk/KAteSYHOLd.mp4?dl=0

**Comment by SturmB** [comment]
For what it's worth, the problem seems to have disappeared for me. I don't recall when or on what version of VS Code, but I think it was within days of my previous post.

**Comment by egamma** [comment]
@SturmB thanks for the update. Closing the issue, please reopen when the problem shows up again.
