### ISSUE TITLE
Git Bash Terminal Slash issue

### ISSUE THREAD

**Issue by retro-future** [microsoft/vscode#111457]
Issue Type: <b>Bug</b>

git bash terminal can't handle path with one slashes like C:\Users\<username>\............it makes problem when automatically installing extensions because terminal couldn't access to python interpreter,  when automatically installing extensions i got an error : "No such file or directory",  so for every plugin i have to add 1 more slashes manually like "C:\\Users\\<username>\..... then it works 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042
![Capture](https://user-images.githubusercontent.com/53857715/100537010-98f19200-3246-11eb-97ab-3929e2031af2.PNG)
`

**Comment by retro-future** [comment]
sorry for my english but please do not refer me to another closed issue...I need solution here thanks

**Comment by meganrogge** [comment]
have you tried [this]( https://github.com/microsoft/vscode/issues/70050#issuecomment-475964508)?

**Comment by retro-future** [comment]
No it doesn't work so many settings I have to configure to start using vscode((

**Comment by retro-future** [comment]
> have you tried [this](https://github.com/microsoft/vscode/issues/70050#issuecomment-475964508)?

I don't understand how to configure this

**Comment by akib35** [comment]
I need this too..

**Comment by akib35** [comment]
I need this too..
