### ISSUE TITLE
please don't replace opened file!

### ISSUE THREAD

**Issue by keyiis** [Microsoft/vscode#11155]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.when i open new file in vscode,it always replace opened file.
2.it's very damnabl!i must modify opened file(insert space) then open a new file.

has some config can close the issues or is bug?

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by keyiis** [comment]
@bpasero Hi! how to format css file in vscode?

**Comment by bpasero** [comment]
@aeschli do you know the answer?

**Comment by aeschli** [comment]
@bpasero Glad you ask. There are several extension, amongst them the amazing https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter

**Comment by mrmlnc** [comment]
@keyiis, or https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt :panda_face:
