### ISSUE TITLE
cmd.exe

### ISSUE THREAD

**Issue by dhanashrisakharkar** [microsoft/vscode#111516]
Issue Type: <b>Bug</b>

The terminal process failed to launch: Path to shell executable "cmd.exe" does not exist.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|2.91GB (0.96GB free)|
|Process Argv|--crash-reporter-id e17185af-146f-46e8-9c44-b306f3752250|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error?

**Comment by dhanashrisakharkar** [comment]
[image: image.png]

**Comment by joaomoreno** [comment]
Can you send me the screenshot in GitHub, instead of via e-mail.
