### ISSUE TITLE
Test: experiment info in issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#111533]
Refs: https://github.com/microsoft/vscode-internalbacklog/issues/1607

- [x] anyOS @egamma
- [x] anyOS @lszomoru

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111533%0A%0A)

---

The issue reporter now sends information about what A/B experiments a user is in. There is a new "Include A/B experiment info" button at the bottom of the reporter. Toggling this on and off should change whether this gets included in the markdown of the new issue. Currently the experiment flight information is not human-readable, so it's expected that the list will show strings with numbers. The information should not be sent for feature requests, but should be sent for bugs and performance issues.

**Comment by egamma** [comment]
Worked well.

**Comment by lszomoru** [comment]
Works as advertised 👍🏻
