### ISSUE TITLE
focus stolen from git commit input box

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111507]
Version: 1.52.0-insider
Commit: f47aae014cf8567f648e68369d66b4106ae89f08
Date: 2020-11-30T05:43:45.625Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Linux x64 5.3.0-64-generic

- have some changes in the git view
- enter a commit message
- select a changed element, diff editor shows
- double click on a word in the commit message
- the focus on the  git commit input box is stolen and goes to the diff editor
![git-focus-lost](https://user-images.githubusercontent.com/6461412/100618925-bf81fc80-331c-11eb-98c8-17d46c7e438d.gif)

**Comment by joaomoreno** [comment]
#111496

Makes me think it's something new? Can't be a coincidence that both @weinand and @aeschli saw it within 1 hour of each other?

**Comment by weinand** [comment]
@joaomoreno I've seen this for about two weeks, but I couldn't reliably reproduce this. Whenever I tried to record it, it stopped from occurring.
