### ISSUE TITLE
NPM: Improve multiple lockfiles message

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111589]
Testing #111514 

Here's how it appears:

![image](https://user-images.githubusercontent.com/22350/100728603-10026400-33c8-11eb-84cb-a4ee3ad185db.png)
![image](https://user-images.githubusercontent.com/22350/100728630-1abcf900-33c8-11eb-8080-0def85b58568.png)

I suggest the following:

- Use `info` instead of `warn`
- Reorder the phrases: _Using npm as the preferred package manager. Found both package-lock.json and yarn.lock._
- Add a `Do not show again` button
- Add a `Learn more` for those who don't really know what's wrong. This should be a doc explaining that having both files is bogus and they should just have one.

**Comment by egamma** [comment]
The Learn More should also mention the `packageManager` setting and explain that it is now set to `auto` and that the user can also explicitly select a package manager.

**Comment by alexr00** [comment]
I could not find a place in our docs where documentation about multiple lock files should live, so I linked to the nodejs documentation on pack-lock.json files.
