### ISSUE TITLE
Push runs indefinitely over SSH remote

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111522]
Trying to push over an SSH remote fails to ever complete, and no errors are seen.

**Comment by eamodio** [comment]
Running `git push` from the command line resulted in:

```
fatal: Failed to enumerate credentials. [0x520]
fatal: A specified logon session does not exist. It may already have been terminated
```

And the terminal just hung (until I sent a break).

I then upgraded to the [latest beta](https://github.com/microsoft/Git-Credential-Manager-Core/releases/tag/v2.0.280-beta) of Git Credential Manager Core and that resolved the issue -- both in the terminal and in VS Code.

Although in the terminal I see saw the same error outputted a couple of times, but then it succeeded.

**Comment by aeschli** [comment]
Removed the milestone as the fix was upstream.
