### ISSUE TITLE
Keyboard input is invalid after an abnormal RDP session disconnection

### ISSUE THREAD

**Issue by bohrshaw** [microsoft/vscode#111553]
- VSCode Version: 1.51.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open the editor on Windows: `code --disable-extensions`
2. Open a RDP session to this Windows from a [MacOS RDP client](https://apps.apple.com/us/app/microsoft-remote-desktop/id1295203466).
3. Put the MacOS to sleep.
4. Login to Windows. Then try to type on Code.

Symptom:

The keyboard seems unresponsive. Code can't catch any key but mouse events.

Workaround:

Use the mouse to open "Command Palette". Then the keyboard works again.

**Comment by rdsuncn** [comment]
same issue

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167556
