### ISSUE TITLE
Test word wrap in the diff editor

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#111544]
Test plan item for #11387 and #110603

- [x] anyOS @sandy081
- [x] anyOS @rzhao271

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111544%0A%0A)

---

- make edits to a markdown file with long lines (Markdown files are wrapped by default).
- open the diff editor. The two editors making up the diff editor should be wrapped
- (you can also use the right click > select for compare / compare with selected flow to get yourself a diff editor with two distinct file types)
- with word wrapped editors, make sure that in side-by-side mode you can drag the middle sash and that the lines remain aligned (view zones are added to keep equal lines aligned, even if they wrap differently and on a different amount of lines due to the different sizes)
- please try the the inline diff editor and toggle the word wrap on / off. Please check that things look good and that original lines align with modified lines.
- with word wrap on, in the inline diff, please make sure that the deleted text also wraps (i.e. delete 2-3 consecutive long lines). Try to use the lightbulb that appears on deleted zones to copy a specific line from the deleted lines. Please make sure that the context menu is correct and reflects the logical line you have clicked on. 
- try to use `alt+z` or `View > Toggle Word Wrap` in a diff editor (side by side or inline). Please check that the file (URI based) that you toggled is now toggled, so you can have e.g. one side word wrapped and the other side not word wrapped.
- check that you can configure `diffEditor.wordWrap: 'off' | 'on' | 'inherit'` to forcefully change the word wrap behavior in a diff editor. The default is `inherit`, so the diff editor would wrap the editors it contains as if the files were opened independently.

**Comment by sandy081** [comment]
👌 Works like charm
