### ISSUE TITLE
Menu bar background color without custom title bar

### ISSUE THREAD

**Issue by Leseratte10** [microsoft/vscode#111595]
I am using VS Code 1.51.1 on Ubuntu 20.04, with the color theme "Dark+". However, while the VS Code window itself is in dark mode, the menu bar is still white. 

- I know that I could set `window.titleBarStyle` to `custom` but I would like to keep the Ubuntu-style window title bar. The `custom` Windows-10-styled title bar just looks like crap together with other Gnome-themed windows, it has the menu embedded in the title bar, and it doesn't respect the Gnome setting to have the close/min/max buttons on the left and re-ordered.

- I also know that I could set  `window.menuBarVisibility` to `toggle` so the menu only shows up when I hit the Alt key, but I don't like that as well. I'd like the menu bar to always be visible. 

I found the following existing issues, but none of them seemed to contain a satisfactory answer, and seem to get closed "to keep the amount of open issues at a manageable level": #16363 #30031 #57117 #105338

According to some of the pages linked in these bug reports it should be possible to tell the electron framework to change the color of the system menu bar to something else. 

If that does not work for VS code for some reason, I would like to suggest a new parameter for the `window.titleBarStyle` setting which keeps the system-provided title bar but uses the VS Code provided custom themed menu bar.

Is there any way to get this added? I don't like the Windows-10-themed combined title and menu bar, but I'd also like to have the menu bar dark-themed.

**Comment by sbatten** [comment]
The menu theming of the native menu bar on Linux is controlled by your OS GTK theme. The recommended approach is switch your OS theme to a dark theme.

**Comment by sbatten** [comment]
I will close this issue as designed but I will engage if you have further questions.
