### ISSUE TITLE
Import suggestion don't work sometimes.

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#111503]
- VSCode Version: 1.51.1
- OS Version: macos 11.0.1

Steps to Reproduce:

1. press "cmd" + "." on function

When I press hotkey for import suggestion on function, very often nothing happens. There are 2 reasons. Sometimes it can't find exported function, but sometimes it can't execute toolbar menu with suggestion because hotkey don't work and I need to change system language 2-5 times, and after that it starts working.

Does this issue occur when all extensions are disabled?: Yes

![изображение](https://user-images.githubusercontent.com/28058268/100609980-f4438300-331f-11eb-86a0-57b2b28c2cd4.png)

![изображение](https://user-images.githubusercontent.com/28058268/100609999-fd345480-331f-11eb-9942-4d7f285876e3.png)

**Comment by mjbvz** [comment]
Please share a steps to reproduce, including a small example project

**Comment by mjbvz** [comment]
Also, does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
