### ISSUE TITLE
Tree item hovers sometimes stick

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111525]
I don't have a reproducible case, or steps, but sometimes the new tree item hovers get stuck and won't hide -- unless you hover directly over another item in the same tree.

**Comment by Tyriar** [comment]
Is this still a problem for you? Not sure if it's on my side of tree side.

**Comment by eamodio** [comment]
Yeah, I still see it sometimes. Typically when switching between views and expanding a new view when the hover was visible from another.

**Comment by Tyriar** [comment]
@alexr00 would this be the tree not calling `hideHover` at some point?

**Comment by alexr00** [comment]
@Tyriar the tree view relies almost entirely on the automatic hiding that you added. The only time `hideHover` is called by the tree is when the user right clicks on a tree item to work around a case where the automatic hiding didn't work.

**Comment by Tyriar** [comment]
I haven't seen this, will need solid repro steps to action,
