### ISSUE TITLE
code-exploration symlinked to temporary AppTranslation path on MacOS Big Sur arm64

### ISSUE THREAD

**Issue by GJKrupa** [microsoft/vscode#111543]
- VSCode Version:1.52.0-exploration Commit: a31f124319d43aef2e9d8b875015d11a53c6f541 (ARM version)
- OS Version: macOS Big Sur 11.0.1 (Apple Silicon)

Steps to Reproduce:

1. Install Visual Studio - Exploration
2. Run the command workbench.action.installCommandLine
3. Reboot
4. Try to run code-exploration from a terminal

Instead of Code starting up, there will be a "command not found" error.

Runing ls -l /usr/loca/bin/code-exploration shows that this is syminked to something like `/private/var/folders/73/gbzw9z1d17nc9xp7sk5jw64h0000gn/T/AppTranslocation/8218EF9A-F559-487D-8618-E73F3D5D3B68/d/Visual Studio Code - Exploration.app/Contents/Resources/app/bin/code` which no longer exists instead of the actual installation directory e.g. `/Users/krupagj/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/bin/code`

Presumably this is because the app isn't signed and is flagged for quarantine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you update to latest [exploration build](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/VSCode-darwin-arm64.zip) and check if this is still an issue ? I am unable to repro on my machine.

**Comment by GJKrupa** [comment]
Tested on 1.52.0-exploration Commit: 25a4ee40993f43df9229edc552bd3018c086569d
I didn't get the issue on this build

**Comment by deepak1556** [comment]
Closing for now, can reopen if there is a consistent repro. Thanks for testing!
