### ISSUE TITLE
The fix for #26952 broke using Up to scroll the message itself while editing the commit message

### ISSUE THREAD

**Issue by chrisant996** [microsoft/vscode#111555]
- VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
- OS version: Windows_NT x64 10.0.19041
- Does this issue occur when all extensions are disabled?: **Yes**

Pressing Up while editing in the git commit message edit box now starts cycling through historical commit messages if the caret happens to be on the first line.  This is very disruptive:

Imagine if in your word processor, when you hold Up to scroll to the top of your document, the word processor started cycling through other documents you recently edited.  That's exactly what the new Up behavior is doing in the commit message edit box.  It's only a matter of time before I don't notice that it replaced my message with some other message, and I accidentally commit with a wrong or mangled message (I've had 3 close calls this week, so I filed this issue).

This behavioral regression was introduced by the particular implementation details to fix #26952.  The issue cited that Alt+Up cycles through history in other places.  But the fix made Up cycle (with no modifier keys), and that causes unexpected problems because it's not uncommon to tap Up repeatedly in edit boxes to scroll to the top.  Now attempts to scroll can overshoot and throw out the message the user is trying to compose.

It could potentially be reasonable for Up to cycle when the commit message edit box is empty, though.

Here are three suggested mitigation approaches:
- don't overload basic editing keystrokes like Up (safest)
- or only overload them when they can't be destructive/ambiguous, e.g. only when the commit message is empty or already cycled (reasonable compromise)
- or provide some way to disable the cycling feature (acceptable)

**Steps to Reproduce:**

1.  Have some modified files in a git repo.
2.  Have some previous commits that were made through VSCode.
3.  In the commit edit box in VSCode:
  a. type `hello`
  b. press Enter
  c. type `friendly`
  d. press Enter
  e. type `world`
4.  Hold the Up arrow to scroll to the top line (or tap it several times rapidly to scroll up) to simulate if the text were scrolled and you couldn't see how many times you'll need to press it to reach the top, and you want to press it enough times without having to pause and wait to see what happened.

**Expected outcome:**  flashing caret is on the first line of the text that I'm writing (this is how all other edit boxes I've ever used work).
**Actual outcome:**  the Up arrow started cycling through old commit messages.

This is especially troublesome because the commit edit box is so small, so it's very easy to end up text scrolled out of sight.  That makes it difficult/slow+iterative to predict how many times I have to press Up to reach the first line without overshooting into previous commit history.  I realize Ctrl+Home could be used instead but (1) that's not quite the same since it also changes the horizontal position of the caret, (2) not all edit boxes support Ctrl+Home so it's not suitable as a "works everywhere" default muscle memory action, and (3) applications shouldn't expect to reprogram their users.  ;)

**Comment by gjsjohnmurray** [comment]
As a workaround you could try the "Remove Keybinding" context menu option on the `scm.viewNextCommit` and `scm.viewPreviousCommit` commands. It looks like the default keybindings for `scm.forceViewNextCommit` and `scm.forceViewPreviousCommit` will mean you can still use Alt+DownArrow/UpArrow to move through the commits.

**Comment by meganrogge** [comment]
@chrisant996 can you pls confirm the suggestion of @gjsjohnmurray will work for you? For most users, we want to keep this behavior as it is.

**Comment by zbianca** [comment]
@meganrogge I couldn't find that setting and I also had problems with this feature. One of the projects at work requires really **long commit messages** and I oft use the arrows to navigate and keep running into problems now, just like @chrisant996 described.

**Comment by gjsjohnmurray** [comment]
@zbianca Use the context menu from the gearwheel button (bottom left) and choose "Keyboard Shortcuts". Use the search field to find the `scm.viewNextCommit` command. Right-click on it and choose "Remove Keybinding". If you ever want to restore the default keybinding use the "Reset Keybinding" option on that menu.

**Comment by zbianca** [comment]
Done. Thanks a lot!
