### ISSUE TITLE
Code Insiders 1.52.0 can't found git when started on remote wsl2

### ISSUE THREAD

**Issue by comicat-hu** [microsoft/vscode#111563]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/19973124/100704097-db020b80-33df-11eb-84cd-963bb6c20735.png)

Open a folder have git on remote wsl2 host but it show doesn't have a git at source control section.

Change version to 1.51 stable, it can work.

VS Code version: Code - Insiders 1.52.0-insider (ac165d7f974d70212be80cb15eaecfc1fd20b21a, 2020-11-30T17:36:25.607Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.35GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-16.04/home/comi/Project/blog --remote=wsl+Ubuntu-16.04 --crash-reporter-id d520f0c7-5038-4265-8a7f-19b2906f65b3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|12.31GB (9.54GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
vue|jcb|0.1.5
dotenv|mik|1.0.1
remote-containers|ms-|0.151.0
remote-wsl|ms-|0.52.0
code-settings-sync|Sha|3.4.3
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.11
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-footnotes|bie|0.0.7
markdown-image-size|bie|0.0.4
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.2.3
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
presentation-mode|eri|1.0.0
code-runner|for|0.11.1
gc-excelviewer|Gra|3.0.40
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.392013122
vsliveshare|ms-|1.0.3206
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
laravel-blade|one|1.25.0
tabnine-vscode|Tab|3.1.13
vscode-wakatime|Wak|4.0.9
vuter|yoy|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry244cf:30226748
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by lszomoru** [comment]
@comicat-hu, sorry for not getting back to you on this. 
Are you still experiencing this problem with the latest version of VS Code? Thanks!

**Comment by lszomoru** [comment]
@brybalicious, could you please share the steps that you follow to open the workspace containing the git repository? Also could you please share the "Git output" that can be accessed through `Git: Show Git Output...` command in the command palette?
