### ISSUE TITLE
schemaservice://combinedschema is not documented, confuses users

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#111575]
vscode can easily produce errors like below: 
```
Problems loading reference 'schemaservice://combinedschema/foobar': Unable to load schema from 'schemaservice://combinedschema/foobar': No content.
```

The main issue here is that while there is an option to enable or disable download of schemas there is no mention anywhere regarding where they are downloaded from, what is the current list of known schemas or how to add new schemas to that list.

Even the error message is cryptic because it does not mention where it attempted to load them from.

I should mention that I did attempted to search online for references of these but failed to find any proof of where is that hidden schema service.

AFAIK, the only existing public schema store is at https://json.schemastore.org/ and is maintained by a Microsoft employee. But sadly that proved not to be the source for the downloading schemas.

**Comment by aeschli** [comment]
> vscode can easily produce errors like below:

Can you give steps? That should not happen...

> how to add new schemas to that list. That's documented in https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings
