### ISSUE TITLE
Keybinding : Cannot read property 'fsPath' of undefined

### ISSUE THREAD

**Issue by gzjaychen** [microsoft/vscode#111559]
- VSCode Version:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- OS Version:
Mac OS 10.15.6 (19G2021)

- Othres:
Flutter plugin v3.16.0
Android Studio 4.1
XCode

Steps to Reproduce:
0.Create a flutter plugin project.
1.Set Keyboard Shortcuts/Flutter:Open in Android Studio -> Keybinding = Shift+Command+F1（no conflict）
2.Select example/android and press Shift+Command+F1
3.Display warning Cannot read property 'fsPath' of undefined.

It works well if I Right click -> Open in Android Studio.
Open in XCode has the same problem. 

Does this issue occur when all extensions are disabled?: Yes/No
Yes, and the warning become command 'flutter.openInAndroidStudio' not found

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the Flutter extension repository.
