### ISSUE TITLE
Apply enablement to all command links

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111587]
Testing #111517

* use the snippet below
* have a command that toggles the context
* 😕 the "big" button updates, the links aren't 

```json
		"viewsWelcome": [
			{
				"contents": "Hello [World](command:endgame-152.helloWorld).\n[Click Here](command:endgame-152.helloWorld)",
				"enablement": "endgame-152.helloWorld",
				"view": "debug"
			}
		]
```

<img width="352" alt="Screenshot 2020-12-01 at 11 24 51" src="https://user-images.githubusercontent.com/1794099/100728435-d7628a80-33c7-11eb-9b66-f19720de6c74.png">

**Comment by gjsjohnmurray** [comment]
Maybe only do this for command links? It might be useful to be able to use a link to doc even before an extension is ready to have its commands called.

**Comment by jrieken** [comment]
Yeah, command links is what I meant

**Comment by joaomoreno** [comment]
@gjsjohnmurray Want to submit a PR? 👍

**Comment by gjsjohnmurray** [comment]
I started researching this, and ran into the question of how to disable a link (`HTMLAnchorElement`). Found an interesting article [here](https://css-tricks.com/how-to-disable-links/). In summary, setting the `href` attribute to "" will prevent the link from functioning, and CSS selectors can be used to display a no-href one differently from a normal one. Does that sound like the way to go?

If yes, perhaps add a boolean `disabled` property to `ILinkStyles` and have the `applyStyles` method of the `Link` class use this to swap the `href` in or out, stashing it in a `data-href` attribute before clearing it from `href`.

What do you think?

**Comment by joaomoreno** [comment]
Sounds good to me.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray Want to submit a PR? 👍

@joaomoreno I have submitted #113841

**Comment by joaomoreno** [comment]
**Verification steps from @gjsjohnmurray:**

> To test, create an extension that contributes a welcome view with an enablement expression and at least one command link in the contents. Verify that the link is only clickable when the expression is true. Include a regular link in the content and verify it is always clickable.
