### ISSUE TITLE
Run view is blank when connected to SSH host, no debug options

### ISSUE THREAD

**Issue by shira-g** [microsoft/vscode#111501]
- VSCode Version:1.52.0-insider
Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
Date: 2020-11-26T07:22:59.162Z (4 days ago)
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0

- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. open Code - Insiders
2. connect to host using remote ssh
3. open Run view (or Run menu)
4. no options are shown
5. in addition- git repositories are not identified

Does this issue occur when all extensions are disabled?: Yes, I manually disabled all extension except for remote ones which are needed for the reproduction

**Comment by weinand** [comment]
I do not understand your issue.
How do you connect "using remote ssh"?
Are you seeing your project in the explorer?
What do you see in the "Run View"? Please provide a screenshot.
What do you expect to see in the "Run View"?

**Comment by shira-g** [comment]
![Screen Shot 2020-11-30 at 14 47 02](https://user-images.githubusercontent.com/30695324/100612283-682f5c80-331b-11eb-9cad-3d17645a3593.png)

I'm connecting to remote server using the command palette: command "Remote-SSH: Connect to Host", then I open a project located on my remote server. Then I want to debug the (python) code, but I see nothing in the "Run view". I expect to see debugging options.

**Comment by shira-g** [comment]
I switched to VSCode stable version (not insiders) and there is no issue there.

**Comment by isidorn** [comment]
If you F1 > developer tools > do you see some errors in the Devoloper Console?
Did this start happening in the last couple of days?

**Comment by shira-g** [comment]
yes I noticed it today only (I didn't use it in the last 3 days, but before that it was fine).
If you mean F1 > Toggle Developer Tools then yes there are few errors:

![Screen Shot 2020-11-30 at 20 33 00](https://user-images.githubusercontent.com/30695324/100649530-3f26c000-334b-11eb-8cb9-72e724b54eb2.png)
[-1606760927879.log](https://github.com/microsoft/vscode/files/5618010/-1606760927879.log)

**Comment by isidorn** [comment]
@shira-g Those errors do not seem related. Might there be more if you scroll up? Do you have a lunch.json in that repository
@joaomoreno might you have an idea how the debug welcome might not get loaded

**Comment by joaomoreno** [comment]
Yeah none of those errors seem related. Not really sure, @isidorn.

@shira-g Does it reproduce if you run with a new user data directory? `code-insiders --user-data-dir NEW_FOLDER`
