### ISSUE TITLE
Changing multiple occurrences when they are adjacent loses one of the occurrences

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode#11150]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Note how `11` turns into `2`.

![](https://cl.ly/203h0f0v0N2A/Screen%20Recording%202016-08-29%20at%2006.22%20PM.gif)

**Comment by alexandrudima** [comment]
Duplicate of #6661
