### ISSUE TITLE
The "open in visual studio code" is not working

### ISSUE THREAD

**Issue by bhagyajbijukumar** [microsoft/vscode#111565]
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open any folder in file explorer
2. Right click and click on "open in vscode"
![image](https://user-images.githubusercontent.com/62506150/100705000-7e492580-33cc-11eb-84d1-84e6a0e4dca9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Your screenshot shows a menu option named "Open in Visual Studio", which is a a different product. This repo is for Visual Studio Code.

**Comment by bhagyajbijukumar** [comment]
oh my bad
