### ISSUE TITLE
Sub window stop to be displayed

### ISSUE THREAD

**Issue by glt248** [microsoft/vscode#111571]
- VSCode Version: 1.51.1-1605051630
- OS Version: Debian 10 Buster / Xfce 4.12

Steps to Reproduce:

I'm using VSCode form 2 months on this computer, yesterday it was working correctly. This morning I'm not able to open a sub window.

1. Try to open a folder or try to open help/about
2. No window is opened

Does this issue occur when all extensions are disabled?: Yes

I've removed and purged code, reinstall it without extensions,. I've always the same issue.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by glt248** [comment]
Sorry it's a fake problem, one of my screen was activated but not powered (closed laptop)...

Thanks!
