### ISSUE TITLE
Adding Codespace to Home Screen Doesn’t Work

### ISSUE THREAD

**Issue by scrobby** [microsoft/vscode#111523]
- VSCode Version: Unsure - have tested on both stable and beta versions of GitHub Codespaces
- OS Version: iPadOS 14.2

Steps to Reproduce:

1. Open a Codespace in Safari and add it to the homescreen
2. Try to use it
3. The app will launch (in full screen, as is the desired effect) but it just hangs on "Preparing your Codespace"/"Connecting…"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
Not sure where this issue should go, starting with @bpasero

**Comment by bpasero** [comment]
This sounds like a Codespace issue, can you please open an item at: https://github.community/c/code-to-cloud/codespaces-beta/45
