### ISSUE TITLE
Esc is not closing the exception widget

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111592]
Testing #110567

- Press Escape when exception widget is shown
🐛 It is not getting closed.

**Comment by isidorn** [comment]
@sandy081 This works just fine for me.
I believe you had the find widget open or some other thing was eating the `esc` key. Which is designed - I gave the exception widget close a normal priority, so closing the find wigdet would happen first.

Please let me know if you always see this, and if you doing something differently than me?

**Comment by sandy081** [comment]
I do not have any other widgets open except exception widget.

![Kapture 2020-12-03 at 08 39 50](https://user-images.githubusercontent.com/10746682/100978838-3d275180-3543-11eb-8cda-a01ad11bf8a6.gif)

**Comment by isidorn** [comment]
Can you also reproduce if you disable Voice OVer?
Voice Over might be eating up that escape key for some weird reason?
If you click on X it closes just fine?

**Comment by sandy081** [comment]
> Can you also reproduce if you disable Voice OVer?

it works well when I disable Voice Over.

> If you click on X it closes just fine?

Yes

**Comment by isidorn** [comment]
Then it seems that VoiceOver is taking over your escape key. I would guess this is designed VoiceOver behavior, and for now I would just close it.
