### ISSUE TITLE
Downloading folder shows 2 notifications

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111577]
Testing #111250

![image](https://user-images.githubusercontent.com/900690/100722581-0cb7aa00-33c1-11eb-9c8d-c1113fbfd855.png)

I downloaded the "node_modules" folder from a Codespace (vscode repo).

I clicked on the status bar to open notification center.

**Comment by bpasero** [comment]
Also seeing 2 progress bars in the explorer:

![image](https://user-images.githubusercontent.com/900690/100725331-2efef700-33c4-11eb-80e3-610f390d24be.png)

**Comment by isidorn** [comment]
@bpasero two progress bars in the explorer. What are the steps for you to see this? I see you are using Code - Insiders?

For the first -> double downloading, is there an easy way to get into this state by running vscode out of source? Since by running `yarn web` the Download folder action complains. So my question is how did you get into this state?

**Comment by bpasero** [comment]
@isidorn yes, insiders with GH Codespaces extension connected to a CS.

**Comment by isidorn** [comment]
Unfortunetly I was unable to verify my commit since I need a real insiders out and could not verify with out of source build. Though I am 99% certain this fixes the issue

**Comment by roblourens** [comment]
I still see it in today's insiders

![image](https://user-images.githubusercontent.com/323878/101398826-877e3a80-3883-11eb-84cb-c8be9448c5ff.png)

**Comment by roblourens** [comment]
Also while downloading it disconnected/reconnected multiple times

![image](https://user-images.githubusercontent.com/323878/101398926-a67ccc80-3883-11eb-8afc-d0c20e0a34c5.png)

**Comment by isidorn** [comment]
@roblourens please file a separate issue for the disconnect reconnect.
Doulbe notifications are fine -> moving to December to fix then
