### ISSUE TITLE
The sidebar lacks Save and Open File buttons.

### ISSUE THREAD

**Issue by BTMike** [Microsoft/vscode#11159]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10

The two most basic, most used functions are missing buttons on the sidebar, and yet there's plenty of space and there's even an "Extensions" button. How times does anybody use that? Reminds me of the old Photoshop UI.

**Comment by bpasero** [comment]
No plans to add buttons in the sidebar. I think the top level menu is the right place for those. And there is a "Save All" button in the explorer "Opened Editors" view.
