### ISSUE TITLE
Replacing notebook cells results in new cells being inserted

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#111534]
- Version: 1.52.0-insider
- Commit: 0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d
- Date: 2020-11-26T07:22:59.162Z
- Electron: 11.0.2
- Chrome: 87.0.4280.63
- Node.js: 12.18.3
- V8: 8.7.220.24-electron.0
- OS: Darwin x64 20.1.0

Steps to Reproduce:

1. Clone GithuB issues Notebook Repo https://github.com/microsoft/vscode-github-issue-notebooks.git
2. Add the following code into `commands.ts`
```typesript
	subscriptions.push(vscode.commands.registerCommand('github-issues.replaceCells', () => {
		if (vscode.window.activeNotebookEditor) {
			vscode.window.activeNotebookEditor.edit(edit => {
				edit.replaceCells(1, 1, [
					{
						cellKind: vscode.CellKind.Code,
						language: 'java',
						metadata: {},
						outputs: [],
						source: ''
					}
				]);
			});
		}
	}));
```
Add the command into `packages.json`
3. Create a github issue notebook
4. Add 2 empty cells
5. Run the command `Replace Cells` (created above).

**Instead of replacing a cell, we now have 3 cells (we should have 2 cells).**

**If the API usage is incorrect, please advice.**

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
We should probably better document this, the element at `end` position will not be removed

```
/**
 * @param start The beginning of the specified portion of the cell list.
 * @param end The end of the specified portion of the cell list. This is exclusive of the element at the index 'end'.
 */
replaceCells(start: number, end: number, cells: NotebookCellData[]): void;
```

In this case you need to call `edit.replaceCells(1, 2, [])`

**Comment by DonJayamanne** [comment]
> In this case you need to call edit.replaceCells(1, 2, [])

Is `end` the total number of cells?
I.e. if i want to merely replace a cell (not insert), then is `end == cells.length`?
