### ISSUE TITLE
Test tree markdown tooltip API

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111515]
Refs: #100741

- [x] macOS @jrieken
- [x] linux @joaomoreno
- [x] windows @eamodio

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111515%0A%0A)

---

Test the the `TreeDataProvider`'s `resolveTreeItem` and the `TreeItem`'s `tooltip: MarkdownString` API. You can modify the [test view](https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/testView.ts) to test with.
1. Read the [JS doc for the new API](https://github.com/microsoft/vscode-extension-samples/blob/f2a57780639bce99099d5128db2d3be83012d0c0/tree-view-sample/vscode.proposed.d.ts#L1130-L1171) and verify that it makes sense.
2. Verify that you can set a `MarkdownString` as a `TreeItem` `tooltip` without using `resolveTreeItem`.
3. Verify that you can use `TreeDataProvider`'s `resolveTreeItem` to set a `TreeItem` `tooltip`.

**Comment by joaomoreno** [comment]
Added API doc link: https://github.com/microsoft/vscode-extension-samples/blob/f2a57780639bce99099d5128db2d3be83012d0c0/tree-view-sample/vscode.proposed.d.ts#L1130-L1171
