### ISSUE TITLE
HTML autocomplete outputs </[object Object]>

### ISSUE THREAD

**Issue by RobertCraigie** [microsoft/vscode#111537]
- VSCode Version: 1.52.0-insider
- OS Version: Windows_NT x64 10.0.19041

When there is no valid HTML tag to close </[object Object]> is filled in and while neither are really valid, I would have expected </> to be filled in instead.

Fairly certain this is a monaco bug as I originally discovered this issue on [https://play.tailwindcss.com/](https://play.tailwindcss.com/)

Steps to Reproduce:

1. Open a blank HTML file
2. Type </ and press enter or tab

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/confirm

Version: 1.52.0-insider (user setup)
Commit: ac165d7f974d70212be80cb15eaecfc1fd20b21a
Date: 2020-11-30T17:36:25.607Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by jeanp413** [comment]
Created a PR to fix this https://github.com/microsoft/vscode-html-languageservice/pull/93
