### ISSUE TITLE
Outline of exception widget is shown even after closing it

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111593]
Testing #110567

- Close the exception widget by pressing `x` and the outline is still shown

![image](https://user-images.githubusercontent.com/10746682/100732679-5c03d780-33cd-11eb-8bef-1b76e513bd47.png)

**Comment by sandy081** [comment]
Also that Voiceover continues reading the exception widget content even after closing it using `x`.

**Comment by isidorn** [comment]
I believe this is a VoiceOver bug, and not sure if we can do anything about it.
The outline is rendered by VoiceOver. Though assigning to November to investigate

**Comment by isidorn** [comment]
Treating as a bug since closing the exception widget while the focus is in the exception widget should pass focus to the editor. Which it now does.
