### ISSUE TITLE
Markdown Preview Under Working Files Should be Sticky

### ISSUE THREAD

**Issue by curtw** [Microsoft/vscode#1115]
Add a markdown (.md) file to the Working Files section
Under Working Files, right-click on this file and select "Open Preview" (you see preview)
Select another file so that the markdown file is out of view
Under Working Files, select this file again

Actual behavior:  you see the markdown source, not the preview
Preferred behavior:  you see the preview of the markdown file

In general, it would be useful if there were a way to pin the markdown preview so that one could easily switch back to it.

**Comment by bpasero** [comment]
In June you can "pin" any kind of editor to make it durable.
