### ISSUE TITLE
Dano-Norwegian characters are not supported

### ISSUE THREAD

**Issue by rajeshkhanikar** [microsoft/vscode#111505]
Issue Type: <b>Bug</b>

Dano-Norwegian characters are replaced by unicode special character.
Example: Borgs� instead of Borgsø

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 4325)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (35.34GB free)|
|Process Argv|--crash-reporter-id 2e6caca5-00fa-4ecc-9731-22a3cd7301fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gc-excelviewer|Gra|3.0.40
vscode-edit-csv|jan|0.5.0
csharp|ms-|1.23.6
powershell|ms-|2020.6.0
azdo-wiki-md|ni|0.0.3

</details>

**Comment by alexdima** [comment]
@rajeshkhanikar Do you have a problem with a particular file or with the editor? Can you for example create a new file and paste the desired characters?
