### ISSUE TITLE
JSON Schema Validation: Property displayed as missing even when it is there

### ISSUE THREAD

**Issue by dhananjay1405** [microsoft/vscode#111561]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19042

In JSON schema definition, a property decleration is made mandatory by including it in required properties. In the target JSON file, referring to that schema, property is defined. But still VS Code displays error of missing property, even though it is defined with proper data type value assigned to it. Screenshot of it is attached (url property is already defined by again shown as missing)
Schema version: http://json-schema.org/draft-07/schema
![bug-json-schema-missing-prop](https://user-images.githubusercontent.com/43024754/100698601-ded16600-33be-11eb-86d5-d437631e3f0c.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
/question You have a whitespace in the property name
