### ISSUE TITLE
Test: notebook self-host improvement

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111552]
Refs: https://github.com/microsoft/vscode/issues/109549

- [x] anyOS @dbaeumer 
- [x] anyOS @bamurtaugh

Complexity: 3

Authors: @rebornix @misolori 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111552%0A%0A)

---

This month we improved the self hosting experience for the native notebook. Most issues were reported in https://github.com/microsoft/vscode/issues/109549 so please go through the checked-off ones and test if they work reasonably well now. You can test with GitHub Issue Notebook https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks or the Jupyter extension if you want to play with real world scenarios https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter .

**Comment by bamurtaugh** [comment]
It's always great being able to see the work being done on notebooks- I enjoyed using this and it looks really nice! If we're able to figure out a solution to the most recent issue I opened above (error when opening a notebook with changes from source control), I could take a closer look at the reported items related to diffing to verify they're working properly.
