### ISSUE TITLE
Test: Getting Started framework

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#111554]
Refs: https://github.com/microsoft/vscode/issues/106715

- [x] anyOS @kieferrm
- [x] anyOS @sana-ajani

Complexity: 3

Authors: @misolori 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111554%0A%0A)

---

This iteration we worked on creating a framework for displaying a "getting started" experience. The content is still very much a work in progress, but the framework aspect is ready for initial testing. 

1. `"workbench.experimental.gettingStarted": true` (also try `"workbench.startupEditor": "gettingStarted"`)
2. Locate editor via Help -> Getting Started or opening a new empty window, depending on how you've enabled it. 
3. Ensure layout is reasonable.
3. Test that UI state persists across reloads, moving tabs, etc.
3. Test that progress bars work as expected (can be reset with `Getting Started: Reset Progress`)
3. Generally test that things work as expected.

**Comment by sana-ajani** [comment]
This looks awesome Jackson! I'm really excited to see this experience come together.
