### ISSUE TITLE
vscode.workspace.onDidChangeTextDocument ordering changes after closing and re-opening document

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#111548]
If I open a document and make an edit to it, changing the document from clean to dirty, my `vscode.workspace.onDidChangeTextDocument` handler is called twice, once with no `contentChanges` and `document.isDirty` set to `true`, and then again with `contentChanges` and `document.isDirty` also set to `true`. This is what I would expect.

However, if I close the document and reopen it (I'm guessing your internal event handlers get re-registered?) and repeat the above, the ordering of those two events is reversed. I first get called with the `contentChanges` and `document.isDirty` `false`, and then immediately get called again with no `contentChanges` and `document.isDirty` `true`. The first event seems to be erroneously reporting the document state to be not dirty, when in fact it is (after applying the edit anyway). 

Is this expected behavior? I'm guessing it's a bug and could lead to issues where extensions depend on knowing whether or not an edit made a document dirty (because edits made to files on disk when the document is clean don't result in the document becoming dirty).

**Comment by jrieken** [comment]
Please attach a full sample and console.log printings

**Comment by daytonellwanger** [comment]
## Extension sample (extension.ts)
```
'use strict';

import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    context.subscriptions.push(vscode.workspace.onDidChangeTextDocument((e) => {
        console.log(`isDirty=${e.document.isDirty}`);
        console.log(`contentChanges=${e.contentChanges.length !== 0}`);
    }));
}

export function deactivate() {}
```

## console.log printings
*Open file*
*Make edit on clean file*
```
isDirty=true
contentChanges=false
isDirty=true
contentChanges=true
```
*Save file*
```
isDirty=false
contentChanges=false
isDirty=false
contentChanges=false
```
*Close file*
*Open file*
*Make edit on clean file*
```
isDirty=false
contentChanges=true
isDirty=true
contentChanges=false
```

## Full extension
[test.zip](https://github.com/microsoft/vscode/files/5626144/test.zip)

**Comment by jrieken** [comment]
Ok, thanks for the steps. Took a while but this the designed behaviour because the document isn't actually closed. When closing the _editor_ we take the freedom to keep documents arounds for a bit and only clean them up later. You can observe that with the onDidClose/onDidOpenTextDocument events. So, when a document has been kept then it already has the listener for setting the dirty flag.

**Comment by daytonellwanger** [comment]
Thanks! So if an extension wants to know whether or not an edit made the document dirty, they shouldn't rely on checking `isDirty` on the document when they get the `onDidChangeTextDocument` that contains the text change, but rather rely on `isDirty` on the last `onDidChangeTextDocument`?

That's a little unexpected, but seems reasonable.
