### ISSUE TITLE
Built-in git feature fails to discover ".git" folder

### ISSUE THREAD

**Issue by Brawlence** [microsoft/vscode#111504]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Create a folder
2. Open it with VSCode
3. Navigate to Source Control
4. Press the "Initialize Repository" button
5. Note that the folder now has .git directory present; it's not shown in the VSCode folder hierarchy yet is present in filesystem

Expected behaviour:
VSCode's git feature registers the repo and displays branch name on the bottom ribbon.

Resulting behaviour:
Nothing in the UI changes

VSCode's git output reads:
```
Looking for git in: C:/msys2/usr/bin/git.exe
Using git 2.27.0 from C:/msys2/usr/bin/git.exe
> git rev-parse --git-dir
> git rev-parse --git-dir
> git rev-parse --git-dir
> git rev-parse --git-dir
> git rev-parse --git-dir
> git rev-parse --git-dir
> git rev-parse --git-dir
```
Running `git status` for the same folder gives:
```
>git status
On branch master
No commits yet
nothing to commit (create/copy files and use "git add" to track)
```
Developer console reports nothing when opening/closing folder with said repository or init'ing a new repository in the opened folder. This is a fresh install of VSCode, no extensions are present besides the build-in ones.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (5.08GB free)|
|Process Argv|--crash-reporter-id f6d17252-7067-4844-9e86-97e86f598c5b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by MightBeHarmless** [comment]
[This VS Code Issue](https://github.com/microsoft/vscode/issues/4651) by mattn in 2016, assisted me with [a problem](https://github.com/microsoft/vscode/issues/113363) occurring in 2020 with VS Code not being able to properly handle output of the `git rev-parse --git-dir` command.

I modified the proposed git-wrap.bat to make the last line:
`for /f %%1 in ('git %*') do cygpath -wa %%1` to enforce the full path is returned always to Code.

After hooking in the bat file in place of the git.path target, SCM started to function, for the first time.
So, in addition to checking for proper PATH settings, please consider these steps in debugging the resulting path formats.

I am using msys2 (mingw64) versions of git binaries in place of Git for Windows, which seemed too redundant to me. Though it must be considered that whatever simplification they set in place, it permits many users to avoid this troubleshooting. Win 10. 

Don't know why it takes others on VS Code to read or even comment upon our issues. I waited 7 days for a reply. Luckily I kept working the issue on my own, and thanks to others' efforts.

The VS Code devs could do us a great service by increasing the Logging output for their Git console, so we could observe the results of these commands at Logging levels greater than Info.

**Comment by Brawlence** [comment]
Thank you, I'll try this solution ASAP and report if it helps

**Comment by Brawlence** [comment]
@MightBeHarmless thank you! This **was** indeed the crux of the problem and the wrapper you had provided have solved it.

Putting references and copying info for future use:
#4651 : `As I filed issue ago, vscode can't work with msys2's git. Because git provided on msys2 return /c/ prefixed-path for rev-parse command.` (quoted issue: #387)

Since VSCode currently can't handle the output of msys2's `git rev-parse` output, the only temporary solutions appears to be indeed switching to a standalone (non-msys2) git version OR placing a wrapper around git.exe (msys2).
### SOLUTION
1. Place the following `git-wrap.bat` into git's directory:
```bat
@echo off
setlocal

rem If you don't add path for msys2 into %PATH%, enable following line.
rem set PATH=c:\msys64\usr\bin;%PATH%

if "%1" equ "rev-parse" goto rev_parse
git %*
goto :eof
:rev_parse
for /f %%1 in ('git %*') do cygpath -wa %%1
```
2. Change the `settings.json` to include reference to `git-wrap.bat` instead of `git.exe`
```json
"git.path": "C:/msys2/usr/bin/git-wrap.bat",
````

**Comment by ICHx** [comment]
I am having the same issue
![image](https://user-images.githubusercontent.com/11556527/111635374-63db7080-8832-11eb-9708-a42f59279eb1.png)
And this workaround works.

**Comment by mroosz** [comment]
I had no luck with this workaround (vscode insisted on using a git.exe and was thus not using the wrapper).
What helped is creating a directory junction in c:\cygdrive (create folder if it does not exist) from c to c:\ as mentioned at [stackoverflow visual-studio-code-cannot-detect-cygwin-git-exe-path](https://stackoverflow.com/questions/36508177/visual-studio-code-cannot-detect-cygwin-git-exe-path):
```
c:
cd\
mkdir cygdrive
cd cygdrive
mklink /j "c" c:\
```
on a first glance everything seems to work like a charm, having git.path is set back to cygwin folder
> ```json
> "git.path": "C:/cygwin64/usr/bin/git.exe",
> ```
vscode git output:
```
Looking for git in: C:\cygwin64\bin\git.exe
Using git 2.8.3 from C:\cygwin64\bin\git.exe
> git rev-parse --git-dir
Open repository: \cygdrive\c\Users\.....
```
