### ISSUE TITLE
Test: disable documentation and references in the HTML hover

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111549]
Refs: https://github.com/microsoft/vscode/issues/97979

- [x] anyOS @lszomoru
- [x] anyOS @bpasero 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111549%0A%0A)

---

Try the new settings:
```
"html.hover.documentation": false,
"html.hover.references": false,
```

Test that these disable & enable the documentation test on/or references to MDN in the HTML hover

**Comment by lszomoru** [comment]
Works as advertised 👍🏻

**Comment by lszomoru** [comment]
@bpasero, could you help with this test plan item? Thank you!
