### ISSUE TITLE
Keybindings menu cleanup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111598]
Talking about this:

![image](https://user-images.githubusercontent.com/900690/100741797-6082bd00-33da-11eb-8b60-aaef59b0b13d.png)

Suggestions:
* for commands that require user input, append a "..." (e.g. add, change)
* group delete and reset in separators away from the others to make them stand out more

**Comment by bpasero** [comment]
```
Copy
Copy Command Id
-------------------
Change Keybinding...
Add Keybinding...
--------------------
Remove Keybinding
Reset Keybinding
---------------------
Change When Expression
--------------------------
Show Same Keybindings

**Comment by sandy081** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/10746682/100778717-a4d88200-3407-11eb-9679-4b2f9af6d19c.png">
