### ISSUE TITLE
Test: Git uses `vscode.open` and `vscode.diff`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111519]
Refs: #110397

- [x] macOS @bpasero
- [x] linux @JacksonKearl
- [x ] windows @eamodio 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111519%0A%0A)

---

The git extension changed considerably the way it opens files/diffs from the SCM view.

- Test that opening new files, deleted files, changed files, etc, works as expected
- Test that the standard tree mouse/keyboard interactions work: ctrl+click (open to side) and double click (open not in preview)
- Test that settings which control the actions above are respected, such as `workbench.list.openMode`

**Comment by bpasero** [comment]
👏 . Only thing I wasn't sure about is: if I have configured `"workbench.list.openMode": "doubleClick"`, a single middle-mouse click does not open. But maybe that is intentional.

**Comment by JacksonKearl** [comment]
All looked good to me on Ubuntu.

**Comment by eamodio** [comment]
I think it looks good on Windows too. Below are some scenarios that I think make sense, but just documenting to make sure.

FYI, all the double-clicks are sometimes flakey. You really have to wait for the dblclick timeout to expire, before clicking again.

With `"workbench.list.openMode": "singleClick"` and `"workbench.list.multiSelectModifier": "ctrlCmd"`:

- `Ctrl+Click` select/unselect
- `Ctrl+DblClick` opens to the side - not in preview
- `Alt+Click` opens to the side in preview
- `Alt+DblClick` opens to the side - not in preview

With `"workbench.list.openMode": "singleClick"` and `"workbench.list.multiSelectModifier": "alt"`:

- `Ctrl+Click` opens to the side in preview
- `Ctrl+DblClick` opens to the side - not in preview
- `Alt+Click` select/unselect
- `Alt+DblClick` opens to the side - not in preview

With `"workbench.list.openMode": "doubleClick"` and `"workbench.list.multiSelectModifier": "ctrlCmd"`:

- `Ctrl+Click` select/unselect
- `Ctrl+DblClick` opens to the side - not in preview
- `Alt+Click` does nothing
- `Alt+DblClick` opens to the side - not in preview 

With `"workbench.list.openMode": "doubleClick"` and `"workbench.list.multiSelectModifier": "alt"`:

- `Ctrl+Click` does nothing
- `Ctrl+DblClick` opens to the side - not in preview
- `Alt+Click` select/unselect
- `Alt+DblClick` opens to the side - not in preview
