### ISSUE TITLE
Support a way to have nightly/insiders versions of extensions not activate if "main" extension is installed/enabled

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111521]
More an more, extension authors are providing a nightly/insiders version of their extensions. Which can cause issues for end-users if they have both versions installed. And today, extension authors can't properly deal with this because of the static contributions -- which can cause a bad end-user experience.

Since we have a `preview` flag in `package.json`, I would propose that we add a new `previewOf` option that could be set to an extension id, that this preview is a preview of. So for example, GitLens Insiders (eamodio.gitlens-insiders) would set `"previewOf": "eamodio.gitlens"`.

When VS Code sees this flag, it would determine if the `previewOf` extension is installed and enabled, and if so, then would auto-disable this extension so it wouldn't be activated at all.

This would avoid a bad end-user experience, especially if we show a reason in the extension view to why this extension is now disabled. It would also avoid issues with Codespaces issues with built-in extensions and nightlies.

/cc @jrieken @sandy081 @connor4312 @RMacfarlane @JacksonKearl

**Comment by sandy081** [comment]
As per our last discussions with Marketplace team, they are planning to work on enabling beta releases for extensions - https://github.com/microsoft/vscode/issues/15756. It seems to be an intermediate solution and once we have beta versions support from  Marketplace, this approach might become invalid/redundant.

**Comment by eamodio** [comment]
While I do hope that happens soon -- I don't think we should gate anything on that (as its been requested for years). And regardless it seems to me that vscode would need a flag or something to provide this ability to not have versions conflict with one another. This proposal also works without the marketplace -- e.g. just with vsix installs.

Additionally, this issue causes quite a bit of pain for users using insiders/nightly version of our own extension in Codespaces with Settings Sync.

**Comment by eamodio** [comment]
Thinking about this more -- I think we would really need a matched pair of settings, e.g. `stable` / `insiders`. 

"stable" extension's `package.json`, e.g. `eamodio.gitlens`
```json
"insiders": "eamodio.gitlens-insiders"
```

"insiders" extension's `package.json`, e.g. `eamodio.gitlens-insiders`
```json
"insiders": "eamodio.gitlens"
```

And you can only ever have `insiders` or `stable` specified (we shouldn't allow both at the same time to avoid weird loops and edge cases). This would ensure this deactivation is desired by both extensions, to avoid bad actors.

Also, by having the pair, when activating either extension, we will know immediately if we need to check for the other extension (avoiding any extra lookups for most cases), and we would know explicitly what to check for (validating that the match is exists and is correct).

While I quite like the `stable` / `insiders` pair naming (thanks @RMacfarlane), here are some additional alternatives:
`previewExtension` / `previewOfExtension`
`previewVersion` / `previewOfVersion`
`altExtension` / `altOfExtension`
`previewedBy` / `previewOf`
`exclusiveWith` / `exclusiveTo`
`supersededBy` / `supersedes`

**Comment by isidorn** [comment]
Closing as out of scope since we now have the pre-release extension support
