### ISSUE TITLE
Provide a way for extensions to call `authentication.getSession` that won't result in any prompts

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111529]
Today as an extension, there are 2 ways to call `authentication.getSession`:

1. `authentication.getSession(<id>, <scopes>, { createIfNone: true })`
2. `authentication.getSession(<id>, <scopes>, { createIfNone: false })`

The first case is typically used when there is an explicit user action to an extension that the extension requires auth for -- so in theory a prompt/auth flow is expected.

While the second case is often used to get access to an existing session if there is one, usually by an implicit action (which my not even be caused by the user). And if there is a session, BUT the extension doesn't have access to it, then there is a prompt requesting that the user grant access. This is problematic for a couple of reasons, first an extension trying to determine access to a session has no way to avoid prompting the user, and the user (because it isn't related to a specific action) has no idea why they are getting this prompt.

There should be a way for an extension to call `getSession` completely silently -- and it would just return `undefined` if there is either no session or no session with granted access. Granted you'd no longer be able to tell the difference between no session at all vs a session without access. So maybe there should be an additional `hasSession` api that just takes an `id` to account for that.

To deal with this, maybe there is an additional flag `{ createIfNone: false, ensureAccessIfFound: boolean }` so that an extension can pass `{ createIfNone: false, ensureAccessIfFound: false }` for silent access.

Additionally it would be great for an extension to be able to provide a "reason" for the authentication prompt. So that even if `ensureAccessIfFound: true`, the user can be provided with some context as to why they are getting this prompt.

**Comment by nikolaytoplev** [comment]
You found a very important problem.
I am developing vscode extension now and faced such problem.
Thank you for your posting this problem.

**Comment by RMacfarlane** [comment]
Instead of introducing another flag, I've reused the existing "createIfNone" flag. If this flag is set to true, then a modal dialog gets shown prompting for access. Otherwise, a badge is shown on the accounts icon activity bar and an entry is added there.
