### ISSUE TITLE
Test vscode.open in the NPM scripts view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111512]
Refs: #110497

- [x] macOS @alexdima
- [x] linux @rebornix
- [x] windows @lszomoru 

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111512%0A%0A)

---

1. Open a project with NPM scripts.
2. In the Explorer viewlet, right click and make the NPM scripts view visible.
3. Click on a script in the NPM scripts view to open the package.json file at the script's location.
4. Verify that click modifiers that work in Explorer also work from the NPM scripts view (ex. alt+click to open to the side).

**Comment by rebornix** [comment]
Works as advertised, love this feature!
