### ISSUE TITLE
Test Synchronising Global State

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111527]
Testing https://github.com/microsoft/vscode/issues/109896

- [x] anyOS @bpasero
- [x] anyOS @tanhakabir

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111527%0A%0A)

---

## Set Up

You can use two insiders opened with different user data directory (`--user-data-dir`) and extension directory (`--extensions-dir`) for test syncing across machines.

## Testing

In this milestone we changed the internals of how global state is synced. Hence I would request to do some sanity testing of synchronising UI state. You can consider following UI state for testing:

- Visibility and location of view containers (ActivityBar & Panel)
- Visibility and location of views (Sidebar & Panel)
- Visibility of status bar items
- Test setting up new machine - turn on settings sync and make sure UI state is synchronised correctly.

**Comment by bpasero** [comment]
I had to use VSCode Insiders and VSCode stable in the end to test settings sync because when I run 2 instances of VSCode insiders from different user data dirs, I have to constantly log into the other with my GH account but then the wrong instance opens.

**Comment by tanhakabir** [comment]
I don't think it's working on my end. I opened 2 instances of Insiders in 4 different user-dirs and extension-dirs but I don't see changes I make to the UI in one propagate to the other. I also get a dialog box that repeatedly pops up when I click "OK":
![image](https://user-images.githubusercontent.com/12758612/100911904-adbb6900-3484-11eb-829d-1a1fbc006a31.png)

**Comment by sandy081** [comment]
Seems you are having issues setting up multiple insiders. As suggested, please try syncing your main insiders with web self host.

**Comment by tanhakabir** [comment]
Views aren't synced for 2 instances insiders: 
![image](https://user-images.githubusercontent.com/12758612/100929442-7eb0f180-349c-11eb-85ee-b66b716e857e.png)
