### ISSUE TITLE
Test sticky tab stops

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#111542]
Test plan item for #2798

- [x] anyOS @misolori 
- [x] anyOS @stevencl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111542%0A%0A)

---

- Enable `editor.stickyTabStops` (this works well together with `editor.useTabStops` so you can also enable that if you have it disabled).
- Open a file that is indented with spaces 
- (optionally) enable indent guides or render whitespace
- use the left arrow / right arrow keys (and shift+left/right) to move in the indentation whitespace
- also try clicking in the indentation whitespace
- the spaces in the indentation should before more like tabs in terms of selection, making your life easier.

**Comment by stevencl** [comment]
I don't see the setting editor.stickyTabStops but I do see editor.atomicSoftTabs. When I set this to true the editor behaves as described above.

**Comment by misolori** [comment]
This works very cool, nice job! I think having this enabled by default would help a lot of people out.

**Comment by alexdima** [comment]
@misolori Yes, I tried to sell it as the default to the team, but there was push-back that people would be surprised because they don't have render whitespace on and they might "no longer recognize spaces vs tabs". But I agree that we should revisit this and probably make it the default.
