### ISSUE TITLE
Flatpak VSC Tkinter Installation

### ISSUE THREAD

**Issue by Daggerpov** [microsoft/vscode#111502]
- VSCode Version: 1.51.1 (**FLATPAK** version) NOTE: THIS ISSUE DOESN'T OCCUR WITH THE **DEBIAN** VERSION, THAT APPLICATION WORKS FINE FOR ME.
- OS Version: Pop! OS 20.10

The issue is that, despite having tkinter installed and the ability to run it through my terminal like so: 

![image](https://user-images.githubusercontent.com/53918934/100608890-1ff04a00-32db-11eb-81bd-781dcd8fa590.png)

I could not run my tkinter programs the same way through my integrated VSC terminal, since it'd say that the module 'tkinter' could not be found. 

Steps to Reproduce:

1. Open up Terminal within Visual Studio Code
2. Pip install tkinter within a Python virtual environment.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by meganrogge** [comment]
I think your path to the installation is wrong. [This ](https://stackoverflow.com/questions/37380957/tkinter-module-not-found) might help

**Comment by Daggerpov** [comment]
That's actually not the solution to my issue, however, I found out that simply by using the Debian version of VSCode I could remedy it instead of using the Flatpak version.
