### ISSUE TITLE
Can't use shortcut "Ctrl + D" to select multiple word in a new document I didn't save

### ISSUE THREAD

**Issue by yzpTsubasa** [Microsoft/vscode#11152]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open an exsisted document: A.example
2. Create a new document:B.example
3. Type or paste some words into B.example
4. Switch to A.example
5. Switch to B.example
6. Select one word of B.example
7. Use shortcut "Ctrl + D" but doesn't work

**Comment by wallverb** [comment]
Fixed in insiders version https://github.com/Microsoft/vscode/issues/10075

**Comment by alexandrudima** [comment]
@yzpTsubasa Can you please try the insiders version and confirm the issue is fixed? (It can be installed in parallel with the stable version)

https://code.visualstudio.com/insiders

**Comment by yzpTsubasa** [comment]
@alexandrudima Fixed perfectly in insiders versoin. Thank you.
