### ISSUE TITLE
Option to disable the (new) persistence of the suggestions bubble

### ISSUE THREAD

**Issue by CameronBieganek** [microsoft/vscode#111526]
VS Code [recently added a feature](https://code.visualstudio.com/updates/v1_51#_move-cursor-to-select-suggestions) that persists the suggestions box/bubble while moving the cursor through a word. However, as far as I can tell, there is no option to disable this feature.

The problem with this feature is that now the only way to get rid of the suggestions bubble is to hit the escape key. I used to be able to navigate my cursor to the left or right in order to not accept any of the suggestions and get the suggestions bubble to disappear. Now I regularly have to hit the escape key to accomplish this, which is much more annoying.

Note: I do not want to disable suggestions altogether on my machine, I just want it to be easier to get the bubble to disappear when I don't wish to accept any of the suggestions.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest""+label%3A"under-discussion""

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/110193#issuecomment-723846492
