### ISSUE TITLE
I think VSCode is loading previous of file in my Flask app

### ISSUE THREAD

**Issue by GitBashing** [microsoft/vscode#111510]
Issue Type: <b>Bug</b>

Since I have changed the directory of the project VSCode is loading old versions of the HTML and CSS files. When I removed `style.css` from` /static` the problem persisted, still loading some old version of `style.css`. I have tested this by running the flask app from text editor in Kubuntu and it runs as expected, no faults with previous versions of `style.css` or `index.html`. 
I have run the commands 'Clear Editor History' and 'Clear Command History' but that hasn't fixed the issue either.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-54-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.71GB (2.89GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id d4ee4496-e45a-4f79-8de5-4758c591c8a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.10.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.372831992
cpptools|ms-|1.1.2
LiveServer|rit|5.6.1

</details>

**Comment by rebornix** [comment]
> VSCode is loading old versions of the HTML and CSS files

@GitBashing do you mean when you open the file in the editor, the content is the old one?

**Comment by GitBashing** [comment]
Thanks for your reply, this issue can be deleted because I have discovered it was caused by the cache of the browser. Pressing CTRL+SHIFT+R to reload the browser solved it.
