### ISSUE TITLE
Update schema with new color token

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#111547]
![image](https://user-images.githubusercontent.com/35271042/100671617-a4f85500-3315-11eb-9160-5ee51a049f06.png)

Refs #110214

When adding `statusBarItem.errorBackground` to our default light theme, I am getting the `Property ... is not allowed` warning and haven't been able to update the schema. Can you take a look?

**Comment by aeschli** [comment]
This works for me when running from sources:

![image](https://user-images.githubusercontent.com/6461412/100676012-4e683680-3368-11eb-8cdb-233131dd97e3.png)


Maybe you tried in an older build?

**Comment by misolori** [comment]
Ah, you're right I was on an old build that didn't have his color token yet. Thanks!
