### ISSUE TITLE
Memory leak in terminal support

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#111562]
- VSCode Version: 1.51.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Open a terminal
2. Type in the following: while true; do echo test; done
3. Observe memory consumption: it will increase, and eventually the VS Code will die with a OOM

Does this issue occur when all extensions are disabled?: No

I investigated why it happened, and root caused it to a memory leak in xterm.js
- xterm.js has experimental buffer API here: https://github.com/xtermjs/xterm.js/blob/5cb048094e23da22ccfe46666b87d1ad427dce6d/src/browser/public/Terminal.ts#L61
- In the above line BufferNamespaceApi is created
- In the constructor of it, BufferNamepsaceApi created a listener: https://github.com/xtermjs/xterm.js/blob/5cb048094e23da22ccfe46666b87d1ad427dce6d/src/browser/public/Terminal.ts#L251 But this listener never gets removed
- .buffer is called all over the place in terminal support, thus leaking memory

It's possible to work around this issue by getting a buffer once, on xterm object creation, and using this object instead of a terminal.buffer. I checked, and it fixed the above problem. The memory consumption is stable, and vs code doesn't die.

**Comment by meganrogge** [comment]
I'm not seeing this happen in local VS code windows - only remote (after 15+ minutes of running the script). Is that what you're seeing too @solomatov ?

**Comment by solomatov** [comment]
@meganrogge I had it both cases, but in case of the remote it was showing much faster, but your version, and configuration is likely different from mine.

**Comment by meganrogge** [comment]
[fixing ](https://github.com/xtermjs/xterm.js/pull/3203) this upstream in Xterm.js
