### ISSUE TITLE
Hovers have horizontal scrollbar when not needed

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111572]
This just started very recently.

![hovers](https://user-images.githubusercontent.com/641685/100717378-f3ded280-3387-11eb-8773-adff0bb6bcaa.gif)

**Comment by alexdima** [comment]
@eamodio I cannot reproduce. I tried with GitLens `v11.0.6` using the insiders:
```
Version: 1.52.0-insider
Commit: bf21395291146c014220eb70b54fdfc0a15956b5
Date: 2020-12-01T09:20:33.868Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

![Kapture 2020-12-02 at 14 07 36](https://user-images.githubusercontent.com/5047891/100876504-c1c49200-34a7-11eb-87c7-0a83d6ce9a7b.gif)

**Comment by eamodio** [comment]
Yeah it went away for me in yesterday's insiders. Maybe it went away when we switched back to Electron 9?

**Comment by eamodio** [comment]
Not exactly sure but I only saw it very recently. And it was gone again a day or two ago.

**Comment by alexdima** [comment]
OK, given we cannot reproduce right now, let's close for now and we can reopen if we see it again when we bring back Electron 11.

**Comment by eamodio** [comment]
It's back in the current insiders.
