### ISSUE TITLE
usersetting is none

### ISSUE THREAD

**Issue by Aidmx** [microsoft/vscode#111566]
Issue Type: <b>Bug</b>

when i open setting, it's none in viewport

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.71GB free)|
|Process Argv|D:\BimClient --crash-reporter-id 2600cfc5-59f3-45db-9a8e-a5209e3d6002|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
ue4-snippets|CAP|2.0.1
gitlens|eam|11.0.6
git-graph|mhu|1.27.0
compare-folders|mos|0.18.0
vscode-language-pack-zh-hans|MS-|1.51.2
csharp|ms-|1.23.6
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.392013122
cpptools|ms-|1.1.2
powershell|ms-|2020.6.0
unreal-engine-4-helper|ope|0.3.2
vscode-hexdump|sle|1.8.1
sleeping-forest-ue4|suv|0.6.14
vscode-icons|vsc|11.0.0

</details>

**Comment by gjsjohnmurray** [comment]
Please explain in more detail. Screenshots might help. They can usually be pasted directly from the clipboard into the GH input field.
