### ISSUE TITLE
Test contributing codicons for views and view containers

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111531]
Testing https://github.com/microsoft/vscode/issues/106348

- [x] AnyOS @lszomoru 
- [x] AnyOS @sana-ajani

Complexity 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23111531%0A%0A)

---

You can now contribute codicons for view or view container icons. Eg: `"icon": "$(code)"` Refer https://microsoft.github.io/vscode-codicons/dist/codicon.html for codicons.

You can use https://github.com/microsoft/vscode-extension-samples/blob/master/tree-view-sample to test

- Contribute codicon for view or view container icon from package.json and make sure these icons are shown correctly. View icons are shown when you drag the view on to activity bar.

**Comment by sana-ajani** [comment]
In the treeview extension sample, I can contribute a codicon in the viewContainer for the Package Explorer and I see that in the activity bar. But I'm not sure what/where I should be seeing the icon when I set the codicon for the Node dependencies view in Package Explorer viewContainer.

**Comment by sandy081** [comment]
View icons are shown when you drag the view on to activity bar.

**Comment by sana-ajani** [comment]
Ah gotcha, thanks for explaining! Cool, this works well.
