### ISSUE TITLE
Web: no longer seeing progress when uploading a folder

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111583]
Testing #111250

Dropping a folder into a web codespace no longer shows progress in the status bar when using insiders, works fine in stable. 

@isidorn maybe related to your changes for reporting progress from explorer?

**Comment by isidorn** [comment]
Yes, droping a folder was using a custom progress reporting solution. I refactored the thing and did not want a special solution just for drop.
So I will check why the general progress case does not catch this.

**Comment by bpasero** [comment]
@isidorn my web git bisect points out to a change that caused it here: https://github.com/microsoft/vscode/compare/6026ab576dc6a4fbb8e255241a364816f42464c5...0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d

The experience now in web is quite bad, even clicking on a file while the upload is in progress does not work.

**Comment by isidorn** [comment]
@bpasero my changes should not affect that clicking on a file while the upload is in progress does not work.
Maybe I broke that, but I would be surpsied. Did you bisect that to an exact commit maybe?

**Comment by bpasero** [comment]
@isidorn yes, confirmed it is https://github.com/microsoft/vscode/commit/668b1d24399e3df2a517d1d18f2b406b1cef8cee

**Comment by isidorn** [comment]
@bpasero I have pushed a change that the progress is now shown (I was missing an `await`).
For Clicking on a file while upload is in progress I have filled a new issue https://github.com/microsoft/vscode/issues/111832

**Comment by bpasero** [comment]
I commented on that change, I think there is another call you miss to `await`
