### ISSUE TITLE
Chinese MSBuild output gibberish

### ISSUE THREAD

**Issue by dqywill** [Microsoft/vscode#11156]
- VSCode Version: 1.4
- OS Version: Windows 10 14393.103 (1611)

Steps to Reproduce:

1. Press F1, input build
2. Create build task, use msbuild option
3. Run msbuild task
![screen shot](https://cloud.githubusercontent.com/assets/3927006/18076661/76152b90-6eb2-11e6-9da4-984f13b3c680.png)

**Comment by dbaeumer** [comment]
Dups #3550.
