### ISSUE TITLE
Uploading a folder into remote should show similar progress to web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111582]
Testing #111250

When I drop a folder or file into a remote, it reports "Copying..." from the status bar. I wonder if it should be "Uploading..." instead and follow a similar model as we have for web:

![recording (1)](https://user-images.githubusercontent.com/900690/100724427-2823b480-33c3-11eb-954f-464162f67857.gif)

**Comment by isidorn** [comment]
Web uses a custom solution which only works for that use case, I want a general approach for all file operations.
I would not change this for now -> backlog.

**Comment by isidorn** [comment]
Actually let's close as dup of https://github.com/microsoft/vscode/issues/111580
