### ISSUE TITLE
Run tab - NodeJS Debugging errors

### ISSUE THREAD

**Issue by Zorono** [microsoft/vscode#111629]
- VSCode Version: 1.51.1
- Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- Date: 2020-11-10T23:31:29.624Z
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Linux x64 5.8.0-29-generic (Ubuntu 20.10)

<details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
asp-net-core-snippet-pack|adr|1.51.0
Bookmarks|ale|12.0.0
All-Autocomplete|Ati|0.0.23
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-checkbox|bie|0.1.3
path-intellisense|chr|2.3.0
regex|chr|0.2.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
php-class-generator-composer-psr-4|dam|1.0.1
vscode-eslint|dba|2.1.13
xml|Dot|2.5.1
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.3
apacheconf-snippets|eim|1.3.0
bootstrap-4-cdn-snippet|eve|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.1
vscode-google-translate|fun|1.4.9
vscode-pull-request-github|Git|0.21.2
go|gol|0.19.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.188
composer|ika|0.7.1
compareit|in4|0.0.2
easy-snippet|inu|0.6.2
search-node-modules|jas|1.3.0
kite|kit|0.135.0
node-module-intellisense|lei|1.5.0
VS-code-drupal|mar|0.0.12
vscode-discord|max|1.0.2
dotenv|mik|1.0.1
file-downloader|min|1.0.6
compare-folders|mos|0.18.0
vscode-apache|mrm|1.2.0
csharp|ms-|1.23.6
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.392013122
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.2
js-debug-nightly|ms-|2020.11.2617
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.6.0
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.2.3
vsliveshare|ms-|1.0.3206
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
gremlins|nho|0.26.0
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.4.0
fabric8-analytics|red|0.2.1
vscode-yaml|red|0.13.0
explorer-exclude-vscode-extension|Red|1.2.0
vscode-javascript-booster|sbu|14.0.1
html5-boilerplate|sid|1.1.1
search-pawn-package|sre|0.0.3
rewrap|stk|1.13.0
mtasa-lua|sub|2.4.0
lua|sum|1.3.0
control-snippets|svi|1.9.1
vs-code-node-require|tgr|1.4.7
mtasasnippets|the|0.0.3
msbuild-project-tools|tin|0.3.10
vscodeintellicode|Vis|1.2.10
vscode-arduino|vsc|0.3.4
snippet|vsc|0.8.1
codetour|vsl|0.0.39
gistfs|vsl|0.1.12
quokka-vscode|Wal|1.0.331
wordpress-toolbox|wor|1.3.8
eno|Wsc|2.3.38
JavaScriptSnippets|xab|1.8.0
makefile-creator|zen|0.0.3
html-css-class-completion|Zig|1.19.0
</details>

Steps to Reproduce:
1. Open "Run" Tab from the sidebar
2. Try to debug my nodejs app with "Node.js (preview)" option....
3. I receive a bunch of errors which is massively not easy to understand(for me at least...)

Does this issue occur when all extensions are disabled?: Yes

Please note that this issue only appeared after a system halt yesterday(which i guess was caused by a kernel bug LOL...)
however, I tried the following installs which I hadn't luck with...
```
npm install -g iconv-lite
npm install -g iconv
npm remove iconv (I know this is ridiculous :p) 
npm remove iconv-lite
```

The Errors I got:
```
Exception has occurred: Error: Cannot find module 'iconv'
Require stack:
- /path/to/nodejs//lib/node_modules/npm/node_modules/encoding/lib/iconv-loader.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/encoding/lib/encoding.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/make-fetch-happen/index.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /path/to/nodejs/lib/node_modules/npm/node_modules/libnpm/fetch.js
- /path/to/nodejs/lib/node_modules/npm/lib/utils/metrics.js
- /path/to/nodejs/lib/node_modules/npm/lib/npm.js
- /path/to/nodejs/lib/node_modules/npm/bin/npm-cli.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/path/to/nodejs/lib/node_modules/npm/node_modules/encoding/lib/iconv-loader.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**Comment by weinand** [comment]
This is a problem of your program, not a VS Code issue.

**Comment by Zorono** [comment]
> This is a problem of your program, not a VS Code issue.

xD I amn't running any module that requires iconv as dependency...

**Comment by weinand** [comment]
and when you run your program from the command line it works fine?

**Comment by Zorono** [comment]
> and when you run your program from the command line it works fine?

yes
it works with node-inspect and node --inpect|

**Comment by weinand** [comment]
How does you launch.json look like?

**Comment by Zorono** [comment]
> How does you launch.json look like?

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program (Production)",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/${fileBasename}"
        },
        {
            "type": "node",
            "request": "launch",
            "args": ["--inspect"],
            "name": "Launch Program (Basic Debug)",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}/${fileBasename}"
        }
    ]
}
```
