### ISSUE TITLE
Don't render plain text via markdown

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111643]
While discussion `MarkdownStringTextNewlineStyle` with @eamodio I have learnt about this piece of code: https://github.com/microsoft/vscode/blob/af5c09a10cd17e598949c5008018431b97fea9fb/src%2Fvs%2Fworkbench%2Fservices%2Fhover%2Fbrowser%2FhoverWidget.ts#L85

I'd say it trouble some to try to render plain text via fancy escaping and markdown. The simpler variant would be to check if tooltip is a string and that use a simple dom node and text content. For instance the suggest widget details [do that](https://github.com/microsoft/vscode/blob/4a1cea9306d2d0fc39e608a035e331cb9b0c0189/src%2Fvs%2Feditor%2Fcontrib%2Fsuggest%2FsuggestWidgetDetails.ts#L165)

**Comment by alexr00** [comment]
Completely agree! Giving to @Tyriar as the owner of the workbench hover widget.
