### ISSUE TITLE
Bad rendering of status bar item with error background color

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#111618]
Testing #111423

Setting the color works, but the rendering looks off in quite of my themes. This is in SLime:

<img width="73" alt="capture" src="https://user-images.githubusercontent.com/1931590/100747689-ad6a9180-33e2-11eb-94c2-76fcb9ba2ae1.png">

Or solarized dark

<img width="120" alt="capture" src="https://user-images.githubusercontent.com/1931590/100747813-d1c66e00-33e2-11eb-9c7c-cbb88898dc8b.png">

@bpasero @misolori is there anything I need to do here (e.g. setting the foreground color?)

**Comment by dbaeumer** [comment]
My code looks like this:

```ts
	statusItem.backgroundColor = new vscode.ThemeColor('statusBarItem.errorBackground');
	statusItem.text = 'Hello World';
	statusItem.show();
```

**Comment by bpasero** [comment]
@misolori is the idea that this only works well if the extension is also used the associated foreground color? Should we maybe then just set it automatically?

**Comment by misolori** [comment]
@bpasero yea we should set it automatically as the default error foreground should work better. I fear most won't read the description that mention the need to set the foreground so doing it automatically would be best.

**Comment by bpasero** [comment]
I can make that change. @misolori so you also added matching foreground error colors when you tweaked background colors to themes right?

**Comment by misolori** [comment]
Correct, [already updated](https://github.com/microsoft/vscode/commit/c6e90c5ea35877bd835be000d717c37d066b3bb9) the matching foreground color.

**Comment by bpasero** [comment]
I pushed a fix. I do not change the `color` property provided from the extension to not cause weird side effects, I just internally enforce to use the error foreground color if the background color is set.

**Comment by dbaeumer** [comment]
Looks nice now.
<img width="86" alt="capture" src="https://user-images.githubusercontent.com/1931590/100998008-4ae8d100-355b-11eb-86f7-4590ddd15cf1.png">
