### ISSUE TITLE
Text Editor > Search > Loop setting is ignored

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#111690]
- VSCode/OS Version:
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Datum: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

![Loop setting is ignored](https://user-images.githubusercontent.com/9283914/100816348-2a7b2280-3446-11eb-8b34-a5c32473b161.gif)

**Comment by rebornix** [comment]
Closing it and then reopen the editor should take effect.
