### ISSUE TITLE
Code Token/Key/Password Warning

### ISSUE THREAD

**Issue by alpinedelight** [microsoft/vscode#111660]
A feature that scans code before committing/storing to remote locations (i.e. via git) that its detected potentially compromising information, i.e. passwords, access keys, tokens, secrets etc.
This could be a simple confirmation, or even something more advanced i.e. install a secret manager extension, to drive best practice and protect sleep deprived developers from themselves.

**Comment by RMacfarlane** [comment]
This is a great idea! But I think this would be best implemented as an extension
