### ISSUE TITLE
undo/redo copy and paste of a folder changes it to a file

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#111693]
Testing #111015

Ctrl C on the file copies it as expected
Ctrl V pastes the copy as expected
Ctrl Z removes the file as expected
Ctrl Y adds a file with the folder's name
Ctrl Z removes the file with the folder's name

![recording (57)](https://user-images.githubusercontent.com/29464607/100819453-0fd28a80-3401-11eb-84ae-fafc649ed695.gif)

**Comment by isidorn** [comment]
Good catch, assigning to November to try to fix

**Comment by isidorn** [comment]
I ahve have fixed this that it now brings back the folder, however the folder is empty which is captured via this issue https://github.com/microsoft/vscode/issues/111022

**Comment by meganrogge** [comment]
still getting a file instead of a folder when I undo and redo even though it says insiders released

**Comment by isidorn** [comment]
@meganrogge  I justr tried latest insiders and it works for me. Here are my steps, let me know if you are using different steps:

1. Select a folder in the Explorer, Ctrl + C, Ctrl + V
2. Ctrl + Z -> Folder copy gets deleted
3. Ctrl + Y -> Folder gets brought back from trash as a folder
