### ISSUE TITLE
96MB file is not updating after being opened first time and never closes

### ISSUE THREAD

**Issue by NaomiN** [microsoft/vscode#111633]
Issue Type: <b>Bug</b>

I opened ~92MB .log file in the Editor and navigated towards the end of the file searching for the 'error' word. The file is on the Network folder. I have replaced that file several times already with the newer copy of that file. Unfortunately, the editor somehow keeps the version I opened more than a week ago and I am unable to even close it in the Visual Studio Code (that window keeps showing up). I don't know how can I open the most recent version of the file instead and also how can I close that file from the Editor.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

**Comment by rebornix** [comment]
Starting with @alexdima since there are changes to this area recently.

**Comment by alexdima** [comment]
If vscode is closed and the file comes back with an old state, this sounds like hot exit.

**Comment by NaomiN** [comment]
Every time I close VS Code completely and then re-open this file (and 2 other files) come up :( If I try to press x at the top, it keeps asking me to save changes and I always answer 'Don't Save' and the file just never closes and remains in the editor.

**Comment by NaomiN** [comment]
UPDATE. Looks like the file did close now. I'm trying to open this new version of the file (97MB) and I'm seeing the waiting indicator.

**Comment by bpasero** [comment]
@NaomiN when this file opens automatically does it appear as dirty? and if so, when you close it and say "Don't save" does it work?

**Comment by NaomiN** [comment]
Yes, that was the original issue, but I somehow was eventually able to overcome.
