### ISSUE TITLE
Should resolveTreeItem support cancellation?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111614]
Testing #111515

I have a feeling that `resolveTreeItem` should support cancellation because it can be long running (like fetching data via the internet) but also depends on the user gesture (hover, expand-collapse)

**Comment by alexr00** [comment]
What do you think should cause the cancel to trigger? Or, if it takes sufficiently long enough would be show a progress notification with a cancel button?

**Comment by jrieken** [comment]
> What do you think should cause the cancel to trigger?

Moving away is what I have in mind. Like, I hover long enough to start resolving but the move away

**Comment by alexr00** [comment]
That makes a lot of sense.

**Comment by alexr00** [comment]
Proposal is to add an optional cancellation toke parameter:

https://github.com/microsoft/vscode/blob/5b75a42575fd85c3a9f69bec76bd1afe7c2dcb33/src/vs/vscode.proposed.d.ts#L946-L948

**Comment by jrieken** [comment]
I wouldn't make it optional because that makes it harder to consume. Making it not optional won't break the API because it is OK to implement an interface function with less arguments

**Comment by alexr00** [comment]
To verify:
- Read the API and verify that it matches other API where we have a cancellation token.
