### ISSUE TITLE
Not able to re-enable an extension disabled via bisect

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#111666]
Testing #111495

The `Enable` button is missing until reload.
![image](https://user-images.githubusercontent.com/8586769/100788745-5b1d7680-33ca-11eb-831a-f02f51987dfa.png)

**Comment by jrieken** [comment]
Yeah - bisect disables extensions using a low-level mechanism which doesn't allow for user enablement. I am also not sure that it is a good idea to "randomly" re-enable some extensions as that basically breaks the bisect flow

**Comment by JacksonKearl** [comment]
once the bisect is done can it be put back into the user-disable-able state?

**Comment by jrieken** [comment]
ah, now I get it. This is about the final disablement when bisect has found the bad extension, right?

**Comment by JacksonKearl** [comment]
Yes

**Comment by jrieken** [comment]
Adding @sandy081 - I believe this should be working. When you keep the "bad" extension disabled then I disable it with the extensions service. See this https://github.com/microsoft/vscode/blob/e024fd8b967d532588aa1da1c5a9c5129b0d658c/src%2Fvs%2Fworkbench%2Fservices%2FextensionManagement%2Fbrowser%2FextensionBisect.ts#L287-L289

Tho, in all fairness the window should reload quickly after that (line 295) or did that not working for you?

**Comment by JacksonKearl** [comment]
Oh so it doesn't reload the window if I click "report issue & continue" and I end up stuck in the weird state

**Comment by sandy081** [comment]
Enablement is disabled if an extension is disabled in environment (by bisect or through cli). It seems the above blamed extension is disabled by bisect already and hence enablement options are not shown.

https://github.com/microsoft/vscode/blob/5d591624ae2944da29969a9de71e1c89959b55ee/src/vs/workbench/services/extensionManagement/browser/extensionEnablementService.ts#L80-L83

**Comment by jrieken** [comment]
> Oh so it doesn't reload the window if I click "report issue & continue" and I end up stuck in the weird state. I notice in that state I also have access to the Continue Extension Bisect command pallet entry, which feels unexpected.

Hm, this might then be an issue with me [await'ing](https://github.com/microsoft/vscode/blob/e024fd8b967d532588aa1da1c5a9c5129b0d658c/src%2Fvs%2Fworkbench%2Fservices%2FextensionManagement%2Fbrowser%2FextensionBisect.ts#L291) the issue reporter resolving its promise. Which I have just learned [never](https://github.com/microsoft/vscode/blob/37e9cceddc5f8e8fe504378b04ebd7388beb6601/src%2Fvs%2Fplatform%2Fissue%2Felectron-main%2FissueMainService.ts#L189) resolves... 😨 I will push a workaround that ensure that the renderer reload independent of the issue reporter

**Comment by JacksonKearl** [comment]
reneging issue reporter, how fun :)
