### ISSUE TITLE
Update progress message to Copying x of y

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111626]
Testing #111250

Update progress message to Copying x of y

![image](https://user-images.githubusercontent.com/10746682/100750396-43ec8200-33e6-11eb-848c-a27491cc65c6.png)

**Comment by isidorn** [comment]
This is a fair feature request.
However it would have to be supported by the Bulk Edit service.
I also think for this we would need a richer label. Also assinging to @jrieken to think about this

**Comment by jrieken** [comment]
I think this is relatively easy because we have some progress object, tho maybe not the right one. It would need to be a `Progress<URI>` so that it can report what uri is currently being worked on.
