### ISSUE TITLE
EventEmitter listener leak warning while debugging

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11169]
1. Open an extension workspace, one which you can debug
2. Repeat 7 times: `F5`, close debuggee window

![image](https://cloud.githubusercontent.com/assets/22350/18081713/cff0127c-6e9b-11e6-91be-996566fd0f35.png)

**Comment by isidorn** [comment]
August to investigate

**Comment by isidorn** [comment]
Please quickly code review @joaomoreno

**Comment by joaomoreno** [comment]
After that fix you no longer see the message?

**Comment by isidorn** [comment]
Yes, I no longer see the message

**Comment by joaomoreno** [comment]
I think you got it then, the change makes sense. 👍
