### ISSUE TITLE
Redo cut/paste not working

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111631]
Testing #111015

- In the vscode repo, select `src/vs/nls.build.js` in the file explorer
- Use `Cut` from the context menu
- in the file explorer select a different folder (e.g. src/vs/workbench/test), paste
- from the window menu, run `Edit > Undo`. Move is undone :heavy_check_mark: 
- from the window menu, run `Edit > Redo`. Error message is 
`Could not redo 'Rename nls.build.js to nls.build.jsW' across all files. The following files have been closed and modified on disk: /home/martin/workspaces/vscode/src/vs/nls.build.js.`

Maybe related that this is a js file, as it works for other files (e.g. `.editorconfig`)

**Comment by aeschli** [comment]
Also seems to be timing dependend. It can work, other times not. Sometimes even the undo fails with the same message

**Comment by isidorn** [comment]
Assigning to November to investigte

**Comment by isidorn** [comment]
This works just fine for me on my macOS. I tried it intensively 10+ times both via keyboard and context menu
Also assigning to @alexdima since the error is coming from the Undo Redo service and he might have ideas

**Comment by alexdima** [comment]
This error usually happens when there was a text buffer edit, then the text buffer was closed (disposed from memory), then the text buffer opened again from disk, but the opened file sha1 is different than the closed file sha1. @aeschli Your steps do not mention any text edits, but I wonder if you did some in your initial repro?

**Comment by aeschli** [comment]
This works for me today, yesterday it failed consistently.

Ok to close. I'll try to reach out if I get this again.
