### ISSUE TITLE
Undo dnd from system finder throws error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111654]
Testing #111015

* Drag a file from Finder into VS Code
* Undo

<img width="372" alt="image" src="https://user-images.githubusercontent.com/876920/100781061-66b77000-33bf-11eb-813d-7942023770e9.png">

**Comment by isidorn** [comment]
This works fine for me.
Are you dragging some special file?
Can you always reproduce this?
Do you see a more detailed error in the developer console?

**Comment by rebornix** [comment]
Interesting that I can't reproduce anymore. Closing for now. Considering that multiple reported issues were no longer reproducible, I wonder if my machine is in a weird state.
