### ISSUE TITLE
Markdown preview won't update when file changed by git

### ISSUE THREAD

**Issue by louis925** [microsoft/vscode#111685]
Issue Type: <b>Bug</b>

1) right click a markdown file to open a preview of it in VSCode
2) push a change to the same markdown file from other place using git
3) sync the change to this computer using git or github app
4) close the preview tab in VSCode
5) right click a markdown file to open a preview in VSCode again
The preview doesn't reflect the change and is not the same as the markdown file anymore

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|-psn_0_151589 --crash-reporter-id 6bac2fce-2e16-47b5-b5b2-21a65006ddb8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.0.6
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.392013122
remote-containers|ms-|0.148.1
cpptools|ms-|1.1.2
vscode-yaml|red|0.13.0

</details>

**Comment by mjbvz** [comment]
Is the editor content displayed in VS Code's normal text editor correct?

**Comment by louis925** [comment]
Yes!

**Comment by louis925** [comment]
Great! Thank!
