### ISSUE TITLE
Undo/Redo history messed up with dnd and file copy

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111655]
Testing #111015

Prerequisite: have a folder structure like below

```
- github
  - a.txt
- sample
  - b.txt
```

Now follow below steps:

* Drag `b.txt` to `gitHub` folder
* `cmd+z` moves `b.txt` back to `sample` folder
* `cmd+c` on `b.txt`, `cmd+v` will create a file `sample/b copy.txt`
* `cmd+z` will remove file `sample/b copy.txt`
* now press `cmd+shift+z`

Expected behavior: `sample/b copy.txt` comes back
Actual behavior: `sample/b.txt` moves into `gitHub` folder

**Comment by isidorn** [comment]
Yes, I can reproduce this.
I believe the issue is that the redo operation is a move which overwrites the original file name `b.txt`.

No plans to fix this in endgame.
