### ISSUE TITLE
Support setting standard input for debugging

### ISSUE THREAD

**Issue by ByteEater-pl** [microsoft/vscode#111694]
I'd like a feature like at ideone.com whereby standard input can be set and reused non-interactively whenever the code is run. Currently I work around it by creating a file and reading from it instead. But it requires very different code which is a disadvantage particularly when the finished programme is supposed to operate on standard input.

**Comment by weinand** [comment]
What debugger are you using?

**Comment by ByteEater-pl** [comment]
Node.js. But this issue isn't language specific. I would likely need this functionality too when writing C#, Haskell or Python.
