### ISSUE TITLE
TS: warn user when the globally installed version is 2.0 and tsdk isn't set

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11162]
TS 2.0 will become available in September and users will switch. To avoid the confusion that on the command line they are using 2.0 but inside vscode they are using 1.8 we should warn the user.

- run tsc --version on the command line to check the version
- if the tsdk setting isn't defined then inform the user that they should set it

**Comment by dbaeumer** [comment]
@egamma pls verify.

**Comment by dbaeumer** [comment]
Forward link is not in yet. Will ping when ready.

**Comment by roblourens** [comment]
In the case where it detects the local version, looks like the `alwaysUseLocal` option is not totally implemented yet but will that add the correct setting to a local `settings.json`? That would be awesome and really helpful.

**Comment by dbaeumer** [comment]
@roblourens that is the idea. However the API didn't make it into 1.5 so that has to wait for 1.6 :-)

**Comment by egamma** [comment]
@dbaeumer here is the fwdlink:  http://go.microsoft.com/fwlink/?LinkId=826239
It is defined to refer to https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Comment by dbaeumer** [comment]
@egamma forward link added and pushed. Ready to verify.

**Comment by egamma** [comment]
I've verified on Windows. `More Information` spawns the browser.
