### ISSUE TITLE
With `window.restoreWindows=preserve` files do not pick a good window to open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111605]
Testing #111420

> use the terminal to open VSCode on a file when VSCode is not running and verify all your other windows from before also open and the file opens in either your last active window or the one that has the parent folder opened

This didn't work for me.

On Windows, with WSL. I had two windows open: `vscode (WSL)` and `fakeproject` (not WSL). Without Code running, I invoked `code-insiders C:\Users\joao\Desktop`. Now I have three windows: `vscode (WSL)`, `fakeproject` and `Desktop`. I exit Code. I then invoked `code-insiders C:\Users\joao\Desktop\file.txt`. The same three windows come up but `file.txt` is open in the `fakeproject` window instead of the `Desktop` window. 🐛

**Comment by bpasero** [comment]
The [code to open windows on startup](https://github.com/microsoft/vscode/blob/c44732014de3bfe009d56b4eb7371ef7d2a4987c/src/vs/platform/windows/electron-main/windowsMainService.ts#L541-L795) is a horrible mess. Even Frodo would rather happily travel again through Moria than look at that code for any minute....

I am too afraid to change the existing code. Truth is, we actually do not pick a good window to open files in:
* we miss to pick the window that has the parent folder opened (this issue)
* we miss to fallback to the last active window (https://github.com/microsoft/vscode/issues/111620)

I think the right fix would be to rewrite all of this mess and start fresh with all these use cases in mind.

**Comment by joaomoreno** [comment]
I doubt you'll get this issues our in the wild. So let's just close it silently. 🤫

**Comment by bpasero** [comment]
Oh I actually think I would like to fix this and I do think it is quite annoying, especially for users that have asked for the feature to restore windows, so I will see what I can do.

**Comment by bpasero** [comment]
Ah, the "I am too afraid to change the existing code. " was misleading, I just didn't want to push a fix now in endgame week. Needs some good testing in insiders.

**Comment by bpasero** [comment]
i have actually never gotten an issue for this, so I will close it. not so straight forward as I had hoped...
