### ISSUE TITLE
Keep Editors Open menu choice in the editor '...' menu should be a checked option

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111668]
Testing #111417

While I like having the _Keep Editors Open_ choice in the editor `...` menu, it was unexpected to me that it would disappear once I chose it (users would then have to figure out how to undo, what it did). I would rather expect it to behave like a checked option -- you could check it or uncheck it to toggle the behavior.

**Comment by bpasero** [comment]
Yeah I think this is fair. Needs verification:
* this menu action is now always visible and reflects the current state of preview editors
* you can toggle enable and disable it from there
