### ISSUE TITLE
Redo file rename fails

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111653]
Testing #111015

Platform: macOS

* Rename a file from `a` to `b`
* `cmd+z` to undo, file name is reverted to `a`
* `cmd+shift+z` to redo, it throws an error

```
Could not redo 'Rename test.ikqlnb to vscode.ikqlnb' across all files. The following files have been closed and modified on disk: /Users/penlv/code/prototype/notebook-test/kusto/test.ikqlnb.
```

**Comment by isidorn** [comment]
@rebornix Works for me following your exact steps. Are you using some special files?
This might be coming from the Undo Redo Service, thus also assigning to @alexdima for ideas on how to repro

**Comment by isidorn** [comment]
Let's also assign @jrieken for ideas

**Comment by jrieken** [comment]
@rebornix What save settings do you use? auto save, after delay, or manual?

**Comment by alexdima** [comment]
@rebornix I also could not reproduce:

![Kapture 2020-12-02 at 13 46 00](https://user-images.githubusercontent.com/5047891/100874361-bf146d80-34a4-11eb-89e8-e097526da14e.gif)

**Comment by rebornix** [comment]
I don't have a good way to reproduce again, other than seeing it once yesterday. Close it for now.

**Comment by isidorn** [comment]
Okey, let us know if you see it again. Thanks
