### ISSUE TITLE
highlightModifiedTabs and pinned tabs issue

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#111641]
**Env:**
```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

**Steps to Reproduce:**
As you can see, the blue stripe overlaps the pinned tabs
![obraz](https://user-images.githubusercontent.com/30685349/100765477-d0ec0700-33f7-11eb-9070-89638a9ee308.png)

**Does this issue occur when all extensions are disabled?:** 
All disabled except GitGraph, but I don't think this addon is involved in this issue

**Comment by bpasero** [comment]
This is due to our various `z-index` being used in tabs, I am a bit afraid to change this so late in endgame, will revisit next month.
