### ISSUE TITLE
Recent folders list changes when opening folder in extension debug window

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11164]
- Open an extension workspace
- `F5`
- Open folder in debuggee window

Maybe that folder shouldn't come into the recently opened folders list.

**Comment by ramya-rao-a** [comment]
@joaomoreno When you say the "debuggee" window do you mean the extension development host window?
If yes, then I can still reproduce this.

My steps:

1. Create a new folder say "abc" (to ensure that Recently Opened Folders list does not have it)
2. Launch an extension from extension workspace
3. In the window that opens (the extension development host), open the "abc" folder
4. Close this window
5. Open File -> Open Recent from the original VS Code window

I can see "abc" in the recently opened folders list

I am using VS Code Insiders dated 9/29

**Comment by roblourens** [comment]
I apparently was trying to verify this at the same time and I still see it too.
![sep-29-2016 11-21-07](https://cloud.githubusercontent.com/assets/323878/18966701/17d4b0cc-8637-11e6-80d5-e275d8c99129.gif)
