### ISSUE TITLE
Window that contains the passed file should have focus on restore

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#111612]
Testing #111420

1. `window.restoreWindow: preserve`
2. Have a couple of windows open, for example `vscode-smoketest-express` repo and some other
3. Exit vscode
4. Open vscode from the command line such that some file from the `vscode-smoketest-express` repo is passed as command line
5. The correct VS Code windows are restored, however the one that should be focused and in front should be the one containg the file just passed - thus the `vscode-smoketest-express` repo. However focus is on the window which had last focus before exiting.

**Comment by isidorn** [comment]
Same if I pass a `code-workspace` file, that window should be in front and focused

**Comment by bpasero** [comment]
I pushed https://github.com/microsoft/vscode/commit/c44732014de3bfe009d56b4eb7371ef7d2a4987c which will ensure that the window the files are open in get's focus. However, seeing https://github.com/microsoft/vscode/issues/111620 and https://github.com/microsoft/vscode/issues/111605, this may not be the window that is the parent of that file.

**Comment by bpasero** [comment]
@isidorn maybe you could verify this (out of sources is fine too), I am not entirely sure I got your second comment right.

**Comment by isidorn** [comment]
My second comment is: if I pass a code-workspace file to open a brand new workspace that window shuold be focused.

Sure I can verify this, adding label bug so I do not miss this

**Comment by bpasero** [comment]
>  if I pass a code-workspace file to open a brand new workspace that window shuold be focused.

Hm interesting, while this seems to work for folders, it does not seem to work with workspace files. Is that what you saw? Passing a new folder correctly focusses that new folder even when other windows restore, but not when you pass a workspace file from the command line?

**Comment by isidorn** [comment]
Correct. That is what I saw.

**Comment by bpasero** [comment]
Ok will look into that separately.
