### ISSUE TITLE
Mock debug doesn't break on exceptions

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111600]
Testing #111425

The UI looks good, and functions the way I'd expect. However, Mock Debug never breaks on "exceptions".

![recording (29)](https://user-images.githubusercontent.com/38270282/100744396-100d5e80-33de-11eb-8efe-3d3c2642b05a.gif)

**Comment by isidorn** [comment]
Forwarding this to @weinand since it is up to Mock debug to send a break event
