### ISSUE TITLE
Add a LICENSE Auto-filler

### ISSUE THREAD

**Issue by mehtaarn000** [microsoft/vscode#111698]
Hello. Whenever I create a `LICENSE` file in Visual Studio Code, it would be great if I got to select my preferred license (such as MIT) and have the file automatically filled out with said license. Thanks in advance.

**Comment by ffMathy** [comment]
Why not just create an extension for this?

**Comment by mehtaarn000** [comment]
@ffMathy I have 0 experience with TypeScript, so I probably wouldn't be able to make it anytime soon. My bio has JavaScript in it, but I'm pretty much a beginner with the language.
