### ISSUE TITLE
'open in explorer' should be shown at foreground not background

### ISSUE THREAD

**Issue by smalllong** [Microsoft/vscode#11167]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. right click a file
2. select open in explorer

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/929
