### ISSUE TITLE
Find in Folder need escaping when filling "files to include" search option

### ISSUE THREAD

**Issue by diego-mazzaro** [microsoft/vscode#111677]
Issue Type: <b>Bug</b>

- have a folder named "some[folder]"  in the workspace
- right click the "some[folder]" in explorer pane
- select "Find in Folder..."
  - the search pane is shown and files to include will be ./some[folder]
  - no file is shown because brakets are interpreted as special characters
  - instead it shoud be escaped to ./some[[]folder[]]
  - in this way it work as expected and folder content is shown

In the same way it needs to be escaped other characters e.g. '[', ']', '(', ')', '{', '}'.

Other features requests are asking to support folder names with parhentesis; they are already supported indeed but need to be correctly escaped. And this should be done when auto-filling the search options.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/82415
