### ISSUE TITLE
js-debug insists on recent version of node.js

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#111642]
Testing #111422

This launch config (which doesn't use node.js at all):
```js
{
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"runtimeExecutable": "echo",
	"runtimeArgs": [
		"${env.FOO}",
		"${env.PATH}"
	]
}
```

does not work on a linux that only has node.js 5.0.

Error message:

<img width="658" alt="2020-12-01_17-27-15" src="https://user-images.githubusercontent.com/1898161/100767967-a485ba00-33fa-11eb-9584-da191b926a10.png">

The launch config works fine when setting `debug.javascript.usePreview` to false.

(I use "nvm" on that linux and have it configured for node.js "12.13.1" but js-debug doesn't find it on the PATH, but that is a different issue...)

**Comment by connor4312** [comment]
Node versions before 7 use the old inspector protocol rather than CDP, which we don't support, and the protocol is somewhat buggy even on 8. Node 8, which is EOL since this beginning of this year, accounts for <1.2% of debug users, and I imagine there are even fewer users with previous node versions, so I don't think it's worth going to the effort of trying to support this in any way aside from providing the informative prompt.

**Comment by weinand** [comment]
@connor4312 I'm **not** asking for support for legacy versions of node.js here.

The problem is that js-debug eagerly blocks my launch config based on the false assumption that it will use /usr/local/bin/node. The launch config does not use node.js at all. So there is no reason for blocking it. I think the error should only be shown if js-debug detects a real problem and there is some probability that an old version of node.js might be the culprit.

In my case I'm using a standard ubuntu (which seems to have node.js 5.0 installed). But since I'm using "nvm", I do not really care about the old node.js 5.0 install. Whenever I run node.js it picks up the "nvm-installed" version. Only js-debug seems to find the legacy version.

**Comment by connor4312** [comment]
> But the launch config does not use node.js at all. So there is no reason for blocking it. I think the error should only be shown if js-debug detects a real problem where there is some probability that an old version of node.js might be the culprit.

js-debug does not know that the launch won't eventually use Node.js; we support debugging nested processes in the tree. In theory we could allowlist certain commands that don't have side effects like "echo" or "cat", but I don't know why users would want to have a node launch config that doesn't use Node...

On 6 and below we get a syntax error trying to import the bootloader. If the process is not running in an integrated or external terminal, we could catch the syntax error from stderr, but in a terminal we would have no way to know what happened and be stuck waiting for the connection.

> Whenever I run node.js it picks up the correct "nvm-installed" version. Only js-debug seems to find the legacy version.

We pull `node` from the PATH of the extension host both for version detection and actually running the program. If the nvm version of the binary isn't in the extension host, that is a problem. It may be related to https://github.com/microsoft/vscode/issues/106537

**Comment by connor4312** [comment]
One thing I thought of is checking process.version in the bootloader and just echo'ing the warning to the console if the version is too low. However this has two downsides:

- it would not show in the debug console (unless we do more work there...) because we don't emit stdout by default
- --require in NODE_OPTIONS does not work on Node 4 or below, so that would at best be a partial solution for 5 and 6

**Comment by weinand** [comment]
@connor4312 thanks a lot for exploring this...

But again, I'm actually not asking for supporting node.js 5.x (or other obsolete versions).
Couldn't you just turn the fatal error (which blocks debugging completely) into a warning (that doesn't prevent me from debugging)?

Imagine I have shell script that uses a version 12.13.1 of node.js and hardcodes an absolute path to it.
On my system (e.g. Ubuntu) I still have the distribution's default version of node.js installed (e.g. version < 8.0).
But I'm never using this version, but I didn't bother to remove it either.

If I now create a debug config that uses the shell script from above as the "runtimeExecutable", js-debug will prevent me from debugging this perfectly fine setup because it finds the obsolete version of node.

**Comment by connor4312** [comment]
I think that's fair. I will now show this instead. 

![](https://memes.peet.io/img/20-12-0bd7439b-78c7-4db4-b8a2-bc19aa4945c2.png)

**Comment by weinand** [comment]
@connor4312 perfect, thanks a lot!

**Comment by weinand** [comment]
cool, js-debug no longer prevents me from debugging:

<img width="1087" alt="2021-01-27_11-05-58" src="https://user-images.githubusercontent.com/1898161/105975880-c795b880-608f-11eb-8312-aa40466ffd8d.png">
