### ISSUE TITLE
Show detailed progress while copying single folder

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111625]
Testing #111250

- Drag and Drop a single folder into explorer and choose copy
- Progress notification shows copying folder...

![image](https://user-images.githubusercontent.com/10746682/100749721-54e8c380-33e5-11eb-899b-4487526d96cb.png)

It would be nice if you can show detailed progress like how finder does

![image](https://user-images.githubusercontent.com/10746682/100749969-ae50f280-33e5-11eb-9e0e-fdf092c00707.png)

User can also cancel this operation if wanted

**Comment by isidorn** [comment]
Agree with this 100% that it would be awesome to have, however for now closing as dup of https://github.com/microsoft/vscode/issues/111580
As it would require the same thing on the FS layer.
