### ISSUE TITLE
My code highlights and comments are abnormal

### ISSUE THREAD

**Issue by 363797271** [microsoft/vscode#111695]
Hello, I found the code highlight exception when I wrote demo.

Then it turns out that the annotation shortcut (` Ctrl + / ') is not working as well.

Is this caused by vscode or extension?

> 你好，我编写demo的时候发现代码高亮异常。
> 接着发现注释快捷键（`ctrl + /` ） 效果也不对。
> 请问这是 vscode 还是扩展造成的？

![image](https://img-blog.csdnimg.cn/2020111717302746.gif#pic_center)

**Comment by 363797271** [comment]
I tried to disable the extensions in turn.

When Babel JavaScript (vscode language Babel) is disabled, the highlight is normal.

But the annotation problem still exists

> 我尝试将扩展依次禁用。
> 当禁用 Babel JavaScript(vscode-language-babel) 后，高亮显示正常。
> 但是注释问题依然存在

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example?
