### ISSUE TITLE
git.api.getRemoteSources argument clarification

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#111651]
Testing #111518

I found 'providerLabel' and 'urlLabel' both confusing concepts for this command, I didn't understand what was going to be displayed in the UI. 'providerLabel' was especially strange to me, since as the caller of the command, I don't have much insight into what providers are available, and I didn't know why the provider itself wouldn't specify a label. I think I just need an example of when the caller would need to be able to tweak these labels

**Comment by joaomoreno** [comment]
This command isn't really meant to be used outside, but as tight integration with some other features like devcontainers. No big need to document it fully, but thanks for the feedback!
