### ISSUE TITLE
Open Editor Sorting - provide feedback during dnd

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#111623]
Testing #110482

When dragging an open editor from one group to another, it would be nice to indicate to the user a valid drop target - maybe changing the background of the target editor group. It would also be nice to indicate that they cannot drop the editor onto the editor group to which the editor belongs.

The current editor group is an invalid drop target only if the open editors are sorted alphabetically.

**Comment by isidorn** [comment]
Good suggestion, however nothing for endgame.
Assigning to December so I investigate more in debt week. Thanks

**Comment by isidorn** [comment]
Since we have hidden the Open Editors view by default I would not add new features to it atm. Thus closing this as out of scope
