### ISSUE TITLE
Search field breaks page layout

### ISSUE THREAD

**Issue by makemefeelgr8** [microsoft/vscode#111622]
Issue Type: <b>Bug</b>

1. Display 2 files in split screen mode
2. Click ctrl+F to open search
3. Scroll to the very top using scroll wheel
4. Take a look at the red arrow on the screenshot:
![details](https://user-images.githubusercontent.com/39099842/100748134-a005d500-33eb-11eb-9383-7545e89e8002.png)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IllusionMH** [comment]
This is intentional so you would be able to see content of first 1-3 lines (you can expand this widget even more for replace).
