### ISSUE TITLE
workbench.startupEditor setting not showing Getting Started tab

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#111699]
Testing #111554

Trying out with the setting "workbench.startupEditor": "gettingStarted". Opening up a new window shows a blank window for me, no Getting Started tab. 

![recording](https://user-images.githubusercontent.com/9721254/100822807-048f5700-3421-11eb-999e-4dd5489bc368.gif)

**Comment by JacksonKearl** [comment]
Thanks!
