### ISSUE TITLE
string literal does not work with status bar item [background] color

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#111687]
Testing #111423

https://github.com/microsoft/vscode/issues/111423#issuecomment-736887601

**Comment by gjsjohnmurray** [comment]
I think you should do it like this

https://github.com/microsoft/vscode/issues/111618#issuecomment-736557773

**Comment by bpasero** [comment]
String is for when you pass a color, which is unsupported here.

**Comment by sbatten** [comment]
@bpasero ah, I see. I think this is a doc bug then. I ended up having both the foreground and background set with string because `color` accepts a string and neither have text indicating that string is only used for colors. Also the `backgroundColor` description says "when setting the background color to `statusBarItem.errorBackground`" which makes me think string literal even if it is not allowed. Not sure why my build task was not reporting errors though.

**Comment by bpasero** [comment]
Fair, changed the JSDoc to:

```ts
export interface StatusBarItem {

	/**
	 * The background color for this entry.
	 *
	 * Note: only `new ThemeColor('statusBarItem.errorBackground')` is
	 * supported for now. More background colors may be supported in the
	 * future.
	 *
	 * Note: when a background color is set, the statusbar may override
	 * the `color` choice to ensure the entry is readable in all themes.
	 */
	backgroundColor: ThemeColor | undefined;
}
```
