### ISSUE TITLE
Web: No progress is shown while copying folder into explorer

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111627]
Testing #111250

- Use Web selfhost set up
- Drag and drop a large folder

🐛 No progress is shown

![Kapture 2020-12-01 at 15 15 48](https://user-images.githubusercontent.com/10746682/100751941-3e903700-33e8-11eb-83f0-c7962d9d5f8e.gif)

**Comment by sandy081** [comment]
Could be a duplicate of https://github.com/microsoft/vscode/issues/111583 ?

**Comment by isidorn** [comment]
Yeah, closing as dupe, thanks for finding the duplicate
