### ISSUE TITLE
findInWorkspace does not always update search term

### ISSUE THREAD

**Issue by bacuffe1** [microsoft/vscode#111634]
Issue Type: <b>Bug</b>

1) Have setting "Search: Seed On Focus" ticked
2) Have "findInWorkspace" bound to a keystroke
3) Perform a findInWorkspace search (that produces results)
4) Click on an entry in the search results (changes focus to the source file with the result)
5) Single-click on a another symbol in the newly-focused file
6) Hit the keystroke for "findInWorkspace" : SEARCH pane is now focused but search term is not the new symbol, it remains at the old / first one <this is the bug, it should have updated to the symbol single-clicked in 5 above >

Repeating steps 5 and 6 at this point give expected behaviour (search term updated and in focus for [enter] to start the search)

Note : steps 1 and 2 may or may not be required - these are settings I have in place.
Note : 6 months or more ago, this used to work as expected (not sure at what point it changed)

Is this some stale setting that I have ? How could I tell?
Or actual intended behaviour (in which case I would like a setting to disable it :-) )

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 4.19.0-12-amd64
Remote OS version: Linux x64 4.19.0-11-amd64
Remote OS version: Linux x64 4.19.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|7.70GB (0.12GB free)|
|Process Argv|--unity-launch --crash-reporter-id e9d0359a-2d75-43e7-90c0-927a321abba0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: 10.130.33.21|
|OS|Linux x64 4.19.0-11-amd64|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor (24 x 2195)|
|Memory (System)|62.84GB (2.03GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.130.33.21|
|OS|Linux x64 4.19.0-11-amd64|
|CPUs|AMD Ryzen 9 3900XT 12-Core Processor (24 x 2195)|
|Memory (System)|62.84GB (2.03GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.56.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
devicetree|plo|0.1.1
diff|raf|0.0.1
code-settings-sync|Sha|3.4.3
code-gnu-global|aus|0.2.2
git-easy|bib|1.11.0
githistory|don|0.6.14
gitlens|eam|11.0.6
bitbake|Eug|1.1.2
vscode-favorites|how|1.8.3
githd|hui|2.2.4
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.392013122
cpptools|ms-|1.1.2
vscode-make|tec|1.0.2
gitblame|wad|6.0.0

</details>

**Comment by roblourens** [comment]
I think you also need `search.seedWithNearestWord` enabled

**Comment by bacuffe1** [comment]
Hi Rob, thanks for looking.

Confirmed : "Search: Seed With Nearest Word" was also ticked.
I experimented with disabling it and re-enabling it - neither action made any difference to the described behaviour.
keybindings and settings attached, do you want any others?
[User.zip](https://github.com/microsoft/vscode/files/5628441/User.zip)

**Comment by roblourens** [comment]
It seems like this is by design in this command. It's designed to be invoked from the context menu in the files explorer, not to be used via keybinding in the editor. You probably just want the basic `workbench.view.search`

**Comment by bacuffe1** [comment]
You're right, I did. (and it doesn't wait for a [enter] to start searching - nice :-) )
I _did_ have to remove the default "when" condition though (my search output pane is always visible)
Thanks Rob
