### ISSUE TITLE
Can't attach debugger to extension host

### ISSUE THREAD

**Issue by ffMathy** [microsoft/vscode#111656]
Issue Type: <b>Bug</b>

I ran `yo code` to generate a new extension.

Chose "typescript", "webpack", called it "pruner" (both identifier and product name), chose "npm".

However, when I hit F5, the extension window does indeed launch, but my breakpoint isn't being hit, and I don't see the "Congratulations" message of the template in my Debug Console.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (17.22GB free)|
|Process Argv|--crash-reporter-id a60ec61b-5d8e-4b93-a86d-f923a81e01be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-titanium|Axw|0.10.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
tsl-problem-matcher|eam|0.3.1
vs-sharper|ese|0.2.0
vscode-solution-explorer|fer|0.3.11
vscode-jest-runner|fir|0.4.31
dotnet-test-explorer|for|0.7.4
vscode-test-explorer|hbe|2.19.3
ilspy-vscode|ics|0.9.0
error-gutters|Igo|1.0.1
dotnet|leo|1.3.0
vscode-cosmosdb|ms-|0.15.0
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.6
vscode-edge-devtools|ms-|1.1.1
remote-containers|ms-|0.148.1
remote-wsl|ms-|0.51.4
azure-account|ms-|0.9.4
powershell|ms-|2020.6.0
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.3206
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vscode-json-editor|nic|0.2.3
vscode-nuget-gallery|pat|0.0.23
vscode-versionlens|pfl|1.0.9
vscode-yaml|red|0.13.0
csharp-helper|roa|0.0.14
code-complexity-report-generator|sel|1.1.7
vscode-autohide|sir|1.0.7
swdc-vscode|sof|2.3.21
sonarlint-vscode|Son|1.18.0
vscode-taskexplorer|spm|1.27.0
tech-debt-tracker|Ste|0.27.5
sass-indented|syl|1.8.13
vscode-counter|uct|2.2.0
errorlens|use|3.2.4
vz-file-templates|vis|1.0.3
quokka-vscode|Wal|1.0.331
zoombar-vscode|wra|1.4.0

</details>

**Comment by ffMathy** [comment]
It should be mentioned that I tried with many different combinations of choices in `yo code`. All of them were TypeScript though. But I tried with and without webpack for instance.

**Comment by ffMathy** [comment]
Alright, here are the logs that were produced after letting it run for a while. A brand new `yo code` project.

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5631175/vscode-debugadapter-0.json.gz)
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode/files/5631176/vscode-debugadapter-1.json.gz)

**Comment by ffMathy** [comment]
cc @connor4312

**Comment by connor4312** [comment]
It doesn't look like your extension is activated -- no scripts in the `pruner-foo` repo are loaded by the extension host. Are you running the `Hello World` command?

**Comment by ffMathy** [comment]
The command is not even present 😅

**Comment by ffMathy** [comment]
Could it be that some of my extensions are blocking it?

Would it make sense if the extension host was clean and ONLY tried to load the extension I am debugging?

**Comment by ffMathy** [comment]
I also tried it on my work machine now, same result (although the same extensions are installed with that machine via settings sync).

Where to go from here?

**Comment by connor4312** [comment]
You might find the [Your First Extension](https://code.visualstudio.com/api/get-started/your-first-extension) doc useful. We also have a community on StackOverflow and [on Slack](https://aka.ms/vscode-dev-community) who might be able to give you general pointers/guidance if you run into things.

Closing this for now since it doesn't seem to be debug related.

**Comment by ffMathy** [comment]
How come it's not debug related when I can't attach a debugger on a freshly created extension project from your own template?

**Comment by ffMathy** [comment]
Cc @connor4312

**Comment by ffMathy** [comment]
I can repro on 3 different computers. Just follow the steps. I'm sure you'll be able to repro as well. No breakpoints are being hit. So why close the issue?

**Comment by weinand** [comment]
@ffMathy if the "Hello World" command is not available in the new VS Code instance, then the problem is before "debugging"...
On what platform are you?

**Comment by weinand** [comment]
Oh I see, Windows...

**Comment by weinand** [comment]
In the meantime: please try to run and debug your extension with all extensions disabled. Does it make a difference?

**Comment by weinand** [comment]
@ffMathy I cannot reproduce the issue.

What I did:

- on Windows 10 updated "yo" to the latest with "npm install -g yo generator-code"
- "yo code" with "typescript", "webpack", called it "pruner" (both identifier and product name), chose "npm".
- "cd pruner"
- "code ."
- noticed problem in problems viewer and opened launch.json
- installed recommended extension ("ESLint" and "TypeScript + Webpack Problem Matchers")
- opened "extension.ts" and set breakpoints in line 11 and 20
- "F5"
- another VS Code window opened
- "F1" and started typing "hello..."
- selected "Hello World" action
- breakpoint in line 11 in first VS Code window was hit.
- pressed continue button twice: "hello" notification showed up.

![2020-12-04_12-11-47 (1)](https://user-images.githubusercontent.com/1898161/101158453-07aa6300-362c-11eb-9777-c903c992ed67.gif)

**Comment by ffMathy** [comment]
Thank you so much for this. I did the same, no luck. It MUST be my extensions then.

Is there a smart way to make the extension host version ONLY load my extension, ignoring all others?

**Comment by weinand** [comment]
@ffMathy you can just add the "--disable-extensions" argument to the launch config:

```js
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--disable-extensions",
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
```

**Comment by ffMathy** [comment]
Great! I'll try that. I think this is worth mentioning in the documentation though, or perhaps even enable as default.

People are typically only interested in testing their own extension. Why even allow the possibility of an external failure?

**Comment by weinand** [comment]
- all command line options of VS Code (see "code --help") can be used for extension development. 
- the "normal" behavior of VS Code is to use the installed extensions automatically for every new window. For extension development we do not want to provide a different behavior.

**Comment by ffMathy** [comment]
@weinand I tried `--disable-extensions`, but then it seems my installed extension is also disabled?

What I'd love to be able to do, is disable all extensions *except* the one I'm developing.

Is that possible?

**Comment by ffMathy** [comment]
Hmmm apparently `--disable-extensions` is not supposed to disable the existing extension, so I suppose it's still just not working in general.

We still have a problem. I can't attach a debugger on 3 different Windows machines, I tried disabling all extensions, and I tried a fresh install of VS Code.

**Comment by ffMathy** [comment]
Can we re-open the issue?

**Comment by ffMathy** [comment]
I am an idiot...

I did not see that there was an extension "activation event".

It would be awesome if the default activation event was to load on startup though, or make it more clear in the documentation that the extension itself won't be loaded.

I was under the impression that the extension would load, but the function for the handler wouldn't run until the command ran.

**Comment by weinand** [comment]
@ffMathy the activation event is mentioned as the first item here:
https://code.visualstudio.com/api/get-started/extension-anatomy
