### ISSUE TITLE
Consider removing the "..." from "Edit condition..."

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111601]
Testing #111425

This feels like an action similar to the "Rename" action in the explorer, or the "Change Local Port" action in the ports view. Neither of those have "...".

**Comment by isidorn** [comment]
Agree. Thanks for feedback.

**Comment by isidorn** [comment]
Changed this.
I think for the future the pattern with `...` should be: that we add them when additional input is required from a not so connected place - for example quick pick.

fyi @bpasero and @misolori for thoughts on when to use `...` at end of action labels

**Comment by bpasero** [comment]
@isidorn I would not come up with our own principle here but make sure we adhere to existing UX guidelines such as https://docs.microsoft.com/en-us/windows/win32/uxguide/cmd-menus#using-ellipses. A "..." for me indicates that clicking the action literally does nothing until I have provided further input. It does not matter where I provide this input.

From the guidelines:

> Proper use of ellipses is important to indicate that users can make further choices before performing the action, or even cancel the action entirely. The visual cue offered by an ellipsis allows users to explore your software without fear.

**Comment by misolori** [comment]
If it requires input from the user, there should always be a `...` as we already do that in several places:

<img width="400" src="https://user-images.githubusercontent.com/35271042/101695992-3fe5e300-3a2a-11eb-814f-28927d47e495.png">

<img width="400" src="https://user-images.githubusercontent.com/35271042/101696011-48d6b480-3a2a-11eb-9d9f-8fb4ee6c604b.png">

**Comment by isidorn** [comment]
I believe we have some inconsitencies, for Example 
New File, New Folder, Rename in Explorer

Maybe we should do a pass and clean this up..

**Comment by bpasero** [comment]
Yes they should have a "...".
