### ISSUE TITLE
VS Code should open file in a last focused window

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#111620]
Testing #111420

1. `window.restoreWindow: preserve`
2. Open multiple windows
3. Exit
4. From command line open VS Code with passing a file that does not belong to any of the opened windowss
5. File gets open in a random window :bug: 

I thin file should open in a window that had last focus. 
If we behaved like this the setting description could also have a bit more clarity

**Comment by bpasero** [comment]
I will merge this into https://github.com/microsoft/vscode/issues/111605 because the fix is related.

**Comment by isidorn** [comment]
Makes sense, thanks.
