### ISSUE TITLE
git.api.getRemoteSources doesn't wait for providers to activate

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#111658]
Testing #111518

To get the GitHub picker to show up, I had to explicitly wait for the `github` extension to activate:
```
	const githubExtension = await vscode.extensions.getExtension('vscode.github');
	if (githubExtension) {
		await githubExtension.activate();
	}

	const results = await vscode.commands.executeCommand('git.api.getRemoteSources', {
		providerLabel: (provider: RemoteSourceProvider) => `Testing the branch picker of ${provider.name}`,
		urlLabel: `URL`,
		branch: true
	});
```

It would be cool if running 'git.api.getRemoteSources' triggered an activation event that extensions providing these sources could use.

**Comment by joaomoreno** [comment]
Yeah this is a long standing issue with this approach, but one which we don't really have an answer for, unfortunately.
