### ISSUE TITLE
Unable to undo folder copy

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111657]
Testing #111015

Folder structure:

```
- github
  - a.txt
- sample
  - b.txt
```

* Copy folder `sample`
* Paste into `github`
* `cmd+z` throws error `Unable to delete non-empty folder '/Users/penlv/code/prototype/notebook-test/github/sample'.`

**Comment by isidorn** [comment]
Good catch, I can repro.

**Comment by isidorn** [comment]
Pushed a fix, however please be aware of this limitation https://github.com/microsoft/vscode/issues/111022
