### ISSUE TITLE
'vscode.open' label effects all editors with the file

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#111689]
Testing #111421

1. Using the FS Provider sample
1. Add a new command call `memfs.hello` that does the following:

```ts
context.subscriptions.push(vscode.commands.registerCommand('memfs.hello', _ => {
        vscode.commands.executeCommand('vscode.open', vscode.window.activeTextEditor!.document.uri, vscode.ViewColumn.Beside, 'xxx');
    }));
```

3. Open any file from memfs
4. Run the command

**Potential bug**
Two editors should be open. However the title on both of them is now `xxx`. 

I expected that only the editor opened using `vscode.open` would use the new label (although this behavior may be by-design)

**Comment by bpasero** [comment]
Yeah by design, all file editor inputs are actually shared across all open editors. This is a limitation I cannot easily resolve and I think should be fine.
