### ISSUE TITLE
Extension bisect wording

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#111667]
Testing #111495

Wording here feels a bit odd to me:
![image](https://user-images.githubusercontent.com/8586769/100790370-8b661480-33cc-11eb-97b1-1fe6aef5e190.png)

For fun tried pugging into GPT-3 and it suggests "Are you still seeing the problem for which you started an extension bisect?"  🤷‍♀️
![image](https://user-images.githubusercontent.com/8586769/100790427-9f117b00-33cc-11eb-95a0-ac3e88cf4cf5.png)

Maybe "Are you still seeing the problem for which you started the extension bisect?"

**Comment by jrieken** [comment]
<img width="765" alt="Screenshot 2020-12-02 at 11 29 25" src="https://user-images.githubusercontent.com/1794099/100861160-bb2b2000-3491-11eb-9b2b-13a6e91234f3.png">

I now reusing the message from the notification that shows after window reload.
