### ISSUE TITLE
Clicking issue from output of GitHub Issues notebook loses blue border around focused cell

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#111663]
Testing #111552, with a closer look at last checked item in https://github.com/microsoft/vscode/issues/109549 (clicking on an issue in cell output and navigating back to VS Code).

Focus on a cell and run it:

![image](https://user-images.githubusercontent.com/25310137/100781567-0bd24880-33c0-11eb-9870-adb5c9da0f17.png)

Click on an issue from its output

Return to VS Code, looks like focus on the cell was lost:

![image](https://user-images.githubusercontent.com/25310137/100781641-21e00900-33c0-11eb-98e8-e18ce1f9ab5c.png)

However, I tried changing language mode, and it successfully picked up that cell and changed it to markdown:

![image](https://user-images.githubusercontent.com/25310137/100785341-5b674300-33c5-11eb-8a3a-75eb9f51614a.png)

Could we indicate focus on this cell (/when users interact with or click on the output area) in some way? i.e. still include the blue border around the cell, or some sort of border/shading around the output?

**Comment by misolori** [comment]
@rebornix we seem to add a class `cell-output-hover` on `cell-inner-container`. If we could add a similar class for when the output has focus, we can tweak the focus rules and give the cell focus.

**Comment by rebornix** [comment]
@misolori I added the output focus class, anything else we need https://github.com/microsoft/vscode/commit/412f45fa80a35f9dd6f5f1336e0415e099ab43c8 ?

**Comment by rebornix** [comment]
Fixed now.
