### ISSUE TITLE
Seeing disconnect action when debugging extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11163]
- Start debugging
- Press `Stop` before the window shows up

![image](https://cloud.githubusercontent.com/assets/22350/18080877/8e7a16fc-6e97-11e6-864e-a7d1b2ad379d.png)

We should have the `Stop` action there instead.

**Comment by weinand** [comment]
Since the stop button really kills the extension host window, we should not use the 'disconnect' hover text and the crossed-plug icon but show the red square.
