### ISSUE TITLE
Optimize autosave message when changing settings

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#111648]
Testing #111330

On step 2, I set `terminal.integrated.sendKeybindingsToShell` to true.

I got a toast notification, "Your changes are automatically saved as you edit."

![image](https://user-images.githubusercontent.com/25310137/100772618-b0e72400-33b4-11eb-9e49-4036814e8833.png)

At first glance, this would seem to be a way to tell me I have autosave on in general (which I don't).

![image](https://user-images.githubusercontent.com/25310137/100775217-d32e7100-33b7-11eb-89e3-083a7e32b943.png)

I had figured this notification came from changing the terminal setting since that was the only work I was doing, but it might be nice to be a bit more explicit so that users definitely know what changes are being automatically saved, i.e. wording it in a way like, "Your **_settings_** changes are automatically saved as you edit."

@meganrogge Although this is your test plan item, I'm not sure who might approach the notification wording if we decided that's something we'd want to address.

**Comment by meganrogge** [comment]
Hey Brigit, thanks for bringing this to my attention. Git Lens indicates @JacksonKearl added this notification, so let's see what he thinks.

**Comment by JacksonKearl** [comment]
Will go with "Changes to settings are saved automatically" as suggested in the original issue. (https://github.com/microsoft/vscode/issues/57033)

**Comment by JacksonKearl** [comment]
Thanks for reporting!
