### ISSUE TITLE
Missing iconDefinitions hints for debug-alt and debug-alt-small

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#111691]
Testing #111551

`debug-alt` and `debug-alt-small` are available properties for `iconDefinitions` but don't offer any hint.

<img width="285" alt="Screen Shot 2020-12-01 at 5 31 39 PM" src="https://user-images.githubusercontent.com/8599/100816522-1bbb4e00-33fb-11eb-9ea9-b79ad69a0d18.png">

**Comment by aeschli** [comment]
`debug-alt` and `debug-alt-small ` are no longer used by our UI but only around for background compatibility in case an external extension still uses it.
