### ISSUE TITLE
Background always dark after upgrading to OSX Big Sur

### ISSUE THREAD

**Issue by AnthonyChiavelli** [microsoft/vscode#111645]
- VSCode Version: 1.51.1
- OS Version: Big Sur (11.0.1 (20B50))

Steps to Reproduce:

1. Upgrade to Big Sur (11.0.1)
2. Wait some time (or maybe just until your first post-install system restart)
3. Open vscode and try to use a light theme

Basically, the background colors remain dark* no matter what theme is chosen, while the text and highlight colors correctly update. As a result, light themes are unusable (since they typically feature dark text, expecting a light background). My system is set globally to light mode, and this problem did NOT start happening immediately after my Big Sur upgrade, it took a day or two. 

*Aside from being dark, the backgrounds are semi-transparent (only when not in a full screen window, and when focused) 

I've seen the recent dark font issue, and this almost seems to be an inverse of that.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/1650435/100771297-44781f00-33cc-11eb-8802-712e822efaad.png)

**Comment by AnthonyReid99** [comment]
Update: Upon opening a new project, my background colors have now become _grey_, except my current line, which is rendered white...

**Comment by deepak1556** [comment]
Does stating code with `--disable-gpu` help ?

**Comment by AnthonyReid99** [comment]
It does not :(

**Comment by deepak1556** [comment]
Can you try forcing a color profile following https://github.com/microsoft/vscode/issues/106756#issuecomment-722494532

**Comment by AnthonyReid99** [comment]
Just tried, none of those worked

**Comment by itkfm** [comment]
> Just tried, none of those worked

There's a chance that `--force-color-profile <value>` is somewhat be broken. For me it seems to always produce the same result as putting `"force-color-profile": "srgb"` into `argv.json`.

See: https://github.com/microsoft/vscode/issues/106756#issuecomment-724720529
