### ISSUE TITLE
DnD to copy folders end with an error

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111606]
Testing #111250

Platform: Mac

- Drag n drop a folder into explorer (copy the folder)
- Folder is copied but at the end an error is shown

![Kapture 2020-12-01 at 14 21 43](https://user-images.githubusercontent.com/10746682/100746187-aa6ea180-33e0-11eb-8211-b63c9a2f53fe.gif)

- Undo (cmd+z) the operation fails with following error

![image](https://user-images.githubusercontent.com/10746682/100746331-db4ed680-33e0-11eb-988a-9c35daf70be6.png)

**Comment by isidorn** [comment]
This has been fixed via 2 independent issues https://github.com/microsoft/vscode/issues/111581 and https://github.com/microsoft/vscode/issues/111657
