### ISSUE TITLE
Features > Search > Show Line Numbers setting is ignored

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#111696]
- VSCode/OS Version:
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Datum: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

![Search Show Line Numbers is ignored](https://user-images.githubusercontent.com/9283914/100820661-f821f300-344e-11eb-9315-23fb04204657.gif)

**Comment by IllusionMH** [comment]
I'm not sure if Search results are rerendered on settings change. Do you see line number if you run search again after enabling this setting?

**Comment by roblourens** [comment]
You have to rerun the search to rerender results

**Comment by SetTrend** [comment]
Thanks, @IllusionMH and @roblourens!

Sorry for my late reply. I've been busy the other day.

I was looking for the change to appear in the extra Search editor (shown at the bottom editor group in my screencast). That's where I first ran a new search when I reported this issue.

**Comment by roblourens** [comment]
I see, that setting only affects the search view in the sidebar, not the search editor. But you should be able to disable line numbers in the search editor with the normal editor line numbers setting, and you can set it per-language to scope it to the search editor if you want.

**Comment by SetTrend** [comment]
Thank you, @roblourens.

How can I set the visibility of line numbers per language? I disabled line numbers at `editor.lineNumbers": "off",`. Still, the Search editor displays line numbers:

![Search editor](https://user-images.githubusercontent.com/9283914/101094643-042bc300-35bd-11eb-976f-db1d25a9f505.png)
<br/>

Actually, considering the Search editor design ... I would have proposed a more tight design, resembling the layout of Araxis Merge: I'd have proposed to omit the blank line and instead add a separator line between found ranges:

![Search editor proposal](https://user-images.githubusercontent.com/9283914/101096805-633f0700-35c0-11eb-95ba-e55127ee8b82.gif)

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings

**Comment by SetTrend** [comment]
I read that documentation. But that won't have influence on the Search editor, will it?

**Comment by roblourens** [comment]
I thought that 

```json
    "[search-result]": {
        "editor.lineNumbers": "off"
    },
```
would do it, but I guess not, is there a way to disable line numbers in the search editor @JacksonKearl ?

**Comment by JacksonKearl** [comment]
No, they're used for determining the match location.
