### ISSUE TITLE
Error while trying to paste in explorer

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111602]
Testing #111250

On Mac OS

- Try to copy (cmd+c) a folder from finder and paste (cmd+v) into explorer

🐛 Following error is shown

![Kapture 2020-12-01 at 14 16 33](https://user-images.githubusercontent.com/10746682/100745757-0c7ad700-33e0-11eb-9755-d9b3511dd384.gif)

**Comment by isidorn** [comment]
This was never working, however previously we were alos not throwing an error - just silently failing. So I will go back to that behavior.

For Cmd+C working from Finder to VS Code there is already a Feature Request open for this
