### ISSUE TITLE
Tree hover gets too large

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111608]
Testing #111515

* have resolve call that return much data, like our README file
* hover over the a tree item
* 🧀 the hover bleeds into the title widget, inheriting the mac window controls

In the editor land (hover, suggest) we pad things with 22px 

<img width="566" alt="Screenshot 2020-12-01 at 14 24 38" src="https://user-images.githubusercontent.com/1794099/100746596-34b70580-33e1-11eb-89b6-f63af2a0d0d7.png">

**Comment by alexr00** [comment]
We'll wait for @Tyriar for this one.

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/101865
