### ISSUE TITLE
vscode.SymbolKind.Constant has no icon in Show All Symbols

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11171]
Testing #11113

![image](https://cloud.githubusercontent.com/assets/22350/18082204/1998ce1c-6e9e-11e6-8908-f1cf32081758.png)

**Comment by jrieken** [comment]
We actually don't have an icon for that...

**Comment by joaomoreno** [comment]
To the issue resolver: please check all types, while you're at it. :)

**Comment by bgashler1** [comment]
FYI @chryw

**Comment by bgashler1** [comment]
Here is the asset
[Constant_icon.zip](https://github.com/Microsoft/vscode/files/446018/Constant_icon.zip)

**Comment by jrieken** [comment]
Thanks @bgashler1!
