### ISSUE TITLE
Customize field naming convention

### ISSUE THREAD

**Issue by marlongerson** [microsoft/vscode#111778]
In C#, I would like to be able to customize the format of my automatically generated private fields. While others use `this.` to prefix their private fields, I would like to be able to customize vs code so that it generates my private fields with an underscore `_`. Does vs code have this feature built in? I have only seen it capable via editorconfig plugin, but it would be nice if vscode supports this out of the box. Perhaps a user setting text field like `"_$(var)"` or `"this.$(var)"` that provides the string format.

<img src="https://i.imgur.com/Xrz59bX.png">

<img src="https://i.imgur.com/s2dz32o.png">

**Comment by yume-chan** [comment]
These code actions are provided by the [C# extension](https://github.com/OmniSharp/omnisharp-vscode/issues), please file an issue there.
