### ISSUE TITLE
Each time saving a file editor zooms out!

### ISSUE THREAD

**Issue by SantoshV01** [microsoft/vscode#111790]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I'm working on a project when ever i want to save a file with vs code editor with "ctrl+s", the code editor zooms out.
2. This is too annoying, please fix this bug.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
