### ISSUE TITLE
"Find in files" during a liveshare not returning all results until files are manually opened

### ISSUE THREAD

**Issue by afernando79** [microsoft/vscode#111799]
Issue Type: <b>Bug</b>

Find in files
Enter text that exists in many files within the shared session's code
Review results -> some missing as host of liveshare demonstrates using screen share

Open file(s) manually and perform search, text is then found.

VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:36:22.965Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (0.52GB free)|
|Process Argv|--crash-reporter-id 32465e51-92f2-4834-81bd-bf50d547ab10|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|Memory (System)|7.77GB (2.21GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|Memory (System)|7.77GB (2.21GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker-syntax|dun|0.1.5
intellij-idea-keybindings|k--|0.2.41
remote-wsl|ms-|0.52.0
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
vscode-docker|ms-|1.8.1
python|ms-|2020.12.394869726-dev
vscode-pylance|ms-|2020.12.0
jupyter|ms-|2020.11.392013122
vsliveshare|ms-|1.0.3206

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please report at https://github.com/MicrosoftDocs/live-share
