### ISSUE TITLE
CTRL+F3 does not work on selections spanning multiple lines

### ISSUE THREAD

**Issue by jan11011977** [microsoft/vscode#111740]
Issue Type: <b>Bug</b>

1. Select multiple lines of text
2. Press CTRL+F3
3. VSCode does not search for the selected text, but repeats the most recent search instead

Another way to repro:

1. Select multiple lines of text
2. Press CTRL+F
3. Note that the multiple lines of text have not been populated into the CTRL+F dialog

As an aside, if you press CTRL+D followed by CTRL+F, that does populate the search box with the multiple lines. This shows that it is possible to search for multiple lines, it's just that the populating of the dialog appears to be broken.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2175 CPU @ 2.50GHz (28 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (45.82GB free)|
|Process Argv|d:\\coredev\\game\\bin\\s4_compass.code-workspace --crash-reporter-id 86f3fb0b-b0e3-4c97-9947-af81c4bbd013|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
selected-lines-count|gur|1.4.0
restructuredtext|lex|129.0.0
perforce|mjc|4.14.0
vscode-docker|ms-|1.8.1
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.11.2
jupyter|ms-|2020.11.392013122
remote-containers|ms-|0.148.1
remote-wsl|ms-|0.51.4
powershell|ms-|2020.6.0
hide-gitignored|npx|1.1.0
vscode-yaml|red|0.13.0
partial-diff|ryu|1.4.1
jinjahtml|sam|0.15.0

</details>

**Comment by boltex** [comment]
I also am an extension developer, and since the last version (1.60 or 1.61 not sure) the F3 keybinding is sometimes buggy: coming from the focus in a webview in the sidebar, the F3 (repeat find) default vscode action has precedence over my custom keybinding for F3. But somehow, putting the focus in the treeview, then in the editor fixes it. 

It does not do that for other keybindings with the same context 'when' conditions. only for F3 so far as i can see.
