### ISSUE TITLE
Quick open perform slow when includeSymbols settings is true

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11177]
Testing #11106
Steps to Reproduce:

Set up:
```
"search.quickOpen.includeSymbols": true
```

1. Open VS Code dev workspace. It has two files **editorStyles.ts** and **editorState.ts**
2. Open editorStyles.ts file
3. Quick Open => search for **editorS**

Observed: Quick open is slow - See the attached videos comparison

Insiders:

![aug-30-2016 11-12-49](https://cloud.githubusercontent.com/assets/10746682/18083329/fca8d50e-6ea2-11e6-91d3-e3f368e59577.gif)

Stable:

![aug-30-2016 11-14-09](https://cloud.githubusercontent.com/assets/10746682/18083342/075ea640-6ea3-11e6-9e52-d539275e04e7.gif)

**Comment by bpasero** [comment]
@sandy081 can you compare the speed to the "Open Symbol" quick open (Cmd+T)?

**Comment by bpasero** [comment]
This was caused by the symbol search to not run through a delayer as it does in the Cmd+T case. Somehow hammering the language service with many requests makes it very slow. Now Cmd+P is using the same buffer if symbol results are included.
