### ISSUE TITLE
VS code uninstalled itself completely on closing open windows?! 

### ISSUE THREAD

**Issue by shaunakv1** [microsoft/vscode#111704]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. VS Code is uninstalling itself automatically! This keeps happening yet someone closed this ticket with all the people complaining #93072 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
