### ISSUE TITLE
Please include proper multilevel macro expansion

### ISSUE THREAD

**Issue by yysh12** [microsoft/vscode#111789]
Please include multilevel macro expansion

e.g. 
#define WITHIN(N,L,H)       ((N) >= (L) && (N) <= (H))
#define NEAR_ZERO(x) WITHIN(x, -0.000001f, 0.000001f)

when I hover over "NEAR_ZERO(angular_travel)"  
I currently get:
WITHIN(angular_travel, -0.000001f, 0.000001f)
But I want to get:
(angular_travel) >= (-0.000001f) && (angular_travel) <= (0.000001f)

Please this is a must have feature. I am working on the marlin firmware project and they use a TON of macros embedded in macros. Currently it is completely impossible to go through the code without some sort of feature like this.

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode-cpptools/issues/4970 but you didn't say what language you are coding in.

**Comment by yysh12** [comment]
I am coding in c++ using the gcc compiler on ubuntu.

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please raise this on the extension's repository.

**Comment by yysh12** [comment]
Would you happen to know which extension it is? I'm totally new to vscode.

**Comment by gjsjohnmurray** [comment]
> 
> 
> Would you happen to know which extension it is? I'm totally new to vscode.

I think the repo I previously pointed you to is the correct one:

https://github.com/microsoft/vscode-cpptools/issues/

Rather than opening a new issue I suggest you comment on the one I linked to earlier.

**Comment by yysh12** [comment]
Awesome thanks!
