### ISSUE TITLE
Extension editor is not opening

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111732]
Running from sources

- Go to extensions view and click on an extension

🐛 Extension editor is not opening

**Comment by sandy081** [comment]
Seems caused by the fix - https://github.com/microsoft/vscode/issues/111496

**Comment by joaomoreno** [comment]
Sorry about that @sandy081

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/111733
