### ISSUE TITLE
Mixing resolveTreeItem and onDidChangeTreeData leads to TreeItem corruption

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111715]
Testing #111515

In `resolveTreeItem`, after a possibly long running operation, I am firing an `onDidChangeTreeData` for the resolved item (after a 50ms `setTimeout`). And I am seeing tooltips for many items swapped around or duplicated. It seems like there is some internal data corruption in the tracking of which resolve goes with which item or something.

You can see it in action using this branch of GitLens:
https://github.com/eamodio/vscode-gitlens/commits/feature/prs

Here is part of the relevant code:
https://github.com/eamodio/vscode-gitlens/blob/98cfe9da4ef78d7d33f4979d57f6806c83b0107a/src/views/nodes/commitNode.ts#L145-L154

**Comment by alexr00** [comment]
I think we said that you shouldn't call `onDidChangeTreeData` from `resolveTreeItem` when designing the API. I will update the comment, and see if I can ignore `onDidChangeTreeData` from within `resolveTreeItem`.

**Comment by eamodio** [comment]
Its in a `setTimeout`, so you won't be able to ignore it -- and it isn't really "within" the `resolveTreeItem` because of that either. So it should definitely not cause data to get mismatched/corrupted.

**Comment by alexr00** [comment]
> You can see it in action using this branch of GitLens:
https://github.com/eamodio/vscode-gitlens/commits/feature/prs

How do I repro with that branch?

**Comment by eamodio** [comment]
In the Commits view just hover over the commits and see that the commit message in the tooltips will not always match the commit message in the view

**Comment by alexr00** [comment]
I don't see the tooltip not matching, however I do see a nasty flicker: 
![recording (30)](https://user-images.githubusercontent.com/38270282/101177263-e6f00680-3647-11eb-959e-8a2f7c9021ce.gif)

**Comment by alexr00** [comment]
I'm no longer seeing this flicker. Closing for verification.
