### ISSUE TITLE
Extensions viewlet "Install from VSIX" doesn't let me choose a local folder when remote

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111746]
I was testing with Codespaces.

1. Connect to your remote
2. Have a VSIX locally that you want to install
3. Extensions viewlet -> ... menu -> Install from VSIX...
4. Expected: The simple file picker shows up and has a "Show Local" option to get to my local filesystem to get the VSIX
Actual: The simple file picker shows up, but doesn't let me get to my local filesystem.

@sandy081 if you already support local URIs here, then probably all you need to do is add `Schemas.file` to the `availableFilesystems` when you pop the file dialog.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/106914
