### ISSUE TITLE
Preserve command line arguments on subsequent windows even when changing folders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111766]
In my `launch.json`, I have `--disable-extension` specified in the `args`

https://github.com/eamodio/vscode-gitlens/blob/53c9a42886e455189577fc7bf99fdc5eed25ae5c/.vscode/launch.json#L51-L74

This works fine for the initial launch, but if I change workspaces/folders in the Extension Development Host window, the `--disable-extension` flag seems to get lost.

**Comment by sandy081** [comment]
@bpasero Assigning to you because it seems related to env args.

**Comment by bpasero** [comment]
My feeling is that we might need more tweaks similar to what we do in `reload`:

https://github.com/microsoft/vscode/blob/155691d0bec4acfac0e3bbccb362f61278a132de/src/vs/code/electron-main/window.ts#L750-L775

It is quite possible that none of the initial launch arguments are kept when changing folders in the target.

@weinand can you help me understanding how these args end up in the window? Are they literally passed as command line arguments when launching?

**Comment by weinand** [comment]
@bpasero VS Code receives the request to launch another instance of VS Code in "rawDebugSession.ts" from the debug extension and basically constructs a command line from the received arguments:

![2020-12-03_12-05-16](https://user-images.githubusercontent.com/1898161/101002545-52f73f80-3560-11eb-9288-118e7d412586.png)

Then we call `extensionHostDebugService.openExtensionDevelopmentHostWindow(...)` which is already in your land.

**Comment by bpasero** [comment]
This goes way beyond extension development: any command line arguments that are passed to a N+1 startup (not the first) is lost when you change folders. This is a bit similar to our recent fixes for preserving the shell environment even when you change folders I would say. But it could be risky to just blindly take over all the original CLI args to each folder, especially we could not take over the file/folder related arguments. And some arguments maybe only make sense for specific folders?

I am a bit too afraid to change this...

**Comment by eamodio** [comment]
Maybe we could identify a set of flags that we think should apply? 

Here is my list:
- `--disabled-extension`
- `--disabled-extensions`
- `--enable-proposed-api`
- `--disable-gpu`
- ` --inspect-extension`
- ` --inspect-brk-extension`
- `--log`
- `--max-memory`
- `--prof-startup`
- `--sync`
- `--telemetry`

**Comment by bpasero** [comment]
Yeah, some of them are already listed for the `reload` case:

https://github.com/microsoft/vscode/blob/c4d77ea6193e639dfad1431fe92a6c611d697a28/src/vs/code/electron-main/window.ts#L763-L769

Combining this logic for `reload` and `load` would make sense to me. If you feel strong, feel free to propose a PR.

**Comment by eamodio** [comment]
@bpasero I tried adding `disable-extension`, since I use that in GitLens and we use it in the GHPR extension, but I can't seem to get it to work. 

I see that there are multiple different code paths for what gets run depending on if you are using native dialogs, vs the simple dialog. In the simple dialog case, it doesn't even look like we use the args from the environment service. In the native case, we do, but that property doesn't get incorporated into the environment service or anything, so it only seems to survive into the `openExtensionDevelopmentHostWindow` call, which only seems to get called on the first launch of the exthost window.

Can you provide any more pointers?

**Comment by bpasero** [comment]
@eamodio as I said before, a `ICodeWindow` will be loaded with some configuration here from anywhere a window is either opened or reused:

https://github.com/microsoft/vscode/blob/c8ff3471b596a8a21e1f080f3f038e08ee148b6e/src/vs/code/electron-main/window.ts#L693-L693

If the window was loaded before (and thus is reused) you could be able to access the configuration of that window similar to how it is done here:

https://github.com/microsoft/vscode/blob/c8ff3471b596a8a21e1f080f3f038e08ee148b6e/src/vs/code/electron-main/window.ts#L700-L700

Currently we do not preserve any of the configuration of the window other than in this particular case for the process environment. If we want e.g. the `'disable-extension'` property to be saved and reused, we would need to explicitly copy it over into the new config, e.g. doing:

```ts
if (!Array.isArray(config['disable-extension'])) {
	config['disable-extension'] = (this.currentConfig ?? this.pendingLoadConfig)?.['disable-extension'];
}
```

This might be dangerous though in case `disable-extension` was set differently already for the open request (i.e. it may be `undefined` for a reason to not disable extensions anymore).

Maybe only if the window is for extension development, we would preserve some extension development related properties (there are probably more), e.g. looking at:

https://github.com/microsoft/vscode/blob/c8ff3471b596a8a21e1f080f3f038e08ee148b6e/src/vs/code/electron-main/window.ts#L782-L788
