### ISSUE TITLE
editorFocus returns true when output panel is focused.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#111755]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic

-Set a hotkey to only execute when 'editorFocus' is true.
-when panel problems view is focused the hotkey does not run as anticipated
-when terminal view is focused the hotkey does not run as anticipated
-when debug condole view is focused the hotkey does not run as anticipated
-when output is focused the hotkey does execute, indicating that editorFocus == true when output view is focused.

**Comment by rebornix** [comment]
The output view is also using a Monaco editor, that's why it's saying `editorFocus: true`. you may want to exclude output in the `when` clause.
