### ISSUE TITLE
Repository doesn't exist but vs code claim it does.

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#111786]
I have a repos name xyz in my account and if later I will choose to create one with name xyz it will say it exist which is correct. Later I rename xyz to abc now I try to push xyz which is not up there, it still claim xyz is already exist.

This need a fix.

**Comment by joaomoreno** [comment]
Run F1, `Git: Show Git Output`. At the very top of that output log you'll find the root of the git repository that was found. If that isn't supposed to be a git repository, delete the `.git` folder in there.
