### ISSUE TITLE
Accessing links in TreeItem hovers is tricky

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111713]
Testing #111515

![treehovers](https://user-images.githubusercontent.com/641685/100832471-f0098980-3435-11eb-94d0-11e7baf92e4c.gif)

Also, when you do hover over the hover, it seems to actually take focus from the tree -- notice the item highlight & actions go away as well as the view header actions. I don't think it should take focus unless you actually click into it.

This might be related to why #111525 happens sometimes.

**Comment by alexr00** [comment]
I think you're seeing https://github.com/microsoft/vscode/issues/101639 for the hover disappearing.

**Comment by eamodio** [comment]
Yeah it sounds the same, but I don't have a HiDPI display either
