### ISSUE TITLE
Collection of layout issues for Getting Started

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#111753]
Testing #111554.

- [x] Slow down animation when expanding/collapsing items on sublists
- [ ] Since I have the scroll-in-from-the-right animation when opening sublists, I also expect that for other editors such as the playground. 
- [x] Icon should be top aligned with text
![image](https://user-images.githubusercontent.com/4674940/100900911-3089f700-3478-11eb-87a2-a0b7c8a6b040.png)
- [x] Should we top align the content of half-filled tiles?
![image](https://user-images.githubusercontent.com/4674940/100901168-68913a00-3478-11eb-9556-37c028677882.png)
- [x] Remove the icon. It's already there in the editor tab and on Windows in the custom menu bar
![image](https://user-images.githubusercontent.com/4674940/100901303-8a8abc80-3478-11eb-8c16-d37cb0da1063.png)
- [x] Center align the content until there are enough tiles to fill the screen
![image](https://user-images.githubusercontent.com/4674940/100901459-aee69900-3478-11eb-83a9-474c4009649b.png)
- [x] Give sub lists more margin on the left
![image](https://user-images.githubusercontent.com/4674940/100901595-d6d5fc80-3478-11eb-850c-60b31575beca.png)
- [x] Give equal padding to the content of sub list tiles and increase the spacing between the icon and the text
![image](https://user-images.githubusercontent.com/4674940/100901738-071d9b00-3479-11eb-8ccc-9edbf84fa780.png)
- [x] Scale tile reasonably when editor is narrow, consider horizontal scrolling
![image](https://user-images.githubusercontent.com/4674940/100902262-932fc280-3479-11eb-949f-33ea379b3288.png)
- [x] Scale title when editor is small or consider scrolling
![image](https://user-images.githubusercontent.com/4674940/100902643-ec97f180-3479-11eb-85f4-4ba5374c12c1.png)

**Comment by JacksonKearl** [comment]
Got a good chunk of these done (thanks @misolori!), moving rest out to December.

**Comment by JacksonKearl** [comment]
Broke the Interactive Playground task out into a separate issue, scrolling tracked by #111702, rest should be good.

**Comment by Tyriar** [comment]
These are done for the most part, I created a bunch of getting started related issues while testing this as I hadn't touched it yet.
