### ISSUE TITLE
No hover text or code assist text for icons

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#111771]
Testing [#111551](https://github.com/microsoft/vscode/issues/111551)

Not seeing hover text in the theme file, or more info in the in the code assist.
![image](https://user-images.githubusercontent.com/1389808/100939398-11588d00-34ab-11eb-99c1-22cb36df0d4a.png)
Notice I'm hovering over the "folding-expanded" item name in the next photo.
![image](https://user-images.githubusercontent.com/1389808/100939461-28977a80-34ab-11eb-912e-97ee8a31c879.png)

Version: 1.52.0-insider (user setup)
Commit: f4187f22026ff6537f2ca8132ad3209fceb5071f
Date: 2020-12-02T13:21:33.226Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by misolori** [comment]
Pretty sure it's the same issue as https://github.com/microsoft/vscode/issues/111761

**Comment by aeschli** [comment]
dup of #111741
