### ISSUE TITLE
Using Page Up/Down keys in a treeview causes errors

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111710]
![image](https://user-images.githubusercontent.com/641685/100830861-9d7a9e00-3432-11eb-8493-e720f57d54dc.png)

Here I was paging up/down in the GitLens commits view and get this error.

I don't know if this is related to the `resolveTreeItem` work or not

**Comment by alexr00** [comment]
@joaomoreno This is also happening in the Explorer tree. I went back to version 1.46.1 (arbitrary choice, it was what I already had downloaded) and found that this issue doesn't happen there so it is at least new-ish.
