### ISSUE TITLE
VSCode opens maximized on some systems

### ISSUE THREAD

**Issue by jmaynard** [microsoft/vscode#111738]
On just one of my two Linux systems, Visual Studio Code always starts in a maximized window. It doesn't do it on the other one, or on Windows and macOS systems I also use. Both Linux systems are Pop!_OS 20.10, upgraded along the way from each Pop!_OS release from 18.04. VSCode is 1.51.1, and has been doing this since I started using it about 1.36 or so. I'm using the default Gnome Shell on each system. On the system where it doesn't start maximized, it remembers its previous size and placement. If I double-click on the window header on the failing system, it returns to its prior placement and size, but if I close it in that state, when I reopen it it's maximized again.

I'm guessing there's a settings file or something that's set to force it to be maximized, but I didn't explicitly set anything like that, and I wasn't able to find anything when searching that would have that effect.

The failing system is one I built up with a Ryzen 9 3900X, 64 GB RAM, 1 TB M.2 PCIe 4 SSD, and an RTX 2060. The working system is a System76 Oryx Pro v4 with 64 GB and an 8th gen Core i7. VSCode has done this on the failing system ever since I was running it on a dual-hex Mac Pro, and on a 1080p monitor; I'm now using a 3840x2160 monitor - but that's what the Oryx Pro has on it, too.

I tried asking about this on StackExchange and got only one reply that wasn't the issue. It suggested that I close it with the Gnome Shell's `Ctrl-<close button>` to save the size and position, but that did not change the behavior.

**Comment by mbomb007** [comment]
I wish it would always open maximized for me...

**Comment by bpasero** [comment]
You possibly configured `window.newWindowDimensions`?

**Comment by jmaynard** [comment]
Nope. It's set to `default`.

**Comment by bpasero** [comment]
This sounds like an OS issue to me given it works in the one. I cannot explain this, sorry.

**Comment by jmaynard** [comment]
Is there some sort of trace or log file I can turn on to see what it thinks it's doing?

**Comment by bpasero** [comment]
Not for this purpose, sorry.
