### ISSUE TITLE
Hovers broken in JSON

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111741]
- Running out of sources
- open `package.json` move over a property, e.g. `devDependencies`
- no hover appears

Debugging this, I see that the hover provider from JSON works properly. It creates a Hover with a `MarkedString` as content.
However, the `MarkedString` doesn't make it to the renderer (getHover.ts, line 20)

**Comment by Bewinxed** [comment]
I’m facing this issue as well with jupyter notebooks and python scripts, hovering any function highlights its:

- On the first hover, a “loading...” appears but loads indefinitely
- Afterwards, hovering any piece of the code does not show the hover menu (reference, definitions, etc...)

Latest insider, clean install.
