### ISSUE TITLE
webview-view-sample not working when run in codespaces

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#111781]
Testing https://github.com/microsoft/vssaas-planning/issues/1525.

1) Open this repo in a codespace using the desktop client
2) Open a new window on the webview-sample folder
3) `F5`
-> The calico colors view is not styled correctly and the `Add Color` button is not working.

```
reset.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vscode.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
reset.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vscode.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
main.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by mjbvz** [comment]
I did see this working in my testing:

<img width="523" alt="Screen Shot 2020-12-08 at 5 47 11 PM" src="https://user-images.githubusercontent.com/12821956/101563038-6732a680-397d-11eb-8c53-86d5f2058a7e.png">

I've linked to a codespaces issue that could explain this

@kieferrm If you see this again, can you try collapsing and then expanding the webview view. This should force the resources in the webview to be reloaded

**Comment by kieferrm** [comment]
I can not reproduce the problem anymore.

**Comment by mjbvz** [comment]
I just tested this again and it appears to be working on first load. Let me know if you see this again

**Comment by Tyriar** [comment]
Verified, it needed webview-view-sample though.
