### ISSUE TITLE
ctrl could be invalid when after tab switching

### ISSUE THREAD

**Issue by LaodaLuo** [microsoft/vscode#111708]
Follow this steps to repeat it:
1. ctrl + tab, to switch another tab.
2. ctrl + z or ctrl + y, to revoke or redo

It would be fail many times to revoke or redo when doing step 2.

**Comment by alexdima** [comment]
@LaodaLuo What version of vscode are you using? Undo and Redo are focused based. Are you sure the focus is in an editor when you attempt to do ctrl+z or ctrl+y ?
