### ISSUE TITLE
won't allow typing

### ISSUE THREAD

**Issue by MoonbowRay** [microsoft/vscode#111712]
Issue Type: <b>Bug</b>

My computer (HP laptop) doesn't work well with Prettier.  When I save my VSC doesn't fix anything with Prettier.  Also, it is not allowing me to type in the editor anymore <.  I see what I am typing on the status bar below.  However , it is not showing up in the editor itself

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.66GB (1.49GB free)|
|Process Argv|--crash-reporter-id 06ea7323-fe1a-4875-81e8-5d0be3718666|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
vscode-standardjs|che|1.4.0
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.8.0
vim|vsc|1.17.2
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you run the command to reload with all extensions disabled?
