### ISSUE TITLE
File events broken when opening workspace outside of a VM

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11176]
Might be expected.

1. Have a win VM on your mac, open vscode inside the win VM
2. In vscode open a repository which lives on a drive asociated with the mac
3. Notice file events are broken

![screen shot 2016-08-30 at 11 11 11](https://cloud.githubusercontent.com/assets/1926584/18083212/7baa0e0a-6ea2-11e6-8df9-65480240ed8a.png)

**Comment by bpasero** [comment]
@isidorn is that a very large folder? does it work with a smaller example or does the error always show?

**Comment by isidorn** [comment]
@bpasero no, it is a very small folder. 
Though I do not always get the error in the console.
The issue that I see always in this setup is that my workspace settings are only applied on restart, thus I infered file events are missing

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-filewatcher-windows#10
