### ISSUE TITLE
Notebook integration tests: Element already has context attribute

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#111730]
For example: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=95890&view=logs&j=1c20ec05-7612-5293-9b87-7ea15c22422f&t=d9b931d5-6469-5709-27a9-2ddd8b3d265c&l=1210

```
[3851:1202/083542.312296:INFO:CONSOLE(1977)] "Element already has context attribute", source: file:///__w/1/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js (1977)
    ✓ document open/close event (362ms)
```

**Comment by RMacfarlane** [comment]
I can also repro this in Insider's by trying to open the "endgame.github-issues" notebook, it prevents the notebook from rendering:
![Screen Shot 2020-12-02 at 12 53 58 PM](https://user-images.githubusercontent.com/3672607/100930685-490d0800-349e-11eb-854f-d4354df40134.png)

**Comment by roblourens** [comment]
It's a noisy but harmless error, it shouldn't actually break anything

https://github.com/microsoft/vscode/issues/111280
