### ISSUE TITLE
Inconsistent markdown formatting for email

### ISSUE THREAD

**Issue by pedro-w** [microsoft/vscode#111751]
Issue Type: <b>Bug</b>

Markdown's auto-links for emails show differently if the email domain has capital letters in it.
See example below.
I noticed that the regex used in vscode is not the same as the one mentioned in the commonmark spec.
(This is cosmetic only. In the preview, both show the same formatting)

[Commonmark 0.29 autolinks](https://spec.commonmark.org/0.29/#autolinks)  

    /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?
    (?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

VS Code:  
https://github.com/microsoft/vscode/blob/9cd45f96de363dbf86e8ce99c906ea0a892eaa93/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L2577

Screenshot:  
![Screenshot 2020-12-02 160939](https://user-images.githubusercontent.com/22172519/100898631-e07f5480-34b8-11eb-87cc-83542b912a6d.png)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

(Confirmed with all extensions disabled)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.45GB free)|
|Process Argv|D:\Peter\info.md --crash-reporter-id 3eb2ed46-8bb9-4933-b6eb-810f86518bd7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
For anyone interested in contributing a fix, here's where the grammar live: https://github.com/microsoft/vscode-markdown-tm-grammar

Make sure to fix it in the [base.yaml](https://github.com/microsoft/vscode-markdown-tm-grammar/blob/master/markdown.tmLanguage.base.yaml) file, which generates the `tmLanguage` file
