### ISSUE TITLE
Getting Started: capitalized "Editor" looks weird

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#111798]
Testing #111554

![image](https://user-images.githubusercontent.com/6726799/100989820-23890880-3549-11eb-808d-fb3d21632eb4.png)

VS Code version: Code - Insiders 1.52.0-insider (92192baf760315ac47fb2caaf3ce6d0778962352, 2020-12-03T05:43:59.635Z)
OS version: Windows_NT x64 10.0.19042

**Comment by JacksonKearl** [comment]
Yeah I agree, updated. Thanks!
