### ISSUE TITLE
Comma not throwing

### ISSUE THREAD

**Issue by cursorweb** [microsoft/vscode#111777]
Issue Type: <b>Bug</b>

```js
setInterval(() => {
  g.Database.save();
}, );
```

there is not an 'red underline' under line 3 col 2. There should be if I recall correctly

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (8.63GB free)|
|Process Argv|--crash-reporter-id 284b7e3d-4ad9-4d09-a08f-b43e430e540e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
cookeylang|Coo|1.2.5
vsliveshare|ms-|1.0.3206
LiveServer|rit|5.6.1

</details>

**Comment by mjbvz** [comment]
Trailing commas in argument list are valid in JS. The delay arguments for `setTimeout` [is also optional](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout), so this looks like a valid function call to me

**Comment by cursorweb** [comment]
oh, sorry :(
