### ISSUE TITLE
"Setting Sync" doesn't sync Tasks

### ISSUE THREAD

**Issue by ldarshan1991** [microsoft/vscode#111797]
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have VSCode on one computer system - `PC1`
2. Have few VSCode Tasks configured in `User Settings` - `Task.json`
3. Turn on `Setting Sync` in VSCode running on `PC1`
4. On a new computer `PC2`, install VSCode
5. Now login to the VSCode on the `PC2` with the same account as `PC1` and restore the settings.
6. Observe that all key shortcuts, settings are restored but `Tasks` are not restored.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ldarshan1991** [comment]
@sandy081 Can you let me know, this is duplicate of which issue?

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/91011
