### ISSUE TITLE
Getting started: images need alt text

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#111706]
Testing #111554

Images aren't loading for the "Get Started" collection. In this case, should there be some alt text or description of the image/gif? 

![image](https://user-images.githubusercontent.com/9721254/100825955-4cb17800-3427-11eb-911f-2410f18a861b.png)

**Comment by JacksonKearl** [comment]
fixed not loading with 9d9ae54aa87749c07f83ff0687f7f2277297f1dc, alt text is a good idea.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/100951268-16293b00-34c3-11eb-8425-6f0f0b4b84f1.png)
To verify, disable wifi then open the `Essentials` getting started category, you should see alt text in addition to the broken image link.
