### ISSUE TITLE
Intellisense Not Working

### ISSUE THREAD

**Issue by ItsDigitalEngine** [microsoft/vscode#111728]
Issue Type: <b>Performance Issue</b>

Hello,

Intellisense on my copy of Visual Studio Code is not working. I have tried several troubleshooting methods such as restarting the program, restarting my device, and re-installing my program. Nothing is working. Please advise. Thank you.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id f1278add-bcaa-4e07-a218-62d73d3dbb74|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   106	 77089	code main
    7	    25	 77092	   gpu-process
    0	     8	 77094	   utility
    4	    33	 77110	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — DayThree)
|    Folder (DayThree): 37 files
|      File types: js(8) json(8) gitignore(4) md(4)
|      Conf files: package.json(4);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
html-live-server|nav|0.1.0
LiveServer|rit|5.6.1

</details>

**Comment by Bewinxed** [comment]
Can confirm, when i hover for the first time after reloading, it shows "loading..." indefinitely, if I move the cursor away from that I don't get hover tooltips anymore :(

**Comment by mjbvz** [comment]
@ItsDigitalEngine What language is this for. Please provide steps to reproduce the issue

/needsMoreInfo

**Comment by mjbvz** [comment]
@Bewinxed Please open a separate issue (make sure to fill in the issue template and include proper steps to reproduce)

**Comment by Bewinxed** [comment]
> @Bewinxed Please open a separate issue (make sure to fill in the issue template and include proper steps to reproduce)

Issues already exist for this, and it has been fixed with today's update, thanks!

> Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
Closing as more information is needed to investigate this
