### ISSUE TITLE
resolveTreeItem is only ever called once, even after an `onDidChangeTreeData` for that item

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111711]
Testing #111515

While the docs do state this, it should not be the case, if you trigger a refresh, via `onDidChangeTreeData`. Refreshing a tree item, completely resets it -- calling `getTreeItem` again, creating a whole new TreeItem, so this reset things so that `resolveTreeItem` would be called again.

**Comment by alexr00** [comment]
Very good catch!
