### ISSUE TITLE
C++ IntelliSense autocomplete only give one option 

### ISSUE THREAD

**Issue by hpsaturn** [microsoft/vscode#111793]
- VSCode Version: 1.51.1
- OS Version: Debian GNU/Linux 10 (buster)

Steps to Reproduce:

1. do a clean installation of vscode 
2. install platformio extension or the dependency of this, C/C++ IntelliSense
3. open any project

![screenshot20201203_091147](https://user-images.githubusercontent.com/423856/100981929-bcb71f80-3547-11eb-9dc8-c111e4e743d1.jpg)
![screenshot20201203_091159](https://user-images.githubusercontent.com/423856/100981939-c04aa680-3547-11eb-9ff2-22c7f8666723.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Probably #110971

Please try again after running the command to reset suggest widget size (F1 > Reset Suggest Widget Size)
