### ISSUE TITLE
Welcome view buttons should have a width limit

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#111744]
Testing microsoft/vscode-remote-release#4094

is very long

![image](https://user-images.githubusercontent.com/323878/100784588-41793080-33c4-11eb-9fc2-b23baadce849.png)

**Comment by gjsjohnmurray** [comment]
In my experience they **do** have a width limit when in the sidebar. What happens if you move the PORTS view there?

**Comment by joaomoreno** [comment]
Yeah I also have a vague recollection that someone implemented this recently, on the side panel at least. But it doesn't seem like it's working:

![image](https://user-images.githubusercontent.com/22350/101146275-a9e82d80-35cf-11eb-8b80-5c55d9366f90.png)

🤷

**Comment by gjsjohnmurray** [comment]
Looks like it was done by @isidor at 876af4ccfdb6b7179a25d504e7e9c85d3955c904 in response to #94101

**Comment by joaomoreno** [comment]
OK closing this given the decision of https://github.com/microsoft/vscode/issues/94101

**Comment by alexr00** [comment]
I think this is ugly enough to revive. More discussion in https://github.com/microsoft/vscode/issues/94101

**Comment by alexr00** [comment]
Better: 
![image](https://user-images.githubusercontent.com/38270282/101174928-cd998b00-3644-11eb-816f-5a409b564159.png)
