### ISSUE TITLE
VSCode (Git Bash Terminal *White Boxes* Issue)

### ISSUE THREAD

**Issue by johlems** [microsoft/vscode#111717]
![Capture](https://user-images.githubusercontent.com/19777107/100836943-3220e280-34ab-11eb-8b5f-d44fb6a54eeb.PNG)

I'm not sure if my PC Monitor has a problem or the VS Code itself.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
