### ISSUE TITLE
Hint popups unreadable

### ISSUE THREAD

**Issue by ChristophWWagner** [microsoft/vscode#111747]
Issue Type: <b>Bug</b>

Hint popups do not fit the height of multiline text, which makes all multi-line hint-popups (while hovering over a button for example) completely unreadable throughout the whole application.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
cadsoft-ulp|mic|1.0.0
remote-wsl|ms-|0.51.4
cython|tcw|0.1.0
latex-support|tor|3.4.0
overtype|ada|0.2.0
python-preview|don|0.0.4
xml|Dot|2.5.1
jupyter|ms-|2020.11.392013122

</details>

**Comment by jrieken** [comment]
> Hint popups do not fit the height of multiline text

What do you mean by that? Can attach a screen capture?
