### ISSUE TITLE
Extension action buttons are not prominent in light theme when extension is selected

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111750]
![image](https://user-images.githubusercontent.com/10746682/100898112-b598fe80-34c0-11eb-9cf9-ff30dc85152e.png)

**Comment by misolori** [comment]
Slightly darkened the list active background color to make this stand out (which also helps some seti file icons in the tree view):

<img width="400" src="https://user-images.githubusercontent.com/35271042/100969415-ec363f80-34e7-11eb-847a-728af28e5d78.png">

fyi @joaomoreno @bpasero

**Comment by joaomoreno** [comment]
That's why they were green...? 😆
