### ISSUE TITLE
Windows: circular symlinks protection lost

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11179]
Testing https://github.com/Microsoft/vscode/issues/11035

* setup symbols links in a way that you introduce cycles
* use quick open 

=> you notice that the circular symlinks are followed until possibly you reach max file path limit on Windows (255)

**Comment by bpasero** [comment]
Related: http://superuser.com/questions/528487/list-all-files-and-dirs-without-recursion-with-junctions

**Comment by chrmarti** [comment]
Tracking with #11182.
