### ISSUE TITLE
prevent autoClosingBrackets when inserting content as result of registerCompletionItemProvider

### ISSUE THREAD

**Issue by d-koppenhagen** [microsoft/vscode#111764]
VSCode extension development offers a way to contribute to the auto-completion providers aka *InttelliSense*.
It is possible to complete inputs as the following snippet shows.
However, when implementing the snippet below (just as an example), it will watch AsciiDoc files for the `:` (colon) sign input. Once the sign has been entered, the autocompletion provider is executed.
In the example below, it will complete with a selected items label surrounded by curly braches.
E.g. selecting `foo` should result in `{foo}`.
But there is a problem with this approach: Once the completion item has been selected, the default VSCode behaviour for the `"editor.autoClosingBrackets"` setting fires. This will cause -as the inserted string starts with a curly bracket - that the an additional curly bracket is added afterwards. So the result will be `{foo}}` instead of `{foo}` with the cursor placed between the last two curly brackets (`{foo}|}`).

```ts
    const disposable = vscode.languages.registerCompletionItemProvider(
        {
          language: "asciidoc",
          scheme: "file",
        },
        AsciidocProvider,
        ...[":"]
      );

      export const AsciidocProvider = {
        provideCompletionItems,
      };

      export async function provideCompletionItems(
        document: vscode.TextDocument,
        position: vscode.Position
      ): Promise<vscode.CompletionItem[]> {
        return Promise.resolve([
          {
            label: `{${label}}`,
            kind: vscode.CompletionItemKind.Variable,
            sortText: `a_${label}`,
            insertText: `{${label}}` // <-- additional "}" will be added as result of the "editor.autoClosingBrackets" setting
          }
        ])
      }
```

I thought I can handle this by checking the configuration for `"editor.autoClosingBrackets"`. If it is configured as `never`, add the closing bracket manually. If not: let the auto completion do the rest.
But this will lead into another problem: The cursor is placed at the wrong position (right before the last curly bracket, e.g. `{foo|}`). This behaviour doesn't allow a user to keep on writing a path right after a completion item has been selected.

**Context:**

In AsciiDoc it's possible to define somewhere in  the document variables that can contain for example a path string. My goal is to provide such variables as completion items and keep on writing the path target after the variable is inserted.

The current detailed feature implementation for this can be found here:

See PR here: https://github.com/asciidoctor/asciidoctor-vscode/pull/381

### suggestion

a) allow to temporarily disable `"editor.autoClosingBrackets"` when disposable ` vscode.languages.registerCompletionItemProvider` fires

OR

b) completely disable `"editor.autoClosingBrackets"` when any ` vscode.languages.registerCompletionItemProvider` fires

This issue is related to the similar question I posted at StackOverflow:
https://stackoverflow.com/questions/65079743/prevent-autoclosingbrackets-when-inserting-content-as-result-of-registercompleti

**Comment by jrieken** [comment]
You sample doesn't compile but with a "random" value for `label` it doesn't reproduce.

**Comment by d-koppenhagen** [comment]
Hey @jrieken , You are right, the code was not fully functional.
I created a blank vscode extension example repo for reproducing the issue:
https://github.com/d-koppenhagen/registercompletionitemprovider-autoclosingbrackets-example

The `README.md` of this repo contains detailed steps for reproducing the issue.

let me know if you need more information.

**Comment by d-koppenhagen** [comment]
Yes the issue is still there.
Let me know if you need more information for investigation.

**Comment by d-koppenhagen** [comment]
Hey @jrieken , I updated my playground for this issue:
https://github.com/d-koppenhagen/registercompletionitemprovider-autoclosingbrackets-example
fortunately the issue doesn't appear anymore with the latest extension setup.
I will close this issue for now.
