### ISSUE TITLE
Can select/edit multiple lines

### ISSUE THREAD

**Issue by Nabakamal** [microsoft/vscode#111791]
Issue Type: <b>Feature Request</b>

Hello. The popular 'hold the Alt key and drag your mouse down/up a document' to select multiple lines (and possibly edit them at once) doesn't work. The same behavior works in VS as well as Notepad++, etc. It'd be great to have this here as well. Thanks. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.4.0-17134-Microsoft

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

Is this what you mean?

**Comment by alexdima** [comment]
@Nabakamal  You can configure `"editor.multiCursorModifier": "ctrlCmd"` and then hold the <kbd>Alt</kbd> key.

**Comment by Nabakamal** [comment]
Thanks, both. Yes, it's just a little different than what/how other editors let you do this, but, that's fine. Appreciate the prompt response.
