### ISSUE TITLE
Smart selection doesn't respect header levels on release notes Markdown

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#111714]
Testing #111329

1. Open a release notes Markdown file like vscode-docs repo /release-notes/v1_51.md
2. Place the cursor in the paragraph below the "More prominent pinned tabs" H3.
3. Expand the selection

I would expect that the selection would go to the H3 but instead it selects from the top of the file to somewhere about 1/2 way down. Another expansion, selects the rest of the file.

On simpler Markdown files, smart selection expands by header level.

**Comment by gregvanl** [comment]
@meganrogge Let me know if you want help creating smaller repros. I wasn't sure what elements might be causing the expansion to get confused. For example, the release notes have embedded images and links and the YAML front matter section, which could all be confusing the expansion.

**Comment by meganrogge** [comment]
@gregvanl thanks so much and good catch. I think I've found the cause of the issue and fixed it.

**Comment by gregvanl** [comment]
@meganrogge Works great and very useful now for selecting and being able to reorder H2s and H3s in the release notes.
