### ISSUE TITLE
Views are not synchronized in global state

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#111773]
Testing #111527

OS: Windows 10 1909 build 18363.1198
VS Code: 1.52.0 Insiders

When I made 2 instances of insiders with different user directories and extension directories the views aren't sync'd:
![image](https://user-images.githubusercontent.com/12758612/100942177-b6756480-34af-11eb-87a1-32ff18fc6598.png)

Repro steps:
1. Working in an empty directory, cd into this directory using Powershell
2. Run the following 2 lines to get 2 instances of Insiders:
```
code-insiders --user-data-dir=./tmp1 --extensions-dir=./tmp2
code-insiders --user-data-dir=./tmp3 --extensions-dir=./tmp4
```

3. Open the Explorer in both instances
4. Remove a view from the first one. Notice how other instance doesn't mirror this.
4. Try removing a different view from the second instance. Notice again how the first instance doesn't mirror this change.

**Comment by sandy081** [comment]
Can you please provide steps to repro?

**Comment by tanhakabir** [comment]
> Can you please provide steps to repro?

Just added!

**Comment by sandy081** [comment]
It seems to work for me. Sometimes sync does not get kicked off immediately (if sync was done in less than 10s ago). You have to wait for 5 mins for next sync or perform some action that can trigger sync or you can trigger sync manually using Sync Now command from command pallette. To confirm if sync got triggered you can check settings sync log in output view.
