### ISSUE TITLE
The code part can't show perfect, the code is black, there is not any other color;

### ISSUE THREAD

**Issue by MurlinGao** [microsoft/vscode#111782]
- VSCode Version: 1.51.1
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
- OS Version: macOS Big Sur 11.0.1

Steps to Reproduce:

1. when my macbook update to macOS Big Sur , vscode's code part can't show perfect, the code is black, there is not any other color;
![image](https://user-images.githubusercontent.com/51697895/100955876-54217000-3552-11eb-8423-b5d70331af31.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Probably #100840
