### ISSUE TITLE
Getting Started experience resizing window

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#111702]
Testing #111554

The "skip" button isn't responsive when resizing the window and overlays onto the tasks. Maybe it should be in the bottom corner when the window resizes or at the top, above the tasks? It would be good to have a vertical scroll bar as the window resizes too.

![recording (1)](https://user-images.githubusercontent.com/9721254/100823170-b9c20f00-3421-11eb-9d05-e39fd73b4ca4.gif)

**Comment by JacksonKearl** [comment]
fixed as part of #111753
