### ISSUE TITLE
Holding down Ctrl + S shouldn't spam save

### ISSUE THREAD

**Issue by feline87** [microsoft/vscode#111743]
- VSCode Version: 1.51.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Run a Node.js project with nodemon.
2. hold down Ctrl + S
3. Watch the "restarting due to changes" spamming the terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Why do you need to hold down Ctrl+S?

**Comment by feline87** [comment]
I hold Ctrl + S down to save a file :-) 
Why save a saved file again? Is there a reason behind that? It interferes with the normal functionality of nodemon now. It doesn't give nodemon time to restart properly.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem with screen cast mode on
