### ISSUE TITLE
Failed to cut chunks of code

### ISSUE THREAD

**Issue by dannyjavi** [microsoft/vscode#111752]
When a piece of code is cut there is an empty space, as is logical, if those blank spaces are erased by pressing the shift key shift + delete, what had been cut and then pasted in another part of the file is deleted.

**Comment by rebornix** [comment]
@dannyjavi can you please share a recording of what happened to help understand what's going on?

**Comment by dannyjavi** [comment]
Sorry for taking time to answer, I hope it is a little clearer and can be used to help correct what I believe is a mistake.

Thank you

![ezgif com-gif-maker](https://user-images.githubusercontent.com/37238169/102198069-39d88200-3ec2-11eb-986d-fef80082cc0b.gif)
