### ISSUE TITLE
Hard to select all of an output cell

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#111770]
When a text output cell is longer than the screen its difficult to select all of the contents. ctrl+A selects the code, and dragging to the edge of the screen does not trigger scroll.

**Comment by NikTarasov** [comment]
Came here to create a similar ticket. This is very annoying for my workflow, to the point where it renders vs code next to useless.

**Comment by omasoud** [comment]
This has been open for a while. I would be really nice to be able to right-click (or click on the "..." to the left) then "Copy Cell Output"

**Comment by rebornix** [comment]
We now support copy output through the `...` context menu on the left.
