### ISSUE TITLE
Getting Started: Reset Progress doesn't reset all

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#111705]
Testing #111554

`Getting Started: Reset Progress` only resets the progress of the "Get Started" collection, not the "Essentials" collection. Is that intended? Will the user get an option to go through and reset each collection again or reset the whole experience in one command? 

![recording (2)](https://user-images.githubusercontent.com/9721254/100825161-710c5500-3425-11eb-830c-4ea3a731e949.gif)

**Comment by JacksonKearl** [comment]
Hm, so it looks like it reset both progresses, but then you opened the command palette and it progressed that one again. When we have more items that shouldn't be a problem. Going to close this out for now as the command is mainly for dev purposes right now, we haven't discussed a proper UX for resetting.
