### ISSUE TITLE
Unable to find the registered languages while saving the file.

### ISSUE THREAD

**Issue by akhilravuri1** [microsoft/vscode#111788]
- VSCode Version: 1.51.0 (user setup)
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Create a new sample project by selecting ``` New Language support```
2. Now add the following code in package.json to register 3 new languages.
```
        "languages": [
            {
            "id": "db2_z",
            "aliases": ["Db2Z"],
            "extensions": [".spsql", ".sql",".z"],
            "configuration": "./z/language-configuration.json"
            },
            {
            "id": "db2_i",
            "aliases": ["Db2i"],
            "extensions": [".spsql", ".sql",".i"],
            "configuration": "./i/language-configuration.json"
            },
            {
                "id": "db2_luw",
                "aliases": ["Db2Luw"],
                "extensions": [".spsql", ".sql",".luw"],
                "configuration": "./luw/language-configuration.json"
            }
        ]
```
3. Now when I run the extension it displays only one language type while saving. But while selecting the language mode it shows three languages.

Please check the attached screenshots.

Here you can find the 3 languages.

![image](https://user-images.githubusercontent.com/32290825/100967760-0a3a8900-3556-11eb-9a14-2723ec67b429.png)

But while saving we can see only one language.

![image](https://user-images.githubusercontent.com/32290825/100967904-58e82300-3556-11eb-828e-dd0bd33007b9.png)

Please let me know if you need any more details.

Thanks,
Akhil

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Does this change when you install this extension into VSCode, does it then show all 3 languages for saving?

In the end we seem to be using this code to get the extensions:

https://github.com/microsoft/vscode/blob/bf24f189f1d17f701b6440fa5845900a5885fcc1/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L278-L293

If someone wants to debug this and help out to understand why the languages do not appear, that would be helpful.

**Comment by akhilravuri1** [comment]
Hi @bpasero 

Thanks for the comment.

I haven’t installed the extension. I just ran it using F5 as I said in my previous comment.

But I will install the extension and I will update you.

**Comment by akhilravuri1** [comment]
Hi @bpasero 

I have created the vsix and installed the extension but the result is same.

Able to see 3 languages(In select Language Mode)
![image](https://user-images.githubusercontent.com/32290825/101125573-8ea50e80-361f-11eb-8d0d-c01282310137.png)

While saving I can see only 1 language which is registered in the last.(In my first comment I registered db2_luw in the last so we are able to see Db2_luw in the save dialog box). 
![image](https://user-images.githubusercontent.com/32290825/101125744-f9564a00-361f-11eb-8e78-806cf7a20854.png)

In this, I registered db2_i at the last so I can see only db2_i in the save dialog box.

If you need any more details please let me know.

Thanks,
Akhil

**Comment by bpasero** [comment]
I cannot reproduce, I see all 3 entries:

![image](https://user-images.githubusercontent.com/900690/101132185-d23f4e80-3606-11eb-9ca0-56d3caf33110.png)

I did:
* open a new untitled file
* save as
* saw these 3 entries

**Comment by akhilravuri1** [comment]
Hi @bpasero 
Is it possible to share the package.json file?
Sorry, My vscode version is 1.51.0 are you using the same version?

I will uninstall the vscode and install it again.

Thanks,
Akhil

**Comment by bpasero** [comment]
It is a hello world TS extension (from our `yo` generator) with the following `package.json` entry (I was using stable 1.51):

```json
"languages": [
	{
	"id": "db2_z",
	"aliases": ["Db2Z"],
	"extensions": [".spsql", ".sql",".z"]
	},
	{
	"id": "db2_i",
	"aliases": ["Db2i"],
	"extensions": [".spsql", ".sql",".i"]
	},
	{
		"id": "db2_luw",
		"aliases": ["Db2Luw"],
		"extensions": [".spsql", ".sql",".luw"]
	}
]
```

**Comment by akhilravuri1** [comment]
Hi @bpasero 

I have tried all the things...uninstalled and installed the vscode, Restarted my system. But the result is same.
I have installed it in my VM also but I can see only one language type.
I don't understand how you are able to see all the language types.
Is it possible to send my vsix file and check whether my vsix has the problem or my system?
 I am unable to upload my .vsix file here.
```
	"contributes": {
		"commands": [
			{
				"command": "hello.helloWorld",
				"title": "Hello World"
			}
		],
		"languages": [
            {
                "id": "db2_luw",
                "aliases": ["Db2Luw"],
                "extensions": [".spsql", ".sql",".luw"],
                "configuration": "./language-configuration.json"
            },
            {
            	"id": "db2_z",
            	"aliases": ["Db2Z"],
            	"extensions": [".spsql", ".sql",".z"],
            	"configuration": "./language-configuration.json"
            },
            {
            	"id": "db2_i",
            	"aliases": ["Db2i"],
            	"extensions": [".spsql", ".sql",".i"],
            	"configuration": "./language-configuration.json"
            }
        ]
	}
```
Is there any problem with my package.json?

Thanks,
Akhil

**Comment by bpasero** [comment]
I am sorry but I will have to defer you to our other channels for extension development. There is people that can assist.

**Comment by akhilravuri1** [comment]
Hi @bpasero If I select the language mode to any registered language it shows only the last one.

But if I select the built-in language like plain text and save it then it shows all the languages.\

Please let me know how you have saved it.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @bpasero 
Here only one language mode is shown because all the language extension types have the same .type ".sql" as the first.(when registered language is selected).
```
    "languages": [
      {
        "id": "db2_luw",
        "extensions": [
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      },
      {
        "id": "db2_i",
        "extensions": [
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      },
      {
        "id": "db2_z",
        "extensions": [
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      }
    ],
```

![image](https://user-images.githubusercontent.com/32290825/101442239-eeadf480-3940-11eb-9127-b07261df301f.png)

Part-2 of file-types:-
![image](https://user-images.githubusercontent.com/32290825/101443254-04241e00-3943-11eb-9991-a834210313bb.png)

In the below image I just modified when code so that the extensions field in languages have .luw,.i and .z as their first extension type.
```
    "languages": [
      {
        "id": "db2_luw",
        "extensions": [
          ".luw",
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      },
      {
        "id": "db2_i",
        "extensions": [
          ".i",
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      },
      {
        "id": "db2_z",
        "extensions": [
          ".z",
          ".sql",
          ".spsql",
          ".udfsql",
          ".db2",
          ".spdb2",
          ".udfdb2"
        ],
        "configuration": "./syntaxes/language-configuration.json"
      }
    ],
```
![image](https://user-images.githubusercontent.com/32290825/101442569-9e836200-3941-11eb-92f4-7c970bddb3a8.png)


All the above cases are when we change the untitled file language mode from PLAIN TEXT to (Db2_z, Db2_i or Dbw_luw).

If the type is plain text then all the registered languages are shown while saving even the extensions field in the languages are the same.

**Comment by bpasero** [comment]
@akhilravuri1 thank you, I found an actual bug, thanks for being patient with me 👍

**Comment by akhilravuri1** [comment]
Hi @bpasero 
Sorry, I am a bit confused. I have seen the patch does it add all the matching or only the first matching.

In which version we can expect this patch.

Thanks,
Akhil

**Comment by bpasero** [comment]
@akhilravuri1 i will let you know, probably end of this week in our insiders version.

**Comment by akhilravuri1** [comment]
> I have seen the patch does it add all the matching or only the first matching.

About this?

**Comment by bpasero** [comment]
@akhilravuri1 we had some logic to find the first matching extension to handle it specially by putting it to the top of the list. However, if there was a second or third extension also matching, we would loose that one and only pick the last matching. With the fix, we check if we already found a matching extension before returning `null` so that the others are preserved.

**Comment by aeschli** [comment]
Verified with the configuration from https://github.com/microsoft/vscode/issues/111788#issuecomment-740382511
