### ISSUE TITLE
Editor operation problem.

### ISSUE THREAD

**Issue by Rexlu** [microsoft/vscode#111726]
Issue Type: <b>Bug</b>

When the cursor to select(+Alt) the text range exceeds the screen area, the scroll bar of the window cannot be combined with the cursor action to scroll the text selection range. 

But without +Alt to cursor to select the text, can be combined with the cursor action to scroll the text selection range. 

This is the cursor scroll text with Alt key's problem.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.05GB free)|
|Process Argv|--crash-reporter-id 77c9cb2e-2eb5-4dc8-9a39-85faddb3a757|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hant|MS-|1.51.2
cpptools|ms-|1.1.2

(2 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@Rexlu I'm sorry, but I don't understand what "When the cursor to select(+Alt)" means. Do you mean you have a large selection like <kbd>Ctrl</kbd>+<kbd>A</kbd> and then press <kbd>Alt</kbd>? Can you please write more clear steps.

**Comment by Rexlu** [comment]
@alexdima Yes, a little like from your description, but the Ctrl+A is for auto select all words.   The action is like using the mouse long press to select words by long pressing the left button alone! But the same action + Alt is the issue ,what I mean for. May you understand what i mean?

**Comment by alexdima** [comment]
@Rexlu Here is what I have tried:
* mouse down, mouse drag around the editor edges
* mouse down, press alt, mouse drag around the editor edges
Everything appears to behave normally:

![Kapture 2020-12-02 at 17 28 18](https://user-images.githubusercontent.com/5047891/100901115-cbf48980-34c3-11eb-9ef6-687c6022ae23.gif)

What do you expect to happen differently?

**Comment by Rexlu** [comment]
@alexdima  The expect is like your test results ! I can't find the settings or something else to do normally like your test result.
I have two NBs in the same issue situation.
Do you have any settings for this test result?

**Comment by alexdima** [comment]
@Rexlu Sorry, I forgot that I use `"editor.multiCursorModifier": "ctrlCmd"`, so that would free up <kbd>Alt</kbd> to be usable in column selection.
