### ISSUE TITLE
Canceling picker can close another opened picker

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11172]
Testing https://github.com/Microsoft/vscode/issues/11110

* write an extension that opens the picker with a cancellation token that cancels itself after 5 seconds (also configure it to keep open on focus lost)
* run the extension to open quick open
* open another picker (e.g. encoding)

=> after 5 seconds the encoding picker closes

I think the cancellation token should only work on the request that was made to open the picker in the first place.

```typescript
let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    // The code you place here will be executed every time your command is executed

    const src = new vscode.CancellationTokenSource();

    setTimeout(function() {
        src.cancel();
    }, 3000);

    // Display a message box to the user
    vscode.window.showQuickPick(["foo", "bar"], { ignoreFocusOut: true }, src.token).then(res => {
        console.log("res is null?: " + (res === null));
        console.log("res is undefined?: " + (res === void 0));
    });
});
```

**Comment by jrieken** [comment]
and the inverse: "Opening quick pick doesn't cancel an existing quick pick"...
