### ISSUE TITLE
No "file history" for notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#111763]
- Open a notebook
- Find the file history view in scm

![image](https://user-images.githubusercontent.com/323878/100921845-f6c5ea00-3491-11eb-9f92-51f64b62f1ee.png)

**Comment by eamodio** [comment]
The file history view is provided by GitLens, can you open an issue there?

Although I'm guessing the same issue exists with the Timeline view -- is that true?

**Comment by roblourens** [comment]
I actually do see history in the timeline view

**Comment by eamodio** [comment]
OK, thanks closing this then.
