### ISSUE TITLE
VS Code Terminal Launch Error

### ISSUE THREAD

**Issue by shlok-gandhi** [microsoft/vscode#111831]
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 3221225477.

What should I do now to restart terminal again?

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
