### ISSUE TITLE
js-debug attachment fails if --inspect and --remote-debugging-port are the same

### ISSUE THREAD

**Issue by taylorthurlow** [microsoft/vscode#111857]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

I have a Node 14 Electron typescript application and I'm trying to set up a launch.json for in-vscode debugging of the application. That also might not make sense, I'm just doing this for the first time so I'm not sure how electron interacts with the version of node installed, or if it's bundled with 12.x or something.

Steps to Reproduce:

1. Disable the preview javascript debugger with `{ "debug.javascript.usePreview": true }`
2. Configure a basic electron application with a single page and set a breakpoint in a typescript file
3. Run the application in debug mode, and trigger the code with the breakpoint

Expected result: The breakpoint is tripped and the code stops executing and vscode debugging is active

Actual result: The breakpoint is disabled with "unbound breakpoint" and execution is not paused. Disabling the javascript preview with NO changes to the configuration fixes the issue.

Here is the trace output when the preview debugger is enabled: [vscode-debugadapter-24.json.gz](https://github.com/microsoft/vscode/files/5640053/vscode-debugadapter-24.json.gz)

Another note: Vscode, and part of that trace log, determines my node version to be 12, which is partially true - my global system installed version is 12, but I use nodenv and that is set to 14. I have determined that the app is run with Node 14 as expected because 14 is in my path before 12 is, but vscode does pick up 12 in some instances. I can see in the trace log that eventually this happens:

```
{
  "tag": "runtime.launch",
  "timestamp": 1607045565865,
  "message": "Discovered version",
  "metadata": {
    "version": "v14.15.1"
  },
  "level": 1
}
```

So I'm not sure what to make of that.

If it is helpful, here is my terminal output (with `console` set to `integratedTerminal` in my launch.json):

```
$>  /usr/bin/env 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js"' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/nh/ctfx1lvj16ndrbn9p8mc9h4w0000gn/T/node-cdp.690-2.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/taylorthurlow/.anyenv/envs/nodenv/shims/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/var/folders/nh/ctfx1lvj16ndrbn9p8mc9h4w0000gn/T/node-debug-callback-fa76909e0d227084"}' /Users/taylorthurlow/Code/bayphoto/optimus/node_modules/.bin/electron --inspect=9223 --remote-debugging-port=9223 --enable-logging ./../dist/main.js 
Debugger listening on ws://127.0.0.1:61758/7d8f116a-542b-4fba-9758-295e0efda705
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:9223/c40d0d8a-23be-4109-88fe-0ebf95557570
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[6407:1203/174830.050598:ERROR:socket_posix.cc(148)] bind() failed: Address already in use (48)
[6407:1203/174830.050656:ERROR:devtools_http_handler.cc(297)] Cannot start http server for devtools.
(node:6407) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[6445:1203/174830.170893:WARNING:address_sorter_posix.cc(388)] FromSockAddr failed on netmask
[6446:1203/174830.361281:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361338:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361349:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361357:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6407:1203/174830.449789:WARNING:CONSOLE(87)] "%cElectron Security Warning (Insecure Content-Security-Policy) font-weight: bold; This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.", source: electron/js2c/sandbox_bundle.js (87)
[6407:1203/174830.495248:VERBOSE1:CONSOLE(1)] "Main._createAppUI: 31.05810546875 ms", source: devtools://devtools/bundled/main/main.js (1)
[6407:1203/174830.506580:VERBOSE1:CONSOLE(1)] "Main._showAppUI: 11.01806640625 ms", source: devtools://devtools/bundled/main/main.js (1)
[6407:1203/174830.567752:VERBOSE1:CONSOLE(1)] "Main._initializeTarget: 6.6298828125 ms", source: devtools://devtools/bundled/main/main.js (1)
[6407:1203/174830.662684:VERBOSE1:CONSOLE(1)] "Main._lateInitialization: 0.532958984375 ms", source: devtools://devtools/bundled/main/main.js (1)
Debugger attached.
[6407:1203/174832.542358:INFO:CONSOLE(10)] "Uncaught could not locate click event target", source: file:///Users/taylorthurlow/Code/bayphoto/optimus/dist/renderer.js (10)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

Does this issue occur when all extensions are disabled?: No, I need the chrome debugger extension to use this

**Comment by connor4312** [comment]
Thanks for collecting logs. It looks like you set a breakpoint in `src/renderer.ts` which is run by the renderer, but it looks like the logs you uploaded were for the main process (which doesn't load a file called renderer).

I'm assuming that the renderer.ts is pulled in by the renderer process. Can you set `trace: true` in the renderer launch configuration, and share the resulting logs of that?

**Comment by taylorthurlow** [comment]
Sorry, my lack of experience is showing here. I didn't connect the dots before on the renderer process so what I can tell you now is that main process debuggers work fine, but renderer ones don't. Here's the trace logs: [vscode-debugadapter-29.json.gz](https://github.com/microsoft/vscode/files/5644718/vscode-debugadapter-29.json.gz)

I can see that it's failing to connect to the Chrome instance, in this case the electron app. Taking a look at the trace log generated when I have the preview debugger disabled, I can see that it tries quite a few times with the same 503 error but it does eventually connect. I'm not sure if the trace logs are obfuscating the fact that it is trying over and over again, but to me it looks like it only tries once, and I have a 30 second timeout set so that should be plenty of time for the debugger to connect.

The legacy debugger logs are here: [vscode-chrome-debug.txt](https://github.com/microsoft/vscode/files/5644729/vscode-chrome-debug.txt)

**Comment by connor4312** [comment]
No worries, thanks for the log

One suspicious thing that I see you have is:

```
[
  "--inspect=9223",
  "--remote-debugging-port=9223",
  "--enable-logging"
]
```

I didn't know it was possible to share ports in this way; I think it worked for the old debugger because Node.js and Chrome publish their target metadata on different paths, but in js-debug the attach logic is shared so it's attaching to the node process instead of the Chrome process (which is not initially available).

I think this can be resolved by setting it so that the --inspect and --remote-debugging-port values are different which would prevent this mix up.

**Comment by taylorthurlow** [comment]
Nice catch, that doesn't seem to have fixed my issue though. I set `inspect` to port 9223 and `remote-debugging-port` to 9222, and I can confirm that i can visit `/json` and `/json/version` on both of those ports. I still get a connection refused error in the logs, uploaded here: [vscode-debugadapter-3.json.gz](https://github.com/microsoft/vscode/files/5654344/vscode-debugadapter-3.json.gz)

Immediately after the refused connection it does seem like 1 second goes by and it is able to request `/json/list` so I'm not sure if it's waiting for the server to go up and then succeeding. Regardless, the breakpoint is still unbound.

**Comment by connor4312** [comment]
Okay, thanks. My guess as incorrect then.

It looks like electron is denying our request to attach to the browser:

```js
// we send:

{
  "id": 1001,
  "method": "Target.attachToBrowserTarget",
  "params": {}
}

// we get back: 
{
  "id": 1001,
  "error": {
    "code": -32000,
    "message": "Not allowed"
  }
}
```

I don't know off hand if there's any particular configuration/security settings in Electron that could cause this to happen; I don't run into this issue in a simple test Electron 11 app. Is there any special configuration you have which could be causing the issue -- or would it be possible to share the repo or a sample repo where this happens?

cc @deepak1556 if you happen to know what would cause this ^

**Comment by Githubber2021** [comment]
Hi, just a confirmation from my side. I have the same error output I didn't notice a few weeks ago:

```
[6445:1203/174830.170893:WARNING:address_sorter_posix.cc(388)] FromSockAddr failed on netmask
[6446:1203/174830.361281:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361338:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361349:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
[6446:1203/174830.361357:ERROR:node_bindings.cc(260)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.
```

**Comment by connor4312** [comment]
Fyi this is now fixed https://github.com/microsoft/vscode/issues/123420#issuecomment-837290667
