### ISSUE TITLE
When multiple vscode instances are open, reloading one does not reload the other instances.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#111863]
Issue Type: <b>Bug</b>

1. open a couple of VSCode instances. (ex inst-a and inst-b)
2. check for extension updates ( assuming you find a few extension to update)
3. click on the reload button in front of the extension from inst-a

output:
while inst-a gets reloaded, inst-b still shows the reload button in front of the extension.

till the previous update: both inst-a and inst-b would reload.

I only observed this in the last couple of weeks. Is this intended behavior?

Note: I do have some extension set to "enable workspace" if that causes this behavior.

VS Code version: Code - Insiders 1.52.0-insider (92192baf760315ac47fb2caaf3ce6d0778962352, 2020-12-03T05:43:59.635Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.95GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.2
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
output-colorizer|IBM|0.1.2
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-next|ms-|4.2.20201202
vscode-typescript-tslint-plugin|ms-|1.2.3
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
vscode-jest|Ort|3.2.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
sonarlint-vscode|Son|1.18.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.85.0
vscodeintellicode|Vis|1.2.10
glean|wix|5.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by sandy081** [comment]
We never automatically reloaded instances, it could be a UI bug before that reload button getting disappeared in second instance and got fixed recently. So this is now working as expected.
