### ISSUE TITLE
Pinned Tabs do not work on Normal Mode

### ISSUE THREAD

**Issue by tvvignesh** [microsoft/vscode#111896]
- VSCode Version:

```
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20201
```
- OS Version: Windows 10 Home

Steps to Reproduce:

When pinning a tab in normal mode, and scrolling through, the pinned tab scrolls as well with other tabs.

But when I change it to compact or shrink mode, it works well. Added a gif below which shows the issue:

![vscode-pin-bug](https://user-images.githubusercontent.com/1165845/101180242-575f4d80-3671-11eb-8803-8fbcf883c655.gif)

**Comment by bpasero** [comment]
A limitation that I acknowledge but have no plans to fix at the moment due to the complexity of how the layout works for tabs esp. when they have dynamic widths. Use `shrink` or `compact` as you figured out already.
