### ISSUE TITLE
Chromebookのほうが使いやすい

### ISSUE THREAD

**Issue by piroQ** [microsoft/vscode#111802]
Windowsは起動が遅い。 私は、VScodeじゃなくて、vimやtext(ChromeOSの標準エディタ)を使う。
私のPCは、Chromebookだ。
私のPCのOSは、ChromeOSだ。

**Comment by yume-chan** [comment]
Translation:

> ##  Chromebook is easier to use
>
> Windows is slow to start. Instead of VSCode, I use vim or text (the default editor of ChromeOS).
> My PC is Chromebook.
> My PC's OS is ChromeOS

**Comment by piroQ** [comment]
> Windowsは起動が遅い。 私は、VScodeじゃなくて、vimやtext(ChromeOSの標準エディタ)を使う。
> 私のPCは、Chromebookだ。
> 私のPCのOSは、ChromeOSだ。
