### ISSUE TITLE
Find a way to allow us to monetize the extensions

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#111800]
Find a way to allow us to monetize the extensions. In America they say "there is no free lunch" right? We are developing extensions, bringing views to Microsoft and making VSCode more popular. So there should be a way for Microsoft to allow us to monetize the extensions. There is no way to run adds at the moment inside an electron app, so this option is out, and we cant make our extensions paid, unless we spend money to also maintain an API for authentication/authorization, which is also not good for the developer. As any other platform, if we deliver value for your users, even for a small niche, we should also receive something for it.

Microsoft could pay us a monthly fee according to the number of new users we bring to VSCode. It is like a Marketing Campaign, but we are doing it for free. I have received just 99 dollars for an extension that I built using more than 100 hours of work. And I'm sure I'm delivering value to VSCode/Microsoft, because even for a small niche as Salesforce, the extension is growing 1k users a month. How many are new users? I really don't know, but I'm sure you guys track it and could use it to calculate how much each developer should receive. Besides that I also helped to identify bugs and find features for VSCode, which is the "free lunch" Americans love to say that does not exist. But in this case, I feel like I have been doing it. The point here is that we can still leave the extensions to be always FREE, but we should receive money for it anyways.
Is there anybody from Microsoft/VSCode marketing team for us to talk? This can be solve quickly if they move most of the money from marketing campaigns to pay vscode extension developers.

**Comment by gjsjohnmurray** [comment]
See also #90648, #36577, #71968
