### ISSUE TITLE
Support for "--extensions-dir" and "--user-data-dir" as permanent command line arguments

### ISSUE THREAD

**Issue by asas-dev** [microsoft/vscode#111801]
A **huge** impact:

* Support for short command line calls in project folders: `C:\Projekt> code .`
* For those working in a Windows client-server environment:
  * No more profile issues with quota limitations.
  * No more profile issues with User Profile Service struggling with tons of cache files.
  * No need to work around by changing shortcuts and Windows Explorer registry keys.

A **trivial** implementation:

![image](https://user-images.githubusercontent.com/13746847/100990415-22100e00-3552-11eb-9488-c52e53f3ba3d.png)

https://github.com/microsoft/vscode/blob/37e9cceddc5f8e8fe504378b04ebd7388beb6601/src/main.js#L220

**Comment by joaomoreno** [comment]
@bpasero Thoughts?

**Comment by joaomoreno** [comment]
> Support for short command line calls in project folders

@asas-dev The same can be achieved by simply having a `code-foo` bat script which adds these flags, no?

**Comment by asas-dev** [comment]
@joaomoreno For sure, another workaround would be also to edit shortcuts and registry keys for context menu entries in Windows Explorer. But manding here and patching there is not what makes us happy, right?

**Comment by bpasero** [comment]
👎  from me, that was not the intent of this file. The intent is to put config options in there that must be read quickly on startup before Electron is ready. I do not want to overload this with other things. Just create a separate script to launch.

**Comment by joaomoreno** [comment]
@asas-dev I agree with @bpasero. This isn't manding and patching, but rather customizing your setup. Closing this with the workaround suggestion. Sorry about that.

**Comment by asas-dev** [comment]
Okay @bpasero and @joaomoreno, you have the word. But please keep in mind that VS Code is currently an issue for those working in a Windows client-server environment, as I described above. A native support should be strived for.
