### ISSUE TITLE
More beauti for css`${tw`px-8 py-4 text-white bg-green-500`}`

### ISSUE THREAD

**Issue by IRediTOTO** [microsoft/vscode#111874]
Hi, I have a code JSX like this, it look so hurt to your eyes, right? 
```
className={
                  item.type === "AE" || item.type === "YT"
                     ? css`
                          ${tw`px-8 py-4 text-white bg-green-500 border-r rounded-t`}
                       `
                     : item.proofOfPurchaseImage.public_id
                     ? css`
                          ${tw`px-8 py-4 text-white bg-blue-500 `}
                       `
                     : css`
                          ${tw`px-8 py-4 `}
                       `
               }>

```
I would love have a config for this get this
Hi, I have a code JSX like this, it look so hurt to your eyes, right? 
```
className={ item.type === "AE" || item.type === "YT"?
                     css`${tw`px-8 py-4 text-white bg-green-500 border-r rounded-t`} : item.proofOfPurchaseImage.public_id
                     ? css`${tw`px-8 py-4 text-white bg-blue-500 `}                       `
                     : css` ${tw`px-8 py-4 `}   
```                    `
               }>

this
 ```
css`
                          ${tw`px-8 py-4 text-white bg-green-500 border-r rounded-t`}
                       `
```
shoule be 
`css`${tw`px-8 py-4 text-white bg-green-500 border-r rounded-t`}``

**Comment by aeschli** [comment]
You suggest that the TypeScript formatter removes the whitespace in the backtick string?

How would the formatter know that this is not breaking the content?

**Comment by IRediTOTO** [comment]
I mean my origin code is like this 
`<ol className={css`${tw`flex items-center `}`}>`
but after press Alt+Shift+F it become this
```
<ol
               className={css`
                  ${tw`flex items-center `}
               `}>
```
![image](https://user-images.githubusercontent.com/15695252/101182906-5504ef80-3681-11eb-93c2-2dbceceb87c4.png)


![image](https://user-images.githubusercontent.com/15695252/101182889-4cacb480-3681-11eb-89ad-ff4ac4e3ce5c.png)

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by IRediTOTO** [comment]
> Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Yes, it just not beautiful code anymore. This is not an error, just a missing feature i think

**Comment by mjbvz** [comment]
Please share a minimal example that demonstrates the problem. I don't understand what the expected behavior is
