### ISSUE TITLE
Renaming a file by changing only the case keeps previous name in the tab

### ISSUE THREAD

**Issue by MaximeBernard** [microsoft/vscode#111804]
- VSCode Version: 1.51.1
- OS Version: macOS Big Sur 11.0.1 (Darwin x64 20.1.0)

Steps to Reproduce:

1. Open a folder
2. Create a file called `test`
3. Rename your file `TEST`
4. Switch tab (i go to `Welcome` tab but doesn't matter)

Your tab will have previous name.

Does this issue occur when all extensions are disabled?: Yes

Few notes:

- It seems to only occur if you change the case (uppercase <-> lowercase). Adding/Removing characters does not trigger this issue.
- If you click on the file in the `Explorer`, tab will have correct name but if you change tab, tab will have previous name (same issue) 
- Reloading VSCode doesn't fix the issue

**Comment by bpasero** [comment]
I cannot reproduce.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by MaximeBernard** [comment]
I cannot reproduce in Insiders. I guess you fixed it already congrats 🎉 😄
