### ISSUE TITLE
[Allow pattern for extension Material Icon Theme]

### ISSUE THREAD

**Issue by Sevendaye** [microsoft/vscode#111806]
Hi,

I use the extension "Material Icon Theme", for some reasons it is impossible for the extension to apply the same icon for files that end with * Sreen.js for example (LoginScreen.js, HomeScreen.js) , can you please solve the problem, to allow the extension to use this pattern?

Cordially.

**Comment by aeschli** [comment]
Feature requests for the Material Icon Theme must be filed against that extension
