### ISSUE TITLE
Search bar stays always on top and blocks suggestions

### ISSUE THREAD

**Issue by oltodosel** [microsoft/vscode#111833]
- VSCode Version: 1.51.1
- OS Version: Linux x64 5.9.11-arch2-1

Steps to Reproduce:

1. open the search bar
2. type something in right part of the screen so that suggestions would appear close to the search bar

Does this issue occur when all extensions are disabled?: Yes

Screen: 
![2020-12-03-192642_1920x1080_scrot](https://user-images.githubusercontent.com/10230453/101065510-eac74e80-359d-11eb-8b2b-03661ed1a4eb.png)

**Comment by jrieken** [comment]
@rebornix does the editor allow to control this? Will zindex work?

**Comment by amunger** [comment]
suggestions now appear on top of the search widget
