### ISSUE TITLE
GIT_ASKPASS is set unconditionally

### ISSUE THREAD

**Issue by crumblingstatue** [microsoft/vscode#111839]
- VSCode Version: 1.51.1 (OSS)
- OS Version: Linux x64 5.9.11-arch2-1

I disable the git authentication with
```
    "github.gitAuthentication": false,
    "git.terminalAuthentication": false
```
But `git push` errors because vscode still set GIT_ASKPASS:
```
$ git push
/usr/lib/code/extensions/git/dist/askpass.sh: line 3: /usr/lib/electron7/electron: No such file or directory
/usr/lib/code/extensions/git/dist/askpass.sh: line 3: /usr/lib/electron7/electron: No such file or directory
remote: No anonymous write access.
```

Furthermore, this also occurs with --disable-extensions, which makes no sense to me because it tries to execute extensions/git/dist/askpass.sh, even though I have the git extension disabled?

Does this issue occur when all extensions are disabled?: Yes

**Comment by crumblingstatue** [comment]
It seems like it sets GIT_ASKPASS in the term environment unconditionally, regardless whether git authentication is enabled or not.
If I unset GIT_ASKPASS, this error goes away.

**Comment by Tyriar** [comment]
Verified but created a clean up task https://github.com/microsoft/vscode/issues/146082
