### ISSUE TITLE
Rework working copy service participants

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111878]
This is follow-up work from https://github.com/microsoft/vscode/issues/111873

**Comment by jrieken** [comment]
@bpasero this will likely involve you as well because it touches on the working copy service

**Comment by jrieken** [comment]
I am actually unsure what to do here - not really technically but I wonder what's the best from a users point of view. Without [this guard](https://github.com/microsoft/vscode/blob/a029dda2fe73994e5ff6e64e51b9ce66544560bc/src%2Fvs%2Fworkbench%2Fapi%2Fbrowser%2FmainThreadFileSystemEventService.ts#L71) this is what you get: 

<img width="1552" alt="Screenshot 2020-12-11 at 12 32 59" src="https://user-images.githubusercontent.com/1794099/101899253-cecf3880-3bad-11eb-9a4b-f566c195a191.png">

There are two progress things

1. there is progress from the actual move operation in the explorer and the status bar
1. there is progress for the participant (the notification)

My plan is to fiddle with the working copy service (fyi @bpasero) to get rid of the second progress once the refactor preview shows. However, the first progress (explorer/status) would then still remain until the user accepts the workspace edit and I am unsure if that's actually good UI or not. 

There is background/meta about the preview and that's that preview should only show when being explicitly requested, like from rename. Java is using a trick to force preview (Which is to mark individual edits as needing confirmation). I am actually not happy with this and it is only a workaround for us not yet supporting preview in more places. E.g following the rename-symbol logic we should offer the user the choice if they want a preview or not

@isidorn Thoughts?

**Comment by isidorn** [comment]
I can speak from the user experience point of view: we already have some places where we show progress while a sort of user input is expected: debug when is started and asks for a debug type choice via quick pick, and we probalby have something similar in tasks.
The difference is that the Refactor Preview view is not really in the user face. However the progress is also not in the user face, since by default it will be a hidden notification which is only visible in the status bar + progress in explorer - so it is not anoying.
If refactor preview is something which we expect the user to fill in as soon as possible than I think this experience is fine. Especially if you atuomatically open refactor preview view (which you probably do)

Also would be cool if I can try this out easily to provide more feedback.

We can bring it up in a UX call for more feedback if needed...

**Comment by testforstephen** [comment]
> My plan is to fiddle with the working copy service to get rid of the second progress once the refactor preview shows. However, the first progress (explorer/status) would then still remain until the user accepts the workspace edit and I am unsure if that's actually good UI or not.

Showing participant notification while previewing edit is a bit jarring and should be hidden. But keeping progress in the status bar is not a problem for me because it doesn't interfere with my attention. Another issue is about the participant timeout, which I think should be disabled as well while previewing.

> There is background/meta about the preview and that's that preview should only show when being explicitly requested, like from rename. Java is using a trick to force preview (Which is to mark individual edits as needing confirmation). I am actually not happy with this and it is only a workaround for us not yet supporting preview in more places. E.g following the rename-symbol logic we should offer the user the choice if they want a preview or not.

When we introduced refactoring preview in Java, what we wanted was to let user aware that Java extension was refactoring their code, since composite rename undo was not supported at the time. In fact, when the preview is displayed, we also pop up a message box to give user a choice if they want to apply the refactoring automatically. If the user clicks `Refactor automatically` button, that will turn off the preview for all subsequent rename refactorings.
![image](https://user-images.githubusercontent.com/14052197/102175227-102b5500-3eda-11eb-9c1e-18b6ac786610.png)

**Comment by jrieken** [comment]
fyi @bpasero I have pushed https://github.com/microsoft/vscode/commit/af7edd782e127b06a1a2aa54c1d9da2bbe740a3f which moves the progress and cancellation of file participant down to its only customers (the api implementation). This allows me to stop progress when extensions have computed their participation results without accounting the "applying" of those results towards them. It raises the question if `addFileOperationParticipant` should become `setFileOperationParticipant`. I also wonder if I could just use the `onWillRunWorkingCopyFileOperation`-event, event tho it says it shouldn't...

**Comment by bpasero** [comment]
@jrieken I think the reason we separated the participant from the `onWillRunWorkingCopyFileOperation` was that we explicitly wanted the extensions to first participate and then the workbench. If we merge this all into one, we would have to ensure that we still maintain this ordering, which I think we could do, but not sure it is worth it. 

I am fine renaming the method, though if we go for a change I would prefer the one where we simply do everything through the event if we can ensure the order is preserved and the changes from the extensions are awaited for first.

**Comment by jrieken** [comment]
> I am fine renaming the method, though if we go for a change I would prefer the one where we simply do everything through the event if we can ensure the order is preserved and the changes from the extensions are awaited for first.

I like that the best as well. Tho, unsure to achieve this. We cannot use subscriber order because the mainThread-listener will unsubscribe and resubscribe when extension host restart. We would need some kind of property on the listener itself that expresses its order or priority and that's quite similar to having another event

**Comment by jrieken** [comment]
I have now pushed a change that brings back the ability to show the refactor preview while handling onWill-events. This is the sequence

* fire `onWill` events on the extension host and while those events are being handled show cancellable progress
* when the `onWill` handler finish, stop the participants progress but keep the explorer progress

The attached recording shows the flow. There is an artificial delay of 5sec in the participant so that the progress shows. Once the participant delivered its additional workspace edits the preview shows but no more cancellable progress

[Screen Recording 2020-12-17 at 10.15.39.mov.zip](https://github.com/microsoft/vscode/files/5708233/Screen.Recording.2020-12-17.at.10.15.39.mov.zip)

**Comment by jrieken** [comment]
@testforstephen I still wonder if there is better solution for what you have described in https://github.com/microsoft/vscode/issues/111878#issuecomment-745072265. My understanding is that you want to (1) inform the user that Java is participating in the file operation and (2) show a preview of what's going to happen. I think that's fair but this can maybe be improved like so

* we detect that an extension is participating in a file operation
* we tell the user about it and ask if they want to see a preview
* we allow the user to say "don't ask again" and so

The advantage of us owning this flow would be that it is consistent and Java wouldn't need to use the needsConfirmation-trick (which IMO is very error prone because it unselects some edits that you do need)

**Comment by jrieken** [comment]
The screen shots below show what I am implementing: When an extension participates in file operations with a workspace edit then the dialog shows. It allows to select between proceeding, showing a preview, or ignoring the extra edit. There is also a "do not show again" options which remembers the first two options but not the cancelling. The second screen capture shows a slight variation to this and that's when an edit is marked as needing confirmation. Today "needsConfirmation" is used as trick but there are actually valid scenarios in which refactoring are based on some level of "guessing"

<img width="1104" alt="Screenshot 2020-12-17 at 11 43 19" src="https://user-images.githubusercontent.com/1794099/102477796-1e55ae80-405d-11eb-8636-9f21b647c11f.png">


<img width="1104" alt="Screenshot 2020-12-17 at 11 42 34" src="https://user-images.githubusercontent.com/1794099/102477784-1ac22780-405d-11eb-802c-582549108c84.png">

**Comment by testforstephen** [comment]
Yes, `needsConfirmation` is a bit of a hack. To make sure the preview is triggered, we add a dummy text change with a needsConfirmation tag to the normal workspace edit, which causes only the dummy change to be unchecked while preview.

I definitely support the idea to make VS Code to own the logic of prompting the user whether to PREVIEW or not. I'm happy to get rid of the hack preview code In java extension.

Also I'm interested in the screenshot you shared, but have some questions.

> When an extension participates in file operations with a workspace edit then the dialog shows.

Do you mean that when an extension returns an edit via the waitUtil promise, then the dialog shows? Right?

Also the words "additional edits" in the dialog are too technical and unintuitive for me. 
- How about changing the message to `Extension 'Java Lang' wants to apply refactoring changes for this file operation.`? 
- And change the button `Skip additional edits` to `Skip the changes`?

**Comment by jrieken** [comment]
> Do you mean that when an extension returns an edit via the waitUtil promise, then the dialog shows? Right?

Yes - I wrote it so complicated because in theory an extension can participate in file operations without delivering a workspace edit. 

:+1: for your wording suggestions. I will update the code accordingly

**Comment by jrieken** [comment]
Updated wording

* uses "refactor changes"
* names the operation, e.g "with this file move"
* uses "Skip Changes" as option
<img width="455" alt="Screenshot 2020-12-17 at 16 09 52" src="https://user-images.githubusercontent.com/1794099/102505469-4f94a580-4082-11eb-896b-c2390cb16a3a.png">

**Comment by jrieken** [comment]
Most work is done, closing this now

**Comment by testforstephen** [comment]
![image](https://user-images.githubusercontent.com/14052197/104157925-25d36200-5427-11eb-8a62-f08377d67ef8.png)

The space between the buttons is not consistent, is this by design?

**Comment by jrieken** [comment]
> The space between the buttons is not consistent, is this by design?

I think so or at least I don't know of a way to how to influence that. And also, in the latest macOS version they look completely different

**Comment by isidorn** [comment]
Yeah, this is by design. We can not really control it, since Electron does the spacing. We can only change the order....

**Comment by testforstephen** [comment]
I see, thanks.

Another quick question about the checkbox "Don't ask again". Once i toggled it, how can i bring it back? Is there any preference to control that?

**Comment by jrieken** [comment]
Currently not... Tho, we are working on a generic way to handle those

**Comment by jrieken** [comment]
fyi @meganrogge more requests for "don't ask again" resetting

**Comment by jrieken** [comment]
To verify

* use this sample extension https://github.com/jrieken/sample-file-participant (or any other extension that adds extra edits during `onWill[Create|Rename|Delete]` events
* move a file
* acknowledge the prompt, follow each path and ensure it makes sense
* have a slow participate case (e.g move `samples/slow.txt`) and make sure there is progress that allows to cancel the participant
