### ISSUE TITLE
Cannot run extensions tests headless

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#111882]
I'd like to run extension tests in a CI or a TTY.

**Steps to Reproduce:**

1. Open a TTY (on Linux, press Ctrl+Alt+F1)
1. git clone https://github.com/microsoft/vscode-extension-samples
2. cd vscode-extension-samples/helloworld-test-sample
3. npm install
4. xvfb-run -a npm test

**Expected behavior**

The tests succeed

**Actual behavior**

The tests fail

**Additional information**

The `xvfb-run` command was taken [from the docs](https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions).

Install xvfb with `sudo apt install xvfb` on Ubuntu

Seems like extension tests cannot be run in an environment without graphic interface

Seems related to #103060 and #103113 but I don't use snap and those issues are closed

**Complete trace**
```
Found .vscode-test/vscode-1.51.1. Skipping download.
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2020-12-04T13:01:47.387Z] update#setState idle

[main 2020-12-04T13:01:47.388Z] update#ctor - manual checks only; automatic updates are disabled by user preference

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 


/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 


[26655:1204/140147.684597:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

/dev/fd/3: Aucun fichier ou dossier de ce type

Server response: 

Exit code:   null
Done

Failed to run tests

```

```
Version: 1.52.0-insider
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:44:34.000Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-123-generic
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I think we have https://github.com/microsoft/vscode-test/blob/master/sample/azure-pipelines.yml as an example for how to configure Azure pipelines to run extension tests.

**Comment by sguillia** [comment]
Thank you, it works

Seems like `xvfb-run` doesn't work in a TTY, but starting an Xvfb server does.

Some notes
- It makes some extensions crash, so I launch test with extensions disabled (`launchArgs: ["--disable-extensions"]`)
- You might want to add a TTY section in [this document](https://code.visualstudio.com/api/working-with-extensions/continuous-integration) if I'm not the only one doing this

Future developers might want to try this quickly-written script

```bash
#!/bin/bash
set -eux

# Start server
/usr/bin/Xvfb :99 -screen 0 1024x768x24 &
sleep 1

# Make sure it's running 
ps aux | grep Xvfb --color=always | grep -v grep

# Run tests
DISPLAY=:99.0 node ./dist/test/runTest.js

# Kill server
killall Xvfb
```
