### ISSUE TITLE
Terminal Process "node down

### ISSUE THREAD

**Issue by Basile13** [microsoft/vscode#111820]
Visual code studio version: 1.51.1
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Install Pymakr extension, add node JS on the system if not already there
2. Close VS Code and re-open it
3. 3 litle windows pop-up on the bottom left screen simultaneous 
![image](https://user-images.githubusercontent.com/55885109/101041488-b68f6600-357c-11eb-9d11-410c6d4d2ec9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
