### ISSUE TITLE
Error Icon on Manage (gear) when Settings json is formatted incorrectly

### ISSUE THREAD

**Issue by gateslm** [microsoft/vscode#111841]
## Problem
Working with students learning to program for the first time, we have them edit the settings manually (so they don't overwrite other settings by pasting in a file and do not get lost scrolling). Many of the students do not format the _user_ settings correctly which results in subsequent issues the new students don't understand. When helping them, we don't realize the settings were typed in incorrectly (especially helping remotely).

The instructions to modify the settings include all the formats, the students don't follow the instructions or don't understand why quotes and commas are needed. 

![image](https://user-images.githubusercontent.com/12010588/101083800-11c05900-357b-11eb-8a1a-1d6fd7995c6a.png)

## Feature
When there is an update, we see a blue 1 on the **Manage Gear** (pictured above). Is it possible to add a red icon on the gear if the `settings.json` file is unreadable for the _user settings_ (not the local/workspace folder `.vsc/settings.json`? Some sort of icon so people modifying the `setting.json` know there is an error. There are many that don't notice the red squiggle lines underneath. Hopefully it will save time when solving issue why VSC isn't finding the program path correctly. 

Any icon on the **Manage Gear** would be fine, as long as it distinguishes there is an error in the _user settings_.

**Comment by gateslm** [comment]
It is a feature request / suggestion. No issues when running Visual Studio Code. 

Feature suggestion to help handle user error.

**Comment by roblourens** [comment]
Out of curiosity, which settings are these students changing that can't be edited in the settings UI?

**Comment by gateslm** [comment]
Of course! This isn't a desperate feature, but after TAing this class for 6 semesters, students don't read the instructions fully and to save time when installing in lab, it is easier to have them type based on a list. 

Since the set-up tutorial is a nightmare to edit every semester, having them edit the setting in the `json` saves me time (since I can't easily get access to a "blank" computer to do the installation fresh each time to ensure the order hasn't changed and update screenshots). 

Most of the settings can be edited in the UI, but they are spread out all over the setting page. 

We normally have them change (Mac and Windows):
- `python.linting.enabled`
- `python.linting.pylintEnabled`
- `git.path` (Mac due to issues with `xcode` and older versions of the OS)
- `git.enableSmartCommit`
- `files.autoSave`
- `python.pythonPath`
- `terminal.integrated.shell.windows` (this is **rare** now with the terminal picker integrated into Windows ... but students still manage to cause a problem)


Now this can all be solved in the UI, just trying to optimize the installation process for a large class.
