### ISSUE TITLE
tqdm behaviour 

### ISSUE THREAD

**Issue by Bankimchandrayadav** [microsoft/vscode#111810]
- VSCode Version:
- OS Version: Windows10 Home single language

Steps to Reproduce:

1. using tqdm in notebook generates the message about hbox and its properties 
2. Progress bar should have been there

Sample code to reproduce that behaviour: 
`from tqdm.notebook import notebook as td`
`for i in td(range(0, 10000)):` 
`    c=1`

Please note: I have already updated ipywidgets 

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![Screenshot 2020-12-03 180044](https://user-images.githubusercontent.com/13675730/101018545-ac2b9700-3591-11eb-8828-03f5be0c02bd.png)

**Comment by rebornix** [comment]
please file issue agains the Jupyter extension https://github.com/microsoft/vscode-jupyter
