### ISSUE TITLE
Minimap showing old colors

### ISSUE THREAD

**Issue by Zakarya-Netlinks** [microsoft/vscode#111895]
Issue Type: <b>Bug</b>

Minimap showing old colors of theme though I have changed theme colors locally with custom CSS loader.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.00GB free)|
|Process Argv|--folder-uri file:///c%3A/xampp/htdocs/residential_passport --crash-reporter-id 5c5ac354-a12d-4fa4-9b9a-10cde9a6b290|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-model-snippets|ahi|2.0.0
laravel-blade-vscode|ami|2.0.3
vscode-intelephense-client|bme|1.5.4
vscode-tailwindcss|bra|0.5.4
path-intellisense|chr|2.3.0
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.16.0
flutter|Dar|3.16.0
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
vscode-html-css|ecm|0.9.6
EditorConfig|Edi|0.16.3
phpunit|ema|4.1.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
todo-tree|Gru|0.0.188
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
vscode-react-native|msj|1.1.1
vetur|oct|0.30.3
laravel-blade|one|1.25.0
laravel5-snippets|one|1.10.0
phpunit-snippets|one|1.1.0
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
vue-vscode-snippets|sdr|2.1.5
laravel-goto-controller|ste|0.0.12
hyper-javascript-snippets|t7y|2.5.0
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vue|Wsc|1.0.21
JavaScriptSnippets|xab|1.8.0
axios-snippets|Ygg|1.0.0

(3 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@Zakarya-Netlinks Can you describe how you changed the colors in more detail? Do you mean you changed the `workbench.colorCustomizations` setting, or manually changed part of VSCode's CSS?

**Comment by Zakarya-Netlinks** [comment]
I manually changed CSS like this
![image](https://user-images.githubusercontent.com/61266292/101189044-259bb600-3674-11eb-9f66-c525751e3e9e.png)

**Comment by RMacfarlane** [comment]
Where is this file saved? Please give me enough detail to repeat the process on my own machine

**Comment by Zakarya-Netlinks** [comment]
I installed this extension **Custom CSS and Js loader** then you have to enable it in settings and it needs a css file to apply on your vscode

**Comment by RMacfarlane** [comment]
Ok, thanks for clarifying! Unfortunately, this isn't an officially supported way of modifying the theme colors. You could try using the `"editor.semanticTokenColorCustomizations"` setting
