### ISSUE TITLE
editor.multiCursorModifier breaks ctrl-click

### ISSUE THREAD

**Issue by bvandenbon** [microsoft/vscode#111888]
- VSCode Version: 1.51.1
- OS Version: Windows 10

In editors like IntelliJ you can alt-drag to select multiple lines.
Then next, you can type on multiple lines at the same time.
This is sometimes called "column selection". 

To enable alt-drag in visual studio code, I have to set the following setting:
_(I know, this sounds a bit counter-intuitive, but to enable **alt**-drag you actually have to set it to "**ctrlCmd**".)_

    "editor.multiCursorModifier": "ctrlCmd"

And all was good, ... until I found out that it broke something else.
When i set this to `"ctrlCmd"`, then it's no longer possible to ctrl-click the code to navigate to function or class definitions.
I finally found, that if I set it back to `"alt"`, the problem is solved.

    "editor.multiCursorModifier": "alt"

Of course, then the column selection is broken again.

Is that a bug ?

**Comment by alexdima** [comment]
There are 3 features:
- multiple cursors: this is the ability to arbitrarily add a cursor anywhere somewhere in the file e.g.:
![image](https://user-images.githubusercontent.com/5047891/101200437-9340e580-3666-11eb-855c-e21371b7046a.png)
- column selection: this is the ability to add cursors/selections that are arranged on the same column (sometimes called box selection) e.g.:
![image](https://user-images.githubusercontent.com/5047891/101209982-08b3b280-3675-11eb-9474-ad69d1aed731.png)
- go to definition

---

#### `"editor.multiCursorModifier": "alt"`

* multiple cursors can be added using `alt+click` 
* column selection can be done via the toggle state in the Selection menu or via the middle mouse button
* go to definition can be done using `ctrl+click` or `cmd+click` on the mac

#### `"editor.multiCursorModifier": "ctrlCmd"`

* multiple cursors can be added using `ctrl+click` 
* column selection can be done via the toggle state in the Selection menu, via the middle mouse button, or via regular selection + alt pressed
* go to definition can be done using `alt+click`.

**Comment by bvandenbon** [comment]
@alexdima wow, thank you for clarifying that !
