### ISSUE TITLE
Explorer bulk edit and preview changes don't work well together

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111873]
To verify this in the Java extension, I changed the implementation of the rename refactoring by using the `workspace.onWillRenameFiles` handler, and now after I rename fileA.java to fileB.java, one undo will restore the refactor and the filename.

But I also found two potential problems about the willRenameFiles handler.

- The UI state is in chaos if the returned edit enables the preview flag.

If `FileWillRenameEvent.waitUntil()` returns a workspace edit with the preview flag enabled (e.g. add `needsConfirmation` properties), the UI state will be in chaos. See the screenshot below. It shows REFACTOR PREVIEW panel, but the file explorer is frozen and also shows the running notification.
![image](https://user-images.githubusercontent.com/14052197/101131662-a2ad3800-3640-11eb-91af-86e223084ba3.png)

_Originally posted by @testforstephen in https://github.com/microsoft/vscode/issues/111208#issuecomment-738621642_

**Comment by jrieken** [comment]
Adding to November to see if we can workaround this

**Comment by jrieken** [comment]
@isidorn my plan is to signal to the outside (the explorer) that preview is now active and in response the explorer should stop showing progress. makes sense? Did I find the right code place with [this method](https://github.com/microsoft/vscode/blob/564ff91763a0517e13351c2bb8ae88212a2603c7/src%2Fvs%2Fworkbench%2Fcontrib%2Ffiles%2Fbrowser%2FexplorerService.ts#L128)?

**Comment by isidorn** [comment]
@jrieken sounds good. Yeah that is the right code place. Everything goes through there.

**Comment by jrieken** [comment]
This is actually tricky... There is the explorer progress which can be tackled with some tricks but then there is also progress from the participants which shows from within the working copy service which is a layer below the bulk edit service, e.g it is unable to know about the preview 

<img width="761" alt="Screenshot 2020-12-04 at 12 09 38" src="https://user-images.githubusercontent.com/1794099/101157024-c913a900-3629-11eb-8b29-4e40f2fc74bf.png">

**Comment by jrieken** [comment]
There are actually multiple issues here

1. progress in the explorer while preview shows (1)
1. progress from the low-level participants (2)
1. onWill-handler being cancelled when forcing a preview

The last issue is actually not new, just became visible. Before my change for https://github.com/microsoft/vscode/issues/111208 we would silently cancel/skip onWill-handlers and the effect would be an error that the file has been modified in the meantime (because we stopped waiting for the onWill-handler and proceeded with the edit). 

Given the complexity of this and being late in the endgame requires tactical fix. That fix will be to prevent previews from onWill-handlers. With that participants are done when "their part of the work is done" and the previewing won't be account to them (since there is no preview).

**Comment by jrieken** [comment]
Closing and creating a debt-follow-up item

**Comment by jrieken** [comment]
I should not forget to mention that with this change everything is functional and that it is just the previewing that's disabled.

**Comment by jrieken** [comment]
follow up work: https://github.com/microsoft/vscode/issues/111878

**Comment by jrieken** [comment]
To  _verify_

* have an extension snippet as shown below
* move a file
* make sure the files contents have been updated
* make sure no refactor preview has been shown


```ts
    vscode.workspace.onWillRenameFiles(e => {

        const [first] = e.files;

        e.waitUntil(vscode.workspace.openTextDocument(first.oldUri).then(async doc => {
            await new Promise(resolve => setTimeout(resolve, 10000))
            const edit = new vscode.WorkspaceEdit();
            edit.insert(first.oldUri, new vscode.Position(0, 0), `I HAVE BEEN MOVED ${new Date().toDateString()}\n`, { label: 'Hello', needsConfirmation: true });
            return edit;
        }));
    })
```

**Comment by isidorn** [comment]
@jrieken Thanks for fixing this and for creating a follow up item. 
I can verify this.

**Comment by isidorn** [comment]
I have verified using the snippet - thus adding verified label.
@testforstephen would be great if you can also try this out and let us know? Hopefully there should be a VS Code insiders with this fix soon... Thanks

**Comment by testforstephen** [comment]
I tried the insider 2020-12-05 again, `e.waitUntil` ignores the preview flag and applies the edit directly. Undo also works. 

Feel free to loop me in with other remaining renaming issues. thanks.

**Comment by isidorn** [comment]
Thanks! We'll keep you up to date.
