### ISSUE TITLE
sign in and login problem

### ISSUE THREAD

**Issue by Tejas9900** [microsoft/vscode#111825]
Issue Type: <b>Feature Request</b>

I want to sign in and login in my visual studio code please help me with this!!!

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.3.9600

**Comment by RMacfarlane** [comment]
@Tejas9900 You can use the accounts icon above the settings gear on the activity bar to turn on settings sync and log in
<img width="393" alt="Screen Shot 2020-12-03 at 11 22 16 AM" src="https://user-images.githubusercontent.com/3672607/101077538-d19cae80-3559-11eb-805a-6b78e3f33a3e.png">

If you're having a problem with login itself, can you include more details about what's happening?

**Comment by Tejas9900** [comment]
Thank you for the helpSent from Samsung tablet.
-------- Original message --------From: Rachel Macfarlane <notifications@github.com> Date: 04/12/2020  12:53 am  (GMT+05:30) To: microsoft/vscode <vscode@noreply.github.com> Cc: Tejas9900 <tejpunjp@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [microsoft/vscode] sign in and login problem (#111825) 
@Tejas9900 You can use the accounts icon above the settings gear on the activity bar to turn on settings sync and log in

If you're having a problem with login itself, can you include more details about what's happening?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/vscode/issues/111825#issuecomment-738240206",
"url": "https://github.com/microsoft/vscode/issues/111825#issuecomment-738240206",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by RMacfarlane** [comment]
I'm going to go ahead and close this since it sounds like it's working for you now.
