### ISSUE TITLE
Remote explorer isn't respecting view order because of the ports view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111830]
It turns out that view contributed from within VS Code core aren't ordered based on their `group`. Instead, an `order` must be specified.

**Comment by alexr00** [comment]
@bchuecos FYI.

**Comment by rzhao271** [comment]
@alexr00 can you provide some steps to verify this issue?

I noticed that the ports view is now at the top of the remote explorer rather than at the bottom.

**Comment by alexr00** [comment]
To verify:
1. Open VS Code with a fresh `--user-data-dir`
2. Use either Codespaces or Remote-Containers to verify. Connect the remote of your choice from one of those extensions.
3. Open the Remote Explorer to the remote extension you chose for (2).
4. Verify that first there is the "explorer" view where you can choose which remote to connect to. 
5. Verify that the second view is the Ports view.
