### ISSUE TITLE
Graphic artefacts after updating to Pop_OS 20.10

### ISSUE THREAD

**Issue by RobMaskell** [microsoft/vscode#111847]
Issue Type: <b>Bug</b>

MBP 15" running Catalina 10.15.7 -> VMWare Fusion (11.5.7) -> Pop_OS VM

When the Pop_OS VM was running 20.04 vscode was super stable, after upgrade to 20.10 the graphic artefacts started appearing while running vscode and only for vscode getting worse the longer it was running until it became unusable.

Tried creating a fresh VM from 20.10 iso just in case and same issue.

Tried adding "disable-hardware-acceleration": true and problem seems to go away even on the original upgraded VM

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.8.0-7630-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (4 x 2807)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (2.59GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id cfecdeaf-77e1-4fc4-9e54-e2f81c47ec80|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
pgformatter|bra|1.16.0
vscode-lombok|Gab|1.0.1
terraform|has|2.3.0
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
vscode-spring-boot|Piv|1.23.0
java|red|0.72.0
vscode-gradle|ric|3.5.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-test|vsc|0.26.0
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.6.1
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by deepak1556** [comment]
Does the following [exploration build](https://az764295.vo.msecnd.net/exploration/25a4ee40993f43df9229edc552bd3018c086569d/code-exploration-x64-1607069110.tar.gz) run fine without disabling hw acceleration ?

**Comment by RobMaskell** [comment]
Initial testing and I can't see the artefacts, will test more tomorrow for a definitive answer

**Comment by RobMaskell** [comment]
I'm not seeing the same issues, it's back to being super stable and this seems to have fixed the debug console scrolling issues I was also seeing

**Comment by deepak1556** [comment]
Not in November, but will be available in insiders next week https://code.visualstudio.com/insiders and will be targeted for January 2021 stable release.
