### ISSUE TITLE
'When' expressions insert <space> before a '>' character automatically

### ISSUE THREAD

**Issue by berknam** [microsoft/vscode#111899]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Issue Type: <b>Bug</b>

The VSCodeVim extension has some keybindings that make use of the 'when' expressions. The 'Ctrl' based keybindings use a 'when' expression similar to this (for the "Ctrl+r" for example):
```jsonc
editorTextFocus && vim.active && vim.use<C-r>
```

However, vscode is automatically changing these expressions to the following:
```jsonc
editorTextFocus && vim.active && vim.use<C-r >
```

Notice the ' ' (space) between 'r' and '>'. If I try to manually edit the when expression and remove that space, vscode automatically inserts that space again, however it still changes the 'source' to 'User'. There is no way to remove that space.

This means that all keybindings that use this no longer work.

VS Code version: Code - Insiders 1.52.0-insider (5e350b1b79675cecdff224eb00f7bf62ae8789fc, 2020-12-04T10:15:27.849Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (2.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|1.17.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt859:30228413

```

</details>

Does this issue occur when all extensions are disabled?: (it creates an issue to an extension)

**Comment by berknam** [comment]
@alexdima I believe this is related to the following commits:
72defdc77c3dae16cff9ad97a8cf51389a944c55
16ffa1deffd6a843024686f91fa7fbd6e514b345
bbdbcd333bdf449f86c1084bc96c92785e2e0b41

I have also noticed that if I manually change the expression to this:
```jsonc
editorTextFocus && vim.active && vim.use<C-r> == true
```
 Then vscode correctly updates it to this:
```jsonc
editorTextFocus && vim.active && vim.use<C-r>
```

And the key works after this.

Is it possible to implement some kind of check before assuming that it is a "greaterThan" or "lessThan" expression? For example if both sides of the symbol are not numbers then it makes no sense to compare them?!

**Comment by gjsjohnmurray** [comment]
I think #110846 may have caused this.
