### ISSUE TITLE
IntelliSense popup in not expanding to the usual height

### ISSUE THREAD

**Issue by d-domingues** [microsoft/vscode#111819]
- VSCode Version: 1.51.1
- OS Version: windows 10

For some reason, my vs code intelliSense popup height is too small, I just woke up one day and it was like this, I didn't change any settings at settings.json, I also tried to comment all the settings and reinstalled VS Code but the problem remained.

![image](https://user-images.githubusercontent.com/49404822/101028463-0d933c00-3579-11eb-8cd5-a546297e6753.png)

**Comment by gjsjohnmurray** [comment]
Probably #110971

Please try again after running the command to reset suggest widget size (F1 > Reset Suggest Widget Size)

**Comment by d-domingues** [comment]
You are my savior, It worked...
