### ISSUE TITLE
Vscode drains up to 30% battery while sleeping MacBook Pro 16 ( 2020 )

### ISSUE THREAD

**Issue by AniketMalik** [microsoft/vscode#111805]
- VSCode Version: 
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

- OS Version:
macOS Big Sur 11.0.1 (20B29)

Steps to Reproduce:

1. Open any project ( in my case Flutter project ) ( fairly small project )
2. Leave 3-4 tabs open and minimise the window and leave it like this overnight. 

Does this issue occur when all extensions are disabled?
Did not check for it.

I left my MacBook Pro 16 at 100% battery overnight ( logged in back after about 10 - 12 hours ) with vscode window open but minimised and found that the battery had dropped to 55% - 60% ( almost everyday for 3 days continue ). I followed all the macOS steps to resolve this issue but did not help.

I checked the activity monitor's energy consumption and found that vscode has used 19.6 - 28.8 units in the last 12 hours on battery.

I experimented and closed vscode one night before sleeping at 70% battery power and found it to be only 67% the next day after about 10 hours.

**Comment by radixof2** [comment]
Here is my configuration -
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB
  System Firmware Version:	6723.61.3
  System Version:	macOS 11.1 (20C69)

I too am seeing battery drain. In my situation VS Code is not even in background. 12 Hour Power  in Energy tab of Activity Monitor is showing me 203.15, the highest usage on my system on the top the process is not even running.

**Comment by mitchross** [comment]
Same issue here

**Comment by DmitryNevmerzhitsky** [comment]
Same issue, but with MacBook Pro (15-inch, 2018)

**Comment by AniketMalik** [comment]
I figured that the issue was not specifically from vscode. The culprit was icloud contacts syncing from a process "AddressBookSourceSync".

Please check if your mac is not able to go to sleep mode.
From the terminal app run `pmset -g`. You will be able to see something like "ProgramX prevent from sleeping". Then that programX is the one you should troubleshoot.

I tried every thing to stop AddressBookSourceSync but nothing worked until I removed all the internet accounts from the settings and added then after some days. Specifically I removed all the google accounts without any success. But I was able to solve the issue by removing icloud account and adding it back after a few days.

**Comment by DmitryNevmerzhitsky** [comment]
> I figured that the issue was not specifically from vscode. The culprit was icloud contacts syncing from a process "AddressBookSourceSync".
> 
> Please check if your mac is not able to go to sleep mode.
> From the terminal app run `pmset -g`. You will be able to see something like "ProgramX prevent from sleeping". Then that programX is the one you should troubleshoot.
> 
> I tried every thing to stop AddressBookSourceSync but nothing worked until I removed all the internet accounts from the settings and added then after some days. Specifically I removed all the google accounts without any success. But I was able to solve the issue by removing icloud account and adding it back after a few days.
> 
> Hence closing this issue.

Thank you for help. But i don`t have any "ProgramX prevent from sleeping". I got this problem after upgrading to Big Sur.
I left my mbp for two hours and got this(pic).
Maybe this problem is not related to vscode. 
I will do more detailed tests with different apps.
<img width="887" alt="Screenshot_2021-02-12 17 22 48_70orIW" src="https://user-images.githubusercontent.com/8275782/107788507-28dcad80-6d59-11eb-9277-775a230412db.png">


p.s. My hibernate mode is 3.

**Comment by AniketMalik** [comment]
@DmitryNevmerzhitsky I changed my hibernate mode to 25 as well to counter this issue but unless I removed the icloud account the problem didn't leave me.

MacOS version Big sur 11.2.1
