### ISSUE TITLE
Allow folder settings to cascade / be inherited

### ISSUE THREAD

**Issue by hilari0n** [microsoft/vscode#111884]
As we're working with many complex Git repositories, where some repositories host many projects or even solutions (sets of tools for some common scope), some repositories hosting many resources (documentation, graphics libraries, translations), etc. and we work on different levels of those repositories (whole repo folder, solution sub-folder, project sub-folder, resource sub-folder) at different levels of the hierarchies, the current approach of only having 3 levels of settings, where only 2 can host repository-specific configuration (as user settings are local), i.e. the workspace and folder settings, it's hard to provide locally appropriate settings.
E.g. if we'd like to provide configuration which applies to a folder lowest in hierarchy, but be effective regardless, if you open the whole repository folder, any of the parent folders or a workspace, we'd have to copy-paste the folder's specific configuration to all possible levels (all settings for folders above that one and sometimes also one or more workspace settings).

My suggestion would be to allow (as an option) for the ".vscode" settings of folders to cascade to sub-folders.
E.g. if you would be working with folder "/x/y" and would open "/x/y/z/q.txt" file, the vscode would look for ".vscode" in all the folder hierarchy levels, from "/x/y/z/.vscode" up to "/.vscode" (unless at any level, the cascading option is not enabled) and use all the settings found there, with the settings present deeper in the folder hierarchy, overriding the ones from parent folders. There would need to be some additional logic to it (e.g. where settings refer to file locations / paths, those would need to use appropriate folder as base for the location/path expressions).

It could work similarly to how ".editorconfig" files work, with the difference of the "root" flag being on by default, to maintain backward-compatibility, and where the folder hierarchy settings would still be "merged" with workspace and user settings.

**Comment by hilari0n** [comment]
> /duplicate

@sandy081:
Uhm... Duplicate of what? I did search existing issues and could not find anything not closed.
And I'm not reporting an actual issue, but filing a feature request (and I did use the appropriate template for feature requests, I believe).

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/32693
