### ISSUE TITLE
openExternal('vscode://external/..') should be handled internally

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#111814]
Testing scenario https://github.com/microsoft/vssaas-planning/issues/1593 in Codespaces web UI

- Opening a Python file in a fresh codespace Web UI shows a notification:
![image](https://user-images.githubusercontent.com/6461412/101021812-b2f5e200-3570-11eb-9a10-dec6497a3fff.png)
- Clicking on Yes shows
![image](https://user-images.githubusercontent.com/6461412/101021892-d6b92800-3570-11eb-9518-ddda33a5a42d.png)
- VSCode desktop is opened

Python calls `env.openExternal( '${appEnv.uriScheme}:extension/${PYLANCE_EXTENSION_ID}';`

VSCode should intercept that URI and handle it by directly opening the extensions viewlet and not make an external call

**Comment by sandy081** [comment]
Unassigning myself as it seems url handling related.

Please let me know if there is something I have to do in extensions area.

**Comment by joaomoreno** [comment]
@jrieken What do you think? Should we perform the fast-track to handle these URIs internally?

**Comment by joaomoreno** [comment]
I can't repro this in desktop Code. 🤔

**Comment by aeschli** [comment]
I couldn't get the Python extension to show that dialog again, so I verified that with my own extension that does
```
	const PYLANCE_EXTENSION_ID = 'ms-python.vscode-pylance';
	const urlToOpen = vscode.Uri.parse(`${vscode.env.uriScheme}:extension/${PYLANCE_EXTENSION_ID}`);
	vscode.env.openExternal(urlToOpen);
```
That code is inspired by https://github.com/microsoft/vscode-python/blob/3698950c97982f31bb9dbfc19c4cd8308acda284/src/client/languageServices/proposeLanguageServerBanner.ts#L24

That code works and, on codepsaces now opens the extension viewlet.

However, if you do `vscode.Uri.parse(`${vscode.env.uriScheme}:/extension/${PYLANCE_EXTENSION_ID}`);` it opens the external open dialog again.

In the first case the URL has a relative path (`extension/${PYLANCE_EXTENSION_ID}`), in the second one an absolute (`/extension/${PYLANCE_EXTENSION_ID}`). Relative paths are kind of rare.
@joaomoreno Is that all as designed? Or would it be better to also accept the absolute path?

**Comment by joaomoreno** [comment]
@aeschli Paths are not required to be rooted in `/`, or even separated by `/` characters: they can be arbitrary strings within the allowed character set. We've long defined extension URIs to simply be `extension/<ID>`.

**Comment by joaomoreno** [comment]
I will have to revert the fix for this, since it broke existing functionality. With the fix, a web extension can no longer actually open a URI in desktop Code.

> VSCode should intercept that URI and handle it by directly opening the extensions viewlet and not make an external call

When looking at the breakage, I no longer this this is true. If `openExternal` is invoked, it should always be handled externally, never internally, unless it's absolutely obvious (running in Desktop).

The right way to move forward here is to have the Python extension run the `extension.open` instead of calling `openExternal`.
