### ISSUE TITLE
Primitives completion is not working

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11187]
Testing #10997

```javascript
function Person(name, age) {
    this.name = name;
    this.age = age;
}
Person.prototype.greet = function(whom) {
    console.log('Hello ' + whom.name + ', my name is ' + this.name); // <---- BREAKPOINT HERE
}

Student.prototype = Object.create(Person.prototype);
function Student(name, age, school) {
    Person.call(this, name, age);
    this.school = school;
}
Student.prototype.getSchool = function() {
    return this.school;
}

var a = new Person('John', 20);
var b = new Student('Charlie', 20, 'UNI');
a.greet(b);
```

When typing `'hello'.` or `5.` I would expect to get functions and properties available on the constants I defined. I use this a lot in Chromium to find a method and try it out quickly. At the moment, I get global suggestions such as `Buffer` or `console` which results in an invalid expression error.

**Comment by isidorn** [comment]
The list of suggestions is coming from the node debug adapter, thus forwarding to @weinand

**Comment by roblourens** [comment]
This works, but I'm not sure whether it should work in the `5.` case. It will prompt you to complete it like `5.toString()` but this is not valid syntax. And it works because the debug adapter wraps the input before the dot in `()`. Feels wrong to me. It doesn't work in Chrome. Any other thoughts?

**Comment by sandy081** [comment]
I agree with @roblourens. Showing proposals for numbers does not makes sense. Also `5.toString()` is not a valid syntax and doing this will give an error. Hence we should not show.

@weinand Shall I open a new issue for this?

**Comment by sandy081** [comment]
![screen shot 2016-09-02 at 10 45 51](https://cloud.githubusercontent.com/assets/10746682/18197974/717e3ba4-70fa-11e6-8085-3a413ec43b76.png)

**Comment by weinand** [comment]
@sandy081  yes, please create a new issue (but I do not intend to fix that behaviour).

The proposals are valid for the type 'number' and they are still helpful for @alexandrudima use case.

Since I do not have a JavaScript parser/scanner available, I do not want to start validating JavaScript expression. There is an infinite number of incorrect expressions where we still return IntelliSense.
