### ISSUE TITLE
Vs code keeps opening

### ISSUE THREAD

**Issue by jiglo77** [microsoft/vscode#111881]
Everytime i start vs code on my pc, it will open alot of windows and it will keep opening, the only way to stop it from keeping opening is when i restart my pc.

- VSCode Version: latest
- OS Version: win 10

Steps to Reproduce:

1. i dont know how i did this

Does this issue occur when all extensions are disabled?: i dont know, havent had the chance

**Comment by bpasero** [comment]
@jiglo77 does it eventually stop? do these windows maybe have "Untitled Workspace" in their name?

**Comment by jiglo77** [comment]
I have made a video of what happens because i cant really describe what exactly happens

here is the link: https://youtu.be/ra-OCjD_ptQ

**Comment by bpasero** [comment]
@jiglo77 can you try to open a terminal and type "code <folder>" to force only 1 window to open, does that help?

**Comment by jiglo77** [comment]
how do i do that? is it just win key and then type "code" and then hit enter?

**Comment by bpasero** [comment]
@jiglo77 
* win key
* type "command prompt"
* enter
* type "code <path to some folder>"

**Comment by jiglo77** [comment]
it doesnt work, i get this
![Knipsel](https://user-images.githubusercontent.com/75481742/101278771-0f017600-37be-11eb-8eae-5ee8ff1d98e0.PNG)

**Comment by bpasero** [comment]
When you install VSCode you can check to put "code" on the path, maybe try to reinstall and pick that option.

**Comment by jiglo77** [comment]
VSCode still opens unlimited windows, even with the re-install

**Comment by jiglo77** [comment]
i also added it to path

**Comment by bpasero** [comment]
@jiglo77 can you check if there are folders inside `%APPDATA%\Code\Workspaces` and if the contents of `%APPDATA%\Code\Backups`

**Comment by jiglo77** [comment]
i do not have a folder called workspaces, i do have a file in %APPDATA%\Code\Backups called "workspaces.json"

**Comment by bpasero** [comment]
If you run `code --user-data-dir <some new folder>` I assume it no longer happens right? To explain, my theory is that some previous state you accumulated causes these windows to appear. You could also rename that folder in `%APPDATA%` to start totally fresh.

**Comment by jiglo77** [comment]
how do i do thath?

**Comment by bpasero** [comment]
From a windows command prompt.

**Comment by jiglo77** [comment]
i dont know what to type, with all the things i tried it says that it is not an internal command

**Comment by bpasero** [comment]
Then I suggest to stop any running instance of VSCode, rename `%APPDATA%\Code` to `%APPDATA%\Code-Old` and start Code normally again, it should be fine.
