### ISSUE TITLE
Should send a single FileWillRenameEvent instead of separate events when moving multiple files at once

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#111867]
Currently, if I drag and drop multiple files to a new location at once, the VS Code File Event API `workspace.onWillRenameFiles` will send a separate FileWillRenameEvent for each file to be moved. If i choose to use FileWillRenameEvent.waitUtil() to return the refactored edit, that means each event will return a separate edit and the client will call the applyEdit operation multiple times. This is inconvenient for undo operation.

It's better to send a single FileWillRenameEvent instead of separate events when moving multiple files at once.

**Comment by jrieken** [comment]
Very good find. We have [this loop](https://github.com/microsoft/vscode/blob/49ef641300f992f091af92605cc0a1d6366e3763/src%2Fvs%2Fworkbench%2Fcontrib%2FbulkEdit%2Fbrowser%2FbulkFileEdits.ts#L241-L267) which goes over all resource edits and instead of the going one-by-one it should create buckets of equal operation types (likely without changing the order) and then apply a bucket at once

**Comment by jrieken** [comment]
This needs support from the working copy service. For instance, delete only supports a single options bag but multiple resources. Today, we ask the file- & config-service [for a single resource](https://github.com/microsoft/vscode/blob/49ef641300f992f091af92605cc0a1d6366e3763/src%2Fvs%2Fworkbench%2Fcontrib%2FbulkEdit%2Fbrowser%2FbulkFileEdits.ts#L177-L178) whether to use trash or not but I don't see how that's possible with different resources from potentially different schemes/providers. There are similar issues with copying multiple files but using different `overwrite` settings etc

**Comment by bpasero** [comment]
@isidorn let me know if you are interested in a PR to change the working copy file service to support options per resource. I think the support for bulk came in later (via a PR) but we should have also allowed the options to be specified per resource. Instead of adding another options array I would probably just allow to pass in resource and options in one object.

**Comment by isidorn** [comment]
@bpasero yeah, I can look into a PR. Will do it early next week.

**Comment by jrieken** [comment]
@isidorn can you ping when you have done that PR

**Comment by isidorn** [comment]
Will do, started to look into it now...

**Comment by isidorn** [comment]
Created PR https://github.com/microsoft/vscode/pull/112760

**Comment by bpasero** [comment]
Is this done?

**Comment by jrieken** [comment]
Nope

**Comment by jrieken** [comment]
@isidorn I am confused why creating doesn't support multiple resources at once while everything else does. Like, undoing a "multi delete" is now separate create operations

**Comment by isidorn** [comment]
@jrieken originally I did the create to support multiple resources, however after [discussion](https://github.com/microsoft/vscode/pull/112760#pullrequestreview-555447864) with @bpasero I reverted back to only support a single operation. 

I can move back to multi operation support. Though let's see if @bpasero is fine with that

**Comment by bpasero** [comment]
I have no feelings.

**Comment by isidorn** [comment]
Okey so I will bring back the support for multi create. I will push directly to master and ping you Ben on the commit.

**Comment by isidorn** [comment]
I have just pushed a commit that tackles this d51e1fa471
I did not adopt this fully in the `bulkFileEdits` since I thought you are wokring on it @jrieken Let me know if you would like me to look into that

**Comment by jrieken** [comment]
Thanks @isidorn. I am almost done with the adoption

**Comment by bpasero** [comment]
@isidorn checked out the change, it seems that the API now allows for multiple create operations, but within, we are not wiring this in properly (I think that was my initial feedback too that made us go back to supporting just 1 operation).

Specifically, shouldn't we use the array of things to create when passing on to the participants and eventing:

https://github.com/microsoft/vscode/blob/d51e1fa47187ef78739b83dc9b3b5d21b14031c5/src/vs/workbench/services/workingCopy/common/workingCopyFileService.ts#L293-L293

https://github.com/microsoft/vscode/blob/d51e1fa47187ef78739b83dc9b3b5d21b14031c5/src/vs/workbench/services/workingCopy/common/workingCopyFileService.ts#L296-L296

Maybe @jrieken can clarify if this kind of change is still needed or not.

**Comment by jrieken** [comment]
Yes - the event should be fired for many resources. There is a skipped/failing test here: https://github.com/microsoft/vscode/blob/0cb7dad36f07a6f88d4602942c0b85ae4c5bfdde/extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts#L1008-L1009

**Comment by isidorn** [comment]
@bpasero thanks for the feedback, I have created this PR https://github.com/microsoft/vscode/pull/113919 to tackle it

**Comment by jrieken** [comment]
Closing. This is now done. @testforstephen please try this out with next insiders. Thanks

**Comment by testforstephen** [comment]
I have played with the insider on 2021-01-08, moving multiple files will be grouped to one FileWillRenameEvent, which works well for me. Thanks for this great fix.

**Comment by isidorn** [comment]
Thanks a lot for trying it out. Adding verified label based on your comment.
