### ISSUE TITLE
editor.action.refactor command not accessible after removing the keybinding

### ISSUE THREAD

**Issue by AnthonyWeston** [microsoft/vscode#111826]
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open the Keyboard Shortcuts tab (File -> Preferences -> Shortcuts)
2. Remove the default Ctrl+Shift+R keybinding for the editor.action.refactor command
3. Search for `editor.action.refactor` by the name of the command or by its display name "Refactor..." in order to reassign the keybinding
4. The command does not appear in any search result

I have the following keybinding in my keybindings.json file. Removing it restores the original keybinding and makes it searchable again:
```
    {
        "key": "ctrl+shift+r",
        "command": "-editor.action.refactor",
        "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    },
```

Modifying the keybinding adds the following to my keybindings.json file, and the command remains searchable:
```
    {
        "key": "ctrl+tab ctrl+r",
        "command": "editor.action.refactor",
        "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    },
    {
        "key": "ctrl+shift+r",
        "command": "-editor.action.refactor",
        "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    }
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/84072
