### ISSUE TITLE
Issue reporter leaks promise

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111871]
related/finding of https://github.com/microsoft/vscode/issues/111666#issuecomment-738636856

The issue reporter never resolves it promise meaning everyone waiting for it will leak. 

https://github.com/microsoft/vscode/blob/37e9cceddc5f8e8fe504378b04ebd7388beb6601/src%2Fvs%2Fplatform%2Fissue%2Felectron-main%2FissueMainService.ts#L189

**Comment by RMacfarlane** [comment]
😱 wow I can't believe this has been like this for so long. Since it looks like you already have a workaround for this, I'll fix this next iteration
