### ISSUE TITLE
why shortcut changed a lot?

### ISSUE THREAD

**Issue by kastier** [microsoft/vscode#111860]
Issue Type: <b>Feature Request</b>

ctrl+w is not for close editor anymore
ctrl +n is not for new file anymore?
why?????

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by ryan-allen** [comment]
latest insider build has done something to my control commands but i'm still debugging, vscodevim is not behaving the same as it did from yesterdays insiders, when i find out more information i'll edit this comment!

**Comment by yume-chan** [comment]
> latest insider build

Looks like the op is not using insider builds though

**Comment by ryan-allen** [comment]
@yume-chan ah yes this is true, i reset all my settings and extensions and have been unable to reproduce the problem, sorry!

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you see any mentions of these keybindings if you open `keybindings.json` (<kbd>F1</kbd> and `>Preferences: Open Keyboard Shortcuts (JSON)`)
