### ISSUE TITLE
box appears instead of icons

### ISSUE THREAD

**Issue by bharatadk** [microsoft/vscode#111858]
Issue Type: <b>Bug</b>

while opening vscode , sometimes icons loads but most of the times icons do not load and box appear instead

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.94GB free)|
|Process Argv|--crash-reporter-id 8ce826da-90cb-485b-bbcb-036ca4f83aa9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
coldcode|eri|1.1.0
kite|kit|0.135.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
material-icon-theme|PKi|4.4.0
vscode-yaml|red|0.13.0
material-theme|zhu|3.9.11

(2 theme extensions excluded)

</details>

**Comment by bharatadk** [comment]
![image](https://user-images.githubusercontent.com/51126350/101114916-88586780-360a-11eb-835b-eb7a5dee1995.png)

**Comment by bharatadk** [comment]
![image](https://user-images.githubusercontent.com/51126350/101114960-9d34fb00-360a-11eb-88b5-7f36688c54ca.png)

**Comment by aeschli** [comment]
With what theme do you see this?

Can you open the dev tools (`Developer: Toggle Developer Tools`) and see if there's anything in the console?
Also look at the 'Network' tab, press reload (Ctrl +r) and see if there are problems with loading icons.

@deepak1556 @misolori  https://github.com/microsoft/vscode/issues/110288 is likely the same issue and the workaround was to reinstall the font. But instead of a workaround, I'd rather understand the real problem.

**Comment by bharatadk** [comment]
i used mac type font rendering. When i excluded VS Code in process manager
of font rendering , the problem is solved. Now everything is fine.
