### ISSUE TITLE
Remote explorer of Codespaces needs a "nudge" after logging in

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#111822]
Brand new machine, installed VS Code, enabled Settings Sync, allowed Codespaces extension to login to Github

🐛 Remote explorer doesn't show any codespace, need to hit refresh or "sign in", despite that doing nothing at all

![recording](https://user-images.githubusercontent.com/22350/101044604-61c7fd00-3534-11eb-9a21-96839ab8fb38.gif)

**Comment by alexr00** [comment]
Moved to codespaces
