### ISSUE TITLE
Search Editor improvement suggestion

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#111887]
I'd like to propose a more tight design, resembling the layout of Beyond Compare.

I propose to omit the blank line and instead add a separator line between find ranges:

![Search editor proposal](https://user-images.githubusercontent.com/9283914/101096805-633f0700-35c0-11eb-95ba-e55127ee8b82.gif)

**Comment by JacksonKearl** [comment]
Thanks for the suggestion! Unfortunately that's not really feasible given the search editor architecture.
