### ISSUE TITLE
Allow to disable thin srollbar for scrolling tabs

### ISSUE THREAD

**Issue by TIMONz1535** [microsoft/vscode#111817]
- VSCode Version: 1.51.1
- OS Version: Windows 10

I endured for a very long time, but still decided to write this issue. Every day I face the problem that I do not get to the file tab. Instead, I am dropped a couple of pixels below, on the title scrollbar. This causes the tab list of files to travel very far, causing pain and anger every time. It is not even visually highlighted in any way, because the title scrollbar appears only on hover.

Watch video:
https://i.imgur.com/i484WcP.mp4

1) I don't see the point in being able to click on the **thin** title srollbar, because you need to get into 3 pixels. So no one will drag it specifically targeting with the cursor, this is useful only on a **wide** title srollbar. In reality, when the scrollbar is **thin** you are using the **mouse wheel**.
2) I hover over an area where there is no most visible scrollbar button, but when I click, everything goes to the side. This behavior is valid only for the scrollbar where the rest of the area is **visible**, but here it is not visible.
3) When you hover, you can see that initially cursor looks like a hand for a fraction of a second. In next frame the cursor becomes normal, indicating that you hovering over the scrollbar control.
4) I just want to **completely disable this evil title srollbar**. But this is impossible. Every time i get a couple of pixels lower than necessary i suffer ((((((

Please make it so that I can either disable this scrollbar, or disable the ability to click at it (leave it only visually). Or an option that replaces the scrollbar with buttons. Or make the list of all tabs appear as a ladder, like Microsoft Visual Studio, without scrolling.

Steps to Reproduce:

1. Try switching between open tabs
2. Congratulations! In 50% of cases you got a couple of pixels lower than you need and your scrollbar left for another kingdom :(

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
I don't think it can be turned off, but you can use `workbench.editor.titleScrollbarSizing` to make it thicker.

**Comment by TIMONz1535** [comment]
> 
> 
> I don't think it can be turned off, but you can use `workbench.editor.titleScrollbarSizing` to make it thicker.

I tried, but getting into the tab becomes completely unrealistic.

That is, there is such a situation, I have to switch between files. I could use **Mouse4/Mouse5** between files as in **Notepad++**. But if it's just the next tab/previous tab, **VS Code** just like in **Visual Studio**, this is the previous file being edited/the next file being edited.
**Notepad++** also has buttons to switch left and right.
In the **Visual Studio**, all tabs are always visible and I calmly hit them. **VS Code** has one-line toolbar, and the presence of a scroll that bumps over the buttons instead of being under them. I visually hover over the tab, click, but in reality I get into the scrollbar, which a moment ago was not there until I hover over.

**Comment by TIMONz1535** [comment]
Another example of solution without a scrollbar.
![изображение](https://user-images.githubusercontent.com/7351599/101062107-0c7f0080-35b3-11eb-93e7-303da214cb50.png)

**Comment by Ivorforce** [comment]
100 times this. I think disabling interactability of the scrollbar would be enough, but hiding the whole thing might be better. I will _never_ want to click a tab scrollbar, and I have never seen this feature in tab views in any major software before. I click this thing accidentally at least 10 times a day.

**Comment by benibenj** [comment]
The scrollbar can be disabled in the settings by setting `Workbench > Editor > Title Scrollbar Visibility` to hidden.
