### ISSUE TITLE
Vim: <kbd>ctrl</kbd> + <kbd>d</kbd> doesn't work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#11180]
testing #11127:

<kbd>ctrl</kbd> + <kbd>d</kbd> and 🔢 <kbd>ctrl</kbd> + <kbd>d</kbd> neither work on macOS nor on Windows 10 (I'm using a Swiss-German keyboard).

**Comment by sandy081** [comment]
<kbd>ctrl</kbd> + <kbd>d</kbd> works for me with US and Swiss-German keyboards. We have an editor command in VS Code and our Vim sample binds this keys to this keys. I do not know where the issue is. 

Let me change the key binding and check

**Comment by sandy081** [comment]
This issue was moved to VSCodeVim/Vim#679
