### ISSUE TITLE
Visual Studio Code on exit kills a external .exe process to which a C# debugger was attached

### ISSUE THREAD

**Issue by artur170dx** [microsoft/vscode#111891]
Hello. I am using vs code and ms-dotnettools.csharp extension to debug an external .exe process written in C# .NET 4.6 Framework. I am attaching to this process with below configuration

```
"configurations": [
     {
         "name": "Attach to ConsoleApp",
         "type":"clr",
         "request": "attach",
         "processName": "ConsoleApp",
     }]
```

This works pretty fine to the point when I close Visual Studio Code after a breakpoint is hit and make some debug steps. The application to which the process was attached crashes without any information, even the windows Event viewer is empty of any information. However, stopping the debugger, without closing the VSCode works very fine, this is why I assume this could be a vscode issue, not the C# extension itself. Although this crash is not happening each time, for example, I more often reproduce it on a slower VM than on a faster local system.

What happens when VSCode is closing? Will it stop the running extension gracefully?

- VSCode Version: 1.51.1
- OS Version: Windows 10.0.18363
- ms-dotnettools.csharp Version: 1.23.6

Steps to Reproduce:

1. Build a .NET x64 exe application with DebugType portable
2. Run the exe.
3. Open VSCode with C# extension.
4. Run the debugger that will attach to the running exe.
5. Place a breakpoint.
6. Breakpoint is hit.
7. Make some debug steps.
8. Close Visual Studio Code.
9. The .exe to which the debugger was attached crashes without any information.

Does this issue occur when all extensions are disabled?: No. This issue requires the ms-dotnettools.csharp extension

I asked the same question/bug report on [StackOverflow](https://stackoverflow.com/questions/65143468/visual-studio-code-on-exit-kills-a-external-exe-process-to-which-a-c-sharp-debu)

**Comment by weinand** [comment]
VS Code shuts down extension gracefully. But if that takes too long, VS Code exits.

**Comment by artur170dx** [comment]
> 
> 
> VS Code shuts down extension gracefully. But if that takes too long, VS Code exits.

@weinand Ok, I understand. So I believe the reason is, if an extension is taking too long to quit, the VSCode will terminate it, so vscode will not hang on exit when some extension is taking too long to exit. But what if some actions require more time to properly stop its processes?  In case of this issue - it is disconnecting the debugger. Sadly the result is an application crash. 

After your suggestion, I have created an issue in the extension and [here](https://github.com/OmniSharp/omnisharp-vscode/issues/4264#issuecomment-745000968) is the reply.

My question is: Is it possible to change the behavior for some extensions on exit? Can the vscode just execute an async CloseExtension() and do not await for the result, nor terminate it after some time?
