### ISSUE TITLE
Resolution hover message incorrect

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#111853]
Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

In a package.json file with a `resolutions` field, the description given is the same as that for the `dependencies` field.

Expected: some text about the following:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

Actual:
![resolutions-hover](https://user-images.githubusercontent.com/7199958/101098201-63ff7b00-3577-11eb-8bbd-64522cf724b6.PNG)

**Comment by ashtongao** [comment]
1. After debugging in vscode, i found that the definition of resolutions comes from schema service.

![image](https://user-images.githubusercontent.com/45849828/101468315-32731f00-397e-11eb-9ce0-59a06407872b.png)

2. However, the schema service is offered by another repo —— [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice).


3. In another repo, the scheme service provides the  definition from the online schema store —— https://json.schemastore.org/package

4. And the definition of resolutions is quoted from dependency. This may be the reason of the problem.

```
    "resolutions": {
      "$ref": "#/definitions/dependency"
    }
```

**Comment by ashtongao** [comment]
It has been fixed in pr —— https://github.com/SchemaStore/schemastore/pull/1391

![image](https://user-images.githubusercontent.com/45849828/101714277-31ec9c80-3ad4-11eb-8c5c-a2f272793ebc.png)

**Comment by egamma** [comment]
@ashtongao thanks for the update, closing.
