### ISSUE TITLE
E2E Python: Extension view would just die after searching

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111862]
Refs: https://github.com/microsoft/vssaas-planning/issues/1593

After failing to install Pylance from the notification (https://github.com/microsoft/vssaas-planning/issues/1704), I then tried to install the extension manually from the Extensions view, and that view was just dead

  ![image](https://user-images.githubusercontent.com/641685/100916953-7eb4ef80-34a4-11eb-91e6-e56f2425e38b.png)

Even after a reload, the extension view won't search, and it kills the view

**Comment by sandy081** [comment]
@eamodio Can you please provide more info or steps to reproduce here?

**Comment by eamodio** [comment]
@sandy081 I can't get to that codespace anymore (it says failed to fetch) or any others it seems.

But just opening the Extensions view and searching for any extension just caused the view to blank out and spin forever.

**Comment by sandy081** [comment]
I cannot reproduce in other codespaces. This could happen if codespace connection is slow or not responding.

**Comment by aeschli** [comment]
Oh, interesting, I ran into the same issue, in the same scenario, also when searching for extension: In my case it was a connection issue: github/codespaces#1906.

**Comment by sandy081** [comment]
I would think it is connection issue. Hence marking this as dup.
