### ISSUE TITLE
Web: while file upload is in progress Explorer is ignoring clicks

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#111832]
1. `yarn web`
2. Drag and drop a large folder from outside into VS Code in web
3. While the upload is in progress -> click in explorer -> no Effect :bug:

The issue seems to be that Explorer is refreshing the Tree like crazy for each element that arrives.
This seems to be the side effect of adopting to new file event handling.

fyi @bpasero

**Comment by bpasero** [comment]
Yes I noticed this too.

**Comment by isidorn** [comment]
Found some optimisations, will push a fix soon...

**Comment by isidorn** [comment]
Pushed the optimisastion.
It is still not optimal, however I checked previous stable and the performance is comaprable to what we have with this fix (still a lot of refreshes, but not a gazilion and some clicks get lost).

For more optimisations I would not do last day of endgame but potentialy in debt week

**Comment by bpasero** [comment]
@isidorn do you know what exactly causes this change of behaviour? Is it adopting the file events methods? But they should behave the same as before, no?

**Comment by isidorn** [comment]
@bpasero good question, I am not  sure. I can investigate more to be certain. But I have two suspects:
1) More events are comming in due to some other change (both the `onDidRunOperation` and `onDidFilesChange` get triggered and we listen to both)
2) The events did not change, but I handle them a bit differently now. I think it should result in the same amount of refreshes as before, that is why my suspicion is 1)

**Comment by bpasero** [comment]
Behaviour is still rough for me. It has improved, but often a click does nothing and/or the explorer is very hectic: 

![recording](https://user-images.githubusercontent.com/900690/101186295-31c34b80-3653-11eb-8e9b-580326767a9f.gif)

**Comment by isidorn** [comment]
Yeah, the same was for previous stable.
Here's an item which captures my plan to refactor how we handle events in December https://github.com/microsoft/vscode/issues/111652
