### ISSUE TITLE
Can not log into terminal

### ISSUE THREAD

**Issue by DavidPodrazik** [microsoft/vscode#111828]
Issue Type: <b>Bug</b>

My password to log into terminal for the IBMz Mainframe is not working.  I keep getting a permission denied error when trying to log into USS terminal.  I was able to log in earlier but now I am unable to log in.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rebornix** [comment]
May I ask why is this a VS Code issue? A screenshot or screen recording can help us understand it better.
