### ISSUE TITLE
Notebook jumps on edit

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#111886]
* See attached recording
* authoring release notes with MDNB
* double-click a lengthly MD preview to author
* :bug: things scroll up making it very hard to find the edit position

[Dec-04-2020 14-27-18.mp4.zip](https://github.com/microsoft/vscode/files/5643021/Dec-04-2020.14-27-18.mp4.zip)

**Comment by jrieken** [comment]
likely due to so many images in those cells

**Comment by rebornix** [comment]
We should reveal the cell before turning it into editing mode.
