### ISSUE TITLE
Allow word-part (camel-hump) navigation in editor symbol rename input box

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#111868]
I constantly try to use word-part (camel-hump) navigation in the editor symbol rename input box and am frustrated every time it doesn't work 😄 It would be great if we supported the `cursorWordPartLeft[Select]`, `cursorWordPartRight[Select]` commands in that input.

I'd love to see the same in the explorer file rename input box too (though for me much less important).

/cc @isidorn @joaomoreno

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"feature-request""+label%3A"rename""

**Comment by eamodio** [comment]
GitHub search is so frustrating.

Now I found these:
https://github.com/microsoft/vscode/issues/53666 (rename specific)
https://github.com/microsoft/vscode/issues/53498 (everywhere)

**Comment by JacksonKearl** [comment]
@jrieken cool idea, I'll try modifying the bot to use it. Though I think your link is a bit broken :)

**Comment by isidorn** [comment]
@JacksonKearl fyi I requisted this some time ago https://github.com/microsoft/vscode/issues/49912
So maybe you want to close the new issue as a duplicate...
