### ISSUE TITLE
Backslash breaks fuzzy search

### ISSUE THREAD

**Issue by tbenst** [microsoft/vscode#111865]
In below gif, note how typing `n` fails to trigger `#nabla` snippet as expected, but typing `n` triggers the `\\nabla` snippet.

![n](https://user-images.githubusercontent.com/863327/101125786-e9eae880-35ae-11eb-8da9-7c95e7031a52.gif)

**Comment by jrieken** [comment]
please provide those snippets in _source_

**Comment by tbenst** [comment]
```
	"nabla": {
		"prefix": "\\nabla",
		"body": [
			"∇"
		],
		"description": "nabla"
	},
```

**Comment by jrieken** [comment]
please also add what exactly you are typing and when intellisense shows and whether you trigger IntelliSense manually or not

**Comment by tbenst** [comment]
The gif shows exactly what I was typing. I use a keyboard shortcut to jump between panes but that's it. I literally type the letter "n" and "\nabla" shows up as suggestion, but to get "#nabla" as suggestion, typing "n" is not sufficient, which is as expected, just as typing the letter "o" will not bring up suggestion for "for".

**Comment by jrieken** [comment]
So, this happens when typing only, right? What happens when you explicitly request suggestion via `ctrl+space`?
