### ISSUE TITLE
Typescript and Javascript format setting to place else in a control block on a new line

### ISSUE THREAD

**Issue by vsashidh** [microsoft/vscode#111829]
I would like to achieve the following:
```
if
{

}
else
{

} 
```

I have tried the following user and workspace settings:

``` 
 "javascript.format.placeOpenBraceOnNewLineForControlBlocks": true,
 "javascript.format.placeOpenBraceOnNewLineForFunctions": true,
    
"typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
"typescript.format.placeOpenBraceOnNewLineForFunctions": true
```

but they only put the curly braces on new lines and not the else keyword as in

```
if
{

}else
{

}
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
