### ISSUE TITLE
The TypeScript language service died 5 times right after it got started. The service will not be restarted

### ISSUE THREAD

**Issue by mlicciardi** [microsoft/vscode#111811]
Issue Type: <b>Bug</b>

TS 4.0.5

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id dd26c912-d23c-4620-94ad-d182ba329fba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.1
folder-source-actions|bie|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.37.2
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
vs-ng-quick-switch|erh|1.0.7
prettier-vscode|esb|5.8.0
todo-tree|Gru|0.0.188
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.2.3
reload|nat|0.0.6
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
vscode-status-bar-format-toggle|tom|2.0.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mlicciardi** [comment]
Reinstalled the stable version, cannot reproduce to provide more info. U can close this Issue

**Comment by pyrodogg** [comment]
I can also reproduce this with the latest insiders build and all extensions disabled. Simply opening a TypeScript project with VS Code - Insider causes the issue. I can see "Initializing JS/TS language features" in the status bar, flashing a few times (presumably the 5 attempts), and then the error message saying it died 5 times right after it got started.

Version: 1.52.0-insider
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:15:13.654Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-56-generic
