### ISSUE TITLE
python file made the rest not run

### ISSUE THREAD

**Issue by jsurf-in-the-water** [microsoft/vscode#111859]
1. I was programming a web page (HTML, CSS, JavaScript) and threw in some python as well.
2. The python made the entire set of pages not run so I deleted the python, eventhough its deleted I still get the launch.json coming up and I have no idea what to do or what to put in that file, can't find too much on it that explains it.
![screenShot](https://user-images.githubusercontent.com/57844521/101117096-290f3e80-359b-11eb-89cb-37a76aad78c1.jpg)

**Comment by jsurf-in-the-water** [comment]
I'd appreciate any help I can get and thank you in advance.

**Comment by weinand** [comment]
The launch.json just contains debug configurations. From what I see in your screenshot, there are no Python debugger configs visible. And even if there were, they do no harm. They are only used when **you** select them in the debug drop down and run them.

Please read https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
