### ISSUE TITLE
First line cropped from integrated terminal

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11184]
* My settings:
```json
// Place your settings in this file to overwrite the default settings
{
	// "externalTerminal.linuxExec": "xterm",
	"files.autoSave": "afterDelay"
	, "editor.fontFamily": "Hack"
	, "editor.fontSize": 16.5
	, "editor.lineHeight": 22
	, "editor.renderWhitespace": true
	// , "integratedTerminal.fontFamily": "Hack"
	, "telemetry.enableCrashReporter": false
	, "telemetry.enableTelemetry": false
	// , "editor.scrollbar": {
	// 	"verticalHasArrows": true,
	// 	"horizontalHasArrows": true
	// }
	// , "window.zoomLevel": 1
	, "workbench.editor.showTabs": true
	// , "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
	// , "terminal.integrated.fontFamily": "Arial"
	// , "editor.renderIndentGuides": true
	// , tabs
	, "editor.snippetSuggestions": "bottom"
	// , "editor.wrappingColumn": 0
	// , "terminal.integrated.fontSize": 14.5
	// , "editor.scrollBeyondLastLine": false
	, "explorer.showFileIcons": true
}
```

![terminal-crop](https://cloud.githubusercontent.com/assets/5047891/18086310/942aa158-6eaf-11e6-9559-46ce87b565b6.gif)

**Comment by Tyriar** [comment]
I can't reproduce on my Windows 10 machine

`"editor.fontFamily": "Hack"`

![image](https://cloud.githubusercontent.com/assets/2193314/18211301/db12ae3c-70f1-11e6-943d-d9ca7d6c9dde.png)

Default font:

![image](https://cloud.githubusercontent.com/assets/2193314/18211354/170de168-70f2-11e6-9c2d-705b70e42139.png)

Resizing vertically seems to work just right. @alexandrudima @bpasero is this by chance running on a VM with a Mac host and/or is using a high DPI monitor?

**Comment by alexandrudima** [comment]
I am running Windows 10 natively

**Comment by Tyriar** [comment]
@alexandrudima does it work fine if `editor.fontSize` is 16 instead of 16.5?

**Comment by alexandrudima** [comment]
Ok, most weird I can no longer reproduce. Maybe I should've written down the vscode version.

As easy as it was reproducible for me before, it now is completely not reproducible. Sorry for the noise.

**Comment by Tyriar** [comment]
Strange, ping me if you see it again.
