### ISSUE TITLE
Allow to disable extensions selectively

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11189]
The first thing I typically ask a user when an issue is reported is to run with all extensions disabled. However, if one extension is causing issues and 30 are installed, it is very hard to find the one causing the issue.

Ideally we have UI to disable an extension selectively (from the extensions viewlet) so that a user can easily find out which extension is causing issues. 

Optionally we could also allow to do so from the command line, e.g. "`code --disable-extension vscode-icons`"

CC'ing some folks fyi @alexandrudima @joaomoreno @jrieken @egamma

**Comment by jrieken** [comment]
We need `code bisect`

**Comment by joaomoreno** [comment]
#2882
