### ISSUE TITLE
Commenting is not working properly

### ISSUE THREAD

**Issue by alakcreature** [microsoft/vscode#111855]
Issue Type: <b>Bug</b>

I am entering ctrl + / to comment a line in html file but instead it shows comment as given below:

{% comment %}  {% endcomment %}

What to do?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.55GB (0.10GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 336ee453-83ed-4192-9f4c-791ae6ea2636|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.0
es7-react-js-snippets|dsz|3.0.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
swdc-100-days-of-code|sof|1.0.13
swdc-vscode|sof|2.3.21
react-redux-es6-snippets|tim|2.1.0

</details>

Issue Type: <b>Bug</b>

I am entering ctrl + / to comment a line in html file but instead it shows comment as given below:

{% comment %}  {% endcomment %}

What to do?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.55GB (0.10GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 336ee453-83ed-4192-9f4c-791ae6ea2636|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.0
es7-react-js-snippets|dsz|3.0.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
swdc-100-days-of-code|sof|1.0.13
swdc-vscode|sof|2.3.21
react-redux-es6-snippets|tim|2.1.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Does this also happen after you run the command to reload with all extensions disabled? If not, it's being caused by one of your extensions and needs to be reported to the extension's repo.

**Comment by aeschli** [comment]
The built-in HTML extension does not use `{% comment %}` as comment tokens. This must come from an extension.

Please run with extensions disabled.
