### ISSUE TITLE
Property preview text wraps lines in debug console

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode#111843]
**Describe the bug**

Inspecting an object with function properties in the debug console results in source code soup:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/3277153/101073190-eece7e80-3553-11eb-9f21-a09fe6c08af5.png">

I could be misremembering, but I’m pretty sure until recently, the function’s toString() text got truncated, so that each property only takes up one line. At any rate, the current behavior is really difficult to use. The hover widget actually scrolls horizontally, which, while not super useful and not possible for a console, shows how much easier it is to visually scan the properties of an object when they’re displayed compactly and uniformly distanced:

![image](https://user-images.githubusercontent.com/3277153/101073479-656b7c00-3554-11eb-95a1-c065f315d448.png)

**To Reproduce**

1. Evaluate an object with function properties whose source text is long enough to not fit on one line
2. Expand the object preview disclosure thing

Version: 1.52.0-insider
Commit: 92192baf760315ac47fb2caaf3ce6d0778

**Comment by connor4312** [comment]
I think this should be an option for the debug console view (if it's not already). As a debug adapter I have no idea how wide the console is / how many characters can fit in it.

**Comment by andrewbranch** [comment]
Huh, actually the debug console _can_ scroll horizontally with this option:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/3277153/101089460-0d3f7480-356a-11eb-9fde-7e14174317bb.png">

This still doesn’t feel great, because it means the console width grows to however wide the text coming from the debugger reaches, which pushes right-aligned text (like the links to log statement locations) way off so you have to scroll horizontally to see them. But it’s a lot better than the default. Did the debugger recently start showing a lot more characters for property previews? I feel like I would have noticed this problem before now.

**Comment by isidorn** [comment]
I agree this is an ulgy issue and we should fix it. Variables should not be wrapped in the debug console.
Assining to December to fix next week, since we already shipped last stable with this issue.

**Comment by isidorn** [comment]
Pushed a fix, you can try it out with VS code insiders from tomorrow. Thanks!
