### ISSUE TITLE
Configure Task is not working in empty workspace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#111815]
Testing #89456

- Open a workspace with no folders
- Run command `Tasks: Configure Task`
- You get `Create tasks.json from template` option. Select it.

🐛 Nothing happens

Same works in an empty window: Selecting `Create tasks.json from template` option shows templates

**Comment by alexr00** [comment]
I am unable to repro this. @sandy081 when I run **Tasks: Configure Task** in an empty workspace I get the task quick pick with a "Create tasks.json from template" option. What exactly are you seeing?

**Comment by sandy081** [comment]
@alexr00 Sorry, I missed one step. It's after selecting `Create tasks.json from template` option. Updated the steps. Please try now.
