### ISSUE TITLE
Cursor follow not supported

### ISSUE THREAD

**Issue by ElectroLund** [microsoft/vscode#111823]
![image](https://user-images.githubusercontent.com/2272478/101046251-203c4f80-353e-11eb-82c1-d684049c43c6.png)
The VSCode feature doesn't seem to be supported as I navigate my source file.

**Comment by jrieken** [comment]
Do you have "Follow Cursor" enabled?

<img width="468" alt="Screenshot 2020-12-03 at 18 06 54" src="https://user-images.githubusercontent.com/1794099/101062793-5acfd780-3592-11eb-8ea5-98c08aa31983.png">

**Comment by ElectroLund** [comment]
Yeah I do have that turned on.  As a test, I looked at a standard C source file and the follow works as expected there.

Then on another AHK file, same results with cursor not following.

The extensions I have installed and enabled are:
AutoHotkey Plus
Bookmarks
C/C++
Increment Selection
Smart Column Indenter
Todo Tree

**Comment by jrieken** [comment]
> Then on another AHK file, same results with cursor not following.

When you go the other way and click on an item where precisely does the cursor end up?

**Comment by ElectroLund** [comment]
When I click on any item in the Outline, the editor window snaps to that item as you would expect.  It's only from the Editor window that the cursor isn't followed.

I also tried disabling all other extensions.

I closed all editors except for the one AHK (no splits).

**Comment by jrieken** [comment]
This is working for TypeScript, CSS and JSON for which I know that they return non-empty ranges. Please file this issue against the language extension you are using, it seems that its outline items have an empty range so that the cursor is never contained by it
