### ISSUE TITLE
Folds only argument list, not the entire function

### ISSUE THREAD

**Issue by eldarkurtic** [microsoft/vscode#111852]
- VSCode Version: 1.51.1
- OS Version: Big Sur 11.0.1 (Darwin x64 20.1.0)

VSCode folds only the argument list when closing parentheses have smaller indentation than the argument list.
Expected behavior: folds the entire function body.

![folding](https://user-images.githubusercontent.com/8884008/101097205-1445a180-35c1-11eb-8a10-91e726a301cf.gif)

**Comment by gjsjohnmurray** [comment]
This is expected behaviour for the default indent-based folding. For better folding you need language-specific support. What language are you coding in?

**Comment by eldarkurtic** [comment]
Mostly Python and C++. Do you have a suggestion for language-specific extensions?

**Comment by gjsjohnmurray** [comment]
I don't use either of those languages, but it looks like [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) may help you for C++.

**Comment by thunder-coding** [comment]
I remembered it worked well in earlier versions of VS Code <v1.46

**Comment by mundodisco8** [comment]
In C/C++ the argument list is not foldable. I'm using MS C/C++ extension (the one linked above), current version is 1.1.3
![Folding2](https://user-images.githubusercontent.com/8402707/101151999-5c44e280-361a-11eb-9292-8adb2e70f8c1.gif)

**Comment by aeschli** [comment]
Please file C++ folding related issues against the cpp extension: https://github.com/microsoft/vscode-cpptools

**Comment by eldarkurtic** [comment]
> Please file C++ folding related issues against the cpp extension: https://github.com/microsoft/vscode-cpptools

So this is intended behaviour for folding in Python?

**Comment by aeschli** [comment]
If you are using the MS Python extension (which have a folding provider as well) please file the issue against https://github.com/Microsoft/vscode-python/issues
