### ISSUE TITLE
vscode does not respect `~/Library/KeyBindings/DefaultKeyBinding.dict` on macOS

### ISSUE THREAD

**Issue by zsimic** [microsoft/vscode#111950]
I use `~/Library/KeyBindings/DefaultKeyBinding.dict` for years now to define how key bindings should work throughout macOS, and it appears that vscode does not respect those.

For example, I have these sample entries in there: 
```
{
  "^\UF729"   = "moveToBeginningOfDocument:";  /* C-home    Beginning of document */
  "^\UF72B"   = "moveToEndOfDocument:";        /* C-end     End of document */

  "^\UF702"   = "moveWordLeft:";               /* C-left    Move word left */
  "^\UF703"   = "moveWordRight:";              /* C-right   Move word right */

  "^\U007F"   = "deleteWordBackward:";         /* C-Del     Delete word backward */
  "^\UF728"   = "deleteWordForward:";          /* C-FwdDel  Delete word forward */

  "^z"        = "undo:";                       /* C-z       Undo */
  "^y"        = "redo:";                       /* C-y       Redo */
}
```

This makes it so that `CTRL` + `Home` for example goes to the beginning of document (just like on Windows), and `CTRL` + `left/right` arrow keys move word by word etc.

Those key bindings are respected by all text editors I tried so far (without any editor-specific modifications).
vscode is the first editor I noticed is ignoring this entirely (from what I can tell).

Only one of my above settings work for example: `CTRL` + `left` arrow (for some reason), all the others are completely ignored. `CTRL` + `right` arrow for example does absolutely nothing on my machine.

My `~/Library/Application Support/Code/User/keybindings.json` is currently empty (so: using vscode defaults only currently).

Is this a bug, or vscode is maybe simply written currently using APIs that don't take into account `~/Library/KeyBindings/DefaultKeyBinding.dict` on macOS?
Would it be possible to make it respect those settings?

**Comment by zsimic** [comment]
Out of curiosity: just verified that Slack (another electron app) does respect all of these settings no problem.
So it's not an electron limitation.

**Comment by zsimic** [comment]
My full `DefaultKeyBinding.dict` for reference: https://gist.github.com/zsimic/1367779

**Comment by zsimic** [comment]
After further inspection, turns out Slack (another electron app) does NOT actually respect `DefaultKeyBinding.dict` either. They just have slightly better defaults, which made it look like it was respecting my settings (which are simply trying to make Home/End/PageUp/Down keys behave "as usual"...)

I've updated/simplified my [gist](https://gist.github.com/zsimic/1367779).

Maybe there's something I'm missing here, since vscode on mac (with no custom keybindings) behaves in a weird way when not using the built-in mac laptop keyboard (which I never use... so can't tell if/how it's working there).

Things that stand out right away in vscode currently (which I was hoping my `DefaultKeyBinding.dict` would help resolve...):
- `CTRL+Home` works as expected
- `CTRL+End` does nothing
- `CTRL+Shift+Home` and `CTRL+Shift+End` do nothing
- `CTRL+Left` works as expected (goes 1 word back)
- `CTRL+Right` does nothing...
- `CTRL+Shift+Left` does nothing...
- `CTRL+Shift+Right` selects the "next thing in scope" (either next word, then string, then key/value for example, then line, then paragraph etc...)

etc, it seems very inconsistent

**Comment by lastobelus** [comment]
It respects some things, and not others.
For example:
```
  "\UF705" = "cut:";				
  "\UF706" = "copy:";				
  "\UF707" = "paste:";	
  "\UF707" = (insertText:, "works1");
```
all work, but none of the cursor movement or things like `capitalizeWord:` seem to work.
This seems to be an Electron thing, not a VSCode thing.
