### ISSUE TITLE
"Smart" horizontal scroll when scrolling vertically doesn't work properly

### ISSUE THREAD

**Issue by JakubSteplowski** [microsoft/vscode#111937]
- VSCode Version: 1.51.1
- OS Version: Windows 10 Pro 20H2 (19042.630)

Steps to Reproduce:

1. Scroll vertically in a .php or .html file
2. See the editor scrolling horizontally to left and right to "follow the code" in an annoying way

Does this issue occur when all extensions are disabled?: Yes

More:

Is there a way to disable this annoying "feature" (a setting I can change to false)?
If there isn't, I think it should be fixed because I have to move the horizontal scrollbar everytime I scroll vertically to see my code correctly...

![VS-Code-AutoHorizontalScroll-Annoying-final](https://user-images.githubusercontent.com/4522930/101244239-8921f400-3705-11eb-8bb9-ab3af5fad895.gif)

**Comment by alexdima** [comment]
@JakubSteplowski We don't have a "follow the code" feature, so I wouldn't know why the editor scrolls to the right. What gesture are you doing? Are you scrolling with a keybinding or with the mouse wheel?

**Comment by JakubSteplowski** [comment]
Ok, I feel dumb right now...

The "issue" was caused by my mouse, Logitech G903, which has built in horizontal scrolling in the mouse wheel... which I didn't know about. So when I scroll fast in my long code document even a micro shift to the side of the mouse wheel can cause a horizontal scroll... this plus the fact each horizontal scroll (the mouse wheel works as a button when you move it horizontally) is equal to a "tab" it seemed to me as VS code was following the indentation of the code. 🤯

Sorry for wasting your time. 😅

Have a nice day, and thanks a lot for your awesome work!
