### ISSUE TITLE
Command + Click does nothing on Code -exploration

### ISSUE THREAD

**Issue by nezaboravi** [microsoft/vscode#111912]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

When I try to command and click on a method name, class name, etc, it is not clickable.
I am using sync settings and I imported all settings from VSCode
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

On the regular version of VSCode command + click works

VS Code version: Code - Exploration 1.52.0-exploration (25a4ee40993f43df9229edc552bd3018c086569d, 2020-12-03T22:37:53.684Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.4.1
laravel-blade-spacer|aus|2.1.2
vscode-intelephense-client|bme|1.5.4
better-phpunit|cal|1.5.3
laravel-goto-view|cod|1.3.3
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
php-debug|fel|1.13.0
php-cs-fixer|jun|0.1.157
laravel-intellisense|moh|0.1.9
vs-keybindings|ms-|0.2.0
vetur|oct|0.30.3
laravel-blade|one|1.25.0
advanced-new-file|pat|1.2.2
laravel-artisan|rya|0.0.27
vscode-fileutils|sle|3.4.2
laravel-goto-controller|ste|0.0.12
ayu|tea|0.20.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by deepak1556** [comment]
Does it work when you launch with `--disable-extensions` ? Can you also paste the settings configuration.

I am unable to repro in my mac arm64 device, can you provide a screen recording demonstrating the issue ?
