### ISSUE TITLE
Enlarged view when using live server

### ISSUE THREAD

**Issue by darlaford** [microsoft/vscode#111957]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Issue Type: <b>Performance Issue</b>

While working on a file in vscode, the live view suddenly appeared to be like 300% of what it should be. I'm not sure how to tell you to reproduce the problem. I closed vscode and opened again. And I checked another project and got the same results. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.83GB (2.19GB free)|
|Process Argv|--crash-reporter-id 6970c100-c1c1-4b48-b9b9-ddc6233fd1a9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    82	 42816	code main
    0	    91	 10976	   window (Issue Reporter)
    0	    37	 36920	   utility
    0	    23	 38412	   crashpad-handler
    0	    87	 39404	   shared-process
    0	   150	 44880	   window (index.html - zen-garden - Visual Studio Code)
    0	    66	 34548	     searchService
    0	   102	 46560	     extensionHost
    0	    87	 37452	       "C:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\dejae\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=46560
    0	    12	 50304	     watcherService 
    0	    11	 41460	       console-window-host (Windows internal process)
    0	   131	 46708	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - zen-garden - Visual Studio Code)
|    Folder (zen-garden): 21 files
|      File types: scssc(8) scss(7) html(1) css(1) map(1) code-workspace(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
LiveServer|rit|5.6.1

</details>

**Comment by rebornix** [comment]
please file against the Live Server extension, thanks!
