### ISSUE TITLE
NPM scripts explorer - Add contextual title, more detailed icon

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#111994]
When you move the NPM extension explorer view to the activity bar, the name of the activity bar view becomes "Explorer". This is just horrible to deal with from an activity bar management POV.

The current icon does not represent NPM very well to me. It would be great of the extension could take an icon that actually stood for what the extension was used for like the npm icon or something of that nature.

Most of the projects I deal with are not JS/TS projects. There is no reason for the NPM extension to show its view when it has no package.json to analyze.

I am also confused as to the relationship of the built-in extension and the extension that has over 6m installs by egamma. I have opened similar issues over there, but no response from the dev, so I assume that is just some development test bed and the code magically ends up over here?

**Comment by egamma** [comment]
>I am also confused as to the relationship of the built-in extension and the extension that has over 6m installs by egamma. I have opened similar issues over there, but no response from the dev, so I assume that is just some development test bed and the code magically ends up over here?

Good point this should be clarified, I've filed https://github.com/microsoft/vscode/issues/117951.

>When you move the NPM extension explorer view to the activity bar, the name of the activity bar view becomes "Explorer". This is just horrible to deal with from an activity bar management POV.

Issue confirmed. Renaming the title accordingly (the when clause issue is tracked in https://github.com/microsoft/vscode/issues/117951).

**Comment by tristan957** [comment]
Thanks @egamma. If you need to close this issue, go for it. Thanks for acknowledging the issue(s) at hand :).

**Comment by egamma** [comment]
@tristan957 keeping the issue open to track the view container name issue.

**Comment by alexr00** [comment]
We changed the icon with https://github.com/microsoft/vscode/issues/118019.
