### ISSUE TITLE
Remove duplicate (case sensitive) recent workspace/folder names on the welcome screen

### ISSUE THREAD

**Issue by skylinew** [microsoft/vscode#111954]
On the welcome window (on start up of VSCode or opening a new window), there is the Recent workspaces/folder section. If I edit the name of a folder in the recents list outside of VSCode and open the same folder again in VSCode, both the old and new folder names will appear again on the welcome window. This behavior repeats on every subsequent folder rename. Since  they both refer to the same folder, it seems redundant to include the old names, unless there was a deliberate decision to keep this behavior. If this request is approved I would like to work on it.

Steps to recreate:

1. Open VSCode or open a new window in VScode if already open
2. Under "Start" section, do "open folder"
3. Close that folder's window on VSCode
4. Rename the folder (outside of VSCode) only with different casing (e.g. "folder1" to "Folder1")
5. Open a new window on VSCode, repeat step 2 by selecting the same folder but with the "new" name
6. Open a new window, and both folder names appear under "Recent"

Example shown in screenshot below - 

![Screen Shot 2020-12-05 at 8 19 56 PM](https://user-images.githubusercontent.com/66392320/101269031-ed5dab80-3737-11eb-8503-26b4e557ff72.png)

Encountered on the following version of VSCode:
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

macOS: 11.01

**Comment by bpasero** [comment]
Hm, interestingly we don't seem to be very clever to find duplicates around here:

https://github.com/microsoft/vscode/blob/5e6a2779f63c3a1a5d770498c4ead5fd8f34859a/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L429-L439
