### ISSUE TITLE
Terminal is blurry

### ISSUE THREAD

**Issue by s-g4m3r** [microsoft/vscode#111920]
![1 left](https://user-images.githubusercontent.com/74995040/101229821-51f90780-365f-11eb-9aeb-8a636c304a2c.png)
![1 middle](https://user-images.githubusercontent.com/74995040/101229822-52919e00-365f-11eb-8781-d477052a24e5.png)
![Screen Shot 2020-12-04 at 6 27 32 PM](https://user-images.githubusercontent.com/74995040/101229823-52919e00-365f-11eb-91bd-79a8de9ddd61.png)

Issue Type: <b>Bug</b>

The built-in terminal gets blurry the closer to the centre of the screen you go. Very visible when there are big blocks of text in the terminal. attatched is a screenshot of the terminal in light mode, the two cropped 1's are different. the one in the middle is blurrier. Please fix, it makes it hard to look at errors.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|4.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 4bf860e4-157d-4240-bfb1-cd2b583866ec|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.1.3
shader|sle|1.1.4

</details>

**Comment by meganrogge** [comment]
When did this start happening? 

What do you mean by:
> "the closer to the centre of the screen you go?"

I'm not able to reproduce this.

**Comment by ntrf** [comment]
This problem might only be visible with non-integer zoom factors and/or non-integer device scale factor. In my case with zoom 150% terminal window displayed as canvas of size 1298 pixels wide while an element has `865px` width set in style. The result is blury in the middle of the window.
![изображение](https://user-images.githubusercontent.com/2241513/101239524-1ca0f800-36f9-11eb-8b5e-ff9c5419234f.png)

Here is canvas element in question in developer tools:
```
<canvas class="xterm-text-layer" style="z-index: 0;width: 865px;height: 224px;" width="1298" height="336"></canvas>
```

If i change style to have width `865.333333333px` ( = 1298 / 150%), then result is sharper and most digits look the same:
![изображение](https://user-images.githubusercontent.com/2241513/101239587-a4870200-36f9-11eb-8a95-f1c41258f71a.png)

It seems like xterm.js does too much rounding when computing styles, although comments in code claim that it's necessary to reduce blur. https://github.com/xtermjs/xterm.js/blob/master/src/browser/renderer/Renderer.ts#L168-L211

**Comment by s-g4m3r** [comment]
@meganrogge I first noticed it this week when I began getting long errors in my terminal while rewriting my vulkan app. I definetly did change my zoom and appearance settings. 
In the terminal window, the text is blurry in the centre of the window. Along the sides, the text is clear.

To recreate it, set renderer type to canvas, resize VS code and zoom in/out with the terminal open until terminal blurs.

 DOM renderer is not blurry. Imma just start using DOM renderer

**Comment by danielhuang** [comment]
Can this be reopened? I am also experiencing this issue.

**Comment by meganrogge** [comment]
please open a new issue @danielhuang if it is different from this and doesn't resolve with my above reccomendations.

**Comment by danielhuang** [comment]
It appears to be the same issue, as it is (temporarily) resolved if I make the edits as described by @ntrf in the developer tools.
