### ISSUE TITLE
[Regular Expressions] exclude

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#111924]
- VSCode Version:1.51.1
- OS Version:nt64 10.0.19042

Steps to Reproduce:

1.search for `[^b][^c]`

Does this issue occur when all extensions are disabled?: Yes

This code means { 2 chars, the 1st is not a "b" and the 2nd is not a "c" } . But the result is nonsense .

![Screenshot 12-05-2020 04 32 42](https://user-images.githubusercontent.com/13949704/101233936-3d465f00-36b3-11eb-978f-aef834a69083.png)

**Comment by usernamehw** [comment]
Well, it has 4 matches:`ab`, `c `, `ab`, `c ` .

![Screenshot (389)](https://user-images.githubusercontent.com/9638156/101238432-3d654f80-36f1-11eb-8627-08b34c698048.png)

**Comment by irvnriir** [comment]
@usernamehw sorry, i was really tired . you are correct, "`c `" and the last in line chars will match if you add another one (to make the count in line even-numbered)
