### ISSUE TITLE
Add associated hotkeys to all titles/tooltips

### ISSUE THREAD

**Issue by dortonway** [microsoft/vscode#111977]
Hello

I suggest to add associated hotkeys to all titles/tooltips. So when we mouseover some element we see also the quick way to call it.

**Comment by sbatten** [comment]
@misolori thoughts on this?

**Comment by misolori** [comment]
I think this would be great for discoverability, we already do this for views so curious what other areas are missing.

**Comment by sbatten** [comment]
We do this for all view containers as they have associated keybindings. We also already do this for actions in toolbars. Not sure where we are missing that would provide additional value.
