### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by qbao96xb** [microsoft/vscode#111987]
It happens to update feature
Actual result:
1. Setting Icon shows a notificaition that there is an available update
2. Click Restart to Update
3. VCS shutdown and did not restart

Expected:
It did update the software but did not automatically restart, hence I had to restart manually

Version: 1.52.0-insider
Commit: 5e350b1b79675cecdff224eb00f7bf62ae8789fc
Date: 2020-12-04T10:16:29.391Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by gjsjohnmurray** [comment]
Also needs a better title. Imagine if everyone titled their issues "Bug report"...

**Comment by qbao96xb** [comment]
> Also needs a better title. Imagine if everyone titled their issues "Bug report"...

Sorry about that, I thought it has to follow a limit list as per the Feedback feature including Bug Report, Feature Request and Performance Issue

**Comment by gjsjohnmurray** [comment]
> Sorry about that, I thought it has to follow a limit list as per the Feedback feature including Bug Report, Feature Request and Performance Issue

OK. You should be able to edit the title here on GH.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/109728
