### ISSUE TITLE
Typescript Intellisense & Automatic Type Acquisition doesn't work

### ISSUE THREAD

**Issue by cgarrovillo** [microsoft/vscode#111986]
- VSCode Version:    1.51.1
- OS Version:             macOS 11.0.1  x64

Steps to Reproduce:

1. clone https://github.com/cgarrovillo/broken-ts-intellisense 
2. try to get intellisense to trigger in the `index.ts` & `index.js` files.  (like app.listen() or something ).  You'll notice that IntelliSense works for `index.js` but **not** `index.ts `

Does this issue occur when all extensions are disabled?: Yes

---
Changing the global property "typescript.tsdk"  **doesn't fix it.**
Switching to use the project workspace's "typescript.tsdk"  by installing typescript to the project's node/modules folder  **doesn't fix it.**

VSCode also warned me about needing to install @types through npm (@types/node) which was weird as I never had to do this since Automatic Type Acquisition does it for me automatically. That leads me to believe it also doesn't work. 

I assumed it was an issue with nvm, but manually pointing to npm using the "typescript.npm" property **doesn't fix it.**

**Comment by mjbvz** [comment]
Automatic type acquisition is only used for JavaScript. For TypeScript, you need to explicitly install the types (they are also used by `tsc`)

**Comment by cgarrovillo** [comment]
> Automatic type acquisition is only used for JavaScript. For TypeScript, you need to explicitly install the types (they are also used by `tsc`)

Cool. Can you tell me why there seem to be consistent problems with typescript intellisense? 

A quick google search yields lots of results, many of which just end up having the issue prematurely closed while still being unsolved.

**Comment by mjbvz** [comment]
As I explained, the behavior you described is by-design. What still doesn't work?

**Comment by cgarrovillo** [comment]
IntelliSense suggestions / content assist / code hinting/ code completion (whatever proper term is)

<img width="1126" alt="Screen Shot 2020-12-07 at 8 17 13 PM" src="https://user-images.githubusercontent.com/6688713/101435223-3729cb80-38c9-11eb-8513-2ac5f2e97e9b.png">
<img width="1126" alt="Screen Shot 2020-12-07 at 8 17 09 PM" src="https://user-images.githubusercontent.com/6688713/101435225-385af880-38c9-11eb-87cb-fe3a2251b4af.png">


Insider builds yielded no changes,  and neither does  removing typescript.tsdk properties from settings.json

**Comment by mjbvz** [comment]
This is also consistent with tsc.

```js
const http = require('http');
```

Is an untyped import in TS files. If you hover over `http`, you will see it listed as `any`. 

To have a type checked import use `import http = require('http')` (or `import * as http from 'http'`)
