### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by ztlevel** [microsoft/vscode#111989]
- VSCode Version:
- OS Version:

Steps to Reproduce:

When I write a tag and press enter, according to the idea I should get (<a> </ a>). But instead, I just have a break to the next line! Help what to do?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ztlevel** [comment]
When I write a tag and press enter, according to the idea I should get ( </ a>). But instead, I just have a break to the next line! Help what to do?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, extensions being used, and language mode of the document you are typing into.
