### ISSUE TITLE
Editor fontWeight value completion missing values

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11196]
- VSCode Version: 1.5.-insider
- OS Version: Windows

Steps to Reproduce:

1. open settings
2. request code complete on `"editor.fontWeight"` values. Only normal is proposed. Should bold, italic be in there as well.

**Comment by octref** [comment]
Verified but some values are still missing. See https://github.com/Microsoft/vscode/commit/152e0b04a7a2de37358da53287cbad346c0182b8#comments

**Comment by alexandrudima** [comment]
Thank you, answered inline in 152e0b0
