### ISSUE TITLE
Can't mount single files as volumes from inside devcontainer

### ISSUE THREAD

**Issue by elmehalawi** [microsoft/vscode#111967]
- VSCode Version: 1.51.1
- OS Version: macOS 10.15.6

Steps to Reproduce:

1. Cmd+Shift+P and select "Remote-Containers: Add Development Container Configuration Files..."
2. Select the "Docker from Docker Compose" option; this will create the default config files
3. Cmd+Shift+P and select "Remote-Containers: Open Folder in Container..." and choose the workspace folder
4. Create a docker-compose.yaml file with the following contents:

```yaml
version: '3'

services:
    nginx:
        volumes:
            - ${PWD}/nginx-dev.conf:/etc/nginx/nginx.conf:z
        ports:
            - 1313:1313
```

5. Create a file called nginx-dev.conf in the workspace folder. It doesn't matter what's in it, it can be empty
6. From the terminal (making sure you're in the devcontainer), run `docker-compose up`
7. You should get an error similar to:

> ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/workspace/nginx-dev.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/92408f5eb658eb5a829b494d635254b93b8c155091747970baa4d7916dd03323/merged\\\" at \\\"/var/lib/docker/overlay2/92408f5eb658eb5a829b494d635254b93b8c155091747970baa4d7916dd03323/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

Does this issue occur when all extensions are disabled?: Yes

---

For some reason I only get this error when I run docker-compose from inside the devcontainer. When I run this on my host machine, it can mount this file normally.

Also, docker-compose from the devcontainer does work. I just can't use single files in the volumes list. But if I mount a directory from there, it runs normally.

**Comment by chrmarti** [comment]
Mounts are done on the host filesystem, not the container's filesystem. E.g., try changing the mounts source to a file path that exists on your host machine and it should work.

**Comment by elmehalawi** [comment]
@chrisbenti Oh my mistake, I didn't realize it was still using my host filesystem.

For anyone else who might come across this: apparently vscode sets the environment variable `LOCAL_WORKSPACE_FOLDER` to the workspace folder on the host. So you can define the volume like this:

```yaml
volumes:
    - $LOCAL_WORKSPACE_FOLDER/nginx-dev.conf:/etc/nginx/nginx.conf:z
```

The unfortunate thing about this is it breaks running docker-compose outside of a vscode environment for people not using vscode. I wonder if there's a way to avoid this.

**Comment by chrmarti** [comment]
I'm not aware of the `LOCAL_WORKSPACE_FOLDER` variable. Maybe you are setting that in an `.env` file yourself?

**Comment by elmehalawi** [comment]
Just checked, there is no such variable in my code. 

So if that's not the sanctioned way to use docker-compose within devcontainers, what is?

**Comment by chrmarti** [comment]
You can use relative paths for volumes in the docker-compose.yml.
