### ISSUE TITLE
Make Cntrl-C a no-op when selection is empty

### ISSUE THREAD

**Issue by mhekkel** [microsoft/vscode#111933]
Issue Type: <b>Feature Request</b>

If you closely look at the location of the V and C key on a keyboard, you'll notice they are quite close to each other. Now using the keyboard to copy/paste, it happens quite often one wants to paste something and accidentally presses Ctrl-C, because hey, that's the key next to Ctrl-V, right? And then you lose your copy buffer, but nothing happens. You then realize you should have pressed Ctrl-C but now that only inserts an empty line... why? Did I copy an empty line?

Please?

regards, -maarten

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-56-generic

**Comment by usernamehw** [comment]
https://marketplace.visualstudio.com/items?itemName=usernamehw.do-not-copy-empty

**Comment by NotWearingPants** [comment]
Might also be useful - https://marketplace.visualstudio.com/items?itemName=SirTobi.code-clip-ring

**Comment by mhekkel** [comment]
Thank for both the suggestions for extensions, very cool and exactly what I've been missing. However, I really think this is essential basic functionality that should have been in vscode itself.

But hey, I'm old enough to know a good text editor should essentially be a scripting environment where you code your own functionality yourself (emacs e.g.) and that's what vscode apparently is.

**Comment by alexdima** [comment]
Please configure `"editor.emptySelectionClipboard": false`
