### ISSUE TITLE
node debug repl - global const not proposed as a suggestion

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11199]
In this program the variable `port` is suggested in the repl 
```js
port = 3000;
console.log(port);
```
![image](https://cloud.githubusercontent.com/assets/172399/18088670/320f8db4-6ebc-11e6-9b7a-64c380c06573.png)

In this program the const `port` is not suggested in the repl
```js
const port = 3000;
console.log(port);
```

![image](https://cloud.githubusercontent.com/assets/172399/18088715/5d7b2cce-6ebc-11e6-9ca8-7cb0aef35a67.png)

**Comment by weinand** [comment]
I'm now using all scopes which fixes this problem too.
The fix comes from https://github.com/Microsoft/vscode/issues/11186
