### ISSUE TITLE
ctrl+v to paste in search input box has stopped working

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#111900]
Right-click -> paste still works, but ctrl+v to paste in the search view input box doesn't do anything. 

I don't have any keyboard shortcuts defined that use "V". I'm using Windows.

**Comment by meganrogge** [comment]
this is working for me on Windows

**Comment by roblourens** [comment]
Me too. Can you do the "Toggle keyboard shortcuts troubleshooting" to see what command actually gets run?

**Comment by alexr00** [comment]
It's working for me now too 🤷‍♀️
