### ISSUE TITLE
Javascript multi-line comment mis-identifies ending inside string literal

### ISSUE THREAD

**Issue by gitgitwhat** [microsoft/vscode#111941]
- VSCode Version: Latest
- OS Version: Windows 10

Steps to Reproduce:
1) Open/create a Javascript file.

2) Create a string that contains the multi-line comment ending sequence.
var s = "some string */";

3) Now wrap the string in a multi-line comment.  The parser picks up the symbol in the string as the ending.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
This is correct. Comments have higher precedence than strings during parsing 

Try running `/*"some string */"; */` in a browser or node to see this in action
