### ISSUE TITLE
VS Code hard deleted entire folder full of code (no source control interaction)

### ISSUE THREAD

**Issue by christopherbauer** [microsoft/vscode#111947]
- VSCode Version: 1.51.1
- OS Version: Windows 10 Pro 18363.1198

Steps to Reproduce:

1. Moved all files/folders in repo to a subfolder (node_modules, configs, source => /src)
2. Moved configs back out (babel.config.ts, package.json, tsconfig.json) to parent folder
3. Moved node_modules back out to parent folder
4. Got a popup "Replace folders at destination?" > Yes
5. Folders and files hard deleted, not in recycle bin

Does this issue occur when all extensions are disabled?: Yes/No

This just happened, the code was not in source control so it wasn't a git operation that caused it. Some of my folders were effected and some were not. I'm still in a bit of shock, I lost around 5 hours of work.

**Comment by isidorn** [comment]
@christopherbauer sorry to hear that you lost your work.

I can not repro this. Here's what I have done

1. Clone VS Code repository
2. Open, explorer Drag `node_modules` folder into `script` folder
3. Drag back `node_modules` to top level -> all is good, nothing gets overwriten

Can you reproduce using vscode insiders https://code.visualstudio.com/insiders/
If yes, is it possible to provide a bit more exact steps? And potetnaily a repository which I can just clone and reproduce this issue on my machine?
Thanks!
