### ISSUE TITLE
VSCode not recognizing @types/jest installed in subfolder

### ISSUE THREAD

**Issue by GhassenRjab** [microsoft/vscode#111926]
- VSCode Version: 1.51.1 (user setup)
- OS Version: Window 10 Family 20H2

Steps to Reproduce:

1. Create a monorepo using `lerna`
2. Add a package for frontend using `gatsby`
3. Create components with `typescript`
4. Add unit tests to gatsby components by following [this guide](https://www.gatsbyjs.com/docs/unit-testing/)

Does this issue occur when all extensions are disabled?: Yes

I always have this error, even though I installed @types/jest.

> Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha`.

I try to install it at the root directory and the error has gone. But this is not the solution I want. I don't use `typescript `in all my packages.

**Comment by mjbvz** [comment]
Please share an example project that demonstrates this issue

**Comment by GhassenRjab** [comment]
Hi @mjbvz,

Thanks for your answer.

Here is a link to the sample project: https://github.com/GhassenRjab/sample-project

You will notice that the test is running well but **VSCode** keeps on unrecognizing `@types/jest`

**Comment by mjbvz** [comment]
This is almost certainly a confirmation issue with your project. See https://stackoverflow.com/questions/42024526/vscode-automatic-type-acquisition-for-jest for example
