### ISSUE TITLE
after create index.html file, the file won't open

### ISSUE THREAD

**Issue by amrs2127** [microsoft/vscode#111984]
Issue Type: <b>Feature Request</b>

from the app create templates folder then app folder then create index.html file expecting the index file would be active to do html but I couldn't do it. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

**Comment by ArturoDent** [comment]
What do you mean by "the index file would be active to do html"?  You can't type into it?  Do you expect it to be rendered as html just by opening that file in vscode?
