### ISSUE TITLE
Cannot connect to market extension

### ISSUE THREAD

**Issue by peaplesmart** [microsoft/vscode#111948]
Issue Type: <b>Bug</b>

Notification is : We Cannot connect to the Extentsion Marketplace at this time, please try again later

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5015U CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (5.27GB free)|
|Process Argv|--crash-reporter-id c0855466-5912-4db8-8208-f21e0e273535|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

https://marketplace.visualstudio.com/vscode

![image](https://user-images.githubusercontent.com/56358023/101260329-b1d7d700-3761-11eb-9175-0f0323d350e8.png)

**Comment by sandy081** [comment]
please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Developer Tools -> Network (Check if requests to marketplace are successful)
    - View -> Open View… -> Log (Window)

**Comment by peaplesmart** [comment]
> please share the logs from the following locations
>     - Help -> Toggle Developer Tools -> Console
>     - Help -> Toggle Developer Tools -> Network (Check if requests to marketplace are successful)
>     - View -> Open View… -> Log (Window)

# over all clear sir

Just reset my router @sandy081

**Comment by sandy081** [comment]
Does it works now?

**Comment by peaplesmart** [comment]
Yes sir its working now

Pada tanggal Sen, 7 Des 2020 17.37, Sandeep Somavarapu <
notifications@github.com> menulis:

**Comment by peaplesmart** [comment]
Yes this has worked
