### ISSUE TITLE
no installed extensions are working

### ISSUE THREAD

**Issue by rajit2004** [microsoft/vscode#111961]
I can't run my program when I press the f5 key then it does not pop up the run cmd. see to it, please!
![image](https://user-images.githubusercontent.com/75563944/101276730-ef297c80-37d4-11eb-8e4d-ddc71a842f51.png)

**Comment by isidorn** [comment]
This works fine for me

![Screenshot 2020-12-07 at 12 33 20](https://user-images.githubusercontent.com/1926584/101346132-6a983600-3888-11eb-8404-9d3e85c65847.png)


Can you reproduce with altest vscode insiders https://code.visualstudio.com/insiders/

**Comment by rajit2004** [comment]
Please have a look at theses snippets . Before it was working very well but
from few days it isn't . I have 23 installed extension and all were working
properly . Every debugger was fine but I don't know why is it doing so .

**Comment by isidorn** [comment]
Closing this as these are not reproducable steps and there is nothing we can do here
