### ISSUE TITLE
Corrupted extension in the extensions folder

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1119]
(extracted from #1095)

Some time ago I've uninstalled the tslint extension. The extension was not completely removed. 
It was still in the extensions folder and consisted of empty folders only and no package.json file.

I cannot reproduce how this happened but we should recover from such incomplete extensions, so that the user doesn't have to go in manually and clean-up the extension.

On startup there is a warning that the extension is incomplete, i.e., that there is no package.json. This warning should be shown to the user and there should be a command provided that allows cleaning up such a partial extension.

**Comment by dbaeumer** [comment]
Seems to be a dup of #31

**Comment by joaomoreno** [comment]
Absolutely.
