### ISSUE TITLE
Include UserAgent string in Git commands 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#111909]
Request from the GitHub Actions team to include UserAgent string (https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpuserAgent) in the headers for the "git push" command.

**Comment by plkt** [comment]
team, we are looking for user agent to identify the commits and push happening from VSCode, so we would need a unique user agent that VSCode can start sending in all the git push experiences happening on VSCode. 

for reference here is what VSIDE sends

> $"git/{​​​​​​​​gitExeVersion}​​​​​​​​ ({​​​​​​​​Environment.OSVersion.VersionString}​​​​​​​​; {​​​​​​​​Environment.OSVersion.Platform}​​​​​​​​ {​​​​​​​​(Environment.Is64BitOperatingSystem ? "x64" : "x86")}​​​​​​​​) CLR/{​​​​​​​​Environment.Version.ToString(3)}​​​​​​​​ VS{​​​​​​​​majorVSBuild}​​​​​​​​/{​​​​​​​​gpmContext.Version.ToString(3)}​​​​​​​​"


ex:

> _"git/2.29.2 (Microsoft Windows NT 10.0.19042.0; Win32NT x64) CLR/4.0.30319 VS16/16.0.0"_

**Comment by pulkitaggarwl** [comment]
team, we are looking for user agent to identify the commits and push happening from VSCode, so we would need a unique user agent that VSCode can start sending in all the git push experiences happening on VSCode.

for reference here is what VSIDE sends

> $"git/{​​​​​​​​gitExeVersion}​​​​​​​​ ({​​​​​​​​Environment.OSVersion.VersionString}​​​​​​​​; {​​​​​​​​Environment.OSVersion.Platform}​​​​​​​​ {​​​​​​​​(Environment.Is64BitOperatingSystem ? "x64" : "x86")}​​​​​​​​) CLR/{​​​​​​​​Environment.Version.ToString(3)}​​​​​​​​ VS{​​​​​​​​majorVSBuild}​​​​​​​​/{​​​​​​​​gpmContext.Version.ToString(3)}​​​​​​​​"


ex:

> "git/2.29.2 (Microsoft Windows NT 10.0.19042.0; Win32NT x64) CLR/4.0.30319 VS16/16.0.0"

**Comment by eamodio** [comment]
Here is what the user agent will look like: `git/2.29.2.windows.2 (Windows 10 Pro 10.0.19042; win32 x64) vscode/1.53.0 (Code - OSS Dev)`

**Comment by eamodio** [comment]
Not sure the best way to verify this -- likely need to capture the network traffic while running a git `clone`/`fetch`/`pull`/`push` operation.

@sana-ajani Do we have any insight from the GitHub actions team, if they are seeing this?

**Comment by lramos15** [comment]
Using fiddler I do see a useragent, but not the one that was posted abgove.

My verification steps were as follow
1. Start fiddler
2. Make a change and stage it
3. Push using the sync wheel in the activity bar
4.  analyze the traffic
![image](https://user-images.githubusercontent.com/4544166/105897264-f2c3cd80-5fe5-11eb-8b95-6183b47f6fae.png)
Here's what the headers look like for the request.

**Comment by eamodio** [comment]
Interesting. It looks like the credential manager is overwriting the user agent. @lramos15 what version of the creds manager do you have? Did you install the core version?

**Comment by lramos15** [comment]
@eamodio I have version 1.2.0 and git version 2.27.0. As for whether or not I installed the core version I'm not really sure, I just installed it from https://git-scm.com/
