### ISSUE TITLE
HTML Intellisense NOT working as expected.

### ISSUE THREAD

**Issue by evboggs302** [microsoft/vscode#111952]
Issue Type: <b>Bug</b>

My intellisense isn't working like before for HTML. I checked my settings and the checkbox for the HTML extensions is checked (enabled).

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (6.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.13
prettier-vscode|esb|5.8.0
beautify|Hoo|1.5.0
jupyter|ms-|2020.11.399280825

</details>

**Comment by ArturoDent** [comment]
Is it this issue: https://github.com/microsoft/vscode/issues/110971

**Comment by evboggs302** [comment]
> Is it this issue: #110971 You don't really explain what you see: nothing, just one line, or how it isn't working.
> 
> If you are just seeing one line of intellisense info, just drag the lower border down to increase its height.

No. In my case, if I start out typing "<div" it suggests "<div>" but does NOT provide the closing tag "</div>".

**Comment by aeschli** [comment]
But as soon as you type `>`, the tag will be closed?

**Comment by evboggs302** [comment]
No. I'm forced to type the entire opening AND closing tags.

**Comment by aeschli** [comment]
You said it worked before right?
- make sure that the editor mode is HTML (status bar lower right) 
![image](https://user-images.githubusercontent.com/6461412/101603615-1f089800-3a00-11eb-8797-3fa6c67d7b48.png)
- make sure the html language feature extension is enabled
![image](https://user-images.githubusercontent.com/6461412/101605275-47919180-3a02-11eb-9753-205e88f544df.png)

**Comment by evboggs302** [comment]
I've confirmed the language extension is enabled. I'm using HTML inside a ReactJS components render. Pl
<img width="1129" alt="Screen Shot 2020-12-09 at 1 13 56 PM" src="https://user-images.githubusercontent.com/49161965/101669885-846c8100-3a20-11eb-84a5-4ef548c71645.png">
<img width="414" alt="Screen Shot 2020-12-09 at 1 14 15 PM" src="https://user-images.githubusercontent.com/49161965/101669887-85051780-3a20-11eb-9849-a7f6c90e0aaa.png">

ease see the attached.

**Comment by aeschli** [comment]
We don't have the auto close feature in JavaScript/TypeScript files.

**Comment by mjbvz** [comment]
@evboggs302  Please share a complete code example that demonstrates the problem

**Comment by evboggs302** [comment]
> We don't have the auto close feature in JavaScript/TypeScript files.

It was previously working. Not sure when it stopped, but i know for a fact it was working in the same situation in which I've described to you.

**Comment by mjbvz** [comment]
@vboggs302 what situation? Please share a complete code example along with steps to reproduce the problem, and then precisely describe the expected behavior

**Comment by evboggs302** [comment]
In summary thus far:
- My intellisense isn't working like before for HTML.
- I checked my settings and the checkbox for the HTML extensions is checked (enabled).
- I've confirmed the language extension is enabled.
- **I'm using HTML inside a ReactJS components render.** 

Code Example: Any js file in this directory https://github.com/evboggs302/productplan-candidate-homework/tree/master/productplan-homework/src/Components

The expected behavior: When typing any HTML element in a JS file (React), intellisense used to and should be able to auto complete the HTML element I'm creating. See photos above as examples of it NOT doing that.

**Comment by mjbvz** [comment]
Please share a minimal example @evboggs302. It's not a good use for time for maintainers to try debugging through your complete project

**Comment by evboggs302** [comment]
https://github.com/evboggs302/productplan-candidate-homework/blob/master/productplan-homework/src/App.js

**Comment by mjbvz** [comment]
What am I supposed to do in that file to reproduce this?
