### ISSUE TITLE
选项卡的错误

### ISSUE THREAD

**Issue by xsustc** [microsoft/vscode#111996]
Issue Type: <b>Bug</b>

I download a extension called tabout to tab out of quotes,brackets etc for Visual Studio Code. But when I printf "int main(void)"(At the moment ,the cursor stay between i and d), I use the tab only to find that the cursor doesn't go out of brackets. So I try to change the keyboard shortcut and I delete the keyboard shortcut of "insertBestCompletion" which is origional tab because I think this usage maybe influence the usage of tabout.However, I find this opration doesn't work. So I add tab to the keyboard shortcut of "insertBestCompletion" again.But when I use vscode to write c program next time I find the tab can't be used.For example,it can't tabout and even can't be used to indent for four spaces. I hope the opration won't cause this problem so I want to ask how I can solve this problem.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.32GB free)|
|Process Argv|--crash-reporter-id f84524bb-7609-46c2-bdfb-bf4af8b17f9a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab-formatter|Aff|2.8.3
TabOut|alb|0.2.0
matlab-interactive-terminal|apo|0.3.3
matlab-extension-pack|bat|0.1.0
matlab-code-run|bra|1.0.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-great-icons|emm|2.1.62
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.1
matlab|Gim|2.0.0
vscode-language-pack-zh-hans|MS-|1.51.2
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
cpptools|ms-|1.1.3
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
matlab-complete|Sla|1.1.1
code-spell-checker|str|1.10.2
errorlens|use|3.2.4
vscode-icons|vsc|11.0.0
material-theme|zhu|3.9.11

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.
