### ISSUE TITLE
Source Control does not update file on disk when changes are discarded

### ISSUE THREAD

**Issue by Fliptron** [microsoft/vscode#111963]
Issue Type: <b>Bug</b>

How to reproduce:
1) Have a project that is using Source Control
2) Make a bunch of edits, and regularly save work in progress (locally)
3) Decide that all the changes are a bad idea, and want to restore to the
    state of the last commit.
4) Select the Source Control icon, and click on the Discard Changes icon for each edited file.
5) The file(s) is/are now displayed in VSCode with all the changes removed,
    but the flag in the file tab indicating that the file has changed is not
    shown, and the file on disk from the last incremental save still has the
    changes.

I suggest that the file has changed flag should be set, and leave it up to the user to save locally, rather than doing it autonomously as part of the Discard Changes process.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX-8370 Eight-Core Processor                (8 x 4013)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (24.64GB free)|
|Process Argv|--crash-reporter-id 4dcd8d8c-2fa0-479c-bd91-757fef602d1d|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.0.0
cpptools|ms-|1.1.3
platformio-ide|pla|2.2.1

</details>

**Comment by eamodio** [comment]
I'm not sure I'm following -- you want discard changes to only modify the buffer for the file but leave it unsaved?

**Comment by Fliptron** [comment]
What you have written "discard changes to only modify the buffer for the file but leave it unsaved" is exactly the current behavior.

What is surprising is that on the file tab for the buffer, the round dot (that replaces the X) indicating that the buffer is different from the file, is not showing. Since the X is shown after the discard changes, the user could close the buffer, thinking the file has the same content, but it actually still has the un-discarded changes.

In normal editing, if the dot is not showing, it means the buffer and the file are identical. After discard changes, the file tab shows the file name and an X, no dot, which normally means buffer and file are the same, but not for this case.

My suggestion is that to be consistent, when you do a discard changes, the X should be replaced by the dot in the file tab so that the user is made aware (reminded) that the buffer and the file are different, and a save buffer is need to make the file also have the changes discarded. This would then be consistent with normal editing, where as soon as the buffer and file are different, the dot is shown.

Maybe a better title for this issue would be "Discard Changes does not show buffer is different from file in the buffer tab"
