### ISSUE TITLE
[BUG] VS Code

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#11194]
- VSCode Version: 1.0.4 [version](http://s22.postimg.org/4mecb0dnl/screenshot_323.png)
- OS Version: Win8.1 64-bit home

Steps to Reproduce:

1. If you open the context menu of a file "VS code", in which you click on the file-referencing (href, src, etc.), will replace the current window.
2.  When you tap on 2x card through which you pop it open and then click on the linking (a href, src, etc.) will open in a new window (or rather the card).

Video:

[BUG - VS code](https://youtu.be/PjObXsQhKOA)

(sorry, for English - translated by google translator)

And thanks for fix.

**Comment by dbaeumer** [comment]
This can be control via the two settings
```
	"workbench.editor.enablePreview": false,
	"workbench.editor.enablePreviewFromQuickOpen": false,
```
Now control clicking will open a new file. Preview tabs are indicated using an italic font.
