### ISSUE TITLE
Ctrl + x (cut function) issue

### ISSUE THREAD

**Issue by andrejbugi** [microsoft/vscode#111970]
When i use the 'ctrl + x' shortcut, and then delete a line ( shift + delete), I also lose the content in the clipboard which was cut before that and when I paste there is nothing there. Thank you

**Comment by usernamehw** [comment]
<kbd>Shift</kbd>+<kbd>Delete</kbd> is also bound to `editor.action.clipboardCutAction` **Cut** action, not a line deletion

![Screenshot (393)](https://user-images.githubusercontent.com/9638156/101296931-537d2800-3837-11eb-9110-e0bf02e47432.png)

You can rebind them through the keybindings editor.
