### ISSUE TITLE
VSCODE crashes after high intensity code is ran

### ISSUE THREAD

**Issue by ShaneWD** [microsoft/vscode#111940]
- VSCode Version: 1.51.1
- OS Version: 18363.1198

Steps to Reproduce:

1. Create a python (.py) file
2. type:
```python
import string, random

while True:
    code = "".join(random.choices(string.ascii_uppercase, k=100000))
    print(code)
```
- This code generates a random code with a length of 100000. It sometimes freezes and crashes after a few seconds, or if I try to highlight the code in the terminal while it is running, then it freezes.  Yes, this code needs a lot of system resources to run, and that's probably why it crashes, however, it would be a great feature if VSCODE detects of the program is about to crash and then it automatically terminates the code(s) running. This way, VSCODE automatically prevents itself from crashing. 

- While replicating this bug, I also came across another: even if the length of the code is 2 (k=2), and I terminate the code by clicking "kill terminal" instead of ctrl+c, VSCODE just freezes. Anything I click afterwards in VSCODE is unresponsive, I am forced to use task manager to close VSCODE. Very strange bug because generating a two-character length code does not require very little amount of system resources. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
The hang when you kill the terminal is tracked in https://github.com/microsoft/vscode/issues/76548

Window responsiveness when running something like that is tracked in https://github.com/microsoft/vscode/issues/74620

/duplicate
