### ISSUE TITLE
TreeDataProvider - refresh() corrupts the tree view with duplicates from another node level

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#111914]
- VSCode Version:  V.51.1
- OS Version: Windows 10

Steps to Reproduce:
I have an extension with a TreeView.
I create each level in the tree and the tree looks fine.
I then introduce the option to perform a refresh() per the examples:
When I click the refresh, the tree rebuilds and open node indents are now getting currupted with entries from other open levels.

Here is an example of the tree when I manually click to expand a level:
![image](https://user-images.githubusercontent.com/46171060/101219400-f3b92e00-3638-11eb-8e51-9ff1f569654c.png)

Then I perform the refresh() which I have linked to a button and wait
When the refresh is complete the tree now looks like this:
![image](https://user-images.githubusercontent.com/46171060/101219687-3c70e700-3639-11eb-8e14-3f422a153702.png)

If I click refresh again I get a different corruption
![image](https://user-images.githubusercontent.com/46171060/101219759-58748880-3639-11eb-8671-6f8a62b10157.png)
and if I collapse the open levels leaving just 1 open, it then refreshes correctly
![image](https://user-images.githubusercontent.com/46171060/101219858-8528a000-3639-11eb-97fc-b07e1cd09378.png)

This appears to be some timing related issue but I can see nothing amiss with my getChildren method

When I build the tree, I know where I am in the tree at any point in time so I know what children to build next.
So the code is relatively simple:

```typescript
public async getChildren(element?: TreeItem): Promise<TreeItem[]> {
    if (!element) {
      //const rootNode = ZmfController.instance.rootNode;
      //return Promise.resolve([rootNode.children]);
      return this._rootSessionNode.children;
    }
    const session: Session = element.session;
    const deps = [];

    //determine the type of node passed in, then retrieve the child nodes
    switch (true) {
      // Profile Root level node
      case element instanceof SessionNode: {
        deps.push(new ApplicationTitleNode(session, "Applications"));
        return deps;
      }

      // presented node is the applicatiopn title retrieve all applications
      case element instanceof ApplicationTitleNode: {
        const children = await Application.process(<BaseLibTypeNode>element);
        if (children) {
          return children;
        } else {
          return Promise.resolve([]);
        }
      }

      // presented node is an applicatiopn node  display the node headings forthis application
      case element instanceof ApplicationNode: {
        deps.push(new BaselineTitleNode(session, "Baselines", element)); // pass the parent  waypoint
        deps.push(new PackageTitleNode(session, "Packages", element)); // pass the parent   waypoint
        return deps;
      }

      // if presented node is the a "Baselines" title  retrieve all Baseline library types
      case element instanceof BaselineTitleNode: {
        const children = await BaselineTitle.process(<BaselineTitleNode>element);
        if (children) {
          return children;
        } else {
          return Promise.resolve([]);
        }
      }
```

and so on.

**Comment by alexr00** [comment]
@davidkjackson54 is this a new problem (did you have this same code on an older version of VS Code and the problem didn't happen there)? 

Can you provide a full example? A repo I can clone is the best.

**Comment by davidkjackson54** [comment]
This is a totally new Explorer that I am creating and using the current version of VSCode. 
Unfortunately, there is no way I can narrow this down to a limited recreation of the problem. I am issuing REST api calls to an underlying product that cannot be provided.
What I can do is to include some diagnostic tracing within getChildren() at each point that I push a node - if that helps?
If you can let me know what you want to see included, I can do that.

**Comment by alexr00** [comment]
@davidkjackson54 given that you are the only person who has seen this issue, I can't help but suspect that it is a bug in the extension, and not in VS Code. Can you add some diagnostic tracing in your tree that proves that the issue is in VS Code? I'm not trying to be difficult, but since I can't repro this issue I think that this will be the best path forward.

**Comment by davidkjackson54** [comment]
I can certainly do that. Before I go down that path can you confirm:

I have getChildren defined as :
`public async getChildren(element?: TreeItem): Promise<TreeItem[]> {`

Is it OK to define it as async?

Then in my individual elements, I check where I am in the tree structure by using instanceof then do this when I knoiw where I am in hte tree and which children to retrieve :
` case element instanceof ApplicationTitleNode: {
        const children = await Application.process(<BaseLibTypeNode>element);
        if (children) {
          return children;
        } else {
          return Promise.resolve([]);
        }
      }`

**Comment by alexr00** [comment]
Async is fine.

**Comment by davidkjackson54** [comment]
Sorry about the formatting, I used the<> but it  wouldn't format correctly. 
I will add some diagnostics and see what it tells me.  I will get back to you .
