### ISSUE TITLE
Installed extensions are not loading

### ISSUE THREAD

**Issue by K-Dinesh-Chitra** [microsoft/vscode#111997]
Issue Type: <b>Performance Issue</b>

This happens on VSCode start up. Whenever I run VSCode the installed extensions are loading/working.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:35:47.374Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B950 @ 2.10GHz (2 x 2095)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|1.88GB (0.35GB free)|
|Process Argv|--crash-reporter-id f944b8b5-b750-4091-8191-b31082551559|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    68	  4640	code main
    0	    63	   228	   shared-process
    0	    21	  2392	   utility
    0	   120	  3900	   window (Welcome - Python Scripts - Visual Studio Code)
    0	    10	   984	     watcherService 
    0	     9	  2348	       console-window-host (Windows internal process)
    1	    62	  2476	     extensionHost
    0	    22	  1504	       "C:\Users\K Dinesh Chitra\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\K Dinesh Chitra\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2476
    0	    47	  3828	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     5	  7580	     console-window-host (Windows internal process)
    0	    11	  5908	   crashpad-handler
    1	    53	  7628	   window (Issue Reporter)
    3	    70	  8128	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - Python Scripts - Visual Studio Code)
|    Folder (Python Scripts): 25 files
|      File types: py(22) json(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.1
prettier-vscode|esb|5.8.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825

</details>

**Comment by gjsjohnmurray** [comment]
Please disable each extension, one at a time. If you find one that is causing the problem, report it to the extension author.

**Comment by K-Dinesh-Chitra** [comment]
No, My problem is the installed extensions (ALL OF THEM) are not loading/enabling at startup, now I have to enable each one manually. I tried disabling each extension one at a time, it's not working.

**Comment by sandy081** [comment]
> My problem is the installed extensions (ALL OF THEM) are not loading/enabling at startup, 

May I know if you are not able to see them in extensions view or they are not running at all in the window?

**Comment by K-Dinesh-Chitra** [comment]
Yes I am able to see them in extensions view but they are not working at startup

**Comment by alexdima** [comment]
@K-Dinesh-Chitra Can you please provide a screenshot of the Extensions Viewlet? Do they appear "greyed out" (i.e. disabled)?

**Comment by K-Dinesh-Chitra** [comment]
NO, they are not greyed out.
But they are not working/loading until I open a file after I open a file they are loading for 5 minutes.
![vscode](https://user-images.githubusercontent.com/75557169/101497463-044b0a80-3991-11eb-9f1c-08bc7057b889.jpg)

**Comment by alexdima** [comment]
@K-Dinesh-Chitra The extension model of VS Code is that extensions start to load only when needed. So if you open a Python file or run one of their commands, etc. If you open an empty vscode window, then it is expected that these extensions don't start up.
