### ISSUE TITLE
CustomEditor webview onDidChangeViewState not firing after first reveal

### ISSUE THREAD

**Issue by DemonOne** [microsoft/vscode#111980]
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Use the pawDrawEditor example, in the first line of resolveCustomEditor(), webviewPanel.ChangeViewState(x => { console.log(`active: ${e.webviewPanel.active})` };
2.  Run the extension, press F1 and run the "Create new paw draw document" command
3. Open a new text document

Expected output by steps:
"active: true"
"active: false"

**Actual output:**
"active: false"

----------------------------
This behavior is inconsistent with regular webviews, where the event is fired when the panel is first displayed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The bug here is that the webview panel is firing this event when its view state has not actually changed
