### ISSUE TITLE
VS code terminal keeps wrong capitalization when opened with code . from Powershell

### ISSUE THREAD

**Issue by andreasblueher** [microsoft/vscode#111972]
Issue Type: <b>Bug</b>

So this is my mistake, but VS Code made my life harder than it could have and maybe it is something which could be changed.

Instead of creating c:\git like a normally do I created c:\Git with my newest dev environment. Opening powershell as usual I entered "cd c:\git" when worked as expected. However creating an nextjs app (and I don't think it's limited to that specific app) using npx create-next-app and try to run or build it using "npm run dev" or "npm run build" resulted in limitless "there-are-multiple-modules-with-names-that-only-differ-in-casing" errors.

It turns out when opening vs code with "code ." from that exact powershell led it to open it's Terminal with the same "wrong" path c:\git instead of the real "c:\Git" on disk. 

Could vs code check for something like that or change it on the inside with even asking because (right now) I can't see a scenario where one would want to use the wrong one.

Cheers, Andreas

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (8 x 3693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (12.49GB free)|
|Process Argv|. --crash-reporter-id c89f4603-b51c-4412-bc55-af531ca071c5|
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by andreasblueher** [comment]
Is this something I might be able to fix myself?

**Comment by Tyriar** [comment]
I think the main issue here is that next.js isn't supporting Windows' case insensitive file system.
