### ISSUE TITLE
showDefinitionPreviewHover works the same as showHover on Remote SSH

### ISSUE THREAD

**Issue by MKRhere** [microsoft/vscode#111953]
Issue Type: <b>Bug</b>

1) Connect to a VSCode Remote over SSH 
2) Use the Command Palette to trigger `"Show Hover"`
3) Use the Command Palette to trigger `"Show Definition Preview Hover"`
4) Notice they give the same results, as opposed to Ctrl + Mouse Hover

The same is reproduceable when using a keybinding to trigger `editor.action.showDefinitionPreviewHover`.

Current Behaviour:
![image](https://user-images.githubusercontent.com/19621208/101267226-7696d180-377c-11eb-8098-e747ccdc046a.png)

Expected Definition Preview:
![image](https://user-images.githubusercontent.com/19621208/101267237-8adace80-377c-11eb-8f1e-330985023ffb.png)

Expected behaviour happens when the steps are repeated on local VSCode, only reproduceable in Remote SSH for some reason.

Related: #46257 #83912

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 4.19.0-12-amd64
Remote OS version: Linux x64 4.19.0-11-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2024)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.76GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6cae26b9-e3d3-447e-b744-60846b2a3156|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|

|Item|Value|
|---|---|
|Remote|SSH: anton|
|OS|Linux x64 4.19.0-11-amd64|
|CPUs|AMD Ryzen Threadripper 2920X 12-Core Processor (24 x 2007)|
|Memory (System)|31.36GB (20.38GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.56.0
remote-ssh-edit|ms-|0.58.0
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
vscode-styled-components|jpo|1.4.0

</details>

**Comment by diminutivesloop** [comment]
I'm seeing this with a regular local project.

```
Version: 1.81.0-insider (Universal)
Commit: 822ad2de026bf4cf858d17237937a3ca743d1b22
Date: 2023-07-21T08:36:34.360Z
Electron: 22.3.17
ElectronBuildId: 22432899
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
```

**Comment by xiyaowong** [comment]
![hover](https://github.com/microsoft/vscode/assets/47070852/870d4def-438f-4e75-a04a-69d322f29a7c)

**Comment by aiday-mar** [comment]
This was happening because we were not awaiting the promise which was adding the hover preview definition. I fixed this with https://github.com/microsoft/vscode/pull/235489

**Comment by MKRhere** [comment]
Thank you!
