### ISSUE TITLE
A malformed git config fails to load SCM and shows no errors

### ISSUE THREAD

**Issue by pathurs** [microsoft/vscode#111990]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. `git config branch.autosetuprebase true` (malformed)
2. Restart VSCode
3. Open SCM
4. SCM doesn't load git repository

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
If Git on the command line breaks with this bad configuration, there isn't much we can do, as we rely on Git (we shell out to it).

**Comment by pathurs** [comment]
@eamodio so there's no way to detect this with git? If not, then that's a shame.

**Comment by eamodio** [comment]
Not that I know of.
