### ISSUE TITLE
 A keybinding when-clause for looking up the position of windows like the panels

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode#111974]
Could the ability to write "when" expression based on position of windows like the panels be added?

I'm needing this because when the panels are on the right side I want to have different keybindings as when it is on the bottom. I'm mirroring TMUX bindings so when I press CTRL-A H when the panel is on the right I want it to move to the editor, but at the bottom I want it to move to split terminals.

**Comment by leighmcculloch** [comment]
I looked in the source code and discovered there is already a context that provides this, `panelPosition`. It's defined here:
https://github.com/microsoft/vscode/blob/fc9ff5d569b34222dcff2ca0bfdc62de86dbd112/src/vs/workbench/common/panel.ts#L11

This context is not included in the documentation however, so maybe it should be added there. See:
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

Is there anyway to programmatically list all the available contexts for updating the documentation?

**Comment by ArturoDent** [comment]
It may not be a direct answer to your question but should help in the future, see https://stackoverflow.com/a/62202897/836330

By following those steps you could see a `panelPosition: "bottom"` context key.

**Comment by leighmcculloch** [comment]
@ArturoDent Thanks for replying and for providing the StackOverflow link, that was really helpful. As I noted above (https://github.com/microsoft/vscode/issues/111974#issuecomment-739583166) I found the solution, to use the `panelPosition` context key, and it is working perfectly! I'll use the developer options tip that you linked to next time.

I think this issue should probably be converted into a documentation issue. It's odd that the official documentation provides a non-exhaustive list of when-clause contexts. Is there a reason the list cannot be exhaustive given that the values are in the code and could be extracted?

**Comment by usernamehw** [comment]
There's is an open issue for autocomplete in vscode repo #9303. And I think there are multiple issues in https://github.com/microsoft/vscode-docs for documenting all context keys.

**Comment by leighmcculloch** [comment]
Thanks! Sounds great. I'll close this then.
