### ISSUE TITLE
C# console error

### ISSUE THREAD

**Issue by camilo43** [microsoft/vscode#111993]
Issue Type: <b>Performance Issue</b>

I installed in visual studio the c# extension and also the framework .NET. When I wrote some lines of code to test the program I got this message:

/bin/sh: scriptcs: command not found

[Done] exited with code=127 in 0.316 seconds.

VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:00:00.397Z)
OS version: Darwin x64 18.7.0

**Comment by sandy081** [comment]
Seems to be an issue with C# extension, please file the issue against that extension.
