### ISSUE TITLE
Missing suggestions in debug console for err object

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#11193]
- VSCode Version: 1.5.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Create a simple node app that uses lodash but do not install lodash
2. Run the app in the debugger
3. Get an error as the lodash module cannot be found.
4. Inspect the err object in the console. Expect to see intellisense for every member of err but only see one suggestion:

![image](https://cloud.githubusercontent.com/assets/1704059/18087548/b2a07bbe-6ead-11e6-9aa2-97ffea62a2c4.png)

Note in the image above how I have previously typed err.message in the window but message is not offered as one of the suggestions when I type err.

**Comment by stevencl** [comment]
Found while testing #10997

**Comment by isidorn** [comment]
The list of suggestions is coming from the node debug backend, thus forwarding to @weinand

**Comment by weinand** [comment]
Properties of error objects are not enumerable. Using Object.getOwnPropertyNames(o) instead of Object.keys(o) fixes that.
