### ISSUE TITLE
Settings: Get directory of VSCode for Portable Setup

### ISSUE THREAD

**Issue by lon91ong** [microsoft/vscode#111983]
I know the topic is exactly same as #82602 , more [#11918](https://github.com/microsoft/vscode-python/issues/11918)
I'm struggled in the same problem 
I want share vscode and python (lite version) with people, 
if `${execPath}` present the **DIRECTORY** where Code.exe located, not the full path like now...

forgive my poor English

**Comment by joaomoreno** [comment]
> if `${execPath}` present the **DIRECTORY** where Code.exe located, not the full path like now...

Why exactly can't you use `execPath`? Seems to give you exactly what you need.

**Comment by lon91ong** [comment]
@joaomoreno what I need is exactly same as #82602
instead of Arduino，I need to share PYTHON lite pack with other fellow

**Comment by joaomoreno** [comment]
And you want this in your debug launch configs?

**Comment by lon91ong** [comment]
@joaomoreno I placed the lite PYTHON pack in the VS Code DIRECTORY, like:
```
VSCode
 |-Code.exe
 |-Python
     |-python.exe
     |-...
 |-...
```
I want set the "python.pythonPath": "${execPath}\\Python\\python.exe"
so Python and VS code are all portalbe

**Comment by joaomoreno** [comment]
So in your settings, I see.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/2809

Variables in the settings are not supported out of the box. Right now extensions are resolving this by themselves.
