### ISSUE TITLE
Notebook save conflict when the workspace has high latency

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#111910]
- VSCode Version: 1.52 Insiders
- OS Version: macOS/Windows

Steps to Reproduce:

1. Connect VS Code to a remote environment which latency is a bit high
2. Turn on auto save, change the auto save delay to `50`
3. Open a github issue notebook, typing
4. `The contents of the file has changed on disk` notification keeps showing up

When connecting to codespace with a high latency network, you will run into this issue very easily as the default save delay is 1 second. Saving a notebook has a couple of round trips between the UI and the server (save, check file stats) so you can easily have two or more save operations happen at the same time.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Can @kieferrm verify? Or @rebornix do you have a good way to simulate latency?

**Comment by rebornix** [comment]
@roblourens when you are connected to a remote workspace, you can always tweak the file auto save delay. When I was testing, setting it to `50` can already trigger the issue. Try set it to `10` and see if you can reproduce, that should be good enough (unless you have near perfect network, super low latency to codespace)

**Comment by roblourens** [comment]
Oh I see
