### ISSUE TITLE
Close all/other tabs should close all saved tabs when some tabs are unsaved

### ISSUE THREAD

**Issue by xixixao** [microsoft/vscode#111973]
Say I have two tabs:
- tab A shows a saved file
- tab B shows a file with unsaved changes

In VS code, if I "Close All" tabs, the editor will first ask me whether I want to save changes in tab B. If I cancel the dialog, no tabs are closed.

In Sublime Text, if I "Close All" tabs, the editor will close tab A, then ask me what to do with tab B.

This is extremely helpful for cleaning up the work space of the editor, when I have tens of tabs open, but I want to keep the unsaved ones around for whatever reason.

The work around is to go and manually close tabs one by one, which is slow and annoying.

**Comment by NotWearingPants** [comment]
While I agree this should be an option, I prefer the current behavior, so this should probably be a setting.
Also, if this change is made I think we should also have a way of reopening the closed tabs with a single command, and not have to reopen one by one until we find the correct set of tabs that were open.
