### ISSUE TITLE
Crashes with webpack and electron

### ISSUE THREAD

**Issue by sgoel1495** [microsoft/vscode#112056]
Issue Type: <b>Bug</b>

1. run webpack watch
2. run electron .
 after sometime, VS Code stops responding and then asks to reopen the window

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.92GB (14.94GB free)|
|Process Argv|--crash-reporter-id d7e939eb-1686-4e38-b7f0-5d098b2ad821|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|2.1.13
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
file-icons|fil|1.0.27
kite|kit|0.135.0
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.12.0
jupyter|ms-|2020.11.399280825
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
typescript-hero|rbb|3.0.0
java|red|0.72.0
django-intellisense|sha|0.0.2
vscodeintellicode|Vis|1.2.10
vscode-swiftformat|vkn|1.3.6
material-theme|zhu|3.9.11

</details>

**Comment by rzhao271** [comment]
Are you running both of those commands in the same repository?

Also, considering it is a crash, can you attach a crash dump?
See https://github.com/microsoft/vscode/wiki/Native-Crash-Issues on how to generate one.
