### ISSUE TITLE
Alert the user when a dependency extension is unable to be downloaded

### ISSUE THREAD

**Issue by AWhetter** [microsoft/vscode#112053]
I have a situation where I am using vscode behind a corporate firewall, so there is no direct internet access. I have downloaded the Jira and Bitbucket extension (https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode) which depends on the YAML extension (https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) that I don't have installed. When I installed the atlassian extension I got no warnings and the installation completed successfully. However the extension does not function because I don't have the YAML extension installed.

Ideally vscode would either fail installation or raise a warning when a dependency extension is unable to be installed automatically.

I am using vscode v1.51.1

**Comment by sandy081** [comment]
Warning message is actually logged in the output view ->  Log (Shared).
