### ISSUE TITLE
alt+leftArrow/rightArrow  cursor backward/forward function failed

### ISSUE THREAD

**Issue by xflyyxfl** [microsoft/vscode#112059]
Issue Type: <b>Bug</b>

alt+leftArrow/rightArrow  cursor backward/forward function failed 
while I am editing python script file in vscode,press alt+leftarrow/rightArrow,Nothing happend

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.30GB free)|
|Process Argv|--crash-reporter-id 373bc24b-479c-40fe-98db-72dde4e93ea4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
Bookmarks|ale|12.0.0
vscode-drawio|hed|1.2.0
classic-asp-html|jtj|0.1.2
bootsnip|kev|1.2.0
csharpextensions|kre|1.3.6
vscode-language-pack-zh-hans|MS-|1.51.2
csharp|ms-|1.23.6
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
debugger-for-chrome|msj|4.12.11
vetur|oct|0.30.3
code-settings-sync|Sha|3.4.3
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.10
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
pyqt-integration|zho|0.2.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by xdumsidedx** [comment]
💙💚💜🖤

**Comment by xflyyxfl** [comment]
> /needsMoreInfo does the problem also happen after you run the command to reload with all extensions disabled?

problem still there after disabled all extension

**Comment by xflyyxfl** [comment]
Sorry buddy, it's another App hook my keyborad, a software of auto-control. close it and goes well
