### ISSUE TITLE
Typing but not seeing words in IDE

### ISSUE THREAD

**Issue by coffeeandc0d3** [microsoft/vscode#112061]
Edit: Resolved now, I found out I'd been using my ctrl + m shortcut for carriage return but that shortcut also activated 'Tab Sets Focus' by default in vsCode so there was a conflict there and all sorts of weird behavior. 

I probably installed a sketchy or conflicting extension but i've disabled a ton of them & still can't  get words to appear on the screen as I type. Sometimes it works but then inevitably goes out. I've noticed using keyboard shortcuts kills any working instance from staying working too so that lead me to look more into any shortcut configs I have but can't see anything conflicting.

**Comment by gjsjohnmurray** [comment]
@coffeeandc0d3 as you solved it please close the issue here.
