### ISSUE TITLE
Need predefined variable ${workspaceFolderDirname}

### ISSUE THREAD

**Issue by weisun76** [microsoft/vscode#112048]
In VS code, we have two predefined variables ${workspaceFolder} and ${workspaceFolderBasename}. For example, if you open "/home/usr1/proj1/task1", the ${workspaceFolder} is "/home/usr1/proj1/task1" and the ${workspaceFolderBasename} is "task1". They work great but missing one useful case. In my project, I need something like ${workspaceFolderDirname} which is corresponding to "/home/usr1/proj1". Would you please be so kind to consider add this predefined variable?

**Comment by weisun76** [comment]
Use the information from vscode official website. 
===============================================================
Supposing that you have the following requirements:

A file located at /home/your-username/your-project/folder/file.ext opened in your editor;
The directory /home/your-username/your-project opened as your root workspace.

So you will have the following values for each variable:

${workspaceFolder} - /home/your-username/your-project
${workspaceFolderBasename} - your-project

What I need is ${workspaceFolderDirname} - /home/your-username

**Comment by sandy081** [comment]
Where are these variables defined? Is it in launches or tasks?

**Comment by weisun76** [comment]
It will be used in all places - settings.json, tasks.json and launches.json.

**Comment by weisun76** [comment]
I checked the source code. There are only two files have "workspaceFolderDirname".
1. vscode-master/src/vs/workbench/services/configurationResolver/common/variableResolver.ts
2. vscode-master/extensions/configuration-editing/src/configurationEditingMain.ts

It should be a simple task in order to add $workspaceFolderDirname.
In #1 file:

				switch (variable) {
					case 'workspaceRoot':
					case 'workspaceFolder':
						return normalizeDriveLetter(this.fsPath(getFolderUri()));

					case 'cwd':
						return ((folderUri || argument) ? normalizeDriveLetter(this.fsPath(getFolderUri())) : process.cwd());

					case 'workspaceRootFolderName':
					case 'workspaceFolderBasename':
						return paths.basename(this.fsPath(getFolderUri()));

					**case 'workspaceFolderDirname':
						return paths.dirname(this.fsPath(getFolderUri()));**
 
In #2 file:
{ label: 'workspaceFolder', detail: localize('workspaceFolder', "The path of the folder opened in VS Code") },
{ label: 'workspaceFolderBasename', detail: localize('workspaceFolderBasename', "The name of the folder opened in VS Code without any slashes (/)") },		
**{ label: 'workspaceFolderDirname', detail: localize('workspaceFolderDirname', "The Dirname of the folder opened in VS Code") },**

Would you please help to have a try?

**Comment by sandy081** [comment]
Settings does not support resolving variables. Its only tasks and debug, hence assigned respective owners.
