### ISSUE TITLE
Console groups show escape codes instead of interpreting them

### ISSUE THREAD

**Issue by clintonblackmore** [microsoft/vscode#112050]
**Describe the bug**

If I do a `console.log` statement and use embedded styles (such as changing the colour), they are reflected in the debug console in VS Code. If I do the same in a `console.group` statement, I see an escape sequence instead of seeing coloured text.

**To Reproduce**

- Connect VS Code to Chrome for debugging
- In the Chrome Javascript console, execute this statement: `console.group("%cThis is a green group", "color: green"); console.log("Inside the group"); console.groupEnd()`
- Note how it doesn't look great in VS Code.

Here's an image of several similar commands typed in the Chrome console:

![image](https://user-images.githubusercontent.com/64144/100810116-f0cdfb80-33f4-11eb-99b4-24b70c9effd6.png)

Here's the output that's seen in VS Code:

![image](https://user-images.githubusercontent.com/64144/100810141-fe838100-33f4-11eb-931a-08ebdab696e0.png)

The expected result is that the `console.group` command show interpret the escape codes and show the text in colour.

**Log File**

Not included, as I think you should be able to reproduce this more easily than look through a log.

**VS Code Version:** 

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Additional context**
None

**Comment by isidorn** [comment]
@clintonblackmore thanks for reporting this. VS Code insiders will have this fix from Friday, so you can try it out then and let us know if it works well for you. I have verified and the issue is fixed now.
Stable will only have this end of January.

**Comment by clintonblackmore** [comment]
Thank you very much, @isidorn and @connor4312. I'm grateful to hear that.
