### ISSUE TITLE
Markdown Preview doesn't work.

### ISSUE THREAD

**Issue by ChaokunChang** [microsoft/vscode#112058]
- VSCode Version: 1.51.1
- OS Version: WSL 2 on windows

I can not preview my markdown file in vscode and vscode insider. When I click the preview button, there are only blank. What's more, this also prevents me to open ipynb files in vscode. What's the weirdest is that, some buttons' image becomes blank, like this:

![image](https://user-images.githubusercontent.com/33217209/101429497-0b94f880-393e-11eb-8b05-7466747abfae.png)

Steps to Reproduce:

1. I don't know how it happened. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Also, are the buttons just blank or are there no buttons are all? Can you open the markdown preview from the command palette?
