### ISSUE TITLE
Mac/UI-consisteny: clicking into inactive editor window should NOT place the cursor

### ISSUE THREAD

**Issue by marc-guenther** [microsoft/vscode#112038]
Issue Type: <b>Bug</b>

### Summary
On the Mac, clicking into a text editor area of an **inactive** window should NOT change the **location** of the text cursor.

### To reproduce
- open any text file in _VSCode_
- remember the location of the text cursor
- select any other window
- click somewhere else in the now inactive editor window.

-> the text cursor does **not** stay where it was, but jumps to the clicked spot.

### Expected behaviour
Cursor location should not change. Try the same steps with _TextEdit_ or a _Mail_ Compose window or even the Github textarea input field in Safari where I'm currently entering this bug report.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|-psn_0_1061123 --crash-reporter-id 942e714c-4201-410a-9a28-266cd696ccc5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.16.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-quick-select|dba|0.2.9
vscode-npm-script|eg2|0.3.13
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
todo-tree|Gru|0.0.188
terraform|has|2.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
vscode-power-mode|hoo|2.2.0
vscode-hacker-typer|jev|0.1.1
cypress-fixture-intellisense|Jos|1.2.0
vscode-map-preview|jum|0.5.6
hg|mrc|1.7.1
vscode-docker|ms-|1.8.1
cpptools|ms-|1.1.3
indent-rainbow|ode|7.4.0
geo-data-viewer|Ran|2.3.0
vscode-xml|red|0.14.0
preview-vscode|sea|2.2.5
code-settings-sync|Sha|3.4.3
vscode-cy-helper|She|1.0.1
ascii-plist|spe|1.0.3
code-spell-checker|str|1.10.2
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.10
quokka-vscode|Wal|1.0.335
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by IllusionMH** [comment]
This is intended behavior that was requested earlier.
You can disable it with `"window.clickThroughInactive": false`

See https://github.com/microsoft/vscode/issues/24634 for details

/cc @bpasero

**Comment by marc-guenther** [comment]
Oh, interesting, thanks.

Although I think the two are somewhat different. The issue you mentioned talks about which element get's the focus, whereas I talked about placing the cursor.

But disabling that setting also disabled placing the cursor, so I think that would solve my problem.

Thanks for making that an option, btw, different people have very different behaviours, and something which feels natural for one person will be completely confusing for somebody else (and vice versa).

I guess this can be closed then?

**Comment by IllusionMH** [comment]
If settings this to `false` works for you and you are not pursuing other goals with this issue (e.g. changing default) then this it can be closed.

If there is something else here - it make sense to clarify request.

**Comment by marc-guenther** [comment]
Oh, it seems the bot was faster than me (I'm in a different timezone). I also don't think I asked a question, but reported a genuine bug (UI inconsistency with Mac standards), so I don't know what that **question** tag is doing there.

To clarify, we are talking about two somewhat different things here:
- the #24634 is about which UI element gets the focus when the user clicks into an inactive window
- whereas this issue is concerned as to where to place the text cursor in that case.

It turns out that the mentioned preference option controls both of them. So, turning it off is perfectly fine for me, and solves the inconsistent behaviour for me.

The only question left would be, what should be the **default setting** for this option. I would strongly prefer the setting which is consistent with the OS, and not the other way round (as it is currently). People who switch OSs on a daily basis can then change the setting, whereas people who stay within one OS (the majority) can feel right at home without any change.

I think consistency within the OS is way more important than consistency of the application across OS boundaries. For example, I strongly object to Eclipse feeling like a Windows application on every platform. It just doesn't make any sense for people who only use Mac or Linux.

But this discussion would be a separate issue, so this one can stay closed. I'm happy as long as I have an option to have a consistent UI. Thanks for that!
