### ISSUE TITLE
vscode ipython text not shown in terminal (remote ssh)

### ISSUE THREAD

**Issue by karthikeyann** [microsoft/vscode#112073]
- VSCode Version: 1.52.0-insider (user-setup)
Version: 1.52.0-insider (user setup)
Commit: bc13785d3dd99b4b0e9da9aed17bb79809a50804
Date: 2020-12-07T14:46:48.305Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
- OS Version: Windows 10 Enterprise (1809)

Steps to Reproduce:

1. Open remote ssh session - host Ubuntu 18.04
2. Open terminal and type `ipython` and Enter.
3. The version information text will not show. (image 1) If the text is shown, Press Ctrl-D or type `exit()`
4. Type `ipython` and Enter again.
5. If you close the terminal view and open again. Those text will show now. (image 2)

image 1:
<img width="1280" alt="vscode ipython rendering problem1" src="https://user-images.githubusercontent.com/6488848/101462221-f92cb600-3961-11eb-826b-4e096b2aefbc.PNG">
image 2:
<img width="1280" alt="vscode ipython rendering problem2" src="https://user-images.githubusercontent.com/6488848/101462293-12cdfd80-3962-11eb-9c9b-5cf3683e0cbd.PNG">

Does this issue occur when all extensions are disabled?: Yes
Remote SSH extension is needed. So, this can't be tested with extensions disabled.

**Comment by meganrogge** [comment]
can you try changing the renderer type? or zoom in and out?

**Comment by meganrogge** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).
/duplicate https://github.com/Microsoft/vscode/issues/45693

**Comment by msalvaris** [comment]
@meganrogge Tried ConPTY by setting the suggested parameter in settings still have issues with terminal. Only appeared when updated to 1.52.1
Are there any other suggestions on how to remedy?
