### ISSUE TITLE
Incorrect current working directory in extension debugging when multiple window opened simultaneously.

### ISSUE THREAD

**Issue by victor-li-02** [microsoft/vscode#112082]
- VSCode Version: 1.51.1, x64
- OS Version: Ubuntu
    - from lsb_release: core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
    - from uname: 4.15.0-123-generic x86_64
- node: 12.19.1

#### Steps to Reproduce:

**In short**: 
1. open `/dirA1/dirA2` by vscode, we got window **A**
1. then open `/dirB1/dirB2` by vscode again, we got window **B**.
1. When debugging vscode extension in **B**, `process.cwd()` will be that of window **A**, `/dirA1`

**Detailed**:

1. `npm install -g yo generator-code` to install yeoman and generator-code
    * or just Follow the [link](https://code.visualstudio.com/api/get-started/your-first-extension) to setup required environment.
1. prepare the following directories:
    * `~/wrong_dir/fake_dir/`
    * `~/correct_dir`
1. `cd ~/correct_dir`
1. `yo code` to generate an extension template project. (assume it's named `work_dir`)
1. First, `code ~/wrong_dir/fake_dir/`, we refer to it as **winA**
1. Second, `code ~/correct_dir/work_dir`, we refer to it as **winB**
1. in **winB**, add the line below to `src/extension.ts`, then save it.
    * `console.log(process.cwd());`
1. in **winB**, `npm run compile`
1. when finished, in **winB**, press `F5` to start `Run Extension`.
    * This will open a new extension window, **winC**
1. in **winC**, exec command `Hello World`
1. see the **DEBUG CONSOLE** of **winB**
    * the output should be **/home/your_username/wrong_dir**, instead of correct_dir
1. `shift+F5` in **winB**, then close **winA** (don't close winB), then retry 9~11 steps.
    * same wrong output.
1. Close all vscode windows, try 6, 9, 10, 11 again
    * correct output

Does this issue occur when all extensions are disabled?: **Yes**

#### Other info

* For vscode windows opened by Nautilus  (Ubuntu's default file manager), it's all the same for this issue.
    * in Nautilus, right-click on a folder - open with other Applications - vscode
* Expectation
    * I guess it would be preferred if the `cwd` isn't affected by another window or the sequence of opening window.

**Comment by weinand** [comment]
VS Code does not provide the notion of a "current working directory" for extension debugging,
because when running VS Code and its installed extensions in production, then different extensions just share the "current working directory" of the extension host process.

This works as designed.
