### ISSUE TITLE
It's not clear which notebook cell is selected. Which will execute next on shift or ctrl-enter?

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#112096]
- VSCode Version: 1.52.0-insider
- OS Version: Windows 10

While dogfooding my own notebook using the new editor I was finding it difficult to know which cell was selected for. If the entire selected cell is not visible, the single line shown is ambiguous. Even if the entire selected cell IS visible, I'm still finding it difficult to see which one is actually selected and ready for execution on shift-enter.

![image](https://user-images.githubusercontent.com/11685408/101509462-a33e1b00-392d-11eb-9b8a-8b572efd890b.png)

**Comment by rebornix** [comment]
Good point @greazer , it's hard to figure out the focus/active notebook cell when there are outputs.

**Comment by greazer** [comment]
Sure, though even when the outputs aren't as large as what I have shown here, the two lines that border the selected cell just doesn't give me enough feedback.

**Comment by misolori** [comment]
I'm wondering if this is something that is learned over time. When a cell is focused, we do still show actions that are visible:

![image](https://user-images.githubusercontent.com/35271042/102281204-5d5ff480-3ee3-11eb-928a-038fe04baef2.png)

And when a cell is selected, the lines are closer to each cell input/output:

![image](https://user-images.githubusercontent.com/35271042/102282167-022f0180-3ee5-11eb-8e6d-9033018b3421.png)

![image](https://user-images.githubusercontent.com/35271042/102282207-15da6800-3ee5-11eb-8ccb-1ac1b2b92c3e.png)



@claudiaregio do you know if we've received any customer feedback for this? Would be great to see how many people are running into this.

**Comment by claudiaregio** [comment]
@misolori We just got a bunch of customer feedback and I will sift through it and double check, don't think I've seen anything specific on this yet. I could see this being an issue where customers may struggle but have trouble pinpointing why. 

I have personally really been struggling using these new indicators to figure out which cell I am in. It is not a quick indicator, I have to double check/double click in a cell to be sure. I have trouble determining right away if the indicator is the bottom of a cell or the top of the cell. The cell toolbar coming up doesn't actually help me at all either because the cell toolbar pops up on hover depending on my mouse position. In the screenshot I provided below, I have selected the top cell, yet my mouse is hovering above the bottom cell. I find myself thinking/figuring out where I am at with this experience but never thought about it with the last implementation. 

![image](https://user-images.githubusercontent.com/19276747/102390650-889d1f00-3f89-11eb-9431-0e0846210029.png)

**Comment by misolori** [comment]
One idea that @jilljac suggested was to make the top cell actions (run, focus border, and cell toolbar) [sticky](https://cdpn.io/miguelsolorio/debug/dypWZdq/LQMExgjKxPLk) when the cell is out of view. I think this will help make it more obvious which cell is focused and bring more clarity. Below is a rough example of that:

https://user-images.githubusercontent.com/35271042/102661439-a7d6b080-4131-11eb-99c1-4a602e805520.mov

**Comment by greazer** [comment]
Here's a suggestion as to how to change the themes to make this situation better. Base the background of the focused cell on the focusBorder color (which is what the cell border defaults to). All I did is default focusedCellBackground and cellHoverBackground to be a slightly transparent version of focusBorder. I have found this to look appealing and also work well to make it easier to see what cell has focus.

Note that changes to the focusedCellBackground can have a much more significant effect on markdown cells than code cells. These defaults seem to work pretty well though.

```json
    "workbench.colorCustomizations": {
        "[Default Dark+]": {
            // "focusBorder": "#007FD4",
            "notebook.focusedCellBackground": "#007FD444", // "focusBorder"
            "notebook.cellHoverBackground": "#007FD411",
        },
        "[Default Light+]": {
            // focusBorder: "0090F1"
            "notebook.focusedCellBackground": "#0090F144", // "focusBorder"
            "notebook.cellHoverBackground": "#0090F111",
        },
        "[Default High Contrast]": {
            // focusBorder: "F38518"
            "notebook.focusedCellBackground": "#F3851888", // "focusBorder"
            "notebook.cellHoverBackground": "#F3851844",
        },
```
![image](https://user-images.githubusercontent.com/11685408/107097181-3924e380-67c1-11eb-91de-f2550cbba32c.png)
![image](https://user-images.githubusercontent.com/11685408/107097251-607bb080-67c1-11eb-958a-59bc1fb4f51a.png)
![image](https://user-images.githubusercontent.com/11685408/107097317-8acd6e00-67c1-11eb-9738-5547f9f304c5.png)

**Comment by misolori** [comment]
@greazer thanks for the suggestion, we used to have background colors for the active cell but it was visually too noisy, so this was one trade off when we went with the focus border color. I still like the original proposal best where we can show the actions sticky when the cell goes out of view.

**Comment by greazer** [comment]
I'm willing to try it, but I don't think that the sticky widgets is going to alleviate this problem well enough, if at all. In the meantime, I'm going to keep the color changes I made for my own sanity. Honestly, it feels WAY better than what we have as the default. To me, it actually helps alleviate the "visual noise" of all the text, and widgets that exist basically share the same color scheme. 

Do we have a measure for visual noise? I'm thinking this is a pretty subjective thing. But perhaps not?

**Comment by misolori** [comment]
> Do we have a measure for visual noise? I'm thinking this is a pretty subjective thing. But perhaps not?

It definitely is subjective and comes down to personal preference. That's why we still kept that background theme color for those who want to use. Also why everything else is so customizable as well.

**Comment by misolori** [comment]
Another thing I was exploring this week was adding a left/right border for cell focus. I've got [a PR open](https://github.com/microsoft/vscode/pull/116409) that will hopefully be merged in the next few days so we can test this out on Insiders.

![Kapture 2021-02-10 at 21 35 05](https://user-images.githubusercontent.com/35271042/107605414-f8c1cd00-6be7-11eb-95a8-dab52e7c3627.gif)
