### ISSUE TITLE
[Feature Request] - Support Github styles in markdown preview

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#112081]
As a lot of developers use Github to host README.md's, contributing guides and gists, it would be nice see a preview of them in VSCode before pushing. This helps to develop more notes and guides offline in the same environment where you write your code.

VSCode does support this but the styling is different.

A nice option would be to offer "github" style markdown, defaulting to the current styling we have today. Users can opt in to the style via their settings.

## Implementation
1. Make use of already-existing styling today https://github.com/sindresorhus/github-markdown-css (It doesn't have to be this)
2. Apply new styles in the [media folder](https://github.com/microsoft/vscode/tree/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/markdown-language-features/media)
3. Switch based on config [here](https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/markdown-language-features/src/features/previewContentProvider.ts#L178-L180): 

## Screenshots
<img width="2071" alt="Screenshot 2020-12-08 at 11 17 17" src="https://user-images.githubusercontent.com/936006/101477315-f8d2f180-3946-11eb-8f7a-867b314a5688.png">

<img width="1779" alt="Screenshot 2020-12-08 at 11 08 20" src="https://user-images.githubusercontent.com/936006/101476994-7ea26d00-3946-11eb-91fb-a923c63c3eec.png">

**Comment by mjbvz** [comment]
See https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview (I think it's using the css you linked to)

**Comment by yuuuxt** [comment]
> 
> 
> See [marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview](https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview) (I think it's using the css you linked to)

hi Matt, 

Is there a tutorial about how to use an online css file? I tried `raw.githubusercontent` but it's not working. I'd like to personally tweak a little bit of your work (mostly fonts) .

**Comment by mjbvz** [comment]
Try downloading the file or using another site. I don't think that GitHub lets content on raw.githubusercontent be served us as css
