### ISSUE TITLE
random debug.log appearance.

### ISSUE THREAD

**Issue by ogrotten** [microsoft/vscode#112051]
Version: 1.52.0-insider (system setup)
Commit: ac165d7f974d70212be80cb15eaecfc1fd20b21a
Date: 2020-11-30T17:36:25.607Z
Electron: 11.0.2
Chrome: 87.0.4280.63
Node.js: 12.18.3
V8: 8.7.220.24-electron.0
OS: Windows_NT x64 10.0.18362

debug.log appears to showup **_randomly_** in the root of my project.

I understand that it's indicative of an extension problem. I ran the bisect command which resulted in what I believe to be a false positive, tho I left it disabled anyway.

What can I do to be more proactive in discovering the source of the problem? Is there a verbose or active logging mechanism or setting, like something that reports when a non-user file is written?

**Comment by gjsjohnmurray** [comment]
Related - #112023

**Comment by ogrotten** [comment]
That's where I learned about the bisect command.

I have since discovered that debug.log appears at the moment of changing git branch while a debug session is active with the following setup:
```
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch Chrome against localhost",
			"url": "http://localhost:3000",
			"webRoot": "${workspaceFolder}"
		}
	]
```
Is there a way to use bisect to generate that moment and see what's dumping?

**Comment by ogrotten** [comment]
Used `bisect` command. It targeted a specific extension in the last round of it's run, but I continue to have debug.log appearing randomly after removing the reported extension. The most recent occurrences of this were unrelated to using debug features.

Even with it added to .gitignore and having used `git rm -r --cached debug.log`, it continues to appear and cause repo updates.

If debug.log appearance is related to an extension, is there a way to make its contents more verbose so that you can tell where it's coming from?

**Comment by jace4511** [comment]
> Version: 1.52.0-insider (system setup)
> Commit: [ac165d7](https://github.com/microsoft/vscode/commit/ac165d7f974d70212be80cb15eaecfc1fd20b21a)
> Date: 2020-11-30T17:36:25.607Z
> Electron: 11.0.2
> Chrome: 87.0.4280.63
> Node.js: 12.18.3
> V8: 8.7.220.24-electron.0
> OS: Windows_NT x64 10.0.18362
> 
> debug.log appears to showup **_randomly_** in the root of my project.
> 
> I understand that it's indicative of an extension problem. I ran the bisect command which resulted in what I believe to be a false positive, tho I left it disabled anyway.
> 
> What can I do to be more proactive in discovering the source of the problem? Is there a verbose or active logging mechanism or setting, like something that reports when a non-user file is written?

**Comment by ogrotten** [comment]
@jace4511 Did you mean to only quote the original post text?
