### ISSUE TITLE
Binary and other untracked assets included in build

### ISSUE THREAD

**Issue by R030t1** [microsoft/vscode#112090]
- VSCode Version: All current
- OS Version: Any, mainly Linux

Steps to Reproduce:

1. Attempt to build VSCode
2. Binaries and untracked assets included in build

Does this issue occur when all extensions are disabled?: N/A

Hello, this is related to #49159 and #45978. These aspects of the build process make VSCode unpackagable as-is for many distributions and extremely hard to impossible to verify for distributions that desire reproducible builds.

I realize this isn't a high priority issue, but the best place to change this is in this repository. Simplest may be finding a way to fetch the build assets from the distribution package manager as appropriate, or adding build settings to refer to a user-acquired copy of these assets. This is the typical solution used in retargetable build systems.

Can this issue be left open and added to a tracking list?

**Comment by joaomoreno** [comment]
> These aspects of the build process make VSCode unpackagable as-is for many distributions and extremely hard to impossible to verify for distributions that desire reproducible builds.

How is sourcing things from `marketplace.visualstudio.com` any different than `npm.org`? Or even `electron.org`? People source external dependencies during build *all the time*.

Our build tools are all open source, so you can **certainly** package VS Code OSS as-is.

What exactly would you like for us to check in to source? Binaries? All our dependencies? The entire Electron dependency? The entire `node_modules` folder? GlibC?

**Comment by R030t1** [comment]
The problem isn't necessarily `marketplace.visualcode.com` vs `npm.org` (though for some people it is). The problem is that build dependencies are not designed to be satisfied in any way but by pulling in packages from a 3rd party source.

>Simplest may be finding a way to fetch the build assets from the distribution package manager as appropriate,

Often language-specific packages are repackaged for distribution. For example, [NPM packages on Ubuntu](https://packages.ubuntu.com/search?suite=groovy&section=all&arch=any&keywords=node-&searchon=names), or similarly [Pip packages on Ubuntu](https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-&searchon=names). This is not merely a Linux endeavor, as there are also [Pip packages for MSYS2](https://packages.msys2.org/search?t=pkg&q=python-).

And, of course, most Linux systems will have programs like ffmpeg and electron installable from their repository.

Software should be constructed in such a way that it can defer to the system or user to find packages. If you only work on one piece of software regularly I can see how this may seem stupid, but it is the easiest way to defeat dependency hell while still making wise use of system resources. It also allows for things like reproducible builds and reduces build times.

**Comment by joaomoreno** [comment]
Got it. We simply do not support your scenario unfortunately, nor plan on doing so, as explained in the other issues. Sorry about that.

**Comment by R030t1** [comment]
Is there a reason you can't keep this open so someone else can fix it?
