### ISSUE TITLE
VS Code language service will fail if the root directory name includes `[` or `]`

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#112002]
### 1. Env:

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

### 2. Steps to Reproduce:

1. Run any project on Windows 10 where the directory contains `[` or `]`
2. VS Code language service will fail **(read below for details on what this issue is related to)**

### 3. The detailed context of the problem:

- We have a problem with fix issue https://github.com/pucelle/vscode-css-navigation/issues/29 in plugin [CSS Navigation](https://github.com/pucelle/vscode-css-navigation)
- We can't find where the problem is, and owner of this extenion says [_"May be this is a vscode system issue."_](https://github.com/pucelle/vscode-css-navigation/issues/29#issuecomment-739613609)
- That's why I allowed myself to start this thread in your VSCode repository
- Can we ask you to verify that this problem is not caused by a bug in VSCode?

**Comment by aeschli** [comment]
Sorry,  we need precise steps that show a problem is in VSCode. I tested with the built-in HTML and CSS support and could not find any issues with folders containing `[` and `]`
