### ISSUE TITLE
Explorer takes focus away from rename box too fast

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112084]
1. Focus a file/folder
2. <kbd>Ctrl C</kbd>, <kbd>Ctrl V</kbd> to duplicate it
3. Immediately after press <kbd>F2</kbd> to rename

:bug: The input box goes away automatically. Some file event comes in and kills it.

I keep hitting this lately... 😢

**Comment by isidorn** [comment]
Yeah, dup of https://github.com/microsoft/vscode/issues/111652
Fixing it today / tomorrow

Thanks for reporting
