### ISSUE TITLE
Download remote folder picker

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#112045]
- Open a codespace
- Right click folder in the explorer, Download
- Get this file picker

The title makes it sound like I am picking the folder to download, but this is the download destination. Also defaulting to the logs folder is unexpected.

![image](https://user-images.githubusercontent.com/323878/101399080-d75d0180-3883-11eb-9f01-bbb35d98dfe7.png)

**Comment by isidorn** [comment]
We can fine tune the label -> assigning to this milestone to fix 
As for defaulting I believe there is a seperate issue to track that. @alexr00 did you tackle something similar to this

**Comment by alexr00** [comment]
If the caller of the dialog doesn't provide a default, then the dialog service will pick one.
Default logic is here: https://github.com/microsoft/vscode/blob/aa18ca682765edd34edb0c231053577c5d5835d8/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L68-L83

**Comment by isidorn** [comment]
I have changed the wording to
"Chose Where to Download"
If you have better suggestions let me know.
Alternative ideas:
"Download To"
"Choose Download Destination"
