### ISSUE TITLE
Editor copies the whole line even when a subset of the line is highlighted

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/vscode#112035]
- VSCode Version: 1.51.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open up a text editor with some code (C++, C#)
2. Find an identifier on a line (different from where the caret currently is) and click in the middle of it with this timing: click, double-click, click
3. Note that the whole line is not selected when the timing is right. Yet when you copy to the clipboard with ctrl+c you get the whole line.  This is the selection I see in the editor:

![image](https://user-images.githubusercontent.com/5177512/101382887-b2619200-3875-11eb-9203-0a03956e0722.png)

Even though only `user` is displayed as selected, the copied text is: `    user: string;`.

This has been driving me batsh!t for a while now.  I suppose the bug here is that the editor selection, in this case, should indicate the entire line has been selected since the entire line is copied to the clipboard.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
- in the screenshot above, `user` is not selected. It is highlighted via a setting called `"editor.occurrencesHighlight"` which can be turned off if you don't like it.
- when there is no selection and ctrl+c is pressed, the entire line gets placed in the clipboard. This can be turned off via a setting called `"editor.emptySelectionClipboard"`

**Comment by rkeithhill** [comment]
@alexdima That second tip did the trick.  Thanks!
