### ISSUE TITLE
Settings searchbar missing 

### ISSUE THREAD

**Issue by Kovinda** [microsoft/vscode#112003]
Issue Type: <b>Bug</b>

Can't search for user settings because the searchbar is missing !

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.62GB free)|
|Process Argv|--crash-reporter-id 3c55c5f7-2bd2-4afd-a8e1-4b84c3690d0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
todo-tree|Gru|0.0.188
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.11

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Does this also happen after you run the command palette command to reload with all extensions disabled?

If yes, please paste a screenshot here.

**Comment by Kovinda** [comment]
Duplicate of #64932
these settings worked !

"workbench.settings.useSplitJSON": true,
"workbench.settings.editor": "json"
