### ISSUE TITLE
[Windows 8.1] Touch Keyboard pops up at tap on code/text

### ISSUE THREAD

**Issue by Shassk** [microsoft/vscode#112018]
- VSCode Version: Version: 1.51.1 (system setup)
- OS Version: Windows 8.1 32-bit (Windows_NT ia32 6.3.9600)

Basically everything was already described in [#76634](https://github.com/microsoft/vscode/issues/76634).
Except it happens on the latest version of VS Code.
Also when keyboard pops up - whole window slides up by keyboard height which is laggy and extremely annoying (same happens only in other MS products like Office and Skype).

**Comment by Shassk** [comment]
Nothing changed in 1.52.0, still completely unusable.

**Comment by deepak1556** [comment]
Is this still an issue with latest stable `1.53.2` ? Can provide some steps or screen recording to show the issue, I am unable to repro on my windows 10 machine.

**Comment by Shassk** [comment]
Damn, missed your reply.

Here's a [video](https://youtu.be/jKKD8m-Oz0c) showing what's happening.

**Comment by deepak1556** [comment]
Windows 7 has reached EOS https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-older-windows-versions, if the issue is present with latest version of Windows I can reopen the issue.
