### ISSUE TITLE
eslint.fixAllProblems command not found

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11205]
Refs: #11100

- VSCode Version: Latest or stable
- OS Version: OS X

Steps to Reproduce:

1. Install eslint extension
2. Trigger 'ESLint: Fix all auto-fixable problems' from command palette
3. Notice error

![screen shot 2016-08-30 at 14 52 09](https://cloud.githubusercontent.com/assets/1926584/18089713/96cc87e8-6ec1-11e6-9361-6bd8bb1ba582.png)

**Comment by dbaeumer** [comment]
To verify use: 
[vscode-eslint-1.0.1.zip](https://github.com/Microsoft/vscode/files/449621/vscode-eslint-1.0.1.zip)

**Comment by anicoll** [comment]
Why is this bug closed? has it been resolved?

**Comment by gangachris** [comment]
I'm also getting the same error. @dbaeumer was it resolved?

**Comment by dbaeumer** [comment]
@gangachris  Yes, it got resolved however you have to get the latest eslint extension (1.0.5). If you still see it there please ping back.

**Comment by gangachris** [comment]
After going through https://github.com/Microsoft/vscode-eslint/commit/4f554e7593fc066ea12e11fe416ef72bdb59c547 , had to change my  key binding from `eslint.fixAllProblems` to `eslint.executeAutofix`.
