### ISSUE TITLE
Visual Studio Debugger Crashes when hover over variable on breakpoint

### ISSUE THREAD

**Issue by RealJavascriptKid** [microsoft/vscode#112028]
I have very straight forward code which is:

index.js
```
let myvar = `some value`;
console.log(myvar)
myvar = 'new val';
console.log(myvar)
```

package.json

```
{
  "name": "vs_crash",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

There is no node_modules installed and put breakpoint on any of the lines and when I run visual studio code in debug mode (Node.js) and when it hits the breakpoint as soon as I hover my mouse over the variable "myvar" it crashes the debugger 

I also tried by turning on "Developer Tools" and I get following warning in console when it breaks

```
Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at d.add (lifecycle.ts:158)
    at c._register (lifecycle.ts:188)
    at actionbar.ts:271
    at Array.forEach (<anonymous>)
    at c.push (actionbar.ts:264)
    at toolbar.ts:167
    at Array.forEach (<anonymous>)
    at h.setActions (toolbar.ts:166)
    at G.setActions (viewPaneContainer.ts:485)
    at G.updateActions (viewPaneContainer.ts:499)
    at g.runner (callStackView.ts:171)
    at g.doRun (async.ts:693)
    at g.onTimeout (async.ts:687)
```

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using vscode insiders https://code.visualstudio.com/insiders/
Also that error in the developer console is unrelated and would not cause a carsh

**Comment by RealJavascriptKid** [comment]
I have create my repository and also attached a recording of showing the issue https://github.com/RealJavascriptKid/vs-crash

**Comment by isidorn** [comment]
Aha you are using a legacy node debugger. And you probably have a new node version -> thus the hover stops the program since we probably try to evalaute and you have an incompatible node version.
Forwarding to @weinand and @connor4312 

@RealJavascriptKid you can use nodeJS (preview) instead
@connor4312 we should really fix these lables as preview sounds like it is in a worse shap than it actually is

**Comment by weinand** [comment]
@RealJavascriptKid what version of node.js are you using?

**Comment by weinand** [comment]
@isidorn selecting "Node.js (legacy)" does not actually select the old node-debug DA (because the debug type "node" is redirected to "pwa-node" anyway. And the CALLSTACK confirms this: 

js-debug shows anonymous in angle bracktes:
<img width="267" alt="2020-12-09_10-55-23" src="https://user-images.githubusercontent.com/1898161/101614288-1074ad80-3a0d-11eb-9650-b2b8ed2b6c38.png">

whereas node-debug2 uses parenthesis:
<img width="465" alt="2020-12-09_10-51-49" src="https://user-images.githubusercontent.com/1898161/101614231-fd61dd80-3a0c-11eb-9075-6198c8aac1fa.png">

So there must be something else...

**Comment by weinand** [comment]
@connor4312 I've create https://github.com/microsoft/vscode/issues/112139 to rename "Preview..."

**Comment by connor4312** [comment]
I'm not sure the DisposableStore error is necessary related to the problem you're seeing; to me it looks like Node.js crashes/exits when the hover happens. Please try doing the following:

1. Selecting the "create a launch.json file" link that shows in the debug view
1. Create a node.js config, which should be set up to launch index.js.
1. Collect logs from the session:

/jsDebugLogs

**Comment by RealJavascriptKid** [comment]
Node.js (preview) also fails

In case if it helps following are my system specifications:
**node**: v10.9.0
**npm**: 6.2.0

### Device specifications:

**Processor**: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 GHz
**System type**: 64-bit operating system, x64-based processor

### Windows specifications:

**Edition**: Windows 10 Pro
**Version**: 1909
**OS Build**: 18363.1256


Visual Studio Code works fine in my other machines. It is only this specific system. It only crashes when you hover over variable. it still works if I add variables to watch list or directly inside debug console

**Comment by connor4312** [comment]
Okay, thanks. Please grab a log if you can.

**Comment by RealJavascriptKid** [comment]
[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode/files/5668880/vscode-debugadapter-0.json.gz)

I have attached the log file

**Comment by RealJavascriptKid** [comment]
Also in log file it says node version v12.14.1
which is not true
![image](https://user-images.githubusercontent.com/55029881/101692496-4c743680-3a3e-11eb-9eb5-b184d7dc1568.png)

**Comment by RealJavascriptKid** [comment]
and here is screenshot to launch.json

![image](https://user-images.githubusercontent.com/55029881/101692637-7e859880-3a3e-11eb-8f92-076521500926.png)

**Comment by connor4312** [comment]
Okay, thanks. This looks like it's an issue upstream. So I would suggest grabbing the latest Node.js release (15.4.0) to see if it still reproduces: https://nodejs.org/en/download/releases/. If so, then we can open a bug for the Node.js or Chromium team.

**Comment by RealJavascriptKid** [comment]
I am still unsure why this occur. But I am able to fix it by using NVM and switching Node version.
I was using node 10.9.0 and switched to 10.10.0 in my Launch configuration and it fixed the issue. But weird thing is it working now even if I switch back to 10.9.0
