### ISSUE TITLE
[FR]: Allow disabling "There is an available update" popup or certains popups in general

### ISSUE THREAD

**Issue by kiprasmel** [microsoft/vscode#112041]
More often than not I open vscode and get the popup "There is an available update". I use a package manager (pacman on arch linux) to manage my programs etc., thus I do not upgrade vscode through itself by clicking the "install latest updates" or whatever button, thus it does not bring in any use other than being slightly annoying

Any chance to add an option to disable it?

I'd be great to be able to disable certain popups in general - for example, vscode often shows "your vscode installation appears to be corrupt. please reinstall", but it works just fine and I don't want to re-install - I'd like to disable it aswell. A general solution, like an array of disabled popups, would be great.

**Comment by joaomoreno** [comment]
Sure, you can set `update.mode` to `none`.

**Comment by kiprasmel** [comment]
Thanks João, this helps!
