### ISSUE TITLE
Proposed API is only available when running out of dev or with the following command line switch

### ISSUE THREAD

**Issue by rakeshvanga** [microsoft/vscode#112057]
- VSCode Version:
```
Version: 1.52.0-insider (user setup)
Commit: bc13785d3dd99b4b0e9da9aed17bb79809a50804
Date: 2020-12-07T14:46:48.305Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Try to activate extension `Bridge To Kubernetes`. This extension is working fine with VS Code version:
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```
But seeing following error with insiders: 
![image](https://user-images.githubusercontent.com/33327237/101422898-af35c880-38ac-11eb-8937-bd48b5ae2a41.png)

No changes were made to the extension.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
@rakeshvanga Are you developing this extension? There is very little reproducible info here. The error is caused by extensions using API which isn't generally available yet. So, if you the author then please provide more insight, otherwise file this issue against the extension

**Comment by jrieken** [comment]
This issue might be https://github.com/microsoft/vscode/issues/111913

**Comment by rakeshvanga** [comment]
@jrieken Thanks for pointing to the right issue. Yes, that seems to be the right issue. Closing this one.
