### ISSUE TITLE
request times too more

### ISSUE THREAD

**Issue by chenxuyaoniming** [microsoft/vscode#112068]
Issue Type: <b>Bug</b>

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 12, 9|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id b53f22ce-5461-4003-8246-a9813bece4b2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-swan|efe|0.1.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
code-runner|for|0.11.1
beautify|Hoo|1.5.0
vscode-pont|jas|1.0.6
git-graph|mhu|1.28.0
vscode-language-pack-zh-hans|MS-|1.51.2
vetur|oct|0.30.3
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.4.0
java|red|0.72.0
LiveServer|rit|5.6.1
rainbow-fart|sae|1.4.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.0
vscode-maven|vsc|0.26.0
vuter|yoy|0.1.2
material-theme|zhu|3.9.11

(7 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please explain what the bug is.
