### ISSUE TITLE
Can't readily tell which cell is executing

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#112097]
- VSCode Version: 1.52.0-insider
- OS Version:

While dogfooding the native notebook experience...

1. Open a notebook that contains at least one cell that takes a long time to execute.
2. Run all cells
3. While long running cell is executing scroll down to other cells that aren't executing yet.

The spinning status icon of the subsequent cells imply that the cell is actually executing, even though it isn't yet. The existence of the stop button (that replaces the play triangle) and the indefinite blue progress bar makes it more confusing.

This is probably something I could get used to, but it makes the transition from Jupyter Notebooks or Jupyter Lab less comfortable.  

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
> The spinning status icon of the subsequent cells imply that the cell is actually executing, even though it isn't yet. The existence of the stop button (that replaces the play triangle) and the indefinite blue progress bar makes it more confusing.

We don't change the execution status of individual cell in the core when executing command "Run all cells", the extension modifies the run status of each cell. @DonJayamanne can you confirm this?

**Comment by DonJayamanne** [comment]
> xecuting command "Run all cells", the extension modifies the run status of each cell. @DonJayamanne can you confirm this?

yes this is correct.
