### ISSUE TITLE
created index.vue and change name to Index.vue then can't open Index.vue

### ISSUE THREAD

**Issue by shankesgk2** [microsoft/vscode#112001]
版本: 1.51.1
提交: e5a624b788d92b8d34d1392e4c4d9789406efe8f
日期: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

- VSCode Version:1.51.1
- OS Version: MacOS 11.1 Beta (20C5061b)

Steps to Reproduce:

1.Create index.vue
2.Change file name to Index.vue
3.Open Index.vue
<img width="450" alt="WX20201207-162415@2x" src="https://user-images.githubusercontent.com/8123290/101326768-b8249b00-38a8-11eb-917d-c138e5709bd4.png">

can't open "Index.vue":can't read file '/xxxx/xxxx/index.vue' (Error: Cannot parse a file that does not exist"/xxxx/xxxx/index.vue").
changed index.vue to Index.vue with case-sensitive file system

Does this issue occur when all extensions are disabled?: Yes

CPUs | Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.74GB free)
Process Argv | --crash-reporter-id 0bcf1b97-065f-4a81-9db1-3a8ea413277b
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
rainbow-brackets | 2gu | 0.0.6
vscode-angular2-files | ale | 1.6.4
css-compressor | bes | 0.0.2
vscode-intelephense-client | bme | 1.5.4
vscode-mysql-client2 | cwe | 2.8.5
vscode-eslint | dba | 2.1.13
prettier-vscode | esb | 5.8.0
php-debug | fel | 1.13.0
php-intellisense | fel | 2.3.14
php-pack | fel | 1.0.2
auto-close-tag | for | 0.5.9
auto-rename-tag | for | 0.1.5
vscode-mysql | for | 0.4.0
vue-snippets | hol | 1.0.4
vscode-language-babel | mgm | 0.0.30
code-beautifier | mic | 2.3.3
Angular-BeastCode | Mik | 10.0.3
vscode-language-pack-zh-hans | MS- | 1.51.2
python | ms- | 2020.11.371526539
jupyter | ms- | 2020.11.399280825
vscode-typescript-tslint-plugin | ms- | 1.2.3
env-cmd-file-syntax | Nix | 0.2.2
vetur | oct | 0.30.3
webapplicationservices | Opa | 6.10.2
trailing-spaces | sha | 0.3.1
vscode-icons | vsc | 11.0.0
txt-syntax | xsh | 0.1.2

**Comment by mjbvz** [comment]
Are you sure this happens with all extensions disabled? Specifically the vetur extension? 

Make sure to restart VS Code after disabling extensions
