### ISSUE TITLE
Provide a warning when an externalConsole attribute used in Launch

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11209]
Testing #11091 

Steps to Reproduce:

Since `externalConsole` attribute is deprecated, it would make sense to show a warning in the launches when this attribute is used.

**Comment by isidorn** [comment]
August to investigate

**Comment by isidorn** [comment]
Fixed by 74a526a in https://github.com/Microsoft/vscode-node-debug

**Comment by isidorn** [comment]
Actually that is not a good fix, since we still want to show the message that the attribute is deprecated.
@aeschli we want to always show a custom warning message for a field in our json schema. I figured we can use a `pattern` that always fails and use the `errorMessage` there. But not sure if there is some nicer way to achieve this?

**Comment by aeschli** [comment]
I would do the 'pattern' and 'custom error' message trick. JSON schema doesn't have a way to disallow a specific property. You can enforce that only the specified properties are allowed, but the error message will be generic.

**Comment by isidorn** [comment]
Work on our side is done, for this to fully work we are waiting for #11305

**Comment by sandy081** [comment]
@isidorn It seems the warning is appearing on the value instead of the attribute. It looks like as if the value is not supported. But in this case attribute itself is not valid. So does it makes sense to show squiggle on attribute or complete attribute-value?

![screen shot 2016-09-01 at 11 23 56](https://cloud.githubusercontent.com/assets/10746682/18162426/bce64560-7036-11e6-9c52-dc137d813904.png)

**Comment by isidorn** [comment]
@sandy081 It would be nicer to show the warning on the attribute, but this is not currently supported by @aeschli. So we are doing this as a workaround
