### ISSUE TITLE
Cannot connect with node app via remote debugger

### ISSUE THREAD

**Issue by konraddysput** [microsoft/vscode#112011]
- VSCode Version: 1.51.1
- OS Version: Windows (debugging process on Linux via remote-ssh)
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. Ssh into any Linux box with nodejs app
2. Start new debugging session - 
```
"debug": "NODE_ENV=development node --inspect-brk=0.0.0.0:9229  ./dist/main.js -c ./conf-file-name.conf",
```
3. Connect via remote debugger 

```
 {
      "type": "node",
      "request": "attach",
      "name": "Attach to Node process",
      "port": 9229,
      "restart": true,
      "sourceMaps": true,
      "smartStep": true,
      "stopOnEntry": false,
      "timeout": 50000,
      "localRoot": "${workspaceFolder}",
      "remoteRoot": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceRoot}/node_modules/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "outFiles": ["${workspaceFolder}/dist/**/*.js"]
    }
```

Remote debugging worked really well until current update. I didn't find anything related to this bug in your release notes.
Screenshot of an error:

![image](https://user-images.githubusercontent.com/9386268/101349152-2fe4cc80-388d-11eb-9a17-a49cc2c60f62.png)

Does this issue occur when all extensions are disabled?: Yes/No
Can't test.

**Comment by konraddysput** [comment]
I was able to temporary solve this issue by disabling `debug.javascript.usePreview`

**Comment by konraddysput** [comment]
It looks like I don't' have this problem anymore - today I got a new VSCode update and it started working once again. Thanks

**Comment by connor4312** [comment]
Ok, thanks for confirming!
