### ISSUE TITLE
TAB should not indent empty lines in a multi-line selection

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#1120]
1. Start with the document:

    ```
    a
    b
    
    c
    ```

1. Select the entire text

1. Press <kbd>TAB</kbd>

Expected: The three lines with text get indented. The empty third line remains unindented.

```
    a
    b

    c
```

Actual: All the four lines get indented, and I then have to manually delete the trailing whitespace from the third line.

```
    a
    b
    ‌
    c
```

(This is only when indenting a multi-line selection; when pressing TAB in an empty line then the line *should* get indented as it currently does.)

**Comment by alexandrudima** [comment]
:+1: I like the idea

**Comment by yo1dog** [comment]
Is it possible to add a setting for this? I prefer to keep proper whitespace indentation on all lines, including empty ones.
