### ISSUE TITLE
Debug.log file appears everywhere. 

### ISSUE THREAD

**Issue by maw136** [microsoft/vscode#112023]
Issue Type: <b>Bug</b>

Open a folder (to do some code editing or anything)
there is the file 'debug.log'
content:
[1207/153733.086:ERROR:registration_protocol_win.cc(102)] CreateFile: The system cannot find the file specified. (0x2)
and appending every open

VS Code version: Code - Insiders 1.52.0-insider (ac165d7f974d70212be80cb15eaecfc1fd20b21a, 2020-11-30T17:36:25.607Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3299)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (10.49GB free)|
|Process Argv|.\\DevOps\\ --crash-reporter-id f2d845c9-a92c-4386-bbc6-5a22138b5238|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
vscode-angular2-files|ale|1.6.4
ng-template|Ang|0.1100.2
vscode-jest-runner|fir|0.4.31
vscode-test-explorer|hbe|2.19.3
vscode-jest-test-adapter|kav|0.7.4
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.6
mssql|ms-|1.9.0
remote-wsl|ms-|0.52.0
cpptools|ms-|1.1.3
powershell-preview|ms-|2020.9.0
vscode-typescript-tslint-plugin|ms-|1.2.3
angular-console|nrw|15.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-maven|vsc|0.26.0
vscode-icons|vsc|11.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the new bisect command in the Command Palette to try and discover which of your extensions may be creating the debug.log files.

**Comment by ogrotten** [comment]
Used `bisect` command. It targeted a specific extension in the last round of it's run, but I continue to have debug.log appearing randomly after disabling that extension.

Even with it added to .gitignore and having used `git rm -r --cached debug.log`, it continues to appear and cause repo updates.
