### ISSUE TITLE
Allow contributions to the Activity Bar context menu

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#112094]
It would be handy to do some actions on a view directly from the activity bar context  menu, passing the view under the pointer when clicked.

**Comment by sandy081** [comment]
Can you please provide specific use case or an example so that it is easy to understand the requirement?

**Comment by Gruntfuggly** [comment]
I'd like to be able to add a button to the status bar to open the view as an alternative. Also, I'd like to be able to open the settings for the view from the menu.

I realised these are fairly specific, but I am presuming it's not a huge job to allow it?

**Comment by eamodio** [comment]
So this would be on just on a specific activity bar icon? Not for the bar itself?

**Comment by Gruntfuggly** [comment]
Yes, well all activity bar icons - with the associated container id (or view ids?) passed to the receiver.
