### ISSUE TITLE
Extension Host crashes randomly

### ISSUE THREAD

**Issue by e-tip** [microsoft/vscode#112005]
- VSCode Version: 1.51.1
- OS Version: MacOS 11.0.1

I use to launch my application always in debug mode using launch.json

```
{
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "name": "Core",
            "program": "${workspaceFolder}/app.js",
            "request": "launch",
            "restart": true,
            "runtimeExecutable": "nodemon",
            "args": [ "--trace-deprecation", "-a", "api"],
            "skipFiles": [
                "<node_internals>/**",
                "${workspaceFolder}/node_modules/**/*.js"
            ],
            "type": "pwa-node"
        },
```
My development hardware is a macbook pro 2020 base with 8 GB of ram. With the upgrade of os to Big sur, i've started to face an error Extension host terminated unexpectedly- Javascript heap out of memory
Opening developer tools i can see this error 
[visual_studio_code_error.log](https://github.com/microsoft/vscode/files/5651775/visual_studio_code_error.log)
Where it states that the extension that is gigving problems is the 
![image](https://user-images.githubusercontent.com/1098494/101334953-d4104880-3878-11eb-9175-d2188d81838a.png)
This is the cpuprofile file 
[cpuprofile.tar.gz](https://github.com/microsoft/vscode/files/5651799/cpuprofile.tar.gz)

**Comment by connor4312** [comment]
@deepak1556 if I recall correctly you had an issue for this. Profile contents:

![](https://memes.peet.io/img/20-12-d0213088-fcb1-41a9-8875-1e1096f7e449.png)
