### ISSUE TITLE
Removing some buttons from the menu bar

### ISSUE THREAD

**Issue by at-guedesnt** [microsoft/vscode#112083]
Even if I know it's useful for a lot of people, I don't need these features under there like "Go", "Run" and "Terminal".

Is there a way for me to remove it from the menu?

![Captura de tela de 2020-12-08 08-32-15](https://user-images.githubusercontent.com/21070088/101478920-26607080-3930-11eb-803a-f652e5f893b1.png)

Thank you.

**Comment by sbatten** [comment]
That is not possible currently. You could set the visibility of the menubar to `toggle` or `hidden` if you do not wish to see the menubar regularly. Alt is then used to summon the menubar in the case of `toggle`. I don't think this feature request is something we will implement at this time.
