### ISSUE TITLE
An Interactive Sequence Diagram Editor for VSCode

### ISSUE THREAD

**Issue by imesh** [Microsoft/vscode#11202]
At [WSO2](https://github.com/wso2) we are trying to build a new tooling platform using web-based technologies on top of VSCode. The initial requirement is to build an interactive sequence diagram editor for [WSO2 Gateway] (https://github.com/wso2/carbon-gateway-framework/) for modelling integration workflows. 

We went through VSCode extension model and the existing extensions for available diagramming tools but could not find something similar to $subject. We found several options for integrating JS based sequence diagramming tools but they do not support interactive drawing.

The goal of this effort is as follows:
- Implement a new sequence diagram editor in JS and integrate it with VSCode. We have already started this and source code can be found [here](https://github.com/wso2-incubator/js-tooling-framework/tree/master/sequence-editor).
- Allow users to interactively draw sequence diagrams on VSCode. 
- Introduce [a new language](https://github.com/wso2/carbon-gateway-framework/blob/master/gateway-core/components/org.wso2.carbon.gateway.core/src/main/antlr4/org/wso2/carbon/gateway/core/config/dsl/external/wuml/generated/WUML.g4) for defining sequence diagrams and provide language support on VSCode may be using language server.
- Transform visual diagrams into sequence diagram definitions and save as files.
- Once sequence diagram definition files are opened in VSCode, render them in visual mode.
- Allow users to define the sequence flow in both source mode and visual mode.
- Integrate VSCode editor features with the visual representation of the diagrams. For an example debugging, opening up property windows for managing metadata of diagram elements, adding new buttons in VSCode for managing diagramming features, etc.
- Finally, make this tooling solution accessible on the web.

Q1: Would it be feasible to do this via the VSCode extension API?

Q2: If not will us be able to extend VSCode at the editor abstraction and integrate a new visual sequence diagram editor similar to [Monaco](https://github.com/Microsoft/monaco-editor)? 

Q3: Would it be possible to run VSCode on the web and make it accessible via a web browser?
We noticed that Microsoft has done this [at some point](https://channel9.msdn.com/Series/Visual-Studio-Online) but could not find much information on how to do it.

Really appreciate your thoughts on this!

**Comment by jrieken** [comment]
This answers `Q1` and `Q2`: https://code.visualstudio.com/docs/extensions/our-approach, https://github.com/Microsoft/monaco-editor#faq. Re `Q3`: VS Code is a native app.

**Comment by imesh** [comment]
Thanks @jrieken for your quick response! We will go through the extension API and monaco editor documentation in detail.

Regarding Q3, I understand that vscode is a native application implemented on top of electron. I thought it has a separation between the backend and frontend components, and that's how it's run on Azure [1] for editing websites. Is that a separate web application that you have developed by incorporating Monaco?

[1] https://blogs.msdn.microsoft.com/monaco/2014/06/25/how-to-access-visual-studio-online-monaco-from-the-new-azure-portal/ 

Thanks!

**Comment by jrieken** [comment]
Consider that as a pre runner which won't just work again with our current codebase

**Comment by imesh** [comment]
Right! Got it! Thanks for the clarification!
