### ISSUE TITLE
os.getenv not working on Mac 

### ISSUE THREAD

**Issue by ianbroad** [microsoft/vscode#112062]
In my Flask app I use `os.getenv()` to get the `CLIENT_ID`, `CLIENT_SECRET`, and `SECRET_KEY` environmental variables that are specific to my project (using AzureAD). Yesterday this was working fine within VS Code, but today it just returns `None`. The app works fine when ran directly in Terminal or Idle. It seems to be an issue specific with VS Code.

**Version of VS Code:**
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Your operating system:**
MacOS Catalina v10.15.7

**List of extensions that you have installed:**
be5invis.vscode-custom-css
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
esbenp.prettier-vscode
gerane.Theme-Dark-Dracula
humao.rest-client
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-wsl
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
naumovs.color-highlight
ritwickdey.LiveServer
samuelcolvin.jinjahtml
Shan.code-settings-sync
Tyriar.shell-launcher
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons

**Reproducible steps (1... 2... 3...) that cause the issue:**
```
import os

CLIENT_SECRET = str(os.getenv("CLIENT_SECRET"))
CLIENT_ID = str(os.getenv("CLIENT_ID"))
SECRET_KEY = str(os.getenv("SECRET_KEY"))

print(CLIENT_SECRET, CLIENT_ID, SECRET_KEY)
```

**What you expected to see, versus what you actually saw:**
All three of the variables above returned the value None, even though there are valid environmental variables that contain long token strings. These values return correctly in Terminal and Idle.

**Comment by ianbroad** [comment]
Added additional information to my original post.

**Comment by meganrogge** [comment]
is this problem still happening?
