### ISSUE TITLE
Debug Console Linker automatically decodes link

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#112032]
Issue Type: <b>Bug</b>

When debugging code and a link has a URI encode clinking the link in the debug console will auto decode the URL. This causes issues as some APIs expect the paramaters to be URI encoded. When just logging links to the terminal it doesn't do that.

Try the following code:
```
const url = "https://www.test.com/?params=CountryCode%3DUSA%26Name%3Dlramos15";
console.log(url);
```
Steps to reproduce
1. Set a breakpoint on `console.log(url);`
2. Start debugging
3. Type url into the debug console
4. Ctrl+click and navigate to the URL. It will automatically decode to `https://www.test.com/?params=CountryCode=USA&Name=lramos15`, with no way to disable this. Runnig the code normally and following the url in the terminal doesn't do this.

VS Code version: Code - Insiders 1.52.0-insider (5e350b1b79675cecdff224eb00f7bf62ae8789fc, 2020-12-04T10:15:27.849Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.42GB free)|
|Process Argv|C:\\Users\\ramosl\\Desktop\\Fall 2020 - Hw 8 --crash-reporter-id 6835f0a3-d9c6-4053-812a-2c4e35492724|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by isidorn** [comment]
This is a fair request.
Code pointer https://github.com/microsoft/vscode/blob/cf8ed37206e161a30151defa4fc9ea58c32335bc/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L36

PR's to fix this are welcome.

**Comment by grubdragon** [comment]
I'd like to work on this issue! Where do I start?

**Comment by isidorn** [comment]
I put a code pointer...

**Comment by chenjigeng** [comment]
@isidorn Do you think terminal's behavior is correct or debug's behavior is correct.

**Comment by chenjigeng** [comment]
I think the reason is uri.parse

![image](https://user-images.githubusercontent.com/14784326/101527499-0c26a100-39c9-11eb-8ab1-9c3a572b4fb5.png)

**Comment by lramos15** [comment]
The correct behavior to me would be not to decode the URI. If I wanted the URI decoded I could do `URI.Parse` within my code or the equivalent of that in whatever language I chose.

**Comment by chenjigeng** [comment]
I agree with you @lramos15

**Comment by chenjigeng** [comment]
I think we can just get rid of URI.parse. I tried it locally, and it work.  But what are the potential problems without URI.parse

**Comment by chenjigeng** [comment]
Even if we don't use uri.parse here, when we call this.openerService.open(url), the url inside openerService will also be uri.parse, which means that the url shown in the pop-up box is actually decode

![image](https://user-images.githubusercontent.com/14784326/101530331-bb18ac00-39cc-11eb-83ac-b6d61f59bfd1.png)

**Comment by lramos15** [comment]
> Even if we don't use uri.parse here, when we call this.openerService.open(url), the url inside openerService will also be uri.parse, which means that the url shown in the pop-up box is actually decode
> 
> ![image](https://user-images.githubusercontent.com/14784326/101530331-bb18ac00-39cc-11eb-83ac-b6d61f59bfd1.png)

You would definitely want to make sure the URL inside the opener matches the URL the user is being served. So I assume you would want to update it in both places @chenjigeng. I can't think of any consequences of not parsing the URI unless they're using the parsed URI for something besides serving it to the user.

**Comment by isidorn** [comment]
@chenjigeng once you have something feel free to provide a PR and @lramos15 and me can review. Thanks!

**Comment by chenjigeng** [comment]
I think there are a couple of issues here

1.  Ctrl+click and navigate to the URL. And the Url should not  be decode
2. OpenerService should not decode the Url
3. debug console can't open local file, try the following code
```
const url = "file://Users/something/Desktop/whitelist.png";
console.log(url);
```

This PR is mainly to fix 1 and 3 

The first problem is actually very easy to solve, just need to pass in the original link 

The third question I did was to refer to terminal's current solution: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L191

**Comment by isidorn** [comment]
Adding bug label so we get this verified.

**Comment by connor4312** [comment]
It looks like the url opener service still decodes the url, so Logan's initial issue is still present.

**Comment by lramos15** [comment]
> It looks like the url opener service still decodes the url, so Logan's initial issue is still present.

So the url you see in the browser is decoded? The reason we didn't touch the opener service is we felt it touched too much code. Although I thought that would only affect the modal shown

**Comment by connor4312** [comment]
Oh, I was hitting the "copy" button to verify the url, but open works. In this scenario, hitting the copy button would result in a broken (decoded) url, we should probably adjust that as well.

**Comment by isidorn** [comment]
@lramos15 can you please look into this if you have time? If not feel free to push to next milestone and assign back to me. Thanks

**Comment by isidorn** [comment]
@connor4312 thanks for cathcing that case. After discussion with @lramos15 we decided to push this part of the fix out of the endgame since it would require a riskier change.

**Comment by isidorn** [comment]
@lramos15 thanks a lot for fixing this. Assingin to February milestone so we get this verified..

**Comment by connor4312** [comment]
[This](https://github.com/microsoft/vscode/issues/112032#issuecomment-768609178) still seems to be happening

**Comment by isidorn** [comment]
Will not fix it last game of endgame, pushing out to backlog

**Comment by lramos15** [comment]
I'll investigate this for debt week.  I just tested it with my fix commit and it worked so I'll have to bisect and see what broke it nothing pops out to me at the moment.

**Comment by isidorn** [comment]
@lramos15 unassigning myself, feel free to assign back to me if help is needed.
