### ISSUE TITLE
GitHub Enterprise support for the GitHub auth provider

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#112043]
Issue Type: <b>Feature Request</b>

Currently we don't support signing into GitHub Enterprise accounts using the auth provider. The auth provider makes calls to get user information that point specifically to github.com.

Either the `getSessions` API needs a way to provide the enterprise server endpoint, or the auth provider extension should automatically do this detection and let the user choose when performing sign in. The auth provider needs to store what endpoint tokens are associated with and use this instead of always going to github.com. It should also indicate this in the UI.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 18.7.0

**Comment by jasonwilliams** [comment]
> Currently we don't support signing into GitHub Enterprise accounts using the auth provider. The auth provider makes calls to get user information that point specifically to github.com.

@RMacfarlane looks like @kabel’s PR (linked to this issue) fixes that.
