### ISSUE TITLE
Suggest for elements of remote.extensionKind would be helpful

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#112030]
From @alexr00 

After typing the following in settings, it would be nice to put my cursor inside the { and trigger suggest to get suggestions for the extension ID based on the extensions I currently have installed.

**Comment by sandy081** [comment]
Suggestions with installed extensions is shown as follows:

![image](https://user-images.githubusercontent.com/10746682/101380184-7d752f80-38b5-11eb-8799-584e9e30cd90.png)

@alexr00 Please confirm if this is what your recommendation is too?

**Comment by alexr00** [comment]
That is exactly what I was thinking. Thanks!
