### ISSUE TITLE
Disable info boxes but keep color picker enabled.

### ISSUE THREAD

**Issue by mikael1000** [microsoft/vscode#112029]
**For example:** when coding javascript and every time I write `.addEventListener` I get a big info box about it that covers code and I really don't need that info box again and agin. So I tried a lot of settings to disable that. What I found working was:

`"editor.hover.enabled": false`

But it also disables the **color picker** that I get when I hover over a written color (I still have the preview-box that shows the color). I would like to be able to disable the info-boxes but still have the color picker on hover.

**Comment by alexdima** [comment]
FYI @rebornix
