### ISSUE TITLE
[VS Code-Insiders] The copied port address is 1 greater than the forwarded port address after disconnecting and reconnecting to a codespace

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#112016]
From https://github.com/microsoft/vssaas-planning/issues/1293

**Comment by alexr00** [comment]
@wachaudh I think that is is a bug in Codespaces.

When VS Code calls the tunnel factory that the resolver provides, it requests the "correct" port number. What the tunnel factory does with this is up to the tunnel factory.

The also appears to be coming from Codespaces custom port restoring code.

**Comment by srivatsn** [comment]
I believe @plisy has a PR out for a fix in the codespaces extension for this.

**Comment by plisy** [comment]
Yes I do.
