### ISSUE TITLE
"Retry as Sudo" does not honor NOPASSWD

### ISSUE THREAD

**Issue by juagargi** [microsoft/vscode#112091]
- VSCode Version:
```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-54-generic
```
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open VSCode.
2. Open a file that only root can write to.
3. Save. A dialog is displayed, stating: "Failed to save 'file': Insufficient permissions. Select 'Retry as Sudo' to retry as superuser.
4. Press "Retry as Sudo..."
5. A password dialog shows up, regardless of the `NOPASSWD` setting in sudoers.

Does this issue occur when all extensions are disabled?: Yes

Other (maybe helpful) checks:
- `sudo -k; sudo -n echo aa` does not ask for password.
- The password is asked every time saving is attempted.
- I've checked #93699 but the URL mentioned [1] doesn't actually provide any solution for this.
- The file `/etc/sudoers.d/99-user` contains only this line: `user ALL=(ALL) NOPASSWD:ALL`
- The file `/etc/apt/sources.list.d/vscode.list` contains only this line: `deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main`

[1] https://github.com/jorangreef/sudo-prompt/issues/58

**Comment by bpasero** [comment]
Please report here: https://github.com/jorangreef/sudo-prompt
