### ISSUE TITLE
Node repl: consider to only show suggestions after first name segment/'.'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11200]
When stopped in the following program at `<<<` then `request` is not suggested
```js
const http = require("http");
const port = 3000;

const requestHandler = function(request, response)  {
  response.end('hello);    <<<<<<
};

const server = http.createServer(requestHandler);

server.listen(port, function(err) {
  if (err) {
    return console.log('something bad happened', err);
  }
  console.log('server is listening on ' + port);
});
```
![image](https://cloud.githubusercontent.com/assets/172399/18088836/1aa6b34a-6ebd-11e6-83ec-311a26720770.png)

Intellisense works fine after entering `request`:
![image](https://cloud.githubusercontent.com/assets/172399/18088869/44c4deae-6ebd-11e6-98cc-aa6aed722551.png)

To reduce the number of false suggested positives I suggest that suggestions are only shown after the first segment of an expression, e.g, on the first do.

**Comment by weinand** [comment]
I've improved the suggestions for the first segment. All scopes (including parameters) are now available.
Dup of https://github.com/Microsoft/vscode/issues/11186
