### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues #68044

### ISSUE THREAD

**Issue by andrewufrank** [microsoft/vscode#112024]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-13-amd64

Steps to Reproduce:

1. start vscode (with ansible vscode extension installed
2. debug message appears

Does this issue occur when all extensions are disabled?:  no

this has been reported and closed (as duplicate) but obviously not fixed as 
DeprecationWarning: Buffer() is deprecated due to security and usability issues #68044

**Comment by sandy081** [comment]
Seems coming from the extension. Can you please check if you see this message if you disable all extensions?
If this message is coming from the extension, then please file the issue against the extension.
