### ISSUE TITLE
Debug opens a new integrated terminal for each Python session

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#112055]
> I see this
> 
> ![image](https://user-images.githubusercontent.com/323878/101414944-de900980-389b-11eb-9417-b590e06eede8.png)

```json
{
	"name": "Python: Current File",
	"type": "python",
	"request": "launch",
	"program": "${file}",
	"console": "integratedTerminal"
}
```

_Originally posted by @roblourens in https://github.com/microsoft/vscode/issues/82662#issuecomment-740229893_

I was not able to repro this on OSX or Windows. But what rob was seeing is that it consistently open a new terminal on each start, as if the process for the previous terminals is still running

**Comment by jakubnavratil** [comment]
I found old implementation:
This was asked here microsoft/vscode#10940
And implemented here microsoft/vscode@50e91ea

**Comment by jakubnavratil** [comment]
Some observation based on discussion here: https://github.com/microsoft/vscode/issues/82662
I'm running Windows 10.
Integrated terminal using CMD or PowerShell works fine and reuses window.

This problem appears while using Git Bash - version 2.29.1.1
`"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"`

**Comment by nar3nd3r** [comment]
I was able to reproduce this on macOS (10.15.7).

**Comment by ggirard07** [comment]
Getting same issue on Windows while running with Remote extension in a linux based container (using bash).
Launch config is
```json
{
    "name": "My Python Script",
    "type": "python",
    "request": "launch",
    "program": "${workspaceFolder}/some_path/my_script.py",
    "console": "integratedTerminal",
    "env": {...}
}
```

**Comment by connor4312** [comment]
This will be fixed in tomorrow's [Insiders](https://code.visualstudio.com/insiders/) build

**Comment by connor4312** [comment]
@roblourens please verify this since you were able to repo 🙂
