### ISSUE TITLE
Debug launch progress does not stop when launching using integrated terminal

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11206]
#Testing #11091

OS: OSX

Steps to Reproduce:

1. Clone [VS Code Smoke Test](https://github.com/Microsoft/vscode-smoketest-express) application
2. Create a Node debug launch to run the application
3. Use `integratedTerminal` as console in the launch
4. Start the launch

Expected: Progress should stop
Observed: Progress keeps running as if launching is in progress

![aug-30-2016 15-00-10](https://cloud.githubusercontent.com/assets/10746682/18089919/7f5bba7e-6ec2-11e6-944c-dfacd7e3cf08.gif)

**Comment by weinand** [comment]
@sandy081 and you do not see this behaviour if using the two other console options?

**Comment by sandy081** [comment]
@weinand Yes, I see this behavior only with integrated terminal option

**Comment by rebornix** [comment]
@weinand I suppose the fix can only be verified with our next release of Insider, right?

**Comment by weinand** [comment]
@rebornix yes, correct.
