### ISSUE TITLE
Filter by filename or filepath in Git Changes Panel

### ISSUE THREAD

**Issue by robsonrosa** [Microsoft/vscode#11208]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro

I think would be nice if we could filter changes in the Git Changes Panel. I work in a project that often we have a lot of changes in files that I don't want to commit right now. So I need to carefully choose files in Git Panel to adding them to stage. Here an example:

![git-panel](https://cloud.githubusercontent.com/assets/2868031/18089926/a0f586da-6e98-11e6-8f21-ff2d0bd65abf.png)

I'd like to commit only gulp tasks in a project with 19 files changes. With an input text to input a filepath to filter (typing 'gulp' in my case - or just '*.ts'), I'll be able to select only the files that I want. Would be great for me.

**Comment by Deilan** [comment]
Related: #3918 #23775.

**Comment by joaomoreno** [comment]
#3918
