### ISSUE TITLE
console error when using live server

### ISSUE THREAD

**Issue by Fentec199** [microsoft/vscode#112173]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I am getting this error in the console when I open html with live server.  It is not present if I open  html file directly.
Uncaught (in promise) TypeError: this.engines is not iterable
    at E.updateSocialMedia (content.js:48)
    at new E (content.js:48)
    at Function.start (content.js:48)
    at Function.main (content.js:48)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.69GB free)|
|Process Argv|--crash-reporter-id 4d015ffb-d380-49d8-8337-988d3168ea27|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Where do you see this error? In VS Code editor or on your web page?

If in VS Code is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by Fentec199** [comment]
The message is in the console on the web page

**Comment by BRAiNCHiLD95** [comment]
**_content.js is the standard name used for browser-extension code (aka content scripts)._** 
So, I doubt this has anything to do with VSCode or even your application code.

Check your Browser Extensions. The culprit is probably in there. 

PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.

**Comment by IllusionMH** [comment]
/question

Because this error is outside of VS Code editor and VS Code doesn't serve files itself this issue doesn't belong to this repo.

As mentioned above - there is high chance that this is just browser extension.

**Comment by abhitchauhan** [comment]
@BRAiNCHiLD95  I am facing the same error in the console and I too have an McAfee Advisor extension added in chrome can you please lead me that how you fixed it, so that i can follow the same steps and resolve it.

**Comment by BRAiNCHiLD95** [comment]
> @BRAiNCHiLD95 I am facing the same error in the console and I too have an McAfee Advisor extension added in chrome can you please lead me that how you fixed it, so that i can follow the same steps and resolve it.

Get rid of the extension buddy. That's the fix. Just use a good adblocker and be aware of what you're doing on the internet. You don't need McAfee filtering your internet (in my opinion).

Steps to Remove -

Open Chrome -> click on the Settings (hamburger) button -> Extensions -> look for McAfee Crapvisor ->click on Remove

**Comment by nirajsharma99** [comment]
> @Fentec199 Check currently installed Browser Extensions. The culprit is probably in there.
> 
> **_content.js is the standard name used for browser-extension code (aka content scripts)._**
> 
> So, I doubt this has anything to do with VSCode or even your application code.
> 
> PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.

thankyou!! in my case McAfee was the one causing problem.

**Comment by gs7vik** [comment]
yah even I had the same problem, thanks a lot.

**Comment by gs7vik** [comment]
> @Fentec199 Check currently installed Browser Extensions. The culprit is probably in there.
> 
> **_content.js is the standard name used for browser-extension code (aka content scripts)._**
> 
> So, I doubt this has anything to do with VSCode or even your application code.
> 
> PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.

yah even I had the same problem, thanks a lot.
By the way how did you come to know that extension was the culprit?

**Comment by BRAiNCHiLD95** [comment]
> yah even I had the same problem, thanks a lot.
> By the way how did you come to know that extension was the culprit?

Like I said in my original response -

> content.js is the standard name used for browser-extension code (aka content scripts).

I've built a chrome extension myself, and that was the first thing that stood out to me from the error. 
Secondly, the updateSocialMedia() function is NOT a part of our application. So we started to look at extensions, and we had quite a few unnecessary ones in there - we got rid of around 6 of them.. and then only 3 were left (Google Maps API, Docs Offline, McAfee).
Deleting all 6 didn't fix the issue (but they weren't required - so deleting was definitely necessary in our case). We tried disabling McAfee first - and that worked.
So, I think some experience + trying to read and understand the error is how I figured it out.

**Comment by BRAiNCHiLD95** [comment]
> yah even I had the same problem, thanks a lot.
> By the way how did you come to know that extension was the culprit?

Like I said in my original response -

> content.js is the standard name used for browser-extension code (aka content scripts).

I've built a chrome extension myself, and that was the first thing that stood out to me from the error. 

Secondly, the updateSocialMedia() function is NOT a part of our application.

Thirdly, my personal machine didn't have the problem - which meant it was just one machine and one browser.

Then we started to look at extensions, and we had quite a few unnecessary ones in there - we got rid of around 6 of them.. and then only 3 were left (Google Maps API, Docs Offline, McAfee).
Deleting all 6 didn't fix the issue (but they weren't required - so deleting was definitely necessary in our case).
and so we tried disabling McAfee - and that worked.

So, I think some experience + trying to read and understand the error + some good ol' trial and error is how I figured it out.

Immediately after I figured it out, I decided to google the error message to see if there's anything from McAfee regarding the problem - found this issue.

I'm glad I could help so many of you! :)

**Comment by LoiHuiXin** [comment]
I also facing this issues currently,

Thanks for everyone to point out the causes ! 

I have removed the McAfee and the issues was solved!

**Comment by boloroyun** [comment]
extension called McAfee Advisor was the cause. i fixed mine

**Comment by Akshay6890** [comment]
> @Fentec199 Check currently installed Browser Extensions. The culprit is probably in there.
> 
> **_content.js is the standard name used for browser-extension code (aka content scripts)._**
> 
> So, I doubt this has anything to do with VSCode or even your application code.
> 
> PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.

Man you hit the bull's eye, I did the same and the problem was solved, you are a savior! 🤗

**Comment by Akshay6890** [comment]
> > @Fentec199 Check currently installed Browser Extensions. The culprit is probably in there.
> > **_content.js is the standard name used for browser-extension code (aka content scripts)._**
> > So, I doubt this has anything to do with VSCode or even your application code.
> > PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.
> 
> yah even I had the same problem, thanks a lot.
> By the way how did you come to know that extension was the culprit?

Even I have the same doubt!

**Comment by BRAiNCHiLD95** [comment]
> > > @Fentec199 Check currently installed Browser Extensions. The culprit is probably in there.
> > > **_content.js is the standard name used for browser-extension code (aka content scripts)._**
> > > So, I doubt this has anything to do with VSCode or even your application code.
> > > PS: I just fixed this issue for one of our devs a few minutes ago, an extension called McAfee Advisor was the cause.
> > 
> > 
> > yah even I had the same problem, thanks a lot.
> > By the way how did you come to know that extension was the culprit?
> 
> Even I have the same doubt!

Glad I could help, please check my response from 10 days ago. I explained how I figured it out.
