### ISSUE TITLE
"Find in folder, files to include", when folder name has comma, this feature won't find any result.

### ISSUE THREAD

**Issue by KaimingTao** [microsoft/vscode#112116]
- VSCode Version: 1.51.1 also latest inside version
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. create a folder with comma in the name
2. copy some text files into the folder
3. write click the folder, choose "Find in folder"
4. in the "files to include" box, make sure it contain the folder name.
5. in the keyword box, search by some texts exist in copied text files
6. compare with grep result in the same folder.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is basically https://github.com/microsoft/vscode/issues/82415
