### ISSUE TITLE
Allow to await `vscode.diff`'s diff computation

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#112183]
- VSCode Version: 1.51.1
- OS Version: WIndows 10

I have a VSCode Treeview extension that is so far working fine. I offer a right click on a TreeItem node to perform a vscode.diff before proceeding with an update function. 
I call a function:
`await diffCompare(originalFile, developmentFile);

const dj = "x";`

and the function itself:

`export async function diffCompare(original: string, current: string) {

await vscode.commands.executeCommand("vscode.diff", vscode.Uri.file(original), vscode.Uri.file(current));

return;
}`

I am finding that it is dropping straight to the breakpoint that I set instead of remaining in the diff till it is complete and the files closed. 
I am sure, I must be doing something wrong here but searching doesn't offer up any solutions.
Any suggestions as to what might be necessary would be appreciated.

I am told that this is not doable without the means to provide an enhancement to provide a "WAIT" option to the vscode.diff.

Can this be put forward?

**Comment by davidkjackson54** [comment]
I have posted an enhancement to request that the WAIT option be made available as I am told this is not currently doable.

**Comment by eamodio** [comment]
It would be great if there was a way to support the equivalent of the `--wait` command line option for `vscode.diff` and/or `window.showTextDocument`. Especially since without an "open editors" api there is really no way for extensions to do this themselves.

**Comment by bpasero** [comment]
I tried this and for me the `await` only returns after the diff editor has opened:

![recording](https://user-images.githubusercontent.com/900690/101878501-fadbc100-3b8f-11eb-9dd1-f9fe42addc33.gif)

So I am not sure what this issue asks about.

**Comment by davidkjackson54** [comment]
The problem is that the diff files are displayed side by side  but the code continues without waiting for the diff to complete and be  closed. 
 In my example, I offer a right click on a VSCode tree item to perform a diff.  I want the user to complete the diff changes and then close the diff window and only then for the code to continue and complete its follow on  function.

**Comment by bpasero** [comment]
@davidbailey00 yeah the actual diff computation is happening in the background in a worker (iirc), we do return before the diff is computed.

**Comment by davidbailey00** [comment]
@bpasero I think you got the wrong David :D

**Comment by davidkjackson54** [comment]
Right and that is the problem.  We request to have the   WAIT option made available so that we can flow into another dependent process on completion of the diff.

**Comment by bpasero** [comment]
Sorry davidbailey00!

@davidkjackson54 ok thanks, marking as feature request then.

**Comment by davidkjackson54** [comment]
Do I need to 'vote' or as the author, is that taken as a +vote?

**Comment by eamodio** [comment]
@davidkjackson54 feel free to vote :)
