### ISSUE TITLE
No eslint configuration found

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11212]
Refs: #11100

1. Init a sample workspace with eslint
2. Delete the .eslintrc.js file
3. Notice error 'No ESLint conifguration found'
4. I would expect a more user friendly message - something that would point the user to re-initialize eslint in this repository

![screen shot 2016-08-30 at 15 18 45](https://cloud.githubusercontent.com/assets/1926584/18090462/21a795d0-6ec5-11e6-8040-6c8b0dfac4f7.png)

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode-eslint/issues/122
