### ISSUE TITLE
"eslint.nodePath" requires vscode restart

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11217]
Refs: #11100 

1. Simple workspace, with no eslint installed.
2. Open settings and set "eslint.nodePath" to some path where eslint is installed
3. Notice that this path is not picked up until vscode gets restarted

This is very confusing for the user since there is an action to 'Retry' and this action does not do anything. A real restart is required

**Comment by roblourens** [comment]
Agreed, when I change the setting value, the notification bar reappears, if I had closed it earlier. That really makes it look like it's reloading the extension when I change that setting, but it isn't.

**Comment by dbaeumer** [comment]
I will look into resending the setting.

**Comment by dbaeumer** [comment]
To verify this please use the attached version of eslint and side install it. 

[vscode-eslint-1.0.1.zip](https://github.com/Microsoft/vscode/files/447515/vscode-eslint-1.0.1.zip)

**Comment by dbaeumer** [comment]
@isidorn please verify.
