### ISSUE TITLE
Stop icon changes on hitting first breakpoint

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#11215]
- VSCode Version: 1.5.0 insiders
- OS Version: macOS

Steps to Reproduce:
- start extension host debugging
- set and hit a breakpoint
Observe: the stop icon changes from a red square to the crossed-plug icon.

Since the stop button really kills the extension host window, we should not use the 'disconnect' hover text and the crossed-plug icon but show the red square.

**Comment by isidorn** [comment]
Dup of #11163
