### ISSUE TITLE
eslint: init command

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11211]
Refs: #11100 

eslint could contribute the global workbench command: 'eslint: init' which would run the `eslint --init` in the integrated terminal. This would make the setup experience more user friendly.

fyi @egamma

**Comment by dbaeumer** [comment]
Discussed with @egamma and we decided to generate a .eslintrc.json file. Added a custom command to do so. Calling eslint --init fails if there is no package.json which is not very helpful or tire kickers.
