### ISSUE TITLE
Auto closing HTML tag with slash / does not work well when nested within the same tag name

### ISSUE THREAD

**Issue by jsgoupil** [microsoft/vscode#112114]
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z (3 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Write the following:
```
<ng-template>
    <td>
        <ng-template>
        Will Press only -> ENTER SmallerThan then /
    </td>
</ng-template>
```
2. Position your cursor after `then /`
3. Press `ENTER`, `<`, `/`

ACTUAL RESULT:
`</td>` gets written

EXPECTED RESULT:
`</ng-template>` should get written.

Note, that if I replace the first `ng-template` by another tag, like `<tr>`, this bug doesn't happen.

Does this issue occur when all extensions are disabled?: Yes

Attached video.
[● html.html - HBTI.ServiceTech.Web2.Client - Visual Studio Code 2020-12-08 14-45-48.mp4.zip](https://github.com/microsoft/vscode/files/5662473/html.html.-.HBTI.ServiceTech.Web2.Client.-.Visual.Studio.Code.2020-12-08.14-45-48.mp4.zip)

**Comment by aeschli** [comment]
That's what I get when I follow your instructions
![html-complete](https://user-images.githubusercontent.com/6461412/101606995-58430700-3a04-11eb-89fc-7753d5c9e52e.gif)

That's with the editor in HTML mode.

**Comment by jsgoupil** [comment]
That was a tricky bug...
I was able to repro what you did in the following:

1. Open a new file (by default, it is in HTML mode)
2. Paste the content you had
3. Position your cursor after then /
4. Press `ENTER`, `<`, then `/`

It "works"... until you do this:

5. Delete the content of the file, re-paste the original (or simply redo step 1 and 2)
6. Press `CTRL+N` to open another file
7. Go back to your original file
8. Repeat 3 and 4.

Somehow, it happens only when you the current file gets deactivated and re-activated. :scream:

**Comment by jsgoupil** [comment]
I offered a great repro step. This is still happening 1.54.1 :(

**Comment by aeschli** [comment]
Found the problem in the hrml language service. Fixed there, will be soon in VSCode.
