### ISSUE TITLE
OH 3.0 - setting.json setting stopped working.

### ISSUE THREAD

**Issue by Daniel100111** [microsoft/vscode#112181]
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.

openHAB 3.0.0
Build #2058

- OS Version: Windows 2000

Steps to Reproduce:

1. Config.json stopped working after upgrade. Unable to connect to openhab 3 to pull things. Sitemap also not available. 
2. Current config. 

{
    "openhab.host": "192.168.1.200",
    "openhab.port": 8080,
    "openhab.sitemapPreviewUI": "classicui",
    "workbench.iconTheme": "openhab",
    }

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you specify how it's related to VS Code editor itself.

If you are using extension - please report your problem in extension repo.
