### ISSUE TITLE
又crash了 怎么个回事? 怎么又crash了 一分钟内crash了两次

### ISSUE THREAD

**Issue by hualaikeji** [microsoft/vscode#112135]
Issue Type: <b>Bug</b>

又crash了 怎么个回事? 怎么又crash了 一分钟内crash了两次

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 19.6.0

**Comment by fyeeme** [comment]
looks that you're not using the latest vscode , you can try upgrade your vscode. then have a try.

**Comment by mjbvz** [comment]
Closing as not actionably without more information
