### ISSUE TITLE
No way to turn off automatic Intellisense popups.

### ISSUE THREAD

**Issue by rbtyod** [microsoft/vscode#112185]
I find automatic popups to be very distracting while writing code!
I have disabled automatic Quick Suggestions in settings.json and use Ctrl+Space whenever I DO want to see them.
But, there seems to be no way to keep Intellisense messages from automatically popping up without disabling them completely.
...Bob       rbtyod@gmail.com

**Comment by jrieken** [comment]
use these two settings: `editor.quickSuggestions` _and_ `editor.suggestOnTriggerCharacters`

**Comment by rbtyod** [comment]
jrieken, thank you so much. 
That's been driving me crazy.
...Bob

**Comment by rbtyod** [comment]
Johannes,Thank you so much.
That's been driving me crazy.
...Bob

**Comment by rbtyod** [comment]
Johannes,
Sorry to bother you again but I spoke too soon.
With the change you suggested, the popups do not, indeed, appear
automatically as I type BUT they DO appear automatically whenever my cursor
happens to land on some random function anywhere in my code.
Is there a way I can make that kind of popup behavior manually activated as
well?
...Bob

**Comment by gjsjohnmurray** [comment]
@rbtyod this feature is called a "hover". Try searching settings for that term. Maybe set `"editor.hover.enabled": false`
