### ISSUE TITLE
Version 1.51.1 not showing all ts errors in IDE (specifically TS7053)

### ISSUE THREAD

**Issue by andrewkfiedler** [microsoft/vscode#112175]
- VSCode Version: 1.51.1
- OS Version: Darwin x64 18.7.0
![Screen Shot 2020-12-09 at 12 47 07 PM](https://user-images.githubusercontent.com/11984853/101679571-c267a600-3a1c-11eb-859b-47063fae88cc.png)

Steps to Reproduce:

1.  Make a Record type
```
    type RecordKeyType = 'key1' | 'key2'
    const example = { 
        key1: () => {},
        key2: () => {}
    } as Record<RecordKeyType, () => void>
```
2.  Try to pull a value off of the record
```
   const blahKey = getKey() as RecordKeyType
   const valueFromRecord = example[blahKey]
```
3.  No complaints, and it sees valueFromRecord as the correct type in the IDE.
4.  Compiling with the same tsconfig file (no implicit any).  Error on line for valueFromRecord declaration:
```
TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'Record...
```

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur on the nightly?: Yes

From what I can tell from reading, I don't think the Record should even be allowed to be typed in such a way, is that correct?  Anyways, I was able to solve it by instead doing this:
```
   const valueFromRecord = example[blahKey as RecordKeyType]
```

To see the actual code involved:
https://github.com/codice/ddf-ui/pull/470/files#diff-4adaffbe6b5f7afb0441aee2c026c8db3ab942f165f6516167a905c6680abb3cR122
https://github.com/codice/ddf-ui/pull/470/files#diff-4adaffbe6b5f7afb0441aee2c026c8db3ab942f165f6516167a905c6680abb3cR211
```
     const pat = patterns[token as keyof typeof patterns]
```

It doesn't bother me too much having to do this, it's more that the IDE does not catch this.  I have to try and compile to see the failure.

**Comment by mjbvz** [comment]
Have you ensured that you are [using TS 4.1.2 in your workspace too](https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions)?

Can you share a minimal project that demonstrates the issue?

**Comment by andrewkfiedler** [comment]
I'll try and share one.  I tried using switching to the new version as well like in the link, but no dice.

**Comment by andrewkfiedler** [comment]
I gave this a go this morning: https://github.com/andrewkfiedler/typescript-issue-112175

I could not recreate it, so I'm thinking it actually is something to do with our build setup, likely an issue in ts-loader rather than typescript or vscode.  Thanks, I'll go ahead and close this for now!

**Comment by andrewkfiedler** [comment]
Finally tracked down the issue, which was ultimately on our end 🙃 

Our package json was pointing to a _different_ project's dependency (a parent folder) due to: 
https://github.com/andrewkfiedler/ddf-ui-1/blob/CQLtoFilterTreeSquash/ui-frontend/packages/catalog-ui-search/package.json#L11

Swapping that to point to the project's fixed everything right up.  😌
