### ISSUE TITLE
VSCode can not read data from file when debugging c++ code 

### ISSUE THREAD

**Issue by RiverShi** [microsoft/vscode#112165]
- VSCode Version:1.51
- OS Version:Windows 10 2004

Steps to Reproduce:

1. create a .cpp file
2.create a .txt with some data
3.use freopen or fopen, read data from the .txt file
4.debugging
5.the variables never change its value

Does this issue occur when all extensions are disabled?: Yes/No  didn't try

**Comment by weinand** [comment]
@RiverShi please provide more details and a screenshot for steps 4 and 5.

**Comment by mdsheraj123** [comment]
Hi,
I also face this issue. I can provide the screenshots. All settings are default.

![Step4](https://user-images.githubusercontent.com/20283488/103479338-0e76f200-4df3-11eb-8217-c1aa97b4efb0.png)
![Step5](https://user-images.githubusercontent.com/20283488/103479342-146cd300-4df3-11eb-9ebf-ca3d61e31ab6.png)
![ok16](https://user-images.githubusercontent.com/20283488/103479384-58f86e80-4df3-11eb-82b3-4e0c0a5954c9.png)

The value of T was supposed to be 5 (which it is under regular execution) but under debugging it is a random value 16.
I use
```
    #ifdef SHERAJ
        freopen("input.txt"  , "r", stdin);
    #endif
```
for competitive programming and VS Code on Mac debugger runs this perfectly fine. Please fix this.

**Comment by mdsheraj123** [comment]
I asked about it on stackoverflow too if that is helpful.
https://stackoverflow.com/questions/65550374/vs-code-on-windows-debugger-does-not-work-with-freopen
Can you please reopen this issue as it is very inconvenient for me to remove `freopen` and give manual input to the debugger every time.

**Comment by RiverShi** [comment]
> I asked about it on stackoverflow too if that is helpful.
> https://stackoverflow.com/questions/65550374/vs-code-on-windows-debugger-does-not-work-with-freopen
> Can you please reopen this issue as it is very inconvenient for me to remove `freopen` and give manual input to the debugger every 

> I asked about it on stackoverflow too if that is helpful.
> https://stackoverflow.com/questions/65550374/vs-code-on-windows-debugger-does-not-work-with-freopen
> Can you please reopen this issue as it is very inconvenient for me to remove `freopen` and give manual input to the debugger every time.

how to reopen ？I don't know？ is me？

**Comment by RiverShi** [comment]
> @RiverShi please provide more details and a screenshot for steps 4 and 5.

someone else supplied more information about this issue

**Comment by mdsheraj123** [comment]
As explained in the comments of `https://stackoverflow.com/questions/65550374/vs-code-on-windows-debugger-does-not-work-with-freopen` the fix is to change the `cwd` in launch.json to the directory of your input file.
I did not face this issue on Mac, so maybe `cwd` should be set properly by default so other users are not inconvenienced.
