### ISSUE TITLE
Markdown Inline Formats in Headings doesn't themed correctly

### ISSUE THREAD

**Issue by superyyrrzz** [Microsoft/vscode#1121]
In Markdown preview, inline formats in single backticks (`) seems small sized in heading. Headings of different sizes have this problem in common.
![capture](https://cloud.githubusercontent.com/assets/3831744/11680340/70fb35aa-9e92-11e5-8eb5-53e7aaf13c15.PNG)

**Comment by egamma** [comment]
@bpasero fyi

**Comment by bpasero** [comment]
Yes, this collides with our font-size rule for the code block which is not ideal. I am happy to accept PRs for making markdown CSS better. The CSS is defined in https://github.com/Microsoft/vscode/blob/master/src/vs/languages/markdown/common/markdown.css

**Comment by bpasero** [comment]
Still happens with our new markdown extension:

![image](https://cloud.githubusercontent.com/assets/900690/16124420/2bb31f9c-33ef-11e6-95f8-29a4eb84c5ee.png)
