### ISSUE TITLE
follow symbol in next split

### ISSUE THREAD

**Issue by djobet** [microsoft/vscode#112136]
Hello,

I'm quite new to vscode so might have missed it. I googled and stackoverflowed this question many time but did not find an exact match. By the way, very nice editor thanks !

If I ctrl-click on a symbol, it will open a new tab on my current split. I may have to manually move the editor to the split I want.
I'd like to have the possibility to either always follow a symbol to the next split (this is what I used in QtCreator), or to have a new shortcut to follow the symbol to the next split.

The closest I've seen is 
left click on the function/class, ctrl-t, ctrl-enter
The problem with this is that it does a search by name and sometime I would select a class name and end up with opening a function that happens to contain the class name.

With regards,

David

vscode 1.51.1
linux local Ubuntu 18.04.4 LTS
linux remote Ubuntu 16.04.6 LTS
list of extensions : c/c++ 1.1.3, clang-format 1.9.0, clangd 0.1.8, cmake 0.0.17, cmakeTools 1.5.3, gitlens 11.0.6, remote - SSH 0.61.0, Remote - SSH : editing configuration files : 0.62.0

**Comment by gjsjohnmurray** [comment]
The `editor.action.revealDefinitionAside` command does this. On Windows it is bound to the key chord <kbd>Ctrl+K</kbd>, <kbd>F12</kbd> by default, but you can customize this, even make it be what F12 does. I don't think you can yet bind Ctrl+click to this alternative command though.

**Comment by gjsjohnmurray** [comment]
For mouse customization FR see #3130

**Comment by djobet** [comment]
ctrl+K, F12 works for me thanks !
