### ISSUE TITLE
"**" prefix redundant in vscode files.exclude and search.exclude default?

### ISSUE THREAD

**Issue by studgeek** [microsoft/vscode#112167]
The "files.exclude" and "search.exclude" both point to [Basic Editing in Visual Studio Code](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) to explain glob patterns. There it states the following:

> If you enter example, that will match every folder and file named example in the workspace. If you enter ./example, that will match the folder example/ at the top level of your workspace.

But the defaults for both `files.exclude` and `search.exclude` prefix their entries with "**/". Is that prefix redundant or is the documentation incorrect?

```
	"files.exclude": {
		"**/.git": true,
		"**/.svn": true,
		"**/.hg": true,
		"**/CVS": true,
		"**/.DS_Store": true
	},

	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
		"**/*.code-search": true
	},
```

It's probably worth noting that, unlike the above, `files.watcherExclude`explicitly states it uses absolute paths and therefore does need the "**/" prefix.

> Configure glob patterns of file paths to exclude from file watching. Patterns must match on **absolute paths** (i.e. prefix with ** or the full path to match properly). Changing this setting requires a restart. When you experience Code consuming lots of CPU time on startup, you can exclude large folders to reduce the initial load.

**Comment by studgeek** [comment]
It's probably also worth mentioning that those instructions list ! for excluding, but that isn't actually supported in the settings - https://github.com/microsoft/vscode/issues/869.

**Comment by roblourens** [comment]
Search works differently than those settings. We automatically assume `**/.../**` in search for ease of use but settings are more precise
