### ISSUE TITLE
Setting cursorSurroundingLines to either 0 or 1 have same effect

### ISSUE THREAD

**Issue by pangteypiyush** [microsoft/vscode#112127]
- VSCode Version: 1.51.1
- OS Version: Windows10 1909

Expected behavior is to have no extra line below the cursor if `cursorSurroundingLines` is set to 0.

Steps to Reproduce:
1. Set `cursorSurroundingLines` to 0: 1 line always below the cursor while navigating down the line
2. Set `cursorSurroundingLines` to 1: 1 line always below the cursor while navigating down the line

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
It looks like the default was a value of 1 prior to the `cursorSurroundingLines` setting.  Perhaps that default value was never removed when the setting was added? Or intentionally kept, in which case the settings should be restricted to`1` or above?

**Comment by alexdima** [comment]
This is intentional. The minimum value for lines above is 0, while the minimum value for lines below is 1. This is due to the horizontal scrollbar, which makes it very difficult to work on the last line in the viewport.
