### ISSUE TITLE
auto complete 

### ISSUE THREAD

**Issue by jmejiamu** [microsoft/vscode#112105]
Issue Type: <b>Bug</b>

auto complete is not working and also  it is not recognizing extension(example es7-react-js-snippets|dsz|3.0.0), but it does in some projects.  I checked the auto complete tab and it is on, but still does not work. I am using javascript.  vscode version  1.51.1. 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.46GB free)|
|Process Argv|. --crash-reporter-id 6730a13d-475d-4333-9547-9b943436377a|
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-tailwindcss|bra|0.5.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
vscode-peacock|joh|3.9.1
vscode-docker|ms-|1.8.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.11.399280825
remote-wsl|ms-|0.51.4
vsliveshare|ms-|1.0.3303
color-highlight|nau|2.3.0
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|4.4.0
vscode-css-navigation|puc|1.10.1
LiveServer|rit|5.6.1
errorlens|use|3.2.4
vim|vsc|1.18.4
quokka-vscode|Wal|1.0.335
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details>
.

**Comment by mjbvz** [comment]
Please share steps to reproduce this. /needsMoreInfo

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
