### ISSUE TITLE
Configuration javascript.validate.enable not respected by typescript extension

### ISSUE THREAD

**Issue by chemzqm** [microsoft/vscode#112129]
- VSCode Version: Master
- OS Version: MacOS

Should be bug of  typescript-language-features https://github.com/microsoft/vscode/blob/aef539adfcae36d91eb2b8d1a11eeb3da0fc529c/extensions/typescript-language-features/src/tsServer/bufferSyncSupport.ts#L537

This line should exclude resources that `shouldValidate(buffer: SyncedBuffer)` return false

**Comment by mjbvz** [comment]
Please describe the user impact of this

**Comment by chemzqm** [comment]
When using `"javascript.validate.enable": false` configuration, it's possible to receive diagnostics of javascript files on background update event of tsserver from  https://github.com/Microsoft/vscode/blob/master/extensions/typescript-language-features/src/typescriptServiceClient.ts#L850

**Comment by mjbvz** [comment]
This is by design. Those settings only control if we show the errors or not. This lets us both use those errors internally and avoid having to making additional requests if you toggle `validate`
