### ISSUE TITLE
Unable to use shortcut to close panel when terminal is focused.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#112179]
VSCode: 1.50.1
OS: Kubuntu 20.04

I have a set of key mappings that allow me to use escape to close the bottom panel.

These keymappings work in all cases, except for when the terminal is in focus in the bottom panel. For example, if the Problems tab is the tab in focus in the bottom panel, hitting escape key will successfully close the terminal. If the terminal tab is selected, nothing will happen.

I have added the following lines to my user settings to make sure the command does not get eaten by the terminal...

```
 "terminal.integrated.commandsToSkipShell": [
        "workbench.action.closePanel"
   ],
```

Here are the relevant keyboard shortcuts...
```
    { "key": "escape", "command": "workbench.action.terminal.toggleTerminal", "when": "activePanel == 'workbench.panel.terminal'" },// this one doesn't work
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.terminal'" },//and this one doesnt work
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.markers'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.output'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.repl'" },
    { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'workbench.panel.comments'" },
```

**Comment by meganrogge** [comment]
Yes escape is a special key in the terminal, so when the terminal is focused, it receives the Escape key regardless of the commandsToSkipShell. I'd recommend using any other key-binding for closePanel if you want it to work in the terminal. You can test this theory by having focus in the terminal, using Ctrl Shift P to open the command pallette, typing in close panel and hitting enter. The terminal will close.

**Comment by usernamehw** [comment]
I've used command to check context keys **Developer: Inspect Context Keys** and the active panel is somehow `terminal` not `workbench.panel.terminal`, so the documentation is incorrect https://code.visualstudio.com/docs/getstarted/keybindings#_activefocused-view-or-panel-when-clause-context

Either the panel id was unintentionally changed or documentation was not updated (or it never worked, who knows).

**Comment by usernamehw** [comment]
@meganrogge Please, consider reopening this issue because of my previous comment: https://github.com/microsoft/vscode/issues/112179#issuecomment-742710734 - `activePanel` context key seems to be wrong when the terminal is focused.

**Comment by meganrogge** [comment]
@safield update: @sbatten has been able to do this with the following configuration:

```
"terminal.integrated.commandsToSkipShell": [
  "workbench.action.toggleSidebarVisibility",
  "actions.find",
  "workbench.action.closePanel"
],
"terminal.integrated.sendKeybindingsToShell": false
```
```
{
        "key": "escape",
        "command": "workbench.action.closePanel",
        "when": "activePanel != ''"
}
```
If that works for you, please close this issue.

**Comment by meganrogge** [comment]
making this doc change 

> I used command to check out context keys **Developer: Inspect Context Keys** and the active panel is somehow `terminal` not `workbench.panel.terminal`, so the documentation is incorrect https://code.visualstudio.com/docs/getstarted/keybindings#_activefocused-view-or-panel-when-clause-context
> 
> Either the panel id was unintentionally changed or documentation was not updated (or it never worked, who knows).
> 
> ```js
> { "key": "escape", "command": "workbench.action.closePanel", "when": "activePanel == 'terminal'" },// works
> ```
