### ISSUE TITLE
Slow TypeScript quick fixes are repeatedly triggered on cursor change and block other features

### ISSUE THREAD

**Issue by gluxon** [microsoft/vscode#112184]
- VSCode Version: 1.51.1 and recent develop commit a33e1d617
- OS Version: macOS 10.15.7

## Steps to Reproduce

1. Open a large TypeScript project.
  a. (I realize this step is vague and not easily doable. Hopefully more details below help.)
2. Intentionally write an invalid symbol that hasn't been defined yet.
3. Use keyboard arrow keys to put the cursor somewhere in the middle of the red squiggly underlining.
4. Observe (from logs) that the TypeScript `getCodeFixes` IPC call gets executed on every cursor change.

**Does this issue occur when all extensions are disabled?**: No, but the TypeScript extension is builtin and exhibits this issue.

The GIF below shows a `.ts` file from this repo alongside a `tail` of the `tsserver`'s log.

![Kapture 2020-12-09 at 16 37 59](https://user-images.githubusercontent.com/906558/101692767-ad037380-3a3e-11eb-8aa8-4df92abaf60c.gif)

## Details

This behavior looks intentional, and the handler responsible for this is defined here:
https://github.com/microsoft/vscode/blob/864e80dc480506dcdfef03ec58304c61c949f499/src/vs/editor/contrib/codeAction/codeActionModel.ts#L64-L68

In the video above, the `getCodeFixes` tsserver call finishes very quickly for this repo (`microsoft/vscode`).

**Unfortunately this same call takes 8-13 seconds on a proprietary monorepo I work on.** Because tsserver is synchronous, this frequently blocks other semantic editing features (like `completionInfo`) and results in an extremely slow editing experience. 8-13 seconds isn't very long, but as soon as users start typing something new this gets retriggered over and over again.

Another important detail is that `getCodeFixes` doesn't seem to be cached by VS Code or tsserver. It takes the same amount of time despite nothing changing in the editor buffer or on the file system. That's not an issue itself, but the repeated triggering seems strange.

## Questions

1. Is the VS Code `CodeActionTriggerType.Auto` action supposed to call tsserver's `getCodeFixes`? The results of `getCodeFixes` usually appears in the `Quick Fix...` menu, which isn't displayed on cursor changes.
2. If the answer to 1 is yes, could we get a VS Code setting to flag this behavior off? Users can still hover their mouse over the symbol and click on `Quick Fix...`.

Thanks in advance to anyone that looks into this. VS Code is awesome. 🙂

**Comment by mjbvz** [comment]
Yes, this is expected since `getCodeFixes` powers the `lightbulb` that shows users if fixes are available or not

If `getCodeFixes` is taking a long time, please file an issue against TypeScript so they can investigate

**Comment by gluxon** [comment]
> Yes, this is expected since getCodeFixes powers the lightbulb that shows users if fixes are available or not

Ah I missed that. Thanks for explaining.

> If getCodeFixes is taking a long time, please file an issue against TypeScript so they can investigate

Filed https://github.com/microsoft/TypeScript/issues/41909
