### ISSUE TITLE
Extend the diagnostics API to allow the diagnostic collections without of a URIs

### ISSUE THREAD

**Issue by denis-shienkov** [microsoft/vscode#112145]
Right now, the diagnostic API use the file URI to set the diagnostics array: https://code.visualstudio.com/api/references/vscode-api#DiagnosticCollection :

![изображение](https://user-images.githubusercontent.com/8415796/101525521-7b39d080-399c-11eb-90ca-6c8957806084.png)

But, it does not work for the messages comes from the linker (for some custom toolchains), because there are these messages does not contains the path to the file, e.g.:

```
Error: L6415E: Could not find a unique set of libraries compatible with this image.
```

```
*** WARNING L16: UNCALLED SEGMENT, IGNORED FOR OVERLAY PROCESS
    SEGMENT: ?PR?FOO?MAIN
```

```
?ASlink-Warning-Undefined Global '_putchar' referenced by module 'vprintf'
```

and so forth.

So, it would be good to allow to add these messages to the `problems` panel too.

**Comment by jrieken** [comment]
The common tactic is to add such errors the "config file" - what a config file is depends on toolchain and language, the rule of thumb is to place it as close as possible to where the fix should go.

**Comment by denis-shienkov** [comment]
@jrieken 

A common tactic is to show all errors comes from the assembler/compiler/linker on the problems panes.  
I have no idea about what you just said. That's are config files?

**Comment by sean-mcmanus** [comment]
@denis-shienkov Any config/build files you might have like CMakeLists.txt, makefiles, c_cpp_properties.json, etc.

If you're using gcc or clang for linking, the gcc problem matcher in the C/C++ extension could potentially be modified to show linker errors in the problems window. You could file an issue at https://github.com/Microsoft/vscode-cpptools/issues .

**Comment by denis-shienkov** [comment]
@sean-mcmanus ,

> Any config/build files you might have like CMakeLists.txt, makefiles, c_cpp_properties.json, etc.

I'm still don't understand, what about you say. What's relation between the reported 'linker errors` and the "config files"?

> If you're using gcc or clang for linking, the gcc problem matcher in the C/C++ extension could potentially be modified to 

As I said before, I'm talking about the custom toolchains (not GCC/Clang). I'm say e.g. about Keil, IAR toolchains, and so forth.

> You could file an issue at https://github.com/Microsoft/vscode-cpptools/issues .

What's relation of that `vscode-cpptools` project and the `Diagnostins` API?  Besides, I already reported it there as my first stage. But they advised me to create this issue here, because the `Diagnostics` API belongs to the VSCode API..

Let' me repeat again: **"It is impossible to use the Diagnostins API in case if the linker does not report an error containing the file path"**.

Because the method `collection.set(URI)` requires the URI as the first parameter. Using the `empty` Uri's (e.g. `' '`) becomes to the ugly situation, when the user clicked on the diagnostic message, and then the VSCode reports about that "it is impossible to open the file path `' '` ".

**Comment by sean-mcmanus** [comment]
There may not be a relationship between the config file and linker error, other than potentially linker flags or configuration options being present in those files, e.g. the "-lm" option might be specified as a command line option to link to the "m" library. The suggestion is just to use that file as a URI for the purposes of the diagnostics API.

Keil, IAR toolchains, etc. are based on gcc, so using the gcc problem matcher should work in general, from what I've seen.

vscode-cpptools doesn't implement the diagnostics API, but we provide the gcc problem matcher. I mentioned it in response to `So, it would be good to allow to add these messages to the problems panel too.`.

**Comment by denis-shienkov** [comment]
> The suggestion is just to use that file as a URI for the purposes of the diagnostics API.

No, this is a bad idea (it is a crutch), because in my case, all build errors come from the build system. The VSCode does know nothing about specific config files and etc, because the VSCode use only the information provided from the build system (I write the special extension to support this build system in VSCode).

> Keil, IAR toolchains, etc. are based on gcc, so using the gcc problem matcher should work in general, from what I've seen.

I'm sorry, but you are wrong.

> but we provide the gcc problem matcher.

But, this gcc matcher, anyway, use the Diagrostics API? Yes? 
Anyway, matcher require the `file`: 

```
    "problemMatchers": [
      {
        "name": "gcc",
        "source": "gcc",
        "owner": "cpptools",
        "fileLocation": [
          "autoDetect",
          "${workspaceFolder}"
        ],
        "pattern": {
          "regexp": "^(.*):(\\d+):(\\d+):\\s+(?:fatal\\s+)?(warning|error):\\s+(.*)$",
          "file": 1,
          "line": 2,
          "column": 3,
          "severity": 4,
          "message": 5
        }
      }
    ],
```

What happens, if the incoming message has not the file path ("file": 1) ?

**Comment by sean-mcmanus** [comment]
Ah, yeah, you're right -- problem matchers also require a file.
