### ISSUE TITLE
Add option to JS/TS path suggestion to complete the file extension instead of only the file name.

### ISSUE THREAD

**Issue by madcampos** [microsoft/vscode#112117]
When using the import path suggestion, completing the suggestion only adds the file name, not it's extension.

There would be nice to have an option to also add the extension. Some code styles enforce imports with explicit extensions and when using native imports in the browser it needs the extension to resolve to a static file.

In the screenshot below, the suggestions show the file names and also it's extensions.
![image](https://user-images.githubusercontent.com/609904/101552506-58ea8780-3989-11eb-8115-974b3b566886.png)

But when the suggestion is selected it only inserts the file name, not the extension.
![image](https://user-images.githubusercontent.com/609904/101552829-e7f79f80-3989-11eb-82d1-0cbe058519bc.png)

**Comment by mjbvz** [comment]
Try using the `JavaScript › Preferences: Import Module Specifier Ending` setting:

```json
"javascript.preferences.importModuleSpecifierEnding": "js"
```

**Comment by madcampos** [comment]
@mjbvz I tested it on a new editor without any extensions or settings.
The only setting changed was the one suggested. It still don't add the extension to the import.
