### ISSUE TITLE
Auto port forwarding notifies about the wrong port

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#112159]
From @bamurtaugh

Testing https://github.com/microsoft/vssaas-planning/issues/1724

I already started the client with `npm run start` in the terminal. My port was forwarded properly to 4200:

![image](https://user-images.githubusercontent.com/25310137/101555351-5c701580-396d-11eb-8945-f7445153049d.png)

I then start the server with `node server.js` in a new terminal. I'm notified about the same port 4200, although I can see in the terminal output my server is running on port 8080:

![image](https://user-images.githubusercontent.com/25310137/101555704-ffc12a80-396d-11eb-852a-2008e450e7a4.png)

However, when I go to the the Ports view, I see both ports appear to be forwarded properly:

![image](https://user-images.githubusercontent.com/25310137/101555716-08196580-396e-11eb-8ccd-aa8f32a47773.png)

**Comment by isidorn** [comment]
Works great. Adding verified label
