### ISSUE TITLE
not auto underlining errors in code

### ISSUE THREAD

**Issue by rahulshastryd** [microsoft/vscode#112197]
Issue Type: <b>Bug</b>

not auto underlining errors in code 

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.97GB free)|
|Process Argv|--crash-reporter-id 8ffe2760-c75f-4b08-a790-0bc12958b82f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
jupyter|don|1.1.6
code-runner|for|0.11.1
vscode-nuget-package-manager|jmr|1.1.6
csharp|ms-|1.23.7
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.411183155
cpptools|ms-|1.1.3

</details>

**Comment by sandy081** [comment]
/~need-more-info
