### ISSUE TITLE
Substitution issue in 1.52 release notes?

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#112170]
Issue Type: <b>Bug</b>

The hover tip says "Alt+Click" but the text itself is "Alt+unknown"

![image](https://user-images.githubusercontent.com/6726799/101666657-63b72200-3a46-11eb-8844-5268d4add456.png)

VS Code version: Code - Insiders 1.52.0-insider (6f933020e8dd4ea046eae2bcfc59a18edf2bc517, 2020-12-08T15:37:23.937Z)
OS version: Windows_NT x64 10.0.19042

**Comment by ornellaalt** [comment]
thanks @gjsjohnmurray! fixed.
