### ISSUE TITLE
Major Problem

### ISSUE THREAD

**Issue by EManLGI** [microsoft/vscode#112119]
Issue Type: <b>Bug</b>

The Correction System That Fills In The Function For You Seems To Be Broken, So Typing In Somthing Like: private float, Doesn't Work Because It Doesn't Auto Correct It To The Proper Line Of Code Like It Did In Older Versions. This Is A BIG, Big Problem, Because Most Of The Code I Write Relys On This Function, Functioning

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|21.95GB (16.18GB free)|
|Process Argv|C:\UNITY PROJECTS\FPS\Assets\playerMovment.cs --crash-reporter-id a72d7ae5-3793-4c1a-bdce-c7eebec606fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.7
vscode-icons|vsc|11.0.0

</details>

**Comment by mjbvz** [comment]
What language is the for?
