### ISSUE TITLE
Ubuntu uses the moniker Rubbish Bin not Trash

### ISSUE THREAD

**Issue by jaapie** [microsoft/vscode#112118]
- VSCode Version: 1.51.1
- OS Version: 20.04

Steps to Reproduce:

1. Delete a file from within VSCode while on Ubuntu
2. Observe that the word 'Trash' is used in the confirmation dialog box.
3. Realise you're on Ubuntu and it uses the moniker 'Rubbish Bin'.
4. Fume a bit and open an issue on Github.

Does this issue occur when all extensions are disabled?: Yes

Ideally VSCode should not use its own names for OS elements. They should be called whatever the OS called them. In this case, on Ubuntu, VSCode uses Trash where the OS uses Rubbish Bin. On macOS, which uses Trash, it should be called Trash.

If someone points me to the right files etc I am happy to attempt a fix for this. I suspect the easiest but probably not the best is to maintain a hash of OSes and assiciated trash names.

**Comment by isidorn** [comment]
@jaapie yeah makes sense. However it would be cool if all Linux disitrbuitons use the same moniker, then this would be easier.
Anyways, here's a code pointer https://github.com/microsoft/vscode/blob/c6f4565a20360272365db74b7c08a31826548acc/src/vs/workbench/contrib/files/browser/fileActions.ts#L123

You can do a full text search for "trash" inside the `src/vs/workbench/contrib/files` and see where it makes sense and where it does not.

**Comment by jaapie** [comment]
Thanks for the pointer. I may have some time over the Christmas period to try this out.
