### ISSUE TITLE
toggle comment line, switch current line state

### ISSUE THREAD

**Issue by RaptorX** [microsoft/vscode#112103]
When using the toggle line comment command I would like to be able to switch the current line status instead of simply commenting the line.

Take this example:

```
line 1
line 2
```
Ctrl + /
```
// line 1
// line 2
```

everything looks good but:
```
line 1
// line 2
```
Ctrl + /
```
// line 1
// // line 2
```

I would like it to behave as follows:
```
line 1
// line 2
```
Ctrl + /
```
// line 1
line 2
```

This is very useful in scripting languages to quickly test different versions of the code.

**Comment by chenjigeng** [comment]
I agree with you, and I often feel confused about this behavior

**Comment by ArturoDent** [comment]
I have made an extension to toggle line comments as you want, see [Toggle Comments](https://marketplace.visualstudio.com/items?itemName=ArturoDent.toggle-comments).

and more at https://stackoverflow.com/a/65334947/836330
