### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by magminor** [microsoft/vscode#112156]
Issue Type: <b>Feature Request</b>

Please move the main menu out of the title bar. It should be separate because in the title bar there is no enough space to grab for moving the window.

VS Code version: Code 1.51.1 (2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
Consider modifying the following settings: 

`window.menuBarVisibility`: use `hidden`, `toggle`, or `compact`

`window.titleBarStyle`: use `native`
