### ISSUE TITLE
Unexpected scopes when grammar is embedded in HTML grammar.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#112189]
**[TS and JS Grammar Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar) version:**  0.0.55 / latest

When embedding the grammar in another grammar (HTML) there is unexpected behavior. The scope of the `:` is odd. The same `onclick` handler in a js file does not have this problem.

**Code**

```ts
<input type="button" onclick="window.location.href='https://vismaya.us/"
```

![image](https://user-images.githubusercontent.com/38270282/101371428-05a20780-38ab-11eb-8dfb-62ca4cc36e0a.png)

Originally from @vismodo in https://github.com/microsoft/vscode/issues/111394

**Comment by mjbvz** [comment]
The string seems to be getting split into two parts: `'http:` and then `//vismaya`.

Not sure why this is happening and I haven't been able to repo it in a normal JS file yet

**Comment by mjbvz** [comment]
@alexr00 I believe this line may be to blame:

https://github.com/microsoft/vscode/blob/18bab626b9d54e836412b7a6aae620645da0422c/extensions%2Fhtml%2Fsyntaxes%2Fhtml.tmLanguage.json#L225

Specifically, the match rule: `([^\\n\"/]|/(?![/*]))+` seems  to stop parsing if `//` appears anywhere in the JS, even inside of a string

**Comment by alexr00** [comment]
Thanks @mjbvz for looking! Marking issue as upstream: https://github.com/textmate/html.tmbundle/issues/113
