### ISSUE TITLE
Emmet balance commands not working on html files with unclosed tag

### ISSUE THREAD

**Issue by Accudio** [microsoft/vscode#112150]
Issue Type: <b>Bug</b>

1. Open a file like:
```
<html>
  <body>
    <p>
      First part of file
    </p>
```
2. Place cursor at opening `<p>`
2. Open command palette
3. Run Emmet command; eg 'Emmet: Balance (Outward)'

This should highlight from the `<p>` to `</p>` inclusive. Currently does nothing with no error either appearing or in Developer Console.
After closing `<body>` and `<html>` functions as expected.

This occurs with all extensions disabled, and in the latest Insiders build.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (19.37GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by rzhao271** [comment]
Interesting use case.
I'll mark this as a duplicate of #99896 but keep this case in mind

**Comment by Accudio** [comment]
Although not a common practice within modern development, it's still an extremely common practice within WordPress theme development for example to open tags in a different file than you close them. 
It would be very useful to be able to still use emmet within those files.

**Comment by rzhao271** [comment]
I will un-duplicate this issue because there's a problem within the balancing algorithm itself, rather than just the HTML parser.

**Comment by rzhao271** [comment]
\closedWith 483bd40

**Comment by rzhao271** [comment]
Verifier:

1. Create an HTML file with the following contents
```html
<html>
  <body>
    <p>
      First part of file
    </p>
```

2. Place cursor on the word "First"
3. Run `Emmet: Balance (outward)` command twice. Verify range from `<p>` to `</p>` is selected.
4. Run `Emmet: Balance (inward)` command twice. Verify cursor is in same location as in step 2.
