### ISSUE TITLE
Window reload doesn't enable all extensions.

### ISSUE THREAD

**Issue by sdsubhajitdas** [microsoft/vscode#112153]
- VSCode Version: 1.51.1
- OS Version: Mac Os Catalina 10.15.7 

Steps to Reproduce:

1. First launch vscode by disabling all extensions using command `code --disable-extensions .` .
2. Then when the vscode window opens then it shows a UI button to reload the window and return to previous state.
![Screenshot 2020-12-09 at 6 52 09 PM](https://user-images.githubusercontent.com/20211573/101636059-c7464d00-3a50-11eb-804d-d1535d06e090.png)
3. After I reload nothing happens. None of the extensions are enabled.
4. Finally again close the vscode window and start using command `code .`. 
5. Now the extensions are all loaded up.

Is the UI button working right ? If I am not wrong it should reload the window with all the extensions enabled right ?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
I just tried and works for me on latest insiders (might have fixed recently) - can you please try insiders and let us know if you see the issue or not - https://code.visualstudio.com/insiders/
