### ISSUE TITLE
Can't open a terminal

### ISSUE THREAD

**Issue by nitti87** [microsoft/vscode#112174]
Issue Type: <b>Bug</b>

I can't open a terminal through `Terminal -> New Terminal` or through `ctrl+shift+ö`. 

VS Code version: Code - Insiders 1.52.0-insider (c6cb54153991e7e3686c51ccd8d85b626b9b1fe4, 2020-12-09T16:02:22.126Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (9.99GB free)|
|Process Argv|--crash-reporter-id cd7405a1-4997-42c2-abbd-a29c4b00bc6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.52.0
material-icon-theme|PKi|4.4.0
vscode-counter|uct|2.2.0

(1 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by nitti87** [comment]
![recording](https://user-images.githubusercontent.com/44554259/101701020-63d31400-3a7e-11eb-910d-d80e71a93e3d.gif)

I'm clicking on `New Terminal` twice

**Comment by meganrogge** [comment]
what happens if you drag up from the bottom of the window or press ctrl + J?

**Comment by meganrogge** [comment]
also, are there errors in the dev tools console? 

lastly, please follow these steps and report back:

Enabling trace logging
For some terminal issues it's useful to get trace logs, this can reveal at what point something is failing. Follow these steps to get the logs:

Close all VS Code windows
Launch VS Code from the terminal using code --log trace
At this point you should reproduce the terminal issue you're having
Run the command "Developer: Open Log File..." (F1 opened command palette) and select Window to get an editor containing the logs. Select the Remote Extension Host log file if you're diagnosing an issue in a remote workspace (SSH/WSL/Containers/Codespace).

**Comment by nitti87** [comment]
My bad. I moved the terminal  to the side and forgot about it. Sorry
