### ISSUE TITLE
visual studio code changes my volume

### ISSUE THREAD

**Issue by mattwebdev** [microsoft/vscode#112110]
Issue Type: <b>Bug</b>

have music playing, set master volume to 20%, open visual studio code, notice your volume changing to 50%.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.45GB free)|
|Process Argv|--crash-reporter-id 7d070f94-1cf3-43a7-a1a7-a3db4a18e4df|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by rzhao271** [comment]
Cannot reproduce with 1.52.1. Can you attach a clip of the problem occurring? Also, if you continue to close and reopen VS Code does the volume just keep going up?

I found what seems to be the opposite problem here, where Electron apps are sometimes quieter than non-Electron apps https://github.com/electron/electron/issues/15369
