### ISSUE TITLE
Terminal closes automatically with the msg: terminated with exit code 3221225477

### ISSUE THREAD

**Issue by Anirudh-JJW** [microsoft/vscode#112125]
- VSCode Version: 1.51.1 (user setup)
- OS Version: Windows_NT x64 10.0.18363
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
