### ISSUE TITLE
[json] Show default value from JSON schema in IntelliSense window

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#112140]
Currently when a JSON schema contains the `default` keyword, that information is not shown in the IntelliSense window. It would be nice to show that.

**Example of default not being shown (in the far-right window):**

![1](https://user-images.githubusercontent.com/30827238/101613782-757bd380-3a0c-11eb-9eca-0729b8d508ce.png)

**Example of the default being set when pressing <kbd>Enter</kbd> on the completion item:**

![2](https://user-images.githubusercontent.com/30827238/101613876-8cbac100-3a0c-11eb-8376-724d6a6f44cb.png)

Reason for this new, proposed logic is that when users write JSON schemas with defaults, they might want to show and use that default even if they do not set the property. AJV has the option `useDefaults` https://ajv.js.org/#assigning-defaults which means just this, that if a prop is missing that is still taken as a default. As such it would be nice to also show the `default` keyword for users in IntelliSense even if they do not chose to autocomplete a property.

Note that `default` thus has two meanings:
1. Default for when doing auto-complete in VS Code (by pressing <kbd>Enter</kbd>).
2. Default as documentation to the user (in how AJV's `useDefaults` works). I.e. that default will be used if the property is not set at all.

**Comment by thernstig** [comment]
@aeschli I assume this is not good enough to be be brought into the backlog anyway, even though it has not received 20 upvotes? I think it'd be a great usability feature to show the default.

**Comment by aeschli** [comment]
As you observed, JSON schemas are used in various ways and the `default` value can have different purposes. 

Wouldn't it be better to let the schema author add the relevant information for the hover to the documentation field? Appending the default value info could also be unwanted or a duplication of the information that's already there.

I would rather leave things as they are.

**Comment by thernstig** [comment]
With the risk of duplicating the info, I still think it would be preferred to show it. It would guide users into not writing the defaults in the description, which is error-prone. Users often forget to update descriptions along with if they update the defaults. It also gets rid of having to double-document it in description + with the `default` keyword. This would save all users time.

Are there valid reasons to document it in description as well?

**Comment by aeschli** [comment]
>  It would guide users into not writing the defaults in the description, which is error-prone.

But that's not clear from an generated string like`default: null`. Settings have a hierarchy, so if you are in workspace setting, not having the setting will mean the user setting is used, not necessarily `null`

Also what to do with defaults that are objects or arrays?

**Comment by thernstig** [comment]
In VS Code it has a hierarchy, that is true. Users use schemas for other purposes than the VS Code settings. But if you are talking about the hierarchy, that is equally true for writing defaults in the description. Hierarchy (cascading) is something a user has to be aware of as a quirk of VS Code, at least I feel like that.

I don't see the problem defaults with objects arrays. This is already shown right now when the options pop up. Example for array:

```json
"fieldPatterns": {
          "description": "Some description.",
          "type": "array",
          "default": [],
          "items": { "type": "string" },
          "examples": [["field1", "*version*"]]
        }
```

This shows:
![array](https://user-images.githubusercontent.com/30827238/106595738-49845680-6554-11eb-906f-78c63f11b305.png)
