### ISSUE TITLE
.eslintrc.js does not have suggestions

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11213]
Refs #11100

1. Simple repo, initiazlie eslint, .eslintrc.js gets created
2. Open .eslintrc.js and triggere intelli-sense -> no suggestions
3. As found while discussing with @dbaeumer the issue here is that this file is .js and not .json
4. I would expect suggestions to help me set this file up

**Comment by dbaeumer** [comment]
Might be hard to achieve since we need to tell the tsserver about a d.ts eslint file under the cover. On top of this we would need to maintain such a file.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#124
