### ISSUE TITLE
eslint github page does not have setup documentation 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11210]
Refs #11100

Our javascript docs page mentions how to setup eslint https://code.visualstudio.com/docs/languages/javascript
However the https://github.com/Microsoft/vscode-eslint has no mention on how to set this up.

I would copy the documentation from our docs page to the github page, especailly since it is a first google hit for 'vscode eslint extension' query.

fyi @egamma @dbaeumer

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-eslint#231
