### ISSUE TITLE
Command "Run NPM script in folder" from Explorer view doesn't work.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#112152]
Right click on a folder that contains a package.json with npm scripts.
Run the command "Run NPM script in folder"
🐛 Nothing happens.

**Comment by rzhao271** [comment]
I don't see the "Run NPM script in folder" option at all, when right-clicking on the extensions/emmet folder in the vscode repo. Is there an extension I need to install?

**Comment by dbaeumer** [comment]
@rzhao271 there is a setting to enable this `"npm.enableRunFromFolder": true`

Verfied.
