### ISSUE TITLE
Enable `**\*.integrationTest.js` integration tests on Windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112164]
They were disabled a few months ago apparently: https://github.com/microsoft/vscode/commit/46c2494cb08e55637e9f35d6aaa664a3d029b9f0#diff-4442c68839390bb5d662d7115d4c367b14f59b0aae0549d8994a430dbd3934bbL41

**Comment by mjbvz** [comment]
Whoops, this was a mistaken change made during testing that commit. Thanks for catching this @joaomoreno!

**Comment by bpasero** [comment]
They are still commented out, I do not understand the change to add `@REM`?

**Comment by bpasero** [comment]
Left hand side imho shows how they should be looking:

https://github.com/microsoft/vscode/commit/46c2494cb08e55637e9f35d6aaa664a3d029b9f0#diff-4442c68839390bb5d662d7115d4c367b14f59b0aae0549d8994a430dbd3934bbL41
