### ISSUE TITLE
Mouse right-click comment and uncomment code menu 

### ISSUE THREAD

**Issue by ebonat** [microsoft/vscode#112158]
I would like to have the following feature: Mouse right-click comment and uncomment code menu for a line and multiple lines.

Thank you,

Ernest

**Comment by ebonat** [comment]
i did not see any answer in (#81663) post. what is the plan for it?

**Comment by ebonat** [comment]
hello vs code community!

let's vote all for it. we're tired of many shortcuts’ keyboards in vs code already - LET'S ALL VOTE IN 2020! 

thank you all,

ernest

**Comment by Kpax7** [comment]
I was also looking for such a feature. Upvoted +1
