### ISSUE TITLE
vscode uses too much CPU when installing something from snap in terminal

### ISSUE THREAD

**Issue by sysnasri** [microsoft/vscode#112151]
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:

1.  In terminal install something from snap  for example "sudo snap install openstackclients --classic" 

Terminal tries to download the package in verboos mode and generate a lot of entries as shown in the picture.
![image](https://user-images.githubusercontent.com/73346319/101627328-71af7780-3a33-11eb-992b-11ae635358d0.png)

Does this issue occur when all extensions are disabled?:  I have not checked it yet. 

![image](https://user-images.githubusercontent.com/73346319/101627112-1aa9a280-3a33-11eb-90ec-fc985707f90a.png)

It uses a lot of CPU resources and it hangs and have to be killed through task manager.

**Comment by meganrogge** [comment]
does this happen with this specific example only or are there other ways you've seen to cause this?

**Comment by sysnasri** [comment]
> does this happen with this specific example only or are there other ways you've seen to cause this?

so far yes  I have seen this issue with snap packages. 
I have to use screen command to make it not generate lots of entries. 

screen sudo snap install openstackclients --classic

**Comment by meganrogge** [comment]
yeah I've seen other issues with snap

**Comment by sysnasri** [comment]
Do you know when it will be fixed?

**Comment by meganrogge** [comment]
@joaomoreno sorry for the late notice

**Comment by Tyriar** [comment]
I believe this is related to an issue where the canvas renderer is particularly slow in some hardware/OS configurations. We have since improved the fallback mechanism here, you could try tweaking the `terminal.integrated.gpuAcceleration` setting.
