### ISSUE TITLE
Eliminate the term "Preview" from js-debug

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#112139]
Currently VS Code does not seem to have a "standard or "final" Node.js debugger:

<img width="715" alt="2020-12-09_11-13-01" src="https://user-images.githubusercontent.com/1898161/101616749-0f914b00-3a10-11eb-8eb2-5e7cab5c0b30.png">

There is either a "legacy" debugger or a "preview" debugger.

I suggest to eliminate "preview" as soon as possible from Node.js, Chrome, and Extension Development.
And maybe we should consider to rename "legacy" to "node.js < 8.0".

Shouldn't we do this even for the November release?

**Comment by roblourens** [comment]
Do we still need to make the changes to the now-legacy debug adapters? Is there a plan yet for moving the debug adapter types to get rid of "pwa"?

**Comment by connor4312** [comment]
I plan to do the type-swap this month. We've been targeting early this year to remove the old debuggers from being built-in
