### ISSUE TITLE
Completion popup truncated

### ISSUE THREAD

**Issue by amcasey** [microsoft/vscode#112246]
- VSCode Version:

Version: 1.52.0-insider (user setup)
Commit: c6cb54153991e7e3686c51ccd8d85b626b9b1fe4
Date: 2020-12-09T16:02:22.126Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

When I invoke completion, only the first row of results is shown.  I can use the arrow keys to access the others.  For example, this completion invocation should show four rows:

![image](https://user-images.githubusercontent.com/10508071/101829710-489cee80-3ae8-11eb-9051-23b4f5dbc93f.png)

For this exact repro, I was [here](https://github.com/amcasey/TypeScript/blob/da98c004d496f6da8aee74e7ad39b2eda25cb9c3/src/compiler/checker.ts#L16889).

Steps to Reproduce:

1. Create a new TS file
```ts
enum E
{
    A,
    B,
    C,
}

const e = E.// Completion here
```
2. Invoke completion (ctrl-space) where indicated by the comment.

Expected: Three rows
Actual: One row

Does this issue occur when all extensions are disabled?: Yes

**Comment by amcasey** [comment]
Worth noting: I am using Remote Desktop to connect (full screen on one low-res (1080p) monitor) to the machine running VS Code.  I did try rebooting the machine.

**Comment by ArturoDent** [comment]
Do the suggestions in https://github.com/microsoft/vscode/issues/110971 fix this?

**Comment by amcasey** [comment]
Cool, I didn't know VS Code called these suggestions (or that the box was resizable).  Resetting the size worked.  Thanks!
