### ISSUE TITLE
Canvas element support for JavaScript.

### ISSUE THREAD

**Issue by BrownCoatJustice** [microsoft/vscode#112208]
### Canvas Support

The  feature I would like is more support for the canvas element. I am a student and I use VS Code for my projects recently my projects were based around the canvas element although VS Code is known for its impressive JS functionalitie, right after mentioning the context `var ctx = canvas.getContext(2d);` of the canvas it stops giving me IntelliSense and doesn't bother canvas based errors.

 **Keeping in mind that this is a feature request, _please add more canvas support_.**

**Comment by mjbvz** [comment]
What doesn't work? Please share a code example that demonstrates the issue

**Comment by BrownCoatJustice** [comment]
> What doesn't work? Please share a code example that demonstrates the issue
This is just a feature request as mentioned

A screenshot of the reduced IntelliSense after declaring canvas
![image](https://user-images.githubusercontent.com/70653261/101918783-c8fa4700-3bef-11eb-97a1-98d9228177a0.png)
![image](https://user-images.githubusercontent.com/70653261/101918798-ce579180-3bef-11eb-8541-29404b58402b.png)

AS you can see usually it completes the whole syntax for me...But now it justs displays the text and once enter is pressed only the thing I had written (i.e. if ) will be displayed. I don't know if this is a IntelliSense bug or system error I would like it to be looked at.

**Comment by mjbvz** [comment]
Instead of copying `fabric.js` into your project, try installing it through `npm` and importing it that way. 

Also try setting up a [jsconfig](https://code.visualstudio.com/docs/languages/jsconfig) for your project
