### ISSUE TITLE
Theme color support for OUTPUT Panel foreground text

### ISSUE THREAD

**Issue by mkanet** [microsoft/vscode#112252]
Currently, the OUTPUT panel's text is determined by `editor.foreground`  color value.  `editor.foreground` is shared with several other items in VSCode; limiting flexibility in creating awesome themes.

**Please add the ability to explicitly set the OUTPUT panel foreground text color when creating themes**

![OutputPanelForegroundTextColor](https://user-images.githubusercontent.com/811008/101843021-2dd57480-3afe-11eb-823a-eaca737ec92a.png)

**Comment by sandy081** [comment]
@aeschli Assigning to you as it is themes related. Please let me know if I have to do something in `output`.

**Comment by aeschli** [comment]
@sandy081 Each component is responsible for its own colors, so its better if this is owned by you.

That said, given that the output view uses the editor, it might be difficult to implement the request as all editors share the same colors.

**Comment by mkanet** [comment]
Just a note that it shouldn't be presumed that all VSCode themes use the same background color for both the editor and panel.  Some themes can have a dark editor background; while the panel has a light background (or visa-versa).

This enhancement would allow more flexibility for hybrid themes like below.  In fact, this concept is already quite common in MS Visual Studio.
![Screenshot](https://user-images.githubusercontent.com/811008/101934532-9110e680-3b92-11eb-90f4-3065e3595946.png)

**Comment by gmccullo** [comment]
+1 on doing this. It's pretty frustrating when you're working on a color theme and have to deal with these hard-to-control knock-on effects.

**Comment by janhrach** [comment]
I vote for doing this too. I have the same problem like @atjbramley. Pretty annoying.
