### ISSUE TITLE
Flickering red underlines in code with errors

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#11229]
It appears that vscode temporarily removes error highlighting while the file is being edited, then puts the highlighting back when it gets information from the language server.
This means that any code with errors will flicker while the user types and errors are recomputed.

This is especially a problem for `noUnusedLocals` and `noUnusedParameters` errors, which by their nature can't be immediately fixed, if you are in the middle of writing a function and haven't needed to use some locals yet.

To reproduce:

    mkdir repro; cd repro
    code-insiders .

Make a `tsconfig.json` of:

    {
        "compilerOptions": {
            "noUnusedLocals": true,
            "noUnusedParameters": true
        }
    }

Then open `a.ts` and type out (don't paste):

    function f(a: number) {
        const b = 1;
        const c = 2;
        const d = 3;
        const e = 4;
        const f = 5;
    }

You'll notice that the red underlines under `a` through `f` flicker while you type.
This is hard to see for this example, but much more noticable for a large project, where updating errors takes longer (increasing flicker time).

As a side note, we are drawing attention to unused locals that aren't really an error until you've finished writing the function that would use them. A good solution to that would be another issue, but eliminating flickering would greatly reduce the distraction.

**Comment by dbaeumer** [comment]
@andy-ms there must be more to it since a language server doesn't clear errors when you type. We recompute the errors and then do a minimal adoption for the underlines.

**Comment by dbaeumer** [comment]
I can see the flickering as well. We see if we broke something ?

**Comment by dbaeumer** [comment]
There is something strange. The tsserver reports to independent set of problems.
