### ISSUE TITLE
Option to automatically close the task's terminal when the task is done

### ISSUE THREAD

**Issue by maximedupre** [microsoft/vscode#112230]
1. Debug with a pre launch task
2. Task has successfully completed
3. Task terminal window is closed/destroyed automatically

Something to the effect of:

        {
            "label": "npm: knex:migrate",
            "problemMatcher": [],
            "script": "knex:migrate",
            "type": "npm",
            "closeWhenDone": true
        },

Seems like none of the presentation options currently allow me to do this.

My intention is to cleanup task windows automatically and stop accumulating them for a more organized workflow.

**Comment by maximedupre** [comment]
@vscode-triage-bot Not duplicates :D

**Comment by alexr00** [comment]
Given the current language we have when a task is complete, `close` seems like the best name:
![image](https://user-images.githubusercontent.com/38270282/118270556-856a7880-b4c0-11eb-9810-f25bcd65254f.png)

**Comment by alexr00** [comment]
To verify:
1. F5 in your clone of this repo.
2. Verify that the terminal that runs the "Ensure Prelaunch Dependencies" task closes when the task is done.
