### ISSUE TITLE
Ctrl+shift+f opens search editor instead of search tab

### ISSUE THREAD

**Issue by Trismegistos84** [microsoft/vscode#112210]
I wish that I could change VSC behaviour in such manner that when I click ctrl+shift+f search editor is opened "files to include" filled with path selected in project browser. Currently search tab is opened instead of search editor.

**Comment by JacksonKearl** [comment]
You can bind ctrl+shift+f to `Open new Search Editor` in your keybindings.json or by using `Preferences: Open Keyboard Shortcuts`. Does that help?

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/issues/112588
