### ISSUE TITLE
Breakpoint stop work

### ISSUE THREAD

**Issue by Duldris** [microsoft/vscode#112288]
- VSCode Version: 1.52.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. press f9 on php project
2. nothing happen

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by oleevier** [comment]
For me also adding breakpoint doesnt work anymore , i cannot select a line to add breakpoint , i mean it is not adding anymore :(
even i use key or point line by mouse

**Comment by Duldris** [comment]
it's the same, debug doesn't work even with all the tricks.
to fix i download last release and all restart to work.

before install stop auto-update ;-)

**Comment by MatthieuScarset** [comment]
Same here.... I was debugging my PHP app... and had the bad idea to upgrade VSCode to latest release.

Pouf. Breakpoints don't work anymore. 

Terrible...

**Comment by evertoncsilva** [comment]
Same as @MatthieuScarset  here, debug was working perfectly fine until I decided to upgrade

**Comment by Duldris** [comment]
waiting bugfix can be fix downgrade to previous version:

https://code.visualstudio.com/updates/v1_51

**Comment by isidorn** [comment]
I am suspecting you are using a PHP debug extension by @felixfbecker 
This is an extension issue which I reported 1 month ago https://github.com/felixfbecker/vscode-php-debug/issues/424

Please comment on that issue in order to get it fixed. Thank you

**Comment by Duldris** [comment]
change extension like this post, work fine

https://github.com/felixfbecker/vscode-php-debug/issues/424#issuecomment-727932756

**Comment by jakubmisek** [comment]
This issue is related to the extension you use for debugging. Try a different one, i.e. https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode (paid) which should work out of the box.

**Comment by weinand** [comment]
As a workaround, you can use this setting to enable breakpoints everywhere:

<img width="974" alt="2020-12-11_23-16-18" src="https://user-images.githubusercontent.com/1898161/101960127-03231300-3c07-11eb-9854-98cdb42cfcd3.png">

**Comment by MatthieuScarset** [comment]
@jakubmisek so your proposed solution is to switch to a paid extension? Nop but thank you anyway.

@weinand solution works like a charm! thank you :+1:

**Comment by jakubmisek** [comment]
@MatthieuScarset I proposed switching to a different extension that properly registers itself as a debug engine for PHP files. You shouldn't need any workaround for this. Anyways, if it's working and it's free, that's fine as well.

**Comment by weinand** [comment]
The latest stable VS Code (1.52.1) has a workaround for the missing adoption of the removed API.
