### ISSUE TITLE
SourceControl Not Pushing to remote in Remote-WSL

### ISSUE THREAD

**Issue by robcee** [microsoft/vscode#112232]
Issue Type: <b>Bug</b>

Unable to push to remote repository (github) using built-in Source Control or GitLens extension.

Connected to Remote-WSL environment running Ubuntu 20.04 in WSL2.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.75GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+UbuntuFocal/home/rob/Projects/Nightpuck/iQPuckWeb --remote=wsl+UbuntuFocal --crash-reporter-id 6abfd936-139b-4c30-9d8d-b1561c28b8d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: UbuntuFocal|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|25.01GB (22.80GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
antd-snippets|ban|1.2.0
vscode-icontheme-nomo-dark|be5|1.3.6
node-snippets|chr|1.3.2
vscode-firefox-debug|fir|2.9.1
dotenv|mik|1.0.1
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.11
html5-boilerplate|sid|1.1.1
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
vscode-npm-script|eg2|0.3.13
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.411183155

</details>

**Comment by bamurtaugh** [comment]
Closing in favor of https://github.com/microsoft/vscode-remote-release/issues/4170 (if I've misunderstood and these are actually two separate issues, please just let me know). Thank you!
