### ISSUE TITLE
[yaml] add space to surrounding pairs

### ISSUE THREAD

**Issue by jvanderaa** [microsoft/vscode#112227]
When working with YAML files (specifically usually for Ansible), I often will double click on a text entry, then type `"{{ ` which will erase the text name. The space is habit from `"{{` which then autopopulates `}}"` - completely awesome. So the process I have to go through now is to highlight the text, add `"{{`, arrow, space, ctrl-arrow, space that could be simplified. The space in between the braces and the variable name is the best practice on Ansible. It is part of the default ansible-lint rules as well.

**Comment by aeschli** [comment]
Can you add a small code sample? What is the before and after state? What key is `arrow` in your description?

**Comment by jvanderaa** [comment]
```
- name: Debug a var
  debug:
    msg: var_to_debug


- name: Debug after adding Jinja2 Formatting with Ansible best practice
  debug:
    msg: "{{ var_to_debug }}"
```

**Comment by jvanderaa** [comment]
If you highlight the `var_to_debug` and then press `"` it will add the quotes around the whole thing. Then you enter `{{` it will continue to add the closing items as well. The next step is to add the space between the braces and the var name. This is where VS Code then erases and enters a space instead of adding a space in a similar fashion.

**Comment by aeschli** [comment]
Ah, I see, you want surround the selected word with a space.

That doesn't fit well in the surrounding pairs feature which is single character base. Adding space to the surrounding pairs would solve your request but interfere with normal editing and add an inconsistency with other languages. I'm therefore closing the issue as we don't want to go that way.

However, there are multiple extensions that help with surrounding. Search for `surround` in the market place.
