### ISSUE TITLE
Installed Extensions is not shown

### ISSUE THREAD

**Issue by vsquare-code** [microsoft/vscode#112265]
Install extension is not shown in the extensions area. A progress blue bar is moving from left to right but there is no response for a long period of time.

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
- Help -> Toggle Developer Tools -> Console
- Help -> Toggle Developer Tools -> Network (check for any network failed requests)
- View -> Command Pallette... -> Toggle Shared Process -> Console
- View -> Open View… -> Log (Shared)
- View -> Open View… -> Log (Window)

**Comment by vsquare-code** [comment]
Hi Sandeep,
Thanks for the quick response.
By following the steps mentioned, here is the output from the logs.


1. Help -> Toggle Developer Tools -> Console

ERR Object has been destroyed: TypeError: Object has been destroyed
    at WebContents._.send (electron/js2c/browser_init.js:185:2149)
    at IpcMainImpl.<anonymous> (C:\Users\vishnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:562:646)
2. Help -> Toggle Developer Tools -> Network (check for any network failed requests)

3. View -> Command Pallette... -> Toggle Shared Process -> Console[2020-12-11 13:21:54.558] [renderer3] [error] Object has been destroyed: TypeError: Object has been destroyed    at WebContents._.send (electron/js2c/browser_init.js:185:2149)    at IpcMainImpl.<anonymous> (C:\Users\vishnu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-main\main.js:562:646)


4. View -> Open View… -> Log (Shared)
This option not available in the list

5. View -> Open View… -> Log (Window)



Regards,Vishnu
    On Friday, December 11, 2020, 1:21:23 PM GMT+5:30, Sandeep Somavarapu <notifications@github.com> wrote:  
 
 

   
   - Help -> Toggle Developer Tools -> Console
   - Help -> Toggle Developer Tools -> Network (check for any network failed requests)
   - View -> Command Pallette... -> Toggle Shared Process -> Console
   - View -> Open View… -> Log (Shared)
   - View -> Open View… -> Log (Window)

**Comment by sandy081** [comment]
> 4. View -> Open View… -> Log (Shared)
This option not available in the list

Broken shared process

**Comment by joaomoreno** [comment]
Is the issue resolved if you restart your machine?

**Comment by vsquare-code** [comment]
> 
> 
> Is the issue resolved if you restart your machine?

The next day after reporting (I guess) the problem resolved automatically, But I was clueless at that time. I raised the issue because I couldn't install extension. I was thinking about is there any automatic updates applied.

Now when I checked the version numbers, an update was applied. Here is the details:

## Latest:
> Version: 1.52.0 (user setup)
> Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
> Date: 2020-12-10T22:45:11.850Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.18363

## Reported:
> Version: 1.51.1 (user setup)
> Commit: e5a624b
> Date: 2020-11-10T23:34:32.027Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.18363

Thanks.

**Comment by joaomoreno** [comment]
Got it. Let's close this for now. Let me know if it comes back.
