### ISSUE TITLE
Rename input odd in high contrast theme

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11226]
Testing https://github.com/Microsoft/vscode/issues/11130

When in high contrast theme, the rename input box shows a border that is off by 1.

**Comment by sandy081** [comment]
@bpasero I still see text inside rename box is overlapping with the border. Is this a new issue?
<img width="430" alt="screen shot 2016-09-01 at 16 18 30" src="https://cloud.githubusercontent.com/assets/10746682/18170737/be739788-705f-11e6-85e8-3775f4f07970.png">
