### ISSUE TITLE
Can not save workspace settings

### ISSUE THREAD

**Issue by xuziqii** [microsoft/vscode#112260]
I open a folder by double click, it will create a .vscode folder has a file named setting.json
```
{
  "editor.detectIndentation": false,
  "editor.tabSize": 4,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true
}
```

The default setting is not suitable so I edit and save to
```
{
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": false
}
```
But when I reopen this folder, it will reset to its default setting, confusing...

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform and whether the problem also happens after you run the command to reload with all extensions disabled.

**Comment by xuziqii** [comment]
Thank you for you reply! I try to disable all extensions and settings.json won't reset anymore, thank you very much! You are so great! Best wishes!
