### ISSUE TITLE
Editor does not open when working offline

### ISSUE THREAD

**Issue by sanjayojha** [Microsoft/vscode#11228]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

I am trying to edit some php, html, css and js file on my local development machine, while working I had turnoff the internet. To my surprise it does not open when I double click on the icon from my desktop. I have also tried several other way to open it but no luck. 
I turn on the internet and it is working again. This is strange for me
Steps to Reproduce:

1. Turn off the internet
2. Open it

**Comment by bpasero** [comment]
Marking as duplicate.
