### ISSUE TITLE
Find/Search history is lost when (re)opening a workspace

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#112284]
I spent a while creating a fairly complex regex for searching for a pattern in a window. When I opened a new folder (window) I was expecting the find regex to still be available.  I thought maybe it remembered the history for each window which wouldn't have been so bad, but on reopening the original window again, the history is still missing.

This seems like a bug as Code seems to remember most things.

**Comment by roblourens** [comment]
It is remembered per-folder/workspace, and you can navigate history using the arrow keys in the input box

**Comment by Gruntfuggly** [comment]
But it's not. Steps to reproduce:

1. Open window. 
2. Enter search term.
3. Open another folder (same window)
4. Re-open the original folder
5. Search history is gone.

I can reproduce this in Ubuntu and Macos

**Comment by roblourens** [comment]
Sorry, are you talking about find in an editor "ctrl+F" or workspace search "ctrl+shift+F"?

I think the first is not currently saved, the second is.

**Comment by Gruntfuggly** [comment]
Yes - ctrl+f. 

That would explain it - are there any plans to save it?

**Comment by Edger** [comment]
> Sorry, are you talking about find in an editor "ctrl+F" or workspace search "ctrl+shift+F"?
> 
> I think the first is not currently saved, the second is.

I think search history should be saved even after we exit and reopen VSCode, no matter ctrl + f or ctrl + shit + f.

And it should be easily discoverable, so we can review search history in a list and select a previous search pattern to search a file again.

Becasue mostly when we use VSCode to read logs or other from a program, we always search for the same key word to find out problems.

This function should be essential, many other editors all implemete it, such as Notpad++, sublime text etc.
