### ISSUE TITLE
Exclude files in search always active - on/off button has no effect

### ISSUE THREAD

**Issue by gadeberg** [microsoft/vscode#112214]
Issue Type: <b>Bug</b>

The 'Use Exclude Settings and Ignore Files' button in search does not have any effect - 'files to exclude' (please also use capital letter for 'files' -> 'Files') is always active (e.g.: .venv, *.log, *.json).

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gadeberg** [comment]
Not the same issue as suggested by 'vscodebot' ;-)

**Comment by roblourens** [comment]
That button does not toggle off the text input, whatever is in there is always applied. Is that what you are talking about?

**Comment by roblourens** [comment]
It doesn't do that, it toggles of the exclude _settings_ and using the gitignore file. The text input is still applied
