### ISSUE TITLE
Debug console REPL disappears after collapsing and expanding debug console.

### ISSUE THREAD

**Issue by billie-spektor** [microsoft/vscode#112281]
- VSCode Version: 1.51.1
- OS Version: Windows 10 2004

Steps to Reproduce:

1. Move the debug console to the sidebar. The debug REPL is available right below the debug console.
2. Collapse the debug console with the chevron icon
3. Expand the debug console with the chevron icon
4. The debug REPL has disappeared. 

Expanding some other section (like watch), while the debug console is in the expanded state as well results in the reappearance of the REPL.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@billie-spektor thanks for this issue, I can reproduce and I acknowledge it.
I will probably prohibit debug console from being moved outside of the panel - since I think it needs the horizontal space.

Can you explain why you would like it in the sidebar? What is the use case

**Comment by billie-spektor** [comment]
Hi isidorn, thanks for checking! My setup is a dual monitor setup, with VSCode open on one screen, and the browser open on the second. In combination with the microsoft/vscode-edge-devtools extension, my VSCode screen looks like this:

![image](https://user-images.githubusercontent.com/69010225/101919177-8c682480-3bca-11eb-9038-496c82252009.png)

I think this provides a nice integrated experience for debugging HTML, CSS and JS and seeing your changes real-time reflected in the browser. 

I do like to keep all debugging related sections together, hence my preference for using the sidebar for the debug console (given that the other debugging sections are there by default). 

In terms of spacing, the only thing I miss here is some more default vertical spacing for the REPL (which I believe has been suggested before as a feature request but it was decided not to implement that). Regarding the horizontal spacing: I feel that there is enough horizontal spacing (the same as for the other debug sections, such as variables which may show similar information as the debug console).

My setup feels a bit cluttered if I move the debug console to the bottom. At the bottom, it takes up vertical space from the editor as well as from the edge-devtools extension. I also still keep the sidebar open for the other debug sections, so I would actually lose space if the debug console can't be moved to the sidebar anymore.

**Comment by isidorn** [comment]
Makes sense, thanks for the expanation. We will try to fix the issue this milestone.

**Comment by isidorn** [comment]
@billie-spektor can you please try this issue with the latest vscode insiders, it should be fixed.
Thanks!

**Comment by billie-spektor** [comment]
Perfect, thanks for fixing!

**Comment by isidorn** [comment]
Thanks, based on your comment adding verified label
