### ISSUE TITLE
Significantly delay of auto port forwarding under remote development

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#112297]
- VSCode Version: 1.52.0
- OS Version: macOS 11.0.1

Steps to Reproduce:

![Kapture 2020-12-11 at 23 19 11](https://user-images.githubusercontent.com/4662568/101921612-226e7000-3c08-11eb-893e-ffb307633f5b.gif)

In my case, I'm using shiny in R on a remote server via SSH.

1. Install R and shiny package
2. Install vscode-R extension and enable `r.sessionWatcher`
3. In VSCode, run `R: Create R terminal`
4. run `shiny::runExample("01_hello")`
5. A blank WebView is shown but it relies on port forwarding to work.

The WebVie port mapping is broken (https://github.com/microsoft/vscode/issues/102449) for quite a while, but auto port forwarding used to be a good walk-around since it seems to detect the ports that appear in the terminal output.

However, in  the recent release, I start to experience significant delay of  the auto port forwarding, which makes such WebViews no longer work.

Does this issue occur when all extensions are disabled?: Yes (except remote ssh)

**Comment by alexr00** [comment]
@renkun-ken the delay was added to work around some other issues. 

If your application uses the same port every time, you can use that ports view you have open to forward the port, then it will stay forwarded and restore when you reload the window to if you use the setting `remote.restoreForwardedPorts`.

**Comment by renkun-ken** [comment]
Thanks for the tips.

I switched to  `vscode.env.asExternalUri` in https://github.com/Ikuyadeu/vscode-R/pull/494 and this problem is no longer relevant. I guess I could close this for now.
