### ISSUE TITLE
"Fetching build tasks" never completes

### ISSUE THREAD

**Issue by birgersp** [microsoft/vscode#112207]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new folder, add `package.json` and `gulpfile.js` with text listed below.
2. Run `npm i` in the folder.
3. Hit Ctrl+Shift+B to select a build task.
4. Wait for eternity. (Or cancel, restart vscode)
5. Comment out the last line of `gulpfile.js`, the "gulp.watch" one.
6. Hit Ctrl+Shift+B to select a build task.
7. Notice how the list of possible build tasks appeared right away.

**package.json**
```
{
    "name": "helloworld",
    "devDependencies": {
        "gulp": "^4.0.2"
    }
}
```

**gulpfile.js**
```
var gulp = require("gulp");
var htmlGlob = ["src/index.html", "./favicon.ico"];
gulp.watch(htmlGlob, () => {}) // <-- This line makes "Fetching build tasks" never complete
```

Does this issue occur when all extensions are disabled?: Yes

Also tested this with VSCode Insiders, no joy.

**Comment by alexr00** [comment]
Can you try running `gulp --tasks-simple --no-color` in your folder? That is all we call to find gulp tasks, and I think that it is hanging. If that is the case, then this is a bug with gulp itself.

**Comment by birgersp** [comment]
I ran `gulp --tasks-simple --no-color`, it completed but showed no output. This makes sense, since I did not actually define any tasks.

I doubt that no output is the root cause here, because I noticed this problem first in a larger project that *has* several gulp tasks. For what it's worth, I did ask a friend of mine to test this on his system and he had the exact same problem.

**Comment by alexr00** [comment]
How about running `.\node_modules\.bin\gulp.cmd --tasks-simple --no-color`?

I tried your example, and ran both command lines, and I see both hang forever.

**Comment by birgersp** [comment]
Bingo! I'll take my problems to gulp instead. Thanks @alexr00

**Comment by birgersp** [comment]
If anyone else finds this I noticed that when testing this in a terminal, the error only occurs in powershell
