### ISSUE TITLE
Extension Host heap memory errors

### ISSUE THREAD

**Issue by docbill** [microsoft/vscode#112235]
Issue Type: <b>Bug</b>

This started happening today.   I have no idea why.  But most of my extensions are not working a result of this issue.

<--- Last few GCs --->

[6830:0x29af00000000]   161473 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.0 (3956.7) MB, 125.1 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 
[6830:0x29af00000000]   161605 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.1 (3956.7) MB, 128.0 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 
[6830:0x29af00000000]   161734 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.2 (3956.7) MB, 125.2 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Scavenger: semi-space copy Allocation failed - JavaScript heap out of memory

<--- Last few GCs --->

[6830:0x29af00000000]   161473 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.0 (3956.7) MB, 125.1 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 
[6830:0x29af00000000]   161605 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.1 (3956.7) MB, 128.0 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 
[6830:0x29af00000000]   161734 ms: Scavenge (reduce) 3949.9 (3956.7) -> 3949.2 (3956.7) MB, 125.2 / 0.0 ms  (average mu = 0.962, current mu = 0.935) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Scavenger: semi-space copy Allocation failed - JavaScript heap out of memory

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.9.11-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.11GB (22.88GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id aa90ae1a-1375-485b-ab63-68012773182d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
turbo-console-log|Cha|2.1.6
apex-debug|chu|1.0.3
apex-pmd|chu|0.5.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
xml|Dot|2.5.1
vscode-salesforce-toolkit|dro|1.2.2
gitlens|eam|11.0.6
vscode-html-css|ecm|1.1.1
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.5
vscode-lombok|Gab|1.0.1
vscode-javac|geo|0.2.37
gitlab-workflow|Git|3.7.0
vscode-auto-open-markdown-preview|hnw|0.0.4
sfdx-autoheader|Hug|0.7.1
forcecode|Joh|3.22.9
apex-code-runner|Jos|0.1.2
salesforce-vscode-custom-extension-pack|JOT|0.0.5
uncrustify|Lau|2.20.6
turbo-console-log-fork|let|1.0.0
vscode-docker|ms-|1.8.1
remote-containers|ms-|0.148.1
indent-rainbow|ode|7.4.0
vscode-jsp|pth|0.0.3
redhat-sfdc-bundle|red|0.0.1
java|red|0.72.0
vscode-xml|red|0.14.0
java-development-extensions-pack|ric|1.3.3
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|50.8.0
salesforcedx-vscode-apex|sal|50.8.0
salesforcedx-vscode-apex-debugger|sal|50.8.0
salesforcedx-vscode-apex-replay-debugger|sal|50.8.0
salesforcedx-vscode-core|sal|50.8.0
salesforcedx-vscode-lightning|sal|50.8.0
salesforcedx-vscode-lwc|sal|50.8.0
salesforcedx-vscode-visualforce|sal|50.8.0
sfdx-vs-test-class-generator|tea|1.0.0
sfdx-command-builder|Vig|3.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.26.0
vscode-spring-initializr|vsc|0.6.1
Java-extension-pack|wal|0.0.3
JavaScriptSnippets|xab|1.8.0
vscode-java-saber|You|0.1.1

</details>

**Comment by docbill** [comment]
I think I ran a fedora update about 24 hours ago.  I thought maybe it was a java engine update, but that does not appear to be the case.  A reboot did not help.  I don't know why javascript needs 4GiB of memory, and if that is the issue.  Or is it an issue that it normally is already close to full allocation.  If so how do I raise that?

**Comment by alexdima** [comment]
**NOTE**: **Be sure you are using a version of VS Code >= 1.52** 

It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by docbill** [comment]
Yeah.  The problem with uninstalling extensions is many have an order of install/activation requirement, which is almost impossible to track down...

I instead disabled all of them, then I went back to the salesforce documentation as what was required for sfdx to work.  That activated about half my extension.  I then renabled the other ones I was certain I needed. 

The problem has occurred a couple of times since, but is no longer consistently reproducible.  As near as I can tell it has something to do with a salesforce connecting timing out when using the extension that pulls down debugging information.

What gets me, is when it does happen about 30% of the time vscode will completely crash, and google chrome will crash with it.   I have no idea why the two would consistently crash together so consistently when they are completely different processes.  It is as if vscode in sharing node.js memory with google chrome.   Which means it probably depends on what web pages I have open in google chrome as well...

**Comment by docbill** [comment]
BTW.  I have 32 GiB ram, and during none of these crashes was I anywhere near to using it all.  So it is this smaller node.js limit that causing issues.

**Comment by yadutaf** [comment]
I'm experiencing a similar symptom starting today. Applying latest vscode updates did not solve the issue. Extension bisect concluded 'ms-toolsai.jupyter' was the likely cause.

Disabling "ms-python.python" or "ms-toolsai.jupyter" (which is a dependency of "ms-python.python") both solve the issue.

**Comment by yadutaf** [comment]
Hmm, this may actually be another issue. Rolling back "ms-python.python" to "v2020.11.371526539" from 25 days ago solved the issue but the new version is apparently only a couple of hours old while this bug is 5 days old :/

**Comment by alexdima** [comment]
@yadutaf It appears that you might run into a different problem. Please create an issue directly against hte python extension.

@docbill Here are a couple of extensions from your list that have been known to cause performance problems: 
* `bracket-pair-colorizer` (there is a v2 extension, why don't you please migrate to "Bracket Pair Colorizer 2"), 
* `auto-rename-tag` (this is now built-in functionality, you could enable it only in html using `"[html]": { "editor.linkedEditing": true }`)
