### ISSUE TITLE
Expose Panel State in the Extensions

### ISSUE THREAD

**Issue by vHanda** [microsoft/vscode#112283]
I would love to know if the panel is visible or not inside the extension code. I see that `activePanel` is exposed by https://github.com/microsoft/vscode/pull/49971 but I cannot seem to access it within the extension code.

**Comment by gjsjohnmurray** [comment]
Unless the `getContext` idea mentioned in #10471 get implemented I don't think extension code can test the value of contextkeys such as `activePanel`.

**Comment by sandy081** [comment]
May I know your use case for this?

**Comment by vHanda** [comment]
> May I know your use case for this?

I typed a response explaining why I needed it - and then realized this wouldn't solve my problem. So thank you. I now no longer need it. And found a workaround.

The original reason: I never use the vscode terminal cause it occupies too little screen space - I wanted a way to be able to toggle the terminal and maximize the panel, and when hiding the terminal, the panel's size should be restored. I was writing a custom `toggleTerminal` method which would show and hide the terminal and maximize / restore-panel-size on a particular hotkey.

The workaround - have a `startMaximizedTerminal` and `hideMaximizedTerminal` method instead. I don't know why I thought I needed this - https://github.com/Nytra/MaximizedTerminal/pull/4

**Comment by tamuratak** [comment]
We have a use case. When users select the tab of a LaTeX document, we want to reveal our command views in the sidebar if the sidebar is visible. 

https://github.com/James-Yu/LaTeX-Workshop/blob/9c5ab86e9b852eca37bc67a4620ebb4352ead920/src/main.ts#L208

**Comment by sandy081** [comment]
Thanks @vHanda. Closing this.

@tamuratak For your use case you can use view visibility context keys - `view.${viewId}.visible` and this is issue is related to panel.
