### ISSUE TITLE
Auto deleting the opened folder

### ISSUE THREAD

**Issue by SwastikBhattacharjee** [microsoft/vscode#112282]
Issue Type: <b>Bug</b>

Visual Studio Code is deleting the opened folder automatically with all its files
permanently without going to the recycle bin

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.71GB (0.60GB free)|
|Process Argv|--crash-reporter-id cd1381bf-8877-4925-8f7f-f9777e24beda|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|1.1.2
vscode-great-icons|emm|2.1.62
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
file-icons|fil|1.0.28
code-runner|for|0.11.1
rest-client|hum|0.24.4
r|Iku|1.6.2
csharp|ms-|1.23.7
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
typescript-javascript-grammar|ms-|0.0.55
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.2
ruby|reb|0.27.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-zipexplorer|sle|0.3.1
vscode-icons|vsc|11.0.0
vscode-ruby|win|0.27.0
commandlist|yam|1.0.3

(1 theme extensions excluded)

</details>

**Comment by SwastikBhattacharjee** [comment]
Visual Studio Code deletes files/folders permanently (file/folder will not appear in Recycle Bin), which is not appropriate as you could accidentally delete important files.

VS Code version: Code 1.51.1 (e5a624b, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

Steps to Reproduce:

Open VS Code
Open any folder and create some files and folders in it.
Close VS Code
Reopen VS Code
Delete some file/folder
Close VS Code
Again reopen VS code
Now look for it (The whole folder with all its files will be deleted permanently from the hard disk)

**Comment by SwastikBhattacharjee** [comment]
Issue Type: <b>Bug</b>

Visual Studio Code is deleting the opened folder automatically with all its files
permanently without going to the recycle bin

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.71GB (0.60GB free)|
|Process Argv|--crash-reporter-id cd1381bf-8877-4925-8f7f-f9777e24beda|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
vscode-html-css|ecm|1.1.2
vscode-great-icons|emm|2.1.62
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
file-icons|fil|1.0.28
code-runner|for|0.11.1
rest-client|hum|0.24.4
r|Iku|1.6.2
csharp|ms-|1.23.7
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
typescript-javascript-grammar|ms-|0.0.55
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.2
ruby|reb|0.27.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-zipexplorer|sle|0.3.1
vscode-icons|vsc|11.0.0
vscode-ruby|win|0.27.0
commandlist|yam|1.0.3

(1 theme extensions excluded)

</details>

**Comment by SwastikBhattacharjee** [comment]
Sorry to say, but its a bit urgent;
Please let me know how to resolve this issue

**Comment by gjsjohnmurray** [comment]
Does this also happen if you disable all of your extensions?

VS Code version 1.52 just released today. This includes a new command for performing an extension bisect, which may help you discover which extension (if any) is responsible for the problem you reported.

**Comment by SwastikBhattacharjee** [comment]
Thanks, it worked...
I just disabled all the extensions and tried, it worked.
Thanks a lot.
