### ISSUE TITLE
Theme icon modifiers should work everywhere

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#112298]
When using a icon in a label you can make it spinning by appending `~spin` to it.
https://code.visualstudio.com/api/references/icons-in-labels#animation

- `spin` is a ThemeIcon *modifier*.
- currently only `disabled` and `spin` are supported as modifiers
- currently spin only works in icon labels, but not in other places where ThemeIcons can be used (view icons, tree items..)

-> make modifiers work everywhere

**Comment by dsanders11** [comment]
@aeschli, @jrieken previously expressed reservations about supporting the spinning modifier:

> [Not sure if I am ready for spinning toolbar icons but adding colour to codicons contributed via `package.json`, inside markdown, and inside strings makes sense.](https://github.com/microsoft/vscode/issues/110521#issuecomment-726325809)

That's what actually drove the creation of the original PR (#110533).

Just want to make sure that this isn't a feature that's going to get yanked when @jrieken takes a look.

**Comment by jrieken** [comment]
Yeah, I still think that this is a pretty bad idea and I don't think an extension should be that powerful..

![Dec-14-2020 09-28-35](https://user-images.githubusercontent.com/1794099/102057800-c9acfc00-3dee-11eb-8f1c-589d79a92877.gif)

**Comment by aeschli** [comment]
@jrieken  What's the difference to using `~spin` in an icon label, e.g. on the status bar? In the end it's up to each extension to have good taste.

**Comment by jrieken** [comment]
Fair question but I think it's pushing the boundaries here. I'd say we should at least discuss this. Adding @joaomoreno who invented the spinning

**Comment by joaomoreno** [comment]
Yeah I don't think pushing this forward is productive at all.

**Comment by aeschli** [comment]
I would limit the spinning to a limited set of icons that are designed for. So far only  `sync` is documented.
Any other icons that are used with spinning?

**Comment by dsanders11** [comment]
The `loading` icon is used with spinning in the tree views when loading children of a collapsed item.

**Comment by aeschli** [comment]
Yes, you are right. tree uses `tree-item-loading` based on `loading`. Also the dialog uses that.

**Comment by aeschli** [comment]
Spinning is now limited to sync and loading.

**Comment by matangover** [comment]
Can we have `gear~spin` back? :)

**Comment by aeschli** [comment]
allowed `gear~spin`: 0795762a8f02a7588cc51b1ae41520b50fe081ff
