### ISSUE TITLE
error code: 5 and more

### ISSUE THREAD

**Issue by uino-lily** [microsoft/vscode#112202]
- VSCode Version: VSCodeSetup-x64-1.51.1
- OS Version: Windows 10 家庭中文版

All bugs occur after launch:
1. Unable to open a new terminal:
The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5).
![image](https://user-images.githubusercontent.com/70676443/101730627-59a02c80-3af5-11eb-8ed0-8ff74b5ee590.png)

2. Unable to open a new window:
The window has crashed(reason: 'launch-failed')
![image](https://user-images.githubusercontent.com/70676443/101730921-d501de00-3af5-11eb-8840-b29fc9dc617c.png)

3. Unable to open another folder:
No reaction at all. Have to CTRL + ALT + DEL to terminate it.

4.some other issues:
Before I delete all extensions, it also report bugs like:
"Couldn't start client JSON Language Server"
"Couldn't start ESlint Server"

Please help, it's urgent

Does this issue occur when all extensions are disabled?: Yes

**Comment by uino-lily** [comment]
Also, I have Uninstall/install VsCode 2 times today, reboot my computer at least 10 times.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by uino-lily** [comment]
Problems gone! ! 
I'll come back after reinstalling extensions. 
Thx!

**Comment by bpasero** [comment]
To clarify, it appeared again after you had installed extensions?

**Comment by uino-lily** [comment]
All extensions installed and no problem appears so far.
Thanks again.
btw, Is there any chance I can use the stable version again?

**Comment by bpasero** [comment]
Not sure, but the fact that it works in insiders but not stable seems to hint at a configuration problem. Does it also work if you run `code --user-data-dir <some empty folder>` and you try to install extensions there?

**Comment by uino-lily** [comment]
It appears installed:
![image](https://user-images.githubusercontent.com/70676443/101751079-cf62c300-3b0a-11eb-8370-7fe4b9a92e7e.png)
but has errors below:
![image](https://user-images.githubusercontent.com/70676443/101751043-c40f9780-3b0a-11eb-93c3-9d72cb5fcaf8.png)
and when I tried to see details of extension:
![image](https://user-images.githubusercontent.com/70676443/101751437-3aac9500-3b0b-11eb-8ee7-0d0c35bf5482.png)

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by uino-lily** [comment]
[1210/180801.084:ERROR:registration_protocol_win.cc(103)] CreateFile: ϵͳ�Ҳ���ָ�����ļ��� (0x2)
![image](https://user-images.githubusercontent.com/70676443/101757941-bcec8780-3b12-11eb-98fd-cf0aa6428d61.png)

**Comment by bpasero** [comment]
@deepak1556 does that ring a bell?

**Comment by deepak1556** [comment]
`registration_protocol_win.cc` log is fine, it's from crash reporter. The core issue is error code 5 (permission denied). Have you installed stable at the same location as insiders ?

**Comment by uino-lily** [comment]
D:\Microsoft VS Code
D:\Microsoft VS Code Insiders

**Comment by deepak1556** [comment]
can you run

```
> accesschk.exe -uqs Users D:\Microsoft VS Code
> accesschk.exe -uqs Users D:\Microsoft VS Code Insiders
```

and compare if the permissions match. You don't need to post the result here since it might contain sensitive information.

**Comment by uino-lily** [comment]
It's a long list... I don't know how to begin with

**Comment by uino-lily** [comment]
![image](https://user-images.githubusercontent.com/70676443/101852261-34b0c580-3b98-11eb-97e1-0c4d77deaeaa.png)
A lot of difference between the two, what are you looking for?

**Comment by CJMass** [comment]
I know this issue was closed, but I'm having the same issue when running Python scripts
