### ISSUE TITLE
Support that 'Open in New Command' uses the integrated terminal

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11221]
Today the Open in Command always uses an external terminal. 

![image](https://cloud.githubusercontent.com/assets/172399/18092986/ae2fcfb4-6ece-11e6-8c01-60433b43ccec.png)

Now that we have an internal terminal, I'd like that I can configure that this command uses the integrated terminal and opens an integrated terminal on the selected folder.

**Comment by Tyriar** [comment]
Duplicate #8132
