### ISSUE TITLE
extension tailwind css intelliSense works on stable build but not work on exploration build(darwin-arm64)

### ISSUE THREAD

**Issue by ah-yu** [microsoft/vscode#112225]
- VSCode Version: 1.53.0-exploration
- OS Version: Darwin arm64 20.1.0

Steps to Reproduce:

1. install extension tailwindcss intellisense on exploration build , the extension doesn't work
2. install extension tailwindcss intellisense on stable build, the extension works

**Comment by aeschli** [comment]
Please file this against the tailwindcss extension so they can analyze the problem first.
https://github.com/tailwindlabs/tailwindcss-intellisense/issues
