### ISSUE TITLE
Minimap interferes with Word Wrap

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode#112239]
Issue Type: <b>Bug</b>

When both Miniimap & Word Wrap are enabled, there's a horizontal scroll bar that shouldn't be there. Typing enough at the end of a line to cause wrapping first results in scrolling to the right, and when the line does wrap and indent, the scroll does not return completely to the left.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.30GB free)|
|Process Argv|--file-uri file:///c%3A/src/AF4JM.code-workspace --crash-reporter-id 75dbaf1b-c97f-4cbe-92b0-b4ac9d69a742|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-icalendar|af4|1.0.1
vscode-m3u|af4|1.0.0
vscode-caniuse|aga|0.5.0
rtf|ale|2.2.0
vscode-sqlite|ale|0.10.1
swagger-viewer|Arj|3.0.1
vscode-browser-preview|auc|0.6.7
armview|ben|0.4.5
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
disableligatures|Coe|0.0.10
vscode-markdownlint|Dav|0.38.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.13
rushnav|Dev|0.0.6
githistory|don|0.6.14
xml|Dot|2.5.1
escaping-characters|drp|1.0.0
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
git-project-manager|fel|1.7.1
scriptcsRunner|fil|0.1.0
vscode-firefox-debug|fir|2.9.1
vscode-npm|fkn|3.3.0
shell-format|fox|7.0.1
matlab|Gim|2.0.0
vscode-pull-request-github|Git|0.21.2
mdmath|goe|2.5.1
gc-excelviewer|Gra|3.0.40
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
mediawiki|jak|2.1.0
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
gpg|jva|0.1.2
docomment|k--|0.1.19
vscode-liquid-snippets|kil|2.0.1
markdown-shortcuts|mdi|0.12.0
openapi-lint|mer|1.2.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.177.0
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.0.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.1
csharp|ms-|1.23.7
vscode-dotnet-runtime|ms-|1.0.0
mssql|ms-|1.9.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.12.1
jupyter|ms-|2020.12.411183155
vscode-ai|ms-|0.6.18
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
mono-debug|ms-|0.16.2
powershell|ms-|2020.6.0
vscode-node-azure-pack|ms-|0.0.11
vscode-typescript-tslint-plugin|ms-|1.3.0
azurerm-vscode-tools|msa|0.14.0
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
azdo-wiki-md|ni|0.0.3
vscode-yaml|red|0.13.0
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
addDocComments|ste|0.0.8
code-spell-checker|str|1.10.2
code-spell-checker-greek|str|0.1.6
code-spell-checker-hebrew|str|0.1.5
code-spell-checker-medical-terms|str|1.0.9
code-spell-checker-spanish|str|1.0.7
msbuild-project-tools|tin|0.3.10
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
highlight-bad-chars|wen|0.0.3
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
t4-support|zbe|0.5.0
material-theme|zhu|3.9.11

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide screenshot of the problem pelase?
Also is this issue reproducible in insiders build https://code.visualstudio.com/insiders/?

**Comment by af4jm** [comment]
I don't have Insiders, will try to DL tomorrow & check, but I can tell you it's been in VSCode for a few months... a related observation, though: the bug is always triggered by typing. When a file is first opened, it never has horizontal scroll.  I've only noticed the issue with Markdown files, but I'm in Markdown all the time (my personal notebook is an Azure DevOps wiki)... screenshot from one of the pages attached (it's actually 2 screen shots in 1, the top showing "normal" and the bottom showing the same lines scrolled to the right after typing some long lines)
![VSCode-Scroll-WordWrap](https://user-images.githubusercontent.com/849948/101998977-1fc25800-3ca6-11eb-8b1f-a863d650eefb.png)

**Comment by alexdima** [comment]
@af4jm Please try `"editor.wrappingStrategy": "advanced"`. Our default wrapping algorithm assumes that all characters are equal in width, while this "advanced" one uses real DOM measurements. This will be slower, but should be more accurate.

**Comment by af4jm** [comment]
thanks, I'll put that in now and comment again later... that also explains why it's treating the 0-width space as if it's the same as every other character (which should all be the same since I'm using a mono font)

**Comment by af4jm** [comment]
so ran with that setting today & only noticed the horizontal scroll once, and it was less than 1 character width instead of the normal 2 characters, which is much better...

BUT switching `wrappingStrategy` from `simple` to `advanced` also forced `wrappingIndent` to behave as if it's set to `same`, ignoring whatever it's actually set to

**Comment by alexdima** [comment]
Yes, that is a limitation unfortunately caused by the `advanced` implementation. The `advanced` implementation delegates wrapping computation to the browser. It does so by rendering all lines with the editor width and then uses binary search to locate where the DOM has introduced wrapping points.

Unfortunately, the browser has no equivalent CSS styling to our "wrappingIndent": "indent" or "deepIndent" so it is not possible to ask the browser to wrap with those settings.
