### ISSUE TITLE
Make --performance flag work with opening a second window

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11220]
- run the following command: `code --performance`
- run `F1 > Show Startup Perf`
- wait a little ~30sec
- open another blank window of VS Code
- run `F1 > Show Start Perf`
- 🐛 the value of `Total` seems to include the wait time from step 3

**Comment by jrieken** [comment]
@bpasero fyi I found this because I have the *feeling* that opening a new window is slower then starting VS Code but I have a hard time debugging/measuring this. Any tips are welcome.

**Comment by bpasero** [comment]
@jrieken yeah this flag currently only makes sense for the first window to open, it is not fit for multi window case, though we could probably add that because we know how many windows are open.

**Comment by bpasero** [comment]
@jrieken only thing I know right now to measure startup time within a window is to run the profiler and do a Reload Window. This should be very similar to the time it takes to open a second window.

**Comment by bpasero** [comment]
You can now always run `Developer: Startup Performance` even if not providing `--performance` (it will just have a little less details). Also, for a second window, the start time will be correctly taken as the load time of the window and not the overall program start time.
