### ISSUE TITLE
Markdown extension fails in Safari: "Invalid regular expression: invalid group specifier name."

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#112217]
* run `yarn web`
* open http://localhost:8080 and then `file.md`
* 💥 the extension doesn't activate

<img width="900" alt="Screenshot 2020-12-10 at 12 35 54" src="https://user-images.githubusercontent.com/1794099/101767356-61a3a080-3ae4-11eb-85d8-2ea7599cb4c4.png">

**Comment by mjbvz** [comment]
@meganrogge I tracked this down to this regular expression: https://github.com/microsoft/vscode/blob/a2193cb8271ad3b9b2c1daff82a914aa9e4e2b1e/extensions%2Fmarkdown-language-features%2Fsrc%2Ffeatures%2FsmartSelect.ts#L165

The `createOtherInlineRange`  regex may be invalid too. Not
