### ISSUE TITLE
Ctrl-C and Ctrl-V Are Not Working in the Integrated Terminal

### ISSUE THREAD

**Issue by VidarrKerr** [microsoft/vscode#112244]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open an "integrated terminal" and try to copy and paste text with Ctrl-C and Ctrl-V and it doesn't work.
2. Cannot copy, Ctrl-C, any text in the terminal and cannot paste, Ctrl-V, any text in the terminal.
3. I have a brand new, Microsoft keyboard with Ctrl-C and Ctrl-V clearly marked on the "C" key and the "V" key.
4. I don't think my Microsoft keyboard is broken, because Ctrl-C & V are working in every other application except vscode. It is definitely the vscode for the "integrated terminal" that is broken. 

Does this issue occur when all extensions are disabled?: Yes/No
Extensions have nothing to do with the Problem. The Problem exists even in a stock vscode. 

Cheers.

**Comment by VidarrKerr** [comment]
VSCode Version: Latest
OS Version: Latest Ubuntu

**Comment by octaviotastico** [comment]
@VidarrKerr Have you tried doing Ctrl+Shift+C and Ctrl+Shift+V?

**Comment by meganrogge** [comment]
What shell type are you using (bash, powershell, etc)? does it happen in all of them?
