### ISSUE TITLE
Git: Unable to change default git launch location in VSCode

### ISSUE THREAD

**Issue by jeffzy15** [microsoft/vscode#112261]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open any folder/workspace in vscode
2. The git window will show all activities in the default launch location of Git
3. This happens when the folder is not initialized as a git repository
4. It makes vscode slow when it tracks the changes in the default launch location of Git which is the Users Menu.
5. Git says too many activities occurring, only a subset of features will be available.

Does this issue occur when all extensions are disabled?: Yes

### Request: 

A setting to change the default git launch location in vscode like there is a setting to change the default launch location of the in-built terminal in vscode. Thank you.

**Comment by jeffzy15** [comment]
@eamodio Is this issue a bug as only a subset of git features are available when this issue occurs or will it be a feature request as I would like to have a setting to change the default launch location of git in VSCode.

**Comment by eamodio** [comment]
Is there possibly a git repo configured in the parent/ancestor folder of any of the folders you are opening? Because that is about the only way that I can think of that would have the SCM view show items outside the folder you opened in VS Code.

**Comment by jeffzy15** [comment]
The issue happens when I have not created a git repo and build the project.

**Comment by eamodio** [comment]
Can you record a video/gif of what you are seeing? I don't think I'm understanding.
