### ISSUE TITLE
Autocompletion menu is tiny

### ISSUE THREAD

**Issue by helperman** [microsoft/vscode#112218]
Issue Type: <b>Bug</b>

Autocompletion menu is shown in a tiny window.
I need to resize it regularly.
Here is a screenshot:
https://i.imgur.com/lWQZhZK.png

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.66GB (2.86GB free)|
|Process Argv|--crash-reporter-id 7f32048f-9ff4-442f-bdf5-c8e035c4fa53|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey-plus|cwe|2.6.2
vscode-ahk-manager|Den|0.0.18
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.411183155
vscode-autohotkey-plus-slimcode|raf|2.1.18
vscode-autohotkey|sle|0.2.2

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"
