### ISSUE TITLE
Git fails to auto-detect user.name and user.email after update to 1.52.0

### ISSUE THREAD

**Issue by michvllni** [microsoft/vscode#112294]
- VSCode Version: 1.52.0
- OS Version: Windows 10 Version 1909 18363.1198 + Windows Server 2019 Version 1809 17763.1577

Steps to Reproduce:

1. Update to Visual Studio Code 1.52.0
2. Have empty values for user.name and user.email in git config (`git config --global user.name` and `git config --global user.email`)
3. Try to commit anything to a repository
4. Commit fails with the following error (which should usually only appear when auto-detection is disabled, which it is not)

![image](https://user-images.githubusercontent.com/45660891/101918308-8291f180-3bc9-11eb-89d7-951a8bc3a128.png)

Git Output:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
> git config --get-all user.name
```

Note: This does not happen when committing directly through a shell (for example powershell or mingw64), so it has to be a problem with VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gchovanyecz** [comment]
+1

**Comment by jplackey** [comment]
Same here.

**Comment by eamodio** [comment]
This change was by-design, as it can be a privacy issue to allow Git to glean information from your machine without you knowing. We recommend setting your username and e-mail address in your `.gitconfig` file.

**Comment by michvllni** [comment]
As an alternative: Maybe give us the possibility to enable the auto-detection in the settings?

**Comment by mark-hahn** [comment]
When I go to my home directory and look in .gitconfig I see my email and name.  But I'm still getting this error when I try to commit, making vscode git unusable.

**Comment by mrwensveen** [comment]
A lot of users probably don't use the git command line (a lot) and just use the interface VSCode and the Git extension give them. The Learn More button links to a git-scm page that may be confusing to them. It would be nice to be able to configure this from within vscode / the git extension.

**Comment by Irimax** [comment]
Hello I have the same problem in addition I have several git accounts with a credentials because I use git for me and for the work thank you for fixing the problem even if I use the terminal it is still more practical with vscode

**Comment by abby-d** [comment]
We're having this issue at my work, too. We've all updated, but only one person is getting this error. We use Git and GitHub and VSC to version our help content, so we're all technical writers, not developers--and we aren't able to resolve this issue for a person on our team. More communication on this change and a more visual interface for updating this information would be really useful.

**Comment by CoreTechnologyAG** [comment]
this worked for me.

git config user.name "name"
git config user.email name@changeme.com 

But it has to be entered in each project. 

git config --global does not really work

**Comment by GuilhermeAbacherli** [comment]
In the project's directory I typed the following:
`git config --global user.email "thesame@email.com"`
`git config --global user.name "My Name"`
And it worked for me.

**Comment by michvllni** [comment]
@CoreTechnologyAG @GuilhermeAbacherli 
I know how to resolve it, the reason why I opened this issue is because i think it can be done better.
@eamodio could you take a Look at our suggestions?
They are as following:
Suggestion 1:  Make an option in the settings to enable/disable auto-detect
Suggestion 2: Make it a Warning instead of an error (Like git does as well)
Suggestion 3: Give us the option to set user.name and user.email directly from VS Code (By @mrwensveen and @abby-d )

**Comment by jobe451** [comment]
I work on quite a few little personal never shared with others projects and I simply use a local git repository, not synced to anything remote.
So far setting up such a project was essentially a single click. Now I should every few weeks lookup somewhere the syntax to set name and mail by command line. If there were at least a quick dialog when creating the repo asking for name and mail that would be very helpful.

**Comment by LorenzoColombi** [comment]
Same issue. But .gitconfig is set correctly.

**Comment by eamodio** [comment]
@michvllni I opened: https://github.com/microsoft/vscode/issues/114049 to track that

**Comment by vicchimenti** [comment]
I get this same error when setting up vscode on a new computer. When I check my git config everything looks good:

$ git config --list --show-origin
file:/home/victor/.gitconfig    user.name=myname
file:/home/victor/.gitconfig    user.email=my@email.com
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/vicchimenti/law-newsroom.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master

My github profile is also save in vs code yet I get this error:

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
> git config --get-all user.name

**Comment by LorenzoColombi** [comment]
@vicchimenti do you put the ""?

I had same issue because typing _git config --global user.email you@example.com_ and not _git config --global user.email "you@example.com"_

**Comment by vicchimenti** [comment]
Yes, it is entered correctly

**Comment by vicchimenti** [comment]
I can only get it to work without --global, however I have to do this everytime I clone a repo now because --global never works

**Comment by Marjona6** [comment]
> this worked for me.
> 
> git config user.name "name"
> git config user.email [name@changeme.com](mailto:name@changeme.com)
> 
> But it has to be entered in each project.
> 
> git config --global does not really work
> 
> VS-Version:
> `Version: 1.52.0 (user setup) Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be Date: 2020-12-10T22:45:11.850Z Electron: 9.3.5 Chrome: 83.0.4103.122 Node.js: 12.14.1 V8: 8.3.110.13-electron.0 OS: Windows_NT x64 10.0.19042`

Thanks for this, I am having the same problem and removing the `--global` worked for me. But this is not at all ideal as a long-term solution.

```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by vicchimenti** [comment]
Thanks for everyone's help. Dropping the --global worked.

**Comment by eamodio** [comment]
Added a new `git.requireGitUserConfig` setting to control this behavior -- see #114433
