### ISSUE TITLE
Cannot search for Extension or install vsix file

### ISSUE THREAD

**Issue by siyavash4812** [microsoft/vscode#112241]
- VSCode Version: 1.51.1
- OS Version: Mac OS Big Sur 11.0.1 

Steps to Reproduce:

1. Install Vscode
2. Go to extension Tab
3. Infinite loop trying to load extensions
4. Trying to install a vsix file will not do anything 

Does this issue occur when all extensions are disabled?: Yes
<img width="494" alt="Screenshot 2020-12-10 at 19 10 09" src="https://user-images.githubusercontent.com/22658677/101818393-b3b3e880-3b1b-11eb-996a-3b36d12ff84a.png">

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by siyavash4812** [comment]
No request is being sent when I go to the extension tab! I can go to the link you posted successfully. 
Here are the logs: 
1- 

> [Extension Host] Message (loading...) didn't get externalized correctly.
t.log @ console.ts:140

> [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
event.ts:19 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ browser.ts:96
_event._event @ event.ts:562
(anonymous) @ linkedList.ts:127
onFirstListenerAdd @ linkedList.ts:127
_event._event @ event.ts:562
O @ listWidget.ts:548
createMouseController @ listWidget.ts:1180
K @ listWidget.ts:1248
t.PagedList @ listPaging.ts:86
L @ listService.ts:282
_createInstance @ instantiationService.ts:73
createInstance @ instantiationService.ts:73
renderBody @ extensionsViews.ts:132
render @ paneview.ts:213
render @ viewPaneContainer.ts:228
onDidAddViewDescriptors @ viewPaneContainer.ts:1322
onDidAddViewDescriptors @ extensionsViewlet.ts:617
(anonymous) @ viewPaneContainer.ts:1041
fire @ event.ts:584
onDidChangeContext @ viewContainerModel.ts:600
(anonymous) @ viewContainerModel.ts:312
fire @ event.ts:584
(anonymous) @ linkedList.ts:127
fire @ event.ts:584
fire @ event.ts:584
setContext @ contextKeyService.ts:303
set @ contextKeyService.ts:145
doSearch @ extensionsViewlet.ts:595
(anonymous) @ extensionsViewlet.ts:559
(anonymous) @ async.ts:167

2-

> sharedProcessMain.ts:296 Uncaught (in promise) Error: There is an instance already running.
    at sharedProcessMain.ts:296
    at /Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/async file:/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:639
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/applicationinsights.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Logging.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/diagnostic-channel/initialization.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Console.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Exceptions.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/Performance.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Util.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/RequestResponseHeaders.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpDependencyParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Constants.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/AvailabilityData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Domain.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Base.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ContextTagKeys.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Data.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPoint.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/DataPointType.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/Envelope.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/EventData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/ExceptionDetails.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MessageData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/MetricData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/PageViewData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RemoteDependencyData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/RequestData.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/StackFrame.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/Generated/SeverityLevel.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/RequestParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Declarations/Contracts/TelemetryTypes/TelemetryType.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/CorrelationIdManager.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpRequests.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/AutoCollection/HttpRequestParser.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/NodeClient.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/TelemetryClient.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Config.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Context.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/TelemetryProcessors/index.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Channel.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/TelemetryProcessors/SamplingTelemetryProcessor.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/Sender.js.map: Unknown error
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node_modules/applicationinsights/out/Library/EnvelopeFactory.js.map: Unknown error

3- There is noLog (Shared)
4- Log (Window) is empty

**Comment by sandy081** [comment]
No shared process

**Comment by joaomoreno** [comment]
Is the problem fixed if you restart your machine?

**Comment by joaomoreno** [comment]
> sharedProcessMain.ts:296 Uncaught (in promise) Error: There is an instance already running.

🤔

**Comment by siyavash4812** [comment]
@joaomoreno That fixed it 😬 I should have tried that first, thank you
