### ISSUE TITLE
Open new search editor should copy settings from search tab

### ISSUE THREAD

**Issue by Trismegistos84** [microsoft/vscode#112209]
When I open new search editor every field (search word, "files to include", "files to exclude") is empty. It would be more convenient when these fields would be prefilled with content of these fields in search tab. I often open search editor because I don't want to use search tab but it's fields like "files to include" has path that I want to search.

**Comment by JacksonKearl** [comment]
If you use the "Open in Editor" link do you get what you want?

**Comment by Trismegistos84** [comment]
If I do that content of fields is not copied.

**Comment by JacksonKearl** [comment]
![recording (1)](https://user-images.githubusercontent.com/8586769/101809457-6d836880-3acc-11eb-81a5-86631beb34fd.gif)
this is what i see, the. fields do seem to copy over.

**Comment by Trismegistos84** [comment]
It does not copy them for me. I have checked on two different computers: one with Linux other with Windows.

![screenshot2](https://user-images.githubusercontent.com/10066060/101839107-15874900-3b42-11eb-9e4f-4a0b07771b27.png)

**Comment by JacksonKearl** [comment]
Are you clicking this `Open in Editor` link? You won't see it if the search has no results.

![image](https://user-images.githubusercontent.com/8586769/101839772-cfa59300-3af7-11eb-82d0-0669a4847fca.png)

**Comment by Trismegistos84** [comment]
I'm right clicking folder in workspace browser then "Find in Folder..." then "Open New Search Editor" icon.

**Comment by JacksonKearl** [comment]
Ah, I see. Thanks for clarifying!

**Comment by JacksonKearl** [comment]
The search view's config (flags, includes, excludes, *not* query) will now be transfered over to the search editor created with the "Open Search Editor" action bar item.

**Comment by Trismegistos84** [comment]
I have tried that functionality in VS insiders edition. It works as expected. Thank you.
