### ISSUE TITLE
Provide SSH_ASKPASS environment variable along with GIT_ASKPASS

### ISSUE THREAD

**Issue by GeorchW** [microsoft/vscode#112286]
I'm not sure if this should be a bug or a feature request; I'm suggesting to fix a root cause for a variety of problems here.

There are [various bug reports around Git asking for SSH passwords with no ssh-askpass being around](https://github.com/microsoft/vscode/issues?q=is%3Aissue+SSH_ASKPASS+git). The worst is probably #23855, where the entire X session (at least in Cinnamon) freezes because SSH wants some textual input. I've had the exact same problem for quite a while now, and I used to solve it by just unlocking the ssh agent before opening the repository to prevent the password prompt. 

(It was a super-weird bug, since it required the server to accept SSH passwords, and many Git servers don't do so, and as such only happend for *some* repositories. I wouldn't be surprised if it happened only with selected desktop environments, too. I'm absolutely not surprised that you guys had difficulties reproducing #23855. But that's not the point, there are other issues caused by this as well, most prominently a missing ssh-askpass executable on Mac, see #33814, #32097, #52137, #92331, or on Linux, see #57488.) 

When the repository is connected via HTTPS, the editor instead pops up a little box asking to enter a password.
I've always wondered why this box is not consistent between SSH and HTTPS passwords.

Just now, I've realized that the Git extension sets the GIT_ASKPASS env variable, which takes care about passwords via HTTPS, but not the SSH_ASKPASS environment variable to do the same for SSH. 
My suggestion would be to simply make this consistent: use the same password dialog for both SSH and HTTPS by setting both env variables the same way. While we're at it, we might as well force SSH to not use the console by setting SSH_ASKPASS_REQUIRE to "force". 

Now, I'm not an expert in the Git extension code, but to me it looks like we would only have to add a few lines for the additional environment variables right here: https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/extensions/git/src/askpass.ts#L75-L88

This would just make the experience consistent and avoid lots of new bug reports about SSH. I'd be happy to try it out and do the PR, if this kind of change is considered reasonable. I've set these environment variables to something reasonable on my machine now and I'm finally not getting X freezes any more when I forget to unlock my SSH key, but I think fixing the root causes might benefit many more people.

**Comment by GeorchW** [comment]
Ooh, that issue (linked as additional duplicate in #13680) is actually really close, good bot. My suggestion is a little more concrete, though: reusing the same password dialog from HTTPS, nothing more.

**Comment by GeorchW** [comment]
@eamodio can I interpret the "help wanted" label as "go ahead" or is it meant as "I'll need someone else to help me look over it"?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/13680
