### ISSUE TITLE
IPC communication to remote hangs forever when disconnected

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#112278]
- VSCode Version: `1.52.0-insiders`
- Local OS Version: `Windows 10.0.20262.0` (current Dev Channel) ARM64 (Surface Pro X)
- Remote OS Version: `Windows 10.0.19042.0` (current Beta Channel)
- Remote Extension/Connection Type: `SSH`

I've had this happen a few times now, where auto-save during a connection interrupt, basically kills the whole window (can't even reload)

Steps to Reproduce:

1. Make sure you have auto-save set to save on focus change
2. Connect to remote, edit a file
3. Do something to cause the remote to become unavailable
4. Get disconnect dialog, which causes a focus change and causes the file to try to be saved (which will fail)
5. Try to reload the window (I don't know if the remote needs to be back or not) and it will clear the dialog, but status bar says remote is disconnected
6. The unsaved file is still unsaved and you can't close it or open any other files, can't even run Reload Window from the command palette -- have to exit vscode completely usually by killing it via taskman

**Comment by bpasero** [comment]
I now understand why things like "File > Open" do not work because we seem to be doing a file service call here to figure out if the default URI exists:

https://github.com/microsoft/vscode/blob/e16d1f06d738ef620ded7a31e6a682e76017bd6d/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L256-L256

This call never returns and as such the dialog never opens.

As for Quit and Reload not working: same reason, we wait for the file to be saved and this never finishes.

**Comment by bpasero** [comment]
As Alex was pointing out, it makes sense to hold any requests as long as reconnection attempts are made. But in this case I see a native dialog telling me that no reconnection is possible and I have to reload. So in this case we should maybe error each pending IPC request. In this case the workbench would handle it properly on shutdown 👍

**Comment by bpasero** [comment]
Hm, this would still not help in case the user does an explicit window reload, even when the reconnection dialog is showing. So I realise that maybe this issue has to split up into 2:
* give up on pending IPC calls when we know we cannot reconnect (Alex)
* improve the user experience when the user wants to reload while we try to reconnect (Ben(

**Comment by bpasero** [comment]
Pushed a change that brings up a notification with progress when saving takes long:

![recording](https://user-images.githubusercontent.com/900690/102228438-ff370f80-3eea-11eb-88d4-726749b2fdfa.gif)

When cancelling, we will allow the window reload by storing the changes as backups. 

I think this is a good enough change, not sure it is worth changing the IPC communication here.

**Comment by alexdima** [comment]
I will also do the following (as part of #112568):
- dispose the `IPCClient`
- fail any further requests through the channel

**Comment by eamodio** [comment]
Looks good -- now I see a notification for the save that I can cancel, allowing the reload to happen.
