### ISSUE TITLE
Seti: font not perfectly aligned with file label

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11227]
Testing https://github.com/Microsoft/vscode/issues/11130

I find that the icon is not perfectly aligned to the text label. It looks like the file icon could be pushed down by a few pixels on Mac:

![image](https://cloud.githubusercontent.com/assets/900690/18095894/bcbd545c-6ed8-11e6-93dd-043707ae5515.png)

**Comment by aeschli** [comment]
@bpasero The file explorer CSS is yours, feel free to change it to your gusto.
I used `vertical-align: top`.
![image](https://cloud.githubusercontent.com/assets/6461412/18124493/c7c5c6aa-6f72-11e6-9655-80176f0b1409.png)

No specifying `vertical-align` (witch defaults to 'baseline') looks also good:
![image](https://cloud.githubusercontent.com/assets/6461412/18124161/55ce2f7a-6f71-11e6-8b37-9f57dad75a79.png)

**Comment by bpasero** [comment]
@aeschli thanks works for me

**Comment by bpasero** [comment]
I reverted my change with the vertical-align because a) it is causing issues with the rename box dropping down and b) I noticed that the font looks very well aligned in default zoom (at work I always run with 1 level zoomed in and that causes the misalignment).
