### ISSUE TITLE
Broken test: vscode API - editors insert snippet with clipboard variables:

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112264]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=96720&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=73edc4f4-4d06-5ec0-963f-39c19154950b

Test is failing on all platforms, on the built version only.

![image](https://user-images.githubusercontent.com/22350/101871581-1e007380-3b84-11eb-9d4e-6399ee58a0ad.png)

---

@bpasero, assigning you since there were clipboard changes yesterday. Please forward accordingly if this belongs to someone else.

**Comment by bpasero** [comment]
Pushed a change to not prompt if running extension tests.

//cc @jrieken
