### ISSUE TITLE
VS Code Insiders won't update (Windows)

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#11223]
- VSCode Version: 1.5.0-insider (2016-08-26)
- OS Version: Windows 10 AU (64bit)

When a new version is available, the "help -> check for updates" menu turns into "Downloading update...", and when it's ready to be installed I get a pop up asking me if I want to do so.

The problem is that since a few versions, the menu is stuck displaying "Downloading update...", and never displays me the popup.

**Comment by joaomoreno** [comment]
Strange, and always shows the same behaviour even after restarting Code? And your machine?

Are you behind a proxy?

**Comment by warpdesign** [comment]
Restarting Code shows the same behavior. I'll try to reboot the computer. I'm not behind a proxy.

**Comment by warpdesign** [comment]
Restarting the computer fixed the problem.
