### ISSUE TITLE
Remote explorer showing more than 1 view at the time (though one is dead)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#112200]
Not sure how I got into this state exactly, but I did have both a Codespace and a WSL session open. I closed the WSL session, and went back to the Codespace and saw this:

![image](https://user-images.githubusercontent.com/641685/101730063-5a01de80-3a87-11eb-8ebc-d2da1b61c341.png)

The GitHub Codespaces view seems dead -- refresh doesn't do anything, while the WSL view seems to work.

If I switch views via the dropdown, then it fixed things.

I also for some reason seem to have 2 Codespaces items in the dropdown:

![image](https://user-images.githubusercontent.com/641685/101730498-1eb3df80-3a88-11eb-8bd7-6947e8640189.png)

The GitHub Codespaces one works, while the other wants me to sign in via the Azure account extension (which isn't installed)

**Comment by alexr00** [comment]
The two Codespaces is probably because you have the old Visual Studio Codespaces extension installed.

**Comment by alexr00** [comment]
I can repro the extra views showing.

**Comment by alexr00** [comment]
Wrong issue tagged in the commit!
