### ISSUE TITLE
taskExecutions should be empty if dependent task failed during executeTask

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#112247]
Issue Type: <b>Bug</b>

### Repro Steps:
1. Using this tasks.json:
    ```json
    {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Hello World",
                "type": "shell",
                "command": "echo 'Hello World'",
                "problemMatcher": [],
                "dependsOn": "Fail"
            },
            {
                "label": "Fail",
                "type": "shell",
                "command": "exit -1",
                "problemMatcher": []
            }
        ]
    }
    ```
1. Execute the "Hello World" task with this code from an extension:
    ```typescript
    const task = (await vscode.tasks.fetchTasks())[0];
    await vscode.tasks.executeTask(task);
    ```
1. Wait for the "Fail" task to error out (and prevent "Hello World" from running)
1. Inspect the value of `vscode.tasks.taskExecutions`

I would expect `taskExecutions` to be an empty array, but it returns an array with one element (the "Hello World" task). It appears this is only a problem when combined with `vscode.tasks.executeTask` from step 2. If I execute the "Hello World" task from the command palette, `taskExecutions` _is_ empty as expected.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id e2c60431-fb89-41a2-b9ed-11e53cee83ac|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexr00** [comment]
This looks like its going to be very tricky to fix. How big of a problem is the bug causing you @ejizba ?

**Comment by ejizba** [comment]
I just want a way to call `tasks.executeTask` and have it do nothing if the task (or a "dependsOn" task) is already running. Today there's a lot of weird edge cases and race conditions where sometimes it'll start a second instance of the task (which usually causes port conflicts or errors like "this dll is being used by another process") and sometimes it'll show an error like this:
<img width="471" alt="Screen Shot 2020-12-14 at 4 42 34 PM" src="https://user-images.githubusercontent.com/11282622/102153214-8f158480-3e2b-11eb-916e-73e65450008a.png">

I thought the simplest solution would be to check `tasks.taskExecutions` before calling `tasks.executeTask`, but that won't work if `taskExecutions` isn't accurate. I also hoped this bug would be relatively simple to fix since the command palette entry point of executing the task did _not_ seem to have the same problem.

**Comment by alexr00** [comment]
Thanks for the additional context. I'll take another look and see what I can do.

**Comment by alexr00** [comment]
I found a fix that should work and isn't as complex as I had originally thought.
