### ISSUE TITLE
unins000.exe error on automatic update

### ISSUE THREAD

**Issue by RTX3070** [microsoft/vscode#112295]
Issue Type: <b>Bug</b>

Seems VS Code has some problem performing automatic update on my machine. I got a warning on unins000.exe file when trying to install an update.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (27.95GB free)|
|Process Argv|--crash-reporter-id 658eddc0-ad1d-49ae-9a01-a89bc39084f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
woocommerce|cla|1.1.0
vscode-eslint|dba|2.1.13
javascript-ejs-support|Dig|1.3.1
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
search-node-modules|jas|1.3.0
vscode-wordpress-hooks|joh|0.5.3
vscode-codemetrics|kis|1.24.0
node-module-intellisense|lei|1.5.0
vscode-azurefunctions|ms-|1.0.1
remote-wsl|ms-|0.51.4
azure-account|ms-|0.9.4
vsliveshare|ms-|1.0.3303
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.11
vscode-for-node-js-development-pack|nod|2.0.1
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.1.1
wordpress-snippet|tun|1.1.5
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.13.0
wordpress-toolbox|wor|1.3.8
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by RTX3070** [comment]
> 
> 
> Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`. Does that address the issue?
Hello,
didn't worked, If I check for an update and then restart VS Code to install the update I got the same warning message: Can't create a file in the installation directory (unins000.exe)

**Comment by RTX3070** [comment]
> 
> 
> Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`. Does that address the issue?

Hello,
didn't worked, If I check for an update and then restart VS Code to install the update I got the same warning message: Can't create a file in the installation directory (unins000.exe)

**Comment by joaomoreno** [comment]
Strange. Can you try completely uninstalling VS Code, installing it, and then check if the subsequent updates work?

**Comment by RTX3070** [comment]
> 
> 
> Strange. Can you try completely uninstalling VS Code, installing it, and then check if the subsequent updates work?

If I uninstall VS Code I will loose all my settings and installed extensions?

**Comment by joaomoreno** [comment]
> > Strange. Can you try completely uninstalling VS Code, installing it, and then check if the subsequent updates work?
> 
> If I uninstall VS Code I will loose all my settings and installed extensions?

No, they will be preserved.
