### ISSUE TITLE
Dev tools blank out when navagiting to iframe

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#112326]
Issue Type: <b>Bug</b>

When using Dev Tools in OSS, the Dev Tools will blank out whenever trying to focus on an iframe

![image](https://user-images.githubusercontent.com/876920/101948561-1b634580-3ba7-11eb-8a06-25c2171baa49.png)

VS Code version: Code - Insiders 1.52.0-insider (c6cb54153991e7e3686c51ccd8d85b626b9b1fe4, 2020-12-09T16:02:22.126Z)
OS version: Windows_NT x64 10.0.19041

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/112172
