### ISSUE TITLE
Visual Studio Code has very high CPU usage

### ISSUE THREAD

**Issue by cheuk-cheng** [microsoft/vscode#112315]
Issue Type: <b>Performance Issue</b>

I checked for extension updates each day and since yesterday Visual Studio Code had been hogging my CPU (~300%).  I opened the Process Explorer tool inside Visual Studio Code and it showed that extensionHost had very high CPU usage.  I had updated to the November release of Visual Studio Code and tried disabling a few of the recently updated extensions but that did not help.

Thanks. 

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 13, 14|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 0857be46-1a0e-45a9-a9d1-9e5f119a5a62|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    9	   131	 16496	code main
    1	    49	 16499	   gpu-process
    0	    33	 16501	   utility
    0	   360	 16502	   window (Untitled-34 — Untitled (Workspace))
  291	  1507	 16511	     extensionHost
    0	   180	 16534	       electron_node server.js 
    0	    33	 16536	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=16511
    0	    33	 16538	       electron_node server.js 
    0	    66	 16550	       electron_node languageserver.js 
    0	   147	 16610	       electron_node server.js 
    0	    33	 16626	       electron_node ssmServer.js 
    0	    66	 16698	       electron_node server.js 
    0	    33	 17349	       electron_node aslServer.js 
    0	   131	 17461	       electron_node bundle.js 
    0	    66	 16512	     watcherService
    0	    33	 16522	     searchService
   90	   180	 16515	   shared-process
    0	     0	 18415	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    3	    66	 18258	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Untitled-34 — Untitled (Workspace))
|    Folder (GIT_stash): more than 20689 files
|      File types: txt(7364) py(1926) h(1633) sh(1331) png(850) cpp(731)
|                  plist(381) bin(359) traj(276) groovy(214)
|      Conf files: cmake(88) makefile(4) sln(4) launch.json(1)
|                  settings.json(1)
|      Launch Configs: python(11);
```

</details>
<details><summary>Extensions (165)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
string-converter|ada|0.1.2
codesnap|adp|1.2.0
Bookmarks|ale|12.0.0
project-manager|ale|12.0.1
separators|ale|2.0.0
aws-toolkit-vscode|ama|1.17.0
navigateto|app|1.0.1
ascii-tree-generator|apr|1.2.4
awarest-align|awa|1.1.0
vscode-back-forward-buttons|bai|1.0.1
vscode-django|bat|1.0.0
calva|bet|2.0.134
color-info|bie|0.5.1
markdown-preview-github-styles|bie|0.1.6
clj-kondo|bor|2020.11.700
insert-unicode|bru|0.10.0
path-intellisense|chr|2.3.0
regex|chr|0.2.0
vscode-postgres|cko|1.1.14
vscode-navigate-edit-history|cod|1.3.0
bracket-pair-colorizer-2|Coe|0.2.0
decimal-incrementor|coo|0.2.0
file-tree-to-text-generator|d-k|1.4.0
dakara-foldplus|dak|1.5.1
transformer|dak|1.11.0
jsonpath-extract|dav|1.2.3
vscode-quick-select|dba|0.2.9
vscode-hasher|dee|1.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
gitlens|eam|11.0.6
filter-lines|ear|0.2.0
vscode-html-css|ecm|1.1.2
vscode-powertools|ego|0.63.0
LogFileHighlighter|emi|2.10.0
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
auto-close-tag|for|0.5.9
code-runner|for|0.11.1
seito-openfile|Fr4|1.8.7
go|gol|0.19.1
cloudcode|goo|1.7.1
vscode-graphql|Gra|0.3.13
vscode-json-editor|Gre|1.0.200602
better-cursors|Gru|0.0.4
todo-tree|Gru|0.0.192
ubertab|Gru|0.0.7
timing|Haa|2.5.1
vscode-drawio|hed|1.2.0
yaml-plus-json|hil|1.6.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
output-colorizer|IBM|0.1.2
applescript|idl|0.19.0
align-by-regex|jan|1.0.4
jenkins-pipeline-linter-connector|jan|1.2.0
vscode-jmespath|jos|0.0.6
vscode-insertdatestring|jsy|2.3.0
wordcounter|kir|2.3.0
kite|kit|0.135.0
wrapSelection|kon|0.10.0
cql|Law|0.8.7
bash-ide-vscode|mad|1.11.0
string-manipulation|mar|0.4.3
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
vscode-language-babel|mgm|0.0.30
git-graph|mhu|1.28.0
vscode-edits-history|mis|0.1.6
vscode-clang|mit|0.2.3
azure-pipelines|ms-|1.177.0
vscode-apimanagement|ms-|0.1.8
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.0.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.1
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.7
vscode-dotnet-runtime|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.2.1
mssql|ms-|1.10.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.11.371526539
vscode-pylance|ms-|2020.12.1
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
js-debug-nightly|ms-|2020.12.917
powershell|ms-|2020.6.0
sublime-keybindings|ms-|4.0.7
typescript-javascript-grammar|ms-|0.0.55
vs-keybindings|ms-|0.2.0
vscode-node-azure-pack|ms-|0.0.11
vsliveshare|ms-|1.0.3303
azurerm-vscode-tools|msa|0.14.0
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.1.1
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-pg|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
embrace|myc|1.0.0
vscode-json-editor|nic|0.2.3
autodocstring|njp|0.5.4
vscode-drawio-plugin-mermaid|nop|0.1.2
favorites|ole|1.4.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.2
codebucket|pst|0.2.0
bracketeer|pus|1.3.1
quicktype|qui|12.0.46
ruby|reb|0.27.0
java|red|0.72.0
vscode-yaml|red|0.13.0
vscode-statusbar-json-path|ric|1.4.4
Unotes|rya|1.2.1
rylogic-textaligner-vscode|Ryl|1.10.5
edit-with-shell|ryu|1.2.0
partial-diff|ryu|1.4.1
text-marker|ryu|1.11.0
jinjahtml|sam|0.15.0
vscode-fileutils|sle|3.4.2
vscode-hexdump|sle|1.8.1
vscode-multiclip|sle|0.1.5
smart-formatter|Sma|1.1.2
codevalet-vscode|Sop|1.1.2
ascii-plist|spe|1.0.3
regexworkbench|ste|2.0.5
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-counter|uct|2.2.0
vscodeintellicode|Vis|1.2.10
azure-iot-toolkit|vsc|2.16.4
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.26.0
vscode-icons|vsc|11.0.0
vscode-ansible|vsc|0.5.2
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-ruby|win|0.27.0
any-swap|wol|0.1.3
local-history|xyz|1.8.1
current-file-path|Yos|3.0.0
markdown-all-in-one|yzh|3.4.0
json-helper|zho|1.3.2
material-theme|zhu|3.9.11
html-css-class-completion|Zig|1.19.0

(3 theme extensions excluded)

</details>

**Comment by FunnyLamma** [comment]
Sometimes this happens when you run code that might be pretty advanced, or do you have a large file open on it, I would restart it and create an empty folder, and open that folder, and if the problem persists, that would be worrysome.

**Comment by cheuk-cheng** [comment]
> Sometimes this happens when you run code that might be pretty advanced, or do you have a large file open on it, I would restart it and create an empty folder, and open that folder, and if the problem persists, that would be worrysome.

Thanks FunnyLamma.  I closed all files, then restarted Visual Studio Code and extensionHost was still using 300-400% of CPU.

**Comment by cheuk-cheng** [comment]
I had disabled the recently updated extensions one by one and figured out that the "HTML CSS support" extension was causing the extensionHost CPU hogging issue.  Once I uninstalled that extension the high CPU usage disappeared.  I am closing this issue.

Thanks.
