### ISSUE TITLE
Commits view header shows wrong commit count

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#112333]
In the "commits" scm view:

![image](https://user-images.githubusercontent.com/323878/101958973-42c30e00-3bb9-11eb-8564-f4708fbb633e.png)

I have no idea where 10/4 comes from

In the status bar, correct: 

![image](https://user-images.githubusercontent.com/323878/101958981-49518580-3bb9-11eb-9a47-7c554aaee92a.png)

**Comment by roblourens** [comment]
Actually it shows the same numbers even in a different repo

**Comment by usernamehw** [comment]
Isn't this a GitLens issue?

**Comment by eamodio** [comment]
Yes it is. I had inadvertently checked in some test code to the GitLens insiders build. Fixed in today's version.
