### ISSUE TITLE
If 2 folders have the same name, but a different location, then VS Code can't distinguish between them

### ISSUE THREAD

**Issue by move-78** [microsoft/vscode#112368]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a folder at C:/Users/Documents named "X" and create a file in it and open it with VS-Code.
2. Create a different folder at C:/Users/Documents/ named "SomeFolder" and create another folder in "SomeFolder" named "X" (i.e. C:/Users/Documents/SomeFolder/X)
3. Try to open the folder at C:/Users/Documents/SomeFolder/X. It won't work and VS-Code will try to open the folder at C:/Users/Documents/X.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
What exactly do you mean, what is the issue? This?

![image](https://user-images.githubusercontent.com/900690/102073535-bd7f6980-3e03-11eb-92a3-8afa73fb4c1c.png)
