### ISSUE TITLE
VSCode 1.52.0 and git issue with source control menu

### ISSUE THREAD

**Issue by lelloz0** [microsoft/vscode#112305]
- VSCode Version: 1.52.0
- OS Version: Windows Server 2019 / MacOs Catalina 10.15.7
- git version: 2.29.2

Steps to Reproduce:

1. Update VSCode to latest stable version 1.52.0
2. Click on Source Control (left pane), Source Control (three dots), Commit Staged (or Commit All)
3. You are going to get the following error: Make sure you configure your 'user.email' and 'user.name' in git

Does this issue occur when all extensions are disabled?: **Yes (on Windows Server 2019) and No on MacOs Catalina**

![image](https://user-images.githubusercontent.com/24714308/101929912-bb38c780-3bd7-11eb-8660-df411faa8697.png)

**Comment by hijkzzz** [comment]
Also on Ubuntu Server(bash)~

**Comment by eamodio** [comment]
I'm not sure how you are getting that message by using `git commit` from the command line. There was an intentional change in 1.52, when committing from VS Code to stop allowing git to glean user/email information from your machine, but I don't see how that would affect the terminal.

@lelloz0 Also that screen shot looks like it's from mac, but you say it works fine on mac.

@joaomoreno Do you know if we do anything when committing from the integrated terminal?

**Comment by eamodio** [comment]
I'm not sure how you are getting that message by using `git commit` from the command line. There was an intentional change in 1.52, when committing from VS Code to stop allowing git to glean user/email information from your machine, but I don't see how that would affect the terminal.

@lelloz0 Also that screen shot looks like it's from mac, but you say it works fine on mac.

@joaomoreno Do you know if we do anything special when committing from the integrated terminal?

**Comment by hijkzzz** [comment]
Device: MacOS Catalina --> ssh remote --> Ubuntu 18.04 Server (bash)
VSCode, 1.52
git commit by command OK!
git commit by VSCode failed, message 'Make sure your xxxxx'.
@eamodio

**Comment by hijkzzz** [comment]
git log 

Looking for git in: git
Using git 2.17.1 from git
> git rev-parse --git-dir
Open repository: /home/hujian/hujian/pymarl
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :run.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/run.sh
> git cat-file -s b1a2a493426f4ed1a9d67bba49bd95ecf2ac03f2
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s 946818cfa7dd1b9ff11dd34e7b90920c8c2a259c
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s 946818cfa7dd1b9ff11dd34e7b90920c8c2a259c
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :run.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/run.sh
> git cat-file -s b1a2a493426f4ed1a9d67bba49bd95ecf2ac03f2
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s 946818cfa7dd1b9ff11dd34e7b90920c8c2a259c
> git add -A -- .
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

*** 请告诉我你是谁。

运行

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

来设置您账号的缺省身份标识。
如果仅在本仓库设置身份标识，则省略 --global 参数。

fatal: 未提供姓名且自动探测被禁用
> git config --get-all user.name
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

*** 请告诉我你是谁。

运行

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

来设置您账号的缺省身份标识。
如果仅在本仓库设置身份标识，则省略 --global 参数。

fatal: 未提供姓名且自动探测被禁用
> git config --get-all user.name
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

*** 请告诉我你是谁。

运行

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

来设置您账号的缺省身份标识。
如果仅在本仓库设置身份标识，则省略 --global 参数。

fatal: 未提供姓名且自动探测被禁用
> git config --get-all user.name
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git fetch
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git fetch
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :run.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/run.sh
> git cat-file -s b1a2a493426f4ed1a9d67bba49bd95ecf2ac03f2
> git check-ignore -v -z --stdin
> git check-ignore -v -z --stdin
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git fetch
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git fetch
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :src/config/algs/cw_qmix8.yaml
> git ls-files --stage -- /home/hujian/hujian/pymarl/src/config/algs/cw_qmix8.yaml
> git cat-file -s 47059c53021ea3e7ab5760bd8ec9609d8260464b
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git fetch
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git check-ignore -v -z --stdin
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git fetch
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- /home/hujian/hujian/pymarl/.png.png
> git show --textconv :clean.sh
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s b2ccbddb460c763c93ebbc007af0d5bfef5f6e79
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git add -A -- .
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

*** 请告诉我你是谁。

运行

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

来设置您账号的缺省身份标识。
如果仅在本仓库设置身份标识，则省略 --global 参数。

fatal: 未提供姓名且自动探测被禁用
> git config --get-all user.name
> git ls-files --stage -- /home/hujian/hujian/pymarl/clean.sh
> git cat-file -s cd601190f0eb9b530d4735343772377be3639258
> git show --textconv :clean.sh
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template

**Comment by hijkzzz** [comment]
OK, I found the solution.
This is because the verification of Git command and VSCode is inconsistent, Git can commit when only setting email, and VSCode needs to set user at the same time.

**Comment by lelloz0** [comment]
> @lelloz0 Also that screen shot looks like it's from mac, but you say it works fine on mac.

it works fine only when I run code with the extensions disabled
 
> @joaomoreno Do you know if we do anything special when committing from the integrated terminal?

**Comment by lelloz0** [comment]
I've updated the main description: the issue only happens when committing changes fro the VScode GUI source menu, not the command line.

**Comment by Sven-Niehus** [comment]
I'm also experiencing the same issue on Windows 10 2004 with VS Code 1.52.0 and git 2.28.0 while trying to create a commit. Creating a commit using the CLI works just fine

**Comment by hijkzzz** [comment]
> OK, I found the solution.
> This is because the verification of Git command and VSCode 1.52 GUI is inconsistent, Git can commit when only setting email, but VSCode 1.52 GUI needs to set user at the same time.
> @eamodio

I solve this problem by following steps:
vim ~/.gitconfig
add the username to the config.

git cli can commit only with user email, vscode gui not.

**Comment by eamodio** [comment]
This is by design -- see https://github.com/microsoft/vscode/issues/110880

**Comment by eamodio** [comment]
Added a new `git.requireGitUserConfig` setting to control this behavior -- see #114433
