### ISSUE TITLE
my vs code is highly zoomed in an d i cannot do anything

### ISSUE THREAD

**Issue by H-web268** [microsoft/vscode#112386]
Issue Type: <b>Feature Request</b>

since several days I cannot do anything with my vs code because it zoomed in very hightly and I  cannot  even see one single file

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Treasure-dell** [comment]
Hi Coders here's my solution

You can adjust the Zoom level in VS Code with the View > Appearance > Zoom commands. The zoom level increases or decreases by 20% each time a Zoom command is executed. View > Appearance > Zoom In (Ctrl+=) - increase the Zoom level. View > Appearance > Zoom Out (Ctrl+-) - decrease the Zoom level.

**Comment by mehanalavimajd** [comment]
I think if you use ctrl + - it will be ok

**Comment by H-web268** [comment]
thank you very much  coders for your  help now all is ok  my probleme is
solved

my problem is solved


my problem is solv
