### ISSUE TITLE
Open Editor Sorting: Sorting with workbench.editor.untitled.labelFormat = content not working as expected between restarts

### ISSUE THREAD

**Issue by ruudhanegraaf** [microsoft/vscode#112395]
- VSCode Version: 1.52.0
- OS Version: Windows 10

Happy to see the sorting of the open editors arriving! :-)
I know there are currently some limitations in the API which keeps it from being the holy grail just yet, but there is a bug in the sorting of the untitled editors when using workbench.editor.untitled.labelFormat = content, especially between restarts of VSCode.

Steps to reproduce:

- Set workbench.editor.untitled.labelFormat to 'content'.
- Create and save a file Test1.ps1 (or any other extension).
- Create and save a file Test2.ps1 (or any other extension).
- Create and save a file Zzzz.ps1 (or any other extension).
- Create a new, empty untitled file. The order wil be: Test1.ps1, Test2.ps1, Untitled-1, Zzzz.ps1
- Change the first line of the untitled file to '#Blah'. The order will not change. I guess because of the limitations, though it would ne nice if the order would immediately change.
- Close Test2.ps1. The list will now automatically reorder to #Blah (Untitled-1), Test1.ps1, Zzzz.ps1. That's how I would like it to stay. But...
- Close VSCode and start it again.
- The order will now be Test1.ps1, #Blah (Untitled-1), Zzzz.ps1, instead of #Blah being first. That is not the expected behaviour.
- Close Zzzz.ps1. The list will be resorted again, and #Blah will be first again. Until the next restart that is.

Another thing I'm missing is the fact that the 'View: Show All Editors By Appearance' (which I've mapped to a key) will show the list in the non-sorted order. It would be nice if that command also showed the sorted list or an extra command was added 'View: Show All Edtors By Alphabet'. Just let me know if I should post this as a separate feature request.

Thanks for all your efforts on VSCode!

**Comment by isidorn** [comment]
Sounds like an issue in the Open Editors sorting. Assinging to this milestone to investigate more and potentially fix.

As for the View: Show All Editor by Appearance - please file a new issue for that, as that is done by another component in VS Code.

**Comment by ruudhanegraaf** [comment]
Check. Will do. Thanks. :-)

**Comment by isidorn** [comment]
@bpasero do we have some nice event for when the unitiled editor title changes? Since I seem to be missing that and my Open Editors list is not refreshing - it should since the untitled name just changed thus affecting sorting.

**Comment by bpasero** [comment]
@isidorn yes, every editor exposes a `onDidChangeLabel` event:

https://github.com/microsoft/vscode/blob/b8ddffe7b413b52fd9bae16a2e4245a7136a5ff8/src/vs/workbench/common/editor.ts#L388-L388
