### ISSUE TITLE
1.52 reintroduced bug on Big Sur terminal slow

### ISSUE THREAD

**Issue by jvanderaa** [microsoft/vscode#112361]
- VSCode Version: 1.52
- OS Version: Big Sur 11.0.1

Steps to Reproduce:

1. Rebooted VSCode, auto updated to 1.52
2. Use the terminal, response time is slow

This may be the same as #105446, not sure if the update is intended to re-introduce slowness. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by nomo-nomad** [comment]
I'm experiencing this issue as well

**Comment by ertankara** [comment]
Same issue, also slower transition between editor and the terminal

**Comment by ertankara** [comment]
Applied previous solution for myself and it solved again. The new updated must have revoked it maybe

https://github.com/microsoft/vscode/issues/107103#issuecomment-731664821

Executing the following fixes lag but not really sure if it is a safe way. Better than lagging 24 / 7

`codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`

**Comment by meganrogge** [comment]
Duplicate of #105446

**Comment by jvanderaa** [comment]
@meganrogge -> So the latest update of VS Code was intended to re-introduce #105446? I had the fix applied that was recommended in the thread. Then the update happened for VS Code. I had to re-apply the fix again.

**Comment by deepak1556** [comment]
Updating vscode will replace the binaries, so if you had removed the codesign previously they will not be preserved during updates.

**Comment by ivands** [comment]
If this is just a temporary fix, will there be a permanent one?

**Comment by joostshao** [comment]
Same issue

**Comment by deepak1556** [comment]
Please follow https://github.com/microsoft/vscode/issues/105446 for updates on the fix.
