### ISSUE TITLE
Line highlighting off by one in v1.52.0

### ISSUE THREAD

**Issue by bubbajames-docker** [microsoft/vscode#112329]
- VSCode Version: 1.52.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open ANY file type (does not matter extension)
2. Select line number.

Result:
Line number clicked DOES highlight text.  However, the line NUMBER below is highlighted.

Expected:
Line NUMBER clicked is highlighted.

Does this issue occur when all extensions are disabled?: Yes

<img width="755" alt="incorrect-line-number-highlighted" src="https://user-images.githubusercontent.com/67807740/101953979-2b335780-3bb0-11eb-909f-b0e55a228227.png">

**Comment by bubbajames-docker** [comment]
Might be related to (or cause of) all the "Unable to set breakpoint" issues.

Can't set breakpoints in PHP (#112300)
Add breakpoint inside Search editor view (#112132)
Breakpoint not working (#110375)
Node debugging: Breakpoints are verified (#67644)

**Comment by usernamehw** [comment]
There was a bug that active line highlighting was depending on `editor.renderLineHighlight` setting which was fixed #84772.

It highlights the line number with the cursor. In this case it's on the line **3** (selection includes newline symbol and ends there)

**Comment by Eldaw** [comment]
@bubbajames-docker 
The reason is because the bold line number is not showing you where you have text selected. It's showing you where the text caret is. If you click Line number 2, the text on line 2 is selected, and the text cursor/caret is on line 3. In other words, Line 3 is now the active line. So it looks correct to me.

**Comment by alexdima** [comment]
I can confirm, this is working as expected. The bold line numbers renders where the cursor is (the `I`).
