### ISSUE TITLE
"Running 'File <operation>' participants" after November 2020

### ISSUE THREAD

**Issue by jcamden** [microsoft/vscode#112363]
Issue Type: <b>Bug</b>

<b>Reproducible steps (1... 2... 3...) that cause the issue:</b>

1. Disable all extensions.
2. Open an empty directory as a new workspace.
3. Carry out any file operation (e.g. "move," "rename") through the explorer.

<b>What you expected to see, versus what you actually saw:</b>

Expected: not to see a lingering toast which reads: "Running 'File {operation}' participants". 
Saw: a lingering toast which reads: "Running 'File {operation}' participants". 

<b>Images, animations, or a link to a video showing the issue occurring</b>
![Screenshot_2020-12-14_10-52-36](https://user-images.githubusercontent.com/5461045/102103107-92dce300-3dfa-11eb-874d-6b63700a32aa.png)

<b>Version of VS Code, Your operating system, List of extensions that you have installed:</b>

VS Code version: Code - Insiders 1.53.0-insider (76436a4d43566cd313629799e2ec51b4d00caa64, 2020-12-11T17:35:42.622Z)
OS version: Linux x64 5.8.0-33-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 3900)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 3, 2|
|Memory (System)|31.28GB (26.13GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 2c0db040-729f-4c24-bd46-fb046b362a7e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2promptcf:30219163
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by yamafaktory** [comment]
Got exactly the same here:

```
Version: 1.53.0-insider
Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
Date: 2020-12-11T17:35:42.622Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Linux x64 5.4.80-2-MANJARO snap
```
Insiders is now completely unusable at the moment: e.g. no TypeScript types displayed anymore, source control broken, a bunch of extensions are simply not working at all.

**Comment by jcamden** [comment]
Perhaps I should have commented that I edited the issue when it was first flagged as "needs more info." The issue report was complete for nine days before it was closed. Maybe it's a duplicate now, and it's a moot point.
