### ISSUE TITLE
Settings popup menu

### ISSUE THREAD

**Issue by yaowenzhou** [microsoft/vscode#112341]
Issue Type: <b>Feature Request</b>

The width of the menu panel that pops up by clicking the setting button in the lower left corner under windows and linux is not the same, the two ends are aligned under windows, and only part of the two ends are aligned under linux

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

**Comment by roblourens** [comment]
Sorry what do you mean by the "the two ends are aligned"?

**Comment by sbatten** [comment]
@yaowenzhou Linux by default is using native context menus. We don't have the ability to align like that with native menus. Our custom context menus on linux do behave like windows however.
