### ISSUE TITLE
"Go to Definition" should go to existing splitting window

### ISSUE THREAD

**Issue by xnervwang** [microsoft/vscode#112378]
If I have two split windows, like left is header file and right is source file, when I do CTRL+click or F12 in source file window, I hope it can jump to the left window to find the function/variable definition in my left window rather than openning the header file again in my right window. It means, if the destination file is already opened in one of split windows, don't open it again in current split window. Is it possible to make this configurable at least?

**Comment by jrieken** [comment]
This setting: `workbench.editor.revealIfOpen`
