### ISSUE TITLE
unexpected '>' in markdown input with '<'

### ISSUE THREAD

**Issue by MuYunyun** [microsoft/vscode#112388]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. create a markdown file.
2. input with '<'
3. it will auto fill with ">" without to be expected.

![Screen Recording 2020-12-13 at 18 26 19](https://user-images.githubusercontent.com/19354791/102010005-25876e80-3d76-11eb-9452-df7e5290ed20.gif)

Is there any config to ban this behaviour?

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by-design since markdown supports HTML content

Disable auto closing brackets if you don't want this behavior

**Comment by MuYunyun** [comment]
@mjbvz  thanks, I know. 

But sometimes I want to write  `1 < 2` in markdown, it'll be auto filled with `1 <>`, then I must delete the `>` then input 2, it'll be depressed.
