### ISSUE TITLE
Icon picker should have a last entry to search for icon packs on the marketplace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11231]
Similar to how we show this for themes:

<img width="645" alt="screen shot 2016-08-30 at 18 42 47" src="https://cloud.githubusercontent.com/assets/900690/18098216/92f2ac4a-6ee1-11e6-8c1f-21c70af9020e.png">

**Comment by seanmcbreen** [comment]
Very cool - I suggest we use a query like this:

Extension Name: Seti Theme
Category: Theme
Tag: Icon

Specifically:

category:themes tag:icon

Which results in...

https://marketplace.visualstudio.com/search?term=category%3Athemes%20tag%3Aicon&target=VSCode&sortBy=Downloads

cc: @waderyan @joaomoreno

**Comment by aeschli** [comment]
I added it. For now it searches for category:themes until we have a way to differentiate between icon and color themes.
