### ISSUE TITLE
Weird things in Powershell Terminal

### ISSUE THREAD

**Issue by Tomtilla** [microsoft/vscode#112304]
I was executing the "script.py" with the "art.py" file, for this you need the colorama and tkinter libraries and as soon as I execute the script, some of the output is printed in diagonal lines have a look at it...

[Desktop.zip](https://github.com/microsoft/vscode/files/5680329/Desktop.zip)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
