### ISSUE TITLE
Webview still pasting twice on input/textarea elements with caps lock

### ISSUE THREAD

**Issue by mheuzey** [microsoft/vscode#112322]
#101946 and #102805 have been locked, so I'm opening a new issue. Similar to those, pasting in a webview pastes twice. Those issues claim that 1.47.2/1.48 fixed the problem. However, it still occurs when caps locks is on. 

Unlike #101946, double cut does not occur. However, double undo/redo does occur. With caps lock off, ctrl-x and ctrl-y will undo and redo the correct amount of text that should have been pasted, whereas with caps lock on, they undo/redo the whole amount that was double-pasted.

Tested on both regular and insiders builds.

Version: 1.52.0-insider (user setup)
Commit: dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66
Date: 2020-12-10T17:20:40.435Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Download the vscode extension samples: (https://github.com/microsoft/vscode-extension-samples.git)
2. Modify the html in the cat coding webview sample to have a <textarea>
3. Run the cat coding webview
4. Paste some text into the text area using ctrl-v while caps locks is on.

Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (2.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanel:30233467

```

</details>

**Comment by mjbvz** [comment]
Hm, does not seem to happen on MacOS but does happen on Windows
