### ISSUE TITLE
Replace with newline works only when regex mode is on

### ISSUE THREAD

**Issue by bootstraponline** [microsoft/vscode#11237]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Find text and replace with \n
2. Literal \n is used instead of a newline

**Input**

<img width="500" alt="input_vscode" src="https://cloud.githubusercontent.com/assets/1173057/18100800/56b2ee1a-6eba-11e6-9837-497a1ff0b3fd.png">

**Actual**

<img width="511" alt="actual_vscode" src="https://cloud.githubusercontent.com/assets/1173057/18100807/5bfc71b6-6eba-11e6-8b43-a8afb5a3abae.png">

**Expected**

<img width="511" alt="expected_vscode" src="https://cloud.githubusercontent.com/assets/1173057/18100823/60d4aabe-6eba-11e6-8d45-be0dff974265.png">

Regex mode works as expected however I'd rather not have to define a regex.

**Comment by alexandrudima** [comment]
When the regex flag is on, then we parse the replace string:
* `\n` => LF
* `\t` => TAB
* `\\` => `\`

So you would expect that we should always parse the replace string... That would make sense, my only concern is that it might cause some grief to folks that got used to it being "literal" when not in regex mode.

**Comment by bootstraponline** [comment]
> my only concern is that it might cause some grief to folks that got used to it being "literal" when not in regex mode.

If they want the literal, I think `\\n` is a better syntax. This allows both use cases.

**Comment by hashhar** [comment]
I would like to chime in with how some other editors handle this.

The most elegant method is used by vim. They have a special prefix which tells the search to treat special characters as special. But by default they treat all characters as literals.

Atom also treats as literal unless you turn on regex mode and emacs behaves the same way. So I think that the current way is more common to the users and should be left as it is.

Just my 2 cents.

**Comment by alexandrudima** [comment]
So now I'm in a pickle :) ... I don't have a preference either way and it looks like editors have done it before both ways.

**Comment by bootstraponline** [comment]
I think it's weird to only support literals in regex mode when the user does not want to define a regex. Maybe make it an option and keep the existing behavior as the default?

**Comment by hashhar** [comment]
I agree with what @bootstraponline is saying. Ensuring that the new behaviour doesn't differ much from current behaviour is important from a user's perspective. Not everybody reads release notes.

**Comment by sebas-w** [comment]
Is there any idea of when/if this may be added or altered in Visual Studio Code? looks like it's going on 2 years now so my hope is low.

**Comment by bootstraponline** [comment]
I think it'll be up to someone from the community to send a pull request. 🙂
