### ISSUE TITLE
Extensions forcing the output panel to show up unexpectedly is getting out of hand

### ISSUE THREAD

**Issue by juliohm1978** [microsoft/vscode#112345]
A number of issues have been reported already from people complaining that the Output panel keeps coming up and grabing focus away from the keyboard. Reports date back to a few years now (https://github.com/microsoft/vscode/issues/31474).

A couple of examples:
![image](https://user-images.githubusercontent.com/4145456/101971059-29e44800-3c0d-11eb-8630-49dda015f6b0.png)

![image](https://user-images.githubusercontent.com/4145456/101971064-310b5600-3c0d-11eb-8d82-a1861fe2ef9c.png)

This happens unexpectedly everytime a file is opened or when something happens that's handled by the extension (ie: compilation errors, warnings, deprecated apis, outdated tools, you name it).

The fact that extension developers need to explicitly specify `preserveFocus: true` makes for an awkward default. The list keeps growing, and it is becoming unaccetable to ask vscode users to keep opening issues to extension developers across the board telling them their extensions are misbehaving.

Ideally, a global setting to prevent this panel from popping up automatically would also be available. Arguably, it should never grab focus, unless explicitly told to.

Please consider changing the default.

Thank you!

**Comment by sandy081** [comment]
/duplicate 

https://github.com/microsoft/vscode/issues/105270
