### ISSUE TITLE
Build: Darwin arm64 rebuild binaries should be in cache

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112319]
https://github.com/microsoft/vscode/blob/d819caf1d27650eb1171657339ffe68726c7a5af/build/azure-pipelines/darwin/product-build-darwin.yml#L120-L131

@deepak1556 Shouldn't these be in the node_modules build cache as well?

Also, since we're looking into reducing build time... it seems like we first build them... and then we rebuild them. Any chance we can build them right the first time?

**Comment by deepak1556** [comment]
The cross compilation was not working correctly with yarn, so had to electron-rebuild which walks down the node_modules folder and rebuilds only the native modules. Haven't checked if the problem still persists, will check.

**Comment by deepak1556** [comment]
This is completed.
