### ISSUE TITLE
Ctrl-E, Ctrl-Y doesn't work if the file is no more than one page long

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11232]
Testing #11127

- VSCode Version: 1.5.0-Insiders
- OS Version: OSX

Steps to Reproduce:

1. Open a file with few content, like just three lines
2. Run `ctrl-e` on the second line

The line should be moved upward, but right now it does nothing.

**Comment by joaomoreno** [comment]
I don't have `ctrl y` as a default keyboard shortcut.

How to verify?

**Comment by sandy081** [comment]
This need to set up sample Vim extension as described in #11127. I would suggest @rebornix to verify this.

**Comment by octref** [comment]
@sandy081 
Hi I'm also working a bit on the Vim extension. I was able to verify:

- <kbd>ctrl</kbd> + <kbd>e</kbd> Scroll window 1 line downwards
- 🔢 <kbd>ctrl</kbd> + <kbd>e</kbd> Scroll window N lines downwards
- <kbd>ctrl</kbd> + <kbd>y</kbd> Scroll window 1 line upwards
- 🔢 <kbd>ctrl</kbd> + <kbd>y</kbd> Scroll window N lines upwards

Adding `verified`.

**Comment by rebornix** [comment]
This command works perfectly with VSCodeVim now (after we did a little hacking to VSCodeVim's mechanism). @sandy081 thanks for all the contribution and turnarounds, we made it as we promised at the beginning.
