### ISSUE TITLE
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 259.         Help me please

### ISSUE THREAD

**Issue by iamashish0** [microsoft/vscode#112355]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

I am facing problem in vs code whenever i click on Terminal ,it not open and show 
  
 The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 259  
This.

how i resolve this please help
![Screenshot (1)](https://user-images.githubusercontent.com/75880081/101980880-83547300-3c1d-11eb-98e2-a22e8a40c616.png)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

also, what version of VS code are you on?

**Comment by chghulamnabi** [comment]
WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 259.

**Comment by chghulamnabi** [comment]
Visit this link to find its solution.
https://webautomationtool.blogspot.com/2021/01/the-terminal-process.html
