### ISSUE TITLE
Unable to perform tasks

### ISSUE THREAD

**Issue by akscool** [microsoft/vscode#112365]
In my VS code, none of the popups are showing up. For example, if i click on the 'open folder' button which is supposed to open a popup, nothing happens on clicking. Similarly trying to delete/move a file does not work as they are supposed to show a popup asking me to confirm the same.

**Comment by adroitwhiz** [comment]
Why did you close this issue? Did you manage to find a fix for this?

**Comment by shawnee247** [comment]
No I’m just unable to fix the issue it needs to be done externally I can’t do it manually cuz I have no access

**Comment by adroitwhiz** [comment]
That's what this issue tracker is for--reporting issues. All you need to do is provide information on how the issues manifest themselves; you're not expected to fix them yourself.

**Comment by akscool** [comment]
It started working after a few restarts. So, I closed the SR
