### ISSUE TITLE
Word wrap doesn't work well with control characters

### ISSUE THREAD

**Issue by JayXon** [microsoft/vscode#112382]
- VSCode Version: 1.52.0
- OS Version: windows 10

Steps to Reproduce:

1. enable word wrap
```
"editor.wordWrap": "on"
```

2. type a long line with control characters in it, for example ``

3. observe that horizontal scroll bar shows up

![image](https://user-images.githubusercontent.com/1552641/102002204-0b368d80-3caf-11eb-9c22-3aeb48f0b736.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
The default word wrapping algorithm assumes (mostly) that all characters have the same width. You can change that (at the cost of performance) with `"editor.wrappingStrategy": "advanced"`, which will give more accurate wrapping results, but will be slower, especially for large files.

**Comment by JayXon** [comment]
Thanks for the reply, I wasn't aware of that setting, after changing it to advanced, it did help in some cases, however, I'm still seeing horizontal scroll bar if the entire line is control characters.

**Comment by alexdima** [comment]
@JayXon Here I have tried with the following settings:
```
    "editor.wordWrap": "on",
    "editor.wrappingStrategy": "advanced",
    "editor.renderControlCharacters": true
```

But this is the rendering I get:
![image](https://user-images.githubusercontent.com/5047891/102059573-5d7fc780-3df1-11eb-95e8-4b18e66c087b.png)

Do you perhaps use a custom font family that would render that specific control character better?

**Comment by JayXon** [comment]
Looks like github automatically replaced the character with the replacement character, when I copy it back it also shows up like that. This character is `\x06`, you can get it yourself by opening browser console and put `'\x06'`, and copy from the output.
![image](https://user-images.githubusercontent.com/1552641/102061620-8d56ad00-3da8-11eb-9dee-9205795e1469.png)

For the font I was using DroidSansMono, but I tried changing back to the default consolas and can still reproduce.

**Comment by JayXon** [comment]
If I turn off renderControlCharacters and set wrappingStrategy to advanced, then I can no longer reproduce.
```
    "editor.wrappingStrategy": "advanced",
    "editor.renderControlCharacters": false
```

**Comment by alexdima** [comment]
Thank you, I could reproduce. The substitution characters for control characters are often wide, so I will adjust the char width computation to assume that these characters are wide.

**Comment by aeschli** [comment]
@rzhao271 Should the issue be reopened then?

**Comment by alexdima** [comment]
@rzhao271 This works for me. When using `advanced` I don't see a scrollbar:
![image](https://user-images.githubusercontent.com/5047891/106297409-f60fc100-6252-11eb-8e82-4dc8f8ef1583.png)

**Comment by rzhao271** [comment]
I think there's a settings sync bug, but one can still see the ACKs don't wrap whereas the substitution character does.

ACKs:
![bad-ack](https://user-images.githubusercontent.com/7199958/106305270-52ea8780-6211-11eb-8987-0bc835bead42.gif)

Substitution characters:
![good-control](https://user-images.githubusercontent.com/7199958/106305316-64cc2a80-6211-11eb-8dc5-0ddd089d79b7.gif)

**Comment by alexdima** [comment]
@rzhao271 Thank you, I could reproduce with `ACK` and `"editor.wrappingStrategy": "advanced"`
