### ISSUE TITLE
Unable to set breakpoint in v1.52.0

### ISSUE THREAD

**Issue by bubbajames-docker** [microsoft/vscode#112328]
- VSCode Version: 1.52.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open file you want to set breakpoint in.
2. Hover cursor over line number.

Result: 
No red dot appears to left of line number and cannot set breakpoint.

Expected:
Red dot appears to left allowing you to set breakpoint.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bubbajames-docker** [comment]
Sorry, seems to be duplicate of #110375

**Comment by misolori** [comment]
@bubbajames-docker thanks for letting us know!
