### ISSUE TITLE
Comparing two selected files should not open in "preview" mode

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode#112334]
When you select two files in the explorer and compare them to each other, it shouldn't be so easy to lose that comparison view.  Comparing is an explicit action and the editor should open in non-preview mode so it doesn't get closed, forcing the user to go reselect the same files and compare them again.

**Comment by bpasero** [comment]
This has been implemented in our current release.

**Comment by JaPyR** [comment]
@bpasero, is there setting to bring preview back for comparing files?
