### ISSUE TITLE
Resizable Suggestion Detail Widget cover the original Suggestion Tree Widget

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/vscode#112390]
- VSCode Version: 1.52
- OS Version: Win 10, 2004

Steps to Reproduce:

1. `Ctrl+Space` to open suggestion(if there's no *detail widget*, press `Ctrl+Space` to open it)
2. resize the suggestion *tree widget* to become wider and wider, when the widget is wide enough, suddenly, the *detail widget* will **cover** the *tree widget*.

As the gif shown below.
[Twitter Post](https://twitter.com/i/status/1338086725994901505)

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

**Comment by jrieken** [comment]
please provide a gif that shows the whole window

**Comment by JoeyRxy** [comment]
> please provide a gif that shows the whole window

![fullscreen_gif](https://github.com/JoeyRxy/tmp/blob/master/vscode_bug_full.gif)

**Comment by jrieken** [comment]
please provide a gif that shows the whole window

**Comment by JoeyRxy** [comment]
> please provide a gif that shows the whole window

I've post a full screen gif. you can visit the link. No way and no need to show you total screen. I have told you how to reproduce the problem, why don't you try it? What's the problem with you? are you an AI, which only can repeat words? or you want to avoid the problem? if so, then don't waste other's time and close this issue, I would not waste my time with your perfunctoriness.
