### ISSUE TITLE
Double Click  in Explorer show Rename 

### ISSUE THREAD

**Issue by hosseinse1919** [microsoft/vscode#112379]
i requested items double click on explorer shown rename to me like windows 

double click with little delay  show rename

**Comment by isidorn** [comment]
We will not do this, double click in explorer already opens editor and moves focus to it.
Changing that would break the pattern of a lot of users.

Thus closing as designed

**Comment by hosseinse1919** [comment]
it is not quick double click  it is :  click ---- delay for one sec ---- click again . 
anyway for me i think it can be handle via extension ... thanks . 

but all apps are like this .
