### ISSUE TITLE
circle-large-outline is too thick

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#112310]
I thought of using this codicon in a Tree View along with `pass` to represent 2 states. But the `circle-large-outline` has different line-width.

I think all the other large circle-like icons have the same width except this one.

![Screenshot (398)](https://user-images.githubusercontent.com/9638156/101936571-c00a7500-3bf1-11eb-8983-fafea52b470d.png)

![Screenshot (397)](https://user-images.githubusercontent.com/9638156/101936581-c39dfc00-3bf1-11eb-8425-63782b18f20b.png)

**Comment by misolori** [comment]
This was a larger version of `circle-outline` which uses a 2px line width used in unverified breakpoints. I can tweak it so it can be used interchangeably with other circle icons.
