### ISSUE TITLE
Scrolling in editor hover causes it to disappear

### ISSUE THREAD

**Issue by sploders101** [microsoft/vscode#112373]
- VSCode Version: 1.52.0
- OS Version: Darwin x64 19.6.0

When scrolling in the info panel that appears when hovering over code or errors, it disappears entirely if you scroll near the bottom. This makes it extremely frustrating to try and look at errors, because they disappear before you can see them.

![Info panel scrolling mov](https://user-images.githubusercontent.com/26530958/101993986-18865480-3c7c-11eb-9004-7827c63d0e3b.gif)

Steps to Reproduce:

1. Write a function with a large documentation page (easiest method is using JSDoc)
2. Mouse over function and try scrolling to the bottom of documentation (where error and warning messages usually appear)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sploders101** [comment]
For anyone else experiencing this issue, it appears the scroll bar still works, so you can drag the handle to the bottom and see it if you're careful not to move your mouse out of the panel. It's less than ideal, but works if you really need to get work done.

**Comment by huntedman** [comment]
Happens on Mac Os Mojave 10.14.6 also. Happens to all hover windows. Impossible to debug anything.

**Comment by SiAce** [comment]
Same in macOS Catalina 10.15.7.
Besides, if you are not at the top of your file (your file scrollbar is not at the top), and if you try to scroll up in these panels and when the scrollbar in the panel reach the top, the panel will also disappear.

**Comment by sploders101** [comment]
If it's any help, it looks like the panel allows you to scroll all the way to the bottom with a scroll *wheel*, but one click further and it goes away. I would imagine this regression was made as an attempt to curb the impact of panels when trying to scroll the *document*, but it fails with smooth scrolling, because it sends significantly more events to the element than a normal scroll wheel. I would venture to guess this is an issue on Windows laptops as well with high-precision touchpad drivers as those handle smooth scrolling in Chromium in much the same way.

**Comment by mattwelke** [comment]
Lol I specifically tried searching for duplicates before making my issue (https://github.com/microsoft/vscode/issues/113348), but I didn't know how to describe it. I closed my issue as duplicate.

**Comment by susiwen8** [comment]
[this line cause issue](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/hover/hover.ts#L120)

**Comment by susiwen8** [comment]
![Kapture 2020-12-24 at 22 44 30](https://user-images.githubusercontent.com/20318608/103094854-adecf580-4639-11eb-9e3d-ada2dc79f36c.gif)

This is what I have achieve so far, Could I submit a PR?

**Comment by alexdima** [comment]
PR welcome

**Comment by hangacs** [comment]
@susiwen8 I think you should test long documentation which has a scroll bar, because we have to scroll when read them and it's easy to scroll beyond buttom or top which causes popup to disappear.

**Comment by susiwen8** [comment]
@hangacs Sure, I have tested scroll bar in hover widget case. It works so far.

**Comment by hangacs** [comment]
@susiwen8 Great work! I expect yout fix on next update.

**Comment by hangacs** [comment]
@susiwen8 I read the blame and found that line fixed a problem https://github.com/microsoft/vscode/pull/52147#issue-195405577. Maybe there are some other work to do.

**Comment by susiwen8** [comment]
@hangacs Thanks!!! that was a helpful info. I'll take a look on that.

**Comment by JKAnderson409** [comment]
I rolled back to the [October version](https://code.visualstudio.com/updates/v1_51) to get around this problem for the time being. If you do that make sure updates are set to use the setting `"update.mode": "manual"` to prevent VS Code from updating itself.

**Comment by andrewbihl** [comment]
Is this going to be fixed? I don't see the reason for closing the issue.

**Comment by sploders101** [comment]
> Is a fix planned here? I don't see the reason for closing the issue.

I'm seeing the issue is still open. It will auto-close when an associated PR is merged though

**Comment by goulkreek** [comment]
Same annoying behavior on VSCode 1.52.1.

Please merge PR ;-)

Here are `VSCode About details`:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (3 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

**Comment by RyanNtrce** [comment]
Was this resolved?

**Comment by runofthemill** [comment]
@RyanNtrce just from looking at the labels, it looks like it's been fixed in the insider release...so hopefully it'll go into a stable release soon!

**Comment by RyanNtrce** [comment]
@runofthemill Sweet! I'm really looking forward to seeing this in the next release!

**Comment by fakhamatia** [comment]
Is my issue link to this issue?

When I use scroll and if scroll bar reaches the end of scrollbar vscode scroll text editor , sorry for bad English

![Peek 2021-01-20 12-11](https://user-images.githubusercontent.com/20030910/105150326-e0472100-5b19-11eb-8415-7e4ab61be66f.gif)

**Comment by hasezoey** [comment]
@fakhamatia yes seems like this exact issue

**Comment by gazcn007** [comment]
Would love to see the fix soon :) Thanks for working on the issue

**Comment by smeyerhot** [comment]
Is there a PR we are waiting for?

**Comment by sploders101** [comment]
> Is there a PR we are waiting for, why is this closed?

A PR was merged. We are waiting on an official release.

**Comment by ruojianll** [comment]
Same issue, waiting for release.

**Comment by alexdima** [comment]
The fix is already released in [VS Code Insiders](https://code.visualstudio.com/insiders/)
