### ISSUE TITLE
Prettier is not working

### ISSUE THREAD

**Issue by arunmatics** [microsoft/vscode#112399]
Issue Type: <b>Bug</b>

prettier is not working or functioning well after upgrade with 1.52.0

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0

<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
ng-template|Ang|0.1100.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.13
githistory|don|0.6.14
gitlens|eam|11.0.6
vscode-html-css|ecm|1.1.2
tslint|eg2|1.0.44
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.5
rest-client|hum|0.24.4
vscode-docker|ms-|1.8.1
vscode-typescript-tslint-plugin|ms-|1.3.0
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
vscode-manifest-yaml|Piv|1.23.0
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.2
rcore-unused-css-classes|rco|0.1.7
LiveServer|rit|5.6.1
local-history|xyz|1.8.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30233462

```

</details>

**Comment by sandy081** [comment]
Since it is related to Prettier extension, I would recommend to file the issue against the extension first and let them know what exactly is not working so that they can diagnose and fix it, if it is on their side, otherwise they can create exact issue with us that what is not working with VS Code.
