### ISSUE TITLE
[1.52] Release notes mangled. Again.

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#112343]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6532485/101969579-1ac5c000-3c36-11eb-8e30-65a817b9d800.png)

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.23GB free)|
|Process Argv|\\\\DAEMON-EC.DARKDRAGON.LAN\\anrdaemon\\Documents\\caduceus\\bach-x5-gui --crash-reporter-id d05c8b79-33ba-42b6-8c5c-db1f4b0e913c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
php-debug|fel|1.13.0
todo-tree|Gru|0.0.192
composer|ika|0.7.1
sqltools|mtx|0.23.0

</details>

**Comment by mjbvz** [comment]
Works for me on Mac:

<img width="710" alt="Screen Shot 2020-12-14 at 3 41 07 PM" src="https://user-images.githubusercontent.com/12821956/102149229-cf243980-3e22-11eb-9733-83711bd52457.png">


And windows:

<img width="669" alt="Screen Shot 2020-12-14 at 3 42 06 PM" src="https://user-images.githubusercontent.com/12821956/102149288-ee22cb80-3e22-11eb-9dfa-65dd7f2a7cec.png">


Any more details? Does this happen with extensions disabled? Do you have a custom keybinding for smart select?

**Comment by AnrDaemon** [comment]
Of course I do. Alt+BackSlash.
Seems much like #105494

In what other places you do not quote the text properly? Awaiting for injections?

**Comment by connor4312** [comment]
ping @mjbvz for steps

**Comment by mjbvz** [comment]
@connor4312

1. For a keybinding used in the release notes
2. Change it locally to use backslash

**Comment by connor4312** [comment]
This is challenging on Insiders since the insiders release notes don't have keybindings

**Comment by mjbvz** [comment]
To verify in oss:

1. Apply

```
diff --git a/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts b/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
index fa486e25497..d0820bae5f4 100644
--- a/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
+++ b/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
@@ -98,6 +98,7 @@ export class ReleaseNotesManager {
 	}
 
 	private async loadReleaseNotes(version: string): Promise<string> {
+		version = '1.52.0';
 		const match = /^(\d+\.\d+)\./.exec(version);
 		if (!match) {
 			throw new Error('not found');
```

2. Then run the `show release notes actions`
3. You can use the `Delete Word command` to test in the 1.52 notes
