### ISSUE TITLE
Pressing Ctrl + Shift + P in file list dialog should not filter files for 'p' but open command palette

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#112371]
Sometimes when trying to open the command palette I press Ctrl + P by accident instead of Ctrl + Shift + P. It would just a bit more convenient if I could open the command palette from within the file dialog without needing to press Esc before.

Acceptance criterion:
1. Press Ctrl + P
2. Press Ctrl + Shift + P
3. Command Palette is visible.

**Comment by bpasero** [comment]
You can try to remove the keybinding:

```json
{
    "key": "ctrl+shift+p",
    "command": "-workbench.action.quickOpenNavigatePreviousInFilePicker",
    "when": "inFilesPicker && inQuickOpen"
}
```
