### ISSUE TITLE
Extension Development: HTML Canvas in Webview only shows once

### ISSUE THREAD

**Issue by JonasSchatz** [microsoft/vscode#112396]
- VSCode Version: 1.52.0
- OS Version: Windows 10

Steps to Reproduce:
- Clone the demo repository I created (https://github.com/JonasSchatz/webviewBugDemo) and open it in VS Code
- Run the extension (F5)
- In the _Extension Development Host_, run the `WebviewDebugDemo: Show Graph` command (Ctrl + Shift + P). You should see a graph visualization:
<img width="960" alt="working" src="https://user-images.githubusercontent.com/13544864/102012226-703ec180-3d49-11eb-83d0-8a7644d22f09.PNG">
- Close the webview and run the same command again. The graph visualization will, unexpectedly, not be rendered to the Webview. However, if you open the Webview Developer Tools, you will still see the message `force-graph loading 300 nodes 299 links` printed into the console, even though no graph is visible.
<img width="960" alt="notworking" src="https://user-images.githubusercontent.com/13544864/102013337-b39c2e80-3d4f-11eb-804a-945547af99c3.PNG">
- I had to restart my whole computer every time I wanted to see the visualization.   

About the Demo:
All of the data for the Webview can be found in the `static` folder of the repository. 
It contains a `graph.js` file, which just contains the copy-pasted demo code from the force-graph Javascript library (https://github.com/vasturiano/force-graph, first item in the list of examples). It builds on D3's force-graph, but renders to a HTML canvas instead of an svg, which MIGHT be the problem. I'm not an export on the HTML canvas, though, which is why I could not debug it. I had to switch from D3 to another library that can handle bigger force graphs due to performance issues. 
There is also a `dataviz_local.html` file which you can open in your browser. It uses the same javascript files, but with hardcoded locations, so that you can see what it should look like. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Without further evidence, this sounds like an issue with your extension or the libraries you are using. 

Please try narrowing down what doesn't work. If this really turns out to be a VS Code problem, then provide a minimal example that demonstrates the problem

**Comment by JonasSchatz** [comment]
mjbvz was right, it was NOT a problem with VS Code. 

For anyone stumbling upon this problem in the future: When using the force-graph library as a part of your VS Code extension, you need to build it, which will give you a `force-graph.x.y.z.min.js` file. However, you also need to provide d3 (e.g. as `d3.v6.min.js`). force-graph will not complain about the missing dependency, it just won't show any data. 

Caching made this a very tricky thing to detect. When testing in my browser, I still had d3 cached, so it worked without a problem. I expected VS Code to create completely empty webviews, but apparently there was some spillover, and sometimes it had a cached instance of D3 flying around somewhere, but not after closing and re-opening the webview.

**Comment by pelumiojebode** [comment]
Setting up Account and finalization
