### ISSUE TITLE
Typescript interpreter cannot infer function call  or previous checks

### ISSUE THREAD

**Issue by RyannnnnnR** [microsoft/vscode#112358]
Issue Type: <b>Bug</b>

I have this Typescript code:
```ts
function isNotNull (obj: any) {
    return obj !== null && obj !==  undefined
}
pointBorderColor: context => {
             let dataSet = context.dataset?.data
             let index = context.dataIndex
             let dataPoint = isNotNull(dataSet) ? dataSet[0] : null;
             if (!isNotNull(dataPoint)) return '';
             return dataPoint > 100 ? 'green' : 'red'     
},
```
I keep getting a red squiggly line underneath `dataSet[0]` and subsequently `dataPoint` stating:  
```
let dataSet: (number | number[] | null | undefined)[] | Chart.ChartPoint[] | undefined
Object is possibly 'undefined'.ts(2532)
```
![image](https://user-images.githubusercontent.com/26314009/101983059-472c1b80-3ccc-11eb-8742-12d4f30b7d53.png)

Playing around  with this more, something like this **WORKS** and the red squiggly line goes away:
```ts
let dataSet = context.dataset?.data
let index = context.dataIndex
let dataPoint = dataSet !== null && dataSet !==  undefined ? dataSet[0] : null;
```
Another interesting thing I discovered:
```ts
 pointBorderColor: context => {
             let dataSet = context.dataset?.data
             let index = context.dataIndex
             if (!dataSet || !index || !dataSet[index]) return ''
             return dataSet[index] > 100 ? 'green' : 'red'     
},
```
![image](https://user-images.githubusercontent.com/26314009/101983162-2b754500-3ccd-11eb-8a50-aa9230ceecfa.png)

In this code example; `dataSet[index]` reports the same error as above  even though in the check before we are checking for undefined and null states?

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 024407c9-22e6-4008-bfa2-daf0b2c2c88d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
nestjs|ash|1.4.2
vagrant|bbe|0.5.0
vscode-intelephense-client|bme|1.5.4
vscode-tailwindcss|bra|0.5.5
vscode-dash|dee|2.4.0
es7-react-js-snippets|dsz|3.0.0
prettier-vscode|esb|5.8.0
nasc-touchbar|fel|1.12.0
code-runner|for|0.11.1
go|gol|0.19.1
gc-excelviewer|Gra|3.0.40
vscode-JS-CSS-HTML-formatter|lon|0.2.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.7
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.0
cpptools|ms-|1.1.3
vscode-typescript-tslint-plugin|ms-|1.3.0
color-highlight|nau|2.3.0
vetur|oct|0.31.2
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.4.0
java|red|0.72.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.1.5
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.15.0
vscode-java-pack|vsc|0.12.0
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.26.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30233461
pythonvspyt600cf:30228412
vsjup459:30229593

```

</details>

**Comment by mjbvz** [comment]
This is a question about TS, not VS Code

The problem is likely that `isNotNull ` needs to use an explicit type guard: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

**Comment by RyannnnnnR** [comment]
Thanks for the response.

How would you explain the fail fast check still returning the null or undefined error? Can TS not infer that the object was just checked?
