### ISSUE TITLE
Unable to add breakpoints on 1.52.0

### ISSUE THREAD

**Issue by cristian3d** [microsoft/vscode#112325]
Using C# on Windows. I can't add breakpoints using either F9 or the direct command works. Conditional breakpoints doesn't work either. It was working before I updated.

**Comment by slushman** [comment]
I'm seeing the same. Trying to debug PHP on Mac OS X (10.15.7).
Maybe this would work for you too? https://github.com/felixfbecker/vscode-php-debug/issues/424#issuecomment-743334478

**Comment by cristian3d** [comment]
@slushman that worked, thanks! In my case I had to make the change in the unity debug extension

**Comment by cristian3d** [comment]
Since it seems the previous answer from slushman was removed, and other people might be finding this problem, the solution is:

https://github.com/felixfbecker/vscode-php-debug/issues/424#issuecomment-743334478
