### ISSUE TITLE
The popup of Alt Right Clicking on an item in the Explorer disappears immediately after releasing the Alt key

### ISSUE THREAD

**Issue by cateyes99** [microsoft/vscode#112347]
- VSCode Version: **_1.51.1 zip 64 bit_**, & **_1.52.0 zip 64 bit_**
- OS Version: **_Windows 10 Enterprise_**

Steps to Reproduce:

1.  In previous versions, e.g., `1.50.1` From the Explorer, **press** & **hold** <kbd>alt</kbd>, then **right click** on a file or a folder. It shows up a popup as below. After I release <kbd>alt</kbd>, the popup remains there, unless I click on some option from the popup, or press <kbd>esc</kbd> to cancel it.
![image](https://user-images.githubusercontent.com/19678455/101975422-5053c300-3ca1-11eb-87e5-3ef2f61341f6.png)

2. But in `1.51.1` or `1.52.0`, do the same, now when I release <kbd>alt</kbd>, the popup disappears immediately. That isn't convenient. 👀

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@isidorn I think this has to do with the alt-key modifier merging we did. the menubar is getting focus in a case that it didn't before which is why the context menu is getting dismissed. I'll take a look.

**Comment by isidorn** [comment]
@sbatten great, thanks for taking a look. Let me know if I can help

**Comment by sbatten** [comment]
@isidorn not sure how this behavior changed but the repeating keydown events were ruining the lastKeyPressed logic

**Comment by isidorn** [comment]
Might be electron related... I have no other explanation

**Comment by sbatten** [comment]
@isidorn I now know why this happened and I am writing here to document. When we merged, it was necessary for you to reset the key status on context menus. Prior to this, repeat events were not possible to affect our logic since the key status was already set and we never unset it unless a modifier key was pressed.
