### ISSUE TITLE
Ability to switch to previous behavior on 1.52.0 'Preview editor improvements'

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#112348]
With the November 2020 update, code navigation options do not open the navigated file in the same editor even when the current editor is in the preview mode. This quickly litters the workbench with a ton of editors when I want to drill down inheritance trees for example. If I want the navigation target to open in a new editor I can quickly get out of the preview mode with a command like `save` and then navigate so I don't understand the need for this change. I was able to use the `Go->Back` command to go to the previous editor in the preview mode already so I never lost track of where I have navigated from and this way the workbench is not littered with a ton of editors I'm not interested in. It really goes against the nature of "preview mode" in my opinion.

So my request it, please make it toggleable, I want the old behavior back. By old behavior I mean if the current editor is in preview mode and I navigate from it with commands like go to definition, open the definition file in the same editor in preview mode.

**Comment by bpasero** [comment]
This seems like a fair request to me with a new option such as `workbench.editor.enablePreviewFromCodeNavigation`. Open for grab if someone wants to contribute a PR, the change needs to go somewhere here:

https://github.com/microsoft/vscode/blob/36e28683729907cf9a74817e7d4fe3bb5a89d895/src/vs/workbench/services/editor/browser/codeEditorService.ts#L73-L90

**Comment by cateyes99** [comment]
To be honest, this change is silly it causes **so much inconvenience**. If it's in preview editor mode, it isn't hard for someone to make it in normal editor mode first and then navigate to another one, if they really want. Now as **this issue** mentioned: `This quickly litters the workbench with a ton of editors when I want to drill down inheritance trees for example.` IMHO, it's should be roll back, or if add a new option to control this behaviour then the old behaviour should be the default one.

**Comment by ssoher** [comment]
@cateyes99 agreed. why is there a preview mode in the first place if it's going to behave the same with non-preview editors. with this change the preview mode became inconsistent with no added benefit that I can think of.

**Comment by bpasero** [comment]
At least we in the team believe this to be a good change, and it was discussed in our UX meetings. We argue that it is equally confusing that an editor is replaced by the editor you are navigating to and as such you are not building up a history of navigation because all the editors open in the same location. Now, you have a trace of editors you navigated to. And the one you navigate to is opening in preview mode, so you only end up with more editors if you continue navigation.

**Comment by ssoher** [comment]
@bpasero I understand the reasoning but fail to see how turning my preview editor into a normal editor when I use go-to (which is a strange side effect) and make the preview editor behave exactly the same with a normal editor in this aspect is a better way to handle it. In the previous versions users could disable the preview editors all together or simply convert them to normal editors with a simple keyboard shortcut to achieve what is the only default now.

**Comment by bpasero** [comment]
Yup I understand and I am happy to hear from users so that we can tweak this experience. As I said before, I am all up for a new setting to control this.

**Comment by goldst** [comment]
I agree, the best way to do this is probably to let the user choose. If the vscode team would just decide to just revert the changes without adding an option, the same type of request would come from people who got used to the new behavior.

@bpasero you added the `under-discussion` label. Is there anything else to discuss? If not, I'd like to contribute the solution to this issue.

**Comment by bpasero** [comment]
@goldst yeah feel free to open a PR with that setting.

**Comment by bpasero** [comment]
A new setting `enablePreviewFromCodeNavigation` allows to configure this.
