### ISSUE TITLE
Add CTRL + Alt as an option to editor.multiCursorModifier setting.

### ISSUE THREAD

**Issue by NALStudio** [microsoft/vscode#112303]
In Visual Studio multiple selections are added using CTRL + Alt and clicking. Could this be added to VSCode?

**Comment by ArturoDent** [comment]
You can switch it from <kbd>alt</kbd> to <kbd>Ctrl</kbd> now with the setting:

 `Editor: Multi Cursor Modifier`

so you would `Ctrl+click` - almost what you want  - not sure if you were aware of that setting or if that would be sufficient?

**Comment by NALStudio** [comment]
> so you would `Ctrl+click` - almost what you want - not sure if you were aware of that setting or if that would be sufficient?

Yeah I have tested CTRL + Click, but the problem is that I want to press CTRL and ALT for the multi-cursor modifier and currently with both modes (ALT and CTRL), pressing CTRL and ALT and clicking will not work for multi-cursor.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/3130
