### ISSUE TITLE
Toggle between preset Color Themes on toggle OS Dark or Light Theme. 

### ISSUE THREAD

**Issue by michaeldera** [microsoft/vscode#112387]
When I can between Dark and Light theme on my Operating system, I would like for VS code to optionally toggle between a dark and light theme (which I can preset) in response to that change.

**Comment by aeschli** [comment]
That should already work. You can enable this by `"window.autoDetectColorScheme": true`
The preferred themes can be selected by `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`.

Linux is not yet working, we are waiting for Electron support: #102795.

Please try it out and file an issue with details if this is not working for you.
