### ISSUE TITLE
IntelliSense collapsed to 1 item only

### ISSUE THREAD

**Issue by RiperFish** [microsoft/vscode#112372]
Issue Type: <b>Bug</b>

When i type for ex : justify-content: => it should show all item, but it's only showing 1 item at a time, and i have to use arrows to select.

[Gif can be found here](https://i.imgur.com/ruaHovL.gif)

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.5.4
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
auto-rename-tag|for|0.1.5
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.0.3
sass-indented|syl|1.8.13
wordpress-toolbox|wor|1.3.8

(1 theme extensions excluded)

**Comment by twalton83** [comment]
I am also having this issue. 
VS Code version 1.52.0
Mac OSX 10.15.7 

![Hnet com-image](https://user-images.githubusercontent.com/22967723/102000771-a0318a80-3c9f-11eb-8935-c938cc725b00.gif)

**Comment by trm900** [comment]
Same problem here.

VS Code Version: 1.52.0
OS: Ubuntu 20.04.1 LTS | 64-bit

[gif](https://i.imgur.com/7dMVuif.gif)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206 for pointer to a command that resets the size.

**Comment by ArturoDent** [comment]
Since @RiperFish and @trm900 are on v1.52 and this was worked on for that release (https://github.com/microsoft/vscode/commit/c5ab321020b9a223102966d32e7c1c22aaa2a12b), perhaps this should stay open if @jrieken would like to investigate what is different here?
