### ISSUE TITLE
disable "just my code" by default

### ISSUE THREAD

**Issue by codeman101** [microsoft/vscode#112375]
I've noticed that if I go to preferences and have "just my code" unchecked it doesn't act as such until I add it to the launch.json file. `Please add a feature to have disabled by default for every new and existing project. Coming from Pycharm which has the behavior of disabling this by default I was surprised to find out that it has to be disabled manually in vscode. A lot of time I'm debugging with imported libraries that were self written and therefore need to be self modified when debugging so this feature would be very helpful.

If my issue is that each launch.json is generated for each project and therefore can't be overwritten automatically once generated then please give vs code the behavior of giving precedence to the settings set in the preferences menu over the launch.json filee.

**Comment by weinand** [comment]
VS Code has no global "just my code" setting.
Please provide more info (e.g. screenshot) about that setting.
You are using the Python debugger, right?

**Comment by codeman101** [comment]
@weinand 
My apologies I didn't notice that the menu setting I was looking at was for jupyter. I guess my feature request then is to add a just my code global setting for the python debugger.
