### ISSUE TITLE
TS(6133)

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#112391]
- VSCode Version: 1.52
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Declare a variable (javascript).
2. Decide that you want to rename it.
3. Go click on it to rename it.
4. A "quickfix" this variable is declared but never read box gets in the way so I can't change the name.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Why can't you rename it? Please share a screenshot (or, even better, a video) of what isn't working

**Comment by thebinarysearchtree** [comment]
The dialog box appears over the code, so I can't click on any of the code. I have attached a video. This only started occurring with the latest release. Something has changed, such as the algorithm to place the dialog box or the speed at which the dialog box appears.
[unused.zip](https://github.com/microsoft/vscode/files/5686639/unused.zip)

**Comment by thebinarysearchtree** [comment]
Here are some screenshots as well.
<img width="717" alt="Screen Shot 2020-12-14 at 3 30 29 pm" src="https://user-images.githubusercontent.com/960753/102043873-5b356180-3e21-11eb-97a2-7ce22fa1e48d.png">
<img width="717" alt="Screen Shot 2020-12-14 at 3 30 23 pm" src="https://user-images.githubusercontent.com/960753/102043881-5ec8e880-3e21-11eb-9d52-872cff0c8dd8.png">

**Comment by thebinarysearchtree** [comment]
It may be because of the window size, but the window size is the default size that is set when you install and open the application for the first time. I would expect it to work at that size.

**Comment by mjbvz** [comment]
@sandy081 Assigning you since this looks like a bug with the positioning of the problems hover widget

**Comment by sandy081** [comment]
I cannot repro it.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/10746682/102327803-8b4a4500-3f86-11eb-8ef7-3f2b53d57948.png">

Are there any specific steps you followed to repro this? May be you have some settings applied where I do not have or vice-versa. Is it possible to reproduce this by disabling all extensions except the extension that provides quick fixes?

**Comment by sandy081** [comment]
@alexdima Any idea why this can happen?

**Comment by thebinarysearchtree** [comment]
The only extension I have is debugger for Chrome. The only settings I have are:
```
{
    "workbench.colorTheme": "Default Light+",
    "editor.tabSize": 2,
    "extensions.ignoreRecommendations": false,
    "editor.minimap.enabled": true,
}
```

I would probably suggest making sure the window size is the default size when first installed. Maybe if the window size is larger, the algorithm will come up with a different place to put the box. Also, you may want to try javascript, as that is what I am using, not TypeScript. Also I would suggest diffing between the previous version as it didn't happen then. I am not even sure if there was a quickfix suggestion for unused vars in the previous version.

**Comment by thebinarysearchtree** [comment]
It kind of looks like the "quickfix" section is not factored into the algorithm that places the box and it is instead aligning with the box excluding that section.

**Comment by thebinarysearchtree** [comment]
<img width="525" alt="Screen Shot 2020-12-16 at 7 29 57 pm" src="https://user-images.githubusercontent.com/960753/102330370-2c5fec80-3fd5-11eb-9405-0a603a24b025.png">
The same problem occurs in TypeScript. You have "Peek Problem" which I do not have. Maybe try without whatever that is.

**Comment by thebinarysearchtree** [comment]
I cloned vscode and built it from the source. The same problem occurred. I started to debug it and confirmed my suspicion that the quick fix bar (the action bar) is not being recognised in the positioning algorithm. I altered the css of monaco to give an explicit height to the action bar and that fixed the problem. This may not be the actual fix though.

```
.monaco-hover .hover-row.status-bar {
    font-size: 12px;
    line-height: 22px;
    height: 22px; // I added this
}
```

**Comment by thebinarysearchtree** [comment]
Ok so what is happening is the dialog box and the action bar are being made visible at different times. A race condition determines whether monaco measures the height of the dialog box with the action bar visible or not. This is why the bug will not occur if you step through the code. The reason why setting the height works is that unlike line-height, height is still measured when the element is invisible. The actual solution though is most likely to ensure that the entire dialog box is made visible at the same time.

**Comment by thebinarysearchtree** [comment]
If the race condition goes the wrong way, monaco measures the action bar when the action has no content in it.
<img width="767" alt="Screen Shot 2020-12-17 at 7 58 05 pm" src="https://user-images.githubusercontent.com/960753/102472739-529f8e00-40a2-11eb-8ff0-7fc15a763dd5.png">

**Comment by thebinarysearchtree** [comment]
@sandy081 The reason you can't reproduce it is because, as you can see, you have "Peek Problems" in addition to the "Quick Fixes". Looking at the code of renderMarkerStatusbar, the peek problems code is run synchronously, but the quick fix action is based on a promise that allows for the race condition. For people who don't have anything other than "Quick Fixes" in the action bar, it will cause the bug.

**Comment by thebinarysearchtree** [comment]
I have only looked at the code for the first time today, but one way to fix this looks like taking the quick fix code out of the promise callback so that the adding of the quick fix action loaded synchronously, and then changing the "get actions" stuff so that only it is promise-based. It appears the entire reason for the promise was to wait for the possible quick fix actions, but it looks like it is better to load the quick fix container first, and get the actions later.

**Comment by thebinarysearchtree** [comment]
I have only looked at the code for the first time today, but it looks like some options are: have a placeholder there. There is some kind of placeholder, but it isn't synchronous. Even if there is a placeholder there, it will not work if the actions buttons span beyond a single line. The other option is to make the actions container synchronous, and just wait for the actions themselves asynchronously, and then update the container's placeholder from waiting, to no fixes or the quick fix button, depending on how many are returned.

**Comment by teal2** [comment]
Same problem here.
