### ISSUE TITLE
monaco-tree-row

### ISSUE THREAD

**Issue by levan-g** [Microsoft/vscode#11238]
Hello everyone

As I can see ".monaco-tree-row" height is hardcoded, could you add option to customize it's height?

**Comment by joaomoreno** [comment]
Not exactly. Which component of the workbench would you like to increase the height of each row?

**Comment by levan-g** [comment]
@joaomoreno project explorer in sidebar area and command palette.

**Comment by levan-g** [comment]
I can change it via css, but it brokes keyboard navigation in command palette.

**Comment by joaomoreno** [comment]
Thanks for letting us know. It is currently not supported, but we'll take it into account. This is a good issue to follow: #3112
