### ISSUE TITLE
Brief freezes after issuing terminal commands

### ISSUE THREAD

**Issue by pbouffard** [microsoft/vscode#112340]
Issue Type: <b>Performance Issue</b>

I have been noticing brief, but quite perceptible and annoying (maybe 0.5 to 1.5 second) freezes off and on while working on Julia code where I do a bit of editing, try something out in the REPL, do a little editing, repeat. 

I figured out eventually that the freezes were connected to issuing commands in the REPL. This wasn't immediately obvious because the freezes don't happen immediately, they happen a couple of seconds after issuing the command.

I tried turning all extensions off including Julia and restarting to no avail. I then noticed that issuing commands in other kinds of terminals (i.e. bash) inside VS Code has the same effect, i.e. it seems unrelated to Julia.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (2.77GB free)|
|Process Argv|--crash-reporter-id 70e7de16-f5a9-4f06-9e7f-95190c8c3365|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    9	   164	 18681	code main
    1	    66	 18684	   gpu-process
    0	    33	 18686	   utility
    0	   262	 18687	   window (scratch.jl — workspace (Workspace))
    0	     0	 18704	     /bin/zsh -l
    0	    66	 18712	     extensionHost
    0	    33	 18722	     watcherService
   92	    98	 18739	   shared-process
    0	     0	 18778	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    4	    66	 18776	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (scratch.jl — workspace (Workspace))
|    Folder (aoc2020): 40 files
|      File types: jl(14) txt(11) toml(2) json(1) gitignore(1) yml(1) md(1)
|                  xml(1) code-workspace(1)
|      Conf files: settings.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647

```

</details>

**Comment by deltamualpha** [comment]
#105446?

**Comment by pbouffard** [comment]
Seems to be, and the workaround in the comments for that issue appears to resolve. Might be my imagination but everything seems overall snappier too. Thanks!
