### ISSUE TITLE
Current file is not highlighted in Open Editors

### ISSUE THREAD

**Issue by svivian** [microsoft/vscode#112366]
- VSCode Version: 1.52.0 (also tested in 1.53.0-insider)
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open multiple files.
2. Make the Explorer sidebar visible with "Open Editors" panel.
3. Start typing in a file.

The background highlight on the file in the file list disappears, so it's unclear which file I am in. Switching files (with mouse or keyboard shortcut) makes it appear again, but as soon as I type it disappears.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I can reproduce this issue. Thanks for letting us know.
Assigning to January to investigate into it.

**Comment by isidorn** [comment]
@svivian Thanks for letting us know. This is a good catch. I have pushed a fix for this. You can check it out with VS Code insiders from next week and let us know if it works for you. I verified and it should be good now.
