### ISSUE TITLE
VSCode remote crashes on big files

### ISSUE THREAD

**Issue by Shiva7071007** [microsoft/vscode#112318]
- VSCode Version: 1.51.1
- OS Version: Windows_NTx64 10.0.19042

Steps to Reproduce:

1. How big?
More than 25k,
ex: Its main.js that is compiled by angular and its opening while debugging.
Sometimes, even though lines are under <2K but each line is >1.5K characters (generally a SQL dump), It crashes as well.
However, if I will have the file on my own system, it works without any issue.

But on remote, it disconnects and gives me the option to reconnect(which do not work) and reload. Reloading works but my ongoing process is lost.

I have attached logs from `.vscode-server` on remote.

[e5e9e69aed6e1984f7499b7af85b3d05f9a6883a.log](https://github.com/microsoft/vscode/files/5680957/e5e9e69aed6e1984f7499b7af85b3d05f9a6883a.log)
[fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log](https://github.com/microsoft/vscode/files/5680958/fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log)

[93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log](https://github.com/microsoft/vscode/files/5680961/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log)
[d2e414d9e4239a252d1ab117bd7067f125afd80a.log](https://github.com/microsoft/vscode/files/5680962/d2e414d9e4239a252d1ab117bd7067f125afd80a.log)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
@Shiva7071007 Does this still reproduce for you?

**Comment by Shiva7071007** [comment]
> @Shiva7071007 Does this still reproduce for you?

Sorry, but I don't have access to either the machine I was using at that time or the same code base.

**Comment by alexdima** [comment]
Thank you for your prompt answer. I will optimistically close this issue, as we have pushed a lot of improvements in the past 2 years in this area.
