### ISSUE TITLE
cssrem can't use ,  px Cannot be converted to  rem

### ISSUE THREAD

**Issue by liuning-liuning** [microsoft/vscode#112360]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aeschli** [comment]
Please give more information and steps to reproduce.

**Comment by liuning-liuning** [comment]
Sorry, because IntelliSense for CSS class Names in HTML shows only one line by default and does not expand, I apologize for the inconvenience caused.
![QQ截图20201215093024](https://user-images.githubusercontent.com/75016687/102156318-49eb6400-3eb8-11eb-80bc-d44670293d07.png)
![QQ截图20201215093102](https://user-images.githubusercontent.com/75016687/102156327-4bb52780-3eb8-11eb-8c46-567b09654433.png)

**Comment by aeschli** [comment]
Sorry, I still don't know how to reproduce. How did you get the second screenshot?
Is this because the suggest widget did not expand fully?

**Comment by liuning-liuning** [comment]
Yes, it is because of this plug-in: IntelliSense for CSS class names in HTML, the default display only a line, it needs the drop-down to display all suggest that, in fact, unit conversion is complete, just because of the similar to overflow: hidden this attribute let I didn't see, so I thought it was the cssrem plug-in problems, has now been solved, the problem I apologize.As for the picture, it is the code hint that has been expanded, indicating that I can see the unit conversion. The picture may be distorted because of cross-domain, and I can do nothing about it. Sorry for troubling you.

**Comment by aeschli** [comment]
Can the issue be closed then?

**Comment by liuning-liuning** [comment]
yes, yes,  thanks
