### ISSUE TITLE
Not able to mark breakpoint in Visual Studio Code (php file)

### ISSUE THREAD

**Issue by ChennaiArun** [microsoft/vscode#112339]
Issue Type: <b>Bug</b>

After 1.52.0 update, not able to mark breakpoint in my php file. I need to enable them @ VS>Settings>Debug and check @ "Allow setting breakpoints in any file"

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.39GB free)|
|Process Argv|--crash-reporter-id 6d009ecf-1276-4efc-b55b-ffe801e3bece|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.0.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.13
jquerysnippets|don|0.0.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
font-switcher|eva|3.1.0
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.5
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
vscode-css-peek|pra|4.0.2
code-settings-sync|Sha|3.4.3
vba|spe|1.6.2
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.1.18
quokka-vscode|Wal|1.0.335
vscode-todo-highlight|way|1.0.4
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30233462
pythonvspyt875:30228414

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension see https://github.com/microsoft/vscode/issues/110375#issuecomment-725482753
