### ISSUE TITLE
Test: remember terminal layout between restarts

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#112338]
Refs #109244

- [x] wsl @joaomoreno
- [x] ssh @deepak1556
- [x] web @mjbvz

Complexity: 4

Authors: @roblourens, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23112338%0A%0A)

---
For reference, https://github.com/microsoft/vscode-internalbacklog/issues/1555 was the test plan item for remote terminal reconnection in general.

**Action:** 
Open a remote VS Code window and create tabs of split terminals. Reload the window.

**Expectation:** the following persists:
- active tab
- for each tab, the active instance
- the relative widths (horizontal) or heights (vertical) of the terminals in a tab

Some things to try:

1. The terminal state is restored correctly when the terminal is hidden while reloading the window. Try revealing the terminal:
   - using the command / keybinding
   - by dragging it
2. Re-orient the terminal panel to be vertical instead of horizontal
3. Multi-folder
    - Open folder A
    - Open 3 terminals in a split tab
    - Open folder B (in the same window)
    - Run the command “Terminal: Attach to session”
    - Pick one of those terminals, kill it
    - Open folder A again
    - See that the 2 remaining terminals are restored and are split with reasonable sizing

**Comment by joaomoreno** [comment]
@meganrogge What an epic battle with the bot.
