### ISSUE TITLE
html not working

### ISSUE THREAD

**Issue by MirzaYsf** [microsoft/vscode#112364]
Issue Type: <b>Bug</b>

 res.send('User name ${user.firstName} added to dB');

$ not working

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz (4 x 3060)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 3|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id c8523347-8c64-4be2-9075-85c8a3b023a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bubba** [comment]
Replace the single quotes with backticks to use string interpolation in javascript

```
res.send(`User name ${user.firstName} added to dB`);
```

**Comment by aeschli** [comment]
Sorry, how is that related to VSCode? Please add detailed steps.
