### ISSUE TITLE
Cannot open folder in VSCode's Explorer

### ISSUE THREAD

**Issue by wi-fr** [microsoft/vscode#112400]
Issue Type: <b>Bug</b>

With update 1.52 installed, I cannot open my primary folder in VSCode's Editor anymore. Opening subfolders works as expected. [The primary folder contains 1600 files and folders]

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770T CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.70GB free)|
|Process Argv|--crash-reporter-id d20f387d-989e-4f50-a71d-a1c910077159|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by wi-fr** [comment]
I removed all files and subfolders from my primary folder and copied them back one by one. This solved the problem.

**Comment by isidorn** [comment]
Sounds like the problem is solved. I can not repro this, so let us know if you still see this and if you have exact reproducable steps so we can reopen this
