### ISSUE TITLE
Open editors hidden by default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#112480]
We should do one of the following:

1) Hide open editors by default for new users
2) Hide open editors for non desktop vs code version

Hidding open editors for all users would be too risky imho.
@sandy081 @alexr00  do we have some mechanism for first time users - I believe we wanted to use something like this for npm scripts view

**Comment by alexr00** [comment]
We can hide a view by default if the user hasn't changed the view show/hide status. It wouldn't be only new users, but instead users who haven't messed with the visibility of the view. This is what we did for npm.

https://github.com/microsoft/vscode/blob/3689660fcc1d56dbd81832ff8b0230e00ade2cbb/extensions/npm/package.json#L66-L66
