### ISSUE TITLE
Arrow keys not read by python in integrated terminal. Cursor doesn't turn off.

### ISSUE THREAD

**Issue by ChrisIdema** [microsoft/vscode#112405]
- VSCode Version: 1.52.0
- OS Version: windows 10

Steps to Reproduce:

1. download snake.py https://github.com/python-engineer/python-fun/tree/master/snake-game
2. install curses for windows `python -m pip install windows-curses`
3. run in integrated terminal (stretch window to be at least 20 lines): `python snake-game/snake.py`

In external terminal the arrow keys are processed by the python program and no cursor is visible. In the integrated terminal the keys are not mapped properly and the cursor is visible.

- Arrow up is 450 (KEY_A2) instead of  'KEY_UP': 259,
- Arrow down is 456 (KEY_C2) instead of  'KEY_DOWN': 258
- Arrow right is 454 (KEY_B3) instead of 'KEY_RIGHT': 261
- Arrow left is 452 (KEY_B1) instead of 'KEY_LEFT': 260,

A workaround is to change the key-codes in my code and that works for now, but that is not a clean solution. I haven't found a way to disable the cursor. Setting cursorstyle to line makes it slightly better, but the local settings.json file is ignored. I don't want to change the global settings file.

I've tested it on Ubuntu and have no issues in the terminal there (although KEY_C2 etc. are not defined), so it is an issue with the windows build of vscode.

**Comment by outcastdreamer** [comment]
Hey, this works great! For me as well KEY_UP, etc weren't working. I would further like to add that in case KEY_ENTER isn't working, the following works (an example snippet) : 
`
if key == curses.KEY_ENTER or key in [10,13]:
    """Your coding logic here"""
    pass                 #basically [10,13] works for KEY_ENTER
`
I found this after some great struggle. @ChrisIdema do you remember the source of these KEY values? I have been trying to find them 😃

**Comment by ChrisIdema** [comment]
> I found this after some great struggle. @ChrisIdema do you remember the source of these KEY values? I have been trying to find them 😃

I just printed the keycodes of the keys I pressed and I printed all the key definitions of the curses class:

```
import curses
print(vars(curses))
```

And that's how I noticed certain keycodes were missing in curses for ubuntu and some were incorrect in the integrated terminal of vscode in windows, but not in the external terminal in windows.

Tested in latest version of vscode in windows: **still the same problems, cursor visible and keys not recognized.**

**Comment by ChrisIdema** [comment]
> 
> 
> This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in VS Code or the [marketplace](https://aka.ms/vscodemarketplace) for VS Code. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

No that's not true. I tested it with plugins disabled and it still doesn't work. Which extension was identified as the cause of the problem? Please reopen.
