### ISSUE TITLE
Git Fatal Error "Unable to update URL base from redirection"

### ISSUE THREAD

**Issue by AErmie** [microsoft/vscode#112468]
Issue Type: <b>Bug</b>

1. Create a repo in Azure DevOps Repos (not on GitHub)
2. Clone repo locally
3. Make a change to the content
4. Commit changes, and push to origin (through the VS Code UI)

**NOTE:** This Git error ONLY occurs in the VS Code Insider Preview version. I am able to complete the steps without error/issue in the "normal" VS Code, and also from the command-line. 

Full Error: 
> git -c http.userAgent="git/2.29.2.windows.1 (Windows 10 Pro 10.0.19042; win32 x64) vscode/1.53.0-insider (Visual Studio Code - Insiders)" push origin main:main
fatal: unable to update url base from redirection:
  asked for: https://AdinErmie@dev.azure.com/AdinErmie/MPWebDemo/_git/MPWebDemo/info/refs?service=git-receive-pack
   redirect: https://spsprodcus1.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2FAdinErmie%2FMPWebDemo%2F_git%2FMPWebDemo%2Finfo%2Frefs%3Fservice%3Dgit-receive-pack&redirect=1&hid=710ea30d-343b-4aaa-a1ff-af55d5009515&context=eyJodCI6MiwiaGlkIjoiYTg0YTQ4ZjEtMDhkZS00ZmMyLTkxYTctOGMxNGI4ZGZlNjY0IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2

VS Code version: Code - Insiders 1.53.0-insider (96b426ef1da0f0a51ce9ef1931cd1fd2322547e4, 2020-12-14T05:59:27.649Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.42GB free)|
|Process Argv|C:\\Users\\adine\\Documents\\GitHub\\MPWebDemo --crash-reporter-id b048bb0b-cf6e-46af-8204-d3c18332d536|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bicep|Azu|0.1.1-alpha.g427d5e7abe
azurepolicyextension|Azu|0.1.1
vscode-markdownlint|Dav|0.38.0
sentinel|has|0.0.3
terraform|has|2.3.0
git-graph|mhu|1.28.0
azure-pipelines|ms-|1.177.0
vscode-azureterraform|ms-|0.3.2
vscode-bicep|ms-|0.2.59
vscode-docker|ms-|1.8.1
csharp|ms-|1.23.7
vscode-dotnet-runtime|ms-|1.0.0
remote-containers|ms-|0.154.0
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
powershell|ms-|2020.6.0
powershell-preview|ms-|2020.9.0
azurerm-vscode-tools|msa|0.14.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2promptcf:30219163
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by eamodio** [comment]
First, it doesn't look like the url that is being requested is a valid repository url (especially the info/refs part). But if this works fine in the stable version/command line that is very odd.

I've pushed a change to how we are setting the userAgent, and maybe that will have an effect -- so can you try it out in tomorrow's insiders?

Also in the meantime, if you run that exact command from the command line do you see the same failure?
> `git -c http.userAgent="git/2.29.2.windows.1 (Windows 10 Pro 10.0.19042; win32 x64) vscode/1.53.0-insider (Visual Studio Code - Insiders)" push origin main:main`
