### ISSUE TITLE
Changing sorting sequence does not have any impact in extension widget

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#11246]
Testing #11120.

Insiders build from 8/30 on MacOS.
1. Open the extension widget
2. enter `@recommended @sort:installs-desc` in the text widget and press <kbd>return</kbd>
3. enter `@recommended @sort:installs-asa` in the text widget and press <kbd>return</kbd>
There is no change between 2 and 3.

**Comment by gregvanl** [comment]
I think the issue is more general. None of the sort modifiers work if @recommended is also in the search box. You can't filter by installs or rating.
