### ISSUE TITLE
Feature request: tab completion in python debug consolue

### ISSUE THREAD

**Issue by ucohen** [microsoft/vscode#112465]
Issue Type: <b>Feature Request</b>

During debug, in the DEBUG-CONSOLE window, there is no support for tab-completion.
such a feature would greatly improve the consule usability.
Currently, pressing TAB causes the focus to move to other vscode views.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.4.0-56-generic

**Comment by isidorn** [comment]
This actually works fine for me.
Can you reproduce this problem with VS Code insiders https://code.visualstudio.com/insiders/
If yes, what are your exact steps?

Here are mine:
1. Start debugging ,hit a breakpoint
2. Write something in debug console -> see suggest box shows up
3. Press `Tab` suggest box completion is accepted as expected

**Comment by ucohen** [comment]
thanks @isidorn 
it works fine.
TAB seems to work when a suggestion already appears in the console, otherwise, Ctrl+Space is used to suggest completions

**Comment by isidorn** [comment]
As this seems to work -> closing
