### ISSUE TITLE
Unable to toggle Breakpoints

### ISSUE THREAD

**Issue by lmartins** [microsoft/vscode#112488]
Issue Type: <b>Bug</b>

Since the latest release it become impossible to toggle Debugger Breakpoints next to the editor line numbers. Is this a known issue?

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|40.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 255efa05-20de-469c-8ef2-e8f8b3bb5c15|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.0.0
vscode-intelephense-client|bme|1.5.4
simple-react-snippets|bur|1.2.3
indented-block-highlighting|byi|1.0.7
npm-intellisense|chr|1.3.1
laravel-goto-view|cod|1.3.3
bracket-pair-colorizer|Coe|1.0.61
column-jump|Coe|0.0.5
dakara-foldplus|dak|1.5.1
macos-modern-theme|dav|1.6.10
vscode-eslint|dba|2.1.14
vscode-quick-select|dba|0.2.9
vscode-dash|dee|2.4.0
gitlens|eam|11.0.6
vscode-great-icons|emm|2.1.62
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|5.8.0
php-debug|fel|1.13.0
auto-rename-tag|for|0.1.5
vscode-flatland-icon-theme|geb|0.0.6
vscode-pull-request-github|Git|0.22.0
commander|giy|0.2.1
svg|joc|1.4.2
vscode-liquid-snippets|kil|2.0.1
vscode-simple-icons|Lau|1.13.5
expand-region|let|0.1.4
twig-language-2|mbl|0.9.2
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-mjml|mjm|1.0.1
find-jump|mks|1.2.4
mongodb-vscode|mon|0.3.0
theme-monokai-pro-vscode|mon|1.1.18
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.9.0
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
sublime-keybindings|ms-|4.0.7
debugger-for-chrome|msj|4.12.11
trailing-semicolon|nau|1.0.2
language-liquid|nei|0.1.1
incrementor|nms|0.1.0
laravel-blade|one|1.25.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.4.0
vscode-css-peek|pra|4.0.2
seti-icons|qin|0.1.3
LiveServer|rit|5.6.1
laravel-artisan|rya|0.0.27
vscode-field-lights|sve|0.0.11
ayu|tea|0.20.1
vscode-status-bar-format-toggle|tom|2.0.0
vscode-todo-highlight|way|1.0.4
vscode-webhint|web|1.5.9
glean|wix|5.1.0
vscode-import-cost|wix|2.13.0
ReactSnippets|xab|2.4.0
sort-js-object-keys|zen|1.0.6
material-theme|zhu|3.9.11
html-css-class-completion|Zig|1.19.0

(22 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30233461
vsjup459:30229593

```

</details>

**Comment by gjsjohnmurray** [comment]
Judging by your extension list this is probably happening in PHP files, in which case a duplicate of #112288

Workaround is suggested in that issue.

**Comment by lmartins** [comment]
@gjsjohnmurray it is indeed. Dang! I've searched through the open issues and somehow missed this. Thank you for pointing that out John.
