### ISSUE TITLE
Reverse color effect remains after unchecking on Mac OS Big Sur

### ISSUE THREAD

**Issue by wststone** [microsoft/vscode#112475]
I accidently checked Preferences > support > display > reverse color and the color did reversed, however when i unchecked it, the reserved color effect remains in vscode in my second monitor. I restarted my mac mini and it still had the color reversed effect, I then went to manually set my color theme in vscode, i think this could be a potential feature/bug.

**Comment by aeschli** [comment]
@bpasero Can you maybe reproduce that? I don't have Big Sur.

**Comment by bpasero** [comment]
I cannot reproduce. Is this related to having VSCode run on a second monitor? Does it reproduce if you don't have a monitor attached?
