### ISSUE TITLE
Auto dark mode detect

### ISSUE THREAD

**Issue by milad-kamali** [microsoft/vscode#112449]
Hello,
Please add auto dark mode detect based on windows light or dark theme.

**Comment by gjsjohnmurray** [comment]
`"window.autoDetectColorScheme": true`

**Comment by aeschli** [comment]
That should already work. You can enable this by `"window.autoDetectColorScheme": true`
The preferred themes can be selected by `workbench.preferredDarkColorTheme` and `workbench.preferredLightColorTheme`.

Linux is not yet working, we are waiting for Electron support: #102795.

Please try it out and file an issue with details if this is not working for you.
