### ISSUE TITLE
Scroll is gone after exiting vi in integrated terminal

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11244]
Testing #11134

- VSCode Version: 1.5.0-Insiders
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open integrated terminal
2. Run `vi`
3. Quit `vi`
4. The scrollbar is missing and the pane is not scrollable any more. If you press `<enter>` again, the scrollbar is back.

**Comment by rebornix** [comment]
FYI, this issue doesn't happen when using nano.

**Comment by Tyriar** [comment]
I believe I fixed this upstream already so I need to do an uplevel.

**Comment by Tyriar** [comment]
Due to the recent module refactor in xterm.js I think it's too high risk to uplevel at this point, moving to September.

**Comment by Tyriar** [comment]
Due to the recent xterm.js module refactor this is too high risk for August.
