### ISSUE TITLE
Typo Under Terminal Settings

### ISSUE THREAD

**Issue by lassandroan** [microsoft/vscode#112437]
- VSCode Version: 1.52.0
- OS Version: macOS 10.14.6

Seems there's a typo under `Settings > Features > Terminal > Integrated: Allow Mnemonics`, "allow menubar mnemonics to trigger the open the menubar"

<img width="732" alt="Screen Shot 2020-12-14 at 12 40 33 AM" src="https://user-images.githubusercontent.com/9328186/102049471-89c22680-3da6-11eb-9bf6-acc1207a4b17.png">

**Comment by meganrogge** [comment]
thanks!
