### ISSUE TITLE
Debug for php

### ISSUE THREAD

**Issue by IamZenit** [microsoft/vscode#112402]
Issue Type: <b>Feature Request</b>

I can't put breakpoints in a .php file, I can't debug my php code

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

**Comment by savioret** [comment]
Same problem. Clicking on the left margin does to add a new breakpoint.
Please correct the "Issue Type" as it is a Bug, not a feature request.

**Comment by MatthieuScarset** [comment]
Indeed, PHP breakpoints do not work anymore with November 2020 release (1.52).

Need to downgrade to [October 2020 release (1.51)](https://code.visualstudio.com/updates/v1_51).

**Comment by weinand** [comment]
no need to downgrade. Just see this workaround: https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329

**Comment by capegreg** [comment]
> no need to downgrade. Just see this workaround: [#112288 (comment)](https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329)

Yes, the breakpoint indicator shows in the gutter, but it does not get hit during debugging.
