### ISSUE TITLE
btoa is undefined

### ISSUE THREAD

**Issue by Charan72** [microsoft/vscode#112428]
Issue Type: <b>Bug</b>

I have tried many ways. while entering the credentials to set the connectivity of the SAP System I'm always resolving "An error occured: btoa is not defined".

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.47GB free)|
|Process Argv|--crash-reporter-id 793d8dc9-56eb-4768-83ab-8427c1fca8d7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-xml|red|0.14.0
yeoman-ui|SAP|1.1.38
xml-toolkit|SAP|1.0.3
sap-ux-annotation-modeler-extension|SAP|1.0.24
sap-ux-application-modeler-extension|SAP|1.0.24
sap-ux-fiori-tools-extension-pack|SAP|1.0.24
sap-ux-help-extension|SAP|1.0.24
sap-ux-service-modeler-extension|SAP|1.0.24
vsc-extension-mbt|SAP|1.8.0
vsc-extension-mdk|SAP|1.17.0
vscode-cds|SAP|3.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30233462

```

</details>

**Comment by sandy081** [comment]
Seems unrelated to VS Code, please file issue against SAP extension.
