### ISSUE TITLE
Markdown hover: link + codicon styling

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#112493]
Trying to use codicon + span style in hover:

1. Span inside the link description. Styling works, link doesn't work

```ts
const markdown = new MarkdownString(undefined, true);
markdown.isTrusted = true;
markdown.appendMarkdown(`[<span style="color:#fff;background-color:#029cdf;">$(record-keys)</span>](https://github.com)`);
return markdown;
```
![Screenshot (399)](https://user-images.githubusercontent.com/9638156/102124777-bbe09080-3e59-11eb-8fbf-db99fb705d25.png)

2. Span outside the link. Foreground is not applied, link works.

```ts
markdown.appendMarkdown(`<span style="color:#fff;background-color:#029cdf;">[$(record-keys)](https://github.com)</span>`);
```

![Screenshot (400)](https://user-images.githubusercontent.com/9638156/102125132-3f01e680-3e5a-11eb-9c3a-a60bfcd9814e.png)

**Comment by alexr00** [comment]
I'm not sure why 1 doesn't work. 2 doesn't get the colors because links have their own style that is superseding the specified on.

HTML from 1.
```html
<a href="#" data-href="https://github.com" title="https://github.com">
  <span style="color:#ff0000;background-color:#029cdf;">
    <span class="codicon codicon-record-keys">
      ::before
    </span>
  </span>
</a>
```

HTML from 2.
```html
<span style="color:#ff0000;background-color:#029cdf;">
  <a href="#" data-href="https://github.com" title="https://github.com">
    <span class="codicon codicon-record-keys">
      ::before
    </span>
  </a>
</span>
```

**Comment by alexr00** [comment]
Ah. Looks like this is happening: https://stackoverflow.com/questions/22982146/span-with-a-href-link-not-working

**Comment by alexr00** [comment]
If I put something on either side of the codicon, I can click in that space for the link. But the rendered codicon doesn't get the link. @jrieken do you own codicon rendering? I would expect this to occur in any markdown with a codicon, not just in the custom hover, since they would all use `MarkdownString`. I'm not sure how to make the codicon clickable with an anchor tag.

**Comment by jrieken** [comment]
> @jrieken do you own codicon rendering?

That would be @eamodio or @misolori

**Comment by usernamehw** [comment]
Maybe https://stackoverflow.com/questions/21753590/pseudo-element-not-clickable ?

I'm using Custom CSS extension and with this rule the 1st example seems to work fine:

```css
a .codicon {
	pointer-events: none;
}
```

**Comment by misolori** [comment]
@usernamehw yea it looks like links with nested span + pseudo elements aren't clickable ([see sample](https://jsfiddle.net/h2a7j5pr/)). This appears to be a browser/chromium issue though.

**Comment by misolori** [comment]
Ideally we'd need to have proper styling support in markdown hovers to leverage color theme colors. Something like:

```ts
const iconGitHub = new vscode.ThemeIcon('github-inverted', new vscode.ThemeColor('charts.green'));
markdown.appendMarkdown(`[${iconGitHub}](http://www.github.com)`);
```

**Comment by usernamehw** [comment]
To use theme colors NOT only for `ThemeIcon`, but for simple spans (background, for instance) it would still need https://github.com/microsoft/vscode/issues/32813

With https://github.com/microsoft/vscode/issues/32813 it would look:

```ts
md.appendMarkdown(`<span style="color:${ColorTheme.getColor('myColor')};background-color:${ColorTheme.getColor('myBgColor')};">text</span>`);
```

**Comment by misolori** [comment]
In general I don't think this is something that we recommend. Suggestion would be to color the icon as opposed to the background, will close as out of scope.
