### ISSUE TITLE
VSCode install path should use system PATH variable rather then store path

### ISSUE THREAD

**Issue by TGTGamer** [microsoft/vscode#112407]
VSCode stores the path in which it was installed, meaning that if this path changes, it causes issues. In my case, I changed my `c:/users/` directory, which caused all updates to fail. 

![image](https://user-images.githubusercontent.com/11413796/102024978-efa1b480-3d8c-11eb-9cbe-6aea207e0fab.png)

- VSCode Version: October 2020 (version 1.51)
- OS Version: Windows 10 Pro - 19042.685

Steps to Reproduce:

1. Install any previous version of VSCode
2. Change system paths inclusive of `C:/users/<username>/` to `C:/users/<newUsername>`
3. Run `Check for update` and restart to update.

Does this issue occur when all extensions are disabled?: Yes

Temporary fix for users experiencing same issue: `mklink /J "C:\Users\<oldUsername>" C:\Users\<newUsername>`

Proposed Solution: 

VSCode should use `path` variables from the system variables, allowing users to change the directory without issues, or should instead get the path to the install location when it updates by reading the current directory path.

**Comment by joaomoreno** [comment]
> VSCode stores the path in which it was installed, meaning that if this path changes, it causes issues. In my case, I changed my `c:/users/` directory, which caused all updates to fail.

This is an unfortunate limitation, due to the unlikelyhood of that happening. We distribute a portable release as well, in order to mitigate these scenarios. Sorry about that.
