### ISSUE TITLE
[VCQ][DevDiv_VSO][VSCode][Copy {0} files]

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#112411]
<table width=841 style="border-collapse:collapse;width:631pt;"><tbody>
 <tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>MS PM</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;">Daniel Ye</td>
 </tr><tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>MOR PM</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;">Jan Baltus (Moravia IT)</td>
 </tr>
 <tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>String Resource ID</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;">0; &quot;src/vs/workbench/contrib/files/browser/fileActions.copyBulkEdit&quot;</td>
 </tr>
 <tr>
  <td width=138 height=80 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Source String</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;">Copy {0} files</td>
 </tr>
 <tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Subtenant</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;">VSCode</td>
 </tr><tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Source Control Link</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;"></td>
 </tr>
 <tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Filename</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;">vscode-workbench\vs_workbench_contrib_files.xlf</td>
 </tr>
 <tr>
  <td width=138 height=40 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Question</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;"><div><span>Please, define placeholder. Will it be a number of files? Same for strings:</span></div><div><span><br></span></div><div>Delete {0} files &nbsp; &nbsp;0; &quot;src/vs/workbench/contrib/files/browser/fileActions.deleteBulkEdit&quot;?</div><div>Move {0} files &nbsp; &nbsp; 0; &quot;src/vs/workbench/contrib/files/browser/fileActions.moveBulkEdit&quot;?</div><div>Copying {0} files &nbsp; 0; &quot;src/vs/workbench/contrib/files/browser/fileActions.copyingBulkEdit&quot;?</div><div>Moving {0} files &nbsp; &nbsp;0; &quot;src/vs/workbench/contrib/files/browser/fileActions.movingBulkEdit&quot;?</div><div><br></div><span>Several occurrences.</span></td>
 </tr>
 <tr>
  <td width=138 height=20 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Additional details</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;"></td>
 </tr>
 <tr>
  <td width=138 height=60 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#ffc000;border:1px solid #d4d4d4;border-top:none;width:104pt;"><strong>Core Team Response</strong></td>
  <td width=703 style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;"></td>
 </tr></tbody>
 </table>

**Comment by isidorn** [comment]
I have taklced this via a `comment` in the `nls` call
