### ISSUE TITLE
Unable to pull from custom Git remote URLs protected with different SSH keys

### ISSUE THREAD

**Issue by Lucria** [microsoft/vscode#112420]
- VSCode Version: 1.52.0 (user setup)
- OS Version: Windows 10 Enterprise, Windows_NT x64  Version 10.0.19041 Build 19041
- More Info: 
```
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

Steps to Reproduce:

1. Open any folder/workspace in vscode with a remote as `git@github.com-work:<repo-url-here>`
2. Create new Git commit
3. Push using built in Source Control panel (or the sync icon at the bottom)
Push (or pull, or auto fetch) never completes because VSCode attempts to pull from `git@github.com` instead of `git@github.com-work`. As I have different SSH keys set up for these two URLs, an error will display with `git@github.com: Permission denied (publickey,keyboard-interactive).`

Does this issue occur when all extensions are disabled?: No
I have attempted the same action by disabling `eamodio.gitlens` and `donjayamanne.githistory` but issue still persists.

List of extensions installed:
```
aaron-bond.better-comments
Angular.ng-template
austin.code-gnu-global
bhshawon.node-json-autocomplete
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
CoenraadS.bracket-pair-colorizer
dan-c-underwood.arm
Dart-Code.dart-code
Dart-Code.flutter
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
donjayamanne.python-extension-pack
dunstontc.viml
eamodio.gitlens
eg2.vscode-npm-script
emmanuelbeziat.vscode-great-icons
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
eriklynd.json-tools
esbenp.prettier-vscode
felipecaputo.git-project-manager
formulahendry.code-runner
golang.go
Gruntfuggly.todo-tree
helixquar.asciidecorator
HookyQR.beautify
James-Yu.latex-workshop
jasonnutter.search-node-modules
jchannon.csharpextensions
johnpapa.vscode-peacock
johnpapa.winteriscoming
jprestidge.theme-material-theme
LeetCode.vscode-leetcode
leizongmin.node-module-intellisense
magicstack.MagicPython
michelemelluso.gitignore
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-python.python
ms-toolsai.jupyter
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cpptools
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
msjsdiag.debugger-for-edge
oderwat.indent-rainbow
PKief.material-icon-theme
sdras.night-owl
shd101wyy.markdown-preview-enhanced
sldobri.daily
torn4dom4n.latex-support
Tyriar.shell-launcher
VisualStudioExptTeam.vscodeintellicode
vsciot-vscode.vscode-arduino
vscode-icons-team.vscode-icons
waderyan.nodejs-extension-pack
webfreak.debug
wesbos.theme-cobalt2
xabikos.JavaScriptSnippets
yzhang.markdown-all-in-one
ZainChen.json
```

**Comment by MilesNorton** [comment]
This just happened to me when a new vscode insider update came through.
About:
`Version: 1.53.0-insider
Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
Date: 2020-12-11T17:35:42.622Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Linux x64 5.4.0-58-generic snap
`

**Comment by eamodio** [comment]
@Lucria Did this used to work and then stopped? Can you open the Git channel in the Output pane to see if there are any errors when this happens?

**Comment by Lucria** [comment]
@eamodio This did not use to work at all for me. 

This is the error output. It seems that it is unable to determine that the remote is using `git@github.com-work` and attempts to pull from `git@github.com`

```
> git pull --tags origin feature/new-feature
git@github.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The above error that I described also happens for Gitlab repositories, where I have two SSH keys for my work Gitlab account and personal Gitlab account. The sync button will also attempt to pull/push from `git@gitlab.com` instead of `git@gitlab.com-work`
