### ISSUE TITLE
multi line debug repl input doesn't support up/down arrows

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#11245]
Testing #10996

- VSCode Version: 1.5.0-Insiders
- OS Version: Linux

Steps to Reproduce:

1. Debug a nodejs app
2. Write multi line string in repl
3. Use up/down arrows

Now left/arrow works perfectly but since it's a mulit-line string, we should be able to use up/down to move the cursor inside the string as well, like Chrome Debug Console.

**Comment by kieferrm** [comment]
On Mac, up and down arrow navigate the input history. Which is fine  but then I'd expect <kbd>Cmd+ArrowUp</kbd> and <kbd>Cmd+ArrowDown</kbd> to move the cursor.

**Comment by roblourens** [comment]
This feels like what I expect, and seems to match Chrome DevTools' behavior.
