### ISSUE TITLE
Can't get workspace folder if add first workspace folder using updateWorkspaceFolders

### ISSUE THREAD

**Issue by fbs2016** [microsoft/vscode#112439]
- VSCode Version:1.52.0
- OS Version:Ubuntu 20.04

Steps to Reproduce:

1. In my extension:
const uri = vscode.Uri.parse('/home/my/test');
               workspace.updateWorkspaceFolders(
                    workspace.workspaceFolders ? workspace.workspaceFolders.length : 0,
                    0,
                    { uri }
                );
const wsFolder = vscode.workspace.getWorkspaceFolder(uri);  => undefined

2. launch extension without any workspace folder, run command to launch the code above, variable 'wsFolder ' return undefined.

I want to add the first workspace folder and update the settings of the folder through my command. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
From the API doc

Use the onDidChangeWorkspaceFolders() event to get notified when the workspace folders have been updated

**Comment by sandy081** [comment]
Yeah, please use the event for consistency. In your case, we restart extension host for some legacy reasons.

**Comment by fbs2016** [comment]
> 
> 
> From the API doc
> 
> Use the onDidChangeWorkspaceFolders() event to get notified when the workspace folders have been updated

I try to use onDidChangeWorkspaceFolders(), it doesn't work and debug can't step into it.

**Comment by sandy081** [comment]
As said, in your specific case extension host will be restarted and hence the steps after 👇 are not executed.
```
workspace.updateWorkspaceFolders(
workspace.workspaceFolders ? workspace.workspaceFolders.length : 0,
0,
{ uri }
);
```

**Comment by fbs2016** [comment]
> 
> 
> As said, in your specific case extension host will be restarted and hence the steps after 👇 are not executed.
> 
> ```
> workspace.updateWorkspaceFolders(
> workspace.workspaceFolders ? workspace.workspaceFolders.length : 0,
> 0,
> { uri }
> );
> ```
Update the line "vscode.workspace.onDidChangeWorkspaceFolders" before the call updateWorkspaceFolders, it still can't step into onDidChangeWorkspaceFolders.

**Comment by fbs2016** [comment]
> 
> 
> As said, in your specific case extension host will be restarted and hence the steps after 👇 are not executed.
> 
> ```
> workspace.updateWorkspaceFolders(
> workspace.workspaceFolders ? workspace.workspaceFolders.length : 0,
> 0,
> { uri }
> );
> ```

Even if I move vscode.workspace.onDidChangeWorkspaceFolders() before the execution updateWorkspaceFolders(), it lost the listener i write as the extension restart. Am I right?

Is there any way to achieve my goal: Add the first workspace folder and update the folder settings by vscode.workspace.getConfiguration()->update  in one command？

**Comment by sandy081** [comment]
Currently ext host is restarted when first folder is changed. I do not think this can be prevented.
