### ISSUE TITLE
File rename operation automatically stops after copy-paste

### ISSUE THREAD

**Issue by Daninet** [microsoft/vscode#112438]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Select a file in Explorer
2. Press Ctrl-C
3. Press Ctrl-V (new file gets automatically selected)
4. Quickly press F2 to rename the new file
5. Start typing the new name
6. **Bug happens here**: After a few milliseconds, the input field disappears and it prevents typing the new name.

Check the attached GIF.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

![vscode](https://user-images.githubusercontent.com/884882/102050847-3377d680-3dec-11eb-923a-c88d208c0023.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/111652
Fixed in latest insiders
Sorry about the brekage!
