### ISSUE TITLE
Extensions not work with the last update, Commit: 96b426ef1da0f0a51ce9ef1931cd1fd2322547e4

### ISSUE THREAD

**Issue by ykraynov** [microsoft/vscode#112457]
- VSCode Version:
- OS Version:
Version: 1.53.0-insider
Commit: 96b426ef1da0f0a51ce9ef1931cd1fd2322547e4
Date: 2020-12-14T05:39:59.827Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Linux x64 5.4.0-58-generic snap

Steps to Reproduce:

1. After update to visual-studio-code-insiders, 1.53.0-1607925055
2.Try to open remote project
3. No Extensions are shown, remote connection is not established, while there is SHH connectivity to the remote machine. No any output in the OUTPUT window. 

**Note**: works with the previous version: 1.53.0-1607708758
Version: 1.53.0-insider
Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
Date: 2020-12-11T17:35:42.622Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Linux x64 5.4.0-58-generic

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel?

**Comment by alexr00** [comment]
@ykraynov would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.

**Comment by ykraynov** [comment]
Hello,
Unfortunately after the last update the issue is gone.
The last updated version it works fine now:
Version: 1.53.0-insider
Commit: c927a8015b9e26bd454d6e293bb0384aa1975d06
Date: 2020-12-18T05:27:50.274Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.4.0-58-generic

@roblourens There was no output on any channel.

**Comment by ykraynov** [comment]
Not reproducible with the latest update
