### ISSUE TITLE
Autocomplete broken on new release for nodejs imports

### ISSUE THREAD

**Issue by tudor33sud** [microsoft/vscode#112441]
- VSCode Version: 1.52.0
- OS Version: Windows 10

Steps to Reproduce:

1. Declare a nodejs module which returns an object with nested values
2. Try to import the module object directly in another file
3. Imported module autocomplete doesn't work at all and interprets object as any.

Code example:
const patientsContainer = require('./database').containers.patients; -- patientsContainer autocomplete broken
const { patients:patientsContainer } = require('./database').containers; -- patientsContainer autocomplete OK

Export example 
const containers = {
    patients: <cosmosdbcontainerObject>
};
module.exports = {containers}

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
What is the type of `patients`? Both examples work for me if I set  `paitents` to be a string for example:

![Screen Shot 2020-12-14 at 3 38 26 PM](https://user-images.githubusercontent.com/12821956/102149026-6d63cf80-3e22-11eb-9eb5-eaa4a987a22b.png)
