### ISSUE TITLE
Project snippets do not apply immediately when changed while in Remote WSL environment

### ISSUE THREAD

**Issue by flying-sausages** [microsoft/vscode#112477]
- VSCode Version: 1.52.0
- OS Version: Windows 20h2

Steps to Reproduce:

1. Start a session in WLS
2. Make changes to `.vscode/*.code-snippets`
1. Saved changes don't apply

Does this issue occur when all extensions are disabled?: No because you cannot reproduce this without the WSL Remote extension

Only workaround currently is to do `Developer: Reload Window` or restart the entire instance

**Comment by jrieken** [comment]
@aeschli Didn't you say there is an issue with file watching and WSL?

**Comment by aeschli** [comment]
There are known watcher issues in WSL2 when the project is located on `/mnt/c...`: https://github.com/microsoft/vscode-remote-release/issues/3959

**Comment by flying-sausages** [comment]
> @flying-sausages Is your project on `/mnt/c...` ?

Yes I do! I suppose the current workaround would be to move it out of the mount?

**Comment by jrieken** [comment]
Likely, tho I can also push a change to detect when it is us (VS Code) making edit and then update

**Comment by flying-sausages** [comment]
If it's internal VSCode settings/snippets/etc. might as well skip the watcher altogether, I agree.
