### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by PravinKadwe** [microsoft/vscode#112442]
Is there any solution to the "Extension host terminated unexpectedly." problem? this is a notification pop up when the VSCode window loads.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Find out which extension is causing the problem, then report it to the extension author.

**Comment by PravinKadwe** [comment]
**I open the Developer Tool for the notification that popped up in VSCode and these errors are shown in Console:** 

 ERR [File Watcher (node.js)] Error: ENOENT: no such file or log.ts:197  directory, stat 'e:\Study\Bootstrap\Bootstrap\.vscode'

abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:829

console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, open 'c:\Users\pc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js'
t.log @ console.ts:112

abstractExtensionService.ts:467 Extension host terminated unexpectedly. Code:  0  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:431

log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: 

notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:36

extensionHostManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostManager.ts:37

extensionHostManager.ts:74 timeout
(anonymous) @ extensionHostManager.ts:37

lifecycle.ts:158 Error: Trying to add a disposable to a DisposableStore that has already been disposed of. The added object will be leaked!
    at d.add (lifecycle.ts:158)
    at e._register (lifecycle.ts:188)
    at extensionHostManager.ts:80

add @ lifecycle.ts:156
_register @ lifecycle.ts:156
(anonymous) @ extensionHostManager.ts:37
log.ts:197   ERR Error: No authentication provider 'microsoft' is currently registered.
    at E.getSessions (authenticationService.ts:471)
    at async e.getAccounts (userDataSyncWorkbenchService.ts:204)
    at async e.update (userDataSyncWorkbenchService.ts:189)
    at async e.initialize (userDataSyncWorkbenchService.ts:160)
    at async e.waitAndInitialize (userDataSyncWorkbenchService.ts:143)

log.ts:191  WARN Settings Sync: Accounts are not initialized

**Comment by gjsjohnmurray** [comment]
Make sure you are running 1.52, then use the new bisect command to find out which extension is causing the problem.

**Comment by PravinKadwe** [comment]
Thanks for your support. I find out the reason behind the notification  **"Extension host terminated unexpectedly."** 
when we install VSCode ( from the official link (with the recent updates as well ) ) into our system most of the Antiviruses deletes two files from the folders.

[ C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node ]
 AND 
[C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\worker]

These two files get deleted by Antiviruses

**1 ) extensionHostProcess.js** 
Address: 
 C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js

**2) extensionHostWorker.js**
Address:
 C:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\worker\extensionHostWorker.js

**The SOLUTION is: [ I'm using Quick Heal Antiviruses But Steps are the same for most of the Antiviruses ]**

1) open antiviruses then click on the scan option, look for the " Quarantine & Backup " option click on it,

2) Then click on " view files ",  

3) Then from the list of quarantined files restore both the files [ extensionHostProcess.js and extensionHostWorker.js ] individually by clicking on the restore button,

4) Make shower you click in a check box " Add this to exclusion list ",

5) Then click on " Yes ".  

 Well, my problem has been solved by this method.

**Comment by mjbvz** [comment]
Closing since this sounds like a problem with the antivirus program, not VS Code

**Comment by rogierlommers** [comment]
Does this also apply to MacOS? And where do I find these two files?
- extensionHostProcess.js
- extensionHostWorker.js

Running MacOS 11.1 (Big Sur) and facing the problem since a few weeks now.
I'm (forced to) using Carbon Black Cloud (version 3.5.1.13).
