### ISSUE TITLE
Filtering document tree

### ISSUE THREAD

**Issue by MiroJ** [microsoft/vscode#112498]
Issue Type: <b>Bug</b>

The filtering of the document tree recently changed its behaviour. Now (version 1.52.0), the typed term is not searching as a single word but "any letters in the file"

![image](https://user-images.githubusercontent.com/1686322/102129706-cda44280-3e1d-11eb-91f5-5468cad36061.png)

I expect the filtered files to contain the word "css" and not any of the letters at any place in the file name.

This happens with both Filter On Type - ON and OFF.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

**Comment by ArturoDent** [comment]
Probable duplicate: https://github.com/microsoft/vscode/issues/66913

**Comment by isidorn** [comment]
I do not think anything changed here and indeed it looks like a duplicate of that issue, however forwarding to @joaomoreno so he can make a decision

**Comment by joaomoreno** [comment]
Nothing changed here. @MiroJ What makes you say this changed recently? Can you show me a screenshot of the behavior you used to have?
