### ISSUE TITLE
Actions in SubmenuItemAction are not updated on menu change

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#112432]
While using menus/submenus for extensions view actions, I observed that submenu actions' state (enabled/checked) is not getting updated. It seems actions in [SubmenuItemAction](https://github.com/microsoft/vscode/blob/5954c8366d9646958e40bb4e50357afe7f8c22d2/src/vs/platform/actions/common/actions.ts#L305-L305) are not getting updated when the submenu changes (for eg when context keys change).

I fixed it by listening to the menu changes and updating the actions [here](https://github.com/microsoft/vscode/commit/a416c1534bb9159c7ad9d88f19d70019ded16a6a#diff-aaf8a0bc55911640fb6e85531d0e1b0b3325bc11a76ee4240b230b0be4078cf5). But this caused potential listener LEAK - https://github.com/microsoft/vscode/issues/112267. It seems consumers of menus/submenus are not disposing them. So I had to revert my fix and add sub-menu listeners outside menus, while creating the top level menu - https://github.com/microsoft/vscode/commit/5954c8366d9646958e40bb4e50357afe7f8c22d2. 

I think it is unclear and redundant to listen/update submenu changes outside menu service. It would be nice if menuservice / submenu triggers a change event on sub menu changes too.

**Comment by jrieken** [comment]
> I think it is unclear and redundant to listen/update submenu changes outside menu service. It would be nice if menuservice / submenu triggers a change event on sub menu changes too.

So, you want that a menu fires its onDidChange event whenever one of its submenu has changed, right? I think that makes sense. The leaking with `IMenu#getActions()` is real but the MenuItemAction and SubmenuItemAction shouldn't be alive and not listing. The use of the Action type was a pragmatic choice because it was (still is) a popular type back then but in theory those "actions" are only a collection of properties that describe a command. Consumer of menus should call `getActions` in response on a menu change event

**Comment by sandy081** [comment]
> So, you want that a menu fires its onDidChange event whenever one of its submenu has changed, right?

Thats right. To be more specific even when submenu's action property (like enablement / checked) has changed.

**Comment by jrieken** [comment]
> Thats right. To be more specific even when submenu's action property (like enablement / checked) has changed.

Thought more about that and I believe that I don't want. A menu is "self contained" and under normal circumstances a submenu should not affect the rendering of its parent. There you either re-create menu or sub-menu every time you render them or keep the menus alive and listen to event individually.

**Comment by sandy081** [comment]
Closing this as we agreed upon consumer manages collecting menu and submenus and update them when each of them changes.
