### ISSUE TITLE
Indicate menus better in the activity bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112458]
Extracted from https://github.com/microsoft/vscode/issues/112237

<img height="700" src="https://user-images.githubusercontent.com/35271042/101814637-454b3800-3ad3-11eb-8d6c-9eab6dcc9571.gif">

**Comment by sbatten** [comment]
@misolori with the web menu changes, do we need this anymore?

**Comment by misolori** [comment]
This is no longer needed, closing.
