### ISSUE TITLE
Cannot Add Breakpoints

### ISSUE THREAD

**Issue by bmatt468** [microsoft/vscode#112482]
Issue Type: <b>Bug</b>

On the newest version, I am no longer able to add breakpoints within the IDE via:

- Clicking the sidebar beside the line number
- Selecting `New Breakpoint` -> `Inline Breakpoint`

Starting VS Code without extensions (`code --disable-extensions`) does not resolve the issue

Manually downgrading to October 2020 (version 1.51) allows breakpoints to be added as anticipated.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id fd59f538-7605-4609-a55e-5caaba177754|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-json|and|1.5.0
vagrant|bbe|0.5.0
vscode-intelephense-client|bme|1.5.4
laravel-blade|cjh|1.1.2
jquerysnippets|don|0.0.1
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
php-debug|fel|1.13.0
php-pack|fel|1.0.2
file-icons|fil|1.0.28
vscode-jest-runner|fir|0.4.31
auto-close-tag|for|0.5.9
vscode-mysql|for|0.4.0
go|gol|0.19.1
apex|Joh|1.0.4
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.8.1
sublime-keybindings|ms-|4.0.7
phpdoc-comment-vscode-plugin|rex|1.3.0
code-spell-checker|str|1.10.2
serverless-ide-vscode|Thr|0.5.28
lorem-ipsum|Tyr|1.2.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30233462
vsjup459:30229593

```

</details>

**Edit**: This appears to be a duplicate of #112288. Question for the choir, shouldn't `code --disable-extensions` have caused it to work in this case?

**Comment by gjsjohnmurray** [comment]
> This appears to be a duplicate of #112288. Question for the choir, shouldn't `code --disable-extensions` have caused it to work in this case?

/duplicate assuming you are trying to set breakpoints in PHP code. See https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329 for a workaround.

If you disable all extensions I don't think you'll have **any** debug support for PHP.

**Comment by bmatt468** [comment]
> If you disable all extensions I don't think you'll have any debug support for PHP.

Yea, that's on me. Got confused about what's native VS Code v. what's added via an extension. Appreciate the time!
