### ISSUE TITLE
Rename, Drag and Drop Fail with Long Compact Folder Names

### ISSUE THREAD

**Issue by karlhorky** [microsoft/vscode#112463]
- VSCode Version: 1.52.0
- OS Version: macOS Big Sur 11.0.1 

The actions rename, drag and drop fail when the filenames are long enough to cause compact folders (aka **compressed folder rows** or **compressed nodes**) to be cut off with an ellipsis.

These actions were first added in https://github.com/microsoft/vscode/pull/84782 by @joaomoreno

Steps to Reproduce:

1. Create a parent folder with a long name and drag a child folder into it (make sure the combined names are long enough to extend beyond the folder tree pane and that they are cut off by the `...` ellipsis)
2. Create a third folder outside the parent folder and then try to drag into the parent folder to be a sibling of the child folder (by dragging precisely to the parent folder)
3. The third folder becomes a child of the child instead 💥

This also applies to renaming and dragging and possibly other actions.

![Kapture 2020-12-14 at 12 41 48](https://user-images.githubusercontent.com/1935696/102078313-0686ec00-3e0b-11eb-9c8c-778b1e1cf283.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this, however I believe we already have an issue tracking this, I was just not able to find it.
Though for now loeaving this open.

@joaomoreno if he maybe remembers the other issue

**Comment by joaomoreno** [comment]
I don't think we have this open. If you can find an exception related to the tree let me know @isidorn.

**Comment by karlhorky** [comment]
Ah @isidorn this means this bug will not be addressed?

**Comment by isidorn** [comment]
Correct. We are transferring the ownership of the file explorer to a new engineer, so I am closing issues that I think we can live with. Sorry about that.
