### ISSUE TITLE
Feature request: exclude Remote extensions from extension bisect

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#112473]
I'd like Remote extensions, such as Remote SSH, to be excluded from extension bisect (at least when extension bisect is started while in a remote session). My bisects fail in half of the cases because Remote SSH is in the first half of the extensions being disabled, so I cannot even connect to the workspace in which I would like to verify if the problem is now good or still bad, and enabling it manually seems to stop the bisect.

**Comment by jrieken** [comment]
Handling as bug and fixing for Jan 21
