### ISSUE TITLE
alt+left-click vs. ctrl+left-click to open file to the side

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#112467]
https://code.visualstudio.com/updates/v1_52 mentions:

>We changed all of our custom trees (the ones used in the Extensions or Git views, for example) to work more consistently like other built-in trees (such as the File Explorer). This means, the following interactions now apply to all of them:
>
> - Double-click or mouse-middle-click to open in non-preview.
> - Enter to open in non-preview mode (Space to open in preview mode).
> - Alt+Click to open an editor to the side of the active one.

Alt+Click (left-click) works just fine in the File Explorer. But when using `ctrl+p` (or `ctrl+e`) to quick open a recent file, the shortcut suddenly is Ctrl+Click (left-click) if you want to open it to the side.

Shouldn't they be the same for consistency?

**Comment by bpasero** [comment]
@thernstig good observation, however we reserved `Alt` key from pickers to open is reserved to open the editor non-preview if preview is enabled in settings. But since we recently changed the default of this setting to not open as preview from pickers, I pushed a change so that `Alt` key opens to the side in that case. Only if `workbench.editor.enablePreviewFromQuickOpen: true`, we don't.

**Comment by thernstig** [comment]
Great!

Not sure about the reasons, but maybe having `alt+click` always to the side, but have `ctrl+click` open in preview (if enabled with `workbench.editor.enablePreviewFromQuickOpen: true` could have worked to make it all-over consistent? Meaning that `ctrl+click` when `workbench.editor.enablePreviewFromQuickOpen: false` would _also_ open to the side.

Reason why I say this is that it seems that `alt+click` always open to the side form built-in trees. And always in preview mode. No matter if the above setting is true or false.

**Comment by bpasero** [comment]
I think we are fine now given that the default setting has preview disabled. I doubt a lot of users have that setting changed.
