### ISSUE TITLE
How to uninstall/disable GitHub extension?

### ISSUE THREAD

**Issue by crazydef** [microsoft/vscode#112452]
- VSCode Version: 1.51.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Launch VSCode with Git extension disabled.
2. See the super annoying popup with the following message:

"Cannot activate the 'GitHub' extension because it depends on the 'Git' extension, which is disabled. Would you like to enable the extension and reload the window?"

Does this issue occur when all extensions are disabled?: Yes

How do I uninstall or disable the GitHub extension?  It's not listed as an extension.  I never installed it.  I don't want it installed.  I'm never going to use it.

**Comment by gjsjohnmurray** [comment]
In the Extensions view enter `@builtin` as the filter. You should then see it in the list, from where it can be disabled.

**Comment by crazydef** [comment]
wow.  That's a bit random.

Thanks.
