### ISSUE TITLE
Native Notebooks - Cell output is rendered twice

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#112499]
Version: 1.53.0-insider (user setup)
Commit: 96b426ef1da0f0a51ce9ef1931cd1fd2322547e4
Date: 2020-12-14T05:59:27.649Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open Command Pattle, run command Jupyter: Create New Blank Jupyter Notebook.
1. After the new notebook is opened, type something like 123 then press Shift + Enter.
(Make sure you're using Native Notebook Editor)
1. You can see the output is 123123, which should be 123 only.

Taken from https://github.com/microsoft/vscode-jupyter/issues/4222

Does this issue occur when all extensions are disabled?: No

**Comment by DavidKutu** [comment]
This issue is likely not related to the one brought up by the bot.

**Comment by rebornix** [comment]
It's already fixed in master but not shipped yet
