### ISSUE TITLE
Configure Overview Ruler Souce Control Indicators

### ISSUE THREAD

**Issue by xixixao** [microsoft/vscode#112429]
Similar to #46201, but I want to configure the source control indicators (primarily I want to turn them off), and the search indicators (their color is too close to warnings color). How can I do that, while keeping the source control indication in the gutter? I would like to keep the overview ruler to errors and warnings (I already have source control indicated in the minimap, and in general it's not very useful and clutters a lot the actual important signal of warnings and errors).

<img width="20" alt="Screen Shot 2020-12-13 at 21 39 32" src="https://user-images.githubusercontent.com/1473433/102044457-e4c83d80-3de7-11eb-80af-4df79259f5cf.png">

Thanks!

**Comment by alexdima** [comment]
@xixixao You can try the following settings:
```
"workbench.colorCustomizations": {
	"editorOverviewRuler.addedForeground": "#1E1E1E",
	"editorOverviewRuler.modifiedForeground": "#1E1E1E",
	"editorOverviewRuler.deletedForeground": "#1E1E1E",
	"editorOverviewRuler.findMatchForeground": "#1E1E1E",
}
```

**Comment by xixixao** [comment]
Awesome, can we document all of these somewhere besides github issues?

**Comment by xixixao** [comment]
And also one more I can't find in the registry: What is the name for the color used to highlight other occurrences of the current selection?
<img width="1366" alt="Screen Shot 2020-12-14 at 19 17 04" src="https://user-images.githubusercontent.com/1473433/102166440-2830b380-3e9d-11eb-9a13-d74d72dcd485.png">

**Comment by alexdima** [comment]
* Here is the documentation: https://code.visualstudio.com/api/references/theme-color
* the selection highlight color is `editorOverviewRuler.selectionHighlightForeground`
