### ISSUE TITLE
Task behaves different from VS built-in terminal

### ISSUE THREAD

**Issue by iband** [Microsoft/vscode#11241]
- VSCode Version: 1.4
- OS Version: macOS 10.11.6

Why running the same python file with simple command: `print("данные")` shows `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)` error if it's run as Task, while running the same file from built-in terminal shows output correctly?

**Comment by dbaeumer** [comment]
Dups #3550
