### ISSUE TITLE
Open a local program from Codespaces

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#112489]
It would be useful in Codespaces to have the ability to open a local program on the host computer. For example, in the Azure Storage extension we have functionality to open resources in Storage Explorer which runs that program locally alongside VS Code. But since Codespaces runs in a sandbox I couldn't find a way to open local programs.

**Comment by sandy081** [comment]
Moved to https://github.com/github/codespaces/issues/2020

**Comment by wwlorey** [comment]
@sandy081 it looks like the Codespaces repo has been deleted or moved. How should this issue be tracked?

**Comment by sandy081** [comment]
Seems the repo was made private. Will check and let you know what is the suggested approach for users to track issues in codespaces.

**Comment by sandy081** [comment]
@wwlorey Please open a discussion item for this here - https://github.community/c/code-to-cloud/codespaces-beta/45
