### ISSUE TITLE
Extention host consume 100% of the cpu

### ISSUE THREAD

**Issue by Nasseratic** [microsoft/vscode#112466]
Issue Type: <b>Bug</b>

After the recent update, vscode insiders use 100% of a cpu core! I think the issue is related to git extention..

VS Code version: Code - Insiders 1.53.0-insider (76436a4d43566cd313629799e2ec51b4d00caa64, 2020-12-11T17:35:42.622Z)
OS version: Linux x64 5.9.10-1-MANJARO snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 4200)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|15.46GB (6.07GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 2d677874-95ca-4763-a04e-9a4bef915646|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
atlascode|atl|2.8.5
vscode-intelephense-client|bme|1.5.4
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
sftp|lix|1.12.9
vscode-docker|ms-|1.8.1
vscode-kubernetes-tools|ms-|1.2.1
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-tslint-plugin|ms-|1.3.0
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
tslint-vue|pro|1.5.6
vscode-yaml|red|0.13.0
vscode-nginx|sha|0.6.0
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.0.0
twig|wha|1.0.2
gruvbox-concoctis|whe|10.30.27

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by ClementNerma** [comment]
I don't know if this is related to the git extension or not, but I get the exact same problem. Disabling of my installed extensions don't solve the problem, but downgrading to the previous version (october 2020) does.

I tried to update Git as well to the latest version but that didn't change anything.

The problem only occurs when I go in a TypeScript file (I haven't tried with other languages), on text files the CPU usage spikes on startup but becomes reasonable after a few seconds.

**Comment by alexdima** [comment]
**NOTE**: **Be sure you are using a version of VS Code >= 1.52** 
It looks like the issue is caused by one of your installed extensions. All extensions execute together on a single nodejs process, so in order to narrow down the possible problematic extension, please try the following:
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |

**Comment by shanewaz-abbas** [comment]
I'm encountering the same issue on remote ssh development. It doesn't happen when I switch back to the previous vscode version.
``` 
> top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29414 user +  20   0 1337260 145368  32908 R 100.3  0.4   1:33.33 node
```

```
> ps -p 29414 -o args
/home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/node /home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/uriTransformer.js
```

```
Version:          Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS Version:       Windows_NT x64 10.0.20277
CPUs:             Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)
Memory (System):  15.92GB (9.13GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 9415ca2d-428d-4375-9e17-ac402db86067
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       83    2524  code main
    0       91     640     shared-process
    0       67    1548     utility
    0      172    7028     gpu-process
    2      226    7248     window (pid.txt - imports [SSH: 192.168.205.15] - Visual Studio Code)
   18      107    1036       extensionHost
    0        5    8980       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\Shanewaz\AppData\Local\Temp\vscode-linux-multi-line-command-192.168.205.15-408905290.sh" | "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 60560 "192.168.205.15" bash) & exit /b 0
    0       10     340         "C:\WINDOWS\System32\OpenSSH\ssh.exe"  -T -D 60560 "192.168.205.15" bash
    0        7   11880       console-window-host (Windows internal process)
    0       24   13896     crashpad-handler



Remote:           SSH: 192.168.205.15
OS Version:       Linux x64 5.4.0-48-generic
CPUs:             Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (8 x 3777)
Memory (System):  31.26GB (18.67GB free)
VM:               0%
```

**Comment by shanewaz-abbas** [comment]
@alexdima  I'm encountering the same issue on remote ssh development. It doesn't happen when I switch back to the previous vscode version.
``` 
> top
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
29414 user +  20   0 1337260 145368  32908 R 100.3  0.4   1:33.33 node
```

```
> ps -p 29414 -o args
/home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/node /home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/user/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/out/vs/server/uriTransformer.js
```

```
Version:          Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS Version:       Windows_NT x64 10.0.20277
CPUs:             Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)
Memory (System):  15.92GB (9.13GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 9415ca2d-428d-4375-9e17-ac402db86067
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       83    2524  code main
    0       91     640     shared-process
    0       67    1548     utility
    0      172    7028     gpu-process
    2      226    7248     window (pid.txt - imports [SSH: XXXXXXX] - Visual Studio Code)
   18      107    1036       extensionHost
    0        5    8980       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\XXXXX\AppData\Local\Temp\vscode-linux-multi-line-command-192.168.205.15-408905290.sh" | "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 60560 "192.168.205.15" bash) & exit /b 0
    0       10     340         "C:\WINDOWS\System32\OpenSSH\ssh.exe"  -T -D 60560 "192.168.205.15" bash
    0        7   11880       console-window-host (Windows internal process)
    0       24   13896     crashpad-handler



Remote:           SSH: XXXXXXXXX
OS Version:       Linux x64 5.4.0-48-generic
CPUs:             Intel(R) Xeon(R) CPU E3-1246 v3 @ 3.50GHz (8 x 3777)
Memory (System):  31.26GB (18.67GB free)
VM:               0%
```

**Comment by Nasseratic** [comment]
The issue disappeared! I think it has been fixed by the extension update maybe!

**Comment by alexdima** [comment]
@shanewaz-abbas Can you consistently reproduce? The high CPU usage appears in the extension host process, which is the process where extensions execute, so any of the running extensions could be causing the high CPU usage. 

You can see a list via `F1 > Show Running Extensions` or you can also see the running extensions by going through the log using `F1 > Show Logs... > Remote Extension Host`. If you found consistent repro steps that involves a specific extension, please create an issue directly against the extension, as the extension authors might have more context in realising what is needed to reproduce or might be aware of similar issues.

**Comment by shanewaz-abbas** [comment]
@alexdima Yeah I can consistently reproduce, by running the Java debugger. Have tried disabling other extensions to no luck. I cannot disable the java extension as that is what I use to reproduce the issue. Looked at the logs but they are not giving out anything helpful. I looked at `code --status` and extensionHost is saying 0% cpu, so I don't think extensionhost is the problem. Something about the java debugger is causing an issue in the remote ssh host in the latest update:
```
> top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                          
 2612 xxxxxxx+  20   0 1498564 163416  34016 R 100.0  0.5  14:53.38 node
```
The above is the result from running `top` in the ssh host I'm connected to.
The only way I've been able to get around it is by downgrading vscode to previous update 😢. I want to post an issue in the java github issues page but not sure they can do much to help here.

**Comment by shanewaz-abbas** [comment]
Actually never mind, looking at some of the issues others have posted, I may not be alone
https://github.com/redhat-developer/vscode-java/issues/1743

**Comment by alexdima** [comment]
@shanewaz-abbas Thank you for the extra information. This prompted me to check what our code does. This might be caused by our new automatic port forwarding feature which scans the remote OS for available ports in order to forward them locally (https://github.com/microsoft/vscode/issues/112843)

**Comment by alexr00** [comment]
@shanewaz-abbas would you be willing to try the following steps? This would help us confirm that we've found the issue, and you'll also get to use a more up-to-date version.

1. On your remote machine, add the following line to your .bashrc file: `export VSCODE_DISABLE_PROC_READING=true`
2. Install [VS Code Insiders](https://code.visualstudio.com/insiders/)
3. Try to repro your original issue with VS Code Insiders. 

Setting that environment variable will cause VS Code (insiders only right now, I'll make a proper fix that doesn't involve an environment variable for the next stable release), to not do the proc filesystem reading that we do to automatically forward ports for you. This does mean that automatic port forwarding will not work while you have that environment variable set.

**Comment by shanewaz-abbas** [comment]
Hey @alexr00 , setting the environment variable had no effect. It was still forwarding ports automatically. I had it set in the ssh host and it wasn't taking effect. Was I supposed to set it in the ssh host or the OS where vscode insiders is installed?

**Comment by alexr00** [comment]
Setting it in the ssh host is correct. It seems that VS Code isn't picking up the new environment variable though. @alexdima is the remote extension host run in some way that it won't source the users .bashrc file?

**Comment by alexdima** [comment]
@alexr00 Here is what I have tried and works for me:
1. ssh into linux machine
2. edit `~/.bashrc`
3. add
```
export VSCODE_DISABLE_PROC_READING=true
export SOME_ENV_VARIABLE=true
```
4. edit `~/.vscode-server-insiders/bin/4a875e23d20b64504a818834f3fa4c40adb8d480/extensions/typescript-language-features/dist/extension.js`
5. search for the `activate` function in the minified code and add
```
    console.log(`TS activated`);
    console.log(JSON.stringify(process.env));
```
6. restart linux machine
7. connect to it again via SSH and open a `.js` file

I see the environment variables in the console output:
```
...
  "VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH": "/home/alex/.vscode-server-insiders/bin/4a875e23d20b64504a818834f3fa4c40adb8d480/remote/node_modules",
  "VSCODE_DISABLE_PROC_READING": "true",           <------------------
  "LS_COLORS": "",
  "LESSCLOSE": "/usr/bin/lesspipe %s %s",
  "LESSOPEN": "| /usr/bin/lesspipe %s",
  "SOME_ENV_VARIABLE": "true",        <------------------
  "AMD_ENTRYPOINT": "vs/server/remoteExtensionHostProcess",
  "PIPE_LOGGING": "true",
...
```

@alexr00 Does this work for you?

**Comment by alexr00** [comment]
@alexdima yes, that works great for me. I was testing with Containers, and I had some trouble getting the environment variable picked up. With SSH, it works without problem.

@shanewaz-abbas can you make sure you restart your remote machine after adding the variable? You can use steps 4,5, and 7 from @alexdima's post to confirm the variable is picked up.

**Comment by shanewaz-abbas** [comment]
Hi, @alexdima and @alexr00 , The restart linux part did the trick. Now the forward ports automatically is disabled. And as expected, there is no cpu spike anymore. And everything is running smoothly! Although I must say forwarding ports automatically was a nice feature :)

**Comment by alexr00** [comment]
@shanewaz-abbas thanks for confirming! The next insiders build and the next stable release will have a proper fix so you can still have automatically forwarded ports without the bug.

**Comment by jhgg** [comment]
I was affected by the above bug, and can confirm the fix https://github.com/microsoft/vscode/issues/112466#issuecomment-749442688 - am on stable channel, v1.52.1 - ubuntu 18.04 via remote ssh.
