### ISSUE TITLE
Erroneous Locale on MacOS Big Sur

### ISSUE THREAD

**Issue by Smithy80** [microsoft/vscode#112567]
After updating to v1.52 all dates and currencies are formatted in the US format rather than GB format.

When setting a currency format in C# it will show a $ instead of a £ but the larger problem is that the day and months in dates have been reversed. This was highlighted when I had some date dependent code. I wanted to do something where the date was 14th December. In testing I had to format this as 12/14/2020 but then change it to 14/12/2020 for publishing or I would get an invalid date error.

Reverting to v1.51 has resolved this issue. 

I currently use 2 Macs running Big Sur, both of which have had the issue.

**Comment by Smithy80** [comment]
Yes I was developing a .NET Core app then running it through the integrated terminal. When it was published using the GB date settings and then deployed to a server which was set to GB in the locale file, everything showed up as £ and the dates worked correctly.

**Comment by roblourens** [comment]
What is the value of the `$LANG` environment variable with 1.51 and 52? What terminal settings do you have?
