### ISSUE TITLE
1.51.2 breaks debugger breakpoints [xDebug / PHP]

### ISSUE THREAD

**Issue by plueschpruem** [microsoft/vscode#112553]
- VSCode Version: 1.51.2
- OS Version: 10.12.6

Steps to Reproduce:

1. install 1.51.2
2. try to use the debuggers' breakpoints

Does this issue occur when all extensions are disabled?: Yes/No
Did not test, due to workload

After the update I was no longer able to set breakpoints.
Neither keyboard commands, nor clicking the side of the code line invoke a break.
xDebug still works tho, it stops on warnings, functions, etc.
Downloaded the last VSC version and it works just fine.

Not sure if I am the only one with this problem, I was always able to add breaks, even before I installed / started using any debuggers.

**Comment by wengc3** [comment]
I've had the same problem in version 1.52.0. I have to set this setting `"debug.allowBreakpointsEverywhere": true` then it works again

**Comment by plueschpruem** [comment]
> I've had the same problem in version 1.52.0. I have to set this setting `"debug.allowBreakpointsEverywhere": true` then it works again

OK, that did work, **thanks a lot!**
But it wasn't turned on before - yet I was allowed to set breakpoints in any JS/PHP file. odd.

So how would one make breakpoints be allowed without this being true?
Wouldn't be adding the debug setting itself the trigger for that?

**Comment by wengc3** [comment]
In vscode-php-debug there is an issue too https://github.com/felixfbecker/vscode-php-debug/issues/427

**Comment by plueschpruem** [comment]
> In vscode-php-debug there is an issue too [felixfbecker/vscode-php-debug#427](https://github.com/felixfbecker/vscode-php-debug/issues/427)

Ah ok, so it's not me, it's php-debug.

**Comment by weinand** [comment]
php-debug is an abandoned extension that doesn't get any updates. Since they use deprecated functionality, setting breakpoints was broken by the latest VS Code release where we have finally removed the deprecated feature.

Setting `"debug.allowBreakpointsEverywhere": true` is a convenient workaround.

**Comment by RoestVrijStaal** [comment]
@weinand Nuking abandoned extension from the extension marketplace would be more convenient.
