### ISSUE TITLE
Removing several commands from commandsToSkipShell has no effect

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#11257]
Testing #11137
- VSCode Version:1.5.0
- OS Version:Windows 7

Steps to Reproduce:

1. Add default terminal.integrated.commandsToSkipShell
2. Remove workbench.action.terminal.copySelection, Ctrl+Shift+C still copies selected text
3. Remove workbench.action.terminal.toggleTerminal, Ctrl+` still toggles terminal panel
4. Remove workbench.action.terminal.kill, Ctrl+Shift+` still creates new terminal

Perhaps I don't understand how this is supposed to work.

**Comment by octref** [comment]
Also tested in Win 10 and Ubuntu 16.04. Same behavior.

**Comment by gregvanl** [comment]
On Mac OS, removing editor.action.toggleTabFocusMode and workbench.action.quickOpen also don't seem to have any effect.

**Comment by Tyriar** [comment]
Duplicate of #11256
