### ISSUE TITLE
IPC communication to remote hangs forever when disconnected

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112568]
Follow up from https://github.com/microsoft/vscode/issues/112278

The IPC connections (e.g. for file service) are hanging forever even when we know that reconnection is not possible.

**Comment by alexdima** [comment]
Done via 208380cf7663846650621be1802582db57a14890

![image](https://user-images.githubusercontent.com/5047891/102236282-9c964180-3ef3-11eb-884c-c5429999f3cc.png)

**Comment by bpasero** [comment]
Thanks a lot!
