### ISSUE TITLE
php can't add breakpoint

### ISSUE THREAD

**Issue by azagz** [microsoft/vscode#112519]
Issue Type: <b>Bug</b>

when updated vscode 1.52, all php project can't add breakpoint anymore, i restore all default setting and it won't work either, i assume it's a bug

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.75GB (8.70GB free)|
|Process Argv|C:\\Users\\AGz\\source\\repos\\traffic_proj|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
rest-client|hum|0.24.4
customize-ui|ioc|0.1.49
monkey-patch|ioc|0.1.11
vscode-language-pack-zh-hans|MS-|1.52.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0

</details>

**Comment by azagz** [comment]
already found a solution, closed this issue

**Comment by selected-pixel-jameson** [comment]
What's the solution?

**Comment by Bushuo** [comment]
@azagz I am curious as well, what the solution is.
