### ISSUE TITLE
Feature Request: Ctrl + Backspace support for camel case phrases

### ISSUE THREAD

**Issue by mathiasschuetz** [microsoft/vscode#112547]
Hello, it would be nice if you could implement the current function of ctrl + backspace - which deletes whole words instead of letters - on camel case phrases

Example: 
thisIsALongPhrase

1. thisIsALongPhrase
2. thisIsALong
3. thisIsA
4. thisIs
5. this

Currently, if you do ctrl + backspace on camel case phrases it deletes the whole phrase

**Comment by yume-chan** [comment]
<kbd>Ctrl</kbd> + <kbd>Backspace</kbd> binds to `deleteWordLeft` command by default. You can remove this one and create a new one to `deleteWordPartLeft`

```json
  {
    "key": "ctrl+backspace",
    "command": "-deleteWordLeft",
    "when": "textInputFocus && !editorReadonly"
  },
  {
    "key": "ctrl+backspace",
    "command": "deleteWordPartLeft",
    "when": "textInputFocus && !editorReadonly"
  }
```

![GIF 2020-12-16 9-51-24](https://user-images.githubusercontent.com/1330321/102294504-6a80f000-3f84-11eb-9423-af3aae939556.gif)
