### ISSUE TITLE
Too many windows pop up

### ISSUE THREAD

**Issue by johndpope-karhoo** [Microsoft/vscode#11255]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. open different files
2. so many windows

Expected behavior - they should open in tabs by default.

**Comment by dbaeumer** [comment]
VS Code opens files in tabs. Could you provide more detailed steps on how to reproduce this. Or could you attach a screen cast that demonstrates the behavior.

**Comment by johndpope-karhoo** [comment]
I was dragging files /folders into the icon. rather than file open.

**Comment by bpasero** [comment]
Try with `"window.openFilesInNewWindow": false`
