### ISSUE TITLE
Unable to create breakpoint

### ISSUE THREAD

**Issue by afragen** [microsoft/vscode#112520]
Similar issue in the insider version.

Version: 1.53.0-insider
Commit: 96b426ef1da0f0a51ce9ef1931cd1fd2322547e4
Date: 2020-12-14T05:49:14.788Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.2.0

- VSCode Version: 
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

- OS Version: MacOS 11.1

Steps to Reproduce:

1. Open VSCode
2. Attempt to click next to line number or use F9 to create breakpoint

No breakpoint is created.

Does this issue occur when all extensions are disabled?: Yes

**Comment by afragen** [comment]
I did not find a similar issue.

**Comment by afragen** [comment]
It seems there's a new setting to `Allow Breakpoints Everywhere` that needs to be checked.

**Comment by weinand** [comment]
@afragen what debugger are you using?

**Comment by afragen** [comment]
I'm using xDebug. I think I was bitten by the issue in https://github.com/microsoft/vscode/issues/112288 and https://github.com/felixfbecker/vscode-php-debug/issues/424

**Comment by weinand** [comment]
/duplicate #112288

The setting "Allow Breakpoints Everywhere" is not new, it is just a convenient workaround the issue in the abandoned php-debug extension.
