### ISSUE TITLE
Can't enable one snippets extension

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#112532]
Issue Type: <b>Bug</b>

Hello,
I have one extension that I can not enable, and I don't see a reason why.
This is the extension ID:  danielo515.danielo-node-snippets
I would love to see any error message or any hint telling me why.

Regards

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 3bf10e6d-54c9-4df4-8aaa-781f2b9fc1b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (107)</summary>

Extension|Author (truncated)|Version
---|---|---
yaml2json|ahe|0.0.3
project-manager|ale|12.0.1
auto-add-brackets|ali|0.11.0
Handlebars|and|0.4.1
jest-snippets|and|1.8.0
All-Autocomplete|Ati|0.0.23
tailwind-docs|aus|1.4.0
vscode-django|bat|1.0.1
file-browser|bod|0.2.10
vscode-tailwindcss|bra|0.5.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
keymapceditor-vsc|Cia|0.7.6
vscode-devtools-for-chrome|cod|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
python-snippets|cst|0.0.8
danielo-node-snippets|dan|1.8.9
danielo-vsc-tools|dan|1.0.2
vscode-eslint|dba|2.1.14
javascript-ejs-support|Dig|1.3.1
pyinit|Dio|0.0.3
githistory|don|0.6.14
python-extension-pack|don|1.6.0
jest-test-language-support|dpl|1.30.2
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vscode-powertools|ego|0.63.0
prettier-vscode|esb|5.8.0
esy-vscode|esy|0.0.2
vimL|fal|0.0.3
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
reasonml|fre|1.0.38
monkey-c|ghi|0.4.0
lintlens|ghm|3.0.0
vscode-pull-request-github|Git|0.22.0
go|gol|0.19.1
vscode-graphql|Gra|0.3.13
vscode-nginx-conf-hint|han|0.1.0
githd|hui|2.2.4
fuzzy-search|jac|0.0.3
yuml|Jai|3.5.1
search-editor-apply-changes|jak|0.1.1
svg|joc|1.4.2
vscode-peacock|joh|3.9.1
styled-components-snippets|jon|0.10.0
open-in-vim|jon|0.6.0
vscode-styled-components|jpo|1.4.1
magit|kah|0.6.0
vscode-home-assistant|kee|1.13.0
MagicPython|mag|1.1.0
vscode-wrap-console-log|mid|1.7.2
dotenv|mik|1.0.1
vscode-docker|ms-|1.8.1
python|ms-|2020.12.422005962
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-ssh-explorer|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-next|ms-|4.2.20201211
debugger-for-chrome|msj|4.12.11
vscode-purty|mva|0.6.0
color-highlight|nau|2.3.0
incrementor|nms|1.0.3
indent-rainbow|ode|7.4.0
docthis|oou|0.8.2
vscode-react-refactor|pla|1.0.5
python-string-sql|ptw|1.1.0
vscode-yaml|red|0.13.0
partial-diff|ryu|1.4.1
jinjahtml|sam|0.15.0
vscode-javascript-booster|sbu|14.0.1
bash-beautify|sha|0.1.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.2
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.85.0
control-snippets|svi|1.9.1
json-schema-validator|tbe|0.1.0
open-spec-file|the|0.0.6
highlight-matching-tag|vin|0.10.0
template-strings|vit|0.0.6
vscode-icons|vsc|11.0.0
vim|vsc|1.18.5
vscode-ansible|vsc|0.5.2
vspacecode|VSp|0.8.5
whichkey|VSp|0.8.4
vscode-wakatime|Wak|4.0.9
literally-html|web|0.1.3
jinja|who|0.0.8
vscode-file-extra|wil|3.1.0
glean|wix|5.1.0
change-case|wma|1.0.0
disable-eslint-rule|Woo|0.0.2
jinja2-snippet-kit|Wya|2.0.0
template|yon|1.1.5
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6
es6-string-javascript|zjc|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30236573
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30229594

```

</details>

**Comment by jrieken** [comment]
> I have one extension that I can not enable, and I don't see a reason why.

What does that mean?

**Comment by danielo515** [comment]
Hope this screenshot clarifies it.
As you can see, extension is disabled, but the only option I get is to uninstall, there is no option to enable it
![image](https://user-images.githubusercontent.com/2270425/102201485-78703b80-3ec6-11eb-858f-21f383cefce0.png)

**Comment by jrieken** [comment]
letting @sandy081 comment

**Comment by sandy081** [comment]
Can you please try on a different user data directory, eg:

- Start code from command line - `code --user-data-dir <new directory>`
- Install your extension
- Disable it
- Reload window and see if you can enable the extension

**Comment by danielo515** [comment]
@sandy081 followed that steps (`ran code --user-data-dir ~/vscode-data-test
`) and this is what happened:
- All my extensions got installed automatically
- Got a gazillion notifications
- Got a gazillion welcome to XXX screens
- Extensions started to install their dependencies and my CPU skyrocket 
- My extension was already installed in the same state as I described before. I uninstalled, installed again and restarted VSCode. Same result

Will it help if I link to the repo of the extension? I have another extension with the same exact config and that works (not sure why).
Is there any other mode more isolated?

**Comment by sandy081** [comment]
Hmm, let's try it on clean slate by also pointing to a different extensions dir `code --user-data-dir <new directory> --extensions-dir <new directory>`

**Comment by danielo515** [comment]
This is what I tried:

```bash
code --user-data-dir /tmp/user-data --extensions-dir /tmp/extensions
```

I was able to install the extension, but none of the available snippets on any of the contributed file types were suggested.

**Comment by sandy081** [comment]
So is this extension enabled after installing?

**Comment by danielo515** [comment]
Nope, it does not appear as enabled, and I don't get any of the snippets as suggestion, this is how it looks like (it does not says disabled, but doesn't look like an enabled extension either)
![image](https://user-images.githubusercontent.com/2270425/104741366-6691ea80-5749-11eb-8f1e-790223c5d3ba.png)

**Comment by sandy081** [comment]
Seems this extension is disabled in environment. Can you please check if you have following environment args set up anywhere (in your user env or while launching VS Code)

- `--disable-extensions` or
- `--disable-extensions <extensionid>

**Comment by danielo515** [comment]
but wouldn't that disable all extensions and not just one?

**Comment by sandy081** [comment]
If you provide extension id with `--disable-extensions <extension-id>` then only given extension is disabled.

**Comment by danielo515** [comment]
Ok.
I never setup such option in any of my `bashrc`,`.profile` or zsh ini files. What do you mean by environment args set up? Is there any way I can check that from within VSCode?

**Comment by sandy081** [comment]
Can you please enable log level to trace using command `Set Log Level` and provide us with window log available in `F1 > Open View > Log (Window)` ? You can check in that log for `--disable-extensions` configuration.

**Comment by danielo515** [comment]
Hello @sandy081 
Anything else that I should do? 
I set it to Trace, reloaded the window,search for the extension, opened the mentioned window and here is the result. I searched for the disable term with no results.
File is attached
[log-vscode_2021-01-29.log](https://github.com/microsoft/vscode/files/5892278/log-vscode_2021-01-29.log)

**Comment by sandy081** [comment]
Thanks for providing the info. Sorry for not trying this before and I can see the same behaviour. It seems there is an error while activating this extension

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/10746682/106253409-bd062b00-6217-11eb-8e84-fb080c157844.png">

Hence this extension is not loaded and shown disabled.

@alexdima There is no error message shown to the user in this case and none of our UI mention about this.

@danielo515 You have to remove the activation event and publish it again

<img width="203" alt="image" src="https://user-images.githubusercontent.com/10746682/106253684-1706f080-6218-11eb-80c6-6f4bccd2ccb0.png">

@joaomoreno Shall this be validated while publishing ?

**Comment by alexdima** [comment]
> There is no error message shown to the user in this case and none of our UI mention about this

This was an intentional decision from @egamma and @chrisdias . A broken extension does not show an error message. The error message is shown to the user only when the user is doing extension development.

**Comment by sandy081** [comment]
Thanks @alexdima for info.

**Comment by joaomoreno** [comment]
@sandy081 Done: https://github.com/microsoft/vscode-vsce/issues/531

**Comment by danielo515** [comment]
This used to work before.
Thanks for getting to the root cause of the problem.
I understand that you don't want to show popup messages and that stuff, but maybe a small red text on the extension description will save much frustration from users not understanding what is happening. Just my two cents.

Thank you very much.

**Comment by danielo515** [comment]
Removed and published, same problem.
Is this the correct way to define the package.json? Or should I remove the property completely? https://github.com/danielo515/vscode-node-snippets/blob/master/package.json

**Comment by alexdima** [comment]
@danielo515 You are developing an extension, yet you are loading and testing it as if you were a consumer of the extension from the marketplace. VS Code cannot realize that you are actively developing the extension unless you use the `--extensionDevelopmentPath` argument and point to the extension you are developing. This would all be taken care of for you if you would develop your extension by pressing `F5`.

**Comment by danielo515** [comment]
Ok, I have to remove it completely. Now it works.
Thanks.
