### ISSUE TITLE
PHP debugging breakpoints broken

### ISSUE THREAD

**Issue by khoelck0315** [microsoft/vscode#112580]
Issue Type: <b>Bug</b>

Ever since the last update, I am unable to select debugging breakpoints within any PHP file.  Breakpoints are working fine in other types of files.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Windows_NT x64 6.3.9600

**Comment by mjbvz** [comment]
Please file this against your php debugging extension
