### ISSUE TITLE
Odd sytax error

### ISSUE THREAD

**Issue by jshall** [microsoft/vscode#112587]
Issue Type: <b>Bug</b>

I always have a syntax error in my commit message.
![image](https://user-images.githubusercontent.com/6936909/102252620-4b2a8a00-3ed4-11eb-84a3-ecce7e73a467.png)
![image](https://user-images.githubusercontent.com/6936909/102252637-4f56a780-3ed4-11eb-92ac-7b35da92f3c9.png)

I suspect this syntax error is raised by some extension but I have not been able to determine which one.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.73GB free)|
|Process Argv|--folder-uri file:///c%3A/Projects/Brightspace --crash-reporter-id 2a0deae7-d3ec-48bd-bfbd-f8c3b3b6241a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-sqlite|ale|0.10.1
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.9.0
gitignore|cod|0.6.0
data-weave|dat|0.1.1
search|dba|1.1.3
xml|Dot|2.5.1
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
cshtml-tm|fir|1.0.0
gc-excelviewer|Gra|3.0.40
gitattributes|has|0.4.1
svgeditor|hen|2.9.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
yuml|Jai|3.5.1
gpg|jva|0.1.2
envisionbasic|kon|0.0.3
shaderlabformatter|lit|0.4.0
saml-extension|mca|0.0.10
rainbow-csv|mec|1.8.0
ecdc|mit|1.3.0
vscode-scss|mrm|0.9.0
azure-pipelines|ms-|1.177.0
csharp|ms-|1.23.7
mssql|ms-|1.10.0
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
hexeditor|ms-|1.3.0
powershell-preview|ms-|2020.9.0
vsliveshare|ms-|1.0.3303
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
vscode-json-transform|oct|0.1.2
vscode-html-scss|P-d|0.0.42
vscode-yaml-sort|Pas|2.7.2
vscode-auto-scroll|pej|1.0.4
material-icon-theme|PKi|4.4.0
qub-msbuild|qub|0.6.3
vscode-yaml|red|0.13.0
vscode-sort-json|ric|1.18.1
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
yo|sam|0.9.3
gitconfig|sid|2.0.1
vscode-autohotkey|sle|0.2.2
vscode-hexdump|sle|1.8.1
vscode-zipexplorer|sle|0.3.1
code-spell-checker|str|1.10.2
spellchecker|swy|1.3.0
html-preview-vscode|tht|0.2.5
msbuild-project-tools|tin|0.3.10
tmlanguage|Tog|0.9.0
pdf|tom|1.1.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
application-insights|Vis|0.4.2
vscode-icons|vsc|11.0.0
jwt-debugger|yok|0.4.1

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30236573
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459:30229593

```

</details>

**Comment by eamodio** [comment]
@jshall if you disable all extensions does it go away?
