### ISSUE TITLE
Process explorer new tree feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112573]
I noticed how the process explorer now seems to be using the new tree and I think this is a great change 👍 

Some UX things I found meanwhile:
* some columns bleed over [1]
* I can (still?) not click with the keyboard into a row and see a selection and/or use the keyboard to navigate
* clicking a node seems to collapse it without a visual difference (e.g. no twistie) maybe we should prevent that?

[1]

![image](https://user-images.githubusercontent.com/900690/102241207-fcdbb200-3ef8-11eb-9d35-2d9a8254e69c.png)

**Comment by Tyriar** [comment]
Leaky columns is already fixed:

![image](https://user-images.githubusercontent.com/2193314/118280510-233e5300-b481-11eb-85c0-d96eae5b9a11.png)

Moving other issues to more targeted ones:

List styles: https://github.com/microsoft/vscode/issues/123892
Keyboard a11y is captured in https://github.com/microsoft/vscode/issues/120342
Moved twistie issue to https://github.com/microsoft/vscode/issues/123891
