### ISSUE TITLE
Add command for programmatically showing a list of references in the references view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#112507]
## Background
TS just added support for finding all references of a file: https://github.com/microsoft/TypeScript/pull/41805/files. I'm planning on exposing this in VS Code as a command and explorer context menu action. I'd like to show these references in the reference view

## Feature request
Add api commands that let an extension show a list of references in the [references view](https://github.com/microsoft/vscode-references-view/). This would be similar to the builtin `editor.action.showReferences` command

**Comment by mjbvz** [comment]
Sorry if this already exists. I reviewed the code but couldn't find it.

For the command, I'd like to be able to pass:

- An array of reference locations (`vscode.Location[]`)
- The file that triggered the search (possible as a `Location` with the position set to line zero, column zero)
- The search term. This would be the file name itself here

**Comment by jrieken** [comment]
Didn't try this but what could work today is to have this setting `references.preferredLocation: view` and then use the [`editor.action.showReferences`-command](https://github.com/microsoft/vscode-references-view/blob/730800271aa5ef52b1c49608d68f14ee585f7821/src%2Freferences%2Findex.ts#L45). Which raises the question how this should work after all. Should this always be the viewlet or peek or user-preference. I also remember that we have finding file references as general request.

**Comment by jrieken** [comment]
Oh, and then there is also the API the references viewlet export. If you wanna go all custom here: https://github.com/microsoft/vscode-references-view/blob/524e66dea81936167892078baf5d4755fc5a31e4/src%2Freferences-view.d.ts#L22

**Comment by jrieken** [comment]
related/duplicated issue: https://github.com/microsoft/vscode/issues/66162

**Comment by mjbvz** [comment]
Thanks. I took a look at the references-view API but it is pretty complex to implement. I was hoping for something

Could we add an `view` argument to  the `editor.action.showReferences` command? When the user triggers find all references in the explorer, I always want to use the references view instead of showing references in the editor

**Comment by jrieken** [comment]
> Could we add an view argument to the editor.action.showReferences command? When the user triggers find all references in the explorer,

Maybe... It is complicated because the `editor.action.showReferences` comes from the workbench and gets [overwritten](https://github.com/microsoft/vscode-references-view/blob/730800271aa5ef52b1c49608d68f14ee585f7821/src/references/index.ts#L44) by the references-viewlet extension when the `references.preferredLocation`-setting says 'view'. So, the core doesn't know anything about the view and the view would need to always overwrite that command...

Alternatively, we could add another command to the references view which only creates/sets a [`ReferencesTreeInput`](https://github.com/microsoft/vscode-references-view/blob/730800271aa5ef52b1c49608d68f14ee585f7821/src/references/index.ts#L46). That could work, tho I don't know how well the view works without any actual references...

**Comment by mjbvz** [comment]
b565c422aa3a9e789d4c6beeec61269350ab6231 adds a `find file references` command for JS/TS. It is implemented by setting `"references.preferredLocation": "view"`, calling `editor.action.showReferences`, and then trying to restore the user's old setting

**Comment by jrieken** [comment]
That's very "pragmatic" There is also this feature request https://github.com/microsoft/vscode/issues/66162 which asks "file references" to become a concept in VS Code, like other language features. 

@mjbvz Is you current usage only a command to show those references? Do you have plans for more elaborate case like warning use when they delete a file that's still referenced from other files? That would be a nice platform feature and work well across languages, like css-html etc

**Comment by mjbvz** [comment]
Yes, currently I am only using this for showing references although I would like to investigate a safe delete feature too: #52844 

I agree both file references and safe delete make sense in other languages too. I would love to see a `FileReferencesProvider` that JS/TS could implement, while leaving the presentation of the references themselves to VS Code

**Comment by jrieken** [comment]
We have a dedicated request for file references provider and the command for code references. Closing this item as half dupe and half done
