### ISSUE TITLE
integrated terminal doesn't start React development server from wsl2

### ISSUE THREAD

**Issue by danny-p93** [microsoft/vscode#112535]
Issue Type: <b>Bug</b>

I use VScode on Windows together with WSL2 and Ubuntu 18.04.
In my project i work on a little React project, which i created with CRA, so there was a development server automatically build, that starts a new tab in my default browser when i run npm start.
Just after installing V1.52 this morning and nothing other changed the npm start from the integrated terminal does no longer start the new tab. When i run npm start directly in the ubuntu 18.04 (wsl2) terminal it works as expected.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.33GB free)|
|Process Argv|--file-uri file:///c%3A/Users/my/path/to/workspace.code-workspace --crash-reporter-id 539876b6-0154-4876-bed3-c84bf5fc2f6d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|12.35GB (10.95GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
auto-rename-tag|for|0.1.5
remote-wsl|ms-|0.52.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
csharp|ms-|1.23.7
debugger-for-chrome|msj|4.12.11
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30233464
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30229594

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem. See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by danny-p93** [comment]
As requested, here is a gif.
But there is nothing special to see: on both sides i run the same command (npm start).
But the left side where i use the integrated terminal doesn't start my browser as the original ubuntu terminalm on the right side does (and VScode did before V1.52)


![BugReport](https://user-images.githubusercontent.com/32669027/102483094-8a87e080-4064-11eb-90a4-37ad284543c2.gif)

If necessary i can provide a video with better resolution but as said, there is nothing special.

I talked to a colleague who also installed V1.52 and he has the same issue in another project and on WSL1.

**Comment by aeschli** [comment]
What is the URL the browser opens?

**Comment by danny-p93** [comment]
standard CRA: http://localhost:3000

**Comment by aeschli** [comment]
Is this still not working? By guess is that it was related to the $BROWSER variable that we were setting in the integrated WSL terminal (but no longer do)
