### ISSUE TITLE
Very high CPU usage after update in MacOS Big Sur

### ISSUE THREAD

**Issue by Theoton** [microsoft/vscode#112548]
- VSCode Version: 
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

- OS Version:
MacOS Big Sur 11.0.1 (20B29)

Steps to Reproduce:

1. Just open it

Does this issue occur when all extensions are disabled?: 
Yes

I did a test and this extension will cause this problem.
![image](https://user-images.githubusercontent.com/18453647/102206585-d5401600-3f07-11eb-98db-4dd74e0c7629.png)

I executed this command before the above test.
`codesign --remove-signature /Applications/Visual\ Studio\ Code.app/Contents/Frameworks/Code\ Helper\ \(Renderer\).app`

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?:
> Yes
> 
> I did a test and this extension will cause this problem.

Unclear if the problem is caused by one of your extensions.

**Comment by iaroslavglodov** [comment]
I have the same issue Code Helper uses CPU 200%+.
It is ok with the small projects (a few files). But with big projects which worked better with previous OS Catalina.
Tried to find out which Helper is corrupted by `ps aux | grep XXXX` where is XXXX is the PID of the Code Helper, with high CPU usage, found in `Activity Monitor`.
It helped only for some time. Just disabled the extension which used a lot of CPU. But after a while, other extensions started to use CPU highly.

MacOS:
```
$ sw_vers -productVersion
11.0.1
```

VSCode:
```
$ code -v
1.52.0
940b5f4bb5fa47866a54529ed759d95d09ee80be
x64
```

**Comment by dzhgenti** [comment]
The same problem on macOS Catalina after upgrading to 1.52.0. So it probably has nothing to do with Big Sur, but the 1.52.0 update.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Performance-Issues for how to report performance issues.

**Comment by mjbvz** [comment]
Seems like the original poster's issue is caused by an extension

**Comment by iaroslavglodov** [comment]
Just a comment for better understanding.
I could not find an exact extension that used CPU.
But I found out when it happens when I open two windows (projects) in VSCode. The second project is the Magento 2 repository. 
When only one window with the project is open no Code Helper using more than 30%.

**Comment by dzhgenti** [comment]
@iaroslavglodov It's most likely this extension https://github.com/ecmel/vscode-html-css/issues/191. At least it did fix the issue with the performance for me and some other folks. Discussed here https://github.com/microsoft/vscode/issues/112393. The plugin is already fixed, so you need to reload VS Code

**Comment by iaroslavglodov** [comment]
@dzhgenti so true!
It works now with 2 or even 3 different projects open with Magento and others with no high CPU usage! 🤩
