### ISSUE TITLE
The compiler is unable to identify my Comments in code

### ISSUE THREAD

**Issue by Abhilekhgautam** [microsoft/vscode#112559]
Issue Type: <b>Bug</b>

I have commented a sentence in my code. However In the problems section i am being shown that 

identifier "matrix" is undefined [1,19]
expected a';' [1,34]

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (3.25GB free)|
|Process Argv|--crash-reporter-id 36ed88c8-2b5b-4956-992a-c411abf8665c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
exe-runner|bra|0.1.0
c-compiler|bra|0.0.4
c-cpp-compile-run|dan|1.0.13
javascript-ejs-support|Dig|1.3.1
vscode-html-css|ecm|1.1.5
php-intellisense|fel|2.3.14
code-runner|for|0.11.1
rest-client|hum|0.24.4
vscode-clang|mit|0.2.3
cpptools|ms-|1.1.3
java|red|0.72.0
LiveServer|rit|5.6.1
es7-react-js-snippets|rod|1.9.3
open-in-browser|tec|2.0.0
uxcore-snippet|uxc|0.0.6
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.29.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
gulp-run|yod|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30229594

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

**Comment by Abhilekhgautam** [comment]
It is for C

**Comment by mjbvz** [comment]
Thanks. Please start by filing this issue against the C/C++ extension

/extC++
