### ISSUE TITLE
Not brackpoint um PHP

### ISSUE THREAD

**Issue by jorgekg** [microsoft/vscode#112560]
Issue Type: <b>Bug</b>

it is not possible to add breakpoints in php, in other languages they work.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.88GB (6.01GB free)|
|Process Argv|--crash-reporter-id b9b7ee21-e6b8-4f93-aa57-f51b16b18d07|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
ng-template|Ang|0.1100.2
vscode-intelephense-client|bme|1.5.4
phpserver|bra|3.0.1
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
sass-lint|gle|1.0.6
Angular2|joh|11.0.0
twig-language-2|mbl|0.9.2
Angular-BeastCode|Mik|10.0.3
python|ms-|2020.12.422005962
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.2
format-html-in-php|rif|1.7.0
vscode-scss-formatter|sib|2.0.5
twig|wha|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate #112288 where there is a workaround.
