### ISSUE TITLE
Can not set breakpoint in PHP files

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#112564]
1. Install felix becker php-debug extension
2. Open php file
3. Can not set breakpoint 🐛

**Comment by gjsjohnmurray** [comment]
Related #112288

**Comment by isidorn** [comment]
This is fixed, thus closing

**Comment by Abbyyan** [comment]
Can't also set breakpoints on cpp.

**Comment by gjsjohnmurray** [comment]
> Can't also set breakpoints on cpp.

@Abbyyan please open a new issue. Use the option from the Help menu to do this so you include plenty of information. Add repro steps including pasted screenshots if you think they can help.
