### ISSUE TITLE
Problems tab needs to keep compiler error ordering

### ISSUE THREAD

**Issue by pknowlesnv** [microsoft/vscode#112529]
I'm using a Task to build with the visual studio C++ compiler and the `"$msCompile"` problem matcher. Problems are bucketed into files and then sorted by filename. This renders the errors mostly useless. There is no way to tell what the first error was. Often the problem indicated by the first error produces the remaining errors.

- VSCode Version: 1.41.1
- OS Version: Fedora 32

Steps to Reproduce:
1. Create a Task to compile something and use the `"$msCompile"` problem matcher
2. Compile `a.cpp` that includes `b.h` and put a syntax error in `b.h` that would cause further errors in `a.cpp`
3. See the first problems listed in `a.cpp` instead of `b.h`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/62942
https://github.com/microsoft/vscode/issues/55253
