### ISSUE TITLE
Is it possible to call a command registered in an extension from the tasks.json?

### ISSUE THREAD

**Issue by yanchenw** [Microsoft/vscode#11250]
I have a VS Code extension which registered a command via vscode.commands.registerCommand('extension.sayHello').

Is there anyway I can define a task in tasks.json which invokes this command?

```
{
    "version": "0.1.0",
    "command": "vscode", // here
    "isShellCommand": false,
    "args": [],
        "tasks": [
            {
                "taskName": "sayHello", // here
                "suppressTaskName": true,
                "args": [],
                "isBuildCommand": false,
                "showOutput": "always",
                "echoCommand": true
            }
        ]
}
```

Alternatively, is it possible to invoke this command from preLaunchTask in launch.json?

```
    "configurations": [
        {
            "name":"Test",
            "request": "launch",
            "preLaunchTask": "vscode.extension.sayHello" // here?
        }
    ]
```

**Comment by bpasero** [comment]
@dbaeumer please advise.

**Comment by dbaeumer** [comment]
@yanchenw both is not possible.

@isidorn for your interest.

**Comment by isidorn** [comment]
@yanchenw no, it is not possible to invoke an action from a `preLaunchTask` in `launch.json`. Though if tasks would support this it would be possible to just point to a task that triggers this command

**Comment by yanchenw** [comment]
@isidorn is there a plan to support trigger command from tasks?

Also is it possible to subscribe to an event like startDebug to do something in the extension?

Our scenario is we have a shared service library (.NetStandard 1.6), we want to use it in our VS Code extension, the library is hosted in service hub, in our extension we want to do something before debugging started (preLaunchTask), but it seems that there is no way for the extension to either subscribe to the startDebug event or invoking the command from the tasks.

The way I can think of is to implement the service as a CLI tool, then invoke it from the tasks.
Before exploring the CLI route, I want to see if I missed something. 

Please advise.

**Comment by isidorn** [comment]
@yanchenw if this is on the plan is up to @dbaeumer to decide since this item is assigned to him.

Yes it is possible to be activated on event 'onDebug:TYPE', more details: https://code.visualstudio.com/docs/extensionAPI/activation-events#_activationeventsondebug

**Comment by yanchenw** [comment]
@dbaeumer @isidorn actually my problem is not to "activate" the extension but to subscribe to the debug and build event to do something every time user start debug or build. 

The problem is we wrap our service functions in .net dll and try to invoke them in vs code extension using service hub, but it seems hard for current VS extension to support the e2e scenario we need.

@egamma it seems there are some gaps to utilize service hub plus vs code extension, please advise.

Thanks.

**Comment by egamma** [comment]
@yanchenw 

>@dbaeumer @isidorn actually my problem is not to "activate" the extension but to subscribe to the debug and build event to do something every time user start debug or build. 

I recommend to not do this via some subscription mechanism, but your extension should generate a custom task.json and contribute to the launch.config (API for doing this will be added soon).

>The problem is we wrap our service functions in .net dll and try to invoke them in vs code extension using service hub, but it seems hard for current VS code extension to support the e2e scenario we need.

My recommendation would be to write the service functions as a node module that you then consume in VS Code from your extension as a dependency and in VS you consume the service through ServiceHub.

Can you point me to the service functions so that I can understand this scenario better?

**Comment by yanchenw** [comment]
@egamma @dbaeumer @isidorn 

For aspnet core scenario, we'll probably move away from service hub for now and integrate with the new msbuild for custom steps during build/debug. Because dotnet core is moving to msbuild and we need to support round-trip between VS Code and VS, once they finish converting, we get the round trip for free.

For scaffolding in VS Code, we'll extend dotnet cli to do that.

I understand that VS Code is an editor, not an IDE, event subscriptions may not be the right way for editor to interacting with extensions. So feel free to close this issue.

Thanks

**Comment by egamma** [comment]
@yanchenw this approach resonates with me. Thanks for the update.
