### ISSUE TITLE
Rename operation aborted without user interaction

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#112555]
Issue Type: <b>Bug</b>

When I copy a file and then instantly start renaming it, the rename operation is aborted automatically shortly after. This used to behave differently in 1.51.x

It appears that the behavior change is related to SCM. When I paste the copy of the file, it will not have a SCM state indicator next to the name. After the rename operation has been aborted, the green U appears next to the file, marking it as untracked in git.

As this is timing related, you have to be quick or your computer has to be slow enough 😄

![BOxVP0K9yS](https://user-images.githubusercontent.com/1658949/102213757-82e70100-3ed7-11eb-93b3-3c0ce020c6c0.gif)

This is a somewhat rapid succession of Ctrl+C, Ctrl+V, F2. The rename operation is aborted without user input.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (32.90GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (30.39GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (30.39GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (30.39GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.2.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.0.0
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
eslint-disable-snippets|drK|1.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.3.0
vscode-esformatter|how|1.6.0
template-string-converter|meg|0.4.3
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.8.1
vscode-js-profile-flame|ms-|0.0.13
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.1
vscode-xml|red|0.14.0
vscode-yaml|red|0.13.0
lit-plugin|run|1.2.1

(2 theme extensions excluded)

</details>

**Comment by ducalpha** [comment]
I have the same problem with my Python projects. It is so hard to rename files right now because the renaming always aborts in the middle of typing.

**Comment by andriktr** [comment]
+ 1

**Comment by bryan-d** [comment]
Can also confirm that I'm very recently having this issue. Very frustrating.

**Comment by joaomoreno** [comment]
@isidorn This is the file watching bug you fixed recently.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/111652
