### ISSUE TITLE
Source Control broken in 1.53.0-insider build

### ISSUE THREAD

**Issue by bweigel** [microsoft/vscode#112506]
Issue Type: <b>Bug</b>

Current insiders build breaks the source control. The .git repo is not recognized:

![image](https://user-images.githubusercontent.com/6681272/102144943-af166980-3e66-11eb-8922-89b0cae4900d.png)

**About**

Version: 1.53.0-insider
Commit: 96b426ef1da0f0a51ce9ef1931cd1fd2322547e4
Date: 2020-12-14T05:39:59.827Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Linux x64 4.15.0-126-lowlatency snap

VS Code version: Code - Insiders 1.53.0-insider (96b426ef1da0f0a51ce9ef1931cd1fd2322547e4, 2020-12-14T05:39:59.827Z)
OS version: Linux x64 4.15.0-126-lowlatency snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|31.37GB (9.11GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 9db603f8-c4f6-4e97-abb7-f29c25e7a555|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by eamodio** [comment]
Can you provide more information? Does it still happen with the latest insiders?
