### ISSUE TITLE
launch.json

### ISSUE THREAD

**Issue by granat77** [microsoft/vscode#112522]
We
Issue Type: <b>Bug</b>

couldn't find debug adapter descriptor for debug type "launchlisp"
extension might have failed to active

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.47GB free)|
|Process Argv|--open-url --crash-reporter-id a4637da6-6db8-45ef-9674-bf6ebd752ab4 -- vscode://autodesk.autolispext/?pid=13244|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
autolispext|Aut|1.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630

```

</details>

 have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by granat77** [comment]
autocad autolisp extension

**Comment by granat77** [comment]
also 
when i want to launch autocad : 
C:\Program Files\Autodesk\AutoCAD 2021\acad.exe" doesn’t exist. Verify and correct the folder path to the product executable.
it is the correct path

**Comment by granat77** [comment]
autocad autolisp extension



תודה


יעקב גרנט

052-8621312




------ Original Message ------

**Comment by weinand** [comment]
Please see https://github.com/Autodesk-AutoCAD/AutoLispExt/issues/57

**Comment by granat77** [comment]
תודה


יעקב גרנט

052-8621312




------ Original Message ------

**Comment by granat77** [comment]
acadProcessFinder not found


תודה


יעקב גרנט

052-8621312




------ Original Message ------
