### ISSUE TITLE
The text output of the integrated terminal is incomplete!!!

### ISSUE THREAD

**Issue by aheroinustc** [microsoft/vscode#112572]
- VSCode Version: 1.52.0
- OS Version: 

    OS: Arch Linux x86_64 
    Host: VMware7,1 None 
    Kernel: 5.9.14-arch1-1 
    Uptime: 19 mins 
    Packages: 765 (pacman) 
    Shell: zsh 5.8 
    Resolution: preferred 
    DE: Plasma 5.20.4 
    WM: KWin 
    Theme: Breeze [Plasma], Breeze [GTK2/3] 
    Icons: breeze [Plasma], breeze [GTK2/3] 
    Terminal: vscode 
    CPU: Intel i7-8550U (8) @ 1.992GHz 
    GPU: 00:0f.0 VMware SVGA II Adapter 
    Memory: 1180MiB / 7929MiB 

Steps to Reproduce:

Hi , I am a chinese archlinux user . I am using zsh with `oh my zsh` in my kde desktop .
For Konsole,  i  set my terminal's  font with a nerd font and has a perfect output.

However , 

when I switch to the integrated terminal and execute some simple linux commands, such as 'ls`, the text output will be incomplete at this time,  all Chinese context and part of the English output are becoming incomplete. This effect is like a blackboard wiped by a blackboard eraser.

If you reopen the integrated terminal, the full output will be displayed when the command is executed for the first time. If the `ls` command is executed for the second time, the output will be incomplete. Still the third time.

Absolutely  , i have disables all my vscode extensions.
Here is my vscode's  setting.json:

    "terminal.explorerKind":"integrated",
    "terminal.integrated.shell.linux": "/bin/zsh" ,
   
    "terminal.integrated.cwd": "${fileDirname}",
    "terminal.integrated.fontSize": 11,
    "terminal.integrated.fontFamily":"MesloLGS NF",  # this is my nerd font for konsole , its font name is right. 
  
![console2](https://user-images.githubusercontent.com/8321108/102238401-abe7b000-3f30-11eb-8c3b-eea141f24ce9.jpg)
![console](https://user-images.githubusercontent.com/8321108/102238404-adb17380-3f30-11eb-9afa-2ab8da8de069.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
does changing the font or renderer type help?

**Comment by aheroinustc** [comment]
> does changing the font or renderer type help?
ye

"terminal.integrated.rendererType": "dom",

**Comment by aheroinustc** [comment]
> does changing the font or renderer type help?

yes, thks very much.

"terminal.integrated.rendererType": "dom",

**Comment by aheroinustc** [comment]
> does changing the font or renderer type help?
hahaha
![console](https://user-images.githubusercontent.com/8321108/102347398-52888b00-3fdb-11eb-9387-e6f0ffad43a7.jpg)
