### ISSUE TITLE
commandToSkipShell doesn't control showCommands

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#11256]
Testing #11137
- VSCode Version:1.5.0
- OS Version:Windows 7

Steps to Reproduce:

1. Add default terminal.integrated.commandsToSkipShell
2. Remove workbench.action.quickOpen
3. Try Ctrl+P from Integrated Terminal and now ^P shows up in the terminal
4. Now remove workbench.action.showCommands
5. F1 correctly doesn't bring up Command Palette. Show last keys typed instead.
6. Ctrl+Shift+P still brings up Command Palette.

**Comment by octref** [comment]
Same behavior in Win 10 and Ubuntu 16.04. When `workbench.action.quickOpen` is removed, `Ctrl-Shift-P` works while `F1` doesn't.

**Comment by Tyriar** [comment]
This is as designed. Some keybindings are not handled by xterm.js, when this is the case they are bubbled up the vscode.
