### ISSUE TITLE
Add a setting to revert "Preview editor improvements" November 2020

### ISSUE THREAD

**Issue by emptyVoid** [microsoft/vscode#112544]
I'd like VSCode to stop opening new editors when navigating through search results. Essentially reverting preview editor behavior to pre-November 2020 version.

**Comment by gjsjohnmurray** [comment]
Does #112348 and its associated PR resolve this?

**Comment by emptyVoid** [comment]
I guess it does, can't say for sure till it gets released (like in the middle of February?)

PS: I think it's not a good idea to close issues resolutions for which are not yet released. I wouldn't have opened this issue had I found that one.

**Comment by gjsjohnmurray** [comment]
Maybe install Insiders and try it there? It coexists fine with Stable.

**Comment by gjsjohnmurray** [comment]
Probably not in Insiders until tomorrow though.
