### ISSUE TITLE
Collect and deliver (startup) perf marks from extension hosts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#112552]
The main process and renderer process collect timer marks. We use that to track startup performance. We should extend this to also include extension hosts and the agent process, esp. when running in a web/remote scenario. The gist of it is this:

* processes, like extension hosts, should use [`perf.mark`](https://github.com/microsoft/vscode/blob/a4206d19b0db6477717d845c44727cd1a5a65626/src%2Fvs%2Fbase%2Fcommon%2Fperformance.d.ts#L11) to name certain points in time
* when started/ready, all marks should be collected (via [`perf.getMarks`](https://github.com/microsoft/vscode/blob/a4206d19b0db6477717d845c44727cd1a5a65626/src%2Fvs%2Fbase%2Fcommon%2Fperformance.d.ts#L16)) and send to a "central place"
* today, that "central place" is the timer service in the renderer, see [`setPerformanceMarks`](https://github.com/microsoft/vscode/blob/690e9f1e02f98ad22fe5e127838bd96ccbb201ae/src%2Fvs%2Fworkbench%2Fservices%2Ftimer%2Fbrowser%2FtimerService.ts#L346-L347)

The works that needs to be done here is to set mark at meaning full moments and add logic to send those marks to the renderer. 

- [x] extension host
  - ideas for marks: process started, code loaded, hand shake done
- [ ] agent process
  - ideas for marks: process started, server listening, connection established

**Comment by jrieken** [comment]
We should also make sure to add new marks to the inventory: https://github.com/microsoft/vscode/issues/112479

**Comment by jrieken** [comment]
To verify: 

* open F1 > Startup Performance 
* Make sure there are "Raw Perf Marks" sections for the following contexts/processes: main, renderer, local extension host, (maybe) local web worker extension host, (maybe) remote extension host, (maybe) agent process 
* For verify the maybes use VS Code with a remote container or on codespaces

**Comment by JacksonKearl** [comment]
Not seeing anything for "agent" but besides that good.

**Comment by alexdima** [comment]
They were called "server". I can see them in your attached data.
