### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by TristanAdame** [microsoft/vscode#112584]
My Code doesn't want to display images, and when I check other pre-existing code that had already worked, it didn't work.

**Comment by mjbvz** [comment]
Do you mean images in the editor, or in the program you are writing?

/needsMoreInfo

**Comment by TristanAdame** [comment]
![image](https://user-images.githubusercontent.com/76064161/102354845-b88bf880-3f70-11eb-835a-69382c2c4468.png)

![image](https://user-images.githubusercontent.com/76064161/102354989-dd806b80-3f70-11eb-8d56-fb33603cb3a0.png)
