### ISSUE TITLE
Ctrl+C, Ctrl+V Copy Paste in Editor pastes text in terminal since last release

### ISSUE THREAD

**Issue by ceisele-r** [microsoft/vscode#112557]
Issue Type: <b>Bug</b>

Since the last release, copy/paste using Ctrl+C, Ctrl+V in editor seems to be very buggy.

Repro:
* I try to Ctrl+c, Ctrl+V code in the editor

Sometimes, the paste works, sometimes it does not insert any text.
Instead, the text then becomes inserted in the integrated terminal window.

Here are my related keybindings (nothing changed to the defaults here):
![image](https://user-images.githubusercontent.com/54797986/102215715-64ced000-3eda-11eb-90f6-a08fcebfc072.png)

I guess there is something wrong with the focus. I cannot tell what it is because if I am in an editor window and navigate the cursor via my keyboard, the editor window should have the focus.
But after marking text using the keyboard, pressing Ctrl+C, clicking another location in the same editor window and trying to paste the text via Ctrl+v, the text gets pasted in a (sometimes even hidden) integrated terminal.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.76GB (28.87GB free)|
|Process Argv|--crash-reporter-id 0fcfc5d1-d6c4-4a7f-9677-367f3c83f03c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.17.1
flutter|Dar|3.17.0
vscode-eslint|dba|2.1.14
docs-yaml|doc|0.2.6
xml|Dot|2.5.1
prettier-vscode|esb|5.8.0
vscode-guid|hea|1.4.20
vscode-docker|ms-|1.8.1
remote-wsl|ms-|0.52.0
vscode-js-profile-flame|ms-|0.0.13
debugger-for-chrome|msj|4.12.11
awesome-flutter-snippets|Nas|2.0.4
vetur|oct|0.31.3
vscode-yaml|red|0.13.0
vscode-scss-formatter|sib|2.0.5
vsfire|tob|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30233464
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by ceisele-r** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Ctrl-C and Ctrl-V Are Not Working in the Integrated Terminal (#112244)](https://www.github.com/microsoft/vscode/issues/112244)

No duplicate.

**Comment by gjsjohnmurray** [comment]
Please use the new bisect command to check if the problem is being caused by one of your extensions.

**Comment by ceisele-r** [comment]
I did an extension bisect but did not find any harmful extension.
It says "Extension bisect is done but no extension has been identified. This might be a problem with code".
Very cool feature btw. 👍 

**But I could reproduce it now 100%, it happens during debugging.**
Here are the facts/repro:

- Our debug configuration looks like this
```
{
      "type": "pwa-node",
      "request": "launch",
      "name": "Debug App",
      "program": "${workspaceRoot}/server/server.js",
      "internalConsoleOptions": "openOnSessionStart",
      "console": "integratedTerminal",
      "preLaunchTask": "compile",
      "skipFiles": ["<node_internals>/**"]
},
```

```
tasks.json
{
      "label": "compile",
      "command": "npm",
      "type": "shell",
      "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
      },
      "args": ["run", "build"]
    },
```

### Repro:

1. Start debug session
This causes the integrated terminal (Powershell) to open/get focus and starts the compile script (prelaunch-task).
After the prelaunch compile is done, it switches to the Debug Console and starts the app.
2. From now on, copy paste using Keyboard no longer works.
**But if I now manually select the terminal (by clicking the terminal "tab"), copy+paste using the Keyboard starts working again.**
3. After stopping the debug session, the previously copied and pasted text/code gets pasted in the integrated terminal:
![image](https://user-images.githubusercontent.com/54797986/102225360-7074c380-3ee7-11eb-8d73-6318ef4d795d.png)

So my guess is that during the debug session, somehow the integrated terminal keeps the focus.

Another weird thing I noticed is that an integrated terminal gets started when the debug session starts that outputs the same log information as the debug console now. So it is essentially doubled.
To give an overview, these are the consoles available:
ID 1: Original integrated terminal started when starting VSCode
ID 2: Integrated terminal started for the prelaunch task. Performs the prelaunch task and then stays at
![image](https://user-images.githubusercontent.com/54797986/102226206-6a331700-3ee8-11eb-8d52-c8d5e9664a8f.png)
ID 3: Integrated terminal that has the same output as the debug console (this is probably the terminal started as per the `console` setting in the debug configuration) - **in this terminal, the pasted text during the debug session will be pasted after the debug session ended and it's again "ready for input"**

I am actually not sure if ID 3 was started like this in previous VSCode versions.

So I now replaced
```
"console": "integratedTerminal",
```
```
"console": "internalConsole",
```
in the debug configuration and now Copy+Paste works again during debug sessions.


=> I am not sure whether this is now a bug in VSCoe or was a misconfiguration in our debug config. However, in the past, our setup worked the way it was but for me it's also fine to apply the change to internalConsole. I don't think we have any downside from this.
