### ISSUE TITLE
Make loaded scripts view easier to use

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#112582]
> But, you can use our debugger :grin: and “Loaded scripts”. But this is sort of tough because our production sourcemaps don’t have the right paths, and I find using “loaded scripts” kind of tricky, it’s not the scenario we have optimized for -- @roblourens

I find this difficult as well; loaded scripts is not as nice as ctrl+p.

I think one thing that would improve cases is if the loaded script tree view expanded to show matched files when filtering them. At the moment I need to type, toggle into "filter" mode, then expand remaining folders in the tree to find what I'm after.

**Comment by roblourens** [comment]
I can't remember for sure but I think at times I have had to reopen scripts/reset breakpoints after reloading the page. That tends to work pretty smoothly in devtools.

**Comment by isidorn** [comment]
Let's also assign to @weinand since he is the author of the loaded scripts view.

**Comment by connor4312** [comment]
Imo the best experience, if the most drastic, would be to have the loaded scripts in a second group in ctrl+p -- for those which have a sourceRefrence != 0 (don't match up to an existing filesystem file)
