### ISSUE TITLE
vscode will dim when switch tabs

### ISSUE THREAD

**Issue by SeannnnK** [microsoft/vscode#112521]
- VSCode Version: 1.52.0
- OS Version: macOS Big Sur 11.0.1
see below detail:
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Steps to Reproduce:

1. open vscode and open some files in the tab.
2. switch tab to another tab then the screen will dim.

I record a video to let you take a look.
https://1drv.ms/v/s!Alv9WgaOdgFjbII5n4ImFT4yf70?e=nha699

Does this issue occur when all extensions are disabled?: Yes I have disabled all the extensions. But it still has the issue.

**Comment by SeannnnK** [comment]
Does it have any workaround for me? I want to know this is related with visual studio code or related with macOS.

Thanks,
Sean

**Comment by alexdima** [comment]
This looks like the C++ extension unused code dimming. @SeannnnK does this reproduce when disabling the C++ extension?

**Comment by SeannnnK** [comment]
close it. I click one bulb to disable something maybe inactive code dimming.
