### ISSUE TITLE
Smoke tests do not run anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112543]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97127&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=07088cf7-fede-5f74-0d50-155edd53af7d&l=75

```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Multiroot
           "before all" hook for "shows results from all folders":
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-8753Dj8xcDG4GS7L
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           "before all" hook for "starts with 'DE' locale and verifies title and viewlets text is in German":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/test/smoke/out/main.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by joaomoreno** [comment]
They do run, but are flaky. At some point you should just remove that orange flag @bpasero.

![image](https://user-images.githubusercontent.com/22350/102219989-0f240480-3e95-11eb-9758-107aa0f73cd0.png)

**Comment by joaomoreno** [comment]
Here's my suggestion:

Given that we now run this build in CI and DevOps understands the semantics behind our test runs and failures, we will let this run for a longer time and fix according to analytics: the ones which fail more often should be fixed first. And so on and so forth.

![image](https://user-images.githubusercontent.com/22350/102220273-7346c880-3e95-11eb-85d1-ff1050a9af10.png)

**Comment by bpasero** [comment]
@joaomoreno I filed this because of:

```1) VSCode Smoke Tests (Electron)
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-8753Dj8xcDG4GS7L
      at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

This is an error I have never seen before and thought it maybe related to recent build pipeline changes.

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/102222736-1a525100-3ee4-11eb-8007-44055d2892fa.png)

This was never the case until a few days ago, I never got pinged like this before so something must have changed.

**Comment by alexdima** [comment]
@bpasero Is it possible that the scheduled macOS maintenance is affecting Azure as well? -- https://github.com/actions/virtual-environments/issues/2247

**Comment by bpasero** [comment]
Ok thanks for pointing that out, I will keep an eye how it goes during the week.

**Comment by joaomoreno** [comment]
> @joaomoreno I filed this because of:
> 
> ```
>      Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-8753Dj8xcDG4GS7L
>       at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
> ```
> 
> This is an error I have never seen before and thought it maybe related to recent build pipeline changes.

Did you see it happen more than once? I could only find that build 🤔 the builds around that one all passed OK.
