### ISSUE TITLE
rpm dependencies problem for armv7hl 

### ISSUE THREAD

**Issue by czhehua** [microsoft/vscode#112515]
- VSCode Version: 1.52.0
- OS Version: CentOS 7.9 armv7hl (Raspberry Pi 3B)

Steps to Reproduce:
1. # rpm -ivh code-1.52.0-1607640288.el7.armv7hl.rpm
2. rpm dependencies problem:
 error: Failed dependencies:
	libX11.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXcomposite.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXcursor.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXdamage.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXext.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXfixes.so.3() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXi.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXrandr.so.2() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXrender.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXss.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libXtst.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libasound.so.2() is needed by code-1.52.0-1607640288.el7.armv7hl
	libatk-1.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libc.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libcairo.so.2() is needed by code-1.52.0-1607640288.el7.armv7hl
	libcups.so.2() is needed by code-1.52.0-1607640288.el7.armv7hl
	libdbus-1.so.3() is needed by code-1.52.0-1607640288.el7.armv7hl
	libdl.so.2() is needed by code-1.52.0-1607640288.el7.armv7hl
	libexpat.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libfontconfig.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libfreetype.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgcc_s.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgdk-x11-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgdk_pixbuf-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgio-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libglib-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgmodule-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgobject-2.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libgtk-3.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libm.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libnspr4.so() is needed by code-1.52.0-1607640288.el7.armv7hl
	libnss3.so() is needed by code-1.52.0-1607640288.el7.armv7hl
	libnssutil3.so() is needed by code-1.52.0-1607640288.el7.armv7hl
	libpango-1.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libpangocairo-1.0.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libpthread.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	librt.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libsecret-1.so.0() is needed by code-1.52.0-1607640288.el7.armv7hl
	libsmime3.so() is needed by code-1.52.0-1607640288.el7.armv7hl
	libstdc++.so.6() is needed by code-1.52.0-1607640288.el7.armv7hl
	libxcb.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl
	libxkbfile.so.1() is needed by code-1.52.0-1607640288.el7.armv7hl

In armv7hl, libX11 provides libX11.so.6, without (), so all the dependencies must without (), I guess.

**Comment by joaomoreno** [comment]
Can you reproduce with `code-insiders`?
