### ISSUE TITLE
acquireVsCodeApi was initialized too late on Web/iframe in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#112524]
I ran into this issue when running Web or Desktop (with iframe turned on) from master but webview is good. When I opened a github issue notebook and ran a query, I got this error

```
VM11:4 Uncaught TypeError: acquireVsCodeApi is not a function
    at webviewPreloads (<anonymous>:4:24)
    at <anonymous>:487:7
    at main.js:441
```

I verified that there isn't any issue with custom editors. I'm wondering if that's related to how we use `acquireVsCodeApi` in notebook webview.

Together with https://github.com/microsoft/vscode/issues/112326, currently it's not possible to develop notebook webview.

**Comment by rebornix** [comment]
Figured out `globalThis.acquireVsCodeApi` is no longer available. cc @connor4312

**Comment by mjbvz** [comment]
Hey @connor4312, can you please take a look at this since I believe you somewhat recently changed how the API is defined for notebooks

**Comment by connor4312** [comment]
I don't see this in the most recent insiders (with or without `webview.experimental.useIframes` which I think you might have mentioned before). Tried both the existing GH issues notebook and a starter notebook, both works.

Do you still see this / do you have repro steps?
