### ISSUE TITLE
Visual Studo Code "Crashes" and reset all of my settings

### ISSUE THREAD

**Issue by BelminD** [microsoft/vscode#112550]
Issue Type: <b>Bug</b>

## Reproduce
- Sign in to settings sync on same account on at least two machines
- Use vscode for a while, the fans starts to spin up, color theme resets to default and zoom resets to default (vim keybindings still works)

Sorry, not really sure what's causing the issue, I hope the provided logs are helpful.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id c05931f0-434a-4d01-a687-f9197e068886|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
project-manager|ale|12.0.1
vscode-color|ans|0.4.5
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
vscode-relative-line-numbers|ext|0.0.5
theme-monokai-pro-vscode|mon|1.1.18
python|ms-|2020.12.422005962
jupyter|ms-|2020.12.414227025
color-highlight|nau|2.3.0
ayu|tea|0.20.1
vscode-icons|vsc|11.0.0
vim|vsc|1.18.5
vscode-icons-mac|way|7.25.3
material-theme|zhu|3.9.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30233464
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the new bisect command to see if the problem is being caused by one of your extensions.

**Comment by BelminD** [comment]
Thank you, the problem has been identified and is not related to the core of vscode.
