### ISSUE TITLE
Trying to sort Installed Extensions, switches to all Marketplace extensions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#11254]
Testing #11120.

- VSCode Version: 1.5.0
- OS Version: Windows 7

Steps to Reproduce:

1. Switch to Show Installed Extensions
2. ..., Sort By: Rating

@sort:rating is added to search box which shows all Marketplace extensions sorted by ratings.
Same if Sort By: Install Count is used.

**Comment by rebornix** [comment]
I'm too quick to start to verify this issue as it has not been released yet. Will do tomorrow.
