### ISSUE TITLE
Search/Replace misleading key shortcut tooltip

### ISSUE THREAD

**Issue by jakubdabek** [microsoft/vscode#112569]
Issue Type: <b>Bug</b>

In the search/replace dialog when hovering over the `Next match` and `Replace` buttons, both say that the key shortcut is `Enter`,
which is not very useful when I want to skip some matches and replace others. The default binding for `Next match`, the key `F3`, does work when doing that, but I had to find that out elsewhere.

I understand that the bindings are correct when the corresponding inputs (`Search` and `Replace`) are focused, but I would like the shortcuts shown to tell you how to work with both simultaneously without switching focus.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3199)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (3.25GB free)|
|Process Argv|--crash-reporter-id 32641292-c82e-4071-9144-5c8aec315a66|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.0.0
gitlens|eam|11.0.6
go|gol|0.19.1
latex-workshop|Jam|8.15.0
vscode-docker|ms-|1.8.1
python|ms-|2020.11.371526539
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
hexeditor|ms-|1.3.0
rust|rus|0.7.8
vscode-editor-group-minimizer|suh|1.1.0
cmake|twx|0.0.17
shell-launcher|Tyr|0.4.1
tab-groups|usa|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30233462
vsjup459:30229593

```

</details>

**Comment by Xalior** [comment]
Still present, 5 months after it was raised.  

You can't use shortcut keys to "Next Match" when replace is active element, or use shortkeys to "Replace" when find is active element.  Making large, selective, search and replace jobs both much harder, and highly error-prone.


<img width="409" alt="Screenshot 2021-05-19 at 23 40 02" src="https://user-images.githubusercontent.com/114975/118894130-902b7000-b8fb-11eb-8f99-6c9b4c3a73e6.png">

<img width="439" alt="Screenshot 2021-05-19 at 23 38 29" src="https://user-images.githubusercontent.com/114975/118894026-5c504a80-b8fb-11eb-8245-90ed8c593b9e.png">

**Comment by Xalior** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

"Please vote" for accessability issues -- what a joke, what an absolute, offsensive, joke!
