### ISSUE TITLE
cmd+' keybinding used to work

### ISSUE THREAD

**Issue by johnslemmer** [microsoft/vscode#112586]
Issue Type: <b>Bug</b>

Previously I used to be able to bind cmd+' to an action (I use it for go to definition).  But that no longer seems to be working.  I'm not sure when this started, but it definitely used to work in the past.

Steps to reproduce:

- Add the following to the keybindings.json:

```json
      {
        "key": "f12",
        "command": "-editor.action.revealDefinition",
        "when": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor"
      },
      {
        "key": "cmd+'",
        "command": "editor.action.revealDefinition",
        "when": "editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor"
      }
```
- try hitting cmd+' while the cursor is over a variable/class/function that defined elsewhere.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id cc67b08e-8a7f-45aa-b68e-b2b35940532d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.21.1
transformer|dak|1.11.0
vscode-eslint|dba|2.1.14
chmod|dle|1.1.1
xml|Dot|2.5.1
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.62
prettier-vscode|esb|5.8.0
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.9
code-runner|for|0.11.1
endwise|kai|1.4.2
haml|kar|1.3.1
git-graph|mhu|1.28.0
python|ms-|2020.12.422005962
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
vsliveshare|ms-|1.0.3303
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
prisma|Pri|2.13.0
ruby|reb|0.27.0
vscode-yaml|red|0.13.0
code-spell-checker|str|1.10.2
vim|vsc|1.18.5
vscode-ruby|win|0.27.0
file-size|zh9|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry914:30236575
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30229594

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what VS Code detects when pressing `cmd+'`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`cmd+'`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by johnslemmer** [comment]
weird, don't know what to tell you.  Since I posted this my computer has restarted and now I can't reproduce this.  Very strange.
