### ISSUE TITLE
Can't redefine key binding to Alt + `

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/vscode#112528]
- VSCode Version: 1.52.0
- OS Version: Ubuntu 18.04.5

Steps to Reproduce:

1. Open Keyboard Shortcuts window
2. Click on edit icon next to workbench.action.quickOpenNavigateNextInEditorPicker
3. Press Alt + `

This action registers only `Alt` in text input box and displays OS UI preview of open windows. Note that ``Alt + ` ``  
 pressed in any other VS Code editor window has no effect.

**Comment by sandy081** [comment]
Seems this key combination is not getting recognized. @alexdima can you please help user in diagnosing this?

**Comment by alexdima** [comment]
> This action registers only Alt in text input box and displays OS UI preview of open windows

@pauljurczak This indicates that the OS is capturing the keybinding ``Alt + ` `` and it is not reaching vscode at all. There is nothing we can do on our side in this case. You will need to configure the OS to not capture the keybinding. Here is what I found [on StackOverflow](https://askubuntu.com/questions/132304/how-to-disable-alt-backtick-grave)
