### ISSUE TITLE
"Learn more about scanning the task output" should link directly to Problem Matchers

### ISSUE THREAD

**Issue by KyleMit** [microsoft/vscode#112591]
## Problem

When running a task for the first time, you are given the following options:

* Continue without scanning the task output
* Never scan the task output for this task
* Never scan the task output for shell tasks
* Learn more about scanning the task output

![image](https://user-images.githubusercontent.com/4307307/102256482-74014e00-3ed9-11eb-81be-971d8f4730cb.png)

The last option links to:  
[https://go.microsoft.com/fwlink/<b>?LinkId=733558</b>](https://go.microsoft.com/fwlink/?LinkId=733558)

Which redirects to:   
[https://code.visualstudio.com/docs/editor/tasks<b>#vscode</b>](https://code.visualstudio.com/docs/editor/tasks#vscode)

But it would be slightly better to link directly to the section on "Problem Matchers":  
[https://code.visualstudio.com/docs/editor/tasks<b>#_defining-a-problem-matcher</b>](https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher) 

... because it's not entirely clear that's what's meant by "scanning task output"

## Proposed Solution

There are other usages of the referral link at the top of a task definition template, so probably can't just update the redirect address.  Here are all the [usages of `?LinkId=733558`](https://github.com/microsoft/vscode/search?q=733558) in the repo

The option is created in the `abstractTaskService.ts` line here:

https://github.com/microsoft/vscode/blob/1.52.0/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1035

```ts
{ label: nls.localize('TaskService.attachProblemMatcher.learnMoreAbout', 'Learn more about scanning the task output'), matcher: undefined, learnMore: true }
```

Which sets `learnMore: true` which, when clicked, calls the `openDocumentation` method here:

https://github.com/microsoft/vscode/blob/1.52.0/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L856-L858

```ts
private openDocumentation(): void {
    this.openerService.open(URI.parse('https://go.microsoft.com/fwlink/?LinkId=733558'));
}
```

## Action Items

If it's not a requirement that all links go through `fwlink` - I can put in a PR to link to the subsection of the docs, but wanted to check here first

**Comment by alexr00** [comment]
Looks like we have plenty of references directly to https://code.visualstudio.com. Please feel free to make a PR!
