### ISSUE TITLE
Extension search fails to find TeX Comments

### ISSUE THREAD

**Issue by pauljurczak** [microsoft/vscode#112509]
Extension search from EXTENSIONS pane in VS Code with `TeX Comments` query fails to find TeX Comments (https://marketplace.visualstudio.com/items?itemName=vs-publisher-1305558.VsTeXCommentsExtension). It's not in the top 30 results.

Describe the bug

OS and Version: Ubuntu 18.04.5
VS Code Version: 1.52.0

**Comment by sandy081** [comment]
Your extension seems to be a Visual Studio extension and will not be available in VS Code.

**Comment by pauljurczak** [comment]
You are right. It is a bit of a pain to distinguish between `Visual Studio` and `Visual Studio Code` results when searching the web, but that's an entirely different issue. Sorry for false alarm.
