### ISSUE TITLE
Debug Vscode by Nodejs and Express

### ISSUE THREAD

**Issue by maryamsoprano** [Microsoft/vscode#11259]
- VSCode Version:1.3.1
 
Hi,

I am trying to debug  my code inside Visual studio code by launching nodejs.
The procedures are as below:

1- In a specific folder (/home/s/workspace/ myui) I have created  files(server.js,package.json) for node settings:
Note: The path is outside of my project
a)First file is :
server.js:

```
var express = require('express');
var app = express();
app.use(
    express.static("/home/s/git/ui") //where your static content is located in your filesystem
);
app.listen(3002, function () {
  console.log('Express server listening on port 3001!');
});

```
b)second file in that path is:
package.json:

```
{
  "name": "myui",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run server\" ",
    "server": "node server.js",
    "tsc": "tsc",
    "tsc:w": "tsc -w -p /home/s/git/ui"
  },
  "author": "",
  "license": "ISC",
   "dependencies": {
    "concurrently": "^2.2.0",
    "express": "^4.14.0"
  }
}
```

Next, I have a project in different path:(/home/s/git/ui)
 
![projectpath](https://cloud.githubusercontent.com/assets/20918866/18110457/5d2e434c-6f5b-11e6-8eb0-1d1e4b236b0d.png)

and in each folder, there are js and ts files.and there is no a seprated folder for putting all typescript files. all of them are besides their js.

last step is my launch.json:
 
 ````
{
 "version": "0.2.0",
  "configurations": [
        {
            "name": "DEBUG",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/myui/server.js",
            "stopOnEntry": false,
            "args": [],
             "cwd": "${workspaceRoot}",
            "preLaunchTask": "",
            "runtimeExecutable": null,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/app",

            "runtimeArgs": [
                "--nolazy"
            ],
            "env":{
                "NODE_ENV":"development"
            },
            "port": 5858,
            "externalConsole": false

        },
        {
            "name": "Attach to url with files served from ./out",
            "type": "node",
            "request": "attach",
               "stopOnEntry": true,


             "outDir":null,
           "sourceMaps": true,
             "address": "localhost",
       // "preLaunchTask": "",
           "localRoot": "${workspaceRoot}",
            "restart": false,
             "remoteRoot": null,
            "port": 3002

        }
    ]
}
```

 

But when I choose launch for debugging, it just `shows following log in my console and breakpoints are not triggered.

node --debug-brk=5858 --nolazy myui/server.js 
Debugger listening on port 5858
Express server listening on port 3002!

and when I try to attach the project to the specific url, nothing happen.

What is wrong in my settings?

Thanks in advance

**Comment by isidorn** [comment]
Your express server is running and listening on port 3002, your breakpoints should be hit once you go to localhost:3002. More about node debugging can be found here http://code.visualstudio.com/docs/editor/debugging

If after all of that it is still not working you can create a small repository on GitHub for which this problem reproduces and we can investigate.

**Comment by maryamsoprano** [comment]
Thanks for your response. As a matter of fact I have followed the steps of this site.But after running express server, breakpoints would not hit.
As I explained above, in the server part I have just server.js file. there is not any type script file.
I don't know ,outdir should point to which directory?

**Comment by isidorn** [comment]
@maryamsoprano outdir should point to a directory where your typescript is compiled to. So where the built .js files live. If the js files live besides the ts files they you do not need to set the outDir.
You can create a public repository on GitHub with your workspace and we can investigate why the breakpoints are not hit, without that it is very hard to guess what the problem is. Thanks

**Comment by maryamsoprano** [comment]
I have a project in DebugVsCode which is running by express from another path(myuiServer).
After running the project by npm start, corresponding js is created besides the ts files in DebugVsCode. 

My Nodejs server:
https://github.com/maryamsoprano/myuiServer

VsCode:
https://github.com/maryamsoprano/DebugVsCode

**Comment by isidorn** [comment]
@maryamsoprano you did not upload a proper repository. For instance your DebugVSCode repo depends on node_modules in launch.json and there is no top level package.json. Also the launch.json should live inside the .vscode folder

My suggestion is to start from a ts project that you can debug and then slowly convert it to your project folowing the strucutre provided. Our doc tutorials should have some good starting points.
If not @waderyan surely has some awesome videos

**Comment by maryamsoprano** [comment]
Hi again,

I committed a test repo in following path. I hope it would be  completed. it is a test which worked fine in my local .
https://github.com/maryamsoprano/testDebug
