### ISSUE TITLE
editorLineNumber.foreground not working

### ISSUE THREAD

**Issue by firebirddd** [microsoft/vscode#112546]
Issue Type: <b>Bug</b>

"workbench.colorCustomizations": {
    "editorLineNumber.foreground

active line number not change color 

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.05GB free)|
|Process Argv|--crash-reporter-id 864b8d41-e05c-480c-a956-6082c5b1494e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
jsx-html-tags|ang|1.0.0
clipboard-history|Anj|1.0.7
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
vscode-html-css|ecm|1.1.5
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
vscode-google-translate|fun|1.4.9
vue-snippets|hol|1.0.4
vscode-dashboard|kru|2.3.1
vs-color-picker|lih|1.0.0
camelcasenavigation|map|1.1.3
git-graph|mhu|1.28.0
vscode-deploy-reloaded|mkl|0.89.0
debugger-for-chrome|msj|4.12.11
vscode-extension-auto-import|Nuc|1.4.3
vetur|oct|0.31.3
html-to-jsx|ria|0.0.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
vscode-icons|vsc|11.0.0
quokka-vscode|Wal|1.0.335
vscode-import-cost|wix|2.13.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30229594

```

</details>

**Comment by aeschli** [comment]
Use `editorLineNumber.activeForeground` for the active line number.

![image](https://user-images.githubusercontent.com/6461412/102214496-a6f71200-3ed8-11eb-8718-5e83d9bf1d80.png)
