### ISSUE TITLE
Cannot reconnect. Please reload the window

### ISSUE THREAD

**Issue by wjy18666** [microsoft/vscode#112512]
Hello, I encountered such a problem, can you help me solve it? Chrome running vscode often will Cannot reconnect. Please reload the window pop-up, refreshing is useless, the following is my detailed information:
1. Intranet test
Machine configuration and environment: CentOS7.6 32C64G container runs 4C8G nginx without forwarding
Version: code-server: 3.5.0 vscode: 1.48.2
Execution: code server Chrome browser runs vscode without problems

2. Online
Machine configuration and environment:
Bandwidth 100Mbps, mobile network
Machine 48 core 108G
CentOS7.6
Run vscode in the container.
The container limit is 4C8G, and it is forwarded through 3 layers of nginx

Version: code-server 3.5.0 vscode: 1.48.2

Execution: code server running vscode Chrome browser often Cannot reconnect. Please reload the window pop-up window, it is still the same after refreshing

**Comment by roblourens** [comment]
Sounds like you are using code-server, which is not vscode
