### ISSUE TITLE
Bad Font Rendering on Light themes

### ISSUE THREAD

**Issue by diegogarciaa** [Microsoft/vscode#11252]
- VSCode Version: 1.4; 
- OS Version: Windows 10 1607, build 14393.51
- Resolution: 1440 x 900, 18.5 Inches Dell Monitor

Steps to Reproduce:
1.  Open Visual Studio Code, switch theme to Light+ 
2.  Switch theme to Monokai
3. The font rendering quality is way better on dark theme.

Proof:

Light Theme: http://imgur.com/a/u1YA6
Dark Theme: http://imgur.com/a/XDlKe

The truth is: Windows Font Rendering on any monitor with less than 200 ppi will have poor quality. Visual Studio Code should use another font rendering engine

**Comment by alexandrudima** [comment]
All the font rendering eventually happens in Chromium. Therefore, any website in Chrome should suffer from the same. Please feel free to also open an issue with them https://bugs.chromium.org/p/chromium/issues/list

**Comment by diegogarciaa** [comment]
Thanks for the fast response. I will do what you suggested.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
