### ISSUE TITLE
VS Code Task Manager

### ISSUE THREAD

**Issue by PsyLogic** [microsoft/vscode#112566]
Version: 1.52.0 (user setup)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

For Me I have one window project no workspaces, but I do have banch of extensions

It would be better if we have a Task Manager of extensions or VS Code so we can know all details about executed extensions or what it cause of Heigh RAM/CPU

![memory](https://user-images.githubusercontent.com/8070135/102226056-348e2e00-3ee8-11eb-8628-54f2acb79234.png)

Thank you

**Comment by mjbvz** [comment]
Try using the  built-in `process explorer`: https://github.com/microsoft/vscode/wiki/Performance-Issues
