### ISSUE TITLE
Format Document With... Not showing up 

### ISSUE THREAD

**Issue by komen205** [microsoft/vscode#112578]
- VSCode Version: 1.52.0
- OS Version: Windows 10

Steps to Reproduce:

1. Click CRTL + SHIFT +P
2. Write format Document 

I'm not able to change the formatter now

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
What language is this for? Do you have a formatter installed for it?

**Comment by komen205** [comment]
> What language is this for? Do you have a formatter installed for it?

It's .blade and PHP. Yes, I do.
I just wish I could change the formatter but I'm not able

**Comment by jrieken** [comment]
Do you have multiple formatters installed? Format with only show when you have 2 or more formatter for one language

**Comment by komen205** [comment]
> Do you have multiple formatters installed? Format with only show when you have 2 or more formatter for one language

I just had one formatter installed. Added one more and it works.
