### ISSUE TITLE
Debug console sends evalution to parent session which fails

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#112595]
1. Create two js debug sessions
2. Open debug console, manually change the dropdown to the other session
3. try to evaluate something in the debug console -> vs code sends it against the parent session gets an error and no evaluation is shown

**Comment by isidorn** [comment]
If the session is merged with the parent session we  should always send to the child session.
It seems like the drop down incorrectly chooses the parent session

**Comment by weinand** [comment]
@isidorn you said
"If the session is merged with the parent session..."

But in the initial comment I do not see how two unrelated sessions could have a parent/child relation?
The initial problem does not occur if two sessions run in two debug consoles, right?

**Comment by isidorn** [comment]
The two unrelated session do not have a parent/child relation between them.

However each of those two sessions has a parent child relationship with it's wrapper session (since this is using js-debug).

So yes the initial problem was ocurring when those two sessions are running in two debug consoles.

**Comment by weinand** [comment]
Thanks, now I understand. And since we hide the parent now in one-child cases, I was not seeing the parent/child relation anymore...

**Comment by isidorn** [comment]
Correct, sorry for not including the details in the original comment.
