### ISSUE TITLE
Auto-complete adds extra #endregion directive

### ISSUE THREAD

**Issue by cha0tic75** [microsoft/vscode#112596]
- VSCode Version: 1.52.0
- OS Version: Windows 10 Home 1909

Steps to Reproduce:

1. Create an abstract .cs class using #region #endregion to surround relevant regions 
2. Create a new class that inherits from the abstract class created above.
3. Override one of the abstract methods in the new derived class and let auto-complete fill out the method signature.
4. Note the extra #endregion directive

Does this issue occur when all extensions are disabled?: Yes/No  No Which means it is probably from the C# extension

**Comment by aeschli** [comment]
Sorry for the late reply but this needs to be filed against the C# extension: https://github.com/OmniSharp/omnisharp-vscode/issues
