### ISSUE TITLE
Add a page for recent folders / workspaces

### ISSUE THREAD

**Issue by ZZYSonny** [microsoft/vscode#112531]
### Problem
I use VSCode for different folders. Currently I switch between folders using `Recent` in Welcome Page. But every folder in the recent section is small. `File: Open Recent` mixes with single files.

I think the rest of Welcome Page is less useful for people using VSCode for a long time, and switching between folders is a often task. Also VSCode forgots which extension is enabled or disabled in the workspace when they are deleted from Recent folders manually. So it is useful to have a dedicated page for folder management. 

For example, IDEA's startup page gives much more space for every workspace and is much easier to choose.
![image](https://user-images.githubusercontent.com/28442838/102184963-44f3d800-3eeb-11eb-8e7c-da41b5ed8bd0.png)
And VSCode's Recent is much crammed.
![image](https://user-images.githubusercontent.com/28442838/102186405-8be2cd00-3eed-11eb-98ee-7dacac3b2aa9.png)

### Suggested Design
Add a page listing recent folders. For workspace folders, it should be represented in a larger box like customize in startup page. It will be even better to add an icon according to the files / extension. For example, a java project folder with Java extension should show Java icon. (Or just show every extension icon in the box if this is too complicated)

**Comment by ZZYSonny** [comment]
> Hey, thanks for the proposal!
> 
> We've been revamping the welcome page for a bit now:
> ![image](https://user-images.githubusercontent.com/8586769/113041407-c85dd000-914e-11eb-8b80-24d0e325b7cd.png)
> 
> And one idea that came up recently was to change the "empty getting started" list:
> ![image](https://user-images.githubusercontent.com/8586769/113041476-dc093680-914e-11eb-963e-77a18ff2c678.png)
> 
> To instead show a large "recent" list, which I believe would be in-line with your suggestion. Would that help you here?

This is really cool. It will be great if one can pin folders (with some icons) in these empty areas.

**Comment by JacksonKearl** [comment]
Verify: when all getting started walkthroughs are dismissed, the recents list moves to right and expands to show 10 (!) recents.
