### ISSUE TITLE
settings.py激活

### ISSUE THREAD

**Issue by liujuyun** [microsoft/vscode#112583]
Issue Type: <b>Feature Request</b>

我的settinga.py被删掉了，现在不知怎么激活？

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:30.502Z)
OS version: Windows_NT ia32 10.0.19041

**Comment by yume-chan** [comment]
Translation:

> ## settings.py activation
>
> My settings.py has been deleted, now I don't know how to activate?
