### ISSUE TITLE
Inefficient Toggle with Integrated Terminal when Running IPython

### ISSUE THREAD

**Issue by haz-q** [Microsoft/vscode#11253]
- VSCode Version: 1.40
- OS Version: Windows 10 v. 1511
- IPython Version: 5.1

Steps to Reproduce:
1. Open integrated terminal and run `ipython`.
2. In editor (do not hide terminal window), type `print('hello world')`.
3. Highlight text and use VS Code command `Terminal: Run Selected Text in Active Terminal`.

At this stage, the code has loaded into the iPython terminal but has not actually executed.

![capture](https://cloud.githubusercontent.com/assets/21263827/18107572/123a3f36-6ece-11e6-8118-236f8793a3a9.PNG)

The user is required to press Enter in the terminal pane to actually execute the code. (Visual Studio Community with PTVS works as expected: the script runs upon Shift+Alt+F5.) You will notice in the screenshot that after running the selected text, the curor is still in the code panel. Therefore, if you press Enter (in an attempt to execute the code in the terminal pane), your selected text in the editor will be deleted. The only way to complete the code run in the terminal is to, after step 3, either (a) mouse over and click in the terminal panel and hit Enter, or (b) hit Ctrl+` twice to hide and show the terminal panel (which will also focus the panel) and then hit Enter. This is inefficient. The code should either fully execute upon the run command (as it does in Visual Studio) or the terminal pane should automatically focus so the user can hit enter to complete the code run.

Note that when the terminal window is hidden at the time the selected code is run, the terminal opens and is simultaneously focused. The user can then hit Enter to complete the run with little additional effort.

**Comment by Tyriar** [comment]
Right now a `\n` or `\r\n` is added to the end of the selected text (if necessary) to indicate to the shell to run it. Not sure what ipython is expecting here.

**Comment by Tyriar** [comment]
As designed, the Python extension can always polish this experience.
