### ISSUE TITLE
Allow commands from extensions to provide an alias in english locale

### ISSUE THREAD

**Issue by tmitz** [Microsoft/vscode#11266]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

Steps to Reproduce:
1. When using Japanese environment, opened command palette and input "markdown" into command palette
2. Don't complement markdown command

![image](https://cloud.githubusercontent.com/assets/28998/18113028/94b29276-6f67-11e6-91aa-2f6412240049.png)

But, using "マークダウン" (Japanese word), just complement commands.

![image](https://cloud.githubusercontent.com/assets/28998/18113044/b3147252-6f67-11e6-9cb0-c1f41628b42d.png)

I hope can complement commands using English word.

**Comment by dbaeumer** [comment]
@bpasero starting with you since I thought this works without someone doing something. If not please forward to @kieferrm

**Comment by bpasero** [comment]
@dbaeumer since this is an extension contributing commands we need support to provide the english label that we can then use as alias as we do with built in commands.

**Comment by dbaeumer** [comment]
I was busy with TS 2.0.3 aoption. Has to wait a little.

**Comment by tmitz** [comment]
This issue fixed #16087
