### ISSUE TITLE
Git bash terminal dont work in VSC.

### ISSUE THREAD

**Issue by ctacello** [microsoft/vscode#112638]
Issue Type: <b>Bug</b>

Hi, on yesterday i have some problem with source control panel. I try to merge two branches but source control panel dont show me list of files just show number on source control icon and thats all. I try to do this on another PC and this was same. I ask my friend with MacBook and he dont have this problem. So next i try to research problem. If i open my code in another IDE (e.g. atom) i can see all files that i must to stage, so it ok. Next i try update git for windows from CL "git update" and after i cant use Git bash in VSC, if i try use git from other place it works fine.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (5.92GB free)|
|Process Argv|--folder-uri file:///c%3A/xampp/htdocs/athleteportal --crash-reporter-id a613f995-8c60-4c62-ba0b-afd8a1d3eb72|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
js-quick-console|Aha|0.0.3
project-manager|ale|12.0.1
laravel-extra-intellisense|ami|0.4.1
beautify-blade|api|1.0.1
vscode-intelephense-client|bme|1.5.4
laravel-goto-view|cod|1.3.3
vscode-eslint|dba|2.1.14
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
beautify|Hoo|1.5.0
vscode-todo-highlight|jgc|1.2.3
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
php-docblocker|nei|2.1.0
vetur|oct|0.31.3
laravel-blade|one|1.25.0
laravel5-snippets|one|1.10.0
LiveServer|rit|5.6.1
laravel-goto-controller|ste|0.0.12
open-in-browser|tec|2.0.0
vsfire|tob|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by ctacello** [comment]
And i have this file when i try to use git bash in VSC

bash.exe.stackdump

`Stack trace:
Frame        Function    Args
000FFFF4C48  00180063DB0 (000FFFF4E68, 00000000002, 00000000000, 000FFFFDE50)
000FFFFDE50  00180065F9C (00000000064, 00000000000, 00000000360, 00000000000)
000FFFF5370  00180147C18 (0018013EF9B, 00000000030, 00000000030, 00A001BC002)
000FFFF54E0  001800640D6 (00000000000, 00000000000, 00000000000, 000FFFF5B80)
000FFFF5B30  7FF829E9130F (000FFFF5B30, 000FFFF61F0, 00000000000, 000FFFF5630)
000FFFF5B30  7FF829E3B5E4 (000000007A7, 00180351138, 000FFFF64A8, 00000000006)
001005D1D38  7FF829E8FE3E (000FFFF6500, 001005D1D38, 001005DB190, 001005CF044)
001005D1D38  001800B4471 (001005DB190, 00000000000, 008001BA0F0, 00000000002)
001005D1D38  0018016A68B (000FFFFFFFF, 001004234A0, 00000000002, 000003A0000)
001005D1D38  0018013EF9B (000FFFFFFFF, 001004234A0, 00000000002, 000003A0000)
001005D1D38  0010042684B (00180350AB0, 00000000003, 0018015C5D3, 0000000003C)
001005D1D38  00100427402 (000000007F0, 00000000000, 001005D6318, 00000000000)
00000000001  0010042FF35 (001800D851C, 00000000000, 001005D6318, 00000000000)
008001BB100  0010043484E (00100414CF3, 00000000014, 00000000076, 000FFFF685C)
00000000000  00100435B40 (00000000001, 00100000000, 000FFFF697C, 00000000000)
00000000000  00100436C9F (00100000000, 00000000000, 00000000000, 00000000000)
5000001000000002  00100437626 (00000000009, 00000000000, 00000000001, 008001BA770)
5000001000000002  0010043777F (0010041A639, 00000000000, 0080019C550, 00000000000)
5000001000000002  00100430B31 (00000000000, 00100437720, 00800084D30, 00800084D30)
00000000009  00100430FC1 (00000000000, 00000000000, 00000000000, 00000000000)
001005D6558  001004393F6 (0080000001F, FFFFFFFF00000000, 00000000000, 00000000001)
00000000000  001004C11EC (001FFFFFFFF, 00000000000, 00000000000, 0080019B890)
00000000000  00100415650 (00000000020, 00000000000, 00000000000, 0080019B890)
00000000000  00100415571 (0010043D4BA, 00800082C70, 00000000000, 0080019B890)
00000000000  001004178E4 (00000000020, 00000000000, 00000000000, 000FFFFFFFF)
00000000000  0010041552C (0010043D4BA, 00800082C10, 00000000000, 0080019B780)
00000000000  001004178E4 (00000000020, 00000000000, 00000000000, 000FFFFFFFF)
00000000000  0010041552C (0010043D4BA, 00800082BB0, 00000000000, 0080019B670)
00000000000  001004178E4 (00000000020, 00000000000, 00000000000, 000FFFFFFFF)
00000000000  0010041552C (0010043D4BA, 00800082B50, 00000000000, 0080019B560)
00000000000  001004178E4 (00000000020, 00000000000, 00000000000, 000FFFFFFFF)
00000000000  0010041552C (0010043D4BA, 00800082AF0, 00000000000, 0080019B450)
End of stack trace (more stack frames may be present)`

**Comment by eamodio** [comment]
I would recommend opening an issue against Git for Windows
