### ISSUE TITLE
When discarding changes while active process, Git stops working

### ISSUE THREAD

**Issue by animanoir** [microsoft/vscode#112624]
Issue Type: <b>Bug</b>

1. Start `gatsby develop`
2. Discard changes inside VSCode in the Git section

Also, the CPU goes psyrobonkers  and sometimes VSCode simply freezes. **I started having this issue after the last update.**

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
divider|din|2.3.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.0.6
vscode-html-css|ecm|1.1.6
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.8.0
comment-anchors|Exo|1.9.1
beautify|Hoo|1.5.0
path-autocomplete|ion|1.15.0
vscode-gutter-preview|kis|0.26.2
HTMLHint|mka|0.10.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
vsliveshare|ms-|1.0.3303
debugger-for-chrome|msj|4.12.11
indent-rainbow|ode|7.4.0
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
comment-divider|sta|0.3.0
sass-indented|syl|1.8.13
language-pde|Tob|1.4.6
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vscode-import-cost|wix|2.13.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by eamodio** [comment]
It sounds like there might be something up with your setup -- can you post the logs from the Git channel in the Output pane when this happens?
