### ISSUE TITLE
Can not intellisent

### ISSUE THREAD

**Issue by thanhchuongbmd** [microsoft/vscode#112620]
### MacOs 11.1
Can not intellisent all language, I'am using typescript, when I get suggest prototype then VS only show 1 prototype
<img width="1018" alt="Screen Shot 2020-12-16 at 09 29 57" src="https://user-images.githubusercontent.com/67777599/102297134-52f43800-3f81-11eb-8668-5f26ad1de8ae.png">
<img width="1018" alt="Screen Shot 2020-12-16 at 09 30 04" src="https://user-images.githubusercontent.com/67777599/102297143-57205580-3f81-11eb-8c03-12668cd1c693.png">

**Comment by thanhchuongbmd** [comment]
Re-install VS code is working ok

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"
