### ISSUE TITLE
Number in Ports panel title doesn't update when removing ports

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#112692]
- Forward a port
- Click the X to delete it
- The title still says (1)

![image](https://user-images.githubusercontent.com/323878/102418663-07f31880-3fb3-11eb-996a-94941cbe387a.png)

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/3776ba6be2f987feed4424386be14b6662d5cce2

**Comment by JacksonKearl** [comment]
I don't have any number showing up here?

![image](https://user-images.githubusercontent.com/8586769/106079410-021c4700-60ca-11eb-92bc-a29b46a648f6.png)

**Comment by roblourens** [comment]
That's weird. Also I have 6 when maybe it should include the "Existing Tunnels" (or maybe not, I'm not sure)

![image](https://user-images.githubusercontent.com/323878/106086802-b2dd1300-60d7-11eb-8b0c-a31cb66b13bc.png)

**Comment by alexr00** [comment]
@JacksonKearl you'll only get the number there if you end up in the experiment group where we put the ports view in the panel. If you just dragged it there, then there will be no number

@roblourens I don't have existing tunnels included in the count. I don't have a strong preference on whether is should be included. What do you think?

**Comment by roblourens** [comment]
Ok. I'm not sure, I don't think I have a strong preference either. It's fine as-is
