### ISSUE TITLE
When developing electron, the compiled app.asar package is occupied by vscode

### ISSUE THREAD

**Issue by PanchengPcFine** [microsoft/vscode#112616]
When developing electron, I used electron-builder for packaging, but vscode has been occupying the app.asar resource package, resulting in failure to package normally

**Comment by deepak1556** [comment]
Can you provide a minimal test case that demos the issue, thanks!

**Comment by ihhu** [comment]
I also encountered the same problem.

As long as the project is opened by vscode, any asar package file under the project will be occupied by vscode, resulting in failure to recompile the asar package file of the Electron project.

No effective solution has been found yet, I think this is a bug.

I use vscode version 1.52.0.
