### ISSUE TITLE
Valid values for "files.encoding" in settings.json

### ISSUE THREAD

**Issue by lukefan6** [Microsoft/vscode#11269]
- VSCode Version: 1.4.0
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Open settings.json
2. Try to assign "big5" to "files.encoding"
3. An error message saying "Value is not accepted..." appeared

I wonder why there are encoding limitations for workspace file encoding?
Anyway that we can work around this?
I really want files in certain folder be opened with big5 by default, no need to change it every time it get opened.
Thanks.

**Comment by bpasero** [comment]
It is `cp950`

**Comment by lukefan6** [comment]
Thanks for prompt reply, the setting worked.
However, cp950 is not in the "Valid values" suggested in the tooltip when an invalid encoding is typed.
Does that mean somewhere there's something like "Valid Encoding Suggestion" that needs to be updated?

**Comment by bpasero** [comment]
Does for me:

<img width="613" alt="screen shot 2016-08-31 at 10 22 15" src="https://cloud.githubusercontent.com/assets/900690/18121439/d18355f8-6f64-11e6-9f37-05885ced8f32.png">
