### ISSUE TITLE
Change default editor tab size from 4 to 2 spaces

### ISSUE THREAD

**Issue by tsongas** [microsoft/vscode#112615]
Please change the default editor tab size from 4 to 2 spaces. I've trained over 100 developers and I'm tired of having to tell each new student to change their tab size. Does anyone actually still use 4 spaces? If so I feel sorry for those people. VS Code should follow standards and widely accepted best practices, and not kneecap new developers who don't know better.

**Comment by PythonCreator27** [comment]
There are still people who use four spaces. It is still all about preference (I use four). You can set the default tab size with the `editor.tabSize` option in `settings.json`. If you use a formatting extension, you can set the format tab size there too. I think that users should be prompted for default tab size on install (or even better, during install). Changing the default tab size in an update would probably confuse a lot of users.

**Comment by mjbvz** [comment]
The best default is the default :)

But more seriously, ideal tab size is a matter of option. We make it easy to change/configure. Changing the default now would cause a lot of disruption, and would almost certainly result in many new issues with titles such as "Change default editor tab size from 2 to 4 spaces"...
