### ISSUE TITLE
Feature request: recognize modules within an npm package

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#11268]
- VSCode Version: 1.4.0
- OS Version: Mac OS 10.11.6

It would be awesome if VS Code could do what WebStorm does:

![screen_shot_2016-08-30_at_7_13_53_pm__2_](https://cloud.githubusercontent.com/assets/12532733/18113727/cfed5190-6ee6-11e6-93f4-cde923297dbf.png)

If I have the following:

``` js
import {
} from 'material-ui';
```

and I start typing "Table" in the braces, it can see inside the Material UI package and suggest a list of modules (`Table`, `TableBody`, etc).

**Comment by dbaeumer** [comment]
@ffxsam is this JavaScript or TypeScript

**Comment by ffxsam** [comment]
JavaScript.

**Comment by waderyan** [comment]
This is a valid feature request. Thank you @ffxsam!

**Comment by ffxsam** [comment]
You bet! I come from using WebStorm, which admittedly has probably the best JS code formatting and autocompletion I've seen.. but it suffers from huge bloat, and so I started looking for something more lightweight. VS Code is super impressive so far!

**Comment by waderyan** [comment]
@ffxsam can you send me an email? I'm working on the gaps between VS Code and WebStorm and would love to get your feedback in a short 20 minute user interview. 

wade.anderson@microsoft.com

**Comment by waderyan** [comment]
@dbaeumer is something on our end or something that needs to be provided by `tsserver`?

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12243
