### ISSUE TITLE
Prettier does not work

### ISSUE THREAD

**Issue by davidmoseler** [microsoft/vscode#112611]
VSCode Version: 1.50.1
OS Version: Ubuntu 20.04.1 LTS

After running create-react-app, cd into the project, run npm install -D eslint prettier eslint-config-prettier eslint-plugin-prettier eslint-config-airbnb eslint-config-react

Install the prettier and eslint plugins in vscode.

package.json:

{ "name": "restaurant-reservations", "version": "0.1.0", "private": true, "dependencies": { "@testing-library/jest-dom": "^5.11.6", "@testing-library/react": "^11.2.2", "@testing-library/user-event": "^12.6.0", "react": "^17.0.1", "react-dom": "^17.0.1", "react-scripts": "4.0.1", "web-vitals": "^0.2.4" }, "scripts": { "start": "react-scripts start", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject" }, "eslintConfig": { "extends": [ "react-app", "react-app/jest", "airbnb", "prettier" ] }, "browserslist": { "production": [ ">0.2%", "not dead", "not op_mini all" ], "development": [ "last 1 chrome version", "last 1 firefox version", "last 1 safari version" ] }, "devDependencies": { "eslint": "^7.15.0", "eslint-config-airbnb": "^18.2.1", "eslint-config-prettier": "^7.0.0", "eslint-plugin-prettier": "^3.3.0", "eslint-plugin-react": "^7.21.5", "prettier": "^2.2.1" } }

.prettierrc:

{ "semi": true, "trailingComma": "all", "singleQuote": true, "printWidth": 70, "arrowParens": "always", "tabWidth": 2 }

The plugin does not work.

**Comment by mjbvz** [comment]
Please file this against prettier
