### ISSUE TITLE
Outline for markdown files chokes on :::

### ISSUE THREAD

**Issue by gewarren** [microsoft/vscode#112610]
We have custom syntax to insert code snippets in our docs. When this syntax exists in a markdown file, the Outline breaks. It either says "no symbols found" or it shows bogus headings.

```
:::code language="csharp" source="snippets/ca2225.cs" id="snippet1":::
```

**Comment by mjbvz** [comment]
The built-in markdown extension targets standard CommonMark. Support for additional syntax can be added by extensions
