### ISSUE TITLE
Sync Report Issue on Too Many Requests

### ISSUE THREAD

**Issue by TigorLazuardi** [microsoft/vscode#112646]
Issue Type: <b>Bug</b>

I got this notification and said I should report. So I report.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.9.14-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics (4 x 3176)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.56GB (3.07GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id c6a68806-d010-4e91-88fa-9f86e51cc23b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|bspwm|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|bspwm|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-repl|ach|0.6.5
vscode-neovim|asv|0.0.63
hsnips|dra|0.1.9
brackethighlighter|Dur|2.2.2
vscode-great-icons|emm|2.1.62
prettier-vscode|esb|5.8.0
go|gol|0.19.1
todo-tree|Gru|0.0.192
discord-vscode|icr|4.0.0
vscode-docker|ms-|1.9.0
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
reload|nat|0.0.6
vscode-yaml|red|0.13.0
vscode-sort-json|ric|1.18.1
markdown-preview-enhanced|shd|0.5.13
whichkey|VSp|0.8.4
clang-format|xav|1.9.0
random-theme-switcher|zan|0.2.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30236573
pythonvsdeb440cf:30233464
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by sandy081** [comment]
/duplicate

Thanks for reporting.
