### ISSUE TITLE
Minimap does not update background correctly

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#112666]
When no minimapBackground color is defined `minimap._getMinimapBackground` get the background color from the `MinimapTokensColorTracker`

When debugging this I saw that `onThemeChanged` is called before before the MinimapTokensColorTracker is updated, so _getMinimapBackground read the old colors.

Is could listen to `MinimapTokensColorTracker.onDidChange` or invalidate the MinimapTokensColorTracker when it gets the `onThemeChanged`

**Comment by aeschli** [comment]
Just FYI, here's how the MinimapTokensColorTracker gets updated:
workbenchThemeService.onDidColorThemeChange -> abstractTextMateService._updateTheme -> TokenizationRegistry.setColorMap -> TokenizationRegistry.onDidChange -> MinimapTokensColorTracker._updateColorMap

I wonder if that can be simplified now that the theme service is creating and updating the colorMap.

Also, when the minimap gets the editor background color, it could actually just ask the themeService: themeService.getColor('editor.backgroundColor').

**Comment by alexdima** [comment]
@aeschli Can you please provide some repro steps, I am pushing a change that I hope might fix things, but I honestly can't tell due to the high complexity.

**Comment by aeschli** [comment]
The steps are:
- open a codespace, make sure it does not have a setting for the theme (= uses the default theme)
- add `?loadingScreenThemeColor=dark` to the URL

Right now all seems to work, but I somehow don't see how your change has fixed the issue I seen.
MinimapOptions uses the MinimapTokensColorTracker to get the background color. But it's not listening to MinimapTokensColorTracker.onChange. So the color it gets might be stale. That can happen if the Minimap get the theme change event before the MinimapTokensColorTracker.
But as said, it seem to be working now.
