### ISSUE TITLE
IPC resolves with an object when disposed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112652]
This took me a while to understand, but here are the steps:
* open a window on test resolver 
* open an untitled file and make it dirty
* disable `hot.exit` in settings (turn it `off`)
* kill the remote server process from the process explorer
* wait until you see a native dialog asking you to reload
* you are being asked to save or discard the untitled file
* click save
* see how the simple file dialog appears
* pick any file name as target
* => 🐛 notice how the file dialog indicates to you that the file already exists (even though it does not)

The culprit seems to be this line:

https://github.com/microsoft/vscode/blob/208380cf7663846650621be1802582db57a14890/src/vs/base/parts/ipc/common/ipc.ts#L530-L530

Possibly also:

https://github.com/microsoft/vscode/blob/208380cf7663846650621be1802582db57a14890/src/vs/base/parts/ipc/common/ipc.ts#L536-L536

We cannot just resolve the promise with an arbitrary object, rather I would expect the promise to be rejected in this case. Otherwise this breaks any implementation that is using IPC under the hood because I never expect the cancelled error to be returned.

**Comment by alexdima** [comment]
Oh sorry this is my bad. That should be a promise rejection.
