### ISSUE TITLE
Allow per-diff editor sash position in same editor group

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#112682]
I feel like this is a recent change (regression), but if you have 2 diff editors open in the same editor group, where ever you move the split position, will also affect the other diff editor when you switch to it. I'm pretty sure we used to save the diff editor position which would get restored when switched back.

**Comment by bpasero** [comment]
I can reproduce this behaviour all the way back to `1.48.x` and I don't think it was ever different. I personally like that the sash position is remembered because this allows to tweak the position once for many diffs to go through. I would not easily change this.
