### ISSUE TITLE
Cannot do selection because quick fix dialog cover the text

### ISSUE THREAD

**Issue by kaala** [microsoft/vscode#112627]
- VSCode Version: 1.52.0
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. move mouse over text and try to do selection
![截屏2020-12-16 下午2 09 02](https://user-images.githubusercontent.com/246542/102311844-88f8e280-3fa8-11eb-9964-5c70007236f1.png)

2. a quick fix pop up immediately and cover the entire text, not able to select text under it

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/112391
