### ISSUE TITLE
JSDoc not showing @return or @returns {type} in intellisense/hover

### ISSUE THREAD

**Issue by bscaspar** [microsoft/vscode#112679]
- VSCode Version: 1.52.0
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Write a JSDoc for a function in a JS or TS file with a @return or @returns type defined
<img width="308" alt="Screen Shot 2020-12-16 at 11 40 04 AM" src="https://user-images.githubusercontent.com/6042704/102397941-72945c00-3f93-11eb-9e86-876df603df25.png">

2. Hover over function to see @return type description missing
<img width="372" alt="Screen Shot 2020-12-16 at 11 42 58 AM" src="https://user-images.githubusercontent.com/6042704/102398229-dcad0100-3f93-11eb-9401-89ba9f4b43dc.png">

3. If @return type is a bit more complex (like an object) and includes a space, the text after the space is sometimes included.
<img width="351" alt="Screen Shot 2020-12-16 at 11 40 48 AM" src="https://user-images.githubusercontent.com/6042704/102397997-8b9d0d00-3f93-11eb-96dc-a76bc914759e.png">
<img width="378" alt="Screen Shot 2020-12-16 at 11 41 25 AM" src="https://user-images.githubusercontent.com/6042704/102398055-a2436400-3f93-11eb-964e-e4845ef1a648.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The return type is shown in the function signature

Your second example is not a valid type. Try `{{ test: string}}` instead

**Comment by bscaspar** [comment]
Thanks @mjbvz, that did work. I guess I was confused about the expected behavior in VS Code.
