### ISSUE TITLE
GOOGLE_API_KEY no longer needs to be excluded from the environment

### ISSUE THREAD

**Issue by matttilton** [microsoft/vscode#112683]
The environment variable GOOGLE_API_KEY was added to the blocklist 3 years ago in order to fix #32213. At the time electron provided a default value for this environment variable [Electron 1.7.6 Documentation](https://github.com/electron/electron/blob/v1.7.6/docs/api/environment-variables.md#google_api_key) and this caused unexpected behavior. Since then, electron has stopped providing a default value and now expects users to supply their own key [Electron 11.1.0 Documentation](https://github.com/electron/electron/blob/v11.1.0/docs/api/environment-variables.md#google_api_key). This is a minor annoyance that forces me to either run my code outside of the integrated terminal or rename my environment variable.

Inside integrated terminal
![image](https://user-images.githubusercontent.com/19739737/102402729-d6764f00-3faa-11eb-8cdf-b0b0653ef119.png)

Outside
![image](https://user-images.githubusercontent.com/19739737/102402936-1fc69e80-3fab-11eb-8944-91a49496e198.png)

**Comment by deepak1556** [comment]
Yeah electron no longer sets a default https://github.com/electron/electron/pull/15478 , we can remove it from the blocklist https://github.com/microsoft/vscode/blob/bd38c65afc7e2402e974c4bccc528498242a3987/src/vs/base/common/processes.ts#L111
