### ISSUE TITLE
Ability to set sash color

### ISSUE THREAD

**Issue by localjo** [microsoft/vscode#112651]
Thank you for #99709 ❤️

This is a related feature request. I often use split terminals, and a dark theme. When I've got lots of output in both terminals it can be hard to find the sash between the two. Being able to set a hover color for the sash is helpful, but it would be even better if I could set a sash color for the normal state as well.

Here's a screenshot of the problem. Note how hard it is to find the sash that divides the two terminals. It is even harder when the output gets noisier.

![Screen Shot 2020-12-16 at 1 03 03 PM](https://user-images.githubusercontent.com/516388/102346841-cdcc4b80-3f9f-11eb-9750-901dedfb5801.png)

**Comment by localjo** [comment]
I searched for related issues, and I think this is not a duplicate.

**Comment by misolori** [comment]
Have you tried using `terminal.border `?

**Comment by localjo** [comment]
That works! Thanks!
