### ISSUE TITLE
Request for adding a new locale: Cantonese. We can contribute and help.

### ISSUE THREAD

**Issue by laubonghaudoi** [microsoft/vscode#112607]
This is @laubonghaudoi from @CanCLID team. We are a group of linguists and open-source developers dedicated to the infrastructure development of the Cantonese language. Cantonese has over 80 million speakers around the world which includes many VSCode users, and recently Notepad++ [also added Cantonese localization](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/875a397c14c1529f0e5b8dc155b7433fe0a75519). So we believe it is appropriate to request VSCode to add Cantonese as a new locale. We are happy to contribute to translations and other necessary works. May we know what following steps we should take?

**Language name in English**: Cantonese
**Language Name in its own script**: 粵語
**ISO 693-3 code of the language**: `yue`

### Reference

ISO 693 Identifier Documentation: https://iso639-3.sil.org/code/yue

**Comment by danyeh** [comment]
We don't have a plan to host translation of additional languages in near term. 
While community can fork current language pack resources and release own language pack.
@laubonghaudoi , if you want to go with this route and need help. Please create an issue in https://github.com/Microsoft/vscode-loc. We can sync up there.
I am closing this 'issue'.

CC: @nexue2020

**Comment by laubonghaudoi** [comment]
@danyeh Thank you! I have opened the issue here https://github.com/microsoft/vscode-loc/issues/204 Please let us know what to do next.
