### ISSUE TITLE
Cannot profile during reload

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#112643]
* run from master `./scripts/code.sh`
* open dev tools
* start CPU profiling (more tools > JavaScript profiler)
* (alternatively start performance profiling from the performance tab)
* reload the window via ctrl+r
* profiling doesn't work, reload does work

This is somewhat severe because it doesn't allow us to profile startup properly

**Comment by bpasero** [comment]
Cannot reproduce on macOS 10.15.6, possibly Big Sur related?

**Comment by jrieken** [comment]
related to https://github.com/microsoft/vscode/issues/111827?

**Comment by jrieken** [comment]
Seems to be an issue with MSFT Defender ATP for mac...

**Comment by jrieken** [comment]
I reported this to them, lets see what we hear back

**Comment by deepak1556** [comment]
Closing as issue is not with the runtime.
