### ISSUE TITLE
Settings editor does not accept first click

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112645]
See video:

![Kapture 2020-12-16 at 12 11 10](https://user-images.githubusercontent.com/900690/102341603-6068ec80-3f98-11eb-9960-a0e3f044feae.gif)

**Comment by roblourens** [comment]
Is this in web?

**Comment by roblourens** [comment]
Actually, it usually works but I do see this

**Comment by bpasero** [comment]
Yes, web.

**Comment by roblourens** [comment]
Basically duplicate of https://github.com/microsoft/vscode/issues/106577
