### ISSUE TITLE
TreeView loading bar is no longer displayed as a scrolling bar - continued

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vscode#112663]
This is a continuation of 
https://github.com/microsoft/vscode/issues/112592
which was closed.  I do not think it should have been closed without an explanation as to what diagnostics might help to identify the cause.   
This was working for me  up until the last couple of days:
I can recreate the missing blue bar in another 3rd party extension:
- VSCode Version: 1.52.0
- OS Version: Windows 10

I believe that the blue horizontal loading bar is not controlled by the extension so if it isn't being displayed during the loading of the tree, that might suggest a defect.

If there are diagnostics that I can run to help identify the problem, please let me know.

Here is a screen print of my tree loading. The blue clock appears over the icon but the blue scrolling loading bar is not present.
![test](https://user-images.githubusercontent.com/46171060/102377503-9cd92000-3f79-11eb-8488-22c1c2839ea1.gif)

**Comment by alexr00** [comment]
@davidkjackson54 thanks for the gif. This only appears to repro if the view is in its own view container.

@sbatten and @bpasero not sure if this is view related or progress related. For an easy repro:
1. Install the GitHub Pull Requests and Issues extension:
2. Drag the Pull Requests view into a view container by itself
3. Expand the "All" element of the Pull Requests tree. 
4. See that the blue progress bar does not show at the top of the view. 

Version 1.47:
![recording (33)](https://user-images.githubusercontent.com/38270282/102470532-658b7180-4054-11eb-810d-956f4fe9d07f.gif)

Version 1.52:
![recording (34)](https://user-images.githubusercontent.com/38270282/102470751-a7b4b300-4054-11eb-8172-0b53b145ea55.gif)

**Comment by bpasero** [comment]
I think [`this.viewletService.getProgressIndicator`](https://github.com/microsoft/vscode/blob/8d7ad831e57e9038d8c982d861c647d2a487f40e/src/vs/workbench/services/progress/browser/progressService.ts#L411-L411) maybe not working in this case which would hint to a custom view issue.

**Comment by davidkjackson54** [comment]
Has this been accepted as a bug?

**Comment by sandy081** [comment]
This seems to happen when the view is merged with view container (single view in view container).

**Comment by davidkjackson54** [comment]
Hi thanks for the comment. Does that suggest that it has been accepted as  defect?  
As I mentioned, it used to work but stopped around December 15th  I don't know if that synced up with the release of VSCODE 1.52 or is coincidental.   Looks like  @alexr00  was able to recreate a couple of weeks back.

**Comment by sandy081** [comment]
Yes, this is accepted as bug and it is broken from 1.47 as @alexr00 pointed out.
