### ISSUE TITLE
Webview hijacking pasting in the editor find widget

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#112677]
- VSCode Version: 1.52 Insiders
- OS Version: Windows

Originally reported by @eamodio 

Steps to Reproduce:

1. Open a markdown file
2. Ctrl+F to open find widget
3. Run command Open Preview to the side
4. Focus the find widget in the editor
5. Paste, nothing happens

By debugging directly in Insiders' dev tools, the webview thinks itself has focus.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mohameed7841987** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> - VSCode Version: 1.52 Insiders
> 
> - OS Version: Windows
> 
> 
> 
> Originally reported by @eamodio 
> 
> 
> 
> Steps to Reproduce:
> 
> 
> 
> 1. Open a markdown file
> 
> 2. Ctrl+F to open find widget
> 
> 3. Run command Open Preview to the side
> 
> 4. Focus the find widget in the editor
> 
> 5. Paste, nothing happens
> 
> 
> 
> By debugging directly in Insiders' dev tools, the webview thinks itself has focus.
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> 

Mohamed

**Comment by mohameed7841987** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> - VSCode Version: 1.52 Insiders
> 
> - OS Version: Windows
> 
> 
> 
> Originally reported by @eamodio 
> 
> 
> 
> Steps to Reproduce:
> 
> 
> 
> 1. Open a markdown file
> 
> 2. Ctrl+F to open find widget
> 
> 3. Run command Open Preview to the side
> 
> 4. Focus the find widget in the editor
> 
> 5. Paste, nothing happens
> 
> 
> 
> By debugging directly in Insiders' dev tools, the webview thinks itself has focus.
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> 
[]()

**Comment by mjbvz** [comment]
@rebornix I'm having trouble reproducing this. How you are focusing back onto the find widget?

**Comment by eamodio** [comment]
It doesn't need to be the find widget. The search side bar exhibits the same behavior

**Comment by mjbvz** [comment]
Still having trouble reproducing this and now sure what I'm doing wrong:

https://user-images.githubusercontent.com/12821956/102557613-7651dc80-4080-11eb-9f0a-53686e8cea76.mp4

**Comment by eamodio** [comment]
I just tried again and found I can't reproduce it without `"webview.experimental.useIframes": true,` set.

**Comment by rebornix** [comment]
I'm seeing this same behavior as @eamodio
