### ISSUE TITLE
Git refresh bug on wsl 2

### ISSUE THREAD

**Issue by shahakMorag** [microsoft/vscode#112671]
- VSCode Version: 1.52.0
- OS Version: windows version 2004 (OS Build 19041.685)

Steps to Reproduce:

1.  Open project with git
2. Work several time with the project and try to commit stuff
3. After several time when changing file the source control tab doesn't show any changes and i need to push on refresh every time.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
So some changes show up, but then stop? Does the same thing happen with the Insiders version?
