### ISSUE TITLE
Feature request: Allow empty editor e.g. don't close editor when last tab/file is closed

### ISSUE THREAD

**Issue by trash** [Microsoft/vscode#11262]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

Steps to reproduce:
1. Open a file
2. Open 2 more editors to get three-panel view by hitting "cmd+\"
3. Close file in right editor

Expected: File in right editor closes but editor/panel stays expanded, retaining desired three-panel view.
Result: File closes but so does editor, so that only 2 editors in 2-panel view are left.

## Request:
Allow empty editors/panels. If all tabs are closed for an editor it should stay open. (An option for this would be great i.e. `workspace.allowEmptyEditors`, `workspace.dontCloseEmptyEditor` or whatever.)

## Context/User-Perspective:
**tl;dr**: Just because I closed the last tab for an editor doesn't mean I want the layout to change. I just don't want that file open anymore.

My reasoning for this preference is that I like to keep my workspace "clean" as it were. I like to focus on the code I'm currently working on and only really keep other files open as reference material. Visually speaking, I also like having the file I'm currently working on centered. Currently I have to keep adjusting the editor's widths depending on how many are open and which files I've closed. It'd be nice to just have a fixed 3 panel layout like what is possible in SublimeText.

## Examples

The behavior I'm looking for can be seen in SublimeText:

Notice here the right tab-group has no files but is still there.
![screen shot 2016-08-30 at 6 53 27 pm](https://cloud.githubusercontent.com/assets/1890516/18111210/59576c30-6ee3-11e6-857c-385d57a36973.png)

And in this one I've closed all the files in the left tab group but it stays open. In VS Code this would cause the left editor to collapse and the middle editor to be the first.
![screen shot 2016-08-30 at 6 53 35 pm](https://cloud.githubusercontent.com/assets/1890516/18111209/59565af2-6ee3-11e6-99ee-fa04903f4757.png)

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by trash** [comment]
Reference to existing issue https://github.com/Microsoft/vscode/issues/2755
