### ISSUE TITLE
intellisense not working when i share mongodb connection 

### ISSUE THREAD

**Issue by MajidRad** [microsoft/vscode#112690]
We have written t
Issue Type: <b>Bug</b>

hi tech team 
intellisense not working when i share mongodb connection 
i test in php storm an web storm both ide is working fine  intellisense 
but in clean install vs code in windows and node v (15 )
and vs code in ubuntu  node v(14) 
intellisense when i share connection not working 

```js
const mongodb = require('mongodb');
// import mongodb from 'mongodb';
const { MongoClient } = mongodb;

const uri = 'mongodb+srv://majidrad:@cluster0.zrhr9.mongodb.net/shop?retryWrites=true&w=majority';
// const uri = 'mongodb://127.0.0.1:27017';

let db;
const mongoConnect = (callback) => {
  MongoClient.connect(uri, { useNewUrlParser: true, useUnifiedTopology: true })
    .then((client) => {
      console.log('Connected!');
      db = client.db();
      callback();
    })
    .catch((err) => {
      console.log(err);
      throw err;
    });
};

const getDb = () => {
  if (db) {
    return db;
  }
  throw 'No database found!';
};
module.exports = { mongoConnect, getDb() };
```

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30233463
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

he needed data into your clipboard because it was too large to send. Please paste.

**Comment by mjbvz** [comment]
What doesn't work? Please share specific steps to reproduce the issue with the example code

**Comment by MajidRad** [comment]
hello matt

### **Database utils code for connecting to mongoDb in node.js**
`
const mongodb = require('mongodb');
// import mongodb from 'mongodb';
const { MongoClient } = mongodb;

const uri = 'mongodb+srv://majidrad:majid123@cluster0.zrhr9.mongodb.net/shop?retryWrites=true&w=majority';
// const uri = 'mongodb://127.0.0.1:27017';

let db;
const mongoConnect = (callback) => {
  MongoClient.connect(uri, { useNewUrlParser: true, useUnifiedTopology: true })
    .then((client) => {
      console.log('Connected!');
      db = client.db();
      callback();
    })
    .catch((err) => {
      console.log(err);
      throw err;
    });
};

const getDb = () => {
  if (db) {
    return db;
  }
  throw 'No database found!';
};
module.exports = { mongoConnect, getDb() };

`
### **Product Model code** 

`
const mongoDb = require('mongodb');
const { getDb, mongoConnect } = require('../utils/connection.js');

let db;
mongoConnect.then((client) => {
});
class Product {
  constructor(title, price, imageUrl, description) {
    this.title = title;
    this.price = price;
    this.imageUrl = imageUrl;
    this.description = description;
  }

  save() {
    const db = getDb();
    const dbOp = db.collection('products2').insertOne(this);
    return dbOp;
  }

  static fetchAll() {
    const db = getDb();
    return db
// Auto complete  aka (IntelliSense) for mongoDb method not work  
      .collection()
      .find()
      .toArray()
      .then((products) => {
        console.log(products);
        return products;
      })
      .catch((err) => {
        console.log(err);
      });
  }

`

**Comment by MajidRad** [comment]
![Uploading Screen Capture_20201217_074339.gif…]()

**Comment by MajidRad** [comment]
![intellisense](https://user-images.githubusercontent.com/33388949/102458908-29f3a600-405a-11eb-93f3-e0bad2da2d0b.gif)

**Comment by mjbvz** [comment]
Please share a list of steps with example code and describe the expected behavior

**Comment by mjbvz** [comment]
Ah actually there is a comment in the issue. @MajidRad Make sure you use markdown code blocks so that code examples get formatted nicely: https://guides.github.com/features/mastering-markdown/

**Comment by mjbvz** [comment]
In your example, try adding jsdoc typings to `db`.

```js
/** @type {mongodb.Db} */
let db;
```

If you hover over it, you see that its type is `any`. You need to give an explicit type here because the type cannot be safely inferred from usage (for example, `db` is only set if `mongoConnect` is called)

**Comment by MajidRad** [comment]
/** @type {mongodb.Db} */
thank you matt
 its solved
**you are the best**

**Comment by pelumiojebode** [comment]
On Thu, Dec 17, 2020 at 11:34 PM MajidRad <notifications@github.com> wrote:

> /** @type <https://github.com/type> {mongodb.Db} */
> thank you matt
> its solved
> *you are the best*
>
😁

**Comment by pelumiojebode** [comment]
No settlement until the Account is being setup.
Complete the installation of the account
Immediately
