### ISSUE TITLE
不显示冲图文件

### ISSUE THREAD

**Issue by zhangheng950229** [microsoft/vscode#112637]
dev 合并分支master  左侧git显示角标，提示有冲图文件，但是git功能文件管理器中不显示冲图文件以及更改文件
**
![image](https://user-images.githubusercontent.com/30212755/102321159-3b847180-3fb8-11eb-9cde-ebcc080a220e.png)
**
![image](https://user-images.githubusercontent.com/30212755/102321163-3de6cb80-3fb8-11eb-942a-5ea9c0f35dde.png)

**Comment by zhangheng950229** [comment]
The left git of the merge branch master of dev displays a corner mark, indicating that there is a drawing file. However, the drawing file and the change file are not displayed in the GIT function file manager
![image](https://user-images.githubusercontent.com/30212755/102322052-6e7b3500-3fb9-11eb-890f-4854e824b580.png)

**Comment by infinnie** [comment]
> 不显示冲图文件

应为冲突。

**Comment by infinnie** [comment]
Translation:

## Conflicting files are not displayed

When merging branch `dev` into `master`, conflicts are detected and shown in the terminal, but conflicting files are not displayed in the Source Control panel.

**Comment by infinnie** [comment]
#112713
#112697
#112717

**Comment by eamodio** [comment]
Duplicate of #112537 (which will be fixed in tomorrow's insiders)
