### ISSUE TITLE
Unable to add breakpoint in source file since version 1.52.0 (work in version 1.51.0)

### ISSUE THREAD

**Issue by alexismacrelle** [microsoft/vscode#112632]
Issue Type: <b>Bug</b>

- Add php-debug extension 
- Open a any php file
- Try to add a breakpoint on any line (red dot on the left side of the file)

The breakpoint is not add even using shift+F9

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
Bookmarks|ale|12.0.0
pgformatter|bra|1.16.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
markdown-table-formatter|fcr|2.1.3
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
remote-containers|ms-|0.154.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.1.3
vscode-typescript-tslint-plugin|ms-|1.3.2
gitblame|wad|6.0.0
markdown-pdf|yza|1.4.4

</details>

**Comment by weinand** [comment]
see https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329
