### ISSUE TITLE
List action not appear 

### ISSUE THREAD

**Issue by ToujouAya** [Microsoft/vscode#11265]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Use command ctrl+P
2. The window action is not display anything
![untitled](https://cloud.githubusercontent.com/assets/21350606/18112681/a050cddc-6f53-11e6-94b6-2edb0b5eacf9.png)
![untitled](https://cloud.githubusercontent.com/assets/21350606/18112700/d8b6304a-6f53-11e6-8ea8-b6c2cd33a890.png)

**Comment by ToujouAya** [comment]
![image](https://cloud.githubusercontent.com/assets/21350606/18112694/c9576632-6f53-11e6-9575-037b88646bb8.png)

**Comment by dbaeumer** [comment]
@ToujouAya Ctrl+P is used to open files and program symbols. To reach to VS Code commands please use F1.

**Comment by ToujouAya** [comment]
@dbaeumer 
Yes I understood how to use ctrl+P. I want to open files , but it can't work.  As you can see the attachment , i tried to open the controller file , but the window popup doesn't display anything. You can check the second attachment file or the attachment files below

Ctrl+P, F1, ctrl+T, etc... anything i tried but the window popup doesn't display anything.

![untitled](https://cloud.githubusercontent.com/assets/21350606/18119924/34cbcb5a-6f87-11e6-8833-efdc3db18d7b.png)


Sorry for my English.

**Comment by dbaeumer** [comment]
@ToujouAya sorry I misunderstood you. Reopening...

**Comment by bpasero** [comment]
@ToujouAya you seem to be using the vscode-icons extension which can cause major issues because it patches our installation files. Can you completly uninstall Code and the vscode-icons extension and reinstall Code and see if you can still reproduce?

**Comment by ToujouAya** [comment]
@bpasero 
Thank you. I follow your instruction and it's work now.

**Comment by bpasero** [comment]
It does.
