### ISSUE TITLE
Remove need for writing unnecessary characters in Go To File

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#112629]
- VSCode Version: 1.52.0
- OS Version: Windows 10

Steps to Reproduce:

1. Press ctrl+p (Go To File)
2. Two items show up
![image](https://user-images.githubusercontent.com/28700378/102314298-30781400-3fad-11eb-98ab-fabd32c06138.png)
3. Type `svgsnippets`
![image](https://user-images.githubusercontent.com/28700378/102314374-4e457900-3fad-11eb-9b56-887f8e99971f.png)
4. Type `svg snippets`
![image](https://user-images.githubusercontent.com/28700378/102314408-5bfafe80-3fad-11eb-9149-cf463e63fa46.png)

Can we just remove the need for writing space/dash/underscore etc.? The characters without them are enough to get the correct file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/102333772-285cac00-3f8e-11eb-99fb-49e2f21d1df1.png)

Is this file outside of the workspace?

**Comment by wenfangdu** [comment]
@bpasero Yes, it's outside the workspace, but is used more frequently than workspace ones 😆.
