### ISSUE TITLE
No IntelliSense for single file. 

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#11260]
- VSCode Version: Insiders
- OS Version: Mac 

Related #11258

Steps to Reproduce:

1. Create a new file `person.js`
2. Add this code. 

```js
function Person(name, age) {
    this.name = name;
    this.age = age;
}

var p = new Person()
```

I expect to see IntelliSense or even word completion, but I am not. 

![image](https://cloud.githubusercontent.com/assets/2449568/18110756/dfdc4b8c-6ece-11e6-95ec-6f7c0f9334cd.png)

I see this when logging tsserver output. 

![image](https://cloud.githubusercontent.com/assets/2449568/18110761/e9488c44-6ece-11e6-8c4c-42cc51832bb0.png)

Others in the office cannot reproduce this. I can reproduce it on my machine multiple times. I have also observed this starting to work after a time and also IntelliSense will stop working after a time. 

It seemed like the problem was with TypeScript Language Service. I tried the following:

1. Restarted VS Code - still not resolved
2. Killing tsserver.js process - still not resolved, although I did confirm the process restarted. 
3. I updated TypeScript to RC with `npm install -g typescript@rc`. Did not solve the issue. 
4. I looked in `Console.app` on the mac to see any errors logged. 

What other ways can I try and debug this? 
Is there a way to see the error logs for Electron? 
Do we think this is a TypeScript Language Service issue?

**Comment by waderyan** [comment]
ping @dbaeumer could use some help here.

**Comment by waderyan** [comment]
Note that in the time it took to write up the issue (approx. 5 minutes), I have gone back to the file and IntelliSense works now.

**Comment by egamma** [comment]
@waderyan did you have other files than person.js in the workspace when this happened?

I've tried to reproduce this in a vanilla workspace but I could not reproduce what you saw.

**Comment by dbaeumer** [comment]
@waderyan did the workspace have a big node_modules folder. Since it is JS the folder might not be excluded and the tsserver will scan that folder which can take quite some time. Unfortunately the tsserver is not reporting any progress during that time (a feature request exist in the TS land) and since it is single threaded with no async behavior the command queue is blocked :-(

**Comment by waderyan** [comment]
@egamma I tried with two workspaces. The first time I saw the issue I was in a another folder (all the files and folders were generated by `yo node-express`). Once I saw it, I created a vanilla workspace and recreated the issue with an empty directory. 

@dbaeumer in the first case yes and in the second case no. Isn't `node_modules` ignored by default? 

From our [docs](https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson):

> Note: If you do not have a jsconfig.json in your workspace, VS Code will by default exclude the node_modules folder and the folder defined by the out attribute.

**Comment by waderyan** [comment]
Ok I have it happening again. Here are the steps. 

1. Open a New Window

![image](https://cloud.githubusercontent.com/assets/2449568/18147337/05a8e7ac-6f89-11e6-9799-971f3bb7ec77.png)

2. Click Open Folder

![image](https://cloud.githubusercontent.com/assets/2449568/18147343/0f210422-6f89-11e6-8377-b42cc7bb046a.png)

3. Create a new, empty folder and click Open. 

![image](https://cloud.githubusercontent.com/assets/2449568/18147357/20ea61b2-6f89-11e6-8616-8ab0fa10d808.png)

4. Create a new file using the new file button. Name the file `person.js`

![image](https://cloud.githubusercontent.com/assets/2449568/18147385/3e48c406-6f89-11e6-8b17-73871701c2ce.png)

5. Copy and paste this code. 

```javscript
function Person(name, age) {
    this.name = name;
    this.age = age;
}
```

6. Type `var p = new Person()`. Try triggering IntelliSense. 

![intellisense_bug](https://cloud.githubusercontent.com/assets/2449568/18147482/97f626a6-6f89-11e6-8cb7-5a2870fc3ccf.gif)

This is what I see from `tsserver logs`

![image](https://cloud.githubusercontent.com/assets/2449568/18147505/b26a4f1c-6f89-11e6-955d-da12bb77d283.png)

Note I'm on `typescript@rc`

![image](https://cloud.githubusercontent.com/assets/2449568/18147511/bd4ea9f0-6f89-11e6-998a-04b52ab0c6b1.png)

**Comment by waderyan** [comment]
I've repo'd three times the above steps. Sending to others in the office to test.

**Comment by waderyan** [comment]
I think this is a dup #11258

**Comment by waderyan** [comment]
@Tyriar could not repo on his Linux box, although he said that he has seen similar "hanging" behavior in the past and has had to restart VS Code. 

I restarted but am still seeing the issue. I also killed the tsserver and confirmed it restarted but still no resolve.

**Comment by bgashler1** [comment]
@waderyan I cannot reproduce.  I get intelliSense for every part of it.

![screen shot 2016-08-31 at 2 56 11 pm](https://cloud.githubusercontent.com/assets/11839736/18147786/1443d7e8-6f8b-11e6-92ef-2e9c61684715.png)



I'm on macOS 10.11.5
VS Code version 1.4.0
6276dcb0ae497766056b4c09ea75be1d76a8b679

**Comment by waderyan** [comment]
I moved to a different application (OneNote) to do something else. When I came back (literally a few minutes later) IntelliSense now works. Exact same setup. 

![image](https://cloud.githubusercontent.com/assets/2449568/18147773/098321ec-6f8b-11e6-95ff-b0a812c31c5d.png)

It seems that tsserver is hanging on something and needs a bit to reconnect. Do we think this is something on TS services side?

**Comment by dbaeumer** [comment]
@waderyan  I would say so. Especially if you can't reproduce this with TS out of the box (e.g. 1.8.10). Can you? Looks like @bgashler1 used the standard 1.8.10

**Comment by waderyan** [comment]
I cannot repo today with either 2.0 or 1.8. Very strange.

**Comment by waderyan** [comment]
Note opened an issue in TS to try and get to the bottom of this https://github.com/Microsoft/TypeScript/issues/10735
