### ISSUE TITLE
Tab bar not rendered on first load of only a welcome editor

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#112618]
See video. git-bisect gave me affd21e65ac41360704b573a4ca3b90107fd9ee8 as the culprit. 

![recording (2)](https://user-images.githubusercontent.com/8586769/102292221-94410500-3ef9-11eb-9409-4eea8b2b8196.gif)

**Comment by bpasero** [comment]
Amazing how our editor works fine even when we give it the wrong height, great catch 👍
