### ISSUE TITLE
Broken link in the Running Endgame document

### ISSUE THREAD

**Issue by mznet** [microsoft/vscode#112695]
While i read [Running the Endgame](https://github.com/microsoft/vscode/wiki/Running-the-Endgame#os-test-availability) of vscode documents, I found the broken link that says "here" in os test availability section. 

![image](https://user-images.githubusercontent.com/9622730/102423103-97e4a100-404b-11eb-9ba0-ad462f469a8c.png)

This link is linked to [vscode-tools repo](https://github.com/microsoft/vscode-tools), but this repo is not available now, it seems to be deleted. This document needs to be updated.

**Comment by jrieken** [comment]
This is an internal repo that only the dev team has access to
