### ISSUE TITLE
VS Cdoe doesn't interpret `^【` keybinding as `^[` using Chinese input methods on macOS

### ISSUE THREAD

**Issue by tddschn** [microsoft/vscode#112614]
This bug is encountered when using the VSCodeVIM extension, here's a link to the issue in VSCodeVIM: https://github.com/VSCodeVim/Vim/issues/3699#issuecomment-744028455.

- VSCode Version:  1.52.0
- OS Version: macOS 11.1

Steps to Reproduce:

1. Install the latest stable version of VS Code on a Mac
2. Install VSCodeVIM extension, enter Vim Insert Mode and switch the input method to zh_TW / zh_CN
3. Quit Insert Mode with `^[` (control-[)
4. Step 3 would fail because VS Code interprets `^【` as `^【`, not as `^[`. `^【` is shown as `ctrl+[BracketLeft]` in the keybinding settings -> record keys, while `^[` is shown as `ctrl+[`.

Does this issue occur when all extensions are disabled?: Yes/No
No, this bug is encountered when using the VSCodeVIM extension, but is considered an [upstream issue](https://github.com/VSCodeVim/Vim/issues/3699#issuecomment-745525223).

**Comment by alexdima** [comment]
To verify:
* define a keybinding like `{ "key": "ctrl+[", "command": "actions.find" }`
* on macOS, install the Chinese Traditional Pinyin keyboard layout
* switch to the installed layout and press `ctrl+[`, check that it triggers `actions.find`.
