### ISSUE TITLE
Ability to sort debugger variables alphabetically by their name

### ISSUE THREAD

**Issue by bborrel** [microsoft/vscode#112660]
Issue Type: <b>Feature Request</b>

Problem:
While debugging the variables listed in the variables panel are not alphabetically sorted by their name. When there is a lot of variables it thus makes their reading cumbersome.

Solution:
Having a way to sort them, either by a config setting or an action item would improve the developer experience. I do not know wether this is up to vscode or the debugger extensions to implement that though.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-1030-aws

**Comment by gjsjohnmurray** [comment]
What language are you debugging?

**Comment by bborrel-topdevz** [comment]
PHP

PHP version: 7.2.32, with xDebug 2.9.6
VSCode extension version: PHP Debug (felixfbecker.php-debug) 1.13.0

**Comment by bborrel** [comment]
@gjsjohnmurray PHP

PHP version: 7.2.32, with xDebug 2.9.6
VSCode extension version: PHP Debug (felixfbecker.php-debug) 1.13.0

**Comment by gjsjohnmurray** [comment]
@bborrel I think the extension is responsible for controlling the order the variables appear in. @weinand can confirm.

In your case I understand that debug extension is no longer maintained by the author.

**Comment by bborrel** [comment]
@gjsjohnmurray Indeed PHP Debug (felixfbecker.php-debug) repository [doesn't show any activities since a long time](https://github.com/felixfbecker/vscode-php-debug/graphs/code-frequency)... 

I guess I can close my ticket then.

Thank you.

**Comment by weinand** [comment]
Yes, sorting variables needs to be done by the debug extensions.
