### ISSUE TITLE
CPP extension crashes a lot (once a day or so)

### ISSUE THREAD

**Issue by artagnon** [Microsoft/vscode#11261]
- VSCode Version: 1.6
- OS Version: El Capitan

Steps to Reproduce:
Okay, it's very hard to come up with reproduction steps. I'm describing the pattern. I work on a huge codebase, and ignore 90% of everything using `ignore` so that <kbd>Cmd+P</kbd> can work. I usually have a lot of tabs open (15+). Once a day or two, vscode becomes unresponsive, a stray vscode process has taken up 100% of cpu. If I keep using vscode, it eventually grinds to a halt and crashes.

Fixing this issue should be top priority.

**Comment by dbaeumer** [comment]
@artagnon what kind of project are you working on (JS, TS, C#, ....). And could you provide use with the command line of the process that is causing 100% of CPU. That would help to track down what is causing this.

**Comment by dbaeumer** [comment]
@bpasero FYI

**Comment by bpasero** [comment]
@artagnon can you find out which process is causing the high CPU load?

**Comment by artagnon** [comment]
I work in C++. Will give you the name of the process in a couple of days or
so: I forgot to note it down.

**Comment by artagnon** [comment]
Today, it crashed when I'd left it idle for some time: so I don't have the name of that process. Don't we have some kind of crash logging? Atleast a stack trace?

**Comment by bpasero** [comment]
@artagnon you can use the "Console" application on Mac to find the crash log:

<img width="1188" alt="screen shot 2016-09-01 at 06 37 26" src="https://cloud.githubusercontent.com/assets/900690/18155515/91901e18-700e-11e6-8716-90ab67c47f01.png">

**Comment by artagnon** [comment]
So you do have a lot of crash reports; let me add mine to the pile.

```
0   libsystem_kernel.dylib        	0x00007fff99318286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff9a31b9b3 abort + 129
2   libc++abi.dylib               	0x00007fff96144a21 abort_message + 257
3   libc++abi.dylib               	0x00007fff9616c8f4 default_terminate_handler() + 46
4   libc++abi.dylib               	0x00007fff9616a0a1 std::__terminate(void (*)()) + 8
5   libc++abi.dylib               	0x00007fff9616a12e std::terminate() + 78
6   libc++.1.dylib                	0x00007fff9bfd3b8b std::__1::thread::~thread() + 17
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010137691d std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::~vector() + 45
8   libsystem_c.dylib             	0x00007fff9a31c72d __cxa_finalize_ranges + 322
9   libsystem_c.dylib             	0x00007fff9a31ca30 exit + 55
10  libdyld.dylib                 	0x00007fff90ec15d0 start + 8
```

The vector destructor in the CPP extension is crashing. What do we do now?

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-cpptools#195

**Comment by bpasero** [comment]
@artagnon sorry to hear that, I moved the issue to the C++ team, lets see what they have to say.
