### ISSUE TITLE
Flaky unit test: TextFileEditor text file editor preserves viewstate

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#112649]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=97355&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6ad30dce-518e-54c1-94da-00d19cce9354

>   1) Files - TextFileEditor text file editor preserves viewstate:
>     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by bpasero** [comment]
No clue where this timeout kicks in, I have to instrument and throw on each `await`, starting with:

https://github.com/microsoft/vscode/blob/018b924fee2b2eff2d803c55faf54d30f1293c15/src/vs/workbench/contrib/files/test/browser/textFileEditor.test.ts#L77
