### ISSUE TITLE
Use horizontal layout for inspectors such as locals, watch window etc in debug mode

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1126]
When we have the ability to view panels in a horizontal layout, we should use this in debug mode to show inspectors such as locals, watch window, debug console, breakpoints etc. Pickers, such as the call stack, processes etc should remain in the vertical panel.

This does two things - it provides is with more real estate to view the values of variables and expressions and it maintains the overall left to right UX flow in the product where the user sets the context of what they want to inspect from the left hand side.

For example:

![horizontallayout](https://cloud.githubusercontent.com/assets/1704059/11682904/88747274-9e5f-11e5-8014-5ca6ba17927b.png)

**Comment by isidorn** [comment]
Closing this one since we had good UX discussion in December which capture the direction where we want to better.
