### ISSUE TITLE
During liveshare file was created by guest, contents was reset when host viewed new file

### ISSUE THREAD

**Issue by simplyandyg** [microsoft/vscode#112604]
Issue Type: <b>Bug</b>

We were viewing seperate files. Guest created a new file. Copied the contents of the file I was viewing. Pasted it into the new file and edited it. The file was already saved and renamed. When I clicked on the tab at the top to view the new file, the contents of the new file was reset to that of the file that it was copy and pasted from.

Every time we saved the file it would re-apply the copied contents onto the end of the file and sometimes over the edits we had made, but sometimes not over the edits but just append to the end of the file.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_8021926 --crash-reporter-id 5ba23325-9d38-4921-8ba0-7f50c2f427bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
vscode-new-file|dku|4.0.2
vscode-great-icons|emm|2.1.62
php-debug|fel|1.13.0
auto-close-tag|for|0.5.9
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.5
gc-excelviewer|Gra|3.0.40
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.5.2
docthis|joe|0.7.1
rainbow-csv|mec|1.8.0
mssql|ms-|1.10.0
python|ms-|2020.12.422005962
jupyter|ms-|2020.12.414227025
node-debug2|ms-|1.42.5
vsliveshare|ms-|1.0.3303
vscode-react-native|msj|1.2.0
color-highlight|nau|2.3.0
vetur|oct|0.31.3
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
html-preview-vscode|tht|0.2.5
sort-lines|Tyr|1.9.0
gitblame|wad|6.0.0
vscode-todo-highlight|way|1.0.4

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30233464
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30233462
vsjup459:30229593

```

</details>

**Comment by mjbvz** [comment]
Please start by filing this against the LiveShare extension
