### ISSUE TITLE
Changes view: staging file from a bucket collapses entire tree

### ISSUE THREAD

**Issue by Curve** [microsoft/vscode#112661]
Previously reported in #101094.
This still happens for me, it's not fixed (although this does not only happen for the last file but for every file).

![image](https://user-images.githubusercontent.com/900690/85872061-8c689980-b7cf-11ea-98f8-09cae3c27c17.gif)

**Comment by Curve** [comment]
Seems to be fixed now

**Comment by thedelk** [comment]
I'm seeing this same behavior, also reported in #113656.
