### ISSUE TITLE
Debugger Breakpoint not showing in PHP

### ISSUE THREAD

**Issue by devendracnc** [microsoft/vscode#112655]
![image](https://user-images.githubusercontent.com/56667697/102355886-7abfbc00-3fd2-11eb-8a36-94d14bd3e31c.png)

here you can see in new vs code php debug not working any more. on red color i already hover with mouse but no break point is showing. in php file. it showing on other files like html, and js. and this issue occured after 16-Dec-2020. before its working fine.

**Comment by weinand** [comment]
/duplicate #112288

see https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329
