### ISSUE TITLE
Sash hover border color

### ISSUE THREAD

**Issue by shogg** [microsoft/vscode#112685]
Issue Type: <b>Bug</b>

Code 1.52.0 announced "Sash hover border color" as the property "sash.hoverBorder". That doesn't seem to be correct, hoverBorder here is a size, default 4.

Also ... when switching between vscode tabs the "current version annotations page" (I have no idea what it's really named) will always reload and scroll up to the beginning. Quite annoying when just switching tabs.

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:45:11.850Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-122-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.54GB free)|
|Process Argv|--remote=wsl+Ubuntu-20.04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: *****|
|OS|Linux x64 4.15.0-122-generic|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 800)|
|Memory (System)|31.31GB (13.73GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
QML|bbe|1.0.0
vscode-language-pack-de|MS-|1.52.2
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-edifact|DAX|0.6.0
go|gol|0.19.1
camelcasenavigation|map|1.1.3
rainbow-csv|mec|1.8.0
vscode-language-pack-de|MS-|1.52.2
vscode-subword-navigation|ow|1.2.0
pdf|tom|1.1.0

(1 theme extensions excluded)

</details>

**Comment by misolori** [comment]
You have to be sure you're editing this under the `workbench.colorCustomizations` in your settings.json like:

```json
"workbench.colorCustomizations": {
		"sash.hoverBorder": "#007acc"
	}
```

![image](https://user-images.githubusercontent.com/35271042/102418629-fad62980-3fb2-11eb-9f7b-b30618336814.png)

**Comment by shogg** [comment]
I searched for "sash.hoverBorder". Only one setting popped up.

Am Do., 17. Dez. 2020 um 00:26 Uhr schrieb Miguel Solorio <
notifications@github.com>:

**Comment by shogg** [comment]
![image](https://user-images.githubusercontent.com/130464/102420245-fedd6800-4001-11eb-8c70-b6b1e8594bda.png)

**Comment by misolori** [comment]
It's a color token name, not a setting. So you need to edit your settings.json in order to use it like I posted above.

**Comment by shogg** [comment]
It's not a problem for myself, it's a problem how it was anounced.

Sash hover border color
You can now customize a border hover color for sashes (sash.hoverBorder) across the workbench.

All you told me is missing.

**Comment by shogg** [comment]
It should come up in the settings search, but it doesn't.

(and don't forget the tab switching that reloads the "news page", but that's not your business ... so ignore that)

**Comment by shogg** [comment]
(... I should have opened an extra isshue for it,)

**Comment by gjsjohnmurray** [comment]
> (and don't forget the tab switching that reloads the "news page" ... I should have opened an extra issue for this,)

#94945
