### ISSUE TITLE
App icon disappear on update ( linux / ubuntu / .deb )

### ISSUE THREAD

**Issue by d4g0** [microsoft/vscode#112784]
- VSCode Version: 1.52
- OS Version: Linux Mint 20 ( Ubuntu 20 )

Steps to Reproduce:

1. Update VS Code from .deb
2. Search for in the menu, dock or any other place where you should get an icon.

Some where in the 1.4_X  ( linux / .deb based ) release  something change and every time that i update the icon disappear. So i need to reset manually the icon references ( `code.desktop` ,  `code-url-handler.desktop` ) for the app in  the  `/usr/share/applications`  as root to get back  the VS Code icon .

Does this issue occur when all extensions are disabled?: Yes/No
It happens completely outside the app runtime ( at update time ) .

**Comment by Tyriar** [comment]
What do you change the icon reference to?

**Comment by d4g0** [comment]
Well the first time the icon desappear on my laptop, after a litle research i saw the problems where in the files ( app definition files `code.desktop` , `code-url-handler.desktop`) that i mention abobe. I  reinstall the previous version of  VS  with OK app definition files,  save those files. Upgrade and overwrite the new files with the saved ones. And that's what i do every time i update the app since then, im not sure if the problem persist on PPA channels, i always download the current `.deb`  because i have a very very expensive and bad internet service.  I think that no one else do that, and every linux user use the automated PPA channel. We will be fine closing this issue and let you guys focus in other more useful things.

**Comment by Tyriar** [comment]
We've changed the format of the icon multiple times as there's seemingly always a distro that handles it wrong: https://github.com/microsoft/vscode/issues/95459, https://github.com/microsoft/vscode/issues/71942

I don't want to make any changes in this area without advice from an expert on the topic as the current way seems to be working well for most people.
