### ISSUE TITLE
VScode is patchy

### ISSUE THREAD

**Issue by praveenmak** [microsoft/vscode#112780]
Issue Type: <b>Performance Issue</b>

I am using a simple RemoteWSL extention. 
I cannot do any work , it gets patchy and anything I type takes few seconds to show up.
What is wrong? 
I am not doing any special thing.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (15.91GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bubuntu/home/praveemx/gitrepos/mydev/cfgs/WSL/wsl2.code-workspace --crash-reporter-id 42befceb-4c39-4d5d-9bda-e8817d0774bf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|Memory (System)|31.72GB (15.91GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	 11136	code main
    1	    59	  9152	   window (Issue Reporter)
    0	    68	  9876	   shared-process
    0	   243	 15080	   window (main.yml - wsl2 (Workspace) [WSL: Ubuntu] - Visual Studio Code)
    0	    41	  2748	     extensionHost
    0	    17	 20316	       electron_node wslDaemon.js 
    0	     5	 14748	         C:\WINDOWS\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" e5a624b788d92b8d34d1392e4c4d9789406efe8f stable .vscode-server 0  '
    0	     6	 14868	           console-window-host (Windows internal process)
    0	     4	 17364	           C:\WINDOWS\System32\lxss\wslhost.exe {d2d8e551-9737-4088-811f-af7f2106c009} 524 532 536
    0	     8	 16308	             console-window-host (Windows internal process)
    0	   179	 18016	   gpu-process
    0	    23	 18436	   utility
    0	    10	 19132	   crashpad-handler

Remote: WSL: Ubuntu
CPU %	Mem MB	   PID	Process
    0	     0	    22	remote agent
    0	     0	    62	   extensionHost
    0	     0	   410	     /home/praveemx/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node /home/praveemx/.vscode-server/extensions/mads-hartmann.bash-ide-vscode-1.11.0/out/server.js --node-ipc --clientProcessId=62
    0	     0	   463	     /home/praveemx/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node /home/praveemx/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=62
    0	     0	   635	     git fetch
    0	     0	   636	       /usr/bin/ssh git@github.com git-upload-pack 'praveenmak/main.git'
    0	     0	   776	     /home/praveemx/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node /home/praveemx/.vscode-server/extensions/ms-azuretools.vscode-docker-1.9.0/dist/dockerfile-language-server-nodejs/lib/server.js --node-ipc --node-ipc --clientProcessId=62
    0	     0	  1422	     /home/praveemx/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/node /home/praveemx/.vscode-server/extensions/redhat.vscode-yaml-0.13.0/node_modules/yaml-language-server/out/server/src/server.js --node-ipc --clientProcessId=62
    0	     0	    73	   watcherService
    0	     0	    80	   /bin/bash
    0	     0	  5591	   /bin/bash
    0	     0	 11519	   /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 11520	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu;
```

</details>
<details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.1
vscode-docker-syntax|dun|0.1.5
json-parse|jas|0.1.0
remote-containers|ms-|0.148.1
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.51.4
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.15.0
json-parse-validator|Adr|1.1.2
yaml2json|ahe|0.0.3
xml2json|bui|1.2.4
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.0.6
docker-explorer|for|0.1.7
vscode-pull-request-github|Git|0.21.2
json-escaper|jos|1.1.0
favorites|kdc|2.4.5
json2csv|kha|0.0.1
l13-diff|L13|0.30.1
bash-ide-vscode|mad|1.11.0
git-graph|mhu|1.28.0
xml-format|mik|1.0.2
file-downloader|min|1.0.9
prettify-json|moh|0.0.3
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.9.0
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
cpptools|ms-|1.1.3
azurerm-vscode-tools|msa|0.14.0
vscode-json-editor|nic|0.2.3
fix-json|oli|0.1.2
git-file-history|pom|1.0.1
prettyxml|Pra|0.5.4
quicktype|qui|12.0.46
vscode-yaml|red|0.13.0
vscode-docker-ws|tii|0.5.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
Hi, when did this start happening?

Are you using WSL 1 or 2?

You should try updating vs code.

**Comment by praveenmak** [comment]
Thanks for looking into this @meganrogge .
* I am using WSL 1  as I am not in control of Windows build version.. The upgrades are pushed by my company.
* I am using latest VSCode. It all in the debug info I attached.
* Did you mean "uninstall" instead of "run" bisect extension ?

**Comment by meganrogge** [comment]
no I mean use extension bisect https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect
