### ISSUE TITLE
How to change my default code snippets?

### ISSUE THREAD

**Issue by r-light** [microsoft/vscode#112738]
Issue Type: <b>Feature Request</b>

I know I can define my own code snippet. But I don't like some built-in snippets of languages.
For example, when I input if and press enter, this code will show.
  if ()
  {

  }
I want another type like this:
  if () {
   
  }
What should I do?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
See https://code.visualstudio.com/updates/v1_52#_snippets

**Comment by r-light** [comment]
> See https://code.visualstudio.com/updates/v1_52#_snippets

In fact, I want to edit snippets in the C++ extensions. I find it isn't in my configuration. I can close the suggestions like this page https://github.com/Microsoft/vscode-cpptools/issues/3083. Thanks!
