### ISSUE TITLE
Custom theme values: Certain color conventions do not work

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#11272]
- VSCode Version: Insiders
- OS Version: macOS 10.11.5

Regarding test item #11126
1. Try entering a shorthand hex color value in any field.  An example would be `#fff` for white or `#000` for black—instead of `#ffffff` or `#000000` respectively.
2. Now try entering named colors, like `black` or `white`

Neither of these situations work.  Perhaps number 2 is by design (but I think we at a minimum should support number 1).

**Comment by sandy081** [comment]
Currently we only support taking colors in hex with 6 digits. But we can enhance it to take requested forms

**Comment by mjbvz** [comment]
I believe that we now support shortforms, but not color names

Closing this as out-of-scope since there has been no further feedback since 2016
