### ISSUE TITLE
Cannot add breakpoints on php files anymore

### ISSUE THREAD

**Issue by josealeonf** [microsoft/vscode#112749]
- VSCode Version:1.52.0
- OS Version:Linux x64 5.4.0-58-generic

Steps to Reproduce:

1.Cannot add any new breakpoint on php files

Existing breakpoints before the update still remain, can add breakpoint in other files in the same project, not php, can be added.

Other non php projects can add breakpoints normally.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RiccardoManzan** [comment]
This has been marked as fixed in 1.52.1, but i still cant place breakpoints.

**Comment by RiccardoManzan** [comment]
/duplicate #112288
just update
