### ISSUE TITLE
auto detection of git repositories in deeper subfolders

### ISSUE THREAD

**Issue by BEG-Katzenberger** [microsoft/vscode#112715]
Assuming the following project folder structure:

```txt
test_ws/
└── src
    ├── package_a
    │   └── .git
    └── package_b
        └── .git
```

If VCS is running from the top level folder the repositories located in the **src** folder are not detected.
If started from the **src** folder the auto detection is working as expected.

==> please allow more than one level for searching

**Comment by eamodio** [comment]
Closing in favor of #87888
