### ISSUE TITLE
window API: allow to register click on StatusBarItem

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11279]
Currently `vscode.StatusBarItem` has property `command` which it invokes on click, it would be useful if one could register custom callback on click.

**Comment by jrieken** [comment]
You can do that by registering a [`command`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2973) for the status bar item

**Comment by whitecolor** [comment]
Thanks I thought it should be placed in package.json first)
