### ISSUE TITLE
Allow to split editor without duplicating the current file

### ISSUE THREAD

**Issue by AoDev** [microsoft/vscode#112756]
### Current situation
When I split the editor to be able to view multiple files, the file I was on will be duplicated on the new panel. 

### Wish
* Either the current file is __moved__ to the new panel and removed from the panel it was before.
* The new panel could be __empty__ and I'll put whatever file I want there.

The split functionality could have options to allow these different behaviours if people prefer the current one.

**Comment by gjsjohnmurray** [comment]
For an empty new group see https://github.com/microsoft/vscode/issues/77929#issuecomment-518182995

**Comment by AoDev** [comment]
I did search for an issue prior to this... Dont know how I missed it.

I tried the command, it works.
That said I sometimes click the split editor icon located top right but this one can't be configured, can it?



<img width="105" alt="Screenshot 2020-12-17 at 21 53 30" src="https://user-images.githubusercontent.com/1526150/102542841-b16d0380-40b2-11eb-90c3-5dbd252b6314.png">
