### ISSUE TITLE
Use connected account's avatar on accounts icon

### ISSUE THREAD

**Issue by Retr0-01** [microsoft/vscode#112732]
When connected to an account, either your Microsoft or your GitHub account, replace the accounts icon of the side bar with the connected account's avatar. If there is no avatar, use the current default icon.

**Comment by RMacfarlane** [comment]
We discussed doing this when first designing the accounts feature and thought this would generate too much noise on the activity bar. Right now all of the other icons are somewhat consistent with each other and have similar colors. Also, the behavior when you are signed into multiple accounts is unclear.
