### ISSUE TITLE
symlink change not detected in explorer or git view

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#112746]
I had a symblink and it showed as such in explorer (the link symbol on the end of the line)

I then replaced the symblink with the file it linked to (ie same name)

The explorer and git view did not update, even when I used the refresh.

I had to restate vs code. 

But Git view still show no changes but a `git status` on command line shows it as a `typechange:`  change not staged.

**Comment by SteveALee** [comment]
See also #91100 which has been closed.

**Comment by eamodio** [comment]
Duplicate of #91100 (which I re-opened)
