### ISSUE TITLE
Santa Hat on vscode insiders and removing the hat is very offensive to me

### ISSUE THREAD

**Issue by 0xGREG** [microsoft/vscode#112767]
It is very offensive to me that you removed the santa hat because I'm an activist for santa hat rights and it makes me deeply angried that the santa hat is removed...

Version: 1.42.0-insider (user setup)
Commit: 26f5dfc
Date: 2019-12-18T10:34:34.277Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

Install latest build of insiders.
Does this issue occur when all extensions are disabled?: Yes

Additional reading on the issue that most certainly needs to be considered: https://www.etsy.com/au/market/santa_believer

**Comment by 0xGREG** [comment]
this should be important please check

**Comment by yume-chan** [comment]
See #87440

Update to a newer version and it will be gone.

**Comment by 0xGREG** [comment]
> See #87440
> 
> Update to a newer version and it will be gone.

That's the exact issue. I'm a Santa Hat activist and removing the Santa Hat deeply offends me!

**Comment by yume-chan** [comment]
That's not funny.

But I made it back.

![image](https://user-images.githubusercontent.com/1330321/102841095-3d7a8480-443f-11eb-87f4-d85405304340.png)

```json
	"customizeUI.stylesheet": {
		".codicon-settings-view-bar-icon::after": "content:''; position: absolute; top: -2px; width: 100%; height: 30px; background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTYyLjQzIiBoZWlnaHQ9IjE3Mi40IiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAxNjIuNDM0OTEgMTcyLjQwMTkiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6Y2M9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zIyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgo8ZGVmcz4KPGxpbmVhckdyYWRpZW50IGlkPSJiIiB4MT0iLTI1NTguMSIgeDI9Ii0yNjAzLjciIHkxPSItMTQuMDU2IiB5Mj0iLTEyMC41NyIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCguMjgwODQgMCAwIC4zMDI3NCA5OTAuNzIgNzE1Ljg2KSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjMDAwMDgzIiBvZmZzZXQ9IjAiLz4KPHN0b3Agc3RvcC1jb2xvcj0iIzAwMDA4MyIgc3RvcC1vcGFjaXR5PSIwIiBvZmZzZXQ9IjEiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJhIiB4MT0iLTI2NTkuNyIgeDI9Ii0yNjI3LjkiIHkxPSIxNjIuNDIiIHkyPSI3NC4wMjkiIGdyYWRpZW50VHJhbnNmb3JtPSJtYXRyaXgoLjM1OTM0IDAgMCAuMzU5MzQgMTE5Mi40IDcyMS45MykiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iIzAwMDA4MCIgb2Zmc2V0PSIwIi8+CjxzdG9wIHN0b3AtY29sb3I9IiMwMDAwODAiIHN0b3Atb3BhY2l0eT0iMCIgb2Zmc2V0PSIxIi8+CjwvbGluZWFyR3JhZGllbnQ+CjwvZGVmcz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1My40NiAtNjU3Ljc3KSI+CjxwYXRoIGQ9Im0yMzMuMjMgNzEwLjUxYzAuMzU1NTMtMi4yMDYzIDEuODg2LTQuMDQ4MyA0LjUzODUtNC41NjE4IDMuNzk1LTQuODgxMyA1LjU0NjgtOS45NDg3IDYuNjk4OC0xNS4wN2wyOC42OTEgMy4wMjU1YzIwLjI1OCAyMS43NzkgMzcuODA2IDUwLjA2MyAzMy4yMTMgODYuOTM1bC0xMTkuNDItNTguNjIzYzEyLjc5Ni04LjE1MiAyOC45MzktMTIuODE0IDQ2LjI3OS0xMS43MDZ6IiBmaWxsPSIjZjAwIiBzdHJva2U9IiM1MDAiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxLjQzNzQiLz4KPHBhdGggZD0ibTE4OC40IDcyMS40OWMyNC4wODctMy45NTMxIDQyLjE3Mi0wLjE3ODcyIDU2Ljc1NCA1LjU4NDUgMjYuMTEgMTIuNzA4IDQ4Ljg0NSAyOC41NDEgNjEuOTYxIDUzLjI4MyAzLjMwNDMgNi42MjAxIDYuMTE0NSAxMy4xMTcgOC4wNTIxIDE5LjM5NS0wLjU4ODI0IDEzLjczOS03LjUzMjEgMTcuNjU2LTExLjQ4IDI2LjIwMy0zLjQ4MTIgMy42OTI5LTUuNjI2OSAyLjcxMi04LjIyNDkgMy4zMTMxbC0wLjE0NDA5LTguODgxOGMtMTAuODc3LTI2LjAxMi0zNi4yNDMtNDYuNTkyLTYxLjQzMy01Ny42MjctMjMuMDE2LTEwLjA4Mi00OS4xMDQtMTUuMDg5LTcwLjMwNS02LjA2NzgtMi40MzY0IDIuNTQ3Ni00LjY5NjIgNS4zMjQ0LTcuMTI1NyA4LjM1NTctMy4zMjU4LTQuMDE3OC0xLjk4MjctMTEuNjY2LTIuMTQ3NS0xNy44NjEgNi40NzAzLTEwLjAwNiAxMi4wMTItMTIuMTk5IDE4LjA4Mi0xOS4wMDQgMi42Mjc1LTMuMTQxMyA1LjI1ODYtNy4yNzEyIDE2LjAwOS02LjY5MzF6IiBmaWxsPSIjZmRmZWZkIiBzdHJva2U9IiM1MDAiIHN0cm9rZS13aWR0aD0iMS40Mzc0Ii8+CjxlbGxpcHNlIGN4PSIyNjEuNzIiIGN5PSI2NzkuNjYiIHJ4PSIyMS41ODIiIHJ5PSIyMS4xOTYiIGZpbGw9IiNmZGZlZmQiIHN0cm9rZT0iIzUwMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2Utd2lkdGg9IjEuMzk0MiIvPgo8ZWxsaXBzZSBjeD0iMjYxLjk1IiBjeT0iNjgwLjY4IiByeD0iMTguMDU0IiByeT0iMTcuNzMyIiBmaWxsPSJ1cmwoI2IpIiBvcGFjaXR5PSIuMjkyMTgiIHN0cm9rZS13aWR0aD0iLjI5MTU4Ii8+CjxwYXRoIGQ9Im0xNzQuNiA3MzAuMmM2MC44NC0wLjk1MDk2IDEwOS4zMSAxOC43NDYgMTM3LjU3IDcwLjQyLTIuOTUxNyA3Ljg5LTYuNjEyMiAxNC4zNjMtMTAuNTI2IDIwLjMyNy0xOS43LTQ3LjU3My04Ni42MDEtODIuOTA3LTE0NC42NS03Mi43ODEgMi4zOTQ5LTUuOTg5NSAxMS4zMTgtMTEuOTc5IDE3LjYwNS0xNy45Njh6IiBmaWxsPSJ1cmwoI2EpIiBvcGFjaXR5PSIuMTI3NTciIHN0cm9rZS13aWR0aD0iLjM1OTM0Ii8+CjxwYXRoIGQ9Im0yNzIuMjkgNjYxLjNjMi43NTcyIDMuMzM5IDQuNDEzIDcuNTk0NiA0LjQxMyAxMi4yMjkgMCAxMC43MjktOC44NjI0IDE5LjQyNy0xOS43ODYgMTkuNDI3LTYuNjkwNiAwLTEyLjU5MS0zLjI3MTEtMTYuMTctOC4yNjQ4IDIuMjU1MyA5LjMzODkgMTAuNzg5IDE2LjI5NCAyMC45ODggMTYuMjk0IDExLjkxOSAwIDIxLjU4My05LjQ5NDUgMjEuNTgzLTIxLjIwMSAwLTcuOTM5My00LjQ0OS0xNC44NTItMTEuMDI3LTE4LjQ4NHoiIG9wYWNpdHk9Ii4xMDciIHN0cm9rZS13aWR0aD0iLjM1OTM0Ii8+CjxwYXRoIGQ9Im0yMzMuMTggNzEwLjQ5YzIuODI2Ni0wLjA0NzcgNS4zNDcgMC4yMjMxMyA3LjQ4MzMgMC41MTIzOSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjNTAwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS13aWR0aD0iMS40Mzc0Ii8+CjwvZz4KPG1ldGFkYXRhPgo8cmRmOlJERj4KPGNjOldvcms+CjxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0Pgo8ZGM6dHlwZSByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIi8+CjxjYzpsaWNlbnNlIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluLyIvPgo8ZGM6cHVibGlzaGVyPgo8Y2M6QWdlbnQgcmRmOmFib3V0PSJodHRwOi8vb3BlbmNsaXBhcnQub3JnLyI+CjxkYzp0aXRsZT5PcGVuY2xpcGFydDwvZGM6dGl0bGU+CjwvY2M6QWdlbnQ+CjwvZGM6cHVibGlzaGVyPgo8L2NjOldvcms+CjxjYzpMaWNlbnNlIHJkZjphYm91dD0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluLyI+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjUmVwcm9kdWN0aW9uIi8+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjRGlzdHJpYnV0aW9uIi8+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjRGVyaXZhdGl2ZVdvcmtzIi8+CjwvY2M6TGljZW5zZT4KPC9yZGY6UkRGPgo8L21ldGFkYXRhPgo8L3N2Zz4K'); background-size: 24px; background-repeat: no-repeat; background-position: 13px 5px;"
	}
```

**Comment by 0xGREG** [comment]
> That's not funny.
> 
> But I made it back.
> 
> ![image](https://user-images.githubusercontent.com/1330321/102841095-3d7a8480-443f-11eb-87f4-d85405304340.png)
> 
> ```json
> 	"customizeUI.stylesheet": {
> 		".codicon-settings-view-bar-icon::after": "content:''; position: absolute; top: -2px; width: 100%; height: 30px; background-image: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iMTYyLjQzIiBoZWlnaHQ9IjE3Mi40IiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAxNjIuNDM0OTEgMTcyLjQwMTkiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6Y2M9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zIyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgo8ZGVmcz4KPGxpbmVhckdyYWRpZW50IGlkPSJiIiB4MT0iLTI1NTguMSIgeDI9Ii0yNjAzLjciIHkxPSItMTQuMDU2IiB5Mj0iLTEyMC41NyIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCguMjgwODQgMCAwIC4zMDI3NCA5OTAuNzIgNzE1Ljg2KSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgo8c3RvcCBzdG9wLWNvbG9yPSIjMDAwMDgzIiBvZmZzZXQ9IjAiLz4KPHN0b3Agc3RvcC1jb2xvcj0iIzAwMDA4MyIgc3RvcC1vcGFjaXR5PSIwIiBvZmZzZXQ9IjEiLz4KPC9saW5lYXJHcmFkaWVudD4KPGxpbmVhckdyYWRpZW50IGlkPSJhIiB4MT0iLTI2NTkuNyIgeDI9Ii0yNjI3LjkiIHkxPSIxNjIuNDIiIHkyPSI3NC4wMjkiIGdyYWRpZW50VHJhbnNmb3JtPSJtYXRyaXgoLjM1OTM0IDAgMCAuMzU5MzQgMTE5Mi40IDcyMS45MykiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KPHN0b3Agc3RvcC1jb2xvcj0iIzAwMDA4MCIgb2Zmc2V0PSIwIi8+CjxzdG9wIHN0b3AtY29sb3I9IiMwMDAwODAiIHN0b3Atb3BhY2l0eT0iMCIgb2Zmc2V0PSIxIi8+CjwvbGluZWFyR3JhZGllbnQ+CjwvZGVmcz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE1My40NiAtNjU3Ljc3KSI+CjxwYXRoIGQ9Im0yMzMuMjMgNzEwLjUxYzAuMzU1NTMtMi4yMDYzIDEuODg2LTQuMDQ4MyA0LjUzODUtNC41NjE4IDMuNzk1LTQuODgxMyA1LjU0NjgtOS45NDg3IDYuNjk4OC0xNS4wN2wyOC42OTEgMy4wMjU1YzIwLjI1OCAyMS43NzkgMzcuODA2IDUwLjA2MyAzMy4yMTMgODYuOTM1bC0xMTkuNDItNTguNjIzYzEyLjc5Ni04LjE1MiAyOC45MzktMTIuODE0IDQ2LjI3OS0xMS43MDZ6IiBmaWxsPSIjZjAwIiBzdHJva2U9IiM1MDAiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxLjQzNzQiLz4KPHBhdGggZD0ibTE4OC40IDcyMS40OWMyNC4wODctMy45NTMxIDQyLjE3Mi0wLjE3ODcyIDU2Ljc1NCA1LjU4NDUgMjYuMTEgMTIuNzA4IDQ4Ljg0NSAyOC41NDEgNjEuOTYxIDUzLjI4MyAzLjMwNDMgNi42MjAxIDYuMTE0NSAxMy4xMTcgOC4wNTIxIDE5LjM5NS0wLjU4ODI0IDEzLjczOS03LjUzMjEgMTcuNjU2LTExLjQ4IDI2LjIwMy0zLjQ4MTIgMy42OTI5LTUuNjI2OSAyLjcxMi04LjIyNDkgMy4zMTMxbC0wLjE0NDA5LTguODgxOGMtMTAuODc3LTI2LjAxMi0zNi4yNDMtNDYuNTkyLTYxLjQzMy01Ny42MjctMjMuMDE2LTEwLjA4Mi00OS4xMDQtMTUuMDg5LTcwLjMwNS02LjA2NzgtMi40MzY0IDIuNTQ3Ni00LjY5NjIgNS4zMjQ0LTcuMTI1NyA4LjM1NTctMy4zMjU4LTQuMDE3OC0xLjk4MjctMTEuNjY2LTIuMTQ3NS0xNy44NjEgNi40NzAzLTEwLjAwNiAxMi4wMTItMTIuMTk5IDE4LjA4Mi0xOS4wMDQgMi42Mjc1LTMuMTQxMyA1LjI1ODYtNy4yNzEyIDE2LjAwOS02LjY5MzF6IiBmaWxsPSIjZmRmZWZkIiBzdHJva2U9IiM1MDAiIHN0cm9rZS13aWR0aD0iMS40Mzc0Ii8+CjxlbGxpcHNlIGN4PSIyNjEuNzIiIGN5PSI2NzkuNjYiIHJ4PSIyMS41ODIiIHJ5PSIyMS4xOTYiIGZpbGw9IiNmZGZlZmQiIHN0cm9rZT0iIzUwMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBzdHJva2Utd2lkdGg9IjEuMzk0MiIvPgo8ZWxsaXBzZSBjeD0iMjYxLjk1IiBjeT0iNjgwLjY4IiByeD0iMTguMDU0IiByeT0iMTcuNzMyIiBmaWxsPSJ1cmwoI2IpIiBvcGFjaXR5PSIuMjkyMTgiIHN0cm9rZS13aWR0aD0iLjI5MTU4Ii8+CjxwYXRoIGQ9Im0xNzQuNiA3MzAuMmM2MC44NC0wLjk1MDk2IDEwOS4zMSAxOC43NDYgMTM3LjU3IDcwLjQyLTIuOTUxNyA3Ljg5LTYuNjEyMiAxNC4zNjMtMTAuNTI2IDIwLjMyNy0xOS43LTQ3LjU3My04Ni42MDEtODIuOTA3LTE0NC42NS03Mi43ODEgMi4zOTQ5LTUuOTg5NSAxMS4zMTgtMTEuOTc5IDE3LjYwNS0xNy45Njh6IiBmaWxsPSJ1cmwoI2EpIiBvcGFjaXR5PSIuMTI3NTciIHN0cm9rZS13aWR0aD0iLjM1OTM0Ii8+CjxwYXRoIGQ9Im0yNzIuMjkgNjYxLjNjMi43NTcyIDMuMzM5IDQuNDEzIDcuNTk0NiA0LjQxMyAxMi4yMjkgMCAxMC43MjktOC44NjI0IDE5LjQyNy0xOS43ODYgMTkuNDI3LTYuNjkwNiAwLTEyLjU5MS0zLjI3MTEtMTYuMTctOC4yNjQ4IDIuMjU1MyA5LjMzODkgMTAuNzg5IDE2LjI5NCAyMC45ODggMTYuMjk0IDExLjkxOSAwIDIxLjU4My05LjQ5NDUgMjEuNTgzLTIxLjIwMSAwLTcuOTM5My00LjQ0OS0xNC44NTItMTEuMDI3LTE4LjQ4NHoiIG9wYWNpdHk9Ii4xMDciIHN0cm9rZS13aWR0aD0iLjM1OTM0Ii8+CjxwYXRoIGQ9Im0yMzMuMTggNzEwLjQ5YzIuODI2Ni0wLjA0NzcgNS4zNDcgMC4yMjMxMyA3LjQ4MzMgMC41MTIzOSIgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjNTAwIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS13aWR0aD0iMS40Mzc0Ii8+CjwvZz4KPG1ldGFkYXRhPgo8cmRmOlJERj4KPGNjOldvcms+CjxkYzpmb3JtYXQ+aW1hZ2Uvc3ZnK3htbDwvZGM6Zm9ybWF0Pgo8ZGM6dHlwZSByZGY6cmVzb3VyY2U9Imh0dHA6Ly9wdXJsLm9yZy9kYy9kY21pdHlwZS9TdGlsbEltYWdlIi8+CjxjYzpsaWNlbnNlIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluLyIvPgo8ZGM6cHVibGlzaGVyPgo8Y2M6QWdlbnQgcmRmOmFib3V0PSJodHRwOi8vb3BlbmNsaXBhcnQub3JnLyI+CjxkYzp0aXRsZT5PcGVuY2xpcGFydDwvZGM6dGl0bGU+CjwvY2M6QWdlbnQ+CjwvZGM6cHVibGlzaGVyPgo8L2NjOldvcms+CjxjYzpMaWNlbnNlIHJkZjphYm91dD0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbGljZW5zZXMvcHVibGljZG9tYWluLyI+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjUmVwcm9kdWN0aW9uIi8+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjRGlzdHJpYnV0aW9uIi8+CjxjYzpwZXJtaXRzIHJkZjpyZXNvdXJjZT0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjRGVyaXZhdGl2ZVdvcmtzIi8+CjwvY2M6TGljZW5zZT4KPC9yZGY6UkRGPgo8L21ldGFkYXRhPgo8L3N2Zz4K'); background-size: 24px; background-repeat: no-repeat; background-position: 13px 5px;"
> 	}
> ```

Being a religion sheep is not funny and unhealthy

**Comment by chrisdias** [comment]
:)
