### ISSUE TITLE
Hangs my Laptop fully for hours

### ISSUE THREAD

**Issue by BerlinLion** [microsoft/vscode#112703]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Visual Studio hangs for minutes and makes my Laptop to crash. It's happening since now 2 days. It fully prevents me from working. It makes me really upset, since this bug is fully wasting my time. X(

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2593)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 4, 3|
|Memory (System)|7.68GB (0.11GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 128d5747-9ed1-4d2f-ace9-b67a4d96c819|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (120)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
namespace|adr|1.1.2
vscode-flutter-helper|aks|0.2.5
stylus|Ala|0.0.4
markdown-toc|Ala|1.5.6
flutter-snippets|ale|2.0.0
vscode-json|and|1.5.0
flutter-internationalize|api|0.1.6
dependencies-visualizer|art|0.0.2
unity-code-snippets-improved|ble|1.4.1
flutter-view-vscode|blu|1.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
regex|chr|0.2.0
ccs-flutter-color|cir|0.1.3
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.17.1
flutter|Dar|3.17.0
vscode-markdownlint|Dav|0.38.0
mustache|daw|1.1.1
vscode-faker|dee|1.4.1
react-redux-react-router-snippets|dis|0.4.29
githistory|don|0.6.14
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
vscode-npm-script|eg2|0.3.13
RunOnSave|eme|0.2.0
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.0
json-tools|eri|1.0.2
vscode-flutter-i18n-json|ess|0.28.0
pubspec-dependency-search|eve|1.1.0
vscode-todo-plus|fab|4.18.0
unity-dev-pack|fab|1.0.1
git-project-manager|fel|1.7.1
bloc|Fel|5.5.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
file-icons|fil|1.0.28
auto-close-tag|for|0.5.9
terminal|for|0.0.10
vscode-pull-request-github|Git|0.22.0
sass-lint|gle|1.0.6
flutter-stylizer|gml|0.0.16
vscode-flutter-files|gor|2.2.0
complete-flutter-extension-pack|Gul|1.1.0
ansible|haa|0.2.8
vscode-auto-open-markdown-preview|hnw|0.0.4
rest-client|hum|0.24.4
useful-react-snippets|igo|3.0.0
compareit|in4|0.0.2
generic-extension-pack|itm|0.0.9
html-extension-pack|itm|0.0.7
node-extension-pack|itm|0.0.9
jenkinsfile-support|ivo|1.1.0
RelativePath|jak|1.4.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
react-component|jer|1.0.4
pubspec-assist|jer|2.2.1
flutter-mvc-generator|kur|0.1.0
node-module-intellisense|lei|1.5.0
flutter-img-sync|Lih|0.1.4
flutter-intl|loc|1.13.0
flutter-mvvm-architecture-generator|mad|1.6.0
flutter-tree|mar|1.0.0
metago|met|4.2.0
MetaJump|met|1.1.1
MetaWord|met|1.2.1
git-graph|mhu|1.28.0
code-beautifier|mic|2.3.3
gitignore|mic|1.0.1
vscode-csscomb|mrm|5.3.2
vscode-less|mrm|0.6.3
vscode-pugbeautify|mrm|1.0.2
vscode-puglint|mrm|2.3.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.9.0
mssql|ms-|1.10.0
remote-containers|ms-|0.154.1
vsliveshare|ms-|1.0.3303
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
awesome-flutter-snippets|Nas|2.0.4
live-server-preview|neg|0.1.4
vetur|oct|0.31.3
indent-rainbow|ode|7.4.0
dartgettersetter|Pet|0.0.4
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.4.0
polacode|pnp|0.3.4
explorer-exclude-vscode-extension|Red|1.2.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
gi|rub|0.2.11
partial-diff|ryu|1.4.1
jenkinsfile-support|sec|0.1.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.13
mdx|sil|0.1.0
vscode-multiclip|sle|0.1.5
autoimport|ste|1.5.3
ansible-autocomplete|tim|0.0.2
todo-list|Tza|1.6.0
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.13.0
vscode-jumpy|wma|0.3.1
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.11
html-css-class-completion|Zig|1.19.0
vscode-proto3|zxh|0.5.2

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the new bisect command to discover if perhaps one of your 120 extensions is causing the issue.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by BerlinLion** [comment]
How can I use a bisect command?!

**Comment by jrieken** [comment]
"F1 > Start Extension Bisect"

**Comment by BerlinLion** [comment]
At the very beginning of bisect process start, after having disabled 61
extensions by bisect, I was asked if it's good or bad and I pressed bad,
and immediately there was a dialog telling that it was done and that no
issues could have been found, also there's no dialog button to close that
dialog (see attached screenshot). I have to force-close visual studio
because of this bug of bisect.

**Comment by BerlinLion** [comment]
That dialog covers even the system's own "force-close" button (see attached
screenshot). What's that?!

**Comment by bpasero** [comment]
Assigning based on latest comments around extension bisect not working.

**Comment by jrieken** [comment]
@BerlinLion no screenshots attached

**Comment by jrieken** [comment]
>  disabled 61
extensions by bisect, I was asked if it's good or bad and I pressed bad,
and immediately there was a dialog telling that it was done and that no
issues could have been found

That's to be expected. At first it disables all extensions and when it is still bad with that then extension bisect is done because it isn't an extension issue

**Comment by BerlinLion** [comment]
Ok, thanks.

**Comment by jrieken** [comment]
Tho, we still need to know what's slow on your system. Please follow this guide:  https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
