### ISSUE TITLE
Debugger stopped working

### ISSUE THREAD

**Issue by danieltkach** [microsoft/vscode#112785]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

All of a sudden I can't run a debugger in a simple code like a for loop. I don't know what to try, this stopped working all of a sudden and I'm not finding any info on how to fix it.
Any guidance is appreciated.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.45GB free)|
|Process Argv|--crash-reporter-id 3b22fead-da86-4ee7-a37f-940993617a8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.3
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
csharpextensions|jch|1.3.1
vscode-styled-components|jpo|1.4.1
csharp|ms-|1.23.8
js-debug-nightly|ms-|2020.12.1517
debugger-for-chrome|msj|4.12.11
vscode-extension-auto-import|Nuc|1.4.3
LiveServer|rit|5.6.1
ayu|tea|0.20.1
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459:30237187

```

</details>

**Comment by weinand** [comment]
What debugger are you using?
Please provide detailed steps.

**Comment by danieltkach** [comment]
Hi! I'm not sure what debugger I'm using, now adding this into launch.json the debugger starts, but it's getting into all the implementation files (or whatever they are called). So if there's a "typeof" call in my code it gets very deep into all sorts of foreign files.
{
	"version": "0.2.0",
	"configurations": [
	  {
		"type": "node",
		"request": "launch",
		"name": "Launch Program",
		"skipFiles": ["<node_internals>/**"],
		"program": "${workspaceFolder}\\app.js"
	  }
	]
  }

I don't want the debugger to do this, I just want it to debug my own code as it's been for a long time.
Thanks. I'm lost.

**Comment by danieltkach** [comment]
Hi, nothing came up by doing that. When I debug a simple program like:
```
function secuenciaHenry(array, n) {
	if (n < 0) return false;

	array.forEach((x, i) => {
		if (typeof (x) === 'string') array[i] = array[i].length;
	})


	if (n >= 0 && n <= 2)
		return array[n];

	let serie = [...array];

	for (let i = 3; i <= n; i++) {
		serie[i] = (serie[i - 1] + serie[i - 2] + serie[i - 3]) * 2;
	}

	return serie[n];
}


let array = ["Franco", 1, "Henry"];
let resultado = secuenciaHenry(array, 6);
console.log(resultado);
```
The debug goes through run_main.js, loader.js, task_queues.js and all sorts of strange files...

**Comment by connor4312** [comment]
Can you take a screenshot of the VS Code window, with the Debug Console visible, after following the instructions in https://github.com/microsoft/vscode/issues/112785#issuecomment-749059617?

**Comment by danieltkach** [comment]
![coJ9ZQpO7n](https://user-images.githubusercontent.com/70539591/103189736-da5c7800-48ac-11eb-9162-760f15bf428d.png)
Here goes...

**Comment by connor4312** [comment]
Thanks -- can you also share the debug configuration you're using? It looks like it's different that the one you posted above.

**Comment by danieltkach** [comment]
Hi Connor, how do I get that?

**Comment by weinand** [comment]
@danieltkach the "debug configuration" lives in the launch.json file and configures the debug session that you can launch via the drop down menu in the debug viewlet:

<img width="981" alt="2020-12-29_15-39-58" src="https://user-images.githubusercontent.com/1898161/103291498-27933380-49ec-11eb-8f48-01be1c302645.png">

**Comment by danieltkach** [comment]
Hey guys. I just realized, is this configuration local to project folders? I thought it was always global... I realized this because there was no launch.json on the project I'm working on, but on the one I got the screenshot from there's this:
{
	// Use IntelliSense to learn about possible attributes.
	// Hover to view descriptions of existing attributes.
	// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"trace": true,
			"type": "pwa-node",
			"request": "launch",
			"name": "Launch Program",
			"skipFiles": [
				"<node_internals>/**"
			],
			"program": "${workspaceFolder}\\checkpoint.js"
		}
	]
}


How do I make it global? And I guess my main question is... how do I make it work like it used to, whatever that is, I'm sure the debugger didn't drift into the runtime library files (or whatever they are called...) Thank you so much for your patience with a beginner like me. This works all so different than what it used to be 10+ years ago while I programmed in Pascal...

**Comment by danieltkach** [comment]
Any updates on this? @weinand @connor4312

**Comment by weinand** [comment]
@danieltkach yes, a launch.json in a ".vscode" folder applies to the project folder. But you can add launch configs to the workspace or user settings too. Please read https://code.visualstudio.com/docs/editor/debugging#_launch-configurations
