### ISSUE TITLE
No "Launch TensorBoard" option in command palette

### ISSUE THREAD

**Issue by drjinying** [microsoft/vscode#112790]
The latest VS Code asks me to launch TensorBoard natively or not. Click yes does nothing. It also says I can launch the tensorboard anytime by searching for the command in the command palette, however I never found this option in the command palette.

- VSCode Version:1.52.1
- OS Version:Ubuntu 20

Steps to Reproduce:

1.Open Command Palette
2.Search for "Launch TensorBoard"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
VS Code does not have a builtin "Launch TensorBoard" command.

**Comment by drjinying** [comment]
@weinand  Are you really sure? This is what VS Code is telling me:
![Screenshot from 2020-12-17 23-59-54](https://user-images.githubusercontent.com/5470845/102589600-15e48e80-40c4-11eb-94e0-06ff0cab4aeb.png)

**Comment by weinand** [comment]
If you launch VS Code with `--disable-extensions` command line flag, can you still find a  "Launch TensorBoard" command?
