### ISSUE TITLE
Issue with mini window that appears when hovering over a variable

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [microsoft/vscode#112736]
- VSCode Version: December 2020 Release
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. place your cursor over a variable and the mini window appears.

Does this issue occur when all extensions are disabled?: Yes/No Don't Know.

It is extremely irritating when I try to select a variable, but the mini window appears and I end up selecting the text inside the mini window, instead of the variable. 
Here is the image for your reference.
![bug](https://user-images.githubusercontent.com/24194646/102489617-ba021180-4093-11eb-9c41-e12f62a15840.png)

Ideally, this mini window should appear above the cursor position and not over it.

**Comment by alexdima** [comment]
@nisarg-ujjainkar You can configure `"editor.hover.enabled": false` to permanently disable the hover or you can configure `"editor.hover.delay": 2000` to render the hover only after 2 seconds and not after the default 300ms.
