### ISSUE TITLE
Provide method to cleanly uninstall an edition of VSCode on macOS

### ISSUE THREAD

**Issue by richiksc** [microsoft/vscode#112700]
I recently uninstalled the Exploration build of VSCode from my Mac after support for Apple Silicon landed in insiders. I uninstalled as is normally done on Mac - dragging the app from Applications to the Trash. However, VSCode leaves behind lots of preferences and other folders on macOS after uninstalling. It would be a good idea to have a command for removing these in the command palette to cleanup before you uninstall the app itself.

Here's a list of the things that I had to remove, with curly braces as optional suffixes depending on the release channel installed.

```
rm -rf ~/Library/Preferences/com.microsoft.VSCode{Exploration,Insiders}.helper.plist 
rm -rf ~/Library/Preferences/com.microsoft.VSCode{Exploration,Insiders}.plist 
rm -rf ~/Library/Caches/com.microsoft.VSCode{Exploration,Insiders}
rm -rf ~/Library/Caches/com.microsoft.VSCode{Exploration,Insiders}.ShipIt/
rm -rf ~/Library/Application\ Support/Code { - Exploration, - Insiders}/
rm -rf ~/Library/Saved\ Application\ State/com.microsoft.VSCode{Exploration,Insiders}.savedState/
rm -rf ~/.vscode{-exploration,-insiders}/
rm /usr/local/bin/code{-exploration,-insiders}
```

**Comment by joaomoreno** [comment]
Unfortunately this is a classic macOS app issue. This software is pretty good, I use it personally: https://cleanmymac.com/
