### ISSUE TITLE
Option to remove 'This may be converted to an async function' message

### ISSUE THREAD

**Issue by orassayag** [microsoft/vscode#112740]
Is there any way to remove this specific tooltip message? It would be great to add this option. Thanks.
![Untitled](https://user-images.githubusercontent.com/5759067/102495189-78b33700-407e-11eb-96c5-b7bd10999bca.png)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
