### ISSUE TITLE
Typescript engine failed

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [microsoft/vscode#112791]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

unknown, just opened Visual Studio like I do every morning

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:46:53.673Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 13, 19|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 30d3d2e1-d6d1-48a3-86dd-858adc2e7202|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
turbo-console-log|Cha|2.1.6
es7-react-js-snippets|dsz|3.0.0
gitlens|eam|11.0.6
vscode-html-css|ecm|1.2.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
Angular2|joh|11.0.0
vs-color-picker|lih|1.0.0
syntax-project-pbxproj|mar|0.1.3
code-beautifier|mic|2.3.3
dotenv|mik|1.0.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
vscode-typescript-tslint-plugin|ms-|1.3.2
vscode-react-native|msj|1.2.0
typescript-hero|rbb|3.0.0
java|red|0.73.0
ayu|tea|0.20.1
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
html-css-class-completion|Zig|1.19.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30237610
vsjup459cf:30237188

```

</details>

**Comment by AlphaJuliettOmega** [comment]
@vscodebot it's not any of those.

I've narrowed it down to Jupyter, perhaps
I get an error in the 'Dev Console' of VS Code, not the Terminal.
But that's for Python so I don't understand how it could make the Typescript engine crash.
https://github.com/microsoft/vscode/issues/103526
and
https://stackoverflow.com/a/55507284/5334945
mention some flag, that's already set to False on my setup

Yet I can't disable or remove Jupyter even though I've never used it before.

**Comment by AlphaJuliettOmega** [comment]
I successfully disabled both the Python + Jupyter extensions, I'll worry about it when I need python again.

BUT

for some reason Jupyter doesn't unload.

```Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by AlphaJuliettOmega** [comment]
@mjbvz it's just an error that came up every day for a week or so, so I opened this thread but the error has since stopped appearing. Thanks for following up but it must have been patched out already (I have updated VS Code since then)
