### ISSUE TITLE
Vscode deleted itself

### ISSUE THREAD

**Issue by asarra** [microsoft/vscode#112727]
- VSCode Version:
- OS Version: Win10

Steps to Reproduce:

1. Unknown
2. Unknown

Does this issue occur when all extensions are disabled?: Yes/No - Idk

Vscode deleted itself. I noticed it when I started my PC this morning. Unfortunately, I do not know how it managed to do it and what caused it.

**Comment by dschuessler** [comment]
What makes you believe that VSCode did this rather than something (or someone) else?

**Comment by moralesmx** [comment]
That happened to me once. In my research i found that it happens when you turn off your computer and in the middle of a vscode update. The updater deletes the old version and the computer turns off before the updater installs the new one.

**Comment by asarra** [comment]
> 
> 
> What makes you believe that VSCode did this rather than something (or someone) else?

No one could have done it since my family does not know the password to my os and I lock my door.
I have seen people complain that vscode deleted itself for the 3rd or 4th time. Thus I think that this might be related to that.
I have no virus on my PC either. And I doubt that any program would gain a benefit from deleting vscode lol

**Comment by joaomoreno** [comment]
Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
