### ISSUE TITLE
Hover not showing on any decorations

### ISSUE THREAD

**Issue by tgodzik** [microsoft/vscode#112733]
- VSCode Version: 1.52.0
- OS Version: Ubuntu 20.04 - this is reproducible also on MacOs, but seems to work on windows

Steps to Reproduce:

1. Create decoration type:
``` typescript
let decorationType: TextEditorDecorationType = window.createTextEditorDecorationType(
  {
    rangeBehavior: DecorationRangeBehavior.OpenClosed,
  }
);
```

2. Add decoration:
```typescript
        const option: DecorationOptions = {
            range: new Range(
              new Position(1, 5),
              new Position(1, 5)
            ),
            hoverMessage: "test message",
            renderOptions: { after: {contentText : "text" }},
          };
        });
        editor.setDecorations(decorationType, [option]);
```

3. "test message" hover will not show

This seemed to work with 1.51.x versions

The bug is similar to https://github.com/microsoft/vscode/issues/105302, but this time it stopped working altogether and would force us to rework a large part of the extension.

Does this issue occur when all extensions are disabled?: No, but it's mainly due to the fact that this is only used in extensions

**Comment by tgodzik** [comment]
Actually, this seemed to be an issue on our side. Somehow we were probably using an undocumented behaviour, which now changed. I managed to do a fix here: https://github.com/scalameta/metals-vscode/pull/470

**Comment by alexdima** [comment]
I don't remember changing anything on our side in this area. FYI @jrieken

**Comment by tgodzik** [comment]
What seems to have happened is that we seem to have been sending an object with `kind` and `value` fields and that was added to hover, but somehow it worked. It stopped doing so with 1.52.0. Seems weird that it worked in the first place, but my typescript foo is not that great :sweat_smile:
