### ISSUE TITLE
Allow for false `files.exclude` and `search.exclude` rules to override other rules

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11278]
`files.exclude` and `searh.exclude` should respect exclusion from those rules

``` js
"files.exclude": {
  "**/*.js": true, // will hide all js
  "some-module.js": false // currently effects nothing should prevent 'some-module.js' from being hidden
}
```

**Comment by bpasero** [comment]
Currently the rules are mutually exclusive...

**Comment by whitecolor** [comment]
I think first as it is an exclusion rules, and by default all file are NOT excluded, then first should be applied entries with `true` value, and then entries with `false` should exclude from excluded if overlap.

**Comment by whitecolor** [comment]
bump, I believe it would be useful though.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/869
