### ISSUE TITLE
python webbrowser on WSL

### ISSUE THREAD

**Issue by leelhn2345** [microsoft/vscode#112721]
Issue Type: <b>Bug</b>

On WSL 2 Ubuntu-20.04,  I used the following code:

```py
import webbrowser as wb
wb.open("index.html", new=2)
```

Instead of opening the desired html file on web browser, it opens up the html code in a new vscode tab.
This issue did not occur few weeks ago.

Again I tried the same code on windows terminal WSL CLI, the python code was able to open the HTML file in web browser.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.21277
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics          (16 x 2994)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (4.62GB free)|
|Process Argv|--crash-reporter-id bf77eaf0-1c9c-4c4b-87d6-3c6efe693d39|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 4900HS with Radeon Graphics (16 x 2994)|
|Memory (System)|7.48GB (2.34GB free)|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
c-cpp-makefile-project|adr|1.1.0
emojisense|bie|0.8.0
bracket-pair-colorizer-2|Coe|0.2.0
auto-close-tag|for|0.5.9
auto-rename-tag|for|0.1.5
theme-monokai-pro-vscode|mon|1.1.18
remote-containers|ms-|0.154.1
remote-wsl|ms-|0.52.0
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.4.0
highlight-matching-tag|vin|0.10.0
JavaScriptSnippets|xab|1.8.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.0.6
vscode-html-css|ecm|1.1.6
prettier-vscode|esb|5.8.0
code-runner|for|0.11.1
vscode-pull-request-github|Git|0.22.0
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.192
beautify|Hoo|1.5.0
vsc-python-indent|Kev|1.12.0
kite|kit|0.135.0
node-module-intellisense|lei|1.5.0
restructuredtext|lex|135.0.0
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
vsliveshare|ms-|1.0.3303
color-highlight|nau|2.3.0
indent-rainbow|ode|7.4.0
pdf|tom|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
can you try running extension bisect to makes sure this problem wasn't introduced by an extension?

**Comment by leelhn2345** [comment]
I've done extension bisect and am pretty sure it isn't an extension issue.

I just tried running the same code on the previous release and the code works as desired.
This bug appeared after I installed the latest VScode updates.

**Comment by aeschli** [comment]
I pushed a fix to Insiders and the Remote-WSL extension
