### ISSUE TITLE
SSH Remote Extension: Do not auto-forward ephemeral ports by default

### ISSUE THREAD

**Issue by achamayou** [microsoft/vscode#112724]
The SSH Remote Extension is fantastic, and the automated port forwarding is very convenient when we start test services or live documentation servers.

Unfortunately our integration tests start a lot of processes that listen to ephemeral ports (ie. bind to 0), and these also get picked up, resulting in a constant stream of rather distracting popups while the tests are run. If the auto-forward could be configured to ignore ephemeral ports, either explicitly or by default, we wouldn't have to turn the feature off, and it'd be really nice.

With that said, this is also perhaps a bit of a niche use case, most remote users probably do not have tests that start dozens of services on ephemeral ports.

**Comment by alexr00** [comment]
We are going to add a way for you to configure this: https://github.com/microsoft/vscode-remote-release/issues/4046

**Comment by achamayou** [comment]
@alexr00 that's awesome, thank you! Sorry I looked at the wrong repo and filed a duplicate.
