### ISSUE TITLE
jsconfig.json does not support jsx=reaxt-jsx

### ISSUE THREAD

**Issue by mstssk** [microsoft/vscode#112710]
- VSCode Version: 1.52.1
- OS Version: macOS 10.15.7, (Darwin x64 19.6.0)

Steps to Reproduce:

1. Put `jsonfig.json` in any dirrectory with bellow content:
```json
{
  "compilerOptions": {
    "jsx": "react-jsx"
  }
}
```
2. Open `jsonfig.json`.
3. VS Code shows bellow warning:

> When down-level compiling, specify JSX code generation: 'preserve', 'react', or 'react-native'. Requires TypeScript version 2.2 or later.
> Value is not accepted. Valid values: "preserve", "react", "react-native".(1)

![vscode_jsconfig-json_react-jsx](https://user-images.githubusercontent.com/500072/102460582-8ec6f480-408a-11eb-9a85-9b5cc7f1cd1d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Fixed by https://github.com/SchemaStore/schemastore/pull/1410
