### ISSUE TITLE
The app logo is not decent

### ISSUE THREAD

**Issue by PhamBaTho** [Microsoft/vscode#11274]
- VSCode Version: 1.4.0
- OS Version: 10.11.6

Steps to Reproduce:
1. The width of app logo should be relevant to other apps (now it looks a little bit wider, I know actually it fits in square) 
2. The white color in the twist and the border should be transparent or other colors
3. Just a small recommendation, why don't we redesign a separate icon for VSCode, not the same as VS. Thanks.

**Comment by gandaldf** [comment]
I replaced mine with this one:
https://dribbble.com/shots/3168520-Visual-Studio-Code-Icon-Replacement
It looks better on OSX!

**Comment by chrisdias** [comment]
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607
