### ISSUE TITLE
Notebook cell placeholder text should be updated for Markdown cells

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#112772]
![image](https://user-images.githubusercontent.com/35271042/102541506-5c56d080-4065-11eb-9692-855689ed8951.png)

Something like `Escape to stop editing` (like we have on the checkmark) or `Ctrl + Enter to finish editing`. I realize that both commands do the same thing, so we should make sure that all title tooltips are consistent.

**Comment by jilljac** [comment]
One of the engineers from the AZNB team suggested "Esc to preview" as an alternative string for this case. Just an idea :)

**Comment by roblourens** [comment]
Want to do this along with the cell status bar API which is going to April https://github.com/microsoft/vscode/issues/105809

**Comment by roblourens** [comment]
What if we use the formatting from the keybindings editor/the watermark tip when no editors are open? Like

![image](https://user-images.githubusercontent.com/323878/114952229-b5aff000-9e0a-11eb-949f-1a8243b5dc62.png)

**Comment by roblourens** [comment]
Will just try this for now
![image](https://user-images.githubusercontent.com/323878/114952519-4686cb80-9e0b-11eb-853f-57d12076b4ad.png)
![image](https://user-images.githubusercontent.com/323878/114952528-4ab2e900-9e0b-11eb-880c-5d56d9ca8698.png)

**Comment by roblourens** [comment]
Actually going with 
![image](https://user-images.githubusercontent.com/323878/114953072-74b8db00-9e0c-11eb-8834-04cd11c5e283.png)

**Comment by roblourens** [comment]
Let's try this and reopen if we want to tweak more

a7c67442b97a573f99cdda74bad86f8ac199fc4a
