### ISSUE TITLE
Starting vscode for the first time after a restart causes "Resolving Shell Environment is Slow"

### ISSUE THREAD

**Issue by mapringg** [microsoft/vscode#112753]
- VSCode Version: 1.53.0-insider
- OS Version: macOS 11.1

Steps to Reproduce:

I'm running this on the M1 MacBook air with these settings in my .zshrc:
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
export ZSH="/Users/mapring/.oh-my-zsh"
ZSH_THEME="robbyrussell"
DISABLE_AUTO_TITLE="true"
export NVM_LAZY_LOAD=true
plugins=(zsh-nvm yarn z zsh-autosuggestions git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
alias ibrew='arch -x86_64 /usr/local/bin/brew'
alias code='code-insiders'

1. Restart MacBook
2. Opening vscode should trigger the error "Resolving Shell Environment is Slow"

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
See https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning

And https://github.com/microsoft/vscode/issues/108804 plans to resolve this.
