### ISSUE TITLE
Make it possible to configure DENO_DIR in WS settings

### ISSUE THREAD

**Issue by Tzahile** [microsoft/vscode#112758]
Hi guys!

I'm working on a project written in [deno](https://deno.land/). I saved it as a Workspace.
Deno has an environment variable `DENO_DIR` to tell where all the cache goes.
I configured `DENO_DIR` to be in the project's folder.

The problem is that everytime I exit my WS, the environment variables get cleaned - so next time I open the WS, `DENO_DIR` is set to it's default location (*AppData* folder in windows..).

It would be great if I can set `DENO_DIR` in the WS settings (just like how I set `"deno.unstable": true` for instance)

**Comment by mjbvz** [comment]
Please file this feature request against the Deno extension
