### ISSUE TITLE
Double click a line in search editor to show file doesnt work for UNC network path

### ISSUE THREAD

**Issue by Ryan-Shanks** [microsoft/vscode#112775]
- VSCode Version: 1.51.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1.Create a test file on a UNC share, ie \\\\server\share\test.txt and put some text in it
2.Open the file in VSCode (dont open folder or in a workspace)
3.In settings, set your search editor double click behavior to goToLocation
4.Open a search editor and search for some text in your file so that it has matching lines
5.Double click one of the matching lines so that it should take you to that line in the file
6.You should see a message popup at the bottom right like "unable to open 'test.txt': Unable to read file 'vscode-userdata://server/share/test.txt' (Error: The "path" argument must be of type string. Received type undefined).
7.You remain in the search editor instead of being moved to the file

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Thanks for reporting, can you share what the text of the search editor in this case is?

**Comment by Ryan-Shanks** [comment]
> Thanks for reporting, can you share what the text of the search editor in this case is?

Hi,

The text of the file was Hello World and in the search editor I searched for he. Attached a screenshot
![VSCode bug](https://user-images.githubusercontent.com/10743310/102551648-d733e180-408d-11eb-9928-474316ad7b9a.png)

I covered the share names, in the file and the error, they match except that the ones in the error use / instead of \\

**Comment by JacksonKearl** [comment]
Is it possible you don't have a `HOME` environment variable set? I believe the culprit is here, https://github.com/microsoft/vscode/blob/49d1396aeb154bd57789330799dfa59c81469f89/extensions/search-result/src/extension.ts#L134
Which is a bit of a hack in which I expected desktop users to always have `HOME` defined (the other case is related to running in a browser).

**Comment by Ryan-Shanks** [comment]
Hi Jackson,

No, `HOME ` was not set, however if I set it to `C:\` it opens the file on double click as expected.

I checked 2 other Windows 10 computers that are less customized and none had `HOME `set, however they all have `HOMEPATH`.

Thanks,
Ryan

**Comment by JacksonKearl** [comment]
That's helpful, thanks. I'm going to change the condition to HOME or HOMEPATH for now, in the future some other changes are needed to remove the need for that condition entirely.

**Comment by Ryan-Shanks** [comment]
Thank you

**Comment by Ryan-Shanks** [comment]
I downloaded the insider build and tested with a file on a UNC path, it works correctly.
