### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by davidfifth** [microsoft/vscode#112744]
Issue Type: <b>Bug</b>

For the past couple of days, when I use VSCode on my monitor, it flickers. It does not continue to do this when I move the window to my laptop's screen. I have only seen VSCode do this to my monitor, not any other apps. I haven't figured out a general pattern that reproduces this problem, because it happens a lot. But a specific instance it usually happens with is:
using parentheses in a python script - flickering starts when I initiate the parentheses and stops when I complete the parentheses. I tried disabling extensions and it still happened without them enabled.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.46GB free)|
|Process Argv|--crash-reporter-id 4f350809-3c49-472e-86f0-1f7856ee23bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by jrieken** [comment]
Can you describe what flickering means? Is that the whole window? Only colours in the editor text?

**Comment by davidfifth** [comment]
The whole screen, including taskbar, flickers between brightness variations. However, I discovered it does the same thing on VSCode for my linux VM, so it must be something with my monitor :/

**Comment by davidfifth** [comment]
It's just strange how it only does it with VSCode specifically

**Comment by deepak1556** [comment]
Do you see the issue with https://code.visualstudio.com/insiders ?

**Comment by davidfifth** [comment]
I don't have that. I think it's something on my end, though, so I'll close this thread. It was lazy of me to post before thoroughly troubleshooting my end, I apologize! Thanks for the help though guys :)
