### ISSUE TITLE
Dropdown buttons should include the main action as well

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112735]
I think when you have a button with a dropdown, the menu should include the default action as first entry:

![image](https://user-images.githubusercontent.com/900690/102488316-28cb7480-406c-11eb-9cfe-9ccebbc70cca.png)

![image](https://user-images.githubusercontent.com/900690/102488325-2cf79200-406c-11eb-9892-94862c1e7231.png)

**Comment by sandy081** [comment]
Added primary action to dropdown. But in notifications, dropdown is getting shown on top of the button

<img width="476" alt="image" src="https://user-images.githubusercontent.com/10746682/103680963-2ed7b580-4f87-11eb-8613-c6f5ae54b2c3.png">

@sbatten can this be fixable?
