### ISSUE TITLE
Language server died more than 5 times and will not be restarted

### ISSUE THREAD

**Issue by surajmandalcell** [microsoft/vscode#112702]
Issue Type: <b>Bug</b>

Language server died out of nowhere, nothing out of ordinary.

VS Code version: Code - Insiders 1.52.0-insider (0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d, 2020-11-26T07:22:59.162Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|. --crash-reporter-id 38215a3a-9205-4c54-909f-baacb41c5564|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-pick|ada|0.6.2
aws-toolkit-vscode|ama|1.17.0
ng-template|Ang|0.1100.2
language-hugo-vscode|bud|1.2.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
coddx-alpha|cod|0.2.28
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.17.1
flutter|Dar|3.17.0
vscode-eslint|dba|2.1.14
vscode-dash|dee|2.4.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.0.0
css-flexbox-cheatsheet|dzh|3.2.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
vscode-great-icons|emm|2.1.62
prettier-vscode|esb|5.8.0
flow-for-vscode|flo|1.5.0
flutter-mobx|Flu|0.0.6
auto-rename-tag|for|0.1.5
flutter-stylizer|gml|0.0.16
todo-tree|Gru|0.0.192
rest-client|hum|0.24.4
discord-vscode|icr|4.0.0
search-node-modules|jas|1.3.0
react-vscode-extension-pack|jaw|0.4.0
pubspec-assist|jer|2.2.1
Angular2|joh|11.0.0
vscode-styled-components|jpo|1.4.1
firebase-explorer|jsa|0.3.3
vsc-python-indent|Kev|1.12.0
vscode-dashboard|kru|2.3.1
graphql-for-vscode|kum|1.15.3
vscode-fix-checksums|leh|1.1.0
node-module-intellisense|lei|1.5.0
dart-import|lua|0.3.1
flutter-tree|mar|1.0.0
vscode-scss|mrm|0.9.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-typescript-next|ms-|4.2.20201211
vscode-typescript-tslint-plugin|ms-|1.3.2
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
awesome-flutter-snippets|Nas|2.0.4
firebase-firestore-snippets|Pet|0.0.8
ngrok-for-vscode|phi|1.7.0
material-icon-theme|PKi|4.4.0
heroku-command|pko|0.0.8
remove-comments|pli|1.2.2
typescript-hero|rbb|3.0.0
ruby|reb|0.27.0
java|red|0.72.0
vscode-yaml|red|0.13.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.13
move-ts|str|1.12.0
sass-indented|syl|1.8.13
serverless-ide-vscode|Thr|0.5.28
vsfire|tob|1.4.1
lorem-ipsum|Tyr|1.2.0
errorlens|use|3.2.4
transpose|v4r|0.0.5
vscode-icons|vsc|11.0.0
vscode-ruby|win|0.27.0
vscode-import-cost|wix|2.13.0
JavaScriptSnippets|xab|1.8.0

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the new bisect command to find out if one of your 76 extensions is causing the issue.

**Comment by surajmandalcell** [comment]
No idea what broke, and since I did not investigate this further when it happened I'm closing this issue. Will try this if it happens again.
