### ISSUE TITLE
The height of the code smart hint is only one line

### ISSUE THREAD

**Issue by hobeas** [microsoft/vscode#112709]
Issue Type: <b>Bug</b>

1. Type "set", a prompt will appear.
2. The height of this prompt is only one line.

![Screenshot](https://user-images.githubusercontent.com/41267951/102459491-a00b0380-4080-11eb-9ac1-081a8ff4e7c2.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id a4dfe931-70b3-4b59-8dac-6c4620b85c7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.52.2

</details>

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206

**Comment by hobeas** [comment]
> See [#110554 (comment)](https://github.com/microsoft/vscode/issues/110554#issuecomment-726624206)

Works for me, thanks!

**Comment by jrieken** [comment]
@hobeas Any clue how you got into this state? Did you resize the widget by any chance?

**Comment by hobeas** [comment]
> @hobeas Any clue how you got into this state? Did you resize the widget by any chance?

I haven't resized the widget. Even I haven't opened the settings for a long time.
This state appeared about last week. I guess it was caused after I updated v1.52.0.
Today I updated the new version v1.52.1 and saw that the problem still exists, so I submitted this issue.

**Comment by jrieken** [comment]
ok, closing as duplicate.
