### ISSUE TITLE
Setting colorscheme and opening vscode for the first time triggers a white editor

### ISSUE THREAD

**Issue by mapringg** [microsoft/vscode#112752]
- VSCode Version: 1.53.0-insider
- OS Version: macOS 11.1 

Steps to Reproduce:

1. Set any color scheme
2. Quit out of vscode
3. Opening vscode should trigger a white editor for a split second

Does this issue occur when all extensions are disabled?: Yes

**Comment by mapringg** [comment]
I'm still experiencing this bug in the newest release.

**Comment by aeschli** [comment]
duplicate of  #112816
