### ISSUE TITLE
VSCode w/ WSL Prevents folder from being moved/renamed despite all files being closed

### ISSUE THREAD

**Issue by apham-sy** [microsoft/vscode#112764]
- VSCode Version:1 .
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open VSCode w/ WSL
2. Open a file in a subdirectory. E.g. `/tmp/testfolder/file.py`
3. Close that file tab (while keeping vscode still open)
4. Attempt to move that folder through windows explorer or vscode
5. You should get 
```Error: EACCES: permission denied, rename '/tmp/testfolder' -> '/newlocation/testfolder/'```
If you attempt to move with windows you will get 
![image](https://user-images.githubusercontent.com/66134735/102535368-beb3cf00-406d-11eb-9208-872b3df9591a.png)

It looks like vscode holds onto the lock (if this is correct) of the parent folder of a modified file despite it being closed in WSL. **This is not a problem when not using Remote - WSL.**

The problem occurs when you rename the folder as well.

Maybe related to https://github.com/microsoft/WSL/issues/1529

Does this issue occur when all extensions are disabled?: Yes/No
Remote - WSL is required to open the remote window.

**Comment by isidorn** [comment]
Assigning first to @aeschli because it is WSL related, and Explorer is not doing anything special here

**Comment by aeschli** [comment]
Yes, this is a known WSL1 issue. See https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace-in-wsl-1.
