### ISSUE TITLE
When the local extension host crashes, VS Code disconnects from remote server

### ISSUE THREAD

**Issue by CyanBook** [microsoft/vscode#112714]
Issue Type: <b>Bug</b>

vscode Remote-SSH extensionrandomly disconnects from my server.
It may vary from a couple of minutes to a couple of hours. Sometimes it doesn't at all. I already tried to reload and reinstall VSCode Server, but nothing happened. Please help me

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (8.68GB free)|
|Process Argv|--crash-reporter-id d4f79334-6cde-4f34-9a3e-b71cdb9bff7d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Hetzner|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|AMD EPYC Processor (with IBPB) (4 x 2495)|
|Memory (System)|7.59GB (0.20GB free)|
|VM|0%|
</details>

**Comment by CyanBook** [comment]
> Having seen lists of crashing extensions for a while, please try to disable/uninstall `softwaredotcom.music-time` and `softwaredotcom.swdc-vscode`. From our telemetry, users that have these extensions installed can see anywhere between 4x to 6 x times more crashes than users without them.

With these extensions uninstall, I've seen the number of crashes going down significantly. The problem isn't fixed, though.

**Comment by alexdima** [comment]
@CyanBook Does this still reproduce for you?

**Comment by CyanBook** [comment]
Haven't used Remote VSCode in a while, but maybe someone else did.

**Comment by alexdima** [comment]
Thank you for your prompt reply. In the past 2 years, we have pushed a lot of improvements in the area of remote. I will optimistically close this for now and we can reopen it if it reproduces or create new issues as needed. Thank you!
