### ISSUE TITLE
Consistent keyboard treatment of side panel and bottom pane

### ISSUE THREAD

**Issue by ChrisKeefe** [microsoft/vscode#112781]
Side panel feature shortcuts (e.g. ctrl+shift+E for Explorer) should hide the sidebar when pressed while the related section (e.g. Explorer) is focused. This would align the sidebar with the bottom panel behavior. (Ctrl + ` minimizes the bottom panel when the terminal is focused). 

As noted in #68183, sidebar and bottom panel behavior is inconsistent. Currently, it is possible to open and close the bottom panel with the same keyboard shortcut, but _only possible to open the sidebar_ with e.g. the Explorer shortcut. Implementing this UI fix will make the keyboard interface more consistent and intuitive across sidebar and bottom panel, and will alleviate the need for users to learn an additional shortcut to close the sidebar.

**Comment by ChrisKeefe** [comment]
Good try, dupe detector, but your princess is in another castle! Neither of these issues is related to this feature request.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/85785#issuecomment-560317290

**Comment by isidorn** [comment]
Fair requrest, but we will probably not change this.
Keeping this open as a fair feature request but assigning to backlog as we have no plans to tackle

**Comment by ChrisKeefe** [comment]
Thanks for the feedback, gentlemen! 

As a side note, the Vim (`vscodevim.vim`) add-on masks `Ctrl-B` by default, making manual configuration necessary for Vim users who want to close the sidebar in a keyboard-centric way. Given the popularity of that add-on (over 2M downloads), and  that user group's general interest in keyboard-oriented computing, maybe this is another little factor in favor of toggle over focus.
