### ISSUE TITLE
Use a separate column to show the value of a variable or expression

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1127]
Add a separate column to show the value of a variable or expression to improve readability and to improve the experience of scanning a list of variables or values to find the required one.

When appropriate, we should also consider using another column to show the type of the variable or expression.

For example, this screenshot shows one extra column for the value:
![locals](https://cloud.githubusercontent.com/assets/1704059/11683123/c208816e-9e60-11e5-866d-6c33b3d22021.png)

**Comment by isidorn** [comment]
:-1:  IMHO does not look good and does not fix a real problem. When using us and the chrome debugger i never have a problem of distinguishing between name and value - though that might be just me.

@weinand @bpasero opinions?

**Comment by weinand** [comment]
Tables and an additional type column waste space and make only sense if we have horizontal space at our disposal. Chrome dev tools do not use this approach either. As a user, I don't see pressure for this.

**Comment by stevencl** [comment]
I agree, this is only for horizontal layout. In vertical layout we are more constrained for space and this would not make as much sense. I also agree that there isn't a huge problem being solved with this, but sometimes we make small modifications to the UI in order to make small improvements to the UX. 

It's possible though that as more debug adapters are written that we might need to show more information such as type. If so, I think we should reconsider this but I will close this for now.

**Comment by weinand** [comment]
@stevencl the mono debug adapter (and probably other adapters as well) show already the type by  combining the type into the name that is returned from the debug adapter. One reason why we do not separate type from name in the VSC debug protocol is that in some languages the type appears on both sides of the name, e.g. in C you have constructs like this: "char *name[]". Another reason is to keep things simple.
