### ISSUE TITLE
Filenames containing braces render the editor unusable forever.

### ISSUE THREAD

**Issue by RafaGago** [microsoft/vscode#112726]
- VSCode Version: 1.52.1 ea3859d4ba2f3e577a159bc91e3074c5d85c0523 x64
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. $ code {badname}

Does this issue occur when all extensions are disabled?: Yes

After that the file can never be closed. The application doesn't even exit. It has to be killed.

As the session is remembered, starting the application again doesn't fix anything.

Grepping for the files I had open on my home directory gives no matches, so they must be stored on some binary blob.

**Comment by RafaGago** [comment]
Workaround. 

On "~/.config/Code/User/settings.json", adding "window.restoreWindows": "none" still remembered the windows but it did let me close them. Back to normal after deliting that line from "settings.json" again.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
