### ISSUE TITLE
Tab decorations need to update scrollbar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#112799]
It looks like the new decorations in tabs can cause tabs to grow in size. Since this can happen async, the scrollbar can get out of sync because the sizes change.

in the gif below I demonstrate the issue with a fake decoration that has lots of text:

![recording](https://user-images.githubusercontent.com/900690/102593334-06416600-4115-11eb-9ec1-9ce38c433f17.gif)

I think this is similar to the existing [`updateEditorLabel`](https://github.com/microsoft/vscode/blob/b8ddffe7b413b52fd9bae16a2e4245a7136a5ff8/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L515-L515) that eventually will cause a `layout` to be performed. However I think we can skip the part that recomputes editor labels and redraws tabs, a `layout` should be sufficient.

**Comment by jrieken** [comment]
> Since this can happen async, the scrollbar can get out of sync because the sizes change.

idk - it shouldn't be async but more like driven by events. @bpasero where is the code that know when toggling icons? It should be more like that, e.g the label changes dimensions and the tabs must react

**Comment by bpasero** [comment]
@jrieken icons are easier because that is just an options change that we detect here:

https://github.com/microsoft/vscode/blob/b8ddffe7b413b52fd9bae16a2e4245a7136a5ff8/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L561-L561

**Comment by bpasero** [comment]
> idk - it shouldn't be async but more like driven by events

Yeah I mean a decoration for a compilation error can appear after I had opened the editor simply because the compiler runs in the background.

**Comment by jrieken** [comment]
So, what do you think: Should `ResourceLabels` (which already listens to decoration changes) fire an event or should the tabTitleControl listen to decoration changes (IDecorationService#onDidChange) and then redraw/relayout?

**Comment by jrieken** [comment]
> @jrieken icons are easier because that is just an options change that we detect here:

Would my case be just like untitled tab names which update as I type in the editor? Is that done with a generic solution or something specific to untitled?

**Comment by bpasero** [comment]
I like the idea of registering 1 listener to `ResourceLabels` and then triggering this flow whenever decorations change. 

Updating of untitled editors is done with an event too, editors can signal when their labels change and we simply forward this event to the tabs:

https://github.com/microsoft/vscode/blob/affd21e65ac41360704b573a4ca3b90107fd9ee8/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L666-L673

But I think a solution that is local to tabs only and not generic for no-tabs & tabs is sufficient because imho the no-tab solution can deal with decorations changing without having to relayout or redraw.

**Comment by jrieken** [comment]
I have pushed a change that uses the `onDidRender` event that resource labels already emit. I do believe that dynamic titles of untitled editor would also be covered by that

**Comment by bpasero** [comment]
I will see if I can maybe get to a solution that is a bit more performant. I am worried that triggering layout for each tab label change results in a lot of work.

**Comment by bpasero** [comment]
@jrieken please see https://github.com/microsoft/vscode/commit/b069dbe0aeb72786f81a449e6a53de4926aef952, there is now 1 listener for the entire group of labels that only fires when the label updates as a result of decorations changing. This still might cause a layout call that is not needed because a decoration change might not cause the tab size to change, but I am not sure how to better figure that out.
