### ISSUE TITLE
Timed out waiting for debuggee to spawn

### ISSUE THREAD

**Issue by bernardo-suez** [microsoft/vscode#112776]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.016299

Steps to Reproduce:

1. Run my code (proprietary information, so I can't share it)
2. About 12 seconds into the calculations the alert box comes up with the message "Timed out waiting for debuggee to spawn"

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
If this issue doesn't occur when all extensions are disabled, then it is an extension problem.

**Comment by bernardo-suez** [comment]
Sorry I misread the question about the extensions. I disabled all but had to keep the Microsoft Python extension on to use the debugger and reproduce the issue. I'll report the issue on the extension's page.
