### ISSUE TITLE
No code action or quick fix available on Java

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [microsoft/vscode#112795]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Enterprise LTSC 1809 17763.1577
- Client OS Version: Windows 10 Professional 20H2 19042.685

Steps to Reproduce:

1. Connect to SSH based server
2. Install Java extension pack "vscjava.vscode-java-pack"
3. Open a folder and a java file
4. Remove one of the import line
5. See "Predicate cannot be resolved to a type" or something with a type name
6. "Ctrl+." to trigger quick fix
7. No quick fix available

Does this issue occur when all extensions are disabled?: Yes/No
No

-- without extensions, remote via SSH isn't available.

**Comment by jrieken** [comment]
\extJava
