### ISSUE TITLE
vs-code creates a second file when called by less

### ISSUE THREAD

**Issue by ppanhoto78** [microsoft/vscode#112806]
`less` invokes the editor with this syntax: `$EDITOR +n target-file`. When EDITOR is *code*, this `+n` is interpreted as a separate file. This new "file" is always opened as if it was changed already. Closing it calls a dialog to save this file.

- VSCode Version: 1.52.1
- OS Version: Fedora 32

Steps to Reproduce:

1. export EDITOR=code VISUAL=code
2. less some file
3. press v

Does this issue occur when all extensions are disabled?: Yes/No
This is not related to extensions

**Comment by bpasero** [comment]
Possibly report this against `less` to not add this `+n`? What is VSCode to fix here?

**Comment by ppanhoto78** [comment]
"n" in "+n" is actually the line number where the file should open.
This appears to be a standard syntax among unix editors. See examples below.

vim -h displays:
  +                    Start at end of file
  +<lnum>              Start at line <lnum>

nano -h displays:
To place the cursor on a specific line of a file, put the line number with
a '+' before the filename.  The column number can be added after a comma.
When a filename is '-', nano reads data from standard input.

emacs --help displays:
FILE                    visit FILE using find-file
+LINE                   go to line LINE in next FILE
+LINE:COLUMN            go to line LINE, column COLUMN, in next FILE

micro -h displays:
[FILE]:LINE:COL (if the `parsecursor` option is enabled)
+LINE:COL
       Specify a line and column to start the cursor at when opening a
buffer

Hope this helps,

Paulo.

**Comment by bpasero** [comment]
In order to open a file on a specific line/col with VSCode, you have to add `-g` (or `--goto`). 

![image](https://user-images.githubusercontent.com/900690/102747841-4f85f580-4361-11eb-9ccc-15956a198c47.png)
