### ISSUE TITLE
vs code deletes my local files on sync up with git

### ISSUE THREAD

**Issue by charlesanil** [microsoft/vscode#112839]
i am using vs code 1.52.

I clicked on the sync button at the bottom to get the latest check-outs from git before checking in my file & folder.

Unfortunately, it deleted my local files & folder. I cant see the files in the recycle bin. Lost about 2 weeks of code. any way i recover these deleted files ??

Is there a way to get this back? No luck on google! :-(

Thanks,

**Comment by joaomoreno** [comment]
> I clicked on the sync button at the bottom to get the latest check-outs from git before checking in my file & folder.

The sync button won't ever delete your code. What might delete your code is the `Discard Changes` action, which warns you about it. Did you run that maybe?
