### ISSUE TITLE
my VSCode lags sometimes, it never happened earlier before I installed macOS Big Sur 11.1

### ISSUE THREAD

**Issue by yash19pro** [microsoft/vscode#112820]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. there are no steps as such but I have some extensions installed, I am not sure it is related to that. they are C/C++, ESLint, GitLens, Jupyter, Live Server, Python, Visual Studio Intellisense, Vim and vscode-icons. all to latest version at the time when I am posting this issue

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
