### ISSUE TITLE
CSS/SASS validation settings are being ignored 

### ISSUE THREAD

**Issue by tbhaxor** [microsoft/vscode#112809]
- VSCode Version: 1.52.1
- OS Version: Manjaro 20.2

Steps to Reproduce:

1. Setup a vuejs project woth css-preprocessors
2. Create SFC and add scss styles
3. Use the following settings

```json
{
  "editor.quickSuggestions": {
    "strings": true
  },
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "vetur.format.enable": false,
  "css.validate": false,
  "less.validate": false,
  "scss.validate": false
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
> Create SFC and add scss styles

What does that mean exactly? I assume you create a file. What's the file name? What language?

**Comment by tbhaxor** [comment]
> What does that mean exactly?

SFC in vuejs means Single File Component, which is writing template, javascript and css styles for a particular component in one single file. For example, see this file (from vuejs documentation)


![](https://vuejs.org/images/vue-component.png)

**Comment by tbhaxor** [comment]
@aeschli any updates?

**Comment by tbhaxor** [comment]
@aeschli Any update on this??

**Comment by aeschli** [comment]
Ok, so this is a vue file. You have to file the request against the vue extension. If you use vetur, that's the repo: https://github.com/vuejs/vetur
