### ISSUE TITLE
Conflicts of "tab" key between autocomplete in shell and switching focused contents.

### ISSUE THREAD

**Issue by liberix** [microsoft/vscode#112841]
Issue Type: <b>Bug</b>

I want to use "tab" to accomplish autocomplete in the terminal. But every time I press "tab", vscode always switched focus to othed tabs (from side bar to bottom and to tabs in the editor).

VS Code version: Code - OSS 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-12T10:54:25.653Z)
OS version: Linux x64 5.8.18-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4064)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.45GB (5.95GB free)|
|Process Argv|--no-sandbox --unity-launch /home/duk3m0n/code/games101/pa0/main.cpp --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.5.3
cmake|twx|0.0.17

</details>

**Comment by meganrogge** [comment]
Have you tried setting `terminal.integrated.sendKeybindingsToShell`: true?
