### ISSUE TITLE
Horizontal Scroll of MX master 3

### ISSUE THREAD

**Issue by javb93** [microsoft/vscode#112827]
Issue Type: <b>Feature Request</b>

Have an MX master 3 mouse from logitech, configured VS code on the application for horizontal scroll, but is not working, when I open VS code, I can scroll a little but then it stops and doesn't register

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by javb93** [comment]
Found that this was already submitted on 107848, how do I label it as duplicate?

**Comment by alexdima** [comment]
You can simply close the issue. Duplicate of #84136
