### ISSUE TITLE
Gives me an error on NPM Start

### ISSUE THREAD

**Issue by Jeskalana** [microsoft/vscode#112849]
Issue Type: <b>Bug</b>

It gives me an error, says"enoent Enoent: no such file or disk." on NPM Start.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (1.07GB free)|
|Process Argv|--crash-reporter-id b82a7703-3cb6-43eb-bdb1-6f679a147066|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
xd|ado|1.1.2
add-reference|adr|1.0.2
asp-net-core-snippet-pack|adr|1.51.0
asp-net-core-switcher|adr|2.0.2
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
user-secrets|adr|2.0.1
vscode-javascript-snippet-pack|aka|0.1.6
code-gnu-global|aus|0.2.2
git-easy|bib|1.11.0
vscode-standardjs-snippets|cap|0.8.15
vscode-standardjs|che|1.4.0
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.38.0
vscode-dotnet-adapter|der|1.4.3
phptools-vscode|DEV|1.1.5620
netcore-extension-pack|dog|1.4.0
netcore-snippets|dog|3.15.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.0
git-cheatsheet|dzh|1.4.1
gitlens|eam|11.0.6
vscode-html-css|ecm|1.2.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
git-commits|Exe|3.7.14
php-intellisense|fel|2.3.14
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.4
vscode-yarn|gam|1.7.1
php-awesome-snippets|hak|1.1.3
vscode-test-explorer|hbe|2.19.3
vscode-git-tags|how|1.4.4
csharpextensions|jch|1.3.1
xd-theme|jef|0.1.150
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.20
vscode-github|Kni|0.30.4
git-indicators|lam|2.1.2
git-graphy|mar|1.0.14
vscode-dotnet-essentials|mau|0.0.3
start-git-bash|McC|1.2.1
csharp|ms-|1.23.8
dotnet-interactive-vscode|ms-|1.0.160901
vscode-dotnet-runtime|ms-|1.0.0
vscode-edge-devtools|ms-|1.1.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
cpptools|ms-|1.1.3
js-atom-grammar|ms-|0.1.14
js-debug-nightly|ms-|2020.12.1517
vscode-typescript-next|ms-|4.2.20201211
gitpatch|par|0.2.1
vscode-versionlens|pfl|1.0.9
quicktype|qui|12.0.46
addlocalnetreferences|Raf|0.4.8
java|red|0.73.0
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
git-autoconfig|shy|0.0.2
git-prefix|srm|1.2.0
hyper-javascript-snippets|t7y|2.5.0
msbuild-project-tools|tin|0.3.10
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-todo-highlight|way|1.0.4
vscode-js-console-utils|wht|0.7.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0
vscode-proto3|zxh|0.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by mjbvz** [comment]
Without more evidence, this sounds like a general development question and not a VS Code issue
