### ISSUE TITLE
Port scanning executes even if auto forward ports is off

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#112843]
We have been seeing a bunch of remote issues where the remote extension host burns a lot of CPU. I think it is caused by our port scanning code, which executes even if the setting `"remote.autoForwardPorts"` is false. See https://github.com/microsoft/vscode/blob/768cd308c620936ccb79a94ae80cb6edf7d214ed/src/vs/workbench/api/node/extHostTunnelService.ts#L160-L171

Possible issues:
* https://github.com/microsoft/vscode/issues/112581 / https://github.com/redhat-developer/vscode-java/issues/1743
* https://github.com/microsoft/vscode-remote-release/issues/4205
* https://github.com/microsoft/vscode/issues/112466#issuecomment-744869515

Other:
* https://github.com/microsoft/vscode-remote-release/issues/4204
* https://github.com/microsoft/vscode-remote-release/issues/4201
* https://github.com/microsoft/vscode-remote-release/issues/4211
* https://github.com/microsoft/vscode-remote-release/issues/4186
* ? https://github.com/microsoft/vscode/issues/112457
* ? https://github.com/microsoft/vscode/issues/112367
* ? https://github.com/microsoft/vscode-remote-release/issues/4210
* ~~https://github.com/microsoft/vscode/issues/112797~~

**Comment by QwertyZW** [comment]
Maybe save the return value of `setInterval`and put a `clearInterval(poller)` before the return?

**Comment by alexdima** [comment]
I could reproduce some increased CPU usage of the remote extension host using the project linked to [here](https://github.com/redhat-developer/vscode-java/issues/1743#issuecomment-745087511) i.e. https://github.com/spring-projects/spring-petclinic

**Comment by alexr00** [comment]
In insiders, you can now temporarily disable the port scanning code by adding this line to your .bashrc file, then restarting the VS Code server on your remote:
`export VSCODE_DISABLE_PROC_READING=true`

**Comment by alexr00** [comment]
Once we have an insiders build I'll start commenting in each of the issues asking folks to try out the workaround in insiders.

**Comment by alexr00** [comment]
Keeping open for now so that the issue can be found more easily.

**Comment by alexr00** [comment]
Closing since the fix is available in insiders.

**Comment by connor4312** [comment]
Verified that cpu usage was reasonable when running the petclinic app

![](https://memes.peet.io/img/21-01-cc6eab6f-7a30-4c4a-9fee-f9769dc6edd8.png)
