### ISSUE TITLE
Extra characters appended when pasting text of certain size into Julia REPL running in VSCode

### ISSUE THREAD

**Issue by BioTurboNick** [microsoft/vscode#112831]
- VSCode Version: 1.52.1
- OS Version: Windows 10.0.21277

Steps to Reproduce:

1. Install Julia 1.5.3
2. Open Terminal inside VS Code
3. Navigate to and execute julia.exe to run Julia REPL
4. Paste "combinednormalizedmontecarlomeasurementsc" at prompt (right click, excluding quote marks)
5. Observe that the characters "01~" have been appended.

Does this issue occur when all extensions are disabled?: Yes

The issue varies with length of the string, as documented here: https://github.com/julia-vscode/julia-vscode/issues/1824

I'm reporting it here because this problem does not occur when the REPL is running inside a Windows Terminal window.

**Comment by meganrogge** [comment]
Here are the logs from pasting `combinednormalizedmontecarlomeasurementsc`:

```
xterm.js: sending data "[200~combinednormalizedmontecarlomeasurementsc[201~" (53) [27, 91, 50, 48, 48, 126, 99, 111, 109, 98, 105, 110, 101, 100, 110, 111, 114, 109, 97, 108, 105, 122, 101, 100, 109, 111, 110, 116, 101, 99, 97, 114, 108, 111, 109, 101, 97, 115, 117, 114, 101, 109, 101, 110, 116, 115, 99, 27, 91, 50, 48, 49, 126]
LogService.ts:62 xterm.js: parsing data c
LogService.ts:62 xterm.js: parsing data ombinednormalizedmontecarlomeasurementsc01~
```

**Comment by meganrogge** [comment]
happens for the same character counts even if I split the terminal / resize it

**Comment by Tyriar** [comment]
It looks like the Julia REPL is not handling bracketed paste mode correctly and sending it back to print `01~`. `\x1b[200~` and `\x1b[201~` wrap pasted text only when requested by the REPL, these are meant to be stripped out by Julia after accepting them.

**Comment by BioTurboNick** [comment]
Thanks all for looking into it. I'll forward this over.

**Comment by BioTurboNick** [comment]
@meganrogge Is the logging you did something I can enable locally? The extension dev isn't convinced it's something the extension is doing, and I'd like to be able to poke around at it.

Also, is bracketed paste mode something that is handled by Windows, or by VS Code and passed through to the extension and then to the REPL/terminal?

**Comment by Tyriar** [comment]
@BioTurboNick you can enable with the toggle escape sequence logging command, they then show up in devtool's console.

Bracketed paste mode is enabled by the shell process sending us `\x1b[?2004h`, we will then wrap any pasted text in `\x1b[200~` and `\x1b[201~`. I don't know how Julia's repl is built but it might be built upon something that handles bracketed paste mode, maybe incorrectly?

**Comment by BioTurboNick** [comment]
Thanks. The REPL when running in a normal Windows Terminal doesn't have the issue, which is what's odd.

Something that stands out to me: the logging shows bracketed data is being sent, but then it's being parsed into two chunks. Where is that happening? (maybe that's a downstream by-design side effect of the bug, but I just want to thoroughly understand what's happening).

Is the extension interposed into this process, and it should be stripping the brackets before the parse function is called using some hook?

Or are the brackets unexpected at the "sending data" stage, and the extension is supposed to, but isn't, stripping them out prior to that? Is there a hook it should be using?

**Comment by Tyriar** [comment]
@BioTurboNick WT doesn't support bracketed paste mode yet: https://github.com/microsoft/terminal/issues/395

> Something that stands out to me: the logging shows bracketed data is being sent, but then it's being parsed into two chunks.

That should be fine

> Is the extension interposed into this process

I don't think the extension has anything to do with this, it's just the repl executable.

**Comment by BioTurboNick** [comment]
@Tyriar sorry one more question to gauge my understanding

Is this what's happening?

1. Paste event triggered in xTerm, wraps content in brackets.
2. xTerm sends the data to STDIN
3. Julia REPL reads STDIN, processes it, then sends to STDOUT
4. xTerm reads STDOUT and displays text

**Comment by Tyriar** [comment]
Basically yeah, it's possible something funny is going on with conpty which is Windows' emulation layer if WT doesn't implements bracketed paste support. Hard to say exactly as I mainly only have experience programming on this side of the terminal.

**Comment by BioTurboNick** [comment]
Thanks. Okay. Just proving to myself I'm not crazy... Julia in WSL in WT vs. Julia in WSL in VSCode

![image](https://user-images.githubusercontent.com/1438610/143317138-861d54a2-d991-4d65-997c-8fa930aa66b4.png)
![image](https://user-images.githubusercontent.com/1438610/143317175-6ad09a0d-5cb6-431e-a3d2-64d555c19739.png)

(the tail of that last one shows stray end-bracket characters)

**Comment by BioTurboNick** [comment]
Out of curiosity, is there any way to interject some monitor of STDIN and STDOUT of the components here on Windows? Or to see which ones are hooked up to each other?

**Comment by BioTurboNick** [comment]
Okay, it definitely isn't Julia at fault here. This issue should be reopened or moved to the appropriate supporting project repository.

This is the result of pasting into a WSL terminal on Windows 10 in VSCode after enabling bracketed paste mode manually:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/1438610/143689258-060fdf17-7770-4da7-82a3-63aa621e14d1.png">
