### ISSUE TITLE
allow to copy file between workspaces on tab drag

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#112819]
currently we can copy file from one ws to another through a drag from sidebar but not when using a tab drag ex.

![demo](https://user-images.githubusercontent.com/7388088/102628113-e4b29f80-4151-11eb-9452-58e9e1fc2e83.gif)

**Comment by isidorn** [comment]
Fair feature request. I think this might have already been requested, but for now assinging to backlog.

fyi @bpasero

**Comment by bpasero** [comment]
I am not entirely convinced a file should be copied when dragging the editor.

**Comment by ctf0** [comment]
but its already doing that, u can even copy a file when tab is dragged to a folder on disk
