### ISSUE TITLE
Icons in open editors view

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11287]
Refs: #11130 

Steps to Reproduce:

1. Enable icon theme
2. Notice there are no icons in the open editors view. I find this strange, especially with the seti theme, as the users eyes might get used to a particular icon when finding a file, and that approach will not work in the open editors view

Opinions @bpasero?

**Comment by bpasero** [comment]
I think also the vscode-icons theme does not show them and it seems to be OK.

**Comment by isidorn** [comment]
Yes, but the vscode-icons shows the same icon for all file types so it would be just noise. But in the seti theme I feel like the icons would bring value in the open editors view

**Comment by bpasero** [comment]
If we do this we need to start adding settings so that a user can decide. We also might need this for tabs.

As far as I know, the vscode-icons extension does NOT show icons for "opened editors".

**Comment by robertohuertasm** [comment]
Hi @bpasero, @isidorn. vscode-icons does currently support tabs and "open editors" icons. I was under the impression, after talking with @aeschli by email that this was somehow on the roadmap. I fully understand that this is not going to be released by Sept 12th but I thought that it was more or less to be released by October.

I'm willing to avoid code injection but I would like to keep users with a similar functionality if possible.

**Comment by robertohuertasm** [comment]
@isidorn I think you're confusing vscode-icons with the new standard icons provided by the new icons extension point. Check out [this](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)

**Comment by bpasero** [comment]
This is in for September, closing.
