### ISSUE TITLE
希望增加文件拷贝功能

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#11280]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2. 希望增加文件拷贝功能，git在优化下。

**Comment by dbaeumer** [comment]
Automatic translation: Want to increase file copy function, git under optimization.

@rebornix can you help with the translation. I can't make much sense out of the automatic one.

**Comment by leaxoy** [comment]
Simple translate.
1. hope to add copy file(not only content) feature (Maybe when select a file, we can use cmd+c to copy whole file.)(The description a little blurry)
2. enhance git features and some optimization

**Comment by rebornix** [comment]
@dbaeumer he wants us to improve the git features and add support for file copying. But I don't see detailed requests and suggestions.

@cw19931024 请问可以提供更具体的需求吗，比如你在使用 git 的时候遇到了什么问题，你希望的文件拷贝功能是什么样的？
(I'm asking @cw19931024 if he can make it more specific that what kind of issues he ran into while using git and describe the file copy-paste feature request in more details)

**Comment by dbaeumer** [comment]
@rebornix thanks!

**Comment by joaomoreno** [comment]
Waiting on @cw19931024's updates.

**Comment by cw19931024** [comment]
额，我说的拷贝是指新增加文件进项目的时候能随手像ide一样能支持复制进去，这样其实更友好。

**Comment by joaomoreno** [comment]
Sorry, I can't understand this.

**Comment by rebornix** [comment]
@joaomoreno I understand every characters he wrote but not quite 100% sure I get he is saying, seems what he wants is 

1. Copy file in File Explorer 
2. Launch VS Code, navigate to File Explorer Viewlet
3. Run `Ctrl-V` to paste, then the file can be pasted in the folder.

It's somewhat similar to drag files from System's File Explorer to our File Explorer Viewlet.

**Comment by joaomoreno** [comment]
cc @bpasero

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/164

**Comment by cw19931024** [comment]
Sorry, my English sucks. But I really want to code can be getting better and better
