### ISSUE TITLE
DocumentLink doesnt persist when code is folded

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#112822]
```
Version: 1.53.0-insider
Commit: c927a8015b9e26bd454d6e293bb0384aa1975d06
Date: 2020-12-18T05:27:22.865Z
Electron: 11.0.5
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

1. have a extension/provider that creates document links [ex.](https://github.com/ctf0/laravel-goto-view/blob/master/src/providers/linkProvider.ts)
2. make sure document link is visible
3. fold the code block where the document link is active
4. link is gone

![ScreenFlow](https://user-images.githubusercontent.com/7388088/102629729-378d5680-4154-11eb-8b0f-77706cb76a3c.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
The problem is with the link provider implementation you have linked. The link provider implementation should not use the active editor and the current visible ranges for computation, it should compute links on the entire passed in document.

For example, this works fine in markdown:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/102659803-50106780-417a-11eb-9e9b-415405e08b35.gif)

**Comment by ctf0** [comment]
ok, bear with me.

going through the entire document is bad because
- it will take long to do so
- the editor will become sluggish until the operation is done
- with big files the editor will freeze

while using visible ranges is the most performant way i could think of and it shouldn't care of the fold because
- the link is added to a fixed range "line number doesnt change, nor the string length we add the link to"

so could u plz tell me "with a more in depth answer" on why using the visible ranges to add document link doesnt persist when we fold the code ?

**Comment by alexdima** [comment]
- The link provider is designed to return results for the entire document. This gives the best user experience, we can render at 60FPS a fast, scrolling editor which will not flicker when a link scrolls into the viewport.
- The editor will not become sluggish when you compute links on a separate process. You appear to be computing things on the extension host process. That is not a good idea, your code will block the event loop and make all other extensions sluggish. You can launch your own node process and do heavy lifting in a separate process. Please read about LSP on our website which can help you with some libraries and examples to get started building a language server.

**Comment by ctf0** [comment]
thank you for the clarification.
