### ISSUE TITLE
Emmet: support to exclude languages from emmet abbreviation

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11283]
With the new support to infer from the language's grammar's scope ('text.html.markdown') whether emmet should be enabled for a file, emmet is now enabled for more languages, e.g., in markdown files.

There should be support to exclude a list of languages from the emmet abbreviations so that users can get back the old behaviour without having to fully disable emmet.

@mrmlnc what do you think?

**Comment by mrmlnc** [comment]
@egamma, I fully agree with you. For example, this behavior would be useful for PHP developers (#7913).

I think that such a possibility should work only with commands when you press Tab.

**Comment by egamma** [comment]
@mrmlnc 

>I think that such a possibility should work only with commands when you press Tab.

I agree, but this would require to introduce a separate in addition to ExpandAbbreviation e.g. ExpandAbbreviationOnTab to distinguish this case, An action should not know how it was invoked. This would mean that two actions show up in the Command Palette which is ugly. So let's see what feedback we get first.
