### ISSUE TITLE
Handle vscode-icons extension in 1.5 with icons support

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11288]
We should coordinate with the author of vscode-icons how to transition to the official icon extension in VS Code 1.5.

@aeschli @egamma we should discuss here

**Comment by bpasero** [comment]
My idea:
* vscode-icons pushes an update early enough before we ship 1.5
* this update bundles icons using the official way of the new file icons extension point
* this update includes a check for the `vscode.version` being 1.5.0 or newer (using semver)
* if we run in 1.5.0 or newer, disable the `runAutoInstall` call and show a message to the user for any of the contributed commands (e.g. Enable Icons)
* the message includes instructions for how to enable the icons (File > Preferences > File Icon Theme)

**Comment by robertohuertasm** [comment]
@bpasero I just released v2.0.1 with official support by default [#286](https://github.com/robertohuertasm/vscode-icons/pull/286).
