### ISSUE TITLE
Rename folder screen glitch

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11286]
Refs: #11130

- VSCode Version: insiders
- OS Version: mac, linux

Steps to Reproduce:

1. Rename a folder
2. Notice blue screen glitch

![screen shot 2016-08-31 at 09 45 31](https://cloud.githubusercontent.com/assets/1926584/18120429/cb629508-6f5f-11e6-9082-9fc8a441ec4e.png)

**Comment by bpasero** [comment]
This seems to be fixed via https://github.com/Microsoft/vscode/issues/9170
