### ISSUE TITLE
Changing file icon theme to none applies it to only one VSCode window

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11285]
Refs: #11130

- VSCode Version: insider
- OS Version: linux

Steps to Reproduce:

1. Open two vscode windows, enable seti icon theme
2. In one of those windows set icon theme to 'none'
3. Notice that this none theme only gets applied to that window, not the other one. Also notice that setting icon theme to anything other than 'none' nicely applies it to both windows

**Comment by aeschli** [comment]
the problem seems to be in the windowService. onBroadcast is not called if the payload is empty.
		windowService.onBroadcast(e => {
			if (e.channel === ICON_THEME_CHANNEL && typeof e.payload === 'string') {
				this.setFileIconTheme(e.payload, false);
			}
		});
