### ISSUE TITLE
Crash: vscode crashes after attempting to delete firebase/functions file from vscode

### ISSUE THREAD

**Issue by jeffzy15** [microsoft/vscode#112802]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. run `firebase init functions`
2. right-click on the functions directory and click delete
3. vscode crashes and is not responsive to scrolling and keyboard input
4. but the mouse still works and can open and close files
5. the mouse is a text cursor instead of a mouse-cursor
6.  had to end task of vscode in task manager and re-opened vscode 
7.  vscode is now functioning well
7.  had to delete the folder in the file explorer instead of vscode

Not sure if this issue occurs when all extensions are disabled as I have already deleted the file but it should still crash as it is not a problem with the extensions.

The functions file is quite big so maybe that's the reason why vscode crashed.

**Comment by bpasero** [comment]
I think this is likely https://github.com/microsoft/vscode/issues/71243

**Comment by jeffzy15** [comment]
The issue that has been referenced states that VSCode crashed attempting to delete a 10GB file while the file I tried deleting was a mere 20-30MB.

Is there a specific reason why this happens?

Thanks in advance.

**Comment by bpasero** [comment]
@jeffzy15 how exactly do you delete the file, from the explorer?

**Comment by jeffzy15** [comment]
In the explorer I right click on the directory and click delete which moves it to the recycle bin. But when I right click to delete the folder in VSCode to do the same, it crashes while the file explorer handled it well without crashing.

**Comment by bpasero** [comment]
@jeffzy15 explain what "crashes" means, can you record a screen recoridng?

**Comment by jeffzy15** [comment]
The initial crash was longer and didn't eventually delete the folder.

**Comment by bpasero** [comment]
Ok thanks, that video is useful. I refer to @deepak1556 for how to diagnose this further as it seems to be an issue from the Electron API we use to move an item to the trash.

**Comment by jeffzy15** [comment]
Clarification: 

Folder size is 46MB.

Folder size on disk is 60MB.

**Comment by FDiskas** [comment]
Why not just send delete command to the background task and free up vscode instance? Why it so done in the first place?
This issue is so old

**Comment by jeffzy15** [comment]
@FDiskas could you show how to send delete command to the background task and free up VSCode instance.

**Comment by FDiskas** [comment]
Are you shure that I'm the right person to ask?
I would use google or stackoverflow.
There is something like "node detach child process"

**Comment by rzhao271** [comment]
Can you attach a crash dump for that scenario above? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
I'm unable to reproduce the issue locally.

**Comment by FDiskas** [comment]
Reproducible on windows
