### ISSUE TITLE
"Go to Symbol in Workspace" cannot find symbols

### ISSUE THREAD

**Issue by adamalton** [microsoft/vscode#112845]
- VSCode Version: 1.52.1
- OS Version: macOS 11.0.1

*Steps to Reproduce:*

1. Open a folder or workspace which contains at least one Python file with at least one function or class definition and at least one Javascript file with at least one function definition.
2. Click `Go => Go to Symbol in Workspace` and type the name of one of the defined functions or classes.
3. If extensions are enabled, open the command palette and run `Python: Build Workspace Symbols`.
4. Repeat step 2.

*Expected behaviour:*

VS Code can find the function or class which is defined in the file in the workspace.

*Actual behaviour:*

VS Code says "No matching workspace symbols".

Note that in the case of the Javascript file, the defined function *is* found if the file is open, but not otherwise. In the case of the Python file, the defined function is not found, regardless of whether the file is open or not.

See video demo: https://youtu.be/eKZjfv40_YY

*Does this issue occur when all extensions are disabled?: Yes*

The uploaded video was recorded with extensions enabled, which included the Python extension. With extensions disabled the behaviour is exactly the same, except you can't run the `Python: Build Workspace Symbols` command.

**Comment by adamalton** [comment]
@mjbvz is this definitely purely a Python problem? Is it really expected behaviour that "Go to Symbol in Workspace" cannot find any symbols from any files in the workspace unless those files are open?

**Comment by adamalton** [comment]
Hi, just bumping this. I'm pretty sure that this issue is not confined to the Python extension. For example, with Javascript files, symbols are only found in _open_ files, which doesn't seem like the right behaviour for "Go to Symbol in _Workspace_".

Could this please be re-opened?

**Comment by mjbvz** [comment]
Yes, each language implements this feature individually. If you see a problem with python, file an issue against python

You only see results from opened JS files for JS because you likely don't have a [jsconfig](https://code.visualstudio.com/docs/languages/jsconfig)

**Comment by adamalton** [comment]
Ah, ok, that makes sense now, thanks @mjbvz.
