### ISSUE TITLE
Terminal windows can be placed/docked like any other window in the file editing section.

### ISSUE THREAD

**Issue by jordanrancie** [microsoft/vscode#112814]
It would be very useful to be able to dock Terminal windows anywhere within the File Editing section. 

I often use 2, 4 or 6 file layouts to work with multiple files at once:
<img width="1620" alt="before" src="https://user-images.githubusercontent.com/8184815/102617999-ed937900-4131-11eb-81cf-24ca17587d13.png">
however, I have never used Terminals within VSCode because of an inability to customise its location or size (other than splitting the section in two). Instead, I use an external window outside VSCode to better organise the screen real estate. An ability to organise the terminal would avoid a lot of back-and-forths.
<img width="2430" alt="after" src="https://user-images.githubusercontent.com/8184815/102618127-29c6d980-4132-11eb-8ea6-bbb9470cc056.png">

This could also be done for Problems, Output and Debug windows

**Comment by gjsjohnmurray** [comment]
Discussed in #10546
