### ISSUE TITLE
PHP associative array keys in UTF-8 not decoded

### ISSUE THREAD

**Issue by anvltu** [microsoft/vscode#112836]
- VSCode Version: 1.52.1
- OS Version: Ubuntu Mate 20.10 Tested in Windows 10 - the same behaviour.

Steps to Reproduce:

1.
Example PHP code:

		$example = [
			'первый' => 'первый',
			'второй' => 'второй',
		];

		foreach($example as $key => $value) {
			sleep(1);
		}

2.
Set a breakpoint as seen on the picture, "Variables" will show associative array keys in wrong encoding. In example keys and values are identical.  PHP handles Cyrillic array keys correctly, VS Code shows them as unreadable strings.

Does this issue occur when all extensions are disabled?: Yes/No

Cannot test with all extensions disabled since PHP Debug extension is mandatory for debug
![Снимок экрана в 2020-12-18 23-33-34](https://user-images.githubusercontent.com/75672916/102649465-05e3b200-418b-11eb-9cec-5db1e62479a4.png)
.

**Comment by roblourens** [comment]
This sounds like an issue with the PHP debug extension you are using, please file an issue on that extension's repo
