### ISSUE TITLE
need a refresh context menu item for file list view

### ISSUE THREAD

**Issue by yaxinlx** [Microsoft/vscode#11282]
- VSCode Version:

1.4.0

- OS Version:

Debian 8

Steps to Reproduce:

Sometimes, new created files outside vcs doesn't reflect info vcs editor. 
I must restart the editor to see the changes.

**Comment by bpasero** [comment]
@yaxinlx can you run "code --verbose" and open the developer tools console (from help menu) and show the output that happens when you create a file outside of VS Code?

**Comment by yaxinlx** [comment]
@bpasero this case is rare, it only happens for about every several days.

I just run "code --verbose" , and everything is normal. There is no output changes in the developer tools console.

**Comment by bpasero** [comment]
@yaxinlx you should see output for each file change in the console. That is how we can find out if a file event is missing.

**Comment by yaxinlx** [comment]
@bpasero ok. There are really some outputs on file changes after switching to console tab.
But as I said above, this issue is hard to reproduce.

**Comment by bpasero** [comment]
Ok without steps or diagnostic output this is hard to reproduce.

**Comment by bpasero** [comment]
Closing until reproducible steps are present.
