### ISSUE TITLE
Error code 801

### ISSUE THREAD

**Issue by account0123** [microsoft/vscode#112800]
Issue Type: <b>Bug</b>

1) i enter git push command
2) asks me credentials
3) console says Logon failed, use ctrl+c to cancel basic credential prompt.
4) popout opens and says "The extension 'GitHub' wants to sign in using GitHub"
5) i click "allow" and browser open on "https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate"[...] <- if there is sensible information in the url i shortened it
6) i click "Continue"
7)  i enter credentials
8)  the webpage says... i will copy html code
```html
<main><div><h1>Oh no! An error occurred!</h1>
<p>Please restart the sign in process from the editor.</p>
<p>Error code 801</p> </div> </main>
```
9) i try all steps above, the result is the same as step 8

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.55GB free)|
|Process Argv|C:\\Users\\Alumno\\Documents\\GitHub\\observer-bot-ts --crash-reporter-id 3dbff216-0a59-4cc7-936a-4d7884a9b7dc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
chronicler|arc|0.1.8
vscode-great-icons|emm|2.1.62
prettier-vscode|esb|5.8.0
discord-vscode|icr|4.0.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
java|red|0.73.0
tabnine-vscode|Tab|3.1.18
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt875:30237613

```

</details>

**Comment by eamodio** [comment]
@RMacfarlane Do you have any idea on what error 801 means?

**Comment by RMacfarlane** [comment]
This is thrown from the GitHub auth server. I'm not completely sure under what circumstances, but I think is related to proxies.

Duplicate: https://github.com/microsoft/vscode/issues/108304
