### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by AnshRoshan** [microsoft/vscode#112852]
- Issue Type: `Bug`
- Extension Name: `bracket-pair-colorizer`
- Extension Version: `1.0.61`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by pelumiojebode** [comment]
645721

**Comment by pelumiojebode** [comment]
565341
