### ISSUE TITLE
Request for changing text editor style for powershell

### ISSUE THREAD

**Issue by Alessar** [microsoft/vscode#112825]
For PowerShell language, one of code style can be formatted as:
```
Do-SomeFunction -Argument1 value1 `
                -Argument2 value2 `
                -Argument3 value3
```
Indentation for parameters is equal.

When typing a second line and put "Newline" character - cursor goes to indentation as at previous (second) line - and it is expected. But when typing a first-line and put "Newline" character - cursor calculates indentation as a previous first line (it has no indentation) - and after that user should put several additional "spaces" for making a correct indentation.

It will be cool if cursor calculates the first occurrence of argument and make the same (equal) indentation.
It should be done only if the latest character is "top comma" ( ` )
Maybe it should work only if indentations place by "spaces" but not tabs.
Maybe such new behaviour should be turned on/off by additional preference.

**Comment by alexr00** [comment]
Thanks for the feature request! We only provide very basic support for PowerShell built-in to VS Code. This sounds like a good request for the [PowerShell extensions](https://github.com/PowerShell/vscode-powershell) though.

**Comment by rjmholt** [comment]
@alexr00 do you know if there's way for our extension to tell VSCode where the cursor should go? Really I want to know if this is possible for us to configure from an extension, so that when the user enters a new input we can tell VSCode that if they then press return, it should indent to a given level.

**Comment by alexr00** [comment]
You might be able to do it with [indentation rules](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules), but this is outside of my expertise. Maybe @dbaeumer knows of a way to do it with a language server?

**Comment by Alessar** [comment]
@alexr00 Thanks for the link to indentation rules, but I think it can not be used for such feature request.
According to the article about indentation rules, they can add or remove one indentation step.
But for the proposed changes it is needed to calculate different indentation on every time when it happens.

**Comment by dbaeumer** [comment]
@rjmholt LSP doesn't let you control the cursor (on purpose), except for snippets. But you might want to look into the `onEnterRule` that a language configuration in code can specify (https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/src/languageFeatures/languageConfiguration.ts#L21)
