### ISSUE TITLE
Current Line Info and Line Change Event

### ISSUE THREAD

**Issue by itskhurram** [Microsoft/vscode#11298]
Hello,
I want to know if you can guide me how can i get Current Line Information i mean text and Line Change Event in the Editor.

Also how can i Indent / outdent the line Text

Regards,
Khurram

**Comment by jrieken** [comment]
From an editor you for its [selection](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L529) and you can subscribe to [selection change events](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3316).
