### ISSUE TITLE
Disable "dir" for file search on Windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11294]
As a workaround for the issues we see.

**Comment by bpasero** [comment]
Pushed via https://github.com/Microsoft/vscode/pull/11293

**Comment by bpasero** [comment]
Verifier: best to use a tool like process monitor to see that on Windows we do not spawn a dir command when doing file search.

**Comment by dbaeumer** [comment]
Verifying...

**Comment by dbaeumer** [comment]
Verified. However opened: https://github.com/Microsoft/vscode/issues/11461
