### ISSUE TITLE
CSS color box is badly positioned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11296]
Seeing this on Mac:

![image](https://cloud.githubusercontent.com/assets/900690/18123149/e1368332-6f6c-11e6-8a7e-57081a143b88.png)

**Comment by aeschli** [comment]
caused by my change for #10456. I reverted the change.

**Comment by sandy081** [comment]
@aeschli I do not see the color box at all now. Is this expected?

**Comment by sandy081** [comment]
![screen shot 2016-09-01 at 12 57 00](https://cloud.githubusercontent.com/assets/10746682/18165095/9ccfa3ae-7043-11e6-9803-6e719023496a.png)

**Comment by aeschli** [comment]
duplicate of #11381... Fixed but not yet in the insiders build.
