### ISSUE TITLE
Make Event class chainable

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11297]
It would be cool to do:

```typescript
const event2 = event.filter(data => !!data).map(data => data.field);
```

**Comment by jrieken** [comment]
dude - don't over do it ;-)

**Comment by joaomoreno** [comment]
It sucks cause now I have to write:

```
map(filter(event, data => !!data), data => data.field);
```

Or worse:

```
event = filter(event, data => !!data);
event = map(event, data => data.field);
```

Here are a few examples:

- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionEditor.ts#L189
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L95

I could write all that logic in each event listener, but that wouldn't be cool. 😎

**Comment by jrieken** [comment]
Sorry, but how is [that](https://github.com/Microsoft/vscode/blob/3e14ed6a02797e071a9a9f56396513d7a983f262/src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts#L95) more elegant (not event talking about wasted performance and function scopes) that a single listener and a switch/if-else statement?

**Comment by jrieken** [comment]
Apart from personal taste, the reason I comment on this is that `Event` and `Emitter` must kept stable cos they are reflected [one by one](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L139) as API and wouldn't like to see a set of shadow features on top of the [defined](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1209) [ones](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1231).

**Comment by joaomoreno** [comment]
Good to know. I don't mind doing it in a subtype, doesn't need to go to the base type:

```typescript
interface EventVNext extends Event {
  constructor(event: Event);
  map...
  filter...
}
```

Performance is relative. I doubt that it is a significant factor for the amount of these events we intend to observe. I take preference on code style over that sort of performance problems, any day.

The [entire virtual rendering of the list](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listView.ts#L174), which we can agree is quite performant, is made with function closures, by the way.  Would it be faster with a bunch of `for` loops and `if` statements? Yes. Would it be perceivable? Probably not. Would it be more readable or better maintainable code? I don't agree that it would.

**Comment by jrieken** [comment]
> Would it be more readable or better maintainable code? I don't agree that it would.

That's where personal taste begins
