### ISSUE TITLE
[stylus] Add Stylus language support

### ISSUE THREAD

**Issue by buzinas** [Microsoft/vscode#113]
I would like to have full Stylus language support, the same we already have for Sass and Less.

Coloring is already available with `tmLanguage`, but we should have full intellisense support, errors, warnings etc.

I've already taken a look at the way Sass was built, and if you would like to have this improvement in VSCode core, I can contribute with a PR.

If there is any way to do that as an extension (but using the power of Monarch etc), I'll be glad if you give some guidelines of how I can achieve that.

Thanks in advance.

**Comment by joaomoreno** [comment]
Sounds like a great opportunity for an extension, @buzinas ;)

**Comment by aeschli** [comment]
@buzinas If you want to give it a try: Use our [yeoman extension generator] (https://code.visualstudio.com/docs/tools/yocode) to create an extension contributing a colorizer based on text mate (we are currently moving away from Monarch).
Then read on in the documentation how to add intellisense, validation...

**Comment by buzinas** [comment]
@aeschli thanks for the guidelines, I'll give it a try.

About "we are currently moving away from Monarch": are you doing that even with the core TypeScript/Javascript intellisense? It's so powerful (probably the main advantage that Code has against the other editors), why would one move away from that?

**Comment by egamma** [comment]
Monarch provides for colouring only and text mate bundles replace the colouring. The deeper language support we provide isn't affected by this change.

**Comment by buzinas** [comment]
@egamma sorry, I was confusing Monarch with Monaco.

**Comment by buzinas** [comment]
Btw, for anyone who is interested, I've created an extension: https://github.com/buzinas/vscode-stylus

I'll be developing the full intellisense support over the next days.

**Comment by buzinas** [comment]
@aeschli looking at Sass and Less support, they both inherit lots of things from CSS, and put some sugar on top of it (and some modifications either). Is there any way I can also import to my extension the CSS schema etc., to facilitate the process of creating the intellisense?

It would be much simpler, apparently, to create a native support for stylus, instead of an extension. At the moment, I'm using vscode-go extension as my base, but still trying to figure out many things.

**Comment by aeschli** [comment]
@buzinas  CSS/Less and Sass are not yet using the new extensions API, they were written before that. Eventually I'll have to rewrite them to do so.
I see that Stylus itself is implemented in NodeJS, so I'd recommend to use as much as you can from there. Scanner, parser, AST.
Have a look at https://code.visualstudio.com/docs/extensions/example-language-server. You'd implement the language server in a separate NodeJS process, that can keep the ASTs for open documents as to (re-)use them for validation, intellisense, hovers and so on.
We have packages that already implement the process communication for you.
IMO that the best way to go. As mentioned, CSS/Less and Sass is old style and is of limited use as an example or framework to build on.

**Comment by buzinas** [comment]
@aeschli is there any estimate of when CSS will be using the new extensions API? 

Probably it will be easier to provide Stylus support by taking advantage of the CSS one.

**Comment by aeschli** [comment]
@buzinas Looking at the different styles of syntax that Stylus supports, I wonder if it really makes sense to reuse the CSS scanner and parser. 
There's no time decided when CSS is moved to use the extension APIs.

**Comment by mjbvz** [comment]
Closing as stylus support can be added by an extension. Try this one : https://marketplace.visualstudio.com/items?itemName=sysoev.language-stylus
