### ISSUE TITLE
Ignore Error Feature

### ISSUE THREAD

**Issue by Shone03** [microsoft/vscode#113089]
This is a simple thing that has been bothering me for so long.
The point is sometimes I just do something in my code that VSCode (or extension) recognizes as an error but it actually is not. The little ignore button when you hover over it would be so nice. That way I don't need to give up on error detecting completely.

Thanks in advance!

**Comment by sandy081** [comment]
These errors are generated from an extension and the asked feature to ignore the error shall also be provided the extension. Hence please file the issue against the extension.
