### ISSUE TITLE
Code - OSS crashed consistently at start time – renderer process crashed! – until after I removed cached data workbench.desktop.main-17c1ea9255cc303c9339b9c2ce2b4a02.code

### ISSUE THREAD

**Issue by grahamperrin** [microsoft/vscode#113069]
Issue Type: <b>Bug</b>

- reproducible with `--disable-extensions`
- VS Code version: Code - OSS 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-12-16T02:04:21.157Z)
- OS: FreeBSD x64 13.0-CURRENT r368589

I can not guess what caused the problem (sorry) but the application became unusable, probably after I used it on the afternoon or evening of Wednesday 2020-12-16. 

In the absence of an answer to [code-oss (Code - OSS) on FreeBSD-CURRENT: renderer process crashing, the application can no longer open my workspace](https://stackoverflow.com/q/65337416/38108) I methodically removed files from my `.config` directory, then restored them, until an offending file was identified: 

`~/.config/Code - OSS/CachedData/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/workbench.desktop.main-17c1ea9255cc303c9339b9c2ce2b4a02.code`

### After removing the file

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.89GB (0.37GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/local/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
ini-for-vscode|Dav|0.0.4
reg|ion|1.0.2
wordcounter|Lud|0.0.1
vscode-language-pack-en-GB|MS-|1.46.3
vscode-ros|ms-|0.6.3
python|ms-|2020.6.91350
cpptools|ms-|1.0.1
languagetool|ray|1.0.1
rewrap|stk|1.13.0
zip-file-system|Tom|2.0.0
reflow-paragraph|Tro|1.3.0
vscode-aspell|zap|0.1.4
</details>

**Comment by grahamperrin** [comment]
From <https://stackoverflow.com/a/65367754/38108> after working around the bug: 

> Extension host terminated unexpectedly.

– with screenshots. Please, is this coincidental? Or might it be relevant?

**Comment by grahamperrin** [comment]
> … cached data … 

> … an offending file …

#3884

> Code - OSS 1.46.1

Re: <https://www.freshports.org/editors/vscode/> no more recent version has been ported to FreeBSD, 

I sped through subsequent release notes – June 2020 https://code.visualstudio.com/updates/v1_47 to date – found nothing like the crash in this case. 

> … I can not guess what caused the problem (sorry) …

Through https://github.com/microsoft/vscode/search?q=%22renderer+process+crashed%22+is%3Aissue&type=Issues two issues caught my eye: 

* https://github.com/microsoft/vscode/issues/97132 ▶ https://github.com/microsoft/vscode/pull/103122 tagged `1.48.0`
* https://github.com/microsoft/vscode/issues/105984 with reference to a fix in `1.49`

– might this issue 113069 be a duplicate of either of those?

**Comment by deepak1556** [comment]
Can you follow https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash dumps if you can still repro the crash. Thanks!
