### ISSUE TITLE
IntelliSense stops working when renaming a file and creating a new one with the same name

### ISSUE THREAD

**Issue by jltjohanlindqvist** [Microsoft/vscode#11307]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1.  Have a working IntelliSense for TypeScript files in the project.
2.  Rename a file you're currently working in that has working IntelliSense. (from app.ts to app1.ts)
3.  Create a new file with the same original name as the file you renamed. (app.ts)
4.  You no longer have working IntelliSense in the new file (app.ts).

**Comment by gregvanl** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/6139 which was moved to https://github.com/Microsoft/TypeScript/issues/8587.
Might be fixed in a more recent version of TypeScript?

**Comment by jltjohanlindqvist** [comment]
I see that it was added to master https://github.com/Microsoft/TypeScript/pull/8371 in April. I'm running the latest stable of TS, shouldn't this fix be included in that version?

**Comment by waderyan** [comment]
Thanks for opening this issue @jltjohanlindqvist. 

I cannot recreate your issue with the latest RC of TypeScript (2.0.2). Can you follow the [docs](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions) here and see if doing so fixes your issue?

**Comment by jltjohanlindqvist** [comment]
Updating TS to `Version 2.1.0-dev.20160901` and changing the `typescript.tsdk` setting to use the new version fixes the problem.
