### ISSUE TITLE
Fix tree loading animation deprecation

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11302]
`SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.`

**Comment by Emasoft** [comment]
This is wrong. SVG SMIL Animations are NOT deprecated anymore. Thanks to popular demand, Google was forced to cancel the intent to deprecate SMIL. Please keep SMIL animations.

![svg_is_not_deprecated_anymore](https://cloud.githubusercontent.com/assets/713559/18296857/e7dfe68e-74ac-11e6-85b6-6a2748268c41.jpg)

**Comment by joaomoreno** [comment]
Good to know, thanks. I'll still change the animation to CSS on that icon though.
