### ISSUE TITLE
Support snippets, intellisense etc in debug console

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1130]
We should consider supporting snippets, intellisense and other rich design time experiences in the debug console so that we can provide a rich commanding experience in the console. For example, extension providers could take advantage of this so that specific debug commands can easily be exposed and discovered by users as shown in the screenshot below:
![debugconsolesnippets](https://cloud.githubusercontent.com/assets/1704059/11683490/0edef9da-9e63-11e5-9c65-2486f03b5f16.png)

**Comment by isidorn** [comment]
I would use our regular intelli-sense box and not introduce a new concept.
As for the particular commands each debug adapter would have to contribute the,

**Comment by stevencl** [comment]
I agree, this isn't a new concept. This is just reusing the same UI for intellisense, snippets etct inside the debug console. So I press Ctrl-Space and I can see a list of snippets (which as you say would be provided by the debug adapter). I start typing and I get a list of commands that match the characters I type.

It's using the great design time tools we already have to improve the experience inside the repl.

**Comment by daviwil** [comment]
Would love to see IntelliSense appear in the debug console!  I know that PowerShell users would find it really helpful.

**Comment by isidorn** [comment]
This is now supported. Each debug adapter has to pick up the suggestion API for this to work in those languages though.
