### ISSUE TITLE
Tabs look bad in High Contrast theme

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11303]
![image](https://cloud.githubusercontent.com/assets/22350/18124910/867075ea-6f74-11e6-96f3-5fa0e9b1e46a.png)

**Comment by bpasero** [comment]
@joaomoreno @bgashler1 I am fine changing this but I took the same UI we use for selected tree elements that also have an orange border. Also, I did not hear back in any negative way from our HC users, so just saying it looks bad from a user like you that does not rely on HC might not be the best way of looking at the issue.

**Comment by bpasero** [comment]
Made some improvements:

![image](https://cloud.githubusercontent.com/assets/900690/18126500/b1426a4c-6f7b-11e6-991c-8ed8c9efecbf.png)

**Comment by bgashler1** [comment]
I'm not sure there's enough contrast between the active tab and the inactive tabs since the borders are touching.  Perhaps we could make the active tab stroke thicker?

**Comment by bpasero** [comment]
Pushed 2px border:

<img width="597" alt="screen shot 2016-09-01 at 07 04 24" src="https://cloud.githubusercontent.com/assets/900690/18155924/5a62c31a-7012-11e6-9157-9526d62b4bf0.png">
