### ISSUE TITLE
The terminal process failed 

### ISSUE THREAD

**Issue by ali94p** [microsoft/vscode#113065]
while I am trying to run the python code in VS code I get this error:

The terminal process failed to launch: A native exception occurred during launch (Unable to start terminal process: CreateProcess failed).

I tried creating another file in different directory but still doesnt work.
anyone can help please?

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
