### ISSUE TITLE
Font icon theme doesn't use specified font

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#11301]
Testing #11131:

- VSCode Version: 1.5 Insiders
- OS Version: macOS

With the following icon definition I got green 'U' icons for files, but I was not able to see the correct glyph of the TrueType font 'AIR3.TTF'. 

```js
{
	"fonts": [
		{
			"id": "andre-font",
			"src": [
				{
					"path": "./AIR3.TTF",
					"format": "ttf"
				}
			],
			"weight": "normal",
			"style": "normal",
			"size": "150%"
		}
	],
	"iconDefinitions": {
		"_file": {
			"fontCharacter": "U",
			"fontColor": "#00FF00",
			"fontId": "andre-font"
		}
	},
	"file": "_file"
}
```

When switching to the "Akashi.ttf" font from http://designmodo.com/free-fonts-fontface/ I had success after changing the font's format from "ttf" to "woff". So it seems that VS Code is somewhat picky about the fonts.

It would help if the documentation for this feature would make clear what font types/formats are supported.

**Comment by aeschli** [comment]
I updated the icon theme documentation (now hosted on vscode-docs) with the recommendation to use woff fonts
