### ISSUE TITLE
SQL Syntax Highlight Bug with \'

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode#113087]
Issue Type: <b>Syntax Highlight Bug</b>

I have no extension's that effect sql.
I try that  without extensions and i have the same syntax bug:
`\'` this get detected as **sql** `'` but not as **string** `'`
in a sql editor this works.
![image](https://user-images.githubusercontent.com/20490672/102684747-a235a500-41db-11eb-9a8d-372f2df947e9.png)

VS Code version: Code - Insiders 1.53.0-insider (76436a4d43566cd313629799e2ec51b4d00caa64, 2020-12-11T17:56:17.606Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.98GB free)|
|Process Argv|--crash-reporter-id 389cf739-eb5b-4f3b-81a6-f0f8ad7b0e8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (80)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.0.0
ng-template|Ang|0.1100.2
i18n-ally|ant|2.4.14
code-gnu-global|aus|0.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
angular-schematics|cyr|4.7.0
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.38.0
vscode-simpler-icons|dav|1.6.5
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
angular-extension-pack|dog|9.4.5
githistory|don|0.6.14
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vue-inline-template|fai|1.0.1
vue-format|feb|0.1.8
git-project-manager|fel|1.7.1
auto-rename-tag|for|0.1.5
code-runner|for|0.11.1
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.22.0
gitlab-workflow|Git|3.8.0
vscode-test-explorer|hbe|2.19.3
beautify|Hoo|1.5.0
discord-vscode|icr|4.0.0
angular2-switcher|inf|0.3.3
docthis|joe|0.7.1
Angular2|joh|11.0.0
vscode-gutter-preview|kis|0.26.2
electron-debug|kod|18.11.1
refactorix|kri|0.3.6
graphql-for-vscode|kum|1.15.3
json-to-ts|Mar|1.7.5
Angular-BeastCode|Mik|10.0.3
vscode-docker|ms-|1.9.0
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.1
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-next|ms-|4.2.20201211
vscode-typescript-tslint-plugin|ms-|1.3.2
vsliveshare|ms-|1.0.3375
debugger-for-chrome|msj|4.12.11
gremlins|nho|0.26.0
vetur|oct|0.31.3
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.4.0
quicktype|qui|12.0.46
java|red|0.73.0
vscode-yaml|red|0.13.0
vscode-jest-test-adapter|rtb|0.2.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
sonarlint-vscode|Son|1.19.0
autoimport|ste|1.5.3
tech-debt-tracker|Ste|0.27.5
move-ts|str|1.12.0
sass-indented|syl|1.8.13
vscode-status-bar-format-toggle|tom|2.0.0
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
quokka-vscode|Wal|1.0.335
vscode-todo-highlight|way|1.0.4
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanel:30233467

```

</details>

**Comment by alexr00** [comment]
Can you please provide a copy/pastable example?

**Comment by DaniGTA** [comment]
![image](https://user-images.githubusercontent.com/20490672/103794127-a61f4f00-5044-11eb-80af-e9a31cbb1d02.png)
```sql
INSERT INTO test (test1,test2,test3) VALUES
('test','test\'s', 'test')
```

**Comment by alexr00** [comment]
Thanks for filing this issue. I've moved it into the repository where we get our SQL syntax highlighting grammar: https://github.com/microsoft/vscode-mssql/issues/16934
