### ISSUE TITLE
VScode suddenly disappeared from computer localdrive

### ISSUE THREAD

**Issue by Meghana-sk** [microsoft/vscode#113171]
Dear MS Team,
I had installed VS Code 1 month back. Today I couldnt find it on my system. I have not uninstalled or modified anything. So I had to install again. I dont know where the previoulsy installed version went?
Additional info-Integrated VS Code with Github desktop
Kindly look into it please. 

Thank you

**Comment by joaomoreno** [comment]
Strange. Let us know if it happens again.

**Comment by wskruse** [comment]
I can add a second report of this behavior. Went digging to see what I could find at the install location and found this:
![VSCodeInsiders_Directory](https://user-images.githubusercontent.com/74443508/104026175-93676000-5193-11eb-93ea-ad884c4cbfb5.png)

A bit deeper the underscore directory has this in it:
![VSCodeInsiders_DirectoryUnderscore](https://user-images.githubusercontent.com/74443508/104026240-a5490300-5193-11eb-939b-0ac0e2a17994.png)

Looks like the version sitting in the underscore directory is `1.53.0-insider` (based on the package.json in resources/app).

No idea if any of this is helpful or not. I'll try to preserve the install state temporarily if you have any questions you want to ask.

**Comment by Meghana-sk** [comment]
Hi team,
               Thanks for the response. I shall report if it occurs again.


Regards,
Meghana

**Comment by joaomoreno** [comment]
@wskruse Can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by wskruse** [comment]
Done, will report back if the issue recurs.
