### ISSUE TITLE
Expose exception settings in a json file

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1131]
We should consider exposing the ability for the user to specify which exceptions they want to break on when thrown or when they are unhandled. Consistent with how we manage settings throughout the product we could have a default exceptionsettings.json file that defines the default settings and a user settings file that the user can override or customise.

For example, something like the following:
![exceptionsettings](https://cloud.githubusercontent.com/assets/1704059/11683573/8ef8df32-9e63-11e5-844a-0865de2a21f7.png)

**Comment by isidorn** [comment]
I like this however where would this setting file live?
Why not have it top level in our launch.json, as a sibling to `"configurations"` we could have `"exceptions"`.
Putting it in a separate file has the downside of introducing one more configuration file and it would be disconnected from other debug configurations.
Another thing to tackle is how to disable / enable these exception breakpoints from the UI. There can be an option for global enable / disable but not sure how to disable one specific breakpoint. Though we can discuss this later.

@weinand, @stevencl thoughts?

**Comment by stevencl** [comment]
Putting it in the launch.json sounds like a good idea.

**Comment by weinand** [comment]
@stevencl @isidorn Yes, we should store all **breakpoints** (not only exceptions) in the launch.json. Exceptions are just a special type of breakpoint (very similar to function-breakpoints).

**Comment by isidorn** [comment]
Closing this as out-of-scope, feel free to reopen
