### ISSUE TITLE
Laging

### ISSUE THREAD

**Issue by yash19pro** [microsoft/vscode#113145]
Issue Type: <b>Performance Issue</b>

It just started 2 days back when I installed this on my MacBook Pro 13.
I have my gitLens enabled, and while I use the integrated terminal, typing lags, it hangs lags for 1-2 seconds and then back to normal.
I have my Vim extension enabled as well.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 99210095-1d7a-44fc-8aa8-05e52ddf461d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   131	 11219	code main
    2	    57	 11222	   gpu-process
    0	    33	 11224	   utility
    0	   287	 11225	   window (Settings — Untitled (Workspace))
    0	     0	 11229	     /bin/bash -l
    0	   123	 11232	     extensionHost
    0	    41	 11315	       /Users/yashpatel/.vscode/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools
    0	    25	 11334	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=11232
    0	    33	 11239	     watcherService
    0	    33	 11245	     searchService
   92	   106	 11240	   shared-process
    0	     0	 11586	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    4	    57	 11584	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings — Untitled (Workspace))
|    Folder (competitive-coding): 580 files
|      File types: cpp(359) out(38) DS_Store(34) py(19) c(3) txt(2) json(1)
|                  zip(1) md(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vim|vsc|1.18.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by maximusnikulin** [comment]
same here

**Comment by MateWW** [comment]
For me changing typescript version from `4.1.2` to older one solved problems

**Comment by meganrogge** [comment]
@mjbvz 

> For me changing typescript version from `4.1.2` to older one solved problems

**Comment by mjbvz** [comment]
@MateWW  If you are seeing issues related to TypeScript, please open a new issue so we can investigate further (make sure to fill in the issue template too)
