### ISSUE TITLE
Stale image preview when updating an image file

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vscode#11317]
- VSCode Version:1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project folder in VSCode
2. Copy an image named test.png into that folder.
3. Overwrite the test.png image with another image of the same name (via drag and drop, or outside of VSCode)
4. Observe that the image preview shows the old image, even after pressing refresh

A restart of VSCode shows the new image.

I tripped over this twice already and it is extremely confusing when pulling changes from git and still seeing the old version.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7951
