### ISSUE TITLE
Error al mostrar ramas de git 

### ISSUE THREAD

**Issue by jesusfvb** [microsoft/vscode#113187]
Después de actualizar el editor a la versión 1.52.1 y clonar un repositorio de GitHub, cree una nueva rama la cual tenía el nombre de menor precedencia alfabética que el de la rama master (master), después cambie a la rama master y al tratar de acceder de nuevo a la rema que cree esta se dejó de observar, lo mismo ocurrió a la rama master cuando cree otra rama con el nombre de mayor precedencia alfabética. También prevé el editor sin extensiones y dio el mismo resultado para los dos casos, cambie a una versión más antigua y no presento problemas

**Comment by eamodio** [comment]
Duplicate of #112481
