### ISSUE TITLE
settings sync not working on arch linux

### ISSUE THREAD

**Issue by nisarg-ujjainkar** [microsoft/vscode#113157]
- VSCode Version:1.51
- OS Version:Arch linux

Steps to Reproduce:

1.Try to turn on settings sync
2.select GitHub account or Microsoft account

Does this issue occur when all extensions are disabled?: Yes
When trying to turn on settings sync, vs code just keeps showing signing into GitHub instead of redirecting to the browser. I also tried to manually generate an access token it still did not work. The log is also not helping.

```
[2020-12-20 01:58:03.059] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-12-20 01:58:03.059] [userDataSync] [info] Auto Sync is disabled.
```

**Comment by nisarg-ujjainkar** [comment]
The issue was with the display manager and not vscode itself. It is now fixed.

**Comment by bartekpacia** [comment]
@nisarg-ujjainkar how did you manage to solve it? I have the same exact problem with XFCE4 on Arch :(

**Comment by bartekpacia** [comment]
I solved it by installing `xdg-utils`, and then `gnome-keyring` and `libsecret`

**Comment by nisarg-ujjainkar** [comment]
Probably, I need to install `xdg-utils` as well. Anyways, I switched to sddm as my display manager from gdm, and everything started working.

**Comment by HowBoring** [comment]
> I solved it by installing `xdg-utils`, and then `gnome-keyring` and `libsecret`

Thank you for sharing the solution! It was a great help to me. Actually, Archlinux does not install `xdg-utils` by default.

**Comment by bartekpacia** [comment]
Happy to help!^^

I lost myself an hour or two looking for the solution, which was extremely annoying
