### ISSUE TITLE
Shows Problem - but there is no Problem

### ISSUE THREAD

**Issue by ToiletGin** [microsoft/vscode#113196]
Issue Type: <b>Bug</b>

The  following code is part of sqlalchemy to access a sqlite database. 
VS Code shows me that there is a porbelm with the code but if i run it everything works fine.

````
class dbCo():
  #databaseConnection

  def __init__(self, databaseName = ':memory:'):

    self.databaseName = databaseName

    self.engine = create_engine('sqlite:///' + self.databaseName, echo=True)

    Base.metadata.create_all(self.engine)
    self.Session = sessionmaker(bind=self.engine)
    self.sessionz = self.Session()

    #here tis the same session used but here vs code doesent think that 'query' is missing
    aus_ = self.sessionz.query(Block_identifier)
    for row in aus_:
      print(row)

def test():
   db = dbCo()

  #in the following vs code underlines "db" and shows:
  #"Instance of 'session' has no 'query' member"
  aus_ = db.sessionz.query(Block_identifier)
  for row in aus_:
    print(row)
````

how do i get rid of the red underline?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.99GB free)|
|Process Argv|--crash-reporter-id 7c8d53de-44ab-4451-985a-04fb50603d49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025

</details>

**Comment by alexr00** [comment]
I can't reproduce this issue. I copied the code, and set the Language Mode to SQL.
What language mode is your editor set to?
