### ISSUE TITLE
Insert key looks like constantly pressed(text cursor)

### ISSUE THREAD

**Issue by MarcelodeOliveiraSilva** [microsoft/vscode#113122]
I dont know if its my mistake cause im newbie at vs, but looks my insert key is constantly pressed, and i would like to change to a normal text cursor. tnks for anyone that helps me. sorry about my bad english, but its not my native language, im still learning. here is the example in line 22.

![erro cursor de texto](https://user-images.githubusercontent.com/42013438/102688379-26d0f500-41d5-11eb-8484-159d4221556a.png)

**Comment by alexdima** [comment]
It looks like you have installed `vim`. `vim` is an extension that changes the input mode of vscode to more resemble `vim`. Simply disable or uninstall the extension.

**Comment by MarcelodeOliveiraSilva** [comment]
oh man, u're a genius. i've just clone my teacher's repository and VS offered me to install the same tools he uses, so i did it. tnks so much for help, i know its a simple thing, but for a newbie as me, helped me a lot! have a good day!
