### ISSUE TITLE
Support connecting to a debug adapter instance running remotely without having to write extension glue code

### ISSUE THREAD

**Issue by DaanDeMeyer** [microsoft/vscode#113192]
Currently, a debug adapter extension can specify a program in it's package.json and users can use the debug adapter extension without any extension code required. However, in this setup, vscode will always start its own instance of the program specified in "program" in the debug adapter's package.json. For remote debugging, an instance of the debug adapter will have already been started and will be running remotely on a specific host/port. VSCode currently doesn't seem to support connecting to a remote instance of a debug adapter without wiriting extension glue code. Ideally, we could set "host" and "port" options in launch.json which would automatically instruct vscode to instantiate an instance of `DebugAdapterServer with the given host and port` instead of `DebugAdapterExecutable` so that it connects to a remote instance of the debug adapter instead of trying to start it locally.

**Comment by weinand** [comment]
It does not make sense to hardcode a server and port in the package.json (which is part of an extension and unmodifiable).
Using the `DebugAdapterServer` or the `DebugAdapterNamedPipeServer` is the way to go.

For remote scenarios I suggest to use the "RemoveDevelopment" extension which runs debug extensions (and their adapters) automatically in a remote location and takes care of all communication issues.

**Comment by DaanDeMeyer** [comment]
I specifically mentioned adding these options to launch.json and not to package.json. In fact, that's what vscode already via the debugServer attribute but that only does the port and not the host. See the linked PR which adds the debugServerHost attribute so the host can be specified as well.

**Comment by weinand** [comment]
Since we want to keep the number of VS Code-defined launch.json attributes small, we are reluctant to add any new attributes. The "debugServer" attribute only exists for historical reasons.

A "host" attribute would be of very limited use, since running a debug adapter remotely breaks the VS Code assumption/restriction that both the debug adapter and VS Code has access to the same filesystem. 
(VS Code's official way around this restriction is the "RemoveDevelopment" extension mentioned above).

**Comment by DaanDeMeyer** [comment]
Unfortunately, the remote development extensions can't be preinstalled which makes them extremely frustrating to use when the remote host is a test container/vm that is rebuilt whenever the source code changes.

You're right about the filesystem assumption, that's exactly what I encountered just now when trying to test this. As a workaround I'm going to fall back to the C++'s extension's pipeTransport for now.

**Comment by weinand** [comment]
@DaanDeMeyer then let's try to investigate the first problem ("remote development extensions can't be preinstalled"). I'm not sure that this is really a problem...

**Comment by DaanDeMeyer** [comment]
> BTW, some extensions explicitly support remote debugging (if the underlying runtime supports this). E.g. JavaScript debugging can connect to a remote runtime and in this case the extension provides a configurable mapping between rmeote and local file system paths. This approach was the precursor of the "remote development" extension. I think the C++ and C# debug extensions support something similar.

Yes, this seems to be the pipeTransport launch.json config option of the C++ extension. The only annoying thing about this is that it requires the source code to be available on the remote host which isn't the case in my scenario. (But I will be making changes so that this is no longer the case so I can use pipeTransport)

In the absolute ideal scenario, the debug adapter protocol would allow debugging on a remote host without having the source code available on the remote host. Requests from the debugger to access specific source files would be routed from the remote host to the local host running vscode which would provide the requested source file to the debugger. As I understand it, we're not there yet though since this approach would require changes to debuggers such as lldb as well which currently expect the source code to be available somewhere on the remote host filesystem.
