### ISSUE TITLE
PHP (built-in): Incorrect syntax highlighting with `interface`

### ISSUE THREAD

**Issue by Kroc** [microsoft/vscode#113185]
Issue Type: <b>Bug</b>

The syntax highlighter breaks when defining an `interface`, because interface methods have no body.

![image](https://user-images.githubusercontent.com/142650/102711603-e778d600-42b2-11eb-8e51-e3567c33538b.png)

VS Code version: Code - Insiders 1.53.0-insider (c927a8015b9e26bd454d6e293bb0384aa1975d06, 2020-12-18T05:27:48.567Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Moranilt** [comment]
This problem happenes because of your **colored theme**. I have no issues here.

**Comment by Kroc** [comment]
No, the colours are off on the built in themes, it's because I didn't include the PHP prolog in the example:

```php
<?php
interface Test {
    public function testMethod();
    public function __toString(); // <-- not coloured!
}
?>
```

**Comment by ctf0** [comment]
same here too, also not working with abstract methods, basically anything that ends with `();`

**Comment by Moranilt** [comment]
just try theme [One Dark pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) I have no issues yet.

**Comment by ctf0** [comment]
@Moranilt 

![Screen Shot 2020-12-25 at 8 36 10 AM](https://user-images.githubusercontent.com/7388088/103123252-63489900-468c-11eb-97b9-822130fed8e2.png)

u r probably using the stable version of vscode.

**Comment by roblourens** [comment]
Hey @KapitanOczywisty, it looks like we pulled the PHP grammar into Insiders early, but I pulled the latest release and am still seeing this issue. Can you think of any change that might be responsible? Or I can debug some more. This is where it breaks, it never leaves `meta.function.parameters.php`.


![image](https://user-images.githubusercontent.com/323878/103375136-37fbea80-4a8e-11eb-87b8-975fd65a7e92.png)

**Comment by KapitanOczywisty** [comment]
@roblourens To be honest I really forgot about methods without a body, but on the other hand, the `interface` is not implemented properly in the syntax, so I feel a bit justified 😛 Issue is caused by https://github.com/atom/language-php/pull/398 where I've rewritten quite a bit of code to include new typehinting and constructor property promotion (php 8.0).

Will deploy fix shortly 😃

**Comment by KapitanOczywisty** [comment]
@roblourens As an exception can we make direct edit in this repo with fixes waiting for merge upstream? They are rather slow with these stuff and would be better to have this tested in insiders properly.

**Comment by roblourens** [comment]
Sure. Do you want to send a PR to this repo with your change?
