### ISSUE TITLE
No matching version found for @types/vscode@^1.52.0

### ISSUE THREAD

**Issue by Kate605690919** [microsoft/vscode#113176]
- VSCode Version: 1.46.0
- OS Version: 10.14.6

Steps to Reproduce:

1. Run yo code to generate a new extension
2. run npm i and you got an error: No matching version found for @types/vscode@^1.52.0
3. run npm view @types/vscode versions, and the latest version is 1.51.0

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dousha** [comment]
Hi. If you are using a private registry or a registry mirror, then probably the registry you are using is out of sync with npmjs.org.
`@types/vscode@1.52.0` is published on npmjs.org 9 days ago.
