### ISSUE TITLE
Can't do anything meaningful with Go build tasks

### ISSUE THREAD

**Issue by Urethramancer** [Microsoft/vscode#11316]
- VSCode Version:
1.4.0, Luke Hoban's Go plugin

- OS Version:
OS X El Capitan, macOS Sierra beta <any build>.

Steps to Reproduce:
1. Desire building a Go program without debug code.
2.Marvel at how this simple command is seemingly impossible to enter:
go build -ldflags "-w"

This fails at the quotes, and it doesn't accept escaping with \" at all. Build tasks need to be more flexible in that respect.

**Comment by dbaeumer** [comment]
@Urethramancer How exactly does your tasks.json file look like? Something like:
{
   command: "go",
   args: ["build", "-ldflags", "\"-w\""]
}

**Comment by Urethramancer** [comment]
Yep, almost exactly like that:
`{
    "version": "0.1.0",
    "command": "go",
    "isShellCommand": true,
    "args": ["build","-ldflags \"-w\""],
    "showOutput": "silent"
}
`

When first typing \" the existing auto-filled closing quote is overwritten, and I need to add another. But it doesn't like that at all :/

Perhaps allowing single-quoting would be an option, unless there's a trick I don't know about to get it how I like my build commands.

**Comment by dbaeumer** [comment]
@Urethramancer two things: since go is an executable you need to remove isShellCommand or set it to false. Quotes and shell commands are tricky and I even have problems typing them in a terminal sometimes. At the end you will pass three arguments from a process call API point of view. So the tasks.json like

```json
{
	"version": "0.1.0",
	"command": "go",
	"args": [
		"build",
		"-ldflags",
		 "\"-w\""
	],
	"showOutput": "silent"
}
```

works for me. Any objection to close.

**Comment by Urethramancer** [comment]
Thanks a bundle - that works for me! 👍 

isShellCommand was definitely the culprit.
