### ISSUE TITLE
Setting `resourceUri` on a TreeItem override the provided `tooltip`

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#113180]
I have a `TreeItem` that I'm adding a custom `resourceUri` to so that I can use the new `FileDecorationProvider` API, but I've found when a `resourceUri` is set, the `TreeItem.tooltip` is ignored.

I would expect the tooltip to behavior like the `TreeItem.label` -- where if the label isn't specified then it falls back to the `resourceUri`.

I want to be able to specify both a `resourceUri` and `tooltip` and have the tooltip be used. 

One question that would need to be answered is: If a `FileDecoration` is applied to a `TreeItem` that specifies a tooltip, and the `FileDecoration` has a tooltip, should the `FileDecoration.tooltip` be applied to the `TreeItem.tooltip`? I could see it argued both ways and don't have a strong preference either way -- though my inclination is to say that the decoration tooltip should still be applied.

Also this should work even with the tooltip being provided in the `resolveTreeItem`

/cc @jrieken

**Comment by alexr00** [comment]
If a markdown tooltip is provided, then merging the file decoration + the markdown sounds like it will often look ugly. I would not try to merge tooltips in this case.

Given that, I would also not merge string tooltips + file decoration tooltips for consistency (and because it could also look messy).

The most predictable behavior here then is to use either the resource/file decoration tooltip OR the tree item's tooltip. Since the tree tooltip is explicitly provided, I would lean towards showing the tree item's tooltip.

**Comment by eamodio** [comment]
@alexr00 Yeah, I'm good with not merging the tooltips and totally agree with honoring the provided item's tooltip. 

Here are the cases, I think we need to handle:

- `Item.tooltip` provided: use it always, no decorations appended to the tooltip
- `Item.label` provided w/o `Item.tooltip` : use it as the tooltip always, no decorations appended to the tooltip
- `Item.resourceUri` w/o `Item.label` & `Item.tooltip` provided: use it as the tooltip and append the decoration tooltip (if there is one) -- this matches the behavior in the explorer & SCM views

Additionally, it would be great if a user could hover just over the decoration and have the decoration tooltip show, just like we do with the commands (I've wanted the same in the SCM view)

**Comment by eamodio** [comment]
@alexr00 fyi, this is a blocker for me from adopting the new decorators in GitLens. 😉

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/1285843e55e263f2016176dfd61a45c05ff5ec73
