### ISSUE TITLE
Open external terminal launch/debug with correct Terminal

### ISSUE THREAD

**Issue by chenasraf** [Microsoft/vscode#11315]
- VSCode Version: 1.4.0
- OS Version: OS X El Capitan 10.11.5

When debugging/launching your code, VSC doesn't use your external terminal preference set in `settings.json`. I think it should be global, or at the very least, another option to be able to change for that specific type of action.
#### Steps to Reproduce:
1. In your `settings.json`, set your terminal to a different one. e.g. for OSX, use:
   
   ```
   // Customizes which terminal application to run on OS X.
   "terminal.external.osxExec": "iTerm.app"
   ```
2. In `launch.json`, set an action with `"externalConsole": true`
3. Start debugging/running your application
4. Your application will run in the default `Terminal.app` (or your OS equivalent)
#### Expected behavior:

Last step should respect your preferences

**Comment by isidorn** [comment]
fyi @Tyriar

**Comment by weinand** [comment]
Today external terminals managed in debug adapters are completely independent from VS Code and have no access to the the corresponding settings.
But we plan to consolidate this in the future.

**Comment by weinand** [comment]
This should work since August 2016.

**Comment by Evilcat325** [comment]
VSCode Version: 1.7.2 - 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
OS Verson: macOS Sierra 10.12.1

Same reproduce steps. The Terminal.app opened instead of iTerm.app

The right click 'open in terminal' option open the iTerm.app specified in the settings.json.
The launch.json "externalConsole" option seems ignoring the setting in the settings.json

**Comment by chenasraf** [comment]
@weinand but I reported this at the end of august :)

**Comment by weinand** [comment]
@Evilcat325 @chenasraf What debug extensions are you using? Options in launch.json are implemented by a specific debug extension. So if it doesn't work, it is a problem of a debug extension and not VS Code in general.

**Comment by weinand** [comment]
I've just verified that this works fine in the Node debugger of VS Code (extension: Node Debug).

BTW, Node Debug's `externalConsole` attribute has been deprecated. Please use the `console` attribute instead (and if you are not seeing `externalConsole` as deprecated, then you are not using Node debug).

**Comment by Evilcat325** [comment]
@weinand  Thanks for fast respond and explained the detail of the process. I was using the cpp debugger and it still use the `externalConsole` attribute,  I guess I would have to open a issue at their repo. Thanks for the help
