### ISSUE TITLE
Shortcut for Peek Call Hierarchy

### ISSUE THREAD

**Issue by phatNfqAsia** [microsoft/vscode#113184]
I can not set a shortcut for peek Hierarchy Call, can you consider making it available? thanks.

![image](https://user-images.githubusercontent.com/39822773/102710998-14e07680-42e9-11eb-8774-b937239ed35f.png)
![image](https://user-images.githubusercontent.com/39822773/102711007-1ad65780-42e9-11eb-8085-cd1895cf11c3.png)

**Comment by jrieken** [comment]
The command is called `editor.showCallHierarchy`

**Comment by phatNfqAsia** [comment]
> The command is called `editor.showCallHierarchy`

this is not what I meant, the show call hierarchy show a menu in left bar while I want a floating menu right in the editor - the peek version of it for a quicker UX.

**Comment by yngwi** [comment]
I'm interested in this as well. The function is visible in this screenshot:
![image](https://user-images.githubusercontent.com/963440/102987676-01185880-4513-11eb-9738-725744d59705.png)

**Comment by jrieken** [comment]
The command is still called `editor.showCallHierarchy`. So, please try this first and report back if that doesn't work

<img width="792" alt="Screenshot 2020-12-23 at 12 37 56" src="https://user-images.githubusercontent.com/1794099/102992565-b9e29580-451b-11eb-9553-37479f608043.png">

**Comment by coolcorexix** [comment]
@jrieken can you specify the 'condition' that can be set in keybinding to call this 'peek' action, I tried this name but it keep calling the 'show call hierarchy' with UI in the sidebar 😢

**Comment by phatNfqAsia** [comment]
@jrieken I confirm it doesn't work, you can also check from your side though

**Comment by jrieken** [comment]
Please paste the keybindings that you are using/trying

**Comment by phatNfqAsia** [comment]
@jrieken 
this
![image](https://user-images.githubusercontent.com/39822773/103527810-83126500-4eb5-11eb-9d2d-c3649350eea7.png)

when I press `Shift + Cmd +  ,`
this appear
![image](https://user-images.githubusercontent.com/39822773/103527895-a0473380-4eb5-11eb-8d74-f6dcd0abebd9.png)

when I press `Shift + Option + H`
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/39822773/103527951-b6ed8a80-4eb5-11eb-8189-2f4be87fbcb1.png)

**Comment by jrieken** [comment]
The command is still called `editor.showCallHierarchy`! You have bound `Shift + Cmd + ,` to `editor.action.peekCallHierarchy` which does not work because the command is still called `editor.showCallHierarchy`. 

What makes you think the command is called `editor.action.peekCallHierarchy`?

**Comment by phatNfqAsia** [comment]
@jrieken the thing is when I call `Shift + Option + H` the sidebar appear not the peek action, so I try another name and it did not exist. I am trying to tell you is that there is no action to activate `peek  call hierarchy` via shortcut, only the `showCallHierarchy`. The only place where I can get wrong is the condition of the keybinding, or we might have to have an distinct action name for this `peek` action

**Comment by jrieken** [comment]
Having this in keybinding.json just works for me

```json

	{
		"key": "shift+alt+h",
		"command": "editor.showCallHierarchy",
		"when": "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor"
	}
```

**Comment by phatNfqAsia** [comment]
@jrieken I confirm this worked the way I expected. Thank you for your patience

**Comment by phatNfqAsia** [comment]
> Having this in keybinding.json just works for me
> 
> ```json
> 	{
> 		"key": "shift+alt+h",
> 		"command": "editor.showCallHierarchy",
> 		"when": "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor"
> 	}
> ```

@jrieken I confirm this worked the way I expected. Thank you for your patience
