### ISSUE TITLE
Lubuntu 20.4: VS code is very slow and consuming more resources. It's making the computer very slow and the VS code  app itself is becoming very slow.

### ISSUE THREAD

**Issue by venkatrahul-sre-manager** [microsoft/vscode#113174]
Issue Type: <b>Performance Issue</b>

Hello Microsoft support team,

VS code is very slow and consuming more resources. It's making the computer very slow and the VS code  app itself is becoming very slow. I am using Lubuntu 20.4. Please kindly see below the linux distribution details and thanks very much for the help:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic
Remote OS version: Linux x64 5.4.0-58-generic

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
AWK|lug|0.0.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
code-runner|for|0.11.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
python|tht|0.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
pythonvspyt617cf:30237717
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by pelumiojebode** [comment]
57833106

**Comment by venkatrahul-sre-manager** [comment]
Hello team members,

Very good morning.
Can you please kindly let me know if this has been addressed?

Best regards & thanks 
Venkat

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
