### ISSUE TITLE
Add "Open folder in VSCode" option to Context Menu

### ISSUE THREAD

**Issue by bruc3mackenzi3** [microsoft/vscode#113186]
# Feature Request
VSCode should add an option in Finder / File Explorer's Context Menu to open the folder in VSCode.

This would add a fast and convenient way of opening Folders in VSCode.  Many other native apps provide this (e.g. Git Bash as seen below) and it would be nice to see VSCode adopt it too.

![context](https://user-images.githubusercontent.com/1413947/102713752-6a406780-4298-11eb-800d-5a523ebada82.png)

# Rationale
When opening a new folder in VSCode the process currently is as follows:

- Open VSCode application or open a new VSCode window if the current session is to be preserved
- Navigate to "Open Folder", either via File menu or Ctrl + K + O
- Navigate to the folder and select it for opening

As a user who does not make heavy use of workspaces I frequently go through these steps to open a new folder for editing.  Sometimes I arrive at the folder I want to work on via File Explorer.  Having the context menu option in this scenario would be extremely useful.

A similar case could be made for opening files via the context menu.  I feel it is less compelling however because systems already provide configuration to open each file type with a preset program.

I come to this feature request as a Windows user, but I'm sure the equivalent is valid in OSX's Finder.  If you're a Mac user feel free to share your perspective.

**Comment by yume-chan** [comment]
Code supports Windows Explorer context menu [way back to 2016](https://github.com/microsoft/vscode/blame/2cfaec6fe122740d036f94061752e74f453e5807/build/win32/code.iss#L65). If you don't see it, re-run the installer and check the option this time.

For macOS, duplicate of #1223

**Comment by bruc3mackenzi3** [comment]
Thanks for the tip!  In the installer I see the option (which is disabled by default)  to add context menu entries.

**Comment by bruc3mackenzi3** [comment]
Thanks for the tip! In the installer I see the option (which is disabled by default) to add context menu entries.

**Comment by miguelms95** [comment]
It would be great to have this option as a configuration menu, and not require to re-install. Would it be possible?

**Comment by bruc3mackenzi3** [comment]
Sure it's _possible_ - however configuring at installation time is standard behaviour for Windows applications.
