### ISSUE TITLE
Support use option as meta in terminal

### ISSUE THREAD

**Issue by mikehaas763** [Microsoft/vscode#11314]
- VSCode Version: 1.4.0
- OS Version: 10.11.6 mac os x

Steps to Reproduce:
1. type in a word/command into vs code terminal
2. hold option key and tap delete key

Deleting a whole word while holding option "meta" key does not work. One character is deleted. In the regular terminal for os x in preferences there is a checkbox that lets you enable the option key to be used as a meta key which allows holding the option key and hitting delete to delete an entire word at a time.

**Comment by adamluzsi** [comment]
+1 for this :) 
👍

**Comment by Tyriar** [comment]
`ctrl+w` does this now, you should be able to do this by remapping keys to send the escape sequence you want (`^W`).

**Comment by Tyriar** [comment]
Actually maybe you can't do that now as the same escape sequence is sent regardless of whether alt/option was pressed. I filed this upstream https://github.com/sourcelair/xterm.js/issues/486

**Comment by adamluzsi** [comment]
Option key is more than just for deleting. There is a couple of great thing you can do with option key, delete is only one thing from that. :)

**Comment by Tyriar** [comment]
@adamluzsi any others in particular that you can do with other terminals but not vscode?

**Comment by mikehaas763** [comment]
@Tyriar All I use it for personally is moving one word at a time as opposed to one letter. Moving includes deleting and using arrow keys.

**Comment by Tyriar** [comment]
Thanks, we're looking into how to solve this problem in the general case so we can remove some of the non-standard keybindings we hard coded into the terminal code https://github.com/sourcelair/xterm.js/issues/487

**Comment by LeviticusMB** [comment]
Essentials: Arrow keys, backspace, d (delete current word), c (capitalize), l (lowercase), u (uppercase) but see https://en.wikipedia.org/wiki/GNU_Readline and http://www.aboutlinux.info/2005/08/bash-shell-shortcuts.html.

**Comment by qinix** [comment]
+1 for this

**Comment by dodalovic** [comment]
👍

**Comment by peabnuts123** [comment]
On OSX "Use Option as Meta Key" is a setting in the default Terminal app. All this does is change the functionality of Option to send the Meta key instead (as opposed to typing in special characters such as ∂, not very useful on a Terminal IMO). The Meta key is then used for whatever by whatever application you run within it. A List of Features that the Option key "should do" is not really the right solution for this. For example, when using `tmux`, I have `Meta-Z` bound as my prefix for commands; so to split a pane I first press `Option-Z (Meta-Z)` and then `\`. This does not work in the VSCode integrated terminal, and no amount of feature documenting is going to fix that.

I think that the change that is needed here is a similar option for the Integrated terminal on OSX to support the Meta key within the terminal. I realise this may be an issue with the underlying terminal library itself, however.

**Comment by so0k** [comment]
Is there an issue  to track regarding the feature to `Use Option as a Meta key` in `sourcelair/xterm.js`?

**Comment by danseethaler** [comment]
My personal favorite is `alt+.` which inserts the last argument from the previous command. Any progress on this issue? I don't see any comments in the upstream issue since January.

**Comment by DiegoSalazar** [comment]
I would love to move forward/back by word `meta + b, meta + f` as well.

**Comment by jingweno** [comment]
Any update on this? Happy to put up a PR for this

**Comment by ricard0ff** [comment]
+1

**Comment by Tyriar** [comment]
@jingweno the prerequisite to this is https://github.com/xtermjs/xterm.js/issues/487 which has a discussion going. We'll should be able to accept a PR if we all agree on the design.

**Comment by Tyriar** [comment]
Actually I just saw https://github.com/Microsoft/vscode/issues/31262 which has a pretty nice solution to this:

@mikelward 

> Originally https://stackoverflow.com/questions/45257525/ctrlc-inside-vscode-terminal
>
> Inside the integrated terminal, I'd like to be able to make `Ctrl+C`/`Ctrl+V` copy and paste, and have `Ctrl+Shift+C` and `Ctrl+Shift+V` send literal `Ctrl+C`/`Ctrl+V`.
>
> I can do the first two by setting custom key bindings for `workbench.action.terminal.copySelection` and `workbench.action.terminal.paste`.
>
> It looked like maybe I could do the second two using `workbench.action.terminal.sendText`, but when I try it I get `command 'workbench.action.terminal.sendText' not found`, presumably because it's not defined in `terminalActions.ts`.
>
> And if it was available as a command, I'm not sure how I'd pass arguments, or specify control characters.  I would try something like:
>
>        {
>             "key": "ctrl+shift+c",
>             "command": "workbench.action.terminal.sendText",
>             "args": ["\003", false],
>             "when": "terminalFocus"
>         }
> 
> but maybe something more explicit would be better.

@raphadko

> This would be incredibly useful for running all sorts of commands in the terminal. For example I would like to create a macro to switch to terminal and run the last command I ran (CTRL + P) or (arrow up), currently I can't find a way to do this.

**Comment by Tyriar** [comment]
@jingweno if you're still up for doing a PR you can try exposing the `workbench.action.terminal.sendText` command to be accessible via keybindings.json as in the above comment.

**Comment by Frodox** [comment]
Same story for `Alt + .` (not working. For linux - last argument in terminal)

**Comment by Tyriar** [comment]
Another case: https://github.com/Microsoft/vscode/issues/31823

**Comment by saamalik** [comment]
Found a temporary solution. Add the following to your `~/.inputrc` file:
```
"ƒ": forward-word
"∫": backward-word
"≥": yank-last-arg
```

And restart your terminal (or run `bind -f ~/.inputrc`). _I tested the above on Hyper terminal, but should work in vscode as well._

**Comment by DiegoSalazar** [comment]
Brilliant! That works in vscode. Thanks!


- Diego E. Salazar

**Comment by saamalik** [comment]
@DiegoSalazar cool!

btw I think this is an even better option: [Mac OSX: altIsMeta support](https://github.com/xtermjs/xterm.js/pull/1225)! If @Tyriar is okay with the PR, then you'll probably need to make a corresponding change in VScode to enable `altIsMeta`.

**Comment by DiegoSalazar** [comment]
Noticed a problem though, on vscode after applying your fix to .inputrc I
was no longer able to press the regular b key! I can type f normally, but
the terminal ignores the b key :/


- Diego E. Salazar

**Comment by saamalik** [comment]
@DiegoSalazar oh really! That's actually a lot worse than not being able to jump between words. btw the altIsMeta fix will probably be merged soon. In the interim you can also use 'ESC'+b, 'ESC'+f, etc. to jump between words.
