### ISSUE TITLE
Improve discoverability of cell folding 

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#113248]
We provide actions for folding cells. This is hard to discover. Jupyter supports double clicking on the focus bar which is rather intuitive. We don't have a focus bar, but we should explore whether we can find another way to  support double click to fold/unfold cells.

**Comment by misolori** [comment]
I wonder if we could get away with double-clicking the empty space on the side. We do this double-click in other areas (explorer, suggest widget, find widget):

https://user-images.githubusercontent.com/35271042/102828809-757bbc00-439a-11eb-99b1-e5769a95e907.mov

cc @rebornix

**Comment by roblourens** [comment]
Implemented this, only works for code cells currently and only on the left side of the sidebar, needs https://github.com/microsoft/vscode/issues/119535

**Comment by misolori** [comment]
@roblourens I'm not able to get this to work, do you have a screen recording?
