### ISSUE TITLE
Repository settings

### ISSUE THREAD

**Issue by alexkuc** [microsoft/vscode#113202]
Current version of [doc settings](https://code.visualstudio.com/docs/getstarted/settings) does not mention that you can create so-called "repository settings" ([source](https://stackoverflow.com/a/58943928/4343719)). 

By repository settings, I mean `.vscode/settings.json`. This way you can override settings specific to that folder/repository.

Case regarding workspaces: I know you can use workspaces for this, but they have one disadvantage - you need to open workspace for settings to apply; in case of `.vscode/settings.json`, you can run `code folder` and `settings.json` is automatically applied.

Is this an actual omission in the official docs or am I misunderstanding something here?

**Comment by gjsjohnmurray** [comment]
These are also workspace settings. See https://github.com/microsoft/vscode/issues/77718#issuecomment-748807315 by @bpasero in a recent thread about ongoing confusion around the term "workspace".

**Comment by alexkuc** [comment]
@gjsjohnmurray Seems true but I have noticed the following difference in regards to workspaces:

- if I save `.code-workspace`, I need to open `.code-workspace` for the workspace settings to be applied
- if I have `setttings.json` to `.vscode`, the settings are applied automatically when I open the folder via `code` from command line

As a concrete example:

- in the first case, I would do `code .vscode/test.code-workspace`
- in the second case, I would do `code .`

**Comment by roblourens** [comment]
Yes, see the linked issue for a very long discussion about how the term "workspace" is overloaded. When you have just opened a folder, "workspace settings" is the settings.json file that you have identified. Can also be called "folder settings"
