### ISSUE TITLE
why my ext"CMAKE TOOLS" has no icon

### ISSUE THREAD

**Issue by GSRLW** [microsoft/vscode#113265]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.open a project
2.has no icon 
![image](https://user-images.githubusercontent.com/35130268/102846560-3ce7eb00-444b-11eb-85d5-adfd79824961.png)

this problem just do just only a project .  disable when I change  a project(folder).
maybe ,it's my wrong setting?

**Comment by joaomoreno** [comment]
You mean the extension view? Make it wider and you'll see the extension icons.

**Comment by GSRLW** [comment]
Thanks


Best Wishes！
