### ISSUE TITLE
not export method not display reference info

### ISSUE THREAD

**Issue by fjqingyou** [microsoft/vscode#113213]
``` typescript


/**
 * this method has 1 reference display
 */
//1 reference display in here
export function method1() : void{

}


/**
 * this method not reference display
 */
//here not display reference info
function method2() : void{

}

//call method
method1();
method2();
```

**Comment by fjqingyou** [comment]
not covered, this is a new issue

**Comment by jrieken** [comment]
what language is this. what extensions are you using. what is the expected behaviour? I do not understand "
not export method not display reference info"

**Comment by fjqingyou** [comment]
@jrieken Hello 。 I'm using typescript. this code write 'test.ts' file!

**Comment by jrieken** [comment]
> not export method not display reference info

and what does that sentence above mean?

**Comment by yume-chan** [comment]
I think the op is talking about the references code lens?

![image](https://user-images.githubusercontent.com/1330321/102755538-8b44ad80-43a9-11eb-85dc-90fa2abe4752.png)

However I couldn't reproduce this issue.

**Comment by fjqingyou** [comment]
![20201221181121](https://user-images.githubusercontent.com/31087168/102765719-f6957c00-43b7-11eb-90a4-b6e647eb44b4.jpg)

**Comment by yume-chan** [comment]
I know. I have `"typescript.referencesCodeLens.showOnAllFunctions": true`

The only problem is anonymous functions also get reference lens.

![image](https://user-images.githubusercontent.com/1330321/102767387-70c70000-43ba-11eb-91e0-6d6c23441167.png)

**Comment by fjqingyou** [comment]
Thank you. It is the configuration that caused the problem!
