### ISSUE TITLE
Apparent pause when run python input() in the integrated terminal

### ISSUE THREAD

**Issue by qiulang** [microsoft/vscode#113259]
- VSCode Version: 1.52.1
- OS Version:Darwin x64 20.1.0
- Python extension:v2020.12.424452561

It happens to all python3 version I encounter.

When run python `input()` in the integrated terminal, especially to get more than one input value separated space, I can feel the apparent pause, compared to running the code in system provided terminal or iTerm, I don't feel the pause at all (as it shouldn't)

Just run this in the integrated terminal

```
 tmp = input('Input your values, separated by space\n')
 ```

I originally opened issue at https://github.com/microsoft/vscode-python/issues/15019 but they told me I should open here directly.

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
