### ISSUE TITLE
Lines Selected in the bottom right?

### ISSUE THREAD

**Issue by CoryNull** [microsoft/vscode#113244]
Issue Type: <b>Feature Request</b>

Can I have the ability to see how many lines I highlighted in the corner?
It tells me how many chars selected but not enough other information.
A little extra information like that could help me program.

Use case? I need to know how many elements I need to allocate in an array, so I highlight all the lines with an entry on each, and get how many lines selected... Then punch it in.

I'd rather not install an extension for such a tiny feature.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by alexdima** [comment]
Extensions have the ability to show extra information on the status bar. We already have a busy status bar, so we will not be adding more information about the selection in the core vscode. So I recommend to look for or create a tiny extension that does this.
