### ISSUE TITLE
Filename renders incorrectly on Tab

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/vscode#113229]
Issue Type: <b>Bug</b>

When I sometimes rename files, the filename changes from lower case `frameItStore.ts` to upper case `FrameItStore.ts` in the sidebar but it doesn't update in the Tab.

Sometimes it happens after rename too. This is only happening since the latest release which I downloaded 2 days ago I think.

See the image where the filenames are out of sync 👇

![bug](https://user-images.githubusercontent.com/16436270/102780387-d7005280-43bb-11eb-8f1d-fa55c9ad594a.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (99)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-profile-switcher|aar|0.3.3
string-converter|ada|0.1.2
markdown-toc|Ala|1.5.6
Bookmarks|ale|12.0.0
project-manager|ale|12.0.1
alignment|ann|0.3.0
vscode-apollo|apo|1.18.0
ascii-tree-generator|apr|1.2.4
svgmini|ave|0.2.1
vscode-icontheme-nomo-dark|be5|1.3.6
search-crates-io|bel|1.2.1
color-info|bie|0.5.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
vscode-styled-jsx|bla|2.0.0
vscode-tailwindcss|bra|0.5.6
better-toml|bun|0.3.2
simple-react-snippets|bur|1.2.3
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
overmind-devtools-vscode|chr|0.0.36
coddx-alpha|cod|0.2.28
bracket-pair-colorizer|Coe|1.0.61
postcss|css|1.0.9
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
eslint-disable-snippets|drK|1.2.0
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.0
prettier-vscode|esb|5.8.0
vscode-highlight|fab|1.4.1
vscode-open-in-github|fab|1.2.3
vscode-todo-plus|fab|4.18.0
auto-rename-tag|for|0.1.5
macros|ged|1.2.1
gc-excelviewer|Gra|3.0.40
vscode-graphql|Gra|0.3.13
headwind|hey|1.7.0
easy-snippet|inu|0.6.2
RelativePath|jak|1.4.0
latex-workshop|Jam|8.15.0
svelte-vscode|Jam|0.9.3
search-node-modules|jas|1.3.0
vscode-pigments|jas|2.0.0
pubspec-assist|jer|2.2.1
vscode-hacker-typer|jev|0.1.1
vscode-text-pastry|jkj|1.2.0
lorem-whatever|job|1.0.2
read-time|joh|0.2.0
vscode-cloak|joh|0.3.0
vscode-peacock|joh|3.9.1
vscode-mdx|Jou|0.2.2
vscode-styled-components|jpo|1.4.1
vscode-colorize|kam|0.8.17
swift|Kas|0.2.0
auto-comment-blocks|kev|1.0.1
vscode-dashboard|kru|2.3.1
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
markdown-link-updater|mat|1.1.3
vscode-language-babel|mgm|0.0.30
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.18
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.2
wordcount|ms-|0.1.0
vscode-jest|Ort|3.2.0
advanced-new-file|pat|1.2.2
material-icon-theme|PKi|4.4.0
remove-comments|pli|1.2.2
polacode|pnp|0.3.4
prisma|Pri|2.13.1
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
ActiveFileInStatusBar|Ros|1.0.3
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.4.2
velocity|sod|0.2.0
autoimport|ste|1.5.3
vscode-field-lights|sve|0.0.11
ayu|tea|0.20.1
alphabetical-sorter|ue|2.0.1
vscode-svg-previewer|vit|0.6.0
rainbow-tags|vol|0.3.2
vscode-icons|vsc|11.0.0
gistfs|vsl|0.1.12
vscode-wakatime|Wak|4.0.9
vscode-import-cost|wix|2.13.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.12

(43 theme extensions excluded)

</details>

**Comment by deadcoder0904** [comment]
I also thought the issue template was missing. It was empty as I filled it through VSCode's `Help > Issue` option.

**Comment by deadcoder0904** [comment]
And disabling all extensions still gives the filename error.

**Comment by bpasero** [comment]
Need exact steps to reproduce.

**Comment by deadcoder0904** [comment]
I'd tell you if I knew but I don't 😂

The only thing I know is it started happening since the latest update 2 days ago, maybe 3 days ago now ;)

**Comment by deadcoder0904** [comment]
I was using https://github.com/RoscoP/ActiveFileInStatusBar

Suddenly, I looked at the status bar & it had the lowercase filename so I thought this might be the issue. It doesn't show different filenames atleast for now.

Idk why disabling all extensions didn't work as expected.

I'll re-open this if it happens again.
