### ISSUE TITLE
Debugger opens copy of typescript file in a new tab with breakpoint at correct line number of the original file

### ISSUE THREAD

**Issue by ahaberbosch** [microsoft/vscode#113253]
- VSCode Version: 1.47.3 +
- OS Version: Windows 10

Steps to Reproduce:
1. i'm attempting to debug a protractor typescript spec that uses ts-node.
2. ts config: {
  "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "downlevelIteration": true,
        "module": "commonjs",
        "outDir": "./dist/out-tsc",
        "mapRoot": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2017",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2017",
            "dom"
        ],
        "types": [
            "jasmine",
            "jasminewd2",
            "node"
          ]
    }
}

3.launch.json example: {
            "type": "node",
            "request": "launch",
            "name": "Launch Protractor DEV",
            "args": [
                "${workspaceFolder}\\node_modules\\protractor\\bin\\protractor",
                "${workspaceFolder}\\debug.conf.js",
                "\"--specs ${file}\"",
                "--params.env=dev",
                "--params.loglevel=debug"
            ],
            "protocol": "inspector",
            "smartStep": true,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js",
                "**/*async_hook*.js"
              ],
        }

4. set a breakpoint in a simple spec file

Actual results: So slow, nagging about setting outfiles. opens the same file in a different tab in what looks like preview mode, and breaks on the wrong line, but because it appears to be sort of a transpiled version the line content is totally wrong. 

Does this issue occur when all extensions are disabled?: No

This seems to be related to the new js debugger in version 1.47+I tried to manually compile to create .js and map files and I get the same behavior. I noticed that now the debug terminal doesn't show inspect-brk  when launching protractor. I tried several different tsconfigs and launch config alternatives with all similar behavior. My only workaround is to stay at 1.46. 

I

**Comment by connor4312** [comment]
Thanks for the issue. Something that looks supicious is `"mapRoot": "./dist/out-tsc",` -- this almost never needs to be specified and can cause issues.

If removing that doesn't fix your issue, please share a small sample repro.

**Comment by ahaberbosch** [comment]
I tried that, but it takes about 10 minutes for any type of debugger output, and I get nagged about setting outfiles.

**Comment by connor4312** [comment]
You may want follow that tip. If you're using ts-node (don't need to depend on any on-disk outfiles) you can set outFiles to an empty array and then `resolveSourceMapLocations` to null, docs: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by ahaberbosch** [comment]
vs code tells me "property resolveSourceMapLocations is not allowed"

**Comment by connor4312** [comment]
The option is a new one -- though it will complain that it's invalid, it'll work, or alternately you can change your `type` to `pwa-node` to go directly to the new debugger.

**Comment by ahaberbosch** [comment]
Ok, I think I have it working now. It also didn't like the protocol property i had specified, and it was spitting out "source map not found" errors for node. Another thread mentioned the following:
```
"resolveSourceMapLocations": [
  "${workspaceFolder}/**",
  "!**/node_modules/**"
]
```

I ended up with the following that I think is working as desired:
```
{
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Protractor DEV",
            "args": [
                "${workspaceFolder}\\node_modules\\protractor\\bin\\protractor",
                "${workspaceFolder}\\debug.conf.js",
                "\"--specs ${file}\"",
                "--params.env=dev",
                "--params.loglevel=debug"
            ],
            "smartStep": true,
            "skipFiles": [
                "${workspaceFolder}/node_modules/**/*.js",
                "<node_internals>/**/*.js",
                "**/*async_hook*.js"
            ],
            "outFiles": [],
            "resolveSourceMapLocations": [
                "!**/node_modules/**"
              ]
        },
```

Thanks and Merry Christmas

**Comment by connor4312** [comment]
Glad you got it working! Happy holidays to you as well.
