### ISSUE TITLE
Find match color is hardcoded at multiple places

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11323]
Search view and References widget re-uses the find match color `rgba(234, 92, 0, 0.3)` by hardcoding. After exporting the find match color as TM theme setting, these should also start using the color value from the setting.

**Comment by Tyriar** [comment]
How can this be verified? Should this be marked `debt` instead of `bug`?

**Comment by sandy081** [comment]
@Tyriar This is not yet part of the build. I just delivered this change. I will update this item with clear verification steps. Thanks for pointing this.

**Comment by sandy081** [comment]
@alexandrudima Can you verify this?

**Comment by alexandrudima** [comment]
Works nice!
