### ISSUE TITLE
Git icons disapear at night

### ISSUE THREAD

**Issue by guillermo11bq** [microsoft/vscode#113256]
Issue Type: <b>Bug</b>

I enabled the feature where the theme changes with the rest of the system at night in MacOS. Everything works except the "Open changes with previous revision" and the rest of git buttons in the editor simply stop showing, but still take a place. What I mean is they are still there and are clickable, but completely transparent or hidden.
Even after changing the theme, they only show up again with light themes.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 3.10.0-1127.19.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|-psn_0_3535711 --crash-reporter-id c33a5fe9-f542-47bb-b10a-d316d9cadf45|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 3.10.0-1127.19.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU @ 2.00GHz (8 x 2000)|
|Memory (System)|29.29GB (2.87GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
smarty|imp|0.3.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
vscode-easy-coding-standard|azd|1.4.0
vscode-intelephense-client|bme|1.5.4
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
php-debug|fel|1.13.0
vscode-test-explorer|hbe|2.19.3
git-graph|mhu|1.28.0
etsy-test-adapter|zwr|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

![image](https://user-images.githubusercontent.com/42749248/102834310-4c1e5880-43b9-11eb-997f-3dfcb1562a58.png)
![image](https://user-images.githubusercontent.com/42749248/102834358-7112cb80-43b9-11eb-91fb-ccc0e4e447ed.png)
![image](https://user-images.githubusercontent.com/42749248/102834381-7d972400-43b9-11eb-9681-1620953720ec.png)

**Comment by aeschli** [comment]
Does the same happen with other dark theme when  you manually select an other dark theme with `Preferences: Color Themes` ?

**Comment by aeschli** [comment]
@guillermo11bq  If you are familiar with the chrome dev tools, use `Developer: Toggle Developer Tools` to inspect the gifs.
@eamodio These are icons from gitlens. Anything special about these svgs?

**Comment by eamodio** [comment]
Nothing special about the SVGs and I've never seen them disappear like that before.

**Comment by deepak1556** [comment]
Root issue is fixed at https://github.com/microsoft/vscode/issues/114743 , please follow that issue for updates. Thanks!
