### ISSUE TITLE
ID and classes are displayed in the same color in Pug file.

### ISSUE THREAD

**Issue by mk-startialab** [microsoft/vscode#113205]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 18362.19h1_release, 190318-1202

Steps to Reproduce:

1. Open a Pug file which includes ID and class

![problem](https://user-images.githubusercontent.com/22786610/102731245-a815bc80-437a-11eb-87f2-5c7af952c0cf.png)

Does this issue occur when all extensions are disabled?: Yes

This is caused by pug.tmLanguage.json.
Whose statement of classes is "attribute-name.class.pug".
It should be changed to "attribute-name.class.css" to solve this issue.

**Comment by alexr00** [comment]
Details on how you can do this: https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting
