### ISSUE TITLE
Console freezing

### ISSUE THREAD

**Issue by nerxhan-eduongo** [microsoft/vscode#113247]
Issue Type: <b>Performance Issue</b>

When I'm using VS Code console, and start typing on that, ie git branch, git status it freez, and the word comes later

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 2|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv|--crash-reporter-id 44547d9d-b8bf-42f4-be92-cf8cf3f4d7e2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   10	   180	   375	code main
    1	    66	   602	   gpu-process
    0	    16	   605	   utility
    0	   229	   606	   window (index.js — talent-db-frontend)
    0	    82	   610	     extensionHost
    0	    66	   612	       electron_node tsserver.js 
    0	   721	   613	       electron_node tsserver.js 
    0	    16	   622	         electron_node typingsInstaller.js typesMap.js 
    0	   147	   623	       electron_node eslintServer.js 
    0	    16	   691	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=610
    0	    16	   611	     watcherService
    0	     0	  1022	     /bin/bash -l
   87	    66	   621	   shared-process
    0	     0	  3432	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    2	    66	  3430	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js — talent-db-frontend)
|    Folder (talent-db-frontend): 2068 files
|      File types: js(1363) svg(122) jsx(60) less(53) png(29) json(29) md(27)
|                  ts(10) jpg(4) yml(2)
|      Conf files: package.json(2) jsconfig.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspyt653:30237719
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459:30237187

```

</details>

**Comment by meganrogge** [comment]
please try "terminal.integrated.rendererType": "dom"

**Comment by nerxhan-eduongo** [comment]
still has some freezing, looks much better now. I will continue to work on this way.
If I have same problem again, I'll come back


Thank

**Comment by NerxhanMusliu** [comment]
it is getting worse, whenever I try to use the integrated terminal, it freeze after I type one word, and then I have to wait until the word comes

**Comment by skiabox** [comment]
I have the same exact problem.
My system is a macbook pro 16 with mac OS Big Sur.

**Comment by jk779** [comment]
seems to be this issue here: https://github.com/microsoft/vscode/issues/105446

**Comment by meganrogge** [comment]
Duplicate of #105446
