### ISSUE TITLE
Menubar has dissappeared and I am unable to restore it

### ISSUE THREAD

**Issue by egildon** [microsoft/vscode#113241]
Issue Type: <b>Bug</b>

I dont know how it happened.
I began using VS one day and noticed that the Menu Bar dissappeared.
I attemoped to press and then hold the <Alt> key but it does not reappear.
I navigated to visual:toggleMenuBar it is unresponsive to change
attempted Keybinding change. Still no effect 
Json value continues to reset to default when <Alt> is pressed

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 3177)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.37GB (1.67GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 67deb282-eb87-4e5f-8595-7ac99796e659|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|0.0.63
vscode-django|bat|1.0.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-footnotes|bie|0.0.7
markdown-image-size|bie|0.0.4
markdown-preview-github-styles|bie|0.1.6
file-browser|bod|0.2.10
vscode-markdownlint|Dav|0.38.0
vscode-html-css|ecm|1.3.0
font-switcher|eva|3.1.0
calendar|Gru|0.0.13
todo-tree|Gru|0.0.192
vscode-hackmd|Hac|1.1.2
vscode-test-explorer|hbe|2.19.3
live-html-previewer|hdg|0.3.0
view-git-branch-merged-status|hum|0.4.1
fuzzy-search|jac|0.0.3
vscode-theme-switcher|Jan|0.2.0
nbpreviewer|jit|1.2.2
solidity|Jua|0.0.80
nvim-ui-modifier|Jul|0.0.7
magit|kah|0.6.2
auto-comment-blocks|kev|1.0.1
vscode-python-test-adapter|lit|0.6.5
markdown-shortcuts|mdi|0.12.0
theme-monokai-pro-vscode|mon|1.1.18
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.4
autodocstring|njp|0.5.4
vscode-vim-search-and-replace|nle|0.1.0
vscode-qt-for-python|sea|0.5.3
vscode-file-explorer-menu|sen|1.0.2
markdown-preview-enhanced|shd|0.5.13
html5-boilerplate|sid|1.1.1
vsc-workspace-sidebar|ske|1.1.9
vscode-todo-list|thi|1.0.4
Terminal-StatusBar|Tho|0.0.5
html-preview-vscode|tht|0.2.5
learn-vim|vin|0.0.27
vscode-icons|vsc|11.0.0
org-mode|vsc|1.0.0
whichkey|VSp|0.8.4
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30236573
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459:30237187

```

</details>

**Comment by sbatten** [comment]
please re-open if this occurs on recent builds
