### ISSUE TITLE
words are broken in terminal

### ISSUE THREAD

**Issue by anshumeena1947** [microsoft/vscode#113261]
- VSCode Version: November 2020 (version 1.52)
- OS Version: zorin os 15.3 (based on ubuntu 18.04)

i just update vs code to November 2020 (version 1.52) version and after that the words in the terminal are broken for example i create a file hello,world.py 
and after run the file in vs code integrated terminal then my aspect-ed output is
$ /usr/local/bin/python3 /home/anshu/Projects/coding/python/helloworld.py
hello world!

but vs code show me
$ /u r/l   o  a   l /b i n /p y  o   n 3   / o m e/  s h u /   o j   e c   s/c o d    n g/ t h o n / h e l      o r l d . p y 
he     w    r d!
$ 
what the bug is this?

Does this issue occur when all extensions are disabled?: Yes

here is the link of image please check out my screenshot
[screenshot of bug](https://pasteboard.co/JG2AYk9.png)

**Comment by anshumeena1947** [comment]
solve this issue i am not able to code in vs code i am waiting doe your replay

**Comment by meganrogge** [comment]
pls try changing the font and renderer type

**Comment by anshumeena1947** [comment]
oo thank you i change me vs code terminal renderer type to dom and after that i don't face any issue thank you mis meganrogge
