### ISSUE TITLE
compare selected bug

### ISSUE THREAD

**Issue by winner106** [microsoft/vscode#113263]
![vscode](https://user-images.githubusercontent.com/50519642/102845071-b1b92600-4447-11eb-894a-4638cff4d3f2.gif)

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.select two files
2.compare selected

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Not sure if this is a explorer issue or not.

**Comment by isidorn** [comment]
I can not reproduce this.
@bpasero can you repro
What are the exact steps? Do I need to have some files already open

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
