### ISSUE TITLE
quickSuggestions auto completes numbers with decimals

### ISSUE THREAD

**Issue by codism** [Microsoft/vscode#1132]
In the latest update (Version 0.10.3 (0.10.3) on Mac ), typing a number with a decimal autocompletes suggestions for other libraries in tsd.d.ts.

Example attached shows attempt to type "0.1" and "1.1"

"Power0" autocompletes with ease from tweenMax

Seems to be no way past this without removing quickSuggestions.

TSD has :
```typescript
    /// <reference path="greensock/greensock.d.ts" />
    /// <reference path="pixi.js/pixi.js.d.ts" />
    /// <reference path="createjs-lib/createjs-lib.d.ts" />
    /// <reference path="createjs/createjs.d.ts" />
    /// <reference path="easeljs/easeljs.d.ts" />
    /// <reference path="tweenjs/tweenjs.d.ts" />
    ///<reference path="requirejs/require.d.ts" />
```
![vs-code-autocomplete](https://cloud.githubusercontent.com/assets/4097335/11683880/b4e2c18e-9e65-11e5-8f6d-0403dfd978da.gif)

**Comment by joaomoreno** [comment]
Yes, this is quite bad. Duplicate of #1003
