### ISSUE TITLE
Breakpoints no longer working (TypeScript)

### ISSUE THREAD

**Issue by alecramsay** [microsoft/vscode#113236]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur (11.1)

Steps to Reproduce:

1. Open a TypeScript project -- breakpoints have worked forever, but
2. Set a breakpoint on code that runs
3. Start debugging that code

and the debugger no longer stops at the breakpoint (which obviously makes debugging difficult).

Note: Breakpoints in Python projects still work.

These are my dev dependencies from package.json -- we just upgraded our source map, TypeScript, and webpack dependencies:
```
  "devDependencies": {
    "@types/jest": "^26.0.14",
    "@types/node": "^12",
    "@types/yargs": "^12.0.12",
    "csv-parse": "^4.12.0",
    "jest": "^26.4.2",
    "json-loader": "^0.5.7",
    "prettier": "^2.1.2",
    "source-map-loader": "^1.1.3",
    "ts-jest": "^26.4.4",
    "ts-loader": "^8.0.12",
    "tsify": "^5.0.2",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "^4.1.3",
    "webpack": "^5.11.0",
    "webpack-cli": "^4.2.0",
    "yargs": "^12.0.5"
  }
```

Does this issue occur when all extensions are disabled?: Yes. Disabling extensions had no effect.

Thanks!

**Comment by connor4312** [comment]
/jsDebugLogs

The [new](https://code.visualstudio.com/updates/v1_52#_javascript-debugger) `Debug: Create Diagnostic Information for Current Session` command may also help you self-diagnose.

**Comment by alecramsay** [comment]
> /jsDebugLogs
> 
> The [new](https://code.visualstudio.com/updates/v1_52#_javascript-debugger) `Debug: Create Diagnostic Information for Current Session` command may also help you self-diagnose.

This command doesn't show up for me.

**Comment by alecramsay** [comment]
Trace log attached:

[vscode-debugadapter-6da077ab.json.gz](https://github.com/microsoft/vscode/files/5727729/vscode-debugadapter-6da077ab.json.gz)

**Comment by connor4312** [comment]
That command will only show up while a debug session is running.

In the log file, you have a breakpoint in:

- /Users/alecramsay/src/dra-graph/src/connected.ts
- /Users/alecramsay/src/dra-graph/cli/_cli.ts

In the first step, we scan for sourcemaps in the workspace that reference these files. connected.ts was found in `/Users/alecramsay/src/dra-graph/dist/dra-graph.bundle.js`, but the latter file was not found anywhere. Further when the program actually ran, the only two scripts included outside node_modules were

- `/Users/alecramsay/src/dra-graph/utils/main.js`
- `/Users/alecramsay/src/dra-graph/testdist/cli.js`

The latter had a sourcemap, but didn't include either of these two files.

So from what I can tell it looks like your build process either is not including the files you're interested in debugging, or it's not creating sourcemaps for them.

**Comment by alecramsay** [comment]
The fix was to add this to each configuration:

`"sourceMapPathOverrides": {
    "webpack://@dra2020/<project-name>/./*": "${workspaceFolder}/*",
  },`

It appears that webpack changed the sourcemap format it was writing in order to ensure it was correctly disambiguated, so when I upgraded the toolset we use, I also had to update the launch.json configurations.
