### ISSUE TITLE
Outline request

### ISSUE THREAD

**Issue by quang827** [microsoft/vscode#113284]
Issue Type: <b>Feature Request</b>

-Please add something to make the outline feature shows the local variables in a function !

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
Which language is this for?

**Comment by mjbvz** [comment]
Closing as not enough information was provided to investigate this further
