### ISSUE TITLE
Please do not put 'M' into the file tab title!

### ISSUE THREAD

**Issue by alvipeo** [microsoft/vscode#113239]
Issue Type: <b>Feature Request</b>

When file is modified locally, so its Git status is Modified. But the tab is not only has "modified" color but it also has "M" right next to the file name. This is really annoying and clutter the tabs

VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:33:38.481Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alvipeo** [comment]
Here's an example:

![Annoying M](https://inus.azureedge.net/temp/vs%20code%20problem.png?sv=2019-12-12&st=2020-12-21T16%3A43%3A35Z&se=2021-01-22T16%3A43%3A00Z&sr=b&sp=r&sig=WNJxLryZ0YCPfRE7xF67PhAFvL4ZILR8tCR%2B39OsOaM%3D)

**Comment by jrieken** [comment]
see https://github.com/microsoft/vscode/issues/49382#issuecomment-747288867

This is a new feature which is on by default (in insiders) to collect feedback. You feedback is noted

**Comment by dotspencer** [comment]
You can turn this off with `"workbench.editor.decorations.badges": false`

**Comment by alvipeo** [comment]
Thank you! But this should be off by default in my opinion.
