### ISSUE TITLE
Markdown hover no longer shown through extension since VSC 1.52

### ISSUE THREAD

**Issue by emicklei** [microsoft/vscode#113286]
- VSCode Version: 1.52.1
- OS Version: 10.15.7

Does this issue occur when all extensions are disabled?: No
Because this is behaviour added through an extension (Melrose).

Hi, I am the author of an extension that uses the Hover Provider API (see below for code snippet of its usage).

Since 1.44 up to version 1.51.1, the editor would show the Hover object that uses a vscode.MarkdownString.
Both the insiders version and versions 1.52+ no longer show this content despite the evidence (logging) that the provider is being called.

If I change the code to show a simple string, it does work!

```
return new vscode.Hover("help", range);
```

Please let me know if I need to provide more details (such as package versions etc).

Below the code that uses Hover with Markdown
```
	let disposable8 = vscode.languages.registerHoverProvider(
		{ scheme: 'file', language: 'melrose' }, {
		provideHover: async (doc: vscode.TextDocument, pos: vscode.Position): Promise<vscode.Hover> => {
			console.log("hover request");
			let range = doc.getWordRangeAtPosition(pos);
			let token = doc.getText(range);
			let response = await axios({
				method: 'post',
				url: 'http://localhost:8118/v1/inspect?debug=false',
				data: {
					token: token
				},
				headers: { 'Content-Type': 'text/plain; charset=UTF-8' }
			});
			if (!response || !response.data || !response.data.MarkdownString) {
				console.error("hover fail", response);
				return new vscode.Hover('');
			}
			console.log("hover data", response.data.MarkdownString);
			return new vscode.Hover(<vscode.MarkdownString>{
				value: response.data.MarkdownString,
				isTrusted: true
			}, range);
		}
	});
	context.subscriptions.push(disposable8);
```

**Comment by mjbvz** [comment]
Have you tried creating a new markdownstring instead of casting to one?

**Comment by emicklei** [comment]
@mjbvz just tried it and yes, now works. thanks!
