### ISSUE TITLE
Improve focus handling in notebooks

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#113246]
- [x] focus in large cells https://github.com/microsoft/vscode/issues/112096
- [x] investigate play button changes when the cell has focus (such as background color)
- [ ] polish focus colors in out-of-the-box themes

**Comment by greazer** [comment]
See comment I left in #112096 for a suggestion on default coloring for focused cells.

**Comment by misolori** [comment]
Closing issue as most are done, created https://github.com/microsoft/vscode/issues/117302 to track the default themes colors for notebooks.
