### ISSUE TITLE
NodeJs: Debugger not stopping at breakpoint (WSL2/Ubuntu18)

### ISSUE THREAD

**Issue by nhosko** [microsoft/vscode#113283]
Using WSL2/Ubuntu18 I've not been able to make the VSCode NodeJs Debugger to stop on the breakpoints of any NodeJs app. When I start the debugger, it runs (I can see the output on the integrated terminal) but breakpoints are simply ignored.

For test I have a very simple JS File with a breakpoint on line 3:
```
var x = 0
while (x < 5){
    console.log(x)
    x++
}
```
The launch.json is set to:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "NodeJs: Launch Program",
            "program": "${file}",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "console": "integratedTerminal"
        }
    ]
}
```
When I press F5 or click on the "Start Debugging" button on VS Code, the app runs and following appears on the integrated Terminal - ignoring the breakpoints:

```
/usr/bin/env 'NODE_OPTIONS=--require /home/myuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.19338-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/myuser/.nvm/versions/node/v14.15.1/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-ff32d873905abafa"}' /home/myuser/.nvm/versions/node/v14.15.1/bin/node ./simple.js 
Debugger attached.
0
1
2
3
4
Waiting for the debugger to disconnect...
```
I've already upgraded from Node10 to Node14, but the problem persists.

On another computer using WSL1, and using the same launch.json the debugger stops at the given breakpoints. Do I need to set something additionally on WSL2? For the record, this is what appears on the integrated terminal on the WSL1 computer before it stops at line 3:

```
/usr/bin/env 'NODE_OPTIONS=--require /home/myuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.787-3.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/myuser/.nvm/versions/node/v14.15.1/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-b901b6d6e3e9799b"}' /home/myuser/.nvm/versions/node/v14.15.1/bin/node ./simple.js 
Debugger attached.
<Breakpoint hit and stop...>

```

Additional info, debugging Python3 files work correctly on both machines.
Both computers have the same VS Code Version and the same Node Version installed.

**Comment by nhosko** [comment]
Added `"trace": true` to the `launch.json`,
Breakpoint added on code:
![image](https://user-images.githubusercontent.com/23018070/102923111-7b06fe00-448f-11eb-95ed-fd8412798005.png)

Debug started, script runs without stopping on breakpoints.

The requested `vscode-debugadapter-d037893a.json.gz` file has been sent by email to connor@xbox.com

Thanks.

**Comment by connor4312** [comment]
It looks like you have your script symlinked into `/bin/nhosko/simple.js`, but its actual location is `/mnt/c/Users/<snip>/bin-nhosko/simple.js`. In this case you need to specify some flags so that Node will report the linked location that vscode sees and told the debugger about: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_can-i-debug-if-im-using-symlinks. I want to make the debugger smart enough to fix this automatically in https://github.com/microsoft/vscode-js-debug/issues/776.

Let us know if you run into any more issues.

**Comment by nhosko** [comment]
Adding `"runtimeArgs": ["--preserve-symlinks", "--preserve-symlinks-main"]` on launch.json did not solve the issue.

I can confirm that when I open the workspace from its real direction (`/mnt/c...`) and not from the linked (`/bin/...`) the debugger stops at the breakpoint.

The launch.json looks currently like this:

```
        {
            "name": "NodeJs: Launch Program",
            "program": "${file}",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "console": "integratedTerminal",
            "runtimeArgs": [
                "--preserve-symlinks",
                "--preserve-symlinks-main"
            ]
        }
```

**Comment by connor4312** [comment]
Okay, thanks for confirming. There are some cases where those flags don't work (I think when the cwd is in the symlink'd folder, rather than just 'calling into' a symlinked path). As part of the linked issue, I want to fix that, so I will close this as a duplicate.

Hoping to have a fix/mitigation this month.
