### ISSUE TITLE
Failed to launch

### ISSUE THREAD

**Issue by Sushil-biz-insights** [microsoft/vscode#113268]
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" failed to launch (exit code: 4294901760).

**Comment by Sushil-biz-insights** [comment]
Still same problem

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
