### ISSUE TITLE
notabstitlecontrol.css contains tab specific rules?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113217]
Not sure I misunderstand the `tabs-breadcrumbs` rule, but I noticed that `notabstitlecontrol.css` contains rules that seem to be tab specific, e.g. 

https://github.com/microsoft/vscode/blob/4efb4a2e8dbfe8a6a7dbd8269bfc4034e1c21907/src/vs/workbench/browser/parts/editor/media/notabstitlecontrol.css#L88-L88

I typically keep rules that are shared between tabs and no-tabs in `titlecontrol.css` because that one will be loaded in both cases of tabs enabled or disabled. And I only keep rules that are specific to no-tabs or tabs-enabled in the related CSS files.

**Comment by jrieken** [comment]
@misolori I believe this came in with https://github.com/microsoft/vscode/commit/235f8512433e42f7cea9d2befa565c026bea592f

**Comment by misolori** [comment]
I added those because there were other breadcrumb rules related to when tabs are off. Happy to move these to the breadcrumb file:

https://github.com/microsoft/vscode/blob/cfccae30dbf7e65d472475a568dbd828051c0336/src/vs/workbench/browser/parts/editor/media/notabstitlecontrol.css#L33-L90

**Comment by bpasero** [comment]
Since I was in this place for some cleanup, I took care of it.

**Comment by jrieken** [comment]
thanks
