### ISSUE TITLE
Continue should have priority over Start Debugging while debugging is active

### ISSUE THREAD

**Issue by mpunak** [microsoft/vscode#113242]
Issue Type: <b>Bug</b>

Running VSCode against Brave browser with chrome debugging plugin causes hotkeys not to work properly. Specifically, once a breakpoint is hit, the f5 hotkey to "Continue" becomes enabled without disabling the menu option to  "Start Debugging", which also uses the f5 hot key. Both options visible and enabled under "Run" menu.

<img width="279" alt="Screen Shot 2020-12-21 at 10 07 38 AM" src="https://user-images.githubusercontent.com/6179773/102803518-98e04000-4375-11eb-9aa8-90cce69eede0.png">

Hitting F5 causes VSCode to display a growl message saying "there is already a debug configuration running" rather than the expected Continue behavior when sitting at a breakpoint.
<img width="456" alt="Screen Shot 2020-12-21 at 10 17 54 AM" src="https://user-images.githubusercontent.com/6179773/102803661-d349dd00-4375-11eb-8a98-b45f2212aaed.png">

Reverting to debugging against a Chrome browser seems to now produce the same broken result for me.

My workaround is to use the arrow option on the debug menu to continue.
<img width="219" alt="Screen Shot 2020-12-21 at 10 17 00 AM" src="https://user-images.githubusercontent.com/6179773/102803589-b0b7c400-4375-11eb-8f30-e41531a6264a.png">

My debug launch.json block:
` {
            "type": "chrome",
            "request": "attach",
            "name": "BRAVE",
            "urlFilter": "https://localhost:4200/*",
            
            // "url": "https://localhost:4200",
            "port": 9223,
            "webRoot": "${workspaceFolder}"
        },` 

My Brave launch command line:
`/Applications/Brave Browser.app/Contents/MacOS/Brave Browser' --user-data-dir=/Users/dev/.bravedebug --remote-debugging-port=9223 https://localhost:4200?debugger=connect`

My Brave version: Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)

Extension version: 4.12.11
VS Code version: Code - Insiders 1.53.0-insider (c927a8015b9e26bd454d6e293bb0384aa1975d06, 2020-12-18T05:27:22.865Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 4.4.0-1118-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.21GB free)|
|Process Argv|--crash-reporter-id a43b3ddf-bf1d-4e67-9b4c-7ed03f9fd16e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vfp|
|OS|Linux x64 4.4.0-1118-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (2 x 2699)|
|Memory (System)|14.93GB (12.45GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by kborowinski** [comment]
I'm experiencing the same issue on latest _VSCode Insiders_ version.

**Comment by n8sabes** [comment]
This is a * **PAINFUL** * situation here too debugging against Edge and it's been driving me crazy. Every time I hit F5 to continue, it generates the error and I have to move to the mouse to click the play icon. 🤬

Any help or or workarounds are welcome.

MacOS X Big Sur 11.1
Edge 87.0.664.66
VS Code Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:32:43.927Z (1 wk ago)
Electron: 11.1.0
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.2.0

**Comment by n8sabes** [comment]
Here is a temporary workaround idea that is less painful. Change **Start Debugging** to CONTROL + OPTION + COMMAND + F5.

![image](https://user-images.githubusercontent.com/10445528/103472104-250f4180-4d3e-11eb-95d4-dbe843a3b43e.png)

**Comment by isidorn** [comment]
Sorry about this breakage and slow response I was on vacation. I will look into a fix today or tomorrow.

**Comment by jvesouza** [comment]
I changed F5 to ctrl+f9.

**Comment by gvanrossum** [comment]
I think I hit the same thing with the Python debugger: https://github.com/microsoft/vscode-python/issues/15081
The Debug panel advertises F5 as the shortcut to continue (and so does the official keyboard shortcuts sheet from http://aka.ms/vscodekeybindings) but I get an error that a debug session is already running.

**Comment by gvanrossum** [comment]
I'm not sure if this is the right place to ask a question like this, but I'm just curious; there's an example in http://aka.ms/vscodekeybindings that suggests this can be done with conditions:
```
// Keybindings that are complementary
{ "key": "f5",              "command": "workbench.action.debug.continue", "when": "inDebugMode" },
{ "key": "f5",              "command": "workbench.action.debug.start",    "when": "!inDebugMode" },
```
Is that documentation out of date or is the issue that the debug panel key bindings use a different mechanism? (And if so, why?)

**Comment by isidorn** [comment]
This can be fixed with the condition correct.
However the default should just work and user should not have to fix anything.

**Comment by jvesouza** [comment]
I just did a test and everything is working as expected.
Thanks.

**Comment by isidorn** [comment]
@jvesouza thanks, adding verified label!
