### ISSUE TITLE
Replace not working

### ISSUE THREAD

**Issue by 161134077** [microsoft/vscode#113234]
Version: 1.52.1 (user setup) 
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:50.160Z (4 days ago)
Electron: 9.3.5
Chrome 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows NTia32 10.0.18363

file format .txt find text: "/" not results 
![bug replace](https://user-images.githubusercontent.com/39833970/102794784-70d8f700-43de-11eb-81a7-b48a21b6f687.JPG)

**Comment by ArturoDent** [comment]
It looks like you have the `Find in Selection` option enabled (next to the close `X`) but no selection in the shown text - if there is no selection then nothing will ever be found if that option is enabled.

**Comment by 161134077** [comment]
I used `find in selection` @ArturoDent  Thanks
