### ISSUE TITLE
Support update npm dependencies in package.json.

### ISSUE THREAD

**Issue by LeuisKen** [microsoft/vscode#113281]
Since we can see the latest version when hover, why not support upgrade dependencies directly.

![image](https://user-images.githubusercontent.com/7701575/102870203-ad0c6600-4477-11eb-9f68-59bd73820cd9.png)

Maybe just add some code actions here will be okay.

**Comment by mjbvz** [comment]
Possibly an extension candidate. Assigning you @egamma since I think you were still maintaining out npm scripts support
