### ISSUE TITLE
Launching from command line disables ability to launch from shell

### ISSUE THREAD

**Issue by codefoster** [Microsoft/vscode#11324]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:
1. Right click in any Windows Explorer window and Open in Code. It works.
2. Close Code.
3. Now run `code .` from any directory at the command line. VS Code will launch.
4. Now try step 1 again and Code will no longer launch. Same behavior for launching either files or folders or opening any files with Code as associated handler.

cc: @danielegan

**Comment by joaomoreno** [comment]
This has been fixed.

**Comment by DanielEgan** [comment]
@joaomoreno do you know when this will roll into production?

**Comment by joaomoreno** [comment]
@DanielEgan On which version can you still reproduce?
