### ISSUE TITLE
Source Controle pannel Can't check conflicts detail.

### ISSUE THREAD

**Issue by chokingwin** [microsoft/vscode#113258]
When i merge dev branch to master,they are some conflicts happened.
But i can't check the detail of these conflicts in Source Controle pannel.

**Comment by inmativ** [comment]
У меня аналогичная проблема. При этом я могу открывать файлы через встроенный файловый менеджер и разрешать конфликты. Но сама панель контроля версий не работает. Проблема воспроизводится на другой синхронизированной машине. Отключение всех дополнений не помогает.

**Comment by winlx** [comment]
https://github.com/microsoft/vscode/issues/112717#issuecomment-749321371

**Comment by eamodio** [comment]
Duplicate of #112537 (which will be fixed in tomorrow's insiders)
