### ISSUE TITLE
Set editor font family

### ISSUE THREAD

**Issue by dragonDScript** [microsoft/vscode#113240]
In Linux, the font used in the editor if you are using the custom style, looks very weird (Ubuntu, sans-serif, in Ubuntu 20.04).
It would be very cool to add an editor font setting, that if null, would be overwritten by the OS's font.
![image](https://user-images.githubusercontent.com/46191980/102802455-f5b01a80-43b6-11eb-8bd5-be66494fa8c4.png)
*I'm not asking for fontsize, only font-family

**Comment by dragonDScript** [comment]
This is not a duplicate. I'm talking about the UI's font, not Monaco Editor's font.

**Comment by dragonDScript** [comment]
#86542

**Comment by dragonDScript** [comment]
#519

**Comment by sweettyler** [comment]
This is a request for font setting in Find/Replace box:

https://github.com/microsoft/vscode/issues/101064

**Comment by misolori** [comment]
This falls under https://github.com/microsoft/vscode/issues/519 for setting changing the default font family. Please upvote that issue and subscribe to get updates.
