### ISSUE TITLE
Jupyter NoteBook

### ISSUE THREAD

**Issue by code-zz** [microsoft/vscode#113264]
Issue Type: <b>Bug</b>

In VS Code's Jupyter NoteBook, using Python3's seaborn package to draw a pairplot, VS Code cannot be displayed normally and a black screen appears.

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (10.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
vscode-language-pack-zh-hans|MS-|1.48.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.9.114305
remote-ssh|ms-|0.61.0
remote-ssh-edit|ms-|0.62.0
vscode-yaml|red|0.13.0

</details>

**Comment by rebornix** [comment]
/extJupyter 

Let's start our investigation from the Jupyter extension
