### ISSUE TITLE
Miscolored #if and #endif preprocessor directives in initializer list of struct constructor definition

### ISSUE THREAD

**Issue by ClydeHobart** [microsoft/vscode#113204]
Issue Type: <b>Bug</b>

The following code snippet, when viewed in VSCode, has miscolored `#if` and `#endif` preprocessor directives around the `, bar(0)` line in the initializer list of the `SSomeStruct` struct default constructor definition.
```
#include <iostream>

#define SOME_MACRO 1

struct SSomeStruct {
	// Functions
	SSomeStruct() :
		foo(0)

		#if SOME_MACRO
			, bar(0)
		#endif // SOME_MACRO
	{}

	// Variables
	public:
		int foo;

		#if SOME_MACRO
			int bar;
		#endif // SOME_MACRO
};

int main() {

	SSomeStruct someStruct;

	std::cout << someStruct.foo << ' ' << someStruct.bar << std::endl;

	return 0;
}
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.58GB free)|
|Process Argv|--crash-reporter-id 831a3e34-55dc-40bc-9bc5-c822bd469494|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.89GB (7.58GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.52.0
mono-snippets|zra|0.0.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by alexr00** [comment]
Moved to the repository that our C++ grammar comes from: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/528
