### ISSUE TITLE
When developer tools are pinned to the left and custom title bar is used, some menu items in developer tools are not clickable.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#113274]
- VSCode Version: 1.52.1
- OS Version: Windows 7

Steps to Reproduce:

1. Set title bar style to custom and maximize the VS Code window.
2. Open developer tools and pin to left.
3. Some of the menu items are not clickable, but instead behave as part of the title bar.

https://user-images.githubusercontent.com/8168391/102863601-c7414680-446d-11eb-8ad9-91237c4afd29.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Unable to repro with recent versions.
