### ISSUE TITLE
invalid mystery character in python file

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode#113251]
Issue Type: <b>Bug</b>

This code fails with a syntax error
 ```
class ModelAnomalies (object):
    ''

    def reset_models(self):
        ''
	pass
```
        def reset_models(self):
    ^
SyntaxError: invalid character in identifier

The code was pasted from PowerPoint.  The mystery character causing the error cannot be deleted, and moves as text is inserted before and after it. 

Presumably there's an encoding error with the file format - not sure this code example will fail as mentioned, but copy-paste from this window into VS code will fail. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:50.160Z)
OS version: Windows_NT ia32 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.99GB free)|
|Process Argv|--crash-reporter-id 4d1bdb97-1b1b-4775-a0da-165d721a49b5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-converter|man|3.1.2
rainbow-csv|mec|1.8.0
vscode-azurefunctions|ms-|1.1.0
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-ai|ms-|0.6.19
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
wordcount|rid|0.1.33
vim|vsc|1.18.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
pythonvspyt617cf:30237717
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630

```

</details>

**Comment by IllusionMH** [comment]
@jmagosta PowerPoint might use `0xa0` characters https://www.fileformat.info/info/unicode/char/00a0/index.htm if you copy content from it. Or other like paragraph separator or something similar etc.

It will be pasted as is in most places not only into VS Code, so it's better to remove whitespaces and trigger formatter after you paste content from PowerPoint.

Not sure if it's VS Code issue that it accepts content that is pasted and doesn't replace characters "randomly".
You can try to check pasted content with extension like https://marketplace.visualstudio.com/items?itemName=nachocab.highlight-dodgy-characters to see if come control characters were pasted.

**Comment by jmagosta** [comment]
@IllusionMH  Exactly - "highlight dodgy characters" lit the code up like a Christmas tree.  A global replace with spaces fixed it all. Maybe there's a feature request to have the VS Code python linter make more of a fuss - since it does give the squiggly underline when it first encounters the bad spaces.

**Comment by IllusionMH** [comment]
In my case for JS/TS using built-in formatter it removed there extra characters after <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>
![image](https://user-images.githubusercontent.com/1312662/102889195-dff82f00-4462-11eb-85e4-4c1288628761.png)
So my routine is: paste code, trigger format, edit as usual.

Maybe Python formatter can do same.
