### ISSUE TITLE
remote php.validate.executablePath

### ISSUE THREAD

**Issue by JStiller** [Microsoft/vscode#11328]
Today everyone is using virtual environments. In my case, i need to maintain a mass of microservices which got diffrent configurations. Espacialy the php version in combination with diffrent extensions.

Therefore i would like to execute the php, which is located on the virtual machine! To make that happen i need the ability to configurate that.

**Comment by dbaeumer** [comment]
@chrisdias @egamma FYI.

**Comment by Thavarajan** [comment]
i think this [extention](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug) usefull

**Comment by JStiller** [comment]
Thanks for the advice. I'am already using that extension. But that doesn't solve the reported feature request.

Actually i'am forced to install PHP with every extension including the configs on my local machine, to use the benefits which are provided by php.validate.executablePath. But it shouldn't be necessary because the needed PHP with every extension including the configs are already installed and configured on the virtual machine. That way i have to maintain two environments for one. And if you got multiple environments things get really complicated.

**Comment by roblourens** [comment]
I'm not sure how we could use PHP on the remote machine (which has its own environment and may be a different OS, etc). Do you know if this is done for any other languages?

**Comment by fresnizky** [comment]
It would be great if you can support this feature to setup a PHP executable running in a Docker container

**Comment by JStiller** [comment]
And also in Vagrant.

**Comment by roblourens** [comment]
The builtin PHP support is very simple, I recommend using a PHP extension and requesting this support there. Unless anyone has a simple idea of how this could work.
