### ISSUE TITLE
Context menus leave the cursor in the wrong state after exit

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#113230]
- VSCode Version: 1.53
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Right-click somewhere, such as the editor window, to make the context menu appear.
2. Click somewhere else to make the context menu go away.
3. The cursor stays as a default cursor and does not return to the appropriate cursor type for that section.

Does this issue occur when all extensions are disabled?: Yes

**Comment by thebinarysearchtree** [comment]
This will fix both this and the other issue related to quick fixes:

```
export function popup(items: IContextMenuItem[], options?: IPopupOptions, onHide?: () => void): void {
	const processedItems: IContextMenuItem[] = [];

	const contextMenuId = contextMenuIdPool++;
	const onClickChannel = `vscode:onContextMenu${contextMenuId}`;
	const styleSheet = document.createElement('style');
	styleSheet.innerText = '* { cursor: default !important }';
	const onClickChannelHandler = (event: unknown, itemId: number, context: IContextMenuEvent) => {
		const item = processedItems[itemId];
		if (item.click) {
			item.click(context);
		}
	};

	ipcRenderer.once(onClickChannel, onClickChannelHandler);
	ipcRenderer.once(CONTEXT_MENU_CLOSE_CHANNEL, (event: unknown, closedContextMenuId: number) => {
		if (closedContextMenuId !== contextMenuId) {
			return;
		}
		styleSheet.remove();
		ipcRenderer.removeListener(onClickChannel, onClickChannelHandler);

		if (onHide) {
			onHide();
		}
	});
	document.head.appendChild(styleSheet);
	ipcRenderer.send(CONTEXT_MENU_CHANNEL, contextMenuId, items.map(item => createItem(item, processedItems)), onClickChannel, options);
}
```

**Comment by thebinarysearchtree** [comment]
I was expecting 'menu-will-show' and 'menu-will-close' events from the native menu, but it appears these are instantiated via a call to another process. These events could be inserts instead of the stylesheet code, and then event listeners could be added elsewhere. The bug here appears to be that for whatever reason, the context menu does not return the cursor to its appropriate state unless you force a change in the cursor style that makes the browser re-evaluate what the style should be. This is why you can move your mouse over another element with a different cursor style and the problem goes away.

**Comment by bpasero** [comment]
Not sure if this is upstream, given https://github.com/electron/electron/issues/27129

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/97864
