### ISSUE TITLE
the VSC window keeps reloading ceaselessly. no operation can be done.

### ISSUE THREAD

**Issue by UNS2406** [microsoft/vscode#113287]
- VSCode Version: 
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (5 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 17.7.0

- OS Version: maOS high sierra 10.13.6

Steps to Reproduce:

1. just launch the VSC window
2.  it was working fantastic,
3. but, of nowhere, everything got disturbed
4. reinstalling does not work.
5. even after installing, I do not receive fresh settings

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> the VSC window keeps reloading ceaselessly. no operation can be done

Can you describe that in more details?
