### ISSUE TITLE
multi-line indent doesn't indent empty lines

### ISSUE THREAD

**Issue by xaxazak** [microsoft/vscode#113288]
- VSCode Version: 1.52.1
- OS Version: Linux (Xubuntu 20.10)

Steps to Reproduce:

1. Select two or more lines of code including at least one empty line (can be all empty).
2. Press tab.
3. The empty lines are not indented.

This may be intentional. If so, there should be an option to indent empty lines.
Usage examples: Moving multiple code items (eg functions) from global scope to class or namespace scope - the line gaps (empty lines) between items should be indented to the level of their new scope.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joeshaw** [comment]
I am seeing this as well.  I started to file a new bug report, but I'll add my details here.

- VS Code Version: 1.55.1
- OS Version: Darwin x64 20.3.0

This issue isn't limited to JSON, but it's an easy repro case.  Suppose you have a JSON document:

```
  12345
1 {
2     "hello": "world",
3
4
5     "goodbye": "for now"
6 }
```

Note that in this document, both lines 3 and 4 are completely blank.  No whitespace is on either line.

If you are anywhere on line 3 and run `reindentSelectedLines`, your cursor is moved to column 5.  This is good, and what I would expect.

If you are anywhere on line 4 and run `reindentSelectedLines`, your cursor is moved to column 1.  I would have expected it to be placed at column 5.

If line 3 has whitespace in it, then hitting tab on line 4 will indent to align with line 3.  I would still expect it to indent to column 5.

If you hit `Enter` on line 3, a new line is inserted and the cursor is indented to column 5.  So it seems like VSCode has the ability to indent to the correct place, but whatever the algorithms are between inserting a blank line and "reindent selected lines", they don't match up.


Does this issue occur when all extensions are disabled?: Yes

Related: https://github.com/sakapoko/vscode-emacs-indent/issues/1
