### ISSUE TITLE
Conflict w/ "Nahimic Service" (audio driver service) causes slow (~20 sec) startup times for VSCode. 

### ISSUE THREAD

**Issue by corylulu** [microsoft/vscode#113360]
As mentioned here (https://github.com/microsoft/vscode/issues/22087#issuecomment-735281920), the "Nahimic Service.exe" installed on many systems using Nahimic audio drivers causes VSCode very slow (~20 seconds) startup times. 

- VSCode Version: 1.52.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Have Nahimic audio drivers installed and Nahimic Service running
2. Open VS Code
3. Wait 20 seconds for it to load... then close
4. Stop "Nahimic Service" in Task Manager
5. Open VS Code
6. Starts instantly. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
can you provide `chrometrace.log` following the steps below,

* Create trace.json somewhere on your disk with the following content:

```
{
 "result_file": "<some-absolute-writable-path>\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "browser",
     "io",
     "ipc",
     "content",
     "renderer",
     "renderer_host",
     "latency",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "input",
     "disabled-by-default-renderer.scheduler"
 ],
 "excluded_categories": ["*"]
 }
}
```

* Start code --trace-config-file="<absolute-path-to>\trace.json"
* Once the app is loaded and workbench is ready
* Quit the editor
