### ISSUE TITLE
Emmet: svg abbreviations dont work

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#11333]
**Update**: We can now support svg abbreviations but only after mapping the current language mode to "svg" in `emmet.syntaxProfiles` setting.

We should investigate having `svg` as an embedded language like we do for `html` inside `jsx`

Testing #11139
- VSCode Version: 1.5.0- Insiders (dated 8/31)
- OS Version: Windows 10

Steps to Reproduce:
1. Create `svg` file. Type `gl` and hit `TAB`

As per the abbreviations in [lib/snippets.json#L892](https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L892), `gl` should have expanded to `<glyph>`
Instead, it expands to `<gl></gl>`

Same result with other abbreviations for `svg`

Similarly, if you associate any language with `svg` syntax profile, you cannot get any abbreviations expansion.

**Comment by ramya-rao-a** [comment]
This might be because the `svg` files are associated with `xml` language mode. 

Other file types like `haml`, `slim`, `sass`, `styl` and `stylus` have `plaintext` as their language mode. But none of these have any extra abbreviations or snippets like `svg`. Therefore one can set `xml` or `css` as language mode for these file types to get xml/html emmet features.

But `svg` has loads of extra emmet abbreviations that we are losing out on.

**Comment by mrmlnc** [comment]
@ramya-rao-a,

Unfortunately, we do not support SVG with Emmet.

VS Code used Emmet v1.3.1 (see [package.json#L19](https://github.com/Microsoft/vscode/blob/master/package.json#L19)), but support for SVG in Emmet was added in version (see [emmet/6efa2234cd3a72a9bd1232fa79783a878d556107](https://github.com/emmetio/emmet/commit/6efa2234cd3a72a9bd1232fa79783a878d556107)).

More details on this issue: https://github.com/Microsoft/vscode/pull/9002#issuecomment-234944128.

**Comment by ramya-rao-a** [comment]
With #19655 we can now support svg abbreviations but only after mapping the current language mode to "svg" in `emmet.syntaxProfiles` setting.

We should investigate having `svg` as an embedded language like we do for `html` inside `jsx`

**Comment by ramya-rao-a** [comment]
Closing this issue as there is no sufficient interest from the community in getting this done.
We can revisit if there is any interest in the future
