### ISSUE TITLE
"editor.formatOnSaveMode": "modifications" doesn't work

### ISSUE THREAD

**Issue by andreyohiienko** [microsoft/vscode#113361]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Without `"editor.formatOnSaveMode": "modifications"` formatting works fine.
https://www.screencast.com/t/sT8wL2OmR

With `"editor.formatOnSaveMode": "modifications"` formatting doesn't work on save, only on "Format Document" or "Format Selection".
https://www.screencast.com/t/CqSPjfUbY

P.S. it doesn't work in js, ts files too.

Steps to Reproduce:

1. Set "editor.formatOnSaveMode": "modifications"
2. Set "editor.formatOnSave": true.
3. Enable only Prettier - Code formatter extension.
3. Enable source control.
4. Make changes in file.
5. Save.
6. See no formatting.

Does this issue occur when all extensions are disabled?: Yes

Also I saw [107940](https://github.com/microsoft/vscode/issues/107940) and [106450](https://github.com/microsoft/vscode/issues/106450) issues.

**Comment by Gameghostify** [comment]
This is because the extension (in this case Prettier) needs to support the "modifications" formatOnSaveMode as well

Right now prettier doesn't support it 😕
