### ISSUE TITLE
Extension Host Crashes during Chrome Debugging

### ISSUE THREAD

**Issue by HarleyCoegil** [microsoft/vscode#113368]
Issue Type: <b>Bug</b>

A few times a week my extension host will crash during Chrome debugging. 
I kill the browser but VS Code thinks that it is still debugging something.
I click the red box to stop debugging and nothing happens.
I have to kill Vs Code and restart to get it back to a stable state.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|16, 11, 7|
|Memory (System)|8.00GB (0.51GB free)|
|Process Argv|. --crash-reporter-id 84448663-c496-4e91-9cc5-fb82d310bc2a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-toggle-quotes|Bri|0.3.3
scratchpads|bue|0.0.7
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
jsrefactor|cms|2.20.6
vscode-devtools-for-chrome|cod|0.0.7
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
multi-file-renamer|dan|1.0.0
angular2-snippets|dan|1.0.21
dart-code|Dar|3.17.1
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.0.6
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vscode-statusbar-debugger|fab|2.0.6
vscode-firefox-debug|fir|2.9.1
auto-rename-tag|for|0.1.5
debugger-for-phantomjs|ira|0.1.1
batch-rename-extension|Jan|0.0.3
search-node-modules|jas|1.3.0
ReplaceWithNewline|jma|0.0.1
vscode-peacock|joh|3.9.1
intellij-idea-keybindings|k--|0.2.41
chat|kar|0.35.0
vscode-commitizen|Kni|0.9.3
graphql-for-vscode|kum|1.15.3
syntax-project-pbxproj|mar|0.1.3
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
resharper9-keybindings|ms-|1.1.0
vsliveshare|ms-|1.0.3375
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
typescript-hero|rbb|3.0.0
java|red|0.73.0
copy-copy-paste|roc|0.0.7
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.13.0
change-case|wma|1.0.0
vscode-surround|yat|1.0.2
markdown-all-in-one|yzh|3.4.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30239448

```

</details>

**Comment by connor4312** [comment]
Thanks for the issue. Do you notice any patterns before it crashes? For example, are there particular actions you take while debugging, do you notice high memory/CPU usage?

**Comment by HarleyCoegil** [comment]
I'll pay more attention to the CPU and memory usage. I am working on an Angular project with a lot of modules. 
My general workflow is to start the angular local server and launch chrome via the debugger. 
I'll work on developing features and fixing bugs with the debugger running so that I can see changes in the browser and the logs in VS Code. If I am working further down the stack I will open up Chrome Dev tools to see the network traffic. Having the Chrome Dev tools open may be a contributing factor as the two debuggers will attempt to take focus when breakpoints are hit. 

I notice that VS code has gotten into a bad state when "Go To Definition" and Intellisense stops working. At that point, I'll try to kill the debugger to shut down normally and see that the debugger won't detach even if the browser window is gone.

I hope that helps. Let me know if there are logs or another telemetry that I can provide.
