### ISSUE TITLE
[scss] resolve paths relative to node_modules in scss files

### ISSUE THREAD

**Issue by massimo-cassandro** [microsoft/vscode#113308]
Issue Type: <b>Feature Request</b>

In js / ts I can import a file using a path relative to the node_modules folder. The path is also clickable and is a very quick way to open the file.

A similar option in scss files would be really useful

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

**Comment by aeschli** [comment]
Can you provide a scss code snippet that shows such an import?

**Comment by massimo-cassandro** [comment]
Hi,
I've created a little gif screenshot to better explain what I mean:

![js](https://user-images.githubusercontent.com/1047169/103642653-c3282500-4f53-11eb-9ae4-0be7f4dae481.gif)

It represent what I have in js/ts when importing a file from node_modules: I'have not to specify the path from my file to the the node_modules folder, and in addition the path is clickable (pressing CMD or CTRL) 

In scss I don't have a similar behavior. 
Since I use an external tool to compile my scss ([codekit](https://codekitapp.com/)) which has the ability to resolve node_modules paths, I can import and compile my scss files using the path relative to the node_modules folder, but it is not possible to open that file by cmd/ctrl-clicking the path:

```scss
@import 'glightbox/dist/css/glightbox'; // path from node_modules folder, codekit compiles it to css but I can't cmd-click it 
```

Maybe I have not correctly set some parameters in my VSCode configuration or that there is a plugin that allows this, but I could not find anything.

Thanks

**Comment by aeschli** [comment]
I suspect that this works using the [load paths](https://sass-lang.com/documentation/at-rules/import#load-paths) that scss supports.

We don't have support for that in the VSCode css/scss service. If someone is interested to add support for that, help is welcome!

What we have is support for `~` imports as defined by the css-loader webpack-plugin: https://github.com/webpack-contrib/css-loader#url. Not sure if that helps you.
