### ISSUE TITLE
Github OAuth authentication

### ISSUE THREAD

**Issue by OPVL** [microsoft/vscode#113388]
Issue Type: <b>Bug</b>

When attempting to sign in (created a new branch that didn't exist on origin repo & push to remote)

Opens browser at github authorize page, after clicking authorize it returns a forbidden message and does not pass back in vscodium

Debian Bullseye
VSCodium (latest stable)

VS Code version: VSCodium 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-17T00:37:39.556Z)
OS version: Linux x64 5.9.0-4-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 2942)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (5.92GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.4.0
vscode-intelephense-client|bme|1.5.4
laravel-goto-view|cod|1.3.3
php-debug|fel|1.13.0
php-pack|fel|1.0.2
vscode-docker|ms-|1.9.0
laravel-blade|one|1.25.0
material-icon-theme|PKi|4.4.0
vscode-blade-formatter|shu|0.6.3

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
We don't support auth with VSCodium
