### ISSUE TITLE
Native Notebooks - Tags not rendered in markdown cells

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#113351]
From Jupyter issue:

I believe that not all tags are being rendered in markdown cells. Img tags are quite useful in notebooks but they seem to be missing in the cell preview mode:

![2020-12-22_21-31-37 (1)](https://user-images.githubusercontent.com/9402690/102926164-397d4f80-449d-11eb-8a86-2fe98e17a9de.gif)

_Originally posted by @roma-glushko in https://github.com/microsoft/vscode-jupyter/issues/4261#issuecomment-749735862_

**Comment by mjbvz** [comment]
To test:

1. Set `"notebook.experimental.useMarkdownRenderer": true`
2. Reload VS Code
3. Create a markdown cell with some html, such a as `<b>bold</b>`
4. Confirmed that it is rendered
