### ISSUE TITLE
Hash Mismatch While Updating VS Code from 1.47.3 to 1.52.1

### ISSUE THREAD

**Issue by MaisGurbanov** [microsoft/vscode#113350]
Issue Type: <b>Bug</b>

When I click on the "Manage" button and select the "Check for Updates..." option, there is an error pop-up message such as "Hash Mismatch".

VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
Do you still get this error?
