### ISSUE TITLE
Switching Python Environment Doesn't Work

### ISSUE THREAD

**Issue by mbentley00** [microsoft/vscode#113356]
I can't get VSCode to consistently switch to a different Python environment. I load the interpreter selecter for the entire workspace. Then I choose my conda environment. But even after restarting when I go to debug it still uses a previously set conda environment.

And even the environment it tries to activate (the wrong one) gives me an error like this:

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

**Comment by meganrogge** [comment]
Closing this as it seems like a generic python environment setup question.
