### ISSUE TITLE
html-language-features formatting started doing things it wasn`t doing before

### ISSUE THREAD

**Issue by pokermanx** [microsoft/vscode#113386]
- VSCode Version: 1.52.1
- OS Version: Windows 10, 20H2

Steps to Reproduce:
Just Format your html.

Does this issue occur when all extensions are disabled?: Yes

This started happening yesterday/today, I am using `"editor.defaultFormatter": "vscode.html-language-features"`.
`"html.format.wrapAttributes": "force-aligned"` worked perfectly, it touched tag attributes and was doing nothing to tag content (I'm writing in Angular so its perfect for me) until today. Content started to wrap in places I don't want it to wrap in, I just want it to be preserved as it is. Everywhere. `"html.format.wrapLineLength": 0` isn't helping, as so `html.format.contentUnformatted` doesn't (when I start to add some tags there - everything breaks). I need a solution for this.

Just an example what it does to a ternary operator;
![image](https://user-images.githubusercontent.com/36159194/103092131-ec18f380-45fe-11eb-9471-774e94e3c972.png)
![image](https://user-images.githubusercontent.com/36159194/103092210-339f7f80-45ff-11eb-8be9-41a5e19fe3d1.png)

**Comment by aeschli** [comment]
We updated the version of the HTML formatter which is jsbeautify.

Can you try if `"html.format.templating": true` solves the problem?
