### ISSUE TITLE
VSCode href link to html in local folder does not work

### ISSUE THREAD

**Issue by DonZheng** [microsoft/vscode#113304]
While editing a html based on a working template, below issue occurs:
Existing href refs to other html file within the same folder works fine
More html files added to the folder, then created new href link to the newly created file:
1. If manually type the complete href, it works.
2. If copy existing working href then update it to point to newly created file, it works.
3. If generate href links outside of vscode then paste into vscode, it **DOES NOT** work

Tried disabling all extensions, restarting vscode. Can not solve the issue.

Kindly advise if I have missed anything here.

Thanks

![image](https://user-images.githubusercontent.com/40833875/102911735-921a1000-44d0-11eb-9993-09c59b405c44.png)

**Comment by aeschli** [comment]
Is it a rendering issue? Does the underline show when reopening the editor?
Can you provide the html file?
