### ISSUE TITLE
option to only show autocomplete suggestions after N characters

### ISSUE THREAD

**Issue by xaxazak** [microsoft/vscode#113305]
I suggest not displaying autocomplete suggestion lists until a minimum number of characters is typed. This minimum should be configurable in user settings, and should default to 1 (where it would have no effect).

To me, having autocorrect lists show up after a single character seems excessive and very distracting. I would probably opt for 3 or 4.

From googling, this seems a fairly common request (or feature) in other editors, and it seems like it would be popular and shouldn't be too hard to implement.

**Comment by jrieken** [comment]
Worth trying to workaround this: increate the delay for quick suggestiosn via the `editor.quickSuggestionsDelay` setting

**Comment by xaxazak** [comment]
Thanks - I tried but mostly it just shifts the problem - I'm either waiting on it after typing quickly or it's still appearing after 1 slow-typed letter - plus IMHO it's harder to train muscle memory with a fixed time.
