### ISSUE TITLE
Provide a homeDir system variable for use in launch.json

### ISSUE THREAD

**Issue by aaronblythe** [Microsoft/vscode#11337]
- VSCode Version: 1.2.1
- OS Version:  OSX 10.10 and OSX 10.11

Steps to Reproduce:

1. Folow tutorials on creating .vscode/launch.json 
2. Set paths that start at the Home Directory (eg: %USERPROFILE% on Windows, $HOME / ~ on Linux)

It would be nice to have a `homeDir` system variable to use in the Launch.json.  I have been using the ruby plugin and I have looked over a number of examples, issues and tutorials.  One thing that strikes me is that the launch.json looses some utility if it is not reusable.  Take for example the RSpec launch that I am working through now while using RVM on a Mac:

```
        {
            "name": "RSpec - all",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/bin/rspec",
            "useBundler": true,
            "pathToBundler": "/Users/<username>/.rvm/gems/ruby-2.3.0/wrappers/bundle",
            "showDebuggerOutput": true,
            "pathToRDebugIDE": "${workspaceRoot}/bin/rdebug-ide",
            "args": [
                "-I",
                "${workspaceRoot}"
            ]
        },
```
While this works:

`"pathToBundler": "/Users/<username>/.rvm/gems/ruby-2.3.0/wrappers/bundle",`

It would be much easier/shareable/reusable to have:

`"pathToBundler": "${homeDir}/.rvm/gems/ruby-2.3.0/wrappers/bundle",`

Similar to what is available for `workspaceRoot`.  

I speculate the complexity here would come in from working for all OS's. (eg: %USERPROFILE% on Windows, $HOME / ~ on Linux).

**Comment by isidorn** [comment]
It is possible to reference enviroment varialbes in your `launch.json`, for instance to access the PATH env variable use the following syntax `${env.PATH}`
More details can be found here http://code.visualstudio.com/docs/editor/tasks#_variable-substitution
I suspect that you can acess the HOME via env variables
