### ISSUE TITLE
ICellViewModel#language sometimes undefined

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#113333]
I saw some errors and when debugging I found out that `ICellViewModel#language` was `undefined` even though the spec/api says it cannot be like that

<img width="426" alt="Screenshot 2020-12-23 at 11 33 40" src="https://user-images.githubusercontent.com/1794099/102987593-e1813000-4512-11eb-844e-56edb70c3373.png">

**Comment by jrieken** [comment]
This only happens in one particular notebook and I do remember having run the "Change to Markdown" cell command

**Comment by rebornix** [comment]
This should be fixed now with us moving to workspace edits for "Change Cell to Markdown"
