### ISSUE TITLE
Uri.parse doesnt render link correctly if the uri has a space in it

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#113328]
```
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:32:43.927Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

based on the [docs](https://code.visualstudio.com/api/extension-guides/command#command-uris)
i have an [ext](https://github.com/ctf0/vscode-goto-package/blob/d8b48917abd97fef5e9f499feb24335697b563b7/src/utils.ts#L51-L57) that have the same setup but with a DoucmentLink instead of hover, which was working perfectly but now instead of getting a link i get the text

`
[remove "spatie/laravel-backup"](command:gotoPackage.removePackage?[{"cmnd":"composer remove spatie/laravel-backup","pkg":"spatie/laravel-backup"}] "Execute command gotoPackage.removePackage") (cmd + click)
`

and here is the console log

![Screen Shot 2020-12-23 at 10 23 22 AM](https://user-images.githubusercontent.com/7388088/102975797-49cb1400-4509-11eb-8089-02ca6b8b8995.png)

am not sure if the api has changed or is it a genuine bug 😢 

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
Please provide a simple repo case. I have tried with the provider below and everything is working fine

```
  vscode.languages.registerDocumentLinkProvider('*', new class implements vscode.DocumentLinkProvider {
        provideDocumentLinks(document: vscode.TextDocument): vscode.DocumentLink[] {
            return [
                new vscode.DocumentLink(new vscode.Range(0, 0, 1, 0), vscode.Uri.parse('command:extension.helloWorld'))
            ]
        }
    })
```

**Comment by ctf0** [comment]
u can try with the extension provided above, its basically a 
- link provider 
https://github.com/ctf0/vscode-goto-package/blob/d8b48917abd97fef5e9f499feb24335697b563b7/src/linkProvider.ts#L29

- calling a function that create the document link
https://github.com/ctf0/vscode-goto-package/blob/d8b48917abd97fef5e9f499feb24335697b563b7/src/utils.ts#L51-L57

- that calls a cmnd
https://github.com/ctf0/vscode-goto-package/blob/e458dd0f45f053e29ee104284823e3f63c1a4b73/src/extension.ts#L23-L28

i've even tried with an old version of the extension and still give the same result, whats really strange is the other 2 normal links "open file, open url" works without any problems.

**Comment by jrieken** [comment]
> u can try with the extension provided above, its basically a

Sorry, but asking you to distill a repo case from that

**Comment by ctf0** [comment]
sure np,  i will ping you once done.

**Comment by ctf0** [comment]
https://github.com/ctf0/cnbd-uri-test, same ext downsized to bare min

> steps
- yarn
- run debug
- open `package.json`
- hover a dependency

**Comment by ctf0** [comment]
finally found the issue.

if the uri have an empty space in it, it wont render correctly and will show the text instead.
this is related to the `DocumentLink` api, not `Commands URIs` api ex.

```[resources/lang/en.json](vscode-insiders://ctf0.laravel-goto-lang/Users/xxx/test/resources/lang/en.json?hello world)```
> note `hello world`

```[remove "spatie/laravel-backup"](command:gotoPackage.removePackage?[{"cmnd":"composer remove spatie/laravel-backup","pkg":"spatie/laravel-backup"}] "Execute command gotoPackage.removePackage")```
> note `composer remove `

removing the empty spaces will render the link as expected.

**Comment by jeanp413** [comment]
@jrieken I took a look at this and found that this is a regression from https://github.com/microsoft/vscode/pull/112670
Not sure if it would be better to revert that commit or https://github.com/microsoft/vscode/issues/85930 would be a better fix for this

**Comment by jrieken** [comment]
@ctf0 This is confusing. How does https://github.com/microsoft/vscode/issues/113328#issuecomment-752040124 relate to the document link provider API? That comment talks about markdown link syntax which seems unrelated to that API

**Comment by ctf0** [comment]
@jrieken actually u can use the same logic with any api that use `vscode.Uri.parse` & u r correct, the docs only mention `MarkdownString` but in reality its applicable with lots of other apis like `document link`.

so to be as accurate as possible, i believe the issue is related more to `vscode.Uri.parse` in general no matter where u use it & not  `document link` or `MarkdownString`.

**Comment by ctf0** [comment]
a temp solution for anyone having this issue is to use `encodeURI` which will escape the empty space & `decodeURI` inside the `UriHandler`.

**Comment by jrieken** [comment]
This get more confusing. The make zero sense to me, `Uri.parse` doesn't render anything. Can't you just provide simple steps like: 

1. Doing _xyz_
2. expecting foo
3. seeing bar

**Comment by ctf0** [comment]
> Can't you just provide simple steps like:

- try this

```
let args  = JSON.stringify([{cmnd: `echo "hello"`}])

new vscode.DocumentLink(new vscode.Range(0, 0, 1, 0), vscode.Uri.parse(`command:extension.helloWorld?${args}`))
```
