### ISSUE TITLE
TreeItems rendered with multiple icons in custom tree

### ISSUE THREAD

**Issue by xqzlgy2** [microsoft/vscode#113374]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Set both `resourceUri` and `iconPath` attribute for a TreeItem in custom tree (`iconPath` is set with `ThemeIcon` instead of path)
2. Multiple icon will be displayed in custom tree, one is contributed by `iconPath`, the other is same as File Explorer's.

For example, if I set `resourceUri` to a Java file, and I also set `class`, `interface`, `enum` icons in order to distinguish main class type in a Java file, I would get:

![image](https://user-images.githubusercontent.com/30518415/103072748-271c2680-4601-11eb-8eff-2a86e81c3d9d.png)

I've already tried that if I set `iconPath` to a svg path, the TreeItem will be rendered correctly. But it's more consistent to use `ThemeIcon`.

Also, if I don't set `resourceUri`, it would also be correct, but in that case I can not benefit from VS Code's built in `FileDecorator` to display each files' source control status.

Does this issue occur when all extensions are disabled?: No

**Comment by ElfQQ** [comment]
Does the next version fix this issue?
