### ISSUE TITLE
Exception in shader when SQL string concatenation in PHP.

### ISSUE THREAD

**Issue by huye** [microsoft/vscode#113324]
Issue Type: <b>Bug</b>

```
<?php

// The single quotation mark in the string causes the color highlight of the implode function to be incorrect.
$sql = "SELECT * FROM  WHERE  IN('" . implode("','", $subs) . "')";
```

VS Code version: Code 1.52.0 (940b5f4bb5fa47866a54529ed759d95d09ee80be, 2020-12-10T22:43:50.597Z)
OS version: Linux x64 5.4.70-amd64-desktop

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 x 2920)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|14.65GB (2.58GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 14391a16-897d-41f8-af87-c27038b34956|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.5.4
php-cs-fixer|jun|0.1.157
php-server-vars-snippets|Mih|0.0.3
vscode-language-pack-zh-hans|MS-|1.52.2
jupyter|ms-|2020.12.414227025
php-docblocker|nei|2.1.0
guilite-previewer|nia|0.0.2
code-settings-sync|Sha|3.4.3
xmake-vscode|tbo|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by roblourens** [comment]
https://github.com/atom/language-php/issues/392
