### ISSUE TITLE
VS code is extremely slow

### ISSUE THREAD

**Issue by harshitachaurasia** [microsoft/vscode#113317]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

Whenever i open a file to code it's stucks on hanging position in the window even after uninstalling unused extensions.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.53GB free)|
|Process Argv|D:\\Programmings\\web dev apna college --crash-reporter-id 7760dc67-9273-4582-8a80-fb7664e33091|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    85	  3372	code main
    0	    96	  1800	   shared-process
    0	   167	  2704	   window (Welcome - web dev apna college - Visual Studio Code)
    0	   119	    32	     extensionHost
    0	    23	  3332	       c:\Users\harsh\.vscode\extensions\ms-vscode.cpptools-1.1.3\bin\cpptools.exe
    0	    10	  5516	         console-window-host (Windows internal process)
    0	    11	 10964	         "c:\Users\harsh\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 3332 0
    0	    64	  3628	       "C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=32
    0	    88	 10468	       "C:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\harsh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=32
    0	    14	 10160	     watcherService 
    0	    11	   696	       console-window-host (Windows internal process)
    0	    66	 11664	     searchService
    1	    78	  4076	   window (Issue Reporter)
    0	    22	  4952	   crashpad-handler
    0	    36	  8512	   utility
    2	   137	 10736	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Welcome - web dev apna college - Visual Studio Code)
|    Folder (web dev apna college): 5 files
|      File types: html(3) c(2)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
dart-code|Dar|3.17.1
competitive-programming-helper|Div|5.0.1
code-runner|for|0.11.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
cpptools|ms-|1.1.3
debugger-for-chrome|msj|4.12.11
autodocstring|njp|0.5.4
vscode-readme-pattern|tho|1.3.0
vim|vsc|1.18.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
pythonvspyt617cf:30237717
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30239448

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with *all* extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

And what kind of file you are trying to open? HTML, C, or something else?

**Comment by harshitachaurasia** [comment]
It's working with all disabled extensions.I'm opening HTML files using the live server extension, it's been extremely slow to run about 1120ms

**Comment by IllusionMH** [comment]
> It's working with all disabled extensions.

Does it mean that VS Code will open file quickly with all extensions disabled but slow if live server extension is enabled?

**Comment by harshitachaurasia** [comment]
Yes. This is the only issue

**Comment by IllusionMH** [comment]
/causedByExtension

If it's not reproduced with all extensions disabled - please report this issue in extension repo.
[Extension bisect](https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect) could help to find one causing problem if you are not sure which one causes it.

If it's Live server in your case - they already have couple of issues related to performance so new info should be helpful in those issues.
