### ISSUE TITLE
Allow to remove a specific sub-directory from explorer

### ISSUE THREAD

**Issue by iamshreeram** [microsoft/vscode#113354]
I was trying to read all the user configs (.bash_profile, .vimrc, etc.) and the application configs (.cabal, .minikube, .npmrc, etc.) that was located at `~` from vsc.

```
.kotlinc_history,.ghcup,.bashrc,.ghc,.pm2,.m2,.cabal,.gradle,.eclipse,.jmc,.minikube,.local,.vim,.cache,.IdentityService,.gitconfig,.git-credentials,.azuredatastudio,.rediscli_history,.clojure_history,.ServiceHub,.anyconnect,.config,.sonic-pi,Desktop,.DS_Store,.docker,.kube,.lein,.Trash,.npmrc,.hyper_plugins,.npm,.python_history,.viminfo,.bash_profile,.hyper.js,.bash_history
```

So, I had to add the `~` folder to my workspace. 

Now, I don't want VSCode to track all the directories inside `~`. While I was trying to remove specific folder like `clojure_history,.ServiceHub,.anyconnect,.config,.sonic-pi,Desktop,.DS_Store,.docker,`, VSC doesnt provide such feature. I'm able to remove the complete root folder (`~`) from workspace though. 

I want to remove few directories / files inside the main directory that was added to workspace.

**Comment by bpasero** [comment]
You can hide things via the `files.exclude` setting.

**Comment by iamshreeram** [comment]
@bpasero , File exclude will allow VSCode to stop monitoring that specific files. That is not what we want. 

Below is the scenario :

Let us say Below is my directory  
```
~/.config
~/.cabal/
~/project/python
~/project/node
~/project/haskell
~/project/Clojure
~/project/Shell
~/.nvm/
.bash_profile
.bashrc
```

**Now:**
Currently, the vscode monitors every folders inside `~/project/` separately. (i.e., `python`, `node`, `haskell`, etc.). Structure of the workspace

```
/python
/node
/haskell
/project/
 | /python
 | /node
 | /haskell
 | /Clojure/
 | /Shell/
```

If i add `~/project/` or `/python` to `files.exclude`, this is excluding entire projects directory and ignoring `python`, `node`, and `haskell`.   Workspace will look like below -
```
~| /.config
 | /.cabal/
 | /.nvm/
 | .bash_profile
 | .bashrc
```

**What is needed**
Now, we want to add `~` that has `~/.config`, `~/.cabal/`, `~/.nvm/`, `.bash_profile`, `.bashrc`. But also monitor `python`, `node`, and `haskell`. That way, Workspace will look like below

```
~| 
 | /.config
 | /.cabal/
 | /.nvm/
 | .bash_profile
 | .bashrc
/python
/node
/haskell
/project/
 | /Clojure/
 | /Shell/
```

The only solution is to add `~` fully and remove `~/project` from it. That way, vsc will be able to track  `python`, `node`, and `haskell` inside `project` and also can have `~/.config`, `~/.cabal/`, `~/.nvm/`, `.bash_profile`, `.bashrc`.

I have also posted this question on [stackoverflow](https://stackoverflow.com/questions/65430256/vscode-removing-a-specific-sub-directory-from-workspace). Created a github ticket as there is no response.

Appreciate if you can keep the ticket open until this issue is fixed.

**Comment by bpasero** [comment]
Is it fair to say that this is only a request to hide things from the file explorer?

**Comment by iamshreeram** [comment]
@bpasero , That is right. I would say, a request to remove specific sub-folders or a file from a folder in the file explorer.

Currently, vscode lets us to _Remove folder from workspace_ but it does not allow us to _remove a sub-folder_ from a folder. It allows us to _delete_ the sub-folder but not _remove_ .

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
However this will probably be handled by extensions if we open up the explorer exclusion api to extensions

**Comment by iamshreeram** [comment]
@isidorn , are you planning to open up the exclusion api anytime soon?

**Comment by isidorn** [comment]
@iamshreeram currently not on the plan, but we might do it. I do not really know, sorry.
