### ISSUE TITLE
typeof in generics breaks syntax highlighting

### ISSUE THREAD

**Issue by apostolos** [microsoft/vscode#113345]
- VSCode Version: Insiders
- OS Version: Windows 10

![image](https://user-images.githubusercontent.com/41679/103018308-af40f400-454d-11eb-86d4-5d4dc4da7482.png)

Use the following code in a tsx file:

```tsx
function Test1() {
  return null;
}

const test1 = <Test1 />;

type TestProps = React.ComponentProps<typeof Test1>;

function somethingElse() {
  const myVar = 1;
  return myVar;
}
```

or something simpler:

```ts
const arr = [1];
type MyType = Readonly<typeof arr>;

function somethingElse() {
  const myVar = 1;
  return myVar;
}
```

![image](https://user-images.githubusercontent.com/41679/103018775-6ccbe700-454e-11eb-80f5-9cba52ff0060.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by christianalfoni** [comment]
I have the same issue on this, Insiders on Mac (Arm)

**Comment by rokoroku** [comment]
Same here, after **typeof in generics** almost every type token is scoped as `meta.type.parameter` 

![image](https://user-images.githubusercontent.com/5208632/103302366-d1071300-4a46-11eb-9465-69729828f192.png)

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/TypeScript-TmLanguage/issues/846
