### ISSUE TITLE
Initializing JS/TS language features in the loop

### ISSUE THREAD

**Issue by vtereshyn** [microsoft/vscode#113339]
Issue Type: <b>Bug</b>

For some reasons Typescript can't be initialized in Visual Studio Code. This issue appears for no reason. Sometimes, window reload helps. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (3.15GB free)|
|Process Argv|-psn_0_110619 --crash-reporter-id d0f6a646-1a5a-4c45-8ad0-e12fcbc53656|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
vscode-pull-request-github|Git|0.22.0
graphql-for-vscode|kum|1.15.3
remote-containers|ms-|0.154.1
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.4.0
vscode-yaml|red|0.13.0
vscode-import-cost|wix|2.13.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
pythonvspyt617cf:30237717
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt859:30239450
vsjup459cf:30237188

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
