### ISSUE TITLE
Search Close / X Button at the right is much worse than leaving directly next to the file / line

### ISSUE THREAD

**Issue by jjblodgett** [microsoft/vscode#113349]
- VSCode Version: 1.52.0
- OS Version: Win 10 (Windows_NT x64 10.0.18363)

Steps to Reproduce:

1. Run file search after latest update.
2. Scroll to the right for an hour and a half to reach the "close" X.

While I appreciate the need and reasons to "standardize" the close position of the individual line / filename results of searches, moving it to the far right of the search window is extremely cumbersome and takes even more time than moving the mouse slightly on each row depending on the config of the windows / monitors. On my primary / largest monitor with the search in a horizontal plane of its own, the X is so far to the right that it takes an enormous amount of time to constantly scroll back and forth from line to X and back (see image). I would love to see a "fixed" position horizontally somehow, but the far right is not the place to do it!!!

![image](https://user-images.githubusercontent.com/6646643/103025006-cb20a780-4505-11eb-8c9c-bf2c59cfd622.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
You can set `"search.actionsPosition": "auto"` to revert this, I changed the default value of this setting in the last release, after many user complaints of accidentally clicking those buttons.

**Comment by jjblodgett** [comment]
Thanks!
