### ISSUE TITLE
Use a configuration object when creating terminals via API

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11332]
In order to avoid issues with parameter order and addition options in the future, factor out the terminal configuration and use that in `window.createTerminal` (similar to the config object used in `setLanguageConfiguration`).

Old: `createTerminal(name?: string): Terminal`
New: `createTerminal(configuration: TerminalConfiguration): Terminal`

FYI @jrieken

**Comment by jrieken** [comment]
No - we don't go complex first but handle the situation (with an overload) if case it ever arises.

**Comment by Tyriar** [comment]
The need has arisen, a shell path will need to be added for this to be useful for a lot of people #10917. See https://github.com/Microsoft/vscode/issues/11214#issuecomment-244157685

**Comment by Tyriar** [comment]
Another one #11384

**Comment by Tyriar** [comment]
Reverted in https://github.com/Microsoft/vscode/commit/7bd499af9bc2b210b1faa499f9af5ed7cdf1af48
