### ISSUE TITLE
Unwanted underscore when trying to format code in macos

### ISSUE THREAD

**Issue by suyashdeshpande** [microsoft/vscode#113392]
- VSCode Version: Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
- OS Version: macOS BigSur version 11.1

Steps to Reproduce:

1. Open any file
2. Try to format code using the keyboard shortcut
3. Instead of formatting, underscore is printed

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by suyashdeshpande** [comment]
https://user-images.githubusercontent.com/28438230/104091323-b0d71f80-52a2-11eb-8b9c-c42a88c98155.mov

When I press option + shift + F on macOS, this weird character is printed instead of formatting the code.

**Comment by suyashdeshpande** [comment]
@bpasero @alexdima Added a video for your reference

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/41024 . It looks like another variant, this time for Shift+Option+F.
