### ISSUE TITLE
Allow setting viewType selector at runtime

### ISSUE THREAD

**Issue by Coding-Kiwi** [microsoft/vscode#113329]
In the [Custom Editor API](https://code.visualstudio.com/api/extension-guides/custom-editors) you define a package.json entry like this for example:

```json
"contributes": {
  "customEditors": [{
    "viewType": "extensionid.example",
    "displayName": "example",
    "selector": [{
    "filenamePattern": "*.example"
    }]
  }]
},
```

But then the selectors / filenamePatterns are hardcoded in the package.json. It would be awesome if we could change these during runtime (for example user-defined via the config).

I'm trying to make an extension that lets the user define which file patterns should be handled by the extension's CustomTextEditorProvider

**Comment by mati-o** [comment]
I have a similar need.

I am dealing with a bunch of JSON files, which in my case, I cannot rely on the location of the files. Instead, I have to read the file first to check if it has a specific key in it, if so get the correct view or fallback to default text editor. 

I have hoped to find anything to hook onto before `resolveCustomTextEditor` is called, however it seems there's no way at the moment.
