### ISSUE TITLE
Go to definition opens duplicate instances of files.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#113398]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic

-I have two source files open A and B 
-each A and B are in their own separate editor pane
-File A contains a method call that is defined in File B.
-when I hit 'go to definition' on this method, vscode opens a new instance of file B inside of file A's editor pane.

The expected behaviour is that the editor would just jump to a focus the existing instance of file B in the other editor pane.

**Comment by safield** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * ["Go back" Jumps to different editor when in split editor mode with same File (#95818)](https://www.github.com/microsoft/vscode/issues/95818)

Not a duplicate. Thanks though bot.

**Comment by IllusionMH** [comment]
> -when I hit 'go to definition' on this method, vscode opens a new instance of file B inside of file A's editor pane.

Do you mean that Peek view is opened? See https://code.visualstudio.com/Docs/editor/editingevolved#_peek

If there are several definitions for various "go to ..." you would get Peek view. To change this check family of "Goto Location" settings (searching by `editor.gotoLocation`) and check that `editor.definitionLinkOpensInPeek` is `false`

**Comment by safield** [comment]
I have a method call. I right click on the method and in the subsequent dropdown menu I hit "goto definition". It then opens a brand new instance of the file that the method is defined in, instead of focusing the existing instance of the file.

No peek view involved. Let me know if I still need to provide clarification.

**Comment by IllusionMH** [comment]
Oh, I was confused by "inside of file A's editor pane." looks like you are talking about editors group.

By default new editors are opened/focused within same group so you can have independent groups and navigation in one won't break focus/workflow in other.

Setting `"workbench.editor.revealIfOpen": true` should focus file in other groups instead (when possible) which I guess is your preferred behavior.
