### ISSUE TITLE
Happy Christmas

### ISSUE THREAD

**Issue by varadero** [microsoft/vscode#113396]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Its Christmas but there is no Santa hat in the cogwheel button in the lower-left corner. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Grapphy** [comment]
I'm really disappointed about this. I was expecting to find a Santa's hat in the cogwheel button this year. I hope Microsoft does the right thing and bring it back. (I'm Jewish by the way.)

**Comment by jrieken** [comment]
Happy New Year!
