### ISSUE TITLE
Suggest widget should not let scroll events escape

### ISSUE THREAD

**Issue by dipanshparmar** [microsoft/vscode#113389]
Right now when I scroll the autocomplete box and when it reaches the end it triggers the whole window to scroll.

What I want is that when it reaches the end then it shouldn't be moving as long as the cursor is inside the autocomplete box, doesn't matter how much I scroll.

### Examples about what I want
**Intellij autocomplete box:**
(When I reached the end and tried to scroll it just stopped there and that's good)

**VS Code autocomplete box:**
(When I reached the end and continued scrolling while my cursor was in the box itself the scrolling didn't stop there and it triggered the whole window to scroll and that's something bad I guess)

**I'm looking forward to hearing other's opinions on this.**

**Comment by alexdima** [comment]
@jrieken `ScrollableElementCreationOptions.alwaysConsumeMouseWheel`. It is `false` by default and if it is set to `true`, the scrollable element will "eat up" all wheel events, even when scrolling is no longer possible.

**Comment by jrieken** [comment]
Thanks!

**Comment by nrayburn-tech** [comment]
Unless I am missing something, I don't see a way to just add the setting without modifying some constructors/types.

The `suggestWidget` uses a `listWidget`, which uses a `listView`, which finally creates the `SmoothScrollableElement` that needs the `alwaysConsumeMouseWheel: true` option.  There isn't a way to currently pass the options down that far.  It could be added to here where some other scrolling options are, https://github.com/microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listWidget.ts#L833.

Or maybe the list should extend the scrollableElement options somewhere.

**Comment by jrieken** [comment]
Adding @joaomoreno for making this a list options

**Comment by susiwen8** [comment]
@joaomoreno @jrieken Hi, I have submit a pr for it, could you review it?
