### ISSUE TITLE
Hover widget don't disappear when editor scroll 

### ISSUE THREAD

**Issue by susiwen8** [microsoft/vscode#113380]
When content in hover widget was too long, hover widget will show scrollbar, allow user scroll to read reset of content
But, as soon as reach bottom of hover widget, it will fire editor scroll event which would close hover widget [at this line](https://github.com/microsoft/vscode/blob/master/src/vs/editor/contrib/hover/hover.ts#L120)
Here is gif 
![Kapture 2020-12-24 at 19 23 28](https://user-images.githubusercontent.com/20318608/103085781-acadcf80-461d-11eb-807d-27c968ae8c41.gif)

So I propose when mouse was over hover widget, editor scroll event won't close hover.

I have try to implement it, if you guys think this were worth to do, I will submit a PR

**Comment by alexdima** [comment]
Let's track in #112373
