### ISSUE TITLE
MacOS Touch bar function keys control system functions (eg brightness)

### ISSUE THREAD

**Issue by Christilut** [microsoft/vscode#113387]
Issue Type: <b>Bug</b>

I have a macbook with touch bar and I've set up osx to always show the function keys in VSCode. So far this works but when I press a function key, eg F1, then instead of performing the VSCode action, it performs the underlying OSX action. For F1, it decreases brightness.

F1 is bound to opening the command palette normally.

When I hold FN, the touch bar changes to the system controls (eg brightness etc).

The only way I can execute a real F1 command is by shortly pressing the FN key and pressing F1. Then it opens the command palette.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|VirtualApple @ 2.50GHz processor (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 26559e62-57d4-421c-869c-bb6149edaa0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
scratchpads|bue|0.0.7
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
vscode-html2pug|dba|4.0.0
githistory|don|0.6.14
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.13
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-puglint|mrm|2.3.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-typescript-tslint-plugin|ms-|1.3.2
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
vscode-jest|Ort|3.2.0
seti-icons|qin|0.1.3
vscode-scss-formatter|sib|2.0.5
vscode-surround|Swo|1.0.1
selectline-statusbar|tom|0.0.2
vscode-todo-highlight|way|1.0.4

</details>

**Comment by jrieken** [comment]
I believe this a macOS answer and unrelated to vscode. But did you try that setting?

<img width="668" alt="Screenshot 2020-12-24 at 15 29 51" src="https://user-images.githubusercontent.com/1794099/103094166-eae6c700-45fc-11eb-8687-29ba6f8480c8.png">

**Comment by Christilut** [comment]
Thanks for the super fast response! That was actually it. I glanced over it but figured it was for external keyboards only, but this works for the touch bar.
