### ISSUE TITLE
Graphical Glitch in Windows

### ISSUE THREAD

**Issue by kadajett-remo** [microsoft/vscode#113352]
- VSCode Version: 1.52.1
- OS Version: Windows 10 18363.1256

Steps to Reproduce:

1. Open VS Code
2. Look at any part of the window that VS code isn't currently interacting with, with the mouse

![image](https://user-images.githubusercontent.com/74637592/103030064-0bdde800-4529-11eb-9c47-6859399124b5.png)

This might be an issue with electron, but I wanted to post here first.
It is very trippy lol

Does this issue occur when all extensions are disabled?: Yes

**Comment by kadajett-remo** [comment]
I have tried turning on and off windows blur remover in the display settings. I also have latest node installed, if that matters. And I am running this through the Linux subsystem if that matters

**Comment by yume-chan** [comment]
> I am running this through the Linux subsystem

Do you mean you are running the Linux version of Code with some X forwarding software, or you are using the Remote - WSL extension?

**Comment by kadajett-remo** [comment]
The extension. But, I have tried it without may extensions running as well, with the issue persisting. I have a rather complex setup, running on multiple external and internal GPUs. I wonder if electron is having issues rendering because of this 🤔

**Comment by deepak1556** [comment]
Similar to https://github.com/microsoft/vscode/issues/92379

Can you try running with `--disable-gpu`
