### ISSUE TITLE
Manual alignment in diff view

### ISSUE THREAD

**Issue by Florin-Popescu** [microsoft/vscode#113357]
Hello!

When comparing files (either different versions of the same file or different files) I sometimes need to change the alignment of the differing lines between the 2 files. I would like to suggest a way to **manually align lines in the diff view** when needed.

Some use case examples:
1. I would expect that lines 5-10 on the left side should be compared line by line with lines 10-15 on the right side, but due to similarities in the other lines, lines 5-10 on the left side are matched to lines 8-13 on the right side in the diff view.
2. There is a recurring pattern in a file and I would like to compare every occurrence of that pattern. So on the left I have the pattern on lines 5-10 and on the right file I have the same pattern with small modifications on lines 5-10, 25-30, 50-55. I would like to compare the one pattern on the left side against lines 5-10 on the right side, then against lines 25-30, then against lines 50-55.
3. I move a section of a file to further down that file and make some modifications. I would then like to compare these 2 sections but it's not possible with the way the diff view currently displays them. Like here, I moved the `==Register==` section higher in the same file and would like to compare the 2 `==Register==` sections:
![Screenshot 2020-12-23 234607](https://user-images.githubusercontent.com/18745211/103039408-88001c00-4579-11eb-9cab-5151667ba2b9.png)

I used the feature a lot previously in Beyond Compare. There I would right click a line in the left pane and click Align With, then click a different line in the right pane. Then the 2 lines would be aligned side by side with the compare algorithm starting from there as if they were both the beginning of their files.

Taking the previous example, this is what I would like to be able to compare:
![Screenshot 2020-12-23 235727](https://user-images.githubusercontent.com/18745211/103039920-b5999500-457a-11eb-85b0-dc25bb263ef6.png)

I think this would be very useful to have.

**Comment by Florin-Popescu** [comment]
I didn't find an existing issue for this. #34585 isn't really about the same thing.

**Comment by tarnopolsky** [comment]
Oh, i miss this feature a lot, and know others who would be happy to use it. I know it is closed now, but still is there any chance that it can be moved to the backlog anytime soon?
