### ISSUE TITLE
text-stroke is not valid CSS property

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#113321]
Steps to Reproduce:

1. Type text-stroke in CSS
2. Invalid message

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
We get the list of valid properties from MDN. `text-stroke` is not documented as it is not part of any W3C spec. For that reason it probably should not be used. 

To tell VSCode to not warn about `text-stroke`, use the setting `css.lint.validProperties`.
