### ISSUE TITLE
Add Uppercase letters as word separator

### ISSUE THREAD

**Issue by maximMalofeev** [microsoft/vscode#113312]
It would be great if you add an ability to mark uppercase letters as a word separator, because in case of CamelCase text the word separator is uppercase letter.

P.S Thank you for your job!

**Comment by jrieken** [comment]
> It would be great if you add an ability to mark uppercase letters as a word separator, because in case of CamelCase text the word separator is uppercase letter.

In place/feature do you want that?

**Comment by y1n0** [comment]
indeed, this would be very useful for languages that use camelCase. This would help with navigating through words with the keyboard. If we can somehow specify case change as a separator in `editor.wordSeparators` setting would much appreciated!
