### ISSUE TITLE
eslint-stylish problem matcher fails on multi-line rule messages

### ISSUE THREAD

**Issue by thw0rted** [microsoft/vscode#113306]
- VSCode Version: 1.52.1
- OS Version: Win10 20H2

Steps to Reproduce:

1. Configure a task to run `eslint` with the default ("stylish") formatter, using the `$eslint-stylish` problem matcher
2. Write code that trips a linter rule with a multi-line message, such as https://github.com/typescript-eslint/typescript-eslint/issues/2895
3. Run the task
4. The Problems tab has a new problem that points to a file called "ban-types" (in this example), because it matched the rule message as if it were a file path

Does this issue occur when all extensions are disabled?: Yes

Note that the linked issue has an example of some Typescript source that will trigger the example rule.

**Comment by yrtimiD** [comment]
If somebody also waits this fix to be merges, you can temporary override problemMatcher patters directly in the tasks.json:
```json
"problemMatcher": {
  "base": "$eslint-stylish",
  "pattern": [
    {
      "regexp": "^((?:[a-zA-Z]:)*[\\\/.]+.*?)$",
      "kind": "location",
      "file": 1
    },
    {
      "regexp": "^\\s+(\\d+):(\\d+)\\s+(error|warning|info)\\s+(.+?)(?:\\s\\s+(.*))?$",
      "line": 1,
      "severity": 3,
      "message": 4,
      "code": 5,
      "loop": true
    }
  ]
}
```

**Comment by yrtimiD** [comment]
@alexr00 , any plans to merge this PR soon? I'm using this fix for some time and all looks good.

**Comment by alexr00** [comment]
I missed the PR when it came in 😳. I've posted a comment in the PR.
