### ISSUE TITLE
"Open Containing Folder" context menu is open a Terminal window instead of File Browser

### ISSUE THREAD

**Issue by brpaz** [microsoft/vscode#113394]
Right-clicking in a folder and selecting "Open Containing folder" is opening a Terminal Window instead of the File Browser as you can see in the following GIF.

![issue](https://user-images.githubusercontent.com/184563/103098157-a6115f00-4601-11eb-8cea-128a26029ba9.gif)

It´s not even opening the correct folder in the terminal, but my home directory.

It was working yesterday. The only thing I did was to update my system, which included installing the November release of VS Code.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.9.15-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2480)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.45GB (1.50GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 51617097-5af8-4008-9aa7-5019089fd2f1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details>

</details>

**Comment by brpaz** [comment]
I found the problem. Somehow, my default file handler for directories changed from nautilus to a terminal-based application.

**Comment by hichemfantar** [comment]
I fixed this by switching from SNAP version to apt
