### ISSUE TITLE
Misspelling of keyboard shortcut filter name

### ISSUE THREAD

**Issue by zigfreid5** [microsoft/vscode#113323]
Issue Type: <b>Bug</b>

The keyboard shortcut for "find previous" contains a misspelled "where" filter name of "findInputFocussed". While this is the correct filter, this is not the proper spelling, and attempting to use the proper spelling in another shortcut, for example, results in a missed filter.

The proper spelling should be "findInputFocused", which is not only the correct spelling, but matches the spelling of other "*.Focused" filters.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

**Comment by amunger** [comment]
closing this as we won't be able to fix it without breaking users that are using it in their keybindings.json
