### ISSUE TITLE
Minimap highlight frame position is incorrect, not representing actual view position/boundaries

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#113375]
Issue Type: <b>Bug</b>

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.1.0

When scrolling through a large file and locating errored lines, the frame seems really offset to what the view actually shows.

See screenshot (the screenshot contains the entire window):

<img width="1468" alt="Screenshot 2020-12-24 at 3 21 58 PM" src="https://user-images.githubusercontent.com/9585787/103074389-0e5d4200-45fc-11eb-9c3b-832e2d241724.png">

I have to scroll to get the actual code in question.

see next screenshot:

<img width="1523" alt="Screenshot 2020-12-24 at 3 24 35 PM" src="https://user-images.githubusercontent.com/9585787/103074627-9fccb400-45fc-11eb-8c09-b9c212d3c386.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 1d67baca-9983-4dc9-9976-f411530bc7c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
ng-template|Ang|0.1100.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
vs-code-xml-format|fab|0.1.5
debugger-for-chrome|msj|4.12.11
markdown-preview-enhanced|shd|0.5.13
vscode-open-in-github|sys|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30239448

```

</details>

**Comment by alexdima** [comment]
In really large files, if the aspect would be always maintained, the scroll slider would get very very small, like 1px tall. That would make it unusable. It would not be possible to click it with the mouse. That is why we artificially keep it at a minimum height of `20px`. This causes it to remain clickable, but it becomes imprecise when the file has many lines.
