### ISSUE TITLE
Custom Folds

### ISSUE THREAD

**Issue by ihdavids** [microsoft/vscode#113372]
I would like to request more flexible folding.

Background:
At the moment it looks like a fold provider is the only way to manage folds in a document.
These folds are a list of FoldingRange objects.
FoldingRange objects have a line granularity.

In sublime folds in a view are positions not lines.

Request:
- Facilitate sub line folding.
- Facilitate controlling the fold icon (or even the ability to hide the fold icon)

Specifically I would like to fold away the URL in a link in a markdown or org mode file so the text can simply look like the link description unless the cursor walks over the link, in which case I dynamically unfold the link.

**Comment by aeschli** [comment]
Folding ranges inside a line is https://github.com/microsoft/vscode/issues/50840. We currently have no plans to support that.
