### ISSUE TITLE
terminal error

### ISSUE THREAD

**Issue by arya100-max** [microsoft/vscode#113466]
Issue Type: <b>Bug</b>

The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 4294967295).

how can i solve this problm?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.20257

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
