### ISSUE TITLE
Expose which lines the file is scrolled at / scroll position in user tasks

### ISSUE THREAD

**Issue by caub** [microsoft/vscode#113429]
The idea would be to be able to run 

```
"command": " NODE_ENV=test npx mocha -b ${file} --grep "first test description visible in screen"
```
If I could access the scrollStart line for the current file, and have also a simple script parsing the test with an AST parser to map line number to tests descriptors, I'd be able to do:

```
"command": " NODE_ENV=test npx mocha -b ${file} --grep "$(custom-script '${scroll.startLine}')"
```

Just an idea, I know I could also use mocha's watch mode `-w`/`--watch` to achieve something similar, but I'm still interested in that idea, as it might not be too hard for vscode to expose this kind of meta editor data maybe?

**Comment by jrieken** [comment]
How is this related to vscode?

**Comment by caub** [comment]
@jrieken it's about vscode code tasks and variables: https://code.visualstudio.com/docs/editor/tasks#_variable-substitution
