### ISSUE TITLE
Can't rename files

### ISSUE THREAD

**Issue by wsjgithub** [microsoft/vscode#113497]
Whenever I try to rename a file from say 'sentence.js' to 'Sentence.js' (changing from lower case to upper case). VSCode will change the name for a second but immediately falls back to the old name. The name in the explorer is different from the name on the tab. I have disabled all extensions and the issue remains. I am not sure if this is a bug or a feature that I am not aware of. 
Steps to recreate
1. create a file 'hello.js;
2. change the file name to 'Hello.js' (change the letter case only h->H)
3. save the file.
4. issue: the file changes back to' hello.js' on the tab. The file in the explorer is 'Hello.js'. Also auto import will import the file from 'hello.js'

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Computer OS: Mac Catalina 10.15.7
<img width="237" alt="Screen Shot 2020-12-28 at 9 38 12 PM" src="https://user-images.githubusercontent.com/19483949/103218363-bef97780-4955-11eb-9347-dee2d06eb3a7.png">
<img width="1158" alt="Screen Shot 2020-12-28 at 9 38 35 PM" src="https://user-images.githubusercontent.com/19483949/103218368-c02aa480-4955-11eb-9d1c-2b87d5879472.png">

**Comment by isidorn** [comment]
This works just fine for me.
Can you reproduce with latest vscode insiders 
https://code.visualstudio.com/insiders/

fyi @bpasero in case you are aware of duplicates

**Comment by bpasero** [comment]
It would be interesting if the file fails to change on disk and this is just a label issue or if the casing really does not change on disk. We have had other issues such as https://github.com/microsoft/vscode/issues/113277 which are similar.
