### ISSUE TITLE
Extensions not loading

### ISSUE THREAD

**Issue by easa** [microsoft/vscode#113498]
I can't use any extension. But after re-installing them they'll be available till the next restart!
![image](https://user-images.githubusercontent.com/6375599/103220702-31f2f600-4936-11eb-8254-7401b0ae4669.png)

- VSCode Version: Version: 1.36.1 (system setup)
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
It seems you are using pretty old version of VS Code. Can you please update VS Code and try again?
If you still see the issue, please provide us the steps to reproduce.
