### ISSUE TITLE
can't extend Terminal

### ISSUE THREAD

**Issue by evya5** [microsoft/vscode#113457]
Issue Type: <b>Bug</b>

hello, i wanted to let you know that my collaborator could not extend mt shard terminal and was left with a narrow terminal while tyring to run the files.
even though he  held the edge and pulled up, the terminal itself stayed small and uncomfortable to work with

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.64GB free)|
|Process Argv|--crash-reporter-id ba1ff838-f907-4868-a7cd-64b767f3bb0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
pip-packages|etm|0.4.3
vsls-whiteboard|los|0.0.12
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
vsliveshare|ms-|1.0.3375

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30236573
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt600:30239448
vsjup459cf:30237188

```

</details>

**Comment by meganrogge** [comment]
Hi I'm not able to reproduce this. Could you please provide me w the exact steps used to do so?
