### ISSUE TITLE
Termination of extension host

### ISSUE THREAD

**Issue by momt99** [microsoft/vscode#113443]
Issue Type: <b>Bug</b>

Recently, it happens a lot for me in the C# project to see that the extension host is terminated and I should restart it. Most of the time it happens when there's a change in the file tree. I mean file creation/rename or git checkouts are some situations that cause the termination.
Although it seems to be a bug in the C#/Omnisharp extension which I have also reported [here](https://github.com/OmniSharp/omnisharp-vscode/issues/4270), I think it's also a problem in vscode that an issue in an extension can cause the termination of the whole extension host.
Logs from the developer tools console are included.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>Console Log</summary>

```
c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16
var r=function(e,t){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)t.hasOwnProperty(n)&&(e[n]=t[n])})(e,t)};function i(e,t){function n(){this.constructor=e}r(e,t),e.prototype=null===t?Object.create(t):(n.prototype=t.prototype,new n)}},function(e,t,n){"use strict";n.d(t,"a",(function(){return l}));var r=n(0),i=n(50),o=n(97),s=n(8),a=n(78),c=n(27),u=n(65),l=function(e){function t(n,r,i){var s=e.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof t?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new d(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new d(s,n,r,i)}return s}return r.a(t,e),t.prototype[a.a]=functio

[TypeError: Cannot read property 'replace' of null
	at t.post [as _next] (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:36:383967)
	at t.__tryOrUnsub (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:3217)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:2362)
	at t._next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:1414)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:1085)
	at t.next (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:26271)
	at t.EventStream.post (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:36:67000)
	at EventEmitter.<anonymous> (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:536991)
	at EventEmitter.emit (events.js:228:7)
	at e._fireEvent (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:535713)
	at e._handleEventPacket (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:543372)
	at e._onLineReceived (c:\Users\UserName\.vscode\extensions\ms-dotnettools.csharp-1.23.8\dist\extension.js:16:542694)
	at Interface.emit (events.js:223:5)
	at Interface._onLine (readline.js:315:10)
	at Interface._normalWrite (readline.js:460:12)
	at Socket.ondata (readline.js:172:10)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)] {
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}
  ]
}
```
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.51GB free)|
|Process Argv|--crash-reporter-id f54ed90e-e790-4e57-8437-932de4ddce01|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.10.1
dart-code|Dar|3.17.1
flutter|Dar|3.17.0
vscode-eslint|dba|2.1.14
netcore-snippets|dog|3.15.1
xml|Dot|2.5.1
vscode-html-css|ecm|1.3.3
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.8.0
html-preview-vscode|geo|0.2.5
beautify|Hoo|1.5.0
reg|ion|1.0.2
latex-workshop|Jam|8.15.0
svg|joc|1.4.2
roslynator|jos|3.0.1
flutter-intl|loc|1.13.0
git-graph|mhu|1.28.0
escape-quotes|mil|1.10.0
vscode-docker|ms-|1.9.0
csharp|ms-|1.23.8
mssql|ms-|1.10.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3375
material-icon-theme|PKi|4.4.0
vscode-autohide|sir|1.0.7
swdc-vscode|sof|2.3.24
code-spell-checker|str|1.10.2
msbuild-project-tools|tin|0.3.10
vscodeintellicode|Vis|1.2.10

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30236573
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30239448
vsjup459cf:30237188

```

</details>

**Comment by alexdima** [comment]
> I think it's also a problem in vscode that an issue in an extension can cause the termination of the whole extension host.

This is as designed. The extension host is a nodejs process where all extensions are loaded without any sandbox. That means we execute any piece of code written by the extension. Extensions have many ways to induce crashes, the most common being an OOM crash. For example, an extension can allocate objects in a loop until there is no more memory and the process crashes. Extensions can also enter an endless loop, in which case they completely starve other extensions. Extensions can also induce crashes by shipping a native C++ node module and causing segmentation faults, or using OS APIs in wrong ways (like spawning thousands of processes), etc.

The extension host is a nodejs process where we load the code from extensions. It is not in our scope to create an extension host which has Operating System - like features, like being resilient to a runaway extension, etc.
