### ISSUE TITLE
while loop crashes VS Code

### ISSUE THREAD

**Issue by wioym** [microsoft/vscode#113499]
- VSCode Version: 1.52.1
- OS Version: Windows 10 

Steps to Reproduce:

1. Run a while loop and click the bin icon
2. Rerun the while loop causing a crash

Does this issue occur when all extensions are disabled?: Does not depend on extensions.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide more details where you input this loop (what language) and where you press bin icon?
Screenshot will be helpful.

Not sure how it's available without extensions.

**Comment by wioym** [comment]
> /needsMoreInfo
> 
> Could you provide more details where you input this loop (what language) and where you press bin icon?
> Screenshot will be helpful.
> 
> Not sure how it's available without extensions.

Language: Python 3
Inter.: Anaconda (up-to-date)
<img width="1391" alt="Screenshot 2020-12-28 at 16 39 00" src="https://user-images.githubusercontent.com/24494206/103226061-8cd32000-492b-11eb-9883-00eeff5d5a4f.png">

The crash does not occur during the code execution, it occurs when attempting to rerun the infinite loop

**Comment by IllusionMH** [comment]
So to clarify:
you launch python program with infinite loop from built-in terminal (not from editor) and click on "Kill terminal" button?

If yes then most likely duplicate of #76548

/assign Tyriar

**Comment by wioym** [comment]
> So to clarify:
> you launch python program with infinite loop from built-in terminal (not from editor) and click on "Kill terminal" button?
> 
> If yes then most likely duplicate of #76548
> 
> /assign Tyriar

Yup 100% correct. 
Attempted to replicate the bug on Mac, didn't work, Windows only.

**Comment by wioym** [comment]
Hello, just wanted to add a bit more information. I was able to semi-reproduce the following error with a for loop where the input was a list contained 685 lines. VS Code slowed down significantly, leading to unresponsive UI, after the completion of the loop the software continued to work perfectly normal. Recreated the following issue on Pycharm, there were no issues.

**Comment by Tyriar** [comment]
> If yes then most likely duplicate of #76548

Yes this is it, constant output while closing the terminal is the main way to repro it.

/duplicate
