### ISSUE TITLE
Cannot add include path to settings. 

### ISSUE THREAD

**Issue by Antranilan** [Microsoft/vscode#11346]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Hover over any green squiggle in a source file (e.g. a #include statement).
2. Click the lightbulb that appears underneath the mouse cursor.
3. Click Add include path to settings.

c_cpp_properties.json does not generate/cannot find a directory of the file

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-cpptools#194

**Comment by sridmad** [comment]
@Antranilan - What is the version of the extension?

**Comment by Antranilan** [comment]
0.9.0

**Comment by Cloudwu1** [comment]
@Antranilan  No sure if you opened a file or a folder. If you only open a file, it seems by design.
