### ISSUE TITLE
Indentation in html syntax during my django project

### ISSUE THREAD

**Issue by Aakash007-ai** [microsoft/vscode#113447]
Issue Type: <b>Feature Request</b>

While developing my django based project :-
the syntax is not indented  automatically while creating html files

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-53-generic

**Comment by aeschli** [comment]
Can you give a small code sample and steps to reproduce?
