### ISSUE TITLE
Cannot load assembly <assembly name>. Powershell

### ISSUE THREAD

**Issue by Koan-om** [microsoft/vscode#113492]
- VSCode Version:
- [Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

[OK] [Copy]
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1.Clean install
2.Install Powershell extention v2020.6.0
3.Open a .ps1 file with the first lines:
Using Assembly System.windows.forms
Using Assembly System.Drawing
Using Assembly System.XML

4. Squiggly lines appear after all Using Assembly commands with the message "Cannot load assembly <assembly name>. Powershell"
5. On the other hand the "Using NameSpace System.windows.forms" does not cause a warning message.
6. If i try to run the .ps1 file i get:
ParserError: C:\PS1\PD\PD.ps1:3:16
Line |
   3 |  Using Assembly System.windows.forms        
     |                 ~~~~~~~~~~~~~~~~~~~~        
     | Cannot load assembly 'System.windows.forms'.

7. The same .ps1 file runs alright on old Powershell ISE.

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
seems unrelated to vscode

**Comment by Koan-om** [comment]
Good day.
Could you tell me where i can submit a bug report related to Powershell extension?

**Comment by Koan-om** [comment]
Good day.
Could you tell me where i can post a bug report on Powershell extension for VSCode?
 
Regards
Kamil
 
 
С уважением
Камиль Измайлов
