### ISSUE TITLE
Debugger fails to use fopen from cstdio.

### ISSUE THREAD

**Issue by Eugenius63** [microsoft/vscode#113490]
Issue Type: <b>Bug</b>

Steps to reproduce:
On a fresh vscode and gcc install, according to vscode website's guide.
All .json files as created by default:

launch.json :
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}

```
tasks.json :
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\g++.exe",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```
Write this program:
```
#include <cstdio>
int main() {
    FILE *in = fopen("input.txt", "rt");
    if (in == nullptr) printf("Failed to open file.");
    fclose(in);
}
```
and save it as a .cpp file

In the same directory create an input.txt file.

Run debugger (F5) on the program above.

Notice that it fails to open the file. The debugger seems to not have the correct path to where to look for input.txt.

If instead of running debugger, you build the program and run it, it opens the file normally.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
In the launch config the "cwd" is set to come "bin" directory. Is this the location where the file "input.txt)" lives?

**Comment by Eugenius63** [comment]
@weinand
> In the launch config the "cwd" is set to some "bin" directory. Is this the location where the file "input.txt)" lives?

No, the source file, executable and input.txt are together elsewhere. I changed cwd to "${fileDirname}" and it seems to work fine now. Thanks.

**Comment by weinand** [comment]
@Eugenius63 launch configurations are specific to individual debuggers. VS Code knows nothing about launch config properties like "cwd". I don't know when and how the "cppdbg" debugger extension configures "cwd". If you think the "cppdbg" debugger extension configures "cwd" incorrectly, please file an issue here: https://github.com/microsoft/vscode-cpptools/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
