### ISSUE TITLE
program is not running

### ISSUE THREAD

**Issue by OneNOnlyHacker** [microsoft/vscode#113460]
when ever i run a program i am facing problem i have downloaded all extenction which are require and also downlaoded MinGW and add path of MingWD\bin but facing this problem help me.In Visual Studio Code

'g++' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sangwoo-98** [comment]
It seems to be not a problem of VS code itself. Seems like your environment variable for gcc compilers or other compilers are not set correctly.

**Comment by rng70** [comment]
Can you elaborate on your problem by providing some images of the environment variable section? It seems to be that your environment variable is not properly set. 

I am not sure about "MingWD\bin" but sure about "MinGW\bin". And as sangwoo-98 mentioned, it is not a problem of VS code itself. Check the version of gcc/g++ outside of vs-code and make sure it works properly.
