### ISSUE TITLE
Search in Files work incorrectly with Chinese pattern

### ISSUE THREAD

**Issue by jackie-wayland** [microsoft/vscode#113459]
- VSCode Version: 1.52.1
- OS Version: Windows 7

Steps to Reproduce:

1. create 5  text files, and copy the Chinese pattern "中文" into every files, and close all files tab in vs code window. 
2. search the chinese pattern "中文" using the  "Search in Files"
3. the chinese pattern can't be find!

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
What is the encoding of those files? If not UTF-8, you will have to set the `files.encoding` setting. This works for me.
