### ISSUE TITLE
cursor 

### ISSUE THREAD

**Issue by cutoche** [microsoft/vscode#113480]
Issue Type: <b>Feature Request</b>

cursor cambio su forma y no trabaja

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Please provide screenshot of window with this problem.
