### ISSUE TITLE
git localization for index should not be translated

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11344]
- VSCode Version: Code - Insiders 1.5.0-insider (1de4d832ccb061c13cf70eaf0221fbaa86abfbdd, 2016-08-31T06:16:16.953Z)
- OS Version: Linux x64 4.4.0-36-generic, Ubuntu 16.04

Related to #10283, likely happens in other languages as well.

Steps:

1. Launch code --locale=ko
2. Add a file to the git index
3. Right click the file
4. Select the "병경 내용 열기" context menu item

![image](https://cloud.githubusercontent.com/assets/2193314/18147742/e2c6ac90-6f8a-11e6-8d8c-41d83a6cf223.png)

/cc @joaomoreno

**Comment by dbaeumer** [comment]
@Tyriar you can localization bugs directly assign to @johnliu2016

**Comment by johnliu2016** [comment]
over localized "Index", @lukaschal need term linguistic review
gitServices.nls.resx.lcl

ResID: 
changesFromIndex
gitIndexChanges

**Comment by lukaschal** [comment]
@dbaeumer Should we revert this string on all langs to ENU without any linguistic input ?

**Comment by dbaeumer** [comment]
@joaomoreno can you please comment on this ?

**Comment by joaomoreno** [comment]
I have no idea. This question requires specific language knowledge to know if the term `index`` should be translated or not. @Tyriar says it shouldn't in Korean. I know it also should't in Portuguese. So I can only interpolate that it also shouldn't in every other language, based on my narrow sample.

**Comment by lukaschal** [comment]
@dbaeumer @joaomoreno  Please, is it possible to add ENU screenshot ?

**Comment by joaomoreno** [comment]
What is _ENU_?

**Comment by dbaeumer** [comment]
@joaomoreno ENU === English

**Comment by Tyriar** [comment]
en

![image](https://cloud.githubusercontent.com/assets/2193314/18286823/53fa5f0e-7429-11e6-8320-2568b23364fd.png)

ja

![image](https://cloud.githubusercontent.com/assets/2193314/18286540/1889a890-7428-11e6-8af2-3d65a1993d50.png)

After thinking about this a bit, the best translation may actually depend on the specific language. I don't think the current translations are useful though, Korean and Japanese phonetically spell out "index" in their native characters (indeksu, indekkusu respectively) as opposed to actually translating the word "index". I guess the best translation would be whatever git translates the word as, if git even localizes that is.

This is a little different to the `HEAD` case in #10283 as `HEAD` is an actual keyword that is frequently entered when using git. Index however is a *concept* rather than a keyword. I believe it should either be `index` or a proper translation to a native word, not what it is currently which is "index" spelled out in the native characters (potentially forcing the user to learn yet another word).

**Comment by lukaschal** [comment]
Waiting for linguistic input on all languages.

**Comment by lukaschal** [comment]
After linguist confirmation, all these strings reverted to ENU now.
