### ISSUE TITLE
In the terminal, click on the Shut down terminal button, VSCode hangs

### ISSUE THREAD

**Issue by youra-halloween** [microsoft/vscode#113428]
Create a terminal, use it.
At some point, it is not known for what reason. By clicking on the Shutdown terminal button - VSCode freezes completely.
This does not always happen. Randomly.

Version: 1.52.1 (user setup)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

List extensions:
aaron-bond.better-comments
abusaidm.html-snippets       
dbaeumer.vscode-eslint       
dracula-theme.theme-dracula  
eamodio.gitlens
esbenp.prettier-vscode       
felixfbecker.php-debug       
felixfbecker.php-intellisense
felixfbecker.php-pack        
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
GitHub.github-vscode-theme
GitHub.vscode-pull-request-github
imanilchaudhari.yii2-snippets
jamesmaj.easy-icons
junstyle.php-cs-fixer
MS-CEINTL.vscode-language-pack-ru
msjsdiag.debugger-for-chrome
octref.vetur
oliversturm.fix-json
xabikos.JavaScriptSnippets
ZainChen.json

**Comment by YouraHalloween** [comment]
This is ridiculous! I initially tried using the Report Bug service, I thought it would attach all the metadata. But instead, when submitting the report, he wrote that the text was too long and sent me to github. I thought, "This is very strange, but Okay, apparently he attached all the metadata." I added some text and clicked Add.
Apparently, the Send Report service is not working correctly.
