### ISSUE TITLE
in markdown, cmd+click on invalid link to create new file doesn't work

### ISSUE THREAD

**Issue by qiaojy19** [microsoft/vscode#113475]
I usually  use cmd+click on an invalid link to create new markdown  file.

However, this function seems to not work recently. I don't know why.

I have tried in macOS and Windows, the latest update version of VS Code, they both don't  work.

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ksundong** [comment]
I have same problem.

**Comment by liushilive** [comment]
I have same problem.

VSCode Version: 1.51.1 proper functioning

![image](https://user-images.githubusercontent.com/13434707/103517618-65d99880-4ead-11eb-9f4a-16d607c00a0a.png)

**Comment by hediet** [comment]
It would be nice when following a link to a non-existent relative file in markdown documents would open a suited custom editor if one is registered. I don't know if custom editors can be opened if the target file does not exist yet though.

**Comment by bartholomew-gander** [comment]
Yesterday I took a look at code for Markdown preview and do not see any traces of mentioned functionality (creating new file after clicking link). I might be able to add it but I already see that some checks would be necessary.
@qiaojy19 did you meant "click" functionality in Markdown preview, or in Markdown file editor?

**Comment by bartholomew-gander** [comment]
I've added commit with proposition on how it can be fixed. It works for both editor, and preview.
Known issues:
- New file disappears after saving, but I'm not sure if it's in the scope of this
- This code will not prevent you from creating file outside of your workspace, eg. you can have pointer to ../../some-file, and this will still open new editor windows with that default location.

This is my first commit to vscode so any feedback will be appreciated.

https://github.com/bartholomew-gander/vscode/commit/fb9c00961e1a21471e17d88bac26c3c3f49b919c

**Comment by qiaojy19** [comment]
> Yesterday I took a look at code for Markdown preview and do not see any traces of mentioned functionality (creating new file after clicking link). I might be able to add it but I already see that some checks would be necessary.
> @qiaojy19 did you meant "click" functionality in Markdown preview, or in Markdown file editor?

hi, I mean in file editor. 
In the past years or months, I always use something like `[aa](xx/xx/aa.md)`, then I use ctrl + click at `aa.md`, it will hint me that the file is not existed, do you want to new a file? Then I click yes, and a file will be created at the directory `xx/xx/`

**Comment by liushilive** [comment]
![1615172484047 00_00_00-00_00_30](https://user-images.githubusercontent.com/13434707/110269194-28ed6780-7ffe-11eb-9129-784a07da7f30.gif)

**Comment by qiaojy19** [comment]
> > > Yesterday I took a look at code for Markdown preview and do not see any traces of mentioned functionality (creating new file after clicking link). I might be able to add it but I already see that some checks would be necessary.
> > > @qiaojy19 did you meant "click" functionality in Markdown preview, or in Markdown file editor?
> > 
> > 
> > hi, I mean in file editor.
> > In the past years or months, I always use something like `[aa](xx/xx/aa.md)`, then I use ctrl + click at `aa.md`, it will hint me that the file is not existed, do you want to new a file? Then I click yes, and a file will be created at the directory `xx/xx/`
> 
> ![1615172484047 00_00_00-00_00_30](https://user-images.githubusercontent.com/13434707/110269194-28ed6780-7ffe-11eb-9129-784a07da7f30.gif)

yeah! What I mean is this function! I checked my vscode. The version is latest. However, I still can not use this function. ctrl+click can not create new file. And I still don't know what is the reason.

![image](https://user-images.githubusercontent.com/11640301/110272681-b6808580-8005-11eb-82d3-f9bec747e54a.png)

**Comment by liushilive** [comment]
> > > > Yesterday I took a look at code for Markdown preview and do not see any traces of mentioned functionality (creating new file after clicking link). I might be able to add it but I already see that some checks would be necessary.
> > > > @qiaojy19 did you meant "click" functionality in Markdown preview, or in Markdown file editor?
> > > 
> > > 
> > > hi, I mean in file editor.
> > > In the past years or months, I always use something like `[aa](xx/xx/aa.md)`, then I use ctrl + click at `aa.md`, it will hint me that the file is not existed, do you want to new a file? Then I click yes, and a file will be created at the directory `xx/xx/`
> > 
> > 
> > ![1615172484047 00_00_00-00_00_30](https://user-images.githubusercontent.com/13434707/110269194-28ed6780-7ffe-11eb-9129-784a07da7f30.gif)
> 
> yeah! What I mean is this function! I checked my vscode. The version is latest. However, I still can not use this function. ctrl+click can not create new file. And I still don't know what is the reason.
> 
> ![image](https://user-images.githubusercontent.com/11640301/110272681-b6808580-8005-11eb-82d3-f9bec747e54a.png)

Version functionality after 1.51.1 is invalid

**Comment by qiaojy19** [comment]
> > > > > Yesterday I took a look at code for Markdown preview and do not see any traces of mentioned functionality (creating new file after clicking link). I might be able to add it but I already see that some checks would be necessary.
> > > > > @qiaojy19 did you meant "click" functionality in Markdown preview, or in Markdown file editor?
> > > > 
> > > > 
> > > > hi, I mean in file editor.
> > > > In the past years or months, I always use something like `[aa](xx/xx/aa.md)`, then I use ctrl + click at `aa.md`, it will hint me that the file is not existed, do you want to new a file? Then I click yes, and a file will be created at the directory `xx/xx/`
> > > 
> > > 
> > > ![1615172484047 00_00_00-00_00_30](https://user-images.githubusercontent.com/13434707/110269194-28ed6780-7ffe-11eb-9129-784a07da7f30.gif)
> > 
> > 
> > yeah! What I mean is this function! I checked my vscode. The version is latest. However, I still can not use this function. ctrl+click can not create new file. And I still don't know what is the reason.
> > ![image](https://user-images.githubusercontent.com/11640301/110272681-b6808580-8005-11eb-82d3-f9bec747e54a.png)
> 
> Version functionality after 1.51.1 is invalid

yeah, I uninstall vscode, and instal versino 1.51.1, I can use the ctrl+click to create new file. Thank you very much!

**Comment by liushilive** [comment]
# recovered

版本: 1.55.2 (user setup)
提交: 3c4e3df9e89829dce27b7b5c24508306b151f30d
日期: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by qiaojy19** [comment]
> # recovered
> 版本: 1.55.2 (user setup)
> 提交: [3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d)
> 日期: 2021-04-13T09:35:57.887Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042

thank you so much!!!
I just update vs code to 1.55.2 on Mac, the it still doesn't work...

**Comment by maqiv** [comment]
Hello everyone

Any updates on this issue? Going back to an older version to solve the problem is not a suitable solution to me.

Greetings

**Comment by crifan** [comment]
same problem here. Already found this issue months ago. but found still existed now. Hope somebody fix it ASAP. Thanks.

**Comment by liushilive** [comment]
> # 已恢复
> 版本：1.55.2（用户设置）
> 提交：[3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d)
> 日期：2021-04-13T09：35：57.887Z
> 电子：11.3.0
> 铬：87.0.4280.141
> Node.js
> ：12.18.3 V8：8.7.220.31-electron.0
> 作业系统：Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/13434707/117941128-6216c080-b33c-11eb-84a1-1d40367073d0.png)

New version defunct!!!

**Comment by myflowpl** [comment]
for me it still doesn't work in 1.56.1 😢
may be there are some settings I have to change ?

![image](https://user-images.githubusercontent.com/3133380/117944790-ea31a180-b30d-11eb-944a-4cafaf725fc2.png)

**Comment by crifan** [comment]
> > # 已恢复
> > 版本：1.55.2（用户设置）
> > 提交：[3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d)
> > 日期：2021-04-13T09：35：57.887Z
> > 电子：11.3.0
> > 铬：87.0.4280.141
> > Node.js
> > ：12.18.3 V8：8.7.220.31-electron.0
> > 作业系统：Windows_NT x64 10.0.19042
> 
> ![image](https://user-images.githubusercontent.com/13434707/117941128-6216c080-b33c-11eb-84a1-1d40367073d0.png)
> 
> New version defunct!!!

obviously your system is **Win**, but still **NOT** fix for our **Mac** version.

**Comment by jeanp413** [comment]
Created a PR #130815 fixing this
