### ISSUE TITLE
Lines in Terminal Disappearing After Running Code

### ISSUE THREAD

**Issue by ExoticGG** [microsoft/vscode#113400]
- VSCode Version: 1.52.1 and 1.53.0-Insider
- OS Version: Windows 10 Home 1909

Steps to Reproduce:

1. System.out.println(); 3 random values (or more)
2. Run the code multiple times.
3. After a few repetitions, some lines in the terminal will disappear: See first run where the "1" is missing:
![image](https://user-images.githubusercontent.com/67757364/103111829-0367d900-461f-11eb-9bb2-715dda413efd.png)
![image](https://user-images.githubusercontent.com/67757364/103111831-08c52380-461f-11eb-8282-a64b72441366.png)
4. I suspect this is a bug with the way lines are displayed: Here are all the terminal settings that are modified: 
![image](https://user-images.githubusercontent.com/67757364/103111681-addefc80-461d-11eb-88ba-8f0304b6e4f2.png)
![image](https://user-images.githubusercontent.com/67757364/103111683-b5060a80-461d-11eb-89cb-d614d3870c61.png)

Does this issue occur when all extensions are disabled?: Yes/No
No. Don't know how to run Java without extensions.

**Comment by meganrogge** [comment]
Does zooming in and out or changing the renderer type help?

**Comment by ExoticGG** [comment]
Thanks for your response. Either I had an extremely strange and vivid dream or this was somehow fixed overnight. <br>
Thanks for the help!
