### ISSUE TITLE
Add a quick intellisense navigation search to the explorer tab. 

### ISSUE THREAD

**Issue by rmaheedharan** [Microsoft/vscode#11340]
- VSCode Version: 1.4.0
- OS Version:

When I have 1000 files within the folder and when I need to get to a file, I have to manually go though the list and select it. Instead if there is a intellisense textbox on top of the explorer that helps to get the file immediately if I type the first three characters of the file name.

I feel this feature will be great to implement.

**Comment by dbaeumer** [comment]
Ctrl+P should do the trick. You can type the filename you are looking for.

**Comment by rmaheedharan** [comment]
Great, Thank you!
