### ISSUE TITLE
global search cant find the file in .git

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode#113409]
vscode:1.52.1
os: macos 11.1

global search cant find the file in .git
// conf in user setting, workspace dont reset this conf

    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "output": true,
        "**/CVS": true,
        "**/.git": true,
        "**/.svn": true
    },
    "files.exclude": {
        ".*": false,
        "**/CVS": true,
        "*.a": true,
        "**/a.out": true,
        "**/.DS_Store": true,
        "**/.git": true,
        "**/.hg": true,
        "*.o": true,
        "*.so": true,
        "**/.svn": true
    },

**Comment by roblourens** [comment]
You can set `"search.useIgnoreFiles": false`

**Comment by Kurt-Shiwz** [comment]
> You can set `"search.useIgnoreFiles": false`

the problem is "search.exclude" is not effect(` "**/.git": true,`).

```
"search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "output": true,
    "**/CVS": true,
    "**/.git": true,
    "**/.svn": true
},
```

**Comment by roblourens** [comment]
If you want to search in .git, you need to set that to `false`

**Comment by Kurt-Shiwz** [comment]
make it enable, "search.exclude" will effect.
![image](https://user-images.githubusercontent.com/7554917/103600512-8dc70b80-4f42-11eb-9314-a8804db3d8f6.png)

**Comment by Kurt-Shiwz** [comment]
> If you want to search in .git, you need to set that to `false`

ensure it enable, "search.exclude" will effect.
![image](https://user-images.githubusercontent.com/7554917/103600621-d4b50100-4f42-11eb-8e32-ab8929124bbf.png)
