### ISSUE TITLE
I accedendly pressed remember my choise

### ISSUE THREAD

**Issue by ubgamingpro** [microsoft/vscode#113408]
it happened when I solved all problem in launch and tasks.json and started debugging

**Comment by ubgamingpro** [comment]
this is copy of my incompleted game file









#include <iostream>
#include <conio.h>
#include <windows.h>
#include <linux.h>
#include <dos.h>
#include <macOS.h>
#include <android.h>

#define SCREEN_WIDTH 1900
#define SCREEN_HIEGHT 1900

"images":
{
    "title":
     {   "image" : "MINECRAFT Real Life edition:MINECRAFT Real Life edition.png",




copy of launch.json















{
	"version": "0.2.0",
	"configurations": [
	    {
		"name": "cl.exe build and debug active file",
		"type": "cppvsdbg",
		"request": "launch",
		"program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
		"args": [],
		"stopAtEntry": false,
		"cwd": "${workspaceFolder}",
		"environment": [],
		"externalConsole": false,
		"preLaunchTask": "cl.exe build active file"
	    }
	]
    }



copy of tasks.json
















{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "cl.exe build active file",
			"command": "dotnet cl.exe build active file",
			"type": "shell",
			"group": "build",
			"presentation": {
			"reveal": "silent"
			},
			"problemMatcher": "$msCompile"
		}
	]
}

**Comment by ubgamingpro** [comment]
how can I clear remember my choice

**Comment by weinand** [comment]
I don't understand. What was the "remembered choice"?
