### ISSUE TITLE
Support ESM for editor worker

### ISSUE THREAD

**Issue by aryzing** [microsoft/vscode#113448]
It would be great if we could add esm support for the editor worker [here](https://github.com/microsoft/vscode/blob/90724cd823aa34cd9e955a6d7164953c1ae01d7d/src/vs/base/worker/defaultWorkerFactory.ts#L19). Currently, the second argument of the `new Worker()` expression can't be configured to allow esm scripts.

In any case, grateful for the examples using webpack & co. on how to get it to work. As esm support increases (or is used in development like with [snowpack](https://www.snowpack.dev/concepts/how-snowpack-works#unbundled-development)), having the option to allow the worker to use modules would be great! You would really come full circle given that you already publish the editor code in esm format.

**Comment by alexdima** [comment]
@aryzing You could define on your side `MonacoEnvironment.getWorker`. Then you can instantiate the WebWorker yourself and just return its instance.
