### ISSUE TITLE
Can't create breakpoint with vscode `version 1.52`

### ISSUE THREAD

**Issue by Abbyyan** [microsoft/vscode#113485]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Use [Native debug ](https://github.com/WebFreak001/code-debug) to debug cpp with vscode `version 1.52`, can't create breakpoint on the editor side bar.
2. Change to vscode version `1.51`, it works and the breakpoint works perfectly.

**Comment by Abbyyan** [comment]
OK, it's because the extension doesn't give the obvious language supported by this extension like [contributes.breakpoints](https://code.visualstudio.com/api/references/contribution-points#contributes.breakpoints) in `package.json`. Modify the extension and show the [language.identifiers](https://code.visualstudio.com/docs/languages/identifiers). Or you can enable the breakpoint for all files like https://github.com/microsoft/vscode/issues/112288#issuecomment-743456329

**Comment by weinand** [comment]
This issue has been fixed in the latest VS Code stable (1.52.2). There is no need to patch the package.json.
