### ISSUE TITLE
Sync feature suddenly disabled

### ISSUE THREAD

**Issue by yuriykaz** [microsoft/vscode#113450]
Issue Type: <b>Bug</b>

Hi, I was trying some new themes in my VS Code, installing and removing, and the sync function was suddenly disabled.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.87GB (12.28GB free)|
|Process Argv|--crash-reporter-id f3c7514d-3196-4990-8f75-0600989cdc22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-mysql-client2|cwe|2.8.7
vscode-html-css|ecm|1.4.0
prettier-vscode|esb|5.8.0
vscode-firefox-debug|fir|2.9.1
vscode-mysql|for|0.4.0
hclappscancodesweep|HCL|1.1.3
mssql|ms-|1.10.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
debugger-for-chrome|msj|4.12.11
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by jaintj95** [comment]
@yuriykaz - Same happened with me. Just wait for a while and try to turn on settings sync and it will work.

https://github.com/microsoft/vscode/issues/113694

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/91286
