### ISSUE TITLE
Refactoring Not Available

### ISSUE THREAD

**Issue by KoshankGarg** [microsoft/vscode#113417]
Issue Type: <b>Bug</b>

Refactoring suddenly stopped working, it was working fine but now  when I use the refactor shortcut, I am getting 'Rectoring Not Available' popup.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (2.68GB free)|
|Process Argv|--crash-reporter-id 3820579d-8d07-49da-8001-584a5338f171|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-data-class-generator|Ben|0.4.4
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.18.0
flutter|Dar|3.18.0
material-icon-theme|PKi|4.4.0
errorlens|use|3.2.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30236573
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

![Issue](https://user-images.githubusercontent.com/76247437/103135239-f1e50680-46dc-11eb-9360-886cc971a32d.png)

**Comment by KoshankGarg** [comment]
Hello,

Can you please update.

Regards,
Koshank

**Comment by mjbvz** [comment]
Please file this against dart/flutter

**Comment by rashek** [comment]
Ctrl+. in Code opens the “lightbulb” menu showing all code fixes/refactors.

**Comment by ancileddu** [comment]
Hello everyone, I've been having the same problem for a couple of days now. I have tried uninstalling / installing vscode. I also tried to uninstall all extensions. I only re-installed the official dart and flutter extensions. What can I do? Help me please

**Comment by rashek** [comment]
Hit  . +ctrl

**Comment by ancileddu** [comment]
Really thanks. You saved me. Thanks
