### ISSUE TITLE
Expose API to modify declarative language configuration (such as comments)

### ISSUE THREAD

**Issue by dan-c-underwood** [microsoft/vscode#113495]
With Arm assembly, the character used in assembler files can vary from toolchain to toolchain (some use `@`, some use `;`). It would be useful to provide users of my extension the ability to select which character is used by that particular toolchain. 

As far as I'm aware, because comments are from declarative configuration files there is no mechanism exposed to override them.

The issue is explained further in: https://github.com/dan-c-underwood/vscode-arm/issues/19

**Comment by alexdima** [comment]
You could use the semantic coloring API to tweak the tokens generated by TM. Although that API is not designed specifically for this scenario, I think you could use it to conditionally "correct" TM coloring based on user settings.

**Comment by dan-c-underwood** [comment]
What would the best solution be for toggling line and block comments? Would it be a case of building in keymaps that link to those same settings?

**Comment by alexdima** [comment]
I think the builtin toggle line comment / toggle block comment commands just work, regardless of tokens.
