### ISSUE TITLE
Wrong highlight if there are duplicate strings in completion item

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#113404]
- VSCode Version: 1.52.1
- OS Version: MacOS Big Sur 11.1

If a suggestion contains two "div", the second "div" is wrongly highlighted after "di" is entered

![div](https://user-images.githubusercontent.com/8640918/103114926-9e05fd80-469b-11eb-8211-81d53189c122.gif)

Does this issue occur when all extensions are disabled?: No, with my customed completion extension

**Comment by HaoboGu** [comment]
@jrieken I'd like to open a PR to fix it, would you please give me some hints about where can I start?

**Comment by HaoboGu** [comment]
Step to reproduce it:

1. Create an extension, use the following `extension.ts`
```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const provider1 = vscode.languages.registerCompletionItemProvider('plaintext', {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
			const simpleCompletion = new vscode.CompletionItem('⭐div classname=""></div>');
			return [simpleCompletion];
		}
	}, ' ', '.', '<');
	context.subscriptions.push(provider1);
}

export function deactivate() {}
```
2. Set activateEvent in `package.json`:
```json
"activationEvents": [
		"*"
	],
```
3. open a txt and enter character "d"
![image](https://user-images.githubusercontent.com/8640918/103371327-248e6500-4b0a-11eb-8dca-4632225de15f.png)

only the later "d" is highlighted

**Comment by jrieken** [comment]
Understood. Our fuzzy score function treats certain characters as separators, like `_` and `.`. However, emojis and such aren't on that list. The code is here: https://github.com/microsoft/vscode/blob/696dca786ac73ca0779a65e18f4bdb613d66b26f/src/vs/base/common/filters.ts#L466

**Comment by HaoboGu** [comment]
> Understood. Our fuzzy score function treats certain characters as separators, like `_` and `.`. However, emojis and such aren't on that list.

@jrieken Thanks for the hint! Here is another case, the later match of `di` is highlighted even though the first character is not emoji nor symbol.
![image](https://user-images.githubusercontent.com/8640918/103535623-08a10f80-4ecc-11eb-8e2a-c40e3eb2f58e.png)

It seems that just adding emoji or symbols to `isSeparatorAtPos` couldn't solve the entire problem.

**Comment by jrieken** [comment]
That is a different case. Having `adiv` and `di` isn't match for us because the first match (`d` in `ad`) is considered weak. A strong match is one after a separator or a the word start and matches much start with a strong match.

**Comment by HaoboGu** [comment]
So the `adiv` case is by design, right?

**Comment by jrieken** [comment]
yes, see here https://github.com/microsoft/vscode/issues/53715

**Comment by HaoboGu** [comment]
Thanks, I'll open a PR to fix the emoji case ;D

**Comment by connor4312** [comment]
This doesn't seem to be working for me in the latest Insiders. I don't see the highlight after the emoji, and the match doesn't come up if I start typing `div` in a suggestion that contains only `⭐div`

![](https://memes.peet.io/img/21-01-74e3d65d-d8bb-4e43-8109-3b0ab2e1b7e1.png)

**Comment by HaoboGu** [comment]
> This doesn't seem to be working for me in the latest Insiders. I don't see the highlight after the emoji, and the match doesn't come up if I start typing `div` in a suggestion that contains only `⭐div`

Can you try other emoji like ✨ ？
In my insiders it works:
![image](https://user-images.githubusercontent.com/8640918/105933249-12600200-6089-11eb-9726-2452778f1d0e.png)

It seems that '⭐' is not included by https://github.com/microsoft/vscode/blob/5da5495a7f84723dd2d9052bfb66639a531abeb0/src/vs/base/common/strings.ts#L776-L782

**Comment by HaoboGu** [comment]
@alexdima do you have any suggestions on it? I would like to fix `isEmojiImprecise` if possible

**Comment by jrieken** [comment]
Not critical for this release, moving to February

**Comment by alexdima** [comment]
I've created https://github.com/microsoft/vscode/issues/115221 to track the `isEmojiImprecise` problem.

**Comment by connor4312** [comment]
I can verify it works with ✨, so I'll close this and mark as verified pending Alex's new issue
