### ISSUE TITLE
Settings sync cannot be turned on because the current version is not compatible with the sync service.

### ISSUE THREAD

**Issue by CAProjects** [microsoft/vscode#113439]
Version: 1.50.0
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:03.989Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux arm 5.4.79-v7l+

Steps to Reproduce:

1. Install latest version ( .Deb Arm 32bit) on a raspberry pi
2. go to settings
3. Click Turn on Settings Sync
4. Sign in with an account
5. Get error message
   *  `Settings sync cannot be turned on because the current version  
(1.50.0, 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3) is not  
compatible with the sync service. Please update before  
turning on sync.`

Does this issue occur when all extensions are disabled?: **Yes**

![image](https://user-images.githubusercontent.com/23136480/103150165-564da780-4769-11eb-88a5-df3c02621328.png)

![image](https://user-images.githubusercontent.com/23136480/103150179-6feeef00-4769-11eb-82f3-903a37438d56.png)

**Comment by yume-chan** [comment]
Have you ever synced using that account on a newer version of Code?

Isn't the latest version for arm 32-bit deb also 1.52.1? https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-armhf points to `code_1.52.1-1608136275_armhf.deb` for me.

**Comment by sandy081** [comment]
You are on older version of VS Code and latest is `1.52` - https://code.visualstudio.com 

Please install latest version and try again.
