### ISSUE TITLE
Make explorer file search search for whole words.

### ISSUE THREAD

**Issue by abhijit-hota** [microsoft/vscode#113465]
### I have a long list of files in the explorer:
![image](https://user-images.githubusercontent.com/8116174/103168356-78722300-4858-11eb-917c-64daa43b456e.png)

### I search (type with the explorer in focus) for the word "modal":

It searches for the letters m, o, d, a and l. I don't know if this is expected and I'm using it wrong or a bug.
![image](https://user-images.githubusercontent.com/8116174/103168461-6f358600-4859-11eb-8ca6-8899938c2e8e.png)

### Expected

It should search for the whole word, not just the letters.

P.S.
- I have tried using it as a regex search but it's not that.
- I have searched in the issues for duplicates but couldn't find any.
- If I have missed a setting or an existing feature, please point me towards it and close this issue.

**Comment by isidorn** [comment]
I guess this is a feature request against the tree to not fuzzy search but regular search, thus forwarding to Joao

**Comment by joaomoreno** [comment]
Sorry but this was closed out of scope: https://github.com/microsoft/vscode/issues/66913
