### ISSUE TITLE
1 paste requires 2 undo operations to revert

### ISSUE THREAD

**Issue by johnchurchill** [microsoft/vscode#113453]
- VSCode Version:  1.52.1
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Copy a single line of code which is within other code (ts, html, doesn't seem to matter, as long as there is indentation) - example: `</div>` which is within another div
2. move to end of line, press enter (cursor will be aligned under first div), and paste, now it's: `</div>` (new line) `</div>`, with second one aligned with last open `<div>`
3. press cmd-Z - the new `</div>` does not go away, instead it becomes aligned with the first one
4. press cmd-Z again. Now the second `</div>` goes away

I would expect 1 undo would take me back to how the editor existed before I pressed cmd-v. But it appears that the auto-indenter is adding its own memo to the stack, and the editor's undo operation does not recognize that they are together.

Does this issue occur when all extensions are disabled?: Yes

**Comment by nrayburn-tech** [comment]
Do you have the format on paste setting enabled?
Like you mentioned, the paste and format are probably being treated as separate modifications.

**Comment by johnchurchill** [comment]
I looked that setting up, and no it was not set.
I tried with and without that setting, and sometimes it needs one undo, and sometimes two. It depends on what content I'm copying and pasting. It's pretty erratic.

**Comment by alexdima** [comment]
This sounds like it is caused by `"editor.autoIndent": "full"` (the default). The idea is that text that is pasted and differs in indentation to your code gets "auto indented" to the right indent level for you. You can turn this off via `"editor.autoIndent": "advanced"` for example.

**Comment by nrayburn-tech** [comment]
I think the question is, should the paste action take up multiple events in the undo stack?  When pasting, I can see how it would make sense to a user that it is only one single action and should be undone with one command.

**Comment by alexdima** [comment]
Well, the problem is that by default, in vscode, paste can lead to an extra step after pasting caused by adjusting indentation. This extra step could produce undesireable effect, and it can therefore be undone separately. It is similar in thinking to format on paste, but it is indentation auto-adjust on paste...

**Comment by nrayburn-tech** [comment]
I agree that it can be beneficial keeping them separate.

Would this be something that a user setting could be used to control?  If it is enabled, then these side effects would be combined with the previous action.  Then it would only require 1 undo.
How feasible is it to track these side effects and push them into a single undo action?

**Comment by alexdima** [comment]
I personally don't think it is that big of a deal to justify a setting. If there are a lot more people hitting this, then I would add a setting. In my mind, pasting is pasting and adjusting. You can undo once to get the verbatim paste and twice to undo the paste completely.

If we want to add a setting, this can be easily implemented [here](https://github.com/microsoft/vscode/blob/ffef9abe92426af2801e885e67cd38f3b748b7f1/src/vs/editor/contrib/indentation/indentation.ts#L586), by removing the call to `this.editor.pushUndoStop();` and instead calling `this._editor.popUndoStop()` to remove the undo stop introduced by the core paste handler.
