### ISSUE TITLE
English versions of Terminal commands in command palette don't show up

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11345]
- VSCode Version: Code - Insiders 1.5.0-insider (1de4d832ccb061c13cf70eaf0221fbaa86abfbdd, 2016-08-31T06:16:16.953Z)
- OS Version: Linux x64 4.4.0-36-generic, Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/18147898/957d659a-6f8b-11e6-8f78-c1c1a8e16f3c.png)

**Comment by Tyriar** [comment]
@dbaeumer is this something I need to do on my side? I think I'm doing the same as output.contribution.ts which shows up fine in English.

**Comment by dbaeumer** [comment]
@bpasero can you comment on this. My understanding is that @Tyriar needs to do something to make this work.

**Comment by bpasero** [comment]
I fixed this already. https://github.com/Microsoft/vscode/commit/e63da2416b97dafa04906812e22c97a0ce788a02

**Comment by Tyriar** [comment]
Thanks @bpasero!
