### ISSUE TITLE
O PROMPT DO VSCODE NÃO ABRE PARA DIGITAÇÃO DE COMANDOS

### ISSUE THREAD

**Issue by ednsinf** [microsoft/vscode#113493]
We have written the needed data into your clipboard becau
Issue Type: <b>Bug</b>

AO ABRIR O VS CODE, O PROMPT DO POWERSHELL NÃO ABRE PARA DIGITAÇÃO DE COMANDOS

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.91GB (12.24GB free)|
|Process Argv|--crash-reporter-id d838a4bc-d80d-4bd3-9762-e1f7afea1281|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vue-format|feb|0.1.8
vetur|hik|0.24.1
vue-snippets|hol|1.0.4
rest-client|hum|0.24.4
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
vuex-suggest|mis|1.1.1
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
angular-console|nrw|15.0.0
vetur|oct|0.31.3
vue-beautify|pea|2.0.4
material-icon-theme|PKi|4.4.0
code-settings-sync|Sha|3.4.3
material-theme|zhu|3.9.12

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

se it was too large to send. Please paste.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
