### ISSUE TITLE
Confirmation for action like `Enable / Disable All Extenions`

### ISSUE THREAD

**Issue by kanlukasz** [microsoft/vscode#113444]
VSCode should require confirmation for  `Enable / Disable All Extenions` operations.
Something like `"Are you sure?"`

Example scenario:
If you have 50 extensions, some are enabled, some are disabled, and you click  `Enable / Disable All Extenions` by accident, then it's hard to figure out what was enable and what wasn't

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/108541
