### ISSUE TITLE
Add `activityBarFocus` when clause context

### ISSUE THREAD

**Issue by zzzachzzz** [microsoft/vscode#113477]
There exists a when clause context for `sideBarFocus`, among others. As far as I know there is not one for the Activity Bar, for instance, `activityBarFocus`. I noticed this when trying to set up a conditional key bind for toggling the activity bar visibility.
https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by usernamehw** [comment]
Maybe visible context would be enough? `config.workbench.activityBar.visible`

**Comment by isidorn** [comment]
Correct, we do not have a `activityBarFocus` context key. It is a fair feature request that we add it, thus leaving this open for now.
@usernamehw suggestion might also be helpful.
