### ISSUE TITLE
Diff should show trailing spaces

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11349]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Make some changes to include trailing spaces
2. Open git diff view

VSCode: 
![screen shot 2016-08-31 at 3 42 17 pm](https://cloud.githubusercontent.com/assets/4033249/18148910/8cddbc22-6f91-11e6-802d-cb1b51ad44ef.png)

Real changes:
<img width="1067" alt="screen shot 2016-08-31 at 3 43 16 pm" src="https://cloud.githubusercontent.com/assets/4033249/18148928/ad6e4916-6f91-11e6-941d-19eaf61840e9.png">

**Comment by hashhar** [comment]
Set `"diffEditor.ignoreTrimWhitespace": false`.
![2016-09-09_11-19-39_1366x768](https://cloud.githubusercontent.com/assets/10473142/18376762/67efe526-767f-11e6-81dd-5af5a0e631d8.png)

**Comment by octref** [comment]
@hashhar 

Thanks a lot for telling me these hidden features!
