### ISSUE TITLE
Error displaying terminal name

### ISSUE THREAD

**Issue by SimonDudu** [microsoft/vscode#113411]
- VSCode Version: 1.52.1(user setup)
- OS Version: Windows_NT X64 6.1.7601

Steps to Reproduce:

1.Start VS Code
2.Open the project to the workspace
3.Open integration terminal
4.The integration terminal name is displayed as Dingtalk

Does this issue occur when all extensions are disabled?: Yes/No  
No
![B1DC9F13-5738-402e-B40D-231E7A569C3C](https://user-images.githubusercontent.com/57025175/103128131-03271680-46cf-11eb-8715-c34132739663.png)

**Comment by meganrogge** [comment]
Hi pls disable all extensions and reload the window to see if the issue persists
