### ISSUE TITLE
[folding] Permit the unfold '...' at end of line to unfold recursively (not just fixed to 1 level)

### ISSUE THREAD

**Issue by ddorsett** [microsoft/vscode#113418]
Currently the '...' at the end of the header line of a folded function only unfolds 1 level, would like a preference to have this unfold recursively

**Comment by aeschli** [comment]
Just to mention: `Shift+click` on the folding indicator already unfolds recursively.

**Comment by ddorsett** [comment]
The Shift-click def what I want, thanks. Now what I'd like is a way to swap the click and shift-click behavior (make the unfold recursively the default)
