### ISSUE TITLE
Remote-SSH - Switch Hosts

### ISSUE THREAD

**Issue by sachit-menon** [microsoft/vscode#113479]
Hi and thanks for the great work! Perhaps there is already an easy way to do this that I just don't know. I do remote work on a cluster of many machines; the Remote-SSH plugin is great for using one machine, but often if a particular machine is under high usage by others, I need to switch to a different machine on the cluster to do the same work (they share memory, the files are the same). 

I currently have each machine configured separately, and when I need to switch I connect to the new host, then open everything I had open previously, but this is kind of time consuming to do repeatedly. What would be great is a simple 'Switch Hosts' command that would let me keep everything as is but switch machines - that is, **in one click switch machines and open everything up to the same state I was in on the original machine**. 

This sounds like it would be straightforward given what's already built in, and I'm sure many users have multiple machines sharing memory in this cluster-like setup! It would save a lot of time in the long run. Thank you for your consideration and please let me know if anything is unclear. 

(I created an issue here before realizing the Remote VSCode repo might be a better place for this, I'm happy to delete one of them if it's in the wrong place.)

**Comment by roblourens** [comment]
Will reply on https://github.com/microsoft/vscode-remote-release/issues/4235, thanks
