### ISSUE TITLE
Enter key doesnt work

### ISSUE THREAD

**Issue by savinspm** [microsoft/vscode#113489]
Issue Type: <b>Bug</b>

I can't use my key "enter" in VSCode. It happens today for first time

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 9|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|. --crash-reporter-id f9514ac4-4fcb-466b-b221-fd98cd4d5a4d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (98)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
latex-preview|ajs|0.5.1
arepl|alm|2.0.1
code-gnu-global|aus|0.2.2
vscode-django|bat|1.0.1
vscode-intelephense-client|bme|1.5.4
path-intellisense|chr|2.3.0
laravel-blade|cjh|1.1.2
gitignore|cod|0.6.0
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
c-cpp-compile-run|dan|1.0.13
vscode-markdownlint|Dav|0.38.0
python-preview|don|0.0.4
vscode-html-css|ecm|1.5.0
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.62
prettier-vscode|esb|5.8.0
vscode-diff|fab|1.4.0
php-debug|fel|1.14.5
auto-close-tag|for|0.5.9
code-runner|for|0.11.1
readthedocs-vscode|gep|0.4.0
gc-excelviewer|Gra|3.0.40
vscode-back-forward-button|gri|0.1.3
CppSnippets|har|0.0.15
beautify|Hoo|1.5.0
HdsCppSnippets|hua|0.0.1
output-colorizer|IBM|0.1.2
r|Iku|1.6.2
path-autocomplete|ion|1.17.0
latex-workshop|Jam|8.15.0
vscode-edit-csv|jan|0.5.3
nbpreviewer|jit|1.2.2
vscode-insertdatestring|jsy|2.3.0
vsc-python-indent|Kev|1.12.0
cmake-tools-helper|mad|0.2.1
MagicPython|mag|1.1.0
rainbow-csv|mec|1.8.0
render-crlf|med|1.5.16
dotenv|mik|1.0.1
vscode-clang|mit|0.2.3
vscode-html-format|moh|0.0.4
prettify-json|moh|0.0.3
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.9.0
vscode-language-pack-es|MS-|1.52.2
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
veriloghdl|msh|1.3.6
vscode-sanddance|msr|3.1.0
autodocstring|njp|0.5.4
printcode|nob|3.0.0
indent-rainbow|ode|7.4.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.10.0
open-html-in-browser|pea|2.1.3
vscode-gitignore-generator|pio|1.0.2
psi-header|psi|1.14.1
java|red|0.73.0
format-html-in-php|rif|1.7.0
laravel-artisan|rya|0.0.27
partial-diff|ryu|1.4.1
matlab-snippets|sky|1.11.0
guides|spy|0.9.3
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
code-spell-checker-spanish|str|1.0.7
latex-utilities|tec|0.3.7
python|tht|0.2.3
pdf|tom|1.1.0
latex-support|tor|3.5.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.0
tensorflow-snippets|vah|0.3.3
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0
vscode-icons|vsc|11.0.0
clang-format|xav|1.9.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
material-theme|zhu|3.9.12
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by savinspm** [comment]
I will check it but I can say in advance that it has happened when I had two files opened. A python script and other big text file (around 40Mb) which I was processing. I will keep you update! Thank you

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<Enter>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`<Enter>`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
