### ISSUE TITLE
Comment Block Background Color

### ISSUE THREAD

**Issue by serhanbakir** [microsoft/vscode#113478]
Currently vs code (1.52.1) do not allow user to change the background color of the comment section. 
As foreground color I request that **background color to be adjustable** for comment blocks. 
Thanks!

![Comment Background Color](https://user-images.githubusercontent.com/11442487/103178958-85af0200-4898-11eb-8ee1-7c95335a67cc.png)

**Comment by ArturoDent** [comment]
As a workaround, you could use the extension https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight
