### ISSUE TITLE
"file copy + rename" scenario explorer bug on Mac OS

### ISSUE THREAD

**Issue by gbezyuk** [microsoft/vscode#113446]
- VSCode Version: Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.2.0
- OS Version: Mac OS Catalina 10.15.2

Steps to Reproduce:

1. Copy a file using the Explorer (cmd+C, cmd+V), and then QUICKLY (in under half a second)
2. Hit "Enter" to rename the file

Expected behaviour: file name is being edited, until the next "Enter" hit.
Observed behaviour: after less than a second, file name edit loses focus, and further typing goes to the explorer search instead

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is fixed in latest insiders.
Dup of https://github.com/microsoft/vscode/issues/111652
