### ISSUE TITLE
Timeline view missing

### ISSUE THREAD

**Issue by garrettwilliamson11** [microsoft/vscode#113544]
Issue Type: <b>Bug</b>

Hello, I'm on version 1.52 for vscode, and I do not see a timeline view. I haven't disabled this feature in settings.json, or anything like that. I've found no documentation on how to enable it. Can you please assist?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.22GB free)|
|Process Argv|--crash-reporter-id 55cc835e-4124-4a59-9b12-eb8c2617bb3e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459:30237187

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you see it if you press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> (or <kbd>F1</kbd>) and execute  `> Source Control: Focus on Timeline View` ?

**Comment by garrettwilliamson11** [comment]
That command does not appear to work. I’m new to vscode, so it’s possible I’m not entering this properly. Here’s what I see:

[cid:image001.jpg@01D6DDEA.240B62A0]

**Comment by IllusionMH** [comment]
Looks like Github doesn't support attaching images from emails so I can not see it.

Do you have git repo set up in this folder?

**Comment by garrettwilliamson11** [comment]
![image](https://user-images.githubusercontent.com/74317706/103307480-20652900-49de-11eb-88a4-1ec94473274c.png)

^Let's see if that works.

But in answer to your question, ah, it's very likely that I do not. I didn't realize that was a requirement, and I don't immediately see a setting to enable it. Is there a document you could link me to? Sounds like it may be as simple as that.

**Comment by IllusionMH** [comment]
Latest mention of timeline that only lists only Git as built-in extensions that utilizes Timeline View https://code.visualstudio.com/updates/v1_44#_timeline-view

View will be shown only if there is at least one timeline provider registered and Git won't register one if there is no Git repo.
So to see this repo you either need active git repo and you'll see commits in timeline or use any other extension that provides info to timeline view.
