### ISSUE TITLE
xvfb-run launch.json debugger support

### ISSUE THREAD

**Issue by ringcrl** [microsoft/vscode#113524]
I want to execute a command like this `xvfb-run -s "-ac -screen 0 1280x1024x24" node test/index.js`, via launch.json，but I couldn't find a viable solution and wanted to ask for support

**Comment by weinand** [comment]
pls see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools
