### ISSUE TITLE
Developer Tools becomes all white when using Inspect Element on Windows

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#113530]
* from master, on Windows
* run `scripts\code.bat`
* open an editor
* press Ctrl+F
* open developer tools
* use inspect and pick the find widget input
Observe how developer tools becomes all white and is no longer usable:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/103270485-54c5ee80-49b8-11eb-9bad-9e89ab6eeb0a.gif)

I'm going to give it important because it is really really annoying to not have Inspect Element.

**Comment by IllusionMH** [comment]
Duplicate of #112172
