### ISSUE TITLE
Emmet Select Item does not select into script tags

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#113515]
Version: 1.53.0-insider (user setup)
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:33:38.481Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042

1. Create an HTML file with the following contents
```html
<script type="text/plain">
  <p></p>
</script>```

2. Place the cursor within the text/plain string
3. Run 'Emmet: Select Next Item' command

Expected: Emmet selects the opening `p` tag
Actual: Emmet does nothing

**Comment by rzhao271** [comment]
Code pointer:
nextItemHTML and prevItemHTML within selectItemHTML.ts manually search for the next node to use, but the next node to use might be one of those embedded script nodes.

**Comment by vinku** [comment]
I am willing to look into this.

**Comment by vinku** [comment]
Hey @rzhao271 , can you have a look at the PR?

**Comment by rzhao271** [comment]
Sorry I forgot about it, thanks for the ping!

**Comment by jrieken** [comment]
Verifies that this one case works but the "select next" seems very limited, e.g once I am at the `<p>` tag it doesn't advance any further. @rzhao271 Unsure if that's unwanted or not?

**Comment by vinku** [comment]
@jrieken , the select next supports opening tag, attributes etc. Since there is no opening tag after p it does not select anything else.

You can check the behavior here: https://docs.emmet.io/actions/select-item/
