### ISSUE TITLE
Auto update not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by paulcre99** [microsoft/vscode#113534]
- VSCode Version: 1.5.1
- OS Version: Linux x64 5.4.0-58-generic

Steps to Reproduce:

1. Wait for an update.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ATGardner** [comment]
I am not 100% sure it is related, but my insiders build has not been updated since 2020-12-21T12:33:38.481Z (commit 4a875e). I use both mac (big-sur) and Windows 10, and I seem to be stuck on that exact same commit.

**Comment by ATGardner** [comment]
I asked about it in Reddit, and it's related to Holidays + NYE. Updates should resume at around Jan 5th.
https://www.reddit.com/r/vscode/comments/knklvl/vscode_insiders_doesnt_update/

**Comment by Tyriar** [comment]
Yep we paused for a while as most of the team was out, things should start up again now.
