### ISSUE TITLE
`paths` option not working in jsconfig.json

### ISSUE THREAD

**Issue by davidchai717** [microsoft/vscode#113504]
- VSCode Version: .52.1
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. Included the following in jsconfig.json at the root level of the project:
`{
  "include": ["node_modules/cypress", "./cypress/**/*.js"],
  "compilerOptions": {
    "target": "es2017",
    "allowSyntheticDefaultImports": false,
    "baseUrl": ".",
    "paths": {
      "@testUtils/*": ["./testUtils/*"]
    }
  }
}`
2. Alias would not work still for @testUtils, even if I restart VSCode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share an example project

/needsMoreInfo
