### ISSUE TITLE
Convert to named export/convert to default export grayed-out

### ISSUE THREAD

**Issue by alber70g** [microsoft/vscode#113532]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create two files, one with a default export one with import
2. Try ctrl+shift+r, refactor code
3. Find that both options are greyed out

Does this issue occur when all extensions are disabled?: **Yes**/~~No~~

![convert-to-named-export-grayed-out](https://user-images.githubusercontent.com/516972/103274460-0289cb00-49c2-11eb-8bb8-31cc0eef25f9.gif)

**Comment by mjbvz** [comment]
That means the refactoring is disabled. Please share an example project if you don't think it should be

**Comment by alber70g** [comment]
@mjbvz How is the refactoring disabled? It's really just these 4 files. I make the files and then it doesn't work. How should I share this with you?

**Comment by mjbvz** [comment]
Please create a simple GitHub project with the code and share a link

**Comment by JamieMason** [comment]
I had the same problem @alber70g, I think it's because the function is unnamed – if you give the function a name first you should hopefully be then able to then use the refactoring.
