### ISSUE TITLE
Could not create temporary directory: Permission denied

### ISSUE THREAD

**Issue by EdgarLip** [microsoft/vscode#113555]
Issue Type: <b>Bug</b>

i get this error "Could not create temporary directory: Permission denied"

those commands does not help : 
sudo rm -Rf ~/Library/Caches/com.microsoft.VSCode.ShipIt
sudo rm -Rf ~/Library/Caches/com.microsoft.VSCodeInsiders.ShipIt

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 7b809862-30bf-444a-a54f-8e7b80c840b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-junos|cod|0.1.7
selected-lines-count|gur|1.4.0
saltstack|kor|0.0.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
text-power-tools|qcz|1.15.0
vscode-yaml|red|0.13.0
text-marker|ryu|1.11.0
jinjahtml|sam|0.15.0
jinja|who|0.0.8

</details>

**Comment by joaomoreno** [comment]
> i get this error "Could not create temporary directory: Permission denied"

When exactly do you get this error?
