### ISSUE TITLE
HTML .Class Problem

### ISSUE THREAD

**Issue by NathanielCW87** [microsoft/vscode#113513]
It started today, I would type a .Class for a tag in HTML and a Error would show up stating the .Class can't be found.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have HTML CSS Support (`ecmel.vscode-html-css`) installed? See related question on SO https://stackoverflow.com/questions/65459034/vs-code-css-class-selector-not-found-with-angular-and-bootstrap-5-beta

**Comment by Ginab972** [comment]
I'm having the same issues "css class selector name not found. This just started yesterday. id works fine. I keep all my work in separate folders. I opened a completed project that did not have this issues and now it does. Something had to change.
![class error 2020-12-28 160834](https://user-images.githubusercontent.com/76008560/103291005-d7e74480-49b8-11eb-9db5-54fa69ef39e2.png)

**Comment by IllusionMH** [comment]
Try with all extensions disabled.
if it doesn't report error without this extension - report problem in extension repo

**Comment by Ginab972** [comment]
I disabled the firefox extension and now my class's are working
