### ISSUE TITLE
Filename completion for imports?

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#11351]
- VSCode Version: 1.4.0
- OS Version: Mac OS 10.11.6

I haven't been able to figure out if VS Code will do file/path completion when using ES2015 `import`. It seems like it doesn't (it should IMO). Once I've typed in a path, I can cmd-click it to jump to the file, which is great, _except_ if the import is an absolute path, e.g.:

    import { something } from '/rootlevel/this/that';

Then VS Code has no idea what that file is. Is there some way to get this working?

**Comment by dbaeumer** [comment]
The TS team is working on this. See https://github.com/Microsoft/TypeScript/pull/9353

**Comment by ffxsam** [comment]
So, once this change is live, will it work if I'm using VS Code with `javascript.validate.enable` set to `false`?

**Comment by dbaeumer** [comment]
Yes.

**Comment by ffxsam** [comment]
Excellent. Thanks, Dirk!
