### ISSUE TITLE
[Live Share Web] Error: TreeError [FileExplorer] Tree element not found: [object Object]

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#113562]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:43.616Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66

Please note: I can also repro on the latest Insiders

This issue is only occurring in Live Share Web. We are currently opening Live Share Web with a folderUri:

const folderUri = `vsls:///?${sessionId}&${params}

This is undesirable as it results in an UNTITLED (WORKSPACE). To fix this I've switched it to use a workspaceUri as per the guidance of @bpasero in this issue #109619:

const workspaceUri = `vsls:///Visual Studio Live Share.code-workspace?${sessionId}&${params}`;

This worked! I then switched our vsls FileSystemProvider to return the correct content when there is an attempt to read a "Visual Studio Live Share.code-workspace" workspaceUri

Everything is working as expected until you do the following:

1. open files that are a few levels deep (sub directories) in the file explorer
2. reload the window in the same browser tab

The Live Share session will reload and because this is workspaceUri being reloaded it will try to restore the file explorer to be in the same state as it was previously. 

These errors are seen in the debug console:

![image](https://user-images.githubusercontent.com/8161247/103322103-a5a60900-49f1-11eb-8eee-4b8dabb4c120.png)

and the file explorer is broken - contains no files:
![image](https://user-images.githubusercontent.com/8161247/103322117-bb1b3300-49f1-11eb-95f2-e7e2af973bca.png)

It appears to be a timing issue. I've debugged and it looks like there is an attempt to refresh the subtree before our vsls FileSystemProvider has even had a chance to complete reloading (reading) the workspace file (readFile & readDirectories)

 Note: I've had to switch back to using the folderUri until we can resolve this issue.

This doesn't occur when we use a folderUri as on browser reload the folders are all collapsed. I think it still hits the issue but it is able to recover by simply collapsing all the folders - which resets the FileExplorer tree state

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
@jramsay since the steps to repro are a bit complex, let me ask you a few questions since you have the setup on your machine:

1. Can you see where the exception happens in the unminified code? Since the stack trace you posted looks minified and there is not much I can infer from it. You should be able to get the exception locations by F1 > developer tools > sources > break on exceptions. And there shuold be an option to use source maps
2. If you close all open files before reloading and collapse all folder in explorer than all works fine? Since then we should not restore anything?

**Comment by jramsay** [comment]
@isidorn: thanks, I tried closing all files and then collapsing all folders when I get the window onbeforeunload event from the browser. This event gets sent to our extension from the website (serverlessWorkbench).   Unfortunately that doesn't work though. Possibly because even when I try it manually I have to click the "Collapse folders" button twice to fully collapse all folders. The first time you press it it only collapses one level (same behavior on desktop). I tried executing this twice: 
 
vscode.commands.executeCommand('workbench.files.action.collapseExplorerFolders');

but I don't think there isn't enough time for that to complete before the browser reload happens.

I've debugged a bit and although still minified here is some additional info to show what is happening:

The issue is in [asyncDataTree's doRefreshNode on the call to setChildren](https://github.com/microsoft/vscode/blob/d6936dd524cc6542802db2da8696400fda311768/src/vs/base/browser/ui/tree/asyncDataTree.ts#L769)

On reload after the user has opened multiple subfolders in the workspace this throws a cancellation error. It goes into the catch  then tries to recover by collapsing the tree. This collapse fails though as this.nodes is empty in the model.


here is the callstack:

**Comment by isidorn** [comment]
Thanks for more details. Assigning to february to look in Debt week into this.
Let me know if this is blocking and I can look before...

**Comment by jramsay** [comment]
Thanks @isidorn - unfortunately it is blocking as resolving this one will be required for Live Share Web GA. Due to this issue we're unable to join Live Share Web using a workspaceUri. Unfortunately this means there are a few other GA bugs that remain active. Any chance you can look at it sooner and let me know if you need any additional help from my end?

**Comment by isidorn** [comment]
@jramsey I have pushed a potential fix for this issue. Namely when a new file system provider is regsitered we would set the whole new tree input - not only refresh the tree. Hopefully that should get the tree out of the bad state. I am not 100% this fixes the issue. I expect that your file system provider is registered only once ready.

It would be very cool if you try this out as soon as possible. And if it does not work then we can do a live debug session in some time that works both for you and me. Either today evening my time, or Monday evening.

**Comment by isidorn** [comment]
Let's reopen since @jramsay mentioned that this does not fix the issue for him

**Comment by jramsay** [comment]
Hi @isidorn: I'm available now if you want to take a look

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/commit/0a0537961c780170f11ffe2e6d120eb4dcbd1b84

**Comment by jramsay** [comment]
Verified (0a05379) fix resolves the issue. Tree is now visible but in the collapsed state on reload. Thanks @isidorn!

**Comment by isidorn** [comment]
Thanks for letting us know, adding verified label

**Comment by jramsay** [comment]
Confirmed the cleanup fix still works - thanks!

**Comment by isidorn** [comment]
Great, thanks a lot!
