### ISSUE TITLE
Setting Environment variables for Debugger itself not just target

### ISSUE THREAD

**Issue by tundy** [microsoft/vscode#113529]
I have multiple toolchains for different ARM platforms and so on.
To start GDB I have to specify LD_LIBRARY_PATH to toolchain's lib's directory otherwise it will not even start.

Variables in "envirnoment" settings are passed to debugged application and are not set up before starting gdb, so I can't use it to specify toolchain's library path.

Right now I'm using wrapper (export LD_LIBRARY_PATH  and exec real gdb) that is called in miDebuggerPath instead of real debugger. It would be nice to do it without it.

**Comment by tundy** [comment]
Maybe this should be moved to MIEngine?

**Comment by weinand** [comment]
This is a feature request/question for an individual debugger extension.
