### ISSUE TITLE
Naming files/folders exits randomly

### ISSUE THREAD

**Issue by james10424** [microsoft/vscode#113552]
- VSCode Version: 1.52.1
- OS Version: macOS 11.0

Steps to Reproduce:

1. Create a new file/folder with the side bar, or rename a file/folder by highlighting a file/folder and pressing enter in the side bar
2. Now we should be able to enter/edit the name of the file/folder
3. After a few seconds, the dialogue will close automatically, making it impossible to enter a file name

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Please see https://github.com/microsoft/vscode/issues/111652 - fixed in the Insiders' Build.
