### ISSUE TITLE
Evaluating document type on save like it is done on open

### ISSUE THREAD

**Issue by RayMacLewis** [microsoft/vscode#113547]
I am working a lot with bash scripts that do not have a file ending.
When I copy/paste an existing code block with the shebang line (`#!/bin/bash`)(I guess is used to identify its a bash script). I understand that it might not be useful to check the file type each time something was changed on a document but I would like that to happen when I hit <kbd>CTRL</kbd>+<kbd>S</kbd>.
At the moment I have to save and close the file and reopen it so that VS Code recognizes it as a bash file.

**Comment by bpasero** [comment]
I wonder if it should rather be on type even? At least when the mode is plain text, we should maybe detect on typing?
