### ISSUE TITLE
[UX] Indentation level unclear

### ISSUE THREAD

**Issue by ffxsam** [Microsoft/vscode#11358]
- VSCode Version: 1.4.0
- OS Version: Mac OS 10.11.6

I feel like the gutter (with line #s) should have a different color than the page background. With the two being the same color, it's difficult to tell if something is indented at all or not.

![image](https://cloud.githubusercontent.com/assets/12532733/18151877/353a36d8-6fa7-11e6-949f-721233a06594.png)

Compare to WebStorm:

![image](https://cloud.githubusercontent.com/assets/12532733/18151903/6aec3b6e-6fa7-11e6-9875-f716fad3400f.png)

**Comment by alexandrudima** [comment]
This is possible since a few releases. e.g.
```
"workbench.colorCustomizations": {
	"editorGutter.background": "#ff0000",
}
```
