### ISSUE TITLE
Terminal is not work properly in Linux version

### ISSUE THREAD

**Issue by lannyyip** [microsoft/vscode#113514]
Version: 1.52.1 as well as 1.51
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z (1 wk ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-128-generic

When I launch VS Code through Icon or terminal command, the VS Code is shown with empty content in Terminal tab. I can not even run my code, as I am using it for Python design.
Occassionaly, I want to check what's going wrong with 'code --verbose'. It happend that the Terminal tab work properly. I can run python script through this method.
Moreover, when I launch 'code --verbose', it promted in Terminal tab in VS Code that "bash: export: `:/usr/lcal/cuda-11.0/lib64': not a valid identifier". Not sure whether it is related to the issue. I check that /usr/lcal/cuda-11.0/lib64 in my system is valid and links to targets/x86_64-linux/lib/

**Comment by ahtyamovdanil** [comment]
i fixed it by enabling this option:
File -> Preferences -> Setting -> Features -> Terminal -> Inherit Env

**Comment by lannyyip** [comment]
Thank you. I tried and it works for me.
