### ISSUE TITLE
The scroll bar jumps up and down on its own

### ISSUE THREAD

**Issue by stelulocom** [microsoft/vscode#113592]
- VSCode Version: 15.2.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open VSCode
2. Found a bug

## bug video

https://user-images.githubusercontent.com/76684088/103355839-48da4980-4aea-11eb-8dc3-9c83838f433f.mp4

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by stelulocom** [comment]
https://user-images.githubusercontent.com/76684088/103355911-78895180-4aea-11eb-9f53-79b943ef69c2.mp4

**Comment by IllusionMH** [comment]
Unfortunately Github shows it only as 5 sec audio. Could you please reupload it?

**Comment by stelulocom** [comment]
https://user-images.githubusercontent.com/76684088/103356784-9bb50080-4aec-11eb-9633-8d72fb4301e0.mp4

**Comment by stelulocom** [comment]
https://user-images.githubusercontent.com/76684088/103357011-21d14700-4aed-11eb-8441-42baff4cacb9.mp4

**Comment by stelulocom** [comment]
Can you see that

**Comment by IllusionMH** [comment]
Yes, now video is visible, thanks.

Does it happens only when cursor is close to the scroll bar or any time?
Are there any hovers in editor when this start to happen?
Does it happen if you only have ASCII characters in file?

**Comment by stelulocom** [comment]
No, Basically I open up VSCode and he's like this.
Yes, my mouse hovers over my code.
Don't.

**Comment by stelulocom** [comment]
> Yes, now video is visible, thanks.
> 
> Does it happens only when cursor is close to the scroll bar or any time?
> Are there any hovers in editor when this start to happen?
> Does it happen if you only have ASCII characters in file?

**Comment by IllusionMH** [comment]
Is this issue supposed to be closed?

**Comment by stelulocom** [comment]
That problem was solved, but now it's back😥

**Comment by IllusionMH** [comment]
You can also try if it's reproducible in Insiders build https://code.visualstudio.com/insiders/

If yes - please provide minimal example of file content that causes this issue (if depends on content), value of `editor.wordWrap` setting if chaged, and reopen issue so it could be fixed.

**Comment by stelulocom** [comment]
Now it looks like this
https://user-images.githubusercontent.com/76684088/103363842-21d64480-4af7-11eb-9cdd-c29e6af0fc2f.mp4

**Comment by stelulocom** [comment]
I found this problem mostly when editing HTML files

**Comment by stelulocom** [comment]
> You can also try if it's reproducible in Insiders build https://code.visualstudio.com/insiders/
> 
> If yes - please provide minimal example of file content that causes this issue (if depends on content), value of `editor.wordWrap` setting if chaged, and reopen issue so it could be fixed.
Thank you.
