### ISSUE TITLE
unable to use check update and auto sync

### ISSUE THREAD

**Issue by Mustafa-Lashkarwala** [microsoft/vscode#113575]
Issue Type: <b>Bug</b>

check for update option not working every time he show me net::ERR_CERT_AUTHORITY_INVALID and auto sync show check log file 
log file show :- 
[2020-12-30 11:24:53.257] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2020-12-30 11:24:53.257] [userDataSync] [info] Auto Sync is disabled.
[2020-12-30 11:25:09.858] [userDataSync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest
Please See This Image.
![image](https://user-images.githubusercontent.com/76550123/103333248-4c8eb180-4a93-11eb-98b7-4901f5300c03.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3491)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (1.09GB free)|
|Process Argv|--crash-reporter-id b2366b99-c81e-40a9-8a01-7c919e1e073e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

![image](https://user-images.githubusercontent.com/76550123/103333248-4c8eb180-4a93-11eb-98b7-4901f5300c03.png)

**Comment by sandy081** [comment]
Seems to have proxy / network issues and hence you are not able to connect to our update or settings sync service.

@joaomoreno / @lszomoru  Is there a way user can test to check access to these services?
