### ISSUE TITLE
文本文件底部只留半屏空白

### ISSUE THREAD

**Issue by adai-w** [microsoft/vscode#113576]
Issue Type: <b>Feature Request</b>

在查看log文件时发现，在右边把进度条拉到底时没有内容，有一整屏的空白，每次都要先拉到底之后，再上划几行才能看到想看的内容，希望可以把整屏的空白改成半屏的空白。

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-126-generic

**Comment by bpasero** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
