### ISSUE TITLE
Allow to send feedback through other services than twitter

### ISSUE THREAD

**Issue by wesleyboar** [Microsoft/vscode#11357]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6
### Kind Words

Though I agree with issue [#7893](https://github.com/Microsoft/vscode/issues/7893), I support the existence of the feedback box. As a new software, this is an easy way to acquire immediate feedback. As a new user, this is a quick way to give feedback.
### Complaint

But some users do not participate in social media. This feedback box emphasizes Twitter for communication.
### Suggestion
- The links within the "Other ways to contact us" should be turned into sibling buttons to the Tweet button i.e. a GitHub "Issue" and/or "Request" button.
- There should be a button to provide positive feedback that does not require a social media account, perhaps a button that is equivalent to a `mailto:` hyperlink on a webpage.

**Comment by chrisdias** [comment]
We are [grooming our backlog](https://github.com/Microsoft/vscode/wiki/Issue-Grooming) this milestone and it is unlikely that we'll address this issue in the next 6-12 months.
