### ISSUE TITLE
C++ highlight partialy fails when same header includes twice in the same "loop"

### ISSUE THREAD

**Issue by markio00** [microsoft/vscode#113560]
![File h - ProgettoPao  WSL_ Ubuntu  - Visual Studio Code 30_12_2020 00_34_34](https://user-images.githubusercontent.com/13108446/103320762-f0963f80-4a36-11eb-926e-c292811f6ddd.png)

- VSCode Version: 1.52.1
- OS Version: WSL2 Ubuntu 20.04.1 LTS (focal) over Windows_NT x64 10.0.19041

Note:
Same issue even with insiders preview rining on base windows so i guess problem being not tied with WSL

Steps to Reproduce:

1. Create 2 C++ header files
2. Include them each other
3. Observ the variables declarations coloring all hite except for the primitive types and std namespace (not tried others)
4. delete the include directive from one of the headers
5. Observ how the coloration turns back on

Ohew

Does this issue occur when all extensions are disabled?: No, because c++ highlighting is tied to the C/C++ plugin and I also work in WSL so I have no real ways of havig it tested

**Comment by RMacfarlane** [comment]
Since this is caused by the C/C++ extension, please open this issue with that extension. Thanks!
