### ISSUE TITLE
Accessibility issue on closing file

### ISSUE THREAD

**Issue by dmlaziuk** [microsoft/vscode#113589]
- VSCode Version: 1.52.1
- OS Version:  Darwin x64 20.2.0 (macOS 11.1.0 BigSur)

Steps to Reproduce:

1. Open any file
2. Change something in it
3. Cmd+W to close the file
4. In alert window I cannot select any options except `Save file`. Arrow keys are not working. Tab key is not working. Alt+<any letter> is not working. The only way I can select `Don't save` is by using mouse or touchpad.

Does this issue occur when all extensions are disabled?: Yes

![Screen Shot 2020-12-30 at 16 01 20](https://user-images.githubusercontent.com/32341162/103353516-216b8880-4aba-11eb-94d3-c9b7473582cf.png)

**Comment by bpasero** [comment]
Please review the macOS help pages from Apple to learn more about dialog accessibility.
