### ISSUE TITLE
WorkspaceEdit.set doesn't clear edits for an uri when passed an empty arrray

### ISSUE THREAD

**Issue by Veykril** [microsoft/vscode#113512]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a `vscode.WorkspaceEdit` with at least one `vscode.TextEdit` for an uri.
2. call `vscode.WorkspaceEdit.edit` on the the workspace edit with the uri and an empty array of text edits.

The textedit array for the given uri will still contain all its elements afterwards.

I took a peek at the implementation(my typescript knowledge is very minimal):
https://github.com/microsoft/vscode/blob/a9bf16e00192e5da6b1067667a0b55a4593bcc5f/src/vs/workbench/api/common/extHostTypes.ts#L688-L706
but if I am not mistaken the first branch will never be taken, as empty arrays are still truthy correct?

On a second note the docs for `set` read
```
/**
 * Set (and replace) text edits for a resource.
 *
 * @param uri A resource identifier.
 * @param edits An array of text edits.
 */
```
which also seems wrong in regards to this implementation. It says it sets the edits but the implementation appends edits.

Does this issue occur when all extensions are disabled?: Not relevant

**Comment by jrieken** [comment]
> Create a vscode.WorkspaceEdit with at least one vscode.TextEdit for an uri.
> call vscode.WorkspaceEdit.edit on the the workspace edit with the uri and an empty array of text edits.

Please provide a code snippet for that
