### ISSUE TITLE
Проблеми с названием класов 

### ISSUE THREAD

**Issue by Radion111** [microsoft/vscode#113502]
При  названии  любого тега любим названиям   класа видает ошибку.
![image](https://user-images.githubusercontent.com/64467402/103234781-2b21ae80-4949-11eb-894e-ae5d2f824a08.png)
![image](https://user-images.githubusercontent.com/64467402/103234801-383e9d80-4949-11eb-8c4b-38be014183a4.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

See https://stackoverflow.com/questions/65459034/vs-code-css-class-selector-not-found-with-angular-and-bootstrap-5-beta for similar problem

**Comment by slyshykO** [comment]
@Radion111 так а в чем собственно проблема?  Опиши классы в CSS и предупреждения пропадут.
