### ISSUE TITLE
Página inicial sempre abrindo

### ISSUE THREAD

**Issue by mpiber** [microsoft/vscode#113542]
Issue Type: <b>Bug</b>

Detalhes de sistema:
VSCode: 1.52.1
SO: Linux x64 5.4.0-58-generic snap

Ubuntu 20.04.1 LTS
Gnome 3.36.8

O BUG é que sempre abre a página inicial ("Settings Sync") quando abro o vscode, mesmo estando desmarcado o checkbox ("Show this page on startup").

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic snap
Remote OS version: Linux x64 4.15.0-126-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1044)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|11.61GB (1.06GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id c2e95afe-fc4c-4ef3-b152-00332fb66764|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|12.1.0
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.5.4
vscode-standardjs|che|1.4.0
node-snippets|chr|1.3.2
dart-code|Dar|3.18.0
flutter|Dar|3.18.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.0
EditorConfig|Edi|0.16.4
php-debug|fel|1.14.5
code-runner|for|0.11.1
vscode-pull-request-github|Git|0.22.0
go|gol|0.20.1
phpcs|ika|1.0.5
vscode-docker|ms-|1.9.0
vscode-language-pack-pt-BR|MS-|1.52.2
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
reload|nat|0.0.6
material-icon-theme|PKi|4.4.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
code-spell-checker-portuguese|str|0.1.6
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.0.0
vscode-import-cost|wix|2.13.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30239448

```

</details>

**Comment by taismassaro** [comment]
> O BUG é que sempre abre a página inicial ("Settings Sync") quando abro o vscode, mesmo estando desmarcado o checkbox ("Show this page on startup").

The bug is that the `Settings Sync` page always shows up when I open vscode, even when the checkbox `Show this page on startup` is unchecked.

👍🏽

**Comment by sandy081** [comment]
VS Code does not has any Settings Sync page and I suspect this is by Settings Sync extension. Please file issue against the extension.
