### ISSUE TITLE
vscode default html extension tags are not case sensitive

### ISSUE THREAD

**Issue by meowWhat** [microsoft/vscode#113577]
- VSCode Version:1.45.0
- OS Version:  ubuntu 18.04 LTS

Steps to Reproduce:

1." Button"  is always resolved as "button", resulting in native hover, and completion overrides my plug-in's features

![image](https://user-images.githubusercontent.com/59830413/103336238-6ee3f780-4ab2-11eb-8e90-291118207d19.png)
![image](https://user-images.githubusercontent.com/59830413/103336251-7efbd700-4ab2-11eb-98ef-15e35265334b.png)

So how can I make native HTML plugins case-sensitive

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
According to the HTML spec, tag names and attribute names case insensitive. So `<button>` and `<Button>` both describe a button.

Not sure I understand your scenario correctly.

**Comment by meowWhat** [comment]
> According to the HTML spec, tag names and attribute names case insensitive. So `<button>` and `<Button>` both describe a button.
> 
> Not sure I understand your scenario correctly.

In my framework `<Button>` is a component 、`<button>` is a  tag node . 
But our  template file  extension  name is `.html` , because we want to use  VSCode HTML Support .
So how do i distinguish `<button>` and `<Button>` in HTML File .

**Comment by aeschli** [comment]
Ok, I see. You are using the HTML language server for a HTML like language. 

The proper solution would be to have your own language and language server. You could use the vscode-html-languageservice library to get the HTML functionality you want.

I'm not a fan of adding a new 'case sensitive' setting. It will be confusing to HTML users.
