### ISSUE TITLE
Feature: Rounded text cursor

### ISSUE THREAD

**Issue by manen** [microsoft/vscode#113500]
Self-explanatory: Add a setting to enable a rounded text cursor.

**Comment by Shiva7071007** [comment]
@manen can you post a image of the cursor you want?

**Comment by manen** [comment]
This is what it currently looks like (Cursor Style: line, Cursor Width: 3)
![Screenshot from 2020-12-29 14-22-11](https://user-images.githubusercontent.com/49951816/103286794-f2311a80-49d8-11eb-924f-8bf0812174c0.png)

And what I'd like is the same thing but rounded

![103286794-f2311a80-49d8-11eb-924f-8bf0812174c0](https://user-images.githubusercontent.com/49951816/103287402-5ef8e480-49da-11eb-8a03-9d8175c6b64d.png)

**Comment by manen** [comment]
ok
