### ISSUE TITLE
[New Feature Request] - Add a section that covers new features only

### ISSUE THREAD

**Issue by Corfucinas** [microsoft/vscode#113525]
With the increasing rate of new versions and updates to VS code, it would useful to have a section in settings that has the new features that can be modified.

Example:
With a new release, VS Code allows "x,y,z" new settings, instead of navigating the settings menu to find these new options, we could have a section within settings that shows exactly what Is new, this would make it simpler to navigate and adjust them.

**Comment by manen** [comment]
I would love to see that happen

**Comment by roblourens** [comment]
This has been discussed before (I can't find an old issue, sorry) but we don't think that the settings editor is the right place for something that duplicates part of the release notes, we would rather people read the release notes.
