### ISSUE TITLE
Search: preserve selected file after edits

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode#113584]
- VSCode Version: latest
- OS Version: latest

Steps to Reproduce:

1. Search for something
2. Select a search result
3. Add a new line above the result

Expected: the search result remains selected (pictured below)

<img width="300" src="https://user-images.githubusercontent.com/921609/103347440-eef86600-4a8e-11eb-89a6-c5daaed16e1d.png" />

Actual: the search result does not remain selected

Does this issue occur when all extensions are disabled?: Yes

### Context

I have the following workflow: I want to make edits to multiple files which match my search. I perform a search and go through the results by pressing F4. For each result, I would like to perform my edit and then proceed to the next result by pressing F4 again. Unfortunately this is not what happens, because as soon as I edit a result, the "selected search result" state is lost. This means that when I press F4, I'm taken to the first search result instead of the next search result.

https://user-images.githubusercontent.com/921609/103347444-f1f35680-4a8e-11eb-9056-204f9175ca6b.mov

**Comment by OliverJAsh** [comment]
This is very similar to https://github.com/microsoft/vscode/issues/20467 and https://github.com/microsoft/vscode/issues/29209 but I believe it is slightly different, because this issue is about the "selected" state being lost when a line _above_ the search result is modified (therefore the modified file should still appear in the list of results) whereas the other issues are specifically about what happens when you modify the text which was originally matched.

**Comment by roblourens** [comment]
This is the same as https://github.com/microsoft/vscode/issues/20467 - the bug is with anything that changes the line number of the selected match, meaning the identity of the selected item changes. I do really need to fix this.
