### ISSUE TITLE
Keyboard word selection does not include the space and is inconsistent with other editors

### ISSUE THREAD

**Issue by landofjoe** [Microsoft/vscode#11359]
- VSCode Version: any
- OS Version: Windows

Steps to Reproduce:
1.  Enter a string of words in the editor, such as "Today is going to be a good day."
2. Click anywhere in the sentence and select a word using Ctrl+Shift+Right Arrow.

The selection should include the word and the following space, if it exists.  This behavior is pretty standard in Windows applications, including the OS itself (try the "start>run" box), Microsoft Word and Visual Studio.  Since VSCode behaves differently in this regard, it results in excessive keyboard navigation and selection mistakes.

**Comment by alexandrudima** [comment]
@landofjoe 

(From https://code.visualstudio.com/updates/vMarch)

![image](https://cloud.githubusercontent.com/assets/5047891/18168937/5ee4cd2a-7058-11e6-947c-9442b9945575.png)
