### ISSUE TITLE
Objects with numeric or boolean enum values don't render in the Settings editor

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#113587]
according to [docs](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) 
> Other types, such as object and array, aren't exposed directly in the settings UI, and can only be modified by editing the JSON directly. Instead of controls for editing them, users will see a link to Edit in settings.json as shown in the screenshot above.

which is incorrect as we can access & change it though the UI, but with some limitation to the ext creator 😢 , 
as atm we can only have items of type `string` & when trying to use something else like `boolean` (which actually works) vscode will show an error of mismatch value type because of the outdated scheme.

the end goal is to have a dropdown list where user can chose meaningful options instead of having to edit it manually.

- example for ext config
```json
"autoPosthtml.togglePlugins": {
    "type": "object",
    "description": "toggle plugin",
    "default": {
        "schemes": true,
    },
    "properties": {
        "schemes": {
            "type": "string",
            "default": true,
            "enum": [
                true,
                false
            ],
            "description": "enable/disable schemes"
        },
    }
},
```

- settings ui editor
![Screen Shot 2020-12-30 at 2 39 52 PM](https://user-images.githubusercontent.com/7388088/103351832-2249ed80-4aad-11eb-9fcf-9ef7500a8139.png)

- but because of the current limitation we will get an error in the settings file
![Screen Shot 2020-12-30 at 2 43 19 PM](https://user-images.githubusercontent.com/7388088/103351957-7f45a380-4aad-11eb-8e6b-17f9b513abf9.png)

**Comment by roblourens** [comment]
Oh yeah, will fix the docs thanks.

I think the values in your "enums" should be strings, does that help?

**Comment by ctf0** [comment]
> I think the values in your "enums" should be strings, does that help?

not really, am after using it as a `boolean`.

**Comment by roblourens** [comment]
"enum" goes with "string". You just want `"type": "boolean"` I think

**Comment by ctf0** [comment]
yeap & support to other other types too, or would that be an issue ?

**Comment by roblourens** [comment]
I don't understand, you want enum to support other types?

**Comment by ctf0** [comment]
am after this part
```
"schemes": {
            "type": "string",
            "default": true,
            "enum": [
                true,
                false
            ],
            "description": "enable/disable schemes"
        },
```

so instead of being limited to only `string` we should be able to use any of the other supported types as well ex.`boolean, integer`

**Comment by roblourens** [comment]
Oh, you just want to use other types in the settings editor? Yes that isn't supported yet.

**Comment by rzhao271** [comment]
I confirmed the following:
- Numeric and boolean enum settings render in the Settings editor
- Numeric and bool object settings render in the Settings editor
- Objects with numeric or boolean enum values don't render in the Settings editor
