### ISSUE TITLE
"Filter" not persisted in breadcrumbs

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#113509]
### Steps to reproduce:

> 1. Open breadcrumbs
> 1. Type a search query, enable "Filter on type"
> 1. Close breadcrumbs
> 1. Open again and type something
> 1. "Filter on type" mode is disabled, but it should remember my preference like other trees do.

Does this issue occur when all extensions are disabled? : Yes

__________
### VS Code Version Details:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by jrieken** [comment]
That was done purpose, see https://github.com/microsoft/vscode/issues/75969. There is now a global setting for this: `workbench.list.keyboardNavigation`
