### ISSUE TITLE
Automatical semicolons when formatting document

### ISSUE THREAD

**Issue by gitowiec** [microsoft/vscode#113563]
Issue Type: <b>Feature Request</b>

When I use Jetbrains WebStorm I can do formatting the whole document. It is great because it not only auto indents lines of code but also inserts semicolons in proper places.
It just saves time a lot. Please add this feature for TypeScript and C#.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.6.17-050617-generic snap

**Comment by ArturoDent** [comment]
For typescript, see

 

>  // Defines handling of optional semicolons. Requires using TypeScript 3.7 or newer in the workspace.
>   //  - ignore: Don't insert or remove any semicolons.      <= the default
>   //  - insert: Insert semicolons at statement ends.
>   //  - remove: Remove unnecessary semicolons.

   `"typescript.format.semicolons": "insert"`

**Comment by mjbvz** [comment]
As noted, already exists for TS. 

Please file a separate issue against the c# extension
