### ISSUE TITLE
window.onDidChangeWindowState doesn't fire when the window is focused by clicking in a webview editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#113539]
Repro:

Create an extension containing:

```ts
window.onDidChangeWindowState(state => {
  console.log('state change', state.focused);
});
```

Watch logs when you focus/blur the window by clicking on the tab vs clicking inside a webview editor.

Version: 1.53.0-insider (user setup)
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:33:38.481Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by MrAndersen1** [comment]
This also seem to be the case when you focus the window by clicking the developer tools window.

**Comment by mjbvz** [comment]
I just tested this on MacOS with the latest VS Code insiders build using the webview sample and the events now seem to be fired expected


Closing for verification

**Comment by mjbvz** [comment]
@rchiodo With VS Code unfocused, did you try clicking onto a markdown preview? With the original bug this would not fire `window.onDidChangeWindowState`

However now `window.onDidChangeWindowState` should be fired in this case

**Comment by MrAndersen1** [comment]
@rchiodo The video makes it look like you expect onDidChangeWindowState to fire when switching editors within the window. My interpretation is that it is supposed to fire when switching between apps, just like the behavior that you described. The window being the app instance.

**Comment by rchiodo** [comment]
@mjbvz yes it fires the event for clicking in markdown preview. 

If this event only fires on app switching, it works just fine for me.
