### ISSUE TITLE
Terminal - last line overwriting itself in Window mode

### ISSUE THREAD

**Issue by aj02mirra** [microsoft/vscode#113501]
Issue Type: <b>Bug</b>

When writing the last line in the terminal of VS Code, it starts to overwrite itself. This only happens when in a windowed mode. 
![image](https://user-images.githubusercontent.com/59363043/103224611-00862480-494e-11eb-96a3-457aa27565f0.png)

When VS Code is maximized, this doesn't happen, and a new line comes up.
![image](https://user-images.githubusercontent.com/59363043/103224704-388d6780-494e-11eb-9d68-d52fbcb4099e.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.154.1
remote-wsl|ms-|0.52.0
vscode-icons|vsc|11.0.0
prettier-vscode|esb|5.8.0
terraform|has|2.3.0
vscode-docker|ms-|1.9.0
vscode-kubernetes-tools|ms-|1.2.1
vscode-yaml|red|0.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630

```

</details>

**Comment by meganrogge** [comment]
does zooming in and out or changing the renderer type resolve this?

**Comment by aj02mirra** [comment]
Maximizing the VS Code window resolves it.

Also, if I resize the VS Code Window, resolves it as well:
- Overwriting:
![image](https://user-images.githubusercontent.com/59363043/103338334-14dc3580-4aa4-11eb-9889-a22a93877945.png)

- Resizing the same window, produces 2 lines:
![image](https://user-images.githubusercontent.com/59363043/103338373-34735e00-4aa4-11eb-96c4-9516b8d60d63.png)

**Comment by meganrogge** [comment]
I am unable to reproduce the issue. Thanks for the info and glad resizing helps
