### ISSUE TITLE
If the terminal view is visible, a new terminal is not created on initial load in remote

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#113564]
Latest Insiders. Steps to Reproduce:

1. When connected to a remote, open the terminal view
2. Reload the window
3. A terminal is not created 🐛 

This works in the previous stable release. I think I might have seen this in other cases, but this is my easy repro. Maybe related to terminal reconnection logic?

Video: https://memes.peet.io/img/20-12-ecc65942-93a3-475f-b541-d5da656a8305.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by AliZaidi0786** [comment]
@connor4312 Can you please help me with VS Code.I am an beginner and it says "exited with code=2" don't know what to do.Please response if you aren't busy.Thank You!

**Comment by connor4312** [comment]
Please open a new issue using the instructions and details in the issue template

**Comment by meganrogge** [comment]
Hey Connor, thanks for bringing this to my attention. I'm not able to reproduce the issue with the latest insider's 
![recording (81)](https://user-images.githubusercontent.com/29464607/103328792-0abc2780-4a0f-11eb-8a01-8c80dea2ac13.gif)

**Comment by connor4312** [comment]
The problem seems to only happen with `"terminal.integrated.enablePersistentSessions": false`. I probably added that to my settings during verification. If that toggle is going away this issue can probably be closed. @roblourens / @alexdima  fyi.

**Comment by meganrogge** [comment]
I think this issue can be closed even if that toggle remains, since, by definition, it will not persist when that is set (as expected). Correct?

**Comment by connor4312** [comment]
I would not expect it to persist, but I would expect a new terminal to be started since the terminal view is visible (like it does locally)

**Comment by meganrogge** [comment]
Oh that makes sense
