### ISSUE TITLE
Eagerly show tab or Preview Editor when using "Quick open"

### ISSUE THREAD

**Issue by wprater** [Microsoft/vscode#11355]
When using Quick Open or editor stack `ctrl+tab`, the tab should be eagerly be selected so a visual context of the content can be seen below the quick open view pane.  

While navigation the view with your arrow keys, if selected editor tabs were open, they would be switched to, hitting escape would return to the tap you initiated the action on, hitting return would in effect keep you on the tab that was being eagerly shown (through open tabs or the Preview Editor).

This is very helpful to find the file you're planning to open.  It's heavily used feature of mine from ST3.

![image](https://camo.githubusercontent.com/397c67e42200857d1efc2d5b294e2bd36b2c24a4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f38323433372f313638363736332f30356136666433362d356465632d313165332d383035302d6463623637343030643632312e676966)

- VSCode Version: 1.5 insider
- OS Version: macOS

refs: https://github.com/atom/fuzzy-finder/issues/5

**Comment by bpasero** [comment]
Thanks for reporting this issue. Please use the issue search next time to see if there is a duplicate already. In this case, the issue has already been reported.

**Comment by wprater** [comment]
Certainly, I did some searching, but must have used the wrong terminology.  Shall I remove this one, or cross reference another issue?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8939
