### ISSUE TITLE
console.log issues (urgent)

### ISSUE THREAD

**Issue by Mbowman1221** [microsoft/vscode#113595]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Issue Type: <b>Performance Issue</b>

visual studio code will not let me console.log anything or fn f8 anything as well.
email is ragnarok769@gmail.com

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.80GB (6.40GB free)|
|Process Argv|--crash-reporter-id a6fd385c-6ced-4f13-9767-895a95663cec|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    74	  3408	code main
    1	    77	  3484	   window (Issue Reporter)
    0	    22	  6204	   crashpad-handler
    0	    36	 10304	   utility
    0	   156	 10404	   window (● loop - jsFundamentals - Visual Studio Code)
    0	    64	 17484	     searchService
    0	    91	 17772	     extensionHost
    0	    86	 17696	       "C:\Users\ragna\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\ragna\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=17772
    0	    12	 18304	     watcherService 
    0	    11	 18312	       console-window-host (Windows internal process)
    1	   201	 16564	   gpu-process
    0	    90	 18084	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● loop - jsFundamentals - Visual Studio Code)
|    Folder (jsFundamentals): 35 files
|      File types: js(20) jpg(1) html(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
git-project-manager|fel|1.7.1
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
vstry914:30236575
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by weinand** [comment]
Please provide reproducible steps.
