### ISSUE TITLE
Failure to backup custom editors close veto message should list problem tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#113627]
If backup fails for a custom editor, it may be hard to know which editor is the issue.

![image](https://user-images.githubusercontent.com/2193314/103414363-7d71f380-4b32-11eb-9c6e-0a402f0c3df6.png)

This message could be made more friendly by listing the problem files much like a regular dirty save dialog:

![image](https://user-images.githubusercontent.com/2193314/103414437-d477c880-4b32-11eb-8279-80e8987d5077.png)

I'm aware this ideally shouldn't happen, but it may be inevitable if the source of truth must be kept within the webview and `retainContextWhenHidden` is false. It wouldn't be a problem if we had https://github.com/microsoft/vscode/issues/113507, but the dialog improvement would be welcome still for misbehaving extensions.

**Comment by bpasero** [comment]
I really like the suggestion to list the editors that are still dirty after an attempted backup.

Code pointer: https://github.com/microsoft/vscode/blob/3b5cdf3a0ebe0ae332499cfa8b058b468a784dfc/src/vs/workbench/contrib/backup/electron-sandbox/backupTracker.ts#L127-L127

**Comment by mjbvz** [comment]
To verify: 

1. In the [custom editor sample]
2. In the `PawDraw.backup` method, throw an exception `throw new Error('hairball')`
3. Run the extension, open and edit a paw draw file, then try exiting the window (note that hotexit is disabled by default in extension development mode. You can package and install the extension instead to test this)

**Comment by Tyriar** [comment]
Works 👍 

![image](https://user-images.githubusercontent.com/2193314/104816359-84a22e00-57cf-11eb-9642-4e29a1f0fb41.png)
