### ISSUE TITLE
This bug is not fixed #30936 = resolution error

### ISSUE THREAD

**Issue by tengineerio** [microsoft/vscode#113671]
- VSCode Version:  1.52.1
- OS Version: windows 10

Steps to Reproduce:

1. open up a file dialog in windows 10 on a dell precision 5540
2. the resolution requires magnification but vs code doesn't respect it, and makes the window unusable.
3. this is 100 % reproduceable and very annoying because it makes vs ode unusable to open files with laptop open

Does this issue occur when all extensions are disabled?: Yes

**Comment by rzhao271** [comment]
Can you attach a screenshot showing the issue with the open file dialog?
