### ISSUE TITLE
<img src=" "> just can't find the image file, not on local folder, not outside, just don't show it.

### ISSUE THREAD

**Issue by HackingTheMatrix** [microsoft/vscode#113600]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by HackingTheMatrix** [comment]
Basically, all of a sudden, after uninstalling and reinstalling the HTML
preview extension, the images "jpg, jpeg, png," just won't show up, and the
files will only display in the browser when I insert the full path from
C:/, otherwise it's either being ignored or vscode tries to get them from a
wrong folder. Like...
if I have C:/users/user/desktop/myproject/mywebsite.html and
"C:/users/user/desktop/myproject/icons/trashcan.png"
when I look for this file and select it <img src="/icons/trashcan.png"> the
preview will show a tiny "broken" icon like not found, and when I try
opening site in the browser it does the same, unless I insert the full path
from C:/. I was wondering if VSCODE could be updated and bring its own
integrated HTML viewer with php maybe. Because I have some similar issue
with the action="file.php", it will always say file not found and it's
actually looking for the include in the main C:/ folder for some reason.
Besides that, if I write php and html together, it just works fine.
As a programmer who's just getting comfortable with this activity,
I'm sure that some kind of update would surely take some time. But it's
undoubtedly a great tool.

**Comment by mjbvz** [comment]
Please file this issue against your html preview extension
