### ISSUE TITLE
rebuild computer,and version back to 1.3

### ISSUE THREAD

**Issue by ericsoul1987** [Microsoft/vscode#11364]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.i have been upgrade this version many times;
2.when my computer rebuild,the version will be back to 1.3.

ps.my hard drive is SSD.

**Comment by joaomoreno** [comment]
Can you try uninstalling and [installing](http://code.visualstudio.com/Download) again?
