### ISSUE TITLE
Can we at least have "Do not show me again" for this thing?

### ISSUE THREAD

**Issue by rui-infotrack** [Microsoft/vscode#11361]
This happens after I installed eslint plugin and I think it tries to use global eslint-config-defaults package, which I didn't install and honestly I don't care, coz my project has local .eslintrc file. Point is, you can show that but please do not keep showing that. I clicked 'Close' but it just keeps showing up, which is so annoying.
![image](https://cloud.githubusercontent.com/assets/12144265/18153100/8300c278-703e-11e6-9ce9-09206b1bd794.png)

**Comment by dbaeumer** [comment]
This is on the plan, but requires some additional extension API. For now you can simple add the following settings to the workspace settings: `"eslint.enable": false`. This will disable eslint for that particular workspace.
