### ISSUE TITLE
System crash when switching desktop

### ISSUE THREAD

**Issue by 2ico** [microsoft/vscode#113663]
Issue Type: <b>Bug</b>

It is happening frequently that my system crashes when switching to another i3-wm desktop (on the same display), when VS Code is running in the first desktop.
I have installed the proprietary Nvidia drivers.
This is the output of journalctl:

[coredump_gpu.txt](https://github.com/microsoft/vscode/files/5759123/coredump_gpu.txt)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.9.14-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2237)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|15.49GB (9.89GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>

**Comment by rzhao271** [comment]
Does it still crash when running with --disable-gpu?
