### ISSUE TITLE
"terminal.integrated.env.linux" cannot override .bashrc variables

### ISSUE THREAD

**Issue by bafonso** [microsoft/vscode#113635]
- VSCode Version: 1.52.1
- OS Version: Manjaro Linux 5.9.11-3-MANJARO

Steps to Reproduce:

1. set variable already defined in .bashrc to a new value using "terminal.integrated.env.linux" in settings.json
2. start terminal and do "export | grep {variable}" and it does not override .bashrc value

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by meganrogge** [comment]
Duplicate of #47816
