### ISSUE TITLE
ELECTRON_RUN_AS_NODE=1 is set on cmd.exe started from bash inside terminal in remote WSL session

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode#113687]
Issue Type: <b>Bug</b>

I had a weird issue today with an Electron application misbehaving. Turns out that ELECTRON_RUN_AS_NODE=1 was set on the process, even though I certainly didn't set that, and it also doesn't exist in my system/user environment variables.

Turns out it's coming from VSCode, but it's not visible on the shell process directly, only on the cmd.exe child (VSCode's grandchild of sorts). This is WSL1.

**How to reproduce:** Open some folder as remote WSL1 session in VSCode, open terminal, enter `cmd.exe /c echo %ELECTRON_RUN_AS_NODE%`.

You'll see it comes back as `1`, even though it's empty inside bash itself:

```
david@CHE-X1:/mnt/c $ echo $ELECTRON_RUN_AS_NODE

david@CHE-X1:/mnt/c $ cmd.exe /c echo %ELECTRON_RUN_AS_NODE%
1
```

I'm running in WSL remote mode using WSL bash as default shell for almost all projects, because I'm extensively using tools I have installed in WSL and most projects are designed for a Linux environment. In this case there was a subproject that was designed to run in Windows as Electron application, but I wanted to manage it the same way as everything else (in fact it's part of a workspace which is set as remote WSL session). I was expecting to be able to launch Windows applications normally, like I can from a WSL terminal outside of VSCode, but it seems due to this weird issue I'm getting my environment polluted with various variables, including problematic ones like `ELECTRON_RUN_AS_NODE`.

VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:33:38.481Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.85GB free)|
|Process Argv|--crash-reporter-id c6356cfd-7a7a-4cee-93f1-a6019521c8bb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.86GB (2.85GB free)|
|VM|0%|
</details><details><summary>Extensions (85)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
Doxygen|bbe|1.0.0
vscode-standardjs-snippets|cap|0.8.15
LogFileHighlighter|emi|2.10.0
vscode-svelte-snippets|fiv|0.5.0
vscode-cloak|joh|0.3.0
Lua|key|0.0.9
vscode-nsis|Kry|0.0.1
VBScript|lug|0.0.2
dotenv|mik|1.0.1
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-ssh-explorer|ms-|0.56.0
remote-wsl|ms-|0.52.0
ejs-language-support|Qas|0.0.1
vscode-autohotkey|sle|0.2.2
vscode-todo-highlight|way|1.0.4
rebound-delete|aar|1.1.0
paste-fixer|aar|1.0.0
vscode-color|ans|0.4.5
svelte-intellisense|ard|0.7.1
vscode-intelephense-client|bme|1.5.4
htmltagwrap|bra|0.0.7
vscode-standardjs|che|1.4.0
npm-intellisense|chr|1.3.1
bracket-select|chu|2.0.2
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
insert-use-strict|cri|1.0.2
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
vscode-new-file|dku|4.0.2
vscode-npm-source|dku|1.0.0
xml|Dot|2.5.1
gitlens|eam|11.1.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
crystal-lang|fau|0.4.0
flow-for-vscode|flo|1.5.0
kaitai-struct-vscode|fud|0.7.0
gc-excelviewer|Gra|3.0.40
rest-client|hum|0.24.4
RelativePath|jak|1.4.0
hungry-delete|jas|1.6.0
join-comment-aware|joh|0.0.3
typings-autoinstaller|jvi|1.2.0
nodejs-repl|los|0.5.15
edge|luo|0.3.2
twig-language-2|mbl|0.9.2
rainbow-csv|mec|1.8.0
ecdc|mit|1.3.0
find-jump|mks|1.2.4
prettify-json|moh|0.0.3
vscode-cosmosdb|ms-|0.15.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.4
cpptools|ms-|1.1.3
powershell|ms-|2020.6.0
node-modules-resolve|nau|1.0.2
prettier-standard-vscode|num|0.8.1
svelte-extractor|pro|0.0.3
quicktype|qui|12.0.46
java|red|0.73.0
vscode-yaml|red|0.13.0
json-organizer|rin|0.0.4
LiveServer|rit|5.6.1
ActiveFileInStatusBar|Ros|1.0.3
vscode-paste-and-indent|Rub|0.0.8
bracket-jumper|sas|1.1.8
trailing-spaces|sha|0.3.1
rewrap|stk|1.13.0
ignore-gitignore|stu|1.0.1
svelte-vscode|sve|102.8.0
sort-lines|Tyr|1.9.0
use-strict-everywhere|vee|0.1.3
bracket-padder|via|0.3.0
codetour|vsl|0.0.42
gitdoc|vsl|0.0.6
quokka-vscode|Wal|1.0.335
change-case|wma|1.0.0
join-lines|wma|0.2.2
FilterText|yhi|0.0.15
html-css-class-completion|Zig|1.20.0

</details>

**Comment by weinand** [comment]
In my understanding Electron is never used (or available) in remote setups and consequently there is no need to use "ELECTRON_RUN_AS_NODE=1" to make Electron turn into "node.js".

**Comment by CherryDT** [comment]
Why wouldn't it be available? I understand that my use case in which I call a Win32 program from WSL is not something that was considered (but I still think it should work), but it's equally possible that it's a remote machine via SSH which you are debugging... and you could also run Electron there (either with X11 forwarding or with a parallel VNC connection to see the UI).

(In fact I also have a similar setup in a kiosk system which runs the UI with a fullscreen Electron window in Linux.)

**Comment by weinand** [comment]
@CherryDT ok, let me clarify my comment: Electron might be available but VS Code cannot rely on it.

In the "regular" (non-remote) case, VS Code relies on "node.js" being available as part of Electron (which is obviously available). So when an internal node.js process (e.g. the extension host) needs to be launched, VS Code sets ELECTRON_RUN_AS_NODE to 1 and launches Electron (which turns into node.js).

In a remote setup VS Code can not assume that Electron is available remotely and we rely on the normal node.js runtime. So there is no need to set "ELECTRON_RUN_AS_NODE" to control the behaviour of Electron.

**Comment by CherryDT** [comment]
Oh OK sorry, I misunderstood, I thought you meant that it's not available for the _user_ to use in their workflow so it's not considered what would happen to it.

What you said makes more sense, thanks for the clarification :)

**Comment by weinand** [comment]
Yes, in the remote setup Electron might be available on the remote machine if the user has installed it. And in that case it should not interfere with VS Code's internal environment variables.

**Comment by CherryDT** [comment]
> Could it be that the "ELECTRON_RUN_AS_NODE" env var leaks from the local client into the server?

It seems this is what's happening.

Even though the `[ -d ~/.vscode-server-insiders/bin/4a875e23d20b64504a818834f3fa4c40adb8d480 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)` command is actually run with the correct stripped-down environment, the following command `"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 4a875e23d20b64504a818834f3fa4c40adb8d480 insider .vscode-server-insiders 0  --disable-telemetry` is run with all the variables including `ELECTRON_RUN_AS_NODE`. This will cause any Win32 children eventually spawned by this server or its children to inherit the variable.

![image](https://user-images.githubusercontent.com/6010463/103538921-6a935200-4e97-11eb-8b30-fa989d163820.png)

![image](https://user-images.githubusercontent.com/6010463/103538980-80a11280-4e97-11eb-87a9-744c6f356e36.png)

**Comment by aeschli** [comment]
- open a WSL window
- open the integrated terminal and run `cmd.exe /c "SET && PAUSE"`
- observe that `ELECTRON_RUN_AS_NODE` is set

The process hierarchy is as follows:
```
Code-insiders.exe [Renderer]   :  ELECTRON_RUN_AS_NODE undefined
  Code-insiders.exe [Ext Host]    :  ELECTRON_RUN_AS_NODE=1
    Code-insiders.exe [WSL Deamon Process]   :  ELECTRON_RUN_AS_NODE=1
     WSL.exe
        [Server Running in WSL]
        cmd.exe ["SET && PAUSE"]
```

@bpasero @alexdima The ext host environment has `ELECTRON_RUN_AS_NODE=1` set, so all processes launched from extensions will inherit that. Ideally it doesn't have it set, but I assume there's nothing we can do there.

I would fix that in the WSL-Remote extension then when launching WSL.exe then.

**Comment by bpasero** [comment]
I think we cannot just remove `ELECTRON_RUN_AS_NODE` because there are child processes forked from the extension host that probably need it.

@deepak1556 do you know if it is possible to remove `ELECTRON_RUN_AS_NODE` environment from a process after it has been created? Or is that needed to fork further child processes?

**Comment by CherryDT** [comment]
> I think we cannot just remove `ELECTRON_RUN_AS_NODE` because there are child processes forked from the extension host that probably need it.

Are you sure? It was mentioned before in this thread the inside the remote environment, Electron isn't used, but even if it were - we are talking about the _Windows_ environment variable here (which isn't shared with the Linux processes unless configured in `WSLENV`, but _is_ shared with other Windows processes spawned as descendents by Linux processes).

So, if I understand correctly, removing the variable from the `wsl.exe` calls should not do any harm, unless you are saying that the _Linux_ extension host will also attempt to spawn _Windows_ processes which need this variable set...

**Comment by aeschli** [comment]
Pushed a fix to the Remote-WSL extension.

As an observation, it would be great if there were a way of running Electron as node that doesn't involve an env variable. The best would be a separate executable, A command line parameter would also simplify things. There's some tricky code in the Remote-WSL start scripts when we call from WSL to Windows-Electron that could be simplified.

**Comment by weinand** [comment]
BTW, I use this approach to delete the `ELECTRON_RUN_AS_NODE` variable once it has been used in a fork: 

https://github.com/microsoft/vscode/blob/fa593d83ad159cb9227d00db62cf334312ffa82a/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L212

**Comment by dbaeumer** [comment]
Verified using steps https://github.com/microsoft/vscode/issues/113687#issuecomment-755181308
