### ISSUE TITLE
command line launcher accept line number

### ISSUE THREAD

**Issue by alzix** [microsoft/vscode#113629]
When woking with command line tools (e.g. `git grep -n`) it is very convenient to be able to open file on a current line.
Same feature exists in vim: `$ vim some.file +155` will open `some.file` and move cursor to line 155.

Can we consider adding same functionality for vscode?
For example: `code some.file +155`

**Comment by ArturoDent** [comment]
See doc at https://code.visualstudio.com/docs/editor/command-line#_core-cli-options

There is an option to include goto lines.

**Comment by IllusionMH** [comment]
/question
It's already supported as mentioned in doc linked by @ArturoDent.

Thnanks for the link @ArturoDent!
