### ISSUE TITLE
Undo should be related only to the area on focus (file edit or file list)

### ISSUE THREAD

**Issue by sickdyd** [microsoft/vscode#113653]
VSCode version: `November 2020 (version 1.52)`

**Steps**
Write some code in a new file, rename the file, change the code and keep hitting `command + z` to undo.

**Problem**
While pressing `command + z` to revert changes, even if you cursor is in the text file, it will ask if you want to undo the file renaming.

**Expected**
Just undo edits in the code when the focus is on the text file where I write code.

**Rant**
I just want to undo edits to the code, not undo the renaming. The feature was supposed to undo only actions related to where the focus is set but it's not working, it just automatically goes from one stack to another.

**From your release notes**
> Undo file operations in Explorer#
>
> The File Explorer now supports Undo and Redo for all file operations: delete, rename, copy, move, new file, and new folder. Make sure the focus is in the File Explorer and trigger the Undo or Redo commands and your last file operation will be undone or redone respectively. Keep in mind that we have separate undo stacks for the editor and the File Explorer, and we choose which one to undo based on focus.

**Also: after I got this message, I was stuck, unable to redo or undo**
> Could not undo 'Rename index.ts to index.js' across all files. The following files have been closed and modified on disk: /Users/robertoreale/Desktop/webdev.nosync/playaround/api/src/index.ts.

```
CPUs | Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 32.00GB (1.87GB free)
Process Argv | --crash-reporter-id dc592e5f-dbee-4845-a19e-244f84d0ad99
Screen Reader | no
VM | 0%
```

Extensions
```

Extension | Author (truncated) | Version
-- | -- | --
copy-relative-path | ale | 0.0.2
simple-react-snippets | bur | 1.2.3
gitlens | eam | 11.1.0
prettier-vscode | esb | 5.8.0
vue-inline-template | fai | 1.0.1
html-slim-scss-css-class-completion | gen | 1.7.8
gc-excelviewer | Gra | 3.0.40
vscode-graphql | Gra | 0.3.13
ruby | gro | 0.1.0
vscode-edit-csv | jan | 0.5.3
vue | jcb | 0.1.5
vscode-styled-components | jpo | 1.4.1
haml | kar | 1.3.1
vscode-docker | ms- | 1.9.0
mssql | ms- | 1.10.0
remote-containers | ms- | 0.154.1
color-highlight | nau | 2.3.0
env-cmd-file-syntax | Nix | 0.2.2
vetur | oct | 0.31.3
ruby | reb | 0.27.0
rust | rus | 0.7.8
trailing-spaces | sha | 0.3.1
vscode-todo-highlight | way | 1.0.4
vscode-ruby | win | 0.27.0
material-theme | zhu | 3.9.12
```

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/111659
