### ISSUE TITLE
Source control Tab: Listed items are not rendring properly, there is a green line background  

### ISSUE THREAD

**Issue by hackrx** [microsoft/vscode#113690]
- VSCode Version: 1.52
- OS Version: macOS Big Sur (11.0.1)
## Before opening Release notes:
![image](https://user-images.githubusercontent.com/54453778/103457640-f5087400-4d26-11eb-9207-44b24aa876ca.png)
## After opening Release Notes:
![image](https://user-images.githubusercontent.com/54453778/103457545-4401d980-4d26-11eb-9de2-bf0b7e36338d.png)

Steps to Reproduce:

1. It sometimes happens, I don't know what is wrong here.
2. Sometimes it goes away when I reopen vs code but now it is persisting like this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hackrx** [comment]
After committing the changes, this behaviour disappears and it works normally.

**Comment by rzhao271** [comment]
Does launching vscode with `--disable-gpu` solve the issue?

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/111412

Can you also check if this is fixed in insiders https://code.visualstudio.com/insiders
