### ISSUE TITLE
Output of any python code in VSC isn't showing properly. It doesn't show the letters of all the words in Output. 

### ISSUE THREAD

**Issue by NothingIRL** [microsoft/vscode#113648]
![Issue 1](https://user-images.githubusercontent.com/25146865/103435181-3b7ba700-4c31-11eb-8904-f1ec63dda8a4.png)
![vsc](https://user-images.githubusercontent.com/25146865/103435187-3fa7c480-4c31-11eb-8d70-93799608d76b.png)
![issue 2](https://user-images.githubusercontent.com/25146865/103435209-a1682e80-4c31-11eb-96c8-0745d7158f8a.png)

Whenever I run a code in VSC, it doesn't show proper output. As you can see in the screenshots, it misses some letters randomly of any word. Even if I write print('Hello World'), it'll show 'He lo W rld'. I thought it might be an issue with my OS (Linux Mint XFCE), so I installed Linux Mint Mate LTS. Issue is still there. Code runs fine in Python IDLE. Please let me know if I missed to mention anything.
VS Code version - 1.52.1

**Comment by NothingIRL** [comment]
I tried VSCode Insider 1.53.0 and so far this still isn't there. Probably this is an issue with VS Code stable 1.52.1

**Comment by RMacfarlane** [comment]
Please open this issue on the Python extension. Thank you!
