### ISSUE TITLE
Bash tab completion failed to work when using Remote SSH

### ISSUE THREAD

**Issue by LittleYe233** [microsoft/vscode#113624]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows 7 Ultimate 64-bit (Internal Version: 7601 Service Pack 1)

I use RemoteSSH to connect with my Ubuntu 16.04 server and bash in the internal terminal cannot complete some words with tabs. What is weird that the completion works when nothing has been input (then the console returns lots of possibilities of all possible programs) but fails when something has been input (on this occasion I want bash to complete paths). So I guess maybe bash cannot complete **paths** instead of **all possible words**.

Steps to Reproduce:

1. Enable RemoteSSH extensions and connect with target server.
2. Open internal terminal.
3. Type `cd ` first for example.
4. Press `Tab` button. Nothing returns.

Does this issue occur when all extensions are disabled (except extensions related to RemoteSSH) ?: Yes

**Comment by meganrogge** [comment]
What are the keybindings you have set for tab?

You can also try to turn off chords in the terminal with this setting:

"terminal.integrated.allowChords": false

**Comment by LittleYe233** [comment]
> 
> 
> What are the keybindings you have set for tab?
> 
> You can also try to turn off chords in the terminal with this setting:
> 
> "terminal.integrated.allowChords": false

I found I was so busy that I forgot this issue... So sorry for my neglect!

As for your reply, I tested it and found the problem didn't solve. In addition, I have pasted contents of `~/.bashrc` and `/etc/bash.bashrc` in my first comment. Hope that will make sense.
