### ISSUE TITLE
No "Windows" tab on the upper main bar

### ISSUE THREAD

**Issue by ez202012** [microsoft/vscode#113607]
- VSCode Version: 1.52.1 (user set up)
- OS Version: windows 10 enterprise (64 bit)

Steps to Reproduce:

1. downed and installed the latest VS code
2. launch it, you can see there is  no  "Windows" tab on the upper main bar

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
What do you mean?
