### ISSUE TITLE
Problem with terminal

### ISSUE THREAD

**Issue by sayand0122** [microsoft/vscode#113695]
Issue Type: Bug
![Screenshot from 2021-01-02 20-18-18](https://user-images.githubusercontent.com/53222600/103459840-bd55f800-4d37-11eb-9b8f-976b61542ec5.png)

For few days I am having a trouble with the terminal. I am using ubuntu 20.04 LTS and the terminal I use is bash.

So, whenever i run file like python or cpp (using code runner extension) i get 2 commands printed in my terminal one above the prompt and one as usual below my termial prompt.

It's really annoying sometimes so please if you all can help.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic

**Comment by sayand0122** [comment]
Sorry but I really didn't understand. 
Can you please explain again?

**Comment by Tyriar** [comment]
This happens because of how the code runner extension is implemented.

**Comment by sayand0122** [comment]
So what's the solution for this or like do you have any reference on how to solve this issue?

**Comment by Tyriar** [comment]
You can ask the extension author https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner, vscode is doing what code runner is telling it to do.

**Comment by sayand0122** [comment]
i asked him and its been like more than a week but there's no reply from their end?

**Comment by Tyriar** [comment]
I can't do anything about it unfortunately.
