### ISSUE TITLE
Not able to run code

### ISSUE THREAD

**Issue by jainyash4292** [microsoft/vscode#113691]
Issue Type: <b>Performance Issue</b>

While typing code in visual studio the text does not occur in color it appear in white only.
For eg. If I type "#include<iostream>" as header file it should appear in blue and purple color respectively but it occurs in white only .

Please suggest me solution regarding my problem so I can solve my issue

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.79GB (0.93GB free)|
|Process Argv|--crash-reporter-id be7cd6e3-7c6a-4230-ba3a-c5f103ee3354|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    71	 12000	code main
    0	    22	   780	   crashpad-handler
    0	    36	  3052	   utility
    1	   164	  5504	   gpu-process
    0	    83	  5616	   shared-process
    2	    76	  8552	   window (Issue Reporter)
    0	   141	  9432	   window (● #include <iostream> • Untitled-1 - Visual Studio Code)
    0	    87	  5788	     extensionHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.1
cpptools|ms-|1.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30

**Comment by georgetian3** [comment]
Have you saved your file as a `.c` or `.cpp` file?
