### ISSUE TITLE
Extensions missing dependencies die silently when installed offline

### ISSUE THREAD

**Issue by mrburrito** [microsoft/vscode#113614]
- VSCode Version: 1.52.1
- OS Version: CentOS 7.6

I'm using VSCode on an internal company network that is fully air-gapped. We are able to transfer files from the internet to the network, but are unable to reach out so I've been installing extensions manually by downloading them. I needed to work on a Python project today so I grabbed the [MS Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension and installed it, along with the [Python Test Explorer](https://marketplace.visualstudio.com/items?itemName=LittleFoxTeam.vscode-python-test-adapter) extension. I started VSCode, opened my project, and thought everything was working because syntax highlighting was there. Then I tried to Ctrl-Click a function name to Go to Definition and it didn't work. Nor did code completion. I opened the dev console and finally saw an error from the Test Explorer extension that said it couldn't activate because it depended on the `ms-python.python` extension which was unable to activate. I looked through logs for hours today, trying multiple different configurations, including only the Python extension enabled, and bumping log level up to `trace`. The Python extension was completely silent. No errors. No mention of attempting to start. Nothing.

Finally, when I got home, I decided to try to replicate the issue. I downloaded the Python extension, disabled my networking, and started VSCode. Same problem. Nothing. Syntax highlighting worked, but autocompletion and code navigation didn't work. No output at all in the logs. So I turned networking back on and restarted VSCode. At that point, I got this error dialog telling me the Jupyter extension was a dependency and missing.

<img width="473" alt="Screen Shot 2020-12-30 at 10 05 01 PM" src="https://user-images.githubusercontent.com/1143629/103392613-ca32db80-4aec-11eb-9fe6-5e687f34a0c8.png">

That dialog should be displayed regardless of whether or not VSCode can reach the marketplace! The dependencies are specified in the `package.json` of the extension! At a minimum, there needs to be some notification that an enabled extension could not activate and log messages indicating why -- particularly in the event of missing dependencies, since that is a pretty trivial problem to fix in most cases.

Once I downloaded and installed the Jupyter extension, disabled networking, and started VSCode, I could clearly see both extensions activating in the status bar and the Python extension behaved as expected.

Steps to Reproduce:

1. `rm -rf ~/.vscode/extensions` 
2. Download [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension (`ms-python.python-2020.12.424452561.vsix`)
3. `code --install-extension /path/to/ms-python.python-2020.12.424452561.vsix`
4. Disable all networking
5. `code`
6. Open Python file/project
7. Attempt to use intellisense, "Go To" navigation, or other extension features; none work -- extension is not activated
8. Verify extension non-activation by executing `Python: Select Interpreter` command; you will see error saying it is not configured

Does this issue occur when all extensions are disabled?: No  -- the target extension must be enabled for the error to occur

*Expected Behavior:*

- Extensions generate logs indicating that they are attempting to activate and, particularly in the case of a failure, output logs that help troubleshoot activation failures.
- Missing dependency error is displayed in the UI even when unable to connect to the marketplace

**Comment by alexdima** [comment]
I see the screenshot and believe that something must have been very wrong. However, I don't understand what exactly is going on in this case. The Python extension does not have a dependency to the Jupyter extension (at least according to the `package.json` from https://github.com/microsoft/vscode-python/blob/main/package.json). I have looked at the history of that file and could not find a point where `extensionDependencies` would be removed. 

I agree that something is fishy, but I would start with the team owning the Python extension to clarify if they edit their `package.json` at runtime or if they used to have an `extensionDependency` which they then removed.

**Comment by alexdima** [comment]
Let's ask the Python team to investigate first, as I am aware that they do quite a lot of special things w.r.t. downloading pieces on-demand. https://github.com/microsoft/vscode-python/issues/15705

**Comment by alexdima** [comment]
The problem is that the Python extension depends on the Jupyter extension. But the activation error handling tries to query the marketplace to render the "Install and Reload" button. But that query throws at https://github.com/microsoft/vscode/blame/9b5eceb1f6692b9fc0b3b187b3a5da1318454146/src/vs/workbench/api/browser/mainThreadExtensionService.ts#L109

cc @sandy081

**Comment by alexdima** [comment]
This is the message that will be presented when the gallery cannot be reached:

![image](https://user-images.githubusercontent.com/5047891/111751606-fd3b6e80-8894-11eb-9ecd-0d86d50e6886.png)

**Comment by mrburrito** [comment]
Thanks for tackling this one! That dialog should be perfect. It will save me a ton of hassle and time off I run across this in the future!
