### ISSUE TITLE
[Live Share] vscode.window.onDidWriteTerminalData: events are only raised for first terminal window on MacOS Big Sur

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#113641]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

Live Share's Shared Terminal is no longer working on MacOS Big Sur (using VS Code stable 1.52.1)
MicrosoftDocs/live-share#4035

The issue occurs when sharing an existing terminal window, one that the host creates by clicking on New Terminal (+) from the VS Code's Terminal pane.

I've debugged and can see onDidWriteTerminalData isn't raised when input is typed in the newly created terminal. It appears to only pick up the events in the first terminal. Every time a new host terminal is created Live Share listens for input from this terminal and forwards it to the guest:

vscode.window.onDidWriteTerminalData((e) => {
if (e.terminal === terminal) {
const s = e.data;
writeDataQueue = writeDataQueue.then(
async () => {
await socket.write(s);
});
}
},
null /* this */,
registrations);

Note: everything is working as expected on Windows so this appears to only be an issue on MacOS (Big Sur)

FYI: @lostintangent

**Comment by cbrunnkvist** [comment]
The previously broken feature started working for me again after updating VS Code to `Version: 1.53.0`.

**Comment by jramsay** [comment]
I just tested as well and as @cbrunnkvist mentions (thanks!) it is working in 1.53.0 on MacOS Big Sur. Closing this issue

**Comment by lostintangent** [comment]
Nice!!
