### ISSUE TITLE
VSCode Insdier for ARM64 on M1 Macmini SOURCE CONTROL is slowly

### ISSUE THREAD

**Issue by stilleshan** [microsoft/vscode#113660]
- VSCode Version:1.53.0-insider
- OS Version:Darwin arm64 20.2.0

Steps to Reproduce:

1.Open Github folder
2.SOURCE CONTROL is very slow to refresh

When i use VSCode stable on M1 Macmini the SOURCE CONTROL is very fast
But it is very slow when i use VSCode Insider for ARM64

**Comment by eamodio** [comment]
@deepak1556 any idea on this one?

**Comment by deepak1556** [comment]
Can you provide the performance profile from both stable and insider following, thanks!

* Execute "F1 > Toggle Developer Tools."
* Select 'Performance' tab
* Start the profiler and perform the actions for slowdown
* Save the profile to a file and attach here.

**Comment by stilleshan** [comment]
@deepak1556 
Thanks for your reply.
[profile.zip](https://github.com/microsoft/vscode/files/5767504/profile.zip)

**Comment by seloner** [comment]
I have the same issue,any fix?

**Comment by deepak1556** [comment]
This is pending fix from upstream https://github.com/electron/electron/pull/27026

**Comment by stilleshan** [comment]
When i update macOS 11.2 today ,  The extension "Bracket Pair Colorizer 2" makes vscode - insiders an error "Extension host terminated unexpectedly" .

When i uninstalled it , I found "SOURCE CONTROL" has back to normal

<img width="454" alt="截屏2021-02-02 14 26 19" src="https://user-images.githubusercontent.com/22582966/106561584-eef2f680-6563-11eb-90a0-3e886dca4b18.png">

**Comment by seloner** [comment]
I confirm with mac os 11.2 the performance is a lot better.

**Comment by deepak1556** [comment]
@stilleshan the extension host crash is tracked at https://github.com/microsoft/vscode/issues/115646

**Comment by deepak1556** [comment]
@stilleshan can you check if the original issue of perf regression with source control is seen with latest insiders ? Thanks!

**Comment by stilleshan** [comment]
@deepak1556 

The performance has returned to normal now.

- macOS 11.2 (M1 Mac mini)
- VSCode insader ARM
Version: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:17:08.594Z (21 hrs ago)
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

**Comment by deepak1556** [comment]
Thanks for confirming!
