### ISSUE TITLE
Change the directory for the workspace. 

### ISSUE THREAD

**Issue by mouradbka** [microsoft/vscode#113686]
When I had to define the directory for my workspace, I misclicked and select the wrong directory. This directory is to big and therefore, I also have an error message when I launch ADS. "Visual Studio Code is unable to watch for file changes in this large workspace"

I found a solution for this error message here: 
https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc 
But it's only to change the max value, not to change the choice of directory. 

Thank you in advance,

**Comment by bpasero** [comment]
You can explicitly ignore folders to watch via the `files.watcherExclude` setting.
