### ISSUE TITLE
C++ debugging character arrays and strings: <error reading variable> and "Converting character sets: Invalid argument."

### ISSUE THREAD

**Issue by georgetian3** [microsoft/vscode#113677]
When debugging a C++ file containing character arrays or strings, the contents of the array/string are not shown, but instead shows "\<error reading variable\>" for character arrays and "Converting character sets: Invalid argument." for strings. Integer arrays are not affected:

![bad](https://user-images.githubusercontent.com/14836161/103451899-4f003e00-4d15-11eb-85ca-9e490d1d96fd.png)

However, what puzzles me is that on a different machine but with the exact same VSCode version (1.52.1), C/C++ extension version (v1.1.3) and C++ compiler (mingw-w64 x86_64-8.1.0-posix-seh-rt_v6-rev0), and `launch.json` file, the contents of the array/string appears normally:

![good](https://user-images.githubusercontent.com/14836161/103451898-4dcf1100-4d15-11eb-8abb-aad9ac89f81d.png)

The contents of `launch.json` are given below:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++.exe build active file"
        }
    ]
}
```

This problem has been posted elsewhere but with no solutions, as seen [here](https://stackoverflow.com/questions/64849170/gdb-error-reading-variable-in-array-while-debugging-vs-code) and [here](https://stackoverflow.com/questions/64531685/vscode-error-reading-variable-when-viewing-array-elements-during-debugging)

- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Create character array in C++ file
2. Start Debugging

Does this issue occur when all extensions are disabled?: Yes/No

Disabling extensions disables the debugger, so I cannot tell if the issue still occurs.

**Comment by RMacfarlane** [comment]
Since this issue is caused by the C/C++ extension, please open this issue there. Thanks!
