### ISSUE TITLE
Extension 'Uninstall' feature hides error message if right-click menu is used

### ISSUE THREAD

**Issue by norbertHauriel** [microsoft/vscode#113643]
Issue Type: <b>Bug</b>

Right click - Uninstall (on Jupyter extension) does not send error message if there is error, silently does nothing.
If clicked on the Manage icon and then click Uninstall, the error message shows (Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this.).

I expect the error message to always appear, no matter which way the Uninstall is executed.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.15.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1895)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|3.77GB (0.28GB free)|
|Process Argv|--unity-launch --crash-reporter-id fc53034c-fc7c-4ffa-847e-7d5c1ab5c2f0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt875:30239451
vsjup459cf:30237188

```

</details>

**Comment by isidorn** [comment]
Adding verified based on code review, not sure how to get into steps
@norbertHauriel you could try it out in VS Code insiders and let us know how it goes

**Comment by sandy081** [comment]
@isidorn Here are steps to verify:

- Install Python extension (this also installs Jupyter extension because it is a dep)
- Go to installed extensions view
- Right click on Jupyter extension and Uninstall
- You shall get a error notification - Cannot uninstall 'Jupyter' extension. 'Python' extension depends on this

**Comment by isidorn** [comment]
Thanks! I was able to verify with these steps
