### ISSUE TITLE
Code doesn't keeps the 'problems' section up-to-date

### ISSUE THREAD

**Issue by rohanbari** [microsoft/vscode#113666]
- Version: 1.52.1
- Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- Date: 2020-12-16T16:32:10.090Z
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Linux x64 5.4.0-58-generic

Steps to Reproduce:

1. With Microsoft's C++ extension activated, create a `.cpp` file and write the code, include a faulty code too.
2. Now we configure and start the debugger, we come across something like this:
![Test errors](https://user-images.githubusercontent.com/54104015/103444327-73183c80-4c8d-11eb-8f7b-c881ad805dae.png)
3. Still okay... now revert those erroneous code. Oops! They're still existing:
![Errors still existing, outdated](https://user-images.githubusercontent.com/54104015/103444358-aa86e900-4c8d-11eb-9851-3ecc9a370f5f.png)

Does this issue occur when all extensions are disabled?: No
**But:** Without C++ language support via its extension, nothing matters in Code, it will just become a simple text editor without any Intellisense suggestions – which is one of the best part of Code itself.

**Comment by RMacfarlane** [comment]
Since this is caused by the C/C++ extension, please open this issue there. Thanks!
