### ISSUE TITLE
Extremely slow/laggy

### ISSUE THREAD

**Issue by wasinwill** [microsoft/vscode#113647]
Issue Type: <b>Bug</b>

Very slow/laggy when doing pretty much anything: scrolling (including with files under 500 lines), switching between tabs/files, search within a file, copy-pasting, rendering text when opening a file, etc... Reproduces with all extensions disabled, and when all other applications are closed. Does NOT reproduce with Insiders (with the exact same files, same basic extensions installed and enabled, same settings synced between VS Code and Insiders).

This is what I did when recording the attached video:
- Open VS Code
- Show all extensions are disabled
- In new file created by default, copy-paste some long text
- Scroll using the minimap

You can see how long it takes for the preview rectangle on the minimap to follow the cursor. Even when initially pasting the text, VS Code seems to struggle to reach the end of the file immediately.

https://user-images.githubusercontent.com/44789688/103433187-f7e65600-4bba-11eb-9271-ff0de081b445.mp4

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 x 3498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.37GB free)|
|Process Argv|--crash-reporter-id 161dbe8d-2699-4a5e-a94f-12179563064e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.0
auto-close-tag|for|0.5.9
todo-tree|Gru|0.0.193
color-manager|roy|0.6.1
highlight-matching-tag|vin|0.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
vsjup459cf:30237188

```

</details>

**Comment by alexdima** [comment]
This sounds very similar to https://github.com/microsoft/vscode/issues/107016 . Could you please try closing all VS Code windows and starting with `code --disable-renderer-accessibility` ?

**Comment by wasinwill** [comment]
Alright. I'll try that and report back.

**Comment by wasinwill** [comment]
It seems to have fixed the issue. Thanks!

**Comment by schroef** [comment]
> This sounds very similar to #107016 . Could you please try closing all VS Code windows and starting with `code --disable-renderer-accessibility` ?

Does this option do the same as this menu in the settings? Sound like its the same option. However when i try using Terminal, i get a warning this option is not there. Then checking the settings, its still set to auto. So probably this option is doing something else.

![Screen Shot 2021-01-25 at 16 32 56](https://user-images.githubusercontent.com/6923008/105762990-8e443800-5f2b-11eb-8016-25d36c4323af.png)
