### ISSUE TITLE
Independent font size configuration options for the Editor tabs font

### ISSUE THREAD

**Issue by irisida** [microsoft/vscode#113606]
I think this has been touched on or encapsulated in others but not explicitly that I can see still open. I'd like to be able to configure/control the font size of an editor tab header to use a smaller/larger font size. 

granted the immediate ideas for naming are a bit weird. 
"editor.tabFontSize" - meh
"editor.windowTabFontSize" - maybe
"editor.???"

Anyway, worth the punt to see if it's possible or roadmapped anywhere. 
Best wishes.
Keep up the awesome work!

**Comment by yume-chan** [comment]
Basically duplicate of #509

You can try the [iocave.customize-ui](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui#customizeui.fontsizemap) extension.
