### ISSUE TITLE
Regex infinite loops aren't caught

### ISSUE THREAD

**Issue by flying-sausages** [microsoft/vscode#113608]
- VSCode Version: 1.53.0-insider
- OS Version: MacOS 11.1 (M1)

Steps to Reproduce:

1. Go to Search
2. Switch to regex
3. End up with a ...`(.*)*`... in the search field
4. death

Does this issue occur when all extensions are disabled?: Yes

**Comment by flying-sausages** [comment]
Looks like there are some pretty specific scenarios when this gets triggered based on the sequence of searches, I'll reproduce this on video

**Comment by flying-sausages** [comment]
Got it https://streamable.com/54i96p

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/30874
