### ISSUE TITLE
When I write CSS, window is not responding

### ISSUE THREAD

**Issue by BGOnline-CN** [Microsoft/vscode#11362]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by dbaeumer** [comment]
@BGOnline-CN can you please provide more information on how to reproduce this. Can we clone a github repository that demonstrates the behavior.

**Comment by dbaeumer** [comment]
@BGOnline-CN can you reproduce this if you disable all extensions (e.g. start code with --disable-extensions)

**Comment by aeschli** [comment]
Closing due to lack of information.
