### ISSUE TITLE
Please don't make the Terminal kill shortcut key disabled most of the time

### ISSUE THREAD

**Issue by justrajeshkp** [microsoft/vscode#113651]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a terminal with a nodejs -  'webpack serve' command
2. Try to terminate the command with CTRL+C
3. Nothing happens

Please make this functionality back as it was working well even in 1.2x versions

Thanks in advance

Regards,
Rajesh

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
I can't repro. Maybe you have a selection which will cause it to copy on Windows? Try adding this to your keybindings.json file:

```json
{
	"key": "ctrl+c",               
	"command": "-workbench.action.terminal.copySelection",
	"when": "terminalFocus && terminalProcessSupported && terminalTextSelected"
}
```

If that doesn't help you can try logging escape sequences to see if ctrl+c is getting sent correctly to your shell: https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging
