### ISSUE TITLE
Swapping places of elements between each other that are divided by an operator

### ISSUE THREAD

**Issue by eBitzu** [Microsoft/vscode#11368]
- VSCode Version: 1.4.0
- OS Version: Win7
- Language: Javascript

The most annoying thing ever in and IDE is the time you have to swap conditions, or parameters or members of an equation for example:

`var randomName = paramValue || $rootScope.paramValue;`
In this case maybe I want to switch them too... and for that I have to copy paste stuff to have something like this

`var randomName = $rootScope.paramValue || paramValue;`
This takes to much time, but if we could select the entire expression and right click a menu to say swap parameters... that would be super cool and the first IDE, as far as I know to do that.

Operators known to be useful: '||' , ','  all math operators.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#10663
