### ISSUE TITLE
"gotoSymbol" failed in golang

### ISSUE THREAD

**Issue by cjqpker** [Microsoft/vscode#11363]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. shift+cmd+o, input some keywords
2.vscode locates a strange position

![img_20160901_111603](https://cloud.githubusercontent.com/assets/14192091/18154361/7c8c89f2-7036-11e6-8bd7-7e14a2afd379.jpg)

**Comment by dbaeumer** [comment]
Moving to the vscode-go repository.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/vscode-go#465
