### ISSUE TITLE
Using Plotly in the jupyter extension of VScode insider 1.53.0 results in No renderer could be found for MIME type: application/vnd.plotly.v1+json

### ISSUE THREAD

**Issue by hugocool** [microsoft/vscode#113628]
- VSCode Version: 1.53.0 - insiders
- OS Version: mac os catalina 10.15.6 (19G73)

When using plotly with vscode renderer (to which the renderer is set by default) I get an error: 

Steps to Reproduce:
0. open jupyter extension
1. !pip install plotly
2. import plotly.express as px
3. px.line()
error: No renderer could be found for MIME type: application/vnd.plotly.v1+json

This also happens with older versions of plotly (I tested 4.14, 4.11, 4.10)
Using other [plotly renderers](https://plotly.com/python/renderers/#builtin-renderers) either results in the same error or no working output (except for the browser renderer which opens a new browser screen and shows the plot there).

Does this issue occur when all extensions are disabled?: does not apply, you need the Jupyter extension

**Comment by hugocool** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Plotly notification doesn't appear in notebook (#98773)](https://www.github.com/microsoft/vscode/issues/98773)

This is a much less problematic issue which occurs in a different version of vscode.

**Comment by dshalvardjiev** [comment]
I have the same issue with 

VSCode Version: 1.53.0-insider
plotly                      4.10.0

**Comment by RMacfarlane** [comment]
Since this is caused by the Python extension, please open this issue there. Thanks!

**Comment by dshalvardjiev** [comment]
Hi, 

@RMacfarlane - rather the Jupyter extension team. I found multiple (duplicate) issues filed there already:

https://github.com/microsoft/vscode-jupyter/issues/3936
https://github.com/microsoft/vscode-jupyter/issues/4227

Maybe close this one?
