### ISSUE TITLE
Stylesheet color preview display issue

### ISSUE THREAD

**Issue by itsakt** [Microsoft/vscode#11365]
- VSCode Version: 1.5.0-insider
- OS Version: Win 10 build 1607

Color preview used to be in line with code but now it shows up like this

![image](https://cloud.githubusercontent.com/assets/8027805/18157754/f00a9814-703c-11e6-88ed-19664a4c2eae.png)

**Comment by dbaeumer** [comment]
@aeschli starting with you and setting to August since it looks like a regression.

**Comment by aeschli** [comment]
duplicate of #11296
