### ISSUE TITLE
VSCode Insider ARM Mac does not open

### ISSUE THREAD

**Issue by hongfeiyang** [microsoft/vscode#113658]
- VSCode Version: Latest insider ARM Mac version as of today 
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. Download the latest insider version for ARM Mac 
2. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

The icon bounces twice on my M1 MacBook then it quits without any error info. I am unable to use this Insider version on my ARM Mac at all.

**Comment by deepak1556** [comment]
Did you have the x64 insiders installed before on this device ?

What is the output of `code-insiders --verbose` ?

**Comment by hongfeiyang** [comment]
> Did you have the x64 insiders installed before on this device ?
> 
> 
> 
> What is the output of `code-insiders --verbose` ?

Yes I think I did have a intel version of the insider VSCode installed previous but I have uninstalled it beforehand to install a arm version of VSCode insider

And since I cannot open VSCode insider to install the VSCode command to my PATH, this command cannot be run (not found)

**Comment by hongfeiyang** [comment]
And btw I just saw the someone mentioned this issue and after removing the .VSCode-insiders/ folder in my home directory and reinstall VSCode insider I can now open the application now 😄

**Comment by deepak1556** [comment]
Thanks for checking, I will merge this to https://github.com/microsoft/vscode/issues/113680
