### ISSUE TITLE
File content change round symbol not coming on the editor tab

### ISSUE THREAD

**Issue by prodv** [microsoft/vscode#113632]
Issue Type: <b>Bug</b>

1.  Open a file.

2. Change the content.

3. Round circle should appear on the editor's tab showing that the file content has been changed and not saved.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.15.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4014)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (1.50GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id d67c7c96-46c3-49f6-b2d5-9524ba6bc782|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.0
vscode-intelephense-client|bme|1.5.4
githistory|don|0.6.14
prettier-vscode|esb|5.8.0
color-highlight|nau|2.3.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt875:30239451
vsjup459:30237187

```

</details>

**Comment by bpasero** [comment]
Did you maybe enable auto save (File > Auto Save)?

**Comment by prodv** [comment]
Yes that's the case.

Thank you!!
