### ISSUE TITLE
The cursor can't keep up when typing too fast

### ISSUE THREAD

**Issue by stelulocom** [microsoft/vscode#113615]
Optimize performance

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

If it's reproduced without extensions - check https://github.com/microsoft/vscode/wiki/Performance-Issues for instructions on how to provide info required for performance related issues.
