### ISSUE TITLE
Settings sync turns off if you try to experiment with different themes too quickly.

### ISSUE THREAD

**Issue by jaintj95** [microsoft/vscode#113694]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. I was trying out different themes by scrolling through the theme list
2. After a while Settings Sync turned off with a "Too many requests" error

` [userDataSync] [error] LocalTooManyRequests (UserDataSyncError) syncResource:unknown operationId:unknown: Too many requests. Only 100 requests allowed in 5 minutes.`

Maybe it would be good to have a small timeout after which settings are synced? Why sync immediately on a theme change?

After a while I was able to turn it back on, but it shouldn't sync so quickly when changing themes to avoid timeouts.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/91286
