### ISSUE TITLE
The window is no longer responding when right-click to see the context menu without action on Windows.

### ISSUE THREAD

**Issue by Cloudwu1** [Microsoft/vscode#11367]
- VSCode Version: 1.4.0
- OS Version: Win7, Win10

Steps to Reproduce:

1. Right-click in a cpp file or in the side bar to see the context menu.
2. Wait for a minutes.

It reproes with/without cpptools 0.9.0.
![norespond](https://cloud.githubusercontent.com/assets/21057022/18160089/44b670d8-705e-11e6-8c3d-122c367f321f.PNG)

**Comment by dbaeumer** [comment]
@Cloudwu1 us your code public available so that we can clone it to test this. Without a test case it is very hard to track down.

**Comment by Cloudwu1** [comment]
@dbaeumer You can use any project cpp file to repro it.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6414
