### ISSUE TITLE
TypeError: Cannot read property 'aliases' of undefined

### ISSUE THREAD

**Issue by MuriloRios** [microsoft/vscode#113668]
C:\Users\SILVA\Desktop\Cardosinho ;-;\bot.js:56
            if (pull.config.aliases.includes(command)) pull.run(cake, message, args)
                            ^

TypeError: Cannot read property 'aliases' of undefined
    at C:\Users\SILVA\Desktop\Cardosinho ;-;\bot.js:56:29
    at Array.forEach (<anonymous>)
    at C:\Users\SILVA\Desktop\Cardosinho ;-;\bot.js:53:16
    at FSReqCallback.oncomplete (fs.js:171:23)

**Comment by jrieken** [comment]
seems unrelated to vscode
