### ISSUE TITLE
When ever i create and start debugger , i get a error stating that the exe file does not exist. It is quite strange as it is the duty of the debugger to create .exe file

### ISSUE THREAD

**Issue by Amanraj13** [microsoft/vscode#113611]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.Create new file (C++)
2.Now set up debugger then write some code and start the debugger.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by weinand** [comment]
No, it's the debugger's duty to debug, not to build the executable.
Please create a build task that creates the executable.
