### ISSUE TITLE
Commanding UX

### ISSUE THREAD

**Issue by stevencl** [Microsoft/vscode#1136]
We need to explore ways we can provide access to commands that are global in scope. For example, the start debug icon is only visible in the debug viewlet but should be available regardless of context.

This should also handle the current UX for the likes of git checkout where we have a label in the status bar that shortcuts to the git checkout command in the command palette.

**Comment by stevencl** [comment]
We also need to consider ways in which we communicate whether or not a command is valid. Consider extension actions showing up in the command palette for example.

Also, can we get clear guidance on when to show commands, how overflow should work, how many commands we show on a viewlet, appropriate use of context menus, how to arrange and order main menu commands etc.

Some of this just needs an overhaul (i.e., the View menu is getting pretty big), others need some design guidelines.

Also see #10308

**Comment by bpasero** [comment]
@stevencl should we close this, it seems very generic and should maybe have more specific actionable issues?
