### ISSUE TITLE
Decorators are not execute

### ISSUE THREAD

**Issue by aabdou5** [microsoft/vscode#113601]
Issue Type: <b>Bug</b>

I can't call a python decorator with "@"

VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.60GB free)|
|Process Argv|--crash-reporter-id 53469439-9a52-4000-9e35-4c902962a5df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
java|red|0.73.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.24.2

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please specify how it's related to editor itself?
What do you mean call? If call in runtime - VS Code does not execute Python code itself

**Comment by aabdou5** [comment]
I mean "execute", when I tried to execute my code on PyCharm, it worked well but not on VS

**Comment by RMacfarlane** [comment]
Since this is caused by the Python extension, please open this issue there. Thanks!
