### ISSUE TITLE
vscode remove/create file will auto compact folder

### ISSUE THREAD

**Issue by shengbeiniao** [microsoft/vscode#113622]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

**settings, disable explorer compact not work

when move/remove/create file will auto compact folder**

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64
Fetching remote diagnostics for 'ssh-remote+zstack.test' timed out.
Remote OS version: Linux x64 3.10.0-1127.8.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.93GB free)|
|Process Argv|--crash-reporter-id 8a5e4338-f281-4da9-86a9-f80e93846c47|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zstack.test|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2094)|
|Memory (System)|31.24GB (10.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zstack.test|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2094)|
|Memory (System)|31.24GB (10.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zstack.test|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2094)|
|Memory (System)|31.24GB (10.35GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: zstack.test|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2094)|
|Memory (System)|31.24GB (10.35GB free)|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+zstack.test' timed out.

|Item|Value|
|---|---|
|Remote|SSH: zstack.test|
|OS|Linux x64 3.10.0-1127.8.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (8 x 2094)|
|Memory (System)|31.24GB (10.35GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.18.0
emojisense|bie|0.8.0
mermaid-markdown-syntax-highlighting|bpr|1.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.38.0
mustache|daw|1.1.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
smarty|imp|0.3.0
jenkinsfile-support|ivo|1.1.0
jenkins-pipeline-linter-connector|jan|1.2.0
search-node-modules|jas|1.3.0
yarn-lock-syntax|mar|0.1.3
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.9.0
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
debugger-for-chrome|msj|4.12.11
vscode-jest|Ort|3.2.0
run-as|ply|1.8.27
jenkinsfile-support|sec|0.1.0
shader|sle|1.1.4
vscodeintellicode|Vis|1.2.10
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630

```

</details>

**Comment by isidorn** [comment]
Those are not steps. Please file a nice issue with reproducable steps. Also can you reproduce with vscode insiders 
https://code.visualstudio.com/insiders/

**Comment by shengbeiniao** [comment]
> Those are not steps. Please file a nice issue with reproducable steps. Also can you reproduce with vscode insiders
> https://code.visualstudio.com/insiders/

I found this problem will occur in multi workspace view. when one folder setting root
