### ISSUE TITLE
Mouse pointer does not move to submenu and submenu disappears.

### ISSUE THREAD

**Issue by mrburrito** [microsoft/vscode#113630]
When I try to use any submenus, either from the top menubar (e.g. File -> Open Recents) or right-click context (e.g. Right Click -> Open Changes), as soon as I move the mouse to the submenu, the pointer jumps to the top of the parent menu and, if I move too far to the right, the submenu just disappears. Hovering over the main menu trigger allows me to use keyboard arrows to operate the submenu, but I can't use the mouse at all. I've tested on version 1.51 and 1.52 with the same problem.

- VSCode Version: 1.52, 1.51
- OS Version: CentOS 7.6

Steps to Reproduce:

1. Open File Menu
2. Highlight "Open Recent"
3. Move mouse to highlight recent project

Does this issue occur when all extensions are disabled?: Yes

**Comment by mrburrito** [comment]
Correction: OS is CentOS 7.7

**Comment by mrburrito** [comment]
This does not appear to be a duplicate of any of the above.

**Comment by mrburrito** [comment]
Additionally, I connect to the Linux workstation using an RDP client, if that makes any difference in reproducing.

**Comment by sbatten** [comment]
@mrburrito can you confirm your setting for `window.titleBarStyle`?

**Comment by mrburrito** [comment]
@sbatten I just tested on a separate remote desktop using AWS Workspaces and I see the same issue. In this case, it's on Amazon Linux 2, but based on that it seems this is an error with VSCode getting the mouse location from a remote desktop session.

On the AWS Workspace, `window.titleBarStyle` is `native`. I believe it is the same on my other workstation. Assuming `native` is the default, I didn't do anything to change it.

**Comment by sbatten** [comment]
thanks @mrburrito for confirming. this indicates that there may be an issue upstream with how these menus are handled.

**Comment by mrburrito** [comment]
I tried switching that to `custom` on the AWS Workspace and the submenus worked properly! Not sure if that changes anything beyond LAF (obviously is does something!) but hopefully that helps isolate the problem.

**Comment by mrburrito** [comment]
I don't have access to my original workstation today, but I'm trying to get verification on the current setting and see if changing to `custom` fixes the menu behavior on the CentOS box as well.

**Comment by sbatten** [comment]
I expect it will resolve the issue for both since in the `custom` case, we handle all of the menu rendering. hope its a good workaround for now.

**Comment by mrburrito** [comment]
A lot better than not having submenus at all! I'll update once I have confirmation.

**Comment by mrburrito** [comment]
@sbatten confirmed that `custom` works on the CentOS workstations as well. It seems to be a problem with `native` menus and a remote desktop.

**Comment by PranavBakre** [comment]
I had a similar issue on Fedora with KDE desktop. Worked after changing to custom

**Comment by Blanko2** [comment]
to jump in on this - had same issue with AwesomeWM -- Atom also has this same behaviour, maybe it's an Electron issue?

**Comment by danielhorng** [comment]
I also encountered the same problem, I'm using XRDP from windows 10 to connect to Ubuntu 20.04. My current temporary solution is hold [Shift] or [Alt] before moving to the sub-menu.

**Comment by ChrisZIT** [comment]
Hi, I updated to the current stable version of vscode and I can select submenu now with Ubunut 20.04.
In the elecron issue an other user reported it is fixed also in cromium: https://github.com/neutrinolabs/xrdp/issues/1763#issuecomment-932860135

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/113630#issuecomment-1098883291
