### ISSUE TITLE
打开扩展详情时出问题

### ISSUE THREAD

**Issue by ZAY-LSY** [microsoft/vscode#113623]
Issue Type: <b>Bug</b>

在打开扩展详情时，vscode可能会显示出多个功能贡献...
![image](https://user-images.githubusercontent.com/75121874/103405010-93ae9c80-4b90-11eb-8862-083fe6545321.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:50.160Z)
OS version: Windows_NT ia32 6.1.7601

**Comment by liubq7** [comment]
Translation:

It may display multiple **Future Contributions** in extension details page.
