### ISSUE TITLE
Switch between Terminals by keyboard shortcut

### ISSUE THREAD

**Issue by behnammodi** [microsoft/vscode#113681]
I always use 3 terminals and switch between them most of the time, how can I switch by keyboard shortcut?

In macOS terminal we can do it by `[shift]+[command]+[left arrow]/[right arrow]`

![Screen Shot 2021-01-02 at 11 49 45 AM](https://user-images.githubusercontent.com/1549069/103453606-e69f6580-4cf0-11eb-8ef5-9adcda1d71a0.png)

**Comment by Tyriar** [comment]
Try adding this to your keybindings.json file:

```json
{ "key": "cmd+shift+right",     "command": "workbench.action.terminal.focusNext" },
{ "key": "cmd+shift+left",     "command": "workbench.action.terminal.focusPrevious" }
```

**Comment by behnammodi** [comment]
@Tyriar thanks 🙏
