### ISSUE TITLE
emmet not working

### ISSUE THREAD

**Issue by nteetzel** [microsoft/vscode#113638]
Emmet isn't working in Visual Studio Code.

**Comment by rzhao271** [comment]
Can you give some steps so that I can reproduce the issue?
Also, what version of VS Code are you on?

**Comment by nteetzel** [comment]
Hello I'm using version 1.52. - Emmet was working fine until I installed Github... or so it seems that's when it stopped working. 

I was hoping I could just reinstall VSC to bring me back to default - but it just reinstalls from where I left off at?

I've spent the last two days trying to find a fix but nothing seems to work?

Thank you!

Nick

**Comment by nteetzel** [comment]
Well it's fixed - and I have no idea how I did it?

Thank you so much!

Nick
