### ISSUE TITLE
Stop scrolling editor background when hovering tip window

### ISSUE THREAD

**Issue by MariuzM** [microsoft/vscode#113631]
When i hover on a variable to get this information / tips i have to be really careful on how i scroll for example when checking for errors on that tip window they are at the bottom so when i scroll to it and if i reach the end of it it will start scrolling the editor window. 

I don't think this issue was in the earlier versions.

Made a quick video demonstrating this. 
https://imgur.com/a/lprnQTe

**Comment by ArturoDent** [comment]
Dups of  https://github.com/microsoft/vscode/issues/113586 and https://github.com/microsoft/vscode/issues/112373
