### ISSUE TITLE
Keep getting "the typescript language service died" errors

### ISSUE THREAD

**Issue by nitarsh** [microsoft/vscode#113649]
Issue Type: <b>Bug</b>

Just opening my Javascript/Node.Js project causes this. I don't use any typescript code in this project.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|-psn_0_6256119 --crash-reporter-id d50c3fdd-0c2c-4673-9ebf-8867b17ebd12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.13
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.8.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.3
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vsliveshare|ms-|1.0.3375
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
tsimporter|pmn|2.0.1
vscodeintellicode|Vis|1.2.10
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt859:30239450
vsjup459:30237187

```

</details>

**Comment by nitarsh** [comment]
Issue Type: <b>Bug</b>

Just opening my Javascript/Node.Js project causes this. I don't use any typescript code in this project.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|-psn_0_6256119 --crash-reporter-id d50c3fdd-0c2c-4673-9ebf-8867b17ebd12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
vscode-babel-coloring|dza|0.0.4
vscode-npm-script|eg2|0.3.13
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.8.0
beautify|Hoo|1.5.0
graphql-for-vscode|kum|1.15.3
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vsliveshare|ms-|1.0.3375
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
tsimporter|pmn|2.0.1
vscodeintellicode|Vis|1.2.10
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt859:30239450
vsjup459:30237187

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
