### ISSUE TITLE
Flaky test: EditorsObserver - copy group

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#113620]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98794&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6ad30dce-518e-54c1-94da-00d19cce9354&l=7719

Failed on Windows:

```
  6405 passing (3m)
  42 pending
  1 failing

  1) EditorsObserver
       copy group:

      AssertionError [ERR_ASSERTION]: 136 == 137
      + expected - actual

      -136
      +137
      
      at Context.<anonymous> (file:///D:/a/1/s/out-build/vs/workbench/services/editor/test/browser/editorsObserver.test.js:177:20)

```

**Comment by bpasero** [comment]
I have disabled the test for now.

**Comment by bpasero** [comment]
TBD: the test seems to be more flaky in web, this it was skipped before:

https://github.com/microsoft/vscode/commit/82b99b3286fb8c573e88669526431ade4bdad81d#diff-389cf3523b767a02d16fc12ac6447352d1aee0e13508bbb4a6fcc0b1e5dd0d7eL209
