### ISSUE TITLE
Editor Rendering Very Slowly

### ISSUE THREAD

**Issue by cubeleo** [microsoft/vscode#113683]
Issue Type: <b>Performance Issue</b>

Some time in the past year, VSCode has begun to render extremely slowly.  I get about 2-3 fps when scrolling.  I have a GTX 1080 and Windows 10.  I stay as up to date as possible with software updates for windows and my NVidia drivers.  This happens no matter the size of the code base or the language mode the editor is in, as far as I can tell.  I've been running VSCode for years, so I'm not sure if it's some stale setting I need to get rid of or what is going on.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.19GB free)|
|Process Argv|--crash-reporter-id f175fa33-84c8-46fb-b27e-6f67d5029833|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    92	 47248	code main
    0	    36	 41964	   utility
    0	   442	 51248	   window (ContactTests.cpp (Working Tree) - PerfectWorldSoftware - Visual Studio Code)
    0	    17	 66408	     watcherService 
    0	     6	 50968	       console-window-host (Windows internal process)
    0	    49	 86120	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   133	103208	     extensionHost
    0	    59	 33764	       c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3\bin\cpptools.exe
    0	     6	 77232	         console-window-host (Windows internal process)
    0	   362	 99736	         "c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 33764 20
    0	   106	123772	         "c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 33764 23
    0	   247	139904	         "c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 33764 19
    0	    98	145552	         "c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 33764 24
    0	   142	162508	         "c:\Users\adwyer\.vscode\extensions\ms-vscode.cpptools-1.1.3/bin/cpptools-srv.exe" 33764 22
    0	    61	144936	       "C:\Users\adwyer\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\adwyer\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=103208
    0	     6	115272	     console-window-host (Windows internal process)
    0	    94	166560	     searchService
    7	    85	135176	   shared-process
    0	    80	140272	   window (Issue Reporter)
    0	    22	151532	   crashpad-handler
    0	    92	186196	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ContactTests.cpp (Working Tree) - PerfectWorldSoftware - Visual Studio Code)
|    Folder (PerfectWorldSoftware): 16790 files
|      File types: png(2337) tlog(1384) obj(1145) json(1108) h(804) cpp(701)
|                  cmake(446) xml(404) lib(345) hgt(311)
|      Conf files: cmake(446) makefile(13) sln(12) launch.json(1)
|                  settings.json(1) tasks.json(1) csproj(1)
|      Launch Configs: cppvsdbg;
```

</details>
<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.1.0
compiler-explorer|Mat|0.5.0
start-git-bash|McC|1.2.1
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
vscode-hexdump|sle|1.8.1
msbuild-tools|ste|0.0.12
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by Babygogogo** [comment]
I've got the same problem. The editor works well when I open it, but it always slows down after some time (about half an hour or so), even if I haven't typed anything in the editor. When it slows down, everything you do in the editor becomes extremely laggy. Restarting the editor will help, but it will again slow down after some time.
This is very frustrating. Please fix it, thank you!

**Comment by alexdima** [comment]
This soundsvery similar to https://github.com/microsoft/vscode/issues/107016 . Can you please try closing all windows and running `code --disable-renderer-accessibility` ?

**Comment by cubeleo** [comment]
I ran with that switch, and now it runs fast again.  Nice to have a workaround, thanks.

**Comment by schroef** [comment]
Can i ask how i use the code "--disable-renderer-accesibility"? I tried starting the app with Terminal on OSX and add this as a flag. It returns its an unfamilliar code

`Mac-Pro:~ macpro1$ /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron --disable-renderer-accessibility
Warning: 'disable-renderer-accessibility' is not in the list of known options, but still passed to Electron/Chromium.
`
