### ISSUE TITLE
insider version cannot switch github account to sync settings

### ISSUE THREAD

**Issue by kingvagabond** [microsoft/vscode#113669]
- VSCode Version: 1.53.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. start settings sync with one github account login - choose insider by default
2. turn settings sync off and try to login another account - choose either stable or insiders 
3. cannot login to another github account

Does this issue occur when all extensions are disabled?: Yes/No
have to use settings sync extension for this feature

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/104595
