### ISSUE TITLE
Certain input is truncated in node repl in VSC's terminal

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode#113692]
My reproducible environment:

* Win10 20H2 x64 + VSCode 1.52.1 + Nodejs 15.5
* VM Win7 x86 + VSCode 1.51.1 + Nodejs 12.20

My **not** reproducible environment:

* External console
* WSL Debian

Steps to Reproduce:

1. Open terminal and run `node`
2. Input `JSON.parse('{"aaaaaaaaaaaaa":null,"bbbbbbbb.bbbbbb":null}')`
3. It shows
    ```
    JSON.parse('{"aaaaaaaaaaaaa":null,"bbbbbbbb.bbbbbb
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Uncaught SyntaxError: Invalid or unexpected token
    ```
    which seems `":null}')` is lost.

	![图片](https://user-images.githubusercontent.com/24759802/103458666-4d4e6e80-4d45-11eb-9e21-eb40dfd9dd39.png)

	![图片](https://user-images.githubusercontent.com/24759802/103458684-74a53b80-4d45-11eb-95f1-bbea8fd1b44d.png)
4. It seems that shorter key works, and the second key must contain a `.`

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This is likely an issue with the upstream component "conpty". Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps if it happens there.
