### ISSUE TITLE
VSCODE hangs when opening  c++ file with a long line in 1.52.1

### ISSUE THREAD

**Issue by MR-TLL** [microsoft/vscode#113685]
Issue Type: <b>Performance Issue</b>

This issue happens from version 1.52 onward, whenever i open a  c++ file with a long line (length of around 1800) the editor freezes for 1-2 minute with high cpu usage. This happens whenever i close and open that file or paste the attached code in a cpp file. Removal of that long line fixes the issue. Word wrap and disabling all extensions also dont fix the issue. 

I am attaching the source code below for reference and reproducibility:

#include "bits/stdc++.h"
#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>
#include <vector>
using namespace std;
using namespace __gnu_pbds;
using ll = long long;
template <typename T, typename R>
using os = tree<pair<T, R>, null_type, less<pair<T, R>>, rb_tree_tag,
                tree_order_statistics_node_update>;
#define el "\n"
#define n_l "\n"
#define dbg(...) cout << "[" << #__VA_ARGS__ << "]: "; cout << to_string(__VA_ARGS__) << endl
template <typename T, size_t N> int SIZE(const T (&t)[N]){ return N; } template<typename T> int SIZE(const T &t){ return t.size(); } string to_string(const string s, int x1=0, int x2=1e9){ return '"' + ((x1 < s.size()) ? s.substr(x1, x2-x1+1) : "") + '"'; } string to_string(const char* s) { return to_string((string) s); } string to_string(const bool b) { return (b ? "true" : "false"); } string to_string(const char c){ return string({c}); } template<size_t N> string to_string(const bitset<N> &b, int x1=0, int x2=1e9){ string t = ""; for(int __iii__ = min(x1,SIZE(b)),  __jjj__ = min(x2, SIZE(b)-1); __iii__ <= __jjj__; ++__iii__){ t += b[__iii__] + '0'; } return '"' + t + '"'; } template <typename A, typename... C> string to_string(const A (&v), int x1=0, int x2=1e9, C... coords); int l_v_l_v_l = 0, t_a_b_s = 0; template <typename A, typename B> string to_string(const pair<A, B> &p) { l_v_l_v_l++; string res = "(" + to_string(p.first) + ", " + to_string(p.second) + ")"; l_v_l_v_l--; return res; } template <typename A, typename... C> string to_string(const A (&v), int x1, int x2, C... coords) { int rnk = rank<A>::value; string tab(t_a_b_s, ' '); string res = ""; bool first = true; if(l_v_l_v_l == 0) res += n_l; res += tab + "["; x1 = min(x1, SIZE(v)), x2 = min(x2, SIZE(v)); auto l = begin(v); advance(l, x1); auto r = l; advance(r, (x2-x1) + (x2 < SIZE(v))); for (auto e = l; e != r; e = next(e)) { if (!first) { res += ", "; } first = false; l_v_l_v_l++; if(e != l){ if(rnk > 1) { res += n_l; t_a_b_s = l_v_l_v_l; }; } else{ t_a_b_s = 0; } res += to_string(*e, coords...); l_v_l_v_l--; } res += "]"; if(l_v_l_v_l == 0) res += n_l; return res; } void dbgm(){;} template<typename Heads, typename... Tails> void dbgm(Heads H, Tails... T){ cout << to_string(H) << " | "; dbgm(T...); }
#define dbgm(...) cout << "[" << #__VA_ARGS__ << "]: "; dbgm(__VA_ARGS__); cout << endl
clock_t time_p=clock();

template<typename T>
void print(T v){
  for(auto i:v){
    cout<<i<<" ";
  }
  cout<<el;
}

int main(){
int t; cin>>t;
while (t--){
    

}

}

VS Code version: VSCodium 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-17T00:37:39.556Z)
OS version: Linux x64 5.10.2-2-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.33GB (0.19GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   165	 25161	codium main
    0	    38	 25163	   zygote
    0	    75	 25192	     gpu-process
    0	    38	 25164	   zygote
    0	    90	 27783	     window (Process Explorer)
    1	    83	 62152	     window (Issue Reporter)
    0	    68	 25205	   utility
    0	   113	 25274	   shared-process
    0	     0	 62411	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   308	 26732	   window (cf.cpp - vsc_Projects - VSCodium)
    0	   210	 26754	     extensionHost
    0	   203	 26853	       /home/silent_solitude/.vscode-oss/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools
    0	   150	 26908	         /home/silent_solitude/.vscode-oss/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 26853 0
    0	   143	 55691	         /home/silent_solitude/.vscode-oss/extensions/ms-vscode.cpptools-1.1.3/bin/cpptools-srv 26853 2
    0	    60	 26892	       /usr/share/vscodium-bin/codium /usr/share/vscodium-bin/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=26754
    0	   120	 32834	       /usr/bin/pypy3 /home/silent_solitude/.vscode-oss/extensions/ms-python.python-2020.11.358366026/pythonFiles/pyvsc-run-isolated.py /home/silent_solitude/.vscode-oss/extensions/ms-python.python-2020.11.358366026/pythonFiles/completion.py
    0	    75	 26770	     watcherService
    0	    68	 27406	     searchService
    0	     0	 62387	   /bin/bash /usr/share/vscodium-bin/resources/app/out/vs/base/node/cpuUsage.sh 25161 25163 25164 25205 25274 26732 62386 25192 27783 62152 26754 26770 27406 26853 26892 32834 26908 55691
    0	     0	 62406	     sleep 1
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cf.cpp - vsc_Projects - VSCodium)
|    Folder (vsc_Projects): 825 files
|      File types: hpp(468) inl(268) h(20) py(12) cpp(9) txt(8) json(4) zip(2)
|                  csv(2) frag(2)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(2) python;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
python|ms-|2020.11.358366026
jupyter|ms-|2020.11.358541065
cpptools|ms-|1.1.3
deepdark-material|Nim|3.2.1
glassit|s-n|0.2.2

</details>

**Comment by deepak1556** [comment]
Thanks for the report with a test case, merging to https://github.com/microsoft/vscode/issues/117264
