### ISSUE TITLE
Ctrl + Click not Working

### ISSUE THREAD

**Issue by sahusaurav** [microsoft/vscode#113626]
Issue Type: <b>Bug</b>

Ctrl + Click for Go To Navigation is not working. Also, on selection of a variable/entity I cannot find the go to definition option as well.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.47GB free)|
|Process Argv|--crash-reporter-id 0c538646-0e1c-4d40-a811-53943707891c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
java|red|0.73.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-maven|vsc|0.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide more info about workspace configuration and what is language of the file where you are trying to use Go to...?

**Comment by bpasero** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.

Happy Coding!
