### ISSUE TITLE
gcc: error: helloworld.c: No such file or directory gcc: fatal error: no input files

### ISSUE THREAD

**Issue by narasimhan11102** [microsoft/vscode#113616]
When I try to compile the program in VS Code using ctrl+shift+B I get an error showing the following message 
![Capture](https://user-images.githubusercontent.com/76741184/103395178-dd789200-4b52-11eb-994c-87a0075c8857.PNG)

The bottom terminal window shows the error and the compilation terminates.
Can someone please help me resolve this issue?

**Comment by Tyriar** [comment]
Either an extension problem and/or your task is wrong.
