### ISSUE TITLE
Github password authentication deprecated

### ISSUE THREAD

**Issue by lcsqlpete** [microsoft/vscode#113787]
Issue Type: <b>Bug</b>

Push local to remote.

I receved an email from github when pushing a local branch to origin as follows:

You recently used a password to access the repository at KleenEdge/web-php with git using git/2.20.1 (Apple Git-117).

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

The link indicates that password authentication will be deprectaed as of 8/31/2021 and must ve replaced by a personal access token or SSH key.

WIll vscode be updated to handle this change prior to 8/31/2020?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (9.29GB free)|
|Process Argv|--crash-reporter-id 5af32177-13d8-4b6f-b795-cbf22dd13792|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
mustache|daw|1.1.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.2
vscode-html-css|ecm|1.6.2
php-intellisense|fel|2.3.14
vscode-phpfmt|kok|1.0.30
vscode-JS-CSS-HTML-formatter|lon|0.2.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt859:30239450
vsjup459:30237187

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by eamodio** [comment]
This is already supported today, as VS Code relies on your configured Git authentication.

**Comment by lcsqlpete** [comment]
Could you please tell me where to configure my git authentication and the
format for using a personal access token.
