### ISSUE TITLE
unbound breakpoint in 1.52.1 debuging in wsl

### ISSUE THREAD

**Issue by hcldan** [microsoft/vscode#113777]
- VSCode Version: 1.52.1
- OS Version: windows 10

I looked at #102493 but none of the steps seemed to help.
I emailed connor@xbox.com my trace.

**Comment by connor4312** [comment]
Thanks for the logs. It looks like VS Code doesn't get the debugger connection back from Node.js. Can you check on a few things?

1. Check what the `process.env.NODE_OPTIONS` are in your app
2. See if the app runs if you run it in the integrated console (remove `"console":"integratedTerminal"`)

**Comment by hcldan** [comment]
```
<dir>(master)$  /usr/bin/env NODE_ENV=development 'NODE_OPTIONS=--require <homedir>/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.18470-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/tmp/node-debug-callback-3d5f5fcbd56d026d"}' /usr/bin/node --expose-gc ./service/iam/index.js 
Debugger attached.
```

**Comment by connor4312** [comment]
Thanks for checking. Do you have any antivirus/firewall running in WSL which could be preventing the connection from happening?

**Comment by hcldan** [comment]
I don't think so... I'm just using windows defender

**Comment by hcldan** [comment]
when i turn off using the preview debugger i get this:
```
Debugger listening on ws://127.0.0.1:31936/90b36290-335b-4231-a489-69ba6d575779
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:31937/3f8c6b55-9eb2-4374-ae41-8d4ac3ba3638
For help, see: https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:31938/3cdfeb04-a866-4345-a7eb-26328b21fef8
For help, see: https://nodejs.org/en/docs/inspector
```

This is weird, because it was working about a month ago the last time I tried to debug this project.
There's no fancy stuff here, just a node server.

**Comment by hcldan** [comment]
also..  (not using preview) I was able to use chrome (windows) to connect to that node endpoint (wsl) 
it didn't seem like there was issues connecting

**Comment by hcldan** [comment]
Anything other info I can try to gather for you?

**Comment by liam-jones-lucout** [comment]
I'm also having this issue. Happy to help with any info

environment is WSL2
attempting to debug via ts-node

**Comment by connor4312** [comment]
@liam-jones-lucout the issue you're having is unlikely to be the same, please file a bug with information here: https://github.com/microsoft/vscode-js-debug/issues/new/choose

@hcldan you mentioned

> when i turn off using the preview debugger i get this

Does the old debugger work, or does it face the same issue? If the latter, I would guess it's 'some' networking weirdness. If it does, I can dig in more.

**Comment by hcldan** [comment]
@connor4312 No, it's not working there either.

I'm not really sure what the network issue would be....    the network between wsl2 and my windows machine should be fairly permissive...

**Comment by hcldan** [comment]
aaaaaand today the preview debugger is working for me ....   :-/     I guess you can close this but I have no idea why it's working now.

**Comment by connor4312** [comment]
Thanks for the followup. The new and old debuggers do not share any lineage, so if it failed there that would support the idea of 'something' happening that prevented connecting to the debug server. I don't know what it would be, but it seems external to the debugger itself.

**Comment by hcldan** [comment]
@connor4312 Can you please open this again?
I have a bit more info...   though I'm not sure what else to do.  The problem came back for no apparent reason the next day.

So I've been trying to get this to work in WSL...   I haven't noticed any firewall or networking issues, where do you suggest I look?

I moved my code over to windows and when I launch code and use the same exact settings (preview debugger is enabled) debugging works fine.  But I really would rather be working inside wsl.

**Comment by connor4312** [comment]
Reopened, but I'm not sure what we can do here 😕

**Comment by hcldan** [comment]
@connor4312 can you add some debugging or something to log connections failing or timing out?
As it is... I don't see any evidence of why it's not connecting at all.

**Comment by connor4312** [comment]
When you see `Debugger listening on ws://<address>`, I'm curious what happens if you try to:

1. Run `curl -v http://<address>`
2. Open `https://<address>` in your browser

Neither of these will result in a happy 200 status code, but am curious whether you get a timeout or different failure in those cases

**Comment by hcldan** [comment]
I stated earlier that I was able to connect chrome to the debugger in that scenario and it did indeed work.

I can try doing a curl against it if you think that would give more info.

 

----- Original message -----

**Comment by hcldan** [comment]
this is the craziest issue...   
I tried to get you a curl trace and browser results... but I don't get the listening console message on the console anymore with preview debugger.

So I disabled preview and tried to connect and now it's working with the non-preview debugger.
