### ISSUE TITLE
vscode does not run npm script names with whitespaces

### ISSUE THREAD

**Issue by jonamat** [microsoft/vscode#113750]
- VSCode Version: 1.52.1
- OS Version: Windows 10 10.0.19042 build 19042

Steps to Reproduce:

1. Create a new node project
2. Add a script in the package.json with whitespaces in the key name
3. Try to run it from the "scripts" panel

Does this issue occur when all extensions are disabled?: Yes

I have these scripts defined  in the package.json

```js
 "scripts": {
        //...
        "[test] unit": "jest src/.*.unit.test.tsx?",
        "[test] unit --watch": "jest src/.*.unit.test.tsx? --watch",
        "[test] integration": "jest __tests__/.*.int.test.tsx? --silent",
        "[test] integration --watch": "jest __tests__/.*.int.test.tsx? --watch --silent",
        //...
    },
```

If I run `yarn "[test] unit --watch"` or `npm run "[test] unit --watch"` it works  

But if I click on the play button near the script name in the left panel it calls `yarn run [test] unit --watch`, and throws a `Command "[test]" not found.`

[Link to the SO question](https://stackoverflow.com/questions/65478888/vscode-does-not-run-npm-script-names-with-whitespaces)

Is this a vscode bug?

**Comment by swapnilmisal** [comment]
@alexr00 I would like to contribute to resolving this issue.

**Comment by alexr00** [comment]
@swapnilmisal thanks for the interest! However, there is already a PR that fixes this issue that is almost ready to merge: https://github.com/microsoft/vscode/pull/113840

**Comment by swapnilmisal** [comment]
@alexr00 yeah sure,  I'll find some other issue to work on.
