### ISSUE TITLE
EXC_CRASH (Code Signature Invalid) when running tests on macOS

### ISSUE THREAD

**Issue by tanshihaj** [microsoft/vscode#113720]
It seems that macOS Catalina 10.15.7 have troubles with runnings macOS downloaded for test from `.vscode-test` folder. It seems there is some problems with singing:

```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
```

However `codesign --verify --verbose Visual\ Studio\ Code.app/Contents/MacOS/Electron` says that's everything ok, and even if I move/coppy Visual Studio Code.app from `.vscode-test` to the desktop it runs normally.

- VSCode Version: 1.52.1
- OS Version: macOS Catalina 10.15.7 (19H114)

Steps to Reproduce:

1. Clone on macOS Catalina 10.15.7 extension hello world example https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample
2. Run `npm install && npm run tests`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by top-master** [comment]
From: https://developer.apple.com/library/archive/qa/qa1884/_index.html

**Q:  When I run my Mac app, it crashes immediately, and the crash log says Exception Type: EXC_CRASH (Code Signature Invalid). What is going on here?**

A: The crash log indicates that your app is signed with your Mac App Store distribution identity, with the certificate’s Subject Common Name starting with “3rd Party Mac Developer Application.” Mac apps signed this way can no longer be run directly. Here’s the background on this.

Over time, more Mac App Store technologies have been added that require entitlements that come from a provisioning profile. This started with push notifications and iCloud. Later, Game Center and Maps were added to the list.

Recently, the `com.apple.developer.team-identifier` entitlement was added to all new Mac provisioning profiles. This means that, going forward, distribution builds of Mac apps cannot be run directly; they are for submitting to iTunes Connect for app review only

Instead, developers should adopt the Archive Build Workflow in [QA1778: How to reproduce bugs reported against Mac App Store submissions][1] for testing the builds that they plan to submit for the Mac App Store. On Xcode 6, select `Export as a Mac Application`. You won't see any chance to select your development signing identity, but Xcode will export the app from the archive as it was signed at build time. So the result will be the same.

You can create an installer package containing your development-signed app by hand with the `productbuild` [tool](x-man-page://1/productbuild), like this:
```
$ productbuild --component Sample.app /Applications --sign “3rd Party Mac Developer Installer:" Sample.pkg
```
Then install the package as documented in [Testing the Mac Installer Package][2]:
```
$ sudo installer -store -pkg Sample.pkg -target /
```
This workflow means that you will need to add your beta testers’ test systems to your Mac Developer Program account so they will be able to run your app.

Another possibility is to use `Xcode Organizer > Export > Export a Developer ID-signed Application`. Developer ID-signed apps can be run by anyone. However, code that uses technologies only available to Mac App Store apps, such as receipt validation, iCloud, and push notifications, will not work if your app is Developer ID-signed. You might need to temporarily disable those parts of your app if you opt for the Developer ID testing approach.

 [1]: https://developer.apple.com/library/mac/qa/qa1778/_index.html
 [2]: https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/SubmittingYourApp/SubmittingYourApp.html#//apple_ref/doc/uid/TP40012582-CH9-SW40

**Comment by deepak1556** [comment]
Does this issue persist with latest stable `1.74` ?

**Comment by tanshihaj** [comment]
Confirm that on 1.74.1 there is no problem.

**Comment by deepak1556** [comment]
Thanks for confirming.

**Comment by top-master** [comment]
@deepak1556 Which commit and/or PR did fix this?
(link please, no matter if `vscode` or `vscode-test`.)

But this is a binary signing related, hence maybe there is no such commit?

**Comment by tanshihaj** [comment]
Btw I forget to mention - since 21 Jan I've changed laptop and issue doesn't reproduce on macOS Monterey 12.6.
