### ISSUE TITLE
Quitting application and re-opening only persists one window

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#11379]
- VSCode Version: 1.4.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Open more than one vscode window
2. Quit the app
3. Re-open the app

Expected: all previously open windows should be restored

Actual: only one window is restored

**Comment by bpasero** [comment]
Try with setting: `"window.reopenFolders": "all"`

**Comment by OliverJAsh** [comment]
Thanks, but this setting doesn't seem to be working for me?

**Comment by bpasero** [comment]
What happens?

**Comment by OliverJAsh** [comment]
Only one folder opens, not sure which one (most recently viewed?)

**Comment by bpasero** [comment]
@OliverJAsh can you try this:
* set "window.reopenFolders": "all" in your user settings (NOT workspace settings)
* open 2 windows on a folder (we do NOT restore empty windows)
* File > Quit
* Launch again

Works?

**Comment by OliverJAsh** [comment]
Here is my settings file, located at:
/Users/OliverJAsh/Library/Application Support/Code/User/settings.json

![image](https://cloud.githubusercontent.com/assets/921609/18380160/fb1e3666-766d-11e6-9c92-81e1bbf05ab5.png)

I followed your steps again and it seemed to work this time round. Odd! Thanks

**Comment by bpasero** [comment]
Ok then I do not see an issue here 👍
