### ISSUE TITLE
Debug: Twistie in hover tree is not properly aligned

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11375]
OS: OSX

See the twistie and the element next to it in the hover tree

![sep-01-2016 11-16-28](https://cloud.githubusercontent.com/assets/10746682/18162229/b1ae11ce-7035-11e6-8659-7d43315fbdfa.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11352
