### ISSUE TITLE
Visual Studio Code keeps reverting to old update

### ISSUE THREAD

**Issue by M-Chen-3** [microsoft/vscode#113702]
Issue Type: <b>Bug</b>

I've been a user of Visual Studio Code on Windows for about 3 months, and recently I've discovered a serious issue.

Ever since the November 2020 update, whenever I close my Visual Studio Code tab and then reopen it, it shows me the July 2020 update screen. It seems to revert as well, as it then doesn't show me the run/debug buttons and F5 no longer works as well.

When I hit "Help", I'm able to restart to update, then it shows me the November 2020 update screen and everything works normally again. But then the next time I close the tab and reopen it, it reverts again.

I have looked at the Visual Studio Code website and found nothing about this problem, and I've already reinstalled Visual Studio Code once. I have no antiviruses currently.

How can I prevent this from happening?

VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-5745M APU with Radeon(tm) HD Graphics   (4 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.19GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.41
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
java|red|0.73.0
html-preview-vscode|tht|0.2.5
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0

</details>

**Comment by joaomoreno** [comment]
Strange. Can you fully uninstall VS Code? It's possible that you have more than one installation in your machine, you can search for it. Then, reinstall VS Code and let us know if it keeps happening.

**Comment by M-Chen-3** [comment]
I just uninstalled and reinstalled VS Code! I tried first to uninstall it by clicking the "uninstall.exe" file, but afterwards VS Code still existed. Then I deleted the entire Microsoft VS Code file and that did the trick. When I reinstalled it, all my files and extensions were still there and it worked perfectly. Thanks for your help!
