### ISSUE TITLE
Flaky test: get application scope settings are not loaded after defaults are registered when workspace folder is passed

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#113760]
Failed on macOS in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=98956&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d55b56b-c0b2-5f64-1c6a-62c9163a0d5b&l=7728

```
  6415 passing (2m)
  35 pending
  1 failing

  1) WorkspaceConfigurationService-Multiroot
       get application scope settings are not loaded after defaults are registered when workspace folder is passed:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by sandy081** [comment]
This test should not fail unless the underlying fs takes long time to do some fs operations. 

@bpasero Is it recommended now to use `flakyTestSuite` for all tests using fs?

**Comment by bpasero** [comment]
You can use `flakySuite` and it will just ensure a `timeout` of 20s and `retry` of 3, nothing else. I have not adopted it blindly for all tests that need fs, only in those cases where I saw them failing previously.

**Comment by sandy081** [comment]
I have not seen this test failing before and I am also not inclined to add it to `flakySuite`. 

@alexdima Is it ok to wait for next failure before adding to the flakySuite?

**Comment by bpasero** [comment]
I thought we had discussed that we use `timeout` and `retry` for any test that failed once. Isn't this a sign of a flaky test if it failed once? How does it change if we wait more?

**Comment by sandy081** [comment]
Yeah I remember that. This test case is mainly failing because fs operations took long time. I can change the corresponding test suite to use `timeout` and `retry`. Probably all tests using fs operations shall follow the same strategy?

**Comment by bpasero** [comment]
> Probably all tests using fs operations shall follow the same strategy?

I would not do this for all tests until a build failed. I think going in case-by-case via issues still allows a developer to change the test to not use fs at all if that is possible, e.g. by passing in a in-memory fs provider.
