### ISSUE TITLE
Provide an event to know when another extension has activated.

### ISSUE THREAD

**Issue by bcanzanella** [microsoft/vscode#113783]
We'd like to take advantage of some extension points that GitLens has created related to pull requests. (see here https://github.com/eamodio/vscode-gitlens/blob/11d32802890cfbeefc4586dbf678f047c4a13761/test/extension.test.ts). 

Unfortunately there isn't a great way to know when the GitLens extension has activated from our [CodeStream] extension. The best I can think of is some sort of polling (pseudo code below) as part of the CodeStream activation:

```
const getGitLens = () =>
		extensions.getExtension<Promise<GitLensApi>>("eamodio.gitlens") ||
		extensions.getExtension<Promise<GitLensApi>>("eamodio.gitlens-insiders");
	let gitlens = getGitLens();
	if (!gitlens) {
		// no gitlens
	} else {
		let i = 0;
		const timeout = setTimeout(async _ => {
			gitlens = getGitLens();
			if (!gitlens) {				
				clearInterval(timeout);
				return;
			}
			if (gitlens.isActive) {
				const api: GitLensApi = await gitlens.exports;
				api.registerActionRunner("openPullRequest", {
					//yay it worked
				}		 				
				clearInterval(timeout);
			} else {				 
				i++;
				if (i === 9) {					 
					clearInterval(timeout);
				}
			}
		}, 15000);
	}
```

It would be great if our extension could listen for some kind of activation event from a third-part extension like GitLens to avoid polling.

**Comment by eamodio** [comment]
@sandy081 It would be nice if there was an `onDidActivate`/`onDidDeactivate` either for all extensions like the `onDidChange` or on a specific `Extension` instance. That way extensions could avoid forcing an activation and only take an action when/if the extension in question becomes activated.

This would be useful for optional integration points between extensions.

**Comment by alexdima** [comment]
@eamodio Here is a pattern that we have used succesfully in the past, for example with the docker extension. You can define your own extension points! So, for example a interested extension would do something like this in its `package.json`:
```
"contributes": {
  "gitlens.actionRunner": [ "openPullRequest" ]
}
```

Then, from the gitlens extension (immediately on activation or soon after activation), you can use `vscode.extensions.getAll()` and loop through all package.json for all extensions and check if one of them contains "gitlens.actionRunner". You can then activate that extension as part of the gitlens activation, soon after the gitlens activation, or perhaps just-in-time, right when running the "openPullRequest" action.

Depending on what makes most sense, you can even ask for the API in reverse, like the willing extension must return some predetermined API that you call into from gitlens.

**Comment by eamodio** [comment]
@alexdima interesting -- thanks! I still think this request is more natural and doesn't require special configuration by an extension to make it worth (and avoid extra loops through `vscode.extensions.getAll()` on start up and anytime extensions change).
