### ISSUE TITLE
Cannot open .exe - Javascript Error occurred in main process

### ISSUE THREAD

**Issue by emseymour** [Microsoft/vscode#11378]
- VSCode Version: 1.4.0.0
- OS Version: Windows 7 Enterprise 64-bit

Steps to Reproduce:

1. Downloaded VSCode-Stable from the main website
2. Tried to open Code.exe, get error window
![vscodeerror](https://cloud.githubusercontent.com/assets/10958375/18162829/f97b9f2c-702f-11e6-9813-0f1e58ad78f1.jpg)

**Comment by dbaeumer** [comment]
@emseymour this works for me without a problem. Can you start code from a terminal ?

**Comment by emseymour** [comment]
Hi @dbaeumer no, I got the same error window when trying from terminal

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/issues/10616

@joaomoreno fyi

**Comment by dbaeumer** [comment]
@bpasero thanks.

@emseymour can you check whether the APPDATA env variable is set in our terminal.

**Comment by emseymour** [comment]
Hi @dbaeumer @bpasero 
APPDATA wasn't set, but setting it has allowed me to open, thanks for your help!

**Comment by dbaeumer** [comment]
Dups #10616

**Comment by Mattgyver317** [comment]
If you just installed an update to your version of Java on your PC b4 *this occurred, then you may need to reinstall to the newest version of VSCode straight from the Visual_Studio website... 
->  https://code.visualstudio.com/download
