### ISSUE TITLE
Implement PHP symbol search

### ISSUE THREAD

**Issue by sebfie** [Microsoft/vscode#11371]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.16

Steps to Reproduce:
1. Import a magento project
2. Quick search Mage_Catalog_Model_Product_Api_V2

Hello, I work on magento projects, and I would like to be able to search using class name. 
Example : `Mage_Catalog_Model_Product_Api_V2`

In `magento Mage_Catalog_Model_Product_Api_V2` => go to `app/code/core/Mage/Catalog/Model/Product/Api/V2.php`. So it will be able to find file if I replace "_" by "".

Can we do it by default or set a settings for that? Thx

**Comment by bpasero** [comment]
@sebfie what language is this?

Moving to Martin as owner of symbol search but this could well be for an unsupported language.

**Comment by sebfie** [comment]
It's just php with zend naming convention. 

Sébastien fieloux
0698458781
sebastien.fieloux@gmail.com
http://www.sebfie.com

**Comment by aeschli** [comment]
What do you call 'Quick search'? Can you add a screenshot?

**Comment by aeschli** [comment]
@sebfie What exactly do you mean by 'Quick search'? Which keyboard shortcut. Can you maybe add a screenshot?

**Comment by sebfie** [comment]
I mean cmd + p

Sébastien fieloux
0698458781
sebastien.fieloux@gmail.com
http://www.sebfie.com

**Comment by bpasero** [comment]
@sebfie I assume you are using an extension for PHP to be able to find symbols? Is that true?

**Comment by sebfie** [comment]
No I don't, in fact I just want that "underscore" can be ignored from search. 
Searching `Mage_Catalog_Model_Product_Api_V2 ` should be equal to `MageCatalogModelProductApiV2 ` which works!

![capture_d ecran_2016-09-08_a_09_42_23](https://cloud.githubusercontent.com/assets/862129/18341098/a99b87b4-75a8-11e6-98fe-1addbe82c858.png)

**Comment by bpasero** [comment]
@sebfie that is a PHP symbol and not a file right?

**Comment by sebfie** [comment]
@bpasero That's a file, look on left column.

**Comment by bpasero** [comment]
@sebfie thanks for clarification, to rephrase: You want to open the class name of a PHP file (V2.php).

@aeschli @jrieken please triage accordingly, this is about opening a symbol from a PHP file, ignoring underscores.

**Comment by sebfie** [comment]
Right, in fact in zend framework, class name correspond to file PATH, so I want to put class name on this search and it will be able to find the corresponding file.

**Comment by jrieken** [comment]
You are looking for php symbol search which we didn't implement

**Comment by felixfbecker** [comment]
PHP IntelliSense now supports workspace symbol search in v0.0.8
https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

![workspacesymbol](https://cloud.githubusercontent.com/assets/10532611/18989665/7b98f07e-870d-11e6-973b-fa17c922dafd.gif)

**Comment by sebfie** [comment]
I do not understand why everyone is speaking about symbol. My request is simple : 

"Be able to ignore underscore in this "quicksearch" "

**Comment by felixfbecker** [comment]
Because you asked to open a file by class name. That is workspace symbol search. But the underscore should already be ignored, the file search has had fuzzy search for several iterations now.

**Comment by sebfie** [comment]
No it's not the case, it's not ignored.

In fast I asked for searching class name because in zend, class name is representing path : 

`App_Stats_Model_Stats` will be in `app/stats/model/stats.php`

Do I need a configuration to make underscore ignored?

**Comment by felixfbecker** [comment]
Yeah VS Code cannot just completely "ignore" a specific character because one (outdated!) autoloading standard in one language happens to map that specific character to the directory separator.

I suggest you try out PHP IntelliSense and if the workspace symbol search is not sufficient for your use case (PSR-0) open an issue

**Comment by jabranr** [comment]
To be honest, I would rather be typing `stats` to list the file and then select it. I would rather NOT type `App_Stats_Model_Stats`.

**Comment by sebfie** [comment]
In a magento product, you will have many stats files for exemple.

**Comment by roblourens** [comment]
For the file name quickopen case, it should now be fuzzy enough to ignore underscores. For the symbol case, that would be handled by an extension.

**Comment by sebfie** [comment]
Can you clarify and tell me how to configure vscode to ignore "underscore" ? Thx

**Comment by roblourens** [comment]
It should work automatically:

![image](https://cloud.githubusercontent.com/assets/323878/25867208/b8b849de-34ad-11e7-95c8-bb1796e13bae.png)

**Comment by felixfbecker** [comment]
I will also look at fuzzy searching once we have the new parser merged in

**Comment by sebfie** [comment]
In fact, I need the other way : 

<img width="618" alt="capture d ecran 2017-05-10 a 09 11 26" src="https://cloud.githubusercontent.com/assets/862129/25887046/b754062e-3560-11e7-859b-29a5fb0c512b.png">

Should find file : `Mage/Tax/Model/Sales/Total/Quote/Tax.php`

**Comment by felixfbecker** [comment]
Why are you not simply omitting the underscores while typing? I don't understand why you want to type more characters just so VS Code ignores them

**Comment by sebfie** [comment]
You can see my previous messages, because it's a php class respecting a naming convention, so, I search a php class, I copy/paste its name in quick search and find it. It works on atom for example.

**Comment by felixfbecker** [comment]
But you are copy+pasting it into the file search. If you copy+pasted it into symbol search it would work.

**Comment by sebfie** [comment]
You mean if I search using `#Mage_Tax_Model_Sales_Total_Quote_Tax` ?

**Comment by felixfbecker** [comment]
Works for me. 

![image](https://cloud.githubusercontent.com/assets/10532611/25888401/4e6dbfdc-3566-11e7-890f-986cba3b2854.png)

Have you installed the PHP IntelliSense extension?

**Comment by sebfie** [comment]
You are right, I forgot to install it, thx a lot !

**Comment by sebfie** [comment]
mmm in fact magento project seems too big, it does not show any results

**Comment by sebfie** [comment]
Finally, I just want to be able to use search file and ignore underscore, It does not seems to be a so hard feature to have. It can be a params in config : `search_file_ignore_char`

**Comment by felixfbecker** [comment]
Imo it screws the semantics. You want to search for a symbol, but you want to search by it from file search. And you want VS Code to transform your query in a way that matches the naming conventions of a very specific language convention. PSR-0 (underscores) is legacy. If VS Code supports searching by PSR-0 convention, they should support searching by PSR-4 convention (backslashes) too. If they support PHP naming conventions, they should support Java conventions (dots) too. VS Code can't special case all the language conventions in _file search_. That's what _language servers_ are for, and the _symbol search_ they provide.

If you have a specific problem with magento please open an issue at https://github.com/felixfbecker/php-language-server.

**Comment by sebfie** [comment]
That's why I suggest an option to ignore some char, users can use or not.

Thx anyway but I can not use your editor for magento/zend projects.

**Comment by felixfbecker** [comment]
@sebfie Please open an issue at the LS repo. If you have magento or zend as a Composer dependency the index will be cached after the first time.
