### ISSUE TITLE
extHostSearchTest.ts: some skipped tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113761]
This is to report that skipped tests should either be deleted or fixed:

https://github.com/microsoft/vscode/blob/1927f9b6e07ad66d4ee06ee794d2a2ab92fa3fd2/src/vs/workbench/test/electron-browser/api/extHostSearch.test.ts#L464-L464

https://github.com/microsoft/vscode/blob/1927f9b6e07ad66d4ee06ee794d2a2ab92fa3fd2/src/vs/workbench/test/electron-browser/api/extHostSearch.test.ts#L500-L500

https://github.com/microsoft/vscode/blob/1927f9b6e07ad66d4ee06ee794d2a2ab92fa3fd2/src/vs/workbench/test/electron-browser/api/extHostSearch.test.ts#L536-L536

**Comment by roblourens** [comment]
Not sure why I skipped them, they seem fine
