### ISSUE TITLE
Update to v1.52.1 is stuck

### ISSUE THREAD

**Issue by aditya-giri** [microsoft/vscode#113719]
- VSCode Version: 1.52.0
- OS Version: Microsoft Windows 20H2 (Build 19042.685)

Steps to Reproduce:

1. Click on settings icon in the bottom left corner > Install Update
2. Notification pops up in the bottom right corner informing me that "Visual Studio Code 1.52.1 is being installed in the background". It never goes away and I never get the usual UAC prompt to install VS Code.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?

**Comment by aditya-giri** [comment]
I can. Do you want me to collect some diagnostic data before I do so?
Also, do you want me to reinstall the same version (1.52.0) and then try to upgrade? Or do you want me to install 1.52.1?

**Comment by joaomoreno** [comment]
You can try 1.52.1 and then see how the update goes.
