### ISSUE TITLE
Not using installed extensions 

### ISSUE THREAD

**Issue by shripad1** [microsoft/vscode#113701]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by khashayarnazari** [comment]
I want to learn hacking, I like it very much, and I have a big problem. My family needs money for surgery, so I want to learn in Iran, because I do not like Iran. Please help me.

**Comment by khashayarnazari** [comment]
I want to learn hacking, I like it very much, and I have a big problem. My family needs money for surgery, so I want to learn in Iran, because I do not like Iran. Please help me.
