### ISSUE TITLE
useless architecture in ubuntu source list

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#113739]
please remove useless architecture items `arm*` in x86 system.

```
N: 鉴于仓库 'http://packages.microsoft.com/repos/vscode stable InRelease' 不支持 'armhf' 体系结构，跳过配置文件 'main/binary-armhf/Packages' 的获取。
N: 鉴于仓库 'http://packages.microsoft.com/repos/vscode stable InRelease' 不支持 'arm64' 体系结构，跳过配置文件 'main/binary-arm64/Packages' 的获取。
```

**Comment by joaomoreno** [comment]
We no longer publish ARM to this repo, those are old and likely to stay there. Do they cause any harm to you?

**Comment by gdiet** [comment]
Any harm? - Well, it's annoying if each time I run `sudo apt update` I get two messages like
`N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'arm64'`

Note for all who are affected: This can be fixed manually by editing the package sources and changing
`deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/vscode stable main`
to
`deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main`

But I would appreciate if the .deb package would be fixed so this doesn't happen at all.

**Comment by joaomoreno** [comment]
Yeah today I realized there is indeed a problem. Already fixed in master. Related issue: https://github.com/microsoft/vscode/issues/114137

Sorry for dismissing it so quickly. Thanks!
