### ISSUE TITLE
Missing "editor.action.customEditor.toggle" command

### ISSUE THREAD

**Issue by Gregoor** [microsoft/vscode#113756]
In https://github.com/microsoft/vscode/issues/86504#issuecomment-564218725 it was mentioned that this command exists. My VSCode installation seems to disagree: `Error: command 'editor.action.customEditor.toggle' not found`

And googling it only leads to the issue mentioned above. Has it been silently removed since?

**Comment by mjbvz** [comment]
This command was renamed to `workbench.action.toggleEditorType` (it was renamed so that it would also work for notebooks and other types of resources)
