### ISSUE TITLE
VS Code hangs frequently

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode#113727]
Issue Type: <b>Performance Issue</b>

Can't say if it's a extension or VS code itself.

VS Code suddenly hangs, and after some time, VS Code prompts to reload because main windows does not respond.

Never had this kind instability issues prioor to the Nov 2020 update.

I have not yet found a pattern..

My PC is an older i5 Lenovo.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.17GB free)|
|Process Argv|--crash-reporter-id 3c3c8955-bb4d-49b2-b984-6126f6d2daf7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    77	 11048	code main
    0	    10	  6500	   crashpad-handler
    0	    43	  6640	   utility
    0	   154	  8240	   gpu-process
    0	    66	  8904	   shared-process
    0	   249	 11000	   window (WiFiService.h - ChainedLights - Visual Studio Code)
    0	    11	  3108	     watcherService 
    0	    11	  1308	       console-window-host (Windows internal process)
    0	   137	  7952	     extensionHost
    0	    27	  7384	       "C:\Users\maxim\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\maxim\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=7952
    0	   288	 11732	       c:\Users\maxim\.vscode\extensions\ms-vscode.cpptools-1.1.3\bin\cpptools.exe
    0	    11	  5916	         console-window-host (Windows internal process)
    0	    30	 14292	     searchService
    1	    54	 11168	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (WiFiService.h - ChainedLights - Visual Studio Code)
|    Folder (ChainedLights): 31 files
|      File types: h(21) json(3) ino(2) html(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
vscode-gcode-syntax|app|0.4.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.22.0
better-cpp-syntax|jef|1.15.5
select-highlight-minimap|mde|0.1.0
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.3.0
vsonline|ms-|1.0.3076
vscode-json-transform|oct|0.1.2
cmake|twx|0.0.17
vscode-arduino|vsc|0.3.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspyt653:30237719
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30237827
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by iqapps** [comment]
I've just tried to use bisect but the result vas indeterminate, eventually suggesting that VS code is the problem, when i pressed bad button.

But Bisect also hangs when VS code hangs, which could cause Bisect to also fail.

I was able to reproduce the problem while bisect was still bisecting extensions. VS Code hung at a point where only two extensions was disabled, one was Arduino, the other was ?? (im sorry). It was the last iteration when bisect was enabling some more extensions that clearly causes the error, but I cannot find out which extensions was enabled just before the hang.

Is there a Bisect log I can find and upload ?

**Comment by iqapps** [comment]
Yet another hang up.

I'm getting a feeling, that this has to do with problems with popups from intellisense. But it is just a guess.

**Comment by iqapps** [comment]
Yet another hang.

Now I'm getting somewhere.

When I hoover a variable in my Arduino C++ class code with the name 'name', VS Code hangs.

If I rename that variable to ex. 'fname', it does not hang.

My guess is that the number of possible 'name' entries in the language parser buffer is to large for VS Code to handle.

I just need to avoid using 'name' in my variables.

I have tried in the Arduino *.ino file to create a line:

String name;

Then hover it - bang - VS Code hangs.

Thats actually a bit funny.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
