### ISSUE TITLE
Error while editing in phyton

### ISSUE THREAD

**Issue by Superkingpat** [microsoft/vscode#113743]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__))+"/SubFolder")
import ProgramFromSubFolder <pylint(import-error)>

"Other way program run normally. It only show error when editing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
Please include the version of VSCode you are using.

Do you mean that you are seeing a pylint error?

**Comment by Superkingpat** [comment]
VSCode version is 1.52.1
That is what it print out.

Unable to import 'Edit' <pylint(import-error)>

But when I start program it work normally. Like there is no problem at all.
