### ISSUE TITLE
Moving VS Code Insiders ARM to programs "folder" on M1 mac makes it unable to start (crashes/exits immediately). Can only start from "downloads" folder

### ISSUE THREAD

**Issue by NielsKSchjoedt** [microsoft/vscode#113751]
- VSCode Version: 1.53.0-insider
- OS Version: Bigsur 11.1 on M1 macbook pro

Steps to Reproduce:

1. Download the regular VS code insiders version (non-arm), drag it into the "/Applications" directory, start it. 
2. Delete it from there again.
3. Download the VS code insiders arm version, drag it to "/Applications" - like you would normally do when installing a mac OS program.
4. Start the vs code insiders => crash💥

VS code insiders ARM will only start if I launch it while in the "/Downloads" location. I wonder if it has to do with the fact that I by mistake had the "regular" (non arm) version installed briefly.

**Comment by Ynewtime** [comment]
Same here. VS Code can only be launched from any folders other than `/Applications`.

**Comment by deepak1556** [comment]
Can you check if running with `--user-data-dir <some-absolute-path>` fixes the issue ?

**Comment by ademgcl** [comment]
> Can you check if running with `--user-data-dir <some-absolute-path>` fixes the issue ?

Getting the very same error. This fixes the issue

**Comment by deepak1556** [comment]
Merging this to https://github.com/microsoft/vscode/issues/113680

**Comment by deepak1556** [comment]
You can also workaround by starting the app with `--no-cached-data` instead of deleting data folders.
