### ISSUE TITLE
Add a command to sort tabs my most recently used

### ISSUE THREAD

**Issue by ZacharieBaptiste** [microsoft/vscode#113717]
I find my self constantly searching for tabs and needing to close them. Tab sorting and closing has become a task I need to think about while coding since I switched to VSCode. 

With a simple sort tabs by last recently used option, this way it's going to be simple to find the tab you recently used.

This is a common feature in other IDE's.

Another nifty add-on feature to do, is adding a limit on open tabs and auto closing them, of course only in the case they don't have unsaved content.

This has become so frustrating, and I never understood why I always felt frustrated using VSCode, but now I finally figured it out, it was the tab sorting.

**Comment by yume-chan** [comment]
1. `workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup` command (<kbd>Ctrl/Cmd</kbd> + <kbd>Tab</kbd>) lists opened tabs in recently used order, and you can close them in the popup
2. Set `workbench.editor.limit.enabled` setting to `true` and `workbench.editor.limit.value` to the number you want, Code will limit the number of concurrent opened tabs.
