### ISSUE TITLE
URL with port number in terminal opens to wrong port

### ISSUE THREAD

**Issue by rensa** [microsoft/vscode#113733]
Issue Type: <b>Bug</b>

1. Run `livereload` in a folder
2. Livereload prints to the terminal:

```
[I 210104 13:35:24 server:335] Serving on http://127.0.0.1:35729
```

3. Ctrl+click the hyperlink for port 35729
4. Default browser (in this case, Microsoft Edge Dev) opens a new tab to `http://127.0.0.1:35730`

Expected: default browser would open to port 35729, not 35730.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (24.12GB free)|
|Process Argv|--crash-reporter-id c7f5e4c5-bee4-4bc0-b9c3-50b06aeb2da9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 5 3600 6-Core Processor (12 x 3593)|
|Memory (System)|25.02GB (24.49GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.154.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
debugger-for-edge|msj|1.0.15
diff|raf|0.0.1
better-toml|bun|0.3.2
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
pythonvspyt700:30237718
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by Tyriar** [comment]
This might be by working as expected due to WSL port forwarding?

**Comment by alexr00** [comment]
We shouldn't actually be doing any port forwarding for WSL.

**Comment by alexr00** [comment]
I assume that the open is going through here: 

https://github.com/microsoft/vscode/blob/91f00c7c285ecd85a8d86298183180703d719486/src/vs/workbench/electron-sandbox/window.ts#L505-L525

@mjbvz is there a way to not do the resolve external URI for WSL?

**Comment by mjbvz** [comment]
@alexr00 Could the wsl remote extension implement a `ITunnelProvider` that either returns `undefined` or returns the original url?

**Comment by alexr00** [comment]
Huh, nice idea (wish I'd thought of it)! I'll take a look.

**Comment by Tyriar** [comment]
I actually hit this yesterday, links are broken on the WSL terminal 🙁

**Comment by alexr00** [comment]
Bonus: while testing I found that trying to connect to something that was listening on 0.0.0.0:3000 and running in WSL didn't work. BUT you can connect on localhost. So with the tunnel factory, clicking on 0.0.0.0 links in the terminal from WSL will work.
