### ISSUE TITLE
Allow syncing all files and folder located in ~/…/Code/User/. Some important extensions settings are there.

### ISSUE THREAD

**Issue by Fred-Vatin** [microsoft/vscode#113774]
For instance, there is the folder named **globalStorage** where some extensions store their settings ([color-manager](https://github.com/royaction/vscode-colormanager)). @royaction

Project Manager store projects settings in `~\…\Code\User\projects.json`. See alefragnani/vscode-project-manager#431.

There may also be `…\Code\User\Emmet Settings\snippets.json` if you set it so in 
```json
"emmet.extensionsPath": "${env:APPDATA}\\Code\\User\\Emmet Settings",
```

Currently, it can only be handled by [shanalikhan sync extension](https://github.com/shanalikhan/code-settings-sync) or [zokugun Sync Settings](https://github.com/zokugun/vscode-sync-settings) not the built-in settings-sync.

Users and extensions devs are waiting for a built-in solution. A glob pattern to pick which files and folder to include would be appreciated.

**Comment by sandy081** [comment]
Extensions can now synchronize state in globalStorage, please file an issue against them.

**Comment by freMea** [comment]
> Extensions can now synchronize state in globalStorage, please file an issue against them.

Nice but what about other files like `…\Code\User\Emmet Settings\snippets.json` ?

**Comment by sandy081** [comment]
How different are these from regular user snippets ?

**Comment by freMea** [comment]
> How different are these from regular user snippets ?

https://docs.emmet.io/customization/snippets/

I personally use this by duplicating huge default emmet snippets and overriding them with customization when needed and some addition.

**Comment by sandy081** [comment]
Is it supported by an extension?

**Comment by freMea** [comment]
> Is it supported by an extension?

No, it is an emmet feature controlled by this setting 
```json
"emmet.extensionsPath": "${env:APPDATA}\\Code\\User\\Emmet Settings",
```

Allowing custom folder in _code\user_ to be synched would make VSCode user environment truly…synched.

**Comment by sandy081** [comment]
I see, this is coming from built in emmet extension. At present we do not support custom user files from extensions. I would use this issue to track that feature.

**Comment by TylerLeonhardt** [comment]
https://github.com/alefragnani/vscode-project-manager would love to see this for their projects.json's

**Comment by majkinetor** [comment]
Its essential feature, this way sync is half baked.
