### ISSUE TITLE
cmd/ctrl + shift + p -> set syntax/language

### ISSUE THREAD

**Issue by gkiely** [microsoft/vscode#113771]
Ability to set a file's language mode or syntax from the command menu.

**Comment by IllusionMH** [comment]
/needsMoreInfo

There is already `>Change Language Mode` for Command palette. Is it what you are looking for you have some other request?

If later - provide more info about your request and how it is different form Change Language Mode

**Comment by gkiely** [comment]
My apologies, I was coming from sublime and didn't know the terminology. Closing.
