### ISSUE TITLE
Polymer and x-tag support

### ISSUE THREAD

**Issue by a8775** [Microsoft/vscode#1137]
WebComponents are more and more frequently used.
Is it possible to add to Code the syntax highlighting and support for debugging?
Now the Polymer and x-tag are on the horizon.

**Comment by Tyriar** [comment]
Is the HTML highlighting not sufficient for Polymer HTML files? They are pretty much just regular HTML and share the same file extension.

On debugging, my personal opinion is that Polymer, x-tag and web components in general are not widespread enough to be worth the effort for first class support. React has also just emerged and seen a lot of adoption which is a method of implementing web components without the native web components apis (that still aren't widely implemented).

- [Web components on caniuse.com](http://caniuse.com/#search=web%20components)
- [Mozilla is holding off on HTML imports until ES6 modules come](https://hacks.mozilla.org/2014/12/mozilla-and-web-components/)

**Comment by a8775** [comment]
You are right, most of the time it's working very well but there are sometimes situations when it's not perfect.

![snip_20151209194907](https://cloud.githubusercontent.com/assets/14092227/11695184/2aec8674-9eae-11e5-99da-110c18ee6d6a.png)
This is an example from paper-dropdown-menu.html, you can see my point. 

It would be very useful to have IntelliSense:
![image](https://cloud.githubusercontent.com/assets/14092227/11695748/2520e0d4-9eb1-11e5-86bb-16254cc1ac45.png)

I know, lack of native suport is a problem. I think we should look forward and implement the most up to date features. In general WebComponents seems to be approaching very fast - the Angilar2 team is working realy very fast, similar to Polymer group. 

Any way, I find Code perfect when I'm doing experiments with new tech :+1:

**Comment by Tyriar** [comment]
`:host` specifically is part of [the shadow DOM spec](http://caniuse.com/#feat=shadowdom) which vscode probably won't support [until at least 2 browsers support or at least strong interest](https://github.com/Microsoft/vscode/issues/806) (chrome and opera count as one).

**Comment by jmalonzo** [comment]
Second this, especially for CustomElements. It would be nice if we get IntelliSense support for CEs.

IMO, we don't need to wait for FF, Safari, Edge implementations to implement support. You can write web components today and it would still work in those browsers provided you use the WebComponent polyfill.

**Comment by vimalraj-a** [comment]
+1 for Polymer support in vscode.
I tried to write Polymer custom element in typescript with help of typings(polymer.d.ts) and It worked very well but IntelliSense was not working as I expected. 

It never shows the polymer functions when I use `this.<ctrl+space>`.


![image](https://cloud.githubusercontent.com/assets/13977942/13198813/ed2358b2-d838-11e5-87f4-dcc6828a75b8.png)

**Comment by mjbvz** [comment]
Polymer specific features are something that we expect an extension to provide. Here's one extension that looks promising: 

https://marketplace.visualstudio.com/items?itemName=polymer.polymer-ide

If you notice cases where the built-in TypeScript or JavaScript flows have the wrong behavior, please open a new issue with so that we can investigate.

Thanks
