### ISSUE TITLE
For Java intellicode suggests a lot of poor choices

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode#113726]
Issue Type: <b>Bug</b>

In java, when typing code, intellicode should be smart enough to know what context I am in, like coding a class and it should only provide what the most likely keyword I am going to type next.

1. Create a class person with two private string fields
2. Type "p", note what is suggested (should be private, public).
3. After private, type "S", note what is suggested, in fact typing "Str" still does not yield "String" as a top choice.

This is no where close to improving productivity like with intellij, would love to see this fixed.

I'm sure this is also a problem with other languages like TypeScript, JS, GoLang.

## After pressing "p"

![bug-0](https://user-images.githubusercontent.com/439226/103478718-967ade80-4d96-11eb-954d-3695c016f96a.png)

## After pressing "S"

![bug-1](https://user-images.githubusercontent.com/439226/103478721-9b3f9280-4d96-11eb-865d-33a5ea3e4f8d.png)

## After pressing "Str"

![bug-2](https://user-images.githubusercontent.com/439226/103478868-9a5b3080-4d97-11eb-9fca-a7024072848e.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3967)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|31.29GB (9.76GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.1
vscode-base64|ada|0.1.0
vscode-tomcat|ada|0.11.3
markdown-toc|Ala|1.5.6
Bookmarks|ale|11.1.0
ng-template|Ang|0.1100.2
vscode-browser-preview|auc|0.6.7
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.8
java-decompiler|dgi|0.0.2
EditorConfig|Edi|0.15.1
prettier-vscode|esb|5.5.0
markdown-preview-bitbucket|hbr|1.0.0
java-properties|ith|0.0.2
vscode-peacock|joh|3.8.0
solidity|Jua|0.0.76
sort-typescript-imports|mic|1.4.1
vscode-docker|ms-|1.1.0
python|ms-|2020.5.86806
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.3.2
debugger-for-chrome|msj|4.12.8
angular2-inline|nat|0.0.17
vetur|oct|0.24.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.24.0
vscode-manifest-yaml|Piv|1.24.0
vscode-spring-boot|Piv|1.24.0
platformio-ide|pla|1.10.0
java-ide-pack|pve|1.2.1
java|red|0.59.1
vscode-yaml|red|0.13.0
markdown-preview-enhanced|shd|0.5.15
vscode-checkstyle|she|1.3.3
java-generate-setters-getters|soh|5.3.0
sonarlint-vscode|Son|1.19.0
language-stylus|sys|1.11.0
find-then-jump|tra|2.0.4
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.27.1
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.22.3
vscode-maven|vsc|0.27.0
vscode-spring-boot-dashboard|vsc|0.1.10
vscode-spring-initializr|vsc|0.6.1
better-align|wwm|1.1.6
vscode-java-saber|You|0.1.1
markdown-pdf|yza|1.4.4
vscode-aspell|zap|0.1.4

(8 theme extensions excluded)

</details>

**Comment by WPluim** [comment]
\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM8': FileNotFoundError(2,

**Comment by tommai78101** [comment]
Please file an issue over at vscode-java github, maintained by RedHat.

**Comment by rajinder-yadav** [comment]
Will do thanks

**Comment by rajinder-yadav** [comment]
Closing, PR raised with RH: https://github.com/redhat-developer/vscode-java/issues/1754
