### ISSUE TITLE
Refactoring leaves files dirty when auto save is on

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113752]
Steps to Reproduce:

1. run out of sources and leave auto save on (after 1s)
2. use a refactoring to extract a class into a new file
3. notice how editors appear dirty

I find this weird, when auto save is enabled I would expect that editors save automatically, but maybe I am missing something?

![recording](https://user-images.githubusercontent.com/900690/103537215-51d56d00-4e94-11eb-97c3-11f41778a2db.gif)

**Comment by jrieken** [comment]
I think that's nothing the refactoring should decide

**Comment by bpasero** [comment]
My mistake, I had auto save delay to 30 seconds...
