### ISSUE TITLE
vscode.debug.onDidReceiveDebugSessionCustomEvent() only called when the 'process' event occurs

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#113725]
I am trying to make a vscode extension to interact with the debugger, but I realized the `onDidReceiveDebugSessionCustomEvent()` method does not work properly, because it only calls the listener when the 'process' event occurs.
```typescript
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.debug.onDidReceiveDebugSessionCustomEvent(dapEvent => {
        console.log(dapEvent.event);
    });
}

// this method is called when your extension is deactivated
export function deactivate() {}
```

It doesn't call the listener when other events like 'stopped' occur.

- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a VSCode extension with the code provided above
2. Execute it
3. In the new VSCode window that opens, create a javascript with some code and set a breakpoint anywhere
4. Make sure the `activate()` function gets called to register the listener by triggering the extension activation event defined in package.json
5. Execute the code and see how the only thing printed in the debug console is 'process' when it actually should have printed some other events like 'stopped'

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
As the description says `onDidReceiveDebugSessionCustomEvent` fires for "custom" events. You cannot use it to intercept regular DAP events. If it fires on "process" events, then this is a bug.

**Comment by adriancuadrado** [comment]
How do I intercept regular DAP events, then?

**Comment by weinand** [comment]
You can use the "DebugAdapterTracker" API. 
Example: https://github.com/weinand/augmented-debug

**Comment by isidorn** [comment]
`"process"` event is not handled by vscode and thus it is fired as a "custom" event
I have pushed a fix for this
