### ISSUE TITLE
Webview tests are skipped

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#113769]
Couple of milestones ago I have skipped these tests becuase they were failing. I am not sure if I created the issue at the moment but I am doing that now. Sorry if I did not ping sooner.

Code pointer
https://github.com/microsoft/vscode/blob/ca370bdb0aef33613cbaced701c38281cf851e19/extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts#L20

**Comment by bpasero** [comment]
I had to revert this change: https://github.com/microsoft/vscode/commit/6bd7b70515d546aba9010d2a0249a1a19205822f

I think they cause our browser tests to hang/fail:

```
 vscode API - webview
    1) webviews should be able to send and receive messages
    √ webviews should not have scripts enabled by default (1001ms)
    2) webviews should update html
    - webviews should preserve vscode API state when they are hidden
    3) webviews should preserve their context when they are moved between view columns
    4) webviews with retainContextWhenHidden should preserve their context when they are hidden
Terminate batch job (Y/N)? 
##[error]The task has timed out.
```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=99855&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&l=136
