### ISSUE TITLE
VSCode and git commit --amend bug

### ISSUE THREAD

**Issue by hquote** [microsoft/vscode#113718]
Issue Type: <b>Bug</b>

When I change a file (which is under git) and git correctly sees it as M (modified) and then I decide not to make a new commit, but rather amend the previous  one( using the command : "git commit --amend" in external terminal) everything goes OK with git (showing status: "nothing to commit, working tree clean"), but VSCode still thinks the file is not commited and it's still Modified. Amusingly, when I click Changes in this file, VSCode shows in a diff window that there are none, though.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (7.36GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/mnt/d/vlad/programming/c/Learn --remote=wsl+Ubuntu --crash-reporter-id 8052a0e0-b98e-4975-bd70-511db2959e26|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|9.24GB (8.72GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-language-pack-ru|MS-|1.52.2
remote-wsl|ms-|0.52.0
vscode-todo-highlight|way|1.0.4
vscode-language-pack-ru|MS-|1.52.2
cpptools|ms-|1.1.3

</details>

**Comment by hquote** [comment]
Closing and restarting VSCode helps though. It indicates that there's a small bug in syncronizing the git status

**Comment by eamodio** [comment]
How are you opening this repo? Is the repository (the `.git` folder) inside the folder that you are opening in VS Code? If the `.git` folder is outside the folder you are opening in VS Code, this is a known issue with our file watching (we only watch for changes inside the folder opened).
