### ISSUE TITLE
JavaScript-file does not show all console.logs while node does

### ISSUE THREAD

**Issue by chappy721** [microsoft/vscode#113744]
Hi everybody and happy new year:-)

mhm, I have a strange problem with a JS-file. When I run it within VS Code, it does not show all three console.log-lines, sometimes only the first, sometimes the first two, or sometimes the first with a "Canceled" as a second line.
But, when I run it from the terminal with
`node curry3.js`
it works every time perfectly.

There is no difference if I use a launch.json file or not. Neither if F5 or Ctrl & F5.

Ah, first I thought there is a problem with conflicting node versions, but I use the exact same commandline in terminal as VS Code writes in the debug console:
`C:\Program Files\nodejs\node.exe .\curry3.js`
In the terminal window it works fine, within VS Code with F5 (or similar commands) it doesn't.

Does anybody have an idea what's wrong here?

Thanks a lot and best wishes
Daniel

- VSCode Version: 1.52.1
- OS Version: Win 10 20H2

Does this issue occur when all extensions are disabled?: Yes

Here's the small codesnippet:
```
list2 = [2,6,77,1,3,9,0,44];

function firstN2(list){
    return function(n){
        return list.slice(0,n);
    }
}

firstX = firstN2(list2);
console.log(firstX(3));
console.log(firstX(2));
console.log(firstX(5));
```

**Comment by mjbvz** [comment]
@connor4312 Assigning you since this is about running JS

**Comment by connor4312** [comment]
/duplicate https://github.com/microsoft/vscode-js-debug/issues/161
