### ISSUE TITLE
VSCode Crashed reason OOM

### ISSUE THREAD

**Issue by BravesDevs** [microsoft/vscode#113737]
Hello, I am working on angular and VSCode keeps crashing with the about title/error message, I'm tired of it please solve this issue as soon as possible, because switching to another code editor is quite hard for me as VSCode is my primary editor since beginning as it provides best features and comforts then others. So, its a request to solve this issue ASAP.

**Comment by rzhao271** [comment]
Hi, can you attach a crash dump please?
See https://github.com/microsoft/vscode/wiki/Native-Crash-Issues for instructions on generating one

**Comment by rzhao271** [comment]
Potential related issue #113291

**Comment by asphub** [comment]
Crash happening continuously. In my case its happening when run an `ng serve` command on integrated terminal on an angular project.

**Comment by rzhao271** [comment]
@asphub is the crash happening also due to out-of-memory issues?
If it is not, can you create a new issue? Otherwise, can you attach a crash dump? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
