### ISSUE TITLE
Mardown preview should be disabled when Git diff 

### ISSUE THREAD

**Issue by fchastanet** [microsoft/vscode#113730]
- VSCode Version: 1.52.1
- OS Version: Linux x64 5.4.0-58-generic

Steps to Reproduce:

1. on a git repo update an existing markdown file
2. diff the file with existing one
3. I have no way to toggle to text only file to diff clearly the differencies

Does this issue occur when all extensions are disabled?: Yes

complementary I found this open question [How to configure multiple viewers for a file type in VS Code?](https://stackoverflow.com/questions/65234050/how-to-configure-multiple-viewers-for-a-file-type-in-vs-code)

for me it's a bug because it was working correctly before markdown preview was existing

kind regards

**Comment by mjbvz** [comment]
The markdown preview must be explicitly opened. Do you have any extensions or settings installed that automatically open the markdown preview?

**Comment by fchastanet** [comment]
first of all I found that I was not launching code insiders correctly, I thought that installing it was overriding default code but actually I had to launch it like that: 
`code-insiders --disable-extensions`
Note that with code-insiders with or without extensions enabled, it works as expected (without previewing) because code-insiders doesn't import my extensions and settings ;-)

I finally found the culprit it was this setting in settings.json
`    "workbench.editorAssociations": [
        {
            "viewType": "vscode.markdown.preview.editor",
            "filenamePattern": "*.md"
        }
    ],
`

thanks for your answer , I close this ticket
