### ISSUE TITLE
ssh port forward is not working

### ISSUE THREAD

**Issue by kasanitej** [microsoft/vscode#113763]
- VSCode Version: 1.52.1
- OS Version: Windows 20H2

Steps to Reproduce:
1. I have created a service in minikube (azure vm), the service is available at 192.168.99.100:31606 (in azure vm)
2. when port forward : remote explorer> ports > "forward a port" .. give "192.168.99.100:31606"

 when I manually did it in the cmd with command  `ssh -L 31606:192.168.99.100:31606 azureuser@<azureip>` it is working.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by kasanitej** [comment]
No error, but my browser is not showing anything when I try to access 127.0.0.1:31606 in my local machine.
I think instead of mapping (vm)192.168.99.100:31606-> (local)127.0.0.1:31606
it is mapping (remote)127.0.0.1:31606->(local)127.0.0.1:31606.

**Note:** manualling tunneling via `ssh -L 31606:192.168.99.100:31606 azureuser@<azureip>` is working, which indicates that my minikube service is working fine.

**Comment by alexr00** [comment]
Ah, thanks for the clarification. The Ports view for SSH only supports 0.0.0.0 and localhost (or 127.0.0.1) as possible hosts for the remote.

**Comment by alexr00** [comment]
@roblourens if SSH wants to support other hosts, then the SSH extension could implement a tunnel provider.

**Comment by kasanitej** [comment]
can this ticket be used as a feature enhancement, instead of closing it?

**Comment by roblourens** [comment]
You can add them to your SSH config to have SSH do the forwarding

**Comment by kasanitej** [comment]
but these are temporary ports
