### ISSUE TITLE
Do not suggest Golden Dracula theme extension for Go projects with .golden files

### ISSUE THREAD

**Issue by slimsag** [microsoft/vscode#113731]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Open [any Go project](https://github.com/hexops/valast/) which has `.golden` files in its `testdata/` directories
2. VS Code suggest that there are extensions to help with `.golden` files, suggests installing the Golden Dracula theme extension (`ext:golden`)
3. That extension does not help with Go golden files

Possible ways to improve this:

* If the `.golden` file is in a directory named `testdata/` then do not suggest the extension.
* If there is a `go.mod` file in the parent directories, then do not suggest the extension.

`.golden` files are pretty common in the Go community: they are used by the Go authors for testing [the standard library](https://golang.org/src/go/doc/doc_test.go), the [`gofmt` tool](https://github.com/golang/go/blob/master/src/cmd/gofmt/gofmt_test.go#L124-L130), etc. and are [a common pattern](https://medium.com/soon-london/testing-with-golden-files-in-go-7fccc71c43d3) in the Go community for snapshot testing outside the official Go project.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It is unfortunate that golden theme has a tag name `golden` and hence this is being shown. Not sure if there is anything we can do here 😞
