### ISSUE TITLE
Writing login information to the keychain failed with error wrong ELF class

### ISSUE THREAD

**Issue by OofChair** [microsoft/vscode#113707]
Issue Type: <b>Bug</b>

1: Open a new VS window (and previously be logged in with GitHub)
2: Click on account icon
3: It says "You are not signed into any accounts" even though I was

One quick thing, I have a GitHub repo that I can push/pull from. Not sure if that will help

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:31:12.802Z)
OS version: Linux arm64 5.8.0-1010-raspi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (4 x 1500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|3.65GB (0.07GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 573edcf6-1f0d-4970-a672-255463f2d61a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.6
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.0
prettier-vscode|esb|5.8.0
vscode-pull-request-github|Git|0.22.0
vscode-github|Kni|0.30.4
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
cpptools|ms-|1.1.3
java|red|0.73.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt859:30239450
vsjup459:30237187

```

</details>

**Comment by RMacfarlane** [comment]
Can you open the output panel and select "GitHub Account" from the dropdown and copy any text from there?

**Comment by FionnLive** [comment]
Where is the output panel?

**Comment by RMacfarlane** [comment]
It's at the bottom by the terminal, you can open it by running the command `Output: Focus On Output View`
<img width="899" alt="Screen Shot 2021-01-04 at 9 25 25 AM" src="https://user-images.githubusercontent.com/3672607/103561801-edec7d80-4e6e-11eb-9dbc-9ba1f7b623bb.png">

**Comment by OofChair** [comment]
Hmm I don't see anything in there, but I think this might be the cause of the problem:
Whenever I sign in with GitHub, I get this error that pops up:

Writing login information to the keychain failed with error '/usr/share/code/resources/app/node_modules.asar.unpacked/keytar/build/Release/keytar.node: wrong ELF class: ELFCLASS32'.

**Comment by TylerLeonhardt** [comment]
Hi @OofChair  👋

I recently gained ownership of the GitHub auth feature and so I'm getting ramped up!

It's been few versions now... Can you confirm if you're still seeing this issue?

Thanks!
