### ISSUE TITLE
Create method to convert document Character Index to Position and the other way around as weel

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#113780]
I have a bunch of Regex Matches that I would like to substitute for something. With regex match I can get start and end indexes to know where the match is in the text, but I can't natively convert it to a Position object. I would like to have a method to convert this index to a Position. This way I can use document.set(range), where range is start and end Position instances that were retrieved given the character index position that I got from a regex match.

Or you can give us a method that makes substitution given start and end char indexes, which would make everything easier. Example:

`document.set(134, 240, 'My new Text')`

**Comment by AllanOricil** [comment]
After a few lines of code I was able to convert char index to Position. But it would be good to have it in the API natively. What do you think?

**Comment by jrieken** [comment]
Did you try/see [`vscode.TextDocument.positionAt`](https://github.com/microsoft/vscode/blob/b6c601b4fc80733465ba52198a0c672d3527927a/src/vs/vscode.d.ts#L195)?

**Comment by AllanOricil** [comment]
> Did you try/see [`vscode.TextDocument.positionAt`](https://github.com/microsoft/vscode/blob/b6c601b4fc80733465ba52198a0c672d3527927a/src/vs/vscode.d.ts#L195)?

That method is exactly what I needed haha. Thank you @jrieken
