### ISSUE TITLE
request to get access to "oneLineAboveText" property in "vscode.onEnterRules"

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#113782]
C/C++ extension need to get access to "oneLineAboveText" property in "vscode.onEnterRules" to fix this bug: https://github.com/microsoft/vscode-cpptools/issues/5733 .

I can see this property is being used here: https://github.com/microsoft/vscode/blob/e5ceb315da2462b0fea70716e79cc82ce708b438/extensions/typescript-language-features/src/features/languageConfiguration.ts#L21

but it is missing from the vscode extension API:
https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4677

**Comment by alexdima** [comment]
Let's track in #58440
