### ISSUE TITLE
Release Notes Reactions

### ISSUE THREAD

**Issue by jpenna** [microsoft/vscode#113764]
Not sure if this should be here.

Reading this latest Release Notes, **some of the new features stood out for me and I wish I could react to them** with 👍  or 🥳 . 

Besides turning the release notes more interactive (and fun), it would give the development team feedback on what features are more important to the community and which are hated (with 👎  maybe).

**Comment by mjbvz** [comment]
Closing since I don't foresee us investing in this anytime soon

If you have any feedback, please let us know on Github (you can also tweet at us)
