### ISSUE TITLE
The explorer becomes unreadable du to multi colours flickering all over the component

### ISSUE THREAD

**Issue by larsoleruben** [microsoft/vscode#113721]
- VSCode Version: 1.52.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Leave code running for a while.
2. Some times it takes weeks, others days

Does this issue occur when all extensions are disabled?: Yes/No No

**Comment by larsoleruben** [comment]
![Screenshot 2021-01-03 at 08 20 57](https://user-images.githubusercontent.com/2634802/103474685-aa2e4100-4da6-11eb-8872-937ea30c7b95.png)

**Comment by rzhao271** [comment]
I wonder if launching vscode with the `--disable-gpu` flag could help for now?
