### ISSUE TITLE
Bracket Pair Matching

### ISSUE THREAD

**Issue by mahi-man** [microsoft/vscode#113795]
Issue Type: <b>Feature Request</b>

The bracket pair highlighter in VSCode is quite large than compared to that of Sublime Text which makes a conjusted code look more conjusted. So instead of highlighting the whole bracket pair, underlining the bracket pair would work fine. I request you to please peruse the matter. Thank you VSCode for being a beautiful editor :)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by alexdima** [comment]
Let's track in #19534
