### ISSUE TITLE
"code ." at the CLI should return to the prompt, not show log info

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode#113772]
Issue Type: <b>Bug</b>

It's quite unexpected that typing "code ." at the CLI in a project folder shows output from VS Code and then waits rather than returning to the prompt to accept another command.

What's even stranger is that I can go ahead and type another command (e.g. dir) and it will show the directory contents and display the prompt, but if I check for updates in VS Code it will log the following output to the CLI:
"
[main 2021-01-04T17:42:22.926Z] update#setState checking for updates
[main 2021-01-04T17:42:23.073Z] update#setState idle
"

What I would expect is to have the prompt return immediately after typing "code ." and see no logged output from VS Code in the CLI.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (6.27GB free)|
|Process Argv|. --crash-reporter-id 036d74de-35dc-4313-ba1e-6f6db72790d7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-sidebar|Acr|1.1.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.10
docs-build|doc|0.2.4
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.82
docs-metadata|doc|1.0.5
docs-preview|doc|0.3.56
docs-yaml|doc|0.2.6
python-preview|don|0.0.4
es7-react-js-snippets|dsz|3.1.0
prettier-vscode|esb|5.8.0
vscode-env|Iro|0.1.0
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.1.0
vscode-azurestorage|ms-|0.11.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
powershell|ms-|2020.6.0
vscode-react-native|msj|1.2.0
env-cmd-file-syntax|Nix|0.2.2
vscode-yaml|red|0.13.0
jinjahtml|sam|0.15.0
code-spell-checker|str|1.10.2
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt600:30239448

```

</details>

**Comment by bpasero** [comment]
Sounds to me as if `code` is bound to start the exe, not our script.

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable?

**Comment by charris-msft** [comment]
I thought I had included my path previously, but must have not actually sent it. Here is my path:

C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
C:\Python39\Scripts\
C:\Python39\
C:\windows\system32
C:\windows
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0\
C:\windows\System32\OpenSSH\
C:\Program Files\Microsoft VS Code\bin
C:\Users\charris\AppData\Local\Microsoft\WindowsApps
c:\tools\scripts
c:\tools\localbin
C:\Program Files\PowerShell\7\
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
C:\Program Files\dotnet\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\Git\cmd
C:\Program Files\nodejs\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Program Files (x86)\dotnet\
C:\Users\charris\AppData\Local\Programs\Fiddler
C:\Program Files (x86)\GitHub CLI\
C:\Users\charris\AppData\Roaming\npm
C:\Users\charris\AppData\Local\GitHubDesktop\bin
C:\Users\charris\.dotnet\tools
C:\Users\charris\AppData\Local\Programs\Microsoft VS Code\
C:\Users\charris\AppData\Local\Programs\Azure Data Studio\bin

**Comment by joaomoreno** [comment]
It's strange that `C:\Users\charris\AppData\Local\Programs\Microsoft VS Code`, the right value should be `C:\Users\charris\AppData\Local\Programs\Microsoft VS Code\bin`. Once you change that, the issue will be fixed.

**Comment by charris-msft** [comment]
Correcting that path value did fix the issue. I'll keep an eye on it and see if I can identify anything that may have caused it to be set w/o the /bin folder.
Thanks!
