### ISSUE TITLE
don't expand node_modules directory when finding a definition inside node_modules.

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#113797]
Issue Type: <b>Feature Request</b>

don't expand node_modules directory when goto definition or zip node_modules directory when it's files are all closed.

currently whenever go to a definition inside node_modules will cause node_modules directory to expand, and it is very annoying.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.15.0-128-generic

**Comment by mjbvz** [comment]
@isidorn Assigning you since I believe this issues is about VS Code's explorer.

I don't think we want to have a JavaScript/TypeScript specific solution here, but maybe we could add an option to disable auto-reveal if the file is in a hidden or excluded directory?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/87956
