### ISSUE TITLE
"Select for Compare" is available for WebView tabs

### ISSUE THREAD

**Issue by m417z** [microsoft/vscode#113703]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a WebView tab, such as the Markdown preview.
2. Right click on it in the Open Editors Section, and select "Select for Compare".
3. Right click on any other item and select "Compare with Selected".

![yvwR4diJAw](https://user-images.githubusercontent.com/4129781/103464599-bb8f3300-4d3d-11eb-8376-e725380e2ba0.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
//cc @mjbvz not sure we have a context key to use here already

**Comment by isidorn** [comment]
Code pointer https://github.com/microsoft/vscode/blob/ea51fb1bddfe097ad6539b68571cdb16ed677250/src/vs/workbench/contrib/files/browser/fileActions.contribution.ts#L310

We would need to use that context key for all the compare context menu actions in the Open Editors view

**Comment by bpasero** [comment]
@isidorn isn't this just a matter of using `ResourceContextKey.IsFileSystemResource` for this command? We seem to be using this also to limit commands such as "Copy"?

**Comment by isidorn** [comment]
@bpasero you are correct, I checked and this is indeed the context key we needed here.

**Comment by bpasero** [comment]
👏

**Comment by isidorn** [comment]
Will have to revert this due to https://github.com/microsoft/vscode/issues/115580

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/115665
