### ISSUE TITLE
about ipc disconnect

### ISSUE THREAD

**Issue by spcBackToLife** [microsoft/vscode#113888]
in ipc connection, when you disconnect, will fire this event listener
```
const onDidClientDisconnect = Event.any(
        Event.signal(createScopedOnMessageEvent(id, 'vscode:disconnect')),
        onDidClientReconnect.event,
      );
```
but you will find, if there is a same  id, to disconnect and reconnect, and then keep disconnect, onDidClientDisconnect will be triggered  a lot of times.

so here I think need  to use `Event.once`

```
const onDidClientDisconnect = Event.once(Event.any(
        Event.signal(createScopedOnMessageEvent(id, 'vscode:disconnect'),
        onDidClientReconnect.event,
      )));
```

**Comment by joaomoreno** [comment]
@spcBackToLife Did you see a bug in the product related to this?

**Comment by spcBackToLife** [comment]
> @spcBackToLife Did you see a bug in the product related to this?

I have develop a framework of electron, refer from vscode, I have a sence like this:

I need to connect ipc in webview preloadjs, and then when I refresh page, I need to do is :

disconnect webview ipc connection,
reconnect webview ipc connection

when i refresh a lot of times ,"disconnect" will be done many times.

**Comment by spcBackToLife** [comment]
> @spcBackToLife Did you see a bug in the product related to this?

not from vscode production, just read the vscode source , and i think here should use 'once', I am also curious about why not use once

**Comment by spcBackToLife** [comment]
> @spcBackToLife Did you see a bug in the product related to this?

here is source code of vscode
![image](https://user-images.githubusercontent.com/20703494/103881892-06ca8c80-5116-11eb-97ea-c917c1864e86.png)
so when I have refresh page action, it must run more then once of this 'onDidClientDisconnect'.

so, I think here should be like this:
![image](https://user-images.githubusercontent.com/20703494/103882020-31b4e080-5116-11eb-966a-dd0661fe8658.png)

**Comment by joaomoreno** [comment]
We don't use `once` because as soon as it happens, the entire machinery gets disposed.

Let me know if you eventually find a bug in the product related to this. Until then, let's leave the code since it obviously works just fine.
