### ISSUE TITLE
When 'shrink' is the Tab Sizing selected, there should be a delay before the tab shrinks

### ISSUE THREAD

**Issue by tyirvine** [microsoft/vscode#113860]
Shrinking the tab was inspired by web browsers such as Google Chrome or Safari. What makes shrinking a tab so great is that it's easy to delete 10 tabs at once. This is because there is a slight (maybe 250ms) delay before the browser resizes the tab.

Right now, VS Code is shrinking the tabs the moment a tab is deleted. So if the number of tabs (sized at the minimum) exceeds the width of your editor window, great! You won't have this issue. Otherwise, as soon as the number of tabs (sized at the minimum) is less than your editor window's width then you have a problem → every tab you delete will cause the entire tab collection to resize instantly.

I ran into this problem when browsing extensions. I somehow managed to open up ~50 tabs. I've never worked on the VS Code application itself but I'd be happy to do this! It seems like a pretty easy fix but I don't have any familiarity with this code base.

If this is a duplicate I apologize! I couldn't any similar issues. 

![Screen Recording 2021-01-05 at 3 26 52 PM](https://user-images.githubusercontent.com/39813066/103706903-df838c00-4f6a-11eb-8eab-592e9577ca8c.gif)

**Comment by bpasero** [comment]
This issue has been reported already in either this or a similar form. Please check the label that was assigned to this issue to find it.

**Comment by tyirvine** [comment]
Duplicate of #40290
