### ISSUE TITLE
with rust-analyzer extension enabled, rust code can not do folding

### ISSUE THREAD

**Issue by E834159672** [microsoft/vscode#113879]
- VSCode Version:1.52.1
- OS Version:fedora 33 kernel 5.10.4

Steps to Reproduce:

1. create new file name main.rs
2. open it with code 
3. write code like this :
```
// #region mytest

fn test(){

}

// #endregion

```
4. it can not  fold the mytest region.

Does this issue occur when all extensions are disabled?: Yes/No
No. but when enable rust-analyzer extension ,it occur.

**Comment by E834159672** [comment]
same issue in the rust-analyzer repo : [issue link](https://github.com/rust-analyzer/rust-analyzer/issues/7175)

**Comment by aeschli** [comment]
The rust analyzer adds a folding provider that is not aware of the region markers. It needs to be fixed in the extension.
