### ISSUE TITLE
fetch wrong argument if comma existing in java main argument 

### ISSUE THREAD

**Issue by woderchen** [microsoft/vscode#113868]
Issue Type: <b>Bug</b>

1. this is java project
2. input args param in lanuch.json. 
example: 
{
            "type": "java",
            "name": "light-core-generator",
            "request": "launch",
            "mainClass": "daq.light.core.Generator",
            "projectName": "light-job-core",
            "vmArgs": "-Ddaq.job.forbid-period=22:00~21:00 ",
            "args": "-sSortPkColumn \"{deptdict:'dept_code' , staffdict:'dept_code'}\" -sSortPkColumnType char  -sSqlMethod pk"}

3. run main and check those argument with debug mode
i want to fetch argument according to  args[++i]) in  main(String[] args), but the string "{deptdict:'dept_code' , staffdict:'dept_code'}" will be divided into two argument as comma existing.   
i try to debug with other IDE, no this issue.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 6|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 787f0589-22df-49ba-bd6c-3e3f8a818c32|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-django|bat|1.0.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-lombok|Gab|1.0.1
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
vetur|oct|0.31.3
java|red|0.73.0
vscode-xml|red|0.14.0
vscode-counter|uct|2.2.1
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.26.1
vscode-maven|vsc|0.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt600:30241727
vsjup459:30237187

```

</details>

**Comment by weinand** [comment]
@woderchen what exactly are the arguments that you want to pass to the Java program?
Please list the command line as you would use it in a regular shell.
