### ISSUE TITLE
Apple SI: chokidar does not seem to be working

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113883]
Steps to Reproduce:

1. be on Apple SI
2. open a folder
3. notice in devtools:
4. 
`WARN [File Watcher (chokidar)] Watcher is not using native fsevents library and is falling back to unefficient polling.`

**Comment by bpasero** [comment]
Related failing unit test:

```
2) Native Modules (macOS)
       chokidar (fsevents):

      AssertionError [ERR_ASSERTION]: Unable to load "chokidar (fsevents)" dependency. It was probably not compiled for the right operating system architecture or had missing build tools.
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (file:///Users/bpasero/Development/Microsoft/monaco/out/vs/platform/environment/test/node/nativeModules.test.js:49:20)
```

**Comment by deepak1556** [comment]
Chokidar v3.5.0 was just released that takes in fsevents universal build https://github.com/fsevents/fsevents/pull/350 , we can update to it.

**Comment by paulmillr** [comment]
yep this required compiling fsevents as universal binary
