### ISSUE TITLE
Build issue: vscode compile from source fails on Mac11.1

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode#113894]
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0

Steps to Reproduce:
1. git clone git@github.com:microsoft/vscode.git
2. cd vscode
3. yarn

Does this issue occur when all extensions are disabled?: Yes

**Error seen:**
[3/4] 🔗  Linking dependencies...
warning " > eslint-plugin-mocha@8.0.0" has incorrect peer dependency "eslint@>=7.0.0".
warning "gulp-atom-electron > @octokit/rest > @octokit/plugin-request-log@1.0.2" has incorrect peer dependency "@octokit/core@>=3".
warning " > gulp-tsb@4.0.5" has incorrect peer dependency "typescript@^3.0.0".
[4/4] 🔨  Building fresh packages...
[6/17] ⢀ spdlog
[7/17] ⢀ vscode-nsfw
[13/17] ⢀ electron
[9/17] ⢀ vscode-sqlite3
**error** /Users/swinder/code/vscode/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/swinder/code/vscode/node_modules/playwright
Output:
/Users/swinder/code/vscode/node_modules/playwright/lib/utils/utils.js:58
        throw new Error(message);
              ^

**Error**: ERROR: Playwright does not support chromium on mac11.1
    at Object.assert (/Users/swinder/code/vscode/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/Users/swinder/code/vscode/node_modules/playwright/lib/install/browserFetcher.js:131:13)

**Comment by bpasero** [comment]
I am on that macOS version and it works fine for me.

**Comment by swinder0161** [comment]
@bpasero  but is there something I can do here? I run the command as mentioned on vscode build page on github.
cd vscode
yarn

I get this error. Need help to solve it

**Comment by bpasero** [comment]
We have instructions at https://github.com/microsoft/vscode/wiki/How-to-Contribute but we are not giving support  through issues. The comment in https://github.com/microsoft/vscode/issues/113894#issuecomment-755186369 might also be helpful or our StackOverflow community for VSCode: https://stackoverflow.com/questions/tagged/visual-studio-code?tab=Newest

**Comment by swinder0161** [comment]
https://github.com/swinder0161/vscode/commit/fa15b67a0c85a4303f9ec62bdc229b7c2c22cdf6

This can fix it

**Comment by bpasero** [comment]
Feel free to open a Pull Request for us to look at, thanks.

**Comment by bpasero** [comment]
Thanks.
