### ISSUE TITLE
Spelling error in description of workbench.editor.wrapTabs

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#113806]
Issue Type: <b>Bug</b>

Second occurrence of the word 'whether' is incorrectly spelled 'wether'

![image](https://user-images.githubusercontent.com/6726799/103627780-fcea3300-4f35-11eb-8da4-b3f170cf0bff.png)

VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:23:04.938Z)
OS version: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/c4ea0b55906a3ebdedc39f4e921a109181e016d5
