### ISSUE TITLE
Context menu is clipped in the commit message box of Source Control panel.

### ISSUE THREAD

**Issue by infinnie** [microsoft/vscode#113866]
- VSCode Version: 1.52.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a folder with a Git repository.
2. Switch to the Source Control panel and right click on the commit message box.

Does this issue occur when all extensions are disabled?: Yes

Screenshot:
![image](https://user-images.githubusercontent.com/8168391/103716640-89602880-4ffe-11eb-9efd-f921c92efd2f.png)

**Comment by infinnie** [comment]
Maybe related to: #102401

The commit message editor’s context menu is placed within the `.monaco-editor` element, but the `.monaco-list-rows` element it is contained within is wrapped within a `ScrollableElement`, which would make the element receive an `overflow: hidden` style.

![image](https://user-images.githubusercontent.com/8168391/103720523-7d786480-5006-11eb-8cf4-4f2866f26445.png)

**Comment by eamodio** [comment]
@infinnie thank you so much -- awesome investigation!

**Comment by infinnie** [comment]
> @infinnie thank you so much -- awesome investigation!

Maybe a comment should be left to explain why transform optimization should not be applied here, or it is possible that it might get confusing sometime later.

**Comment by eamodio** [comment]
The commit is linked to this issue, so it should provide the context.
