### ISSUE TITLE
mask spaces in the search view result in the side bar

### ISSUE THREAD

**Issue by david85fr** [microsoft/vscode#113838]
the search result delete heading and trailing spaces in the result view.
But it could be good to also mask multi(or all) spaces between words.

'_' as space caracter
`
{E_func1_____________________,___e1,__________________________________1},
{E_func2_____________________,___e2,__________________________________2},
{E_func11____________________,___e11,_________________________________11},
{E_lastLongfunc12____________,___E_lastLongfunc12,____________________12},
`

when I search "e2", vscode show:
`{E_func2_____________,___e2,__________________________2},`

It could be good to show only:
`{E_func2 , e2, 2},`

**Comment by roblourens** [comment]
I don't want to modify the actual text within what we display. But using a search editor might make this easier for you
