### ISSUE TITLE
Tab wrap - provide a way to toggle wrapping via keybinding

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#113802]
Great to have a shortcut to dis/enable TabsWrap
![image](https://user-images.githubusercontent.com/1876302/103617992-27ee7a00-4f6a-11eb-92ce-d6fef76f2a9b.png)

**Comment by bpasero** [comment]
I am not sure it should be in the menu, but having a command to toggle is fine I guess.

**Comment by gjsjohnmurray** [comment]
How about making a vertical drag gesture on the bottom edge of the tabs section toggle this? Drag down on the bottom edge of a scrolling tabs section to enable wrap. Drag up on the bottom edge of a wrapping tabs section to disable wrap.

**Comment by heartacker** [comment]
> How about making a vertical drag gesture on the bottom edge of the tabs section toggle this? Drag down on the bottom edge of a scrolling tabs section to enable wrap. Drag up on the bottom edge of a wrapping tabs section to disable wrap.

for me is ok,but that is unconspicuous for so many users,just like panel(panel can also drag out from button status bar)
