### ISSUE TITLE
Exporer / Workspace file rows reset every ~5s, can't rename files

### ISSUE THREAD

**Issue by siverv** [microsoft/vscode#113821]
Issue Type: <b>Bug</b>

The rows of the file explorer reset every ~5s, making it problematic to rename files. When renaming files, the reset causes the edit-mode to end prematurely.

By using "Toggle Developer Tools", then "Inspect Element" (ctrl-shift-c) on one of the explorer rows, one can observe that every `.monaco-list-row` element resets every 5s or so, and this coincides with the end of edit-mode when renaming. The reset is independent of the renaming edit-mote itself, and seems to always be active.

Just before the `.monaco-list-row` elements are updated, the `.monaco-progress-container` replaces the `.done` class with `.active.infinite` and back.

Neither restart of VSC nor the computer itself have resolved the issue.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.15.0-128-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2699)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|23.38GB (3.84GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 2775da45-7b4c-40b7-b367-68eda283fa8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.1.3
flow-for-vscode|flo|1.5.0
jq-syntax-highlighting|jq-|0.0.2
gnuplot|mam|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
vstry244:30236573
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30239448
vsjup459cf:30237188

```

</details>

**Comment by isidorn** [comment]
This is fixed in latest vscode insiders
