### ISSUE TITLE
Inline action for "edit condition" action in Breakpoints view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#113805]
As @bpasero suggested we could use an inline action for the "Edit Condition" action in the breakpoints view.
This inline action would appear on hover for exception breakpoints, function breakpoints, data breakpoints.

Currently we only allow to edit conitions once debugging is started and we know what debug adapter we are using. And we only show these actions if the debug adapter supports the corresponding capabilites. We might also want to consider to show this actions also when not debugging.

fyi @connor4312 @weinand 
@misolori for icon ideas

**Comment by weinand** [comment]
Yes, enabling to edit the condition outside of a debug session would be helpful because it makes the this feature more discoverable. In addition it better aligns exception breakpoints with source breakpoints which already support 7/24 condition editing.

And using inline actions is another thing to try (but only after implementing the 7/24 condition editing).

**Comment by isidorn** [comment]
Makes sense, let me assign to Jaunary to investigate more into this.

**Comment by misolori** [comment]
For icon, i'd suggest using our standard `edit` icon:

![image](https://user-images.githubusercontent.com/35271042/103959161-ce21b780-5103-11eb-9574-8fce4f7f9f59.png)

**Comment by isidorn** [comment]
@misolori makes good sense, thanks!

**Comment by isidorn** [comment]
I just verified that we actually already have 24/7 condition editing, seems like I was thinking about when coding this up before Christmas break 👏 
It just took me some time to figure out that I need the js-debug-nightly for the condition editing. @connor4312 do we plan to release this in the js-debug regular release?

Since we have the 24/7 condition editing, I will now look to add the inline action using the Icon Miguel proposed.

**Comment by weinand** [comment]
@isidorn yes, Mock Debug has 24/7 condition editing.

**Comment by isidorn** [comment]
Here's how this looks in practice. I will render this inline action for all breakpoints since all breakpoints support conditions now.

![Screenshot 2021-01-13 at 16 49 50](https://user-images.githubusercontent.com/1926584/104475427-61a12f80-55bf-11eb-878b-7893461e5f9c.png)

**Comment by yannickowow** [comment]
Hi,
I don't know if you were facing it yet, but, when debugging, I cannot use `Edit Hit Count` or `Edit Condition` from actions menu, but I can use pencil icon to edit condition. 
When not debugging, it seems to work fine and usage is intuitive. 
My debugger supports `conditionalBreakpoints`, `hitConditionalBreakpoints` and `functionBreakpoints`
See:
![image](https://user-images.githubusercontent.com/45362067/104710136-05a1ec80-5720-11eb-829d-7ed50bf21a31.png)
![image](https://user-images.githubusercontent.com/45362067/104710189-15b9cc00-5720-11eb-83ad-69007e348359.png)
![image](https://user-images.githubusercontent.com/45362067/104710234-25d1ab80-5720-11eb-8af2-e57dba411ebb.png)

Regards.

**Comment by isidorn** [comment]
@yannickowow thanks a lot for trying it out and for providing feedback. I have just pushed a fix for this issue which you found. Thanks!

**Comment by yannickowow** [comment]
Hi
I did found a bug associated to "Edit Condition" for DataBreakpoints. It did shows "Edit Condition" action but it does not open "Edit" view. Edit icon is not displayed as well.
It works fine actually with FunctionBreakpoints.

Thanks!

**Comment by yannickowow** [comment]
Thanks.
Since DataBreakpoints implementation in DebugAdapterProtocol supports the same arguments (ie `Hit Count` and `Condition`), it would be great if VS Code can show an unified attribute for this.
