### ISSUE TITLE
Creating a terminal and sending text to it should not show it

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11384]
Creating a new terminal immediately shows it which 

* gives me no way to create a terminal in background
* is different from `createOutputChannel` or `createStatusBarItem`

**Comment by jrieken** [comment]
Pushing for August since no one has yet programmed against the API and changes after that won't be possible

**Comment by Tyriar** [comment]
This is actually a non-trivial change and is related to #11275. A `createInBackground?: boolean` property can be added to `vscode.TerminalConfiguration` to keep this backwards compatible.

**Comment by Tyriar** [comment]
Are you suggesting this should create in background by default? Seems to me that the majority of use cases would want it in the foreground?

**Comment by jrieken** [comment]
> Are you suggesting this should create in background by default?

For the sake of being consistent with other API (`createOutputChannel`, `createStatusBarItem`) "yes". Also it won't require the proposed `createInBackground`-flag thus keeping it more simple.

**Comment by jrieken** [comment]
@Tyriar I would suggest for *August* to internally call `hide` after creation. That would align the behaviour, be an easy fix, and the flickering would be along the lines of #11275

**Comment by jrieken** [comment]
Alternatively we release-note this behaviour for August - the API is correct but wrongly implemented. That would mean consumers for 1.5 have to be prepared for a behavioural change with 1.6

**Comment by Tyriar** [comment]
@jrieken while calling `hide` immediately works for `createTerminal`, it does not for `sendText` which also forces the display of the terminal. Changing the latter is a more high risk change, I'm going to make a note in `vscode.d.ts` indicating that it will be changed as the release notes defer to the docs.

To clarify, my original design for this was all extension interaction with vscode should be visible to the user.

**Comment by Tyriar** [comment]
Set the PR to August, moving this to September for the real fix.

**Comment by Tyriar** [comment]
This was done via #11839 and subsequent fixes with one caveat; if the terminal panel is not initialized, the output will not be retained. So the process will run fine, just output will not be kept until `Terminal.show` is invoked at least once. The upstream issue tracking this is https://github.com/sourcelair/xterm.js/issues/266

**Comment by jrieken** [comment]
@Tyriar We still have the doc comments about changes in 1.6 in vscode.d.ts

**Comment by Tyriar** [comment]
Done, I just removed it and didn't elaborate on it not showing the terminal as that's consistent with `createOutputChannel`.
