### ISSUE TITLE
Error opening vscode as git editor with rebase

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#113873]
### I think I'm getting the same issue on Windows 10
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
git version 2.29.2.windows.3
```

### Reproduce
Using the [repository I created](https://github.com/subz390/wait-bug) for testing;
1. Checkout `development` branch
2. Rebase with `main`
2. Resolve conflicts, accept incoming changes
3. Save conflict file
4. Stage
5. Commit - expect VSCode to continue with the commit, instead I get the following error; `Code.exe: bad option: --wait`

![201227-022158 VSCode error box](https://user-images.githubusercontent.com/11546815/103163369-2815a980-47f5-11eb-838c-930cc5b6a68a.png)

### Video

Here's a [video I made reproducing the error](https://youtu.be/m5PVz4Il18s)

### Git log
Here's the log from the moment where it generates the error.
```
> git rebase --continue
C:\Users\Z390\AppData\Local\Programs\Microsoft VS Code\Code.exe: bad option: --wait
error: There was a problem with the editor 'Code.exe --wait'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
```

Check: I disabled/uninstalled all VSCode Git extensions.

_Originally posted by @subz390 in https://github.com/microsoft/vscode/issues/113302#issuecomment-751422381_

**Comment by eamodio** [comment]
_Originally posted by @subz390 in https://github.com/microsoft/vscode/issues/113302#issuecomment-755014602_

> @eamodio thanks for looking into the issue. I came to the same conclusion as you and so meticulously went through Google for answers, all of which suggested the same thing. When I exhausted all those possible solutions, I searched all the issues in this repo and only found this issue.
> 
> So to summarise:
> 
> * core editor is set to `core.editor=Code.exe --wait` what should it be set to?  because this is what it was originally set to and what everyone on Google said it should be set to.
> * I tried setting it with the full path to `Code.exe`, however `Code.exe` is in PATH so I've left it like this.  Changing it from full path to this made no difference.
> * May I confirm you watched the video I posted all the way through?  Why does this only happen with rebasing and not merging?  Surely if there was a problem with `core.editor` merging would also fail?
> * And can you confirm that I'm performing the correct actions in the right order?
> * Finally, as you feel this is a separate issue should I open a new issue or are we good to continue discussing here?  Either way I would sincerely like to get to the bottom of this.

**Comment by eamodio** [comment]
@subz390
Hrm, this one is confusing. I hadn't watched the video, but have now -- and everything looks fine (except for the error of course). Do you have possibly have `sequence.editor` set in your git config? As that will override `core.editor` for rebases. 

For the hell of it, I'd try just setting `core.editor` to `code --wait` to see if that makes any difference.

If none of that fixes anything -- do you have any special settings? Could you post your settings.json (ensuring there isn't any sensative info in there)?

**Comment by subz390** [comment]
@eamodio ok leave it with me, I'll try what you suggest and report back with a list of settings.

**Comment by subz390** [comment]
@eamodio I think `git config --global core.editor "code --wait"` has done the trick.
Is this what it should do, opening the interactive commit message?
Either way the error message is gone and closing the commit message confirmation proceeds with the rebase.
![210106-075704 commit editmessage](https://user-images.githubusercontent.com/11546815/103744009-ece55880-4ff4-11eb-84cf-d2dea955b90f.png)

**Comment by eamodio** [comment]
Yup, that looks like the correct behavior.
Odd that the `.exe` part caused an issue, but good to know. And glad it's resolved for you.

**Comment by subz390** [comment]
If I ever find out I'll return to let you know.  Thanks for tracking the issue, peace out...
