### ISSUE TITLE
Minimap spazzes

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#113877]
Issue Type: <b>Bug</b>

The minimap spazzes out and the file scrolls spastically, with zero user interaction. The affected file is [this one](https://gitlab.com/gitlab-org/gitlab/blob/2779d69bc1e4103f6fde8d3a9da25fbc3089df05/doc/development/database_review.md). You can see the effect in this video, where the only action I take is to click on the search result to open the file:

https://user-images.githubusercontent.com/879055/103735198-272e0600-4fb3-11eb-85da-21486ca20738.mov

In `~/Library/Application Support/Code/storage.json`, here's the UI state for the affected workspace:

```
{
    "windowsState": {
        "lastActiveWindow": {
            "uiState": {
                "mode": 3,
                "display": 2077750265,
                "width": 1024,
                "height": 768,
                "x": 358,
                "y": 171
            }
        }
}
```

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 10, 17|
|Memory (System)|16.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id b66d31ed-6df8-483a-9367-cc739cc188f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.0
quitcontrol-vscode|art|3.1.3
markdown-mermaid|bie|1.9.0
rails|bun|0.16.7
vscode-gemfile|bun|0.4.0
better-toml|bun|0.3.2
solargraph|cas|0.21.1
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.1.3
permute-lines|ear|1.1.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
vscode-byebug|eth|0.1.2
vscode-go-test-adapter|eth|0.1.5
vscode-firefox-debug|fir|2.9.1
gitlab-workflow|Git|3.8.0
go|gol|0.20.1
vscode-graphql|Gra|0.3.13
vscode-test-explorer|hbe|2.19.3
docomment|k--|0.1.20
template-string-converter|meg|0.4.5
ruby-rubocop|mis|0.8.5
csharp|ms-|1.23.8
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
vsliveshare|ms-|1.0.3375
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
material-icon-theme|PKi|4.4.0
ruby|reb|0.28.0
slim|sia|0.1.2
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
haml|vay|1.0.1
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt859:30241729
vsjup459:30237187

```

</details>

**Comment by Nxt3** [comment]
Yes! I'm having the same issue. It happens a lot for me when using split-editors.

![spazzy_minimap](https://user-images.githubusercontent.com/2940826/114960667-81055e00-9e35-11eb-9e81-1d429c7f65fc.gif)


[Here is the text file in question.](https://gist.github.com/Nxt3/e9a845c70a1690471d414210a9bc5712)

My minimap settings:

```json
  "editor.minimap.maxColumn": 80,
  "editor.minimap.renderCharacters": false,
  "editor.minimap.showSlider": "always",
  "editor.minimap.size": "fill"
  ```
