### ISSUE TITLE
Outline should allow to distinguish public/private properties

### ISSUE THREAD

**Issue by NicBright** [microsoft/vscode#113884]
First of all, this feature request has already been posted previously: #61239

Unfortunately it has been closed with pointing to other issues (recursively) that increasingly went into more details about vscode internals that seem to have been closed as well. In the end, nothing has changed from the end user perspective as of now (January 2021): it is still not possible to distinguish public/private properties in the outline (which, for me, is the only use case to use the outline in the first place). See this screenshot for example:

![image](https://user-images.githubusercontent.com/1225659/103741223-fb357380-4ff8-11eb-9abc-1a7ecb212144.png)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"outline"
