### ISSUE TITLE
Isolate node code cache on apple silicon

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#113852]
Steps to repro:

* Install and run x64 version on M1
* Install and override x64 with arm64
* Crash on startup in v8 when trying to read the `CachedData`

Workaround:

Start the app with `--no-cached-data`

Proposed solution:

Split out the cache data with arch prefix `CachedData-x64` , `CachedData-arm64`

**Comment by jrieken** [comment]
code pointer: https://github.com/microsoft/vscode/blob/c87c95a1a04b01107328fe1987b1865b2eb367a8/src/main.js#L510

**Comment by jrieken** [comment]
This is now fixed. The root directory is still `CachedData` but the individual hash each cache file uses considers now the arch as well. Keeping the root directly the same helps with the cached data cleaning
