### ISSUE TITLE
Remote-ssh : ssh remote host error with : Access Denied.

### ISSUE THREAD

**Issue by hitcbw** [microsoft/vscode#113871]
1. I have tested ssh connection on powershell and it showed success.
![image](https://user-images.githubusercontent.com/44915850/103727537-76595280-5016-11eb-836b-06b9432e07ff.png)
2. Then I add a config at .ssh folder
![image](https://user-images.githubusercontent.com/44915850/103727614-a7d21e00-5016-11eb-92bc-d2cf67cd837d.png)
3. use remote ssh command with that config, and I set "remote.SSH.showLoginTerminal": true
![image](https://user-images.githubusercontent.com/44915850/103727834-41013480-5017-11eb-9834-c0b069c538e6.png)
4. After inputting the absolutely right password, i got 
![image](https://user-images.githubusercontent.com/44915850/103727746-00092000-5017-11eb-85e8-5dce99ff436a.png)

**Comment by roblourens** [comment]
Does it work if you don't use a `@` in your ssh config? That is the syntax for connecting to that IP with the user "Vultr"

**Comment by hitcbw** [comment]
it seems like works. By the way, if i didn't make a misunderstanding, the string after HOST should be the name of the specified ssh config? So why the Vultr will be resoved as a username? In fact, the Vultr is the VPS supplier instead of my VPS username.
So, if that is the design of VSCode, i' ll close this issue. Please let me know if that's a bug.
Thanks for your reply.

**Comment by roblourens** [comment]
Yeah, I think this is the design of SSH, not just vscode. I can't figure out how to escape the `@` so that ssh would treat it as part of a host name instead of a user/host separator
