### ISSUE TITLE
delay `sendText` until terminal is ready?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11383]
* have code as creates a terminal and immediately sends text to it (like below)
* it would be nice if `sendText` waits for bash (or whatever folks are using) to be ready before sending because now the stuff I have send shows up twice

![screen shot 2016-09-01 at 12 38 13](https://cloud.githubusercontent.com/assets/1794099/18164622/392d9cea-7041-11e6-888a-5768dfe6421b.png)

```

        let terminal = vscode.window.createTerminal();
        terminal.sendText('node');
        terminal.sendText(text);
```

**Comment by Tyriar** [comment]
I don't think this is possible, closing as designed.
