### ISSUE TITLE
State of tabs is not fully updated when toggling workbench.editor.wrapTabs

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#113808]
Issue Type: <b>Bug</b>

With `"workbench.editor.wrapTabs": true`, open enough files to cause wrapping, then open Settings Editor. Clear the wrapTabs checkbox. The currently active tab ("Settings") doesn't scroll into view. Nor does the tab area get a horizontal scrollbar.

Click onto a visible tab to make that scrollbar appear. Scroll to find the "Settings" tab again. Select it. Set the wrapTabs checkbox. The tabs wrap correctly but the horizontal scrollbar remains on the tab area until a tab (even the current one) is clicked.

![junk](https://user-images.githubusercontent.com/6726799/103630110-20fb4380-4f39-11eb-9240-d0fec3d08a0d.gif)

VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:23:04.938Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
//cc @SneakyFish5 @bpasero

**Comment by bpasero** [comment]
Happy to accept a PR to fix this.

**Comment by bpasero** [comment]
@gjsjohnmurray somehow I cannot reproduce anymore, maybe some changes I pushed today also fixed this one. Can you still reproduce running out of sources, or maybe try tomorrow?

**Comment by bpasero** [comment]
![recording](https://user-images.githubusercontent.com/900690/103885896-fcda6680-50e0-11eb-8c9d-f2a692f16364.gif)

**Comment by gjsjohnmurray** [comment]
@bpasero it still happens for me on today's Insiders, and also when I run from source.

**Comment by bpasero** [comment]
Yup I see it, required me to use a fresh user data dir though.

**Comment by bpasero** [comment]
This is better now with my fix for this particular scenario but I am still finding situations where the active tab may not be revealed but I cannot understand what is going wrong. I suspect a timing issue because often the issue is fixed when I delay the layout to a later point.
