### ISSUE TITLE
Never-Ending "Fetching build tasks" Cause Found To Be "package.json"

### ISSUE THREAD

**Issue by vindicatorr** [microsoft/vscode#113898]
- VSCode Version: 1.52.0-insider (24b28f57be22fe3029cb17a1dd72d8d9c2d6468b)
- OS Version: Linux x64 5.8.7-dirty

Steps to Reproduce:

1. mkdir -v ./workspace
2. touch ./workspace/package.json
3. Open ./workspace folder in vscode
4. Create task to do anything (even just "gcc --version")
5. Build project

Does this issue occur when all extensions are disabled?: Yes

I came across this issue in https://github.com/microsoft/vscode-cpptools/issues/6733#issuecomment-754984875

**Comment by alexr00** [comment]
I'm not able to reproduce this issue on the latest insiders. If you still see the problem with the latest insiders I can investigate further.

**Comment by vindicatorr** [comment]
You are correct. It works fine in:
Version: 1.53.0-insider
Commit: 9b6aaf1e86c8fec4c86c664edf5f713583c70fe5
