### ISSUE TITLE
Big Sur Open Dialog does not respond to mouse input

### ISSUE THREAD

**Issue by sihde** [microsoft/vscode#113861]
Issue Type: <b>Bug</b>

After choosing File > Open from the main menu, the expected Open dialog appears. However it does not respond to any mouse input (no clicks, no drag, no scroll wheel). Because it is a modal dialog VS Code appears hung, but the Open dialog does respond to keyboard input so it is possible to exit with "ESC". 

Confirmed on latest Insiders build as well as December public build.

VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:22:22.983Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 6, 7|
|Memory (System)|16.00GB (2.88GB free)|
|Process Argv|--crash-reporter-id bdd69246-9cfd-43c2-b180-9b4e6f32ca1c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
core-portspanel:30233467

```

</details>

**Comment by sihde** [comment]
This may not be a VS Code issue after all... it happens even with the Open dialog in the standard Apple Preview (PDF viewer) app. Maybe if I opened files in something other than VS Code I would have noticed sooner! There is also this thread on the Apple forums about the problem, though it offers no resolution: https://discussions.apple.com/thread/252146315

**Comment by deepak1556** [comment]
Is this still an issue with latest insiders ?

**Comment by sihde** [comment]
This was a Big Sur issue, not VS Code. Agreed it should be closed.
