### ISSUE TITLE
vscode devtool not have chinese language but edge has

### ISSUE THREAD

**Issue by qi525** [microsoft/vscode#113876]
Issue Type: <b>Feature Request</b>

vscode devtool not have chinese language but edge has

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rzhao271** [comment]
Yep, the Edge team has a [blog post](https://blogs.windows.com/msedgedev/2020/02/04/localizing-edge-devtools/#:~:text=Once%20on,%20your%20DevTools%20will%20match%20the%20language,Add%20another%20language,%20change%20it%20to%20your%20primary.) on it, which links to the following Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=941561

Marking this as a Chromium issue, and maybe there's a flag we can turn on.

**Comment by deepak1556** [comment]
There is no feature flag for this, once the above issue completes devtools will be localized according to host system locale. https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/front_end/main/MainImpl.js;l=91-102

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/161002364-2cb5a810-a0f5-4d50-a63e-1f246f95c2d5.png)

DevTools localization has been shipped in 1.66.0

**Comment by deepak1556** [comment]
Thanks for confirming! Closing per above comment
