### ISSUE TITLE
Splits can be opened with a relative path and an absolute path and will not sync

### ISSUE THREAD

**Issue by djobet** [microsoft/vscode#113897]
- VSCode Version:1.52.0
- OS Version:Ubuntu 18.04.4 LTS (local) and Ubuntu 16.04.6 LTS (remote)

Steps to Reproduce:

1. Open a c++ file
2. ctrl-click to follow a symbol with vscode-clangd, this opens a file with an absolute path (e.g : /path/project/A.cc)
3. ctrl-P to open the same file, now the file is "duplicated", it shows both with a relative path and an absolute path (/path/project/A.cc and project/A.cc)
4. if both the relative and the absolute path are opened in 2 different splits, it's now possible to edit one split without seeing the other split synchronized

Does this issue occur when all extensions are disabled?: NA : I didn't do this check since I need an extension to be able to follow symbol with C++.

I use
- CMakeTools 1.5.3 to generate the project
- clangd 0.1.8 to follow symbols

This was first reported there https://github.com/clangd/vscode-clangd/issues/121 and there https://github.com/microsoft/vscode-remote-release/issues/4160

**Comment by bpasero** [comment]
Yes that is expected, you need to open files with the same paths, not different. We take care of path casing, but anything else we do not (such as symbolic links).

**Comment by djobet** [comment]
The thing is I'm not consciously deciding to open those files that way.
I'm quite new to vscode and I started to notice that my edits of the same file in 2 different splits would sometime not synchronize, which IMHO is a bug.
I then started to test when this happens, because it was not clear to me why it would work sometime and would break in other cases, and I found this was the relative vs absolute path thing.
When I code, I tend to open a file, make a change, then eventually explore the code using ctrl-click, ctrk-K F12... to quickly browse the code and see where I need to make the next change.
I can end up with having the same file opened at 2 different places in 2 different splits and make different edits at the same time.
Nothing tells me the splits are not synchronizing at that point if the file is long enough.
It's only when I try to save files that the 2nd split would report that the file was changed on disk and that I need to manually merge it, which is IMHO a waste of time, and can be error prone.

Bottom line, I think there is an inconsistency between
- ctrl-click which opens the file using an absolute path (not my decision) while
- ctrl-P seems to prefer relative path (except when the file has been opened recently, in that case, I see the file twice : one in relative, one in absolute path).

What about having an option to have ctrl-P always show absolute path ?
That way, all my paths would be absolute, no problem.

I'd actually prefer it the other way around : all my files in relative paths, but the guys from clangs-vscode seem to suggest otherwise :
> clangd as a language server communicates all the files through file URIs, which can always be considered as absolute rather than relative, and that's the only way it can communicate with the clients as dictated by language server protocol.

Another possibility would be for vscode to figure out that both files are one and the same. That would be the most transparent I think for the user (no need to change the display, just internally refer to it using say the absolute path).
What would be the rationale/use case of not doing that ?

**Comment by bpasero** [comment]
It seems to me you are possibly using an extension that allows you to navigate from one file to the other (from within the editor). If you can distill some steps to reproduce then it would be good to report against the extension. There is a chance that they produce file paths that we do not detect as normal workspace paths.

Are you able to reproduce this when you run `code --disable-extensions` as well and if so can post the steps?

**Comment by djobet** [comment]
Yes, I explicitly listed the extension I use in the bug report :
    CMakeTools 1.5.3 to generate the project
    clangd 0.1.8 to follow symbols
As explained in the bug report, I use c++ which needs an extension for ctrl-click to work.
As explained in the bug report, I initially opened a bug report with the extension here : https://github.com/clangd/vscode-clangd/issues/121 but they said, and I quote :

> clangd as a language server communicates all the files through file URIs, which can always be considered as absolute rather than relative, and that's the only way it can communicate with the clients as dictated by language server protocol.

Please advise

**Comment by bpasero** [comment]
I don't really understand what "relative" paths the extension could return. When you have the case of 2 editors being "not in sync", what is the result of "Copy Path" from the context menu of the tab in both sides? Is there any difference?

**Comment by djobet** [comment]
Ah ! That's interesting !
They're both absolute, and different because it seems of an intermediate symlink.
I'm editing through NFS and have my edit machine on network XXX and my build machine on network YYY.
There are 2 NFS mount points, so my home in NFS from XXX has a symlink to the home from NFS@YYY.
And somehow, everytime when I open a file using ctrl-P it opens a file from XXX while ctrl-click opens a file from YYY, thus they do not have the same absolute path...
I could not see it because ctrl-P shows relative path from XXX.
Nothing vscode can do here I guess.

**Comment by djobet** [comment]
I confirm that reopening the project directly on the right NFS fixes the issue for me.
