### ISSUE TITLE
Debug: Hovering on same object is not moving the hover 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#11380]
- VSCode Version: Latest insiders
- OS Version: OSX

Steps to Reproduce:

```ts
let obj = {field:1,b:2}

let test = ()=>{
    console.log(obj)
    console.log(obj.field)
    debugger
}
test()
```

In the video, I am trying to move the mouse over two occurrences of `obj` 

![sep-01-2016 11-44-01](https://cloud.githubusercontent.com/assets/10746682/18163060/6cebef4e-7039-11e6-9868-7c2b6d4c64b5.gif)

**Comment by isidorn** [comment]
This is a current limiation of the debug hover.
Closing this as will not fix since I do not think it is a big limitation. Actually might be prefereble in some cases
