### ISSUE TITLE
Tab wrap - allow to change height of tabs

### ISSUE THREAD

**Issue by swinder0161** [microsoft/vscode#113832]
- VSCode Version: 1.53.0-insider
- Commit: a48ef56fbf7767f55a193d7d5687addd1fc9239c
- Date: 2021-01-05T05:22:22.983Z
- Electron: 11.1.0
- Chrome: 87.0.4280.88
- Node.js: 12.18.3
- V8: 8.7.220.29-electron.0
- OS Version: Darwin x64 20.2.0:

This version has https://github.com/microsoft/vscode/pull/106448 integrated and can wrap tabs to multiple lines. https://github.com/microsoft/vscode/issues/70413

After enabling the wrapping, it seems too much height for tabs and screen space is wasted.

It will be good to have an option to sqeeze the tab height so that rows can move up.

as an optional feature, also an option ot change horizontal width of tabs in shrink mode will be good to have

**Comment by swinder0161** [comment]
@bpasero here is the issue I discussed in PR https://github.com/microsoft/vscode/issues/70413

**Comment by vannaka** [comment]
@swinder0161 have you written any code for this issue? I can't find a PR for it and you haven't linked to any? 
> 
> 
> @bpasero here is the issue I discussed in PR #70413

In your comment you say 'PR', did you mean 'issue'? This page that we are having this conversation on is an 'issue' not a 'PR'.

**Comment by swinder0161** [comment]
@vannaka is it related to PR #70413
I have not yet written any code. Maybe next week I might have some time to do it.

**Comment by swinder0161** [comment]
@bpasero I see another issue that edirot font size change also changes the font size of filename in tab. so if some one increases editor font size, which I normally do to not strain my eyes, the tabs row takes more vertical space.

**Comment by bpasero** [comment]
The editor don't size is not used anywhere outside the editor, i think you talk about zooming?

**Comment by swinder0161** [comment]
Yes you are correct my zoom was set to 1 and now -0.5 looks nice. incidentally my old font size(12) matched the font size in tab text. Now I changed font size in editor to 10 but tab font size is still bigger ~12

What is zoom you are talking about.

![image](https://user-images.githubusercontent.com/397543/103893843-f87b7100-5113-11eb-872d-98c34fceb577.png)

**Comment by yume-chan** [comment]
I found #42253 when searching, not sure whether the old hacks in there are still valid after wrapping tabs.
