### ISSUE TITLE
Support word wrap in the diff editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#11387]
I cannot get word wrapping enabled in a diff editor when using that action but maybe there is no word wrapping for diff editors?

**Comment by alexandrudima** [comment]
Yes, word wrapping was never supported in diff editor -- has to do with aligning lines that wrap.

**Comment by bpasero** [comment]
Got it 👍

**Comment by vogler** [comment]
It would be nice if the diff editor also respected the word wrap setting.

Another related issue:
Both panes scroll in sync - but only to their content's width instead of the maximum of both panes.
So if I scroll on the left and come to a change where the right version is longer, I have to move the mouse to the right pane in order to be able to scroll to the end of the line.

**Comment by Fania** [comment]
I work on Latex projects with long paragraphs of text. Find and replace is almost unusable without word wrap. I can see how it wouldn't bother me much on my python projects maybe, but in Latex it's terrible.

**Comment by jakearchibald** [comment]
I'm a huge fan of vscode, but this is a blocker for me when it comes to using it for diffing.

**Comment by mattfaces** [comment]
Is there some way to configure VS Code so that it launches an external Diff Tool instead (e.g. Araxis Merge) as a temporary workaround until this issue is fixed? (Even if I have to manually click a button to launch the the 3rd party diff tool.)

**Comment by Dominik-K** [comment]
@alexandrudima If aligning lines is the blocker for this request, then the "flowing lines" diff view mentioned in #25887 would solve this, right?

**Comment by protoEvangelion** [comment]
Are there any updates related to this issue?

**Comment by yaronyg** [comment]
I'm trying to diff MD files and the lack of word wrap support makes it pretty much impossible. :(

**Comment by Kappanneo** [comment]
Same problem here, can't work on Latex diffs.

**Comment by pavelkouril** [comment]
Yes, this is a huge issue, makes it unuseable for a lot of diffing. :(

**Comment by pumpkinlink** [comment]
A good solution about aligning would be to break the line at any character, as opposed to breaking only between words, actually that is how have my Vim setup, it is good for small screens. Example:
This:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque suscipit r
isus quis pulvinar elementum. Aliquam faucibus nibh in turpis semper mollis. Nul
la euismod diam eu feugiat venenatis. Nullam quis ex vel mi condimentum maximus 
id id massa. Donec felis sem, porttitor at ligula eu, dapibus ultrices ante. Ali
quam quis accumsan arcu. Donec sollicitudin a ante id scelerisque. Aliquam eget 
lectus lectus. Quisque mattis, lectus non auctor auctor, nisi dui accumsan est, 
nec finibus ligula est nec est. Praesent scelerisque in sapien et consequat. Mae
cenas sollicitudin magna augue, quis ultrices urna pulvinar ut. Proin nisi turpi
s, fringilla eget diam eu, gravida iaculis tellus. Etiam et gravida nulla. Ut no
n faucibus lacus. Nulla facilisi.
```

Instead of this: 
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque suscipit 
risus quis pulvinar elementum. Aliquam faucibus nibh in turpis semper mollis. 
Nulla euismod diam eu feugiat venenatis. Nullam quis ex vel mi condimentum 
maximus id id massa. Donec felis sem, porttitor at ligula eu, dapibus ultrices 
ante. Aliquam quis accumsan arcu. Donec sollicitudin a ante id scelerisque. 
Aliquam eget lectus lectus. Quisque mattis, lectus non auctor auctor, nisi dui 
accumsan est, nec finibus ligula est nec est. Praesent scelerisque in sapien et 
consequat. Maecenas sollicitudin magna augue, quis ultrices urna pulvinar ut. 
Proin nisi turpis, fringilla eget diam eu, gravida iaculis tellus. Etiam et 
gravida nulla. Ut non faucibus lacus. Nulla facilisi.
```

**Comment by jakearchibald** [comment]
@pumpkinlink I wouldn't mind that as an option, but don't think it should be the default.

I like what Github's split view does https://github.com/w3c/ServiceWorker/pull/1229/files?diff=split.

**Comment by nicolefmfa** [comment]
I would also like to know if there are any updates on this issue. Comparing files is very difficult at the moment due to the lack of word wrap in the Git diff view. Has anyone found any workarounds?

**Comment by michou** [comment]
@alexandrudima re:

> Yes, word wrapping was never supported in diff editor -- has to do with aligning lines that wrap.

The thing is, it doesn't work with inline diffs, either. Don't know if that would be easier to implement, but I'd take this half-solution any time.

`<backstory>` I was **_SO_** thrilled to be able to review code inside VSCode only to stumble on a markdown file with lines long enough to send me back to the browser screaming 😱`</backstory>`

**Comment by slikts** [comment]
Is there a better workaround than using an external tool for diffing? It's not exaggeration to say that the current diffing is unusable for use cases like markdown editing.

**Comment by liudonghua123** [comment]
I like this feature 😃

**Comment by lennart-tondeleir** [comment]
Word wrap for the diff editor would be very useful indeed...

**Comment by robertbenjamin** [comment]
+1

**Comment by werunom** [comment]
Badly need this for tracking latex files

**Comment by protoEvangelion** [comment]
@bpasero If the decision is that you will not implement this, that is OK 😄 
But an update would be nice on whether or not it will make it onto the roadmap.
Thanks for all the fantastic work by the way!!!

**Comment by chnmng** [comment]
+1

**Comment by rtens** [comment]
+1

**Comment by iliyang** [comment]
This would be so awesome to have! I also work on LaTeX projects where every paragraph is a single (looong) line, and it's so frustrating that so few git clients have a word wrapping feature in their side-by-side diff views (and some don't even have side-by-side diffs!). VSCode's git integration is pretty slick already, and having this feature would put the nail in the coffins of dedicated git clients for me. Keeping fingers crossed!

**Comment by wsdou** [comment]
Badly need this feature to compare Latex files.

**Comment by fulldecent** [comment]
It will be most helpful if the people here can post screenshots of other best-in-class diff editors which do allow diffing of long lines of text.

How do they handle very long lines?

How do they handle scrolling if the left or right side has very different length of content?

**Comment by Summerslyb** [comment]
> It will be most helpful if the people here can post screenshots of other best-in-class diff editors which do allow diffing of long lines of text.
> 
> How do they handle very long lines?
> 
> How do they handle scrolling if the left or right side has very different length of content?

I have tried a lot of diff tools. For me, the best tools must be `Araxis Merge`. The screenshot is presented below: 
![QQ截图20190523102517](https://user-images.githubusercontent.com/10459559/58221434-1892cc80-7d45-11e9-9690-6b97b7eae53b.png)

`WinMerge` is also a good diff tools for multi-line diff, but some details is not as good as `Araxis Merge`.

![QQ截图20190523102652](https://user-images.githubusercontent.com/10459559/58221609-ca31fd80-7d45-11e9-8ca2-3cc3761d4bbd.png)

**Comment by MagTun** [comment]
Here is a printscreen of np++ (which wrap long lines)

![image](https://user-images.githubusercontent.com/15843700/58622562-2bb91580-82cc-11e9-9ac9-29beee9437bf.png)

**Comment by gsanchezu** [comment]
I would also love this feature to be implemented, any update on this?

**Comment by madacol** [comment]
> How do they handle very long lines?

Why not treat word wrapping like you already do when there's new lines?
![image](https://user-images.githubusercontent.com/6379896/62579092-7923a700-b868-11e9-8332-c30d202e3631.png)

If new file has a way longer line that when wrapped it shows more lines, then the old one could show those striped lines to fill in

Vscode highlights word differences like the examples given by [Summerslyb](#issuecomment-495044134), but wrapping is what's missing

**Comment by inwardmovement** [comment]
Any news on this?

**Comment by bkarlson** [comment]
Anyone here?

**Comment by liudonghua123** [comment]
Any news on this?

**Comment by fkjogu** [comment]
Please do not spam the issue tracker.

**Comment by elesiuta** [comment]
> How do they handle very long lines?
> 
> How do they handle scrolling if the left or right side has very different length of content?

I like the option already described by [madacol](https://github.com/Microsoft/vscode/issues/11387#issuecomment-518857992), which is also how GitHub's split diff works and was already mentioned by [jakearchibald](https://github.com/Microsoft/vscode/issues/11387#issuecomment-349953802)
![Github](https://user-images.githubusercontent.com/8146662/67218918-2ed8ad80-f3f5-11e9-925b-4454bc2dd429.PNG)

The compare plugin for Notepad++ also works well and was mentioned, but the screenshot didn't show how it handles scrolling when left and right have different length. It doesn't create empty lines on the opposite side like GitHub's split diff, and instead handles this by syncing the location of the lines where caret/text cursor is when scrolling.
![Notepad++ compare plugin](https://user-images.githubusercontent.com/8146662/67218966-3f892380-f3f5-11e9-9fa9-6bcd008882bf.PNG)
![YP7kN3MfN0](https://user-images.githubusercontent.com/8146662/67219442-0a310580-f3f6-11e9-9377-4aeea97ee832.gif)

**Comment by brunoarruda** [comment]
> I found a solution by adding this to my ~/.gitconfig file:
> 
> ```
> [mergetool "araxis"]
> 	path = /Applications/Araxis Merge.app/Contents/Utilities/compare
> [diff]
>     tool = araxis
> [merge]
>     tool = araxis
> ```

I configured Git to work with an external Difftool as @matt-cooper suggests, while VS Code doesn't fix this issue. but I used WinMerge instead of Araxis, because its opensource. I didn't need to install GitDiffer extesion because the context menu already had an option for it. For anyone interested, I added the exe to the path on Windows and set the `.gitconfig` file following instructions [here ](https://coderwall.com/p/76wmzq/winmerge-as-git-difftool-on-windows) and [here](https://stackoverflow.com/questions/10713925/how-can-i-make-winmerge-my-git-mergetool):

```
[mergetool "winmerge"]
    cmd = WinMergeU -e -ub -fm -wl -wr $LOCAL $BASE $REMOTE -o $MERGED -am
[difftool "winmerge"]
    cmd = WinMergeU -e "$LOCAL" "$REMOTE"
[merge]
    tool = winmerge
[diff]
    tool = winmerge
```

As other people stated here, I missed word wrapping when I started working on a latex project. It is really impracticable to have such large lines rendered as a single one.

**Comment by FMuro** [comment]
I can understand the difficulties of implementing word wrap in the side by side diff mode, but could we in the meantime get the option of enabling word wrap just in the inline diff mode? I guess this could be done straight away, sort of, and would be a satisfactory solution for many of us dealing with long lines files, e.g. LaTeX.

**Comment by coffee-and-genomics** [comment]
> It will be most helpful if the people here can post screenshots of other best-in-class diff editors which do allow diffing of long lines of text.
> 
> How do they handle very long lines?
> 
> How do they handle scrolling if the left or right side has very different length of content?

FileMerge has, I think, an excellent view to base this off of. It is great for diffing prose lines, but that's pretty much all it does AFAIK. I think this is the view people are clamoring for to be implemented alongside other git functionality:
<img width="1459" alt="Screen Shot 2020-01-29 at 5 23 16 PM" src="https://user-images.githubusercontent.com/43548130/73406546-4bba3200-42bc-11ea-9b82-abd1e74633b6.png">

**Comment by matt-cooper** [comment]
Here's an example in Araxis Merge (as you scroll the lines scroll at different rates so that the middle of both viewports point to equivalent parts of code and the lines connecting the diffs adjust accordingly):
<img width="1113" alt="araxis-merge-example" src="https://user-images.githubusercontent.com/1268224/73408066-37743600-42b8-11ea-85c7-0e519068bbb9.png">

**Comment by pmattei** [comment]
This feature will be very usefull. Do we have any news on it?

**Comment by alikrc** [comment]
we are still waiting for this guys

**Comment by jxbell** [comment]
I also would love to have this. I work on a lot of Markdown files with extremely long lines.

**Comment by iliyang** [comment]
As another example, [Diffchecker](https://www.diffchecker.com) also supports word wrapping. [Here](https://www.diffchecker.com/OWTMaTI7)'s an example (where the diff view has some extra new lines, but that's probably some bug).

**Comment by AlexandreDecan** [comment]
I don't understand why this feature is still in the backlog and not planned for an upcoming release of vscode :(

**Comment by alexeedm** [comment]
+1 for the feature. Latex and Jupyter notebooks with long markdown lines are a nightmare to diff in VS Code right now.

**Comment by liudonghua123** [comment]
It's almost four years about this wanted feature. 😲

**Comment by avin-shum** [comment]
Actually some formatter do not format code with hard wrap (e.g. C#). Support word wrap in the diff editor is quite essential for those use cases.

**Comment by skupjoe** [comment]
Was expecting compareit plugin to support word wrapping. 👍

**Comment by gjsjohnmurray** [comment]
> Was expecting compareit plugin to support word wrapping.
> Without it, it's impossible to compare a two single long strings

@skupjoe this should be reported to the compareit extension author.

**Comment by skupjoe** [comment]
Also happens on partialdiff

**Comment by stagefright5** [comment]
This is a necessity. Please take this on priority

**Comment by SergeyMatsiupa** [comment]
I also join to this request.
Now I have use because of this some external tools (think that [Meld](http://https://meldmerge.org) is the best one - so you can take it as an example).

**Comment by Nadano** [comment]
I made a feature request for a word based diff on vscode, could it be an alternative to what people are asking in this post?

https://github.com/microsoft/vscode/issues/103285

**Comment by FMuro** [comment]
> I made a feature request for a word based diff on vscode, could it be an alternative to what people are asking in this post?
> 
> #103285

I don't see the relation.

**Comment by Nadano** [comment]
At least until word wrapping it done it should be possible to work with long lines if you can see the changes inline

**Comment by PeteX** [comment]
Word diff would be somewhat useful to me, but it's not as important as line wrapping.  You get something approximating word diff anyway, because VSCode highlights the changed characters as well as the changed lines.

(The funny thing is that VSCode highlights changed characters but doesn't wrap lines.  Atom wraps lines but doesn't highlight changed characters.  When comparing documentation files with long lines, you just can't win!)

**Comment by frodal** [comment]
Instead of using an external diff tool with VSCode, the `Rewrap` extension can be used to break lines while looking at the diff with VSCode. The extension can be used to break lines at the cursor location by pressing `Alt`+`Q`. `Rewrap` also supports automatic wrapping (off by default) https://github.com/stkb/Rewrap/wiki/Auto-wrap. `Rewrap` requires no further settings to use. This behavior should be implemented in the diff editor of VSCode.

See also https://stackoverflow.com/questions/43122175/automatically-hard-wrap-lines-at-column-in-vscode/45883430

**Comment by SergeyMatsiupa** [comment]
> Instead of using an external diff tool with VSCode, the `Rewrap` extension can be used to break lines while looking at the diff with VSCode. 

@frodal sorry but looks like it doesn't work properly (for two in-memory documents at least):
![Screenshot_2020-09-05_17-55-01](https://user-images.githubusercontent.com/58095743/92307810-a974d200-efa1-11ea-95e2-ab3d1056dc94.png)

**Comment by frodal** [comment]
@SergeyMatsiupa have you tried changing the settings of `Rewrap`, e.g., the wrapping column setting?
Here's an example with Latex, I guess it's not perfect.
![image](https://user-images.githubusercontent.com/22394313/92992270-14666180-f4ea-11ea-9bd7-8c5664f5e42a.png)

![image](https://user-images.githubusercontent.com/22394313/92992324-6313fb80-f4ea-11ea-8712-93eee947cb59.png)

**Comment by technic** [comment]
@frodal

This looks nice. Could you provide instructions how to get the wrapping work like on your second screenshot?

**Comment by frodal** [comment]
@technic see my previous post: https://github.com/microsoft/vscode/issues/11387#issuecomment-687106750

**Comment by floschl** [comment]
I think the initial intention of this feature request is rather to display the differences of a long line auto-wrapped in a multi-line, without making changes in the code, i.e. inserting new lines. The Rewrap extension seems to insert new lines!?

**Comment by pmattei** [comment]
I totally approve @floschl objection. 
@frodal Thank for your workaround, but it cannot be used in many work situations.
For my example, we work on differents IDE (VScode/emacs/vim)
We already had a debate about the max line code length, with no concensus.
Just one rule, "please, do not commit to only modify code appearance, respect other coworkers work."
So it happend, that I have to review some lines with more than 300 characters. 
With your workaround, I should rewrap all modified files before each review, and if I want to propose a diff, I should revert my modifications before. Not really efficient.
Other coworkers do not have this problem on emacs for example.

**Comment by Glaeqen** [comment]
I'm impressed that this issue just hangs in here for 4 years now.

**Comment by bknaepen** [comment]
I also would like this feature added...

**Comment by piersdeseilligny** [comment]
This issue also makes it impossible to diff [fountain](https://github.com/piersdeseilligny/betterfountain) documents. Although this issue applies to any type of markup really, which means it isn't exactly an edge case or anything.

Why is something like this on the backlog? The original issue has got over 300 likes and was opened when vscode 1.4.0 was released - there's been 46 feature updates since. What other community support would be necessary for this to at least be looked at?

**Comment by pmattei** [comment]
Can't wait to see it :)

**Comment by AlexandreDecan** [comment]
Thank you!

**Comment by gjsjohnmurray** [comment]
@alexdima should this be working in Insiders now? I selected two files in Explorer, chose "Compare Selected", then tried to toggle word wrap from the View menu. It gave me an info notification"Cannot toggle word wrap in a diff editor."

Version: 1.52.0-insider (user setup)
Commit: 050a123750e4ef4009930d0da1ff7a1a6441d4f3
Date: 2020-11-12T05:43:04.852Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by alexdima** [comment]
@gjsjohnmurray Yes, I've also seen that the toggle action in the View menu does not work yet. Setting word wrap via settings works for now. Let's track in https://github.com/microsoft/vscode/issues/110468

**Comment by h-h-h-h** [comment]
It's *finally* working! 😲 🤩
