### ISSUE TITLE
Page-Up / Page-Down in git commit text box scrolls entire page

### ISSUE THREAD

**Issue by ralfstx** [Microsoft/vscode#11385]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. In the Git view, enter multiple lines of text into the commit message text box, until the scroll bar appears.
2. While the text box is focused, press Page-Up / Page-Down.

At some point, the entire page is shifted up by approx. 15px. The tabs at the top are partly covered and there is some empty space below the status bar.

**Comment by joaomoreno** [comment]
The (hidden) panel seems to overflow the whole workbench.

<img width="1680" alt="screen shot 2016-09-02 at 10 02 04" src="https://cloud.githubusercontent.com/assets/22350/18196889/67297192-70f4-11e6-8a30-4ed0b2eede3d.png">

@isidorn I've attempted to unflow the panel when it gets hidden, which fixes the issue. Created a PR with that change for September, for you to review: #11436

**Comment by isidorn** [comment]
I have merged the PR thus closing this issue
