### ISSUE TITLE
When using typeahead right arrow should stop at the end of the prompt 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#113857]
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:32:43.927Z (2 wks ago)
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.2.0

holding down right arrow makes the cursor continue past where we expect it to end... screenshot isn't great but imagine holding right arrow and cursor keeps going right
![image](https://user-images.githubusercontent.com/2644648/103704990-1b185900-4f5f-11eb-8651-57cf49ab5aef.png)

It should stop at the "end of the prompt" just like how typeahead stops at the being of the prompt on left arrow.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jace4511** [comment]
> Version: 1.53.0-insider
> Commit: [4a875e2](https://github.com/microsoft/vscode/commit/4a875e23d20b64504a818834f3fa4c40adb8d480)
> Date: 2020-12-21T12:32:43.927Z (2 wks ago)
> Electron: 11.1.0
> Chrome: 87.0.4280.88
> Node.js: 12.18.3
> V8: 8.7.220.29-electron.0
> OS: Darwin x64 20.2.0
> 
> holding down right arrow makes the cursor continue past where we expect it to end... screenshot isn't great but imagine holding right arrow and cursor keeps going right
> ![image](https://user-images.githubusercontent.com/2644648/103704990-1b185900-4f5f-11eb-8651-57cf49ab5aef.png)
> 
> It should stop at the "end of the prompt" just like how typeahead stops at the being of the prompt on left arrow.
> 
> Does this issue occur when all extensions are disabled?: Yes
