### ISSUE TITLE
UI Popup intellisense

### ISSUE THREAD

**Issue by aldd-waguirreo** [microsoft/vscode#113855]
- VSCode Version: 1.53.0 (insider)
- OS Version: Windows 10

Steps to Reproduce:

1. Intellense typescript
![image](https://user-images.githubusercontent.com/64616116/103703882-5a05d900-4f76-11eb-8e13-7da4e9c0cddb.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This should be fixed in the current insiders builds
