### ISSUE TITLE
Notebook moves focus in and out of output

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#113882]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=99302&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea&l=104

```
 1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           moves focus in and out of output:
     Error: Timeout: is active element 'webview, .webview' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by rebornix** [comment]
It seems it's still flaky https://dev.azure.com/monacotools/Monaco/_build/results?buildId=110155&view=logs&jobId=3792f238-f35e-5f82-0dbc-272432d9a0fb&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=bd1c96ef-8f6c-518c-1bd9-e87b3a72835d

**Comment by TylerLeonhardt** [comment]
Consolidate notebook smoke-test failures? https://github.com/microsoft/vscode/issues/119164
