### ISSUE TITLE
No authentication provider 'microsoft' is currently registered

### ISSUE THREAD

**Issue by shreyaskarnik** [microsoft/vscode#113844]
Issue Type: <b>Bug</b>

Settings sync is on and the extension host crashes

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|. --crash-reporter-id 16b676c3-cd93-4c10-885e-030fcabdb6fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-apollo|apo|1.18.0
django-html|bib|1.3.0
django-snippets|bib|1.1.1
better-toml|bun|0.3.2
gotemplate|cas|0.4.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
systemd-unit-file|coo|1.0.6
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.9
shell-format|fox|7.0.1
go|gol|0.20.1
terraform|has|2.3.0
Lua|key|0.0.9
vscode-lua-format|Koi|1.3.6
rust-analyzer|mat|0.2.441
dotenv|mik|1.0.1
file-downloader|min|1.0.9
mindaro|min|1.0.120201211
vscode-cosmosdb|ms-|0.15.1
vscode-docker|ms-|1.9.0
kind-vscode|ms-|0.0.3
vscode-kubernetes-tools|ms-|1.2.1
vscode-postgresql|ms-|0.3.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2020.12.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.4
cpptools|ms-|1.1.3
vs-keybindings|ms-|0.2.0
vscode-typescript-tslint-plugin|ms-|1.3.2
debugger-for-chrome|msj|4.12.11
material-icon-theme|PKi|4.4.0
polacode|pnp|0.3.4
quicktype|qui|12.0.46
vscode-yaml|red|0.13.0
jinjahtml|sam|0.15.0
code-settings-sync|Sha|3.4.3
ayu|tea|0.20.1
opa|tsa|0.6.1
vscode-lldb|vad|1.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.1.0
codetour|vsl|0.0.42
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
material-theme|zhu|3.9.12
vscode-proto3|zxh|0.5.3

(15 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
Can you please explain what is the issue here? What is not working?

**Comment by shreyaskarnik** [comment]
All extensions cease to work after the extension host crash.

**Comment by sandy081** [comment]
/duplicare

Seems similar to #113817
