### ISSUE TITLE
terminal screen cheese

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11382]
* I have an extension that evaluates some selected text in node in the terminal
* As soon as I select the terminal (click) its content scroll up and I cannot get it back

![sep-01-2016 12-35-53](https://cloud.githubusercontent.com/assets/1794099/18164541/b7b4b32e-7040-11e6-9f14-e5ce4b122383.gif)

```js
    let terminal: vscode.Terminal;
    vscode.commands.registerCommand('extension.runInNode', () => {
        let {selection, document} = vscode.window.activeTextEditor;
        let text = document.getText(selection);

        if (!terminal) {
            terminal = vscode.window.createTerminal({ name: 'nodejs - scratch page'});
        }

        terminal.sendText('node');
        terminal.sendText(text);

    });
```

```json
		"menus": {
			"editor/context": [
				{
					"command": "extension.runInNode",
					"when": "editorHasSelection"
				}
			]
		}

```

**Comment by Tyriar** [comment]
Cannot repro in Ubuntu 16.04 on bash, what platform/shell are you on?

**Comment by Tyriar** [comment]
Difficulty reproducing so moving to September. If this is a bug I is very likely a low-repro bug that's present in the terminal, not an issue with the API.

**Comment by Tyriar** [comment]
Closing this off as it has not been reported for 2 weeks and can't repro. It's also very likely an upstream issue.
