### ISSUE TITLE
Progress bar indication with withProgress, using progress.report and increment, does not look correct visually

### ISSUE THREAD

**Issue by bpringe** [microsoft/vscode#113846]
Version: 1.52.1
OS: Linux x64 5.4.85-1-MANJARO

Using `vscode.window.withProgress` to report incremental progress of a file download (using `vscode.ProgressLocation.Notification` as the `location`, I see the progress indicator bar in the notification fill the whole width of the notification window well before the progress reaches 100%.

Below is the relevant code:

```javascript
response.on('data', data => {
    bytesReceived += data.length;
    increment = (bytesReceived / totalBytes) * 100;
    progress.report({
        increment,
        message: Math.round(increment) + '%'
    });
```

At 1% completion (increment of ~1) the status bar (blue line at bottom) looks to be filling about 20% of the notification window width.

![image](https://user-images.githubusercontent.com/12722744/103694892-89a1ea80-4f50-11eb-89fd-9971480a2682.png)

At 2% completion, the bar fills 60%+ of the notification window width.

![image](https://user-images.githubusercontent.com/12722744/103695017-b6560200-4f50-11eb-8ac0-4dd9245a2426.png)

Here's a gif of the progress in real time:

![download-progress](https://user-images.githubusercontent.com/12722744/103695229-0d5bd700-4f51-11eb-9c8f-370e8e52ba7c.gif)

Edit: Am I misunderstanding what should be happening? I expect the blue progress bar to take up the same percentage of the width of the notification window as the progress percentage.

**Comment by bpasero** [comment]
Please speak up again if you could not find help, but we are not giving support for our API in issues. If you still think there is a bug in VSCode we can always reopen.

**Comment by bpringe** [comment]
Sorry. Where are issues related to the extension API tracked (not ephemerally, like on Slack)?

**Comment by bpasero** [comment]
They are tracked here in this repository. I was mainly asking you to get some help from others that were successful in using the progress indicator with discrete progress and then come back here if you still think there is a bug in VSCode itself or if the documentation should be updated.

**Comment by bpringe** [comment]
For anyone who may come across this, `increment` is summed automatically for you, as the docs state:

> Each call with a increment value will be summed up and reflected as overall progress until 100% is reached

I somehow missed this. :smile:
