### ISSUE TITLE
Quick open fails to locate file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#113823]
Am I missing something? 🤔

This is on our distro repo.

![image](https://user-images.githubusercontent.com/22350/103655490-2f873200-4f1c-11eb-9248-daa141e8e874.png)

**Comment by roblourens** [comment]
Uh, weird: 
![image](https://user-images.githubusercontent.com/323878/103673675-bc3cea80-4f32-11eb-95b3-b10b9200ea31.png)

anything else missing?

You can set log level -> Trace and see search logs in the Window output channel

**Comment by roblourens** [comment]
Does text search work?

**Comment by jrieken** [comment]
> Does text search work?

Nope. I don't find `src/vs/workbench/contrib/notebook/browser/contrib/outline/notebookOutline.css` via file search and there should also be a text match in that file

<img width="349" alt="Screenshot 2021-01-05 at 18 50 31" src="https://user-images.githubusercontent.com/1794099/103680736-e5876600-4f86-11eb-8a2c-a08b41704362.png">

**Comment by bpasero** [comment]
however this works for me:

![image](https://user-images.githubusercontent.com/900690/103680868-14054100-4f87-11eb-8735-abf199e2343d.png)

**Comment by roblourens** [comment]
I have something I can repro now, it works in my remote vscode repo but not local

**Comment by roblourens** [comment]
Who put this in .gitignore? `out*/` 🤔

**Comment by roblourens** [comment]
And the original issue, the .gitignore in distro has 

```
src/vs/server
resources/server
``` 

which should not be there, seems they were merged in probably by mistake at some point in the past couple months

**Comment by roblourens** [comment]
Reading the gitignore doc, really seems like the leading slash shouldn't be necessary if the pattern already contains a slash, but testing with git, that's not how it works. Anyway, pushed fixes to both repos.

**Comment by joaomoreno** [comment]
Oh my bad! Thanks for the fix, @roblourens.
