### ISSUE TITLE
VS Code not working in Windows Server 2012 R2

### ISSUE THREAD

**Issue by ayankumaar** [microsoft/vscode#113890]
We have installed VS Code version 1.51.0 (Per-User installation). The system configuration is given below:

**OS: Windows Server 2012 R2
Processor: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (2 Processors)
Installed Memory (RAM): 8.00 GB
System Type: 64-bit Operating System, x64-based processor**

The installation has been successful. But, when we are trying to launch VS Code then it is not launching. So, we ran this command **code --verbose**. Here is the output of that command:

[main 2021-01-06T07:37:12.706Z] Starting VS Code
[main 2021-01-06T07:37:12.706Z] from: c:\Users\XXXX\AppData\Local\Programs\Microsoft VS Code\resources\app
[main 2021-01-06T07:37:12.706Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'f95f1436-6d9c-42cd-a63c-51b64b3cdb4e',
  'disable-user-env-probe': false,
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'open-devtools': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false
}
[main 2021-01-06T07:37:12.708Z] Resolving machine identifier...
[main 2021-01-06T07:37:12.708Z] Resolved machine identifier: 001394eff4095b6306ca7ca12ebda81812142335a7bd5d6c694248c0ead82aca
[main 2021-01-06T07:37:12.855Z] [storage state.vscdb] open(c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2021-01-06T07:37:12.855Z] lifecycle (main): phase changed (value: 2)
[main 2021-01-06T07:37:12.857Z] windowsManager#open
[main 2021-01-06T07:37:12.857Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\XXXX\\AppData\\Roaming\\Code\\Backups\\1609915016674',
    remoteAuthority: undefined
  }
]
[main 2021-01-06T07:37:12.859Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 128, y: 20, width: 1024, height: 666 }
[main 2021-01-06T07:37:12.859Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1280, height: 683 }
[main 2021-01-06T07:37:12.859Z] window#ctor: using window state { mode: 1, x: 128, y: 20, width: 1024, height: 666 }
[main 2021-01-06T07:37:12.930Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-01-06T07:37:12.930Z] lifecycle (main): phase changed (value: 3)
[main 2021-01-06T07:37:12.931Z] update#setState idle
[main 2021-01-06T07:37:13.123Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
[main 2021-01-06T07:37:13.125Z] getShellEnvironment: running on Windows, skipping
[main 2021-01-06T07:37:13.188Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:13.188Z] [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 2021-01-06T07:37:13.189Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2021-01-06T07:37:13.189Z] [storage state.vscdb] getItems(): 41 rows
[main 2021-01-06T07:37:13.291Z] [storage state.vscdb] updateItems(): insert(Map(3) {storage.serviceMachineId => 128f1789-bd68-433e-9f1f-7e6a9b7b448a, telemetry.lastSessionDate => Wed, 06 Jan 2021 07:36:05 GMT, telemetry.currentSessionDate => Wed, 06 Jan 2021 07:37:13 GMT}), delete(Set(0) {})
[main 2021-01-06T07:37:13.344Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2021-01-06T07:37:13.359Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('storage.serviceMachineId','128f1789-bd68-433e-9f1f-7e6a9b7b448a'),('telemetry.lastSessionDate','Wed, 06 Jan 2021 07:36:05 GMT'),('telemetry.currentSessionDate','Wed, 06 Jan 2021 07:37:13 GMT')
[main 2021-01-06T07:37:13.360Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:13.394Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2021-01-06T07:37:13.412Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:13.620Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:15.152Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:15.363Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage
[main 2021-01-06T07:37:42.932Z] update#checkForUpdates, state =  idle
[main 2021-01-06T07:37:42.932Z] update#setState checking for updates
[main 2021-01-06T07:37:42.932Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64-user/stable/fcac248b077b55bae4ba5bab613fd6e9156c2f0c
[main 2021-01-06T07:37:43.029Z] Error: net::ERR_PROXY_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6395)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
[main 2021-01-06T07:37:43.029Z] update#setState idle
[main 2021-01-06T07:37:43.169Z] [VS Code]: detected unresponsive
[main 2021-01-06T07:38:02.992Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-01-06T07:38:02.992Z] Lifecycle#onWillShutdown.fire()
[main 2021-01-06T07:38:02.997Z] [storage state.vscdb] close()
[main 2021-01-06T07:38:02.998Z] Lifecycle#app.on(window-all-closed)
[main 2021-01-06T07:38:02.998Z] Lifecycle#app.on(before-quit)
[main 2021-01-06T07:38:02.998Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-01-06T07:38:02.998Z] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: 'C:\\Users\\XXXX\\AppData\\Roaming\\Code\\Backups\\1609915016674',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 128,
      y: 20,
      width: 1024,
      height: 666
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-01-06T07:38:02.999Z] Lifecycle#app.on(will-quit)

We also tried to install VS Code VSCodeSetup-x64-1.53.0-insider as a system installer (For all users in the system). Even in that case we are not able to launch VS Code after the installation. We ran again **code --verbose**. Here is the output of that command:

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[main 2021-01-06T07:47:18.622Z] Starting VS Code
[main 2021-01-06T07:47:18.622Z] from: c:\Program Files\Microsoft VS Code Insiders\resources\app
[main 2021-01-06T07:47:18.622Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': '689bab03-b20b-41b5-b0e8-8941793a6245',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: 'C:\\Users\\XXXX\\AppData\\Roaming\\Code - Insiders\\logs\\20210106T014718'
}
[main 2021-01-06T07:47:18.630Z] Resolving machine identifier...
[main 2021-01-06T07:47:18.630Z] Resolved machine identifier: 8ab78a4249a8264a073232192be43f72b1773615a8195b4a8623ac9dd5eb6a75
[main 2021-01-06T07:47:18.992Z] [storage state.vscdb] open(c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage\state.vscdb, retryOnBusy: true)
[main 2021-01-06T07:47:18.998Z] lifecycle (main): phase changed (value: 2)
[main 2021-01-06T07:47:19.000Z] windowsManager#open
[main 2021-01-06T07:47:19.000Z] windowsManager#open pathsToOpen [
  {
    backupPath: 'C:\\Users\\XXXX\\AppData\\Roaming\\Code - Insiders\\Backups\\1609918891961',
    remoteAuthority: undefined
  }
]
[main 2021-01-06T07:47:19.001Z] window#validateWindowState: validating window state on 1 display(s) { mode: 1, x: 128, y: 0, width: 1024, height: 684 }
[main 2021-01-06T07:47:19.002Z] window#validateWindowState: 1 monitor working area { x: 0, y: 0, width: 1280, height: 683 }
[main 2021-01-06T07:47:19.003Z] window#ctor: using window state { mode: 1, x: 128, y: 0, width: 1024, height: 683 }
[main 2021-01-06T07:47:19.139Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 0, emptyToRestore: 1, emptyToOpen: 0)
[main 2021-01-06T07:47:19.145Z] lifecycle (main): phase changed (value: 3)
[main 2021-01-06T07:47:19.153Z] update#setState idle
[main 2021-01-06T07:47:19.153Z] resolveShellEnv(): skipped (Windows)
(node:4152) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-01-06T07:47:19.266Z] [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
[main 2021-01-06T07:47:19.266Z] [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
[main 2021-01-06T07:47:19.267Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:19.319Z] [storage state.vscdb] getItems(): 6 rows
[main 2021-01-06T07:47:19.320Z] [storage state.vscdb] Trace (event): SELECT * FROM ItemTable
[main 2021-01-06T07:47:19.431Z] [storage state.vscdb] updateItems(): insert(Map(3) {storage.serviceMachineId => 6cec377b-5c13-4beb-b3ee-4f963b2b00ed, telemetry.lastSessionDate => Wed, 06 Jan 2021 07:44:42 GMT, telemetry.currentSessionDate => Wed, 06 Jan 2021 07:47:19 GMT}), delete(Set(0) {})
[main 2021-01-06T07:47:19.449Z] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[main 2021-01-06T07:47:19.467Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:19.515Z] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('storage.serviceMachineId','6cec377b-5c13-4beb-b3ee-4f963b2b00ed'),('telemetry.lastSessionDate','Wed, 06 Jan 2021 07:44:42 GMT'),('telemetry.currentSessionDate','Wed, 06 Jan 2021 07:47:19 GMT')
[main 2021-01-06T07:47:19.516Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:19.517Z] [storage state.vscdb] Trace (event): END TRANSACTION
[main 2021-01-06T07:47:19.640Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:19.843Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:21.239Z] [File Watcher (node.js)] [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:21.452Z] [File Watcher (node.js)] >> normalized [CHANGED] c:\Users\XXXX\AppData\Roaming\Code - Insiders\User\globalStorage
[main 2021-01-06T07:47:22.173Z] resolveShellEnv(): skipped (Windows)
(node:4152) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-01-06T07:47:49.155Z] update#checkForUpdates, state =  idle
[main 2021-01-06T07:47:49.155Z] update#setState checking for updates
[main 2021-01-06T07:47:49.156Z] RequestService#request https://update.code.visualstudio.com/api/update/win32-x64/insider/9b6aaf1e86c8fec4c86c664edf5f713583c70fe5
[main 2021-01-06T07:47:49.221Z] Error: net::ERR_PROXY_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:6508)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[main 2021-01-06T07:47:49.222Z] update#setState idle
[main 2021-01-06T07:47:49.281Z] [VS Code]: detected unresponsive
[main 2021-01-06T07:48:09.555Z] Lifecycle#window.on('closed') - window ID 1
[main 2021-01-06T07:48:09.555Z] Lifecycle#onWillShutdown.fire()
[main 2021-01-06T07:48:09.559Z] [storage state.vscdb] close()
[main 2021-01-06T07:48:09.632Z] Lifecycle#app.on(window-all-closed)
[main 2021-01-06T07:48:09.632Z] Lifecycle#app.on(before-quit)
[main 2021-01-06T07:48:09.632Z] Lifecycle#onBeforeShutdown.fire()
[main 2021-01-06T07:48:09.633Z] [WindowsStateHandler] onBeforeShutdown {
  lastActiveWindow: {
    workspaceIdentifier: undefined,
    folder: undefined,
    backupPath: 'C:\\Users\\XXXX\\AppData\\Roaming\\Code - Insiders\\Backups\\1609918891961',
    remoteAuthority: undefined,
    uiState: [Object: null prototype] {
      mode: 1,
      x: 128,
      y: 0,
      width: 1024,
      height: 684
    }
  },
  lastPluginDevelopmentHostWindow: undefined,
  openedWindows: []
}
[main 2021-01-06T07:48:09.633Z] Lifecycle#app.on(will-quit)

We have also tried to install VS Code 1.26.0. But, even that is not working properly. We are able to launch it after the installation but, the VS Code extensions are not working properly. So, we aren't able to run anything from VS Code.

Please, suggest us a version of VS Code that will work with the specified system configuration. Our first choice will be to go with VS Code version 1.51.0. So, if there is any way to install that version then that will be our first choice.

**Comment by bpasero** [comment]
I do not think we support this OS, but maybe Deepak you know more about compatibility.

**Comment by ayankumaar** [comment]
I was just checking, any update on this issue ?

**Comment by ayankumaar** [comment]
I have one version of Windows Server 2012 R2. **There VS Code version 1.45.1 is working fine**. 

There the configuration is:
Processor: Intel(R) Xeon(R) Gold 6132 CPU @ 2.60 GHz 2.59 GHz (2 Processors)
Installed Memory (RAM) : 32 GB
System Type: 64 bit, x64 based processor
Hard disk size: 200 GB

But, I have another version of Windows Server 2012 R2. **There VS Code 1.26.0 and 1.51.0 are not working. I haven't tried 1.45.1 here.**
There the configuration is:
Processor: Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80 GHz 2.80 GHz (2 Processors)
Installed Memory (RAM) : 8 GB
System Type: 64 bit, x64 based processor
Hard disk size: 120 GB

Both the machine has .NET Framework 4.7.2 installed.

I was just wondering why it is not working in the second machine ? Can it be related to the Processor and RAM ? If not then should I try VS Code 1.45.1 in the second machine ?

**Comment by GitMensch** [comment]
You may want to try running with `code --verbose --disable-gpu` and if that still does not work retry with `code --verbose --disable-gpu --disable-extensions`.

Note: your log says it tries to run an insider build, I highly suggest using plain 1.51.0 in your tests.

**Comment by deepak1556** [comment]
Are you able to open https://www.electronjs.org/fiddle on your system ?

Can you start vscode with `--crash-reporter-directory <some-path>/vscode-crash` and attach the crash dmps generated at that path once vscode quits.
