### ISSUE TITLE
Type Ahead isn't "on" for cursor movement when using PowerShell on non-Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#113853]
Version: 1.53.0-insider
Commit: 4a875e23d20b64504a818834f3fa4c40adb8d480
Date: 2020-12-21T12:32:43.927Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 20.2.0

This seems to be because right arrow in PowerShell on non-Windows emits `\x1bOC` instead of [what the ANSI spec says](https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_output_sequences) which is `\x1b[C`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Steps to verify?

**Comment by TylerLeonhardt** [comment]
It'll be easiest to see this in Codespaces or Remote probably (or throttle the CPU via dev tools maybe):

* Install PowerShell on non-Windows: https://github.com/PowerShell/PowerShell#get-powershell
* Set it as the default shell: `"terminal.integrated.shell.linux": "pwsh"`,
* Open a terminal and type really fast

You should see characters start grey and then become colorized. This is the work of typeahead.

**Comment by JacksonKearl** [comment]
I mean what does `"on" for cursor movement` mean in the context of TypeAhead?

**Comment by TylerLeonhardt** [comment]
This would be transparent to the end user, unfortunately. The true test is verifying that when you use the left or right arrow key that this code block gets hit:

https://github.com/microsoft/vscode/blob/3f3e35bf17ecf423dca5dc613e7c32474a8f9f16/src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts#L1451-L1458

**Comment by TylerLeonhardt** [comment]
ok I think ive got a valid test...

1. Open the vscode repo in Codespaces
2. launch `pwsh`
3. type asdf asd fasdf asd fasd fas dfsd afsdf a sadfsadf a sdfaf sdsaf dsadf to fill the prompt a bit
4. Hit left arrow a few times to be in the middle of that ^
5. do: Ctrl+LeftArrow a few times

TypeAhead assumes that `Ctrl+LeftArrow` moves the cursor by a word (tbh this is a bad assumption... but since 95% of the time Codespaces will use bash or zsh... it's slightly less bad of an assumption I guess)
PowerShell doesn't use `Ctrl+LeftArrow` to move back a word so what you see is:

TypeAhead guesses by moving the cursor back a word
PowerShell responds saying "the cursor didn't go anywhere"
TypeAhead's prediction is reverted and the cursor goes back to where it was

**Comment by TylerLeonhardt** [comment]
If TypeAhead was off, by doing:

```json
"terminal.integrated.localEchoLatencyThreshold": -1
```

The word jump wouldn't happen at all
