### ISSUE TITLE
Add an API to access the problems view

### ISSUE THREAD

**Issue by Gama11** [Microsoft/vscode#11399]
I'm looking for a way to show the problems view in an extension. There's the `workbench.actions.view.problems` command, but since it's a toggle, I would also need a way to check if the view is currently opened or not, which does not seem to exist.

The API should probably at least support:
- showing
- hiding
- checking the current visibility of
- clearing 

the problems view.

**Comment by dbaeumer** [comment]
- clearing. This should be done using the diagnostic collections.

**Comment by Simn** [comment]
> clearing. This should be done using the diagnostic collections.

What exactly does this mean?

**Comment by jrieken** [comment]
Diagnostics are fed into the system by using a [Diagnostic collection api](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2761). Only with that in hand you can remove diagnostics

**Comment by jrieken** [comment]
@Gama11 Can I ask what you are trying to build with this? Our rule is to only expose a little of the UX state. Are you planning on having a command that reveals/hides the problems view based on some state?

**Comment by Gama11** [comment]
In the Haxe extension, we have a command called "Run Global Diagnostics Check". This performs some static analysis on the entire workspace, and the results are shown in the problems view. This means the user needs to _know_ where the results will be shown and he then has to manually open the view.

It would make for a much better UX if the problems view could be opened by the extension after the check is complete.

**Comment by jrieken** [comment]
I see - so maybe it's enough to have show/hide commands in addition to the toggle command. fyi @sandy081

**Comment by sandy081** [comment]
If this issue is all about these two commands, I can own it otherwise I ld create a separate issue for commands

**Comment by Simn** [comment]
Show/hide is sufficient for us.

I feel like having a toggle without an ability to check state is not exactly useful, but that's not very important.

**Comment by KalitaAlexey** [comment]
Also checking the current visibility isn't bad.
Why don't we add it?

**Comment by dakaraphi** [comment]
Will a context also be added to the key bindings so that key bindings can be set based on the problems view being shown?

**Comment by rajasimon** [comment]
What is the status of this issue. Any early code I can access to test my extension?

**Comment by sandy081** [comment]
Sorry this is postponed to next milestone.

**Comment by zjhmale** [comment]
Can't wait to see the new feature :)

**Comment by sean-mcmanus** [comment]
Our extension just wants a show command instead of the toggle (which can hide when we don't want it). https://github.com/Microsoft/vscode/issues/31690 .

If this change is made, the existing "Show Problems" button that appears when doing a "Launch Extension" with build errors should be changed to do an actual show instead of toggle (I've accidentally hid my problems window many times).

**Comment by pltrant** [comment]
Yes, please either add a method to get the current state of the Problems view (so we can check it to know if issue show problems command or not) or add separate hide and show Problems view commands.

**Comment by sandy081** [comment]
Here are the commands 

- `workbench.action.problems.show` : Show Problems view
- `workbench.action.closePanel`: Close the view

**Comment by sandy081** [comment]
Verify that command `workbench.action.problems.show : Show Problems view` shows problems view always.

**Comment by pltrant** [comment]
FYI for anyone who tries to implement these.  `workbench.action.problems.show` was changed to `workbench.action.problems.focus` per https://github.com/Microsoft/vscode/issues/37717.

**Comment by sandy081** [comment]
@pltrant Yes, thanks for mentioning and reminding.
