### ISSUE TITLE
A great idea

### ISSUE THREAD

**Issue by NateLing** [microsoft/vscode#113944]
Hi, i love vscode

When i create an js module , 
step 1: need to open the context menu
step 2: need to create a folder
step 3: create an index.js or index.ts  file

Now, Will we to offer an option "create module" for the context menu that can create a folder with an index.ts file? so i just to fill a name of the folder.

Next, some programe language has itself module.
As i know, rust mod default file is mod.rs rust lib default file is lib.rs

Can we offer an api to LSP, so extendsion can set the create module way by itself?

**Comment by mjbvz** [comment]
Seems worth exploring with an extension first. If enough extensions/languages need this sort of thing, we could consider it for VS Code / LSP

Also please give issues a descriptive title
