### ISSUE TITLE
Flaky test: IndexDB Filesystem

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#113911]
* failed on Windows in https://github.com/microsoft/vscode/runs/1652966527
```
 6423 passing (3m)
  38 pending
  2 failing

  1) IndexedDB File Service
       createFile (batched):
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) IndexedDB File Service
       "after each" hook for "createFile (batched)":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
```

* failed on macOS in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=99338&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d55b56b-c0b2-5f64-1c6a-62c9163a0d5b&l=7746
```
  6437 passing (4m)
  31 pending
  1 failing

  1) IndexedDB File Service
       createFile (batched):
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

* failed on Windows in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=99384&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=6ad30dce-518e-54c1-94da-00d19cce9354&l=7748
```
  6431 passing (3m)
  38 pending
  1 failing

  1) IndexedDB File Service
       createFile (batched):
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by sandy081** [comment]
Assigning to @JacksonKearl as he expected that this can be flaky. 

Chatted with @alexdima about this and I agree with him that a functionality test shall be different from performance test. I would recommend following:

- Have a unit test that tests create file in batches but with smaller number of files
- Have a separate perf unit test to validate the performance and we can skip it to run on builds. We can enable it locally if needed to check perf.

**Comment by alexdima** [comment]
Totally agree. We shouldn't have unit tests that validate performance because we run them a gazillion times locally and on the build machine and it isn't useful as they just burn CPU. We should have them skipped or something and they can be executed manually whenever a change is made to the indexdb code to validate that the perf was not affected.

**Comment by JacksonKearl** [comment]
Disabled the test for now.

**Comment by alexdima** [comment]
Thank you @JacksonKearl !
