### ISSUE TITLE
Opinion: kinda disturbed by the hubris of closing this without giving any consideration for the impact on UX.

### ISSUE THREAD

**Issue by jace4511** [microsoft/vscode#113939]
Opinion: kinda disturbed by the hubris of closing this without giving any consideration for the impact on UX.

Case: I am setting up VSCode and went to install the Terminals Manager Extension. To complete the install, I had to edit the extension config. I did this by running the command to open the json config in a new tab, then attempted to switch between that tab and the extension's marketplace page tab to reference the config guide.

Result: Horrible UX from the marketplace tab constantly reloading from the slightest and most miniscule tab switch. What is more valuable - a little bit of RAM, or my time and patience?

_Originally posted by @Hadakajime in https://github.com/microsoft/vscode/issues/36310#issuecomment-755777133_

**Comment by mjbvz** [comment]
The rational was explained in https://github.com/microsoft/vscode/issues/36310#issuecomment-493633050

You are free to disagree with the choice, but just because you have a different option does not mean the other side is acting in bad faith
