### ISSUE TITLE
New macOS Icon

### ISSUE THREAD

**Issue by makzr** [Microsoft/vscode#11392]
The icon of the macOS client doesn't look mac-like.

You do not have to implement 100% of the macOS icon guidelines https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html

Some small fixes could help to align it with other macOS icons:
1. Make it a little smaller, it's too big
2. Add some color gradient
3. Add a little drop shadow

**Comment by wangweixuan** [comment]
See also #11274. There is an example contributed.

**Comment by chrisdias** [comment]
Closing all icon issues against https://github.com/Microsoft/vscode/issues/6607
