### ISSUE TITLE
Extension's webview does'nt ask for permission for user media.

### ISSUE THREAD

**Issue by sastaachar** [microsoft/vscode#113916]
Issue Type: <b>Bug</b>

Extension webview does'nt ask for permission for user media ,

The vscode api for extensions provides us with methods to create webviews , but we can run scripts through this webview and get access to users media devices such as their camera and microphone. For my local environment no permissions were asked to access these resources.

I've developed a basic extension to demonstrate this issue , you can find it here : - https://github.com/sastaachar/vscode-demo

To reproduce , clone the repo , install node and npm , 
npm i  -> to install all dependencies
npm run watch -> to compile and watch for changes

After this you can open the debug window to run the extension locally.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.20GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-18.04/mnt/e/Projects/audioComments --remote=wsl+Ubuntu-18.04 --crash-reporter-id c3386ab5-fa56-4cd3-bc21-6df076e205b4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2901)|
|Memory (System)|15.90GB (5.20GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
javascript-ejs-support|Dig|1.3.1
remote-wsl|ms-|0.52.0
env-cmd-file-syntax|Nix|0.2.2
JavaScriptSnippets|xab|1.8.0
spellcheck|Bel|0.0.1
simple-react-snippets|bur|1.2.3
turbo-console-log|Cha|2.1.6
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
cpptools|ms-|1.1.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
svelte-vscode|sve|102.8.0
sass-indented|syl|1.8.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30237718
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30236574
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt875:30241730

```

</details>

**Comment by mjbvz** [comment]
This is blocked in browsers: `NotAllowedError: Permission denied` (and also for all iframe based webviews on desktop)

But does to skip the prompt in normal electron webviews (although on Mac it also doesn't not actually seem to record anything for me, possibly because VS Code does not actually have microphone permissions)

**Comment by sastaachar** [comment]
Yes  for mac it just denied the permission , and logged the error that it could not find a media device, but in a WSL and Linux environment it doesn't deny them.

**Comment by roblourens** [comment]
I see this in the webview developer tools, what is expected exactly? `DOMException: Permission denied`

**Comment by mjbvz** [comment]
@roblourens  Yes the request should be blocked without any prompt. `Permission denied` sounds like the correct error
