### ISSUE TITLE
Graphics rendering error in User Interface of VS Code

### ISSUE THREAD

**Issue by mr-ro-cha** [microsoft/vscode#113942]
Issue Type: <b>Bug</b>

Visual Studio UI is showing lots of lines, making text difficult to read

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.95GB free)|
|Process Argv|--crash-reporter-id 15bcd44d-fc6b-4ff8-8c97-195079edda39|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244cf:30236574
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt875:30241730

```

</details>

**Comment by mr-ro-cha** [comment]
![image](https://user-images.githubusercontent.com/16214503/103841220-0de39300-5061-11eb-9918-d0356f5ead97.png)

**Comment by rzhao271** [comment]
Does launching code with `--disable-gpu` fix the issue?

Might be related to https://github.com/microsoft/vscode/issues/92586#issuecomment-727562935

**Comment by mr-ro-cha** [comment]
Yes, that resolves the issue. Thanks!
