### ISSUE TITLE
WebView - update extension-guides/webview outlining that the webview content might not yet be fully loaded and postMessage can therefore fail if called immediately after updating the content (tags: blank webview, webview not rendering)

### ISSUE THREAD

**Issue by tintinweb** [microsoft/vscode#113904]
I've been trying to fix an issue where my webview content wouldn't render the first time the webview is created and finally found a solution that I'd recommend to mention in the official webview extension guide.

#### background

* I had multiple reports in https://github.com/ConsenSys/vscode-solidity-metrics/issues/6 and https://github.com/tintinweb/vscode-interactive-graphviz/issues/2 that the webview sometimes does not render. 
* It wasn't completely fixed by adopting the `asWebViewUri` API https://github.com/tintinweb/vscode-interactive-graphviz/issues/7
 
#### the issue

I finally tracked it down to likely being a timing issue because this is how I render reports:
  1. I create a web view panel pushing static content
  2. then the content is updated. scripts are linked as local file resources in HTML head
  3. assuming the page fully loaded I then immediately after creating the webview panel, `postMessage` content to be rendered to the webview. This is supposed to be picked up by the event handler that is registered in one of the linked javascript files.

Here's the relevant code that is spawning a webview and immediately post-messaging after revealing it:

https://github.com/ConsenSys/vscode-solidity-metrics/blob/fb21dc4a2016ab3e68d8390404c61be3c7fc5780/src/extension.js#L69-L77

As the webview renders asynchronously from the extension, updating the webview content gives no guarantee about the state of the webview and if it is fully loaded. If the extension continues to `postMessage` right after updating the content the message might not be picked up by the content script as it's event handler might not yet be registered. 

Worse, this is kinda hard to debug as it may not always occur. For example, it mainly manifest in my test cases right after activating my extension the first time.

#### fix

I've fixed this now by adding a callback from the webview that notifies the extension that the page fully loaded. the extension then attempts to `postMessage` again providing the data to be rendered in the webview.

here's the webview `onload` callback:

https://github.com/ConsenSys/vscode-solidity-metrics/blob/fb21dc4a2016ab3e68d8390404c61be3c7fc5780/websrc/main.js#L330-L334

#### request

Assuming that others might have the same issues when first dealing with webviews and message passing I request

* a note to be added to the https://code.visualstudio.com/api/extension-guides/webview that after updating the views content, content is loaded asynchronously and it is not guaranteed that all scripts loaded right after updating it. In this case a callback pattern should be implemented where the webview content notifies the extension that it finished loading/rendering the static content.
* an `onload` callback to be provided by the vscode-webview that can be directly accessed from the extension without having to add `window.onload -> postMessageToExtension` boilerplate code to the html content.

**Comment by mjbvz** [comment]
The actually behavior you describe sounds expected me to me. Determining when a webview is actually ready is best left up to each extension IMO (for example, does ready mean that the dom has finished loading or that all linked assets have also loaded?)

I haven't seen other reports of people running into this so I can't say if this is a common issue or not but we would accept a PR that add a  note in the webview guide if you think it could help others avoid frustration. Here's the webview docs: https://github.com/Microsoft/vscode-docs/blob/master/api/extension-guides/webview.md

**Comment by mjbvz** [comment]
Closing this since there hasn't been any recent activity. Again, it sounds like the feature is working as expected but we would take a PR on the docs if it would clarify this behavior
