### ISSUE TITLE
Settings Sync: Support syncing workspace state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#113996]
Settings Sync: Support syncing workspace state

**Comment by alefragnani** [comment]
With the recent addition of [Virtual Workspaces](https://code.visualstudio.com/updates/v1_56#_remote-repositories-remotehub), it would be really interesting if its workspace state could be synced too. 

I mean, if I have some repository _already cloned_ on any of my machines and I decide to open it _virtualy_ on another machine, VS Code could sync its state, just like it will do when I open it on **Codespaces**.

Doing so, no matter if I’m opening the repository on _virtually_ or not, VS Code would understand it as being the same.

Thank you
