### ISSUE TITLE
Information about functions overflowing it's container

### ISSUE THREAD

**Issue by lolfail** [microsoft/vscode#113929]
When using functions in a javascript file, the IDE gives information about what goes into the function as parameter and what the function does, this information overflows the darker colored box that is supposed to contain the text.
![image](https://user-images.githubusercontent.com/39534294/103813262-1a1b2080-5060-11eb-8274-5cee65f7169c.png)
I am on windows 7 pro.

**Comment by mjbvz** [comment]
Should be fixed in the current insiders
