### ISSUE TITLE
send willRenameFiles when change folder path.

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode#113925]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willRenameFiles
It says
```
	/**
	 * An array of all files/folders renamed in this operation. When a folder
	 * is renamed, only the folder will be included, and not its children.
	 */
        files: FileRename[];
```

But it seems rename folder would not send such message.

**Comment by bpasero** [comment]
I verified that the `vscode.workspace.onWillRenameFiles` event is fired for folders, so this is probably an LSP issue.

**Comment by ShuiRuTian** [comment]
Thanks so such for the verify.
I guess this is due to LSP client `document select`, which only selects specific  file type or extension, so folder changes are just passed.

**Comment by dbaeumer** [comment]
@ShuiRuTian see my comments in the issue you open in the LSP repository.
