### ISSUE TITLE
Fira Code broken on every VSC startup

### ISSUE THREAD

**Issue by mohan-ys** [microsoft/vscode#113949]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

I have the below setting in my settings.json file 
"editor.fontFamily": "'Fira Code', Consolas",
"editor.fontWeight": "400",
"editor.fontLigatures": true,

I have installed the font just for me since i do not have the admin rights to install it to 'all users'.
The font works fine in MS word but in not working in VSC after restart (it was working fine before the restart)

Does this issue occur when all extensions are disabled?: Yes

This issue was already raised (with the exact same title & number #92744 ) but closed with the resolution "Install Fira Code to all users". However, as I mentioned I don't have the rights to do that & would like this addressed for individual users. Hence reporting the issue again.

**Comment by alexdima** [comment]
@mohan-ys VS Code is built with Electron, which is built with Chromium. All font rendering in the editor is delegated ultimately to Chromium. If you open this test page in Chrome or the new Edge (based on Chromium), how does the text render? https://jsfiddle.net/wk0juteL/ Can you please include screenshots.

**Comment by mohan-ys** [comment]
@alexdima Below is the output of the text in Chrome Browser (I modified it a little because I installed 'Fira Code' mainly for the ligatures & also, these ligatures show 'Fira Code` accurately). 
![image](https://user-images.githubusercontent.com/54783631/103868035-572df400-50ee-11eb-8ebd-6fc4106b1e6f.png)

![image](https://user-images.githubusercontent.com/54783631/103868006-48474180-50ee-11eb-9fd1-1a1245b8b4d2.png)

Then I installed 'Fira Code' again & the result is below.
![image](https://user-images.githubusercontent.com/54783631/103868353-cc99c480-50ee-11eb-9acf-5b975692863f.png)

**Comment by mohan-ys** [comment]
OK! This issue has led me down a rabbit hole!
After I found this workaround (to install Fira Code after every restart of the the computer). Next time I restarted the computer (not VSC but the computer itself), I searched for Fira Code in the 'Available Fonts' & it was not there !!! I have no idea why. I have installed fonts recently just for myself (not for 'all users') & they are still available even after restart 
So, I opened MS word to see if the font was there & it was there!
![image](https://user-images.githubusercontent.com/54783631/103873957-919b8f00-50f6-11eb-9f83-9c66f21df48f.png)
Then I installed it again. It - as expected - showed up in both 'available font' search & MS word.
![image](https://user-images.githubusercontent.com/54783631/103874071-b8f25c00-50f6-11eb-8748-b62fcf7dac9d.png)
This got me even more intrigued. So, I restarted again & searched the FONTS folder this time. The font was there but still did not show-up in the 'available Fonts' search.
![image](https://user-images.githubusercontent.com/54783631/103874222-eb03be00-50f6-11eb-90a5-461476e73d1a.png)
Then I searched for the font right next to it. It shows up !
![image](https://user-images.githubusercontent.com/54783631/103874434-2605f180-50f7-11eb-918c-259e6f46d7b9.png)
Then I installed it again. It - as expected - it showed up in the 'available font' search.
![image](https://user-images.githubusercontent.com/54783631/103874365-12f32180-50f7-11eb-9287-60b2e2a1b2b6.png)

Now, I don't know what it going on.

**Comment by alexdima** [comment]
I agree that is super weird. This might be a bug, but it could also be some security thing or some corporate user policy that might be causing this. I'm sorry, I honestly don't know.

**Comment by jace4511** [comment]
> * VSCode Version: 1.52.1
> * OS Version: Windows 10
> 
> Steps to Reproduce:
> 
> I have the below setting in my settings.json file
> "editor.fontFamily": "'Fira Code', Consolas",
> "editor.fontWeight": "400",
> "editor.fontLigatures": true,
> 
> I have installed the font just for me since i do not have the admin rights to install it to 'all users'.
> The font works fine in MS word but in not working in VSC after restart (it was working fine before the restart)
> 
> Does this issue occur when all extensions are disabled?: Yes
> 
> This issue was already raised (with the exact same title & number #92744 ) but closed with the resolution "Install Fira Code to all users". However, as I mentioned I don't have the rights to do that & would like this addressed for individual users. Hence reporting the issue again.
