### ISSUE TITLE
allow to specify highlighted range in definition provider

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#113946]
I was trying to add a feature in Maven extension, which allow users to navigate to parent/dependency POM files with <kbd>ctrl + click</kbd>.

With the help of [definition provider API](https://github.com/microsoft/vscode/blob/01089c0a5052432594a177f90ad9f3148ec2a6a2/src/vs/vscode.d.ts#L2415-L2432), I managed to implement it, but the underline highlighting is not as expected. After pressing <kbd>ctrl</kbd>, **I want the whole string to be highlighted**, but I don't find any way to specify it in the response. Does vscode hardcode the delimiters?

#### Current behavior:
![image](https://user-images.githubusercontent.com/2351748/103844498-f940e280-50d4-11eb-8d5c-614d2f0a63fb.png)

#### Expected behavior:
Provider a way to include `.` and `-`, i.e. when hovering on `<version>` section, highlight `2.2.4.RELEASE` instead of `RELEASE` only, and in `<artifactId>` section, highlight the whole string with `-`.

**Comment by jace4511** [comment]
> I was trying to add a feature in Maven extension, which allow users to navigate to parent/dependency POM files with ctrl + click.
> 
> With the help of [definition provider API](https://github.com/microsoft/vscode/blob/01089c0a5052432594a177f90ad9f3148ec2a6a2/src/vs/vscode.d.ts#L2415-L2432), I managed to implement it, but the underline highlighting is not as expected. After pressing ctrl, **I want the whole string to be highlighted**, but I don't find any way to specify it in the response. Does vscode hardcode the delimiters?
> 
> #### Current behavior:
> ![image](https://user-images.githubusercontent.com/2351748/103844498-f940e280-50d4-11eb-8d5c-614d2f0a63fb.png)
> 
> #### Expected behavior:
> Provider a way to include `.` and `-`, i.e. when hovering on `<version>` section, highlight `2.2.4.RELEASE` instead of `RELEASE` only, and in `<artifactId>` section, highlight the whole string with `-`.

**Comment by jrieken** [comment]
Make your provider return a `DefinitionLink`/`LocationLink` (see https://github.com/microsoft/vscode/blob/0319fedae103b2d867fc02a2c9dd848a087ed8b4/src/vs/vscode.d.ts#L4971). That allows to define an origin selection range
