### ISSUE TITLE
Visualize change of peripheral variable while debugging

### ISSUE THREAD

**Issue by MasterTim17** [microsoft/vscode#113965]
Hello,
im debugging microcontrollers with VSC and Platformio. When values in variables and watch tab change, the change their color according to `debugView.valueChangedHighlight`. Please make this colorchange also available in peripherals tab
![grafik](https://user-images.githubusercontent.com/52961929/103872193-59805600-50ce-11eb-945e-6e7ac46314ff.png)

**Comment by weinand** [comment]
The "Peripherals" view is contributed by an extension and not part of VS Code.
