### ISSUE TITLE
Tasks are run relative to the first root vs the current root

### ISSUE THREAD

**Issue by brianlow** [microsoft/vscode#113941]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Setup two fake projects
   ```
    mkdir project-a
    mkdir project-b
    touch project-a/README.md
    touch project-b/README.md
   ```
2. Setup multi-root workspace
  * Open VSCode
  * File -> Add Folder to Workspace -> pick project-a
  * File -> Add Folder to Workspace -> pick project-b
  * Add custom task
      ```
      // tasks.json
      {
        "version": "2.0.0",
        "tasks": [
          {
            "label": "Test Task",
            "type": "shell",
            "command": "echo ${relativeFile}; echo ${workspaceFolder}"
          }
        ]
      }
      ```
2. Open project-**b**/README.md
3. Run tasks -> Test Task
```
Expected: > Executing task in folder project-b: echo              README.md; echo /Users/brian/dev/project-b <
Actual:   > Executing task in folder project-a: echo ../project-b/README.md; echo /Users/brian/dev/project-a <
                                             ^       ^^^^^^^^^^^^^                                         
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
> Add custom task

Which folder did you add the task to?

**Comment by brianlow** [comment]
@alexr00 how do you tell?

I had existing custom tasks, so to add this task I used:

* command palette -> Configure Tasks -> picked one of my tasks -> replaced the file contents

tasks.json is at: `~/Library/Application Support/Code/User/tasks.json`

**Comment by alexr00** [comment]
Looks like you configured a User task then, which means that this is the expected behavior (user tasks and multiroot workspaces aren't well integrated). If you want a task to run in a specific folder, you should add a tasks.json file in a .vscode folder in the folder you want the task to run in.

**Comment by brianlow** [comment]
Ok, thank you
