### ISSUE TITLE
VS Code Duplicate Icons (NOT DUPLICATE of existing Issue steps to replicate tested on separate mac with success)

### ISSUE THREAD

**Issue by Sergio16T** [microsoft/vscode#113955]
- VSCode Version:1.52.1
- OS Version: Mac OS Big Sur 

Duplicate Icons in Dock On Mac OS (This is not an exact duplicate of existing issue - I read through those and they did not have steps to reproduce I was able to replicate it on older mac with same OS and VS code version) Something to do with Shell commands  being installed with VS code 1 time in the downloads folder and then reinstalled again in the applications folder to enable the code . command from terminal . 

Steps to Reproduce:

1. VS code is installed in downloads folder 
2. Command P >Shell Command Install Code Command in Path 
3. Move VS Code from downloads folder to applications folder 
4. Code . command from terminal no longer works so I have to repeat step 2 to reinstall the Code Command in Path 
5. Run code . to open a directory with code in it 
6. Change directory to another code base and run code . from terminal again (this leads to duplicate icons in desktop) 

Please help. Not sure how to fix not enjoying the duplicate VS code icons. 
<img width="186" alt="Screen Shot 2021-01-06 at 11 37 36 PM" src="https://user-images.githubusercontent.com/47071119/103855379-2c08bd80-5078-11eb-8739-464c2de57e4a.png">

Does this issue occur when all extensions are disabled?: Yes/No Yes 

Similar to Issue #60579 but this includes steps to reproduce. Hoping to receive guidance if it's having to do with shell command perhaps I can fix it with some commands that  I do not know. Otherwise I hope this report is helpful if it's a potential bug fix I imagine the steps to reproduce will help. Not sure it's OS mac bug or VS code bug.

**Comment by rzhao271** [comment]
Seems like a duplicate to me, for example https://github.com/microsoft/vscode/issues/60579#issuecomment-732163120 also suggests running `code .` twice, and I think that's the main issue.

Are you unable to reproduce the issue if you only do steps 5 and 6?
