### ISSUE TITLE
No Internet connection We cannot connect to the Extension Marketplace at this time -- No Proxy, Reinstalled

### ISSUE THREAD

**Issue by h3seas0n** [microsoft/vscode#113974]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 20H2

Steps to Reproduce:

1. Open Visual Studio Code
2. Open Internet-dependent utilities

Does this issue occur when all extensions are disabled?: Yes/No

Yes, no extensions installed.

When searching in "Search Extension in..." the error "We cannot connect to the extensions Marketplae at this time, please try again later." pops up. 

When installing directly from the Web Extension-Store (website): error: "XHR Failed"

Developer tools:
Console: 
![image](https://user-images.githubusercontent.com/61113049/103879151-c2200080-50d7-11eb-9220-7065933de1b3.png)
Network when searching in "extensions": 
![image](https://user-images.githubusercontent.com/61113049/103879367-0c08e680-50d8-11eb-8168-d4976ded2a90.png)

Already done:
- Reinstall VSC 
- Test on VSC-Insiders (same issue)
- reset windows network settings
- change dns to 8.8.8.8, 8.8.4.4

**Comment by sandy081** [comment]
I think you might be behind a proxy server which is blocking you to connect to Marketplace.

**Comment by h3seas0n** [comment]
I am not behind a proxy server, just in my home network. This just suddenly stopped working mid programming, which is quite strange.

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by h3seas0n** [comment]
Hey @chrmarti , thanks for your response, here it is:
[netlog.zip](https://github.com/microsoft/vscode/files/5786293/netlog.zip)

**Comment by chrmarti** [comment]
It mentioned `download.microsoft.com` as proxy which seems wrong. Have you set that somewhere as proxy?
![image](https://user-images.githubusercontent.com/9205389/103999915-d29aae80-519d-11eb-8fca-4b33292481b3.png)

**Comment by h3seas0n** [comment]
Oh, I set that as an environment variable for the Live Share extension, removing it seems to fix the errors. Thanks!
