### ISSUE TITLE
Settings Sync does not work

### ISSUE THREAD

**Issue by EvasiveXkiller** [microsoft/vscode#113988]
Issue Type: <b>Bug</b>

I am trying to sync the settings between multiple computers with GitHub but it does not even start to sync. Followed the official guide but still getting the same error.

I get this error after logging into GitHub:
"Error while turning on Settings Sync. Please check [logs](command:workbench.userDataSync.actions.showLog) for more details."

The console output is not helpful either:

[2021-01-07 22:27:18.022] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-01-07 22:27:18.022] [userDataSync] [info] Auto Sync is disabled.
[2021-01-07 22:31:09.447] [userDataSync] [info] Did reset the local sync state.
[2021-01-07 22:31:09.683] [userDataSync] [info] GlobalState: Skipped synchronizing globalstate as it is disabled.
[2021-01-07 22:31:09.819] [userDataSync] [info] Settings: Stopped synchronizing settings.
[2021-01-07 22:31:09.819] [userDataSync] [info] Keybindings: Stopped synchronizing keybindings.
[2021-01-07 22:31:09.819] [userDataSync] [info] Snippets: Stopped synchronizing snippets.
[2021-01-07 22:31:09.821] [userDataSync] [info] Extensions: Stopped synchronizing extensions.

Would be great if there is a solution for this.
Thanks.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.1
prettier-vscode|esb|5.8.0
remote-wsl|ms-|0.52.0
cpptools|ms-|1.1.3
vscode-open|san|0.1.0
quokka-vscode|Wal|1.0.335

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt875:30241730

```

</details>

**Comment by sandy081** [comment]
May I know at which point during the settings sync turn on flow you are getting the error?

**Comment by EvasiveXkiller** [comment]
Steps that I followed:

1.  Click on the settings icon (bottom left), then "Turn on Settings Sync"
2. Click on "Turn on" after the warning about settings sync being a preview feature.
3. The settings sync menu comes up on the top. Click on the "Please sign in to synchronize your data across devices"
4. Click on "Sign in with GitHub"
5. The default web browser opens with the login page to GitHub.
6. After logging in, the web browser redirects back to Visual Studio Code. This is where the _"Error while turning on Settings Sync. Please check logs for more details."_ error shows up.
7. The console is the same as the original post.

**Comment by sandy081** [comment]
Thanks for the steps. I suspect you have sign in issue. Can you please check following logs and see if there are any errors there?

- F1 > Open View > Log (Window)
- F1 > Open View > Github Authentication 

Also check in your Accounts dropdown if it shows the account you signed in?

**Comment by EvasiveXkiller** [comment]
I have found the problem.
Turns out that my settings.json has some warnings about and extra "}" in the end. The log window did show that error.
Removing that did help solve the issue and now sync is working as expected.
Thanks.

**Comment by sandy081** [comment]
Also fixed to show the error in settings sync log. 

To verify:

- Have errors in settings file
- Turn on settings and make sure you see following error notification
![image](https://user-images.githubusercontent.com/10746682/104003594-e4328500-51a2-11eb-900f-b1c8cb1d1344.png)
- Click on show logs link and make sure you see the error in the logs

**Comment by laskel** [comment]
I have the same problem


[2021-01-08 14:28:03.534] [userDataSync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2021-01-08 14:28:03.534] [userDataSync] [info] Auto Sync is disabled.
[2021-01-08 14:28:19.835] [userDataSync] [info] Did reset the local sync state.
[2021-01-08 14:30:55.216] [userDataSync] [info] Did reset the local sync state.
[2021-01-08 14:31:24.488] [userDataSync] [info] Did reset the local sync state.

**Comment by EvasiveXkiller** [comment]
> Also fixed to show the error in settings sync log.
> 
> To verify:
> 
> * Have errors in settings file
> * Turn on settings and make sure you see following error notification
>   ![image](https://user-images.githubusercontent.com/10746682/104003594-e4328500-51a2-11eb-900f-b1c8cb1d1344.png)
> * Click on logs link and make sure you see the error in the logs

The logs link did not work on my version though. It does not link to anywhere

**Comment by sandy081** [comment]
This fix is currently available only on insiders, so the stable build you are using might still have the issue (logs not showing the error). Please try insiders to check the fix - https://code.visualstudio.com/insiders/

**Comment by EvasiveXkiller** [comment]
/verified

Thanks!
