### ISSUE TITLE
Messes with Paths

### ISSUE THREAD

**Issue by ishfaqfariq** [microsoft/vscode#113964]
I'm using kali linux latest version. 
![Screenshot_2021-01-07_13-32-31](https://user-images.githubusercontent.com/30369065/103869915-d3273c80-50ec-11eb-8609-58ac377824f5.png)
And after installing VSC, the drive paths on my desktop are opening in VSC. The paths for drives on my desktop opens just as if its a text file. Its just happing on desktop. I can access my drives from toolbar though. But still its quite strange and uncomfortable. Kindly Check it out.

**Comment by bpasero** [comment]
This does not sounds like a Linux distribution we support officially, please try with one of: https://code.visualstudio.com/docs/supporting/requirements

**Comment by ishfaqfariq** [comment]
Its debian based. And VSC supports Debian, I used the docs for the installation and configuration.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ishfaqfariq** [comment]
Let me check this one, and I'll let you know about the issue.

**Comment by bpasero** [comment]
Thanks
