### ISSUE TITLE
"Duplicating files" on changing file name case

### ISSUE THREAD

**Issue by SergeyBeloglazov** [microsoft/vscode#113957]
I have changed only case of one letter (renamed file.php to File.php) and duplicate results appeared:
- in search/replace in explorer
- in find declaration in PHP Intelephense plugin
They shows two results: in file.php and in File.php.
If I make a replacement, it applies twice.
SFTP plugin sends File.php to ..../file.php on remote side.

Reloading VSC doesn't help.

- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Rename file.php to File.php
2. Search/search and replace, use PHP Intelephense plugin for finding declaration, being in renamed file, upload using SFTP plugin

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by SergeyBeloglazov** [comment]
I found a workaround: delete **C:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage\<workspace_the_right_directory>**
It helped me.
https://github.com/microsoft/vscode/issues/12448#issuecomment-655001292
The problem source, as I think is also there:
https://github.com/microsoft/vscode/issues/12448#issuecomment-639278969

> For example, opening a file /some/path/file.css and /some/path/FILE.css would result in just 1 editor opening. Internally we introduced the notion of "canonical" URIs, meaning that the first time a file is opened, we take the casing for granted and anytime a different case is opened, we use the first one.

So, if you will rename the file, changing only the case of some letters, internally it still have the old name, until you clear VSC workspace database.
If it's a complex cross-platform problem, I suggest to refresh internal names on pressing a refresh button in file explorer.

**Comment by isidorn** [comment]
I can not reproduce this with latest vscode insiders
Can you reproduce without the PHP extension using vscode insdiers 
https://code.visualstudio.com/insiders/

**Comment by SergeyBeloglazov** [comment]
The bug is reproduced with all extensions disabled.
Tell me, please, will "VSC insiders" replace my VSC?
It says "Insiders has the most recent code pushes and may lead to the occasional broken build."
I don't want a broken build. Can I install it separately?

**Comment by isidorn** [comment]
Yes you can install it seperatly

**Comment by SergeyBeloglazov** [comment]
I reproduced the problem in VSC Insiders.
I made a new installation. I didn't install any extension.
![image](https://user-images.githubusercontent.com/74024346/106388372-3f951300-63ef-11eb-97d9-fe03a7c55c61.png)

**The steps to reproduce the bug:**
1) I opened the directory with 1 test PHP file
![image](https://user-images.githubusercontent.com/74024346/106388183-6d2d8c80-63ee-11eb-9235-7a6a36283ddd.png)
2) Saved the workspace
![image](https://user-images.githubusercontent.com/74024346/106388200-820a2000-63ee-11eb-9fb3-9215ebc22c3b.png)
![image](https://user-images.githubusercontent.com/74024346/106388212-8e8e7880-63ee-11eb-93c9-6bad1f07de77.png)
Everything is fine, the search finds well only one item:
![image](https://user-images.githubusercontent.com/74024346/106388223-9c43fe00-63ee-11eb-8a7a-12f4dae7d3e1.png)
3) Then I changed the case of the first letter of the file name to uppercase in the Windows Explorer
![image](https://user-images.githubusercontent.com/74024346/106388284-d6150480-63ee-11eb-98cf-c474b57e6b39.png)
4) It was changed in the explorer panel, but left in lowercase in the editor
![image](https://user-images.githubusercontent.com/74024346/106388291-de6d3f80-63ee-11eb-8451-7c0510f41670.png)
5) The search could find only one item in a lowercase file  (which didn't exist at that time) by now
![image](https://user-images.githubusercontent.com/74024346/106388332-0b215700-63ef-11eb-9af2-8a5ef05ea5d8.png)
6) I reopened the file
![image](https://user-images.githubusercontent.com/74024346/106388339-14aabf00-63ef-11eb-8f0d-4dcca98151d2.png)
7) Now the serach started finding two items in two files: with lowercase and uppercase file names
![image](https://user-images.githubusercontent.com/74024346/106388349-242a0800-63ef-11eb-8b74-13e40156821d.png)
