### ISSUE TITLE
Don't copy the empty line

### ISSUE THREAD

**Issue by shekari-ah** [microsoft/vscode#113963]
When `editor.emptySelectionClipboard` enables and nothing has been selected, you can copy the current line.  
now the problem is: why do we have to copy the empty line in this situation?

it's been bothering me since then, I think you have to check the line content before doing this action.

p.p: I would like to do this myself if you help me.

**Comment by shekari-ah** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Breakpoint moves with copy line up/down action (#75426)](https://www.github.com/microsoft/vscode/issues/75426)

Nope, it's not

**Comment by alexdima** [comment]
The setting `editor.emptySelectionClipboard` has the exact purpose of controlling what Ctrl+C does on an empty line.

If the setting is true (the default), pressing Ctrl+C on an empty line will place `\n` in the clipboard.
If the setting is false, pressing Ctrl+C on an empty line will not write anything to the clipboard.
