### ISSUE TITLE
Add ExceptionInfo Request handler

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode#113921]
It _seems_ like I should be able to simply make the following change to mock-debug to handle the `ExceptionInfo` request:
```diff
diff --git a/src/mockDebug.ts b/src/mockDebug.ts
index 08b770f..b2325b8 100644
--- a/src/mockDebug.ts
+++ b/src/mockDebug.ts
@@ -149,6 +149,8 @@ export class MockDebugSession extends LoggingDebugSession {
                // make VS Code provide "Step in Target" functionality
                response.body.supportsStepInTargetsRequest = true;
 
+               response.body.supportsExceptionInfoRequest = true;
+
                // the adapter defines two exceptions filters with support for conditions.
                response.body.supportsExceptionFilterOptions = true;
                response.body.exceptionBreakpointFilters = [
@@ -404,6 +406,20 @@ export class MockDebugSession extends LoggingDebugSession {
                this.sendResponse(response);
        }
 
+       protected exceptionInfoRequest(response: DebugProtocol.ExceptionInfoResponse, args: DebugProtocol.ExceptionInfoArguments) {
+               response.body = {
+                       exceptionId: 'exceptionId',
+                       description: 'This is a descriptive description.',
+                       breakMode: 'always',
+                       details: {
+                               message: 'This is a descriptive message.',
+                               typeName: 'ErrorException',
+                               stackTrace: '1. Foo\n2. Bar',
+                       }
+               }
+               this.sendResponse(response);
+       }
+
        protected stepInRequest(response: DebugProtocol.StepInResponse, args: DebugProtocol.StepInArguments): void {
                this._runtime.stepIn(args.targetId);
                this.sendResponse(response);

```
`exceptionInfoRequest` is being called and afaict the response conforms to the DAP specs, but VSCode (insiders or stable) doesn't display any exception details inline:

![image](https://user-images.githubusercontent.com/6735977/100286688-85f36f00-2f73-11eb-9a39-55fdc3682ca3.png)

I was expecting something like
![image](https://user-images.githubusercontent.com/6735977/100286817-c05d0c00-2f73-11eb-857b-2958b14a8e98.png)

**Comment by weinand** [comment]
@isidorn I've added support for the `exceptionInfo` request to Mock Debug.

**Comment by isidorn** [comment]
@weinand Thanks.
Assigining to January to investigate more what is going on on the VS Code side

**Comment by isidorn** [comment]
I had a bad check if a field is there by doing
 `if (exceptionInfo && exceptionSf.range.startLineNumber && exceptionSf.range.startColumn) {`
So if the `column` was `0` this was `false` which was the cause of the issue.
However this check is no longer needed since we introduced `null` types in vscode.

Now this seems to work

![Screenshot 2021-01-07 at 16 46 03](https://user-images.githubusercontent.com/1926584/103912653-d845b500-5107-11eb-8e3f-21b47d60afa9.png)

**Comment by isidorn** [comment]
@pfitzseb you can try it out with vscode insiders from tomorrow and let us know if this is now good for you, thanks!

**Comment by pfitzseb** [comment]
Nice, this fixes the issue in our extension. Thanks for the quick response!

**Comment by isidorn** [comment]
Thanks for letting us know it is now good, adding verified label
