### ISSUE TITLE
PERL syntax highlighter doesn't like 'split' PATTERN of a double-quote 

### ISSUE THREAD

**Issue by leonid-s-usov** [microsoft/vscode#113985]
Issue Type: <b>Bug</b>

Thils line of PERL code 

    my @list = split /"/, $string;

will color all following lines as if withing a string because of the unbalanced quote.

This, however, is a valid PERL code that will split the $string by quotation mark symbols.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (1.52GB free)|
|Process Argv|-psn_0_3085041|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
yacc|car|1.3.1
mikrotik-routeros-script|dev|2018.8.2
xml|Dot|2.5.1
gitlens|eam|11.1.3
go|gol|0.20.1
sftp|lix|1.12.9
lex|lun|0.1.0
autoconf|mae|0.1.0
perl-debug|mor|0.6.3
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
java|red|0.73.0
angelscript|ren|1.0.1
cmake|twx|0.0.17
vscode-lldb|vad|1.6.1
vscode-java-debug|vsc|0.30.0

</details>

**Comment by alexr00** [comment]
Thanks for the issue! I've moved it to the repository that we get our perl syntax highlighting grammar from https://github.com/textmate/perl.tmbundle/issues/45
