### ISSUE TITLE
Terminal hover labels don't go away

### ISSUE THREAD

**Issue by nicolaskruchten** [microsoft/vscode#113913]
Issue Type: <b>Bug</b>

When moving my mouse over the terminal shell, the "follow link" and "open file in editor" frequently (90% of the time) don't disappear on mouseout. If I slowly/carefully mouse in and out then they do but if I just move my cursor over the terminal on my way somewhere else, this distracting hover thing stays there.

Is there a workaround whereby I simply disable this hover? I know how to command-click, I don't need to see it all the time :)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id d86f84f4-11a3-40aa-8322-22bc71e01d57|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.8.0
vscode-pull-request-github|Git|0.22.0
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.8.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
sublime-keybindings|ms-|4.0.7
sass-indented|rob|1.5.1
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383cf:30185419
vspyt653:30237719
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by Tyriar** [comment]
FWIW the hover actually displays dynamic information depending on the type of link, for example:

![image](https://user-images.githubusercontent.com/2193314/103785222-ce309300-4fef-11eb-8709-30e0027e77eb.png)

I'm open to creating a setting to disabling the hover outright though.

I'd also like to get to the bottom of the problem you're seeing of the hover not going away, can you record a gif using https://gifcap.dev/ of the problem case(s) you see? Also knowing if there are errors in the devtools console would be helpful (Help > Toggle Developer Tools).

**Comment by nicolaskruchten** [comment]
So poking at it a bit more, it seems to mostly happen when I'm moving my cursor over a list of files, and "90% of the time" seems to be an exaggeration due to the annoyance factor of this one frequent issue in an otherwise-amazing and critical tool for me (so *thank you* to all the devs and apologies for the hyperbole ;)

Here's a GIF:

![recording](https://user-images.githubusercontent.com/203523/103788371-c3d0c200-500c-11eb-96a0-22d94a383697.gif)

**Comment by nicolaskruchten** [comment]
Ah, the way to get it to happen more often, which is quite common for me, is when the list of many files goes to the top of the terminal, and the final destination of the cursor is the main editor window (see gif). Note also that when the hover label is stuck, scrolling up and down causes the little blue outline to stay as well.

![recording (1)](https://user-images.githubusercontent.com/203523/103789885-82d9ad00-500e-11eb-9747-ce8b0df2c2af.gif)

**Comment by nicolaskruchten** [comment]
Ahh I think I found the problem! I had `"terminal.external.osxExec": "iTerm2.app"` in my settings. I can't remember why just now... what does that setting do, materially? :)
