### ISSUE TITLE
camelcase snippet variable format

### ISSUE THREAD

**Issue by lanmonster** [microsoft/vscode#113992]
I see the grammar at https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar only supports `upcase`, `downcase`, and `capitalize` for format options. can there be a `camelcase` option that would transform the match text into camelCase?

Thanks for the awesome work!

**Comment by ArturoDent** [comment]
Just FYI, I believe pascalcase is also supported but undocumented.

**Comment by movermeyer** [comment]
Docs updated in https://github.com/microsoft/vscode-docs/pull/4434

**Comment by movermeyer** [comment]
> Just FYI, I believe pascalcase is also supported but undocumented.

The docs were updated to include `/pascalcase` in https://github.com/microsoft/vscode-docs/pull/4434 to

**Comment by jrieken** [comment]
To verify:

* insert a snippet like below
* type 'Hello_World'
* press `tab`
* the second line should become `helloWorld`

```
	"f1": {
		"prefix": "f1",
		"body": [
			"${1}",
			"${1/(.+)/${1:/camelcase}/}"
		]
	},
```
