### ISSUE TITLE
[Notebook] Request: allow NotebookContentProvider to query and open any matching notebook type

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#113937]
Given that the method `registerNotebookKernelProvider` can specify the view types that are allowed to use the provided kernels, it would be hugely beneficial to be able to decouple the implementation of notebook kernels from the notebook content.

E.g., consider the imagined scenario where:

1. The [Jupyter](https://github.com/microsoft/vscode-jupyter) extension _only_ provides read/write capabilities of `.ipynb` files.
2. The [.NET Interactive](https://github.com/dotnet/interactive/tree/main/src/dotnet-interactive-vscode) extension _only_ provides a notebook kernel that can execute C# cells.
3. The [Python](https://github.com/microsoft/vscode-python) extension _only_ provides a notebook kernel that can execute Python cells.

As it stands, the .NET Interactive extension needs its own handling of `.ipynb` files, and any future notebook extension that wants to use the `.ipynb` file format needs to re-implement this, too.

There is also the issue where currently the Python extension only knows how to create a Jupyter-style kernel for .NET Interactive, and that's problematic because it's operating over the Jupyter protocol and in a separate process that the "real" .NET Interactive kernel provider doesn't know about, so you're in a weird situation where cell execution is handled in Jupyter mode in it's own process, but language service calls (e.g., Hover) are handled through the VS Code extension that has no idea about the "real" runtime.

To make this work, my proposal is that a method be added _somewhere_ (?) that can query for notebook kernels based on a view type that the existing extension supports.  E.g., something like this:

``` typescript
function getNotebookKernels(viewType: string) NotebookKernel[];
```

With this change, the Python/`.ipynb` extension simply calls that method with `getNotebookKernels('jupyter')` and included in that list will be the .NET Interactive kernel that can execute C#.  From there, the .NET Interactive extension would be able to handle both UI interactions like hover, as well as runtime execution actions.

**Comment by brettfo** [comment]
As a sub-note on this, it would be nice for a notebook kernel to also provide a list of languages that it supports.  As it currently stands, a user can open a `.ipynb` file, set the kernel to '.NET Interactive (C#)', and then individually set a cell's language to Ruby or C++, and that doesn't make a lot of sense, but if the kernel (once found as per my suggested method above) reported that it only supports the language types `['dotnet-interactive.csharp', 'dotnet-interactive.fsharp', ...]`, then we could give a much better experience to the user.

**Comment by DonJayamanne** [comment]
Suggestion:
* .NET can register kernels with jupyter containing some special metadata
* When Jupyter extension lists kernels we will check both of the following:
	* Look for kernels that contain this special metadata & hide it
	* Check if .NET extension is installed
	* If both of the above conditions are met, then we can hide these jupyter kernels.
* .NET kernel will register its own kernel with VS Code
* Jupyter exenion will now not display any .NET kernels
* A user will see a .NET kernel that was contributed by the .NET extension, hence all kernel execution & everything will be handled by .NET extension
* Jupyter kernel will only provide the content for ipynb files & nothing else and .NET extension owns execution.

With this approach, we don't need any new API from VS Code and minimal changes to the Jupyter extension.

**Comment by rchiodo** [comment]
Maybe the metadata could be the extension name that should provide this kernel to VS code? Something like so:

```json
       "metadata": {
          "vscode-extension": "ms-dotnetinteractive"
}
```

This would allow the jupyter extension to skip kernels from other extensions too.

**Comment by rebornix** [comment]
Thanks for all the great input, we had similar discussion/investigation into this previously, you may want to give https://github.com/microsoft/vscode/issues/106694 a read but we can continue discussion here.

**Comment by DonJayamanne** [comment]
Havig discussed this issue with @brettfo 
I think the status as follows:
* .NET extension doesn't know that its the selected controller
I.e. from what I can tell the following issue will address this https://github.com/microsoft/vscode/issues/122415

@jrieken @rebornix /cc

Bascially .NET needs to know whether their VS Code kernel was selceted or not (instead of the Python kernel).
