### ISSUE TITLE
Visual Studio Code cannot find or open AutoRest

### ISSUE THREAD

**Issue by kktam** [microsoft/vscode#113940]
AutoRest is generally available in the Visual Studio Code marketplace for preview.  However, Visual Studio code cannot find it from the extension panel, and even when autorest is manually installed using npm, VSCode still cannot find and locate it.

When VSCode is asked to generate an new Azure function, using Open API v2/v3 wIt generates the error message 

- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

to generate the bug of not finding autorest in VS Code extension marketplace

1. Click VSCode marketplace
2. Type "autorest" hit find
3. returns no result

to generate the bug when Autorest is run

1.  Open VSCode
2.  Click Azure -> Azure Function. Click "Create New Project"
3. In "Create new Project", select C#
4. In select a template, select "HTTP triggers from Open Api V2/V3 (Preview)"

Got an error message

> Failed to find 'autorest' | Extension need autorest to generate a function app from the Open API specification...

Does this issue occur when all extensions are disabled?: Yes

AutoRest can be found in [https://github.com/Azure/AutoRest](https://github.com/Azure/AutoRest)

Below are screenshots:

1. Autorest announcement in VSCode Marketplace
![autorest marketplace](https://user-images.githubusercontent.com/2776485/103834973-cc8bbd00-5039-11eb-926c-5dced80166ca.JPG)

2. locally installed autorest, using npm
![autorest](https://user-images.githubusercontent.com/2776485/103834974-cd245380-5039-11eb-9f02-cfc2ecea10be.JPG)

3. VSCode cannot locate autorest error message
![vscode cannot find autorest](https://user-images.githubusercontent.com/2776485/103834975-cdbcea00-5039-11eb-9d5b-3b40073e0f33.JPG)

4. VScode cannot find autorest from extension marketplace
![vscode no autorest extension](https://user-images.githubusercontent.com/2776485/103834976-cdbcea00-5039-11eb-952b-19a07774a461.JPG)

**Comment by sandy081** [comment]
It seems this extension is no longer available in Marketplace. You can see following info on the extension

<img width="665" alt="image" src="https://user-images.githubusercontent.com/10746682/103919506-63c34400-5110-11eb-8f94-e3e76289d133.png">

Hence you are not able to find the extension from VS Code.
