### ISSUE TITLE
Infinite loop when closing several tabs

### ISSUE THREAD

**Issue by trevorsg** [Microsoft/vscode#11394]
- VSCode Version: 1.4.0
- OS Version: Win 10 build 14393.82

This only happened to me once. I closed VS Code and tried to reproduce the issue, but I was unable to. Here is what I did:

1. Open VS Code form command line by typing "code ."
 -- it opened with all of the tabs I had open in the previous session.
2. Right-click on the left-most tab and click "Close Others".

Instead of everything else closing, I got a really cool UI loop that I captured in a gif (below).

![scaryloop-vscode](https://cloud.githubusercontent.com/assets/397836/18170157/4206bac4-702b-11e6-81b4-bbce2132919c.gif)

I went away for about 15 minutes, and it was still in that loop when I returned. I clicked the [X] in the top-right to close VS Code, re-opened, and everything was fine.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by trevorsg** [comment]
Thanks @bpasero. I don't have any extensions installed. Like I said, this only happened to me once, but it was pretty nasty so I wanted to get it on the radar. Feel free to close the issue as not reproducible. I will re-open it if I can find more consistent repro steps.

**Comment by bpasero** [comment]
@trevorsg this looks bad though, if it ever happens again it would be cool if you could contact me again so that we can look into some things (e.g. debug it).

Anyway, please report back when you found out a pattern to reproduce.

**Comment by bpasero** [comment]
I found a way to reproduce this 👍

**Comment by bpasero** [comment]
A bit tricky to verify:
* have many tabs open
* have one tab (not active) on a file that is no within the workspace
* delete this file on disk
* right click on the tab of this file and select "Close Others"

=> you should not end up in an endless loop 👍

**Comment by trevorsg** [comment]
Wow, I'm impressed you found a repro so quickly :)

**Comment by bpasero** [comment]
@trevorsg it was a lucky guess with success ;)
