### ISSUE TITLE
Solarized Light color theme with Jupyter Notebook integration invisible highlight

### ISSUE THREAD

**Issue by petetalbert** [microsoft/vscode#113928]
Issue Type: <b>Feature Request</b>

Hello,

If I use the Solarized Light color theme with the Jupyter Notebook theme, I can't see when I'm highlighting any code. It must be the same color as the highlight. Not a huge deal, but I do really like the Solarized Light color theme!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17763

**Comment by aeschli** [comment]
Can you add a screenshot?
What is the 'Jupyter Notebook theme'? I'm not very familiar with Jupyter, so if you have steps to reproduce, that would help.
