### ISSUE TITLE
Find & Replace

### ISSUE THREAD

**Issue by Hecaretha** [microsoft/vscode#113953]
Issue Type: <b>Bug</b>

when I used the 'find and replace' ability, it is not working as intended as of today.

i.e.

* using Ctl + H to open view port.
* Then, enter Item I want found in top input - (working fine)
* Then, I enter the content I want to replace this content with in the bottom input and press the Enter key - (There is no response or change when the enter key is pressed)

P.S. I checked for visual studio updates to see if this was cuasing the issue, howwever there was no updates at this time

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rebornix** [comment]
@Hecaretha can you share a screen recording to help troubleshoot?
