### ISSUE TITLE
Gulp autodetection should install gulp if not found

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#113982]
Issue Type: <b>Bug</b>

Currently, when gulp isn't found, the following output is produced:

```
/bin/sh: 1: gulp: not found

Auto detecting gulp for folder XXX failed with error: Error: Command failed: gulp --tasks-simple --no-color
/bin/sh: 1: gulp: not found

```

It would be better if installing it was suggested to the user instead of failing.

VS Code version: Code - Insiders 1.53.0-insider (01089c0a5052432594a177f90ad9f3148ec2a6a2, 2021-01-07T05:22:09.742Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-59-generic

<details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
output-colorizer|IBM|0.1.2
dotenv|mik|1.0.1
remote-ssh-edit-nightly|ms-|2021.1.8133
remote-ssh-nightly|ms-|2021.1.8132
diff|raf|0.0.1
vscode-icons|vsc|11.1.0
calculate|aca|2.1.0
Bookmarks|ale|12.1.1
project-manager|ale|12.0.1
arepl|alm|2.0.1
All-Autocomplete|Ati|0.0.23
gitignore|cod|0.6.0
doxdocgen|csc|1.1.0
macros|ctf|0.0.4
vscode-markdownlint|Dav|0.38.0
githistory|don|0.6.14
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
whitespace-formatter|eet|0.1.0
vscode-git-history|fab|2.0.5
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.193
triggertaskonsave|Gru|0.2.16
vscode-systemd-support|han|0.1.1
polacode-2019|jef|0.5.2
chat|kar|0.35.0
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.12.0
restructuredtext|lex|142.0.0
vsls-whiteboard|los|0.0.12
rainbow-csv|mec|1.8.0
gitexplorer|mfe|1.0.1
git-graph|mhu|1.28.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.0
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
vsliveshare|ms-|1.0.3375
vsliveshare-audio|ms-|0.1.91
python-docs|Muk|0.8.3
gremlins|nho|0.26.0
vscode-yaml|red|0.13.0
git-autoconfig|shy|0.0.2
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.1.25
html-preview-vscode|tht|0.2.5
simple-rest-client|Tin|1.4.2
vscodeintellicode|Vis|1.2.10
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600:30241727
core-portspanel:30233467

```

</details>

**Comment by sana-ajani** [comment]
Agreed, just ran into this myself and was not sure what to do. Would be nice if the error message was more helpful!

**Comment by jtsom** [comment]
No. I would NOT want VS Code to install Gulp (or anything) for me. If I need something installed, tell me I need it and I will install it. I was getting this error, and I do not need Gulp for my project.
