### ISSUE TITLE
JSON Schema: cyclic references resolve to wrong path

### ISSUE THREAD

**Issue by PiIsFour** [microsoft/vscode#113993]
VSCode Version: 1.53.0-insider (user setup)
Commit: 01089c0a5052432594a177f90ad9f3148ec2a6a2
Date: 2021-01-07T05:22:09.742Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. If we have two schema files that reference each other

test.schema.json
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "oneOf": [
    {
      "type": "boolean"
    },
    {
      "$ref": "generic/node.schema.json"
    }
  ]
}
```

generic/node.schema.json
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "left": {
      "$ref": "../test.schema.json"
    },
    "right": {
      "$ref": "../test.schema.json"
    }
  }
}
```

2. in a schema file that uses this we get an error about not being able to find the file
`Problems loading reference 'file:///d%3A/projects/test.schema.json': Unable to load schema from 'd:\projects\test.schema.json': ENOENT: no such file or directory, open 'd:\projects\test.schema.json'.`
which is one folder to high.
3. switching to `"$ref": "./test.schema.json"` does not help because it is rightly a folder to low.
4. if both files are in the same folder the two cyclic refs work fine
5. if you remove the second ref (right) it will also work so relative paths are also wirking

Not sure why this combination of things stoops it from working. I would be glad if this is fixable because it seemed to work in 1.51. Please let me know if you need any more information or I'm doing something wrong. Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Looks like this got caused by https://github.com/microsoft/vscode-json-languageservice/commit/c91518682ba7545dd2160eb9f932b0f94662a02b

**Comment by aeschli** [comment]
Fix is now in insiders

**Comment by PiIsFour** [comment]
@aeschli Thanks a lot for fixing this. Works good for now in insiders, in which release will this probably come to normal vscode?

**Comment by aeschli** [comment]
Next stable (1.53) is coming in 1-2 weeks.
