### ISSUE TITLE
Custom Windows icon based on project.

### ISSUE THREAD

**Issue by alex-piccione** [microsoft/vscode#113936]
When I have some projects opened in VS Code I always wonder which Windows I have to open for the specific project.
The Windows App logo on the Taskbar is the same for all and the text is the current file, so I can only see 3-4 same logos with "index.tsx" or "README" but I don't know which one is the UI, the backend or the admin project.

![image](https://user-images.githubusercontent.com/876490/103826594-075c1800-506f-11eb-9640-1617f89e5246.png)

Is there a way to customize the Windows icon based on the project?
If not how can I ask for this feature?

**Comment by jace4511** [comment]
> When I have some projects opened in VS Code I always wonder which Windows I have to open for the specific project.
> The Windows App logo on the Taskbar is the same for all and the text is the current file, so I can only see 3-4 same logos with "index.tsx" or "README" but I don't know which one is the UI, the backend or the admin project.
> 
> ![image](https://user-images.githubusercontent.com/876490/103826594-075c1800-506f-11eb-9640-1617f89e5246.png)
> 
> Is there a way to customize the Windows icon based on the project?
> If not how can I ask for this feature?
