### ISSUE TITLE
TabWraping: uncertain wrap when fouce on diff tab

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#113947]
版本: 1.53.0-insider (system setup)
提交: 4fe3f75c6d3d88a19c47f029524172303f1a1a82
日期: 2021-01-06T15:36:33.674Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.14393

when I select different tab, vscode show different TabWraping status。
![image](https://user-images.githubusercontent.com/1876302/103845840-dd8b0b80-50d7-11eb-8ce4-a670e69199c4.png)

`note.md`  ：2 rows
`INL_DNL.m` : 1 row

**Comment by gjsjohnmurray** [comment]
When you focus on the Markdown file there are more action buttons to display. This leaves less space for the tabs, causing the wrapping.
