### ISSUE TITLE
How to use File Icon  in  VS Coded API - showQuickPick

### ISSUE THREAD

**Issue by meowWhat** [microsoft/vscode#113948]
I want to use File Theme Icon  like this in VS Coded API - showQuickPick
![image](https://user-images.githubusercontent.com/59830413/103845505-2bebda80-50d7-11eb-879c-a5d5e4107431.png)
in your docs  i  see ` use the $(<name>)-syntax, for instance quickPick.label = "Hello World $(globe)"  ` ，  But I don't know the file icon ID with color 。The icon list displayed in the document has no color 。
So how can I use the File Icon Theme  like  `Seti` in `QuckPick.Label`

**Comment by chrmarti** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/109460
