### ISSUE TITLE
Code Helper (Renderer) 100% CPU usage - tsserver

### ISSUE THREAD

**Issue by vobarian** [microsoft/vscode#113934]
@mjbvz When I tested this in the Insiders build on 12/2, it was not reproducing the issue. Since that time, VS Code 1.52.0 came out and now 1.52.1. Unfortunately the issue is still occurring in 1.52.1 but when I downloaded the latest Insiders build today (4a875e23d20b64504a818834f3fa4c40adb8d480) it is again not occurring.

So the assumption that it had been fixed in the Insiders build and would be fixed in the next stable release seems to not be true. Instead there is some persistent difference between the stable build and the Insiders build.

Again, when I have our TypeScript/React project open in VS Code and run "npm install", CPU usage goes to 100% and remains there until I close the window. This happens regardless of whether I run the command from the embedded Terminal window or from a completely separate external terminal. VS Code Process Explorer shows the offending process to be "electron_node tsserver.js"

I have uninstalled all extensions and restarted Code. Additionally I completely deleted it from my Applications folder and downloaded and installed a fresh copy of the stable release:

> Version: 1.52.1
> Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
> Date: 2020-12-16T16:30:02.420Z
> Electron: 9.3.5
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Darwin x64 19.6.0

_Originally posted by @vobarian in https://github.com/microsoft/vscode/issues/111683#issuecomment-751078997_

**Comment by mjbvz** [comment]
Have you checked to make your settings are the same between the two version (for example, using the same TypeScript version in both cases)

**Comment by vobarian** [comment]
Thank you for drawing my attention to that. I'm opening the same project folder in both cases, but for whatever reason the stable build (1.52.1) shows "TypeScript React 3.9.7" in the lower right corner, while the Insiders build shows "TypeScript React 4.1.2". If I click on the version shown on the status bar, then "Select TypeScript Version...", the stable build shows that I am set to "Use Workspace Version 3.9.7" then the line below that shows "node_modules/typescript/lib." However in the Insiders build, with the same project folder open and while viewing the same file, it shows "Use VS Code's Version 4.1.2". Indeed, after changing the version in the stable build to "Use VS Code's Version 4.1.2" the problem no longer occurs. So that is the difference.

I'm not sure why stable and Insiders are coming up with different TS versions when I open the same project folder. I'm guessing that setting is not stored in the project folder then, but I don't know where it would be. I also completely deleted my VS Code application folder and reinstalled the stable version, so I'm guessing the setting is not in there either.

I suppose changing this setting will be a good enough fix, or we can update our project's TS version. I am a little concerned about ignoring the project TS version in general--it seems like one would always want the editor to understand the same TS version that is actually going to be used when building the project.

**Comment by mjbvz** [comment]
Thanks for checking. Using an older typescript version would. explain the issue

Try running the `TypeScript: Select typescript version command` with a typescript file open. For stable, you likely changed VS Code to use the workspace version of typescript (3.9.7) while insiders is using the default version of TypeScript that VS Code ships with (4.1.2). 

The specific TS version used is not stored as a normal VS Code setting for security reasons, so deleting the settings file has no effect on it (you'd need to fully delete all user data associated with VS Code)

**Comment by vobarian** [comment]
Thank you for helping point me to a solution. We'll look into upgrading our TS version.

As far as the behavior of VS Code it still seems like an area for improvement though. Is using older TS versions unsupported? It just seems like a huge "gotcha". Configuring the right version of Node.js, TS, all the stuff in tsconfig, and apparently the VS Code setting to all work together is confusing and frustrating enough. If the old version is not supported perhaps it would save users a lot of time to not allow selecting it in the first place. I certainly never would have expected that my CPU usage is going to 100% because at some point in the distant past I selected "Use workspace version" instead of "Use VS Code's version".

I'm also not sure why it is a good idea to use a different version in the editor than you will actually use when compiling. This seems like it will lead potentially to different errors & warnings being shown in the editor vs. when actually compiling with tsc, which would be another source of confusion. Surely the editor should understand the code the same way the compiler does in order to present correct feedback to the developer. On the documentation page https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions it seems to list this as one of the reasons for configuring this setting: "Making sure you are using the same version of TypeScript for IntelliSense that you use to compile your code", although it also makes the rather vague claim that "You can just use VS Code's built-in TypeScript version for IntelliSense without worry for most common cases."
