### ISSUE TITLE
Occasional errors pasting clipboard to terminal

### ISSUE THREAD

**Issue by Slaggard** [microsoft/vscode#113952]
Tonight I'm testing a PowerShell script with a Read-Host prompt, at which I copy a string from another application, paste into terminal (by hitting right mouse button), and hit enter to continue.   Several times tonight I've caught it skipping a character during the paste!  Example: I copy string "test**programs**.onmicrosoft.com" but after pasting the terminal reads "test**rograms**.onmicrosoft.com".  I've confirmed it's happening during the paste action: when I see the incorrect value, I hit Esc to clear the prompt then paste again and get the correct value!  

I've seen this happen before with things like AutoHotKey keyboard macros that type text:  if they try to type it too fast it can drop a character, especially if the system's busy.  In those cases, the easy fix is to add a millisecond or two of pause after each character.   It's worth noting: I'm running the script in debug mode, which I know adds some overhead and may be contributing to the issue.

**Comment by meganrogge** [comment]
Thanks for this issue. If you have a reliable way to reproduce it, please let us know.

**Comment by Slaggard** [comment]
Don't currently know a way to reliably reproduce it: it's one of _those_.  Hopefully it's something on my end.

**Comment by meganrogge** [comment]
Closing for now, please file an issue if you can reproduce it. thanks!
