### ISSUE TITLE
Not sure if folding is working correctly with backticks or if there is a setting for it.

### ISSUE THREAD

**Issue by dungle-scrubs** [microsoft/vscode#113901]
- VSCode Version: 1.52.1
- OS Version: MacOS Big Sur 11.1

Not sure if folding is working correctly for functions beginning and ending in a back tick.

Steps to Reproduce:

1.  Create a function, for example, using `@emotion`'s `css` in React.
```
const VIDEO_WRAPPER = css`
  label: VIDEO_WRAPPER;
  margin-bottom: 1em;
`
```

2. Fold it and it folds to two lines and looks like this:

```
  >  const VIDEO_WRAPPER = css`...
     `
```

3. In the previous version of VSC, and what I would expect is for it to look like this:

```
  >  const VIDEO_WRAPPER = css`...
```

Is this a bug or is this intentional.  If it's intentional, is there a setting?  I'm unable to find one.

Thanks

**Comment by mjbvz** [comment]
Yes this was changed in #110108 as is by-design (template strings should now be consist with folded brackets and arrays)
