### ISSUE TITLE
Port forwarding is broken in insiders build

### ISSUE THREAD

**Issue by tetious** [microsoft/vscode#113914]
Issue Type: <b>Bug</b>

I'm not sure how to help narrow this down, but as of yesterday's (1/4/2021) insider build, SSH port forwarding seems to be completely broken. This is still a problem with today's build. The prior build (pre-holiday break) was working normally.

I am forwarding a few ports (one via workspace config), and they still show in the ports list on remote explorer, but do not appear to work. They don't work if I add them manually in remote explorer, either. I'm forwarding localhost ports only, so I don't think this is [#113763](https://github.com/microsoft/vscode/issues/113763), though it could be related.

Manually creating the forwards with `ssh -L 15432:localhost:15432 -L 4000:localhost:4000` works fine. 

If there is any additional info I can provide, please let me know!

Extension version: 0.62.0
VS Code version: Code - Insiders 1.53.0-insider (a48ef56fbf7767f55a193d7d5687addd1fc9239c, 2021-01-05T05:33:42.154Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.9.10-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 14c50ee1-a00b-46b0-abaf-6965d9e59493|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: putz|
|OS|Linux x64 5.9.10-200.fc33.x86_64|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2196)|
|Memory (System)|31.33GB (6.21GB free)|
|VM|0%|
</details>

**Comment by tetious** [comment]
I've gotten two new Insider builds, and this problem is not fixed in them. This might be expected, as I'm not sure which branch you target for those builds. Just wanted to mention, if it should be fixed... it isn't, yet. 😄

**Comment by alexdima** [comment]
@tetious Could you please try with today's Insiders for example:
```
Version: 1.53.0-insider
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:12:22.156Z
```

I have tested SSH from a macOS client to a Windows server and forwarding ports worked for me.

@alexr00 Could you please also double check?

**Comment by tetious** [comment]
This is indeed now fixed for me in that build. Thanks for tracking this down so quickly. 👍

**Comment by alexr00** [comment]
(doubled check, it's working from Windows to an Ubuntu remote too)

**Comment by sbatten** [comment]
marking as verified by comments above
