### ISSUE TITLE
Terminal: Context-menu does not work in the PS Terminal

### ISSUE THREAD

**Issue by Bartolomeus-649** [microsoft/vscode#113935]
Issue Type: <b>Bug</b>

The context-menu does not show when right-clicking in the PowerShell terminal window.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment]
Change the setting `terminal.integrated.rightClickBehavior` : default
