### ISSUE TITLE
Feature Request: R language extension

### ISSUE THREAD

**Issue by asdncg** [Microsoft/vscode#11393]
- VSCode Version: 1.4
- OS Version: Windows 10

Steps to Reproduce:
1. 
2.

**Comment by asdncg** [comment]
when?

**Comment by rwatts3** [comment]
Will there be support for intellisense in R ? 
If so is there an expected timeline?

@chrisdias

**Comment by rwatts3** [comment]
Wondering if we can get an update or info on whether or not this feature request will be honored.

**Comment by hoovercj** [comment]
Is this a duplicate of #14393?

**Comment by mjbvz** [comment]
Duplicate of #14393
