### ISSUE TITLE
Keybinding: Allow colon to be a valid keybinding

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vscode#114]
Working on a [VIM extension](https://github.com/VSCodeVim/Vim). A core key binding of VIM is `:`.

The below is a workaround:
```
     {
        "key": "Shift+;",
        "command": "extension.vimMode_colon",
        "when": "editorTextFocus"
      },
```
but it doesn't work on international keyboards.

**Comment by alexandrudima** [comment]
@jpoon I can't really add support for that. The keybinding dispatching occurs in a keydown browser event handler, where I only get the keyCode and the modifiers state (i.e. keyboard layout independent, not what would be produced in a keypress).

We need to do something special for vim where all typed characters can be "trapped" and redirected to an extension

**Comment by alexandrudima** [comment]
@jpoon We cannot add colon as a valid keybinding for now. Please see #713 where the problem is explained. I also suggest #713 as the tracking issue instead of having an issue for each individual desired keybinding character.
