### ISSUE TITLE
File name in editor tab reverts casing on save

### ISSUE THREAD

**Issue by elanhamburger** [microsoft/vscode#114096]
- VSCode Version: 1.52.1 / 1.53.0-insider
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Create a new file `TEST.js`
2. Rename the file to `test.js`
3. Save the file

Expected: File name in tab above editor window should retain new casing (`test.js`)
Actual: File name in tab above editor window reverts to previous casing (`TEST.js`), even across multiple opens

This is similar to an intermediate state in a fix for a [bug I reported last June](https://github.com/microsoft/vscode/issues/100436), perhaps it's a regression?

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@bpasero I see some people reporting issue like this?
Probably caused by my change to use `bulkFileEdits`. Might you have an idea?

@elanhamburger I can not reproduce this. @bpasero can you try to repro?

**Comment by bpasero** [comment]
Could be a variant of https://github.com/microsoft/vscode/issues/113277

**Comment by isidorn** [comment]
Yeah looks like that
