### ISSUE TITLE
Lose color scheme when I press CTRL+OPT+CMD+8 to Invert colors

### ISSUE THREAD

**Issue by shinokada** [microsoft/vscode#114027]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. macOS System > Shortcuts > Accessibility > Invert colors CTRL+OPT+CMD+8
2. When I invert colors, I have to reset VS Code color scheme.

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
When 'Invert colors' is set, VS Code assumes you are in a high contrast mode and switches to the High Contrast theme.

You can specify your preferred HC theme by: `workbench.preferredHighContrastColorTheme`
Or you can turn that feature off by `"window.autoDetectHighContrast": false`
