### ISSUE TITLE
Unbound breakpoints while debugging node.js in vscode 1.52.1

### ISSUE THREAD

**Issue by Epacik** [microsoft/vscode#114007]
I was trying to debug two projects lately in typescript.
An extension for vs code with language server with support for 8051 assembly which is supposed to be a part of my thesis and this [https://github.com/sindresorhus/caprine](https://github.com/sindresorhus/caprine).

But while I can work on the projects, I cannot effectively debug them because breakpoints set in typescript and in transpiled javascript aren't bound. 
I tried multiple things from the internet and from issues here and none of them seems to fix that problem.
Just to be sure, I tested debugging Caprine on Linux as well as on Windows, and after a few hours, a few reinstallations, running vs code without extensions and removal of `%UserProfile%\.vscode`, `%AppData%\Code`, `%LocalAppData%\Programs\Microsoft VS Code` folders I realized that the only ways I can properly set breakpoints are:

1. Opening the "Run" panel, searching for a script in the "Loaded scripts" section, and setting a breakpoint trough a script opened that way (I may be mistaken, but I think that could be a problem with paths to files because script opened using "Loaded scripts" have an absolute path at the top of the editor and script opened trough the Explorer have a relative path).
2. Using VS Code Insiders but only on Manjaro Linux, on Windows using the newest Insider build didn't make a difference, breakpoints were still unbound.

I tried to compile vs code from source but I wasn't able to, so I didn't check if that would make breakpoints to bind properly.
On Manjaro I've installed `visual-studio-code-bin` and `visual-studio-code-insiders-bin` from AUR and on Windows, I just downloaded installers from the official website.

- VSCode Version: 1.52.1 (user setup) / 1.53-insider
- OS Version: Windows 10 20H2 (19042.685) / Manjaro Linux (Kernel: 5.7.19-2-MANJARO, KDE: 5.20.4)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Epacik** [comment]
A little update, today I realized that on Manjaro both 1.52.4 and 1.53-insider works now fine, on Windows problem persists

**Comment by sidgoel85** [comment]
Hi, I've tried all the possible suggestions but I keep getting unbound break-point issue in VS Code. Any help will be greatly appreciated.
