### ISSUE TITLE
Ability to Sync Settings per Device

### ISSUE THREAD

**Issue by cmario92** [microsoft/vscode#114036]
As a user, using VSCode on different devices, I would like the ability to sync different configurations of settings per device. 
The device settings should inherit and override any configurations from the global settings(same approach as workspace/folder)

### Explanation:
Currently the Settings sync inherits the following hierarchy: **_Global -> Folder -> Workspace_**
The proposal in the issue is to add a new layer: _**Global -> Device -> Folder -> Workspace**_

### **Scenarios:**

1. Work Laptop - is using proxy, whereas the home laptop for side projects does not require the `proxy` setting
2. Desktop Computer is plugged in to a 27" monitor and the fontSize is better with 16px, whereas VSCode on laptop is using the 13" screen, so a much smaller fontSize is suitable. 
3. VSCode on Desktop is installed on debian, VSCode on work laptop is installed on Windows.

#### A valid real-life scenario
![image](https://user-images.githubusercontent.com/5765285/104021579-b1e74e80-51c7-11eb-8c4c-69bbc901600e.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/89627
