### ISSUE TITLE
The Microsoft authentication provider requires sign in for each scope

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#114003]
Issue Type: <b>Bug</b>

The Microsoft authentication provider, instead of using signed in identiy, prompts user to sign in again for getting token for a new scope. 

Repro steps:
1. Create two empty extensions named `aad-auth-1` & `aad-auth-2` through the yo code generator. [See this tutorial.](https://code.visualstudio.com/api/get-started/your-first-extension)
2. Register two AAD apps to act as two resources. [See this.](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/4-AdvancedGrants/1-call-api-graph#register-the-service-app) You can skip 8th step here.
3. Add the VS Code AAD client (Id: aebc6443-996d-45c2-90f0-388ff96faa56) as trusted client for the user_impersonation scope in the above two AAD apps.
4. In 1st extension, package.json, change the hello world command title to `Hello World 1` . Then update the command execution to 
```
let disposable = vscode.commands.registerCommand('aad-auth-1.helloWorld1', async () => {
    // The code you place here will be executed every time your command is executed

    // Display a message box to the user
    vscode.window.showInformationMessage('Hello World from aad-auth-1!');
    try {
        await vscode.authentication.getSession('microsoft', [
            'api://cd96451f-9709-4a95-b1f5-79da05cf8502/user_impersonation',
            'offline_access',
            ], { clearSessionPreference: false, createIfNone: true })
            .then((session: vscode.AuthenticationSession) => {
                console.log(session);
            });
    } catch (error) {
        console.log(error.message);
    }
});
```
5. In 2nd extension, do same as above, but request `user_impersonation` scope for the 2nd AAD app. 
6. Compile, package and install the two extension.
7. Run the command `Hello World 1` followed by `Hello World 2`.

Notice that you get prompted for sign in twice. Ideally, user should get a prompt saying second extension is trying to use you logged in identity and their on consent, the refresh token from 1st sign in should be silently used to get the access token for 2nd extension.

VS Code version: Code - Insiders 1.53.0-insider (01089c0a5052432594a177f90ad9f3148ec2a6a2, 2021-01-07T05:22:09.742Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (15.60GB free)|
|Process Argv|--crash-reporter-id 89bbd2c8-eadf-40a4-831a-2bab71a0d01a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-typescript-tslint-plugin|ms-|1.3.3
aad-auth-1|sag|0.0.1
aad-auth-2|sag|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092

```

</details>

**Comment by samrat-gavale** [comment]
@RMacfarlane this is a common enterprise scenario where a developer team is required to work with 2-3 different extensions which access different resources behind AAD. Signing in separately for each of them is sub-optimal experience. The only caveat in the single sing on as requested above is when multiple extensions get activated at same time and none of them has user logged in previously. Not sure how and if the Microsoft auth provider should synchronize between such concurrent requests.

**Comment by samrat-gavale** [comment]
@RMacfarlane, any comments about this request? Based on the how much work it would be, I can make contributions to get this in.

**Comment by RMacfarlane** [comment]
Hey @samrat-gavale, thanks for creating this, I wasn't aware that it was possible to request different scopes when refreshing the token and thus avoid the additional sign in attempt. Do you know if this works for any scopes, or does the refresh have to be with a subset of scopes that were originally granted?

**Comment by samrat-gavale** [comment]
@RMacfarlane, the [documentation](https://docs.microsoft.com/en-us/previous-versions/azure/dn645538(v=azure.100)) does not mention that the new scope for which access token is being requested should be a subset of the scopes that were originally granted. So I believe it should work for any new scope. I am trying to confirm this. I will let you know about what I find.

**Comment by samrat-gavale** [comment]
@RMacfarlane, I verified that the new scope for which access token is being requested doesn't need to be part of original requests which obtained auth code and access token. Here is what I did. I can share the Postman requests if needed.

1. Obtained authorization code for resource A's scope and `offline_access`.
2. Exchanged this auth code for an access token for resource A's scope and `offline_access`.
3. Used the refresh token obtained from step 2 above to get access token for resource B's scope.

**Comment by RMacfarlane** [comment]
Ok cool, thanks for the documentation link! Right now we use the `scopes` query parameter instead of `resource` so I'll test out that it behaves in the same way

**Comment by samrat-gavale** [comment]
@RMacfarlane , pining to see if there are any updates here. Again, if you have identified a set of tasks needed to implement this, I would be open to taking up some of them.

**Comment by samrat-gavale** [comment]
@TylerLeonhardt , I know this issue was only recently assigned to you, but would like to draw your attention to it, since it is related to [#124643](https://github.com/microsoft/vscode/issues/124643) which you seem to be working on. As stated above, let me know if there is anything I can do to get this implemented earlier.

**Comment by TylerLeonhardt** [comment]
@samrat-gavale from reading this, it sounds like the downside is that you have to log in twice, but then you'll be logged in "forever" after that. Is that the only downside?

**Comment by samrat-gavale** [comment]
@TylerLeonhardt , yes, the major downside I am concerned about is logging in multiple times. But there are some nuances to it:

1. Two is a low number for extensions requiring user sign in. Typically there will at least 3-4 extensions which would require user sign in.
2. Being signed in forever after initial sign in is not necessarily true. I have seen many times that the token refresh on subsequent launches of VS Code fails with `unable to transform input` error. As a result the re-sign-in is much more frequent than the 90 day mark allowed by AAD.

From my experience of a pilot rollout which requires sign-in, less than half users actually signed in. So getting all users to sign in even once for each of their extensions can be challenging. AAD has implemented MRRT tokens for this very reason of reducing the sign in fatigue for end users. Therefore I strongly feel that VS Code should leverage it to enable better adoption of the extensions.

**Comment by TylerLeonhardt** [comment]
Hi @samrat-gavale, I looked into this a bit... and one problem I see with this is that this feature that you've sent docs on is a v1 feature and we've been using v2 identity APIs: login.microsoftonline.com/organzations/oauth2/v2.0/....

Do you know of any docs on how to do this in the v2 world? I don't particularly want to support v1 and v2 or auth flows.

**Comment by TylerLeonhardt** [comment]
I think I figured out how to do this... essentially I am using the refresh token & the 2nd set of scopes to get a token. It seems to be working for me.

**Comment by TylerLeonhardt** [comment]
This will be in tomorrow's insider build to try out

**Comment by TylerLeonhardt** [comment]
Just to be clear, you will still get 2 modals because you _are_ asking for another set of scopes... but rather than going to your browser a 2nd time, you'll see this:
![image](https://user-images.githubusercontent.com/2644648/156667692-5211ac3a-d2fb-4d2c-a81c-4cd2583b373b.png)
