### ISSUE TITLE
workspace.asRelativePath doesn't work for path outside workspace

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#11402]
From verifying #10446
(on Linux, 1.5.0-insider, Commit d2c04e3789757413ae1ebfda9d88896686b6d006)
```
let input = "/home/aeschli/frr/samples/docker";

console.log("root: " + workspace.rootPath);
console.log("input: " + input);
console.log("output: " + workspace.asRelativePath(input));
```

Output:

root: /home/aeschli/workspaces/samples/docker
input: /home/aeschli/frr/samples/docker
output: /home/aeschli/frr/samples/docker

If this expected then maybe this we could add it to the doc.

**Comment by jrieken** [comment]
@aeschli Like so: https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3580

**Comment by aeschli** [comment]
Ok, now I see it. Just not very intuitive, this API. asRelativePath returns an absolute path.

'when the path is not a child of that folder, the input is returned.'
Then, this is then actually a bug:
```
root: /home/aeschli/workspaces/samples/docker
input: /home/aeschli/workspaces/samples/docker
output:
```
Let me know if you want a separate issue.

**Comment by jrieken** [comment]
Yup - i'll use this issue

**Comment by jrieken** [comment]
> just not very intuitive, this API. asRelativePath returns an absolute path.

The idea is that you can use that function to show workspace relative paths in the UI. that's how the funny default came in - cos then you wanna see the full path
