### ISSUE TITLE
Light bulp still visible behind the F8 window

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#11400]
From verifying https://github.com/Microsoft/vscode/issues/11022:

- Have a css file 
```css
.aria-container {
	left1:-999em;
}
```
- set the cursor at the end of the line where the error is
- press F8
- set the cursor to the error
![image](https://cloud.githubusercontent.com/assets/6461412/18173442/e11c66e8-7069-11e6-8fd7-9bea87210472.png)

**Comment by jrieken** [comment]
Yeah - the one lightbulb is still there... I couldn't get the focusout/in stuff to work

**Comment by jrieken** [comment]
We now show the light bulb in glyph margin

<img width="366" alt="screen shot 2016-10-06 at 10 41 18" src="https://cloud.githubusercontent.com/assets/1794099/19145898/6dde210e-8bb1-11e6-916f-61de177136d0.png">
