### ISSUE TITLE
launch.json environment variables getting lost on resolver extension

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#114063]
- VSCode Version: 1.52.1
- OS Version: Mac OS Big Sur

Environment variables declared in a launch configuration seem to get lost after reloading into the resolver of an extension.

Steps to Reproduce:

1. Add an environment variable to `launch.json` like:
            "env": { "TEST_ENV": "test-val"},
2. Check the environment variable to be present on extension main file during the first activation. It should be there fine.
3. After kicking off the resolver check the environment variables and it won't be there.

**Comment by isidorn** [comment]
Forwarding to @weinand since I know he investegted already this area for similar issues.

**Comment by weinand** [comment]
@osortega what do you mean by "After kicking off the resolver"?

**Comment by osortega** [comment]
@weinand we kick off our resolver by opening a folder with the VS Code remote protocol and our remote authority.
Once this happens and the VS Code window reloads , the env variables set in the `launch.json` won't be present.

**Comment by osortega** [comment]
Is there an ETA on this bug fix? It will really help us to reduce significantly our extension compile time.

**Comment by connor4312** [comment]
@osortega this may be fixed with https://github.com/microsoft/vscode/issues/123508. Please try tomorrow's [Insiders build](https://code.visualstudio.com/insiders/) and let us know.
