### ISSUE TITLE
Settings editor: Increase section disctinction

### ISSUE THREAD

**Issue by t-gebauer** [microsoft/vscode#114077]
It is very hard to notice when one is (accidentally) scrolling over the boundaries of a settings group. (Especially for new users who might not be familiar with such a continuous one-page view?)
This also relates to the fact that the toc switches very late to the next heading, which makes it look like one is still in the previous section even though most of the screen is already occupied by the next one.

This is how the settings editor currently looks like in 1.52.1:

![2021-01-09-120158_697x248_scrot](https://user-images.githubusercontent.com/5971351/104090189-c03b7600-526c-11eb-924e-a3cda9cd34f1.png)

Notice how "Features" and "Explorer" are styled identically, even though they are clearly hierarchical in the toc.

## Suggested improvements

I am not a UI designer, so this is just an uninformed suggestion. But probably anything would be better than the current state.

- increase the font size of "chapter" headings compared to "section" headings
- add horizontal row separators to all "section" headings
- increase the white-space around headings

### double "chapter" heading
![2021-01-09-124950_716x439_scrot](https://user-images.githubusercontent.com/5971351/104090754-ca5f7380-5270-11eb-95e0-103ce1e79b3b.png)

### single "section" heading
![2021-01-09-130405_692x278_scrot](https://user-images.githubusercontent.com/5971351/104091053-dc421600-5272-11eb-8a91-53ca8dafa52e.png)

**Comment by misolori** [comment]
@roblourens can we place certain styling for groups where there is no immediate settings? Seems like Features + Application are the only groups where there aren't settings unlike the others.

**Comment by roblourens** [comment]
Yeah that should be possible

**Comment by rzhao271** [comment]
Closing this issue as wontfix now that the Settings editor headers have sticky scroll to help users navigate.
