### ISSUE TITLE
Constant Reconnections with WSL 2 on Win 10

### ISSUE THREAD

**Issue by mike01720** [microsoft/vscode#114014]
Issue Type: <b>Bug</b>

Repro:
1. Open cmd line wsl to git repo
2. enter 'code .'
3. Opens VS Code with repo
4. Type in file(s). 
5. Save changes (ctrl+s)
6. Pop up appears 'Attempting to reconnect'
7. Click Reload window

Actual result:
1/3 reloads successfully
2/3 reopens blank with lost connection to wsl and repo fails to load.
The pop ups can happen within 5 min of working or 30 min. No deterministic apparent cause. 

Expected:
Limited/none reconnection requests and a successfuly reconnection and resume working in the same VS Code window. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor           (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (3.84GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/code/Buster/DeepDiscovery --remote=wsl+Ubuntu --crash-reporter-id 47f4bdb5-06e8-463a-9efc-bce693a4e562|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 3000)|
|Memory (System)|12.45GB (2.18GB free)|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
systemd-unit-file|coo|1.0.6
autoconf|mae|0.1.0
Angular-BeastCode|Mik|10.0.3
remote-wsl|ms-|0.52.0
atom-keybindings|ms-|3.0.9
debugger-for-chrome|msj|4.12.11
jenkinsfile-support|sec|0.1.0
material-theme|zhu|3.9.12
data-converter|att|1.0.3
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.1.3
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vscode-diff|fab|1.4.0
vscode-open-multiple-files|fab|1.3.0
vscode-npm|fkn|3.3.0
docker-explorer|for|0.1.7
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|3.0.40
terraform|has|2.3.0
vscode-test-explorer|hbe|2.19.3
jenkinsfile-support|ivo|1.1.0
dupchecker|jia|0.1.6
svg|joc|1.4.3
vscode-python-test-adapter|lit|0.6.5
MagicPython|mag|1.1.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|0.73.0
sonarlint-vscode|Son|1.19.0
remove-blank-lines|tha|1.1.1
html-preview-vscode|tht|0.2.5
vscode-docker-ws|tii|0.5.0
pdf|tom|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.0
vscode-json-path|wei|2.4.0
hex-ascii-converter|yrp|0.0.1
vsc-docker|Zim|0.34.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30241727
vsjup459cf:30237188

```

</details>

**Comment by aeschli** [comment]
@alexdima Any recommendation how to get more debug information?

**Comment by alexdima** [comment]
@mike01720 Does this reproduce every time you try it or only sometimes? Can you please attach the window log (`F1 > Show Logs... > Window`) and the server log (`F1 > Show Logs... > Remote Server`).

**Comment by mike01720** [comment]
Hi,

Thanks for looking at this. It usually shows up minimum 1 a day. Next time it happens I will try to capture the two logs.

**Comment by mike01720** [comment]
I have not seen the issue again. I removed all 'remote -' extensions except for 'remote - wsl' and that seems to have made a large difference. I previously had remote -ssh, remote development, and remote -containers installed.

**Comment by aeschli** [comment]
Thanks for getting back. Closing the issue then.
