### ISSUE TITLE
VS Code Does Not Recognize TSConfig Settings in SubDirectory

### ISSUE THREAD

**Issue by SamOhrenberg** [microsoft/vscode#114060]
- VSCode Version: 1.52.1
- OS Version: Windows x64 10.0.19041

Steps to Reproduce:

1. Create tsconfig.json under subdirectory (in my case, a new folder in the root of the project called "config") 
2. Add values to the tsconfig (for example, "experimentalDecorators": true and values under "paths")
3. Create a typescript file in the src/ directory
4. Errors should pop up saying "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning."

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share an example project that demonstrates the issue

**Comment by SamOhrenberg** [comment]
Thank you!

I created a clean typescript project (Angular 11.0.1) and moved the tsconfig files to a subdirectory named 'config'. I then updated the references to the tsconfig to ensure they include the corrected path. 

Here is the new repo

https://github.com/SamOhrenberg/tsconfig-error

I also recorded a video displaying the error happening:

https://www.loom.com/share/b2702d865d11440291baade61747943d

**Comment by JCMais** [comment]
I think this is also related to path aliases not working anymore inside monorepo packages. At least with the latest insiders version.

**Comment by mjbvz** [comment]
Root cause is: https://github.com/microsoft/TypeScript/issues/33094

As a fix, move `tsconfig.json` to the roof of your project (or create a new one that extends the ones under `config`)

**Comment by mjbvz** [comment]
PS: you can check if VS Code considers a TS file part a project by clicking on the TypeScript version in the status bar:


<img width="1076" alt="Screen Shot 2021-01-12 at 11 36 27 PM" src="https://user-images.githubusercontent.com/12821956/104420624-ff005300-552e-11eb-9ccf-7666c7e2436c.png">
