### ISSUE TITLE
Unintended multiple cursors

### ISSUE THREAD

**Issue by buckstephenh** [microsoft/vscode#114051]
Issue Type: <b>Bug</b>

cut copy paste or other keyboard navigation frequently causes VSC to add multiple unintended cursors especially on Dell keyboard.  I've looked at the menu to see the key combinations but don't understand exactly how this is happening.   How to remap/disable this behavior.  It causes many mishaps.   I frequently use CTRL-X,C,V, but realize some of my issue may also be the oversized track pad under my opposable thumb pads.

**Comment by alexdima** [comment]
@buckstephenh Multiple cursors can be added in many ways, including by ctrl+click if using `"editor.multiCursorModifier": "ctrlCmd"`. It would be helpful to find out how exactly you are adding these mutliple cursors. Even if this is not meant to be used in this particular way, you could try to enable the keyboard troubleshooting to see which keybinding you are hitting that ends up inserting cursors:

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Work as you do normally and once you end up with multiple cursors, look at the logs to try to understand how you ended up in this situation.

Finally, extensions can create multiple cursors. Does the issue reproduce when disabling extensions?
