### ISSUE TITLE
Backspace stops prematurely 

### ISSUE THREAD

**Issue by Steampunkrue** [Microsoft/vscode#1140]
With the selected area, I would expect it all to be removed to the given point, but instead, it only removes the parenthesis. Happens when I tested this with both Java and Javascript. 

Before backspace:
![vscode java bug1](https://cloud.githubusercontent.com/assets/12275268/11690583/5aa160d6-9e65-11e5-9fe9-d542ccade6b2.png)

After pressing backspace:
![vscode java bug2](https://cloud.githubusercontent.com/assets/12275268/11690584/5c6df5dc-9e65-11e5-9b12-79b8bf4902b4.png)

Expected:
![vscode java expected](https://cloud.githubusercontent.com/assets/12275268/11690739/0f7978cc-9e66-11e5-9c05-1b02af697321.png)

**Comment by Tyriar** [comment]
Reproduced on vscode v0.10.1, ubuntu 12.04 with this JS snippet:

```
function foo() {
  return 1;
};
```

Looks like the code that handles the bracket matching is intercepting the backspace keypress, this should only happen when a range is not selected.

Note that this only occurs if the cursor/anchor is in between the brackets, not at the end of the return.
