### ISSUE TITLE
Accidentally broke the sidebar

### ISSUE THREAD

**Issue by Cristian-A** [microsoft/vscode#114043]
I don't have any idea how this could ever happen:
<img width="416" alt="Screenshot 2021-01-08 at 17 10 21" src="https://user-images.githubusercontent.com/30161685/104037319-dc8bd400-51d4-11eb-913e-a64b32520422.png">
As you can see I now have 2 source control tabs and one of them is the actual "find and replace" tab. I might have accidentally dragged one icon onto the other while the app was loading something and so it froze for a second and did this to the tabs.

Also, it's gone from the menu as well:
<img width="327" alt="Screenshot 2021-01-08 at 17 17 11" src="https://user-images.githubusercontent.com/30161685/104038445-69cf2880-51d5-11eb-999d-2be7bfbed66b.png">

- VSCode Version: 1.52.1
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. Open a project
2. Drag your sidebar icons onto one another

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
I can repro this only if I do following

- Move Search view into Source control views
- Move source control views out into its own view container

I do not think this can be done automatically other than user interaction. You can always use `Reset Locations` command to reset all.

**Comment by Cristian-A** [comment]
@sandy081 so for you it's completely normal behaviour that when you drag an icon into another, the other tab name (find and replace) gets replace by the dragged one. See the picture, and tell me whether it's normal that the find and replace tab has the title "source control"...

**Comment by sandy081** [comment]
>  so for you it's completely normal behaviour that when you drag an icon into another, the original tab name gets replaced by the dragged one.

I don't think this is happening here right? When you moved Search views into Source control, Original tab name and icon are still applied. It is still true when you move all other Source control views out of Source control. As a result, search view remains as the only view in Source control. The original tab name and icon still remain and hence search view got Source control icon and name.

**Comment by Cristian-A** [comment]
Well, I'm a programmer and I find this behaviour very confusing anyways. To me it doesn't make any sense at all. Why would you rearrange tabs and then get the wrong names for them...

**Comment by sandy081** [comment]
I do not think VS Code is doing this automatically and all actions are performed by the user and works in according to the user actions. May be we are not on same page, can you please explain your thinking, probably by providing the steps to repro and what is the expected behaviour.
