### ISSUE TITLE
iPadOS: Workbench loses focus when switching tabs

### ISSUE THREAD

**Issue by jsjoeio** [microsoft/vscode#114012]
I would be happy to help with this if given some guidance on where to start.

- VSCode Version: 1.53.0-insider
- OS Version: iPad 14.1 (18A8395)
- Commit: 01089c0a5052432594a177f90ad9f3148ec2a6a2
- Date: 2021-01-07T05:25:51.740Z
- Browser: Mozilla/5.0 (iPad; CPU OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

## Steps to Reproduce:

1. On iPad, open Codespaces in Chrome
2. Open a file in the Workbench and type in file
3. Switch to a new tab
4. Switch back to Codespaces

## Expected
Cursor should be in same place in file and Workbench should be focused

## Actual
Workbench is not focused

See video:

https://user-images.githubusercontent.com/3806031/103953627-b7796180-50ff-11eb-8aca-a612c0aa4ca3.MP4

Does this issue occur when all extensions are disabled?: Yes

**Comment by jsjoeio** [comment]
@vscodebot not a duplicate!

**Comment by isidorn** [comment]
Sorry for the slow response, this somehow slipped through my fingers.
Potential solution would be to introduce a super simple workbench contribution to use the [`IHostService.onDidChangeFocus`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/host/browser/host.ts#L28) and than react and focus the editor.
It would also be interesting to see if this event is fired at all in this case.

**Comment by isidorn** [comment]
Actually I can not reproduce this with latest insiders and latest iPad OS. Thus closing.
Please let me know if you still see this and we can reopen
