### ISSUE TITLE
package installation for python

### ISSUE THREAD

**Issue by rafi6243** [microsoft/vscode#114029]
Issue Type: <b>Feature Request</b>

please help me. I cannot install python packages using pip due to some proxy issues, so can u make some changes as your extension are downloaded. it will be really helpful.
how can be packages installed not using pip

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.10586

**Comment by joaomoreno** [comment]
>  I cannot install python packages using pip due to some proxy issues

How is this related to VS Code?

**Comment by rafi6243** [comment]
I was just asking that it would be great if the packages were installed just like extensions on the vs code

**Comment by joaomoreno** [comment]
Got it. This is a scenario we don't support at all. Thanks.
