### ISSUE TITLE
Website keybindings font issue

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#11401]
Reported by @nocksock

OS - OS X El Capitan 
Browser - Chrome 52.0

https://code.visualstudio.com/docs/customization/keybindings

![image](https://cloud.githubusercontent.com/assets/2449568/18173834/0423043e-7020-11e6-9384-3dae74f249dc.png)

**Comment by waderyan** [comment]
Cannot repo

👍 Mac - Chrome

![image](https://cloud.githubusercontent.com/assets/2449568/18173166/71e8e91e-701d-11e6-848f-4f94eb85dc2e.png)

👍 Mac - Firefox

![image](https://cloud.githubusercontent.com/assets/2449568/18173198/99644fa6-701d-11e6-808a-d6b4b0f58a86.png)

👍 Mac - Safari

![image](https://cloud.githubusercontent.com/assets/2449568/18173225/aeb2089e-701d-11e6-8621-0690e6534ea0.png)

👍 Windows - IE

![image](https://cloud.githubusercontent.com/assets/2449568/18173252/c70c44ea-701d-11e6-9277-8544bf16a542.png)

👍 Windows - Firefox

![image](https://cloud.githubusercontent.com/assets/2449568/18173298/f67b405a-701d-11e6-9da3-1aadb223183c.png)

👍 Windows - Chrome

![image](https://cloud.githubusercontent.com/assets/2449568/18173313/03ea2f1c-701e-11e6-8b2d-306647f86dbb.png)

**Comment by nocksock** [comment]
It might have something to do with the webfont. On Your Screen it's a different font than in mine. That can be seen best with the K: 

![](http://riedemann.co/s/nnKmAt.png) vs ![](http://riedemann.co/s/T7iwQC.png)

On my System the Font displayed is `Lato`.

Also it's working in FF here too. 🤔

**Comment by waderyan** [comment]
@nocksock what is FF?

**Comment by mrmlnc** [comment]
@waderyan, Firefox :santa:

**Comment by waderyan** [comment]
Ah. I see. 

@bgashler1 do you know anything about why @nocksock would be seeing different fonts on Chrome than me? His keybindings page is broken.

**Comment by bgashler1** [comment]
@nocksock can you try these steps

Right click on the text that's having an issue and click "Inspect Element"

![screen shot 2016-09-06 at 3 21 51 pm](https://cloud.githubusercontent.com/assets/11839736/18293249/81f57430-7446-11e6-984e-4f45dcdbd17b.png)

Then click on the text I've underlined above on the far right panel
![screen shot 2016-09-06 at 3 22 30 pm](https://cloud.githubusercontent.com/assets/11839736/18293258/915ebf58-7446-11e6-8e0f-9f086818a261.png)

Replace this text with just `sans-serif`
![screen shot 2016-09-06 at 3 23 00 pm](https://cloud.githubusercontent.com/assets/11839736/18293279/aa276508-7446-11e6-9374-df9f3bb1b015.png)

Does your browser now render fonts that look like this?
![screen shot 2016-09-06 at 3 24 47 pm](https://cloud.githubusercontent.com/assets/11839736/18293280/afbd0702-7446-11e6-85b9-ee0cbcd4086d.png)

**Comment by nocksock** [comment]
Will do as soon as I get back to my MacBook on Saturday!

**Comment by nocksock** [comment]
Yes it does. 

![](http://riedemann.co/s/D0Dy17.png)

It also works when I just remove Lato from the font-family - which I checked is *not* installed locally.

![](http://riedemann.co/s/8UnCVP.png)
