### ISSUE TITLE
VS Code randomly rewrited my new code with 1 month old code - where is backup? My code is gone

### ISSUE THREAD

**Issue by Pietro228** [microsoft/vscode#114090]
- VSCode Version: 1.52
- OS Version: Windows 10 Home 20H2

Steps to Reproduce:

1. Open VS Code.
2. It will randomly found newer file version and asks me if I want to get newest file changes.
3. I said yes.
4. And it rewrited my (800 lines) code to state that was 1 month ago (250 lines) and I was not able to get it back :(

I'm sad, because all my work is gone.. :/ **I was making css style for my web, so I through that I wouldn't need a GitHub backup. But from nowhere came that message to get newest file changes - where did VS Code found that old file save? Why did it asked after 1 month and replaced with the old one?**

**Is here any backup or how can I get this file back?**

Please help me :( Thank you for your help, Peter

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
> It will randomly found newer file version and asks me if I want to get newest file changes

I am not aware of that, do you have a screenshot of this flow or steps to reproduce?

**Comment by Pietro228** [comment]
I don't know how to reproduce it, I have opened VS as usual and it showed me this message

**Comment by bpasero** [comment]
@Pietro228 can you at least recall how you got asked? Was it a dialog or notification?

I am asking because I don't know of such a dialog in VSCode itself that would ask to fetch newer changes.

PS: to ensure, you talk about VSCode, not Visual Studio right?

**Comment by Pietro228** [comment]
Yes, I'm talking about VSCode. In the bottom right corner appeared box with that text in application - like dialog box.

**Comment by bpasero** [comment]
Can you recall if it was maybe this:

![image](https://user-images.githubusercontent.com/900690/104162812-99f51200-53f5-11eb-9665-a51fbabdea75.png)

**Comment by Pietro228** [comment]
Yeah, this is propably it. But I did not noticed that compare.. I'm stupid 😅 I clicked overwrite, because I through that it will not get back very old changes

**Comment by bpasero** [comment]
Ah ok, yes that will overwrite the contents you have with the file on disk.

**Comment by Pietro228** [comment]
Oh, so there is no way how to get it back? Is here any auto backup?

**Comment by bpasero** [comment]
I cannot answer these questions without some steps to reproduce. I agree, it is unlikely that this notification and action would trigger this (a file getting reverted to a version of 1 month ago).
