### ISSUE TITLE
The window has stopped responding - Right Click in solution

### ISSUE THREAD

**Issue by MauroSergioRodriguez** [Microsoft/vscode#11406]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. Right click in any file of the solution explorer (dont move nothing)
2. Wait  1-2 minutes

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6414
