### ISSUE TITLE
workspace.asRelativePath doesn't work for URI paths

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#11403]
From verifying #10446
(on Linux, 1.5.0-insider, Commit d2c04e3789757413ae1ebfda9d88896686b6d006)
```
let input = vscode.Uri.file("/home/aeschli/workspaces/samples/docker/gooo/kl").toString();

console.log("root: " + workspace.rootPath);
console.log("input: " + input);
console.log("output: " + workspace.asRelativePath(input));
```

Output:

root: /home/aeschli/workspaces/samples/docker
input: file:///home/aeschli/workspaces/samples/docker/gooo/kl
output: file:///home/aeschli/workspaces/samples/docker/gooo/kl

I would have expected `gooo/kl`

**Comment by jrieken** [comment]
You are passing a stringified uri not a path - the behaviour then is undefined
