### ISSUE TITLE
Settings Sync syncs zoom level

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#114013]
Issue Type: <b>Bug</b>

At some point we had said that the zoom level is a setting that is not being synced. We seem to have lost that restriction.

VS Code version: Code - Insiders 1.53.0-insider (01089c0a5052432594a177f90ad9f3148ec2a6a2, 2021-01-07T05:22:09.742Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.57GB free)|
|Process Argv|--crash-reporter-id 4b0156b6-04c0-4ed1-93af-580bb689ce29|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|12.43GB (12.03GB free)|
|VM|0%|
</details>

**Comment by sandy081** [comment]
@bpasero FYI
