### ISSUE TITLE
Indicate active pane somehow

### ISSUE THREAD

**Issue by p-i-** [microsoft/vscode#114056]
Frequently I think I am typing into the terminal, only to find that my keystrokes are going into a source code pane.
Or vice versa.
It's frustrating enough that I'm creating an issue.
It is my number one annoyance on this wonderful IDE.

- You could use a slowly flashing cursor.
- You could make the background 10% lighter for the active pane.
- You could put a green rectangle around the active pane.
How about all three?

I would love to see this feature!
🙏

**Comment by sbatten** [comment]
@p-i- both the code editor and terminal support a blinking cursor. by default the source editor enables blinking and the terminal does not.

![image](https://user-images.githubusercontent.com/6561887/104194948-db29f980-53d6-11eb-8d70-063e20448a96.png)

**Comment by p-i-** [comment]
Argh, closed!
I've played with the cursor, but still it's hard to see which pane has the focus.
Lightening the background colour on the active pane would be a huge usability plus.

Edit: cross-linking this issue: https://github.com/microsoft/vscode/issues/66640

**Comment by isidorn** [comment]
I think this can nicely be solve via https://github.com/microsoft/vscode/issues/97790
So you can comment there if you think that idea makes sense
