### ISSUE TITLE
F8 widget text doesn't update if diagnostics change while the window is open

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11407]
- VSCode Version: 1.5 (Insiders)
- OS Version: Windows 10

If you edit the doc while the F8 widget is open and that causes diagnostics to update, the widget text doesn't update.

Here you can see I change the name of the function and the diagnostic (bottom) is updated, but the widget still shows the old text.

![Code fix update](https://cloud.githubusercontent.com/assets/1078012/18052295/6c316d12-6df1-11e6-834b-cdb80f166652.gif)

**Comment by dbaeumer** [comment]
@sandy081 assigning to you as our problems master. The widget comes originally from @jrieken. Might want to consult him.

**Comment by jrieken** [comment]
It is the designed behaviour. If the widget moves or hides while typing the editor view will become nervous and jumpy. That's why the color changes to greyish, press `F8` again will reconcile with the actual errors

**Comment by jrieken** [comment]
Opting  for no fix here

**Comment by DanTup** [comment]
Isn't there a way to update it without anything jumping? If the widget is a fixed size and didn't flicker but the text updated, I think this would look perfect.

It kinda looks like a bug to me as-is - the command text updates and the diagnostic text updates but the widget text does not. I understand it changes colour, but that's kinda subtle and I don't think it's obvious that means it might be stale.

**Comment by DanTup** [comment]
It's worse if you make an edit that changes the error entirely, since the error displayed and the quick fixes don't match any more :(

**Comment by jrieken** [comment]
Yeah, if there is still an error updating it makes sense (that it doesn't is actually a bug). The challenge is that the size might change depending on the error message and number of quick fixes. Also it's still unclear to me what should happen when the current error/warning goes away

**Comment by DanTup** [comment]
> The challenge is that the size might change depending on the error message and number of quick fixes.

I don't think that's a massive issue; it's below the cursor so it has room to grow/expand without affecting the user/editor too much and it might not happen that often (the lengths might not vary across the line length boundary that often).

> Also it's still unclear to me what should happen when the current error/warning goes away

I think in the absence of a better idea, the current behaviour (remove fixes, go grey) doesn't seem unreasonable here; (it's mainly the lack of updating that feels wonky to me). Another option could be to replace the text with some help info like "Press F8 to move to the next error" in addition to going grey?

**Comment by jrieken** [comment]
I have fixed the updating issues. Couldn't keep the gray frame cos that requires the zone to be in the view port (which it must not be after scrolling anymore). Instead the content now becomes gray - there is still a lot of debt and tech challenge in this seemingly simple feature... I'll revisit early Oct

**Comment by DanTup** [comment]
From your animation, this all looks great to me! 👍

**Comment by jrieken** [comment]
It only shows the happy case ;-)

**Comment by DanTup** [comment]
lol; I didn't really understand the issue you described, but it definitely solves the issue I had :)
