### ISSUE TITLE
F8 widget steals focus from document on every key press

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11408]
- VSCode Version: 1.5 (Insiders)
- OS Version: Windows 10

Steps to Reproduce:

1. Press F8 to open the diagnostics widget
2. Click in the document and try to make some changes

The first key press in the document works, but then focus seems to move to the widget(?) and the subsequent keypresses do not update the document. This makes it really hard to fix the thing the popup is telling you about as you have to put focus back in the editor for every key press (or close the F8 widget).

**Comment by jrieken** [comment]
@alexandrudima We had to add that for accessibility and screen reading purposes, right?

**Comment by jrieken** [comment]
Oh, wow. It actually jumps back after every keystroke... 😨

**Comment by jrieken** [comment]
A regression from reconciling the quick fixes while marker change...
