### ISSUE TITLE
Buffer test: Performance issue with VSBuffer#slice #76076 disabled in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114042]
A follow up from https://github.com/microsoft/vscode/pull/114041, I had to disable one test that fails in browsers:

`Performance issue with VSBuffer#slice #76076`

https://github.com/microsoft/vscode/blob/aa5064d4fd47e3e0b6cd177f0a69cbf23c06d90e/src/vs/base/test/common/buffer.test.ts#L377-L377

**Comment by alexdima** [comment]
The problem was that the test was using `Buffer` which was not defined in browsers. I've made that part of the test conditional.

**Comment by bpasero** [comment]
Thanks!
