### ISSUE TITLE
unbound breakpoints in yarn workspace typescript libraries with pwa-node

### ISSUE THREAD

**Issue by FrozenKiwi** [microsoft/vscode#114076]
- VSCode Version: 1.51.1
- OS Version: Win10

Steps to Reproduce:

1. Place breakpoints in library code in monorepo (ie, not the project currently running)
2. F5 with pwa-node.  Note breakpoints not bound
3. Switch to `node` debugger.  Breakpoints resolve normally

Does this issue occur when all extensions are disabled?: Yes/No (didn't check)

The default option for resolveSourceMapLocations seems poor for yarn workspaces.  When debugging, typescript library breakpoints are unbound, and there is no indication why. Adding the below fixes this issue and removes spam:
```
      "resolveSourceMapLocations": [
        "**",
        "!**/node_modules/**"
      ]
```
Related issues: 
https://github.com/microsoft/vscode/issues/114007
https://github.com/microsoft/vscode/issues/102042
https://github.com/microsoft/vscode/issues/107327

I searched this issue over several days without finding any mention or indication of what was wrong.   Haven't tested with insiders build/any extensions because I found a resolution, this issue is just to check whether you are aware.  I also haven't done full debugging cause time & its 4am on saturday.  Apologies if it is a dup.

Note: I see the monorepo issue is referenced in 107327 as an optimization, but the resolution appears strange to me: part of the reasoning of a monorepo is to limit your focus to a subset of your code, but it is implicit that you'll work on multiple projects at a single time (otherwise we'd just use submodules/referencing).  Restricting sourcemaps to a single folder/project is much too limiting.  At minimum, I would expect every folder in the workspace to be resolved.  

Feel free to delete this issue.

**Comment by connor4312** [comment]
It looks like this issue fell through the cracks. Please let me know if you're still running into this.

**Comment by matteodepalo** [comment]
I'm still running into this with the following configuration:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node-terminal",
      "request": "launch",
      "name": "Next",
      "command": "yarn dev",
      "cwd": "${workspaceFolder}/packages/debugger-test",
      "resolveSourceMapLocations": [
        "**",
        "!**/node_modules/**"
      ],
    }
  ]
}
```

I have a yarn workspace with a top level package.json and a `packages/debugger-test` being a next.js app with the actual app code. Adding a breakpoint makes it point to the webpack compiled file, but not the original file:

Original file location is `/workspaces/debugger-test/packages/debugger-test/pages/index.tsx`

<img width="1169" alt="Screenshot 2021-10-17 at 10 13 00" src="https://user-images.githubusercontent.com/151725/137620460-dd331221-786d-41b7-a3e1-535c364d5f2c.png">

This compiled file's path is `/pages/index.tsx`

<img width="1847" alt="Screenshot 2021-10-17 at 10 13 28" src="https://user-images.githubusercontent.com/151725/137620473-8b7a724f-4120-4164-84a8-a20de361c54f.png">

I've tried for a few days with a combination of configurations but wasn't able to have it working. If I move the content of packages/debugger-test into the root folder (basically remove yarn workspaces) then it all works as expected.
