### ISSUE TITLE
Please add the ability to whitelist/blacklist certain notifications

### ISSUE THREAD

**Issue by zwhitchcox** [microsoft/vscode#114069]
So, for a regular plugin, would just uninstall the plugin if it kept giving me annoying notifications that I don't want, but with VSCode, you don't have that option, because they are built into application itself.

Can you please create a way to silence the infuriating notifications that pop up all the time that no one wants? People are trying to work.

**Comment by zwhitchcox** [comment]
Please re-open this issue. This is the exact opposite of the issue you claim is a "duplicate".

That issue is asking about turning off notifications from plugins. I'm wanting to turn off notifications from VS Code itself.

Like for instance, how it seemingly creates a popup every time you close a terminal saying it exited with some error code or something that I don't care about and interrupts my workflow.

And there are a lot of notifications like that, and it is extremely annoying.

So, this is not a "duplicate", please unmark it as a "duplicate". This is its own issue.

**Comment by bpasero** [comment]
@zwhitchcox we have support in VSCode notifications to add a "Do not show again", which then will cause the notification to never show again. Can you tell for which notification you would like to configure to hide it?

I don't think that hiding all notifications is currently an option.

**Comment by zwhitchcox** [comment]
OK, I will start taking screenshots whenever I get one so I can provide you with examples. Thank you for your help.

**Comment by bpasero** [comment]
Ok

**Comment by zwhitchcox** [comment]
![Screenshot from 2021-01-12 09-01-53](https://user-images.githubusercontent.com/4328800/104324148-0b47ca00-54b5-11eb-9995-f9ffcc3c9d9d.png)

**Comment by zwhitchcox** [comment]
There's also the notification "Ignorance is bliss, we will not show any more notifications for this plugin" or something where they literally show a popup notification after you just asked them not to show any more popup notifications for something, I think it's "Suppress Errors".

I would even be ok if they made it where these notifications just fade away after a few seconds (although I would rather have the ability to turn them off), but I have to drop what I'm doing and dismiss the notification, and as a vim user, I do everything from the keyboard, and there is no way to dismiss them from the keyboard, so I have to actually drag my mouse, find where the cursor is, and get used to using a mouse again (your mind sort of has to calibrate how far moving your hand is going to move your mouse), and click on the X (and God help you if you miss the X, because who knows what that's going to do). And in the case of "Suppress Errors", right after that, there is another popup which shows up after a slight delay, and you have to exit that.

It just completely interrupts my rhythm, and especially when you're working on a complicated project, it is vital to eliminate all distractions you can. I mean, I guess it only happens a few times a day, and I guess the error above about the terminal process exiting is the only one you can't dismiss forever (or at least until you  close the program and open it again), but a few times a day over several years is a lot, especially when it interrupts your work flow.

**Comment by bpasero** [comment]
> I would even be ok if they made it where these notifications just fade away after a few seconds

Most do, but not if an error is shown or input is asked for (via buttons). It is hard to know if a notification shows up because input is needed or the user really needs to be told or not.

> and there is no way to dismiss them from the keyboard

That is just not true, there are tons of commands that allow you to do everything with regards to notifications:

![image](https://user-images.githubusercontent.com/900690/104333624-c0987300-54f1-11eb-8c88-77a034037787.png)

We try really hard to allow you do operate notifications without a mouse, if something is missing please file a new issue.

I like that you posted a screenshot of a notification that you find annoying. Can you report it as individual issue so that we can think about alternatives? I somewhat agree that maybe notifications could selectively show closer within the component where it originates from (e.g. inside the terminal).

**Comment by zwhitchcox** [comment]
Ultimately, I think the solution should probably be to have the ability to disable all popups, which are notoriously annoying to users. I think the best solution for me personally would be to have them display in a little notification center in the sidebar. I personally would never look at them (and maybe this would cause more reported errors because users would not see something that would cause them to have errors). For me personally, I don't think I've ever seen a useful toast notification aside from maybe the ones that say "Would you like to install the extension for this file type?" (although a better solution, I think would be allowing users configurations for plugins and allowing them to sign in to VS Code, but  I realize that has its own challenges (and I realize there is a plugin for this too, but that solution is a little more complicated than just signing in)). But it would give users at least an option to display notifications in a less obtrusive way.

The next best solution would be a method to turn off all notifications.

The solution you gave of using a keyboard shortcut *would be* good, except you can't use the shortcut when the terminal is open, which is usually when that particular notification shows up, i.e., you're closing a terminal to create a new one, or you're consolidating all your terminals.

But I don't know, maybe this is a bug?

**Comment by zwhitchcox** [comment]
One other thing, I don't think there's anywhere else you could report the notification in the screen shot, because once you close the terminal, you obviously can't use that terminal to report that the terminal was closed.

Idk, though, maybe you're suggesting report it in the notification bar in the little status bar at the bottom of the window? I do think that would be a better place for it.

**Comment by zwhitchcox** [comment]
Also, btw, I hope I'm not coming across too negative, the product your team has made is amazing, and really, really good on 99.9999% of things, it's just this one thing that kind of grinds on my nerves over time, and unfortunately, that's the only time you're going to hear from me. But great work, and it's much appreciated!

**Comment by bpasero** [comment]
@zwhitchcox 

> But I don't know, maybe this is a bug?

As for keyboard support from terminal it would be good to file this as individual issue, I think we have a list of commands we allow from the terminal.

> Ultimately, I think the solution should probably be to have the ability to disable all popups, which are notoriously annoying to users. 

As I said before, some notifications may be critical for the flow of an extension. Just to give an example: an extension might require you to sign in but that failed and a notification is shown. If you hide this notification how would you know that something went wrong? In the end we cannot tell if a notification is important to show to the user or not. We have a heuristic by looking for error severity and the fact that buttons are added, but that might not be correct all the time.

**Comment by zwhitchcox** [comment]
Ok, thank you for your suggestions. I think I'm going to close this issue and split it into 3 separate issues, because any of these ways could potentially have been a solution for me:

1. ability to close all notifications from terminal through keyboard shortcut #114268 
2. ability to turn off the "terminated with exit code: 1" notification #114271
3. ability to keep all notifications minimized #46676 which you already mentioned.

Thank you for your help..you're a superstar!

**Comment by bpasero** [comment]
Thanks a lot, going on in individual issues is a good way forward 👍
