### ISSUE TITLE
Provide API for opening images

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#114054]
Something similar to `vscode.workspace.openTextDocument` except for opening image files would be helpful. Right now, `vscode.workspace.openTextDocument` throws a "File seems to be binary and cannot be opened as text" error for images.

**Comment by mjbvz** [comment]
You can use the [`vscode.open` command](https://code.visualstudio.com/api/references/commands) for this

**Comment by wwlorey** [comment]
@mjbvz For more context I'm using a virtual file system. `vscode.open` works for text files but for images it displays this error:

<img width="952" alt="Screen Shot 2021-01-08 at 2 19 54 PM" src="https://user-images.githubusercontent.com/22795803/104075003-739d5f80-51c6-11eb-8247-9edc25072084.png">

`vscode.open` works as expected for local image files.

**Comment by Jonatthu** [comment]
@mjbvz Why this is closed? I still having this issue

**Comment by mjbvz** [comment]
If the image preview does not work for custom files system, please open a new issue to track that separately
