### ISSUE TITLE
Suggest box fails to regrow when backspacing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#114030]
0. F1 > Reset Suggest Widget Size
1. Open an empty TS file
2. Trigger suggest
3. Type `monaco`, notice the suggest widget gets shorter due to only being 4 results
4. Backspace slowly, 🐛 the widget fails to regrow as more suggestions become available

![recording (4)](https://user-images.githubusercontent.com/22350/104015342-50909280-5169-11eb-9206-17d53200fd41.gif)

**Comment by jrieken** [comment]
Not for me... Tho, I do see different suggestions to begin with. In what project are you trying this?

https://user-images.githubusercontent.com/1794099/104017400-5b264880-51b8-11eb-809f-bddb57632bc5.mov

**Comment by joaomoreno** [comment]
This was a brand new folder, no project.

**Comment by jrieken** [comment]
still not reproducing with a brand new folder and a single file.

**Comment by joaomoreno** [comment]
Yeah I can't repro on my other machine as well. 😢 

Let me try this again tomorrow on the original machine, see if I can repro.

**Comment by jrieken** [comment]
\closedWith https://github.com/microsoft/vscode/commit/dcce02644eac4e2dd749480b471a331928a7639c
