### ISSUE TITLE
Visual editor

### ISSUE THREAD

**Issue by tpangalala90** [microsoft/vscode#114034]
I have been trying to type on my visual code editor but for some reason, it will not let me do so and I am reaching out to see if there is anything we can do to solve this issue? This has been slowing me down on a few projects that I have been working on. Thank you in advance and looking forward to hearing from you!
Takondwa Pangalala

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill data required by issue template ( or copy content that is provided if you issue report from VS Code).

Also first thing to check in this case if issue is reproducible with all extension disabled.
