### ISSUE TITLE
File searching not found

### ISSUE THREAD

**Issue by valtido** [microsoft/vscode#114021]
Issue Type: <b>Bug</b>

When copying a file path from dev.azure.com repo, which is usually displayed as "/src/components/myfile.ts" notice the leading "/", I then go to VS Code press "ctrl + p" paste the link "/src/components/myfile.ts" no files are found. 

I have to then go to the begining and remove that first character "/" then the file is found. 
 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-1031-azure

**Comment by roblourens** [comment]
In that format, it is an absolute path, and we will search for the actual absolute path outside of your workspace. The "root" on dev.azure.com is the workspace.
