### ISSUE TITLE
The icon of New Folder should be more easily understandable

### ISSUE THREAD

**Issue by ercmat** [microsoft/vscode#114016]
Issue Type: <b>Feature Request</b>

When I want to create a new folder in a file tree, there is sometimes a pause to think about which icon the New Folder function is. I don't know exactly why so, but maybe because the icon of New file and that of New Fodler look very similar and that makes me confused a little bit. Not a big issue, but just for a slightly better experience.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by yume-chan** [comment]
Maybe move the "plus" part to the bottom right?

In codicon (icon pack used in Code), many icons already have their "operation indicator" at bottom right

https://microsoft.github.io/vscode-codicons/dist/codicon.html

![image](https://user-images.githubusercontent.com/1330321/103973571-a174ab00-51aa-11eb-9be1-69d18e60aaab.png)
![image](https://user-images.githubusercontent.com/1330321/103973605-bc471f80-51aa-11eb-96f0-2ec33635728d.png)
![image](https://user-images.githubusercontent.com/1330321/103973561-9a4d9d00-51aa-11eb-94b1-b0e10f355294.png)

GitLens also have this convention

![image](https://user-images.githubusercontent.com/1330321/103973670-f1537200-51aa-11eb-9df5-71bfc142bd8f.png)
(the first one, Stash all changes icon, was provided by GitLens)

Also in Fluent UI Icons

https://developer.microsoft.com/en-us/fluentui#/styles/web/icons

![image](https://user-images.githubusercontent.com/1330321/103973749-2bbd0f00-51ab-11eb-9564-0216cb10a839.png)

**Comment by isidorn** [comment]
I personally would not change this since our users are already used to this. Though I think we should keep this in mind when updating all our icons thus for now leaving this feature request open.

**Comment by ercmat** [comment]
@isidorn @yume-chan Thank you for kind consideration 🙂

**Comment by misolori** [comment]
Thanks for the feedback, we did try out the bottom right location when we first originally re-designed the icons but felt like it was changing too much so we opted for where it's been. It would be interesting to try this out though since it would match the rest of the modifier locations we have:

![image](https://user-images.githubusercontent.com/35271042/104047235-2d300c80-5196-11eb-8dc9-517667c2d89d.png)

**Comment by isidorn** [comment]
@misolori nice work, I like these. I suggest you just go ahead and update the icons so we get feedback in insiders from users.

**Comment by misolori** [comment]
This is now updated:

![image](https://user-images.githubusercontent.com/35271042/104239409-51e2e900-540f-11eb-9b50-c6c52f6e05a1.png)

I also updated the reactions icon that had the `+` in the top right:

![image](https://user-images.githubusercontent.com/35271042/104239431-59a28d80-540f-11eb-933d-ef5abf7502cb.png)

**Comment by ercmat** [comment]
@misolori Thank you for the quick implementation! 🙂

**Comment by isidorn** [comment]
@ercmat @yume-chan try this out in vscode insdiers and let usk now how you feel about the change

**Comment by yume-chan** [comment]
I like the new ones. The difference between "file" and "folder" icons is their top portion, now it's very clear.

![image](https://user-images.githubusercontent.com/1330321/104301051-2a207d80-5502-11eb-87e6-db3d518aeef2.png)

One subtle problem, the gap between "plus" and other parts looks too small that they are almost connected. Compare with https://github.com/microsoft/vscode/issues/114016#issuecomment-756902639 (resized to similar size), I prefer the original design, the staggering makes them not so rigid and "bottom heavy".

**Comment by gjsjohnmurray** [comment]
I agree with the point @yume-chan makes about how the "plus" is hard to distinguish from the file and folder edges. Either an offset or an extra pixel of space between the elements might help.

**Comment by isidorn** [comment]
@misolori I agree with this feedback, let's reopen for discussion. Plus is hard to distinguish

**Comment by ercmat** [comment]
@isidorn The insider ver. has successfully cleared my original concern now. Thank you very much 🙂

**Comment by misolori** [comment]
I've increased the gap between the `+` and offset it on the file icon

![image](https://user-images.githubusercontent.com/35271042/104488258-f8033000-5582-11eb-9df5-4458a1694781.png)

**Comment by isidorn** [comment]
Lovely, thanks!

**Comment by isidorn** [comment]
We did not recieve negative feedback and I think the change makes sense -> verified
