### ISSUE TITLE
Black patches on the window is seen after waking up the desktop from sleep.

### ISSUE THREAD

**Issue by jaskeerat789** [microsoft/vscode#114081]
# Env info
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.04.1
- GPU: Nvidia GTX 1660 super
- GPU Driver Version: 450.60.2

# Bug Description
Whenever i put my desktop to sleep with my VS Code running, i see multiple dark patches on window and entire terminal tab. some of the dark patches are removed as i take my cursor near to them or in the patch area. terminal patch is fixed partially when cursor is  moved over it. This behavior is consistent and occurs every time i put my desktop on sleep. I have tried with disable all the extensions but the issues can't be fix. This could be a OS and GPU driver related issues but i not very sure of it. 

  
![image](https://user-images.githubusercontent.com/38110126/104102809-aaf23600-52c4-11eb-96e5-a9f6ce373bef.png)
_Before moving cursor over the terminal window_

![image](https://user-images.githubusercontent.com/38110126/104102819-be9d9c80-52c4-11eb-84e5-625139b5254c.png)
_After changing the terminal tab_

![image](https://user-images.githubusercontent.com/38110126/104102866-150adb00-52c5-11eb-817a-25af7d2412ce.png)
_After changing the workspace tab and returning back to same tab_

# Steps to Reproduce:

1. Open VS code and put your PC to sleep.
2. Wake you PC and switch to the VS code window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Disable hardware acceleration in the runtime https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
