### ISSUE TITLE
Language/Css, SCSS and less wrong description

### ISSUE THREAD

**Issue by patrickmohrmann** [microsoft/vscode#114091]
- VSCode Version: 1.52.1
- OS Version: Windows

Steps to Reproduce:

1. the tutorial https://code.visualstudio.com/docs/languages/css#_step-3-create-tasksjson has written down [...] run Terminal > **Configure Tasks** and click Create tasks.json file from templates. [...]  the Bold part should actually be:  **Configure Default Build Task...** the other one did not lead to the described instruction.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by patrickmohrmann** [comment]
Improvement

**Comment by alexr00** [comment]
When I run the **Configure Tasks** command I still see the "Create tasks.json file from template" option. Can you please provide a gif or screen shot of what you're seeing?
