### ISSUE TITLE
Dirty files are empty / Backups folder is empty

### ISSUE THREAD

**Issue by FatalBulletHit** [microsoft/vscode#114022]
- VSCode Version: 1.52.1
- OS Version: Win 10 2004

Steps to Reproduce: _Unknown_

Does this issue occur when all extensions are disabled?: _Probably (unknown)_

I've a few unsaved/dirty/untitled files open and normally I just close VSCode and the next time I start it, they will show up as expected.
But it has happened for the 2nd time now in a span of multiple months, that the unsaved files are empty as is the Backups folder and all work is gone.
Auto save is set to `afterDelay` (1000ms).

No idea if this could be connected to the issue at all, but this time (I don't know about last time) it happened after starting the PC from hibernation. However, VSCode was not open during hibernation. I also sometime accidentally start VSCode and then close it asap, but that also works fine normally.

**Comment by bpasero** [comment]
If auto save is set to 1s, I assume you talk about "Untitled" files that are not restored, not normal files that get saved after 1s anyway?

**Comment by FatalBulletHit** [comment]
Correct.

**Comment by bpasero** [comment]
Ok, without some reliable steps to reproduce it will be hard to find a fix. E.g. it is not clear to me what could happen when you hibernate or restart the OS while VSCode is running on your system. That should typically not result in the backups to get lost. 

We have a way to persist logs for VSCode, I wonder if you could upload them to this issue. They are inside `C:\Users\<name>\AppData\Roaming\Code\logs`

**Comment by FatalBulletHit** [comment]
These are the [logs.zip](https://github.com/microsoft/vscode/files/5790466/logs.zip) from when the untitled files were fine to them being deleted. I wish I'd be able to provide more useful information, but I've no idea what could've caused it.

On a side note, I was able to restore the untitled files, but I had to do a content search for one of my variables in the shadow copy of my disk because the file names are randomized (why is that?).

**Comment by bpasero** [comment]
Thanks, I cannot find something related unfortunately.

The backups are the hash of their file path simply because we need to ensure that any file on disk is persisted with a fixed length name in our backup directory.

**Comment by FatalBulletHit** [comment]
Interesting, would you mind telling me how exactly they're generated or where I can find that info? It'd make restoring easier if it's ever going to happen again (as it's significantly faster to do a name search rather than a content search).

**Comment by bpasero** [comment]
It is a simple MD5 hash of the entire absolute path of the file.

**Comment by FatalBulletHit** [comment]
I just did some trial and error and (at least regarding unsaved files) it seems to only be the file name (e.g. `Untitled-1` was saved as `13264068D108C6901B3592EA654FCD57`), but thanks! :)

**Comment by bpasero** [comment]
Ah yes, for untitled it is just the name 👍
