### ISSUE TITLE
Issue in code helper

### ISSUE THREAD

**Issue by hernanimattos** [microsoft/vscode#114079]
Code helper use 100% of cpu

**Comment by DennisNDean** [comment]
I'm having the same issue, on a brand new MacBook Pro with a brand new install (minutes old) of VS Code. As soon as VS code opened, my fan spun up and Activity Monitor showed "code helper (renderer)" using >500% of the CPU. VS Code was open but had no files/project open or active. It's a brand new install with no plugins, etc.

**Comment by mjbvz** [comment]
Closing as we need more information from the original poster. If you are seeing a similar issue, follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information and open a new issue with that information
