### ISSUE TITLE
tsc version mismatch more information button does nothing

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11410]
- VSCode Version: Code - Insiders 1.5.0-insider (d2c04e3789757413ae1ebfda9d88896686b6d006, 2016-09-01T06:11:55.766Z)
- OS Version: Linux x64 4.4.0-36-generic, Ubuntu 16.04

I got this message when updating this morning 

> A version mismatch between the globally installed tsc compiler (1.5.3) and VS Code's language service (1.8.10) has been detected. This might result in inconsistent compile errors.

I clicked more information and it did nothing. No errors in console.

**Comment by dbaeumer** [comment]
The button was a noop at the beginning since I was missing the correct forward link. The actual link got add via commit: 64a75fa8bb882d2de625aabf1a0577e343479f9f via got puhsed after d2c04e3.

@egamma & @bpasero tested this in the latest insider and it worked for them. Closing as invalid.
