### ISSUE TITLE
Debug expand/collapse misalignement

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11411]
- VSCode Version: Code - Insiders 1.5.0-insider (d2c04e3789757413ae1ebfda9d88896686b6d006, 2016-09-01T06:04:41.555Z)
- OS Version: Darwin x64 15.6.0

`TypeScript`:
![image](https://cloud.githubusercontent.com/assets/1723815/18180030/140fc8d6-7053-11e6-8a61-2d3488ff232a.png)

Triangles appear to be between items:
![image](https://cloud.githubusercontent.com/assets/1723815/18180061/31daea6c-7053-11e6-9045-1589c6fc3290.png)

**Comment by isidorn** [comment]
Dup of #11352
