### ISSUE TITLE
Method signature info overflows the box

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#114173]
Steps to Reproduce:

1. Type `vscode.commands.executeCommand()`
2. On the parenthesis, the info overflows 🐛 

![](https://memes.peet.io/img/21-01-0029ed50-98df-40ae-b7cc-7b0a351cce9e.png)

**Comment by jrieken** [comment]
@alexdima or @mjbvz did you change anything here?

**Comment by alexdima** [comment]
AFAIK I didn't touch the parameter hints, I just did some refactorings in the modes content hover.

**Comment by eamodio** [comment]
Seeing the same thing with contents overflowing the hovers.

I wonder if its related to https://github.com/microsoft/vscode/issues/111572

**Comment by mjbvz** [comment]
@jrieken Possibly d66e65fcdd90644685f4afa4ed369dad0e189a95 but that was merged back on Dec 8th. It just added an extra call to `scanDomNode` after the markdown finishes rendering

**Comment by mjbvz** [comment]
Oh actually, @alexdima I think it's cbea242dcbb3709a8cecc59f442d897515bba502 which changed the class name but didn't update this location:

https://github.com/microsoft/vscode/blob/cbea242dcbb3709a8cecc59f442d897515bba502/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L372

 Checking now

**Comment by mjbvz** [comment]
Yes that was it. Just pushed a change that updates the class name, which fixes the issue for me

**Comment by alexdima** [comment]
Oh no, very sorry about that!
