### ISSUE TITLE
replace highlighted does not function correctly

### ISSUE THREAD

**Issue by stan-ac** [microsoft/vscode#114141]
- VSCode Version:1.52.1
- OS Version:Windows_NT x64 10.0.19041

**sorry this IS a duplicate** 

The replace selected does not work properly unless the selected option is the first thing that is selected  when replace is invoked. 

Steps to Reproduce:

1. select text 
2. do replace 
3. add text to replace 
4. select 'selected text symbol'
5. text selection will have no effect on operation

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@stan-ac can you please share a screen recording to help explain the issue?
