### ISSUE TITLE
going to a new line

### ISSUE THREAD

**Issue by MountahaBoukallel** [microsoft/vscode#114169]
Issue Type: <b>Bug</b>

every time i click (enter) to go o the next line it goes done for 1s and my line get deleted again

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.6
vscode-JS-CSS-HTML-formatter|lon|0.2.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.13
vscode-icons|vsc|11.1.0

</details>

**Comment by sbatten** [comment]
I don't quite understand the issue being reported. Could you provide more details and perhaps a short video of your experience? Also, please try with extensions disabled.

**Comment by sanket-bhalerao** [comment]
@MountahaBoukallel can you check the following
1. do you have file autosave enabled?
2. do you have formatOnSave enabled?
3. can you replicate this issue by disabling "prettier-vscode" and/or "vscode-JS-CSS-HTML-formatter"

I think this issue is due to the format tool is removing the empty line as your file does an autosave.

**Comment by MountahaBoukallel** [comment]
Yes! It was due to "vscode-JS-CSS-HTML-formatter" after I disabled it everything went back to normalThank you Sent from Mail for Windows 10 From: Sanket BhaleraoSent: Tuesday, January 12, 2021 4:39 AMTo: microsoft/vscodeCc: MountahaBoukallel; MentionSubject: Re: [microsoft/vscode] going to a new line (#114169) @MountahaBoukallel can you check the followingdo you have file autosave enabled?do you have formatOnSave enabled?can you replicate this issue by disabling "prettier-vscode" and/or "vscode-JS-CSS-HTML-formatter"I think this issue is due to the format tool is removing the empty line as your file does an autosave.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
