### ISSUE TITLE
Author identity unknown error when git config is properly set

### ISSUE THREAD

**Issue by vicchimenti** [microsoft/vscode#114168]
- VSCode Version: Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z

- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Cloned github repo
2. make changes to any file and save
3. commit changes via Source Control
4. Get this error: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: no email was given and auto-detection is disabled
> git config --get-all user.name

When I check the git config everything looks good: $ git config --list --show-origin
file:/home/victor/.gitconfig    user.name=vicchimenti
file:/home/victor/.gitconfig    user.email=myname@email.com
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/vicchimenti/law-newsroom.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master

Does this issue occur when all extensions are disabled?: Yes/No Need the Git Hub extension active to use Source Control

**Comment by eamodio** [comment]
This behavior is by design -- see #110880, but I just added a new `git.requireGitUserConfig` setting to control this behavior -- see #114433

**Comment by vicchimenti** [comment]
Thank you for the input, I have been able to sync all my working repos to my new local machine by removing the --global and adding my user.name and user.email manually to each repo individually.

I don't remember having this last issue on my previous machine but if the explanation is that this is expected behavior by design then it feels like a challenging user experience by design. When a user is logged into an IDE this configuration should carryover through their profile shouldn't it?
