### ISSUE TITLE
vscode修改左侧资源管理器字体大小

### ISSUE THREAD

**Issue by a1003584293** [microsoft/vscode#114138]
无法更改资源管理器（左边显示目录栏）的字体大小，改完Microsoft VS Code\resources\app\out\vs\workbench\ 目录下的workbench.main.css文件，打开搜索  .monaco-workbench .part>.content    修改为15px后提示vscode损坏

**Comment by yume-chan** [comment]
Duplicate of #519

You can insert custom css with [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui).
