### ISSUE TITLE
Sync disabled because device making too many requests.

### ISSUE THREAD

**Issue by deverl** [microsoft/vscode#114117]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Sync disabled because device making too many requests.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.67-09356-gf3ed4c0c4a31

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (4 x 1799)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|6.48GB (6.47GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id d1de527d-6456-41d1-9d9b-4628a61b24b2|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.10.1
vscode-intelephense-client|bme|1.6.1
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
php-debug|fel|1.14.5
smarty|imp|0.3.0
vscode-docker|ms-|1.9.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
cpptools|ms-|1.1.3
vsliveshare|ms-|1.0.3449

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt875:30241730
vsjup459:30237187

```

</details>

**Comment by sandy081** [comment]
Can you please provide the settings sync log during the time this issue happened. This will help us to know why this error has occurred. You can view settings sync log using `F1 > Open View > Log (Settings Sync)`

**Comment by deverl** [comment]
It is working, so we can close this case. I will try to capture the logs and reach out if it happens again.
