### ISSUE TITLE
Support multi cell selection in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#114156]
The notebook is a list of cells so we may want to support multiple selection, similar to how it works in other list views in the workbench.

**Comment by misolori** [comment]
All of these options assume the user is holding down shift/ctrl to select multiple cells and also adds an item to the status bar for total selection count.

## Option 1

This option simply re-uses the current selection into the other cells.

https://user-images.githubusercontent.com/35271042/104352874-13573800-54bc-11eb-90a1-fdc37374174f.mov



## Option 2

This option also re-uses the current selection but adds a ✔️ to indicate a cell has been selected in multi-select

https://user-images.githubusercontent.com/35271042/104352889-16522880-54bc-11eb-8924-8fe8cc57c45d.mov



## Option 3

This options adds a background color to indicate a cell has been selected in multi-select

https://user-images.githubusercontent.com/35271042/104353369-a85a3100-54bc-11eb-9546-96930a7774a8.mov

## Option 4

This options adds a background color for multi-selected cells but only shows the border on the active cell. This matches Jupyter's behavior.


https://user-images.githubusercontent.com/35271042/104354104-9331d200-54bd-11eb-9d91-9f62888b8bdd.mov

**Comment by misolori** [comment]
Open questions:
- Does selecting multiple cells and then clicking the run button only execute the selected cells?
- What about clicking a run button from a cell at the bottom?

**Comment by rebornix** [comment]
> Does selecting multiple cells and then clicking the run button only execute the selected cells?
> What about clicking a run button from a cell at the bottom?

We will sync the cell selections info to the extension host and the extension is fully responsible for execution, the extension can control the behavior: whether all selected cells should be executed, and in visual sequence or selection sequence.

**Comment by claudiaregio** [comment]
Great work @misolori! Thanks for coming up with all these options. 
I think option 4 provides the best experience. 
Options 1 - 3 would require an additional visual cue/element to for users who try to navigate and select through their keyboard. 

Option 4 would align with AzNb's plans for mutliselect that follows the fluent ui and the two blue lines clarify current location to user among the selected and would not require an additional visual cue/element. Option 4 would work great for smart select requirements

**Comment by claudiaregio** [comment]
@misolori Additional question, where are the actions a user can take with the selected cells surfaced?

**Comment by misolori** [comment]
@claudiaregio they'd still appear on hover and whatever actions are taken there would apply for the selected cells. We'd only want to show actions that can be performed in bulk.

**Comment by claudiaregio** [comment]
> they'd still appear on hover and whatever actions are taken there would apply for the selected cells. We'd only want to show actions that can be performed in bulk.

@misolori would the cell toolbar still appear on hover for any non-selected cells? Or would that interaction be blocked unless a user escapes from the multiselected state?

**Comment by misolori** [comment]
@claudiaregio my initial thought was to only show actions for the items that are selected (so it wouldn't show up non-selected cells), but maybe we need to validate that with customer feedback and expectations.

**Comment by rchiodo** [comment]
+1 on Option 4. Makes it clear what's selected and what's the current cell (in case I want to hit shift+enter)

**Comment by misolori** [comment]
We now support multi-select in notebooks! This follows the pattern from our list widget, which you can also see in the explorer/any tree list, which supports shift + click and cmd/ctrl + click:

![Kapture 2021-03-22 at 11 03 15](https://user-images.githubusercontent.com/35271042/112036941-6ffb5280-8afe-11eb-9853-ebf54e6fb6b5.gif)


We also added a new color token (`notebook.inactiveSelectedCellBorder`) that has no default but is available for those that prefer to use borders for multi-select instead of background colors:

![Kapture 2021-03-22 at 10 49 13](https://user-images.githubusercontent.com/35271042/112035128-7c7eab80-8afc-11eb-8fef-841113fc006f.gif)
