### ISSUE TITLE
When working with VueJS components: EMMET => Tab is giving error.

### ISSUE THREAD

**Issue by OtabekSadiridinov** [microsoft/vscode#114145]
- VSCode Version: Latest
- OS Version: Windows 10 Latest

Steps to Reproduce:

1. Open a VueJS file
2. Press tab key in any section to use Emmet
3. Emmet will not work.

Note: This is not happening permanently. This is just happening sometimes. But, I am having to refresh VSCode.
Below see the video. I hide my code content. Just left the line itself to show.

https://user-images.githubusercontent.com/60849894/104180082-8ca84980-542e-11eb-87e8-ca74cfc16392.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by OtabekSadiridinov** [comment]
Yes, it looks like the same with the issue. But, in that issue the user reopened VSCode or restart his PC. Then, error is gone.
He himself fixed it. But, this cannot be a solution. Try to fix that issue. It even maybe happening on many of the users' PC.
Thank you.

**Comment by OtabekSadiridinov** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [emmet not working (#113638)](https://www.github.com/microsoft/vscode/issues/113638)

Yes, it looks like the same with the issue. But, in that issue the user reopened VSCode or restart his PC. Then, error is gone.
He himself fixed it. But, this cannot be a solution. Try to fix that issue. It even maybe happening on many of the users' PC.
Thank you.

**Comment by rzhao271** [comment]
Hi, can you try mapping tab to the command editor.emmet.action.expandAbbreviation instead?
