### ISSUE TITLE
Problema ao atualizar o Debian após instalar o vscode (Problem updating Debian after installing vscode)

### ISSUE THREAD

**Issue by danilomarto** [microsoft/vscode#114137]
Gostaria de relatar um inconveniente eu que tive: Quando eu abaixei o vscode pelo site oficial e o instalei na minha máquina (Debian 64bit) e logo em seguida eu rodei o ``` apt update ```. Recebi esse erro

```
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'arm64'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'armhf'
```

Eu resolvi esse problema editando o arquivo ``` /etc/apt/sources.list.d/vscode.list ```  que estava assim ``` deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/vscode stable main ```. Estou relatando isso por que foi um incoveniente não pode atualizar a minha máquina antes de corrigir esse arquivo.

(Eu o corrigi escrevendo-o assim ``` deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main ```)

## GOOGLE TRADUTOR

I would like to report an inconvenience that I had: When I downloaded vscode from the official website and installed it on my machine (Debian 64bit) and right after that I ran the ``` apt update ```. I got this error

```
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'arm64'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://packages.microsoft.com/repos/vscode stable InRelease' doesn't support architecture 'armhf'
```

I solved this problem by editing the file ``` /etc/apt/sources.list.d/vscode.list ``` which looked like this ```deb [arch = amd64, arm64, armhf] http://packages.microsoft .com / repos / vscode stable main ```. I am reporting this because it was an inconvenience not being able to update my machine before fixing this file.

(I corrected it by writing it like this  ```deb [arch = amd64] http://packages.microsoft.com/repos/vscode stable main```)

**Comment by robsonpctech** [comment]
> deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

Muito Obrigado, resolveu muito bem aqui. Parabéns.

**Comment by connor4312** [comment]
@joaomoreno are there any verification steps for this?

**Comment by joaomoreno** [comment]
Let's merge it into https://github.com/microsoft/vscode/issues/112223 since this issue becomes deprecated with the migration.
