### ISSUE TITLE
Bug on some cached memory loop

### ISSUE THREAD

**Issue by Osolemio44** [microsoft/vscode#114126]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 19042.685
- -Node version: 14.15.4 LTS

Issue:
Since a few days, I have problems with VSCode. Autoimport works badly and imports wrong code that you have not requested. But I have solved that more or less disabling the "autoimport" in the settings.
The second bug that makes it impossible for me to use VSCode is that it gets into a kind of loop in which it doesn't matter if you modify your code since it gets stuck at one point and when you run your application, it executes the code in which it is has been blocked.
I have reinstalled VSCode 3 times. I have even deleted the hidden folders of the plugins and where it saves the configuration. But nothing has worked.
I hope someone can tell me what the problem is because I would not like to have to format my computer if it turns out to be a VSCode problem later. Like I said, it has been happening to me for a few days, maybe a week. I am not aware of having done anything special to make that happen.

Steps to Reproduce:

No concrete step to reproduce. It just happens within a couple of minutes of using VSCode. It doesn't matter if you create a new project with other libraries.

https://user-images.githubusercontent.com/55595063/104154127-6a89d980-53e4-11eb-85f2-0bae68b2dcfb.mp4

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/104167936-2d4f3700-5438-11eb-8409-694dabfc14d5.png)

Node says the error is at line 1.

![image](https://user-images.githubusercontent.com/1330321/104167963-3b04bc80-5438-11eb-87de-3ff3ccdf8922.png)

But you only showed us lines 3-6?

**Comment by Osolemio44** [comment]
there is nothing on the line one 
![image](https://user-images.githubusercontent.com/55595063/104170700-d890c980-5401-11eb-8ba4-b05f54e7ad66.png)

**Comment by mjbvz** [comment]
Does this happen if you run the file outside of VS Code, such as launching node from command prompt?

**Comment by Osolemio44** [comment]
i tried using Atom, and seems to not have this issue.

**Comment by mjbvz** [comment]
Did you try from a normal command prompt?

Also, did you test with all extensions disabled in VS Code?

**Comment by Osolemio44** [comment]
Sorry, no. didnt try in a commando prompt. 
I did reinstall and try without any plugin, but still had the same issue. Now i am using another editor and it works fine. I have no time to do more tests. Hope you can find that bug. cant help more, sorry.
