### ISSUE TITLE
CPU will rise sharply when scrolling.

### ISSUE THREAD

**Issue by HuberTRoy** [microsoft/vscode#114136]
Issue Type: <b>Bug</b>

1. Open a file. 
2. Scroll.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.35GB free)|
|Process Argv|--crash-reporter-id 2caac36f-06c5-40f5-8418-cfd35b9966c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
wxml-vscode|cny|0.1.2
vscode-wxml|cod|0.1.9
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
jupyter|ms-|2020.12.414227025
vetur|oct|0.31.3
material-icon-theme|PKi|4.5.0
vscode-snippets|the|0.1.3
vscode-icons|vsc|11.1.0
ReactSnippets|xab|2.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt875:30241730
vsjup459cf:30237188

```

</details>

**Comment by rebornix** [comment]
@HuberTRoy can you please follow the steps https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to provide more details?

**Comment by HuberTRoy** [comment]
@rebornix 
Yes, the snapshot: https://github.com/HuberTRoy/myown/blob/master/saver/CPU-20210116T185227.cpuprofile
