### ISSUE TITLE
option to open new or existing editor

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode#114161]
I basically need a `TextEditor` object for a given url.
If that file is already open I want that editor to be reused.
This works well if the editor is in the active view column but not otherwise, always creating a new editor.

There are the `ViewColumn.Active` and `Beside` options for `showTextDocument` but they don't cover this case.
The other options in `TextDocumentShowOptions` don't seem to be useful either.

(Preview editors are disabled.)

**Comment by bpasero** [comment]
//cc @jrieken

**Comment by johnsoncodehk** [comment]
I have a same request, but I accidentally found a way:
```ts
async function showExistingTextDocument(document: vscode.TextDocument) {
  const editor = vscode.window.visibleTextEditors.find(editor => editor.document.uri.toString() === document.uri.toString());
  await vscode.window.showTextDocument(document, editor?.viewColumn);
}
```

**Comment by boltex** [comment]
@johnsoncodehk  Would that not just cycle through the visible ones (say you have 3 columns of opened documents -each with a bunch of opened tabs, only one in each column is the 'visible' one) in each column only - therefore not poping up if already opened but in a tab not in focus in a particular column?

**Comment by boltex** [comment]
@johnsoncodehk easy to test with console.log('visibleTextEditors.length' , vscode.window.visibleTextEditors.length); while having 2 columns of 3 documents each seeing a total of 6 tabs, does it print 6 or 2 ?

**Comment by boltex** [comment]
@Trass3r I also have this requirement - did you ever found a solution for this?
