### ISSUE TITLE
Allow TextEdit to have silent flag so it won't trigger onDidChangeTextDocument

### ISSUE THREAD

**Issue by drew-wallace** [Microsoft/vscode#11418]
- VSCode Version: 1.4.0
- OS Version: 10.11.6

```javascript
editor.edit(function (textEditorEdit) {
	return textEditorEdit.insert(position, "new silently inserted text");
}, true); // <-- silent == true
```

This would make my life easier for my remote pair programming app: [vscode-motepair](https://github.com/drew-wallace/vscode-motepair)

**Comment by jrieken** [comment]
This is something we won't do because it will break *true* listeners, think of linters et al. What we can think about is to allow you to set a `source` object that we pass along and you can do the filtering on your side.

**Comment by jrieken** [comment]
merge this with #10801
