### ISSUE TITLE
Ctrl+Shift+F should ignore .js files for TS project root

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/vscode#114175]
1. Detect if there is a `tsconfig.json` in the current directory
2. If so, exclude `*.js` from the `Ctrl+Shift+F` search by default
3. (Optional) Exclude only `${compilerOptions.outDir}/**/*.js` and `${compilerOptions.outFile}`

The reasoning being that we don't want to search compiled output, just source code.

**Comment by IllusionMH** [comment]
It's already possible to achieve that without depending on project type:

![image](https://user-images.githubusercontent.com/1312662/100602866-226b9780-330d-11eb-807b-d83f811a9c33.png)
1. Files in `.gitignore` are excluded if toggle enabled as shown above (`outDir` should be there)
1. Files in `files.exclude` setting if toggle enabled as shown above
1. Add this folder to "files to exclude" field

**Comment by roblourens** [comment]
It's common to use both. We need to rely on your project setup or gitignore here like @IllusionMH points out.

**Comment by ctjlewis** [comment]
Yeah, this would have been a feature request to do this without configuration, as there is literally never a time anyone would want to Ctrl+Shift+F compiled output in `outDir` for TS projects, but you can go ahead and close summarily close it anyway, seems about Microsoft.

**Comment by roblourens** [comment]
Issues can be reopened. My perspective is, listing your transpiled files in your gitignore is typically the best practice, and then they will automatically not be searched. Reading the tsconfig to automatically not search in outDir/outFile is actually an interesting idea. But I don't really want to pursue that. Getting this to work across different languages/toolchains is too hard. And I would say that of all the ts projects I've worked on, most have had some more complex build configuration with gulp, webpack, multiple tsconfig subprojects, etc, where we wouldn't be able to easily determine the out folder, so I don't want to try to mix language smarts into search. But I think it's fairly easy to configure your project to hide a new folder.
