### ISSUE TITLE
Old workspace reopens on opening file

### ISSUE THREAD

**Issue by Erik1984** [microsoft/vscode#114154]
- VSCode Version: 1.52.1
- OS Version: Windows 10 (versie 20H2)

Steps to Reproduce:

1.  Open a folder (let's say folder A) with vscode (right mouse in windows explorer ->"Open with code")
2.  Add another folder (let's say folder B) to the workspace (File->Add folder to workspace)
3.  Close vscode
4.  Open a different folder (let's say folder C) with vscode (right mouse in windows explorer ->"Open with code")
5.  VS code will now open twice. Once with folder C and an instance with folder A+B.
6.  When i first close folder C and then folder A+B i can repeat the same behavior from step 4
7. When i first close A+B i will get a message to choose whether or not i want to save the temporary workspace: "Do you want to save your workspace configuration as a file?". Pressing "Don't save" will solve the problem untill de next time i start with step 1.

I would expect to get the question from step 7 every time i close vscode, but this does not happen. I have the following settings:

"window.restoreWindows": "none",
"workbench.editor.restoreViewState": false,
"workbench.startupEditor": "newUntitledFile",
"files.hotExit": "off",

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
This is expected for "Untitled Workspaces": https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file

**Comment by Erik1984** [comment]
> This is expected for "Untitled Workspaces": https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file

I agree with the decription from the link, but this is not the behavior i get. When i close VS code i would expect to get the save question every time, but i only get the question when there is still an other instance of VS code open. If it's the last instance it will not trigger the save question and this results in 2 instances of VS code the next time i try to open an folder.
