### ISSUE TITLE
My Dom for JavaScript is not working

### ISSUE THREAD

**Issue by Aks-cyber** [microsoft/vscode#114106]
Issue Type: <b>Feature Request</b>

document.getElementaryid("") is not working properly.
Please tell the issue

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by yume-chan** [comment]
I never heard of `document.getElementaryid`, only `document.getElementById`
