### ISSUE TITLE
Expose actions to duplicate editor groups

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114132]
We have support to copy/duplicate editor groups including all of the editors, but we never exposed this as commands/actions. 

![image](https://user-images.githubusercontent.com/900690/104162555-1e936080-53f5-11eb-87af-03acb9a49e95.png)

**Comment by bpasero** [comment]
**Verification:** try to use the 4 duplicate group actions and verify that text editors duplicate in the new group.

**Comment by isidorn** [comment]
Works great!
One suggestion: only show the Duplicate Group Left and Duplicate Group Up if there is more than 1 group currently open. Otherwise these actions are same as the others and might just create confusion...
