### ISSUE TITLE
Reloading Extension Host window doesn't restart debug session

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1141]
- create TypeScript extension
- F5
- reload EH window (Cmd-R)
Observe: VSCode debugger doesn't attach to EH

BTW, an "Open file" in the EH works fine.

**Comment by weinand** [comment]
@isidorn please verify that you receive an event from Ben and send an attach request to the debug adapter

**Comment by isidorn** [comment]
Root cause seems to be the timing issue. In this case I first get a reattach request and only then a terminate for the running session. Since the debug service always tries to attach to a running session if there is one, in this case it will attach to the one that is about to be terminated

**Comment by weinand** [comment]
@isidorn thanks for the analysis. Yes, there was a change on my side that most likely delayed the terminate event: for windows I had to make the 'killtree' synchronous, so that the debug adapter would not terminate before 'killtree' had done its job.

Since this is a 'good fix', I don't want to revert it. I think we should try to make your code less dependent on the order of events: a terminated event may arrive later than the event to attach to a new EH.

Instead of just checking whether there is a session around to attach to, you should only attach to a session that has not been attached before (e.g. a "launched" session). If the session already had an "attach", a "reattach" should not attach to it but create a new session instead. 
So a simple flag "hadAttach" could solve this problem.
