### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by erlisakulla** [microsoft/vscode#114120]
I am having some usability issues. My cursor constantly turns into the block style and makes everything harder for me to edit. 

When I press Ctrl+A, instead of selecting everything, it pastes what I have on my clipboard many times.

Also cursor navigation is very confusing and I can't go from the line below to the one above from the edge.

**Comment by yume-chan** [comment]
Please file your issue using [template](https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md), or from Code run <kbd>F1</kbd> > `Help: Report Issue...`

**Comment by rebornix** [comment]
@erlisakulla can you please run VS Code with all extensions disabled `code  --disable-extensions` to see if you can still reproduce the issue?
