### ISSUE TITLE
recover untitled unsaved files

### ISSUE THREAD

**Issue by classicalboy** [microsoft/vscode#114184]
Issue Type: <b>Feature Request</b>

Hi team,

I love visual studio code , its simple and awesome as well. 
there were some untitled files in my visual studio code, whenver i opened the ide, i had access to those files/kind of notes always. but today morning , i accidently closed those files without giving them a name and so lost the data.
can you please suggest if there is a way I can recover that file

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by yume-chan** [comment]
Unsaved files should be at `%AppData%\Code\Backups\<one of the folders>`, but can't guarantee it will be the latest version or exist at all.
