### ISSUE TITLE
Allow sorting or filtering search results

### ISSUE THREAD

**Issue by Crossfire83** [microsoft/vscode#114109]
It'd be cool for VSCode to sort/filter search results by file name, file extension and so on

**Comment by roblourens** [comment]
Filter - this is basically what the "files to include/exclude" boxes are for, but maybe you only want to filter after the fact, not trigger a new search?

And sort - so you would want files of the same extension grouped together, regardless of the rest of the path?

**Comment by Crossfire83** [comment]
Sorting by file extension or by file name, something similar like windows file explorer on details view mode would be great
