### ISSUE TITLE
source control 输入中文卡死

### ISSUE THREAD

**Issue by qhdhiman** [microsoft/vscode#114128]
经常出现source control 提交操作时，输入中文提交信息卡死
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1725040/104158228-de010a80-5427-11eb-8b55-32fb5d436cde.png">

**Comment by binyellow** [comment]
在空白处右键先取消显示源代码管理，然后再勾选，可暂时重启解决卡死问题

**Comment by yume-chan** [comment]
Duplicate of #112621

**Comment by 2007lf** [comment]
> 在空白处右键先取消显示源代码管理，然后再勾选，可暂时重启解决卡死问题

不行，只能重启。
