### ISSUE TITLE
Source control editor lost responsibility。

### ISSUE THREAD

**Issue by gzx-miller** [microsoft/vscode#114135]
1. Input some commit comments in source control.
2. Select sub-string of the comments, then input new string to replace the selected-string, will cause the commit editor lost responsibility。

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, and whether it happens after you disable all extensions.

Tip: use the Report Issue option from the Help menu to feed this info into a new Git issue automatically.

**Comment by gzx-miller** [comment]
Report this issue from vscode, and the new issue is here[https://github.com/microsoft/vscode/issues/114250].
