### ISSUE TITLE
Bad look

### ISSUE THREAD

**Issue by amadersoto** [microsoft/vscode#114152]
Issue Type: <b>Feature Request</b>

the architect of the vs code is looking bad. just make menu, sidebar, status bar  and etc thinner like mac.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by misolori** [comment]
@amadersoto can you please elaborate on this?
