### ISSUE TITLE
Inconsistent Folding (JS/TS)

### ISSUE THREAD

**Issue by lukeed** [microsoft/vscode#114108]
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (2 mos ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Copy JavaScript snippet below
2. Run `Fold All` command
3. Observe that second block collapses differently.
4. Unfold, and Change L7 from `});` to `}` (syntax error). Folding this will now be correct.

Does this issue occur when all extensions are disabled?: Yes

---

I would hope/expect to see the end-blocks for all folded code. The current format makes it very difficult to navigate, refactor, and/or highlight the collapsed portion as a single-line summary. This problem/obstacle doesn't happen with the other folded blocks because I can see the end/bottom of what I'm doing.

```js
if (true) {
  console.log('pass')
}

hello('name', () => {
  console.log('fail');
});

function hello(str, fn) {
  console.log('pass');
}
```

***Folded Result***

<img width="391" alt="Screen Shot 2021-01-10 at 10 58 49 AM" src="https://user-images.githubusercontent.com/5855893/104132586-330f2480-5333-11eb-8b9d-b05a2a78f958.png">

**Comment by lukeed** [comment]
Impressive bot results :) but none of these are quite the same actually. I checked before posting too.

**Comment by mjbvz** [comment]
Works fine in the latest VS Code insiders build:

<img width="664" alt="Screen Shot 2021-01-11 at 11 04 21 AM" src="https://user-images.githubusercontent.com/12821956/104226512-c52f2f80-53fc-11eb-9d78-83a38c0bc76b.png">
