### ISSUE TITLE
Move cursor by paragraphs

### ISSUE THREAD

**Issue by obsgolem** [microsoft/vscode#114166]
[This extension](https://marketplace.visualstudio.com/items?itemName=jmfirth.vsc-space-block-jumper) is one of my most used VSCode extensions. Sadly it does not appear to function correctly in the presence of code folding. The issue appears to be much the same as the one presented in #81498. I suggest moving this functionality into VSCode proper, perhaps by a new option in the `to` field of `cursorMove`.

**Comment by obsgolem** [comment]
Just an extra data point in support of this, it appears that the extension I mentioned doesn't work in notebook view.

**Comment by obsgolem** [comment]
I think I might be able to do this. I reviewed the relevant code and here are the list of things I think would need to be done:
* Add functions to get the next/previous empty line to IViewModel https://github.com/microsoft/vscode/blob/044741569781be2f5842ae01bb5ceba4b26f1cc3/src/vs/editor/common/viewModel/viewModel.ts
* Implement functions in viewModelImpl https://github.com/microsoft/vscode/blob/3564f180616c43054e2f7c3cdbcc75934dcc7d37/src/vs/editor/common/viewModel/viewModelImpl.ts
* Add a pair of functions to perform the relevant cursor motions to https://github.com/microsoft/vscode/blob/7ecce71a487455c782eef943fb22af450ba07267/src/vs/editor/common/controller/cursorMoveCommands.ts. `CursorState.fromViewState` is the function to call to create a cursor at a given view position.
* Add a new `by` property here: https://github.com/microsoft/vscode/blob/7ecce71a487455c782eef943fb22af450ba07267/src/vs/editor/common/controller/cursorMoveCommands.ts#L640
* Update the parse function: https://github.com/microsoft/vscode/blob/7ecce71a487455c782eef943fb22af450ba07267/src/vs/editor/common/controller/cursorMoveCommands.ts#L698
* Add the commands to the keymapping, default unbound
* Write unit tests as needed. Not sure what your requirements for this are.

**Comment by alexdima** [comment]
The first two bullet points are not necessary:
> Add functions to get the next/previous empty line to IViewModel https://github.com/microsoft/vscode/blob/044741569781be2f5842ae01bb5ceba4b26f1cc3/src/vs/editor/common/viewModel/viewModel.ts
> Implement functions in viewModelImpl https://github.com/microsoft/vscode/blob/3564f180616c43054e2f7c3cdbcc75934dcc7d37/src/vs/editor/common/viewModel/viewModelImpl.ts

You can simply use `getLineContent()` and `getLineCount()` to find empty lines from the command implementation.

The other bullet points make sense to me. No need to add a keybinding, some simple unit tests should be fine, like having 2 empty lines, having empty lines at the end of the file, etc.

**Comment by alexdima** [comment]
To verify, you can use the following keybindings:

```
{
    "key": "ctrl+down",
    "command": "cursorMove",
    "when": "editorTextFocus", 
    "args": {
        "to": "nextBlankLine",
        "by": "wrappedLine"
    }
},
{
    "key": "ctrl+up",
    "command": "cursorMove",
    "when": "editorTextFocus", 
    "args": {
        "to": "prevBlankLine",
        "by": "wrappedLine"
    }
}
```
