### ISSUE TITLE
Tabs are inconsistent

### ISSUE THREAD

**Issue by OriginLive** [microsoft/vscode#114133]
Issue Type: <b>Bug</b>

Why is control + tab and shift + control + tab acting so retarded?

Literally browsers do it right, control + tab goes on next tab
and shift + control + tab goes on previous one.

Why is that so hard to do??

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.06GB free)|
|Process Argv|--crash-reporter-id 34480e2c-728b-451a-bb8f-5a317f931da8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
vscode-coding-tracker|han|0.6.0
remote-wsl|ms-|0.52.0
typescript-imports-sort|nso|1.12.1
tabnine-vscode|Tab|3.1.25
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.10
gitblame|wad|6.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt700:30237718
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by rasberrylasagna** [comment]
+1
