### ISSUE TITLE
Auto import js module not working

### ISSUE THREAD

**Issue by athenasumit** [microsoft/vscode#114198]
Issue Type: <b>Bug</b>

In my node project, when I press ctrl+space it list import suggestion but on selecting it the text is filled but not filling auto import code.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
apex-pmd|chu|0.5.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
debugger-for-chrome|msj|4.12.11
vscode-xml|red|0.14.0
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|50.8.0
salesforcedx-vscode-apex|sal|50.8.0
salesforcedx-vscode-apex-debugger|sal|50.8.0
salesforcedx-vscode-apex-replay-debugger|sal|50.8.0
salesforcedx-vscode-core|sal|50.8.0
salesforcedx-vscode-lightning|sal|50.8.0
salesforcedx-vscode-visualforce|sal|50.8.0

</details>

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue

/needsMoreInfo
