### ISSUE TITLE
Make errors descriptions more visually clear

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11415]
You've all heard about syntax coloring it is something to make it easier for kinder-gardeners to do programming.

See it is quite hard to distinguish logical/context parts of the message and identify the problems from such output:
![image](https://cloud.githubusercontent.com/assets/736697/18182803/eabcf0e6-70aa-11e6-88e6-7febacf0d419.png)

It would be good if error descriptions contained some highlighting of important parts like particular error messages (underlined on the picture), and maybe included code/signature highlighting as well.

**Comment by waderyan** [comment]
@whitecolor thank you for opening this issue. Can you show me more about the context of your feature request? Is this in the output window? 

If you could share something simple I could recreate what you are seeing that would be appreciated.

**Comment by whitecolor** [comment]
@waderyan Yes this is a popup that appears when I the mouse is over the errored code (undelined with red).
![image](https://cloud.githubusercontent.com/assets/736697/18306716/83d66596-7506-11e6-92d7-9bea6fa7e1f9.png)

There is even some code highlighting in the popup =) But it is obviously is not enough.

**Comment by waderyan** [comment]
@dbaeumer do you have an opinion on this? 

I agree with OP that it would be good to do some highlighting in the popover view. Who would be best to send this to on the team? Is this strictly a UX issue?

**Comment by dbaeumer** [comment]
Agree that the error message needs to be better understandable. Being able to colorize that however need some support from the tsserver. We can't simple take the error message and run a tokenizer over it. Will very likely produce a suboptimal coloring. 

So in a first step we need to ask the tsserver to produce 'strucutured' error message and then we can try to improve the coloring and rendering on it. In the above example I could even imagine some sort of folding.

**Comment by waderyan** [comment]
@dbaeumer thank you. Sending to TS. 

Note there is a closely related issue here - https://github.com/Microsoft/vscode/issues/13070#event-808268456

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11334
