### ISSUE TITLE
Keep activity bar icons stable on reload (Web)

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#114144]
In Desktop (not connected to remote), all icons in the activity bar are shown at the same time but in Web (Codespaces) icons from extensions are shown a bit later thereby having non ideal user experience. 

Use the same caching strategy that is done in Desktop and avoid flickering in Web

**Comment by sandy081** [comment]
Cached icon paths in web - acb0a35629d1006f5517bb9c78d56aa68202479b

**Comment by sandy081** [comment]
I confirm that above attached fix caches the icons in browser and prevent flickering in activity bar. But this needs fix in Codespaces which is available in PPE. Hence reverted the caching change until codespaces fix is pushed to production. 

Also needs another fix for Remote Explorer icon because currently this is shown only after remote views are contributed. Created a PR to show remote explorer always in remote window - https://github.com/microsoft/vscode/pull/114257

**Comment by sandy081** [comment]
To verify:

- Open a codespace
- make sure you have some extensions those contribute view containers installed. Eg: GitHub Pull Requests & Issues extension, Docker etc.,
- Reload window and make sure activity bar icons are shown immediately

**Comment by isidorn** [comment]
Works great!

**Comment by aeschli** [comment]
Testing with Codespaces (dev), 1.53.0-insider Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, Date: 2021-01-26T05:20:01.859Z, I still see the view icons to appear with delay after the reload.
![viewicons](https://user-images.githubusercontent.com/6461412/105867119-0165b100-5ff5-11eb-9c0d-230cb3a531ea.gif)

@sandy081 Is that expected?

**Comment by isidorn** [comment]
I am using the ppe environemnt on codespaces and for me this works fine.

**Comment by sandy081** [comment]
Thanks for verifying @aeschli and @isidorn .

Some container icons coming after is expected because their views visibility is based on when context which is not cached either in desktop or in web. So you shall see the same behaviour in desktop with those view containers.
