### ISSUE TITLE
MAC Intellisence "Tab" keypress not selecting highlighted item (inserts regular Tab instead)

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#11414]
- VSCode Version: **1.4.0**
- OS Version: **MAC 10.10.3**

Steps to Reproduce:

1. Type in something that brings up intellisence, for example `doc` (which will bring up an intellisence dropdown with `document` being at the top and selected)

2. Press the `TAB` Key. Instead of selecting document, it will just create a tab in your document. Now you have `doc(tab-spaces-here)`(several spaces after doc)

On windows the Tab key selects the item you have highlighted in intellisense.

Just wanted to point it out, loving VSCode otherwise 👍 👍

**Comment by joaomoreno** [comment]
@MarkPieszak Do you have any extensions installed? Does it reproduce when disabling all extensions (`code --disable-extensions`)? Do you override some keybindings?

**Comment by MarkPieszak** [comment]
You're completely right, I pinpointed it down to `Angular 2 Typescript Emit` plugin, which templates out things like `ul>li` and when you push Tab it creates multiple of them for you automatically. Removed this, and it works like a charm. Apologies for the issue! False alarm ;)

**Comment by joaomoreno** [comment]
Thanks for letting us know!
