### ISSUE TITLE
˝ character is typed before first typed character after app start on non US keyboard

### ISSUE THREAD

**Issue by 1hub** [Microsoft/vscode#11417]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. change keyboard to nonUS, for example CSQ (Czech QWERTY)
2. run VS Code
3. type something, for example "a"
=> ˝a is typed

**Comment by alexandrudima** [comment]
@1hub I could not reproduce on both 1.4.0 and on 1.5.0 on the insiders channel.

Here is the keyboard layout I installed:
* I added the Czech language:

  ![image](https://cloud.githubusercontent.com/assets/5047891/18201731/08612a70-710c-11e6-97df-5471b1f0bb3f.png)

* I then proceeded and added the Czech QWERTY keyboard layout:

  ![image](https://cloud.githubusercontent.com/assets/5047891/18201779/5508bc62-710c-11e6-900d-4f7fd5bb21a4.png)

* I then changed from the taskbar to the CES CSQ:

  ![image](https://cloud.githubusercontent.com/assets/5047891/18201805/77aafcbc-710c-11e6-80e9-b84e92c7f65e.png)

* I then tried typing a,b,c etc:
![asdf](https://cloud.githubusercontent.com/assets/5047891/18201846/c8ecee5a-710c-11e6-87fe-5328de24aee7.gif)

**Comment by 1hub** [comment]
To be clear: you have to have closed VS Code when changing keyboard (ie set CES CSQ keyboard before you run Code)
1. close VS Code
2. change keyboard to CES CSQ (if you have had another one)
3. run Code and type something. Char ˝ will show before first typed char
Char ˝ is "copied" to keyboard buffer after you run Code, so this steps works too:
1. close Code, run notepad
2. set CES CSQ keyboard
3. run Code
4. alt-tab to notepad, type something => ˝something will be typed

No problem with US keyboard. This bug is very old, not related to v1.4, I experienced this behaviour long time ago (Win7/Code 0.x, now Win10/Code 1.4)

**Comment by alexandrudima** [comment]
Oh wow, I could reproduce. This only happens for me the first time I type `a`. I think this is a Chromium or Electron issue because I can reproduce in the native `input` elements of the search viewlet. I am thinking this must be happening for you in Chrome too?

**Comment by 1hub** [comment]
Yes, ˝ is typed only before first typed character, not before each.
Chrome: No. I'm using several editors based on similar technologies like Atom, several browsers (Chrome as default), CES CSQ is my only keyboard and I never saw this behaviour except in VS Code.

**Comment by alexandrudima** [comment]
Wow, this is caused by `native-keymap` -- see Microsoft/node-native-keymap#5 . Great catch @the-ress

**Comment by the-ress** [comment]
@1hub If you don't want to wait a month for the release, you can build [node-native-keymap](https://github.com/Microsoft/node-native-keymap/tree/0e43c25dedf2f95db09fbf10af039f3c639b5c25) yourself and replace `C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\native-keymap\build\Release\keymapping.node`.

**Comment by 1hub** [comment]
@the-ress Thank you very much for removing this annoying bug ;) The easiest way for me was to download the Insiders version of VS Code and copy the keymapping.node file to current instalation.
