### ISSUE TITLE
`code-insiders --status` results in error

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#114181]
Issue Type: <b>Bug</b>

When connected to a remote machine via Remote-SSH, running `code-insiders --status` on a remote machine or locally results in the regular output plus the following error line:

`Fetching remote diagnostics for 'SSH: az-devbox' failed: Canceled`

VS Code version: Code - Insiders 1.53.0-insider (3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e, 2021-01-11T05:14:18.990Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.4.0-1031-azure
Fetching remote diagnostics for 'SSH: az-devbox' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (8.71GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: az-devbox' failed: Canceled
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.3.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
theme-monokai-pro-vscode|mon|1.1.18
remote-containers|ms-|0.154.2
remote-ssh-edit-nightly|ms-|2021.1.8133
remote-ssh-nightly|ms-|2021.1.8132
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
vscode-github-issue-notebooks|ms-|0.0.58
vsonline|ms-|1.0.3076
material-icon-theme|PKi|4.5.0
vscode-ruby|win|0.28.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-pull-request-github-insiders|Git|2021.1.14942
rainbow-csv|mec|1.8.0
vscode-js-profile-flame|ms-|0.0.13
vscode-markdown-notebook|ms-|0.0.13
vscode-typescript-tslint-plugin|ms-|1.3.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt875:30241730
core-portspanel:30233467

```

</details>

**Comment by kieferrm** [comment]
I just realized that one of the remote windows that I had open was disconnected. So, I guess, the error message should be more clear.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/99608

**Comment by Tyriar** [comment]
@Yash621 sure, search the codebase for `Fetching remote diagnostics`, we basically want to handle this case where the remote connection isn't available more gracefully and say something more along the lines of "Connection to 'SSH: az-devbox' could not be established". You can run the server via `./resources/server/bin/server.js`

**Comment by p4nu** [comment]
Should this be closed?

**Comment by Tyriar** [comment]
@p4nu yes, thanks
