### ISSUE TITLE
Error in Authrization Of ORG

### ISSUE THREAD

**Issue by VidishSharma1** [microsoft/vscode#114150]
Issue Type: <b>Bug</b>

17:06:02.644 sfdx force:auth:web:login --setalias S Org --instanceurl https://test.salesforce.com --setdefaultusername
17:06:02.646 sfdx force:auth:web:login --setalias S Org --instanceurl https://test.salesforce.com --setdefaultusername
 ended with error spawn C:\WINDOWS\system32\cmd.exe ENOENT

Starting SFDX: Authorize an Org

17:24:55.199 sfdx force:auth:web:login --setalias Some --instanceurl https://login.salesforce.com --setdefaultusername
17:24:55.200 sfdx force:auth:web:login --setalias Some --instanceurl https://login.salesforce.com --setdefaultusername
 ended with error spawn C:\WINDOWS\system32\cmd.exe ENOENT

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1596)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.09GB free)|
|Process Argv|--crash-reporter-id 7a2864e3-1207-49af-aae6-f5f81e4bee4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
salesforce-soql-editor|all|0.10.2
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.8.0
vscode-xml|red|0.14.0
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|50.8.0
salesforcedx-vscode-apex|sal|50.8.0
salesforcedx-vscode-apex-debugger|sal|50.8.0
salesforcedx-vscode-apex-replay-debugger|sal|50.8.0
salesforcedx-vscode-core|sal|50.8.0
salesforcedx-vscode-lightning|sal|50.8.0
salesforcedx-vscode-lwc|sal|50.8.0
salesforcedx-vscode-visualforce|sal|50.8.0
vscode-taskkill|Shy|0.0.65
lightning-component-snippets|Ter|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30236574
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by bpasero** [comment]
This sounds VSCode unrelated.

**Comment by VidishSharma1** [comment]
what is the fix for this issue. I already reinstall the VSCode but still, I
am facing the same problem.

PFA.

Regards,
Vidish

**Comment by bpasero** [comment]
How do you trigger this exactly?

**Comment by VidishSharma1** [comment]
I just created a new SFDX Project With Manifest and then tried to authorize an org by clicking no default org Set button in the below section and after that, I selected the SFDX: Authorize an Org and then I Selected Sandbox (test.salesforce.com) . in the last I gave an alias (Name) to my org and hit enter.  

Before 5 min of this error occurs, I also authorized another org successfully but I don't know what happened to my VSCode after that.

**Comment by bpasero** [comment]
Sorry, but what exactly is a "SFDX Project", this does not sound like something VSCode provides built in?

**Comment by VidishSharma1** [comment]
It has resolved now. there was some issue with the project now I created
the new one and it's working fine.
