### ISSUE TITLE
behavior of require.resolve inconsistent in dev vs prod mode

### ISSUE THREAD

**Issue by kyliau** [microsoft/vscode#114172]
- VSCode Version: 1.52.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

In the extension runtime, the following code has different behavior compared to Node.js:
```javascript
const options = {
  paths: [
    "/some/path"
  ]
};
require.resolve('something', options);
```
The `options` parameter is not processed by the extension runtime.

This is confirmed by looking at the source code in this repo:
https://github.com/microsoft/vscode/blob/03450bf09414f1883dd9b8cfea02df3fac8df0f4/src/vs/loader.js#L744-L746

According to Node.js [documentation](https://nodejs.org/docs/latest-v12.x/api/modules.html#modules_require_resolve_request_options):

> * options &lt;Object&gt;
> > * paths &lt;string[]&gt;
Paths to resolve module location from. If present, these paths are used instead of the default resolution paths, with the exception of GLOBAL_FOLDERS like $HOME/.node_modules, which are always included. Each of these paths is used as a starting point for the module resolution algorithm, meaning that the node_modules hierarchy is checked from this location.    

If passing an option is not supported by `require.resolve`, it should be documented and an error should be thrown at runtime.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@kyliau That is the AMD require, which an extension should not receive. Could you please provide a minimal example where you can reproduce stepping into `loader.js` from a VS Code extension?

**Comment by kyliau** [comment]
@alexdima sorry for the lack of information in the initial report, I discovered this some time ago and I just realized I left out a few crucial details.

Here's a full description of the problem.
1. When the extension runs in the development mode (presumably in debug mode), `require.resolve` works fine. To verify this, I added a line `require.resolve('something')`, and put a breakpoint on it. From the screenshot below, we can see that the `options` parameter is accepted, and `require.resolve()` works as expected.

<img width="1136" alt="Screen Shot 2021-01-15 at 10 51 10 AM" src="https://user-images.githubusercontent.com/2941178/104767486-14d56a00-5721-11eb-83b7-94df1be1816b.png">

2. The real issue is that the behavior of `require.resolve` is different in **production** mode. 
To reproduce this, I cloned the [`i18n-sample`](https://github.com/microsoft/vscode-extension-samples/tree/master/i18n-sample) project from the [`vscode-extension-samples`](https://github.com/microsoft/vscode-extension-samples) repo. I picked this project because it's the only example that provides a command to package a `vsix` file using `vsce`.

Now, I don't know how to debug the extension in production mode, so I resorted to a very crude logging method. I added the following line
```js
vscode.window.showInformationMessage(require.resolve.toString())
```
to `extension.ts`, ran `npm run gulp package`, then installed the extension from the `vsix` file.
Here's the output when I run the extension:

<img width="1067" alt="Screen Shot 2021-01-15 at 10 57 22 AM" src="https://user-images.githubusercontent.com/2941178/104768116-fae85700-5721-11eb-9976-1b98d316c1b4.png">

From the screenshot, we can infer two things:

1. The execution code path is different in development vs "production" mode.
2. `require.resolve` in "production" mode does not accept a second parameter, the `options` object.

I then did a quick `grep` for the keyword `_resolveFilename` in this repository, and the following snippet is the only result I found.

https://github.com/microsoft/vscode/blob/03450bf09414f1883dd9b8cfea02df3fac8df0f4/src/vs/loader.js#L744-L746

Please let me know if you need more info, thank you very much!

**Comment by alexdima** [comment]
Thank you for the extra information. I wasn't aware that we patch the `require` passed in to commonjs modules, but I see now why we do this, in order to generate cache data recursively. cc @jrieken

**Comment by jrieken** [comment]
verified in source
