### ISSUE TITLE
Display Hint for settings set as default

### ISSUE THREAD

**Issue by YPetremann** [microsoft/vscode#114104]
As for now the json setting ui tells us about Unknown Configuration Setting with a Hint,
I would like a similar Hint to tell that our setting and the default are the same with a message like "Set as Default".

It would be interesting when cleaning our setting file or to indicate that this setting is enforced, or when a last month feature have his settings set by default.

**Comment by YPetremann** [comment]
Doesn't correspond to the suggested issue

**Comment by roblourens** [comment]
I can see how this could be useful, but it's often useful to purposely configure settings to their default values, like to override the setting in another scope, and I don't think I would want to add the noise from this hint to my settings file.
