### ISSUE TITLE
Visual Studio Code doesn't save terminal history on exit

### ISSUE THREAD

**Issue by hostedvideorn** [microsoft/vscode#114164]
Visual Studio Code Version: 1.52.1
Windows 10
Git bash installed under C:\Program Files\Git 
C:\Users\my_windows_user\.bash_history

I have the following extensions installed
- HashiCorp Terraform v2.4.0
- Terraform (forked) v1.4.51 - had to get this one installed for Terraform code references to work
- Shell launcher v0.4.1
- Terminal v0.0.10

C:\Users\my_windows_user\AppData\Roaming\Code\User\settings.json
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"

When working on the integrated bash terminal its history is never saved.
The only way I can get it saved is to type "exit" on the terminal and then close VSC.

**Comment by meganrogge** [comment]
this is expected/as designed behavior. If you want the terminals to reconnect, you can use a remote connection like WSL

**Comment by hostedvideorn** [comment]
Hello. I am afraid this is not what I said. I am trying to say that before VSC would save the bash terminal history but it doesn't do it anymore. Not sure how this is "as designed" as it never was.

**Comment by hostedvideorn** [comment]
@meganrogge - please see comments

**Comment by meganrogge** [comment]
please attach a [gif](https://gifcap.dev/) of this happening.
