### ISSUE TITLE
HyperLinks in HTML

### ISSUE THREAD

**Issue by TheShreyank** [microsoft/vscode#114196]
So, this I had been in my concern that I am not been able to use hyperlinks in HTML. I had tried the same code in other software. The hyperlink code for a website is working on other software but not on VSCode. I would like to know the reason why it has been doing this.

Thank You.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide code example and more description about what doesn't work.

**Comment by TheShreyank** [comment]
Yes, I will send it to you. Here it is;
The code has to be copy-pasted in your VSCode.

This is the Code:
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image and Links</title>
</head>
<body>
    <a href="https://google.com" target="_blank"> Go to google</a><br>
    <a href="https://facebook.com" target="_blank"> Go to facebook</a><br>
    <a href="https://linkedin.com" target="_blank"> Go to linkedin</a><br>
    <a href="https://twitter.com" target="_blank"> Go to twitter</a><br>
    <a href="/Meta Tags.html" target="_blank"> Meta Tags</a><br>
    <a href="/Heads and Paras.html" target="_blank">Paras</a><br>

    <img src="https://source.unsplash.com/user/erondu/500x400" alt=
"Error loading Image"
</body>
</html>
There is also a screenshot of the code.

**Comment by aeschli** [comment]
Here's what I see:
![image](https://user-images.githubusercontent.com/6461412/104898775-53b22c80-597a-11eb-9f5c-c134aa87850c.png)

Can you explain what hyperlink is not working?

**Comment by TheShreyank** [comment]
What do you mean? The HTML code isn't working. When I type,for example: <a
href="https://google.com" target="_blank"> Go to google</a><be>
When I press on go live it doesn't show the hyperlink "Google".

**Comment by IllusionMH** [comment]
/causedByExtension

If I create new html file and paste from example in your last comment - VS Code correctly highlights code and allows all other actions, if you save it to HTML file and open with browser directly - everything works as expected.

Make sure you don't have cached version of page in browser or report issue to extension you are using for Go Live functionality (I guess that it is Live Server)

**Comment by TheShreyank** [comment]
OK! Will be checking on it and will inform you if everything is ok

**Comment by TheShreyank** [comment]
Thank You for informing me about the problem. I opened it again found it
working.
Sorry, I caused an issue with extensions.
Thank You for your response.

Happy Coding!
