### ISSUE TITLE
Bug in Refactoring 

### ISSUE THREAD

**Issue by Amansh993** [microsoft/vscode#114143]
- VSCode Version: 1.52.1(user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. reinstalling done
2. restart the laptop

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/needsMoreInfo

It's not clear what code or even language causing problem. Please provide minimal code sample where it can be reproduced.
