### ISSUE TITLE
JSON Schema intellisense markdown/jsdoc not parsing links anymore

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#11413]
- VSCode Version:
Version 1.4.0 (1.4.0)
- OS Version:
Mac OSX 10.11.5

## Before (not sure what version, a few months ago)
![screenshot 2016-09-01 15 12 44](https://cloud.githubusercontent.com/assets/317498/18181057/78a2795c-7057-11e6-9680-86dbbc662b75.png)

✅  Clickthrough possible

## Now
![screenshot 2016-09-01 15 12 24](https://cloud.githubusercontent.com/assets/317498/18181075/87382e94-7057-11e6-9575-500671e62d7e.png)

❌  Clickthrough **not** possible

## Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=sequoia.loopback-json-schemas
2. Create a file called `common/models/test.json`
3. add opening curly brace `{`
4. Mouse over

* **Expected**: link is rendered & you can click through to the browser
* **Actual**: link **not** rendered, click through not possible.

## Additional note
This is a jsdoc `@see` link, but the issue also affects `[markdown style links](https://github.com/Microsoft/vscode/issues/11413)`

**Comment by aeschli** [comment]
Has to with the fix to render JSON hovers as text not markdown.
Text in schemas are simple text, not markdown. Before we rendered them as markdown, which resulted in bugs that certain text was lost, such as *. We now render it as text, and there's no longer automatic link detection.

**Comment by aeschli** [comment]
@jrieken We need to discuss what is the way to go here. We basically need API to create a MarkedString for regular (non-markdown) text. Ideally it would do link detection.

**Comment by jrieken** [comment]
It looks like we want to escape markdown text not using code blocks but another trick

**Comment by jrieken** [comment]
http://daringfireball.net/projects/markdown/syntax#backslash

**Comment by Sequoia** [comment]
@jrieken I'm not sure if you were suggesting the markdown `<http://short.link.style>` but that doesn't seem to work either.
![screenshot 2016-09-02 12 29 41](https://cloud.githubusercontent.com/assets/317498/18210939/097f82c4-7109-11e6-85e1-d95e40c23d89.png)

**Comment by jrieken** [comment]
Yeah, that's because the JSON extension 'ghetto escapes' all markdown by putting it into code block

**Comment by Sequoia** [comment]
Feature request? 🙀  I thought this was a regression (it used to work). 😅 

Either way thanks for looking into this. My thoughts:

## Reasons to revert to previous behavior (parse & render markdown and optionally jsdoc comments)
* Makes the feature *much* more powerful: the intellisense with example code, links, bulleted lists etc. are just *really* useful. I've been using it as a selling point for switching to VSCode 👈  mostly this reason
* It used to work this way so at least one person (this guy) has been relying on the feature, possibly others
* jsonschemas, while not a new technology, are not used extremely widely-- it's not millions that would be affected by a change here but possibly thousands (if that). I mean to say "conventions don't exist here yet & there's no reason the convention can't be 'include markdown in descriptions if you want'."
* The metaschema doesn't seem to say anything about the contents of description, merely that it is a string. So nothing forbidding HTML or markdown:
```
        "description": {
            "type": "string"
        },
```

On a personal note:
* I've been developing a [plugin](https://marketplace.visualstudio.com/items?itemName=sequoia.loopback-json-schemas) + [fairly extensive json schemas](https://github.com/Sequoia/loopback-json-schemas) that rely on this feature. 😿  [My demo](https://www.youtube.com/watch?v=IqixTiB6Xyc&feature=youtu.be&t=100) doesn't really work anymore.

## Reasons to keep current behavior
* Not all schemas will be markdown friendly, some may break
* Creating new behavior may cause split between "regular" schemas and "vscode schemas" (deviation from standard, tho the spec/metaschema says nothing about the contents of description).

## Notes

I of course want to see the behavior restored. I am curious to see the schema which markdown rendering broke & learn how many users that affected. If it is a small handful, I'd argue that more stand to benefit from the enhanced behavior than be inconvenienced by it. If the fix is as simple as "wrap example in backticks," again, this doesn't strike me as a terribly onerous burden and [already occurs in the wild](http://json.schemastore.org/jshintrc).

Optionally, I'd be happy to mark or flag my schemas in some way to say "this schema's descriptions should be rendered in markdown." The spec [does allow](http://json-schema.org/latest/json-schema-core.html#anchor20) for additional, "custom" properties to be added to a schema.

Bring back rendering!! Save my extension!! 😸

**Comment by Sequoia** [comment]
> Text in schemas are simple text, not markdown.

@aeschli is this per jsonschema spec or VS Code project conventions or...? The standard/metaschema merely say it's text, and markdown strings are text . . . as I read it there's nothing forbidding markdown there.

**Comment by aeschli** [comment]
@Sequoia Descriptions in JSON schemas are regular, unformatted text, and I need to treat it so, otherwise lots of descriptions in schemas are wrongly rendered: Characters ignored, wrong formats, etc. JSON schemas are widely used, with lot's of schemas. http://schemastore.org/json/

You should stick to unformatted text in your schema and will try to add automatic link detection on top of it. The old behaviour was cause of a bug and therefore not a supported feature.
If you need a solution right now, our extension API lets your create your own hovers, with markdown :-) You can use our light weight JSON parser [jsonc-parser](https://www.npmjs.com/package/jsonc-parser) to figure out where you are in the JSON.

**Comment by Sequoia** [comment]
Thanks for the follow-up @aeschli 

## Proposal
**Allow feature to be reënabled via flag in json schema user-settings mapping**. See ["Mapping in the user settings"](https://code.visualstudio.com/Docs/languages/json#_json-schemas-settings):

```json
"json.schemas": [
    {
        "fileMatch": [
            "/.babelrc"
        ],
        "url": "http://json.schemastore.org/babelrc",
        "markdown": true, //or
        "render": true, //or
        "render": ["markdown", "jsdoc"]
    },
```

This would allow user mapped schemas, or plugins (such as mine) to *opt in* to this this powerful, existing feature, without breaking anyone else's json schemas. Do you see any issues with this?

**Comment by aeschli** [comment]
Now creating the MarkedString by escaping markdown characters instead of using the 'string' code block brings back the link detection.

**Comment by Sequoia** [comment]
@aeschli I'm confused-- where does this leave my issue? Does this fix the markdown regression? I'll try to run VSCode from source to test this out, on my stable version the regression is still there.

**Comment by Sequoia** [comment]
I checked on `master` (641121489ac45fb6588abc6ff6209e4943e9ff2e) and the problem persists, and there is a new problem (for which I'll file a separate ticket).

Note that the regression is still in place wrt. markdown parsing (the fenced code block is not parsed):

![screenshot 2016-09-21 15 42 39](https://cloud.githubusercontent.com/assets/317498/18726443/7231b8ba-8012-11e6-84b1-f0340f6371ba.png)

**Comment by Sequoia** [comment]
Bump. Any news on this regression? Should I open a new ticket?

**Comment by egamma** [comment]
@Sequoia need @aeschli's insights on this. He is currently out.

**Comment by Sequoia** [comment]
paging @aeschli. What's my path forward?

What I'm hoping for is a path forward for me, the user who relied on the feature that got removed. Ideally (for me) the feature would be reinstated or put behind a flag so I can add a "parse these schema descriptions as markdown"/"do legacy behavior" setting somewhere in my plugin to recreate legacy behavior.

Another "path forward" that would not leave me feeling like the rug was pulled out from under me would be a scaffolded plugin for what @aeschli suggested above:

> If you need a solution right now, our extension API lets your create your own hovers, with markdown :-)

My plugin was *very* very simple & leveraged built-in behavior; there was no typescript at all in fact. I am not eager to have to go back & learn how to *manually reimplement* this behavior in a plugin, but if a VSCode Whiz were willing to roll a plugin scaffolding and say "put your schema links here & it should behave like before" that would be an adequate resolution for me.

Thanks again & again let me emphasize that **I like VS Code**, that's why I'm recommending it to people & building plugins on it etc. (here's my [latest of several](http://sequoia.makes.software/interactive-debugging-with-nodejs/) blog posts evangelizing VS Code: this one is not yet published, I've linked a live "preview"). I want nothing more than to come away from this hiccup with a good experience & feeling like VS Code is a solid platform to build on & recommend! This would be difficult, however, if I had to recommend VS Code with the caveat "proceed with caution on this platform, if you build on it the features you're building on may evaporate." That's not a very good user story! ☹️

**Comment by aeschli** [comment]
@Sequoia oh, sorry, for not replying earlier. We are flooded with mail, request and work. My fix in September brought back the old behaviour where links in schema descriptions where detected again, which should fix your original bug. 
As to other markdown tags, it was a bug that that schema descriptions were rendered as markdown. Bringing this back would bring back the bugs we saw with all other correctly specified schemas that are out there and happen to use a '*', '-' etc in their description. 
Adding a flag or some custom schema extension would just complicate everything, and unless we get more requests in that direction I don't want to go there.

We do everything to keep documented APIs and behaviour stable. What you were relying on was unintended unspecified behavior.

I appreciate your support of VSCode and hope you stick with us even I currently can't help you with an easy workaround. Give the TypeScript implementation a chance.  This is how your extension code would look like
```typescript
'use strict';

import * as vscode from 'vscode';
import { getLocation } from 'jsonc-parser';

export function activate(context) {

	context.subscriptions.push(vscode.languages.registerHoverProvider({ pattern: '**/yourfile.json' }, {

		provideHover(document, position, token) {
			const location = getLocation(document.getText(), document.offsetAt(position)); // returns the location in the JSON
			if (location.path[0] === 'dependencies' && location.path[1] === 'mypackage') { // looks for a property 'mypackage' inside property 'dependencies'
				return new vscode.Hover('My *Markdown* content', document.getWordRangeAtPosition(position));
			}
		}
	}));
}
```
Use our [vscode yeoman generator](https://code.visualstudio.com/docs/tools/yocode) to get started.
