### ISSUE TITLE
VScode opens empty file

### ISSUE THREAD

**Issue by markkkkas** [microsoft/vscode#114102]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. Terminal -> Go to yours code directory -> code . OR Launch Visual Studio Code -> Open folder
<img width="662" alt="Screenshot 2021-01-10 at 11 31 01" src="https://user-images.githubusercontent.com/48568793/104119343-520fb580-5337-11eb-8726-7caf38871a01.png">
<img width="676" alt="Screenshot 2021-01-10 at 11 31 11" src="https://user-images.githubusercontent.com/48568793/104119347-589e2d00-5337-11eb-9e39-1d802b78e99d.png">
![Screenshot 2021-01-10 at 11 31 18](https://user-images.githubusercontent.com/48568793/104119349-5cca4a80-5337-11eb-8238-0ee001f59400.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by hackrx** [comment]
Hey @markkkkas how you solved this issue, I am also facing this issue.
[Issue](https://github.com/microsoft/vscode/issues/97048#issue-613042208) does not solve this issue.

**Comment by markkkkas** [comment]
Hi @hackrx. Unfortunately its very rare case when i hit this bug, for my helped pc restart

**Comment by hackrx** [comment]
In My case opening the folder directly from vs code Explore is also not working. :(,
