### ISSUE TITLE
VS Code doesn't show workspace after latest update

### ISSUE THREAD

**Issue by rodrigomf24** [Microsoft/vscode#11412]
- VSCode Version:1.4
- OS Version:Windows 10 Pro 64 bit

Steps to Reproduce:

1. Open VS Code
2. Nothing shows on the workspace, I can open a folder but it won't load anything

* I had to install an older version 0.9.2 and it works fine, this happened after the latest update.

**Comment by bpasero** [comment]
@rodrigomf24 can you share a screenshot how it looks? are you able to open the developer console from the help menu?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
