### ISSUE TITLE
Hover scrolling messed up (popover disappears when scrolled to bottom)

### ISSUE THREAD

**Issue by tnrich** [microsoft/vscode#114160]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (3 wks ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:

1. Hover a function with a long enough info hover helper to need scrolling
2. Scroll that hover popover to the bottom (or top) and the popover disappears

Does this issue occur when all extensions are disabled?: Yes

https://user-images.githubusercontent.com/2730609/104217586-6cf23080-53f0-11eb-8d6f-69a90e0e99fd.mov

**Comment by gjsjohnmurray** [comment]
Possible duplicate of #112373

**Comment by tnrich** [comment]
Whoops I searched but didn't find the issue mentioned! Closing this one. Thanks !
