### ISSUE TITLE
File renaming with just case change in Explorer tab

### ISSUE THREAD

**Issue by abheist** [microsoft/vscode#114139]
- VSCode Version: 1.52.1
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Make a new file `layout.tsx`
2. Add into git and commit it
3. Rename the from VSCode explorer from `layout.tsx` to `Layout.tsx`
4. Then check for git status, there will be no change visible

To fix this issue I've to rename the file using command `git mv layout.tsx Layout.tsx`

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by yume-chan** [comment]
MacOS is case insensitive by default, and git follows platform default.

You can change this behavior with `git config core.ignorecase false` (this repository only) or `git config --global core.ignorecase false` (globally).

**Comment by isidorn** [comment]
Thanks, thus closing as designed. 
There are some other open issues for case sensitivity on macOS, so you can also check those out for further details
