### ISSUE TITLE
Notebook doesn't snap view to the executed cell.

### ISSUE THREAD

**Issue by FGhavamian** [microsoft/vscode#114100]
Issue Type: <b>Bug</b>

- open a notebook
- execute a cell which generates a long output (exceeding view height)
- right click on the l.h.s. of the cell and click "clear cell outputs"

Expectation: 
the view should snap to the cell that just got executed.

What happens:
the view stays where it was and hence, all cells are shifted to out of the view. 

VS Code version: Code - Insiders 1.53.0-insider (ed6c343edb720d91ee0859e566c84b5687f5a9d5, 2021-01-08T10:46:04.327Z)
OS version: Windows_NT x64 10.0.21286
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (13.08GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/fghavamian/projects/accelerate_computer_simulations --remote=wsl+Ubuntu-20.04 --crash-reporter-id e7f4e6f1-32af-4fc6-b89f-a530bcad4f73|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.64GB (0.16GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.0
remote-wsl|ms-|0.52.0
material-theme|zhu|3.9.12
latex-workshop|Jam|8.15.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by rebornix** [comment]
Same as collapsing cell outputs
