### ISSUE TITLE
Bug: misleading message when selecting deleted images in the Git pane

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#11426]
- VSCode Version: 1.4
- OS Version: macOS El Capitan

Steps to Reproduce:
1. Open any project/folder bounded to Git and containing an image
2. Delete an image (tested with .png)
3. Open the Git pane and select the entry for the deleted image

Observed:
The following message is shown: **ERROR**: Unable to open 'xxx.png (HEAD)': File seems to be binary and cannot be opened as text. The image is not shown.

Expected:
The image shall be shown without an error message, as it happens with [deleted] text files.

**Comment by joaomoreno** [comment]
#3935
