### ISSUE TITLE
Emmet Abreviation

### ISSUE THREAD

**Issue by subashpatra28** [microsoft/vscode#114284]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Few days before all good but I dont know why or how my emmet abreviation was too slow.
Earlier I only have to type then instantly it get poped up but now it simply not working properly. So Please help to fix it

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5157U CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.80GB free)|
|Process Argv|--crash-reporter-id 92a7db1d-6dff-47ea-b2bc-0bfec7dd59b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
vscode-html-css|ecm|1.8.0
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.22.0
vscode-language-babel|mgm|0.0.30
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-react-native|msj|1.2.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.1.0
quokka-vscode|Wal|1.0.335
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
vstes516:30244333
pythonvspyt600cf:30241728

```

</details>

**Comment by rzhao271** [comment]
Hi, does this issue still occur for you on the latest [Insiders](https://code.visualstudio.com/insiders/)?
