### ISSUE TITLE
Extreme memory usage for "rzls" in large project

### ISSUE THREAD

**Issue by emmenlau** [microsoft/vscode#114224]
Issue Type: <b>Bug</b>

I have a project that references several GB of source files, spread out over hundreds of thousands of files. VSCode opens the project nicely and makes it possible to work with and search through the files.

However every once in a while it crashes my computer. I've seen that a process called "rzls" seems to hog immense amounts of RAM, in the range of 80-90% of all available RAM. Today it crashed by work computer with 64GM of RAM, of which typically only 10-20% are used with common applications like Crome or Thunderbird. No compile was running at the time of the crash.

See attached screenshot.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-60-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3910)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.10GB (0.25GB free)|
|Process Argv|BDAScripts.code-workspace --no-sandbox --crash-reporter-id cfee8681-3b9d-43e6-a2b1-3c1799828d72|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.1.3
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.22.0
vscode-test-explorer|hbe|2.19.4
latex-workshop|Jam|8.15.0
autoconf|mae|0.1.0
vscode-catch2-test-adapter|mat|3.6.19
vscode-docker|ms-|1.9.0
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
cpptools|ms-|1.1.3
bash-debug|rog|0.3.9
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
shellcheck|tim|0.12.3
cmake|twx|0.0.17
markdown-all-in-one|yzh|3.4.0

</details>

![Screenshot from 2021-01-12 21-15-26](https://user-images.githubusercontent.com/1098087/104368640-a2943800-551c-11eb-897b-15801fad7ca7.png)

**Comment by IllusionMH** [comment]
Most likely you need to report this issue in C# extension repo https://github.com/OmniSharp/omnisharp-vscode
VS Code doesn't support this kind of projects out of the box.
