### ISSUE TITLE
Consider renaming/updating descriptions of menubar visibility for web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114200]
I would expect that setting menu visibility to `default` puts the menu into the activity bar when running in web.

**Comment by sbatten** [comment]
default describes the behavior of visibility more so than the location. default will be hidden on full screen but visible in the titlebar when not. this is the only way to get this behavior.

all settings have a "reset setting" option which will put it to the true "default" which in web is compact. (this is marked in web in the settings editor as well)

**Comment by bpasero** [comment]
Up to you, I just felt that `default` should be the actual settings default on all platforms and browsers. I felt it weird that we pick `compact` in `web` when there is also `default`.

**Comment by sbatten** [comment]
also this one https://github.com/microsoft/vscode/commit/99f71a032ea932670744d14d6364903a00b99ae3

**Comment by sbatten** [comment]
I have updated the settings names/descriptions/visibility and behavior for all platforms. macOS does not use alt key to focus the menu bar so we now talk about the `Focus Application Menu` command for macOS web.

**Comment by sbatten** [comment]
This will require a test plan imo.
