### ISSUE TITLE
Warn about invalid file associations

### ISSUE THREAD

**Issue by MrSpecific** [microsoft/vscode#114223]
Issue Type: <b>Bug</b>

No steps to reproduce - this bug happens even with all extensions disabled, and VS Code & OSX completely up-to-date. 
When working in CSS / PostCSS files (.css) Intellisense will do basic suggestions, but nothing context-specific. I've tried with no extensions, and with PostCSS language support and other extensions - always the same behavior. On non M1 Macs, context-specific suggestions ARE shown. As far as I can tell, the only thing that is different about my setup is that I'm using an M1 Mac vs an Intel Mac.

Screenshots for reference.
On my computer, missing context-specific suggestions:
![image](https://user-images.githubusercontent.com/1530703/104364210-26253900-54cb-11eb-8ee6-b6845c957234.png)

On a co-worker's computer, accurate suggestions:
![image](https://user-images.githubusercontent.com/1530703/104364253-36d5af00-54cb-11eb-8dbc-0ad562f1d197.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 5|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|. --crash-reporter-id 06defd16-5b05-4ef5-9a59-cb083277e1cb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-toggle-quotes|Bri|0.3.3
bracket-pair-colorizer-2|Coe|0.2.0
postcss|css|1.0.9
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.8.0
duplicate|gee|1.0.1
vscode-liquid-snippets|kil|2.0.1
nunjucks|ron|0.3.0
shopify-liquid|sis|2.3.0
selectline-statusbar|tom|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt859:30241729

```

</details>

**Comment by aeschli** [comment]
Can you verify that the editor mode is 'CSS'? You should see `CSS` somewhere on the right side in the status bar.

Also check if there's something in the log (Output view, Log tab).
You can put the setting `"css.trace.server": "messages"` to get more output from the CSS language server. When set, check out `Output > CSS Language Server`

**Comment by MrSpecific** [comment]
@aeschli - Running with no extensions, `.css` files are opened as "Plain Text", so VS Code is not (by default) recognizing those file types - and as you would expect, Intellisense does not show CSS suggestions for those files. 
I've been able to get working Intellisense by trying out a different PostCSS extension. Out of the three PostCSS extensions I've found, this is the only one that provides the correct Intellisense suggestions for CSS files: https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language

**Comment by aeschli** [comment]
Maybe the CSS Language Features extension is disabled. Open the extensions view and enter `@builtin css language features` in the search field to see the extension and it's enablement state.

Other possibility is that the file association for css files has been changed. Open the settings and look for `files.associations`. If there's an entry for `*.css`, remove it.

**Comment by MrSpecific** [comment]
@aeschli - I checked, and CSS Language Features is (and was) enabled. After disabling extensions again, I did still find an association for .css files (for PostCSS) and removed it, and that does seem to do the trick, so thank you for that suggestion!
I think the thing that could use improvement is that with that association in-place, but without a PostCSS language extensions active, VSCode just silently defaults to "plain text" rather than alerting that the association isn't valid, or defaulting back to CSS.

**Comment by aeschli** [comment]
@MrSpecific Thanks for figuring out. 
What would make it easier if there was a error reproting for invalid language associations. E.g. in the status bar, next to the language or in the settings file.
#34450 is similar.

**Comment by alexdima** [comment]
@MrSpecific So you had user settings mapping `*.css` to something else? Can you please share how you had it configured?

**Comment by MrSpecific** [comment]
@alexdima - I went through a number of configurations trying to figure out the issue, but I know for certain that there was an issue when I had all extensions disabled, and for `file.associations` I had this association in place: 
![image](https://user-images.githubusercontent.com/1530703/104945123-172c0400-596d-11eb-9bfd-5587dc73812f.png)
