### ISSUE TITLE
Log service fails to flush errors to disk that happen on startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114254]
We use the `logService` on startup to log critical startup errors and it looks like the `spdlog` is only enabled after startup so that errors that occur during startup are not flushed to disk.

**Steps:**
* throw an error [here](https://github.com/microsoft/vscode/blob/878bf135043770f5e2270378b2376bc5e3f8deac/src/vs/code/electron-main/main.ts#L222-L222)
* start with an empty user data dir
* observe the `logs` folder after starting

It is empty. I wonder if this line should be moved up?

https://github.com/microsoft/vscode/blob/878bf135043770f5e2270378b2376bc5e3f8deac/src/vs/code/electron-main/main.ts#L135-L135

**Comment by joaomoreno** [comment]
@bpasero Spdlog was created at startup when it was first introduced: https://github.com/microsoft/vscode/blob/9b3478b66df97e8dc1ef9b6bc4cd409bcdb36dda/src/vs/code/electron-main/main.ts#L55

Then: https://github.com/microsoft/vscode/issues/72906

**Comment by sandy081** [comment]
Logs are buffered until the spdlog logger is created and we compromised to loose crash logs that can happen during this time for the performance - https://github.com/microsoft/vscode/issues/72906#issuecomment-495536535
