### ISSUE TITLE
Feature request: Ctrl+Shift+F should ignore .js files for TS project root

### ISSUE THREAD

**Issue by ctjlewis** [microsoft/vscode#114249]
### Feature Request

1. Detect if there is a `tsconfig.json` in the current directory
3. Exclude `${compilerOptions.outDir}/**/*.js` and `${compilerOptions.outFile}` from Ctrl+Shift+F search by default

This prevents users from unintentionally searching generated TS output as a default action for project roots we know for sure are TypeScript projects. **This means a user must manually configure their search excludes if they want to avoid repeatedly scrolling past compiled JS results**.

---

Re-submitted from #114175 and clearly designated a feature request. 

If it is Microsoft policy to close feature requests based on a random team member's first impression, I would very much appreciate resources on that policy. Until I have them, I will continue to re-submit this request so that it is open for comments.

**Comment by mjbvz** [comment]
The solution is to gitignore your build output. This will automatically excludes those files from search results and quick open

Assigning @roblourens and @JacksonKearl for the feature request of letting extensions/languges configure default ignored files

IMO letting extensions/project configs also change which files are/aren't ignored would add another layer of complexity and potential confusion to searching. For TS, adding the output files to gitignore is a better solution, except in some potential  advanced use cases

**Comment by gjsjohnmurray** [comment]
@ctjlewis please be aware that it is not usually necessary to open a duplicate issue in order to continue discussing an issue that has been closed.

**Comment by ctjlewis** [comment]
What I thought was VS Code picking up compiled output was actually just manually compiled output in a committed `third_party/` folder, so this actually *is* a pointless request - 100% on me, sorry about that.
