### ISSUE TITLE
Source control editor cursor lost control.

### ISSUE THREAD

**Issue by gzx-miller** [microsoft/vscode#114250]
Issue Type: <b>Bug</b>

1. Input some commit comments in source control.
2. Select sub-string of the comments, then input new string to replace the selected-string, will cause the commit editor lost responsibility。

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.70GB free)|
|Process Argv|--folder-uri file:///c%3A/CCode/WebNative/xfind_next --crash-reporter-id 2200551b-14cc-4abb-9a43-e043225e0e9a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.2
dart-code|Dar|3.17.1
flutter|Dar|3.17.0
gitlens|eam|11.0.6
vue-snippets|hol|1.0.4
svg|joc|1.4.3
react-native-snippet|jun|0.5.6
vscode-typescript-tslint-plugin|ms-|1.3.3
vetur|oct|0.31.3
vscode-css-peek|pra|4.0.2
react-node-desktop-debugger|rea|2.0.1
vue-vscode-snippets|sdr|2.1.5
gitblame|wad|6.0.2
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by eamodio** [comment]
I can't reproduce this -- Can you still reproduce this on the latest insiders build?
