### ISSUE TITLE
Incorrect signature for php date_format function suggestion.

### ISSUE THREAD

**Issue by ilmarsL** [microsoft/vscode#114218]
Issue Type: <b>Bug</b>

VS code shows incorrect parameter order in suggestion for completing php date_format() function in procedural style.
Suggestion shown in vs code: 
`date_format( string $format , DateTimeInterface $object )`
Signature in [php manual](https://www.php.net/manual/en/datetime.format.php):  
`date_format ( DateTimeInterface $object , string $format ) : string`

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-36-generic

**Comment by roblourens** [comment]
I will just patch this as a one-off, but we should dig up the script that generates these and take another look
