### ISSUE TITLE
Setting up commands to skip shell should use intellisense

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#114216]
I was setting up a new machine and realized that the recent menu shortcut (ctrl + r) didn't work in the terminal. So I tried setting it in the "commands to skip shell" but then realized that i didn't know the command name: 

![image](https://user-images.githubusercontent.com/35271042/104352124-1dc50200-54bb-11eb-8cb5-4bb9979ba164.png)

I'd imagine a lot of users wouldn't know the command name or how to get it. It would be nice if we could provide intellisense suggestions that allowed users to search for a command similar to the keyboard shortcut:

![image](https://user-images.githubusercontent.com/35271042/104352211-3e8d5780-54bb-11eb-99f7-24a78411fe68.png)

Unrelated to this, I think `workbench.action.openRecent` should be added to the default list for `terminal.integrated.commandsToSkipShell`

**Comment by xpe** [comment]
@misolori Hi, let me see if I can distill your question. Here is how I understand what you are asking...

You want to lookup a command name based on the keybinding.

If so, this has nothing intrinsically to do with the Terminal. Do you understand what I mean?

Are you aware of the existing functionality that lets you lookup a command name by pressing the keybinding? Here it is:
https://code.visualstudio.com/updates/v1_28#_record-and-search-keyboard-shortcuts

**Comment by misolori** [comment]
@xpe no, what I want is for intellisense to show up on the settings input for "commands to skip shell" to help find the command name. Right now I have to go to the keyboard shortcut ui and type my command and find the command id and then go back to the settings page and paste that in. I'd like to avoid the hassle of doing all of that but having intellisense inside the input box.
