### ISSUE TITLE
Save As Type dialog is not sorted alphabetically

### ISSUE THREAD

**Issue by popey456963** [microsoft/vscode#114264]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NTx64 10.0.19042

Steps to Reproduce:

1. Install some custom languages, examples that it definitely works for are "Caddlefile Syntax", "Graphviz language", "Hjson", "Better TOML", "Svelte for VS Code".
2. Create a new blank file.
2. File --> Save as and expect to find it in the alphabetically sorted list (e.g. Toml from Better TOML between Swift and TypeScript) , instead find it at the bottom.

It appears to be in the order 'inbuilt languages sorted alphabetically' followed by 'other languages sorted somewhat randomly'.

![image](https://user-images.githubusercontent.com/1338129/104441727-f853f900-558b-11eb-85be-8bea40e2c4d2.png)

Does this issue occur when all extensions are disabled?: No

**Comment by bpasero** [comment]
They are sorted on macOS, so it maybe Windows doing something weird. But we also dont sort the list explicitly:

https://github.com/microsoft/vscode/blob/aa18ca682765edd34edb0c231053577c5d5835d8/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L278-L293

**Comment by bpasero** [comment]
Up for grab, I think we should sort the languages by name. We still have to make sure that:
* "All Files" appears first
* the current language appears second and selected
* "No Extension" is last

**Comment by rydwhelchel** [comment]
If you sort registeredLanguageFilters that should solve the problem no? 
"All files" appearing first, current language appearing second and "No Extension" appearing last is handled by these lines:

https://github.com/microsoft/vscode/blob/aa18ca682765edd34edb0c231053577c5d5835d8/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L308-L313

Still getting the hang of all this, so please correct me if I am wrong.

**Comment by bpasero** [comment]
Can we have this discussion in a Pull Request?

**Comment by lramos15** [comment]
Two things I notice.
1. Save as with untitled files defaults to `.bat` not `All Files`.
2. Calling Save as on a file with a pre-existing extension leads to an out of order list. I.e. here's a picture of .CSS
![image](https://user-images.githubusercontent.com/4544166/106183052-b8853800-616d-11eb-81d5-ebffad4821b3.png)

**Comment by bpasero** [comment]
It is intentional that the language mode picked for a file is the second most entry in the list, we have explicit code to change the order there. 

As for untitled: did you have the language mode configured to ".bat"? I suggest we follow up in a new issue here as it is independent from the sorting fix.

**Verification:** 
* create an untitled file
* save it
* in the picker verify that the languages are sorted by name, specifically check for languages contributed by extensions such as JSONC
