### ISSUE TITLE
Pin folders so they dont collapse when you click on collapse-all

### ISSUE THREAD

**Issue by aruniverse** [microsoft/vscode#114295]
I'm working in a pretty big monorepo, jumping back and forth between multiple folders. I would like to be able to pin a folder, so that when you click on the collapse all button, the folder that I pinned doesn't collapse.

![image](https://user-images.githubusercontent.com/11051042/104489840-188cb380-559e-11eb-9d52-353699979499.png)

I saw someone made a similar request, #28929, where pinning a folder would pin it to the top and the suggestion was to use the multi-root/folder workspace feature. I don't love this solution as the folder I'd like to pin changes dynamically depending on what I'm working on and I don't want to constantly be updating my .code_workspace file or don't want to open the file browser when i click on "Add Folder to Workspace" and then have to manually navigate to that sub folder in the monorepo again. Also, with this approach, if i try to collapse all, the folder collapse too so doesn't really solve my problems besides pulling the folder I want to the root of that file tree explorer.

I don't really care for it, but maybe you can add an option for if the pinned folder moves to the top or not.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
