### ISSUE TITLE
Treeview hovers flicker and wrap strangely depending on location

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#114230]
Here you can see that the label and the description seem to trigger the hover separately, causing it to move which IMO isn't desirable. This also causes the hover to wrap, since it seems to be trying to align with the left edge of the description, which also isn't desirable.

Also you can see that the hover sometimes flickers strangely , like it quickly hides and shows, sometimes as well.

![tree-hovers](https://user-images.githubusercontent.com/641685/104380092-79fa4700-54f8-11eb-9280-a426ca1f1dcb.gif)

**Comment by Tyriar** [comment]
@alexr00 seems awfully similar to https://github.com/microsoft/vscode/issues/106431

**Comment by fadeevab** [comment]
Hey @alexr00! I have a question unrelated to this ticket but perhaps you could help me a lot: I see that Makefile syntax and tests have gone from `extensions`, I used them before to test my changes, and I have an open issue to fix some Makefile highlighting, so could you suggest me where to start now? :)) Were they removed? Seems like I have to change my approach. Thanks!

**Comment by alexr00** [comment]
@fadeevab the make extension has moved to https://github.com/microsoft/vscode-make. Tooling around tests in that extension is currently being worked on. Feel free to open new issues if you have make development related questions so that we don't sidetrack this issue.

**Comment by fadeevab** [comment]
@alexr00 Hey! Sorry for the off-topic again, but seems like that https://github.com/microsoft/vscode-make is a private repository, it is unaccessible

**Comment by alexr00** [comment]
We decided to move the make extension back into the microsoft/vscode repo, that's why microsoft/vscode-make is gone (it's been deleted :)).
