### ISSUE TITLE
Shouldn't c++ preprocessor #elif's textmate scope be keyword.control.directive.conditional.elif ?

### ISSUE THREAD

**Issue by REYNEP** [microsoft/vscode#114297]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:
1. create a .cpp file and write "#elif"

WHY?:-
1. all conditional Preprocessor Commands, #if, #else, #endif, #ifdef, #ifndef are inside **_keyword.control.directive.conditional_** (eg. **_keyword.control.directive.conditional.ifdef_**)
2. But #elif is inside _**keyword.control.directive,**_ (like this: _**keyword.control.directive.elif**_)
3. Shouldn't #elif's textmate scope be under keyword.control.directive.conditional too like the others?

> I have fixed this by modifying **_cpp.tmLanguage.json_**
> At Line 12683 if you add **_elif_** beside the other **_#if #ifdef #ifndef_** preprocessor commands, this gets fixed

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Thanks for the issue! I have moved this issue to the repo that our C++ grammar comes from: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/532
