### ISSUE TITLE
Webview: Autofocus processing was blocked because a document already has a focused element.

### ISSUE THREAD

**Issue by mheuzey** [microsoft/vscode#114221]
I recently noticed that the cursor is no longer being positioned to my autofocused elements. Opening the console, I see this message: "[Embedded Page] Autofocus processing was blocked because a document already has a focused element." Since I know that autofocus used to work, I went back through previous versions of VSCode. It seems to work up through July 2020 (version 1.48.2), but breaks in August 2020 (version 1.49.3). I tested with the latest Insiders build to make sure that this hasn't already been fixed.

What makes this issues extra strange is that it is (usually) not present when there is an image on the page. I don't know anything about HTML rendering, so this is a wild guess, but I'm thinking that whatever is holding focus and causes the message to appear, releases it by the time the image is retrieved and rendered? Most images will cause the issue to disappear, but some of them don't.

Version: 1.53.0-insider (user setup)
Commit: e17aea136d32fdb06d9b32184b04ccd36bb51e9c
Date: 2021-01-12T08:23:24.929Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Download the vscode extension samples: (https://github.com/microsoft/vscode-extension-samples.git)
2. Modify the html in the cat coding webview sample to have a `<textarea>` with `autofocus`
3. Remove the image tag (`<img src="${catGifPath}" width="300" />`)
4. Run the cat coding webview
5. Note that cursor is not placed in the textarea. Open console to see message

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The error I see with iframe based webviews:

```
Blocked autofocusing on a <textarea> element in a cross-origin subframe.
```

This is a Chrome limitation on iframes that you will need to workaround. Even if we could fix this for desktop VS Code, it would still not work when VS Code is run on the webview

Instead of using `autofocus`, try calling `.focus` on the element instead

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###

**Comment by deshyah** [comment]
###deshyah'sTimeLog###
