### ISSUE TITLE
Bug: An Image doesn't change in the editor whenever it is altered externally

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#11427]
- VSCode Version: 1.4
- OS Version: macOS El Capitan

Steps to Reproduce:
1. Open a project/folder containing an image
2. In the Folder view, select the image in order to show it in the editor window (tried with a PNG)
3. Replace the image file externally (tried with macOS Finder)
4. In the Folder view, select another file and select back the image

Observation:
The image doesn't change. It keeps showing the old image. It is needed to restart VSCode in order to see the updated image.

Expected:
The updated image shall be shown.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7951
