### ISSUE TITLE
Emmet expand abbreviation goes into visual mode with vim extension

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#114213]
Version: 1.53.0-insider (user setup)
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:14:06.672Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19042

1. Get the vim extension
2. Expand an Emmet abbreviation such as `div`, or wrap `<div></div>` with an abbreviation
3. The vim extension goes into visual mode, whereas it should stay on insert mode

Downstream: https://github.com/VSCodeVim/Vim/issues/5884

**Comment by gkssjovi** [comment]
I have the same problem. Any progress or suggestions on this bug?

**Comment by rzhao271** [comment]
1. The Emmet expansion/wrap algorithms currently rely on selecting text to work: https://github.com/VSCodeVim/Vim/issues/5884#issuecomment-758810279
2. The last comment here https://github.com/VSCodeVim/Vim/issues/5884#issuecomment-766413548 suggests it's an extension issue. 
Closing this issue for housekeeping.

**Comment by gkssjovi** [comment]
Thank you for the clarification.
