### ISSUE TITLE
Synchronization authorization failed

### ISSUE THREAD

**Issue by czfadmin** [microsoft/vscode#114276]
Issue Type: <b>Bug</b>

After the prompts in the following figure appear, click the Login button to log in. According to the operation results, authorization failure will be shown.

![image](https://user-images.githubusercontent.com/13393959/104457675-5103b000-55e5-11eb-8b25-7d44c2f8d166.png)

VS Code version: Code - Insiders 1.53.0-insider (e17aea136d32fdb06d9b32184b04ccd36bb51e9c, 2021-01-12T08:23:24.929Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.42GB (17.71GB free)|
|Process Argv|--crash-reporter-id 993f6513-7f85-4215-8eea-70e3cd2723d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (114)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
nestjs-files|Abh|0.4.0
codesnap|adp|1.2.0
Bookmarks|ale|12.1.2
project-manager|ale|12.0.1
ng-template|Ang|0.1100.2
nestjs|ash|1.4.2
vscode-django|bat|1.0.3
armview|ben|0.4.5
django|big|1.0.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
codestream|Cod|10.3.0
bracket-pair-colorizer-2|Coe|0.2.0
angular-schematics|cyr|4.8.0
flutter|Dar|3.18.1
vscode-eslint|dba|2.1.14
docs-markdown|doc|0.2.82
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.3
vscode-html-css|ecm|1.8.0
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vscode-todo-plus|fab|4.18.2
vscode-ionic-snippets|fiv|2.2.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
docker-explorer|for|0.1.7
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.4
vscode-lombok|Gab|1.0.1
codespaces|Git|0.5.1
vscode-codeql|Git|1.3.9
vscode-pull-request-github|Git|0.22.0
google-translate|han|1.1.6
vscode-jasmine-test-adapter|hbe|1.7.1
vscode-mocha-test-adapter|hbe|2.8.1
vscode-test-explorer|hbe|2.19.4
vscode-test-explorer-liveshare|hbe|1.0.5
vscode-drawio|hed|1.2.0
ionic-preview|ion|0.0.20
Ionide-Paket|Ion|2.0.0
vue|jcb|0.1.5
vscode-peacock|joh|3.9.1
julia-debug|Jud|0.0.32
language-julia|jul|1.0.10
vscode-python-test-adapter|lit|0.6.5
vsls-whiteboard|los|0.0.12
MagicPython|mag|1.1.0
git-graph|mhu|1.28.0
code-beautifier|mic|2.3.3
csharp|ms-|1.23.8
dotnet-interactive-vscode|ms-|1.0.206106
vscode-dotnet-runtime|ms-|1.0.0
vscode-postgresql|ms-|0.3.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.1.3
js-atom-grammar|ms-|0.1.14
mono-debug|ms-|0.16.2
powershell-preview|ms-|2020.9.0
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3449
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.11
debugger-for-edge|msj|1.0.15
vscode-react-native-preview|msj|2021.1.1120
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
resourcemonitor|mut|1.0.7
nativescript|Tel|0.11.0
vscode-python-typehint|njq|1.4.1
vetur|oct|0.31.3
vscode-jest|Ort|3.2.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-spring-boot|Piv|1.24.0
platformio-ide|pla|2.2.1
gotestexplorer|pre|0.1.13
nextjs-snippets|Pul|0.0.3
java|red|0.73.0
vscode-xml|red|0.14.0
LiveServer|rit|5.6.1
bash-debug|rog|0.3.9
rust|rus|0.7.8
vscode-nebular-snippets|sha|1.0.1
django-intellisense|sha|0.0.2
vscode-julia-formatter|sin|0.3.0
autoimport|ste|1.5.3
tabnine-vscode|Tab|3.1.26
bootstrap4-vscode|the|6.1.0
linenote|tkr|1.2.1
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.6.1
vscode-icons|vsc|11.1.0
markdown-pdf|yza|1.4.4
material-theme|zhu|3.9.12
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by XuCpeng** [comment]
same issue

Version: 1.53.0-insider (user setup)
OS: Windows_NT x64 10.0.21286
