### ISSUE TITLE
MacBook Air M1 Crashed and Rebooted

### ISSUE THREAD

**Issue by a777med** [microsoft/vscode#114226]
Issue Type: <b>Bug</b>

VS Code Insiders edition 1.53 took longer than expected to open then a blue screen appeared for a second then a black screen and a reboot on base model MacBook Air M1. The report after reboot showed "Kernel stack memory corruption detected". The laptop was in normal condition with only a handful of apps open. I could not reproduce the problem.

VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:32:43.927Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 997d206a-8862-4fdf-b804-4970d1fda71a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanelcf:30233468

```

</details>

**Comment by allamid06** [comment]
Hey, same happened to me right now... I oppened up vs code, after unziping the installer... do you know anything about? do you thing it could be hardware problem? or something else from the macbook air?

**Comment by aftabhussain02** [comment]
any update on this? i faced the same issue.

**Comment by a777med** [comment]
Hi,
 
It happened to me again. Opening VS Code Insiders edition 1.53 crashes the whole system sometimes. I included the complete crash report below.

<details>
<summary>
Crash report / stack trace
</summary>

> panic(cpu 5 caller 0xfffffe001b1ebc4c): "Kernel stack memory corruption detected"
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 20C69
Kernel version: Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
Fileset Kernelcache UUID: 3E6AA74DF723BCB886499A5AAB34FA34
Kernel UUID: 48F71DB3-6C91-3E62-9576-3A1DCEF2B536
iBoot version: iBoot-6723.61.3
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x00000000135cc000
KernelCache base:  0xfffffe001a5d0000
Kernel slide:      0x000000001410c000
Kernel text base:  0xfffffe001b110000
Kernel text exec base:  0xfffffe001b1d8000
mach_absolute_time: 0x134689e4b21
Epoch Time:        sec       usec
  Boot    : 0x600731b5 0x0002a5f9
  Sleep   : 0x600ad1d6 0x0008a390
  Wake    : 0x600ad1de 0x000d6504
  Calendar: 0x600ad28e 0x00000f5e

> CORE 0 recently retired instr at 0xfffffe001b342c5c
CORE 1 recently retired instr at 0xfffffe001b342c5c
CORE 2 recently retired instr at 0xfffffe001b342c5c
CORE 3 recently retired instr at 0xfffffe001b342c5c
CORE 4 recently retired instr at 0xfffffe001b342c60
CORE 5 recently retired instr at 0xfffffe001b341798
CORE 6 recently retired instr at 0xfffffe001b342c60
CORE 7 recently retired instr at 0xfffffe001b342c60
Panicked task 0xfffffe166e1a6b88: 874 pages, 6 threads: pid 511: lsd
Panicked thread: 0xfffffe16747ee610, backtrace: 0xfffffe3f5429af00, tid: 461564
		  lr: 0xfffffe001b225f8c  fp: 0xfffffe3f5429af70
		  lr: 0xfffffe001b225d58  fp: 0xfffffe3f5429afe0
		  lr: 0xfffffe001b347f5c  fp: 0xfffffe3f5429b000
		  lr: 0xfffffe001b339914  fp: 0xfffffe3f5429b0b0
		  lr: 0xfffffe001b1df7e8  fp: 0xfffffe3f5429b0c0
		  lr: 0xfffffe001b2259e8  fp: 0xfffffe3f5429b450
		  lr: 0xfffffe001b2259e8  fp: 0xfffffe3f5429b4c0
		  lr: 0xfffffe001b9c03f8  fp: 0xfffffe3f5429b4e0
		  lr: 0xfffffe001b1ebc4c  fp: 0xfffffe3f5429b4f0
		  lr: 0xfffffe001b7b9e48  fp: 0xfffffe3f5429b750
		  lr: 0xfffffe001b46206c  fp: 0xfffffe3f5429b8d0
		  lr: 0xfffffe001b4615a0  fp: 0xfffffe3f5429bb10
		  lr: 0xfffffe001b47a838  fp: 0xfffffe3f5429bb60
		  lr: 0xfffffe001b449fa4  fp: 0xfffffe3f5429bd70
		  lr: 0xfffffe001b449e98  fp: 0xfffffe3f5429bdb0
		  lr: 0xfffffe001b8225a8  fp: 0xfffffe3f5429be40
		  lr: 0xfffffe001b3395f8  fp: 0xfffffe3f5429bef0
		  lr: 0xfffffe001b1df7e8  fp: 0xfffffe3f5429bf00

> last started kext at 323036078798: com.apple.filesystems.smbfs	3.4.1 (addr 0xfffffe001b0e4000, size 65536)
last stopped kext at 5391804738: com.apple.driver.usb.AppleUSBHostPacketFilter	1.0 (addr 0xfffffe001af7c000, size 16384)
loaded kexts:
com.apple.filesystems.smbfs	3.4.1
com.apple.filesystems.autofs	3.0
com.apple.fileutil	20.036.15
com.apple.driver.AppleTopCaseHIDEventDriver	4020.6
com.apple.iokit.IOBluetoothSerialManager	8.0.2f9
com.apple.driver.AppleBiometricServices	1
com.apple.driver.BCMWLANFirmware4378.Hashstore	1
com.apple.driver.CoreKDL	1
com.apple.driver.SEPHibernation	1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	11.5
com.apple.filesystems.apfs	1677.60.23
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.driver.ApplePMP	1
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	556.60.1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.AppleSmartIO2	1
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.AppleCS42L83Audio	437.96
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.AppleTAS5770LAmp	437.96
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleT8020SOCTuner	1
com.apple.driver.AppleT8103CLPCv3	1
com.apple.AGXG13G	172.20.14
com.apple.driver.AppleAVD	375
com.apple.driver.AppleAVE2	401.63.3
com.apple.driver.AppleJPEGDriver	4.6.0
com.apple.driver.AppleMobileDispH13G-DCP	140.0
com.apple.driver.usb.AppleUSBHostT8103	1
com.apple.driver.AudioDMAController-T8103	1.58
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleT8103PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleS5L8960XWatchDogTimer	1
com.apple.driver.AppleInterruptController	1.0.0d1
com.apple.driver.AppleT8020DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleT8101	1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	1
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	310
com.apple.kec.InvalidateHmac	1
com.apple.kext.triggers	1.0
com.apple.driver.AppleActuatorDriver	4400.28
com.apple.driver.AppleHIDKeyboard	222
com.apple.driver.AppleMultitouchDriver	4400.28
com.apple.driver.AppleHSBluetoothDriver	4020.6
com.apple.driver.IOBluetoothHIDDriver	8.0.2f9
com.apple.iokit.IOAVBFamily	900.12
com.apple.plugin.IOgPTPPlugin	900.11
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.IOBluetoothHostControllerPCIeTransport	8.0.2f9
com.apple.iokit.IOBluetoothHostControllerTransport	8.0.2f9
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltDPInAdapter	8.1.4
com.apple.driver.AppleThunderboltDPAdapterFamily	8.1.4
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleAOPAudio	14.32
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.nke.ppp	1.9
com.apple.driver.AppleHIDTransportSPI	4400.35
com.apple.driver.AppleHIDTransport	4400.35
com.apple.driver.AppleInputDeviceSupport	4400.35
com.apple.driver.AppleBSDKextStarter	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.AGXFirmwareKextG13GRTBuddy	172.20.14
com.apple.AGXFirmwareKextRTBuddy64	172.20.14
com.apple.driver.AppleSPU	1
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleCSEmbeddedAudio	437.96
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleEmbeddedAudio	437.96
com.apple.iokit.AppleARMIISAudio	80.34
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.iokit.IOGPUFamily	20.21.1
com.apple.driver.AppleH11ANEInterface	4.51.0
com.apple.driver.AppleH13CameraInterface	2.77.0
com.apple.driver.AppleH10PearlCameraInterface	14.70.0
com.apple.driver.DCPAVFamilyProxy	1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.AppleSPMI	1.0.1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleUSBXHCIARM	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleSART	1
com.apple.driver.ApplePMGR	1
com.apple.driver.watchdog	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.8
com.apple.driver.AppleT8103PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.2
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT8103PCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211FamilyV2	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleMCA2-T8103	510.72
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	900.11
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	585
com.apple.iokit.IOBluetoothFamily	8.0.2f9
com.apple.iokit.IOBluetoothPacketLogger	8.0.2f9
com.apple.driver.FairPlayIOKit	68.5.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	511.60.2
com.apple.iokit.IOUSBMassStorageDriver	184.40.6
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	436.40.6
com.apple.iokit.IOSCSIArchitectureModelFamily	436.40.6
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleEmbeddedAudioLibs	1.17
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	289.3
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.security.AppleImage4	3.0.0
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.corecrypto	11.1
com.apple.kec.Libm	1



> ** Stackshot Succeeded ** Bytes Traced 424166 (Uncompressed 1091696) **
</details>

**Comment by allamid06** [comment]
@aftabhussain02 , @a777med guys, I have to confess, I was really worried about this happening, because I was afraid it could be a hardware problem. Since I'm in Uruguay, it would be hard to take it back for a replacement. I'm using the 1.52.1 version, but since I'm kind of odd/antiquated developer, I'm not using it that much. Maybe that's the reason why it happened just once. 
All in all, I've heard about 4-5 people including us, that have experienced the same issue on MB with M1 CPUs. None of us or them have given any data about previous or related hardware problem. So... in the end, I guess is just Rosetta giving a bad translation that ends up in a really bad crash that for some reason I'm not getting even using Visual Studio with net core projects and some simulators. At the end it's part of being early technology adopters. I don't think it's a hardware issue, I don't think there is anything bad with out macs, and certainly I don't think it's something related to vs code. It's not running natively maybe that's the big deal...

**Comment by deepak1556** [comment]
Can you check if the crash repros with the arm64 application https://code.visualstudio.com/insiders/

<img width="395" alt="Screen Shot 2021-01-22 at 12 34 55 PM" src="https://user-images.githubusercontent.com/964386/105542501-495f9d80-5cae-11eb-9b8b-cd81404884d9.png">

**Comment by a777med** [comment]
> Can you check if the crash repros with the arm64 application https://code.visualstudio.com/insiders/
> 
> <img alt="Screen Shot 2021-01-22 at 12 34 55 PM" width="395" src="https://user-images.githubusercontent.com/964386/105542501-495f9d80-5cae-11eb-9b8b-cd81404884d9.png">

Wow. Thanks. I was using the x86 version. the ARM version seems to be OK. Also, a little faster when starting it up. For some reason, I did not notice the ARM64 link before. I thought it would automatically detect my system.
