### ISSUE TITLE
Native Notebooks - Timer Issues

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#114232]
Steps to Reproduce:

1. Open notebook
2. Run some cells 
3. Re-run cells
4. Watch timers

Issues: 
1. Sometimes timer for multiple cells runs at the same time - I would expect the timer for one to start only after the previous has completed
2. After running cells once, the timer starts at random strange values. If I continued running the cells the timer for the second cell would start at 10 seconds or 80 seconds or 100 seconds etc - I would expect the timer to start from zero again each time
![Timer Off](https://user-images.githubusercontent.com/19276747/104382540-1dd8f800-54e3-11eb-8ca9-95ec7f9cb1dd.gif)

**Comment by DonJayamanne** [comment]
@claudiaregio this is an issue with the Jupyter extension.
Please could you close this & file it in the Jupyter extension repo.

Also the time is an estimation, not an accurate time (communication, translation of protocols/messages could be adding a few extra milliseconds). 
if you want more accurate times we could use `%%time` magic & probably do that as a separate feature.
