### ISSUE TITLE
Can enumerate PowerShells test failure 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#114248]
Looks like the `Can enumerate PowerShells` test caused a failure:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=100258&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=99b4f36c-57e7-52a9-d2fb-83a564c876a6&l=7733

**Comment by bpasero** [comment]
Test is disabled.

**Comment by TylerLeonhardt** [comment]
This should be fixed now.
