### ISSUE TITLE
Error when trying to quit: One or more dirty editors could not be saved

### ISSUE THREAD

**Issue by albert239825** [microsoft/vscode#114244]
- VSCode Version: 1.52.1
- OS Version: window 10.0.19041

Steps to Reproduce:

1. I don't really know.
2. Code in python and quit VS Code? Sorry.

Occurs without extensions: yes

Current Behavior
This is very similar to issue #109404, except this is on my PC. When I try to close my VS Code, sometimes I get an error that says that one or more dirty editors could not be saved. Furthermore, I can't quit out of VS Code without ending the task in the task manager. Thank you so much for your help!

**Comment by bpasero** [comment]
I will need to ask for exact steps how to reproduce or output from log files to further assist.
