### ISSUE TITLE
VSCode lags if a videoConference is occurring

### ISSUE THREAD

**Issue by eunito** [microsoft/vscode#114261]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open Vscode
2. Open Chrome
3. Start videoconference with Google Meet and video from one of the other participants
4. Save file or try to code... autocompletes get lagged, hovering over methods lag, ...

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@eunito please verify your CPU usage in Window Process Explorer by application. It seems like Chrome is starving VS Code of cycles.
