### ISSUE TITLE
Option to show folder name in tabs for files with the same name

### ISSUE THREAD

**Issue by Ruzo** [Microsoft/vscode#11421]
When several files with the same name are opened (which is especially common with index files), it would be great to have the option to show the folder name of its location. An option between showing the folder name or a path could cover different use cases.

This is how Sublime does it:
![sublime_tabs_folder_names](https://cloud.githubusercontent.com/assets/1992115/18186458/e7c1fcae-7070-11e6-86c9-00ce660b0721.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8499

**Comment by Ruzo** [comment]
Great, thanks. that's after searching for a good while. Sorry.
If the title of #8499 included 'tab', maybe that would make it easier to find. Or, maybe there is a better way to search?
