### ISSUE TITLE
[javascript] Leading space is added for new line when code block is preceded by multi-line comment block

### ISSUE THREAD

**Issue by akphi** [microsoft/vscode#114236]
- VSCode Version: 1.52.1
- OS Version: Mac OS 11.1 (Big Sur)

Steps to Reproduce:

1. In a javascript file, add a multi-line comment `/** ... */`
2. In the code line right after that comment, place the cursor at the beginning of the line and hit enter
3. A new line is created with a leading space, why? This doesn't happen when there is no comment prior to the code block.

Hope the attached screen capture helps with reproducing the issue.

https://user-images.githubusercontent.com/13574879/104393045-7cb56600-5511-11eb-9164-7157886b7d53.mov

Does this issue occur when all extensions are disabled?: Yes

I have tested with both the Insiders version and https://vscode-web-test-playground.azurewebsites.net/?enter=true

**Comment by mjbvz** [comment]
Repo:

```js
/**
 * comment
 */
// press return twice on this line
```
