### ISSUE TITLE
`forceNewWindow: false` not being respected

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#114259]
To repro, connect to a container then File -> Open another file in that container.
Expected: The file opens in the same window.
Actual: A new remote window is opened for just this one file.

`openWindow` is called from the file dialog service with `forceNewWindow: false`, which has always worked for this in the past. However, that flag appears not to be used now.

**Comment by bpasero** [comment]
Feel free to move back if this is not remote specific, dont think I touched this code recently.

**Comment by alexr00** [comment]
@bpasero I debugged to https://github.com/Microsoft/vscode/blob/7f7307b89a348b06099d43bd36d8bf3583feb358/src/vs/workbench/services/host/electron-sandbox/nativeHostService.ts#L69-L70
And saw that the correct value for `forceNewWindow` made it that far, which is why I thought it was opener related.

**Comment by bpasero** [comment]
@alexr00 `forceNewWindow: false` does not force a window to be reused. Rather, settings will be respected. See my comment from before that I just udpated.

**Comment by alexr00** [comment]
Doh! I had some settings from testing that were causing this. Sorry for the noise.
