### ISSUE TITLE
Saving images with data urls doesn't work in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114225]
- Version: 1.53.0-insider
- OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Install Jupyter extension (download VSIX with support for widgets from here https://pvsc.blob.core.windows.net/extension-builds-jupyter-public/ms-toolsai-jupyter-insiders-with-widgets.vsix)
2. Install extension in VS Code Insiders
3. Create a notebook & select a Python kernel
4. Run the following in a cell to install required dependencies
(Ensure cell language is `python`)
```
!pip install matplotlib
```
4. Run the following in a cell to install required dependencies
```
!pip install ipympl
```
4. Run the following in a cell to view the plot
```python
import matplotlib.pyplot as plt
%matplotlib widget
plt.plot([1,2,3,4],[1,2,3,4])
```
4. Click the last (bottom most) icon in the toolbar to save the plot (see screenshot or hover to see tooltip of icon).
**Nothing happens.**

Try the same in old notebooks in Jupyter Extension (stable VS Code or just create a python file and run the python code against a python environment with required dependencies), when the plot viewer appears you can click on the save icon & you'll be able to save the plot to a png file.

I believe the issue is vscode is ignoring window navigate events when attempting to save files with a blob url.
I believe the following is not working in VS Code native notebook https://github.com/matplotlib/ipympl/blob/bd477f537464a3cc7e3196cb820a8531d97c7f97/js/src/mpl_widget.js#L90-L97

See here for how we added support for this in old notebooks & interactive window https://github.com/microsoft/vscode-jupyter/blob/main/src/datascience-ui/interactive-common/handlers.ts#L25-L45

5. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
I remember @roblourens had similar fixes before for blob url.

**Comment by DonJayamanne** [comment]
Validated, thanks.
