### ISSUE TITLE
Add "vscode.executeSemanticTokensProvider" command

### ISSUE THREAD

**Issue by ryanbrandenburg** [microsoft/vscode#114299]
Now that SemanticTokens are no longer a preview feature of the LSP specification (as of v3.16) [it would be helpful](https://github.com/dotnet/aspnetcore-tooling/blob/d1e1e11d3496eb7e999a88e61dfa054a0942679c/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/Semantic/SemanticTokensHandler.ts#L35) to have a `vscode.executeSemanticTokensProvider` command [like other LSP concepts have](https://code.visualstudio.com/api/references/commands#commands).

My specific scenario for this is to allow SemanticTokens for C# portions of code in the Razor VSCode extension.

[Here's an example](https://github.com/dotnet/aspnetcore-tooling/blob/master/src/Razor/src/Microsoft.AspNetCore.Razor.VSCode/src/RazorCodeLensProvider.ts#L60) of us doing something similar with CodeLens results.

**Comment by alexdima** [comment]
This is a bit more complex than other providers because the semantic tokens provider contains a legend, so basically invoking `vscode.executeSemanticTokensProvider`, getting the encoded semantic tokens from another provider and just returning them would not work well if the legends are not 100% equal. It is also an open question if the result should always include the legend and the tokens, or just the tokens.

So this provider is somewhat different than other providers because the results cannot be composed so easily as others.

cc @jrieken are there other providers with multiple "methods"? Should we have two commands, like `vscode.getSemanticTokensProviderLegend` and `vscode.executeSemanticTokensProvider` or should there be a single command returning both.

**Comment by jrieken** [comment]
Yeah, for call hierarchy there are multiple commands: prepare, incoming calls, and outgoing calls: https://github.com/microsoft/vscode/blob/6f11d34f677a57815e6ffa31b8b9f9f320b62dcd/src/vs/workbench/api/common/extHostApiCommands.ts#L143

**Comment by ryanbrandenburg** [comment]
I noticed that this is assigned but listed as backlog, does that imply anything about the ETA? We're eager to get this in so we can improve our Semantic Colorization story.

**Comment by alexdima** [comment]
The commands are:
- `vscode.provideDocumentSemanticTokensLegend` with an argument of type `Uri`
- `vscode.provideDocumentSemanticTokens` with an argument of type `Uri`
- `vscode.provideDocumentRangeSemanticTokensLegend` with an argument of type `Uri`
- `vscode.provideDocumentRangeSemanticTokens` with two arguments: the first an `Uri` and the second a `Range`.

**Comment by pgfearo** [comment]
I maintain a semantic tokens provider for XPath, a widely used sub-language (here, all tokens are 'semantic' there are no non-semantic tokens). Would it be possible to extend `provideDocumentRangeSemanticTokens` so that it also takes a language-id argument like 'xpath'?

**Comment by alexdima** [comment]
@pgfearo Our language providers work with text documents. So if someone wants to invoke your provider on a piece of text, they can create a new text document, set the content they want, and then invoke your provider on that URI. This can be a `file://` URI, but it can also be a virtual document. VS Code offers other APIs through which schemes can be registered and defined by extensions.

**Comment by pgfearo** [comment]
An imaginative idea - only really feasible with virtual documents. However I fear what you're suggesting would prove too much effort for what would otherwise be a simple linter extension for say JavaScript with many embedded XPath expressions.

**Comment by alexdima** [comment]
@pgfearo These commands are directly driven by our semantic tokens providers API which work with text documents. All other language features providers work in the same way. So for example requesting suggestions also requires having a text document, etc. So this is not something that can be added as a one-off for semantic tokens providers.

The simple alternative would be for your extension to export API (this can be done by returning an object from your `activate` method). Then, other extensions (using `vscode.extensions`) could load your extension and exercise its API directly. In the API you export, you can export any kind of method signature, like `tokenizeXPath(text: string): ... `

**Comment by pgfearo** [comment]
Thanks for explaining this restriction for providers, I had come across this with the notebook API, and initially couldn't understand why example code was making temporary files. I will export an API as you suggest.
