### ISSUE TITLE
When i type "code .env" command in my git bash terminal, it does not launch vs code application as usual, it prompt me with a Javscript error msg

### ISSUE THREAD

**Issue by janetcheung-byte** [microsoft/vscode#114239]
```
A JavaScript error occurred in the main process.

Windows: Unexpected undefined %USERPROFILE% environment variable at Object.getDefaultUserDataPath (C:\Users\Username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\paths.js:5:288
```

Help I need to fix this!

![image](https://user-images.githubusercontent.com/54462304/104395626-1a5f6400-5517-11eb-98f8-0106f25c8fda.png)

**Comment by meganrogge** [comment]
did this start happening recently? 

what's your VS code version?

have you run extension bisect? this could be caused by an extension

**Comment by janetcheung-byte** [comment]
Thank you for your response!  Somebody have just solved this issue. The problem was that a virtual environment was activated from my bash terminal. The solution for me is to deactivate the environment.
