### ISSUE TITLE
Support Speculative Preloading Of Custom Editors

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#114270]
If custom editors are used by a lot of users on machines with a lot of free RAM (like 10 GB), this moderate-effort issue might make subsequent openings of some custom editors instantanious.

I think speed is a signature of VS Code and a lot of people would be fine with increased memory usage if they get increased performance, as long as their machine admits that. This trade of memory vs performance should be optional though.

Currently, `CustomTextEditorProvider` looks like this:
```ts
export interface CustomTextEditorProvider {
    resolveCustomTextEditor(document: TextDocument, webviewPanel: WebviewPanel, token: CancellationToken): Thenable<void> | void;
}
```

I suggest to extend that interface to something like this:
```ts
export interface CustomTextEditorProvider<TPreloadData = {}> {
    resolveCustomTextEditor(
        document: TextDocument,
        webviewPanel: WebviewPanel,
        token: CancellationToken,
        preloadData: TPreloadData | undefined // new
    ): Thenable<void> | void;

    /**
     * Might be called speculatively before
     * `resolveCustomTextEditor` to preload the webview.
     * Might not be called at all.
     */
    public async preloadCustomTextEditor?(
        webviewPanel: WebviewPanel,
        token: CancellationToken
    ): Promise<TPreloadData>;
}
```

Extensions can use `preloadCustomTextEditor` to initialize the webview with all the application code. At least for the Draw.io custom text editor, initializing the application takes far longer (~3s) than loading the data (~50 ms).
Even the Hex-Editor takes some time to initialize before the white webview shows some UI controls.

VS Code could speculatively spawn hidden webviews and call `preloadCustomTextEditor` to prepare the webview without knowing yet which file, if any, will be opened. VS Code would need to guess which custom text editor will be used.

I can think of the following algorithm to decide what to preload:
1. If a user opens a file with a custom editor provided by some `c: CustomTextEditorProvider<TPreloadData>`, wait until some CPU/Memory resources are available.
2. If (1) happened in the last 5 minutes and some resources became available, spawn a hidden webview and preload it with `c.preloadCustomTextEditor` and store the returned `TPreloadData`. Dispose this webview if not used after 10 minutes or if memory-pressure increases.
3. If the user opens a file with a custom editor and its `CustomTextEditorProvider` preloaded a hidden webview that is still available, use that hidden webview and call `resolveCustomTextEditor` with the stored `TPreloadData`.

This algorithm bases on the assumption that if a user has one file that they open with a custom editor, they likely have more files that they open with the same custom editor.

Extensions/Modifications of this idea could be:
1. Do this also for arbitrary webviews
2. Allow to reuse custom editors (introduce `CustomTextEditorProvider.isWebviewReusable: boolean`) so that closed custom editors are not fully disposed, but only hidden
3. Allow to create hidden webviews / to hide/show webviews
4. Don't use some `TPreloadData` and move to burden to the extension author to check whether this particular `webviewPanel` has been preloaded/used (a map could be used for that).

Some research would be needed to see whether this feature is worth it. I would love to have it.

**Comment by mjbvz** [comment]
Interesting problem but I don't think it's something we'd want in the form you propose. Even if we think a user has free resource, they may not take kindly to us speculatively allocating memory and using cpu for something they did not trigger and cannot control. 

Have you profiled to see why the DrawIO extension takes so long to render currently?

**Comment by mjbvz** [comment]
Closing as out of scope given the lack of additional feedback for this
