### ISSUE TITLE
No longer able to edit commit message via "Amend"

### ISSUE THREAD

**Issue by josemigallas** [microsoft/vscode#114204]
Issue Type: <b>Bug</b>

Steps to Reproduce:

In Source Control tab, select "Commit > Commit All (Amend)" or "Commit > Commit Staged (Amend)". It should prompt the user to enter a commit message.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

https://user-images.githubusercontent.com/11672286/104309315-3bea2c80-54d2-11eb-920b-80e8712143d6.mp4

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (1.18GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id 0719ccf2-1f18-49b5-93aa-6bccb2c0476d|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt859:30241729
vsjup459cf:30237188

```

</details>

**Comment by RMacfarlane** [comment]
I'm still not seeing a quick input when running these commands

**Comment by eamodio** [comment]
No quick-input anymore, we re-use the SCM input (which could have been hidden before this change). Are you not seeing the message in the SCM view's input?

**Comment by RMacfarlane** [comment]
That works! Confirmed the SCM view input is visible in the multi-repo case.
