### ISSUE TITLE
MacBook Pro M1 Unable to debug .NET APP

### ISSUE THREAD

**Issue by zack542** [microsoft/vscode#114241]
- VSCode Version:Latest official version
- OS Version:Mac OS Big Sur 11.0.1

Steps to Reproduce:

1.dotnet new mvc --auth Individual
2.OPEN HomeController.cs   
3.Insert Breaks
4.debugger
![a1](https://user-images.githubusercontent.com/34257415/104403294-37397d00-5593-11eb-891d-743e79306057.jpg)
![a2](https://user-images.githubusercontent.com/34257415/104403306-3a346d80-5593-11eb-82c0-ae39337d7177.jpg)
![a3](https://user-images.githubusercontent.com/34257415/104403311-3dc7f480-5593-11eb-9a8a-013e7238d79d.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by zack542** [comment]
[https://pic1.zhimg.com/v2-2eac6e7c4f49210d7f885bbe70331420_b.jpg](url)
[https://pic4.zhimg.com/v2-4f386887752f1083d7120e9a52c48c2b_b.jpg](url)
[https://pic3.zhimg.com/v2-12c36ab47ca7f8fb132aea941c98e1ae_b.jpg](url)

**Comment by zack542** [comment]
"Visual studio for Mac" debugging also crashes

**Comment by weinand** [comment]
Please file this against the C# extension.
