### ISSUE TITLE
search.useIgnoreFiles seems to be ignored. 

### ISSUE THREAD

**Issue by reneweteling** [microsoft/vscode#114262]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. enable ignore files setting
```json
{
  "search.useGlobalIgnoreFiles": true,
  "search.useIgnoreFiles": true
}
```
2. have a .gitignore file that ignores for instance the `.elixir_ls` folder
```.gitignore
.elixir_ls
```
3. search for something, and you will see hits in the excluded folder
![image](https://user-images.githubusercontent.com/3830933/104439075-ffc9d100-5590-11eb-9c4e-4a14d48e67a9.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by reneweteling** [comment]
sorry, it was hidden feature in teh UI more info here https://github.com/microsoft/vscode/issues/94689

**Comment by roblourens** [comment]
Glad you figured it out. I'm curious whether you noticed the message "exclude settings and ignore files are disabled" and how you interpreted it. Would it help if that message was a link, and clicking it would toggle that button back on? That is something I have considered.
