### ISSUE TITLE
Show which extension is generating intellisense

### ISSUE THREAD

**Issue by SharakPL** [microsoft/vscode#114207]
![obraz](https://user-images.githubusercontent.com/5007456/104321873-78bf1f00-54e4-11eb-8d07-1dbc007fec53.png)

Sometimes I get weird intellisense that messes with my workflow. I want to hit <kbd>enter</kbd> to write my style properties, but instead I get `{{`. I have no idea how to fix it other than disable extenstions one by one. Would be much better if each intellisense proposal (or each group of proposals) was described by the name of extension that generated it.

**Comment by jrieken** [comment]
You can press `cmd+/` when suggestion show. it will toggle the suggest details widget with meta information which also include the extension id. 

<img width="840" alt="Screenshot 2021-01-12 at 16 02 27" src="https://user-images.githubusercontent.com/1794099/104331616-92b22f00-54ef-11eb-90ae-901651817734.png">

**Comment by SharakPL** [comment]
@jrieken thanks, I was not aware of this :) Though it doesn't fix my problem, cause this weird suggestions don't have any details. Nothing shows on `ctrl + space` or `ctrl + /`. It must be one of the extensions that are supposed to provide classes from styles and html. Clearly something is broken there cause both `{{` and `vc_{{` are not valid html classes. Searched whole project for these strings but couldn't find anything. I have no idea where this comes from :(

**Comment by jrieken** [comment]
>  Searched whole project for these strings but couldn't find anything. I have no idea where this comes from :(

Likely means that it is caused by an extension then. You can try the bisect flow to figure out which extension this is: F1 > Start Extension Bisect and then follow the steps
