### ISSUE TITLE
a new "down,up"

### ISSUE THREAD

**Issue by preiodGeek** [Microsoft/vscode#11425]
- VSCode Version:1.4.0
- OS Version:

Steps to Reproduce:
1. ![qq 20160902104502](https://cloud.githubusercontent.com/assets/17465121/18191110/531c7f22-70fa-11e6-9c9d-16b24a9891cc.png)
2. i need a keybindings (alt+shift+j   ===  down, alt+shift+k === up)

**Comment by preiodGeek** [comment]
a new "down,up" 2016/09/02

**Comment by dbaeumer** [comment]
@preiodGeek You can configure these keybindings yourself using File > Preferences > Key Bindings.

@bpasero do you see any reason to include this in the product by default?

**Comment by bpasero** [comment]
If this is standard navigation in tree it would have to go into the tree @joaomoreno

**Comment by joaomoreno** [comment]
Is it, though? Where is this standard?

@preiodGeek, why these specific keybindings? Where else are they used?

**Comment by joaomoreno** [comment]
Closing due to silence.
