### ISSUE TITLE
Saving file deletes redo history.

### ISSUE THREAD

**Issue by ConduciveMammal** [microsoft/vscode#114209]
Issue Type: <b>Bug</b>

When saving a file, it seems to delete redo history.

### Replicate
* Open a document and make some changes
* Save the file and using Cmd/Ctrl+z, undo some of those changes
* Save the file again and use Cmd/Ctrl+Shift+z to redo those changes.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 4a9c861e-8151-46a8-904b-dc014f93ec08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
polaris-snippets|And|0.1.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
coddx-alpha|cod|0.2.28
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
vscode-dash|dee|2.4.0
githistory|don|0.6.14
jquerysnippets|don|0.0.1
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
auto-complete-tag|for|0.1.0
vscode-drawio|hed|1.2.0
beautify|Hoo|1.5.0
vscode-fast-folder-structure|Huu|3.1.1
vscode-cdnjs|Jak|0.18.0
vscode-liquid-snippets|kil|2.0.1
vscode-autoprefixer|mrm|3.0.1
vscode-scss|mrm|0.9.0
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.13.0
bash-beautify|sha|0.1.1
stylelint|shi|0.51.0
json-template|sto|0.3.1
vscode-status-bar-format-toggle|tom|2.0.0
vscode-sort-package-json|uni|1.2.2
vscodeintellicode|Vis|1.2.10
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244cf:30236574
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
vsjup459:30237187

```

</details>

**Comment by alexdima** [comment]
@ConduciveMammal Does the issue reproduce when you disable your extensions? Do you perhaps have some extensions that participate on save?
