### ISSUE TITLE
App exits during debug "The program '[2967] xxxxxxx.dll' has exited with code 0 (0x0)."

### ISSUE THREAD

**Issue by ljunquera** [microsoft/vscode#114279]
- VSCode Version: Version: 1.53.0-insider
- OS Version: macOS Big Sur 11.1 (MacBook Pro, 13 inch, M1, 2020)

Steps to Reproduce:

1. Open a Razor Pages project
2. Click on .NET Core Launch (web)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Please file the issue against the C# extension.
