### ISSUE TITLE
BackupRestorer: after each" hook for "Restore backups"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114273]
```
1) BackupRestorer
       "after each" hook for "Restore backups":
     Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\VSSADM~1\AppData\Local\Temp\vsctests\backuprestorer\1b36d813-1f9d-4c2e-b8e6-e57326506f35\Backups\2746e85e3aa3db1143f8b6945d3619a5\untitled'

```

//cc @alexdima (interesting that we still seem to be hitting these after all your changes)

**Comment by alexdima** [comment]
I think we might be seeing these for a while until we fix all these tests. We fixed together the `BackupTracker` suite, while this one appears to be another one, `BackupRestorer`. We could now use the `vs/base/test/common/troubleshooting` utilities to try to pinpoint the problem. In this case, it also looks like all tests share the same backup directory, so there might be more overlap than usual. LMK if you need any help from me.
