### ISSUE TITLE
asDebugSourceUri does not adhere to spec regarding sourceReference

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode#114229]
- VSCode Version: 1.52.1
- OS Version: Win10 / WSL2

`asDebugSourceUri` was introduced in #79228 by @weinand.
https://github.com/microsoft/vscode/blob/04efea43fa3ab33e8a50bbf3caf0270f6b0b3030/src/vs/workbench/api/common/extHostDebugService.ts#L151-L171

But it doesn't follow the [spec](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source) which allows `sourceReference` set to 0 to denote a normal path which is what the C# debugger does:
```js
"stackFrames": [
      {
        "id": 1000,
        "name": "Program.Main(string[] args) Line 16",
        "source": {
          "name": "Program.cs",
          "path": "/.../Program.cs",
          "sourceReference": 0,
        },
        "line": 16,
        "column": 13,
```
which when passed to `showTextDocument` results in a blank editor with `Could not load source '/.../Program.cs': Incorrect format of 'source' message..`
```cs
const srcuri = vs.debug.asDebugSourceUri(frame.source);
const editor = await vs.window.showTextDocument(srcuri);
```

**Comment by weinand** [comment]
@Trass3r good find, thanks!

**Comment by lonix1** [comment]
@Trass3r Same prblem here... did the latest vscode (1.53.2) fix it for you? It didn't for me.
