### ISSUE TITLE
Add activation event `onNotebook:*`

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#114233]
It would be beneficial for an extension that only provides a notebook kernel provider to add `onNotebook:*` to its activation events, because that notebook kernel doesn't care what notebook content provider is doing the display work.

**Comment by rebornix** [comment]
It doesn't work in following scenario:

* Install Jupyter extension
* Install .NET Interactive Notebook
* Run command "Jupyter: Create New Blank Jupyter Notebook"
* Run command "Select Notebook Kernel"
* .NET Interactive extension is not activated, thus no .NET kernel are contributed to the list

**Comment by connor4312** [comment]
> 
> 
> It doesn't work in following scenario:
> 
>     * Install Jupyter extension
> 
>     * Install .NET Interactive Notebook
> 
>     * Run command "Jupyter: Create New Blank Jupyter Notebook"
> 
>     * Run command "Select Notebook Kernel"
> 
>     * .NET Interactive extension is not activated, thus no .NET kernel are contributed to the list

I reproduced this issue in the latest Insiders: https://memes.peet.io/img/21-01-8248bd4c-2305-4ae0-819b-79fec51dbf07.mp4

Does .net or python need to adopt something for this to work?

**Comment by brettfo** [comment]
The currently released version of the .NET Interactive extension doesn't say that it wants to trigger on `onNotebook:*`, but our unreleased internal builds _do_ have this, so as soon as we finish our current round of updates and publish, then it'll work.

**Comment by connor4312** [comment]
Ok, thanks, please comment `/verified` if you know that this works already 🙂
