### ISSUE TITLE
Window crashing when connecting to remote instance with v1.52

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode#114227]
- VSCode Version: 1.52.0, 1.52.1
- OS Version: Multiple [Mac, WIndows]

Steps to Reproduce:

1. Install Azure Machine Learning extension for VS Code.
2. Ensure you're using VS Code version 1.52.1.
3. Navigate to ml.azure.com. Pick an Azure subscription and workspace.
4. Navigate to the Compute tab and create a new compute instance (if there isn't one listed that's usable).
5. Click on the "VS Code" link [this will only be shown if working in an internal subscription].
6. Land in VS Code and allow the AML extension to set up a remote instance (connected to the compute instance).
7. Validate that the "VS Code server" and "websocket servers" have been installed successfully.
8. Validate that a remote window is opened and that the Azure ML extension attempts to create a connection.
9. The window crash should occur at this point.

Does this issue occur when all extensions are disabled?: No [scoped to functionality in the Azure Machine Learning extension

Context:
Some Azure ML extension users have filed issues related to connecting to their compute instances through a remote VS Code window (new capability shipped in Dec 2020). These users were successfully connecting after the initial release of the capability (prior to the 1.52 ship).

We tested configurations with these users to see whether there was a pattern in terms of extension and Code versions:

| VS Code Version | AML Extension Version | Connection Result |
| - | - | - |
| 1.52 | 0.6.19 | Unable to connect; window crashes when connecting |
| 1.52 | 0.6.20 (experimental bits that move remote functionality to different extension) | Unable to connect; window cashes when connecting |
| 1.51 | 0.6.19 | Successful Connection |

Action Items
1. Working on obtaining crash reports from users running into this issue.
2. Asking users to try Insider bits and see if able to reproduce.

Additional Notes:
We tried 'cache clearing' to see if that helped resolve the issue. The following screenshot explains the deletion process:
![image](https://user-images.githubusercontent.com/6413608/104376865-76f05e00-54da-11eb-936b-801ea8b3dc72.png)

**Comment by roblourens** [comment]
I don't know why the window would crash only when connecting to a remote, or what changed in 1.52. Offline @SiddhanthUnnithan is trying to get a crash dump. But wondering if you have any idea @alexdima or why deleting those user data dir folders would fix it. The only thing that stands out to me is the folder that contains the cached compiled js, there are modules loaded in a remote window that are not loaded in a local window.

**Comment by SiddhanthUnnithan** [comment]
@roblourens I've attached the _log_ files that were obtained after the crash. To clarify the _log_ files were just copied from the console output when running "code ..".

Please let me know if there's anything else needed to help diagnose the issue.
[45be461b-272a-410a-9b18-1db09dc43379.log](https://github.com/microsoft/vscode/files/5817103/45be461b-272a-410a-9b18-1db09dc43379.log)

[a530e90c-df18-4983-8dd6-34ff97a0356d.log](https://github.com/microsoft/vscode/files/5817104/a530e90c-df18-4983-8dd6-34ff97a0356d.log)

For some reason I'm unable to include the _dmp_ files here. I'll send them over mail.

**Comment by SiddhanthUnnithan** [comment]
@roblourens I sent mail with the dmp and log files (we suspected they contained AAD credential traces so we didn't want to upload here). Let me know if there's anything more you need from me!

**Comment by alexdima** [comment]
cc @deepak1556 who has some good ways to symbolize native crashes.

**Comment by deepak1556** [comment]
@SiddhanthUnnithan were the crash dumps taken following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports 

Can you please add me to the mail with the crash dumps deepak.mohan@microsoft.com

**Comment by roblourens** [comment]
I forwarded them to you @deepak1556. I haven't tried to look at them yet.

**Comment by deepak1556** [comment]
Thanks for the crash dmps, all the 3 dmps have the following trace. 

```
Crash reason:  EXC_BREAKPOINT / EXC_I386_BPT
Crash address: 0x10bb81d65
Process uptime: 4 seconds

Thread 0 (crashed)
 0  Electron Framework!blink::V8ArrayBuffer::ToImpl(v8::Local<v8::Object>) [v8_array_buffer.cc : 77 + 0x0]
    rax = 0x0000000000000000   rdx = 0x00000001091fd838
    rcx = 0x00000001091fd7c4   rbx = 0xffffffff00000000
    rsi = 0x0000000000000000   rdi = 0x0000000000000014
    rbp = 0x00007ffeeab4d390   rsp = 0x00007ffeeab4d320
     r8 = 0x00007ffeeab4d478    r9 = 0x0000000000007ba9
    r10 = 0x00000000fffffe1f   r11 = 0x00007fe0d707d870
    r12 = 0x0000003d00000000   r13 = 0x00007ffeeab4d598
    r14 = 0x00007fe0d780bca8   r15 = 0x00007ffeeab4d450
    rip = 0x000000010bb81d65
    Found by: given as instruction pointer in context
 1  Electron Framework!blink::V8Uint8Array::ToImpl(v8::Local<v8::Object>) [v8_uint8_array.cc : 73 + 0x8]
    rbp = 0x00007ffeeab4d3c0   rsp = 0x00007ffeeab4d3a0
    rip = 0x000000010bb82d26
    Found by: previous frame's frame pointer
 2  Electron Framework!blink::V8ArrayBufferOrArrayBufferView::ToImpl(v8::Isolate*, v8::Local<v8::Value>, blink::ArrayBufferOrArrayBufferView&, blink::UnionTypeConversionMode, blink::ExceptionState&) [v8_binding_for_core.h : 479 + 0xb]
    rbp = 0x00007ffeeab4d3f0   rsp = 0x00007ffeeab4d3d0
    rip = 0x000000010b9ea60d
    Found by: previous frame's frame pointer
 3  Electron Framework!blink::V8SubtleCrypto::DigestMethodCallback(v8::FunctionCallbackInfo<v8::Value> const&) [v8_subtle_crypto.cc : 282 + 0xa]
    rbp = 0x00007ffeeab4d4d0   rsp = 0x00007ffeeab4d400
    rip = 0x000000010cfc3cb5
    Found by: previous frame's frame pointer
 4  Electron Framework!v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [api-arguments-inl.h : 158 + 0x6]
    rbp = 0x00007ffeeab4d580   rsp = 0x00007ffeeab4d4e0
    rip = 0x0000000108eed8bf
    Found by: previous frame's frame pointer
 5  Electron Framework!v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [builtins-api.cc : 111 + 0xb]
    rbp = 0x00007ffeeab4d630   rsp = 0x00007ffeeab4d590
    rip = 0x0000000108eecde1
    Found by: previous frame's frame pointer
 6  Electron Framework!v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [builtins-api.cc : 141 + 0x21]
    rbp = 0x00007ffeeab4d6c0   rsp = 0x00007ffeeab4d640
    rip = 0x0000000108eec472
    Found by: previous frame's frame pointer
```


`EXC_BREAKPOINT` means a crash due to `CHECK` condition failure and according to the chromium source its at https://source.chromium.org/chromium/chromium/src/+/master:out/win-Debug/gen/third_party/blink/renderer/bindings/core/v8/v8_array_buffer.cc;l=77

Based on the callstack its triggered by call to `blink::V8SubtleCrypto::DigestMethodCallback` and the only place in our renderer code where we call it is https://github.com/microsoft/vscode/blob/master/src/vs/base/browser/hash.ts#L13

The `CHECK` crash means that there was unsuccessful attempt in obtaining the C++ backing class associated with the v8 buffer argument passed to `crypto.subtle.digest`, most likely the object got GC'd ?

**Comment by deepak1556** [comment]
I couldn't repro with the some sample strings to `sha1Hex` call and I don't have `ml.azure.com` setup. @alexdima can you try to see what kind of input goes to `sha1Hex` following https://github.com/microsoft/vscode/issues/114227#issue-784608856 

If there is a sample remote instance I can use, would be helpful to debug further.

**Comment by alexdima** [comment]
@deepak1556 Thank you for investigating. 

@bpasero I remember you asking me about the `crypto` browser API, but I don't think I call that method from anywhere. Maybe the `crypto` API does not allow to pass in a native JS `string` created via `TextEncoder`. I remember we have seen very weird behaviours where strings created via `TextEncoder` would not show up in the heap snapshot?

**Comment by alexdima** [comment]
@deepak1556 So that code path does something like this:
```js
crypto.subtle.digest({ name: 'sha-1' }, Buffer.from(str))
```
where `str` is some string passed into `sha1Hex`. Why would `Buffer.from(str)` return an invalid `ArrayBuffer`

**Comment by SiddhanthUnnithan** [comment]
@deepak1556, @alexdima, @roblourens we had another user that was seeing the same window crash issue. I'm forwarding the dmp file to you all via mail (GH isn't allowing me to attach with this comment).

**Comment by alexdima** [comment]
cc @bpasero if you have any ideas if the strings we pass into `sha1Hex` are in any way special.

**Comment by bpasero** [comment]
@alexdima yes, special in that in Electron `VSBuffer` will use node.js `Buffer` and as such we pass a node.js `Buffer` to Chrome API. I discussed this with @deepak1556 and a workaround would be to explicitly use `TextEncoder` in `browser/hash.ts`.

**Comment by bpasero** [comment]
Slightly related, I think SHA1 is overkill for what we use it here: telemetry hashes for paths can easily use our own hash implementation in `common`.

**Comment by deepak1556** [comment]
> Why would Buffer.from(str) return an invalid ArrayBuffer

@alexdima its hard to say without having to see the stack state in the captured process dump, the previous provided dumps where from macOS and I don't have a good way of inspecting them. The recent one I got from windows can be looked into further, will get back with more info from there.

**Comment by deepak1556** [comment]
I couldn't make much progress in backtracking the values passed down to the crypto callback on the native side, couldn't resolve most of the pointer regions in the minidump.

@alexdima as next step we could either log the value of `str` passed to `sha1Hex` and see the inputs from users that observe the crash, it might give some clue. Or we could go ahead and try the workaround of using `TextEncoder` instead of node buffer.

**Comment by alexdima** [comment]
I've pushed https://github.com/microsoft/vscode/commit/1848d3111fc73054dec98c84edf70e64f3c19cf8 to be able to use `VSBuffer` directly with `TextEncoder`.

**Comment by bpasero** [comment]
Looks good, maybe a link to this issue from that code would help understand the reason why we use that new option.

**Comment by alexdima** [comment]
:+1: feel free to push (I'm not sure about ownership of `hash.ts`)

**Comment by bpasero** [comment]
Done

**Comment by sevillal** [comment]
@alexdima @bpasero will this fix be part of the next insiders build?

**Comment by bpasero** [comment]
@sevillal yeah we already released a new insiders including this change, can you try it out?

**Comment by SiddhanthUnnithan** [comment]
@bpasero we've had one internal user test with Insiders and it's worked! We're asking some others that were running into this issue to do the same. Will follow up in this thread if we run into anything.

**Comment by deepak1556** [comment]
Closing as there haven't been newer reports after the workaround.
