### ISSUE TITLE
Saving an untitled file closes it

### ISSUE THREAD

**Issue by nynsrkr** [microsoft/vscode#114272]
- VSCode Version: 1.53.0-insider for arm
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. After pressing Command + N,  to open a blank new tab.
2. Saving the file using Command + S to any extension or location causes the tab to crash.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by nynsrkr** [comment]
No .dmp file is been

> Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

I followed the steps , no dmp file is generated.

**Comment by bpasero** [comment]
When you say it crashes "Tab", what does that mean? Can you record a screen recording?

**Comment by nynsrkr** [comment]
> When you say it crashes "Tab", what does that mean? Can you record a screen recording?

After clicking save on the save dialog box, the tab simply closes by itself. Its only happening on the Insider builds.

**Comment by nynsrkr** [comment]
Screen Recording

https://user-images.githubusercontent.com/10292012/104543999-cb87fc00-55f4-11eb-975d-e253e1bb2eb7.mov

**Comment by bpasero** [comment]
Yeah that looks like an issue to me, strange. To clarify: you tried this with all extensions disabled? Can you reproduce this on another machine without macOS ARM?

**Comment by bpasero** [comment]
Oh nevermind, I can reproduce this too.
