### ISSUE TITLE
SCM input border is cropped

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#114201]
![recording (6)](https://user-images.githubusercontent.com/22350/104305012-ffdaab80-5480-11eb-873c-951a7f6a7121.gif)

Probably from https://github.com/microsoft/vscode/pull/112316

My settings:

- VS Code Zoom: 0
- Windows scaling: 125%

**Comment by sbatten** [comment]
I'm reproing the original issue (negative zoom case now)
