### ISSUE TITLE
Add command to close all notifications from the terminal

### ISSUE THREAD

**Issue by zwhitchcox** [microsoft/vscode#114268]
In reference to #114069, I was directed to open an issue regarding the inability to close all notifications from the terminal.

As a specific use case, there is the popup that notifies you that a terminal exited with a non-zero error code:

![Screenshot from 2021-01-12 09-01-53](https://user-images.githubusercontent.com/4328800/104452697-5aebcb80-5571-11eb-8abe-1a41d111d2fa.png)

As I mentioned in the previous issue, this happens when you're probably closing an old terminal or consolidating different terminal to create a new one. This means you have to stop what you're doing, move your hand to the mouse, close the notification, and then go back to what you were doing, which can interrupt your workflow/train of thought, when you probably already knew/don't care the the terminal had a non-zero exit code (that's an assumption that I make for myself, maybe other people need that for some reason).

VS Code gives the ability to map a shortcut to close all notifications, e.g.:

```
    {
        "key": "shift+escape",
        "command": "notifications.clearAll",
    },
```
 but it does not work when using the terminal. For the aforementioned reasons, I think it would be beneficial to add this to the whitelisted commands available for the terminal.

**Comment by Tyriar** [comment]
The keybinding should work if you add `notifications.clearAll` to the `terminal.integrated.commandsToSkipShell` setting.

If you don't care about the warning though, there's a setting to suppress that one, I think unless it exited with a code immediately after launching:

```
"terminal.integrated.showExitAlert": false
```
