### ISSUE TITLE
Python compilation errors cannot be jumped to if the path has spaces in it

### ISSUE THREAD

**Issue by crebzh** [microsoft/vscode#114287]
Issue Type: <b>Bug</b>

My python file is on my OneDrive, which has spaces in it. That means when when I have a python syntax error, VisualCode will not allow me to click on the compilation error to jump to the right line number when the syntax error has been detected

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.76GB free)|
|Process Argv|--crash-reporter-id 1198425e-e0f7-4092-b949-564db116f606|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
vscode-yaml|red|0.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30241727
vsjup459:30237187

```

</details>

We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by sbatten** [comment]
@crebzh please start by filing an issue with the Python extension: https://github.com/Microsoft/vscode-python/issues
