### ISSUE TITLE
When you search for $ in file it actually matches with empty spaces.

### ISSUE THREAD

**Issue by anilrathod04** [microsoft/vscode#114202]
Issue Type: <b>Bug</b>

When you search for "$" in file it actually matches with empty spaces.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Maybe you have set the "Use Regular Expression" toggle:
![image](https://user-images.githubusercontent.com/6726799/104312710-e3656000-54ce-11eb-94b4-d50a0d4e4770.png)
