### ISSUE TITLE
"command 'selectAll' not found" error when hitting "Ctrl+A" (win10)

### ISSUE THREAD

**Issue by gtzures** [microsoft/vscode#114256]
The `Ctrl+A` keybinding is assigned to the `selectAll` command, but when I hit it I get this error.
I have no overlapping `Ctrl+A` bindings.

**Comment by rebornix** [comment]
Can you check if you are assigning the keybinding to `editor.action.selectAll` ?

**Comment by gtzures** [comment]
@rebornix yes, I am:
![image](https://user-images.githubusercontent.com/57182897/104838529-23a85200-58c4-11eb-896c-ecab16c79204.png)

**Comment by asbjornu** [comment]
I'm experiencing this for both built-in commands and extensions.

### Paste

```
command 'markdown.extension.editing.paste' not found
```

<img width="534" alt="image" src="https://user-images.githubusercontent.com/12283/104918983-da283780-5995-11eb-88d8-5779103d3d9d.png" alt="command 'markdown.extension.editing.paste' not found">

### Rewrap extension

```
Command 'Rewrap Comment / Text' resulted in an error (command 'rewrap.rewrapComment' not found)
```

<img width="535" alt="image" src="https://user-images.githubusercontent.com/12283/104919121-0774e580-5996-11eb-865e-cf22257fd545.png" alt="Command 'Rewrap Comment / Text' resulted in an error (command 'rewrap.rewrapComment' not found)">


If I install the extensions in the latest Insiders build of VS Code, I'm unable to reproduce the problem. My environment:

```
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by gtzures** [comment]
@vscode-triage-bot, @rebornix, the problem still exists.
Here are all the commands with "Ctrl + A" binding:
![image](https://user-images.githubusercontent.com/57182897/114176537-f22fa780-9943-11eb-8bb0-1fbdc41c23fd.png)

My environment:
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by LizDW** [comment]
I'm experiencing the same issue after updating VSCode.

VSCode version: 1.55.2
OS: Microsoft Windows 10 Home 10.0.19041 Build 19041 

I found another person who suggested changing the keybindings for 'Save All" from `ctrl+a ctrl+s` to something not starting with `ctrl+a` but that did nothing for me.

**Comment by LizDW** [comment]
@rebornix Any ideas on how I can fix this issue?

**Comment by rebornix** [comment]
@LizDW can you run "Toggle Keyboard Shortcut Troubleshooting" command and then try ctrl+a and share the log you see?
