### ISSUE TITLE
Paths to internal pseudofiles are incorrectly rendered as OS paths

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#114234]
1. `node ./resources/web/code-web.js`
2. open settings.json
3. search for text in the file
![image](https://user-images.githubusercontent.com/8586769/104388675-811c5780-54ee-11eb-8be7-c212556fb04f.png)

notice the label claims this file is in `~/User/settings.json` on MacOS, or `\\User\settings.json` on Windows. This is misleading, as those are real OS path formattings, but the file itself does not live there (I believe its really at vscode-userdata:///User/settings.json`)

we should instead label these like `User/settings.json (internal)` or something.

ref #112775

**Comment by gjsjohnmurray** [comment]
Is it possible to fix this by simply registering a resource label formatter for the vscode-user data scheme?

**Comment by JacksonKearl** [comment]
Yeah, that's what I'd expect.

**Comment by JacksonKearl** [comment]
Or rather modify the existing one,

https://github.com/microsoft/vscode/blob/67f9988bdc476e99eedd50ae083ec3d90eb38604/src/vs/workbench/contrib/remote/common/remote.contribution.ts#L45-L48

cc @isidorn for thoughts on changing this to be more clear that these aren't real paths.

**Comment by isidorn** [comment]
@JacksonKearl thanks for providing a PR, let's continue the discussion there
Assigning this to January since I think we can tackle this week.
