### ISSUE TITLE
LabelService#hasDriveLetter seems wrong

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114203]
There is a method `hasDriveLetter` in `labelService` that a) seems wrong (shouldn't `path[2]` be `path[1]`?) and b) duplicates existing methods in `extpath` (that I just added):

https://github.com/microsoft/vscode/blob/675638196d27275f1daf688a2a4a71e70f68cd78/src/vs/base/common/extpath.ts#L287-L287

**Comment by isidorn** [comment]
Thanks for creating this, I guess I will just start using your method.

**Comment by alexdima** [comment]
Had to push a revert because tests on Windows were failing e.g. https://github.com/microsoft/vscode/runs/1704072398:
```
1) URI Label
       file scheme:

      AssertionError [ERR_ASSERTION]: '\\C:\\testWorkspace\\a\\b\\c\\d' == 'C:\\testWorkspace\\a\\b\\c\\d'
      + expected - actual

      -\C:\testWorkspace\a\b\c\d
      +C:\testWorkspace\a\b\c\d
      
      at Context.<anonymous> (file:///D:/a/vscode/vscode/out/vs/workbench/services/label/test/electron-browser/label.test.js:25:20)

```

**Comment by isidorn** [comment]
@alexdima sorry about that, I just ran the tests on macOS.
Thanks for reverting
