### ISSUE TITLE
No extension installed for 'test' debugging -- in Windows only, works in Linux

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#1142]
I'm developing a debugger extension that works fine in Linux (VSCode 0.10.1), but when I try to install in Windows (VSCode 0.10.3), it isn't recognized.

I've boiled down this simple test debugger in this zipfile: http://onetacoshort.com/temp/test_debug_extension.zip

In its `package.json` it contributes debugger of type `test`. It also includes a sample project with accompanying `launch.json`.

On linux, if I unzip this in my `~/.vscode/extensions` and try to debug the included sample project, it fails expectedly with "Debug adapter process has terminated unexpected". Of course it has, it's fake, but at least it gets invoked.

On windows, if I unzip this in `%USERPROFILE%\.vscode\extensions` and try to debug the included sample project, the error is "No extension installed for 'test' debugging."

That's odd, because it shows as installed:

![image](https://cloud.githubusercontent.com/assets/2192439/11691484/66cd7bcc-9e58-11e5-9a28-6040a2e1b28b.png)

This is just a test, but my real debug adapter is suffering from the same problem. So what am I doing wrong?

**Comment by weinand** [comment]
@isidorn I could easily reproduce this but I have no idea why this behaves differently on Windows. Please investigate.

**Comment by isidorn** [comment]
@jcward great repro steps - thanks!
The issue is that we wrongly expect "win" not "windows" in `package.json`. So as a workaround please use "win" in your `package.json`. I understand this is not aligned with our docs so from now on we will support both "win" and "windows" to end the confussion - will push that in 5mins 😊

**Comment by jcward** [comment]
Excellent, it's working, thanks!
