### ISSUE TITLE
Option for opening Getting Started side-by-side with readme

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#114315]
To allow Getting Started to be presented as onboarding within a freshly opened project, the current UX idea is to open the Getting Started page in split view with the readme.

This could be a new entry for `workbench.startupEditor`.

To simplify further, this could be the behavior for the existing `gettingStarted` startupEditor option. The content already has `when` clauses to make the entries aware of workspace state.

Draft for heuristics:

- If _Getting Started_ was dismissed, don't show again
- If project has a readme, open it in split view with _Getting Started_
- Fallback back to show just _Getting Started_ when workspace is empty or doesn't have a readme

We will test the heuristics and the content with users and gather feedback to make sure this actually helps and delights, and doesn't cause frustration.

cc @JacksonKearl @misolori

**Comment by DivonilLiquid** [comment]
Hey admin, i have recently started with open source contributions , can you assign this task to me so that i can learn the process.

**Comment by misolori** [comment]
@DivonilLiquid please take a look at the issues labeled `good first issue` ([query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22))

**Comment by digitarald** [comment]
Superseeded by other discussions that decided to open readme by default in web environments.
