### ISSUE TITLE
Workspace Symbol should limit to 512 symbols. Makes no sense to pull in thousands of symbols the user never looks at.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#11432]

**Comment by dbaeumer** [comment]
Has to wait. Was busy with 2.0.3 adoption.

**Comment by mjbvz** [comment]
I don't think this limit exists any longer. Searching for `a` in the VSCode codebase for example, returns thousands of symbols which all seem to be displayed in the list

**Comment by mjbvz** [comment]
Whoops, I misread 512 as being a vscode limit

**Comment by mjbvz** [comment]
To verify:

1. Open file in VS code workspace
1. Wait for TS to finish init
1. Do workspace symbol search for `#a`

It should now return results more quickly since we don't pull in 16000+ items :)

**Comment by garyking** [comment]
But is VSC still pulling in symbols from files in `node_modules` dir? Since those are polluting the results. If they're still included, then all the legitimate results will be pushed out of the list, now...

**Comment by mjbvz** [comment]
It re-requests results as you type

**Comment by garyking** [comment]
Yeah I know, but sometimes I'm looking for a symbol in my project, with a
common name. And hundreds of results from node modules appears, and I can't
filter my results any further. I thought that's what this issue was trying
to address.
