### ISSUE TITLE
UI-Issue in Vscode Insider version - Clicking on More action icon on a cell activates the delete button and deletes the cell

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode#114311]
UI-Issue - Clicking on More action icon deletes the cell

![more-action-deletes](https://user-images.githubusercontent.com/12703975/104505779-70f99a80-560a-11eb-8968-d00c933871c1.gif)

But I can avoid it, by very carefully clicking on the very very bottom left corner of the icon. If the clicking is slightly towards the middle of the icon the cell gets deleted.

---

VS-Code version

```
Version: 1.53.0-insider
Commit: e17aea136d32fdb06d9b32184b04ccd36bb51e9c
Date: 2021-01-12T08:22:28.134Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Linux x64 5.8.0-36-generic
```

And I am using Ubuntu 20.04

**Comment by roblourens** [comment]
Sorry, I can't repro this, is it still an issue @rohan-paul?
