### ISSUE TITLE
SHIFT key gets unpressed after combination with button 3 even if I am pressing it. 

### ISSUE THREAD

**Issue by michaelmiscanuk** [microsoft/vscode#114351]
- VSCode Version:
Version: 1.53.0-insider (system setup)
Commit: 3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e
Date: 2021-01-11T05:14:06.672Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. PRES AND HOLD SHIFT KEY
2. TYPE 3, it will type #
3. TYPE 4, and it will type 4, INSTEAD OF $

Does this issue occur when all extensions are disabled?: Yes

Hi, this is very probably something on my side, but I am not able to figure out, why it can be unpressing..
Posting pictures when comparing with STABLE VS CODE, where it works fine.

Stable:
![image](https://user-images.githubusercontent.com/37830487/104587749-a8e2fb00-5667-11eb-9be2-552af1449242.png)

Insiders:
![image](https://user-images.githubusercontent.com/37830487/104587781-ba2c0780-5667-11eb-946e-d07c7ac5e46f.png)

**Comment by alexdima** [comment]
I have never seen this. Two things:
1. Did you configure your `keybindings.json`? Can you try to comment that completely.
2. Extensions can intercept typing. Does this reproduce when disabling all extensions?

**Comment by michaelmiscanuk** [comment]
I found the culprit. I had something set in the Key Manager. Thank you for help. Closing.
