### ISSUE TITLE
Color and File Icon Theme change when launching the Extension Development Host

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#114385]
- VSCode Version:Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:50.160Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT ia32 10.0.19042

Steps to Reproduce:

1. I do Launch Extension to run the Extension Development Host:
![image](https://user-images.githubusercontent.com/19859882/104672446-a64aca80-5694-11eb-9f8c-621c06afcd0d.png)

The host instance has it's theme and file icon theme changed every time. It's change to Abyss and Minimal Icons instead of Default Dark+ and icons disabled (see the screenshot).

This just started happening a few hours ago.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sean-mcmanus** [comment]
The issue doesn't repero with 1.53.0-insiders so maybe it's fixed?

**Comment by sbatten** [comment]
@sandy081 for awareness

**Comment by sean-mcmanus** [comment]
The bug stopped reproing. Not sure why or if it'll re-occur.

**Comment by sandy081** [comment]
I am closing it as it is not being repro. Please reopen it if you see again with steps.
