### ISSUE TITLE
RPM package lacks icon?

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11430]
Installed the Insiders RPM in CentOS and it seems to be lacking an icon:

![image](https://cloud.githubusercontent.com/assets/22350/18195965/f8a974e2-70ee-11e6-9a7a-095c76648f00.png)

![image](https://cloud.githubusercontent.com/assets/22350/18195968/fbaa00da-70ee-11e6-8aa8-a01aa324f7e1.png)

**Comment by Tyriar** [comment]
The spec file does have an icon now https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/code.spec.template#L10, this could also be related to not having appdata.xml. There's an effort to get us in the software center in Fedora so this should be covered there.
