### ISSUE TITLE
Panel contents overflow after toggling panel

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11434]
Show the panel, hide it using the sash, show it again.

Contents overflow:

![image](https://cloud.githubusercontent.com/assets/22350/18196752/ac198054-70f3-11e6-98c2-810f092eb938.png)

**Comment by isidorn** [comment]
@joaomoreno do you still see this? When you say show it again - how do you show the panel? I tried all combinations and could not repro.
Might have been fixed by 97ddcf6

**Comment by joaomoreno** [comment]
Can't repro no more
