### ISSUE TITLE
Feature Request: Optional Auto Collapse Folder after leaving preview

### ISSUE THREAD

**Issue by glekner** [microsoft/vscode#114308]
I find my self checking signatures of objects imports inside `node_modules`, and after leaving the preview view, `node_modules` remains expanded in the Explorer resulting in a cluttered Tree.
It would be fantastic to have an option to auto collapse a folder after leaving a review view of a file that is inside it.

----------------------

![image](https://user-images.githubusercontent.com/24938324/104505897-48af7300-55ed-11eb-99cc-4b16c3720a3f.png)

**Comment by gjsjohnmurray** [comment]
Did you try using the Peek options on the context menu instead of opening the target file in preview mode?
