### ISSUE TITLE
RPM package lacks shortcut in PATH

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11431]
Just installed the Insiders RPM package in CentOS and `code-insiders` wasn't placed on the `$PATH`:

```
➜  ~ sudo find / -name 'code-insiders'
find: ‘/run/user/1000/gvfs’: Permission denied
/usr/share/code-insiders
/usr/share/code-insiders/bin/code-insiders
/usr/share/code-insiders/code-insiders
➜  ~ which code-insiders
/usr/bin/which: no code-insiders in (/home/joao/.nvm/versions/node/v5.10.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/joao/bin)
```

**Comment by dbaeumer** [comment]
Looks like a regression

**Comment by Tyriar** [comment]
There is meant to be a symlink in `/usr/bin`, created here https://github.com/Microsoft/vscode/blob/master/resources/linux/rpm/code.spec.template#L33

@joaomoreno can you do a `ls /usr/bin | grep code`? I'll try repro when I get to the office

**Comment by Tyriar** [comment]
I managed to repro this when installing via the UI package manager but not when installing via the command line. Note that installing via the command line (`yum`) requires `sudo`

**Comment by Tyriar** [comment]
Taking it off August since this is not a regression, at least not in the past month.

**Comment by Tyriar** [comment]
To verifier, please verify using Fedora:

- Install rpm using software center
- Ensure `code`/`code-insiders` command shows up in the terminal
- Uninstall package
- Ensure `code`/`code-insiders` command is not available in terminal
- Install via command line (see [docs](https://code.visualstudio.com/docs/setup/linux))
- Ensure `code`/`code-insiders` command shows up in the terminal
