### ISSUE TITLE
can not start!

### ISSUE THREAD

**Issue by ksnyde** [microsoft/vscode#114312]
> OS: macOS BigSur
> Computer: iMac Pro - 14 processors, 128gb RAM

I tried to start vs-code (insiders) and the UI starts to load but then stops. The pull-down menus are responsive but the rest of UI is just grey boxes.

- I immediately removed the old executable and reinstalled but the problem remains. 
- I then started vs-code via the CLI and with the --user-data-dir and --extensions-dir parameters set to a clean set of dirs
- starting with CLI and these options works!
- This worked but unless I use these parameters every time it continues to fail in the same way!
- I have identified that the "extensions" live off of `~/.vs-code-insiders/extensions` so I have replaced the folder with a symbolic link
- I have zero idea where the "data" directory is but it would appear that this is causing the problems because even with the extensions symbolically linked the normal startup is borked

The documentation talks about these command line options but never about how to permanently change the location of the "extension" and "data" directories. I now can no longer use `vs-code` without running the cli to start it and then adding these CLI options! 

> 

CPUs | Intel(R) Xeon(R) W-2170B CPU @ 2.50GHz (28 x 2500)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 3, 3, 3
Memory (System) | 128.00GB (67.17GB free)
Process Argv | --user-data-dir /Users/ken/coding/vs-code/data --extensions-dir /Users/ken/coding/vs-code/extensions --crash-reporter-id 3f3eef0e-7e0c-4dc0-9fee-a3a1048f4692
Screen Reader | no
VM | 0%

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by ksnyde** [comment]
@bpasero I run into a problem in the first step ... it says to run: `code --crash-reporter-directory <absolute-path>` but this hits my question from above ... i have no idea what the "default" data directory is. When I start via the command line and force the data directory to a directory of my choosing things work it's when I don't do that that the problems occur.

Note, that this morning I vs-code told me there was an update to update to and when I updated it forgot about my CLI command line switches and restarted with the defaults (aka, crashed vs-code). Just so you can see what I see, here's a screen shot of the "dead on arrival" version of vs-code:

![image](https://user-images.githubusercontent.com/980757/104615898-8c7e9880-563e-11eb-9330-8530ba64f1f6.png)

> Note: this is it _fully loaded_ not "as it's loading"

**Comment by ksnyde** [comment]
I believe I can fairly easily create a "work around" if you could just tell me where this data directory on a Mac is supposed to reside. I can then -- just like I have for the extensions directory -- create a symbolic link to my controlled directory and it will work.

I have tried googling for the answer to this as well as digging around the vs-code config but I can't find it. Further I looked at the files in my _explicit_ data directory and did a full hard drive search for similarly named files hoping to find the mysteriously hidden default directory but to no luck there either.

> Note: i searched for `storage.json` and `settings.dat`; the only examples of these files found were within my explicit data directory but with the `settings.dat` I noted that there were two versions ... one in the root and one in the "Crashpad" directory.

![image](https://user-images.githubusercontent.com/980757/104617020-d156ff00-563f-11eb-975d-d7e83bef5f25.png)

**Comment by ksnyde** [comment]
Now, while I could not follow the directions in the link you sent me ... the intent was to produce `*.dmp` files. I do have `*.dmp` files in the explicit data directory's "Crashpad" directory (four of them). I will include them here but I do worry that they are actually a red herring ... when i _successfully_ start vs-code I am often writing VueJS code and there are a combination of extensions that seem (only in the past day or two) to crash the **Extension Host**. I suspect these are related to that issue and not to the larger matter at hand.

![image](https://user-images.githubusercontent.com/980757/104617818-c486db00-5640-11eb-8d62-e204b912ea6e.png)

[dump files.zip](https://github.com/microsoft/vscode/files/5815610/dump.files.zip)

**Comment by ksnyde** [comment]
Finally, looking further down the page that your link pointed me to I see the following for macOS:

![image](https://user-images.githubusercontent.com/980757/104618559-ba191100-5641-11eb-9781-2ebb8271c8d2.png)

I don't know if these docs are out of date or my system simply has no "User Reports" but I'm on the latest version of Big Sur and here's what I see:

![image](https://user-images.githubusercontent.com/980757/104618854-111ee600-5642-11eb-9ff6-b03e9e8e31bd.png)

While there is no user reports, I did look through what was there and found these issues yesterday from vs-code:

![image](https://user-images.githubusercontent.com/980757/104619762-1597ce80-5643-11eb-8d6b-9e2f0e624a6e.png)

I'm not expert at looking at this kind of info but my guess is that this is not related to issue only because I've seen many programs exceed the Mac's expected wakeups threashold.

**Comment by bpasero** [comment]
Yeah the `Console` is also a place where crashes are logged, great findings. This looks like a more generic crash so I leave it up to Deepak to triage further.

**Comment by ksnyde** [comment]
please let me know if I can provide anything else

**Comment by bpasero** [comment]
Is there any difference when you try with "Code Stable"  instead of insiders?

**Comment by ksnyde** [comment]
i do have it installed but rarely use it ... it starts  up fine but then it has it's own independent data directory I believe.

**Comment by bpasero** [comment]
Yeah to test that you could simply point stable to the insiders user data dir and extensions (maybe make a backup first).

Bottom line: we updated Electron in our insiders (to 11 from 9) so it could have an impact.

**Comment by ksnyde** [comment]
good to know ... my problem is that I do not understand where the _default_ data directory resides. One of my developers said they thought it was at `Library/Application Support/...` and I'm going to go looking for it there. Until I know this I am limited in my ability to debug. If you could confirm the directory location that would be super helpful.

**Comment by ksnyde** [comment]
Ok I believe I have found it at:

![image](https://user-images.githubusercontent.com/980757/104632124-17b55980-5652-11eb-8691-a64010ac367d.png)

and in the **Crashpad** directory I see this high-level structure:

![image](https://user-images.githubusercontent.com/980757/104632292-54815080-5652-11eb-95a3-918c88d0be61.png)

There are a LOT of dump files in the _completed_ folder but none in the other folders. Of these, most of these are too old to be relevant but there is one from two days ago. My problems really started yesterday though maybe there was something the day before that set me up for this problem (aka, the next time I restarted).

![image](https://user-images.githubusercontent.com/980757/104632575-c0fc4f80-5652-11eb-8018-e0e37c015f76.png)

If it helps, i've included this dump file here.

[0f2612cf-30e5-466f-9685-91297b432d15.dmp.zip](https://github.com/microsoft/vscode/files/5816275/0f2612cf-30e5-466f-9685-91297b432d15.dmp.zip)

**Comment by ksnyde** [comment]
Now that I have identified the default data directory I have sym linked it to a known location and have both **Code** and **Code - Insiders** pointing to the same locations. The _insiders_ now starts up correctly. As does the regular version of Code.

This solves -- or at least works around -- this main problem I have. Let me know if you'd like me to close this (or feel free to yourself if you prefer).

> Note: I have an entirely different issue which relates to extensions crashing (with almost no way to identify the source container) ... would LOVE to see these extensions isolated into their own containers so they can only crash themselves and the error reporting is much clearer.

**Comment by deepak1556** [comment]
```
Operating system: Mac OS X
                  11.1.0 20C69
CPU: amd64
     family 6 model 85 stepping 4
     28 CPUs

GPU: UNKNOWN

Crash reason:  0x00000000 / 0x00000000
Crash address: 0x7fff20321462
Process uptime: 1351 seconds

Thread 0 (crashed)
 0  libsystem_kernel.dylib!__pthread_kill + 0xa
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00007ffee809b5f8   rbx = 0x000000010f78be00
    rsi = 0x0000000000000006   rdi = 0x0000000000000307
    rbp = 0x00007ffee809b620   rsp = 0x00007ffee809b5f8
     r8 = 0x00000000000130a8    r9 = 0x00007fff889af0e8
    r10 = 0x000000010f78be00   r11 = 0x0000000000000246
    r12 = 0x0000000000000307   r13 = 0x000000010f30f610
    r14 = 0x0000000000000006   r15 = 0x0000000000000016
    rip = 0x00007fff20321462
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib!abort + 0x78
    rbp = 0x00007ffee809b660   rsp = 0x00007ffee809b630
    rip = 0x00007fff202a2720
    Found by: previous frame's frame pointer
 2  Electron Framework!node::Abort() [node_errors.cc : 238 + 0x5]
    rbp = 0x00007ffee809b680   rsp = 0x00007ffee809b670
    rip = 0x000000010a198d92
    Found by: previous frame's frame pointer
 3  Electron Framework!node::OnFatalError(char const*, char const*) [node_errors.cc : 425 + 0x5]
    rbp = 0x00007ffee809b700   rsp = 0x00007ffee809b690
    rip = 0x000000010a198f24
    Found by: previous frame's frame pointer
 4  Electron Framework!v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [api.cc : 516 + 0x5]
    rbp = 0x00007ffee809b720   rsp = 0x00007ffee809b710
    rip = 0x000000010b1e9183
    Found by: previous frame's frame pointer
 5  Electron Framework!v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [api.cc : 479 + 0xf]
    rbp = 0x00007ffee80a0170   rsp = 0x00007ffee809b730
    rip = 0x000000010b1e9113
    Found by: previous frame's frame pointer
 6  Electron Framework!v8::internal::Heap::FatalProcessOutOfMemory(char const*) [heap.cc : 5788 + 0xa]
    rbp = 0x00007ffee80a0180   rsp = 0x00007ffee80a0180
    rip = 0x000000010b2c0dc5
    Found by: previous frame's frame pointer
 7  Electron Framework!v8::internal::MarkCompactCollector::Evacuate() [mark-compact.cc : 3422 + 0xc]
    rbp = 0x00007ffee80a02d0   rsp = 0x00007ffee80a0190
    rip = 0x0000000108559aa0
    Found by: previous frame's frame pointer
 8  Electron Framework!v8::internal::MarkCompactCollector::CollectGarbage() [mark-compact.cc : 554 + 0x8]
    rbp = 0x00007ffee80a0310   rsp = 0x00007ffee80a02e0
    rip = 0x0000000108556e00
    Found by: previous frame's frame pointer
 9  Electron Framework!v8::internal::Heap::MarkCompact() [heap.cc : 2265 + 0x5]
    rbp = 0x00007ffee80a0370   rsp = 0x00007ffee80a0320
    rip = 0x0000000108536906
    Found by: previous frame's frame pointer
10  Electron Framework!v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [heap.cc : 2082 + 0x8]
    rbp = 0x00007ffee80a0480   rsp = 0x00007ffee80a0380
    rip = 0x0000000108533e86
    Found by: previous frame's frame pointer
11  Electron Framework!v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [heap.cc : 1603 + 0xb]
    rbp = 0x00007ffee80a0670   rsp = 0x00007ffee80a0490
    rip = 0x0000000108531acb
    Found by: previous frame's frame pointer
12  Electron Framework!v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [heap.cc : 5154 + 0x11]
    rbp = 0x00007ffee80a06b0   rsp = 0x00007ffee80a0680
    rip = 0x000000010853c72b
    Found by: previous frame's frame pointer
13  Electron Framework!v8::internal::Factory::NewMap(v8::internal::InstanceType, int, v8::internal::ElementsKind, int) [heap-inl.h : 305 + 0x17]
    rbp = 0x00007ffee80a06f0   rsp = 0x00007ffee80a06c0
    rip = 0x000000010851c81b
    Found by: previous frame's frame pointer
14  Electron Framework!v8::internal::Map::RawCopy(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, int, int) [map.cc : 1453 + 0xa]
    rbp = 0x00007ffee80a0730   rsp = 0x00007ffee80a0700
    rip = 0x000000010866b0c2
    Found by: previous frame's frame pointer
15  Electron Framework!v8::internal::Map::ShareDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*) [map.cc : 1654 + 0xb]
    rbp = 0x00007ffee80a0790   rsp = 0x00007ffee80a0740
    rip = 0x000000010866baa2
    Found by: previous frame's frame pointer
16  Electron Framework!v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [map.cc : 2381 + 0x11]
    rbp = 0x00007ffee80a0800   rsp = 0x00007ffee80a07a0
    rip = 0x00000001086674cf
    Found by: previous frame's frame pointer
17  Electron Framework!v8::internal::Map::CopyWithField(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [map.cc : 478 + 0xb]
    rbp = 0x00007ffee80a0890   rsp = 0x00007ffee80a0810
    rip = 0x0000000108667249
    Found by: previous frame's frame pointer
18  Electron Framework!v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::StoreOrigin) [map.cc : 2186 + 0x1c]
    rbp = 0x00007ffee80a09a0   rsp = 0x00007ffee80a08a0
    rip = 0x000000010866d352
    Found by: previous frame's frame pointer
19  Electron Framework!v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::StoreOrigin) [lookup.cc : 580 + 0x15]
    rbp = 0x00007ffee80a09f0   rsp = 0x00007ffee80a09b0
    rip = 0x000000010865fcea
    Found by: previous frame's frame pointer
20  Electron Framework!v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [ic.cc : 0 + 0x7]
    rbp = 0x00007ffee80a0a80   rsp = 0x00007ffee80a0a00
    rip = 0x00000001085b05cc
    Found by: previous frame's frame pointer
21  Electron Framework!v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [ic.cc : 1610 + 0x5]
    rbp = 0x00007ffee80a0ac0   rsp = 0x00007ffee80a0a90
    rip = 0x00000001085b1719
    Found by: previous frame's frame pointer
22  Electron Framework!v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin) [ic.cc : 1596 + 0xe]
    rbp = 0x00007ffee80a0b80   rsp = 0x00007ffee80a0ad0
    rip = 0x00000001085b11f4
    Found by: previous frame's frame pointer
23  Electron Framework!v8::internal::Runtime_StoreIC_Miss(int, unsigned long*, v8::internal::Isolate*) [ic.cc : 2502 + 0x17]
    rbp = 0x00007ffee80a0c40   rsp = 0x00007ffee80a0b90
    rip = 0x00000001085b53ef
    Found by: previous frame's frame pointer
24  Electron Framework!Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit + 0x38
    rbp = 0x00007ffee80a0c60   rsp = 0x00007ffee80a0c50
    rip = 0x0000000108a6c898
    Found by: previous frame's frame pointer
25  0x3d86007218bb
    rbp = 0x00007ffee80a0d00   rsp = 0x00007ffee80a0c70
    rip = 0x00003d86007218bb
    Found by: previous frame's frame pointer
26  0x3d8600506114
    rbp = 0x00007ffee80a0d70   rsp = 0x00007ffee80a0d10
    rip = 0x00003d8600506114
    Found by: previous frame's frame pointer
27  Electron Framework!construct_stub_create_deopt_addr + 0xa0
    rbp = 0x00007ffee80a0de0   rsp = 0x00007ffee80a0d80
    rip = 0x00000001089fb91a
    Found by: previous frame's frame pointer
28  0x3d860055c8e1
    rbp = 0x00007ffee80a0ed8   rsp = 0x00007ffee80a0df0
    rip = 0x00003d860055c8e1
    Found by: previous frame's frame pointer
29  Electron Framework!Builtins_AsyncFunctionAwaitResolveClosure + 0x41
    rbp = 0x00007ffee80a0f38   rsp = 0x00007ffee80a0ee8
    rip = 0x0000000108a2cb41
    Found by: previous frame's frame pointer
30  Electron Framework!Builtins_PromiseFulfillReactionJob + 0x3b
    rbp = 0x00007ffee80a0f70   rsp = 0x00007ffee80a0f48
    rip = 0x0000000108abc0bb
    Found by: previous frame's frame pointer
31  Electron Framework!Builtins_RunMicrotasks + 0x297
    rbp = 0x00007ffee80a0fd8   rsp = 0x00007ffee80a0f80
    rip = 0x0000000108a1ee57
    Found by: previous frame's frame pointer
32  Electron Framework!Builtins_JSRunMicrotasksEntry + 0x78
    rbp = 0x00007ffee80a1040   rsp = 0x00007ffee80a0fe8
    rip = 0x00000001089fc478
    Found by: previous frame's frame pointer
33  Electron Framework!v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [simulator.h : 142 + 0x5]
    rbp = 0x00007ffee80a11a0   rsp = 0x00007ffee80a1050
    rip = 0x00000001084df211
    Found by: previous frame's frame pointer
34  Electron Framework!v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [execution.cc : 428 + 0xb]
    rbp = 0x00007ffee80a1200   rsp = 0x00007ffee80a11b0
    rip = 0x00000001084dfb13
    Found by: previous frame's frame pointer
35  Electron Framework!v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [execution.cc : 505 + 0x8]
    rbp = 0x00007ffee80a1260   rsp = 0x00007ffee80a1210
    rip = 0x00000001084dfbf0
    Found by: previous frame's frame pointer
36  Electron Framework!v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [microtask-queue.cc : 165 + 0x8]
    rbp = 0x00007ffee80a1330   rsp = 0x00007ffee80a1270
    rip = 0x00000001084f513f
    Found by: previous frame's frame pointer
37  Electron Framework!v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [microtask-queue.cc : 117 + 0x5]
    rbp = 0x00007ffee80a1350   rsp = 0x00007ffee80a1340
    rip = 0x00000001084f4f40
    Found by: previous frame's frame pointer
38  Electron Framework!Builtins_CallApiCallback + 0xae
    rbp = 0x00007ffee80a1390   rsp = 0x00007ffee80a1360
    rip = 0x00000001089ff88e
    Found by: previous frame's frame pointer
39  0x3d86003ab7e5
    rbp = 0x00007ffee80a1420   rsp = 0x00007ffee80a13a0
    rip = 0x00003d86003ab7e5
    Found by: previous frame's frame pointer
40  Electron Framework!Builtins_JSEntryTrampoline + 0x5b
    rbp = 0x00007ffee80a1448   rsp = 0x00007ffee80a1430
    rip = 0x00000001089fc51b
    Found by: previous frame's frame pointer
41  Electron Framework!Builtins_JSEntry + 0x78
    rbp = 0x00007ffee80a14b0   rsp = 0x00007ffee80a1458
    rip = 0x00000001089fc2f8
    Found by: previous frame's frame pointer
42  Electron Framework!v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [simulator.h : 142 + 0xb]
    rbp = 0x00007ffee80a1610   rsp = 0x00007ffee80a14c0
    rip = 0x00000001084dec41
    Found by: previous frame's frame pointer
43  Electron Framework!v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [execution.cc : 462 + 0x8]
    rbp = 0x00007ffee80a1690   rsp = 0x00007ffee80a1620
    rip = 0x00000001084de95a
    Found by: previous frame's frame pointer
44  Electron Framework!v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [api.cc : 4994 + 0x16]
    rbp = 0x00007ffee80a17a0   rsp = 0x00007ffee80a16a0
    rip = 0x000000010846b0bc
    Found by: previous frame's frame pointer
45  Electron Framework!node::InternalCallbackScope::Close() [callback.cc : 144 + 0xa]
    rbp = 0x00007ffee80a1810   rsp = 0x00007ffee80a17b0
    rip = 0x000000010a113506
    Found by: previous frame's frame pointer
46  Electron Framework!node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [callback.cc : 197 + 0x8]
    rbp = 0x00007ffee80a1940   rsp = 0x00007ffee80a1820
    rip = 0x000000010a11391a
    Found by: previous frame's frame pointer
47  Electron Framework!node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [async_wrap.cc : 769 + 0x10]
    rbp = 0x00007ffee80a19a0   rsp = 0x00007ffee80a1950
    rip = 0x000000010a126b03
    Found by: previous frame's frame pointer
48  Electron Framework!node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [stream_base.cc : 346 + 0x10]
    rbp = 0x00007ffee80a19d0   rsp = 0x00007ffee80a19b0
    rip = 0x000000010a24b344
    Found by: previous frame's frame pointer
49  Electron Framework!node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [env-inl.h : 0 + 0x15]
    rbp = 0x00007ffee80a1a40   rsp = 0x00007ffee80a19e0
    rip = 0x000000010a24d161
    Found by: previous frame's frame pointer
50  Electron Framework!node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [stream_base-inl.h : 126 + 0xc]
    rbp = 0x00007ffee80a1ac0   rsp = 0x00007ffee80a1a50
    rip = 0x000000010a252020
    Found by: previous frame's frame pointer
51  Electron Framework!uv__stream_io [stream.c : 1239 + 0x13]
    rbp = 0x00007ffee80a1ca0   rsp = 0x00007ffee80a1ad0
    rip = 0x0000000107bb9488
    Found by: previous frame's frame pointer
52  Electron Framework!uv__io_poll [kqueue.c : 0 + 0x8]
    rbp = 0x00007ffee80a9d60   rsp = 0x00007ffee80a1cb0
    rip = 0x0000000107bc0ffc
    Found by: previous frame's frame pointer
53  Electron Framework!uv_run [core.c : 381 + 0x8]
    rbp = 0x00007ffee80a9dd0   rsp = 0x00007ffee80a9d70
    rip = 0x0000000107bafe97
    Found by: previous frame's frame pointer
54  Electron Framework!electron::NodeMain(int, char**) [node_main.cc : 264 + 0x7]
    rbp = 0x00007ffee80aa060   rsp = 0x00007ffee80a9de0
    rip = 0x0000000107d50c93
    Found by: previous frame's frame pointer
55  Electron Framework!ElectronInitializeICUandStartNode [electron_library_main.mm : 44 + 0xb]
    rbp = 0x00007ffee80aa170   rsp = 0x00007ffee80aa070
    rip = 0x0000000107bc1760
    Found by: previous frame's frame pointer
56  Code - Insiders Helper (Renderer)!main [electron_main.cc : 254 + 0xb]
    rbp = 0x00007ffee80aa240   rsp = 0x00007ffee80aa180
    rip = 0x0000000107b59657
    Found by: previous frame's frame pointer
57  libdyld.dylib!start + 0x1
    rbp = 0x00007ffee80aa258   rsp = 0x00007ffee80aa250
    rip = 0x00007fff2036a621
    Found by: previous frame's frame pointer
58  libdyld.dylib!start + 0x1
    rbp = 0x00007ffee80aa258   rsp = 0x00007ffee80aa258
    rip = 0x00007fff2036a621
    Found by: stack scanning
```

**Comment by deepak1556** [comment]
Crash due to OOM when reading a file on startup, this looks similar to the cache data issue we had for x64 and arm64 version.

@ksnyde can you try starting with `--no-cached-data` , also does the latest insiders repro the issue ?

**Comment by ksnyde** [comment]
Hi @deepak1556 , sorry just noticed your reply now. Will try but my old config is now gone so I'm not sure it'll be apples to apples. BTW, I'm assuming OOM stands for out of memory? I have 128gb of RAM and tons of fast (aka, SSD) disk cache. Seems like a surprising situation to find myself in. 

Note, with the new configuration I have been able to operate pretty much normally now. I think my personal issues are behind me (knock on wood) but I would like to be helpful if I can.

**Comment by deepak1556** [comment]
Closing for now, can revisit if the issue persists.
