### ISSUE TITLE
Option "Install Another Version..." is non-clickable for all installed extensions

### ISSUE THREAD

**Issue by RachelGuo76** [microsoft/vscode#114341]
**Browser:** Edge Beta\Dev, Chrome
**Operation System Information:** Win10 (18363.1316)

**Repro Steps:**

1. Open link https://github.com/codespaces
2. Create a codespace and connect to it.
3. Navigate to Extensions tab, select any installed extension, clicking setting icon.
Observe "Install Another Version..." option on opened dropdown.

**Expected:**
"Install Another Version" option is clickable. we are able to install previous extension version by it.

**Actual:**
"Install Another Version" option is gray, we are unable to use it.

GitHub Codespace Version: #1.0.3070
VS Code Version:
Version: 1.53.0-insider
Commit: c265dff48a27868c7f0f84fd25a169897dc43d73
Version: 1.52.1-Stable
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523

GIF show as below:
![nonclickable_InstallAnotherVersion](https://user-images.githubusercontent.com/67084699/104568512-279d5f80-568b-11eb-9cc2-e0de7817ef90.gif)

**Comment by susiwen8** [comment]
@sandy081 Hi, I have make a PR for this issue, could you take a look.

**Comment by RachelGuo76** [comment]
@susiwen8 I could repro this bug on PPE. This option of GitHub codespaces extension is non-clickable by default, and this option of other extension becomes non-clickable after refreshing web page.
![InstallAnotherVersion](https://user-images.githubusercontent.com/67084699/106422096-ec779a80-6498-11eb-822e-dd1ea7abccd0.gif)

**Comment by sandy081** [comment]
@susiwen8 **Install Another Version...** action is not supported for builtin extensions. Codespaces extension is builtin extension and hence this action is disabled.

**Comment by RachelGuo76** [comment]
Verify this bug on [Web](https://github.com/codespaces) , Install Another Version... action is disabled for GitHub codespaces extension, and it is enabled for other extensions which shows in Extensions: 'INSTALLED', so this bug is fixed now.
