### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by bala-rao-au9** [microsoft/vscode#114366]
Issue Type: <b>Bug</b>

when i am installing react packages or any packages its not installing

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core  CPU      E5700  @ 3.00GHz (2 x 2992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.75GB (1.59GB free)|
|Process Argv|--crash-reporter-id bd99a961-8a82-4020-af5a-9bce034cfb3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
live-server-preview|neg|0.1.4
LiveServer|rit|5.6.1

</details>

**Comment by sbatten** [comment]
see #114029
