### ISSUE TITLE
Ability to create custom Side bar Panels

### ISSUE THREAD

**Issue by sketchpunk** [Microsoft/vscode#1143]
Trying to create an FTP Extension but I need a way to be able to view the contents on the FTP server. A side bar panel would be great or at least the have access to the folder panel to create a virtual tree for the user to use for navigation.

**Comment by egamma** [comment]
Duplicate of #710

What you could consider is to use the quick box in similar way as it is used in the yeoman extension:
https://marketplace.visualstudio.com/items/samverschueren.yo
