### ISSUE TITLE
Getting Started rendering broken after Split Editor

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#114321]
Steps to Reproduce:

1. Open Getting Started after enabling the experimental pref
2. Right-click the tab and _split_ in any direction

Result:

Newly created tab is empty while content gets added to the old tab.

![image](https://user-images.githubusercontent.com/8599/104529843-7ed5fe00-55bf-11eb-8e04-133acd8bd354.png)

**Comment by JacksonKearl** [comment]
how bizarre
