### ISSUE TITLE
Cypress Verification Time out after 30000 milliseconds

### ISSUE THREAD

**Issue by tindiya** [microsoft/vscode#114349]
Issue Type: <b>Bug</b>

./node_modules/.bin/cypress open
PS C:\Users\Mathew Joy\CypressAutomation> ./node_modules/.bin/cypress open
It looks like this is your first time using Cypress: 6.2.1

  ×  Verifying Cypress can run C:\Users\Mathew Joy\AppData\Local\Cypress\Cache\6.2.1\Cypress
    → Cypress Version: 6.2.1
Cypress verification timed out.

This command failed with the following output:

C:\Users\Mathew Joy\AppData\Local\Cypress\Cache\6.2.1\Cypress\Cypress.exe --smoke-test --ping=394

----------

Command timed out after 30000 milliseconds: C:\Users\Mathew Joy\AppData\Local\Cypress\Cache\6.2.1\Cypress\Cypress.exe --smoke-test --ping=394     
Timed out

----------

Platform: win32 (10.0.18363)
Cypress Version: 6.2.1
PS C:\Users\Mathew Joy\CypressAutomation> VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-6410 APU with AMD Radeon R5 Graphics     (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.96GB (0.47GB free)|
|Process Argv|--crash-reporter-id cbc3a40f-642b-4916-9fd0-798152111214|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30244299
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
vstes627:30244334
pythonvspyt600cf:30241728

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you provide more info why this is an issue with VS Code editor itself?

**Comment by tindiya** [comment]
Dear Team,

I could not open cypress because of this error message. can yoou please
help me.

Tindiya
004915143604535

**Comment by IllusionMH** [comment]
/question

This is issue tracked for VS Code editor. Please ask question about issue not related to editor in corresponding places like SO (even then you would need to provide more info about your setup there)

**Comment by tindiya** [comment]
Dear All,

I have some problem with test runner after I changed the default command
time reset. Therefore, I tried to uninstall cypress from windows.
Unfortunately, it is not working. Could you please inform me how could I
uninstall from windows? I would like to install after that. Please help me
in this matter.

Thanks,

Tindiya

**Comment by SinghalAyushh** [comment]
To resolve this issue, you need to increase default timeout. For this, go to below path: node_modules\cypress\lib\tasks\verify.js

Open verify.js, search variable VERIFY_TEST_RUNNER_TIMEOUT_MS. By default it should be 30000. Change it to 100000.
