### ISSUE TITLE
Terminal does not scroll up

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11439]
- VSCode Version: latest insiders
- OS Version: OS X, zsh shell

Steps to Reproduce:

1. Open integrated terminal, have lots of output
2. Can not scroll up. Vertical scroll bar is not appearing, also tried the mouse well but can not scroll up

I also see this behavior in our stable VSCode build so not a regression

**Comment by isidorn** [comment]
Works nicely on win. The root cause is probably me using zsh shell

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/7817
