### ISSUE TITLE
Preserve tabs when opened intentionally

### ISSUE THREAD

**Issue by kamlekar** [Microsoft/vscode#11435]
- VSCode Version: 1.4.0
- OS Version:  Windows 8

Steps to Reproduce:

1.  <kbd>ctrl</kbd> + <kbd>p</kbd> 
2.  Type some file name
3.  Press <kbd>Enter</kbd>
4.  When above three steps did again, the previously opened file is disappearing.

VS Code should keep the file when user Intentionally opened it.  Currently, it is showing the file in italics (stating that the tab isn't preserved).

**Comment by Dragory** [comment]
Have you tried setting the `workbench.editor.enablePreviewFromQuickOpen` setting to `false`?

**Comment by kamlekar** [comment]
Thanks @Dragory it is working :)
