### ISSUE TITLE
Needs Improvement

### ISSUE THREAD

**Issue by another180** [microsoft/vscode#114324]
Issue Type: <b>Feature Request</b>

Can you move the Selection for LF and CRLF at least close to the button? It's a hassle to move the cursor from bottom to top just to change LF to CRLF. I am not sure if you have shortcuts for this.

It would also be great if there's a way to handle it for multiple documents.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.5.0

**Comment by sbatten** [comment]
the command is `workbench.action.editor.changeEOL` which you can add a keybinding for.

**Comment by rebornix** [comment]
Adding a keybinding to the action is a good solution.

**Comment by Thaina** [comment]
> the command is `workbench.action.editor.changeEOL` which you can add a keybinding for.

Can we have this command accept arguments "CRLF" and "LF" on the keybindings?
