### ISSUE TITLE
Watch: copy value should respect multi selection

### ISSUE THREAD

**Issue by illegal-instruction** [microsoft/vscode#114353]
During debugging there is the option to copy the value from a watch variable. VSCode by default allows to inspect arrays. I can select with shift click a range of values within the array and they are highlighted. Pressing 'copy value' however, will only copy the value of the array that the mouse is hovering. It could be nice that if several values are highlighted all those values are copied into the clipboard.

![image](https://user-images.githubusercontent.com/55837609/104589473-3889a900-566a-11eb-90fb-462ae4aaa9b4.png)

As a use case, I work with numerical methods and exporting those vector values to excel allows me to quickly validate that some operations are computed correctly, evolution of values during the solving phase, etc.

Moreover, from the point of view of UX, in my humil opinion, it makes more sense that if multiple values are highlighted, all of them are copied to the clipboard, separated by \n.

Just a small suggestion,
Thanks in advance, 
vscode is awesome

**Comment by isidorn** [comment]
@illegal-instruction this feature request makes sense.
I guess you would expect that each value is followed by a new line to distnguish between them?

This is doable, assigning to next milestone to look into it then.

**Comment by illegal-instruction** [comment]
@isidorn Yes, I suggested new line because it seems reasonable as it copy pastes well to excel and notepad and it resembles the structure you are 'seeing' in the screen.

**Comment by isidorn** [comment]
Adding help wanted in case somebody from the community wants to help here.

Code pointer 
https://github.com/microsoft/vscode/blob/7a9bb5a44f9fc0dc51535959f6f15f8dd3d037cd/src/vs/workbench/contrib/debug/browser/variablesView.ts#L397

The command should be changed that as arguments it gets an array of selected expressions. Might be a bit tricky for first time contributors to get 100% right.

**Comment by jeanp413** [comment]
I'll work on this
