### ISSUE TITLE
Move close 'x' on tabs to left side of name.

### ISSUE THREAD

**Issue by KevinHopps** [microsoft/vscode#114318]
Issue Type: <b>Feature Request</b>

Please move the 'x' for closing a tab to the left side of the name. Because the tabs are of varying width, closing several tabs to the right of a given tab requires moving the mouse and re-targeting the 'x' for each close. If the 'x' were on the left, it would be easy to click in rapid succession.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

**Comment by gjsjohnmurray** [comment]
A Google of "vscode tabs close left" gave  this as the first suggestion

https://stackoverflow.com/questions/50176249/how-can-i-make-vs-code-editor-tabs-close-on-left-side

**Comment by KevinHopps** [comment]
> A Google of "vscode tabs close left" gave this as the first suggestion
> 
> https://stackoverflow.com/questions/50176249/how-can-i-make-vs-code-editor-tabs-close-on-left-side

Woo hoo! Thanks.

**Comment by abelardolg** [comment]
Hi there,

I would prefer to move on top. 
You can unintentionally close any tabs by selecting them.

Best regards.
