### ISSUE TITLE
Source Control message field not always auto-focused

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#114367]
Issue Type: <b>Bug</b>

This started happening in a recent version of vscode; not sure which. It affects both git and svn.

Normal behavior:
1. Open a project under version control.
2. Hide the sidebar.
3. Make a change, save it, and close the file.
4. Click the Source Control tab or press the key combination to open it.
5. **The cursor is in the Message field**, so you can quickly type and commit.

Problem behavior:
1. Open a project under version control.
2. Hide the sidebar.
3. Make a change, save it, and **keep the file open**.
4. Click the Source Control tab or press the key combination to open it.
5. The open file is selected under Source Control, and **the cursor is not in the Message field**.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv|--crash-reporter-id ee98133f-4180-44b0-86f2-150582a5f918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
ng-template|Ang|0.1100.3
vscode-intelephense-client|bme|1.6.2
npm-intellisense|chr|1.3.1
mustache|daw|1.1.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-npm-script|eg2|0.3.13
vscode-powertools|ego|0.63.0
php-debug|fel|1.14.5
vscode-favorites|how|1.8.3
svn-scm|joh|2.13.5
vscode-apache|mrm|1.2.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
hexeditor|ms-|1.3.0
debugger-for-chrome|msj|4.12.11
copy-json-path|nid|0.1.0
gitpatch|par|0.2.1
java|red|0.73.0
vscode-yaml|red|0.14.0
slack|soz|0.0.14
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.16.0
vscode-java-pack|vsc|0.12.1
vscode-maven|vsc|0.27.1
sync-rsync|vsc|0.36.0
jinja|who|0.0.8

</details>

**Comment by jacobweber** [comment]
Actually I just found that scm.autoReveal=false turns this behavior off. So maybe this is a non-issue.

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/108073

**Comment by eamodio** [comment]
@joaomoreno isn't this by design with `scm.autoReveal` on?

**Comment by joaomoreno** [comment]
Yeah 👍
