### ISSUE TITLE
Make it easier for new users to save untitled files

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#114307]
We notice that beginners often get tripped up when they launch VS Code for the first time and create their new file. They are not sure how to run their file, because they often don't realize they have to save their file and save it as a particular file extension to get language support. From @burkeholland's user test, one idea that came up was to include the options to Save an untitled file from the right-click tab menu. Thoughts on also adding an option to "Choose language" from the right-click menu which would open up the language mode quick pick? 

![image](https://user-images.githubusercontent.com/9721254/104504493-8510ae00-55b0-11eb-8c87-dacac4793500.png)

**Comment by bpasero** [comment]
I wonder though: for someone that does not know the concept of untitled vs files, would it help to see a "Save" entry in the context menu? Wouldn't that require to know this concept to begin with?

I find the idea of having a new type of editor that saves automatically (like a scrapbook kind of thing) more interesting imho, but maybe we should have a UX discussion about this.

//cc @misolori

**Comment by burkeholland** [comment]
@bpasero I think you bring up the core point - which is that what the user is _really_ expecting is that the file is already saved for them. The fully abstracted file experience of phones has done this to our brains. I'm also interested in an experience where you can create a new file of a type and it just "is". And when you change it, it's just changed. 

That said, when beginners do try and save files as eventually they will, it seems like they will head for a the context menu. My kid is still doing it even though I've taught him about File/Save.

**Comment by bpasero** [comment]
Related scrapbook feature request from a while ago: https://github.com/microsoft/vscode/issues/44100

**Comment by misolori** [comment]
I don't mind adding a save action in the context menu, though I'm not sure if that will help for those that don't know you can right-click on tabs. I like the idea of a scrapbook concept, kinda like saving everything to a "untitled" workspace that the user never has to manage (like codepen).

Another idea, what if we showed a codelens that asked the user to choose a language mode on empty untitled files? Then we could prompt a save afterwards:

![image](https://user-images.githubusercontent.com/35271042/104872738-85d47780-5903-11eb-8782-d4c481addc5e.png)

**Comment by sana-ajani** [comment]
> Related scrapbook feature request from a while ago: #44100

I think having a temporarily saved "untitled" workspace would be greatly valuable, because I think many people expect that nowadays anyway. I compare this to the experience when creating a new file on Google Drive - when I create a blank Google Docs document, the file name is "untitled" until I've explicitly renamed it, but it is saved on my drive as "untitled" as well. We could save this for a duration of a session, and if the user adds code to this untitled file and tries to execute the code, then they will be prompted to save it because of https://github.com/microsoft/vscode/issues/111850.



> I don't mind adding a save action in the context menu, though I'm not sure if that will help for those that don't know you can right-click on tabs. I like the idea of a scrapbook concept, kinda like saving everything to a "untitled" workspace that the user never has to manage (like codepen).
> 
> Another idea, what if we showed a codelens that asked the user to choose a language mode on empty untitled files? Then we could prompt a save afterwards:
> 
> ![image](https://user-images.githubusercontent.com/35271042/104872738-85d47780-5903-11eb-8782-d4c481addc5e.png)

It's a good point about new users not realizing you can right click on a tab, though I would say the action of right clicking a tab might be more likely for these users than them going to File -> Save or realizing the keyboard shortcut for saving a file, so it could still be a worthwhile option to add. Perhaps we can try this as an experiment? And see which options for saving an untitled file is most common. cc @digitarald.

I also *really* like the codelens for the untitled file @misolori ! It's a simple instruction that can offer a lot of guidance, without being too annoying. Repl.it has a similar flow. You are first asked what kind of repl to create (python, node.js, java, etc) and asked to name it, then presented with an empty tab with this codelens. When you click on "examples", it opens up a modal with sample snippets of code to insert. 

![recording (4)](https://user-images.githubusercontent.com/9721254/106536658-e4ceea80-64c6-11eb-92fa-1eacd93aa1f0.gif)

Something like this in the editor to guide new users would be enormously helpful. Clicking on the "language" would open the language picker, and clicking on "save" could open the native save dialog. 

![image](https://user-images.githubusercontent.com/9721254/106537076-9e2dc000-64c7-11eb-8870-b1dc616b9b66.png)

**Comment by bpasero** [comment]
I feel this issue is still in the process of being figured out and does not provide a clear solution yet, so switching owners. I think this needs a UX champion that figures out the best solution and needs more discussion in the UX calls.

**Comment by bpasero** [comment]
@sana-ajani your original reasoning was:

> We notice that beginners often get tripped up when they launch VS Code for the first time and create their new file. They are not sure how to run their file, because they often don't realize they have to save their file and save it as a particular file extension to get language support.

But didn't we just fix this for `1.53` (@isidorn):

![image](https://user-images.githubusercontent.com/900690/106770778-93496b80-663e-11eb-833b-9b322e9df3ae.png)

I really think that is the right way to go because I think the intent of the user is to run a file, it is not necessarily to save it. Again, a new user may not understand the concept of a file or where to save it, so I like the fact that we just guide the user now whenever you try to run it.

**Comment by isidorn** [comment]
To also write this down (since we discussed in UX):
Setting `files.defaultLanguage` should have a better default. A default that would try to figure out what kind of file a user wants to create and based on it the untitled editor would have the correct type and thus user would not have to worry about saving the file...

Ideas how to correctly guess the `files.defaultLanguage`:
* Look at installed extensions
* Look at content of the workspace

@sana-ajani if you think this makes sense, feel free to assign this issue also to me and I can look into it from the engineering side this milestone. Thanks

**Comment by sana-ajani** [comment]
@isidorn sounds good! If we can add logic for detecting default file based on the majority of files in an open workspace, perhaps that is a new value we can add to the `files.defaultLanguage` setting.

**Comment by isidorn** [comment]
Pushed a first version of this to insiders to gather feedback
Next step: how to improve the `files.defaultLanguage` default value - how to detect the language the user wants.

![Screenshot 2021-02-17 at 20 02 48](https://user-images.githubusercontent.com/1926584/108255179-3381b300-715c-11eb-9480-d32fc55b0484.png)

**Comment by bpasero** [comment]
@isidorn implementation wise I wonder if there is a better way of adding the hint than listening for each editor opening and adding it. I feel this should be a code editor contribution like the "Open Workspace" button is, would you agree?

For example here is how we do that: https://github.com/microsoft/vscode/blob/a5b078b5514cbe30ba3b9447c44faf910ca98799/src/vs/workbench/browser/codeeditor.ts#L210-L210

I feel we could do something similar, do a real code editor contribution there to make it appear.

**Comment by isidorn** [comment]
@bpasero hey there. I was actually thinking about that, but some reasons why I decided to do it like a workbench contributions:
1) I only want to show it for the active editor, not for every editor
2) I was not 100% sure how to get `IEditorInput` from the `ICodeEditor`. I needed the IEditorInput to figure out if the ICodeEditor is Untitled

Though I can change to the IEditorContribution. Let me know what you think. Thanks!

**Comment by bpasero** [comment]
@isidorn you can use get the URI of the editor easily, see how we do it here:

https://github.com/microsoft/vscode/blob/a5b078b5514cbe30ba3b9447c44faf910ca98799/src/vs/workbench/browser/codeeditor.ts#L247-L254

You can just check for scheme being `untitled`.

**Comment by isidorn** [comment]
Great feedback from the zurich standup: use the blue floating button instead since:
* it is a ux pattern that we already have
* does not confuse users that they can not type
* might allign better with our future plans to detect language as user types

So I plan to move to using the blue button instead and after that try to use ML to auto detect language

**Comment by isidorn** [comment]
@bpasero changed it to be an editor contribution

After feedback here are the changes I pushed
1. For inline text we will render the keybinding in brackets to teach to user how to always do this
2. Added a setting workbench.editor.untitled.hint to be either text (default)` 'button' or 'hidden'. When we go to production the idea is to not have a setting for this. The setting is just that we can easily switch the approach for user testing
3. Added the button option
![Screenshot 2021-02-18 at 21 43 12](https://user-images.githubusercontent.com/1926584/108419378-baa15a80-7232-11eb-81d4-9059b342fdcf.png)


@stevencl it would be cool if you could run some user studies with insiders from tomorrow, just makes sure to set `"workbench.editor.untitled.hint": "button"`

![Screenshot 2021-02-18 at 21 42 55](https://user-images.githubusercontent.com/1926584/108419373-b9702d80-7232-11eb-843f-1b69ba754c15.png)

**Comment by isidorn** [comment]
After trying out the button I definitely think it is not too heavy. Quite the opposite my suspicion is that users will not see it. That is why it would be interesting to do a couple of user studies.

**Comment by misolori** [comment]
Like the direction this is going! Small knit: since this is aimed at newer users, not sure we should include the keyboard shortcut. While it is useful to know, it could add unnecessary complexity because it introduces "chord" keyboard shortcuts. Also, we don't have this for "Open Folder" on the explorer empty view.

**Comment by sana-ajani** [comment]
I still like the editor hint because it's more instructional and obvious, but I would be curious to see what users prefer. Depending on the feedback and if there is not an obvious preference, we could also run the button and the editor hint as an A/B experiment. Main metric of success being how many new users change their language mode and then install the recommended extension for the language they choose.

**Comment by isidorn** [comment]
Thanks for the feedback.
Here's some info from @stevencl who is running user studies 

![Screenshot 2021-02-19 at 14 19 15](https://user-images.githubusercontent.com/1926584/108509492-98085380-72bd-11eb-9aad-e843c17e4acb.png)

**Comment by isidorn** [comment]
Some more discussions, pasting here to have it all in one place

![Screenshot 2021-02-19 at 15 04 14](https://user-images.githubusercontent.com/1926584/108514125-c4bf6980-72c3-11eb-9a4e-8d35a4396211.png)

**Comment by isidorn** [comment]
Created this issue for next milestone for modal dialog recommendations https://github.com/microsoft/vscode/issues/117051

**Comment by isidorn** [comment]
We have done what we have planned for this milestone. I have also created a test plan item so we get feedback on our inital solution,
For stable release we just think what would be the default value for the setting, I would probably go with `hidden` and then next milestone release it in stable. Let me know what you think, for now pushing this to next milestone

**Comment by sana-ajani** [comment]
I think hidden is okay for this release! We can try this as an experiment in Insiders and see which options gets more engagement before the next release. (Personally, I also like the button on the bottom right a lot)

**Comment by isidorn** [comment]
I changed this to be hidden for this release. I will not mention it in the release notes.
Next milestone we will change the default and we can advertise it in release notes.

**Comment by isidorn** [comment]
I have changed it back to be `button` by default for insiders. Though we Insiders will have this change end of week (once we release the stable - which has the hint as hidden).

**Comment by isidorn** [comment]
We will be running an experiment with the two choices for the untitled hint.
I believe no further changes are planned for this milestone here, we are waiting for feedback on the Experiment. Thus moving to April.
I will change the default to be hidden again while we are waiting for results

@sana-ajani let me know if I should change something.

**Comment by pixieaka** [comment]
@isidorn The button hint not hidden after start typing like text hint.

**Comment by isidorn** [comment]
Yeah, that is expected for now. I planned not to change this yet

**Comment by isidorn** [comment]
For now we have decided to go with the inline text.
Closing this issue.
Feel free to open additional issues for furhter disucssions

@stevencl we have also polished the debug extension is not there, you can check out the details here https://github.com/microsoft/vscode/issues/119110#issuecomment-823263742

![Screenshot 2021-04-20 at 16 34 02](https://user-images.githubusercontent.com/1926584/115414339-39e0e980-a1f6-11eb-905a-0bb8b374c236.png)
