### ISSUE TITLE
Master branch missing from checkout UI

### ISSUE THREAD

**Issue by thupsi** [microsoft/vscode#114337]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro, build 19042.746

Steps to Reproduce:

1. Initialize repository
2. Create new branch
3. Checkout the new branch
4. Click on the new branch name on the status bar
5.  The master branch is missing from the checkout selection UI

![image](https://user-images.githubusercontent.com/19857599/104561163-a4aae380-564f-11eb-9d6f-5076bf6ec9bb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by thupsi** [comment]
Reading through the above mentioned links I seem to have experienced the same bug as https://github.com/microsoft/vscode/issues/112838

The only thing to clarify is that this happens on ALL new repos created with this version of VSCode (1.52.1)

**Comment by eamodio** [comment]
It's a duplicate and is fixed in the current insiders build.
