### ISSUE TITLE
Allow a silent "save before commit" option

### ISSUE THREAD

**Issue by babramczyk** [microsoft/vscode#114363]
**Proposed option**: Something like `git.saveBeforeCommit`, that saves any dirty files right before bringing the the commit message input for the `Git: Commit` action

**The rationale**

If you keep your files dirty sometimes, it'd be really nice to be able to just enter one keybinding and commit your progress, without having to save.

As-is, a lot of times you might forget to save, in which case you get a notification saying "there's no changes to commit" if it's the only file. In that case you need to clear the notification, save the file, and try again.

My current workaround is a custom task that does this. **This works because of a similar option, `task.saveBeforeRun`, does this same behavior**, just for tasks. It'd be nice to have the same thing for committing specifically (and other commit-related actions, like `Git: Commit (amend)`.

**Comment by eamodio** [comment]
This behavior exists today, although there was a bug with it that has been fixed in the latest insiders, see #104945. Are you not seeing that behavior?

**Comment by babramczyk** [comment]
Ah, yeah so maybe that bug was making it worse than it actually was. Now that that's fixed, it's not _too_ bad -- it's just one extra `Enter` press to confirm

Still, it would be nice to have a preference that, in the scenario where there's dirty editors when you're committing, it would always just `Save All and Commit` (and thus never show that dialog). For me at least, that's always the behavior I want, so it would be nice to take the extra modal confirmation step out of it
