### ISSUE TITLE
Uncrustify not shown in the extension marketplace

### ISSUE THREAD

**Issue by picatostas** [microsoft/vscode#114344]
VSCode Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
- OS Version: ubuntu 20.04 (5.8.0-36-generic)

Steps to Reproduce:

1.Open extension marketplace
2. Search for uncrustify
![Selection_006](https://user-images.githubusercontent.com/36212945/104576697-d3798780-5658-11eb-9281-b5246720c705.png)

Does this issue occur when all extensions are disabled?: No

**Comment by IllusionMH** [comment]
It was unpublished from Marketplace - see note in the header.
https://marketplace.visualstudio.com/items?itemName=LaurentTreguier.uncrustify

**Comment by picatostas** [comment]
Oh, thats sad
