### ISSUE TITLE
Cells stops to execute after drag&drop rearrangement

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114310]
@roma-glushko commented on [Wed Dec 23 2020](https://github.com/microsoft/vscode-jupyter/issues/4267)

## Environment data

-   VS Code version: 1.53.0-insider(4a875e23d20b64504a818834f3fa4c40adb8d480)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.429416775-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS Catalina 10.15.5 (19F101)
-   Python and/or Anaconda version: 3.9.1 64bit
-   Type of virtual environment used: venv (poetry env use python3)
-   Jupyter server running: Local
-  Pylance version: v2020.12.2

## Expected behaviour

I expect to be able to rerun cells again after drag-and-drop rearrangement

## Actual behaviour

After rearrangement of section with a few cells inside, I was not able to run those cells till I recreated all cells manually

## Steps to reproduce:

Notebook: https://github.com/roma-glushko/kaggle-wine-quality

![2020-12-23_17-48-42 (1)](https://user-images.githubusercontent.com/9402690/103014944-45721b80-4548-11eb-8057-70abf8ce3abe.gif)

Notice how run button ignores clicking on it after SVC section was rearranged

---

@claudiaregio commented on [Wed Dec 23 2020](https://github.com/microsoft/vscode-jupyter/issues/4267#issuecomment-750410972)

Thanks @roma-glushko , I am able to reproduce this issue. I'm also finding that after moving a section of cells the run appears to no longer be aligned with its cell, it runs a different cell. 

Steps to recreate gif: 
1. Create 2 sections and run all
2. Collapse second section and move above
3. Try running cells from first section -- either nothing happens, or it "appears" to run another cell while producing the output of the cell you're trying to run

**Notice when I run the second cell from the newly moved "Section 2" the execution count, cell execution count and the running icon change in the last cell from "Section 1". The output rendered is from the cell I am actually trying to run (output goes from "section 1" to "section 2"

![Moving Cells Run Not Aligned](https://user-images.githubusercontent.com/19276747/103024430-ae37a480-4504-11eb-8cad-82175dc305fa.gif)

Clearing the output and restarting the kernel does not resolve the location issue, cells are mismatched and output is produced in wrong spot. 

---

@roma-glushko commented on [Wed Dec 23 2020](https://github.com/microsoft/vscode-jupyter/issues/4267#issuecomment-750428818)

@claudiaregio yes, this is exactly what I see locally 👍 

---

@greazer commented on [Tue Jan 05 2021](https://github.com/microsoft/vscode-jupyter/issues/4267#issuecomment-754922108)

@claudiaregio to enter two separate bugs in the vscode issues. This wouldn't be our bug to fix. 

---

@DonJayamanne commented on [Tue Jan 12 2021](https://github.com/microsoft/vscode-jupyter/issues/4267#issuecomment-759026480)

Adding to parity as we cannot ship native notebooks with this bug.
Makes notebook unusable after such operations.

---

@claudiaregio commented on [Tue Jan 12 2021](https://github.com/microsoft/vscode-jupyter/issues/4267#issuecomment-759126672)

@DonJayamanne Do you have the ability to transfer this to vs code? Peng said he couldn't and recommended not splitting into two new issues until they can verify they're separate

**Comment by DonJayamanne** [comment]
@rebornix copied the issue, as I do not have rights to transfer the issue.

**Comment by roblourens** [comment]
It looks like the extension is sending edits with the wrong index. But, I will see whether this still reproes after the execution changes and debug some more if so.

**Comment by roblourens** [comment]
Can't repro this anymore, let me know if you still see it.
