### ISSUE TITLE
Could not read source map for file:///Users/owner/Code/project/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/Users/owner/Code/project/node_modules/typescript/lib/typescript.js.map'

### ISSUE THREAD

**Issue by liby** [microsoft/vscode#114395]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1. Open `index.ts`
2. Run / Start Debugging
3. Click "Continue"
4. DEBUG CONSOLE Output:
    > Could not read source map for file:///Users/owner/Code/project/node_modules/typescript/lib/typescript.js: ENOENT: no such file or directory, open '/Users/owner/Code/project/node_modules/typescript/lib/typescript.js.map'

https://user-images.githubusercontent.com/38807139/104704817-1704ec00-5754-11eb-92a2-c1aa63ffb3d7.mp4

Does this issue occur when all extensions are disabled?: Yes

### Other

<details>
<summary>launch.json</summary>

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch current file w/ ts-node",
      "protocol": "inspector",
      "args": ["${relativeFile}"],
      "cwd": "${workspaceRoot}",
      "runtimeArgs": ["-r", "ts-node/register"],
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}
```
</details>

**Comment by gilgameshskytrooper** [comment]
Bump

**Comment by connor4312** [comment]
/duplicate #109561

This is fixed if you use `type: "pwa-node"` instead of `"node"`. This will become the default in 1-2 iterations.
