### ISSUE TITLE
vscode.open for image file doesn't work when using virtual file system

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#114300]
From https://github.com/microsoft/vscode/issues/114054

- VSCode Version: 1.53.0-insider
- OS Version: macOS 11.1 

Steps to Reproduce:

Using a virtual file system, `vscode.open` works for text files but for images it displays this error:

![image](https://user-images.githubusercontent.com/22795803/104495876-20902780-558d-11eb-89d0-1ecbe26a4d2a.png)

`vscode.open` works as expected for local image files.

Does this issue occur when all extensions are disabled?: N/A

**Comment by mjbvz** [comment]
Please share a small extension that demonstrates this issue. You can build on the [fs-provider sample extension](https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample)

**Comment by wwlorey** [comment]
This ended up being a problem on my end. I was converting the image stream to a string before using that to create the buffer opened by `vscode.open`. It works if you just convert the stream to a buffer.
