### ISSUE TITLE
html.format.templating doesn't honor django (maybe nothing)

### ISSUE THREAD

**Issue by ZackPlauche** [microsoft/vscode#114390]
Issue Type: <b>Bug</b>

There's a setting in VSCode called "html.format.templating" with the description "honor django, erb, handlebars and php templating language tags."

I set this from false to true in settings and the result: nothing.

I have an html template with django tags just to test.

Expected result upon format: <div> tag should be indented.
```
<!DOCTYPE html> 
<html>
    <head>
     <head>
     <body>
          {% if x %}
              <div></div>
          {% endif %}
     </body>
</html>
```
What happens: nothing
```
<!DOCTYPE html> 
<html>
    <head>
     <head>
     <body>
          {% if x %}
          <div></div>
          {% else %}
     </body>
</html>
```

It treats it currently as if you were to type random text inside of a tag, but doesn't treat as a tag.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.37GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/zackp/Desktop/testfolder --crash-reporter-id 13b676ee-8fdb-465c-97b8-f48a69806915|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.0.3
gc-excelviewer|Gra|3.0.40
todo-tree|Gru|0.0.193
beautify|Hoo|1.5.0
rainbow-csv|mec|1.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
swdc-vscode|sof|2.3.24

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630

```

</details>

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying HTML formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

I don't expeted the formatter can understand what's in the templating tags. It just is able to ignore these without formatting them.
But the jsbeautify team would know better.
