### ISSUE TITLE
Unable to install extensions, "No extensions found"

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#114327]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-19T14:42:39.893Z
Electron: 9.4.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.85-1-MANJARO

**Steps to Reproduce / Scenario:**

1. Open marketplace
2. Search for "AssemblyScript" or other things.
3. No results.
4. Network tab in devtools shows the following response from https://open-vsx.org/vscode/gallery/extensionquery for the search for "AssemblyScript"
   ```json
   {
     "results": [
       {
         "extensions": [],
         "resultMetadata": [
           {
             "metadataType": "ResultCount",
             "metadataItems": [
               {
                 "name": "TotalCount",
                 "count": 0
               }
             ]
           }
         ]
       }
     ]
   }
   ``` 
   for the following request headers:
   ```
   POST /vscode/gallery/extensionquery HTTP/1.1
   Host: open-vsx.org
   Connection: keep-alive
   Content-Length: 241
   X-Market-User-Id: 95c50457-d6cd-4e88-93c1-387daceceb24
   Accept: application/json;api-version=3.0-preview.1
   User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) code-oss/1.52.1 Chrome/83.0.4103.122 Electron/9.4.0 Safari/537.36
   X-Market-Client-Id: VSCode 1.52.1
   Content-Type: application/json
   Sec-Fetch-Site: cross-site
   Sec-Fetch-Mode: cors
   Sec-Fetch-Dest: empty
   Accept-Encoding: gzip, deflate, br
   Accept-Language: en-US
   Cookie: d0a4a538d980f7aceac422c85ff6b50a=910ad2ff466f6c4ee94a4156b2b3b730
   ```

![no-extensions](https://user-images.githubusercontent.com/297678/104542742-f82e1a80-55d8-11eb-894b-6036f70128f0.png)

**Comment by gjsjohnmurray** [comment]
Manjaro's build of VS Code uses the Open VSX Registry instead of the Microsoft Marketplace.

https://open-vsx.org/?search=AssemblyScript&category=&sortBy=relevance&sortOrder=desc currently returns no matches.

**Comment by trusktr** [comment]
Oh, I see. Thanks!

Not too long ago, I thought I recalled having seen more extensions that I no longer see.

Anywho, as a workaround, I have my user config folder synced to a git repo, so I can add things on another machine with a different OS then pull it over.
