### ISSUE TITLE
Responsive design for narrow display of Getting Started

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#114322]
Getting Started's current CSS is not responsive enough to work on smaller screens:

![recording](https://user-images.githubusercontent.com/8599/104530176-4125a500-55c0-11eb-835b-91eac9c64e58.gif)

The following mockups are from @misolori to fit the content into a split tab or sidebar:

1. Cover image moved to top of the list:

<img width=400 src="https://user-images.githubusercontent.com/8599/104530289-7df19c00-55c0-11eb-9ec6-265bc3ee584a.png">

2. No cover image for minimal sidebar mode:

<img width=400 src="https://user-images.githubusercontent.com/8599/104517754-783d8b80-55ab-11eb-9d59-674486e4f060.png">

@misolori apart from what I shared from your prior work, any other ideas that we could consider for a narrow responsive design?

**Comment by digitarald** [comment]
Talking to @misolori for UX review, pushing the cover image on top of the list seems the current UX preference. CSS Grid named areas could help.

**Comment by JacksonKearl** [comment]
Agree the current narrow view isn't great, one concern with this version is it might be hard to operate a larger listing of items. For instance if you had 5 items and a screen both short and narrow it would probably be hard to operate the scrolling list, especially as things expand/contract. 

To that end one idea I had was maybe using a carousel for the items when in narrow mode?

**Comment by digitarald** [comment]
Even on the current layout some items are pushed below the fold, so not sure if that would be a trade off for a narrow viewport layout. With a CSS Grid layout the image could scale down further to a min height to make room for the list.

**Comment by misolori** [comment]
As long as the list area is scrollable, I think allowing for content to go below the fold would be fine. We could even add some gradients to the bottom to make it appear more obvious that there is more content below. 

I also like the carousel idea, which we've mocked up in the past

**Comment by JacksonKearl** [comment]
Using the power of ✨grid✨:
![image](https://user-images.githubusercontent.com/8586769/114256297-3be0b800-996d-11eb-853e-9796501f3d68.png)
![image](https://user-images.githubusercontent.com/8586769/114256302-43a05c80-996d-11eb-9243-2f7aa5064cb4.png)

Still some odd looking aspect ratios but overall not too shabby. We can address specifics in new issues.
