### ISSUE TITLE
Test: breakpoint conditions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#114345]
Refs: https://github.com/microsoft/vscode/issues/3646 https://github.com/microsoft/vscode/issues/113805 https://github.com/microsoft/vscode/issues/104453

- [x] anyOS @TylerLeonhardt
- [ ] anyOS @rzhao271

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114345%0A%0A)

---

We have made changes to the breakpoints view. Have a javascript project, for example our [smoke test express app](https://github.com/microsoft/vscode-smoketest-express). Add some breakpoints in a file, add some function breakpoints (click `+` in the Breakpoints view title) and verify:
* You can edit the condition of regular breakpoints, exception breakpoints and function breakpoints by clicking on the inline `Edit` icon
* You can use the Context Menu action to also edit the condition and hit condition of Exception Breakpoints and Function Breakpoints
* Once a breakpoints has a condition it is nicely rendered in the breakpoints view and can be seen on hover (note that for regular breakpoints we only show condition on hover, since there is not enough space - we render the breakpoint `path`)

If you start on this testplan before endgame begins, make sure to use [js-debug-nightly](https://github.com/microsoft/vscode-js-debug/#nightly-extension)

**Comment by connor4312** [comment]
Sure, we can use this for validating the js-debug implementation as well.

**Comment by connor4312** [comment]
@TylerLeonhardt / @rzhao271 use [mock debug](https://github.com/microsoft/vscode-mock-debug) to test function breakpoints. js-debug does not support function breakpoints/

**Comment by rzhao271** [comment]
Not sure how to hit the function breakpoints for Mock Debug on markdown files, but editing the breakpoint while running the markdown file lgtm.
