### ISSUE TITLE
Git merge conflict not detecting

### ISSUE THREAD

**Issue by Bhardvaj** [microsoft/vscode#114397]
Issue Type: <b>Bug</b>

1) Create a merge conflict between two branches.
2) Try to merge two branches (With git bash or with VScode).
3)Open the conflicted file. there will not be any conflict and will not show any merge conflict UI.

If, try to use command form command pallet. Visual Studio will give an error that "Editor cursor is not within a merge conflict" but you can see that in side-panel vscode is showing that there are merge changes.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.75GB free)|
|Process Argv|--crash-reporter-id 2b2a8bc7-b3a6-494c-9ff7-ddf0c2827971|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.1.3
vscode-html-css|ecm|1.8.1
prettier-vscode|esb|5.8.0
auto-rename-tag|for|0.1.6
template-string-converter|meg|0.4.7
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30241727

```

</details>

itten the needed data into your clipboard because it was too large to send. Please paste.

**Comment by eamodio** [comment]
I can't reproduce this. Does this happen with all merge conflicts? Or only with very large conflicts? Is there anything more you can provide to shed more light on what you are seeing?

**Comment by Bhardvaj** [comment]
Yes, this happens with all type of conflicts no matter large or small.
I tried with completely new repository also, same issue.
And also i tried disabling all extensions in case if any extension is interfering with merge conflict extension which is in built in vscode.
I also checked my settings.json file overriden properties but everything was fine just merge conflict is not working.

**Comment by Bhardvaj** [comment]
![Branches in repo](https://user-images.githubusercontent.com/35463557/104796488-b968b200-57dc-11eb-92af-378e1fa7d160.png)

**Here I created a demo repository and created one bugfix branch.**
.
.
**Both branches have only one file 'file.txt'.**

![File in master branch](https://user-images.githubusercontent.com/35463557/104796529-f9c83000-57dc-11eb-9924-77b6ae66f408.png)
![File in bugfix branch](https://user-images.githubusercontent.com/35463557/104796531-fd5bb700-57dc-11eb-8bfb-c223cdaf785f.png)
Only line number 2 in 'file.txt' is different between the two branches.
.
.
**When I try to merge the bugfix branch to the master branch it gives an error that we have to solve the conflict.**

![Conflict in terminal](https://user-images.githubusercontent.com/35463557/104796595-7f4be000-57dd-11eb-8aa4-73b02715e96f.png)
Now git is in merge state in the terminal and has conflict in the 'file.txt' file. This is true if I try to merge branches with vscode.
.
.
**In vscode side panel it shows that we are in a merge state and conflict in 'file.txt' but in the file, it doesn't show any merge conflict but clearly, we have a conflict on the second line of this file.**

![Conflict in vscode](https://user-images.githubusercontent.com/35463557/104796641-0a2cda80-57de-11eb-8b14-088cdfc0563b.png)
And if I try to use the command palette and use the option to merge. it shows an error that "Editor cursor is not within a merge conflict".
![use command palette for merge](https://user-images.githubusercontent.com/35463557/104796681-7c9dba80-57de-11eb-8785-9bd61cebfe93.png)

**Comment by hanzlahabib** [comment]
i have also reported the same issue, i face this issue only when there is big merge, or it may occur based on different factors which don't know
https://github.com/microsoft/vscode/issues/115286

**Comment by crispinkoech** [comment]
Facing this issue too.

**Comment by randym127** [comment]
Facing the same issue, reverting to an older version of VS code

**Comment by randym127** [comment]
FYI, I downgraded to 1.51.1 and it works again.

**Comment by crispinkoech** [comment]
Yeah, I had to do the same too @randym127

**Comment by eamodio** [comment]
Does this still happen with 1.53?

**Comment by Bhardvaj** [comment]
> Does this still happen with 1.53?

Yes, the bug is still there. 😟😟

**Comment by Bhardvaj** [comment]
This is issue still present in version 1.55.2. with the same step as I have given above. For, me this doesn't only happen for big merge but also happens for the small one-line merge too.
