### ISSUE TITLE
git source control: even if the code has not changed, the commit Input will be displayed

### ISSUE THREAD

**Issue by cnwyx** [microsoft/vscode#114396]
VSCode Version:1.53.0-insider
OS Version:Windows_NT x64 10.0.21292
Does this issue occur when all extensions are disabled?: Yes

It was normal before yesterday(if have changes: visible ,else hidden)
The VSCode-insider was updated twice in the past two days
The same after disabling all extensions and clear user settings

Is this my problem?

![image](https://user-images.githubusercontent.com/18470410/104707308-318c9480-5757-11eb-9ed1-bdda0affd0a3.png)

**Comment by eamodio** [comment]
This was an intentional change, because removing the input when there aren't any changes blocks the ability to reword (via Commit Amend) the last commit, or even add a message to an empty commit.

**Comment by cnwyx** [comment]
@eamodio 
Understandable!
If you can add a setting option...that would be happy  :smile:

**Comment by kgns** [comment]
An option to be able to use this as it was before would be really great. if we need to commit amend or add a message to an empty commit, we can enable it. More often than not we only need that text input for new non-empty commits, and every repo having a visible text input just makes it harder to see actual changes when used with large number of repos (10 would be a good example size)
