### ISSUE TITLE
Vscode doesn't show a editor area, sidebar and doesn't work any keyboard shortcut

### ISSUE THREAD

**Issue by zbandhan** [microsoft/vscode#114335]
- VSCode Version: 1.52.1
- OS Version: Deepin 20.1

Steps to Reproduce: I think this is happening after installing node 15.5.1 but I'm not sure though. Because removing node from global path doesn't solve the issue.
![image](https://user-images.githubusercontent.com/10957285/104559158-2dd11300-566e-11eb-8513-5a1d7bfac95b.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sbatten** [comment]
please try a fresh data dir by using the following command line to launch `code --user-data-dir ~/Desktop/tmpdir`

**Comment by zbandhan** [comment]
@sbatten Fresh data dir takes me back to the Editor but whenever I'm trying to open a specific project of mine in the sidebar, the problem's coming back. No other project is making this problem but the specific one. And if the problematic project is opened after the non-problematic one then the issue will not appear.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by zbandhan** [comment]
@bpasero I got this log. But I can't reproduce the issue now that's gone suddenly. Don't know why and how came and go.

[20532:0125/124117.684269:ERROR:browser_main_loop.cc(271)] GLib-GObject: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
(code:20532): Gtk-WARNING **: 12:41:17.718: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
[20564:0125/124117.824694:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[main 2021-01-25T06:41:17.877Z] Sending env to running instance...
[main 2021-01-25T06:41:17.958Z] Sent env to running instance. Terminating...
[main 2021-01-25T06:41:17.959Z] Lifecycle#kill()

**Comment by bpasero** [comment]
Ok let's close it then, the log is not revealing much.
