### ISSUE TITLE
"enablement" and "when" clause in viewsWelcome debug view not updating/loading correctly

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode#114304]
Issue Type: <b>Bug</b>

I'm trying to add buttons to the Run & Debug panel in vscode depending on if you have a compatible file opened or not, however the buttons do not seem to enable consistently.

package.json:
```json
"contributes": {
    "viewsWelcome": [
        {
            "view": "debug",
            "contents": "[Run File with RDMD](command:code-d.rdmdCurrent)",
            "enablement": "resourceLangId == d"
        }
    ]
}
```

I also tried using `debugStartLanguage` however that actually never worked with `d` as language, even though I do provide breakpoints in the package.json for it and there is a debugger for it in another extension.

The buttons seem to _sometimes_ be enabled but after a fresh load it's not. Opening a new file to the side and selecting it makes it enabled then.

![bug happening](https://wfr.moe/f6JOey.png)

VS Code version: Code - OSS 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-19T14:42:39.893Z)
OS version: Linux x64 5.10.3-zen1-1-zen

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2194)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|31.35GB (2.65GB free)|
|Process Argv|served-workspaced.code-workspace --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by isidorn** [comment]
@WebFreak001 I can somewhat reproduce this. 
@joaomoreno is there something needed for the Welcome view to be aware of what context keys it needs to watch out for? I would expect this just works?

Here's my snippet for which I can reproduce this

```
viewsRegistry.registerViewWelcomeContent(WelcomeView.ID, {
	content: 'HELLO THERE',
	group: ViewContentGroups.Debug,
	when: ResourceContextKey.LangId.isEqualTo('javascript')
})
```

**Comment by joaomoreno** [comment]
> is there something needed for the Welcome view to be aware of what context keys it needs to watch out for?

It watches out for the ones listed in the `when`.

> but after a fresh load it's not

@isidorn Not sure who owns `ResourceContextKey.LangId`, but it sounds like it isn't being properly set on startup?

**Comment by isidorn** [comment]
@joaomoreno you are off the hook the issue is that this context key is set by the explorer, so if the explorer is hidden this does not really work.

@WebFreak001 `resourceLangId` is a context that is valid only while the explorer is shown.
Please use `editorLangId` instead. That is what you need

**Comment by WebFreak001** [comment]
`editorLangId` doesn't seem to work at all, the button never got enabled with `"enablement": "editorLangId == d"`

**Comment by isidorn** [comment]
Yeah after double checking that context will only be set only inside the editor.
So what you want is a new context key, which would be `activeEditorLangId`. Unforutnetnly we do not seem to have this built in (I might be mistaken, so you can search our source dode).
I believe your extension can introduce a new context key, and set it when active editor changes based on the editor language.
