### ISSUE TITLE
Extension host crash with extension ssh workspace folder on RHEL 6

### ISSUE THREAD

**Issue by scriptninja** [microsoft/vscode#114362]
Issue Type: <b>Bug</b>

1. Install 1.53 Insider (my tests have been in portable mode)
1. Install either kelvin.sshfs or liximomo.remotefs 
1. Configure an SSH connection to a RHEL 6 host
1. Add connection as workspace folder (crash may occur before this step with liximomo)

VS Code version: Code - Insiders 1.53.0-insider (c265dff48a27868c7f0f84fd25a169897dc43d73, 2021-01-14T06:31:42.082Z)
OS version: Windows_NT x64 10.0.21292

Also reported SchoofsKelvin/vscode-sshfs#225 but at least at the time, he was unable to reproduce the crash, which I am guessing - since I only just discovered this was relevant - is because he was not trying to connect to a RHEL 6 host. As I mentioned in the other issue, I just discovered that the crash doesn't seem to happen when connecting to RHEL 7.3.

Both extensions work fine with the same connection configurations on 1.52.0-insider (dbbf7079b20b3036b3ff5ac2e2106b84dd3c6d66, 2020-12-10T17:20:40.435Z). 

The crash _seems_ to happen - I think - during the check for various potential configuration files in the workspace folder (.vscode, .git, .devcontainer, etc.), but I don't know whether those are causing it or if the timing might be coincidental.

I looked into using the official Remote SSH extension instead, but it doesn't seem to allow a remote workspace folder in the current session rather than the remote session taking over, and isn't compatible with the hosts I need to connect to anyhow.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (13.94GB free)|
|Process Argv|--crash-reporter-id 8b95c023-eb1f-4528-9f8a-1680eaf9da0e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sshfs|Kel|1.19.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
vstes627:30244334
pythonvspyt859:30241729
core-portspanelcf:30233468

```

</details>

**Comment by alexdima** [comment]
@scriptninja Please continue the troubleshooting with @SchoofsKelvin via https://github.com/SchoofsKelvin/vscode-sshfs/issues/225 . IMHO the crash of the extension host is caused (directly or indirectly) by something the extension is doing. I am happy to jump back into troubleshooting once we figure out that this is a crash caused by vscode core itself.

**Comment by SchoofsKelvin** [comment]
With the stable release of 1.53.0, this issue seems to have returned with multiple reports: SchoofsKelvin/vscode-sshfs#239. This also seems to be affecting users of a similar extension: liximomo/vscode-sftp#881.

I've [noticed](https://github.com/SchoofsKelvin/vscode-sshfs/issues/239#issuecomment-774234196) that there have been several internal version changes regarding OpenSSL/Electron/NodeJS, which might be part of the cause.

**Comment by scriptninja** [comment]
Thanks to the efforts of people who understand node and electron better than I, it seems we've traced this as far as electron/electron#27673
Telling the server you're connecting to not to use Diffie-Hellman seems like it may not be possible for a lot of people, which I have the impression means their options are limited to staying on 1.52 until a fix both lands in Electron and gets pulled into vscode, or doing without the affected extensions. At any rate I thought it might be useful to connect this issue to that one.

**Comment by SchoofsKelvin** [comment]
I've quickly tested this in 1.54.0-insiders (3290f9a) and it seems like e4a082a did indeed fix it. I was able to use the affected `diffie-hellman-group-exchange-sha256` without problem.
