### ISSUE TITLE
界面模糊

### ISSUE THREAD

**Issue by GUJUNNIAN** [microsoft/vscode#114343]
Issue Type: <b>Bug</b>

打开编辑一会就会出现界面模糊现象

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.21GB free)|
|Process Argv|--crash-reporter-id 15822082-ba19-4786-bc92-eae33ab568ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gltf-vscode|ces|2.3.1
githistory|don|0.6.14
gitlens|eam|11.0.6
prettier-vscode|esb|5.8.0
beautify|Hoo|1.5.0
vue|jcb|0.1.5
vscode-language-pack-zh-hans|MS-|1.51.2
debugger-for-chrome|msj|4.12.11
git-commit-plugin|red|1.0.0
vscode-preview-server|yui|1.3.0

</details>

**Comment by GUJUNNIAN** [comment]
![image](https://user-images.githubusercontent.com/30283164/104572944-47368700-568f-11eb-90d9-e70b8985ea00.png)

**Comment by jianboli** [comment]
Issue Type: Bug

The interface becomes blurry after starting editing a little while.  

VS Code version: Code 1.51.1 (e5a624b, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

**Comment by deepak1556** [comment]
Is the issue present with insiders https://code.visualstudio.com/insiders ?
