### ISSUE TITLE
Can't drag and drop to move or open files after windows update KB4592438

### ISSUE THREAD

**Issue by wnzhyee** [microsoft/vscode#114392]
- VSCode Version: 1.52.1
- OS Version: windows10 KB4592438(updated at 20210115)

Steps to Reproduce:

We meet this problem today(2021.1.15) on 3 different pc, and the same thing we have done is update windows10 automantically this morning, and the update version is KB4592438. Now i have tried to reinstall vscode and fallback windows, but it seems not work.

Does this issue occur when all extensions are disabled?: Yes/**No**

**Comment by bpasero** [comment]
Is it possible you run VSCode as admin or different user and it happens?

**Comment by wnzhyee** [comment]
> Is it possible you run VSCode as admin or different user and it happens?

no, i check the code.exe , and i don't use the "open as admin" config, and the problem is not frag files from other windows to vscode, even drag inside vscode is not worked...

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by yaoshawn** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

We have tried the insider version and it doesn't work either. 
The specific windows update caused the problem for me is actually kb4598242. After the update, the open tabs in vscode are fixed and can't be dragged and moved left or right. We can not drag to open files from remote explorer at side bar either.

**Comment by bpasero** [comment]
This sounds like an upstream issue to me, nothing VSCode can fix. Related KB: https://support.microsoft.com/en-us/help/4598242/windows-10-update-kb4598242
