### ISSUE TITLE
Wrong warning while the output path is outside the extension folder.

### ISSUE THREAD

**Issue by vchirikov** [microsoft/vscode#114371]
Hi.
I have a project structure like this:

```yml
c:\code\⬛⬛⬛\vscode-extension  # root of the workspace/reporoot
c:\code\⬛⬛⬛\vscode-extension\src\extension # root of the vscode extension
c:\code\⬛⬛⬛\vscode-extension\artifacts\extension # output of webpack
```

my configs:

c:\code\⬛⬛⬛\vscode-extension\src\extension\tsconfig.json:
```js
{
// ...
  "outDir": "../../artifacts/obj/extension/tsc/",
}
```
c:\code\⬛⬛⬛\vscode-extension\src\extension\package.json:
```js
{
// ...
"main": "../../artifacts/extension/extension.js",
}
```

And I've got warning like this:

```
[c:\code\⬛⬛⬛\vscode-extension\src\extension\]: Expected `main` (c:\code\⬛⬛⬛\vscode-extension\artifacts\extension\extension.js) to be included inside extension's folder (c:\code\⬛⬛⬛\vscode-extension\src\extension\). This might make the extension non-portable.
```

As you can see the main is not included inside extension's folder.

The problem is here:

https://github.com/microsoft/vscode/blob/e2458c2d70552806aa834c87019cb2a70735a183/src/vs/workbench/services/extensions/node/extensionPoints.ts#L407-L409

**Comment by alexdima** [comment]
@vchirikov In a vscode extension, the `package.json` must be situated at the root of the extension. That is why resources referenced from `package.json` must be in the same folder as `package.json`. Please see https://code.visualstudio.com/api/get-started/extension-anatomy#extension-file-structure

**Comment by vchirikov** [comment]
@alexdima
I made repro for this issue. This is not a question and `package.json` is placed at the root of the extension. I've made a repro for you, please check it.
https://github.com/vchirikov/vscode-bug-repro

**Comment by alexdima** [comment]
@vchirikov What you desire is not possible. `package.json` must be at the root of the extension. It is not allowed to point to files outside of the extension folder. I have pointed you to documentation which clearly explains this. There are also `yo` generators that we maintain that you can use to scaffold a valid vscode extension.

**Comment by vchirikov** [comment]
> package.json must be at the root of the extension

It is. I only changed the output path to the upper directory.

>I have pointed you to documentation which clearly explains this

Let's check the docs:

> main: The extension entry point.

no, it is not "clearly explains" that `main` should points ONLY in a subfolder of the extension's source root (where `package.json` is placed and where `--extensionDevelopmentPath` points).
moreover, everything works fine, only this annoying warning appears.

**Comment by alexdima** [comment]
@vchirikov That warning is there to help you when you try to package the extension and presumably publish it to the marketplace. As part of packaging for the marketplace, only the extension folder is packaged and any other files on your hard disk will not be packaged. Such a package (which references missing files) will not work correctly. So the warning is there to let you know that although this works, this is not a good idea because the extension will not be portable.

**Comment by vchirikov** [comment]
Yep, `vsce` doesn't work when the artifacts output folder is higher than `package.json`.
