### ISSUE TITLE
"Variable ${workspaceFolder} can not be resolved. Please open a folder." when you run a task 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#114381]
- VSCode Version:
- OS Version:

### Steps to Reproduce:

Have an extension with the following
```ts
	const shellExec = new vscode.ShellExecution('ls',
	{
		executable: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', // or '/bin/bash'
		shellArgs: [ '-c' ]
	});

	const task = new vscode.Task(
		{ type: 'get-help' },
		vscode.TaskScope.Global,
		'Get help online',
		'Test HyperLink',
		shellExec);

        vscode.tasks.executeTask(task);
```

### Expected:

The task executes properly

### Actual:

"Variable ${workspaceFolder} can not be resolved. Please open a folder." Error notification

### Workaround:

If you add:

```
cwd: os.homedir()
```

to the options of `vscode.ShellExecution` it works as expected.

### Proposal

The default value of `cwd` should fall back to `os.homedir()` if `workspaceFolder` does not resolve.

Does this issue occur when all extensions are disabled?: N/A

**Comment by alexr00** [comment]
Seems reasonable.

**Comment by noviicee** [comment]
Is anyone working on this one or it is available..? @sana-ajani

**Comment by alexr00** [comment]
You're welcome to work on it @noviicee. The change should be made in the terminal task system, even though the error comes from the configuration resolver service. The change should be specific to the cwd not being resolved to the workspace folder. 

Please let me know if you need any code pointers!

**Comment by noviicee** [comment]
Thanks @alexr00. If you can point me to the code then that will be great!!

**Comment by alexr00** [comment]
@noviicee I think you should be able to check for the exception in `resolveOptions`
https://github.com/microsoft/vscode/blob/0d0a8f1aac4c24ebde2b217a99fb60c42f47734e/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1614-L1615

Then, if the exception is thrown you can use the path service to get the home directory, similar to here
https://github.com/microsoft/vscode/blob/0d0a8f1aac4c24ebde2b217a99fb60c42f47734e/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1093-L1094

**Comment by noviicee** [comment]
> @noviicee I think you should be able to check for the exception in `resolveOptions`
> https://github.com/microsoft/vscode/blob/0d0a8f1aac4c24ebde2b217a99fb60c42f47734e/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1614-L1615
> 
> Then, if the exception is thrown you can use the path service to get the home directory, similar to here
> https://github.com/microsoft/vscode/blob/0d0a8f1aac4c24ebde2b217a99fb60c42f47734e/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1093-L1094

Basically, what I have estimated is that If we don't have a cwd, then the terminal uses the home dir. So I need to add the path service to get the home directory for the exception in `resolveOptions`

**Comment by noviicee** [comment]
Basically, what I have estimated is that If we don't have a cwd, then the terminal uses the home dir. So I need to add the path service to get the home directory for the exception in `resolveOptions`

**Comment by noviicee** [comment]
Hey @alexr00 `await this.pathService.userHome()` returns type `URI` but in the *exception* in *resolveOptions*, the `cwd` is of the type `string`
Any help on fixing that..?

**Comment by TylerLeonhardt** [comment]
@noviiee here's a hint...there should be a property on the URI object you get back that turns the URI into a string.

**Comment by alexr00** [comment]
Tasks that know how to deal with a workspace folder could easily deal poorly with the user home dir (maybe the task does enumerates all files in the cwd for example. You probably don't want that happening in the user's home dir).
