### ISSUE TITLE
Save All - keyboard shortcut should use VS binding

### ISSUE THREAD

**Issue by shammelburg** [Microsoft/vscode#11433]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Visual Studio (IDE) has the Save All keyboard shortcut of (Ctrl+Shift+S), the same shortcut is available in code but it actions the Save As... function.

Can you apply the same to VS Code? I use both daily, like many other developers.

It would be nice to keep the same functionality between both Microsoft products.

**Comment by bpasero** [comment]
@shammelburg keybindings can be changed via settings. The current keybinding was inspired from Sublime and Atom and has been like this from day one. 

Marking as UX issue.

**Comment by chrmarti** [comment]
The main problem is that there is no keybinding by default, yet we propagate a UX where refactorings and global replace open all affected files, apply the changes and leave the editors dirty. In that situation I often want to use Save All and I think we should provide a keybinding by default. What about using the same as Atom/Sublime use: Alt+Cmd+S?

**Comment by shammelburg** [comment]
@chrmarti I think that'll be great. Having this feature as a default keybinding would help a lot.
