### ISSUE TITLE
"Reopen editor with" leaves duplicate tab open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#114306]
- Open readme.md, opens in markdown notebook
- "Reopen editor with" > Text editor
- Now there are two readme.md tabs open, and clicking the second only reopens the first

![image](https://user-images.githubusercontent.com/323878/104505039-31926600-5598-11eb-9811-6d556cf9af8d.png)

**Comment by mjbvz** [comment]
Duplicate of #111474
