### ISSUE TITLE
CPP: Grammar test fixture takes too long to parse

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#114411]
The following CPP grammar test fixture takes over 10 seconds on my beefy machine to run the test:

```
vscode-cpp/test/colorize-fixtures/test-92369.cpp
```

Here's the mocha output:

```
    ✓ test-92369.cpp (10159ms)
```

Even when I open that file in VS Code I see it freezing for a short bit. The file is quite small tho, so it makes me think something is really broken in the tokenizer and it must be looping wayyyy too much.

```cpp
std::tuple_element<0, std::pair<pugi::xml_node, std::map<std::basic_string<char>, pugi::xml_node, std::less<std::basic_string<char> >, std::allocator<std::pair<const std::basic_string<char>, pugi::xml_node> > > > >::type dnode

std::_Rb_tree_iterator<std::pair<const long, std::pair<pugi::xml_node, std::map<std::basic_string<char>, pugi::xml_node, std::less<std::basic_string<char> >, std::allocator<std::pair<const std::basic_string<char>, pugi::xml_node> > > > > > dnode_it = dnodes_.find(uid.position)
```

cc @alexdima

**Comment by joaomoreno** [comment]
Please wait before fixing this, as I'm in the process of extracting grammar extensions.

**Comment by joaomoreno** [comment]
Notice it here on GA: https://github.com/microsoft/vscode-cpp/runs/1708544581?check_suite_focus=true#step:5:40

**Comment by alexr00** [comment]
@jeff-hykin FYI (though I think you already know about this one).

We have this test to make sure that a bug where all of VS Code freezes doesn't happen.

**Comment by jeff-hykin** [comment]
Yeah, sadly for a line that long with that much nesting, the only thing we could do is set a line limit and ignore it. But that is already a built in feature/user-option.

**Comment by alexr00** [comment]
Thanks for confirming. Since the test is actually moving into an extension specific repo, I'd like to leave it in despite how long it is.
