### ISSUE TITLE
Python interpeter is not loding

### ISSUE THREAD

**Issue by Riju007** [microsoft/vscode#114472]
Issue Type: <b>Bug</b>

Though I am selecting correct interpeter vs code is not loding the interpeter. I am usnig windows10 32-bit operating system(Desktop).
FYI:
One thing I want to mention for my 64 bit sytem(Laptop) it working perfectly.
I have installed latest version in both the machine

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:50.160Z)
OS version: Windows_NT ia32 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.41GB (0.56GB free)|
|Process Argv|--crash-reporter-id 2c9d8983-ee4a-45d7-b2f6-ad9895b1f024|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.1
jupyter|ms-|2020.12.414227025
autodocstring|njp|0.5.4
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt600cf:30241728

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
