### ISSUE TITLE
Conflict of vscode node definitions with @types/node

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11447]
While developing extension, some modules may require node definitions they install it as dependency in `@types/node`

But then there appear many errors of duplicate indentifier:
![image](https://cloud.githubusercontent.com/assets/736697/18201847/f139c6f8-7125-11e6-8db4-f0993526f4a0.png)

If to remove `@types/node` those modules that require it, error that can not find definitions:

![image](https://cloud.githubusercontent.com/assets/736697/18201797/961527e0-7125-11e6-9ead-d894a033d4ab.png)

It is possible to resolve the conflict?

**Comment by bpasero** [comment]
This issue was moved to Microsoft/vscode-extension-vscode#33

**Comment by whitecolor** [comment]
I've updated 
```
npm i install vscode@latest --save-dev
```

And after that it can not find vscode module
![image](https://cloud.githubusercontent.com/assets/736697/18878823/8589b9a2-84eb-11e6-9171-1ca71ec2df2e.png)

What else should have to be done?

**Comment by bpasero** [comment]
@whitecolor I suggest you compare how a freshly generated extension looks like:
* `npm install -g generator-code`
* `yo code`
* pick ts
* check package.json and compare with yours

**Comment by bpasero** [comment]
Btw all you need is `vscode: ^1.0.0`
