### ISSUE TITLE
Turn off [js] linter

### ISSUE THREAD

**Issue by nie-xin** [Microsoft/vscode#11443]
I only installed eslint plugin as linter, but for some js files I noticed there are some [js] error prompts as following:

![capture d ecran 2016-09-02 a 12 13 00](https://cloud.githubusercontent.com/assets/3535692/18200836/12faee62-7107-11e6-848d-65b8e2c61a53.png)

I just want to know what this linter is and how to turn it off (I didn't install anything related, and prompts form eslint will start with [eslint])

**Comment by dbaeumer** [comment]
It is the build-in JavaScript support. you can turn it of via `javascript.validate.enable= false` setting
