### ISSUE TITLE
New File better flow for beginners

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#114423]
Experiment with the New File flow to make this easier for new users to create a file they want (example python file)
Maybe introduce some submenu actions to make it easier to create new files.

My idea is to leave the Cmd + N action unchanged.
But change how the main menu, and welcome view new file action behave.
Will experiment next milestone with this, thus assigning to February.

fyi @sana-ajani @digitarald @bpasero

**Comment by sana-ajani** [comment]
What are you thinking for this? Adding a new submenu for "New File"? Something like this? 

![image](https://user-images.githubusercontent.com/9721254/106770371-e81fbe80-660b-11eb-97c3-ce981cf57c5f.png)

**Comment by bpasero** [comment]
@sana-ajani that doesn't scale does it? And we need API for extensions to contribute this, no? Maybe a "New File..." that brings up a picker to select from would be better?

**Comment by isidorn** [comment]
I would suggest to first focus on https://github.com/microsoft/vscode/issues/114307
If we get that thing 100% right this one might not be needed. And the only remaining thing would be how to do it for custom editors, and Daniel already has an issue for that.

**Comment by isidorn** [comment]
No plans to change this. Closing
