### ISSUE TITLE
[BUG] VSCode filesystem cache on launch halts UI operations

### ISSUE THREAD

**Issue by zeuschops** [microsoft/vscode#114451]
- VSCode Version: 1.52.1 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a directory with at least 1 million files
2. Relaunch VSCode

Does this issue occur when all extensions are disabled?: Yes

The issue is that VSCode caches the entire most recent working directory into memory after the GUI is launched. Upon doing so the IDE becomes completely unresponsive while the filesystem is cached. This is significantly more noticeable the more files you have in your working folder. At 1+ million files, you then see 2GB of RAM and the complete UI halt become a bit of an issue.

**Comment by bpasero** [comment]
@zeuschops you are not opening 1 million files in the editor but just see them in the explorer and that makes the UI stop?

You can always from the command line ask VSCode to open a different folder and then you should be good.

**Comment by zeuschops** [comment]
That is correct, the file explorer seems to be halting the UI. I physically just moved the folder and had already combined the files down to one CSV so I did get it sorted out, but it's still just noting the it down about (what I think is) a buffer issue.

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by zeuschops** [comment]
Removed the project name and replaced it with [project-name]. The project name is alphabetical with hyphens, all lower case - for what it's worth. This was captured with peak CPU usage from VSCode. This has only the first-party Python extension and Jupyter extension running. I can rerun this without those running as well if needed.

I also did startup profiling, the reference functionName that fills up the majority of the log is "(program)", assuming I'm correlating the ids correctly.
```
Version:          Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS Version:       Windows_NT x64 10.0.19042
CPUs:             Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)
Memory (System):  15.86GB (7.25GB free)
VM:               0%
Screen Reader:    no
Process Argv:     C:/Users/zeusc/Desktop --crash-reporter-id a8d02479-2fc8-4bf6-8ec0-49075240d2b7
GPU Status:       2d_canvas:                  enabled
                  flash_3d:                   enabled
                  flash_stage3d:              enabled
                  flash_stage3d_baseline:     enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       86    3732  code main
    0       86    5728     shared-process
    0       24    6832     crashpad-handler
    0       37    7368     utility
   14      411   15748     window (metadata-to-csv.py - [project-name] - Visual Studio Code)
    0      185    9340       extensionHost
    0       12   13752       watcherService
    0       11     532         console-window-host (Windows internal process)
    0       70   16156       searchService
    8        7   17836         "c:\Users\zeusc\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/*.ipynb -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store --no-ignore --follow --no-config --no-ignore-global
    0       11    6108           console-window-host (Windows internal process)
    1       86   16248     gpu-process

Workspace Stats:
|  Window (metadata-to-csv.py - [project-name] - Visual Studio Code)
|    Folder ([project-name]): more than 1032536 files
|      File types: json(19987) py(5) txt(2) lisp(1) csv(1) gz(1)
|      Conf files:
```

**Comment by isidorn** [comment]
@zeuschops this profile does not really catch anything fishy. None of the processes are taking more than 14% cpu...
Can you 
1) Reproduce the issue with vscode insiders https://code.visualstudio.com/insiders/
2) Upload a repository with 1 million files to GitHub for which you can reproduce this problem. That way I can just clone that repository and try to repro on my machine

**Comment by zeuschops** [comment]
Apologies for the delay, I haven't gotten a chance to reproduce the issue with VSCode insiders, but the tar.gz file I expanded the over 1 million files from can be found here - [donk.sh/metadata.tar.gz](https://donk.sh/metadata.tar.gz).

**Comment by isidorn** [comment]
@zeuschops the link does not work for me. Though it would be best if you first try to repro with VS Code insiders. Thanks

**Comment by zeuschops** [comment]
Finally got some time available to test this on VSCode Insiders. Yeah, the Insiders build responds with "The window is no longer responding" about halfway through loading the data (I can only assume it's halfway as it was about 2GB of data and the read speed was under 100MB/s for close to 30 seconds thereabout).

Even after relaunching VSCode and attempting the repro steps, the issue occurs again. However, VSCode completely fails to respond on a second attempt while attempting repro steps.

Restating them;
- Open VSCode with a project that has a sub directory with over 1 million files
- Wait for the initial UI to load
- Attempt to open sub directory, then use the navigation menus to do anything (ex. Attempt to find out what's available in the Terminal/Help menus)
- VSCode hangs, attempts to load the files, eventually gives up and responds with "The window is no longer responding" after some time

**Comment by isidorn** [comment]
Okey, the link to 1M files stil ldoes not work, can you fix that and then I can try to repro. Thanks

**Comment by zeuschops** [comment]
Attempted to upload that tar.gz file to [Google Drive](https://drive.google.com/file/d/1M6dTuGAyZDa9T11eWECuBM4El9gLdX6s/view?usp=sharing). Maybe now it'll work 🙂
