### ISSUE TITLE
Insiders: setting to disable SCM annotation in title bar

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#114489]
Hi!

What's the name of this feature introduced in Insiders 1.53? Can we disable it?

![Capture du 2021-01-17 13-57-43](https://user-images.githubusercontent.com/15984272/104843696-49395980-58cc-11eb-8062-03b4043d03fd.png)

The coloring of the editor title name, and the SCM annotation

**Comment by ArturoDent** [comment]
`Workbench > Editor > Decorations: Colors`

and `Badges`
