### ISSUE TITLE
Sort/organize open editors using relative path

### ISSUE THREAD

**Issue by studgeek** [microsoft/vscode#114470]
https://github.com/Microsoft/vscode/issues/12453 added support for sorting the open editors alphabetically based on just the file name. As mentioned in the discussion there, it would be beneficial to sort based on the file's relative path so that they are ordered the same as the explorer outline (and implicitly near similar files).

**Comment by isidorn** [comment]
@studgeek I think this makes sense and is a fair request.
It would just be another option in the `"explorer.openEditors.sortOrder"` setting.
How would we call this value?
`relativePath`?

Does the Outline have a setting name for this that we could reuse?

**Comment by studgeek** [comment]
`relativePath` sounds fine to me! I don't think Explorer has a directly relevant value because it always is grouped by relative path. It's settings just control how files are sorted within a particular directory group.

**Comment by isidorn** [comment]
Let's keep this open and if we see that more users want this we can add it....

**Comment by petval** [comment]
Yes it would be great!

**Comment by coling** [comment]
FWIW, as the other option is "alphabetical", making this one relativePath is a bit inconsistent. Perhaps better to rename "alphabetical" to "filename" (keeping alphabetical as an alias) and then add either "relativePath" or "fullPath" (in the context, I think "fullPath" is a more understandable term, even if it is technically relative to the project root - most people won't really understand "relative path" as a term here (and even for me, I think of a relative path being relative to some base value and possibly containing ../../ etc. to traverse relative to that base - without a project open, there is no base path or perhaps I'm missing something here.)

Anyway, if you point me at the code that uses this, I'm sure I could knock up a patch. I'd certainly use it as the extension I currently use is a pain in the backside with the resorting only happing when you click on the files!

**Comment by coling** [comment]
Appreciate this is totally the wrong approach to development/review etc, but is this vaguely on the right lines?

Not hacked on typescript before nor have I looked into how to build/test this change, so very much just a drive by hack at the code in what looks like vaugely the right place.

If someone wants to take this patch, tweak it, test it and make it a full pull request, feel free. You have my full permission to do with it what you please. I'm not sure if I'll have time to learn the whole build/test chain procedure anytime soon.

```
diff --git a/src/vs/workbench/contrib/files/browser/files.contribution.ts b/src/vs/workbench/contrib/files/browser/files.contribution.ts
index ef271b53a5c..4d490bda5db 100644
--- a/src/vs/workbench/contrib/files/browser/files.contribution.ts
+++ b/src/vs/workbench/contrib/files/browser/files.contribution.ts
@@ -315,11 +315,13 @@ configurationRegistry.registerConfiguration({
                },
                'explorer.openEditors.sortOrder': {
                        'type': 'string',
-                       'enum': ['editorOrder', 'alphabetical'],
+                       'enum': ['editorOrder', 'alphabetical', 'filename', 'fullPath'],
                        'description': nls.localize({ key: 'openEditorsSortOrder', comment: ['Open is an adjective'] }, "Controls the sorting order of editors in the Open Editors pane."),
                        'enumDescriptions': [
                                nls.localize('sortOrder.editorOrder', 'Editors are ordered in the same order editor tabs are shown.'),
-                               nls.localize('sortOrder.alphabetical', 'Editors are ordered in alphabetical order inside each editor group.')
+                               nls.localize('sortOrder.alphabetical', 'Editors are ordered alphabetically by filename inside each editor group (alias for filename).')
+                               nls.localize('sortOrder.filename', 'Editors are ordered alphabetically by filename inside each editor group.')
+                               nls.localize('sortOrder.filePath', 'Editors are ordered alphabetically by full file path inside each editor group.')
                        ],
                        'default': 'editorOrder'
                },
diff --git a/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts b/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts
index 81912c52f46..dc743a38592 100644
--- a/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts
+++ b/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts
@@ -47,7 +47,7 @@ import { IViewDescriptorService } from 'vs/workbench/common/views';
 import { IOpenerService } from 'vs/platform/opener/common/opener';
 import { Orientation } from 'vs/base/browser/ui/splitview/splitview';
 import { IListAccessibilityProvider } from 'vs/base/browser/ui/list/listWidget';
-import { compareFileNamesDefault } from 'vs/base/common/comparers';
+import { compareFileNamesDefault, comparePaths } from 'vs/base/common/comparers';
 import { Codicon } from 'vs/base/common/codicons';
 import { KeyCode, KeyMod } from 'vs/base/common/keyCodes';
 import { KeybindingWeight } from 'vs/platform/keybinding/common/keybindingsRegistry';
@@ -69,7 +69,7 @@ export class OpenEditorsView extends ViewPane {
        private contributedContextMenu!: IMenu;
        private needsRefresh = false;
        private elements: (OpenEditor | IEditorGroup)[] = [];
-       private sortOrder: 'editorOrder' | 'alphabetical';
+       private sortOrder: 'editorOrder' | 'alphabetical' | 'filename' | 'filePath';
        private resourceContext!: ResourceContextKey;
        private groupFocusedContext!: IContextKey<boolean>;
        private dirtyEditorFocusedContext!: IContextKey<boolean>;
@@ -107,7 +107,7 @@ export class OpenEditorsView extends ViewPane {
                        }
                        this.needsRefresh = false;
 
-                       if (this.sortOrder === 'alphabetical') {
+                       if (this.sortOrder === 'filename' || this.sortOrder === 'fullPath' || this.sortOrder === 'alphabetical') {
                                // We need to resort the list if the editor label changed
                                elements.forEach(e => {
                                        if (e instanceof OpenEditor) {
@@ -336,8 +336,10 @@ export class OpenEditorsView extends ViewPane {
                                this.elements.push(g);
                        }
                        let editors = g.editors.map(ei => new OpenEditor(ei, g));
-                       if (this.sortOrder === 'alphabetical') {
+                       if (this.sortOrder === 'filename' || this.sortOrder === 'alphabetical') {
                                editors = editors.sort((first, second) => compareFileNamesDefault(first.editor.getName(), second.editor.getName()));
+                       } else if (this.sortOrder === 'fullPath') {
+                               editors = editors.sort((first, second) => comparePaths(first.editor.getResource().fsPath, second.editor.getResource().fsPath));
                        }
                        this.elements.push(...editors);
                });
```

**Comment by isidorn** [comment]
@coling I am not 100% sure we want this feature in VS Code core yet. However if you would like me to review these proposed changes please create a new PR since then it is easier for me. Thank you

**Comment by maxgrekhov** [comment]
@JacksonKearl, please review the pull request.

**Comment by kokoshneta** [comment]
I only just realised now that an alphabetic sorting order had been implemented, and my very first thought was that it would be so much more useful to sort by folder as well, so I’m very happy to see that this is being actively worked on. I look forward to seeing the result in a future update!

**Comment by JacksonKearl** [comment]
\closedWith a7575fb
