### ISSUE TITLE
TypeService died 5 times...

### ISSUE THREAD

**Issue by chrishacia** [microsoft/vscode#114491]
Issue Type: <b>Bug</b>

I have no idea, I left my computer idle for about 30 minutes and came back to that.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|. --crash-reporter-id 081862b8-cc93-4dc4-a0a1-992234c77e9d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
vscode-styled-jsx|bla|2.0.0
bracket-pair-colorizer|Coe|1.0.61
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.3
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-jest-runner|fir|0.4.31
auto-rename-tag|for|0.1.6
vscode-docker|ms-|1.9.0
remote-containers|ms-|0.154.2
java|red|0.73.0
vscode-yaml|red|0.14.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0
nyan-cat|zhe|0.0.8
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
vstry244cf:30244300
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30241727

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Have you hit this issue again? To investigate this issue we need to know triggered it

**Comment by chrishacia** [comment]
I am not 100% sure, I am mot exactly sure how I would recreate the issue. Overall I had been working my normal days worth of work,I had walked away from my desk for a short while during which time my computer went idle, screen saver came on, and when I came back I saw that error.

**Comment by mjbvz** [comment]
Closing this as there's not enough information to investigate this.

If you see this again, first check to see if it happens when extensions are disabled. If it does, then try collecting the server log so we can investigate:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
