### ISSUE TITLE
CustomExecution missing task variables with arguments get truncated

### ISSUE THREAD

**Issue by SchoofsKelvin** [microsoft/vscode#114473]
For my extension that involves a FileSystemProvider with SSH, I defined a `ssh-shell` task type. Currently I'm in the process of adding some variables to it (SchoofsKelvin/vscode-sshfs#232), e.g. `${remoteFile}` and `${remoteWorkspaceFolder:SSH - Test}`. While coding and testing some things, I stumbled upon my custom variables being truncated after being resolved.

For example, `${test:abc} ${test}` would be resolved to `${test} ${test}`.

________________________________
**Steps to reproduce:**
<details>
<summary>Extension that outputs a resolved task definition (field)</summary>
Attached a .vsix to this issue, consisting of the following:

**extension.js**
```js
  const vscode = require('vscode');
  function activate(context) {
	context.subscriptions.push(vscode.tasks.registerTaskProvider('echo', {
		resolveTask(task) {
			return new vscode.Task(task.definition, task.name || 'echo', 'echo', new vscode.CustomExecution(async resolved => {
				const onDidWrite = new vscode.EventEmitter();
				const onDidClose = new vscode.EventEmitter();
				return {
					onDidWrite: onDidWrite.event,
					onDidClose: onDidClose.event,
					close: onDidClose.fire.bind(onDidClose),
					open() {
						onDidWrite.fire(`Original: ${task.definition.message}\r\n`);
						onDidWrite.fire(`Resolved: ${resolved.message}\r\n`);
						onDidClose.fire(0);
					}
				};
			}));
		}
	}));
  }
module.exports = { activate };
```
**Task contribution in package.json**
```json
	"contributes": {
		"taskDefinitions": [
			{
				"type": "echo",
				"properties": {
					"message": {
						"type": "string",
						"description": "The message to output"
					}
				},
				"required": [
					"message"
				]
			}
		]
	},
```
</details>
<details>
<summary>Task definition with special usage of non-existing variables</summary>

```json
{
    "type": "echo",
    "label": "ABC",
    "message": "echo '${workspaceFolderBasename}' '${def:arg}' '${abc:test}' '${abc}' '${abc:def}' '${xyz:123}' '${xyz:456}'",
    "problemMatcher": []
}
```
**Requirements for the task definition:**
- Have at least one `${something}` and one or more `${something:stuff}` _somewhere_ in the task definition
_(doesn't have to be within the same string)_
- Every instance with an argument will be "resolved" to `${something}`, discarding the argument
</details>
<details>
<summary>Run task to observe the non-existing variables (meeting the requirements) being truncated</summary>

```
> Executing task: ABC <

Original: echo '${workspaceFolderBasename}' '${def:arg}' '${abc:test}' '${abc}' '${abc:def}' '${xyz:123}' '${xyz:456}'
Resolved: echo 'Empty workspace' '${def:arg}' '${abc}' '${abc}' '${abc}' '${xyz:123}' '${xyz:456}'

Terminal will be reused by tasks, press any key to close it.
```
</details>

________________________________
**Cause:**
- First iteration, VS Code [collects](https://github.com/microsoft/vscode/blob/eaa959d34b863dec932077d94daece22504a396b/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L667) all variables, then [resolves](https://github.com/microsoft/vscode/blob/eaa959d34b863dec932077d94daece22504a396b/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L569) them
- This results in `${abc}` geting mapped to `${abc}` and `${abc:test}` getting mapped to `${abc:test}`, as expected
- `CustomExecution` gets handled [differently](https://github.com/microsoft/vscode/blob/eaa959d34b863dec932077d94daece22504a396b/src/vs/workbench/api/browser/mainThreadTask.ts#L422), resolving the definition, this time filling in stuff
- Unknown variables [try to be read](https://github.com/microsoft/vscode/blob/eaa959d34b863dec932077d94daece22504a396b/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L321) from the previously calculated mapping, **only passing the "variable type", ignoring the argument**
- This [results](https://github.com/microsoft/vscode/blob/eaa959d34b863dec932077d94daece22504a396b/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L332) in `commandValueMapping['abc']` instead of `commandValueMapping['abc:test']` _(the latter also being present in the mapping)_

________________________________
- VSCode Version: 1.52.0
- OS Version: Windows_NT x64 10.0.18363

**Comment by alexr00** [comment]
> Currently I'm in the process of adding some variables to it

How are you adding variables? As far as I'm aware, we don't actually support a way to add custom variables.

**Comment by alexr00** [comment]
Ah, I see. Yes, this is a legit issue.

**Comment by SchoofsKelvin** [comment]
> How are you adding variables? As far as I'm aware, we don't actually support a way to add custom variables.

To clarify _(for other readers)_: I parse `${...}` tags of task definitions _(in a similar way to how VS Code does it internally)_ inside my `ssh-shell` TaskProvider's CustomExecution callbacks. Those variables are thus specific to my task type, and not global through VS Code. While the latter might be a nice feature to have, it's unrelated to this issue.

**Comment by SchoofsKelvin** [comment]
/verified Tested on version 3290f9a _(2021-02-26 05:13:29 according to `About`)_ with the [example extension](https://github.com/microsoft/vscode/files/6049208/issue-example.zip) and it now doesn't truncate variables anymore.

**Comment by alexr00** [comment]
Thank you @SchoofsKelvin !
