### ISSUE TITLE
Intellisense for "Rename Symbol"/F2

### ISSUE THREAD

**Issue by sadburai** [microsoft/vscode#114479]
Hi, 
I think it would be great if you could add Intellisense Suggestions to "Rename Symbol" (F2). 

Example: 
I want to rename an html `<section>` to `<article>.` In the text editor `<article>` would be suggested after typing `"<a",` which makes editing much quicker.

Best regards,
Till

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"rename"
