### ISSUE TITLE
.env file variable substitution seems broken

### ISSUE THREAD

**Issue by schnort** [microsoft/vscode#114435]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

variables don't seem to be substituting correctly in the .env file.

in settings.json:
    "python.envFile" : "${workspaceFolder}/.env",

in .env:
PYTHONPATH=${PROJ_DIR}/utf;${WORKSPACE_FOLDER};${workspaceFolder}/tools/api_generation

In python file launched by F5:
import sys
import os
print(sys.path)
print(os.environ['PYTHONPATH'])

output:
`['c:\\silabs\\falcon2-repository\\modules\\falcon2-modules\\api\\system_manager_api\\pyapi', 'C:\\utf', 'C:\\silabs\\falcon2-repository', 'C:\\tools\\api_generation', 'c:\\silabs\\Python\\Python38\\python38.zip', 'c:\\silabs\\Python\\Python38\\DLLs', 'c:\\silabs\\Python\\Python38\\lib', 'c:\\silabs\\Python\\Python38', 'C:\\Users\\ruschult\\AppData\\Roaming\\Python\\Python38\\site-packages', 'c:\\silabs\\Python\\Python38\\lib\\site-packages', 'c:\\silabs\\Python\\Python38\\lib\\site-packages\\win32', 'c:\\silabs\\Python\\Python38\\lib\\site-packages\\win32\\lib', 'c:\\silabs\\Python\\Python38\\lib\\site-packages\\Pythonwin']`

`/utf;;/tools/api_generation;C:\silabs\falcon2-repository`

You can see the variables are just not getting substituted.  This did work at one point, but i'm not sure how to easily regress versions of VSCODE.

**Comment by weinand** [comment]
VS Code does not know anything about `.env` files.
if this worked before, it must be a feature of the Python extension.
