### ISSUE TITLE
Show port forwarding notification only in the focussed window

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#114448]
1) have multiple windows open against the same SSH remote box
2) run a new server on the box

You get a notification in all open windows:

![image](https://user-images.githubusercontent.com/4674940/104793509-cee7c880-5757-11eb-90b8-5b8dcce18a2b.png)

**Comment by alexr00** [comment]
Fixed by 49061a5b8a1a8548e9f825fb3097eabd5e4ce5a7

**Comment by connor4312** [comment]
@alexr00 it seems like I'm not getting notifications for any forwarded ports, even if I explicitly configure them. Is this is a separate bug?

![](https://memes.peet.io/img/21-02-bf14cf51-cfc4-4fc5-bad7-00945beb4449.png)

**Comment by alexr00** [comment]
@connor4312  That sounds like a separate bug. SSH now uses output based port forwarding, so it may be that the output that your `serve` command generated wasn't read properly. Can you make a new bug with repro steps for how to get that specific output?
