### ISSUE TITLE
Cannot open second Remote-SSH

### ISSUE THREAD

**Issue by pavel-francirek** [microsoft/vscode#114484]
Issue Type: <b>Bug</b>

If I try to open second Remote-SSH Folder in new window (both via "Remote-SSH: Connect To Host" or "New Window -> Open Recent") it opens in old window (replaces already opened folder). Works OK on Ubuntu 20.04 with same (synced) config.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 4.4.0-190-generic
Remote OS version: Linux x64 4.15.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 5a2eee78-e3c8-4733-8a08-680f636050a4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev|
|OS|Linux x64 4.4.0-190-generic|
|CPUs|Intel Xeon E312xx (Sandy Bridge) (2 x 2599)|
|Memory (System)|3.86GB (0.94GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev-www3|
|OS|Linux x64 4.15.0-96-generic|
|CPUs|Intel Core Processor (Broadwell, IBRS) (4 x 2099)|
|Memory (System)|7.79GB (1.07GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
vscode-firefox-debug|fir|2.9.1
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
jinjahtml|sam|0.16.0
gitconfig|sid|2.0.1
gitlens|eam|11.1.3
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025

</details>

**Comment by roblourens** [comment]
Can you share your vscode settings? Particularly anything starting with `window.*`.

**Comment by pavel-francirek** [comment]
Sorry, didn't notice question. My .settings file is:

```
{
    "workbench.colorTheme": "Default Light+",
    "workbench.startupEditor": "none",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "files.autoSave": "off",
    "emmet.showSuggestionsAsSnippets": true,
    "python.analysis.memory.keepLibraryAst": true,
    "breadcrumbs.symbolSortOrder": "name",
    "python.analysis.symbolsHierarchyDepthLimit": 5,
    "python.experiments.enabled": false,
    "python.showStartPage": false,
    "git.enableSmartCommit": true,
    "window.zoomLevel": -1,
    "emmet.triggerExpansionOnTab": true,
    "emmet.preferences": {
    
    },
    "python.pythonPath": "/usr/bin/python3",
    "git.confirmSync": false
}
```

**Comment by roblourens** [comment]
Strange, I have no clue. Does the original window have a folder open or empty? I assume you get exactly the same result if you use "Connect Current Window to Host"
