### ISSUE TITLE
Freezes/crashes when hovering in sidebar panel on Raspberry Pi 4

### ISSUE THREAD

**Issue by joelspadin** [microsoft/vscode#114454]
Issue Type: <b>Bug</b>

I am attempting to use VS Code on a Raspberry Pi 4GB running Ubuntu Mate (32-bit). When moving my mouse over anything in the sidebar that has a hover (files in the explorer panel, the sidebar panel icons, etc.), VS Code will freeze for a couple seconds and then either the entire window will briefly go blank before it recovers, or it will crash. The hovers themselves appear as blank rectangles with no text.

To reproduce:

1. Open a folder containing files.
2. Move the mouse over sidebar icons or files in the explorer panel.

I have reproduced the crash with crash reporting enabled, as described at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues, and have attached the crash reports.

[vscode-crash.tar.gz](https://github.com/microsoft/vscode/files/5823998/vscode-crash.tar.gz)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:35.090Z)
OS version: Linux arm 5.8.0-1011-raspi

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|ARMv7 Processor rev 3 (v7l) (4 x 1500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|3.68GB (0.56GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id e086c4b6-8d50-4e91-8b2b-dd395ec58997|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244:30244299
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600cf:30241728

```

</details>

**Comment by joelspadin** [comment]
An example of the blank hovers it shows while freezing. 
![image](https://user-images.githubusercontent.com/760836/104806123-bea50d00-579a-11eb-8a82-f118b3259022.png)

**Comment by deepak1556** [comment]
Thanks for the crash reports, does this happen when you run with `--disable-gpu` ? Can you also test with latest stable `1.53`

**Comment by joelspadin** [comment]
It still crashes on 1.53. 

If I run 1.53 with `--disable-gpu`, it just shows a blank white screen for about ten seconds before crashing. Here's the crash reports from that:

[vscode-crash-disable-gpu.tar.gz](https://github.com/microsoft/vscode/files/5955408/vscode-crash-disable-gpu.tar.gz)

**Comment by deepak1556** [comment]
Can you try with latest insiders https://code.visualstudio.com/insiders and start with `code-insiders --use-gl=swiftshader`

**Comment by joelspadin** [comment]
That appears to have the same problem, though in the cases where VS Code doesn't outright crash, it seems to recover a little faster.

It also seems to randomly crash the window manager too. Ubuntu Mate's desktop panels disappeared and reappeared a few seconds later several times before VS Code eventually crashed. Should I provide crash reports with that enabled too?

**Comment by joaomoreno** [comment]
cc @deepak1556

**Comment by joelspadin** [comment]
This still occurs with VS Code 1.55.2. Let me know if there's any extra info I can grab.

**Comment by joelspadin** [comment]
After upgrading to Ubuntu Mate 21.04 and VS Code 1.57, this appears to be fixed.
