### ISSUE TITLE
Possibility to move around pinned tabs with workbench.action.openEditorAtNextIndex/PrevIndex

### ISSUE THREAD

**Issue by CIRCULARKA** [microsoft/vscode#114453]
I wanted to make new shortcut on `Shift+j` to move on a left pinned tab and `Shif+k` to move on a right one. But there are only workbench.action.openEditorAtIndex1-9 commands. I think that implementing commands that allow moving on a next/previous pinned tab could be a good idea. Such commands can be named as `workbench.action.openEditorAtNextIndex` and  `workbench.action.openEditorAtPreviousIndex`. Implementing it will allow to move on a next/previous pinned tabs by shortcuts very easy comparing to existing `Alt+1 ... Alt+9`.

**Comment by bpasero** [comment]
@CIRCULARKA how is this not covered already by the existing commands to open the next or previous editor either in a group or across all groups:

![image](https://user-images.githubusercontent.com/900690/105693086-98e8d800-5eff-11eb-89e3-5ba9e08c435a.png)

**Comment by CIRCULARKA** [comment]
Ok.
