### ISSUE TITLE
Change all occurrences has doens't working

### ISSUE THREAD

**Issue by xtremebh** [microsoft/vscode#114410]
- VSCode Version: 1.52.1
- OS Version: Windows 10 pro

Steps to Reproduce:

1. go to a code section that have repeated occurrences.
2. and use keyboard shortcut control + f2 or menu.

Does this issue occur when all extensions are disabled?: I don't know how to disable all extensions

**Comment by IllusionMH** [comment]
/needsMoreInfo

To disable extension you can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

You also need to specify what language and minimal code sample that causes problems. Those occurrences might be not related, involve other specifics language specifics etc.
