### ISSUE TITLE
User/Workspace files.exlude cannot exclude from root of folder added to workspace

### ISSUE THREAD

**Issue by spongepaul** [microsoft/vscode#114447]
Cannot exclude folders from the root of a folder added to the workspace.

Add Folder to Workspace:    `X:\LaunchIntranet\illustrators`
Add User/Workspace Files Exclude:  `**/illustrators/img/artists/*`          ...does not work

Only solution is to make a more generic exclude `**/img/artists/*`   (but will match folders outside illustrators)
or make a Files Exclude in the Folder(illustrators) settings:  `img/artists/**`    (but will affect all users accessing this folder)

![Capture](https://user-images.githubusercontent.com/1760807/104793347-18441200-5770-11eb-8a4a-863d537c0c84.PNG)

**Comment by gjsjohnmurray** [comment]
Is he proposal in https://github.com/microsoft/vscode/issues/50638#issuecomment-721685105 the kind of thing you want?

**Comment by psultan** [comment]
Bingo.  I tried doing a issue search for in:title files exclude but that one did not pop up.

**Comment by isidorn** [comment]
Let's close as duplicate since the `files.exclude` would be respected across the workbench - including search and explorer
