### ISSUE TITLE
Cannot push/pull repo with git-lfs enabled

### ISSUE THREAD

**Issue by Cuberick-Orion** [microsoft/vscode#114407]
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.04

This only took place after an update (not sure after which version).

I found that I cannot pull/push git repositories in the Source Control Panel with `git-lfs` enabled. Even though I can still commit locally.

Meanwhile, opening up a terminal and `git push` there works fine.

Here is the git output from the VsCode -> Output -> Git (although it's very limited):
```bash
From github.com:REDACTED
 * branch            main       -> FETCH_HEAD
> git push origin main:main
> git ls-files --stage -- [Some new files to be pushed - Note: doesn't even have to be git-lfs related!]
> git cat-file -s 3e6aa5c6765b5ccda1595089ee96a737cc358915
> git show --textconv :[Some new files to be pushed]

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'git@github.com:REDACTED'
```

Does this issue occur when all extensions are disabled?: Yes

Appreciate any help. If further details are needed please let me know.

**Comment by eamodio** [comment]
Can you see if this is still reproducible on the latest insiders edition?
