### ISSUE TITLE
Can't update "Visual Studio Code".

### ISSUE THREAD

**Issue by mr4660** [microsoft/vscode#114469]
Issue Type: <b>Bug</b>

I VPN behind a corporate fire-wall; using a proxy ("http.proxy": "http://one.proxy.att.com:8080").  Each time I execute "Help\Check for Updates"), I get error message "net:ERR_TUNNEL_CONNECTION_FAILED".   Even when I turn off VPN and remove "proxy" settings, I sitll get that error message.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.62GB free)|
|Process Argv|--crash-reporter-id 2cb11189-4d03-4706-afc9-d13e9153b0ad|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by deepak1556** [comment]
Do you still experience the issue with latest stable `1.53` ?

**Comment by dliedke** [comment]
I am facing the same issue with VS.NET 2022 when connected to VPN. The check for updates dialog just keeps going forever. What is the host VS.NET is using to check for updates so I can work with my company VPN team to add it?
