### ISSUE TITLE
findCandidatePorts memory exhaustion and high CPU usage

### ISSUE THREAD

**Issue by BlackGlory** [microsoft/vscode#114452]
https://github.com/microsoft/vscode/blob/61312f3708df5e3ae4f7de338b3c46cf36849d7c/src/vs/workbench/api/node/extHostTunnelService.ts#L260

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

WSL1
OS: Ubuntu 20.04.1 LTS on Windows 10 x86_64
Kernel: 4.4.0-19041-Microsoft

![htop](https://user-images.githubusercontent.com/1365962/104798008-e5e0f600-57fd-11eb-8f12-92dced72fdba.png)
![htop2](https://user-images.githubusercontent.com/1365962/104798009-e7aab980-57fd-11eb-946f-437c5eb3342f.png)

**Comment by alexr00** [comment]
Thanks for reporting this @BlackGlory! I've tried to address all of the problems in `findCandidatePorts` for our next release. Do you still see this issue in [Insiders](https://code.visualstudio.com/insiders/)?

**Comment by BlackGlory** [comment]
I can't reproduce this problem, it appears completely randomly, it only happened twice in the past month.

**Comment by alexr00** [comment]
Since this issue looks identical to the others reported with `findCandidatePorts`, I'll close it as duplicate.
