### ISSUE TITLE
Integrated terminal jerky scrolling with scrollbar

### ISSUE THREAD

**Issue by karepte** [Microsoft/vscode#11448]
- VSCode Version: 1.5.0-insider commit bd35113a
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Open Visual Studio Window.
2. Press CTRL + ' to open Integrated Terminal.
3. type some command that will generate a couple of pages of output. e.g. execute twice **ipconfig** command
4. Try to grab scrollbar and scroll up and down.

Expected behavior:
The console output scrolling is synchronized with the scrollbar position giving smooth scrolling experience.

Actual behavior:
The console output scrolling is jerky. It's position is only refreshed about once a second.

**Comment by Tyriar** [comment]
Some questions:

- What shell are you using?
- Is the terminal generally slow?
- Can you create a gif that demonstrates the issue?

Also note that it's a design constraint that it will only scroll 1 line at a time, by pixel scrolling is not supported intentionally.

**Comment by karepte** [comment]
Normal cmd.exe shell.
Turns out this is only an issue when connected on a Remote Desktop session.
I am closing this issue.
