### ISSUE TITLE
Turning off tab completions does not turn off the tab completions

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#114427]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. For the sake of reproducing the bug, suppose we open any file in our workspace. Here I opened a Python file in my workspace folder.
2. I have disabled tab completions and also checked all the relevant settings which may turn on the tab completion .
3. When I am in a for loop, as soon as I type for, a snippet shows up. Ok fine, I press enter to insert the snippet and when I am in the loop,

![image](https://user-images.githubusercontent.com/54276661/104759970-b4791380-5786-11eb-980d-577faef77726.png)

**Here you can see I just entered the variable i to iterate in the loop and when I press Tab ,I just want it to ignore the completion suggestions and go over the _expression_list_ using tab keyword. But no...it will insert the snippet although I have turned off tab completions.**

Does this issue occur when all extensions are disabled?: Yes/No
YES

**What I want is when I disable tab completions, then on pressing tab it should not auto complete the code word I am writing.**

**Comment by lakshits11** [comment]
No it's not a duplicate issue.

**Comment by jrieken** [comment]
Unrelated to tab completion. What you need is this setting to be true: `editor.suggest.snippetsPreventQuickSuggestions`
