### ISSUE TITLE
File name displayed on the tab is automatically changed when saving file changes

### ISSUE THREAD

**Issue by mabooky** [microsoft/vscode#114486]
Issue Type: <b>Bug</b>

To Reproduce:

1. Make a folder and open it in VS Code.
2. Make a file. Let's suppose the new file name 'Example.js'.
3. Change the file name to 'example.js'. Then the file name displayed on the tab will be changed to 'example.js' too.
4. Make any changes on the file and save changes.
5. The file name on the tab changes to wrong name, 'Example.js'.
6. If I click 'example.js' on project tree again, the file name on the tab changes back to 'example.js'.

This occurs regradless of file extension and only occurs when a file name is same but only case is different. For example, 'eXaMPlE.js', 'EXAMPLE.js' too.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8300 Eight-Core Processor            (8 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.97GB (6.85GB free)|
|Process Argv|--crash-reporter-id d5d4fffc-5da6-4dd4-b82d-ea7089ca55d8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|0.2.41
vscode-language-pack-ko|MS-|1.52.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt875:30241730

```

</details>

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues?q=is%3Aissue+tab+casing+is%3Aclosed
fyi @bpasero
