### ISSUE TITLE
Cannot move VS Code/VS Codium Windows

### ISSUE THREAD

**Issue by SullyInATX** [microsoft/vscode#114457]
Hi all. I'm running PopOS and, for some reason, VS Code's window is "locked" in place. I can resize it, but it is not movable via the standard method (clicking and dragging the title bar). Search engines aren't returning much in regards to this specific issue, so I thought I'd ask here. It's only on PopOS - I have no problems with it on any other distro/operating system. 

I also have no other issues with PopOS - it's only VS Code. 

Any ideas? Any other info you need? Both the system and VS Code are updated fully/to the latest versions.

**Comment by bpasero** [comment]
This does not sound like a supported platform or distribution.

**Comment by SullyInATX** [comment]
> This does not sound like a supported platform or distribution.

It is, and I was able to fix it via making some changes in the settings.json file.
