### ISSUE TITLE
String representation of a URI should not convert port component of authority to lowercase

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#114406]
[Section 6.2.2.1 of RFC3986](https://tools.ietf.org/html/rfc3986#page-38) says that only the scheme and host components should be normalized to lowercase. The host component is a subcomponent of authority and may optionally be followed by a port subcomponent, with ':' being the separator.

The way the following code converts to lowercase means that port will also be affected.

https://github.com/microsoft/vscode/blob/addb6b9b53a5095ebde7036da50fab766aa011b6/src/vs/base/common/uri.ts#L642-L650

On a FileSystemProvider I implement the authority component consists of two colon-separated elements, and I want the case of the second element to be preserved.

@jrieken I think this may be your area. Are you willing to take a PR from me?

**Comment by jrieken** [comment]
https://tools.ietf.org/html/rfc3986#section-3.2.3 says that ports are digits and they shouldn't change when lower-casing, right?

**Comment by gjsjohnmurray** [comment]
You're correct. My URI syntax diverges from the generic syntax in allowing non-digits in the second colon-piece.

The doc for toString already warns:
```
	 * * The result will be encoded using the percentage encoding and encoding happens mostly
	 * ignore the scheme-specific encoding rules.
```

Looks like this also applies to scheme-specific casing rules.

I guess there's a small chance that other users are also subverting the port piece of authority **and** relying on current behaviour to lowercase it. So I'll understand if you decide not to allow this to be changed.

**Comment by jrieken** [comment]
> So I'll understand if you decide not to allow this to be changed.

The unfortunate truth is that I get burnt whenever I change the URI - even when fixing its bugs. Therefore I am very reluctant to any change. This is independent of the proposed change but just because extensions have used and persisted uris in all funny ways...

**Comment by gjsjohnmurray** [comment]
OK, I'm closing this. Thanks for your input.

**Comment by jrieken** [comment]
Thanks for understanding
