### ISSUE TITLE
Restart specific debugger using command

### ISSUE THREAD

**Issue by DJ4ddi** [microsoft/vscode#114467]
Hi there.

A bit of background for the setup: I'm working with an Electron application, which requires two different debugging configurations - one for the main process, one for the renderer. I set up my `launch.json` so that the *chrome attach* automatically runs when the *node launch* is done starting (the same could also be achieved through a compound configuration).

But this setup has a major inconvenience: Whenever a task, extension or the user runs the "Debug: Restart" command, it restarts the configuration that is currently selected in the debugging widget (the one with the pause, continue and step buttons) or the "Debug Console" tab. By default, that's the main process launcher. Unfortunately, in 99% of cases the intended behavior is to restart the renderer, not the launcher, which means that the wrong debugger is restarted if the user doesn't pay attention to the currently selected one.

What I want to do is to configure a preferred debugger that will be restarted when the `workbench.action.debug.restart` command is invoked.
- One possible solution would be to add a launch.json option for runtime priority so that the renderer can be selected, e.g. through a new *presentation* property (or by respecting the existing *order* option).
- Another solution would be a parameter for the command, although I am not sure how that would interact with calling it from a task (using the `${command:<command>}` syntax).

I am, of course, open for alternative solutions.

**Comment by ArturoDent** [comment]
Possibly this extension could help: [Launch Debug](https://marketplace.visualstudio.com/items?itemName=ArturoDent.launch-config)  and assign a keybinding to your renderer debug.

**Comment by weinand** [comment]
@DJ4ddi could you give Arturo's extension a try?

**Comment by DJ4ddi** [comment]
Unfortunately the extension does not solve my issue. I like the approach (defining a command for a specific configuration), but the problem is that it always attempts to start the configuration. In my case, I need it to *restart* the active one. Attempting to do so using Launch Debug displays the following error: `There is already a debug configuraton "testConfig" running.`

**Comment by ArturoDent** [comment]
Good point, I'll look into stopping the matching debug session first before re-starting the same configuration.  It looks doable.

**Comment by DJ4ddi** [comment]
Cool. Do keep in mind that stopping and starting is not the same as restarting for many browser based debuggers (e.g. Debugger for Chrome, which is used for Electron, reloads the window on restart, but not on re-attach).

**Comment by DJ4ddi** [comment]
@weinand Looks like implementing this functionality in an extension would require an API to restart a `DebugSession`. I could imagine this being an option for `debug.startDebugging` or a separate function. Any chance of that happening?

**Comment by weinand** [comment]
Most built-in commands (like "Restart") have an ID ("workbench.action.debug.restart") and can be executed via the `vscode.commands.executeCommand` API

**Comment by DJ4ddi** [comment]
The command you suggested restarts the currently active debugging instance, which is the reason why this ticket exists. There is no way to restart a different instance via commands or the API.

**Comment by weinand** [comment]
@isidorn any idea how to address this issue?

**Comment by isidorn** [comment]
@weinand that sounds like a good approach and it might already work looking at the code [here](https://github.com/microsoft/vscode/blob/af2bcd4d4612dc25f848a0a6a758507010401fa0/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L221)

@DJ4ddi you should be able to execute the `workbench.action.debug.restart` and pass the following object `{ sessiondId: YOUR_SESSION_ID }`
Try passing it as the first argument, if that does not work, pass it as a second argument.

Let me know how it goes.

**Comment by DJ4ddi** [comment]
Great, that worked (second argument is the correct one).

Code sample for my use case:
```js
var sessions = [];
function activate() {
  vscode.debug.onDidStartDebugSession(session => sessions.push(session.id));
  vscode.debug.onDidTerminateDebugSession(session => sessions = sessions.filter(sid => sid !== session.id));
  vscode.commands.registerCommand("workbench.action.debug.restartLatest",
    () => vscode.commands.executeCommand("workbench.action.debug.restart", "", { sessionId: sessions[sessions.length - 1]);
  });
}
```

@ArturoDent this might interest you as well.
