### ISSUE TITLE
Repeated CTRL+S Causes Multiple Save Dialogues

### ISSUE THREAD

**Issue by jehugaleahsa** [microsoft/vscode#114432]
Issue Type: <b>Bug</b>

If you create a new file and then CNTL+S several times, clicking Cancel causes another save dialogue to show up. I have a tendendy to slam this keyboard shortcut many times (maybe some sort of nervous tick :-) ) but then I have to sit there and hit Cancel as many times as I pressed the keys.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (15.76GB free)|
|Process Argv|--crash-reporter-id 22865162-8583-4afc-9d43-fef955820053|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-sbt-scala|lig|0.2.4
vscode-docker|ms-|1.9.0
csharp|ms-|1.23.8
vscode-postgresql|ms-|0.3.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-wsl|ms-|0.52.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|0.73.0
vscode-xml|red|0.14.0
rust|rus|0.7.8
scala|sca|0.5.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629

```

</details>

**Comment by CameronIrvine** [comment]
I've also noticed this issue. Provided a fix in the above PR.
