### ISSUE TITLE
Scrolling in a notebook document results in onDidChangeVisibleTextEditors events

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#114440]
- VSCode Version: 1.53.0
- OS Version: Windows 10

Scrolling up and down in notebook document files results in onDidChangeVisibleTextEditors events. 

Steps to Reproduce:

1. Open changevisibleeditor folder attached to this issue
2. Press F5
3. In the extension development host, open test.github-issues in the /changevisibleeditor folder
4. Scroll up and down in test.github-issues while observing console output

Expected: onDidChangeVisibleTextEditors should not be triggered

Actual: onDidChangeVisibleTextEditors is called many times

Another issue with this being triggered for notebook cells is that the `viewColumn` of the editor is undefined. If the above behavior is expected, we request defining the viewColumn of the cells when returned as part of the visible editors.

cc @rebornix @daytonellwanger

[changevisibleeditor.zip](https://github.com/microsoft/vscode/files/5823390/changevisibleeditor.zip)

**Comment by rebornix** [comment]
This is actually as expected as `onDidChangeVisibleTextEditors` will include the cell editors in the notebook editor.
