### ISSUE TITLE
manage id's page not opening after clicking on setting in bot service. Insufficient privileges to complete the operation. | Certificates & secrets while opening opening any of the pages in bot framework

### ISSUE THREAD

**Issue by maheshpardeshi** [microsoft/vscode#114465]
- VSCode Version:
- OS Version:

Steps to Reproduce:
manage id's page not opening after clicking on setting in bot service. 
No Access error even when logged in as global admin to azure portal.
1. Login to portal.azure
2.Open bot service
3. click on the setting option
4. click on any of the tabs on the left side of the Navigation bar.
5. getts error of "No access"
![Capture](https://user-images.githubusercontent.com/6695075/104815465-c3b99900-583a-11eb-8766-384a844a6129.PNG)

Does this issue occur when all extensions are disabled?: Yes/No
NA

**Comment by bpasero** [comment]
This does not sound VSCode related.
