### ISSUE TITLE
Extension management disposal and cleanup should move into service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114417]
Currently only the shared process disposes the extension management service and calls `removeDeprecatedExtensions`:

https://github.com/microsoft/vscode/blob/2964fcbb84651625bb16fd1b30a44fcaa27f0caf/src/vs/code/electron-browser/sharedProcess/contrib/deprecatedExtensionsCleaner.ts#L10-L25

There is a few issues with that imho:
* it reaches into the internals of the service (it needs to cast to the implementation)
* disposing the service from that place seems wrong, it would be better to have some kind of lifecycle that can be listened to from within the management service
* we never benefit from this code in other places where we use the service (remote server, CLI).

**Comment by sandy081** [comment]
This is fixed
