### ISSUE TITLE
LabelService.getUriLabel misreports relative path when workspace folder is at root of filesystem

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#114416]
Issue Type: <b>Bug</b>

This showed up when trying to use the new `RELATIVE_FILEPATH` snippet variable (see #114208) with a resource served by a FileSystemProvider in which it is common to have a workspace path of `/`

I plan to submit a PR. Initially it will only contain a new test to demonstrate the bug. Then I will push a fix.

VS Code version: Code - Insiders 1.53.0-insider (1a6eef3170be2a11751ee50d450328d458f7bfac, 2021-01-15T05:15:40.826Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
Adding to January milestone so we get this verified.
@gjsjohnmurray once you get todays vscode insiders it would be cool if you let us know if this behaves as expected. Thanks!

**Comment by isidorn** [comment]
Thanks 👏
