### ISSUE TITLE
Visual Studio Code starts as a blank window, and stays that way.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#114459]
Issue Type: <b>Bug</b>

VSCode insiders start as a blank window and stays that way. This happened to me 2-3 times in the last couple of weeks.
When this happens there are no controls visible on the window(not even the close button), I have to uninstall VSCode altogether and reinstall a fresh download to get it working again. 
Also, I am not sure if this issue is VSCode insiders build or any extensions I have installed or my Windows 10 is doing something fishy with VSCode only. 
I tried to reproduce this issue by disabling/enabling all the installed extensions however I could not reproduce it so won't be able to provide a concrete set of steps.

>Note: Countless thanks for the setting sync feature, I would have spent at least a couple of days trying to set all the shortcuts and the configs I have. it would have been a pretty ugly mess.

UPDATE:
> workaround (as per the trailing comments if there are any additional workarounds I will add them here.)
> - use  `code-insiders --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` to start the VSCode instance.

VS Code version: Code - Insiders 1.53.0-insider (1a6eef3170be2a11751ee50d450328d458f7bfac, 2021-01-15T05:15:40.826Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.80GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
output-colorizer|IBM|0.1.2
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.13
vscode-typescript-next|ms-|4.2.20210115
vscode-typescript-tslint-plugin|ms-|1.3.3
cordova-tools|msj|2.1.2
debugger-for-chrome|msj|4.12.11
vscode-react-native|msj|1.2.0
vscode-xml|red|0.14.0
vscode-yaml|red|0.14.0
sonarlint-vscode|Son|1.19.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.85.0
vscodeintellicode|Vis|1.2.10
glean|wix|5.1.1
vscode-import-cost|wix|2.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanelcf:30233468

```

</details>

**Comment by bpasero** [comment]
Does this only happen with insider or also stable?

**Comment by sanket-bhalerao** [comment]
i use insiders build 99.99% of the time, so can not say if it happens with a stable build or not.

**Comment by bpasero** [comment]
Please try.

**Comment by sanket-bhalerao** [comment]
I faced a similar issue in the stable version as well.
The condition of insider build is becoming worse, in the past couple of hours I faced this issue 5 times.

**Comment by sanket-bhalerao** [comment]
I am unable to open insiders.
reinstall did not help this time.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by sanket-bhalerao** [comment]
I got the same result for this as well.
![image](https://user-images.githubusercontent.com/9264813/105461482-4b782b00-5cb3-11eb-8f35-88dc644b949a.png)

If I open a directory with files and folder in it and I hover over the place where the file explorer/extensions icon would have been I see a tooltip for it.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by sanket-bhalerao** [comment]
I tried with the following 2 commands however, the results in both cases are the same.

- `code-insiders --disable-extensions --disable-gpu --user-data-dir .`
- `code-insiders --disable-gpu`

I uninstalled the insiders build and removed the directory in which it was installed. Have not deleted the .extensions directory yet. I am using the user installer.

**Comment by bpasero** [comment]
Can you run from the command line with `code --verbose` to see if any error output is logged?

**Comment by sanket-bhalerao** [comment]
executed ` code-insiders --verbose --disable-extensions --disable-gpu --user-data-dir .`, and ` code-insiders --verbose` in both cases I see error like `[16208:0122/135257.995:INFO:CONSOLE(25)] "%cTRACE color: #888 Error: ENOENT: 
no such file or directory, open 'asdf\.vscode-insiders\extensions\wallabyjs.quokka-vscode-1.0.317\package.json'", source: file:///C:/Program Files/Microsoft VS Code Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (25)` for all the extensions I have.

**Comment by bpasero** [comment]
Ok, that unfortunately does not reveal much.

**Comment by sanket-bhalerao** [comment]
if you want the entire log i can send over email.

**Comment by bpasero** [comment]
Is there anything special with the file system not being standard? Or user accounts? Or AV software running?

**Comment by sanket-bhalerao** [comment]
not really,
at least there is no change in the file system, user account, AV software in the last few months.

**Comment by deepak1556** [comment]
Sorry for the late response, can you attach the full log for

`code-insiders --verbose --disable-extensions --disable-gpu --user-data-dir <some-absolute-path>`

**Comment by sanket-bhalerao** [comment]
@bpasero @deepak1556 , 
the insiders' instance has started working again. I did the following steps.

1. uninstall insiders
2. remove the ~insiders/extensions
3. restart the system 
4. download the fresh installer and install
5. enable setting sync to get back all the settings and extensions.
so far insiders' is running fine the blank window issue is not coming.

**Comment by sanket-bhalerao** [comment]
@bpasero i am facing this issue again.

**Comment by sanket-bhalerao** [comment]
@bpasero , @deepak1556 

I am using this on an office laptop and not comfortable sharing the logs publically.
can you please provide an email address where I can share the logs?

**Comment by bpasero** [comment]
@sanket-bhalerao you can find my mail here: in the info about me https://github.com/bpasero

**Comment by sanket-bhalerao** [comment]
logs sent over mail.

**Comment by bpasero** [comment]
@sanket-bhalerao thanks, I forwarded the logs to @deepak1556 

At first glance I do not see something obvious, in fact the workbench seems to be perfectly functional. When this log was created, was the window empty the entire time?

**Comment by deepak1556** [comment]
Don't see any renderer crash or exception from workbench either, except for some ENOENT from shared process when syncing extensions. @bpasero does settings sync feature try to perform extension sync even when `--disable-extensions` is passed ?

@sanket-bhalerao can you perform https://github.com/microsoft/vscode/issues/114459#issuecomment-765586385 without enabling settings sync feature. Also for `--user-data-dir` use some absolute path other than `.`, also make sure the directory is writable.

**Comment by bpasero** [comment]
@deepak1556 I am not sure, please ask @sandy081

**Comment by sanket-bhalerao** [comment]
> @sanket-bhalerao thanks, I forwarded the logs to @deepak1556
> 
> At first glance I do not see something obvious, in fact the workbench seems to be perfectly functional. When this log was created, was the window empty the entire time?

i kept the window on for 3-4 hours and it was blank the whole time.

**Comment by sanket-bhalerao** [comment]
> 
> @sanket-bhalerao can you perform [#114459 (comment)](https://github.com/microsoft/vscode/issues/114459#issuecomment-765586385) without enabling the settings sync feature. Also for `--user-data-dir` use some absolute path other than `.`, also make sure the directory is writable.

@deepak1556 i tried the command 
>code-insiders --verbose --disable-extensions --disable-gpu --user-data-dir D:\user\study\test
I am not sure how to disable the setting sync (I have installed this insiders instance fresh so I doubt sync will be enabled in this)
The output is same in this case as well (i.e. a blank window)
sending the log file to @bpasero .

**Comment by sanket-bhalerao** [comment]
log file "insiders-2.log" send to @bpasero

**Comment by bpasero** [comment]
@sanket-bhalerao does this reproduce with any folder you open? E.g. from the command line try "code <path to folder>" or even "code -n" to enforce opening an empty folder. Does the window turn blank right from the beginning or only later? When you test this always make sure you have restarted your OS to ensure there is no ghost instance behind.

**Comment by sanket-bhalerao** [comment]
@bpasero 
-reproduce with any folder -> yes
-`code-insiders -n` -> results in the same blank window
-window is blank from the beginning
-tested this with system restart as well.

**Comment by sandy081** [comment]
> does settings sync feature try to perform extension sync even when --disable-extensions is passed ?

@deepak1556  Yes.

**Comment by sanket-bhalerao** [comment]
@bpasero I'm still facing this issue. 
is there any other information needed from my side as this issue is closed with "needs more information".

in order to use vscode I have to
- uninstall vscode completely
- restart the system
- download and install the fresh copy from the vscode site.

this is my new morning ritual now 😂

**Comment by bpasero** [comment]
@sanket-bhalerao so it always works fine with a fresh install and then starts to stop working after a while?

**Comment by sanket-bhalerao** [comment]
@bpasero most of the time it works fine with a fresh install. 
if I keep the instance on throughout the day it will keep working fine for the whole day, the blank window will usually come either if the instance is restarted or the system is restarted.

Note: I am facing this only on my windows laptop, on MacBook Pro vscode run without this issue.

**Comment by bpasero** [comment]
@sanket-bhalerao you mentioned that you also cannot reproduce when you disable all your extensions is that still true?

**Comment by sanket-bhalerao** [comment]
@bpasero the issue can be reproduced with all the extensions disabled.

**Comment by doctorkelp** [comment]
I'm also affected by this. I've tried `--disable-gpu` and `--disable-extensions`

**Comment by Sciroccogti** [comment]
> I'm also affected by this. I've tried `--disable-gpu` and `--disable-extensions`

I also have the same situation. It works well before `1.53.0`, but stays blank window in `1.53.0`.

**Comment by deepak1556** [comment]
Can anyone try https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and check if any crash reports are generated, if so please attach them. Thanks!

**Comment by deepak1556** [comment]
Also does it help when you launch with `--disable-features=CalculateNativeWinOcclusion` ?

**Comment by YuSyuan1208** [comment]
> Also does it help when you launch with `--disable-features=CalculateNativeWinOcclusion` ?

it works, thanks.

**Comment by deepak1556** [comment]
> Also does it help when you launch with --disable-features=CalculateNativeWinOcclusion ?

> it works, thanks.

Great, thanks for confirming. This was originally reported in upstream https://bugs.chromium.org/p/chromium/issues/detail?id=1139022, looks like it didn't fix the above scenarios.

Next step would be to get a reliable repro, can anyone provide a video recording of the issue.

**Comment by sanket-bhalerao** [comment]
@deepak1556 please check the screen capture.

![recording](https://user-images.githubusercontent.com/9264813/107320300-7097d680-6ac6-11eb-9e55-b70a27cd0934.gif)

**Comment by GrooveGod** [comment]
Hello all.  After upgrading to `1.53.2` I was still getting the plain black window as reported on #116049.  Since `code --disable-gpu` works for now, I set `"disable-hardware-acceleration": true,` in `argv.json`.  Let me know if you want any ERRORs from the verbose output.

**Comment by gjsjohnmurray** [comment]
@GrooveGod if you resize the blank window fractionally by dragging an edge does it paint properly?

**Comment by Rc-Cookie** [comment]
I am also experiencing this bug, on both VS Code and Insiders, for any 1.53.x . For me reinstalling did not help, I care to restart my machine regularly. It always works for ~3 windows are opened since VS Code was, then I get the freeze. This does not need to be more VS Code instances.
Also, if VS Code freezes while it was open (because another window was opened) I don't get the blackscreen. It rather freezes the current window's look. Thus, it seems like graphics are simply not updating no more

**Comment by sanket-bhalerao** [comment]
> @GrooveGod if you resize the blank window fractionally by dragging an edge does it paint properly?

@gjsjohnmurray, yes, even after resizing the blank window it stays blank there is no change.

i find that if I use `code-insiders --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` from command prompt VSCode starts as expected. Frankly, I do not know what  `--disable-features=CalculateNativeWinOcclusion`  option does and what are its side effects, however, it lets me start VSCode and continue my work without any (so far) issues.

I am adding the command to the original issue as a workaround so others don't have to go through the entire thread to get VSCode working.
NOTE: please let me know in case  `code-insiders --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` is not working for you or you are using a different way to get around this issue. so I can add it to the issue for others' convenience.

**Comment by reidnax** [comment]
> Also does it help when you launch with `--disable-features=CalculateNativeWinOcclusion` ?

life saver

**Comment by Vodorok** [comment]
I've also got this issue, when starting a capture session in the Xbox Game Bar. When I start the capture the VS Code gui freezes. When closed, then reopened I get the same dark square that's referenced before. The issue disappears when ran with the `--disable-features=CalculateNativeWinOcclusion`. The issue also disappears when the capturing is stopped.

**Comment by zwwtj2014** [comment]
> Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`
> 
> If that helps, you can permanently configure this option via:
> 
> * Command Palette search for "Configure Runtime Arguments"
> * Set `disable-hardware-acceleration: true`
> * Restart

it works, thanks

**Comment by sanket-bhalerao** [comment]
@bpasero hi, getting this issue again after the latest update (updated just few mins ago).

**Comment by Elias-Graf** [comment]
Having the same issue on:

```
Linux pop-os 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
VS Code version:
```
30dcb112b46595657695d14c2cd6a37f783fbed2
x64
```

<details>
<summary>code-insiders --verbose:</summary>
<pre>
[main 2021-04-07T10:55:31.353Z] Starting VS Code
[main 2021-04-07T10:55:31.354Z] from: /usr/share/code-insiders/resources/app
[main 2021-04-07T10:55:31.354Z] args: {
  _: [],
  diff: false,
  add: false,
  goto: false,
  'new-window': false,
  'reuse-window': false,
  wait: false,
  help: false,
  'list-extensions': false,
  'show-versions': false,
  version: false,
  verbose: true,
  status: false,
  'prof-startup': false,
  'prof-v8-extensions': false,
  'disable-extensions': false,
  'disable-gpu': false,
  telemetry: false,
  debugRenderer: false,
  logExtensionHostCommunication: false,
  'skip-release-notes': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-keytar': false,
  'disable-crash-reporter': false,
  'crash-reporter-id': 'f36c4516-cce9-4302-828c-929970d3eabb',
  'skip-add-to-recently-opened': false,
  'unity-launch': false,
  'open-url': false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  force: false,
  'do-not-sync': false,
  trace: false,
  'force-user-env': false,
  'force-disable-user-env': false,
  'open-devtools': false,
  __sandbox: false,
  'no-proxy-server': false,
  nolazy: false,
  'force-renderer-accessibility': false,
  'ignore-certificate-errors': false,
  'allow-insecure-localhost': false,
  logsPath: '/home/elias/.config/Code - Insiders/logs/20210407T125531'
}
[main 2021-04-07T10:55:31.355Z] Resolving machine identifier...
[main 2021-04-07T10:55:31.356Z] Resolved machine identifier: 92355cab41b107a04c319aa40ad56f59fb81156b1b63d02c32283baddd417a2b
[main 2021-04-07T10:55:31.360Z] Main->SharedProcess#connect
[main 2021-04-07T10:55:31.380Z] StorageMainService: creating global storage
[main 2021-04-07T10:55:31.380Z] lifecycle (main): phase changed (value: 2)
[main 2021-04-07T10:55:31.381Z] windowsManager#open
[main 2021-04-07T10:55:31.381Z] windowsManager#open pathsToOpen [
  {
    workspace: { id: '82573d819aee4b54ea5655c12a7f1e8a', uri: [m] },
    exists: true
  }
]
[main 2021-04-07T10:55:31.382Z] IPC Object URL: Registered new channel vscode:92f037ef-38f6-412c-ae47-d952ee201c42.
[main 2021-04-07T10:55:31.383Z] window#validateWindowState: validating window state on 2 display(s) { mode: 1, x: 340, y: 308, width: 1909, height: 1132 }
[main 2021-04-07T10:55:31.383Z] window#validateWindowState: multi-monitor working area { x: 0, y: 44, width: 2560, height: 1396 }
[main 2021-04-07T10:55:31.383Z] window#ctor: using window state { mode: 1, x: 340, y: 308, width: 1909, height: 1132 }
[main 2021-04-07T10:55:31.383Z] window#ctor: vscode-file:// protocol is explicitly disabled
[main 2021-04-07T10:55:31.461Z] StorageMainService: creating workspace storage (82573d819aee4b54ea5655c12a7f1e8a)
[main 2021-04-07T10:55:31.461Z] windowsManager#open used window count 1 (workspacesToOpen: 0, foldersToOpen: 1, emptyToRestore: 0, emptyToOpen: 0)
[main 2021-04-07T10:55:31.463Z] lifecycle (main): phase changed (value: 3)
[main 2021-04-07T10:55:31.463Z] update#setState idle
[main 2021-04-07T10:55:31.464Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
(node:9663) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-04-07T10:55:31.560Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[9663:0407/125531.567344:INFO:CONSOLE(1)] "Uncaught (in promise) ReferenceError: s is not defined", source: file:///usr/share/code-insiders/resources/app/out/bootstrap.js (1)
</pre>
</details>

I may lauch vs-code using `code-insiders --user-data-dir .` but my configuration seems to be gone (I'm not an experienced with the workings of vs-code).

**Comment by bpasero** [comment]
As a workaround, deleting the `Code Cache` folder in the user data dir should also help.

**Comment by Springrbua** [comment]
I just updte my insider instance and now I get a blnak screen. Starting with `--user-data-dir path/to/some/empty/dir` works but ofc, I loose all my configurations.

> As a workaround, deleting the Code Cache folder in the user data dir should also help.

Where is the user data dir located by default?

**Comment by Elias-Graf** [comment]
@bpasero I deleted one in `~/Code Cache` and one in `~/.vscode-insiders/Code Cahce`, still not working.

**Comment by bpasero** [comment]
@Elias-Graf what do you get when you run `code-insiders --open-devtools` in the console?

**Comment by Elias-Graf** [comment]
@bpasero I think the same bootstrap error I had in the `--verbose` log.

```
Uncaught (in promise) ReferenceError: s is not defined
    at Object._ [as enableASARSupport] (bootstrap.js:48)
    at Object.h [as load] (bootstrap-window.js:63)
```

**Comment by bpasero** [comment]
Yeah looking into a solution. The easiest to get out of this is to delete the `Code Cache` folder:

* **Windows** `%APPDATA%\Code - Insiders\Code Cache`
* **macOS** `$HOME/Library/Application Support/Code - Insiders/Code Cache`
* **Linux** `$HOME/.config/Code - Insiders/Code Cache`

**Comment by Rc-Cookie** [comment]
> 
> 
> As a workaround, deleting the `Code Cache` folder in the user data dir should also help.

Didn't work for me

**Comment by gjsjohnmurray** [comment]
@Rc-Cookie have you updated to 1.55.1 yet?

**Comment by Rc-Cookie** [comment]
No, didn't know about the update
