### ISSUE TITLE
VS Code can't recognize some Unicode

### ISSUE THREAD

**Issue by Cloudwu1** [Microsoft/vscode#11441]
- VSCode Version: 1.4
- OS Version: Win10 10.14393

In Visual Studio
![capture1](https://cloud.githubusercontent.com/assets/21057022/18200418/5228da60-7137-11e6-8e3a-975ba312a733.PNG)

In VS Code
![vscode](https://cloud.githubusercontent.com/assets/21057022/18200336/ec86297e-7136-11e6-8246-c68501a1d1d2.PNG)

Below is the strings I use:
	   string s02 = "_㐀㒣㕴㕵㙉㙊䵯䵰";
	   string s03 = "ꀀꒌꂋꂌꂍꂎꂔꂕ꒐";
	   string s04 = "啊齄丂狛狜隣郎隣兀﨩"
	   string s05 = "АЯаяāɡㄅㄩ─╋︵﹄︻︱︳︴ⅰⅹɑɡ〇〾⿻⺁䜣€";
	   string s06 = "Ext-A 㐀㒣㕴㕵㙉㙊䵯䵰䶴䶵 ";
	   string s07 = "Ext-B 𠀀𠀁𠀂𠀃𪛑𪛒𪛓𪛔𪛕𪛖 ";
	   string s08 = "Mongolian ᠀᠐᠙ᠠᡷᢀᡨᡩᡪᡫ ";
	   string s09 = "Tibetan ༀཇཉཪཱྋ྾࿌࿏ྼྙ ";
 	   string s10 = "Yi ꀀꒌꂋꂌꂍꂎꂔꂕ꒐ ";
	   string s11 = "Uighur ،؟ئبتجدرشعەﭖﭙﯓﯿﺉﺒﻺﻼ";
	   string s12 = "Tai Le ᥐᥥᥦᥧᥨᥭᥰᥱᥲᥴ ";

**Comment by bpasero** [comment]
If the file is not UTF-8 you have to set the right encoding in settings. Closing, but let me know otherwise if that does not help.
