### ISSUE TITLE
On edit->paste operation text gets pasted into multiple files

### ISSUE THREAD

**Issue by veljkomilj** [microsoft/vscode#114475]
This has been an issue that I have observed on random since I started using Visual Studio Code. I occasionally find my source code polluted with random text. I cant reproduce this again but I still wanted to share because the issue is vary destructive and annoying.

So what happens is that occasionally on pasting text into tab that is currently in focus, the text will also get inserted into files that are in other tabs.

I don't know how to provide a proper repro because this happens on random. In average I experience this issue one in every two days.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform and list of extensions. Help\About is a good source of some of this information. If you had used Help\Report Issue it would have included all this automatically in the new GH issue.
