### ISSUE TITLE
Published extension does not show up in search

### ISSUE THREAD

**Issue by mrakgr** [microsoft/vscode#114460]
This issue does not happen for me personally, so I'll skip filling in my own info.  I recently published Spiral to VS Code marketplace and got [a report](https://github.com/mrakgr/The-Spiral-Language/issues/17) that it does not show up in the search tab.

The user who made the report is using Arch Linux, and just recently installed VS Code.

Any idea what could be going on here?

**Comment by gjsjohnmurray** [comment]
That may be a Linux distribution whose VS Code package gets built to use Open VSX for its extension repository rather than the Microsoft one. Do you publish your extension there too?

**Comment by mrakgr** [comment]
No. Never heard of it before.

**Comment by mrakgr** [comment]
I've just published [Spiral on OVSX](https://open-vsx.org/extension/mrakgr/spiral-lang-vscode). Hopefully that should deal with the issue. I'll reopen it if that did not work for the user.
