### ISSUE TITLE
[html] adopt TypeScript semantic highlighting

### ISSUE THREAD

**Issue by ImRodry** [microsoft/vscode#114477]
Issue Type: <b>Bug</b>

Example code:
```js            
                array.forEach(element => {
                const [key, ...valueArr] = element.split('=')
                const value = valueArr.join('=')
                if (key && value) result[key] = value
            });
```
key and valueArr should be highlighted in dark blue outside of the line where they're declared. Instead, they show as light blue, the color of a var/undeclared variable.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.89GB (4.98GB free)|
|Process Argv|D:\\Users\\rodri\\Documents\\GitHub\\hypixel-translators-bot --crash-reporter-id 1aa51578-c79e-468f-b062-c24334e21918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-crowdin|Cro|1.0.6
vscode-lombok|Gab|1.0.1
discord-vscode|icr|4.1.0
csharp|ms-|1.23.8
gradle-language|nac|0.2.3
vetur|oct|0.31.3
java|red|0.73.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
minecraft-lang-colorizer|zz5|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspyt653:30244269
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30241727

```

</details>

**Comment by mjbvz** [comment]
Here's what I see once semantic highlighting kicks in:

<img width="889" alt="Screen Shot 2021-01-26 at 10 06 46 PM" src="https://user-images.githubusercontent.com/12821956/105950170-ca0df900-6022-11eb-91bc-8a43ac194d53.png">


Did you perhaps disable semantic highlighting?

**Comment by ImRodry** [comment]
> Here's what I see once semantic highlighting kicks in:
> 
> <img alt="Screen Shot 2021-01-26 at 10 06 46 PM" width="889" src="https://user-images.githubusercontent.com/12821956/105950170-ca0df900-6022-11eb-91bc-8a43ac194d53.png">
> 
> Did you perhaps disable semantic highlighting?

If this was enabled by default then I didn’t touch it but otherwise I may need to enable it, can you tell me where to find that option? Also did tou get that behavior in the same vscode build?

**Comment by ImRodry** [comment]
I had semantic highlighting configured by theme so I set it to true and I'm still getting the same behavior

**Comment by mjbvz** [comment]
Did you test with just the snippet you shared using the default Dark+ theme?

**Comment by ImRodry** [comment]
> Did you test with just the snippet you shared using the default Dark+ theme?

Yep, I tested with that exact same code and using the same settings as before with the only difference being the one I mentioned before. Here are my semantic highlighting settings in case that helps
![image](https://user-images.githubusercontent.com/38259440/106043060-c8513d80-60d5-11eb-8cea-a1e5b0cfdfeb.png)

**Comment by mjbvz** [comment]
* Are you using a workspace version of TypeScript?
* What is the language mode of the file? This is shown in the status bar on the right side

**Comment by ImRodry** [comment]
This file was written in HTML and the script is in JavaScript, not sure what you mean by the first question

**Comment by mjbvz** [comment]
Ah ok. Semantic highlighting for JavaScript is only supported in JS files right now, not JavaScript embedded in html

**Comment by ImRodry** [comment]
Are there any plans to support it in the near future?

**Comment by aeschli** [comment]
Sorry, don't know when I'll get to that.
