### ISSUE TITLE
Navigate to module member definition from module.exports object having shorthand property values

### ISSUE THREAD

**Issue by humkins** [microsoft/vscode#114456]
I'm not sure whether this is an improvement or a bug, but current VSCode behaviour is a bit strange. Here is an example

```js
const foo = params => {}
const bar = params => {}

const someStructure = {
  foo, // here its definition is navigable!!!
}

module.exports = {
  foo, // can't navigate to the definition
  bar: bar, // can navigate to the definition
}
```

Why is it not possible to navigate to `foo` definition by CTRL+click from `module.exports` whereas it is possible to do that from `someStructure`?

VSCode 1.52.1, Linux

**Comment by humkins** [comment]
Hello, can you please clarify is it unimplemented functionality or a bug?

**Comment by jcuffe** [comment]
Hello, would also like the answer to this! VSCode has broken my workflow with this change - I am absolutely certain that this method of navigation was possible as little as a month ago, as I have been using it to navigate the codebase of an ES5 Express project at work.

**Comment by mjbvz** [comment]
This already seems to be fixed in TypeScript nightly builds. You can test `typescript@next` by installing [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) 

We will pick up TS 4.2 (the currently nightly version) for VS Code in February

**Comment by humkins** [comment]
Hi @mjbvz , but what about vanilla JS?

**Comment by mjbvz** [comment]
The TypeScript project powers both JS and TS intellisense.

Test it out using the linked extension
