### ISSUE TITLE
Add the abitlity to drag and drop variables in the debugging panel to the watch 

### ISSUE THREAD

**Issue by QDelage** [microsoft/vscode#114488]
In the debugging panel, I think it could be useful to have the ability to drag and drop variables from the "variables" part to the "watch" part, and/or at least to autocomplete when writing them there.
![Screenshot_20210117_135122](https://user-images.githubusercontent.com/46454342/104843635-f790cf00-58cb-11eb-91d9-1ffafb55fcea.png)
As an example, on the picture above, I had to write these expressions by hand, I think it could have been better to drag and drop the variables (and then modify them to have the indexes I need etc.) or to autocomplete them.

**Comment by isidorn** [comment]
Currently you can Right Click -> `Add to Watch` for this functionality.
Though Drag and Drop is a fair feature request, thus assigning to Backlog as we have no immediate plans to work on this.

**Comment by QDelage** [comment]
> Currently you can Right Click -> `Add to Watch` for this functionality.
> Though Drag and Drop is a fair feature request, thus assigning to Backlog as we have no immediate plans to work on this.

Okay actually I didn't even notice, so thank you!
But yes of course it is absolutely not a priority request, it can wait.
