### ISSUE TITLE
Fast duplicate + rename issue

### ISSUE THREAD

**Issue by ChezMose** [microsoft/vscode#114426]
- VSCode Version: 1.52.1
- OS Version: Window 10

Steps to Reproduce:

1. In the explorer, duplicate a file with Ctrl+C, Ctrl+V
2. Immediately try to rename it by clicking F2

What happens: the file name gets editable for a few ms then becomes unselected.
Note that if you wait for > 2s between step 1 and step 2, the issue does not occurs.

This is a regression as it always worked and was the fastest way to create a file (in my team).
I won't call that a critical issue, it's more a productivity reduction issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Fixed in latest insiders
