### ISSUE TITLE
Windows 10: integrated terminal cut off to the top

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11457]
I am on latest insider and when I open the integrated terminal I see the top is being cut off:

![image](https://cloud.githubusercontent.com/assets/900690/18206750/53fedbb4-7128-11e6-9e97-2556728af95b.png)

Not happening in 1.4:

![image](https://cloud.githubusercontent.com/assets/900690/18206758/631a5be6-7128-11e6-9bc0-b352c7f4505c.png)

**Comment by Tyriar** [comment]
Duplicate #11184
