### ISSUE TITLE
Cannot format C# code

### ISSUE THREAD

**Issue by MagicalLeaf** [microsoft/vscode#114560]
Recently I am using VS code to write a little C# code, but I found that I cannot format the C# code.
Every time when I use the shortcut keys, the lower right corner will prompt me "There is no formatter for'csharp' files installed.". In fact, I installed Microsoft's C# plug-in, and the code can still be formatted normally the last time I used VS Code to write C# (about a month ago).
I tried to find a solution from the forum, but I tried five different solutions (including changing settings, changing setting.json, clearing user configuration and uninstalling and reinstalling) and four different C# plugins (ms-dotnettools. csharp, aaron-bond.better-comments, gaoshan0621.csharp-format-usings, simonsiefke.prettier-vscode) still cannot solve this problem.
And I asked my colleagues and found that at least four colleagues encountered the same problem (I only asked four colleagues). And other languages ​​can be formatted normally, such as JavaScript, HTML, SQL, etc. I feel a little confused about this. C# is Microsoft's, and VS Code is also Microsoft's. They shouldn't have any conflicts.

**Comment by yangbing007** [comment]
I disabled all extensions except `ms-dotnettools.csharp`, but it still doesn’t work!!!So disappointed!!!
