### ISSUE TITLE
tests are not discoverd

### ISSUE THREAD

**Issue by aragong** [microsoft/vscode#114526]
Issue Type: <b>Bug</b>

I am having problems with loading the test files using unittest framework. They do not load. I made the configuration but the tests are not detected, I attached a test example:

```
import os

from teseo_model.environment import Environment

import unittest

class Test_Environment(unittest.TestCase):
    def test_init(self, project):
        self.assertIsNotNone(Environment(project="SICMA"))
```

VS Code version: Code - Insiders 1.53.0-insider (eaa959d34b863dec932077d94daece22504a396b, 2021-01-18T05:13:25.733Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3412)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (8.71GB free)|
|Process Argv|--crash-reporter-id dcc88fd9-fed3-4050-a9e9-4928cc13bd3d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.14
vscode-pull-request-github|Git|0.22.0
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600cf:30241728
core-portspanel:30233467

```

</details>

**Comment by IllusionMH** [comment]
/extPython

VS Code doesn't provide support for Python/tests out of the box and it's up for extensions to provide this functionality.
You need to make sure that you have proper setup required by extension or raise an issue in extension repo.
