### ISSUE TITLE
can not automatically change focus on terminal

### ISSUE THREAD

**Issue by Primimy** [microsoft/vscode#114529]
- VSCode Version: 1.53.0-insider (system setup)
eaa959d34b863dec932077d94daece22504a396b
- OS Version:Windows_NT x64 10.0.18363

Steps to Reproduce:

1.Open a file and run it, but the it cannot change focus on terminal automatically.

Does this issue occur when all extensions are disabled?: Yes

Tested with same settings(default) on VSCode 1.52.1 stable, and it works good.

**Comment by meganrogge** [comment]
Not sure what you mean. Please upload a [gif](gifcap.dev) with screen cast mode enabled

**Comment by Primimy** [comment]
1.In VSCode insider version,after editing I press F5 to run a file, but the focus will not change from editor to terminal, it needs mannally press "Ctrl+`" to change focus on it.
2.This will not happen in VSCode stable version, here is a gif in stable version.

![20210118 cpp - Cpp - Visual Studio Code 2021-01-20 09-22-57 mp4_2](https://user-images.githubusercontent.com/38491737/105116189-35c50300-5b05-11eb-91f7-315fff74919f.gif)
