### ISSUE TITLE
Large word spacing in Source Control and Extensions

### ISSUE THREAD

**Issue by sant123** [microsoft/vscode#114503]
- VSCode Version: 1.52.1
- OS Version: Fedora 33 / KDE 5.20.5

Steps to Reproduce:

1. Open `Search` and type this `||| ||| |||`:

![image](https://user-images.githubusercontent.com/7959437/104856920-22d2e880-58e3-11eb-8445-62c5f3ee1388.png)

2. Now open `Source control` and type this `||| ||| |||`:

![image](https://user-images.githubusercontent.com/7959437/104856944-45650180-58e3-11eb-894c-eaa32ab5d1da.png)

Note the space width between the pipes, is this expected? The same happens in `Extensions`

Does this issue occur when all extensions are disabled?: Yes

Thanks.

**Comment by misolori** [comment]
@eamodio is this because SCM and Extensions are using intellisense, which means they are different elements (monaco) than Search (text area)?

**Comment by eamodio** [comment]
Ah, yeah, that must be why.

**Comment by lszomoru** [comment]
I am unable to reproduce this with the latest version of VS Code Insiders. @sant123, please feel free to reopen in case I missed something. Thanks! 

![Image](https://user-images.githubusercontent.com/3372902/206751791-37dc15ed-1374-4253-b0c4-98c2636bf01a.png)

![Image](https://user-images.githubusercontent.com/3372902/206751877-74c257cb-6f3a-470b-b197-63a7fcbec2b2.png)
