### ISSUE TITLE
Simple browser brakes the Github login

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#114543]
- have the setting
```json
        "workbench.externalUriOpeners": [
		{
			"uri": "*",
			"id": "simpleBrowser.open"
		}
	],`
```
- try to login to the Github account
- the simple browser shows up with `https://vscode-auth.github.com/authorize/?callbackUri%3Dvscode...` as URL. No content, the login flow is broken.

Maybe it was not clever to set `"uri": "*"` but how would a user know?

**Comment by mjbvz** [comment]
The GitHub auth extension was calling `env.openExternal` here.

In general, I think that there will be other extensions that do not want calls to `openExternal` to go to a contributed opener. Therefore, I've disabled contributed openers by default in both external calls to `env.openExternal` and for most internal callers to our opener service (except for places where the user clicks on a link in an editor or in documentation)
