### ISSUE TITLE
Auto-completion for `import from '..'` file address

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11454]
It would be nice if editor provided auto completion for `import from` file names

![image](https://cloud.githubusercontent.com/assets/736697/18206189/fc11d1ba-713e-11e6-93a6-dd9ff88e52d5.png)

**Comment by dbaeumer** [comment]
This is on the plan for TS. see https://github.com/Microsoft/TypeScript/pull/9353
