### ISSUE TITLE
Removing a contributes.keybindings rule by keybindings.json

### ISSUE THREAD

**Issue by kasecato** [microsoft/vscode#114536]
I want to remove the `contributes.keybindings` by `keybindings.json`.

The use case is to load settings from an external file into the key mapping extension and overwrite the default `package.json`'s `contributes.keybindings` setting with `keybindings.json`.

### package.json
```json
    "contributes": {
        "keybindings": [
            {
                "key": "shift+f6",
                "mac": "shift+f6",
                "command": "editor.action.rename",
                "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
            },
```

### keybindings.json (Not working: macOS, Version: 1.52.1)
```json
[
            {
                "key": "-shift+f6",
                "mac": "-shift+f6",
                "command": "editor.action.rename",
                "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
            },
]
```

- "contributes.keybindings", https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings
- "Removing a specific key binding rule", https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule
- "is it possible to import myown custom keymap from Intellij Idea to vscode?", https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/120
- "importer", https://github.com/kasecato/vscode-intellij-idea-keybindings/pull/194

**Comment by IllusionMH** [comment]
It should be 
```json
{
    "key": "shift+f6",
    "command": "-editor.action.rename"
     ...
}
```

`-` attached to `command`, not `key`. I don't think that `keybindings.json` has differentiation between `key` and `mac`, because they are for final user with currently set keybindings for OS.

**Comment by kasecato** [comment]
Thank you. It worked so well.
