### ISSUE TITLE
FAIL IN REFRESHING FILES USING WSL

### ISSUE THREAD

**Issue by juancamilocorralesosvath** [microsoft/vscode#114541]
Issue Type: <b>Bug</b>

My problem is that when I'm using my subsistem, everytime i add a new file or folder, it won't show up on VS code, I need to close the window and reopen it to show the desire files or folders. In order to reproduce it, for instance the famous npx create-react-app <folder>, when I do this, everything works fine, but the created folder won't show up, so as I said, I need to close the window and reopen it. Thanks! God bless you!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.40GB free)|
|Process Argv|. --crash-reporter-id c05eeb9d-e027-4b0e-9fc6-fccfad597a44|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|6.07GB (5.54GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
remote-wsl|ms-|0.52.0
material-icon-theme|PKi|4.5.0
open-in-browser|tec|2.0.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
beautify|Hoo|1.5.0
vscode-language-babel|mgm|0.0.30
LiveServer|rit|5.6.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
vstes627:30244334
pythonvspyt600:30241727

```

</details>

**Comment by aeschli** [comment]
Are the files on `/mnt/c` ?

**Comment by juancamilocorralesosvath** [comment]
thank you for answering! hmm I don't think so, you'll see, I open two windows in the VS Code: the same folder, both in windows and with ubuntu which is the subsystem I have. When I add a file when I'm on the windows one, it doesn't appears on the WSL one. Nevertheless, when I add a file being on the WSL one, it does appears on the windows one!

**Comment by juancamilocorralesosvath** [comment]
![problem-normal-window](https://user-images.githubusercontent.com/61639827/104964787-2762d400-59ab-11eb-8ac1-5b53a89ad3d4.png)
![problem-WSL-window](https://user-images.githubusercontent.com/61639827/104964800-2df14b80-59ab-11eb-9b43-e6c0fb04537c.png)

**Comment by juancamilocorralesosvath** [comment]
there you can see what I told you

**Comment by juancamilocorralesosvath** [comment]
(the sass one on the WSL does appears on the normal window, but the hello.js file won't appear in WSL, to do so I need to close the window and reopen it)

**Comment by isidorn** [comment]
@aeschli assigning first to you since the bot auto assigned me, feel free to forward back to me

**Comment by aeschli** [comment]
Thanks for the screenshots. So yes, your files are on `/mnt/c`. What you see is a known issue with WSL that file events on `/mnt/c` are not coming through.
https://github.com/microsoft/vscode-remote-release/issues/3959

I think you can just click on refresh in the file explorer as a workaround.
The best way to work with WSL is if you keep your project in the Linux file system (e.h. `/home/youruser/`).

Closing as dup of https://github.com/microsoft/vscode-remote-release/issues/3959

**Comment by juancamilocorralesosvath** [comment]
Alright! damn I'm sorry haha, thank you very much! God bless you!
