### ISSUE TITLE
Css property doesn't work correctly 

### ISSUE THREAD

**Issue by karinacrmcldev** [microsoft/vscode#114546]
Issue Type: <b>Bug</b>

When i have a lot of text **without spaces** in HTML div container
- css property "max-width" doesnt work on it. So i should add spaces in html, and then it works.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by IllusionMH** [comment]
/needsMoreInfo
Could you please specify how exactly it's related to the VS Code editor itself?
