### ISSUE TITLE
Cannot re/name entries in Explorer

### ISSUE THREAD

**Issue by TechNyquist** [microsoft/vscode#114573]
If I create a file or a folder, or try to rename one, I cannot achieve it because a focus trick or a refresh of Explorer panel makes text input field disappear automatically. This offending "refresh" occurs every about less than 5 seconds.
I'm not including extension info as I intentionally tried VSCode with --disable-extension and still occurs, so extensions responsibility is excluded.
I cannot still tell what is the real trigger to reproduce this, I just try the above in a workspace with tracking remote Git branch.
IDE/PC restart does not help.

![cannot_name](https://user-images.githubusercontent.com/5136855/105053241-0369c600-5a71-11eb-8b3f-89f06b47a36b.gif)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-38-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500T CPU @ 2.20GHz (6 x 3255)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|15.45GB (0.16GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id ed967029-172e-4fa0-bc68-10e4fcba0484|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Nxt3** [comment]
Same here.

```
Version: 1.53.0-insider
Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
Date: 2021-01-19T06:08:35.996Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by isidorn** [comment]
Fixed in latest vscode insdiers. Closing as duplicate

**Comment by daprahamian** [comment]
Is there an ETA on fixing this for non-insiders? I am currently on `1.52.1`, and am currently incapable of making new files or renaming files via the sidebar.

**Comment by ajhyndman** [comment]
Hi, I'm actually still able to reproduce this issue in the current insiders build, `v1.54.0-insiders`.

@isidorn Can we get a reference to the duplicate issue or commit that addressed this so we can follow along and/or contribute?
