### ISSUE TITLE
Getting Started: Allow `Link` buttons

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#114582]
Button contents should be able to open links in addition to running commands.

**Comment by JacksonKearl** [comment]
cc @digitarald add a reference example, basically:
```
					button: {
						title: localize('gettingStarted.video.button', "Open"),
						link: 'https://aka.ms/unknown'
					},
					doneOn: { eventFired: 'linkOpened:https://aka.ms/unknown' },
```

(Note: the `linkOpened` event type will only fire for links opened via `gettingStarted`, it doesn't listen to general vscode link opening)

**Comment by connor4312** [comment]
Verified the `Watch Tutorial` button
