### ISSUE TITLE
`${env:VARIABLE}` not work sometimes in `settings.json`

### ISSUE THREAD

**Issue by woobhurk** [microsoft/vscode#114515]
- VSCode Version:
    - 1.52.1 (Stable)
- OS Version:
    - Windows 10 Pro 20H2 (Build 19042.608)

Steps to Reproduce:

1. **The `${env:JAVA_HOME}` issue:**
    1. In `settings.json`, set `java.home` to `${env:JAVA_HOME}`, and `JAVA_HOME="D:\Program Files\Java\jdk8"`.
    2. Open a Java project.
    3. The extension `Language Support for Java (TM) ...` shows an error: `The java.home variable defined in Visual Studio Code settings points to a missing or inaccessible folder (${env:JAVA_HOME})`.
    4. Set `java.home` to `D:\\Program Files\\Java\\jdk8`, and no error message again.
    5. So why VS Code did not recognize the `JAVA_HOME` variable?
2. **The `${env:M2_HOME}` issue:**
    1. In `settings.json`, set `java.configuration.maven.userSettings` to `${env:M2_HOME}\\conf\\settings.xml`, and `M2_HOME="D:\Program Files\maven"`.
    2. Open a Java project.
    3. The maven starts to download all libraries into `$HOME\.m2`, but I already set the repository folder to `D:\app-data\maven` in `settings.xml`.
    4. Set `java.configuration.maven.userSettings` to `D:\\Program Files\\maven\\conf\\settings.xml`.
    5. Re-open the Java project, and Maven starts to download libraries into the correct folder `D:\app-data\maven`.
    6. So why the specified `settings.xml` in variable reference did not work, and I have set to full path of Maven?

All the other variable references works well, such as `PYTHON_PATH`, except the above. Please tell me how to use variable references to set the `java.home` in right way.

Thank you very much! 

Does this issue occur when all extensions are disabled?: Yes/No
- I don't know. If I disable the Java extension, all the Java and Maven features will lose.

**Comment by sandy081** [comment]
Variables are not supported in settings. There is already a feature request for it, hence marking it as duplicate.
