### ISSUE TITLE
Workbench should not know about isNotebookEditor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114554]
I noticed a pattern has leaked into workbench core that smells like debt ([here](https://github.com/microsoft/vscode/blob/4e1eff7083ddd34a141d21c775f74e405338e56b/src/vs/workbench/browser/actions/navigationActions.ts#L229-L229) and [here](https://github.com/microsoft/vscode/blob/7aee2c7d45ea5affe83d0807d88e206ecfc65b25/src/vs/workbench/browser/parts/editor/editorStatus.ts#L1057-L1057)): 

```ts
const activeEditorPane = editorService.activeEditorPane as unknown as { isNotebookEditor?: boolean } | undefined;
if (activeEditorPane?.isNotebookEditor) {
...
```

Workbench core should not reach into `contrib` so this needs a proper cleanup with new concepts.

**Comment by jrieken** [comment]
Adding @isidorn for the first violation (this happened via https://github.com/microsoft/vscode/issues/107580)

**Comment by jrieken** [comment]
> Workbench core should not reach into contrib so this needs a proper cleanup with new concepts.

Wrt that we shouldn't make our lives harder than needed and we shouldn't shy away from moving the notebook editor into `src/vs/workbench/browser/parts/editor` or a similar place. Notebooks are becoming are workbench thing and if things like the editor status bar need to know about it then that's a viable option.

**Comment by bpasero** [comment]
Yeah I agree, I am fine having notebooks a core workbench thing.

**Comment by isidorn** [comment]
I have added that because that command needs to know where the focus is. And just checking if the editor part has focus was not working, so we needed a custom solution when the focus is in the notebook.
If there is a general way to check if any editor (including custom editors) has focus I would be happy to change the current code.
And I guess if we make Notebooks a core workbench thing then we are fine either way.

**Comment by bpasero** [comment]
@isidorn that sounds like something `IComposite` could provide, given we already have `onDidFocus` event there:

https://github.com/microsoft/vscode/blob/a825aaaa909ef33eee11cb1d322e9a64981978d2/src/vs/workbench/common/composite.ts#L11-L19

It seems to me then all that is missing would be a `hasFocus` property there?

**Comment by isidorn** [comment]
@bpasero good idea, I have introduced a `Composite.hasFocus` and could adopt this succeffully. So now we no longer have a dependency to Notebooks from here.
@rebornix the best way for me to check if a notebook editor has focus was using the `isAncestor` trick. Just using `this._widget.value.hasFocus()` did not work. Maybe you can siplify [this code](https://github.com/microsoft/vscode/blob/bc84f07dc53df37ed07aa33aa251b00ef0135a8f/src/vs/workbench/contrib/notebook/browser/notebookEditor.ts#L134) if there is a better approach.

**Comment by rebornix** [comment]
@isidorn you can leave that to me. I'll investigate what's the best generic way of expressing that.

**Comment by rebornix** [comment]
The workbench core currently is aware of binary editor, text editor and diff editor. It also has some knowledge of how to create custom editor input (for custom editor and notebook). We may want to move some notebook concept into `src\vs\workbench\common\editor.ts`  (like `INotebookEditorInput`, `INotebookEditorPane` which are counter parts of `IFileEditorInput` and `ITextEditorPane`), @bpasero would this make sense to you? 

cc @mjbvz as we may also want to lift custom editor there.

**Comment by bpasero** [comment]
@rebornix is there a generic concept we could extract to make this easier, similar to what Isi did? What do you need the `isNotebookEditor` for exactly?

**Comment by rebornix** [comment]
Removed `isNotebookEditor` completely across the workbench, to check if an editor control is notebook editor, we can compare the editor id with `NOTEBOOK_EDITOR_ID`. The only work left is extracted to https://github.com/microsoft/vscode/issues/117943, which filters out notebook editor by checking context keys. The ideal though is supporting Change Language in composite editors.

**Comment by rebornix** [comment]
We also discussed having notebook editor as the core concept in the workbench. After reviewing the code and refactoring, I found that we don't have to go that route, at least for now. We can still try to enforce using `isCompositeEditor` if possible.
