### ISSUE TITLE
Wrong keyboard command displayed for "Find in folder..." on MacOS

### ISSUE THREAD

**Issue by john-harding** [microsoft/vscode#114508]
- VSCode Version: 1.49.1
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Have any project open
2. Right click on a folder in the Explorer side bar and look for "Find in folder..."
3. Keyboard command listed is "Option" + "Shift" + "F".  Actual command is "Command" + "Shift" + "F"

<img width="247" alt="Screen Shot 2021-01-17 at 8 13 06 PM" src="https://user-images.githubusercontent.com/6278090/104862720-dfd43d80-5901-11eb-8ab3-3c33d3433846.png">

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by alexdima** [comment]
@john-harding You're on a few months old VS Code version (1.49 was released sometime in Sept 2020). Does the problem reproduce also in the latest VS Code?

**Comment by john-harding** [comment]
@alexdima I just installed 1.52.1, which it tells me is the latest (Dec 16th release).  The issue is still present.

**Comment by alexdima** [comment]
@john-harding Thank you. 

I have now tried on the mac, but it looks to me that the command is working fine. When I click in the explorer and move focus on a folder using arrow up and down and press `Shift+Option+F`, I get to see the Search viewlet with the folder path prepopulated in the search options (under "files to include"). This command from the context menu is called `filesExplorer.findInFolder`.

The above is a different command than `workbench.action.findInFiles` ("Search: Find in Files") which is bound by default to `Cmd+Shift+F` and which does not prepopulate the current selected folder in the search options.
