### ISSUE TITLE
VS Code Terminal does not display IRB output 

### ISSUE THREAD

**Issue by by-ron** [microsoft/vscode#114585]
Newbie here.. I'm trying out VS Code and am running into an issue. I've connected VS Code to WSL through remote connection and everything is running great expect for IRB.. When I open IRB in the Terminal and execute a command, the output is not displayed. If I open pry and execute a command, output is displayed as normal. Even weirder, when using IRB if I switch to the Output tab and then back to Terminal all the output is displayed. Examples below:

```
➜  ~ irb
3.0.0 :001 > 1 + 1

3.0.0 :002 > greeting = 'hello'

3.0.0 :003 > 
➜  ~ pry
[1] pry(main)> 1 + 1
=> 2
[2] pry(main)> greeting = 'hello'
=> "hello"
[3] pry(main)> 
```
If I copy the lines where IRB output is displayed and paste on newline, the output is exactly as expected. Any help would be awesome!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

**Comment by meganrogge** [comment]
Hey, can you try changing your renderer type in settings?

**Comment by by-ron** [comment]
Hey, added the following to my settings which worked:

```
{
    "terminal.integrated.rendererType": "experimentalWebgl"
}
```

Thanks!

**Comment by yyhmsg** [comment]
I'd like to open this again, I'm experiencing the same issue as the OP, but adding the settings.json doesn't work for me - well it sort of works:

without ..."exerpimentalWebgl"
irb(main)>4+5
[[[[ answer should be here and it isn't ]]]]
irb(main> 

with the "experimentalWebgl"
irb(main)>4+5
[[[[ still blank but if you actually click on the line then it appears, which is different from above ]]]]
irb(main)>

This is clearly a bug of some sort.  In my case I'm using this via wsl and it works fine in a standard terminal (i.e. not inside of vscode).

**Comment by by-ron** [comment]
@yyhmsg I actually abandoned VS Code due to this. The solution worked for about 2 days and then it began popping up intermittently. Mine is only affected while using via WSL2

**Comment by yyhmsg** [comment]
Yeah, I'm just using a wsl2 terminal next to the vscode editor for now.  I thought I had it "fixed" by using irb --simple-prompt and oddly, that worked until I quit the terminal and then when I restarted it was back to the same behavior.

**Comment by by-ron** [comment]
So I haven't been able to fix the issue by modifying settings but in the process I have uninstalled/re-installed VS Code twice. After the second re-install I haven't had a single issue! Terminal and irb have been working great with no issues after 48 hours
