### ISSUE TITLE
Extension pack dependencies are not respected when installing via the VS Code URI

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#114587]
Issue Type: <b>Bug</b>

1. Open a VSCode window
2. Open the uri vscode://shsuman.dummy-extension-main in the browser
3. VSCode will prompt you to install the Dummy Extension - Main
4. Install the Dummy Extension - Main (shsuman.dummy-extension-main)

This will install the Dummy Extension - Main but wouldn't install the Dummy Extension -Remote(shsuman.dummy-extension-remote) which is a part of the extension pack for the Dummy Extension - Main

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.42GB free)|
|Process Argv|--crash-reporter-id 611024cc-5acc-4121-a31a-6d32c5099117|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.1.3
tsl-problem-matcher|eam|0.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
vscode-azurestorage|ms-|0.11.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.1
jupyter|ms-|2020.12.414227025
vscode-ai|ms-|0.6.20-dev
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
azure-account|ms-|0.9.4
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3484
java|red|0.73.0
html-preview-vscode|tht|0.2.5
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30247033

```

</details>

**Comment by sandy081** [comment]
I tried it and it install both extensions for me. Can you please try to repro again and let me know the exact steps you follow. It would be helpful if you provide a gif.

**Comment by shsuman** [comment]
Yes, I am seeing the right behaviour now. For some reason, it wasn't working at the time
