### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by likwidgold09** [microsoft/vscode#114549]
We have written the needed data into your clipboard because it was too large to send. Please paste. During the installation process, I received a Deprecation warning. I left the screen alone as I did research and the installer appeared to finish without me entering a command. However, I am now having issues with git, within Visual Studio Code? I'm showing that it's not installed. I installed an extension for GitHistory, within Visual Studio Code, but it didn't solve the problem. Attached is a screenshot of the Deprecation Warning i received, before the installer finished, without me entering a command. 

<img width="851" alt="Screenshot 2021-01-18 155019" src="https://user-images.githubusercontent.com/77648091/104975961-b7137d00-59c1-11eb-88f3-c39f8ddd8071.png">

**Comment by likwidgold09** [comment]
Issue Type: <b>Bug</b>

During the installation process, I received a Deprecation warning. I left the screen alone as I did research and the installer appeared to finish without me entering a command. However, I am not having issues with git? i'm showing that it's not installed. I installed an extension for GitHistory, but it didn't solve the problem. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.14
gitlens|eam|11.1.3
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.8.0
vscode-graphql|Gra|0.3.13
vscode-styled-components|jpo|1.4.1
vsliveshare|ms-|1.0.3484
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773cf:30236630
vstes627cf:30244335
pythonvspyt600:30241727

```

</details>

**Comment by joaomoreno** [comment]
This is during the installation process of Visual Studio or maybe Build Tools, not VS Code.
