### ISSUE TITLE
Colors not consistent rendered according to theme specification

### ISSUE THREAD

**Issue by PiotrSokol** [microsoft/vscode#114591]
Insider version
- Version: 1.53.0-insider 
- Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
- Date: 2021-01-19T06:10:13.886Z
- Electron: 11.2.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0

Regular
- Version: 1.52.1
- Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
- Date: 2020-12-16T16:32:10.090Z
- Electron: 9.3.5
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0

- OS: Linux x64 5.4.0-62-generic
- nVidia driver: 460.32.03
- Ubuntu color space configuration: Standard RGB

The colors rendered by VSC are not consistent with the specification in any given theme.

E.g. tried out the "City Lights theme" in VSC and Atom (same author) and you can see the difference below
Steps to Reproduce:

1. VSCode
![image](https://user-images.githubusercontent.com/10500908/105087247-352a5f00-5a68-11eb-9267-56456629ae2e.png)

2. Atom
![image](https://user-images.githubusercontent.com/10500908/105087292-44111180-5a68-11eb-83d9-dae90c95ebbc.png)

This holds for any theme I've tried. 
Moreover, tried separately the fixes previously reported here, i.e.
```
	"disable-color-correct-rendering": false,
	"force-color-profile":"srgb",
	"disable-hardware-acceleration": true,
```
and no luck.

Does this issue occur when all extensions are disabled?: yes

**Comment by aeschli** [comment]
This is dup of https://github.com/microsoft/vscode/issues/24569.
VSCode interprets themes colors as sRGB, as used by browser, while TextMate (and probably Atom) interprets them as Apple RGB.

While we came from TextMate themes, VSCode color themes have become more than TextMate themes. We will stick with sRGB. 

As a consequence, when you convert a TextMate theme to a VSCode theme and you want to be 100% color compatible, a color conversion is necessary.
