### ISSUE TITLE
Improve the usability when working with multiple instances: Color schemes

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode#114555]
I use VSC on MacOS, Windows 10 and Linux for native applications development. I often need to open multiple unrelated projects/folders. I have a few suggestions:
1. Add different color schemes for different instances. This will make navigating between them easier. This can now be achieved by installing both standard and insider's preview versions.
2. Get rid of the caption/title bar like Visual Studio 2019 and Xcode do now. It just takes up space.

**Comment by joaomoreno** [comment]
This works? https://github.com/johnpapa/vscode-peacock
