### ISSUE TITLE
Expand Selection To Tag (Ctrl + Shift + A)

### ISSUE THREAD

**Issue by townivan** [Microsoft/vscode#11458]
Working with HTML, I found this "expand selection to tag" feature very useful on other editors.

I'd LOVE to have this on vscode!  Hopefully others agree.

![expand select to tag](https://cloud.githubusercontent.com/assets/6314163/18207095/a3097d58-70f7-11e6-88b8-06d718e96b5c.gif)

If your cursor is anywhere on the lorem line after the first < then Ctrl + Shift + A will select just lorem ipsum.

Then repeating that keystroke will expand the selection to the p tags, and then up the tree.

*Not sure how to add [feature-request] label :(

**Comment by aeschli** [comment]
We have 'expand selection' but it would expand only to the innermost tag. Anything we can do here, @jrieken ?

**Comment by jrieken** [comment]
Today it works with the tokens and brackets which isn't very reliable. I close this as a dupe of #4795 which is about getting this right

**Comment by ramya-rao-a** [comment]
You can use the `Emmet: Balance (outward)` command for html files to achieve this
