### ISSUE TITLE
Possible support for other MathJax separators

### ISSUE THREAD

**Issue by superkuvar** [microsoft/vscode#114565]
VS Code can work with MathJax out of the box without any extensions. I love this fact.

I use this code to create Jekyll with MathJax formulas, where VS Code supports MathJax render in Preview (CTRL+K V) mode.

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    jax: ["input/TeX","input/MathML","output/SVG", "output/CommonHTML"],
extensions: ["tex2jax.js","mml2jax.js","MathMenu.js","MathZoom.js", "CHTML-preview.js"],
TeX: {
  extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
},
  tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true,
      processEnvironments: true
    },
    "HTML-CSS": { availableFonts: ["TeX"] }
  });
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>
```

VS Code seams to understand `$` and `$$` formula enclosures but it is not working for _original_ enclosures:

* "\\(" ,   "\\)"
* "\\[",    "\\]" 
Can we somehow make this work as well.

![image](https://user-images.githubusercontent.com/58330327/105028439-503da480-5a51-11eb-96c7-a971c5e4f1e0.png)

**Comment by superkuvar** [comment]
I have just found that `$$` should work for inline cases also. Do you use Kramdown in VS Code preview?

Look the preview will not show this text highlighted in blue.

![image](https://user-images.githubusercontent.com/58330327/105083672-87ce4000-5a95-11eb-9c16-1577975e8e46.png)

While on GitHub page it works perfectly. Should I set this as a bug?

**Comment by mjbvz** [comment]
VS Code's  built-in markdown preview does not support math. See https://marketplace.visualstudio.com/items?itemName=koehlma.markdown-math for an example extension that adds math support

**Comment by superkuvar** [comment]
> VS Code's built-in markdown preview does not support math

I removed all the extensions and still latest VS Code preview ![image](https://user-images.githubusercontent.com/58330327/105170287-002c1400-5b1d-11eb-9bbd-e848ba77d4ee.png) shows math formulas. See above.

It may be the official statement VS Code doesn't support math but when you try it it works for:
* `$...$` 
* `$$...$$`

I just wonder if VS Code preview renders HTML where can I find the JavaScript to render math inside the preview. 
I would use JavaScript this for GitHub.

**Comment by superkuvar** [comment]
As for the "Markdown Math" plugin you mentioned it doesn't provide anything in addition to what VS Code offers.
Although it alters the behavior a bit (`$$` is not supposed to do inline math):

![image](https://user-images.githubusercontent.com/58330327/105172000-3ec2ce00-5b1f-11eb-89df-28d00f9df298.png)

**Comment by mjbvz** [comment]
The built-in preview does not natively support math (unless you've added a math script into your markdown file):

![Screen Shot 2021-01-20 at 12 37 11 PM](https://user-images.githubusercontent.com/12821956/105231784-4634a800-5b1c-11eb-9c2f-c2b493df1e89.png)
