### ISSUE TITLE
Failing to check if suggest popup is still open after clipboard access causing error when trying to read from context

### ISSUE THREAD

**Issue by nathggns** [microsoft/vscode#114518]
**monaco-editor version:** 0.21.2
**Browser:** Chrome
**OS:** Windows & macOS

```js
monaco.languages.registerCompletionItemProvider("javascript", {
    provideCompletionItems: () => {
        return {
            suggestions: [
                {
                    label: "clipboard",
                    insertTextRules:
                        monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
                    kind: monaco.languages.CompletionItemKind.Snippet,
                    documentation: "Insert clipboard",
                    insertText: "$CLIPBOARD"
                },
            ],
        };
    },
});

monaco.editor.create(document.getElementById("container"), {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript"
});
```

Using the above, you can reproduce this issue from https://microsoft.github.io/monaco-editor/playground.html

In Chrome, copy the above snippet into the playground, and then type the letter "c" into the editor. Make sure you have Chrome's "Clipboard" permissions for this page to "Ask". Click "Block" in the popup, and then you should see the following (or something similar) in the console.

```
DOMException: Read permission denied.
(anonymous) @ clipboardService.ts:70

Uncaught Error: Cannot read property 'column' of undefined
TypeError: Cannot read property 'column' of undefined
    at _.<anonymous> (suggestModel.ts:460)
    at Generator.next (<anonymous>)
    at r (compressedObjectTreeModel.ts:457)
    at errors.ts:22
```

## Investigation

Unfortunately it's not the most helpful  error. What it does tell us is that the error is caused in the `trigger` method of the `SuggestModel` class.

This is the bit of code that's erroring

```js
this._completionModel = new CompletionModel(items, this._context.column, {
    leadingLineContent: ctx.leadingLineContent,
    characterCountDelta: ctx.column - this._context.column
}, wordDistance, this._editor.getOption(96 /* suggest */), this._editor.getOption(93 /* snippetSuggestions */), clipboardText);
```

And it's suggesting that `this._context` is undefined.

This is incredibly confusing because the trigger method itself sets `this._context` to an instance of `LineContext`

```js
const ctx = new LineContext(model, this._editor.getPosition(), auto, context.shy);
  // Cancel previous requests, change state & update UI
  this.cancel(retrigger);
  this._state = auto ? 2 /* Auto */ : 1 /* Manual */;
  this._onDidTrigger.fire({ auto, shy: context.shy, position: this._editor.getPosition() });
  // Capture context when request was sent
  this._context = ctx;
```

This only other place (that I can find) that `this._context` is set is in the cancel method of `SuggestModel`

```js
cancel(retrigger = false) {
    if (this._state !== 0 /* Idle */) {
        this._triggerQuickSuggest.cancel();
        if (this._requestToken) {
            this._requestToken.cancel();
            this._requestToken = undefined;
        }
        this._state = 0 /* Idle */;
        this._completionModel = undefined;
        this._context = undefined;
        this._onDidCancel.fire({ retrigger });
    }
}
```

However, `suggest` does yield to the browser in between `this._context` being set and it being accessed – as it awaits the completions and the wordDistance. However, it seems you accounted for that with `this._state` as `trigger` checks `this._state` after it is resumed and when `this._context` is cleared, `this._state` is also set to 0

```js
Promise.all([completions, wordDistance]).then(([completions, wordDistance]) => __awaiter(this, void 0, void 0, function* () {
    dispose(this._requestToken);
    // ========= CHECKING STATE HERE (MY EMPHASIS) =========
    if (this._state === 0 /* Idle */) {
        return;
    }
    if (!this._editor.hasModel()) {
        return;
    }
    let clipboardText;
    if (completions.needsClipboard || isNonEmptyArray(existingItems)) {
        clipboardText = yield this._clipboardService.readText();
    }
    const model = this._editor.getModel();
    let items = completions.items;
    if (isNonEmptyArray(existingItems)) {
        const cmpFn = getSuggestionComparator(snippetSortOrder);
        items = items.concat(existingItems).sort(cmpFn);
    }
    const ctx = new LineContext(model, this._editor.getPosition(), auto, context.shy);
    this._completionModel = new CompletionModel(items, this._context.column, {
        leadingLineContent: ctx.leadingLineContent,
        characterCountDelta: ctx.column - this._context.column
    }, wordDistance, this._editor.getOption(96 /* suggest */), this._editor.getOption(93 /* snippetSuggestions */), clipboardText);
    // store containers so that they can be disposed later
    this._completionDisposables.add(completions.dispoables);
    this._onNewContext(ctx);
})).catch(onUnexpectedError);
```

However, if you look closely, after you check the state, you then yield (I guess this is a polyfill for async/await) to check the clipboard. I guess it's possible that if that takes some amount of time (or errors because the user blocks the request to the clipboard), then the context could be cleared in that time (if `cancel` is somehow triggered).

I think you need to add another state check after the clipboard check to ensure cancel hasn't been triggered whilst requesting clipboard access 

## Note

Interestingly, we don't define any clipboard snippets in our app, but it seems there are other ways to get `suggestModel` to attempt to read from the clipboard and therefore cause this error. I just went with the clipboard snippet example because it's the easiest to reproduce.

**Comment by jrieken** [comment]
I can also reproduce with `yarn web`

The problem is that reading the clipboard and that triggering the permissions flow implicitly cancels that suggestion session. That's some we don't except the [check for idle](https://github.com/microsoft/vscode/blob/690db82ef2cd3468c68c0f2abddd2e1e11e772b3/src/vs/editor/contrib/suggest/suggestModel.ts#L446) should come after the clipboard access

**Comment by aeschli** [comment]
Verified on the latest monaco playground (0.22.0 from yesterday).
- type a letter
- triggered by quick suggestions, browser asks for clipboard access. Answer `block`, no completion widget shown
- press Ctrl+Space, completion widget shows
- no error in console except for `Read permission denied`

Looks fine to me. 
@jrieken Not sure if that's the expected behavior, if not please reopen
