### ISSUE TITLE
Test additional information in the ports view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#114532]
Refs: https://github.com/microsoft/vscode/issues/112796 and https://github.com/microsoft/vscode-remote-release/issues/4120

- [x] ssh @connor4312
- [x] dev container @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114532%0A%0A)

---

1. Connect to your non-Windows remote.
2. Start a process that listens on a non-privileged port (the microsoft/vscode-try-node example is always good).
3. Verify:
  - Verify that the port is auto forwarded.
  - Open the Ports view. Verify that the pid is shown in parentheses for that port.
  - Drag the width of the Ports view "wide" and "narrow". Verify that you get a little more process info when the view is wide.

**Comment by bamurtaugh** [comment]
This LGTM - I like the additions with pid and more port info. The only part I was unsure about was that I'm still seeing more ports forwarded than I anticipated, and they share pid's.

![image](https://user-images.githubusercontent.com/25310137/105876740-1c640100-5fb4-11eb-9c61-388442314edf.png)

However, I think this would be addressed by https://github.com/microsoft/vscode-internalbacklog/issues/1717?

**Comment by connor4312** [comment]
> Verify that you get a little more process info when the view is wide.

I'm not sure what more I'm supposed to see here:

![](https://memes.peet.io/img/21-01-62da8169-117a-4383-bf55-0033b2d5754d.png)
