### ISSUE TITLE
Simple file picker keeps filling in the file name when I delete it

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114569]
Repro:

1. Open an untitled file
2. Set markdown language
3. Write some text
4. Save (with simple dialog enabled)
5. Clear path and enter a new one, the file name is added for each folder added

![recording (29)](https://user-images.githubusercontent.com/2193314/105039298-3c744d00-5a15-11eb-9086-8ec664828a91.gif)

This is particularly annoying as I would never name a file based on the untitled file's tab name.

Some options:

- Don't fill in the name
- If you specify just a folder, the existing file name is used
- Select the name when it's filled in so it's easy to remove

**Comment by alexr00** [comment]
You can use `workbench.editor.untitled.labelFormat` to change this back to "untitled".

**Comment by Tyriar** [comment]
Good to know, the tab name is useful to ID the tab when it's not focused, just not as a filename.

**Comment by bersbersbers** [comment]
This is a duplicate of #89751, isn't it?

**Comment by Tyriar** [comment]
Looks like it, thanks @bersbersbers
