### ISSUE TITLE
Return promise from workspace.openTunnel

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#114584]
Right now workspace.openTunnel returns a `Thenable`, which is slightly awkward for the consumer to deal with (I have to wrap it with Promise.resolve() to await it). As far as I know we allow extensions to return Thenables, but generally don't return Thenables from vscode APIs. Should it return `Promise<Tunnel | undefined>` instead?

**Comment by alexr00** [comment]
I think our API isn't supposed to return any Promises, only Thenables. The only Promise I could find in vscode.d.ts is 

https://github.com/microsoft/vscode/blob/152d0ec8f05179bdbed8c35b852e0d6bcac1bb22/src/vs/vscode.d.ts#L12164-L12164

@jrieken is it correct that API should not return `Promise`?

**Comment by jrieken** [comment]
Yes - years back when we started with vscode.d.ts the `Promise` types was finalized yet. Therefore we used the Thenable common denominator. We have considered to change that in place where we return a promise but didn't see the value in it. 

AFAIK you can await any thenable, it must not be a promise, but you cannot implement an async function returning a thenable.

**Comment by jrieken** [comment]
re https://github.com/microsoft/vscode/issues/114584#issuecomment-763443136

The `reactionHandler` actually looks a like bug...
