### ISSUE TITLE
New tab causes closing VSCode

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#114528]
Issue Type: <b>Bug</b>

Hi VSCode developers and maintainers.

I found issue which closes window on trying to create new macOS Tab.

Steps to reproduce:

1. Open VSCode
2. Open any project
3. Maximize/Full-screen VSCode
4. Try open new tab via "Window -> New Tab"
5. If VSCode didn't closed, open new tab until you get close (for me it's 3-4 tab, sometime 1)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|116, 42, 18|
|Memory (System)|28.00GB (5.70GB free)|
|Process Argv|--crash-reporter-id b225e7d4-aa5e-4699-9a2b-abfb60e37365|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fish|bma|1.0.20
vscode-intelephense-client|bme|1.6.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
dprint|dpr|0.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
LogFileHighlighter|emi|2.10.0
prettier-vscode|esb|5.8.0
shell-format|fox|7.0.1
go|gol|0.20.2
rust-analyzer|mat|0.2.457
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
gather|ms-|2020.12.1
python|ms-|2020.12.424452561
vscode-pylance|ms-|2021.1.1
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
vscode-yaml|red|0.14.0
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-todo-highlight|way|1.0.4

</details>

**Comment by dalisoft** [comment]
Yes @vscodebot. Thanks.

Related issue seems #102046

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
