### ISSUE TITLE
Simple file picker doesn't like backspace

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114567]
![recording (28)](https://user-images.githubusercontent.com/2193314/105038984-dbe51000-5a14-11eb-80d8-57c7a107a16d.gif)

Repro:

1. Type e:\e
2. Backspace several times

**Comment by alexr00** [comment]
The only recent change here was supposed to help screen readers (72e82ba). Do you have `editor.accessibilitySupport` enabled?

**Comment by Tyriar** [comment]
Nope. I'm not sure if this is a recent change or it always happened.
