### ISSUE TITLE
 Run sfdx help force for a list of available commands

### ISSUE THREAD

**Issue by ashish2889** [microsoft/vscode#114512]
Issue Type: <b>Feature Request</b>

 Warning: force:auth:web:login is not a sfdx command.
Did you mean auth:web:login? [y/n]: 
 »   Error: Run sfdx help force for a list of available commands.
12:32:45.941 sfdx force:auth:web:login --setalias DemoOrg --instanceurl https://login.salesforce.com --setdefaultusername
 ended with exit code 127

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.3.9600

**Comment by Ashok2216** [comment]
I got rid of it by running the update command in the terminal.
sfdx update
and then retry authentication.

**Comment by hareesh345** [comment]
By running sfdx update in CLI, fixed the issue.

**Comment by roshani22495** [comment]
Run command "sfdx plugin:install @salesforce/plugin-auth@1.4.3" on windows CMD. and retry authentication. It worked for me.

**Comment by ashish2889** [comment]
Yeah , this is work 
Thanks roshani22495

**Comment by rjuliao** [comment]
> Run command "sfdx plugin:install @salesforce/plugin-auth@1.4.3" on windows CMD. and retry authentication. It worked for me.

Thanks @roshani22495 your solution works for me too
