### ISSUE TITLE
Collapsing yaml blocks

### ISSUE THREAD

**Issue by StefanTheWiz** [microsoft/vscode#114595]
Issue Type: <b>Bug</b>

VS code not collapsing yaml blocks properly

example yaml:
```
  ApiToDynamoDbRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Description: Allows a web client, via API Gateway, to access the backend services
      ManagedPolicyArns:
        - !Ref AuthenticatedApiToCognitoPolicy
        - !Ref ApiToDynamoDbPolicy
  
  AuthenticatedApiToCognitoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: API authenticated access to Cognito
      ManagedPolicyName: !Sub "AuthenticatedApiToCognitoPolicy-${Environment}"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'mobileanalytics:PutEvents'
              - 'cognito-sync:*'
              - 'cognito-identity:*'
            Resource: '*' # todo: restrict futher?
```
I'd expect to only see 
```
> ApiToDynamoDbRole: [...]
> AuthenticatedApiToCognitoPolicy [...]
```
but what I get is:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/9119353/105092901-c7972680-5a99-11eb-855d-ca182d5d34a1.png">

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 8142ea11-e5a7-449a-8f86-5147367b1052|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-css-formatter|aes|1.0.1
aws-toolkit-vscode|ama|1.18.0
ng-template|Ang|0.1100.4
xml|Dot|2.5.1
cloudformation-yaml-snippets|dst|3.5.0
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
vscode-aws-cloudformation-auto-template-generator|joh|1.1.1
aws-cli-configure|mar|0.3.0
rainbow-csv|mec|1.8.0
gitignore|mic|1.0.1
vscode-docker|ms-|1.9.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3484
debugger-for-chrome|msj|4.12.11
csv-to-table|php|1.2.3
vscode-gitignore-generator|pio|1.0.2
vscode-yaml|red|0.14.0
svg-preview|Sim|2.8.3
serverless-ide-vscode|Thr|0.5.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773cf:30236630
pythonvspyt600:30247031

```

</details>

**Comment by briantreff** [comment]
I'm finding the same issue with version 1.52.1. I also happened to be working with AWS CloudFormation when I noticed the problem.

**Comment by aeschli** [comment]
If you have `vscode-yaml` installed, then the folding regions come from that extension.
Can you file the issue against the extension? https://github.com/redhat-developer/vscode-yaml/issues
