### ISSUE TITLE
The specified task cannot be tracked while developing a vscode extenstion

### ISSUE THREAD

**Issue by cqh963852** [microsoft/vscode#114575]
I am trying to developing a vscode extenstion in wsl2.
It will show me a error while running the extenstion at the first time.

![image](https://user-images.githubusercontent.com/17702287/105063594-db9d5100-5ab6-11eb-9af5-f5c0064d71c6.png)

After close that, I can run the hello world extenstion by press the f5 button.

Is there any way I can avoid the error?

- VSCode Version:1.52.1
- OS Version: WSL2 ubuntu18.04

Steps to Reproduce:
1. yo code
2. f5 run extenstion

**Comment by alexr00** [comment]
@eamodio I can repro when I choose to webpack in the yeoman generator. I see that this happened: https://github.com/microsoft/vscode-generator-code/issues/231

But now it seems that the problem matcher can't track the task.

**Comment by eamodio** [comment]
I've seen this in OSS, but never in built vscode. I'm not sure how that change would be related -- because how would the task know if a matching string will come or not?

**Comment by alexr00** [comment]
I am no longer able to repro.
