### ISSUE TITLE
Prevent default "close editor" behavior of going to previously opened editor

### ISSUE THREAD

**Issue by elliott-king** [microsoft/vscode#114596]
When closing an editor/tab in VSCode, it navigates back to the previous editor/tab you were using. Compare this behavior to Firefox or Chrome, which simply go to the next tab to the right.

This can be annoying, because it depends on state that is not visible. If possible, could you create a setting that depends on the horizontal locations of the tabs? This may be more predictable.

Thanks!

**Comment by elliott-king** [comment]
@bpasero not sure how this is a question instead of feature request. I am requesting a new settings option.

**Comment by bpasero** [comment]
I suggested to search on SO for discovering the existing `workbench.editor.focusRecentEditorAfterClose` setting.
