### ISSUE TITLE
Right-align actions for items in the ports view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#114586]
When clearing out my opened ports on another issue, I noticed that we don't have the actions right-aligned on tree items like we do in the scm and debug views. This makes it awkward to click things when items are of varying length (especially when the ports view is in the panel).

![](https://memes.peet.io/img/21-01-2029226f-2428-455a-94f3-a180b81e0a19.png)

**Comment by alexr00** [comment]
Yes, I had this concern too. However, the majority opinion was that the actions should not be right aligned when the ports view is wide.
