### ISSUE TITLE
multi-root workspace issue

### ISSUE THREAD

**Issue by grant-ymy** [microsoft/vscode#114521]
- VSCode Version: 1.52.1
- OS Version: Windows 10 with WSL (Ubuntu18.04)

Steps to Reproduce:

My project directory structure is like this：

- portal (It's a git repository)
    - xxx
    - xxx
    - ...
    - modules
        - ademo (It's a git repository)
        - ...
1. Add `portal` and `ademo` to workspace
2. Rename file/dir in `ademo`, it will automatically saved (in seconds) as if I had pressed enter:
    
    ![3](https://user-images.githubusercontent.com/30177246/104898179-3b5f0380-59b4-11eb-916b-9536494c4fe7.gif)

3. Open `portal/modules`，then open files/dirs under `ademo`, it alwals collapses automatically.

    ![4](https://user-images.githubusercontent.com/30177246/104898722-f1c2e880-59b4-11eb-8f98-df167cd56df7.gif)

    

Does this issue occur when all extensions are disabled?: No (My project is in WSL, so I just enabled `Remote - WSL` to test)

**Comment by isidorn** [comment]
Issue number 2 is duplicate of https://github.com/microsoft/vscode/issues/112503 and potentialy other issues which I pushed fixes for in VS code insiders
Issue number 3: can you reproduce with VS Code insiders. https://code.visualstudio.com/insiders/ if yes, can you create a minimal reproducable sample and put it on GitHub, so I could ideally just clone the repository and reproduce the issue on my machine?

**Comment by grant-ymy** [comment]
@isidorn Hi! I submitted a sample code [here](https://github.com/grant-ymy/vscode-bug-demo.git). It should be able to reproduce the problem 3. 
Thank you very much for your hard work！

**Comment by grant-ymy** [comment]
This issue seems does not appear in the insides version.

**Comment by isidorn** [comment]
If the issue does not appear in the insiders version than I will also not be able to reproduce it...
Maybe one of your extensions is causing this.
Otherwsie we can wait for the next stable release

**Comment by grant-ymy** [comment]
> If the issue does not appear in the insiders version than I will also not be able to reproduce it...
> Maybe one of your extensions is causing this.
> Otherwsie we can wait for the next stable release

OK, fo far, the insiders version works well, and I will continue to use it for a while to see if it will reappear. I believe the next stable version will be good.
This issue can be closed. Thanks! @isidorn
