### ISSUE TITLE
After closing FSI VSC unresponsive

### ISSUE THREAD

**Issue by halcwb** [microsoft/vscode#114540]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Whenever I close the FSI window, VSC becomes unresponsive and I have to reload the window.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.31GB free)|
|Process Argv|--crash-reporter-id 328296b9-26ce-41df-a08e-70cc91c2da4a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
vscode-markdownlint|Dav|0.38.0
githistory|don|0.6.14
EditorConfig|Edi|0.16.4
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|5.2.0
Ionide-Paket|Ion|2.0.0
rainbow-csv|mec|1.8.0
csharp|ms-|1.23.8
remote-containers|ms-|0.154.2
debugger-for-chrome|msj|4.12.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
pythonvspyt875:30241730

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

I think this needs reporting at https://github.com/ionide/ionide-vscode-fsharp
