### ISSUE TITLE
Can't install vscode extensions

### ISSUE THREAD

**Issue by xettrisomeman** [microsoft/vscode#114510]
- VSCode Version: 1.52
- OS Version: 20H2,19042, widows 10, 

When ever i try to install python or jupyter extensions, it shows an error.
"[renderer1] [error] EPERM: operation not permitted, lstat 'c:\Users\ai\.vscode\extensions\.ms-toolsai.jupyter-2020.12.414227025\out\client\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node': deleting: EPERM: operation not permitted, lstat 'c:\Users\ai\.vscode\extensions\.ms-toolsai.jupyter-2020.12."

When i install extensions by running vscode as an administrator ,
"[renderer1] [error] not enough bytes in the stream. expected 1076736. got only 1076730:

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Are you seeing this issue when installing any extension?

Can you also please provide complete logs?

- Shared process
- Renderer

**Comment by xettrisomeman** [comment]
Thanks but it worked after installing ubuntu.
