### ISSUE TITLE
Unable to open file from `git status` output into new tab

### ISSUE THREAD

**Issue by cjativa** [microsoft/vscode#114511]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have a folder (in this case a TypeScript project) open in VS Code through a WSL remote connection (Ubuntu 18.04)
2. Have an initialized git configuration for your project with some unstaged changes
3. Run `git status` to view list of unstaged files
4. Hover over a file in the list - you should be prompted to open it in a new tab, but instead are always prompted to open in a new window
5. Even after opening into a new window, the desired file is not opening into that window, and instead you're shown the usual VS Code start-up screen

I've tried these following settings to my `settings.json` to no avail. This appears to only happen when I have the project folder opened in a **Remote - WSL** window. It works as expected when the project folder is open locally.

```
    "window.openFoldersInNewWindow": "off",
    "workbench.editor.showTabs": true,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false
```

![screen-capture (4)](https://user-images.githubusercontent.com/41299115/104876653-22a80c80-5926-11eb-8298-3db7df4caedc.gif)

Does this issue occur when all extensions are disabled?: No

**Comment by aeschli** [comment]
Not reproducible for me, but I'm not familiar on what link detection in the terminal depends on.

**Comment by Tyriar** [comment]
A stat on the link is done here via the file service:

https://github.com/microsoft/vscode/blob/3c49afeaafa9bd13f9cba34409de4ce61cdbf916/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L326-L340

This result is then used to determine whether the link is one of the following:

- Open file in editor
- Focus folder in explorer
- Open folder in new window

https://github.com/microsoft/vscode/blob/3c49afeaafa9bd13f9cba34409de4ce61cdbf916/src/vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.ts#L140-L153

@aeschli I've seen other reports of this but was never able to repro, does anything look fishy with the implementation above?
