### ISSUE TITLE
Space key is not working

### ISSUE THREAD

**Issue by yashgarg330** [microsoft/vscode#114594]
space key is not working in html file please check it

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide information required by issue template (easier to copy from built-in issue reporter)

Check if there are any shortcuts that include spaces and comment them out in keybinding config <kbd>F1</kbd> and `>Preferences: Open Keyboard Shortcuts (JSON)`

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by aeschli** [comment]
Please check that the editor mode is HTML (see status bar)
Also check that the HTML language feature extension is enabled.
