### ISSUE TITLE
\u200b in vscode 

### ISSUE THREAD

**Issue by geeklibin** [microsoft/vscode#114550]
Issue Type: <b>Bug</b>
About invisible chars '\u200b'
copy with run this code:

'​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​123'.length;//=======>length:38

hope to show '\u200b' in vscode,Avoid bugs in programs
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 3792)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (25.66GB free)|
|Process Argv|--crash-reporter-id af9c6f66-49c7-44b3-814e-0d620c0e24c3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vue|jcb|0.1.5
vscode-docker|ms-|1.9.0
vscode-language-pack-zh-hans|MS-|1.52.2
vetur|oct|0.31.3
material-theme|zhu|3.9.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt859:30241729

```

</details>

**Comment by yume-chan** [comment]
Duplicate of #13239, #58252, #87127, #91137
