### ISSUE TITLE
Terminal not working when Windows host tries to use Remote-SSH to access Linux host

### ISSUE THREAD

**Issue by Nand087** [microsoft/vscode#114504]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Use vscode and Remote-SSH from Windows host to access remote Linux host.

Does this issue occur when all extensions are disabled?: Yes/No --> Not Applicable, the __Remote-SSH__ extension is needed to reproduce the issue.

The following is a screenshot of vscode not loading the terminal as expected. The destination host has both __bash__ and __zsh__ installed, so one would think that choosing any of them would make __terminal__ work.

![2021-01-17_14-29-07](https://user-images.githubusercontent.com/11032562/104858053-7c321c00-58d1-11eb-8f30-7c7280625ea3.png)

__Edit:__ Formatting and clarity.

**Comment by meganrogge** [comment]
Hey, the terminal works fine for me when I use WSL from a Windows host. From there, what are you doing to try to access a Linux host?

**Comment by Nand087** [comment]
I'm using the __Remote-SSH__ extension to connect from my Windows host to a Linux host. I can __view__ the files on the remote Linux host, and I can __edit__ them as well. The __terminal__ part of the connection is the one that is currently not working.
Please let me know if more information is needed.
Thank you for looking into this.

**Comment by Nand087** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4324#issuecomment-763344124
