### ISSUE TITLE
Github Authentication no longer functional

### ISSUE THREAD

**Issue by ZzZombo** [microsoft/vscode#114509]
Issue Type: <b>Bug</b>

I'm trying to sign in Github for Settings Sync but it doesn't work. Neither through the browser nor through manually copying either the generated link or an access token I generated myself.

* Click the "Sign in" link to sync settings.
* Select Github.
* Authorize VS Code in the browser or copy and paste the link manually.
* Signing in fails silently.

I have gathered this output from the Github Authentication extention:

```[Info  - 04:07:15.196] Logging in...
[Info  - 04:08:24.375] Exchanging code for token...
[Info  - 04:08:27.835] Token exchange success!
[Info  - 04:08:27.836] Getting user info...
[Info  - 04:08:29.112] Got account info!
[Info  - 04:08:29.256] Login success!
[Error  - 04:08:29.303] Getting token failed: Error: Cannot get password
[Info  - 04:08:29.350] Removing session no longer found in keychain
```

I've tried disabling-reenabling the extension, using diffrerent browsers, passing the generated link or an access token directly, deleting the Windows Credentials Manager entry created by the extension.

The authentication process did work correctly previously right after I installed VS Code, and so I had managed to sync my settings once. I am not quite sure as to what might have changed that caused it to malfunction ever since.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz (4 x 2167)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.89GB free)|
|Process Argv|--crash-reporter-id 5b864675-3a26-4790-9ea0-654705e65a4b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.3
project-manager|ale|12.0.1
vscode-color|ans|0.4.5
insert-unicode|bru|0.10.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
regex|chr|0.2.0
vscode-css-modules|cli|0.2.3
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
erb|Cra|0.0.1
vscode-github-actions|csc|0.13.0
dart-code|Dar|3.18.1
vscode-faker|dee|1.5.0
vscode-npm-source|dku|1.0.0
git-extension-pack|don|0.1.3
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
json-tools|eri|1.0.2
vs-code-xml-format|fab|0.1.5
vscode-pull-request-github|Git|0.22.0
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
c-cpp-flylint|jbe|1.7.1
vscode-gist|ken|3.0.3
contextualduplicate|laf|0.2.0
git-indicators|lam|2.1.2
node-module-intellisense|lei|1.5.0
sftp|lix|1.12.9
ecdc|mit|1.4.0
vscode-filesize|mkx|2.1.4
perl-debug|mor|0.6.3
hg|mrc|1.7.1
vscode-language-pack-ru|MS-|1.52.2
csharp|ms-|1.23.8
remote-wsl|ms-|0.52.0
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.55
debugger-for-chrome|msj|4.12.11
vscode-json-editor|nic|0.2.3
vscode-extension-auto-import|Nuc|1.4.3
indent-rainbow|ode|7.5.0
quicktype|qui|12.0.46
vscode-xml|red|0.14.0
vscode-sort-json|ric|1.19.2
perl6-lsp|scr|0.3.0
view-in-default-application|see|3.3.0
git-merger|sha|0.4.1
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
gitflow|vec|1.2.1
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.13.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
luahelper|yin|0.1.46
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by altokarev** [comment]
Same on Win 10 1903 (build 18362.1082) and VSCode 1.52.1.

**Comment by Mikezett** [comment]
I have a similar problem with 1.52.1 (Win10 20H2 (19042.685))

**Comment by altokarev** [comment]
And 1.53.1 insiders too.

**Comment by wesj1s** [comment]
I'm getting the following error when trying to enable Settings Sync via Github:

`Sign in failed: TypeError: Promise.race(...).finally is not a function`

**Comment by RMacfarlane** [comment]
@wesj1s Is that also using VSCode insiders on Windows? I think this may be a different problem based on the error message

**Comment by wesj1s** [comment]
> @wesj1s Is that also using VSCode insiders on Windows? I think this may be a different problem based on the error message

Hi @RMacfarlane you are correct this is not the insiders version. I managed to get it working using the Microsoft login instead.

**Comment by TylerLeonhardt** [comment]
Hi @ZzZombo 👋

I recently gained ownership of the GitHub Auth feature and so I'm getting ramped up!

It's been few versions now... Can you confirm if you're still seeing this issue?

Thanks!
