### ISSUE TITLE
code script for macOS not working

### ISSUE THREAD

**Issue by ipinky77** [microsoft/vscode#114547]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. open terminal and type "code -enter" you'll get an error 

it basically brings up a python error.
if you remove the python function and the CONTENTs formula like this:
codePath=$(which code)
codeDir=${codePath:0:${#codePath}-5}
CONTENTS="$codeDir/../../.."

it will work just about fine

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
not sure what you mean. when I enter `code -enter`, I get
```
Warning: 'e' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 't' is not in the list of known options, but still passed to Electron/Chromium.
```
What error do you see wen you enter that and what do you expect to see isntead?

**Comment by ipinky77** [comment]
well it didn't work on mine.. -enter was supposed to mimic the "enter" key...

anyway.. for me it only worked by calling Electron directly but not as everywhere proposed "code" (which points to Electron).. and with my fix it works for everyone
