### ISSUE TITLE
切换文件时项目自动编译

### ISSUE THREAD

**Issue by liuk123** [microsoft/vscode#114558]
Issue Type: <b>Bug</b>

我的项目时angular的项目，当从文件资源管理器切换文件时，项目自动编译。以前是执行保存操作的时候，项目才会编译。现在切换文件就会编译。

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.41GB free)|
|Process Argv|--crash-reporter-id 5a56f9f3-f975-499d-80b9-9fc3e604bde9|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1100.4
vscode-markdownlint|Dav|0.38.0
auto-rename-tag|for|0.1.6
vscode-language-pack-zh-hans|MS-|1.52.2
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30242242
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt875:30241730

```

</details>

**Comment by yume-chan** [comment]
To turn off auto save, set `"files.autoSave": "off"`
