### ISSUE TITLE
debug fails/command line works

### ISSUE THREAD

**Issue by michaelhyman** [microsoft/vscode#114589]
I have a program i've been running forever. Had some config issues and ended up removing and reinstalling node, npm, etc.

if i run my program from terminal everything works fine. I can do so from the terminal window in vs code or standalone terminal and it is fine. i can run by launching from npm or node. all works

when i go to the debugger in vs code, i get 

Exception has occurred: ReferenceError: Blob is not defined
  at Object.<anonymous> (/Users/xxx/Documents/GitHub/pbt-inventory-matcher/node_modules/xlsx/jszip.js:1506:28)

I've tried a few versions of xlsx.  We've tried on different computers and it works fine. But I can no longer debug on this one specific computer. 

I'm sure some config issue of some sort. My node and npm debug settings are the same across both vs instances.

FWIW, I also need to Force Quit vs code when i close it.

In the interim i will reinstall vs code

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2170B CPU @ 2.50GHz (28 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|64.00GB (11.41GB free)|
|Process Argv|--crash-reporter-id 1f2db8b5-9c0e-4aed-a392-efeed3a128eb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by michaelhyman** [comment]
The problems started when i mistakenly installed node again. You guys helped me with that. Subsequently, as noted, I removed nvm, npm, node, and my various node_modules folders. I also removed vs code. Reinstalled node. npm install all packages. reinstalled vs code.

same issue

**Comment by michaelhyman** [comment]
general symptom seems to be libraries are missing underlying components or don't find them while debugging but work fine in terminal

**Comment by michaelhyman** [comment]
also, sometimes i get:
node: --inspect-publish-uid= is not allowed in NODE_OPTIONS
Process exited with code 9

fwiw

**Comment by connor4312** [comment]
> node: --inspect-publish-uid= is not allowed in NODE_OPTIONS

This sounds like the same issue as https://github.com/microsoft/vscode-js-debug/issues/911#issuecomment-762554186

> Exception has occurred: ReferenceError: Blob is not defined

This is an issue from Node.js; the Node version that VS Code sees in your path is probably outdated. You can see the path to `node` when it runs in the Debug Console. Using [nvm](https://github.com/nvm-sh/nvm) is just fine and may be the easiest way to install a certain version of Node.js, e.g. with `nvm install 14`. You can then put `runtimeVersion: "14.<minor>.<patch>"` in your launch.json to use that specific version.

**Comment by michaelhyman** [comment]
For the first issue, yes, my bad. 
Looking at the second.

**Comment by michaelhyman** [comment]
/usr/local/bin/node ./test.js
from terminal:
which node
/usr/local/bin/node
node -v
v14.15.4

**Comment by michaelhyman** [comment]
From terminal: 
node test.js
..works
/usr/local/bin/node ./test.js
..works
from vs code debugger, using Run Current File:
/usr/local/bin/node ./test.js
This method of applying plugins is deprecated. See documentation for details.
Exception has occurred: Error: Cannot find module 'webworker-threads'
Require stack:
- /Users/xxx/Documents/GitHub/xxx/node_modules/natural/lib/natural/classifiers/classifier.js

**Comment by michaelhyman** [comment]
or if i run a different file i get an exception inside bluebird
but from terminal, everything runs just as expected

**Comment by michaelhyman** [comment]
any suggestions on what i might look at? again, terminal seems to use the same version of node and works fine. but in the debugger things fail. 
same code on a different machine with an older version of node, and everything runs fine.
same code on a different machine with same version of node and everything runs fine

**Comment by michaelhyman** [comment]
For another clue:
I did a git clone to a fresh directory
there i can run
so i suspect there are some settings in the project that are causing this issue... any magic areas i can look for?

**Comment by michaelhyman** [comment]
So, everything is now working again. 
Don't know what was causing the issue. I'm guessing some  hidden something file. 
But after a complete clone/reset up and recreation of the launch files, everything works as expected

the only odd thing is the sometimes vs code refuses to open or save a file or open a folder, and when i close vs code it doesnt'  close... i need to force quit. 

any ideas on that one?

(note, i do have a keychain password reset i need to do for github.login for vs studio, perhaps that is related to the force quit?)
