### ISSUE TITLE
npm.exclude seems to exclude only deep subdirectories

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#114562]
We are seeing dozens of `package.json` scripts from our `.cache` directory appear in NPM Scripts. Even with `npm.exclude` set to any of `.cache`, `**/.cache/**` or `.cache/**` it still lists a script in `.cache/package.json`:

Steps to Reproduce:
1. Create a subdirectory `.cache` with a package.json with a script (package A)
2. Create a subdirectory inside `.cache/foo` with a package.json with a script (package B)
3. Setting `"npm.exclude": [".cache/**"]` results in both these unwanted scripts appearing
4. Setting `"npm.exclude": ["**/.cache/**"]` results in scripts from package A appearing

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/498834/105016523-08178580-5a43-11eb-8140-2f6d1aa9e766.png)

VSCode 1.52.1 user
Ekectron 9.3.5
Chrome 83.0
Node.js 12.14.1
V8: 8.3
OS: Windows_NT x64 10.0

**Comment by crystalfp** [comment]
In a similar situation I had to put in `npm.exclude` both `**/.cache/**` and `**/.cache` to have `.cache/package.json` excluded.

**Comment by cawoodm** [comment]
Thanks that worked. Funny that someone decided imple `*` wildcards were not enough here. What is this strange language of `**` magic of which you speak?

**Comment by crystalfp** [comment]
** = Any directory level
