### ISSUE TITLE
VSCode doesn't register default formatter when languages are configured as array

### ISSUE THREAD

**Issue by mhatvan** [microsoft/vscode#114570]
In my settings.json I want to define prettier as default formatter for various languages:
```
"[html, javascript, javascriptreact, typescript, vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

Unfortunately, this leads to VSCode re-asking to set default formatter for these types.

In the end after reconfirming to set the default formatter, I always end up with a config looking like this:

```
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
```

This takes up a lot of space unnecessarily in my already huge config.

- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.10

Steps to Reproduce:

1. Configure Prettier as default formatter for multiple languages as array
2. VSCode will re-prompt you to set default formatter for language xyz

**Comment by gjsjohnmurray** [comment]
That syntax isn't valid. #51935 is a feature request for it.

**Comment by mhatvan** [comment]
Hah, I guess that explains it!
Quite confusing since the syntax doesn't error out and looks like a legit array.
Looking forward to have the feature request merged then, thank you!

**Comment by gjsjohnmurray** [comment]
@mhatvan please close this issue.
