### ISSUE TITLE
[JS] IntelliSense disregards properties if prototype defined by assigning object

### ISSUE THREAD

**Issue by odonyde** [Microsoft/vscode#11450]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro 1607
- Language: JavaScript

I observed that IntelliSense disregards any property inherited from the object's prototype in case the prototype is defined by assigning an object. For example, IntelliSense does not show property 'greet' in the screenshot below.
![vscode-intellisense-02](https://cloud.githubusercontent.com/assets/21695902/18188632/06e87f54-708a-11e6-96e0-4e787e506b7e.jpg)

IntelliSense only lists an inherited prototype property in case it is defined individually (see second screenshot).
![vscode-intellisense-01](https://cloud.githubusercontent.com/assets/21695902/18188606/ddd89b6c-7089-11e6-9c4d-1c45cf6b959f.jpg)

I would expect that IntelliSense presents inherited properties also in case the object's prototype is defined by assigning an object.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10736
