### ISSUE TITLE
Code doesn't start _after WindowServer crash_

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode#114531]
- VSCode Version: 1.52.1
- OS Version: macOS 11.2 Beta 2 (20D5029f)

Steps to Reproduce:

1. ~Download VS Code for Mac.~
2. ~Double-click to open~

1. Start VS Code for Mac
2. Wait until `WATCHDOG` kills the macOS `WindowServer`
3. Log back in
4. Start VS Code for Mac

Workaround:
Kill all `Code Helper (Renderer)` processes still lingering around.

Does this issue occur when all extensions are disabled?: Yes/No
Yes.

Expected Results:
VS Code opens

Actual Results:
VS Code bounces once in the doc. Nothing further happens. No crash report is created.
```
% code --disable-extensions; echo $?
0
% /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron; echo $?
0
```

**Comment by joaomoreno** [comment]
> Wait until WATCHDOG kills the macOS WindowServer

Why does this happen?

**Comment by toh-ableton** [comment]
This is unclear to me. At some point, my system froze, and apparently, there's a watch dog that kills and restarts WindowServer when it doesn't process events any more. I was presented with a login window and had to log in again, and then VS Code wouldn't start because of the left over helper processes that were still running, albeit without any Windows.

**Comment by joaomoreno** [comment]
It feels you might have bigger problems in your system than VS Code not working?

**Comment by toh-ableton** [comment]
Thanks for your concern, but my system is working just fine most of the time 😅 . 

It's maybe an edge-case issue, and I'm not saying it's something you should work on with the highest priority, but it was quite frustrating when it did happen until I understood what was happening. That's why I thought I'd share my insights with you.

**Comment by joaomoreno** [comment]
Maybe @deepak1556 knows of something we could do to help users that have this happen to them.

**Comment by deepak1556** [comment]
Sorry missed this, do you have any crash reports in the `Console.app` when this happens ? Also can you give the insiders a try https://code.visualstudio.com/insiders

**Comment by toh-ableton** [comment]
I haven't experienced Window-Server crashes since, and Code didn't crash (no crash reports).

**Comment by deepak1556** [comment]
Thanks, closing for now.
