### ISSUE TITLE
[remote cli] uninstall-extension should remove both local and remote extension

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#114542]
Open an integrated terminal in a remote window

- `code-insiders --install-extension aeschli.vscode-css-formatter`
- the extensions viewlet shows that the extension is installed both locally and remote (not sure if that's the expected result)
- `code-insiders --uninstall-extension aeschli.vscode-css-formatter` only removes one of the extensions

**Comment by dbaeumer** [comment]
Calling

```
code-insiders --remove-extension aeschli.vscode-css-formatter
```

results in 

```
Warning: 'remove-extension' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by aeschli** [comment]
Sorry, I corrected the description. It's `--uninstall-extension`

**Comment by aeschli** [comment]
Note, yesterday I changed that remote CLI only operates on the remote. That means removing a local extension is not possible with the remote CLI. User need to use the local CLI or the extensions viewlet.
Removing the milestone as the issue is no longer valid.
