### ISSUE TITLE
VS Code forgets some recents

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#114500]
- VSCode Version: 1.52.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Open and close a file. `C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\xxxxxxxx.default\user.js` in my case. Optionally edit and save it.
2. Restart VS Code.
3. If you're unlucky, upon pressing `ctrl` + `r` you won't find the file. This is inconsistent, so you may have to try a few times to reproduce.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
How do you open the file exactly?

**Comment by github-account1111** [comment]
Double-click on it in a file manager.

**Comment by bpasero** [comment]
Does this happen only with that specific file or all files you open like that?

**Comment by github-account1111** [comment]
No it happens with various files throughout the system, not just that one.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
