### ISSUE TITLE
Allow to rename untitled buffers

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#114694]
There is an existing identically named issue (#50303) which was marked as a duplicate of another issue (#37414), which ended up having a different resolution.

I would like to be able to rename untitled buffers manually.
I have a number of open buffers which are JSON files.
The first line is open brace `{`, and so all my files show as `{}` for the name.
Being able to rename them manually would be ideal.

I can see no open issue with the same request.

**Comment by IllusionMH** [comment]
Current available approach is change language mode to JSON with comments and use `// custom name` as first line.

/assing bpasero
