### ISSUE TITLE
Deserialized webviews cannot load resources after extension is updated on disk

### ISSUE THREAD

**Issue by evangrayk** [microsoft/vscode#114659]
- VSCode Version: dev build on master 1.53.0
- OS Version: macOS

When deserializing a webview, its extension location and local resource roots are taken from the moment it was serialized. If the extension is updated on disk, this points to an old version of the extension. This causes resources to fail to load due to being in a different extension folder. Usually, this breaks the javascript of a webview getting deserialized.

**Steps to Reproduce:** (a bit involved, we need to simulate an extension update)
1. Build the [cat-coding webview sample extension](https://github.com/microsoft/vscode-extension-samples/tree/master/webview-sample)
2. Copy the `package.json`, `out`, `media` dirs into a new folder called `sample-version1`. The package.json has version 0.0.1.
3. Move this into a folder somewhere called `test-ext-dir`.
4. Launch vscode with that as the extensions dir: `code --extensions-dir=/path/to/test-ext-dir`
5. Open the webview (cmd-shift-p "cat coding")
6. Close vscode
7. Copy `sample-version1` to `sample-version2`, update the package.json version to 0.0.2.
8. Relaunch vscode again with the same ext-dir.
9. Because the version is higher but the extension id is the same, vscode will prefer loading 0.0.2. But this disagrees with what was serialized from the last launch. It tries to load the webview but throws a 401 in the resource loader because it thinks it's accessing files from a different root, even though it's using the correct one. This results in the webview loading the HTML, but the JS not loading and the counter not counting.

<img width="1232" alt="Screen Shot 2021-01-20 at 10 26 20 AM" src="https://user-images.githubusercontent.com/1762690/105224413-010b7880-5b12-11eb-987e-c5e2fa838366.png">

**Does this issue occur when all extensions are disabled?:** No (you need an extension to provide a webview that has a deserializer)

**Comment by mjbvz** [comment]
Closing in favor of fixing the extension samples: https://github.com/microsoft/vscode-extension-samples/pull/376
