### ISSUE TITLE
accidentally i hide all activity bar. how to get again

### ISSUE THREAD

**Issue by arunkr741** [microsoft/vscode#114695]
Issue Type: <b>Feature Request</b>

accidentally i hide all activity bar. how to get again

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.16299

**Comment by IllusionMH** [comment]
/question

![image](https://user-images.githubusercontent.com/1312662/105351033-aa2a9f80-5bf4-11eb-8b6b-ae6f0fb2c27d.png)

Or from Command palette (<kbd>F1</kbd>) `>View: Toggle Activity Bar Visibility`
