### ISSUE TITLE
debug config variable substitution on debugger restart

### ISSUE THREAD

**Issue by dvirtz** [microsoft/vscode#114664]
Restarting a debug session does not go through debug configuration variable substitution, which is a problem since variable values might be different (e.g. for [command variables](https://code.visualstudio.com/docs/editor/variables-reference#_command-variables)) or substitution might have side effects like in the CMake extension which [uses](https://github.com/microsoft/vscode-cmake-tools/blob/develop/docs/debug-launch.md#debug-using-a-launchjson-file) the `cmake.launchTargetPath` command to trigger a build before debugging.

- VSCode Version: 1.52.1
- OS Version: MacOS Catalina

Steps to Reproduce:

1. Download https://github.com/dvirtz/vscode-bug/archive/debug-restart.zip
2. Open the folder in VScode with the C/C++ and CMake extensions
3. Put a breakpoint on `hello.cpp` line 4
4. Launch debug and see that CMake builds the target
5. After hitting the breakpoint, modify the code and save the file
6. Press debugger restart button and see that CMake doesn't build the target and the code changes do not apply 

Does this issue occur when all extensions are disabled?: ~~Yes~~/No

**Comment by roblourens** [comment]
I think that what we have now is a good default, but I could imagine an option on the launch config to force variable reevalution on restart
