### ISSUE TITLE
Function Breakpoints inserted into all sessions regardless of active session

### ISSUE THREAD

**Issue by kevingty** [microsoft/vscode#114612]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Running multi-thread programs with multiple sessions 
2. Entered Function breakpoints would be inserted into both sessions, causing errors.

Hi, I'm developing my own debug extension on multi-thread programs with multiple debug sessions. 

![callstack sessions](https://user-images.githubusercontent.com/5349543/105139857-d0d3d200-5b31-11eb-89a1-24515e5fb1a9.JPG)

But when inserting function breakpoints, I found breakpoints would be **inserted into all sessions regardless of the current active session.** 

I expect the function bkpt entered only to be inserted into core 0 in dsp session in the attached 'dsp session bkpt' image. 

![function breakpoint](https://user-images.githubusercontent.com/5349543/105139861-d29d9580-5b31-11eb-8b62-40c7d0cbb256.JPG)

But now both session (dsp & avp) are inserted.

![dsp session bkpt](https://user-images.githubusercontent.com/5349543/105139860-d204ff00-5b31-11eb-9f98-20922fe5d43f.JPG)
![avp session bkpt](https://user-images.githubusercontent.com/5349543/105139851-cf0a0e80-5b31-11eb-8f8b-f7be14254031.JPG)

 Would it be fixed? Thank you. @weinand @isidorn

**Comment by weinand** [comment]
Since breakpoints are global and owned by VS Code, they are registered with all debug sessions. 
This works as designed.

**Comment by kevingty** [comment]
@weinand May I ask how to achieve threads mapped to a specified debug session in frontend through vscode api? I can't find any api available.  What I expect is threads info be filtered in debug extension so that thread for a breakpoint would be correctly mapped to the correspondant breakpoint. Thank you.

**Comment by weinand** [comment]
What do you mean by "threads mapped to a specific debug session"? You cannot set breakpoints for a thread. You set them for a source line or a function in all threads. But a breakpoint condition can be added that becomes true only for specific threads.

**Comment by kevingty** [comment]
@weinand Thanks Andre. I'm sorry I didn't make it clear enough. We use a reformed gdb as debugger, and breakpoints would be inserted restricted to specified threads using thread-id.  We persist and apply thread-id information to breakpoints in DAP protocal request implementation.  

The program is stared with multiple debug sessions with multiple threads. The case now is that we need to figure out a way to block breakpoints that do not belong to threads of active debug session to be set when DAP setBreakpointsRequest executed. 

We've tried adding a custom event in source code called 'onDidFoucusThread' in **setFocus**()  of **debugViewModel**.ts, hoping that would help tag the specified thread and we could pass breakpoint info with the focus thread and do filtering in DAP setBreakpointsRequest. But it seems when starting debug session, this event would be triggered for each thread. Thus our persisted breakpoint info would not work.

You got any advice for 'Debug sessions that cannot deal with them should ignore them' when dealing with breakpoint not needed?

**Comment by weinand** [comment]
you asked:
> You got any advice for 'Debug sessions that cannot deal with them should ignore them' when dealing with breakpoint not needed?

Since you are building your own debug extension, you probably have your own debug adapter.
If this is true, your debug adapter can filter ("throw away" or "ignore") breakpoints received via the `setBreakpoints` and `setFunctionBreakpoints` requests.

> you said:
We persist and apply thread-id information to breakpoints in DAP protocal request implementation.

So if your breakpoints already got a thread-id attribute, you can use that information inside the `setBreakpoints` and `setFunctionBreakpoints` requests to only register the breakpoints for the specified thread.
