### ISSUE TITLE
[Markdown preview] Code tag font size

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#114667]
```js
"editor.fontSize": 25,
```

Markdown preview seems to be using different font-size for `<code>`  depending on editor font size. It doesn't look good if the editor font is big:

![Screenshot (426)](https://user-images.githubusercontent.com/9638156/105232280-35fee600-5b79-11eb-81ef-556e7ee933ed.png)

I think it would be better if `<code>` was using the same font size as all the other text in the webview.

**Comment by sandy081** [comment]
@mjbvz Can you please provide steps to verify, as I do not see any change in extension editor which is reported in description.

**Comment by mjbvz** [comment]
Looks like the PR only fixed the release notes (I confirmed the fix there). I'll also port this fix to the extension editor too

**Comment by sbatten** [comment]
reopening due to above comment
