### ISSUE TITLE
Expand PickList to support *grouping*

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#11468]
Originally reported in https://github.com/Microsoft/vscode/issues/7019#issuecomment-222484365

The idea is to show items in the pick list, just like _Go to Symbol_, where you have some kind of groups of items (that appears when you type '@:' in the pick list)? 

![653e93ac-264a-11e6-8dda-4c0af353f65c](https://cloud.githubusercontent.com/assets/3781424/18210934/61b60e10-7111-11e6-8008-41ccf1f45e79.png)

Thanks in advance

**Comment by shinhwagk** [comment]
+1

**Comment by gjsjohnmurray** [comment]
Would the team consider a PR for this API enhancement request so [QuickPickItem](https://code.visualstudio.com/api/references/vscode-api#QuickPickItem)s can be grouped?

**Comment by chrmarti** [comment]
@gjsjohnmurray Lets first discuss the API change. Would you just surface what we use internally? There we allow the items list to be either a QuickPickItem or a QuickPickSeparator which then separates the groups and can have a label.

**Comment by gjsjohnmurray** [comment]
@chrmarti that makes good sense to me. @alefragnani is that what you wanted?

**Comment by alefragnani** [comment]
@gjsjohnmurray I never thought the API would be that way. I was thinking about a group/category data _attached_ to each `QuickPickItem` and the `QuickPick` itself would deal with grouping and counting the items in each group (when properly turned on with a new `QuickPickOptions` option). At first sight, I thought the groups (line separator and labels/counting) would be generated _automatically_.

But, if the proposed API (`QuickPickItem` and `QuickPickSeparator`) could give me the same power/flexibility as we see today in `Go to Symbol` command, it would be great. 

![Kapture VSCode QuickPick with Grouping](https://user-images.githubusercontent.com/3781424/80431999-60ad5e00-88c9-11ea-8304-00e1632f8ea8.gif)

I just wonder how/if I should deal with the _ordering_, _visibility_ and _counting_ myself when the user filters the PickList, with the `QuickPickSeparator`. As you see, the _counter_ changes, so should I "recreate/update" that `QuickPickSeparator` too? 

I didn't dig in VS Code source to see how the internal API works today, but with the right documentation and samples, I guess it wouldn't be a problem.

Thank you

**Comment by chrmarti** [comment]
The built-in filtering removes all separators because it also sorts across groups by the best match. `Go to Symbol` does its own filtering and sorting, the `createQuickPick` API would allow you to do the same once we support disabling sorting and filtering.

**Comment by jrieken** [comment]
>  I was thinking about a group/category data attached to each QuickPickItem and the QuickPick itself would deal with grouping and counting the items in each group 

Big :+1: for that

**Comment by chrmarti** [comment]
> > I was thinking about a group/category data attached to each QuickPickItem and the QuickPick itself would deal with grouping and counting the items in each group
> 
> Big 👍 for that

We would copy the group labels across items. If the group label were alternating A, B, A, we would have two options: either sort them by first appearance or consider it distinct groups.

I like an approach without the replication and ambiguities better.

**Comment by gjsjohnmurray** [comment]
I just discovered this has also been discussed on #74967.

@chrmarti I'll leave it to you (or someone else) to decide if that issue or this one should be closed as a dup. This one is older.

**Comment by chrmarti** [comment]
Indeed thanks @gjsjohnmurray.

/duplicate #74967
