### ISSUE TITLE
Increase the recent folder list capacity

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11460]
_From @joaomoreno on September 2, 2016 14:17_

It's OK to only show 10 in the `File > Open Recent` menu, but we should't limit ourselves to only 10 recent folders when going through with <kbd>Ctrl R</kbd>.

_Copied from original issue: Microsoft/vscode-vsce#122_

**Comment by enVolt** [comment]
Doesn't seem to be working on Mac OS X. Can someone verify this on Mac?

**Comment by bpasero** [comment]
Done:

<img width="644" alt="screen shot 2016-10-04 at 09 48 17" src="https://cloud.githubusercontent.com/assets/900690/19066102/b4763476-8a17-11e6-8c9e-f958f9df5639.png">

**Comment by enVolt** [comment]
I'm on version 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
Do I need to do something to enable this?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by enVolt** [comment]
Working fine on Insider Build, recent list shows more than 10 items.
(Version 1.6.0-insider 602155bb781f509c7a4ddcd700b57cb9b9f5286d)
