### ISSUE TITLE
Remove recently used task doesn't work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#114679]
Clicking on _Remove Recently Used Task_ seems to invoke the _Configure Task_ action.

![image](https://user-images.githubusercontent.com/641685/105276183-c84dbc80-5b6e-11eb-9f52-46ba7c5e8a97.png)

**Comment by alexr00** [comment]
Interesting. I can't repro this. Will investigate in February.

**Comment by alexr00** [comment]
It seems to be related to the double "Kill Build VS Code" tasks that you have, but I can't repro that. Regardless, I can fix the configure action occurring.
