### ISSUE TITLE
Repeatedly clicking a link in Settings Editor behaves unexpectedly

### ISSUE THREAD

**Issue by ihigg** [microsoft/vscode#114615]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Navigate to `Search > Search Editor: Default Number Of Context Lines` in the settings editor
2. Scroll up until that option is at the bottom of the window
3. Click the link to `Search › Search Editor: Reuse Prior Search Configuration`.
4. You should still be able to see the link; click it again.

- Repeatedly clicking the link will repeatedly apply the same scroll offset.
- If the link is close to disappearing off the end of the editor window, clicking it will apply an offset in the opposite direction bringing the link back away from the edge.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

VS Code version: Code - Insiders 1.53.0-insider (32b28f6f8f9dfe36efad102cc460e14a84ba756a, 2021-01-19T06:09:44.762Z)
OS version: ~Windows_NT x64~ Windows 10 Home 10.0.19042 _For some reason vscode is giving the wrong OS here and in the about screen_

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt600:30247031
core-portspanel:30233467

```

</details>

**Comment by roblourens** [comment]
> You should still be able to see the link; click it again.

Why? The code tries to scroll the target to the same place that the source was, this seems fine to me.
