### ISSUE TITLE
"Go to line" feature -- same as MS Dev studio Debug C++

### ISSUE THREAD

**Issue by genapol** [microsoft/vscode#114658]
MS Dev studio Debug C++ mode has got a feature "Go to line". User puts the cursor on the line in the code and presses CTRL+SHIFT+F10 to move the next command pointer to that line. Some conditions apply -- the user can't just move a pointer to a random line.

It would be useful to have this functionality in Python and potentially in other "codes"

**Comment by weinand** [comment]
VS Code already supports this functionality as "Jump to Cursor" or "Set Next Statement" but only if the underyling debug extension supports it.
Please file this feature request against the Python extension.
