### ISSUE TITLE
terminal display

### ISSUE THREAD

**Issue by liangguangming** [microsoft/vscode#114689]
- VSCode Version: 1.52.1
- OS Version: wsl2

Steps to Reproduce:

1. kubectl exec -it xxx -- sh
2. type "env",but get
![image](https://user-images.githubusercontent.com/38413913/105338207-3e592e80-5c16-11eb-88c0-1253b5c84860.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
Hi, it's not clear to me what's going on here. Can you please attach a [gif](gifcap.dev)?
