### ISSUE TITLE
Tasks not showing up in Command Palette

### ISSUE THREAD

**Issue by perrytribolet** [Microsoft/vscode#1146]
Tested using windows version

**Comment by egamma** [comment]
Not sufficient information, please provide steps and expected results. 

Also notice tasks show up in the Command palette when entering 'task '.

**Comment by msiniscalchi** [comment]
There seems to be nothing related to tasks showing up in the Command Palette. At the > prompt, if I type `task`, absolutely nothing shows up. For instance, the instructions at https://code.visualstudio.com/docs/languages/typescript#_transpiling-typescript-into-javascript about how to transpile TypeScript code do not work. There is no "Configure Task Runner" command.

This is on Win10, 
Version 0.10.3
Commit 783ecf841a2b21edca6d86853670cae89b4c244f
Date 2015-11-26T14:06:31.538Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1

**Comment by irongeorge** [comment]
Same here @msiniscalchi on Ubuntu 14.04. I can't follow instructions to configure. There is no "Configure Task Runner" and no "task", just nothing related to tasks.

**Comment by egamma** [comment]
Can you attach a screenshot of what you see. Here is what I see:

<img width="623" alt="screen shot 2015-12-22 at 17 53 59" src="https://cloud.githubusercontent.com/assets/172399/11960870/1aca0920-a8d5-11e5-9417-963c32e97f94.png">

Is there any message in the console of the developer tools Help>Toggle Developer Tools>Console.

**Comment by irongeorge** [comment]
I toggled the console too.
![screenshot from 2015-12-22 21 05 35](https://cloud.githubusercontent.com/assets/5410669/11961097/e1e91cb6-a8ef-11e5-804c-6c6dc13130e6.png)

**Comment by irongeorge** [comment]
It now works for me! I did a clean reinstall again and made a symlink too and now it works. Don't know what was going wrong. I have the application folder on my desktop. Here's a screenshot too. 
![screenshot from 2015-12-22 21 22 08](https://cloud.githubusercontent.com/assets/5410669/11961494/63e0c988-a8f2-11e5-98db-c912fdf375ae.png)

**Comment by dbaeumer** [comment]
I can't reproduce this neither on Linux nor on Windows using 0.10.6. @msiniscalchi can you still reproduce this using 0.10.6 ?

**Comment by msiniscalchi** [comment]
Here. Just tried this on OS X, right after installing.

<img width="1023" alt="code no tasks" src="https://cloud.githubusercontent.com/assets/668933/12100205/1d8567b8-b2f3-11e5-87c5-e5a07bdb11fa.png">

**Comment by dbaeumer** [comment]
@msiniscalchi very wired. Can you check if there is something in the log. From the menu bar select Help > Toggle Developer Tools and repeat the action. Thanks !

**Comment by msiniscalchi** [comment]
Absolutely nothing! There is not a single line in the console log (I assume that's what you wanted me to check). I tried several times to pul up tasks.... BUT I think I got it!!!

Task-related items DO show up in the palette if you open a folder---any folder. And when you close the folder, task items are no longer shown.  Not sure whether this is a bug or not, but it should be documented.

**Comment by dbaeumer** [comment]
@msiniscalchi tasks are only available if you open a folder. The underlying reason is that task rely on a .vscode/tasks.json file and this can only exist in a folder case not when editing single files. I fully agree that this should be documented. I will do so for the next release

**Comment by dbaeumer** [comment]
As suggested I address this by updating the corresponding documentation.

**Comment by dbaeumer** [comment]
To verify check the documentation for tasks.json. There is now a sentence at the beginning addressing this.

**Comment by rohitj559** [comment]
On the Command Palette i type the literal 'code'. I need to get the below - 
![image](https://user-images.githubusercontent.com/13977044/31055577-8684f532-a6e2-11e7-8eed-c1f89fa25de6.png)

But i get the below -
![image](https://user-images.githubusercontent.com/13977044/31055613-1e292fde-a6e3-11e7-8ade-8012a4519a8a.png)

Please help. What should i do to get the former? Palette options?

**Comment by dbaeumer** [comment]
The first one is contributed by the C# extension. The next two once are to my knowledge not necessary anymore. @joaomoreno can you clarify.
