### ISSUE TITLE
Cannot copy code problem message after Ctrl+Tab from an active Webview

### ISSUE THREAD

**Issue by MetRonnie** [microsoft/vscode#114697]
If I <kbd>Ctrl</kbd>+<kbd>Tab</kbd> from an extension-contributed webview tab to an editor tab which has "problems" identified by a linter/language server, I can't copy the problem message from the hover/peek problem dialog. I can only copy the message if I click on the editor tab instead of using <kbd>Ctrl</kbd>+<kbd>Tab</kbd>.

- VSCode Version: 1.52.1
- OS Version: Linux x64 3.10.0-1160.15.2.el7.x86_64

```
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
```
Also reproduced on Windows 10 (`OS: Windows_NT x64 10.0.17763`)

Steps to Reproduce:

1. Have a repo or workspace with an editor tab (i.e. a code file open) and a webview tab open (e.g. the git-graph extension). 
2. Make a "problem" in the code, e.g. unused variable or undefined variable that gets picked up as a warning/error by a linter/language server and underlined with a squigly line.
3. Go to the webview tab.
4. Use <kbd>Ctrl</kbd>+<kbd>Tab</kbd> to switch to the code file again.
5. Hover over the squigly line and when the hover dialog appears with the linter problem, try to select and <kbd>Ctrl</kbd>+<kbd>C</kbd> the message (or click on "peek problem" and try the same).
6. The text does not get copied to the clipboard

![image](https://user-images.githubusercontent.com/61982285/105343425-8574fe80-5bd9-11eb-9a1a-4ce7cddb0f38.png)

However, if I explicitly click on the editor tab instead of using <kbd>Ctrl</kbd>+<kbd>Tab</kbd>, then I can copy the problem message.

This seems to be a keyboard focus issue?

Does this issue occur when all extensions are disabled?: N/A - cannot see code problems at all when extensions are disabled.

*Moved from https://github.com/mhutchie/vscode-git-graph/issues/453*

**Comment by mjbvz** [comment]
I can't seem to reproduce this in the latest VS Code insiders build using MacOS and Windows. Can you please test and let me know if you still run into this problem?

If you do, please share more details about the exact steps to reproduce this. Also, do you see this with all webviews or just specific ones? Try checking using the markdown preview for example

**Comment by MetRonnie** [comment]
The problem does not seem to be there when ctrl+tabbing from a markdown preview, but I have tested and it's still there for extension-contributed webviews including https://github.com/mhutchie/vscode-git-graph, and https://github.com/eamodio/vscode-gitlens custom settings view (these are the only 2 extensions I have installed that come with a webview). I had originally opened this as an issue on vscode-git-graph, but the author was able to reproduce the bug with other extensions's webviews: https://github.com/mhutchie/vscode-git-graph/issues/453#issuecomment-764580849

**Comment by mjbvz** [comment]
I just tested with git graph on MacOS and Window but could not reproduce this. Can you please share a screen recording that shows the exact keypresses you are making? You can enable screencast mode in VS Code to do this: `Developer: toggle screencast mode`

**Comment by mjbvz** [comment]
Also I noticed you originally opened this using an old version of VS Code. Make sure to test using the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)

**Comment by MetRonnie** [comment]
I've updated the post with the latest version I'm running at the moment (1.52.1) reproduced on Windows too. Unfortunately can't test on insiders build at work or do a screen recording, will try to do so on my personal laptop at some point

**Comment by mjbvz** [comment]
Yes please test using insiders when you get a chance

**Comment by MetRonnie** [comment]
I've tried with 1.53 on Windows (different device to the original one), and cannot reproduce the issue on it.
