### ISSUE TITLE
VsCode Exntesion API: vscode.workspace.getConfiguration.get returns undefined

### ISSUE THREAD

**Issue by hanct** [microsoft/vscode#114671]
VSCode Version: 1.52.1
OS Version: Windows 10

Steps to Reproduce:
1. In my package.json, i have the below contributes.configuration setting

```
"contributes": {
		"configuration": {
			"title": "Test Extension",
			"properties": {
				"sr.display": {
					"type": "object",
					"properties": {
						"editor-display":{
							"type":"boolean",
							"default":true
						},
```

2.  In my extension.ts, i have a line of code
        const config = vscode.workspace.getConfiguration("srr.display")
        value:boolean|undefined = config.get<boolean>("editor-display")
  

Weird thing is, the config.get keep returning undefined.   Although my external development host's settings.json does not define the editor-display setting, but according to package.json, this setting by default is true.  Hence I am expecting the config.get to return true.   Only when i rewrite the line of code to become 
`config.get<boolean>("editor-display",true)`, it will then return true.. But if i have to do that , then what is the purpose of defining "default":"true" in the package.json.  

Or did i actually miss or overlook something?

**Comment by PEZ** [comment]
I think that with object properties you need to define the default on the object. See if it works if you do:

```json
				"sr.display": {
					"type": "object",
					"properties": {
						"editor-display":{
							"type":"boolean"
						}
					},
					"default": {
						"editor-display": true
					}
				},
```

Caveats for me not formatting the json correctly (and also for guessing a bit here 😄 ).

**Comment by hanct** [comment]
> I think that with object properties you need to define the default on the object. See if it works if you do:
> 
> ```json
> 				"sr.display": {
> 					"type": "object",
> 					"properties": {
> 						"editor-display":{
> 							"type":"boolean"
> 						}
> 					},
> 					"default": {
> 						"editor-display": true
> 					}
> 				},
> ```
> 
> Caveats for me not formatting the json correctly (and also for guessing a bit here 😄 ).
Yes, you are right! It did works. Thanks!
 But that would also mean i have to end up duplicating the properties into the default object, which does not seem to comply with DRY (Do not Repeat Yourself) design.  In fact, I have more than couple of properties to put in, and all has default values, Imagine repeating their names again in the default. 
I really wish that the default value defined in the properties for object type, can be returned when   vscode.workspace.getConfiguration.get is called when the setting is not defined

**Comment by sandy081** [comment]
Thanks @PEZ and whatever you said is correct and this is designed as of now.
