### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by fatscally** [microsoft/vscode#114691]
Please create and implement the Ultimate Bookmark system for  VS Code.
Ok any basic bookmark system would be really useful right now working on an enterprise project.   But you could go to the top with this adding colour coding for different sets of bookmarks and groupings etc.

Good luck!!!

**Comment by gjsjohnmurray** [comment]
Have you tried using any of the bookmark extensions that are available?

**Comment by fatscally** [comment]
> Have you tried using any of the bookmark extensions that are available?

Hi John.   
tbh it never entered my mind that there would be one!   I'm a Visual Studio 20xx bunny.   I don't often add gizmos to it anymore.  If it's worth having MS usually buys it and implements it such as CSharpener etc.   
Thanks for the tip.   Is there one you'd recommend?
