### ISSUE TITLE
File tabs stay open when stepping through search results using F4 key

### ISSUE THREAD

**Issue by bardware** [microsoft/vscode#114651]
- VSCode Version: 1.42.1
- OS Version: Windows 10 64 bit, German

Steps to Reproduce:

1. Click on the magifying glass on the left and enter a search term to search through all files of the workspace
1. press `F4` to step between the results

Does this issue occur when all extensions are disabled?: Yes/No
Yes

I was used to the functionality that the current tab is closed and the next file is opened in a new tab. A temporarily opened tab can be recognized by the fact that the title is written in italics. When I click on the various files in the search result a temporary tab is opened. Still, when I step through the results pressing `F4` a new permanent tab is opened.
To find out if it is a matter of settings I explicitly set
```
    "workbench.editor.enablePreview": true,
    "workbench.editor.enablePreviewFromQuickOpen": true,
```
which changed nothing.

Is this a bug? Was a new setting introduced I'm missing?

**Comment by roblourens** [comment]
First off, you are on a very old version of vscode :) but I still see the issue in the latest

**Comment by bardware** [comment]
> First off, you are on a very old version of vscode :)

Should read 1.52.1; sorry.
Thank you for caring!

**Comment by roblourens** [comment]
Hey @bpasero I think this is from f3a23697a90f49276cdb4f5531e931f9d6134086. When I press F4, focus goes to the editor, but I might navigate quickly through many files so I still want them to be preview tabs. Is it ok to force `pinned` to false in SearchView?

**Comment by bpasero** [comment]
@roblourens yes feel free to change it back as you see fit. I would argue that going through search results should match the experience of clicking with the mouse, so preview seems legit to me.

**Comment by roblourens** [comment]
I think the default in ListService is correct so I added a new flag to override `pinned` while setting the selection, same as we already do for `preserveFocus`, I think this is ok. FYI @joaomoreno
