### ISSUE TITLE
Extension Api: Make workspace.applyEdit / TextEditor.edit race-condition free

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#114656]
With the currently provided extension APIs (VS 1.52.1), it is not possible to use `workspace.applyEdit` or `TextEditor.edit` in a race-condition free way.

If an extension issues a `TextEditor.edit` as reaction to `TextEditor.onDidChangeTextDocument`, sometimes things get out of sync. I guess this is due to the async nature of the extension host.

As an example, currently, it seems impossible to reliably replace every entered `a` with an `x`.
This code has race condition issues:

```ts
this.dispose.track(workspace.onDidChangeTextDocument(async (e) => {
    for (const c of e.contentChanges) {
        if (c.text === "a" && c.rangeLength === 0) {
            const ed = new WorkspaceEdit();
            ed.replace(e.document.uri, new Range(c.range.start, c.range.end.translate(0, 1)), "x");
            await workspace.applyEdit(ed);
        } else if (c.text !== "x") {
            // This is never called when keeping "a" pressed
        }
    }
}))
```

This is what happens:

![bf224a6d-6eda-4bdb-94ce-7aa690ec2fdc](https://user-images.githubusercontent.com/2931520/105221043-db559200-5b58-11eb-9837-a6afaa215e4f.gif)

I'm not entirely sure why this example already causes this behaviour, as all the edits in this example are conflict free. I guess it gets way worse for conflicting edits.

It would be great if the text document version could be passed to the `WorkspaceEdit.replace` function. If the edit is about to be applied but the version has been incremented in the meantime, `applyEdit` should throw a catchable version mismatch error and the edit should not be applied.

This gives the extension the option to retry the edit (which I guess is quite complex if the specification is to replace every typed `a`).

Something similar would be nice for setting selections too.

**Comment by jrieken** [comment]
> It would be great if the text document version could be passed to the WorkspaceEdit.replace function.

We are actually implicitly doing that behind the scene. Whenever a `WorkspaceEdit` is serialised we fill in the version id (as it is currently known on the extension host) https://github.com/microsoft/vscode/blob/b165e20587dd0797f37251515bc9e4dbe513ede8/src/vs/workbench/api/common/extHostTypeConverters.ts#L537

In you sample, can you check the return value of `applyEdit`. It should return a boolean indicating of the edit has been applied or not. The renderer error log could/should also contain a message with more information

**Comment by hediet** [comment]
Oh, thank you, this is very good to know! Sorry that I missed that! I thought the boolean parameter would just indicate whether the change itself is sound (e.g. doesn't insert something into line 10 of a document with 5 lines).

This code is not how it should be implemented, but for future reference, this works reliably:
```ts
workspace.onDidChangeTextDocument(async (e) => {
    for (const c of e.contentChanges) {
        if (c.text === "a" && c.rangeLength === 0) {
            const ed = new WorkspaceEdit();
            ed.replace(e.document.uri, new Range(c.range.start, c.range.end.translate(0, 1)), "x");
            while (true) {
                if (await workspace.applyEdit(ed)) {
                    break;
                }
            }
        }
    }
}))
```

I think some generic retry logic could be implemented by extension-authors that works for conflict-free edits.
