### ISSUE TITLE
Ephemeral debug configs in broken state after reload

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#114606]
Noticed this first in codespaces but can repro locally too.

```
git clone https://github.com/JacksonKearlCAHours.git
cd CAHours
npm i
code-insiders .
```

In command palette, `debug `, then select `Node.js`, then `Run Script: start` (the `Run Script: start` seen here shouldn't exist yet)
![image](https://user-images.githubusercontent.com/8586769/105117258-0f5d8400-5a81-11eb-8a9e-dac5cb906793.png)
![image](https://user-images.githubusercontent.com/8586769/105117337-2dc37f80-5a81-11eb-96be-6c3d688406fb.png)

Should work fine.

Reload window.

Press F5, or the play button in debug viewlet, or the `Run Script: start` entry at top level of the `debug ` quick pick.
![image](https://user-images.githubusercontent.com/8586769/105117452-5cd9f100-5a81-11eb-8bca-338f98127a93.png)
🐛🐛🐛🐛 `Configuration 'Run Script: start' is missing in 'launch.json'`

**Comment by isidorn** [comment]
@JacksonKearl thanks for great steps! I have pushed a fix, once you try it out let me know so we add verified label. I tried it out with the fix it works for me
