### ISSUE TITLE
Regression? VScode portable GUI doesn't work when running from a UNC path

### ISSUE THREAD

**Issue by ralgozino** [microsoft/vscode#114641]
- VSCode Version: 1.52.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Download vscode zip and extract it to a UNC path like \\sharedfoler\mystuff\vscode
2. Open Code.exe
3. vscode's main window will open up but nothing gets drawn, no menus, no icons, only the different bars colors are visible.

Does this issue occur when all extensions are disabled?: Yes

This is what you get:
![image](https://user-images.githubusercontent.com/6362698/105199730-6164df00-5b3f-11eb-9ecc-11933f37a1f7.png)

This doesn't happen if you copy the same extracted folder to a local disk. Also, creating the `data` folder doesn't seem to change the behavior.

This started to happen somewhere after v1.46.1, using this version everything works as expected. I haven't tried other versions in between.

Possible related issues: #53857 #66128

**Comment by bpasero** [comment]
I cannot reproduce this trying to run latest VSCode from a local UNC: `\\localhost\c$\Users\name\Downloads\VSCode\Code.exe` via PowerShell.

However, we will actually not be able to support running VSCode from UNC paths going forward given limitations such as https://github.com/electron/electron/issues/25618. 

You can already see this today, the process explorer and issue reporter will not appear correctly.

**Comment by ralgozino** [comment]
Hi @bpasero 
Sorry for the delayed answer, I missed the notification somehow.

On one hand, If I copy the extracted folder to a local disk and use the `\\localhost\c$\Users\name\Downloads\VSCode\Code.exe` path VSCode's window gets drawn. So it seems that using `\\localhost` isn't the same as running from an actual network path.

On the other hand, if I mount the shared path as a disk (`Z:` for example) and run it from there, it works.

Too bad to hear that UNC support could be dropped, it's a pretty common thing on enterprises.

**Comment by bpasero** [comment]
@ralgozino I didn't mean to say that running from UNC is unsupported entirely, I think a mapped network drive will always work just fine. What I think will not work is running explicitly from a command line that is on `\\...`. Even today, you will notice that `*.cmd` refuse to execute from UNC paths.

**Comment by ralgozino** [comment]
Sorry for the late response. The mount as a network drive workaround was enough for me, but I can imagine some limited environments where one can't have permissions to do it. But that's another issue.

I don't know if this workaround is documented somewhere, I was lucky to try it out of dispair. It would be a nice addition to the portable version instructions may be?

Thank you for your time and your answers!

Have a nice day.
