### ISSUE TITLE
INVALID CREDENTIALS

### ISSUE THREAD

**Issue by ahardy16199** [microsoft/vscode#114678]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Issue Type: <b>Bug</b>

invalid credentials

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD E2-9000e RADEON R2, 4 COMPUTE CORES 2C+2G   (2 x 1497)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.48GB free)|
|Process Argv|--crash-reporter-id 8fea302d-5835-48a6-8c68-3f7fd5b9d3f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
zopeneditor|IBM|1.1.3
indent-rainbow|ode|7.5.0
vscode-extension-for-zowe|Zow|1.11.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30242242
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt600:30247031

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please give details of how to reproduce this issue

**Comment by tejas-2232** [comment]
I  am getting kind of same issue when I try to do `git push`

terminal message:-
```

Missing or invalid credentials.
Error: connect ENOENT /run/user/1000/vscode-git-d9e87de8e9.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1000/vscode-git-d9e87de8e9.sock'
}
Missing or invalid credentials.
Error: connect ENOENT /run/user/1000/vscode-git-d9e87de8e9.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'connect',
  address: '/run/user/1000/vscode-git-d9e87de8e9.sock'
}
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/tejas-2232/python'
```

**Comment by gjsjohnmurray** [comment]
@tejas-2232  please open a fresh issue for this. Use the "Report Issue" option from the Help menu so your report includes your platform and version info.

**Comment by tejas-2232** [comment]
Thank you for your response. I will report issue.
