### ISSUE TITLE
Default keybindings missing.

### ISSUE THREAD

**Issue by PatrykSitko** [microsoft/vscode#114634]
Hi,
I've had installed and choosen the wrong keybindings template.
Instead of choosing the vscode template I've had choosen another one.
I cannot reset the keybindings map to default (vscode) template.
I have learned to use (some) vscode shortcuts; And would like to keep using them.
In the extensions store, I can download vscode keymaps. But none offers the default keybinding scheme.
It would be nice if there would be a button to reset the keymap to the default vscode scheme.
Thank you.

With regards

Patryk Sitko

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by alexdima** [comment]
@PatrykSitko You can simply uninstall the keymap extension that you installed and then the keybindings will go back to the default VS Code ones.
