### ISSUE TITLE
Duplicate files appear when cyclic symbolic links are created using the junction command

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11464]
- VSCode Version: 1.5 Insider
- OS Version: Windows 10

Steps to Reproduce:
1. create a cyclic symbolic link dependency using the junction command (need to download from MS). 
2. have a file abc.txt in that cycle
3. Ctrl+P abc.txt

You get:

![capture](https://cloud.githubusercontent.com/assets/1931590/18209093/86f347da-7132-11e6-8d57-d14cad21e6ab.png)

**Comment by bpasero** [comment]
Moving to @chrmarti to consider once we revisit the solution on Windows. I am still surprised that the node.js cyclic link detection does not protect against this case but maybe fs.realPath() does not return something smart here.

**Comment by bpasero** [comment]
@chrmarti isn't this fixed because we no longer use "dir" on Windows?

**Comment by dbaeumer** [comment]
If I remember correctly this was with NO dir on Windows. But I used junctions instead of mklink which seem to do something else that node might not handle correctly

**Comment by bpasero** [comment]
@dbaeumer ah yeah, maybe we had this issue since day 1

**Comment by dbaeumer** [comment]
@bpasero could be.
