### ISSUE TITLE
not able to get remote explorer open in github codespaces

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/vscode#114603]

**Comment by himanshuahlawat31** [comment]
in github codespace i am not able to open remote explorer

**Comment by isidorn** [comment]
Works for me 
![Screenshot 2021-01-20 at 11 08 19](https://user-images.githubusercontent.com/1926584/105159833-d3bdcb00-5b0f-11eb-989d-60772cf857a3.png)

I think this should just be closed, but forwarding to @alexr00
