### ISSUE TITLE
Debug console should compute colored output's length correctly

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11467]
- VSCode Version: 1.5.0
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. Clone https://github.com/Microsoft/vscode-node-debug
2. `npm install && gulp build`
3. Run tests

![](https://cloud.githubusercontent.com/assets/4033249/18183174/fefbbbe0-7047-11e6-9289-4b9e563d43e7.png)

When going to `launch.json` and remove `--colors` from `mocha`, it works fine:

![image](https://cloud.githubusercontent.com/assets/4033249/18210842/5ab5a9bc-70ef-11e6-95e9-533545135071.png)

The debug console need to handle color code like `\033[0;31m` used to color terminal output.

Related to #11321

**Comment by isidorn** [comment]
The code for computing output length is [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/replViewer.ts#L119)
I am not jumping on this since we will probably change the underlying implemntation of the debug console #11462

fyi @roblourens

**Comment by isidorn** [comment]
This is fixed now
