### ISSUE TITLE
Native Notebooks - Default kernel not honored

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#114663]
Steps to Reproduce:

1. Open new notebook using command palette - default kernel set to "A" 
2. Open kernel picker and change default kernel to "B" using wheel
3. Create new notebook using command palette 
4. Notebook created with kernel "A" **not** "B"

**Comment by rebornix** [comment]
@claudiaregio I think this is something the kernel provider can control (by listening to kernel change and change its `preferred` kernel decision) @DonJayamanne can you confirm?

**Comment by DonJayamanne** [comment]
@rebornix @claudiaregio will update the issue with more information.
The confusion was around the usage of the `grear` icon to select the default kernel provider. She assumed that was the same as setting it as the default `Kernel`. I.e. a user doesn't know what a kernel provider is, they only know about kernels.

**Comment by claudiaregio** [comment]
I expected that clicking the wheel was going to set this as my default kernel and when I opened a new one it would be set to this but it keeps setting it to Python 3 instead. @rebornix is this not setting default kernel? 

![image](https://user-images.githubusercontent.com/19276747/106958503-4d4be080-66ee-11eb-9af5-f33cadc30655.png)

**Comment by claudiaregio** [comment]
I believe a user is falling into the same or related issue here based on the feedback below. No email provided to follow-up and get clarification. Sounds like it could be the same issue where new notebooks opened up with Python 3 for me instead of the one I thought I had set as default. 

![image](https://user-images.githubusercontent.com/19276747/112346388-238d4f80-8c83-11eb-9b2b-8c6fbc38527a.png)

**Comment by claudiaregio** [comment]
+1 customer feedback

![image](https://user-images.githubusercontent.com/19276747/123856826-6724d480-d8d6-11eb-8224-02adc2c598fa.png)

**Comment by rchiodo** [comment]
I think the 'default' kernel should be remember by the core (as it might not be a jupyter kernel).

**Comment by rchiodo** [comment]
Related:
https://github.com/microsoft/vscode/issues/134830

**Comment by roblourens** [comment]
I don't think this is relevant anymore
