### ISSUE TITLE
node: Studio is not supported in NODE_OPTIONS

### ISSUE THREAD

**Issue by fredddy123** [microsoft/vscode#114637]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Create JavaScript Debug Terminal
2. nvm install 8
3. nvm use 8
4. node -v

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
We are not able to dynamically detect changes in the Node version when running the debug terminal. Node versions prior to 12 don't support quoting in their shell arguments, which we need to enable some capabilities. In this case it looks like your node version was >= 12 when creating the terminal, then downgrading to 8 caused the environment variables that were previously set to hook up debugging in the terminal to no longer be parsable.

All node versions prior to 12 will be end-of-life in April of this year, so I do not plan on going to great lengths to fix this.
