### ISSUE TITLE
onDidSaveNotebookDocument not fired when saving notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114650]
Version: 1.53.0-insider
OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Create an extension using the VSC Notebook API
2. Add event handler to `onDidSaveNotebookDocument`
3. Save a notebook and this event isn't fired.

This seems to only work when saving an untitled notebook or using the `Save As` option.
Doesn't fire for regular saves (with & without auto save).

Does this issue occur when all extensions are disabled?: Yes

**Comment by mklechan** [comment]
@DonJayamanne  Im also trying to get this to work, could you share your extension code?

**Comment by DonJayamanne** [comment]
@mklechan Sure https://github.com/microsoft/vscode-jupyter/blob/afaadfff655a927c09d7b6394b7c0e91fcb8b878/src/client/datascience/notebook/defaultCellLanguageService.ts#L47

**Comment by DonJayamanne** [comment]
This event seems to fire when i close the notebook.

**Comment by susiwen8** [comment]
@DonJayamanne I think this is a typo issue :joy:
