### ISSUE TITLE
Cannot type anything in vscode editor and also cannot copy and paste the code.

### ISSUE THREAD

**Issue by Yeshwanth33** [microsoft/vscode#114624]
![Screenshot (1)](https://user-images.githubusercontent.com/69045972/105157534-147b0b80-5b33-11eb-994e-635e8560f80c.png)
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Do you have Vim extension? Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by joaomoreno** [comment]
Uninstall the VIM extension and you'll be able to type again.
