### ISSUE TITLE
Delete key not working

### ISSUE THREAD

**Issue by Mukulbaid63** [microsoft/vscode#114629]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.As we start the app, the delete key doesn't work

Does this issue occur when all extensions are disabled?: Yes

**Comment by Mukulbaid63** [comment]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by IllusionMH** [comment]
Check if you have any shortcuts assigned to this key (see https://github.com/microsoft/vscode/issues/113489#issuecomment-751752626)

If there are no overrides for that button - follow instructions in https://github.com/microsoft/vscode/issues/113489#issuecomment-760196112
