### ISSUE TITLE
Reopen with picker stays open

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114690]
* have the MD notebook extension configured as default
* open a MD file (see the notebook editor being used)
* from the title context menu select open with and pick an editor
* :bug: the picker doesn't close when editors have changed

<img width="1317" alt="Screenshot 2021-01-21 at 11 28 47" src="https://user-images.githubusercontent.com/1794099/105338574-01704600-5bdc-11eb-9b79-40a5001f1f82.png">

**Comment by mjbvz** [comment]
When verifying, also confirm that right arrow opens the file but keeps the picker open
