### ISSUE TITLE
 Assertion failed (item already registered: variable:variable:variable:scope:1:Local:1000:response:users:[0])

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#11469]
Issue Id: <b>2ad1c8f9-f86a-7e63-b860-a35889cfee27</b><br /><br />*Versions* <br />- 1.5.0-insider (9/1/2016 6:06:23 AM)<br />*Stack* <br />Error: Assertion failed (item already registered: variable:variable:variable:scope:1:Local:1000:response:users:[0])<br />    at Object.n [as ok] (<br />    at t.register (<br />    at new t (<br />    at <br />    at Object.g [as _notify] (<br />    at Object.W.enter (<br />    at n.Class.define._run (<br />    at n.Class.define._completed (<br />    at <br />    at t.e.dispatch (<br />

**Comment by kieferrm** [comment]
The same insider build generated a considerable number of these exceptions.

@bpasero pointed out that this could either be that the same object is being used multiple times in a tree in a debug view or that the function that generates the IDs is not sufficiently discriminating.

Let's start with debugging.

**Comment by kieferrm** [comment]
Here is another stack track that might give a hint:
Error: Assertion failed (item already registered: variable:variable:scope:1:Fermeture:1002:slaveClientsList:length) 
at Object.n [as ok] (out/vs/workbench/workbench.main.js:5:8389) 
at t.register (out/vs/workbench/workbench.main.js:36:28030) 
at new t (out/vs/workbench/workbench.main.js:36:28784) 
at out/vs/workbench/workbench.main.js:36:31919 
at Object.g [as _notify] (out/vs/workbench/workbench.main.js:30:12868) 
at Object.W.enter (out/vs/workbench/workbench.main.js:30:16446) 
at n.Class.define._run (out/vs/workbench/workbench.main.js:30:18274) 
at n.Class.define._completed (out/vs/workbench/workbench.main.js:30:17715) 
at out/vs/workbench/workbench.main.js:83:16911 
at t.e.dispatch (out/vs/workbench/workbench.main.js:83:18578)

**Comment by isidorn** [comment]
Currently the id of a variable is determined based on it's parent's id and the name of the variable. And this should be unique. However a debug adapter can always return two variables with the same name in a given scope - this should be invalid in all languages but still the adapter could return such a falsy result. We are guarding against that [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L298)

Not sure how this exact situation was caused but I have made our variable id more restricite (taking refernece into account)
