### ISSUE TITLE
Snap: VS Code snap uses old theme for Adwaita-dark

### ISSUE THREAD

**Issue by validatedev** [microsoft/vscode#114625]
- VSCode Version: 1.52.1
- OS Version: Fedora 33

Steps to Reproduce:

1. Open VSCode snap
2. Look at the top menu

Does this issue occur when all extensions are disabled?: Yes
Referring https://github.com/snapcrafters/vscode/issues/53

This is the look from Fedora 33:
![image](https://user-images.githubusercontent.com/29679552/105160736-a5e18200-5b21-11eb-9033-b3e5bce52b9d.png)
The color used on the top menu is from the old Adwaita-dark theme.

And look at the Sublime Text snap
![image](https://user-images.githubusercontent.com/29679552/105160885-cc9fb880-5b21-11eb-8456-ccacc445b89a.png)
As you can see, the color on the top menu is different.
The one that used on Sublime Text should be used, that is from the new -official- Adwaita theme.

**Comment by joaomoreno** [comment]
This is related to the snap base image. We won't fix this any time soon.

**Comment by validatedev** [comment]
Well, why don't you use an upper version of the base image? VSCode snap looks out of place when using the classic default Adwaita theme. Is there a reason for using an older base, or you simply don't care how VSCode looks? @joaomoreno

**Comment by joaomoreno** [comment]
> Is there a reason for using an older base

There are plenty of reasons, all related to compatibility of libraries across all features of VS Code. The effort it will take to advance the snap just for a theme change won't pay off the amount of work it will take to make sure all features are going to be OK, especially considering the current and past issues related to [snap](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asnap). Thanks for understanding.

**Comment by validatedev** [comment]
First, thanks for the explanation. Of course, I prioritize stability over how it looks.

Second, I couldn't find a way to simply change the theme of snap, did plenty of research. Don't want to add repos on my package manager, unless I have not any chance. Using the flatpak version of VSCode is not an option for me, because it is not official, thus I don't sure about stability and compatibility. So, sticking with snap. Using an old theme is not a dealbreaker though, it just annoys me.
