### ISSUE TITLE
Vs Code command line --install-extension

### ISSUE THREAD

**Issue by pnrthomp** [microsoft/vscode#114668]
Hi,

In Windows 10 Edu, 20H2, VS Code 1.52.1 does not install any extension via command line as per the online instructions.
"code --install-extension (<extension-id> | <extension-vsix-path>)
    Installs an extension."
    
It simply loads the GUI and produces the following output:

C:\Program Files\Microsoft VS Code>code --install-extension ms-vscode.cpptools

C:\Program Files\Microsoft VS Code>
[main 2021-01-20T20:59:10.242Z] update#setState idle
(node:6004) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:6004) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:5504) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2021-01-20T20:59:40.260Z] update#setState checking for updates
[main 2021-01-20T20:59:40.339Z] update#setState idle

Any help would be appreciated.

Thanks,

Paul T.

**Comment by sandy081** [comment]
May I know if other command line arguments work for you, for eg: `code --help` ?

**Comment by pnrthomp** [comment]
Hi,

No, it produced this:
C:\Program Files\Microsoft VS Code>code.exe --help

C:\Program Files\Microsoft VS Code>
[main 2021-01-22T16:53:31.492Z] update#ctor - updates are disabled by user preference
(node:7928) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:7928) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:5128) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Program Files\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.

...and loaded VS Codes GUI.

Thanks for responding,

Paul T.

**Comment by sandy081** [comment]
It seems cli args are not getting respected while launching.

**Comment by bpasero** [comment]
Do not use `Code.exe` directly.

**Comment by pnrthomp** [comment]
> Do not use `Code.exe` directly.

This is not a solution, considering the official documentation shows it can be used on CLI.

Paul T.

**Comment by Zelec** [comment]
@pnrthomp I found out where the issue is. I'm trying to do something similar where I'm installing extensions for new users at the org I work at with a simple script.

I have no clue if this is properly documented or not (I had to do some digging with a Windows 10 system that had VSCode properly added to the path), but to pass command line arguments in the windows copy of vscode, you don't call Code.exe directly, You have to call `bin/code.cmd`

So in your case, you would call `"C:\Program Files\Microsoft VS Code\bin\code.cmd" --install-extension ms-vscode.cpptools` and that will install the cpptools you need from commandline.
