### ISSUE TITLE
Auth API specs two labels and uses both

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114685]
The current API allows to define a label in package.json and when registering. I believe the former is enough but I am sure that in case both are needed one should win

```json
"authentication": [
	{
		"id": "autho",
		"label": "[Autho(PGJ)]"
	}
],
```

```ts
 vscode.authentication.registerAuthenticationProvider('autho', '[Autho]', new Autho());
```

<img width="1519" alt="Screenshot 2021-01-21 at 09 17 48" src="https://user-images.githubusercontent.com/1794099/105322780-9d448680-5bc9-11eb-8e6e-728ef37ead1d.png">

<img width="332" alt="Screenshot 2021-01-21 at 09 17 56" src="https://user-images.githubusercontent.com/1794099/105322790-a03f7700-5bc9-11eb-8ec4-47e65e8ff570.png">

**Comment by jrieken** [comment]
required for https://github.com/microsoft/vscode/issues/88309

**Comment by RMacfarlane** [comment]
Augh I forgot about this problem.

My current thinking is we should get rid of the package.json registration. We needed that for exposing a `providers` property on authentication that was synchronous, but I'm not sure that is actually needed. I think it does have value for extension authors to learn what provider ids to use, but I think the use case of checking it at runtime is rare.

**Comment by RMacfarlane** [comment]
The label specified in `registerAuthenticationProvider` is now used everywhere

https://github.com/microsoft/vscode/commit/a5a8392079eb08d5166e19f866520bb212166459
