### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by zherar7ordoya** [microsoft/vscode#114631]
Improve the default formatter to do a better job with files common to any project: md, jsx, .env, etc. It would not be a bad idea if a format style is configurable (there are several). And thanks for the wonderful job you do with my beloved vscode.

**Comment by IllusionMH** [comment]
Examples of formatting that is bad and need improvement will be useful, otherwise meaning of "bad" formatting is different for each person.

**Comment by zherar7ordoya** [comment]
I didn't say that vscode does a bad formatting. I have said that, for example, there are very common files for which vscode does not do any formatting and for which add-ons must be installed. From this point of view (that of installing plugins) perhaps this request is already resolved. Thank you anyway.
