### ISSUE TITLE
Add command to insert copied cells above the current cell

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114720]
Today we have a command to paste a copied cell, however this only pastes the cell below the current cell.
We'd like to have the ability to paste the cell above the current cell.
This is required to add support for Jupyter style keyboard shortcuts in the Jupyter exetnsion.

@claudiaregio /cc

**Comment by DonJayamanne** [comment]
@rebornix Jupyter extension could attempt to create their own command to do this,
* Select the previous cell
* Then invoke the paste command
Feels hacky (specially if user were to move the cursor around just after we selected the previous cell). I.e. its possible for cell the get inserted elsewhere (unlikely but possible).

If you feel this is a good enough solution for Jupyter, we can try that.

**Comment by jeanp413** [comment]
@rebornix  I took a look at this and found the [`notebook.cell.pasteAbove`](https://github.com/microsoft/vscode/blob/5f17dc2a596707b9eff8b41eb864bde827d09ccb/src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts#L67) command is already implemented.
Isn't it the correct command or am I missing something?

**Comment by rebornix** [comment]
@jeanp413 thanks for verifying! Yup the command is already implemented.
