### ISSUE TITLE
vscode python outline is not working

### ISSUE THREAD

**Issue by erdemult** [microsoft/vscode#114704]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. outline screen is reporting "the active editor cannot provide outline information"
2. I get the same issue if I enable/disable extension ms-python.python

Does this issue occur when all extensions are disabled?: Yes

Please let me know what other info I can provide?

**Comment by jrieken** [comment]
\extPython
