### ISSUE TITLE
Untitled files aren't well supported in custom editors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#114711]
The custom editor flow is normally as follows:
1. User calls open with / the editor is the default editor
2. The custom editor is passed a URI, normally a file URI but sometimes can be the untitled file
3. The custom editor then utilizes various `fs` APIs to perform actions on that file URI.

This flow is of course broken when the URI passed in isn't a file URI as the custom editor can no longer utilize the `fs` APIs. We currently don't have a good story on how to handle untitled files in custom editors. Taking the hex editor for example, if the user calls `reopen editor with` -> `hex editor` on an untitled file the custom editor will crash due to the fs APIs failing. The current workaround is:
1. Check the URI passed in to your custom editor to see if it is an untitled file
2. Find the matching URI in `vscode.workspace.textDocuments`.
3. Call `.getText()` on the matching text document.
4. Convert that text into a `Uint8Array` as that is the form of data `vscode.workspace.fs.readFile(uri)` would normally return.
5. When the user attempts to save, always trigger a saveAs.

**Comment by jrieken** [comment]
@bpasero what's the deal with untitled files? Those are always text document, right? Who is owning them and disposing them?

**Comment by bpasero** [comment]
Can we have a meeting rather than Q&A in this issue please with everyone involved, I am not up to speed with the issues around untitled and custom editors and would like to get a intro + discussion in person.

**Comment by bpasero** [comment]
Can we have a meeting rather than Q&A in this issue please with everyone involved, I am not up to speed with the issues around untitled and custom editors and would like to get a intro + discussion in person.

**Comment by mjbvz** [comment]
Closing this in favor of #115631
