### ISSUE TITLE
Option to keep pinned editors visible

### ISSUE THREAD

**Issue by brunnerh** [microsoft/vscode#114747]
It would be nice if there were an option to prevent the pinned editors from scrolling out of view, if many editors are opened.
With the option on, only the non-pinned editors would scroll.

Mock example:

![image](https://user-images.githubusercontent.com/834235/105475052-3db8aa80-5c9f-11eb-89e2-9af7c62b5f92.png)

**Comment by brunnerh** [comment]
If this is supposed to be the default behavior then this a bug or regression in case this worked before.
Tested on 1.52.1 user setup. Reproduces with and without extensions enabled.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/108355#issuecomment-706514266 by @bpasero indicates what you're seeing is as designed.

**Comment by brunnerh** [comment]
I have been looking through the settings and did not expect this behavior to be hidden in `workbench.editor.pinnedTabSizing`.
Thanks!
