### ISSUE TITLE
Insiders + Remote SSH + Python: unit test rendering errors.

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode#114732]
- VSCode Version:Version: 1.53.0-insider
Commit: 1a4b35c2023a41efae1af2661026d57cea90ef5c
Date: 2021-01-21T05:12:00.322Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Use VS Code remote, try to discover python unit tests.
2. Unit test interface widgets missing.

see /microsoft/vscode-python#15165 for more details but a `vscode-remote-resource:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT` error is occuring when trying to use Python extension remotely to run unit tests in the latest insiders. (Insiders VS COde, Insiders Python Extensions, Remote SSH nightly.)

Does this issue occur when all extensions are disabled?: N/A, requires Python and Remote SS

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/114740

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/114743, please subscribe to the issue for updates. Thanks!
