### ISSUE TITLE
Introduce GlyphWidgets and tackle overlapping decorations in gutter

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#114776]
Related discussion https://github.com/microsoft/vscode/issues/25174

So far we have never tackled the problem of mutliple decorations on the same line.
@alexdima and me have started a discussion and here's are things that came up:

#### Overlapping decorations

What to render in the Glyph Margin once there are multiple decorations, here are some options:
1) Try to combine multilpe icons into one. Downside of this is that this will probably not look good if we automatically merge icons
2) We render the first icon that came and in the corner we put N where N is the number of decorations there
3) We render a generic decoration icon, so we render the Generic one + N (like a badge)

Once we have something rendered, here are two options how the interaction could look llike:
1) Clicking on it triggers the context menu which for each decoration has the decoration label as text and no icons
2) Hover expands the multiple decorations and each decoration gets rendered, on each decoration the user can click / drag

#### `GlyphWidgets`

One thing is that we might need to add a new concept to the editor where glyph margins are not just decorations since you need so much interaction with them. One option is to add the concept of “glyphWidget” similar to “contentWidget” where you pass in a dom node to the editor. That would give you a chance to add dom event listeners on your own and then the editor can just be responsible with positioning them. 
The `glyphWidgets` would give more control to the decoration author, one use case would be https://github.com/microsoft/vscode/issues/88227

**Comment by isidorn** [comment]
@connor4312 it would be cool if you could share your ideas behind the test decorations. What would they be and how would they fit in our above ideas.
@misolori let me know if you have some good ideas for a "generic decoration icon", or what are your thoughts on what would visually fit when there are multiple decorations on a line.

**Comment by connor4312** [comment]
I'm guessing Alex shared my use case, which is being able to show breakpoints on lines where the test runner icon is also present

![image](https://user-images.githubusercontent.com/2230985/105519517-5d93a280-5c8e-11eb-8988-09413111b40d.png)

For me implementing this experience with `GlyphWidgets` would be preferable since I need multiple icons and colors here. The badge idea for option (3) sounds nice, and perhaps glyph widgets could control this themselves with something like

```
interface IGlyphWidget {
  render(c: HTMLElement): void;
  // called if multiple glyphs are on a line, can optionally return a new widget to use instead of the original widgets
  merge?(other: IGlyphWidget): IGlyphWidget | undefined; 
}
```

I'm having trouble picturing what the "hover expands" scenario would look like, though I see that having the actual breakpoint widget available somewhere is important for the drag+drop scenario.

I think the context menu is good (and is what I am doing manually with test decorations and the breakpoint menu today.)

For another reference, I looked at what intellij does yesterday: they just permanently expand the gutter when extra icons are added. This works but feels bad to me:

![](https://memes.peet.io/img/21-01-44014157-142e-4dc0-b37a-c54dd36c0d83.gif)

**Comment by misolori** [comment]
One simple thing we could do if we just wanted to highlight multiple items is using the `...` ellipsis that we already use for context menus:

![image](https://user-images.githubusercontent.com/35271042/105521373-a77d8800-5c90-11eb-8370-a6de27b4eee5.png)

Adding a number in a 16x16 would be really difficult to be readable so I'm not sure if that would be good.

**Comment by connor4312** [comment]
My concern with that approach is that it removes the ability to see the gutter icons at a glance

**Comment by misolori** [comment]
Another idea (taking the combining icon approach) is making half the glyph area clickable for one action and the other half for setting a breakpoint. Once we have two glyphs, we show a context menu for the various actions. Here's a simple prototype:


https://user-images.githubusercontent.com/35271042/105527416-891b8a80-5c98-11eb-9ace-a52584b42996.mov

**Comment by isidorn** [comment]
@misolori I think the half half idea does not really scale, since if there are 3 it would not work.

If you think it is resonable to expect that mutliple decorations can be merged and this looks good then we should go down that approach. I personally think this will automatically not look good, and we should have some icons prepared for some known overlapps. So for example when a test decoration overlaps with a breakpoint we show our previously designed icon by using the `glyhWidget.merge` API. If we do not have a preset icon, then we should show have some default one...

Inteli-sene approach of expadning the whole margin looks ugly to me.

**Comment by misolori** [comment]
So we either need to find a generic icon that means "more than 1 glyph" but for @connor4312 that doesn't work. We can't show all glyphs as we don't have space for it.

**Comment by connor4312** [comment]
Maybe just show the glyph with the highest z-index with some indicator (like 🔽 ) beside it, and have click actions (which are not formalized for the glyph margin right now, but could be) always open the context menu.

This would require that the breakpoint drag action be startable from the context menu, which I think is less intuitive but probably fine.

**Comment by isidorn** [comment]
Thanks for ideas! Let's assign this to February, and I plan to bring it up in our first UX meeting in that milestone so we can continue the discussion there.

@connor4312  Agree, being able to drag and drop a breakpoint when there are multiple decorations there is a bit of an edge case and I would not really worry about it at the moment. Agree that option 2 is a good start.

**Comment by eamodio** [comment]
FYI, this is very related to: https://github.com/microsoft/vscode/issues/47559

**Comment by isidorn** [comment]
We did not have cycles this milestone, pushing out to April for now.

**Comment by connor4312** [comment]
Since we now have time before testing is finalized, let's try to get this in next iteration to present a more polished experience for users 🔮

**Comment by isidorn** [comment]
Not happening this milestone -> On deck. Connor feel free to move to august if you would like to tackle next mielstone.

**Comment by karthiknadig** [comment]
Just adding here a potential bug with coloring:
![image](https://user-images.githubusercontent.com/3840081/129233709-48f07bec-6aa4-48c6-9f12-bbd56fdd0141.png)

This happens if you `Add Breakpoint` after successfully running a test.

**Comment by lukas9393** [comment]
If you use the [vscode-go](https://github.com/golang/vscode-go) plugin and set coverage decorator to `gutter`, it is not possible to set a breakpoint in the areas where coverage is shown.

```json
"go.coverageDecorator": {
  "type": "gutter",
}
```

https://user-images.githubusercontent.com/11976901/130292326-91eca31a-f98e-41d3-ade6-8a3a2367032e.mov

Maybe the extension should not offer the configuration `gutter`, as long as VSCode does not allow overlapping decorations in gutter (for this it is of course the wrong repository). However, I wanted to mention the case here so it can be included.

**Comment by JamyDev** [comment]
@isidorn Any update on this? We're facing the same issue as @lukas9393 and had to switch to highlight to show coverage as a temporary workaround.

**Comment by isidorn** [comment]
No updates, sorry.

**Comment by r3m0t** [comment]
Is this considered part of the same bug? When a test is running, the custom decoration (`gutterIconPath`) spins with the "test running" symbol.

You can see it with this extension - https://github.com/ryanluker/vscode-coverage-gutters

Here's my code:
```
dark: {
                gutterIconPath: gutterSetting
                    ? vscode.Uri.joinPath(this._ctx.extensionUri, "media", "gutter-icon-dark.svg")
                    : "",
                backgroundColor: lineSetting ? "rgba(0, 122, 30, 0.4)" : "",
            },
```
