### ISSUE TITLE
Search/replace crashes VC

### ISSUE THREAD

**Issue by hencomb** [microsoft/vscode#114760]
[style.bundle.css.zip](https://github.com/microsoft/vscode/files/5856036/style.bundle.css.zip)

We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Steps:

1.  Open a large minified CSS file.

2. search/replace for #181c32 with #666666

3.  crash

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (4.41GB free)|
|Process Argv|--crash-reporter-id 6f431879-5fa7-486b-b9ec-8fbb7f805e58|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.4
vscode-intelephense-client|bme|1.6.2
htmltagwrap|bra|0.0.7
auto-comment-next-line|ctf|0.1.0
dart-code|Dar|3.18.1
flutter|Dar|3.18.1
jshint|dba|0.11.0
githistory|don|0.6.14
jquerysnippets|don|0.0.1
vscode-great-icons|emm|2.1.64
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
php-debug|fel|1.14.5
auto-rename-tag|for|0.1.6
vscode-indent-on-paste|gaz|2.4.0
todo-tree|Gru|0.0.196
vscode-perl|hen|1.17.0
beautify|Hoo|1.5.0
path-autocomplete|ion|1.17.0
minifyall|jos|2.4.13
vscode-linthtml|kam|0.5.0
auto-comment-blocks|kev|1.0.1
PHPDocument|man|1.0.3
vscode-checkpoints|mic|1.3.1
HTMLHint|mka|0.10.0
theme-monokai-pro-vscode|mon|1.1.18
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
material-icon-theme|PKi|4.5.0
subtle-brackets|raf|3.0.0
pdf|tom|1.1.0
vscode-icons|vsc|11.1.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.12
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244:30244299
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by sandy081** [comment]
Can you please share the file in which the crash happens?

**Comment by roblourens** [comment]
I think it is attached @sandy081 

But @hencomb are you doing find/replace just in the file, or across the workspace (in the sidebar)?

**Comment by sandy081** [comment]
Yes, you are right, I missed it. Thanks.

**Comment by hencomb** [comment]
Hi Rob - no it was just in the file (option-command-f on a mac)

Regards
Henry

**Comment by hencomb** [comment]
Typical action to trigger the crash:  search/replace #9c97da or some other
color with #000000

**Comment by hencomb** [comment]
Don't know if this is related (although it only happens when I
search/replace in a huge file) - and because I have dart/flutter extensions
installed - my machine starts to get hot and the activity monitor shows the
culprit:

[image: image.png]

**Comment by sandy081** [comment]
@hencomb Thanks for info. I could not reproduce the crash. I am sorry that I do not understand which replace feature are you using. We have replace functionality at two places

1. On the file itself - which is shown below

![image](https://user-images.githubusercontent.com/10746682/106018790-35f36e80-60c2-11eb-9ade-c5e554cdca35.png)

2. Global search/replace which is shown below

![image](https://user-images.githubusercontent.com/10746682/106018849-44da2100-60c2-11eb-83fb-80b824ab3ac7.png)

Please let us know which one you are using.

If it is hang please provide more information (say profiling) by following the wiki - https://github.com/microsoft/vscode/wiki/Performance-Issues

If it is. crash provide more information by following the wiki - https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
