### ISSUE TITLE
Allow to dock editors, views and panels anywhere in the workbench

### ISSUE THREAD

**Issue by ehouarn-perret** [Microsoft/vscode#11472]
Would be nice if tabs (inc. Terminal) could be arranged with a docking layout component like, it's kinda frustrating to not be able to have the layouts we are used to work with.

**Comment by bpasero** [comment]
@ehouarn-perret can you clarify what that means?

**Comment by ehouarn-perret** [comment]
@bpasero sure, basically right now the layout can only be vertical, it would be better if the editor could provide more layout options, a sort of docking like component. This would not only applicable to the code editor part but also to the console.

**Comment by ehouarn-perret** [comment]
Out of curiosity, are (free) external components allowed to be in used when developing a feature? Like for example https://golden-layout.com/ I haven't checked for that one and probably need a lot of integration work but something like that but you get the gist.

Considering that there is already something in use for the current tabs system I guess and assume it's probably better to simply leverage and extend what is already existing.

**Comment by Alex-Addy** [comment]
Has there been any progress on this? Something general like this, or more specifically #14148 would be very helpful for my situation and this appears to have been forgotten.

**Comment by costincaraivan** [comment]
In case there's MS devs taking a look at this issue, what some people want (myself included) is basically the workflow from screen/tmux + vim or from Emacs or more recently from vim itself, which now has a terminal command built-in.

Basically there's a grid layout and you can put anything in the grid sections. Generally "anything" is either a editor window or a terminal but it can be a documentation browser or something else.

This is obviously very powerful and flexible. Visual Studio Code has a more limited design, inspired by good ole Visual Studio, with 1 debug console, 1 problem window, 1 output window etc. For terminal windows especially it would make a lot of sense to have them embeddable in any grid section.

**Comment by ehouarn-perret** [comment]
@costincaraivan 
Well something slightly more flexible is also okay ;-)
I keep thinking that something like https://golden-layout.com/ in the Visual Studio code fashion would be the way to goooooo!

**Comment by ehouarn-perret** [comment]
The grid layout feature has been released!
