### ISSUE TITLE
Hot exit not working in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114719]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Install Jupyter extension
2. Ensure auto save is tuned off
2. Open a notebook
3. Make changes to a cell
4. Reload VS Code
5. The changes are lost

The Jupyter extension is handling the call to `backupNotebook` & is returning the `id` of the back.
However when `openNotebook` is invoked by VS Code, the `backupid` in the `NotebookDocumentOpenContext` is empty.
FYI - this used to work. Has the API changed in VS Code (should we be using `NotebookDocumentBackupContext` in the `backupNotebook` method, this is ignored today).

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
Not aware of any change with the back api. Will take a look

**Comment by rebornix** [comment]
Can't reproduce this issue with GitHub Issue Notebook. @DonJayamanne can you share what version of VS Code you are using, on what OS? If you are using OSS, then it will not work as designed.

**Comment by DonJayamanne** [comment]
* Setup & Debug the Jupyter extension
* Set breakpoint in `openNotebook` of https://github.com/microsoft/vscode-jupyter/blob/b368ea9326c13d6497e0f070d89d810d4ff86416/src/client/datascience/notebook/contentProvider.ts
* Set break point in same file in `backupNotebook`
* Open an existing notebook
* Make changes (edit a cell)
* Confirm backupNotebook method is invoked & backup id is returned.
* Reload VS Code
* Confirm `openNotebook` is invoked and notice how `backupId` is empty.

**VS Code version is**
Version: 1.53.0-insider
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:17:02.999Z

**Comment by DonJayamanne** [comment]
Just saw the GitHub issues code, looks like in there you're writing to the file provided. Hmm, we always backup to our own file & return a backupid.
Interesting how this works, we never did write to that.

**Comment by DonJayamanne** [comment]
> I guess we need to use the same mechanism.

Lets discuss this in person. We didn't do this in the past, same goes with CustomEditor support.
We backup to our own file & return our own `backupId`.
Looks like something changed in VS Code that prevents this from working with our own backupid. I.e. we're now forced to use the VSC file.

**Comment by nasosev** [comment]
Same problem for me on v1.52.1.

**Comment by DonJayamanne** [comment]
@rebornix thanks for your help, confirmed this works but not when debugging.
