### ISSUE TITLE
[json] Allow "json.validate.enable": false in settings / disable JSON validation or error checking

### ISSUE THREAD

**Issue by bn-l** [microsoft/vscode#114775]
It would be good if we could turn off the inbuilt JSON validation. I don't think people realize how painful these warnings are for people with OCD / ADHD. I want to turn it off and run ad lib or run a command line linter only.

Steps to Reproduce
set "json.validate.enable": false in settings
json files are still validated
Does this issue occur when all extensions are disabled?
Yes

Versions 1.52.1
Windows 10

**Comment by emretepedev** [comment]
yes! exactly what i need.

**Comment by kconedera** [comment]
I also need this. The constant validation warnings while I'm typing in .json files has made vs code completely unusable for me.

**Comment by yume-chan** [comment]
You can disable the "JSON Language Features" built in extension (search for `@builtin json-language-features`)

**Comment by emretepedev** [comment]
> I pushed a change that implements the new setting for the next release.

Thanks!
