### ISSUE TITLE
With lines wrap, I cannot jump to physical EOL, only to logical one

### ISSUE THREAD

**Issue by Kri-Ol** [Microsoft/vscode#11473]
- VSCode Version:1.4
- OS Version:Windows 10, Linux

Steps to Reproduce:
1. File with long lines, wrapped in editor
2. <End> will move cursor to logical EOL, not physical EOL

**Comment by alexandrudima** [comment]
Since a few releases, pressing <kbd>End</kbd> does:
* on first press, goes to end of wrapped line.
* on second press, goes to end of physical line.
