### ISSUE TITLE
Editor tabs to reflect git status of a file

### ISSUE THREAD

**Issue by chrissyast** [microsoft/vscode#114765]
In "Open Editors" there are already different colours for unchanged (white), changed (yellow), and new (green) files

![image](https://user-images.githubusercontent.com/31564153/105499571-9432e280-5cb9-11eb-8cc4-d245839f5d98.png)

I would like this colour scheme to also apply to the editor tabs.

**Comment by chrissyast** [comment]
No, not covered by #43292

**Comment by gjsjohnmurray** [comment]
This already happens in Insiders and will arrive in the next Stable, due out next month.
