### ISSUE TITLE
Avoid collapsing TreeView when selecting node

### ISSUE THREAD

**Issue by xldenis** [microsoft/vscode#114766]
This is more of a request to undo a regression that occured than introduce a new feature. It seems that over the past two years the functionality introduced to resolve #34130 was lost. 

The problem I'm having is that _selecting_ a `TreeViewItem` also changes its `CollapsedState`. I'd like to control this behavior for a tree view I'm introducing in an extension. What I would imagine is that the item would only expand if we click on the triangle to the left hand side of the item.

**Comment by joaomoreno** [comment]
@alexr00 There is some discussion to switch the default behavior for trees: they should only collapse/expand on when interacting with the twistie.

**Comment by alexr00** [comment]
For completeness, the current behavior of extension provided trees (as arrived at in #34130):
- When the tree item has a command, expand/collapse is _only_ controlled by the twisie.
- When the tree item _does not_ have a command, expand/collapse is controlled by clicking on the entire tree element. 

@joaomoreno thanks for the heads up on the twistie discussion. I will defer to whatever is decided in that discussion to maintain consistency.
