### ISSUE TITLE
Keyboard shortcuts on wrong keys after changing from layout to other

### ISSUE THREAD

**Issue by Jaakkonen** [microsoft/vscode#114713]
- VSCode Version: 1.52.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Use sway
2. Set keyboard layout to `workman,us` with `swaymsg input type:keyboard xkb_layout workman,us`
3. Open vscode
4. Keyboard shortcuts are set to keys corresponding to that layout
5. Change layout with `Super + Space`
6. Shortcuts persist on same keys and not changing to the keys in the current layout.
   For example C key is at V in workman and V in B. Now copy is Ctrl+V and paste Ctrl+B.

Expected behavior:

Keyboard shortcuts would work with the keys set in Keyboard Shortcuts menu and change to mach the current keyboard layout.

Other knowledge:

- Reloading window doesn't help. Full restart with all windows closed is the only way to get the new keyboard layout recognized
- Could be fixed by using key charactes to trigger shortcuts, not keycodes which are looked up from layout at startup

Does this issue occur when all extensions are disabled?: Yes

**Comment by Jaakkonen** [comment]
Looking at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings it seems that `"keyboard.dispatch": "keyCode"` got it working. I still think that it should be the default on Linux platforms as it's not that error prone as just using the raw keycodes is. 

The configuration is showing keys by name and not their scancode and thus leads users to think it's the key names being used when in fact they're not.

**Comment by alexdima** [comment]
Let's track in #24166
