### ISSUE TITLE
Can't open entry 0 from list in Debug mode , debug line in foreground

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#114756]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

![2021-01-22 13_32_05-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/105491574-c8f16a80-5cb6-11eb-8d7e-371be0391d78.png)

Steps to Reproduce:

1. Have a list with many entries
2. Debug your code
3. Hover over the list variable
4. Try to open entry 0

Does this issue occur when all extensions are disabled?: Yes

My display Settings:
![2021-01-22 13_36_31-Settings](https://user-images.githubusercontent.com/17874713/105491624-e292b200-5cb6-11eb-88bf-2fd8da37ba49.png)

**Comment by isidorn** [comment]
Move the debug toolbar somewhere.... Or just dock it via debug.toolbarLocation: docked
No action planed here, thus closing

**Comment by TobiasSekan** [comment]
Thanks, i didn't know that.
