### ISSUE TITLE
Some extension icons are missing

### ISSUE THREAD

**Issue by tetious** [microsoft/vscode#114703]
Issue Type: <b>Bug</b>

Starting with the noted version, various icons that extensions add are blank. I'm not sure of what to call the spots in the UI where this is happening, so please have a look at the screenshots which make it clear.

![sidebar](https://user-images.githubusercontent.com/55581/105356588-974aa780-5bc1-11eb-8be7-446cc3522048.png)
![topbar](https://user-images.githubusercontent.com/55581/105356598-987bd480-5bc1-11eb-9d14-3babbe61fc52.png)

This impacts the Docker and GitLens extensions, but certain others (GitHub) aren't affected, mysteriously.

The problem recurs immediately at startup, and is consistent.

VS Code version: Code - Insiders 1.53.0-insider (1a4b35c2023a41efae1af2661026d57cea90ef5c, 2021-01-21T05:14:13.256Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.9.16-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 14c50ee1-a00b-46b0-abaf-6965d9e59493|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: putz|
|OS|Linux x64 5.9.16-200.fc33.x86_64|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 2195)|
|Memory (System)|31.33GB (9.41GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
dotenv|mik|1.0.1
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
vscode-icons|vsc|11.1.0
ng-template|Ang|11.1.0
gitlens|eam|11.1.3
dotnet-test-explorer|for|0.7.5
vscode-pull-request-github|Git|0.22.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
vscode-versionlens|pfl|1.0.9
code-spell-checker|str|1.10.2
msbuild-project-tools|tin|0.3.11

</details>

**Comment by tetious** [comment]
Ahh, great catch. Looks like it's remote only extensions for me too.

**Comment by yume-chan** [comment]
Maybe same as #113256, also using remote develop extensions, also in dark theme, also messing GitLens icons.

**Comment by joaomoreno** [comment]
cc @eamodio

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/114743 , please follow that issue for updates. Thanks!
