### ISSUE TITLE
navigator.usb.requestDevice immediately returns "DOMException: No device selected." without prompting for device selection in custom editor

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [microsoft/vscode#114733]
- VSCode Version: 1.53.0
- OS Version: Window 10 Version 10.0.19041 Build 19041

Steps to Reproduce:

1. Create an extension that exposes a custom editor
2. In the custom editor setup an event listener for some user action (button click, keypress, etc) and in response request access to a USB device attached to your system
```
document.addEventListener('keydown', event => {
    const filters = [{vendorId: 0x046D, productId: 0xC52B}] // Swap Ids to those of a USB device attached to your system
    navigator.usb.requestDevice({filters}).then(dev => console.log(dev))
}
```
3. Initiate the user action and observe the error "DOMException: No device selected." reported in console without the user being prompted to select a USB device.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Relates to electron/electron#14545

You can use the [usb](https://www.npmjs.com/package/usb) package in your main extension code, and communicate with your custom editors via messages

**Comment by dread-pirate-johnny-spaceboots** [comment]
Fantastic, thank you. Apologies for not seeing the existing issue in my search 🙏
