### ISSUE TITLE
The debug function disabled, when I connect to linux server.

### ISSUE THREAD

**Issue by hooyubin** [microsoft/vscode#114735]
when I connect to the linux server, the debug function is disabled.
![微信图片_20210122105206](https://user-images.githubusercontent.com/26893483/105439573-10203100-5ca0-11eb-8d7a-d31ceb38d36e.png)
Linux server system info:  Linux kylin 4.4.58-20170818.kylin.5.desktop-generic #5 SMP Fri Aug 18 10:19:03 CST 2017 aarch64 aarch64 aarch64 GNU/Linux

**Comment by weinand** [comment]
How do you connect to the linux server?
