### ISSUE TITLE
Typescript Intellisense sorts incorrectly capitalized single-letter word

### ISSUE THREAD

**Issue by RainingChain** [microsoft/vscode#114739]
Issue Type: <b>Bug</b>

Create a new typescript file.

Enter the code:
```
const {b, B} = {b:{x:1}, B:{x:1}};
```

On a new line, type `b` then `Enter`. `b` is transformed into `B`.
Type `b` then `.` and `B.x` is written.

Expected behaviour:
Typing `b` then `Enter` should write `b`.

Strangely, the bug doesn't occur for  `const {a, A} = {a:{x:1}, A:{x:1}};`

VS Code version: Code - Insiders 1.53.0-insider (eaa959d34b863dec932077d94daece22504a396b, 2021-01-18T05:13:25.733Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HK CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.30GB free)|
|Process Argv|--crash-reporter-id 139c5582-267c-4379-bb57-9f98b505d0e3|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
vstes516:30244333
pythonvspyt600:30247031
core-portspanel:30233467

```

</details>

**Comment by mjbvz** [comment]
@jrieken Looks like the entries for `b` and `B` have the same score here. Could the suggest widget prioritize exact matches that have the same case as the text to be replaced?

**Comment by jrieken** [comment]
> Strangely, the bug doesn't occur for const {a, A} = {a:{x:1}, A:{x:1}};

Not for me, but you might have selected `a` before and now we remember that

> @jrieken Looks like the entries for b and B have the same score here.

Yes, both have the same score and then we fallback to provider-order. Boosting prefixes that matches a suggestion perfectly might be an option and that will also always prefer suggestions that are a prefix of a longer suggestion.
