### ISSUE TITLE
"Open file" scrolling buttons not working

### ISSUE THREAD

**Issue by sweettyler** [microsoft/vscode#114789]
Issue Type: <b>Bug</b>

1) launch VScode;
2) select "File"-> "Open file";
3) then you get the file selection window as shown in the attached snapshot;
4) both arrow buttons (circled in red) don't work;
5) if you enlarge the window you'll find the current folder is at the right end. However you cannot see it by clicking the scrolling buttons alone - to see it you have to enlarge the window.

This is a long time bug in all the recent VScode versions (including the insider versions).

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 3.10.0-693.17.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (32 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|187.41GB (110.02GB free)|
|Process Argv|--no-xshm --disable-renderer-accessibility --no-sandbox --crash-reporter-id 40a71cf6-f3f4-454f-8c70-7d5cca2ef0c9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.2
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.1.3
material-icon-theme|PKi|4.5.0

</details>

**Comment by sweettyler** [comment]
![scroll_buttons2](https://user-images.githubusercontent.com/49961658/105533646-0a334b80-5cb2-11eb-9629-e8a93ee5c1ef.png)

**Comment by IllusionMH** [comment]
Looks like initial screenshot (with circles) is missing

**Comment by sweettyler** [comment]
Here it is.
![scroll_buttons](https://user-images.githubusercontent.com/49961658/105565999-4933c200-5cef-11eb-8d9e-fd92ff80f93d.png)

**Comment by joaomoreno** [comment]
Please file an issue to Electron: https://github.com/electron/electron
