### ISSUE TITLE
Syntax errors detected in JSON files do not disappear after they are fixed.

### ISSUE THREAD

**Issue by awshelley-beckman** [microsoft/vscode#114788]
- VSCode Version: 1.52.1
- OS Version: Kubuntu 20.04

Steps to Reproduce:

1. Open a .json file
2. Add a trailing comma
3. Observe the red squiggly line, telling you that you have a trailing comma
4. Delete the trailing comma
5. Observe that the red squiggly line has not disappeared.

Does this issue occur when all extensions are disabled?: Yes/No
No.

**Comment by aeschli** [comment]
I am not able to reproduce with no additional extensions.
If you can, please attach a small code snippet that reproduces the issue.

You can try https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect to find out which extension causes the problem.
