### ISSUE TITLE
Cannot set workspace color theme to Dark+ (default), if user color theme is non-default

### ISSUE THREAD

**Issue by synchronos-t** [microsoft/vscode#114751]
Issue Type: <b>Bug</b>

In the **user** settings I've set the color theme to "Ayu Mirage Bordered", i.e. something other than the default (which is Dark+, with my Windows set to dark mode). I then tried to set the current **workspace** color theme to Dark+ in the Settings window, but it's not possible. In the Settings window the Dark+ is already selected, marked as default. I can select any other theme, but I cannot make the workspace setting to override the user setting with the default theme. If I change it to some other theme and then to Dark+, it just removes the `workbench.colorTheme` from settings.json.

Everything works just fine by using the settings.json file. This is only a problem when using the Settings window.

My solution proposition would be to make the default (i.e. "do not override") its separate item in the theme selection, and make it also reflect the setting the other settings are overriding it to (i.e. if I've set a user color theme to something other than default, it'd show its name, not the VSCode default color theme).

To reproduce:
1. Set user color theme to non-default (with settings.json or Settings window; doesn't matter), e.g. Monokai.
2. Open workspace Settings tab.
3. Try setting the workspace color theme to Dark+ (or Light+, if your Windows is in light mode). See that Dark+ is actually already selected.
(4. Try setting the workspace color theme to Monokai, then back to Dark+.)
(5. Try setting the workspace color theme to Kimbie Dark, then back to Dark+.)

Expected result:
- Current workspace would use Dark+, while all other workspaces still use Monokai.

Actual result:
- Dark+ is shown selected in the workspace settings.
- Current workspace still uses Monokai.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.66GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu-20.04/home/elmo/vainu-public --crash-reporter-id acaafb9d-d230-4d6d-8ed3-72c941ea5078|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.86GB (19.56GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.86GB (19.56GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.1
remote-wsl|ms-|0.52.0
ayu|tea|0.20.1
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
hubl|Hub|0.8.0
rainbow-csv|mec|1.8.0
vscode-docker|ms-|1.9.1
hexeditor|ms-|1.3.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by aeschli** [comment]
But removing the setting from the user settings will result in the dark theme, right?

**Comment by synchronos-t** [comment]
> But removing the setting from the user settings will result in the dark theme, right?

Yes, naturally, if I remove the user setting for the color theme, it either uses the VSCode default (which is Dark+) or the workspace setting (which has now nothing to override, if I want it to be Dark+, so it doesn't matter if it's there or not). There is only a problem, if I want to override the user setting with a workspace setting that is same as the VSCode default setting. (Using the Settings window, that is.)

**Comment by yume-chan** [comment]
See also #58038
