### ISSUE TITLE
Conditional breakpoints can severly slow execution and even stall application

### ISSUE THREAD

**Issue by MarByteBeep** [microsoft/vscode#114771]
At first I thought the problem described in #114048 had to do with older breakpoints. So I closed that one. But today I ran into the exact same issue again. 

It turns out that conditional breakpoints seem to be borked in some way. After setting one in my project, execution starts to slow down to the point that the whole application stalls and there is no way for me to even stop the execution. The only remedy then is to restart the application.

See video below for a demonstration.

[![VS code slows down after setting conditional breakpoint](https://img.youtube.com/vi/wOiczx-jGCk/0.jpg)](https://www.youtube.com/watch?v=wOiczx-jGCk)

Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by connor4312** [comment]
Thanks for the issue and video!

This is actually a bug in V8 and e.g. can be reproduced in the chrome devtools as well. I've opened an issue on Chromium for this: https://bugs.chromium.org/p/chromium/issues/detail?id=1169895

**Comment by MarByteBeep** [comment]
Thanks!!!
