### ISSUE TITLE
VS Code Search box has a limit - does not exclude Python .venv folder - gets cancelled

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode#114796]
- VSCode Version:
- OS Version:
I am in the GitHub Codespaces browser 

Steps to Reproduce:

1. Create a new Codespace using https://github.com/ucheNkadiCode/codespaces-docker-python
2. Press Ctrl + Shift + P and run command Python: Select Interpreter. Select the Python interpreter in your workspaces folder (e.g. ./pythonenv3.8...).
Press Ctrl + Shift + ` to open VS Code terminal and run python -m venv env to create a virtual environment. When VS Code prompts you to use this new virtual environment, select Yes. Otherwise Press Ctrl + Shift +P again, Select Interpreter and choose the interpreter ending with "env".
2. Ctrl + Shift + P Add Docker files to workspace
3. You will notice that although `manage.py` is found right in the workspace folder, it is not found on the list. Instead, the list is flooded with .venv files that were just created by the CLI command in Step 2. All of these files are not useful as an entrypoint. (The Docker Extension team has added code to now exclude .venv folders in our next update)

This makes it so that If I were to type in "manage.py" and hit Enter, the command gets cancelled immediately. This is because unfortunately the VS Code Search box does not have a "true/false" flag our Devs can set to allow an input that was not found in the search to still get input to our next steps (the way an input box does). 

I wonder how many other teams could possibly run into an issue where noisy folders could cause the search box to reach a limit and exclude other important files? Hopefully the limit can either be increase or there is a solution for searches to be rerun as the user is typing.

Does this issue occur when all extensions are disabled?: IDK

**Comment by IllusionMH** [comment]
VS Code doesn't know that folder is special. However you should be able to tell VS Code not to look into this folder explicitly by adding it to "files.exclude".

**Comment by roblourens** [comment]
Sorry I don't understand the request. Is it for the search to return different results? If so, the extension needs to change. Or is it to add a checkbox to the quick input control?

**Comment by ucheNkadiCode** [comment]
The scenario is that if a User is trying to do a command that has a stage in which they need to select a specific file (and they are using a VS Code Search box in this stage), they have any folder such as `node_modules` (for npm) or in this case `.venv` (for Python) which has way too many unnecessary files, the search box doesn't allow us to input a file that the search box does not find to still proceed to the next stage of the command. Instead it simply cancels the command.

In the case of "Docker: Add Dockerfiles to Workspace" we say "Please input the app's entrypoint", but because I created a virtual environment to install my django extensions to run my python app, a .venv folder is created and has way too many files. The entry point for our sample project should be "manage.py" but this file is not displayed in the VS Code Search box since .venv overwhelms the number of selections even though manage.py is in the root folder. I recognize now that I can add the .venv folder to files.exclude, but it would be nice to have the ability for our Extension developers to ALSO have an option to use a VS Code Search box that allow user input and DOES NOT depend on the search box actually finding the specific file to select.

**Comment by roblourens** [comment]
> it would be nice to have the ability for our Extension developers to ALSO have an option to use a VS Code Search box that allow user input and DOES NOT depend on the search box actually finding the specific file to select.

Sorry, I still don't understand the specific request that you have for vscode. I don't understand how the search is being executed or why the file is not found. Maybe you can tell me what you extension is doing here or share a screenshot.

**Comment by ucheNkadiCode** [comment]
@bwatersmsft Would you mind explaining to @roblourens what our extension is doing here? I am pretty sure you mentioned that the main issue is we're reaching a maximum limit and the search box is getting cut off so not all files are displayed. Then if they aren't displayed, they aren't selectable so the user is not able to move on to the next step of our command

**Comment by bwateratmsft** [comment]
@ucheNkadiCode I don't think we actually need anything from VSCode here. I realized that it was our own code requesting a maximum of 1000 files which is why it hit a limit--the .venv folder exceeded that.

We also already made a change to put manage.py and app.py at the very top of the list, and exclude everything in .venv.

The only improvement I could think of for `vscode.workspace.findFiles()` would be if it could accept a flag to sort in such a way that files in the root folder were first, then files 1 folder down, then files 2 folders down, etc.--so that you could more easily find stuff close to the root (which is probably more likely to be an entrypoint).

**Comment by roblourens** [comment]
We can't really control the search order due to the limitations of the search tool we use. Exposing the "max-depth" flag might be useful in some cases. Would like to do that when we revamp `findFiles` (no timeline for that however)

**Comment by bwateratmsft** [comment]
I did find a way to "cheat" to force a certain ordering; we wanted manage.py and app.py to be first--so my first search pattern is just those two, and then my second search pattern is everything else. It comes back in that order.

I don't know if glob patterns actually support this, but if so it could potentially be accomplished like this:
```
/*.py
/*/*.py
/*/*/*.py
/*/*/*/*.py
```
The caller could thus design in a maximum depth--based on the number of entries--and an ordering that considers files closer to the root first. It's cumbersome but possible (maybe? Still don't know glob that well :smile:)
