### ISSUE TITLE
TS Watch task build indicator stops working

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11470]
- VSCode Version: Code - Insiders 1.5.0-insider (5fb5131a7d8ab0245af3653fca77f31d7d81d735, 2016-09-02T15:34:16.539Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

Not sure how to reproduce - it just stops showing up at some point - might be related to starting debugger. The only way to bring it back is to kill watch task and start again

![j2ms44pseq](https://cloud.githubusercontent.com/assets/1723815/18212150/6a718ba8-710f-11e6-81d1-50d8e96ec826.gif)

**Comment by dbaeumer** [comment]
I tried to reproduce this but wasn't able to do so. @wallverb do you have a workspace you can share that shows the behaviour.

**Comment by wallverb** [comment]
@dbaeumer - I did not see it anymore with new versions of insiders so maybe it got autofixed :)

**Comment by dbaeumer** [comment]
@wallverb I will close the issue. Ping me if you see it again and I will investigate more.
