### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by KinjalDodiyaTechifysolutions** [microsoft/vscode#114744]
Issue Type: <b>Bug</b>

editor most of the time not savig file automatically.
editor didn't  redirect(jump) to function.
editor most of the time not working in collapse and expand.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz (4 x 3297)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|19.44GB (9.74GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b9d4618b-de96-4f8a-9f07-2eeb4e3e6996|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|Lubuntu|
|XDG_CURRENT_DESKTOP|LXQt|
|XDG_SESSION_DESKTOP|Lubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.38.0
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.14
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
shell-format|fox|7.0.1
dotenv|mik|1.0.1
mssql|ms-|1.10.1
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
gitblame|wad|6.0.2
vscode-import-cost|wix|2.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe use the Bisect command to investigate whether one of your extensions is causing the problems.

**Comment by KinjalDodiyaTechifysolutions** [comment]
> Maybe use the Bisect command to investigate whether one of your extensions is causing the problems.

thanks It helps
