### ISSUE TITLE
Undo last commit should warn user if they have uncommited changes

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11477]
- VSCode Version: 1.5.0
- OS Version: OS X 10.11.6

Steps to Reproduce:

- Choose any git repo, add a file `test.js` with the following content

```js
var foo = 1;
var bar = 2;
```

Add the file and commit it.

- Remove the second line, so the file ends up with:

```js
var foo = 1;
```

- In VSCode's git viewlet, choose `Undo Last Commit`

Now the file is:

```js
var foo = 1;
```

and this bit

```js
var bar = 2;
```

is permanently lost.

Suggestions:

1. If user has uncommited changes, prompt him to stash before doing Undo Last Commit. Or

2. Use `git reset --soft` instead of `git reset`, which defaults to `--mixed`. In this case, when user has staged but uncommited changes, prompt him to either commit or unstage them.
The benefit of using `--soft` this way is all last commit changes will end up in staged mode, whereas any local changes won't. So user could select which change they want, if the same file is edited both on last commit and locally.

**Comment by joaomoreno** [comment]
Great catch!

**Comment by joaomoreno** [comment]
Decided to simply disable the action.
