### ISSUE TITLE
Kubernetes extension icon not visible in the sidebar

### ISSUE THREAD

**Issue by moijes12** [microsoft/vscode#114740]
- VSCode Version: 1.53.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
After rebooting my setup on 22 January 2021, the kuberenetes extension was not visible in the sidebar. It was vsibile all the while till yesterday.

Does this issue occur when all extensions are disabled?: Not applicable. This is regarding the kubernetes extension.

**Comment by moijes12** [comment]
Thanks @joaomoreno

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/114743 , sorry about the issue. Please subscribe to the other issue for updates.
