### ISSUE TITLE
block plugins with blinking icons or disable blinking icons in plugin list 

### ISSUE THREAD

**Issue by rmgit** [microsoft/vscode#114784]
please block plugins with blinking icons or disable blinking icons in plugin list.
vscode is a great tool for focussed development work.
plugins like https://github.com/Dannark/Android-Launcher-for-VSCode with a blinking icon in the plugin list distract and annoy. 
to stop this selfish attention stealing behaviour block plugins like https://github.com/Dannark/Android-Launcher-for-VSCode.

**Comment by sandy081** [comment]
You can uninstall that extension if you do not like that or file an issue against that extension if you have bugs/features.

**Comment by rmgit** [comment]
i can not uninstall the plugin marketplace.
i do not have the plugins installed
