### ISSUE TITLE
Disable extensions only on local/remote

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#114731]
Our extension (ms-vscode.azure-sphere-tools) sometimes needs to be activated on local or remote manually. However, currently we can only set it to have higher priority to activate locally. And there is no way to disable it locally and activate it on remote.

So it would be nice to have a feature to disable an  extension only on local or remote.

**Comment by xisui-MSFT** [comment]
There used to be a way to "disable" it locally - uninstall locally. However, it's not possible in VS Code app anymore now, since "uninstall" will uninstall the extension both locally and remotely.

One workaround is to install it, and then remove it locally by deleting corresponding folders in %HOMEPATH%/.vscode/extensions.

**Comment by sandy081** [comment]
You can use the setting `remote.extensionKind` to override the extension kind behaviour and make it run locally or remotely - https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

**Comment by xisui-MSFT** [comment]
@sandy081 I think you misunderstood my question. So let me state this more specifically here.

Our extension has setting:
"extensionKind": ["ui", "workspace"]
Which means it prefers to run locally, and that's true for most our scenarios.

However, in some circumstances, we need it to run remotely, even when we are using the VS Code app. 

In our specific case, there's no way to test such circumstances programmingly. So the best way I can think of is to have way to let the user force the extension to activate remotely, or be able to disable the extension locally only.

**Comment by sandy081** [comment]
@xisui-MSFT you (user/extension author) can force that by adding following setting in your user settings file

```
"remote.extensionKind": {
		"ms-vscode.azure-sphere-tools": [
			"workspace"
		]
	},
```

**Comment by xisui-MSFT** [comment]
@sandy081 Ah I see what you mean. Would it be better to add this settings to the remote settings file?

**Comment by sandy081** [comment]
You can but depends upon user's use case.

**Comment by xisui-MSFT** [comment]
@sandy081 Thank you very much for the help!
