### ISSUE TITLE
Staging file maximizes unwanted folder

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [microsoft/vscode#114785]
- Extension version: 2.25.1
- VSCode Version: 1.5.2.1
- OS: Mac OS / Linux

Steps to Reproduce:

1. Have two folders in workspace with git repositories (folder 1 has to have a lot of changes for maximum effect)
2. Stage file in second folder with + icon in git extension tab
  - this expands the first folder.

Reason:
This is annoying when I try to go through one file at a time before staging. The sidebar does not stay in the same region as you clicked because the folder expansion displaces it. I have to scroll up and reminimize or scroll down.

edit: I think im in the wrong git repository. Is this the default git extension for vs code?

**Comment by RMacfarlane** [comment]
Thanks for the issue write-up, I moved it over to the main vscode repo since that's where this feature comes from
