### ISSUE TITLE
The project tree is visually confusing

### ISSUE THREAD

**Issue by rightbrainy** [microsoft/vscode#114722]
The project tree is hard to read at a glance.  It may be too compressed.  It looks more like a long list. When there are a lot of things it's hard to get baring.  Breaks flow. I'm sure there is some keyboard shortcut to sync to the current file but not obvious.  The tree in intelij for example is very clear and easy to use.  Could also make more use of color to distinguish different parts of the tree.

**Comment by IllusionMH** [comment]
Won't solve all requests, but you already can:

- > It looks more like a long list.

    increase `workbench.tree.indent` to make nested items more prominent, indentation 

- > I'm sure there is some keyboard shortcut to sync to the current file but not obvious.

    Set `"explorer.autoReveal": true` (default) which will focus current open file in Explorer or you can assign shortcut to `workbench.files.action.showActiveFileInExplorer`

- Install file icon themes that provide icons for specific files/folder names (but no background colors for folders).

**Comment by ArturoDent** [comment]
There is also `Workbench > Tree: Render Indent Guides`

**Comment by joaomoreno** [comment]
> The project tree is hard to read at a glance. It may be too compressed. It looks more like a long list. When there are a lot of things it's hard to get baring. Breaks flow. I'm sure there is some keyboard shortcut to sync to the current file but not obvious. The tree in intelij for example is very clear and easy to use. Could also make more use of color to distinguish different parts of the tree.

Can you show me a screenshot?

**Comment by rightbrainy** [comment]
It's better when indentation is increased.  I guess if you play around with fonts and spacing and search for the right extentions, improves a lot.  Overall I find myself going back to Jetbrains for everything. They pay a lot of attention to detail. Everything is more refined, smoother out of the box.

**Comment by joaomoreno** [comment]
> It's better when indentation is increased. I guess if you play around with fonts and spacing and search for the right extentions, improves a lot.

Thanks for the update! Closing this for now.
