### ISSUE TITLE
Terminal's text suddenly disappears

### ISSUE THREAD

**Issue by Ronkiro** [microsoft/vscode#114710]
Issue Type: <b>Bug</b>

* Steps to Reproduce: I really don't know, it occurs occasionally when using VSCode for a long time.

* Actual behavior: Terminal's text suddenly disappear.

![image](https://user-images.githubusercontent.com/27526023/105370686-95dda700-5be2-11eb-8dee-4e1536bd1fda.png)

![image](https://user-images.githubusercontent.com/27526023/105370861-c9203600-5be2-11eb-965f-991500ca446f.png)

Opening a new terminal fixes it:

![image](https://user-images.githubusercontent.com/27526023/105370749-a857e080-5be2-11eb-98f5-97c2977b2de1.png)

While into the issue's state, any new entry (For example, if you write a command) will also disappear. Commands like `clear` do not help.

This doesn't happens if using external terminal for a long time.

> Note: (I'm using Git Bash)

* Expected behavior: Terminal acting normally.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.67GB free)|
|Process Argv|--crash-reporter-id 5a732a24-3149-42eb-aa6e-f15a47c4d8f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
dotenv|mik|1.0.1
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
debugger-for-chrome|msj|4.12.11
vetur|oct|0.31.3
vscode-yaml|red|0.14.0
vs-code-node-require|tgr|1.4.7
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440cf:30242243
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30236629

```

</details>

**Comment by meganrogge** [comment]
does this happen if you use powershell?

**Comment by meganrogge** [comment]
does this happen if you use powershell?

**Comment by Ronkiro** [comment]
I was using powershell before, and yes it used to happen. But it's very occasional, on some days i can work on my projects without even facing it.

**Comment by meganrogge** [comment]
Closing this for now, please reopen it if you have a reliable way to repro it. Thanks
