### ISSUE TITLE
(Windows) Visual Studio Code blocks folder deletion

### ISSUE THREAD

**Issue by aureole82** [microsoft/vscode#114759]
Issue Type: <b>Bug</b>

1. Create a simple local git repository.
2. Create/Edit a simple file inside this repository with Visual Studio Code.
3. Try to delete complete local git repository: Windows explorer: "Folder Access Denied"
![image](https://user-images.githubusercontent.com/4819891/105493923-4f5b7b80-5cba-11eb-9a53-053129d30121.png)

**You can delete all inside the folder!! But you cannot delete the folder itself until closing Visual Studio Code.**
Maybe it's Gitlens fault!?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.33GB free)|
|Process Argv|--crash-reporter-id 5e72afc5-09b2-42d4-9f98-92954cbd46d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.1.0
gitlens|eam|11.1.3
vscode-liquid-snippets|kil|2.0.1
csharp|ms-|1.23.8
hexeditor|ms-|1.3.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-scss-formatter|sib|2.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by eamodio** [comment]
Can you disable all extensions and still reproduce this? Does this only happen with a Git repo, or does it happen with a normal folder (no git repo)?
