### ISSUE TITLE
Autocomplete doesn't work with snippets

### ISSUE THREAD

**Issue by smootok** [microsoft/vscode#114780]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur

Steps to Reproduce:

1. Add the following to the snippet configuration file.

```json
{
  "Print to console": {
    "scope": "javascript,typescript",
    "prefix": "log",
    "body": ["console.log($1);"],
    "description": "Log output to console"
  }
}
```

When I try to use the snippet it works but the autocomplete of `$1` doesn't.

**Comment by jrieken** [comment]
?  works but the autocomplete of $1 doesn't.

"doesn't" what? doesn't get inserted? doesn't insert a placeholder?

**Comment by smootok** [comment]
> > works but the autocomplete of $1 doesn't.
> 
> "doesn't" what? doesn't get inserted? doesn't insert a placeholder?

doesn't suggest autocompletion inside console.log()
Let's take an example.
If I have a variable named isActive and I use the snippet it doesn't suggest it. if I write console.log manually without snippet it does.

**Comment by jrieken** [comment]
this setting will help you `	"editor.suggest.snippetsPreventQuickSuggestions",`
