### ISSUE TITLE
`^[[D` appears in terminal when clicking on links

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#114767]
```
Version: 1.53.0-insider
Commit: 4f2341834e646360e603953b62bf6c6020b07a29
Date: 2021-01-22T08:55:11.282Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0
```
* configure `"editor.multiCursorModifier": "ctrlCmd"`
* `git clone https://github.com/microsoft/monaco-editor.git`
* `npm install`
* `npm run simpleserver`
* try to open the link printed in the terminal using `alt+click`:

https://user-images.githubusercontent.com/5047891/105504297-e11db580-5cc7-11eb-9073-b9f8298732b3.mp4

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/pull/114669/https://github.com/microsoft/vscode/issues/101136 was meant to fix this yesterday, @meganrogge can you verify whether it's fixed?

**Comment by alexdima** [comment]
@meganrogge I am quite confident I am on latest (I mentioned that in my OP):

```
Commit: 4f2341834e646360e603953b62bf6c6020b07a29
Date: 2021-01-22T08:55:11.282Z
```


https://user-images.githubusercontent.com/5047891/105536250-53a28b80-5cf0-11eb-9c00-a344fd0bbb30.mp4

**Comment by alexdima** [comment]
I just got a vscode update and I can reproduce also on:
```
Version: 1.53.0-insider
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:17:02.999Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0
```

It might be a problem specific to macOS ?

**Comment by meganrogge** [comment]
hmm, I'm thinking the [upstream setting](https://github.com/xtermjs/xterm.js/blob/4da5d557a5eaedc7ae45afd12fdc22216f940d20/src/browser/services/SelectionService.ts#L673) that I've exposed in VS Code is only looking for alt. So you are correct this is now just a mac issue.

**Comment by meganrogge** [comment]
regardless of OS, this is how that feature is set:

`altClickMovesCursor: config.altClickMovesCursor && editorOptions.multiCursorModifier === 'alt'`

so I have no idea how that feature is still getting activated for you

**Comment by Tyriar** [comment]
@alexdima thanks for the report, I managed to repro it and fix. The issue happened when you changed `multiCursorModifier` after creating the terminal in question.

**Comment by alexdima** [comment]
🎉 I've just tried it out on latest, and I no longer see `^[[D`
