### ISSUE TITLE
Testing 'Search in Open Editors': error when settings.json or keybindings.json open

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#114795]
@JacksonKearl 
Ref #20530

Steps to Reproduce:

1.  Have `settings.json` or `keybindings.json` open.  Non-configuration json files are no problem.
2.  Search in Open Editors errors - see error message in demo

![searchOpenJSONFile](https://user-images.githubusercontent.com/31813701/105539293-cd675480-5cb1-11eb-836e-ddd4300899f6.gif)

Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.53.0-insider (user setup)
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:18:22.679Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21292

**Comment by JacksonKearl** [comment]
Thanks, again only can repro on Windows. Less clear why that might be the case this time.

**Comment by JacksonKearl** [comment]
Error should be gone now, but results wont be found in user data files on windows yet.
