### ISSUE TITLE
Testing 'Search in Open Editors': nested file search term not found

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#114794]
@JacksonKearl 

Steps to Reproduce:

1.  Enable the experimental `Search in Open Editors`
2.  reload vscode
3.  open multiple files known to have a certain search term search term, at least one of those files not at the root level
4.  enable the search in open editors icon
5.  note that only the search terms in files at the root level are found, nested file search term is not found

![searchOpenDepth](https://user-images.githubusercontent.com/31813701/105536133-1f59ab80-5cad-11eb-83fc-f3b00495d070.gif)

Note that `numList.js` is not at the root level but does contain the search term `const fs`.  That file is found when the `Search only in open editors` icon is not enabled.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.53.0-insider (user setup)
Commit: 4f2341834e646360e603953b62bf6c6020b07a29
Date: 2021-01-22T08:57:22.447Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21292

**Comment by JacksonKearl** [comment]
Ref #20530

Investigating, can't repro on Mac.

**Comment by ArturoDent** [comment]
I can confirm this is now working for me on W10.

Before I file another issue on it - should the search in open editors find text in an unsaved/open editor?

**Comment by JacksonKearl** [comment]
It should, it did at one point must I must have broken it. I created #114956 to track just now.
