### ISSUE TITLE
lock scroll in integrated terminal

### ISSUE THREAD

**Issue by robstoll** [Microsoft/vscode#11479]
Would be nice if it is possible to set an option "lock scroll" in the integrated terminal (similar as in Eclipse) so that one can stop at a certain line and read on while output is written to the terminal below. 
In contrast to the current behaviour where one cannot stop and the terminal keeps on scrolling down.

**Comment by Tyriar** [comment]
Upstream issue #216

**Comment by Tyriar** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/11542
