### ISSUE TITLE
Find/Replace button in search pane opens a preview diff after applying the replace

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11475]
- VSCode Version: 1.4 or 1.5-insiders
- OS Version: Win/OSX

Steps to Reproduce:

1. Open the find pane on the side and do a global find/replace for anything
2. There are a list of results. When you click an item in the list, it opens a diff editor showing the effect of the find/replace. This is correct.
3. When you hover the cursor over an item, a button appears on the right side which you can click to apply the replacement. Click this.
4. It applies the replace to the file then opens a preview diff which doesn't show anything, since the change is applied.

It also opens the file where the replace happened, and I expect that, but not the preview diff.

**Comment by sandy081** [comment]
Expected behavior:

Replace on a single match shows
- the file if the file is active
- the file if there no more matches to replace
- the replace preview otherwise
