### ISSUE TITLE
Ominsharp

### ISSUE THREAD

**Issue by NEWBORN3** [microsoft/vscode#114746]
Issue Type: <b>Bug</b>

Ominshap downloads every time an instance of vscode is opened. sometimes it succeed but most of the time it doesn't.

Extension version: 1.3.6
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.72GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by 928PJY** [comment]
A bug is already created in [OmniSharp/omnisharp-vscode#3462](https://github.com/OmniSharp/omnisharp-vscode/issues/3462) to track this issue, but no response from them.

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Also, @NEWBORN3 your VS Code version is quite old. Current is:

 Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
