### ISSUE TITLE
theme bug:In a color theme, the function keyword colors are different

### ISSUE THREAD

**Issue by HondryTravis** [microsoft/vscode#114894]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.6.0(MacOS 10.15.7)
Steps to Reproduce:

## frist of all
in theme [Simple Dark]

then

![image](https://user-images.githubusercontent.com/24218012/105686310-0dd50580-5f32-11eb-957a-50906ab59be6.png)

1. method keyword in one object, but they color are different
2. method keyword in one Class, but they color are different

how did i can resolve this? please :D

**Comment by aeschli** [comment]
Can you paste a small but complete code example? 
You can use the `Inspect Editor Tokens und Scope` command to get more information on token at a given cursor position.

**Comment by HondryTravis** [comment]
Apologies, too busy before, thanks for you message

it's just like keyword, i try something.

@aeschli  hello

theme version: Simple dark[0.3.3 author: travis]

only in javascript file. as long as this color scheme appears once, it will always be like this, code is repeat, only change function name

but in html and typescript file is normal

![image](https://user-images.githubusercontent.com/24218012/105951614-4ea45a00-60ab-11eb-9ded-68931a0dffab.png)

**Comment by aeschli** [comment]
I'm not able to reproduce
```
var test = {
	text: 1,
	setCurrent(text) {
		this.text = text;
	},
	find: function () {

	},
	less: function () {

	}
}
```

![image](https://user-images.githubusercontent.com/6461412/115208255-a677bd80-a0fc-11eb-8fc3-d0f4e4166933.png)

**Comment by HondryTravis** [comment]
@aechan this code is normal
![image](https://user-images.githubusercontent.com/24218012/115262831-76193900-a167-11eb-9281-d86dfcc07a65.png)

**Comment by aeschli** [comment]
Thanks. I created https://github.com/microsoft/TypeScript/issues/43747 as the semantic highlighting code is now in the TypeScript extension.
