### ISSUE TITLE
Undo doesnt work properly

### ISSUE THREAD

**Issue by shubhamkes** [microsoft/vscode#114812]
Issue Type: <b>Bug</b>

Thank you Microsoft team for providing such a wonderful editor :) :)

However, nowadays am noticing that on pressing cmd+z, changes stuck between last two change and keep on repeating.
This is very annoying. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 6|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_69649 --crash-reporter-id e7cafd76-c409-4ff2-a473-876875367879|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-tailwindcss|bra|0.5.7
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.1.3
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
terminal|for|0.0.10
vscode-graphql|Gra|0.3.13
vscode-styled-components|jpo|1.4.1
vscode-github|Kni|0.30.4
vscode-wrap-console-log|mid|1.7.2
graphql|mqu|0.1.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.11
color-highlight|nau|2.3.0
addDocComments|ste|0.0.8
vscode-icons|vsc|11.1.0
vscode-import-cost|wix|2.13.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30244300
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Bisect command to investigate whether the problem is being caused by one of your extensions.
