### ISSUE TITLE
File/folder name editing - loses focus on shift + A (keybinding for creating a folder)

### ISSUE THREAD

**Issue by trompx** [microsoft/vscode#114857]
- VSCode Version: 1.51.1
- OS Version: Linux Mint 19.3

Steps to Reproduce:

1. Create a new file
2. Start editing its name
3. Each time I want to write an uppercase "A" with shift + A (keybinding which create a new folder) it exit editing the file name and try to create the folder.

When editing a file or folder name, keybindings shouldn't trigger.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Probable duplicate of https://github.com/microsoft/vscode/issues/111652.  I can reproduce in Stable but not in Insiders' Build.
