### ISSUE TITLE
Do not attempt to reopen files that lead to a crash in previous session

### ISSUE THREAD

**Issue by Matthijz98** [microsoft/vscode#114844]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open a file that is to big for your ram
2. VS code wil crashes with this error:
![image](https://user-images.githubusercontent.com/17087153/105616927-ba9c6f00-5dda-11eb-8a60-d43936aca844.png)
3. Click on of the options
4. VS code closes when I reopen it tryes it al again
5. Closing the file while it is loading it does not work

I would be nice to have a option "close file"

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Makes sense, slightly related https://github.com/microsoft/vscode/issues/57585

**Comment by bpasero** [comment]
Added a checkbox to control that:

![image](https://user-images.githubusercontent.com/900690/163927461-26d2b154-042c-42d1-a520-6a3100176a1b.png)
