### ISSUE TITLE
Code Command with Editor Group option

### ISSUE THREAD

**Issue by PKeves** [microsoft/vscode#114864]
When opening files with `code` CLI command, it would be nice to be able to select which editor's group the file will be open with, is it possible to integrate such feature?

Thanks in advance.

**Comment by xpe** [comment]
@PKeves What syntax would you recommend? 

How do you suggest specifying a group? (This part is non-obvious to me.)

Some background:

> By default, editor groups are laid out in vertical columns (for example when you split an editor to open it to the side). You can easily arrange editor groups in any layout you like, both vertically and horizontally
> ( https://code.visualstudio.com/docs/getstarted/userinterface#_editor-groups )
