### ISSUE TITLE
Markdown syntax color highlighting for markup.italic

### ISSUE THREAD

**Issue by poychang** [microsoft/vscode#114874]
There has no color highlighting for italic in markdown syntax, both dark and light theme. It would be very nice to see the color added, like other themes.

In markdown syntax, the italics of dark and light VSCode themes are not used to display colors. it's nice to see the added color.

![image](https://user-images.githubusercontent.com/4879879/105653577-1eb45580-5ef7-11eb-9979-6540ee2e58ad.png)

**Comment by mjbvz** [comment]
Themes can contribute a color for italic markdown content. The default dark+ chooses to italicize the text instead
