### ISSUE TITLE
code-insiders issue

### ISSUE THREAD

**Issue by D-Nouveau** [microsoft/vscode#114852]
Issue Type: <b>Bug</b>

In the project folder, when I tried to launch code-insiders, it just launched the VS code, not the project directory.

VS Code version: Code - Insiders 1.53.0-insider (ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57, 2021-01-22T17:18:22.679Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (0.45GB free)|
|Process Argv|--remote=wsl+Ubuntu --crash-reporter-id 571a8e74-6b5b-4f41-acb7-6a6e1a336e79|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.52.0
cpptools|ms-|1.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
vstes627:30244334
pythonvspyt600:30247031
core-portspanelcf:30233468

```

</details>

**Comment by bpasero** [comment]
@D-Nouveau can you clarify what exactly you did and how to reprodcue?

**Comment by D-Nouveau** [comment]
Sure,
I have my project files in the "projects" folder,  so I did `cd Desktop/projects`; after getting into this directory, I tried opening it into the VS code using `code-insiders` after the command the VS code was opened, but it was the homepage, not the current project folder.

**Comment by bpasero** [comment]
@D-Nouveau if you just type `code-insiders` it will restore whatever session you had before. To open that folder you are in, you need to type `code-insiders .`

**Comment by D-Nouveau** [comment]
Thank you so much! It worked.
