### ISSUE TITLE
F5 no longer launches electron project that previously worked

### ISSUE THREAD

**Issue by kakyoism** [microsoft/vscode#114887]
- VSCode Version: 1.52.1
- OS Version: Windows 10
- node.js Version: 12.18.3

Steps to Reproduce:

1. Create an empty electron project
2. Create a simple main.js file
3. Create the following `launcher.json`

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Debug Main Process",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceFolder}",
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceFolder}\\node_modules\\.bin\\electron.cmd"
        },
        "program": "${workspaceFolder}/src/main.js",
        "protocol": "inspector",
	      "console": "integratedTerminal",
        "sourceMaps": true,
        "runtimeArgs": [
          "--enable-logging",
          "--remote-debugging-port=9223"
        ]
      },
      {
        "name": "Debug Renderer Process",
        "type": "chrome",
        "request": "launch",
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceFolder}\\node_modules\\.bin\\electron.cmd"
        },
        "runtimeArgs": [
          "${workspaceFolder}/src/main.js",
          "--remote-debugging-port=9222"
        ],
        "sourceMaps": true
      },
      {
          "name": "Attach",
          "type": "node",
          "request": "attach",
          "port": 5858,
          "address": "localhost",
          "restart": false,
          "outFiles": [],
          "localRoot": "${workspaceFolder}",
          "remoteRoot": null,
          "sourceMaps": true
      }
    ]
  }
  
```

On F5, Then VSCode complains that it cannot find node.js in PATH, although my node binary folder is already in the system PATH.

Does this issue occur when all extensions are disabled?: Yes

I've tried to add this property:

```json
        "nodeVersionHint": 10
```
[as instructed here](https://github.com/microsoft/vscode/issues/102035#issuecomment-656801666) to no avail

**Comment by weinand** [comment]
@kakyoism which of the three launch configurations in your launch.json are you actually running?

**Comment by kakyoism** [comment]
> @kakyoism the launch configurations need to go in a file "launch.json", not "launcher.json".
> It looks like VS Code does not found any launch config and tries to launch your project via the fallback node.js behavior
> (for launching electron no node.js is needed).

The second one. It works on macOS without issues.
