### ISSUE TITLE
After installing the extension will automatically disappear!

### ISSUE THREAD

**Issue by Luncher** [Microsoft/vscode#11489]
- VSCode Version: 1.4
- OS Version: fedora21

Steps to Reproduce:

1.  code .

2.  click extension menuItem&show recommended extensions
![screenshot from 2016-09-03 15 09 02](https://cloud.githubusercontent.com/assets/5138977/18223384/89342b42-717b-11e6-8a03-46aa109b3464.png)

3. install PHP Debug&After the installation is complete, list the already installed extensions.

![screenshot from 2016-09-03 15 16 02](https://cloud.githubusercontent.com/assets/5138977/18223407/743e41c2-717c-11e6-9b93-cdadc9280ca7.png)

4.click the enable `PHP Debug extensions`& list the already installed extensions.

![screenshot from 2016-09-03 15 17 46](https://cloud.githubusercontent.com/assets/5138977/18223411/9f05d564-717c-11e6-87ed-a35e2a4870ed.png)

![screenshot from 2016-09-03 15 18 15](https://cloud.githubusercontent.com/assets/5138977/18223416/b04c0d84-717c-11e6-9bf1-d6355d8da514.png)

**Not found PHP Debug extension**

The problem is not the problem itself extension, Other extension-ins also exist such problems.

**Comment by joaomoreno** [comment]
I can't reproduce.

Do you have a `.vscode/extensions/.obsolete` file?

**Comment by Luncher** [comment]
After the restart problem persists.

not found the `.obsolete` file.

![screenshot from 2016-09-06 10 08 38](https://cloud.githubusercontent.com/assets/5138977/18259748/157ae6f8-73ad-11e6-866a-07accd4d5e47.png)

**Comment by Luncher** [comment]
![screenshot from 2016-09-06 10 11 38](https://cloud.githubusercontent.com/assets/5138977/18259770/593f0c7a-73ad-11e6-80ec-3179d21b31f5.png)

**Comment by joaomoreno** [comment]
Does it reproduce if you uninstall the `Shan.code-settings-sync` extension?

**Comment by Luncher** [comment]
Feeling is `Shan.code-settings-sync` problems.

After uninstall  `Shan.code-settings-sync`  can't reproduce it.

thankyou!!

**Comment by joaomoreno** [comment]
Please let the extension developer know.
