### ISSUE TITLE
IntelliSense from remote CDN

### ISSUE THREAD

**Issue by jimmywarting** [microsoft/vscode#114891]
Some developers host there esm script directly on a CDN so you can use `import` directly in the browser. Some even provide JSDoc on dev build files.

It would be grate if vscode could download remote javascript files to a temp directory, cache it and parse it accordingly and even work offline after the files have been downloaded from a CDN.

Deno are one that acts more like the browser and they don't use any package mananger. (neither dose the browser) they simply just import something from a absolute http path from some CDN and starts coding

```js
// vscode downloads remote file and scans it
import sdk from 'https://example.com/sdk-dev-esm.js'

// vscode provide autosuggestion
sdk...
```

if this was supported then you wouldn't need any npm modules to provide autocompletion
A plus would be if it also could provide IntelliSense based on SourceMaps from the original source code.

**Comment by mjbvz** [comment]
Our JavaScript and TypeScript intellisense is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
