### ISSUE TITLE
Snippets and IntelliSense do not work for Python

### ISSUE THREAD

**Issue by mikemadden42** [microsoft/vscode#114868]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

Code Snippets and IntelliSense do not work for Python.  This has worked for me before.

For example, if I type the `def` keyword, code normally snows a popup to insert a snippet which contains a basic definition of a Python function.  The snippet for the function no longer works.  The `def` keyword is entered and the snippet is not created.

![Screen Shot 2021-01-24 at 14 19 48](https://user-images.githubusercontent.com/5888518/105642553-11905b80-5e50-11eb-982c-f0ff18c1de32.png)

Similarly IntelliSense no longer works.  Generally I would get a list of methods and attributes when I enter a dot `.` for an object.  Now I just get a popup that it is loading.

![Screen Shot 2021-01-24 at 14 20 45](https://user-images.githubusercontent.com/5888518/105642618-63d17c80-5e50-11eb-9069-768c3a8d48a8.png)

Here is the version of the Python extension I'm using.

![Screen Shot 2021-01-24 at 14 22 26](https://user-images.githubusercontent.com/5888518/105642642-895e8600-5e50-11eb-94b7-1b28a217d3b5.png)

Does this issue occur when all extensions are disabled?: No

**Comment by mikemadden42** [comment]
This same issue with missing snippets is also happening on my Windows box:
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2

**Comment by mikemadden42** [comment]
IntelliSense does seem to work.  Perhaps it was just taking longer with the large `pandas` library.

![Screen Shot 2021-01-24 at 16 47 27](https://user-images.githubusercontent.com/5888518/105646185-28d94400-5e64-11eb-93c4-c6c8df6dec8c.png)

However, the snippets are definitely not working.  There is generally an additional popup here for a snippet.

![Screen Shot 2021-01-24 at 16 48 39](https://user-images.githubusercontent.com/5888518/105646190-32fb4280-5e64-11eb-85d7-570b38fbdaed.png)

**Comment by jrieken** [comment]
\extPython

**Comment by MiloCheunghaha** [comment]
Having the same problem: still got the IntelliSense but missing the snippets.

**Comment by ToastedGuy2** [comment]
I have the same problem, I'm new to python, so i installed [Python Extension Pack](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python-extension-pack), but not working, any thoughts about it?.
