### ISSUE TITLE
pre-commit fails using VSCode interface

### ISSUE THREAD

**Issue by aragong** [microsoft/vscode#114893]
Issue Type: <b>Bug</b>

Hello,

I use vscode in windows, mini-conda environment and the integrated interface of vscode to run git. 
I am suffering this error trying to setup pre-commit to perform file autoformatting with black:
```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
/usr/bin/env: ‘python’: Permission denied
```

However, if I directly run in the terminal `git commit`, `pre-commit` works fine and the hook with `black `also a success. The error has to be related with some bad configuration of my vscode or my git but I do not know how to find and solve the preoblem. 

Please could you try to help me? Thank you in advance!!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.98GB (7.61GB free)|
|Process Argv|--crash-reporter-id 374583dc-5a50-46a8-a2bc-0e19ed58e733|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.14
vscode-pull-request-github|Git|0.22.0
todo-tree|Gru|0.0.196
python|ms-|2020.12.424452561
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.52.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244:30244299
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30247032

```

</details>

**Comment by aragong** [comment]
Checking my vscode preferences. I can see this:
![image](https://user-images.githubusercontent.com/48764870/105684062-b95f6500-5ef4-11eb-87a3-0d4afb6e923d.png)

and the configuration in the JSON:
![image](https://user-images.githubusercontent.com/48764870/105684125-d5fb9d00-5ef4-11eb-9bd4-a43059906dd0.png)
 
Maybe it will be helpfull

**Comment by aragong** [comment]
Any clue? I am still suffering this error and I have no idea what to do... 

Thank you all!

**Comment by eamodio** [comment]
If you run the same command from a terminal does it work there?

**Comment by aragong** [comment]
If I run the same command the terminal gets stucked. if I skip the last argument `--file -`, running `git -c user.useConfigOnly=true commit --quiet --allow-empty-message` it works perfect. But if I use the vscode GUI fails.

same error: 
`git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - `
`/usr/bin/env: ‘python’: Permission denied`

I installed precommit using the vscode terminal running `pre-commit install`
and then I tried the different commands using the GUI and vscode terminal (cmd with auto-activation of the conda)

I work with conda environments and cmd terminal in windows, when I open a new terminal the conda environment automatically is activated by default. In fact, I tried sometimes to add a second terminal or change the cmd by PS, but in this terminal conda is not recognised... so in order to avoid problems, I use the default terminal (cmd).

Thank you for trying to help me... best regards!

**Comment by adrianturcato-initiative** [comment]
@aragong Did you come up with a solution for this? Have a similar message when using JetBrains PyCharm with pre-commit.

**Comment by aragong** [comment]
No @adrianturcato-initiative, I am still stuck in this issue. Seems something related to which terminal is the git interface running the command... but I am not sure. Maybe @eamodio will throw up some light in the close future.

In the meanwhile, I am exploring if It is possible to use black before push de repo using a GitHub action.

**Comment by kaushiksk** [comment]
@aragong Found the solution [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/contribute/install-pre-commit-hook.html#:~:text=%2Fusr%2Fbin%2Fenv%3A,AppStore%2C%20not%20a%20real%20one.) which works for me.

As mentioned:

If you’re in Git Bash or MSYS terminal, please check the python executable location by running  `which python`.
If the executable is under `~/AppData/Local/Microsoft/WindowsApps/`, then it’s a link to Windows AppStore, not a real one.
Please install python manually and update this in your `PATH` environment variable.

**Comment by aragong** [comment]
@kaushiksk words are right! I've no python loaded in my MSWindows system... I use minicoda, and I don't want to add any extra python to de windows path... Now I am working in WSL and the problem is solved in this environment. So I am closing this issue! 

Thanks to all!
