### ISSUE TITLE
Show commit message length check warning on main input box

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#114834]
Hello,

it would be helpful when the commit message length warning is shown on the main input box too

The commit message box have a commit message length check and show a warning

![2021-01-23 14_46_37-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/105579960-d75c8680-5d89-11eb-8dde-c3a747515b75.png)

but when I don't type in these box, vscode show me the main input box

![2021-01-23 14_47_35-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/105580000-0c68d900-5d8a-11eb-9b75-9ccecd7e107a.png)

but it have no length check

![2021-01-23 14_39_44-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/105579887-8a78b000-5d89-11eb-8861-c731087852fd.png)

**Comment by eamodio** [comment]
Instead of showing the length warning on the quick input, I think we should instead force focus into the SCM input and wait for input there.

**Comment by lszomoru** [comment]
@TobiasSekan, thank you very much for filing this issue and apologies for not getting back to you on this. In the [June 2022 release](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor), we have introduced a new default flow to commit without specifying a commit message. The new flow leverages the full editor as a commit input. Given the new default flow, we are not planning on making any improvements to the flow that leverages the quick input widget. I will go ahead and close this issue as "won't fix" but in case you have any questions or concerns please feel free to reopen the issue. Thank you!
