### ISSUE TITLE
Git Error: Refusing to allow a GitHub App to create or update workflow without workflows permission 

### ISSUE THREAD

**Issue by starkpsmichael** [microsoft/vscode#114821]
- VSCode Version: Latest Insiders on GitHub Codespaces

Hi,
i’am using GitHub Codespaces and was trying to update my GitHub workflow file.
I created a new branch, updated my .github/workflows/ci.yml file and tried to push it to my repo.

This doesn’t work, because it says: "refusing to allow a GitHub App to create or update workflow without workflows permission.

I already tried all the workarounds about revoking permissions for OAuth & GitHub apps, and logged in and out in Codespaces - nothing works.

The permission page for “GitHub Codespaces” has the following:
- Verify your GitHub identity
- Know what resources you can access
- Act on your behalf

The permission page for “GitHub for VSCode” has the following:
- Full control of orgs and teams, read and write org projects
- Full control of private repositories

How can i make this work? :frowning:
I hope this is the right repo for this 😜
See also [VisualStudio@2455](https://github.com/github/VisualStudio/issues/2455)

Does this issue occur when all extensions are disabled?: N/A

**Comment by eamodio** [comment]
@RMacfarlane Any idea on this one?

**Comment by eamodio** [comment]
I believe this has been resolved, now that we ask for the workflow permission. Please re-open if that's not the case.
