### ISSUE TITLE
Documentation for files.exclude and search.exclude point to incorrect glob patterns documentation

### ISSUE THREAD

**Issue by studgeek** [microsoft/vscode#114870]
New documentation should be created that accurated describes how "files.exclude" and "search.exclude" globbing actually works.

As described in https://github.com/microsoft/vscode/issues/112167, the "files.exclude" and "search.exclude" both point to [Basic Editing in Visual Studio Code](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) to explain glob patterns. But that documentation is wrong in a severals ways for "files.exclude" and "search.exclude" including "**" (https://github.com/microsoft/vscode/issues/112167) and "!" (https://github.com/microsoft/vscode/issues/869).  This is a source of ongoing confusion reflected in issues and stackoverflow questions.

**Comment by studgeek** [comment]
It should also describe how `when` works (https://github.com/microsoft/vscode/issues/1214).

**Comment by studgeek** [comment]
It also seems that "files.exclude", "files.watcherExclude", and "search.exclude" work differently in terms of being absolute or relative (if they assume ** prefix). That should be captured more clearly as well.

**Comment by roblourens** [comment]
- The note about `!` is out of date, and I will change that in the docs, thanks.
- Globs work differently in those settings vs in the search view, but I will add a note to the docs about that
- `when` is an advanced pattern that isn't even fully supported by the settings editor. I'm not sure I want to describe it in the docs. It's essentially the same as how it's used in keybindings and other settings.

**Comment by roblourens** [comment]
Did that but also noticed that we just added a new docs section on "when" clauses. So I will look into what would be appropriate for mentioning that for the exclude settings.
