### ISSUE TITLE
[Question] Is it safe to adjust the language name in my extension

### ISSUE THREAD

**Issue by robinbentley** [Microsoft/vscode#11484]
Hi, 

I just wanted to ask a quick question, I figured this was the best place. I made the Sass (Indented) extension and have seen since 1.3 that the built in **Scss** was renamed from **Sass** to **Scss** to reflect the actual support.

I was wondering if it would be safe for me to drop the (Indented) now and just use Sass for my extension or is there a risk it could still cause clashes or cause problems with other extensions?

Thanks

**Comment by alexandrudima** [comment]
ping @aeschli

**Comment by aeschli** [comment]
@robinbentley +1 from to now use 'sass' for indented sass. There might be some swirls, probably with users that use old VSCode versions, but I think it's the right way forward. You can avoid that if you add a 1.4 vscode engine dependency to your extension and add a note to the readme.
    "engines": {
        "vscode": "^1.4.0"
    },

**Comment by robinbentley** [comment]
@aeschli Thanks, I'll look at making the change
