### ISSUE TITLE
Refresh the vscode

### ISSUE THREAD

**Issue by smartDataSDN** [Microsoft/vscode#11488]
Hi,
I am facing the problem with the vscode for the refreshing the page.Just tell me how to refresh the page.

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7600

Steps to Reproduce:

1.
2.

**Comment by glen-84** [comment]
`F1` -> `Reload Window` ?

**Comment by dbaeumer** [comment]
@glen-84 thanks. Closing since he answered it.
