### ISSUE TITLE
Codicon not rendered in markdown list

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#114853]
Issue Type: <b>Bug</b>

1. Create editor hover:

```ts
vscode.languages.registerHoverProvider(
    { scheme: 'file' },
    {
        provideHover(document, position, token) {
            const markdown = new vscode.MarkdownString(undefined, true);
            markdown.isTrusted = true;
            markdown.appendMarkdown('- $(history)');
            return new vscode.Hover(markdown);
        },
    },
);
```

2. Codicon is rendered as text.

VS Code version: Code - Insiders 1.53.0-insider (1a4b35c2023a41efae1af2661026d57cea90ef5c, 2021-01-21T05:14:12.411Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
I believe this should have been fixed as part of #109025

Let me know if this is still not working in the current insiders build
