### ISSUE TITLE
Add a show "hidden" button to the file explorer

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#11486]
- VSCode Version: `Version 1.5.0-insider (1.5.0-insider)` 1de4d832ccb061c13cf70eaf0221fbaa86abfbdd
- OS Version: `OS X El Capitan Version 10.11.6 (15G31)`

I often have `node_modules` and `typings` (as well as others) hidden from the vscode file explorer, but it would be nice to be able to easily toggle them back to visible without having to edit my settings file for a transient check.

**Comment by schmuli** [comment]
You could try using the [Peep](https://marketplace.visualstudio.com/items?itemName=nwallace.peep) extension.

**Comment by eamodio** [comment]
Peep is outdated and touches the settings outside of vscode, which causes some issues -- and I believe it doesn't properly support the newer features of the `files:exclude` setting.

Check out [Toggle Excluded Files](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) it is up-to-date with the latest features and uses supported vscode apis to toggle them (it also provides state tracking as well)
