### ISSUE TITLE
Add "not show again" for duplicate alert dialog

### ISSUE THREAD

**Issue by whoiscc** [microsoft/vscode#114838]
I was downloading a  binary file with curl in terminal while keeping the file open in editor. Then the "fix this file" dialog shows up infinitely because curl updates the file continuously and it becomes an alert bomb.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform, and whether it still occurs if you run with all extensions disabled. If yes, please paste a screenshot of the dialog.

**Comment by whoiscc** [comment]
Sorry, I will reopen it when I can reproduce and record.
