### ISSUE TITLE
Updating (Downloading) Extensions Manually Fails: Current Version is Requested Instead of New Version

### ISSUE THREAD

**Issue by jar240** [microsoft/vscode#114862]
VS Code v 1.52.1
OS: Windows Server 2012 R2 x64; Version	6.3.9600 Build 9600
Network: Behind Corporate Firewall

Steps to Reproduce the Issue:

1. Launch Visual Studio Code and navigate to the Extensions dock
2. See that an extension has an update available (ex. current: 1.5.0, new 1.6.0)
![image](https://user-images.githubusercontent.com/6794643/105633850-05dd6e80-5e29-11eb-9949-ae70c9ff5c2c.png)
3. Click on the "Update to 1.6.0" link. (The hostname being requested isn't allowed through our proxy, but the hostname used in the manual downloads is)
4. The expected "Error while updating..." message appears. Click the "Try Downloading Manually..." button.
![image](https://user-images.githubusercontent.com/6794643/105634020-f4e12d00-5e29-11eb-8e89-a56778f2c782.png)
5. The default browser is opened **to the incorrect URL**. VS requests the currently-installed (0.1.5) version of the extension instead of the new (0.1.6) version.
![image](https://user-images.githubusercontent.com/6794643/105634023-fa3e7780-5e29-11eb-948b-0c341ae0b783.png)

## Expected URL (in this example):
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/formulahendry/vsextensions/auto-rename-tag/**0.1.6**/vspackage
## Actual URL:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/formulahendry/vsextensions/auto-rename-tag/**0.1.5**/vspackage

(I understand we can avoid this situation by adding a proxy exception for the extension update URL, but it doesn't fix the bug)

# List of installed extensions:
hbenl.vscode-test-explorer-2.19.3
hookyqr.beautify-1.5.0
johnpapa.vscode-peacock-3.9.1
johnpapa.winteriscoming-1.4.3
kisstkondoros.typelens-1.9.6
ktriek.ng-bootstrap-snippets-1.0.0
mohsen1.prettify-json-0.0.3
msjsdiag.debugger-for-chrome-4.12.11
ms-mssql.mssql-1.9.0
ms-vscode.powershell-2020.6.0
ms-vscode.powershell-preview-2020.9.0
ms-vscode.vscode-typescript-tslint-plugin-1.2.3
ms-vsts.team-1.161.0
sonarsource.sonarlint-vscode-1.18.0
stringham.move-ts-1.12.0
thekalinga.bootstrap4-vscode-6.1.0
xabikos.jasminesnippets-1.0.1
yzhang.markdown-all-in-one-3.4.0
andrew-codes.cypress-snippets-1.2.0
angular.ng-template-0.1100.1
anseki.vscode-color-0.4.5
dotjoshjohnson.xml-2.5.1
eamodio.gitlens-11.0.6
esbenp.prettier-vscode-5.8.0
fabianlauer.vs-code-xml-format-0.1.5
ferreirarubens.vsc-angular-pack-0.0.1
formulahendry.auto-rename-tag-0.1.5
hbenl.vscode-jasmine-test-adapter-1.7.1

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/113257
