### ISSUE TITLE
Test: shared process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114825]
Refs: 

- [x] macOS @eamodio
- [x] linux @roblourens
- [x] windows @lszomoru 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114825%0A%0A)

---

This milestone the IPC connection to the shared process changed from node.js socket to Electron's message ports. 

Smoke test that the shared process works as before:
* you can make the hidden window visible via F1 command ("Toggle Shared Process") and close it without the process stopping
* you can install, search and manage extensions
* settings sync works (also check the related output channel)
* installing a different display language and displaying it works
* run with `--verbose` and verify you see output in the telemetry output channel

**Comment by lszomoru** [comment]
@devinvalenciano, I will grab this one.

**Comment by lszomoru** [comment]
👏🏻
