### ISSUE TITLE
[ext-api] provide Pseudoterminal.onDidChangeName event

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#114898]
Current it is not possible to change the name of the pseudo terminal implemented by the extension.

**Comment by Tyriar** [comment]
Makes sense, if a PR for this comes in for this I can bring it to the API sync. Seems like a good improvement so I don't see why it wouldn't be able to get merged in.

**Comment by hbibkrim** [comment]
I can take this if nobody has already

**Comment by Tyriar** [comment]
@hbibkrim that would be great 👍

**Comment by hbibkrim** [comment]
@Tyriar Should this go under proposed API?

**Comment by Tyriar** [comment]
@hbibkrim yes

**Comment by Tyriar** [comment]
Test for proposal in May https://github.com/microsoft/vscode/issues/122945, moving to June for finalization

**Comment by Tyriar** [comment]
Temporarily reopening for planning call.
