### ISSUE TITLE
Set GtkSettings:gtk-application-prefer-dark-theme for dark themes

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#114807]
In GNOME/GTK the way to request dark decorations is up to the application developer. Currently when you are using a VSCode dark theme in a light theme environment you end up with unaesthetic scenarios like this one:

![image](https://user-images.githubusercontent.com/2845433/105567560-801acf80-5d11-11eb-98aa-c4ac12f0a841.png)

It's VSCode that should notify the environment about it's theme preference and the way to do that is explained in https://gitlab.gnome.org/GNOME/gtk/-/issues/99

**Comment by memeplex** [comment]
It seems that this is already supported in Electron, but VSCiode is not using it https://github.com/electron/electron/issues/352
?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/130974
