### ISSUE TITLE
Test: consistent context menus in workbench layout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114822]
Refs: https://github.com/microsoft/vscode/issues/113757

- [x] anyOS @lszomoru
- [x] anyOS @ornellaalt

Complexity: 2

Authors: @bpasero, @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114822%0A%0A)

---

We tried to make the context menus that appear throughout the workbench to be consistent. This impacts the following right-clickable locations:
* activity bar (either any entry directly or empty space between)
* panel header (either an entry directly or empty space between)
* side bar (either a view directly or the title area at the top)

The experience should be consistent:
* you see an explicit "Hide XY" entry as first entry if you right click on a specific entry
* you always see a list of entries with checkboxes to toggle visibility
* you never see a "Hide XY" entry when you right click into empty space
* you see management related entries at the end (e.g. "Move Sidebar Right")

**Comment by ArturoDent** [comment]
Very small thing on Activity Bar. Context menu reads `Hide 'Extensions'` for example but `Hide Accounts`  (Accounts not in quotes).

**Comment by bpasero** [comment]
@ArturoDent thanks for testing this, yes I would say that is intentional because view names can be anything including multiple words and potentially coming from extensions so I felt it better to surround with quotes.

**Comment by lszomoru** [comment]
Tested on macOS 👏🏻

**Comment by ornellaalt** [comment]
Also tested on macOS :tada:
