### ISSUE TITLE
Option to pause / restart "Initializing JS/TS language features"

### ISSUE THREAD

**Issue by vzaidman** [microsoft/vscode#114860]
I'd like to have the option to pause / restart "Initializing JS/TS language features"

Sometimes I prefer changing branches and running "npm install" first, for example.

![image](https://user-images.githubusercontent.com/5188459/105632673-160f4100-5e5d-11eb-813f-3950dab467a3.png)

**Comment by mjbvz** [comment]
You can run the `Restart TS server` command to restart the server. This is not a passable operation (or one we think users should care about pausing in the first place) so no plans to add support for that
