### ISSUE TITLE
.md file markdonwn error create problems

### ISSUE THREAD

**Issue by alexandre-leng** [microsoft/vscode#114841]
Hi,

It can be great if VS CODE ignore .md file format markdonwn and didn't report false positive.

Have a nice day 
Alexander
![markdown false positive](https://user-images.githubusercontent.com/72550137/105608606-2a433780-5da4-11eb-97b5-e487c0d1305c.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension you appear to have installed a spellchecker extension
