### ISSUE TITLE
Property 'cwd' does not exist on type TerminalOptions

### ISSUE THREAD

**Issue by alor-pretatma** [microsoft/vscode#114858]
- VSCode Version: 1.52.1
- OS Version: Windows10 Version 20H2 (Build:19042.746)

Steps to Reproduce:

1.
![Screenshot 2021-01-24 191034](https://user-images.githubusercontent.com/33311165/105631664-b07d7d80-5e79-11eb-88b4-697581a63b16.png)

Does this issue occur when all extensions are disabled?: Yes

But in documentation it says TerminalOptions.cwd should be [**_A path or Uri for the current working directory to be used for the terminal._**](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions)

I have printed the terminal object too, but cwd is not present in Terminal.createOptions

**Comment by meganrogge** [comment]
I find that casting things is useful, as you can see here, I don't see that error.
![err](https://user-images.githubusercontent.com/29464607/105747366-8bc6eb80-5ef5-11eb-8dbf-b2077662d6f0.PNG)

**Comment by alor-pretatma** [comment]
This report is not about casting. Please visit this link [https://code.visualstudio.com/api/references/vscode-api#TerminalOptions](https://code.visualstudio.com/api/references/vscode-api#TerminalOptions)

> It says, _**TerminalOptions**_ class has a property called _**cwd**_. And that contains the current working directory of the terminal.

But the problem is, in the image I've given it says
>  _**the property cwd does not exist on type TerminalOptions**_ .

But it should exist.

And when I hit run, this happens:

![Screenshot 2021-01-26 002440](https://user-images.githubusercontent.com/33311165/105748987-05e68700-5f6d-11eb-9b7e-cf317c86d461.png)

### I am working on a VS Code extension. In this image it's completely new project(For testing). But yet this happens..

**Comment by meganrogge** [comment]
try this instead:

```
	const disposable = vscode.commands.registerCommand('some-test.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World from Easy Runner!');
		(vscode.window.terminals as any).forEach((ter: { creationOptions: { cwd: any; }; }) => {
			console.log(ter.creationOptions.cwd);
		});
	});
```

**Comment by alor-pretatma** [comment]
Hey, I did not want to hide the message. I need to get the terminals cwd. But this is returning undefined. Why are you just ignoring the problem instead of solving it?

**Comment by Tyriar** [comment]
@alor-pretatma you're hitting the error because `Terminal.creationOptions` is a `Readonly<TerminalOptions | ExtensionTerminalOptions>` as the error says. You need to use [type narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html) to make sure it's not an `ExtensionTerminalOptions` to safely access `TerminalOptions.cwd`:

```ts
vscode.window.terminals.forEach(t => {
  // Return if it's an extension terminal
  const options = t.creationOptions;
  if ('pty' in options) {
    return;
  }
  console.log(options.cwd);
});
```
