### ISSUE TITLE
Goto next problem does not go in sequence in certain scenarios

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#114848]
ATTENTION ATTENTION: This is a BUG. Repeat this is a BUG. Do not label this a a feature request so your bot comes and auto closes it because it is not getting votes.

Repeat once again.....this is a BUG not a feature request.

Version: 1.51.1
Commit: e5a624b
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-53-generic

I have observed a scenario where pressing F8 to go to next problem will take me back the first problem, instead of to the next problem.

The problems in my problems view can be summarized as follows. (number of files and issues within files is irrelevant).

File A
problem 1
problem 2
problem 3
File B
problem 1
problem 2
problem 3
File C
problem 1
problem 2
problem 3

-press F8 to go to problem A1.
-keep pressing F8 until you get to problem B3 (the last problem in a file that has problems in a file before it and problems in a file after it).
-fix the problem and save the file.
-press F8 again....
-it jumps to problem A1.

Expected Behaviour
-it should jump to problem C1.

**Comment by sandy081** [comment]
Reopening the original issue - https://github.com/microsoft/vscode/issues/113257
