### ISSUE TITLE
cnc selector

### ISSUE THREAD

**Issue by gcarty-gc** [microsoft/vscode#114842]
Issue Type: <b>Bug</b>

I have .cps file open, code not produced when face.cnc selected.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
hsm-post-processor|Aut|3.4.0
nc-gcode|ML2|0.14.1

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
