### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by imhimanshukr** [microsoft/vscode#114849]
Issue Type: <b>Performance Issue</b>

When i open terminal then it open and suddenly close and then it shows me following at right down corner:
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 4294901760.

Please help me as soon as possible.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.22GB free)|
|Process Argv|--crash-reporter-id 4ee2d5e5-ebfb-4e58-856a-e0339ee57eef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	  6844	code main
    1	   538	  2356	   gpu-process
    0	   175	  3000	   window (chat.js - iChat - Visual Studio Code)
    0	    31	  2200	     searchService
    0	    13	  6136	     watcherService 
    0	     9	  7740	       console-window-host (Windows internal process)
    0	    73	  6412	     extensionHost
    0	    66	  6304	       electron_node tsserver.js 
    0	    73	  6380	       electron_node tsserver.js 
    0	    42	  8620	         electron_node typingsInstaller.js typesMap.js 
    0	    37	  6672	       "C:\Users\Himanshu kumar\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Himanshu kumar\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6412
    0	    23	  3964	   utility
    0	    65	  5184	   shared-process
    0	    12	  6724	   crashpad-handler
    0	    51	  8448	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (chat.js - iChat - Visual Studio Code)
|    Folder (iChat): 14 files
|      File types: json(3) js(2) html(1) css(1) png(1) mp3(1)
|      Conf files: launch.json(1) package.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
vstes516:30244333

```

</details>

![Screenshot (334)](https://user-images.githubusercontent.com/63518367/105621093-088c9380-5e2a-11eb-9861-ffcb587537e7.png)

**Comment by jonathanmarp** [comment]
Have you seen the folders in "C: \ WINDOWS \ System32 \ WindowsPowerShell \ v1.0 \ powershell.exe".  If the file explorer also doesn't exist that means the terminal cannot be opened.

**Comment by meganrogge** [comment]
please provide your settings, something is probably wrong with your `terminal.integrated.cwd`
