### ISSUE TITLE
[Settings GUI] selection.background is washed out

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#114861]
Issue Type: <b>Bug</b>

```js
"workbench.colorCustomizations": {
    "selection.background": "#ff000050",
}
```

1. Open Settings GUI
2. Select text inside the input

|   All other inputs ✅      |   Settings GUI ❌        |
| ------------- |-------------|
| ![Screenshot (429)](https://user-images.githubusercontent.com/9638156/105633475-d69b2180-5e69-11eb-949e-7e35a92c6c99.png)  | ![Screenshot (430)](https://user-images.githubusercontent.com/9638156/105633465-cbe08c80-5e69-11eb-980c-f1b37b7afb5e.png) |

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by roblourens** [comment]
This is an old issue. So the native html input has some custom behavior for how the selection color is blended with the background behind it. I tried to reverse engineer this and replicate it for editors, but this is the closest I could get, unfortunately :(

**Comment by usernamehw** [comment]
@roblourens It's just weird that other inputs work fine.

Actually, Extensions View Filter and Settings GUI both have this issue. 

SCM input uses `editor.selectionBackground`.

Search View, Find Widget, Terminal Find widget, Keybinding GUI filter, Search Editor, Problems filter input, Debug Console filter - they all have the right color.

**Comment by roblourens** [comment]
Yes, native inputs look as expected, inputs that are actually editor instances (usually because they have a suggest widget)sss have to guess the native bg color.
