### ISSUE TITLE
css float and inline-block

### ISSUE THREAD

**Issue by vitaliyterziev** [Microsoft/vscode#11481]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:

1.  Use float with inline-block and it will mark it as nonvalid code 
2.  The float property is ignored with inline-block which is not the case even in legacy engines like IE9

**Comment by aeschli** [comment]
Not using float with 'block-inline' comes from http://csslint.net/about.html (see Use correct properties for a display). As float turns 'block-inline' into a 'block', it's probably cleaner to just use 'block' instead.
