### ISSUE TITLE
first scroll event ignored after application was inactive

### ISSUE THREAD

**Issue by Optiligence** [microsoft/vscode#114817]
- VSCode Version: 1.5.3.0-insider
- OS Version: Arch Linux

Steps to Reproduce:

1. switch to another application
2. switch back to vscode
3. scroll

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Can you please provide a [screen recording](https://gifcap.dev/)?

**Comment by Optiligence** [comment]
you won’t see me scrolling, will you?

**Comment by Optiligence** [comment]
there is actually no fancy application switching necessary

i just opened `code-insiders --disable-extensions`
selected Help → Release notes and tried to scroll: the first event gets eaten

**Comment by Optiligence** [comment]
i scrolled twice here, idk what you want to see
![recording](https://user-images.githubusercontent.com/1899299/105682774-25d96480-5ef3-11eb-8d3e-e39487b43468.gif)

**Comment by joaomoreno** [comment]
What window manager are you using? Can you reproduce in any other application?

**Comment by Optiligence** [comment]
GNOME/Mutter, happens in X11 as well as Wayland

now that you say it it seems to happen in slack as well, so probably an electron bug

**Comment by Optiligence** [comment]
ok, so it seems to be more widespread

it works fine in Firefox as well as e.g. ksysguard, but doesn’t in gnome-system-monitor, nautilus or sublime text

i guess i have to dig more and create an issue somewhere else
