### ISSUE TITLE
Add a shortcut for removing file from recently opened 

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#114882]
Instead of manually clicking these `x`s, it'll be more convenient and faster to use shortcuts like `delete`, `shift + delete` etc. to remove:
![image](https://user-images.githubusercontent.com/28700378/105673143-90ed6000-5f20-11eb-98a0-77ca1914a3e8.png)

**Comment by sbatten** [comment]
this seems more like a general request of quick picks

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode/issues/98479
