### ISSUE TITLE
Provide full documented json schema

### ISSUE THREAD

**Issue by SrTobi** [Microsoft/vscode#1148]
The configuration contribution point offers a great chance to provide a rich documentation about the JsonSchema, [yet it simply refers to the official meta-schema](https://github.com/Microsoft/vscode/blob/468635529ed0e10f1aeffee31ee2327e76051b05/src/vs/platform/configuration/common/configurationRegistry.ts#L110) that does not contain any useful description.

If you say, that this is something you would merge into VS Code, I would start the implementation and open a PR. Implementation details:

1. Create a new file containing the complete meta-schema in Typescript with descriptions.
2. Import the schema and register it with `PluginsRegistry.registerExtensionPoint<IConfigurationNode>(...)`.

**Comment by aeschli** [comment]
What you suggest we actually already do. We have some built-in schemas. The meta-schema is one of these, it's modified in that it includes descriptions. 
But I'm currently working on allowing extensions to contribute schema associations and was about to remove all built-in schemas. I changed it and package the meta schema again, so we don't loose the descriptions.
The right thing to do would be to write the guys that own the meta schema to add description in the schema, so everbody profits.

**Comment by aeschli** [comment]
To verify:
- open `package.json`
- add a `contributes` and a `configuration` section
- add some configuration keys
- inside the configuration keys object make sure you get intellisense and hovers

**Comment by SrTobi** [comment]
:+1: it works. Intellisense as well as hovers as well as validation. Thats great.

Maybe add more defaults everywhere only one type is valid. For example `anyOf` or `allOf` are always arrays, so why not set their defaults to an empty array. It is not necessary but would improve the flow of writing an schema.

**Comment by bpasero** [comment]
Thanks @SrTobi
