### ISSUE TITLE
Markdown (.md) switching view (CTRL+SHIFT+V) not working

### ISSUE THREAD

**Issue by Yanjun31** [microsoft/vscode#114805]
- VSCode Version: 1.52.1
- OS Version: Windows 10 V20H2 Build 19042.746

Steps to Reproduce:

1. Open a markdown file with .md extension.
2. Try pressing Ctrl + Shift + V to swtich to the preview mode.
3. Try pressing Ctrl + Shift + V again to swtich to the editor mode.

Expectation: Users can switch between the preview mode and the editor mode of the Markdown file.

Observed: In the editor mode, Ctrl + Shift + V will not switch the file to the preview mode. Instead, a preview mode of the file will be opened beside it. In the preview mode, Ctrl + Shift + V will not switch the file to the editor mode. Switching to the editor mode can only be realized by double clicking.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
`Ctrl + Shift + V ` opens a new markdown preview editor.

To change the current editor, try using the `Toggle editor type` command instead
