### ISSUE TITLE
Autodetecting gulpfile.ts tasks

### ISSUE THREAD

**Issue by robstoll** [Microsoft/vscode#11482]
As it seems, VS Code does only detect gulpfile.js tasks but not gulpfile.ts tasks. Would be nice if it works with a .ts file as well.

**Comment by roblourens** [comment]
Wouldn't you have to compile the gulpfile.ts to a gulpfile.js first anyway?

**Comment by robstoll** [comment]
no, you just require ts-node (as far as I can tell, I am a beginner in typescript)

**Comment by dbaeumer** [comment]
To verify:

- new folder
- install ts-node, typescript and gulp locally
- create a gulpfile.ts
```
import * as gulp from 'gulp';

gulp.task('compile', () => {
	console.log('Hello World');
});
```
- Run task should list the task from the gulpfile.ts

**Comment by dbaeumer** [comment]
Need to move to next milestone. This is not fully working.

**Comment by ramya-rao-a** [comment]
Is this still meant for the January milestone? If not, can you move it to February milestone?
