### ISSUE TITLE
[Debugger] VariablePresentationHint.readOnly is ignored

### ISSUE THREAD

**Issue by Trass3r** [microsoft/vscode#114803]
Most [`VariablePresentationHint`](https://microsoft.github.io/debug-adapter-protocol/specification#Types_VariablePresentationHint
)s are meant for optional presentation differences,
but when `readOnly` or `constant` is set it should actually be impossible to change the variables in the UI.

Currently VSCode still sends a https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetVariable which actually [crashed](https://github.com/microsoft/MIEngine/pull/1039#issuecomment-758340990) the C++ debug adapter before fixing it.

In fact `virtual` seems to be the only hint that ever got implemented:
https://github.com/microsoft/vscode/blob/9d9afaacfb0362b15c3828a19f056cfd428d6fc5/src/vs/workbench/contrib/debug/browser/baseDebugView.ts#L106

- VSCode Version: 1.52.1
- OS Version: Win10 WSL

**Comment by weinand** [comment]
"VariablePresentationHints" are hints to the client (e.g. VS Code) to render variables in specific ways.
Clients do not know the source level semantics of these hints and consequently they do not prevent editing of "readOnly" or "constant" variables. If a debugger does not support this, the debugger should report back an error from the "setVariable" request.
