### ISSUE TITLE
Git not installed

### ISSUE THREAD

**Issue by SelenaKhurana** [microsoft/vscode#114872]
Issue Type: <b>Bug</b>

Hello, I have git but it keeps saying that git is not installed in my system. How can I fix this?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 10|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 5f09fa50-49e6-436f-b479-ef0471060f5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.11
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0
vscode-java-debug|vsc|0.30.0

</details>

**Comment by eamodio** [comment]
This usually is an issue requiring an xcode update. Can you try running `xcode` and then agree to the license, or if that doesn't work try running `xcode-select --install`.
