### ISSUE TITLE
File rename box was automated unfocus

### ISSUE THREAD

**Issue by bahung1221** [microsoft/vscode#114819]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Copy and then paste any file
2. Press enter to "rename" copied file
3. Wait for ~500ms you will see the rename box was automated unfocus

**NOTE**: This issue only occurs the first time the file was copied (within 500ms~1s). A workaround is waiting for 1s before start renaming the file.

Does this issue occur when all extensions are disabled?: Yes

Gif Image:
![Screen-Recording-2021-01-23-at-1 (1)](https://user-images.githubusercontent.com/27690861/105571687-afb6ef80-5d84-11eb-9dac-0fd9e6d73512.gif)

**Comment by gjsjohnmurray** [comment]
/duplicate and already fixed in Insiders, so the fix should arrive in Stable in a couple of weeks.
