### ISSUE TITLE
seemingly randomly activated copy on select

### ISSUE THREAD

**Issue by Teiem** [microsoft/vscode#114846]
Sometimes vscode enables some kind of "copy on select" (when selecting text, e.g. double-clicking a word with your mouse, the selected text gets copied to the clipboard without any further action), reloading the window disables it.
I hope someone else who also experienced this bug can add some additional insights.

- VSCode Version: 1.52.1
- OS Version: Windows 10 19042

Steps to Reproduce:
- The bug happend about about 4 times in the last few months, I sadly don't know what causes it.

Does this issue occur when all extensions are disabled?: unknown

**Comment by alexdima** [comment]
@Teiem I'm not sure what you mean by "copy on select". Please let us know if you find a way to reproduce it.
