### ISSUE TITLE
Incorrect Textmate scopes for `string.quoted.single` in SQL

### ISSUE THREAD

**Issue by dustypomerleau** [microsoft/vscode#114876]
I have submitted an upstream fix for this in https://github.com/microsoft/vscode-mssql/pull/16923, but it doesn't seem to be getting enough traction for a review. CC: @alexr00.

---

- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Load any SQL file
2. Navigate to a single-quoted string
3. Choose `Developer: Inspect Editor Tokens and Scopes`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
@dustypomerleau you could try filing an issue in https://github.com/microsoft/vscode-mssql. Since this is an upstream issue, I'm going to close it as such. I don't have any influence over what happens in that repo :(.
