### ISSUE TITLE
missing Python interpreter 

### ISSUE THREAD

**Issue by noce2k** [microsoft/vscode#114845]
Issue Type: <b>Bug</b>

probably, after the upgrade with the latest version of vscode, I'm not able to execute python.

I use the virtual env and I change the settings.json in this way

{
    "python.pythonPath": "Scripts\\python.exe",
    "powershell.codeFormatting.addWhitespaceAroundPipe": true,
    "editor.fontFamily": "'cascadia code'"
}    

yesterday everything working fine

VS Code version: Code - Insiders 1.53.0-insider (ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57, 2021-01-22T17:18:22.679Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.88GB free)|
|Process Argv|--folder-uri file:///c%3A/s/TelloDroneChallenge --crash-reporter-id e66b2208-b422-4bb0-b376-d80cf946efe5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.2.0
vscode-pytest|Cam|0.1.1
python-extension-pack|don|1.6.0
beautify|Hoo|1.5.0
kite|kit|0.135.0
MagicPython|mag|1.1.0
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.2
jupyter|ms-|2020.12.414227025
powershell|ms-|2020.6.0
powershell-preview|ms-|2020.9.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.10
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
pythonvspyt700:30244268
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30247032
core-portspanelcf:30233468

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
