### ISSUE TITLE
Can't update, says on read only volume

### ISSUE THREAD

**Issue by arturogh** [microsoft/vscode#114804]
Issue Type: <b>Bug</b>

VS Code says it's on a read only volume and can't update. It's not.

<img width="885" alt="CleanShot 2021-01-22 at 16 57 44@2x" src="https://user-images.githubusercontent.com/7030831/105563552-4e831380-5cd3-11eb-8842-0d3997fe129c.png">

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 69f7fc60-9d49-4aa3-994a-ae8107e76b0c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by arturogh** [comment]
So...just downloaded the new versions, put them in my Applications folder (stable and insiders).

Insiders has the same problem...but stable works now?
Stable: 1.52
Insiders: 1.53

**Comment by joaomoreno** [comment]
The application is very likely in quarantine, which the `this link` explains. Follow the link for resolution. Let me know how this goes.

**Comment by arturogh** [comment]
I've tried running:
```
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```

But I get
```
zsh: no matches found: /Users/arturogoicochea/Library/Caches/com.microsoft.VSCode.ShipIt/*
```

Not sure what steps to try next. 
Also, at least in my case the message is confusing as the app is not in a read only volume.

**Comment by joaomoreno** [comment]
```
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
```

This is the important step. Run that one.

> Also, at least in my case the message is confusing as the app is not in a read only volume.

The message is correct. When apps are in quarantine, macOS runs them from a read only volume.

**Comment by arturogh** [comment]
Thanks! As it was Insiders, I did (and it worked):

```
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code\ -\ Insiders.app
```

Still, I wouldn't have guessed my app was in quarantine, which means it is run from a read only volume. This feels like a UX problem. 

CC: @misolori, what do you think?

**Comment by misolori** [comment]
Hmm...I'm not sure it's obvious that "read-only mode" means the app is in "quarantine", which I've personally never heard before. My first guess would be that my app is in Downloads, and if that wasn't the case then I would assume that this is a bug and wouldn't click on the link because it wouldn't apply to me. Feels like the language could be improved to mention this? Something like:

`...The application is either in a read-only volume or in quarantine mode. See our docs to get your application out of this mode."`

**Comment by joaomoreno** [comment]
This is exactly why we have the link:

![image](https://user-images.githubusercontent.com/22350/105971742-ba50dd80-603f-11eb-9897-446e891b95f9.png)

**Comment by misolori** [comment]
My main point is if you believe your volume isn't read only then you wouldn't click the link because it doesn't apply to you.

**Comment by joaomoreno** [comment]
OK, I've improved the message. 👍
