### ISSUE TITLE
`"editor.mouseWheelZoom": true` not working

### ISSUE THREAD

**Issue by blueray453** [microsoft/vscode#114829]
Issue Type: <b>Bug</b>

I found that I can zoom in and out by ctrl+scrollup/scrolldown if I set `"editor.mouseWheelZoom": true`

However, it does nothing in my machine. It does neither zoom in nor zoom out if I use ctrl+scrollup/scrolldown after setting `"editor.mouseWheelZoom": true` 

`"window.zoomLevel": 0` works (if I change the value of 0 to 1 or something). However, I do not know how to control its value using mouse (ctrl+scrollup/scrolldown).

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 4099)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|6, 5, 3|
|Memory (System)|31.03GB (24.01GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 2ad3d0e5-1630-4051-9f76-52cd096fee78|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon2d|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon2d|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
codesnap|adp|1.2.1
vscode-caniuse|aka|0.5.4
Bookmarks|ale|12.1.4
project-manager|ale|12.0.1
filewatcher|App|1.0.3
chronicler|arc|0.1.8
quitcontrol-vscode|art|3.1.3
asciidoctor-vscode|asc|2.8.4
simple-search|bur|1.0.1
turbo-console-log|Cha|2.1.6
vscode-opennewinstance|chr|0.0.7
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-quick-select|dba|0.2.9
githistory|don|0.6.14
brackethighlighter|Dur|2.2.3
gitlens|eam|11.1.3
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
terminal|for|0.0.10
todo-tree|Gru|0.0.196
vscode-test-explorer|hbe|2.19.5
vscode-settings-cycler|hoo|1.0.1
rest-client|hum|0.24.4
output-colorizer|IBM|0.1.2
vscode-dimmer-block|ima|2.2.0
easy-snippet|inu|0.6.2
path-autocomplete|ion|1.17.0
copy-filename|jac|2.3.2
open-file-from-path|jac|1.3.4
align-by-regex|jan|1.0.4
hungry-delete|jas|1.6.0
autofilename|Jer|0.1.3
vscode-format-context-menu|lac|1.0.4
sftp|lix|1.12.9
i18n-ally|lok|2.4.19
camelcasenavigation|map|1.1.3
select-highlight-minimap|mde|0.1.0
render-crlf|med|1.5.16
git-graph|mhu|1.28.0
goto-next-previous-member|mis|0.0.5
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
autotrim|Nat|1.0.6
vs-sequential-number|nep|1.0.0
gremlins|nho|0.26.0
copy-json-path|nid|0.1.0
incrementor|nms|1.0.3
indent-rainbow|ode|7.5.0
text-power-tools|qcz|1.18.1
vscode-data-preview|Ran|2.2.0
toggle|reb|0.0.1
vscode-sort-json|ric|1.19.2
vscode-text-tables|Rom|0.1.5
multi-command|ryu|1.4.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-fileutils|sle|3.4.3
vscode-taskexplorer|spm|1.27.0
css-auto-prefix|spo|0.1.7
autoimport|ste|1.5.3
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
pdf|tom|1.1.0
selectline-statusbar|tom|0.0.2
go-to-method|tri|0.2.0
shell-launcher|Tyr|0.4.1
non-breaking-space-highlighter|vik|0.0.3
vscode-icons|vsc|11.1.0
codetour|vsl|0.0.42
vscode-todo-highlight|way|1.0.4
save-and-run|wk-|0.0.21
vscode-jumpy|wma|0.3.1
vscode-surround|yat|1.0.2
FilterText|yhi|0.0.15
emmet-live|yse|1.0.0

</details>

**Comment by alexdima** [comment]
[Here](https://github.com/microsoft/vscode/blob/9788e81e98dddbc36e923effa9a39cc71337e019/src/vs/editor/browser/controller/mouseHandler.ts#L107-L124) is our code. We look for a mouse wheel event with only the `ctrl` key pressed. 
1. Are you perhaps pressing other modifiers besides `ctrl`? 
2. Do you have Linux installed natively on a computer (i.e. not a VM)?
3. Are you sitting physically at the computer (i.e. not using remote desktop/vnc/etc)?
4. Is your OS perhaps "eating up" the ctrl + mouse wheel event to do something specific (e.g. with window management), 
5. can you use ctrl + mouse wheel in other applications on the same system?

**Comment by alexdima** [comment]
I wanted to add that there are also commands for the font zooming. Here is what I use:

```
	{ "key": "ctrl+numpad_add",		"command": "editor.action.fontZoomIn", "when": "isWindows" },
	{ "key": "ctrl+shift+=",		"command": "editor.action.fontZoomIn", "when": "isWindows" },
	{ "key": "ctrl+=",				"command": "editor.action.fontZoomIn", "when": "isWindows" },
	{ "key": "ctrl+numpad_subtract","command": "editor.action.fontZoomOut", "when": "isWindows" },
	{ "key": "ctrl+shift+-",		"command": "editor.action.fontZoomOut", "when": "isWindows" },
	{ "key": "ctrl+-",				"command": "editor.action.fontZoomOut", "when": "isWindows" },
	{ "key": "ctrl+numpad0",		"command": "editor.action.fontZoomReset", "when": "isWindows" },
	{ "key": "ctrl+0",				"command": "editor.action.fontZoomReset", "when": "isWindows" },
```

This rebinds ctrl++ and ctrl+- to zoom in the editor font and not the entire vscode.

**Comment by blueray453** [comment]
> [Here](https://github.com/microsoft/vscode/blob/9788e81e98dddbc36e923effa9a39cc71337e019/src/vs/editor/browser/controller/mouseHandler.ts#L107-L124) is our code. We look for a mouse wheel event with only the `ctrl` key pressed.
> 
>     1. Are you perhaps pressing other modifiers besides `ctrl`?
> 
>     2. Do you have Linux installed natively on a computer (i.e. not a VM)?
> 
>     3. Are you sitting physically at the computer (i.e. not using remote desktop/vnc/etc)?
> 
>     4. Is your OS perhaps "eating up" the ctrl + mouse wheel event to do something specific (e.g. with window management),
> 
>     5. can you use ctrl + mouse wheel in other applications on the same system?

1. No. I am only pressing Ctrl.
2. Linux Mint 20 is installed natively on my computer (i.e. not a VM).
3. I am sitting physically at the computer 
4. Not sure. ctrl + mouse works with other application.
5. Yes

**Comment by blueray453** [comment]
@alexdima I also wanted to share my `keybindings.json` and `settings.json` in-case something is conflicting.
[json-files.zip](https://github.com/microsoft/vscode/files/5877059/json-files.zip)

**Comment by blueray453** [comment]
Do not know how to say this, but suddenly it is working.
