### ISSUE TITLE
Enable intendation folding in Code Blocks [markdown]

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#114828]
The same as with the main content -- reading is easier than writing . So please add ability to fold the code in { \`\`\` <<_>> \`\`\` } .

It also should be enabled for comments { \<!-- <<_>> --\> } .

**Comment by mjbvz** [comment]
@aeschli Is there a command to get the folding ranges for a string or a file?

@meganrogge Adding you since you worked on folding recently
