### ISSUE TITLE
Support terminal links for Windows paths containing whitespace

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/vscode#114885]
### Unable to open file path when file path contains whitespace, specially with the username with space.  

- VSCode Version: 
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
- OS Version: Windows 10 10.0.19042 N/A Build 19042

Steps to Reproduce:

<img width="959" alt="Untitled" src="https://user-images.githubusercontent.com/59607654/105678717-795baa80-5f13-11eb-8378-8f9a24dbaffe.png">

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by starship863** [comment]
I really need this feature. My whole project is located at Onedrive business folder which will always contains a space in path like "Onedrive - Company Name".

Looking forward to this new feature.

**Comment by tjx666** [comment]
@Tyriar Same on MacOS: 

![image](https://user-images.githubusercontent.com/41773861/148694209-fbd0c8a0-7d5d-49bd-b1b4-87eb487bc91d.png)

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/97941
