### ISSUE TITLE
Git stage selected ranges doesn't work without when condition in a specific case

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#114839]
- VSCode Version: 1.52.1
- OS Version: Win 10  

It's hard to describe, please watch the reproduce gif.

Steps to Reproduce:  

![stage](https://user-images.githubusercontent.com/28700378/105599815-94250680-5dcf-11eb-9c5f-6fab8d5e8aa9.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
I'm not sure I'm understanding the exact steps here. Can you please list out the steps you are performing, and what the issue is you are running into and what you expect?

**Comment by wenfangdu** [comment]
@eamodio Hi, sorry if the gif confused you, I thought it would describe better than words. 

The issue is if the `Git stage selected ranges`'s `When` condition is unbound (which is `isInDiffEditor` by default), still I can only stage selected changes through diff editor, in the normal editor, it wouldn't work.

This is understandable, but given `isInDiffEditor` is already unbound, this limitation should be removed as well.

**Comment by dwelle** [comment]
I'm experiencing the same issue. The staging works, but it's not reflected in the diff editor, same as shown in the GIF above.
