### ISSUE TITLE
I can't lunch a terminal

### ISSUE THREAD

**Issue by RokDo** [microsoft/vscode#114824]
Issue Type: <b>Bug</b>

When i open terminal it close and show: The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 1392). 
What i need to do to fix it?

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.84GB free)|
|Process Argv|--crash-reporter-id d21da198-ac5f-4dfb-9c9a-8d82526d92ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|4.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30247032

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by RokDo** [comment]
What info you need?

**Comment by meganrogge** [comment]
Enabling trace logging
For some terminal issues it's useful to get trace logs, this can reveal at what point something is failing. Follow these steps to get the logs:

Close all VS Code windows
Launch VS Code from the terminal using code --log trace
At this point you should reproduce the terminal issue you're having
Run the command "Developer: Open Log File..." (F1 opened command palette) and select Window to get an editor containing the logs. Select the Remote Extension Host log file if you're diagnosing an issue in a remote workspace (SSH/WSL/Containers/Codespace).

**Comment by RokDo** [comment]
Oh i fix it but you need to use F1 and Terminal: Select Defalut Shell and select Command Prompt
