### ISSUE TITLE
VScode installer auto-delete

### ISSUE THREAD

**Issue by vishalsinghpoker** [microsoft/vscode#114832]
- VSCode Version: Latest
- OS Version: Windows 10 pro

Steps to Reproduce:

after downloading the VScode installer, then click to install in the system, windows automatically removing the vscode setup file.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Are you using an antivirus product? Did you check whether it is doing this?

**Comment by vishalsinghpoker** [comment]
yes, antivirus auto deletes the vscode installer. after de-activating it's working fine. thanks

**Comment by joaomoreno** [comment]
Closing this as it seems to be an antivirus issue. I propose to reach out to the antivirus company.
