### ISSUE TITLE
Links to files include trailing quote

### ISSUE THREAD

**Issue by ChaseMor** [microsoft/vscode#114801]
- VSCode Version: 1.52
- OS Version: Darwin x64 20.2.0

Steps to Reproduce:

1. Log a string to an output channel that contains a path to a file within the workspace (e.g. the launch config)
2. Have the path to the file surrounded by single quotes `'`

![Screen Shot 2021-01-21 at 6 21 24 PM](https://user-images.githubusercontent.com/13285164/105560492-baac4a00-5cc8-11eb-9025-49db705139e3.png)

Notice how the link, shown by the underlined text, contains the last single quote. Clicking the link tries to open a file with the trailing quote in the path which doesn't exist.

Does this issue occur when all extensions are disabled?: No? Because they're wouldn't be logging?

**Comment by bpasero** [comment]
Thanks for the issue, but I am not willing to invest into the output link detector since I think https://github.com/microsoft/vscode/issues/107314 is the right solution out of this.
