### ISSUE TITLE
Debugger doesn't focus any source code if all frames are "deemphasized" making it unclear that the debugger paused

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#114914]
There was some work in https://github.com/microsoft/vscode/issues/65012 to allow DAs to mark frames as "deemphasize" and they would not be auto-focused when the debugger breaks. This allows us to focus on user code rather than framework code.

This generally works great, except in the case where an exception occurs that appears to have no user code in the stack. In this case the debugger doesn't jump to any source at all, and the only indication that the debugger paused is the Play/Pause icon in the debug toolbar.

Originally, I would scan the stack myself and if there are no frames that are user code, then do not set deemphasize on the top frame. However, since started to fetch the stack lazily, this no longer works. When VS Code asks for only the top frame, I also only fetch the top frame from the debugger and don't have enough information to know whether there is user code further up the stack.

I think it would be better if VS Code does not find any frames to focus, it always focuses the top frame.

(cc @isidorn)

**Comment by weinand** [comment]
@isidorn I think Dan's suggestion sounds like a good approach:
> I think it would be better if VS Code does not find any frames to focus, it always focuses the top frame.

**Comment by isidorn** [comment]
Agree, assigning to this milestone to potentially fix

**Comment by isidorn** [comment]
@dantup would be great if you can verify this with the insiders build tomorrow (Thursday)

**Comment by DanTup** [comment]
@isidorn it seems like something isn't working right - in the case where I do have an allowed (user) frame 4th in the stack, it's _always_ pausing on the very top frame.

Is it possible it's only looking at the very first frame (since VS Code initially only asks for one frame), rather than the larger set that's requested?

<img width="1322" alt="Screenshot 2021-01-28 at 15 06 53" src="https://user-images.githubusercontent.com/1078012/106157543-bd9cb400-617a-11eb-9c6d-c2c2ee48bc29.png">

**Comment by isidorn** [comment]
Looking at the code that is not possible.
Can you create some repo with mock debug so I try it out.
Or you can put a breakpoint here and try to investigate more https://github.com/microsoft/vscode/blob/bb93190883278b0bd7de703edd9a6db7396a4aaa/src/vs/workbench/contrib/debug/common/debugModel.ts#L426

**Comment by DanTup** [comment]
@isidorn got a repro - turns out there are two things that cause stack frames to be grayed:

1. Not having a `Source`
2. Having a source marked `deemphasize`

The problematic case is 2, not 1. I've got a repro here:

https://github.com/DanTup/vscode-repro-114914

I made MockDebug return no source for the top few frames:

```ts
const hasSource = startFrame + f.index > 2;
const sf = new StackFrame(f.index, f.name, hasSource ? this.createSource(f.file) : undefined, 0, 0);
```

In current stable, this causes the debugger to pause on the first frame with source:

![Screenshot 2021-01-28 at 15 46 06](https://user-images.githubusercontent.com/1078012/106162399-f7bc8480-617f-11eb-8040-035b91dc5564.png)

But with the new changes, it pauses on the top frame:

![Screenshot 2021-01-28 at 15 46 47](https://user-images.githubusercontent.com/1078012/106162462-0c008180-6180-11eb-81d6-edc76836a26c.png)

**Comment by isidorn** [comment]
@dantup thanks for a lovely repro.
I made a "rookie mistake" as my friend would say. Try it out from tomorrow and it should be good.

**Comment by DanTup** [comment]
heh, I've made that mistake a _feeeew_ times 😄

Will do, thanks!

**Comment by connor4312** [comment]
Hm, I can can still repro the second issue Dan mentioned

![](https://memes.peet.io/img/21-01-5c1d0a75-a0e9-43ff-b989-7902b4046720.png)

First few stackframes:

```json
[
  {
    "id": 8,
    "name": "<anonymous>",
    "line": 1,
    "column": 1,
    "presentationHint": "normal"
  },
  {
    "id": 9,
    "name": "Module._compile",
    "line": 955,
    "column": 30,
    "presentationHint": "normal"
  },
  {
    "id": 10,
    "name": "Module._extensions..js",
    "line": 991,
    "column": 10,
    "source": {
      "name": "<node_internals>/internal/modules/cjs/loader.js",
      "path": "<node_internals>/internal/modules/cjs/loader.js",
      "sourceReference": 1789622821
    },
    "presentationHint": "normal"
  }
]
```

**Comment by DanTup** [comment]
Yeah, I still see it in my real project (same as my previous screenshots) although it's working in the Mock Debug example. I'll try to figure out what else is different and update my repro.

**Comment by isidorn** [comment]
Weirdly this seems to work for me
@connor4312 are you debugging some special program when you see this? I am doing a simple `console.log` app
Here's what I see with you custom vsix: the first stack frame gets focussed.
Just to clarify: for you it seems like the original issue does not get fixed ("all frames are deemphasized and none get focused")?
[Code pointer](https://github.com/microsoft/vscode/blob/178e7034bc4667c8c044c22ca61cc8004e59ad36/src/vs/workbench/contrib/debug/common/debugModel.ts#L426) for potential breakpoints

@DanTup let me know if you are able to update your repro so I can see the issue on my machine

![Screenshot 2021-02-01 at 14 43 03](https://user-images.githubusercontent.com/1926584/106466592-d1f2f080-649b-11eb-9f41-d2513ab1b340.png)

**Comment by DanTup** [comment]
Struggling to figure this out... I've copied/pasted pretty much my entire stackTraceRequest responses into the repro, and it's working correctly! I'll keep trying..

**Comment by DanTup** [comment]
I copied the same hard-coded stack from Mock Debug into my real debug adapter, and I still see the issue there - it jumps to the wrong file. So it seems like there's something outside of the `stackTraceRequest` affecting this, though I'm not sure what yet.

**Comment by isidorn** [comment]
Pushing out to next milestone to give us more time to figure out what is going on

**Comment by isidorn** [comment]
@dantup since we can not get a repro, can you maybe put a brekapoint here https://github.com/microsoft/vscode/blob/42cdb7fa0b5092cdbbb2eee9e9db811cf069bdf6/src/vs/workbench/contrib/debug/common/debugModel.ts#L426

And figure out what gets to be the `topStackFrame`, and why isn't it the one you expect to get focussed?

**Comment by DanTup** [comment]
Sorry for the delay. I put a breakpoint there and the call stack only had the top frame in it:

![Screenshot 2021-02-04 at 14 57 57](https://user-images.githubusercontent.com/1078012/106910750-702fc200-66f9-11eb-9ecc-e60000fdea46.png)

Could it be a race because of this?

![Screenshot 2021-02-04 at 14 59 25](https://user-images.githubusercontent.com/1078012/106910936-9b1a1600-66f9-11eb-9043-5f9d4f01fb37.png)

If so, I should be able to repro in MockDebug by making only the second request slow (it would certainly be slower in my real DA than the top frame, as I recently added an optimisation to avoid a round trip to the VM for the top frame).

**Comment by DanTup** [comment]
Yep, I can repro in mock debug now:

https://github.com/DanTup/vscode-repro-114914

This now breaks in `file_sdk` but should break in `file_user`. The difference is ensuring `supportsDelayedStackTraceLoading = true` and making sure the second stack trace request is slower.

Moving the `focus()` call down one line *might* solve it?

**Comment by isidorn** [comment]
@DanTup lovely, thanks for steps. 
I have pushed a fix for this. Would also appreicate if you try it out with VS Code insdiers from Friday. Thanks!

**Comment by DanTup** [comment]
@isidorn sorry for the delay! This does appear to work now in both my MockDebug fork and my real code, although it does first open the "wrong" file (top frame), which results in a flicker and the file becoming visible in the open tabs:

![Screenshot 2021-02-09 at 15 12 57](https://user-images.githubusercontent.com/1078012/107383911-60452300-6ae9-11eb-9283-bd1e79fb992a.png)

If the top frame is deemphasized, could focusing it by delayed for a short period to allow time for the second request? It seems like that request will always be _some_ slower than the first, so no matter how fast it responds this flicker will occur.

**Comment by isidorn** [comment]
@dantup thanks for letting me know.
Focusing with a delay sounds like a bit of a hack. A better approach might be: if there is only one stack frame and it is deemphasized do not focus it. It is also a bit hackish, but at least does not require any timeouts. Let me know what you think

**Comment by DanTup** [comment]
Yes, I'd agree that would be better if you're happy with it. I'm not sure how long frames 2-19 typically take or how long you'd be prepared to wait.

One thing that could be nice in future might be to allow DAs to return more than just the top stack frame in the first request. It feels awkward to be sending two requests and the DA can already basically send as many as it wants (and whatever `totalFrames` it wants) in subsequent requests. This would - for example - allow me to just send 10 frames in the first request.

(It's possible that already works today given the previous DA changes, although it's not clear whether that should be done - especially if VS Code sends the top-frame and frame-2-to-19 requests concurrently).

**Comment by isidorn** [comment]
Ok. However let's flow a bit with the current approach and I am open to change this in a couple of weeks.

**Comment by DanTup** [comment]
Sgtm - I was just thinking out loud and don't think changing that is too important (and it may warrant other DA author feedback). From other threads, it seems like DAs have better ideas of how expensive getting stack frames are, so letting them be more in control might be a nice future direction.

The fix you suggest above resolves the main user-facing issue though 👍

**Comment by isidorn** [comment]
Sounds good.
