### ISSUE TITLE
Cannot open a remote workspace via --remote syntax

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114900]
Looking at the implementation of `--remote` support, I do not think we correctly open a workspace when I provide one via command line, e.g. `code-insiders --remote wsl+Ubuntu /home/ticino/workspaces/workspace.code-workspace`

I would have expected that in this method we create a workspace openable if we encounter the `.code-workspace` file extension:

https://github.com/microsoft/vscode/blob/c8ff3471b596a8a21e1f080f3f038e08ee148b6e/src/vs/platform/windows/electron-main/windowsMainService.ts#L922-L937

**Comment by aeschli** [comment]
Looks like I broke this with https://github.com/microsoft/vscode/commit/f667462a2a8a12c92dbcdd8acf92df7354063691
