### ISSUE TITLE
Intellisense is not working in react native project

### ISSUE THREAD

**Issue by dineshchandrasekaren** [microsoft/vscode#114996]
Issue Type: <b>Bug</b>

intellisense is not work in react native

Extension version: 1.3.0
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A4-4350B R4, 5 COMPUTE CORES 2C+3G      (2 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.47GB (0.98GB free)|
|Process Argv|--crash-reporter-id d21752c6-772b-4340-a089-06376a4c9802|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

![Screenshot 

> (13)](https://user-images.githubusercontent.com/64305855/105825826-0707ca80-5fe6-11eb-8b16-2120d220c712.png)

![Screenshot (14)](https://user-images.githubusercontent.com/64305855/105825841-0bcc7e80-5fe6-11eb-9ba2-dc28e92f0190.png)
![Screenshot (15)](https://user-images.githubusercontent.com/64305855/105825867-1129c900-5fe6-11eb-8a09-efb1a158ee56.png)
![Screenshot (16)](https://user-images.githubusercontent.com/64305855/105825873-1555e680-5fe6-11eb-9e07-0631115128b6.png)

**Comment by dineshchandrasekaren** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Disable intellisense when typing <?php in php documents (#68535)](https://www.github.com/microsoft/vscode/issues/68535)
> * [intellisense not working (#109208)](https://www.github.com/microsoft/vscode/issues/109208)

I told is not working in react native project 
Please see above screen shots

**Comment by dineshchandrasekaren** [comment]
How to fix it .

My problem is if I type padd means it want to give options to me like paddingLeft, paddingRight,paddingHorizontal,paddingVertical .
But it is not working why how to fix it
You can see it in my images above

**Comment by mjbvz** [comment]
Seems to work for me:

<img width="1011" alt="Screen Shot 2021-01-26 at 9 40 11 PM" src="https://user-images.githubusercontent.com/12821956/105948023-13f4e000-601f-11eb-8a5f-ad3b85ce81f4.png">

Please share a small example project that demonstrates the issues


/needsMoreInfo

**Comment by dineshchandrasekaren** [comment]
Its working fine in my linux 
But I need it in windows 

I noticed one thing while using in linux 

I create the react then I was open the folder using vs code

After that it will automatically download one zip file name is intellicode xxxxxx.zip something I don't know exactly

 but in my windows I  uninstalled vs code and then install it again it was show same I feel like notepad without intellisense

**Comment by dineshchandrasekaren** [comment]
So can you tell me how to full  uninstall vs code 

I will install it again then try it

**Comment by dineshchandrasekaren** [comment]
Now its working sir thank you 

I was reset my pc then I install again node and npm ,vs code now it working 

- - - Thank you very much sir

**Comment by dineshchandrasekaren** [comment]
> Seems to work for me:
> 
> <img width="1011" alt="Screen Shot 2021-01-26 at 9 40 11 PM" src="https://user-images.githubusercontent.com/12821956/105948023-13f4e000-601f-11eb-8a5f-ad3b85ce81f4.png">
> 
> Please share a small example project that demonstrates the issues
> 
> 
> /needsMoreInfo



Can you suggest me usefull extensions for react native
