### ISSUE TITLE
Automatically Skip to setting.json when i trying to debug my C++/C file

### ISSUE THREAD

**Issue by IraShinking** [microsoft/vscode#114913]
I've confused by this question for such a long time ,that my vscode always **skip to the setting.json without anyother problems or notice when i try to debug my C++/C file**.
  Tonight I try to fix this problem, by checking profiles and looking for a few json file, but i still failed to fix it after modifying these json files. It has bothered my so much and i couldnot find any answer through searching the internet.
 Here're some of problems i thought but didnt help:

1. i thought it was setting java that bothering the debug mod from acting properly, but i can run _.java_ in my vscode
2. i found that i forgot to add the specified path of debugger to my launch.json, but after i added, it didn't fix up.
3. i thought the environment variable of python or java i added lately may do something wrong to it, but i cant tell why and how.

i can only run my C++/C file using extension, but never successed by using  F5 or ctrl+F5 because of this problem.
when i press F5 to run debugger of the C++ file, it looks like this:
![image](https://user-images.githubusercontent.com/24153413/105722500-b1d5a580-5f60-11eb-9146-3225ee5a5caa.png)
**then no matter i chose GDB or WINDOWS, it will automatically skip to setting.json**
here's my code in setting.json

`{
    "explorer.incrementalNaming": "smart",

    "debug.allowBreakpointsEverywhere": true,

    "workbench.colorTheme": "Tomorrow Night Blue",

    "code-runner.runInTerminal": true,

    "editor.wordWrap": "on",

    "editor.suggestSelection": "first",

    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",

    /*"python.languageServer": "Microsoft"*/
}`

and there's my code in launch.json
`
// https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md
 { "version": "0.2.0",
     "configurations":
      [{ "name": "(gdb) Launch", 

     "type": "cppdbg", 

     "request": "launch", 
 
     "program": "${fileDirname}/${fileBasenameNoExtension}.exe", 

    "stopAtEntry": false, 
    "cwd": "${workspaceFolder}", 
     "environment": [], 

     "externalConsole": true, 

     "internalConsoleOptions": "neverOpen", 

    "MIMode": "gdb", 

    "miDebuggerPath": "D:\\ira\\VSCBuilder\\mingw64\\bin\\gdb.exe", // i add this but it didnt work
    "setupCommands": [
         { 

            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing", 
            "ignoreFailures": false
         } 
    ],
    "preLaunchTask": "g++" // here i changed 'complie' into 'g++' and do it in task.json as well but still changed nothing
    }]
}`

**Comment by weinand** [comment]
@IraShinking 
The Quickpick menu to "Select Environment" only appears when VS Code cannot find the launch.json.

Is the "(gdb) Launch" selected in the debug dropdown menu?
<img width="398" alt="2021-01-25_16-55-10" src="https://user-images.githubusercontent.com/1898161/105729997-1d524f80-5f2e-11eb-9625-f8ad97068562.png">

Where does your "launch.json" live?
