### ISSUE TITLE
VS Code needs Expand/Collapse controls for ':::' syntax sections in markdown

### ISSUE THREAD

**Issue by MightyPen** [microsoft/vscode#114961]
Hello,
In our markdown documentation articles, the Zone Pivot and Versioning features are example that use the increasingly common syntax of `:::` (three colons) at the start of a line, to indicate a special section of content.
In practice, in VS Code markdown editor, when scrolling through .md file that has ::: sections, presently it is too difficult to really follow which section I am currently in.

It would help the ease of editing if I could expand/collapse these sections. Or maybe some other technique?

Thank you.
GeneMi (or perhaps contact Erik Hopf too)
2021/January/25

**Comment by mjbvz** [comment]
VS code's built-in markdown support targets [common mark](http://commonmark.org), which does not support `:::` blocks

However I believe an an extension could add folding support for these
