### ISSUE TITLE
Notebook diff editor screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114915]
<img width="1136" alt="Screenshot 2021-01-25 at 16 06 58" src="https://user-images.githubusercontent.com/1794099/105723819-82567700-5f27-11eb-9242-7eb27170330d.png">

* opened internal back
* pull
* got the usual conflict dialog
* selected overwrite
* open diff from SCM viewlet

fyi - I have both version locally, cannot attach to this issue

**Comment by rebornix** [comment]
Not sure which commit triggers it but the root cause is https://github.com/microsoft/vscode/commit/7468a060129fb55c50635d534c828473b2887828. Reverting this.

**Comment by rebornix** [comment]
Fixed via 7468a060129fb55c50635d534c828473b2887828.

**Comment by jrieken** [comment]
I now see different screen cheese...
