### ISSUE TITLE
Bugs in json settings manager

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#114909]
*Environment*
- VSCode Version: 1.52.1
- OS Version: linux

*Does this issue occur when all extensions are disabled?: Yes/No*

Yes

*Steps to Reproduce:*

1. Must use json settings manager: `"workbench.settings.useSplitJSON": true`
2. Open workspace settings <kbd>ctrl ,</kbd>
3. PROBLEM 1: nodes on the left are not sorted, so it's **very** hard to find things (especially when there are lots of extensions)
4. PROBLEM 2: when switching to another tab and then back, it automatically collapses all nodes and opens the default 'Commonly Used' node; this wastes even more time looking for the correct node again

I realise many devs use the GUI, but many prefer the json manager because `.vscode/settings.json` file is added to source control, and changes made by hand don't result in massive diffs. For those of us who prefer the "config as code" mantra, the json editor is more useful.

Thank you!

**Comment by gjsjohnmurray** [comment]
Related: #68386

Are you aware of this button as an alternative to `useSplitJSON`?

![image](https://user-images.githubusercontent.com/6726799/105717459-128cc000-5f18-11eb-8e7c-e8e1d0998a04.png)

It's my impression that the Split JSON settings interface is unlikely to get any love from the developers.

**Comment by lonix1** [comment]
@gjsjohnmurray Thanks, yes as I mentioned above I'm using the json editor *in lieu of the gui*. I also outlined reasoning for this.

Many devs commit config to source control, and want to control the config by hand. Relying on a gui means the config is auto-generated and that leads to ugly and hard-to-maintain diffs.

THEREFORE, given that many are using the json editor, the two bugs I mentioned should be fixed. They are incredibly frustrating. Incidentally, they seem to be minor and "should be" easy to fix.

**Comment by sandy081** [comment]
Thanks for the issue. Sorry that we are no longer enhancing split JSON UI in favour of rich UI and so we are not accepting any feature requests or bugs. This editor was mainly there for those who are still passionate to use it. Hence, I would close this issue.

**Comment by lonix1** [comment]
Okay thanks - you gotta focus on what you think is more important.

But for the record (and I hope others will find this issue and upvote it), many devs manage config by hand and check it into source control. For those devs, the json editor has two bugs.

I hope you'll reconsider at some point in the future. :smile:

**Comment by lonix1** [comment]
Future users who land here via google/whatever:

Upvote the original post above. When it reaches 20 they'll reconsider as that's their threshold for considering requests.
