### ISSUE TITLE
Test: Mac universal build

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#114974]
Refs: https://github.com/microsoft/vscode/issues/113851

- [x] Mac @aeschli with intel
- [x] Mac @kieferrm with apple silicon
- [x] Mac @deepak1556 with intel 
- [x] Mac @chrmarti with intel
- [x] Mac @jrieken with apple silicon
- [x] Mac @bpasero with apple silicon

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114974%0A%0A)

---

## Background 

We are looking to make universal build as the default for mac which can run natively on x86_64 as well as arm64. As a start in this iteration the default download on the website will point to universal build while we will still provide arch specific downloads.

<img width="1321" alt="Screen Shot 2021-01-25 at 8 32 38 PM" src="https://user-images.githubusercontent.com/964386/105800919-c445e400-5f4c-11eb-8097-30979dda9ce3.png">

## Testing

The website bits are pending to be merged and published to ppe https://github.com/microsoft/vscode-website/pull/924. So for testing use the builds from https://builds.code.visualstudio.com/builds/insider

- Download universal build and install on x86_64 machine which had a previously running native x86_64 copy.
   - verify that universal app continues your session from where you had left off on the previous native version without any changes to configurations
   - verify your everyday setup **just** works
   - verify automatic update works
  
- Download universal build and install on arm64 machine which had a previously running native arm64 copy.
   - verify that universal app continues your session from where you had left off on the previous native version without any changes to configurations
   - verify your everyday setup **just** works
   - verify automatic update works

**Comment by deepak1556** [comment]
I have assigned this item based on the members of team who have access to devices with M1 chips, feel free to reassign or unassign if you are blocked on other items. Thanks!

**Comment by bpasero** [comment]
The only way I figured out how to ensure I am on universal build is by checking the size of the application. Not sure we want a way to show this in e.g. the about dialog to diagnose issues?

**Comment by jrieken** [comment]
For me this isn't working

**Comment by joaomoreno** [comment]
@deepak1556 You forgot to update the `Create Issue` link, so people have created issues related to the wrong TPI.

**Comment by chrmarti** [comment]
@deepak1556 I don't have a silicon Mac. I'll just test with Intel, so you can potentially unassign yourself.

**Comment by kieferrm** [comment]
If got an M1, I'll test the apple silicon -> universal direction.

**Comment by paulmillr** [comment]
universal check can be done like this:

```
❯ file Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron 
Visual Studio Code - Insiders.app/Contents/MacOS/Electron: Mach-O 64-bit executable arm64
```

Universal is like this:

```
app: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
app (for architecture x86_64):	Mach-O 64-bit executable x86_64
app (for architecture arm64):	Mach-O 64-bit executable arm64
```
