### ISSUE TITLE
Adjustable mouse scrolling lines for file tree

### ISSUE THREAD

**Issue by daslicht** [microsoft/vscode#114987]
It woudl be nice if we could define the lines to scroll in the files Tree under Windows.
One nudge scrols about 4 lines atm and that independent from teh Windows Mouse Settings.
4 Lines is a huge JUMP.

**Comment by daslicht** [comment]
Under macOS this much better

**Comment by isidorn** [comment]
Sounds like tree and list scrolling feature request, forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
#102261

**Comment by daslicht** [comment]
@joaomoreno joaomoreno
```Mouse Wheel Scroll Sensitivity``` is only fo the content NOT the tree !

**Comment by joaomoreno** [comment]
Sure. The issue I mentioned above is the feature request for adding it to the tree.

**Comment by daslicht** [comment]
ahh ok yeh perfect !
