### ISSUE TITLE
Add support for an overlay context key service

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114901]
this is a follow up from https://github.com/microsoft/vscode/issues/107903#issuecomment-765589206

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/86d96faaaf8b15a66abc2d766dc47cbdabd177f9/src/vs/workbench/browser/parts/views/treeView.ts#L1126-L1137

We often create CKS that we only use for a few static values (see above). This can then cause issues with them not being disposed of or them being alive for too long. Instead should have a dead/immutable CKS which delegates everything to its parent, esp eventing, and which only holds a few static values.

**Comment by joaomoreno** [comment]
@jrieken Unfortunately, looking at the code again I don't really see creating a immutable context key service doing anything here.

I think to solve the pattern above we should just provide some util at the `menuService` level: `getActions()`. Then, adopt it everywhere, and look into removing all other remaining calls to `this._contextKeyService.createScoped()`.

**Comment by jrieken** [comment]
> That util should probably only take in IContext as an arg, instead of a whole IContextKeyService

Doesn't that mean that actions are stale and not updated when context keys change?

**Comment by joaomoreno** [comment]
D'oh, you're right. Now I remember why this whole store. On it.
