### ISSUE TITLE
html.format.unformatted has no affect to closed tags

### ISSUE THREAD

**Issue by calebeaires** [Microsoft/vscode#11496]
- VSCode Version: 1.4.0
- OS Version: MacOS

Steps to Reproduce:

1. Change value to ```"html.format.unformatted"``` to ``` null``` on settings.json
2. Create a single html document with span tags
3. Format command to the Initial span tag ```<span>``` works, but not to the close tag ```</span>```
4. **but** when using just one value like ``` "html.format.unformatted": "abbr" ``` it works

**Comment by aeschli** [comment]
@calebeaires Can you paste the html code snippet that you format?

**Comment by calebeaires** [comment]
This is the tags:

```
    <span>
        test word
            </span>
```

**Comment by aeschli** [comment]
As written in the settings comment, 'null' defaults to all tags listed at https://www.w3.org/TR/html5/dom.html#phrasing-content.
span is part of these tags, that why the content of span is not formatted.

If you want all elements to be formatted, use
```"html.format.unformatted": ""````
