### ISSUE TITLE
View doesn't scroll with selector if there is more then one

### ISSUE THREAD

**Issue by VojtechStep** [microsoft/vscode#11490]
- VSCode Version: Code - Insiders 1.5.0-insider (6dff3f61be3c8f99bac8e9ba9a0aecef51b4dbbb, 2016-09-03T01:41:40.747Z)
- OS Version: Windows_NT ia32 10.0.14905

Steps to Reproduce:
1. Click on a spot within a document
2. Use Alt+Ctrl+(ArrowUp/ArrowDown) to create another selector instance
3. Hold ArrowUp or ArrowDown until the selectors get out of the view

Possible solution:
Make the view follow the main selector (the bold one)

**Comment by alexandrudima** [comment]
@VojtechStep Some time ago (more than 1 year) we had the following behaviour:
* when going up we would reveal the first (lowest line number) cursor
* when going down we wold reveal the last (highest line number) cursor

In many cases, where having multiple cursors that would span more than the viewport size, this would lead to a very jumpy behaviour. The root problem is that we don't know where the user is looking when there are multiple cursors...

**Comment by siegebell** [comment]
@alexandrudima how about: when all cursors are currently visible and a subset of them are moving outside the viewport, all in the same direction, then scroll the editor in that direction. I.e. do try to scroll when there is no ambiguity.

**Comment by alexandrudima** [comment]
:+1: This could be implemented by computing a bounding box around all the cursors and if the bounding box fits within the viewport, then scroll the viewport accordingly.

**Comment by alexdima** [comment]
Let's track in #6995
