### ISSUE TITLE
Search results omit certain characters

### ISSUE THREAD

**Issue by bugpowder** [microsoft/vscode#114940]
- VSCode Version: Version: 1.52.1
- OS Version: Big Sur 11.1

Steps to Reproduce:

1. Create a file text.py with these contents:

```
# AAAAAAAAAAAAAAAAAAAAA = 'foobar'

# BBBBBBBBBBBBBBBBBBBBBB = 'foobar'

# AAAAAAAAAAAAAAAAAAAAA = 'foobar'

# AAAAAAAAAAAAAAAAAAAAA = 'foobar'

# AAAAAAAAAAAAAAAAAAAAA = 'foobar'

# BBBBBBBBBBBBBBBBBBBBBB = 'foobar'

# AAAAAAAAAAAAAAAAAAAAA = 'foobar'
```

2. Do a file search for the term "foobar"

In the result lines that are shown, the lines with B are shown without the initial "#". 

This is not about the variable being named AAA... vs BBB... though, it's about the length of the variable, I just used different letters to make it easier to see where the issue is in the results. 

I narrowed the issue in that the variables with B are 1 character above  some internal limit (they are 22 chars, whereas AAA... are 21 chars), and it causes the # to drop, giving misleading results. This happened a source file with regular variable names, which is how I discovered it.  It appears as if 22 is somehow some significant limit.

![vscode_bug_showcase](https://user-images.githubusercontent.com/1735274/105753122-e04b8480-5f50-11eb-9d83-65456dacccc3.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/59310, indeed there is an internal limit which can look unexpected when the search view is very wide. You might be more interested in the Search Editor if this is important to you.

**Comment by bugpowder** [comment]
> Search Editor

Thanks for the reply. 

What is the "Search Editor" tho?
