### ISSUE TITLE
HTML figcaption tag should be suggested when using the full word instead of only "figc"

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/vscode#114923]
- VSCode Version: 1.52.1 commit ea3859d
- OS Version: Windows 10 1909

Steps to Reproduce:

1. In an html file, write `figure` and press <kbd>TAB</kbd>. You'll see the following behavior, which is correct.

    ![image](https://user-images.githubusercontent.com/31348972/105733986-cbfc8d00-5f3a-11eb-9218-39d138dd19e2.png)

    ![image](https://user-images.githubusercontent.com/31348972/105734007-d4ed5e80-5f3a-11eb-80bb-3b688d884579.png)

2. Try the same with `figcaption`, it doesn't work.

    ![image](https://user-images.githubusercontent.com/31348972/105734076-edf60f80-5f3a-11eb-8648-a142aca52ffd.png)

3. Try again with only `figc`, it works.

    ![image](https://user-images.githubusercontent.com/31348972/105734171-06fec080-5f3b-11eb-9a81-8ff6e669a64b.png)

4. **The same issue with `time` tag, but VSCode's Emmet completely doesn't recognize `time`.**

Expected behavior:

The suggestion should show using the full tag `figcaption`.

**Comment by Youssef1313** [comment]
cc: @rzhao271

**Comment by AnuBhar** [comment]
I am starting to look into this issue. Have been able to repro it. figcaption does not have any suggestions, only figc does.

**Comment by rzhao271** [comment]
Code pointer:
https://github.com/microsoft/vscode-emmet-helper/blob/main/src/emmetHelper.ts#L523

We need to add `figcaption` to `commonlyUsedTags`.

**Comment by Youssef1313** [comment]
@rzhao271 That should go in https://github.com/microsoft/vscode-emmet-helper/blob/main/src/data.ts?
I don't see "figc" there, so confused a little bit how "figc" works today.

**Comment by rzhao271** [comment]
@Youssef1313 'figc' gets recognized as a snippet here instead
https://github.com/emmetio/emmet/blob/master/snippets/html.json#L110

**Comment by rzhao271** [comment]
\closedWith 7661c8e
