### ISSUE TITLE
User data: register a better label provider

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114979]
I see the following label in web selfhost when opening keybindings or settings file:

![image](https://user-images.githubusercontent.com/900690/105815648-8d56e900-5fb3-11eb-8674-9ff9d801de7f.png)

I think this is a bit misleading and leaks the custom protocol to the user, I think we can register a better label provider to show a better label here?

//cc @isidorn

**Comment by sandy081** [comment]
I remember @JacksonKearl added label provider for this scheme recently only in web - not sure if this caused this.

**Comment by isidorn** [comment]
@JacksonKearl feel free to also assign to me if you would like me to investigate

**Comment by JacksonKearl** [comment]
Yes that was an intentional change to better differentiate those paths from OS paths. (Previously it'd say something like `~/User/settings.json`, which seems misleading). Happy to tweak if you have any suggestions

**Comment by bpasero** [comment]
If the intent is to distinguish from normal OS paths then maybe the label could be more user friendly and not leak the schema?

**Comment by JacksonKearl** [comment]
Okay, some ideas: 

Appending "(In Memory)" to the path:
![image](https://user-images.githubusercontent.com/8586769/106029024-84cce400-6081-11eb-8482-079b4c9b311e.png)
![image](https://user-images.githubusercontent.com/8586769/106029090-97471d80-6081-11eb-9c7b-9d64fee9c47c.png)

Prepending:
![image](https://user-images.githubusercontent.com/8586769/106029271-c5c4f880-6081-11eb-814f-c3359a4542cb.png)
![image](https://user-images.githubusercontent.com/8586769/106029338-d4abab00-6081-11eb-8b97-6cc94c8862f2.png)

**Comment by sandy081** [comment]
I do not think `In Memory` is correct because these files are stored in indexed DB in web. Sorry if you mention it already, what is the reason for not showing just the path ?

**Comment by JacksonKearl** [comment]
This is for search editors being able to track down the real location of the file. If it's just `/User/settings.json` there's some ambiguity about where the file actually lives, as to the user it looks like an OS path

**Comment by sandy081** [comment]
I see. One option would be to use **Preferences** as logical group label for all user data resources or **Settings** which we use for Settings Sync.

**Comment by bpasero** [comment]
Yeah I like "Settings" or "Preferences", curious how that would look like.

**Comment by isidorn** [comment]
+1 for that

**Comment by JacksonKearl** [comment]
Pushed a change to `(Settings)` prefix
![image](https://user-images.githubusercontent.com/8586769/109798112-30141000-7bcf-11eb-9dfb-d6d4925995f7.png)
