### ISSUE TITLE
Search smoke test failure

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#114993]
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Search
           dismisses result & checks for correct result number:
     Error: Timeout: get text content '.search-view .messages .message>span' after 20 seconds.
      at /Users/runner/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/1/s/test/automation/out/code.js:9:58)

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=102159&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/115244
