### ISSUE TITLE
Integrated Terminal error = El proceso del terminal finalizó con el código de salida: 1

### ISSUE THREAD

**Issue by mjarte** [Microsoft/vscode#11497]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
2.

**Comment by mjarte** [comment]
No function Integrated Terminal....

**Comment by Tyriar** [comment]
This means that the shell process could not be launched. You likely need to tweak your `terminal.integrated.shell.windows` value in your `settings.json` file.
