### ISSUE TITLE
Test outline, breadcrumbs, quick pick for notebooks

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114902]
Refs: https://github.com/microsoft/vscode/issues/98173

- [x] anyOS @misolori
- [x] anyOS @alexdima 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114902%0A%0A)

---

We have added support for outline, breadcrumbs, and symbol picks for notebooks. This needs testing. Use an extension that supports native notebooks, e.g [GH issue notebooks](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks) or [Jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) notebooks:

The outline of a notebook is derived from its cells - markdown and code cells. The contents of an outline entry is the first non-empty line of that cell. The hierarchy of the outline is derived from headers (of markdown cells), e.g a cell with `# H1` is the parent of all subsequent cells that don't contain an equally strong heading. 

Please test that

* the outline view and breadcrumbs shows entries for notebooks following the logic explained about
* the outline view and breadcrumbs update when 
  * changing cells contents
  * remove cells
  * adding cells
* breadcrumbs always follow the current selection of notebooks
* breadcrumb elements show a picker
* the order of items in the breadcrumbs picker can be configured via `breadcrumbs.symbolSortOrder`
* selecting an item from the breadcrumbs picker focuses cells but MD cells stay in preview mode
* the `breadcrumbs.symbolPath`-setting is working in notebooks
* outline follows the current selection when enabled ("Follow Cursor" in its title (`...`) menu)
* outline supports sorting by name, type, and position (default)
* from the outline selecting an item with single-click reveals it, double-click also focuses it
* cmd+clicking an item opens it in a new side-editor
* `notebook.outline.showCodeCells` allows to configure if code cells show in breadcrumbs and outline
* quick outline contains all entries and works just as usual

**Comment by gjsjohnmurray** [comment]
When a code cell is set to a language for which a DocumentSymbolProvider exists, should I expect to see the same hierarchy within the notebook cell's Outline or Breadcrumb entry as I do if I copy the code from the cell, paste it into a new untitled document, and set that to the same language mode?

**Comment by jrieken** [comment]
No

**Comment by gjsjohnmurray** [comment]
Is this already planned for the future? Or should I open an enhancement request?

**Comment by jrieken** [comment]
This has been thought of but there are currently no plans. We do have the infrastructure in place but code cells are often short-ish, e.g define little symbols, so that this isn't a priority right now
