### ISSUE TITLE
Unable to save & retrieve secrets using getPassword

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#114955]
- Version: 1.53.0-insider
- Commit: dcda88e5a69a52b3a9e141af73b68caae08cb2bf
- Date: 2021-01-25T08:41:30.565Z
- OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Use the new VSC API in insiders
2. Use context.secrets.get & set to save and retrieve passwords
3. No errors, when when invoking `get`, `undefined` is returned. I.e. password isn't saved.

Does this issue occur when all extensions are disabled?: N/A

**Comment by RMacfarlane** [comment]
@DonJayamanne I'm having trouble reproducing this, can you share the extension code you're using? I did recently rename `set` to `store`, but that would have thrown an error
