### ISSUE TITLE
Test: Find all references to file for JS/TS

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#114966]
Refs: #66150

- [x] Mac @kieferrm
- [x] Linux @aeschli
- [x] Windows @fiveisprime

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114966%0A%0A)

---

## Background 

We've added support for 'find all references to file' for JS and TS. This is only available in TS 4.2+

## Testing
- Make sure you are using TypeScript 4.2+ in your workspace.
- Confirm that file references are shown when triggered the following ways:
    - For the currently active file using `Find file references` command
    - Right click on editor tab
    - Right click on a file in the explorer
    
- Now downgrade to an older TypeScript version
- Confirm that those commands are no longer available

**Comment by kieferrm** [comment]
LGTM
