### ISSUE TITLE
Breadcrumbs: drive letter is lowercase

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114908]
I noticed that a file I open that is not inside the workspace appears with a lowercase drive letter:

![image](https://user-images.githubusercontent.com/900690/105712978-dc047480-5f1a-11eb-8fe2-a7aacd4d023d.png)

I thought our label provider takes care of uppercasing if presented as label, such as the editor tabs do (when breadcrumbs are disabled):

![image](https://user-images.githubusercontent.com/900690/105713354-559c6280-5f1b-11eb-929b-79f599b1d31c.png)

Not sure if this is a label provider issue or not.

**Comment by jrieken** [comment]
@bpasero this is using the value of [`getOriginalUri`](https://github.com/microsoft/vscode/blob/475d3464e87ebea002b5046ddef8c94ff5eb6739/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L268)

**Comment by bpasero** [comment]
@jrieken yeah that is fine, we have a way to always uppercase the drive letter when it is being displayed to the user:

LabelService:
https://github.com/microsoft/vscode/blob/dcc1e9df99189622b79282a868460f6b6815bc68/src/vs/workbench/services/label/common/labelService.ts#L286-L288

More generic method without service:
https://github.com/microsoft/vscode/blob/675638196d27275f1daf688a2a4a71e70f68cd78/src/vs/base/common/labels.ts#L95-L101

I think Windows is typically showing drive letters in uppercase, so we did so too:

![image](https://user-images.githubusercontent.com/900690/105720187-74065c00-5f23-11eb-89c9-0ba5f183da2e.png)

**Comment by jrieken** [comment]
Yeah, I believe my question is why `getOriginalUri` isn't doing this? Its doc says: "and should be used whenever the URI is presented to the user" which you now says in't true

**Comment by bpasero** [comment]
@jrieken `originalUri` is the thing that was passed to the editor when opening and that can be different from the canonical URI as such you are using the right kind of URI. However, when the URI is created it can have any form of uppercase or lowercase drive letter (for the file access it doesn't really matter). Only when we display the URI as a label to the user, we need to use the label service to get consistent display. I do not think the `originalUri` should be doing that because it literally just passes on what it got.

**Comment by jrieken** [comment]
I'd say the comment for `getOriginalUri` is bogous/misleading. Nevertheless, I can do all the tweaks but I actually do use a `ResourceLabel` which consumes the label service. So, this might actually @isidorn after all. 

https://github.com/microsoft/vscode/blob/475d3464e87ebea002b5046ddef8c94ff5eb6739/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L134

**Comment by bpasero** [comment]
Yeah good point, I have updated the JSDoc:

```
The original URI of an editor is the URI that was used originally to open the editor and should be used whenever the URI is presented to the user, e.g. as a label together with utility methods such as `ResourceLabel` or `ILabelService` that can turn this original URI into the best form for presenting.
```

**Comment by isidorn** [comment]
Sounds like the labelService does not normalize the drive letter for uris outside of the workspace. Let me assign to January and I can investigate this week

**Comment by isidorn** [comment]
The issue was the the `ResourceLabelWidget` was not calling the `labelService` in a corner case it seems.

**Comment by isidorn** [comment]
Will have to reopen, the fix was not good.

**Comment by bpasero** [comment]
I think the easiest would be to just put the result of `basenameOrAuthority` to `normalizeDriveLetter`

**Comment by isidorn** [comment]
Yeah, let's do that. I will push next week.
