### ISSUE TITLE
Helper for interfaces/types structure 

### ISSUE THREAD

**Issue by whitecolor** [Microsoft/vscode#11495]
Here TS is able to detect which type of object is required, if I don't pass `url` property here it errors:
![image](https://cloud.githubusercontent.com/assets/736697/18225276/7ba35f74-7208-11e6-945a-cd05d55cf9a6.png)

But how to get help on the current interface/type which fields there present/required/etc?

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
@whitecolor, thank you for opening this issue. 

I don't quite understand. Can you explain "But how to get help on the current interface/type which fields there present/required/etc?" by providing an example.

**Comment by waderyan** [comment]
I apologize for the spam. Strange issue on my end with the comment button.

**Comment by whitecolor** [comment]
Ok I will make a simplier example
```ts
interface AB {
  a: number
  b: string
}

function f(x: AB) {
  return x
}
...

/* 
Now I want to call this f function
I don't know/remember what expected is type AB is what and properties does it expect
and unfortunately I don't get enough help from the editor on this topic
*/
f({ })
```
Here with pictures:
Ok now I know that it expects `AB` type, but what is AB type?
![image](https://cloud.githubusercontent.com/assets/736697/18306962/a8de9916-7507-11e6-9a2f-df7f6fd7c292.png)

Ok then I type "a", wow, I guessed there is "a" property on the type an it is a number - great
![image](https://cloud.githubusercontent.com/assets/736697/18306999/d7c6f37c-7507-11e6-9336-f6b73439dec7.png)
I fill the "" and continue, nay, that doesn't help me much, again it tells me that type is AB, but I don't know that props are there esle there in the type "AB"
![image](https://cloud.githubusercontent.com/assets/736697/18307091/412a064c-7508-11e6-8786-e1e94e685a9d.png)

But there is an error I can mouse over on it and get that I'm lacking some "b"
![image](https://cloud.githubusercontent.com/assets/736697/18307163/9a184fac-7508-11e6-9454-01c8a9678221.png)

That solves some thing, but what if there is some not required "c" property on AB interface, I will never know about it, editor won't tell me.

So what is needed that while filling object type one could see helper with all the props on the type, something like that:

![image](https://cloud.githubusercontent.com/assets/736697/18307314/51e2b64a-7509-11e6-8cb3-88e7eb209b91.png)

Hope I was clear =)

**Comment by whitecolor** [comment]
It should be something like helper that we see in in tsconfig, when all options is shown:

![image](https://cloud.githubusercontent.com/assets/736697/18318779/732e3a30-753c-11e6-8df6-64e0318d584d.png)

And helper for each option:
![image](https://cloud.githubusercontent.com/assets/736697/18318814/8b39306c-753c-11e6-8cb3-5b6d5800b38b.png)

**Comment by whitecolor** [comment]
Again about this feature request:
![image](https://cloud.githubusercontent.com/assets/736697/18708563/f0a10960-8014-11e6-9df1-8bd173bbf4d3.png)

You see I'm need to fill the options, I see the type of options it expects (`ForageDriverOptions`) but have no clue what it is about. I think this is strange, maybe I'm doing something wrong?

**Comment by waderyan** [comment]
Very interesting. Thank you for the thorough explanation. This seems like a valid feature request. Moving to TS.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11045
