### ISSUE TITLE
Improve font options for SCM input

### ISSUE THREAD

**Issue by UncleClapton** [microsoft/vscode#114945]
Hello!

It seems there's no way to control `font-size` and `font-weight` for the SCM input widget, despite there being an option for `font-family`. When using my main editor font, this results in uncomfortably large text which is far from ideal. This also may be considered an accessibility issue since users who would prefer a certain font can't adjust it to maximize legibility.

If possible, I'd like to see these options added. Perhaps they could optionally mirror the editor settings similar to how `scm.inputFontFamily` does as well.

**Comment by krishnaanaril** [comment]
Hi @eamodio, How can I help? Are you working on this?

**Comment by eamodio** [comment]
I'm not, so feel free to jump in :smile:. I'd suggest following the `scm.inputFontFamily` setting and add a new one, say `scm.inputFontSize`. I'm not necessarily convinced we need more than the size (since we don't anywhere else except the editor). But I could have my mind changed :wink:

**Comment by krishnaanaril** [comment]
Okay, I'll try then :smiley:

**Comment by eamodio** [comment]
To verify:

- Ensure that both `scm.inputFontFamily` and `scm.inputFontSize` apply to both the placeholder text and the editor
- Ensure that changing `scm.inputFontSize` changes the line height (e.g. the input grows/shrinks) appropriately
- Ensure that the correct values of `scm.inputFontFamily` and `scm.inputFontSize` are applied on startup
