### ISSUE TITLE
window.reopenFolders: "none" not working in 1.4.0

### ISSUE THREAD

**Issue by rogerpence** [Microsoft/vscode#11499]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04.1

Steps to Reproduce:

1. Add to user settings (settings.json):  "window.reopenFolders": "none" 
2. Close VSCode.
3. Change directory to a project. Open VSCode with $ code .
4. It always opens with files previously opened for that project (including those in child folders)
5. Opening VS Code from Launcher opens VS Code without any files open. This issue seems to be caused by opening VS Code with "code ." in a project top-level folder.

**Comment by bpasero** [comment]
@rogerpence if you start with `code .` you override the setting. The setting only has an impact for when you run `code` without argument.

**Comment by rogerpence** [comment]
Thank you. I woulda sworn that wasn't the behavior before the last update or so. But it's not a big deal. VSCode is great. Very good job by everyone!
