### ISSUE TITLE
"Skip" in Getting Started should reset startup editor

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#114964]
_Getting Started_ will keep opening for each new project without any means of disabling it from the page itself. Similar to unchecking _Show welcome page on startup_ in _Welcome_, selecting _Skip_ in _Getting Started_ should reset the `startupEditor` setting to `none` (_Welcome_'s  checkbox resets startupEditor to `newUntitledFile`).

@misolori what are your thoughts? I wanted to double-check that these were your intention with the Skip button. We can also iterate on this to refine the opt-out experience; but this first step seems the easiest fix right now.

**Comment by misolori** [comment]
My thought was "skip" would go to the Welcome page and the user wouldn't see the get started again unless they manually reset it, since this is intended for new users anyways. I just saw the update where there is now a checkbox to keep it? What's the thinking there? Feels a bit confusing given the welcome page's "don't show again" checkbox

![image](https://user-images.githubusercontent.com/35271042/107801728-4d169b00-6d15-11eb-8860-bda4eefe9af6.png)

**Comment by JacksonKearl** [comment]
Added the checkbox based on user testing showing that folks are likely to just skip over the getting started on first run because they want to poke around themselves at first. With the checkbox it's an active decision to never see it again versus just "let me get on my with my life right now but I might look at this later".

**Comment by digitarald** [comment]
> Feels a bit confusing given the welcome page's "don't show again" checkbox

Agreed, the reversed pattern can be confusing. It also somewhat competes with Skip.

> My thought was "skip" would go to the Welcome page

I like this alternative – we had considered it. On further thought, users that skip quickly are probably also not beginners that would read the content later. Maybe a hint under _Skip_ button can point to re-opening that page via Help menu.

> With the checkbox it's an active decision to never see it again versus just "let me get on my with my life right now but I might look at this later".

Could you clarify? Doesn't the unchecked box make it an active decision to *keep seeing* the Getting Started page?

**Comment by JacksonKearl** [comment]
This is what the first launch would look like: 
![image](https://user-images.githubusercontent.com/8586769/107803493-83551a00-6d17-11eb-82bf-9e0010b5205b.png)
If you exit out or press skip here, the editor closes and nothing changes on next launch. If you uncheck the checkbox, next launch looks like this:
![image](https://user-images.githubusercontent.com/8586769/107803590-a384d900-6d17-11eb-9d47-7b810ed43922.png)
(current behaviour in stable)
Unchecking that then puts you into `newUntitledFile` startup editor.

**Comment by digitarald** [comment]
Thanks for clarifying, @JacksonKearl! My confusion stemmed from opening the page manually.

Maybe _Skip_ can be removed, as the tab can just be closed?

**Comment by JacksonKearl** [comment]
Yeah `Skip` can be removed, it doesn't do anything besides run the 'close tab' command. Though it does get registered as a telemetry event, which might be helpful to look at when testing out changes to the main page's content.

**Comment by JacksonKearl** [comment]
Actually we do have `"monacoworkbench/editorclosed"`, which includes the editor id closed, so we can remove skip without losing telemetry.

**Comment by misolori** [comment]
The original intention of this page was to only be shown for first time users and then transition into the welcome page, with content being brought over to the welcome page:

![image](https://user-images.githubusercontent.com/35271042/107805127-c0baa700-6d19-11eb-87f1-4bbadf40ef54.png)

The skip button essentially opens the welcome page.

**Comment by digitarald** [comment]
This a great progression and makes the content available after people opted out of the fullpage getting started. Would it make sense to revisit Skip when we merged the content into Welcome, so the 2 are linked together?

**Comment by misolori** [comment]
I don't think the Skip button ever got hooked up to work this way, which explains why it feels useless. In my mind I really didn't want to have two different welcome pages, the get started was just the friendlier way to transition users into the welcome page.

**Comment by JacksonKearl** [comment]
We could do that, it'd essentially be a css change in the getting started page. One thing @digitarald and I discussed was possibly tuning the Welcome page content to be exclusively content that was relevant to power users and the getting started to be content relevant to new users.

**Comment by misolori** [comment]
> One thing @digitarald and I discussed was possibly tuning the Welcome page content to be exclusively content that was relevant to power users and the getting started to be content relevant to new users.

👍  to this, and this is what extension authors have also asked for to have onboarding content for new/existing users

**Comment by JacksonKearl** [comment]
Verify presence of checkbox that resets startup editor to welcome page.
