### ISSUE TITLE
Test: Merged Web Menu and Web App Icon in Title Bar

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#114949]
https://github.com/microsoft/vscode/issues/112237

- [x] macOS @alexdima
- [x] windows @digitarald
- [x] linux @joaomoreno

Complexity: 2

Authors: @sbatten

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114949%0A%0A)

---

_Edit from @joaomoreno: This is about the `window.menuBarVisibility` setting on the **web**. Also, take this: https://vscode-web-test-playground.azurewebsites.net/?enter=true_

We removed the home indicator icon from the activity bar and merged the underlying menu with the recognizable hamburger menu in the activity bar. This is `compact` mode and the default on web.

If not using `compact` mode, the menu will appear in the title bar like it does on Windows Desktop. We have introduced the web app icon to the menu to act as a link to go home.

Please test in web: 
1. `compact` mode shows a single hamburger menu with both the app menu entries followed by the web contributed entries (such as Go Home)
2. The remaining `window.menuBarVisibility` options show the title bar as appropriate with an app icon and menu bar. The web menu entries are added to the file menu at the end. The `Go Home` entry is replaced by the app icon which acts as a link to go home.
3. Switching visibility works as expected.

**Comment by joaomoreno** [comment]
> 2\. The remaining `window.menuBarVisibility` options show the title bar as appropriate with an app icon and menu bar.

@sbatten  The `default`, `toggle` and `hidden` options do not show any title bar at all. Only `visible` does.

**Comment by joaomoreno** [comment]
@sbatten Should `default` be renamed? It seems that `compact` is the default for web. So calling it `default` is weird.

**Comment by sbatten** [comment]
@joaomoreno your comment is similar to one filed by @bpasero so I have updated that issue to encompass a reevaluation of the settings names/descriptions/behaviors for web
