### ISSUE TITLE
Missing shortcut on Getting Started's Run button

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#114975]
STR: Opened the Getting Started on Codespaces

![image](https://user-images.githubusercontent.com/8599/105802929-1c7ee500-5f51-11eb-820e-e59fa3eae86a.png)

Run Code has a few shortcuts, but none is showing up for this button. Showing F5 would be important for this one. I guess we need to change the command to make the shortcut work?

The min-width of 100px for buttons makes it look even more like a shortcut is missing. @JacksonKearl any idea why the min-width was added?

**Comment by JacksonKearl** [comment]
`F5` does not do what we want here, I'm running the command which will find a way to run the app even if no launch config is set up (`workbench.action.debug.selectandstart`), but `F5` only works if a launch config is already set up or the active editor can support running. The command I'm using has no default keybinding. It could be changed to `workbench.action.debug.start` aand it'd get the `F5` label back, but IMO the end user experience is much worse.

**Comment by JacksonKearl** [comment]
We could alternatively assign a default bind to the new action. I have it set to Shift+F5, for instance.

**Comment by digitarald** [comment]
Fixed by e48b3d3cad5bd538b1003425c1a49a73f8778c16, which adds the shortcut and removes the `min-width`.
