### ISSUE TITLE
Test: New GHPRI create pull request flow

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#114967]
Refs: https://github.com/microsoft/vscode-pull-request-github/issues/2293

- [x] macOS @bpasero
- [x] linux @isidorn
- [x] windows @JacksonKearl

Complexity: 5

Authors: @RMacfarlane, @eamodio 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114967%0A%0A)

---

**Please make sure you are using the nightly version of the [extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) and file issues in the [extension repo](https://github.com/Microsoft/vscode-pull-request-github)**

The GitHub Pull Requests and Issues extension has new UI for creating pull requests, making use of a webview in the activity bar. You should be able to:

- Start create from the "+" icon in the pull requests view
- Start create from the command palette items for "Create Pull Request" and "Create Draft Pull Request"
- Choose a different base branch or different remote if you have multiple remotes, and have the diff view update
- Be warned in the diff view if the current branch is not published, and be able to publish it from there
- Be warned if there is no commit difference between the current branch and your selection
- Be warned if you try to create with no title
- Change the `githubPullRequests.pullRequestTitle` and `githubPullRequests.pullRequestDescription` settings and see different default values for the title/description
- Have changes to fields preserved if you navigate away and back to the viewlet
- Select repo at beginning of create if you are in a multi-root workspace
- Cancel create and return to the pull request list
- Create a pull request and draft pull request successfully

Please make sure you are using the nightly version of the [extension](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github-insiders) and file issues in the [extension repo](https://github.com/Microsoft/vscode-pull-request-github)

**Comment by bpasero** [comment]
Fyi I wasted 30 minutes until I realised that I need to install the GH PR nightly extension.

**Comment by isidorn** [comment]
I am unable to move past the https://github.com/microsoft/vscode-pull-request-github/issues/2395 
So I was not able to successfuly finish testing this...

**Comment by isidorn** [comment]
After some tries I was able to move past the  microsoft/vscode-pull-request-github#2395 and now this seems to work, not sure what was the root cause...

**Comment by bpasero** [comment]
My speculation is that it could be related to wether the branch is pushed to the remote or not before creating the PR?

**Comment by isidorn** [comment]
I have pushed it to remote and it was not working. Maybe it needs a manual reload - which makes for a bad experience...

**Comment by isidorn** [comment]
I have assigned all the issues to @RMacfarlane, let me know if I should assign them to @eamodio as well (since only know I noticed that he is also listed as author). For now I leave that up to the authors.

In the end I could successfully do the scenario, thus checking my name off.
