### ISSUE TITLE
Oauth problems connecting to SF

### ISSUE THREAD

**Issue by jenny241093** [microsoft/vscode#114916]
Hello,

After I made a Windows update I am not able to Authorize an Org with VS Code through Salesforce extensions. Please find below the error:
![image](https://user-images.githubusercontent.com/24233318/105725269-6eb00e00-5f31-11eb-827c-ebc1222ee2bb.png)
And from VS Code:
 sfdx force:auth:web:login -a EV_ZACould not retrieve the username after successful auth code exchange in org: 00D2o000000ZUaYEAW.
Due to: Expected parsed JSON data to be an object

**Comment by kieferrm** [comment]
Please file the issue against the salesforce extension you use. The investigation needs to start there. Thank you!
