### ISSUE TITLE
ctrl+backspace doesn't work in the Python REPL on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114919]
Repro:

1. Open terminal
2. Type/paste "test test test"
3. Press ctrl+backspace

![image](https://user-images.githubusercontent.com/2193314/105728691-4bf60900-5ee1-11eb-8944-78d2427e516f.png)

Related: https://github.com/microsoft/vscode/issues/98404

**Comment by gvanrossum** [comment]
CC: @zooba

**Comment by zooba** [comment]
This seems to be exactly the same as #98404, and I assume is due to VS Code's use of pseudoterminals, as Ctrl+Backspace works fine in other console hosts.

**Comment by Tyriar** [comment]
Yeah it is the same, VT doesn't encode ctrl+backspace so we have to use custom keybindings to send other sequences to the shell. If there is something we could send to Python or cmd to reliably go back a word then we could add a builtin keybinding. That would make use of https://code.visualstudio.com/docs/editor/integrated-terminal#_send-text-via-a-keybinding

/duplicate
