### ISSUE TITLE
Autocomplete not working as expected

### ISSUE THREAD

**Issue by lejun** [Microsoft/vscode#11498]
- VSCode Version:1.4.0
- OS Version:mac os 10.11.5

Ready to work:
```
typings install --global --save dt~react
typings install --global --save dt~react-native
```
tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "es6",
        "jsx": "react",
        "outDir": "built",
        "rootDir": "src",
        "sourceMap": true,
        "noImplicitAny": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true
    },
    "filesGlob": [
        "typings/index.d.ts",
        "typings/globals/**/*.d.ts",
        "src/**/*.ts",
        "src/**/*.tsx"
    ],
    "exclude": [
        "node_modules",
        ".vscode/launchReactNative.js",
        "built",
        "index.android.js",
        "index.ios.js"
    ]
}
```

example:
1.
```js
import * as RN from 'react-native';
const{View,Text,Navigator} = RN;
```
<img width="625" alt="ok tips" src="https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png">

2.
```js
import {View,Text,Navigator} from 'react-native';
```
<img width="535" alt="error tips" src="https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png">

question:
###Why can normally prompt mode 1, and mode 2 not?

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
@lejun thank you for opening this issue. To make sure I understand correctly... you are asking why you are prompted to choose `Navigator` in screenshot 1 but not in screenshot 2?

https://cloud.githubusercontent.com/assets/4397814/18225933/1988820e-7232-11e6-9918-8bd5e7c4758b.png

https://cloud.githubusercontent.com/assets/4397814/18225941/35077792-7232-11e6-827b-16fcf31e2735.png

**Comment by waderyan** [comment]
I apologize for the spam. Strange issue on my end with the comment button.

**Comment by lejun** [comment]
Thank you for your reply.
The screenshot 1 is correctly.(react component)

**Comment by leaxoy** [comment]
+1

**Comment by preetb123** [comment]
@lejun how are you able to get autocomplete  for ReactNative components, as in the above fig.

**Comment by lejun** [comment]
@preetb123 
```ts
import * as RN from 'react-native';
const{View,Text,Navigator} = RN;
```

**Comment by waderyan** [comment]
@DanielRosenwasser can you advise me and OP on this issue? 

Is `Navigator` recommended in screenshot two simply because of the edit distance (`Navi` is closer to `Navigator` then `Nav` is) on the language service side.

**Comment by DanielRosenwasser** [comment]
I'm not totally sure why that happens. If VS Code only displays items as returned, and you're using our prefix logic, this might be a bug on us.

**Comment by waderyan** [comment]
I'll move this over then to have help investigating.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11253
