### ISSUE TITLE
Keyboard Shortcuts editor: distinguish deleted versus unset keybindings

### ISSUE THREAD

**Issue by xpe** [microsoft/vscode#114931]
## Context

Users can remove a keybinding.

## Problem 

In the Keyboard Shortcuts editor, removed keybindings are non-obvious. The editor only shows the *absense* of a shortcut.

<img width="1024" alt="Keyboard Shortcuts editor showing removed keybinding" src="https://user-images.githubusercontent.com/4576329/105744587-5af1b100-5f0b-11eb-9b48-1be792c0df8d.png">

## Discussion

* "If the keybinding is blank, why does VS Code show it at all?" Yes, **I** know the answer to this question, but only because I know how "keybindings.json" works. This is not intuitive to a new user of VS Code.

* "Maybe I'll just delete the row?" Everyone is new to something. Indeed, before I understood how "keybindings.json" worked, I deleted a row myself. 🤕 

## Suggestion

In such cases, I'd suggest:

* adding text saying "disabled" or "cleared" or "removed", and/or
* some graphic or symbol that conveys the same idea.

## Similar Issues

I ran these GitHub issue searches to look for similar issues:
1. ['clear keybinding Keyboard Shortcuts'][1]
2. ['delete keybinding Keyboard Shortcuts'][2]
3. ['remove keybinding Keyboard Shortcuts'][3]
4. ['unset keybinding Keyboard Shortcuts'][4]

Here are the closest somewhat related issues (but none convey what I'm going for in this feature request):

* Improve User Overrides for Keybindings #92601
* Improve settings editor accessibility #97567

[1]: https://github.com/microsoft/vscode/issues?q=clear+keybinding+Keyboard+Shortcuts
[2]: https://github.com/microsoft/vscode/issues?q=delete+keybinding+Keyboard+Shortcuts
[3]: https://github.com/microsoft/vscode/issues?q=remove+keybinding+Keyboard+Shortcuts
[4]: https://github.com/microsoft/vscode/issues?q=unset+keybinding+Keyboard+Shortcuts

**Comment by xpe** [comment]
Some more context: I understand and use the "keybindings.json" file, but I consider that outside the scope of my feature request here. My point here is to recommend improving the user experience of the Keyboard Shortcuts editor.

**Comment by sandy081** [comment]
At present. you can differentiate that by using the source column - If it is `User` then it is removed by user, if it is `Default` then it is unset.

**Comment by xpe** [comment]
> At present. you can differentiate that by using the source column - If it is `User` then it is removed by user, if it is `Default` then it is unset.

While this may be technically true, this is not a good end user experience. Nor should such a claim impede usability improvements.
