### ISSUE TITLE
Debugger requires path to program be correct casing for breakpoints to get hit

### ISSUE THREAD

**Issue by martellaj** [Microsoft/vscode#1149]
Assume there's a file `app.js` in directory `Foo`. If in my `launch.json` file, I specify `foo/app.js` as the `program`, the debugger will run, but none of my breakpoints will get hit. However, if I give it the actual casing of the path, `Foo/app.js`, the debugger runs and breakpoints will get hit.

I think it should be all or nothing here. As in, if correct casing is required for breakpoints to get hit, then correct casing should be required for the debugger to work at all. Or vice versa (and preferably), if correct casing isn't required to run the debugger, than correct casing shouldn't be required for breakpoints to get hit.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#26
