### ISSUE TITLE
find/replace hangs or loops

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#114939]
@taisbak commented on [Mon Jan 25 2021](https://github.com/microsoft/vscode-jupyter/issues/4477)

## Environment data

-   VS Code version: 1.53.0-insider (user setup)
-   Jupyter Extension version: 2020.12.414227025
-   Python Extension version: 2021.2.505054260-dev
-   OS: Micosoft Windows 10 Enterprise 10.0.18363 build 18363
-   Python and/or Anaconda version: 3.8 
-   Type of virtual environment used N/A
-   Jupyter server running: Local
## Expected behaviour

change sss to ss in string sss...sss...sss...sss should give ss...ss...ss...ss 

## Actual behaviour

never completes

## Steps to reproduce:

1. enter sss...sss...sss...sss in a notebook editor
2. use find/replace to find sss and replace with ss

---

@rchiodo commented on [Mon Jan 25 2021](https://github.com/microsoft/vscode-jupyter/issues/4477#issuecomment-767042509)

Thanks for the bug.

Searching and replacing in the insiders build is actually handled by VS code itself. I'll move your issue there.

**Comment by taisbak** [comment]
Thank you for the reply.

I thought so as well.

However, I only encountered the problem in connection with the Jupyter notebook extension, which also have undo/redo problems.

Another symptom: 
Sometimes find/replace doesn't loop, but uses the offsets found in the original string for replacements in the amended string.

Hope that provides some clues.

**Comment by rebornix** [comment]
I'm not able to reproduce this issue anymore.
