### ISSUE TITLE
Test rich diff editor for notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#114969]
Refs: https://github.com/microsoft/vscode/issues/112486

- [x] anyOS @jrieken
- [x] anyOS @Tyriar

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114969%0A%0A)

---

We added support for rendering outputs for notebook in the diff editor this iteration. To test this feature, you would need a bit of time setting things up but once that's done, you should be able to use it just like the normal text diff editor.

## Setup

* Install Jupyter extension from master
  * go to https://github.com/microsoft/vscode-jupyter/actions/runs/510651036#artifacts and download ms-toolsai-jupyter-insiders.vsix
* Install the extension from vsix
* If you don't want to mess up with python or jupyter
  * you can create a `.ipynb` file with following content  [plotly.txt](https://github.com/microsoft/vscode/files/5870534/plotly.txt)
  * open it in VS Code, which should be opened in notebook editor
* Or, if you already have Python installed, Jupyter can use it as a kernel, with which you don't need future customization
  * run command "create new blank jupyter notebook"
  * create a code cell with language Python, type in `!pip install plotly=4.5.2`, run the cell
  * create another code cell with following content, run the cell
  ```py
    import sys
    import plotly.graph_objects as go
    fig = go.Figure(
      data=[go.Bar(y=[2, 1, 3])], layout_title_text="A Figure Displayed with fig.show()"
    )   
    fig.show()
    ```
  * you should be able to see a graph

## Testing

Once you can open a jupyter notebook with rich outputs in VS Code, you can then use git command to change its state in order to see it in SCM viewlet, or you can duplicate the file and then compare them directly through file explorer

![image](https://user-images.githubusercontent.com/876920/105785873-c8640880-5f30-11eb-84d0-d1b8cae63c59.png)

A diff editor with document generated by above python code will look like below

![image](https://user-images.githubusercontent.com/876920/105785950-f0ec0280-5f30-11eb-992b-c9d90540c2f4.png)

Please test that:

* Rich outputs can be rendered in the diff editor
* If an output has multiple mimetypes, you can switch between mimetypes (for this you would need  [plotly.txt](https://github.com/microsoft/vscode/files/5870534/plotly.txt))
* You toggle the visibility of outputs
* You can choose to see the outputs' raw data
* Scrolling in the notebook diff editor with rich output rendered is reasonablly performant (no siganificant performance drop)

**Comment by jrieken** [comment]
This is equally cool as buggy
