### ISSUE TITLE
Renamed folder from upper to lowercase, both cases show up in search

### ISSUE THREAD

**Issue by joetex** [microsoft/vscode#114950]
Issue Type: <b>Bug</b>

1) Create project folder
2) Make project folder a git repo (might be unecessary)
3) Add folder into project folder with uppercase letter, i.e. "Test"
 a) Add file with some random text to search
4) Open project folder in VSCode
5) From VSCode, rename folder to "test" all lowercase
6) Do a global search in files for a piece of the random text 

You should see two results from the "Test" and "test" folder.

Here is an example from one of my projects with "Games" vs "games":
![image](https://user-images.githubusercontent.com/1610876/105759740-68606880-5f16-11eb-929d-0715782eb5ef.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.95GB free)|
|Process Argv|--crash-reporter-id 167cd315-07b7-4af0-8818-97d1f3855f12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.18.1
flutter|Dar|3.18.1
prettier-vscode|esb|5.8.0
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
typescript-javascript-grammar|ms-|0.0.55
vscode-react-native|msj|1.3.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry914:30244301
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30247033

```

</details>

**Comment by dragonDScript** [comment]
> Issue Type: Bug
> 
> 1. Create project folder
> 2. Make project folder a git repo (might be unecessary)
> 3. Add folder into project folder with uppercase letter, i.e. "Test"
>    a) Add file with some random text to search
> 4. Open project folder in VSCode
> 5. From VSCode, rename folder to "test" all lowercase
> 6. Do a global search in files for a piece of the random text
> 
> You should see two results from the "Test" and "test" folder.
> 
> Here is an example from one of my projects with "Games" vs "games":
> ![image](https://user-images.githubusercontent.com/1610876/105759740-68606880-5f16-11eb-929d-0715782eb5ef.png)
> 
> VS Code version: Code 1.52.1 ([ea3859d](https://github.com/microsoft/vscode/commit/ea3859d4ba2f3e577a159bc91e3074c5d85c0523), 2020-12-16T16:34:46.910Z)
> OS version: Windows_NT x64 10.0.19042
> 
> System Info
> Extensions (11)
> A/B Experiments

Have you tried to reload the window?

**Comment by joetex** [comment]
Huh, reloading worked, like this:
`Ctrl+Shift+P` -> `Developer: Reload Window`

I had tried closing/opening, but I guess that doesn't clear cache.  Thanks!

**Comment by dragonDScript** [comment]
Please close the issue!
