### ISSUE TITLE
"window.openFilesInNewWindow" doesn't work 

### ISSUE THREAD

**Issue by kevin1211** [Microsoft/vscode#11491]
- VSCode Version:1.4.0
- OS Version:OSX 10.11.6

"window.openFilesInNewWindow" doesn't work

**Comment by bpasero** [comment]
@kevin1211 what happens when you try?

**Comment by kevin1211** [comment]
i want to open file in a new tag , but it always opened in current tag 。

**Comment by bpasero** [comment]
@kevin1211 how do you open files? and what is your setting set to?

**Comment by kevin1211** [comment]
just click it ,
![qq20160906-0](https://cloud.githubusercontent.com/assets/13352521/18259603/5e7976ce-7418-11e6-9393-8fba8bbc917c.png)
for example, i click gulpfile.js and then i click jsconfig.json, gulpfile.js will be covered in the right workspace. i just want to open it in a new tag like this
![qq20160906-1](https://cloud.githubusercontent.com/assets/13352521/18259653/fce1f87c-7418-11e6-9f0d-7adfffe6d46a.png)

**Comment by bpasero** [comment]
@kevin1211 can you try with `"workbench.editor.enablePreview": false` ?

**Comment by kevin1211** [comment]
yes, it works.thank you very much .

**Comment by nocke** [comment]
**I suggest re-opening:**
I can confirm, with the workaround ( "workbench.editor.enablePreview": false ) indeed "window.openFilesInNewWindow" works as described. Without, it still does not. (Various projects, several laptops...)

A hack/workaround is not a fix.

> Version 1.17.0
> Shell 1.7.7
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64
> 
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> (Ubuntu-MATE)
