### ISSUE TITLE
Mac: Inconsistent dirty status and the Proxy Icon on tile bar is not draggable

### ISSUE THREAD

**Issue by sbarex** [microsoft/vscode#114951]
Issue Type: <b>Bug</b>

I'm on a mac (macOS 11.1 intel).
I have an editor window with opened some tabs.
If all files are saved I can drag the proxy icon on the title bar to drop the current file on other application. 

When I edit a file (without saving him) the Mac red semaphore on the title bar is set to the dirty status and the proxy icon is disabled and it cannot be dragged any more. This behaviour is correct for the unsaved file, but when I switch to the tab of another *saved* file the dirty status must be reset so that the proxy icon for this file is reenabled.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|1.1.2
code-gnu-global|aus|0.2.2
autolispext|Aut|1.3.2
spellright|ban|3.0.56
binary-plist|dni|0.4.0
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
go|gol|0.21.1
jsx|Hen|1.2.1
githd|hui|2.2.4
electron-debug|kod|18.11.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0-insiders2
bash-debug|rog|0.3.9
zsh-debug|rog|0.1.3
vscode-3dviewer|sle|0.2.2
vscode-lldb|vad|1.6.1

</details>

**Comment by bpasero** [comment]
I see this as well and assume that setting the window to "document edited" triggers this, which is provided by Electron but may well be standard macOS behaviour.

**Comment by sbarex** [comment]
Yes, I set `window.titleBarStyle: native` to show the proxy icon. But the dirty state it's not right also with the defaul settings.

**Comment by deepak1556** [comment]
Closing as issue is not actionable in the runtime.
