### ISSUE TITLE
Universal build uses x64 on M1 mac

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#114986]
Testing #114974

* download latest insiders
* start
* first start takes a very long time
* VS Code running x64, not ARM

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/1794099/105818921-c2653a80-5fb7-11eb-93a4-db6b1b4e06ac.png">

**Comment by jrieken** [comment]
This is maybe because it was running both variants of that machine already?

**Comment by deepak1556** [comment]
Was this after quitting all running instances of the app ? It will not pick up correct architecture if there is already a running instance for a particular architecture.

**Comment by jrieken** [comment]
Yeah, all instances quit and uninstalled

**Comment by deepak1556** [comment]
Can you open the `Info.plist` file under `Visual Studio Insiders.app/Contents` and add the following value https://developer.apple.com/documentation/bundleresources/information_property_list/lsarchitecturepriority with `arm64` as the first value in the array followed by `x86_64`

**Comment by deepak1556** [comment]
If it still doesn't pick up the correct architecture after the above, can you also add the boolean https://developer.apple.com/documentation/bundleresources/information_property_list/lsrequiresnativeexecution set to `true`

**Comment by jrieken** [comment]
Downloading fresh from the website and the `file` command shows this

```
jrieken@joh-13m1 Code % file ~/Downloads/Visual\ Studio\ Code\ -\ Insiders.app/Contents/MacOS/Electron 
/Users/jrieken/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron: Mach-O 64-bit executable x86_64
jrieken@joh-13m1 Code % 
```

**Comment by deepak1556** [comment]
@jrieken was it downloaded from https://az764295.vo.msecnd.net/insider/7b0cfdd04ad530a9c8d782c618afd79290be3d64/VSCode-darwin-universal.zip ?

I see the file has universal binaries.

**Comment by jrieken** [comment]
downloaded from here: https://code.visualstudio.com/insiders/.

**Comment by deepak1556** [comment]
Ah the website has not been updated yet to pull in unviersal https://github.com/microsoft/vscode-website/pull/924 , will be updated for the release. For testing you can download from the builds page.

**Comment by jrieken** [comment]
🤦 that explains it
