### ISSUE TITLE
Hex Editor 1.4.0 test item

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#114952]
Refs:https://github.com/microsoft/vscode-hexeditor
- [x] anyOS @gregvanl
- [x] anyOS @fiveisprime

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114952%0A%0A)

---
Use this VSIX (change from .zip to .vsix)
[hexeditor-1.4.0.zip](https://github.com/microsoft/vscode/files/5869519/hexeditor-1.4.0.zip)

Test general hex editor functionality. Ensure search, data inspector, and untitled files work as expected. 
See https://github.com/microsoft/vscode-hexeditor/blob/master/CHANGELOG.md for all the changes for the 1.4.0 release

**Comment by fiveisprime** [comment]
Looks good.
