### ISSUE TITLE
Add 'Go to Symbol' to the 'Go' menu

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11494]
The 'Go' menu currently includes `Go to Symbol...` but it doesn't include `Go to any symbol by name` and we should add it. 

To do so we should rename `Go>Go to Symbol` to `Go>Go to Symbol in File` and then add `Go>Go to Symbol in Workspace`

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/18229911/eb84d764-728a-11e6-9224-1a86cc93ee1f.png)
