### ISSUE TITLE
Test: Create issue directly from issue reporter

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#114963]
Refs: https://github.com/microsoft/vscode/issues/95165
- [x] macOS @ornellaalt
- [x] linux @chrmarti
- [x] windows @tanhakabir

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114963%0A%0A)

---

Previously, the issue reporter only allowed opening an issue as a preview on GitHub, instead of a direct create, which often ran into issues with url length limits. Now, if you have signed in with permissions that allow creating issues, we will use that auth information to directly create the issue on GitHub.

Please test that:
- if you are signed in using the `GitHub Pull Requests and Issues`, `GitHub Issues Notebook`, or other extension that uses GitHub auth and requests `repo` permissions, the submit button on the issue reporter reads "Create on GitHub"
- if you're not signed in, or are only signed into settings sync, the button remains "Preview on GitHub"

**Comment by yume-chan** [comment]
I see `Create on GitHub` while the text above still reads "You will be able to edit your issue and add screenshots when we preview it on GitHub."? Maybe should be like "you can edit the created issue to add screenshots" or something similar.

Or make this textarea a rich text editor so we can upload images here directly.

**Comment by RMacfarlane** [comment]
Thanks @yume-chan, that's a good point. I opened a new issue based on your comment. Right now there isn't a public API for uploading images to GitHub, but at the very least the text should change
