### ISSUE TITLE
Test onEnterRules that can be defined in `language-configuration.json`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#114948]
Test plan item for #114348

- [x] anyOS @dbaeumer 
- [x] anyOS @rzhao271

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23114948%0A%0A)

---

Please try to edit a `language-configuration.json` from one of our extensions (or make a new one if you really want to). Add some `onEnterRules`. 

e.g.
```
"onEnterRules": [
{
	"beforeText": "^\\s*(?:def|class|for|if|elif|else|while|try|with|finally|except|async).*?:\\s*$",
	"action": { "indent": "indent" }
}
]
```

Please also see that the JSON schema is working and that the object properties make sense.

**Comment by dbaeumer** [comment]
Tip. The regexp should look like this

```
	"onEnterRules": [
		{
			"beforeText": "^\\s*(?:def|class|for|if|elif|else|while|try|with|finally|except|async).*\\s*$",
			"action": { "indent": "indent" }
		}
	]

```
