### ISSUE TITLE
Big Sur unsaved changes dialog

### ISSUE THREAD

**Issue by lukepighetti** [microsoft/vscode#114911]
- VSCode Version:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

- OS Version: 11.1 (20C69)

Steps to Reproduce:

1. Have a file with unsaved changes
2. Stash the file

Does this issue occur when all extensions are disabled?: Yes/No
N/A

There is now this really jarring dialog when you try to stash a file with unsaved changes. Is this upstream in Big Sur or is this a stylistic change that can be reverted?

<img width="1449" alt="Screen Shot 2021-01-25 at 9 17 22 AM" src="https://user-images.githubusercontent.com/666539/105717805-903bd600-5eee-11eb-8d72-d673251a9704.png">

**Comment by gjsjohnmurray** [comment]
See #87938, for which the fix appeared in the November 2020 release.

/cc @joaomoreno

**Comment by lukepighetti** [comment]
Warn before stash makes sense, this issue covers the UX change of showing a Big Sur modal dialog instead of a command palette confirmation step.

**Comment by lukepighetti** [comment]
Upon reflection, it's entirely possible that this wasn't a command palette confirmation step previously, and that I have confused the Catalina => Big Sur save modal change for a change in VSCode.

**Comment by joaomoreno** [comment]
Yeah this is just how Big Sur shows modal dialogs, unfortunately. Can't do much here. 😢

**Comment by lukepighetti** [comment]
No problem, thanks!
