### ISSUE TITLE
Data brekapoints: support setting conditions and hit conditions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#114903]
This should behave just like the function breakpoints.

I would add this if there are debug adapters that would profit from this. So please comment if you are interested in this and what debugger you are using.

**Comment by yannickowow** [comment]
Hi
I am currently working on a debug adapter which uses GDB.
For this specific debugger, DataBreakpoints (or watchpoint) can have multiple attributes, such as 

- Hardware (-h)
- Temporary (-t)
- **condition (-c)**
- **Ignore Count (-i)**...
(for reference: https://sourceware.org/gdb/current/onlinedocs/gdb/GDB_002fMI-Breakpoint-Commands.html)

For the two first ones, it does not match DAP, so it is not really a concern.
For the two last ones, I think it can be useful to customize this arguments the same way as FunctionBreakpoint. 

Thanks in advance @isidorn !

**Comment by yannickowow** [comment]
Hi,
Do you think it will be adequate to add the possibility to update a Data Breakpoint `accessType` on this feature request ?

**Comment by isidorn** [comment]
@yannickowow I think it should be better to have that as a seperate feature request. My personal preference is to have smaller specific feature requests

**Comment by isidorn** [comment]
This should work now, thus closing
