### ISSUE TITLE
UI State: SCM repos view is not syncing properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#114995]
Since a long time I see the SCM repos view not showing up after enabling settings sync.

Steps to Reproduce:

1. open a multi root workspace with folders that each have git repo
2. open changes view
3. enable SCM repos view
4. you should see all git repos in a list to the top
5. enable settings sync
6. let it sync up
7. open a new instance with fresh user data dir and open the same workspace
8. enable sync and notice how in SCM view the multi repo view does not appear

![image](https://user-images.githubusercontent.com/900690/105826299-e24d2c00-5fc0-11eb-9d13-3308cecd1b38.png)

**Comment by sandy081** [comment]
This is expected because this view is workspace specific view and we do not sync workspace state yet.

**Comment by bpasero** [comment]
@joaomoreno is this something you picked intentionally? or is this true for all views

**Comment by joaomoreno** [comment]
I believe it was a purposeful decision. Whether you'd like to see that view sorta depends on whether you have opened a workspace which may have many repos.
