### ISSUE TITLE
Popups blocking text selection

### ISSUE THREAD

**Issue by Media-Evil** [microsoft/vscode#114938]
Issue Type: <b>Bug</b>

Create an .mjs-file, declare a variable, like this:

```js
 let  { foo } = bar;
```
Then try to select `foo` via mouse cursor. As soon as you hower over it, the popup will show up, making it impossible to select the desired portion of text. SUPER ANNOYING!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.1.3
html-in-template-string|enh|0.0.4

</details>

**Comment by gjsjohnmurray** [comment]
Maybe dup of #112391. Can you test with Insiders?

**Comment by Media-Evil** [comment]
I can't test with insiders bor a couple of reasons, but I confirm that this issue is a dup of the following:

#112391
#112627
#113172
#112813
#113330
#113456

**Comment by gjsjohnmurray** [comment]
/duplicate and is fixed in 1.53 which is expected to release as Stable this coming week.
