### ISSUE TITLE
Test doesn't work error shows error color but hover icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#114928]
![image](https://user-images.githubusercontent.com/2193314/105740611-35a27a00-5eee-11eb-8108-8ba90d5aa1e9.png)
![image](https://user-images.githubusercontent.com/2193314/105740641-39ce9780-5eee-11eb-8981-69eb0a5045c3.png)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-codicons/issues/34
