### ISSUE TITLE
Odd code in vscode/src/vs/editor/common/modes/lineStream.ts

### ISSUE THREAD

**Issue by keithn** [Microsoft/vscode#115]
private actualStringToArray(str:string):boolean[] {
		var maxCharCode = 0;
		for (var i = 0; i < str.length; i++) {
			maxCharCode = str.charCodeAt(i);
		}
		var r = [];
		for (i = 0; i < maxCharCode; i++) {
			r[i] = false;
		}
		for (i = 0; i < str.length; i++) {
			r[str.charCodeAt(i)] = true;
		}
		return r;
	}

is the first loop supposed to find the largest Char code?  at the moment it will just return the the last character in str.

**Comment by alexandrudima** [comment]
Thank you for spotting this! :+1:
