### ISSUE TITLE
'postbuild' and 'prebuild' scripts are missing from hints for ASP.NET project.json

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#1150]
For some reason the `postbuild` and `prebuild` scripts are missing from hints shown for `project.json` in editor:
![20151209223221](https://cloud.githubusercontent.com/assets/14539/11700668/811a0248-9ecb-11e5-94d1-dd717954c992.jpg)
The same `prebuild` script in Atom:
![20151209223109](https://cloud.githubusercontent.com/assets/14539/11700669/812195c6-9ecb-11e5-984d-589c3ca9c1f8.jpg)

The current schema:
http://json.schemastore.org/project

I cannot yet trace where there is a provider of that content. I've only found that current provider also seems to be missing that properties:
https://github.com/Microsoft/vscode/blob/468635529ed0e10f1aeffee31ee2327e76051b05/src/vs/editor/browser/standalone/standaloneSchemas.ts#L391-L405

Thanks!

VSCode: 10.3
OS X: 10.10

**Comment by egamma** [comment]
@aeschli let's update the schema for December.

**Comment by aeschli** [comment]
This got fixes in the latest. We now always load the latest schema from http://json.schemastore.org/project (before it was cached)

**Comment by peterblazejewicz** [comment]
Thanks!
