### ISSUE TITLE
Go to definition not working

### ISSUE THREAD

**Issue by locdiep** [microsoft/vscode#115061]
Issue Type: <b>Bug</b>

I don't know why the go to definition does not work for everything (I use C/C++).

"Go to definition" was working yesterday, but suddenly stop working.

I added all necessary include paths:
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${env:IDF_PATH}/components/freertos/include",
                "${env:IDF_PATH}/components/driver/include",
                "${env:IDF_PATH}/components/esp_wifi/include",
                // and more ...
            ],
            "defines": [],
            "compilerPath": "${env:ESP_PATH}/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
```

I tried to open my project in another computer using Ubuntu 20.04 and I see the same issue (I use 2 computers for my project and "go to definition" worked perfectly until yesterday). I followed the answer on this [link](https://stackoverflow.com/questions/37341849/vscode-go-to-definition-not-working) by adding `fs.inotify.max_user_watches=524288` to the end of the file `/etc/sysctl.conf` and it worked! But my Macbook seems does not have that file.

I tried to disable all extensions or reinstall VSCode but it still not working.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.02GB free)|
|Process Argv|-psn_0_2126343 --crash-reporter-id ed37316e-bb6c-45ce-a9f7-862b6c003331|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.38.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0-insiders2
vscode-icons|vsc|11.1.0
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details>

**Comment by locdiep** [comment]
<img width="856" alt="issue" src="https://user-images.githubusercontent.com/19490612/105863810-dc3c6700-6023-11eb-896d-0391d4c22f37.png">

**Comment by locdiep** [comment]
For example:
<img width="841" alt="Screen Shot 2021-01-26 at 22 13 38" src="https://user-images.githubusercontent.com/19490612/105863964-03933400-6024-11eb-954f-4569da553b97.png">

**Comment by jrieken** [comment]
\extCpp
