### ISSUE TITLE
Large Files "Auto Expand" all collapsed Functions/Regions

### ISSUE THREAD

**Issue by Kirchesch** [microsoft/vscode#115025]
- VSCode Version: Latest
- OS Version: Latest

Steps to Reproduce:

1. Open a large file that is fully collapsed
2. Wait about 5 seconds and every region/function will be expanded

Does this issue occur when all extensions are disabled?: Yes

 It seem to happen when vs code is under heavy load, for some reason instead of waiting, it is just giving up, cleaning its own memory idk how it works, but it should wait and not screw all the dev work on the organization

**Comment by aeschli** [comment]
For what language is that?

**Comment by Kirchesch** [comment]
Sorry i had no idea i got an answer, it is for C++, it happens when intellisense is updating and i edit the current open file or open a new file, the work arround is go really slow everytime i change the header, or am opening a new file

**Comment by aeschli** [comment]
Can you file the issue against C++? https://github.com/microsoft/vscode-cpptools

When an editor is closed, we remember the folded ranges for that file. When the file is opened again, we reapply the folded ranges while send a request to the folding provider of the language extension.
If the folding provider doesn't respond for 30 seconds, we fall back to indentation based folding.
But from your description it rather seems the c++ extension responds but with less ranges. FYI @Colengms
