### ISSUE TITLE
Randomly starts highlighting errors that are not present. Reboot helps.

### ISSUE THREAD

**Issue by ulitiy** [Microsoft/vscode#11501]
- VSCode Version: 1.4.0
- OS Version: 10.11.2

Steps to Reproduce:

1. Do random things
2. It just occurs.

**Comment by dbaeumer** [comment]
@ulitiy can you provide more information about what is not working. Which language are you programming in. Can you provide a screen shot or a github URL we can clone to reproduce this?

**Comment by ulitiy** [comment]
It's typescript. In webpack/tsc it works well without errors but VSC underlines errors that are not present. I have to restart the editor to make these errors disappear. It's primarily about lacking some Phaser dependency from typings.json. I'll try to record a video with this behavior.

**Comment by dbaeumer** [comment]
Have you configured VS Code to use the typescript in your local folder. I am sure it is a version mismatch WEbpack using TS 2.0 (which is not official yet) and VS Code still using the official 1.8.19. See also: https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions

**Comment by ulitiy** [comment]
https://drive.google.com/file/d/0B-4e-jj1-69ZaGtMM0VESzdqSUE/view?usp=sharing
I've made this screen recording demonstrating the problem. Also the latest NPM version is 1.8.10, not 1.8.19.

**Comment by ulitiy** [comment]
https://drive.google.com/file/d/0B-4e-jj1-69ZS1pIM0lMV29pSms/view?usp=sharing

I've made this short screen recording to show the bug...

**Comment by waderyan** [comment]
@ulitiy thank you for opening this issue and for making the helpful video. Can you share a snapshot of your code so I can try and recreate what you had? 

@dbaeumer the video is worth a watch. It is strange behavior to see `Phasor` marked as an error and then it resolves when he runs `webpack`. Any idea why that would occur?

**Comment by dbaeumer** [comment]
@waderyan I am not very familiar with webpack but what I heard is that they merge/copy/compile files from various source into one location. So I assume that webpack will produce some d.ts or ts files in a location which VS Code / tsserver picks them up from making the error disappear (we listen to file events and react to them. The tsserver for example adds new files to the project if the belong to the project scope)

**Comment by waderyan** [comment]
Closing until a small code sample is provided per this [comment](https://github.com/Microsoft/vscode/issues/11501#issuecomment-245094751).
