### ISSUE TITLE
Empty test explorer view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#115007]
Testing #114932

If the test provider does not provide workspace hierarchy then the test explorer is shown empty.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/10746682/105833425-71f6d880-5fc9-11eb-8e22-2739e67c9466.png">

There shall be at least a message and actions shall be disabled.

**Comment by connor4312** [comment]
This will now be shown if there are no workspace providers, or if the providers do not discover any tests (they have a root test item with no children)

**Comment by jrieken** [comment]
>  the providers do not discover any tests (they have a root test item with no children)

I have that and think it is misleading to send users to the market place. There should be a differentiation between having test extension installed and having one which isn't returning results

<img width="345" alt="Screenshot 2021-02-23 at 15 42 54" src="https://user-images.githubusercontent.com/1794099/108859735-ceabda00-75ed-11eb-9df5-b03749af08cc.png">

**Comment by connor4312** [comment]
I think it's still appropriate to show this text, as there might be test providers registered but they're not the right ones for the workspace.

However I've made a change to allow extensions to contribute text here via the standard `viewsWelcome` contribution. They can use that and context keys to display better help text as appropriate.

```

  "contributes": {
    "viewsWelcome": [
      {
        "view": "testing",
        "contents": "Hello world!"
      }
    ]
  },
```

**Comment by misolori** [comment]
Verified

<img width="500" src="https://user-images.githubusercontent.com/35271042/116464751-33b7c200-a821-11eb-91c7-26e4d12778c2.png">
