### ISSUE TITLE
Warning: Duplicate definition of module 'xyz'

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115013]
Testing #114969

While testing I have noticed these errors. That usually hints to a bundling problem, e.g some modules have been bundled multiple times

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1794099/105834658-0c0b5080-5fcb-11eb-96bf-f5ce9b487502.png">

**Comment by rebornix** [comment]
Call stack of the first warning I'm seeing 

```
s.defineModule	@	loader.js:1337
p	@	loader.js:1797
(anonymous)	@	fake:8
(anonymous)	@	fake:1
s.load	@	loader.js:693
s.load	@	loader.js:607
m	@	loader.js:1606
s._loadModule	@	loader.js:1618
s._resolve	@	loader.js:1703
s.defineModule	@	loader.js:1350
l	@	loader.js:1822
(anonymous)	@	simpleWorker.ts:373
initialize	@	simpleWorker.ts:371
_handleMessage	@	simpleWorker.ts:322
handleMessage	@	simpleWorker.ts:312
_handleMessage	@	simpleWorker.ts:140
handleMessage	@	simpleWorker.ts:108
onmessage	@	simpleWorker.ts:317
self.onmessage	@	workerMain.ts:34
(anonymous)	@	workerMain.ts:36
setTimeout (async)		
(anonymous)	@	workerMain.ts:29
s._safeInvokeFunction	@	loader.js:1089
s._invokeFactory	@	loader.js:1108
s.complete	@	loader.js:1121
s._onModuleComplete	@	loader.js:1747
s._resolve	@	loader.js:1707
s.defineModule	@	loader.js:1350
l	@	loader.js:1822
P	@	workerMain.ts:28
self.onmessage	@	workerMain.ts:51
```

@alexdima any idea what could possibly go wrong of how I use simple worker?

**Comment by alexdima** [comment]
@rebornix I'm not sure where to look. Where do you bundle the worker? What steps do you do in vscode to load the worker? I haven't seen this when just opening a notebook.

**Comment by rebornix** [comment]
I'm no longer seeing this error anymore. Closing it for now. Feel free to reopen if it still occurs.
