### ISSUE TITLE
Breadcrumbs is not very intuitive in notebooks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115097]
Testing #114969

The breadcrumbs seem to just name the nodes after the first line in the notebook which doesn't seem very useful. Is there some way we could derive a name in a smarter way? At the very least I think `Cell #1 - <first line>` would be more useful as it tells you where in the document you are.

![image](https://user-images.githubusercontent.com/2193314/105879666-4ec32d80-5fb7-11eb-8211-c2a4cb508f6c.png)

**Comment by jrieken** [comment]
@Tyriar there is an option to hide code cells for this exact reason

**Comment by jrieken** [comment]
Close because code cell are now filtered by default.
