### ISSUE TITLE
Notebooks +Code/+Markdown is distracting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115078]
Testing #114969

It keeps showing and displaying when you move the cursor vertically

![recording (34)](https://user-images.githubusercontent.com/2193314/105874508-7911ec80-5fb1-11eb-95d4-692a81484191.gif)

![recording (35)](https://user-images.githubusercontent.com/2193314/105874626-a52d6d80-5fb1-11eb-904e-016755e02e24.gif)

Can we improve this somehow? Some thoughts:

- Only show after a timeout has happened (reset on cursor move?)
- Show all the time at lower opacity, only setting to `opacity: 1` when the cursor is over it?

**Comment by misolori** [comment]
I think this is a bug when hovering over the output, the buttons should always be visible when hovering over the entire cell.

**Comment by Tyriar** [comment]
@misolori it also shows when the panel is being hovered.

**Comment by misolori** [comment]
> it also shows when the panel is being hovered.

oh right, this the other state where you have an active cell selected and your cursors moves away from the editor.

**Comment by Tyriar** [comment]
I'd expect that to be the same as the mouse hovering within the notebook but outside the cell though.

**Comment by misolori** [comment]
@Tyriar not sure what you mean? When you hover a cell those buttons always appear.

**Comment by Tyriar** [comment]
@misolori hovering the green part is where it shows now:

![image](https://user-images.githubusercontent.com/2193314/105996807-af0daa00-605f-11eb-898c-31c1d84d2305.png)

I think we both agree that it not showing when hovering the webview is a bug, but I think it should look like this:

![image](https://user-images.githubusercontent.com/2193314/105997177-280d0180-6060-11eb-86b1-727c56fa9718.png)

If hovering outside the cell within the notebook hides it, hovering outside the notebook should as well because that's even more "unfocused".

**Comment by misolori** [comment]
> If hovering outside the cell within the notebook hides it, hovering outside the notebook should as well because that's even more "unfocused".

Hovering outside the cell doesn't hide it you are just hovering over a different cell and that's where it is being shown it's just not visible. The logic goes:

- If mouse is inside of the editor/notebook, show actions (run, cell toolbar, +Code/+Markdown) for the hovered cell
- If mouse is outside of the editor/notebook, show actions for the focused cell

**Comment by Tyriar** [comment]
Why do we hide the focused cell buttons at all then? It's the flickering the moving your mouse around that bothers me.

**Comment by misolori** [comment]
We only want to show one set of actions, we got feedback that it was too noisy when you have more than one set of actions and can be confusing on which cell is the focused one as the focus border wasn't enough of an indicator.

**Comment by rebornix** [comment]
We increased the delay of showing the insert toolbar and also added setting to hide it.
