### ISSUE TITLE
Notebook icon problems

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115094]
Testing #114969

Maybe this belongs to the Jupyter extension?

- Export as and open jupyter variable view looks really bad on standard dpi
- Not enough contrast on the green icons, we shouldn't be using color at all yet blue, green and red are used

![image](https://user-images.githubusercontent.com/2193314/105877963-65688500-5fb5-11eb-80f3-1ea2761d099e.png)

- Run cell and below and run cells above do not show up initially, you need to focus another cell to get it to show up

![image](https://user-images.githubusercontent.com/2193314/105878217-a3fe3f80-5fb5-11eb-8235-34e08a4edb7f.png)

- Trusted is red initially and then it turns green when opening - this should be green from the beginning to reduce visual noise

**Comment by misolori** [comment]
Yea, this is from the Jupyter/Python extension. Will move this over.

**Comment by Tyriar** [comment]
@misolori @rebornix this one may be in core?

> Run cell and below and run cells above do not show up initially, you need to focus another cell to get it to show up

**Comment by misolori** [comment]
That's also from the extension, but this is expected behavior as it requires a selection to run. We have similar actions in the GH Issues notebook for splitting cells that only shows up when you're in a code cell.
