### ISSUE TITLE
Universal build: Missing indicator in Issue Reporter details

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#115051]
Issue Type: <b>Bug</b>

https://github.com/microsoft/vscode/issues/114974

The following does not indicate that this is from the universal Mac build:

VS Code version: Code - Insiders 1.53.0-insider (1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, 2021-01-26T05:12:23.287Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.39-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 7aad610c-0e6b-48aa-ba87-b704b1b543cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost:2223|
|OS|Linux x64 5.4.39-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (2.11GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
persona|chr|0.0.3
regex|chr|0.2.0
vscode-eslint|dba|2.1.14
ghlink|dt|1.2.0
remotehub|eam|0.5.0
tsl-problem-matcher|eam|0.3.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
codespaces|Git|0.6.0
vscode-pull-request-github|Git|0.22.0
vscode-mocha-test-adapter|hbe|2.9.1
vscode-test-explorer|hbe|2.19.5
rest-client|hum|0.24.4
graphql-for-vscode|kum|1.15.3
template-string-converter|meg|0.4.7
git-graph|mhu|1.28.0
vscode-azureappservice|ms-|0.20.0
vscode-docker|ms-|1.9.1
vscode-kubernetes-tools|ms-|1.2.3
remote-containers|ms-|0.156.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.1
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
hexeditor|ms-|1.3.0
vscode-github-issue-notebooks|ms-|0.0.60
debugger-for-chrome|msj|4.12.11
vscode-versionlens|pfl|1.0.9
vscode-yaml|red|0.14.0
music-time|sof|2.1.0
vscode-open-in-github|sys|1.14.0
vscodeintellicode|Vis|1.2.10
vscode-test-resolver|vsc|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
vstes516:30244333
pythonvspyt600:30247031
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by deepak1556** [comment]
To verify. check if the universal apps version information in about dialog as well as issue reporter details have it like `1.53.0-insider (Universal)`

<img width="564" alt="Screen Shot 2021-01-27 at 8 32 54 PM" src="https://user-images.githubusercontent.com/964386/106112126-ba191680-6101-11eb-895f-a841a8ddee34.png">
