### ISSUE TITLE
VSCode opening several windows on MacOS with the command "code".

### ISSUE THREAD

**Issue by juniorbotelho** [microsoft/vscode#115060]
Bug report

- VSCode Version: 1.52.1
- OS Version: MacOS 11.1 Big Sur

### VSCode opening several windows on MacOS with the command "code"
Whenever I try to run Visual Studio Code through the "code" environment variable, it ends up opening several windows at once and forcing me to close one by one, I have already done some research to try and solve it and I found nothing, I hope that developers solve this problem.

Steps to Reproduce:

1. Open the terminal or even Spotlight and execute the command "code".
2. Once loaded, several VS Code windows will open at once, and you must close them one by one.

Does this issue occur when all extensions are disabled?: Yes

Edit:
- This is true for both standard MacOS bash and Zsh.
- Even with extensions disabled, the problem occurs.
- I am reporting the problem now, but it has been going on for a long time, I even restored my MAC thinking that the problem was with him.

### Screenshots (GIF):
![Alt Text](https://media.giphy.com/media/aw5nTKRCAjJtzcjycT/giphy.gif)

**Comment by bpasero** [comment]
@juniorbotelho are those windows "Untitled" workspaces?

**Comment by juniorbotelho** [comment]
@bpasero Yes, all windows are "Untitled" workspaces.

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file

**Comment by juniorbotelho** [comment]
How can this be considered normal?
I didn't run multiple workspaces, even until I close the only workspace I work on to run later, and even then it happens.

**Comment by bpasero** [comment]
It is easy to get into a state of accumulating untitled workspaces if you are simply adding or removing folders in a non-multi-root instance. We enforce to restore untitled workspaces because they may contain user data (e.g. workspace settings) that we cannot simply delete. To delete an untitled workspace you can close it's window and you will be asked to save or discard.

**Comment by juniorbotelho** [comment]
@bpasero Now I understand how it works, thank you very much.
