### ISSUE TITLE
List all context keys in "default keyboard shortcuts"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11509]
I don't see a list of them documented anywhere, so it might be helpful to list them at the bottom of the default keyboard shortcuts page, like the commands are. See #9988

**Comment by gregvanl** [comment]
Are you looking for something different than https://vscode-westeu.azurewebsites.net/docs/customization/keybindings#_when-clause-contexts
There is also an open issue to provide the when clause contexts in keybindings.json IntelliSense. https://github.com/Microsoft/vscode/issues/9303

**Comment by roblourens** [comment]
Yeah actually I think that between those two, this isn't really needed.
