### ISSUE TITLE
Terminal shakes while magnifier turned on

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#115021]
Refs: https://github.com/microsoft/vscode/issues/112490

Windows, turn on Windows Magnifier, make sure you have the Magnifier View Docked (under magnifier settings)

1. Open a terminal, start typing, notice how the docked magnifier shakes left and right making it very hard to see what is going on while typing
2. Now type in the editor, notice how the magnifier shakes considarably less

**Comment by isidorn** [comment]
This works well with the ZoomText magnifier software. So there might be an issue with the Winodws Magnifier. I am trying to connect with the Magnifier team and will let you know if I have updates.

**Comment by Tyriar** [comment]
I'm not seeing a difference between the terminal and editor?

**Comment by isidorn** [comment]
It might be due to the fact that I use a VM, but here's what I am seeing (hopefully that helps) - shaking is from left to right, and the gif partially captures it, in reality it is a bit worse

![recording (3)](https://user-images.githubusercontent.com/1926584/105874838-5efdfb80-5ffd-11eb-8b47-e6c33d6757b3.gif)

**Comment by Tyriar** [comment]
My magnifier is quite different, it zooms the entire screen. Maybe this was fixed in the magnifier in a later version of Windows 10? I'm on 20H2 (19042)

![recording (43)](https://user-images.githubusercontent.com/2193314/105885571-2985ed80-5fbe-11eb-8cf5-6c6d98c76038.gif)

**Comment by isidorn** [comment]
@Tyriar check the first sentence of my first comment
" Windows, turn on Windows Magnifier, make sure you have the Magnifier View Docked (under magnifier settings)"

So can you check if you can Dock the Magnifier view under the settings?

I also might be on a older windows version...

**Comment by Tyriar** [comment]
Opps 😅 

Works fine here though, I checked all terminal renderers:

![recording (44)](https://user-images.githubusercontent.com/2193314/105886335-24756e00-5fbf-11eb-99a2-d275063827a6.gif)

**Comment by isidorn** [comment]
Let's close now, maybe the later versions of Windows have fixed it, and maybe my VM is causing this.

Sorry for the false alarm.
