### ISSUE TITLE
Tab wrap - flicker when there is not enough room for wrapping tabs to display

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#115050]
Testing #114827

- Create multiple editor groups
- Ensure that the selected tab is not the first one in the editor group
- Start dragging the sash so that there is not enough room to wrap tabs
- Notice how the name of the tab that is visible jitters as it switches between the name of the first tab, and the name of the selected tab

![recording (1)](https://user-images.githubusercontent.com/3372902/105855753-b645a100-5fe8-11eb-9bde-8a99d4c5d18b.gif)

**Comment by bpasero** [comment]
Yeah I was not able to figure out what triggers this and was even suspecting a browser bug (though didn't follow up).

//cc @SneakyFish5

**Comment by bpasero** [comment]
I see this being related to:
* `layout` is called
* we enable wrapping
* we disable wrapping right after because we figure out the space is too limited
* somehow the scrollbar is now in a bad spot and needs a proper reset to avoid flicker

**Comment by goldst** [comment]
I was able to find the origin of the bug in `doLayoutTabsWrapping`: wrapping is activated even when there is no space due to the actions right to the last tab. In the next call, it is disabled again, because the action's size is considered in that case. I'll make a PR.

**Comment by bpasero** [comment]
@goldst 👏
