### ISSUE TITLE
Javascript Intellisense not working

### ISSUE THREAD

**Issue by webglider** [Microsoft/vscode#11505]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 14.04

I followed all the instructions on the Intellisense for JS setup page. I have a project folder which contains the following jsconfig.json file:
`{
	"compilerOptions": {
		"target": "ES5"
	},
	"exclude": [
		"node_modules"
	]
}`

Also installed typings and dt~node (with --global) using it in my project directory.
Now when I try to edit a js file in my project folder, IntelliSense does not work, not even simple autocomplete. If I try to trigger it using Ctrl + Space, a box with text "Loading..." appears and stays like that forever. 
When I edit files outside my project directory individually, autocomplete works fine. (tried both HTML and JS files).

I also set the tssserver output option to verbose and checked the output window. This is the output after a few attempts at using Intellisense:

> Sending request: open (0). Response expected: no. Current queue length: 0
> Arguments: {
>     "file": "/home/midhul/jsws/dump/test.js",
>     "fileContent": "console."
> }
> 
> Sending request: geterr (1). Response expected: no. Current queue length: 0
> Arguments: {
>     "delay": 0,
>     "files": [
>         "/home/midhul/jsws/dump/test.js"
>     ]
> }
> 
> Sending request: projectInfo (2). Response expected: yes. Current queue length: 0
> Arguments: {
>     "file": "/home/midhul/jsws/dump/test.js",
>     "needFileNameList": true
> }
> 
> TypeScript Service: canceled request with sequence number 4
> TypeScript Service: canceled request with sequence number 16
> TypeScript Service: canceled request with sequence number 18
> TypeScript Service: canceled request with sequence number 20
> TypeScript Service: canceled request with sequence number 22
> TypeScript Service: canceled request with sequence number 24
> TypeScript Service: canceled request with sequence number 26
> TypeScript Service: canceled request with sequence number 28
> TypeScript Service: canceled request with sequence number 39
> TypeScript Service: canceled request with sequence number 50
> TypeScript Service: canceled request with sequence number 52
> TypeScript Service: canceled request with sequence number 68
> TypeScript Service: canceled request with sequence number 83
> TypeScript Service: canceled request with sequence number 116
> TypeScript Service: canceled request with sequence number 118
> TypeScript Service: canceled request with sequence number 120
> TypeScript Service: canceled request with sequence number 122
> TypeScript Service: canceled request with sequence number 124
> TypeScript Service: canceled request with sequence number 126
> TypeScript Service: canceled request with sequence number 128
> TypeScript Service: canceled request with sequence number 139
> TypeScript Service: canceled request with sequence number 146
> TypeScript Service: canceled request with sequence number 149
> TypeScript Service: canceled request with sequence number 152
> TypeScript Service: canceled request with sequence number 157
> TypeScript Service: canceled request with sequence number 170
> TypeScript Service: canceled request with sequence number 172
> TypeScript Service: canceled request with sequence number 187
> TypeScript Service: canceled request with sequence number 197
> TypeScript Service: canceled request with sequence number 199
> TypeScript Service: canceled request with sequence number 200

**Comment by webglider** [comment]
Issue resolved, there were some large video files in my project folder. Shifting them to another folder and excluding it in jsconfig.json did the job. Wonder why autocomplete is being affected by video files o.O

**Comment by waderyan** [comment]
@dbaeumer this is similar to the other issues I have seen #11260 and #11258. I am glad that OP could resolve his issues by moving the video files, but this was not the case in the bugs I opened. 

Closing for now and will continue to keep my eye out for how to reproduce this reliably.

**Comment by waderyan** [comment]
Opened an issue in TS to try to get to the bottom of this. 

https://github.com/Microsoft/TypeScript/issues/10735

**Comment by xujihui1985** [comment]
adding large file to exclude solve the problem

**Comment by waderyan** [comment]
@xujihui1985 can you make your comment in this issue https://github.com/Microsoft/TypeScript/issues/10735
