### ISSUE TITLE
Windows 10 location of settings.json file not given in get started guide

### ISSUE THREAD

**Issue by Scrabble96** [microsoft/vscode#115071]
I was trying to find the Windows location of the settings.json file so that I could edit it. I came across instructions on this page: https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations but the location for Windows 10 is different. 

The guide says:
%APPDATA%\Code\User\settings.json

I eventually found the file in Windows 10 here:
\Users\Username\Appdata\Roaming\Code\User\settings.json

I assume that the first location probably still applies to older versions of Windows, but perhaps the Windows 10 location could be added here and anywhere else that the file location is mentioned.

**Comment by gjsjohnmurray** [comment]
Why not edit it in VS Code? Open the Command Palette (F1), type "json" and pick the relevant command.

**Comment by roblourens** [comment]
I think APPDATA should point to that folder:

![image](https://user-images.githubusercontent.com/323878/105887856-1c1e3280-5fc1-11eb-9b4b-0b9bdd228699.png)
https://ss64.com/nt/syntax-variables.html
Where does it point for you?
