### ISSUE TITLE
Watch view: Copy value copies array index instead of value

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115049]
Verifting  #114353

Have the following node program:
```
const x = [100, 10202, 232., 32];
console.log(x);
```
- set a breakpoint on `console.log`
- reach the breakpoint
- In the watch view, create an expression `x`. Expand x, the first item, Run `Copy Value`

-> '0' is copied to clipboard

Looks like it's always the index, not the value

**Comment by isidorn** [comment]
@aeschli thanks for filling this.
The problem here is that the `evaluateName` of the first element of the array is `0` instead of `x[0]`.
This is coming from js-debug thus forwarding to @connor4312
