### ISSUE TITLE
Feature Request: Remove extension command registeration from package.json 

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#11506]
Currently, you register an extension command by defining it in the `package.json` and also registering it within your code.

My request is to remove commands from needing to be defined in `package.json` contributions and make them definable and registerable only within your code.

This would open up the door for new functionality and flexibility and dynamic extension command registrations. For example being able to register a command on the fly only for specific languages.

The other part of this request is to be able to unregister commands so that they do not show up in the command palette anymore. I don't see a way in the API to unregister commands.

Again, a use case for this would be unregistering a command that is language specific. For example if you have a command you want available only for the HTML language. The way you would accomplish this:

1. Make your extension activate on the `"onLanguage:html"` activationEvent.
2. Register your extension command in your code so now its available for HTML language
3. When you switch to a different language, your extension deactivates, you code could deregister the command in you code, so now its no longer available for other extensions

So now you have an extension command that is limited only to a certain language. This is just a simple example but I imagine there are many other use cases that would come from being able to dynamically register/deregister commands on the fly without needed them to be hardcoded in `package.json`.

**Comment by jrieken** [comment]
> Currently, you register an extension command by defining it in the package.json and also registering it within your code.

Registration happens only via the `registerCommand` function. The entry in `package.json` is *only* there to add your command to the UI before loading/activating the extension code (F1 list, context menus etc). 

> I don't see a way in the API to unregister commands.

The register call gives you a disposable which removes the command again. 

In short, if you only want to expose a command by id that's fine and legit. Actually extensions and VS Code do that. Dynamic modifications of the F1 list are tracked here: #10401

**Comment by Jakobud** [comment]
Okay perhaps I'm a bit confused. If I remove the command from the `contributes` in `package.json`, and set my extension to activate `onLanguage:html`, and then register my command inside the `activate` method, I don't see it show up in the command palette. I don't see a way to set the title and description of the command dynamically. And I don't see even the command id `myExtension.myCommand` in the command palette.

I figure this topic may not have been explored much yet so there is probably just a lack of documentation on the subject. :-) If you could help clear up what I'm misunderstanding I would appreciate it!

**Comment by jrieken** [comment]
As said above: Dynamic modifications of the F1 list aka palette are tracked here: #10401.

**Comment by riteshatsencha** [comment]
@Jakobud I concur. My use case is, I only want to build the UI with commands, context menu etc. when a user has a valid license for the extension, else no need to build the UI. Listing commands in a package.json always adds the commands to the UI. Being able to add commands on fly would be great. 

Thank you
