### ISSUE TITLE
Tests and diagnostic integration

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115092]
cc @Florin-Popescu from https://github.com/microsoft/vscode/issues/107467#issuecomment-767521331, and @connorshea from https://github.com/microsoft/vscode/issues/107467#issuecomment-699096166

My current plan is to make testing separate from diagnostics on an API level, as their lifetime and properties are different than those of diagnostics. However I will have an option (on by default) show test errors/failures the Problems panel and navigable using the diagnostics keybindings.

**Comment by ashgti** [comment]
When implementing a test provider, does the test provider need to update the location of the diagnostic as the user edits the file?

In other words, if I had an assertion failure and I add a newline above the diagnostics, does the test provider need to update the TestItem to have the location adjusted?

**Comment by connor4312** [comment]
@sandy081 has expressed concern around having tests mixed with diagnostics this way.

Talking with Kai and others, though, it seems like a desirable thing to have there. It's little different than linting errors, except in the liveness of the update -- test errors are only dismissed on re-run, though this is still somewhat live if the user uses autorun. A simple solution to this would be a keybinding to toggle the participation of tests in Problems and Diagnostics.

**Comment by connor4312** [comment]
After exploring testing output and peeks some more, I now think that a dedicated peek and flow is probably better
