### ISSUE TITLE
Results peek view shall be closed if test is passed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#115003]
Testing #114932

<img width="950" alt="image" src="https://user-images.githubusercontent.com/10746682/105831635-4115a400-5fc7-11eb-8e74-634c5d7e721b.png">

**Comment by sandy081** [comment]
Peek view is still shown even after test is passed

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/10746682/109132204-ddac9c80-7753-11eb-939a-0b8acaa20907.png">

**Comment by connor4312** [comment]
This is actually different: https://github.com/microsoft/vscode/issues/117524 For the sample test provider, the test is destroyed when you change it since we use the expression to make the test ID. I recommend verifying this issue in the selfhost test provider.
