### ISSUE TITLE
Diff editor goes stale

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115042]
Testing #114969

* added the plotly.txt-based notebook, file as untracked
* open diff editor, everything is new
* commit the file
* close editors
* reopen notebook, delete a cell
* open diff
* :bug: diff shows old/stale information

<img width="1338" alt="Screenshot 2021-01-26 at 14 38 17" src="https://user-images.githubusercontent.com/1794099/105852148-5fd66380-5fe4-11eb-916c-c98d285de308.png">

**Comment by rebornix** [comment]
The Jupyter extension doesn't resolve the right content for the git resource.

**Comment by rchiodo** [comment]
I don't believe this is the extension's fault. It looks like we're not queried for the cells from the git-resource. We're only queried for the result on disk?
