### ISSUE TITLE
Output not resized correctly

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115008]
Testing #114969

* have two editor tabs open (15" screen)
* open the plotly.txt-notebook
* change to diff mode
* notice all rendered output being too narrow
* close the RHS editor group
* :bug: outputs don't resize

<img width="1264" alt="Screenshot 2021-01-26 at 11 30 25" src="https://user-images.githubusercontent.com/1794099/105833724-e598e580-5fc9-11eb-81b7-d048212ac9b8.png">

**Comment by rebornix** [comment]
The webview is resized properly, the renderer doesn't respond to that, reported to Jupyter https://github.com/microsoft/vscode-jupyter/issues/4506
