### ISSUE TITLE
not recognizing some tests I added

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#115065]
Testing #114932

![recording (6)](https://user-images.githubusercontent.com/29464607/105867416-ef125580-5fa9-11eb-842f-bb5674eb152d.gif)

**Comment by TylerLeonhardt** [comment]
I'm suspicious of the sample extension and not the underlying test code for this.

**Comment by connor4312** [comment]
Oh, yea, the sample test provider only recognizes addition.

Maybe in the next few years technology will advance enough to implement subtraction.

**Comment by TylerLeonhardt** [comment]
Quantum subtraction

**Comment by connor4312** [comment]
Marking as a bug since I'd like someone else to go through to try to hit this now that these APIs are stabilizing.
