### ISSUE TITLE
Notebook icon click feedback should be centered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115087]
Testing #114969

This applies to the play button too

Actual:

![image](https://user-images.githubusercontent.com/2193314/105877122-7a90e400-5fb4-11eb-8ab9-488422f8b919.png)

Expected:

![image](https://user-images.githubusercontent.com/2193314/105877163-867ca600-5fb4-11eb-88cd-143ad81fd399.png)

**Comment by misolori** [comment]
@Tyriar is this in a diff view or regular notebook cell? hard to tell, assuming this is the play button and output renderer?

**Comment by Tyriar** [comment]
@misolori regular notebook cell

**Comment by misolori** [comment]
These are now centered

![image](https://user-images.githubusercontent.com/35271042/106215789-93e98a00-6186-11eb-8362-422478f1b394.png)
