### ISSUE TITLE
Changing output ids cause false diffs

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115044]
Testing #114969

* use the plotly.txt-notebook, tracked, not changes
* delete a cell, save
* diff editor shows the deleted cells but also red/green for other outputs
* text-diff of the output shows that it is output ids (this might be an issue with the jupyter extension)

<img width="1517" alt="Screenshot 2021-01-26 at 14 43 54" src="https://user-images.githubusercontent.com/1794099/105852720-1a666600-5fe5-11eb-92a6-d53142329be6.png">

<img width="977" alt="Screenshot 2021-01-26 at 14 45 51" src="https://user-images.githubusercontent.com/1794099/105852800-34a04400-5fe5-11eb-9907-e75bbd7618c2.png">

**Comment by rebornix** [comment]
The jupyter extension may want to make it transient, which we don't currently support yet. cc @DonJayamanne

**Comment by DonJayamanne** [comment]
@rebornix Apologies for the delay in looking into this.
The property `outputId` is something VS Code is in control of. We don't add this & don't even have access to this property.
I think VSCode should not display this in the diff viewer at all, I think its used internally by VS Code (when rendering output).

See here for spec of output (there is no `outputId`)
```typescript
	export interface CellDisplayOutput {
		outputKind: CellOutputKind.Rich;
		/**
		 * { mime_type: value }
		 *
		 * Example:
		 * ```json
		 * {
		 *   "outputKind": vscode.CellOutputKind.Rich,
		 *   "data": {
		 *      "text/html": [
		 *          "<h1>Hello</h1>"
		 *       ],
		 *      "text/plain": [
		 *        "<IPython.lib.display.IFrame at 0x11dee3e80>"
		 *      ]
		 *   }
		 * }
		 */
		data: { [key: string]: any; };

		readonly metadata?: NotebookCellOutputMetadata;
	}
```

**Comment by rebornix** [comment]
This issue should be gone now as we move to the new API and only compare `outputItems` now.
