### ISSUE TITLE
Indent guides don't look great in notebook cells

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115079]
Testing #114969

The "status bar" of the notebook cell has the same color as the editor so the indent guides just end all of a sudden:

![image](https://user-images.githubusercontent.com/2193314/105874824-eaea3600-5fb1-11eb-8010-9b75cb8c8436.png)

Compare to editor:

![image](https://user-images.githubusercontent.com/2193314/105874884-f9d0e880-5fb1-11eb-9ef9-e01379e166e9.png)

**Comment by misolori** [comment]
This is intentional as there can be items in the status bar that would overlap with the guides and would make the text hard to read.
