### ISSUE TITLE
Usage of mimetype when changing output

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115081]
Testing #114969

Most users won't know what a mimetype is:

![image](https://user-images.githubusercontent.com/2193314/105875299-7d8ad500-5fb2-11eb-8356-8d9c62ce7236.png)

Could this instead say:

Select how to render the output

- **HTML document** Currently Active
  text/html (built-in)
- **Raw text**
  text/plain (built-in)

**Comment by rebornix** [comment]
Make sense
