### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#115093]
- [x] Windows @bamurtaugh
- [x] macOS @connor4312 
- [x] Linux @dbaeumer 
- [x] web @RMacfarlane 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23115093%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by dbaeumer** [comment]
@sbatten I don't have a Mac. I can volunteer for Windows or Linux.

**Comment by sbatten** [comment]
@dbaeumer I will reassign you to linux, relieving @alexdima  since I believe he got overassigned
