### ISSUE TITLE
Request for "Edit settings.json" option in File -> Preferences

### ISSUE THREAD

**Issue by joshxyzhimself** [microsoft/vscode#115068]
It's a bit sluggish having to remember `CTRL + SHIFT + P` then manually typing `settings.json`; or `CTRL + ,` or navigating `File -> Preferences -> Settings` then search for small `Edit in settings.json` links just to get to the `settings.json` file.

Users new to VSCode are having a legit hard time going through these loops when they just want to do simple changes to `settings.json`.

Can't we just directly include `Edit settings.json` option between `Settings` and `Online Services Settings` in the `File -> Preferences` ?

```
File
--> Preferences
----> Settings
----> Edit settings.json
----> Online Services Settings
```

![image](https://user-images.githubusercontent.com/60829711/105870705-7d7ee980-6033-11eb-94c3-906cf43bbdb6.png)

**Comment by CaptainN** [comment]
Or even just a button at the top of the GUI - as it is I have to search through dozens of settings to find a "Edit in settings.json" link - just include it at the top please.

**Comment by roblourens** [comment]
There is already a button for it, top left here

![image](https://user-images.githubusercontent.com/323878/106647823-4bdeb480-6544-11eb-8fbf-0e88a44e21a4.png)

I get it, but I don't want to add a menu item to a sort of crowded menu. There are many ways to get into it.

- Command palette
- That button, or the per-setting links that you identified
- The `workbench.settings.editor` to change the default
- Add a keybinding (I use this)

**Comment by CaptainN** [comment]
Oh, well that was obvious! (<-- sarcasm). Thanks for pointing it out though! ;-)

**Comment by joshxyzhimself** [comment]
@roblourens That's literally the same as navigating File -> Preferences -> Settings then search for small Edit in settings.json links just to get to the settings.json file, except much harder because who would've thought that top-right icon becomes a link to the `settings.json` when the `Settings` tab is open? That's very special-cased and non-intuitive otherwise we would've easily found it, right?

You're right, there are many ways to get into it.

But when a new user installs an extension (e.g. a linter like ESLint or Prettier), people need to config parts of it on `settings.json` directly, and the available many ways to get into it aren't really that obvious.

**Comment by joshxyzhimself** [comment]
Sample scenario, say you're talking to students / interns.

"Now guys, after installing that extension, let's navigate to `File` -> `Preferences` -> `Edit settings.json` and enter our linter configuration."

"Now guys, after installing that extension, let's navigate to `File` -> `Preferences` -> `Settings`, then click the first top-right icon at the tabs. Note that that icon has different function when Settings tab is closed."

"Now guys, after installing that extension, let's navigate to `File` -> `Preferences` -> `Settings`, then keep scrolling down until we find a line that says "Edit settings.json""

Now guys, after installing that extension, let's press `CTRL + SHIFT + P` then manually type "Edit settings.json" then click on the first item.."

Which is more easier, obvious, and easier to follow: first one right?

**Comment by roblourens** [comment]
These buttons are contextual to the editor for all editors, also we can't expose 100% of functionality through menu items. I would expect that students or people who are new to vscode will prefer a graphical settings UI over learning the syntax of a JSON config file. That's who it is designed for. I know it doesn't handle all cases but we try to continue to improve it. Will move this to backlog candidates though.
