### ISSUE TITLE
Confusing diff information

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115040]
Testing #114969

* create fresh notebook plotly.txt-contents, the file is untracked
* open diff editor
* for one cell/output-pair it says "Outputs changed", 
* for all other it doesn't, outputs are collapsed
* I would expect all outputs to rendered equally because they are all untracked

<img width="1338" alt="Screenshot 2021-01-26 at 14 31 09" src="https://user-images.githubusercontent.com/1794099/105851476-6dd7b480-5fe3-11eb-84ab-35cee5107a77.png">

**Comment by DonJayamanne** [comment]
I think this happens because we always end up with 1 cell when creating new notebooks. Which is why we see the intput is also marked as changed (for first cell)

**Comment by DonJayamanne** [comment]
Tested, and doesn't seem to be an issue anymore.

**Comment by DonJayamanne** [comment]
Can still repro
