### ISSUE TITLE
Find all references to file: Improve History entry rendering

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115014]
Testing #114966

- open the VSCode repo. Update typescript with `yarn add typescript@4.2.0-beta`, reopen the window
- select a `.ts` file in the file explorer (e.g. `themeService.ts`) and run `Find file references` from the context menu, repeat this for other `ts` files
- clear the results in the references view (clear command in the view bar title)

The search history entries are confusing:

![image](https://user-images.githubusercontent.com/6461412/105834261-8be4eb00-5fca-11eb-97ab-1aed358b7c5d.png)

**Comment by mjbvz** [comment]
@jrieken Is there any way I can explicitly set the history label in the references view? I believe it uses the position by default, which ends up being our header comments

**Comment by jrieken** [comment]
No, that cannot be configured. The logic is build around the assumption that your are searching references from a symbol and showing the surroundings of a symbol makes usually sense. I also wouldn't add this to the references viewlet, instead we should invest in a "real" UI for file references

**Comment by mjbvz** [comment]
Closing this in favor of #134405
