### ISSUE TITLE
Github 

### ISSUE THREAD

**Issue by qmit1000** [microsoft/vscode#115029]
Issue Type: <b>Bug</b>

I have installed github desktop for my pc but visyal studio0 isnt able to detect it thus i am not able to clone any repository that i need. i am studying to code and this is making it very hard for me to code please tell me what i should do to make  visual studio detect my github application. 

my sincere thanks

Justin 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (1.50GB free)|
|Process Argv|--crash-reporter-id 7a6dcde0-590b-4afb-981a-b19f9f1d580f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspyt653:30244269
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30247032

```

</details>

**Comment by qmit1000** [comment]
i sent this through github on the web

**Comment by Samridhi-98** [comment]
Hey @qmit1000 
Please read these articles mentioned below and follow the steps, hope it will help you to resolve the issue.

Link 1: https://marketplace.visualstudio.com/items?itemName=wraith13.open-in-github-desktop#:~:text=Show%20extension%20side%20bar%20within,Code%20when%20installation%20is%20completed.

Link 2: https://adamtheautomator.com/visual-studio-code-github/

**Comment by kieferrm** [comment]
Pls see https://code.visualstudio.com/docs/editor/github#_cloning-a-repository.
