### ISSUE TITLE
Unsure how to leverage new attributes for ports

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#115098]
Testing #114532

I wanted to test out the attributes described here: https://github.com/microsoft/vscode-remote-release/issues/4046#issuecomment-758754107 to see how they'd impact port forwarding. However, when I try including them in my `devcontainer.json`, I get the following problem:

![image](https://user-images.githubusercontent.com/25310137/105879813-774b2780-5fb7-11eb-8e6a-3683c530f546.png)

This could certainly be user error - but if so, do we have how to use these attributes documented anywhere so that users can avoid any issues?

**Comment by aeschli** [comment]
There's a `[` too much after `"remote.portsAttributes": `. I tried this and it worked:
```
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash",
        "remote.portsAttributes": {
            "5000": {
                "label": "XX",
                "onAutoForward": "notify"
            }
        }
    },
```
