### ISSUE TITLE
Test explorer shall show the document tests if workspace tests are not provided

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#115010]
Testing #114932

If the test provider does not provide workspace hierarchy then the test explorer shall show the document tests

<img width="750" alt="image" src="https://user-images.githubusercontent.com/10746682/105833840-0eb97600-5fca-11eb-8d05-5630f7c9a0e5.png">

**Comment by connor4312** [comment]
Tyler implemented this

**Comment by connor4312** [comment]
Nevermind, this is actually separate. Will put in next milestone.

**Comment by connor4312** [comment]
We now require workspace tests to be provided
