### ISSUE TITLE
UI state not restored in insiders

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#115024]
Testing #114826

I have this folder and UI state in stable:

![image](https://user-images.githubusercontent.com/1704059/105838741-6bb42c80-5fc8-11eb-8912-c25c462f5adf.png)

When I close stable and open the same folder in insiders I see this:

![image](https://user-images.githubusercontent.com/1704059/105838852-969e8080-5fc8-11eb-90ad-f577462cc74e.png)

The state is preserved when reopening stable.

Insiders build: Version: 1.53.0-insider (user setup)
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:13:59.356Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Stable: Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
@stevencl I tried to reproduce this and failed. I wonder if any setting you have configured could have an impact. To begin with, does it reproduce when you run VS Code from a fresh user data dir from the command line (`--user-data-dir <some empty dir>`)?

Can we also try other workspace UI state, e.g. the visibility and size of the panel?

**Comment by bpasero** [comment]
Oh sorry, as I pointed out in slack I forgot one important piece for testing: needs the same `--user-data-dir` for both instances otherwise we cannot simulate the restoral of UI state properly. I have updated the test plan item.

**Comment by stevencl** [comment]
No worries, works now.
