### ISSUE TITLE
Doing a performance profiling freezes notebook and defers all mouse events until the profile has stopped

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115091]
Testing #114969

This issue makes it touch to look into scroll/layout perf of notebooks

Repro:

1. Open an ipynb
2. Open devtools
3. Do a perf profile
4. Use the mouse wheel in the editor, nothing happens
5. Stop the profile, all wheel events are triggered

![recording (40)](https://user-images.githubusercontent.com/2193314/105877511-ef641e00-5fb4-11eb-8c48-1dd0b576a756.gif)

Version: 1.53.0-insider (user setup)
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:13:59.356Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by rebornix** [comment]
@deepak1556 do you have ideas about this?

**Comment by deepak1556** [comment]
Is it better when you start the app with `--disable-renderer-accessibility` ?

**Comment by Tyriar** [comment]
@deepak1556 no it still happens, I ran it like this:

```
$ c --disable-renderer-accessibility
Warning: 'disable-renderer-accessibility' is not in the list of known options, but still passed to Electron/Chromium.
```

I don't see it on the renderer's argv, does it only get applied to the main proc?

![image](https://user-images.githubusercontent.com/2193314/106748438-14224c00-65da-11eb-9a03-874df4b457a9.png)

**Comment by deepak1556** [comment]
Issue does not repro with recent versions.
