### ISSUE TITLE
Notebook cell status bar lacks left padding

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115099]
Testing #114969

![image](https://user-images.githubusercontent.com/2193314/105879934-9cd83100-5fb7-11eb-8742-3ddead95d026.png)

**Comment by eamodio** [comment]
I'm still seeing this:
![image](https://user-images.githubusercontent.com/641685/109215294-fc755800-7780-11eb-89aa-d0652b6e81e4.png)

It worked fine if I had and expression in the cell, but when I ran an empty cell it didn't have padding

**Comment by rebornix** [comment]
I'm not going to fix this issue with css tricks, may need @roblourens 's help on this. My previous fix was adding `padding-left` for the first element, but the cell status code logic will set it `display:none` when the run status is idle, which break the fix.

The reason we can't have padding-left for the whole left status bar container is it will break the padding of the contributed status item. @roblourens we can look into revamp the DOM structure to fix it properly.
