### ISSUE TITLE
Renderer log is missing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115027]
* I ran into some trouble with Insiders that I wanted to trace
* opened output
* no renderer log.. 😕 

<img width="362" alt="Screenshot 2021-01-26 at 12 32 43" src="https://user-images.githubusercontent.com/1794099/105840352-34974880-5fd3-11eb-9618-7667537d0e72.png">

**Comment by jrieken** [comment]
After reload this back

**Comment by sandy081** [comment]
@jrieken Is there any more info you can provide to reproduce this? Did you follow any specific steps?

**Comment by jrieken** [comment]
No further steps, no log viewer 😆

**Comment by sandy081** [comment]
This can happen only if the corresponding log file was not created yet. I think it is hard to speculate why it was not yet created. I am not sure if you checked the dev tools console at that time, have you seen any errors ?

**Comment by jrieken** [comment]
No, I was busy drilling into another issue and didn't have patience to investigate

**Comment by sandy081** [comment]
I understand. Do you mind keeping an eye on this and if you get into this again, can you please try to get more info like:

- Check if there are any errors in the console
- Open logs folder and see if the log file for that window is created or not
- Also any specific steps that lead to this
