### ISSUE TITLE
Find all references to file: not all references to vscode.d.ts found

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115020]
Testing #114966

- open the VSCode repo. Update typescript with `yarn add typescript@4.2.0-beta`, reopen the window
- select r `src/vscode.d.ts`,  in the file explorer and run `Find file references` from the context menu: No results
- Now open a `ref.d.ts` file and search again, reference found
- we have around 30 reference in various ref.d.ts files.

**Comment by mjbvz** [comment]
This sounds like it is by-design. Find file references will only apply to your currently opened JS/TS projects. It will not try to open additional project in the current workspace.

When you open `vscode.d.ts`, it should load the core VS Code project. However the individual extension projects will only be loaded when you open a file from them, such s `ref.d.ts`
