### ISSUE TITLE
Icons to the right of + shake when mousedown on new terminal button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115082]
Notice how the split and kill icons shake when mouse down is fired, it's just for a frame so some don't show up in the gif:

![recording (36)](https://user-images.githubusercontent.com/2193314/105875738-030e8500-5fb3-11eb-9234-26a142aa1c6e.gif)

**Comment by misolori** [comment]
This feels like a grayscale issue due to the zoom on click, I can't repro since I don't have any non-hidpi screens.

**Comment by isidorn** [comment]
I also do not see this on my machine. @Tyriar do you see this across all action bars or only for those exact icons?

**Comment by Tyriar** [comment]
It happens in output as well, it seems to start from the 4th+ icon from the right. It does not happen in the explorer or editor top right.

**Comment by isidorn** [comment]
I have no plans to fix this and neither do I know how. Unassigning myself

**Comment by misolori** [comment]
@Tyriar can you confirm if this still happens since we removed the scale on click?

**Comment by Tyriar** [comment]
I think the scale was the cause
