### ISSUE TITLE
Unable to open 'plotly.txt.ipynb (Untracked)': ModelService: Cannot add model because it already exists!.

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115019]
Testing #114969

* open notebook editor for plotly.txt
* open diff editor for notebook
* press `cmd+\` to split/duplicate the error to the side
* 💥 an error shows

The bad code is here: https://github.com/microsoft/vscode/blob/51d19635946a76d2f9007f9e4f4db1c26a0ebfae/src/vs/workbench/contrib/notebook/browser/diff/diffComponents.ts#L489

@rebornix the rule of thumb is that you should NEVER use `createModel` unless you the owner (content provider) of that uri

**Comment by rebornix** [comment]
Might share the same root cause as https://github.com/microsoft/vscode/issues/115018 and already fixed, continue investigation there.
