### ISSUE TITLE
Write access problems are not handled clean

### ISSUE THREAD

**Issue by HolgerJeromin** [Microsoft/vscode#11504]
- VSCode Version: 1.4.0
- OS Version: Debian stable 64 bit

Steps to Reproduce:
1. Open a file which is only readable for this user
2. Change something and try to save. Bam! A warning is shown:
![image](https://cloud.githubusercontent.com/assets/2410353/18227121/294116a6-721a-11e6-98c2-97afe8f695fb.png)
3. Click on "retry" and visual studio is happy again, the dialog was closed. But the file is not saved!

clicking "retry" triggers the same warning in the console again:
`messageService.ts:119 Fehler beim Speichern von "admin_int.php": Systemfehler (EACCES: permission denied, open '/var/www/XXXX`

**Comment by bpasero** [comment]
@HolgerJeromin what does "clean" mean then?

**Comment by HolgerJeromin** [comment]
File is not saved. No info is presented to the user. I thought my explanation in the issue was complete.

**Comment by bpasero** [comment]
@HolgerJeromin what do you mean "no info is shown to the user", did you not even attach the screenshot with that info?

**Comment by HolgerJeromin** [comment]
*Save try 1:
** Message with "cannot save file" 
*Click retry:
**Message goes away, but file is not saved. 
**User thinks the file is saved, but it is not

**Comment by bpasero** [comment]
Ok that would be a bug indeed.

**Comment by HolgerJeromin** [comment]
I can reproduce the issue on windows, too. Just deny write access to the file in this dialog:
![image](https://cloud.githubusercontent.com/assets/2410353/18250054/f8af020a-7381-11e6-82c3-082a605677ce.png)

Changing to "write only" in the first tab allows vscode to overwrite this lock after a dialog.

**Comment by bpasero** [comment]
Verify: after retrying the save operation, the error message shows up again in case of another error.

**Comment by HolgerJeromin** [comment]
Thanks for the quick fix!
