### ISSUE TITLE
Support retired test states

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115086]
About [retired](https://github.agodadev.io/agoda-front-end/agoda-com-dictator/blob/5a17a280545bb142c1274276e587844f5da623cc/Src/Agoda.Website/Agoda.Website.MVC/Areas/NewSite/Login/Services/AccountProtectionService.cs#L66) states.

This basically a property which is perpendicular to the `TestRunState`.
If the binary which contains the tests has changed then all the test results are retired/old/expired/invalid.
<img width="168" alt="Screen Shot 2021-01-26 at 21 02 37" src="https://user-images.githubusercontent.com/16504598/105854825-f113fd00-6019-11eb-88b0-6f1bb3cae5b0.png">

Me personally really liked this feature of the "Test Explorer" by @hbenl.
It's almost like setting the TestRunState to `Unset` back but still indicating what was the previous result.

Please consider the support of it 🙏

_Originally posted by @matepek in https://github.com/microsoft/vscode/issues/107467#issuecomment-767565151_

**Comment by hbenl** [comment]
> It's almost like setting the TestRunState to Unset back but still indicating what was the previous result.

Actually that describes exactly how it is implemented in the Test Explorer extension: the current state is set to pending (which corresponds to Unset in the TestProvider API) but the previous state is remembered and shown with a faint icon.
So the new Test Explorer could support this without changing the API, it just needs that special logic when a test's state is changed to Unset.

**Comment by connor4312** [comment]
Thanks! I ended up doing this kind of differently since states are now (only) stored in test results. Tests added to the result are not-retired, and I add a retired flag when they get retired. Persisted results from previous sessions are always marked as retired, since we can't generally know whether they're still alive.
