### ISSUE TITLE
Not able to open IDE

### ISSUE THREAD

**Issue by saptarshi007** [Microsoft/vscode#11508]
- VSCode Version: 1.4.0
- OS Version: WIndows 7

Steps to Reproduce:

1. always its unexpectedly closing with the error 'you can reopen the window to continue where you left off'
2.  I reinstalled the app. But still facing same issue.
Kindly help

**Comment by dbaeumer** [comment]
@saptarshi007 could you attach a screen shot showing this. AN can you reproduce it when starting code with --disable-extensions from a terminal.

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
