### ISSUE TITLE
I don't know what [1] means in notebooks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115095]
Testing #114969

Unfiltered notebook noob feedback:

![image](https://user-images.githubusercontent.com/2193314/105879163-b167f980-5fb6-11eb-9c66-1a5c83975bb7.png)

I was expecting a tooltip to tell me what it meant.

**Comment by rebornix** [comment]
Agreed that we should add tooltip for it.

**Comment by roblourens** [comment]
@Tyriar what would you think it means if there was a tooltip that said "Execution Order"?

**Comment by Tyriar** [comment]
@roblourens when you run all cells it goes in that order? I was expecting that to be sequential from the top?

**Comment by roblourens** [comment]
It's the order that it _was_ executed it, not the order it _will_ execute in. Hopefully a user would figure that out if they run the cell and see it change.

**Comment by Tyriar** [comment]
@roblourens oh, more explicit would be better then imo

> The order this cell was executed in

I also question why this is useful but I'm guessing this is a common notebooks feature elsewhere?

**Comment by roblourens** [comment]
Yeah it's what people expect from Jupyter and can help you understand the state of the kernel

**Comment by roblourens** [comment]
Thanks @tanhakabir, that needs to be localized though. btw if you are going to merge your change in, you can just commit directly, on PR needed
