### ISSUE TITLE
Diff editor screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115012]
Testing #114969

No clear steps, but using the plotly.txt notebook, with the diff-editor and output-diff-rendering I see a lot of screen cheese. 

<img width="1275" alt="Screenshot 2021-01-26 at 11 33 16" src="https://user-images.githubusercontent.com/1794099/105834085-54763e80-5fca-11eb-83ee-1e210174babb.png">

**Comment by jrieken** [comment]
Maybe simpler to reproduce

* get `joh/persistOutput` branch for GH issue notebook
* run `npm bundle-all` and hot `F5`
* open a diff for GH issue notebook
* reload the window
* 🧀 


<img width="1354" alt="Screenshot 2021-01-26 at 12 57 31" src="https://user-images.githubusercontent.com/1794099/105842195-1848db00-5fd6-11eb-9289-300c6f63759e.png">

**Comment by DonJayamanne** [comment]
I'm not able to repro this, and given the fact that a number of similar issues were fixed in the past (I recall fixing such screen cheese issues early in the year), I believe its safe to close this as fixed.
