### ISSUE TITLE
Is Default's CompletionItem info cut off?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#115166]
Testing #114962

![image](https://user-images.githubusercontent.com/2644648/105925593-4db0f100-5ff5-11eb-9449-4541e77e929c.png)

```
The opener can open the uri.

When the user clicks on a uri, they will be prompted to select the opener they wish to use for it. All
```

All... what?

**Comment by mjbvz** [comment]
Fixed by 9421e50aa8e68a2f1dda4f4418fe3dc1cc646c63
