### ISSUE TITLE
Loaded script section pushes down the realtime performance chart

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115116]
Testing #114345

See lower-left corner:
![loaded-scripts-pushdown](https://user-images.githubusercontent.com/7199958/105890498-49201480-5fc4-11eb-868a-08cfa497a33a.PNG)

Before pressing the play button, the loaded scripts section isn't rendered, but after I start debugging, that section is rendered collapsed, and pushes down the breakpoints and realtime performance viewlets.

**Comment by weinand** [comment]
Please use drag-and-drop to bring the section in your preferred order (or hide the ones you are not interested in).
