### ISSUE TITLE
 onUriOpen is not suggested as a completion in package.json activationEvents

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115131]
Testing #114962

<img width="379" alt="image" src="https://user-images.githubusercontent.com/2230985/105894891-a5396780-5fc9-11eb-9526-d3a8c064a3f5.png">

**Comment by mjbvz** [comment]
Good note for the future but I'm going to hold off on adding this  suggestion until we finalize the api (I also may change the name to `onOpenExternalUri`)

refs #109277
