### ISSUE TITLE
Default Outline sorting is not useful for notebooks

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115197]
Testing #114902

* open `.vscode/notebooks/inbox.github-issues`
* observe the Outline in the Explorer
* the default sorting for notebooks should be by "Position" and not by categories/alphabetical
* (it is even questionable if any other sorting besides "Position" should be offered at all)

![image](https://user-images.githubusercontent.com/5047891/105963242-112ad700-6081-11eb-8951-10b51943b68b.png)

**Comment by jrieken** [comment]
Default should be `ByPosition`, see https://github.com/microsoft/vscode/blob/d66db5cc754dc760ffb0a69049e5127fb78d723f/src/vs/workbench/contrib/outline/browser/outlineViewState.ts#L20

@alexdima Can you check what's selected the `...`-menu

**Comment by alexdima** [comment]
This is the menu:

![image](https://user-images.githubusercontent.com/5047891/105971147-7e8f3580-608a-11eb-8c9b-2c6f0febfbed.png)

Maybe I changed this some long time ago? Is this stored in a setting that I can reset?

**Comment by jrieken** [comment]
> Is this stored in a setting that I can reset?

You can change it in the menu, that's then stored in a memento and sync'd across the machines (iff using settings sync)

> Maybe I changed this some long time ago?

Maybe but I have also fixed a bugs shortly that the default was wrong

**Comment by jrieken** [comment]
closing as dupe
