### ISSUE TITLE
Allow hiding/excluding tests

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115102]
Requested in https://github.com/microsoft/vscode/issues/107467#issuecomment-763938766 by @OmarTawfik

**Comment by connorshea** [comment]
My use case for this would be to exclude tests from other parts of a large repo, although that might be something that should be handled via a glob at the test adapter level.

**Comment by connor4312** [comment]
This raises the question of whether excluded tests should be run at all. If they shouldn't, then either:

- we don't modify the run tests request, so if deeply nested test is excluded from a massive tree, we should request each individual test in the tree be run except for the one excluded tests, or
- the "run tests" request would change to be something like `{ include: T[]; exclude: T[]; ...}`. This would solve it nicely but I'm not sure this could be implemented very well by all test adapters. **Action:** I'm interested in feedback from test extension authors on this.

**Comment by firelizzard18** [comment]
I suggest a capabilities-based approach, similar in design to the Debug Adapter Protocol. This would allow different test adapters to support different feature sets.

**Comment by connor4312** [comment]
We don't have 'capabilities' in the extension host api. The most we do is detect the presence of registered providers or implemented methods.

We could just have it always use the include/exclude pattern, and adapters could respect exclude if they're able to. This might lead to some user reports if they exclude a test in an adapter that doesn't respect it and it ends up running... but I think every major test runner supports exclusion, so this may not be a big deal.

**Comment by connor4312** [comment]
There's now an `exclude` option in in the `runTests` method / TestRunOptions. Only excluded tests who are children of the provided set of tests will be given in the exclude call. Providers can honor the exclusion or not, but regardless VS Code will not include states of excluded tests in results or the UI.

**Comment by jrieken** [comment]
Rendering is very subtle. Will create a separate issue for that
