### ISSUE TITLE
Smoketests fails on osx

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115151]
Testing https://github.com/microsoft/vscode/issues/115093

While smoke testing, this alert came up. Then other tests started timing out:

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/2230985/105901156-cdc55f80-5fd1-11eb-95a5-922ecd419589.png">

I reran the tests and this didn't happen the second time.

**Comment by bamurtaugh** [comment]
I believe this also happened for me (just on my first run), but since it was my first smoke test, I thought it was user error on my end.

**Comment by rebornix** [comment]
I'm not seeing this while testing it on macOS. @roblourens can you help confirm?

**Comment by connor4312** [comment]
Unfortunately I don't have any repro steps 😕

**Comment by sbatten** [comment]
@connor4312 just want to confirm, does this happen to you reliably, or just happened the first time?

**Comment by connor4312** [comment]
This just happened the first time. Wasn't able to repro in a couple runs afterwards.

**Comment by roblourens** [comment]
I'll close it and we can see whether it happens again. I don't remember this coming up in the CI runs
