### ISSUE TITLE
Notebook diff editor shows pointer cursor when hoving the border of the cell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115145]
Testing #114969

This happens on the left/right border as well.

![recording (50)](https://user-images.githubusercontent.com/2193314/105898804-bafd5b80-5fce-11eb-9199-f951622028ac.gif)

**Comment by Tyriar** [comment]
Also in the black shadow part

**Comment by rebornix** [comment]
No longer reproduceable in latest Insiders.
