### ISSUE TITLE
Tab wrap - dragging a tab with wrapping could end up dragging the wrong tab

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115143]
Testing #114827

Here you can see that I started dragging the settings editor, but it ends up dragging `git.ts`

![tab-dragging](https://user-images.githubusercontent.com/641685/105898306-44b92300-5fe7-11eb-8943-3fa589bece3c.gif)

**Comment by bpasero** [comment]
Again, the fact that editor toolbar actions appear right on click moving the tabs around is causing issues like this one. I believe a solution would require the editor actions toolbar possibly appearing only later, e.g. after mouse-up. Would also help for https://github.com/microsoft/vscode/issues/113818 I think.

**Comment by bpasero** [comment]
related/duplicate https://github.com/microsoft/vscode/issues/115136

**Comment by eamodio** [comment]
Glad this was re-opened. We need to ensure the tab we moused down on is the same that gets dragged.

**Comment by bpasero** [comment]
This is not trivial, the editor group is getting active through a focus change event and this seems to fire at the same time the mouse goes down. When you then start to drag, it drags the actual tab that is under the mouse. I have not yet figured out how to prevent that but I feel that there is a bunch of issues around tabs moving that need one fix.

**Comment by bpasero** [comment]
Still merging into #115136, I don't want to push a hack fix for this if we end up fixing #115136 properly. I feel what we need is a way to have editor actions on a dedicated row below tabs in case needed so that tabs are not pushed around.
