### ISSUE TITLE
Tab wrap - odd break in selected tab underline border

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115129]
Testing #114827

With settings
```json
	"workbench.editor.wrapTabs": true,
	"workbench.editor.tabSizing": "shrink"
```

![image](https://user-images.githubusercontent.com/641685/105894016-cefe8880-5fe1-11eb-8f9e-095d747f1428.png)

**Comment by bpasero** [comment]
Good catch, we have a `::after` element when `tabSizing: shrink` to draw a gradient at the end of the tab. This gradient was potentially drawing over borders. My fix is to adjust the height and position of this overlay to be within the tab and not over borders.
