### ISSUE TITLE
Split terminal visually overlaps with neighbor during resize

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#115154]
Issue Type: <b>Bug</b>

**Repro**
1. Split a terminal
1. In both terminals, run some kind of script that outputs text that horizontally fills the terminal
1. Now resize the left terminal to make the right one smaller

**Bug**
For a half second during the resize, the content of two terminals end up overlapping

https://user-images.githubusercontent.com/12821956/105904006-73c69900-5fd5-11eb-9718-18ac400cd725.mp4

VS Code version: Code - Insiders 1.53.0-insider (1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3, 2021-01-26T05:12:23.287Z)
OS version: Darwin x64 20.2.0
Remote OS version: Linux x64 5.4.0-1036-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id cc7f0c9b-aa2b-4a45-8baa-81ffda32679e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1036-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|3.84GB (0.93GB free)|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
I think this is just a problem with the dom renderer?

**Comment by mjbvz** [comment]
Oh yeah, I had `"terminal.integrated.rendererType": "dom"` set. There's a slight amount of overlap with canvas renderer (specifically the sash border seems to overlap with a few characters of the terminal for a few hundred ms at most), but it is much better

**Comment by Tyriar** [comment]
Should probably use `overflow: hidden` on each pane, that should fix.
