### ISSUE TITLE
Focusing VS Code causes system volume to increase.

### ISSUE THREAD

**Issue by jedensuscg** [microsoft/vscode#115174]
After fresh install of Windows 10 Pro and VS Code. Every time I open or make VS Code window the focus, my system volume increases to 47%. If I un-focus VS Code, the system volume returns to the previous setting after a few seconds. Disabled all extensions and still does it.
Using same headset as previous Windows install (same edition). Sadek SA-902
Uninstalled and reinstalled VS Code, no change. Tried different USB Ports, no change. Tried using Sadek headset drivers, no change.

This only happens with VS Code, no other program I have tried has the same issue. This includes Atom, Chrome, Steam, Steam VR, any other game, and numerous other apps and programs.

**UPDATE** does not reproduce in VS Code Insiders

Windows 10 Pro Version 10.0.19042 Build 19042
VS Code version 1.52.1
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.05GB free)|
|Process Argv|--crash-reporter-id d1370ff0-5879-413d-8443-aa630059c2c1|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

You've removed part that would tell VS Code and OS version.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Is it reproducible with VS Code Insiders? https://code.visualstudio.com/insiders/

Do you have any automation programs installed?

**Comment by jedensuscg** [comment]
Not sure why it didn't copy paste the rest of my system info. When I get home from work I will try VS Code Insiders, get a video of what's happening, and try a few other things. In the meantime:

I do have some automation software for control fans and motherboard options (rgb and such.). It's a brand new hardware setup, new Motherboard, CPU, RAM and HDD I should add. 

I did shutdown all running programs though, including all software that controls the above functions, but I did not actually verify if the services attached to them were stopped. Will check that as well.

Also, all extensions are currently disabled while I was troubleshooting.

More info to follow.

**Comment by jedensuscg** [comment]
> /needsMoreInfo
> 
> You've removed part that would tell VS Code and OS version.
> 
> Is it reproducible with all extensions disabled?
> You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> 
> Is it reproducible with VS Code Insiders? https://code.visualstudio.com/insiders/
> 
> Do you have any automation programs installed?

My VS Code Issue Reporter form was not actually reporting my windows version or VS Code version when I used, even when I preview on Github. So I added it to the original report.

The issue DOES NOT reproduce on VS Code Insiders. I even sync all my settings and extensions from Stable to see if it was something in there.

**Comment by kieferrm** [comment]
1.52 is on a different electron version than Insiders. 1.53 which we plan to release this week will then be on the same electron version as the current Insiders build.

**Comment by deepak1556** [comment]
Do you still experience the issue with latest stable `1.53` ?

**Comment by jedensuscg** [comment]
> Do you still experience the issue with latest stable `1.53` ?

Yes. I even uninstalled and re-installed and did install any extensions.
My full version info
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Insiders Edition still works normally:
Version: 1.54.0-insider (user setup)
Commit: 9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea
Date: 2021-02-23T10:46:22.816Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

My insiders version has all the same settings and extensions (used settings sync to bring everything over). Really have no idea why they are working differently, especially since my laptop works fine with release edition.

**Comment by deepak1556** [comment]
Can you delete the contents under `%APPDATA%\Code` and `%USERPROFILE%\.vscode\extensions` then start vscode. Does the issue continue to happen ?

**Comment by jedensuscg** [comment]
Deleted everything, even reinstalled afterwords, still does it.
But I did 'sorta' fix it, as described below:

I think this changed since the last time I installed VS code (on my old computer before I upgraded), but I have been installing the user installer. When this dawned on me, I downloaded and installed the SYSTEM installer and the problem is no longer there. It seems to only be on the standalone user installer.

**Comment by deepak1556** [comment]
Thanks for testing, I don't have further ideas to debug this issue. Maybe you can obtain the audio device handle from `Sound Control Settings` and check if the vscode process is accessing it when focused. I am pretty sure the behavior doesn't arise from vscode but rather another audio software is mistreating the application. Going ahead and closing, sorry about it.

**Comment by agent457** [comment]
I also have something similar happening to me, but it happens whenever I open Visual Studio, not VScode.
Additionally, for me, it goes to 100, and a few seconds later it back down to my original, which is 24.

Did anyone succeed in finding a solution?

**Comment by will-code-for-foo** [comment]
Disabling the extension `VS Code Speech` fixed the issue for me

**Comment by D-jazic** [comment]
> Disabling the extension `VS Code Speech` fixed the issue for me

thanks, helped, when focused VS code my volume was like from the bucket:)
