### ISSUE TITLE
If it can support Haskell that will be much better!!!

### ISSUE THREAD

**Issue by AurevoirXavier** [Microsoft/vscode#11511]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. No

**Comment by XVincentX** [comment]
You should try to look for [plugins](https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell)

**Comment by xaviercest** [comment]
@XVincentX ooooh i forgot...

**Comment by chrisdias** [comment]
Closing as there are some great [Haskell extensions](https://marketplace.visualstudio.com/search?term=haskell&target=vscode&category=Languages&sortBy=Relevance
) in the marketplace!
