### ISSUE TITLE
Unhelpful suggestions for `workbench.externalUriOpeners` setting

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#115155]
Testing #114962

1. Open settings gui and search for workbench.externalUriOpeners
2. Click "Edit in json"

![Screen Shot 2021-01-26 at 11 22 33 AM](https://user-images.githubusercontent.com/3672607/105904892-9b6a3100-5fd6-11eb-831d-85e4fd275e5d.png)

Not sure where these values are coming from, but was only able to figure out the formatting of the setting by writing something random and then hovering over it

**Comment by mjbvz** [comment]
I believe these are the cross-file word based suggestions. Let me see if I can add a snippet or something to improve this

**Comment by mjbvz** [comment]
#115648 added a visual editor for this setting. I don't think there's a way to fix the json side of things here (although there is a default snippet when you first fill in this setting)

**Comment by mjbvz** [comment]
For verification, make sure you can use the settings UI to edit `workbench.externalUriOpeners`
