### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jagadeesh14** [microsoft/vscode#115106]
Issue Type: <b>Bug</b>

sfdx force:source:retrieve --json --loglevel fatal -m LightningComponentBundle:newTaskQuickAction
'\\vdifs\UEM_Profiles\jvuddamarri\Data\Desktop\dx'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
{
  "status": 1,
  "name": "RequiresProjectError",
  "message": "This command is required to run from within an SFDX project.",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "RequiresProjectError: This command is required to run from within an SFDX project.\n    at Function.create (C:\\Users\\jvuddamarri\\AppData\\Local\\sfdx\\client\\7.84.2-a2868a68d5\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:160:16)\n    at SourceRetrieveCommand.assignProject (C:\\Users\\jvuddamarri\\AppData\\Local\\sfdx\\client\\7.84.2-a2868a68d5\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:100:40)",
  "warnings": []

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (3 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|12.00GB (6.64GB free)|
|Process Argv|--crash-reporter-id 3ea231b8-ee97-48c5-ab08-cf5c2a749ad1|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
node-json-autocomplete|bhs|0.1.3
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.8.0
vscode-cli|pko|1.0.0
vscode-xml|red|0.14.0
salesforce-vscode-slds|sal|1.4.0
salesforcedx-vscode|sal|50.14.0
salesforcedx-vscode-apex|sal|50.14.0
salesforcedx-vscode-apex-debugger|sal|50.14.0
salesforcedx-vscode-apex-replay-debugger|sal|50.14.0
salesforcedx-vscode-core|sal|50.14.0
salesforcedx-vscode-lightning|sal|50.14.0
salesforcedx-vscode-lwc|sal|50.14.0
salesforcedx-vscode-visualforce|sal|50.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30244300
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600:30247031

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension please raise this with the authors of your Salesforce extension(s)
