### ISSUE TITLE
Open the correct settings tab

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#115158]
From https://github.com/microsoft/vscode-jupyter/issues/4512

An extension opens the settings UI to show a specific setting that works in desktop but fails on a remote (Codespaces in my case) as the tab defaults to the user setting:

## Desktop
![image](https://user-images.githubusercontent.com/35271042/105908112-b179f080-5fda-11eb-90f2-a4d76349abb2.png)

## Remote
![image](https://user-images.githubusercontent.com/35271042/105907980-8099bb80-5fda-11eb-85f0-586c0a979c7a.png)

We should either figure out what tab should be shown based on where the extension is installed or allow for the extension to specify a certain tab.

cc @rchiodo

**Comment by joyceerhl** [comment]
Related: https://github.com/microsoft/vscode/issues/102146

**Comment by misolori** [comment]
@joyceerhl thanks for the link, I'll close this one in favor of that one.
