### ISSUE TITLE
Vscode Insider 

### ISSUE THREAD

**Issue by uhlhosting** [microsoft/vscode#115187]
Version: 1.53.0-insider
Commit: ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57
Date: 2021-01-22T17:17:02.999Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. navigate to https://lottiefiles.com/plugins/vscode
2. scroll down and click the button Install plugin

I would expect that the new safari window, will add the module directly in VSCode, this is not the case, since the day I removed VSCode, and added Insider version, the linking from Browser and Application was lost. I checked several closed issues here reported by other users, yet there was vague replies from Microsoft, most of them other talk that maybe this is solved or not, is not solved in any ways. 

This works fine with VSCode, yet when adding VSCode Insider, it simply continues to use the VSCode linking.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/6324047/105946705-12033f00-6068-11eb-8a21-765a3674b6bf.png">

And again this is not a new issue, just that everytime I tried to report it, someone had something else to say, never an approach to solve this issue, or track it what is causing it.

The only possible way at the moment is to add this manually by adding -insider to above url.

vscode-insiders:extension/modulename

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by IllusionMH** [comment]
VS Code Insiders can't register `code:extension/...` handler otherwise it will break stable Code for those who have both installed.

I think it's up to website to provide alternative link for Insiders users.

**Comment by kieferrm** [comment]
As said, the lotti site needs to distinguish between VS Code and VS Code Insiders and show actions for both.

**Comment by kieferrm** [comment]
I forgot to point you to the actual url structure: https://code.visualstudio.com/api/references/activation-events#onUri.
