### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by Hishaam20** [microsoft/vscode#115196]
Issue Type: <b>Bug</b>

When trying to code, intellisense does not respond at all

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

**Comment by gjsjohnmurray** [comment]
Often an indication of a problem with an extension. Please use the new bisect command to find out.

Also tell us what language you are coding in.

**Comment by Hishaam20** [comment]
C#. Trying out unity scripts for coding a game
