### ISSUE TITLE
intelliSense stoped working on Typescript

### ISSUE THREAD

**Issue by adumesny** [microsoft/vscode#115123]
Issue Type: <b>Bug</b>

about a week ago Intellisense (mouse over tooltip, F12, code completion) stopped working for multiple Typescript projects I have.
I re-installed vscode, removed .vscode extension folder, re-install, rebooted - tried eveything and nothing worked.

Today I tried installing 1.53.0-insider and it has no issue - intellisense works as expected!
I will add my extensions back to the insider build and continue working... I couldn't find an older (using 1.52.1 now) build to revert to but found the next rev one.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.15GB free)|
|Process Argv|--crash-reporter-id 68aa4e19-cd52-400b-a9fa-936ac044a83a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30247032

```

</details>

**Comment by mjbvz** [comment]
If this works in insiders, then either the bug has already been fixed or you have extensions/settings in your VS Code stable install that are causing problems.

Please ;et us know if you see this in the insiders build with extensions disabled

**Comment by adumesny** [comment]
I had removed all extensions in both cases (and re-added them to insider which still works). Something about 1.51.1 or my versions (I download and re-installed after nuking the install folder and ~/.vscode folder) but there are some other resources (window's registry ?) as line indentation and minimap was off in 1.51.1 beased on ym prev settings, but defaulted to on in 1.52.0 insider.

Where are vscode things stored on windows 10 ? maybe I can nuke those and see where it breaks...

**Comment by mjbvz** [comment]
[Settings file location](https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations)

Did you configure one version to the use the workspace version of TypeScript?

**Comment by adumesny** [comment]
deleting Windows %APPDATA%\Code worked (tried just resetting user\settings.json and that didn't do it)

> Did you configure one version to the use the workspace version of TypeScript?

How do you do that ? can't recall...

**Comment by adumesny** [comment]
I find that if I delete `AppData\Roaming\Code\User\globalStorage\state.vscdb` then everything works again as expected! (I saved a copy in case it helps debug things).

I restored all my extensions, settings and folder from original 1.51.1 build I've been using, and just nuked that file above to re-create and all is good. it's like it got corrupted or something (640k, new one is for now ~100k)

**Comment by mjbvz** [comment]
I suspect you probably just configured VS Code to use a different version of TypeScript. See https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

This is not stored in user settings for security reasons. It is stored in the global state. After deleting the data, VS Code will instead use its bundled version of TypeScript
