### ISSUE TITLE
Tab wrap - add a setting for uniform tab sizing across all rows

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115132]
Testing #114827 & Similar to https://github.com/microsoft/vscode/issues/115052

In testing the new tab wrapping, it would be nice if there was a sizing mode that picked a uniform tab size -- so the tabs would all be aligned to the same boundaries. Similar to shrink, but shrink chooses to "shrink" rather than wrap.

I want something like this:

![image](https://user-images.githubusercontent.com/641685/105894808-adea6780-5fe2-11eb-86db-d1a59c01eb63.png)

But with all the tabs aligned

//cc @lszomoru

**Comment by patricio-ezequiel-hondagneu-roig** [comment]
I was about to propose the same feature. It would be really nice to have it.

**Comment by bpasero** [comment]
@eamodio can you please try how it behaves with latest out of sources, I pushed some fixes so that tabs would no longer evenly grow in a row, see https://github.com/microsoft/vscode/issues/113801#issuecomment-787809227

I do not fully understand what else is needed, maybe you can clarify.

**Comment by eamodio** [comment]
@bpasero sorry for the delay in getting back to you on this. The changes are better wrt the final row, but what I'm asking for here, is that all the tabs be the same size so that they align vertically.
