### ISSUE TITLE
Support any scheme

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#115165]
Testing #114962

The first time I tried this, I did:

```ts
context.subscriptions.push(vscode.window.registerExternalUriOpener(openerId, {
		canOpenExternalUri(uri: vscode.Uri) {
			return vscode.ExternalUriOpenerPriority.Preferred;
		},
		openExternalUri(resolveUri: vscode.Uri) {
			console.log(resolveUri.toString());
		}
	}, {
                // note this
		schemes: ['myextension'],
		label: 'Do the thing'
	}));
```

Note the scheme.

I then realized it only supported `http` and `https`. Why? Is there a technical reason? Supporting any arbitrary scheme makes the code for `canOpenExternalUri` much simpler because I can say anything with the scheme I care about, `myextension://` should be opened with my UriOpener.

If we only support `http` and `https`, we might as well just make that the default behavior so `schemes` doesn't have to be specified. Are there a lot of scenarios where someone would only want to handle `http` or only `https`?

**Comment by mjbvz** [comment]
This is for future proofing. The limit is (mostly) artificial and in the future we could allow extensions to handle other schemes, such as `file` or app specific schemes.

I agree it's a little ugly to have both `http` and `https`, but I like keeping it explicit and consistent. Also #115168 will help as it makes the supported schemes more obvious
