### ISSUE TITLE
File Creation dialog cuts off end of long path

### ISSUE THREAD

**Issue by zbs** [microsoft/vscode#115152]
[Screenshot](https://imgur.com/a/CyJbzev). (I can't inline because GitHub is having upload issues currently).

When I create a new file with CTRL + N and save, if the path is particularly long, the end of the path is cut off, which requires awkwardly using text selection to get to the end of the path. It would be great if the path were shifted as far to the left as possible.

**Comment by isidorn** [comment]
This is using the file picker quick pick thus forwarding to @alexr00
