### ISSUE TITLE
vscode.authencaition.session failed on remote container

### ISSUE THREAD

**Issue by weny-tang** [microsoft/vscode#115172]
- VSCode Version: lastest
- OS Version: windows

Steps to Reproduce:

1.open my workspace in remote container.
2.use toolkit login my microsoft account.

Does this issue occur when all extensions are disabled?: Yes

I create an vscode extension tookit, and wanna to open it in remote container.
I create the devcontainer files, and reopen the workspace in remote container successful.
when I login my microsoft account in toolkit using vscode.authentication.session, vscode popup a browser with localhost:port to redirect login page.
but web page redirect failed!
I did find any operation to get authN success.

**Comment by weny-tang** [comment]
Or any other alternative login methods  ?

**Comment by weny-tang** [comment]
@RMacfarlane any update?

**Comment by RMacfarlane** [comment]
@weny-tang Can you please include more details about what the "web page redirect failed" means? What is there error message?

**Comment by weny-tang** [comment]
once I click the

**Comment by weny-tang** [comment]
ok.
after upgrade my vscode to 1.52.1, this problem have resolved.
