### ISSUE TITLE
onnxruntime package crashes in extension without exception

### ISSUE THREAD

**Issue by skdeng** [microsoft/vscode#115185]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new extension
2. Install `onnxruntime` package
3. Load any ONNX model
4. Create a correct input to the model and modify the data type of one of the inputs to force an error
5. Run the model with the input
6. Expected behavior: Model execution fail and throws a catchable exception
7. Actual behavior: Extension crashes without any error or exception

**Running the same code above in node produces a catchable exception.**

After debugging and looking through onnxruntime source code, it looks like the native code fails at [ORT_ENFORCE](https://github.com/microsoft/onnxruntime/blob/afd7b8b3f751e7aedbea708282003c380084606a/include/onnxruntime/core/common/common.h#L180) which throws a C++ exception (which somehow does not get propagated back).

Does this issue occur when all extensions are disabled?: N/A

**Comment by kieferrm** [comment]
@skdeng what extension do you use? I.e. which one crashes in step 7?  This issue needs to go either to that extension or to https://github.com/Microsoft/onnxruntime in general. Thanks!
