### ISSUE TITLE
How to configure `onEnterRules` for language config?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11514]
I'm trying to add functionality to Dart Code that automatically inserts `/// ` for you if you're typing a comment; eg.:

```dart
/// this is a comment[<enter here>]
```

Should result in:

```dart
/// this is a comment
/// [cursor here]
```

There are some properties on the `LanguageConfiguration` interface that look like they're to support this (`onEnterRules`), but I've been playing around and been unable to make them work. I can't find any existing code that uses these, so I'm not entirely sure they're supposed to be used like this. If not, is there another way to achieve this?

I've noticed TypeScript automatically inserts ` * ` when I'm typing a multiline comment; but I can't find the code/config that's causing that.

An example of what I've tried in my language config:

```json
"onEnterRules": [
	{
		"beforeText": "/\/\/\/ /g",
		"action": {
			"indentAction": "None",
			"appendText": "/// "
		}
	}
]
```

**Comment by alexandrudima** [comment]
@DanTup 

example: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L163

for your use-case:

```
languages.setLanguageConfiguration(modeId, {
...
	onEnterRules: [
		{
			beforeText: /^\/\/\//,
			action: { indentAction: IndentAction.None, appendText: '/// ' }
		}
	]
...
});
```

The `onEnterRules` are not at this point read from the language configuration file. We need to figure out how to serialize/deserialize a regex without ambiguity yet from JSON.

**Comment by DanTup** [comment]
@alexandrudima Excellent, thank you! I did search GH for `onEnterRules` trying to find it in code (suspecting a regex json issue) and didn't find it; hwoever I can see loads now, so maybe I pasted it badly! :(

Closing this as I think it's answered then :+1:
