### ISSUE TITLE
Error when searching in open  user settings.json

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#115176]
Testing #114970

With Search only in Open Editors enabled, open the user settings.json and try to search.

![image](https://user-images.githubusercontent.com/12818376/105939655-84473580-600e-11eb-980e-c15b4bce84c5.png)

Doesn't seem to happen with an open workspace settings.json

**Comment by gregvanl** [comment]
Seems to be a problem for any file under my user AppData folder. Also repros for keybindings.json

![image](https://user-images.githubusercontent.com/12818376/105940038-38e15700-600f-11eb-8862-b194dbed263e.png)

**Comment by gregvanl** [comment]
Seems like the feature needs the files to be under the workspace root. Adding loose files from outside the workspace break it.

**Comment by JacksonKearl** [comment]
Thanks, this should be fixed now, it won't error but it also wont provide results for the user data files yet (https://github.com/microsoft/vscode/issues/114795#issuecomment-767250781). Results should be provided for free standing files though.

![image](https://user-images.githubusercontent.com/8586769/106036328-0aed2880-608a-11eb-9e21-ce337bd1eb45.png)
