### ISSUE TITLE
Recent Folders should not be case sensitive in Windows

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#1151]
Since Windows is not case sensitive_ for Files and Folders, the recent folders should also not to be.

If you open a folder in Code via command line, with different case, it adds a new entry for each one. It also maintain a _folder state_ (like the files that are opened in that folder) different for each entry.

Opening **Code** with different case:

![recent_folders_console_call](https://cloud.githubusercontent.com/assets/3781424/11701976/0fed331c-9eba-11e5-80e8-ba9d4a3990fb.png)

It adds 3 different entries in **Menu**

![recent_folders_menu](https://cloud.githubusercontent.com/assets/3781424/11702027/5cbbf94e-9eba-11e5-8bbf-41e5c7b01481.png)

And also in **Command Palette**:

![recent_folders_command_palette](https://cloud.githubusercontent.com/assets/3781424/11702042/7ab8a5b4-9eba-11e5-9c57-de6f5fd656e3.png)

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
Fixed this issue, but there is still the problem with workspace UI state not being found if the case differs, filed https://github.com/Microsoft/vscode/issues/1162

**Comment by alexandrudima** [comment]
@bpasero Opening a folder from the command line doesn't work for me.

![image](https://cloud.githubusercontent.com/assets/5047891/11844468/4245c004-a40f-11e5-8089-b4a4c9f53bbc.png)

When I run that I get a new window without any folder opened.

**Comment by alexandrudima** [comment]
I was reusing a command prompt where I ran code.bat out of development. When using a fresh command prompt I could open folders and verify the issue is fixed
