### ISSUE TITLE
Not sure how to add a working function breakpoint

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115115]
Testing #114345

I'm trying to add function breakpoints but they get greyed out.
When I hover over them, it says that they aren't supported by the debug type I have.

![greyed-out-function](https://user-images.githubusercontent.com/7199958/105888805-4d4b3280-5fc2-11eb-8033-abbe6049c88c.PNG)

Here's my launch config:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\index.js"
        }
    ]
}
```

**Comment by isidorn** [comment]
This is controlled by the js-debug, thus forwarding to @connor4312 
I believe the message is correct and that js-debug simply does not support them and this is expected behavior, however leaving this up to Connor

**Comment by connor4312** [comment]
That's right. There's not functionality that V8 exposes in its debug protocol for us to have function breakpoints, sadly.
