### ISSUE TITLE
Revisting test states

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115101]
Currently the model of test states works great to show the current state of thing, but browsing and navigating test results gets more challenging. The responsibility to persist the most recent test result is on the extension. For example, if I run tests in a document, close the document, and reopen it (creating a new test subscription) the extension needs to re-hydrate the state of tests at that time. My workaround for this was to expose the test results to the extension, but this is a poor solution.

https://github.com/microsoft/vscode/blob/b7e87c1bf2780f6b9338721369e422dcb398224d/src/vs/vscode.proposed.d.ts#L2084-L2101

So, it appears the idea of tests containing their state is flawed.

Instead, I think it is reasonable to say that test states only change during a test run. An approach to this is to modify the signature to `runTests(run: TestRun, cancellationToken)`, where `TestRun` is:

```ts
/**
 * Class given to `TestProvider.runTests`
 */
export class TestRun<T extends TestItem = TestItem> {
	// existing properties of TestRunOptions
	tests: T[];
	debug: boolean;

	/**
	 * Updates the state of the test in the run. By default, all tests involved
	 * in the run will have a "queued" state until they are updated by this method.
	 */
	update(test: T, state: TestState): void;
}
```

...and then there would be no `state` on TestItems themselves. This is closer to the API that @hbenl has in the test explorer API. TestItems are purely metadata about the location and runnability of tests, and VS Code handles the display and persistence of test states.

Something I like about this API is that it opens the door to streaming output (as @matepak requested in https://github.com/microsoft/vscode/issues/107467#issuecomment-766085288) via some `appendOutput(test: T, contents: string | TestMessage)` method, as well as extra information like coverage later on. It also removes the awkward event emitter loopback I mentioned in https://github.com/microsoft/vscode/issues/107467#issuecomment-730706370

One use case that the current API provides that this change does not is the ability to open test results without previously running tests. For that we can introduce some a new optional `provideTestResults()` which can return a result summary.

**Comment by hbenl** [comment]
> Instead, I think it is reasonable to say that test states only change during a test run.

There are some important exceptions: when tests are loaded, their state may be set to Errored (that was the original purpose of that state in my Test Explorer extension: to indicate an error other than a regular test failure, including the inability to load it) and it should be possible for TestProviders to set a test's state to Unset at any time (to indicate that the state is outdated).

**Comment by connor4312** [comment]
I added an "onDidInvalidateTest" event that providers can use for this (on the hierarchy). I'll think about error states as part of https://github.com/microsoft/vscode/issues/115089

**Comment by matepek** [comment]
Next to the `errored` state the `skipped` state is also should be able to be set. ⚠️

## And there is another use case which I'm not sure how will work:

Quick intro: In case of C++ the detection of new, deleted and changed tests depends on the detection of the change of the executable. I have half a dozen scenario when this changes is not detected. 

Let's say that there is an executable which contains tests: `a`, `b`, `c` but my extension originally detected only `a` and `b`.
When the user run all the tests in the executable the extension will encounter a new test case: `c`.
This test case should be added and the state also should be reported at some point. 

In this version of the API what I can do is that **during the** `runTests`:
- adding the new test case `c`
- sending a `onDidChangeTest` event about the parent
- call `setState` for `c`

Will this work?

## Other questions

Can the user trigger another `runTests` before the previous finishes? It makes sense to do. I can just add up the new test to a queue.

## Notes

`interface TestRun` might could contain the cancellation-token for simpler API. Now I have to pass everything anyway on the stack if I want to report states.

`TestMessageSeverity.Error` I guess the term is coming from the `UI` but in case of tests it sounds a bit weird to me. How about `Failure`?

**Comment by connor4312** [comment]
> Next to the errored state the skipped state is also should be able to be set

I'm not sure I agree with this. In my tests I can have code that skips a certain test. I think this is fine and doesn't need representation in the UI until I run the test. I may actually have my code skip on certain test _runs_, for example, if I skip slow tests in specific runs. In this case "skipped" state is definitely associated with a run rather than with the embodiment in code.

>Let's say that there is an executable which contains tests: a, b, c but my extension originally detected only a and b. When the user run all the tests in the executable the extension will encounter a new test case: c.

That is something that @DonJayamanne brought up with Python as well. I do not recall off the top of my head if it's the case, but I will make sure that the steps you laid out works ^ i.e. that tree modifications are applied before state updates are set.

> Can the user trigger another runTests before the previous finishes? It makes sense to do. I can just add up the new test to a queue.

Yes, this is possible. If your runner doesn't support this then a queue is an appropriate mechanism.

> interface TestRun might could contain the cancellation-token for simpler API. Now I have to pass everything anyway on the stack if I want to report states.

I understand your point, but the cancellation token as the last parameter is a convention taken throughout the vscode extension API (borrowed from C# where this is also the practice) so this is probably not going to change.

> TestMessageSeverity.Error I guess the term is coming from the UI but in case of tests it sounds a bit weird to me. How about Failure?

There's both... I copied this from Holger's runner, but since we have a separate notion of results and load errors this state _could_ be removed. However some extension authors may still want to be able to differentiate errors in setup/teardown, for instance, with test failures.

I will probably remove it for now and see what feedback we get. It's easy to add later, but impossible to remove if it hits stable.

**Comment by matepek** [comment]
> Next to the errored state the skipped state is also should be able to be set

Let's put it this way. The fact that some tests are skipped or not can be determined at enumeration/test-listing time. I think the users would appreciate to see this information before running any tests.

> TestMessageSeverity.Error 

Hm, I didn't see any `Failure`:

```
  export enum TestMessageSeverity {
    Error = 0,
    Warning = 1,
    Information = 2,
    Hint = 3,
  }
```

I'm not talking about `TestRunState`. What am I missing?
