### ISSUE TITLE
Tab wrap - tab right border color changed after pin

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#115122]
Testing #114827

After having tabs wrapped, the tab right border color is correct 

![image](https://user-images.githubusercontent.com/876920/105892316-88e7fb80-5fc6-11eb-8037-700d53da91a0.png)

Sometimes when I pin an tab, the right border color changed, unpinning the tab will restore the color

![image](https://user-images.githubusercontent.com/876920/105892291-7f5e9380-5fc6-11eb-8e49-d06add246089.png)

**Comment by bpasero** [comment]
This is actually working as intended, we maintain a `tab.lastPinnedBorder` color to highlight where the last pinned tab is at to distinguish from others:

![image](https://user-images.githubusercontent.com/900690/105969036-163f5480-6088-11eb-9cf2-c8182e09f4e9.png)

I am open for suggestions wether we should change this or even not do that when tabs wrap.

//cc @SneakyFish5 @misolori

**Comment by misolori** [comment]
I'm open to hide it by default or use the same border color from tabs so they blend in.

**Comment by bpasero** [comment]
I will wait for user feedback on this before making an action. I think having a separate border color for the last pinned tab is still valid even in this case.
