### ISSUE TITLE
Exception breakpoints don't show up sometimes

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#115121]
Testing #114345

Clone: https://github.com/microsoft/vscode-mock-debug
Open it and run the mock debug extension.

Expected the Exception breakpoints to show up under breakpoints.

Actual (nothing there):
![image](https://user-images.githubusercontent.com/2644648/105892054-2ee73600-5fc6-11eb-8705-ff9b4f6aa5d7.png)

I briefly repro'd this with the JS debugger when I got the nightly but now I don't see this issue anymore.

#### Workaround

Run a debug session, they show up:

![image](https://user-images.githubusercontent.com/2644648/105892312-884f6500-5fc6-11eb-886b-b60cd0b1f3ed.png)

After I reload the window, they disappear again.

**Comment by isidorn** [comment]
@TylerLeonhardt great catch, thanks for filling good issues

**Comment by connor4312** [comment]
Please verify tomorrow if you can, not sure how 'sometimes' the 'sometimes' is 🙂

**Comment by isidorn** [comment]
I suggest to verify with mock-debug since for that sometimes = always

**Comment by TylerLeonhardt** [comment]
@isidorn I still don't see them:

![image](https://user-images.githubusercontent.com/2644648/106174556-05571780-614a-11eb-9ab7-ccc35b28e0b8.png)


They don't show up until after the first debug session.

**Comment by isidorn** [comment]
That is expected. Exception breakpoints are coming from the debug adapter. Thus we only know them on the very first session that you start.
However if you do not see them after you have debugged in the workspace than that is an issue, since we should store them in storage. If this is the case let me know and I can reopen. Thanks

**Comment by TylerLeonhardt** [comment]
Thanks for the clarification! This bug is fixed.

**Comment by isidorn** [comment]
Great, adding `verified` label
