### ISSUE TITLE
Is there a list of all stable commands we can call?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11519]
In the help for `hide` on a `TextEditor` it says:

```text
@deprecated **This method is deprecated.**
Use the command 'workbench.action.closeActiveEditor' instead.
```

However `closeActiveEditor` is not listed on the [Complex Commands API](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) page. Is this just an oversight, or is that page not a full list of commands we're allowed to call?

**Comment by jrieken** [comment]
We have the following
* API commands with defined arguments and return types: https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands
* the `commands.getCommand(true)` to get a list of all known (not internal) commands https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3285, or
* generally everything that shows up when configuring keybindings
