### ISSUE TITLE
Highlight Bug in C++

### ISSUE THREAD

**Issue by AzusaCat1111** [microsoft/vscode#115173]
Issue Type: <b>Bug</b>

When you write inline comments which have a '>' and there is an unmatched '<'  in the same line, the highlight of the comment after '>' will disappear.
Example:
```cpp
for(int i=1;i<=n;i++)//(0,0)->(n,m)
```

You can find that the highlight of `(n,m)` is white instead of green

![P{OXFI7LBT%LOIL%WRT9STO](https://user-images.githubusercontent.com/71953098/105937097-d7150180-608f-11eb-9e5c-885fd23ded24.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.71GB (1.23GB free)|
|Process Argv|--crash-reporter-id 53522c61-3303-48f1-b98f-bd10408a7bdd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-standardjs|che|1.4.0
code-runner|for|0.11.2
marp-vscode|mar|0.17.0
vscode-language-pack-zh-hans|MS-|1.52.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0-insiders2
prettier-standard-vscode|num|0.8.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
swig-tpl|zha|0.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30247033

```

</details>

**Comment by alexr00** [comment]
Thanks for the clear repro! We get our C++ syntax highlighting grammar from https://github.com/jeff-hykin/cpp-textmate-grammar/. I've created an issue there: https://github.com/jeff-hykin/cpp-textmate-grammar/issues/536
