### ISSUE TITLE
Notebook cell selection color changes when mouseup occurs outside the editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115127]
Testing #114969

Not sure why this would happen, maybe monaco doesn't think it's focused?

![recording (48)](https://user-images.githubusercontent.com/2193314/105893769-57702f80-5fc8-11eb-9729-4ad61fc145c2.gif)

**Comment by rebornix** [comment]
Weird, it's very likely the textarea is not focused

**Comment by rebornix** [comment]
We have fixes for the cell focus recently and I'm not able to reproduce this in latest Insiders. Closing for now.
