### ISSUE TITLE
Remote terminal local echo breaks terminal wrapping

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#115164]
When I have local echo enabled, this happens when wrapping to scroll. Still wraps when it doesn't need to scroll.

If I disable local echo, it works as expected

![Jan-26-2021 15-44-27](https://user-images.githubusercontent.com/323878/105921194-674e3a80-5fed-11eb-8cb7-db671ccc5bd8.gif)

**Comment by connor4312** [comment]
thanks for the issue. I see this sometimes when copy/pasting long lines in. Doesn't happen on powershell, but does on bash or zsh
