### ISSUE TITLE
Hex Editor: original untitled file editor is not closed when opening in the Hex Editor

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#115182]
Testing #114952

1. Create new untitled file and add some text.
2. Hex Editor: Open File

The original untitled file is left open and changes in the Hex Editor are not reflected in that original file.

![image](https://user-images.githubusercontent.com/12818376/105943467-30d8e580-6016-11eb-8a62-965395977f04.png)

**Comment by lramos15** [comment]
This will be fixed by #114947
