### ISSUE TITLE
Notebook outline is using # characters outside of markdown headings

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115205]
Testing #114902

Have a markdown cell with the following content:
![image](https://user-images.githubusercontent.com/5047891/105972407-df6b3d80-608b-11eb-9cf4-35f28f6cd317.png)

Create a comment in the python fenced block by typing `#`.

Observe how the outline is confused by this:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105972600-12153600-608c-11eb-9226-8074e5cd141e.gif)

**Comment by alexdima** [comment]
A similar example is:
```
  #asd # asd
```

which is not interpreted as a title by markdown itself, but is interpreted as a title by the outline.

**Comment by alexdima** [comment]
Another example is a `#` without a space after it:
```
#asd
```
which is not a markdown title, but is accepted as a title by the outline.

**Comment by jrieken** [comment]
@rebornix folding will have the same problem
