### ISSUE TITLE
[folding] collapse block comment shortcut

### ISSUE THREAD

**Issue by jesperstarkar** [Microsoft/vscode#11524]
When writing a lot of documentation pr. method, and for each variant when overloading methods, you end up with a tonne of green comment blocks and hardly readable code after a just a short while.

I would love a shortcut that collapses all multiline comments in the editor.

**Comment by surajreddy** [comment]
It would be great if large sections of comments can be folded. Atom supports this by default:

<details>
<summary>Before Folding</summary>

![cancancan 2017-01-20 10-58-29](https://cloud.githubusercontent.com/assets/80290/22155991/696bf3fc-deff-11e6-8934-7cf150303e3a.png)
</details>

<details>
<summary>After Folding</summary>

![cancancan 2017-01-20 10-59-02](https://cloud.githubusercontent.com/assets/80290/22156009/7ad9de56-deff-11e6-8d40-4ab7b4f45cfa.png)
</details>

---

This is for the file https://github.com/CanCanCommunity/cancancan/blob/develop/lib/cancan/controller_additions.rb

**Comment by ericrovtar** [comment]
I'd appreciate this feature as well. It'd be great for it to apply to all kinds of comments, like multiple line comments (// or #).

**Comment by Skatterbrainz** [comment]
Just add folding for <# ... #> and /* ... */  comment blocks would be very helpful

**Comment by AdamLeBlanc** [comment]
+1 +99 = +100. Would be extremely useful for working on projects littered with doc comments that make code hard to read.

**Comment by SheikhThingsUp** [comment]
It would  be good to implement this as a generic feature where users can add/remove symbols to start/end of foldable region. This will allow for different commenting styles to be foldable, such as Perl POD like it is in vim. 
<img width="505" alt="screen shot 2017-09-28 at 08 42 26" src="https://user-images.githubusercontent.com/1805700/30941489-05210b36-a429-11e7-9968-ee0f9c659889.png">
