### ISSUE TITLE
command + L not working.

### ISSUE THREAD

**Issue by g0lf-code** [microsoft/vscode#115296]
when pressed "cmd+L" button, it used to select line/s.
ive checked in keybindings also, no changes have been made.
but i dont know why it says "waiting for the next chord : ", when theres no bindings like that whatsoever.
its happening only in mac, on windows "CTRL+L" works fine.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `cmd+L`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`cmd+L`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by g0lf-code** [comment]
[2021-01-28 19:58:03.548] [renderer1] [info] [KeybindingService]: /
Received keydown event - modifiers: [meta], code: MetaRight, keyCode: 93,
key: Meta
[2021-01-28 19:58:03.548] [renderer1] [info] [KeybindingService]: |
Converted keydown event - modifiers: [meta], code: MetaRight, keyCode: 57 (
'Meta')
[2021-01-28 19:58:03.548] [renderer1] [info] [KeybindingService]: \
Keyboard event cannot be dispatched.
[2021-01-28 19:58:03.829] [renderer1] [info] [KeybindingService]: /
Received keydown event - modifiers: [meta], code: KeyL, keyCode: 76, key: l
[2021-01-28 19:58:03.829] [renderer1] [info] [KeybindingService]: |
Converted keydown event - modifiers: [meta], code: KeyL, keyCode: 42 ('L')
[2021-01-28 19:58:03.829] [renderer1] [info] [KeybindingService]: |
Resolving meta+[KeyL]
[2021-01-28 19:58:03.829] [renderer1] [info] [KeybindingService]: \ From 3
keybinding entries, matched chord, when: editorTextFocus, source: user
extension ritwickdey.LiveServer.

i've only pressed "cmd+L"

>

**Comment by alexdima** [comment]
```
/ Received keydown event - modifiers: [meta], code: MetaRight, keyCode: 93, key: Meta
| Converted keydown event - modifiers: [meta], code: MetaRight, keyCode: 57 ('Meta')
\ Keyboard event cannot be dispatched.
/ Received keydown event - modifiers: [meta], code: KeyL, keyCode: 76, key: l
| Converted keydown event - modifiers: [meta], code: KeyL, keyCode: 42 ('L')
| Resolving meta+[KeyL]
\ From 3 keybinding entries, matched chord, when: editorTextFocus, source: user extension ritwickdey.LiveServer.
```

It looks like vscode receives the keybinding and that it dispatches to a chord that is contributed by the extension `ritwickdey.LiveServer`. You can disable that extension or remove the keybinding that it contributes for `cmd+L`.

**Comment by g0lf-code** [comment]
Thanx mate🤘🏻
