### ISSUE TITLE
Recommendation for a installed extension

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115294]
- have a dev container with docker installed on remote but not locally
- close the window and open it from the recent history again

![image](https://user-images.githubusercontent.com/6461412/106114791-43573a00-6150-11eb-93ab-03ffc8fd87eb.png)

**Comment by aeschli** [comment]
My guess is that the recommendation is for local

**Comment by sandy081** [comment]
Yes, Exe based recommendations should not be shown in remote window.
