### ISSUE TITLE
Can't scroll on Terminal output

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#11525]
- VSCode Version: 1.4.0
- OS Version: macOS Sierra Beta 7 (But should do the same on any macOS/OS X version)

Steps to Reproduce:

1. Open Terminal at bottom.
2. Run a command that will do a long output (At least more than the terminal height).
3. Try to scroll up.

**Comment by kube** [comment]
Scroll seems to work when on a program that has not closed stdout.
**e.g:** `webpack-dev-server` output is scrollable while running.

**Comment by Treri** [comment]
Are you using oh-my-zsh?

Is your problem the same with #10575 ?

**Comment by Jakobud** [comment]
OSX 10.10.5 here. I am able to scroll up and down the integrated terminal just fine. Maybe you shouldn't be reporting bugs while using beta OS software...

**Comment by kube** [comment]
Yeah sorry for not specifying it, I'm using `oh-my-zsh` with `antigen`.
I disabled antigen to try, and scroll worked fine.

I also modified `oh-my-zsh` `lib/key-bindings.zsh` as specified in https://github.com/Microsoft/vscode/issues/8219#issuecomment-239651392 and it worked well too.

So problem seems to come from this line:
`echoti smkx`

**Comment by Treri** [comment]
Yes.
But I do not know why zsh's application keypad mode will turn off vscode scrollbar and what's the relation between zsh's application keypad mode and vscode terminal's turn on/off.

**Comment by Tyriar** [comment]
Duplicate #7817

@Treri the scroll bar is turned off when application keypad mode is entered, if there is a better way of determining when the scroll bar should be disabled you should create an issue against [xterm.js](https://github.com/sourcelair/xterm.js). Currently the scrollbar works on the full buffer which doesn't change when an application such as vim is entered so the scrollbar would look strange.
