### ISSUE TITLE
spaces:4  not work

### ISSUE THREAD

**Issue by yangyuke001** [microsoft/vscode#115285]
- VSCode Version:1.52.1
- OS Version:ubuntu18.04

Steps to Reproduce:

my vscode content like this:

![2021-01-28 14-21-56 的屏幕截图](https://user-images.githubusercontent.com/27425366/106099133-26812d80-6175-11eb-96d0-547bb346d0f8.png)

the Spaces:4 setted
Anyone konwns?thanks!

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kieferrm** [comment]
\extPython
