### ISSUE TITLE
Improve label 'Existing Tunnels' 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115220]
Testing #114532

Have a dev container with an appPort defined. 
![image](https://user-images.githubusercontent.com/6461412/105985443-c074a780-609b-11eb-8960-53d250e86281.png)

The ports views shows a list of ports and the forwards to a local port. Some ports where detected, some where from previous sessions (see #115216).

The `Existing Tunnels` node doesn't fit in that. `3000 -> 127.0.0.1:3000` looks like one of the ports above, but now it's about tunnels. Maybe it would also use 'Ports'? 
Also 'Existing' is strange as in fact there's no server running on 3000

Maybe better 'Configured ports'? Or even 'Container app ports' ?

**Comment by alexr00** [comment]
How does "Ports from Extensions"? Or, "Ports from Remote Containers"/"Ports from Remote SSH" (use the name of the extension)?

**Comment by aeschli** [comment]
Not much clearer... `Predefined ports` ?

Does it need it's own category node? It could just be a n entry in the ports list but you can change the local port. When editing, there could be a message 'The tunnel is established by the ${remoteHostName} extension and can be modified here.`

**Comment by alexr00** [comment]
I'd like to simply leave the actions that don't work on existing tunnels off. I think that's the best practice. Which means that there's no opportunity to show why you can't edit the tunnel.  Existing tunnels also don't get the x to close the tunnel.

I like `Predefined Ports`. @roblourens what do you think of renaming "Existing Tunnels" to "Predefined Ports" to make the language more consistent? I know you have seen that section before, so I'd like to get your opinion.

**Comment by aeschli** [comment]
You could show the extra information in the hover. The advantage is that it can be more verbose than a node label. That said, it is generic and will always be hard to understand. May the resolver could give a info string that explains where the forwarding comes from. ('devcontainer.json...`). Sure that's that delux solution.

**Comment by roblourens** [comment]
I like having them in their own node too, they are managed totally separately from other forwards. I'm not crazy about "predefined", I think I prefer "existing" over that. I do like including the extension name

**Comment by roblourens** [comment]
Compromise, "preexisting" 😁

**Comment by alexr00** [comment]
Is "Static" too overloaded a term here? "Static Ports" accurately describes that they aren't modifiable.

**Comment by roblourens** [comment]
I like that, I also like referring to "Tunnels" or "port forwards" over just "ports"

**Comment by alexr00** [comment]
Going with "Static Ports" then. We don't use "Tunnels" anywhere in the UI so for consistency I'm avoiding it now.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/bd20a720fba05f87ddb53c11c6af66936fd88a55

**Comment by alexr00** [comment]
For verifier: This text is now in the "Origin" column of the Ports view.

**Comment by aeschli** [comment]
Good solution with the new table view!
