### ISSUE TITLE
Property 'cwd' does not exist on type TerminalOptions

### ISSUE THREAD

**Issue by alor-pretatma** [microsoft/vscode#115299]
Hey, I did not want to hide the message. I need to get the terminals cwd. But this is returning undefined. Why are you just ignoring the problem instead of solving it?
And shouldn't you wait  at least  a day for my response?
_Originally posted by @alor-pretatma in https://github.com/microsoft/vscode/issues/114858#issuecomment-768907334_

**Comment by Tyriar** [comment]
Answered in the original issue
