### ISSUE TITLE
Breadcrumbs shows outline from wrong other notebook document

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115210]
Testing #114902

* open `.vscode/notebooks/grooming.github-issues`
* click in second query and press alt+z
* open `.vscode/notebooks/grooming-delta.github-issues`
* switch between files, sometimes it reproduces immediately, sometimes after a couple of switches
* observe that the breadcrumbs show the data from the other editor

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105978413-cca83700-6092-11eb-8704-71eb1024bc7c.gif)

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"notebook"+label%3A"outline"

**Comment by jrieken** [comment]
Yeah, quite embarrassing. But in my define this only happens when using tabs. Pushed a fix this morning
