### ISSUE TITLE
Expand indicator appears in Outline for leaf nodes

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115219]
Testing #114902

* open `src/vs/editor/browser/view/viewImpl.ts`
* switch to `.vscode/notebooks/grooming-delta.github-issues`
* observe that some of the leaf nodes have a twisty indicator:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105986106-ba32fb00-609c-11eb-98fc-8718eb073c31.gif)

**Comment by jrieken** [comment]
Hm... when editors change I dispose the current outline tree and create a new tree...

**Comment by joaomoreno** [comment]
Caused by https://github.com/microsoft/vscode/commit/fe175afdb80bd7a28caae83028e7440b45698007

**Comment by joaomoreno** [comment]
To repro, make sure you reload when the Outline has enough height for ~15-20 rows.
