### ISSUE TITLE
Terminal does not set the USER environment breaking cross-compiled Go tools

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode#115288]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Open VSCode on Mac
2. View -> Terminal
3. A new terminal opens
4. Run `echo $USER`

The `USER` environment variable is not set in the VSCode terminal, however in the standard Mac Terminal it is set. When I compare the output of `env` in the VSCode terminal and the Mac Terminal app the outputs are much the same except that the `USER` environment variable is present in Mac Terminal and set appropriately to the username of the signed in user, but VSCode does not have that.

Does this issue occur when all extensions are disabled?: Yes

This impacts tools built with Go that were cross-compiled for Mac, which is common. Go's [`user.Current()`](https://golang.org/pkg/os/user/#Current) function loads information about the current user and when cross compilation is used it relies on the presence of common environment variables like `USER` to determine the username of the currently logged in user. If a cross-compiled tool that relies on `user.Current` is run inside VSCode's terminal it will get the error:
```
user: Current requires cgo or $USER set in environment
```

Mac Terminal and terminals in other unix and linux based operating systems often set the USER environment variable, and tools and scripts often rely on it. It is inconvenient and unexpected that VSCode's Terminal does not.

**Comment by leighmcculloch** [comment]
This problem also occurs inside VSCode's Remote, which I'm not sure if it is a separate issue or related, so I opened microsoft/vscode-remote-release#5370.

**Comment by Tyriar** [comment]
Do you have `inheritEnv` set in your settings.json? We don't remove `$USER` from the environment. Also we changed the `inheritEnv` recently so update vscode if you haven't.

**Comment by leighmcculloch** [comment]
It appears this problem is fixed in the local terminal in v1.58.2, as since my last update the `USER` env var is now set in the VSCode terminal window. If nothing changed in VSCode for this possibly something changed in my system that impacted this.

**Comment by leighmcculloch** [comment]
@Tyriar It does appear I have `inheritEnv` set to `false` in my settings.json. I'm not sure why tbh, I don't remember setting it intentionally.
