### ISSUE TITLE
encoding doesn't work with ctrl+o on remote ssh

### ISSUE THREAD

**Issue by szakrzewski98** [microsoft/vscode#115298]
Issue Type: <b>Bug</b>

I have my settings.json for all of workspaces the same.  To encode all files the same
"files.encoding": "iso88592"

1. work on remote ssh
2. try to open file from local by ctrl+o ctrl+o
3. open file from local
4. encoding is not right as I set in settings.json

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

**Comment by bpasero** [comment]
@szakrzewski98 this is intentional, if you open a file that is not inside your workspace, the workspace settings will not apply.

**Comment by szakrzewski98** [comment]
@bpasero so why settings are applied when I open local file without using shortcuts? File -> Open File -> Show Local, it works, but still ctrl+o ctrl+o doesnt work

**Comment by bpasero** [comment]
@szakrzewski98 I cannot explain that, are you sure in both cases you open the exact same file? Do they have the same paths?

**Comment by szakrzewski98** [comment]
@bpasero Paths are the same. Other settings are ok when I open it with shortcuts, only encoding is set to windows1252 instead of iso88592

**Comment by bpasero** [comment]
@szakrzewski98 can you show a screencast or video of this. Try opening once via menu and once via keybindings.
