### ISSUE TITLE
Parameter hints persists when changing view to Settings

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#115265]
- VSCode Version: 1.53.0-insiders
- OS Version: Win 10 1909

Steps to Reproduce:

1. Create a new Notebook using the command palette command: `Jupyter: Create New Blank Notebook`
2. Create some dummy code where some sort of info dialog pops up
3. While dialog is open click on Settings gear and see that dialog is still open

![recording (7)](https://user-images.githubusercontent.com/12758612/106049491-011ff100-609b-11eb-8f09-5d15c6fd5d90.gif)

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
I cannot reproduce. @tanhakabir is the the new native notebooks or pythons custom notebooks?

**Comment by tanhakabir** [comment]
@jrieken using the Jupyter notebook on insiders which I believe uses the native notebooks?

**Comment by jrieken** [comment]
This is signature help and reproduces also outside of notebooks

* open a TS file
* trigger signature help
* focus the SCM view
* 😕 signature help still shows

**Comment by jrieken** [comment]
@mjbvz I have pushed a change that cancels parameter hints when the editor blurs
