### ISSUE TITLE
Sugestion on typing

### ISSUE THREAD

**Issue by evandrodenzin** [microsoft/vscode#115242]
Issue Type: <b>Feature Request</b>

I would like to see suggestions of file names on directory to complete while I am typing the code. There are some extension for this? For example: when I type this line, <a href="transparencia/dirhumanos/prestacao...", the Code should show  me the files in the local folder...
Tks

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

**Comment by kieferrm** [comment]
![image](https://user-images.githubusercontent.com/4674940/106344473-e39b8480-625e-11eb-92ae-2cc64bd85da8.png)
