### ISSUE TITLE
Multi Cursor Not Working

### ISSUE THREAD

**Issue by Princejaiswal986** [microsoft/vscode#115222]
Issue Type: <b>Bug</b>

My multi cursor is not working , please fix it . When i press  control+Alt+Uparrow . It doesn't Work

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (1.11GB free)|
|Process Argv|--crash-reporter-id feeb845f-eb3b-485f-ae16-f16067c77bad|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
theme-monokai-pro-vscode|mon|1.1.18
vsliveshare|ms-|1.0.3577
material-icon-theme|PKi|4.5.0
java|red|0.74.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Control+Alt+Uparrow`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`Control+Alt+Uparrow`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by Princejaiswal986** [comment]
Thank you it worked
