### ISSUE TITLE
Notebook outline ignores markdown headings 

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115200]
Testing #114902

* open `.vscode/notebooks/inbox.github-issues`
* observe that "Inbox Tracking" is not present in the outline, even if it is a heading

![image](https://user-images.githubusercontent.com/5047891/105964022-f9078780-6081-11eb-9395-1c03fa7e7a11.png)

**Comment by jrieken** [comment]
That's actually the current designed behaviour for outline and folding (I copied from folding). The rule is the a there is only one entry per cell and that entry is the strongest heading. Unsure why folding is doing that (likely because folding works on a per-cell level) and if outline should deviate from that

**Comment by alexdima** [comment]
Just as a note, there is also folding inside the editor and the one inside the editor recognizes the heading:

<img src="https://user-images.githubusercontent.com/5047891/105986293-05e5a480-609d-11eb-83d8-ae4589ddf725.png" alt="image" width="250">

**Comment by gjsjohnmurray** [comment]
Maybe my comment https://github.com/microsoft/vscode/issues/114902#issuecomment-766805790 and @jrieken's response are relevant to this.

**Comment by jrieken** [comment]
What has kept us from doing this was the fact that you cannot differentiate between offsets in rendered markdown. You can have a blurb of many lines with many heading. They can all show in the outline but selecting them will always reveal the same element, unless we switch the markdown view into edit mode (like search does)

**Comment by jrieken** [comment]
I have pushed that makes notebook outline create an entry per heading. I like how it follows a simpler logic. Tho, the active element (outline and breadcrumbs) will be the first entry for a cell.

<img width="787" alt="Screenshot 2021-03-01 at 14 59 25" src="https://user-images.githubusercontent.com/1794099/109507159-b846c800-7a9e-11eb-9a7d-7f73b7e39138.png">
