### ISSUE TITLE
Auto forwarded ports shouldn't be restored

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115216]
Testing #114532

Sorry if this has been discussed, feel free to close if this is all as designed.

When testing the ports view in a dev container, I start servers on various ports and see them automatically detected and show up in the ports view. When stopping the server, the port goes away. That's a great user experience. 

However, when shutting down the container and reopen it (e.g by saying `Rebuild Container`) I find that the ports view restores ports from the former session.

I'm always puzzled by that and start to check out if there's maybe already servers running, but there aren''t. So I start cleaning up the ports view manually by removing all old ports.

IMO automatically detected ports should not shown unless they are detected again.

**Comment by alexr00** [comment]
I agree, we should only restore ports that are not auto forwarded.
