### ISSUE TITLE
resources/server/test/test-web-integration.sh: No such file or directory

### ISSUE THREAD

**Issue by arjaiswa** [microsoft/vscode#115235]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Run test of browser. vscode>test>integration>browser
2. As per readme Run (inside browser) resources/server/test/test-web-integration.sh this script is missing in repo.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We currently do not allow to run web integration tests from OSS, sorry.
