### ISSUE TITLE
Ports info: servers started from the EH: info too long hard to understand

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115213]
Testing #114532
- start a dev container on a sample (e.g. the NodeJS sample)
- install the live server extension (ritwickdey.liveserver)
- add a html file and click on the `Go Live` button in the status bar
- check out the ports view
The info is very long and not informative. 

![image](https://user-images.githubusercontent.com/6461412/105979418-f150de80-6093-11eb-85da-acab1dd72b21.png)

The server is created from the liveserver extension with [`http.createServer(...)`](https://github.com/ritwickdey/vscode-live-server/blob/a4be2d766d271862f41d973137a21551e1bc9583/lib/live-server/index.js#L271).

Ideally we could detect that this is our extension host process command line just write '[code-insider extension host]`

Also, I'd suggest to always shorten the command line if it gets longer than a threshold. We can still have the hover show the full line.
E.g. just show the basename of the first segment ('node' in this case)

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/105984043-e39e5780-6099-11eb-8c51-04a88f3d72df.png)

**Comment by egamma** [comment]
>Ideally we could detect that this is our extension host process command line just write '[code-insider extension host]`

To avoid having to parse the command line, can we know the extension host process ID and then either do what Martin suggests above or exclude ports from this process all together. This would reduce the list of ports.

**Comment by aeschli** [comment]
+1 for looking at the process id and give it a readable label instead
Not sure about excluding all ports from it. An extension that starts a server seems a valid scenario to me.

**Comment by alexr00** [comment]
If the pid of the process matches that of the remote extension host we now show "Code Extension Host" in ports view. The hover still shows the whole process.
