### ISSUE TITLE
Double clicking on markdown title in Explorer Outline focuses the notebook but also collapses the node

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115212]
Testing #114902

* open `.vscode/notebooks/grooming-delta.github-issues`
* double click on `vscode-remote-release` in the Outline
* this will focus the editor (expected) but will also collapse the node (unexpected?)

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/105980541-493c1500-6095-11eb-8950-16412c0ff20b.gif)

**Comment by jrieken** [comment]
happens in the "symbols" tree of code files as well

**Comment by jrieken** [comment]
Seems to be a tree thing
