### ISSUE TITLE
Secrets API documentation: How long are secrets stored?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115252]
Testing #115160

For the `store` method the documentation is `Store a secret under a given key.`
I'm not sure how long this secret is stored for, though -- it seems I can retrieve a secret after restarting OSS, whereas I expected it to only last a single session (which is more like a cache).

I'd like the docs to include the duration of how long the secret is stored for, and I also noticed that the `Memento` class has a similar issue.

**Comment by ankitbko** [comment]
I am relying on the fact that secrets are not cleared after every session. I am using it to store PAT token.

I think the secrets are not cleared when extensions are uninstalled. I uninstalled my extension, reloaded and reinstalled the extension and the secrets still existed. It would be helpful if uninstalling extension will clear out the secrets in situation where an extension does not provide a way to clear out the storage in case user needs it. Which brings me to a potential feature to force clear all secrets of an extension similar to how browser devtools provide a way to force clear cache and application data. Will be again helpful in situations where extension authors do not provide a way to clear the secrets.

**Comment by RMacfarlane** [comment]
Thanks @ankitbko, I created a new issue based on your comment
