### ISSUE TITLE
Search in Open Editors triggers errors when done without files

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#115271]
Testing #114970

VS Code without a folder and just Settings open shows a red `Search path not found: .` error:

![image](https://user-images.githubusercontent.com/8599/106061261-059fd600-60aa-11eb-9c86-825bcf851143.png)

**Comment by digitarald** [comment]
Same error just with Welcome page open:

![image](https://user-images.githubusercontent.com/8599/106061664-95458480-60aa-11eb-901a-e7911ff64ffa.png)

**Comment by JacksonKearl** [comment]
Thanks, good catch. Settings was fixed in master but walkthrough is still broken.
