### ISSUE TITLE
bogus terminal title: `0.0.0.0:3000) [rails_sample_app]`

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#115291]
I can reproduce it by running rails server: 
<img width="452" alt="Screenshot 2021-01-28 at 09 28 37" src="https://user-images.githubusercontent.com/3082655/106110663-4b60ab00-614b-11eb-9006-d21b9df8582c.png">

It seems that applications can change title and use the space character instead of the null as a delimiter:
<img width="1757" alt="Screenshot 2021-01-28 at 09 27 39" src="https://user-images.githubusercontent.com/3082655/106110658-48fe5100-614b-11eb-8167-0c69969f1f87.png">

VS Code though assumes that titles of terminals created by a user always paths to executable and drops everything before the last path separator.

**Comment by akosyakov** [comment]
@meganrogge Could you clarify by which extension is caused? 😮 

@Tyriar I think it is caused by how node-pty generates process title and how VS Code takes only basepath of it.

**Comment by Tyriar** [comment]
@akosyakov thanks for the info, any suggestions on when we should avoid using `basename`?

https://github.com/microsoft/vscode/blob/52f437953d5fdc6375d3396fb2c462152833df04/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1508-L1514

**Comment by akosyakov** [comment]
One idea would be to check whether the given title is an absolute path, i.e. starts with `/` and only then use `path.basename`?

**Comment by akosyakov** [comment]
in tmux there is such function: https://github.com/tmux/tmux/blob/545a610c6b14af2db02eb40866654f0df7ad2b6a/names.c#L139-L170 maybe it could be used for inspiration
