### ISSUE TITLE
Allow opening new tabs in the edge tools for vscode extension

### ISSUE THREAD

**Issue by mbuotidem** [microsoft/vscode#115246]
I love the new microsoft edge tools for vscode extension. but i'm wondering why there isn't a feature to open an actual browser tab. It would be super helpful for googling an error code or using stackoverflow without ever leaving vscode.

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Tip: use the Report Issue option from VS Code's Help menu if you want a convenient way of directing a bug report or feature request to the correct repo for one of the extensions you are using.
