### ISSUE TITLE
getCachedChannel blocks workspace reloading for seconds

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#115247]
Issue Type: <b>Bug</b>

* Open a repository with changes
* Open a diff editor from SCM view
* Reload the window
* After the window reloads, the window freezes for a few seconds 

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/106035226-b72e0f80-6088-11eb-9e7e-7410e49424ab.png">

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:57:30.935Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.70GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|11.1.3
codespaces|Git|0.6.0
vscode-pull-request-github-insiders|Git|2021.1.37982
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-azurefunctions|ms-|1.2.0
vscode-azurestaticwebapps|ms-|0.5.0
vscode-docker|ms-|1.9.1
vscode-language-pack-zh-hans|MS-|1.53.0
csharp|ms-|1.23.8
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.1.502429796
jupyter|ms-|2021.1.510651036-dev
notebook-renderers|ms-|0.0.1
remote-containers|ms-|0.156.0
remote-ssh-edit-nightly|ms-|2021.1.35460
remote-ssh-nightly|ms-|2021.1.35460
azure-account|ms-|0.9.4
hexeditor|ms-|1.3.0
js-debug-nightly|ms-|2021.1.2617
powershell-preview|ms-|2020.9.0
vscode-github-issue-notebooks|ms-|0.0.60
vscode-markdown-notebook|ms-|0.0.13
vscode-notebook-history|ms-|0.0.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.1.0-dev
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.12
toggle|reb|0.0.1
java|red|0.74.0
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
vsc-nwjs|rua|1.0.18
rust|rus|0.7.8
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.1
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1
notebook-editing|vsc|1.0.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt875:30247033
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/105446

Root issue is spawn is slow on Big Sur
