### ISSUE TITLE
SecretStorage does not work if gnome-keyring is not installed on the machine

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115248]
Testing #115160

I get the following exception when trying to store a value in secrets:

'Error calling StartServiceByName for org.freedesktop.secrets: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.freedesktop.secrets: Operation not permitted'

**Comment by RMacfarlane** [comment]
I think what's going on here is that on Linux, the `keytar` library we use for storing secrets uses `gnome-keyring`, which expects there to be an actual gnome session and not just a headless server. Not immediately sure how to fix.

**Comment by TylerLeonhardt** [comment]
This appears to be fixed. Not sure when but verification steps are:

Make an extension with this at the activate:

```ts
export async function activate(context: vscode.ExtensionContext): Promise<void> {
	context.secrets.store('mysecret', 'secret');
	vscode.window.showInformationMessage((await context.secrets.get('mysecret')) || "");
}
```

Run the extension in Codespaces Web and see that the secret notification pops up.

**Comment by rzhao271** [comment]
I'm still getting this error in Codespaces Desktop.

**Comment by TylerLeonhardt** [comment]
@rzhao271 can you provide info about the OS you're using client side?

**Comment by rzhao271** [comment]
Version : 1.57.0-insider (user setup)
Commit : fe1eafc80c07608de52a2f9c99fee103dea77f5e
Date : 2021-06-04T12:21:40.077Z
Electron : 12.0.9
Chrome : 89.0.4389.128
Node.js : 14.16.0
V8 : 8.9.255.25-electron.0
OS : Windows_NT x64 10.0.19043

**Comment by karolz-ms** [comment]
Docker extension has a long history of problems if `gnome-keyring` is not on the machine: https://github.com/microsoft/vscode-docker/issues/2925 https://github.com/microsoft/vscode-docker/issues/722

The extension *could* work around the issue by rolling out its own, in-memory, "backup" secret store (we used to do that in the past), but it defeats the purpose and spirit of having a common, hardened secret store in VS Code, so we do not want to go  down that path. But we would really appreciate fixing this issue (i.e. making `SecretStorage` work, in degraded mode if necessary, when `gnome-keyring` is not installed on the machine), as it affect mainline scenarios for us (connecting to- and working with external Docker registries).

**Comment by karolz-ms** [comment]
Suggest title change to something like "SecretStorage does not work if gnome-keyring is not installed on the machine". This issue is not specific to Codespaces

**Comment by TylerLeonhardt** [comment]
The odd part for me is that this should never happen because all secrets should be stored on the client OS.

**Comment by timsneath** [comment]
This also applies to GitHub. VSCode should simply add a dependency for gnome-keyring, IMO.

**Comment by TylerLeonhardt** [comment]
@timsneath KDE users will be frustrated by that decision as KDE has a different keyring application

**Comment by mletterle** [comment]
Bumping, because this is an annoying issue.
