### ISSUE TITLE
[Proposal] Display all properties (inherited or not) of a given class (in TypeScript)

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/vscode#11526]
Visual Studio Code is a fantastic tool and I am really impressed by all its features despite being quite young.

There is a feature that does not still exists in VS Code which could be really convenient when we are forced to deal with big inheritance hierarchies.

This proposal is based on the TypeScript language, but I am quite sure this could apply to other OOP languages VS Code supports.
## Overview of the Workflow

Let us assume we have a source file _animal.ts_ like this:

``` ts
// animal.ts

abstract class Animal {
    private dna: number;
    name: string;

    constructor(name: string) {
        this.dna = Math.random();
        this.name = name;
    }

    abstract shout(): string;
}
```

This file could be open or not in VS Code, but it is part of the current project.

Let us assume we have another source file _bird.ts_ like this:

``` ts
// bird.ts

class Bird extends Animal {
    constructor() {
        super();
        this.name = "Hector";
    }
    shout(): string {
        return "Cuicui!"; // sorry it is in French... I do not know how a bird shouts in English ^_^
    }
}
```

This file is open in VS Code.

What I would like to be able to do in VS Code is displaying all properties, inherited or not, available for the class `Bird`.

To do so, we could move the cursor on the `Bird` identifier, press F1 key, and run a new _Display all inherited properties_ command.

This new command would open a new file in a new tab called _Bird (all inherited properties)_.

In this example, the content of this file would be the following:

```
class Bird {
    private dna: number;
    name: string;

    super.constructor(name: string) {
        this.dna = Math.random();
        this.name = name;
    }

    constructor() {
        super();
        this.name = "Hector";
    }

    shout(): string {
        return "Cuicui!";
    }
}
```

The content of _Bird (all inherited properties)_ has nothing to do with valid syntax. Its purpose is only informational.
## Some informal rules
- Attributes should be displayed first.
- Type anotations should be rendered unchanged.
- Access modifiers `public`, `protected`, `private` should be rendered unchanged.
- Abstract methods which are not overriden should be rendered.
- All versions of an overriden method should be rendered, with a concatenation of `super` prefixes to distinguish each version in the inheritance hierarchy. For instance `super.method()` would refer to immediate `method()`'s parent, whereas `super.super.method()` would refer to `method()`'s grand-parent, and so on.
- `Method()`'s parent should be displayed before the `method()` itself.
- The same rules for `method()` apply to `constructor()`.

**Comment by waderyan** [comment]
@dbaeumer this request seems valid to me. Is this something I should feed to TypeScript or is this a feature we would implement on our end (possibly both)?

**Comment by dbaeumer** [comment]
@waderyan this needs work on both ends. First the tsserver has to expose a corresponding API and then we need to adopt it. So we need to feed the request to the TS team as well.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10752

**Comment by waderyan** [comment]
Reopening to track this on our end.

**Comment by mjbvz** [comment]
Closing as extension-candidate.

To implement something like, try using the TypeScript library to collect all properties of a class or interface. See the [extension-editing](https://github.com/Microsoft/vscode/blob/master/extensions/extension-editing/src/extension.ts) built-in extension for a basic example of using this library
