### ISSUE TITLE
I can't Comment Out

### ISSUE THREAD

**Issue by deeeharris** [microsoft/vscode#115268]
I hit Command + / to comment out and it doesn't work on any new files, only old, established ones.  Why won't this work on new filies?  I have a Mac

**Comment by gjsjohnmurray** [comment]
What language mode are your new files using? Look at the indicator towards the right-hand end of the status bar. Maybe it says 'Plain Text', in which case click it to pick a different mode.

Tip for future reports: use the 'Report Issue' option on the Help menu. This will pre-fill your GitHub report with version information. For more advice about reporting issues, see https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by kieferrm** [comment]
@deeeharris Here is a picture showing what @gjsjohnmurray describes. If you click "Plain Text" in the status bar you can tell VS Code what type of source code you are editing and it can behave accordingly. 

![image](https://user-images.githubusercontent.com/4674940/106344424-b4851300-625e-11eb-9622-0733d8b8480f.png)
