### ISSUE TITLE
Change workbench.editor.enablePreview default to false

### ISSUE THREAD

**Issue by wesinator** [microsoft/vscode#115231]
Creating issue for discussion based on #115088

For background, see https://stackoverflow.com/questions/38713405/open-files-always-in-a-new-tab

**Current:** workbench.editor.enablePreview default `true`. Newly opened files open over the current file being edited

**Expected/sane:** workbench.editor.enablePreview default `false`. 

There are numerous requests in this stackoverflow post to change the default behaviour to more sane default of new file opens being done in a new tab instead of over the existing tab. 

This would follow the principle of least astonishment and be more similar to how browsers open (_blank) links in new tab. 

I have to change this setting every time on a new instance.
I have not heard a case where someone prefers the current default behaviour to the more expected conventional one.

I can reopen #115088 if it is decided this is the way to go. 

Thanks,

**Comment by goldst** [comment]
I personally prefer the current default behavior. Especially when navigating through projects with many files, I often end up having too many files open and lose track. The current behavior helps to tackle that problem, it keeps VS Code cleaner by default.

It is also not hard to go back when that happens, using the menu (Go > Back) or <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>-</kbd>. And, as mentioned on StackOverflow too, this can be easily avoided by double-clicking the file.

I understand that this behavior is a bit surprising at first though and might need some time to get used to. What I would suggest instead is that the preview editors should be visually more different from the normal editors - the italic font in the tab title can easily be overlooked. I'm not a UI designer, but something like a different background shade in the editor or some kind of border around it would work.

**Comment by wesinator** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to [upvote](https://github.com/microsoft/vscode/wiki/Issues-Triaging#up-voting-a-feature-request) the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).
> 
> Happy Coding!

if my original post has 20 upvotes ?
