### ISSUE TITLE
Remote explorer showing too many views

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#115251]
Issue Type: <b>Bug</b>

This is an issue that never disappeared for me but, I think, was declared fixed. When I open the remote explorer, I usually get more several views, not just the one that is selected in the dropdown.

![image](https://user-images.githubusercontent.com/4674940/106038400-c44cfd80-608c-11eb-9db9-0802e914343e.png)

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:57:30.935Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.4.0-1031-azure
Remote OS version: Linux x64 5.4.0-1031-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (7.71GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (7.71GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.3
git-branch|ale|1.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
tsl-problem-matcher|eam|0.3.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
graphviz-markdown-preview|gee|0.0.8
codespaces|Git|0.6.0
vscode-pull-request-github-insiders|Git|2021.1.37982
mdmath|goe|2.5.1
rainbow-csv|mec|1.8.0
theme-monokai-pro-vscode|mon|1.1.18
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.156.0
remote-ssh-edit-nightly|ms-|2021.1.35460
remote-ssh-nightly|ms-|2021.1.35460
remote-wsl|ms-|0.53.1
azure-account|ms-|0.9.4
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2021.1.2617
vscode-github-issue-notebooks|ms-|0.0.60
vscode-js-profile-flame|ms-|0.0.13
vscode-markdown-notebook|ms-|0.0.13
material-icon-theme|PKi|4.5.0
ruby|reb|0.28.1
vscode-xml|red|0.14.0
vscode-ruby|win|0.28.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt875:30247033
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by alexr00** [comment]
@kieferrm is the "GitHub Codespaces" view always one of the visible views?

**Comment by kieferrm** [comment]
Yes. In my case it's usually what you see above: SSH and Codespaces.

**Comment by alexr00** [comment]
@kieferrm do you have to be connected to a remote when you see this?

**Comment by kieferrm** [comment]
I have right now remote and local windows open, I see it in both:

Codespaces window:
![image](https://user-images.githubusercontent.com/4674940/107797040-569d0480-6d0f-11eb-9988-2b31d9a24544.png)

New local window:
![image](https://user-images.githubusercontent.com/4674940/107797095-661c4d80-6d0f-11eb-825f-f325daf38174.png)

**Comment by kieferrm** [comment]
Here is what seems to happen:
1) Have the Remote-SSH and the Codespace extension enabled
2) Ensure there are ssh and codespaces workspaces in your "recent" list
3) Close VS Code, restart with -n
4) Open Remote Explorer in the new local window -> SSH selected and visible
5) From recent list open ssh workspace
6) Open Remote Explorer in the new remote window -> SSH selected and visible
7) Open new local window
8) Open Remote Explorer in the new local window -> SSH selected and visible
9) From recent list select codespace
10) Open Remote Explorer in the new codespace window -> Codespaces selected, SSH and Codespaces visible
11)  From now on, all new windows no matter whether  local or remote show a remote explorer with Codespaces selected, SSH and Codespaces visible.

**Comment by alexr00** [comment]
Thank you for the detailed steps! I'm still not able to repro this, though it is clearly a problem. Just to confirm though: you have the latest Codespaces extension installed?

**Comment by alexr00** [comment]
@kieferrm is this still happening for you?
