### ISSUE TITLE
Windows - The terminal process exited with code 1 

### ISSUE THREAD

**Issue by abdurrosyidhandoyo** [Microsoft/vscode#11527]
- VSCode Version: 1.4.0
- OS Version: Windows 7

Steps to Reproduce:

1. Open VSCode
2. Press Ctrl+` to open integrated terminal
3. The terminal process terminated with exit code 1

**Comment by Tyriar** [comment]
This error means that the shell process could not be launched, likely due to having the wrong path. Try changing your `terminal.integrated.shell.windows` setting in your `settings.json` ([documentation here](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration)).

Improving this message is being tracked in #9261

**Comment by hwen0419** [comment]
I am having the same issues on Windows 10, nothing can be opened via integrated terminal.

**Comment by Tyriar** [comment]
@hwen0419 do you have anything in settings.json? Also what's the output of `echo %COMSPEC%`?

**Comment by hwen0419** [comment]
output of echo %COMSPEC%:  C:\WINDOWS\system32\cmd.exe
and in settings.json I only specifiy "typescript.tsdk" location

**Comment by volkancakil** [comment]
same error on Win 8.1 x64 and vscode 1.6.1 when the working path contains any special/unicode characters

**Comment by Tyriar** [comment]
@volkancakil that one is fixed for 1.7.0. @hwen0419 @abdurrosyidhandoyo does the path contain non-ascii characters? If so this is a duplicate of https://github.com/Microsoft/vscode/issues/7727

**Comment by hwen0419** [comment]
The project folder contains non-ascii characters. So it's a duplicate issue.

2016年10月16日星期日，Daniel Imms <notifications@github.com> 写道：

**Comment by Tyriar** [comment]
Great! This should be working in the [Insiders build](https://code.visualstudio.com/insiders), coming to Stable in v1.7 (early November).
