### ISSUE TITLE
Startup time taking longer than usual since last updates

### ISSUE THREAD

**Issue by guercheLE** [microsoft/vscode#115232]
Issue Type: <b>Performance Issue</b>

I have noted startup time is taking longer than usual since last updates

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:59:32.031Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.51GB free)|
|Process Argv|--crash-reporter-id 8a44d333-3bcd-4b7b-bf4c-b2f77ed8b895|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    80	  9252	code-insiders main
    0	   119	  2780	   gpu-process
    0	    78	  2988	   window (Issue Reporter)
    0	    38	  9316	   utility
    0	    76	 11152	   shared-process
    0	   133	 15164	   window (Welcome - Visual Studio Code - Insiders [Administrator])
    0	   342	 19868	     extensionHost
    0	    66	 19212	       electron_node serverMain.js 
    0	    23	 15580	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
angular-schematics|cyr|4.8.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
reg|ion|1.0.2
docthis|joe|0.7.1
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
docomment|k--|0.1.20
chat|kar|0.35.0
csharpextensions|kre|1.3.6
csharpfixformat|Leo|0.0.84
Angular-BeastCode|Mik|10.0.3
ecdc|mit|1.4.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.156.0
remote-wsl|ms-|0.53.1
cpptools|ms-|1.1.3
powershell|ms-|2020.6.0
powershell-preview|ms-|2020.9.0
vsliveshare|ms-|1.0.3577
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
vuejs-extension-pack|mub|1.2.1
angular-console|nrw|16.0.2
vetur|oct|0.32.0
quicktype|qui|12.0.46
csharp2ts|raf|0.0.25
vscode-essentials-snippets|rob|2.0.0
vue-vscode-snippets|sdr|2.1.5
javascript-typescript|sou|0.0.7
bootstrap4-vscode|the|6.1.0
vscode-status-bar-format-toggle|tom|2.0.0
vscodeintellicode|Vis|1.2.10
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30247032
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.
