### ISSUE TITLE
cannot install extensions or chage config files on linux

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#11529]
- VSCode Version:1.4.0
- OS Version:ubuntu 16.4

Steps to Reproduce:
1. install an extension
2. restart vscode
3. get the weird error ![](http://i.imgur.com/FNRc5nb.png)
4. installed extension is gone and all config files reverted back to old versions

**Comment by NikosEfthias** [comment]
also got this popup ![](http://i.imgur.com/e4aDQX0.png)

**Comment by jrieken** [comment]
@NikosEfthias Which extension did you install?

**Comment by NikosEfthias** [comment]
recommended golang extension @jrieken but weird part is that it was installed earlier and also i cannot edit config file its all the time reverting back

**Comment by jrieken** [comment]
Please try without any extension using the `--disableExtensions` flag when starting  VS Code from the command line.

**Comment by NikosEfthias** [comment]
seems like the error is gone

**Comment by jrieken** [comment]
> seems like the error is gone

In general or only when running with the `disableExtensions` flag?

**Comment by NikosEfthias** [comment]
with `disableExtensions` flag

**Comment by jrieken** [comment]
What extensions do you have installed? Try to uninstall them one by one to figure out which caused this
