### ISSUE TITLE
Notebook outline does not recognize alternative markdown heading format

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115206]
Testing #114902

* have a cell with the content:
```md
My Title
--------
```
While the rendering recognizes this as a markdown header, the outline does not:
![image](https://user-images.githubusercontent.com/5047891/105972893-66b8b100-608c-11eb-88e4-855b18245a33.png)

**Comment by jrieken** [comment]
@rebornix same problem for folding
