### ISSUE TITLE
ExtensionContext.globalState: Can't unset a Memento stored value

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#11528]
- VSCode Version: 1.4.0
- OS Version: OSX 10.10.5

Steps to Reproduce:

1. Set a value in the ExtensionContext globalState:
```
context.globalState.update('testkey', 'somevalue')
        .then(function() {
            console.log(context.globalState.get('testkey');
        });
```
2. There are no methods to unset or clear that value from your global state as far as I can tell. The Memento object only has 2 methods: `get` and `update`. I tried updating the value with values of `null` and `undefined`, but the `testkey` persisted and did not go away. There doesn't seem to be a way of removing it or clearing it completely from the `globalState`.

**Comment by jrieken** [comment]
```
     context.globalState.update('testkey', undefined).then(function () {
            console.log(context.globalState.get('testkey'));
        });
```

does print `undefined` for me which means the key has no value. @Jakobud what is your expected behaviour?

**Comment by Jakobud** [comment]
You are correct and I was mistaken. For some reason I thought I was still seeing the object show up under `context.globalState._value` when I examined the object. Thank you,

**Comment by jrieken** [comment]
Thanks for getting back so quickly
