### ISSUE TITLE
Status bar: setting invalid color sets opacity 100%

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115292]
Follow steps from https://github.com/microsoft/vscode/issues/110214#issuecomment-768495015 and notice how you end up with a status bar that uses the following color and thus is invisible: 

![image](https://user-images.githubusercontent.com/900690/106110956-b316f600-614b-11eb-8028-dddab8f24da9.png)

**Comment by aeschli** [comment]
@bpasero Please review [my fix](https://github.com/microsoft/vscode/commit/e86befc8a9ffb91e9183e367ca0133b164876cee). Blame thinks it was you who wrote the code with the `Color.transparen`, but, to be honest, I don't remember.

**Comment by bpasero** [comment]
Thanks, I cannot recall. Why would we have picked `Color.transparent ` for invalid colors? I think the motivation was to not pick any color if the color if unknown.
