### ISSUE TITLE
Format on save for TypeScript files sometimes indents JSDoc comments incorrectly

### ISSUE THREAD

**Issue by craxal** [microsoft/vscode#115272]
- VSCode Version: 1.52.1
- OS Version: macOS Big Sur 11.1

1. Create a TypeScript file with a class and several methods.
2. Create a JSDoc comment for one of the methods.
3. Make sure that auto format on save is enabled for TypeScript files.
4. Save the file.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/3473026/106064226-55809c00-60ae-11eb-989d-115007a9ccde.png)

Carried over from #109622, because that issue is now closed.

**Comment by mjbvz** [comment]
Very likely same root cause as https://github.com/microsoft/TypeScript/issues/42310
