### ISSUE TITLE
Markdown icon in outline is drawing attention away from code cells

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115201]
Testing #114902

* open `.vscode/notebooks/inbox.github-issues`
* notice how in a regular outline all the entries are "balanced"
* notice how in the notebook outline, the markdown entries appear more emphasised

| regular outline | notebook outline |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/105964305-4a177b80-6082-11eb-806b-b745af21384d.png) | ![image](https://user-images.githubusercontent.com/5047891/105964361-5c91b500-6082-11eb-851a-b0f65e83f9e6.png) |

**Comment by gjsjohnmurray** [comment]
Maybe because there's no icon on the code cell entries.

**Comment by jrieken** [comment]
Hm... I actually do see icons. @alexdima do you use an icon theme? did you disable outline icons?

<img width="362" alt="Screenshot 2021-01-27 at 11 00 23" src="https://user-images.githubusercontent.com/1794099/105975094-dd56ae00-608e-11eb-9f38-7ff266643fa4.png">

**Comment by alexdima** [comment]
Yes, I have this configured: `"workbench.iconTheme": "vscode-icon-theme"`. But I didn't change that since a long time. Somehow, I see the markdown icon, but not the `</>` icon.

**Comment by alexdima** [comment]
After commenting out `"workbench.iconTheme": "vscode-icon-theme"` here is the rendering I see:

![image](https://user-images.githubusercontent.com/5047891/105981130-03cc1780-6096-11eb-8244-8bf8dea685cb.png)

**Comment by alexdima** [comment]
Very weird, all of those entries had dropdown icons but then clicking on them didn't do anything.

**Comment by misolori** [comment]
I saw the same thing in https://github.com/microsoft/vscode/issues/115120 where code cells show the default icon except for Python cells. I never see the code icon for cos cells.

**Comment by jrieken** [comment]
I can reproduce - that's because the theme uses background images, not an icon font..
