### ISSUE TITLE
Don't steal the focus

### ISSUE THREAD

**Issue by grisu48** [microsoft/vscode#115226]
Hi,

The defaults of VS Code are set to enable "Focus Window On Break". I find this a highly disturbing default behaviour because sometimes a program needs some time to reach the section you want to debug. In this case there is a high chance, that the user does something else in the meantime and then be forcefully interrupted by VS Code. Even worse, it might occur, that the user is about to type in sensitive information into a terminal or a web form, which then lands within VS Code.

In fact, I'm writing this feature request, while there is a debugging session going on ;-)

Please, do not steal the focus ever, at least not by default. Thanks :slightly_smiling_face:

**Comment by gjsjohnmurray** [comment]
I assume you have discovered that the setting `"debug.focusWindowOnBreak": false` exists?

Changing defaults for settings is rarely done because of the negative impact it has on people who are happy with the existing default.

**Comment by grisu48** [comment]
Thanks for the reply. Yes, I was able to fix this issue for my installation.

However, focus steal is arguably very bad behaviour and a security issue. If the focus steal happens in the right moment, I'm gonna type my password into VS Code. Since most users are not aware of this default, it happens at least once before the user notices. It happened to me, and made me upset and angry.

So, knowing that changing the defaults will cause a non-negligible fractions of users complain, I find this a highly annoying and unsafe default. Here I wanted to at least raise awareness, so that the current defaults could perhaps be reevaluated.

**Comment by xpe** [comment]
@grisu48 I'm here looking at various open feature requests to see if I can lend a vote to ones that seem important. So I'm interested to learn more, though I haven't encountered this myself. Can you provide more context, such as a screencast that shows the current behavior?

**Comment by grisu48** [comment]
> @grisu48 I'm here looking at various open feature requests to see if I can lend a vote to ones that seem important. So I'm interested to learn more, though I haven't encountered this myself. Can you provide more context, such as a screencast that shows the current behavior? This will help "drive by" people who want to weigh in and up-vote.

Sure, I'll have a look tomorrow and see if I can provide a screencast with an example :+1:

**Comment by grisu48** [comment]
I could quickly hack a peek session, hope this illustrates why I mean.

## Example 1: Text goes to MS Code while Typing

Focus steal while working on some other things

![Focus-Steal](https://user-images.githubusercontent.com/1527829/106018382-bd8cad80-60c1-11eb-83ca-ffdbef3a4935.gif)

## Example 2: Password leak

Focus steal leads to password being typed into MS Code

![Focus-Steal-Password](https://user-images.githubusercontent.com/1527829/106018398-c1b8cb00-60c1-11eb-866f-0bf7fcde0f3a.gif)

**Comment by xpe** [comment]
@grisu48 Well explained! Thanks.

A follow up: are there any *benefits* to this being the default behavior? (I'm not saying the benefits outweigh the security risks; I'm just asking.)

**Comment by isidorn** [comment]
@grisu48 thanks a lot for your feedback!
However this is the default behavrio for preivous 5+ years and this is the first complaint.
I understand the problem and you have nicely demonstrated that via your gif.

For now I suggest you change the setting, and I would be open to change the default value of the setting in the future. I will like to keep this issue open so we gather more feedback from users. Thanks

**Comment by grisu48** [comment]
> @grisu48 thanks a lot for your feedback!
> However this is the default behavrio for preivous 5+ years and this is the first complaint.
> I understand the problem and you have nicely demonstrated that via your gif.
> 
> For now I suggest you change the setting, and I would be open to change the default value of the setting in the future. I will like to keep this issue open so we gather more feedback from users. Thanks

thanks for the reply @isidorn. I understand the implications and pain of changing the default behaviour and appreciate your open mind towards this issue.

For all the folks who stumbled across this issue, you can change the behaviour as suggested by @gjsjohnmurray by setting `debug.focusWindowOnBreak` in the Settings dialog of VS Code to `false`, as shown below:

![setting-focusWindowOnBreak](https://user-images.githubusercontent.com/1527829/106245912-92af7000-620d-11eb-9d68-72998dbeb0b8.png)

Cheers :slightly_smiling_face:

**Comment by geoidesic** [comment]
Errors in vscode also steal focus. That drove me mad. I was trying to copy / paste something from a browser and VsCode wouldn't let me because it kept stealing focus. Whoever came up with the idea of "let's steal focus" in the first place was being obnoxious.

**Comment by iso2013** [comment]
I've used VSCode for years, and the focus stealing has always been something that bothered me, without me realizing - I only now thought to search for it and found the setting and this issue.

Yes, the onus is on me for not searching for my issue - but the thing was I didn't even realize it was something I *should* search. It's been one of those minor annoyances that's bothersome but since the rest of the program is so quintessential to your workflow, it slips by.

Personally, I think changing the default would be a good move - I don't think most people would notice the change, and the (probably few) who do would be more likely to search for a solution and find the setting.
