### ISSUE TITLE
Copying with CMD+C in cell output sometimes copies cell contents

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#115278]
@pbotros commented on [Wed Jan 27 2021](https://github.com/microsoft/vscode-jupyter/issues/4528)

## Environment data

Version: 1.53.0-insider
Commit: 1a9dd758530782ee4bb09a15bdc484f3dcb9b5a3
Date: 2021-01-26T05:12:23.287Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
-   Python and/or Anaconda version: 3.7
-   Jupyter server running: Local 

## Expected behaviour

Highlighting any part of a Jupyter cell's output then pressing Cmd+C should copy the highlighted text.

## Actual behaviour

Highlighting a part of a Jupyter cell's output and then pressing Cmd+C _sometimes_ copies the cell's code contents. This happens pretty often for me in larger more complicated notebooks. Notably, it seems that clicking Edit > Copy copies the right thing.

## Steps to reproduce:

1. Create a new jupyter notebook.
2. Make a Python code cell and put in:
```
print('This is output')
print('This is output')
```
3. In the output, select immediately after the "is" on the first line to the second "is" on the second line, inclusive. See GIF.
4. Press Cmd+C.
5. Open any other text editor, and Cmd+V. The cell contents with `print(...)` are instead copied.

See attached GIF for repro illustration. Note in the GIF where manually clicking Edit > Copy works properly as does Cmd+C when copying another part of the output, but the GIF includes two other instances of using Cmd+C that do not work properly and instead copy the code.

![copying](https://user-images.githubusercontent.com/773285/106060561-113ecd00-60a9-11eb-90bf-e6b488a74c73.gif)

</details>

---

@rchiodo commented on [Wed Jan 27 2021](https://github.com/microsoft/vscode-jupyter/issues/4528#issuecomment-768672240)

Thanks for the issue. I believe this issue would actually be handled by VS code as they're controlling the copy.

**Comment by DonJayamanne** [comment]
@rebornix I think this used to work. I managed to repro this last week, & can still repro.

**Comment by rebornix** [comment]
I'm not seeing this anymore with text output. Please ping if you are still seeing it.

**Comment by chencjiajy** [comment]
I met this problem too

### Environment data: 
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 18.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id de4820fb-db21-4d66-8b35-89e8bb659650|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-markdownlint|Dav|0.43.2
json-tools|eri|1.0.2
python|ms-|2021.9.1218897484
vscode-pylance|ms-|2021.9.1
jupyter|ms-|2021.8.2041215044
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
cpptools|ms-|1.6.0
sqltools|mtx|0.23.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30364560
pythonf5test824:30361777
javagetstartedt:30364666
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603

```

</details>
