### ISSUE TITLE
`isEmojiImprecise` misses ⭐

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115221]
https://github.com/microsoft/vscode/blob/5da5495a7f84723dd2d9052bfb66639a531abeb0/src/vs/base/common/strings.ts#L776-L782

**Comment by JacksonKearl** [comment]
Verified via code review, couldn't observe any differences in handling ⭐ between stable and insiders.

**Comment by JacksonKearl** [comment]
Verified by cursoring around in
```
"`isEmojiImprecise` misses⭐",
"`isEmojiImprecise` misses🙂",
"`isEmojiImprecise` misses🐧",
"`isEmojiImprecise` misses🙂",
```
