### ISSUE TITLE
IntelliSense completion not correctly highlighting text in front of cursor

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#115250]
In the current Insiders version, IntelliSense will only highlight a single letter instead of whats already written in front of the cursor. However, when I click somewhere else to dismiss IntelliSense, and then click back at the end of the text and re-trigger it again it works fine. See the images for a comparison between Stable and Insiders. 

**Expected behaviour (Stable/Insiders after re-triggering IntelliSense)**

![grafik](https://user-images.githubusercontent.com/11841072/106036868-2aaa3e00-60d6-11eb-8fe1-5f390e33f135.png)

**Actual behaviour**

![grafik](https://user-images.githubusercontent.com/11841072/106037105-81177c80-60d6-11eb-9d28-33a2ab9b67da.png)

- Insiders VSCode Version:  1.53.0-insider (system setup) (7b0cfdd04ad530a9c8d782c618afd79290be3d64)
- Stable VSCode Version:  Version: 1.51.1 (user setup) (e5a624b788d92b8d34d1392e4c4d9789406efe8f)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a TypeScript project
2. Reference something with the `.` character and start typing

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
To verify: make sure use TS/JS or any completion provider that uses the filterText-property. In that case we score against a string that we don't show and then we "guess" highlights.

A good sample (JS) in `console.`. When it triggers completions for console make sure the highlight are good
