### ISSUE TITLE
Menu bar collides with command palette on web

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#115267]
when setting `window.menuBarVisibility` to `visible` on web:

![image](https://user-images.githubusercontent.com/35271042/106051572-78ef1b00-609d-11eb-86be-86fc682e6d46.png)

**Comment by sbatten** [comment]
after reload the issue is resolved, it seems the offset required is not being updated properly on web

**Comment by sbatten** [comment]
actually this isn't web specific
