### ISSUE TITLE
Color Theme picker: it should mark the currently active Theme

### ISSUE THREAD

**Issue by schittli** [microsoft/vscode#115330]
- VSCode Version: 1.52.1
- OS Version: W10 1909

Steps to Reproduce:

1. Open the Color Theme picker by Ctrl+K Ctrl+T or with File > Preferences > Color Theme.
2. **The Theme List should mark the current active Theme**

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
For me that works. What do you see?
![theme-picker](https://user-images.githubusercontent.com/6461412/106250924-9692c080-6214-11eb-9025-1860cf696e24.gif)
