### ISSUE TITLE
If tooltip is falsy after `resolveTreeItem` is called, then the tooltip gets stuck as 'Loading...'

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#115337]
Issue Type: <b>Bug</b>

In the past, if the tree item `tooltip` was falsy, the `label` would be used instead on hover.

[This code](https://github.com/microsoft/vscode/blob/5b75a42575fd85c3a9f69bec76bd1afe7c2dcb33/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L262-L269) makes it so that if the tree item's `tooltip` is falsy after calling `resolveTreeItem`, then instead of following the old behavior and using `label`, it will stick as 'Loading...' forever.

Instead, if `resolvedTooltip` is falsy, it should fall back to `label` to most closely resemble prior behavior.

VS Code version: Code - Insiders 1.53.0-insider (7b0cfdd04ad530a9c8d782c618afd79290be3d64, 2021-01-27T08:59:32.031Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.38GB free)|
|Process Argv|--crash-reporter-id edba2bce-ac1c-499b-b3ff-28d400cc9143|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.156.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.5

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt600:30247031

```

</details>

**Comment by bwateratmsft** [comment]
@alexr00 FYI

**Comment by sbatten** [comment]
@bwateratmsft this fix is out in the latest insiders, can you please let us know when you've verified, thanks

**Comment by bwateratmsft** [comment]
@sbatten @alexr00 everything seems to be working nicely, thanks!
