### ISSUE TITLE
Getting started images for link items should be links too

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115320]
I clicked the play button and getting started made me feel silly, permanently lowering my self confidence.

![image](https://user-images.githubusercontent.com/2193314/106179491-f6736380-614f-11eb-9532-13c208c696ab.png)

**Comment by JacksonKearl** [comment]
cc @digitarald for content

**Comment by digitarald** [comment]
@JacksonKearl what do you think about putting a link on the cover image as well for link buttons?

**Comment by JacksonKearl** [comment]
Yeah we could do that

**Comment by JacksonKearl** [comment]
Testing this out it made sense to me to treat all image clicks the same as their respective button clicks.

**Comment by bpasero** [comment]
I find it very unexpected that clicking the image would trigger the action. I was clicking an image in the Codespace and it opened VSCode locally wanting to install the Codespaces extension?

Can we please reconsider this, esp. in the web clicking an image typically means to open the image in large. There is also no hand cursor indicating that a click works.

**Comment by JacksonKearl** [comment]
Scoped down to only apply to links and also give a pointer for the images on link-items.
