### ISSUE TITLE
Regression: Source control changes now requires manually clicking refresh button to pick up changes

### ISSUE THREAD

**Issue by zbs** [microsoft/vscode#115366]
Normally, the changes section in the source control sidebar automatically picks up changes in the given repo after the changes are saved (given that they're in a git repo). Within the last couple of days, I've had to manually refresh in order to pick up changes.

Notes:
- Version: 1.52.1
- Using Remote SSH
- Tested on multiple machines

**Comment by zbs** [comment]
Figured it out. The issue reproes specifically when my workspace root is `/home/zbs/git/rootFolder` as opposed to the realpath of that (e.g. `realpath /home/zbs/git/rootFolder` is `/really/long/path/.../home/zbs/git/rootFolder)`. This is a bug because it catches the changes when I manually hit the refresh button in the Source Control sidebar.

Note that the `home` folder is mounted onto a filesystem shared across a network.

**Comment by vpatel-gb** [comment]
I am facing issue "need to manually refresh source control section" on  1.65.2 (Universal) Date: 2022-03-10T14:33:49.188Z

**Comment by lszomoru** [comment]
@vpatel-gb, are you facing this issue while using a network drive as described above?

**Comment by lszomoru** [comment]
Closing this issue as part of our housekeeping as I have never heard back from @vpatel-gb.
Please feel free to reopen the issue in case you are still able to reproduce this problem. Thanks!
