### ISSUE TITLE
FSI print out is a mess

### ISSUE THREAD

**Issue by halcwb** [microsoft/vscode#115385]
Issue Type: <b>Bug</b>

The printing of results in FSI is a mess. When printing records they overwrite each other in the FSI output.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (14.23GB free)|
|Process Argv|--crash-reporter-id 077c0682-2013-4f6f-af94-7d4f5e7cbd7c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
Ionide-FAKE|Ion|1.2.3
Ionide-fsharp|Ion|5.2.0
Ionide-Paket|Ion|2.0.0
mechanic|Ion|0.0.19
csharp|ms-|1.23.8
remote-containers|ms-|0.155.1
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

https://github.com/ionide/ionide-vscode-fsharp
