### ISSUE TITLE
On deleting a directory, return focus to it's parent

### ISSUE THREAD

**Issue by sramam** [microsoft/vscode#115312]
It didn't seem like this has been reported before. Hopefully my search was thorough enough.

When deleting a directory, in the Explorer pane, the focus currently goes to the root directory of explorer. 
This is a pain say if one is trying to delete the directory to replace it with another in the clip board.

Current Behavior:
1. ctrl-c to copy a directory to the clipboard
2. Navigate to target-dir
3. shift-del to delete replacement-target
4. Navigate to parent-dir
5. ctrl-v to paste 

Desired Behavior:
1. ctrl-c to copy a directory to the clipboard
2. Navigate to target-dir
3. ctrl-v to copy/replace target - a confirmation here is appropriate

Acceptable compromise:
1. ctrl-c to copy a directory to the clipboard
2. Navigate to target-dir
3. shift-del to delete target
4. ctrl-v to recreate target

I had to replace a bunch of sub-directories in an involved directory structure - a "replace-all" if you will - and that re-navigating was a real bother.

**Comment by isidorn** [comment]
Let me try to be concise:
* when a folder is deleted, you want the focus to move to it's parent

Currently when a folder is deleted we focus the next item in the tree.

The current behavior is actually designed behavior. It just made sense for most users and especially for accessibility - since focus unexpectidtly jumping is not nice. More details can be found here https://github.com/microsoft/vscode/issues/71315

For now leaving this open, but we currently have no plans to change this

**Comment by sramam** [comment]
hmm - this was precisely the behavior I was requesting - so when back and setup an repro.
It seems not to be the case when there is a mismatch between the directory being deleted and the current mouse position, is when the problem occurs. 

## Expected behavior

1. copy sub1
![image](https://user-images.githubusercontent.com/518574/106183085-9f23c200-6154-11eb-8c15-ddbbee4e77d1.png)

2. select target 
![image](https://user-images.githubusercontent.com/518574/106183104-a945c080-6154-11eb-9a9b-ca70c0145aff.png)

3. delete target
![image](https://user-images.githubusercontent.com/518574/106183154-bbbffa00-6154-11eb-89b0-78ebf56baf54.png)

4. paste replacement
![image](https://user-images.githubusercontent.com/518574/106183203-caa6ac80-6154-11eb-88dc-248bd252c94b.png)

This is exactly what I expect and you describe - it's all 🌈 🌈 🦄 🦄 so far. 


## Unexpected behavior

1. copy sub2
![image](https://user-images.githubusercontent.com/518574/106182881-5409af00-6154-11eb-8d2d-dc7e8d65fd37.png)

2. select replacement target
![image](https://user-images.githubusercontent.com/518574/106182914-5f5cda80-6154-11eb-980e-e2706f58f64a.png)

3. delete target *OOPS*
![image](https://user-images.githubusercontent.com/518574/106182976-77345e80-6154-11eb-8e20-571ff0b8e876.png)

4. Paste replacement
![image](https://user-images.githubusercontent.com/518574/106183004-81eef380-6154-11eb-9d14-2c3edefa00e6.png)

The behavior was unexpected and since I was doing it repeatedly, it required more fiddling to accomplish my goals than
I wanted. Hopefully these details are useful. 

I'm just a very happy user of VSCode and grateful for all the work you folks put into it.

I'll live either way, filing this issue at least clarified my frustration....

**Comment by isidorn** [comment]
Aha the combination of compact explorer folders and focusing down leads to the bad experience for you...
