### ISSUE TITLE
"the file cannot be displayed in the editior because it is either binary ..."  but sometimes we need to read binary file  as text

### ISSUE THREAD

**Issue by rainssong** [Microsoft/vscode#11530]
- VSCode Version: 1.3.1
- OS Version: windows8

Steps to Reproduce:

1. find a binary file
2. open it

result:"the file cannot be displayed in the editior because it is either binary ..." 

but, sometimes we need to read binary file as text.

**Comment by bpasero** [comment]
@rainssong you could try with https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-hexdump

**Comment by rainssong** [comment]
@bpasero fantastic
