### ISSUE TITLE
Explorer: indicate symlinks

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11539]
I think this should be done via icons.

**Comment by niieani** [comment]
It might be better if a symlink is highlighted in a different way than an icon, perhaps with color, or a second icon? Cause icons indicate the file type, but a symlink only indicates the file isn't actually there. It would be a very useful feature, especially for larger projects.

**Comment by PKief** [comment]
Is there already a way to add an icon for symlinks?

**Comment by snoopdouglas** [comment]
For reference, [that other trendy text editor](https://github.com/atom/atom) does it with icons like this.

In this example `httpd.conf` is a symlink, `hyper.js` is not:

<img width="190" alt="screen shot 2017-03-08 at 09 08 45" src="https://cloud.githubusercontent.com/assets/4892574/23697233/e60c6ed8-03de-11e7-8f14-993e495687e2.png">

**Comment by daniell0gda** [comment]
I have situation that I am linking some folders from sub-project. Before I was linking I was using bat file to copy files and I thought that simply linking is awesome idea. Problem was that after a while I don't know if folder was linked and that makes me really sad 👎

**Comment by jimblue** [comment]
Any news about a fix? Iit's pretty old issue and very expected and  useful feature!

**Comment by jimblue** [comment]
Adding a symlink icon to concerned files and folder seems the best approach. Or maybe an highlight colour.

Your input on this @isidorn ?

**Comment by ryansully** [comment]
I like @snoopdouglas's example, but rather than replace the icon completely, maybe it could preserve the icon for that file type but overlay the icon from the example as a badge overlay in the corner?

**Comment by snoopdouglas** [comment]
I agree, an overlay would be even better. A tooltip Indicating the link
target would be a good idea too

**Comment by jimblue** [comment]
Agree a symlink icon as badge overlay would be the best solution.

**Comment by isidorn** [comment]
We would need to add two properties to icon themes
`symbolicLink`
`symbolicLinkExpanded`

Root folders are already doing this, here's an [example](https://github.com/Microsoft/vscode/blob/master/extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json#L38)

It would need to be added to this [interface](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/fileIconThemeData.ts#L142) and the [FileKind](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L886) would need to be expanded to contain `SymbolicLink`.
The explorer passes this information to he label decorator [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L240)

The only missing piece is how to check if a link is symbolic. For that the fileService would need to expose the node [`isSymbolicLink()`](https://nodejs.org/api/fs.html#fs_stats_issymboliclink)

@bpasero if the outline of the work makes sense to you could you expose this in the `FileService` and I can adopt it in all the other places I mentioned above.

**Comment by bpasero** [comment]
@isidorn we can add it, however `isSymbolicLink` is only working if `fs.lstat` is used (instead of `fs.stat`). `lstat` will return the metadata of the link itself, not its target. We would have to add this call after the `fs.stat` call [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L1227).  

The downside is that we need both `stat` and `lstat` because `lstat` would return `false` for `isDirectory` for a symbolic link that points to a folder.

**Comment by isidorn** [comment]
@bpasero yes I would start with the symbolic link icon having priority (from the screenshot above it seems like other editors are doing this). Otherwise we would need to beef up our icon themes for the overlay. Fyi @aeschli 

I will sketch out a PR.

**Comment by aeschli** [comment]
I agree we need an overlay. Users can have different icons per folderName as well as per filename, extension, language.

**Comment by bpasero** [comment]
@isidorn @aeschli maybe an alternative solution would be to use an explorer decoration instead of tampering with the icon. One thing to keep in mind is that the icon would only indicate symlinks in the files explorer but nowhere else, so I think going with the icon might actually not be such a good idea.

**Comment by isidorn** [comment]
@bpasero to start I can just color it in a differnt color, and maybe contribute some hover text.
As to how to exactly show it we can also discuss in ux meeting / standup

**Comment by jimblue** [comment]
👍 for different color!!!

**Comment by bpasero** [comment]
@isidorn yeah good point, but then it should be an overlay as @aeschli suggests which is probably more work

**Comment by chryw** [comment]
@bpasero @isidorn should I make a tiny symlink overlay icon in svg without color (#000000), and let the code handle color changing? 

BTW this is our usual symlink file icon -
![image](https://user-images.githubusercontent.com/7075677/35948717-caec614c-0c22-11e8-9a4e-8df3ccd00649.png)

[SymlinkFile_16x_vscode.zip](https://github.com/Microsoft/vscode/files/1705239/SymlinkFile_16x_vscode.zip)

**Comment by Kroc** [comment]
Does this indicate hard-links on Windows? Even though hard-links are supposed to be entirely transparent, you can easily confuse yourself if you edit a file in one folder and unexpected changes are occurring in another folder. Whilst the presence / use of hard-links are rare on Windows, they do exist and recent versions of Git allow the use of hard-linking where before soft-links were used.

**Comment by netpoetica** [comment]
From what I can see, symlinks do not show up in File Explorer at all - am I missing something? Let alone having a nice icon next to them or colorization, they just are not present

**Comment by PKief** [comment]
@netpoetica The feature was shipped with the latest release of VS Code. Symlinks are indicated with the small arrow on the right side in the explorer:

![image](https://user-images.githubusercontent.com/12248527/38211519-09c55b36-36bb-11e8-9721-928d84451fef.png)

The arrow is activated by default.

Maybe you should refresh the explorer or restart your VS Code instance.  Make sure that you've installed the latest version of VS Code (1.21.1).

**Comment by netpoetica** [comment]
I think for folders yes, but if it is a symlinked file, I do not see it in VSCode. 

In my case, I have one file inside of a folder:

```
src/
-> myfile.js
```

and then I create a soft link

```
ln -s myfile.js myotherfile.js
```

myotherfile.js is not present in VSCode, even after refresh, close or open
