### ISSUE TITLE
Getting started images for light theme would look better and be more helpful

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115327]
Maybe this isn't worth the effort because the dark theme is the default, but a light theme would not only make things look nicer but also be more helpful because the image will actually look like what it's trying to teach.

![image](https://user-images.githubusercontent.com/2193314/106183287-e5792100-6154-11eb-9c51-951958255a13.png)

**Comment by digitarald** [comment]
Right now all images for codespaces specifically are all light while all VS Code specific ones are dark.

As the original focus is codespaces, I can make all images using the light theme for now. Vector images that pick up the theme colors might eventually help with this.

**Comment by Tyriar** [comment]
A different set of images for each theme.

**Comment by JacksonKearl** [comment]
Images can now be optionally specified as `{light: 'light/somepath', dark: 'dark/somepath', hc: 'hc/somepath'}`.

**Comment by bpasero** [comment]
I still see dark images:

![image](https://user-images.githubusercontent.com/900690/109015539-80faa480-76b5-11eb-9487-1e5482493781.png)

**Comment by JacksonKearl** [comment]
Added support for light theme images but it isn't out on all items. I believe "settings" is the only one to support. We can keep this issue open to track adopting the new API.

**Comment by digitarald** [comment]
Fixed by f7cc0f2c79de6e7df16c6171e30c4ac4826c76b5.

**Comment by rzhao271** [comment]
\closedWith f7cc0f2

**Comment by rzhao271** [comment]
High-contrast images for the steps shown in the screenshot seem to be missing

![hc-missing](https://user-images.githubusercontent.com/7199958/112656837-071e1e00-8e0f-11eb-9644-18c3d42abee6.PNG)
