### ISSUE TITLE
TS papercut: import should prefer type-correct import

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115370]
I often end up importing the wrong type when methods have the same name (such as `isEqual`). I do not understand why we cannot suggest the correct import for the type that is passed in. Even worse, when I do "Add all imports", I end up with the wrong one.

![recording](https://user-images.githubusercontent.com/900690/106244280-f97f5a00-620a-11eb-8b77-a55af2563dc0.gif)

**Comment by bpasero** [comment]
//cc @egamma (since you ask me for TS papercuts often)

**Comment by mjbvz** [comment]
Can you please add a specific example in our codespace where the happens?

**Comment by bpasero** [comment]
@mjbvz steps:
* open `src/vs/workbench/contrib/files/browser/files.contribution.ts`
* remove the existing `isEqual` import
* go to the compile error
* press `Ctrl+.` to bring up quick fix

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/42615 to track upstream
