### ISSUE TITLE
TS: JSDoc does not allow me to reference an exported type

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115380]
I am in a JS file (`bootstrap.js`) and want to declare a type in JSDoc comment like so:

```js
/**
 * @returns {typeof import('./vs/base/parts/sandbox/electron-sandbox/globals').ISandboxNodeProcess}
 */
function safeProcess() {
	if (typeof process !== 'undefined') {
		return process; // Native environment (non-sandboxed)
	}

	const globals = safeGlobals();
	if (globals) {
		return globals.process; // Native environment (sandboxed)
	}
}
```

I am getting an error: 

``
Namespace '"/Users/bpasero/Development/Microsoft/monaco/src/vs/base/parts/sandbox/electron-sandbox/globals"' has no exported member 'ISandboxNodeProcess'.ts(2694)
```

**Comment by mjbvz** [comment]
`ISandboxNodeProcess` is a type (an interface) so you should not use `typeof` here. If I use:

```ts
/**
 * @returns {import('./vs/base/parts/sandbox/electron-sandbox/globals').ISandboxNodeProcess}
 */
```

Then it seems to work for me

**Comment by bpasero** [comment]
Thanks you are right 👍
