### ISSUE TITLE
Can't submit the code

### ISSUE THREAD

**Issue by INTMIN** [microsoft/vscode#115379]
Issue Type: <b>Bug</b>

I can't submit the code  The git window cannot be clicked 

and Console error：

[0129/172541.800:ERROR:registration_protocol_win.cc(103)] CreateFile: ϵͳ�Ҳ���ָ�����ļ��� (0x2)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.42GB free)|
|Process Argv|--folder-uri file:///e%3A/work/qianchuan/aisuperstar-evo --crash-reporter-id 8fd7fba4-de6d-4c4a-af90-a5d7237570e2|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
react-hooks-snippets|AlD|1.2.0
simple-react-snippets|bur|1.2.3
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-mysql-client2|cwe|3.4.3
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.1.3
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.13
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.10
search-node-modules|jas|1.3.0
sftp|lix|1.12.9
vscode-language-babel|mgm|0.0.30
code-beautifier|mic|2.3.3
vscode-language-pack-zh-hans|MS-|1.52.2
remote-wsl|ms-|0.52.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
sqltools|mtx|0.23.0
miniapp-helper|ove|1.0.3
vscode-versionlens|pfl|1.0.9
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
js-jsx-snippets|sky|10.1.0
autoimport|ste|1.5.3
pdf|tom|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.1.0
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by INTMIN** [comment]
![image](https://user-images.githubusercontent.com/30612388/106721195-55007c00-663f-11eb-916a-ddb84cc1f79a.png)

**Comment by INTMIN** [comment]
This is the Dom ,I can not click and Submission code，only add . Just like commit doesn't work，It happened again and again.I have to reopen it .Sometimes it doesn't work to reopen it.

**Comment by eamodio** [comment]
I believe this has been fixed in 1.53, can you try it out and report back? Thanks!

**Comment by INTMIN** [comment]
> I believe this has been fixed in 1.53, can you try it out and report back? Thanks!


Yes, I was busy in the last period, but I didn't pay attention to it, but the problem was solved. Thank you
