### ISSUE TITLE
Invalid argument to notebook.cell.execute is ignored

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#115326]
Verifying https://github.com/microsoft/vscode/issues/114583

- Have this code in an extension command `vscode.commands.executeCommand('notebook.cell.execute', vscode.Uri.file('/blah'));`
- Open a notebook and run the command
- The current cell is executed

If I pass an invalid URI it should probably throw or do nothing

**Comment by rebornix** [comment]
maybe it should throw.
