### ISSUE TITLE
Cap size of the getting started images

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115325]
The image itself is very large and probably shouldn't be. If we do this the core may need a change to not stretch the image.

![image](https://user-images.githubusercontent.com/2193314/106182799-350b1d00-6154-11eb-8507-2a455fbb8d97.png)

**Comment by JacksonKearl** [comment]
We could prevent scaling images over their natural height? cc @digitarald would that work for you?

**Comment by Tyriar** [comment]
Yeah I think we should do that, but that alone wouldn't fix above due to the huge size of the image. Also consider how HDPI screenshots show up on standard dpi monitors

**Comment by digitarald** [comment]
> We could prevent scaling images over their natural height?

These are 800x600 and exported with 1.5 dpi, so 1200x900. The images should not scale beyond 800px width, but there will be some blur for hdpi screens if we don't export with 2 dpi.

I agree though that the max image size can be scaled down a bit in the design.

**Comment by JacksonKearl** [comment]
Now scaling all images to 66% under assumption they're exported at 1.5x (max-width is still 800px). This means smaller images can be used where needed and they wont grow past their proper width.

**Comment by bpasero** [comment]
I am still seeing a very large image:

![image](https://user-images.githubusercontent.com/900690/109015772-c5864000-76b5-11eb-9c42-738c453dcb12.png)

**Comment by JacksonKearl** [comment]
Change was to allow smaller images but hasn't been adopted yet. cc @digitarald we can use a smaller image there and it should work fine so long as we still have it at 1.5x scale.

**Comment by connor4312** [comment]
Images now seem modestly sized

![](https://memes.peet.io/img/21-03-dc89698f-9fb3-4592-a717-0fb99b033f00.png)
