### ISSUE TITLE
Add 'Copy Reference' as editor context menu natively in VS Code

### ISSUE THREAD

**Issue by iamzhout** [microsoft/vscode#115361]
Early in 2016 there is already a feature request for this, but rejected and closed in 2018. https://github.com/microsoft/vscode/issues/12518
> We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the VS Code Marketplace. Just in case, in a few simple steps you can get started writing your own extension. See also our issue reporting guidelines.

However I don't quite agree with the logic, keep VS Code lean not mean to leaving all basic/common function to VS Code extension, to recommend using a plugin created in 2016 ([plugin Relative path and line](https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line)), which doesn't work in Remote-SSH mode:
![image](https://user-images.githubusercontent.com/14846203/106227448-2855fa00-6224-11eb-8418-bdb1a3a54545.png)

in IntelliJ, it just provides `Copy Reference` context menu which I prefer as below:
![image](https://user-images.githubusercontent.com/14846203/106226886-2d667980-6223-11eb-8fec-bcd1e2e6b3d2.png)

**Comment by jrieken** [comment]
#12518 asks for "copy relative path" and we do have that since a while already. not sure what you are still looking for here

**Comment by iamzhout** [comment]
> #12518 asks for "copy relative path" and we do have that since a while already. not sure what you are still looking for here
The title of issue #12518 is somehow not quite accurate to cover all his whole question, what I want is the `Copy Reference` feature as in IntelliJ, which will get relative path and line of code, just like this result: `cmd/kube-apiserver/apiserver.go:31`

**Comment by jrieken** [comment]
@iamzhout The references viewlet as copy as you want it. Is that what you are looking for? A sample is this `802, 3: 		cancelableKernel.controller.dispose();`

<img width="491" alt="Screenshot 2021-04-20 at 15 43 22" src="https://user-images.githubusercontent.com/1794099/115406227-41e95b00-a1ef-11eb-923f-9953982a8ebb.png">
