### ISSUE TITLE
Getting started back button looks unstyled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115316]
![image](https://user-images.githubusercontent.com/2193314/106178468-ab0c8580-614e-11eb-92e7-3a67972674a2.png)

**Comment by JacksonKearl** [comment]
Checked the mocks and they're indeed a bit different, how does this look? cc @misolori 
![image](https://user-images.githubusercontent.com/8586769/106179107-6e8d5980-614f-11eb-8ef4-58bf43dda43e.png)

**Comment by Tyriar** [comment]
Yeah that looks nicer, also moving it above the content would help like in the mockup
