### ISSUE TITLE
Add CompletionTriggerKind.QuickSuggestions or CompletionTriggerKind.Manual

### ISSUE THREAD

**Issue by WilliamVenner** [microsoft/vscode#115343]
Related: #10098

For whatever reason, it appears that both `editor.quickSuggestions`'s suggestions and the user manually invoking completions via `CTRL + Space` have the same `CompletionTriggerKind`, which is... nonsense.

It would be great if a new enumeration was added to differentiate.

### Use case

If my trigger characters are `[")", ".", ":"]` I simply do not want to return any completions for quick suggestions (which appears to eagerly ignore any trigger character rules for completion item provider subscriptions.)

However, I DO want to provide completions if the user manually presses `CTRL + Space` to invoke completions manually.

Both quick suggestions and manual invokation have the same `CompletionTriggerKind` and `CompletionContext.triggerCharacter`

**Comment by jrieken** [comment]
> If my trigger characters are [")", ".", ":"] I simply do not want to return any completions for quick suggestions (which appears to eagerly ignore any trigger character rules for completion item provider subscriptions.)

Quick suggestions and trigger characters are not related, quick suggestion triggers suggestion when type at a word end, trigger characters happen when you type one of those characters.
