### ISSUE TITLE
Command Palette (Ctrl+Shift+P): Should offer "Open active Theme (JSON)"

### ISSUE THREAD

**Issue by schittli** [microsoft/vscode#115332]
In vscode it is very tedious to every time search the json-file of the active theme to edit it.
**Therefore, it would be great if the Command Palette (Ctrl+Shift+P) would offer the command:**
**_Open active Theme (JSON)_**

Thanks a lot, kind regards
Thomas

**Comment by aeschli** [comment]
Why would you edit the JSON of a theme? That's not what you should do unless you are the developer of a theme, but then the workflow is different.

Read [here](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) how to customize a theme.
Read [here](https://code.visualstudio.com/api/extension-guides/color-theme) how to develop a theme.
