### ISSUE TITLE
Getting started "Tweak My Settings" resets the getting started page

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115318]
![recording (59)](https://user-images.githubusercontent.com/2193314/106179251-9da3cb00-614f-11eb-8364-355667e821f2.gif)

**Comment by JacksonKearl** [comment]
Oh, weird. Previously the view state of getting started would be saved and restored on changing tabs but looks like that isn't happening anymore for some reason.

**Comment by Tyriar** [comment]
This was in codespaces, maybe that's it (webview vs iframe)?
