### ISSUE TITLE
NPM Scripts pane very slow to load/refresh

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#115384]
Issue Type: <b>Bug</b>

The NPM Scripts pane takes about 10 seconds to load or refresh. This happens after reloading the window, and often happens after expanding the pane, too.

I am using a monorepo in a dev container. There's nothing unusual about my setup; there are a few scripts defined in the root `package.json`, and a few more defined in each of the 6 workspaces within.

An animated loading indicator appears at the top of the pane during this process:

![image](https://user-images.githubusercontent.com/1505561/106261984-9bf70780-6222-11eb-8d5e-8c90661d2e9e.png)

If you try to run any of the scripts in the list while this process is underway, an error notification appears:

> Error running command npm.runScript: Cannot read property 'task' of undefined. This is likely caused by the extension that contributes npm.runScript.

I first noticed this behaviour change in the last 1-2 months. Prior to this, I recall the pane loading and refreshing instantly (I definitely didn't need to wait 10 seconds after expanding the pane before I was able to run a script).

I cannot find any output to diagnose the delay.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.52GB (11.18GB free)|
|Process Argv|--crash-reporter-id a9305738-51b5-4cca-ac9d-97e8b1880520|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Web Apps|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.68GB (17.01GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Function Apps|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.68GB (17.01GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.155.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244:30250195
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by alexr00** [comment]
@aaronadamsCA can you try setting the setting `	"npm.packageManager"` to your specific package manager? It defaults to `auto` now, and I suspect that's where the slowdown is. Once I know for sure that that's where the slowdown is coming from, I'll look into improving it.

**Comment by aaronadamsCA** [comment]
Thanks @alexr00, I can confirm setting `"npm.packageManager": "yarn"` works around the slowdown. 🙌

If it helps, the delay is consistently 8 seconds long. I experienced it both before and after switching the project from NPM (multiple `package-lock.json` files) to a Yarn workspace (single `yarn.lock` file).

If I remember correctly, the slowdown started around the release of 1.51. It's also reproducible on Insider.

**Comment by alexr00** [comment]
Since the slowdown is around `auto`, I know where to start improving.

**Comment by alexr00** [comment]
\closedWith 3973012a9cd6184611a0b7373a074ac08c5fe0e8

**Comment by aaronadamsCA** [comment]
It is improved, down from 8 seconds to ~2.5 seconds for first load and ~1.5 seconds for refresh. I can live with that!

**Comment by alexr00** [comment]
@aaronadamsCA thanks for testing this change!

It's still slower than before because with `auto` we still need to check which package manager to use for each folder. Not ideal, but then you do get automatic package manager detection out of it. For your case, I would recommend setting `"npm.packageManager"` so that the extra work isn't done.
