### ISSUE TITLE
Low quality images in getting started

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115324]
It seems like all images are poorly encoded, they're png though so they shouldn't be. Were they exported using a limited color set or something?

Examples:

![image](https://user-images.githubusercontent.com/2193314/106182588-e78eb000-6153-11eb-8ad8-1c1ade49d01b.png)
![image](https://user-images.githubusercontent.com/2193314/106182639-faa18000-6153-11eb-996a-0af640201b4a.png)
![image](https://user-images.githubusercontent.com/2193314/106182662-042ae800-6154-11eb-9e58-ed67537674ae.png)

**Comment by digitarald** [comment]
They've been lossy compressed using [pngquant](https://pngquant.org/). The current images are are lowest (40%) quality, so I have some room to increase quality while trading off size.

**Comment by Tyriar** [comment]
Full color pngs are typically still really small unless you're working with photos. I'm all about perf but a few extra kbs are totally worth not having this blurriness/bad dithering.

**Comment by digitarald** [comment]
Solved by using SVGs across all images.
