### ISSUE TITLE
[loc][Query][VSCode] Please clarify "languages"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#11538]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Associates languages to icons. The object key is the language id as defined in the language contribution point.

File Name:
src\vs\workbench\services\themes\electron-browser\themeService.nls.resx

Resource ID:
".resx", 0; "schema.languageIds"

Query:
Does it refer to programming language or language such as English, spanish...?	
Cristina Carrasco	9/5/2016 10:10:11 AM

**Comment by aeschli** [comment]
It refers to programming languages.
