### ISSUE TITLE
no shader icons

### ISSUE THREAD

**Issue by Med-H** [microsoft/vscode#115335]
glsl icons are shown as standard text files.

**Comment by Med-H** [comment]
> /needsMoreInfo

I dunno how to describe it, maybe an image is a better description. here is an extract from the explorer tab

![image](https://user-images.githubusercontent.com/74670211/106570777-a07b3300-6536-11eb-9edf-0a3e1922e293.png)

as you can notic there are no standard icon for openGL glsl shader files.

**Comment by aeschli** [comment]
The icons come from https://github.com/jesseweed/seti-ui. Please file the request there (or make a PR if you have an icon for glsl)
