### ISSUE TITLE
Extension bisect not working with remote container

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#115383]
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2 19042.746

I'm trying to do an extension bisect on a remote container. When it starts, I see this helpful notification:

> ![toast](https://user-images.githubusercontent.com/1505561/106260024-40c41580-6220-11eb-8aed-27c9742765fa.png)
>
> Extension 'Remote - Containers' is required to open the remote window. OK to enable?

Unfortunately when I click "Enable and Reload", the window reloads but the remote container extension is still disabled. I just get the same prompt over and over again, and I can't start the bisect.

Does this issue occur when all extensions are disabled?: N/A

**Comment by gjsjohnmurray** [comment]
#112473 suggest this is fixed in the upcoming 1.53 release, which should be out by this time next week. Meanwhile are you able to use [Insiders](https://code.visualstudio.com/insiders/)?

**Comment by aaronadamsCA** [comment]
I just updated Insiders and tried it out - I can confirm this broken dialog doesn't exist anymore, and instead the extension is automatically excluded from the bisect. Thanks, and sorry for not finding that myself!

**Comment by gjsjohnmurray** [comment]
Thanks for confirming.

/duplicate
