### ISSUE TITLE
Notebook showtabs false results in accidental multiline title

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115353]
Version: 1.53.0-insider (user setup)
Commit: 2ce26643d85bf985d3d3ce6ce0ff5d78866f9b5f
Date: 2021-01-28T13:54:01.170Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

1. Set `"workbench.editor.showTabs": false`
2. Go into a notebook and click into a cell
3. 🐛 Part of the title seems unaligned, as though it's multiline when it's not supposed to be
![notebook-names](https://user-images.githubusercontent.com/7199958/106212768-25093280-6180-11eb-9ad0-4118cc6f99ff.PNG)

**Comment by kieferrm** [comment]
The breadcrumb entry for a code cell is misaligned.

**Comment by jrieken** [comment]
Likely wraped the line and therefore shows like that...

**Comment by jrieken** [comment]
Doesn't happen with document symbols, so adding for Feb

**Comment by jrieken** [comment]
This is actually more severe than I thought... It happens with all notebook breadcrumbs when a file icon theme is used...
