### ISSUE TITLE
Hover: clicking on a source link does not work in web

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115381]
Steps to Reproduce:

1. open `vscode.d.ts` in web selfhost
2. hover over something that has a link
3. click it

![image](https://user-images.githubusercontent.com/900690/106258801-9d263580-621e-11eb-8015-a03a0b720d36.png)

=>

![image](https://user-images.githubusercontent.com/900690/106258772-90094680-621e-11eb-81f4-615bae60a902.png)

**Comment by mjbvz** [comment]
These links also doesn't work on desktop (the links are in a special format the only our built-in extension editing extension understand): 

<img width="539" alt="Screen Shot 2021-01-29 at 1 18 57 PM" src="https://user-images.githubusercontent.com/12821956/106328372-8c80ba00-6234-11eb-977a-5b123b0d8682.png">

We are tracking https://github.com/microsoft/TypeScript/issues/35524 which would let us use standard JSDoc tags for links instead
