### ISSUE TITLE
Getting started is not vertically aligned in center 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115328]
This was called out in https://github.com/microsoft/vscode/issues/111753 but not done exactly, maybe intentional?

![image](https://user-images.githubusercontent.com/2193314/106184454-671d7e80-6156-11eb-924c-f491f3e539fc.png)

It's due to how `.gap' works:

![image](https://user-images.githubusercontent.com/2193314/106184603-a0ee8500-6156-11eb-9e03-f7524e31e698.png)

**Comment by JacksonKearl** [comment]
This was intentional. It looks kinda odd in the center... cc @misolori

**Comment by Tyriar** [comment]
Let's close this then, just making sure it was intentional.

**Comment by misolori** [comment]
yea that is intentional, it's "almost centered" 😄
