### ISSUE TITLE
Can not retrieve source from org

### ISSUE THREAD

**Issue by karuny** [microsoft/vscode#115364]
Issue Type: <b>Feature Request</b>

I am unable to retrieve source from org but I am able to deploy source to org.
Also I am not able to retrieve source in manifest from org

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Are you using a Salesforce extension? If yes, please report the issue to the extension repository and close this one.

**Comment by karuny** [comment]
thanks
