### ISSUE TITLE
the ' intergrated Terminal ' outputs unreadable ascii characters

### ISSUE THREAD

**Issue by uglybugs** [microsoft/vscode#115369]
[We](url) have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

1) installed VS code
2) install Microsoft Python extensions
3) launched VS code and created file " simple.py" ------> print("simple output")
4) saved file 
5) Ctrl  & F5  to run

6) ' intergated Terminal ' outputs random ascii characters

system : Raspberry Pi - Buster 10
have also install VS code on a brand new image without any additional programs or applications installed with identical results - unreadable text in the ' integrated Terminal ' window. Shown below:

![2021-01-29-072857_1920x1080_scrot](https://user-images.githubusercontent.com/75214913/106245199-03518f00-6204-11eb-874a-97aeb83d16af.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:35.090Z)
OS version: Linux arm 5.4.83-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|0.90GB (0.10GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id f39243d2-8505-4c31-acbe-1d7d12154df3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|LXDE-pi|
|XDG_CURRENT_DESKTOP|LXDE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.22.0
better-cpp-syntax|jef|1.15.5
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.3
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0-insiders3
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3577
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
python|tht|0.2.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244cf:30250196
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by uglybugs** [comment]
i also see the  unreadable characters in the integrated Terminal when using C/C++

**Comment by luabud** [comment]
hey @meganrogge, this issue is not Python specific, we don't control what is written on the terminal. It also happens when using the C/C++ extension.
Do you mind reopening it?
