### ISSUE TITLE
[json] completion suggests items already there: improve error recovery

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11537]
- open settings JSON
- find a setting that is already configured
- put cursor one line below, completion does have it
- put cursor one line above 🐛 completion has it

![sep-05-2016 12-26-21](https://cloud.githubusercontent.com/assets/1794099/18245183/2d5b59fe-7364-11e6-89c2-10e55fb62a5c.gif)

**Comment by aeschli** [comment]
Existing properties are normally not proposed but in the example there's a syntax error that prevents that the next property is correctly parsed.
