### ISSUE TITLE
How to force VSCode to use default PostCSS syntax <style> tag?

### ISSUE THREAD

**Issue by xxSkyy** [microsoft/vscode#115342]
I cant set vscode to mark tags in vue component as postcss syntax.
Is totally not a solition here as I figured it to work assets stopped loading by default but I dont want to struggle with webpacker for it. I want force tag as postcss from vscode side. How can I do it? 
If I cant please add this feature

**Comment by IllusionMH** [comment]
VS Code does not provide support for Vue temple files, so most likely better place will be in Vetur extension repo.
