### ISSUE TITLE
Python core extension cannot be installed in a codespace environment via a url

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#115344]
From issue https://github.com/microsoft/vscode-jupyter/issues/4512. The Jupyter extension uses a simple uri to cause an install of the Python extension to get installed. This fails per the following: 

![image](https://user-images.githubusercontent.com/11685408/106202900-71984200-616f-11eb-955b-5ad50e885057.png)

**Comment by rchiodo** [comment]
Example of the URI we use:

```"vscode-insiders:extension/ms-python.python"```

We do an env.openExternal on that UI. This is failing when running in codespaces.

**Comment by misolori** [comment]
It would make sense for VS Code to convert all internal URLs (Stable/Insiders/etc) to one the current Codespace can open.

**Comment by jakebailey** [comment]
Related is https://github.com/microsoft/vscode-python/issues/14264#issuecomment-703790367 since I do this same thing in the Python extension to link to Pylance's marketplace entry.

**Comment by joaomoreno** [comment]
@rchiodo If the intent is to drive the user back into Code, why leave it at all via a URL? Why can't the notification action simply call back into the extension directly?

**Comment by jakebailey** [comment]
VS Code provides no API to open the marketplace entry for an extension (though it has the API under the hood for the "recommended extension" popup). Using:

```ts
vscode.env.openExternal(`${vscode.env.uriScheme}:extension/<some ID>`)
```

is the only way to do it. There's a command to open a search with an ID, but it only searches and does not actually open up the page for the extension.

**Comment by joaomoreno** [comment]
@sandy081 Can you get us a command to open a specific Marketplace extension?

**Comment by jakebailey** [comment]
FWIW this is probably actually #111814, but adding a command specifically to open the marketplace entry is a workable fix.

**Comment by sandy081** [comment]
There is a command `workbench.extensions.search` that searches for extensions

https://github.com/microsoft/vscode/blob/56dfaf8b98551573e4f75c823d62150581f5bd8a/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L260-L271

**Comment by sandy081** [comment]
If it is to open extension in editor - here is the command `extension.open`

https://github.com/microsoft/vscode/blob/7690293ae208f91f4e3612e309ac130a85244486/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L181-L191

**Comment by jakebailey** [comment]
Thanks; I wasn't aware of the above. It appears to do exactly what we need (and in fact works better for debugging, since the old call would open the URL in whatever VS Code window happened to be open, e.g. where we were debugging).

**Comment by joaomoreno** [comment]
Closing this then. 👍 Thanks @sandy081
