### ISSUE TITLE
Cannot disable unpublished extension anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115398]
* create an extension e.g. `package.json`
```js
{
    "name": "115307",
    "authors": "alex",
    "version": "1.0.0",
    "engines": { "vscode": "^1.22.0" },
    "activationEvents": ["*"],
    "main": "index.js"
}
```
* `index.js`
```js
console.log(`hello world`);
```

Run `scripts\code.bat` and see:

The extension cannot be disabled:
![image](https://user-images.githubusercontent.com/5047891/106277161-e84d4200-6238-11eb-9c70-ac47b1d75730.png)

**Comment by sandy081** [comment]
@alexdima It seems the extension does not has proper publisher. Please change `authors` to `publisher`.

**Comment by sandy081** [comment]
If publisher is not provided, then extension id will be `undefined.115307` and it seems there is mismatch between extension running with extension shown in UI.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/10746682/106280524-56483800-623e-11eb-9c0b-0f62a3a5dbbf.png">

**Comment by alexdima** [comment]
You're right, sorry my bad.
