### ISSUE TITLE
Getting started pressing enter when when the step has focus does nothing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115323]
Repro:

1. Open getting started
2. Go into one of the items
3. Click on an entry
4. Press enter (does nothing)
5. Shift+tab
6. Press enter
7. Press enter (does nothing)

I think it should either toggle visibility for that step or focus the button

**Comment by JacksonKearl** [comment]
What platform? Seeing this work correctly on MacOS.

**Comment by Tyriar** [comment]
Windows

**Comment by JacksonKearl** [comment]
The action button will now get focus when a block is expanded
