### ISSUE TITLE
Editor reopen scenarios

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#115329]
We have now multiple editor view types in the workbench core now, they don't necessarily know about each other and they rely on the editor service to behave properly when users try to open a document. It gave us a lot of trouble as they sometime conflict with each other. This issue will try to list all potential scenarios for custom editor, notebook, untitled, etc.

* Open from file explorer
  * ✅ Editor service will get all available editor view types, e.g., text editor, 2 custom editor view types, 2 notebook editor view types. Editor service read `workbench.editorAssociations` to decide which one to use.
  * ✅ Users use action *Open With...* from file explorer context menu to force open a document with specified view type.
* Double click editor tab
  * ❓ Editor service tries to open the same editor input with new options (`pinned`), it goes through the `editorOverride` logic again
* Switch editor view type through action *Reopen Editor With...* 
  * ✅ Switch from an unpinned editor. It should always replaces current editor (by closing it) with a new editor. 
  * ❓ Switch from an pinned editor
  * ❓ Switch from an untitled text editor
  * ❓ Switch from a dirty editor
* Toggle editor view type
  * ❓ It should always replace current editor, no matter what state it's in?
* Open the same document in another editor group
  * ❓ Some custom* editor might not allow that, the knowledge should be shared with editor service
* Open the same resource with a different editor view type in another editor group
  * ❓ Some custom* editor might not allow that (e.g., notebook), the knowledge should be shared with editor service
* Move an editor from one editor group to another
  * ✅ Custom* editors may want to reuse the editor widget

**Comment by lramos15** [comment]
@rebornix Should we revisit this in the May iteration and tackle these once the overrideService matures?

**Comment by rebornix** [comment]
@lramos15 yup, sounds good to me. Or we make this a test plan item.

**Comment by mjbvz** [comment]
Closing this since I think it was part of planning/discussion
