### ISSUE TITLE
Search use ignore file does not work

### ISSUE THREAD

**Issue by korakotlee** [microsoft/vscode#115352]
- VSCode Version: 1.52.1
- OS Version: Ubuntu SMP Tue Jan 5 21:23:50 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. go to Search Preference, uncheck Search:Use ignore Files
2. search include ignored files
3. go to check Search:Use ignore Files
4. search still include ignored files

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by korakotlee** [comment]
![image](https://user-images.githubusercontent.com/23171381/106212954-eaf05e80-6188-11eb-8d47-c419af38e2c0.png)

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/106214596-067a5a00-61c7-11eb-97a0-9a45c2a82da4.png)

The highlighted message is telling you that you have deselected the indicated toggle button. Click that button and all should be well.

**Comment by korakotlee** [comment]
Wow, I've been living with this for years.
Clicking on the cog really works!
Thank you

**Comment by roblourens** [comment]
Glad you found a solution, thanks @gjsjohnmurray.

@korakotlee it's very common for people to miss this button. Do you have any ideas for how to make it more obvious? Did you notice the underlined message?

**Comment by korakotlee** [comment]
maybe a little help icon that when click show a tooltip
<img width="46" alt="Screen Shot 2021-01-29 at 9 10 00 PM" src="https://user-images.githubusercontent.com/23171381/106346741-60862880-6276-11eb-9181-5a7e815a0042.png">

"exclude settings and ignore files are disabled - <ins>enable</ins>"
