### ISSUE TITLE
VScode won't open on mac

### ISSUE THREAD

**Issue by d3utu** [microsoft/vscode#115306]
- VSCode Version: latest version on 28 january
- OS Version: macOS Big Sur 11.1

Steps to Reproduce:

1. Downloaded latest zip file on. the website
2. Used archive utility to extract the .app file
3. Tried to open the app
4. The app gets in the dock but closes instantly
5. I gave the app all the authorization in System and Preferences

Does this issue occur when all extensions are disabled?: No, I haven't been able to add any extensions yet

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by d3utu** [comment]
From what I understand I should open vscode go to Help/Toggle Developer Tools, and then in the console type code --verbose. But I can't open code. I think I haven't understood what you asked me to do.

**Comment by bpasero** [comment]
Yeah I realised that. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by d3utu** [comment]
Ok, I have downloaded indsiders
![Screenshot 2021-01-29 at 10 05 51](https://user-images.githubusercontent.com/73715542/106255989-02782780-621b-11eb-928e-5e55bcf2eee6.png)

**Comment by d3utu** [comment]
I have checked those files don't exist, so I suppose this message means that vscode wants the access so it can create those directories?

**Comment by d3utu** [comment]
I have gave it the permissions it works thank you very much, may I ask what is the difference between the insiders version and the stable one?

**Comment by d3utu** [comment]
Ok now the stable version also works, I think it was a permission problem, the thing is that the stable version didn't give me any feedback
