### ISSUE TITLE
Snap version Vscode  cannot use iBus Input  in Ubuntu 20.10

### ISSUE THREAD

**Issue by Mark24Code** [microsoft/vscode#115399]
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.10

```
Vscode About Detail:

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-41-generic snap
```

Steps to Reproduce:

1. Just open Vscode
2. Cannot use ibus input.

Does this issue occur when all extensions are disabled?: Yes

# [This may be help: failed-to-input-chinese-in-many-snap-apps ](https://forum.snapcraft.io/t/failed-to-input-chinese-in-many-snap-apps/7251)

**Comment by joaomoreno** [comment]
#96041
