### ISSUE TITLE
GitHub issues notebook results sometimes don't show

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115350]
While trying to verify #112180 with the steps given by https://github.com/microsoft/vscode/issues/112180#issuecomment-765819299:

![no-output](https://user-images.githubusercontent.com/7199958/106210758-48ca7980-617c-11eb-9abe-63a002b497cc.PNG)

The results aren't showing up, but the console doesn't give any error either.
Sometimes the results show after a reload so this isn't the easiest to reproduce.

Version: 1.53.0-insider
Commit: 2ce26643d85bf985d3d3ce6ce0ff5d78866f9b5f
Date: 2021-01-28T13:48:59.430Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.53

**Comment by rebornix** [comment]
It can happen when sometimes the result is empty. We should probably give better hint for this.

**Comment by rzhao271** [comment]
Cannot repro now
