### ISSUE TITLE
[loc][Query][VSCode] More context for "Language"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#11534]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Languages ({0})

File Name:
src\vs\workbench\parts\extensions\electron-browser\extensionEditor.nls.resx

Resource ID:
".resx", 0; "languages"

Query:
Can you please clarify whether language here refers to a programming language  or a natural language (English, Spanish.,, etc.)? Thanks!
(es)

**Comment by joaomoreno** [comment]
It refers to programming languages.
