### ISSUE TITLE
Ctrl+C/Ctrl+V randomly stop copying/pasting

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#115396]
Issue Type: <b>Bug</b>

I don't know why this starts happening, it just randomly happens several times a day for me.

Pressing Ctrl+C or Ctrl+V will not have the desired effect (copy/pasting). Ctrl+X and many other hotkeys still behave as expected. If more hotkeys are affected is currently not clear.

In the state where the hotkeys do not work, I can still see the event being received fine in the hotkey troubleshooter:
```
[2021-01-29 13:15:44.728] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyC, keyCode: 67, key: c
[2021-01-29 13:15:44.728] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyC, keyCode: 33 ('C')
[2021-01-29 13:15:44.728] [renderer1] [info] [KeybindingService]: | Resolving ctrl+C
[2021-01-29 13:15:44.729] [renderer1] [info] [KeybindingService]: \ From 7 keybinding entries, matched editor.action.clipboardCopyAction, when: no when condition, source: built-in.
```

Manually invoking the _Copy_ action from the command palette will also work as expected. Using the context menu to copy also works as expected.

Reloading the window always resolves the issue and the hotkeys will again work as expected.

As I require my extensions to work, and this happens apparently randomly, it's hard to try to see if it reproduces without extensions. Also, if any of my extensions is causing this, I'd like to find out. If someone can suggest another way of tracing the root cause, I'd appreciate it.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (29.63GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (21.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (21.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (21.65GB free)|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.3.1
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.1.0
vscode-zipfs|arc|2.2.2
vsc-prolog|art|0.8.23
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.8.0
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-graphql|Gra|0.3.13
terraform|has|2.5.0
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
template-string-converter|meg|0.4.7
code-beautifier|mic|2.3.3
vscode-lebab|mrm|2.6.0
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
js-debug-nightly|ms-|2021.1.2617
vscode-js-profile-flame|ms-|0.0.13
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.20
vscode-yaml|red|0.14.0
lit-plugin|run|1.2.1
language-pde|Tob|1.4.6
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by chuangshizhiqiang** [comment]
Have the same issue, and other software is ok.

**Comment by chuangshizhiqiang** [comment]
We need fix

**Comment by oliversalzburg** [comment]
While troubleshooting again, I noticed that only Ctrl+V seems to have been affected this time, Ctrl+C actually worked fine. The troubleshooter shows:

```
[2021-02-17 12:45:07.788] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyV, keyCode: 86, key: v
[2021-02-17 12:45:07.788] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyV, keyCode: 52 ('V')
[2021-02-17 12:45:07.789] [renderer1] [info] [KeybindingService]: | Resolving ctrl+V
[2021-02-17 12:45:07.789] [renderer1] [info] [KeybindingService]: \ From 4 keybinding entries, matched workbench.action.terminal.paste, when: terminalFocus && terminalProcessSupported, source: built-in.
```
This seems completely wrong to me. The terminal is not in focus.

After clicking back and forth between an editor and the terminal, it seems to get unstuck, but pasting still doesn't work.

```
[2021-02-17 12:46:40.460] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyV, keyCode: 86, key: v
[2021-02-17 12:46:40.460] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyV, keyCode: 52 ('V')
[2021-02-17 12:46:40.461] [renderer1] [info] [KeybindingService]: | Resolving ctrl+V
[2021-02-17 12:46:40.461] [renderer1] [info] [KeybindingService]: \ From 4 keybinding entries, matched editor.action.clipboardPasteAction, when: no when condition, source: built-in.
```

**Comment by oliversalzburg** [comment]
I'm now also seeing this in 1.53.2 on another machine and with more shortcuts. Ctrl+Home and Ctrl+End would stop working.

**Comment by alexdima** [comment]
cc @Tyriar See https://github.com/microsoft/vscode/issues/115396#issuecomment-780502890 . It looks like sometimes `terminalFocus` is set when the terminal is not focused.

**Comment by oliversalzburg** [comment]
After about a hundred more times of this happening, it does indeed seem to be broken focus detection.

I'm trying to narrow it down further. My current best guesses are:

- Conflicts resulting from calling `terminal.show();` from an extension in certain states.
- Conflicts resulting from focus-adjusting hotkeys (starting a debug session).
- Conflicts resulting from hitting a breakpoint during debugging.

**Comment by Tyriar** [comment]
Will investigate this today/tomorrow

**Comment by Tyriar** [comment]
Speculative fix: https://github.com/microsoft/vscode/pull/117716

**Comment by oliversalzburg** [comment]
I will gladly switch to Insiders for a week to verify this, if I don't hit any road blocks with it

**Comment by Tyriar** [comment]
@oliversalzburg it will be going in the next iteration which is probably a week out, after we release 1.54

**Comment by heartacker** [comment]
so Confused me so that I thought my computer was slowing down

**Comment by oliversalzburg** [comment]
Not sure if I'm too early, but this is not fixed in the build I currently have:
```
Version: 1.55.0-insider (user setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by Tyriar** [comment]
Not sure what could be causing this unfortunately.

**Comment by treeder** [comment]
Same issue here after upgrading to 1.54.3.

**Comment by heartacker** [comment]
> Not sure what could be causing this unfortunately.

After I disabled the extension *bracket pair colorizer 2*, it seems better.

**Comment by oliversalzburg** [comment]
Still seeing the same pattern btw:
```
[2021-04-07 14:54:40.723] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2021-04-07 14:54:40.726] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-04-07 14:54:40.726] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-04-07 14:54:40.837] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: KeyV, keyCode: 86, key: v
[2021-04-07 14:54:40.837] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: KeyV, keyCode: 52 ('V')
[2021-04-07 14:54:40.837] [renderer1] [info] [KeybindingService]: | Resolving ctrl+V
[2021-04-07 14:54:40.837] [renderer1] [info] [KeybindingService]: \ From 4 keybinding entries, matched workbench.action.terminal.paste, when: terminalFocus && terminalProcessSupported, source: built-in.
[2021-04-07 14:54:41.245] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
```

It still seems to believe I have the terminal focused. Closing all open terminals is a sure way to resolve the situation without reloading the window.

Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/112557#issuecomment-745315475 may be a clue. I also see it intermittently, and I'm often editing during debugging too.

Maybe the build instance of Terminal is periodically grabbing focus and occasionally messing up a contextkey?

**Comment by oliversalzburg** [comment]
FWIW, I have a pretty similar setup as mentioned in that comment. Also a preLaunchTask that is executed in the terminal, before focus is switched to the debug console. I also notice the behavior during debugging, as I usually have a debug session running.

**Comment by LoungeFlyZ** [comment]
This is an issue for me in 1.55.2.

**Comment by Tyriar** [comment]
Repro in https://github.com/microsoft/vscode/issues/112557#issuecomment-745315475, trying

**Comment by Tyriar** [comment]
I still couldn't repro, but the timing of https://github.com/microsoft/vscode/commit/0ef0d2d65a3d seems to align around the time we started getting these reports. It's also the most suspicious code touching the terminalFocus context key so I'm going to revert that as it didn't end up fixing the problem anyway.

**Comment by Tyriar** [comment]
This will land in tomorrow's Insiders build, let me know if you see it again if you're using Insiders.

**Comment by Tyriar** [comment]
This issue will probably be a challenge to verify as I never got a solid repro case. Code review should do.

**Comment by oliversalzburg** [comment]
I got the new build. A quick test shows that the new terminal window handling slightly changed a few of my common UI workflows. I used to regularly Ctrl+C in terminals, used by tasks, to get back to my command line terminal.

I will definitely use this version throughout the rest of the week and report back.

**Comment by Tyriar** [comment]
Thanks @oliversalzburg, keep us posted if you hit it again

**Comment by isidorn** [comment]
I trust @oliversalzburg as a committed member of the community -> verified
