### ISSUE TITLE
Conflict corrupts files

### ISSUE THREAD

**Issue by AartIluminacion** [microsoft/vscode#115373]
Issue Type: <b>Bug</b>

I use several machines to code and work on a USB drive (conserving regular backups). Since I change between machines quite frequently and other pueple use these machines in the mean time, I normally do not shut down the machines or Visual Studio Code. This lately has become a problem, because when I insert my USB drive with code that is changed on another machine the changes get corrupted as if files are mixed. I am using Visual Studio Code for olmost a year and this problem came up abouth 10 days ago.
Steps:
- Code to a folder on a USB drive (I use Lua)
- Make changes using the drive in another machine
- Insert to USB in the original machine without closing VBS

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz (6 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (4.57GB free)|
|Process Argv|--crash-reporter-id 1ccfb50c-46f2-4070-ac08-c1d93dfe87a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-lua|gcc|0.1.2
lua|sum|1.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
You are using the Stable build of VS Code. The date in the version string shows that it hasn't changed since the middle of December 2020. So the fact that you say the problem only started about 10 days ago means it's more likely to be caused by a recently-updated extension or a Windows update/change.

**Comment by AartIluminacion** [comment]
Thank you for your quick reply. It is very well possible that the problem
is caused by a Windows update, since I didn't change anything on purpose.

Nevertheless the problem arises only with VSC. I'm not a software engineer
but it seems to me that the automatic save functionality is using pointers
to the drive instead of the directory structure to access the files.
Changing the files outside of the app while the app keeps running, can
change the physical location of the data and will cause the app to read
corrupted data.

Of course this might be caused by a change in how Windows handles the
files, but (since I am using the latest available Windows version) that
doesn't mean that this is not a problem that should be resolved by the VSC
team.

As for now I take care to shut down the app every time I leave a machine
and verify that it is not running before I connect the USB drive, but it is
a little annoying and a little error might cause the loss of valuable data.

Anyway, thank you for your attention and if this problem will be solved I
would be glad to be informed.

A_art Iluminación está en Facebook y en Youtube

**Comment by kieferrm** [comment]
@AartIluminacion can you still please provide more concrete steps? Thank you

**Comment by gjsjohnmurray** [comment]
@AartIluminacion  please also confirm whether or not you always use the mandatory steps to notify Windows that you are about to remove the USB drive. If you are doing that, are you wanting to get the message that kit is safe to remove the drive?

**Comment by AartIluminacion** [comment]
I uninstalled the last Windows update (16th of January) and can not
reproduce the problem anymore.
However, in answer to your question I do confirm that I never take out a
mounted drive.
Anyway I will inform you with more details if the problem arises again in
the future.
Many thanks to all for your support.

A_art Iluminación está en Facebook y en Youtube

**Comment by kieferrm** [comment]
Thank you. I'll close the issue. Please reopen if the problem reoccurs.
