### ISSUE TITLE
Git file system puts (git) behind every path segment

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#115389]
* enable breadcrumbs
* make a change in a ts file, save and stage it
* open staged changes diff
* the path show `(git)` repeatedly

<img width="908" alt="Screenshot 2021-01-29 at 12 08 39" src="https://user-images.githubusercontent.com/1794099/106267989-c056e200-622a-11eb-8339-89d5099299ce.png">

**Comment by joaomoreno** [comment]
The git label provider has been there for a year now: https://github.com/microsoft/vscode/commit/ff2341223702fb4d5cf00d5ec7ced00c506a1b53

It seems that what changed was the resource label, perhaps?

**Comment by joaomoreno** [comment]
Yup broken sometime between last stable and now: 

![image](https://user-images.githubusercontent.com/22350/106276133-f032c500-61eb-11eb-952e-babed14ad62c.png)

**Comment by bpasero** [comment]
Regression from https://github.com/microsoft/vscode/commit/3da578616121cd294c29d52d142fdb3440d6539e#diff-f925458429e390c87a38d5f816ee899c460f8d90efe10c3531585bd52199c3d5

**Comment by isidorn** [comment]
Fixed via revert b36f999316
Sorry about that
