### ISSUE TITLE
solution explorer covers with blue-white stripes 

### ISSUE THREAD

**Issue by portiss** [microsoft/vscode#115303]
- VSCode Version: 1.52.0
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. open vscode
2. check solution explorer
3. solution explorer covers with blue-white stripes - cannot see any file view.
![image](https://user-images.githubusercontent.com/29782156/106144806-64824f80-617d-11eb-969a-e166f9cd4296.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/106429

Please follow https://github.com/microsoft/vscode/issues/106429#issuecomment-690777260 for workaround.
