### ISSUE TITLE
Screen pixels

### ISSUE THREAD

**Issue by BichoTraveco** [microsoft/vscode#115363]
Issue Type: <b>Performance Issue</b>

My screen have some pixels when i don't click with my mouse and I don't know no how stop it

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 14776	code main
    0	    86	  4232	   shared-process
    0	    37	  7704	   utility
    0	   179	  9440	   window (Settings - projeto_p1_minesweeeper-Update-Windows_version - Visual Studio Code)
    0	    66	  1300	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   121	  4948	     extensionHost
    0	    24	 15208	       c:\Users\bacan\.vscode\extensions\ms-vscode.cpptools-1.2.0-insiders3\bin\cpptools.exe
    0	    11	 14628	         console-window-host (Windows internal process)
    0	    81	 18644	       "C:\Users\bacan\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\bacan\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=4948
    0	    12	 13240	     watcherService 
    0	    11	 11380	       console-window-host (Windows internal process)
    0	     7	 18464	     console-window-host (Windows internal process)
    0	    23	  9480	   crashpad-handler
    0	    77	 11604	   window (Issue Reporter)
    0	   132	 16900	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - projeto_p1_minesweeeper-Update-Windows_version - Visual Studio Code)
|    Folder (projeto_p1_minesweeeper-Update-Windows_version): 25 files
|      File types: c(8) json(1) txt(1) h(1) sh(1) md(1) exe(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
cpptools|ms-|1.2.0-insiders3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

![2021-01-29 03_03_11-](https://user-images.githubusercontent.com/77287281/106228535-772f6f80-61e3-11eb-86d6-80e37c95f181.png)

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/93356

Please use https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration as a workaround.
