### ISSUE TITLE
Add a `when` clause to control custom editor priority

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115347]
Currently an extension has no programmatic control over the "priority" of a custom editor, e.g. if it is the default for a file type, or just available.

It would be great to allow extensions to control this behavior, e.g. an extension could have a simple "enable" setting that would control this (or contextual values depending on the state/how it was invoked, etc).

As a use-case, this would be helpful for the GitLens Rebase Editor, because users want better control over when it is opened. Like never if invoked from the terminal, but desired if invoked from a GitLens command, etc.

/cc @Tyriar

**Comment by lramos15** [comment]
I have the hardest time understanding the use cases of this. So if they want it to open through gitlens commands your extension can open the file even if it's optional. Optional always covers all the cases where I can think of wanting it to open in some cases but not others.
