### ISSUE TITLE
Animate getting started step closing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115314]
You can't see it in the gif due to the lowered frame rate, but when clicking on a new step you can see the steps at the bottom go up and then go down again. I think you can avoid this by animating the hide and the show with the same duration.

![recording (57)](https://user-images.githubusercontent.com/2193314/106177491-6c2a0000-614d-11eb-858b-f52bd78aeac2.gif)

**Comment by JacksonKearl** [comment]
It's a bit weird because we cant animate it to the actual height because that can vary based on the contents and editor width, instead we animate the max-height, so even though the animation lengths are the same on paper if the contents are smaller the animation will finish faster.

**Comment by Tyriar** [comment]
You should be able to do it in JS by resolving the height, this isn't a big deal just a small polish issue I noticed.

**Comment by misolori** [comment]
I saw the same thing and everything was jumping all over the place:


https://user-images.githubusercontent.com/35271042/107806392-a97cb900-6d1b-11eb-973a-02e5c07bcd41.mp4
