### ISSUE TITLE
an error occurred when trying to rename a file in the destination directory movefile failed 

### ISSUE THREAD

**Issue by Surepavan9** [microsoft/vscode#115394]
unable to install the vs code on my system, tried multiple times same error. please help 
![image](https://user-images.githubusercontent.com/64972343/106272885-c8794680-6257-11eb-8ca7-1c4ae2063d13.png)

**Comment by gjsjohnmurray** [comment]
Probably being removed by your antivirus product

**Comment by Surepavan9** [comment]
Nope, still the same error, I uninstalled antivirus software on my pc but no use

**Comment by gjsjohnmurray** [comment]
Anything special about your G: drive?

**Comment by Surepavan9** [comment]
No, I'm just trying on every drive on my lap, but the same error occurs when i tried in any drive

**Comment by joaomoreno** [comment]
Have you tried clicking `Skip this file`?

**Comment by Surepavan9** [comment]
Yes i tried, but another error will appear on the screen

**Comment by Surepavan9** [comment]
Thanks for the help.
