### ISSUE TITLE
Typescript definitions not found when comparing changes on working tree

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#11536]
- VSCode Version: 1.4.0
- OS Version: Win10 April 2016

![capture](https://cloud.githubusercontent.com/assets/3494407/18244063/65aeeb46-735e-11e6-98ed-ee47c28034b3.PNG)

When I open the changes of a .tsx file from GIT toolbox (Ctrl+Shift+G)  VSCode reports a lot of TypeScript errors. It seems like it cannot find file with typescript definitions.

However, when I open the same file from explorer (Ctrl+Shift+E) no errors are reported. 

What's even stranger, when I open changes of similar .tsx file in the same directory or any other .tsx file, no errors are reported, unlike the first file. I don't know what's so special about the first one.

**Comment by waderyan** [comment]
@Liero thank you for opening this issue. I have tried the following steps to reproduce your issue. Can you review the steps I took and try them on your machine? What did I do differently than what you have done? 

Thanks! 

1. Create a new typescript project with `test.tsx` file. 
2. Run `npm init`
3. Run `npm install react --save`
4. Run `typings install react`
5. Paste the following code into `test.tsx`. 

```typescript
import * as React from 'react';

console.log('hello world');
```

Based on what you described and your image above I expect to see red squiggles under `'react'`. I do not see the error. 

![image](https://cloud.githubusercontent.com/assets/2449568/18290906/33fabbf2-743a-11e6-9537-6356ff0862c3.png)

**Comment by waderyan** [comment]
Closing until more info is given.
