### ISSUE TITLE
CTRL+Z can delete unstaged files, add warning

### ISSUE THREAD

**Issue by dzvancuks** [microsoft/vscode#115313]
- VSCode Version: 1.52.1
- OS Version: Linux x64 5.8.0-40-generic snap (Ubuntu 20.04)

Steps to Reproduce:

1. Have several files opened in current project
2. Create directory and some files in it
2. Do more actions in explorer view like renaming directory
3. Keep focus on explorer, press CTRL+Z several times
4. Check that file is deleted
5. Edit something else, like another opened file

Ctrl+Y will not restore deleted files. Unless they are staged for commit all work is lost.
Please add some kind of warning in case file is about to be deleted via Ctrl+Z in explorer view

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
We added the warning in insdiers. Should be soon in stable. 
Closing as duplicate
