### ISSUE TITLE
Error message when opening Code with no internet connection

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11535]
![image](https://cloud.githubusercontent.com/assets/323878/18244140/c2dbd7e8-735e-11e6-9d04-cf5bb3cbdb9b.png)

I see this in 1.5-insider but not 1.4, every time I open a new window while not connected to the internet.

**Comment by dbaeumer** [comment]
@joaomoreno marking as important. Saw this this morning as well. All my windows this morning showed the message.

**Comment by roblourens** [comment]
And there's another message when you're connected but being MITM'd by hotel wifi :) (in case you try to fix it by detecting that there's no connection at all)

**Comment by joaomoreno** [comment]
@dbaeumer @roblourens Maybe we should actually do something here for the release. I'll put something in the `release/1.5` branch.
