### ISSUE TITLE
Integrated terminal should remember scroll position

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11542]
- VSCode Version: Code - Insiders 1.5.0-insider (538cd9ded5a471fbb20920f01eff9c8df4b83ee9, 2016-09-05T08:31:20.203Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:
1. Open integrated terminal or start debugger and open debug window
2. Have enough output so there is a scroll
3. Have terminal (or debug console) continue to output stuff (for terminal eg. `while true; do echo "hi"; sleep 1; done`)
4. Scroll up because you want to read or copy something
5. Problem: As soon as new data comes - both windows are scrolled down to the bottom - they should only auto scroll to bottom if user was at the bottom of the window - otherwise scroll position should not change

**Comment by isidorn** [comment]
Fix for the debug window was pushed yesterday via 2a215cc
Thus unassigning myself and renaming issue

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/216

**Comment by ArtemGovorov** [comment]
Could you please consider doing the same for output channels? They do have the exact same issue: https://github.com/Microsoft/vscode/issues/3351

**Comment by Tyriar** [comment]
@ArtemGovorov it looks like that issue was fixed 8 hours ago so it will work in output channels in v1.6 :+1:

**Comment by hgl** [comment]
@Tyriar Somehow it's not working for me.

I'm using
- vscode Version 1.16.0-insider (1.16.0-insider)
- zsh 5.3 (x86_64-apple-darwin17.0) default version comes with macOS
- macOS 10.13 Beta (17A360a) (beta7)

And if I type 
```
while true; do echo "hi"; sleep 1; done
```
in the integrated terminal and scroll up, it would still scroll, making it hard to view and select text.

Is there an option that I have to enable to get this behavior or something?

**Comment by Tyriar** [comment]
@hgl thanks for the repro steps, created https://github.com/Microsoft/vscode/issues/33955
