### ISSUE TITLE
Multi-root workspace: Settings that can chain

### ISSUE THREAD

**Issue by glenn2223** [microsoft/vscode#115482]
This feature is specific to multi-root workspaces.

### Current
The settings in the workspace control everything. Settings in the roots themselves are not applied even if the workspace doesn't have the setting.

### Suggestion/Feature
Settings that are set at a root level can be overridden by the workspace folder. However, when the workspace doesn't have the setting applied then it gets it from the root. (Chaining up and a duplicate overriding the root as it goes)

### Context
I have an extension for the marketplace in which I have just added a new setting, however the current setup is very restricting.

See the setting `liveSassCompile.settings.forceBaseDirectory` [here](https://github.com/glenn2223/vscode-live-sass-compiler/blob/8ded8917ed3695a38d39f32820355d45ffc40ebe/docs/settings.md)

If someone has a multi-root workspace where, in folder 1, they want to set this to `x/y/z/` and, in folder 2, they want it to be `a/b/c/` then this is impossible. If the settings chained up being overridden as they go then this would work perfectly. They can set the setting at each root level and nothing at the workspace level.

I think this would have to go down as a breaking change as any current setup will most likely break. For example, if someone moved from a single root to multi-root. Then removed a setting and forgot about the initial settings file then the sub-setting will apply

**Comment by gjsjohnmurray** [comment]
Unless I am misunderstanding you, it already works as you want it to. Just remember to pass a resource uri when you call `vscode.workspace.getConfiguration` so VS Code picks the settings from the correct root.

**Comment by glenn2223** [comment]
It doesn't.

The setting on the workspace setting file overrides the setting on the root folder, see below notice when I try.

![image](https://user-images.githubusercontent.com/33450392/106373799-251e5380-6375-11eb-8013-c88c7cf4b554.png)

Basically the setting set at this root won't work, we're using the workspace settings

**Comment by gjsjohnmurray** [comment]
Unless you pass a uri when you get settings how will VS Code know which of your workspace roots yo want the folder-specific settings from?

**Comment by gjsjohnmurray** [comment]
Are you setting `"scope": "resource"` on this configuration contribution?

**Comment by glenn2223** [comment]
> Are you setting `"scope": "resource"` on this configuration contribution?

You are amazing! Had to do some extra research to find out how to get the setting at resource level, but all is working as expected now.

What an amazing feature to have tucked away 😄
