### ISSUE TITLE
C/C++ debug extension missing?

### ISSUE THREAD

**Issue by Michal-Gagala** [microsoft/vscode#115472]
Issue Type: <b>Bug</b>

For some reason this extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools&ssr=false#overview can't be found by my vs code installation

VS Code version: Code - OSS 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-19T14:42:39.893Z)
OS version: Linux x64 5.10.11-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (12 x 2981)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.64GB (3.93GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
haskell|has|1.2.0
language-haskell|jus|3.3.0
python|ms-|2020.10.332292344
java|red|0.74.0

</details>

**Comment by gjsjohnmurray** [comment]
My guess is that you are using a VS Code distribution from your Linux version, and it may have been built to connect with the Open VSX Registry instead of the Microsoft Marketplace.

Workaround may be to download the VSIX file from Marketplace and install it manually in the Extension view. Drag/drop might work.
