### ISSUE TITLE
The global variable looks gray, as if it is not being used(but it is)

### ISSUE THREAD

**Issue by Den0702** [microsoft/vscode#115474]
Issue Type: <b>Bug</b>

The global variable `currentSlide` looks gray, as if it is not being used. If I move it to the global scope, the variable declaration stops being gray.  And if I move it back again, everything is still ok. 
![ice_screenshot_20210130-194925](https://user-images.githubusercontent.com/30319035/106365723-b373e480-6337-11eb-9c41-77d97fb23400.png)
When I delete this variable from local scope - the global variable looks like it's still been used. 
![ice_screenshot_20210130-201449](https://user-images.githubusercontent.com/30319035/106366040-993b0600-6339-11eb-98ee-2f470d4c026e.png)
I have autosave option being swiched on

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz (4 x 2128)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.86GB (1.34GB free)|
|Process Argv|D:\\Курс JavaScriptDOMИнтерфейсы для новичков\\jsbasic-20201022_ellan --crash-reporter-id 3271867f-5249-444b-84ff-f4d63580ccb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.10
debugger-for-chrome|msj|4.12.12
elmmet|nec|1.0.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.16

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by mjbvz** [comment]
The value is faded out because it is never read. In the first example you only declare and increment it. In the second, `totalShift` is also never used for anything after its declaration

**Comment by Den0702** [comment]
@mjbvz Thank you very much for the reply.
