### ISSUE TITLE
VS Code Folder Struckture created after reboot

### ISSUE THREAD

**Issue by RedCrafterLP** [microsoft/vscode#115467]
I copied VSCode to my Desktop to test it. Later I moved it to my personal program folder. 
The problem is every time I restart my system (not starting VSCode) this folder struckture is created: 
"...\Desktop\VSCode\data\user-data\User\workspaceStorage\f5f3f5a2473a09f5237a83ec3d4648e3\ms-vscode.js-debug\.profile\" 
without any files in it. 
When I remove the Folder, it reapears seconds after I restart the system and logged in. 
I'm not shure if VSCode is responsible for the structure but I couldn't find any way to prevent it. 
Thanks for help in advice.

EDIT: I just tried locking the system and unlocking it, yields the same result

**Comment by connor4312** [comment]
@joaomoreno this isn't a folder that js-debug creates, is this something built-in to vscode?

**Comment by joaomoreno** [comment]
Got it. @jrieken Could it be extension profiling?

**Comment by jrieken** [comment]
Nope - auto profile goes into temp

**Comment by jrieken** [comment]
This does look like "workspaceStorage" (as suggested by the name)

**Comment by connor4312** [comment]
Oh, nevermind. I know what this is -- it's the user data dir that gets created when a Chrome session starts.

From the user it sounds like the workspaceStorage path is just incorrect / still 'cached' on the desktop. Not sure whether we support moving vscode installs around like this.

**Comment by RedCrafterLP** [comment]
It sounds like you got something.? It does not create any files in it just the folders. I wouldn't be so clueless when it would create some config, but it doesn't.

**Comment by RedCrafterLP** [comment]
It stopped happening, was it fixed with an update? Then I would close the thread.
