### ISSUE TITLE
shellscript: cmd+/ doesn't comment out

### ISSUE THREAD

**Issue by shinokada** [microsoft/vscode#115483]
On macOS, when I use `CMD`+`/`, I can comment out a line (or lines) in Python.
But when I use it with shellscript, it doesn't.

Is this a bug?

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

**Comment by gjsjohnmurray** [comment]
What language mode is VS Code handling your shellscript file with? Look at the indicator on the right end of the status bar.

If this suggestion doesn't help, please post more details. 

/needsMoreInfo

**Comment by shinokada** [comment]
I can't find bash or shellscript under the Select language mode, so I have to install the shell-format.

After selecting the shellscript, it still doesn't comment out.

![image](https://user-images.githubusercontent.com/147320/106377047-8d088480-63dd-11eb-9755-e4b2ece38157.png)

**Comment by kieferrm** [comment]
Simple shell script support ships out of the box.

![image](https://user-images.githubusercontent.com/4674940/106404755-95b28800-63e8-11eb-9a98-a71bf2246bb7.png)

Please make sure the built-in extension is enabled.

![image](https://user-images.githubusercontent.com/4674940/106404708-71ef4200-63e8-11eb-9186-4cc62b388978.png)

**Comment by shinokada** [comment]
@kieferrm Thanks for your reply, but shouldn't the VScode support the shellscript natively?

**Comment by shinokada** [comment]
Yes, it worked thanks kieferrm.
