### ISSUE TITLE
Support transferables in webview postMessage

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115411]
Issue asking _what_ is supported: https://github.com/microsoft/vscode/issues/79257

`postMessage` does not support transferables (eg. typed arrays) so `new Unt8Array([0, 1])` for example ends up being encoded as an object like `{0: 0, 1: 1}`. Some approaches I've tried to workaround this problem:

- Convert the typed array to an array `Array.from(typedArray)`, this is slow, duplicates memory and causes unnecessary GC
- "Encode" the typed array as an ascii string and "decode" it back on the other side, this is slower but ends up being a smaller payload that `Array.from`, benefits also don't seem to kick in until the payload is quite large

The real fix here is just supporting transferring typed arrays.

I'm not sure if it's possible but it would be amazing if we could use `SharedArrayBuffer`s between the ext host and webview, then there is no transfer time. For example the ext host could initialize the SAB and transfer it over for use, if the webview needed a bigger buffer it could request it via `postMessage`.

**Comment by mbehr1** [comment]
would be really nice! Need this feature for my extensions.

**Comment by mjbvz** [comment]
Closing in favor of #115807

Supporting SharedArrayBuffers (or anything that cannot be serialized) is not possible due to our extension architecture. This is not likely to change in the short term

**Comment by mbehr1** [comment]
@mjbvz can you elaborate a bit / provide more details? Is it cause the messages have to be posted twice? (If I read the getVsCodeApiScript.postMessage or e.g. host.onMessage('message',...) correctly.) This would still be possible to implement though, or?

**Comment by mjbvz** [comment]
See the details on #115807
