### ISSUE TITLE
Testing + breakpoint looks like a slow test

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115400]
Intuitively to me the top one looks like a slow test, not a test with a breakpoint

![image](https://user-images.githubusercontent.com/2193314/106280870-4d7e4480-61f3-11eb-9580-aab8a16d2208.png)

**Comment by connor4312** [comment]
Thanks for the issue, we'll tackle this in https://github.com/microsoft/vscode/issues/114776

/duplicate
