### ISSUE TITLE
vs code overides my custom settings to default when using a custom keybinding

### ISSUE THREAD

**Issue by danBamikiya** [microsoft/vscode#115456]
Issue Type: <b>Bug</b>

After updating to the latest VS Code it overides my custom settings and deletes them from the settings.json (including the settings of my extensions) when i use a custom keybinding that toggles the status bar!!

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.17GB free)|
|Process Argv|--crash-reporter-id b34f5534-62c3-4d55-8ebc-25066440b9f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vueGenerator|adr|0.2.2
project-manager|ale|12.0.1
vs-code-css-comments|ash|1.0.5
vscode-custom-css|be5|4.0.1
stories|ben|2.22.0
css-compressor|bes|0.0.2
vscode-tailwindcss|bra|0.5.7
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.18.1
flutter|Dar|3.18.1
vscode-eslint|dba|2.1.14
javascript-vue|Dig|0.3.2
githistory|don|0.6.14
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|3.1.0
css-flexbox-cheatsheet|dzh|3.2.0
gitlens|eam|11.1.3
vscode-html-css|ecm|1.9.1
clipboard-manager|Edg|1.4.2
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
vscode-terminals|fab|1.12.9
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.1
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vscode-pull-request-github|Git|0.22.0
vscode-test-explorer|hbe|2.19.5
live-html-previewer|hdg|0.3.0
live-debug-vscode|hed|0.6.0
Angular2|joh|11.0.0
minifyall|jos|2.4.13
vscode-gutter-preview|kis|0.26.2
graphql-for-vscode|kum|1.15.3
vscode-python-test-adapter|lit|0.6.6
MagicPython|mag|1.1.0
g-translate|map|0.0.2
git-graph|mhu|1.28.0
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vsliveshare|ms-|1.0.3577
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
color-highlight|nau|2.3.0
deepdark-material|Nim|3.2.1
vscode-for-node-js-development-pack|nod|2.0.1
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
css-tree|sac|1.1.0
code-settings-sync|Sha|3.4.3
sass-indented|syl|1.8.15
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
python|tht|0.2.3
lorem-ipsum|Tyr|1.2.0
vscode-counter|uct|2.2.1
vscode-icons|vsc|11.1.0
vscode-import-cost|wix|2.14.0
vue|Wsc|1.0.26
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
emmet-live|yse|1.0.0

(11 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you launch with all extensions disabled? If not, use the extension bisect command to find out which extension is causing the problem.

If it does still happen please post simplest reproduction steps.

**Comment by danBamikiya** [comment]
Hello @gjsjohnmurray I ran the extension bisect command and everything was all good. I haven't installed extensions in a long while so I don't think it's the extensions. It's just after the new update that it started happening.

**Comment by sandy081** [comment]
Can you please be specific about the issue and provide steps to repro?

**Comment by danBamikiya** [comment]
Hello, so I created a custom keybinding that toggle the status bar (Ctrl+Q   Ctrl+Q). After the recent update when I try to use the keybinding(usually after i resume my computer from sleep and open vscode) I notice vscode hangs then 'refreshes' itself with all my settings gone and even the theme goes back to the default theme and all installed extensions don't work( I have to re-enable them).

**Comment by sandy081** [comment]
Does this happens only after you use this keybinding ?

**Comment by danBamikiya** [comment]
Yes

**Comment by sandy081** [comment]
Can you please try change the keybinding to a different keybinding (say ctrl+shift+m or any other simple one) and try toggling the status bar using the new keybinding and see if you can still repro?

**Comment by danBamikiya** [comment]
It doesn't happen after using an alternative keybinding!

**Comment by sandy081** [comment]
Seems something special with this keybinding (Ctrl+Q Ctrl+Q). You mentioned that after applying this keybinding, your settings and extensions are gone - Can you please elaborate on that ? Please open settings file and let us know if your settings are there and also check extensions in extensions view?

Also before applying above keybinding enable the log level to trace (using command Developer: Set Log Level) and please collect all logs (You can see them in the output section dropdown in the bottom panel) and provide us.
