### ISSUE TITLE
Python interactive console/terminal, keyboard combo shift+alt+right arrow should highlight the word, but produces characters ;4C

### ISSUE THREAD

**Issue by colstats** [microsoft/vscode#115439]
I am using Python interactive console. The keyboard shortcut shift+alt+right arrow should highlight to the end of the word, but prints ;4C. Likewise, shift+alt+left arrow prints ;4D.

This is an otherwise great editor, but not being able to highlight is frustrating. I've been holding the backspace key to erase words. It gets a bit too much after while.

![Screen Shot](https://user-images.githubusercontent.com/14314760/106337354-f615be00-625e-11eb-917c-b174f3e16c43.png)

Any fix would be greatly appreciated, thanks!

**Comment by meganrogge** [comment]
We can't control this. It needs to be a feature within python

We are sending the keystrokes, but it's not handling them

**Comment by colstats** [comment]
Hi, @meganrogge. 
Similar software like Matlab and R both have interactive console. It's a full REPL.

Currently, the Python console uses the terminal to run. Keyboard shortcuts don't work in terminal.

Here's a screenshot from Matlab. As you see, key combo alt+shift+right arrow lights word to the right of cursor. Extremely convenient!
![Screen Shot 2](https://user-images.githubusercontent.com/14314760/106503486-b1bf3380-6493-11eb-8811-9dde8f0cdbcb.png)

My request is for an interactive console. Possibly like Python REPL?

Thanks!
