### ISSUE TITLE
Don't propagate scroll events from Intellisense to editor

### ISSUE THREAD

**Issue by movsb** [microsoft/vscode#115471]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 20.2.0

Steps to Reproduce:

Just see the recording below, scrolling in the Intellisense window will hide the Intellisense window and propagates to the editor below.  Earlier versions have no such issue. Or Is it a feature? How to disable it?

https://user-images.githubusercontent.com/5374525/106363912-678c6400-6366-11eb-8647-6ddee330d0fd.mov

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate and is fixed in 1.53, due to release this week.
