### ISSUE TITLE
Some files are not sorted in alphabetical order, in Explorer

### ISSUE THREAD

**Issue by Sea-bottom** [microsoft/vscode#115492]
Udgave	Windows 10 Pro
Version	20H2
Installeret d.	‎28-‎10-‎2020
Operativsystemets build	19042.572
Visning	Windows Feature Experience Pack 120.2212.31.0

-  DX DIAG: [DxDiag.txt](https://github.com/microsoft/vscode/files/5899398/DxDiag.txt)

ISSUE in the screenshot:
![Not Sort](https://user-images.githubusercontent.com/11725933/106378935-4c286400-640d-11eb-919f-8a20ceb5c865.png)

![not alph](https://user-images.githubusercontent.com/11725933/106378978-8f82d280-640d-11eb-9251-079735ea07c0.png)

Steps to Reproduce:
1. Create .wav file with those names
2. Sort by name, and it does not sort properly
3. I think any file name with double-a is not sorted properly ???

**Comment by gjsjohnmurray** [comment]
Your screenshot is of Windows Explorer. How does this issue relate to VS Code?

/needsMoreInfo 

Tip: screenshots can be pasted directly into GitHub

**Comment by Sea-bottom** [comment]
> Your screenshot is of Windows Explorer. How does this issue relate to VS Code?
> 
> /needsMoreInfo
> 
> Tip: screenshots can be pasted directly into GitHub
This is the same kind of issue in this subforum, so I figured I would post it here?
https://github.com/microsoft/vscode/issues/99955

**Comment by gjsjohnmurray** [comment]
This GitHub repository only deals with Visual Studio Code. The Explorer app in Microsoft Windows is unrelated to VS Code, which has a view called Explorer. If you are using VS Code and can reproduce your problem in the VS Code Explorer please post screenshots from there. If not, please close the issue.
