### ISSUE TITLE
Redo

### ISSUE THREAD

**Issue by willywil548** [microsoft/vscode#115485]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

While editing Java, ctrl + y deletes the current line.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.80GB free)|
|Process Argv|--crash-reporter-id 34f668ed-3953-4911-8a63-426d2d658f5e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
intellij-idea-keybindings|k--|1.3.0
csharp|ms-|1.23.8
remote-wsl|ms-|0.52.0
java|red|0.74.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.30.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.27.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry914:30250197
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like you have a custom keybinding.

See https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice.

**Comment by willywil548** [comment]
![image](https://user-images.githubusercontent.com/4316475/106374545-0732fd80-6339-11eb-8698-e8a73389fb6d.png)

**Comment by willywil548** [comment]
> Sounds like you have a custom keybinding.
> 
> See https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice.

Thanks for the tip... I wasn't tracking the extensions :)
