### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by vikesh44** [microsoft/vscode#115493]
Issue Type: <b>Bug</b>

In VS code I am unable to use internet but internet works on my Visual Studio and browsers.

Extensions **POPULAR** tab shows error as 
> We cannot connect to the Extensions Marketplace at this time, please try again later.

When I click on Help -> **Check for Updates...** getting elow error
>net::ERR_PROXY_CONNECTION_FAILED
>
>Source: Update Service

When I click on Check for Extension Updates below error is shown
>XHR failed

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (23.02GB free)|
|Process Argv|--crash-reporter-id 086150dc-7a3b-4b9b-b392-9edc648f5ed1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.22.0

</details>

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=netlog.json`, retry the failing feature and then post the created netlog.json here?

**Comment by vikesh44** [comment]
Please find below required file.

[netlog.zip](https://github.com/microsoft/vscode/files/5931927/netlog.zip)

**Comment by chrmarti** [comment]
You seem to have a proxy config script at `http://127.0.0.1:9000/systemproxy-1612521890.pac` that returns `coiagb1:9400` as the proxy and that hostname `coiagb1` does not resolve to an IP address using your DNS config.

What do you get for `nslookup coiagb1` on the command line? What is in `http://127.0.0.1:9000/systemproxy-1612521890.pac`?

**Comment by vikesh44** [comment]
`http://127.0.0.1:9000/systemproxy-1612521890.pac` is proxy set by my organization. With this proxy enabled, I am able to user internet and other application except VS Code.
P.S. other people with same proxy set able to use VS Code without any issue.

Below is the result of `nslookup coiagb1`
![image](https://user-images.githubusercontent.com/47881034/107554277-bc986780-6bfb-11eb-93dd-256b051ab28e.png)

**Comment by chrmarti** [comment]
nslookup did not return an IP address for the proxy, so your machine has no way of reaching the proxy. This seems to be an issue with your local DNS forwarder (that could be part of your VPN client or some other network software).

Is there an entry for `coiagb1` in `C:\Windows\System32\drivers\etc\hosts` by any chance?

**Comment by vikesh44** [comment]
No entry of `coiagb1` in `hosts` file.

**Comment by chrmarti** [comment]
Can someone with the same setup where this is working check what the output of `nslookup coiagb1` is?
