### ISSUE TITLE
settings sync

### ISSUE THREAD

**Issue by m1keVi** [microsoft/vscode#115491]
Issue Type: <b>Bug</b>

i was preview skins using keyboard arrows, although i did not press enter to accept the skin, program start synchronising settings to the cloud. That should only happen after i press enter to accept the skin

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.67GB free)|
|Process Argv|--crash-reporter-id 9e496d8c-3358-4ccf-aa88-17d1e36227af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.4
vscode-django|bat|1.3.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-markdownlint|Dav|0.38.0
py-pack|dav|1.2.0
python-preview|don|0.0.4
githistory|don|0.6.14
python-extension-pack|don|1.6.0
gitlens|eam|11.1.3
vscode-great-icons|emm|2.1.64
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
code-runner|for|0.11.2
gc-excelviewer|Gra|3.0.40
vscode-test-explorer|hbe|2.19.5
format-python-docstrings|ian|1.2.1
icon-fonts|idl|2.4.0
python-coding-conventions|igr|0.0.4
conda-cheatsheet|joj|1.2.7
vscode-python-test-adapter|lit|0.6.6
MagicPython|mag|1.1.0
python-path|mge|0.0.11
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.3
jupyter|ms-|2020.12.414227025
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.5.0
trailing-spaces|sha|0.3.1
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.2.4
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.13

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspyt653:30244269
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
vstry244cf:30250196
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
See #110817 and the open denounce issue it references.
