### ISSUE TITLE
trusted domains in actual file

### ISSUE THREAD

**Issue by 54696d21** [microsoft/vscode#115453]
I want to be able to store the trusted domains file like the settings.json file in a git to use it on multiple computers

**Comment by gjsjohnmurray** [comment]
Seems unlikely to happen. See #81841

Did you consider enabling the native Settings Sync? This should sync your trusted domains list across machines.

**Comment by 54696d21** [comment]
I really want to sync it the way I do with all my dotfiles, but I appreciate the hint

**Comment by JacksonKearl** [comment]
@gjsjohnmurray is correct, we prefer to keep it out of the normal filesystem for the reasons in the linked issue.
