### ISSUE TITLE
Disable "undo command for file operations"

### ISSUE THREAD

**Issue by mivd7** [microsoft/vscode#115457]
Something that really bugs me in recent version of VSCode is this feature to undo file operations in the file explorer. Apparently this is a new feature since v1.52 (November 2020) https://code.visualstudio.com/updates/v1_52 . 

This sometimes causes files that I previously created to disappear because I accidentally press cmd+z in the file explorer instead of the file editor. I do not want this, because it messes heavily with my workflow and it's just generally very annoying that files get deleted which I don't want deleted. I know I can redo the action with cmd + shift + z, but I just don't want the undo feature at all. It doesn't seem like I can disable it in the settings, and I would like to be able to do so.

**Comment by gjsjohnmurray** [comment]
I think the next release will ask you for confirmation before undoing a file operation. You can try it in Insiders now, or wait for 1.53 to land in Stable, due this coming week.

**Comment by isidorn** [comment]
I believe there has been requests to disable this feature in another issue. Thus closign as duplicate
And I would like to get feedback since we introduced a confirmation dialog for the next release

**Comment by ghs** [comment]
Same here. Will be great to disable it or have it as a preference option if people want to use it.
