### ISSUE TITLE
Intellisense always shows only 1 result

### ISSUE THREAD

**Issue by bzuillsmith** [microsoft/vscode#115430]
Issue Type: <b>Bug</b>

I recently noticed VS Code intellisense only giving me 1 result when using typescript. I hit the `.` to see all functions and it shows me the first function it finds only. Then start typing and the matching result changes but is always 1 item. I then switched to a c# app, same thing. I then disabled all extensions for the workspace, restarted and added only the C# extension and it still did the same thing.

I tried searching for this issue and found on SO someone had the same issue: https://stackoverflow.com/questions/65897902/vscode-only-shows-single-item-in-autocomplete

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.04GB free)|
|Process Argv|--crash-reporter-id be34ad6d-3c3e-43f6-8adf-f3f910336055|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30250195
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like your autocomplete dropdown got resized to a single row. You should be able to drag it from the bottom right corner to fix this.

**Comment by mjbvz** [comment]
See https://stackoverflow.com/questions/64789393/visual-studio-code-intellisense-showing-one-suggestion-at-any-time/64817846
