### ISSUE TITLE
vscode JavaScript hover show tooltip NOT working even Editor>Hover:Enabled

### ISSUE THREAD

**Issue by lq3297401** [microsoft/vscode#115431]
- VSCode Version: 1.52.1
- OS Version: Darwin x64 19.5.0

I have disabled all the extensions, and keep editor>Hover:Enabled, but when I hover on the JavaScript symbol, it didn't show any type information or relevant documentation. I also have tried the The ⌘K ⌘I keyboard shortcut, it still not working.

Here is my screenshots:
<img width="964" alt="hover do not work" src="https://user-images.githubusercontent.com/19629037/106319510-83cbca80-62ac-11eb-96d0-9614b23ea45a.png">

What I expect to see is (from https://code.visualstudio.com/Docs/languages/javascript)
Hover Information#
Hover over a JavaScript symbol to quickly see its type information and relevant documentation.

<img src="https://code.visualstudio.com/assets/docs/languages/javascript/hover.png">

The ⌘K ⌘I keyboard shortcut shows this hover info at the current cursor position.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by lq3297401** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

No, the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) doesn't have this issue, it shows the tooltip perfectly. Only my Visual Studio Code Version: 1.52.1 with OS Version: Darwin x64 19.5.0 (the blue icon one) has this issue.

**Comment by mjbvz** [comment]
If it works in insiders, then you've likely either:

- Disabled the built-in JS/TS extension. In the extensions view, search `@builtin javascript` to check this
- Have a user setting that is causing this
- Or you have an extension that is causing this


Try tracking down the root cause
