### ISSUE TITLE
import pygame

### ISSUE THREAD

**Issue by Derek-Pruitt** [microsoft/vscode#115426]
We have written the needed data into your clipboard because it was to
Issue Type: <b>Bug</b>

I am making a space shooter game with python. I have already installed pygame through the cmd. but when i debug it says module not found. i put import pygame at the top not sure what i am doing wroung

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.76GB (2.73GB free)|
|Process Argv|--crash-reporter-id a2a0562a-0f55-4003-a115-c1021ebe2f81|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.0.1
armview|ben|0.4.5
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.14
git-extension-pack|don|0.1.3
githistory|don|0.6.14
gitlens|eam|11.1.3
vscode-html-css|ecm|1.9.1
prettier-vscode|esb|5.8.0
pip-packages|etm|0.4.3
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.10
code-runner|for|0.11.2
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
HTMLHint|mka|0.10.0
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.2.0
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.2.0
vscode-cosmosdb|ms-|0.15.1
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.8
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.5
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.1.0
vsliveshare|ms-|1.0.3577
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.14.0
debugger-for-chrome|msj|4.12.12
vscode-zipexplorer|sle|0.3.1
pygame-snippets|tus|0.0.1
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

![2021-01-29](https://user-images.githubusercontent.com/64759619/106313863-1e34fb00-6226-11eb-8c88-df5b62f6920e.png)
o large to send. Please paste.

**Comment by kieferrm** [comment]
\extPython
