### ISSUE TITLE
Starting VS Code from Run Box opens CMD

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#115496]
- VSCode Version: 1.52.1
- OS Version: Wi0ndows 10 1909 (18363.1316)

Steps to Reproduce:

1. Close all instances of VS Code
2. `WinKey`+`R`
2. Type `code`, hit enter

Expected outcome: VS Code opens

Actual outcome: CMD opens then VS Code opens. CMD stays open until either VS Code is closed or the CMD window is manually closed.

**Comment by joaomoreno** [comment]
#66750
