### ISSUE TITLE
Native Notebooks - Add code cell not working after markdown

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#115432]
## Steps to Reproduce: 
1. Have a markdown cell followed by code cell
2. Try to add code cell using +code button between markdown and code cell

## Actual Behavior
Markdown cell added, not code cell

![Markdown Sandwich error](https://user-images.githubusercontent.com/19276747/106323010-9225d200-622b-11eb-9c5b-82dfc85d71e1.gif)

**Comment by rebornix** [comment]
This would better be addressed by supported languages info from active kernel and also some context in the document.

**Comment by lramos15** [comment]
@rebornix I also saw this issue and opened it against jupyter as I only saw it in their notebooks. I'm not sure where this bug should live.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/2a1f20afc7c2a52a74806c88c21fc4e333c36363.
