### ISSUE TITLE
Terminal won't interpret

### ISSUE THREAD

**Issue by JBCHK** [microsoft/vscode#115484]
Issue Type: <b>Performance Issue</b>

This issue has been happening since last night...the terminal fails to interpret, then the computer crashes and restarts.  I scanned the computer last night for malware/cleaned my computer with CleanMyMacX, but the issue persists. The following screenshots are of: last night's crash, and this evening's terminal failure.

![Screen Shot 2021-01-30 at 8 41 48 PM](https://user-images.githubusercontent.com/45148241/106374179-b4fcd700-634e-11eb-814c-aa34e3bfeb06.png)

![Screen Shot 2021-01-30 at 8 51 29 PM](https://user-images.githubusercontent.com/45148241/106374185-bc23e500-634e-11eb-8b96-51fa267cecab.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv|-psn_0_45067 --crash-reporter-id 8375249f-3bef-4151-bf83-a042a4036f3f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    61	   383	code main
    0	    29	   629	   gpu-process
    0	    12	   632	   utility
    0	    41	   699	   shared-process
    0	     0	  2639	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    86	  2573	   window (Welcome)
    1	    57	  2623	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30250195
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by JBCHK** [comment]
meant to send this photo of the crash.
![Screen Shot 2021-01-30 at 8 51 29 PM](https://user-images.githubusercontent.com/45148241/106373293-03f23e80-6346-11eb-97d6-036caca30eb0.png)

**Comment by gjsjohnmurray** [comment]
Please edit your original post to remove the first screenshot, which you posted by mistake.

Then see the wiki advice (link below) about posting information for crashes. 

/needsMoreInfo
