### ISSUE TITLE
Go To Declaration/Go To Definition context menu entries weirdly broken, often show Go To References results instead

### ISSUE THREAD

**Issue by ell1e** [microsoft/vscode#115473]
The `Go To Declaration`/`Go To Definition` context menu entries weirdly broken for me, and often show Go To References results instead. It is quite random and seems to be really just depend on whether VS Code thinks the line number is weird or not, or what do I know. Since the entirely wrong UI (the references section with entries) pops up in the first place I assume this is a VS Code and not an LSP bug, since I would expect VS Code to do nothing if worst case the LSP really sent the completely wrong response to the given request and not comply with indeed fully unrelated actions. For what it's worth, the LSP I'm seeing this with is the clangd diagnostics plugin.

- VSCode Version: 1.51.1 (VS Codium)
- OS Version: Linux x64 Fedora 33

Steps to Reproduce:

1. Use Go To Declaration or Go To Definition
2. Every 1 out of 50 occurrences or so, the references pop up instead. You can close them and retry however often you want, VS Code is now stuck and insists to show you completely useless references instead of carry out your requested action. Restarting VS Code will usually fix it.
3. I have also noticed Go To Declaration/Go To Definition will sometimes just do *nothing at all* if the target file isn't among the open tabs right after restarting VS Code (if the target file was opened previously then it seems to work even when the tab is closed again). Since the clangd LSP plugin supposedly supports background indexing, is there a bug in VS Code's LSP handling in that it doesn't maybe send the unopened files as part of the workspace? Whether this also causes the weird references mixup I made this ticket for I'm not sure, just mentioning it in case this is possibly related to all this misbehavior.

Does this issue occur when all extensions are disabled?: no idea, didn't know how to try when that removes the LSP backend to make these menu entries do anything at all

**Comment by jrieken** [comment]
The can only be caused by your extension. To populate the context menu VS Code doesn't do anything fancy, the only check is if for the given the current document an extension has registered a provider for "go to xyz" results
