### ISSUE TITLE
File name stuck unchanged after rename

### ISSUE THREAD

**Issue by axone13** [microsoft/vscode#115447]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Build 19042.746

Steps to Reproduce:

1. Open a folder
2. Create a file called "**example.txt**"
3. Write something inside it and save the file
4. Rename the file to "**Example.txt**" from the left side explorer
5. Make some changed in the file and hit Ctrl + S to save the file
6. You can see the file name at the tabs revert to the last name "**example.txt**" - (Expected to remain unchanged)

Does this issue occur when all extensions are disabled?: ***Yes***

I use the sftp extension and when "upload on save" is on, **this issue cause my files to upload on the server with the previous name**

Also, it doesn't help if I remove the file completely and make it again. It always stuck with the name that was entered at the beginning.

![1](https://user-images.githubusercontent.com/47145617/106342944-3190a680-62b8-11eb-8ae4-538790c330fc.png)
![2](https://user-images.githubusercontent.com/47145617/106342949-39504b00-62b8-11eb-8aae-b4c1f1a38d4c.png)

**Comment by isidorn** [comment]
This should be fixed in insiders, howeveer forwarding to @bpasero so he can close

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by axone13** [comment]
@bpasero I tested the insider build and it seems the issue is fixed. I'll let you know if something went wrong. Thank you
