### ISSUE TITLE
Markdown Preview keyboard shortcut doesn't work for editor in Preview Mode

### ISSUE THREAD

**Issue by vwkd** [microsoft/vscode#115458]
The keyboard shortcut to open Markdown Preview doesn't work for an editor that is in Preview Mode. This is unfortunate, because opening it manually works, either through the Command Pallete or by right clicking on the editor title area.

- VSCode Version: 1.52.1
- OS Version: macOS 11.1

Steps to Reproduce:

1. Open VSCode with Preview Mode enabled (default)
2. Single click on a `.md` file in Explorer such that the editor opens in Preview Mode
3. Use the keyboard shortcut to open Markdown Preview (default is SHIFT + CMD + V on macOS)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by-design since the file is already in preview mode. it matches when happens if you use the shortcut inside a markdown preview opened from the command
