### ISSUE TITLE
Gulp Auto Detection reporing errors in non gulp project

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#115428]
Issue Type: <b>Bug</b>

I have a project that is not Javascript, and does not use Gulp. It does have a tasks.json file to set up some build scripts. However every time I use the "Command-Shift-B" command, I get an error from the Gulp Auto Detection built in extension:
```
Auto detecting gulp for folder untitled folder failed with error: Error: Command failed: gulp --tasks-simple --no-color
```

I was complaining that Gulp was not installed, which it was not as I do not use Gulp. So I did install gulp and am now getting this error. 

Running the command in the error directly in the terminal seems to complete without error.

![image](https://user-images.githubusercontent.com/13488/106315520-55f96e00-6239-11eb-87d0-16d8e8ba44a1.png)

VS Code version: Code - Exploration 1.53.0-exploration (0c9e2dadd986d0bc085f1c5352245531eef65e84, 2021-01-07T06:27:03.244Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.1.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
output-colorizer|IBM|0.1.2
mads|mir|0.0.5
csharp|ms-|1.23.8
cpptools|ms-|1.1.3
hexeditor|ms-|1.3.0
js-debug-companion|ms-|1.0.8
js-debug-nightly|ms-|2021.1.2617
vscode-typescript-next|ms-|4.2.20210128
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
mvbasic|mve|2.1.2
ossaction|pga|1.0.0
material-icon-theme|PKi|4.5.0
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.11
flatuscode|Vin|1.1.1
vscodeintellicode|Vis|1.2.10

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2prompt:30219162
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenucf:30219169
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by jtsom** [comment]
This is NOT a duplicate of existing issues, and referencing https://www.github.com/microsoft/vscode/issues/113982 I certainly would NOT want VS Code to automatically install Gulp for me.

**Comment by alexr00** [comment]
This should already be fixed by bebd06640734c37f6d5f1a82b13297ce1d297dd1

**Comment by jtsom** [comment]
No, it is not, at least with this version:


![image](https://user-images.githubusercontent.com/13488/106598658-090de400-6526-11eb-903e-d3380d4b18e9.png)

![image](https://user-images.githubusercontent.com/13488/106598799-3e1a3680-6526-11eb-89d1-e159d863b64c.png)


```
Version: 1.53.0-exploration
Commit: 0c9e2dadd986d0bc085f1c5352245531eef65e84
Date: 2021-01-07T06:27:03.244Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin x64 19.6.0
```
![image](https://user-images.githubusercontent.com/13488/106598710-1cb94a80-6526-11eb-91a9-d3dd8524762d.png)

**Comment by alexr00** [comment]
That build is quite old. Please try updating to a newer one!

**Comment by jtsom** [comment]
There are no updates, at least using the build in "Check for Updates" 
![image](https://user-images.githubusercontent.com/13488/106612852-8c840100-6537-11eb-8307-f886c52a90b9.png)

**Comment by alexr00** [comment]
@bpasero it seems like there haven't been any exploration builds in a while. Is that intentional?

@jtsom I would recommend switching to VS Code Insiders if you aren't specifically testing changes that are only available in the exploration build!

**Comment by bpasero** [comment]
@alexr00 yes they are suspended until we pick up with Electron 12.
