### ISSUE TITLE
Deleting file via tab removes incorrect file and discards any unsaved changes (severe 🚨)

### ISSUE THREAD

**Issue by adamreisnz** [microsoft/vscode#115486]
Issue Type: <b>Bug</b>

See screen recording: https://www.loom.com/share/6858657ab50f416997a0b2777698d759

1. Open 2 files
2. Edit one of the files (optional) and keep focus on this file's editor window
3. Right click on tab of the other file (which doesn't have focus) and choose **Delete**
4. Observe how the first file with the focus is deleted instead
5. Observe how the tab is also closed and not preserved with a _(deleted)_ suffix
6. Observe how if you had unsaved changes in this file these are now lost

This is consistently reproducible and on account of not saving the contents in the file that is incorrectly removed, a very severe bug in my opinion.

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 006a2d24-d7bd-4f93-aadc-2c2054511bf1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
vscode-eslint|dba|2.1.13
gitlens|eam|11.0.6
EditorConfig|Edi|0.16.4
file-icons|fil|1.0.28
gc-excelviewer|Gra|3.0.40
name-that-color|gui|0.1.3
json2csv|kha|0.0.1
l13-diff|L13|0.30.1
prettify-json|moh|0.0.3
vetur|oct|0.31.3
multi-command|ryu|1.5.0
vscode-fileutils|sle|3.4.3
control-snippets|svi|1.9.1
reopenclosedtab|uyi|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

The Delete option you describe is not on my tab context menu.

**Comment by adamreisnz** [comment]
Apologies, I got so used to that feature that I thought surely it's core VS Code.
Have reposted as https://github.com/sleistner/vscode-fileutils/issues/330
