### ISSUE TITLE
'debugger' on first line - stop event received before initilized 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#11541]
Have the following code snippet:

``` js
debugger;
var array = []
for (var i = 0; i < 100; i++) {
    aLargeArray.push(i);
} 
```

Start debugging that code in vscode - notice an exception in the developer console. The root cause of this exception is that the 'stopped' event is coming before the 'initialized' event. I would not expect any 'stopped' events until initalization has completed.

Notice that everything works fine, if debugger statmment is ommited and there is a breakpoint on a first line or if `"stopOnEntry": true`

**Comment by weinand** [comment]
works fine now.
