### ISSUE TITLE
Icons not showing in Visual Studio Code header

### ISSUE THREAD

**Issue by jamielukephillips** [microsoft/vscode#115436]
Dear Sir/Madam,

I have having a problem where some of the icons are not showing my Visual Studio Code. I am unable to find tools on the toolbar at the top of the screen. Please could you help me with this?

Kind regards,

Jamie

(please respond to jamielukephillips@gmail.com)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill issue according to template with all necessary info (better just copy from issue report from VS Code)

Also there was recent issue with icons in Insiders builds #114743 but it is already resolved

**Comment by jamielukephillips** [comment]
Thanks for your response. This issue has been occurring since I downloaded Visual Studio weeks ago.  The missing icons on the toolbar are always absent.

**Comment by IllusionMH** [comment]
Still no useful info that will help to see that issue.
Template requires VS Code version, OS version etc.

Also screenshot will be helpful.

**Comment by jamielukephillips** [comment]
![image](https://user-images.githubusercontent.com/71874875/106357512-66bfe780-62fe-11eb-8fd1-bdf757986286.png)
64-bit operating system, Visual Studio version 1.50.1

**Comment by gjsjohnmurray** [comment]
That all looks fine apart from if the status bar message about the Python extension loading never disappears, in which case please log an issue with the extension author. The Report Issue option from the Help menu can help you do that.

In your original post here you mentioned missing tools on the toolbar at the top of the screen. But VS Code doesn't have such a toolbar.
