### ISSUE TITLE
Custom editors do not have good error handling when saving fails

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115414]
Context: https://github.com/microsoft/vscode/issues/115028#issuecomment-769813586

Repro:

1. Throw in your custom editor extension's `saveCustomDocument` implementation
2. Debug
3. Open custom editor
4. Make a change, exception occurs on auto save
5. Try close, error notification shows
6. Stop debugging, waiting for dirty editors to save notification shows

![recording](https://user-images.githubusercontent.com/2193314/106291072-05b1ea00-6200-11eb-999a-5ac62dba9e6a.gif)

Related issue I just created for dirty custom editors with auto save: https://github.com/microsoft/vscode/issues/115404

**Comment by bpasero** [comment]
Looks like we still have some specific code for handling save errors that is not generic enough to handle the custom editor, e.g.:
* you don't see any notification when save fails
* the editor does not indicate dirty

![image](https://user-images.githubusercontent.com/900690/106305901-936ff280-625d-11eb-8510-5aebc1954ec5.png)

**Comment by bpasero** [comment]
@Tyriar I pushed some commits today that should improve this, can you maybe retry your scenario? Mainly:
* custom editors no longer hide dirty indication on auto save (https://github.com/microsoft/vscode/issues/115526)
* shutdown is no longer prevented when running from an extension development window (https://github.com/microsoft/vscode/commit/c2759462f8bacd367ccaae30c23af2b09ff1929d)

**Comment by Tyriar** [comment]
@bpasero thanks, made a note to try it out in tomorrow's insiders

**Comment by bpasero** [comment]
Closing as per https://github.com/microsoft/vscode/issues/115028#issuecomment-771444544 where you can see how this behaves now. The underlying reason why the notification appears and never ends is actually https://github.com/microsoft/vscode/issues/115588

**Comment by Tyriar** [comment]
@bpasero much better 👍
