### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'symbol' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1154]
Issue Id: <b>2f6a083e-4961-8bfb-9851-be9a373466cf</b><br /><br />*Versions* <br />- 0.10.3<br />*Stack* <br />TypeError: Cannot read property 'symbol' of undefined<br />[/vs/editor/contrib/codelens/browser/codelens.ts#L94:8 (CodeLensContentWidget)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/contrib/codelens/browser/codelens.ts#L94:8 (CodeLensContentWidget))<br />[/vs/editor/contrib/codelens/browser/codelens.ts#L433:7 (CodeLensContribution.onModelChange)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/contrib/codelens/browser/codelens.ts#L433:7 (CodeLensContribution.onModelChange))<br />    at Array.forEach (native)<br />[/vs/editor/contrib/codelens/browser/codelens.ts#L431:24 (CodeLensContribution.onModelChange)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/contrib/codelens/browser/codelens.ts#L431:24 (CodeLensContribution.onModelChange))<br />[/vs/editor/contrib/codelens/browser/codelens.ts#L306:8 (CodeLens)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/contrib/codelens/browser/codelens.ts#L306:8 (CodeLens))<br />[/vs/base/common/async.ts#L296:0](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/async.ts#L296:0)<br />

**Comment by alexandrudima** [comment]
Stack is broken
