### ISSUE TITLE
The 'x' button to close a tab doesn't always work

### ISSUE THREAD

**Issue by oheard** [Microsoft/vscode#11543]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04.1

VSCode seemingly randomly forgets how to close tabs, furiously clicking the 'x' will eventually close the tab. There are no lockups/freezes when this happens, just the 'x' click being ignored (aside from animating on click).

Steps to Reproduce:

1. Open lots of files
2. Start closing them
3. Notice that although the X animates on press, not all tabs are closed
4. If all the tabs closed first time, go to step 1.

**Comment by bpasero** [comment]
We recently fixed something in this area, maybe you try from the insiders build:

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
Assuming this is fixed in 1.5.

**Comment by oheard** [comment]
Just to confirm, I haven't experienced this issue since 1.5. Thanks @bpasero :smile:
