### ISSUE TITLE
TypeScript: rename enum doesn't cascade changes

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#11548]
Version 2.1.0-dev.20160905

Given:

``` ts
    enum Foo { Bar }

    type Baz = {
        type: Foo.Bar
    }

    const baz: Baz = { type: Foo.Bar };
```

When I rename `Foo.Bar` on line one, it only renames usages of the enum as a value, not as a type.

Expected result (rename to Bob)

``` ts
    enum Foo { Bob }

    type Baz = {
        type: Foo.Bob
    }

    const baz: Baz = { type: Foo.Bob };
```

Actual result

``` ts
    enum Foo { Bob }

    type Baz = {
        type: Foo.Bar
    }

    const baz: Baz = { type: Foo.Bob };
```

![image](https://cloud.githubusercontent.com/assets/921609/18252278/afe4062a-7385-11e6-8dfc-0a4154716a18.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10732
