### ISSUE TITLE
Terminal issue (Letters Distortion)

### ISSUE THREAD

**Issue by ahmadfaizan965** [microsoft/vscode#115460]
- VSCode Version:1.52.1
- OS Version: Xubuntu 20.4 LTS 64-Bit (Linux)

Launch with `code --disable-extensions` to check.
Does this issue occur when all extensions are disabled?: Yes
***
# Terminal Issue while running Python file.
I encountered this issue a little while ago. When ever i am running a **Python File** in integrated terminal, it is executing properly but i am unable to see the output as the letters are distorted and messed up.

i tried to re-install the app but nothing changed. *This is particularly happening with a *Python File* only.*

i am attaching the screenshot for your reference.

![VSCODE terminal issue2](https://user-images.githubusercontent.com/69793423/106357605-10b66880-632d-11eb-8beb-989668ef0a21.png)

**Comment by ahmadfaizan965** [comment]
can you please tell me what specific details you need.

**Comment by meganrogge** [comment]
> Try changing the renderer type and zooming in and out

**Comment by ahmadfaizan965** [comment]
i just changed the Renderer Type from  'auto' to "DOM" and the issue is resolved. Now i can continue using VSCODE for Python development. Thanks @meganrogge
