### ISSUE TITLE
Git: change default keybinding for Revert selected lines from editorText

### ISSUE THREAD

**Issue by kasecato** [microsoft/vscode#115459]
As a git user, I want to revert selected ranges in `editorTextFocus`. So that I can revert changes from a text editor instead of from source control diffs.

# Before
```json
	{
		"key": "cmd+k cmd+r",
		"command": "git.revertSelectedRanges",
		"when": "isInDiffEditor"
	}
```
https://user-images.githubusercontent.com/10364603/106356773-7878ad80-6345-11eb-834c-8638791426ba.mov

# After
```json
	{
		"key": "cmd+k cmd+r",
		"command": "git.revertSelectedRanges",
		"when": "editorTextFocus && !editorReadonly"
	}
```
https://user-images.githubusercontent.com/10364603/106356782-7f9fbb80-6345-11eb-81a1-33b6929e8ec3.mov

# Related issue
- https://github.com/microsoft/vscode/issues/93564
- https://github.com/kasecato/vscode-intellij-idea-keybindings/issues/205

**Comment by gjsjohnmurray** [comment]
Default keybindings are not usually changed. You should be able to change your own if you don't like the defaults.

**Comment by kasecato** [comment]
I see. Thanks
