### ISSUE TITLE
When the filename of a C# does not match the class name, the `ctor` snippet generates the wrong code

### ISSUE THREAD

**Issue by richardthombs** [microsoft/vscode#115490]
- VSCode Version: 1.52.1
- Edition:	Windows 10 Pro
- Version:	20H2
- OS build: 19042.782
- Experience: Windows Feature Experience Pack 120.2212.2020.0

Steps to Reproduce:

1. Create a dot net project
2. Create a new file called "NotAClassName.cs"
3. In the file, create an empty class called "ThisIsMyClass".
4. Inside the class, activate the `ctor` snippet to create a constructor.
5. Observe that the constructor name is called `NotTheClassName`

![image](https://user-images.githubusercontent.com/1511599/106377465-0def5e00-6395-11eb-87d9-70b00f22cdd8.png)

**Comment by gjsjohnmurray** [comment]
A snippet can use the current filename but I don't think it can access the file content. Even if it could, it would then have to extract the classname.

A language extension could use CompletionitemProvider and respond that way instead of offering a static ctor snippet.

**Comment by richardthombs** [comment]
Thanks @gjsjohnmurray , do you think I should I be reporting this in a different repo? I don't know how to determine what provides the `ctor` snippet in the first place.

**Comment by gjsjohnmurray** [comment]
/extC#

https://github.com/OmniSharp/omnisharp-vscode/blob/136383252fb46c02fec693b6b06367d65cd1dfff/snippets/csharp.json#L455 

When intellisense shows the list that includes ctor, pressing Ctrl+space should give you extra info, but I don't recall if that includes origin.
