### ISSUE TITLE
Continual pasting results in lag or changing appearance

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115422]
Version: 1.53.0-insider (user setup)
Commit: 5a52bc29d5e9bc419077552d336ea26d904299fa
Date: 2021-01-29T05:13:48.533Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Testing #112382 

When I hold and paste � for long enough, the settings seem to change around.
![good-control](https://user-images.githubusercontent.com/7199958/106305812-03f12200-6212-11eb-9811-c37213517ac0.gif) 

Meanwhile, continually pasting the following heavily lags the editor:
`ttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest`

**Comment by alexdima** [comment]
@rzhao271 It looks like you are making edits to the `settings.json` file and adding invalid JSON. I'm not sure what you would expect to happen.

**Comment by sandy081** [comment]
Adding invalid content to `settings.json` can cause inconsistent behaviour and it is expected. Our JSON parser tries to recover and read as much as valid settings as possible. I do not think we can do more than that. 

I am closing this, since it is an unrealistic scenario.

**Comment by rzhao271** [comment]
Just a note that I forgot to try out the pasting in another file, and thought it applied to them too, hence the papercut label.
Thanks for explaining what was happening!
