### ISSUE TITLE
Odd tree hover flicker (seems to build up)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#115418]
![flash](https://user-images.githubusercontent.com/641685/106200772-7ff15880-6185-11eb-859c-15136b02fa58.gif)

_Originally posted by @eamodio in https://github.com/microsoft/vscode/issues/112750#issuecomment-769408931_

**Comment by alexr00** [comment]
I can no longer repro this. Seems like it's fixed by https://github.com/microsoft/vscode/commit/3ec92ad8ad55de21bcc3f253481486fd632b79c7. Please let me know if you can still repro it!

**Comment by eamodio** [comment]
Yup, looks gone now.
