### ISSUE TITLE
"Duplicating files" on changing file name case #113957

### ISSUE THREAD

**Issue by SergeyBeloglazov** [microsoft/vscode#115498]
- VSCode Version: 1.53.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
https://github.com/microsoft/vscode/issues/113957#issuecomment-770396780

Does this issue occur when all extensions are disabled?: Yes

PS. I can't find any information in Wiki, what I have to do, if I was late and the issue is closed automatically - start new issue or continue old, closed. Is there any information about it?
So I'm sorry for duplicating my issue.

**Comment by isidorn** [comment]
This is a duplicate of a casing tab issue that @bpasero is already aware of
Thanks
