### ISSUE TITLE
Shebang should take precedence over filename or extension

### ISSUE THREAD

**Issue by dkebler** [microsoft/vscode#115427]
Issue Type: <b>Bug</b>

Per issue I had with shell linter extension VScode should consider a shebang in the filename over the filename and or file extension when determining file type.   In my case using a file with name of  `env` was picked up by vscode as a vscode environment file intead of being considered a bash shell file for which the extension would have been enabled.   I had to tell vscode specifically that `env` was a bash file to fix this which isn't a good work around as `env` might be used in many contexts.

https://github.com/timonwong/vscode-shellcheck/issues/156#issuecomment-769968494

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.54GB (7.01GB free)|
|Process Argv|--no-sandbox --unity-launch /opt --crash-reporter-id b020dad4-c065-4679-9865-4e9e15ca324d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-format|fox|7.0.1
vscode-docker|ms-|1.9.1
remote-containers|ms-|0.155.1
markdown-preview-enhanced|shd|0.5.16
shellcheck|tim|0.12.3

</details>

**Comment by bpasero** [comment]
//cc @alexdima, I think the issue here is that an extension wins over our built in languages. In the referenced comment it seems to me that `env` is guessed as `dotenv` likely from an extension.
