### ISSUE TITLE
Terminal blocking due to Xcode will cause error

### ISSUE THREAD

**Issue by leungyauming** [microsoft/vscode#115499]
Issue Type: <b>Bug</b>

After installing Xcode, the terminal will be blocked for a while when opening the terminal for the first time after booting/rebooting.
In other words, if I dont open the terminal myself once after every boot/reboot to prevent the terminal being blocked, Visual Studio Code will inform me with the "Unable to resolve your shell environment in a reasonable time. Please review your shell configuration" error.

Sorry for my bad English, I'm not a native English speaker.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by leungyauming** [comment]
vscode.gif shows the error.
terminal.jpg shows the long blocking period caused by Xcode after boot/reboot.

I believe the long blocking period shown in terminal.jpg is the reason causes the error in vscode.gif

![vscode](https://user-images.githubusercontent.com/50203211/107007946-295fcc00-67ce-11eb-9628-e2e4631b949b.gif)
![terminal](https://user-images.githubusercontent.com/50203211/107009333-db4bc800-67cf-11eb-9b33-8f4deb618e0e.jpg)

**Comment by meganrogge** [comment]
not confirmed
