### ISSUE TITLE
Tasks have different encoding than shell, breaks build task

### ISSUE THREAD

**Issue by nocksock** [Microsoft/vscode#11544]
I have a fairly complex build task using grunt, which breaks when I try to use Tasks. However it works fine, when I use the Integrated Terminal. 

I get the following error:

```
Running "concurrent:buildTemplates" (concurrent) task
    Warning: Error: Invalid US-ASCII character "\xC3"
            on line 2 of original/scss/settings/_mixins.scss
            from line 3 of original/scss/main.scss
      Use --trace for backtrace. Use --force to continue.
```

Which is due to a `ü` in a comment. So I'm guessing it has something to do with the encoding, but I'm not sure what to do.

**Comment by dbaeumer** [comment]
Yes, has something to do with the encoding. Dups #3550
