### ISSUE TITLE
Settings editor: Provide simple/advanced filter mode

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115410]
Related/parent issue: #70589

An idea @eamodio and I were discussing was the idea of a simple and advanced mode. We could opt-in core settings as simple settings for example which would be the ones that show up by default, unless some checkbox on the settings UI was checked. This would help surface the settings that really matter to most users and hide the settings that only power users would care about. Some examples:

Simple settings:

- editor.minimap.enabled
- terminal.integrated.fontSize

Advanced settings:

- editor.minimap.renderCharacters
- editor.minimap.showSlider
- editor.minimap.maxColumn
- editor.minimap.scale
- editor.minimap.side
- editor.minimap.size
- terminal.integrated.fontWeight
- terminal.integrated.fontWeightBold

Extensions could then leverage this simple setting category to cut down what's exposed in the settings UI.

The toggle could show up here?

![image](https://user-images.githubusercontent.com/2193314/106286026-0c3d6300-61fa-11eb-84f5-7d51ed9a0229.png)

**Comment by roblourens** [comment]
@JacksonKearl is there any plan to extend the Getting Started experience to do more configuration beyond theme, keymap, etc?

**Comment by JacksonKearl** [comment]
We might do a few more, but generally we're trying to direct folks to existing UI rather than create a 4th settings editor experience.

**Comment by rzhao271** [comment]
I'd like to look more into how I could improve the searching capabilities of the Settings editor, instead.
Implementing a simple/advanced filter would also project a judgement of which settings are simple and which ones aren't.
