### ISSUE TITLE
Buffer() Deprecation Warning, when installing a  extension manually on code insiders

### ISSUE THREAD

**Issue by ciruz** [microsoft/vscode#115587]
- VSCode Version:1.53.0-insider (user setup)
- OS Version:Windows_NT x64 10.0.19042
- Commit: b99487f4168ba70369edfb8629303be0d3979d4b

Steps to Reproduce:

1. Get ``.vsix`` file from store, I used https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-de , since VSCode can't auto update this right now.
2. Manually install the extension via ``code-insiders --install-extension MS-CEINTL.vscode-language-pack-de-1.53.1.vsix``

Result:
```console
code-insiders --install-extension MS-CEINTL.vscode-language-pack-de-1.53.1.vsix

Installing extensions...
(node:24484) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'MS-CEINTL.vscode-language-pack-de-1.53.1.vsix' was successfully installed.
```

Does this issue occur when all extensions are disabled?: Yes

with disabled extensions:
```console
code-insiders  --disable-extensions --install-extension MS-CEINTL.vscode-language-pack-de-1.53.1.vsix
Installing extensions...
(node:15644) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'MS-CEINTL.vscode-language-pack-de-1.53.1.vsix' was successfully installed.
```

**Comment by sandy081** [comment]
/duplicate

#82524
