### ISSUE TITLE
Problem occurs while renaming a file name in the EXPLORER.

### ISSUE THREAD

**Issue by udayraj21** [microsoft/vscode#115518]
Issue Type: <b>Bug</b>

In the left side, in EXPLORER, when I right-click on a file name and select rename and I start changing file name, it leaves focus suddenly and file name gets incomplete.

For example, file name is "user.component.ts" and expecting "user-list.component.ts" and when I try to rename it, it gets "use.component.ts" or "user-l.component.ts" or "user-lis.component.ts" or something else.

It shoud be stay focused until I click outside or hit Enter.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.56GB (2.23GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 018f242f-9a17-4394-8c4f-5ee84a68d968|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.1.3
prettier-vscode|esb|5.8.0
Angular2|joh|11.0.0
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vscode-scss-formatter|sib|2.1.0
php-formatter|Sop|0.2.4
vscode-icons|vsc|11.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in the upcoming release of 1.53 expected this week.
