### ISSUE TITLE
ICustomEditorInputFactory is not implemented properly anywhere?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115516]
I noticed how we have a method `registerCustomEditorInputFactory` to register a `ICustomEditorInputFactory`. The interface itself is not exported (why?) and when I search for implementations of `createCustomEditorInput` I only find `static` implementations here:

https://github.com/microsoft/vscode/blob/51dc3193d3f92c0d1854be9b1a462d0cedbd8a7e/src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts#L108-L108

and here:

https://github.com/microsoft/vscode/blob/51dc3193d3f92c0d1854be9b1a462d0cedbd8a7e/src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts#L108-L108

When I export `ICustomEditorInputFactory` and let those implement `ICustomEditorInputFactory` I rightfully get a TS error.

PS: totally unclear to me why TS is not showing an error already now

**Comment by mjbvz** [comment]
This interface is implemented statically on the custom editor input factory:

https://github.com/microsoft/vscode/blob/51dc3193d3f92c0d1854be9b1a462d0cedbd8a7e/src/vs/workbench/contrib/customEditor/browser/customEditorInputFactory.ts#L108

This is valid TS but I'll refactoring it to make this code more clear
