### ISSUE TITLE
[Feature Request] Exclude namespaces in intellisense popups

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#115534]
If I'm editing a c# file, and I hover over a class/method/whatever then I get an intellisense popup with the xml documentation comments.

For example, `EndpointRoutingApplicationBuilderExtensions.UseEndpoints()`:
> The Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware defines a point in the middleware pipeline where routing decisions are made, and an Microsoft.AspNetCore.Http.Endpoint is associated with the Microsoft.AspNetCore.Http.HttpContext. The Microsoft.AspNetCore.Routing.EndpointMiddleware defines a point in the middleware pipeline where the current Microsoft.AspNetCore.Http.Endpoint is executed. Middleware between the Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware and Microsoft.AspNetCore.Routing.EndpointMiddleware may observe or change the Microsoft.AspNetCore.Http.Endpoint associated with the Microsoft.AspNetCore.Http.HttpContext.

It's very hard to read and understand all that noise, and in a little popup.

This is easier:
> The EndpointRoutingMiddleware defines a point in the middleware pipeline where routing decisions are made, and an Endpoint is associated with the HttpContext. The EndpointMiddleware defines a point in the middleware pipeline where the current Endpoint is executed. Middleware between the EndpointRoutingMiddleware and EndpointMiddleware may observe or change the Endpoint associated with the HttpContext.

Please add a setting where the full namespaces are ignored when showing intellisense.

This applies to other languages too, like Java. Any language that uses namespaces.

**Comment by jrieken** [comment]
You can use the `suggest.showXYZ` setting for this

**Comment by lonix1** [comment]
Thanks, I didn't know about those settings.

But they don't help, this is what I found:
````json
"editor.suggest.showClasses": true,
"editor.suggest.showColors": true,
"editor.suggest.showConstants": true,
"editor.suggest.showConstructors": true,
"editor.suggest.showCustomcolors": true,
"editor.suggest.showEnumMembers": true,
"editor.suggest.showEnums": true,
"editor.suggest.showEvents": true,
"editor.suggest.showFields": true,
"editor.suggest.showFiles": true,
"editor.suggest.showFolders": true,
"editor.suggest.showFunctions": true,
"editor.suggest.showIcons": true,
"editor.suggest.showInlineDetails": true,
"editor.suggest.showInterfaces": true,
"editor.suggest.showIssues": true,
"editor.suggest.showKeywords": true,
"editor.suggest.showMethods": true,
"editor.suggest.showModules": true,
"editor.suggest.showOperators": true,
"editor.suggest.showProperties": true,
"editor.suggest.showReferences": true,
"editor.suggest.showSnippets": true,
"editor.suggest.showStatusBar": false,
"editor.suggest.showStructs": true,
"editor.suggest.showTypeParameters": true,
"editor.suggest.showUnits": true,
"editor.suggest.showUsers": true,
"editor.suggest.showValues": true,
"editor.suggest.showVariables": true,
"editor.suggest.showWords": true,
````

I don't "suggest" (:wink:) that we disable anything - just that we don't show namespaces. These settings don't control that.

Or am I mistaken?

**Comment by jrieken** [comment]
Yes - I was mistaken. IntelliSense mean suggestion in our world. Tho, I don't be able to help you and I have to close this as "cuased by extension" because there is nothing we can do about this. Hovers are just textual and we have no structured understanding of what's in it

**Comment by lonix1** [comment]
Okay I understand now thanks. Maybe the omnisharp repo is the right place for this.
