### ISSUE TITLE
 Cannot read property 'editOperations' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1155]
Issue Id: <b>2ec89842-1cd7-8e05-0e52-47e2d4ca87a8</b><br /><br />*Versions* <br />- 0.10.3<br />-  7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066<br />*Stack* <br />TypeError: Cannot read property 'editOperations' of null<br />[/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts#L5:0](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts#L5:0)<br />[/vs/editor/common/model/textModelWithDecorations.ts#L738:50 (ModelDecorationOptions._htmlContentArrEquals)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/model/textModelWithDecorations.ts#L738:50 (ModelDecorationOptions._htmlContentArrEquals))<br />[/vs/editor/common/controller/cursor.ts#L559:3 (Cursor._getEditOperations)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L559:3 (Cursor._getEditOperations))<br />[/vs/editor/common/controller/cursor.ts#L476:4 (Cursor._getEditOperationsFromCommand)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L476:4 (Cursor._getEditOperationsFromCommand))<br />[/vs/editor/common/controller/cursor.ts#L273:35 (Cursor.getSelection)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L273:35 (Cursor.getSelection))<br />[/vs/editor/common/controller/cursor.ts#L196:37 (Cursor.restoreState)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L196:37 (Cursor.restoreState))<br />[/vs/editor/common/controller/cursor.ts#L1153:9 (Cursor)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L1153:9 (Cursor))<br />[/vs/editor/common/controller/cursor.ts#L906:80 (Cursor._registerHandlers)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L906:80 (Cursor._registerHandlers))<br />[/vs/editor/common/controller/cursor.ts#L217:8 (Cursor)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L217:8 (Cursor))<br />[/vs/editor/common/controller/cursor.ts#L196:37 (Cursor.restoreState)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/editor/common/controller/cursor.ts#L196:37 (Cursor.restoreState))<br />

**Comment by alexandrudima** [comment]
Stack is broken
