### ISSUE TITLE
scm view mode "list" not working

### ISSUE THREAD

**Issue by Siddharth-Ashri** [microsoft/vscode#115550]
Issue Type: <b>Bug</b>

despite including `"scm.defaultViewMode": "list"` and restarting vs code the view mode is still tree. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz (4 x 1100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 4|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|. --crash-reporter-id 1c3958a9-16fc-4edf-b7b2-60198baaeddc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.6.3
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vue-peek|dar|1.0.2
git-diff-and-merge-tool|dav|1.0.4
vscode-eslint|dba|2.1.14
gitlens|eam|11.1.3
vscode-html-css|ecm|1.9.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.8.0
font-switcher|eva|3.1.0
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
phpcs|ika|1.0.5
vscode-edit-csv|jan|0.5.4
php-cs-fixer|jun|0.1.158
php-xdebug|kak|0.0.7
php-namespace-resolver|Meh|1.1.8
xml-format|mik|1.1.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-scss|mrm|0.9.0
vsliveshare-pack|ms-|0.4.0
vscode-json-editor|nic|0.2.3
vetur|oct|0.32.0
fix-json|oli|0.1.2
laravel-blade|one|1.25.0
material-icon-theme|PKi|4.5.0
live-preview|pro|0.0.3
phpdoc-generator|ron|1.1.1
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
svg-preview|Sim|2.8.3
php-formatter|Sop|0.2.4
sass-indented|syl|1.8.15
html-preview-vscode|tht|0.2.5
vsfire|tob|1.4.1
vscode-status-bar-format-toggle|tom|2.0.0
highlight-matching-tag|vin|0.10.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
vstry914:30250197
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

![Screen Shot 2021-02-01 at 11 21 42 AM](https://user-images.githubusercontent.com/39203389/106487159-63ed0000-6480-11eb-9709-ec02b94b08fa.png)

**Comment by Siddharth-Ashri** [comment]
https://github.com/microsoft/vscode/issues/81384#issuecomment-534695124
i suspect the toggle view mode button overrides the settings.json file?

**Comment by eamodio** [comment]
@joaomoreno I can repro this -- but was this intentional -- e.g. remember the last chosen value even on reload?

**Comment by joaomoreno** [comment]
Yeah it's intentional, this is why it's called _default_. It's the default value to apply in new workspaces. But if the user toggles it, then the user preference stays.
