### ISSUE TITLE
I recently installed VS Code on my HP ENVY Laptop and whenever I run the program it'll pop open then go invisible

### ISSUE THREAD

**Issue by kleos1421** [microsoft/vscode#115504]
VsCode Version: 1.52
OS Version: Windows 10 Home //Version	10.0.19041 Build 19041

I installed VSCode and when ever I try to boot it up the program will be visible for a fraction of a second and then it goes invisible. I've tried messing with the compatabilities option, I've ran it as an admin and even uninstalled and reinstalled.

Yes I did reboot my pc... 

Note: I have create path checked when installing it.
I use to have VSCode a while ago and I had a theme that was transparent on this very same pc. If VSCode is loading my profile settings from a while ago I need help removing the extension while the window is invisible.

**Comment by kleos1421** [comment]
VsCode Version: 1.52
OS Version: Windows 10 Home //Version	10.0.19041 Build 19041

I installed VSCode and when ever I try to boot it up the program will be visible for a fraction of a second and then it goes invisible. I've tried messing with the compatabilities option, I've ran it as an admin and even uninstalled and reinstalled.

Yes I did reboot my pc... 

Note: I have create path checked when installing it.
I use to have VSCode a while ago and I had a theme that was transparent on this very same pc. If VSCode is loading my profile settings from a while ago I need help removing the extension while the window is invisible.

**Comment by kleos1421** [comment]
If I open a random VSCode project file it'll stay visible.....

**Comment by gjsjohnmurray** [comment]
Try launching from a Windows command prompt like this:
```
cd %localappdata%\programs\microsoft vs code
code --disable-extensions
```

**Comment by deepak1556** [comment]
Do you still experience the issue with latest version `1.53.2` ?
