### ISSUE TITLE
As a user I want to be able to set the exception type for exception breakpoints

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode#11552]
- VSCode Version: 1.4.0
- OS Version: 10.11.5

Currently the exception breakpoint settings apply to all types of exceptions. In many languages such as Clojure/Java, there is a hierarchy of exception classes and it is convenient to only break on specific exception types. For instance if I see an exception caused by a ClassCastException I want to be able to set a breakpoint that will only trigger for ClassCastExceptions.

I think this would merely entail an input text box for typing the class to associate with a particular breakpoint, and this could be enabled only for debug adapters that report the capability to break on specific exception types.

**Comment by isidorn** [comment]
Currently our debug protocl supports that the vscode frontend can send exception filters to the backend. However the SetExceptionBreakpointsResponse would have to somehow notify vscode if an exception breakpoint is accepted or not. For instance a user could try to add a ClassCastException while debugging node and the vscode frontend would need to notify the user that this is ilegal.

Assigning first to @weinand to assess on this feature request.

**Comment by nbransby** [comment]
+1

**Comment by weinand** [comment]
The corresponding protocol addition is Microsoft/vscode-debugadapter-node/issues/64

**Comment by weinand** [comment]
@indiejames so your proposal would be this:
- the user would add an exception breakpoint via some action
- a text input box shows up where the user can enter the name of an exception class
- the exception breakpoint shows up in the BREAKPOINTS view (maybe under a new root node)
- the user can disable/enable the breakpoint.

In Microsoft/vscode-debugadapter-node#64 it was proposed to support the following configuration options for an exception breakpoint:

- disabled: do not break when this exception is thrown,
- unhandled: break if the exception is unhandled,
- userUnhandled: break if the exception is not handled by user code,
- thrown: break when the exception is thrown.

Do these options make sense for you? Which options could your debugger support?

**Comment by weinand** [comment]
@indiejames any comments to my last comment?

**Comment by weinand** [comment]
We've added support for exception configuration to the debug protocol (Microsoft/vscode-debugadapter-node#64).
Now we'll have to decide whether/how to surface that in the generic VS Code debugger UI.

**Comment by indiejames** [comment]
@weinand Sorry, I didn't see your comments earlier. I think those options look good. I think all of those options apply to me except "unhandled". The REPL I execute code in always traps exceptions at the top level, so there are no "unhandled" exceptions. I'm not sure if I can trigger an event when that happens or not. For now these look good to me.

**Comment by weinand** [comment]
@indiejames Please see what I was able todo in the mono-debug extension without touch anything in VS Code itself:

![2017-04-04_15-17-17](https://cloud.githubusercontent.com/assets/1898161/24697055/0e1622fc-19ec-11e7-8919-d1bc1181b517.gif)

The code is [here](https://github.com/Microsoft/vscode-mono-debug/blob/master/src/typescript/extension.ts#L90)

**Comment by indiejames** [comment]
@weinand That looks pretty good. I like the search completion to find the desired exception class. What is displayed in the Breakpoints pane of the Debug viewlet?

**Comment by weinand** [comment]
@indiejames these exception configurations don't show up in the breakpoints pane (because the UI would would not scale if you have lots of exceptions and because there is no API for adding them to the breakpoints pane). The exception configurations are managed completely independent from VS Code breakpoints in "settings" (user or workspace).
