### ISSUE TITLE
PATH not read properly in terminal.integrated.env.linux

### ISSUE THREAD

**Issue by bcorcoran** [microsoft/vscode#115553]
- VSCode Version: 1.52.1
- OS Version: elementaryOS 6 (Linux)

Steps to Reproduce:

1. Open integrated terminal
2. Try to run literally any command

Does this issue occur when all extensions are disabled?: Yes

Trying to use the integrated terminal in VSCode, and it won't read the path properly. It can't even find binaries that are in the (incorrect) PATH it does have.

For example:

VSCode's (incorrect) path is currently: `/app/bin:/usr/bin:/home/bcorcoran/.var/app/com.visualstudio.code/data/node_modules/bin`

and if I try to launch even vi/vim, which is located at `/usr/bin/vi` it says it cannot find the command. Obviously this is totally wrong.

I've tried setting the PATH key in `terminal.integrated.env.linux` but it doesn't seem to have any effect. I'm not even sure what I should be putting for the value but I'd like it to source the PATH from my .bashrc... it's reading my PS1 prompt, so I'm pretty confused right now.

**Comment by Tyriar** [comment]
Can you share your settings.json file?

**Comment by bcorcoran** [comment]
```
"terminal.integrated.shell.linux": "/bin/bash",
"terminal.integrated.env.linux": {
"PATH": process.env.PATH 
}
```

I've tried $PATH, or even manually entering in the path and it seems to have no effect. I've restarted vscode multiple times.

**Comment by bcorcoran** [comment]
I'm not sure if you want to keep this open, but I think this was caused by the Flatpak version of VSCode. I uninstalled and then reinstalled via the .deb on the VSCode website and the terminal now works as expected.
