### ISSUE TITLE
File collapse arrow

### ISSUE THREAD

**Issue by andrew-jolley** [microsoft/vscode#115555]
Issue Type: <b>Bug</b>

When a folder is open, and sub-folders are open, the arrows by the side of the sub-folders face down. In the issue, when I 'close' the sub-folder, the arrows don't face to the right, it still faces down

VS Code version: Code - Insiders 1.53.0-insider (861a88ebadb4335df92251faf6420b598440e082, 2021-01-29T21:59:10.149Z)
OS version: Darwin arm64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 215d3acb-9c97-49ec-abbe-5281bc62d58f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vsc-python-indent|Kev|1.12.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedpromptcf:30219165
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also occur after you run the command to reload with all extensions disabled?

Can you record a short animated GIF or MP4 and post it here?

**Comment by andrew-jolley** [comment]
Yep after reloading with extensions it works properly and after re-enabling extensions it works properly. 

Andrew Jolley

**Comment by isidorn** [comment]
So sounds like one of your extensions is causing this
