### ISSUE TITLE
Special characters unreadable

### ISSUE THREAD

**Issue by johandanforth** [microsoft/vscode#115584]
- VSCode Version: 1.52.1
- OS Version: Win 10 pro (insider build) Version 2004 

![vscode_fido_special_characters](https://user-images.githubusercontent.com/527037/106560381-3c9d3e00-6527-11eb-95cf-5a6ab97f0e86.PNG)

Steps to Reproduce:

1. Open up a sample.cs code file with special (swedish) characters (looks fine in vs2019, also saved/created in vs2019)
2. Special characters undreadable in vs code
3. If saved in vs code with unreadable characters, the characters will also be unreadable in vs2019

Does this issue occur when all extensions are disabled?: Yes

I don't usually use national characters in code, this is old legacy code I'm about to update.
I suspect it's due to the file having wrong encoding. Will look into it later today.

**Comment by gjsjohnmurray** [comment]
Try clicking on the UTF-8 indicator in the status bar and reopening the file with the encoding it was written in.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for answering
If that does not work please ask this on stack overlfow, thus closing
