### ISSUE TITLE
Dragging and dropping from VS Code to a Codespace does not work

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115535]
**Describe the bug**

See title, it works when dragging from the explorer (Windows).

**To Reproduce**
1. Open VS Code
2. Open a codesapce
3. Try drag a file to the codespace, it throws an error

**Screenshots**

![image](https://user-images.githubusercontent.com/2193314/106459128-426f2280-6446-11eb-9380-b1542139e727.png)

**Additional context**

Desktop:

Version: 1.53.0-insider (user setup)
Commit: 861a88ebadb4335df92251faf6420b598440e082
Date: 2021-01-29T21:49:22.151Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Codespace:

Version: 1.53.0-insider
Commit: 861a88ebadb4335df92251faf6420b598440e082
Date: 2021-01-29T21:52:44.449Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.6 Safari/537.36 Edg/89.0.774.8

**Comment by bpasero** [comment]
I have spend a bit looking into this and don't think there is a lot we can do unless we start to add the entire content of a file into the data transfer or get some Electron API to help us here.

In web, we use `IWebkitDataTransfer` proprietary API from Chrome to get access to the file that is dragged. I am sure we are currently not filling this transfer when starting to drag from the explorer and I am not sure if there is any way to do so.

https://github.com/microsoft/vscode/blob/e375d137174ab15b9eadaf32428a980aa0a059e8/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1046-L1046

This API gives us file stream access to the actual file that is dragged and thus prevents us from having to fill the entire file contents into the transfer (and thus into memory).

I think the best fix here is to be able to fill that exact same transfer that Chrome fills when you drop a file e.g. from the finder into the browser but I am not sure how do get there.

https://github.com/microsoft/vscode/issues/164 is very much related.

**Comment by isidorn** [comment]
@bpasero thanks a lot for looking into this
I remember I was also trying to fill the same transfer that Chrome fills for a related issue and was unsucessful.

**Comment by Tyriar** [comment]
Can we get a notification saying it's not supported instead of an NPE?

**Comment by bpasero** [comment]
Or maybe even not show the drop feedback if we can detect this case 👍

**Comment by Tyriar** [comment]
That would be great too, in combination with a notification in case someone does try dropping it.

**Comment by isidorn** [comment]
Yes, that makes sense. Let's assign to Feb for nicer support

**Comment by isidorn** [comment]
Did not find time for this, moving out to next milestone when I plan to polish drag and drop a bit.

**Comment by isidorn** [comment]
We are now not showing any drop feedback on drag over for resources from vscode to web.
We will not show notification because we already have this pattern on drop not working in other cases and we always handle this with lack of drop feedback. Also if there is no drop feedback the tree does not even call back the explorer on drop so can not really do this.

**Comment by bpasero** [comment]
This change caused https://github.com/microsoft/vscode/issues/125041

**Comment by isidorn** [comment]
Thanks for fixing that one. I will need to put that check in a more precise place...
