### ISSUE TITLE
Search Mode setting does not open editors unless search view is visible

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#115511]
We register `Cmd+Shift+F` to both `Search: Find in Files` and `View: Search` for historic reasons:
```
// Show Search and Find in Files are redundant, but we can't break keybindings by removing one. So it's the same action, same keybinding, registered to different IDs.
// Show Search 'when' is redundant but if the two conflict with exactly the same keybinding and 'when' clause, then they can show up as "unbound" - #51780
```

With the addition of the new `search.mode` setting, https://github.com/microsoft/vscode/issues/112588, `Search: Find in Files` has potentially different behaviour from `View: Search`, but `View: Search` will always overpower it when it's context expression is true (`!searchViewletVisible`). This means that even after setting `search.mode`, `Cmd+Shift+F` will still open the search view, unless a separate keybinding is registered to unbind `View: Search`.

**Comment by sandy081** [comment]
@JacksonKearl @roblourens Just to confirm that if you are aware that this change will not show the keybinding for Search view anymore at following places:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/10746682/106486437-ef32b980-64b1-11eb-95e7-9798d9704924.png">

<img width="161" alt="image" src="https://user-images.githubusercontent.com/10746682/106486532-0a052e00-64b2-11eb-8d33-959010a5f1de.png">

Not sure if it is intended.

**Comment by JacksonKearl** [comment]
Not intended, thanks for the heads up. @roblourens we could add back the keybinding at a lower priority?

**Comment by JacksonKearl** [comment]
To verify:

Set `search.mode` to `newEditor`. Hit `cmd+shift+f` (make sure the search view isn't already focused), expect to see a new search editor created.
