### ISSUE TITLE
normal tab border top cover the pinned tab

### ISSUE THREAD

**Issue by ColorFuzzy** [microsoft/vscode#115532]
Issue Type: <b>Bug</b>

1. pin 5 tabs
2. open more files (not pinned)
3. scroll tab bar

![image](https://user-images.githubusercontent.com/1814478/106451119-0e851300-64c1-11eb-818a-19aebd013f65.png)

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.61GB free)|
|Process Argv|--crash-reporter-id 1555b0b7-9614-4ed3-8ac0-d4f4b3a159fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
Bookmarks|ale|12.1.4
project-manager|ale|12.0.1
asciidoctor-vscode|asc|2.8.7
vscode-browser-preview|auc|0.6.7
vscode-blink-mind|awe|0.0.10
browser|ayq|1.1.0
vscode-icontheme-nomo-dark|be5|1.3.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
markdown-table-prettify|dar|3.2.0
dart-code|Dar|3.19.1
flutter|Dar|3.19.0
svg-gallery|dev|2.1.0
clipboard-manager|Edg|1.4.2
xvscode|Eks|0.0.1
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.8.0
dictionary|Exi|0.0.2
vscode-highlight|fab|1.4.1
vscode-todo-plus|fab|4.18.2
foam-vscode|foa|0.9.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
markmap-vscode|ger|0.0.6
leek-fund|gis|1.9.5
gc-excelviewer|Gra|3.0.40
debug-visualizer|hed|2.0.6
vscode-drawio|hed|1.2.0
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
output-colorizer|IBM|0.1.2
shortcut-menu-bar|jer|2.2.0
svg|joc|1.4.5
json-escaper|jos|1.1.0
presentationmode|jsp|1.1.5
vscode-insertdatestring|jsy|2.3.0
language-julia|jul|1.0.10
theme-karyfoundation-themes|kar|20.0.3
favorites|kdc|2.4.5
vscode-markdown-notes|kor|0.0.22
vscode-leetcode|Lee|0.17.0
expand-region|let|0.1.4
fish-ide|lun|0.4.0
MagicPython|mag|1.1.0
Lisp|mat|0.1.11
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.8.1
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.9.1
vscode-edge-devtools|ms-|1.1.2
vscode-kubernetes-tools|ms-|1.2.3
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.3
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.3.0
vscode-gitignore-generator|pio|1.0.2
material-icon-theme|PKi|4.5.0
text-power-tools|qcz|1.19.1
quicktype|qui|12.0.46
vscode-yaml|red|0.14.0
color-manager|roy|0.6.1
gi|rub|0.2.11
vscode-markdown-header-coloring|sat|0.1.7
trailing-spaces|sha|0.3.1
fish-vscode|sky|0.2.1
vscode-fileutils|sle|3.4.3
vscode-mindmap|Sou|0.0.5
code-spell-checker|str|1.10.2
markdown-links|tch|0.8.0
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
pdf|tom|1.1.0
emacs-mcx|tut|0.25.0
codelf|unb|11.7.0
vscodeintellicode|Vis|1.2.11
org-mode|vsc|1.0.0
vscode-icons-mac|way|7.25.3
markdown-all-in-one|yzh|3.4.0

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by bpasero** [comment]
I think I fixed this already in insiders. 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ColorFuzzy** [comment]
> I think I fixed this already in insiders.
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Yes, it's fixed, thanks very much. I'll close this issue.
