### ISSUE TITLE
Insiders Build: search.action.openNewEditor keybindings args do not work in W10

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#115509]
FYI @JacksonKearl 

Related to https://github.com/microsoft/vscode-docs/commit/264e414af364eb256e5cd22e2455b02f2131bdb2#diff-8e4070848d66238a2f38844ad247ec18694d10b0e8704b5da4f2185a8d7ee920 ?

Steps to Reproduce:

1.  Set up a keybinding for `search.action.openNewEditor` with any `args`
2.  Trigger the keybinding, search editor opens but none of the `args` are used
3.   Same keybinding **works in Stable**

Demo using a workspace file: `file:///c:/Users/Mark/OneDrive/Test Bed/text2.txt`
Same result: `C:\Users\Mark\command-alias\src\extension.js`  (not involving OneDrive)

![searchEditorKeybindings1](https://user-images.githubusercontent.com/31813701/106408836-79b8e180-63fc-11eb-82d1-5f14bc58f1d6.gif)

Does this issue occur when all extensions are disabled?: Yes

Version: 1.53.0-insider (user setup)
Commit: 861a88ebadb4335df92251faf6420b598440e082
Date: 2021-01-29T21:49:22.151Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21301

Log Window) with `trace` enabled:

    [2021-01-31 19:44:09.185] [renderer1] [trace] CommandService#executeCommand workbench.output.action.clearOutput
    [2021-01-31 19:44:15.502] [renderer1] [trace] KeybindingService#dispatch Ctrl+Shift+G search.action.openNewEditor
    [2021-01-31 19:44:15.502] [renderer1] [trace] CommandService#executeCommand search.action.openNewEditor

**Comment by JacksonKearl** [comment]
Thanks, I can reproduce.

**Comment by JacksonKearl** [comment]
To verify:

Add a keybinding like:
```
  {
    "key": "shift+f8",
    "command": "search.action.openNewEditor",
    "args": {
      "contextLines": 20
    }
  }
```

Execute it, expect to see the context line input properly filled out.

**Comment by ArturoDent** [comment]
**Works for me (W10)**.  Used this keybinding just to test more args (see below for a comment in the args):  

```jsonc
{
  "key": "ctrl+shift+g",
  "command": "search.action.openNewEditor",
  "args": {
    
    "query": "CN=([^,]*).*$",
    "isRegexp": true,

    // "includes": "${file}",         // does not work, ripgrep error probably
    "includes": "${relativeFile}",    // works

    "showIncludesExcludes": true,
    "triggerSearch": true,
    "contextLines": 2,
    "focusResults": true,
  },
  "when": "editorTextFocus"
}
```
I suppose an issue should be filed on `${file}` not working if it was intended to - it does properly insert the full path, ala

`C:\Users\Mark\command-alias\src\extension.js`  - but fails silently and `Run Search` button does nothing.

**Comment by JacksonKearl** [comment]
thanks, as far as I'm aware directly putting that absolute path into the `includes` entry would fail as well, correct? So not a new issue.

**Comment by ArturoDent** [comment]
Yes, it fails inserting it directly into the `includes` arg (escaped properly) and in the `Search` view in the Panel `files to include` input - although in Search view it does show the error highlight around the query box and hover error message.  I will not file an issue on this.
