### ISSUE TITLE
Notebooks: revisit `revert` with `soft: true`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115596]
I found this code:

https://github.com/microsoft/vscode/blob/dc8ac78031bd6828bbb5e81d96a7e1d3a95798d0/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L126-L129

I am a bit confused:
* why does it discard the backup
* why does it not clear the dirty flag?

The idea of `soft: true` reverts is to only clear the dirty flag but not change the model or backups because the editor is about to close right after. This operation should succeed fast and not await promises.

The backup will automatically be discarded once the dirty flag clears.

**Comment by jrieken** [comment]
fyi - in https://github.com/microsoft/vscode/pull/116685 I have made it reset the dirty-flag
