### ISSUE TITLE
Inverted (natural) scrolling on Linux?

### ISSUE THREAD

**Issue by Streppel** [Microsoft/vscode#11553]
- VSCode Version: 1.4.0
- OS Version: Ubuntu (Lubuntu flavor) 16.04 LTS 

Steps to Reproduce:
1. Swipe with two fingers upwards 
2. Window moves up instead of down, though I have natural scrolling enabled on Lubuntu

Could it be the reason that natural scrolling is not a default preference in Lubuntu? Is there a way to enable natural scrolling on VSCode, though? I use it everywhere, it feels unnatural to behave differently when I'm using the editor.

[This has been asked on SO before, as well.
](http://stackoverflow.com/questions/36835562/inverted-scrolling-natural-in-vscode)

**Comment by xaverh** [comment]
In my case _synclient_ did the trick. You can change the value of VertScrollDelta to your choice (higher absolute value means faster scrolling, the minus changes the direction to 'natural scrolling'), eg

`synclient VertScrollDelta=-30`

**Comment by Streppel** [comment]
@xaverh this does the trick for everything (Firefox, Lubuntu's Leafpead, the default text editor etc), but VSCode, weirdly enough, remains the same. I guess I might try reinstalling it...

**Comment by Tyriar** [comment]
@Streppel can you try scrolling in the integrated terminal to see if that works correctly? Its scroll logic is separate to the editor's.

**Comment by Streppel** [comment]
@Tyriar scrolling the integrated terminal gives me the same result (two fingers upwards goes up instead of down)

**Comment by Tyriar** [comment]
@Streppel and Chrome works fine? I would expect this to be built into [`WheelEvent.deltaY`](https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent).

**Comment by Streppel** [comment]
@Tyriar I just downloaded and installed Google Chrome and it behaves accordingly (natural scroll ok, fingers upwards window moves down)

**Comment by alexandrudima** [comment]
@Streppel I can only imagine this is because we ship on an older version of Chromium (49).

You could use `"editor.mouseWheelScrollSensitivity": -1` to flip the direction

**Comment by Tyriar** [comment]
@alexandrudima should the terminal support that ideally as well or is it meant to be just for the editor, not panels/viewlets/etc?

**Comment by alexandrudima** [comment]
@Tyriar we could generalize and add a `mouse.wheelScrollSensitivity`. I can honor it in the editor because I use the custom scrollbars where scroll events are interpreted (it is not the browser scrolling).

**Comment by Tyriar** [comment]
Ah OK, I think the terminal is fine as is as it uses a native scroll bar currently.

**Comment by alexandrudima** [comment]
@Tyriar the custom scrollbars behave the same as the native scrollbar in terms of direction.

I've added a setting in the past, `editor.wheelScrollSensitivity` because folks asked to customize that (to make mouse wheel scrolling faster/slower), so I just multiply that with the values I get from the native scroll / mouse wheel event. Because we multiply, it is possible to flip directions by using a negative number.

If you wish the terminal to support flipping the direction through a user setting, you need to write some code to do so.
