### ISSUE TITLE
Setting to increase overview ruler width

### ISSUE THREAD

**Issue by aminomancer** [microsoft/vscode#115571]
I searched through the settings and google trying to find this so I'm pretty sure it doesn't already exist, but if I'm mistaken please let me know. I think there should be a setting to change the width of the overview ruler. This is one of the most useful features in vs code, I use it constantly and I use some extensions that mark even more things in the overview ruler.

So as a consequence it gets pretty full of markers. I would still like to increase the width of the ruler even if I didn't have extra marks from extensions, but its tinyness becomes especially noticeable when using extensions that add stuff to the ruler like GitLens and Bracket-pair-colorizer-2.

As far as I can tell, there isn't a way to increase the size of the ruler without increasing the size of everything else. Technically I guess you can zoom in on the editor and decrease the font size, but the latter seems to reset every time vs code starts.

We have options to resize the minimap so there should also be a way to resize the overview ruler. Btw, I noticed that the minimap scaling only works in proportional mode. I think there should just be a way to define the absolute width of the minimap and overview ruler, in pixels or I guess percent.

Anyway, that's my main request since it seems very feasible. I would also love if you could have more than 3 columns in the ruler, but I don't know how realistic that is since it might break a lot of extensions that expect to draw their markers to one of only 3 columns.

If a setting to add more columns seems unreasonable, maybe allowing the user to define some margin between the columns would be more practical. I know it looks cool that the markers are all precisely adjacent to each other, but when you have so many different colors of marker, sometimes you can get 2 right next to each other that are very similar in appearance. Anyway, thanks 😊

**Comment by usernamehw** [comment]
The editor has a hidden scrollbar size setting:

```js
"editor.scrollbar.verticalScrollbarSize": 20,
```

**Comment by alexdima** [comment]
Thank you @usernamehw , I forgot that setting also affects the overview ruler. 

@aminomancer You might need to restart vscode for the setting to apply.

**Comment by aminomancer** [comment]
thanks, that worked!
