### ISSUE TITLE
files.associations for inline tags

### ISSUE THREAD

**Issue by xxSkyy** [microsoft/vscode#115508]
its all about <style> tag

I want to use
`  "files.associations": {
    "*.css": "sugarss",
  },`
but for inline <style> tag itself 

Is it possible to set it up like that?

**Comment by aeschli** [comment]
No, it's not possible to define to associate an style element with another language than css.

**Comment by aeschli** [comment]
Closing as out of scope. We currently have no plans to support more than css in <style> tags.
