### ISSUE TITLE
Unable to set up anaconda enviuronment with visual studio code - error message 

### ISSUE THREAD

**Issue by jamielukephillips** [microsoft/vscode#115569]
Hi,

I have a 64-bit operating system, Visual Studio version 1.50.1

This is the error message I am receiving:

PS C:\Users\Jamie\OneDrive\Documents\Python Scripts> conda activate base
conda : The term 'conda' is not recognized as the name of   
a cmdlet, function, script file, or operable program.       
included, verify that the path is correct and try again.    
At line:1 char:1
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:Stri
   ng) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Thank you.

![image](https://user-images.githubusercontent.com/71874875/106525543-0dadaa80-64dc-11eb-9a3b-2df57f681a8d.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you able to run same command from native Power Shell not form integrated terminal.

Looks like you either need to add path to `conda` to PATH env variable or setup different terminal that would recognize it.

Nothing to do with VS Code edutor itself.
