### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by chrisjones0517** [microsoft/vscode#115510]
No matter what file I have open, the editor lags. This happens with copy/paste or simple typing, mainly with copy/paste. It's not showing excessive resource use on the system stats, so I'm not sure what's going on. It could be an extension, but I have quite a few extensions, so I want to see if you guys have run into this before before I systematically begin removing extensions.

Update 2/8/2021: 
Apologies for the late reply. I'm running Windows 10. The latest update caused some issues with other programs, so I rolled it back, and it had no effect on the VSC issue. I also followed the same procedures outlined by the commenter below to no avail.

Processor: Intel i7-6500U CPU @ 2.50 GHz
RAM: 8 GB
Lenovo machine with Samsung 512 GB SSD installed.
VSC version 1.53

It seems safe to assume the issue is independent of OS, per today's additional comment.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform. If version is recent enough, try using the extension bisect command. If no extension is identified as the cause, see the wiki for how to diagnose performance problems.

**Comment by apasashkov** [comment]
Have the same issue on brand new machine.

HARDWARE:
Ryzen 5900x (10% utilization)
RAM 32Gb (12gb used)

SOFTWARE:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: UBUNTU 20.04 kernel: Linux x64 5.8.0-41-generic

Any other app works smoothly (chrome, firefox, slack, libreoffice etc)

Tried restarting in dev mode with extensions OFF - same situation.

Dev console - 1 error related to the project, 99% sure not related to the issue (have the same error on different machine and no lagging).
Also, on different machine have older hardware (i7 6700 + 16gb ram) + older software (ubuntu 18.04 kernel 4.15). Same workload. Same VS code version - works much more smoother.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode-wiki/blob/master/Performance-Issues.md

**Comment by chrisjones0517** [comment]
Apologies, after all was said and done, the issue was completely unrelated to VSC. It was just more noticeable in that environment for a variety of reasons. Please consider the matter closed on my part.
