### ISSUE TITLE
Smoke test: replaces first search result with a replace term

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115586]
The smoke test for replacing in search fails and it seems to me that the search view by default now opens with search/replace expanded, but I am not sure when that happened.

I pushed a workaround: https://github.com/microsoft/vscode/commit/04d4310a8a5fbb8e9318f7ad5caca48f74ca5793

**Comment by bpasero** [comment]
Yes it does, from a fresh user data dir:

![image](https://user-images.githubusercontent.com/900690/106565761-96a20180-652f-11eb-9861-d84c2e556313.png)

**Comment by sandy081** [comment]
I cleaned up commands to open view containers and generalized them - So registering a view container also registers the command to open the view container - this will make user experience consistent when user opens the view container from various locations

- Activity Bar
- Menu > View
- Command Pallette
- Keyboard Shortcut

It seems Search view is behaving differently when opening from Activity Bar and from other places. In former, Replace input is shown where as latter does not. With my refactorings, this was made clean and consistent. 

So fixing it in smoke tests.

**Comment by roblourens** [comment]
> It seems Search view is behaving differently when opening from Activity Bar and from other places. In former, Replace input is shown where as latter does not. With my refactorings, this was made clean and consistent.

Huh? I don't see that

**Comment by roblourens** [comment]
I do see it expanding replace with code in a clean user-data-dir though

**Comment by roblourens** [comment]
Actually, it has been like that (for clicking the search icon in a new window in a clear user data dir) for years. 

Here's my best explanation which is really just for myself or future reference
- We always restore the persisted state, but default to showing it
- Previously in a new user data dir, pressing cmd+shift+f  would hit the "find in files" command which does not show replace (there is a matching command "replace in files")
- Now pressing it with the search viewlet hidden will run `workbench.view.search`, so it will show replace by default on the first run when no other state has been persisted (smoketest hits this case)
- Pressing it again with the viewlet visible will run "find in files" and hide replace

Still feels weird and we should revisit these search actions, but tl;dr, it's ok for now and the smoke test fix is fine.
