### ISSUE TITLE
Creating a new file or folder - file/folder name input field loses focus randomly

### ISSUE THREAD

**Issue by Ahmed-Ghiloubi** [microsoft/vscode#115500]
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Open VS Code 
2. Attempting to create a new file or folder
3. Input field loses focus

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in 1.53 which is expected to release this week.
