### ISSUE TITLE
Cannot connect to the Extensions

### ISSUE THREAD

**Issue by zakky-sy** [microsoft/vscode#115583]
I can't access the extension, and an error message appears ("We cannot connect to the Extensions Marketplace at this time, please try again later"). And I have tried completely uninstalling and reinstalling it several times. The internet network that I use is smooth there are no problems and also have switched networks if maybe the problem is on the internet network that I use. But I still can't access the extension.

VS Code version: Code 1.52.1

**Comment by joaomoreno** [comment]
Are you in a corporate network? Behind a proxy? A VPN?

**Comment by zakky-sy** [comment]
> Are you in a corporate network? Behind a proxy? A VPN?

No, I'm not in a corporate network, and I'm not using VPN or behind a proxy

**Comment by deepak1556** [comment]
Do you see the issue with our insiders version https://code.visualstudio.com/insiders ?
