### ISSUE TITLE
Select for Compare missing for unsaved files

### ISSUE THREAD

**Issue by willxinc** [microsoft/vscode#115580]
Issue Type: <b>Bug</b>

Create 2 new files and fill them with text, and don't save them, then try to select for compare.

This is likely due to #113703

VS Code version: Code - Insiders 1.53.0-insider (861a88ebadb4335df92251faf6420b598440e082, 2021-01-29T21:49:22.151Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Does the issue exist in Stable (1.52.1)? If not then it should probably be tagged as a regression and maybe a candidate.

**Comment by isidorn** [comment]
I caused this with the `IsFileSystemResource` context key
fyi @bpasero

**Comment by bpasero** [comment]
@isidorn oh yeah, d'oh. I suggest to revert and then we can look into a better fix.

**Comment by isidorn** [comment]
Fixed via revert 2fb57aa3b6
@bpasero can you please review https://github.com/microsoft/vscode/pull/115611

**Comment by isidorn** [comment]
Merged.
@bpasero Thanks for the review. I will ping you tomorrow to verify once the build is out
