### ISSUE TITLE
Swiggle lines not shown and Problems pane not working

### ISSUE THREAD

**Issue by gokva** [microsoft/vscode#115527]
I have problem with my editor where i dont see any swiggle lines and my problems pane in integrated terminal is always empty with below message. 
![image](https://user-images.githubusercontent.com/50981922/106447146-19897480-64bc-11eb-974d-33cf803095d0.png)

VSCode version 1.52
Below is my settings file. 
```
{
    "python.linting.pylintArgs": [
        "--init-hook",
        "import sys; sys.path.append('${workspaceFolder}')",
        "--disable=C0103",
        "--disable=logging-fstring-interpolation",
        "--disable=fixme"
    ],
    "python.testing.pytestArgs": [
        "tests",
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.nosetestsEnabled": false,
    "python.testing.pytestEnabled": true,
    "python.formatting.provider": "black",
    "python.linting.pylintEnabled": true,
    "python.linting.enabled": true,  
    "python.linting.flake8Enabled": false,    
}
```
I tried uninstalling the editor and reinstalling... it didnt help. How to enable the swiggle lines in editor?

**Comment by sandy081** [comment]
Please file an issue against the extension which shall create diagnostics so that you can see them in the editor.
