### ISSUE TITLE
[snippets] How to get current Filename, LineNumber from Snippet

### ISSUE THREAD

**Issue by 1-9** [Microsoft/vscode#11555]
- VSCode Version: 1.4.0
- OS Version: OS X EL Capitan

How can I get filename and line number to insert into a snippet?

**Comment by aeschli** [comment]
We currently don't have support for that.

**Comment by careuno** [comment]
It would be great if you enable the possibility to get the filename (name of the class) and path (for name of namespace), I'm trying to generate C# class skeleton like Visual Studio.
Thank you

**Comment by jrieken** [comment]
closing as duplicate of #13047
