### ISSUE TITLE
JS Syntax highlighting breaks when creating new objects without parenthesis

### ISSUE THREAD

**Issue by achshar** [Microsoft/vscode#11551]
- VSCode Version: 1.4
- OS Version: Win 10

Steps to Reproduce:

![untitled](https://cloud.githubusercontent.com/assets/3441158/18254579/c2a55156-73bc-11e6-8e1d-db619cafd466.png)

It only happens if there's a closing parenthesis right after the class name.

so `var a = new Date;` is fine but `var a = (new Date);` is not. The function baz doesn't show it's green color. Not sure if this is a VS code issue or if there's some other repo for just language specific syntax highlighting.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#255
