### ISSUE TITLE
Promise.all() does not await all promises when one throws

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115522]
This came to my surprise, but `Promise.all` will actually not `await` all promises you give it if anyone is rejected.

Proof:

```js
const testNativePromise = function () {
    return Promise.all([
        nativePromise(10, true),
        nativePromise(20, false).then(() => console.log("Executed succeeding promise")),
        nativePromise(30, true)
    ]).then(() => console.log("DONE: SUCCESS"), error => console.log("DONE: ERROR"));

    function nativePromise(delay, fail) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (fail) {
                    reject(new Error("fail: " + delay));
                } else {
                    resolve({ delay });
                }
            }, delay);
        });
    }
}

testNativePromise().finally(() => {
    console.log("EXIT");
    // !!! at this point the second promise is still running !!!
});
```

If you run this the output will be:

```
DONE: ERROR
EXIT
Executed succeeding promise
```

Example where this could end up bad:
* we have many places where you can `join` events with `Promise` and where we await all those that join, we would leave dangling joiners and return early if any throws an error
* we have some places where we do multiple independent tasks in a `Promise.all` (e.g. saving multiple editors) and the `save` method would return early while saves are still running if one throws an error

There is a new [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) coming that helps for this case, but we cannot use it yet. I have pushed 2 utility functions to help:
* [`Promises.allSettled`](https://github.com/microsoft/vscode/blob/0ca20779b5b4d7903f2020d98e53d97e53b335db/src/vs/base/common/async.ts#L1093-L1093): this is a shim for the official version that is coming in ES2021
* [`Promises.settled`](https://github.com/microsoft/vscode/blob/0ca20779b5b4d7903f2020d98e53d97e53b335db/src/vs/base/common/async.ts#L1112-L1112): this behaves like `Promise.all` (will throw the first error it encounters from any of the promises) but only return when all promises are either resolved or rejected

**Comment by bpasero** [comment]
I did a quick scan over our code and have identified a few logical areas where there is a lot of `Promise.all` that should get a review:
* [ ] extension management / gallery / scanning @sandy081 
* [ ] settings sync @sandy081 
* [ ] configuration @sandy081 

Found some in the area of debug too @isidorn but not sure how critical. 

Watch out for `Promise.all` where promises can have a side effect: for example, when you uninstall multiple extensions as a cleanup task and task is expected to finish consistently (either with error or without), then I would suggest to switch to `Promises.settled` to ensure that all succeeding promises had a chance to finish.

**Comment by sandy081** [comment]
@bpasero ✅

**Comment by bpasero** [comment]
Thanks, closing this issue then.

**Comment by isidorn** [comment]
Thanks for the ping, in debug land I would not make any changes atm. But will keep this in mind in case some funkiness happens
