### ISSUE TITLE
node.js: Debug console always displays some internal line number for every console.log message.

### ISSUE THREAD

**Issue by mplwork** [microsoft/vscode#115552]
- VSCode Version: 1.52.1
- OS Version: Windows 10 Enterprise 1909

As my issue #115408 was just closed and my problem apparently not understood I try again: 

Steps to Reproduce:

1. Create a file, say `index.js`
2. place a statement there like `console.log('%s listening to %s', server.name, server.url); `
3. hit F5

What I get:

```
C:\Program Files\nodejs\node.exe .\index.js
restify listening to http://[::]:3978      node_modules/diagnostic-channel-publishers/dist/src/console.pub.js
```

What I want:

```
C:\Program Files\nodejs\node.exe .\index.js
restify listening to http://[::]:3978      .\index.js:42
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Please share a reproducable case (code sample or repository is good). I'm not able to repro this with a test program like

```js
const server = { name: 'test', url: 'test' };
console.log('%s listening to %s', server.name, server.url);
```

If you're able to get a repro, please post it on the original issue. Thanks!

/duplicate https://github.com/microsoft/vscode/issues/115552

**Comment by mplwork** [comment]
> 
> 
> Please share a reproducable case (code sample or repository is good). I'm not able to repro this with a test program like
> 
> ```js
> const server = { name: 'test', url: 'test' };
> console.log('%s listening to %s', server.name, server.url);
> ```

I can't come up with a reproducible case either. Simple things like this produce correct line numbers. Looks to me that this https://github.com/microsoft/node-diagnostic-channel module is messing up the reported location. But I haven't traced which module imports `node-diagnostic-channel`. I certainly don't.

> 
> I'm also not clear whether the proposed solution worked for you or not, or what you tried.

No, I couldn't get it to work.

> 
> If you're able to get a repro, please post it on the original issue to keep issues concise and readable. Thanks!
> 
> /duplicate #115552

#

**Comment by connor4312** [comment]
> No, I couldn't get it to work.

Can you share what you tried? It should look something like `"skipFiles": ["**/node_modules/node-diagnostic-channel/**"]`

**Comment by mplwork** [comment]
> "skipFiles": ["**/node_modules/node-diagnostic-channel/**"]

This is my launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            //"type": "node",
            "request": "launch",
            "name": "Launch Program",
            "env": {
                "HTTPS_PROXY": null
            },
            "program": "${workspaceFolder}\\index.js",

            "type": "pwa-node",
            "resolveSourceMapLocations": [
                "${workspaceFolder}/**",
                "!**/node_modules/**"
            ],
           "skipFiles": ["**/node_modules/node-diagnostic-channel/**",
                "**/node_modules/diagnostic-channel-publishers/**" ]
        }
    ]
 }
```

However, I found the culprit in the meantime: It is the `applicationinsights` required by `botbuilder-applicationinsights`
