### ISSUE TITLE
Another instance of Code is running but not responding

### ISSUE THREAD

**Issue by rarevalo13** [microsoft/vscode#115563]
- VSCode Version:
- Version 1.52.1 (1.52.1)
- OS Version:
- macOS 10.15.7

Steps to Reproduce:

1. Trying to open a new instance, this has. happened before, this is a fresh install. I've seen this issue before, usually resolved by restarting my computer, but that is not always an option. 
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by isidorn** [comment]
Please file a new issue with proper steps https://github.com/microsoft/vscode-wiki/blob/master/Performance-Issues.md
