### ISSUE TITLE
Forzon

### ISSUE THREAD

**Issue by ksyp-7** [microsoft/vscode#115545]
We have written the needed data into your clipboard because it was too large to send. Please paste.i am facing problem with vs code. while i am coding on vs code after every 10-15 minites its froze.it take much time to reopen.when even other editors runs smuthly

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version, platform, extensions, does this happen if you launch/reload with all extensions disabled. Also see the wiki section about performance problems.
