### ISSUE TITLE
AUTOCOMPLETE

### ISSUE THREAD

**Issue by Mohad-code** [microsoft/vscode#115517]
Issue Type: <b>Bug</b>

hello guys i am using this program more time so there is one problem that is 

autocomplte or intellisense not working i do everthing to fix the problem but nothing be good

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
What language?
