### ISSUE TITLE
Full Black VS Code windown

### ISSUE THREAD

**Issue by rkumargit** [microsoft/vscode#115561]
- VSCode Version:x64 -1.52.1
- OS Version: Windows 8

Steps to Reproduce:
Whenever I start the VS Code, a full black screen window open. I'm not able to see any option on the VS Code window. It is strange that by guessing where the minimize, maximize and close buttons are I'm able to perform these actions.

Does this issue occur when all extensions are disabled?: Yes
![Capture](https://user-images.githubusercontent.com/41901207/106505000-b57fa400-64ed-11eb-854b-5cea5f636728.PNG)

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible if you launch VS Code with HWA disabled like `code --disable-gpu`?
Could you please try Insiders build (https://code.visualstudio.com/insiders/) and check if this issue is reproducible there?

**Comment by bpasero** [comment]
Looks a lot like https://github.com/microsoft/vscode/issues/114459, I suggest to merge the discussion into there.

**Comment by rkumargit** [comment]
> /needsMoreInfo
> 
> Is it reproducible if you launch VS Code with HWA disabled like `code --disable-gpu`?
yes, it is reproducible even with `code --disable-gpu`
> Could you please try Insiders build (https://code.visualstudio.com/insiders/) and check if this issue is reproducible there?
I have tried this with both stable and insiders and faced the same issue. No matter how many times reinstall and tried to open using shotcut or cmd it always have full black window. As I mentioned controls are there but it is not visible.
