### ISSUE TITLE
vs code does not show git command output

### ISSUE THREAD

**Issue by vision10** [microsoft/vscode#115542]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. In vs code 'Source Control' panel, click on 'pull' command

Does this issue occur when all extensions are disabled?: Yes

vs code does not print output  from git command (pull) in output view

> git pull --tags origin master
From https://...visualstudio.com/...
 * branch            master     -> FETCH_HEAD
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template

**Comment by eamodio** [comment]
@vision10 what is the issue here? We don't log the output of most git commands.

**Comment by vision10** [comment]
It would be very helpful if you could show git commands output and I could see if my repository is up to date or what files where changed.
