### ISSUE TITLE
Empty untitled file should not show up as dirty

### ISSUE THREAD

**Issue by leo90skk** [Microsoft/vscode#11554]
- VSCode Version: 1.4
- OS Version: ubuntu 16.04 LTS

Steps to Reproduce:

1. create empty file
2. write something
3. delete the content
4. try to close
5. you will be asked:

> Do you want to save the changes you made to Untitled-1?

Why that question? ... the content is empty and a file does still not exist.

**Comment by jaseonline** [comment]
@leo90skk I'd like to fix this. This disrupts my workflow and is becoming very tedious.

**Comment by bpasero** [comment]
Yes, we should fix this.

**Comment by bpasero** [comment]
Verify: once you make an untitled buffer empty, it is not dirty anymore.
