### ISSUE TITLE
Cannot place a Bookmark on a line

### ISSUE THREAD

**Issue by jaseonline** [Microsoft/vscode#11559]
- VSCode Version: 1.5.0
- OS Version: Windows 10 (Windows_NT 10.0.10586)

Steps to Reproduce: Cannot reproduce a non-existent feature.

Ideally, I need to be able to bookmark [a] line(s) of code. I find this feature allows me to work more efficiently in other editors, so I don't see why it shouldn't exist in Code.

**Comment by dbaeumer** [comment]
@jaseonline this kind of feature is provided by extensions. Go to the extensions viewlet and type bookmark to see the two available once.
