### ISSUE TITLE
Mouse cursor activates items to the left of it

### ISSUE THREAD

**Issue by pantsmann** [microsoft/vscode#115575]
Issue Type: <b>Bug</b>

Sometimes the mouse cursor activates to the right of where is appears. For example, to highlight 'times' in the previous sentence I would have to click and hold over the first 'e' in 'Sometimes' and drag to the last 'e' in 'Sometimes'. It affects all components in the window (e.g. the gutter arrows for collapsing code  activate when clicking to their left , same with icons  in the Explorer side bar, resizing editors, or anything else I try. I have no idea why this starts happening or what steps to reproduce it. Restarting VS Code does tend to fix it, but resizing, maximizing, or minimizing the app does nothing.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (0.89GB free)|
|Process Argv|--crash-reporter-id a9e2ca89-e48e-4712-9201-25c1f9d16fe0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|12.39GB (10.03GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
git-diff-and-merge-tool|dav|1.0.4
xml|Dot|2.5.1
gitlens|eam|11.1.3
go|gol|0.22.0
todo-tree|Gru|0.0.196
vscode-docker|ms-|1.9.1
vscode-yaml|red|0.14.0
code-spell-checker|str|1.10.2
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30250196
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce this

**Comment by pantsmann** [comment]
I have no idea how to reproduce it. I don't know what triggers it. It seems
to take time; not happening every day, but happening a few times a week.
The only thing I'm aware of changing on my machine before this started was
an update of VS code. But this issue didn't show up for at least a day or
two after that. I can try insiders and see if it continues to happen. I
just haven't seen any pattern that sets it off.

**Comment by isidorn** [comment]
Once you have reproucable steps let us know and we can reopen
