### ISSUE TITLE
Publish reference-viewlet as a public package

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode#115515]
It would be very great if the reference-viewlet extension could be published to npm. It brings the extension developers who want to use the reference-viewlet API a lot of convenience in case the API version changes.

**Comment by jrieken** [comment]
> It would be very great if the reference-viewlet extension could be published to npm.

I don't understand... It is an extension that ships (and needs) VS Code. How can it be on npm?

**Comment by jrieken** [comment]
You should be using `extensionDependencies` for that

**Comment by CsCherrYY** [comment]
> You should be using `extensionDependencies` for that

Thanks for the suggestion but actually I have done that :smile:. My concern is about the API shape. Currently I put the `references-view.d.ts` into my extension's source folder so that I can get the API shape. Since `extensionDependencies` doesn't support restricting version, is there any efficient way to keep consistent between my API definition file and the API get from `ms-vscode.references-view` in case the version changes?

**Comment by jrieken** [comment]
> My concern is about the API shape. 

We will not break that API
