### ISSUE TITLE
workspaceFolderBasename variable is not resolving immediately after window load

### ISSUE THREAD

**Issue by geneing** [microsoft/vscode#115560]
Issue Type: <b>Bug</b>

In order to avoid multiple remote tmux sessions, I set in settings.json the following 
 "terminal.integrated.shell.linux": "/usr/bin/tmux",
    "terminal.integrated.shellArgs.linux": [
        "new-session",
        "-A",
        "-s",
        "${workspaceFolderBasename}"
    ],

I expect that workspaceFolderBasename variable contains valid value. However, initally or after window reload this variable is not set. It is only set correctly after I switch source code tabs or open a file. 

This is a problem when using remote sessions, because this happens  every time I reconnect to the remote session and VSCode tells me to reload window. 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-45-generic
Remote OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.78GB free)|
|Process Argv|--crash-reporter-id 43e1efde-3d38-401f-a9f5-1b22f067980f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: elephant.itw|
|OS|Linux x64 4.15.0-45-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 3051)|
|Memory (System)|62.87GB (28.44GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: elephant.itw|
|OS|Linux x64 4.15.0-45-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 3051)|
|Memory (System)|62.87GB (28.44GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.52.0
githistory|don|0.6.14
gitlens|eam|11.1.3
vscoq|max|0.3.2
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.1.3
jupyter|ms-|2020.12.414227025
cmake-tools|ms-|1.5.3
cpptools|ms-|1.1.3
biosyntax|rea|0.0.9
vscodeintellicode|Vis|1.2.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Just-Insane** [comment]
Were you able to find a solution for this? I have this in settings.json:

```json
"terminal.integrated.profiles.osx": {
  "tmux ws-session": {
    "path": "tmux",
    "args": [
      "new-session",
      "-A",
      "-s",
      "vscode-${workspaceFolderBasename}"
    ]
  },
}
```

and the "osx" version works correctly locally (it's identitcal), but whenever I use Remote-SSH my tmux session is named "vscode-${workspaceFolderBasename}", even after killing all terminal sessions, opening a remote file, and then re-opening tmux.

**Comment by zix99** [comment]
This is impacting me too, but I was able to come up with this work-around (but it isn't pretty...)

In your remote config, replace the other config with this line (Replace path as appropriate):

```json
{
  "terminal.integrated.shell.linux": "/path/to/home/bin/code-tmux"
}
```

And `code-tmux` should look like this:
```bash
#!/bin/bash
exec tmux new-session -A -s vscode-$(basename $PWD)
```

Hope it helps for now until config variables work again here.

**Comment by lukebennett** [comment]
@zix99 works a treat, nice one!

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/126066

**Comment by diegohavenstein** [comment]
In my case it is not resolving at all, not even after reload. Tried it on the current vs code and with the insiders edition, running on Mac OS. Tried using it within user setting and within workspace setting, as part of the clangd configuration

**Comment by xgdgsc** [comment]
When I work with julia extension with tmux persistent mode. It's really weird on start REPL the `workspaceFolderBasename` resolves correctly while after use for sometime, on trying to stop REPL  the `workspaceFolderBasename` resolves to empty.
