### ISSUE TITLE
Improve Error Dialog when an extension requires an UI extension host and fails to install

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#115590]
Installing an extension with the `extensionKind` set to `["ui']` results in the following error dialog when there is no UI extension host available:

![image](https://user-images.githubusercontent.com/172399/106570959-e932ec00-6536-11eb-81ce-e1a0bef4898c.png)

The current dialog is a bit scary and it is not clear to the user that this is the expected behaviour. I therefore suggest the following changes:
- change the dialog to an informational dialog, nothing has gone wrong and everything is as expected.
- change the wording accordingly "The 'Settings Sync' extension does not run in this setup and therefore it cannot be installed. The extension has declared that it must run locally."    --- I have tried to avoid the term remote server

**Comment by sandy081** [comment]
@egamma 

Regarding message, I am not sure if term `locally` is helpful as web extensions can be installed locally (in browser). So I would propose following

<img width="550" alt="image" src="https://user-images.githubusercontent.com/10746682/106617700-274c0200-656f-11eb-932d-55ee31867caa.png">

**Comment by sandy081** [comment]
Finalized on following message:

`Cannot install the 'Settings Sync' extension because it is declared to not run in this setup.`
