### ISSUE TITLE
Attempts to copy text intermittently triggers Go to definition

### ISSUE THREAD

**Issue by albgus** [microsoft/vscode#115543]
- VSCode Version: 1.52.1
- OS Version: macOS 11.1

I have an issue that has started to become more and more annoying in VS Code. Sometimes when selecting something which has support for "Go to Definition" and attempting to copy the text with Ctrl+C, Visual studio will open a new web browser with the definition link. This is despite there not being any keyboard shortcuts registered for Go to definition.

This is _NOT_ triggered by pressing Ctrl and the mouse button at the same time. I have been able to recreate this even when waiting more than one second after selecting the text. It's also intermittent in that it will not always open the definition, but it seems that it will almost always trigger after switching open files (tabs) or refocusing Code. It seems to happen less if the same file has been open for a while (although repeatedly pressing Ctrl will consistently trigger the issue). 

A possible thing that could cause issues is that I have swapped Ctrl and Cmd in the macOS settings, but I have checked and cannot find any matching mappings for either of the keys.. and it doesn't explain why it can be triggered by spamming Ctrl.

Steps to Reproduce:

1. Switch file in Visual Studio Code
2. Select any snipped which have any support for "Go to Definition"
3. Press Ctrl (or cmd), if needed spam the button a bit.
4. VS Code proceeds to throw you away to a browser page.

Does this issue occur when all extensions are disabled?: No, but that disables "Go to Definition" entierly...

**Comment by alexdima** [comment]
@albgus What programming language are you using? What extensions do you have installed? (Extensions can trigger programmatically "Go to Definition").

**Comment by albgus** [comment]
I've only noticed this problem with Terraform, although I think that may be the only plugin I'm actively using with Go to definition support.

Is there any way to enable debug logging / find out if this is caused by some plugin?

**Comment by albgus** [comment]
This behaviour seems to have gone away now and the only thing I have changed is activating "Switch to Alt+Click for Multi-Cursor" from the Selection menu. Not sure why this would have had any impact so it might still be a bug, but at least I have a workaround that doesn't seem to have any downsides now.

**Comment by alexdima** [comment]
The menu item "Switch to Ctrl|Alt+Click for Multi-Cursor" changes the gesture to trigger go to definition. It is either bound to alt+click or to ctrl+click.
