### ISSUE TITLE
EOS not formatting properly in shell scripts

### ISSUE THREAD

**Issue by srideep3** [microsoft/vscode#115691]
- VSCode Version: 1.51.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file
2. Change the file type to shell script
3. Add the following line to reproduce the issue:
`test=`\``abc <<EOS`
`123
EOS`\`
`echo "Formatting issue starts from this line"`

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you please also provide screen shots of the issue?

**Comment by srideep3** [comment]
PFA
![VSCode](https://user-images.githubusercontent.com/39752835/106962120-9874ec00-670c-11eb-8b22-36cb0cf8ad16.jpg)

**Comment by srideep3** [comment]
PFA
![VSCode](https://user-images.githubusercontent.com/39752835/106962262-db36c400-670c-11eb-9abc-8090c7ca6312.jpg)

**Comment by alexr00** [comment]
We get our shell script syntax highlighting grammar from https://github.com/atom/language-shellscript/. Duplicate of https://github.com/atom/language-shellscript/issues/158
