### ISSUE TITLE
Completed installing extension from VSIX notification never times out

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115690]
Extension notifications eventually collapse into the tray by themselves, I think this one in particular should also do this in core because it's just an unactionable status message:

![image](https://user-images.githubusercontent.com/2193314/106747976-7169cd80-65d9-11eb-9101-ed981200a41c.png)

@bpasero maybe we should just do this for all info notifications in core?

**Comment by bpasero** [comment]
Well, someone explicitly made this notification sticky:

https://github.com/microsoft/vscode/blob/7690293ae208f91f4e3612e309ac130a85244486/src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts#L681-L681

**Comment by Tyriar** [comment]
@bpasero ah ok, I wasn't sure how this worked.
