### ISSUE TITLE
Outdent-line ("command + [") does not respond in Visual StudioCode on m1 mac.

### ISSUE THREAD

**Issue by 108works** [microsoft/vscode#115651]
Issue Type: <b>Bug</b>

Outdent-line ("command + [") does not respond in Visual StudioCode on m1 mac.

It has been confirmed that the shortcut is registered. Recoding Keys didn't detect it only when I pressed these two keys.

Completion of this key works on other code editor and Google Chrome.

VS Code version: Code - Insiders 1.53.0-insider (8d779a4fadaadec06b44b8875a1d3c4adba8e380, 2021-02-02T16:34:06.213Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id ad5aa5e3-8f95-41bd-8db1-70ba10843493|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|12.1.4
vscode-sqlite|ale|0.11.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
python-preview|don|0.0.4
gitlens|eam|11.2.1
prettier-vscode|esb|5.8.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
vscode-nginx-conf-hint|han|0.1.0
vscode-drawio|hed|1.2.0
autofilename|Jer|0.1.3
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.9.1
vscode-language-pack-ja|MS-|1.53.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vetur|oct|0.32.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.5.0
nginx-formatter|ray|0.0.11
ruby|reb|0.28.1
java|red|0.74.0
format-html-in-php|rif|1.7.0
vue-vscode-extensionpack|sdr|0.2.0
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
vscode-nginx|wil|0.7.2
nuxt-typescript-snippets|wil|0.1.3
vscode-ruby|win|0.28.0
vscode-jumpy|wma|0.3.1
wordpress-toolbox|wor|1.3.9
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by PabloLema** [comment]
I have the same bug for all shorcuts using [

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled, using the command palette?

**Comment by 108works** [comment]
@gjsjohnmurray 
Yes. The situation does not change if you start with all extensions disabled.

**Comment by 108works** [comment]
I have confirmed that it works, so I will close it.

**Comment by satoshiyamamoto** [comment]
@108works Hi, I have the same problem and I haven't been able to solve it yet.
If you don't mind, can you tell me how it was resolved?

**Comment by 108works** [comment]
@satoshiyamamoto 
Hi, I haven't done anything special other than update

**Comment by 108works** [comment]
> @108works Hi, I have the same problem and I haven't been able to solve it yet.
> If you don't mind, can you tell me how it was resolved?

@satoshiyamamoto
Hi, I haven't done anything special other than update

**Comment by satoshiyamamoto** [comment]
@108works Thank you for your comment. 
I have updated to the latest version, but it still seems that VSCode is not receiving `cmd+[`. 
Unfortunately, this may be a problem only in my environment.

```[2021-07-08 13:46:44.093] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
[2021-07-08 13:46:44.095] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2021-07-08 13:46:44.095] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-07-08 13:46:44.114] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 91, key: Meta
[2021-07-08 13:46:44.114] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift,meta], code: MetaLeft, keyCode: 57 ('Meta')
[2021-07-08 13:46:44.115] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-07-08 13:46:44.895] [renderer1] [info] [KeybindingService]: + Storing single modifier for possible chord meta.
[2021-07-08 13:46:45.196] [renderer1] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

**Comment by ryu0121** [comment]
@satoshiyamamoto 
Hi, I also have the same issue in my environment.
I  can still not use `cmd+[`.
But, There is no clue for resolving it...

**Comment by satoshiyamamoto** [comment]
@ryu0121 

That's right, the US keyboard did not work with either the built-in keyboard or the Bluetooth keyboard.
By the way, the Japanese keyboard seems to be sending a different key code than "[" and works fine.

This problem has not happened with other Electron applications...

**Comment by Stirfry70** [comment]
When was this ?
