### ISSUE TITLE
VSCode forgets last session when reopening through an associated file extension

### ISSUE THREAD

**Issue by stderr-to-devnull** [microsoft/vscode#115602]
- VSCode Version: 1.51.1
- OS Version: Pop OS 20.10

Steps to Reproduce:

1. Close VSCode
2. Open a file associated with VSCode instead of normally opening VSCode
3. The file will open in a brand new session instead of being added as a new tab to last session; the last session is completely lost, everything opened is gone

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
https://code.visualstudio.com/updates/v1_52#_restore-previous-session-windows

**Comment by stderr-to-devnull** [comment]
I think that option should be enabled by default as this is the generally expected behavior.
