### ISSUE TITLE
Can't start vscode since 1.49 version

### ISSUE THREAD

**Issue by jeremy-peng** [microsoft/vscode#115663]
- VSCode Version: 1.49 or higher
- OS Version: Red Hat Enterprise Linux Server release 7.4 (Maipo)

Steps to Reproduce:

1. download new version the linux tar package (1.49, 1.5x ), extract it
2. start vscode with 'code'
3. vscode start but it's whole empty, wait 10+ mintue still the same
4. use previous 1.48 version, vscode start normally 

![image](https://user-images.githubusercontent.com/6103154/106706303-7145ee00-662a-11eb-9640-cdb3aa57a974.png)

Does this issue occur when all extensions are disabled?: No

**Comment by joaomoreno** [comment]
Can you run it from the command line?

```
code --verbose
```

**Comment by jeremy-peng** [comment]
Hi joaomoreno,

I update the log start with --verbose, please check.

[vscode.log](https://github.com/microsoft/vscode/files/5919210/vscode.log)

**Comment by joaomoreno** [comment]
@jeremy-peng From your screenshot, it looks like a Windows UI. Which OS are you on?

**Comment by jeremy-peng** [comment]
> @jeremy-peng From your screenshot, it looks like a Windows UI. Which OS are you on?

i am using Linux, centos7.4

**Comment by jeremy-peng** [comment]
it may related to the Eod (Exceed onDemand Client), I use this to connect to my remote linux server, and it will has this issue.

But if I use VDI, then won't has this issue.

**Comment by joaomoreno** [comment]
Do other Electron apps also have that problem? Eg Slack.
