### ISSUE TITLE
vscode style error

### ISSUE THREAD

**Issue by CarlosLiujin** [microsoft/vscode#115656]
vsocde get style error when I use vscode.it looks like a html without any style,it has scroll ,ugly input
![微信图片_20210203124231](https://user-images.githubusercontent.com/43985778/106699191-5c169280-661d-11eb-9a39-e66f9517bb52.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Does the problem also happen if you launch with all extensions disabled? 

`code --disable-extensions `

**Comment by CarlosLiujin** [comment]
> /needsMoreInfo
> 
> Does the problem also happen if you launch with all extensions disabled?
> 
> `code --disable-extensions `

I am not sure you have seen my picture.I can't do anything when I enter voscode because it's style get error.the error always  in there also I restart

**Comment by CarlosLiujin** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

I think my problem is very clear . I don't what basic infomation you need.This is vscode's bug,right?

**Comment by gjsjohnmurray** [comment]
I gave you the command to launch VS Code from your command prompt but with all extensions disabled.

You haven't told us your version or platform. 

Did the problem suddenly start happening? Or is this a new install?

**Comment by CarlosLiujin** [comment]
> I gave you the command to launch VS Code from your command prompt but with all extensions disabled.
> 
> You haven't told us your version or platform.
> 
> Did the problem suddenly start happening? Or is this a new install?

OK,vscode 1.52.1,window 10.
The problem has exist when I restart but get resolved when I new install.I am not sure I can resolve it if this problem reappear next time.Unfortunately,I have no idea.
& thanks your command but I can't select or focus any function when problem exist.So I can't launch with all extensions disabled.

**Comment by gjsjohnmurray** [comment]
> So I can't launch with all extensions disabled.
😕 
You don't have to interact with VS Code in order to launch with all extensions disabled. Don't start VS Code from its icon or from the Windows Start menu. Instead, start a Command Prompt. Then run the command I gave you.
