### ISSUE TITLE
HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait. Freezed.

### ISSUE THREAD

**Issue by msaiyaff** [Microsoft/vscode#11563]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10240

I think it's an issue with the extension HTML CSS Class Completion. When i uninstall the extension issue has solved. But, is there a solution for that while the extension is added.

When i open html File in my project vscode get freezed with below command shown.
"HTML CSS Class Completion: Fetching CSS rules from CSS files, please wait."

**Comment by dbaeumer** [comment]
@msaiyaff you need to report the problem to owner of the extension. There is little VS Code can do to make the extension work.

I will close the issue. Please ping if there is anything you think VS Code can do to solve this.
