### ISSUE TITLE
monarchCompile function need an extra option which can control replacement

### ISSUE THREAD

**Issue by MeetzhDing** [microsoft/vscode#115662]
https://github.com/microsoft/vscode/blob/5cc0aa284968c66b0075ac3b89a70c2edb10b891/src/vs/editor/standalone/common/monarch/monarchCompile.ts#L87

In the function compileRegExp, RegStr which contains the '@'  will be replaced to lexer[attr].  It's great feature can simplify regular expressions, but when my custom language want to highlight the /@sth/ statement, i will get error from line 97, and which cause page crash in the page using monaco and react.

I try to define @key in langDef, but the loop statement will replace the value of @key。
```ts
    let langDef = {
      ignoreCase: false,
      tokenizer: {
        root: [
          {
            regex: new RegExp(`^${props.beginRegexTokenizer}$`),
            action: 'beginRegex',
          },
        ],
      },
    }
    for (const atKeyMatch of props.beginRegexTokenizer?.matchAll(/\\?@(\w+)/g) || []) {
      const atKey = atKeyMatch[1]
      if (!(atKey in langDef)) {
        langDef[atKey] = `@${atKey}`
      }
    }
   monaco.languages.setMonarchTokensProvider('logSample', langDef)
```

Even though I can add @sth to the langDef to deal with 5 times replacement, but it sounds unreasonable. and when using RegExp '\\@sth', '\\' may cause error in RegExp constructor

Overall , Can we add an option which control the replacement ?

**Comment by MeetzhDing** [comment]
```ts
    let languageDef = {
      ignoreCase: false,
      uselessReplaceKey1: '@uselessReplaceKey2',
      uselessReplaceKey2: '@uselessReplaceKey3',
      uselessReplaceKey3: '@uselessReplaceKey4',
      uselessReplaceKey4: '@uselessReplaceKey5',
      uselessReplaceKey5: props.beginRegexTokenizer || '',
      tokenizer: {
        root: [
          {
            regex: /@\w+/.test(props.beginRegexTokenizer)
              ? new RegExp(`^${'@uselessReplaceKey1'}$`)
              : new RegExp(`^${props.beginRegexTokenizer || ''}$`),
            action: 'beginRegex',
          },
        ],
      },
    }
    monaco.languages.setMonarchTokensProvider('logSample', languageDef)
```
Temporary solution

**Comment by JacksonKearl** [comment]
Verified in the monaco playground with:
```ts
return {
  hams: ['pork'],
  ham: /ham/,
  tokenizer: {
    root: [
      [/@@ham/, 'invalid'],
      [/@ham/, 'comment'],
      [/[a-z_$][\w$]*/, { cases: { '@hams': 'keyword',
                                   'sausage': 'type',
                                   '@@bacon': 'annotation',
                                 } }],
    ]
  },
};
```
![image](https://user-images.githubusercontent.com/8586769/109370411-08cae500-7855-11eb-8c70-cfb546415a60.png)

Noticed that the doubly escaped `@` in a case key position does not work consistently with the top level regex ones, is this expected?
