### ISSUE TITLE
'build errors exist' dialog causes gnome ui to hang.

### ISSUE THREAD

**Issue by bsutton** [microsoft/vscode#115652]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.8.0-41-generic snap

Steps to Reproduce:

1. using the dart-code extension edit a dart unit test file leaving a compile error. ( I believe the problem occurs for any dart launch).
2. Try to launch the test using the 'in editor' debug option that appears just above the 'test' method.
3. vs code displays dialog box. Title: Visual Studio Code, Message: Build errors exist in your project. With three buttons, Show Errors, Cancel Debug Anyway
4. The gnome ui hangs. (Although I was able to take a screen shot using print scrn). 

I'm able to recover the session by switching to a terminal (ctrl-alt-f6) and run 'killall code'
I can then return to the gnome session (I have to log back into the session) and the session is still running and is responsive.
I can then restart vscode and resume work.

This error occurs EVERY time I attempt to run a debug session when there are outstanding compile errors.

 

Does this issue occur when all extensions are disabled?: Yes/No

- given I can't compile with vs-code disabled disabling extensions doesn't help.
I did however disable all extensions except for vs-code and I was still able to reproduce the problem.

Screen shot attached.
![Screenshot from 2021-02-03 13-13-42](https://user-images.githubusercontent.com/900408/106689195-a733a400-6623-11eb-88cd-ff166bc7ec73.png)

**Comment by zmunk** [comment]
I have the same issue.

**Comment by deepak1556** [comment]
Do you experience the issue with latest stable `1.53.2` ?

If so, can you provide repro steps with minimal dart script. Thanks!

**Comment by bsutton** [comment]
I've just done a trivial test using 1.53.2 and the problem didn't occur.

I will do some more testing today.

**Comment by bsutton** [comment]
Just using 1.53.2 and the problem occurred again.

So still an issue. Maybe less frequently?

**Comment by deepak1556** [comment]
Can you provide the output of `code --status` and also if possible a minimal workspace that triggers this.

**Comment by bsutton** [comment]
(electron) Sending uncompressed crash reports is deprecated and will be
removed in a future version of Electron. Set { compress: true } to opt-in
to the new behavior. Crash reports will be uploaded gzipped, which most
crash reporting servers support.
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol:
g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
[215217:0223/114927.612650:ERROR:angle_platform_impl.cc(43)]
Display.cpp:805 (initialize): ANGLE Display::initialize error 12289:
glXQueryExtensionsString returned NULL
[215217:0223/114927.612791:ERROR:gl_surface_egl.cc(773)] EGL Driver message
(Critical) eglInitialize: glXQueryExtensionsString returned NULL
[215217:0223/114927.612814:ERROR:gl_surface_egl.cc(1322)] eglInitialize
OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[215217:0223/114927.613391:ERROR:angle_platform_impl.cc(43)]
Display.cpp:805 (initialize): ANGLE Display::initialize error 12289:
glXQueryExtensionsString returned NULL
[215217:0223/114927.613427:ERROR:gl_surface_egl.cc(773)] EGL Driver message
(Critical) eglInitialize: glXQueryExtensionsString returned NULL
[215217:0223/114927.613446:ERROR:gl_surface_egl.cc(1322)] eglInitialize
OpenGLES failed with error EGL_NOT_INITIALIZED
[215217:0223/114927.613464:ERROR:gl_initializer_linux_x11.cc(160)]
GLSurfaceEGL::InitializeOneOff failed.
[215217:0223/114927.614214:ERROR:viz_main_impl.cc(150)] Exiting GPU process
due to errors during initialization
Version:          Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4,
2021-02-11T11:48:44.518Z)
OS Version:       Linux x64 5.8.0-43-generic
CPUs:             AMD Ryzen 7 3700X 8-Core Processor (16 x 2199)
Memory (System):  31.37GB (17.62GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --no-sandbox --crash-reporter-id
e86afc88-2186-4152-a4a8-2f277411e866
GPU Status:       2d_canvas:                  unavailable_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  protected_video_decode:     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU % Mem MB   PID Process
    0   128 214376 code main
    0    32 214378   zygote
    0   161 214414     gpu-process
    0    32 214379   zygote
    0    32 214423   utility
    0   257 214436   window (pubspec.yaml - test1 - Visual Studio Code)
    0   128 214466     extensionHost
    0     0 214635       /bin/sh -c
"/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/dart"
"/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/snapshots/analysis_server.dart.snapshot"
"--lsp" "--client-id=VS-Code" "--client-version=3.19.2"
    0   289 214637
/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/dart
/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--lsp --client-id=VS-Code --client-version=3.19.2
    0     0 214710       /bin/sh -c
"/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/pub"
"global" "run" "devtools" "--machine" "--try-ports" "10" "--allow-embedding"
    0    64 214711
/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/dart
/home/bsutton/.dswitch/channels/beta/versions/2.12.0-259.12.beta/dart-sdk/bin/snapshots/pub.dart.snapshot
global run devtools --machine --try-ports 10 --allow-embedding
    0    64 214485     watcherService
    0    64 214588     searchService
    0    96 214666   shared-process

Workspace Stats:
|  Window (pubspec.yaml - test1 - Visual Studio Code)
|    Folder (test1): 7 files
|      File types: yaml(2) json(1) packages(1) lock(1) dart(1)
|      Conf files:

**Comment by bsutton** [comment]
And the status when crashed:

cat code.crash
(electron) Sending uncompressed crash reports is deprecated and will be
removed in a future version of Electron. Set { compress: true } to opt-in
to the new behavior. Crash reports will be uploaded gzipped, which most
crash reporting servers support.
[219533:0223/115137.562670:ERROR:browser_main_loop.cc(1434)] Unable to open
X display.
The futex facility returned an unexpected error code.
/dev/fd/3: No such file or directory
Server response:

**Comment by bsutton** [comment]
Sample project.

It has a compile error in start.dart

Just try to run the project by clicking the debug option that appears above
main().

**Comment by deepak1556** [comment]
Can you check if the issue happens with

1) `code --disable-gpu`
2) `code --use-gl=swiftshader`

**Comment by deepak1556** [comment]
> Sample project.
>
>It has a compile error in start.dart
> 
> Just try to run the project by clicking the debug option that appears above
main().

I don't see the link to the project, can you zip and attach it to the issue.

**Comment by bsutton** [comment]
1. code --disable-gpu
   - still crashes
   2. code --use-gl=swiftshader
   - still crashes

**Comment by bsutton** [comment]
I've just resent it but it should have appeared as an attachment on the
original.

**Comment by deepak1556** [comment]
I still don't see any attachment in your last comment, please clarify where you had sent it.
