### ISSUE TITLE
Branches created in Git CLI missing in integrated SCM

### ISSUE THREAD

**Issue by juliusn** [microsoft/vscode#115608]
- VSCode Version: 1.52.1
- OS Version: Mac OS Catalina 10.15.7

Steps to Reproduce:

1. Create a new folder and put a file in it
2. Open the folder in VS Code
3. Init Git repo
4. Create a branch using Git CLI: ```% git branch dev```
5. From Source Control menu select "Checkout to..." or run command ```> Git: Checkout to...```
6. The newly created branch does not show

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by eamodio** [comment]
I belive this has been fixed in 1.53, can you try that and report back? Thanks!

**Comment by juliusn** [comment]
Seems to be fixed!
