### ISSUE TITLE
Tooltips block or obscure text in the Explorer panel

### ISSUE THREAD

**Issue by alanschneider** [microsoft/vscode#115653]
- VSCode Version: 1.52.1
- OS Version: Windows 10

Steps to Reproduce:

1. Hover mouse cursor over file

![vscode_obscuring_filenames](https://user-images.githubusercontent.com/4107515/106691817-01335b80-6589-11eb-90f6-03c356cfd5db.png)

This one manages to block out multiple filenames:

![vscode_obscuring_filenames2](https://user-images.githubusercontent.com/4107515/106693820-16f65000-658c-11eb-8cbe-fb4db3740cc5.png)

Does this issue occur when all extensions are disabled?: Yes

This is a known issue that has been reported multiple times, but never resolved.

https://github.com/microsoft/vscode/issues/82775
https://github.com/microsoft/vscode/issues/70768

The tooltip provides almost zero value, but it does block text, adds to the visual noise of this interface, and is incredible annoying. This should either have a configuration item to disable the tooltip, or just get rid of it altogether.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/70768
We might reopen that one in the future
