### ISSUE TITLE
Change the colour of the windows

### ISSUE THREAD

**Issue by simeoncapy** [microsoft/vscode#115683]
Hello,
I need sometimes to open several windows of VSC (e.g. one in SSH, and one in local), and when I switch from one to the other, sometimes it's hard to remember which one is which.

It could be interesting to change the colour of a part of the window to allow fast "distinguishment". For example, the status bar, or the left bar with the icons.

**Comment by IllusionMH** [comment]
You can changes colors of these elements (as theme overrides in workspace `workbench.colorCustomizations` setting) or better use [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension.

**Comment by isidorn** [comment]
@IllusionMH thanks for a great answer

**Comment by simeoncapy** [comment]
Thank you so much, I didn't know this extension!
