### ISSUE TITLE
Use F12 or other shortcuts to jump to a function definition

### ISSUE THREAD

**Issue by taichirain** [Microsoft/vscode#11567]
- VSCode Version: 1.4
- OS Version: windows 7

Steps to Reproduce:
Use F12 or other shortcuts to jump to a function definition
1. 
2.

**Comment by dbaeumer** [comment]
@taichirain could you please provide additional information about what is not working. A screen cast my help or a expected behavior description.

**Comment by taichirain** [comment]
When writing code, I want to see where a function or variable is defined. Similar to the Sublime Text's "goto definition". 
In vscode, what should I do
![20160907110457](https://cloud.githubusercontent.com/assets/10025692/18298509/ae41ad24-74eb-11e6-9d01-2ee471967108.png)

**Comment by dbaeumer** [comment]
We currently don't have Goto Definition support for php. You might want to look at https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense which looks promise to provide such a feature in the future.

**Comment by taichirain** [comment]
@dbaeumer Thank you, I will continue to focus on the update of this plugin

**Comment by roblourens** [comment]
Now provided by Felix's extension.
