### ISSUE TITLE
Insider: notebook.cell.quitEdit not working as intended

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#115629]
@tyeoneill commented on [Tue Feb 02 2021](https://github.com/microsoft/vscode-jupyter/issues/4605)

## Environment data

-   VS Code version:1.53.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.2.529263813-dev
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.18363
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

The command `notebook.cell.quitEdit`  stops editing the cell.

## Actual behaviour

It does not stop editing the cell.

## Steps to reproduce:

The change introduced for VSCodeVim in the commit below doesn't seem to work:

https://github.com/VSCodeVim/Vim/commit/a3e4314239f3575d5328b783b818036e50486df3

I don't believe it's an issue with VSCodeVim as I have the command 'Notebook: Stop Editing Cell' at the top of my Command Palette and when I press Enter to run the command it does nothing, whereas if I select it directly with a mouse it works. So clearly something is up, I just don't know where to post the issue!

**Comment by IanMatthewHuff** [comment]
Moving @tyeoneill 's issue from the Jupyter extension, as I believe this command is owned by VS Code notebook UI.

**Comment by rebornix** [comment]
Fixed via Vim
