### ISSUE TITLE
 Cannot read property 'launch' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#1156]
Issue Id: <b>280d969c-e5e6-d1ae-0945-cfa99441ab50</b><br /><br />*Versions* <br />- 0.10.3<br />-  7cc0c602a2b802b09a3f56b68a1a61ee9e8f0066<br />*Stack* <br />Error: Cannot read property 'launch' of null<br />[/vs/base/common/errors.ts#L300:4 (toErrorMessage)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/errors.ts#L300:4 (toErrorMessage))<br />[/vs/workbench/parts/debug/browser/debugService.ts#L459:13 (DebugService.enableOrDisableAllBreakpoints)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/workbench/parts/debug/browser/debugService.ts#L459:13 (DebugService.enableOrDisableAllBreakpoints))<br />[/vs/base/common/winjs.base.raw.js#L1432:0](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1432:0)<br />[/vs/base/common/winjs.base.raw.js#L1080:0 (_cancelAction)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1080:0 (_cancelAction))<br />[/vs/base/common/winjs.base.raw.js#L1319:0 (_progress)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1319:0 (_progress))<br />[/vs/base/common/winjs.base.raw.js#L1207:0 (_notify)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1207:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1387:0 (_isException)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1387:0 (_isException))<br />[/vs/base/common/winjs.base.raw.js#L1080:0 (_cancelAction)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1080:0 (_cancelAction))<br />[/vs/base/common/winjs.base.raw.js#L1319:0 (_progress)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1319:0 (_progress))<br />[/vs/base/common/winjs.base.raw.js#L1207:0 (_notify)](https://github.com/microsoft/vscode/blob/783ecf841a2b21edca6d86853670cae89b4c244f/src/vs/base/common/winjs.base.raw.js#L1207:0 (_notify))<br />

**Comment by isidorn** [comment]
@SofianHn do we know how many times did this issue happen?
