### ISSUE TITLE
Closed Repositories keep reopening

### ISSUE THREAD

**Issue by justlevine** [microsoft/vscode#115621]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open folder associated with two git repos (e.g. `/mysite` (has repo)  -> `mysite/plugins/my-plugin` (has separate repo). 
2. Right click on `mysite` repo, and select Close Repository.
3. Make a change to one of the files in `/mysite/plugins/my-plugin`.
4. Wait a few and the `mysite` repo shows back up in Source Control.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
Related #107398

**Comment by kaffarell** [comment]
Duplicate #107398, pr already created (#128797)

**Comment by justlevine** [comment]
It's a dupe
