### ISSUE TITLE
Provide a way for custom editors to process untitled files without relying on textDocument

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#115631]
Currently the "Reopen with" experience for untitled files and custom binary editors needs better support. See #114711. After discussion in the API call the best proposal seems to be placing the untitled file data in the OpenEditor / OpenNotebook context. There interface would be modified as shown:
```ts
	/**
	 * Additional information about the opening custom document.
	 */
	interface CustomDocumentOpenContext {
		/**
		 * The id of the backup to restore the document from or `undefined` if there is no backup.
		 *
		 * If this is provided, your extension should restore the editor from the backup instead of reading the file
		 * from the user's workspace.
		 */
		readonly backupId?: string;
		/**
		 * If the URI is an untitled file, this will be populated with the byte data of that file
		 *
		 * If this is provided, your extension should utilize this byte data rather than executing fs APIs on the URI passed in
		 */
		readonly untitledDocumentData?: Uint8Array;
	}

	interface NotebookDocumentOpenContext {
		readonly backupId?: string;
		readonly untitledDocumentData?: Uint8Array;
	}
```
The extension other would then not be required to resolve the URI to a text document (which would have been disposed of).

**Comment by lramos15** [comment]
Closing this as this API is stable for custom editors and will most likely remain stable for notebooks too as it follows the same pattern. Although the notebook piece will remain in proposed typings due to all Notebook APIs currently being proposed, see https://github.com/microsoft/vscode/issues/106744.

**Comment by Tyriar** [comment]
@lramos15 did this get tested? We'll need to add on-testplan or verification-needed

**Comment by lramos15** [comment]
@Tyriar Thanks for pointing this out. I have added the verification-needed flag. This is my first API proposal so I'm just getting used to the flow and didn't even think about tests, it definitely needs testing and should've had a test plan item but instead I will just ask for some verification as I missed the test plan assignment.

To verify:
1. Clone the sources of a custom editor and a notebook. I recommend https://github.com/microsoft/vscode-hexeditor and https://github.com/microsoft/vscode-markdown-notebook respectively
2. Ensure that when you open an untitled file their open contexts are respectively populated with the buffer containing the bytes of the untitled file
3. Open a non untitled file and ensure these properties aren't passed to the open context.

**Comment by aeschli** [comment]
Verified for the  custom editor (hex editor), but I wasn't able to open the vscode-markdown-notebook on a untitled editor (see #119954)
