### ISSUE TITLE
Visual Studio Code Getting anaconda working 

### ISSUE THREAD

**Issue by jamielukephillips** [microsoft/vscode#115610]
Issue Type: <b>Bug</b>

xfb

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.47GB free)|
|Process Argv|--crash-reporter-id 6c730041-0bc9-423f-b067-d0ad969de8b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

![image](https://user-images.githubusercontent.com/71874875/106612691-45126a80-6561-11eb-9bb4-71008dc056d1.png)
![image](https://user-images.githubusercontent.com/71874875/106612777-607d7580-6561-11eb-85e6-c08482bec926.png)
![image](https://user-images.githubusercontent.com/71874875/106612816-6d9a6480-6561-11eb-9f3f-82a58e33f3db.png)
![image](https://user-images.githubusercontent.com/71874875/106612875-7be88080-6561-11eb-8b13-77f669c08b1d.png)

Hi,

I am unable to access anaconda packages on Visual Studio Code. 
Please could you help me to solve this problem?

Kind regards,

Jamie

**Comment by jeffnorville** [comment]
Hi Jamie - do you need 64-bit Python (ex Tensorflow etc), or did you install it because you have a 64-bit system?

**Comment by jamielukephillips** [comment]
I installed it because of my 64-bit system- is it unnecessary?
