### ISSUE TITLE
Extensions not working at all

### ISSUE THREAD

**Issue by vraghu1983** [Microsoft/vscode#11561]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:
1. Just installed VS Code - and tried to browse extensions 
2. There seems to be a progress bar running indefineitely - and then no extensions are shown.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by vraghu1983** [comment]
Yes - office network - let me try it at my home - and let you know.

Regards,
Raghu

**Comment by joaomoreno** [comment]
Ping @vraghu1983
