### ISSUE TITLE
v8 crash when loading wasm in extension host

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#115646]
Created from https://github.com/microsoft/vscode/issues/113410#issuecomment-772096623

Minimal electron repo: https://gist.github.com/deepak1556/a6d791b204978aeed549347b6c55d124

StackTrace: https://github.com/microsoft/vscode/issues/113410#issuecomment-767052786

Upstream issue in node: https://github.com/nodejs/node/issues/37061

The issue is only with process running as node.

```
Version: 1.53.0-insider (Universal)
Commit: 8d779a4fadaadec06b44b8875a1d3c4adba8e380
Date: 2021-02-02T16:34:06.213Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
```

**Comment by deepak1556** [comment]
The difference between the chrome and node arise from the use of different page allocator for v8. Chrome renderer uses Gin's v8 page allocator which inturn depends on partition_alloc handles `MAP_JIT` calls pretty well base/allocator/partition_allocator/page_allocator_internals_posix.h compared to the default page allocator from v8. Switching the page allocator in node platform creation to use chromium's partition alloc fixes the issue.

I can push that as a fix for vscode but the root issue needs to be investigated in node as they can't do such a switch.

**Comment by deepak1556** [comment]
v8 issue : https://bugs.chromium.org/p/v8/issues/detail?id=11389

**Comment by andreialecu** [comment]
Out of curiosity. How does the electron bump fix it? I wasn't able to find anything relevant in the commit history.

**Comment by deepak1556** [comment]
The allocator switch has been made in our internal electron builds for early testing, we will create a PR in OSS electron with the same change sometime this week.

**Comment by jtkiley** [comment]
Sorry to ask here, but I've been poking around, can't find a solid answer, and don't want to break vscode on my M1. Is the latest insiders build now working with macOS 11.2 in cases where this issue popped up?

**Comment by RajceP** [comment]
> Sorry to ask here, but I've been poking around, can't find a solid answer, and don't want to break vscode on my M1. Is the latest insiders build now working with macOS 11.2 in cases where this issue popped up?

Yes!

**Comment by andreialecu** [comment]
<img width="870" alt="Screenshot 2021-02-05 at 21 32 21" src="https://user-images.githubusercontent.com/697707/107080216-a2c0e400-67f9-11eb-84d4-2465cd1cc07d.png">

I'm seeing this error in the developer tools with the latest insiders. cc @deepak1556

**Comment by deepak1556** [comment]
Can you open an new issue for that extension `vscode-oniguruma` https://github.com/microsoft/vscode-oniguruma if the issue is seen with stable too. /cc @alexdima

**Comment by alexdima** [comment]
@andreialecu I think that is a problem with the bracket pair colorizer 2 extension (AFACIT it is using `vscode-oniguruma` incorrectly).

**Comment by andreialecu** [comment]
Was my initial suspicion as well.

I can also confirm that latest insiders works great on MacOS `arm64`.

**Comment by simonhyphen8** [comment]
I'm using VSCode with Salesforce.
MacBook Pro M1 with Big Sur V11.0
VSCode version 1.53.0
I only have 14 extensions installed - the standard Salesforce ones, VSCode LiveShare, ESLint and a Salesforce Documenter.
Restarting the extension host using the button that pops up works, as does closing & reopening the project, but this is proving very frustrating.  I can't tell in these posts if this issue is fixed or not, or if I have to do something to resolve it myself?

Any advice greatly appreciated!

**Comment by deepak1556** [comment]
Can you try the universal build or arm64 build insiders version https://code.visualstudio.com/insiders and see if the issue persists.
