### ISSUE TITLE
Multiple Full Screen Windows Can Freeze

### ISSUE THREAD

**Issue by amiller77** [microsoft/vscode#115628]
Quite frequently when I open a second full-screen window of VS Code, and click "open" to view another project's contents, the dialog box does not appear and I am not able to open the contents - I also lose the ability to close the second window and have to Command-Q and repoen VS Code entirely for it to work as expected.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
