### ISSUE TITLE
electron_node tsserver.js uses a lot cpu on typing

### ISSUE THREAD

**Issue by ako-v** [microsoft/vscode#115697]
Steps to reproduce:
1) create js file
2) Start typing

possible solutions attempted that didn't work:
1) disable all extensions
2) use  JS and TS Nightly extension
3) Check 'TypeScript: Disable Automatic Type Acquisition'.

but none of them worked. I know that there are duplications of this problem, but NO Solution provided till yet, or none of them worked for me. I'm not using Typescript, just plain JavaScript. also project is so small.

![Screenshot from 2021-02-03 16-25-42](https://user-images.githubusercontent.com/69965670/106751080-fab2eb80-663d-11eb-8455-b9a6eceb12bc.png)

<details>
<summary>System Info</summary>

CPUs | Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2628)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: disabled_software skia_renderer: enabled_on video_decode: unavailable_off vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 0, 0, 0
Memory (System) | 15.56GB (3.87GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id 3fe038ea-eaa5-408f-a600-efc55d86f436
Screen Reader | no
VM | 0%

</details>

<details>
<summary>Running Processes</summary>

CPU% | Mem MB | PID | Process
------|-----|-----|-----
0|159|70728|code main
0	    |32	 |70732	|zygote
0	   |127	 |70757	     |gpu-process
0	    |32	 |70733	   |zygote
1	    |80	|106677	     |window (Issue Reporter)
0	    |48	 |70764	   |utility
0	   |239	 |70779	   |window (● User.js - Backend - Visual Studio Code)
0	    | 0	 |71111	    | /bin/bash
0	   |112	 |71241	     |extensionHost
0	   |112	 |71300	      | electron_node tsserver.js 
14	   |414	 |71301	       |electron_node tsserver.js 
0	    |48	 |71368	       |/usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=71241
0	    |64	 |71272	     |watcherService
0	   |112	 |71335	   |shared-process
0	    | 0	|106696	    | /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
0	     |0	|106697	     |  /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   
</details>

<details>
<summary>Workspace Metadata</summary>

|  Window (● User.js - Backend - Visual Studio Code)
|    Folder (Backend): 24 files
|      File types: js(11) json(2) gitignore(1) env(1) txt(1)
|      Conf files: package.json(1)

</details>

**Comment by mjbvz** [comment]
When you type, we have to complete IntelliSense, errors, etc. This requires some CPU usage

If you see excessive cpu usage, please share a project that demonstrates the issue

**Comment by ako-v** [comment]
> When you type, we have to complete IntelliSense, errors, etc. This requires some CPU usage
> 
> If you see excessive cpu usage, please share a project that demonstrates the issue

It's because of IntelliSense, because I have this problem even when I type comments.

**Comment by mjbvz** [comment]
The language service has to do work, even in comments. IntelliSense is still enabled in them
