### ISSUE TITLE
`MainThreadNotebooks` does not dispose everything in its `dispose` method

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#115698]
1. Launch vscode and use notebooks
2. Kill the extension host via terminal / task manager.
3. Observe that not all resources associated with the crashed extension host are disposed
4. (Restart the extension host. Perhaps some problems will appear in the UI due to forgotten registrations, etc.)

e.g. problematic forgotten `IDisposable`s: `_notebookProviders`, `_notebookKernelProviders`, `_toDisposeOnEditorRemove`, etc.

**Comment by jrieken** [comment]
fyi - I am addressing some of this (maybe all) in https://github.com/microsoft/vscode/pull/116443/files#diff-6b66ff05127abe5d554680a1d009788668f8b22257cb8b7ae09b9e1c3d0e7f17
