### ISSUE TITLE
Can't press Ctrl+F5 to start without debugging in VsCode on Linux OS

### ISSUE THREAD

**Issue by SunnyChen1** [microsoft/vscode#115600]
**Environment**
Operating System:Linux
JDK version:14.0.2
Visual Studio Code version:1.52.1
Java extension version:0.74.0
Java Debugger extension version:0.31.0

**Steps To Reproduce**
1. Open a  js file  in VS Code
2. Set a breakpoint
3. Press Ctrl+F5to start without debugging

**Actual Result**
The program cannot be run and vscode windows will be closed auto.

**Expected Result**
The program starts without hitting the breakpoint.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce

**Comment by SunnyChen1** [comment]
@isidorn , the issue can repro in Visual Studio Code Insiders on **Linux OS**  with using above steps

**Comment by isidorn** [comment]
I just tried this on my Ubuntu 20 and this works like a charm with JavaScript.
@testforstephen can you reproduce this? If yes, is java doing something funky with the keybindings, or is it supporting run without debugging mode?
@SunnyChen1 if you do this with a simple javascript file do you see the same. Here's an example file
```
console.log('hello there!')
```

**Comment by testforstephen** [comment]
Sorry, i don't have linux on hand yet. I cannot reproduce it in macOS.

And yes, Java debugger supports run without debugging mode.
