### ISSUE TITLE
Hide or shorten path in Debug Console

### ISSUE THREAD

**Issue by MCluck90** [microsoft/vscode#115625]
When I'm debugging, I like to have my console on the right side of the screen. Unfortunately, I frequently see problems like this

![image](https://user-images.githubusercontent.com/1753801/106646564-23a68400-654b-11eb-9cd4-f4007c3d4e1e.png)

I'd love it if I could hide the file path so that the values don't get squashed down like this. Ideally, there would be some sort of indicator on the end of the line that I could hover to show the file path and if I click on it, it would open that file.

**Comment by isidorn** [comment]
@MCluck90 thanks for feedback. You can try it out with VS Code insdiers from this Friday and let us know how it works!
