### ISSUE TITLE
Test viewlet failing tests not shown

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#115687]
Have some tests failing, run all tests, notice how 2858 passed out of 2861

1) The math is off, it says 100% pass 🐛 
2) Failing tests should be easier to find, they should be sorted to top imho

![Screenshot 2021-02-03 at 12 26 49](https://user-images.githubusercontent.com/1926584/106741986-b6fbba00-661c-11eb-85c3-cc09ce865203.png)

**Comment by connor4312** [comment]
It rounds to 3 digits... should probably round down 😛

**Comment by isidorn** [comment]
Haha I was expecting something like that!

Also failing tests to top? How do I find them easily in this huge tree?

**Comment by connor4312** [comment]
There's another issue open for the sorting 🙂
