### ISSUE TITLE
Revisit "Find File References" contribution in editor tab and explorer menus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115694]
I noticed that a new "Find File References" entry made it into these menus:

![image](https://user-images.githubusercontent.com/900690/106753214-adc61980-662b-11eb-97a5-fccd19d46cb8.png)

![image](https://user-images.githubusercontent.com/900690/106753237-b3236400-662b-11eb-84e4-2164f21fdefc.png)

I think we should at least have a UX discussion around making these menus larger than they are already today. We are generally very careful about adding more entries.

//cc @misolori @egamma

**Comment by isidorn** [comment]
Please have in mind that we are working very hard to keep this menus compact and that we literally close 2 issues every week where people request more actions in this menus. Until we have customisable context menus I think we should be very careful what we are adding.

The `Open Timeline` action is also questionable in the Explorer.
As for the `Open Timeline`, can we at least not show it if the Timeline view is collapsed or Hidden? Since that is a clear signal the user is not interested in the timeline view.
@eamodio let me know if you would like me to create a new issue for this

**Comment by gjsjohnmurray** [comment]
> The `Open Timeline` action is also questionable in the Explorer.

Its behaviour is also a bit surprising to me. If the Timeline view is visible (collapsed or expanded) `Open Timeline` reveals the timeline for the chosen file **and** pins it there. Whereas if the Timeline view is hidden `Open Timeline` shows the view and displays the timeline for the chosen file but doesn't pin it.

**Comment by mjbvz** [comment]
One thing to note: this command comes from the JS/TS extension. File references are not yet a feature of core, although I believe @jrieken was interested in adding official support for them in the future

I believe that file references have clear value for JS/TS users and putting this command in the menu helps users discover this feature. I'm not sure what the alternative would be. There's a command to get file references for the current file, but it is nice to be able to just right click and run this on any file

**Comment by eamodio** [comment]
> > The `Open Timeline` action is also questionable in the Explorer.
> 
> Its behaviour is also a bit surprising to me. If the Timeline view is visible (collapsed or expanded) `Open Timeline` reveals the timeline for the chosen file **and** pins it there. Whereas if the Timeline view is hidden `Open Timeline` shows the view and displays the timeline for the chosen file but doesn't pin it.

That's a bug it should pin in both cases.

**Comment by bpasero** [comment]
@mjbvz 

would it make sense to have it at a similar location where we already have "Find" for folders:

![image](https://user-images.githubusercontent.com/900690/106873713-056c8f80-66d5-11eb-82da-c2bb6d63cd37.png)

I am not a big fan of having this at the end just piling up with other things that are totally unrelated:

![image](https://user-images.githubusercontent.com/900690/106873768-15846f00-66d5-11eb-9996-7f7461e72e65.png)

As for editor tabs: I am not convinced that it makes sense to have it there (I am more convinced to have it for the explorer, given it is scoped to 2 file types). Editor tabs typically do not have as many file related entries as the explorer, as you can see the menu is more for managing tabs and not for doing operations on the file (with some exceptions - but e.g. there is no delete or rename in there). In the past we have pushed back on every request to add more file-related operations to this menu so I would like us to follow this principle as well.

**Comment by mjbvz** [comment]
I previously moved find file references into the search group in the explorer

I haven't heard any other feedback about removing `find file references` from file tabs, so am going to close this. We can revisit it if we add `file references` as a built-in feature instead of a JS/TS specific one
