### ISSUE TITLE
All extensions should be required to respect the enableTelemetry setting to be allowed on the marketplace

### ISSUE THREAD

**Issue by jerkstorecaller** [microsoft/vscode#115619]
Quoting the website: "VS Code lets you add features to the product by installing Microsoft and third-party extensions. These extensions may be collecting their own usage data and are not controlled by the telemetry.enableTelemetry setting. Consult the specific extension's documentation to learn about its telemetry reporting and whether it can be disabled."

I see no reason why there's an extension-sized loophole in the telemetry optout. It's unreasonable to expect the user to read the doc of every extension to see what setting they need to disable telemetry (assuming they even provide such a setting). This skirts the line of a dark pattern designed to discourage the user from avoiding telemetry, and getting them used to forceful telemetry. 

If you're serious about allowing the user to opt out of telemetry, then the terms of the extension marketplace should require authors to respect the single enableTelemetry flag, or they don't get approved.

**Comment by isidorn** [comment]
Our plan is to tackle this via https://github.com/microsoft/vscode/issues/160090
Thus closing as duplicate
