### ISSUE TITLE
Open live Server on html 

### ISSUE THREAD

**Issue by turkishkitten** [microsoft/vscode#115624]
Issue Type: <b>Bug</b>

Ok so first of all I'm not a pro, :) but I will have a project working with nmp and it will be working fine, then I take a short break when my computer goes to sleep mode or even if I close my mac so say a client doesn't see what I'm working on, the whole live server stops. now the npm is still detecting change and looks like it's working but when I go to the html file to right click and open live server again nothing opens and I have to totally close my vs code and restart it and npm run start again and right click open with live server for this to work. Is there a bug? or am I doing something wrong? Thanks Bonnie 

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 17.7.0

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
sass-indented|syl|1.8.15
emmet-live|yse|1.0.0

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

If there is something wrong happens to LiveServer it should be reported in LiveServer repo (if it wasn't reported already)

At this point it looks like editor itself works as expected.
