### ISSUE TITLE
SSH connections

### ISSUE THREAD

**Issue by codigo66** [microsoft/vscode#115649]
Issue Type: <b>Bug</b>

Hello.
I really don't know if this is a bug.

I'am working in several projects, some of then with GIT version controlled by SSH connection. I pull and push to remote repository directly with VSC (no extensions).

The issue that I have, is that VSC repeatedly make SSH connections by itself, with out pull or push request by me, even when I working with projects that don't have a git versioning.

I know about it, because my server send me an email every time that SSH connection was made from my ip and my computer at the time when I open or working with VSC.

Like I said, I don't know if this is a bug, or this is a normal procedure by VSC.
Sorry about my terrible english.

Best regards.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz (8 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (25.36GB free)|
|Process Argv|--crash-reporter-id 80c069d2-4504-47ff-96a2-658157252399|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.6.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.19.1
flutter|Dar|3.19.0
gitlens|eam|11.2.0
vscode-html-css|ecm|1.9.1
prettier-vscode|esb|5.8.0
php-debug|fel|1.14.7
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
terminal|for|0.0.10
beautify|Hoo|1.5.0
minifyall|jos|2.5.0
awesome-flutter-snippets|Nas|2.0.4
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.0.2
quicktype|qui|12.0.46
open-in-browser|tec|2.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by roblourens** [comment]
Our git extension will periodically update automatically if you have `"git.autofetch": true` set, do you?

**Comment by codigo66** [comment]
> Our git extension will periodically update automatically if you have `"git.autofetch": true` set, do you?

Hello @roblourens 
Yes, I have set git.autofetch to true.
Thank you for your time and for your quick response and I am very sorry for the delay of mine.
