### ISSUE TITLE
Allow to "copy" language support from one side of diff editor to the other

### ISSUE THREAD

**Issue by marcelofarias** [microsoft/vscode#115618]
It would be nice if symbolic information was retrieved from LSP for non-physical files as well. IntelliJ for instance accomplished that exposing an API that allow to mark any document as "close enough" to some file that exists on disk, so when you view a previous version of this file in a git diff you can still do things like go to definition, view docs, find usages, etc.

**Comment by dbaeumer** [comment]
Actually this is unrelated to LSP. IMO this would be a general feature in VS Code since it can be fulfilled using the normal VS Code API.

@bpasero assigning to you since this would be a feature in the workbench editor itself.

**Comment by bpasero** [comment]
I think you picked the wrong person.

**Comment by dbaeumer** [comment]
@bpasero can you help me to decide who owns the diff editor (https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/textDiffEditor.ts#L1).

The request ask that we add some sort of button to the diff editor that supports that code navigation features use the workspace file for doing the navigation when compared to the workspace file.

**Comment by bpasero** [comment]
@dbaeumer I wrote that class but in the end it just uses our monaco diff editor from Alex.

I don't think this is about diff editors but about language support in non-file editors. Here is what happens:
* git registers a file system provider for files that are on the index or staged
* we open a diff of the local file and the staged one or the index one
* we compare the 2 files leveraging the file system provider
* we have infrastructure in the code editor to provide smart language information (and here I am not an expert anymore)
* the extension responsible for showing that smart language information needs to be able to provide this information for these git resources

So I suggest to think about it this way:
* there are non-file editors
* extensions typically only support file based editos
* extensions need to be able to provide language smarts for the non-file based editors

Does that make sense?

**Comment by dbaeumer** [comment]
@bpasero yes, it does make sense it a perfect world where we can teach language services to understand git resource. However this is most of the time complicated and requires quite some work inside a language server.

The proposed feature (to my understanding) would work differently. Assuming you have a file file:///a.ts and file git:///a.ts and the user want to use code comprehension features in git:///a.ts he can press a button saying that the file is close to file:///a.ts. If the user then for example executes go to definition in git:///a.ts we would use the diff to file:///a.ts to map the position in git:///a.ts to a position in file:///a.ts and would execute go to definition with that position and file:///a.ts. 

This might not always work but it would give a user navigation features with a language server understanding git:/// URIs.

The most prominent place of such a feature would be the diff editor. 

So it looks to me that this would be a combined effort between workbench diff editor and Monaco diff editor.

**Comment by bpasero** [comment]
I have absolutely no idea how this would work, but I am fine leaving this open as feature request. 

To clarify: you might have replaced the contents of the file with something entirely different so how would the "left hand side" of the diff be any helpful in figuring out the symbols for these new contents?

**Comment by dbaeumer** [comment]
> To clarify: you might have replaced the contents of the file with something entirely different so how would the "left hand side" of the diff be any helpful in figuring out the symbols for these new contents?

That is correct. That is why the suggestion adds a button where the user needs to say that the two files are close to each other and the mapping will very likely be correct.

**Comment by marcelofarias** [comment]
Not as a button pressed by the user, but as a method that extension authors can call. In IntelliJ, we call `OutsidersPsiFileSupport.markFile(file, /path/to/physical/file)` and that's all it takes to have PSI support in buffers associated with our custom protocol handler.

**Comment by marcelofarias** [comment]
And again, this is not about git diffs only, but something to offer to any extension that calls `workspace.registerTextDocumentContentProvider()`

**Comment by dbaeumer** [comment]
Actually I like the API thing as well. 

@jrieken did something like this every come up. It would be a cool trick to get code navigation in files which a language service usually doesn't understand.
