### ISSUE TITLE
Extension Fail to load properly or not at all once installed

### ISSUE THREAD

**Issue by ghost-sage** [microsoft/vscode#115650]
I have installed multiple extension for Python, MSSQL Server, MySQL, PL/SQL, and RStudio.  The seems to load issues with Extension receiving pop notification regarding loading and settings.  Also to manual add connection for the SQL Server side and I receive notification for Object commands errors.  I have attempted uninstall all the extension added and then re-install them, but the issue still comes back, but not for all extensions load errors become random on each startup.   I have even done a full uninstall with removal of the registry entries, Data files and download of the install file. 

Current Version of Visual Studio Code:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

System Info:
CPUs	AMD A8-4500M APU with Radeon(tm) HD Graphics (4 x 1896)
GPU Status	2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg)	
Memory (System)	15.47GB (6.04GB free)
Process Argv	--crash-reporter-id 8f6cdae2-2d3e-4037-915f-29669a8a6b3f
Screen Reader	no
VM	0% 

Extension	Author (truncated)	Version
better-comments	aar	2.1.0
tfcomplete	afp	1.0.1
vscode-sequence-diagrams	Ale	0.4.3
altwalker-model-visualizer	Alt	0.0.2
previewseqdiag-vscode	ari	0.2.4
sql-builder	ash	0.0.2
snapshot-tools	asv	0.4.0
scratchpad	awe	0.1.0
vscode-database	baj	2.2.3
code-diagram	bda	0.1.0
vscode-importmagic	bra	0.2.5
py23	Bru	0.0.1
scratchpads	bue	0.0.7
plsql	cas	0.0.5
evaluate-python-expression	cpr	0.1.0
vscode-postgresql-client2	cwe	3.3.0
vscode-postgresql-client2	cwe	3.4.4
vsc-invoke	dch	0.0.12
deepcode	dee	3.0.11
pyinit	Dio	0.0.3
python-preview	don	0.0.4
code-runner	for	0.11.2
vscode-mysql	for	0.4.0
matlab	Gim	2.0.0
vscode-test-explorer	hbe	2.19.5
r	Iku	1.6.4
mysql-scratchpad	jbl	0.1.1
nbpreviewer	jit	1.2.2
extract-sql-from-script	Joe	0.0.6
code-flow-extension	Jos	1.1.1
python-project-scaffold-generator	Kam	0.0.1
python2go	leb	0.0.48
MagicPython	mag	1.1.0
fox	Mal	0.1.1
python-path	mge	0.0.11
vscode-postgresql	ms-	0.3.0
gather	ms-	2021.1.0
python	ms-	2021.1.502429796
jupyter	ms-	2020.12.414227025
vscode-mscgen	msc	1.2.0
vscode-ts-uml	myx	1.0.4
neuron-IPE	neu	1.0.4
python-coding-tools	nil	1.0.3
vscode-pylens	nin	0.0.3
typescript-uml	ott	1.1.7
VSNotebooks	pav	1.4.4
open-php-html-js-in-browser	Pri	2.0.1
python-string-sql	ptw	1.1.0
vscode-data-preview	Ran	2.2.0
py-coverage-view	rdu	0.1.0
ruby	reb	0.28.1
fabric8-analytics	red	0.3.1
vscode-qt-for-python	sea	0.5.3
python-init-generator	See	0.0.7
visualize-control-flow	tea	0.2.0
python-editing-terminal	ted	1.0.6
umlet	the	1.0.3
python	tht	0.2.3
vscode-decompiler	tin	0.0.8
python-extended-snippets	tus	0.0.1
vscodeintellicode	Vis	1.2.11
vscode-ruby	win	0.28.0
livecode	xir	1.3.10
plsql-language	xyz	1.8.2
json	Zai	2.0.2

Include A/B experiment Info:
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorercf:30224615
openfilemenucf:30224648
pythonvsded773:30248341
pythonvspyt600cf:30251589

**Comment by gjsjohnmurray** [comment]
Please run the Start Bisect command to investigate which extension is causing the problem. Then report it to the extension author.

**Comment by ghost-sage** [comment]
I ran the Bisect command and the results notification below which is pretty much all the extensions I have installed and a lot them were the 5 star rated ones.  

Extension Bisect is active and has disabled 65 extensions. Check if you can still reproduce the problem and proceed by selecting from these options.
