### ISSUE TITLE
Source control keeps changing repository

### ISSUE THREAD

**Issue by gtron** [microsoft/vscode#115604]
Issue Type: <b>Bug</b>

When I do any operation on a the repository view the focus keeps changing randomly to another repository.

For example, if I stage a file in the repository A the focus changes to the repository B, and if I try to commit it obviously says that I do not have staged files because it is a different repo!
It is annoying.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-64-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 1799)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 5, 5|
|Memory (System)|15.34GB (0.17GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id e45735a1-21fb-412e-90f5-0734787091d0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.1.1
better-toml|bun|0.3.2
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.8.0
git-project-manager|fel|1.7.1
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
vscode-docker|ms-|1.9.1
remote-containers|ms-|0.155.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|16.0.2
material-icon-theme|PKi|4.5.0
salesforcedx-vscode-core|sal|50.14.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen after you run the command to reload with all extensions disabled? If not, reload with extensions and use the extension bisect command to try and pinpoint the source of the issue.

If it still happens without extensions, are you able to try with the Insiders build? If not, maybe wait until 1.53 ships (expected later this week) and re-test.

**Comment by eamodio** [comment]
I believe this has been fixed in 1.53, can you try it and report back? Thanks!

**Comment by gtron** [comment]
Hi, sorry for the delay. 
Even if this is closed, I'd like to report back and thank you for the answers.
The IDE auto-updated so I couldn't test 1.53 exactly but I am using 1.54 and it works.
Thanks for your work!
