### ISSUE TITLE
"Open Editors" view should not open collapsed when making visible

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115685]
When I make the "open editors" view visible, it should not be collapsed.

**Comment by isidorn** [comment]
Very good point. I would like to fix this as part of the release. The fix is super simple - just changing the boolean value.

**Comment by isidorn** [comment]
Pushed a fix to master, let see if @lszomoru agrees and I will also cherry pick it on top of the release branch

**Comment by isidorn** [comment]
@bpasero can you please review https://github.com/microsoft/vscode/pull/115686
@lszomoru gave a green light so we can merge to the release

**Comment by isidorn** [comment]
@lszomoru also approved the PR, I mereged the PR and triggered build. All is good, closing issue
