### ISSUE TITLE
Close folder shortcut not working

### ISSUE THREAD

**Issue by AvanishCodes** [microsoft/vscode#115682]
- VSCode Version: 1.52.1
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. The folder is not getting closed with the shortcut Ctrl+K+F.
2. It was present even when I had no extensions
3. I had same issue in Windows 10 also.
4. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by AvanishCodes** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I got it.
So Ctrl+K F is not a shortcut, but what does it mean?

**Comment by bpasero** [comment]
See https://code.visualstudio.com/docs/getstarted/keybindings
