### ISSUE TITLE
Is it possible to integrate the terminal that comes with the system into VS Code.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode#115659]
VS Code supports cmd terminal, powershell terminal, and bash terminal. Can the system's own terminal be integrated into VS Code instead of popping up?

For example, when using: "_C:\Users\username\AppData\Local\Microsoft\WindowsApps\wt.exe_", "wt.exe" will pop up separately instead of being embedded in VS Code.

**Comment by Tyriar** [comment]
You're configuring the roles of shells and terminals. Windows terminal runs shells (power shell, cmd, bash) just like vscode's terminal does. We cannot embed windows terminal inside vscode though.
