### ISSUE TITLE
support extension-provided tasks when there is no folder open (single-file mode)

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#115678]
The current behavior in providing tasks for single-files is as below:

it looks like that VsCode is searching for the tasks.json in .vscode folder for reading tasks,
and it searches for the tasks.json in the user temp folder for writing the selected configuration tasks.

and the only case that vaCode read and run a task for a single-mode file from the tasks.json is when the task is a default task. otherwise, the user can not choose between other tasks in tasks.json.

"configure task" shows the template configurations, although it should show the tasks in tasks.json if they exist:
![image](https://user-images.githubusercontent.com/16143955/106720542-72d6ce00-65b8-11eb-8e0d-8ce0f4da43fc.png)

"run build task" will work fine if there is a default task being configured in tasks.json. otherwise, this will be shown (the correct behavior is to show all the build tasks to choose from if there is no default being set):
![image](https://user-images.githubusercontent.com/16143955/106720571-78ccaf00-65b8-11eb-96a0-1ce81a897933.png)

cpptools extension issue: https://github.com/microsoft/vscode-cpptools/issues/6829

**Comment by alexr00** [comment]
Can you clarify what single-file mode means?

**Comment by elahehrashedi** [comment]
when we open a single .cpp file without opening a folder or creating a project

**Comment by alexr00** [comment]
Ok, I get it now. Only User Tasks are supported when there isn't a folder open. And, only tasks.json `shell` and `process` tasks are permitted in Users Tasks. 

This is a feature request to support extension provided tasks when there is no folder open.
