### ISSUE TITLE
vscode can't open staged file.

### ISSUE THREAD

**Issue by HppZ** [microsoft/vscode#115684]
Issue Type: <b>Bug</b>

click on a staged file, vscode can't open it. loading for a long time. I have to reopen vscode.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.06GB free)|
|Process Argv|--crash-reporter-id 57692a97-58af-41ee-a1e0-4451b93bc8e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
csharp|ms-|1.23.8
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
powershell|ms-|2020.6.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt600cf:30251589

```

</details>

**Comment by eamodio** [comment]
Does this happen with only a single file, any file, all repos? Can you provide more information as to how you are reproducing this? Can you try reproducing the issue with 1.53?
