### ISSUE TITLE
No response after creating .cpp file

### ISSUE THREAD

**Issue by Charlie-Stuwart** [microsoft/vscode#115669]
These days when I use Visual Studio Code(right after Jan.1, 2021), I found that sometimes if I create a new file and change it's suffix name to .cpp, it didn't response. Whic means this new file is still named as "Untitled.txt", I hope if you can check that?
Or maybe just because I finish these operation too fast.

**Comment by alexr00** [comment]
Can you please share the code that is in the file when you change it .cpp?

**Comment by Charlie-Stuwart** [comment]
It's empty, I found this bug(?) when I was creating a new file, and just turn it in to .cpp, because the default type is .txt

**Comment by Charlie-Stuwart** [comment]
And I was just be surprised because of the extremely fast reply from VScode

**Comment by alexr00** [comment]
Ah, I thought you were saying that VS Code became unresponsive (froze) when you changed the file extension to cpp. 

Can you provide step by step instructions for how to reproduce the issue? For example, where are you changing the extension cpp?

**Comment by Charlie-Stuwart** [comment]
Emm, it's my problem that I didn't get a good title.
I just mean that when I am trying to create a new file and turn the .txt to .cpp, nothing happens, the file is still named as untitled.txt, not the name I typed in.

**Comment by Charlie-Stuwart** [comment]
And if I close it and open it again, it will be named as the correct one
