### ISSUE TITLE
[Question] Is it possible to add debugging capabilities to other file types

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode#11566]
We have a VSCode extension for [Cake](http://cakebuild.net/) which extends VSCode with a few things, including snippets, commands, syntax highlighting etc.

We recently converted Cake to be built with .Net Core, which means that we have now been able to add debugging support within VSCode.  However, in order for this to work, we have to switch the configured language for the file, i.e. we have to change this:

![image](https://cloud.githubusercontent.com/assets/1271146/18263632/8300bad0-7403-11e6-83d0-6c234cf8bbe6.png)

To this:

![image](https://cloud.githubusercontent.com/assets/1271146/18263650/a1d36890-7403-11e6-9e85-983167e937b7.png)

via the dropdown list:

![image](https://cloud.githubusercontent.com/assets/1271146/18263641/94c8638a-7403-11e6-81ea-0931bda8d77c.png)

However, in doing that, we then lose the configured snippets that we have configured.  Is there a way to enable the debugging experience for files to type `.cake` without first needing to switch to the `C#` language?  Thanks!

**Comment by isidorn** [comment]
If I understand your question correctly, the only missing debugging experience for `.cake` files is that you can not set breakpoints inside them. If that is correct you just need to add contribute breakpoints for `cake` files in your `package.json`. Here is an example how node-debug extension does that for javascript files
https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L70

**Comment by gep13** [comment]
@isidorn that looks like exactly what we need.  Let me give that a try, thank you!

**Comment by gep13** [comment]
@isidorn is there any documentation around the configuration section that is being used in the example that you linked to?  All I can find is this:

https://code.visualstudio.com/docs/extensionAPI/extension-manifest

Which points here:

https://code.visualstudio.com/docs/extensionAPI/extension-points

But this don't mention anything about a `breakpoints` section. Thanks!

**Comment by isidorn** [comment]
@gep13 https://code.visualstudio.com/docs/extensions/example-debuggers
Unfortunently that document has an outdated way of contributing breakpoints, thus I created this issue https://github.com/Microsoft/vscode-docs/issues/559 which has more details / pointers which you can follow

**Comment by gep13** [comment]
@isidorn ah, perfect, thank you.

And just to confirm, where can I find a list of supported languages for breakpoints.  Specifically, I am interested in C#, but would be good to know where to find the list.  Thanks!

**Comment by isidorn** [comment]
@gep13 you can put any language you want in there. What is supported on a vscode instance depends on the extensions that are installed. E.g if you have the Go extension installed then you can add breakpoints in .go files.
However just adding those breakpoints in those files does not mean the brekapoints will get hit, for that you need a debug adapter that supports that language type.

More about languages https://code.visualstudio.com/docs/languages/overview
More about debug adapters  https://code.visualstudio.com/docs/extensionAPI/api-debugging

**Comment by gep13** [comment]
@isidorn ok, so if I have understood correctly, I shouldn't need to create a Debug Adapter, or anything like that, as C# debugging is already supported out of the box.  I know if I switch to C# (as per the screenshots at the top of this issue) I can switch to C#, add a breakpoint, and my `build.cake` file is then debuggable.  What I am trying to do is to miss out the step in which I have to switch to C# at the lower right hand corner, and instead, be able to do this when the `Cake Script` language is selected.

Based on what you have said above, I should simply be able to add the `breakpoints` section into the `contributes` section of the package.json file, and it should work, right?

And the remaining question is, is this:

```
	"contributes": {
        "breakpoints": [
		    {
			    "language": "csharp"
		    }
        ],
```

Or do I need something "other" for the name of the language? Thanks.

**Comment by isidorn** [comment]
Yous should put 'cake' there instead of csharp. That will allow you to add breakpoints in cake files. And the rest should hopefully be done by the C# extensions

**Comment by gep13** [comment]
>@isidorn said...
Yous should put 'cake' there instead of csharp. That will allow you to add breakpoints in cake files. And the rest should hopefully be done by the C# extensions

Doh! Now I get it! Thanks, that seems to be working now, thank you!
