### ISSUE TITLE
Emmet Abbreviation been suggested twice

### ISSUE THREAD

**Issue by MrAmericanMike** [microsoft/vscode#115623]
- VSCode Version: 1.52.1
- OS Version: Windows 7 Ultimate

Steps to Reproduce:

1. Create a new index.html file
2. Type `htm`

Does this issue occur when all extensions are disabled?: Yes

`html` Emmet Abbreviation comes up twice in the suggestions, both result in

```html
<html></html>
```
After invoking them.

**Comment by ArturoDent** [comment]
Verified in Insiders and Stable W10.  Oddly, for me typing the last `l` in `html` makes one of the `html` suggestions disappear.

**Comment by rzhao271** [comment]
\closedWith caca11f
