### ISSUE TITLE
Search should take precedence

### ISSUE THREAD

**Issue by u9520107** [microsoft/vscode#115675]
Issue Type: <b>Feature Request</b>

With the recent update, the search function is not a separate tab but part of the explorer.
However, in explorer, the folder structure pane and the open editors pane is usually expanded. In this case, search results will be covered up as the search pane will not expand and take over most of the space.

The search pane does not offer scrolling in this case either. I am basically being forced to close the folder structure pane in order to do searches.

I think I'd prefer either of the solutions:
1. Search pane should be able to expand to compress the folder structure pane, I am fine with needing to manually close search pane in order to use the folder structure pane.
2. Expand which ever pane that I click into. 

Apologies if there are duplicated issues on this already.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

**Comment by IllusionMH** [comment]
Can you please provide screenshot.
Also are you sure you haven't dragged Search to Explorer pane by accident? You should be able to drag it to panel or  action bar to make it separate.

![image](https://user-images.githubusercontent.com/1312662/106734825-24f3b180-661c-11eb-9194-a01aeed10260.png)
_(clean 1.52.1 installation)_

**Comment by JacksonKearl** [comment]
As @IllusionMH said it sounds like you've possibly dragged the search view out of its default location. You can right click on the header and select "Reset Location" to move it back. (or drag it back to the side bar)
![image](https://user-images.githubusercontent.com/8586769/106788787-4649a300-6606-11eb-8c06-a6602b094ad0.png)

**Comment by u9520107** [comment]
Whoah. I did not know that could be dragged around.
In that case, I am pretty sure the culprit would be my cat, threading on my touchpad.

Thanks @IllusionMH @JacksonKearl for the help!
