### ISSUE TITLE
[Feature] Ability to parse build.cake files to auto create task definitions

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode#11565]
I asked the question on Twitter:

https://twitter.com/gep13/status/772878923243876352

And @egamma replied to say that there wasn't currently any extension points to allow extensions to provide additional automatic task definitions.  Instead, that the only point where this was possible was contained within this file:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/common/taskTemplates.ts

So, my question is, would a PR to extend this file to recognise build.cake files be accepted if I were to create one?  Also, I am assuming that I would need to extend the codebase with the ability to parse the build.cake file, but after a quick glance at the code, I couldn't see where that happened, could someone point me in the right direction?  Thanks!

**Comment by dbaeumer** [comment]
@gep13 Instead of providing a PR to add this to taskTemplates.ts I would suggest to work on a PR to make this an extension point. Simply adding this to the core will not scale.

**Comment by gep13** [comment]
@dbaeumer agreed. My familiarity with the score base isn't that extensive though. Could you provide some pointers on where that work would be required, and suggestions on how to achieve it? Thanks!

**Comment by egamma** [comment]
Fully agree with @dbaeumer. 

Actually there are several feature similar feature requests for this: #966, #9309.

**Comment by gep13** [comment]
@egamma is this feature on the roadmap to be implemented by the team, or are you looking for an external contribution?  If an external contribution, would it be possible to get a "starter for 10" in terms of what is required in order to implement the feature?

**Comment by egamma** [comment]
@gep13 we are just planning the next 2 months, let me get back to you.

**Comment by gep13** [comment]
@egamma just wanted to follow up with this to see if there was an update. Thanks!

**Comment by egamma** [comment]
@gep13 the feature didn't make the cut for the September iteration, sorry.

**Comment by gep13** [comment]
>@egamma said...
@gep13 the feature didn't make the cut for the September iteration, sorry.

Thanks for getting back to me!

How close did it get? 😄 

Is this feature something that the Core VsCode Team will be looking to implement at "some" point though, or is it something that would be left for a community contribution?

**Comment by egamma** [comment]
@gep13 it is currently a candidate for October.

**Comment by gep13** [comment]
Perfect! Let us know if you want an extension to try out the new extensibility points in VsCode. Would be happy to help out.

**Comment by gep13** [comment]
@egamma how are you?  Just wanted to touch base on this one to see if it is still on the radar for October.  Thanks!

**Comment by dbaeumer** [comment]
@gep13  As it stands today this will not make it for October.

**Comment by gep13** [comment]
>@dbaeumer said...
As it stands today this will not make it for October.

That's a real shame 😭 I will check back next month.

Thanks for getting back to me though.

**Comment by gep13** [comment]
@dbaeumer @egamma following the 1.7.1, I thought I would follow up with this again.  Do you know if it is going to make the cut for the next release?  Thanks!

**Comment by gep13** [comment]
@dbaeumer @egamma just wanted to follow up again.  Thanks!

**Comment by dbaeumer** [comment]
@gep13: yes and no :-) I started https://github.com/Microsoft/vscode/issues/15179 to discuss how to continue with the task framework, especially around build. The current proposal is that we decouple build from tasks so that extensions can participate in building without providing a task. So for you that would mean that your extensions registers a build provider and can the execute build.cake files without hooking into the task framework. Would that help?

**Comment by gep13** [comment]
@dbaeumer thanks for getting back to me...

I am not sure if I follow the intention of that issue.  The feature request that I was looking for here was the ability for our Cake extension to "parse" the build.cake file within the currently open folder, and then allow the user to select one of the tasks that are located, by shelling out to the cake.exe.  Is what you are suggesting in #15179 the first step to implementing that, or how does that issue fit into this request.

Thanks!

**Comment by dbaeumer** [comment]
@gep13: the idea is that you don't need to provide a task to run a build.cake file. You will be able to participate in building (the Ctrl+Shift+B) command and your extension will shell out to cake.exe and do the correct thing.

We also want to move away from one central task file. If you want to provide users access to targets in cake file we are more imagining something like the https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script instead of mangling everything into tasks.

So the idea is also to move the built-in support for gulp into an extension.

**Comment by gep13** [comment]
>@dbaeumer said...
So the idea is also to move the built-in support for gulp into an extension.

Gotcha!  So, if/when gulp becomes an extension, we should be in a position to do this for Cake as well?  Do you have an eta on when that will be happening?

Thanks again!

**Comment by dbaeumer** [comment]
The work is planned for January next year. Ideas are collected in here  #15179

**Comment by gep13** [comment]
@dbaeumer perfect, I will follow along there.  Should this issue now be closed then?

**Comment by dbaeumer** [comment]
I will clean up the issues as soon as the new implementation is ready.

**Comment by gep13** [comment]
@dbaeumer @egamma I just wanted to follow up with this issue.  Given the recent changes to VsCode, are we now in a position to do what this issue was asking for?  i.e. the ability for an extension author to provide the ability to parse a file (in our case a .cake file) and then allow the execution of the tasks that are located within that file.  If so, could you point me at the documentation for this.

Thanks in advance.

**Comment by dbaeumer** [comment]
@gep13: unfortunately not. It is on the February iteration plan as a stretch goal. See https://github.com/Microsoft/vscode/issues/20021

**Comment by gep13** [comment]
@dbaeumer thank you for the update.  If it is a stretch task for February, does that mean if it doesn't appear then, that is will be available in the March update?

**Comment by dbaeumer** [comment]
@gep13. Yes, that is usually or goal.

**Comment by egamma** [comment]
@gep13 a fallback option for you is to implement a command that creates a 'task.json' from a cake file.

**Comment by gep13** [comment]
@dbaeumer @egamma just wanted to follow up with this issue to say that we now have something working:

![image](https://user-images.githubusercontent.com/1271146/28287381-60d396da-6b33-11e7-91b7-c92749be695f.png)

Which we will hopefully be shipping soon 😄
