### ISSUE TITLE
Syncing uninstallation of extension doesn't appear to work

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#115681]
Originally posted by @TylerLeonhardt

It seems to be very hard to properly uninstall an extension because of settings sync and the 1-many relationship of codespaces.

I have a my local dev env, and then a few codespaces. If I try uninstalling an extension in my local dev env and then move over to my codespace, it still has the extension installed and it appeared to sync it back and then it was back on my local dev env. I've had to uninstall the same extension numerous times.

Steps to repro:

1. Start a couple Codespaces
2. close out of your codespaces
3. open vscode local and install an extension (it works best if it's an extension pack like: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack)
4. Open the Codespaces and verify the sync happened on the remote side
5. Close all Codespaces tabs (but don't destroy them)
6. Uninstall the docs authoring pack locally
7. log in to your Codespaces and wait a bit... you should still see the docs authoring pack
8. uninstall the docs authoring pack in the Codespaces
9. close the codespaces
10. Check local and then also reopen the Codespaces

You should see the docs authoring pack still installed in Codespaces

**Comment by sandy081** [comment]
@TylerLeonhardt I followed above steps with 3 codespaces and at step 7 - I see that docs authoring pack is uninstalled from all codespaces. Would you like to try again and see if you can repro?

**Comment by TylerLeonhardt** [comment]
@sandy081 something still doesn't add up here.

> * Start a couple Codespaces
> * close out of your codespaces
> * open vscode local and install an extension (it works best if it's an extension pack like: https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack)
> * Open the Codespaces and verify the sync happened on the remote side

At this point, is the extension actually installed? Because I see "install in codespace" button. If I click that button and continue the steps:

> * Close all Codespaces tabs (but don't destroy them)
> * Uninstall the docs authoring pack locally
> * log in to your Codespaces and wait a bit... you should still see the docs authoring pack


I still see the docs authoring pack installed in the codespace. The good news is, if I uninstall it in the Codespace, it does seem to go away forever as expected... but I do wonder if it should have gone away when I uninstalled it locally.

**Comment by sandy081** [comment]
> At this point, is the extension actually installed? Because I see "install in codespace" button. If I click that button and continue the steps:

Yes, they are installed in codespaces for me - can you please make sure if you are syncing with same settings sync service in codespaces and local?

> I still see the docs authoring pack installed in the codespace. The good news is, if I uninstall it in the Codespace, it does seem to go away forever as expected... but I do wonder if it should have gone away when I uninstalled it locally.

This makes me believe more that codespaces and local are not syncing using same service. Hope I am not wrong.

**Comment by TylerLeonhardt** [comment]
> Yes, they are installed in codespaces for me - can you please make sure if you are syncing with same settings sync service in codespaces and local?

I'm pretty sure I am... but how can I check this?

**Comment by sandy081** [comment]
Please open Settings Sync log from output view and check the service that is being used - this is logged at the very beginning.

**Comment by TylerLeonhardt** [comment]
Looks like they're the same.

local: `[2021-03-01 19:12:57.003] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/`
codespaces: `[2021-03-01 19:12:57.003] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/`

I recorded a video for you:
https://msit.microsoftstream.com/video/970fa1ff-0400-85a8-697e-f1eb7b069f5c

As I interact with Settings Sync following the steps above.

**Comment by sandy081** [comment]
Sorry for the confusion - By codespaces I assumed it is web version on browser. Settings Sync in VS Code does not sync extensions in remote (WSL, DevContainer, SSH, Codespaces). Because Settings Sync is to sync user extensions and in VS Code user extensions are installed locally and remote is assumed to have workspace specific extensions (especially containers). It is not clear which is user extension and which is remote scoped extension. Hence they are not synced by default. There is an open request for this https://github.com/microsoft/vscode/issues/90968. 

Codespaces (web) is completely a different scenario as the codespace remote is the location for user installed extensions too. Hence remote extensions in codespaces in web are synced. 

Hence Marking this as duplicate of #90968
