### ISSUE TITLE
"X" close button | Reallocation

### ISSUE THREAD

**Issue by abelardolg** [microsoft/vscode#115787]
Issue Type: <b>Feature Request</b>

Hi there,

Most times I unintentionally close tabs when I click on them to change of file.

Could you place the "X" close button on the top of the tab instead?

Best regards.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-41-generic

**Comment by gjsjohnmurray** [comment]
I suggest you set `workbench.editor.tabCloseButton` to `off` and then use the context menu to close tabs instead.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for answering the question. Thus closing this
