### ISSUE TITLE
Command Pallete is empty while trying to select encoding or eol sequence

### ISSUE THREAD

**Issue by Andy-Amoy** [Microsoft/vscode#11576]
- VSCode Version: 1.4.0
- OS Version: Windows 7 SP1 X64
- Installed extension: donjayamanne.python;  gerane.Theme-TomorrowNight;  ms-vscode.cpptools;  ms-vscode.csharp;  ms-vscode.PowerShell;  msjsdiag.debugger-for-chrome;  robertohuertasm.vscode-icons

Steps to Reproduce:

Didn't do any think, just found that when I click the item at the right bottom, the table shows without any words or content, see the below screen capture:
![vscode_issue](https://cloud.githubusercontent.com/assets/13942826/18270897/e7c5a44a-7461-11e6-8c56-e5f8185d4cad.png)
I click the item in the red rectangle, and it didn't show any options in the command filed
1. 
2.

**Comment by ramya-rao-a** [comment]
@Andy-Amoy Can you provide more details?

- Which locale are you using?
- Do you see the issue on all file types or any particular ones?
- Do you see the issue on saved or unsaved files?
- Do you see the issue when the extensions are disabled? You can try this by running `code --disable-extensions` on the command line. This will open VS Code with the extensions disabled.

**Comment by Andy-Amoy** [comment]
1. My windows is zh-cn version, and this function works fine several days ago
2. All file types will hit this issue, I think. As I hit it via edit .h .cpp .txt .proto .py, but I didn't test more types
3. Both of them
4. I have disabled all of the extensions as your direction, still show nothing at this field. Even I uninstall all of the extensions, issue is here yet.
5. Aditional, the code is simplified chinese version

**Comment by ramya-rao-a** [comment]
@Andy-Amoy Just to rule out if the locale is causing the problem, can you try running vscode in another locale and see if you are still seeing issues? `code --locale=en-us` 
Adding @bpasero @aeschli @dbaeumer @alexandrudima for more insights

**Comment by bpasero** [comment]
@Andy-Amoy this is the vscode-icons extension. You will have to reinstall VS Code to work around the issue. vscode-icons is a dangerous extension which changes the installation bits. We do NOT recommend to use this extension (as for icons, we plan to support icons starting with our 1.5 release).

**Comment by ramya-rao-a** [comment]
@Andy-Amoy Can you confirm that reinstalling VS Code fixes the issue for you?

**Comment by ramya-rao-a** [comment]
@Andy-Amoy Closing this as resolved. If you still find the issue after reinstalling VS Code, then reopen this issue

**Comment by Andy-Amoy** [comment]
Hi Ramya, good news is that after reinstall VS Code, the issue is gone. If there is no more questions, I will close this ticket or you do it if convinient.

**Comment by ramya-rao-a** [comment]
@Andy-Amoy glad to know you are unblocked. I have closed this issue
