### ISSUE TITLE
Save dialog whilst open multiple tabs of the same file

### ISSUE THREAD

**Issue by Phisherman** [Microsoft/vscode#11577]
- VSCode Version: 1.4.0
- OS Version: Windows 10

If I have open multiple tabs of the same file and want to close one VS Code forces me with a modal to decide if I want to save the file. Wouldn't it be sufficient if it just asks if someone wants to close the last tab of this file?

See here:
![image](https://cloud.githubusercontent.com/assets/2873986/18271432/48759582-7432-11e6-94da-48c827c0295c.png)

**Comment by bpasero** [comment]
This has been fixed for 1.5

**Comment by Phisherman** [comment]
@bpasero I forgot to test it in the insider version. Sorry!
