### ISSUE TITLE
Adding code cell after non-runnable code cell creates a runnable cell

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#115773]
Issue Type: <b>Bug</b>

1. Create a notebook extension in which code cells are set runnable or not runnable when a notebook is opened, based on the language mode of the stored cells.
2. Click the +Code button after a non-runnable cell.
3. Observe that the new cell has the same language mode :+1: but it is runnable :-1:

VS Code version: Code - Insiders 1.53.0-insider (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:53:41.416Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
In contrast, `metadata,breakpointMargin` **does** get carried forward to the new code cell :+1:

**Comment by gjsjohnmurray** [comment]
Contrast this with what copy+paste does with metadata

https://github.com/microsoft/vscode/issues/103881#issuecomment-673752304

**Comment by roblourens** [comment]
I think this would have been based on the `cellRunnable` property and require the extension to jump in and fix up `runnable`, but all of this has been deleted and the runnability is now inferred based on kernel+language, so it should be good now.
