### ISSUE TITLE
More control/settings for how undo behaves when working in the context of the explorer

### ISSUE THREAD

**Issue by dnllowe** [microsoft/vscode#115750]
Issue Type: <b>Feature Request</b>

Hey,

I love Visual Studio Code. It's by far my favorite editor. However, there's a new (?) feature that's been giving me headaches recently. Maybe it's not new, but I've only noticed it disrupting my workflow recently.

### The problem
If I use undo while the context is the explorer, it will silently start removing and renaming files based on the last changes that occurred in the explorer. The problem is, I may have added files an hour ago, and could now be working on a new file and simply want to undo a typo in the new file (that just happened). But, if I'm accidentally in the explorer and hitting undo, it will silently start perma-deleting all my files. Once I realize what's going on, it may be too late to truly recover them. 

### How it affects one's workflow
It's hard to realize sometimes that the undo is happening in the file explorer, where there can be hundreds or thousands of files, silenting renaming or deleting themselves. When the undo action doesn't delete the latest typo in a file, it's easy to see why one would start spamming undo, only to realize later that they're making changes in the explorer.

### Solution
I'd like to have a setting that warns me (either every time, or only on the first delete/rename/restore) that I'm about to take an "undo" action in the Explorerer and not the currently or last opened file. If the context ever switches to a file, then I should be warned again when undo will affect the explorer--again, either for the first "new" explorer undo action, or only the first--until the context changes again.

I envision a simple dialogue box asking me to confirm.

Thanks

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-65-generic snap

**Comment by isidorn** [comment]
We have actually done this in the current January release and should be out in VS Code stable in a couple of days. We will ask for confirmation every time there is a destructive undo. Try it out and let me know how it goes.

**Comment by dnllowe** [comment]
Hah. You guys were already on top of it! Just got the update and tried it
out. It works just as expected--awesome.

Thanks

**Comment by isidorn** [comment]
Lovely, thanks for letting us know.
