### ISSUE TITLE
Some tokens are missing colorization with semantic tokens

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode#115786]
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.19042
- Full "About" text
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

## Steps to Reproduce:

1. Install Bicep extension (https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep) at version v0.2.328
1. Open a file named `main.bicep`, with the following contents:
    ```bicep
    resource foo 'Microsoft.SignalRService/signalR@2020-07-01-preview' = {
      name: 'foo'
      tags:{
        'foo': 'bar'
        'buz': 'bur'
      }
    }
    ```
1. 'bar' and 'bur' are showing in white with no colorization.
1. Note that this repros consistently on some installs of VSCode, but does not repro at all on other installs.

## Further info:

This has been reported by users of our extension under https://github.com/Azure/bicep/issues/1428, however when I open the same file, colorization is correct with the following build:
```
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

I've compared the language server semanticTokens data being sent, and it's identical between working and non-working systems. When we enable "Developer: Inspect Editor Tokens and Scopes", VSCode reports the correct color in the debug panel, yet this color is not displayed.

### Working:
![image](https://user-images.githubusercontent.com/38542602/106936115-2be8f580-66ea-11eb-842c-0f8e14f83670.png)
### Non-working (note the panel also reports `"foreground": "#ce9178"`):
![image](https://user-images.githubusercontent.com/38542602/106936227-52a72c00-66ea-11eb-94c9-bf2908094f48.png)

Does this issue occur when all extensions are disabled?: No

**Comment by anthony-c-martin** [comment]
It looks like the culprit may be the following setting:
```
"editor.renderWhitespace": "all"
```
If I enable that setting, I can repro the bad behavior. If I comment it out, I get the expected behavior.

**Comment by alexdima** [comment]
In this particular case, it looks like the semantic tokens returned by the semantic tokens provider are illegal:
Here is the raw response:
```
// deltaLine, deltaStart, length, tokenType, tokenModifiers
0 0  8  1 0
0 9  3 17 0
0 4 53  2 0
1 2  4 14 0
0 6  5  2 0
1 2  4 14 0
1 4  5  2 0
0 0  5  2 0
0 7  5  2 0
1 4  5  2 0
0 0  5  2 0
0 7  5  2 0
```

After decoding the positions and the token types:
```
1  1  8 keyword
1 10  3 variable
1 14 53 string
2  3  4 member
2  9  5 string
3  3  4 member
4  5  5 string
4  5  5 string // <--- duplicate of the previous token
4 12  5 string
5  5  5 string
5  5  5 string // <--- duplicate of the previous token
5 12  5 string
```

Notice how the token at (4,5) appears twice, just like the token at (5,5). 

I can look on our side to better recover from this, right now we have assumptions that semantic tokens are not overlapping.

**Comment by anthony-c-martin** [comment]
> In this particular case, it looks like the semantic tokens returned by the semantic tokens provider are illegal:

Thank you very much for this analysis, this does indeed look the cause of the problem! I'll update our code to ensure we don't do this.

**Comment by rzhao271** [comment]
I'm not getting syntax highlighting now, even though I have the extension installed and am on a Bicep file. Instead I get 'No grammar or semantic tokens available.'

![bicep-highlight-fail](https://user-images.githubusercontent.com/7199958/109233441-bcad7100-777e-11eb-9f9d-24cc7092977d.PNG)

Version : 1.54.0-insider (user setup)
Commit : 59c31364c707ee962cc594389966801af4ce69bd
Date : 2021-02-25T07:44:40.955Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

**Comment by alexdima** [comment]
@rzhao271 I have just tried again on a VS Code Insiders without any settings and this works fine for me. Did you perhaps turn off semantic highlighting or something?

![image](https://user-images.githubusercontent.com/5047891/109276420-478d7a80-7816-11eb-89c3-cc1b47dc12cb.png)
