### ISSUE TITLE
Integration tests: lots of ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115747]
When running integration tests (on macOS) I see tons of this output:

`ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete`

Disabling minimap in settings helps, so I will push that as a workaround.

**Comment by alexdima** [comment]
I have spent quite some time trying to understand this. I could reproduce by just replacing the entire minimap rendering code with the following:
```
const ctx = this._canvas.domNode.getContext('2d')!;
const tmpImageData = ctx.createImageData(this._canvas.domNode.width, this._canvas.domNode.height);
ctx.putImageData(tmpImageData, 0, 0);
```

I have added checks that the canvas element is in the dom when using `putImageData` and AFAICT I am doing everything OK. So it looks to me that this is an issue with Chromium itself that surfaces in the rapid case of creating the canvas, using `createImageData`, using `putImageData` and then removing the canvas from the DOM. We can continue with the workaround to disable minimap in integration tests.

**Comment by deepak1556** [comment]
Thanks for the minimal repro, I was able to verify the error is seen with electron nightly. Test used

```
for (let i = 0; i < 100; i++) {
  let canvas = document.createElement('canvas')
  document.body.appendChild(canvas)
  let ctx = canvas.getContext('2d')
  let tmpImageData = ctx.createImageData(200, 400);
  ctx.putImageData(tmpImageData, 0, 0);
  document.body.removeChild(canvas)
}
```

Similar issue https://bugs.chromium.org/p/chromium/issues/detail?id=1124738 , unless the error causes a visual regression or impacts the runtime, this won't get much attention in upstream.
