### ISSUE TITLE
VScode terminal (Shell) directory capitalization issue causing [HMR] bundle errors when building gatsby app

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#115705]
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a file directory open VSCode by typing "code ." in the terminal
2. Close VSCode and reopen

Does this issue occur when all extensions are disabled?: Yes

I'm building a Gatsby app and getting [HMR] bundle has # warnings with the message "There are multiple modules with names that only differ in casing."

The problem is that the terminal directory keeps outputting C:\Users\Jason\desktop\coding\website when the directory is "Desktop" "Coding" "Website" 

So, I can get rid of this warning messages and errors by cd .. multiple times to get to the user directory and enter manually with the capital letters for the directories and re-build the app.

But when I close the VSCode and relaunch it the terminal directory goes back to lower capitalization.

So I guess there are two bugs:

1. Not remembering the directory names with the capitalization.
2. Default directory path is not displaying the correct capitalization of the directories.

But if the #2 can be solved we can ignore number 1.

**Comment by hiredtocode** [comment]
Any updates on this issue would be appreciated =)

**Comment by yume-chan** [comment]
Duplicate of #98611

**Comment by hiredtocode** [comment]
Thank you @yume-chan I'll close this one since it's a duplicate.
