### ISSUE TITLE
Visual Studio Code for PWA with Native File System API

### ISSUE THREAD

**Issue by gnusiva** [microsoft/vscode#115754]
I would like to see my favorite code editor, ships online as PWA with native file system API. 
Refer: https://web.dev/file-system-access/

**Comment by yume-chan** [comment]
Code needs a backend to run, except file access, how does a PWA open terminals on your machine?

**Comment by gnusiva** [comment]
@yume-chan ya, that's correct. But let's not have a terminal feature. In my opinion, the terminal is nice to have only. As you stated, we can ship a lightweight electron app to bridge those gaps. And that should be kept optional.

**Comment by shd101wyy** [comment]
I am now trying to build an extension for vscode web that implements a FileSytemProvider using the Native File System API. However, it seems like I am not able to call `window.showDirectoryPicker` in my extension code, as I am assuming the extension is running as a javascript worker. It doesn't have access to the global `window` object. 
Does anyone have any idea how to solve this problem? I have thought about one solution that starts a webview and calls the `window.showDirectoryPicker` there then `postMessage` to communicate with the parent level FileSystemProvider. However, this way will always have a Webview tab panel open.

**Comment by shd101wyy** [comment]
@gnusiva Please check https://0xgg.io/vscode-web-with-native-filesystem/ that I built using https://github.com/Felx-B/vscode-web

You could run `NativeFS: Open Folder` to open a local folder :)

https://github.com/0xGG/vscode-web-with-native-filesystem
