### ISSUE TITLE
Help text decorator on untitled file

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#115767]
From https://github.com/microsoft/vscode/issues/114307#issuecomment-761973812, there is an idea for having a codelens/decorator as help text in an untitled file, similar to repl.it. From UX discussion, having a codelens above the first line that goes away when the user starts typing would shift the editor up. 

![image](https://user-images.githubusercontent.com/35271042/104872738-85d47780-5903-11eb-8782-d4c481addc5e.png)

Perhaps we could use a decorator instead. For the help text to be useful, it would have to guide the user to do an action. An example could be:

- Choose the language you want to code in -> user clicking on language would open up the Language Mode quick pick. 

Once the user does that, the help text could change to linking to snippets of code for that language, like the repl.it experience. To flesh this idea out some more, could we add hyperlinks in decorators? Could we add logic to have the decorator go away as the user starts typing?

**Comment by bpasero** [comment]
Isn't this a duplicate of https://github.com/microsoft/vscode/issues/114307 ?

**Comment by sana-ajani** [comment]
you're right, closing it in favor of https://github.com/microsoft/vscode/issues/114307
