### ISSUE TITLE
System becomes sluggish after open a folder that contains many files and subfolders

### ISSUE THREAD

**Issue by EugenWiens** [Microsoft/vscode#11570]
- VSCode Version: 1.4 and 1.3
- OS Version: Ubuntu 16.04 and Ubuntu 14.10

Steps to Reproduce:

1. Open a folder that contains many files and subfolders.
    In my case it is a Yocto Project Folder (https://www.yoctoproject.org/) containing 144987 directories and 1493109 files.
![image](https://cloud.githubusercontent.com/assets/7880602/18267271/9bd89eea-741e-11e6-8119-d27c3a276e47.png)

**Comment by ramya-rao-a** [comment]
@bpasero Can you clarify the performance expectations with this big a workspace?

**Comment by bpasero** [comment]
@EugenWiens can you try disabling the file watcher for this workspace to see if that helps:

```
"files.watcherExclude": {
   "**": true
}
```

**Comment by EugenWiens** [comment]
At first glance it looks good. I will test it further during my daily work and get back to you again after a week or so.

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/3998
