### ISSUE TITLE
Keep previous position when returning to the "Release Notes: ..." tab.

### ISSUE THREAD

**Issue by BluSpanner** [microsoft/vscode#115791]
Current behaviour: Moving away from the "Release Notes: ..." tab, the position is lost.

How to replicate.
Open the Release notes (eg. "Janurary 2021 (version 1.53)"
Click on another tab, to investigate the new feature
Return to the "Release Notes:..." tab
The position of the "Release Notes: ..." tab is reset to the top of the page.

Feature Request: Keep the current position when returning to the "Release Notes: ..." tab.

**Comment by gjsjohnmurray** [comment]
@mjbvz See also https://github.com/microsoft/vscode/issues/63690#issuecomment-611217316

A fix might encounter the same problem I had in my PR #85982, which was merged in 1.53. Noting the vertical scroll position (the fraction of the total height) when all images have loaded completely, then setting that scroll position before all images have fully reloaded will leave the document scrolled to the wrong position. My fix is imperfect (see PR comments).

**Comment by wendellhu95** [comment]
@mjbvz I am willing to fix this, provided that no one is working on it currently.

**Comment by radekwojpl2** [comment]
@wendellhu95 you are still working on this issue?

**Comment by mjbvz** [comment]
Already seems fixed in VS Code insiders
