### ISSUE TITLE
Regex find does not match on beginning and end of lines (missing multiline flag?)

### ISSUE THREAD

**Issue by erikbra** [Microsoft/vscode#11572]
- VSCode Version: 1.4.0
- OS Version: Windows

Steps to Reproduce:

1. Search for regex including beginning or end of line matches. Examples:
   * `^\s*$\n` (should match empty lines)
   * `^A.*B$` (should match every line starting with A and ending with B (e.g. `A****************B`)
2. Expected: match
3. Actual: No match.

Ref. issue #313, which is closed, but in essense the same, or at least very similar.

Esp. @alexandrudima 's comment, stating that this might be to a missing multiline flag passed to the Javascript regex engine.

https://github.com/Microsoft/vscode/issues/313#issuecomment-244772017

**Comment by erikbra** [comment]
This does not work as expected in September (insiders build).

`^\s*$\n` matches on end-of-every-line. Should only match empty lines. It says:

`^` - start of line
`\s*` - none or more whitespaces
`$` - end of line
\n - newline

`^\s*$\n` matches empty lines in all other regex editors (sublime, Visual studio, regex testers)
`^\s+$\n` matches empty lines. 

It looks as if `^\s*$\n` starts matching on the previous line (I can tell from looking at the highlights). So it's not respecting the `^`. See also #11575.

**Comment by sandy081** [comment]
@erikbra Thanks for reporting.. I will investigate this empty lines case.

**Comment by sandy081** [comment]
@erikbra You can use regex `^\s*$` also to match empty lines. 

Filed #13355 for this particular case.

**Comment by erikbra** [comment]
Hi.

Thanks for looking into this.

`^\s*$` does not do the trick. Instead of doing what I want. It only matches on the first occurence of empty lines. I don't really understand why, but that's what it does.

`^\s*$\n` does not seem to 
respect the `^`, as it seems to treat the newline on the previous line as part of the next line (see attached screenshot).

I have attached screenshots from another editor (Sublime, but this is common on all other regex-aware editors) which demonstrates the difference. 

Test text used:
```
søflkjasdlkfj

           asdølfnasdøfln   
dasfsadf

asdfasdfasdf


gasgasdgasdgasd
```

<img width="828" alt="newline-matches-non-empty-lines-also" src="https://cloud.githubusercontent.com/assets/1628994/19230089/bc3e10e2-8ed2-11e6-9778-fba79c29ad22.png">
<img width="828" alt="no-newline-matches-only-first" src="https://cloud.githubusercontent.com/assets/1628994/19230087/bc366b08-8ed2-11e6-87f5-e72baeeb6013.png">
<img width="810" alt="sublime-newline-matches-only-blank-lines-and-does-not-remove-initial-empties-on-next-line" src="https://cloud.githubusercontent.com/assets/1628994/19230086/bc35f6a0-8ed2-11e6-9206-15d029789812.png">
<img width="810" alt="sublime-no-newline-matches-also-blanks-in-next-line" src="https://cloud.githubusercontent.com/assets/1628994/19230088/bc37bbfc-8ed2-11e6-9654-5ac35d04dc78.png">

**Comment by erikbra** [comment]
Maybe this is the problem? Looks like you do some sort of single/multi-line optimization on regexes? https://github.com/Microsoft/vscode/issues/9051#issuecomment-231734302

**Comment by sandy081** [comment]
@erikbra I will have to check and confirm you. Thanks.
