### ISSUE TITLE
Distinguish between essential modal dialogs and popup notifications

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#115702]
Currently, the product does not distinguish between an essential modal dialog (e.g. a sign-in dialog, a trusted workspace dialog) and a non-essential pop-up (e.g. a recommendation to install a linter, a popup asking users to fill out a survey). 

If this distinction were possible, we would enable a wide range of new notification management features - office hours, snooze, turn of notifications by extension, turn off all non-essential notifications.  These changes could empower the user to drastically reduce the notification load in their workspace.

**Comment by bpasero** [comment]
@devinvalenciano just to clarify we know from the API wether an extension shows a modal dialog or a notification but we currently don't know if an extension shows a notification that is essential for the user to engage or just for information purposes. We have some heuristic by looking if any button is part of the toast, but it is not ideal.

I think extensions will have to move to our modal dialog API once we allow to snooze notifications.

**Comment by devinvalenciano** [comment]
@bpasero this is helpful context, thanks for sharing.  

Here are some possible options I see moving forward - 

1. We have three classes of notifications - modal dialogs, essential notifications, non-essential notifications.
2. As you mention, extensions could make use of the existing modal dialog API for essential notifications.
3. As you mention, we could look for interaction surfaces (e.g. buttons) to estimate whether a dialog is essential. 

Only option 3 would require no changes from the extensions themselves, but I'm not sure we could sufficiently detect essential dialogs from the data we have available today.  An example where this could get blurry - see the non-essential linter recommendation dialog, which requests input from the user.
![image](https://user-images.githubusercontent.com/1389808/106904858-88c7ba00-66b0-11eb-9a41-8b1d4fba5dee.png)

**Comment by devinvalenciano** [comment]
Is it possible to unify all of these concepts at a telemetry/API level?  Right now, we have a modal dialogs and notifications, and we're discussing the ability to differentiate between two types of notifications.  Within notifications, we have many different telemetry events.  Some examples, just for extension recommendation pop-ups:

"monacoworkbench/remoteextensionrecommendations:popup",
"monacoworkbench/terminallaunchrecommendation:popup",
"monacoworkbench/languagepacksuggestion:popup",
"monacoworkbench/extensionworkspacerecommendations:popup",
"monacoworkbench/fileextensionsuggestion:popup",
"monacoworkbench/extensionrecommendations:popup"

Would there be any benefits to consolidating these (plus any others out there) into two events?  One that fires when the notification is shown, and one that fires when the notification is interacted-with - regardless of what type of notification/dialog it is.  All of the other distinctions could be made in Properties.  See example schemas below:

"monacoworkbench/notificationshown" - Properties["type":"modaldialog", "purpose":"trustedworkspace", "id":"AAA"....]
"monacoworkbench/notificationshown" - Properties["type":"essential", "purpose":"extensionrec", "source":"fileextension", "id":"BBB"....]
"monacoworkbench/notificationshown" - Properties["type":"notification", "purpose":"extensionrec", "source":"config", "id":"CCC", "extension":"ms-vscode.ms-python"....]

"monacoworkbench/notificationinteraction" - Properties["action":"cancelled", "type":"modaldialog", "purpose":"trustedworkspace", "id":"AAA"....]
"monacoworkbench/notificationinteraction" - Properties["action":"install", "type":"essential", "purpose":"extensionrec", "source":"fileextension", "id":"BBB"....]
"monacoworkbench/notificationinteraction" - Properties["action":"show", "type":"notification", "purpose":"extensionrec", "source":"config", "id":"CCC", "extension":"ms-vscode.ms-python"....]

**Comment by bpasero** [comment]
Yes I think once there is central telemetry for notifications (and possibly dialogs?) I would not expect to have these telemetry events that are notification specific anymore.

I do not think we can detect "essential" notifications going forward. Extensions will be forced to use the modal dialog API for those that need immediate attention. Possibly with some new API for the user to "Do not show again" in case an extension is spamming.
