### ISSUE TITLE
VS Code Blank screen

### ISSUE THREAD

**Issue by KirilVelichkov** [Microsoft/vscode#11578]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. I dont know how you can re-produce it , because it happened out of nowhere.

Here are the errors in the console in devTools

loader.js:136Loading "vs/workbench/workbench.main" failedt @ loader.js:136
loader.js:137Detail:  Error: No define call received from module vs/workbench/workbench.main.(…)t @ loader.js:137
loader.js:139Error: No define call received from module vs/workbench/workbench.main.
    at e._onLoad (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:20081)
    at Object.callback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:25944)
    at e.triggerCallback (file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:27076)
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:26882
    at file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/loader.js:4:30131
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)t @ loader.js:139
loader.js:141Here are the modules that depend on it:t @ loader.js:141
loader.js:142Array[1]0: "===anonymous1==="length: 1__proto__: Array[0]t @ loader.js:142

I have tried  running  "code --disableExtensions" still not working. 
Please help :( I need my editor back.

**Comment by mrmlnc** [comment]
Have you tried reinstalling the editor?

**Comment by KirilVelichkov** [comment]
I have read all articles about this problem and everyone with the same issue have tried re-installing it , but that didnt fix the issue.
I have so many things already saved on the editor (extensions, snippets etc) that i really dont want to re-install it

**Comment by mrmlnc** [comment]
@KirilVelichkov, you used a **vscode-icons** extension?

**Comment by KirilVelichkov** [comment]
@mrmlnc , yes. I use this extension and it updates like 3 times a day ... :/

**Comment by mrmlnc** [comment]
@KirilVelichkov, Good news! Download **ZIP** archive:

https://code.visualstudio.com/?utm_expid=101350005-27.GqBWbOBuSRqlazQC_nNSRg.0#alt-downloads

Then unzip `VSCode-win32-stable.zip\resources\app\out\` directory to the `C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out` directory.

**Comment by KirilVelichkov** [comment]
@mrmlnc  YOU DA REAL MAN!

Thank you soooooo much. This fixed it.
I have delete my vscode-icons extension. Can I safely put it back , or was that causing the problem?

**Comment by mrmlnc** [comment]
@KirilVelichkov, 

Most likely **vscode-isons** incorrectly updated a files. You can use it, bearing in mind the described me method.

**Comment by ramya-rao-a** [comment]
Closing as issue is solved

**Comment by MehmetKaplan** [comment]
As a workaround, I have edited file /usr/share/applications/code.desktop

Replacing 
`Exec=/usr/share/code/code --unity-launch %U`
with
`Exec=/usr/share/code/code --disable-gpu --unity-launch %U`
solved my problem of launching code through launcher.

Just in case one may need...
