### ISSUE TITLE
Open Editors file list jump (autoscroll) after closing an editor

### ISSUE THREAD

**Issue by redtopia** [microsoft/vscode#115714]
When closing a tab, and your current editor is represented by a tab that's out of view, the tab bar will jump (auto-scroll) to reveal the tab for the current editor. This is a problematic behavior that also occurs when closing files found in the Open Editors pane.

A simple solution that I think will improve the UX would be to postpone the auto-scroll until after the user is no longer hovering over the tab bar (or the Open Editors pane). This would allow the user to close multiple tabs or editors without losing their place and having to scroll back.

**Comment by isidorn** [comment]
Assigning to @bpasero for the tab area
For the open editors to me - though we plan no changes there at the moment

**Comment by bpasero** [comment]
Tabs is covered with: https://github.com/microsoft/vscode/issues/40290

**Comment by redtopia** [comment]
#40290 doesn't seem to be the same issue. The issue I'm reporting is that in some cases, the entire tab bar auto-scrolls as soon as you close a tab, making it impossible to close a bunch of tabs without re-scrolling back to where you were. This happens if the current editor is represented by a tab that is out of the visible tab area.

**Comment by bpasero** [comment]
> as soon as you close a tab

So how do you close the tab and what do you expect?

**Comment by redtopia** [comment]
Let's say I am closing a bunch of editors because I just finished up some work. The current editor is represented by the far left tab. I scroll my tab bar over to the right, which reveals a bunch of tabs I want to close. The far left editor tab is no longer visible. I then close a tab and immediately the tab bar scrolls back to the far left to reveal the current editor's tab. Then I have to scroll all the way back to where I was in my tab bar to close the next window.

This same behavior can be seen in the Open Editors pane. If you scroll away from the current editor, and close a file in the list, the list will immediately scroll back to the reveal the current editor.

I realize that it's good to always show the current editor tab or open file. But this "always show" behavior can be postponed until after the user has moved their mouse out of the area where they are doing things. This way, I would be able to close a bunch of editors without having to keep scrolling between actions. 

FYI, there is a workaround that I've gotten used to using, which is to change your current editor to be in the same visible location of the tabs (or open editor items) where you're doing things. But, this is a PIA in most cases.

**Comment by bpasero** [comment]
@redtopia so how is https://github.com/microsoft/vscode/issues/40290 not relevant then that would make sure the tabs stay where they are for as long as the mouse is over tabs? I assume this is using mouse?

**Comment by redtopia** [comment]
@bpasero because #40290 has to do with keeping all the tabs the same size so you don't have to move your mouse when closing a bunch of adjacent tabs. This feature request has to do with not auto-scrolling the entire tab bar after closing a tab.

**Comment by redtopia** [comment]
Here's a screenshot of the behavior:

![screenshot](https://user-images.githubusercontent.com/812777/106932067-80817600-66d4-11eb-8b5f-3e060ff63e60.gif)

**Comment by bpasero** [comment]
@redtopia fair, I have opened a new issue just for tabs: https://github.com/microsoft/vscode/issues/116170

One thing that probably helps you is to configure `workbench.editor.focusRecentEditorAfterClose: false`

**Comment by redtopia** [comment]
Thanks @bpasero, that actually does help when closing an active tab, though it doesn't do anything with regard to this issue.

**Comment by redtopia** [comment]
I cannot understand why this issue would be closed. I run into this UX problem every single day in my workflow. Closing multiple editors is always a problem unless I pre-select an open editor that is in close proximity to the editors I want to close, and that only helps if the editors I want to close are grouped together. Why is nobody else complaining about this? Seems like a straightforward fix to postpone the auto-scrolling until after your mouse leaves either the tabs or the open editors pane.
