### ISSUE TITLE
Add setting to prevent closing the pinned tab when using middle click

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#115734]
I wanted to add this as a comment to #100738, but it's been locked.

A pinned tab cannot be closed with <kbd>ctrl + w</kbd>, but it can be closed with the mouse (middle click).

Please extend this behavior so the middle click cannot close a pinned tab?

**Comment by bpasero** [comment]
Setting is called `workbench.editor.preventPinnedEditorClose` and can be configured to block editor close for `mouse`, `keyboard`, `keyboardAndMouse` or `never`.

This change will actually also set `keyboardAndMouse` as the default, which means all users will see the behaviour of not being able to close a pinned tab with middle mouse click unless the setting is changed. Will see how many complaints we get.
