### ISSUE TITLE
Have Files Open with Double Click Rather than Single Click in VS Code

### ISSUE THREAD

**Issue by theodore-steiner** [microsoft/vscode#115755]
Apologies if this has been answered, but currently, the files I have listed in VS code on the left-hand navigation window open with a single click. Is there any way to change this to only open with a double-click?

**Comment by isidorn** [comment]
`"workbench.list.openMode": "doubleClick"`

**Comment by akislawek** [comment]
Is it possible to still have the preview mode working with files, when the "workbench.list.openMode" is set to "doubleClick"?

What I'm trying to achieve:
1) Single clicking on a file shows it's preview (so single clicking multiple files one after the other would use one tab)
2) Double clicking on a file would open the file in it's own tab (double clicking multiple files would open multiple tabs)
3) Single clicking a directory only selects the directory in the explorer.
4) Double clicking on a directory opens it.

Currently when I have "workbench.list.openMode" set to "singleClick" I have the preview functionality which I like for files, but when clicking on a directory, it opens and closes automatically (which is a pain when I try to copy/paste/move directories in my project structure). When I have the setting set to "doubleClick", the directories work like I want (so they don't open/close automatically), but then the preview of files does not work.

Ideal solution: add a different "opneMode" behaviour for directories and files.
