### ISSUE TITLE
Problem with "format document"

### ISSUE THREAD

**Issue by neoneeco74** [microsoft/vscode#115700]
Issue Type: <b>Bug</b>

Bonjour,

Il y a un probleme avec le click droit > mettre le document en forme (raccourcis : Maj Alt F). Je suis sur un fichier twig et lorsque je fais cette action, la mise en page tronque le document au bout de 118 lignes. C'est donc un bug assez genant.

Hello,

There is a problem with right click > format document (shortcuts: Shift Alt F). I am on a twig file and when I do this the layout truncates the document after 118 lines. So it's a pretty annoying bug.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (1.45GB free)|
|Process Argv|--crash-reporter-id 44e81c29-0c34-4984-8720-74f8b7d9298f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
vscode-sqlite|ale|0.11.1
vscode-intelephense-client|bme|1.6.3
apacheconf-snippets|eim|1.3.0
php-debug|fel|1.14.7
php-intellisense|fel|2.3.14
duplicate|gee|1.0.1
helium-icon-theme|hel|1.0.0
twig-language-2|mbl|0.9.2
php-namespace-resolver|Meh|1.1.8
vscode-language-pack-fr|MS-|1.52.2
mssql|ms-|1.10.1
material-theme|zhu|3.9.13

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by yume-chan** [comment]
The formatter for your twig files is provided by an extension (mblode.twig-language-2)

So please file an issue directly to the extension's issue tracker: https://github.com/mblode/vscode-twig-language-2/issues/new

**Comment by yume-chan** [comment]
The formatter for your twig files is provided by an extension (mblode.twig-language-2)

So please file an issue directly to the extension's issue tracker: https://github.com/mblode/vscode-twig-language-2/issues/new
