### ISSUE TITLE
Support different cursor style for multi cursors

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#115753]
When using multi cursor selection, sometimes only one is selection is visible and the other selections are off screen. If I leave the vscode for whatever reason and come back to it later, it is not immediately visible that there are multiple cursors, and once in a while I unintentionally change other parts of code. I would like to easily know there are more than one cursor even if only one is on screen.

**Comment by alexdima** [comment]
We already have indicators in the status bar and in the overview ruler:

![image](https://user-images.githubusercontent.com/5047891/107076519-d563e000-67eb-11eb-86ab-c6019c0741c4.png)

**Comment by alexdima** [comment]
Perhaps it would be helpful to see a small number next to each cursor or some kind of extra "bubble" at the top of the viewport "N cursors above" and at the bottom "M cursors below" in case there are off-screen cursors. cc @misolori

**Comment by a5hk** [comment]
Thanks. I had never noticed the indicator in statusbar, and only looked at the overview ruler when I was searching.

> Perhaps it would be helpful to see a small number next to each cursor or some kind of extra "bubble" at the top of the viewport "N cursors above" and at the bottom "M cursors below" in case there are off-screen cursors.

Or maybe a different color for cursor. This way the indicator is inside the main focus area.
