### ISSUE TITLE
Typo: Missing space in tool tip ("sync changes")

### ISSUE THREAD

**Issue by CWempe** [microsoft/vscode#115735]
- VSCode Version: 1.52.1
- OS Version: Windows 10

There is a space missing in the following Git status bar tool tip between "6" and "Änderungen synchronisieren" (Synchronize Changes).

![image](https://user-images.githubusercontent.com/1270359/106864499-3dbaa080-66ca-11eb-9245-f3135d1c0547.png)

Steps to Reproduce:

1. Open a Repository that has changes on remote
2. Move mouse over sync button to see tool tip
3. See tool tip

**Comment by eamodio** [comment]
@dbaeumer Where do we assign i18n issues like this?

**Comment by dbaeumer** [comment]
@nexue2020 is the new owner of i18n issues.

**Comment by CWempe** [comment]
I just realized this bug is a little different than I described first.

It looks like it always shows "6Änderungen". Even when there are 0 changes or mor than 6.
So maybe it is not supposed to show any number at all.

**Comment by sleeksorrow** [comment]
Oh god please..... This bug just caused me 60 minutes of searching and syncing and pruning to find those invisible 6 changes in my repositories until I realized that this "6" is just a typo in i18n...

**Comment by v-mholloway** [comment]
fix implemented - will take a few days to migrate into the next build

**Comment by v-mholloway** [comment]
fix should be in build now - closing
