### ISSUE TITLE
Disable "prompt to save untitled before run"

### ISSUE THREAD

**Issue by chrisduda** [microsoft/vscode#115785]
I just updated to 1.53.0 and use vscode for powershell.  It now requires me to save the file prior to running an untitled script.  Is there a way I can turn this off or disable it?  Sometimes I may just pop a few lines of code in the editor for a one-time use, I really don't want to have to save the file and then have to delete it afterwards.  Thanks.

Chris

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/114890
We will fix this milestone and next milestone you will be able to use it
