### ISSUE TITLE
Providing an interface to the issue duplicate detector

### ISSUE THREAD

**Issue by vonas** [microsoft/vscode#115711]
I just submitted issue #115710 which was a duplicate of an existing one. I did search in the large archive of issues beforehand but did not find anything, though I'll admit, I didn't search very well. I found it immediately after looking again.

Either way, I'd like to suggest a simple interface somewhere (perhaps on your website) to interface with the duplicate detection ([bot](https://github.com/microsoft/vscode/issues/115710#issuecomment-772774683)). This suggestion really relies on how others perceive this problem. I could imagine that after some more time and a huge archive of issues, this might become an attractive idea.

The reason I am suggesting this is, that it unnecessarily cost me some time to put together the issue description (and install VS Code Insiders) which I'd rather have saved (yes, I should have searched a little bit better). I'll just leave this suggestion here, and let it be victim of your opinions! :)

**Comment by JacksonKearl** [comment]
cc. @chrmarti who wrote that bot, do you think such an endpoint could exist?

**Comment by chrmarti** [comment]
The issue reporter (`Help` > `Report Issue`) uses a REST API to search for duplicates. That wouldn't be ready for heavier workloads than that at the moment.
