### ISSUE TITLE
DebugConfigurationProvider should support compound targets

### ISSUE THREAD

**Issue by karljs** [microsoft/vscode#115719]
Because compound targets are not debug `"configurations"`, but rather included separately under the `"compounds"` key in `launch.json`, it is not possible for a debugging extension to provide a compound configuration.  It should be possible, in some way, to dynamically provide a compound target.

There is an overlapping request from 3.5 years ago which was marked "out of scope" with no explanation:
https://github.com/microsoft/vscode/issues/37193

I am hoping that this can be re-evaluated now.

**Comment by alexweininger** [comment]
A way to dynamically resolve compound configurations based on the current debug configurations would be much appreciated. I would love to see `resolveCompoundConfiguration` and `provideCompoundConfigurations`.
