### ISSUE TITLE
git: can't commit without staging: 'test/test-ext-authprovider/' does not have a commit checked out

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#115757]
Version: 1.53.0-insider
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T15:54:10.467Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-41-generic

In the vscode repo,
- I make changes to a number of files
- In the SCM view, I click directly on the `Commit` button
- Strange error dialog shows up: `error: 'test/test-ext-authprovider/' does not have a commit checked out`
![image](https://user-images.githubusercontent.com/6461412/106904419-74f57580-66fb-11eb-96ec-4b41877106d4.png)

```
Using git 2.27.0 from git
...

> git add -A -- .
error: 'test/test-ext-authprovider/' does not have a commit checked out
fatal: adding files failed
> git fetch
```

I have set:
`"git.smartCommitChanges": "all"`

**Comment by eamodio** [comment]
@aeschli what is `test/test-ext-authprovider/`? Do you have something odd in your `.gitconfig` or in the `.git/config` file in the vscode repo?

**Comment by aeschli** [comment]
Looks like I have a folder `test/test-ext-authprovider` in my vscode repo folder.
How it got there I don't understand.
It only has empty folders in it so it doesn't show up as an outgoing change. But it still seems to block auto commit.

![image](https://user-images.githubusercontent.com/6461412/107363552-9c24bc00-6ada-11eb-9995-c6d846c74368.png)

**Comment by eamodio** [comment]
I can't reproduce this by creating empty folders like this. But the failure seems to be coming directly from git given your output:

```
> git add -A -- .
error: 'test/test-ext-authprovider/' does not have a commit checked out
fatal: adding files failed
```

So I don't think there is anything we can do here. Might be a bug in Git.
