### ISSUE TITLE
VS Code does not execute .zshrc when launching from UI

### ISSUE THREAD

**Issue by korstiaanS** [microsoft/vscode#115738]
- VSCode Version: 1.52.1
- OS Version: Big Sur 11.2

Hi,

If I launch VS Code from the UI it seems like it would not launch the .zshrc.
(as described in [https://github.com/microsoft/vscode/wiki/Resolving-Shell-Environment-is-Slow](url))
As a result if I then want to execute a task it won't work because of missing variables, path, ...

If I start VS Code from a terminal window via `code .` it works fine. Variables/path are taken over then.

Korstiaan

**Comment by fishnet37222** [comment]
I'm also seeing this issue on both Linux Mint and Arch Linux using Visual Studio Code Insider.

**Comment by masaki9** [comment]
I am also seeing this issue in 1.54.0 (Universal) and 1.54.0-insider (Universal) on my M1 Mac. As a workaround, I set "terminal.integrated.shell.osx" to "bin/bash" and created .bash_profile, but I would like to see this issue fixed and change it back to /bin/zsh which is the default shell in macOS.

**Comment by Tyriar** [comment]
Are you seeing the message in https://github.com/microsoft/vscode/wiki/Resolving-Shell-Environment-is-Slow?

**Comment by fishnet37222** [comment]
I do see that message.  I've attached my .zshrc file.  Nothing in that file should take long to load, since my terminal loads quickly.
[zshrc.txt](https://github.com/microsoft/vscode/files/6087371/zshrc.txt)

**Comment by Tyriar** [comment]
@fishnet37222 these ones stick out as might be taking a while:

```
source ~/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE}
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
```

I don't think there's anything we can do here, as I understand it that notification was added as a way to point out a problem on your end so we can avoid investigating slow launching VS Code. I'd recommend adding echo statements or something so you can measure how long it takes to identify if it is indeed an issue. More info on investigating it at the bottom of https://github.com/microsoft/vscode/wiki/Resolving-Shell-Environment-is-Slow
