### ISSUE TITLE
Notebook editors have an undefined viewColumn

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#115704]
- VSCode Version:  1.53.0-insider
- OS Version: Windows 10

The editors in the list of `vscode.window.visibleNotebookEditors` do not have a defined `viewColumn`. The cells included in the list of `vscode.window.visibleTextEditors` also have undefined view columns. Therefore, there is no way to figure out where the notebook is open for the user. This value should be defined.

![image](https://user-images.githubusercontent.com/22576531/106780275-acc9c380-65fc-11eb-95d3-2b0b960a4e62.png)

cc @daytonellwanger @rebornix

**Comment by jrieken** [comment]
YEs - this isn't implemented. Only the API has been spec'd for some reason

**Comment by jrieken** [comment]
This will be working in next insiders but we don't have the equivalent of `onDidChangeTextEditorViewColumn` and I am not yet planning on adding that
