### ISSUE TITLE
Windows: different zoom levels on different monitors fail to restore windows at correct location

### ISSUE THREAD

**Issue by bighammer** [microsoft/vscode#115768]
- VSCode Version:1.52.1
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
I have extension screens setup: 
- Main screen: laptop resolution 3840x2160 and enlarger text& application size to 200%
- extension screen 1: ultrawide screen 2516x1080, no enlargerment
- extension screen 2: nomral wide screen: 1920x1080, no enlargerment

and using FancyZones from PowerToys to manage my screens.
                 =================================

1.  put vscode in extension screen 1 or 2
2. Drag vscode window & press shift (shortcut of FancyZones) to put to a target sub-screen
2. close vs code, reopen it

Vscode window positon will not restore to the position where I closed it. In addtion, the vscode window size seems enlargered to 200%. My guess is vscode restores window size & position based the coordinator of main screen rather then the extension screen.
I am not sure it is vscode's bug or FancyZones messed up OS ( win10) ?
 
If I just put vscode in main screen or extension screens without using draging it to a subscreen, it works fine. 

=============================
I double checked. It seems nothing to do with FancyZones. If I put vscode in the certain postion in extension screen but close to main screen, the problem will happen. 

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by bpasero** [comment]
This sounds like an electron issue to me, esp. given the zoom factor.

**Comment by bpasero** [comment]
@bighammer to clarify:
* you have 3 monitors
* your primary is the most left one
* you start VSCode with exactly 1 window and move that to monitor 2
* you close VSCode
* you start VSCode

=> VSCode does not restore where you left it?

PS: please make sure to not use any third party tool at all, just move the window with the mouse if you must.

**Comment by bighammer** [comment]
@bpasero 
you have 3 monitors - Yes
your primary is the most left one - No. My primary is the bottom (monitor 1), monitor 3 is the middle, monitor 2 is the top. Monitor 3 is ultrawide 2516x1080. Monitor 2 is 1920x1080. Monitor 1 is laptop resolution 3840x2160 and enlarger text& application size to 200%

you start VSCode with exactly 1 window and move that to monitor 2 - It doesn't matter. If I put vscode in certain position & size, it happens.
you close VSCode
you start VSCode
=> VSCode does not restore where you left it? - Correct!

Please see the attached screen shot for more information.
One is the layout of my monitors. The other is positon in monitor 3 where it causes issue.

![monitor2 vscode position where it causes issue](https://user-images.githubusercontent.com/3233391/106948677-f7674f00-6766-11eb-9ae0-1ea2b585ed24.png)
![monitors layout](https://user-images.githubusercontent.com/3233391/106948688-fa623f80-6766-11eb-95f9-4f2feec19b52.png)

**Comment by bpasero** [comment]
@bighammer any chance this reproduces with just 2 monitors as well? I will have a hard time setting up your setup from home...

**Comment by bighammer** [comment]
@bpasero Of cuz.
I tried this: without the top monitor, just laptop + ultrawide monitor.  The same issue. 
It seems vscode retores to the wrong coordinators (and window size) when it is reopened.

**Comment by bpasero** [comment]
Thanks, more questions: when you temporarily disable the extra 200% zoom on the one monitor, does that help? Trying to figure out if the zooming is the origin of this problem.

**Comment by bighammer** [comment]
@bpasero It IS 200% zoom causes the problem. It goes away, when I change 200% to 100%.  In my case, I can work this around by changing the 200% zoom.  The laptop resolution is 3840x2160 with limited screen size. It has to be change to 200% or more.

**Comment by bpasero** [comment]
Ok thanks, I will try to see if I can reproduce this, but I suspect a bug in Electron (= upstream).

**Comment by bpasero** [comment]
Opening for help wanted, as I do not have a good windows setup with multiple monitors right now. If someone wants to chime in with this setup (Windows, 2 monitors, 1 with zoom to 200%) willing to help, a good start to figure out what goes wrong is here:

https://github.com/microsoft/vscode/blob/5c330b06d4df1e2c7b17b629b7b31df4b85efea5/src/vs/platform/windows/electron-main/window.ts#L133

Either the state from the previous session is already wrong or we fail to restore it properly.

**Comment by bpasero** [comment]
Reported as upstream: https://github.com/electron/electron/issues/29605 as I was able to reproduce easily when snapping the window to the right of the second monitor.

**Comment by u84six** [comment]
I've updated #131098  with details of the scale settings on monitor 1 (250%)

**Comment by u84six** [comment]
> Reported as upstream: [electron/electron#29605](https://github.com/electron/electron/issues/29605) as I was able to reproduce easily when snapping the window to the right of the second monitor.

Did you ever find a work-around for this other than having to change the scale? Is there some way with the way electron works where I can force the default location of where the window opens? This is a really annoying problem, because when it opens between monitors, it's trick to even move it to one or the other.

**Comment by amunger** [comment]
this seems to be fixed for me on insiders after the electron update

**Comment by h-h-h-h** [comment]
> Nice, anyone else able to confirm? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

Before I posted my issue #144227, I tested whether the problem also happens with the insiders build and it did.

**Comment by bpasero** [comment]
Insiders is back to Electron 13 for a moment, so hold your breath until we resume Electron 16.

**Comment by bpasero** [comment]
I have a feeling that @gjsjohnmurray fix in https://github.com/microsoft/vscode/pull/155589 would fix this as well, 🤞 should validate once insiders is out end of week.

**Comment by alexr00** [comment]
I can repro some non-restoring behavior with 1 monitor at 250% and the other at 100% with stable, but I can't repro with insiders. Verified.
