### ISSUE TITLE
Integration tests: should not profile unresponsive extension host

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#115748]
I ran the colorizer extension integration tests on macOS locally and was surprised to see this message:

```
UNRESPONSIVE extension host, 'vscode.vscode-colorize-tests' took 96% of 75.458ms, saved PROFILE here: 'file:///var/folders/fv/p__j7gw9097crr40g7sf2pxw0000gn/T/exthost-eca7f7.cpuprofile' [
  { id: 'program', total: 2208, percentage: 3 },
  { id: 'self', total: 292, percentage: 0 },
  { id: 'vscode.git', total: 125, percentage: 0 },
  { id: 'vscode.vscode-colorize-tests', total: 72792, percentage: 96 }
]
```

I think creating a CPU profile from an integration test run should be avoided, especially when we run tests in a build machine and not when triggered from an extension test.

**Comment by jrieken** [comment]
> I think creating a CPU profile from an integration test run should be avoided, 

I would disagree. Profiling comes at almost no cost and writing a temp file also isn't bad. Assiging to @aeschli for why the extension host blocks (profiling is started when the extension host gives dark for a couple of seconds)

**Comment by aeschli** [comment]
The profile is triggered when running the test: `  ✓ colorize: test-92369.cpp (12325ms)` (for #92369)
It's only only a 'near freeze' with the process spending it's time in native oniguruma code (I assume)

@alexr00 To decide if action is needed.

**Comment by alexr00** [comment]
That test causes a known near freeze, and the purpose of the test is make sure that it doesn't actually freeze. 

It is expected that most users don't have C++ code that has causes a near freeze, but if they do, the grammar shouldn't cause a full freeze.
