### ISSUE TITLE
vscode can't show colorpicker for colors

### ISSUE THREAD

**Issue by wekin** [microsoft/vscode#115737]
version:1.52.1
![image](https://user-images.githubusercontent.com/12882708/106869202-9d38a080-670a-11eb-8c02-1f661ebe71dd.png)

color not highlight and don't show colorpicker when hover

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill issue template properly with required info (better just copy data from built-in issue reported).

What king of file it is - regular CSS or some other kind?
