### ISSUE TITLE
Re: Action in explorer is interrupted shortly after creating a folder (#111652)

### ISSUE THREAD

**Issue by DominikSerafin** [microsoft/vscode#115725]
- VSCode:
  - Version: 1.52.1
  - Electron: 9.3.5
  - Chrome: 83.0.4103.122
  - Node.js: 12.14.1
  - V8: 8.3.110.13-electron.0
- OS:
  - Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Copy & paste the file in the explorer
2. Quickly rename the new file (e.g. via F2 key on Windows)
3. The rename action gets interrupted 

https://user-images.githubusercontent.com/7447244/106829922-5f496700-668d-11eb-8f1d-c56fca9d043d.mp4

This is duplicate of #111652 - which was closed & conversation was limited to collaborators, so I couldn't reply there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please either test with Insiders or wait for 1.53 to land. It will be out very soon.

/duplicate
