### ISSUE TITLE
Problems with html:5 snippet

### ISSUE THREAD

**Issue by sarahdialmeida** [microsoft/vscode#115709]
I´m trying to use the html:5 snippet on my project but is not working. Normally, when I type html on vsCode´s editor, the html:5 auto completes with:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
</body>
</html>
```
I´ve been looking on internet and asked for help in a frontend forum and in a group, but all ideas and suggestions failed:
- disable all vscode’s extensions
- check if VsCode is updated
- created a new repository

I created a new index.html file on an old project to check if it´s working and yes it works! So, I suppose it´s something related to VsCode´s config. Does anyone have any suggestions? :blush:

**Comment by rzhao271** [comment]
What was previously happening? For example, was it not expanding, or were the suggestions not popping up?

**Comment by sarahdialmeida** [comment]
Hi there. I found the solution for this issue. The snippet window was
minimized. Many thanks for your help anyway!!

S.

Em qui., 4 de fev. de 2021 às 13:59, Raymond Zhao <notifications@github.com>
escreveu:
