### ISSUE TITLE
[VCQ][DevDiv_VSO][VSCode][Ambiguity - &&&&]

### ISSUE THREAD

**Issue by danyeh** [microsoft/vscode#115777]
<table style="border-collapse:collapse;width:631pt;" width=841>
<tbody>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>MS PM</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703>Daniel Ye</td>
 </tr>
<tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>MOR PM</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703>Jan Baltus (Moravia IT)</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>String Resource ID</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border-top:none;border-right:0.5pt solid windowtext;border-bottom:0.5pt solid windowtext;border-left:0.5pt solid windowtext;border:1px solid #d4d4d4;border-left:none;width:527pt;" width=703>0; &quot;src/vs/workbench/contrib/debug/browser/debugViewlet.miToggleDebugConsole&quot;</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=80><strong>Source String</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>De&amp;&amp;&amp;&amp;bug Console</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Subtenant</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>VSCode</td>
 </tr>
<tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Source Control Link</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Filename</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>vscode-workbench\vs_workbench_contrib_debug.xlf</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=40><strong>Question</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703>Would you please check &quot;&amp;&amp;&amp;&amp;&quot; is a set of mnemonics according to the instruction, so it should not be treated the same way as hot keys? Also, please note I placed it at the front to keep consistency with other strings of the same kind:

0; &quot;src/vs/workbench/contrib/debug/browser/breakpointsView.miFunctionBreakpoint&quot;
0; &quot;src/vs/workbench/contrib/debug/browser/debugEditorActions.miConditionalBreakpoint&quot;
0; &quot;src/vs/workbench/contrib/debug/browser/debugEditorActions.miLogPoint&quot;
0; &quot;src/vs/workbench/contrib/debug/browser/debugEditorActions.miToggleBreakpoint&quot;
0; &quot;src/vs/workbench/contrib/debug/browser/debugViewlet.miOpenConfigurations&quot;</td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#9bc2e6;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=20><strong>Additional details</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr>
 <tr>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;vertical-align:top;border:0.5pt solid windowtext;background:#ffc000;border:1px solid #d4d4d4;border-top:none;width:104pt;" width=138 height=60><strong>Core Team Response</strong></td>
  <td style="color:black;font-size:11pt;font-family:Calibri, sans-serif;vertical-align:bottom;border:none;text-align:left;vertical-align:top;border:0.5pt solid windowtext;border:1px solid #d4d4d4;border-top:none;border-left:none;width:527pt;" width=703></td>
 </tr></tbody>
 </table>

**Comment by isidorn** [comment]
Yes `&&` specifies a mnemonic. I am not sure where Jan Baltus found `&&&&`? So it should only be two `&` characters.
I am not sure what placing in front means, but they should remain at the same letter so the mnemonic on windows gets rendered below that letter - that is a hot key that needs to be pressed for the command to be executed.
