### ISSUE TITLE
Allow to close a window opened from "code --wait" from the terminal

### ISSUE THREAD

**Issue by felipenmoura** [microsoft/vscode#115728]
Hi.
It's possible to open new instances of vscode from terminal (CLI) commands.
I managed to spawn it using node spawn, for example. It works perfectly.
But then, it's impossible to close it!

They only way I almost did it was by using `code -s ./ |grep -i "name-of-project-or-directory-opened"` to get the PID and then, killing it with `kill -9 {pid}`. But even then, it shows an alert saying it "crashed".

For example, if I start it in terminal with `code ./` I can't just hit `ctrl+c` to end it.
Even spawned processes in node will have a PID but, when I try to kill them, either nothing happens or it shows me a message that this pid does not exist.

By the way, I understood that `-w or --wait` could do the trick, but it will only wait if you don't open with files.
For example:
```sh
code -w # works. It keeps running in the terminal
```

```sh
code -w ./ # does not work. It ends and vscode opens up normally.
```

Is there a way I can start code from terminal, and close (that instance of) code from terminal as well?

Thanks.

**Comment by bpasero** [comment]
I think this is not a good idea, being able to kill the process from the command line would prevent to do a normal shutdown and thus could lead into data loss or other bad things to happen.

**Comment by felipenmoura** [comment]
Yes, I agree. But shouldn't it work at least when we send the SIGTERM signal?
Or maybe there could be some other way to tell vscode via CLI to close itself the right way.

**Comment by bpasero** [comment]
Yeah maybe with `--wait` we could have something given that the CLI works when you use it. Leaving up as feature request.
