### ISSUE TITLE
[Extension Dev] No type definition for vscode.authentication.logout

### ISSUE THREAD

**Issue by SrBrahma** [microsoft/vscode#115761]
- VSCode Version: 1.52.1
- OS Version:

@types/vscode = 1.52.0

Steps to Reproduce:

1. vscode-pull-request-github extension uses `vscode.authentication.logout('github', this._sessionId);` (https://github.com/microsoft/vscode-pull-request-github/blob/master/src/github/credentials.ts) to logout from the vscode auth, however, this function isn't defined in current @types/vscode.

Does this issue occur when all extensions are disabled?: Yes

Edit: Read my comment below.

**Comment by gjsjohnmurray** [comment]
I think it is still only proposed API

**Comment by SrBrahma** [comment]
> I think it is still only proposed API

Yeah, looks like.

However, I am not being able to use the logout() as the vscode-pull-request-github does, nothing happens. My package.json includes ` "enableProposedApi": true` as they do. My engine version is set higher than their published version one.

**Comment by SrBrahma** [comment]
@RMacfarlane sorry for the question, but, do you have any information about when the `authentication.logout()` will be available?

**Comment by RMacfarlane** [comment]
The current plan is to deprecate this API, since logging out is centralized under the accounts menu. What was your intended use case for it?

**Comment by SrBrahma** [comment]
I see and now understand the main objective with the account system. I was somewhat mistaken.

My extension still uses an OAuth system to login to the GitHub. The user can simply logout and login with another account with it. But, makes total sense to now use directly the VsCode account as a "Single source of truth" to handle the extension current account. It's different from what I was thinking, but also seems a good philosophy.

I was a little afraid due to security reasons, as another physical person could access a logged VsCode and read/write the previous user repos. But, actually and currently, this is already doable by just using a logged VsCode without any extension.

For now I think it's ok, then. I haven't touched my extension for like 2 months so I may have forgot any special usage/case.

I will close this issue, and if I remember or think about anything related, I will open another one mentioning this one. Thanks, @RMacfarlane!

**Comment by SrBrahma** [comment]
Btw, this is my extension: https://marketplace.visualstudio.com/items?itemName=henriqueBruno.github-repository-manager&ssr=false

I am aware that eventually VsCode will have similar functionalities, as it is already slowly doing for some months.
