### ISSUE TITLE
Add an option to disable passing Git credential from local to container

### ISSUE THREAD

**Issue by zhanzhenzhen** [microsoft/vscode#115723]
Sometimes we want to use the extension "Remote - Containers" to test untrusted code that may be harmful to our local environment. But Git in the container always has the ability to read all our private repositories on GitHub without entering the password, just like in local environment. If the container has harmful code, it can do all `git` operations so it's like there's no isolation. Could you consider adding an option to disable passing Git credential from local to container, so the container is more isolated?

**Comment by eamodio** [comment]
@chrmarti what would need to happen to support this?

**Comment by zhanzhenzhen** [comment]
Hi, I think the remote container extension already has this feature, but maybe it has a bug, so credential is still copied. I created an issue there:
https://github.com/microsoft/vscode-remote-release/issues/4426

**Comment by chrmarti** [comment]
Continuing the discussion there.

@eamodio I suggest to close this issue in favor of the other.

**Comment by eamodio** [comment]
Sounds good , closing.
