### ISSUE TITLE
Would love to be able to change the color of editor tabs

### ISSUE THREAD

**Issue by mdiehlenator** [microsoft/vscode#115792]
Issue Type: <b>Feature Request</b>

I would love to be able to change either/both the foreground and background of the edit tabs at the top of VS Code.

This would allow me to set my code files in red, my template files in blue, and my css files in green, for example.

The file-type icons are a start, but this would be much nicer.

Thanks for considering.

Mike 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.4.0-64-generic

**Comment by isidorn** [comment]
You can change the colors for all editor tabs via color customisations
Open the settings json file and do some color customisations as you prefer
``
"workbench.colorCustomizations": {
        "tab.activeBackground": "#ff0000"
    }
```

However changing colors per file type is currently not possible, thus forwarding to @bpasero as a feature request

**Comment by af4jm** [comment]
on a related note, with the new tab highlighting, files with changes are yellow & files with issues are also yellow... there should be a difference (I'm using the VSCode standard dark theme)
