### ISSUE TITLE
Tooltip not show when hover codelens

### ISSUE THREAD

**Issue by TAUnionOtto** [microsoft/vscode#115732]
- VSCode Version: 1.52.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Open [codelens-sample of vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/tree/master/codelens-sample)
2. Run `yarn && yarn watch`，then press `F5` to run extension
3. Open any folder with some code.
4. Wait code lens show, then hover one of codelens.

Actual Result:

![image](https://user-images.githubusercontent.com/7018688/106855951-b7698300-66f8-11eb-825d-d39a26409a05.png)

Is this an expected behavior of vscode extension?

Or is there any configation to show it?

**Comment by isidorn** [comment]
I believe this is expected behavior, however forwarding to @jrieken so he can close

**Comment by jrieken** [comment]
Yes. @TAUnionOtto what tooltip to you expect when hovering over a code lens?

**Comment by TAUnionOtto** [comment]
> Yes. @TAUnionOtto what tooltip to you expect when hovering over a code lens?

As [the code](https://github.com/microsoft/vscode-extension-samples/blob/master/codelens-sample/src/CodelensProvider.ts#L46), show `Tooltip provided by sample extension` maybe suitable I think. @jrieken

**Comment by jrieken** [comment]
Ah, I see. That actually makes sense and would be a simple change

**Comment by hantatsang** [comment]
@jrieken I'm looking at contributing to this though I'm fairly new to the vscode repo and having trouble understand how to attach the hover event listener for the code lens feature. Do you mind pointing me to an example in the codebase for doing that?

**Comment by spetrescu** [comment]
Can I take a look at this issue and try to work on this?

**Comment by jrieken** [comment]
This is where the dom-nodes for codelens are created: https://github.com/microsoft/vscode/blob/6260e655bc606e204ad51ce5b1cb34216cd36dd3/src/vs/editor/contrib/codelens/codelensWidget.ts#L91. Using  the title attribute on them should do the job

**Comment by spetrescu** [comment]
Is the native tooltip sufficient for the fix? @jrieken 

#### Before fix
Windows & MacOS
:-------------------------:
<img src="https://user-images.githubusercontent.com/60047427/110217775-a27e3c00-7ebe-11eb-886b-6efb423eaadd.png" width="400">


#### After fix
Windows | MacOS
:-------------------------:|:-------------------------:
<img src="https://user-images.githubusercontent.com/60047427/110217933-8f1fa080-7ebf-11eb-9dcc-ddd7d78078fe.jpeg" width="400"> |  <img src="https://user-images.githubusercontent.com/60047427/110174344-af405880-7e08-11eb-8c75-aeadae7d3656.png" width="400">
