### ISSUE TITLE
Theme switches to Dark+ when zooming in

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#115740]
This issue happens to me about once a month:

1. Zoom in

🐛 VS Code theme changes to Dark+

---

As I open new windows, they still show the correct original theme I have in my settings:
![image (3)](https://user-images.githubusercontent.com/22350/106879342-e0096280-668f-11eb-97bf-fe252ab59a6a.png)

![image (4)](https://user-images.githubusercontent.com/22350/106879344-e0a1f900-668f-11eb-9b60-39205ab43217.png)

---

I have a feeling this happens only if I Zoom In right after Alt-Tabbing to VS Code. Since Settings Sync runs when focusing VS Code and zoom level is a setting, I wonder if there's some conflict going on? I wonder too why all other settings appear unchanged though... I really only see a theme change.

cc @bpasero, @aeschli

**Comment by sandy081** [comment]
> Since Settings Sync runs when focusing VS Code and zoom level is a setting, I wonder if there's some conflict going on? 

Settings sync ignores zoom level setting during sync, so I doubt if there is a conflict.

**Comment by joaomoreno** [comment]
Debugging with @aeschli we found out that when the issue occurs, there's a configuration change event reporting a **lot** of affected keys. @sandy081 Let's debug this together next week.

![image](https://user-images.githubusercontent.com/22350/107035596-41ebca00-676d-11eb-9a10-54b15e0c6fe7.png)

**Comment by sandy081** [comment]
Cool.. lets debug together.

**Comment by sandy081** [comment]
As discussed, provided tactical/practical fix 

>  if the file appears empty, wait 20ms and try again, repeat 5 times
