### ISSUE TITLE
Persist user choice in Find options (case, whole word, regex) in the Find widget in editor

### ISSUE THREAD

**Issue by peterbourgon** [Microsoft/vscode#11574]
- VSCode Version: 1.4.0
- OS Version: Mac OS El Capitan 10.11.4

Steps to Reproduce:
1. Open VS Code and some file
2. Cmd+F to find something
3. Check the box to enable case-sensitivity and regex searching
4. Close VS Code
5. Open VS Code and some file again
6. Cmd+F to find something

Expected behavior: the boxes for case-sensitivity and regex searching are checked.

Actual behavior: the boxes for case-sensitivity and regex searching are unchecked.

I _always_ want to search with these options enabled. How can I persist this state across restarts?

**Comment by ramya-rao-a** [comment]
@jrieken The `Find` options are persisted for text search across files after restarting VS Code but not for test search in a file

**Comment by alexandrudima** [comment]
Let's track in #10344 we should add a configuration option where you could specify the default toggle states.

**Comment by ramya-rao-a** [comment]
I'd prefer we persisted user choice (notepad++, sublime and Visual Studio do persist user choice) rather than set configuration option explicitly. This way text search inside a file and across files would be consistent too.

**Comment by alexandrudima** [comment]
@ramya-rao-a I haven't noticed Visual Studio persisting the user choice. Same as we, they have a find widget for each editor (so if you open multiple editors side-by-side they each get their find widget). What would we persist if we have multiple find widgets that have different toggles?

**Comment by peterbourgon** [comment]
@alexandrudima Last writer wins? Honestly that's an edge condition, any decision is fine.

**Comment by alexandrudima** [comment]
That works for me. I will do the following:
* anytime a find widget toggle is changed, I will persist it (last one wins)
* when the workbench starts up, I will read the persisted values and start with those by default.

**Comment by rwatts3** [comment]
Any updates on this matter ?

**Comment by ryanwinchester** [comment]
Trying out vscode after hearing much hype, and this is my biggest issue in adopting it.

I use (cmd+d) multiple cursors a lot, and having to do cmd+f and toggling case-sensitive every time I open an editor is a pain in the rear-end.

**Comment by peterbourgon** [comment]
Still annoyed by this on a daily basis as well :)

**Comment by rebornix** [comment]
Let's track the setting persistence in #6158
