### ISSUE TITLE
Improve extension engine compatibility

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11573]
Currently, an extension is deemed **outdated** when there's a newer version published in the Marketplace. Installing an extension requires `O(published_versions)` request roundtrips: starting from the latest version, the engine field is checked for compatibility with the current Code, and it goes on backwards from there.

We should:

- [x] Publish extensions with the compatibility value as a property
- [x] Use that property to figure out which version to install
- [x] Use that property to correctly figure out whether the extension is outdated

--

VSIX manifest format:

```
<Properties>
      <Property Id="abc" Value="def" />
      <Property Id="ghi" Value="jkl" />
</Properties>
```

Response:

```json
"version": "0.1.15",
              "flags": "validated",
              "lastUpdated": "2016-09-06T04:41:03.74Z",
              "properties": [
                {
                  "key": "abc",
                  "value": "def"
                },
                {
                  "key": "ghi",
                  "value": "jkl"
                }
]
```

**Comment by joaomoreno** [comment]
@rebornix just hit the bug that this will fix: an extension which has a new version published, which isn't compatible with the user's version of Code, always appears out of date in the product.

**Comment by daviwil** [comment]
I wonder if this explains what @gerane was seeing in issue #12281?

**Comment by joaomoreno** [comment]
Probably not, since this is about update notifications.

**Comment by gerane** [comment]
Not sure. My issue is that code is not able to connect some of my installed extensions to to the ones in the marketplace any longer. I don't get update notifications for them, but not sure if those mechanisms are linked in anyway.

Also, I'm pretty sure this issue was introduced a while ago, but it's not an easy one to catch.

**Comment by sandy081** [comment]
Outdated check for an extension is done as follows:

If the extension has defined engine property in the VSIX manifest, it is used to check its compatibility. Otherwise falls back to old way.
