### ISSUE TITLE
tasks.json npm script does not work with arguments since 1.53

### ISSUE THREAD

**Issue by xmedeko** [microsoft/vscode#115876]
- VSCode Version: 1.53.0
- OS Version: Windows 10

Steps to Reproduce:

I have a npm task (`tasks.json`): 
```json
{
    "label": "test:web current file",
    "type": "npm",
    "script": "test:web -- suites=\"${relativeFileDirname}/${fileBasenameNoExtension}\"",
}
```
It has been working fine until I have upgraded to 1.53. Since then, I got error:
```
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run 'test:web -- suites="tests\dir\File"'" terminated with exit code: 1.
```

Seems to me v1.53 has added shell escaping. So, how I can add arguments to a task npm?

Also, I am miss information about additional npm tasks properties in 
* https://code.visualstudio.com/docs/editor/tasks 
* https://code.visualstudio.com/docs/editor/tasks-appendix

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
I didn't realize users were adding args to npm tasks in `tasks.json`. Looks like the only way to support npm scripts with spaces and npm scripts with args is to add support for the --.

**Comment by xmedeko** [comment]
@alexr00 Or, support `args` property and join the result properly: `npm run script -- arg1 arg2 ...`

**Comment by xmedeko** [comment]
@alexr00 You have probably forgotten your older comment with a npm script params  https://github.com/microsoft/vscode/issues/82626#issuecomment-544420713 😉

**Comment by alexr00** [comment]
Indeed, I had forgotten that, thank you. Since this used to work and now does not, I'd like to fix it.

**Comment by xmedeko** [comment]
@alexr00 Is your commit a4a6607ceb047abef8b51c7307a428997f0a1d64 working for  #113750 particularly for the `"[test] unit --watch"` script name?

**Comment by alexr00** [comment]
No. As a user you can either have the old behavior where we support arguments, or you can have the new behavior where script names have spaces.

**Comment by xmedeko** [comment]
I am happy with the "old behavior where we support arguments". You should ask @jonamat if he is happy with breaking #113750 

That's why I have proposed to add `args` instead (working with other task types already). Or maybe some explicit flag to switch the behavior - not to relay on the presence of `--` in the `script` param. These automagic behaviour changes may be very confusing when not documented. (I have pointed lack of documentation before). So, if you want it keep it this way, it would be helpful to improve the documentation.

**Comment by xmedeko** [comment]
I have converted type `npm` to `shell`:
```json
{
    "label": "test:web current file",
    "type": "shell",
    "command": "test:web",
    "argv": [ "test:web", "--", "suites=\"${relativeFileDirname}/${fileBasenameNoExtension}\"" ]
}
```
And it does the jobs well. IMHO either type `script` is redundant, or it should behave similarly to the type `shell` (i.e. user `argv` array).

**Comment by alexr00** [comment]
The fix for this bug allows the following:
- You can have an npm script where the script name has spaces (the feature request of https://github.com/microsoft/vscode/issues/113750)
OR
- You can use `--` in your npm script in tasks.json to pass argument to your script.

The fix for this bug _does not_ allow you have a task that uses an npm script with a space and the `--`. Certainly having an `args` property would be better. But this is a case of something worked by happy accident (allowing arguments in npm scripts) and now we would prefer not to break the users who depend on it.

**Comment by xmedeko** [comment]
OK, just such automagic behaviour may be very confusing when not documented. Please, document the `type: npm` and the `script` property:

https://code.visualstudio.com/docs/editor/tasks - _For a custom task, this can either be `shell` or `process`._ - No `npm` there, no doc for `script`, etc.
https://code.visualstudio.com/docs/editor/tasks-appendix - _type: 'shell' | 'process';_  - No `npm` there, no doc for `script`, etc.

It's difficult to find what's a proper behaviour and what is a bug without doc.
