### ISSUE TITLE
No save

### ISSUE THREAD

**Issue by guedo** [microsoft/vscode#115816]
Hello everyone,
I am on macOS Mojave version 10.14.6 with a MacBook Pro
So my problem is that the scripts aren't saving, not matter how I save them. I tried with "cmd + s", file > save and closing Visual Studio and when the message "Would you like to save scripts?" I press on "save and quit" but it would just close without saving. 
...".

I didn't change anything in the settings or somewhere else. 

The problem began today.

Hoping someone could help me,

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled? There is a Command Palette item to do that.

If this fixes the problem, reload with extensions enabled, then use the Bisect command to find out which extension is causing it.
