### ISSUE TITLE
can not change font size

### ISSUE THREAD

**Issue by abrarlabib-code** [microsoft/vscode#115870]
Issue Type: <b>Bug</b>

I am tring to change font size if editor but it is not working. It has mistakenly been small but when I am tring to increase the size it is not working.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.68GB free)|
|Process Argv|--crash-reporter-id 5aa0725c-63c4-4c24-8b0e-ef14eae126ea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
android-dev-ext|ade|1.3.2
kivy-vscode|Bat|0.5.5
vscode-html-css|ecm|1.9.1
vscode-firefox-debug|fir|2.9.1
kite|kit|0.136.0
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
LiveServer|rit|5.6.1
commandlist|yam|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment]
This works just fine for me
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
