### ISSUE TITLE
Hang on Windows 10 under VSCode debugger when executing the example code.

### ISSUE THREAD

**Issue by SteveShe** [Microsoft/vscode#11582]
- VSCode Version: 1.4.0
- OS Version: Windows 10586.545
The script below should execute and terminate naturally, as it does from a command prompt. Under the VSCode debugger, it executes and then sits in the debugger.

Steps to Reproduce:
1. Install Nodejs (4.5.0 or 6.5.0): https://nodejs.org/en/
2. Install Tedious: http://tediousjs.github.io/tedious/installation.html
3. Create an Azure database. 
4. Execute the following script.

```javascript
var Connection = require('tedious').Connection;

var config = {  
    userName: 'user',  
    password: 'password',  
    server: 'server001.database.windows.net',  
    options: {encrypt: true, database: 'db001'}  
}

var connection = new Connection(config);
connection.on('error', function(err) {  
    if (err) {  
        console.log(err);
    }else {  
        console.log("Error called with no err object.");
    }  
});
// connection.on('debug', function(messagetext) {  
//     if (messagetext) {  
//         console.log('debugtext: ' + messagetext);
//     }else {  
//         console.log("Debug called with no messagetext object.");
//     }  
// });  
connection.on('connect', function(err) {
// If no error, then good to go...
    executeStatement();
    return;
}
);

var Request = require('tedious').Request;

  function executeStatement() {
    request = new Request("select 42, 'hello world'", function(err, rowCount) {
      if (err) {
        console.log(err);
      } else {
        console.log(rowCount + ' rows');
      }
      console.log('About to call connection.close().');      
      connection.close();
      console.log('Called connection.close().');
    });

    request.on('row', function(columns) {
      columns.forEach(function(column) {
        console.log(column.value);
      });
    });

    connection.execSql(request);
  }
```

**Comment by ramya-rao-a** [comment]
This is not specific to the example code in question. A simple node app with a `console.log('hello world');` behaves the same way. From a terminal, this would print `hello world` and terminate. In debug mode, it prints `hello world` and waits. Any particular reasoning behind this? @weinand @isidorn

**Comment by weinand** [comment]
This is a long-standing node bug: https://github.com/nodejs/node/issues/1788

It is independent from VS Code and you can reproduce it by running the 'hello world' oneliner from the command line with `node --debug hello.js`
