### ISSUE TITLE
Quick fixes popup: up arrow doesn't go to bottom

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#115875]
In most popup lists / right-click menus, I can press the **Up** arrow (`↑`) to jump to the **bottom** of the list. For example:

1. Right-click in the SCM view:

<img width="312" alt="Screen Shot 2021-02-05 at 14 22 18" src="https://user-images.githubusercontent.com/101152/107038982-9cad1200-67bd-11eb-8cb7-6ac9a15db701.png">

2. Press the `↑` arrow:

<img width="312" alt="Screen Shot 2021-02-05 at 14 22 23" src="https://user-images.githubusercontent.com/101152/107038996-a2a2f300-67bd-11eb-816c-e6018dd52df1.png">

This works in most places but it doesn't work in the (quick) Fixes popup (`Cmd-.`):
 
1. Press the `Cmd-.` or click the small overlay icon:

<img width="282" alt="Screen Shot 2021-02-05 at 14 24 34" src="https://user-images.githubusercontent.com/101152/107039277-f57caa80-67bd-11eb-8ed6-f57811d41124.png">

2. Press the  `↑` arrow, observe that it _doesn't_ go to the bottom of the list.

Being able to go to the bottom of the list quickly is a nice usability feature and it would be great to have it in the fix list as well.

**UPDATE**: I've just realized that the crux of the issue might be that in quick fix lists, **the first item is pre-selected** (unlike in SCM view or the Explorer). That's probably what prevents the ability to jump to the bottom.

Maybe there's a UX reason why the first item is preselected in quick fix? It's true that I can just hit Enter to accept the first suggestion, but it also prevents going to the bottom.

**Comment by mjbvz** [comment]
As you noted, this is because we preselect the first item so you can easily apply it. This is more important than being able to use the up arrow to jump to the bottom of the list

**Comment by borekb** [comment]
@mjbvz Thanks for confirming. I reported this because I use "Fix all auto-fixable problems" most of the time and the sequence of `Cmd-.`, `↓`, `↓`, `↓`, ..., `↓`, `Enter` was becoming annoying.

However, I just realize that "Fix all auto-fixable problems" is a top-level command contributed by ESLint so all is fine.
