### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by Leogarcru** [microsoft/vscode#115823]
Issue Type: <b>Bug</b>

The last update causes a bug with an extension called Live Server and now its imposible to access from another device to the server created with that extension. but Also it needs to be changed the default port because it cant even be used at the localhost with the default settings
Please help to correct that issue

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (5.12GB free)|
|Process Argv|--crash-reporter-id db31573b-8fbf-453b-b26c-dbed5a7c1a0d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2711)|
|Memory (System)|9.24GB (8.72GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-edge-devtools|ms-|1.1.3
remote-wsl|ms-|0.53.2
debugger-for-edge|msj|1.0.15
material-icon-theme|PKi|4.5.0
ayu|tea|0.20.1
rainbow-brackets|2gu|0.0.6
path-intellisense|chr|2.3.0
codestream|Cod|10.4.2
prettier-vscode|esb|5.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the extension author. Ideally add a link here to the issue that you open there.
