### ISSUE TITLE
Big Sur Icon

### ISSUE THREAD

**Issue by gusgrassi** [microsoft/vscode#115893]
Issue Type: <b>Feature Request</b>

Hey guys! I know this is not important at all, but it would be nice you update VSCode icon so it matches Big Sur icons style. This shouldn't take you that much work ;)

I love this app!!

Gustavo.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

**Comment by misolori** [comment]
Thanks, we have already have an issue tracking this, please subscribe to https://github.com/microsoft/vscode/issues/101014
