### ISSUE TITLE
Extension host terminated unexpectedly (since updating to 1.53.0)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#115859]
- VSCode Version: 1.53.0
- OS Version: MacOS 10.15.7

Sorry if this has already been reported.
Since updating to v1.53 all extensions crash on save. 

Steps to Reproduce:
1. Make a change in some code
2. Hit Save

Notification:
![image](https://user-images.githubusercontent.com/936006/107027825-92cae500-67a4-11eb-8d40-dfaf7486aa58.png)

Dev Tools
![image](https://user-images.githubusercontent.com/936006/107027754-80e94200-67a4-11eb-92bf-5f0daa4600da.png)

**Comment by gjsjohnmurray** [comment]
Please use the Bisect command to discover which extension is causing the crash. If you find one, report the issue on its repo and close this issue.

**Comment by jasonwilliams** [comment]
Thanks for the suggestion!
"Extension Bisect is done and has identified liximomo.sftp as the extension causing the problem."

It seems the problem is https://github.com/liximomo/vscode-sftp/issues/881
