### ISSUE TITLE
Broken menu system on Linux

### ISSUE THREAD

**Issue by thanhle-phd** [microsoft/vscode#115800]
- VSCode Version: 1.53
- OS Version: Debian Buster 10

Steps to Reproduce:

1. apt-get update then apt-get install code
2. run code, check the file menu, all menu items are improperly displayed. 

Does this issue occur when all extensions are disabled?: Yes

ps- This problem happens when upgrading to VSCode Version: 1.53
to fix: Settings / window: Title Bar Style : custom

**Comment by gjsjohnmurray** [comment]
Are you able to paste a screenshot here to show what you mean by "improperly displayed"?

**Comment by thanhle-phd** [comment]
> 
> 
> Are you able to paste a screenshot here to show what you mean by "improperly displayed"?

Yes, please see attached.
![errmenu](https://user-images.githubusercontent.com/36068736/107001249-2ae1b380-673e-11eb-896b-84ae2538fd45.jpg)

**Comment by deepak1556** [comment]
Does it happen when you run with `--disable-gpu` ?

**Comment by thanhle-phd** [comment]
> 
> 
> Does it happen when you run with `--disable-gpu` ?

Yes, it still does the same.

**Comment by deepak1556** [comment]
Can you install https://www.electronjs.org/fiddle and check the menus on the app ?

Native menus rendering are controlled by electron, unless it can be repro'd in a minimal electron app there is nothing further actionable here.

Does it render fine when you have the following setting `"window.titleBarStyle": "custom"` ?

**Comment by thanhle-phd** [comment]
> Can you install https://www.electronjs.org/fiddle and check the menus on the app ?
> 
> Native menus rendering are controlled by electron, unless it can be repro'd in a minimal electron app there is nothing further actionable here.
> 
> Does it render fine when you have the following setting `"window.titleBarStyle": "custom"` ?

electron fiddle has the same problem. setting titlebarstyle to custom fixes the problem.

Thanks,

**Comment by rerdavies** [comment]
@Deepak: There absolutely *IS* something actionable to do. YOU need to report the issue to Electron, not us, because YOU need to ensure that this issue closes when (and not before) upstream fixes are incorporated into VSCode. We can't do that.

**Comment by rerdavies** [comment]
The actual workaround, correctly described:

1. Select File/ {references > Settings.

2. Select the Window tab.

3. Scroll down to find "Title Bar Style", and set it to custom.

**Comment by thanhle-phd** [comment]
FYI- This problem may happen again when opening a new vscode instance (new window). I fixed this by:
1. Go to vscode settings
2. Under Window: New Window Demensions, select inherit
