### ISSUE TITLE
IME ON at Alt+` key, Focus ALT Menu

### ISSUE THREAD

**Issue by tatosan924812** [microsoft/vscode#115810]
Issue Type: <b>Bug</b>

at version 1.53.
I using USKeybord. When press Alt+` key to change IME mode at editor or find box, keybord focus move to menu bar.

If key press slow, is not focus menu. but when normaly speed, move focus menu.

I rollback to 1.52.1, here is no problem.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3599)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.79GB free)|
|Process Argv|--crash-reporter-id 9d38bd2d-0e0c-4eb8-81b0-d07fb55194e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|12.1.4
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer|Coe|1.0.61
smarty|imp|0.3.0
svn-scm|joh|2.13.5
php-cs-fixer|jun|0.1.158
vscode-language-pack-ja|MS-|1.53.2
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by alexdima** [comment]
@tatosan924812 What keyboard layout are you using?

**Comment by sbatten** [comment]
I have the root cause and fix, this is related to our modifier key event listener
