### ISSUE TITLE
"CXABI_1.3.9 not found" in 1.53.0 (CentOS 7)

### ISSUE THREAD

**Issue by RudiFueller** [microsoft/vscode#115871]
- VSCode Version: 1.53.0
- OS Version:CentOS 7

Steps to Reproduce:

1. yum update code
2. open code
3. View -> Terminal

Error message occurs: "The terminal process failed to launch. A native exception occurred during launch (/lib64/libstdc++.so.6: Version 'CXXABI_1.3.9' not found (required by /us/share/code/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node))."

I downgraded to 1.52.1, all is fine again.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Byarlant** [comment]
I have the same problem when I run code --list-extensions from the terminal.

OS Version: Linux x64 3.16.0-11-amd64 (debian jessie)
