### ISSUE TITLE
Tabs: hovering over file symbol or git state of a tab doesn't show git status in the title

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vscode#115858]
- VSCode Version: 1.53.0
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. edit a file in a git repo
2. save it
3. hover over its tab title (notice git status e.g. "modified")
4. hover over the file icon or the "M" batch and see the error

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Do you have this setting?
```
"workbench.editor.tabSizing": "shrink"
```

For me this prevents the decoration badges from displaying despite my setting `"workbench.editor.decorations.badges": true`

I think this is a bug. If not, the description of `workbench.editor.decorations.badges` should state that it is incompatible with shrink tabsizing.

**Comment by Thomas1664** [comment]
> Do you have this setting?
> 
> ```
> "workbench.editor.tabSizing": "shrink"
> ```

No. I use `fit`.

I can confirm your issue and think hiding the badge when `workbench.editor.tabSizing` is set to `shrink` is intentional because it doesn't fit in. However, you can use `workbench.editor.decorations.colors` in that case.

**Comment by gjsjohnmurray** [comment]
@Thomas1664 so with `fit`, plus `badges` true, you get the "M", correct? Please clarify what you mean by "see the error". Maybe paste screenshots here.

**Comment by Thomas1664** [comment]
I can't capture the title on hover. It disappears when I try to record a screenshot. 
Hovering over the file name in the tab: path/to/file modified
Hovering over the file icon/badge: path/to/file

Notice the different content of the `title` attribute of the container and the tab title elements:
![image](https://user-images.githubusercontent.com/46387399/107031975-53f05b80-67b3-11eb-9179-1d5c76f84dc2.png)

**Comment by gjsjohnmurray** [comment]
Yes, that's what I see too.

tip: Windows Snipping Tool lets you set a delay of up to 5 seconds before the capture happens.

cc @jrieken who implemented this in PR #111222 and can say whether or not it is as designed.

**Comment by jrieken** [comment]
It doesn't do that anywhere, not in the explorer, scm-view, etc. I think the confusing part is that the tab provides a tooltip which then see instead.

**Comment by rodchristoffersen** [comment]
Hi thomas, this issue is one I am having difficulties with as well. I will see if I can resolve it by other means and talk to you soon, Rod PS: your name is the same as my mothers maiden name, funny
