### ISSUE TITLE
Seeing a single space inserted at the end of strings when editing HTML/JS files

### ISSUE THREAD

**Issue by rykr** [Microsoft/vscode#11584]
- VSCode Version: Code - Insiders 1.5.0-insider (d2c04e3789757413ae1ebfda9d88896686b6d006, 2016-09-01T06:10:12.264Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1.  Edit HTML file (JS block)
2.  Have some strings in the JS block, edit the string.  Hit save.  Seeing in many cases a single space inserted at the end of the all the strings in the file (which can break the JS)

**Comment by ramya-rao-a** [comment]
@rykr I was not able to repro this. Can you share a screen cast/gif of your steps?

**Comment by rykr** [comment]
At a soccer game. I'll try when I get back

**Comment by rykr** [comment]
Here is a video.  It appears to be one of my extensions that is causing it. Not sure which one.

[Bug.zip](https://github.com/Microsoft/vscode/files/458134/Bug.zip)

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
