### ISSUE TITLE
Index all files in open folders for intellisense

### ISSUE THREAD

**Issue by finger563** [Microsoft/vscode#1158]
Perhaps there's already a way to force, this but none that I've found.  I'd really like to get intellisense code-completion, and since I'm opening the folders which contain all the relevant code I'd like to be able to use those files for this feature.  

Alternatively, I'd like to be able to reference local modules (in the case of node.js) by relative or absolute path, as opposed to having just a few presets that I can choose from in the jsconfig.json file.  

If there's a better way to get code-completion for javascript code in VSC then please let me know :)

**Comment by iamzhout** [comment]
Also hope this feature being added, refer to below screen capture of Atom after adding a new directory into it.

![screencap_20160111-093707](https://cloud.githubusercontent.com/assets/14846203/12225590/c3993ac6-b848-11e5-9e22-f4e147dde55e.png)

Without indexing, the ```ctrl + p``` will be really slow for large projects.

**Comment by blopez2010** [comment]
Any news about this feature? Thanks!

**Comment by hksoul909** [comment]
I'm in for this feature. This is the feature that keep me from switching to VScode from Sublime 3. I want to have a quick way to jump to all function definitions across all source files in my javascript project folder.

**Comment by ryanellis** [comment]
Like @hungkhuu said... I want to drop Sublime for good and go VSCode all the way! This is the only feature stopping me

**Comment by mjbvz** [comment]
Try creating a [jsconfig.json](https://code.visualstudio.com/docs/languages/javascript#_javascript-project-jsconfigjson) file at the root of your project with the contents:

```json
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ]
}
```

This tells VS Code to treat all js files in the workspace as part of the same project. This will ensure that workspace symbol search returns results from these as well

Closing this issue as file indexing itself is an implementation detail. Creating a jsconfig is the recommended way to achieve what file indexing does in other editors
