### ISSUE TITLE
Detecting Extensionless C++ Headers

### ISSUE THREAD

**Issue by cpsauer** [microsoft/vscode#115826]
C++ libraries have an unfortunate convention of creating headers without extensions. 

VSCode then doesn't detect those headers are C++, breaking tooling. It's be awesome if VSCode could perform some simple heuristics to detect those extensionless headers as being in the C language family.

More details:
- Examples of extensionless headers: 
  - Think the standard library's `<iostream>`. 
  - Another good example I just ran into is Eigen, a popular linear algebra library. An example header would be "Eigen/Dense".
- Some STL implementations already work because VSCode detects a magic comment (see https://github.com/microsoft/vscode/issues/23873), but many headers, like Eigen's, don't have such a magic comment.
- The reason this is a bummer for usability is that it stops tooling for C++ from being automatically applied to the file.
  - Manually telling VSCode to mark the file as C++ by clicking in the lower right does seem to fix the issue, but it'd be nice if it happened automatically. 
  - Even just marking no-extension headers that contain #include or #if at the start of a line would do the trick--and be a better default than plain text!
  - I'd originally brought this up wrt the clangd plugin (https://github.com/clangd/vscode-clangd/issues/139). While they have a bit more information about the include graph with which to infer headers, I now think this is more properly handled at the VSCode level. Other C++ extensions would have the same issue, I imagine. Looks like the Microsoft C++ extension ran into it, too.

Thank you for your consideration and a most incredible piece of software!

**Comment by yume-chan** [comment]
Since #23873 and #1800 have been resolved, I believe now it's the extension authors' responsibility to implement any algorithm they need to detect file types. (the [Modelines](https://marketplace.visualstudio.com/items?itemName=chrislajoie.vscode-modelines) extension does this, as mentioned in your linked issues)

A large portion of Code users don't code in C++ and won't want every file they opened to be checked for C++ syntax.

**Comment by cpsauer** [comment]
Ah! My apologies. If that's indeed general enough to check more than modlines, let's close this down.

**Comment by yume-chan** [comment]
Yes, #1800 added a [`vscode.languages.setTextDocumentLanguage`](https://code.visualstudio.com/api/references/vscode-api#languages.setTextDocumentLanguage) API to let extension switch editor language mode dynamically.

Extensions can scan each opened file, detect their types, and call this API to tell Code the correct language. A quick glance of how [Modelines](https://marketplace.visualstudio.com/items?itemName=chrislajoie.vscode-modelines) does this:

https://github.com/ctlajoie/vscode-modelines/blob/b7b20dde15f3ab57c11c044f76366a49f18f5bd9/src/modelines.ts#L188-L215

```ts
export function applyModelines(editor: vscode.TextEditor|undefined): void {
	if (!editor || !editor.document || editor.document.isUntitled)
		return;
	try {
		let searcher = new ModelineSearcher(editor.document);
		let options = searcher.getModelineOptions();
		console.log('[modelines] setting editor options: ' + JSON.stringify(options));
		let language = translateLanguageName(options.language);
		if (options.language)
			delete options.language;


		extend(editor.options, options);
		// assignment is necessary to trigger the change
		editor.options = editor.options;


		if (language && language.length > 0) {
			vscode.languages.getLanguages().then(codelangs => {
				let codelang = codelangs.find(codelang => codelang.toLowerCase() === language.toLowerCase());
				if (codelang) {
					console.log('[modelines] setting language to '+codelang);
					vscode.languages.setTextDocumentLanguage(editor.document, codelang);
				}
			});
		}
	} catch (err) {
		console.error(err);
	}
}
```

**Comment by DBJDBJ** [comment]
"... A large portion of Code users don't code in C++ and won't want every file they opened to be checked for C++ syntax...." 

A few C/C++ lucky ones can use the ever-excellent (and free) Visual Studio.

VSCode is slowly but surely approaching a point of implosion due to the "jack of all trades" policy seemingly applied.

**Comment by isidorn** [comment]
@yume-chan thanks a lot for answering

**Comment by cpsauer** [comment]
Thanks all! Had mistakenly figured VSCode wanted to determine the languages itself.

FWIW, I think VSCode's ability to support a wide range of languages and extensions to be a real plus. We've certainly appreciated it! It lets us edit 10+ languages seamlessly in the same place.

**Comment by DBJDBJ** [comment]
"... It lets us edit 10+ languages seamlessly in the same place..." ... Bless
