### ISSUE TITLE
Proposal for updating commenting area for diffs

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#115808]
I was exploring ways to improve the PR experience in VS Code and one of the ideas involved updating the glyph area for comments. Currently we show a gray bar and a unicode `+` and `♦` that don't look very pretty. 

## Current
![image](https://user-images.githubusercontent.com/35271042/106973183-3b2a6c00-6707-11eb-92e3-a201790c4e41.png)

## Proposal

A couple of things I explored:

- Moving glyph area to the left of line numbers. This helps create separation between between the scm indicators and a clear area for adding comments.
- Adding button for adding and view comments. This follows a similar pattern on GitHub for reviewing changes.
- Hiding diff chunk areas. This reduces the visual noise and I think most people will be commenting on changed lines in the PR as opposed to lines that are not related
- Adding color to the `+` and `-` changes to look visually pleasing

![Kapture 2021-02-04 at 16 36 03](https://user-images.githubusercontent.com/35271042/106973201-42ea1080-6707-11eb-8728-ea12fce064bb.gif)

Unsure who should I assign to so assigning to @rebornix and @alexdima for now

**Comment by misolori** [comment]
Some additional feedback from the team:
- We might still need the indicator for comment areas, particularly when viewing files with changes in review mode where the diffs are not present
  ![image](https://user-images.githubusercontent.com/35271042/106994459-a9842400-6731-11eb-9491-ea56d1349b15.png)
- We could also surface the "add comment" button on line hover to increase discoverability

**Comment by alexr00** [comment]
Here's what I'm thinking:

![Recording 2022-08-08 at 14 31 12 (1)](https://user-images.githubusercontent.com/38270282/183419002-399c6d44-96b1-4e4f-aa43-4524bb72fcd2.gif)

- It uses the comment codicon for lines with a comment thread.
- Keeps the exiting + for add
- Makes them both look a little more clickable but making them more square and giving them rounded corners.

@misolori and @daviddossett what do you think? I didn't add any color for now and I kept everything to the right of the line numbers still.

**Comment by misolori** [comment]
@alexr00 this is looking great, love that we can have codicon support in the comments! I know you mentioned you hadn't added any color, is that something that you'd be open for us to add? I did a quick mockup that shows an alternate styling:

<img width="314" alt="CleanShot 2022-08-08 at 08 57 41@2x" src="https://user-images.githubusercontent.com/35271042/183461148-a4859ce6-4b50-463b-9a95-2edc695fa438.png">

**Comment by alexr00** [comment]
I didn't add color because I thought the blue was a bit too strong, but I really like the color in this mock up. I'll add it and merge the change!

**Comment by alexr00** [comment]
Also updated the multiline add:

![image](https://user-images.githubusercontent.com/38270282/184635785-1f3b9267-de14-43b3-9665-5041d39aa068.png)
