### ISSUE TITLE
1.53 editor not responding (frozen) after window resize

### ISSUE THREAD

**Issue by jurajkapsz** [microsoft/vscode#115868]
- VSCode Version: 1.53
- OS Version: Xubuntu 18.04

Steps to Reproduce:

1. Upgrade to/Install v1.53
2. Resize vscode window
3. Try to scroll or click inside editor etc.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you start with `code --verbose` and provide the output when you perform the above actions.

**Comment by edson-domenech** [comment]
Same problem....

- Version: 1.53.0 (user setup)
- Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
- Date: 2021-02-03T20:36:38.611Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.18363


Steps to Reproduce:

- Upgrade to/Install v1.53
- Resize vscode window
- Try to scroll or click inside editor etc.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
@edson-domenech can you follow the steps from my previous comment and provide the verbose log.

**Comment by edson-domenech** [comment]
attachment logs
[Logs.txt](https://github.com/microsoft/vscode/files/5934874/Logs.txt)

**Comment by deepak1556** [comment]
Thanks for the logs, did you obtain the log from system terminal ? the log is obfuscated, can you make sure to paste logs from the start of app till app quit.

**Comment by jurajkapsz** [comment]
> Can you start with `code --verbose` and provide the output when you perform the above actions.

Done, thanks: [code.log](https://github.com/microsoft/vscode/files/5935207/code.log)

**Comment by deepak1556** [comment]
I don't see any obvious errors in the log, @jurajkapsz can you follow these steps

* Open code
* Open process explorer from `Help` and check PID of the process name starting with `window`
* Perform resize to create the frozen state
* In the terminal run `gcore -o <some-path> <PID-from-step-2>`
* Send the dump to Deepak.Mohan@microsoft.com

**Comment by tammet** [comment]
I can confirm similar behaviour on Ubuntu gnome 16.04.1 LTS: resizing the window in any way makes vs code extremely slow: takes a long time (like several seconds) to respond to tab clicks, like half a minute to respond to menubar clicks.

**Comment by deepak1556** [comment]
@tammet can you provide log from `code --verbose`

**Comment by tammet** [comment]
Here is the log from code --verbose. Opened vscode, clicked on a few tabs, resized the window, became frozen, tried to click on tabs and other places, no visible effect, finally I terminated it using gnome.

[vscodelog.txt](https://github.com/microsoft/vscode/files/5960970/vscodelog.txt)

**Comment by deepak1556** [comment]
log looks good, as a next step can you provide the trace followin https://github.com/microsoft/vscode/issues/115868#issuecomment-774325403

**Comment by tammet** [comment]
vs code had created 10 processes, so I took the pid of the first one. The gcore output is binary blob with the size 4.6 gigabytes. Can I make a smaller version of it or is there a suggested place to upload?

**Comment by deepak1556** [comment]
From the process explorer check the PID of `window ...` and capture the dump from it. Also send the dump to Deepak.Mohan@microsoft.com

**Comment by tammet** [comment]
Well, I do not have a process explorer on ubuntu. Got the relevant pid anyway, ran code main, but the corefile is still 4.6 gigabytes, far too big for easy sending.

**Comment by jurajkapsz** [comment]
> vs code had created 10 processes, so I took the pid of the first one. The gcore output is binary blob with the size 4.6 gigabytes. Can I make a smaller version of it or is there a suggested place to upload?

@tammet Mine dump was around 20 GB, a `gzip` compression created a 26 MB file, a `zip` was 30 MB.

**Comment by deepak1556** [comment]
@jurajkapsz are you using wayland or x11 ? can you launch the app with `--disable-gpu --disable-extensions` and check if the unresponsive window continues to happen. If it does, then can you obtain the output of `code --status` ?

**Comment by tammet** [comment]
@deepak1556 did the same experiment you propose for @jurajkapsz. code --disable-gpu made code work perfectly ok after resizes. --disable-extensions was not necessary. Did several tries of starting code with --disable-gpu and without and resizing: working ok vs semi-frozen as expected every time. I am attaching the code --status outputs for both the with_gpu (freezing) and without_gpu (OK) runs, plus glxinfo output while I was running the with_gpu version (before resize and freeze):
[code_with_gpu_status.txt](https://github.com/microsoft/vscode/files/5970148/code_with_gpu_status.txt) 
[code_without_gpu_status.txt](https://github.com/microsoft/vscode/files/5970150/code_without_gpu_status.txt)
[glxinfo.txt](https://github.com/microsoft/vscode/files/5970156/glxinfo.txt)

I am running Ubuntu Gnome 16.04 LTS on X11, with the intel HD Graphics 5500 and Nvidia GM108GLM [Quadro K620M / Quadro M500M] card. Not sure which of these two was running, but from glxinfo output I suspect Intel.

**Comment by jurajkapsz** [comment]
> @jurajkapsz are you using wayland or x11 ? can you launch the app with `--disable-gpu --disable-extensions` and check if the unresponsive window continues to happen. If it does, then can you obtain the output of `code --status` ?

@deepak1556 I have `x11` and when launching the app with `--disable-gpu ...`, everything works fine.

**Comment by deepak1556** [comment]
Can you follow these to generate performance trace, try to generate the trace with and without `--disable-gpu`

* Create trace.json somewhere on your disk with the following content:
```
{
 "result_file": "/tmp/vscode_trace_event.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "renderer",
     "v8",
     "renderer.scheduler",
     "blink",
     "browser",
     "io",
     "input",
     "latency",
     "cc",
     "gpu",
     "viz",
     "benchmark"
 ],
 "excluded_categories": ["*"]
 }
}
```
* Start `code --disable-extensions --trace-config-file="<path-to>/trace.json"`
* Use vscode for a while as normal until the slowdown is seen
* Quit the editor and attach `vscode_trace_event.log`

**Comment by krasoffski** [comment]
Same problem on Xubuntu 18.04 with the vscode `v1.53` but `v1.52.1` does not have this problem on my laptop. With disabling gpu cannot reproduce this problem.

**Comment by jurajkapsz** [comment]
Guys, if anyone has time and [this input](https://github.com/microsoft/vscode/issues/115868#issuecomment-779502873) is still needed, pls feel free to supply the data, I will be an additional week+ off.

**Comment by deepak1556** [comment]
Can anyone try the latest insiders https://code.visualstudio.com/insiders and check if this is fixed.

**Comment by jurajkapsz** [comment]
> Can anyone try the latest insiders https://code.visualstudio.com/insiders and check if this is fixed.

@deepak1556 

```
Version: 1.54.0-insider
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:32:11.854Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.15.0-136-generic
```

`1.54.0-insider` behaves better, but not 100%: still occasionally hangs on some window resizing but does not crash, and can be unfreezed by resizing window again.

**Comment by deepak1556** [comment]
Thanks for checking, can check back once a newer version of the runtime is updated. For now, you can use the https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration workaround.

**Comment by jurajkapsz** [comment]
> Thanks for checking, can visit this again once a newer version of the runtime is updated. For now, you can use the https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration workaround.

@deepak1556 Thank you.

**Comment by krasoffski** [comment]
`v1.54` still has problem with freeze of window.

**Comment by texjoachim** [comment]
1.54.2 (Just released, too.)

**Comment by texjoachim** [comment]
One more update: Still freezes on X11, but only when the titlebar is set to "custom". No problems when using the "native" titlebar.

**Comment by jurajkapsz** [comment]
Currently I have `Xubuntu 20.04` with `x11` (had 18.04 before), and a default `vscode` (new install), so far no issues.

```
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-50-generic
```

**Comment by kolesar-andras** [comment]
I had same issue on Xubuntu 20.04.2 with 1.55.2. Upgraded to 1.56.2, works fine. Thanks for the fix.

**Comment by krasoffski** [comment]
Is solution to fix this upgrade to `Xubuntu 20.04.2`?

**Comment by jurajkapsz** [comment]
> Is solution to fix this upgrade to `Xubuntu 20.04.2`?

Can't tell, I upgraded to `Xubuntu 20.04` in general.

**Comment by krasoffski** [comment]
I understood, but why  issue has been closed without any reason?

**Comment by deepak1556** [comment]
@krasoffski are you seeing the issue with vscode stable `1.56.2` ?

**Comment by krasoffski** [comment]
@deepak1556 
Thank you!
With the latest 1.56.2 cannot reproduce.
