### ISSUE TITLE
Add multiple tab support for search view (add setting "search.mode": "newView")

### ISSUE THREAD

**Issue by Merlin2001** [microsoft/vscode#115899]
I love the new Search Mode setting (introduced by #112588) to be able to keep **multiple search results quickly accessible** by opening multiple editors for them! And at the same time I'd like to **keep the benefits of the search view**:  
a) quickly collapsible and _most importantly_  
b) double-clicking results open them in the "main" area.

My feature idea is probably most easily explained by the workaround I tried to achieve this:
I set `"search.mode": "newEditor"`, started a search, dragged the new editor to the left of my working area and reduced it's width so that it kind of looks like a panel:
![Search Mode newEditor](https://user-images.githubusercontent.com/13134791/107062737-e73c8780-67d9-11eb-914e-aff7d5627b8c.gif)

The problem is of course, that the search results open in the same (small) area instead of the main one. (Also, when focus is in the main area, Ctrl + Shift + F won't open the search editor in the "panel" on the left.)

### Solution idea 1
Make the search view work like a bunch of search editors docked to the left abandon the search view. (Although I see that there are _subtle differences_ between the two: the search view will show an entry for every occurrence _within_ a line, while the search editor only shows one entry _per_ line.)

### Solution idea 2
Add multi-tab support to the search editor (so it keeps its behavior but still allows for a "history" of results being open).

**Comment by JacksonKearl** [comment]
> The problem is of course, that the search results open in the same (small) area instead of the main one. (Also, when focus is in the main area, Ctrl + Shift + F won't open the search editor in the "panel" on the left.)

You can set `"search.searchEditor.doubleClickBehaviour": "openLocationToSide"` to address the first point, for the second point I can see value in opening the new search editor in the same view as the prior, either as an option or just replacing the current behaviour.

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. PRs are welcome so you can create a PR that fixes this if you are passionate about getting this feature across the finish line. Thanks!
