### ISSUE TITLE
Show Extension Properties based on the result of a function

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#115866]
I need a way to only show properties for paid users. I thought about adding a key called "visible" that receives a function name that will be called by vscode. If the result is true, then the prop is available. 
In my case I will determine if the prop is available after issuing a request to my server to check if the user's license is still activate.

````json
"configuration": {
      "title": "Extension",
      "properties": {
        "myProp": {
          "type": "boolean",
          "default": true,
          "description": "If checked, the form is displayed.",
          "visible": "functionNameToBeCalledToResolveTrueOrFalse"
        },
}
````

Workaround: I can allow anybody to toogle the properties on, and then verify or not if they are allowed to use or not that prop. But this creates more complexity to me, as I will need to keep checking in the server if that user is allowed to use that configuration.

**Comment by gjsjohnmurray** [comment]
Even if you were able to do that, what would stop the unlicensed user from simply adding the setting to `settings.json` directly? It seems to me you still need to do the check in your extension.

**Comment by AllanOricil** [comment]
@gjsjohnmurray good point haha
I just don't want users to configure things they would not be allowed to use. Just to now keep asking "Why this is not working If I toogled in on"

**Comment by gjsjohnmurray** [comment]
@AllanOricil maybe add "(requires license)" to the end of the description of each setting it applies to?

**Comment by AllanOricil** [comment]
@gjsjohnmurray it is a solution. But do you think it is the best way of implementing it?

**Comment by eamodio** [comment]
Forgetting the proposed use-case, I think adding an optional `when` clause using the existing context infrastructure could be very interesting for extensions to control setting visibility (in the UI).

**Comment by eamodio** [comment]
Related to #70589

**Comment by AllanOricil** [comment]
Please, don't use the word "when". It is so weird. If this feature gets enough votes, ask the community about the their preference. My opinion is that is much more clear to use "visible"
