### ISSUE TITLE
show promt dialog over mouse cursor

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#115852]
Issue Type: <b>Bug</b>

show promt dialog over mouse cursor

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2086)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 0, 0|
|Memory (System)|7.66GB (0.35GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9cc3893b-361e-4ca7-8513-c98a43defcee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.38.0
prettier-vscode|esb|5.8.0
prisma|Pri|2.16.0
markdown-preview-enhanced|shd|0.5.16

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

Every time if you want to change some names the dialog will cover that name under your mouse pointer.
the line where MemoryStore residents is where I want to add some one imports.
but when ever i move mouse over that line, a dialog is preventing me from change that line.

![2021-02-05 18-18-10屏幕截图](https://user-images.githubusercontent.com/131776/107021225-d6dadb80-67de-11eb-9151-b71945f409b3.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

A bug like this got fixed in 1.53 but you haven't said what version you are running, nor on what platform.

**Comment by yume-chan** [comment]
Does this still happen to you in 1.53?

**Comment by calidion** [comment]
it seems this bug is occasional.
It is not shown again even i use version 1.52.1 now.
