### ISSUE TITLE
screen will shake when typing markdown file which contains pics

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#115864]
- VSCode Version: 1.53.0/1.52.0
- OS Version: all
Steps to Reproduce:

1. markdown file contain pics
2. preview 
3. typing markdown file
![vscode_markdown](https://user-images.githubusercontent.com/1876302/107028827-0c84c200-67e9-11eb-85b0-721959e4a015.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a file that demonstrates the issue

**Comment by tamuratak** [comment]
I guess the cause is MathJax or KaTeX. They are inserting math equations asynchronously and are changing the rendered HTML's height.

We can see `$I_{...}$` in the markdown file.

**Comment by heartacker** [comment]
> I guess the cause is MathJax or KaTeX. They are inserting math equations asynchronously and are changing the rendered HTML's height.
> 
> We can see `$I_{...}$` in the markdown file.

Thanks for your remind. with my testing, problems is caused by the rendering of mathematical formulas while picture is showed.
I have installed  `yzhang.markdown-all-in-one` for math.
so how to deal with? thx
