### ISSUE TITLE
Cannot unset StatusBarItem background from errorBackground

### ISSUE THREAD

**Issue by ntotten** [microsoft/vscode#115886]
- VSCode Version: 1.53.0
- OS Version: macOS 10/11

Steps to Reproduce:

1. An extension sets the `statusBarItem.backgroundColor` to `statusBarItem.errorBackground`
2. The status bar item is shown with the error background.
3. Set the `statusBarItem.backgroundColor` to `undefined`
4. The error background color is still shown

Does this issue occur when all extensions are disabled?: N/A

Code snippet from [Prettier extension](https://github.com/prettier/prettier-vscode/commit/4508673383b40666ab5f79e509f2790d9a7b7d52#diff-983faffe5d596cfa5a8ef74a92ded90860d8834d266884fa869fe34667d714f3R53-R59)

```
if (result === FormattingResult.Error) {
  this.statusBarItem.backgroundColor = new ThemeColor(
    "statusBarItem.errorBackground"
  );
} else {
  this.statusBarItem.backgroundColor = undefined
}
```

I would expect this to unset the background color, but it does not do anything.

**Comment by zegl** [comment]
I just encountered the same issue, and have resorted to using the following workaround:

```ts
export interface StatusBarMessage {
    msg: string;
    backgroundColor: vscode.ThemeColor | undefined;
}

export function setStatusBarText(m: StatusBarMessage) {
    // There is a bug and you can't unset the background color of a status item.
    // If we want to do it, dispose the previous status bar item, and create a new one.
    // https://github.com/microsoft/vscode/issues/115886
    if (myStatusBarItem.backgroundColor !== undefined && m.backgroundColor === undefined) {
      myStatusBarItem.hide()
      myStatusBarItem.dispose()

      // Create a new item
      myStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
      myStatusBarItem.command = statusBarCommandID;
      ctx.subscriptions.push(myStatusBarItem);
    }

    myStatusBarItem.text = m.msg;
    myStatusBarItem.backgroundColor = m.backgroundColor;
    myStatusBarItem.show();
}
```

**Comment by bpasero** [comment]
A fix is planned for recovery: https://github.com/microsoft/vscode/pull/116181
