### ISSUE TITLE
 Jupyter Notebook does not execute !python or %run in the selected conda environment.

### ISSUE THREAD

**Issue by spdavern** [microsoft/vscode#115825]
- VSCode Version: 1.53.0
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Open Jupyter notebook in VS Code.  Select a kernel with a Conda environment with a package that isn't in the base env.
2. Run a <name>.py script using `! python <name>.py` or `%run <name>.py` that imports a package in the selected conda environment.

![2021-02-04_18-16-43](https://user-images.githubusercontent.com/5695380/106992024-5fe50a80-672c-11eb-8648-313b507a5733.png)

The attached image shows a Jupyter Notebook that worked fine yesterday before VS Code updated to 1.53.0 from the previous version.

Does this issue occur when all extensions are disabled?: Yes/No
Not sure.

**Comment by spdavern** [comment]
After submitting the above issue I deleted VS Code by opening my Mac Applications folder, right clicking on VS Code, selecting Move to Trash.  I then downloaded VS Code 1.52.1 from [here](https://code.visualstudio.com/updates/v1_52), unzipped the download, dragged VS Code back to my Applications folder.  Opened VS Code and the Jupyter Notebook displayed above, re-ran the cells and NO ERROR!  There is an issue with 1.53.0!

**Comment by isidorn** [comment]
Ok, so it seems fixed, thus closing.
fyi @rebornix for notebooks

**Comment by spdavern** [comment]
LOL!  No, 1.53.0 is not "fixed".  I reverted from 1.53.0 back to 1.52.1.  I hoped reporting this would 1) rule out various potential causes for what I have reported is broken in 1.53.0 and 2) help others know a solution since version 1.53.0 cost me hours of troubleshooting effort yesterday.  My report does NOT justify closing this issue.

**Comment by isidorn** [comment]
File against python extension please https://github.com/microsoft/vscode-python
Thanks!

**Comment by spdavern** [comment]
https://github.com/microsoft/vscode-python/issues/15327
