### ISSUE TITLE
After adding a folder to a workspace whose .code-workspace file is read-only, the "Save As..." option does nothing

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#115840]
Issue Type: <b>Bug</b>

1. Have an empty XXX.code-workspace file.
```
{
	"folders": [],
	"settings": {}
}
```
2.  Set the file read-only on the filesystem. On Windows I set the read-only attribute.
3. Open the workspace.
4. Add a folder to the workspace. An error notification appears with the message "Failed to save 'XXX.code-workspace': File is read-only. Select 'Overwrite' to attempt to make it writeable."
5. Click "Save As..."

**Expected**
A 'Save As' dialog with which to create a new code-workspace file.

**Actual**
Nothing appears. The file tab 'XXX.code-workspace' that opened continues to show the 'modified' indicator dot.

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:50.117Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Key to reproducing this is that at least one editor must be open when you do step 4, and the focused editor must not be the XXX.code-workspace file itself.

The save error causes the dirty XXX.code-workspace file to be loaded into an editor if it isn't already open, but focus is not moved to this file's editor. This means that when the "Save As..." button executes the `workbench.action.files.saveAs` command it acts on the wrong editor.

When I initially observed the problem my only open tab was the Welcome page, for which saveAs does nothing.

In a subsequent test of the repro I had a regular file open, and I noticed that the Save As dialog appeared but named the focused file, not the XXX.code-workspace file I expected to see there.

**Comment by bpasero** [comment]
Open for a PR with a small simple fix if possible.

**Comment by bpasero** [comment]
Very good issue, turns out that the buttons in the save error notification were simply just operating on the currently active editor. I also noticed the same issue for custom editors actually so fixed both.

**Comment by JacksonKearl** [comment]
getting an error `cannot read property getGroups of undefined` when I try to test this. cc @gjsjohnmurray did you see anything like this?

![recording (1)](https://user-images.githubusercontent.com/8586769/109237859-4bbe8700-7787-11eb-9b87-ae7bfe36f8f1.gif)

**Comment by gjsjohnmurray** [comment]
@JacksonKearl in my verification I didn't actually test the Save As. Now that I do that I can confirm I get the same error as you.

It's happening here:
https://github.com/microsoft/vscode/blob/1e25d0c49bd8177ece0dbdf47689c286673ddbd5/src/vs/workbench/contrib/files/browser/editors/textFileSaveErrorHandler.ts#L334

**Comment by JacksonKearl** [comment]
Thanks for the confirmation! Strange that the construction call on https://github.com/microsoft/vscode/blob/00cb6865ab89c339e7d6bae01e3be4bf9cbd4adc/src/vs/workbench/contrib/files/browser/editors/textFileSaveErrorHandler.ts#L158
type checks... I'd expect it to error since fewer parameters are passed than needed and there's no service injection in the constructor.

**Comment by bpasero** [comment]
Good finding.

**Comment by rzhao271** [comment]
\closedWith aa9f384

**Comment by connor4312** [comment]
I'm on the latest Insiders and am hitting the issue as originally described, on windows: https://memes.peet.io/img/21-02-95f46e11-ad59-4f0c-9dde-94c5785a9a46.mp4

**Comment by bpasero** [comment]
I cannot reproduce what you see, for me the dirty file opens in the background:

![recording](https://user-images.githubusercontent.com/900690/109378539-a238dc00-78d3-11eb-88a8-bb44758134f8.gif)

I think I have to throw the towel for this one, please do not mark code workspaces as readonly if you want to use them.

**Comment by bpasero** [comment]
Oh nevermind, you have auto save enabled and I found an actual issue, though unrelated to this one: https://github.com/microsoft/vscode/issues/117870
