### ISSUE TITLE
Insiders version on .deb says gi.repository partially initialized

### ISSUE THREAD

**Issue by JimOfCR** [microsoft/vscode#115881]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Because my release version of vs code suddenly began to report that code was unresponsive immediately after hitting a breakpoint, I could not continue debugging. So I switched to the Insiders version. This allowed me to complete my debugging. However, almost immediately after that the Insider's version started saying that it could not import the Gtk because the gi.repository was only partially initialized. So I returned to the released install of code which does not report this error. I am not stuck between a rock and a hard place. I cannot debug in the released code version and I cannot use the Insiders version. I'm running on the very latest updated version of Zorin OS Ultimate 1.53. The only extension that I installed on the Insiders version was Python. I cannot remove it to see if it is the problem, obviously, since my code is in Python.
Version: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:16:37.087Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-65-genericVersion: 1.54.0-insider
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:16:37.087Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-65-generic

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:16:37.087Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor (12 x 2156)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.63GB (0.93GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 2afb06b9-f602-4ce1-9a15-bd8c3772fae3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin|
|XDG_CURRENT_DESKTOP|zorin:GNOME|
|XDG_SESSION_DESKTOP|zorin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by chrmarti** [comment]
This seems to be an issue with your Python installation or Python packages. E.g., https://stackoverflow.com/questions/34401677/meld-error-cannot-import-gtk-no-module-named-repository talks about similar issues. Please try finding an answer searching Python-related posts / articles on the web.

The debugging issue sounds like it might be an issue with the Python extension. Please open an issue for them here: https://github.com/microsoft/vscode-python/issues/new/choose

**Comment by JimOfCR** [comment]
Thank-you for your response. I do have doubts that it is the Python plug-in. The exact same plug-in is in use the release version of vs code and does not have this problem.


    On Tuesday, February 9, 2021, 02:01:24 AM CST, Christof Marti <notifications@github.com> wrote:  
 
 


This seems to be an issue with your Python installation or Python packages. E.g., https://stackoverflow.com/questions/34401677/meld-error-cannot-import-gtk-no-module-named-repository talks about similar issues. Please try finding an answer searching Python-related posts / articles on the web.

The debugging issue sounds like it might be an issue with the Python extension. Please open an issue for them here: https://github.com/microsoft/vscode-python/issues/new/choose

**Comment by chrmarti** [comment]
The Python folks will have more context to help solve the issue. Thanks.
