### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by Byarlant** [microsoft/vscode#115872]
- VSCode Version: 1.53.0
- OS Version: Linux x64 3.16.0-11-amd64

Steps to Reproduce:

1. Launch vscode
2. 100% CPU usage by the process /usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
3. Same behavior when launching vscode with all extensions disabled: code --disable-extensions

Does this issue occur when all extensions are disabled?: Yes

The previous version 1.52.1 didn't exhibit this behaviour.

**Comment by Byarlant** [comment]
I just downgraded to version 1.52.1 by downloading the .deb from https://code.visualstudio.com/updates/v1_52 and the CPU usage is normal, with all extensions enabled.

**Comment by MaeveOReilly** [comment]
I'm seeing same behavior on RedHat 7.9 since upgrading to VS Code 1.53.0.

**Comment by texjoachim** [comment]
Same here on openSUSE Tumbleweed.
1.53.0 grinds to a halt a few seconds after start und becomes completely unusable.
A downgrade to 1.52.1 solves the problem.

**Comment by jrieken** [comment]
/needsMoreInfo

Please use this guide to provide more information: https://github.com/Microsoft/vscode/wiki/Performance-Issues. Thanks.

**Comment by Byarlant** [comment]
So I tried to follow the guide https://github.com/Microsoft/vscode/wiki/Performance-Issues.

I downloaded the version 1.53.0 from the official vscode site, unarchived it in /opt and launched it with all extensions enabled:

![Screenshot 2021-02-09 102431](https://user-images.githubusercontent.com/3017624/107344585-e8fc9880-6ac2-11eb-9a1f-4315283f680b.jpg)

I then took a look at the process explorer:

![Screenshot 2021-02-09 102521](https://user-images.githubusercontent.com/3017624/107344640-fb76d200-6ac2-11eb-85b1-ebb27bbd6a95.jpg)

The extensionHost is the one with the highest CPU usage (25).

I ran code --status, the information seems to be similar to the one in the process explorer:

[code status.txt](https://github.com/microsoft/vscode/files/5950300/code.status.txt)

I ran code with all extensions disabled (code --disable-extensions), still 100% CPU usage:

![Screenshot 2021-02-09 103227](https://user-images.githubusercontent.com/3017624/107344984-62948680-6ac3-11eb-91bb-857d573d5fb9.jpg)

I tried reporting the issue directly from vscode, but the command does not respond.

**Comment by jrieken** [comment]
please follow this section of the aforementioned guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

**Comment by deepak1556** [comment]
@Byarlant which linux distro flavor are you using ? Can you also provide the output of `code --verbose`

**Comment by Byarlant** [comment]
I'm using Debian GNU/Linux 8.11 (jessie).

Here's the output of `code --verbose`: 
[code_output.txt](https://github.com/microsoft/vscode/files/5958695/code_output.txt)

**Comment by Byarlant** [comment]
The following are the distros known to work for the x64 desktop app:

- Ubuntu 16.04 and newer
- Fedora 24 and newer
- **Debian 9 and newer**
- CentOS 8 and newer

Sorry, I guess I'll read the release notes more carefully next time.

**Comment by scaprile** [comment]
I can add that in CentOS 7 (el7 rpm) Terminal ->New terminal  does not work, there seems to be a library version issue:
```
The terminal process failed to launch: A native exception occurred during launch (/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code/resources/app/node_modules.asar.unpacked/node-pty/build/Release/pty.node)).
```
Don't know if this is related to the 100% CPU usage, that I can also confirm (CentOS 7.9.2009 with glibc-2.17-323)
Version 1.52.1 works OK.

**Comment by deepak1556** [comment]
@scaprile yes the cpu usage is related to that module loading error, you can check https://github.com/microsoft/vscode/issues/115784 for details and workaround. Thanks!

**Comment by scaprile** [comment]
> @scaprile yes the cpu usage is related to that module loading error, you can check #115784 for details and workaround. Thanks!

Oops, busy testing missed your reference to that
