### ISSUE TITLE
使用ctrl 输出错误日志

### ISSUE THREAD

**Issue by wukuang-818** [microsoft/vscode#115822]
所需的数据太大，无法直接发送
Issue Type: <b>Bug</b>

[Error - 下午12:08:10] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:08:10] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:10:32] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:13:50] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:14:14] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:15:42] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:24:39] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:24:39] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:25:27] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:25:51] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:26:10] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:26:11] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:31:42] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:31:46] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:31:56] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:31:57] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:00] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:00] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:05] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:06] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:15] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:15] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:33] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:33] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:34] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:38] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:43] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:43] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:44] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 
[Error - 下午12:32:45] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'start' of undefined
  Code: -32603 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.63GB free)|
|Process Argv|--crash-reporter-id fdf5e976-354a-43ee-a547-52e414d756db --crash-reporter-id fdf5e976-354a-43ee-a547-52e414d756db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (134)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
node-ts-api-snippet|aba|0.0.7
vscode-file-peek|abi|1.0.1
es7-javascript-class-snippets|abr|0.4.0
html-snippets|abu|0.2.1
vscode-css-formatter|aes|1.0.1
aessoft-class-autocomplete|AES|0.1.0
vscode-caniuse|aka|0.5.4
vscode-javascript-snippet-pack|aka|0.1.6
MochaSnippets|Ala|0.0.1
TabOut|alb|0.2.0
Bookmarks|ale|12.1.4
project-manager|ale|12.0.1
html-class-suggestions|And|1.0.7
vscode-json|and|1.5.0
vscode-color|ans|0.4.5
vscode-browser-preview|auc|0.6.7
color-info|bie|0.5.1
vscode-standardjs-snippets|cap|0.8.15
vue-css-peek|Cha|1.0.0
node-snippets|chr|1.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
regex|chr|0.2.0
bracket-pair-colorizer|Coe|1.0.61
vscode-express|Com|0.0.5
flask-snippets|cst|0.1.1
vscode-mysql-client2|cwe|3.5.2
vscode-eslint|dba|2.1.14
vscode-faker|dee|1.5.0
vscode-npm-source|dku|1.0.0
jquerysnippets|don|0.0.1
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.0
vscode-html-css|ecm|1.9.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
vscode-drawio|eig|1.0.3
vscode-great-icons|emm|2.1.64
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|5.9.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
html-slim-scss-css-class-completion|gen|1.7.8
giflens|gif|2.0.0
vscode-atom-javascript-snippet|glu|0.2.1
nodejs-module-snippet|gun|0.0.2
vscode-drawio-insiders-build|hed|1.3.2
vue-snippets|hol|1.0.4
minify|Hoo|0.4.3
rest-client|hum|0.24.4
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.17.0
mysql-syntax|jak|1.3.1
search-node-modules|jas|1.3.0
svg|joc|1.4.5
docthis|joe|0.7.1
vscode-codemetrics|kis|1.24.0
node-module-intellisense|lei|1.5.0
ftp-sync|luk|0.3.9
mafratechnodejs|Maf|0.0.8
MagicPython|mag|1.1.0
string-manipulation|mar|0.4.4
code-beautifier|mic|2.3.3
vscode-todo-parser|min|1.9.1
HTMLHint|mka|0.10.0
vscode-filesize|mkx|2.1.4
javascript-code-snippets|moa|0.2.0
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.18
vscode-csscomb|mrm|5.3.2
vscode-azurefunctions|ms-|1.2.0
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.5
cpptools|ms-|1.2.0
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
node-modules-resolve|nau|1.0.2
python-coding-tools|nil|1.0.3
vscode-for-node-js-development-pack|nod|2.0.1
korofileheader|OBK|4.8.2
vetur|oct|0.32.0
indent-rainbow|ode|7.5.0
Lodash|oys|1.0.0
vuehelper|oys|0.1.0
emoji|Per|0.0.3
vscode-css-peek|pra|4.0.2
promise-snippets|pro|0.2.3
vscode-css-navigation|puc|1.10.3
minapp-vscode|qiu|2.2.2
chai-spec-generator|rin|0.4.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
vs-code-prettier-eslint|rve|0.4.1
vue-vscode-snippets|sdr|2.1.5
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.16
html5-boilerplate|sid|1.1.1
svg-snippets|sid|1.0.1
code-bing|Sir|0.2.0
indenticator|Sir|0.7.0
html-to-css-autocompletion|sol|1.1.2
guides|spy|0.9.3
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.85.0
language-stylus|sys|1.11.0
vscode-gulp|tan|0.0.4
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
vs-code-node-require|tgr|1.9.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
node-dependencies|tsc|1.2.1
python-extended-snippets|tus|0.0.1
codelf|unb|11.7.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.1.0
snippet|vsc|0.8.1
nodejs-extension-pack|wad|0.1.9
vscode-js-console-utils|wht|0.7.0
vscode-import-cost|wix|2.15.0
wx-snippets|wux|1.0.4
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.13
html-css-class-completion|Zig|1.20.0
classnametocss|zit|0.0.5

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

。我们已经将其写入剪贴板，请粘贴。

**Comment by yume-chan** [comment]
Title translation:

> Use Ctrl to output error log

or

> When using Ctrl there is error output

I dunno.

**Comment by isidorn** [comment]
Please file issues in english and with reproducable steps. There is nothing we can do here...
