### ISSUE TITLE
VSCode is asking me to update the updated VSCode

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/vscode#115838]
Have this "info" and reminder:

![image](https://user-images.githubusercontent.com/145155/107011678-437eb780-6798-11eb-8955-b4425945d2dd.png)

but there is no update

![image](https://user-images.githubusercontent.com/145155/107011445-f00c6980-6797-11eb-9a69-50575dc7e375.png)

I do not know if related, but I added GO extension yesterday:

![image](https://user-images.githubusercontent.com/145155/107011825-7b85fa80-6798-11eb-8f12-84dbf4a9ccaf.png)

And this is my VS Code and OS info box

![image](https://user-images.githubusercontent.com/145155/107011997-b720c480-6798-11eb-87d9-ce646a429c1c.png)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1. just close and open the VSCode ... after a little while it will inform there is a new VSCode to be downloaded?
2.

Does this issue occur when all extensions are disabled?: Yes/No

**YES**

**Comment by DBJDBJ** [comment]
@isidorn @joaomoreno well this seems fixed inside 15 mins. Many thanks.

**Comment by DBJDBJ** [comment]
Eh ... it is doing it again

![image](https://user-images.githubusercontent.com/145155/107025802-35399700-67aa-11eb-98e0-0f25a4696f75.png)

**Comment by DBJDBJ** [comment]
@isidorn   And again .. this time from MX Linux installation. How peculiar :)

**Comment by joaomoreno** [comment]
@DBJDBJ Is this still hapenning?

**Comment by DBJDBJ** [comment]
Let me see ... Ok. No this is not happening anymore

![image](https://user-images.githubusercontent.com/145155/141298279-391512e2-c4b8-4e4b-8415-9403bdaadd83.png)

This machine is  `Microsoft Windows [Version 10.0.19042.1288]`

And yes, I do not remember seeing it on MX Linux either.

Thanks!
