### ISSUE TITLE
Delay when creating new integrated terminals

### ISSUE THREAD

**Issue by jaminthorns** [microsoft/vscode#115887]
- Version: 1.53.0
- Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
- Date: 2021-02-03T16:01:04.046Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Open a new integrated terminal.
2. Observe slow (1-2 sec) terminal creation.

I can confirm that this was introduced with the `1.53.0` release, I immediately noticed the delay when creating terminals. The delay occurs when creating terminals by opening the panel, creating a new terminal when the panel is already opened, and splitting a terminal. It occurs for every terminal renderer type.

Does this issue occur when all extensions are disabled?: **Yes**

https://user-images.githubusercontent.com/6618434/107054326-97d46800-6795-11eb-91cf-e8a6822ea8ad.mov

**Comment by jaminthorns** [comment]
This seems to be fixed in `1.54.0`! Spawning a new integrated terminal still isn't as fast as standalone terminals (iTerm, Terminal.app, Kitty, etc.), but I believe it's back to pre-`1.53.0` speeds and feels pretty speedy.

**Comment by Tyriar** [comment]
Sorry I didn't see this, I have no idea what caused it but glad it's back 😅

_A lot_ of changes have been happening around the terminal to enable "persistent terminals" across reload, so perhaps some refactoring there fixed it. Anyway, let us know if you see problems again and we hopefully won't be so slow to respond.
