### ISSUE TITLE
Launcher node js don't work anymore since last apple update

### ISSUE THREAD

**Issue by parkego** [Microsoft/vscode#11586]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0
- OSX el Capitan 10.11.6 (15G1004)
Steps to Reproduce:

1.  set the lauch.json with this json : 
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Lancer",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/index.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            /*"preLaunchTask": "test",*/
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attacher",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}
```
2. click on F5 to launch the debugger.
3. Try to ping your node application ( on my computer, port localhost:3000 )

The node application does not respond anymore, but if i use "node index.js" in the folder with the index.js file, the application is working well.
This issue appeared when i installed the last update of OSX el Capitan ( just before it it was working well).

**Comment by isidorn** [comment]
This works fine on my machine and I have the same OS X version. In order for us to investigate further please upload a small repository for which you can repro this issue to GitHub. Thanks!

**Comment by weinand** [comment]
@parkego please try to run your `node index.js` from the command line but in VS Code's integrated terminal. Do you see the same problem?

**Comment by parkego** [comment]
Hello,
I have tried with a small hapi server and the debugger works.
But on my project the hapijs dont start.
i have already tried to lauch « node index.js » in the integrated terminal and it’s working well.
But the lauch action don’t.
Thanks for the help

Thomas TRIVIDIC
T +33 6 44 23 07 56
E thomas@parkego.com (mailto:thomas@parkego.com)

PARKEGO – S.A.S. au capital de 30 000 €
Siège Social : 1 Boulevard Maître Maurice Slama
Immeuble Premium
06 200 NICE, France

**Comment by parkego** [comment]
Hello.
First thanks for the help,
I resolved the problem removing all the files of VS code and re installing it.
I removed this files and folders :
/Applications/Visual Studio Code.app /private/tmp/VSCode Crashes ~/.vscode ~/Library/Application Support/Code ~/Library/Caches/Code ~/Library/Preferences/com.microsoft.VSCode.* ~/Library/Saved Application State/com.microsoft.VSCode.savedState

Thomas TRIVIDIC
T +33 6 44 23 07 56
E thomas@parkego.com (mailto:thomas@parkego.com)

PARKEGO – S.A.S. au capital de 30 000 €
Siège Social : 1 Boulevard Maître Maurice Slama
Immeuble Premium
06 200 NICE, France

**Comment by weinand** [comment]
@parkego great to hear that you could solve your problem.
But from the things you had to remove, I have no idea why it should have solved the issue.
Did you had installed some extensions? Removing ~/.vscode would have deleted them. So that could have been an issue...

**Comment by parkego** [comment]
Yes i had some extensions but i could not remember which ones ( they are deleted so i can’t find them anymore).
I don’t know wich remove file command did solve my problem but yes it could be a bug with a extension.

Thomas TRIVIDIC
T +33 6 44 23 07 56
E thomas@parkego.com (mailto:thomas@parkego.com)

PARKEGO – S.A.S. au capital de 30 000 €
Siège Social : 1 Boulevard Maître Maurice Slama
Immeuble Premium
06 200 NICE, France

**Comment by weinand** [comment]
@parkego I've you experience strange issues like yours, it is always a good idea to launch VS Code with the `--disable-extensions` and verify that it is not a problem introduced by an extension.

**Comment by parkego** [comment]
Hello,
Good to hear, i’ll do this the next time .
Thanks for your help
Thomas TRIVIDIC
T +33 6 44 23 07 56
E thomas@parkego.com (mailto:thomas@parkego.com)

PARKEGO – S.A.S. au capital de 30 000 €
Siège Social : 1 Boulevard Maître Maurice Slama
Immeuble Premium
06 200 NICE, France

**Comment by ramya-rao-a** [comment]
Closing
