### ISSUE TITLE
VSCode emmet SASS snippets

### ISSUE THREAD

**Issue by Pabuin** [microsoft/vscode#115839]
- VSCode Version: 1.5.3
- OS Version: Debian 10.7

Steps to Reproduce:

1. EMMET snippets in SASS files end of line - ' ; '
2. tac --> text-align: center; (!!)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by saminton** [comment]
Same comportement here, a way to revert to the old Emmet functionality would be nice. Am having other bugs with SASS files and the recent emmet updated also.

**Comment by zawys** [comment]
Duplicate? #115854

**Comment by rzhao271** [comment]
Try this workaround:
1. Press F1 to open the Command Palette
2. Search for and run the command 'Preferences: Open Settings (JSON)'
3. Paste the following into the settings file that shows up and save it:
```json
"emmet.preferences": {
    "sass.propertyEnd": "",
    "stylus.valueSeparator": " ",
    "stylus.propertyEnd": ""
}
```

The issue:
I forgot to set some defaults in vscode-emmet-helper while refactoring the code 😓

**Comment by rzhao271** [comment]
\closedWith 339d6dd

**Comment by lyachartem** [comment]
> 
> 
> **Edit**: The fix should be in VS Code Insider's tomorrow.
> (Previous message below)
> 
> Try this workaround:
> 
>     1. Press F1 to open the Command Palette
> 
>     2. Search for and run the command 'Preferences: Open Settings (JSON)'
> 
>     3. Paste the following into the settings file that shows up and save it:
> 
> 
> ```json
> "emmet.preferences": {
>     "sass.propertyEnd": "",
>     "stylus.valueSeparator": " ",
>     "stylus.propertyEnd": ""
> }
> ```
> 
> The issue:
> I forgot to set some defaults in vscode-emmet-helper while refactoring the code 😓

Thank You!

**Comment by Venegrad** [comment]
```
"emmet.preferences": {
    "sass.propertyEnd": "",
    "stylus.valueSeparator": " ",
    "stylus.propertyEnd": ""
}
```

**Comment by rzhao271** [comment]
Verifier:

Set up a .sass document with the following content:
```sass
body {

}
```
Within the braces, type `tac`. Confirm that `text-align: center` shows up with no trailing semicolon.
