### ISSUE TITLE
Files don't preview when selected in explorer

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode#115869]
Issue Type: <b>Bug</b>

1. Open a folder with files a.txt, b.txt, c.txt.
2. Click on a.txt in the explorer.
3. Press Arrow Down to select b.txt

Expected Results:
b.txt is previewed in the active editor.

Actual Results:
b.txt is highlighted in the explorer. No way to open the file using the keyboard. Enter allows to rename the file.

Background:
I want to quickly skim through a lot of files in a folder.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2191B CPU @ 2.30GHz (36 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv|. --crash-reporter-id 933de67e-f1b5-433f-bdc3-8f88412891cd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
vsliveshare|ms-|1.0.3629

</details>

**Comment by gjsjohnmurray** [comment]
Did you try spacebar as the cue to open the file?

**Comment by toh-ableton** [comment]
No, thank you! This is what I had been looking for. I was searching for this, but couldn't find this information anywhere.

Ideally, it would still speed up my workflow if I didn't have to press space bar, but that's a good-enough workaround for now.

**Comment by gjsjohnmurray** [comment]
Glad to have helped. Please close the issue.

**Comment by isidorn** [comment]
Lovely, closing this as designed
