### ISSUE TITLE
Revisit List/Tree UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#115873]
Changes:

1. The default expand/collapse behavior in trees has changed to become more consistent among all trees in the workbench: one must now click the twistie/icon of the tree node to expand/collapse it. Double clicking also works. You can revert this with the `workbench.tree.expandMode` setting.
2. The default style of a focused list/tree element has changed to the default focused widget outline color This was adopted across all core themes. We will suggest theme authors to do the same.

**Comment by joaomoreno** [comment]
Will roll out these changes in Insiders to get feedback

**Comment by joaomoreno** [comment]
Closing with https://github.com/microsoft/vscode/commit/4a941b1853a7b9e0173fd3f9c6eeeb6af13503f0

**Comment by yume-chan** [comment]
Description of `workbench.list.openMode` reads:

https://github.com/microsoft/vscode/blob/714b41738e404d80e9f19c4f2622c35ce2f0df1b/src/vs/platform/list/browser/listService.ts#L1020

> For parents with children in trees, this setting will control if a single click expands the parent or a double click.

Is that still true?

---

Why the existing setting is called workbench.**list**.openMode and the new one is workbench.**tree**.expandMode? Are "list" and "tree" interchangeable?

**Comment by dhruvit-r** [comment]
Just wanted to point out that the default `workbench.tree.expandMode` is `doubleClick` on the latest insiders build, and this will probably irk a few of us who are used to `singleClick` being the default (there are a couple duplicate issues already: #116804 and #116905).

Build Info:
```
Version: 1.54.0-insider
Commit: 3f0d8a14759cddea93f0dbddc12a4ef1e5586e86
Date: 2021-02-17T07:37:50.976Z (23 hrs ago)
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by joaomoreno** [comment]
> > For parents with children in trees, this setting will control if a single click expands the parent or a double click.
> 
> Is that still true?

You're correct. I'll revise this phrase.

> Why the existing setting is called workbench.**list**.openMode and the new one is workbench.**tree**.expandMode? Are "list" and "tree" interchangeable?

The former applies to all lists and trees. The latter only to trees. Basically trees are also lists, but not the other way around. 😉

**Comment by joaomoreno** [comment]
We've decided to revert the default `openMode` setting! All other changes will remain, as they improve usability. Thanks for all the feedback!

**Comment by joaomoreno** [comment]
To verify:

- Make sure the focus indicator on lists and trees is now an outline decoration. Ie, click on an item in the explorer and press <kbd>DownArrow</kbd>.
- Make sure this looks good across our core themes
