### ISSUE TITLE
Extension Management Profiles

### ISSUE THREAD

**Issue by kode4food** [microsoft/vscode#115834]
While it's nice that one can enable/disable Extensions per Workspace, I find myself with quite a few Workspaces that tend to have the same sets of extensions enabled or disabled (for example: Go projects, Vue.js projects, C projects, and so on).

Having to perform the enable/disable for every Workspace to narrow the set of appropriate Extensions is cumbersome and requires revisiting all Workspaces when a new Extension becomes applicable for a certain project type.

I'm wondering if there are plans to create an Extension Profile Manager in order to create distinct sets of enabled/disabled Extensions, depending on a user-defined project type?

And if not, would the current VSCode API even allow for this? So that I can maybe start working on such an Extension?

**Comment by kode4food** [comment]
@sandy081 any reference to the issue(s) it's duplicating?

**Comment by sandy081** [comment]
Please search for existing issues [here](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+) using label `extensions`
