### ISSUE TITLE
Let users know what extension is requesting permissions

### ISSUE THREAD

**Issue by vomc** [microsoft/vscode#115844]
Every once in a while I get this popup asking me to put in my macos password when some mysterious 'helper tool' is requesting permissions. This is not a great user experience - you basically have no idea what update is requesting permissions and why.

It would be great if you would include some information in this dialog such what the 'helper tool' in question is, what version is being updated and what permissions are being requested.

<img width="555" alt="Screenshot 2021-02-05 at 11 01 31" src="https://user-images.githubusercontent.com/78635/107019279-c35d4f80-67a1-11eb-800d-a2efb00d3492.png">

**Comment by yume-chan** [comment]
It's not related to any extension. Something goes wrong and Code can't update itself so came this popup.

See https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 and https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469

**Comment by joaomoreno** [comment]
@deepak1556 AFAIK this comes from Electron.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/100517

Its a macOS thing, to avoid the pop-up make sure the app and updater config are owned by your user. Check https://github.com/microsoft/vscode/issues/95534 for details.
