### ISSUE TITLE
Improve transfer of ArrayBuffers to and from webviews

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#115807]
## Problem

There are currently two issues when you try posting a ArrayBuffer to a webview or from a webview back to VS Code:

1. The `ArrayBuffer` is not revived. Instead the receiver ends up getting a JavaScript object literal with the contents of the array buffer

1. Serialized messages for typed arrays are currently super inefficient . For example, a Uint8Array is serialized as `"{ "0": 0, "1": 0, "2": 0, ... }"`

## API Proposal
In `Webview.postMesssage`, add a second parameter that lets extensions specify the types to 'transfer':

```ts
interface Webview {
    postMessage(message: any, transfer?: readonly ArrayBuffer[]): Promise<bool>;
} 
```

This is inspired by the [`postMessage` web api](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), however to start with, we'd only allow transferring of array buffers.

When `transfer` is provided, we'd walk the `message` object to find any `ArrayBuffer` object that appear in the message and make sure these are more efficiently transferred. We'd also revive them properly on the other side (so if an `ArrayBuffer` goes in, then an `ArrayBuffer` object comes out too)

### Why not just always enable this behavior instead of requiring `transfer`?

We'd potentially break existing extensions that rely on the current serialized format of ArrayBuffers/typed arrays.

Having a `transfer` parameter also lets us really transfer the `ArrayBuffer` in cases where this is possible

### Can we always "transfer" ownership of the `ArrayBuffer` the way that we can on web?

No, we can't.

Consider an extension running on a remote with a local webview for example. There is no way to actually transfer the `ArrayBuffer` between these contexts. Instead we have to serialize it and then recreate it on the other side.

However, this new api would still let us improve the serialization and reduce the amount of data transferred.

Even if we can't really transfer ownership, semantically, `transfer` should behave like `window.postMessage` in that extensions should not use transferred objects after they have transferred. I'm not sure if we can enforce this though

### Can we support other types? `Blob` or `OffscreenCanvas` for example?

Potentially, but not all of them. Because we can't support transfer all the time (see above), we can only support types that can be serialized. This means no `OffscreenCanvas` or other rich objects.

**Comment by mjbvz** [comment]
Copying a few people who may be interested in this:

- @eamodio for GitLens (or CodeStream contacts)
- @Tyriar for LunaPaint
- @rchiodo @rebornix  @connor4312  for notebooks (I think we'd have to add this feature to the notebook api as well)
- @hediet for DrawIO

**Comment by connor4312** [comment]
also cc @DonJayamanne

**Comment by Tyriar** [comment]
While I like the inspiration of the transfer parameter, we might need a different name as that's specifically transferring ownership of the buffer so it can no longer be used from where you're posting it from:

> The ownership of these objects is given to the destination side and they are no longer usable on the sending side.

So it's not transferring in our case, it's more copying quickly.

---

Also it would be convenient for the extension if typed arrays still get transferred correctly, [just like the web worker postMessage](https://stackoverflow.com/a/48178501/1156119):

```ts
// webview
const arr = new Uint8Array([1, 2, 3]);
postMessage({ arr }, arr.buffer);

// exthost
onmessage(m => {
  console.log(m.data.arr instanceof Uint8Array);
  // true
});
```

We wouldn't be transferring the typed array view but recording the type and recreating it on the other side using the `ArrayBuffer`. This would just be a really nice convenience and close the gap with the native `postMessage` transfer.

**Comment by mjbvz** [comment]
Current implementation is in #115664 if you want to test it out. 

@Tyriar I like the idea of reviving typed arrays too. I'll take a look to see what that would involve. Again, I think we'd only be able to enable this behavior if an extension opts in to it. Otherwise we may break existing extensions.

Also on the web, we can actually transfer ownership between the extension host worker and the main process. On desktop, that's currently not possible but I do like using the transfer semantic from web so that we can potentially use them more widely in the future

**Comment by eamodio** [comment]
Definitely agree with @Tyriar about trying to use `transfer` as the signal to this better serialization behavior (as it break the intent when you actually want to transfer ownership).

As for backward compatibility -- could we do something unorthodox, and say if an extension explicitly targets 1.54 or greater, we opt them into the new behavior, and if not they stick with the current? Because I can't see a case where anyone would want the current behavior (other than not break assumptions right now) going forward.

**Comment by hediet** [comment]
Thanks for the mention!
My input on this is:
* I generally like the idea
* For the drawio extension, I already use a Base64 encoding to send ArrayBuffers. Would be interesting to see how much this API further increases performance of data transfer.
* I find it spooky that passing a transfer array has an effect on how `msg` is serialized. Usually, I would expect `postMessage(msg, [])` to be the same as `postMessage(msg)`. If backwards compatibility is a real issue here since someone actually put an ArrayBuffer in msg, I guess this spooky behavior will be observed and might cause bugs.
It would be interesting to report an analytics event every time someone actually passes an array buffer. I doubt this is being done, in this case backwards compatibility would not be an issue.
* I really like @eamodio s idea of having different vscode apis for different extensions, depending on their targeted vscode version. However, I doubt this can be implemented without ugly and slow hacks like using the stack trace to figure out which extension calls an API.

**Comment by Tyriar** [comment]
> As for backward compatibility -- could we do something unorthodox, and say if an extension explicitly targets 1.54 or greater, we opt them into the new behavior, and if not they stick with the current?

I am also a fan of leveraging the vscode engine version as a means to do this "soft api breakage", imo since the current behavior is pretty unusable and most extensions would have a workaround anyway (`Array.from(...)`, base64, etc.). AFAIK we haven't done this before though and I'm not sure if it's easy to implement, we definitely don't want to create a stack.

An alternative if we want to just do this for all array buffers is to use options:

```ts
postMessage(msg, {
  serializeArrayBuffers: true
});
```

There may be special cases where extensions are transferring so much data that we don't want to walk the object though?

**Comment by mjbvz** [comment]
#115664 now serializes and restored typed arrays too (`Uint8`, ....).

If you have a chance, please test out the branch and let me know if there are any bugs and what the perf looks like for real world use cases

**Comment by mbehr1** [comment]
would be really nice if SharedArrayBuffers would be supported as well!

**Comment by mjbvz** [comment]
I update the extension api to change its behavior based on the engine version (you need to target 1.55+)

On the webview side, you should still pass a `transfer` parameter to `postMesage`. It will not effect serialization but will improve performance

**Comment by DonJayamanne** [comment]
@mjbvz so sorry for not looking at this even though i was pinged.
Thanks for this, i'll check this out. In WebView today we manually serialize Array buffers to overcome this issue.
However we have both types `ArrayBufferView` & `ArrayBuffer`.
Will this new serializer implementation support `ArrayBufferView` as well?

FYI - In Notebooks, IPYWidgets can end up sending array buffers to & fro.

**Comment by DonJayamanne** [comment]
@connor4312 thanks for pinging, this is useful for us (Jupyter extension with IPYWidgets).

**Comment by mjbvz** [comment]
@DonJayamanne We should serialize `Uint8Array` and other typed arrays. However `DataView` is currently not supported

**Comment by mjbvz** [comment]
@Tyriar Can you verify with Luna paint when you have a chance?

**Comment by Tyriar** [comment]
I've tried to verify this 3 times over the past few weeks and failed each time. The serialization/deserialization code got a little complex in my codebase but I don't believe this is fixed. Here are problems I was having:

- You mentioned `transfer` above but it's not in the types, it's not clear exactly what I need to do here
- Passing either a Uint8Array or ArrayBuffer from the ext host to webview ends up coming back as `{}`. This is the format of the message I was posting:
  <img width="486" alt="Screen Shot 2021-04-30 at 8 04 54 AM" src="https://user-images.githubusercontent.com/2193314/116714556-c0ca5a80-a98a-11eb-85f2-b9bbb1a56c9a.png">

I had similar problems getting webview -> ext host to work but didn't check that this time.

**Comment by mjbvz** [comment]
Thanks for checking @Tyriar. There seem to be two issues:

- It still required proposed api. This was just an oversight
- Only array buffers can be posted to the webview (not typed arrays).
     I think I had a merge conflict or left some bad code in after refactoring, because there are basically two function that do the same thing, but one is correct and the other is doing things incorrectly the old way. Will update to use the correct one

**Comment by DonJayamanne** [comment]
Are there any plans to support dataviews?
This is something Jupyter notebooks uses for ipywidgets.

**Comment by mjbvz** [comment]
Yes please file a separate issue

**Comment by mjbvz** [comment]
I'm going to push this to 1.57 so we can get more testing to make sure it doesn't cause any regressions

**Comment by mjbvz** [comment]
To verify:

1. Checkout https://github.com/microsoft/vscode-extension-samples/tree/vscode-115807
2. Open and run webview sample 
3. In the extension development window, run the `start cat coding` command
4. Open the developer tools
5. Now in the cat coding panel, run the `cat coding: do some refactoring command`
     The branch makes this command post a message with a UInt8Array to and from the webview
6. In the developer tools, you should now see:

    ![Screen Shot 2021-04-30 at 5 13 40 PM](https://user-images.githubusercontent.com/12821956/116764881-74593c00-a9d7-11eb-80e0-1256ca45966c.png)

7. The first message is from inside the webview. It shows that a `UInt8Array` has been received from the extension
8. The second message is posted from the webview to the extension host. It shows that a `UInt8Array` has been correctly posted over

9. Finally, try downgrading the engines version in `package.json` to `1.56`
10. Repeat the same steps. Now you should see:
    - The `data` object in the webview is now an object instead of a `Uint8Array`
    - The type printed in the extension host is `function Object()` instead of `Uint8Array`

**Comment by Tyriar** [comment]
I'll see if I can test this on the weekend if all I was missing was the enable proposed api flag 🤞 

Thanks for the sample!

**Comment by Tyriar** [comment]
Still doesn't seem to work with this setup:

```json
	"engines": {
		"vscode": "^1.55.0"
	},
	"enableProposedApi": true,
```

Same thing for vscode engine `^1.56.0`

exthost:

![image](https://user-images.githubusercontent.com/2193314/116785238-4ca4bb00-aa4d-11eb-89bd-5dbed1567618.png)

webview:

![image](https://user-images.githubusercontent.com/2193314/116785270-74941e80-aa4d-11eb-8ea3-80916a68207a.png)

**Comment by mjbvz** [comment]
@Tyriar Try with 1.57+ in the current OSS build (or first 1.57 insiders)  I moved this out of 1.56 because it's not urgent and I want more testing for potential regressions

**Comment by Tyriar** [comment]
Using 1.57.0 and enableProposedApi the transport time on save (webview -> exthost) drops from ~4s to ~400ms.

For opening (exthost -> webview), it went from ~10s to ~500ms 😳. @mjbvz so this is awesome and verified, but one complications I ran into and a reason why it was so hard to verify was that `await workspace.fs.readFile` returned a `Buffer` which doesn't get the perf benefits, so the typings of readFile are lying:

<img width="830" alt="Screen Shot 2021-05-30 at 7 58 42 AM" src="https://user-images.githubusercontent.com/2193314/120109098-dc0cbf00-c11c-11eb-9f85-637687e5cfad.png">

Needed to do this to fix it:

```ts
// Old
const data = await workspace.fs.readFile(uri);
// New
const data = new Uint8Array(await workspace.fs.readFile(uri));
```

The `Buffer` type should probably be checked and handled automatically.

**Comment by Tyriar** [comment]
@mjbvz is any issue tracking the finalization of this?
