### ISSUE TITLE
Errors not highlighted

### ISSUE THREAD

**Issue by saumyakraj** [microsoft/vscode#115962]
Issue Type: <b>Bug</b>

Errors are not being highlighted in my editor. I have only installed a couple of basic extensions.

Language - C++

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.45GB free)|
|Process Argv|--crash-reporter-id ef90918b-af68-4242-8a18-748d98c3a7c1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
cpptools|ms-|1.2.0
errorlens|use|3.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Bisect command in Command Palette to check whether one of your extensions is causing the problem.

**Comment by soetji** [comment]
Here's a screenshot with Bisect. There are syntax problems but they are not highlighted on the editor nor on the scrollbar.

<img width="1155" alt="Screen Shot 2021-02-12 at 11 02 45 AM" src="https://user-images.githubusercontent.com/220015/107791372-dcc24680-6d21-11eb-89ba-33a6e1fdb0c3.png">

**Comment by isidorn** [comment]
Closing this issue - first comment does not have enough details
Last comment from @soetji seems to be another issue, and the process of bisect does not seem completed

Thanks
