### ISSUE TITLE
Disposing activeTerminal causes te renderer to freeze

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#115927]
1. In an extension, have 

```
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		vscode.window.activeTerminal?.dispose();
	});

	context.subscriptions.push(disposable);
}
```

2. Open the terminal
3. Type in text (this is required, uninteracted terminals don't trigger this)
4. Run the command
5. After several seconds, the window will freeze

**Comment by connor4312** [comment]
Oh yea, I didn't check but this happens when closing any terminal... pretty sure this is new to recent builds, this would otherwise make the integrated terminal pretty risk to use for me (having to kill all vscode windows if I accidentally close a terminal)

**Comment by Tyriar** [comment]
It could have been an OS update, it also seems to repro at different rates for different people, I guess depending on hardware specs and usage habits.

**Comment by connor4312** [comment]
Sounds good. I will rebuild my PC in a week or two in order to attempt a workaround.

(Just waiting on the 3080 to ship 🙂 )

**Comment by Tyriar** [comment]
Jealous 🙄
