### ISSUE TITLE
CMD + V not working

### ISSUE THREAD

**Issue by superandrew** [microsoft/vscode#115934]
Issue Type: <b>Bug</b>

After some minutes working on a Mac, CMD+V stops working. Paste with mouse is still regularly working, so does CMD+C or CMD+X

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz (16 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (2.81GB free)|
|Process Argv|--crash-reporter-id d4e5f6f0-173b-403a-843e-1d2c5c2f2691|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ng-template|Ang|11.1.3
vscode-color|ans|0.4.5
folder-source-actions|bie|0.2.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.9.1
vscode-firefox-debug|fir|2.9.1
todo-tree|Gru|0.0.196
vscode-drawio|hed|1.2.0
vscode-redux-devtools|jin|1.0.2
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
code-coverage|mar|1.2.3
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.3.0
color-highlight|nau|2.3.0
typescript-hero|rbb|3.0.0
java|red|0.74.0
sonarlint-vscode|Son|1.20.1
autoimport|ste|1.5.3
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Please review the information at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

If that doesn't lead you to a resolution, use the Command Palette command to reload with all extensions disabled, then see if you can reproduce the problem. If this fixes the problem, reload with extensions re-enabled, then use the Bisect command to try and discover which extension is causing the issue.

**Comment by superandrew** [comment]
Ok sure, I will do this. But just to understand, since the problem began exactly today when I updated to 1.53, why do you think an extension is causing the issue?

**Comment by gjsjohnmurray** [comment]
You hadn't previous said that. And disabling extensions is one of the standard recommended steps when investigating.

The simpler and more detailed the repro you can offer, the better chance of a member of the dev team being able to recreate the problem.

**Comment by superandrew** [comment]
Ok, perfect, just to be clear my question was solely to understand if there was some previous report that extensions could have triggered this behavior.

I will check the recommended steps and get back with some more useful information.

Thank you

**Comment by superandrew** [comment]
@vscode-triage-bot this is not a question, this behavior returns in an inconsistent way, the only common factor being the version 1.53. I tried disabling the extensions but since this is not a behavior which is consistently reproducible, I'm not sure I could help anyway, so let the issue be closed
