### ISSUE TITLE
Crashes on file deleting

### ISSUE THREAD

**Issue by Zakariya1057** [microsoft/vscode#115995]
Issue Type: <b>Bug</b>

This has been an issue for the last week or so. When I delete a file from vscode, it freezes up and wont delete the file. Happens every time I attempt to delete a file.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 0aa69860-6581-4f07-8564-592212ce43be|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.11.1
vscode-intelephense-client|bme|1.6.3
gitlens|eam|11.2.1
php-intellisense|fel|2.3.14
todo-tree|Gru|0.0.196
sftp|lix|1.12.9
prettify-json|moh|0.0.3
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
php-docblocker|nei|2.1.0
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you reload with all extensions disabled?

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Zakariya1057** [comment]
The issue seems to specific to only a set amount of files in my folder. Once I deleted them in finder, I haven't had that issue again.

**Comment by isidorn** [comment]
Okey, closing this issue then. Thanks
