### ISSUE TITLE
Emmet plain text with repeat doesn't expand

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#115946]
I was testing https://github.com/emmetio/emmet/issues/632 in VS Code and then realized it didn't expand.

For example:
abbreviation: `{test}*5`
expected: `testtesttesttesttest`
actual: `[no expansion occurs]`

This issue is likely due to us rejecting the abbreviation within our own repo, even though it's valid.

**Comment by hantatsang** [comment]
Hi, I'm inspecting the issue and having trouble finding out why `{` character doesn't trigger emmet's completion provider. Do you have some idea? Potentially this issue comes from `vscode-emmet-helper`?
