### ISSUE TITLE
External link dialog box width overflows when URL is very long.

### ISSUE THREAD

**Issue by shubhendusaurabh** [microsoft/vscode#115933]
-Version: 1.53.0
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T15:56:04.185Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-65-generic

Steps to Reproduce:

1. Click to open very long URL e.g. `http://example.com/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpg`
2. External domain dialog box width overflows screen width.

![Screenshot from 2021-02-06 02-41-53](https://user-images.githubusercontent.com/1818387/107089615-ee3cb780-6824-11eb-8e43-19e8a594fef5.png)

Doesn't happen with all long URLs, but some that have long filename and have trouble wrapping. [Real World Link Example](https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vbWVkaWEucmJsLm1zL2ltYWdlP3U9JTJGZmlsZXMlMkYyMDE2JTJGMDUlMkYwMiUyRjYzNTk3ODA4NTg4NzU4ODg5OC0zNjI5NTcwOTVfZ2l2ZSUyNTIwYSUyNTIwbW91c2UlMjUyMGElMjUyMGNvb2tpZS5qcGcmaG89aHR0cHMlM0ElMkYlMkZhejYxNjU3OC52by5tc2VjbmQubmV0JnM9MjAwJmg9NzMwODUzZDEyNTNlOGViMjg5NDBjOTQ1NTMwMzVhM2MxMTlkMGVjZDcwM2I0NGFmYWMyMTA4N2VmZTU1NjFlOCZzaXplPTk4MHgmYz03MjY5NDA1MzIiLCJleHBpcmVzX2F0IjoxNjU5NTMwNjE4fQ.Z98TKPLScgMykHp8Bt56NEI3GHqRGQXGU6gDwdX5lJc/img.jpg?width=1200&height=628)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Not 100% sure who owns the open external dialog now, starting with @rzhao271

**Comment by rzhao271** [comment]
Seems to do with trusted domains, and I'm not sure how the URL should be shortened, or whether it should be shortened at all in this case.

Pinging @JacksonKearl and @lramos15

**Comment by lramos15** [comment]
I don't own this dialog as the work I did was just with URL encodings. The only comment I have to add is that we often truncate long strings with `...` and may want to do that here, the native mac dialog adds a scrollbar to keep the dialog in the center of the screen without being too wide and I quite like that. I'm not sure what other native dialogs do but definitely need to make it not so large as it doesn't quite overflow on my large monitor but takes up 95% of the screen.

**Comment by rzhao271** [comment]
@shubhendusaurabh for now, you can set the `window.dialogStyle` setting to `custom` to use VS Code's custom dialogs.

Because VS Code must work on multiple platforms, each with their own way of rendering native dialogs and links within such dialogs, there's no easy way to ensure that the out-of-box experience for _native_ dialogs displaying long links is pleasant on all platforms.
