### ISSUE TITLE
Autocomplete in settings goes away when removing a section of text

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#115975]
This bug has been around a long time and its quite frustrating when adding a new setting. I tried to see if there were similar issues but couldn't find one.

- VSCode Version: 1.53.0
- OS Version: Windows 10

Steps to Reproduce:

1. Add a new setting in settings.json (local or user)
2. whilst writing the setting delete the last word (ctrl + backspace or cmd + backspace)
3. the autosuggestion is lost and you need to start again to get it back

Example:
In this example if I remove the "send" in "anki.send" then I lose autocompletion until I start again.
![settings](https://user-images.githubusercontent.com/936006/107121664-9dac7500-688b-11eb-8b17-a9640425b920.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by hediet** [comment]
I'm very sure that this issue is independent of the settings or even JSON:
Whenever you press `ctrl` + `delete`, autocompletion closes!

I'm sure you are aware of it, but you can press `ctrl` + `space` to open the autocompletion window after it got closed!

**Comment by jrieken** [comment]
This is what happens

* when deleting a word with `option+backspace` IntelliSense stops
* then, when typing again, IntelliSense only auto-retriggers when typing at the end of a word
* @aeschli decided that JSON words include quotes so in that particular case are not typing at a word end.

**Comment by aeschli** [comment]
The issuer complains that after after option+backspace, code completion is lost. That's not JSON specific but can also be reproduced in TypeScript. 

![code-assist-stops](https://user-images.githubusercontent.com/6461412/107488053-23c80480-6b87-11eb-8797-105693da5029.gif)

**Comment by jrieken** [comment]
> The issuer complains that after after option+backspace, code completion is lost. 

as said, as design
