### ISSUE TITLE
Freeze on Zen Mode or Full Screen Mode

### ISSUE THREAD

**Issue by gennaro-ruccolo** [microsoft/vscode#115981]
- VSCode Version: 1,53
- OS Version: Debian Buster

Steps to Reproduce:

1.  Open visual studio then type ctrl+k z or press F11
2.  try to type ... the cursor disappear an the editor hangs
3. Disable Full Screen or Zen Mode and the editor works fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce

**Comment by gennaro-ruccolo** [comment]
Hi, code_1.52.1-1608136922_amd64.deb is the latest package that works.
Insiders , i have no idea . 

Thanks

**Comment by isidorn** [comment]
I can not reproduce, thus closing. If more users complain or if you can reproduce with insiders we can reopen. Thanks

**Comment by gennaro-ruccolo** [comment]
Finally I found a workaround: start code with --disable-gpu option for release > 1.52.1-1608136922_amd64
