### ISSUE TITLE
Did Quick Heals quarantine or delete a VS Code file when you updated to 1.44 and tried using it?

### ISSUE THREAD

**Issue by shashank5416** [microsoft/vscode#115952]
https://github.com/shashank5416/vs-code-extensionHostprocess.js/issues/1

**Comment by gjsjohnmurray** [comment]
Please contact your AV provider about this.

Also, 1.44 is outdated. Current release is 1.53

**Comment by shashank5416** [comment]
Oky i will contact to av provider
