### ISSUE TITLE
System making too many requests according to VS Code

### ISSUE THREAD

**Issue by ProcrastinatingEntrepreneur** [microsoft/vscode#115942]
Issue Type: <b>Bug</b>

Just following along to a LinkedIn Learning React tutorial.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.98GB free)|
|Process Argv|--crash-reporter-id b90a0554-2aa0-41a7-95fe-0f55429daee1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3400)|
|Memory (System)|12.45GB (10.55GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
remote-containers|ms-|0.155.1
remote-wsl|ms-|0.52.0
material-icon-theme|PKi|4.5.0
ayu|tea|0.20.1
vscode-icons|vsc|11.1.0
material-theme|zhu|3.9.13
npm-intellisense|chr|1.3.1
vscode-npm-script|eg2|0.3.13
vscode-pull-request-github|Git|0.22.0
vscode-docker|ms-|1.9.1
vscode-kubernetes-tools|ms-|1.2.3
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
heroku-command|pko|0.0.8
vscode-yaml|red|0.14.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
vscode-spotify|shy|3.2.1
docker|vsc|1.0.0
yaml|vsc|1.0.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
When and how does VS Code notify you or this? Maybe paste screenshots.
