### ISSUE TITLE
Find *first* instance/occurrence

### ISSUE THREAD

**Issue by nr1995** [microsoft/vscode#115973]
How can you find the first instance of the term you search for,
instead of the one closest to the caret?
If this feature doesn't exist, can you add it?  It seems pretty basic.
Thanks!

**Comment by hediet** [comment]
You can use `ctrl` + `f` then `enter` then `esc` for that!
It will jump to the first occurrence.

I understand that these are many key strokes if you need to do this more often (personally, I never needed this particular feature).
It should be quite easy to implement an extension that provides a command for this feature that you can bind to a shortcut!

**Comment by nr1995** [comment]
If you're jumping through occurrences one-by-one for the specific occurrence of the term you want
(but, for example, it doesn't actually exist)
then if you started at occurrence 13 of 35 (the instance closest to your caret)
you'll have to hold that “13” in your head,
or you'll not know when you've actually finished checking every occurrence.
I would argue it's pretty useful to always know where you started looking from.
It would be great to have the option of this as the default behaviour.
It would take barely any time to code.

**Comment by ArturoDent** [comment]
An extension or macro could do this easily.  See https://stackoverflow.com/a/57816422/836330 for a macro.
