### ISSUE TITLE
[Need help] Unable to write to User Settings because ... is not a registered configuration.

### ISSUE THREAD

**Issue by MiKr13** [microsoft/vscode#115992]
- VSCode Version: 1.53.0
- OS Version: Windows 10 20H2 (19042.746)

I am trying to create a new extension for vs code, in that process, I have to change two specific user settings namely `workbench.colorCustomizations` & `editor.tokenColorCustomizations` now when I am trying to change these values, the debugger is showing me this error, also it's automatically pretending my extension name in front:
![image](https://user-images.githubusercontent.com/34394719/107126681-3b796180-68d7-11eb-90b1-9444f26da85e.png)

My logic to apply settings looks something like this:
```js
const applySettings = (settings) => {
  if (!settings) {
    return // no settings, nothing to do
  }
  const workspaceSettings = getConfig()
  Object.keys(settings).forEach((k) => {
    workspaceSettings.update(k, settings[k], true).then(undefined, (reason) => {
      window.showErrorMessage(
        `You tried to apply \`${ k }: ${ settings[k] }\` but this is not a valid VS Code settings
          key/value pair.`
      )
    })
  })
}
```

What I have tried:

1. Checking my `user settings.json` for any errors.
2. Checking my `workspace settings.json` for any errors.
3. Checking the local extension tmp settings for any errors.

JSON is valid in all these cases.

Please help me as I have tried searching every thread but couldn't find anything wrong, plus resources are very scarce for this error.
Thank you.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
What's in your `getConfig` function? Did you pass your extension's name to the `workspace.getConfiguration` call?

**Comment by MiKr13** [comment]
> What's in your `getConfig` function? Did you pass your extension's name to the `workspace.getConfiguration` call?

Yes, you're right, I have provided the extension name there, found the error. Thanks for the help.
