### ISSUE TITLE
OPEN EDITOR PROBLEM

### ISSUE THREAD

**Issue by amadersoto** [microsoft/vscode#115923]
Issue Type: <b>Feature Request</b>

Hi, i am selim. culd you please remove 'OPEN EDITOR' option from vscode ?
it's really disturbing and opended filse gone bello .

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Right click on its title and you will be able to remove it yourself.

**Comment by isidorn** [comment]
It is actually removed in latest by default. But yeah, left click + hide
