### ISSUE TITLE
File Explorer Issue

### ISSUE THREAD

**Issue by Aamir2000** [microsoft/vscode#115939]
- Version: 1.53.0 (user setup)
- Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
- Date: 2021-02-03T20:36:38.611Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. Just try to expand and collapse folders in file explorer in the side menu

Does this issue occur when all extensions are disabled?: Yes/No
Yes

## Problem's Screenshot
As you can see in this image that scss folder is actually expanded but that icon bugs out and its not working properly and its annoying because I keep accidentally thinking that these files are not inside the folder they're supposed to be in, That views folder as well its collapsed but it shows that icon as if it was expanded for whatever reason. Its broken.

![image](https://user-images.githubusercontent.com/39049734/107092116-f8f94b80-6828-11eb-9e19-aea52160a629.png)

**Comment by ArturoDent** [comment]
So it is actually expanding and collapsing correctly but the icon is in the wrong state?  After a reload or restart does it start correctly and then go bad?

**Comment by Aamir2000** [comment]
> So it is actually expanding and collapsing correctly but the icon is in the wrong state? After a reload or restart does it start correctly and then go bad?

@ArturoDent Sometimes it fixes itself but then it breaks again I have to click on different folders expand and collapse randomly to fix the nested icon issues not sure what's happening I wasn't expecting icons to bug out like that because that's like the least expected thing to break in a code editor.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Aamir2000** [comment]
Sure I can try that will let you know soon

**Comment by isidorn** [comment]
Ok

**Comment by mvllow** [comment]
Using latest insiders and can add that clicking the folder icon (for me at least) works consistently but clicking the file name *does not* work 90% of the time. A double click on the file name acts as a single click and  *does* work 90% of the time

```
Version: 1.54.0-insider
Commit: 6eaef7d42f982a0e9b22ac465245fc2c27721fd0
Date: 2021-02-18T05:17:08.142Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```

**Comment by isidorn** [comment]
That is a seperate change @joaomoreno did for the tree.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/115873#issuecomment-781967348
