### ISSUE TITLE
running slow

### ISSUE THREAD

**Issue by I-Tsenov** [microsoft/vscode#115991]
Issue Type: <b>Performance Issue</b>

When running or debugging, the process takes 4-5 seconds. Before the update it was in an instant.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.92GB free)|
|Process Argv|C:\\Users\\Acer\\Desktop\\programming\\js practice and assignments\\JS BASICS.code-workspace --crash-reporter-id a3399133-da22-4aa0-b127-231497263874|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by I-Tsenov** [comment]
I tried some of the troubleshooting methods but I know It's not from my side of things, I didnt really expect someone to answer as well. Thank you for the response.  The additional information is that it is not only me, I am going through a university basic course right now and my colleagues have the same issue right after the new update to version 1.53.0. When I run the program I got 4-5 seconds delay on the output response. Also if I get into a infinity cicle and try to stop the operation it takes me like 4 clicks till it recognize the command. Collegues on the older version have no problems. I got only one extension, I disabled it and still no difference but I wasnt really surpriced. I'll probable roll out the an older update. Thanks again for caring!

P.S. Im on a laptop, which is powerful enough, modern cpu  (10 gen) and 16gb ram. Also Windows was recently preinstalled.

**Comment by isidorn** [comment]
What program are you running or debugging? What extension are you using for debugging?
provide somre repro steps

**Comment by I-Tsenov** [comment]
JS basic practice tasks, simple and light on the software. The extension is bracket pair colorizer. Running on Node Js. As I said I'll just roll out and wait for a fixed update. Thank you for your time, but I don't see possible fix on my side.

**Comment by isidorn** [comment]
Brakcet pair colorizer is a slow extension. Please file an issue against their repostiry.
Closing this as I can not reproduce
