### ISSUE TITLE
[sass] highlight bug and error

### ISSUE THREAD

**Issue by Sokol-ua** [Microsoft/vscode#11590]
- VSCode Version: 1.4.0
- OS Version: x64 Win 10 Enterprise, 

Strange errors in **each function**:

![screenshot_3](https://cloud.githubusercontent.com/assets/8975621/18278977/add4318e-745c-11e6-8213-df7d6b561e7d.png)

Compiles without errors, outputed styles are as expected.

**Comment by ivancuric** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/11633 ?

**Comment by Sokolua** [comment]
@ivancuric about syntax highlight yes, also I'm experiencing strange error with **each** loop as on second screenshot.

**Comment by aeschli** [comment]
The @each is a separate issue. I turn this issues in one for it. Hope that's ok for you.

**Comment by Sokolua** [comment]
@aeschli OK, thanks. With new VSCode update to 1.5.1 I'm no longer experiencing this highlight bug. Each is still on th board...

**Comment by aeschli** [comment]
All issues got fixed in the meantime. Verified in 1.10-insiders.
![image](https://cloud.githubusercontent.com/assets/6461412/23248180/534c1f20-f99e-11e6-8108-72e88285f621.png)
