### ISSUE TITLE
navigator.clipboard API is broken within webview in insiders

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115925]
The `navigator.clipboard` API seems to have broken in the latest insiders, works in stable and 8490d3dde4 (last insiders before release).

Repro:

1. Install Luna Paint
2. Open an image
3. Take a screenshot
4. Ctrl+v

Version: 1.54.0-insider (user setup)
Commit: 52838cf6799cc448e738677ec37e86cf62a5bd89
Date: 2021-02-05T05:17:50.117Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
There haven't been any changes in the webview related to copy/paste since release. Do you see any error messages?

**Comment by Tyriar** [comment]
`await navigator.clipboard.read()` never ends up resolving, `navigator.clipboard.write([item])`  work working though?

@deepak1556 I see Electron updated from 11.2.1 to 11.2.2?

**Comment by Tyriar** [comment]
Just tested on macOS and it also happens there as of the last Insiders.

**Comment by Tyriar** [comment]
I had a chat with @deepak1556 and the only thing related in Electron 11.2.2 is trusted types which shouldn't affect this, so I tried both Electron 11.2.2 and 11.2.1 in Code - OSS and both of them don't work on master. So this seems unrelated to Electron.

**Comment by Tyriar** [comment]
I'm doing a bisect to try isolate the commit

**Comment by Tyriar** [comment]
@mjbvz it's caused by https://github.com/microsoft/vscode/commit/7d5052f50846a8d2d52106b782f6260ccd4f7deb

**Comment by mjbvz** [comment]
@Tyriar What are your thoughts on this since it apparently never worked on the web?

**Comment by Tyriar** [comment]
I think custom editors need a way to copy and paste in order to reach their potential. If that's done by having a single domain per extension so that there's an extra _single_ permissions dialog per extension (asking for every single webview will suck), or if it needs to be an extension API to proxy it over from the client, either works for me.

And if either of those take too long for Feb, allowing just paste in the meantime would be ideal since I'm using Luna Paint every day in stable now so Insiders isn't getting much love.

**Comment by Tyriar** [comment]
Back to insiders! 🕺 🎉
