### ISSUE TITLE
vscode mixes up remote processes with compound launch configuration 

### ISSUE THREAD

**Issue by dejangeci** [microsoft/vscode#115996]
- VS Code version:
  - Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
  - Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:50.117Z)
- OS version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Launch compund debug configuration (4 configs in this case) that attaches to docker containers
2. End up with unbound breakpoints for some of the projects randomly

Does this issue occur when all extensions are disabled?: Yes, in both regular and insider version

Problem completely goes away when `"debug.javascript.usePreview": false` is set.

In the screenshot below you can see that the selected launch config does not match the selected process in the sidebar. They are matched randomly on every launch, and some processes are missing their names. Launching individual configurations works fine.

![image](https://user-images.githubusercontent.com/1375514/107128212-4a064f80-68bc-11eb-95db-4fe017e0642f.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6300 Six-Core Processor              (6 x 3511)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none<details>

<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by connor4312** [comment]
That's interesting. Can you share your launch.json to make reproduction easier?

**Comment by connor4312** [comment]
This was a fun issue. We keep a map of 'pending' sessions when we wait for VS code to set up a debug session for the process we know about. The IDs of the session were process IDs. In the attach case, we don't know the process ID and were always using `0`. This could cause mix ups, or sessions to not get attached at all (which is what I saw on my machine).

Fixed in the [next nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)

**Comment by connor4312** [comment]
For verification, have a launch config like this:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "attach",
      "name": "a",
      "port": 9229,
    },
    {
      "type": "pwa-node",
      "request": "attach",
      "name": "b",
      "port": 9230,
    },
    {
      "type": "pwa-node",
      "request": "attach",
      "name": "c",
      "port": 9231,
    },
  ],
  "compounds": [
    {
      "name": "Compound",
      "configurations": ["a", "b", "c"]
    }
  ]
}

```

And run `node --inspect=<port> -e 'setInterval(() => undefined, 1000)'` 3x for each of those. Then, run "Compound" and verify that it attaches to each process
