### ISSUE TITLE
Task autorun permission notification lacks information if "runOn": "folderOpen" comes from a .code-workspace file

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#115990]
Issue Type: <b>Bug</b>

1. Create a folder with a .vscode/tasks.json file defining a `"runOn": "folderOpen"` task whose name indicates it has come from this file.
2. Start VS Code and close any pre-opened folder or workspace.
3. Add your folder to a workspace and save the workspace as foo.code-workspace
4. Edit foo.code-workspace to add a `tasks` object containing a `"runOn": "folderOpen"` task whose name indicates it has come from the .code-workspace file.
5. Open the workspace.
6. Run either of the tasks manually to trigger the notification asking for permission to run these tasks automatically on future opens.
7. Observe that the notification text talks about "This folder" and a "'tasks.json'" file, when in fact one of the two tasks listed has come from the code-workspace file. In another scenario all autorun tasks could have come from the workspace (i.e. the code.workspace file) and no folder nor tasks.json file be involved in autorun.

![image](https://user-images.githubusercontent.com/6726799/107126746-7fee0880-68a9-11eb-85c0-66f357ddb8da.png)

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:50.117Z)
OS version: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
I opted for verbosity here, since it's important that the user know what's going on.
- Changed language to talk about "workspace" since that is how we refer to folder/workspace-with-codeworkspace-file.
- Added a list of the files that the tasks come from.
- Changed the last button to "Open file(s)". It will open all the files that the tasks come from.

![image](https://user-images.githubusercontent.com/38270282/107656990-fceff800-6c84-11eb-8bc3-50f84e45a5ba.png)

**Comment by gjsjohnmurray** [comment]
Afterthought: the capitalization in the button labels look a bit odd. To match standard style for notification buttons I think they should be `Allow and Run`  and `Open Files`

**Comment by alexr00** [comment]
Thanks for verifying! On the capitalization note: I think I heard from @misolori that unless we are specifically referencing a command, we should use sentence casing. Most of our notifications don't do this though.
