### ISSUE TITLE
Tab wrap - improve wrapped tabs with color/symbol support

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#115904]
When my tab bar is basically at its max size, and would wrap if one tab is just a little longer, and then I'm editing a JavaScript file, which likes to say all in-progress code has syntax errors 50% of the time I'm writing it, this makes the tab show the newly relevant number of errors, and then it pops a tab onto the next line, and my whole code editor moves down a line. Then it shifts back up as I fix the syntax error by typical coding process. This toggles the code editor position every 5 seconds. That's not a good UX, but I can't think of a concrete way to solve it. Just wanted to let you know that I request the feature of this UX being improved.

**Comment by bpasero** [comment]
@sdegutis do you have `workbench.editor.decorations.badges` enabled?

Does it help if you configure `workbench.editor.tabSizing: shrink`?

**Comment by sdegutis** [comment]
> @sdegutis do you have `workbench.editor.decorations.badges` enabled?

Yes

> Does it help if you configure `workbench.editor.tabSizing: shrink`?

That probably solves it, but not in a great way, since now I can't see the last third of every tab.

Either way, I'm just not satisfied with wrapped tabs, so I'm turning them off.

**Comment by bpasero** [comment]
> Either way, I'm just not satisfied with wrapped tabs, so I'm turning them off.

We can still have issues opened for suggestions how to improve it. If you can think of an issue that improves wrapped tabs that has not been filed already (https://github.com/microsoft/vscode/labels/workbench-tabs) then feel free to open them.

**Comment by sdegutis** [comment]
Feel free to reopen this issue if it makes sense for you. I'm unsubscribing for now.
