### ISSUE TITLE
Error when logging in to settings sync. Logged out of settings sync after VSCode restart

### ISSUE THREAD

**Issue by FlorianW7** [microsoft/vscode#115994]
- VSCode Version: 1.53
- OS Version: Windows 10 20H2 19042.789

Steps to Reproduce:

1. Turn on setting sync
2. Log in via Microsoft or GitHub account

Does this issue occur when all extensions are disabled?: Yes

While trying to log in to a microsoft or github account via the settings sync feature, I am getting the following error message: 

> Writing login information to the keychain failed with error 'Not enough memory resources are available to process this command.'.
>

When I restart visual studio code the settings sync feature is still turned on, but I am not signed in to any accounts.
The same error occurs for me in the newest visual studio code insider version (v1.54)

![Screenshot 2021-02-06 200308](https://user-images.githubusercontent.com/39637840/107127431-58ea0380-68b6-11eb-81e5-2212791703fd.png)

**Comment by RMacfarlane** [comment]
This error is coming from Windows when we try to store the credential information there. Can you try clearing your temp folder or running DISM to try clean boot mode?

**Comment by FlorianW7** [comment]
Clearing my temp folder seemed to have solved this issue! 

@RMacfarlane thank you so much for your help.
