### ISSUE TITLE
[Notebook] WorkspaceEdit.replaceNotebookMetadata() unsets cell languages.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#115912]
- VSCode Version: 1.53
- OS Version: Windows

Steps to Reproduce:

While developing the .NET Interactive notebook extension, I have the following scenario:

- In extension activation, subscribe to `notebook.onDidChangeActiveNotebookKernel()`
- In that handler, call `WorkspaceEdit.replcaeNotebookMetadata()`

Result:
After calling `workspace.applyEdit()`, the cell's languages have been changed, it seems to the first entry in the `document.languages` property.

Expected:
The cell's languages should remain unchanged.

Workaround:
For now I'm capturing all cell data before updating the metadata, including language, then after the document metadata has been updated, I call `WorkspaceEdit.replaceNotebookCells()` to ensure the language is preserved.

Does this issue occur when all extensions are disabled?: N/A.

**Comment by jrieken** [comment]
> In that handler, call WorkspaceEdit.replcaeNotebookMetadata()

Can you point us the code sample? When calling replaceNotebookMetadata it actually replaces everything. So, when you don't pass languages along, the you will loose them. A trick is use this pattern `replcaeNotebookMetadata({ ...currentMetadat, newProp: 1, newProp2: true})`. Tho, also note that I am working on https://github.com/microsoft/vscode/issues/116333 which should make metadata modification more simple

**Comment by jrieken** [comment]
> Tho, also note that I am working on #116333 which should make metadata modification more simple

Please note that happened today. So, please update and let us know what issue you are running into

**Comment by brettfo** [comment]
To test this I need to wait until microsoft/vscode-jupyter#4796 is addressed, but as soon as that's handled, I'll come back to this.

**Comment by jrieken** [comment]
Closing as obsolete, there is no more languages in notebook metadata
