### ISSUE TITLE
After changing case of a file, the filename appears twice in search results and replaces are currupt in that file

### ISSUE THREAD

**Issue by jan-scorl** [microsoft/vscode#115972]
This is basically a duplicate of #111407.
The suggested workaround of renaming the file to another word and then back to the desired version did work for me but only if restarting VSCode in between.

- VSCode Version: 1.53.0
- OS Version: macOS 11.2

Steps to Reproduce:

1. Change case of a file
2. Search for something within that file

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
I can reproduce the duplicated results if an editor tab for that file is open, but if and reopen I close the editor tab, the duplication goes away. Does this work for you?

**Comment by JacksonKearl** [comment]
Possible duplicate of https://github.com/microsoft/vscode/issues/107778.

**Comment by jan-scorl** [comment]
If I close the editor tab, the duplication in the search results disappears.
Once I open it again, the duplication returns.

**Comment by JacksonKearl** [comment]
Thanks, going to close as duplicate of #107778
