### ISSUE TITLE
Custom editors show non-Windows path in tab and tooltip

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#115924]
The description should be hidden just like regular untitled files imo.

Custom editor:

![image](https://user-images.githubusercontent.com/2193314/107081354-682e5b80-67a7-11eb-8197-4665ed9eebbc.png)

Regular untitled:

![image](https://user-images.githubusercontent.com/2193314/107081378-71b7c380-67a7-11eb-933b-3c5c157df745.png)

**Comment by mjbvz** [comment]
@Tyriar Can you please add some information on how you are opening these untitled files in the first place?

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/107518640-19484380-6b64-11eb-9417-482d8f04ae21.png)

My `CustomDocument` class exposes `readonly uri: Uri` as per the interface.

**Comment by mjbvz** [comment]
That command is using `vscode.open` with a `untitled:` uri, correct?

**Comment by Tyriar** [comment]
Oh yeah I create the URI:

```ts
      const uri = Uri.joinPath(workspaceFolders[0].uri, `NewImage-${PaintEditorProvider._nextUntitledId++}.png`)
        .with({ scheme: 'untitled' });
      ...
      commands.executeCommand('vscode.openWith', uri, PaintEditorProvider.viewType);
```

Derived from https://github.com/microsoft/vscode-extension-samples/blob/502cba6fc040c91eef80b1385bd5fed8da24d90b/custom-editor-sample/src/pawDrawEditor.ts#L206-L209

**Comment by Tyriar** [comment]
Use in Remote - WSL is now broken:

![image](https://user-images.githubusercontent.com/2193314/138121971-d4dbc321-ae6b-4e96-8eaa-93718d9acf38.png)

**Comment by mjbvz** [comment]
That isn't custom editor specific. Opened https://github.com/microsoft/vscode/issues/135506 to track this issue
