### ISSUE TITLE
Option to Specify Line Height as a Multiple of Font Size

### ISSUE THREAD

**Issue by cpsauer** [microsoft/vscode#115960]
Small usability tweak request: 
It'd be really nice to be able to specify editor line height as a multiple of font size. 

Pitch for why it's worth considering: 
- It'd be more consistent with the other line height settings in VSCode. (markdown.preview.lineHeight and terminal.integrated.lineHeight are both multipliers--only editor.lineHeight is absolute).
-  It would also unbreak dynamically resizing code on the fly, which is often important while communicating, like in teaching.
- Seems like lots of people change this setting, since [VSCode's spacing default](https://github.com/microsoft/vscode/issues/23806) is significantly bigger than most editors and people like seeing lots of code on the page. And [this leads to confusion](https://github.com/microsoft/vscode/issues/33968) because most line spacing settings are a multiplier, in VSCode and elsewhere.

Being able to (optionally) specify the value in ems would solve the problem, while remaining backwards compatible. To give concrete examples, "15" could remain a valid value (implicitly in pixels), but 1.25em could also be a valid value that would rescale properly if the text size were changed.

Thank you for your consideration--and a truly excellent piece of software!

**Comment by cpsauer** [comment]
Good folk of #33968 (@smtnsk, @yume-chan, @luangong), if you still believe in VSCode line height being expressible as a ratio, is there any chance we could get your upvote here to get it over the finish line?

I think we've got a clean, backwards compatible way to do it, and just a few more days to get those last few votes.

(commenting here and tagging bc #33968 is locked)

**Comment by cpsauer** [comment]
One other really great idea from @appetite-j in #105888: Just autodetect and do the right thing for whichever the user enters. If line height is less than 4, assume it's a multiple of font size, otherwise assume it's an absolute size in pixels.

**Comment by usernamehw** [comment]
It might not be a perfect solution, but this feature can still be implemented using the existing setting:

```js
"editor.lineHeight": 0, // Default - relative to fontSize 1.35
"editor.lineHeight": 1.5,// > 0 <= 3 - Relative line number (too small to be a viable absolute)  
"editor.lineHeight": 25,// > 3 - Absolute value
```

**Comment by alexdima** [comment]
To verify, configure `editor.lineHeight` to a value `<8`. The line height will be interpreted as a multiplier for `editor.fontSize`. For values above `8`, the `editor.lineHeight` will be interpreted as the literal value of the line height.

**Comment by rzhao271** [comment]
It seems that setting `editor.lineHeight` to 8 results in it being interpreted in px. Can that be added to the setting description? I thought only values strictly above 8 would end up that way.
