### ISSUE TITLE
Keyboard shortcut for Close all tabs except current working tab

### ISSUE THREAD

**Issue by abeprincec** [microsoft/vscode#115906]
I want to be able to code all other tabs expect the current focused tab. I know there is a way to do it from right clicking the tab and clicking "Close Others". It would be nice to have that functionality in a keyboard shortcut.

**Comment by gjsjohnmurray** [comment]
Doesn't `workbench.action.closeOtherEditors` do this? In Command Palette it is called "View: Close Other Editors in Group"

**Comment by abeprincec** [comment]
Thank you that solves my issues !

**Comment by gjsjohnmurray** [comment]
:+1: please close the issue.
