### ISSUE TITLE
Can't update, can't uninstall, can't install fresh.

### ISSUE THREAD

**Issue by hsmyers** [microsoft/vscode#115936]
- VSCode Version: 
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
- OS Version: 
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.21301 N/A Build 21301

Steps to Reproduce:

1. check for updates
2. watch error messages referring to path that doesn't exist
3. click to uninstall
4. error message referring to path that doesn't exist—the same tree as update error
5. attempt to install fresh copy of vscode
6. leads to the same error chain as 2. above.

This is a catch-22 loop. The **bad user path** is the source. Please supply a fix…

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error messages?

**Comment by hsmyers** [comment]
No, sad to say I fixed the problem. I got to thinking about the uninstall
error message and duplicated the missing directory tree. That worked to
remove the message and successfully uninstall. Then, following the original
advice from a similar issue, I reinstalled it without a problem. Close
this, and point to my stubborn solution should it occur again.
