### ISSUE TITLE
empty snippets menu after latest update

### ISSUE THREAD

**Issue by dankeyy** [microsoft/vscode#115978]
- VSCode Version: latest. i think 1.53
![Screenshot_20210206_175422](https://user-images.githubusercontent.com/74069206/107123219-03592b00-68a5-11eb-86e9-188c4d0f415f.png)

- OS Version: win 10 and manjaro alike. Talked to a few people. also said it got messed up after update.

I'm of course talking about the "insert snippet" feature in the command palette (which offers stuff like "if `__name__ ==`...").

Steps to Reproduce:

1. Try to insert snippet at latest version. Menu will not show any results of the usual builtin snippets.

Another thing, I also tried in an old vscode before the latest update in windows 10. It worked fine.
Then I got an update and it just broke. Menu was empty and no snippets could be inserted.

Does this issue occur when all extensions are disabled?: Yes. Though I'm pretty sure it gets it from the extensions but nevermind, doesn't work either way. Previously it was able to fetch those snippets.

**Comment by gjsjohnmurray** [comment]
What language are you coding in?

Does the problem also occur if you use File\New and change the new file's language mode to 'Batch'? For me this gives two snippets:

![image](https://user-images.githubusercontent.com/6726799/107123642-8757e680-6896-11eb-8e09-3304cb528773.png)

Tip: in future if you use the 'Report Issue' option on the Help menu your version and platform details will be autofilled.

**Comment by dankeyy** [comment]
> What language are you coding in?
> 
> Does the problem also occur if you use File\New and change the new file's language mode to 'Batch'? For me this gives two snippets:
> 
> ![image](https://user-images.githubusercontent.com/6726799/107123642-8757e680-6896-11eb-8e09-3304cb528773.png)
> 
> Tip: in future if you use the 'Report Issue' option on the Help menu your version and platform details will be autofilled.

tested for python and haskell

**Comment by gjsjohnmurray** [comment]
Maybe after the 1.53 update one of your extensions has started to crash the extension host process which all extensions share. Try running the `Start Extension Bisect` command to investigate this.

**Comment by dankeyy** [comment]
> Maybe after the 1.53 update one of your extensions has started to crash the extension host process which all extensions share. Try running the `Start Extension Bisect` command to investigate this.

![Screenshot_20210206_200248](https://user-images.githubusercontent.com/74069206/107126065-4ec80500-68b6-11eb-8ed2-485bd5bdd32e.png)

**Comment by jrieken** [comment]
Out of the box, VS Code doesn't ship snippets for python or haskell. Not sure what you are expecting

**Comment by jeanp413** [comment]
@dankeyy in the case of python snippets, the python extension removed all the snippets in their latest release https://github.com/microsoft/vscode-python/issues/15220
