### ISSUE TITLE
Emmet doesnt work after January 2021 update

### ISSUE THREAD

**Issue by crisamdegracia** [microsoft/vscode#115979]
Issue Type: <b>Bug</b>

"emmet.triggerExpansionOnTab": true,

Nothing happens when pressing tab on HTML tags.

then this error always popping

Running the contributed command: 'emmet.expandAbbreviation' failed.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics     (4 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (11.91GB free)|
|Process Argv|--crash-reporter-id 10cecce3-b73c-420d-b7aa-f8570e67212e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
vscode-html-css|ecm|1.9.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.1
phpcs|ika|1.0.5
vscode-phpfmt|kok|1.0.30
vscode-autoprefixer|mrm|3.0.1
LiveServer|rit|5.6.1
lorem-ipsum|Tyr|1.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem still happen after you run the Command Palette command `Developer: Reload With Extensions Disabled` ? If not, reload with your extensions enabled, then use `Help: Start Extension Bisect` to identify which of your extensions is crashing the process shared by all extensions, including the built-in Emmet extension.

**Comment by crisamdegracia** [comment]
Start Extension Bisect 

 it works! Thanks! @gjsjohnmurray
