### ISSUE TITLE
Extensions should be able to define code folding regions in a document

### ISSUE THREAD

**Issue by daschult** [Microsoft/vscode#11594]
I looked in the API, but I couldn't find a way for an extension to define code folding regions. If such a feature doesn't exist, it should.

**Comment by siegebell** [comment]
See #3422 & #9786.

**Comment by ramya-rao-a** [comment]
The discussion on what should and shouldn't be exposed to extensions in the code folding API is already tracked in #9786 like @siegebell mentioned. Closing this issue as duplicate.
