### ISSUE TITLE
Don't show custom hover under context menu 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#115926]
![Feb-05-2021 12-16-09](https://user-images.githubusercontent.com/323878/107084542-0d4b3300-67ac-11eb-8452-2d59a2269fcf.gif)

**Comment by alexr00** [comment]
@roblourens is this on desktop VS Code on Mac?

**Comment by roblourens** [comment]
Yes

**Comment by alexr00** [comment]
I can't repro on Windows. be820b8f425aa07a3514933e766666b022c6df35 may have fixed this issue. Are you still seeing it?

**Comment by roblourens** [comment]
Yes

**Comment by alexr00** [comment]
@roblourens do you still see this?
