### ISSUE TITLE
Source Control no longer syncing

### ISSUE THREAD

**Issue by trv-rpeoples** [microsoft/vscode#115937]
In last month's (December 2020) release of VSCode, after making a change to a repo, you would press Cmd+Enter (on Mac) after entering a commit message to commit changes, and then an asterisk would appear next to the branch name to indicate that there were unsynced changes that needed to be pushed to the origin. In the January 2021 release of VSCode, the asterisk no longer appears, and clicking on the sync icon does nothing. I now have to click the ellipsis and choose one of the Push options.

**Comment by eamodio** [comment]
Can you provide more information? Does this happen with all repositories? What OS are you on, git version, etc.

**Comment by trv-rpeoples** [comment]
This appears to happen on every repo. I am using multiple folders in a workspace. Using VSCode 1.53.0 on Mac 10.14.6 via Remote: SSH to a RHEL7 server that has Git version 1.8.3.1.

**Comment by trv-rpeoples** [comment]
Figuring this was related to the ancient version of Git that's available on RHEL7, I moved to the software collection version instead, which was a pain to get working system-wide:

As root:
```bash
yum remove -y git
yum install -y rh-git218
ln -s /opt/rh/rh-git218/enable /etc/profile.d/z-rh-git218.sh
source /etc/profile
git --version
```

Output:
```bash
git version 2.18.4
```

Everything appears to be working now. Thanks.
