### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by anudeepdaruvuri2021** [microsoft/vscode#115976]
Issue Type: <b>Bug</b>

I dont know what happend its popping up that your code is corrupted please reinstall, as i did three times reinstalling but no use, And also on top of the logo near visual studio code its saying Unsupported.
Please give me a solution.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.20GB free)|
|Process Argv|--crash-reporter-id 7234c0fa-dd0d-4d2c-b109-0751b3bba31d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.2
beautify|Hoo|1.5.0
kite|kit|0.136.0
theme-monokai-pro-vscode|mon|1.1.18
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.2
cpptools|ms-|1.2.0
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
ruby|reb|0.28.1
java|red|0.74.0
LiveServer|rit|5.6.1
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
vscode-ruby|win|0.28.0
material-theme|zhu|3.9.13

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Some possible causes:
- antivirus product is damaging the set of files the VS Code installer put onto your device.
- an extension is modifying one of the VS Code files.

I suggest you uninstall VS Code, then disable AV, then install again. When installation completes, don't launch VS Code normally. Instead open a Windows command prompt and use this command:
```
code --disable-extensions
```

If you no longer get the "Unsupported" problem, close VS Code and launch it normally. If the problem returns, suspect one of your extensions.

Re-enable your AV afterwards. If the problem returns, suspect you AV.
