### ISSUE TITLE
Focus does not always return to editor when moving from VS Code

### ISSUE THREAD

**Issue by chrisnorman7** [microsoft/vscode#115968]
Issue Type: <b>Bug</b>

* Open VS code (with or without extensions enabled).

* Select a file with control p.

* Do some edits in the file.

* Switch away (to a web browser for example).

* Observe that occasionally focus is not in the editor when you return.

On my system, I have to press f6, followed by shift f6 to get back to the editor.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.47GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id a8e6cd95-80e9-4b96-82fa-d30c9dc9a22e|
|Screen Reader|yes|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by efkan** [comment]
The same here on a Mac.

Wile I'm working on another window (for instance on the browser), I can create a new file by clicking "New File" command from context menu but I cannot give a name to the new file because focus won't be on VSCode.

https://user-images.githubusercontent.com/6974198/107144086-cf841100-6949-11eb-841f-646a46d2cd11.mov

**Comment by isidorn** [comment]
This is a known electron issue
Sorry but I do not know the exact issue number, feel free to search in our repository
