### ISSUE TITLE
Run | Debug lens not working for Maven tests in vscode

### ISSUE THREAD

**Issue by vswamire** [microsoft/vscode#115928]
I'm currently working with Maven project. the tests are already being in the project, I need to debug the tests. Code Run | debug is not appearing in the vscode, tried various ways and workarounds. but nothing seems to be working out

Can you please help me to resolve this issue.

**Comment by yume-chan** [comment]
Can you add your VS Code version and installed extension list?

Code has no built-in support for Maven tests so an extension must be installed to add this feature.

**Comment by vswamire** [comment]
I've attached the extension list and vscode version, please take a look and let me know.

I've figured out that, the vscode is not recognizing the tests which does not have main method, is there any workarounds for this issue.

![Screen Shot 2021-02-08 at 9 30 32 AM (2)](https://user-images.githubusercontent.com/77068971/107233973-298be180-69f1-11eb-933a-0181562a3a6f.png)
