### ISSUE TITLE
Terminal error message in vscode

### ISSUE THREAD

**Issue by harishk97** [microsoft/vscode#115966]
Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.
'Z:/projects\notepadAlias.cmd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by harishk97** [comment]
no

**Comment by fast-and-curious-1910** [comment]
@harishk97 use 'Z:\projects\notepadAilias.cmd' or just 
```cmd
cd Z:/projects/
./notepadAilias.cmd
```

**Comment by harishk97** [comment]
This is been resolved. Had issus with my cmd itself. Resolved now by microsoft support, thanks for looking into it.
