### ISSUE TITLE
Trusted Workspaces editor content doesn't reload after Grant / Deny actioned from gearwheel menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#115977]
Issue Type: <b>Bug</b>

Testing #115961 by building from master.

1. Build and install an extension whose package.json includes `	"requiresWorkspaceTrust": "onStart"` as well as `"enableProposedApi": true` and a `workspaceContains` activation event.
2. Open a workspace containing a file that triggers activation of the extension.
3. Observe that the gearwheel (bottom left) has a trust-related badge and hover message.
4.  From its menu choose 'Manage Trusted Workspaces (1)', which opens the Trusted Workspaces editor. Unless you have previously (un)trusted any workspaces the JSON file's object will be empty.
5. From the gearwheel menu choose 'Grant Workspace Trust' and OK the dialog.
6. Observe that the gearwheel badge disappears :+1: and the status bar shows the Workspace Trust indicator as a green icon :+1: but the Trusted Workspaces editor content hasn't changed :bug:
7. Close that editor and repoen it from the gearwheel menu to see the change that step 5 actually made.

VS Code version: Code - OSS Dev 1.54.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19042

**Comment by lszomoru** [comment]
@gjsjohnmurray, thank you very much for taking this for a spin and thanks for filing the first issue. Adding @sbatten.

**Comment by sbatten** [comment]
yes, thanks for taking the time to test. the current editor experience will likely be removed in favor of something much more featureful so there is currently minimal code to make this feature work. Ideally, the resolution of this bug is the deprecation of this editor.

**Comment by lszomoru** [comment]
Closing this issue as we are actively working on a 1st class UI for managing workspace trust.

**Comment by aeschli** [comment]
@lszomoru Is there something to verify here?

**Comment by lszomoru** [comment]
@aeschli, nope. Updated the labels.
