### ISSUE TITLE
Provide a way to remove a CodeLens in the resolveCodeLens

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#11599]
- VSCode Version: `Version 1.5.0-insider (1.5.0-insider)` 538cd9ded5a471fbb20920f01eff9c8df4b83ee9
- OS Version: `OS X El Capitan Version 10.11.6 (15G31)`

Sometimes you want the work to ultimately show a CodeLens to be deferred as much as possible, so it would be create if there was a way to signal that CodeLens being resolve isn't actually desired anymore.

For example, it might be desirable to not show a "references" CodeLens if there are no references (rather than having to say 'no references' or something like that). Basically for any CodeLens where the work involved in actually resolving it is too expensive in the providing phase.

**Comment by jrieken** [comment]
Not convinced - whenever you remove or add a lens it moves the lines up or down. That's the reason  why we first gather all lens locations and then fill in the visible ones. In early versions of this feature we used to have what you describe and it was not fun to use.
