### ISSUE TITLE
Tooltip keeps lingering and overlay UI elements

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#115930]
- VSCode Version: 1.5.4-insiders
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Opened MDN link for a CSS property
2. Select "Configure Trusted Domain"

After step 1, occasionally the MDN link tooltip gets stuck and overlays content like the prompt from step 2.

![image](https://user-images.githubusercontent.com/8599/107087190-ed1d7300-67af-11eb-987d-2a9984899bd1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@digitarald and in this case moving the mouse does not remove the hover?

Can you please try to reproduce at https://vscode-web-test-playground.azurewebsites.net/?enter=true so that you are able to report this against Chrome if it reproduces.

**Comment by digitarald** [comment]
> […] in this case moving the mouse does not remove the hover?

Correct.

> Can you please try to reproduce […]

It was a rare issue already and so far I have not had luck reproducing it in the web. Not sure if its just bad luck or helps.

**Comment by bpasero** [comment]
But does it reproduce easily for you on desktop?

**Comment by digitarald** [comment]
> But does it reproduce easily for you on desktop?

Not reliably. Have not seen it since I filed this issue.

**Comment by bpasero** [comment]
Ok, I fear without repro for Chrome, this issue will be hard to address.
