### ISSUE TITLE
ASP.NET 5 rc1 application showing unresolved items 

### ISSUE THREAD

**Issue by spboyer** [Microsoft/vscode#116]
Same application in Atom is fine. Application runs without issue. application created using 

`yo aspnet`, basic web application no auth. ran `dnu restore`

Code - Version 0.10.1 (0.10.1)

![screen shot 2015-11-18 at 4 56 45 pm](https://cloud.githubusercontent.com/assets/7681382/11255723/c0ad8b80-8e15-11e5-8590-39c91c53f176.png)

@chrisdias

**Comment by spboyer** [comment]
If you were on the insiders program and were using the Auto update feature, download the app and replace in Applications and launch.  This should fix this issue, if it does not resolve by replacing. `rm -rf` your `$HOME/Library/Application Support/Code` directory and re-install. This resolved the issue for me.

**Comment by johnpapa** [comment]
I deleted the VS Code file from my Applications folder on OSX. Then re-downloaded. Fixed it too, as another option

**Comment by jrieken** [comment]
@joaomoreno Look like an installer issue and left-overs?

**Comment by joaomoreno** [comment]
No idea. Squirrel should do a nice clean update. Is there someone else that still has the broken copy so we run a diff over it?

**Comment by jrieken** [comment]
@spboyer Can you attach or PM the omnisharp log (Cmd+L, L)?

**Comment by spboyer** [comment]
@jrieken it has been resolved in the process by replacing the .app, here is an example however if @code trying to use *mono.1.0.0-beta3* in the log which might be another issue?

```
[INFO] Starting OmniSharp at '/Users/shayneboyer/spboyer/cleanshave-rc'...
[INFO] Started OmniSharp from '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/csharp-o/bin/omnisharp' with process id 12362...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/Users/shayneboyer/spboyer/cleanshave-rc' on host 12351.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/Users/shayneboyer/.k/runtimes/kre-mono.1.0.0-beta3'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/Users/shayneboyer/spboyer/cleanshave-rc' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/Users/shayneboyer/spboyer/cleanshave-rc/project.json'.
Listening on port 55967
[INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running DesignTimeHost on port 55967, with PID 12369
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected
Client accepted 127.0.0.1:55967
Client accepted 127.0.0.1:55967
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/Users/shayneboyer/spboyer/cleanshave-rc'
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/Users/shayneboyer/spboyer/cleanshave-rc'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 433ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 435ms
```

**Comment by jrieken** [comment]
The mono is thing is ~~by design~~ a hack of OmniSharp (since coreclr cannot talk via sockets). Not much to do for us then waiting.

**Comment by spboyer** [comment]
Thanks @jrieken
