### ISSUE TITLE
When multiple files are selected, it will prompt that the length of the command card is exceeded 

### ISSUE THREAD

**Issue by yrtw** [microsoft/vscode#116018]
Issue Type: <b>Feature Request</b>

When withdrawing multiple modified files, if more files are selected, it will prompt that the length of the command card is exceeded, it will be stuck for a period of time, and then the operation is successful. 

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Your version is nearly two years out of date. Please update to the current release, 1.53, then test again.
