### ISSUE TITLE
Allow for control of SCM quick options

### ISSUE THREAD

**Issue by kylemh** [microsoft/vscode#116055]
In the Source Control panel, above the (commit) message text input, there exist quick actions. I use this feature with every branch I make at work and on personal projects to keyboard navigate my way through the commit/push process.

![](https://user-images.githubusercontent.com/9523719/107155052-14e51600-692b-11eb-95e3-f2a9563364dd.png)

In the last year, there were 2 issues in this area that causes issues.

- https://github.com/microsoft/vscode/issues/103923
- https://github.com/microsoft/vscode/issues/100273

Additionally, extensions are changing the options out from under me as well: https://github.com/microsoft/vscode-pull-request-github/pull/2347

I would love it if there were a way to define this quick actions menu for myself, and never have it be altered.

**Comment by eamodio** [comment]
I'm going to close this issue, as we aren't going to make specific changes here for SCM, but we ultimately want user-controllablle menus/toolbars

**Comment by kylemh** [comment]
@eamodio is there an issue I can follow to track progress on that goal?

**Comment by eamodio** [comment]
This one is probably the closest we have open right now: https://github.com/microsoft/vscode/issues/46403

**Comment by kylemh** [comment]
This seems to reference a different area in the UI, but I'll just take your word for it.
