### ISSUE TITLE
Scrolling shouldn't close error popups

### ISSUE THREAD

**Issue by AcademyOfF** [microsoft/vscode#116061]
For context, here is the type of error pop-up I'm talking about: 
![image](https://user-images.githubusercontent.com/51732963/107161033-bdf13800-694e-11eb-90cb-95a2179e6175.png)

If you scroll past the bottom of this pop-up, it closes and scrolls whatever window is behind it. This requires you to be extremely precise with your mouse if you are trying to read the bottom of any error message that doesn't fit in the pop-up.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo if you haven't already updated to 1.53 please do that and then retest.

**Comment by AcademyOfF** [comment]
I apologize, normally I wouldn't have forgotten to do that. Now that I have, I can see this doesn't occur anymore. That said, if the error popup isn't large enough to scroll, this issue still exists. I still think that's worth addressing, because sometimes I scroll just to see *if* there is more content; after all, the scrollbar doesn't show unless you scroll, and sometimes the content is the perfect size where you can't tell if you're reading the whole thing.
