### ISSUE TITLE
"Open Recent" is Confusingly Similar to "Recently Opened"

### ISSUE THREAD

**Issue by dylan-k** [microsoft/vscode#116044]
I'd like to be able to use the File > Open Recent command to open a file that I literally just opened and closed. Seems simple enough, but it doesn't do that. No, I had to do some deep googling through forums and here on some (closed?) issues to learn that there's an, unbeknownst-without-searching, different command, control+p, to do what you'd expect.  And so, in short, my feature request is for an "open recent files" option, easily found in the file menu, that does what it says, regardless of how the file was opened.

**Comment by bpasero** [comment]
We intentionally leave out entries that are opened from e.g. the file explorer from the "File > Recently Opened" menu to keep the list short. The rule is that only entries opened from "File > Open" will end up there, which in most cases are files that are outside of the workspace to make them easier to find later.

The quick pick inside VSCode is the main source to navigate between recently opened files that have been opened from within the workspace.

**Comment by dylan-k** [comment]
What's that you say, intentionally confusing? j/k
But for my part, I'd prefer an accurate list to a short one, with perhaps the option to set a limit.
