### ISSUE TITLE
Cmd+V does not paste in Integrated Terminal

### ISSUE THREAD

**Issue by davidbailey00** [microsoft/vscode#116098]
- VSCode Version: 1.54.0-insider afd102cbd2e17305a510701d7fd963ec2528e4ea
- OS Version: macOS 11.3 Beta (20E5172i) Darwin arm64 20.4.0

Steps to Reproduce:

1. Copy some text
2. Open Integrated Terminal
3. Press Cmd+V

Expected result: the text is pasted
Actual result: the text is not pasted, however I can paste using right-click -> Paste

Does this issue occur when all extensions are disabled?: Yes

Additional search terms: command, ⌘

**Comment by davidbailey00** [comment]
Similar issue to #112557, however this issue occurs for me consistently, without starting a debug session, and was not occurring until the latest Insiders release today.

**Comment by davidbailey00** [comment]
I've bisected the issue to 98f697844a39427e7c555271888cbd64f26adb3d

**Comment by Tyriar** [comment]
Thanks for the bisect, made it very clear what the issue was 🙂
