### ISSUE TITLE
Enable Go to Implementation in VSCode for Typescript

### ISSUE THREAD

**Issue by parksj10** [microsoft/vscode#116072]
Highly upvoted issue here: [https://github.com/microsoft/TypeScript/issues/6209](https://github.com/microsoft/TypeScript/issues/6209)

Note sure if it can be solved on the vscode side of things, but this is making a lot of devs (myself included) switch to Webstorm (love everything about VSCode, this just makes it a nightmare trying to understand libraries)

**Comment by parksj10** [comment]
@mjbvz can you link to the duplicate? I couldn't seem to find it in the issuebase

**Comment by mjbvz** [comment]
It's a duplicate of issue you linked to. We can't fix this on the VS Code side.

Please don't open duplicate issues if you already know they are being tracked somewhere

**Comment by parksj10** [comment]
@mjbvz I didn't know if it could be fixed on the VSCode side of things, hence opening the issue. However, the incapability is duly noted. This begs the question... what kind of magic is JetBrains doing to make this work without Typescript core modification?
