### ISSUE TITLE
Files with double-byte not included in file search

### ISSUE THREAD

**Issue by thdoan** [microsoft/vscode#116002]
Issue Type: <b>Bug</b>

1. Unzip attached sample files
[_locales.zip](https://github.com/microsoft/vscode/files/5937730/_locales.zip)

2. Select Find in Files and search for "generalOptions"

Issue: only files in `en` and `pt_PT` are searched -- file in `zh_CN` is not searched, which I believe because VS Code treats it as a binary file.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (5.46GB free)|
|Process Argv|--crash-reporter-id 87146db6-51dd-47a9-a9fe-074405a51226|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
prophet|Sqr|1.3.33
sort-lines|Tyr|1.9.0
remove-empty-lines|use|0.0.6

</details>

**Comment by JacksonKearl** [comment]
This works fine for me. Have you possibly set `files.encoding` away from UTF-8?

![image](https://user-images.githubusercontent.com/8586769/107273909-92308980-6a04-11eb-9c47-fce402d67de9.png)

**Comment by thdoan** [comment]
@JacksonKearl strange... I made a recording:

https://www.loom.com/share/9a15c74bc5914ee6a3520ed4ee8d58c6

File encoding is UTF-8.

**Comment by JacksonKearl** [comment]
Testing on windows I see the correct behaviour as well:
![image](https://user-images.githubusercontent.com/8586769/109793984-35229080-7bca-11eb-8112-6c28fb18d562.png)

Could you try working through the steps listed here, including attaching the search logs so I can better diagnose this issue? https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by thdoan** [comment]
@JacksonKearl thank you for the link to the common search issues -- after reading this I was able to pinpoint the root cause: it was something in my search file exclusions.
