### ISSUE TITLE
File search popup disappears when tabbing away from code

### ISSUE THREAD

**Issue by nwgh** [Microsoft/vscode#11602]
- VSCode Version: 1.5.0-insider (538cd9ded5a471fbb20920f01eff9c8df4b83ee9)
- OS Version: OS X 10.11.6 (15G1004)

Steps to Reproduce:

1. Press Cmd-P
2. Start searching for a file you haven't yet searched for in a large project (the file doesn't even have to exist - I just did 'asdf' to verify)
3. Cmd-Tab away to another app
4. Cmd-Tab back to code
5. Your Cmd-P search has disappeared and (to all appearances) been canceled.

This is especially frustrating given it can sometimes take near a minute for results on large projects (I'm working on https://hg.mozilla.org/mozilla-central) and I would like to be able to tab away from code to finish reading the bug I'm working on while it searches the files. As it stands, I have to just wait for code to finish searching.

**Comment by bpasero** [comment]
With 1.5 there is a new setting: `"workbench.quickOpen.closeOnFocusLost": true`

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by nwgh** [comment]
Excellent, I missed that one when trolling for new prefs. Thanks!
