### ISSUE TITLE
`settingsSync.ignoredSettings` no longer accepts `window.zoomLevel`?

### ISSUE THREAD

**Issue by borekb** [microsoft/vscode#116046]
VS Code version: Code 1.53.0 (8490d3d, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

I've had this in my `settings.json` for a while:

```json5
{  
  "window.zoomLevel": 1.0341734124049706,
  "settingsSync.ignoredSettings": [
    "window.zoomLevel"
  ]
}
```

However, I noticed that it's no longer accepted:

![Screen Shot 2021-02-07 at 18 10 37-shadow](https://user-images.githubusercontent.com/101152/107153886-34526200-6970-11eb-80c6-eca3d651ed14.png)

The error message is:

> Value is not accepted. Valid values: "editor.tabSize", "editor.insertSpaces", [etc.]

I tried to search the issues, the [Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync) topic in the docs and the [Updates](https://code.visualstudio.com/updates) but couldn't find anything about this change. Is `window.zoomLevel` always excluded from Settings Sync now? Or what's the reason for the warning?

**Comment by sandy081** [comment]
`window.zoomLevel` setting is not synced by default - https://github.com/microsoft/vscode/issues/114013

You can remove that setting from ignored settings to sync.

I will add that in the release notes.

**Comment by noopurphalak** [comment]
@sandy081 Yes, it is synced by default. I set `window.zoomLevel: -0.5` in my work laptop and it gets synced to my home laptop and overrides the setting `window.zoomLevel: 0.5`

**Comment by sandy081** [comment]
It should not sync `window.zoomLevel` setting by default - please try with latest version of VS Code.

**Comment by noopurphalak** [comment]
@sandy081 I am on the latest VS Code version on both my laptops, still `window.zoomLevel` is synced between them.

![vscode_version](https://user-images.githubusercontent.com/8924488/107378661-36542680-6b12-11eb-8331-83b187f0f01c.png)

**Comment by sandy081** [comment]
- Update zoom level 
- Sync manually - `Settings Sync: Sync now`
- open settings sync data using command `Settings Sync: Show synced data`
- Check the diff of latest settings json entry and let me know what it shows

**Comment by noopurphalak** [comment]
![sync](https://user-images.githubusercontent.com/8924488/107381215-a4015200-6b14-11eb-8230-c3cb60f86f4f.png)

There you go...

**Comment by sandy081** [comment]
You can see that the change you made is not synced - but since it was already synced before it still exists in remote. To remove it completely please follow following steps:

- configure `window.zoomLevel` setting to sync as follows:
```
"settingsSync.ignoredSettings": [
		"-window.zoomLevel"
	],
```
- delete the window.zoomLevel setting locally
- Let it sync
- Remove `-window.zoomLevel`  from ignored settings

**Comment by noopurphalak** [comment]
@sandy081 After that, should I add `window.zoomLevel` again locally?

**Comment by sandy081** [comment]
yeah adding it back will not sync it up.

**Comment by noopurphalak** [comment]
@sandy081 But it got synced again.

![synced](https://user-images.githubusercontent.com/8924488/107383378-f04d9180-6b16-11eb-8b21-f820ddb42905.png)

**Comment by sandy081** [comment]
I do not think so, you can see on the left hand side the setting does not exist - diff shows the diff between remote and local and clearly the setting is excluded/

**Comment by noopurphalak** [comment]
@sandy081 Okay, got it. Thanks a lot for your help.
