### ISSUE TITLE
settings sync disabled

### ISSUE THREAD

**Issue by bibek761** [microsoft/vscode#116074]
Issue Type: <b>Bug</b>

I get a dialogue saying saying sync is disabled bacuase of too many requests

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (10.68GB free)|
|Process Argv|--crash-reporter-id a5cfd3f6-6a3f-4659-bc56-fbf31dd8a119|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
vscode-intelephense-client|bme|1.6.3
htmltagwrap|bra|0.0.7
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
jquerysnippets|don|0.0.1
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
prettier-vscode|esb|5.9.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
code-runner|for|0.11.2
vscode-mysql|for|0.4.0
go|gol|0.22.0
beautify|Hoo|1.5.0
vscode-dashboard|kru|2.3.1
git-graph|mhu|1.28.0
HTMLHint|mka|0.10.0
vscode-autoprefixer|mrm|3.0.1
vscode-edge-devtools|ms-|1.1.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.5.0
vscode-css-navigation|puc|1.10.3
vscode-yaml|red|0.14.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.1
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
phpcs|she|1.0.8
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
bootstrap4-vscode|the|6.1.0
pdf|tom|1.1.0
vscode-icons|vsc|11.1.0
ReactSnippets|xab|2.4.0
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.9.13

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
You can view settings sync log using `F1 > Open View > Log (Settings Sync),,, `

Look for clues there.

**Comment by gjsjohnmurray** [comment]
Also, the `Settings Sync: Show Synced Data` command from the Command Palette may help you discover what was spamming the settings sync server.
