### ISSUE TITLE
Typescript 2.0.2: Global Types Not Found if tsconfig.json Contains an "include" Field

### ISSUE THREAD

**Issue by xwvvvvwx** [Microsoft/vscode#11604]
- VSCode Version: 1.4.0
- OS Version: OSX 10.11.6

I am using typescript 2.0.2 and installing types with npm.

I have the following `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "baseUrl": "src",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "sourceMap": true,
    "outDir": "ts-build",
    "jsx": "react",
    "types": ["mocha", "node"]
  },
  "include": [
    "src"
  ],
  "files": [
    "type-declarations/globals.d.ts"
  ]
}
```

If the `include` field is present, then my global types (`mocha` / `node` / types defined in `globals.d.ts`) are not found by vscode (see pic below):
![screen shot 2016-09-07 at 00 02 24](https://cloud.githubusercontent.com/assets/6689924/18292604/61eaef38-748e-11e6-8d67-fa1dcb3526ae.png)

If I remove the `include` field then vscode finds the global types, but my webpack rebuilds often fail due to out of memory errors.

Running `tsc` or webpack with `ts-loader` does not produce any errors with the above config.

Running `tsc` with `"includeFiles": true` in the `tsconfig.json` produces the following output:

```
/Users/david/Code/typescript-boilerplate/node_modules/typescript/lib/lib.es6.d.ts
/Users/david/Code/typescript-boilerplate/type-declarations/globals.d.ts
/Users/david/Code/typescript-boilerplate/node_modules/@types/mocha/index.d.ts
/Users/david/Code/typescript-boilerplate/node_modules/@types/node/index.d.ts
```

You can see the full project here: https://github.com/xwvvvvwx/typescript-react-electron-boilerplate

Am I missing something?

**Comment by waderyan** [comment]
Thank you for opening this issue. This will fall onto TypeScript language service. Moving over to them.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10795
