### ISSUE TITLE
Jitter when selecting or scrolling in editor even without `zoomLevel` is set.

### ISSUE THREAD

**Issue by gencer** [microsoft/vscode#116026]
- VSCode Version: 1.53.0
- OS Version: Windows 10 2009 x64

Steps to Reproduce:

1. Disable `zoomLevel`. 
2. Set:
  a. `fontSize` to `18`
  b: `lineHeight` to `35` or `34` or `30`
  c: `fontFamily` to `Hack` or `Consolas`.
3. Select some lines or click few different lines. You'll see the jitter.

Does this issue occur when all extensions are disabled?: Yes

I am using Windows 10 with 4K Display which is set to 125% DPI. I also use `--disable-renderer-accessibility`.

## Solution

Use 100% or 150% DPI instead of 125%.

System Info:

CPUs | AMD Ryzen 3 1300X Quad-Core Processor (4 x 3600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.94GB (24.70GB free)
Process Argv | --disable-renderer-accessibility
Screen Reader | no
VM | 0%

**Comment by gencer** [comment]
Hm.. Interesting that If I set my Display to `150%` DPI and restart VSCode (I did not restarted VSCode in above video of 150% DPI) all jitter is gone even with `lineHeight` but now including my Windows, everything is big. I am using 4K Display with 49" Display.

**Comment by gencer** [comment]
If I get this correct, Based on the feedback from @alexdima on #28439, even `zoomLevel` is set to `0`, It will jitter because of Windows is set to `125%` DPI.

Let me know If my assumption is wrong on Windows DPI + VSCode.

**Comment by gencer** [comment]
From my point of view, By changing my Windows DPI from 125% to 150%, Not only VSCode works great but also some other applications which I see some issues fixed too. Therefore, I am going to use it with 150% DPI.

Closing this now.

**Comment by gencer** [comment]
@alexdima Can we reopen this or should I open a new issue? Reason is:

I get jitter at 150% DPI when search box (CTRL+F) is opened in editor. See below video:

https://user-images.githubusercontent.com/1711576/107440445-af6c7180-6b44-11eb-984d-5c1056421c6f.mp4

If you notice when search box is closed white (empty) line between the lines are gone. When the box open they appears and jitter begins.

**Comment by gencer** [comment]
Hi @alexdima Is there anything that i can do to help on this case? I hope you didn't missed this issue.

**Comment by alexdima** [comment]
Here's a summary of my understanding in this area:

* when using a `window.zoomLevel` value which is non zero, or when using the scaling feature in Windows, Chromium internally creates a zoom factor, perhaps something like 1.25.
* we paint all our `<div>`s at integer coordinates on our side.
* but Chromium begins multiplying all our integers with the zoom factor.
* this causes the nice integers to become floats and at one point there will be rounding errors or situations where a certain integer, based on how it aligns will round up or down and introduce a gap or jitter, etc.

If you are sensitive about pixel perfect rendering, I recommend:
* close all instances of vscode
* execute ` code --force-device-scale-factor=1` (this will instruct Chromium to ignore the multiplier scale coming in from Windows). This can be persisted using `F1 > Preferences: Configure Runtime Arguments` or by modifying the shortcut.
* configure `window.zoomLevel: 2` or 3 and then reduce the fontSize and lineHeight. It could be that one of these zoom levels results in a better zoom factor with smaller (or more rare) rounding errors, given how floats are represented.

But that being said, I don't think there is any possible code change that we could do on our side.
