### ISSUE TITLE
search files by name imperfect tokenization

### ISSUE THREAD

**Issue by image72** [microsoft/vscode#116021]
- VSCode Version:1.53.0
- OS Version:Darwin x64 17.7.0

Version: 1.53.0
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T16:01:04.046Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 17.7.0
Steps to Reproduce:

1. open search files by name palette
2. example:

 search project files by name, type **interview man** means I want search **interview man** start serial files, but search result list imperfect
![image](https://user-images.githubusercontent.com/243154/107142796-4500d900-696c-11eb-8946-3b198608564c.png)

search file name include **route**, result list
![image](https://user-images.githubusercontent.com/243154/107142848-8abda180-696c-11eb-8f6f-1e17f8be7d90.png)

Does this issue occur when all extensions are disabled?: Yes

sorry, I'm not good at english.

**Comment by image72** [comment]
keyword should have minimal match weight?  _//just my ideas only_

**range 1** should view in result list index 1, 
not match should dismiss

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/99171#issuecomment-637973584

Try `interviewman` instead of `interview man`

**Comment by gjsjohnmurray** [comment]
@bpasero is there a way that a contiguous match in the path can be made to outrank a non-contiguous match in the name (see second screenshot)?

**Comment by image72** [comment]
> See [#99171 (comment)](https://github.com/microsoft/vscode/issues/99171#issuecomment-637973584)
> 
> Try `interviewman` instead of `interview man`

But, **interview man** means I want fuzzy search with two keyword **interview** & **man** maybe fireman,woman,manager or another includes
Start match, End match, middle match

**Comment by image72** [comment]
![image](https://user-images.githubusercontent.com/243154/107172005-2566c080-69ff-11eb-95d5-529c8030d44f.png)

**Comment by image72** [comment]
![image](https://user-images.githubusercontent.com/243154/107172221-c0f83100-69ff-11eb-8c1f-5c6da24b0696.png)

**Comment by gjsjohnmurray** [comment]
The implementation is at https://github.com/microsoft/vscode/blob/master/src/vs/base/common/fuzzyScorer.ts

By entering `interview man` you are requiring both `interview` AND `man` to score > 0. In your latest screenshot see how the matches that you boxed with yellow qualify by containing the letters m, a and n somewhere in one of the components (path, name), even though those letters appear in a different sequence.

**Comment by image72** [comment]
thanks for your explain.

**Comment by bpasero** [comment]
Related https://github.com/microsoft/vscode/issues/25925

@gjsjohnmurray 

>  is there a way that a contiguous match in the path can be made to outrank a non-contiguous match in the name (see second screenshot)?

Currently not.
