### ISSUE TITLE
Menu is not displayed

### ISSUE THREAD

**Issue by JMasak** [microsoft/vscode#116085]
Issue Type: <b>Bug</b>

- restart VS Code after update
- release notes (1.53.0) are displayed in new editor tab
- press alt to show hidden menu bar (File, Edit, Selection...)
-> menu bar stays hidden
- change to another tab (in my case a .cpp file)
- press alt
- menu bar appears

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.86GB free)|
|Process Argv|--crash-reporter-id 9d36b549-4c2d-49f9-a73b-60f1aa70ebe0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
doxdocgen|csc|1.1.0
arm|dan|1.5.0
gitlens|eam|11.2.1
cortex-debug|mar|0.3.11
rust-analyzer|mat|0.2.473
cpptools|ms-|1.2.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/68335
