### ISSUE TITLE
VSCodeUserSetup-x64-1.53.0.exe or 1.54.0-insider.exe Install but fail to launch with a completely black window

### ISSUE THREAD

**Issue by jmaincpa** [microsoft/vscode#116042]
- VSCode Version:  1.53.0 or 1.54.0
- OS Version:  Windows 10 Enterprise 1909 SAR

Steps to Reproduce:

1.  Install any x64 version of Windows VSCode version 1.53.0 or 1.54.0, or upgrade to 1.53.0 from any previous version.
2.  Try to launch the editor, get a window that's completely black.

Windows 10, previous versions all installed and worked perfectly.

VSCodeUserSetup-x64-1.53.0.exe or 1.54.0-insider.exe Install but fail to launch, showing only a completely black window. Several Visual Studio Code processes (5-6) run in the background but never complete.

Upgrades, from previously working earlier versions, complete to 1.53.0, but also fail to launch with a completely black window.

Downloaded and installed 1.52.1, works perfectly.  Changed Update Mode to None, and able to get back to work.

Location of install does not seem to impact this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Most likely same issue as https://github.com/microsoft/vscode/issues/114459

Can you follow https://github.com/microsoft/vscode/issues/114459#issuecomment-775369473 and provide the result.

**Comment by deepak1556** [comment]
Also can you try https://github.com/microsoft/vscode/issues/114459#issuecomment-775374293

**Comment by jmaincpa** [comment]
Appears to be the same issue.   Seems odd that any sort of config option would have that impact between 1.52 and 1.53

**Comment by deepak1556** [comment]
Thanks for confirming, merging as duplicate.

> Seems odd that any sort of config option would have that impact between 1.52 and 1.53

https://github.com/microsoft/vscode/issues/114459#issuecomment-775629095
