### ISSUE TITLE
vscode main window display error on Debian 10

### ISSUE THREAD

**Issue by Samir2912** [microsoft/vscode#116006]
- VSCode Version: 1.53.0
- OS Version: Debian 10

Steps to Reproduce:

1. upgrade Debian 10 that includes the upgrade of vscode: >> sudo apt upgrade
2. launch vscode: >> code
3. No menu, texts, info are displayed. Only a empty window.  
4. I've deleted the version 1.53.0 and installed the previous version 1.52.1: sudo apt install code_1.52.1-1608136922_amd64.deb and it worked fine.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose` , also can you try starting with `--disable-gpu`

**Comment by Samir2912** [comment]
- it worked fine with --disable-gpu
- you can find logs of the verbose mode in the attached file:
[code_verbose.log](https://github.com/microsoft/vscode/files/5974471/code_verbose.log)
- in this attached file, you can find the screenshot of a non woking vscode:
<img width="915" alt="Capture d’écran 2021-02-12 à 23 01 16" src="https://user-images.githubusercontent.com/3882879/107827337-db773500-6d86-11eb-9dfe-a3cceb08ceeb.png">

**Comment by deepak1556** [comment]
Thanks for testing, are you running on any VM ?

You can disable gpu via setting for now https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration until this is fixed in next electron update.

**Comment by Samir2912** [comment]
Thanks for you quick reply.

Yes! I'm running a VM using Parallels Desktop

**Comment by deepak1556** [comment]
It would be https://github.com/microsoft/vscode/issues/111290 , merging to it then.
