### ISSUE TITLE
Open New Terminal Shortcut not working

### ISSUE THREAD

**Issue by Satwik29** [microsoft/vscode#116096]
I am using VSCode Insiders....this problem is not present in the stable version

- VSCode Version: 1.54
- OS Version: Windows 7

Steps to Reproduce:
1. Open VSCode - Insiders
2. Enter the shortcut for opening a new terminal

Does this issue occur when all extensions are disabled?: Yes

**Comment by tomaxsas** [comment]
Fix is wrong, terminal still cannot be opened from editor. condition  KEYBINDING_CONTEXT_TERMINAL_FOCUS should be removed
