### ISSUE TITLE
Deploy Extension Issue after update VSCODE v1.53 on MAC OS

### ISSUE THREAD

**Issue by narongnong** [microsoft/vscode#116070]
<img width="1904" alt="issueDeploy" src="https://user-images.githubusercontent.com/78712784/107170626-72dd3080-69f3-11eb-95c8-b40123ce76e8.png">
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate which extension is causing the problem. Then report the problem to the extension author and update / close this issue.
