### ISSUE TITLE
Show folder name prefix in tab if multiple files are having the same name

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#11606]
- VSCode Version: 1.4
- OS Version: OS X

![screen shot 2016-09-06 at 3 13 54 pm](https://cloud.githubusercontent.com/assets/543633/18292905/aff285be-7444-11e6-943e-22f585d1c512.png)

It's a common pattern in many projects to have an `index` file in each folder. When I open multiple index files I can't tell from tab header which index file is which. 

To fix this problem I'm proposing to have a smarter tab name that detects if multiple tabs are having exact same file name and prepends the folder those files are at in the tab header. It should do this when multiple editor instances of the same file are open.

**Comment by ramya-rao-a** [comment]
Wouldn't hovering on the tab give you the full path?

**Comment by mohsen1** [comment]
yes, but that takes a few seconds.

Sublime has an option to show the full path in the tab header but I think that's too much and messy. What I proposed should be simpler and cleaner

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8499
