### ISSUE TITLE
Open Recent is Confusingly Similar to Recently Opened

### ISSUE THREAD

**Issue by samjones3** [microsoft/vscode#116066]
- VSCode Version: 1.53.0
- OS Version: Win10

This is similar to #[57642](https://github.com/microsoft/vscode/issues/57642)

Also discussed on this thread: https://stackoverflow.com/q/59897579/147637

While I use VS Code a lot, I am confused by and unable to use the whole Recent mechanism. Why?
- The intuitive spot lacks what I am looking for 
- The spot with what I am looking for is via a special keystroke that is not used in other apps

Steps to Reproduce:

1. Open VS Code
2. In VS Code, open file: c:\temp\1.txt
3. Close c:\temp\1.txt
4. Exit VS Code
5. Open VS Code
6. Go to Open Recent
7. Files from months ago are there, but 1.txt is NOT THERE

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Confusingly similar to #116044
