### ISSUE TITLE
Annoying Save prompt in the new version

### ISSUE THREAD

**Issue by BBengtsson** [microsoft/vscode#116099]
Your new feature "Prompt to save untitled files before run/debug" is really annoying when I just want a quick scratch powershell script to execute a few times and when there is no need to keep the script.

please revert or provide a configuration to change this behaviour.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/114890

**Comment by BBengtsson** [comment]
Would be nice to know what case this is a duplicate off...

**Comment by isidorn** [comment]
#114890
