### ISSUE TITLE
workbench.action.focusActiveEditorGroup keyboard shortcut when explorerFocus no longer works

### ISSUE THREAD

**Issue by AlphaHydrae** [microsoft/vscode#116090]
- VSCode Version: 1.53.0
- Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
- Date: 2021-02-03T16:01:04.046Z
- Electron: 11.2.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Disable the new `editor.action.rename` F2 shortcut:

   ```json
   {
     "key": "f2",
     "command": "-editor.action.rename",
     "when": "editorHasRenameProvider && editorTextFocus && !editorReadonly"
   }
   ```

2. Add the following shortcuts from my custom configuration:

   ```json
   {
     "key": "f2",
     "command": "workbench.action.focusActiveEditorGroup",
     "when": "explorerFocus"
   },
   {
     "key": "f2",
     "command": "workbench.view.explorer",
     "when": "editorFocus"
   }
   ```

3. With these shortcuts, the F2 key should allow quickly switching focus between the explorer and the editor, which used to work fine before the January 2021 update. Now, switching from the editor to the explorer works, but then hitting F2 does not do anything and does not switch back to the active editor group as it should considering the configured shortcuts.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please review the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues
