### ISSUE TITLE
Python green run button

### ISSUE THREAD

**Issue by yoberner** [microsoft/vscode#116014]
- VSCode Version: 1.53.0
- OS Version: macOSX Catalina 10.15.7

When viewing a Python file in VSCode, I do not see the green run button in the upper right hand like the tutorial shows here: https://code.visualstudio.com/docs/python/python-tutorial#_configure-and-run-the-debugger. I have the extensions enabled for python, but still don't see it.

UPDATE: I think this might be because I have the code runner extension enabled, however I would also like to the the green run with terminal button. Is there a way to enable the green button so I can see both?

**Comment by isidorn** [comment]
/extPuthon

We are also looking into this from the VS Code side, and there are other issues to cover this
