### ISSUE TITLE
<<RENDER ERROR>> in all files

### ISSUE THREAD

**Issue by viclafouch** [microsoft/vscode#116094]
Hello ! 

Since the last version, I have this error.. I don't know how can I reproduce it, bit it happens in a lot of files and all of my projets... 

![image](https://user-images.githubusercontent.com/23353836/107209399-0a964b00-6a03-11eb-9a08-8f447ba0f941.png)

![image](https://user-images.githubusercontent.com/23353836/107488158-465a1d80-6b87-11eb-8bcd-756801864e82.png)

```
breadcrumbsWidget.ts:319 TypeError: Cannot read property 'symbol' of undefined
    at ks.renderElement (documentSymbolsTree.ts:139)
    at x.render (breadcrumbsControl.ts:87)
    at C._renderItem (breadcrumbsWidget.ts:316)
    at C._render (breadcrumbsWidget.ts:304)
    at C.setItems (breadcrumbsWidget.ts:273)
    at z (breadcrumbsControl.ts:290)
    at u.fire (event.ts:623)
    at breadcrumbsModel.ts:164
_renderItem @ breadcrumbsWidget.ts:319
```

- VSCode Version: 1.53.0
- OS Version: MAc Big Sur 1.11

Steps to Reproduce: 

Does this issue occur when all extensions are disabled?: yes

**Comment by jrieken** [comment]
Please open dev tool (f1 > toggle developer tools) and then check the console for error messages

**Comment by viclafouch** [comment]
![image](https://user-images.githubusercontent.com/23353836/107430875-07e04680-6b26-11eb-9fe8-a8cbce11fee0.png)

Here the error messages

**Comment by jrieken** [comment]
Can you attach the file in source so that I can simply copy&paste it

**Comment by viclafouch** [comment]
Not sure of what you ask, but I attached the image to the source issue. Good ?

**Comment by jrieken** [comment]
> Good ?

No. I cannot copy paste and image into a text editor.

**Comment by viclafouch** [comment]
Here the tsconfig and the file of the screenshot. 
My TS version is 4.1.4
I use the Tyoescript-React language mode.

[Archive.zip](https://github.com/microsoft/vscode/files/5957310/Archive.zip)

Do not hesitate if you need more info !

**Comment by jrieken** [comment]
🤷 hm... there is still some unknown piece of information missing

<img width="1084" alt="Screenshot 2021-02-10 at 11 18 54" src="https://user-images.githubusercontent.com/1794099/107496574-c4bbbd00-6b91-11eb-8a63-a254b74d2b42.png">

**Comment by viclafouch** [comment]
Ok I know how to reproduce the bug:

Enable these 2 VSCode settings : 

`  
"breadcrumbs.enabled": true,
"breadcrumbs.symbolPath": "last"
`

![image](https://user-images.githubusercontent.com/23353836/107498383-0188b380-6b94-11eb-9ea6-8f89aa338ccc.png)

![image](https://user-images.githubusercontent.com/23353836/107498551-3ac12380-6b94-11eb-8d7f-a780dab4cef6.png)

**Comment by jrieken** [comment]
Thanks! Now I can reproduce, actually also with other languages

**Comment by jrieken** [comment]
Simple repro steps

* default setting, e.g breadcrumbs on
* also `breadcrumbs.symbolPath: last`
* have the ts/js-snippet below
* put your cursor inside the function -> all good
* put your cursor outside the function, e.g position 1,1 -> breadcrumbs shows error

```ts
  // cursor here -> bad
function foo() {
  // cursor here -> good
}
```

**Comment by jrieken** [comment]
Adding this to the 1.53.2 recovery release
