### ISSUE TITLE
C++ intelliCode not working

### ISSUE THREAD

**Issue by JohnGu9** [microsoft/vscode#116010]
Issue Type: <b>Bug</b>

1.53 make C++ intelliCode doesn't work at all. Can't jump file. Can't rename. Can't search reference. 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 7, 7|
|Memory (System)|16.00GB (0.88GB free)|
|Process Argv|--crash-reporter-id 1bb62fb4-2269-44eb-a66d-bc6711028445|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|12.1.4
ng-template|Ang|11.1.3
doxdocgen|csc|1.1.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
xml|Dot|2.5.1
vscode-pull-request-github|Git|0.23.0
better-cpp-syntax|jef|1.15.5
Kotlin|mat|1.7.1
asm-code-lens|maz|1.7.1
git-graph|mhu|1.28.0
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.3.0
angular-console|nrw|16.0.2
java|red|0.74.0
vscode-yaml|red|0.14.0
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
vscode-counter|uct|2.2.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.17.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-spring-initializr|vsc|0.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you try to use the Extension Bisect command to investigate whether the problem is being caused by one of your extensions. But first identify which extension should be providing the missing Intellicode, then use the tip from https://github.com/microsoft/vscode/issues/113568#issuecomment-759334161 to exclude it from the Bisect.

**Comment by JohnGu9** [comment]
> I suggest you try to use the Extension Bisect command to investigate whether the problem is being caused by one of your extensions. But first identify which extension should be providing the missing Intellicode, then use the tip from [#113568 (comment)](https://github.com/microsoft/vscode/issues/113568#issuecomment-759334161) to exclude it from the Bisect.

I done. But not working that even only enable C/C++ extension (from ms). Including only enable C/C++ extension Pack. Just doesn't work. More annoying that if I keep open C/C++ workspace, the copy and paste operation will be blocked (ye, I need to reload vscode every few hours). It seem to be bug (I don't change any settings after update. I remember 1.53 version update request manually quit before update).

**Comment by JohnGu9** [comment]
I finally reinstall vscode and fix the problem😃

**Comment by JohnGu9** [comment]
After reinstall and one day using, the problem show again.
