### ISSUE TITLE
If Conda is not on path, VSCode can't activate enviroments

### ISSUE THREAD

**Issue by zurgeg** [microsoft/vscode#116054]
Issue Type: <b>Bug</b>

In my case, Conda is not on path and when I run `conda activate myenv` VSCode kills it and switches back to Powershell.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.07GB free)|
|Process Argv|--crash-reporter-id 6c5f0ebb-c40d-40c4-aed2-ee694cde8268|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
haxe-hl|Hax|1.1.1
discord-vscode|icr|4.1.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
hexeditor|ms-|1.4.0
debugger-for-chrome|msj|4.12.12
vshaxe|nad|2.21.4
haxe-debug|vsh|1.2.3
haxe-extension-pack|vsh|1.3.0
hxcpp-debugger|vsh|1.2.4
codedox|wig|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
pythonvsdeb440:30248342
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenu:30224647
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by IllusionMH** [comment]
/question

This is documented behavior for Powershell and conda combination.

See documentation https://code.visualstudio.com/docs/python/environments#_environments-and-terminal-windows and issue in Python extension repo for more details and recommendated workflow https://github.com/microsoft/vscode-python/issues/11638
