### ISSUE TITLE
Toggling editor.detectIndentation from within the settings menu doesn't work

### ISSUE THREAD

**Issue by mickael-h** [microsoft/vscode#116040]
Issue Type: <b>Bug</b>

Checking this box from the settings menu doesn't seem to do anything.
The setting works correctly when entered manually in settings.json, though.
(Note: this bug also occurred before the last update)

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (5.75GB free)|
|Process Argv|--crash-reporter-id 45d2796d-4663-4105-9f47-9fd92c48d0da|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2894)|
|Memory (System)|12.03GB (10.26GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.0
vscode-firefox-debug|fir|2.9.1
remote-containers|ms-|0.158.0
remote-wsl|ms-|0.53.2
awesome-flutter-snippets|Nas|2.0.4
svg-preview|Sim|2.8.3
path-intellisense|chr|2.3.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
gitlens|eam|11.2.1
vscode-jest-runner|fir|0.4.31
godot-tools|gee|1.1.2
pubspec-assist|jer|2.2.1
flutter-intl|loc|1.13.0
dart-import|lua|0.3.1
flutter-tree|mar|1.0.0
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
vscode-react-native|msj|1.3.0
vscode-jscpd|pau|0.3.4
flutter-dart-utils|Rod|0.0.67
sonarlint-vscode|Son|1.20.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by hediet** [comment]
I cannot reproduce this.

Maybe you open settings.json from your workspace, but use the user-global settings editor?
If `editor.detectIndentation` is configured in both places, the workspace entry has precedence.

Please try to reproduce in an empty folder.
