### ISSUE TITLE
Fresh install won't open any windows or allow me to open any windows

### ISSUE THREAD

**Issue by tommyp** [microsoft/vscode#116049]
- VSCode Version: 1.53.0
- OS Version: macOS Big Sur 11.2

Steps to Reproduce:

1. Install from visualstudio.com
2. Open from command line or icon
3. App appears open, but with no windows and no windows can be opened

Does this issue occur when all extensions are disabled?: Yes

Opening with `--verbose` only gives me:
```
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
```

Attempted launches creates multiple instances of the App but they all act the same - no windows and I can't create windows. It was initially working, but trying to open new windows gave me errors saying something along the lines of `cannot create multiple instances`. I tried to update macOS and clean install Code and now I have this new problem.

I'd appreciate all the help I can get. This is happening on a new refurbished 2020 Intel Mac. I'm setting it up for a new job and it would be good to be able to code. 🙈

**Comment by JiamingJiao** [comment]
same on Ubuntu 16.04

**Comment by tommyp** [comment]
I tried to figure this out a bit more and the extremely weird thing is that the options under `help` in the menu lead to Electron. The `Documentation` open links to: https://github.com/electron/electron/tree/v11.2.1/docs#readme

**Comment by GrooveGod** [comment]
Same for me.  I initially performed the _Upgrade_ and just a window with no frames, no menus, and no toolbars appeared.  Also tested a full, clean install with _no_ extensions; same results; a window with no frames, no menus, and no toolbars.

- VSCode Version: 1.53.0
- OS Version: MS Windows v1909 (build 18363.1316)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tommyp** [comment]
@bpasero The nightly insider build launches fine.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by tommyp** [comment]
@bpasero That command worked.

**Comment by bpasero** [comment]
How about only running with `--disable-extensions`?

**Comment by tommyp** [comment]
That doesn't work. It exhibits the same behaviour as before.

**Comment by bpasero** [comment]
@tommyp then I think it must be something with your settings maybe? Can you try to selectively copy them over to the other instance that runs from a fresh user data directory to see which one could be triggering this?

**Comment by tommyp** [comment]
Deleting `Code` in `~/Library/` seemed to fix it. I tried to look for my settings in there and found the symlink, but it couldn't find the original file.

**Comment by bpasero** [comment]
Any chance you can recover that deleted folder for test purposes?

**Comment by tommyp** [comment]
Yeah sure. I can zip it an email it to you?

**Comment by bpasero** [comment]
@tommyp if you don't mind me having access to your data from the archive I am happy to see if I can reproduce the issue 👍 

My mail is accessible from: https://github.com/bpasero

**Comment by bpasero** [comment]
@tommyp thanks a lot I see the issue too.

@deepak1556 @rzhao271 please try to reproduce and let me know what you found.

**Comment by bpasero** [comment]
Oh wow, this seems to be caused by a symbolic link to `settings.json` that does not seem to be valid:

![image](https://user-images.githubusercontent.com/900690/107374526-fa0bd080-6ae7-11eb-81c3-fe2e9a92d7be.png)

Scary how we fail to startup so silently then.

@sandy081 adding you, I think we might need to be more robust on startup in such cases.

**Comment by sandy081** [comment]
I can repro it too, will investigate further to see what is causing this.

**Comment by bpasero** [comment]
I can reproduce, it looks like file streams are hanging now when an error is encountered. I would speculate this is a regression from  https://github.com/microsoft/vscode/commit/b47aa19443cae6a5b6537fd1652cc38639c5bbbf#diff-9eff79f6e04dd0d895fdaac933118e59be90aebf9145c269fa0f23f517deeeec or https://github.com/microsoft/vscode/commit/af59db28c8dc47f1a347e70408073f9b7b72c828#diff-9eff79f6e04dd0d895fdaac933118e59be90aebf9145c269fa0f23f517deeeec

**Comment by GrooveGod** [comment]
Hey gang, I just upgraded to 1.53.2.0 and am still seeing the plan black window.  Any suggestions?
![image](https://user-images.githubusercontent.com/25233137/107704006-6cf48300-6c71-11eb-9fd6-02229b04cf7a.png)

**Comment by deepak1556** [comment]
@GrooveGod please check https://github.com/microsoft/vscode/issues/114459 for workaround.

**Comment by GrooveGod** [comment]
@deepak1556 - Thanks for the workaround, `code --disable-gpu` works for now.
