### ISSUE TITLE
No Link hovers shown for output in the Debug Console

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#116037]
Pls see the screenshot below, 
![image](https://user-images.githubusercontent.com/172399/107149330-49bb9200-6958-11eb-9b1f-4ea673aa9afe.png)

**Comment by isidorn** [comment]
I have aligned the experience between the debug console and terminal. On hover over link we underline the link, and the hover text is now the same.

However the debug console uses the native hover and the terminal uses the custom hover. Thus in the debug console we do not have a link within the hover like the terminal does.

@Tyriar @alexr00 let me know if terminal does additional smartness regarding remote - that it shows a different link in the hover.

![Screenshot 2021-02-19 at 15 49 07](https://user-images.githubusercontent.com/1926584/108519585-110da800-72ca-11eb-8268-79e3fa25841b.png)

**Comment by alexr00** [comment]
@isidorn Terminal does have some smartness here:

https://github.com/microsoft/vscode/blob/507e210014ef69ed9faf07be3f1d0d725bf72ee8/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L238-L242

**Comment by isidorn** [comment]
@alexr00 thanks! I am now doing the same.
