### ISSUE TITLE
Unable to trigger DisconnectArguments.terminateDebuggee

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#116081]
- VSCode Version: 1.53.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Hello. I am currently maintaining the xdebug/vscode-php-debug extension and wanted to implement a feature. When the PHP process and the debugger are attached the user should have two options to stop debugging:
1. terminate the debuggee, so execution stops
2. disconnect the debugger from the debuggee and execution continues.

There are a couple of interesting options in the debugSession.ts:
supportsTerminateRequest, supportsTerminateThreadsRequest supportTerminateDebuggee.

I was currently concentrating on getting DisconnectArguments.terminateDebuggee of disconnectRequest, but was unable to find a scenario where this argument would be present at all.
I was also unable to find any relevant source reference to it in vscode.

Perhaps it has also to do with the `request` filed in `jaunch.json`. Currently we always use `launch`.

What do I need to do, so that the user will have both options available to them: Detach/Disconnect and Stop/Terminate.

Thank you!

Does this issue occur when all extensions are disabled?: Does not apply

**Comment by isidorn** [comment]
@weinand assigning first to you, feel free to assign back to me and I can try to answer

**Comment by weinand** [comment]
Yes, the behavior of DAP's "disconnect" can be controlled by the `terminateDebuggee` property, but VS Code makes no use of this. VS Code relies on the default behavior of the `disconnect` request: 

- if a debug configuration uses `"request": "launch"`, then the debug adapter is expected to launch the debuggee and consequently it is responsible for terminating it in the implementation of the `disconnect` request.
- if a debug configuration uses `"request": "attach"`, then the debug adapter only "attaches" to an already running debuggee. In this case `disconnect` only needs to "detach" the debugger from the debuggee.

**Comment by zobo** [comment]
However unfortunate, it is what it is. Thank you for clearing this up.

**Comment by weinand** [comment]
Please feel free to turn this issue into a feature request by proposing what UI VS Code should offer to make use of the terminateDebuggee property.

**Comment by weinand** [comment]
BTW, there is another related DAP feature request: https://github.com/microsoft/debug-adapter-protocol/issues/175

**Comment by zobo** [comment]
Great, thanks a lot! I will check it out and make a new feature request in vscode project if what I need isn't covered by that request.

**Comment by weinand** [comment]
Please note that DAP feature requests are independent from VS Code because more clients use DAP and VS Code does not support every feature offered in DAP.

**Comment by polinasok** [comment]
I noticed the same unfortunate behavior in vscode. Setting SupportTerminateDebuggee in the adapter doesn't seem to expose any additional controls to the user. The fact that vscode doesn't use this capability is not clear. For example this [update from 2017](https://code.visualstudio.com/updates/v1_12) says ```"An optional argument, terminateDebuggee, has been added to the disconnect request. If a debug adapter has opted into this feature with the supportTerminateDebuggee capability, a client can use this to control whether the debuggee should be terminated when the debugger is disconnected". ``` I don't see any documentation saying that this option is ignored.

+1 to supporting this feature. In the UI this could be supported as a dropdown next to the detach button or as two different buttons.

**Comment by zobo** [comment]
I agree very much with @polinasok. I have also created a feature request a while back: #116731.

**Comment by weinand** [comment]
We are planning to implement feature #116731 in April.

@polinasok please note, that capabilities like `SupportTerminateDebuggee` do not necessarily trigger anything in a client.
The spec says:
> a client can use this to control whether the debuggee should be terminated when the debugger is disconnected"

So a client can use this, but clients are not required to do so (and older clients could not even know that this feature exists).
