### ISSUE TITLE
vscode.list in sources.list contains 3 architectures

### ISSUE THREAD

**Issue by Robke69** [microsoft/vscode#116039]
- VSCode Version: 1.53.0
- OS Version: debian 10

Steps to Reproduce:

1. install vscode
2. apt update

Now u get messages of debian complaining that its amd64 and not arm or armhf.
By updating the program also updates te vscode.list file so changes are trown away.

It would be more nice to check what the architecture realy is, and put only that in the vscode.list file.

Greetings from the Netherlands !

Rob

**Comment by joaomoreno** [comment]
What repository URL is apt complaining about?

**Comment by Robke69** [comment]
Hi João,

N: Opvragen van het in de configuratie vermeld bestand
'main/binary-armhf/Packages' overgeslagen, vermits pakketbron '
http://packages.microsoft.com/repos/vscode stable InRelease' de
architectuur 'armhf' niet ondersteunt
N: Opvragen van het in de configuratie vermeld bestand
'main/binary-arm64/Packages' overgeslagen, vermits pakketbron '
http://packages.microsoft.com/repos/vscode stable InRelease' de
architectuur 'arm64' niet ondersteunt
N: Bij pakketbron 'http://deb.debian.org/debian buster InRelease' is de
'Version'-waarde gewijzigd van '10.7' naar '10.8'

its in dutch but it not that difficult :) , this is the repo :

http://packages.microsoft.com/repos/vscode stable InRelease
the reson for this is because of the vscode.list file that your program
created in the directory /etc/apt/sources.list.d

it contains this text :

### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/vscode
stable main

the green line should only contain the right architecture, in my case amd64.

u can always call me at +31 657584688

greetings Rob

Op di 9 feb. 2021 om 11:47 schreef João Moreno <notifications@github.com>:

**Comment by joaomoreno** [comment]
Got it. This issue has been resolved. The latest stable, which just got released, will update your URL to `http://packages.microsoft.com/repos/code`, which supports all 3 architectures, so apt won't complain any more.

**Comment by Robke69** [comment]
Thanks João, your quick :)

have a nice day !


Op di 9 feb. 2021 om 16:10 schreef João Moreno <notifications@github.com>:
