### ISSUE TITLE
Apple M1 device "windows" uses a lot of CPU

### ISSUE THREAD

**Issue by zoain-it** [microsoft/vscode#116017]
Issue Type: <b>Performance Issue</b>

I use the "Language Support for Java(TM) by Red Hat" plugin, when writing code faster than the code prompt window pops up. The whole editor becomes very slow and you can see in the task manager that the "window" is using a lot of CPU

The cause is unknown at this point, but there is a good chance that it is a plugin issue. I've sent this problem to the "Language Support for Java(TM) by Red Hat" plugin a few weeks ago, but they haven't responded so far, so I'm here. I hope you can help me to investigate the reason.

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:08.594Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|--crash-reporter-id 98a66260-4af7-4580-8035-6d4430c37e47|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   197	 68267	code-insiders main
    0	    98	 68270	   gpu-process
    0	    33	 68272	   utility
    0	   131	 68448	   shared-process
    0	     0	 69287	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
  126	   705	 69039	   window (Test.java — private)
    0	     0	 69040	     /bin/zsh -l
    0	   557	 69049	     extensionHost
    0	   885	 69239	       /opt/jdk/zulu11.45.27-ca-jdk11.0.10-macosx_aarch64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -noverify -Xmx4G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:/Users/lizhaofa/.m2/lombok-1.18.18.jar -jar /Users/lizhaofa/.vscode-insiders/extensions/redhat.java-0.74.0/server/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar -configuration /Users/lizhaofa/Library/Application Support/Code - Insiders/User/globalStorage/redhat.java/0.74.0/config_mac -data /Users/lizhaofa/Library/Application Support/Code - Insiders/User/workspaceStorage/bf7afe102eea650107ce6ddbcabe35b0/redhat.java/jdt_ws
    0	    49	 69053	     watcherService
    0	    49	 69231	     searchService
    0	    66	 69285	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Test.java — private)
|    Folder (private): 3918 files
|      File types: js(1141) png(574) class(352) java(314) css(244) gif(201)
|                  html(148) svg(94) jpg(36) ttf(24)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
java|red|0.74.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by ghoshanjega** [comment]
yeah I'm seeing high CPU usage in on the latest VScode insiders build and hence high temps

**Comment by zoain-it** [comment]
> yeah I'm seeing high CPU usage in on the latest VScode insiders build and hence high temps

It seems that "Language Support for Java(TM) by Red Hat" has been triggering this issue since the release of the m1 chip (I don't know if it's a plugin issue or a VSCode issue).

**Comment by deepak1556** [comment]
Can you follow the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions and https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to collect the performance profiles and attach them here.

**Comment by zoain-it** [comment]
> Can you follow the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions and https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to collect the performance profiles and attach them here.

[CPU-20210209T051645.118Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/5949047/CPU-20210209T051645.118Z.cpuprofile.txt)

**Comment by zoain-it** [comment]
> > Can you follow the steps at https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions and https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process to collect the performance profiles and attach them here.
> 
> [CPU-20210209T051645.118Z.cpuprofile.txt](https://github.com/microsoft/vscode/files/5949047/CPU-20210209T051645.118Z.cpuprofile.txt)

A demonstration of the specific slowdown can be seen in [vscode-java#1770](https://github.com/redhat-developer/vscode-java/issues/1770)

**Comment by deepak1556** [comment]
<img width="680" alt="Screen Shot 2021-02-09 at 1 41 48 PM" src="https://user-images.githubusercontent.com/964386/107432338-ad6ec800-6adc-11eb-902f-edb46986a3b7.png">

<img width="943" alt="Screen Shot 2021-02-09 at 1 51 55 PM" src="https://user-images.githubusercontent.com/964386/107433315-02f7a480-6ade-11eb-961a-1440649e5ab5.png">



The slowdown calls are from the vscode-java extension, the issue should further be diagnosed in the extension. Closing as there is nothing actionable from vscode.

FYI @alexdima

**Comment by cforce** [comment]
This is not realted to Mac/ M1 chip.
I am using Dell / Intel / Windows . Even if its CPU the rest of my system is still pretty fast, juts VisCode completly freezed or reacts not on clicks for minutes. It started with 1.53.1 official release(doesn't matter which redhat plugin - latest 0.74.0 or 073.0)  Rolling back vscode to 1.52 and all works again as expected

The problem has been introduced with vscode 1.53.1
