### ISSUE TITLE
Cannot read property 'highlightSpans' of undefined

### ISSUE THREAD

**Issue by csnover** [Microsoft/vscode#1160]
Useless stack trace:

```
Cannot read property 'highlightSpans' of undefined
  e.doShow @ workbench.main.js:1598
```

Reproduction code (TypeScript):

```ts
function a() {
	let b = {{
		a: 'string'
	};
}
```

Expected: No fatal error in engine
Actual: Fatal error caused by `b = {{` inside function.

Version: 0.10.3 Mac OS X

**Comment by dbaeumer** [comment]
I can't reproduce this using the latest tsserver which we intend to upgrade to with the next VSCode build. I verified that we don't access highlightSpans in our code.

**Comment by dbaeumer** [comment]
Closing. Please ping @dbaeumer if you still see this with the next build.

**Comment by dbaeumer** [comment]
No ping received. Closing as verified.
