### ISSUE TITLE
The terminal cannot be used due to error report

### ISSUE THREAD

**Issue by lanhuyue** [microsoft/vscode#116087]
When starting, you can see the error message "enoent: no such file or directory, scanner'c:: (users, a1181, appdata, local, Microsoft, windowsapps')" in Ctrl + Shift + I under the console option. This problem also causes the terminal to be unable to initialize

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" integrated-terminal
