### ISSUE TITLE
Add Find in folder

### ISSUE THREAD

**Issue by FileSubmit** [Microsoft/vscode#11608]
- VSCode Version: 1.4.0
- OS Version: Win 10

Please, add feature to search through files in user selected folder.

**Comment by mohsen1** [comment]
You can just right click on ay folder and select "Find in folder"
![screen shot 2016-09-06 at 3 36 42 pm](https://cloud.githubusercontent.com/assets/543633/18293465/c195611c-7447-11e6-87b8-0757c5a475e7.png)

**Comment by ramya-rao-a** [comment]
Also, if you do not want to drill all the way down to the folder to be able to right-click and then `Find in Folder`, you can specify the relative path of your folder to your workspace in the `files to include`  option 

![image](https://cloud.githubusercontent.com/assets/16890566/18296253/23c361bc-745d-11e6-9051-6d044eb89905.png)
