### ISSUE TITLE
Unable to open files in relative directories from the Terminal

### ISSUE THREAD

**Issue by eblot** [microsoft/vscode#116097]
- VSCode Version: Version: 1.53.0
- OS Version: macOS 11.2 (20D64)

Steps to Reproduce:

1. Open VsCode from a terminal, $PWD being a subdirectory of a project, *e.g.*
   ```
   $ pwd
   /Users/user/Sources/Git/QEMU/build
   $ code --disable-extensions ..
   ```
2.  From VsCode, open a terminal
3. cd back to the subdirectory (`cd build`) and build from here, *i.e.* out of source build
4. Alt+Click on a compiler output error/warning message, on a source file path starting with `../`
5. VsCode does not find the path to the source file ("*No matching results*")
6. Removing the leading `../` from the VsCode popup "fixes" the trouble and VsCode is now able to jump to the source file

It seems to be a regression of v1.53.0, as it used to work fine till the last update, and a regression from #58256 

Does this issue occur when all extensions are disabled?: Yes

**Comment by eblot** [comment]
Reverting back to v.1.52.1 fixes the issue. It seems to be a regression with v1.53.0

**Comment by eblot** [comment]
Same issue with v1.53.2

**Comment by eblot** [comment]
Is there any progress on this issue. It seems to be stalled, and using v1.52.1 is starting to be a real issue as the clangd extension is no longer usable: `The language client requires VS Code version ^1.53.0 but received version 1.52.1`.

Thanks.

**Comment by eblot** [comment]
Still there in 1.55.2 :-(

**Comment by eblot** [comment]
- VSCode Version: Version: 1.55.2
- OS Version: macOS 11.2.3 (20D91)

**Comment by eblot** [comment]
Still there with 1.59.0 (Universal)

@isidorn it seems that this ticket has been forgotten. Am I the only one to use out-of-source builds from the Terminal?

**Comment by Tyriar** [comment]
This is caused by https://github.com/microsoft/vscode/issues/78438 disabling lsof to detect the terminal's cwd. Unfortunately the fix is only in our official product builds until the [libuv change](https://github.com/libuv/libuv/pull/3257) goes in so out of source builds will continue having the issue. Track in https://github.com/microsoft/vscode/issues/78438

/duplicate

**Comment by eblot** [comment]
ok thanks for the update.
