### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by keeturan** [microsoft/vscode#116001]
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[5106:0207/002109.002899:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Version:          Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS Version:       Linux x64 5.4.0-65-generic
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)
Memory (System):  3.84GB (0.11GB free)
Load (avg):       3, 2, 2
VM:               50%
Screen Reader:    no
Process Argv:     --no-sandbox --unity-launch --crash-reporter-id 5f78c46f-b413-4982-b2d0-70e12b1e297c
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    0       16    4661  code main
    0        0    4665     zygote
    1       59    4695       gpu-process
    0        0    4666     zygote
    0        0    4706     utility
    0       94    4723     window (bblayers.conf - yocto - Visual Studio Code)
    0        0    4759       /bin/bash
    0        0    5063         sh /usr/bin/code --status
    0       28    5068           electron_node cli.js 
    0       59    5080             /usr/share/code/code --status --no-sandbox
    0       12    5082               zygote
    0       71    5106                 gpu-process
    0       12    5083               zygote
    0        4    5131               utility
    0        0    5132               /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    5133                 /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        8    4768       extensionHost
    0        0    4803         electron_node server.js 
    0       12    4831     shared-process

Workspace Stats: 
|  Window (bblayers.conf - yocto - Visual Studio Code)
|    Folder (yocto): more than 32584 files
|      File types: rpm(3849) siginfo(2447) tgz(811) packaged(798) sample(293)
|                  idx(224) pack(224) done(182) log(88) gz(82)
|      Conf files:

**Comment by keeturan** [comment]
Why does it happen. I don't do anything

**Comment by deepak1556** [comment]
Which linux flavor are you seeing this issue on ?

**Comment by uwenayoallain** [comment]
windows, not Linux 
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.

**Comment by keeturan** [comment]
VirtualBox ubuntu 18.04.5,

Disk usage is heavy for a certain period of time every time I turn it back on.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`

**Comment by keeturan** [comment]
kerem@kerem-VirtualBox:~/yocto-labs/build$ code --verbose
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[main 2021-02-11T12:47:09.278Z] Sending env to running instance...
libGL error:
MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
[3548:0211/154709.775314:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[3548:0211/154709.776879:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[3548:0211/154709.777692:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3548:0211/154709.781479:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[3548:0211/154709.781821:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[3548:0211/154709.782018:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3548:0211/154709.782338:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
[3548:0211/154709.984837:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
[main 2021-02-11T12:47:13.235Z] Sent env to running instance. Terminating...
[main 2021-02-11T12:47:13.235Z] Lifecycle#kill()
kerem@kerem-VirtualBox:~/yocto-labs/build$

**Comment by deepak1556** [comment]
Was the log cut off ? I only see the gpu process initialization step and exit logs. Can you try running with `code --verbose --use-gl=swiftshader` and also provide the output of `code --status` with this run.

**Comment by keeturan** [comment]
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
[3325:0211/215918.285602:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[3325:0211/215918.289189:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[3325:0211/215918.290058:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
[3325:0211/215918.290721:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: Could not create a backing OpenGL context.
[3325:0211/215918.294031:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: Could not create a backing OpenGL context.
[3325:0211/215918.294152:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[3325:0211/215918.298070:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.
[3325:0211/215918.506686:ERROR:viz_main_impl.cc(150)] Exiting GPU process due to errors during initialization
Version:          Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:30:54.166Z)
OS Version:       Linux x64 5.4.0-65-generic
CPUs:             Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)
Memory (System):  3.84GB (0.11GB free)
Load (avg):       3, 3, 1
VM:               100%
Screen Reader:    no
Process Argv:     --force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id ee380c01-7c9b-43ab-83ac-dc47295f1887
GPU Status:       2d_canvas:                  unavailable_software
                  gpu_compositing:            disabled_software
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     disabled_off
                  protected_video_decode:     disabled_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      unavailable_software
                  webgl2:                     unavailable_software

CPU %   Mem MB     PID  Process
    5       28    2091  code main
    0        0    2093     zygote
    0       35    2132       gpu-process
    0        0    2094     zygote
    0        0    2131     utility
    0       94    2148     window (linux-ti-staging_4.14.bbappend - yocto-labs - Visual Studio Code)
    0        0    2183       /bin/bash
    0        4    2192       extensionHost
    0        0    2242         electron_node server.js 
    0       24    2223     shared-process
   10      146    3202     window (Untitled-1 - Visual Studio Code)
    0       39    3228       extensionHost
    0        0    3253       /bin/bash
    0        0    3263         sh /snap/code/54/usr/share/code/bin/code --status
    0       24    3287           electron_node cli.js 
    0       67    3299             /snap/code/54/usr/share/code/code --status --no-sandbox
    0       12    3301               zygote
    0       31    3338                 gpu-process
    0       12    3302               zygote
   10        0    3341               utility
    0        0    3349               /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0        0    3350                 /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Workspace Stats: 
|  Window (linux-ti-staging_4.14.bbappend - yocto-labs - Visual Studio Code)
|    Folder (yocto-labs): more than 28858 files
|      File types: siginfo(3844) tgz(1320) rpm(426) sample(331) idx(267)
|                  pack(267) done(202) gz(91) 1(53) bz2(47)
|      Conf files: settings.json(1)

**Comment by deepak1556** [comment]
I don't see any abnormal cpu usage in the status info, but gpu is definitely crashing due to the GL errors with virtualbox.

```
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
```

Might want to try disabling hw acceleration on the box and start the app with `--disable-gpu`. There is nothing much that can be done from the app here.
