### ISSUE TITLE
extension devlop multiple "view/item/context" displays overlap

### ISSUE THREAD

**Issue by Fu-Shengsheng** [microsoft/vscode#116023]
- VSCode Version: 1.53.0

Steps to Reproduce:

1. VScode extension when my package.json write like this: 
```json
{
  "contributes": {
    "menus": {
      "view/item/context": [{
					"command": "a.test",
					"group": "inline"
				},
				{
					"command": "b.test",
					"group": "inline"
				}
			]
    }
  }
}
```

2. my extension ui willbe looks like:
<img width="1597" alt="issue" src="https://user-images.githubusercontent.com/32768330/107142266-960ece00-6968-11eb-9293-df0f03b4e9b2.png">

3. Ithink the problem causes is the "display: inline-flex;"，and I solved it localy by change "width:16px;" to  "min-width:16px;"

**Comment by alexr00** [comment]
Looks like this is already fixed by https://github.com/microsoft/vscode/issues/116235
