### ISSUE TITLE
Line/column indicator only updating at one side in Diff mode

### ISSUE THREAD

**Issue by Renzo904** [microsoft/vscode#116011]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Compare two files
2. Move the cursor on the left side
3. The line/column indicator it does not update

Indicator working properly
![image](https://user-images.githubusercontent.com/63516530/107134818-3ff04b00-68d4-11eb-90ee-8c2a51216910.png)
Indicator not working properly(Should be "**Ln 4, Col 3 (9 selected)**")
![image](https://user-images.githubusercontent.com/63516530/107134986-b9d50400-68d5-11eb-8c7f-af984a5860a2.png)

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:50.117Z)
OS version: Windows_NT x64 10.0.19042

**Comment by yume-chan** [comment]
It's even worse for me because I have line numbers turned off.

**Comment by alexdima** [comment]
Historically, we have made the status bar only work with the right-hand-side editor. That is true for the line number; column indication, but is also true for the file encoding, indentation selector, EOL selector and language selector.

fyi @bpasero
