### ISSUE TITLE
Error after installing extension

### ISSUE THREAD

**Issue by hundai0730** [microsoft/vscode#116089]
- VSCode Version: Insiders 1.54.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. download vscode-insiders.zip
2. copy to C:\Program Files
3. start vscode and install any extension, that will be show 'Cannot read property 'name' of undefined'

![error](https://user-images.githubusercontent.com/19946098/107196808-0e8b9280-6a2e-11eb-9a7a-a9ea1c02924a.png)

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
Or are you saying this happens no matter which extension you try and install?

Also, I don't understand why you are downloading the Insiders as a zip and then copying it to c:\Program Files. Why not download the Insiders installer and run it?

**Comment by hundai0730** [comment]
> Or are you saying this happens no matter which extension you try and install?
> 
Yes, but this issue seems to be only happening in the specified commit

This commit didn't happen

![no problem commit](https://user-images.githubusercontent.com/19946098/107310390-45fa4d80-6ac7-11eb-8950-8299b86038e7.png)

This commit will be happen

![issue commit](https://user-images.githubusercontent.com/19946098/107310311-2400cb00-6ac7-11eb-9991-fcaf0dfe902d.png)
