### ISSUE TITLE
powershell 7 not showing

### ISSUE THREAD

**Issue by Govind-Keshri** [microsoft/vscode#116032]
We have written the needed data into your clipboard because it was too large to send. Please paste.

(1) open visual studio code
(2) click on terminal then select new terminal 
(3) in terminal click on the down arrow select  default shell
(4) it only shows only two options **cmd** and **powershell 1.0**
issue
(5) i installed **powershell 7.1.1** and add it to **windows path** but it cannot show in 
**preferred terminal shell** option it shows in VSCode-win32-ia32-1.52.1 but not showing in VSCode-win32-ia32-1.53.0 i use the both zip package versions

**Comment by isidorn** [comment]
fyi @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
@Govind-Keshri custom installations of PowerShell are not supported in the "select default shell"  as the PowerShell discovery code does not use the PATH to find pwsh's (intentionally). However, you can always set the setting:

```
"terminal.integrated.shell.windows": "C:\\path\\to\\your\\pwsh.exe",
```

and that will work just fine for your need.

**Comment by Govind-Keshri** [comment]
> @Govind-Keshri custom installations of PowerShell are not supported in the "select default shell" as the PowerShell discovery code does not use the PATH to find pwsh's (intentionally). However, you can always set the setting:
> 
> ```
> "terminal.integrated.shell.windows": "C:\\path\\to\\your\\pwsh.exe",
> ```
> 
> and that will work just fine for your need.

> i tried your  "terminal.integrated.shell.windows": "C:\\path\\to\\your\\pwsh.exe" method

 before report issue it worked in VSCode-win32-ia32-1.53.0 )) though i do it manually it cannot show in preferred shell when i chose new terminal it shows 
PowerShell 7.1.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

> but but why i do it manually it detect automatically in VSCode-win32-ia32-1.52.1 and not in VSCode-win32-ia32-1.53.0

**Comment by TylerLeonhardt** [comment]
@Govind-Keshri what is the path to your PowerShell? Also, what OS and architecture are you running on?

**Comment by Govind-Keshri** [comment]
> @Govind-Keshri what is the path to your PowerShell? Also, what OS and architecture are you running on?

my path C:\Program Files\PowerShell\7\pwsh.exe

PowerShell-7.1.1-win-x64.msi )) worked in VSCode-win32-ia32-1.52.1 (( not worked in VSCode-win32-ia32-1.53.0 (*zip version both)

OS Windows 10 64bit version 2004 (OS Build 19041.264)

**Comment by Govind-Keshri** [comment]
i am am very happy to see how active github is i appreciate and thank you for reply

**Comment by TylerLeonhardt** [comment]
Is there a reason you use the 32bit version of VS Code instead of the 64bit version?

**Comment by Govind-Keshri** [comment]
> @Govind-Keshri what is the path to your PowerShell? Also, what OS and architecture are you running on?

in very happy to see how active github is i appreciate and thank you for reply

**Comment by Govind-Keshri** [comment]
> Is there a reason you use the 32bit version of VS Code instead of the 64bit version?

your thought is right it is an architecture problem 

i just download the VSCode-win32-ia32-1.53.1.zip and VSCode-win32-x64-1.53.1.zip and it not working in 32bit and working in 64

i thought vscode dropped the path detection from VSCode-win32-ia32-1.52.1 to VSCode-win32-ia32-1.53.0

**Comment by Govind-Keshri** [comment]
> Is there a reason you use the 32bit version of VS Code instead of the 64bit version?

i install  PowerShell-7.1.1-win-x86.msi  and it detect in 32bit vscode

**Comment by TylerLeonhardt** [comment]
Thanks for the info!

**Comment by Govind-Keshri** [comment]
> Thanks for the info!

it is a bug i thought vscode dropped the path detection thank you  for all your support and detect the bug

**Comment by TylerLeonhardt** [comment]
I've got a fix out for this now ^

**Comment by TylerLeonhardt** [comment]
Test plan:

1. Download **32bit** version of VS Code and [install PowerShell 7 **x64 MSI**](https://github.com/PowerShell/PowerShell#get-powershell)
1. make sure you don't have a default shell set for Windows

Expected:

PowerShell 7 should show in your terminal and it should be 64bit (run `[System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture` which should be `X64`)

Also, choose the default shell in the terminal drop down. You should see PowerShell 7 in the list.

Other Test plan:

1. Download **64bit** version of VS Code and [install PowerShell 7 **x64 MSI**](https://github.com/PowerShell/PowerShell#get-powershell)
1. make sure you don't have a default shell set for Windows

Expected:

PowerShell 7 should show in your terminal and it should be 64bit (run `[System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture` which should be `X64`)
