### ISSUE TITLE
Support for pseudo terminal on Web

### ISSUE THREAD

**Issue by bummoblizard** [microsoft/vscode#116022]
1. Create a pseudo terminal in a web extension
```ts
const writeEmitter = new vscode.EventEmitter<string>();
const pty: vscode.Pseudoterminal = {
  onDidWrite: writeEmitter.event,
  open: () => writeEmitter.fire('\x1b[31mHello world\x1b[0m'),
  close: () => {}
};
vscode.window.createTerminal({ name: 'My terminal', pty });
```
2. `yarn web`
3. Error: `Could not create terminal when process support is not registered`

From my understanding, terminal is disabled on web due to the lack of process support. Should this affect the use of pseudo terminal as well? In my use case, I would like to create a fake terminal in my web extension.

**Comment by Tyriar** [comment]
The `Pseudoterminal` API will work when actually running in web like Codespaces, just not when running `yarn web` as it's a stripped down version of the server.

**Comment by Tyriar** [comment]
Repening as live share web would like this

**Comment by setaskin** [comment]
Hi, @Tyriar , is it scheduled to be fixed soon :) ?

**Comment by Tyriar** [comment]
We'll try squeeze this into the iteration for next week

**Comment by Tyriar** [comment]
Fixed showing the select default shell command which doesn't work without an ext host while working on this: 
![Uploading image.png…]()

**Comment by Tyriar** [comment]
@setaskin this should land in tomorrow's insiders build, if you could test whether this works for you sometime this week (ideally) that would be great!

**Comment by setaskin** [comment]
@Tyriar that is awesome!, I will test as first thing tomorrow. Thank you very much

**Comment by setaskin** [comment]
@Tyriar , I just tested with insiders. They are working great. Thanks again.

**Comment by Tyriar** [comment]
Good to hear 🙂
