### ISSUE TITLE
Missing code formatter, intellisense, code navigation in 1.53

### ISSUE THREAD

**Issue by zandr14** [microsoft/vscode#116091]
- VSCode Version: 1.53
- OS Version: CentOS Linux 7

Steps to Reproduce:

1. I installed 1.53 from within rpm package on the box without internet.
2. cd to src folder with my sources, run 'code .'
3. Now I can't format typesrcipt/javascript documents and all the stuff regarding intellisense and code navigation is missing: when I open context menu it's almost empty. Below is the image from 1.52.1, in 1.53 all the stuff which is inside the red rectangle is missing, context menu is almost empty:
![1](https://user-images.githubusercontent.com/19690588/107198880-bb521980-6a06-11eb-8e98-28d83c2421de.png)
4. if I try to run Format doc command I get the message  'There is no formatter for '...''
5. When I reverted back to 1.52.1 all works fine. Weird...

Extensions I have:
esbenp.prettier-vscode-5.8.0
firefox-devtools.vscode-firefox-debug-2.9.1
msjsdiag.debugger-for-chrome-4.12.11
ms-vscode.node-debug2-1.42.5
octref.vetur-0.31.3

Does this issue occur when all extensions are disabled?: Don't know.

**Comment by gjsjohnmurray** [comment]
Please use the Begin Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by zandr14** [comment]
Tried. No effect at all.

**Comment by gjsjohnmurray** [comment]
/duplicate

1.53 is not compatible with CentOS 7. See https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356
