### ISSUE TITLE
Word Wrap will hide some word in RTL text, below minimap panel

### ISSUE THREAD

**Issue by amirhakh** [microsoft/vscode#116180]
- VSCode Version: 1.53.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create the new document
2. Enable Word Wrap
3. Type long RTL text like below
4. When resizing the window, some word hide below the minimap and can see that word when using horizontal scrolling and scroll to the right
5. As you see, when the scroll panel at left, the `که` word is hidden, and when scroll to the right, the first word of the wrapped line will be hidden.

>  یک متن بلند فارسی برای بررسی حالت فعال word wrap که در صورت رسیدن به سمت راست صفحه، کمی خراب دیده می‌شود. یک متن بلند فارسی برای بررسی حالت فعال word wrap که در صورت رسیدن به سمت راست صفحه، کمی خراب دیده می‌شود.

left scroll (default):
![left scroll](https://user-images.githubusercontent.com/2285342/107350297-844f3700-6ade-11eb-8888-3f08010456d9.png)

right scroll:
![right scroll](https://user-images.githubusercontent.com/2285342/107350294-831e0a00-6ade-11eb-8149-6c801b2c2616.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@amirhakh You can use `"editor.wrappingStrategy": "advanced"` which delegates wrapping points computation to the browser. This is a slow algorithm, that might cause freezes for large files, but it works correctly in all cases.
