### ISSUE TITLE
Using SFTP extension. Extension host terminated unexpectedly (SIGSEGV)

### ISSUE THREAD

**Issue by elvenfighter** [microsoft/vscode#116186]
After VS Code upgrade on GNU/Linux (Ubuntu 20.10 x86_64)  to version 1.53.0-1612368357 the SFTP extension stopped working issuing the abovementioned error. Downgrading VS Code to version 1.52.1-1608136922 works around the issue (everything works as expected, including the extension).

Here is the log from Developer Tools console:
[-1612869483251.log](https://github.com/microsoft/vscode/files/5951048/-1612869483251.log)

**Comment by 778629322** [comment]
在.vscode/sftp.json里添加
