### ISSUE TITLE
Repeat the last word when using Telex keyboard

### ISSUE THREAD

**Issue by PeaceWill** [microsoft/vscode#116175]
- VSCode Version: 1.53.0
- OS Version: Windows_NT x64 10.0.19042

I just change my laptop to MSI and when I use Vietnamese (Telex) keyboard, the last word will repeat after I press enter or click in another place.

**Steps to Reproduce:**

1.  Open a new page in VS
2. Change to Vietnamese (Telex) keyboard
3. Type any word or character and click mouse in another line, it's will repeat the word I just type

This issue also occurs when I disable all extensions.

<details>
<summary>System Information</summary>

CPUs | 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: enabled rasterization: enabled skia_renderer: enabled_on video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.71GB (11.45GB free)
Process Argv | --crash-reporter-id 19893df6-d050-4021-b4c2-7ecdf0795f09
Screen Reader | no
VM | 0%

</details>

<details>
<summary>Extensions</summary>

Extension | Author (truncated) | Version
-- | -- | --
html-snippets | abu | 0.2.1
Bookmarks | ale | 12.1.4
code-gnu-global | aus | 0.2.2
vscode-django | bat | 1.3.0
githistory | don | 0.6.14
python-extension-pack | don | 1.6.0
zsh-completion-script | dua | 1.0.0
vscode-html-css | ecm | 1.9.1
prettier-vscode | esb | 5.9.1
pip-packages | etm | 0.4.3
font-switcher | eva | 3.1.0
mithril-emmet | Fal | 0.7.6
git-project-manager | fel | 1.7.1
code-runner | for | 0.11.2
terminal | for | 0.0.10
vscode-csharp-snippets | jor | 1.1.0
vscode-github | Kni | 0.30.4
csharpextensions | kre | 1.3.6
MagicPython | mag | 1.1.0
start-git-bash | McC | 1.2.1
vscode-clang | mit | 0.2.3
csharp | ms- | 1.23.9
python | ms- | 2021.1.502429796
vscode-pylance | ms- | 2021.2.0
jupyter | ms- | 2020.12.414227025
azure-account | ms- | 0.9.5
cpptools | ms- | 1.2.0
vscode-open-iterm2 | mus | 0.0.4
material-icon-theme | PKi | 4.5.0
java | red | 0.74.0
vscode-yaml | red | 0.14.0
LiveServer | rit | 5.6.1
zsh-debug | rog | 0.1.3
csharp-code-snippets | Som | 0.0.1
code-spell-checker | str | 1.10.2
python | tht | 0.2.3
usql-vscode-ext | usq | 0.2.15
vscodeintellicode | Vis | 1.2.11
vscode-java-debug | vsc | 0.31.0
vscode-java-dependency | vsc | 0.18.0
vscode-java-pack | vsc | 0.12.1
vscode-java-test | vsc | 0.28.0
vscode-maven | vsc | 0.27.1
jinja | who | 0.0.8
html-css-class-completion | Zig | 1.20.0

</details>

<details>
<summary>A/B</summary>

vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590
core-portspanel:30255213

</details>

**Comment by PeaceWill** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

okay, I have added System information and Extensions

**Comment by jrieken** [comment]
please simple and reliable repro steps which include the file (in source, not screen host) and what characters you are typing
