### ISSUE TITLE
Make it easier to switch between menu bar locations

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#116142]
There are 2 possible locations for the menu bar: the title bar and the activity bar.

We should make it easier to move between these settings from the menu location itself.

**Comment by sbatten** [comment]
Options:

**Context Menu on the Title Bar**
![image](https://user-images.githubusercontent.com/6561887/107279350-c9566900-6a0b-11eb-99a4-d3b9c6dd3f3f.png)

**Appearance Menu Entry**
![image](https://user-images.githubusercontent.com/6561887/107280031-a9737500-6a0c-11eb-9b33-e704148b7f47.png)

**Activity Bar Context Menu**
![image](https://user-images.githubusercontent.com/6561887/107280600-65cd3b00-6a0d-11eb-8429-5b19c8e92990.png)

**Comment by bpasero** [comment]
I find the context menu on our custom title slightly irritating because I would expect the OS native entries in there for window management.

**Comment by bpasero** [comment]
Actually nevermind, we seem to support the native menu:

![image](https://user-images.githubusercontent.com/900690/107334913-9c5f9000-6ab7-11eb-97ce-88eea3d9e7ea.png)

So I think having a custom context menu is not an option.

**Comment by sbatten** [comment]
@bpasero, yes agreed about the native menu, alternatively I could put the custom context menu only on the menu itself or only in web

**Comment by sbatten** [comment]
New behavior:
✔️ Show Menu Bar => classic
🚫 ✔️ Show Menu Bar => compact
When menu bar is not visible or compact, use the activity bar context menu to hide fully
