### ISSUE TITLE
Missing right click option

### ISSUE THREAD

**Issue by Darkfish888** [microsoft/vscode#116137]
Issue Type: <b>Bug</b>

Version 1.53.0 - Python

Right clicking on a function or class used to give the option to go to Definition.  This has suddenly vanished, much to my distress!

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux arm 5.4.83-v7+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.19GB free)|
|Process Argv|--crash-reporter-id dda82bfd-c40b-43f6-a28d-42e78c8eba67|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.1.136|
|OS|Linux arm 5.4.83-v7+|
|CPUs|ARMv7 Processor rev 4 (v7l) (4 x 1400)|
|Memory (System)|0.90GB (0.08GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
vscode-remote-extensionpack|ms-|0.20.0
jinja|who|0.0.8
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025

</details>

**Comment by sbatten** [comment]
@Darkfish888 can you provide a screen shot of your experience? I am unable to reproduce this issue with the latest python extension installed.

**Comment by Darkfish888** [comment]
Steve,

I have no idea why, but this morning when I logged on all it working as it should be.  Sorry for wasting your time.  FYI I am developing code on an RPi using SSH and normally this works a treat.

Regards,

Marc




@Darkfish888 can you provide a screen shot of your experience? I am unable to reproduce this issue with the latest python extension installed.

**Comment by sbatten** [comment]
@Darkfish888 I will close for now. I wonder if there was some issue with the Python extension or just some delay in its activation. Thanks for getting back.
