### ISSUE TITLE
Search tree is often misaligned at the bottom

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116182]
![image](https://user-images.githubusercontent.com/22350/107353427-e168cf80-6a81-11eb-98ef-f767c5e8e8ec.png)

**Comment by roblourens** [comment]
I can repro an issue after clicking "clear" but not when there are search results. Are you zoomed or something? We have to measure the message element because it might be wrapped, I think that's the only odd part.

**Comment by roblourens** [comment]
It's also possible that the change I pushed for "clear results" will fix whatever you saw

**Comment by joaomoreno** [comment]
> Are you zoomed or something?

No zoom here.

> I can repro an issue after clicking "clear" but not when there are search results.

When I click clear, the issue gets fixed 🤷 

---

To repro in `microsoft/vscode`:

1. Click the `...` to expand `files to include` et al
2. Search for `constructor-super": "warn`
3. Click the empty space

**Comment by roblourens** [comment]
I think today's Insiders was delayed so you were trying in a build without the change. I still just don't see an issue with your steps though. If it still happens in the next build, I will probably just close this and move on. If you want to debug it you can check whether `SearchView#relayout` is doing the wrong thing or not being called

**Comment by joaomoreno** [comment]
I think this might be related to my Windows scaling setting: 

![image](https://user-images.githubusercontent.com/22350/107660848-8d0a4f00-6c3d-11eb-977f-c822f3879b9e.png)

Here's why:

![recording (11)](https://user-images.githubusercontent.com/22350/107661059-bcb95700-6c3d-11eb-97b6-8810fd63d265.gif)

It keeps jumping up and down, as if there's a rounding error half of the times the measurement happens.

> We have to measure the message element because it might be wrapped, I think that's the only odd part.

What if instead of measuring the message element in order to give a pixel height to the tree, we would instead let the tree container stretch with flex and let the tree measure that itself?

**Comment by roblourens** [comment]
That makes sense. I think that would be a good approach. I could do that from outside the tree too. Would be nifty if the tree could measure its container itself. I would probably still have to tell it when it changed, unless you want to use a ResizeObserver

**Comment by joaomoreno** [comment]
> Would be nifty if the tree could measure its container itself.

That's already implemented, just pass `undefined` as a height: https://github.com/microsoft/vscode/blob/bab55b86fc5f1f3ef8a107a8e98757d75575040c/src/vs/base/browser/ui/list/listView.ts#L677-L677

**Comment by roblourens** [comment]
Oh cool, didn't know that

**Comment by roblourens** [comment]
I think this is much better. Flexbox solves all problems
