### ISSUE TITLE
Search in files not pasting selected text using keyboard shortcut

### ISSUE THREAD

**Issue by tomaxsas** [microsoft/vscode#116188]
Issue Type: <b>Bug</b>

When search is not opened and text is selected, when pressing Ctrl+Shift+F search is opened but text is not filled in. When using command pallete it works fine

VS Code version: Code - Insiders 1.54.0-insider (cd97629c4458c05b16a1fd444d21c61295ba2529, 2021-02-09T08:37:01.449Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (70)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.0.1
go-snippets|ban|0.1.2
haproxy|bma|0.1.2
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.38.0
vscode-quick-select|dba|0.2.9
xml|Dot|2.5.1
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
python-ultisnippets|eli|2.7.0
LogFileHighlighter|emi|2.11.0
opensslutils|ffa|1.1.1
url-encode|fle|1.1.0
auto-close-tag|for|0.5.10
code-runner|for|0.11.2
shell-format|fox|7.0.1
todo-tree|Gru|0.0.196
vscode-nginx-conf-hint|han|0.1.0
vscode-systemd-support|han|0.1.1
vscode-guid|hea|1.4.20
rest-client|hum|0.24.4
vscode-hexdump|ili|1.8.2
path-autocomplete|ion|1.17.1
nginx-log-highlighter|jak|1.1.0
saltstack|kor|0.0.8
rpm-spec|Lau|0.3.1
bash-ide-vscode|mad|1.11.0
yarn-lock-syntax|mar|0.1.3
code-groovy|mar|0.1.2
rainbow-csv|mec|1.8.1
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
ecdc|mit|1.4.0
vscode-filesize|mkx|2.1.4
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.4.0
powershell-preview|ms-|2020.9.0
sublime-keybindings|ms-|4.0.7
linesinfostatusbar|pet|0.0.3
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.14.0
shellman|Rem|4.10.0
shebang-snippets|rpi|0.1.4
jinjahtml|sam|0.16.0
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.16
vscode-fileutils|sle|3.4.4
vscode-taskexplorer|spm|1.30.2
code-spell-checker|str|1.10.2
shellcheck|tim|0.13.2
shell-launcher|Tyr|0.4.1
vscode-counter|uct|2.2.2
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
bracket-lens|wra|1.5.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by tomaxsas** [comment]
![ctflhiftf5](https://user-images.githubusercontent.com/12826401/107359618-91b7f180-6add-11eb-8943-e7a2758c835f.gif)

**Comment by dlong500** [comment]
Note that it should be clarified that this is a regression.  The expected behavior was working fine and broke sometime over the last week in the insiders branch.

**Comment by JacksonKearl** [comment]
Seems to be from the changes in #115289, cc @sandy081  

Pushed a change to never run the `View: Show Search` command but instead always prefer `Find in Files`.

**Comment by sandy081** [comment]
Sorry about that and thanks for the fix.
