### ISSUE TITLE
No run button on the top right corner

### ISSUE THREAD

**Issue by armenhakob** [microsoft/vscode#116172]
I have updated the VSCode and the button disappeared

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including screenshot. It sounds like a button contributed by one of your extensions.

Next time you open an issue please use Report Issue from the Help menu. That way you will get the information included automatically.

**Comment by armenhakob** [comment]
<img width="547" alt="Screen Shot 2021-02-09 at 14 04 53" src="https://user-images.githubusercontent.com/76571160/107348041-f2e0c480-6adf-11eb-8b51-2a06a4a5721f.png">

I had a green button which was running the code in terminal, and it disappeared after version update. The button wasn't contributed by an extension.  VSCode version - 1.53.0

**Comment by gjsjohnmurray** [comment]
@armenhakob what language are you coding in?

**Comment by armenhakob** [comment]
> @armenhakob what language are you coding in?
python 3.8

**Comment by gjsjohnmurray** [comment]
/extPython [(evidence)](https://github.com/microsoft/vscode/issues/114123#issuecomment-773551247)
