### ISSUE TITLE
Sync related services could benefit from channel sender/receiver

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116191]
Noticed that many settings sync related services that talk to the shared process could greatly benefit from our [`createChannelReceiver`](https://github.com/microsoft/vscode/blob/1abefb9be2a9e33a78f4e9bacda722095d342a23/src/vs/base/parts/ipc/common/ipc.ts#L1056-L1056) and [`createChannelSender`](https://github.com/microsoft/vscode/blob/1abefb9be2a9e33a78f4e9bacda722095d342a23/src/vs/base/parts/ipc/common/ipc.ts#L1114-L1114). 

E.g. this code:

https://github.com/microsoft/vscode/blob/b6545a0db66e3c3e4ba62bb9762608291fd42ee9/src/vs/workbench/services/userDataSync/electron-browser/userDataAutoSyncService.ts#L25-L35

Is not needed anymore.

**Comment by joaomoreno** [comment]
FYI @sandy081 I just renamed Ben's proxy utils: https://github.com/microsoft/vscode/pull/116308
