### ISSUE TITLE
IActionViewItem should not live in common

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116112]
The [`IActionViewItem`](https://github.com/microsoft/vscode/blob/2a38ef15feb4042dcd448443b2803a6471e3138f/src/vs/base/common/actions.ts#L42-L42)-type defines the html rendering of an action. However, for some unknown reason that interface is defined in `common`  (src/vs/base/common/actions.ts), with an ugly render-signature like this: `render(element: any /* HTMLElement */): void;`. There used to be a duplicate definition, and more correct declaration of that interface but that got (rightfully) removed by @joaomoreno via https://github.com/microsoft/vscode/commit/e7279b1c505569c52d9f813b9c76476374001db0.

This issue is about moving the type into its correct location and that starts with fixing dependencies that also live in common. I could only find two: src/vs/workbench/common/views.ts#IViewPaneContainer and src/vs/workbench/common/composite.ts#IComposite.

**Comment by joaomoreno** [comment]
> There used to be a duplicate definition, and more correct declaration of that interface but that got (rightfully) removed by @joaomoreno via [e7279b1](https://github.com/microsoft/vscode/commit/e7279b1c505569c52d9f813b9c76476374001db0).

It was a lovely week, everybody on vacation, so I went around the codebase with a chainsaw.

**Comment by jrieken** [comment]
🪓  Yeah, not blaming. the action and action rendering world hasn't received any love in last 5 years - it's about time

**Comment by sandy081** [comment]
Removed it from `src/vs/workbench/common/views.ts#IViewPaneContainer`.

Assigned @bpasero for`src/vs/workbench/common/composite.ts#IComposite.`

**Comment by bpasero** [comment]
I removed `IActionViewItem` from `IComposite`, I think moving `IComposite` is not an option.

**Comment by jrieken** [comment]
Thanks everyone
