### ISSUE TITLE
editor.codeLensFontFamily setting only work temporarily on macOS 10.13.6

### ISSUE THREAD

**Issue by inetfuture** [microsoft/vscode#116104]
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|-psn_0_90134 --crash-reporter-id fdea18b1-6d1e-46eb-a4e5-bd8e595aad3a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

Steps to Reproduce:

1. Change global editor.codeLensFontFamily setting to `'Courier New'`（a mono space font on macOS）.
2. Reload window.
3. Open a file tracked by Git, Git CodeLens first shows with default font, then `'Courier New'`.
4. Switch to another file, Git CodeLens shows with default font, always.
5. Swithc back to the first file, Git CodeLens shows with default font, always, `'Courier New'` not working any more, font size works though.

![Kapture 2021-02-08 at 21 09 53](https://user-images.githubusercontent.com/1363189/107224178-0e9d8980-6a52-11eb-8bbd-f5a353720dbc.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
I can reproduce. The font family is defined with a css variables and the dom node that holds the value of that variable isn't around yet when receiving configured styles...
