### ISSUE TITLE
Allow TreeItems to have optional checkboxes

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#116141]
I'm all for trying to avoid webviews as much as possible, especially when tree views are hard to make work in a webview. This proposal allows for treeviews to have checkboxes:

![image](https://user-images.githubusercontent.com/2644648/107271969-dcfcd200-6a01-11eb-875c-e5aba822d4db.png)
(but better styling of course 😄)

#### Scenarios

* To-do list extensions
* Applying filters where an 'Edit' button drops you into the experience above where checkboxes show up
* Crafting `.gitignore`'s or other 'ignores' where you go down the filesystem and uncheck the files you want to ignore

#### Proposal

* TreeItem has new optional property called `checkboxState` similar to `collapsibleState` which takes in a `TreeItemCheckBoxState`:
```ts
        export class TreeItem {
            // ...

            /**
             * [TreeItemCheckboxState](#TreeItemCheckboxState) of the tree item.
             */
            checkboxState?: TreeItemCheckboxState;

            // ...
        }

       /**
	 * Checkbox state of the tree item
	 */
        export enum TreeItemCheckboxState{
		/**
		 * Determines an item can be neither checked nor unchecked. Implies it has no checkbox.
		 */
		None = 0,
		/**
		 * Determines an item is checked
		 */
		Checked = 1,
		/**
		 * Determines an item is unchecked
		 */
		Unchecked = 2
	}

```
* `TreeDataProvider` will have a new optional event `onDidChangeTreeCheckbox` which will fire when the checkbox of a `TreeItem` is checked or unchecked:
```ts
        /**
	 * A data provider that provides tree data
	 */
	export interface TreeDataProvider<T> {
                // ...

                /**
		 * An optional event to signal that an element or root has either been checked or unchecked.
		 */
		onDidChangeTreeCheckbox?: Event<ChangeTreeCheckboxEvent<T>>;

                // ...
        }

        export interface ChangeTreeCheckboxEvent {
                /**
		 * The item that was checked or unchecked.
		 */
		readonly item: <T>;

		/**
		 * Removed workspace folders.
		 */
		readonly newState: TreeItemCheckboxState;
        }
```

**Comment by TylerLeonhardt** [comment]
btw, this is essentially an alternative to https://github.com/microsoft/vscode/issues/115365

**Comment by joaomoreno** [comment]
Interesting that some internal tree usages already do something similar:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/22350/181593021-86bf14ee-d9d9-4b02-a9f3-a4017824ec72.png">

**Comment by albertelo** [comment]
@daviddossett @misolori Hi folks, this feature request has come up for some of our extension authors. Since the last update was more than a year ago, I was wondering if you had this in your pipeline for the near future?

**Comment by alexr00** [comment]
You should see this appear on our August iteration plan :).

**Comment by benibenj** [comment]
API Proposal: #158250

**Comment by alexr00** [comment]
Re-opening to track API proposal.

**Comment by mattseddon** [comment]
Would it be possible to add an indeterminate (middle) state checkbox to the API? This would match the webview toolkit: https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/checkbox/README.md

**Comment by alexr00** [comment]
When next we revisit this: we also need to add an aria label to the checkbox.

**Comment by Eskibear** [comment]
Here is a use case from Maven extension. Currently we use icon and inline actions to mimic the checkbox, see https://github.com/microsoft/vscode-maven/pull/956#issuecomment-1471187283

Version: 1.78.0-insider (user setup)
Commit: e5512217bcfb2b644fe7ad6c465fe0b45d23265b

When I was switching to treeItemCheckbox APIs, I find some problems:

#### 1. checkbox is not rendered if initial state is `Unchecked`.
![image](https://user-images.githubusercontent.com/2351748/231377854-7aaa7d12-e0db-455a-a93b-8074d7b4874b.png)
By [setting checkboxState to unchecked](https://github.com/microsoft/vscode-maven/pull/963/files#diff-83ef84d04dc4bba390a51a3937221dc76404cde4402ea23e5b44ed98e4e00afdR28-R33), I expect there to be an unchecked box before item `p-parent`.

#### 2. by check/uncheck, context value is not updated unless I signal the element has changed
I expect context value to reflect the checked status of the items, so I can register entries accordingly. But it's not re-calculated after checkging/unchecking. `onDidChangeCheckboxState` seems not to re-render the item, and the event is fired after `getTreeItem` is called. So when I listen to the event and modify the element, the change won't be displayed correctly in the tree view.

I don't know if it's a problem, as a workaround I can use `onDidChangeTreeData` to refresh the item (although `getTreeItem` will be called twice then).

#### do we need indeterminate state for the checkbox?
It might be useful to convey the information of "default" status, but I don't know if that would be more complicated and mess up the state. Anyway, I can live without it, for the moment.

**Comment by alexr00** [comment]
@Eskibear thank you for trying out the API! I'm going to start the finalization process for this next month and I'll address/look into all of your comments then.

**Comment by alexr00** [comment]
> 1. checkbox is not rendered if initial state is Unchecked.

@Eskibear I'm not able to reproduce this. Are you able to reproduce this by adding a checkbox to tree items in the [tree view sample](https://github.com/microsoft/vscode-extension-samples/blob/f7b27a91779e770b8f8f0e6791bcefc5d9c64035/tree-view-sample/src/testView.ts#L50-L51}.

> 2. by check/uncheck, context value is not updated unless I signal the element has changed

As you say, this can be accomplished with `onDidChangeTreeData`. For now, this is by design. We will revisit as part of the finalization process. 

> do we need indeterminate state for the checkbox?

We have discussed this, and it would be nice to have. However, the major use cases we have seen so far for the checkbox can live without it. We will revisit during finalization, but I think the outcome will be that we should have only 2 states for now and make sure the API is designed in such a way that if we want to add a third state later we can.

**Comment by alexr00** [comment]
Starting tomorrow, child and parent checkbox state will be managed by VS Code by default. This can be overridden:

https://github.com/microsoft/vscode/blob/44fc3dbcc7baac4c57b5129b9248edd6d125bc0d/src/vscode-dts/vscode.proposed.treeItemCheckbox.d.ts#L47-L57

We also have a new `accessibilityInformation`: 

https://github.com/microsoft/vscode/blob/44fc3dbcc7baac4c57b5129b9248edd6d125bc0d/src/vscode-dts/vscode.proposed.treeItemCheckbox.d.ts#L8-L14

**Comment by Eskibear** [comment]
@alexr00 I still can produce it. 

`Latest Insiders, Commit: f6be5461f8bc69013a605f5baea834651c6589fb`

<img width="326" alt="image" src="https://github.com/microsoft/vscode/assets/2351748/6d923e90-2410-40ae-8339-aec392d05927">

I made some changes, and expect all items ending with "a" to have a checked box, and otherwise **an unchecked box**. See item "ab", "b" and "bb". 

Code change based on the sample.
https://github.com/microsoft/vscode-extension-samples/compare/main...Eskibear:vscode-extension-samples:checkbox?expand=1#diff-c9867a60c64266b038de2193e5a755121ab3e04c2597c19a1cee9ba77ed3a0d4R82

**Comment by alexr00** [comment]
Thanks for the example @Eskibear! I was using the ` readonly state: TreeItemCheckboxState; readonly tooltip?: string;}` type for `checkboxState`, which is why I failed to repro.
