### ISSUE TITLE
Not posible disable output console focus.

### ISSUE THREAD

**Issue by DaniloOC** [microsoft/vscode#116107]
Issue Type: <b>Bug</b>

Always wich have a new log in output tab the focus change for him, is not possible work this way, 
it would be interesting to have a button to disable this behavior as it exists in the eclipse IDE.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.98GB free)|
|Process Argv|G:\\Meu Drive\\referencias\\. --crash-reporter-id 1d9e94d7-e2c8-4ef4-8420-6a91b4e28ca2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
angular-material|1to|0.13.0
vscode-angular2-files|ale|1.6.4
vscode-eclipse-keybindings|alp|0.12.0
ng-template|Ang|11.1.3
simple-react-snippets|bur|1.2.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
angular-schematics|cyr|4.9.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
prettier-vscode|esb|5.9.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
gc-excelviewer|Gra|3.0.41
angular2-switcher|inf|0.3.3
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
angular-extension-pack|loi|0.9.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
sqltools|mtx|0.23.0
angular-console|nrw|16.0.2
arrr|obe|0.1.3
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.24.0
vscode-manifest-yaml|Piv|1.24.0
vscode-spring-boot|Piv|1.24.0
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
karma-problem-matcher|rct|1.0.1
java|red|0.74.0
vscode-rsp-ui|red|0.23.5
vscode-server-connector|red|0.23.6
vscode-xml|red|0.15.0
simontest|Sim|1.9.7
sonarlint-vscode|Son|1.20.1
autoimport|ste|1.5.3
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by DaniloOC** [comment]
Eclipse example: 
![image](https://user-images.githubusercontent.com/9569708/107268808-725e8d00-6a27-11eb-809a-c1497a9872bc.png)

**Comment by sandy081** [comment]
Not sure if I understand the request... May I know how the focus is changing? Can you please provide a video of what you see and explain what you expect?

**Comment by DaniloOC** [comment]
Video with what happens:
[output-change-focus (2).zip](https://github.com/microsoft/vscode/files/5952927/output-change-focus.2.zip)

 I open the issue as a bug but I think it should be a feature request?

**Comment by sandy081** [comment]
Seems to be issue with the extension logging into the output channel - Please file issue against the extension not to steal the focus
