### ISSUE TITLE
Smoketest: search replace first result with a replace term times out

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#116153]
Running the smoketests on Linux, this test seems to consistently time out. Actually searching and replacing works fine

**Comment by JacksonKearl** [comment]
Related https://github.com/microsoft/vscode/issues/115244

**Comment by JacksonKearl** [comment]
Should be fixed by 8a3a5d9b74723c4167d8415ae6228997c80fb108

**Comment by roblourens** [comment]
This was just removed - https://github.com/microsoft/vscode/issues/115586
