### ISSUE TITLE
PHP (built-in): Incorrect syntax highlighting for `interface extends`

### ISSUE THREAD

**Issue by Kroc** [microsoft/vscode#116103]
Related to #113185

PHP allows for Interfaces to be extended. The interface name provided is not recognised / coloured correctly.

![image](https://user-images.githubusercontent.com/142650/107221779-ff93e880-6a0b-11eb-828e-c2ecb7786b95.png)

**Comment by roblourens** [comment]
Filed https://github.com/atom/language-php/issues/414

**Comment by KapitanOczywisty** [comment]
@roblourens Merged upstream :)

**Comment by roblourens** [comment]
Thanks!
