### ISSUE TITLE
Terminal is not integrated while it says it is.

### ISSUE THREAD

**Issue by liperium** [microsoft/vscode#116139]
![image](https://user-images.githubusercontent.com/48138387/107270513-0b39dc00-6a19-11eb-804f-3f3519f0ffca.png)
![image](https://user-images.githubusercontent.com/48138387/107270557-1a208e80-6a19-11eb-80bc-c2a7743e66e2.png)

**Comment by meganrogge** [comment]
can you attach a [gif](https://gifcap.dev/) of what happens when you click new terminal in the menu with this setting?

**Comment by liperium** [comment]
![Example](https://user-images.githubusercontent.com/48138387/107275006-34f60180-6a1f-11eb-9d6c-ed52720c9c9e.gif)

**Comment by meganrogge** [comment]
What do you have `terminal.integrated.cwd` set to?

**Comment by meganrogge** [comment]
Also, pls see read this:
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch
