### ISSUE TITLE
Integrated terminal multiple tab issue

### ISSUE THREAD

**Issue by nomadoda** [microsoft/vscode#116184]
Issue Type: <b>Bug</b>

**Reproduce:**
1. Open integrated terminal
![image](https://user-images.githubusercontent.com/25898698/107356346-fae53800-6ad0-11eb-8533-3b2bf9d99b43.png)

2. Open new terminal tab
![image](https://user-images.githubusercontent.com/25898698/107356365-02a4dc80-6ad1-11eb-8cd8-92fee0baf8d6.png)

3. Close terminal tab

**Expected result:**
First tab should be active:
![image](https://user-images.githubusercontent.com/25898698/107356346-fae53800-6ad0-11eb-8533-3b2bf9d99b43.png)

**Actual result:**
First tab is not active? Looks like a funny state.
![image](https://user-images.githubusercontent.com/25898698/107356320-f15bd000-6ad0-11eb-8b85-cbec2ee833e3.png)

VS Code version: Code - Insiders 1.54.0-insider (52838cf6799cc448e738677ec37e86cf62a5bd89, 2021-02-05T05:17:08.594Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id d11e044b-3b44-4681-a930-eb0e8d2783df|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by meganrogge** [comment]
I'm not able to reproduce this issue. Can you try selecting a different default shell and seeing if that makes a difference?

![recording (21)](https://user-images.githubusercontent.com/29464607/107387093-58fe2500-6aa9-11eb-9a4c-e2f740cd348d.gif)

**Comment by nomadoda** [comment]
Yes, I tried with zsh or bash and still encounter the same issue

**Comment by meganrogge** [comment]
are there any errors in dev tools?

**Comment by nomadoda** [comment]
No errors, however it seems now the issue has been resolved after restarting! Thank you!
