### ISSUE TITLE
Allow us to configure EDITOR_MIN_DIMENSIONS

### ISSUE THREAD

**Issue by ColCh** [microsoft/vscode#116133]
Speaking about this https://github.com/microsoft/vscode/blob/776541c380657f8e1bf9f4acc459a33d84f755bd/src/vs/workbench/browser/parts/editor/editor.ts#L23

220px is a very large size for "minimal" tab 

I code on 24'' screen (with zoom), and 220px are about a few centimetres on my screen.

Also, current value of 220px not allows to code with 3 editor groups and 1 maximized

Just look at this example, there are 4 editor groups, and 1 is maximized.

<details>
<summary>Self-modified JS file</summary>
<img src="https://user-images.githubusercontent.com/599439/107254775-b0b87400-6a48-11eb-97c9-55d4a0462945.png" />
</details>

<details>
<summary>How I did that?</summary>
Just modified my vscode js bundle `workbench.desktop.main.js`
<img src="https://user-images.githubusercontent.com/599439/107255214-202e6380-6a49-11eb-8deb-12e9db615074.png" />
</details>

Pressing CMD+1, CMD+2 and other numbers would show corresponding group.

**Comment by sbatten** [comment]
this is specifically editor part dimensions
