### ISSUE TITLE
arm32 build of vs code on windows

### ISSUE THREAD

**Issue by jaymin93** [microsoft/vscode#116115]
I want to run vs code on arm32 device which I have running windows10 , currently vs code supports arm64 not arm32 , I would like support for arm32 device as well .

or any documentation how to port vs code to arm32 windows , I know some Linux variants are available for arm 32 but inam looking for windows arm 32 at the moment not Linux one

thnaks

**Comment by joaomoreno** [comment]
@jaymin93 What device is this?

**Comment by jaymin93** [comment]
Surface 1, surface 2, vivo tab all runs windows 10 arm32, I have surface 2 running windows 10 arm32 and looking for the vs code support for it

**Comment by joaomoreno** [comment]
Got it. Sadly, I don't think this will ever happen, since it's just not an architecture in mass use out there.
