### ISSUE TITLE
operating problem

### ISSUE THREAD

**Issue by stephenmandeya** [microsoft/vscode#116138]
Issue Type: <b>Performance Issue</b>

its opening multi-windows therefore its become unresponsive

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

**Comment by meganrogge** [comment]
please provide more details and a [gif](https://gifcap.dev/) of this happening.

**Comment by deepak1556** [comment]
Does the issue happen when you start with `--disable-features=CalculateNativeWinOcclusion` ?
