### ISSUE TITLE
After update emment wont work with stylus correctly

### ISSUE THREAD

**Issue by Venegrad** [microsoft/vscode#116151]
1. 1.53.0
2. Windows 10

After updating vscode to 1.53.0 In stylus Emmet wont work correctly, he add ";", ":", in stylus, and not parsing mixins.

![image](https://user-images.githubusercontent.com/9676703/107297459-12460600-6a7c-11eb-8548-4b47c48d3e32.png)

**Comment by Venegrad** [comment]
![image](https://user-images.githubusercontent.com/9676703/107297486-1ffb8b80-6a7c-11eb-8a79-881dbbaed219.png)

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/115839
Please try with VS Code Insiders: https://code.visualstudio.com/insiders/
