### ISSUE TITLE
Configuration option for pre-tab behavior

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#11612]
I had gotten used to and now prefer the pre-tab behavior... 

I'm able to get close with the following options:

    "workbench.editor.showTabs": false,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,

However, there's still the `LEFT | CENTER | RIGHT` sections in the file list, instead of a unified list... I'd really love to get the old, behavior back completely.  I don't mind setting config options so much.

I can't be the only one that really doesn't like all the tabs that become hard to read anyway.

**Comment by ramya-rao-a** [comment]
@tracker1  #9097 talks about restoring non-tabs behavior. Other than that and the `LEFT | CENTER | RIGHT` sections, is there anything else specifically you are looking to restore?

**Comment by bpasero** [comment]
https://code.visualstudio.com/docs/editor/tabs#_working-without-tabs
