### ISSUE TITLE
Custom hover is often in my way and has minimal contrast

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116197]
I am getting a bit frustrated with how the custom hover decides to put itself over data I look at:

![image](https://user-images.githubusercontent.com/900690/107371995-37229380-6ae5-11eb-87f3-d0ee895ed2b7.png)

Some ideas:
* do not show the hover when I click on a tree item, e.g. consider this as an action that I want to see what is below the item and not see a hover there
* improve the contrast of the hover so that it sticks out more from the underlying content

//cc @misolori

**Comment by Tyriar** [comment]
👍 to hiding on click

**Comment by bpasero** [comment]
I would also suggest to mimic what OS'es do in these cases, maybe there are more cases we need to check, like e.g. scrolling over a tree should probably also hide it. Basically any interaction other than hovering.

**Comment by alexr00** [comment]
I pushed a fix to hid the hover on click. I already see scroll hide the hover appropriately. @bpasero do you see the hover persist even when scrolling?

**Comment by bpasero** [comment]
No, I was just thinking out loud.

**Comment by misolori** [comment]
For increasing contrast, we could apply the shadow we use in other overlays:

![image](https://user-images.githubusercontent.com/35271042/107393807-0d02ae80-6ab0-11eb-8f68-0cdf73ca0fd9.png)

**Comment by bpasero** [comment]
Yeah I like that, why are we not using a `box-shadow` for hovers @Tyriar

**Comment by Tyriar** [comment]
It's kept the same style as in the editor, I'm not opposed to this though.

**Comment by Tyriar** [comment]
Need to add proper light theme support here still

**Comment by misolori** [comment]
@Tyriar shouldn't we use `widget.shadow` here?

**Comment by Tyriar** [comment]
Fixed, here's what it looks like:

<img width="445" alt="Screen Shot 2021-03-19 at 6 36 28 AM" src="https://user-images.githubusercontent.com/2193314/111788645-8d6db980-887d-11eb-83ba-fad499f6fbe0.png">
<img width="374" alt="Screen Shot 2021-03-19 at 6 36 39 AM" src="https://user-images.githubusercontent.com/2193314/111788655-8f377d00-887d-11eb-9153-bd438131d76d.png">
<img width="331" alt="Screen Shot 2021-03-19 at 6 36 44 AM" src="https://user-images.githubusercontent.com/2193314/111788666-92326d80-887d-11eb-9ef9-1a86afe38cf8.png">
<img width="215" alt="Screen Shot 2021-03-19 at 6 37 01 AM" src="https://user-images.githubusercontent.com/2193314/111788679-9494c780-887d-11eb-927f-061a726f7846.png">

**Comment by bpasero** [comment]
Very very nice 👍
