### ISSUE TITLE
Entering (, {, etc while editing a .c file automatically inserts a ")" or "}" without user input

### ISSUE THREAD

**Issue by trollcop** [Microsoft/vscode#11617]
- VSCode Version: latest
- OS Version: windows 10

Steps to Reproduce:

1. open anyfile.c
2. int main(|< now here, after pressing ( it will immediately add a ")".

**Comment by yaSebastian** [comment]
This behavior is intended. You can switch it off.
Set the following to false:
```JSON
    // Controls if the editor should automatically close brackets after opening them
    "editor.autoClosingBrackets": true,
```

You can find a detailed instruction on how to do this [here](https://code.visualstudio.com/docs/customization/userandworkspace).

**Comment by trollcop** [comment]
That works.
I have no idea why such misfeature would be on by default.
Thanks.
