### ISSUE TITLE
[JS] IntelliSense disregards properties if defined via Revealing Prototype Pattern

### ISSUE THREAD

**Issue by odonyde** [Microsoft/vscode#11610]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Pro 64bit 1607
- Language: JavaScript

Likewise issue #11450 concerning the Prototype Pattern with assigned object literal, I observed that IntelliSense also disregards any properties if they are defined using the Revealing Prototype Pattern. For example, IntelliSense does not show property 'greet' in the screenshot below.
![vscode-intellisense-03](https://cloud.githubusercontent.com/assets/21695902/18296719/0c60c918-7482-11e6-9736-393a5d8a6134.jpg)

**Comment by waderyan** [comment]
Hey @odonyde thank you for opening these issues! As this falls onto TypeScript language service, I am moving it there.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10794
