### ISSUE TITLE
这个程序不支持该版本的计算机运行

### ISSUE THREAD

**Issue by YogurtCat2020** [microsoft/vscode#116187]
在win7系统上用vscode，经常弹出“这个程序不支持该版本的计算机运行”的提示框，挺烦人的。。

**Comment by vilic** [comment]
> 标题里的内容对应了 InnoSetup 中的 WindowsVersionNotSupported，估计可以姑且翻译为 Windows version not supported。

Windows version not supported

Using VSCode on Windows 7, frequently get this prompt "Windows version not supported", pretty annoying.

**Comment by joaomoreno** [comment]
Can you share a screenshot of the error?
