### ISSUE TITLE
GIT not working. No errors shown in GIT console

### ISSUE THREAD

**Issue by ferarias** [Microsoft/vscode#11618]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586
- GIT version 2.9.3

Steps to Reproduce:

1.Open any solution with git association
2.GIT error happens. No error is shown in output.

Tried reinstalling GIT, reinstalling VS Code. Same problem.

![2016-09-07 09h18_11](https://cloud.githubusercontent.com/assets/5538461/18303481/94cdffd6-74dd-11e6-93df-3b62803252b2.gif)

**Comment by ferarias** [comment]
This is what I see in Console:

``
messageService.ts:119 There was an issue running a git operation. Please review the output or use a console to check the state of your repository.: Error: There was an issue running a git operation. Please review the output or use a console to check the state of your repository.
    at Object.C [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:34:19570)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:89:526
    at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:8153)
    at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:11658)
    at i.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:12979)
    at i.Class.define._chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:12338)
    at i (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:10161)
    at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:8153)
    at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:11658)
    at i.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:12979)
```

**Comment by ferarias** [comment]
I tried installing VSCode Insiders.
When I try to init repo, I get the following output:

> git init
> C:/Program Files (x86)/Microsoft VS Code Insiders/.git: Permission denied
> git config --get commit.template

**Comment by Sloff** [comment]
I'm also experiencing this issue

**Comment by ramya-rao-a** [comment]
@ferarias Can you run git commands successfully on your external `git bash` or the `integrated terminal` in VS Code ? What version of git are you using?

**Comment by joaomoreno** [comment]
Why do you seem to be trying to initialise a repository in `C:/Program Files (x86)/Microsoft VS Code Insiders`?

```
git init
C:/Program Files (x86)/Microsoft VS Code Insiders/.git: Permission denied
git config --get commit.template
```

**Comment by Sloff** [comment]
Downgrading from git 2.10 to 2.9.3 resolved the issue for me

**Comment by joaomoreno** [comment]
I'll give 2.10 a try.

**Comment by ferarias** [comment]
In console I can run commands as usual:

```
git fetch --verbose
From https://toolfactory.visualstudio.com/DefaultCollection/Logitravel/_git/ApplicationBase
 = [up to date]      master     -> origin/master
```

**Comment by ferarias** [comment]
Reinstalled git 2.9.3. Same problem...

**Comment by ferarias** [comment]
Upgraded VS Code. Same error.

> /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:93 There was an issue running a git operation. Please review the output or use a console to check the state of your repository.: Error: There was an issue running a git operation. Please review the output or use a console to check the state of your repository.
>     at Object._ [as create] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:34:29245)
>     at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:93:7819
>     at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:13448)
>     at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:16953)
>     at n.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:18274)
>     at n.Class.define._chainedError (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:17633)
>     at n (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:15456)
>     at Object.m [as _notify] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:13448)
>     at Object.B.enter (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:16953)
>     at n.Class.define._run (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:30:18274)e.doShow @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:93

**Comment by ferarias** [comment]
How could I inspect git output? Maybe with Sysinternals or similar?

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18379598/a754c256-7673-11e6-8b20-ea8638491821.png)

**Comment by ferarias** [comment]
I did not explain correctly: I meant if there is a way to capture the GIT output that VSCode was unable to capture, since it appears blank.

**Comment by ferarias** [comment]
For the record, I installed https://git-for-windows.github.io/ also to no avail...

**Comment by ferarias** [comment]
i think I give up on VS Code w/GIT. Updated Windows 10, reinstalled VS Code and GIT several times. Nothing works for me. It's frustrating.

**Comment by joaomoreno** [comment]
@ferarias Where did you install git from? In which folder is it installed?

**Comment by ferarias** [comment]
https://git-scm.com/download/win
C:\Program Files\Git

**Comment by ferarias** [comment]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393
- GIT: git version 2.10.0.windows.1

**Comment by joaomoreno** [comment]
Can you try starting code with `code --verbose` and see whether you get any output there?

**Comment by ferarias** [comment]
```
C:\Users\fernando.arias>code --verbose

(10:49:29) ### VSCode main.js ###
(10:49:29) c:\Program Files (x86)\Microsoft VS Code\resources\app { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  locale: undefined,
  wait: false }
(10:49:30) IPC#vscode:startCrashReporter
(10:49:30) IPC#vscode-workbenchLoaded
(10:49:52) Lifecycle#unload() 1
(10:49:53) IPC#vscode:startCrashReporter
(10:49:53) IPC#vscode-workbenchLoaded

```

**Comment by joaomoreno** [comment]
Leaving that running, if you open a git folder, you see no output in that window?

**Comment by ferarias** [comment]
Nothing at all

**Comment by joaomoreno** [comment]
Is there no other errors in the Developer Tools of the window? Can you take a screenshot?

**Comment by ferarias** [comment]
![image](https://cloud.githubusercontent.com/assets/5538461/18506237/546fa12c-7a6b-11e6-9d44-e434724d412f.png)

**Comment by ferarias** [comment]
Strange thing is, when trying to open Code after installing from scratch, it looks like it's trying to modify .git folder into "program files" and fails. If I run with Admin privileges, it continues but says my solution folder is not initialized for git. 
When I try to init, it fails, also.

![image](https://cloud.githubusercontent.com/assets/5538461/18506329/cc0a770c-7a6b-11e6-94a3-05ebdf1a3499.png)

**Comment by joaomoreno** [comment]
Why do you say this?

> modify .git folder into "program files"

Are you trying to open a folder inside `Program Files`? Do you have a `.git` folder in there?

**Comment by ferarias** [comment]
Nope, I just start Code, open a folder and then try to run a GIT operation. When starting as normal user, I get an error. When starting as an admin, it continues but says my solution folder is not initialized for git. 
Furthermore, I see the VS Code folder has been git-initialized
C:\Program Files (x86)\Microsoft VS Code
![image](https://cloud.githubusercontent.com/assets/5538461/18516659/1b5be8bc-7a9a-11e6-9a3b-70e45ab6179c.png)

**Comment by joaomoreno** [comment]
Can you delete that `.git` folder and see whether you still get the error and/or whether the folder comes back?

**Comment by ferarias** [comment]
If I delete the folder and start Code, I get this:
![image](https://cloud.githubusercontent.com/assets/5538461/18518400/1996d806-7aa0-11e6-9523-81c5067ee89c.png)

If I click, then I get
There was an issue running a git operation. Please review the output or use a console to check

**Comment by joaomoreno** [comment]
Using something like [Process Hacker](http://processhacker.sourceforge.net/) can you look for a Code.exe process that contains the word `git` in it and show me the full command line it was launched with?

**Comment by ferarias** [comment]
> "C:\Program Files (x86)\Microsoft VS Code\Code.exe" "c:\Program Files (x86)\Microsoft VS Code\resources\app\out\bootstrap" "C:\Program Files\Git\cmd\git.exe" f:\ExternalRepos\vsts-tasks utf8 "C:\Program Files (x86)\Microsoft VS Code\Code.exe" 2.10.0.windows.1

**Comment by joaomoreno** [comment]
Does it work if you edit a repository in `C:`?

**Comment by ferarias** [comment]
No. Same error.

```
git init
C:/Program Files (x86)/Microsoft VS Code/.git: Permission denied
git config --get commit.template
```

**Comment by joaomoreno** [comment]
Can you [build and run from source](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source), and see whether it reproduces there?

This is quite a mystery...

**Comment by ferarias** [comment]
I think I'm unable to build from sources. Are there any instructions or troubleshooting page?

**Comment by joaomoreno** [comment]
What errors do you see?

**Comment by ferarias** [comment]
> > cd server && npm install
> 
> npm WARN vscode-css-languageserver@1.0.0 No repository field.
> npm WARN css@0.1.0 No description
> npm WARN css@0.1.0 No repository field.
> npm WARN css@0.1.0 No license field.
> 
> > html@0.1.0 postinstall F:\Repos\GitHub\vscode\extensions\html
> > cd server && npm install
> 
> npm WARN vscode-html-languageserver@1.0.0 No repository field.
> npm WARN html@0.1.0 No description
> npm WARN html@0.1.0 No repository field.
> npm WARN html@0.1.0 No license field.
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN Command failed: git -c core.longpaths=true clone --template=C:\Users\fernando.arias\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:bpasero/fsevents.git C:\Users\fernando.arias\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bpasero-fsevents-git-vscode-fa25bc6e
> npm WARN Cloning into bare repository 'C:\Users\fernando.arias\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bpasero-fsevents-git-vscode-fa25bc6e'...
> npm WARN Host key verification failed.
> npm WARN fatal: Could not read from remote repository.
> npm WARN
> npm WARN Please make sure you have the correct access rights
> npm WARN and the repository exists.
> npm WARN

**Comment by ferarias** [comment]
```
F:\Repos\GitHub\vscode>.\scripts\code.bat

[11552:0919/134211:INFO:CONSOLE(136)] "Loading "gc-signals" failed", source: file:///F:/Repos/GitHub/vscode/out/vs/loader.js (136)
[11552:0919/134211:INFO:CONSOLE(137)] "Detail: ", source: file:///F:/Repos/GitHub/vscode/out/vs/loader.js (137)
[11552:0919/134211:INFO:CONSOLE(139)] "Error: Cannot find module '../build/Release/gcsignals'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (F:\Repos\GitHub\vscode\.build\electron\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Repos\GitHub\vscode\node_modules\gc-signals\src\index.js:8:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)", source: file:///F:/Repos/GitHub/vscode/out/vs/loader.js (139)
[11552:0919/134211:INFO:CONSOLE(141)] "Here are the modules that depend on it:", source: file:///F:/Repos/GitHub/vscode/out/vs/loader.js (141)
[11552:0919/134211:INFO:CONSOLE(142)] "vs/workbench/api/node/mainThreadLanguageFeatures,vs/workbench/api/node/mainThreadHeapService", source: file:///F:/Repos/GitHub/vscode/out/vs/loader.js (142)

```

**Comment by joaomoreno** [comment]
Can you `git pull`, `git clean -xfd node_modules` and try again?

**Comment by ferarias** [comment]
No way, I'm desperate!
I guess something is definitely wrong with my git

`C:\repos\GitHub\vscode>scripts\npm install`

> npm ERR! git submodule -q update --init --recursive: Unable to determine absolute path of git directory
> npm ERR! git submodule -q update --init --recursive:
> npm ERR! git submodule -q update --init --recursive: Unable to determine absolute path of git directory
> npm ERR! git submodule -q update --init --recursive:
> npm ERR! git submodule -q update --init --recursive: Unable to determine absolute path of git directory
> npm ERR! git submodule -q update --init --recursive:
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fernando.arias\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.7
> npm ERR! code 1
> 
> npm ERR! Command failed: git -c core.longpaths=true submodule -q update --init --recursive
> npm ERR! Unable to determine absolute path of git directory
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\repos\GitHub\vscode\npm-debug.log

**Comment by ferarias** [comment]
Just in case it helps, I'm attaching npm-debug.log

[npm-debug.txt](https://github.com/Microsoft/vscode/files/482176/npm-debug.txt)

**Comment by joaomoreno** [comment]
Outside of Code, try creating a git repository in a new folder:

```
cd Desktop
mkdir repo
cd repo
git init
echo hello > world.txt
git add world.txt
git commit -m "first commit"
git status
```

Does all of this work?

**Comment by joaomoreno** [comment]
@ferarias ping

**Comment by ferarias** [comment]
Yes, it works

> C:\Users\fernando.arias>cd Desktop
> 
> C:\Users\fernando.arias\Desktop>mkdir repo
> 
> C:\Users\fernando.arias\Desktop>cd repo
> 
> C:\Users\fernando.arias\Desktop\repo>git init
> Initialized empty Git repository in C:/Users/fernando.arias/Desktop/repo/.git/
> 
> C:\Users\fernando.arias\Desktop\repo>echo hello > world.txt
> 
> C:\Users\fernando.arias\Desktop\repo>git add world.txt
> 
> C:\Users\fernando.arias\Desktop\repo>git commit -m "first commit"
> [master (root-commit) 718faf9] first commit
>  1 file changed, 1 insertion(+)
>  create mode 100644 world.txt
> 
> C:\Users\fernando.arias\Desktop\repo>git status
> On branch master
> nothing to commit, working tree clean

**Comment by ferarias** [comment]
I guess something's wrong in my computer regarding GIT, or console, antivirus, windows policies, .... not to do with Code, really, just the tip of the iceberg

**Comment by joaomoreno** [comment]
I have to agree... I can't find anything wrong with Code itself here... I'll close it, but keep it in the back of my head. Let me know if you eventually find the issue.

**Comment by sandy081** [comment]
Removed the bug tag until we know that this is a bug

**Comment by ChrisW123** [comment]
I'm having the same issue...  Did anyone find a solution at all for this?
