### ISSUE TITLE
Update All Extensions Feature

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#11614]
Very simple (I think..)  - a button that updates all the extensions that are outdated..

**Comment by LevanArabuli** [comment]
👍

**Comment by mrmlnc** [comment]
In version `1.5.0` you can use 

![image](https://cloud.githubusercontent.com/assets/7034281/18307278/67f0850e-74f8-11e6-8359-73fcd87444ea.png)

**Comment by ramya-rao-a** [comment]
`1.5.0` will be releasing in a day or 2.
