### ISSUE TITLE
VSCode becomes unresponsive after pasting filename with many dots in file tree

### ISSUE THREAD

**Issue by JornHoofwijk** [microsoft/vscode#116199]
- VSCode Version: 1.53.0 (commit id: 8490d3dde47c57)
- OS Version: Ubuntu 20.04.2 LTS (Kernel: Linux 5.4.0-65-generic)

I stumbled upon this bug by accident when I had the contents of some large file in my clipboard and (not realizing I had these file contents in the clipboard) when I pasted it in the filename of the file explorer of VSCode, it became unresponsive to the point I had to force kill it. In my opinion it is not very critical, not many people with encounter this issue, it was just surprising that my vscode became unresponsive due to this. I tried to locate the source of the issue in the code, but I couldn't find it myself.

Steps to Reproduce:

1. open a directory in VSCode such that you have some file existing in the Explorer
2. copy some filename with many dots to the clipboard. I use ```python -c "print('a.' * 50000)" | xclip -sel clip``` for this
2. select the file and click rename `F2`, followed by `CTRL-V` to paste the string
3. observe vscode is unresponsive for more than 30 seconds, after which I force kill it. 
 
I found out that when you would paste 100.000 characters without using dots (i.e. `python -c "print('ab' * 50000)" | xclip -sel clip`), then VSCode responds very quickly and lets me know the filename is invalid.

Since the maximum allowed length of a filename is 255 characters, I think it would suffice to limit the filename to 255 characters **before** any further parsing is done.  

Does this issue occur when all extensions are disabled?: **Yes** / ~~no~~

**Comment by jrieken** [comment]
I can reproduce. Looks like the [getIconClasses](https://github.com/microsoft/vscode/blob/23579d815faa6712bf7c628bad25d4a4eb4a2dbc/src/vs/editor/common/services/getIconClasses.ts#L14-L14)-function is causing this

<img width="734" alt="Screenshot 2021-02-09 at 16 17 22" src="https://user-images.githubusercontent.com/1794099/107384472-4d831c00-6af2-11eb-8cdb-3d3a2ef1d310.png">

**Comment by jrieken** [comment]
my "fill clipboard snippet" is this `setTimeout(() => navigator.clipboard.writeText(new Array(50000).fill('a').join('.')), 3000)`. Open dev-tools, paste and run, and within the 3sec focus the content window

**Comment by bpasero** [comment]
Since it happens inside the method, like something that was added around here: https://github.com/microsoft/vscode/commit/a84b27289265c87435e933d0b2dbfb9ed2b8f5a4

**Comment by jeanp413** [comment]
I'll take a look at this

**Comment by jrieken** [comment]
Still quite slow but not freezing anymore
