### ISSUE TITLE
DEBUG CONSOLE 's filter prevents expanding objects

### ISSUE THREAD

**Issue by MehdizadeMilad** [microsoft/vscode#116155]
- VSCode Version: 1.53.0
- VSCODE Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.12-200.fc33.x86_64 - Fedora 

I'm developing in Node.JS; while Debugging, in DEBUG CONSOLE after filtering, the output which are some javascript objects with nested children, are not expanded at all;
I think the output's nested objects should not be filtered.

Steps to Reproduce:

Source code in js:
`console.log({ id: 1, link: { id: 2, link: { id: 3, link: null } } });`
`console.log('... 50 more for example...');`
`console.log({ id: 4, link: { id: 5, link: { id: 6, link: null } } });`

without any filter, the output in DEBUG CONSOLE is as the following image:

![image](https://user-images.githubusercontent.com/44354927/107297972-b1252f00-6a89-11eb-9eb1-046239ba81a5.png)

Now the first object is expanded all the way down to the last child:
![image](https://user-images.githubusercontent.com/44354927/107298032-da45bf80-6a89-11eb-8f70-93dd73e87c88.png)

Assume If I write _1_ in the filter box, the output would be filtered like the following image:
![image](https://user-images.githubusercontent.com/44354927/107298112-fea19c00-6a89-11eb-93f2-f40d10ed2a2d.png)

but object's children are filtered too! 
What I expect is that the output should not filter child nodes!

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@MehdizadeMilad good catch, thanks for letting us know. From tomorrow you can try the fix in vscode insiders and let us know if it is now good for you.

**Comment by MehdizadeMilad** [comment]
I've downloaded new release (40b3204d70a9c72305c613164272175d0b344b5f) and checked it out.

with the same output, filtering for _**1**_, _**4**_ and _**hello**_ seems not working properly, as you can see in the following screenshots:

Unfiltered output:
![image](https://user-images.githubusercontent.com/44354927/107585943-4eac6a00-6c14-11eb-96d9-993083a5bba4.png)

_**1**_:
![image](https://user-images.githubusercontent.com/44354927/107585206-0b9dc700-6c13-11eb-9b34-2ca3ee86b71a.png)

_**4**_:
![image](https://user-images.githubusercontent.com/44354927/107585310-3daf2900-6c13-11eb-8cfa-e02b392f8d6a.png)

and _**hello**_:
![image](https://user-images.githubusercontent.com/44354927/107585753-05f4b100-6c14-11eb-993f-714412a1fc56.png)



Thank you for your efforts

**Comment by isidorn** [comment]
The screen shot looks good to me.
You have not expanded the objects in the first two screenshoots...
So I think this works fine. Can you please expand them or clarify if I am missing something here.

**Comment by MehdizadeMilad** [comment]
the original output before any filtering:
![image](https://user-images.githubusercontent.com/44354927/107783615-b7ecc400-6d5f-11eb-8314-62b92e7aeeee.png)

I think _Debug Console_'s output, after filtering for _**Milad**_ text (for example), must be empty.
but, it is showing 2 of 4 items and non of them contains _**Milad**_ text!

![image](https://user-images.githubusercontent.com/44354927/107783739-d488fc00-6d5f-11eb-8ae3-a97eda74d044.png)

and expanded:
![image](https://user-images.githubusercontent.com/44354927/107782811-bff83400-6d5e-11eb-97c6-c048d755d5d2.png)

another example with more clear output that shows, filtering is not working properly if Debug Console contains **Objects**:
![image](https://user-images.githubusercontent.com/44354927/107784424-ace66380-6d60-11eb-8637-14603e255f84.png)

**Comment by isidorn** [comment]
Nah this is expected. Filter is only applied on text, not on objects.
If we get more user feedback that this behavior is unexpected I would be open to change it. For now no change.

**Comment by MehdizadeMilad** [comment]
All alright, thank you for your time, and it was nice to participate in the Open source community
