### ISSUE TITLE
Sentence conversion display is not displayed when inputting with Japanese IME.

### ISSUE THREAD

**Issue by ishisaka** [microsoft/vscode#116169]
- VSCode Version: 1.53.0
- OS Version: Windows 10 1809 / 20H2

Steps to Reproduce:

1. Enables the Japanese IME.
2. Enter Japanese.
3. Change the paragraph break.
4. However, at that time, the IME input display does not follow the change of the paragraph break.

MS-IME, Google IME, and ATOK all have similar issues.

Does this issue occur when all extensions are disabled?: Yes

**Comment by ishisaka** [comment]
I think none of them apply.

**Comment by alexdima** [comment]
@ishisaka Could you please explain in a bit greater detail the precise keys you are pressing on the keyboard and what is expected to happen vs. what happens? I am looking for some very steps explained in great detail like the following example: https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese . This would allow me to troubleshoot what is going on, despite my lack of understanding of Japanese. Thank you!

**Comment by ishisaka** [comment]
Hi, ALL
 https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese

In the link above, there is an IME that doesn't display the underlined dots
that appear when converting from kana to kanji, and while this has been
improved in MS-IME, it doesn't appear in ATOK, an IME that is distributed
in Japan. However, the same thing that doesn't show up in ATOK also doesn't
show up in the Slack app, and from that, in my opinion, it's now an
Electron problem, not a VS Code problem.



==
石坂 忠広 ***@***.***>
***@***.***
http://www.isisaka.com/


2021年11月30日(火) 7:38 Alexandru Dima ***@***.***>:

**Comment by alexdima** [comment]
Thank you for your prompt reply. Given this appears to be an Electron / Chromium issue, I will close the issue here and kindly ask that you please report the problem upstream, either to Electron or Chromium. Thank you!
