### ISSUE TITLE
Leetcode 插件提交test代码出问题

### ISSUE THREAD

**Issue by Edanaw** [microsoft/vscode#116121]
Issue Type: <b>Bug</b>

- Downloading problems
[ERROR] session expired, please login again [code=-1]

vscode版本v1.53.0
node.js版本v12.18.3

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.01GB free)|
|Process Argv|--crash-reporter-id 729fd413-fdcb-4f2a-996c-5100d9cb811a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
snippets|221|0.1.38
Bookmarks|ale|12.1.4
vscode-custom-css|be5|4.0.1
cmake-format|che|0.6.11
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
vscode-pull-request-github|Git|0.23.0
todo-tree|Gru|0.0.196
google-translate|han|1.1.6
markdown-extended|jeb|1.0.18
better-cpp-syntax|jef|1.15.5
vscode-leetcode|Lee|0.17.0
sftp|lix|1.12.9
git-graph|mhu|1.28.0
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.2
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.5.3
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
synthwave-vscode|Rob|0.1.8
highlight-words|rsb|0.1.4
markdown-preview-enhanced|shd|0.5.16
python|tht|0.2.3
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Edanaw** [comment]
#Leetcode plugin issue

**Comment by Edanaw** [comment]
Leetcode plugin submit test issue

**Comment by vilic** [comment]
@Edanaw 这个你应该去 Leetcode 提 issue，跟 vscode 没有直接关系。可以关掉了。

**Comment by YalandHong** [comment]
Caused by extension.
https://github.com/LeetCode-OpenSource/vscode-leetcode
