### ISSUE TITLE
Build task won't work at times

### ISSUE THREAD

**Issue by jyotendra** [Microsoft/vscode#11613]
- VSCode Version: 1.4.0
- OS Version: Microsoft Windows [Version 10.0.14393]

Description:
Build task stops working every now and then. I am trying to run gulp task to launch a node.js server upon activation. It works when gulp is installed afresh but after a restart it won't work. 

Following is my tasks.json code:

`{
    // See http://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "args": [
        "--no-color"
    ],
    "tasks": [
        {
            "taskName": "server",
            "args": [],
            "isBuildCommand": true,
            "isWatching": false
        }
    ]
}`

It should have called the "server" task on building. But nothing happens. I have tried building by using "ctrl+shift+b" and also directly by pallet. While using pallet I noticed something interesting. When I click "run task" - it never actually find any task. Also, while trying to build, nothing shows up on "output" window.

One more thing, if I replace the command with any other thing than gulp, like "echo", "node" etc, it would then work like charm. Is there an issue with gulp only?

I tried running it directly from integrated command line and yes it worked there, using - 
`npm run gulp server`

Pardon me for not adhering to defined template of submitting issue - consider me complete novice. Just wanted to let you know of the issue :)

**Comment by dbaeumer** [comment]
@jyotendra can you share some code demonstrating the problematic behavior. Makes it a lot easier to find out what is not working.

**Comment by jyotendra** [comment]
@dbaeumer : thanks for taking notice of this.

Apart from the tasks.json file, I think the gulpfile.js is the only relevant one. So here it is:

```
var gulp = require("gulp");
var bs = require("browser-sync").create();
var exec = require("child_process").exec;

gulp.task("server",function(){
    exec('node app/server.js', function (err, stdout, stderr) {
    console.log(stdout);
    console.log(stderr);
    cb(err);
    });

    bs.init({
            proxy: "localhost:5000"
        });
});



gulp.task('browserSync', function() {
    bs.reload(true);
});

gulp.watch("./app/css/*.css", ["browserSync"] );
gulp.watch("./app/*.html", ["browserSync"] );
```

I shall also share the package.json code :

`{
  "name": "htmltemp",
  "version": "1.0.0",
  "description": "This is my initial project",
  "main": "index.js",
  "dependencies": {
    "babel-preset-react": "^6.11.1",
    "express": "^4.14.0",
    "gulp-webserver": "^0.9.1",
    "react-dom": "^15.3.1"
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ]
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2015": "^6.14.0",
    "browser-sync": "^2.14.3",
    "gulp": "^3.9.1",
    "gulp-sass": "^2.3.2",
    "gulp-webserver": "^0.9.1",
    "react": "^15.3.1",
    "webpack": "^1.13.2"
  },
  "scripts": {
    "start": "webpack --watch",
    "test": "console.log(\"hi\")",
    "babel": "babel",
    "gulp" : "gulp"
  },
  "author": "JS",
  "license": "ISC"
}
`

And finally that's tasks.json, shared again for brevity:

`{
    // See http://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "args": [
        "--no-color"
    ],
    "tasks": [
        {
            "taskName": "server",
            "args": [],
            "isBuildCommand": true,
            "isWatching": false
        }
    ]
}`

I suppose here is what happens under the hood:

The build task (using ctrl+shift+b) should initiate a "gulp" command and should trigger the task named: "server". The task "server" is defined in gulpfile.js, which in turn triggers the node server file stored by the name "server.js". _However this is not working_. 
I am adopting the same code as was mentioned [here.](https://code.visualstudio.com/docs/editor/tasks#_mapping-gulp-grunt-and-jake-output-to-problem-matchers)

While initiating the command directly from integrated terminal, with :
`npm run gulp server`
npm calls the "gulp" command defined in "package.json" and run the server task defined in "gulpfile.js". _Then it works fine_. This probably by-passed processing "tasks.json", and hence worked.

I think there is some problem with processing of "tasks.json". My understanding is that for some reason "gulp" is not being accepted as a command. To think of which, vs code was also not able to auto-detect gulp and create tasks.json file. Following were my steps:

1. I deleted the old tasks.json file, as it was no longer working.
2. Opened palate and did "configure task runner"
3. Then selected "gulp" - and it hanged on "Auto-detecting tasks for gulp".

Hope this helps. I really love "vs code" - please let me know if I can be of any more help.

**Comment by dbaeumer** [comment]
@jyotendra I understand the problem but don't yet know how to fix it. To get a good gulp integration we run gulp --tasks-simple to retrieve a list of gulp tasks defined by the gulp file. In your case this never returns. Gulp simply keeps running. I could short circuit this for Ctrl+Shift+B but other tasks features like F1 > Run Task would be broken as well.

**Comment by dbaeumer** [comment]
OK. The problem are these two line in the gulp file:

```js
gulp.watch("./app/css/*.css", ["browserSync"] );
gulp.watch("./app/*.html", ["browserSync"] );
```

I suggest to change the gulpfile like this

```js
gulp.task('watch', function() {
	gulp.watch("./app/css/*.css", ["browserSync"] );
	gulp.watch("./app/*.html", ["browserSync"] );
});
```

**Comment by dbaeumer** [comment]
I will close the issue since there is little VS Code can do to fix it. As said `gulp --tasks-simple`doesn't return either in this case.
