### ISSUE TITLE
Opening settings editor does not put focus into input box

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116167]
I think it always should focus the search box for me to find the setting.

It seems to me we restore the last setting that had focus. This makes sense to me if I did not close the editor, but after closing I think it should always focus back on the input field for searching.

**Comment by gjsjohnmurray** [comment]
@bpasero the title of this issue refers incorrectly to search editor.

**Comment by bpasero** [comment]
@gjsjohnmurray thanks! I need that second coffee now....

**Comment by roblourens** [comment]
Isn't it true that editors don't know whether they were "closed" or just put in the background?

**Comment by bpasero** [comment]
Yeah you bring up a good point, but on the other hand, I for example have tabs disabled and I typically do not close editors but I also do not see that the settings editor was opened or not. So from my point of view opening the settings editor, whether it was opened before or not, does not really make a visual difference. So it would be confusing for me at least to see different behaviour depending on whether the editor was closed or not.

Up to you, I feel this should probably be controlled through editor options: 
* if I just click on the editor tab to go back to the settings editor, restore all UI state
* if I hit the command to open settings (`Cmd+,`) focus the input box

**Comment by roblourens** [comment]
I agree, I just thought it wasn't possible. I think this context with `newInGroup` is new? Haven't seen it before, I will use that

**Comment by bpasero** [comment]
Awesome how this works now 👏

**Comment by bpasero** [comment]
@roblourens just one nit: when I am currently inside the settings editor and press `Cmd+,`, focus currently does not go back to the search. I think that would be a nice addition though because that means I can quickly operate the settings editor without mouse.

**Comment by roblourens** [comment]
Seems like this stopped working... I am trying to call openEditor with a custom EditorOptions subclass. But now seems like options are normalized to just EditorOptions. I don't see any relevant code that looks like it changed recently, do you know what happened?

**Comment by bpasero** [comment]
A recent regression: https://github.com/microsoft/vscode/issues/117952
