### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by RaxFord1** [microsoft/vscode#116127]
Visual Studio Code:
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. I dont know what led to this, but i installed some extensions and than it all started. 
2. AFK some time and UI starts bugging. I have to make VS Code an active window to start this.

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/30433545/107246431-e9e8e800-6a38-11eb-9af4-aadf8137ad6a.png)

**Comment by meganrogge** [comment]
Please run extension bisect (search in the command palette for it)  to figure out which extension is causing the issue and uninstall it

**Comment by RaxFord1** [comment]
I disabled all extensions with extension bisect and problem still occurs
