### ISSUE TITLE
z-index on error dialog when debugging is set behind the Visual Studio Code window

### ISSUE THREAD

**Issue by keithwanta** [microsoft/vscode#116140]
****
**- VSCode Version:** 1.52.1
**- OS Version:** Windows 10

**Steps to Reproduce:**

1. Make an Excel spreadsheet file with password "password123" and save to C:\files\files\file.xlsx (not C:\files\file.xlsx like the source code expects)

2. Create a new user environment variable.

Control Panel > System > Advanced system settings > Environment Variables > New (User variable) > Name: EXCEL_PASSWORD | Value: password123

3. Run this Python code in debug mode using this source code:

import os
import win32com.client
excel_password = os.environ['EXCEL_PASSWORD'] 
xl = win32com.client.Dispatch('Excel.Application')
filename = "C:\files\file.xlsx"
wb = xl.Workbooks.Open(filename, None, None, None, excel_password)

4.) Watch for an error dialog box pop up behind the Visual Studio IDE that says "Sorry, we couldn't find '{file full path}'. Is it possible it was moved, renamed or deleted?".  This is difficult to find.  And the debugger does nothing until you hit OK or close the dialog.

5.) Now this exception will occur in the IDE.  "Exception has occurred: com_error. (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel cannot access the file 'C:\files\file.xlsx'.  There are several possible reasons:\n\n.  The file name or path does not exist.\n  The file is being used by another program.\n  The workbook you are trying to save has the same name as a currently open workbook.", 'xlmain11.chm', 0, -2146827284), None)  File "C:\files\file.xlsx", line 7, in <module>
wb = xl.Workbooks.Open(filename, None, None, None, excel_password)

6.) Why do we even get a dialog, despite being behind the IDE?  Shouldn't we just get an exception?

**Does this issue occur when all extensions are disabled?: Yes/No**

I don't know.  I have the recommended Python extensions enabled.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/42356

> Why do we even get a dialog, despite being behind the IDE? Shouldn't we just get an exception?

We don't create this, I believe it's caused by the workbooks lib you're using
