### ISSUE TITLE
Installing `Hex Editor` extension fails with `Cannot read property 'name' of undefined`

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#116114]
Version: 1.54.0-insider
Commit: afd102cbd2e17305a510701d7fd963ec2528e4ea
Date: 2021-02-08T05:13:33.147Z
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-41-generic

- install the  `Hex Editor` extension. Error notification shows: `Cannot read property 'name' of undefined`

**Comment by aeschli** [comment]
![image](https://user-images.githubusercontent.com/6461412/107233473-efd3ce80-6a22-11eb-8dbc-e810bc8b73da.png)

![image](https://user-images.githubusercontent.com/6461412/107233821-46d9a380-6a23-11eb-8103-eab1442ee4e7.png)

**Comment by gjsjohnmurray** [comment]
Based on #116089 it looks like maybe all extension installing is broken in Insiders at the moment.

**Comment by sandy081** [comment]
/duplicate

Seems to be fixed with latest insiders - I suspect got fixed by this - https://github.com/microsoft/vscode/issues/116086
