### ISSUE TITLE
Integrated Terminal malfunctioning

### ISSUE THREAD

**Issue by SpiderMath** [microsoft/vscode#116161]
Version: VSCode-Insiders 1.54.0
OS: Windows 8.1

Here is a Run: https://user-images.githubusercontent.com/71999854/107309986-7f27c300-6ab1-11eb-8c0b-242c3a270cc3.mp4

Reproduction:
1. Open the Integrated Terminal
2. Run some command (like `node .` or something)
3. Close(aka "delete") the terminal using the wastebin icon

Results found:
The terminal does not close, instead it clears itself (like all the output is removed) and however many times I try to close it, it does not close and can still be used as is, I have tried uninstalling and reinstalling but does not seem to be getting fixed.

**Comment by AryanJ-NYC** [comment]
Is paste (ctrl+V) working for you in the Insiders version? It's not working for me...

**Comment by meganrogge** [comment]
@SpiderMath @AryanJ-NYC this is resolved in the next Insider's build. 
Duplicate of #116095
