### ISSUE TITLE
Extensions view empty

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#116152]
Not sure if related to https://github.com/microsoft/vscode/commit/15616c186929f1095992d49dcc7a753428c4ff61 but the extension view is empty with no "view" menus:

<img width="500" src="https://user-images.githubusercontent.com/35271042/107298882-1990f380-6a2b-11eb-83d9-034e3ee61f93.png">

And when I attempt to move the extension view around I get these console errors:

![image](https://user-images.githubusercontent.com/35271042/107298993-5826ae00-6a2b-11eb-9f6d-65c3956835f1.png)

**Comment by sandy081** [comment]
Fixed by 714fd96f61a8a02f26e9acdf93edb24d506ca4f7
