### ISSUE TITLE
The green or blue vertical bar on the right of the line number disappeared

### ISSUE THREAD

**Issue by w-xy** [microsoft/vscode#116157]
Issue Type: <b>Bug</b>

There should have been a green or blue vertival bar on the right of the line number to show if the line is added or modified. But I cannot find it now.
I tried to disable all extensions, but it still doesn't work.

![issure](https://user-images.githubusercontent.com/17586945/107307280-5ad3e280-6ac1-11eb-9261-4db65cc661a3.PNG)

Steps to Reproduce:
Open a file in a git tracked repository;
Add a line or modify something;
See if there is a vertival bar after the line number and before the content.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel Core Processor (Skylake, IBRS) (4 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.12GB (1.62GB free)|
|Process Argv|--crash-reporter-id f14d4cea-f3e3-4560-a1d6-341750f03582|
|Screen Reader|no|
|VM|100%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by meganrogge** [comment]
Without extensions, you won't see this. Also check that you're signed into github

**Comment by w-xy** [comment]
Here are my extensions. I still cannot see the bar.
I am using my working computer, and due to my company policy, I can't sign into github in vscode. But I saw the bar whithout login in. If you want my settings.json, tell me and I will provide you. 


Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-live2d|Cha|1.7.200
vscode-office|cwe|1.9.1
gitlens|eam|11.2.1
LogFileHighlighter|emi|2.11.0
code-runner|for|0.11.2
matlab|Gim|2.0.0
vscode-drawio|hed|1.3.0
vscode-ansi|ili|1.1.1
git-graph|mhu|1.28.0
prettify-json|moh|0.0.3
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
hexeditor|ms-|1.4.0
clang-tidy|not|0.5.1
emoji|Per|1.0.1
background|sha|1.1.26
emoji|tom|0.2.2
cmake|twx|0.0.17
vscode-counter|uct|2.2.2
vscode-icons|vsc|11.1.0
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
material-theme|zhu|3.9.13

**Comment by w-xy** [comment]
Hi @eamodio, the problem still exsits on my working computer. It's fine on my personel computer--a green bar showing adds, and a blue bar showing modifies which is based on the last git commit. I'm dying to see these bars when i'm working, and this can make me more productive. I‘m on vacation during the following week, if you need more information, i can handle it after the vacation.

**Comment by w-xy** [comment]
Good news! I remove the extensions vscode-live2d and background, and the problem no longer exists!!!
Thank you @meganrogge @eamodio !
