### ISSUE TITLE
Append a number to a function name and save will trim the end of line?

### ISSUE THREAD

**Issue by tzwsoho** [microsoft/vscode#116158]
Issue Type: <b>Bug</b>

My golang code are below:

`// PickupGroup 从持有牌中选出特定类型的五张牌组，返回牌组和第一张牌的索引
func (ai Playable) PickupGroup(cards model.CardGroup, gt model.GroupTypes, offset int) (model.CardGroup, int) {
	switch gt {
	case model.GroupTypesStraight: // 没有 2AKQJ/32AKQ/432AK 这三种组合
		for i := offset; i < cards.Len()-4; i++ {
`

---------------------------------------------------------------------
When I rename the func PickupGroup to PickupGroup5 and press Ctrl+s to save. The end of comment `"索引"` would change into `"索"`. And the end of the func "int) {" will change into "int)".

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.62GB free)|
|Process Argv|--crash-reporter-id 00cd863c-f738-4f37-b60c-95df0bb7289d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
jce-plugin|abe|3.0.3
aliyun-serverless|ali|1.27.16
smali|cra|1.0.1
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
xml|Dot|2.5.1
vscode-go-syntax|dun|0.0.18
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.13
vscode-npm|fkn|3.3.0
go|gol|0.22.1
beautify|Hoo|1.5.0
vscode-upsource|kas|1.6.1
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.2
cpptools|ms-|1.2.0
go-doc|msy|1.0.1
vetur|oct|0.32.0
java|red|0.74.0
vscode-zipexplorer|sle|0.3.1
sonarlint-vscode|Son|1.20.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by tzwsoho** [comment]
![image](https://user-images.githubusercontent.com/3684868/107307484-ba31f280-6ac1-11eb-8177-57fa1eb5ba01.png)

**Comment by yume-chan** [comment]
Looks like caused by the formatter from go extension.

**Comment by tzwsoho** [comment]
Probably the filename cause it. When I rename the file `aiplayable.go` to `ai_playable.go`. The problem wouldn't happen again!
