### ISSUE TITLE
"Native (macOS) Tabs" are split into new windows across launches

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#116148]
- VSCode Version: 1.53.0
- OS Version: 10.15.5

Steps to Reproduce:

1. Enable the Native Tabs feature
2. Open a second native tab
3. Relaunch VS Code
4. Observe that what _was_ the second native tab is now opened as its _own window_ instead of a second native tab in a _single window_

Does this issue occur when all extensions are disabled?: Yes

**Comment by NSExceptional** [comment]
@bpasero which issue is this a duplicate of?

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/27222

**Comment by NSExceptional** [comment]
Ah, thank you. Geez, 2 years and no one at electron has responded to your upstream issue? 😓
