### ISSUE TITLE
I can't find target command in command search because the English description has disappeared

### ISSUE THREAD

**Issue by JaxVanYang** [microsoft/vscode#116101]
Issue Type: <b>Bug</b>

I can't just type "collapse" in command search to find the command "workbench.files.action.collapseExplorerFolders", however I could achieve this in previews version in VS Code.
![2021-02-08 20-29-40 的屏幕截图](https://user-images.githubusercontent.com/25650612/107220087-e6f7f280-6a4c-11eb-92fa-556256462d18.png)

This problem appears on both my Windows and Ubuntu machine. I believe that is because you delete its English description in Chinese language pack.
![2021-02-08 20-26-49 的屏幕截图](https://user-images.githubusercontent.com/25650612/107220112-ee1f0080-6a4c-11eb-9d7f-e7075f63bcff.png)

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.8.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2857)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.67GB (1.67GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 078ee844-6d32-4053-9ad3-3027c9560de2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
java|red|0.74.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by dbaeumer** [comment]
This is not a translation problem. If we want to have the original text (e.g. English) for a command we have to provide it (like for example here: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/browser/task.contribution.ts#L321)

We don't automatically have the English version of a string (we don't know for which they are necessary so the developer has to decide this). 

I actually don't know you owns `Action2` and all the code around it. 

@isidorn @jrieken @sbatten any hint?

**Comment by jrieken** [comment]
This is supported in `Action2` when title is an object, this is a sample: https://github.com/microsoft/vscode/blob/7020ccf1346ad505f1395748882a435c1743256b/src/vs/workbench/browser/actions/layoutActions.ts#L36

**Comment by isidorn** [comment]
Assigning to me since I did not add the original title when adopting `Action2` in the Explorer

**Comment by JaxVanYang** [comment]
Thank you guys, this feature helps me a lot. BTW, IDEA doesn't show both English and local language, so VS Code is more friendly in this way :+1:
