### ISSUE TITLE
Action bar in View title area renders the focus with the bottom cut off

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116209]
1. Have the default theme and no settings
2. Focus on the title area actions
3. Notice the bottom focus is cut off

I see this for all views, thus first assigning to @sandy081 and @sbatten 

![Screenshot 2021-02-09 at 18 45 21](https://user-images.githubusercontent.com/1926584/107404985-1cf9ad00-6b07-11eb-8254-8d0c7e8d1c3f.png)

**Comment by sandy081** [comment]
@isidorn I cannot reproduce this in insiders and also running out of sources. Are there any missing steps?

**Comment by sbatten** [comment]
also not reproing on windows for me

**Comment by isidorn** [comment]
I believe my actionBar changes fixed it, let's close. Sorry for the false alarm
