### ISSUE TITLE
Refactoring destroyed hundreds of files, even in node_modules

### ISSUE THREAD

**Issue by thomas-mindruptive** [microsoft/vscode#116267]
Issue Type: <b>Bug</b>

We have an interface containing following method:

    save<T extends IHasId>(options: {
        clazz: string,
        obj: T,
        partitionKey?: PartitionKey,
        id?: string | number,
        create?: boolean,
        one2NParentInfo?: One2NParentInfo<T>,
        transaction?: any
    }): Promise<SaveResult<T>>;

I refactored "clazz" to "className".

We use npm link to link 4-5 npm with each other. 

VSC refactored hundreds of files, also in node_modules to code like:

  "`paramName: className`" instead of "`paramName: string`"

So it replaced all string-parameter-types with "className". In addition, it changed "Extract": 

  "`Extract<keyof T, string>`" to "`Extract<keyof T, className>`"

I can't reproduce, how and which files exactly have been altered. 
I had to revert all changes in GIT, delete all node_modules and re-install them.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.55GB free)|
|Process Argv|--crash-reporter-id e4deceb6-609b-4873-8015-1d29ad7dffe6|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
GetterAndSetterGenerator|afm|1.0.3
gitlens|eam|11.2.1
vscode-html-css|ecm|1.9.1
rest-client|hum|0.24.4
git-graph|mhu|1.28.0
code-beautifier|mic|2.3.3
vscode-less|mrm|0.6.3
type-doc-vscode|Tre|0.0.35

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by mjbvz** [comment]
Can you please share more detailed steps on how this happened, such as the contents of the file you triggered the refactoring in and the packages you had installed. A small project that demonstrates the problem would be ideal

**Comment by thomas-mindruptive** [comment]
I understand that it is hard to reproduce the problem. I does not happen if I try to repeat it now.

We installed 

```
        "@azure/storage-blob": "^12.2.0",
        "atob": "^2.1.2",
        "bcrypt": "^5.0.0",
        "btoa": "1.2.1",
        "bufferutil": "^4.0.1",
        "busboy": "^0.3.1",
        "excel4node": "^1.7.2",
        "express": "^4.17.1",
        "express-session": "^1.17.1",
        "jsonwebtoken": "^8.5.1",
        "nodemailer": "^6.4.11",
        "passport": "^0.4.1",
        "passport-azure-ad": "^4.3.0",
        "reflect-metadata": "^0.1.13",
        "sharp": "^0.26.3",
        "utf-8-validate": "^5.0.2"
```

and in other app-packages some additional packages.

We have a framework consisting of 5 node-packages and we use "npm link" to use them in our application.

Sorry that I can't provide a small-scale sample.  But the fact that VSC refactored "string" to "className" might point to the problem because it is more than strange. Maybe a mandatory preview-step like in WebStorm could prevent the consequences of the error (not the reason). Because the fact that hundreds of files will be changed would have made me suspicious. :-)

In this case the "simple F2 approach" seems more like a danger than a convenience.

**Comment by mjbvz** [comment]
Without steps to reproduce this, we can't really do anything much so I am closing this issue. Please let me know if you find steps to reproduce this
