### ISSUE TITLE
Extend C# IntelliSence suggestions list to symbols out of current using directives.

### ISSUE THREAD

**Issue by GuidC0DE** [Microsoft/vscode#11623]
- VSCode Version: 1.4.0
- OS Version: OS X El Capitan & Windows 10

It would be very handy to see in suggestions list classes that come from namespaces not used in the editable file. For example, when we start typing class name "EventHandler" we'll not see suggestion for it if "using System;" is not presented. Now we have only ability to type class name completely, expand light bulb and choose quick fix to add missing "using". But sometimes it is too hard to remember class name exactly and class names can be too long to type. This is why it would be good to include such classes in suggestions list.

**Comment by ramya-rao-a** [comment]
@GuidC0DE Are you using the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) ?

**Comment by GuidC0DE** [comment]
@ramya-rao-a yes, I'm using this extension. Thank you for clarification! I'm sorry for posting it here.

**Comment by ramya-rao-a** [comment]
@GuidC0DE no problem
