### ISSUE TITLE
[Feature Request] Format on next line (extending the Format on Type feature)

### ISSUE THREAD

**Issue by Leopard20** [microsoft/vscode#116275]
One of the nice features in Visual Studio is that it automatically formats your code when you go to the next line. For example:
```cpp
for(auto i=1;i<10;++i){
```
automatically formats when you press enter:
```cpp
for (auto i = 1; i < 10; ++i) {
```
Unfortunately, VSCode only supports autoformats on the semicolon character (`;`), not next line. Maybe you could also add this right below the `Format on Type` option?

**Comment by jrieken** [comment]
Works for me using TS/JS. This is likely a problem with the extension that you are using but how would I know

https://user-images.githubusercontent.com/1794099/107480859-916f3300-6b7d-11eb-8558-cbe8db3c7fe3.mov

**Comment by Leopard20** [comment]
Nope. I disabled all of the extensions and the issue still persists.
It indeed works for TS/JS (as I just tested), but not for C/C++.

**Comment by jrieken** [comment]
>  but not for C/C++.

Then this issue should be filed againt the c/c++ extension
