### ISSUE TITLE
Changes to http_proxy settings do not take effect in Extensions viewlet without reload

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#11621]
In the home (disable) and workplace (enable) has switched the setting of the `http_proxy`.
However, does not reflect `http_proxy` settings are immediately in Extensions-view.
proxy settings until run the `Reload Windows` command or restart the vscode will not be reflected.

- VSCode Version: 1.5.0-insider (1.5.0-insider) 538cd9ded5a471fbb20920f01eff9c8df4b83ee9
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Save the `http_proxy` of settings.json to comment/uncomment
2. open extensions-view and @outdated. error connect ETIMEDOUT x.x.x.s 

In vscode 1.4 expected operation.

**Comment by ramya-rao-a** [comment]
@satokaz Are you saying that changes made to the `http_proxy` settings do not take effect in the Extensions viewlet until `Reload Windows` is used ?

**Comment by satokaz** [comment]
@ramya-rao-a 

> Are you saying that changes made to the http_proxy settings do not take effect in the Extensions viewlet until Reload Windows is used ?

yes

> And that this was not a problem in 1.4.0 ?

yes

**Comment by joaomoreno** [comment]
Yes this has changed, but it is working as designed. A proxy change involves a restart.
