### ISSUE TITLE
Sub menus by extensions in explorer context menus

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#11625]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.4
2. 
I would like to explorer/context extension right click menu, there is a sub menu ，how do I do

"menus": {
			"explorer/context": [
				{
					"command": "extension.openNewInstance",
					"group": "navigation@2",
					"openNewInstance":[
						{
							"command": "extension.openNewInstance",
							"group": "navigation@1"
						}
					]
				},
				{
					"command": "extension.scopeToHere",
					"group": "navigation@1"
				}
			]
		}

**Comment by ramya-rao-a** [comment]
@ydcoming Are you asking how to add sub menu to your menu item in explorer/context menus?

**Comment by ydcoming** [comment]
yes

**Comment by ydcoming** [comment]
my menu  has items

**Comment by ramya-rao-a** [comment]
@jrieken At the moment, extensions cannot add submenu items to explorer/editor context menus, correct?

**Comment by jrieken** [comment]
closing as dupe of #9827
