### ISSUE TITLE
restrict to scroll in floating window during debug instead of the whole editor

### ISSUE THREAD

**Issue by iamzhout** [microsoft/vscode#116254]
VS Code Version: 1.53.1
OS: macOS Big Sur 11.2.1

Reproducible steps:
As can see in below screenshot video, when scroll in floating window, it will scroll in the whole editor, which make the window disappear.

https://user-images.githubusercontent.com/14846203/107458729-9e951d80-6b8f-11eb-89b5-ea2f999e3fe1.mp4

The right behavior should restrict scroll in the floating window.

**Comment by iamzhout** [comment]
when debugging, we often hover to see detailed values of variables, and if the struct of the variable is large, the popup window will be long, and need to scroll to view them all. 

But when scrolling using mouse, it will scroll the editor instead of the popup window, and make the popup window disappear, as shown in the my screenshot video above.

**Comment by gjsjohnmurray** [comment]
Please state version and platform as a minimum, but the document at https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests gives other pointers too.

**Comment by iamzhout** [comment]
> Please state version and platform as a minimum, but the document at https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests gives other pointers too.

OK, here is the Code & OS version info (other info such as extensions installed seems not quite relevant to this issue): 
VS Code Version: 1.53.1
OS: MAC OS 11.2.1
Debugging language: golang

**Comment by isidorn** [comment]
@iamzhout if the mouse is over the debug hover the scroll should only affect it, not the editor. Only once you move away from the hover and over the editor the scroll will affect the editor. I find this behavior nice and expected.

However let's keep it open to gather more user feedback

**Comment by gjsjohnmurray** [comment]
@isidorn in my testing I saw what I think @iamzhout is raising. If I use the mousewheel to scroll downwards while over a debug hover, and if the hover has no more undisplayed text below to bring into view, then the scroll acts on the editor document.

**Comment by isidorn** [comment]
@gjsjohnmurray I can only reproduce that if my mouse is over the Hover title area or the help text area in the bottom.
So I can not reproduce this if the mouse is in the large central tree area of the hover

**Comment by gjsjohnmurray** [comment]
@isidorn what I reported still reproduces in 1.53.2. In Insiders I get the same as you.
