### ISSUE TITLE
add the "bin" options in launch.json for custom debugging

### ISSUE THREAD

**Issue by mamboer** [Microsoft/vscode#11624]
- VSCode Version: 1.4.0 
- OS Version: MacOSX 10.11

I'm working on a node app which will invoke [pug-cli](http://npmjs.com/package/pug-cli) to compile pug templates to html files.

For certain reasons i have to install `pug-cli` locally in the project, and config the `bin` options in package.json as below:

```
"bin": {
    "pug": "./node_modules/pug-cli/index.js"
  }
```

and in my app.js,

```
require('shelljs/global');
exec(`pug -O "{ env: '${env}' }" -o ${type} chrome/views/`);
...
... 
//other logics
```

When i launch the app via VSC's debugger, it complains '/bin/sh: pug: command not found'。

I hope that VSC can support custom local `bin` options like NPM.

**Comment by weinand** [comment]
@mamboer If you run your app from the command line with "node app.js", does 'exec' find 'pug'?

**Comment by mamboer** [comment]
@weinand 

Yes, it does.

It will use my local 'pug' which specified in the package.json.

I don't have the global `pug-cli` installed.

**Comment by weinand** [comment]
@

**Comment by mamboer** [comment]
As the screenshot above, it returns `/Users/lv/dev/.../node_modules/.bin/pug`

**Comment by weinand** [comment]
We have decide not to automatically add "node_modules/.bin" to the PATH because it is very "npm" specific and only makes sense in an npm context.
