### ISSUE TITLE
Windows cannot access the specified device, path, or file

### ISSUE THREAD

**Issue by JBroyan** [microsoft/vscode#116273]
![Screenshot (8)](https://user-images.githubusercontent.com/75772042/107478364-f5bed200-6b3e-11eb-995f-84cb4f37e604.png)
I recently closed VS code and it randomly just stopped working. There was some buggy popup about VS Code trying to update, but then it failed; now whenever I click the icon I get the Windows popup about not being able to access it. My file path is now apparently invalid, but I didn't change it? I've already redownloaded VS twice, and don't know how to fix it. Somebody please help!

**Comment by joaomoreno** [comment]
You should change the `Microsoft VS Codev2` to `Microsoft VS Code` in that target location.
