### ISSUE TITLE
How to seek to end-of-line of a wrapped line?

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#11626]
- VSCode Version: ALL
- OS Version: Windows

Steps to Reproduce:
1. Write a line long enough so that it wraps into two or more lines.
2. Now, place cursor on first line, and then press "End". It goes to the end of the **first** line only.
3. Pressing "End" again makes it go to the **last non-whitespace** character on the first line.

In Atom (or Sublime, I've forgotten which) pressing "End" second time puts the cursor at the logical end of the line. Right now, vscode doesn't give me any way to go the end real end of line, and the real start of line. This poses serious problems while using multi-cursors to edit lines, as any line which wraps completely breaks the whole flow.

**Comment by ramya-rao-a** [comment]
@alexandrudima Both notepad++ and sublime support the "press End twice to reach logical end of the line". This would be a candidate for a feature request?

**Comment by kumarharsh** [comment]
@alexandrudima this feature has landed in vscode for a few versions now. I'm closing this as resolved.
