### ISSUE TITLE
Add 'Run to cursor' to VS Code debug floating bar

### ISSUE THREAD

**Issue by iamzhout** [microsoft/vscode#116250]
VS Code's debug floating bar has no 'run to cursor' button:
![image](https://user-images.githubusercontent.com/14846203/107455840-66d7a700-6b8a-11eb-8b40-5e01bbc34913.png)

which is only available in context menu:
![image](https://user-images.githubusercontent.com/14846203/107456221-c2099980-6b8a-11eb-972a-23b3f174aa7c.png)

suggest to add this to floating bar, which is often used and quite relevant to debug functionality.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by iamzhout** [comment]
> This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

OK, thanks.

**Comment by jerronl** [comment]
I use extension ext:jerrygoyal.shortcut-menu-bar with editor.debug.action.runToCursor as a user button

**Comment by 19504643** [comment]
@isidorn "Run to cursor" is common used when debugging, could you please move it back to the agenda
