### ISSUE TITLE
Missing "On Run, when projects out of date" setting from Visual Studio

### ISSUE THREAD

**Issue by RCalocaO** [microsoft/vscode#116238]
(Couldn't find a match for an existing issue)

On Visual Studio, there is the **Tools -> Options -> Projects & Solutions -> Build And Run** setting, where you can set "**On Run, when projects out of date**" to "**Never Build**". This is important for some projects (eg Unreal Engine) as their custom build tool mechanism is slow on some platforms, so executing this custom step could take seconds when re-running a previously built executable/binary.

**Comment by alexr00** [comment]
@RCalocaO how are you building/running in VS Code currently?

**Comment by RCalocaO** [comment]
I should've added, this is in the context of Linux (Ubuntu) - I downloaded it from https://code.visualstudio.com/download

**Comment by alexr00** [comment]
@isidorn I think this is a request to have a setting that causes `preLaunchTask` to be ignored.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
