### ISSUE TITLE
Source Control view don't show folder case shift

### ISSUE THREAD

**Issue by TobiasSekan** [microsoft/vscode#116265]
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Explorer:
![2021-02-10 05_56_23-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/107467020-60830400-6b65-11eb-89be-e820d7f6bcf9.png)

Source Control (without staged):
![2021-02-10 05_54_37-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/107467025-62e55e00-6b65-11eb-8dc5-ee02542cce64.png)

Source Control  (with staged)::
![2021-02-10 05_55_22-D__Git_solutionextension](https://user-images.githubusercontent.com/17874713/107467028-6547b800-6b65-11eb-9854-2a8e12107934.png)

Steps to Reproduce:

1. Have a folder with only lowercase name
2. Rename the folder to uppercase (e.g first letter uppercase)
3. Switch to Source Control view

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
If you open a Terminal in your workspace root and run the command `git config core.ignorecase` what does it report?

**Comment by TobiasSekan** [comment]
> 
> 
> If you open a Terminal in your workspace root and run the command `git config core.ignorecase` what does it report?

oh 🤦  i didn't even know that there is a setting for this, thanks for your help

But it would be nice when we have a Information about this, when only the name case have change

**Comment by eamodio** [comment]
Closing this as this behavior is controlled by Git, and as @gjsjohnmurray pointed out, controllable by the `core.ignorecase` configuration value.
