### ISSUE TITLE
Breadcrumbs no longer allow to navigate between projects in a workspace

### ISSUE THREAD

**Issue by PhiLhoSoft** [microsoft/vscode#116297]
Issue Type: <b>Bug</b>

1. I have a workspace with several projects opened (libraries). I have the following breadcrumb, for example:
ng-oo-form > src > lib > date > form-date.directive.ts > …
2. When I click on src, I get the list of files (and folders), I can select one, and if folder, I get a sub-menu, and so on.
3. When I click on ng-oo-form (name of a library), I get the list of projects. But if I click on one, instead of showing the files and folders at the root of the project, as it did before, I get an error message in a toast stating: "Unable to open 'ng-oo-focus': File is a directory."

Bug already seen in the version before this one.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.08GB free)|
|Process Argv|--crash-reporter-id 4d75f8cb-16cc-4be3-a184-35c10c01676f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.10.0
ng-template|Ang|11.1.3
vscode-toggle-quotes|Bri|0.3.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
css-flexbox-cheatsheet|dzh|3.2.0
gitlens|eam|11.2.1
tsl-problem-matcher|eam|0.3.1
EditorConfig|Edi|0.16.4
vscode-jest-runner|fir|0.4.31
auto-rename-tag|for|0.1.6
rest-client|hum|0.24.4
docthis|joe|0.7.1
import-sorter|mik|3.3.1
vscode-scss|mrm|0.9.0
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
console-master|Phi|1.0.0
git-file-history|pom|1.0.1
vscode-yaml|red|0.14.0
stylelint|shi|0.51.0
vscode-ast|thz|1.0.9
quokka-vscode|Wal|1.0.342
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry914:30250197
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by jrieken** [comment]
Yeah, I can reproduce

**Comment by PhiLhoSoft** [comment]
Sorry for the delay, but I don't use the Insiders version, so I waited for the official release to test the fix.
I can confirm the fix is /verified 🍾
