### ISSUE TITLE
Whole UI scrolls up

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#11620]
- VSCode Version: 1.5.0-insider 538cd9ded5a471fbb20920f01eff9c8df4b83ee9 2016-09-05T08:29:15.791Z
- OS Version: Mac OSX El-Captain

Steps to Reproduce:

1.  Open a file that is longer than the window height
2. Scroll down to the bottom

Happens since the last Insider build.

![Gif](http://i.giphy.com/l3vR7Wibcr6Swdwf6.gif)

**Comment by ramya-rao-a** [comment]
@marvinhagemeister I am on the exact same insiders version in Mac OSX El-Captain and I cannot repro.

Can you provide a few more details?

- Which extensions do you have installed? 
- Can you repro this when extensions are disabled? `code --disable-extensions` ?
- Can you open dev tools and inspect that blank area below the status bar and send us a screenshot of that element?

**Comment by bpasero** [comment]
@marvinhagemeister also, how do you scroll to the bottom? And can you pin point which update caused this? Or is it 1.5.0 vs 1.4.0 causing it?

**Comment by marvinhagemeister** [comment]
@ramya-rao-a @bpasero It was yesterdays (7.9.2016) update that broke it for me. Weirdly, I haven't been able to reproduce this anymore today. I'll leave this open for another day and if I can't find anything to reproduce it or the issue is gone, I'll close this one

**Comment by bpasero** [comment]
@marvinhagemeister I would be surprised if any change in that time frame could cause this, rather this bug is hard to reproduce but can always happen with 1.5. Anyhow, when you find steps to reproduce, please comment.

**Comment by bpasero** [comment]
Closing this until we have more steps or more users that see this.

**Comment by marvinhagemeister** [comment]
Yeah, that's best. I haven't been able to reproduce it anymore in the past days abs I'm using vscode daily for up to 10h.
