### ISSUE TITLE
Revisit editorOpenWith living on its own

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116272]
I feel the `editorOpenWith.ts` thing needs to go away and move to respective services. It seems wrong to me that you pass in an editor group to operate on instead of having this exposed from the `IEditorGroupService`. Here is my thinking:
* add a new method to [`IEditorGroup`](https://github.com/microsoft/vscode/blob/630e706ad2de99e255a18bf77f72d569e9fc0e49/src/vs/workbench/services/editor/common/editorGroupsService.ts#L369-L369) (e.g. `openEditorWith`)
* clients will use `IEditorGroupService.getGroup().openEditorWith(...)`
* this method should also include the necessary dialog prompts for dealing with unsaved editors (from https://github.com/microsoft/vscode/pull/115264)

As for the remaining pieces of [`editorOpenWith.ts`](https://github.com/microsoft/vscode/blob/572bc1810dcb469c82f24d7c3135b2e12b72705e/src/vs/workbench/services/editor/common/editorOpenWith.ts#L200-L310) we can simply move them into `src/vs/workbench/common/editor.ts` at the end into a new folded region.

**Comment by bpasero** [comment]
This is now outdated and please see the proposal in https://github.com/microsoft/vscode/issues/100281. Feel free to close.

**Comment by lramos15** [comment]
Closing in favor of #100281
