### ISSUE TITLE
Poor scroll performance on macOS

### ISSUE THREAD

**Issue by jjiburg** [microsoft/vscode#116243]
Info:

- VS Code Version: 1.53.0
- OS Version: macOS 11.0.1 Big Sur
- Hardware: i7-10700k, RX-580 8GB GPU, 3 hi-dpi displays

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Open vscode.
2. Open text file with 300+ lines. 
3. Scroll the page. 

Observed behavior: Scroll performance is degraded. Missed frames, slow response. 

Notes:

It appears that performance is improved in 1.53.0 as compared to 1.52.0. However, launching vscode with the `--disable-renderer-accessibility` still results in improved performance. 

I'm attaching two performance profiles in a zip. One run with the flag enabled and smooth scrolling performance and the other with no cmd args passed and poor performance.

[vscode.accessibility.performance.zip](https://github.com/microsoft/vscode/files/5955120/vscode.accessibility.performance.zip)

**Comment by alexdima** [comment]
@jjiburg I have generated a file with 300 lines of Lorem ipsum:

[116243.txt](https://github.com/microsoft/vscode/files/6045920/116243.txt)

Does this also scroll slowly for you?

From the attached profile I could see a lot of time spent in doing a couple of hit testing (determining what is the (line;column) where the mouse is pointing), so I wonder if there is something specific about the file or its contents that is causing this slowness.
