### ISSUE TITLE
Command disappear from Command pallet  

### ISSUE THREAD

**Issue by arxeiss** [microsoft/vscode#116299]
- VS Code Version: 1.53.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open command and type **Debug Select and Start**
2. There is nothing like this, however, in previous version there was this option. And I can still create a custom shortcut:

```
{
    "key": "shift+alt+m",
    "command": "workbench.action.debug.selectandstart"
}
```

I would like to see this command in Command pallet, but I don't know how to add it there. And the dialog itself is probably still in VS Code, because the command above works.

Does this issue occur when all extensions are disabled?: Yes, same in Insider preview as well

---

Edit: Just to clarify. I have multiple configurations in launch.json and I'm starting them as needed. So I used that dialog which listed all configurations and I chose one.

**Comment by isidorn** [comment]
Good catch, thanks for reporting this.

**Comment by arxeiss** [comment]
Wow, that was quick. Thank you
