### ISSUE TITLE
Popup file navigation links are broken

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode#116224]
- VS Code Version: 1.53.1 (user setup)
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Run a Python file that imports a missing function.
2. Mouseover the file link to see a popup with a link to go to the file: 
![image](https://user-images.githubusercontent.com/9662163/107415097-3a347880-6b13-11eb-9b1d-70de44058988.png)

3. Click that link and see that even while holding ctrl as indicated (and defeating purpose of the link in the popup) the linked file won't open. Maybe one of the other similar popup functions (#78647) still works. 

Does this issue occur when all extensions are disabled?: No, because without the Python extension the file can't be launched by VS Code.

**Comment by meganrogge** [comment]
yeah it seems the `_` character breaks the link

**Comment by Tyriar** [comment]
Tested on latest and this link format with an __init__.py file works fine for me
