### ISSUE TITLE
Git commit input box does not wrap

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116202]
Previously it would wrap text automatically.
I believe from today's Insiders it no longer wraps text.

![Screenshot 2021-02-09 at 16 09 48](https://user-images.githubusercontent.com/1926584/107383406-3e4f9e80-6af1-11eb-8fe0-d4183f8aa61f.png)

**Comment by eamodio** [comment]
I can't reproduce this with today's insiders can you?

**Comment by isidorn** [comment]
This was beacuse I had the following setting
editor.accessibilitySupport": "on"

When we detect a screen reader we disable word wrap in editor. There are already issues for this
Thus closing this. Sorry for the false alarm
