### ISSUE TITLE
Debug in Container - Failed to bind to address http://[::1]:5000: address already in use.

### ISSUE THREAD

**Issue by rwallerms** [microsoft/vscode#116208]
Following the steps verbatim from this article, using the sample project - https://code.visualstudio.com/docs/containers/quickstart-aspnet-core

Testing step works fine.

Debug in container step is having issues. The app is not able to startup because of an _Address In Use_ exception when debugging.

Exception has occurred: CLR/System.IO.IOException
An unhandled exception of type 'System.IO.IOException' occurred in System.Private.CoreLib.dll: 'Failed to bind to address http://[::1]:5000: address already in use.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Net.Sockets.SocketException : Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   
   
   
   I am using WSL2 with Ubuntu 18.04 distribution.

**Comment by chrmarti** [comment]
@gregvanl Not sure who maintains this tutorial. It uses port 5000 on localhost which works well as long as that port is not already in use. This is mentioned here and might need more details on how to work around it:
>When you issue Run command for an image, VS Code will try to use the same port number for the host port and container port. This makes it easy to remember which port to use to communicate with the container, but it won't work if the host port is already in use.

**Comment by rwallerms** [comment]
Apologies, I was able to get this to work on another machine, and then also on the original machine. I must have had another container running at the time that I didn't notice.

**Comment by gregvanl** [comment]
Closing as user is unblocked.
