### ISSUE TITLE
Not possible to add terminator as internal terminal in ubuntu

### ISSUE THREAD

**Issue by Sutyke** [microsoft/vscode#116280]
- VS Code Version:1.52.1
- OS Version:  ubuntu mate 20.04

Steps to Reproduce:
1. sudo apt-get install terminator
2.add to setting.json "terminal.integrated.automationShell.linux": "/usr/bin/terminator",
3. ctrl+shifp p , terminal: Set default shell  ( terminator not visible )

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Terminator is a terminal, not a shell. So it cannot be run internally.
