### ISSUE TITLE
macOS: VS code forgets full screen mode after app restart

### ISSUE THREAD

**Issue by dreasan** [microsoft/vscode#116220]
- VS Code Version: 1.53.1
- OS Version: 10.15.7

I'm not certain if this has been reported before. At least I could not find it in the issues and still experience the behavior.

Steps to Reproduce:

1. Open VS Code.
2. Maximize the application window (e.g. press Control+Command+F)
3. Now close the app (e.g. with Command+Q)

Expected behavior: The app should restore the previous app sessions window in fullscreen mode.
Actual behavior: The app is restored maximized (if it has been maximized before), but not in fullscreen mode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
You need to configure `window.restoreFullscreen: true` in settings.

**Comment by dreasan** [comment]
@bpasero yep, that works. should be a default in my opinion. but guess that's a matter of taste. thank you.
