### ISSUE TITLE
Tree: Support continuous find

### ISSUE THREAD

**Issue by petrillek** [microsoft/vscode#116286]
Issue Type: **Feature Request**

Hi,

in a list of files I can filter them by start typing the name of the file. It is a super useful feature when you have hundreds+ files.
My issue is that the filter is trying to find the letters in the whole file name. 
Here is an example search for word "file":

* this-is-**file**-i-looked-for.jpeg (I expect this to be returned)
* **f**or-th**i**s-**l**.jp**e**g (This should not be returned, it is only a random match)

Would it be possible to add there extra settings to only returns full strings matches? Or is there some setting already buried somewhere?

Thanks a lot for all the work on awesome editor.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 20.3.0

**Comment by petrillek** [comment]
I've searched for it before I posted, but apparently used wrong keywords. Sorry for a duplicate.
But, as the previous issues were closed as "Out of scope" more then one year ago, can you reconsider it again now?

**Comment by joaomoreno** [comment]
Yeah it was closed out of scope here: https://github.com/microsoft/vscode/issues/66913

**Comment by StingyJack** [comment]
> This feature request received a sufficient number of community upvotes and we moved it to our backlog. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Fuzzy filtering on a navigational view does not make sense. Its one thing if this did some title case matching ("gs" locates a node with the name "GardenState.cs" or exact substring matching of "Figs.cs"), but having it bring back "GeeWhizThisIsNothingRelatedToWhatISearchedFor.cs" is just noise and a waste of time.

**Comment by joaomoreno** [comment]
We should support what the editor find widget supports:

- Case sensitivity
- Contiguous string
- Regex
