### ISSUE TITLE
Go to Definition is not working

### ISSUE THREAD

**Issue by parthshah27** [microsoft/vscode#116266]
Issue Type: <b>Bug</b>

I have installed vs code in my pc after that go to definition (F12) is not working earlier it was working but as of now it's not working

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (3.44GB free)|
|Process Argv|--crash-reporter-id f3fd7d5f-c7ae-4a8e-a3b3-f480d6e096a0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.14.7
auto-close-tag|for|0.5.10
docker-explorer|for|0.1.7
composer|ika|0.7.1
smarty|imp|0.3.0
php-cs-fixer|jun|0.1.158
vscode-phpfmt|kok|1.0.30
php-symbols|lin|2.1.0
php-namespace-resolver|Meh|1.1.8
php-docblocker|nei|2.1.0
mvc-php|Ree|0.0.14
format-html-in-php|rif|1.7.0
php-formatter|Sop|0.2.4
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244:30250195
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes516:30244333
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
Likely caused by an extension crashing the EH process that all extensions share. Please use the Extension Bisect command to investigate.

**Comment by robertmazzo** [comment]
I have Version 1.53.2, and the F12 "Go to definition" is no longer functional. It just shows a tooltip-style message "No definition found".

**Comment by luisiacc** [comment]
> I have Version 1.53.2, and the F12 "Go to definition" is no longer functional. It just shows a tooltip-style message "No definition found".

This happend to me upgrading to 1.53.2 too on the Python extension using WSL, I deleted the .vscode-server folder from WSL and then run vscode back, then reinstall all extennsions that were installed on WSL, that seems to resolved the problem for me.

**Comment by weinand** [comment]
@parthshah27  @luisiacc @robertmazzo 
For what language(s) are you seeing this problem?

**Comment by parthshah27** [comment]
The issue was resolved by downgrade the vs code

**Comment by weinand** [comment]
"Downgrading VS Code" is more a workaround than a resolution...
Does the problem occur for php?
