### ISSUE TITLE
VSC triggers a rebuild on angular projects when opening new files

### ISSUE THREAD

**Issue by JDillon522** [microsoft/vscode#116227]
Issue Type: <b>Bug</b>

Nearly every time I open a file in angular project VSC triggers a rebuild somehow with the Angular CLI. 

I have disabled all my extensions to see if it was caused by one and the issue repeats itself, but less frequent (every 3-5 files opened vs every single file). 

This doesnt prevent me from working, but its increadibly annoying and time consuming to have to walk on eggshells while debugging a feature. 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (14.19GB free)|
|Process Argv|--crash-reporter-id 98980995-34b4-4020-bfc4-6617396ed52d|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
vstry244cf:30250196
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by weinand** [comment]
Since VS Code knows nothing about the Angular CLI, the only way to trigger a rebuild is by modifying files.
Opening files in VS Code or debugging with the JS debugger doesn't modify files.
So there must be something in your Angular setup that triggers this.
