### ISSUE TITLE
VS Code Takes A Extremely Long Time To Load UI

### ISSUE THREAD

**Issue by CoderMarcus** [microsoft/vscode#116251]
- VS Code Version: 1.53.1 (user setup)
- OS Version: Windows 10 Home version 20H2 build 19042.746, Windows Feature Experience Pack 120.2212.551.0
- PC Specifications: Intel Core i7-10510U, Nvidia GeForce MX230 2GB, 16 GB RAM

Steps to Reproduce:
1. Download the VS Code Windows stable build installer. (32-bit or 64-bit)
2. Install to the default location.
3. Launch VS Code.
4. Wait. (This may take an hour or more)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Can you provide the `trace_event.log` following the below steps,

```
code --trace-startup --trace-startup-duration=20 --trace-startup-file=<some-absolute-writable-path>\trace_event.log
```

Also was the previous releases working fine ? Can you also check if any antivirus is blocking the app ?

**Comment by CoderMarcus** [comment]
> Can you provide the `trace_event.log` following the below steps,
> 
> ```
> code --trace-startup --trace-startup-duration=20 --trace-startup-file=<some-absolute-writable-path>\trace_event.log
> ```
> 
> Also was the previous releases working fine? Can you also check if any antivirus is blocking the app?

I can't seem to create the 'trace_event.log'. However, I can still interact with the UI even if it doesn't show anything. [https://u.cubeupload.com/CubeUpMarcus/Screenshot2021021017.png](url)

**Comment by deepak1556** [comment]
> I can't seem to create the 'trace_event.log'.

What was the command you had tried.

> However, I can still interact with the UI even if it doesn't show anything.

The image link is broken, but based on what you are seeing it might very well be https://github.com/microsoft/vscode/issues/114459. Can you try `code --disable-features=CalculateNativeWinOcclusion`

**Comment by CoderMarcus** [comment]
> The image link is broken, but based on what you are seeing it might very well be #114459. Can you try `code --disable-features=CalculateNativeWinOcclusion`

That seemed to fix it. However, I did not have this issue until I updated to 1.53.1. Why is that?

**Comment by deepak1556** [comment]
Occlusion tracker was a newly enabled feature in upstream that came in with the Electron 11 update https://chromium-review.googlesource.com/c/chromium/src/+/2424498 

I am merging this issue to https://github.com/microsoft/vscode/issues/114459
