### ISSUE TITLE
Seeing CI failures when testing against VSCode v1.53.x...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode#116232]
hey there :wave:

i just noticed my CI started failing after enjoying a long stretch of stability. the failures occur when targeting VSCode `v1.53.0` and latest (at the time of writing this, `v1.53.1`):

the failure only occurs on my `windows` ([specs](https://circleci.com/developer/orbs/orb/circleci/windows?version=1.0.0)) job:

<img width="1235" alt="Screen Shot 2021-02-09 at 1 31 40 PM" src="https://user-images.githubusercontent.com/367674/107431370-35ec6900-6adb-11eb-9613-619688c4754e.png">

the error reported is:

```
  1) Compilation
       Compile application & DeviceOS (local):
     TypeError: Cannot read property 'execution' of undefined
  	at b.executeTask (c:\Users\circleci\project\packages\particle-vscode-core\.vscode-test\vscode-1.53.1\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:5425)
  	at executeTask (c:\Users\circleci\project\packages\particle-vscode-core\.vscode-test\vscode-1.53.1\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:37548)
  	at runTask (c:\Users\circleci\project\packages\particle-vscode-core\test\compilation.e2e.js:59:9)
  	at Context.<anonymous> (c:\Users\circleci\project\packages\particle-vscode-core\test\compilation.e2e.js:39:30)
  	at runMicrotasks (<anonymous>)
  	at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

the test is:

```js
const vscode = require('vscode');
const expect = require('chai').expect;
const sandbox = require('sinon').createSandbox();
const Project = require('../src/lib/project');
const fs = require('./lib/fs');
const {
	PATH_PROJ_STROBY_DIR,
	PATH_PROJ_STROBY_TARGET_DIR,
	PATH_PROJ_STROBY_CPP,
} = require('./lib/env');


describe('Compilation', () => {
	const { Uri, tasks, commands: { executeCommand } } = vscode;
	const projFolder = { name: 'stroby', uri: Uri.file(PATH_PROJ_STROBY_DIR) };
	const project = Project.create({ vscode, projFolder });

	before(async () => {
		await Promise.all([
			executeCommand('particle.installCLIDependencies'),
			executeCommand('particle.installToolchainDependencies', project.settings)
		]);
	});

	afterEach(() => {
		sandbox.restore();
	});

	after(async () => {
		await project.toolchain.uninstallAll();
		// TODO: we should copy test project to tmp dir then open it
		// but we're blocked on: https://github.com/microsoft/vscode-test/issues/38
		await fs.remove(PATH_PROJ_STROBY_TARGET_DIR);
		await fs.remove(PATH_PROJ_STROBY_CPP);
	});

	it('Compile application & DeviceOS (local)', async () => {
		const task = await project.getTask('Compile application & DeviceOS (local)');
		const { exitCode } = await runTask(task); // LINE: 39 as mentioned in the stacktrace above
		const contents = await getProjectDirContents();

		expect(contents).to.include.members([
			PATH_PROJ_STROBY_TARGET_DIR,
			PATH_PROJ_STROBY_CPP
		]);
		expect(exitCode).to.equal(0);
	});

	async function runTask(task){
		const { executeTask, onDidEndTaskProcess } = tasks;
		const promise = new Promise((resolve) => {
			onDidEndTaskProcess((event) => {
				if (event.execution.task.name === task.name){
					resolve(event);
				}
			});
		});

		await executeTask(task); // LINE: 59 as mentioned in the stacktrace above
		return promise;
	}

	async function getProjectDirContents(){
		return fs.getDirectoryContents(PATH_PROJ_STROBY_DIR, { maxDepth: 3 });
	}
});
```

...where the lines from the stacktrace are flagged w/ `// LINE:` above.

i'm using `vscode-test@1.4.0`.

any ideas? is there anything else i can provide to help troubleshoot?

**Comment by alexr00** [comment]
Can you provide a minimal sample that reproduces the issue?

**Comment by alexr00** [comment]
Maybe somehow related to this change?

**Comment by busticated** [comment]
@alexr00 thanks for taking a look :pray:

>I don't know what await project.getTask('Compile application & DeviceOS (local)'); is doing

ah, nice catch! here's the source for those - TL;DR it's just a wrapper around ` vscode.tasks.fetchTasks()` ([docs](https://code.visualstudio.com/api/references/vscode-api#tasks.fetchTasks))

```js
async getTask(taskName){
    const tasks = await this.getAllTasks();
    return tasks.find(t => t.name === taskName);
}

async getAllTasks(){
    // `folder` here is and instance of https://code.visualstudio.com/api/references/vscode-api#WorkspaceFolder
    // specifically: { name: 'stroby', uri: Uri.file(PATH_PROJ_STROBY_DIR) }; - as seen in the test code i shared
    const { folder, vscode: { tasks: { fetchTasks } } } = this;
    const tasks = await fetchTasks({ type: 'particle' });
    return tasks.filter(task => {
        const { scope } = task;
        return scope.uri.path === folder.uri.path;
    });
}
```

i re-ran CI with some additional logging and low and behold on `windows` the task is not found (`getTask()` returns `undefined`)

so, why might that be?

**Comment by busticated** [comment]
lol... i think i figured it out... 🤦 

here's the folder i create:

```
{
    "name": "stroby",
    "uri": {
        "$mid": 1,
        "external": "file:///c%3A/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby",
        "path": "/c:/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby",
        "scheme": "file"
    }
}
```

here's the task's "scope":

```
{
    "name": "stroby",
    "index": 0,
    "uri": {
        "$mid": 1,
        "fsPath": "c:\\Users\\circleci\\project\\packages\\particle-vscode-core\\test\\__fixtures__\\projects\\stroby",
        "_sep": 1,
        "external": "file:///c%3A/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby",
        "path": "/C:/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby",
        "scheme": "file"
    }
}
```

i create the folder instance like this:

```js
const PATH_PROJ_STROBY_DIR = path.join(__dirname, '..', '..', 'test', '__fixtures__', 'projects', 'stroby');
const projFolder = { name: 'stroby', uri: Uri.file(PATH_PROJ_STROBY_DIR) };
```

this results in a mismatch:

```
"/C:/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby" (what's in the task)
"/c:/Users/circleci/project/packages/particle-vscode-core/test/__fixtures__/projects/stroby" (what i'm trying to match on)
```

(`/C:` !== `/c:` 🤪)

so something changed between VSCode `v1.52.1` and `v1.53.0` such that `uri.path` drive label is capitalized differently between Node.js' `path.join()` / `__dirname` and whatever VSCode is using to build the absolute path.

worth noting that the `external` fields _do_ match so for now i guess i can just use that.

can't help but point out that if there was a more ergonomic way to retrieve a task by name or id, all of this path matching could be avoided in downstream code 🤗

**Comment by busticated** [comment]
victory 🎉 🎊 

<img width="1237" alt="Screen Shot 2021-02-12 at 1 29 50 PM" src="https://user-images.githubusercontent.com/367674/107824518-772c8500-6d36-11eb-821c-0c6ea468d957.png">

@alexr00 thanks again for the help - feel free to close this out if the drive letter / path casing difference i pointed out isn't more broadly concerning 👍

**Comment by alexr00** [comment]
Interesting. I don't think that the casing change came from within tasks code. 

@jrieken were there any URI changes recently that might have caused the drive letter casing to go to from lowercase in the `path` to uppercase?

**Comment by jrieken** [comment]
> @jrieken were there any URI changes recently that might have caused the drive letter casing to go to from lowercase in the path to uppercase?

No - the uri implementation is set in stone. Could this be a case where some code works with `UriComponent` and not with `URI`? The former is the wire/json format and often `URI.revive`-calls are missing. The symptoms described here would be typical for that.

**Comment by alexr00** [comment]
I can't find an issue with this in tasks land. When we get the task from the task provider extension, the uri is revived once it reaches the renderer: 

https://github.com/Microsoft/vscode/blob/aaf73920aeae171096d205efb2c58804a32b6846/src/vs/workbench/api/browser/mainThreadTask.ts#L286-L287

Then, when an extension calls `fetchTask`, we also revive the uri once the task has reached the extension host:

https://github.com/Microsoft/vscode/blob/82c629eb3a4360f4ba5a47668e7e973839b5f6e8/src/vs/workbench/api/common/extHostTask.ts#L301-L301

I'll need to see if I can repro, then debug through and try to find where a revive isn't happening.

@busticated is the task that you're comparing paths on coming from you? Can you share you task provider so I can try to repro?

**Comment by busticated** [comment]
@alexr00 yes, the task i'm trying to execute in my tests is contributed by my extension (`particle.particle-vscode-core`)

the code for the task provider is a bit hard to share on its own - probably the easiest thing is to just grab it from the marketplace:

https://marketplace.visualstudio.com/items?itemName=particle.particle-vscode-core

it ships as plain ol' unbundled / unmangled js atm 😅 

that task provider lives in:

```
C:\Users\me\.vscode\extensions\particle.particle-vscode-core-1.13.3\src\compiler\tasks.js
```

check out `.provideTasks()` which calls into `.createTasks()` to build up a series of `ShellExecution` tasks. 

happy to answer any questions from there 👍

**Comment by alexr00** [comment]
@busticated I started by taking a look at the task code. Nothing unusual there, so I tried to repro with VS Code's built in npm extension. All the drive letters looked fine.

I installed the particle extension, created a project, and ran this command:
```typescript
	const disposable = vscode.commands.registerCommand('extension.helloWorld', async () => {
		const tasks = await vscode.tasks.fetchTasks({type: 'particle'});
		for (const task of tasks) {
			console.log((<any>task.scope)?.uri.path);
		}
	});
```
All the drive letters were still fine (lowercase). Not sure what could be going wrong in your case, but I can't reproduce the uppercase drive letters in the `path`. There weren't many task changes in 1.53, so I don't have any other clues about what could be going wrong. Is there anything special about the folder in your setup?

**Comment by busticated** [comment]
@alexr00 hm. i'm really not sure. the `scope` for my tasks comes almost directly from `vscode.workspace.workspaceFolders` (just filtered to only those with a `project.properties` file at the root). when i `console.log()` them out, they use the lowercase drive letter (`c:`) as i'd expect.

total long-shot: is it somehow related to running within Windows Server (vs. Windows 10) ? looks like my CI uses "Windows Server 2019 Core Datacenter Edition" ([docs](https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image))

**Comment by alexr00** [comment]
I wouldn't expect Windows Server vs. Windows 10 to be a problem.

Given that I can't repro this and only one person has provided repro steps (thank you @busticated) I'd like to understand what the other folks who have 👍 this issue are doing when they see this issue.

Folks who 👍 this issue (I assume you're following the issue), do you have alternate repro steps?
