### ISSUE TITLE
CTRL+C Copy function with empty selection should not override existing copied content in the memory. only if there is selection it should replace the content.  

### ISSUE THREAD

**Issue by vigikaran** [Microsoft/vscode#11629]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
When there is no explicit selection by the user, the inferred selection is the current line by design. Adding @alexandrudima for more insights.

**Comment by alexandrudima** [comment]
Let's track in #11112. 

@vigikaran Don't forget to upvote the issue
