### ISSUE TITLE
Problems not showing

### ISSUE THREAD

**Issue by Bkmaxx** [microsoft/vscode#116292]
Issue Type: <b>Bug</b>

I made a mess while programming i  accidently disabled yellow bulb and from then errors are not visible in problem window 
before running it .as before eroors were visible even before running it

$Please Help!!

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.45GB (0.66GB free)|
|Process Argv|--crash-reporter-id b05b286e-fd74-4c61-a4d6-a6bdc80a0109|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
code-runner|for|0.11.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
material-icon-theme|PKi|4.5.0
xamarin-debug|vad|0.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by meganrogge** [comment]
What happens if you run the command `workbench.panel.markers.view.focus` in the command pallette?
