### ISSUE TITLE
Install extensions from terminal with a file

### ISSUE THREAD

**Issue by yogaxpto** [microsoft/vscode#116304]
Hello.

I think it would be interesting to have some terminal command that could also install multiple extensions from a file like "extensions.json". 
My idea would be to have something like
`code --install-extension extensions.json`

**Comment by yogaxpto** [comment]
@sandy081 can you link the original please?

**Comment by sandy081** [comment]
I am sorry that I cannot find quickly but I am sure I came across this feature request.
