### ISSUE TITLE
Show DAP's new "ExceptionBreakpointsFilter.conditionDescription" as placeholder in condition text box

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#116348]
With https://github.com/microsoft/debug-adapter-protocol/issues/164 a new optional property `conditionDescription` has become available on the `ExceptionBreakpointsFilter`.

This feature request asks for showing this property as the placeholder text in the condition's text box.

**Comment by isidorn** [comment]
This makes good sense.
@weinand do you plan to add this to the Mock-debug? If yes then I can look into adding this to the client.

**Comment by weinand** [comment]
@isidorn done. The "named exception" got a "conditionDescription" attribute.
