### ISSUE TITLE
VPAT to enable US Federal Agencies to use vscode

### ISSUE THREAD

**Issue by jonathanfspencer** [microsoft/vscode#116367]
Please create a VPAT specifically for vscode.  I see that there is a closed issue related to this (https://github.com/microsoft/vscode/issues/12082), but there is not a VPAT listed at https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/.  I have contacted edad@microsoft.com to ask for a VPAT, but they were only able to provide them for Visual Studio 2019 and for the Elements for Visual Studio plug-in.  Without a vpat, my agency will not allow our developers to use vscode.

**Comment by sana-ajani** [comment]
@jonathanfspencer thanks for filing an issue! We've made the accessibility conformance report for VS Code public now. https://cloudblogs.microsoft.com/industry-blog/government/2018/09/11/accessibility-conformance-reports/
