### ISSUE TITLE
Remember Merged Windows Between Launches

### ISSUE THREAD

**Issue by xiata** [microsoft/vscode#116343]
Due to the nature of having a lot of repositories open, I frequently find myself using the Window -> Merge All Windows command, since I don't use tabs for open files, but tabs for open repositories. Definitely a different workflow than the standard workflow, but I find it works nicely since the sidebar has an Open Editors list.

When VS Code Starts, it doesn't remember that I had all the windows merged. Can it remember between launches what windows were merged together? I didn't find any relevant settings that would control it when searching preferences.

![image](https://user-images.githubusercontent.com/1434508/107535023-5f1a0180-6b8e-11eb-821d-3f04d6fe5663.png)

**Comment by bpasero** [comment]
This is not possibly to do for us currently pending https://github.com/electron/electron/issues/18138
