### ISSUE TITLE
Support for markup languages

### ISSUE THREAD

**Issue by EESaldana** [Microsoft/vscode#11631]
- VSCode Version: 1.4.0
- OS Version: Windows 10 1511

Steps to Reproduce:

1. When editing markup language, specifically HTML and XML, there is no single tool that lets me know I left a tag open.
2. There is no vertical line or link to travel from the closing tag to the opening tag, so it is almost imposible to see which closing tag closes which open tag if they are not in the same screen.

**Comment by ramya-rao-a** [comment]
For your first issue, have you tried the [HTMLHint](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint) extension?

For the second, clicking on a tag gives both the opening and the closing tags a highlight, so that should help.
