### ISSUE TITLE
flaky smoke tests

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#116362]
[happened again](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=104399&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094)

**Comment by sandy081** [comment]
TBH I do not know what went wrong here and there are other smoke test failures which I do not own. I see all of them are running fine locally.

Since there is no action can be taken, closing this.
