### ISSUE TITLE
Labels are wrong on non-Windows -> Windows remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#116395]
![image](https://user-images.githubusercontent.com/323878/107594151-18e09480-6bc6-11eb-88b6-a6e3d8023cc4.png)

After https://github.com/microsoft/vscode/issues/114203 we don't properly consider cross-OS paths

**Comment by isidorn** [comment]
@roblourens thanks for reporting
Haha it is hilarious how many issues I have caused with this simple change
@bpasero is it ok if I add a flag to the `hasDriveLetter` helper function to ignore `isWindows` check

**Comment by roblourens** [comment]
Backslashes and drive letters are the biggest mistake in computing history

**Comment by bpasero** [comment]
@isidorn not sure I understand, but we have a utility service that helps you figure out the `IPath` for a scheme correctly from the remote:

https://github.com/microsoft/vscode/blob/528b473dba12e696213c747f3b710981cd32d30d/src/vs/workbench/services/path/common/pathService.ts#L30-L30

I think the method should respect this.

**Comment by isidorn** [comment]
@bpasero thanks, but for the labels I simply need a custom solution that will figure out if the path has a drive letter even if the platform is not windows - since the uri can come from EH running on Windows.
Thus bringing back my custom method.
