### ISSUE TITLE
I need help as vscode, don't want to show the syntax errors.

### ISSUE THREAD

**Issue by MohaMBS** [microsoft/vscode#116386]
- VS Code Version:1.53.1
![image](https://user-images.githubusercontent.com/72398757/107584006-0a14d480-6bfc-11eb-978d-4963726ed140.png)

- OS Version:Windows 10 Pro

Steps to Reproduce:

1.Open the VSCode
2.And strart coding.

Does this issue occur when all extensions are disabled?: Yes/No
YES

I am using a clean version of VSCode, and writing wrong syntax does not show me where the error is.
Here is a video:

https://user-images.githubusercontent.com/72398757/107584325-83acc280-6bfc-11eb-8389-1b580081a1ba.mp4

**Comment by dbaeumer** [comment]
@MohaMBS you need to install a C# extension from the marketplace to make this work. If you have install it then please report issues with the extension here: https://github.com/OmniSharp/omnisharp-vscode

**Comment by MohaMBS** [comment]
I know and I had it. But it still didn't work...
I leave you my solution which works, reinstall / factory reset windows 10.
The problem is Windows.... Agian :(
