### ISSUE TITLE
Title menu bar goes hiddin on changing "title menu style" from custom to native  

### ISSUE THREAD

**Issue by rahulraikwar00** [microsoft/vscode#116329]
- VS Code Version: 1.53.1
- OS Version: garuda linux 1.4
- system : acer swift 3

issue : title menu bar goes hiddin on changing "title menu style" from custom to native  
Steps to Reproduce:
1.  go to the title memu style
2. change custom to  native

**Comment by sbatten** [comment]
can you share a screen cap of your experience?

**Comment by rahulraikwar00** [comment]
![vscodebug](https://user-images.githubusercontent.com/54519734/107595844-dce81680-6c3b-11eb-866d-1482790b69b1.png)

**Comment by rahulraikwar00** [comment]
After changing settings to custom

![bug2vscode](https://user-images.githubusercontent.com/54519734/107595897-102aa580-6c3c-11eb-848c-58705c953f53.png)

**Comment by sbatten** [comment]
Those screenshots show the expected behaviour. Custom moves the menubar to the titlebar of the app. It can be used on Linux but is not recommended if the Linux distro provides a global application menu.
