### ISSUE TITLE
No updates for VS Code Exploration (macOS, ARM)

### ISSUE THREAD

**Issue by pck1980** [microsoft/vscode#116328]
- VS Code Version:  1.53.0-exploration
- OS Version: macOS 11.2.1

Steps to Reproduce:

1. Check for updates

Does this issue occur when all extensions are disabled?: Yes/No
Yes

I downloaded the macOS preview release with support for Apple silicon some time last year and got frequent updates for it. Now, there hasn't been an update for quite some time, the last one matches the version number of the latest stable version, so my guess was that with the release of a new stable build, the "exploration edition" was automatically switched to the stable branch.
But today, 1.53.1 was released, and even if I manually search for updates, it is not found.
Does this simply take some time or has the exploration build become unsupported?

**Comment by bpasero** [comment]
Exploration is currently not updated until we work on Electron 12, please switch to insiders.

**Comment by deepak1556** [comment]
Sorry about that, this was mentioned here https://github.com/microsoft/vscode/issues/106770 but yes please switch to insiders line for apple si support. Exploration builds will continue to roll updates after Electron 12 has been picked up next iteration.

**Comment by pck1980** [comment]
Thanks for the replies. If possible, it would be great if users of Exploration would get some notification to switch to Insiders, because they might miss security updates without noticing.
