### ISSUE TITLE
PHP heredoc - defined string without color

### ISSUE THREAD

**Issue by Jarda-H** [microsoft/vscode#116369]
- VS Code Version: 1.53.1 
- OS Version: Windows_NT x64 10.0.19042

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/62809719/107558446-1177b600-6bdb-11eb-8a86-d50f138cab34.png)
No different color for value in heredoc string. **${string}** or **{$string}**

**Comment by roblourens** [comment]
I think this is essentially covered by https://github.com/microsoft/vscode/issues/98965
