### ISSUE TITLE
New files are saved as Batch file instead of Plain Text

### ISSUE THREAD

**Issue by orobert91** [microsoft/vscode#116392]
Issue Type: <b>Bug</b>

1. Open VS Code.
2. Create new file (File -> New File)
3. Save the file (File -> Save (or Save As...))
4. "Batch (*.bat; *.cmd)" is selected as the default format instead of the expected "Plain text (*.txt)."

Why does VS Code thinks the file is a batch file when not a single line of text is written? It is quite an annoyance when using VSCode as the main editor for text files. I don't see any settings to change that, except the default language.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (11.49GB free)|
|Process Argv|--crash-reporter-id c683bdfb-a390-48ef-bf38-aabf82923ff7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in upcoming 1.53.2
