### ISSUE TITLE
New feature in status Bar which shows Red/Yellow/Green dot(Circle) when code is compiled in terminal.

### ISSUE THREAD

**Issue by surajkrishan** [microsoft/vscode#116368]
Hi Team,

it would be great to see a new feature in vs code where we can see code compilation status in the form of a color circle (Red/Yellow/Green) in the status bar.

Red - for compilation error.
Yellow - for warnings in the console.
Green - for the code compiled successfully with no warnings.

I have attached a screenshot for reference.

![1](https://user-images.githubusercontent.com/32816421/107557142-3bdb6a80-6bff-11eb-883d-2763609c2603.jpg)

I think this will reduce the time as every time we have to switch back & forth to the terminal (ctrl+`) to see if code is compiled or not in the terminal. but once this feature gets implemented we can easily see the code compilation signal in the status bar.

Thanks,
Suraj

**Comment by Tyriar** [comment]
While we can't tell if something failed within the shell, we are planning on adding a similar feature in v1.56 with tabs where terminals can have status icons on their tabs. The statuses we're thinking about adding are:

- Busy (in background and something happened)
- Task running
- Task failed
- Task succeeded
- etc.

See https://github.com/microsoft/vscode/issues/10546
