### ISSUE TITLE
Native Notebooks - Diffing 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#116350]
Forwarding customer bug: https://github.com/microsoft/vscode-jupyter/issues/4736

## Expected behaviour
When viewing diffs of a notebook, when the outputs are the same, the diff viewer should not show that output has changed.

## Actual behaviour
Even when output of the notebook versions is the same, the diff viewer shows that output has changed. That is technically true because the outputId attribute in the output json has changed, but fundamentally the output is the same.

![image](https://user-images.githubusercontent.com/19276747/107543651-4275cd80-6b7e-11eb-930a-a4d5f05a4f80.png)

![image](https://user-images.githubusercontent.com/19276747/107543673-47d31800-6b7e-11eb-8ad0-5582d36e99e3.png)

While it might be useful to see that the notebook cell has been executed, I guess it should be an option to let the user see what they want out of the diff viewer - whether the cell has been executed (even if it gave the same result), or whether the actual output is different.

Without this, viewing diffs of tables/large outputs is difficult.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/115044
