### ISSUE TITLE
[loc][Query][VSCode] Please clarify the meaning of the string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#11635]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
REPL Accept Input

File Name:
src\vs\workbench\parts\debug\electron-browser\repl.nls.resx

Resource ID:
".resx", 0; "actions.repl.acceptInput"

Query:
Please clarify meaning. 	CnE_Developer_Moravia_ITA1@hotmail.com	9/5/2016 1:23:12 PM

**Comment by isidorn** [comment]
REPL is a common term for a read–eval–print loop - that is our debug console.
Accept input means just to apply the current input from the debug console input box.

I have also added a comment to the term so the meaning is clearer in the future.
