### ISSUE TITLE
Resizing text via editor font size causes CPU spike

### ISSUE THREAD

**Issue by oatymart** [microsoft/vscode#116312]
- VS Code Version: 1.52.1
- OS Version: Mac OSX 10.15.6

Steps to Reproduce:
1. Open any document in VS Code
2. Press Cmd-+ to increase font size by one step
3. Observe very noticeable sluggish performance, high fan usage, CPU spike which does not die down

OR:
1. same
2. Open Settings and change Editor Font Size to any value other than 12
3. same

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@oatymart I could not reproduce the sluggishness you describe by simply changing the editor's font size. Could you please create a JavaScript CPU Profile using the steps documented at https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process ? That might help show where the time is being spent.

**Comment by oatymart** [comment]
CPU profiled while reproducing issue, attached.

[CPU-20210305T132151.cpuprofile.txt](https://github.com/microsoft/vscode/files/6090445/CPU-20210305T132151.cpuprofile.txt)

@vscode-triage-bot re-open please

**Comment by alexdima** [comment]
@oatymart

**Comment by deepak1556** [comment]
Yeah the long layout tasks on window resize definitely indicates some weirdness in the compositor. Can you obtain another trace following these steps

* Create trace.json somewhere on your disk with the following content:
```
{
 "result_file": "/tmp/chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "blink",
     "benchmark",
     "gpu",
     "cc",
     "toplevel",
     "viz",
     "v8",
     "disabled-by-default-viz.gpu_composite_time",
    "disabled-by-default-viz.quads",
 ],
 "excluded_categories": ["*"]
 }
}
```
* Start `code --trace-config-file=<full-path-to>/trace.json`
* Replicate the slowdown scenario on resize
* Quit the editor
* Attach the generated chrometrace.log at `/tmp`

**Comment by oatymart** [comment]
I tried the above steps but it says

> Warning: 'trace-config-file' is not in the list of known options, but still passed to Electron/Chromium.

and doesn't generate any file in `/tmp`.

**Comment by oatymart** [comment]
Regarding GPU, my screen is a standard 15.4" Macbook Pro screen at 2880x1800, no special zoom factor.

Another thing is that I frequently work with >10 instances of VSCode open on different workspaces. But the issue is reproducible when all instances but one are hidden (minimised to the Dock). If they are minimised, there's no way the GPU would be spending cycles to font-resize them, right?

**Comment by deepak1556** [comment]
> I tried the above steps but it says

Can you paste the command you had tried. The warning can be safely ignored.

**Comment by oatymart** [comment]
> Can you paste the command you had tried. The warning can be safely ignored.

`code --trace-config-file=trace.json`

also tried other variants of the file path, other tempfile locations, other included_categories and excluded_categories.

**Comment by deepak1556** [comment]
The path to trace config file needs to be absolute, `code --trace-config-file=/tmp/trace.json`

**Comment by oatymart** [comment]
> The path to trace config file needs to be absolute, `code --trace-config-file=/tmp/trace.json`

I have tried that as well, believe me. It opens Code, I close Code, no file is written anywhere.

**Comment by alexdima** [comment]
@oatymart One thing that might happen which also sometimes tricks me is that all instances of vscode need to be closed. The app must be completely quit, otherwise the code CLI just connects to the running code instance.

**Comment by oatymart** [comment]
Even with all instances closed and the app fully terminated, launching with the flag and trace.json doesn't generate output.

The slowdown isn't reproduced when I have only 1 instance of the app. It seems to be linked to the number of windows (even if most of them are offscreen, hidden, minimised).

I probably won't spend more time digging into it. Thanks anyway.

**Comment by deepak1556** [comment]
@oatymart not sure why the trace config was not working for you, sorry about that, verified that it works on my system. Can you help taking a sample of the process that is showing a cpu spike.

* Open activity monitor
* Click the process that is problematic and then in settings select sample process

<img width="949" alt="Screen Shot 2021-03-29 at 8 28 08 PM" src="https://user-images.githubusercontent.com/964386/112929612-a2dcb200-90cd-11eb-96a9-fcaa845737e3.png">
