### ISSUE TITLE
Open editor entry shifts click position in explorer pane

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#116351]
Issue Type: <b>Bug</b>

When opening a file from the explorer pane with double clicking, there used to be (and still is in the stable 1.53.1 version) a slight delay before the newly opened file appears in the open editors pane above. However in the current Insiders release, the entry is added immediately. As long as the open editor pane isn't overflowing, this will shift all entries in the explorer pane down, hence resulting in the second click being picked up by the entry above the originally clicked one.

Opening a file with a file above will therefore open the file and instantly preview the file above as well.
Opening a file with a folder above will toggle the folder state and so on.

VS Code version: Code - Insiders 1.54.0-insider (cd97629c4458c05b16a1fd444d21c61295ba2529, 2021-02-09T08:37:01.449Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.69GB free)|
|Process Argv|--crash-reporter-id 0aa4a008-3a7d-4569-9e3b-f1c8e16c283b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce running out of sources on macOS at least.

**Comment by isidorn** [comment]
I can only reproduce this if I set the following setting

```
"workbench.editor.enablePreview": false
```

However I can also reproduce this behaviour in VS Code stable. Thus nothing seems to have changed
@vainamov is this what you are seeing as well?

**Comment by bpasero** [comment]
Yeah that is expected, relevant code that handles this is:

https://github.com/microsoft/vscode/blob/c11bf9d7dfd561c618b3793e5cd11e4557767c0d/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L207-L232

**Comment by vainamov** [comment]
> 
> 
> I can only reproduce this if I set the following setting
> 
> ```
> "workbench.editor.enablePreview": false
> ```
> 
> However I can also reproduce this behaviour in VS Code stable. Thus nothing seems to have changed
> @vainamov is this what you are seeing as well?

Yes, that seems to be the case. `workbench.editor.enablePreview` is enabled in my stable installation but not in the Insiders. That however is a bit mysterious, since they share settings via my GitHub account and were previously configured exactly the same.

**Comment by bpasero** [comment]
@vainamov I believe we end up syncing to a different service when you use insiders compared to stable, but that is configurable.

**Comment by vainamov** [comment]
Because @bpasero was a bit faster than I could edit I make this a seperate reply:

I don't really mind having the preview enabled to circumvent this, but with the setting disabled, I find requiring a single-click to open counter-intuitive. I think the ability to choose between single and double clicking for opening files would be a welcome addition here.

**Comment by vainamov** [comment]
> 
> 
> @vainamov I believe we end up syncing to a different service when you use insiders compared to stable, but that is configurable.

Ah that might be it, thanks for the explanation!
