### ISSUE TITLE
Go to File menu problem - Always open a new file at the same tab

### ISSUE THREAD

**Issue by elirenato** [Microsoft/vscode#11639]
Sometimes when you use Go->Go to File menu, instead of open the file that you searched in a new tab the VSCode always open the file in a tab that is already open.

Please see the attached image.

[VSCode-GoToFileBug.m4v.zip](https://github.com/Microsoft/vscode/files/459548/VSCode-GoToFileBug.m4v.zip)

- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

We don't have an exactly flow to reproduce the bug, just open a folder with multiple files, type the name of the file using the Go to File, repeat this action and sometime you will see this problem.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`

**Comment by elirenato** [comment]
I will use this settings, thanks!
