### ISSUE TITLE
Visual Studio Code extremely slow

### ISSUE THREAD

**Issue by cforce** [microsoft/vscode#116379]
I updated today on the recent version of vscode and since that it gut unusable because its incredible slow - call it frozen most of the time..even dialogs to visual feedback "clicks" or menu selection take a minute or more.
![image](https://user-images.githubusercontent.com/393286/107570566-011b0780-6bea-11eb-847b-19c0122a29d1.png)
![image](https://user-images.githubusercontent.com/393286/107570672-290a6b00-6bea-11eb-8448-3feec5359d88.png)
[redhat.java-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode/files/5961513/redhat.java-unresponsive.cpuprofile.txt)

Looking into the taskmanager there are enough resources .- can't say where this interrupts coming from. Everything else in my system is running at "normal" speed at the same time.

**Comment by cforce** [comment]
Rolling back from plugin 0.74.0 (which was working vscode before 1.53.1 )  to 0.73.0 ..vscode is not completly unusable  but not acceptable usable (only if your boss pays your to have a coffe after each click or key stroke to wait for vscode to react)

**Comment by cforce** [comment]
Why is this closed?? The bug is still unresolved. The problem is not the plugin. The issue started with vscode 1.53.1. Wth prior versions all works as expected, no matter which version of the redhat plugin. Even not sure if redhat plugin is the root cause at all. Maybe its juts the only plugin that was fast enough to complain by error message before the whole thing is froozen and i need to kill the process.
Pleas reopen my issue. This is a blocker.. and no dupe of Appl1 MC stuff. I haven neither Apple nore do i see more than 23% cpu usage ..while the issue freezes my VsCode. i can't any longer use vscode.

**Comment by deepak1556** [comment]
Do you have the issue when you run with `--disable-extensions` ? If so, please provide the output of `code --status` and also the following profile https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process
