### ISSUE TITLE
Save As dialog with a plain text file has 'Save as type' default to the wrong type

### ISSUE THREAD

**Issue by AndrioCelos** [microsoft/vscode#116390]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Make sure an untitled file is open and set to 'Plain Text' (`Ctrl`+`N` if necessary).
2. Open the Save As dialog using `Ctrl`+`S`.

Expected result: the 'Save as type' field should default to `*` or `*.txt`
Observed result: it defaults to the topmost non-'All files' type in the list, potentially hiding most files that shouldn't be hidden.

This issue occurs both on the release build and the Insiders build with extensions disabled.

VS Code version: Code - Insiders 1.54.0-insider (cd97629c4458c05b16a1fd444d21c61295ba2529, 2021-02-09T08:37:01.449Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.28GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 2fa2b299-feb4-4e39-b908-4ae6c670137c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AndrioCelos** [comment]
This issue may be related, but is not a duplicate of that one.

**Comment by gjsjohnmurray** [comment]
Are you certain that you have the latest Insiders? I thought this problem had already been fixed.
