### ISSUE TITLE
Show DAP's new "ExceptionBreakpointsFilter.description" property in a hover 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#116347]
With https://github.com/microsoft/debug-adapter-protocol/issues/164 a new optional property `description` has become available on the `ExceptionBreakpointsFilter`.

This feature request asks for showing this property when hovering over an exception filter in the BREAKPOINTs view.

**Comment by isidorn** [comment]
Same as the other one, if you add this to Mock-debug would be great so I can try it out and add it.

**Comment by weinand** [comment]
@isidorn done. The "named exception" got a "description" attribute.

**Comment by isidorn** [comment]
@weinand great, thanks

**Comment by isidorn** [comment]
Adding verification needed so we get this verified in endgame.
