### ISSUE TITLE
Wrapped tabs are broken on portrait mode in macOS

### ISSUE THREAD

**Issue by martin-braun** [microsoft/vscode#116385]
Testing #114827

The tabs stop being wrapped when opening some files or closing some tabs. The issue appears randomly. I suspect the bug triggers on specific tab widths. 

Visual demonstration:

![2021-02-10 23 28 44](https://user-images.githubusercontent.com/24259245/107581218-0a12d580-6bf8-11eb-869f-e63cd3c868a5.gif)

**VSCode**
```
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:35:15.302Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

macOS v11.2.1 (20D74)
MacBook Pro (16-inch, 2019)

**Comment by bpasero** [comment]
@martin-braun can you provide me access to a repository and exact steps for how to reproduce this? We have some conditions under which wrapped tabs will stop to wrap and I wonder if we accidentally hit it here.

**Comment by martin-braun** [comment]
@bpasero It happens with any project. But I experimented a little bit and found the cause of the problem. I zoomed out of my VSCode using `CMD` + `-`, once. So it seems to be a pixel perfect precision issue, the math isn't working out for wrapped tabs when you zoom in or out. 

To reproduce:

- Open and empty folder
- Zoom out using CMD` + `-` (your UI gets smaller in VSCode)
- Create some folders and files
- Start opening all files so you get more rows on the tabs
- Now start closing tabs and re-opening some closed files OR
- Just resize the window and you will hit the golden spot when it breaks:

![2021-02-12 00 57 31](https://user-images.githubusercontent.com/24259245/107714310-57ad4200-6ccd-11eb-9f83-2e067ba6af40.gif)

You have to try a little bit until you catch it.

**Comment by bpasero** [comment]
OK thanks I will try to reproduce, might be hard. Open for help if anyone wants to chime in and diagnose.

**Comment by bpasero** [comment]
I think this is entirely related to zooming as it only seems to reproduce with a zoom level of -1. We have a heuristic to disable wrapping tabs when we think that the last tab is large enough that the editor action toolbar is overlapped. With zooming I am seeing some rounding errors when determining this overlap. As a mitigation I pushed a change to allow for up to 1px overlap.
