### ISSUE TITLE
Scrollbar is very narrow

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#116338]
* Have an error in TypeScript
* Dragging the scrollbar with the mouse is difficult because the scrollbar is very short:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/107532735-7d97f100-6bbe-11eb-8ccf-c8474759c226.gif)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/91321

**Comment by alexdima** [comment]
@sandy081 I see how this is related to #91321 but I'm not asking to change any behavior in wrapping logic or anything like that (what is discussed in #91321). I'm just asking that the logic is completely kept as is, but that the horizontal scrollbar size is increased. This issue can be considered an accessibility bug because it is very difficult to click on the slider and see the full error when using a mouse. On macOS, on a touchpad you can scroll with the touchpad to the right, so I can see how you would not think it's a big deal, but with a mouse on Windows you end up needing to click that slider to scroll. So please reconsider that only the size of the scrollbar can be increased without dragging all the baggage (that probably will never be addressed) from #91321.

**Comment by sandy081** [comment]
@alexdima I thought #91321 is mainly about making increasing the size of scrollbar, but I see it also got discussed about wrapping.

**Comment by Kile-D-Asmussen** [comment]
This is a very real accessibility issue.

**Comment by jrieken** [comment]
I have pushed a fix to double the size of the scrollbar. This is how it now looks

<img width="446" alt="Screen Shot 2021-11-04 at 11 57 03" src="https://user-images.githubusercontent.com/1794099/140302178-b5c4500b-101a-480c-acfd-fb351e7d60d7.png">
