### ISSUE TITLE
Location of Manage Trusted Workspace in Gear menu feels wrong

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#116349]
The `Manage Trusted Workspace` menu entry breaks my muscle memory for restart to update. Maybe we should move it just above the update section, or just below the settings+extension section.

![image](https://user-images.githubusercontent.com/6561887/107540888-65eb4900-6b7b-11eb-8f2f-431d0bf440af.png)

**Comment by lszomoru** [comment]
Hm. I am leaning towards moving it above the update section however that could also be problematic as one could build muscle memory that managing workspace trust is always at the bottom, yet that is not trust when there is an update available.

**Comment by sbatten** [comment]
The update entry "Check for updates" would still exist though so I think that's okay?

**Comment by lszomoru** [comment]
doh! 🤦🏻 I will move the menu as I am making a small change to the menu either way.

**Comment by lszomoru** [comment]
Fixed with 20b8e5fddd203964e164ddaac99664dfc2f3a544
