### ISSUE TITLE
File path in terminal broken up by space

### ISSUE THREAD

**Issue by jackHedaya** [microsoft/vscode#116366]
- VS Code Version: 1.53.1
- OS Version: Big Sur (11.1)

Steps to Reproduce:

1. Print directory path in integrated terminal which includes space. For example `/Users/<user>/Desktop/Hello World/index.js`
2. Notice that when clicking on the highlighted path, `/Users/<user>/Desktop/Hello` and `World/index.js` will be treated as different urls.

Does this issue occur when all extensions are disabled?: **Yes**/No

**Comment by meganrogge** [comment]
Duplicate of #97941

**Comment by jackHedaya** [comment]
Ah that's my bad –– thank you
