### ISSUE TITLE
Sandbox background process architecture

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116337]
From discussion today in standup here are suggestions for the sandbox architecture:
* leverage the existing shared process as much as possible (make it robust, start fast and have logging for crashes)
* keep main process usage as little as possible
* aggressively move things over to shared process (e.g. logger, sqlite?)
* investigate into turning the shared process into a lightweight node.js process with `MessagePort` support and access to Electron's proxy solution for network requests (if we cannot get proxy support here, we could think about doing ad-hoc hidden windows for network requests as a workaround)

![image](https://user-images.githubusercontent.com/900690/107609686-0014c500-6c40-11eb-87fb-b0a7b6227fd7.png)

**Comment by Tyriar** [comment]
Won't this delay terminal creation for several seconds after start up? That was the main reason for keeping this out of Shared Process. Is this temporary based on whether we can make it node or when we get message port support would be move it to be a child of main?

**Comment by bpasero** [comment]
@Tyriar once we let the shared process be the parent of the `pty-host` we will no longer delay startup. This can easily be controlled here:

https://github.com/microsoft/vscode/blob/e371faebfb679ca0dcdb61f4f2f33b3d69922a77/src/vs/code/electron-main/app.ts#L458-L462

**Comment by bpasero** [comment]
After discussion in the Electron sync yesterday, here is a revised diagram given @deepak1556 feedback that the new process architecture will not provide `MessagePort` support for child processes spawned from the shared process. That means, all communication from the window will have to go through the shared process and then into the child processes:

![image](https://user-images.githubusercontent.com/900690/108161149-bc600680-70ea-11eb-8769-de6e403e555a.png)

**Comment by bpasero** [comment]
Merged into https://github.com/microsoft/vscode/issues/92164.
