### ISSUE TITLE
Test failure in TerminalCommandTracker

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116321]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=104335&view=ms.vss-test-web.build-test-results-tab

**Comment by michaelsync** [comment]
we can't access the link.

**Comment by Tyriar** [comment]
Haven't seen any flakiness on this test since. The link says it was a 5s timeout, I reviewed the code and it seems unlikely that would happen so guessing it was a one-off flake, the only async part is `writeP` which is very simple.
