### ISSUE TITLE
Newline code is forced to CRLF when saving a file.

### ISSUE THREAD

**Issue by kemo14331** [microsoft/vscode#116357]
Issue Type: <b>Bug</b>

## Process
1. Select LF as the line feed code from the status bar.
2. Save the file

## Expected results
The newline code of the file will be saved as LF.

## Actual result
The newline code of the file will be saved as CRLF.

VS Code version: Code - Insiders 1.54.0-insider (cd97629c4458c05b16a1fd444d21c61295ba2529, 2021-02-09T08:36:56.595Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.10GB free)|
|Process Argv|--crash-reporter-id cff84bdf-0f43-4dd6-9871-31666becd93b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
language-mcfunction|arc|0.17.0
mc-datapack-utility|Che|1.5.0
EditorConfig|Edi|0.16.4
fish|gio|0.0.4
vscode-language-pack-ja|MS-|1.53.2
code-eol|soh|0.3.3
datapack-language-server|SPG|3.3.0
gitmoji-vscode|Vtr|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo - in particular, does this happen after you reload with all extensions disabled?

**Comment by kemo14331** [comment]
Sorry, I disabled EditorConfig, and the problem went away.
