### ISSUE TITLE
Duplicated keybinding preventing to paste in terminal

### ISSUE THREAD

**Issue by lachaib** [microsoft/vscode#116331]
Issue Type: <b>Bug</b>

Hello,

This week I have an issue with keybindings, probably due to some new action.
Both Terminal: Paste into Active Terminal and Terminal: Switch Terminal are configured with keybinding Cmd+V and the same When clause (terminalFocus && terminalProcessSupported), I end up not being able to paste into the terminal and it's a major waste of time...

VS Code version: Code - Insiders 1.54.0-insider (afd102cbd2e17305a510701d7fd963ec2528e4ea, 2021-02-08T05:12:01.280Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.19.121-linuxkit
Remote OS version: Linux x64 4.19.121-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|-psn_0_6567491 --crash-reporter-id 2dfd00f5-9d02-4e2f-88c2-1becf952cbb1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: ****|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (4 x 2000)|
|Memory (System)|5.81GB (0.39GB free)|
|VM|0%|

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|eam|0.3.1
remote-containers|ms-|0.158.0
atlascode|atl|2.8.5
gitlens|eam|11.2.1
vscode-pull-request-github|Git|0.23.0
vscode-test-explorer|hbe|2.19.5
plantuml|jeb|2.14.3
vscode-python-test-adapter|lit|0.6.6
vscode-docker|ms-|1.9.1
python|ms-|2021.3.552933405-dev
vscode-pylance|ms-|2021.2.0
jupyter|ms-|2020.12.414227025
vscode-yaml|red|0.14.0

</details>

**Comment by meganrogge** [comment]
Did you configure Terminal: Switch Terminal to have the keybinding of Cmd+V? That doesn't happen by default

**Comment by lachaib** [comment]
Hello,

no, I checked that before I opened the ticket 😉 

![image](https://user-images.githubusercontent.com/26120426/107624407-1a0fd100-6c5b-11eb-8f7a-4de216052ccb.png)

I'm using vscode insiders and have this behaviour both inside and outside remote-container, so I assume it's really vscode that causes this issue

**Comment by meganrogge** [comment]
What happens if you change the keybinding of switch terminal?

**Comment by lachaib** [comment]
Then I can paste again, but this isn't convenient if all users have to change the keybindings, that's why I've opened the ticket.
Cmd+Shift+V is the new binding I use so maybe it can become the default for this action.

By the way, I am not sure what Switch Terminal is supposed to do but I see no effect to this action when I trigger it.

**Comment by meganrogge** [comment]
When you have multiple tabs open, Switch Terminal toggles between the tabs.

**Comment by Tyriar** [comment]
Updating insiders should fix this.

/duplicate 
![image](https://user-images.githubusercontent.com/2193314/107860554-b4efe300-6df4-11eb-828f-42552ad7d34a.png)
