### ISSUE TITLE
[scss] Syntax highlighting breaks on rules places after a nested selector

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#11633]
- VSCode Version: 1.4
- OS Version: OSX

The syntax highlighting breaks on rules places after a nested selector of any type:

![image](https://cloud.githubusercontent.com/assets/2827047/18343362/5ea1b020-75b3-11e6-9ba2-efd2d6882a88.png)

**Comment by aeschli** [comment]
Coloring of `font-size: 14px;` seems to look right.

Are the following rules ('will-change...) inside a selector?
Maybe best if you copy the full example...

**Comment by ivancuric** [comment]
Wrong reproduction steps. The syntax highlighting breaks on rules places after a nested selector of any type:
![image](https://cloud.githubusercontent.com/assets/2827047/18343275/00868dda-75b3-11e6-907b-460b075b942e.png)

**Comment by aeschli** [comment]
@ivancuric If you still have the snippet at hand, it would be great if you could paste it here.

**Comment by aeschli** [comment]
Seems to be fixed in the meantime. Verified in the January build.
![image](https://cloud.githubusercontent.com/assets/6461412/22697166/f0c56e32-ed50-11e6-8a2e-b1c6fac9da76.png)
