### ISSUE TITLE
Notebook text output should support the word wrap setting

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#116355]
As shown in this screenshot, the editor will wrap the editor text. 

![image](https://user-images.githubusercontent.com/19672699/107547450-50c5e880-6b82-11eb-80a3-4b70c18f4d5e.png)

However it doesn't wrap the text output. This makes it hard to read as described here:
https://github.com/microsoft/vscode-jupyter/issues/1501

**Comment by kylrth** [comment]
Sorry to ping, but this issue still exists for me. I don't see a setting anywhere to get the text output to wrap. This is an important difference in behavior from the standard jupyter notebook display in the browser, which makes it hard to use notebooks created by others.

**Comment by starball5** [comment]
Note that there is the `notebook.output.wordWrap` setting.

See also https://github.com/microsoft/vscode-jupyter/issues/13510, [How can I prevent output lines from wrapping in VS Code Jupyter Notebooks?](https://stackoverflow.com/q/61925283/11107541), [How can I see all the output without a horizontal scrollbar appearing in Jupyter notebooks in VS Code?](https://stackoverflow.com/q/76544303/11107541)

**Comment by JalinWang** [comment]
`notebook.output.wordWrap` does work. However, the search result is odd 🧐

https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

![image](https://github.com/microsoft/vscode/assets/20621784/e0c8ba04-35e9-4b0f-a2ac-48e6502d0f92)
![image](https://github.com/microsoft/vscode/assets/20621784/8348f3a7-ba9f-48bb-96cf-c94d9604f256)
![image](https://github.com/microsoft/vscode/assets/20621784/1d5050e5-41ee-4fe5-bfb8-e8ddd46ee642)
![image](https://github.com/microsoft/vscode/assets/20621784/6e96cffa-030c-4d80-86c5-715cbd4ecd32)

**Comment by Eugleo** [comment]
@starball5  Is there any way to make the output wrap at a specific column, similarly to how `bounded` works in normal files?
