### ISSUE TITLE
Windows: support to restore windows to virtual desktops

### ISSUE THREAD

**Issue by Spotnyk** [microsoft/vscode#116358]
Currently (Windows 10) selecting "Restart to Update" when VS code windows are on multiple desktops, results in _all_ windows reopening on the active desktop.

It would be great if the windows could remember what desktop they were anchored to before the restart.

Thanks

**Comment by bpasero** [comment]
@Spotnyk does the same happen when you click File > Exit and start VSCode again? Does it only happen when updating?

**Comment by Spotnyk** [comment]
> @Spotnyk does the same happen when you click File > Exit and start VSCode again? Does it only happen when updating?

Yes it does. I just tested again to be sure.

Win10 20H2 19042.789
VSC
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
Not sure what would be different between a normal restart and a restart from an update, but needs investigation.

**Comment by Spotnyk** [comment]
> Not sure what would be different between a normal restart and a restart from an update, but needs investigation.

@bpasero Perhaps I wasn't completely clear. My apologies. The same issue occurs with a normal restart _and_ an update.

**Comment by bpasero** [comment]
@Spotnyk ah ok, did this start to happen recently with our last update or was always the case? Anything special about your monitor setup?

**Comment by Spotnyk** [comment]
@bpasero I do not know if it just started. I've only leaned into W10s multi-desktop stuff about a month ago (used it in X for a long time, but not Windows). There has not been a lot of opportunities to update in that time, and I never exit VSC otherwise.

I currently have six monitors on my desk, across two PCs. However, the PC where I am experiencing this only has two monitors, stacked vertically. I don't know if that qualifies as "special".

**Comment by bpasero** [comment]
@Spotnyk oh wait, you say "multi-desktop" on Windows, so this is not actually a single Windows desktop spanning multiple monitors but you leverage "multi desktop" windows feature explicitly?

**Comment by Spotnyk** [comment]
@bpasero Oh, yes. Sometimes referred to as "virtual desktops". I apologize for the misunderstanding. 

This is why I posted this as a feature request. I assumed it was quite fringe in nature. The misunderstanding explains the more active response. :)

**Comment by bpasero** [comment]
We had this opened https://github.com/microsoft/vscode/issues/111376 but it did not get sufficient upvotes.

**Comment by Spotnyk** [comment]
> We had this opened #111376 but it did not get sufficient upvotes.

My apologies for wasting your time. Have a good evening.
