### ISSUE TITLE
Use DAP's new "StackFrame.canRestart" property to enable the "Restart Frame" command

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#116345]
With https://github.com/microsoft/debug-adapter-protocol/issues/147 a new optional property on the StackFrame has become available that indicates whether the "restart" request is available on a stack frame.

This feature request asks for using "StackFrame.canRestart" in VS Code.

I suggest this strategy:
- if the DAP's `supportsRestartRequest` capability is true, the "Restart Frame" becomes available in the CALL STACK view's context menu
- the "Restart Frame" command is enabled if a `StackFrame` has a `canRestart` property with value true or if the property is missing.

With this approach we make good use of the semantically overlapping properties `supportsRestartRequest` and `canRestart` by achieving UI stability.

/cc @connor4312 is this ok with you?

**Comment by connor4312** [comment]
Cool, thanks for the merge! I'll adopt this in js-debug today

**Comment by isidorn** [comment]
@weinand makes good sense
@connor4312 let me know once this is in js-debug nightly so I can work on the client to show it. Or should it just be there tomorrow?

**Comment by connor4312** [comment]
I've adopted it in the linked commit and it'll be in the next nightly

**Comment by isidorn** [comment]
Great, thanks

**Comment by isidorn** [comment]
As Andre suggested if the `supportsRestartRequest` we show the action.
And the stackFrame.canRestart controls if it is enabled or not.

Try it out and let me know what you think
