### ISSUE TITLE
VS Code 1.53+ not asking for admin rights to update, so it fails.

### ISSUE THREAD

**Issue by kinwolfqc** [microsoft/vscode#116323]
- VS Code Version: 1.53+
- OS Version: Windows 10 20H2

VS Code is installed under Program Files, and so far it never caused any problem when updates happened.  It would ask for admin rights(UAC) and install the update.  Since the 1.53 update(actually, the problem was probably with the version before 1.53 since the problem arose first when 1.53 came out.) I get instead an error message that it can't update itself(access denied) and I have to restart vs Code in admin mode to start the update.  This behaviour is very recent and happened again with 1.53.1 , but I'm not sure if the problem resides with vs code or an OS update.  But other programs have no problem popping up UAC.

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the About dialog in VS Code?

**Comment by kinwolfqc** [comment]
Sorry, I missed the question.  Here is the text of the about box

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by kinwolfqc** [comment]
Can we reopen this issue?  I still have the problem.

**Comment by joaomoreno** [comment]
In which location is VS Code installed?

**Comment by kinwolfqc** [comment]
"D:\Program Files\Microsoft VS Code\Code.exe"
It was installed with the system installer version and updated fine until 1.53

**Comment by joaomoreno** [comment]
> It was installed with the system installer version and updated fine until 1.53

This goes against what your about box says:

> Version: 1.53.2 (user setup)

I recommend uninstalling all VS Code installations you can find and then either install the system or the user setup, depending on what you want for your system.

**Comment by kinwolfqc** [comment]
I did notice that is says User Setup, but how did that happened?  Was the wrong version sent by the updater?  VS code on my machine was installed so long ago, I do not even remember when, but it's been updating by itself since then, so how did it shift from system install to user install?
I will reinstall with system setup.
