### ISSUE TITLE
Wrap Tabs feature : Incorrect last tab width

### ISSUE THREAD

**Issue by thunder-coding** [microsoft/vscode#116325]
- VS Code Version: 1.53.0
- OS Version: Windows 7 SP1
Steps to Reproduce:

1. Turn on the new `workbench.editor.wrapTabs` feature
2. Open 2 or more tabs
3. Now shrink the tab space.
4. The last tab in the list will be covering entire space instead on just covering the space it used to when the feature was disabled

Screenshots: 

Before:
![image](https://user-images.githubusercontent.com/68849076/107515226-be990100-6bd0-11eb-81f9-20a5b6060429.png)

After: 
![image](https://user-images.githubusercontent.com/68849076/107514918-4e8a7b00-6bd0-11eb-95c7-86c3e0902b67.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
/duplicate of #113801

_Sorry for second notification_
