### ISSUE TITLE
Left / right navigation does not work for moving focus in keybinding editor input actions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116334]
1. Open keybindings editor
2. Notice the inline actions in the input
3. Focus onto one of those actions. 
4. Use left or right navigation -> focus is not moved 🐛 

![Screenshot 2021-02-10 at 16 03 13](https://user-images.githubusercontent.com/1926584/107527895-8d610680-6bb9-11eb-8d4c-106289999dfd.png)

**Comment by sandy081** [comment]
I am using the action bar for these actions, is not it enough to get this support?

https://github.com/microsoft/vscode/blob/d1cfec444729a9a2c924aab06e5084b5536cccdf/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts#L395-L412

**Comment by isidorn** [comment]
That should be enough, however this was not working before my changes... And it still does not work
Feel free to assign to me and I can also look into it

**Comment by sandy081** [comment]
Thanks a lot Isi, please reassign it to me if there is something that I have to do.
