### ISSUE TITLE
⚠️🚧👷 Scheduled rename `master` branch to `main`

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116341]
On **Feb 14, 2021, 8PM UTC** the `microsoft/vscode` repository will rename its `master` branch to `main`.

cc @microsoft/vscode

---

⚠️ **Call to Action** ⚠️

If you have a clone of `microsoft/vscode` locally, you'll need to run the following commands **_after_** the rename happens:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git fetch --prune
```

**Comment by baslr** [comment]
Women can also be a construction worker 👷‍♀️ 🤦‍♀️

**Comment by joaomoreno** [comment]
> Women can also be a construction worker 👷‍♀️ 🤦‍♀️

@baslr Absolutely, why would you even think otherwise?

In this case, I am the one doing the construction work and I happen to be a man... I think. 🤔

**Comment by solarblueberry** [comment]
May I ask why is this necessary? Did I miss something?

**Comment by foreignmeloman** [comment]
> May I ask why is this necessary? Did I miss something?

I guess the same reason why GitHub defaults to 'main' master branch name now. Good old PC BS. Apparently word 'master' has a bad stigma attached to it now 🤦‍♂️

**Comment by joaomoreno** [comment]
Guys, I'm sorry. Nothing bad happened here, but I'm just going to lock this thread right now before it does.

As a team, we've decided to go ahead with this rename, because reasons. This issue isn't the place to discuss the merits and drawbacks of the rename. If you fell like venting, I recommend you do so through your own personal mechanisms. Mine is running 10k out in the cold. 🏃
