### ISSUE TITLE
Enable customers to profile the extension host

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11638]
From time to time we receive issues about the extension host going mad. When this happens we are blind and are basically asking folks to disable all or _some_ extensions to check if the problem still shows... Instead we should ship the `v8-profiler` module that allows to create cpu profiles and heap snapshots such that users have something real for us to look at

**Comment by jrieken** [comment]
Moving this out to October - this will increase our bundle size by at least 2.5MB which isn't very desirable. For October we should pre-compile bits and ship this as extension

**Comment by ypresto** [comment]
It is very helpful to optimize hotspot in (slow) extension..!

**Comment by jrieken** [comment]
It's quite unlikely that we will ship the profiler as it is supported right now. The problem is that debugging must start form *the inside*.  This is what we were planning: (1) detect extension host slow, (2) start profiler for a bit. However, since a slow/dead extension cannot process yet another request like 'start profiler' we won't be successful. Later versions of node.js/v8 allow to profile from the outside, without depending on a responsive JS event loop. As soon as that is available to us we will make this happens. 

Still, if you want to profile your extensions (or another) you can use the `v8-profiler`. A version that works with VS Code can be found here: https://github.com/jrieken/v8-profiler

**Comment by ipatalas** [comment]
Anyone was able to run this profiler on Windows? 

Can't get this to work:
![image](https://user-images.githubusercontent.com/2623329/27055838-06bf9096-4fc6-11e7-9b84-c8120f0cd251.png)

Am I missing something?

**Comment by jrieken** [comment]
With the latest electron update this is now possible. We just need a way to bring the process into debug mode (in which it normally isn't) and then you can connect chrome-dev-tools to them 🎉

**Comment by ipatalas** [comment]
That would be great! I believe a command line switch should be enough for that. Can't wait to be able to profile one of my extensions :)

**Comment by jrieken** [comment]
> That would be great! I believe a command line switch should be enough for that. Can't wait to be able to profile one of my extensions :)

That's actually already possible. While look for ways to implement this I have found the `debugPluginHost`-option. Do the following (using Insiders)

* start from the command line like so `vscode-insider --debugPluginHost=5678`
* open developer tools and find a message that start with 'Debugger listening on port 5678' and end with a link
* open that link in Chrome

**Comment by eamodio** [comment]
@jrieken is that documented anywhere with regards to extension development? It would be great if not.

**Comment by jrieken** [comment]
Yeah, we should document it

**Comment by jrieken** [comment]
The "implementation" of this will be an update of our documentation. I'll post it here to begin with, the it goes via release notes into our docs (fyi @gregvanl)

**Comment by jrieken** [comment]
* Start VS Code from the command line with `--inspect-extensions=<port>`-flag number, e.g. `code --inspect-extensions=9333`
* In VS Code, hit *F1 > Toggle Developer Tools*, 
* In the developer tools, select the *Console*-tab, and find a message that starts with *Debugger listening on port 9333* and that ends with a link
* Open that link in Chrome and have dedicated dev-tools (debugger, profiler, etc) for the extension host
