### ISSUE TITLE
Investigate to enable webview in sandboxed environment

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116452]
According to @deepak1556 it seems possible to use `webview` even whith `sandbox: true` and `contextIsolation: true`. This would be great to explore given blocking issues such as https://github.com/microsoft/vscode/issues/96307 for https://github.com/microsoft/vscode/issues/83188.

I am unfortunately not able to get a simple `webview` based editor (release notes) to open in sandboxed environments, here are my steps:
* make sure to be able to run sources from `ben/webview-sandbox` branch (this simply adds `webview` code to sandbox layer)
* run with `scripts/code.sh --__sandbox`
* open command palette
* select `Show Release Notes`

Observe devtools (you can open via `Cmd+Shift+I`, but you need to click once into the workbench first for focus):

`[Embedded Page] undefined`

I was able to get a better error message when I flip `contextIsolation: false` ([here](https://github.com/microsoft/vscode/blob/3d9f13ea764a43e084b4fe677aeabcdd4e798c4f/src/vs/platform/windows/electron-main/window.ts#L166-L166)):

```
[Embedded Page] Unable to load preload script: /Users/bpasero/Development/Microsoft/monaco/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js
[Embedded Page] Error: module not found: ../../browser/pre/main
```

@mjbvz @deepak1556 I will need your help here for how to proceed. Any clues? I verified that these files are not getting blocked from our [`protocol`](https://github.com/microsoft/vscode/blob/169a0ec047fe3ac76821af968cde91ff04cedd95/src/vs/code/electron-main/protocol.ts#L87-L92), this must be something else...

**Comment by mjbvz** [comment]
@bpasero Looks like the [webview preload script](https://github.com/microsoft/vscode/blob/ed98eb1968583f83f58fa947735919e9e8a9be0d/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L152) is using a `file:` uri which ends up being blocked:

```
file:///Users/matb/projects/vscode/out/vs/workbench/contrib/webview/electron-browser/pre/electron-index.js
```

@deepak1556 Would we be able to serve this script using a `vscode-file` or `vscode-webview` uri instead?

**Comment by bpasero** [comment]
@mjbvz @deepak1556 my understanding is that `preload` scripts for `webview` must use the `file` protocol, as any other protocol is blocked by Electron from loading. Since the `preload` scripts seems to be loaded using node.js, we cannot use our custom protocol.

Besides, if I disable our blocking of `file` protocol by [comment out this line](https://github.com/microsoft/vscode/blob/8dbc14946b3b85e450eab5adb43a9654b16ef70b/src/vs/code/electron-main/protocol.ts#L41-L41), it still does not work.

**Comment by bpasero** [comment]
Since we want to invest in https://github.com/microsoft/vscode/issues/96307 which would give us a path to dropping `webview` entirely, moving this to Backlog for now.

**Comment by bpasero** [comment]
I am no longer convinced that `webview` is the future for sandbox, so closing.
