### ISSUE TITLE
Typing ( after a function from another module that needs to be auto imported does not add the ) after

### ISSUE THREAD

**Issue by ImRodry** [microsoft/vscode#116491]
Issue Type: <b>Bug</b>

Let's say you have the function start() on a file and want to use that on another file. If the function is already on module.exports and you type start( on the other file, the function will be automatically imported at the top but vscode will not close the brackets, thus creating an error (not a big deal obviously but slightly annoying)

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.89GB (6.31GB free)|
|Process Argv|D:\\Users\\rodri\\Documents\\GitHub\\hypixel-translators-bot --crash-reporter-id 1aa51578-c79e-468f-b062-c24334e21918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-crowdin|Cro|1.0.6
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-lombok|Gab|1.0.1
discord-vscode|icr|5.2.0
vscode-env|Iro|0.1.0
graphql-for-vscode|kum|1.15.3
csharp|ms-|1.23.9
gradle-language|nac|0.2.3
vetur|oct|0.32.0
java|red|0.74.0
vscode-yaml|red|0.15.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
minecraft-lang-colorizer|zz5|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by ImRodry** [comment]
Are there any updates on this? Please let me know if you need more info

**Comment by mjbvz** [comment]
I just tested this and it works fine for me. One exception is that `(` is not considered a commit character when `typescript.suggest.completeFunctionCalls` is enabled.

Can you please share a code example (as text) where this does not work

**Comment by ImRodry** [comment]
I was actually using this on JavaScript but I can't seem to reproduce this anymore so I assume the issue has since been fixed so I'll close this, sorry for the inconvenience!
