### ISSUE TITLE
Rename symbol

### ISSUE THREAD

**Issue by microshine** [Microsoft/vscode#11641]
- VSCode Version: 1.4.0
- OS Version: Windows 10 x64

Source code
```typescript
let arr = {
    item: "Hello"
};

const {item} = arr;

console.log(item);
console.log(arr.item);
```

Trying to rename `item` symbol (F2) to `itemA`

Result
```typescript
let arr = {
    itemA: "Hello"
};

const {item} = arr; // TSError: Has no property `item`

console.log(item);
console.log(arr.itemA);
```

**Comment by waderyan** [comment]
@microshine thank you for opening this issue. This is a TypeScript service issue. Moving to their repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10791
