### ISSUE TITLE
CPU is throtled after update

### ISSUE THREAD

**Issue by BAHorobet** [microsoft/vscode#116441]
CPU is constantly throttled and visual studio code seems to have lagged due to that, happened straight away after the last update, which I've done 1 h ago.

**Comment by wvankuipers** [comment]
I have the same issue on OSX (11.2.1) after opening a project I get:

![image](https://user-images.githubusercontent.com/3356735/107632956-88f32700-6c67-11eb-90fa-ea340ec9b1a1.png)

**Comment by wvankuipers** [comment]
After completely closing the editor I can no longer reproduce this

**Comment by BAHorobet** [comment]
Version: 1.53.1 (system setup)
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Windows 10 pro


25 extensions:
Anaconda Extension Pack 1.0.1
Better Comments 2.1.0
Code Runner 0.11.2
Djaneiro - Django Snippets 1.4.2
Django 1.3.0
flask-snippets 0.1.1
jinja 0.0.8
jupyter
kite autocplete ai code 0.138.0
magicpython 1.1.0
markdownlint 0.38.0
mysql 0.4.0
pylance 2021.2.2
python 2021.1.502429796 (3.7.1)
python docstring generator 0.5.4
python extension pack 1.6.0
python for vscode 0.2.3
python indent 1.12.0
python must-have essentials 1.0.1
restructuredtext 143.0.0
sqlite 0.11.1
sqltools 0.23.0
visual studio intellicode 1.2.11
xml tools 2.5.1
yaml 0.15.0

**Comment by deepak1556** [comment]
Thanks!

> CPU is constantly throttled and visual studio code seems to have lagged due to that

Can you provide a video recording or gif of what you are seeing. It helps understand the problem a bit better.

**Comment by BAHorobet** [comment]
I don't see anything. My CPU jumps to being used heavily 80 90 100% once I
open vscode and vscode is laggy, in terms of when I write python code, it
laggs in recognising which are variables. Functions or anything like that.

Before update used to be instant and low CPU usage.

**Comment by deepak1556** [comment]
> I don't see anything

Do you mean, you are seeing the window open but it stays blank and during that period the CPU usage increases ?

**Comment by BAHorobet** [comment]
Sorry, no. I mean vs code is there but everything has some lag to it and
CPU is high.

**Comment by deepak1556** [comment]
* Start with `code --disable-extensions`
* If you see the cpu increase
* From a separate terminal, provide the output of `code --status`

**Comment by BAHorobet** [comment]
Thanks for your support.

I think one of the extensions was the issue, cpu seems to work as before now! The extension must have updated that caused the issue. Thank you for your support.
