### ISSUE TITLE
Select and Start Debugging no longer available on command palette

### ISSUE THREAD

**Issue by andyboyne** [microsoft/vscode#116432]
Issue Type: <b>Bug</b>

Up until now, and according to the docs: 

(https://code.visualstudio.com/docs/editor/debugging#:~:text=Once%20you%20have%20your%20launch,configuration%20you%20want%20to%20debug.)

"Alternatively you can run your configuration through the Command Palette (Ctrl+Shift+P), by filtering on Debug: Select and Start Debugging or typing 'debug ', and selecting the configuration you want to debug."

This is not possible since 1.53

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.17763

**Comment by lobbi145** [comment]
I believe this is the only way to search through the launch targets, and for projects with many launch targets this is very nice to have

**Comment by isidorn** [comment]
F1 > type `debug ` works just fine for me
What does not work is that the debug select and start debugging command is missing.
This is already fixed in VS Code insiders. Will be in the next stable stable
https://github.com/microsoft/vscode/issues/116299

**Comment by andyboyne** [comment]
A duplicate of what issue?
