### ISSUE TITLE
Add folder to workspace 

### ISSUE THREAD

**Issue by sferrone** [microsoft/vscode#116462]
Issue Type: <b>Bug</b>

Hi,

I'm using a Mac, Catalina 10.15.17. Some things are not responding in visual studio code. For example, when I control+click in the workspace area and then "Add Folder to Workspace..." nothing happens, I am not prompted with finder to add this folder as I was before. 

When I am on the Welcome tab and I click "Open folder..." nothing happens. Also, when I went to Code -> About Visual Studio Code nothing happened. I'm not sure how to fix this and I couldn't find anyone with the same issue on the forms. 

So the result is nothing and my expected result is to be prompted with finder window to add a desired folder to me workspace. 

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.22GB free)|
|Process Argv|--crash-reporter-id 0198779c-d7c1-46f4-8232-6d64ba58eb30|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
latex-workshop|Jam|8.15.0
linter-gfortran|krv|2.2.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
vscode-arduino|vsc|0.3.4

</details>

**Comment by meganrogge** [comment]
Using the command pallette, try running extension bisect to see if your issue resolves

**Comment by bpasero** [comment]
@sferrone if the native system file/folder dialog does not open, then there seems to be a serious issue that could be unrelated to VSCode. As a workaround you can configure `files.simpleDialog.enable: true` in settings to use our file dialog, that should work fine.
