### ISSUE TITLE
Control characters in filenames do not render correctly

### ISSUE THREAD

**Issue by rijenkii** [microsoft/vscode#116485]
Issue Type: <b>Bug</b>

Open a folder, open a terminal in that folder, execute following command:
```bash
$ touch $'foo.txt\nbar.exe'
```
In the Explorer in the sidebar AND in the tabs file will just be displayed as "foo.txt"

Screenshot in the comments

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.10.11-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 x 2832)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.69GB (0.44GB free)|
|Process Argv|--no-sandbox --crash-reporter-id c8f1df93-8c7a-436f-baca-fc061dc64e9c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/bspwm|
|XDG_CURRENT_DESKTOP||
|XDG_SESSION_DESKTOP||
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|2.3.0
vscode-ron|a5h|0.9.0
better-toml|bun|0.3.2
vbscript|Dar|1.0.4
latex-workshop|Jam|8.15.0
rust-analyzer|mat|0.3.447-nightly
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
crates|ser|0.5.5
vscode-fileutils|sle|3.4.4
shader|sle|1.1.4
sass-indented|syl|1.8.15
vim|vsc|1.18.9

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by rijenkii** [comment]
![20210212-003023](https://user-images.githubusercontent.com/5338332/107674475-96d99400-6cc9-11eb-814f-9fce879ce3db.png)

**Comment by isidorn** [comment]
I see that the `uri` has correctly entered our system but just that the `fileLabel` does not render it correctly since it really puts the name in two lines.
The `fileLabel` could escape control characters and show them like that, but this is not a change I would be willing to do right now. I suggest to keep this issue open and we might tackle it in the future

fyi @bpasero

**Comment by bpasero** [comment]
I think best we could do is detect these characters (also tabs?) and show them separated by whitespace. 

Isn't there a CSS rule to enforce this just purely via rendering? Like `white-space` something?

**Comment by isidorn** [comment]
Good idea, there is `white-space: nowrap`. Let me try it out...

**Comment by isidorn** [comment]
Ok tried it out - and it works nicely, however that css rule would collapse all spaces. So then somebody would come saying they have a filename "hello&nbsp;&nbsp;&nbsp;there.txt" that is displayed as "hello there.txt".

There is no css value for that rule that would not wrap new lines and preserve whitespaces.
So I would not change anything here atm

**Comment by bpasero** [comment]
Yeah seems so:

![image](https://user-images.githubusercontent.com/900690/107756951-38da9a00-6d25-11eb-9b64-68e5b26cb70e.png)
