### ISSUE TITLE
Diff inside a single line: make changes easier to see

### ISSUE THREAD

**Issue by kaba2** [microsoft/vscode#116413]
When writing papers in Latex, a single paragraph is on a single line, and hence a line might get relatively long. Have a look at this diff of Latex. Can you tell what has changed? 

![image](https://user-images.githubusercontent.com/2399754/107605517-0ef97880-6c3c-11eb-9e4a-604b15bd4b0d.png)

That's right, a single comma inside the paragraph was added. However, diff visualizes it as if the whole paragraph were changed.

If you look very closely, you'll notice that that comma is actually marked with a lighter color. So Code does know where the change occurs inside a line. However, that lighter color is very difficult to distinguish from the surrounding color. 

My abstract request: 

**Make it so that changes inside a single line can be seen quickly, at a glance.**

I'm not sure what the best approach for that is, but I'll mention a few possibilities in increasing level of hardness:

1) Change the color of the inside-line changes so that they really pop out from the color of the line. Like this:

![image](https://user-images.githubusercontent.com/2399754/107606227-26396580-6c3e-11eb-9102-cc6a1e438b89.png)

2) Restrict the line-coloring to the left sidebar. Use coloring inside a line to locate the changes. Like this:

![image](https://user-images.githubusercontent.com/2399754/107606011-75cb6180-6c3d-11eb-89c0-b4e305d2460e.png)

3) Combination of 1 and 2:

![image](https://user-images.githubusercontent.com/2399754/107606374-8defb080-6c3e-11eb-8105-6f36a354a216.png)

4) Actually, shouldn't the diff just work inside a single line? Like this:

![image](https://user-images.githubusercontent.com/2399754/107606614-4d446700-6c3f-11eb-9ec9-247ed8599b8a.png)

P.S. Many thanks for the recent word wrap functionality in the diff view! It makes reviewing changes to Latex text much simpler.

**Comment by hdodov** [comment]
I think that the first solution is good enough. There just needs to be a separate option for the in-line diff color. Currently, there are just `diffEditor.insertedTextBackground` and `diffEditor.removedTextBackground`. In Monokai:

```
"diffEditor.insertedTextBackground": "#4b661680",
"diffEditor.removedTextBackground": "#90274a70",
```

...and the resulting thing in the DOM is (for the inserted line):

```css
.monaco-diff-editor .line-insert, .monaco-diff-editor .char-insert {
    background-color: rgba(75, 102, 22, 0.5);
}
```

The line (`.line-insert`) is green with alpha `0.5` and then the changed characters (`.char-insert`) are the same green with `0.5` alpha on top of it.

I think it would be enough to simply have separate settings for those two. For example:

```
"diffEditor.insertedLineBackground": "#4b661680",
"diffEditor.insertedCharBackground": "#ff00ff",
"diffEditor.removedLineBackground": "#90274a70",
"diffEditor.removedCharBackground": "#ff00ff",
```

...which results in:

```css
.monaco-diff-editor .line-insert {
    background-color: rgba(75, 102, 22, 0.5);
}

.monaco-diff-editor .char-insert {
    background-color: rgb(255, 0, 255);
}
```

**Comment by alexdima** [comment]
This has been done via https://github.com/microsoft/vscode/issues/103207#issuecomment-1044647883
