### ISSUE TITLE
Window resizing broken on Chromebook (v 1.53.1)

### ISSUE THREAD

**Issue by pvspain** [microsoft/vscode#116406]
## Issue
 
The application window will no longer snap to the left/right half of the screen (keystrokes: Alt+ ], Alt+[)
The application window will no longer maximise via double-clicking on the window title-bar. 
The behaviour was first observed in v1.53.0
I don't think the issue relates to the Linux environment on a Chromebook, as other Linux apps (e.g. Brave Browser, Gimp) resize as expected.

## Environment

VS Code installed as a Linux app on a Chromebook  from Microsoft APT repository source

### VS Code 

```text
Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:30:54.166Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.74-10576-gb6cc41974db3
```
### Linux

```bash
pvspain@penguin:~$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
pvspain@penguin:~$ uname -a
Linux penguin 5.4.74-10576-gb6cc41974db3 #1 SMP PREEMPT Sun Nov 8 15:08:12 PST 2020 x86_64 GNU/Linux
pvspain@penguin:~$ apt policy code
code:
  Installed: 1.53.1-1612827767
  Candidate: 1.53.1-1612827767
  Version table:
 *** 1.53.1-1612827767 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
        100 /var/lib/dpkg/status
     1.53.0-1612368357 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.52.1-1608136922 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.52.0-1607640828 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.51.1-1605051630 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
pvspain@penguin:~$ 
```

### Google Chrome OS

```text
Version:  88.0.4324.153 (Official Build) (64-bit)
Platform: 13597.84.0 (Official Build) stable-channel eve
```

**Comment by DakotahGodfrey** [comment]
Also running into this issue with (v 1.53.1). I'm running VS on a Pixelbook Go through Linux(beta) on the same ChromeOS version. Rolling back to (v 1.52.1) resolved the issue in my case.

**Comment by bpasero** [comment]
Related/duplicate: https://github.com/microsoft/vscode/issues/116146

**Comment by deepak1556** [comment]
Does starting with `--disable-gpu` help ?

**Comment by pvspain** [comment]
Hi @deepak1556,  I started the application via... 

```bash
code --disable-gpu
```
... but the symptoms remain.

**Comment by codysherman** [comment]
Hi! I actually opened up a bug report to the Chromium team a few days ago suspecting it was a recent Chrome OS update, but it's now starting to look like it's only VSCode that is affected, so it could very well be a VSCode or specific version of Electron issue.

Here is the corresponding Chromium thread: https://bugs.chromium.org/p/chromium/issues/detail?id=1175092

**Comment by deepak1556** [comment]
VSCode doesn't handle window operations, it is handled by electron. If you can repro the issue in https://www.electronjs.org/fiddle then we can file an issue in Electron.

**Comment by pvspain** [comment]
Thanks @deepak1556. Fiddle doesn't work out of the box on a Chromebook - Electron download/autoupdater failing. There is a community [electron-installer-debian][1]. I'll need some time to dig further.  

[1]: https://github.com/electron-userland/electron-installer-debian

**Comment by pvspain** [comment]
Hi there,

The symptoms are still present

Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:58:14.757Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.4.99-12983-g8b7876ab9f5e

Cheers, Paul

**Comment by deepak1556** [comment]
@pvspain can you run with `code --enable-features=UseOzonePlatform --ozone-platform=wayland` and verify.

**Comment by titanous** [comment]
Those flags make the window resizable again for me.

**Comment by pvspain** [comment]
That partially works..

1. Working
* The window can be snapped left-right via keystrokes Alt+]/[
2. Broken
* The window is painted without any icons in the right corner of the title
bar (minimise/maximise/close), and does not respond to mouse clicks in that
region.
* The window does not respond to double-clicking on the title bar
(maximise-toggling)
* The maximised window does not fully extend to the top and bottom edges of
the screen
* Repeated Alt+] or Alt+[ sequences toggles between snapped and 'maximised'
rather than snapped and a horizontally-centred half window.
3. Performance hit
* The window rendering has degraded from instantaneous to maybe 300ms when
toggling with Alt+[
  (Google Pixelbook  i7-7Y75 2400x1600 screen)

Cheers, Paul


On Fri, 7 May 2021 at 23:30, Robo ***@***.***> wrote:
>
> @pvspain can you run with code --enable-features=UseOzonePlatform
--ozone-platform=wayland and verify.

**Comment by pvspain** [comment]
Lucky you Jonathan ;)
The only software difference between our stack seems to be the Linux kernel
version.

Cheers, Paul

**Comment by spitfire55** [comment]
[Electron simply closed the issue on their end](https://github.com/electron/electron/issues/27737) stating that Electron is not officially supported on ChromeOS. Using the flags above does fix the issue, but with a pretty significant decline in performance (scrolling, animations, etc.).

**Comment by aschwartz2018** [comment]
On the newest version of VSCode, this WAYLAND fix doesn't work anymore :((
Does anyone have tips?

**Comment by codysherman** [comment]
Google fixed it on the Chrome OS side, it should start popping up in dev, then beta, than stable builds: https://bugs.chromium.org/p/chromium/issues/detail?id=1175092#c29

**Comment by aschwartz2018** [comment]
> Google fixed it on the Chrome OS side, it should start popping up in dev, then beta, than stable builds: https://bugs.chromium.org/p/chromium/issues/detail?id=1175092#c29

That's great thanks. Do you think it will be in the next 92 stable update?

**Comment by aschwartz2018** [comment]
> Google fixed it on the Chrome OS side, it should start popping up in dev, then beta, than stable builds: https://bugs.chromium.org/p/chromium/issues/detail?id=1175092#c29

Unfortunately, that will be released in October.
Is there another workaround to allow VSCode to snap properly?

**Comment by aschwartz2018** [comment]
Yeah this wayland workaround is dead i believe
![Screenshot 2021-08-09 5 36 57 PM](https://user-images.githubusercontent.com/68354532/128777786-40190e94-c375-4b79-85cc-4552e8f564f5.png)

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/116406#issuecomment-895205936 , there is nothing actionable for vscode here.

For https://github.com/microsoft/vscode/issues/116406#issuecomment-895567857 you can ignore the warnings, it simply means the flags are not respected by vscode but rather by the runtime.
