### ISSUE TITLE
Consolidate local and remote terminal implementations

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#116467]
Currently there's a fair bit of duplication

**Comment by Tyriar** [comment]
This one is lower priority and also a little risky to do later in the iteration so it might get pushed to next debt week.

**Comment by Tyriar** [comment]
This is the plan, the topic local side is the current state of the local pty host (in PR), the bottom is what I want remote to look like:

<img width="684" alt="Screen Shot 2021-02-17 at 12 46 54 PM" src="https://user-images.githubusercontent.com/2193314/108267460-162ef380-7120-11eb-9b65-6b9adf865d35.png">

**Comment by meganrogge** [comment]
@meganrogge remember to check if this breaks the remote case when remote starts using `PtyService`

**Comment by meganrogge** [comment]
@meganrogge explored this and doesn't look like events are getting batched w the current `throttleBy` time of 5. #117268
