### ISSUE TITLE
All Extensions not working

### ISSUE THREAD

**Issue by mightypenguin** [microsoft/vscode#116474]
- VS Code Version: 1.53.1
- OS Version: CENTOS7   7.9.2009

Steps to Reproduce:

1. Update to VSCODe 1.53.1 (tried uninstalling, reinstalling, tried removing ~/.vscode folder)
2. Open git repo and look at any file. No extensions work. No error messages.

Does this issue occur when all extensions are disabled?: Yes

Manually installing VSCode 1.52.1 fixed the problem.
The C++ extension does not download dependencies when started with 1.53.1 but does with 1.52.1

Specifically I'm running these extensions:
ms-vscode.cpptools
eamodio.gitlens

Manually updated git to: 2.24.3 from Rackspace ius repo.
No error messages on startup of either VSCode version 1.53.1 or 1.52.1.

**Comment by gjsjohnmurray** [comment]
Starting with 1.53 CentOS 7 is no longer a supported platform. See https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356
