### ISSUE TITLE
Go to next line (move the caret one line down independent of word wrap)

### ISSUE THREAD

**Issue by mstenemo** [microsoft/vscode#116418]
I am requesting a command to move the caret to the beginning of next/previous line, and if shift is also held down (eg using ctrl+shift+up/down) it should select text from the caret to beginning/end of current line. The difference between using shift+home is that hitting ctrl+shift+up multiple times would add another line each time, while +home does not expanding selection.

Similar commands are implemented almost universally with crtl+up/down both in editors (eg in [Sublime](https://stackoverflow.com/questions/45788119/is-there-a-vs-code-shortcut-to-move-select-up-down-to-the-next-empty-line/66066852#66066852) and [Emacs](https://stackoverflow.com/questions/61628527/how-can-i-add-emacs-like-control-up-down-to-vscode) to move between code blocks), and in other common programs (eg **GitHub**, Word, Gmail) to move/select text between paragraphs or on the same line when the line is affected by word wrap). 

This is slightly different from the recently added prevBlankLine and nextBlankLine cursorMove command (Insiders' Build for v1.54) for moving between code blocks like in [Sublime](https://stackoverflow.com/questions/45788119/is-there-a-vs-code-shortcut-to-move-select-up-down-to-the-next-empty-line/66066852#66066852) and [Emacs](https://stackoverflow.com/questions/61628527/how-can-i-add-emacs-like-control-up-down-to-vscode).

**Comment by alexdima** [comment]
This can be done by using the `cursorMove` command. This command is used internally by all other cursor navigation commands. e.g.:

```
{
    "key": "down",
    "command": "cursorMove",
    "args": { "by": "line", "to": "down" },
    "when": "editorTextFocus"
}
```

**Comment by mstenemo** [comment]
> This can be done by using the `cursorMove` command. This command is used internally by all other cursor navigation commands. e.g.:
> 
> ```
> {
>     "key": "down",
>     "command": "cursorMove",
>     "args": { "by": "line", "to": "down" },
>     "when": "editorTextFocus"
> }
> ```

Possible to make this accessible in the "keyboard shortcuts" settings?

**Comment by alexdima** [comment]
AFAIK The rich keyboard shortcuts editor cannot currently edit the `args` or `when` section of a keybinding. This is tracked in https://github.com/microsoft/vscode/issues/84072

**Comment by mstenemo** [comment]
> AFAIK The rich keyboard shortcuts editor cannot currently edit the `args` or `when` section of a keybinding. This is tracked in #84072

This means that this is not a solution to my request. Any more information that is needed @alexdima?

**Comment by alexdima** [comment]
@mstenemo I think you brought up two issues:

1. how to move cursor down by logical lines (not by wrapped lines). I have provided you with the keybinding rule you can use in your `keybindings.json`. By using intellisense in `keybindings.json` you can discover how to create also a keybinding rule for moving the cursor up, for selecting up, for selecting down, etc. I did not write each and every one, I think you can discover them by using ctrl+space.
2. the fact that you cannot edit the `args` and `when` fields in the Keybindings Editor UI. That is being tracked in #84072

Is there something missing?

**Comment by mstenemo** [comment]
Thank you for the clarification Alexdima, the fact that It was closed as "more information needed" indicated that you still waited for information. That should be possible for me to implement, but not ideal for new users. 

So I guess my remaining issue is if this command is important enough to motivate having its own setting in the keyboard shortcuts. 

I assume there is a good reason why your suggested solution is preferred (although not possible as mentioned in your second point) over adding a new command that is discoverable using the keyboard shortcut directly? 

For very uncommon command I could see a point in not having it available in the keyboard shortcuts by default, although this very common command is implemented almost universally with crtl+up/down (to move between paragraphs as well as word wrap), and I think there are many users who would prefer this by default but not have to go through the processes of adding another completely different solution just to implement it.

**Comment by alexdima** [comment]
I don't think we have a built-in command which would do exactly what you describe: going to the beginning of the previous paragraph / the beginning of the next paragraph. We can leave this issue open to track this feature request.

I haven't seen this command in other code editors. For example, lots of code editors use ctrl+up/down for scrolling the viewport without moving the cursor. We do have another variant that might be helpful if you leave a one line gap between paragraphs: e.g. here is what I personally bind to `ctrl+up/down`:
```
{ "key": "ctrl+up",	"command": "cursorMove", "when": "editorTextFocus", "args": { "to": "prevBlankLine", "by": "wrappedLine" } },
{ "key": "ctrl+down",	"command": "cursorMove", "when": "editorTextFocus", "args": { "to": "nextBlankLine", "by": "wrappedLine" } },
```

So let's leave this issue open for tracking the feature request for a command that moves to the beginning of the previous/next line.
