### ISSUE TITLE
Minimap disappearing on tab switch if GitLens installed

### ISSUE THREAD

**Issue by FractalStranger** [microsoft/vscode#116476]
- VS Code Version: 1.53.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Install GitLens
2. Switch tab

Does this issue occur when all extensions are disabled?: No

Minimal is disappearing(toggling) on tab switch after GitLens installed. Two View: ToggleMinimap clicks are needed to get it back.

**Comment by IllusionMH** [comment]
Looks like duplicate of #116060

Fix should go out with VS Code 1.53.2


Can you reproduce this issue in Insiders build? https://code.visualstudio.com/insiders/

**Comment by FractalStranger** [comment]
Yeah it's the same issue. Closing
