### ISSUE TITLE
Interaction in custom render causes Notebook cell to switch to Markdown

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#116493]
- VS Code Version: 1.54.0-insider
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Clone [github.com/tanhakabir/rest-book](https://github.com/tanhakabir/rest-book)
2. Run in Extension Host
3. Create an empty notebook by creating a file with a `.restbook` ending
4. Create 2 simple REST requests (one GET and one illegal POST) in two separate cells
5. Try to search for something in either cell that exists within the the response from the call.
6. See that the bottom cell automatically get flipped into markdown.

![recording (3)](https://user-images.githubusercontent.com/12758612/107691107-e4211b80-6c5f-11eb-837d-147eb9cf745f.gif)

Only when the word exists in the response: I'm adding span tags on search to highlight the search term. This was not an issue in the past.
![recording (4)](https://user-images.githubusercontent.com/12758612/107691115-e5eadf00-6c5f-11eb-95a9-075910fabe4d.gif)

![recording (5)](https://user-images.githubusercontent.com/12758612/107691123-e71c0c00-6c5f-11eb-84b7-bdb252d660ec.gif)

This wasn't the behavior before. One cell didn't affect the rendering of another.

**Comment by rebornix** [comment]
I'm not able to reproduce this with latest API. can you confirm?

**Comment by tanhakabir** [comment]
Can confirm still occurs with latest API:

![recording (9)](https://user-images.githubusercontent.com/12758612/108781851-68588600-751f-11eb-876f-6fa0c980dd45.gif)

**Comment by tanhakabir** [comment]
Ran one more time with 1.54.0-insiders to be sure:
![recording (10)](https://user-images.githubusercontent.com/12758612/108785603-9ab9b180-7526-11eb-955d-1ec4e17e718d.gif)
