### ISSUE TITLE
Search is not working for about a month

### ISSUE THREAD

**Issue by Mujaddadi** [microsoft/vscode#116442]
. VS Code Version: 1.53.1
. OS Version: Windows 10 Pro 10.0.19042 Build 19042

![version](https://user-images.githubusercontent.com/2556882/107630441-349e7600-6c6c-11eb-8c79-026c24d6c51f.jpg)

Steps to Reproduce:

Search anything on the file. In my case it's JavaScript file

![no result](https://user-images.githubusercontent.com/2556882/107630604-6adbf580-6c6c-11eb-9316-df6d767254fd.png)

**Comment by overtomanu** [comment]
for your case "Find in selection" is activated. This is the button on the left side of close(X). Try unselecting it and try find again.

**Comment by Mujaddadi** [comment]
Thank you it worked.
