### ISSUE TITLE
Debugger issue with sourceMaps if sourceMappingURL string present

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11647]
- VSCode Version: Code - Insiders 1.5.0-insider (b2c874b253732778a246b94aa1eba93806c45361, 2016-09-07T11:56:57.966Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Create some folder in your project (important)
2. Create TypeScript file
3. Paste this content:

```ts
const test = '//# sourceMappingURL=script.js.map'
console.log(test)
export {test}
```

Put breakpoint on second line
Start the debugger

You will get:

![image](https://cloud.githubusercontent.com/assets/1723815/18324232/77aec648-7509-11e6-9fe4-4fdd939f1168.png)

with 'Breakpoint ignored ... (source map problem?)

as soon as you change that string to something else then its ok:
![image](https://cloud.githubusercontent.com/assets/1723815/18324266/9c273dc0-7509-11e6-8365-8502488bbb46.png)

**Comment by waderyan** [comment]
@wallverb thank you for opening this issue. 

Can you copy and paste your `launch.json` here?

**Comment by wallverb** [comment]
@waderyan Sure, here it is

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch server",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/build/cli.js",
            "stopOnEntry": false,
            "args": ["server"],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development",
                "NODE_CONFIG_ENV": "local"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/build"

        }
}
```

**Comment by waderyan** [comment]
@wallverb thank you. 

@weinand can you give me some guidance on this issue? I am seeing the same thing as OP, but I believe I'm not configuring debugging for TypeScript correctly. This is possibly an area we could improve the docs. 

1. I have created `test.ts`. 
2. I copied and pasted OP's code. 

```typescript
const test = '//# sourceMappingURL=script.js.map'
console.log(test)
export {test}
```

3. I set a breakpoing per OP's screenshot. 
4. I generated a new `launch.json` and compared it with OPs. There are no material differences that I can see. 

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/test.js",
            "stopOnEntry": false,
            "args": ["server"],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": false,
            "outDir": null
        }
    ]
}
```

> Note: I removed `Attach` and `Attach to Process` debug tasks.

**Comment by weinand** [comment]
This is just a corner case where the usual source map detection stumbles over a "sourceMappingURL"  pattern that happens to look like the one generated by a transpiler (TypeScript) in this case. It is not specific to TypeScript and I'm sure that this pattern will makes other debuggers (e.g. Chrome debug) to fail as well. Since this issue exists since the beginning of time (of the VS Code debugger), and there are no other reports, I consider this a minor issue.
The work around is to break the string into two strings:
```js
const test = '//# sourceMapping'+'URL=script.js.map'
```

**Comment by waderyan** [comment]
Thanks @weinand. Thanks @wallverb for bringing this to our attention, but we are going to count it as a "not going to resolve" corner case for now.

**Comment by weinand** [comment]
@waderyan In your launch config you will have to set "sourceMaps" to true and specify the "outDir" directory where the TypeScript compiler (or your build process in general) generates the JavaScript files.

**Comment by wallverb** [comment]
Guys - I really appreciate the work you do and VSCode is awesome tool - but bug is a bug regardless of how uncommon it is to occur :)  - for someone working with sourcecode generation/minification - this might not be the corner case. I understand that it might be of lowest priority and team might not find a time to fix it ever -  but I'm pretty surprised that it got closed.

FYI - it does not break Chrome debugger:
![image](https://cloud.githubusercontent.com/assets/1723815/18454061/476d96b6-7910-11e6-8fba-d9a7b8ad7ca0.png)

According to `Source Map` documentation - `//# sourceMappingURL=<url>` should be used if it happens to be at the end of generated file https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit

**Comment by weinand** [comment]
@wallverb you are right, this is a bug and should not be closed without a fix.
