### ISSUE TITLE
visual studio code is not producing the type of file image

### ISSUE THREAD

**Issue by Pallav-19** [microsoft/vscode#116497]
Issue Type: <b>Bug</b>

whenever we save any file , let it be a program.cpp file , we generally see the icon of c++ , if we save it as a program.c file we see an icon of c language before that file. right? but in my VS code I am unable to see those,, kindly reslove.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.75GB free)|
|Process Argv|--crash-reporter-id 50fea196-ba21-414b-89eb-e114662f016c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
code-runner|for|0.11.2
vscode-pull-request-github|Git|0.23.1
better-cpp-syntax|jef|1.15.5
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.4
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by Pallav-19** [comment]
![Screenshot 2021-02-12 020640](https://user-images.githubusercontent.com/73886524/107695760-0a35d280-6cd7-11eb-8ba6-601de6c787da.jpg)

**Comment by lramos15** [comment]
I cannot reproduce this, those icons look like ones from the minimal theme can you make sure you icon theme in your settings is not set to minimal and is instead set to seti. 
<img width="568" alt="Screen Shot 2021-02-11 at 3 51 28 PM" src="https://user-images.githubusercontent.com/4544166/107697323-14c57d00-6c81-11eb-8ab6-188b069172e0.png">

**Comment by Pallav-19** [comment]
thank you , it was just a minor issue , thank you Logan Ramos.
Issues resolved,
