### ISSUE TITLE
hideable directory path

### ISSUE THREAD

**Issue by LucasKohanevicRadice** [microsoft/vscode#116438]
Issue Type: <b>Feature Request</b>

Hello! I have this issue where my directory path is horribly long and every time I run the code that I've been running, it first prints out two different directory paths, then my code and then a last directory path in the end of it all. It would be nice if it were possible to have options or a separate terminal that only shows what the program is supposed to be printing or running at the moment and the error messages ofcourse.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
You can do this by modifying your shell settings, for example on bash you could edit the `$PS1` variable.
