### ISSUE TITLE
Microsoft Pinyin Input Method：I only pressed the keyboard keys once on the terminal, It appeared twice

### ISSUE THREAD

**Issue by faydanube** [microsoft/vscode#116408]
- VS Code Version:
![image](https://user-images.githubusercontent.com/8817046/107604429-1f751780-6c6b-11eb-8426-ef1ade909631.png)

- OS Version:
![image](https://user-images.githubusercontent.com/8817046/107604408-0cfade00-6c6b-11eb-85b8-e1814c734d18.png)

Steps to Reproduce:
Microsoft Pinyin Input Method：I only pressed the keyboard keys once。

https://user-images.githubusercontent.com/8817046/107604699-d83b5680-6c6b-11eb-96ab-e1836949828d.mp4
In addition, Sogou Pinyin Input Method's Chinese cannot be input.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Tyriar** [comment]
Cannot reproduce the microsoft pinyin issue, for sogou I believe there are issues with it that need to be fixed within the IME (https://github.com/microsoft/vscode/issues/112856).
