### ISSUE TITLE
Enable extensions to contribute tiles to the welcome page

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#116414]
Add a contribution point for getting started entries such that extensions can provide getting started content in their package.json.

**Comment by JacksonKearl** [comment]
Oops wrong ref.

**Comment by JacksonKearl** [comment]
Entries look something like:
```
		"gettingStarted": [
			{
				"id": "ext.hello",
				"title": "Hello!",
				"description": "world",
				"button": {
					"command": "extension.helloWorld",
					"title": "Say Hello"  
				},
				"media": {
					"path": "hello.webp", 
					"altText": "Helloo" 
				}
			}
		],
```

**Comment by JacksonKearl** [comment]
This would be rendered like so:
![image](https://user-images.githubusercontent.com/8586769/108747435-4ac0f780-74f2-11eb-99f6-6976c96613ba.png)

![image](https://user-images.githubusercontent.com/8586769/108747489-56142300-74f2-11eb-83a9-cc620d3aad28.png)

**Comment by kieferrm** [comment]
@JacksonKearl which `when` clauses are supported?

**Comment by JacksonKearl** [comment]
Uses our standard `IContextKeyService#contextMatchesRules` service, so should be the same as any other place context keys are used.
