### ISSUE TITLE
First execution of PowerShell script changes context into debugger

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#11643]
**IMPORTANT**: I'm filing this more broadly on Visual Studio Code, at the request of @daviwil, after initially filing it on the PowerShell extension for VSCode.

### System Details

- Operating system name and version:
- VS Code version: 1.4.0
- PowerShell extension version: 0.7.2
- Output from `$PSVersionTable`: 

```
PS C:\Users\TrevorSullivan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.103
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.103
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Issue Description

When you open VSCode and run a PowerShell script, for the first time in the new session, the PowerShell Extension switches VSCode from the Explorer context, into the Debugging context. Subsequent executions do not do this.

### Reproduction Steps

- Open VSCode
- Open a project with a PowerShell script (in my case, a Pester test script)
- Hit F5 to run the script
- **NOTICE**: VSCode changes into debugging context, and script runs/exits
- Go back to Explorer context in VSCode (CTRL + SHIFT + E)
- Hit F5 to run the script again
- **NOTICE**: VSCode doesn't change into the debugger context

Originally filed here: https://github.com/PowerShell/vscode-powershell/issues/283

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by isidorn** [comment]
What does change into the debugger context mean?
If you mean opens debug console then this is as designed as you can configure the `internalConsoleOptions` in your launch.json.
More details can be found here https://github.com/Microsoft/vscode/issues/4045

If that is not the case, please let me know and I will reopen this issue - thanks!

**Comment by pcgeek86** [comment]
@isidorn It opens the Debugger pane on the Sidebar, which isn't necessarily desirable. Also, the behavior is inconsistent, because it does it the first time, but doesn't do it after that.
