### ISSUE TITLE
Unable to navigate neighbouring breadcrumb items using arrow keys

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#116410]
- VSCode version: 1.54.0-insider
- OS: macOS Catalina 10.15.7

Steps to Reproduce:

1.  Focus the breadcrumb using `command-shift-.`
2.  Breadcrumb is now focussed with dropdown open
3.  Press `<left>` or `<right>`
4.  Nothing happens instead of focussing on the previous/next breadcrumb item as described in the doc: https://code.visualstudio.com/updates/v1_26#_breadcrumbs
5. Similar thing happens when using `command-shift-;`. When dropdown is not opened, pressing `<left>` or `<right>` still works, but once the dropdown is opened using `<enter>`, I'm just stuck in the dropdown

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
That's the workbench tree eagerly eating left/right-arrow keys

**Comment by joaomoreno** [comment]
I wonder if it's a recent regression?

**Comment by jrieken** [comment]
> I wonder if it's a recent regression?

No, this has been like it ever since. The commands that bind left and right aren't properly guarded with context keys.

**Comment by shskwmt** [comment]
This line eats left / right arrow keys.

https://github.com/microsoft/vscode/blob/992cf6bd44d89f85b50199d52ff34ca14fd5358f/src/vs/workbench/browser/actions/listCommands.ts#L204

This secondary key binding will work.

https://github.com/microsoft/vscode/blob/992cf6bd44d89f85b50199d52ff34ca14fd5358f/src/vs/workbench/browser/parts/editor/breadcrumbsControl.ts#L566

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/commit/e5bcb02e1e9a32fb4ba1760914120dd219d25a4e
