### ISSUE TITLE
Review use of freshExecArgv when forking search process

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#116422]
https://github.com/microsoft/vscode/blob/474b4ae2d51c206fed97730675391d21fe6e3809/src/vs/workbench/services/search/electron-browser/searchService.ts#L68
freshExecArgv was needed to prevent that `--inspect-brk=` and `--inspect=` are inherited in the forked process where they would block the process from being started as the port is already in use.

I changed the IPC client to filter `--inspect-brk=` and `--inspect=` 
https://github.com/microsoft/vscode/blob/474b4ae2d51c206fed97730675391d21fe6e3809/src/vs/base/parts/ipc/node/ipc.cp.ts#L202

So `freshExecArgv: true` is no longer needed, unless this is preferred for other reasons

**Comment by aeschli** [comment]
> Do I want any of these to ever be inherited though? I can't think of any flags that are globally relevant to the Search process and also the renderer.

I'm also not aware any. In that case just update the comment.

**Comment by roblourens** [comment]
Sounds good
