### ISSUE TITLE
Copy from terminal only copies the last word

### ISSUE THREAD

**Issue by shanimal** [microsoft/vscode#116490]
Issue Type: <b>Bug</b>

When I try to use CMD+C to copy selected text from the terminal, it only lets me copy the last word. 

Steps:
1. Select text
2. Press CMD+C
3. Verify the clipboard contents

Notes: 
* select then Right click->"Copy" works as expected.
* double click select w/ CMD+C works as expected.

VS Code version: Code - Insiders 1.54.0-insider (fe6eb68d228472db7e656ffbf2b10f5e987fad48, 2021-02-10T05:12:20.339Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.29GB free)|
|Process Argv|-psn_0_581774 --crash-reporter-id 451718aa-c85b-47e7-b213-cb5e640c7c47|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
marko-beautify|bus|2.0.0
vscode-marko-peek|mar|1.1.1
marko|pca|0.4.0
qf|Wsc|6.8.122

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by meganrogge** [comment]
I can't reproduce the issue. Please send a [gif](http://gifcap.dev/) of this happening with screen cast mode enabled.
