### ISSUE TITLE
`code .` crashes if opened directly or from lxterminal

### ISSUE THREAD

**Issue by benlowry** [Microsoft/vscode#11640]
- VSCode Version: 1.40-1470329130_amd64.deb
- OS Version: Lubuntu / ubuntu trusty 14.04

Steps to Reproduce:
1. open vscode from gui

Or:
1. open `lxterminal`
2. type `code .`

```
/usr/bin/code: line 36: 26163 Aborted                 (core dumped) ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
```

It only seems to open from xterm / uxterm via `code .`

**Comment by jhasse** [comment]
I've seen this bug before on Linux.

Can you post the output of `env` in lxterminal? Or even better only the difference between its output in lxterminal vs xterm.

**Comment by benlowry** [comment]
These are in `xterm` and missing from `lxterm`:

XTERM_SHELL=/bin/bash
WINDOWID=54525988
XTERM_LOCALE=en_US.UTF-8
XTERM_VERSION=XTerm(322)

**Comment by jhasse** [comment]
Try setting each of these (using e. g. `export XTERM_SHELL=/bin/bash`) and see if that fixes the crash.

**Comment by benlowry** [comment]
Still no luck.  Is there a way to make it emit a more specific exception message?

**Comment by Tyriar** [comment]
@benlowry first off please update VS Code so you're on the latest version.

After that it looks like it's failing on the following line: https://github.com/Microsoft/vscode/blob/5b3afc132ef5d50670c1c43a2b9650da532f20e8/resources/linux/bin/code.sh#L36

So you can try tweaking that command. Maybe that shell has issues with setting the environment variable at the beginning of a line?
