### ISSUE TITLE
inconsistency when choosing search results in search panel

### ISSUE THREAD

**Issue by m-manohar** [microsoft/vscode#116482]
Issue Type: <b>Bug</b>

I have two editor groups, say group 1 and group 2. Group 1 has editor A. Group 2 has editor B. Group 2 - editor B is my active editor at this point. I initiate a "search in all files" for a string. I click on the search results in the search panel, which happens to be a string in editor A. I expect that editor A will be opened in Group 2. Instead what happens is that result is opened in Group 1, editor A.

This is a problem because I potentially lose my position in Group 1, editor A.

This problem is not seen if I do the same search with search editor instead of the search panel.

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 19.6.0

**Comment by JacksonKearl** [comment]
This is by design as we do not want to open a bunch of duplicate editors across your groups. You can however Cmd+Click on the result to open it in a new editor to the side of your existing ones.

**Comment by m-manohar** [comment]
There is a setting that already exists that when enabled, reveals an existing editor (in a different group) if it already exists when trying to open an editor in a new group. If the setting is disabled then a duplicate editor is opened. 

It would be good to give the user a similar option. It can be less than desirable to lose your place in an editor in one group, when trying to open search results in an other editor group. The cmd+click doesn’t work that great when you already have your layouts well set and it trying to cram one more editor to the side and shrinking the sizes of all the existing editors.
