### ISSUE TITLE
"experimentalDecorators" and "types" properties can't coexist in tsconfig

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11648]
Reported in gitter, I repro in 1.5-insider.

Have a tsconfig.json with `"experimentalDecorators": true` and `"types": []`. If you use a decorator in TS, you get that error "... set the experimentalDecorators option to remove this warning..." but if you delete the "types" property, then it does not complain about the decorator, as expected.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10790
