### ISSUE TITLE
Panel title bar overflows when there is still space

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#116423]
pls see the screenshot below

![image](https://user-images.githubusercontent.com/172399/107614595-e5941900-6c4a-11eb-8e7b-1b35de96b3d3.png)

**Comment by isidorn** [comment]
@egamma I can not reproduce this. Do you always see this? How do you get into this state?
fyi @sandy081

**Comment by egamma** [comment]
@isidorn I can always see this when the window is smallish

**Comment by egamma** [comment]
@isidorn more info:
- it happens when the width of the window is 1026 pixels
- to repro: Remote Containers> Try a Sample > Node

let me know if you still cannot reproduce this.

**Comment by sandy081** [comment]
@egamma I have tried multiple times to reproduce it but could not. If you are able to repro it consistently, is there something I am missing in the steps here?

**Comment by sandy081** [comment]
@egamma Can you please try again and see if you can repro it?

**Comment by egamma** [comment]
closing in favor of https://github.com/microsoft/vscode/issues/116424

**Comment by sandy081** [comment]
@egamma Can you please try reproducing this again (tomorrow's insiders) - are you seeing overflow action even if there is enough space ?
