### ISSUE TITLE
error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by sv4154** [microsoft/vscode#116479]
Issue Type: <b>Bug</b>

I get the error mentioned in the tile when i try to execute git clone.

SV4154@ILCDTL00SV4154 MINGW64 /c/RepoSync (master)
$ git clone https://ACC-Azure-01@dev.azure.com/ACC-Azure-01/15235_BIRT/_git/15235_BIRT.oracle_pipeline.sv4154
Cloning into '15235_BIRT.oracle_pipeline.sv4154'...
fatal: unable to access 'https://dev.azure.com/ACC-Azure-01/15235_BIRT/_git/15235_BIRT.oracle_pipeline.sv4154/': error:1408F10B:SSL routines:ssl3_get_record:wrong version number

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.93GB (7.29GB free)|
|Process Argv|--crash-reporter-id e18ce86f-ee10-4670-a7c8-4b46950fd567|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by eamodio** [comment]
This is an issue with Git not vscode, so I would suggest asking on StackOverflow or similar community.
