### ISSUE TITLE
Simple file dialog: Doesn't allow me to go back to root

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#116457]
Version: 1.54.0-insider (user setup)
Commit: 93f705ab40b37aade9d3b5165ed09114a8c87ac9
Date: 2021-02-11T05:44:31.644Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

- In a remote window (e.g. WSSL), invoke `Open Folder...`
- The simple file dialog opens, e.g. on my home folder.
- Use `..` to get to the root to be able to navigate to `/mnt/`

-> no '..' once I reached the `/home`/

![image](https://user-images.githubusercontent.com/6461412/107643709-d1661100-6c76-11eb-86eb-e0ed2b46940e.png)

**Comment by alexr00** [comment]
To escape from this bug until it is fixed, you can delete from the inputbox.
