### ISSUE TITLE
Threat detected

### ISSUE THREAD

**Issue by dnavarrokawak** [microsoft/vscode#116478]
Issue Type: <b>Bug</b>

MS Defender Detect this:

Trojan:Win32/Zpevdo.B
file: C:\Program Files\VSCodium\resources\app\out\vs\platform\files\node\watcher\win32\CodeHelper.exe

VS Code version: VSCodium 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-10T00:32:28.070Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.69GB (9.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-html-css|ecm|1.9.1
vsc-material-theme-icons|equ|1.2.2
svn-scm|joh|2.13.5

</details>

**Comment by joaomoreno** [comment]
> VSCodium

We do not distribute VS Codium. I suggest you report this to the VS Codium project.
