### ISSUE TITLE
Open new tab for same file name under different directory

### ISSUE THREAD

**Issue by saml** [Microsoft/vscode#11644]
When there are files named the same but under different directories, they are all opened in the same tab.
Not sure if this is intended feature or a bug.

- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Create the following tree:
    ```
    ./foo/a.js

    ./bar/a.js
    ```
2.  open `foo/a.js` and `bar/a.js`
    - Expected: two tabs are open one for `foo/a.js`, another for `bar/a.js`
    - Actual: `bar/a.js` is opened at the same tab of `foo/a.js`.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreview": false`
