### ISSUE TITLE
map key to another key

### ISSUE THREAD

**Issue by JGStyle** [microsoft/vscode#116553]
It would be amazing if it were possible to map a key on the keyboard to another key on the keyboard only within vscode. 

For example I would like to map caps lock to escape, BUT only in vscode.

this can improve productivity by a lot.

**Comment by dominicpalmer** [comment]
If it helps, this is possible to achieve on Windows using external keymapping software such as AutoHotKey. There are equivalents to AutoHotKey for unix based systems too. You'd simply need to write a script that maps capslock to escape only when the code executable is running. Would look something like:

```autohotkey
#If WinActive("ahk_class VSCode")
CapsLock::Escape
```

**Comment by JGStyle** [comment]
Thanks, but im on Mac - do you know a similar program to do that on OS X?

**Comment by dominicpalmer** [comment]
I would take a look at Karabiner: https://karabiner-elements.pqrs.org/
