### ISSUE TITLE
Pressing Page up/Page down in search moves window

### ISSUE THREAD

**Issue by mattiacoll** [microsoft/vscode#116555]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.1902

Steps to Reproduce:

1. open vscode
2. open the search bar (ctrl + f)
3. type any character in the search bar (doesn't work if empty)
4. in the search bar press pagedown/pageup key

The bug persists until the windows is resized or closed and opened again.

Does this issue occur when all extensions are disabled?: Yes

![diff](https://user-images.githubusercontent.com/64754556/107777907-ba412500-6d43-11eb-8b9c-a272cc94a5c6.jpg)

**Comment by roblourens** [comment]
Can't repro this. Is your window zoomed?

**Comment by mattiacoll** [comment]
The issue is present on any zoom level, the more you zoom in the more visible the effect is.
I checked again and the issue appears only with the pageup key.

Opening, or having open the bottom panel (the one with debug/terminal/ecc.) seems to prevent the issue if there is only one editor open, if there is more than one editor open, only when vertically split not horizontally split. seem to make the issue reappear.

I attach a video to show the issue.

https://user-images.githubusercontent.com/64754556/107814346-0c00a400-6d72-11eb-9d1f-7245273c572f.mp4

**Comment by roblourens** [comment]
Still can't repro, tried messing with zoom and windows scaling factor. But maybe @rebornix knows something about it.
