### ISSUE TITLE
Marketplace doesn't show updated README.md

### ISSUE THREAD

**Issue by scout119** [microsoft/vscode#116567]
Issue Type: <b>Bug</b>

Not sure if this is the right place to submit this bug, but here it is.

I have an extension for Visual Studio Code:
https://marketplace.visualstudio.com/items?itemName=Valentin.beamdasm

I have changed my main branch from "Master" to "Main". README.md has local links (not absolute for the media and the license). It looks like README.md is cached on the Marketplace and shows absolute links pointing to the old "Master" branch:

The folowing two links:
https://github.com/scout119/beamdasm/raw/master/media/main.gif
https://github.com/scout119/beamdasm/raw/master/media/highlight.png

should be:
https://github.com/scout119/beamdasm/raw/main/media/main.gif
https://github.com/scout119/beamdasm/raw/main/media/highlight.png

Same for the license link at the bottom:

https://github.com/scout119/beamdasm/blob/master/LICENSE.md

should be:

https://github.com/scout119/beamdasm/blob/main/LICENSE.md

Thank you

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by joaomoreno** [comment]
Related:

- https://github.com/microsoft/vscode-vsce/issues/504
- https://github.com/microsoft/vscode-vsce/issues/514

For now you must pass `--githubBranch` to VSCE when publishing your extension.
