### ISSUE TITLE
saas compiler not working

### ISSUE THREAD

**Issue by saiprashanthvs** [microsoft/vscode#116573]
We have written the needed data into your clipboai have installed the live saas compiler but my text editor is not showing the watch saas .so i am not able to compile my saas filerd because it was too large to send. Please paste.

**Comment by saiprashanthvs** [comment]
i have installed the live saas compiler but my text editor is not showing the watch saas .so i am not able to compile my saas file

**Comment by weinand** [comment]
Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions to learn how to write bug reports.
