### ISSUE TITLE
List installed extensions in issues created via Help > Report issues

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11655]
This would save some questioning after an issue is filed. Command line args may also be useful?

**Comment by hashhar** [comment]
I can look into implementing it.

**Comment by hashhar** [comment]
How would you like the list. The generated url must be less than 2k characters which is a pretty tight limit. I was thinking of generating gists using an open Id with tokens for write access and then link the gist url to the issue body.

Do you have a better approach @joaomoreno, @Tyriar?

**Comment by joaomoreno** [comment]
Just something similar to what `code --list-extensions` gives you in the command line, with the additional version info.

```
$ code-insiders --list-extensions
Poorchop.theme-darktooth
aalaap.theme-toothpaste
danibram.theme-flatui
```

**Comment by hashhar** [comment]
Okay. So I am able to get a list of the extension but somehow I stupidly ended up deleting my ~/.electron.gyp folder and can't clone the repos since right now I can't use git (network restrictions). I think I'll be able to send a PR with unit tests within the week.

**Comment by Tyriar** [comment]
The current URL is around 250-300 characters, how many extensions do we expect people to have? I would have expected 20-30 characters each for name+version, I have less than 10 and we can always truncate the list if necessary?

**Comment by hashhar** [comment]
@Tyriar I think that's fine. I'll go the URL way. We can actually use upto 8000 characters but people on older browsers may have issues.

Oh and one thing. Why isn't the smiley to report issues not visible on the debug builds? How can I enable it?

**Comment by hashhar** [comment]
Now that I think about it, we don't even have to truncate the list. The browser will do that and the only side effect will be partial information about the extensions in the issue. So I think it doesn't matter that much.

**Comment by hashhar** [comment]
Hey, I'm unable to hit breakpoints that I set in .ts files. I'm using remote debugging from VSCode. Could someone guide me how to debug this?

**Comment by Tyriar** [comment]
@hashhar I run via ./scripts/code.sh and use dev tools in the debug vscode personally

**Comment by hashhar** [comment]
```
import * as vscode from 'vscode';
...
for (var i = 0; i < vscode.extensions.all.length; ++i) {
	var ext = vscode.extensions.all[i];
```

This shows no errors from within VSCode, but on compiling I get:
```
{ errorCode: 'load',
  moduleId: 'vscode',
  neededBy: [ 'vs/code/electron-main/menus' ],
  detail: { [Error: Cannot find module 'vscode'] code: 'MODULE_NOT_FOUND' } }
```

**Comment by Tyriar** [comment]
@hashhar that's the extension API, I think you want to use the `ExtensionWorkbenchService` in the vscode code base https://github.com/Microsoft/vscode/blob/52bceb1207188ecfe8c5b1fbe841b60df512a08a/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L245

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/18909855/8ff9e990-8575-11e6-9d4c-18927380362b.png)

**Comment by joaomoreno** [comment]
Thanks @bpasero !
