### ISSUE TITLE
Consider to wrap languagePacks.js into self-invoking function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116546]
While working on https://github.com/microsoft/vscode/pull/116530 I noticed how our 2 modules that are shared in common.js and AMD world are not wrapped in a function scope:
* [`languagePacks.js`](https://github.com/microsoft/vscode/blob/f45816452265c60b7a65f7392686feb7acc96cac/src/vs/base/node/languagePacks.js#L7-L7)
* [`performance.js`](https://github.com/microsoft/vscode/blob/ce1ffe0e7f891f886b6e7b36b86591f11430e2c8/src/vs/base/common/performance.js#L6-L6)

Not wrapping them into a function scope will hoist all functions up when the bundler moves all modules into a single file. They do not end up in the global (`window`) scope, but there is a chance that we end up with the same function defined multiple times stepping on each other's toes (this is what happened in my PR and was visible in failing integration tests luckily).

I would have just pushed a change to wrap `performance.js` into a self-invoking function (like I did here: https://github.com/microsoft/vscode/pull/116530/commits/b84ed1f6dc4182422d8366ad46cd0318a55759ab) but then noticed that there seems to be a `sharedObj` where hoisting seems to be intentional (not sure?). So leaving it up to you to decide if we can simply add a function scope around it or not.

//cc @alexdima

**Comment by jrieken** [comment]
Yeah, that's from a time in which we would support to load performance without any module system into the browser. This isn't needed anymore

**Comment by jrieken** [comment]
Back to you for languagePacks.js

**Comment by bpasero** [comment]
@dbaeumer I think you own that

**Comment by dbaeumer** [comment]
@bpasero looks like you already did this. See your commit 41339cc2a0844f97315a746b89022d7b51477432

OK to close?

**Comment by bpasero** [comment]
True
