### ISSUE TITLE
Can't run a cell after opening a second notebook and switching back to the first

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#116516]
- VS Code Version: 1.54.0-insiders and 1.53.2 stable
- OS Version: Windows 10

Steps to Reproduce (Warning, this isn't reproducible by everybody. However, I can repro it very very consistently)

1. Open a Python notebook in the native notebook experience.
2. Run a cell
3. Open a second notebook
4. Switch back to the first notebook
5. Run a cell

Cell no longer runs.

Internally, when the bug occurs, our VSCodeNotebookKernelMetadata.executeCell() is not being called. This seems to indicate that the bug is more likely somewhere in the VS Code codebase.

**Comment by jrieken** [comment]
> This seems to indicate that the bug is more likely somewhere in the VS Code codebase.

Maybe not, this doesn't reproduce with GH issue notebooks. Please check on your side and then provide a minimal repo sample

**Comment by jrieken** [comment]
ping @greazer

**Comment by greazer** [comment]
@rebornix, can you provide @jrieken what we discovered in our debug session on this? (perhaps you entered a different bug... looking after I enter this)

**Comment by greazer** [comment]
I believe it was related to this issue, #117077

**Comment by rebornix** [comment]
@greazer I already pushed a fix for it but didn't link with this issue   

fixed via https://github.com/microsoft/vscode/commit/ba3bd11ac7f1879245d865b837361e4bb6f07892
