### ISSUE TITLE
Failed to install 'ms-dotnettools.csharp'.

### ISSUE THREAD

**Issue by drjedo1** [microsoft/vscode#116524]
Issue Type: <b>Bug</b>

I use 
MacBook Pro (Retina, 13-inch, Early 2015)
macOS Big Sur version 11.2

I saw this error : 
"Failed to install 'ms-dotnettools.csharp'."

then i clicked the button : "Download Manually"

file downloaded, and I saw following message : 

Once downloaded, please manually install the downloaded VSIX of 'ms-dotnettools.csharp'.

and I clicked the button : "Install from VSIX..."

and here it is problem. 

I chose downloaded file, and I clicked the button : "Install"

and there's no response.

I click again the button : "Install" from Extension search manu.
and this problem didn't solve

VS Code version: Code 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T09:14:32.385Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/private/var/folders/bx/d17zh1gj3q17sf9zmj7xstyr0000gn/T/AppTranslocation/C0BC7BF8-A841-4866-8A4B-C2A2049739A7/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-clang|mit|0.2.3
cpptools|ms-|0.21.0

</details>

**Comment by gjsjohnmurray** [comment]
Your VS Code version  is ancient. Please update to the latest, which is 1.53.2

**Comment by sandy081** [comment]
Please try with latest and let us know if you still have this issue.
