### ISSUE TITLE
dragging folders into terminal no longer works correctly

### ISSUE THREAD

**Issue by brad-provident** [microsoft/vscode#116583]
I used to be able to change directory by typing "cd " into the terminal panel and then dragging the folder from the workspace list on the left. But now, doing that doesn't work when the path includes backslash-escaped spaces. 

I noticed also that the path, when resulting from a drag like this, is quoted with single quotes. When I do the same path without the quotes, it works. I think the quote marks might be new, and that is what is causing it to fail.

Being able to drag the folder from the workspace list to the terminal is very important for me, as I need to switch directories a lot, and I'm not willing to type those long paths with escapes manually. Apple's Terminal problem does not have this problem.

**Comment by fokke-m** [comment]
I noticed the same behavior. I think this was introduced in the latest update. I too drag folders into terminal because it's a major time saver. It is still possible to copy the (relative) path in the file explorer and paste it in the integrated terminal.

**Comment by Tyriar** [comment]
Can you take a screenshot of the path after it's pasted?

**Comment by fokke-m** [comment]
> Can you take a screenshot of the path after it's pasted?

After the path is pasted or after the file is dragged?

**Comment by meganrogge** [comment]
after it's dragged

**Comment by brad-provident** [comment]
![image](https://user-images.githubusercontent.com/18450830/108101367-f8885e00-703b-11eb-8fbb-d864ab891768.png)

**Comment by brad-provident** [comment]
I think it has to either do quotes or escaping, but not both (unless maybe escaping quotes).

**Comment by Tyriar** [comment]
@brad-provident thanks for the info, makes sense.
