### ISSUE TITLE
Please keep the "Open recent" items on the "Welcome" window

### ISSUE THREAD

**Issue by silvioprog** [microsoft/vscode#116581]
Hi.

The last VSCode Insiders update showed the following "Getting Started" window:

![image](https://user-images.githubusercontent.com/1456829/107814342-83bdd700-6d50-11eb-9eb1-ae9782d50bc4.png)

Will this new feature remove the "Welcome" window and its "Recent" items 😕?:

![image](https://user-images.githubusercontent.com/1456829/107815510-3e020e00-6d52-11eb-9412-b3452d773ce5.png)

 If so, is there any (official) extension to keep showing the recent opened files and directories at VSCode startup?!

I have been using VSCode for years, then all those tips showed in the new "Getting Started" window are known, so keeping the "Recent" items would be much more useful. Tip: show the new "Getting Started" window, but please keep the "Welcome" too, or at least any option to open the recent items just by one click at any main window item, without using menus/shortcuts.

cheers

**Comment by IllusionMH** [comment]
First screenshot is "Getting Started" page, not Welcome page (secons screenshot).
Just uncheck "Show Getting Started page on startup" and restart VS Code to get that Welcome page on startup.

Or access it directly from menu Help > Welcome.

**Comment by silvioprog** [comment]
Is there any option to start VSCode with "Welcome" page instead of "Getting Started"? Because after unchecking the option `Show Getting Started page on startup` it still opening "Getting Started", as showed below:

![video](https://user-images.githubusercontent.com/1456829/107820926-642bac00-6d5a-11eb-8030-8798ea5b2cde.gif)

**Comment by silvioprog** [comment]
It was fixed after uninstalling and reinstalling the VSCode. After that, just open the Welcome page and restart VSCode!

**Comment by IllusionMH** [comment]
Sounds too complex in your case.

I've completed steps from both sections (but I guess this is optional), unchecked, clicked Skip, restarted VS Code to get Welcome page.
