### ISSUE TITLE
Hook for detecting terminal clear

### ISSUE THREAD

**Issue by Riphiphip** [microsoft/vscode#116541]
I am currently working on an extension that requires me to write a command line based on vscode.Pseudoterminal.
For my application, clearing the terminal requires a bit of work behind the scenes, but I have yet to find a good way to detect when this is done through the command pallette or context menu.

If this exists, I must apologize for mislabeling this as a feature request, but if it doesn't it would be very nice to have.

**Comment by Tyriar** [comment]
@GabeDeBacker do you have thoughts on this? Perhaps we should just disallow Terminal: Clear for `vscode.Pseudoterminal` terminals?
