### ISSUE TITLE
Auto close bracket in commit message

### ISSUE THREAD

**Issue by ASponch** [microsoft/vscode#116584]
Hello,

It seems to be cool that in the "commit message" textarea their is an autoclose function.

For example,
- [Fix] bla bla
- [Update] bla bla
- [Patch] bla bla
and so...

Or better, a suggest of "tag prefix".

Best regards

**Comment by gencer** [comment]
If I remember correctly, VSCode already had this feature. And I was very happy with it. But after (i do not remember which version) some time, it is dropped.

I also interested in this.
