### ISSUE TITLE
[Feature] Allow Grouping Breakpoints by File

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#116594]
It would be helpful to group breakpoints by file. Even if it is a setting that can be toggled to change grouping behavior.

An extension to this feature request would be to allow disabling / deactivating breakpoints by file.

This would be extremely helpful for a large code base with several breakpoints

(e.g. grouping by file or by conditional vs. non-conditional breakpoints)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
