### ISSUE TITLE
Windows UE-V with OneDrive and VSC generating large sync files on exit

### ISSUE THREAD

**Issue by jstromergalley** [microsoft/vscode#116575]
Version: 1.53.1 (system setup)
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:29:42.785Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. With UE-V enabled and the SettingsPackages folder on OneDrive
2. Open VSC and open a folder then close VSC
3. 10-20 seconds later 100meg of *.pkgdat and Microsoft-VisualStudioCode.pkgx will sync to OneDrive

Does this issue occur when all extensions are disabled?: Yes (55meg Microsoft-VisualStudioCode.pkgx )

![vsc](https://user-images.githubusercontent.com/446829/107806174-78f54900-6d34-11eb-8622-84384346126c.jpg)

It is my understanding that Microsoft UE-V is expecting files in this folder to be a couple of k not 100s of meg. For example, the MicrosoftOffice2016Win64.Outlook.pkgx  file is 3k and does not seem to grow.

This is a bit of a problem for me when working remotely and attempting to switch tasks or close VSC.

**Comment by bpasero** [comment]
I am not sure I understand how this happens or if VSCode is to blame, need more eyes on this issue.

**Comment by joaomoreno** [comment]
I think this just might be the default behavior of an Electron app under UE-V. This might require adoption. AFAIK we don't support UE-V for now, so this can either be closed or turned into a feature request.

**Comment by jstromergalley** [comment]
What more information do you seek?

> UE-V is an enterprise Microsoft technology: https://docs.microsoft.com/en-us/microsoft-desktop-optimization-pack/uev-v2/
> The electron version of Slack produces no files to sync on close, so this is not conceptually an unfixable problem.
> Other Microsoft products produce tiny files to sync on close.

This seems like something that should both be supported and fixable. If someone points me to where these "settings" are being created/persisted in the code I might be able to do something to fix it as well. I just don't know this codebase at all.

**Comment by deepak1556** [comment]
I am not familiar with UE-V to suggest where the issue might be in the runtime or what needs to be done. Keeping this open as a feature request for now.
