### ISSUE TITLE
Blackscreen / Freezing

### ISSUE THREAD

**Issue by Rc-Cookie** [microsoft/vscode#116526]
- VS Code Version: 1.53
- OS Version: Windows 10 version 20H2 build 19042.746

Steps to Reproduce:

1. Open VS Code
2. Open more VS Code windows or other programs (~3 more)
3. To start fresh again, restart the computer

Result: A some point VS Code starts up but stays in the dark gray startup screen. Already opened windows also freeze in their current state.

However all windows still work just fine, you can edit stuff in them, run commands or get hints when hovering the mouse over where the side bar is. So it seems to be a graphical error.

Downgrading to 1.52 seemed to help. Other fixes, like running --disable-gpu, deleting cache, reinstalling or using insiders has not helped.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/114459

Can you try starting the app with `--disable-features=CalculateNativeWinOcclusion`.
