### ISSUE TITLE
Sync Settings auto disabled

### ISSUE THREAD

**Issue by ashfaque** [microsoft/vscode#116520]
Issue Type: <b>Bug</b>

Sync settings is auto disabled. And shows a notification on the lower right corner that its making too many request.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2030 @ 3.00GHz (2 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.96GB (1.08GB free)|
|Process Argv|--crash-reporter-id e28bf9cd-7287-441b-870d-3230b1d2fa61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
python-preview|don|0.0.4
prettier-vscode|esb|5.9.2
code-runner|for|0.11.2
vsc-python-indent|Kev|1.12.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.5.0
errorlens|use|3.2.4
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled? Perhaps one of your extensions is changing a synced setting too frequently. The Extension Bisect command may help you to investigate.
