### ISSUE TITLE
Feature - Collapse parent folder

### ISSUE THREAD

**Issue by shanimal** [microsoft/vscode#116572]
I have to scroll-up, through maybe a hundred folders in **node_modules** to collapse it. 

As a user I want to right click the folder and select "Collapse Parent".
_(Alternatively, add an icon to the right edge of the hovered menu.)_

<img width="609" alt="README_md_—_motorsweb" src="https://user-images.githubusercontent.com/283957/107804655-fd39d300-6d18-11eb-8ea4-642a97f5921c.png">

**Comment by IllusionMH** [comment]
Just in case you already can just <kbd>ArrowLeft</kbd>(to selects parent) <kbd>ArrowLeft</kbd> (closes parent) as many times as you like.

**Comment by isidorn** [comment]
@IllusionMH thanks for answering the question

No further action planned here, thus closing
