### ISSUE TITLE
Blurry Text regression

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#116566]
Issue Type: <b>Bug</b>

With 1.53 the blurry text has reappeared.
This seems to have a resurgence every now and then with VSCode.
See the picture down below, especially the `|` is pretty unsharp.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

![grafik](https://user-images.githubusercontent.com/2277182/107800007-83c4d380-6d5e-11eb-9d8e-c3da39fa0b93.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.30GB free)|
|Process Argv|--crash-reporter-id 6ad73eb2-e24b-4305-a8ef-19341314fe6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
ifc-syntax|Ala|0.1.4
Bookmarks|ale|12.1.4
spellright|ban|3.0.56
change-color-format|bbu|1.0.0
gitignore|cod|0.6.0
aoe2-rms|del|0.3.3
rhinopython|des|0.1.11
dotfiles-syntax-highlighting|dot|0.1.0
vscode-gitignore-syntax|dun|0.1.2
EditorConfig|Edi|0.16.4
vscode-open-in-application|fab|1.0.5
auto-close-tag|for|0.5.10
gc-excelviewer|Gra|3.0.41
gdl|Gra|1.24.3
vscode-guid|hea|1.4.20
reg|ion|1.0.2
aoe2-aiscript|jvi|0.1.7
vscode-markdown-notes|kor|0.0.22
nim|kos|0.6.6
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.0
hexeditor|ms-|1.4.0
powershell|ms-|2020.6.0
sublime-keybindings|ms-|4.0.7
resourcemonitor|mut|1.0.7
printcode|nob|3.0.0
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
run-on-save|puc|1.4.0
gruvbox-material|sai|6.3.6
sonarlint-vscode|Son|1.20.1
language-stylus|sys|1.11.0
vscode-open-in-github|sys|1.14.0
tabnine-vscode|Tab|3.2.7
markdown-links|tch|0.8.0
open-in-browser|tec|2.0.0
shell-launcher|Tyr|0.4.1
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alexdima** [comment]
@runxel Does this reproduce with a fresh user data dir? (I'm trying to rule out any vscode settings as the root cause). 

* Close all instances of vscode
* run `code --user-data-dir=C:\my\new\folder`
