### ISSUE TITLE
VSCode disappears on taskbar when update is available

### ISSUE THREAD

**Issue by joshxyzhimself** [microsoft/vscode#116506]
Ubuntu Linux 20.04

![image](https://user-images.githubusercontent.com/60829711/107707361-b6d67b00-6cfc-11eb-85b3-5b1363a81427.png)

Problem:

![image](https://user-images.githubusercontent.com/60829711/107707336-a9b98c00-6cfc-11eb-8de2-5dfed3d7d1f6.png)

Should be like this:

![image](https://user-images.githubusercontent.com/60829711/107707436-d1105900-6cfc-11eb-8800-00c45dd36834.png)

**Comment by joshxyzhimself** [comment]
still visible on alt-tab but not on taskbar

**Comment by joaomoreno** [comment]
This is because the snap daemon already updated code in the background, but the running instance is still pointing to the old code. Unfortunately, I'll close this as won't fix.

**Comment by joshxyzhimself** [comment]
All cool thanks for info
