### ISSUE TITLE
Rename folder or file not working

### ISSUE THREAD

**Issue by ant-g** [microsoft/vscode#116554]
Issue Type: <b>Bug</b>

1. Create a new folder, or try to rename a file or folder in explorer window.
2. Attempt to type in new or editted name
3. Edit field aborts returning to standard explorer view (if you continue typing it goes to the filter box) - this can happen immediately or a fraction of a second (2-3 characters in) after typing.

This problem existed for me briefly in the past but then went away, it appears to be back.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (23.10GB free)|
|Process Argv|--crash-reporter-id 6bb05d28-981b-4ed5-ba97-56778b61f605|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
apacheconf-snippets|eim|1.3.0
php-debug|fel|1.14.9
todo-tree|Gru|0.0.196
php-namespace-resolver|Meh|1.1.8
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vs-keybindings|ms-|0.2.0
vetur|oct|0.32.0
laravel-blade|one|1.25.0
seti-icons|qin|0.1.3
java|red|0.75.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt600cf:30251589

```

</details>

**Comment by isidorn** [comment]
I can not reproduce this. But let's keep this open so maybe somebody comes with an exect reproducable step.
Also can you repro with vscode insiders https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
@ant-g does this still happen after you run the Command Palette command to reload with all extensions disabled? If that fixes it, reload again to enable your extensions, then use the Extension Bisect command to identify which one is causing the problem.

**Comment by ant-g** [comment]
It seems to work ok with Insiders.
  
However, the arrow cursors do not work without Shift held down.
i.e. When editing file/folder name it will highlight the whole text by default, if I want to deselect the text and move to a point in the title I would normally press arrow left or right, this does not work.

If I hold shift I can arrow left and the selected text will move back from the end of the title, I can arrow right to reselect.
I can click with the mouse in the middle of the text and then hold shift and arrow left or right to select text.

This may be intended behaviour, but would not be my choice as it requires very accurate mouse aim unless you always replace the full text.

**Comment by ant-g** [comment]
@gjsjohnmurray This still happens when running with extentions disabled

**Comment by ant-g** [comment]
@gjsjohnmurray , @isidorn  This is now working again?!

So in essense I was experiencing the problem all morning including with a couple of restarts of vscode, which led me to raise the bug.  
I downloaded and installed vscode insider as per above request - worked correctly as described.
I shut down and reopened vscode and problem persisted (this was me trying to run without extensions, but then realised I hadn't correctly done this)
Shut down and ran `code --disable-extensions` from the command line, problem persisted.
Shut down and reopened to re-enable extensions, I no longer have the problem.

Not sure if this will help track down an intermittent issue, but thought it was worth reporting.

**Comment by bogem** [comment]
@gjsjohnmurray Thank you for the tip! From Extension Bisect I figured out that VSCodeVim made problems for me

**Comment by bogem** [comment]
See https://github.com/VSCodeVim/Vim/issues/6201

**Comment by gjsjohnmurray** [comment]
:+1:
Please close this issue.

**Comment by ant-g** [comment]
> 👍
> Please close this issue.

VSCodeVim/Vim#6201 is not the issue that I was seeing, but as my issue has not reoccured I will close.
