### ISSUE TITLE
Code cell right hand padding is missing

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#116532]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/3372902/101020263-82ad4400-356e-11eb-9b1b-ebc2f3a9e541.png">

**Comment by jrieken** [comment]
@lszomoru you mean the editor, right?

**Comment by jrieken** [comment]
We should maybe switch to line wrap sooner

**Comment by misolori** [comment]
I believe we intentionally left this out as it matches the editor:

![image](https://user-images.githubusercontent.com/35271042/107800415-9bc33580-6d13-11eb-9aa6-1d22ac48e96f.png)
