### ISSUE TITLE
I'm able to see run button for Python but couldn't find run button for Java and C/C++.

### ISSUE THREAD

**Issue by arrayappy** [microsoft/vscode#116592]
I'm using vscode insiders on **Apple Silicon**, I have installed all the required extensions(Python, Java, C/C++). **I'm able to see run button for Python but I'm couldn't find run button for Java and C/C++.** I'm able to run these languages via terminal without installing anything.
Please check below screenshots once,
<img width="765" alt="image" src="https://user-images.githubusercontent.com/46554685/107837662-10f04280-6dc8-11eb-82ca-bd1b5a313d69.png">
<img width="764" alt="image" src="https://user-images.githubusercontent.com/46554685/107837672-1c436e00-6dc8-11eb-81d2-967b9d598476.png">

**Comment by gjsjohnmurray** [comment]
Go here:

![image](https://user-images.githubusercontent.com/6726799/107838736-30bf4080-6d9f-11eb-8c36-8f08005b9c4a.png)

/question
