### ISSUE TITLE
code-insiders cannot be launched on Windows

### ISSUE THREAD

**Issue by kejxu** [microsoft/vscode#116512]
- VS Code and OS Version:
```
Version: 1.54.0-insider (user setup)
Commit: 40b3204d70a9c72305c613164272175d0b344b5f
Date: 2021-02-10T17:39:27.208Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

just noticed that the file structure for code-insiders changed to:

```
 Directory of C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders

02/10/2021  06:09 PM    <DIR>          .
02/10/2021  06:09 PM    <DIR>          ..
02/10/2021  06:09 PM    <DIR>          bin
02/10/2021  06:09 PM    <DIR>          locales
02/04/2021  03:58 PM    <DIR>          resources
02/10/2021  06:09 PM    <DIR>          swiftshader
02/10/2021  01:51 PM    <DIR>          tools
02/10/2021  01:51 PM        92,257,520 unins000.dat
02/10/2021  01:51 PM         2,627,472 unins000.exe
02/10/2021  01:51 PM            23,365 unins000.msg
02/10/2021  01:51 PM    <DIR>          _
               3 File(s)     94,908,357 bytes
               8 Dir(s)  683,068,620,800 bytes free
```

and the "Code - Insiders.exe" executable is moved inside the `_` directory. For this reason, the default shortcut (pointing to `"C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe"``) and `PATH` variable does not work anymore

**Comment by joaomoreno** [comment]
> just noticed that the file structure for code-insiders changed to:

This was very likely due to a broken update process. Can you completely uninstall and reinstall VS Code? If it happens again, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

**Comment by kejxu** [comment]
> This was very likely due to a broken update process. Can you completely uninstall and reinstall VS Code? If it happens again, can you try disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.

Thanks! I was wondering if this can be recovered, but I'll go ahead and reinstall =)
