### ISSUE TITLE
Accessibility: Shift+Tab gets trapped in debug and problems panes.

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode#116525]
Issue Type: <b>Bug</b>

1. In any file, open the Problems view by clicking on the status bar icon.
2. With focus in the pane, shift+tab until you reach the Filter text field.
3. Press Shift+Tab again. Focus lands on the Close Panel button.
4. Press Shift+Tab again.
   * Expected: Focus moves to the bar of tabs where Problems, Output, Debug and Terminal are located by default.
   * Actual: Focus returns to the Filter text field.
5. Repeat the same in the Debug console.
   * Here, too, the keyboard focus with Shift+Tab gets trapped between the Filter text field and the Close Panel button.

This might be a regression from the recent #106441 work.

VS Code version: Code - Insiders 1.54.0-insider (6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197, 2021-02-12T05:14:39.860Z)
OS version: Darwin arm64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 4ea43554-4a6d-4f7c-b2fb-6de1a3610d98|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.15
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.23.1
beautify|Hoo|1.5.0
jstl|jsx|1.0.4
flutter-intl|loc|1.13.0
vscode-docker|ms-|1.9.1
vscode-edge-devtools|ms-|1.1.3
python|ms-|2021.2.529263813-dev
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.159.0
debugger-for-edge|msj|1.0.15
nunjucks|ron|0.3.0
vscode-webhint|web|1.5.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30233467
coreuntitledfile:30249963

```

</details>

**Comment by isidorn** [comment]
Good catch, yes this is a regression. It happens in debug console and problems since there we have input fields as part of the toolbars. Will look into fixing this.
