### ISSUE TITLE
latest update pop up still opened

### ISSUE THREAD

**Issue by alp-ex** [microsoft/vscode#116552]
Issue Type: <b>Bug</b>

"restart vscode" pop up appear each time i open the editor, I doubt that you push update each hours :sob:

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|. --crash-reporter-id b38eb96f-5ad0-4387-a97b-1472b859e24d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
carbon-now-sh|eri|1.2.0
auto-rename-tag|for|0.1.6
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
material-icon-theme|PKi|4.5.0
vscode-surround|yat|1.0.2

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
1.52.2 was released yesterday, but the version info you posted still shows 1.52.1.

**Comment by joaomoreno** [comment]
Looks like an Electron failing to apply update.

**Comment by alp-ex** [comment]
for some reason after closing very hard my vs code, it was successfully released to 1.53.2 🎈 🥳 
i guess @joaomoreno  was right !

I'm closing this as it was not rocket science to resolve this on my side
