### ISSUE TITLE
Debugger viewlet not choosing the right target

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11653]
- VSCode Version: 1.5.0 Insider
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Clone Microsoft/vscode
2. Open the folder using VSCode Insider. Make sure chrome debugger extension is not installed.
3. Choose `Unit Test` in debug viewlet, and enable a breakpoint that will be hit.
4. When the breakpoint is hit, change the target to `Launch VSCode` (which has `type: chrome`).
5. Click Run icon. It falls back to `Unit Test` instead of running `Launch VSCode` or produce an error saying "Debug type `chrome` is not supported".

![debug-viewlet-wrong-target](https://cloud.githubusercontent.com/assets/4033249/18328277/f82a1978-7502-11e6-9642-b18ef2f76dcd.gif)

**Comment by ramya-rao-a** [comment]
Is it even a valid operation to change launch configurations in the middle of a debug session?

**Comment by octref** [comment]
@ramya-rao-a 
If it's invalid I think the dropdown should be grayed out. The current behavior is unexpected.

Other than that, changing the target and relaunching also has the same problem.

Maybe you can add a UX tag.

**Comment by weinand** [comment]
@isidorn I've seen something like this too. For me it typically happens for the same debug type: first I run a launch config "test", then I switch to launch config "server" and press the green start button. Later, when waiting for the server to startup, I notice that the tests are running again...

I believe this is a timing issue (race condition). While a debug session is running, it should not be possible to switch the launch config. But sometimes it seems to be possible. However, when the debug sessions ends the new launch config is switched back to old launch config.

**Comment by roblourens** [comment]
You can still change launch configs while debugging, if you hide/show the debug sidebar.
![sep-28-2016 17-15-37](https://cloud.githubusercontent.com/assets/323878/18936782/3e33cf02-859f-11e6-95ae-8f770e952f13.gif)
