### ISSUE TITLE
Provide support for Forward / Back mouse buttons on macOS (new info)

### ISSUE THREAD

**Issue by m1h4** [microsoft/vscode#116507]
There is an [previously closed issue](https://github.com/microsoft/vscode/issues/8641) related to this feature, but it seems nobody in that discussion figured out that there is already built-in support for the [swipe navigation events](https://www.electronjs.org/docs/api/browser-window#event-swipe-macos) in Electron on macOS.

Those events should make it relatively trivial to add support for forward/back navigation for those users that use the Logitech Options / SensibleSideButtons software to have their mouse buttons emit these standard events that then work in all macOS standard apps (Finder, Safari, Xcode…).

Something like:
```
browserWindow.on('swipe', (event, direction) => {
    if (direction === 'left') navigation.back()
    if (direction === 'right') navigation.forward()
})
```

Would not only work for all mice that have software which generates these swipe events for the 4th and 5th mouse button, but also would actually work for people that have these legacy swipe events enabled for their trackpad.

**Comment by bpasero** [comment]
I am not willing to buy into more Electron API, see https://github.com/microsoft/vscode/issues/79078#issuecomment-543177718
