### ISSUE TITLE
Make it easier to jump from one Getting Started section to the next

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#116574]
In user testing some users closed and re-opened the Getting Started page when they clicked all the sections they found interesting. It should be easier and more engaging to continue on the page.

Some ideas for discussion:

- Named link in the last item to continue to next incomplete section.
-"Next steps" link in the last sections that jumps up to the index
- Named link to the next section below the items list. Could lead to users skipping too early when the title is too interesting?

cc @misoguy.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/108438106-66cb4d00-7203-11eb-9e44-5a104a21a8ae.png)

**Comment by JacksonKearl** [comment]
"next page" made sense to me, lmk if you feel strongly about "next steps"
