### ISSUE TITLE
Allow Learn More URLs for Getting Started items

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#116578]
In usertesting, users found some of the content too high level and wanted to dive deeper into some topics. As an example, debugging can't be explained in one paragraph and an image, but the sidebar does not give much guidance as well. We have existing docs pages for all of the items, as they are key concepts in VS Code.

Some ideas for how to solve that in the UI:

- Append a `Learn more.` after the description paragraph.
-  `(❓)` styled icon in the section header or footer.
- Optional longer text under the image with a link the docs.

cc @JacksonKearl @gregvanl

**Comment by rhit-namburs** [comment]
Hi! I would like to contribute to this.

**Comment by JacksonKearl** [comment]
@rhit-namburs this issue is a bit out of date, we actually do support inline links in descriptions now. I believe this can actually be closed out, cc @digitarald?

**Comment by digitarald** [comment]
Agreed. We ended up not having a specific UX for it and have used the inline links already for docs.

**Comment by rhit-namburs** [comment]
Oh Okay Thanks for letting me know
