### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by yunior123** [microsoft/vscode#116511]
if I hit the method => toString() instead of completing as toString() it completes as toString. That is just an example

**Comment by yunior123** [comment]
![Uploading code.png…]()

**Comment by yunior123** [comment]
![code](https://user-images.githubusercontent.com/47259501/107791199-a2f14000-6d21-11eb-8190-e7ea7b6ad609.png)

**Comment by yunior123** [comment]
@meganrogge

**Comment by yunior123** [comment]
This is happening since I last updated vsc .I am using a MAC =>OS Catalina

**Comment by jrieken** [comment]
I screen shot is not helpful. How about letting us know what language this happens in? what snippet you are using and I should be trying with (source, NOT screenshotted)

**Comment by yunior123** [comment]
> I screen shot is not helpful. How about letting us know what language this happens in? what snippet you are using and I should be trying with (source, NOT screenshotted)

Thank you for the help, by changing the user settings I was able to solved the problem
