### ISSUE TITLE
Feature Request: Snap Quick Access Debugger Controls to Different Sides/Add Workspace Option

### ISSUE THREAD

**Issue by cwadrupldijjit** [Microsoft/vscode#11652]
- VSCode Version: 1.4.0  <or>  1.5.0-insider
- OS Version: Windows 10 Home Insider Preview, build 14915.rs_prerelease.160826-1902

I work primarily in Node.JS world, and use the built-in debugger often.  In some of my projects, I've spun up a simple Node server to serve some assets while I work on the front-end, and then on occasion, after I've built out some functionality, I return to the server to deal with the XHRs that the front end sends.  It's useful to make changes, restart the server, and use the debugger to help reason with errors and the code.  When I press <kbd>F5</kbd>, the debugger quick access bar appears across the top with the debugging controls.

In previous versions, maybe a year to six months ago, there wasn't a handle to move it across the top, which means that it was stuck behind the file lookup box or any errors that showed up.  Now there is a handle, and it makes it so that you can move it out of the way of the command box.  But now the problem as I see it is that it's still hovering over tabs or options in the sidebar, and occasionally still covered by errors or notifications:  
![2016-09-07 3](https://cloud.githubusercontent.com/assets/13950768/18325704/afe2e896-74ff-11e6-8dab-e280f9e393eb.png)

Personally, I would prefer for it to appear at the bottom or side, where generally it's out of the way of the many UI elements that could conflict with it.  The ability to change which side it's snapped to could be invaluable.  For instance, this example:  
![vscode-debug-bar-right](https://cloud.githubusercontent.com/assets/13950768/18326852/f1d94998-7504-11e6-90df-85cc3226f435.png)

Or maybe even allow to stick it in the side toolbar:  
![vscode-debug-bar-left](https://cloud.githubusercontent.com/assets/13950768/18326878/1329ec24-7505-11e6-9ae9-be91ccabc860.png)

The idea is to keep it out of the way of all of the many UI elements that appear at the top of the screen so that there are no conflicts with it.  Adding the ability to snap the quick access toolbar to other sides would make it easier to deal with in that regard, and is only one proposed option for it.

**Comment by cwadrupldijjit** [comment]
I do also have other pictures that could be used as examples of where it could be.  Let me know if you're interested or if it's even viable.

**Comment by isidorn** [comment]
Dup of #9093
