### ISSUE TITLE
Exit Console With Error Code 1

### ISSUE THREAD

**Issue by DXkite** [Microsoft/vscode#11658]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Use Chinese Path In Dir
2. Open With VS Code
3. Open Console
4. Exit Console With Error Code 1

**Comment by ramya-rao-a** [comment]
@rebornix Can you try and repro this?

**Comment by rebornix** [comment]
Duplicate of #7727
