### ISSUE TITLE
Extension READMEs not correctly displaying HTML content

### ISSUE THREAD

**Issue by YashTotale** [microsoft/vscode#116591]
- VS Code Version: `1.53.2`
- OS Version: macOS Big Sur (Version `11.0.1`)

Steps to Reproduce:

1. Open an extension from the Extensions view.

For example, this is what the [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension README looks like:
<img width="1277" alt="Debugger for Chrome README" src="https://user-images.githubusercontent.com/30784592/107835473-7b649c80-6d4e-11eb-9cc0-93bd3870c8b7.png">

The README for this extension specifies `align="center"` for the image and the heading, however, that is not reflected when displaying the README in the Extensions panel.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Fixed by #116591

**Comment by YashTotale** [comment]
I think you mean fixed by #116885

**Comment by rzhao271** [comment]
\closedWith 6e08e45

**Comment by YashTotale** [comment]
The `align="center"` issue has been fixed, but there's another issue related to extension READMEs not correctly displaying HTML content. When an img tag specifies the `width` attribute, it seems like that attribute is ignored and the true width of the image is used.

Here's an example:
<img width="1193" alt="Screen Shot 2021-02-27 at 2 07 49 PM" src="https://user-images.githubusercontent.com/30784592/109401738-32434980-7905-11eb-95ea-5581f23340f2.png">

The `width` attribute of the image is 200, however the real width of the image is larger, and it seems that the real width is used rather than the `width` attribute. Any help on this issue would be great!

**Comment by mjbvz** [comment]
We'll consider allowing specific attributes on a case-by–case basis. If you want to see width and heigh also supported (and they already work in the marketplace) please open a new issue

**Comment by YashTotale** [comment]
New issue opened: #117939
