### ISSUE TITLE
Diff: support "compaction heuristic"

### ISSUE THREAD

**Issue by alexkrolick** [Microsoft/vscode#11657]
Git 2.9.0 introduced a "compaction heuristic" option that uses blank lines as a "strong hint" in computing diff block boundaries. It would be nice to get use a similar heuristic in the VS Code diff viewer. (If it is using the git diff util behind-the-scenes, this would already work).

https://github.com/blog/2188-git-2-9-has-been-released#beautiful-diffs
- VSCode Version: 1.5.0
- OS Version: Mac OS
- Git Version: 2.9.0+

**Comment by joaomoreno** [comment]
Code doesn't use git for diffing behind the scenes.

cc @alexandrudima

**Comment by alexandrudima** [comment]
I think I just implemented this in c8df698

**Comment by joaomoreno** [comment]
![damn son](https://m.popkey.co/c90e96/RwN4q.gif)
