### ISSUE TITLE
Help rendering issue!!!!

### ISSUE THREAD

**Issue by pb5050** [microsoft/vscode#116538]
![des](https://user-images.githubusercontent.com/58855947/107760381-3f4e1f00-6cef-11eb-86c4-54f948568199.png)

tbe purple box is whgat i get when i open vscode insiders the settings on the left i have toggles to false, false/ true, false , true true

and evry option lol i haver tried everything the only way i can get fix is to restart computer. i have re installed vscode already twice deleted all extensions idk how to fix  any ideas

**Comment by pb5050** [comment]
update i get a spinning wheel when i move mouse over the window like something's loading or whatever but nothing ever happens

**Comment by pb5050** [comment]
![opop](https://user-images.githubusercontent.com/58855947/107835847-80324c00-6d60-11eb-8099-90d43217ba09.png)
 anything  else you need>?

**Comment by deepak1556** [comment]
Do you see the issue when you start the app with `code --disable-features=CalculateNativeWinOcclusion`

**Comment by pb5050** [comment]
i am waiting before closing this to make sure it doesnt happen again but i updated electron and so far so good

**Comment by pb5050** [comment]
that photo was taken after updating electorn btw

**Comment by pb5050** [comment]
No issues in three days. 

I dont know if this is what fixed my issue but this is what i did For anyone else on ARM64


1. i went to the directory below and i erased all contents of every folder with  word "cache" in the title. IDK if thats good but it seems everything worked out.

          - >  "C:\Users\*Your Username*\AppData\Roaming\Code - Insiders"



2. I downloaded  arm64 unofficial build of Node. from the following link

                   - >  https://unofficial-builds.nodejs.org/


     3. installed npm and electron by following this guide (update electron completely)
                - >https://www.electronjs.org/docs/tutorial/windows-arm


I was having issues majorly  trying to install this and after alot of time wasted i figured out the solution 

make sure you set the following values in " Npm edit config "

arch=arm64
msvs_version=2019
platform=win32
prefix=C:\Users\*your username*\AppData\Roaming\npm
python=C:\Python39


*************     IF you do not set these values you will Fail when building electron    ******************

-Good luck ladies and gents

**Comment by deepak1556** [comment]
Please don't attempt to update the runtime this way, it will break the app. Were you able to test out https://github.com/microsoft/vscode/issues/116538#issuecomment-778537951 ?

**Comment by pb5050** [comment]
i had already did what i said and had no issues, but did i do somthing i wasnt supposed to? i dont have any issues  or have not had any issues?

**Comment by deepak1556** [comment]
Did you update electron for VSCode insiders application or did you mean your own electron app ?
