### ISSUE TITLE
An Idea to keep user logged in

### ISSUE THREAD

**Issue by MrDisturbance** [microsoft/vscode#116561]
Issue Type: <b>Feature Request</b>

I would love if VSC kept me logged into my github account so I don't have to constantly logging back in. I would also like it a lot more on the linux version if I didn't have to keep going to the page and re-downloading linux version everytime there's an update.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.4.95-12637-g53420cb1afc9

**Comment by joaomoreno** [comment]
> I would love if VSC kept me logged into my github account so I don't have to constantly logging back in.

Maybe @RMacfarlane can help here.

>  I would also like it a lot more on the linux version if I didn't have to keep going to the page and re-downloading linux version everytime there's an update.

On that: just install a debian package or a snap package, so your system can automatically update.

**Comment by RMacfarlane** [comment]
> I would love if VSC kept me logged into my github account so I don't have to constantly logging back in.

This should already happen - VSCode will try to write your credentials to gnome-keyring. When you sign in, is there any kind of error notification?

**Comment by MrDisturbance** [comment]
Last time I checked my VSCode there was something along the lines of that login error.

**Comment by RMacfarlane** [comment]
@MrDisturbance Can you share what exactly the error message says?
