### ISSUE TITLE
Keep pressing a key causes VSCode to hang up

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11654]
- VSCode Version: 1.5.0 Insider
- OS Version: OS X 10.11.6

Yesterday I found this bug: https://github.com/VSCodeVim/Vim/issues/729
If I keep pressing <kbd>j</kbd> (which is down in VSCodeVim), VSCodeVim hangs up. Originally I thought it's a VSCodeVim issue, but this morning I was able to repro that problem on a fresh install of Insider without VSCodeVim.

**When keeping pressing a certain key (a, j, k, whatever) for more than 2 seconds, VSCode stops taking any input.**

This issue happened: 

- Only on Mac. Tested in Linux/Win and everything was fine.
- With no extension installed
- With an empty `settings.json`
- With no exception shown in devtools window.

I tried deleting `$HOME/Library/Application\ Support/Code\ -\ Insiders/` and doing a reinstall. After that I haven't been able to repro this issue again.

It might has something todo with VSCodeVim's instruction to do 
```bash
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
```
to get j and k to repeat.

Another user was experiencing the same problem: https://github.com/VSCodeVim/Vim/issues/729#issuecomment-245371993

I'll continue looking for exact repro. Meanwhile, if anyone else (especially non-VSCodeVim user) is experiencing the same problem, please chime in.

**Comment by rebornix** [comment]
The reason we are running into this issue in Vim extension is we bind hooks to `type` event when this issue occurs, our handler for `type` event no longer gets called. 

/cc @alexandrudima

**Comment by octref** [comment]
Investigation so far, for people who want to repro the bug:

---

A clean install of Insider built against this commit https://github.com/Microsoft/vscode/commit/b2c874b253732778a246b94aa1eba93806c45361  which I was having this problem, wouldn't repro this bug.

(Download the Insider build [here](https://az764295.vo.msecnd.net/insider/b2c874b253732778a246b94aa1eba93806c45361/VSCode-darwin-insider.zip))

And by clean install I mean dragging the application to `/Applications` after running
```
rm -rf /Users/<username>/Library/Application Support/Code - Insiders
```

---

For Insider, the behavior of keep pressing a key is register 1 keystroke by default.
To let "holding down" produce keystrokes continuously, you need either

```
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
```

or

```
defaults write -g ApplePressAndHoldEnabled -bool false // Changes the setting globally
```

**When I had this problem, neither was set.** But now even if I delete both setting by
```
defaults delete com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled
defaults delete -g ApplePressAndHoldEnabled
```

I can't repro the bug any more.

When either of them or both is set, VSCode and VSCodeVim behaves as expected.

---

So, my guess is some setting generated by previous build of Insiders at `/Users/<username>/Library/Application Support/Code - Insiders` wouldn't work with the current build.

## Need Help With

If anyone is using Mac and downloaded Insiders more than a few days ago, can you try open a random file and keep pressing <kbd>j</kbd>, and see if this problem happens to you? Thanks.

**Comment by alexandrudima** [comment]
@octref What keyboard layout do you have configured?

**Comment by octref** [comment]
@alexandrudima 
US standard.

**Comment by alexandrudima** [comment]
@octref You mention VSCode "hangs up". Is it that it crashes, does not take any mouse input, was it possible to click on a viewlet like the search viewlet at the time and type in its native `<input>`. VSCodeVim probably doesn't get the `type` command because we're not generating it. 

It is possible that Chromium is stuck in some form of input composition. It is my understanding that usually long press & hold on the mac should pop up a list of alternative characters, like when I press `e` I get a list with `e` with different accents.

So I am guessing you reproduced the issue originally not with the default OS settings. We have tried here unsuccessfully to reproduce setting the `ApplePressAndHoldEnabled` keys and for us setting this key to true or to false has no effect. The `e` popup always shows. Perhaps a OS restart is needed for that setting to be applied?

**Comment by alexandrudima** [comment]
From looking at the code in this area - https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/controller/textAreaHandler.ts#L109

This can happen if `this.textareaIsShownAtCursor` is true when receiving the `input` event. That variable is true when Chromium sends our way a `compositionstart` and we set it to false when we receive a `compositionend`. Per w3c spec https://www.w3.org/TR/DOM-Level-3-Events/#events-compositionevents there is no case where a `compositionstart` is left dangling and not at some point followed by `compositionend`.

I believe this is a bug in Chromium where they enter some state where they send a `compositionstart` but never send a `compositionend`. I am weary of making any changes until we can fully reproduce the problem and identify the root cause.

**Comment by octref** [comment]
@alexandrudima 

It didn't crash. No error in devtools window. I was able to click around, including viewlet icons and also editors (setting the location of the cursors). Didn't try inputting text in search viewlet.
If you set the setting, `e` doesn't show any more for me. Let me do a quick gif for you.

**Comment by alexandrudima** [comment]
@octref Given my hunch regarding `compositionstart` and `compositionend`, do you have installed any other keyboard layouts on your mac -- is it possible that you were not in US standard when this happened?

**Comment by octref** [comment]
![hang](https://cloud.githubusercontent.com/assets/4033249/18340659/fbe8c4ee-755a-11e6-9e04-a03a29d24efd.gif)

**Comment by octref** [comment]
@alexandrudima 
It has been US since I setup this work computer last week.

![image](https://cloud.githubusercontent.com/assets/4033249/18340692/36343804-755b-11e6-8aaa-c860bd01241a.png)

**Comment by alexandrudima** [comment]
Thank you @octref I was able to get the key to behave at @jrieken 's mac. So we could switch between e popping up the variants and the e repeating the key e. But we cannot reproduce the "no input" you have experienced.

**Comment by octref** [comment]
This comment https://github.com/VSCodeVim/Vim/issues/729#issuecomment-245300801 and my experience suggest it's not extension's fault. Can you try this build https://az764295.vo.msecnd.net/insider/b2c874b253732778a246b94aa1eba93806c45361/VSCode-darwin-insider.zip with both the key written & deleted?

**Comment by octref** [comment]
@alexandrudima 
I also requested more info from the other user experiencing the same problem, but he hasn't got back to me.

**Comment by octref** [comment]
Could that have anything todo with me using Ctrl-c for exiting insert mode in Vim? (Some people use ESC). Let me do some tests...

**Comment by alexandrudima** [comment]
@octref I have the theory that Chromium gives unbalanced `compositionstart` and `compositionend`, but before I begin to consider any workarounds around their bug, I need to have a reproducible state on a machine where we can begin to reason about when this bugs occurs within Chromium and be able to reason when we apply a workaround and what the workaround should be. As this impacts all IME building cases I am not willing to make any change in this code unless we can reproduce and understand the Chromium issue behind it.

**Comment by octref** [comment]
@alexandrudima I agree. I'll keep looking for repros.

@jayteesanchez Hello! If you are still able to reproduce the issue you were experiencing, do you mind chiming in and give us some valuable feedback?

**Comment by octref** [comment]
@alexandrudima 
Might be related:
https://github.com/VSCodeVim/Vim/blob/9efc43a5e9213ecb61b2d6ff0091f200cffa6309/extension.ts#L173-L201

**Comment by octref** [comment]
OK, it seems to be an extremely rare case since none of us are able to repro. I'll close it for now and keep an eye on VSCodeVim issues.

**Comment by rebornix** [comment]
@alexandrudima the only thing we missed while trouble shooting when the bug occurred is adding breakpoints to `compositionStart` handler. We added one bkp for `type` and failed to receive any key strokes. Apparently next time we run into this issue again, we can verify :)

**Comment by kkito** [comment]
I met the same situation.
if i start vscode from term like `cd project; code .` , this will happened
but if i start from spotlight (cmd+space) , everything is fine
i guess some env from my zsh make this happen
hope it can do some help

**Comment by kevinvavelin** [comment]
This issue is still present in stable release :/ Same behaviour
