### ISSUE TITLE
"debug.log" files in project

### ISSUE THREAD

**Issue by gabirum** [microsoft/vscode#116579]
Issue Type: <b>Bug</b>

All files that I open in editor creates a file with name "debug.log" in folder.

The content of these files are usually:
```[0212/142518.630:ERROR:registration_protocol_win.cc(102)] CreateFile: O sistema não pode encontrar o arquivo especificado. (0x2)```

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.74GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Debian/home/gabriel/projects/nodetest --remote=wsl+Debian --crash-reporter-id 9dddfdea-cbfb-4c4e-b00a-d13851101a34|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2903)|
|Memory (System)|6.13GB (5.13GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.11.1
vscode-mjml|att|1.6.0
vscode-tailwindcss|bra|0.5.9
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.9.2
vscode-lombok|Gab|1.0.1
vscode-styled-components|jpo|1.5.0
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.0
debugger-for-edge|msj|1.0.15
vetur|oct|0.32.0
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.24.0
vscode-manifest-yaml|Piv|1.24.0
vscode-spring-boot|Piv|1.24.0
material-icon-theme|PKi|4.5.0
java|red|0.75.0
vscode-xml|red|0.15.0
vscode-gradle|ric|3.5.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.15
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by deepak1556** [comment]
Please switch to `1.53.2`

/duplicate https://github.com/microsoft/vscode/issues/115874
