### ISSUE TITLE
Access to the libraries files outside of project folder by Ctrl+P

### ISSUE THREAD

**Issue by amigo421** [microsoft/vscode#116562]
The scenario of the feature went from my usage : C++ coding.
it requires to have an ability to search header files  (C++ includes) from a various libraries , linked to the project.
e.g.
1. I'm using boost lib which is located somewhere outside of the project
2. I need to open some header file and don't remember exact name . Ctrl+P solves this by partial filename match , but fr the files inside project only

C++ extension developers say that such support firstly should be implemented on VSCode level before will be included into language server.

P.S. apologizes if such already  exists, didn't find this.

**Comment by JacksonKearl** [comment]
Are you proposing that Ctrl+P searches *every file* on your computer? I don't think thats feasible. Could you perhaps instead open the directory where header files might be located as part of a [multi root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces)?

**Comment by amigo421** [comment]
of course no all files on the computer, 
initially I had this [discussion](https://github.com/microsoft/vscode-cpptools/issues/6935) with your colleagues who works on C++ extension to add an ability to work with a linked to project libraries like it does visual studio , and they [told](https://github.com/microsoft/vscode-cpptools/issues/6935#issuecomment-777058334) me that can't due of vscode limitation. please look at how they describe the problem, probably it will look more clear ...

also let me try recommended solution with multiroot workspace

**Comment by amigo421** [comment]
@JacksonKearl do you still need more info from my side? (I'm about the tag)

**Comment by JacksonKearl** [comment]
cc @roblourens

**Comment by roblourens** [comment]
I know this came up before and had a discussion, but I can't find the issue. Found a couple that I'd closed out of scope. I'm find leaving this open though.

https://github.com/microsoft/vscode/issues/109472
https://github.com/microsoft/vscode/issues/92066

**Comment by roblourens** [comment]
Also consider a multiroot workspace

**Comment by amigo421** [comment]
multiroot works fine for me, thank you for a tip, just the problem is a need to do this manually, would be preferable that c++ extension does this by itself for items in includePath setting, but not a big deal to add this manually.

**Comment by JacksonKearl** [comment]
You could make a feature request against the C++ extension (or just make your own extension) to add a command to create a new .code-workspace file from the includes of a project.

**Comment by amigo421** [comment]
yes, so multiroot solution solves my problem - manually or somehow outside of this project , so if nobody else wants to implement this we can close this
