### ISSUE TITLE
extensionHost keeps crashing the whole  day

### ISSUE THREAD

**Issue by FloMaetschke** [microsoft/vscode#116549]
Issue Type: <b>Bug</b>

Work in multiple repositorys.
The host crashes with this error:

Extension Host
localProcessExtensionHost.ts:266 <--- Last few GCs --->
[10780:000002C100000000]  6249104 ms: Mark-sweep (reduce) 3683.0 (3756.7) -> 3683.0 (3753.2) MB, 479.0 / 0.0 ms  (average mu = 0.339, current mu = 0.009) last resort GC in old space requested
[10780:000002C100000000]  6249581 ms: Mark-sweep (reduce) 3683.0 (3753.2) -> 3682.8 (3753.2) MB, 477.3 / 0.0 ms  (average mu = 0.204, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF786F0A256 node::Buffer::New+47254
 2: 00007FF786F0A455 node::Buffer::New+47765
 3: 00007FF78578F6C3 v8::V8::GetVersion+803
 4: 00007FF78578F661 v8::V8::GetVersion+705
 5: 00007FF785932533 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+195363
 6: 00007FF78593AC79 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+229993
 7: 00007FF78590AD4A cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+33594
 8: 00007FF785905E69 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+13401
 9: 00007FF785B5E627 v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+96551
10: 00007FF78579CE4B v8::JSON::Parse+1083
11: 00007FF785B3C62F v8::Platform::SystemClockTimeMillis+1287151
12: 00007FF785853307 v8::CFunction::CFunction+574951
13: 00007FF785854704 v8::CFunction::CFunction+580068
14: 00007FF78585CF6B v8::CFunction::CFunction+614987
15: 00007FF785798A6D v8::ScriptCompiler::CompileUnboundInternal+685
16: 00007FF785798F7B v8::ScriptCompiler::CompileUnboundScript+59
17: 00007FF787A12BA1 uv_dlerror+113729
18: 00007FF7857FA94E v8::CFunction::CFunction+212014
19: 00007FF7857F99F9 v8::CFunction::CFunction+208089
20: 00007FF7857F9462 v8::CFunction::CFunction+206658
21: 00007FF7857F9087 v8::CFunction::CFunction+205671
22: 00007FF7861F7D7C v8_inspector::V8StackTraceId::ToString+3495020
23: 00007FF786186245 v8_inspector::V8StackTraceId::ToString+3029301
24: 00007FF7862888BF v8_inspector::V8StackTraceId::ToString+4087727
25: 00007FF786189478 v8_inspector::V8StackTraceId::ToString+3042152
26: 00007FF78618613A v8_inspector::V8StackTraceId::ToString+3029034
27: 00007FF7862888BF v8_inspector::V8StackTraceId::ToString+4087727
28: 00007FF786189478 v8_inspector::V8StackTraceId::ToString+3042152
29: 00007FF786189478 v8_inspector::V8StackTraceId::ToString+3042152
30: 00007FF786189478 v8_inspector::V8StackTraceId::ToString+3042152
31: 000002C1000FC2A1 

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (35.52GB free)|
|Process Argv|--file-uri file:///c%3A/Projekte/C2C/my-workspace.code-workspace --crash-reporter-id 47c0698e-5c84-458b-90d4-f9d0d2f4acfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

Nodejs executable says:
$ node -p "process.arch"
x64
$ node -v
v15.3.0

**Comment by gjsjohnmurray** [comment]
Please update to 1.53.2 which released yesterday, then let us know if the problem still occurs.

**Comment by FloMaetschke** [comment]
updated, i will try it out for a while and reply when it happens again! Please do not close now.

**Comment by deepak1556** [comment]
Crash due to out-of-memory, can you find which extension is causing this using https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect

**Comment by FloMaetschke** [comment]
The crash is still happening with the new version of vscode:

```
<--- Last few GCs --->
[18748:0000021500000000] 17421715 ms: Mark-sweep (reduce) 3717.0 (3809.4) -> 3716.8 (3806.4) MB, 395.6 / 0.0 ms  (average mu = 0.973, current mu = 0.909) last resort GC in old space requested
[18748:0000021500000000] 17422211 ms: Mark-sweep (reduce) 3716.8 (3806.4) -> 3716.7 (3805.9) MB, 496.3 / 0.0 ms  (average mu = 0.946, current mu = 0.000) last resort GC in old space requested
<--- JS stacktrace --->
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF778F9A256 node::Buffer::New+47254
 2: 00007FF778F9A455 node::Buffer::New+47765
 3: 00007FF77781F6C3 v8::V8::GetVersion+803
 4: 00007FF77781F661 v8::V8::GetVersion+705
 5: 00007FF7779C2533 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+195363
 6: 00007FF7779CAC79 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+229993
 7: 00007FF77799AD4A cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+33594
 8: 00007FF777995E69 cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex+13401
 9: 00007FF777BEE627 v8::internal::OSROptimizedCodeCache::GetBailoutIdFromEntry+96551
10: 00007FF77782CE4B v8::JSON::Parse+1083
11: 00007FF777BCC62F v8::Platform::SystemClockTimeMillis+1287151
12: 00007FF7778E3307 v8::CFunction::CFunction+574951
13: 00007FF7778E4704 v8::CFunction::CFunction+580068
14: 00007FF7778ECF6B v8::CFunction::CFunction+614987
15: 00007FF777828A6D v8::ScriptCompiler::CompileUnboundInternal+685
16: 00007FF777828F7B v8::ScriptCompiler::CompileUnboundScript+59
17: 00007FF779AA2BA1 uv_dlerror+113729
18: 00007FF77788A94E v8::CFunction::CFunction+212014
19: 00007FF7778899F9 v8::CFunction::CFunction+208089
20: 00007FF777889462 v8::CFunction::CFunction+206658
21: 00007FF777889087 v8::CFunction::CFunction+205671
22: 00007FF778287D7C v8_inspector::V8StackTraceId::ToString+3495020
23: 00007FF778216245 v8_inspector::V8StackTraceId::ToString+3029301
24: 00007FF7783188BF v8_inspector::V8StackTraceId::ToString+4087727
25: 00007FF778219478 v8_inspector::V8StackTraceId::ToString+3042152
26: 00007FF77821613A v8_inspector::V8StackTraceId::ToString+3029034
27: 00007FF7783188BF v8_inspector::V8StackTraceId::ToString+4087727
28: 00007FF778219478 v8_inspector::V8StackTraceId::ToString+3042152
29: 00007FF778219478 v8_inspector::V8StackTraceId::ToString+3042152
30: 00007FF778219478 v8_inspector::V8StackTraceId::ToString+3042152
31: 0000021500405561 

```



VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (38.60GB free)|
|Process Argv|--crash-reporter-id 47c0698e-5c84-458b-90d4-f9d0d2f4acfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>




The only installed extension is: esbenp.prettier-vscode 5.9.2

**Comment by FloMaetschke** [comment]
I am working on a project with 17 git repos (GHE) opened in my workspace. Each for one npm package (micro-architecture). Mostly TypeScript and json, standard stuff.

**Comment by deepak1556** [comment]
Does it crash when you disable the `esbenp.prettier-vscode` extension ? I would like to understand what is causing the host crash before attempting to increase the heap size.

**Comment by FloMaetschke** [comment]
Ok, i have used vscode without any addon the last 2 days without any crash, so i would guess it has to do with the prettier extension.
But i really can't believe that because i guess it has a wide range of users.

**Comment by FloMaetschke** [comment]
No crash without plugins, adding prettier, it crashes again.

**Comment by FloMaetschke** [comment]
I assume prettier requires too much memory when multiple projects with it are in the workspace.

**Comment by deepak1556** [comment]
Please open an issue with the extension `prettier-vscode` to further debug the memory usage by the extension.

To help the extension debug, follow these steps to get a memory profile

* Launch code with `--inspect-extensions=9229`
* In chrome browser visit `chrome://inspect` or in edge browser visit `edge://inspect`
* You should see an entry under `Remote Target` that starts with `/Applications/Visual Studio Code/....`
* If you don't see the above entry, then
  * Under `Devices`, click `open dedicated devtools for node`
  * Under `Connection` tab, add `localhost:9229`
  * You should now see the target
* Click inspect
* Go to `memory` tab and start `Allocation Instrumentation on Timeline`
* Attach the profile to your issue.
