### ISSUE TITLE
Context menus win registry entries not removed if entries already exist from alternate install 

### ISSUE THREAD

**Issue by josh-hemphill** [microsoft/vscode#116563]
- VS Code Version: 1.53.2
- OS Version: Win10 Pro, 1909, build 18363.1316

Steps to Reproduce:

1. Install both system and user installer with context menu actions enabled
2. Uninstall either, or both.
3. Check context menus and registry for unremoved entries

Does this issue occur when all extensions are disabled?: Yes

After accidentally installing both the user and system installers with context menu items enabled, neither uninstaller is able to remove any of the context menu items, leaving the corresponding registry entries in a hard-to-recover-from state; I have to manually search for every instance and remove them.

**Comment by joaomoreno** [comment]
You really can only reproduce this if you install both?

**Comment by josh-hemphill** [comment]
I haven't checked to see if the registry changes persist after a normal uninstall. I should probably have mentioned the breaking issue with this is that when the system installer is run while the user install is active, the context menu items still reference the user install location, and then if you uninstall the user installation, those context menu items still persist and point to a non-existant install location.

**Comment by joaomoreno** [comment]
The thing is: the system and user context menu items all live in separate places in the registry. So I wonder if, when you've managed to install both, shouldn't those items just appear as duplicates in the context menu?
