### ISSUE TITLE
I cannot execute powershell commands from vscode using F8

### ISSUE THREAD

**Issue by gmvs** [Microsoft/vscode#11650]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Write powershell command like "get-date"
2. Press F8.

**Comment by ramya-rao-a** [comment]
@gmvs Are you using the extension 
https://marketplace.visualstudio.com/items?itemName=ms-vscode.PowerShell and expecting to run selected code by pressing F8?

**Comment by ramya-rao-a** [comment]
@gmvs  any updates?

**Comment by gmvs** [comment]
Hi Ramya-rao-a , thanks for your help. I restarted the application and it started to work. Seems to be powershell needed to be restarted after I installed the extension. Thanks!

**Comment by ramya-rao-a** [comment]
@gmvs No Problem
