### ISSUE TITLE
serial port

### ISSUE THREAD

**Issue by khaliqd** [microsoft/vscode#116582]
We have written the needed data into your clipboard because it was too la
Issue Type: <b>Bug</b>

Can not select serial port to connect MXCHIP AZ3166

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21301

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.96GB free)|
|Process Argv|--crash-reporter-id 3ee78208-1f8b-45bf-8ad7-79b0ba91a503|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.9
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.6
cpptools|ms-|1.2.0
azure-iot-edge|vsc|1.23.0
azure-iot-toolkit|vsc|2.16.4
azure-iot-tools|vsc|0.3.0
vscode-arduino|vsc|0.3.4
vscode-iot-device-cube|vsc|0.3.0
vscode-iot-workbench|vsc|0.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

rge to send. Please paste.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please specify how it's related to VS Code editor itself?
Looks like you have problem with one of your extensions that should provide this functionality
