### ISSUE TITLE
Sort workspace results over out of workspace results

### ISSUE THREAD

**Issue by MitchellBouwman** [microsoft/vscode#116551]
**Steps to Reproduce:**

1. Open project and start searching a file in your project.
2. If this file is also in a other project you have a big chance it will be the first result.

I'm having this regularly where I'm editing files that do not belong to the project, yes, off course I can look better but it feels strange opening files in the same project are not the prioritized first.

![vscode-search-bug](https://user-images.githubusercontent.com/11721953/107775789-0f2f6c00-6d41-11eb-9ee2-072367fba2eb.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Related: https://github.com/microsoft/vscode/issues/38128, https://github.com/microsoft/vscode/issues/19762
