### ISSUE TITLE
VS Code fails to update due to MoveFile operation error

### ISSUE THREAD

**Issue by gingters** [microsoft/vscode#116523]
Issue Type: <b>Bug</b>

Since yesterday my VS Code Insiders build shows the following error message regularly during normal use.

I already tried to completely uninstall and re-install VS Code Insiders yesterday, but today the error came up again.

![image](https://user-images.githubusercontent.com/755148/107742539-80eec200-6d0f-11eb-92c6-9b6e0074559f.png)

VS Code version: Code - Insiders 1.54.0-insider (93f705ab40b37aade9d3b5165ed09114a8c87ac9, 2021-02-11T05:44:31.644Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.88GB free)|
|Process Argv|--crash-reporter-id 3476391b-e49a-45b1-aa69-f7f602ce9559|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.9.2
mermaid-markdown-syntax-highlighting|bpr|1.2.0
FreeMarker|dco|0.0.9
terraform|has|2.6.0
coremetrics|jas|0.0.1
plantuml|jeb|2.14.3
vscode-peacock|joh|3.9.1
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
vscode-kubernetes-tools|ms-|1.2.4
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.159.0
remote-ssh|ms-|0.63.0
remote-ssh-edit|ms-|0.63.0
remote-wsl|ms-|0.54.0
azure-account|ms-|0.9.6
powershell-preview|ms-|2020.9.0
vsliveshare|ms-|1.0.3629
azurerm-vscode-tools|msa|0.14.1
vscode-yaml|red|0.15.0
helm-intellisense|Tim|0.9.1
vscode-mermaid-editor|tom|0.9.2
vscode-mermaid-preview|vst|1.5.7
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes516:30244333
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963

```

</details>

**Comment by ragart** [comment]
Same issue in 1.53.2.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by gingters** [comment]
Additional Info: The error message keeps popping up every hour.

**Comment by joaomoreno** [comment]
@mjbvz The file in question is:

```
resources/app/extensions/typescript-language-features/node_modules/typescript-vscode-sh-plugin/.github/workflows/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs
```

This probably shouldn't be in our bits.

**Comment by Therkelsen** [comment]
Keeps happening for me as well
![image](https://user-images.githubusercontent.com/37107686/107829898-f350b800-6d8a-11eb-90fa-7a359719e7fc.png)

**Comment by dotnetengineers** [comment]
Same Issue
![image](https://user-images.githubusercontent.com/12179867/107835573-f6867c80-6d67-11eb-9b08-ba41a88cc4a8.png)

**Comment by chloechantelle** [comment]
Same error as above.
Can we get an update on when this will be fixed?
It's extremely annoying and distracting.

**Comment by jiayisheji** [comment]
Same error as above.
Can we get an update on when this will be fixed?

**Comment by jiayisheji** [comment]
I uninstall the local version, rewrite the download of the latest version for installation, can be normal installation

**Comment by Raydir** [comment]
Same here and 10 other persons in our company...

**Comment by joaomoreno** [comment]
Fix has been pushed to `main`. Unfortunately you very likely have to reinstall VS Code Insiders. But worry not: none of your settings or extensions will be lost!

**Comment by frahugo** [comment]
@joaomoreno Same problem here. Can I just wait for the next official update or I need to either uninstall/install or install Insiders version? thx

**Comment by connor4312** [comment]
@joaomoreno are there any verification steps to take here?

**Comment by joaomoreno** [comment]
> @mjbvz The file in question is:
> 
> ```
> resources/app/extensions/typescript-language-features/node_modules/typescript-vscode-sh-plugin/.github/workflows/obj/Debug/netcoreapp3.1/.NETCoreApp,Version=v3.1.AssemblyAttributes.cs
> ```
> 
> This probably shouldn't be in our bits.

☝️ This file should not be in our builds.

**Comment by mjbvz** [comment]
@aeschli Can you please take a look? It looks like this is coming from the `typescript-vscode-sh-plugin` package

**Comment by joaomoreno** [comment]
@mjbvz This issue is fixed.... we just need it to be verified.

Verification: Confirm that the file above isn't in our builds, eg Windows.
