### ISSUE TITLE
Larger windows make them heavier

### ISSUE THREAD

**Issue by hsk** [microsoft/vscode#116537]
Issue Type: <b>Performance Issue</b>

4GMEM on Ubuntu 19.4,
Intel® Core ™ 2 Duo CPU T7100 @ 1.80GHz × 2
Intel® 965GM (CL)
It was a 64-bit OS.
From this version, VS Code will be heavier if the size of the screen is halved vertically and horizontally.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.15.0-136-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T7100  @ 1.80GHz (2 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|3.84GB (0.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6fdcada8-22bb-474d-9297-3a7e9344ec14|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   157	  9422	code main
    0	    39	  9426	   zygote
    1	    83	  9453	     gpu-process
    0	    39	  9427	   zygote
    3	    87	 10094	     window (問題のレポーター)
    0	    55	  9472	   utility
    0	   248	  9484	   window (sp.c - xevious - Visual Studio Code)
    0	   173	  9857	     extensionHost
    0	    83	  9913	       /home/sakurai/.vscode/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools
    0	     8	  9946	         /home/sakurai/.vscode/extensions/ms-vscode.cpptools-1.2.0/bin/cpptools-srv 9913 {115BA7D9-96EF-4CD1-83AF-2E3DD736ED1A}
    0	    20	  9965	       PHP Language Server
    0	     0	  9967	         sh -c '/usr/bin/php7.2' '-n' '-c' '/tmp/oqWfgG' '/home/sakurai/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php' '--tcp=127.0.0.1:37601' '--memory-limit=4095M'
    0	   185	  9968	           PHP Language Server
    0	    98	  9981	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9857
    0	    87	  9872	     watcherService
    0	    63	  9890	     searchService
    0	   118	  9836	   shared-process
    0	     0	 10108	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 10109	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (sp.c - xevious - Visual Studio Code)
|    Folder (xevious): 2060 files
|      File types: png(2000) mkv(13) o(5) gif(4) c(4) bin(2) envrc(1) json(1)
|                  out(1) php(1)
|      Conf files: makefile(2) settings.json(1);
```

</details>
<details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
asm-php|hsk|0.0.1
amiga-debug|Bar|1.0.0
markdown-mermaid|bie|1.9.2
markdown-preview-github-styles|bie|0.1.6
mermaid-markdown-syntax-highlighting|bpr|1.2.0
bracket-pair-colorizer|Coe|1.0.61
rgbds-z80|don|2.6.0
xml|Dot|2.5.1
scala-lsp|dra|0.2.3
tslint|eg2|1.0.44
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
javac-linter|fau|1.3.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
terminal|for|0.0.10
reasonml|fre|1.0.38
sml|fre|0.0.18
graphviz-markdown-preview|gee|0.0.8
vscode-javac|geo|0.2.37
mdmath|goe|2.5.1
beautify|Hoo|1.5.0
haskell-linter|hoo|0.0.6
vscode-edit-csv|jan|0.5.4
nbpreviewer|jit|1.2.2
ott|Joe|0.0.6
language-haskell|jus|3.3.0
MagicPython|mag|1.1.0
vscode-language-pack-ja|MS-|1.53.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
debugger-for-chrome|msj|4.12.12
tsimporter|pmn|2.0.1
webgl-glsl-editor|rac|1.1.1
prolog|reb|0.0.4
java|red|0.75.0
vscode-yaml|red|0.15.0
llvm|RRe|0.1.1
RustyCode|sav|0.19.1
preview-vscode|sea|2.2.5
simple-asm|hsk|0.0.1
vscode-scheme|sjh|0.4.0
open-in-browser|tec|2.0.0
python|tht|0.2.3
pdf|tom|1.1.0
vscode-mermaid-preview|vst|1.5.7
material-theme|zhu|3.9.13

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Not clear what `heavier` means. Screenshot will be helpful.

Also you can use `window.zoomLevel`/`editor.fontSize` etc. to adapt to screen size/resolution.

**Comment by deepak1556** [comment]
If you are referring to the memory usage, can you provide the output of `code --status` when that happens. Does launching with `code --disable-gpu` help ?
