### ISSUE TITLE
Unable to open '....ipynb': Cannot read property '...' of undefined.

### ISSUE THREAD

**Issue by jjcfrank** [microsoft/vscode#116539]
- VS Code Version: VS Code Insiders Version: 1.54.0-insider
- OS Version: macOS 11.2
- Extra info: Apple Silicon Chip M1

Steps to Reproduce:

1. Download VS Code Insiders
2. Install Python & jupyter notebook extension
3. Pip3 install ipykernel and ipython
4. Open VS Code Insiders and select a folder
5. Open a jupyter notebook within the selected folder
6. Any .ipynb opened will cause VS Code Insiders to say: Unable to open '....ipynb': Cannot read property '...' of undefined.
6.1 The second set of inverted commas has been 'Rich' or 'Error'

Does this issue occur when all extensions are disabled?: Yes

It seems there is an issue with the official Jupyter extension by Microsoft (ms.toolsai.jupyter)

**Comment by gjsjohnmurray** [comment]
/causedByExtension

You can use the "Report Issue" dialog from the Help menu to raise an issue on the extension.
