### ISSUE TITLE
Not able to delete a new file

### ISSUE THREAD

**Issue by AkshayHarti** [microsoft/vscode#116508]
Issue Type: <b>Bug</b>

1. create a new file (Ctrl + N)
2. click the X mark beside the Untitled name
3. click "Don't save" on the dialog
4. the file disappears and appears again

This happens even if I reload the window

Video sample:

https://user-images.githubusercontent.com/21330288/107715243-edbf8780-6d22-11eb-9e84-feb0f8042db1.mp4

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz (12 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.24GB (19.36GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b9810d78-0af0-4474-be56-6bed3923ec23|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
jest-snippets|and|1.8.0
atlascode|atl|2.8.5
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
elm-ls-vscode|elm|2.0.3
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
codetogether|gen|3.2.0
vscode-pull-request-github|Git|0.23.1
Ionide-fsharp|Ion|5.3.2
vscode-styled-components|jpo|1.5.0
git-graph|mhu|1.28.0
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
javascript-test-runner|osh|1.2.4
git-file-history|pom|1.0.1
vscode-yaml|red|0.15.0
vscode-todo-highlight|way|1.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
@AkshayHarti does the problem also happen after you run the command to reload with all extensions disabled? If not, please use the Extension Bisect command to investigate which extension is causing it. Then report the problem to the extension author and close this one.

**Comment by AkshayHarti** [comment]
@gjsjohnmurray , I found out that the problem occurred due to the `codetogether` extension. I disabled it and everything worked fine.

Closing the issue.

**Comment by brianvfernandes** [comment]
@AkshayHarti just wanted to let you know that we've been able to replicate [this issue](https://github.com/Genuitec/CodeTogether/issues/268) and will fix it in our next CodeTogether release. Thank you for the report!
