### ISSUE TITLE
LOOSING MOUSE CURSOR CLICKED POSITION ON SEARCH - MULTI CURSOR

### ISSUE THREAD

**Issue by rinshankolayil** [microsoft/vscode#116645]
I search string in VS code which consist of more than 3576 occurrence.

1. I search first string (Search occurrence 1) on line 635188 and i mouse click on the position.
2. Then i find last occurrence of string (Search occurrence 3576)  by using the up arrow mark in the search tool (CTR + F) which is at line number 6270275.
3. Then click mouse cursor at line number 6270275.
4. Then i am loosing the first mouse clicked position at 635188. Because i need to delete the lines from line number 635188 to 6270275.

![2](https://user-images.githubusercontent.com/40558052/107878801-0926c000-6ee6-11eb-8383-5b19dfae665d.png)

i.e. I wish to have **_mouse cursor positions_** and **_selection_** between the lines from 635188 to 6270275 by search tool with a string. Because it is difficult to scroll from the line 635188 to 6270275.

**Comment by roblourens** [comment]
> Then i am loosing the first mouse clicked position

Sorry... I don't really understand the problem, can you explain a little more? Maybe a screen recording/gif would help?

**Comment by rinshankolayil** [comment]
This is an example video which consists of lines 14. The real time case
might be millions of lines. But this might happen in rare cases only.
If I didn't choose search tool then I can select lines in between criteria
by pressing Shift+mouse click

**Comment by rinshankolayil** [comment]
This is an example video which consists of lines 14. The real time case
might be millions of lines. But this might happen in rare cases only.
If I didn't choose search tool then I can select lines in between criteria
by pressing Shift+mouse click

**Comment by rinshankolayil** [comment]
This is an example video which consists of lines 14. The real time case
might be millions of lines. But this might happen in rare cases only.
If I didn't choose search tool then I can select lines in between criteria
by pressing Shift+mouse click

**Comment by rinshankolayil** [comment]
This is an example video which consists of lines 14. The real time case might be millions of lines. But this might happen in rare cases only.

https://user-images.githubusercontent.com/40558052/108036355-2a53f180-7049-11eb-96a8-c571ff23d3e4.mp4

What i wish to do

https://user-images.githubusercontent.com/40558052/108036373-32ac2c80-7049-11eb-83bb-85de06ea3773.mp4

**Comment by rinshankolayil** [comment]
Currenly i can delete the lines by searching the line number (CTRL + G) but still not with search option. But it is ok for me.


https://user-images.githubusercontent.com/40558052/117539201-48ab0700-b012-11eb-91a1-18f44c856a34.mp4

**Comment by rinshankolayil** [comment]
Sorry, This is not yet solved. Please refer my previous videos again.

- Large text with only one line
- Millions of lines of codes - Please refer first video
- 
Working scenario
https://user-images.githubusercontent.com/40558052/117549672-6729f600-b044-11eb-9d0a-ee44733ee775.mp4

Issue

https://user-images.githubusercontent.com/40558052/117549685-790b9900-b044-11eb-919b-68b8f58e8606.mp4
