### ISSUE TITLE
HTML folding does not work inside a <script> tag

### ISSUE THREAD

**Issue by TotallyInformation** [microsoft/vscode#116652]
- VS Code Version: 1.53.2
- OS Version: Windows 10 (latest)

Steps to Reproduce:

1. Create a .html file
2. Set VScode folding strategy to "auto"
3. Write valid html with a `<script type="text/html">` section (which is valid HTML)
4. Include valid, nested html inside the script section

Does this issue occur when all extensions are disabled?: Yes

Note that region folding is also disabled in this case.

Example screenshots:

![image](https://user-images.githubusercontent.com/1591850/107881750-91ed2e00-6edd-11eb-848f-653992d3522d.png)

---

A followup question would be - why is the folding strategy only auto or indent? Why can't it be both? Which would fix this issue and also the annoying JSDoc folding issue in JavaScript files.

**Comment by aeschli** [comment]
We have folding in <script> but only when the type is JavaScript.

Support for `text/html` is https://github.com/microsoft/vscode/issues/77977

**Comment by TotallyInformation** [comment]
Thanks for the response, looks like there is a PR already in place so I assume that will flow through to the live version in time. If it still isn't working in a few months, I'll raise a new issue.
