### ISSUE TITLE
GUI not working with Xbox Game Bar overlay

### ISSUE THREAD

**Issue by rsoucek** [microsoft/vscode#116651]
Issue Type: <b>Bug</b>

When running Xbox Game Bar overlay (performance bar or recording) VSCode GUI is not  working. Opens just a blank window or wouldn't refresh.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
powershell|ms-|2020.6.0
subtitles-editor|pep|1.1.3

</details>

**Comment by zmajeed** [comment]
I also noticed this

**Comment by deepak1556** [comment]
Do you see the issue when you start with `code --disable-features=CalculateNativeWinOcclusion` ?

**Comment by zmajeed** [comment]
No - issue does not occur with `code --disable-features=CalculateNativeWinOcclusion`

**Comment by deepak1556** [comment]
Thanks for checking, merging to https://github.com/microsoft/vscode/issues/114459
