### ISSUE TITLE
stuck when i run the code

### ISSUE THREAD

**Issue by HARSH419** [microsoft/vscode#116623]
[Issue]([url](url)) Type: <b>Bug</b>

stuck when i run the code, it show that message in terminal that intellisensemode change from "window-gcc-x64" to "window-gcc-x86"

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (4.27GB free)|
|Process Argv|--crash-reporter-id 757f731c-e02b-4a7d-b1e9-93c3e99e9aee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
format-on-auto-save|BDS|1.0.4
csharp-auto-formatter|bil|0.1.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
auto-save|mcr|1.0.3
csharp|ms-|1.23.9
cpptools|ms-|1.2.0
autoimport|ste|1.5.3
html-css-class-completion|Zig|1.20.0

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does this also happen after you run the Command Palette command to reload with all extensions disabled? If not, please restart VS Code and then use the Start Extension Bisect command to discover which extension triggers the problem. Then report it to that extension's author. The Report Issue option from VS Code's Help menu make that easy to do.
