### ISSUE TITLE
enable to open {project}.code-workspace in remote WSL

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode#116698]
Hi.

I have different ```.code-workspace``` projects and some of them I use in a remote WSl.
I would like a [project setting ](
https://code.visualstudio.com/docs/getstarted/settings)option in the .code-workspace to enable open directly in remote WSL.

Thanks in advance for any feedback.

**Comment by aeschli** [comment]
The recommended way is to place the `.code-workspace` in your WSL file system (e.g. /home/you/foo.code-workspace`) and open if from the WSL command line with `code /home/you/foo.code-workspace` or from the Windows command line with `code --remote wsl+Ubuntu /home/you/foo.code-workspace`

**Comment by aeschli** [comment]
You can also add a `remoteAuthority` property to the `.code-workspace` file
```
{
	"folders": [
		{
			"path": "myProject1"
		}
	],
	"remoteAuthority": "wsl+Ubuntu",
}
```

**Comment by alanlivio** [comment]
Thank you so much @aeschli the o  ``` "remoteAuthority": "wsl+Ubuntu-20.04"``` worked for me.
Although I do not find remoteAuthority at any place in the vscode documentation.
