### ISSUE TITLE
Support for NPM / Yarn workspaces in launch.json / tasks.json

### ISSUE THREAD

**Issue by Yzrsah** [microsoft/vscode#116675]
I have a monorepo using NPM workspaces or Yarn workspaces with the node linker.
When attempting to configure the debugger in `repo/packages/SomeChildWorkspace/.vscode/launch.json`, there is a problem:
```
"runtimeExecutable": "${workspaceFolder}/node_modules/.bin/next",
```
- This will fail because `${workspaceFolder}/node_modules` does not exist.
- The `node_modules` are hoisted to the monorepo's root a few directory levels up from the workspace that was opened in VSCode. That's the default+good hoisting behavior and we don't want to disable hoisting and bring back the old problem of having a bunch of `node_modules` directories (obsolete problem).

So I have to modify launch.json every time to use hard-coded paths. This breaks when the project is opened by different users. After fixing this various times I can see it's problem with the way the npm / yarn workspaces system is working.

- A variable called `${rootWorkspaceFolder}` which has explicit support for NPM / Yarn workspaces could solve part of this.

But there are further issues. If you are trying to use `${rootWorkspaceFolder}` for binary paths, it would work with npm or yarn's node linker, but it will still fail with yarn's PNP mode as `node_modules` may not even exist and the binary may be in the virtual cache location. A fix for that could require a variable that is able to resolve binary paths for a given package, like `${packageBinaryFolder:somepackage}/somecommand` or the simpler `${resolvePackageBinary:somecommand}`. I realize this sounds like a lot but I'm not sure how else to deal with the workspaces in VSCode when we cannot access correct path for binaries.

**Comment by weinand** [comment]
How would you solve the issue outside of VS Code when no VS Code variables are available?
