### ISSUE TITLE
Save button should be disabled if file is not dirty

### ISSUE THREAD

**Issue by bhumikasukhadiya0901** [microsoft/vscode#116689]
I am clicking on save all button in my vs code and it stays active even after there are all changes saved.

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.1.0

Please check the attached video.

https://user-images.githubusercontent.com/73881409/107940677-9f261d80-6fae-11eb-877a-18337f53f3da.mov

**Comment by isidorn** [comment]
Yeah that is the Save All button, we always allow to save, since that triggers formaters for example and disabling save if there are no changes would break some other people flow.
So for now - no action planned here, but leaving this open to gather more potential user feedback

**Comment by gjsjohnmurray** [comment]
@isidorn Perhaps have another button with basically the same icon except decorated with something to indicate unsaved changed (perhaps a dot). Use complementary when-clauses on this new item and the existing one so only the correct one shows.

**Comment by isidorn** [comment]
That might be a good idea, but I would not make any changes to the Open Editors view right now which is hidden by default.
