### ISSUE TITLE
tmLanguage syntaxes are not being rendered entirely correctly

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode#116612]
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:35:15.302Z)
OS version: Darwin x64 19.5.0

I noticed that in the Objective-C language, special variables (`#special_variables`) like `self`, `super`, and `_cmd` are not syntax highlighted at all. I also noticed that method calls are not syntax highlighted either, unlike regular C-style function calls.

After some digging around in the `.tmLanguage` file for Objc, I noticed that if I add a top-level include for the `#special_variables` repository and copy the declaration for `meta.function-call.objc` to the top level as well, both are syntax highlighted.

The default rendering:
![Original](https://user-images.githubusercontent.com/8371943/107847899-f791cb00-6db4-11eb-9467-1b1a5285755d.png)

With a duplicate top-level decl for `meta.function-call.objc`:
![With special_variables](https://user-images.githubusercontent.com/8371943/107847901-fe204280-6db4-11eb-8d01-8a8fab9b4879.png)

With the above, and `#special_variables` included:
![Screenshot 2021-02-13 at 4 31 14 AM](https://user-images.githubusercontent.com/8371943/107847924-3162d180-6db5-11eb-9513-cba38be37274.png)

I am filing the issue here and not over at [jeff-hykin/cpp-textmate-grammar](https://github.com/jeff-hykin/cpp-textmate-grammar) because I believe the grammar is correct. `#special_variables` is included by several other repositories in the file, such as `#implementation_innards`, and `meta.function-call.objc` is defined by `#bracketed_content` which itself is included at the top level.

That said, this means VS Code must not be rendering the syntax correctly.

**Comment by alexr00** [comment]
@NSExceptional I ended up opening this issue in jeff-hykin/cpp-textmate-grammar since the changes you're are asking for do involve updates to the grammar. If the folks over there say otherwise then I'll re-open this issue. https://github.com/jeff-hykin/cpp-textmate-grammar/issues/538
