### ISSUE TITLE
How to find out which node vscode is using

### ISSUE THREAD

**Issue by nijikokun** [Microsoft/vscode#11660]
I am trying to figure out which node to use to globally install extensions with but cannot figure it out for the life of me.

I am on the latest VSCode, OSX (el capitan), I use nvm and have around 7 node versions installed.

It would be great if you could specifically set a node version inside of vscode to be used that overrides the automagically found version...

**Comment by egamma** [comment]
VS Code doesn't ship its own version of Node, but leverages the node version that comes with electron. 

This version is shown in the about dialog:
![image](https://cloud.githubusercontent.com/assets/172399/18339654/15a39ecc-75a1-11e6-8ffa-c0001627b989.png)

**Comment by nijikokun** [comment]
@egamma it does not show that on osx: ![https://i.imgur.com/vY7rqnh.png](https://i.imgur.com/vY7rqnh.png)

**Comment by egamma** [comment]
@joaomoreno is there a way to see the node version on OS X?

**Comment by joaomoreno** [comment]
The following comment made me think you are talking about different things:

> to globally install extensions

Electron is built on top of Node, the version of which can be found in the DevTools: `process.versions`.

But, at runtime, Code finds Node in the path and uses that to run tasks, builds, etc. Is that what you meant @nijikokun?

**Comment by ovidius72** [comment]
I suspect VsCode on OS X doesn't find the node path when you use nvm. 
I had similar issues with tsc, node and any other executable file inside node/bin not recognized by VsCode.
To solve this I had to manually add the path to the node/bin directory in .profile.
`export PATH="$PATH:~/.nvm/versions/node/v5.3.0/bin"`

**Comment by joaomoreno** [comment]
Code should detect NVM's path for Node. I personally rely on this on my day-to-day development. If it doesn't on your machine, that is a valid bug you should file.

**Comment by ovidius72** [comment]
@joaomoreno  Are you on OSX or Windows?

**Comment by joaomoreno** [comment]
OSX. Although it also works in Windows with [`nvm-windows`](https://github.com/coreybutler/nvm-windows), on my other box.

**Comment by moimikey** [comment]
#14229
