### ISSUE TITLE
Window not focused on breakpoint hit when Chrome and VS Code maximized

### ISSUE THREAD

**Issue by zmechanic** [microsoft/vscode#116615]
Issue Type: <b>Bug</b>

Steps:
1. Set breakpoint in JSX code.
2. Breakpoint hit and code execution suspended

Expected:
Yellow highlight on line where breakpoint hit; being able to see current variable values.

Observed:
No higlight, VSCode halted (can't click inside). Need to switch to Chrome and back to VSCode. This will immediately indicate breakpoint line with yellow, and can see variables. Seems like focus issue.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (6.53GB free)|
|Process Argv|--crash-reporter-id 6bc32b6e-4df0-47fc-ad3c-da7600333664|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
dotenv|mik|1.0.1
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment]
@zmechanic 
1. can you please share some minimal project for which you can reproduce this?
2. Can you reproduce with VS Code insiders since we pushed some commit that might fix this https://code.visualstudio.com/insiders/
3. Can you post a screenshot


fyi @connor4312

**Comment by zmechanic** [comment]
Hi,

I found when it happens, and when not.

When I put Chrome window and VSCode window side-by-side, it works as
expected. Breakpoint line is immediately highlighted in VSCode. I put them
side-by-side just to take a screenshot for you, and I found that it worked.

However, as I only have one 15" screen on laptop, I run Chrome and VSCode
maximized. And this is when it's not happening. VSCode icon starts blinking
yellow, but when I expand it, no breakpoint highlight, and VSCode appears
to hang, it doesn't react to clicks. I need to flip to some other app, and
then back to VSCode so that it becomes responsive and shows breakpoint
highlight.

I used to be a desktop app developer, and experienced an identical issue
with our WPF app. There was something with focus on app activation. I know
VSCode is Electron based, but the behaviour seems identical to me.

Thanks,
Alex

**Comment by isidorn** [comment]
So this sounds like focusing the window does not work if Chrome is open side by side.
Sounds like an Electron issue, also assigning to @deepak1556 since I know we already had users complaining that window.focus sometimes does not work

**Comment by zmechanic** [comment]
No, it's opposite. Side-by-side works OK. Both maximized doesn't work.

**Comment by deepak1556** [comment]
Can you check if the issue continues to happen when you start the app like `code --disable-features=CalculateNativeWinOcclusion`

**Comment by zmechanic** [comment]
You are right. The disable feature fixes the issue.

**Comment by deepak1556** [comment]
Thanks for checking, merging the issue to https://github.com/microsoft/vscode/issues/114459. Please follow that issue for updates.
