### ISSUE TITLE
Adding folder to workspace closes Interactive window and data viewer

### ISSUE THREAD

**Issue by AltfunsMA** [microsoft/vscode#116630]
Issue Type: <b>Bug</b>

Adding a folder to the explorer window should not have this behaviour. If unavoidable, a warning should be given before executing.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.15.0-76-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.01GB free)|
|Process Argv|--crash-reporter-id f792cfdc-235a-4add-9b1f-33640b4a8ae6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: osgiliath|
|OS|Linux x64 4.15.0-76-generic|
|CPUs|Intel Core Processor (Haswell, no TSX) (12 x 2294)|
|Memory (System)|47.16GB (15.12GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
file-properties-viewer|bru|0.5.0
path-intellisense|chr|2.3.0
r|Iku|1.6.4
vscode-edit-csv|jan|0.5.4
kite|kit|0.138.0
rainbow-csv|mec|1.8.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
vscode-data-preview|Ran|2.2.0
rewrap|stk|1.13.0
code-spell-checker|str|1.10.2
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by isidorn** [comment]
Please file to the extesnion that adds the interactive window and data viewer
VS Code is not closing this views when new folder is added to the explorer window

**Comment by AltfunsMA** [comment]
Thanks for this? If you've managed to isolate the problem as stemming from an extension, wouldn't it make sense for you to write your message above as an issue to that extension rather than reply to me on this thread telling me to do it? I can already read to the bot's message. I'm not even sure which extension you are referring to: Jupyter? Python?
