### ISSUE TITLE
Searching + hitting Enter on breadcrumbs no longer working

### ISSUE THREAD

**Issue by jackfranklin** [microsoft/vscode#116696]
Issue Type: <b>Bug</b>

If I want to get to a file in the same directory as the one I'm editing I'll usually go via breadcrumbs. My workflow is:

1. Hit `cmd+shift+.` to bring up the breadcrumbs ( I have symbols turned off via ` "breadcrumbs.symbolPath": "off",`), so this gives me a list of files in the directory)
2. Type part of the file I want to get to, say `form.js`
3. Hit `enter` and I'll be taken there.

I'm not sure when exactly it broke, but as of today I'm unable to do this. When I search `form`, it highlights that file in the file list, but hitting enter does not take me to hit. I have to use the arrow keys to navigate to the file in the list, at which point it then does take me there if I hit enter. This is a change in behavour (I'm not sure if it's intentional or not), where I now have to focus the file in the breadcrumb list manually rather than it being focused by virtue of matching the string I've searched for.

I can replicate this with all extensions disabled so I don't believe a particular extension is the cause.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.7.17-1rodete5-amd64

**Comment by jackfranklin** [comment]
I saw #116688 which may be related - just flagging in case that's useful!

**Comment by jrieken** [comment]
Works just fine more (stable and insiders). Make sure that you have no unwanted keybindings configure and no extension activated that could change this keybinding

**Comment by jackfranklin** [comment]
So I disabled all extensions, commented out all custom keybindings, and removed all my settings (other than `breadcrumbs.symbolPath: off`).  I still see the bug on VSCode Stable (Mac, 1.53.2), but cannot reproduce on the latest Insiders.

**Comment by jrieken** [comment]
In that case I'd say it is fixed. Tho, I can not reproduce in stable either
