### ISSUE TITLE
Official JSDoc Type Syntax Not Working

### ISSUE THREAD

**Issue by michaelalhilly** [microsoft/vscode#116679]
Issue Type: <b>Bug</b>

Please add support for official JSDoc type syntax using curly braces.

@param {string} name Something about param.
@returns {string} Something about returns.

Right now types inside curly braces are not displayed in the function info popup content area. However, the shorthand syntax is correct.

Thanks.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.50GB free)|
|Process Argv|-psn_0_8771677 --crash-reporter-id c78c0129-b48a-4549-aa93-3069afc14da8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
prettier-vscode|esb|5.9.2
rest-client|hum|0.24.4
materialdesignicons-intellisense|luk|3.1.0
vscode-language-babel|mgm|0.0.30
vscode-filesize|mkx|2.1.4
vscode-docker|ms-|1.9.1
vscode-typescript-next|ms-|4.3.20210214
vetur|oct|0.32.0
indent-rainbow|ode|7.5.0
code-settings-sync|Sha|3.4.3
language-stylus|sys|1.11.0
vsfire|tob|1.4.1
go-to-method|tri|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by IllusionMH** [comment]
What type of file are you using?

It correctly shows in .js/.jsx files already.
![image](https://user-images.githubusercontent.com/1312662/107942287-aee43880-6f93-11eb-83fb-659d0a645fcb.png)

If you are using JSDoc in .ts/.tsx - types types should be in type annotations only and ignored in JSDoc.

**Comment by michaelalhilly** [comment]
@IllusionMH Ah ok. I though the data type was suppose to display to the right of the tags, which is missing from your screenshot as well. However, it seems the bottom section of the popup is for the tag, name, and description text only. That makes sense since the types are already provided at the top of the popup.

Sorry about that. Closing this now.
