### ISSUE TITLE
New file icon at open editors and tab bar.

### ISSUE THREAD

**Issue by oceanroleplay** [microsoft/vscode#116633]
## HI, Devops.
We know, we can create new untitled file using CTRL+N or by selecting manually from File menu.

### **But, if we just have one more button on the location mentioned below in image. I guess, it would be really helpful to many people. specially, who are not developers or starting to learn it.**

I personally, myself lazy to go through menus. I just use shortcuts, but sometime, when switching tabs with mouse. I just hope that I can have this buttons to do it quickly.

Location 1: 
![image](https://user-images.githubusercontent.com/43092101/107867234-32702d80-6e9f-11eb-852a-66a0e04fdf53.png)

Location 2: 
![image](https://user-images.githubusercontent.com/43092101/107867238-3d2ac280-6e9f-11eb-9e5f-bbdee485c2d2.png)

Just need a **+** button, which will execute new file function.

**Comment by YashTotale** [comment]
This would be a great feature!

**Comment by isidorn** [comment]
Hi, even though I am not a DevOp I like this idea. So we add a PLUS in the Open Editors Title area to create a New Untitled File.

Even though Open Editors is now hidden by default for new users, I think this makes sense overall and I would probably add it.
fyi @bpasero in case you do not like the idea

**Comment by isidorn** [comment]
To verify:

Open the Open Editors view and make sure there is the "New Untitled File" action in the Title area. That it functions as expected and that it makes sense.

**Comment by jrieken** [comment]
`verified` tho it is a little confusing that it is different from the "same icon" that's in the explorer
