### ISSUE TITLE
Source Control icon, the badge is periodically shown briefly

### ISSUE THREAD

**Issue by neoneye** [microsoft/vscode#116658]
I have never experienced this before. 

The left-side icon for "Source Control" periodically flashes a badge, that looks like a blue clock icon. The flash lasts for less than 0.5 seconds. Here is a screenshot.

![vscode_flash](https://user-images.githubusercontent.com/147971/107888240-45b8e280-6f0b-11eb-8395-013fc48eb20f.png)

The flash frequency was around every 5 seconds (loose estimate). 

Now as I'm writing this, the flashing seems to have stopped. Maybe it lasted between 5 and 10 minutes.

It happened so many times, that I'm now sending a report to you.

I have no pending changes to my repo, so there should be no badge. IMHO a badge should only be shown if there is something severely wrong, and it takes focus away from my own coding project.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including whether the problem still occurs if you temporarily disable all extensions.

**Comment by neoneye** [comment]
The guidelines says how to `If you want to quickly disable all installed extensions, there is a Disable All Installed Extensions command in the Command Palette and More Actions (...) drop-down menu.`, but I can't seem to figure out to follow these quick instructions. Perhaps make it more verbose.

**Comment by neoneye** [comment]
Aha `SHIFT+CMD+P` opens a the `Command Palette`. It would be helpful if the instructions showed this keyboard combo, or that the gear icon in the bottom left corner.

**Comment by neoneye** [comment]
With all extensions disabled, I once did see the a flash with blue clock badge. I think a badge should only be shown if something is very wrong. I'm clueless to what a blue clock symbol indicates.

**Comment by gjsjohnmurray** [comment]
The clock badge is a progress indicator that appears if some long-running code asks for it to be displayed. You will see this on the gear icon (bottom left) after you have used its menu to check for updates. If no update is available the clock only appears briefly. But if an update is found the clock displays while downloading.

I guess your SCM provider (maybe the git default one) is requesting a progress indicator while it performs some operations.

> Aha SHIFT+CMD+P opens a the Command Palette. It would be helpful if the instructions showed this keyboard combo, or that the gear icon in the bottom left corner.

I think it is reasonable for most instructions to assume the reader knows what Command Palette is and how to access it. This is a fundamental feature of VS Code and is documented in the [User Interface section of GET STARTED](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

The upcoming "Getting Started" experience (previewing in [Insiders](https://code.visualstudio.com/insiders), where it can be accessed from the Help menu) puts Command Palette as the first item in its "Learn the Fundamentals" section.

**Comment by neoneye** [comment]
Yes, I use git. When a badge is briefly flashing, it takes attention away from programming. IMHO the brief flashing clock badge is not good ux.

**Comment by gjsjohnmurray** [comment]
Does the Git channel on the Output tab of the Panel area of the UI reveal what is happening at the time the clock appears?

**Comment by neoneye** [comment]
I will keep the Source Control open and look out for what happens.

I have never used the Source Control tools. I use SourceTree for my many repos.

**Comment by neoneye** [comment]
While the blue clock is shown, there is a blue bar that animates from left to right.
The flash is less than 0.5 seconds. Here is a screenshot.

![blue_bar](https://user-images.githubusercontent.com/147971/107944238-2616ce00-6f8e-11eb-8292-54b13c2b1967.png)


Sometimes it happens as I'm typing. Sometimes it happens when I'm not doing any changes to the code. Sometimes it happens after I have been recompiling my Rust project from commandline and switches focus back to Visual Studio Code.

Maybe SourceTree touches the `.git` dir, causing Visual Studio Code to wake up.

**Comment by gjsjohnmurray** [comment]
Since you aren't using it, maybe use the context menu on the Source Control icon in the Activity Bar to hide it.

**Comment by neoneye** [comment]
Thanks, I have now hidden the Source Control icon. However it doesn't fixes the brief flashes.

**Comment by gjsjohnmurray** [comment]
> Thanks, I have now hidden the Source Control icon. However it doesn't fixes the brief flashes.

I'm not clear where you are seeing the brief flashes now that you have hidden the icon on which the blue clock was appearing. Can you paste a short recording (animated GIF or an MP4 file)?

**Comment by neoneye** [comment]
For me concerned it's fixed, the Source Control icon is hidden, and I no longer see anything flashing, spoiling my focus on coding.

IMHO, it's not fixed, since hiding the Source Control icon is not a fix the deeper problem, that it's possible for a badge flash without providing a text message explaining what the issue seems to be.
