### ISSUE TITLE
Custom Keybindings: Multiple when conditions with predefined vscode variables

### ISSUE THREAD

**Issue by anishmittal2020** [microsoft/vscode#116677]
- VS Code Version: 1.53.2
- OS Version: Ubuntu 20.04

Steps to Reproduce:

I have defined the following 2 custom keybindings

```
    {
        "key": "alt+x",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "\u000AScript1 -f ${file}\u000A" },
        "when": "${fileDirname} == '/home/nikhil/Documents/Git/MyCollection' && ${fileExtname} == '.markdown' && !editorReadonly && editorLangId == 'markdown'"
    },
    {
        "key": "alt+x",
        "command": "workbench.action.terminal.sendSequence",
        "args": { "text": "\u000AScript2 ${file}\u000A" },
        "when": "${fileDirname} != '/home/nikhil/Documents/Git/MyCollection' &&  !editorReadonly && editorLangId == 'markdown'"
    },
```
When the active file path is: '/home/nikhil/Documents/Git/MyCollection/Data.markdown' and when I press the keybinding: Alt+x: the second one works but the first one doesn't works. But, in this case first one should work and not the second keybinding as the `${fileDirname} == '/home/nikhil/Documents/Git/MyCollection' `

I wanted to ask if custom keybindings support  [Visual Studio Code Predefined Variables Reference](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables). If not, is it possible to support it?

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by ArturoDent** [comment]
Those variables, like `${fileDirname}` and `${fileExtname}`,
can be used in the `args` but are not used in the `when clauses` - see [Available Contexts].(https://code.visualstudio.com/api/references/when-clause-contexts#available-contexts)

So first replace `${fileDirname}` with `resourceDirname`  and     

`${fileExtname}` with `resourceExtname` and see if that helps.

[Note: I am personally having trouble getting `resourceDirname` to match anything but I am on Windows with reversed path separators.]

**Comment by anishmittal2020** [comment]
@ArturoDent  This does not work
