### ISSUE TITLE
https://aka.ms/vscodeissuereporting forwarder needs updating

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#116687]
https://github.com/microsoft/vscode/blob/88089d3f204c8367376e3e0729e4382ff9146172/.github/commands.json#L161 links to https://aka.ms/vscodeissuereporting from the comment added by  vscode-triage-bot in response to the /needsMoreInfo directive. A consequence of the recent rename of the 'master' branch' to 'main' (#116341) is that this link's ultimate target needs updating to avoid giving the user the following message:

![image](https://user-images.githubusercontent.com/6726799/107939386-8b62c300-6f7e-11eb-9d1a-d2688a1f0f96.png)

Better still, please point it to the wiki page at https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions instead, which has been updated more recently than CONTRIBUTING.md

**Comment by gjsjohnmurray** [comment]
> Better still, please point it to the wiki page at https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions instead, which has been updated more recently than CONTRIBUTING.md

@chrmarti it seems you decided to keep this forwarder pointing at CONTRIBUTING.md instead of the wiki page. I think the wiki page does a better job of guiding people towards better reports.

**Comment by chrmarti** [comment]
Thanks @gjsjohnmurray, missed your suggestion earlier. I have updated the link.

@Tyriar (seeing you are the lastest updater of the wiki page) Should https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md just point to the wiki page?

**Comment by Tyriar** [comment]
Ideally CONTRIBUTING.md would also say how to contribute code which it does not do currently, I'd be in favor of it just pointing to https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions and https://github.com/microsoft/vscode/wiki/How-to-Contribute, we may need to migrate some content away from https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md though (bots aren't mentioned in the wiki)
