### ISSUE TITLE
Emmet not creating new lines as expected

### ISSUE THREAD

**Issue by AnsonH** [microsoft/vscode#116634]
Issue Type: <b>Bug</b>

## Steps to Reproduce

1. Create a new HTML file, let say `test.html`
2. Add the following boilerplate, which is the same as the boilerplate in [Emmet's "Try it Yourself" page](https://docs.emmet.io/)
    ```html
    <!doctype html>
    <html lang="en">
    <head>
        <title>Demo</title>
    </head>
    <body>
        
    </body>
    </html>
    ```
3. Inside the `body` tag, type `a>span*3` and press "Tab" to use the Emmet abbreviation.

## Expected Result

Go to [Emmet's Documentation](https://docs.emmet.io/) and press the green "Try it yourself" button. When I type `a>span*3` and press "Tab", the following HTML is generated:

```html
<a href="">
    <span></span>
    <span></span>
    <span></span>
</a>
```
![Emmet expected result](https://i.imgur.com/A3pKCrX.gif)

## VS Code Result

However, VS Code generates the following code:

```html
<a href=""><span></span><span></span><span></span></a>
```

![VS Code result](https://i.imgur.com/IW4kZVO.gif)

Therefore, is this behavior a VS Code bug or is it expected behavior? This is because I think VS Code used to create new lines for each `span` tag when I used the above emmet. Thanks!

## Environment info
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.84GB free)|
|Process Argv|D:\\Web Development\\test --crash-reporter-id a37b4fcd-1cbd-4f2c-bb84-018b710e8a69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
material-icon-theme|PKi|4.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by rzhao271** [comment]
There's a few things going on:
- `span` is considered an inline element in the current Emmet so that's why it all goes on one line
- the Emmet sandbox site and documentation isn't currently completely in sync with the Emmet repository, or at least, I don't think it is

I wouldn't consider `span` expanding onto the same line like that a bug unless it seriously affects productivity.
