### ISSUE TITLE
Console prompt is not displayed after opening the terminal

### ISSUE THREAD

**Issue by yhsb2k** [microsoft/vscode#116610]
- VS Code Version: 1.53.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open terminal
2. See that no prompt is displayed on the first line. It is displayed only after I press Enter.
![terminal-display-issue](https://user-images.githubusercontent.com/13915612/107847437-3b57f500-6df4-11eb-96c2-b80725721997.gif)

More details from me:
* 4k monitor with 225% scaling
* vscode user settings related to terminal:
```json
	"terminal.integrated.scrollback": 50000,
	"terminal.integrated.shell.windows": "cmd.exe",
```
* If I commented the line ```"terminal.integrated.shell.windows"``` (powershell is used instead of cmd) - issue has changed a little bit: console prompt is not displayed until I wrote any symbol. Interesting thing is that this issue with powershell appears only once after vscode has been started. If I close terminal (exit) and open it again - console prompt is displayed correctly.
* If I open cmd.exe in Windows (not in vscode), console prompt is displayed correctly.
* ```"terminal.integrated.scrollback"``` line doesn't impact to this issue.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
Does this happen for you if you use Insider's?

**Comment by yhsb2k** [comment]
Tested with vscode-insider's:
>Version: 1.54.0-insider
>Commit: 192c817fd350bcbf3caecae22a45ec39bae78516
>Date: 2021-02-19T05:14:28.632Z

The same behavior. Issue is reproduced.

**Comment by meganrogge** [comment]
Thanks for that info. When did this begin happening?

**Comment by yhsb2k** [comment]
Issue is reproducible on **1.57.1** only with `"terminal.integrated.defaultProfile.windows": "Command Prompt"`

> Thanks for that info. When did this begin happening?

I have investigated it a bit:

| vscode version        | Same issue with powershell           | Same issue with cmd  |
| ------------- |:-------------:|:-----:|
| >= 1.56.0    | no reproduce | reproduced (no input prompt) |
| 1.55.2      | reproduced (no input prompt till I start typing) | reproduced (no input prompt) |
| 1.55.0      | reproduced (no input prompt till I start typing) | reproduced (no input prompt) |
| 1.53.0      | reproduced (no input prompt till I start typing) | reproduced (no input prompt) |
| 1.50.0      | reproduced (no input prompt till I start typing) | reproduced (no input prompt) |
| 1.45.0      | reproduced (no input prompt) | reproduced (no input prompt) |
| 1.35.0      | reproduced (no input prompt) | reproduced (no input prompt) |


So, looks like since 1.56.0 the issue has been fixed for powershell, but not for "Command Prompt".

**Comment by yhsb2k** [comment]
More information about my system:
| | |
|------------------|------------------|
| OS Name:  | Microsoft Windows 10 Enterprise LTSC 1809 |
| OS Version:               | 10.0.17763 N/A Build 17763 |

**Comment by Tyriar** [comment]
This looks like an issue with our old terminal backend "winpty", going forward we are focusing our efforts on the new backend "conpty" which is build by the Console team at Microsoft and should fix many issues with the terminal under Windows. You can read more about getting ConPTY [here](https://github.com/Microsoft/vscode/issues/57803#issuecomment-449495423).

/duplicate https://github.com/Microsoft/vscode/issues/45693
