### ISSUE TITLE
Stuck on a blank background for around 10 seconds on start-up

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#116607]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open vscode and watch as it can take up to 10 seconds to load your code. Stuck on a blank screen.
2.

Does this issue occur when all extensions are disabled?: Yes/No
It's faster but still slow.

Extensions:
Better TOML
Community Material Theme
Discord Presence
EJS language support
GitLens
LiveShare
Material Icon Theme
npm
Paste JSON as code
rust-analyzer
SCSS Intellisense
Tailwind CSS IntelliSense
Template String Converter
Vetur
WakaTime
ZipFS

**Comment by acostaf** [comment]
1+

**Comment by Milo123459** [comment]
Will fill it out.

**Comment by krasoffski** [comment]
Same freeze problem on ubuntu 18.04
Even switch between tabs take a while (more than 10-15 seconds).

**Comment by Milo123459** [comment]
Is there an idea about what's causing this bug?

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by Milo123459** [comment]
https://github.com/microsoft/vscode/issues/117215
