### ISSUE TITLE
Feature request : add file location and line number to CompletionItem

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode#1166]
Hello,

I've read this new feature will be available soon:
With the Dec15 update you can invoke this command https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostLanguageFeatureCommands.ts#L55 to retrieve the same list of completions the UI would show.

It would be great to know where the CompletionItem is pointing to (which file and which line number) if available locally of course.
This could help extensions to display a function, or to go to that function, or to analyse the function to add more info for example when available ...

It could apply to provideHover, so when the text is hovered one can add info regarding the function pointed with an extension.

I hope this could help others.

**Comment by jrieken** [comment]
Tend to disagree because its not part of the completion item model. We might enhance the return to be a CompletionsResult instead of an CompletionItem-array and in there we could provide more context. However, when you make that command-call, you must already know the file and position: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/common/extHostApiCommands.ts#L265

**Comment by jrieken** [comment]
Related to #202 and #752

**Comment by Alphapage** [comment]
I'm agree with you.
If you create a language extension, then you don't need such a feature I think.

My request applies more to extend an existing language.

**Comment by jrieken** [comment]
We are sketching up some ideas here #1172. Still, note that the commands are not meant to be used when extending a language but when building on top of a language, like a status bar UI for the hover.

**Comment by jrieken** [comment]
Closing because we don't want the API to be used for extending other extensions. If, let's say you want to enrich TypeScript, you should use API that extension exposes.
