### ISSUE TITLE
Interrupts_Typing

### ISSUE THREAD

**Issue by hridi-vsCode** [microsoft/vscode#116669]
Issue Type: <b>Bug</b>

Suppose I am trying to give a heading like <h1>Search</h1>
I can not write 'c' in 'search' sometimes as it keeps on popping that :: (c,h has no key binding)::
I don't understand as I have not set any key binding with this two letters then why doesn't it let me complete my word?
This problem started occuring after reinstalling my VS Code, as it got deleted unexpectedly.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.36GB free)|
|Process Argv|--crash-reporter-id e92e6097-8776-4ae4-a675-42fd98653e24|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
codeigniter4-snippets|ben|0.0.2
vscode-intelephense-client|bme|1.6.3
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.1
sublime-keybindings|ms-|4.0.7
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
bootstrap5|shr|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the problem also happen after you run the command to reload with all extensions disabled?

**Comment by hridi-vsCode** [comment]
I haven't tried with all extensions disabled. I will let you know the
outcome after following this procedure.

**Comment by hridi-vsCode** [comment]
Disabling all my extensions didn't work either!
Please tell me a solution, I love to use VS Code for my projects.
Today i realized i am having problem only while i am trying to type small
'c' only. But most often i am trying to type c. And that's when it gets
painful to use this VS Code.

**Comment by gjsjohnmurray** [comment]
Please follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues
