### ISSUE TITLE
Import Module issue

### ISSUE THREAD

**Issue by KingyKingKongg** [microsoft/vscode#116655]
Issue Type: <b>Bug</b>

I'm not sure if this is an extension issue or not.

The import Module shows as an error within VSCode. It did not do that before but just wanting some information as to a possible solution. I do not use import Module a lot but if I want to use it in the future, i'd want it to work. 

Thank you

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.10.0-kali2-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|7.53GB (0.17GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 2ebd0f72-4dc7-4d3b-91d3-690c35e8cf90|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-django|bat|1.3.0
kivy-vscode|Bat|0.5.5
python-extension-pack|don|1.6.0
vscode-mysql|for|0.4.0
vsc-python-indent|Kev|1.12.0
MagicPython|mag|1.1.0
kvlang|Mon|0.0.5
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
vscode-qt-for-python|sea|0.5.3
pykv-snippets|Tak|1.0.7
pygame-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.11
jinja|who|0.0.8
pyqt-integration|zho|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by mjbvz** [comment]
Please share steps to reproduce this issue and example code that demonstrates the problem

/needsMoreInfo

**Comment by KingyKingKongg** [comment]
> Please share steps to reproduce this issue and example code that demonstrates the problem
> 
> /needsMoreInfo

I literally typed "Import Module" at the top of the program and VS Code does not recognize it

**Comment by KingyKingKongg** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

I only typed "Import Module" at the top of the program and VS Code does not recognize it

**Comment by mjbvz** [comment]
What language is this for?
