### ISSUE TITLE
Scoped 'getConfiguration' is causing unexpected behaviour

### ISSUE THREAD

**Issue by kylewetton** [microsoft/vscode#116670]
- VS Code Version: 1.53.2
- OS Version: macOS Catalina (10.15.7)

Steps to Reproduce:

1. Generate a showWorkspaceFolderPick
2. Pass returned folders uri as a scope property in getConfiguration

Example: 

        const quickPickWorkspace =  async () => {
	        const folder = await vscode.window.showWorkspaceFolderPick({ placeHolder: 'Pick the workplace folder...' });
	        if (folder) {
		        console.log(folder.uri); // Always correct / different
		        const configuration = vscode.workspace.getConfiguration('', folder.uri);
		        const currentValue = configuration.get('boxed-components.useTemplates');
		        console.log('Reading:', currentValue); // Always the same settings (incorrect)
	        }
        }

The expected behaviour here is that getConfiguration should return the value from <workspaceFolder>/.vscode/settings.json. 

I believe this value keeps getting cached, I'm able to swap out which value keeps getting returned. The incorrect value is returned each time even if the workspace folder with that setting is removed from the explorer

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
You are changing your `boxed-components.useTemplates` setting in between calls to `quickPickWorkspace()` I assume?  But the updated setting is not being read correctly?  

When I call `quickPickWorkspace()` (using your code) via a custom command I can't reproduce this behaviour.  How are you calling `quickPickWorkspace()`?

 I am on W10 though, so can't replicate macOS.

**Comment by kylewetton** [comment]
@ArturoDent not exactly, I simply have two folders in my Workspace (two roots), both have .vscode/settings.json files, and both have a different value set in this configuration.

Here's the repo to this extension, it's very basic. In extension.js on line 88 you'll see the snippet above that I mentioned. Any eyes on this would be greatly appreciated! the ReadMe explains the data shape that the extension expects

https://github.com/kylewetton/vscode-boxed-components

**Comment by sandy081** [comment]
I see you have not defined any scope to your setting `'boxed-components.useTemplates'`. By default it will be scope to `window` and values from folders will be ignored while reading in a MR workspace.

You have to define your setting to be resource scoped so that it can be applied per folder in a MR folder workspace. 

See the sample for reference - https://github.com/microsoft/vscode-extension-samples/blob/main/configuration-sample/package.json
