### ISSUE TITLE
SCSS file keeps freezing the editor

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#11668]
- VSCode Version: 1.5.0-insider (nightly)
- OS Version: Window 10 64bits

Steps to Reproduce:
1. Open a .scss file
2. Try editing it, it'll eventually freeze randomly, happened a couple of times when editing the code:

``` sass

.active-voucher { // first time I paste this, it froze
   background: #F6F49F;
   text-align: center; 
   pre {
     margin: 0; // happened a lot of times when writing this
     padding: 0;
     vertical-align: middle; // happened once when I typed vertical-ali
   }
}
```

I cannot reproduce all the times, it happens really randomly.

**Comment by ramya-rao-a** [comment]
@pocesar What extensions do you have installed?
Do you still see the issues when extensions are disabled? `code --disable-extensions`

**Comment by pocesar** [comment]
![fasdf](https://cloud.githubusercontent.com/assets/461084/18366284/763bddc6-75ec-11e6-8a5e-c85c07a6a5fa.jpg)

yes, it happens with extensions disabled

**Comment by sandy081** [comment]
@ramya-rao-a css-less-sass areas are owned by @aeschli. So you can assign him those related issues.

Thanks.

**Comment by aeschli** [comment]
Thanks for the example. I'm desperatly trying to reproduce this freeze issue, it has been reported a few times now, but it never happens to me.
The next time you see it, can you check out the Windows Task Manager?
- add the 'Command Line' column in the processes view
- find out which VSCode process runs havoc.

@f83d40f is for September, so its not relevant

**Comment by ramya-rao-a** [comment]
@sandy081 Sorry there was a mapping given to me that I was following. Will keep the update in mind. I must have passed on quite a few of css-less-sass issues over to you the past couple of days

**Comment by sandy081** [comment]
@ramya-rao-a no worries :)

**Comment by pocesar** [comment]
@aeschli I can give you the entire scss if you want. the freeze is pretty random, sometimes just opening the file in the editor will freeze it after 1-2 seconds

**Comment by aeschli** [comment]
Do you have lots of color decorators? I just made a fix to limit the number of decorators. You can test it from tomorrow in the latest https://code.visualstudio.com/insiders buil

**Comment by pocesar** [comment]
my .scss file imports bootstrap partial .scss files, maybe it's a "hidden" cascade? the bootstrap sass files are massive

**Comment by aeschli** [comment]
We don't follow the includes, so, no, that's not a problem. 

Do you have any extensions installed? Please try running with  `code --disable-extensions`.
Also if you can check the task manager which process (with which command line arguments) is blocked that would be great.

**Comment by pocesar** [comment]
Haven't had this problem again in latest insiders versions
