### ISSUE TITLE
Window crashing

### ISSUE THREAD

**Issue by cowboycodr** [microsoft/vscode#116602]
Issue Type: <b>Bug</b>

I am doing algorithmic stuff which uses intense loops. The window keeps crashing when I output stuff per loop to the console. Make it so instead of crashing the window it crashes the tab like google chrome does. 

VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
prettier-vscode|esb|5.9.2
code-runner|for|0.11.2
kite|kit|0.138.0
auto-save|mcr|1.0.3
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.0
vsliveshare|ms-|1.0.3629
gradle-language|nac|0.2.3
java|red|0.75.0
vscode-gradle|ric|3.5.2
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by weinand** [comment]
How are you running your "algorithmic stuff"?
In the debugger or in the integrated terminal?
What language are you suing?
What window keeps crashing?

Please provide more detailed steps.
