### ISSUE TITLE
new release: Wrong Gui initialized on Ubuntu 20.04

### ISSUE THREAD

**Issue by giorgioborri** [microsoft/vscode#116682]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. install last release
2. run code

Does this issue occur when all extensions are disabled?: Yes/No

on ubuntu 20.04 I use the ppa to maintain the updated code app
but with the last update i got a "black boxed gui" when code start
I need to downgrade to the last correctly run version: 1.52.1-1608136922

**Comment by dariusmihut** [comment]
I have the same problem on OpenSuse, the problem appears starting with the version 1.53.0-1612368438.el7

I am using the repository https://packages.microsoft.com/yumrepos/vscode
Kernel : Linux *** 4.4.104-18.44-default #1 SMP Thu Jan 4 08:07:55 UTC 2018 (05a9de6) x86_64 x86_64 x86_64 GNU/Linux

OpenSuse version ="openSUSE Leap 42.2"

![image](https://user-images.githubusercontent.com/7417010/107936065-dbe01d80-6f8a-11eb-8a60-7db06a4bd130.png)

and when turning fullscreen it opens like this:
![image](https://user-images.githubusercontent.com/7417010/107936186-0336ea80-6f8b-11eb-9053-8af4bf7c75ce.png)

**Comment by deepak1556** [comment]
Do you have the issue when you start the app with `--disable-gpu` ?

**Comment by giorgioborri** [comment]
Thanks for answer
I've downloaded the la last deb "code_1.53.2-1613044664_amd64.deb"
and installed
launched with code --disable-gpu
It run normally with viewable gui

Il giorno mer 17 feb 2021 alle ore 19:31 Robo <notifications@github.com> ha
scritto:

**Comment by dariusmihut** [comment]
Hello,

I can confirm that the last version (1.53.2-1613044734.el7) published in the repo https://packages.microsoft.com/yumrepos/vscode is working also on opensuse with --disable-gpu

**Comment by deepak1556** [comment]
Thanks for confirming, merging to https://github.com/microsoft/vscode/issues/115868
