### ISSUE TITLE
Error: Call not found: createConsoleMainLogger

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116691]
* run integration tests
* see the error below

tests seem to run, when running them out the debugger the dev tools console prints output

```
Uncaught (in promise) Error: Call not found: createConsoleMainLogger", source: file:///Users/runner/work/vscode/vscode/out/vs/code/electron-browser/workbench/workbench.html?config=%7B%22_%22%3A%5B%22%2FUsers%2Frunner%2Fwork%2Fvscode%2Fvscode%2Fextensions%2Fmarkdown-language-features%2Ftest-workspace%22%5D%2C%22user-data-
```

**Comment by bpasero** [comment]
I think we only set this up when running tests from the CLI so that there is output.

**Comment by jrieken** [comment]
> I think we only set this up when running tests from the CLI so that there is output.

I am very sure that we used to show output from running tests. Now, when you run them locally you see NO test related output, no passes, no fails. This is pretty bad when you develop API tests

**Comment by bpasero** [comment]
I pushed a workaround so that output appears again but the coloring is all gone. @sandy081 I think you might have nuked the original `consoleMainLogger` in your change?

**Comment by sandy081** [comment]
@bpasero Thanks for the fix. 

I do not think I have removed the colouring, it was not there even before - 

https://github.com/microsoft/vscode/blob/678acbe536491d9dccf1b983291fe61b29e26fcc/src/vs/platform/log/common/logIpc.ts#L58-L78

I can add it if wanted.

**Comment by jrieken** [comment]
I am very sure that it didn't look like this

<img width="506" alt="Screenshot 2021-02-17 at 13 23 46" src="https://user-images.githubusercontent.com/1794099/108203884-5fcd0d80-7123-11eb-8f7b-e299d80564f4.png">

**Comment by bpasero** [comment]
Yeah, see `yarn test` from a `yo code` generated extension using stable:

![image](https://user-images.githubusercontent.com/900690/108205100-e59d8880-7124-11eb-9784-083654968784.png)

**Comment by sandy081** [comment]
Yes, formatting was broken. Fixed it.

![image](https://user-images.githubusercontent.com/10746682/108375682-78602500-7202-11eb-9250-d78d08ec1b2a.png)
