### ISSUE TITLE
Boot time 5-10 min windows 8.1

### ISSUE THREAD

**Issue by BrandinO771** [microsoft/vscode#116665]
Issue Type: <b>Performance Issue</b>

After starting the application it takes 5-10+ minutes to load. This was an issue during 2019 and then mid 2020 Microsoft made some change that helped and VS code was launching instantly on my machine. I have tried everything like closing all projects prior to closing the app and then relaunching and that has NO effect. VS Code maxes out box my C:  and D: drive during this 5-10 min loading period. I am not sure if windows defender is blocking the app from loading quicker? PLease reoptimize VS Code for windows 8.1 basically some update you did between Feb 5  and Feb 12, 2021 both added 4 gigs to my hard drive and seriously bogged down the startup of VS Code...  my email:   brandon.steinke@yahoo.com. thanks 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.48GB free)|
|Process Argv|--crash-reporter-id d702b472-b94a-4ae4-9dbc-381e257932b4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    48	  9768	code main
    0	    39	  7236	   gpu-process
    0	    53	  7644	   window (Issue Reporter)
    0	     6	  9820	   crashpad-handler
    0	     9	  9948	   utility
    0	   165	 10060	   window (curr_error_logs.txt - private_rummi_game_proj - Visual Studio Code)
    0	     2	  5604	     winpty-process
    0	     3	  3220	       console-window-host (Windows internal process)
    0	     1	  6096	       "C:\Program Files\Git\bin\bash.exe"
    0	     4	   340	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    59	  6392	     extensionHost
    0	    10	  4912	       electron_node server.js 
    0	     3	  5192	         "C:\Program Files (x86)\iTunes\iTunesHelper.exe" 
    0	     1	  7080	         "C:\Program Files (x86)\Common Files\Java\Java Update\jusched.exe" 
    0	    18	  8432	         "C:\Program Files (x86)\Creative\Sound Blaster Cinema\Sound Blaster Cinema\SBCinema.exe" /r
    0	    56	  6900	       electron_node tsserver.js 
    0	    24	  1276	         electron_node typingsInstaller.js typesMap.js 
    0	    49	  7796	       electron_node tsserver.js 
    0	     2	  8424	     watcherService 
    0	     1	  7008	       console-window-host (Windows internal process)
    0	    11	  9972	     searchService
    0	    42	 10188	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (curr_error_logs.txt - private_rummi_game_proj - Visual Studio Code)
|    Folder (private_rummi_game_proj): 36 files
|      File types: js(28) txt(3) md(1) html(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.17
githistory|don|0.6.14
gitlens|eam|11.2.1
file-icons|fil|1.0.28
h5-code|gre|0.0.4
vscode-graphviz|joa|0.0.6
vscode-postgresql|ms-|0.3.0
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
vscode-yaml|red|0.15.0
LiveServer|rit|5.6.1
dot|Ste|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Please try launching it from a Windows command prompt like this:

`code --disable-extensions`

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by gjsjohnmurray** [comment]
See #116736
