### ISSUE TITLE
Latest update deleted 12 MB from my big text file

### ISSUE THREAD

**Issue by burtonsys** [microsoft/vscode#116600]
Issue Type: <b>Bug</b>

Before putting on today's update [February 2021 (version 1.54) Insiders build], my giant "notes" file was about 37 MB (about 520,000 lines of text). After the update it is only about 24 MB, and it is truncated to 348,972 lines of text. The file was open in vscode when I put the update on; I did a Ctrl-S (save) before permitting the update.

My last backup of it was 5 days ago, so I've lost 5 days of notes.

This is the vscode version info (after the update):

```
Version: 1.54.0-insider (system setup)
Commit: 6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197
Date: 2021-02-12T05:13:16.111Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

Vscode still has the (truncated) file open; I've not exited it yet. The only thing I've done to it was try some ctrl-Z and ctrl-Y characters, which seemed to have no effect.

- - - - -

VS Code version: Code - Insiders 1.54.0-insider (6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197, 2021-02-12T05:13:16.111Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2310 CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.37GB free)|
|Process Argv|--crash-reporter-id 53a553af-edc0-4097-ab32-93470875ee2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.54.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963
openwslfolder:30257223

```

</details>

**Comment by burtonsys** [comment]
Google searches found reference to backups kept here:

"%USERPROFILE%\AppData\Roaming\Code - Insiders\Backups\"

But there's nothing there except a 106-byte file called workspaces.json

Does VSCode not keep any backups of the files it is editing?

**Comment by burtonsys** [comment]
BTW, in light of https://github.com/microsoft/vscode/issues/111564 I should mention that I'm not low on disk space.  I have 478 GB of free space on the NTFS-formatted volume which contains my Documents folder (which contains the damaged file).

**Comment by bpasero** [comment]
Sorry to hear you encountered data loss. Was the file dirty when you updated or saved on disk?

**Comment by burtonsys** [comment]
Do you mean when I permitted the update to vscode?  I did a Ctrl-S (save) before permitting the update.

Does VSCode not keep any backups of the files it is editing?

**Comment by bpasero** [comment]
> Does vscode not keep any backups of the files it is editing?

Yeah we do, for as long as the file is not saved. Provided the save succeeded without error, I fear that backup might be gone now. But to check, you can see if there is any content in `"%USERPROFILE%\AppData\Roaming\Code - Insiders\Backups"`, which I think you already tried without luck. 

Otherwise, we are not keeping track of edits, we only keep the contents of a file until it is saved. And given https://github.com/microsoft/vscode/issues/43555 is not addressed yet, we do not support to undo/redo between restarts.

Sorry, all in all I fear there is no way to recover the data. 

One thing I would still be interested in is getting hold of your application logs from VSCode. Quite possible that some error is logged in there. You can zip the entire logs folder and send it to me if you can. 

![image](https://user-images.githubusercontent.com/900690/108588446-84122f80-7359-11eb-9a93-3eb84935f84a.png)

**Comment by burtonsys** [comment]
Sure thing. Where is the "logs folder" and where shall I send it?

(I don't understand what that screenshot is, either.)

BTW, the file in question is a sort of an "activity log" to which I've been appending notes for years. The truncation point was around Sept. 1, 2018, so the missing 12MB represents the last 28 months of notes, and most of had been saved hundreds of times.

**Comment by bpasero** [comment]
@burtonsys that screenshot is from our command palette with access to all our commands, you can trigger it via View > Command Pallette.

As a suggestion to prevent issues like these in the future, if you create a git repository where the notes are (even a local one is fine), you can commit our changes into the local git repository and are safe from data loss as long as you commit often. Of course that would not really help for disk failure (in that case, I would suggest to upload the git repository to a server).

**Comment by burtonsys** [comment]
**1.** Okay, I've created the .zip file, now where shall I send it?  (My contact info is here: https://daveburton.wordpress.com/about/ )

**2.** https://github.com/microsoft/vscode/issues/98063 says (you said), "All our writes in VSCode today operate on the target file: / truncate the file to 0 bytes / write the contents into the file / If a crash happens after truncation, the file will remain empty. This should typically not result in dataloss because **we have a backup to recover from.**"

So **_where_** is the "backup to recover from"?

**3.** Is there a way to inspect the internal undo/redo list, to check whether it contains any large chunks of text?

**4.** The obvious way to avoid risk of data loss when writing files is to **_never truncate the file to zero bytes._**  That's just fundamentally a Very Bad Idea, because it creates a window for catastrophic data loss. Instead, vscode should use one of several alternative approaches:

A. Create a new file with a temporary name, rename/move the old one to a backup, and rename the temporary name to the correct file name. (Safest, and naturally produces backups "for free.")

B. Rename/move the old file to a backup, then create the users file afresh, with the correct name. (Almost as safe, and naturally produces backups "for free.")

C. Overwrite the file, in-place, and after writing the last of it, if it became shorter, truncate it. The advantage of this approach is that it is a trivial change from what vscode is doing currently: all you need to do is to do the "truncate" call at the end of the file write, rather than at the beginning. (It is less safe than A or B, and doesn't automatically create backups, but still greatly reduces the risk of large scale data loss, compared to truncating the file to zero length.)

With approach A or B, for a negligible additional performance penalty, you can also enhance it to keep two or more levels of backups, simply by renaming a previous/old backup to an "older backup" name, before renaming/moving the old version of the file to the backup file path/name.

Can you please change vscode to use one of these approaches?

My preference would be to first switch vscode to use approach C, simply because it is a trivial change, which can be made immediately, and then change to approach A or B with multiple levels of backups, when you get around to it.

Please??

**Comment by bpasero** [comment]
@burtonsys 

1.  my work email is accessible from the https://github.com/bpasero page (bottom left).

2. you already figured out the folder but the backups are deleted once we receive no error from the save operation. I cannot tell what happened in your case, but if saving does not result in an error (as reported by the library we use for file writing), we will go ahead and delete the backup on disk assuming the save was successful.

3. currently not

4. one of the main reasons we stay away from moving files for writing is that it can easily confuse file watchers that observe the project waiting for the user to save a file. it can cause a lot of build tools out there to not work properly if every write results in a move operation, so we sticked with our current approach. we have a [feature request](https://github.com/microsoft/vscode/issues/98063) to optionally enable such a save implementation (aka atomic save).

As for why we first truncate a file to 0: this is simply what node.js does by default for writing to a file (see https://nodejs.org/docs/v12.18.3/api/fs.html#fs_file_system_flags). There does not seem to be support to open a file for writing at position 0, then overwriting what is there in the file and then truncating just the end, but maybe I am wrong?

**Comment by bpasero** [comment]
So the log file revealed this error though it is unclear that this caused the issue to begin with:

```
[2021-02-08 11:57:08.153] [renderer1] [error] [text file model] handleSaveError(60) - exit - resulted in a save error: Error: Unable to write file '<path>.txt' (Error: File Modified Since)
```

What this means is the following:
* the file is being saved through VSCode
* internally we keep track of the last time the file was modified on disk
* if this time is ahead of what we have stored internally, we think the file was modified by someone else
* as such we refuse to save the file and ask the user to manually look at the contents

(this is documented at https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_preventing-dirty-writes)

As long as the file is dirty, a backup should still be there. So I wonder if you can recall what happened next after this error. Did you do the conflict resolution flow as outlined in https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_preventing-dirty-writes ?

**Comment by burtonsys** [comment]
2. Wait, what?  You create a backup copy and then immediately DELETE it?
Please don't do that!!! Please just remove the unlink (file delete) call from your code!
You should not delete the backup until and unless you need to replace it with a new backup. (Not even then, in fact: you really should keep a few levels of backups, so instead of deleting the backup you should just rename the backup to an even older backup.)
It's not just vscode that needs backups, users do, too! Even if vscode doesn't malfunction, there's real value having the previous version of the file around (or, better yet, the last several versions) -- because even if vscode doesn't malfunction, the user (or his computer, or his OS, or his file server) might.

3. Feature request, please!

4. I don't think vscode should compromise the safety of its users' files, to work around someone else's file-watcher bugs.

5. I don't know about Node, but, classically, using streams, to overwrite and then truncate to the proper length:
- You open with "r+" mode to overwrite:  fh = fopen64(filename, "r+")
- If you want the overwrite to begin at somewhere other than the beginning, you fseek64 to the desired file offset; otherwise it will overwrite starting at the beginning of the file.
- When you are done writing, if the file remained the same length or got longer, fclose it, and you're done. If it got shorter then you can truncate to file to the current file position by first obtaining the file length by getting the return value from ftell64 (or from fseek64( ,0L,SEEK_CUR)), and then using ftruncate64() to truncate the file to that length:  ftruncate64(fh, ftell64(fh))

(I guess that, since text files probably never exceed 2GB in length, you could drop the "64"s.)

------------------------------------------

I don't think that the file was opened or modified with anything other than vscode.  (It was 37 MB and over 500K lines long, and the other editor that I mainly use, Notepad++, struggles badly with such large text files.)

I do occasionally (rarely) open it in my antique copy of Clark Mauer's SlickEdit, but I'm pretty sure that it wasn't open in SlickEdit that day.  (BTW, SlickEdit is amazing: a 23½ year old Win32 command-line program which still works perfectly, though it doesn't understand UTF-8.)

What happened is that vscode had been awaiting my permission to apply an update, for a while (probably a day or two). When I was about to walk away from my computer, I thought that would be a good time to do the update, so pressed ctrl-S (to ensure the file was saved), and gave vscode permission to restart to apply the update.

Later I returned to my computer, and worked for a while. The giant log file had been reopened, as I expected. Then I searched the giant log file for a note... and couldn't find it. Then I clicked in the body of the text,* did ctrl-End to seek to the end, and realized that the text which should have been at the end wasn't there. I did a couple of page-ups, and realized I was looking at text that was well over a year old. (This file grows at the end, as I add notes to it.) Then I checked the file size, and it was only about 24 MB long, compared the the backup copy five days earlier which was nearly 37 MB long.

No error message was displayed at any point (not that I noticed, anyhow).


(*BTW, it has long been a very minor annoyance that in vscode ctrl-End won't work unless you first click somewhere in the body of the text file.)

**Comment by bpasero** [comment]
@burtonsys 

2. I get the idea and we have a highly upvoted feature request for it (https://github.com/microsoft/vscode/issues/26339). I would argue that this should be a dedicated feature outside of the area of backups that keeps track of changes to files for a couple of revisions. I would not want to tie this how backups work today because that is very specific to handling dirty files and allowing to close VSCode without asking to save (aka "hot exit").

3. please file it if you feel this is needed

4. as you can see, this is a personal opinion and for that exact reason we have https://github.com/microsoft/vscode/issues/98063 to put this behind a setting so that the user has the choice. I still think that with a solution such as https://github.com/microsoft/vscode/issues/26339 we could avoid having to do atomic saves by giving the user some UI to restore previous states

5. yeap you are right, I forgot about `r+` and it is supported in node.js too. what is the user experience though in case something goes wrong? Especially in the light of encodings that are multi-byte you really might end up with a corrupt file? I think again, https://github.com/microsoft/vscode/issues/26339 seems like the golden solution to this issue, wouldn't you agree?

---

> What happened is that vscode had been awaiting my permission to apply an update, for a while (probably a day or two). When I was about to walk away from my computer, I thought that would be a good time to do the update, so pressed ctrl-S (to ensure the file was saved), and gave vscode permission to restart to apply the update.

That is good information, thanks. Do you recall if when you hit Ctrl+S the file was dirty or was it saved?

> (*BTW, it has long been a very minor annoyance that in vscode ctrl-End won't work unless you first click somewhere in the body of the text file.)

You can report this as new issue.

**Comment by burtonsys** [comment]
2. Re: _"we have a highly upvoted feature request for it (#26339)."_  Is "upvote" a synonym of "star". (If so I've added my upvote to the 111,406.)

2&4. If your existing backups are something more complex than just a copy of the previous version of the file, then I agree that a different mechanism for maintaining users' backups would be more appropriate. Implementing 4(A) or 4(B) would do it, with little effort.

#98063 says, _"We closed this issue because we don't plan to address it in the foreseeable future."_  (Atomic saves is different from keeping backups, anyhow.)

It surprises me that any file-watcher would be confused by a rename/replace approach to updating files, because many, many programs do it that way. Do you have a particular problematic file-watcher in mind, or is it a hypothetical issue?

5. For 4(C) (overwrite without first truncating to zero-length) the user experience, in the event of a crash in the midst of the file save is a file for which the first part is from the new version and the last part is from the old version. That's bad, but it's not nearly as bad as a file for which the first part is from the new version and the last part is completely _GONE_ (the current way it works).

It might improve performance a bit, too, since most or all of the file will already be allocated, but with today's fast machines that's not very important.

I wouldn't worry two much about broken UTF-8 multibyte sequences. Everything (including vscode) does something reasonable with them.

If "dirty" doesn't mean "unsaved" then I don't know what it means.  I pressed ctrl+S to ensure that the file was saved.

I probably didn't even bother to look for the asterisk indicator.  There's a good chance that the file was already saved, when I pressed ctrl+S, but pressing ctrl+S should have ensured that it was.

Pressing Ctrl+S frequently is a longstanding habit, born of bitter experience. I press it **_a lot,_** not just in vscode, but in any program that supports it. I am, after all, [a follower of Jesus](http://www.kaitaia.com/jokes/Religious%20Jokes/Religious_Jokes43.htm).

**Comment by bpasero** [comment]
> If your existing backups are something more complex than just a copy of the previous version of the file

They are more than just a copy, carrying a bit of metadata as well. But I don't think they are currently suited to build anything like the local timeline history. That doesn't mean we cannot turn it into supporting that scenario, I am all up for it. Let's keep that specific discussion in the feature request. 

> It surprises me that any file-watcher would be confused by a rename/replace approach to updating files, because many, many programs do it that way. Do you have a particular problematic file-watcher in mind, or is it a hypothetical issue?

Well, I don't have an example directly, but it is true that for a file watcher seeing a file delete first and then being recreated might not be the expected thing to happen when a file get's simply written to. I find the SO https://stackoverflow.com/questions/20634684/what-is-sublime-text-doing-when-i-save-a-file quite interesting in that regard which discusses this for Sublime text. It is worth mentioning that for a long time, Sublime Text's atomic save setting is now `false` and not `true` anymore. The exact reasoning could be related to the issues encountered around atomic saves. 

> I probably didn't even bother to look for the asterisk indicator. There's a good chance that the file was already saved, when I pressed ctrl+S, but pressing ctrl+S should have ensured that it was.

I start to see what was possibly happening:
* the file was indeed saved on disk, and not dirty (i.e. no asterisk visible)
* you saved the file before applying the update which for VSCode means, the entire contents of the editor are saved to disk
* this operation was proceeding while you applied the update for VSCode
* we currently (I believe) have no way of awaiting pending file operations before quitting which means there is a small chance that the file is being written to while the process goes down

I will have further look to see if my theory holds true.

**Comment by bpasero** [comment]
I have a reproducible dataloss case with the following steps:
* open attached zip file in the editor
* observe the number of lines and file size
* very very quickly press `Cmd+S` followed by `Cmd+Q` (you can press and hold `Cmd` key to speed things up)
* reopen VSCode
* verify the file is still the same size and has the same amount of lines

Rationale: the fix is to await any pending save on shutdown to ensure the contents have been written to disk. 

[file.txt.zip](https://github.com/microsoft/vscode/files/6022635/file.txt.zip)

**Comment by burtonsys** [comment]
Well done!!

I had always assumed that Ctrl+S is a no-op if the file's already saved. Apparently not in vscode! Could that be made to happen, please?

Thanks also for the link to the interesting Sublime Text SO discussion.

**Comment by bpasero** [comment]
@burtonsys yes that is possible via keybindings configuration and `when` clauses:

```json
{
    "key": "cmd+s",
    "command": "workbench.action.files.save",
    "when": "activeEditorIsDirty"
},
{
    "key": "cmd+s",
    "command": "-workbench.action.files.save"
}
```

There is a specific reason why we allow `Cmd+S` to write the contents of the editor to disk because it can often help to trigger a file watcher that is watching the project. This gives a developer an easy way to force a write to the file even when the file is not dirty.
