### ISSUE TITLE
Save button not dimmed when all the files are saved

### ISSUE THREAD

**Issue by Anzlim** [microsoft/vscode#116672]
- VS Code Version: 1.53.2
- OS Version: Ubuntu 20.04.1 LTS

Steps to Reproduce:

1. Start editing any file in the editor then click save 
2. if all the files are saved still the save btn is not dimmed

Does this issue occur when all extensions are disabled?: Yes/No - no

**Comment by gjsjohnmurray** [comment]
Is this the button you mean?
![image](https://user-images.githubusercontent.com/6726799/107933849-32436100-6f77-11eb-898a-01632138f9e8.png)

**Comment by Anzlim** [comment]
yes

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/116689
