### ISSUE TITLE
constructor.js

### ISSUE THREAD

**Issue by VSolodkiy** [microsoft/vscode#116678]
Issue Type: <b>Bug</b>

Hello,
As soon as I run the debugger on a .js file and it hits a line item that has a console.log, a "constructor.js" file is opened with a ton of code I don't recognize. My original .js file remains open. If I switch back to my file and click the "step into" button on the debugger, it goes back to this "constructor.js" fie. The debugger will not move past the console.log without opening this file. And the debugger will not move past the console.log line item.

I can't get out of this loop and I can't use my debugger.
VS Code version: 1.53.2
OS version: Windows_NT x64 6.1.7601

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.91GB (3.03GB free)|
|Process Argv|--crash-reporter-id 35e50c05-6cd8-4c81-8536-847800eb71f2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vscode-language-pack-ru|MS-|1.53.2
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

https://user-images.githubusercontent.com/31922553/107929008-b864a500-6f81-11eb-9c16-3ba85641f599.mp4

**Comment by weinand** [comment]
If you don't want to "step into" the console.log function, then please don't use the "Step Into" button.
Use the "Step Over" button instead.

And if you need to step "out of" a function like constructor.js, then use the "Step Out" button.
