### ISSUE TITLE
MongoDB language icon.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [microsoft/vscode#116640]
MongoDB files are missing their icons. The classic "mongo leaf " icon would be cool!

In Image: no icon for MongoDB like the  JS icon on the right.
![Capture](https://user-images.githubusercontent.com/25576658/107877948-7aba3a80-6ef5-11eb-9544-9ce6af0920d1.PNG)

Thanks

**Comment by gjsjohnmurray** [comment]
To make this happen in VS Code I think the icon and file extension association needs to be added at https://github.com/jesseweed/seti-ui

**Comment by ShubhamVerma1811** [comment]
Oh, I get it. So VSCode relies on that library.
In that case, it's up to the maintainer to close this issue or keep it open until we get the icon.
