### ISSUE TITLE
intellisence does not correctly infer the optional parameter when using typescript syntax

### ISSUE THREAD

**Issue by yungitsettings** [microsoft/vscode#116635]
<h3>case 1</h3>
<pre><code>/** @type {(param1: string, param2?: boolean) => boolean} */
const func1 = function(param1, param2) {}
//intellisense hinting "param2?: boolean"
</code></pre>
<h3>case 2</h3>
<pre><code>/** @type {(param1: string, param2?: boolean) => boolean} */
function func2(param1, param2) {}
//intellisense hinting "param2: boolean"
</code></pre>

![report](https://user-images.githubusercontent.com/78241681/107869439-079acf00-6ec9-11eb-8b8c-b718913487b7.png)

**Comment by mjbvz** [comment]
Try enabling strict null checks
