### ISSUE TITLE
Weird behavior in terminal and mimimap after switching users in linux 

### ISSUE THREAD

**Issue by Mohammad-Mohsen** [microsoft/vscode#116620]
Issue Type: <b>Bug</b>

After I switch accounts in linux, VS Code is distorted (I don't know if it's a appropriate adjective) in minimap and terminal asin the screenshot below
![image](https://user-images.githubusercontent.com/52295823/107854078-cc4bc200-6e2e-11eb-926e-4089f7ee7f81.png)
after I reload window, the problem will gone until I switch users again
this problem was not in 1.52, it's new in 1.53 and remained in 1.53.2

EDIT: I found Weird behavior in terminal and mimimap is better to describe the problem

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3118)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id ee917ed4-d999-4afd-88f7-b6d7cf301a49|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.3.0
better-toml|bun|0.3.2
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
rails-snippets|Hri|1.0.8
kite|kit|0.138.0
nim|kos|0.6.6
MagicPython|mag|1.1.0
file-downloader|min|1.0.9
vscode-docker|ms-|1.9.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
azure-account|ms-|0.9.6
cpptools|ms-|1.2.0
hexeditor|ms-|1.4.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
quicktype|qui|12.0.46
ruby|reb|0.28.1
vscode-yaml|red|0.15.0
rust|rus|0.7.8
crates|ser|0.5.5
rust-pack|Swe|0.2.29
vscodeintellicode|Vis|1.2.11
vscode-arduino|vsc|0.3.4
snippet|vsc|0.8.1
jinja|who|0.0.8
vscode-ruby|win|0.28.0
licenser|ymo|1.5.0
material-theme|zhu|3.9.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by 20080** [comment]
This happens when my laptop wakes up from sleep.
