### ISSUE TITLE
When I switch Desktop with VSCode fullscreen (swipes four-finger), it has a short delay before displaying the code

### ISSUE THREAD

**Issue by khoilr** [microsoft/vscode#116608]
Issue Type: <b>Bug</b>

It only happens when I use fullscreen mode of VSCode, whenerver I switch Desktop using four-finger or Ctrl + Windows + Arrow, it has a color screen based on theme duration before displaying my code. But it is totally fine in normal mode

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by bpasero** [comment]
Do you recall if this happened in previous versions too?

**Comment by khoilr** [comment]
> Do you recall if this happened in previous versions too?

No. But it happens in the same way with VSCode Insider previous version

**Comment by deepak1556** [comment]
Does it happen when you start the app with `code --disable-features=CalculateNativeWinOcclusion` ?

**Comment by khoilr** [comment]
> Does it happen when you start the app with `code --disable-features=CalculateNativeWinOcclusion` ?

I got this message when I try to do what you told `Ignoring option disable-features: not supported for code.`

**Comment by deepak1556** [comment]
Can you check if this issue persists with latest insiders https://code.visualstudio.com/insiders ?

**Comment by khoilr** [comment]
> Can you check if this issue persists with latest insiders https://code.visualstudio.com/insiders ?

This issue is fixed in lastest VSCode Insiders

**Comment by deepak1556** [comment]
Thanks for checking, merging to https://github.com/microsoft/vscode/issues/114459. Will be fixed in version `1.54`
