### ISSUE TITLE
Clear terminal before launching another debuggee in terminal

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#116699]
In VS Code the DAP `runInTerminal` request tries to launch a new debug session in the same integrated terminal if the previous session has finished. A consequence of this approach is that the previous commands and output will remain visible in the integrated terminal which is confusing for some users.

This request asks for introducing a setting to automatically clear the integrated terminal before starting a new debug session.

@testforstephen this feature request is a replacement for your [DAP feature](https://github.com/microsoft/debug-adapter-protocol/issues/165) request.

**Comment by weinand** [comment]
Please provide more information by following this link:
https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by testforstephen** [comment]
@weinand thanks. I tried in latest insider (2021-03-22) in macOS, overall it looks good. Just a minor concern about the clear behavior.

By default, launch a new debug session will auto keep the new terminal command at the beginning of my viewport.

https://user-images.githubusercontent.com/14052197/111963344-5c67e000-8b2e-11eb-8f97-70f5d2be28a5.mov

But if i have scrolled the terminal manually, then launch in terminal won't clear the terminal and scroll to the latest terminal line.

https://user-images.githubusercontent.com/14052197/111963946-0e071100-8b2f-11eb-82cf-d89ee8a4d9fd.mov

**Comment by weinand** [comment]
@testforstephen thanks for testing.
Strange, scrolling should not have an effect because clearing the terminal is done by running the "clear" command in the terminal.
