### ISSUE TITLE
taking toooooooooo much time to compile a 20 line code

### ISSUE THREAD

**Issue by manishrnl** [microsoft/vscode#116641]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

i had written a 20 line code in visual studio code and it takes much time to compile.i had waited for half an hour but  i didnt get any output.I dont know when will this run succesfully .I get this compiling duration delay  on nearly every programme i run on it. If the problem persist then i'll had to switch to my earlier software i.e.., CODE  BLOCK

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz (4 x 3191)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.93GB (5.16GB free)|
|Process Argv|--crash-reporter-id 0a0147a5-1d1a-4d17-aea2-bb7d51deb5ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
csharp|ms-|1.23.9
cpptools|ms-|1.2.0
java|red|0.75.0
swdc-vscode|sof|2.4.9
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by joe733** [comment]
Hi, is it possible to post the source code, build tools/logs, please. It'll help others debug the issue.

**Comment by manishrnl** [comment]
Could you Please tell me which extension should i install so that system
doesn't take much time to compile even a larger file.

**Comment by manishrnl** [comment]
I didnt get what you said.
Explain me properly and please name the extension i ought to download

**Comment by manishrnl** [comment]
Hi
I just found that scanf() is not working .
Whenever i use scanf() function then compiler didnt finished compiling not
even hours later. Could you now describe why this error occurs or any
extension i should download.

**Comment by joe733** [comment]
Hi @manishrnl, your issue seems to be with your code not vscode nor any extension. Please try to compile the program from terminal. Such problems are best addressed @ stackoverflow.com/questions

Eg: 
- https://stackoverflow.com/questions/65662791/using-scanf-in-vscode-c-language
- https://stackoverflow.com/questions/3302255/c-scanf-vs-gets-vs-fgets

**Comment by manishrnl** [comment]
# i n c l u d e < s t d i o . h >
 s t r u c t   p e r s o n a l
 {
         c h a r   n a m e [ 2 0 ] ;
         i n t   d a y ;
         c h a r   m o n t h [ 1 5 ] ;
         i n t   y e a r ;
         d o u b l e   s a l a r y ;
 } ;
 v o i d   m a i n ( )
 {
 s t r u c t   p e r s o n a l   p e r s o n ;
 p r i n t f ( " I n p u t   v a l u e s   i n   o r d e r   p e r s o n s
  n a m e , p e r s o n . d a y , p e r s o n . m o n t h , p e r s o n . y
e a r , & p e r s o n . s a l a r y   \ n " ) ;
 s c a n f ( " % s   % d   % s   % d   % d   " , p e r s o n . n a m e , &
p e r s o n . d a y , p e r s o n . m o n t h , & p e r s o n . y e a r , &
p e r s o n . s a l a r y ) ;
 p r i n t f ( " e n t e r e d   v a l u e s   a r e   " ) ;
 p r i n t f ( " \ n N a m e   = % s \ n D a t e = % d \ n M o n t h = % s
\ n Y e a r = % d \ n S a l a r y = % d \ n   " , p e r s o n . n a m e , p
e r s o n . d a y , p e r s o n . m o n t h , p e r s o n . y e a r , p e r
s o n . s a l a r y ) ;
 }

 [ R u n n i n g ]   c d   " d : \ c + +   o u t p u t \ v s c o d e \ "
& &   g c c   s t r u c t c o m p l e x . c   - o   s t r u c t c o m p l e
x   & &   " d : \ c + +   o u t p u t \ v s c o d e \ " s t r u c t c o m p
l e x

 [ D o n e ]   e x i t e d   w i t h   c o d e = 1   i n   1 8 . 9 8   s e
c o n d s

 [ R u n n i n g ]   c d   " d : \ c + +   o u t p u t \ v s c o d e \ "
& &   g c c   s t r u c t c o m p l e x . c   - o   s t r u c t c o m p l e
x   & &   " d : \ c + +   o u t p u t \ v s c o d e \ " s t r u c t c o m p
l e x

 [ D o n e ]   e x i t e d   w i t h   c o d e = 1   i n   8 . 5 9 2   s e
c o n d s

 [ R u n n i n g ]   c d   " d : \ c + +   o u t p u t \ v s c o d e \ "
& &   g c c   s t r u c t c o m p l e x . c   - o   s t r u c t c o m p l e
x   & &   " d : \ c + +   o u t p u t \ v s c o d e \ " s t r u c t c o m p
l e x

 [ D o n e ]   e x i t e d   w i t h   c o d e = 1   i n   1 2 . 9 8 5   s
e c o n d s

 [ R u n n i n g ]   c d   " d : \ c + +   o u t p u t \ v s c o d e \ "
& &   g c c   s t r u c t c o m p l e x . c   - o   s t r u c t c o m p l e
x   & &   " d : \ c + +   o u t p u t \ v s c o d e \ " s t r u c t c o m p
l e x




 S a m e   c o d e   h a v e   b e e n   c o m p i l e d   i n   c o d e
 b l o c k   a n d   v s   c o d e   s i m u l t a n e o u s l y   a n d
 t h e   t e r m i n a l   w i n d o w   f o r   b o t h   h a v e   b e e
n   a t t a c h e d   w i t h   t h i s   m a i l .

 A l s o   n o t e   t h a t   I   h a d   t o   m a n u a l l y   s t o p
 t h e   p r o g r a m m e   e x e c u t i o n   i n   c o d e   b l o c k
 o r   e l s e   i t   w i l l   n e v e r   s t o p   ( f a l s e )   c o
m p i l i n g   m o r e     a p p r o p r i a t e l y   . a l l   m y   s o
f t w a r e   a r e   u p   t o   d a t e .

 S e n t   f r o m   M a i l   f o r   W i n d o w s   1 0

 F r o m :   J o v i a l   J o e   J a y a r s o n
 S e n t :   S u n d a y ,   F e b r u a r y   1 4 ,   2 0 2 1   6 : 5 9
 P M
 T o :   m i c r o s o f t / v s c o d e
 C c :   m a n i s h r n l ;   A u t h o r
 S u b j e c t :   R e :   [ m i c r o s o f t / v s c o d e ]   t a k i n
g   t o o o o o o o o o o   m u c h   t i m e   t o   c o m p i l e   a   2
0   l i n e   c o d e   ( # 1 1 6 6 4 1 )

 H i ,   i s   i t   p o s s i b l e   t o   p o s t   t h e   s o u r c e
 c o d e ,   b u i l d   t o o l s / l o g s ,   p l e a s e .   I t ' l l
 h e l p   o t h e r s   d e b u g   t h e   i s s u e .

 Y o u   a r e   r e c e i v i n g   t h i s   b e c a u s e   y o u   a u
t h o r e d   t h e   t h r e a d .
 R e p l y   t o   t h i s   e m a i l   d i r e c t l y ,   v i e w   i t
 o n   G i t H u b ,   o r   u n s u b s c r i b e .
