### ISSUE TITLE
The TypeScript language service

### ISSUE THREAD

**Issue by hectordufau** [microsoft/vscode#116626]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:56:04.185Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2499)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.67GB (1.10GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 1b537b3a-91ce-43c2-b5ba-8af5323faba1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
android-dev-ext|ade|1.3.2
laravel-extra-intellisense|ami|0.4.1
All-Autocomplete|Ati|0.0.23
vscode-intelephense-client|bme|1.6.3
phpserver|bra|3.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
laravel-goto-view|cod|1.3.4
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.38.0
vscode-eslint|dba|2.1.14
emulate|Die|1.4.0
es7-react-js-snippets|dsz|3.1.0
brackethighlighter|Dur|2.2.3
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.15
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
font-switcher|eva|3.1.0
php-debug|fel|1.14.9
vscode-firefox-debug|fir|2.9.1
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.23.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
search-node-modules|jas|1.3.0
vscode-nuget-package-manager|jmr|1.1.6
rn-full-pack|kel|0.7.0
edge|luo|0.3.2
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.3
ecdc|mit|1.4.0
cpptools|ms-|1.2.0
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
mq4|ner|1.0.4
mql-extension-pack|nic|0.0.4
mql-over-cpp|nic|0.0.3
mql-snippets|nic|0.1.2
vetur|oct|0.32.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.11.0
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.5.0
laravel-artisan|rya|0.0.27
code-settings-sync|Sha|3.4.3
profitrobots-mq5-snippets|sib|1.4.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4
material-theme|zhu|3.9.13

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Please start by updating to 1.53.2 and testing again
