### ISSUE TITLE
Problem with some Korean characters input

### ISSUE THREAD

**Issue by starlinq** [microsoft/vscode#116697]
- VS Code Version: 1.53.2
- OS Version: Ubuntu 20.04 LTS, Linux x64 5.8.0-34-generic

Steps to Reproduce:

1. Type a Korean word, for example "간식을" (correct)
2. The actual typed word is "가ㄴ식을" (incorrect)

Please see the attached video:

https://user-images.githubusercontent.com/2492702/107957809-80427e00-6fe4-11eb-8345-98ce3ea9f7d9.mp4

The [issue #114017](https://github.com/microsoft/vscode/issues/114017) is not reproduced.

Does this issue occur when all extensions are disabled?: Yes

**Comment by starlinq** [comment]
I think that two recently submitted issues show the same problem:

[#118788](https://github.com/microsoft/vscode/issues/118788)

[#118365](https://github.com/microsoft/vscode/issues/118365)

**Comment by bluedskim** [comment]
hi starlinq
You are right, exactly.

**Comment by alexdima** [comment]
@starlinq We believe this might be a problem with the default `"editor.fontFamily"`, called `Droid Sans Mono`. Does the issue reproduce when installing Fira Code and configuring `"editor.fontFamily": "Fira Code"` ?

**Comment by bluedskim** [comment]
> @starlinq We believe this might be a problem with the default `"editor.fontFamily"`, called `Droid Sans Mono`. Does the issue reproduce when installing Fira Code and configuring `"editor.fontFamily": "Fira Code"` ?

@alexdima 
I've installed `fonts-firacode` on my Ubuntu 20.04.
My `"editor.fontFamily"`  was `'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'`.
I've removed two Droid fonts, added Fira Code.
Now, my `"editor.fontFamily"` is `'Fira Code', 'monospace', monospace`.
The problem has gone. Wonderful!
