### ISSUE TITLE
Extension host terminated unexpectedly -- clean install, latest version

### ISSUE THREAD

**Issue by yasmin-bb** [microsoft/vscode#116629]
Extension host terminated unexpectedly.

This started happening with the most recent version.  To confirm, I deleted my VS Code application, deleted my .vscode directory, redownloaded the app from the VS Code site, enabled only the SFTP extension and tried to sync with the remote site using the sftp.json that I've been using successfully for weeks.  The extensions host crashed with the message above.  Log message below:

console.ts:137 [Extension Host] (node:68504) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
b @ console.ts:137
abstractExtensionService.ts:466 Extension host terminated unexpectedly. Code:  null  Signal:  SIGSEGV
_onExtensionHostCrashed @ abstractExtensionService.ts:466
log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.configuration-editing, vscode.extension-editing, vscode.json-language-features, ms-vscode.js-debug, vscode.npm, vscode.debug-auto-launch, vscode.git, liximomo.sftp, vscode.github-authentication, vscode.github, vscode.emmet, vscode.merge-conflict, vscode.testing-editor-contributions
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:40

**Comment by tamuratak** [comment]
Duplicate of liximomo/vscode-sftp/issues/883.

**Comment by oberocks** [comment]
> /causedByExtension - thanks @tamuratak

@gjsjohnmurray it's not caused by the extension(s), but rather a VS Code update (of late) has caused ALL of the extension crashes (plural) that us devs are actually using to sync to servers via FTP/SFTP/SSL etc.

**Comment by gjsjohnmurray** [comment]
@oberocks there can be many causes for an extension no longer working when VS Code updates to a new version. In my experience as an extension developer, the VS Code team works very hard not to make changes that break published APIs and features. But if an extension is no longer maintained by its author there's always a chance it will stop working at some point. Options include:

- Fork the extension and fix it.
- Switch to another extension.

Some extensions seem to end up abandoned because others show up and become very popular. Are you familiar with the remote development options described in https://code.visualstudio.com/docs/remote/remote-overview ?

**Comment by cmparrela** [comment]
Look that solution

https://github.com/liximomo/vscode-sftp/issues/883#issuecomment-778684682

**Comment by DannyCrews** [comment]
bs. This is broken. Take responsibility and fix it.

**Comment by gjsjohnmurray** [comment]
See #116260

Electron update in today's Insiders is supposed to fix this.

**Comment by oberocks** [comment]
@gjsjohnmurray Understood, and many thanks for the suggestion of remote-overview. I had not yet seen that option, which is great, especially considering the rather old-school way of working synced to a FTP - isn't always a fully supported thing.

So, my apologies if I came off as un-empathetic. That's not the case. My concern was just to flag the issue, as in time the OS world would work it's magic - hopefully allowing me to get back to updating VS Code whenever possible and still being able to use our collectively treasured old-school extensions from other underappreciated coders of the ether.

However, please do consider this comment as **a plea for VS Code to just add in FTP client functionality with live watchers**. It's a really great way to work in some fringe cases. In my case, I make web design systems that are integrated with static site generators - resulting in a ton of files generated and needing to be pushed to a live server to check for responsive and accessibility factors. Old-school FTP methods are by far the most direct way to do this sort of cross-device focused work IMO. I'm pretty sure I'm not the only one that has to work this way these days, but can't confirm that per say lol.

Anyhow, thank you kindly for the update about the electron patch as well. Hopefully I can find time to try out a recent VSC version (but still have the old version that's stable for this extension handy).
