### ISSUE TITLE
Bogous highlights with filterText 

### ISSUE THREAD

**Issue by vainamov** [microsoft/vscode#116683]
![grafik](https://user-images.githubusercontent.com/11841072/107933957-ba2d6900-6f7f-11eb-85a2-4a2beeffc248.png)

The same issue as in https://github.com/microsoft/vscode/issues/115250 reoccurred to me in the latest insiders release, however only in situations where the symbol I'm trying to query fields from is ~~the direct result of a function~~.

**Correction**: It occurs when the result of the function is a Promise and IntelliSense provides the fields of the underlying unpromised type whenever I directly reference the unpromised value. VS Code allows this and manually adds the await statement and paranthesis on auto-complete. See the example for a better explanation:

```ts
nonAsyncFunction().| // <- Correct highlighting

asyncFunction().th| // <- Correct highlighting for direct members of Promise like then or catch

(await asyncFunction()).| // <- Correct highlighting

asyncFunction().| // <- Incorrect highlighting for everything that is a member of the promised type instead of Promise itself
```

Version: 1.54.0-insider (system setup)
Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
Datum: 2021-02-15T05:17:48.792Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
Betriebssystem: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a TypeScript project
2. Write an async function and reference the direct result without `await` and paranthesis. Then type the . character and start typing

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share a complete, self contained code example that demonstrates this

**Comment by vainamov** [comment]
I've attached an example for you to check out @mjbvz 
[highlight-issue.zip](https://github.com/microsoft/vscode/files/5994580/highlight-issue.zip)

**Comment by mjbvz** [comment]
Self contained example for reference:

```ts
async function foo() {
    fetch().
}
```

**Comment by jrieken** [comment]
Oh, I see... This uses a filter text and with that we don't have a guarantee for good UI highlights... We simply highlight anything from the prefix that matches the label... That's the infamous `anyScore`-function... Maybe we should simply not do that anymore

<img width="708" alt="Screenshot 2021-02-17 at 17 58 08" src="https://user-images.githubusercontent.com/1794099/108238957-b6e5d900-7149-11eb-9fc8-20bcc13fbb5d.png">

**Comment by jrieken** [comment]
I have pushed changes that makes this nicer but this is just a heuristic. Some completions define a filter text and when ranking them against a prefix we use that filter text. That answers the question whether a completion matches or not but it does give us highlight (because filter text is different from the rendered label). So, computing highlight is still "magic" but I hope the magic is now better. The new approach will repeatedly run fuzzyScore on the label and the prefix where it always skips more of the prefix start
