### ISSUE TITLE
Font Realizability

### ISSUE THREAD

**Issue by Satwik29** [microsoft/vscode#116617]
Another feature I would love to have is instant font resizing. By using the Ctrl+Scroll, we can resize the font to our needs. I would love something like this so I can fine-tune the font size to my needs

**Comment by AnsonH** [comment]
VS Code already has this feature. Try adding this property into your `settings.json`:
```json
"editor.mouseWheelZoom": true
```

Alternatively, open settings using <kbd>Ctrl</kbd>+<kbd>,</kbd> and search for "Editor: Mouse Wheel Zoom". Then, tick the checkbox to enable it. Now you can resize the font with Ctrl+Scroll :)

**Comment by Satwik29** [comment]
Thanks!!....didn't know about this feature

**Comment by AnsonH** [comment]
Great to help! You can close this issue now
