### ISSUE TITLE
Implementing abstract class via quick fix yields compile errors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116606]
Steps to Reproduce:

1. create a new file `storageMainService2.ts`
2. type `export class StorageMainService2 extends AbstractStorageService {}`
3. use quick fix to implement abstract methods

=> 🐛 you see compile errors from the result

![image](https://user-images.githubusercontent.com/900690/107844790-d7730380-6dd6-11eb-8720-273dd1bf84df.png)

**Comment by shskwmt** [comment]
Missing return type for last method.

![image](https://user-images.githubusercontent.com/17052177/107869450-7e3bca80-6ed1-11eb-88d6-b9602b78683c.png)

**Comment by mjbvz** [comment]
@bpasero I can't reproduce using those steps.

Starting with:

```ts
import { AbstractStorageService } from 'vs/platform/storage/common/storage';

export class StorageMainService2 extends AbstractStorageService { }
```

Implement abstract results in :

```ts
import { IStorage } from 'vs/base/parts/storage/common/storage';
import { AbstractStorageService, StorageScope } from 'vs/platform/storage/common/storage';
import { IWorkspaceInitializationPayload } from 'vs/platform/workspaces/common/workspaces';

export class StorageMainService2 extends AbstractStorageService {
	protected getStorage(scope: StorageScope): IStorage | undefined {
		throw new Error('Method not implemented.');
	}
	protected getLogDetails(scope: StorageScope): string | undefined {
		throw new Error('Method not implemented.');
	}
	migrate(toWorkspace: IWorkspaceInitializationPayload): Promise<void> {
		throw new Error('Method not implemented.');
	}
}
```

Can you test this again and make sure you are on the latest TS version: 4.2.0-insiders-20210210

**Comment by bpasero** [comment]
@mjbvz steps:
* `git co 1.53.0`
* open `src/vs/platform/storage/node/storageService.ts`
* type `export class Foo extends AbstractStorageService {}` at the top
* use quick fix to implement methods

**Comment by mjbvz** [comment]
Thanks. Opened https://github.com/microsoft/TypeScript/issues/42833 to track upstream
