### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by chhabra-consultants** [microsoft/vscode#116609]
Issue Type: <b>Feature Request</b>

My visual code studios live server is not funtioning properly i need help regarding the same

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
/causedByExtension

This functionality provided by an extension and should be reported in its repo
