### ISSUE TITLE
Centos 7 not supported by terminal - CXXABI version

### ISSUE THREAD

**Issue by mintyc** [microsoft/vscode#116662]
VS Code's Terminal appears to require libstdc++ v6.0.20 or newer (gcc 4.9.x) but Centos 7 libstdc++ supplies 6.0.19 without the CXXABI version required.

Is there a workaround? Cannot find a way to update Centos 7 version of libstdc++

Using latest vscode and latest centos 7

**Comment by gjsjohnmurray** [comment]
/duplicate and CXXABI is a good term to search open issues with.
