### ISSUE TITLE
When i edit an png outside vscode , it will not change if i refresh

### ISSUE THREAD

**Issue by fallenwood** [Microsoft/vscode#11661]
- VSCode Version: 1.4.0
- OS Version: Windows10 RS1

Steps to Reproduce:

1.  open a image(*.png) inside a workspace in vscode
2.  edit the file with any tool( i am sure i saved)
3.  close the image on the side bar but not vscode, reopen it, the image will not change even though i have changed it

I think this is because vscode automatically cached the static image, i wonder if it is a bug or a feature. Thanks

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7951
