### ISSUE TITLE
Keyboard navigation broken in Output/Terminal select box

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116693]
1. Open Terminal
2. Open select box from that view
3. Press <kbd>DownArrow</kbd>

🐛 Select box closes

![image](https://user-images.githubusercontent.com/22350/107953853-8d159200-6f50-11eb-93c5-f77d354f4381.png)

**Comment by isidorn** [comment]
Ah yes, this is our custom select box which we only use on Linux and Windows and thus the reason why I did not hit this problem.
I have pushed a fix for this. I think it should be good, even though I do not like changing the custom select box code.
