### ISSUE TITLE
Launch.json intellsense doesn't include the envFile option

### ISSUE THREAD

**Issue by SteveALee** [microsoft/vscode#116654]
Issue Type: <b>Bug</b>

I'm using the "envFile" option in my launch config but it gets a yellow squiggle and "Property is not allowed". It works perfectly.

    {
      "name": "sync script",
      "type": "php",
      "request": "launch",
      "envFile": "${workspaceRoot}/.env",
      "program": "${workspaceFolder}/sync/sync.php",
      "cwd": "${workspaceFolder}/sync",
      "port": 9003
    }

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.30GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/wsl/mu/payment-tracking --remote=wsl+Ubuntu-20.04 --crash-reporter-id bd700e0f-5dc0-4848-b4bd-a865e14d0b8d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1991)|
|Memory (System)|12.37GB (10.84GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
bracket-pair-colorizer|Coe|1.0.61
vscode-edge-devtools|ms-|1.1.3
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
debugger-for-edge|msj|1.0.15
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.5.0
better-toml|bun|0.3.2
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
nunjucks-template|ese|0.3.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-versionlens|pfl|1.0.9
code-spell-checker|str|1.10.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt600cf:30251589

```

</details>

**Comment by SteveALee** [comment]
Note many of the extensions listed above are disabled for the workspace. You might want to add and 'enable' column?

**Comment by weinand** [comment]
VS Code knows nothing about "envFile". Support for this is provided by some debug extensions.
Please file issues against php extension.

**Comment by SteveALee** [comment]
OK, so extensions have to update the intellisense?

**Comment by weinand** [comment]
yes, if an extension introduces a new property like "envFile", then the extension has to introduce the JSON-schema for the property. Based on that schema VS Code will perform the verification (yellow squiggle) and provide the intellisense.
