### ISSUE TITLE
Closing Webview when stopped on breakpoint breaks next instance

### ISSUE THREAD

**Issue by mheuzey** [microsoft/vscode#116666]
If a webview is closed while being stopped at a breakpoint (on the chrome side), the next time the webview opens it will be non-interactable, as if still stopped at the breakpoint. Reopening the webview developer tools releases the hold, so there is a workaround, but it is a nuisance. I often do some coding while stopped at breakpoints, and close and reopen the webview so it has the latest script. Occurs in the latest insiders as well.

Version: 1.54.0-insider (user setup)
Commit: 6ac9a3ecb3698e82bf901f11bbb5940f6bc3c197
Date: 2021-02-12T05:13:16.111Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Download the VS Code extension samples: (https://github.com/microsoft/vscode-extension-samples.git)
2. Modify the html in the cat coding webview sample to have a <textarea> (to see if you can interact with the webview)
3. Run the cat coding webview. Type in the textarea with no problem
4. Open the Webview Developer Tools, navigate to the script, and put a breakpoint on the line that posts a message to VS Code (should be line 22)
5. When the breakpoint is hit, close the webview tab, and reopen the webview
6. Notice that you cannot interact with the webview (also, notice that the cursor icon oftens stays what it was when it entered the webview, such as a vertical/horizontal resize cursor, or the hand pointer)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This sounds like a chrome/electron issue. We don't own/control dev tools used here so closing as upstream

However it could also just be that the breakpoint is paused on a separate process  so double that check first
