### ISSUE TITLE
Debug Terminal not openning

### ISSUE THREAD

**Issue by M16Ali** [microsoft/vscode#116638]
Issue Type: <b>Bug</b>

It seems like when debugging, if the "console" option in "launch.json" is set to "integratedTerminal", there is no option available in the "Terminal" tab to view the console output.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.26GB free)|
|Process Argv|. --crash-reporter-id 9ce0ec0d-e0aa-45b7-a51a-781e00193586|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.0.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.23.1
rest-client|hum|0.24.4
better-cpp-syntax|jef|1.15.5
Angular2|joh|11.0.0
vscode-github|Kni|0.30.4
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.1.0
quicktype|qui|12.0.46
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
cmake|twx|0.0.17
vscode-arduino|vsc|0.3.4
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
This works just fine for me.
Can you reproduce with VS Code insiders?
https://code.visualstudio.com/insiders/

![Screenshot 2021-02-15 at 11 49 05](https://user-images.githubusercontent.com/1926584/107937144-d4694600-6f83-11eb-84fe-3198306a5445.png)

**Comment by M16Ali** [comment]
Not an issue in the insiders version.

Thanks!

**Comment by KochC** [comment]
But still an issue in the normal VSCover Version.

**Comment by M16Ali** [comment]
Reopening as the issue now affects both the normal as well as insiders version of VS Code.

**Comment by isidorn** [comment]
Can not repro. Can you please provide steps and picture showing the problem, thanks

**Comment by M16Ali** [comment]
Please see the image.
![image](https://user-images.githubusercontent.com/39730473/108833316-7e972e00-7581-11eb-8612-ae50571e29f4.png)

The launch.json has 'console' set to 'integratedTerminal'. Works fine with 'externalTerminal'.
![image](https://user-images.githubusercontent.com/39730473/108833488-c027d900-7581-11eb-97cf-d36d0556337c.png)

Code version:
Version: 1.54.0-insider (user setup)
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:16:26.487Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
Ok, forwarding to @weinand since he might have changed something in the `console` handling

**Comment by weinand** [comment]
The "console" property is provided by the debugger extension you are using.
