### ISSUE TITLE
Search options are not saved between sessions if `search.mode` is `newEditor`

### ISSUE THREAD

**Issue by ssoher** [microsoft/vscode#116605]
Issue Type: <b>Bug</b>

In the `newEditor` search editor mode, if I toggle `Match Case`, `Match Whole Word` and `Use Regular Expressions` settings in the search editor, upon restarting VSCode, those settings do not persist and are toggled off each run.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18362

**Comment by JacksonKearl** [comment]
Does enabling the setting `search.searchEditor.reusePriorSearchConfiguration` work for you?

**Comment by ssoher** [comment]
> Does enabling the setting `search.searchEditor.reusePriorSearchConfiguration` work for you?

No, the settings are back to their default values on re-launching VSCode

**Comment by JacksonKearl** [comment]
If you run the search I'd expect the data to persist, it may not if you just toggle the entries. Also you referring to opening a new search editor and the flags being set there, or losing the flags set in the existing editor on reload? 

\gifPlease

**Comment by ssoher** [comment]
> If you run the search I'd expect the data to persist, it may not if you just toggle the entries. Also you referring to opening a new search editor and the flags being set there, or losing the flags set in the existing editor on reload?
> 
> \gifPlease

1- Toggle settings
2- Run search, find results
3- Close the search editor (if I don't close search editor and re-open that folder next time I run VSCode the settings persist because they are saved in the search editor I guess?)
4- Close VSCode
5- Re-open VSCode
6- Open new search (I do with ctrl shift f), and see that all the toggles are off and Context Lines count is 1

Still need the gif? I have to close and re-launch VSCode, not sure if a gif would help. I'll do the exact things listed above.

**Comment by JacksonKearl** [comment]
Okay, when I try I do get the settings back if I reopen the same folder, but they don't persist to other folders, such as the empty folder vscode sometimes launches at startup. I believe the settings are persisted per-folder, as that's what makes sense for includes/excludes.

If you want all the toggles enabled no matter the workspace, you could try setting the arguments explicitly in your `findInFiles` command:
![image](https://user-images.githubusercontent.com/8586769/108111012-f973bc80-7048-11eb-828c-7aa5b2fe41b3.png)

**Comment by ssoher** [comment]
They don't persist in the same folder for me if I closed the search editor before closing VSCode completely and re-opening the same folder.

**Comment by ssoher** [comment]
![search_bug](https://user-images.githubusercontent.com/4283979/108112285-8c8b1180-709e-11eb-9d96-0b0417976083.jpg)

**Comment by ssoher** [comment]
@JacksonKearl still labeled as 'needs more info', is there anything else I can provide to help with this?

**Comment by JacksonKearl** [comment]
I still can not reproduce this. I have included a screen recording of what it looks like when I try this flow, perhaps you can see if I'm doing something differently from you?

![recording](https://user-images.githubusercontent.com/8586769/108405199-a54a1300-71d5-11eb-86ac-a355774c8fd9.gif)

**Comment by ssoher** [comment]
Works correctly in the Insiders for me as well, but of course I've been having the problem in the stable release version. So guess we'll say it's fixed in the insiders then?

**Comment by JacksonKearl** [comment]
Oh sorry about that, for some reason I thought you were using Insiders. This is a duplicate (in spirit) of #115633.
