### ISSUE TITLE
VSCode leaking memory

### ISSUE THREAD

**Issue by dkent600** [microsoft/vscode#116644]
Issue Type: <b>Bug</b>

Sorry I have little information.  I only just now noticed the "Process Explorer" feature that I will try if this happens again.

All I can say is that through Windows Task Manager I discovered that VSCode had gobbled 15G of RAM.  I tried to close it and in Windows task bar it appeared gone but Task Manager showed it still active, so I killed it and the 15G was immediately restored.

Let me know if there is anything I can do to help you diagnose this.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.79GB free)|
|Process Argv|--crash-reporter-id 383c58f2-21d9-4471-b4b7-48bc20f1f233|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.0
aurelia|Aur|1.0.7
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.3.0
vscode-svgviewer|css|2.0.0
vscode-npm-script|eg2|0.3.15
vscode-pull-request-github|Git|0.23.1
search-editor-apply-changes|jak|0.1.1
remote-wsl|ms-|0.53.4
powershell|ms-|2020.6.0
typescript-javascript-grammar|ms-|0.0.55
debugger-for-edge|msj|1.0.15
vscode-scss-formatter|sib|2.1.0
vscode-open-in-github|sys|1.14.0
shell-launcher|Tyr|0.4.1
gitblame|wad|6.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by egamma** [comment]
/needsMoreInfo pls follow this guide to helps us track down memory issues https://github.com/microsoft/vscode/wiki/Performance-Issues
