### ISSUE TITLE
Cannot access upstream folders

### ISSUE THREAD

**Issue by PhilB313** [microsoft/vscode#116636]
Issue Type: <b>Bug</b>

VS Code ignores upstream folder designation ../js/MenuCode.js 
It only looks in the local folder /js/MenuCode.js
So with files in sub-folders, they can never access js or css which is located off the website main folder.
MainCode/js/something.js can never be accessed from MainCode/subfolder/OtherCode.html.

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

**Comment by weinand** [comment]
This has nothing to do with VS Code.
