### ISSUE TITLE
VSCode window gets filled with background color when connecting or disconnecting a screen on Windows 10 in specific cases

### ISSUE THREAD

**Issue by Dexesttp** [microsoft/vscode#116762]
- VS Code Version:

  - First found on version 1.53.2
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

  - Reproduced on the latest Insiders version
Version: 1.54.0-insider (user setup)
Commit: a699ffaee62010c4634d301da2bbdb7646b8d1da
Date: 2021-02-15T05:17:48.792Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

- OS Version:
  - Windows 10 Home version 20H2 (os build : 19042.804)
  - Windows 10 Pro version 1909 (os build : 18363.1316)

Steps to Reproduce:

1. Create a new VSCode window
2. Set the window as full screen on the "main" screen
3. Switch to another full screen window of another program (e.g. Chrome) on the "main" screen, hiding the VSCode window
4. Connect or disconnect another screen to the computer
5. Click on the VSCode icon in the taskbar (seems a bit more consistent) or Alt-tab back to the VSCode window (seems a bit less consistent)
6. The VSCode window is completely filed with the background color (see screenshot below)
![image](https://user-images.githubusercontent.com/5400651/108049185-3d19f680-7048-11eb-992e-1c6cf24d4b78.png)

Does this issue occur when all extensions are disabled?: Yes

Extra information :
- Dragging the top of the window, reconnecting the screen, or starting a "snip" screenshot operation re-displays everything properly.
- This issue didn't seem to happen in the 1.52 version
- The issue also seems to happen in the alt-tabbing window previews (see screenshot below)
![image](https://user-images.githubusercontent.com/5400651/108048176-00013480-7047-11eb-9ccf-8c9f78bbf858.png)
- The issue does not seem to happen when the VSCode window is not full screen
- The main issue does not happen every time / consistently (often enough to be slightly annoying during normal use, and inconsistently enough to be annoying to screenshot when trying to make a report). However, the above partial issue of alt-tabbing seems to be 100% consistent.
- Graphics cards and screen resolutions of the main and connected screens do not seem to matter (I reproduced it on two different computers with wildly different configurations and with different connected screens). However, for my tests I could reproduce it when connecting an extra 1920x1080 screen (on a 1920x1080 main screen) and an extra 1360x768 screen (on a 1920x1080 main screen).

**Comment by Dexesttp** [comment]
After digging through the commit history and doing some more testing with local compilations, it seems like this issue appeared in 94142bd7e0dbc073fe6abf130d7b7066a7beb1d6 :
	- commit 962bedc4f47b26e4a6ddc917ee2a4d9445531fb9, right before the commit, works as expected (1.52.1 behaviour)
	- commit 94142bd7e0dbc073fe6abf130d7b7066a7beb1d6 didn't work (new behaviour with bug)

This was the Electron update from 9.3.5 to 11.0.3, so the issue might be coming from Electron itself.

**Comment by shilx** [comment]
我遇到了相同的问题，必现。  
按照您的提示，我下载了1.52.1，终于可以正常使用了。  
    
I encountered the same problem, which is inevitable on my computer.  
According to your tips, I downloaded 1.52.1, and finally it can be used normally.

**Comment by Dexesttp** [comment]
The issue stops happening when using the `code --disable-features=CalculateNativeWinOcclusion` flag.
