### ISSUE TITLE
Zoom can be mixed across windows

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#116754]
1. Open a workspace in window A
2. Open another workspace in window B
3. In window B, Zoom in
4. File > Exit
5. Open VS Code
5. In window A, F1 > Reset Zoom Level
6. In window B, F1 > Reload Window

🐛 Window B is zoomed in!

![image](https://user-images.githubusercontent.com/22350/108039718-5479c500-6ff1-11eb-846f-de1d921d4429.png)

**Comment by joaomoreno** [comment]
I bet this is some type coersion bug like `if (zoomLevel)`, when `zoomLevel` is `0`.

**Comment by bpasero** [comment]
Isn't this just a duplicate of https://github.com/microsoft/vscode/issues/108920?

**Comment by joaomoreno** [comment]
Yeah it's possible. I hit this quite often.
