### ISSUE TITLE
Stray ? glyphs in Debug console

### ISSUE THREAD

**Issue by AdrianJMartin** [microsoft/vscode#116709]
Issue Type: <b>Bug</b>

using something like the code below to output symbols ( above ascii 128 ) 

static void Main(string[] args)
        {
            Console.WriteLine( "Using PadRight" );
            for( var i = 0 ; i < 5 ; i ++ )
                Console.WriteLine("├".PadRight(79, '─') + "┤");
            Console.WriteLine( "");

            Console.WriteLine( "Using Literal");
            for( var i = 0 ; i < 5 ; i ++ )
                Console.WriteLine("├──────────────────────────────────────────────────────────────────────────────┤");
            Console.WriteLine( "");

            Console.WriteLine( "Using StringBuilder");
            var sb = new System.Text.StringBuilder();
            for( var i = 0 ; i < 5 ; i ++ )
                sb.AppendLine( "├".PadRight(79, '─') + "┤" );
            Console.Write( sb.ToString());
        }

???? characters appear in the Debug Console output ( assume its unmapped unicode chars)

Using PadRight
2 <--- dupe row indicator
├──────────────────────────────────────────────────────────────────────────────┤
├───��──────────────────────────────────────────────────────────────────────────┤
├────────���─────────────────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤

Using Literal
├──────────────────────────────────────────────────────────────────────────────┤
├────────────────��─────────────────────────────────────────────────────────────┤
├─────────────────────���────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤
├──────────────────────────────��───────────────────────────────────────────────┤

Using StringBuilder
├──────────────────────────────────────────────────────────────────────────────┤
├───��──────────────────────────────────────────────────────────────────────────┤
├────────���─────────────────────────────────────────────────────────────────────┤
├──────────────────────────────────────────────────────────────────────────────┤
├─────────────────��────────────────────────────────────────────────────────────┤

I tried different fonts etc - but the ? still appears

Running the same code in an C#/Notebook cell produces the correct output

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.78GB free)|
|Process Argv|--crash-reporter-id 2fac746e-77c4-4c8f-abeb-9cc10d2b0ecb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
glsl-canvas|cir|0.2.11
bracket-pair-colorizer-2|Coe|0.2.0
gitlens|eam|11.2.1
rest-client|hum|0.24.4
svg|joc|1.4.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
dotnet-interactive-vscode|ms-|1.0.211402
vscode-dotnet-runtime|ms-|1.0.0
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.0
hexeditor|ms-|1.4.0
vscode-xml|red|0.15.0
LiveServer|rit|5.6.1
shader|sle|1.1.5
boxes|smu|0.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by MonkeyNinja** [comment]
I've just tried in JavaScript(Run Current File) and this works correctly...

```javascript
for (var i = 0; i < 50; i++)
 console.log("├──────────────────────────────────────────────────────────────────────────────┤")
```

**Comment by isidorn** [comment]
If this works correctly with JavaScript then please file against the extension you are using for debugging. Thanks
