### ISSUE TITLE
Source control: do not show action bar for selected but only for focused items

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116752]
Currently in SCM we render the hidden action bar when an item has focus, hover or if it is selected.
This is unlike other view where we render the action bar only when an item has focus or is hovered.

I suggest that we change the SCM to behave like the other views.
Apart from consistency this should also improve focus navigation

fyi @joaomoreno to see if he did this behaviour on purpose

![Screenshot 2021-02-16 at 09 46 59](https://user-images.githubusercontent.com/1926584/108039283-2ff70a80-703c-11eb-8982-80e836ed7c85.png)

**Comment by joaomoreno** [comment]
@isidorn This is because you can click those actions and they will execute for all selected items. We can't really change that. In your screenshot, for example, there wouldn't be a way to stage those 3 selected changes, if we hide those actions, other than the context menu.

**Comment by isidorn** [comment]
@joaomoreno we still show the action bar on hover. So if you would hover you would get it and you could trigger.

**Comment by joaomoreno** [comment]
Oh right! I guess then yeah we could definitely do it.

**Comment by DonJayamanne** [comment]
Perhaps I'm not understanding this issue title.
I would expect the `action bar to not show`, but in the latest insiders, the action bar shows always, whether its selected or not, whether we're hovering or not, 
Is this what's expected?


| Stable        | Insiders  |
| ------------- |-------------|
| ![Screenshot 2024-02-22 at 16 09 09](https://github.com/microsoft/vscode/assets/1948812/48751b75-71a4-410d-8451-96c56b4a82b0)      | ![Screenshot 2024-02-22 at 16 09 14](https://github.com/microsoft/vscode/assets/1948812/f1e7c854-498a-4e0b-941b-3865b63c5d9e)
 |

**Comment by DonJayamanne** [comment]
> an you still reproduce that all the toolbars are shown.

Yes still the same as per the screenshot.
Repro steps are simple, just make changes in a folder with git as scm
btw, I have updated to the latest version of VS Code insiders as well.

**Comment by isidorn** [comment]
Ok. Feel free to reopen this issue, or create a new one then.
I know Lad is out today though

**Comment by DonJayamanne** [comment]
@lszomoru let me know what you need, versions, logs, etc.

**Comment by lszomoru** [comment]
@DonJayamanne, do you have the `scm.alwaysShowActions` setting enabled as that would explain what you are seeing?

**Comment by DonJayamanne** [comment]
Spot on, yes, thanks. Not sure how that got set though.
