### ISSUE TITLE
Console output not correctly shown while Debugging

### ISSUE THREAD

**Issue by M16Ali** [microsoft/vscode#116710]
Issue Type: <b>Bug</b>

Hi,

I encountered an issue while debegging whereby any values pushed to console would not be printed until the cursor moves to next line. 

The issue persists both with integrated as well as external terminal. Windows version of code-insiders does not have the same problem.

I also noticed that the 'step into' feature works differently from Windows and does not actually step into any of the header files like `<iostream>`. 

Let me know if you need any further information.

VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:46.733Z)
OS version: Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (0.29GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 65c1a563-71c6-42b2-b77e-6647a0b3077b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.0.0
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.23.1
rest-client|hum|0.24.4
better-cpp-syntax|jef|1.15.5
Angular2|joh|11.0.0
vscode-github|Kni|0.30.4
Angular-BeastCode|Mik|10.0.3
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.160.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.3
vscode-arduino|vsc|0.3.4
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanelcf:30233468
coreuntitledfile:30249963
openwslfolder:30257223

```

</details>

**Comment by weinand** [comment]
What debugger are you using?

**Comment by M16Ali** [comment]
> What debugger are you using?

GCC. I have provided the task.json and launch.json below:

/home/ali/Documents/Visual Studio Code/CPP/Project 2/.vscode/tasks.json
/home/ali/Documents/Visual Studio Code/CPP/Project 2/.vscode/launch.json
