### ISSUE TITLE
Unable to update per user installation while other user uses VS code

### ISSUE THREAD

**Issue by makersky** [microsoft/vscode#116745]
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. VS Code is installed per user (not system-wide)
2. User b is using VS Code from his own installation directory
3. Update is ready to install for user a
4. User a closes VS Code, installer starts

Installer finds code.exe from user b and tries to terminate process, which fails with Access is denied. Installation fails.

Feb 16 08:32:12.729 INFO Starting: C:\Users\user\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Feb 16 08:32:12.729 INFO Checking for running Code.exe processes... (attempt 1)
Feb 16 08:32:12.729 INFO Code.exe is running, wait a bit
...
Feb 16 08:32:43.171 INFO Gave up waiting for Code.exe to exit
Feb 16 08:32:43.171 INFO Checking for possible conflicting running processes... (attempt 1)
Feb 16 08:32:43.171 INFO Kill process if found: 14860, Code.exe
...
Feb 16 08:32:43.171 WARN Kill error Failed to open process: Access is denied.
...
(many more attempts)

Closing all code.exe processes of user b resolves problem.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
#76641
