### ISSUE TITLE
Visual Studio Code is showing me a blank window. I have tried many things but I can not fix this. Please help we love vs code.

### ISSUE THREAD

**Issue by santokhan** [microsoft/vscode#116794]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/114459

Please start the app with `--disable-features=CalculateNativeWinOcclusion` to workaround.
