### ISSUE TITLE
TS language server crashed 5 times in the past...

### ISSUE THREAD

**Issue by the21st** [microsoft/vscode#116744]
Issue Type: <b>Bug</b>

I created a new tsconfig.json in my project and restarted VSCode

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (2.16GB free)|
|Process Argv|--crash-reporter-id c966816f-5f13-4293-924c-035ff7153c03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
vscode-zipfs|arc|2.2.2
toml|be5|0.5.1
transformer|dak|1.11.0
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
vscode-yarn|gam|1.7.1
vscode-graphql|Gra|0.3.15
vscode-styled-components|jpo|1.5.0
vscode-github|Kni|0.30.4
camelcasenavigation|map|1.1.3
rainbow-csv|mec|1.8.1
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
color-highlight|nau|2.3.0
uuid-generator|net|0.0.4
abracadabra|nic|4.13.1
vscode-yaml|red|0.15.0
partial-diff|ryu|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by the21st** [comment]
Hey! I used the inbuilt VSCode bug reporter, didn't realize it was gonna create a github issue. Maybe the vscode bug reporter could be automated to conform to the issue reporting guidelines? Feel free to close this issue btw, this is too much of a scope creep for me.

**Comment by mjbvz** [comment]
Yes there is nothing we can do without information from you
