### ISSUE TITLE
Git status bar takes a long time to show new branch is checked out

### ISSUE THREAD

**Issue by Joemurai** [Microsoft/vscode#11677]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:

1. checkout a new git branch using windows command console with vs code open 'git checkout -b newbranch'
2. VS Code git status bar (bottom left) takes around 1.40 secs to show that new branch is checked out

**Comment by joaomoreno** [comment]
Code's git model is always delayed, in order not to overload the system with `git status` calls.
