### ISSUE TITLE
Provide Setting to NOT Track the Active Item in the File Explorer

### ISSUE THREAD

**Issue by fourpastmidnight** [microsoft/vscode#116787]
Please add a setting to turn off "tracking" in the  File Explorer tree. I work with many different tabs at the same time. I hate that when I click on a different file tab, the file explorer tree "jumps" to the location of the file in the tree. What if I simply clicked the document tab to get a reference or a name in the document, so that I can then open the appropriate file in the tree. And Maybe I had already scrolled the file tree into position....but _now_, I'll need to scroll the file tree back into position. This is tedious and annoying.

This is one of the **most annoying** "features" for me. It's one I consistently disable in Visual Studio proper. I'd like to have the option to disable it in VS Code, too.

**Comment by plainerman** [comment]
There already is a setting for that called `explorer.autoReveal` as described in [here](https://code.visualstudio.com/docs/getstarted/settings) and answered on [stackoverflow](https://stackoverflow.com/a/41066250/4417954).

**Comment by IllusionMH** [comment]
/question

@plainerman thanks for the answer!

**Comment by fourpastmidnight** [comment]
@plainerman Thank you!! I was looking for the Visual Studio setting called 'Auto-track'.  With all the thousands of settings available in VSCode (what, with after having extensions installed), it's nearly impossible to find a setting, especially one you're not looking for😉 but is really the one you want!! Thanks again!!
