### ISSUE TITLE
Javascript import module specifier ignores "non-relative"

### ISSUE THREAD

**Issue by plof27** [microsoft/vscode#116702]
Issue Type: <b>Bug</b>

1. Set `"javascript.preferences.importModuleSpecifier"` to `"non-relative"`
2. Add the following to `jsconfig.json`
```
{
  "baseUrl": "./"
}
```
3. Trigger the automatic import on a file

Expected behavior: vscode automatically adds an import statement from the `baseUrl` path
Actual behavior: vscode automatically imports using a relative path

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (4.11GB free)|
|Process Argv|D:\\Documents\\Programming\\sm-web-app --crash-reporter-id 7527eb5d-ec7d-4c4c-9761-77a8f9552cc1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.15
prettier-vscode|esb|5.9.2
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
nunjucks|ron|0.3.0
rust|rus|0.7.8
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates the problem

/needsMoreInfo
