### ISSUE TITLE
Add support for metadata in `NotebookCellOutput`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116792]
- VS Code Version:
- OS Version:

In the Jupyter extension today we can have outputs that have no mim-types, but contain metadata.
With the current API there is no way to store such metadata thats realted to output, as only NotebookCellOutputItem can store metadata. However this doesn't work as we don't have any mime types.

Suggestions:
* Add support for metadata in NotebookCellOutput
* Or add support for mime types that will not get rendered. E.g. if we use `text/plain` and an empty string will this get rendered?

Note: This is required in Jupyter today for scenarios as follows:
* Cell one will render an empty output with an id=xyz
* Cell two will return output telling the UI to display the output in the output item with id=xyz.
I.e. the UI needs to find the corresponding output item with that specific metadata and append the output from another cell into that.

As far as I know this is the only case, but considering the dynamic (untyped) nature of this metadata its possible other kernels could be storing other metadata in outputs when there is not visible output.

@jrieken @rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> Cell one will render an empty output with an id=xyz

Not arguing the need to output metadata but for your specific case we have added `NotebookCellOutput#id` so that output can be identified and later modified

**Comment by DonJayamanne** [comment]
Agreed, we can get around this today.
Also, as mentioned this is one scenario (we know of) where we can have metadata in an output without any useful output for display purposes. 

To ensure we store this information in the generated ipynb file, i'll need to now store all output metadata in a private map.

That'll work for me, its just a shame I need to add a work around for this.

Again, thanks for the API, I'll discuss this internally & probably try to work around this with our private map.

**Comment by rebornix** [comment]
@DonJayamanne we discussed that if the output metadata values are persisted on disk, it makes sense to have them in `NotebookCellOutput`. If they are used for other purposes, a private is better as now you have the output id.
