### ISSUE TITLE
Copy&Paste Police: cellActionView.ts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#116706]
The `src/vs/workbench/contrib/notebook/browser/view/renderers/cellActionView.ts` file seems to be copy-pasted from `menuEntryActionViewItem.ts`. It seems the motivation for that was vertical separator which (a) I am unsure if we still need it and (b) is something we surely can achieve with copy-pasting code, e.g via css

**Comment by jrieken** [comment]
The rendering abstraction is actually used already: https://github.com/microsoft/vscode/blob/bc72e7ab7e315a346c31cfa0cb77619375f94d6f/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L231-L233. What's left to do is to use the "normal" separator id and nuke all of the rest

**Comment by rebornix** [comment]
The custom action and action provider adds two changes on top of `menuEntryActionViewItem`:

* Vertical separator (whose width is smaller than normal action item view)
* Add separators between groups for inline (primary, navigation, etc) action items. Right now there is no separator between groups in primary

Both of them can be new options for `createAndFillInActionBarActions`.

**Comment by rebornix** [comment]
Less code.
