### ISSUE TITLE
Search Stops working

### ISSUE THREAD

**Issue by Noob7** [Microsoft/vscode#11670]
- VSCode Version: 1.4.0
- OS Version: Windows 7 Ultimate 64 bit

Steps to Reproduce:

1. press CTRL+F to find something. It will be searched
2. repeat step one and the search stops working. Similarly find all references does not work either. If we close the working file and reopen it, both search and find all references start working again

**Comment by Noob7** [comment]
![image](https://cloud.githubusercontent.com/assets/10553468/18342074/a267b72a-75ca-11e6-82c9-5f5141750a8b.png)

**Comment by alexandrudima** [comment]
@Noob7 From your screenshot it looks like you activated find in selection:

![image](https://cloud.githubusercontent.com/assets/5047891/18438183/8bebbb70-7900-11e6-9681-a5644f6731a0.png)

You can click that button to disable find in selection and start finding in the entire file.

**Comment by Noob7** [comment]
thats explains the name. Thanks :)
