### ISSUE TITLE
Checking off Getting Started items should be easier

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#116799]
Checking off items is a high bar right now. Some actions might not be wanted (like changing a theme) or even possible in the current project (like debugging).

These ideas would check off items much earlier to drive progress:

1. _Already working:_ Completing the linked action.
2. Clicking the checkbox icon in the item. We saw this being tried in user testing).
3. Clicking _Next_ in an item (so Next.
4. Jumping from one to the next section could complete all items.

@misolori any concerns from the UX side about making it easier to check items off?

**Comment by misolori** [comment]
I think the only concern is users blazing through the checklist just to get it out of the way, which is why we tied it to action-based completion. So if we want to abandon that idea we'd just need to account for this in our telemetry as `checked` != `discovered`.

**Comment by JacksonKearl** [comment]
Is there a reason to make it easier to check them off without actually having completed the associated action? Seems counter to the point. 

One thing we could do for theme in particular is change it from needing to change the theme to be checked to just needing to open the picker. That would make it so pressing the button always checks-off the item.

**Comment by digitarald** [comment]
> Is there a reason to make it easier to check them off without actually having completed the associated action? Seems counter to the point.

Two thoughts:

Checking off an item in getting started can mean a few things beyond "did what it told me to": "read it and understood it". "knew it and don't need to do it", .

The checking off state is to help users get a sense of completion. If we make it too hard it can backfire and frustrate (see [this video on a related experiment](https://youtu.be/9vJRopau0g0?t=57)).

I'd be very happy to do further user testing to learn how they work!

**Comment by misolori** [comment]
Another concern, if someone just wants to browse the other sections and we enable click to complete then this breaks that and assumed a “one way” for completing get started. So not very dynamic. 

I think we might look into doing a “Skip” action that removes that item, similar to Dropbox, if we want to tackle the issue of users not wanting complete issues because they’re hard or not interesting.

**Comment by digitarald** [comment]
> I think we might look into doing a “Skip” action that removes that item, similar to Dropbox, if we want to tackle the issue of users not wanting complete issues because they’re hard or not interesting.

Sounds like we have some alignment on adding a changing "Next" to "Skip", which checks off the item as well and has more intent than just clicking away or on the circle by accident. How does that sound, @JacksonKearl?

To understand how this changes the flow, could this be behind a flag?

**Comment by JacksonKearl** [comment]
added clicking the checkbox to mark the item complete, tracked under `gettingStarted.ActionExecuted`:`completeTask` (versus clicking the button is `runTaskAction`)
