### ISSUE TITLE
Cannot install freestanding JSON language server using npm

### ISSUE THREAD

**Issue by siegel** [microsoft/vscode#116720]
- VS Code Version: n/a
- OS Version: macOS 10.15.7, npm 7.5.0

Steps to Reproduce:

1. Go to the [vscode-json-languageserver page](https://www.npmjs.com/package/vscode-json-languageserver) and read the instructions in the "Integrate" section:
```
You can also launch the language server as a command and connect to it. For that, install the json-language-server npm module:

npm install -g json-language-server
```
2. Open a terminal and run the command as indicated: `npm install -g json-language-server`.

Expected outcome: `npm` installs the freestanding JSON language server.

Actual outcome: `npm` reports the following:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/json-language-server - Not found
npm ERR! 404 
npm ERR! 404  'json-language-server@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/siegel/.npm/_logs/2021-02-15T18_32_05_416Z-debug.log
```

I have attached the cited log file.
[2021-02-15T18_32_05_416Z-debug.log](https://github.com/microsoft/vscode/files/5983473/2021-02-15T18_32_05_416Z-debug.log)

Does this issue occur when all extensions are disabled?: n/a

**Comment by aeschli** [comment]
Sorry, that was a typo in the README.

Please try `npm install -g vscode-json-languageserver`

**Comment by siegel** [comment]
Successfully installed using `npm install -g vscode-json-languageserver`, thank you very much!
