### ISSUE TITLE
Allow multiple build tasks depending on file type

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1167]
I'm working with a lot of projects that have different build tasks for different file types, for example I `javac` for Java, `pdflatex` for Latex, others may have `lessc` for their styles and `babel` for their JS.
Currently, you can only define _one_ build task to be run when Ctrl+Shift+B is pressed. tasks.json allows us to nicely define tasks to run with the currently opened file, but (eg compile the currently open java / Latex / Less / ES6 file), but you can only assign one of these tasks the shortcut that comes with `isBuildCommand`.

It would be nice if instead of just `"isBuildCommand": true` we could also define `"isBuildCommand": "java"` and for another task `"isBuildCommand": "latex"` so VS Code automatically runs the desired task when pressing Ctrl+Shift+B depending on what type of file is currently open.

This should also work with `"isTestCommand"`

**Comment by felixfbecker** [comment]
I also have tasks like `build-admin`, `build-main`, `build-server`. It would be nice if <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F5</kbd> would trigger the right build task based on a glob that is matched on the currently opened file (could set the folder in there).

**Comment by dbaeumer** [comment]
Couple of things have improved here with task 2.0.0:

- you can have dependsOn to trigger n tasks
- you can bind a key binding to any task

I will close this issue. Please open a new one if the provided features doesn't satisfies your needs.
