### ISSUE TITLE
Code insiders - Extension host terminated unexpectedly when I have any Live SCSS compiler extension installed

### ISSUE THREAD

**Issue by ChopsKingsland** [microsoft/vscode#116733]
- VS Code Version: 1.54.0-insider
- OS Version: Darwin arm64 20.3.0 (MacOS 11.2.1)

Does this issue occur when all extensions are disabled?: No

The issue:

The issue that I am having is that when I have any live SCSS compiler extension installed, I get the error `Extension host terminated unexpectedly`... If I disable the SCSS compiler, the error goes away, and it works normally... Does anyone know a fix?

**Comment by aeschli** [comment]
You need to file this against the extension that seems to crash.

**Comment by ChopsKingsland** [comment]
It was happening with any live SCSS compiler, but since an update to VSCode, I no longer get the error...
