### ISSUE TITLE
Node debug breaking on reject inside caught promise

### ISSUE THREAD

**Issue by scottdrichards** [microsoft/vscode#116783]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Debug a node script like this: new Promise((resolve, reject)=>reject("Exception!")).catch(console.log);
2. It will break on the exception, even though it is caught in the promise. Hitting continue in the debugger will proceed without issue.

![image](https://user-images.githubusercontent.com/28912482/108081983-94679900-703f-11eb-8cf0-126b471e9f34.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
This is an issue in V8: https://bugs.chromium.org/p/chromium/issues/detail?id=465666&q=uncaught%20promise%20pause&can=2 Once that's fixed, Node and our debugger will (eventually) be fixed.
