### ISSUE TITLE
vscode.env.openExternal escapes URI twice

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/vscode#116753]
Issue Type: <b>Bug</b>

I got the same problem as @eamodio described in https://github.com/microsoft/vscode/issues/76606#issuecomment-512904014 and the issue is unfortunately not solved for me by the linked issues https://github.com/microsoft/vscode/issues/25852 and https://github.com/microsoft/vscode/issues/83645

Do we need to wait for https://github.com/microsoft/vscode/issues/85930 ?

Small example: 
```typescript
let u1 = vscode.Uri.parse("https://example.com?key=myval%23b") 
console.debug(u1);  // correctly parses query: 'key=myval#b'
vscode.env.openExternal(u1);  // opens https://example.com/?key=myval%2523b  instead of https://example.com/?key=myval%23b
```

VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (16.30GB free)|
|Process Argv|--crash-reporter-id d3fb0cf6-1f84-4876-a713-812254481fe2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.1
vagrant|bbe|0.5.0
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
dotnet-test-explorer|for|0.7.5
go|gol|0.22.1
haskell|has|1.2.0
haskell-linter|hoo|0.0.6
rest-client|hum|0.24.4
latex-workshop|Jam|8.15.0
language-haskell|jus|3.3.0
vscode-azurefunctions|ms-|1.2.1
vscode-azureterraform|ms-|0.3.2
vscode-docker|ms-|1.9.1
csharp|ms-|1.23.9
al|ms-|6.5.413786
mssql|ms-|1.10.1
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
azure-account|ms-|0.9.6
powershell-preview|ms-|2020.9.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3629
openhab|ope|0.8.0
phoityne-vscode|pho|0.0.26
quicktype|qui|12.0.46
cosmo-azure-devops|tfe|0.11.22
vscodeintellicode|Vis|1.2.11
crs-al-language-extension|wal|1.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963
wslfolderdoccf:30257225

```

</details>

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"uri"

**Comment by jrieken** [comment]
> Do we need to wait for #85930 ?

Yes
