### ISSUE TITLE
Ctrl + Click doesnt go to the symbol definition

### ISSUE THREAD

**Issue by siju-samuel** [microsoft/vscode#116707]
Issue Type: <b>Bug</b>

After creating the project, if i control + Click on the symbol, its not going to the symbol definition..  It was working in the same workspace earlier and now its not working. i recreated workspace and tried all possiblities. it doesnt even work in project with only one file with 2-3 functions.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (1.02GB free)|
|Process Argv|--crash-reporter-id a6ae0cff-cb1e-4e7c-a628-ba6197ed4175|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ssamuel-vm.ssamuel-internal-server.com|
|OS|Linux x64 4.15.0-50-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8180 CPU @ 2.50GHz (8 x 2494)|
|Memory (System)|39.29GB (8.91GB free)|
|VM|100%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.5
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vsonline|ms-|1.0.3076
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by weinand** [comment]
For what type (language) of symbol do you see this problem?

**Comment by siju-samuel** [comment]
@weinand 
C++
