### ISSUE TITLE
Cannot read property 'Markdown' of undefined.

### ISSUE THREAD

**Issue by jwfu** [microsoft/vscode#116772]
Issue Type: <b>Bug</b>

1. Try to open an ipynb

Expected: file opens

Actual: get error Unable to open 'alphaVantage.ipynb': Cannot read property 'Markdown' of undefined.

This issue also happens in Windows 10 insiders build.  Susupect it is a regression, but unsure if it is in VS Code or one of the numerous python extensions running in the background.  On both platforms, opening the ipynb in the stable VS Code works.

VS Code version: Code - Insiders 1.54.0-insider (5e74ad5430203eadf89fd8e99695f4ebdb0e62ad, 2021-02-16T10:26:57.613Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2273)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|15.52GB (2.42GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.9.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-clock|Com|0.0.1
vscode-markdownlint|Dav|0.39.0
gitlens|eam|11.2.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
gc-excelviewer|Gra|3.0.41
latex-workshop|Jam|8.15.0
restructuredtext|lex|143.0.0
python|ms-|2021.3.559238081-dev
jupyter|ms-|2020.12.414227025
wordcount|ms-|0.1.0
material-icon-theme|PKi|4.5.0
code-spell-checker|str|1.10.2
pdf|tom|1.1.0
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details>

**Comment by wheresmyhair** [comment]
Also have the same issue and it seems that this is due to some VSCode update. I can open .ipynb 14 days ago (handed a homework in at that time and then didn't use vscode for a while).
版本: 1.54.0-insider (user setup)
提交: 192c817fd350bcbf3caecae22a45ec39bae78516
日期: 2021-02-19T05:14:28.632Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by candrewlee14** [comment]
On a fresh install of the Insider's Edition for Windows 10 with only the Python extension installed.
 
"Unable to open 'proj.ipynb': Cannot read property 'Markdown' of undefined."

**Comment by braineruption** [comment]
Same issue here on Mac OS.

**Comment by JontySinai** [comment]
The issue seems to be with v1.54. I've temporarily worked around it by installing v1.53 following instructions from[ #4796](https://github.com/microsoft/vscode-jupyter/issues/4796). Furthermore turn off automatic updates in settings to prevent Insider 1.53 from automatically updating to 1.54.

**Comment by jwfu** [comment]
resolved in https://github.com/microsoft/vscode-jupyter/issues/4796.
