### ISSUE TITLE
Npm: Unable to debug scripts in subfolders

### ISSUE THREAD

**Issue by MichaelHindley** [microsoft/vscode#116705]
- VS Code Version: Version: 1.53.2
- OS Version: macos catalina

Steps to Reproduce:

1. Create a package.json in root, one in "api" and one in "app", with any npm script.
2. Let VScode know they exist by setting ""npm.includeDirectories": ["./api", "./app"]
3. Notice you can see all scripts from all 3 package.json in the "run npm script" menu, but only scripts from the root package.json in the "debug npm script" menu. 

Run:
![image](https://user-images.githubusercontent.com/1016639/107970472-70f60d00-6fb1-11eb-9673-5dce3d9ca3f6.png)

Debug:
![image](https://user-images.githubusercontent.com/1016639/107970497-7b180b80-6fb1-11eb-9662-146aaa361f2b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
Please file this against the npm extension.
