### ISSUE TITLE
Variables tree out of order

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11672]
![image](https://cloud.githubusercontent.com/assets/323878/18340911/d4dbaacc-75a7-11e6-85e8-7d2487019da7.png)
The first 3 variables should be under 'Local', and `_this` should be under 'Closure'.

**Comment by roblourens** [comment]
Just randomly saw this once when debugging, I don't think I did anything out of the ordinary.

**Comment by isidorn** [comment]
@roblourens in the screenshot si the variables view scrolled all the way to the top? If yes then it is a rendering tree issue on the UX side. If not then this is data coming from the node adapter and it is most probably an issue with our node debugger

**Comment by roblourens** [comment]
Yes, it's scrolled all the way to the top. Sorry I don't have actual repro steps. I forgot to check the chrome console... will keep an eye open though.

**Comment by isidorn** [comment]
Then the tree is badly rendered. On what OS are you? Repro steps would be great
ping @joaomoreno

**Comment by roblourens** [comment]
OSX

**Comment by isidorn** [comment]
@roblourens closing this until we get reproducable steps or until you get a broken state on your machine again so we can jump in and investigate
