### ISSUE TITLE
Emmet extensions_path option

### ISSUE THREAD

**Issue by fronteed** [Microsoft/vscode#11679]
- VSCode Version: 1.4.0 (2016-08-04T16:39:36.387Z)
- OS Version: OS X El Capitan 10.11.3

There's an `extensions_path` option for Emmet in Sublime and Atom, which allows you to have an external source for `preferences.json` and `snippets.json`.

> You can easily extend Emmet with new actions and filters or customize existing ones. In Preferences > Emmet, set Extensions path to folder with Emmet extensions. By default, it’s ~/emmet, e.g. emmet folder in your system HOME folder.

https://github.com/emmetio/emmet-atom#extensions-support

It's not available in the latest version of editor.
Can this option be ported into Visual Studio Code?

**Comment by fronteed** [comment]
Any progress on this issue? I've a long list of the snippets to use for Emmet (both CSS and HTML), if I add them to my `settings.json`, it will become messy, that's why an extended file is appreciated.

**Comment by ramya-rao-a** [comment]
@fronteed This is now implemented and should be in tomorrow's insiders build. Can you give it a try and provide feedback?

- The setting to use is called `emmet.extensionsPath`
- You need to provide absolute path at the moment.
- The files `snippets.json`, `syntaxProfiles.json` and `preferences.json` will be read from this directory.
- `emmet.preferences` and `emmet.syntaxProfiles` settings will take precedence over the contents of the above file
- The files are read once and cached. Will be re-read on VS Code reload or whenever there is a change to `emmet.extensionsPath`

More on emmet customization: http://docs.emmet.io/customization/
