### ISSUE TITLE
"Emmet: Wrap Individual Lines with Abbreviation" command does not preview whitespace correctly

### ISSUE THREAD

**Issue by DSlatkin** [microsoft/vscode#116738]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Run "Toggle render whitespace" command until whitespace is visible
2. Create a file and set the language mode to HTML
3. Set whitespace mode to 4 spaces if not already
3. Type `!` and push enter for Emmet HTML5 boilerplate
4. Type a few indented lines of content in the body tag
5. Verify the **indentation is only with spaces**, as expected
6. Highlight those lines and run the "Wrap with Emmet abbreviation" command
7. Use the abbreviation `div` to wrap the block in a div tag
8. Note the indentation is now a **mix of tabs and spaces**

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/9263640/108010636-2e84fe00-6fba-11eb-8e51-7430ef0bcc92.png)

Issue was originally filed at [microsoft/vscode-emmet-legacy#12](https://github.com/microsoft/vscode-emmet-legacy/issues/12) but that repo is getting archived so refiling here with some cleaner instructions. Not really a critical issue but I did spend a bit of time not realizing it was just a preview and not the actual output when you execute the command so would be nice if it's an easy fix. 🙃

**Comment by jeanp413** [comment]
I fixed this in https://github.com/microsoft/vscode/pull/116603
