### ISSUE TITLE
ThrottledDelayer hangs when disposed while triggered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116777]
Have a test such as:

```ts
test('ThrottledDelayer', async () => {
	const throttledDelayer = new async.ThrottledDelayer<void>(100);

	const promise = throttledDelayer.trigger(async () => { }, 0);

	throttledDelayer.dispose();

	return promise;
});
```

=> you get a timeout.

The fix seems to change this line to `this.cancel`:

https://github.com/microsoft/vscode/blob/f644b6b2a96cf40455b6c16f7f435dca932cd3c8/src/vs/base/common/async.ts#L300-L300

So that the pending promise has a chance to throw, but I am not sure about the exact implications?

**Comment by bpasero** [comment]
Nice lag.

**Comment by joaomoreno** [comment]
I was thinking about how to do it.
