### ISSUE TITLE
Globally disable error and warning squiggles

### ISSUE THREAD

**Issue by plof27** [microsoft/vscode#116703]
Often, there are extensions that provide useful functionality, but also clutter the main editor space with real-time warnings and errors. Here is an example from the rust package:

![image](https://user-images.githubusercontent.com/8202612/107965983-d970ca00-6f70-11eb-87d8-568b4ac71041.png)

I'd like to disable these visually, especially for compiled languages like rust, but there is currently no way to do this idiomatically. There does exist a hack solution: setting the editor color values to transparent, but it would be nice to have something officially supported.

**Comment by alexdima** [comment]
@plof27 The decorations cannot be entirely disabled, but their colors can be customized. e.g.

```
"workbench.colorCustomizations": {
  "editorError.foreground": "#00000000",
  "editorWarning.foreground": "#00000000",
  "editorOverviewRuler.errorForeground": "#00000000",
  "editorOverviewRuler.warningForeground": "#00000000",
}
```

**Comment by plof27** [comment]
> 
> 
> @plof27 The decorations cannot be entirely disabled, but their colors can be customized. e.g.
> 
> ```
> "workbench.colorCustomizations": {
>   "editorError.foreground": "#00000000",
>   "editorWarning.foreground": "#00000000",
>   "editorOverviewRuler.errorForeground": "#00000000",
>   "editorOverviewRuler.warningForeground": "#00000000",
> }
> ```

I am aware of this- this is the hack solution I mentioned in the original post. It works well enough, but I still think it would be valuable to have something officially supported.
