### ISSUE TITLE
Git not working after upgrade (appears similar to #37981)

### ISSUE THREAD

**Issue by prekratko** [microsoft/vscode#116758]
- VS Code Version: 1.53
- OS Version: CentOS 7.8

Steps to Reproduce:

1. Version 1.52.1 was installed and working properly
2. Performed yum upgrade via configured repository to available version 1.53.2
3. Git Lens, Git Graph don't recognize git repository root dir, where I start vscode from
4. I performed yum downgrade all the way back to 1.52.1 and it all works as before
5. All 1.53 version variants have this problem, as I noticed during downgrade, one by one

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate 1.53 is not compatible with CentOS 7

**Comment by prekratko** [comment]
Does statement "1.53 is not compatible with CentOS 7" mean it is not compatible at this moment or it will never be compatible at all?

**Comment by gjsjohnmurray** [comment]
@prekratko based on https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356 I think it's not going to change. Several users of CentOS 7 / RHEL 7 have posted ways of working around the issue.
