### ISSUE TITLE
Process explorer is letting other processes into the tree

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#116798]
I see this in main:

![image](https://user-images.githubusercontent.com/2193314/108109301-81a49280-7046-11eb-9cec-4c408639d70e.png)

![recording (12)](https://user-images.githubusercontent.com/2193314/108109308-85d0b000-7046-11eb-8bca-f9c20bcc0f9b.gif)

**Comment by joyceerhl** [comment]
Closing as not reproducible in latest Insiders:

![image](https://user-images.githubusercontent.com/30305945/207193944-32f25d30-5b36-4679-8dc4-6ee7e3992595.png)
