### ISSUE TITLE
Up / down navigation too jumpy in new welcome page

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#116749]
1. Open new welcome view
2. Navigate to the Quick Setup view
3. Navigate up / down using the arrows

As you navigate each part collapses and expands producing a very unstable and jumpy UI. I find it visually disturbing.
fyi @misolori 

![recording (1)](https://user-images.githubusercontent.com/1926584/108038276-ee199480-703a-11eb-87c3-bf0c8fe68629.gif)

**Comment by misolori** [comment]
I think this is the same as https://github.com/microsoft/vscode/issues/115314

**Comment by JacksonKearl** [comment]
Yes, will fix as part of #115314
