### ISSUE TITLE
VSCode produces a lot of docker processes with over 100% CPU usage

### ISSUE THREAD

**Issue by baydet** [microsoft/vscode#116750]
Issue Type: <b>Bug</b>

Process appears after ~10min of working vscode preview

![image](https://user-images.githubusercontent.com/1755124/108038472-eca49800-704b-11eb-9902-a7a0387266ba.png)

I suspect `ms-vscode-remote.remote-containers` extension

VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:27:07.770Z)
OS version: Darwin arm64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (0.66GB free)|
|Process Argv|--crash-reporter-id 5eb15274-2b6f-401e-90d4-e4d02f907449|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
subword-select|all|0.0.1
clipboard-history|Anj|1.0.7
quitcontrol-vscode|art|3.1.3
pgformatter|bra|1.16.0
gitignore|cod|0.6.0
githistory|don|0.6.14
prettier-vscode|esb|5.9.2
gitlab-workflow|Git|3.12.1
beautify|Hoo|1.5.0
JSDocTagComplete|Hoo|0.0.2
rest-client|hum|0.24.4
vscode-edit-csv|jan|0.5.4
a08-test-highlighter|jim|0.0.2
dotenv|mik|1.0.1
csharp|ms-|1.23.9
python|ms-|2021.3.559238081-dev
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.160.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
node-debug2|ms-|1.42.5
vsliveshare|ms-|1.0.3629
debugger-for-chrome|msj|4.12.12
vscode-subword-navigation|ow|1.2.0
gitpatch|par|0.2.1
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
python|tht|0.2.3
gitblame|wad|6.0.2
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963
openwsldoc:30257222

```

</details>

**Comment by weinand** [comment]
VS Code by itself does not use Docker. 
What are you doing in/with Docker?
Please be more specific.

**Comment by baydet** [comment]
You're right. The problem was as I noted below the screenshot in `ms-vscode-remote.remote-containers` extension. After I disabled it problem with CPU consumption gone. 

I think we can close this issue.

**Comment by weinand** [comment]
@baydet thanks for the update
