### ISSUE TITLE
Source Control viewlet: file action icons not vertically centered

### ISSUE THREAD

**Issue by JeffreyCA** [microsoft/vscode#116719]
- VS Code Version: 1.53.2
- OS Version: macOS 11.2.1 (20D74)

Steps to Reproduce:

1. Open project with source control
2. Make a change to one of the files
3. Go to Source Control viewlet
4. Hover over changed file in the tree view

Does this issue occur when all extensions are disabled?: Yes

See how the **M** is properly centered but none of the action icons are.

<img width="379" alt="Screen Shot 2021-02-15 at 1 18 41 PM" src="https://user-images.githubusercontent.com/9157833/107981681-8c045500-6f90-11eb-8d5d-67b3ceed394f.png">

**Comment by eamodio** [comment]
Do you still see this in 1.54? I think this should be resolved.

**Comment by JeffreyCA** [comment]
No it's fixed now. Closing this issue.
