### ISSUE TITLE
Code Navigation, Suggestions, Go to definition not working in VS Code

### ISSUE THREAD

**Issue by JeminiMunis** [microsoft/vscode#116796]
Hi, 
I am facing an issue with Code Navigation, Suggestions, Go to the definition on Visual Studio code. I am using TypeScript for React and I have installed all required extension support. But the code navigation, suggestions, and related stuff not working.
I have already tried without all extensions. Still, it didn't work. In my case, _IntelliSense and Initializing js/ts language feature_ not even loading. Due to that, the TypeScript version is not showing in the status bar. I have attached the screenshot of the issue for your reference. Can you please help me with this issue? 

We could find that the same issue was there already but he hasn't provided any code details so it has been auto closed.  
https://github.com/microsoft/vscode/issues/106628

Thank you!

<img width="960" alt="Capture1" src="https://user-images.githubusercontent.com/34243131/108105313-7a1ad300-70b2-11eb-85c7-21ba7d9f912e.PNG">
<img width="958" alt="Capture3" src="https://user-images.githubusercontent.com/34243131/108105322-7d15c380-70b2-11eb-8ba2-e26edee07b37.PNG">
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/34243131/108105333-7f781d80-70b2-11eb-883e-5a1963cd5cbb.PNG">

- VS Code Version: VSCodeSetup-x64-1.54.0-insider
- OS Version: Windows_NT x64 10.0.18363

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please provide steps to reproduce the problem and example code (as text)

/needsMoreInfo

**Comment by JeminiMunis** [comment]
> Please provide steps to reproduce the problem and example code (as text)
> 
> /needsMoreInfo

1. Not getting code suggestion and mouse over
2. Not Code Navigation.
3. I cleared all vs code cache and uninstalled all extensions and I reinstall the vs code.
	But still, I'm facing the same issue.

I have attached the example code. It's not working in my local setup. 
https://github.com/rokoroku/react-redux-typescript-boilerplate

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue using that project

**Comment by JeminiMunis** [comment]
> Please share steps to reproduce the issue using that project

When I freshly install visual studio code 1.53.2 Code navigation(CTRL+ CLICK), the mouse hover suggestion and go to the definition is not working for any piece of code.
Happy Coding!

**Comment by mjbvz** [comment]
Please provide specific steps, such as:

1. In file X
2. Do this speciation action. 
3. I expected __ but ___ happened instead

**Comment by JeminiMunis** [comment]
import React from "react";
import ReactDOM from "react-dom";
import Main from "./Main";
ReactDOM.render(
  <Main/>, 
  document.getElementById("root")
);

1. I have saved the above text in index.js and in the same folder, I have the Main.js file as well. 
2. When I'm trying to navigate (using CTRL+CLICK) on the third line, Ideally it should have navigated to the Main.js file.
But navigation is not happening for any of the imports.

<img width="172" alt="Capture_1" src="https://user-images.githubusercontent.com/34243131/108166111-b7667b80-7119-11eb-9c3e-1111cb1a1b50.PNG">

I was expecting this behavior, But it's not coming in my IDE.

**Comment by mjbvz** [comment]
`index.tsx` is in a different file than `main.tsx` so  you can't use `./` to reference it

Also, the  example project you linked to is all TS but your comment mentions `.js` files. You probably want to be using typescript instead

This seems like a question about TypeScript/react instead of a bug. If you feel otherwise, please provide more specific steps to reproduce the problem
