### ISSUE TITLE
[microsoft/vscode] Boot time 5-10 min windows 8.1 (#116665)

### ISSUE THREAD

**Issue by BrandinO771** [microsoft/vscode#116736]
Thanks for responding so quickly to my issue, I hope you can open my attachments, 
[prof-1502.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/5984893/prof-1502.extHost.cpuprofile.txt)

[Startup_Performance_Steinke.txt](https://github.com/microsoft/vscode/files/5984908/Startup_Performance_Steinke.txt)

![BS_STEINKE_VSCODE_STATS](https://user-images.githubusercontent.com/50427053/108005116-aba97680-6fac-11eb-9555-7786e4c41bfc.jpg)

 I read through your wiki and produced the below 

 I disabled extensions and that really had no effect still takes 5-6min to load the VS Code Application

A.)  from command prompt  I ran > code --prof-startup   , which created 3 files only 1 is small enough to send or attach to git hub, the other 2 were 42mb and 59mb ? see attached  < prof-1502.extHost.cpuprofile.txt > 

B.)  also I ran the <Startup Performance>   and pasted results into a txt see attached <Startup Performance Steinke.txt >

C.)  also I took screen grabs from task manager, Process Explorer etc... see attached  < BS_STEINKE_VSCODE_STATS.jpg > 

Thanks !!

On Monday, February 15, 2021, 04:03:41 AM PST, Benjamin Pasero <notifications@github.com> wrote:

Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

////////////////////////////////////////////////////////////////////////////////////////////////
Issue Type: <b>Performance Issue</b>

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz (8 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.89GB (11.78GB free)|
|Process Argv|--crash-reporter-id d702b472-b94a-4ae4-9dbc-381e257932b4 --crash-reporter-id d702b472-b94a-4ae4-9dbc-381e257932b4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    69	  9040	code main
    0	    23	   816	   utility
    0	    68	  4456	   shared-process
    0	    16	  6016	   crashpad-handler
    0	   165	  7308	   window (Startup Performance.md (deleted) - Visual Studio Code)
    0	    64	  6996	     extensionHost
    1	    52	  7780	   window (Issue Reporter)
    0	    54	  8844	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by jrieken** [comment]
It takes an unhealthy amount of time to create the renderer

<img width="953" alt="Screenshot 2021-02-16 at 09 23 51" src="https://user-images.githubusercontent.com/1794099/108036603-bb6e9c80-7038-11eb-9d9c-1e23467787ec.png">

**Comment by deepak1556** [comment]
Can you start the app with `code --disable-features=CalculateNativeWinOcclusion` and see if the issue is resolved.

**Comment by BrandinO771** [comment]
* I tried this command :  code --disable-features=CalculateNativeWinOcclusion   , I received this :  Warning : 'disable-features' is not in the list of known options, but still passed to  Electron/Chromium.  
* after this command Startup was still sluggish maybe even slower. 
* <<-- I think I fixed it !! -- >>- VS is running on my laptop with 2 graphics cards, You mention the render was taking too long, I went into  NVIDIA Control Panel and told it that the Intel Integrated Graphics Card is to render VS Code (before this VSCode was not mentioned in NVIDIA Control Panel list but must have defaulted to NVIDIA as the render)   once I did this VS Code booted up in like 5 seconds!!!  Is there a way in VS Code to specify which GPU to utilize?  Maybe I should test for 2 more days before we close this issue ....

**Comment by BrandinO771** [comment]
I am about to close this issue, but question, why was this an issue was VS Code attempting to be rendered by both graphics cards and thus stuck in a struggle to just be rendered by one, and eventually after 5 min it defaulted to my Intel GPU allowing the application to start?
