### ISSUE TITLE
New Outputs API in Notebooks does not support ANSI Codes such as `\u001b[A`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116791]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Use the new Notebook API
2. Send 3 separate output items for the same cell in 3 lines.
3. Ensure the 2nd or 3rd line contians the character `\u001b[A`
4. Notice how this ansic code is not properly interpreted.
The expectation is for previous line to get erased.
This is required in the Jupyter Notebooks when execution displays terminal style progress windows (with characters that deletes the previous line)

See here for some more info https://github.com/microsoft/vscode/issues/107424#issuecomment-735942882

@jrieken  @rebornix /cc
& Thanks for the new API.

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
> Notice how this ansic code is not properly interpreted.

I'd say that depends on the mime types. For plain text I would not expect automatic ansi interpretation. What mime are you using/expecting this for?

**Comment by DonJayamanne** [comment]
Expecting this for `application/x.notebook.stream`
Jupyter has a specific output for streams, its named `output_type=stream` and has two of them, `stderr` & `stdout`. I am assuming this is the raw output from the corresponding named streams.

Again, we can work around this today by not using the new API at all, and we can just concat the streams & always use the old api of `replaceNotebookCellOutput` instead of `appendNotebookCellOutputItems`. Its a shame to do that, as we don't get the benefit of the new API at all.

**Comment by DonJayamanne** [comment]
Discussed and we're planning on doing this ourselves and using the `replaceNotebookCellOutput`

**Comment by DonJayamanne** [comment]
Closing for now, don't see a point keeping this issue open as we're working around this issue.
FYI - we won't be using `appendNotebookCellOutputItems`

**Comment by jrieken** [comment]
> Again, we can work around this today by not using the new API at all, and we can just concat/split the streams (as we did in the past) & use the replaceNotebookCellOutput instead of appendNotebookCellOutputItems.

I am not sure how that would give you interpretation of ANSI. How would you do coloring in example?

**Comment by DonJayamanne** [comment]
> I am not sure how that would give you interpretation of ANSI. How would you do coloring in example?

We don't handle that, we're handling the special character `\u001b[A`, as we can manipulate the string ourselves & update the output.

**Comment by jrieken** [comment]
> We don't handle that, we're handling the special character \u001b[A, as we can manipulate the string ourselves & update the output.

Ideally you handle nothing and simple pass data to us. Tho, generally ansi is thing that you want to be supported, like this, right?

<img width="762" alt="Screenshot 2021-02-17 at 17 37 00" src="https://user-images.githubusercontent.com/1794099/108236041-c0ba0d00-7146-11eb-92ac-08b8284f09a4.png">

**Comment by DonJayamanne** [comment]
Oh wait, now i see, this issue was closed because there was no comment, i assumed upvoting meant the same thing, guess the bot doesn't see it that way.
