### ISSUE TITLE
Wrong highlight with minified javascript code in HTML(PHP)

### ISSUE THREAD

**Issue by Meeeeow** [Microsoft/vscode#11674]
- VSCode Version: 1.4.0
- OS Version: Windows 10 Update 1607

Steps to Reproduce:

Origin code is too large, so , 
1.  Paste all code in this link to VS Code, change file type to PHP  >>> http://pastebin.com/EeteWHqU
2.  Scroll down to see wrong syntax highlight.

![sp160908_152234](https://cloud.githubusercontent.com/assets/19658647/18341028/9eed53f6-75da-11e6-991b-2fe87ae3d1e9.png)
![sp160908_154239](https://cloud.githubusercontent.com/assets/19658647/18341103/fc73c640-75da-11e6-9d04-a3cb3982af62.png)

**Comment by aeschli** [comment]
For performance reasons we stop syntax highlighting when hitting lines larger than 20'000 characters
