### ISSUE TITLE
Changing workbench.tree.expandMode does not toggle twistie upon click anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#116788]
![recording](https://user-images.githubusercontent.com/900690/108091931-78ceb380-707c-11eb-96bd-b2c7f640b265.gif)

**Comment by joaomoreno** [comment]
Great catch! This was hard to find the culprit, but here it is: https://github.com/microsoft/vscode/commit/fe175afdb80bd7a28caae83028e7440b45698007
