### ISSUE TITLE
VS Code not updating

### ISSUE THREAD

**Issue by Satwik29** [microsoft/vscode#116784]
Issue Type: <b>Bug</b>

Open Insiders, click on Restart to Update.
Instead of updating, window opens again and it shows same restart to update.

I dont why this is happening

VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.95GB (2.28GB free)|
|Process Argv|--crash-reporter-id 2e0a5721-0e7a-4a02-8faf-a5be5786b6d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.1
project-manager|ale|12.0.1
code-gnu-global|aus|0.2.2
markdown-preview-github-styles|bie|0.1.6
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.14
git-extension-pack|don|0.1.3
githistory|don|0.6.14
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.23.1
kite|kit|0.138.0
vscode-github|Kni|0.30.4
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.11
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963
openwslfolder:30257223

```

</details>

**Comment by joaomoreno** [comment]
Can you completely uninstall and reinstall VS Code?
