### ISSUE TITLE
json schema validation $schema field

### ISSUE THREAD

**Issue by RedGuy12** [microsoft/vscode#116793]
This might belong in bugs, I'm not sure.

When I set a `$schema` field in a `json` file, it says, `Property $schema is not allowed.` I think `$schema` should be allowed by default, even if the linked schema doesn't explicitly allow it.

**Comment by aeschli** [comment]
Using `$schema` in a JSON file that is not a schema is not part of the JSON schema specs. It's just something that VSCode supports.
So if a schema defines that there's only a given set of properties allowed on top level, then you can not use `$schema`.
There are other ways to associate a schema with a file, see https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings
