### ISSUE TITLE
With native titlebar on Win7, can't open menus via keyboard if focus is in terminal

### ISSUE THREAD

**Issue by JohnKlenk** [microsoft/vscode#116826]
Issue Type: <b>Bug</b>

With the native titlebar enabled on Win 7, you can't open the menus with the keyboard (such as Alt-f for File) if focus is in the terminal.  I don't see the problem on Win 10.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3411)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.02GB free)|
|Process Argv|--crash-reporter-id 97db3b42-efc9-475c-944d-3c8c484c085d|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
vscode-pull-request-github|Git|0.23.1
cpptools|ms-|1.2.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by deepak1556** [comment]
Thanks for the report, native titlebar support comes from Electron and given the issue is only with Windows 7 which has reached EOL, I don't plan to create an issue in upstream.

**Comment by JohnKlenk** [comment]
Actually, I'm now seeing this with even the custom titlebar, and even on Windows 10.  I'm pretty sure it used to work, so it seems like this just broke.  Should this just be reworded to remove the reference to Win7 and the native titlebar, or should I open a new report?

**Comment by deepak1556** [comment]
If it is with custom titlebar, yes. Do open a new issue. Thanks!

**Comment by JohnKlenk** [comment]
Done: https://github.com/microsoft/vscode/issues/117318
