### ISSUE TITLE
Remote Development using SSH - Raspberry Pi Zero W Support

### ISSUE THREAD

**Issue by szh** [microsoft/vscode#116818]
Would like to be able to use Raspberry Pi Zero W as a remote host. Right now when trying to connect it fails with "Unsupported architecture: armv6l" in the output window.

https://code.visualstudio.com/docs/remote/ssh#_system-requirements lists armv7 and 8 but not 6 which the Pi Zero uses.
Issue #106867 is identical to this one but is closed and locked with no comments.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/669
