### ISSUE TITLE
Unable to publish Jupyter extension to marketplace

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116888]
Steps to Reproduce:

1.Attempt to upload the vsix to the marketplace portal
2.We get an error indicating its failing, here's the issue:
![Screen Shot 2021-02-17 at 14 55 35](https://user-images.githubusercontent.com/1948812/108279355-59459280-7131-11eb-8f74-b9309c3d730c.png)
![Screen Shot 2021-02-17 at 15 04 22](https://user-images.githubusercontent.com/1948812/108279422-70848000-7131-11eb-86f3-71877ee06abc.png)

@sandy081 /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by sandy081** [comment]
cc @prashantvc

**Comment by prashantvc** [comment]
@DonJayamanne could you email to vsmarketplace@microsoft.com? 
Is this is the extensions? https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

**Comment by DonJayamanne** [comment]
We managed to solve this issue. A `.so` file was incldued into the extension accidentally (due to python package) & we believe thats what caused the package to get rejected. Would be good to get a more meaningful message.

Thanks, closing as we have resolved this.

**Comment by DonJayamanne** [comment]
Re-opening as we're running into this yet again, & it would be good to know what's wrong with the package.
I've excluded *.so files, and still failing.
I have attached the file here.
[ms-toolsai-jupyter-insiders.4.vsix.zip](https://github.com/microsoft/vscode/files/6014055/ms-toolsai-jupyter-insiders.4.vsix.zip)

Will send the email as well.

**Comment by prashantvc** [comment]
@rheajain can you take a look at this please?

**Comment by DonJayamanne** [comment]
@prashantvc @rheajain Is there anyone we can email to try to expedite this? Thanks

**Comment by DonJayamanne** [comment]
@rchiodo @IanMatthewHuff @greazer /cc

**Comment by DonJayamanne** [comment]
@fiveisprime /cc

**Comment by xavierdecoster** [comment]
Issue moved to [microsoft/vsmarketplace #5](https://github.com/microsoft/vsmarketplace/issues/5) via [**ZenHub**](https://www.zenhub.com/)
