### ISSUE TITLE
Allow focusing of explorer nodes without selecting them

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#116860]
Windows explorer lets you move the focus around without impacting the selection by holding ctrl which I find really nice:

![recording (1)](https://user-images.githubusercontent.com/2193314/108237560-e3273880-70fc-11eb-8edd-7ead63d3d2ee.gif)

Right now we behave a little unexpected where the focused item is always selected. Additionally I noticed that if I have made a selection and move the selection around and then cut the files, only the focused item gets cut when I would expect all selected (excluding the focused item).

**Comment by joaomoreno** [comment]
This is already implemented.

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/118046
