### ISSUE TITLE
1.53 seems to break Markdown Mermaid Support

### ISSUE THREAD

**Issue by ecpearson** [microsoft/vscode#116805]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Preview markdown document with Mermaid diagram in 1.53 and objects that looked correct previously, no boxes constrained (similar to Azure DevOps).
![2021-02-16 14_03_08-Preview Databricks md - vscode (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/7506492/108115618-fdf79f80-705f-11eb-8361-ca9af9f83d22.png)

Does this issue occur when all extensions are disabled?: With no extensions there is no Mermaid preview

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the extension author

**Comment by sebastianzolg** [comment]
Why is this closed, @gjsjohnmurray ? I also tried different mermaid extensions with version 1.53, and they no longer work. Have you tried it yourself with any of the extensions? I don't think it is the extension when they all stop working suddenly. Am I missing something?

**Comment by gjsjohnmurray** [comment]
When features implemented by extensions that are not built into VS Code stop working it is usually necessary for the extension author to begin the diagnosis. If there has been an undocumented breaking change in a new VS Code release the extension author is in the best position to work with the VS Code team to resolve it.

Please start by opening issue(s) on the extension repo(s), and preferably include a link to this issue in them.

**Comment by sebastianzolg** [comment]
Makes sense, @gjsjohnmurray ! Thanks for letting me know. Will open an issue.
