### ISSUE TITLE
Visual Studio Code 

### ISSUE THREAD

**Issue by Sauron2009** [microsoft/vscode#116862]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

On Sunday, 02/14/2021. I opened Visual studio code but, it was a black screen  on the index.html page from the project I was working on the previous night before closing VS Code. So after trying to uninstall and reinstall Vs Code and opening another project that I opened on VS Code before, I was able to get out of the black scrren. I had to open all of my projects on by one on VS Code.
Today when I opened VS Code it said that I don't have any folders opened but, the previous night I was working on a project and I had a folder opened. What should I do?

![image](https://user-images.githubusercontent.com/78165914/108239387-b2e09980-70fe-11eb-8f25-e12b29a9131f.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please start by sharing the version and platform information from The About dialog off the Help menu.

**Comment by Sauron2009** [comment]
I updated the issue

**Comment by Sauron2009** [comment]
> /needsMoreInfo please start by sharing the version and platform information from The About dialog off the Help menu.

![image](https://user-images.githubusercontent.com/78165914/108241521-c68cff80-7100-11eb-9a7c-67fcfe417bd9.png)

**Comment by Sauron2009** [comment]
I have updated the issue. So, can you help me?

**Comment by Sauron2009** [comment]
Hello? Can you help me?

**Comment by Sauron2009** [comment]
hello?

**Comment by Sauron2009** [comment]
hello?
