### ISSUE TITLE
Configuring launch.json to launch app with piped output?

### ISSUE THREAD

**Issue by manad777** [Microsoft/vscode#11680]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

I'm working on a node project which uses bunyan for logging .This is one of the most popular node loggers. It outputs logs in a JSON format, which is good for parsers, not so good for humans working interacively. If running interactively, you would use the bunyan (usually global) package/binary to pipe to and transform the JSON into more human-friendly text.

Example stdout/stderr output, when running ```node server/app.js```:
```{"name":"bapp","hostname":"ubuntu2","pid":7359,"component":"auth","level":30,"msg":"Initializing","time":"2016-09-08T08:21:16.748Z","v":0}```

Example stdout/stderr output when running ```node server/app.js | bunyan```: 
```[2016-09-08T08:21:16.748Z]  INFO: bapp/auth/7359 on ubuntu2: Initializing```

When I'm using VSCode's debugger, the Debug Console shows the JSON output. How can I configure launch.json so that it shows me output after it went through the bunyan executable? I was not able to find any details on the VSCode website. I'm using a pretty standard launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/server/app.js",
            //"program": "${workspaceRoot}/server/mocha-in-node.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development",
                "PORT": "8000"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
        {
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command.PickProcess}",
            "port": 5858,
            "sourceMaps": false,
            "outDir": null
        }
    ]
}
```

**Comment by weinand** [comment]
@manad777 please can try this:

create an executable script bunyan.sh in your project:
```
node $* | bunyan
```

In you launch config "Launch" add the attribute `"runtimeExecutable": "${workspaceRoot}/script.sh"`

With this VS Code will call `bunyan.sh`instead of `node` when starting a debug session.
