### ISSUE TITLE
Unable to execute or save Jupyter notebook

### ISSUE THREAD

**Issue by frenkcleven** [microsoft/vscode#116879]
Issue Type: <b>Bug</b>

Python cells do not execute in Jupyter notebook. It is not possible to save the notebook either. Markdown cells work as expected, I have not tried other languages. Behaviour is identical for local and remote files. Stable build works as expected, Insider build does not.

To reproduce:
1. Create new .ipynb file in folder
2. Open file in Notebook editor
3. Enter arbitrary Python code in cell
4. Run cell, code is not executed (no error, no output)
5. Save file, error is displayed

Error: Failed to save 'test.ipynb': Cannot read property 'Markdown' of undefined.

VS Code version: Code - Insiders 1.54.0-insider (3f0d8a14759cddea93f0dbddc12a4ef1e5586e86, 2021-02-17T07:37:50.976Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (1.71GB free)|
|Process Argv|--crash-reporter-id e83ca5e1-86db-4713-87bf-21dc3a62891d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.39.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
material-icon-theme|PKi|4.5.0
material-theme|zhu|3.9.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
coreuntitledfile:30249963
wslfolderdoccf:30257852

```

</details>

**Comment by hkennyv** [comment]
Same here, seems related to some breaking changes in the vscode notebooks API (see microsoft/vscode-jupyter#4819). In the meantime, looks like you can [downgrade vscode](https://github.com/microsoft/vscode-jupyter/issues/4796#issuecomment-779266138) to get it to work for now

**Comment by frenkcleven** [comment]
> Same here, seems related to some breaking changes in the vscode notebooks API (see [microsoft/vscode-jupyter#4819](https://github.com/microsoft/vscode-jupyter/issues/4819)). In the meantime, looks like you can [downgrade vscode](https://github.com/microsoft/vscode-jupyter/issues/4796#issuecomment-779266138) to get it to work for now.
> 
> The main issue is being tracked at [microsoft/vscode-jupyter#4796](https://github.com/microsoft/vscode-jupyter/issues/4796) for reference!

Thanks! I was looking for a downgrade binary but was unable to find one. This will do for now.
