### ISSUE TITLE
SavaAll

### ISSUE THREAD

**Issue by kumarvani** [microsoft/vscode#116837]
Issue Type: <b>Feature Request</b>

SaveAll feature not activated it is showing blank.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Do you mean this menu item?

![image](https://user-images.githubusercontent.com/6726799/108185143-e70a8900-7103-11eb-80cd-c0bc3d4f0b2f.png)

For me this activates when at least one of my open files has unsaved changes.

**Comment by kumarvani** [comment]
Yes

**Comment by kumarvani** [comment]
Ok. Thanks for updating..

**Comment by gjsjohnmurray** [comment]
@kumarvani please close your issue unless you need more help.

**Comment by kumarvani** [comment]
issue solved

**Comment by kumarvani** [comment]
Ok Sure
