### ISSUE TITLE
DAX does not support '--'

### ISSUE THREAD

**Issue by kirillperian** [microsoft/vscode#116816]
Issue Type: <b>Bug</b>

This is very easy to replicate. When saving a file as .dax with a line inside the code that has '--' in front of the line, it is supposed to function just as '//', commenting out the line. Instead, only '//' works, but not '--'.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by kirillperian** [comment]
I'd love to follow the steps, but I need more info since I am new at VS Code. Can you tell me which extension causes it? I only have C# 1.23.9, evermonkey 2.4.5 and SQL Server (mssql) extensions installed.

**Comment by gjsjohnmurray** [comment]
What language mode do you use with your .dax files? Look at the clickable indicator at the right-hand end of the status bar.

**Comment by kirillperian** [comment]
Hi, John!
It is DAX:
[image: image.png]
Kirill

**Comment by gjsjohnmurray** [comment]
To share your screenshot please update the issue at the GitHub site. Replying to the notification and embedding the image in your email reply doesn't work.

If you have DAX available as a choice in the Language Mode list then you must have installed an extension, and that's probably where your problem needs to get fixed.
