### ISSUE TITLE
(New Notebook UI) Local images cannot be inserted in Jupyter notebook

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode#116846]
Issue Type: <b>Bug</b>

Inserting local pictures in the markdown cells in notebooks does not render them.

![image](https://user-images.githubusercontent.com/36224762/108202179-f7d3f280-7135-11eb-9b6d-6d690a96d320.png)

![image](https://user-images.githubusercontent.com/36224762/108202224-07533b80-7136-11eb-8016-112e2159c741.png)

The previous issue for old notebook UI: https://github.com/microsoft/vscode-jupyter/issues/2988

VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:15:52.209Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 7, 7|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 957573b0-8efb-439e-8824-88e70a27447a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
aw-watcher-vscode|act|0.5.0
interactive-scala|als|1.3.0
docs-view|bie|0.0.9
better-toml|bun|0.3.2
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
scala|dal|0.0.5
gitlens|eam|11.2.1
vsc-material-theme|Equ|33.0.0
vsc-material-theme-icons|equ|1.2.0
crystal-lang|fau|0.4.0
go|gol|0.22.1
Ionide-fsharp|Ion|5.3.2
vscode-peacock|joh|3.9.1
language-julia|jul|1.1.21
crystal-ide|kof|0.0.4
vscode-markdown-notes|kor|0.0.22
nim|kos|0.6.6
dotty|lam|0.1.16
Lisp|mat|0.1.11
git-graph|mhu|1.28.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.160.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.2.1
powershell|ms-|2020.6.0
vscode-js-profile-flame|ms-|0.0.14
debugger-for-chrome|msj|4.12.12
vscode-paste-image|mus|1.0.4
gradle-language|nac|0.2.3
polacode|pnp|0.3.4
java|red|0.75.0
vscode-yaml|red|0.15.0
datetime|rid|2.0.1
rust|rus|0.7.8
multi-command|ryu|1.5.0
scala|sca|0.5.1
code-settings-sync|Sha|3.4.3
vscode-autohide|sir|1.0.7
markdown-links|tch|0.8.0
ayu|tea|0.20.1
vscode-lldb|vad|1.6.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
org-mode|vsc|1.0.0
vim|vsc|1.18.9
debug|web|0.25.0
markdown-all-in-one|yzh|3.4.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
coreuntitledfile:30249963
openwslfolder:30257850

```

</details>

**Comment by ICULikeMac** [comment]
Was there ever a fix to this? I cannot get png's showing in pycharm or visual code? Thanks
