### ISSUE TITLE
Doesn't open file via 'Open File'

### ISSUE THREAD

**Issue by mvoidex** [microsoft/vscode#116858]
Issue Type: <b>Bug</b>

I'm using VSCode remotely with mounted repo on remote host.
Build system produces logs in a long path, for example: `/home/voidex/arcadia/maps/analyzer/sandbox/eta_prediction/online_eta_quality/tests/test-results/py3test/testing_out_stuff/test.py.test_integration.log`

I press `Ctrl+O`, paste this line to input, then click `OK` or press `Enter`.

Expected result: file opened
Actual result: one of suggestions opened or nothing opened. See gif attached: https://gifyu.com/image/VYtq (or download gif [here](https://yadi.sk/i/67frLYwCv73Pgw))

I have to repeat open command 3-4 times to get correct file opened.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.171-70.1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.54GB free)|
|Process Argv|--crash-reporter-id 3c02e466-3797-46e2-b99c-dac1cb742a58|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ain|
|OS|Linux x64 4.4.171-70.1|
|CPUs|Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz (64 x 2095)|
|Memory (System)|124.93GB (13.48GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
cython|tcw|0.1.0
Bookmarks|ale|13.0.1
insert-unicode|bru|0.10.0
vscode-todo-plus|fab|4.18.2
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
cpptools|ms-|1.2.1
vscode-yandex-arc|per|0.7.0
plsql-language|xyz|1.8.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30251590

```

</details>

**Comment by weinand** [comment]
[@mvoidex FYI: you can just paste your images into github comments. You don't have to embed links to images hosted somewhere else].
