### ISSUE TITLE
New notebook error output item mime type doesn't render.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#116819]
- VS Code Version: 1.54.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Construct and display a `NotebookCellOutputItem` with a mime type of `application/x.notebook.error-traceback` and a value of type string.

Result:
The error text is not displayed:
![image](https://user-images.githubusercontent.com/926281/108142178-183e7700-707a-11eb-97e7-5441b7bb2352.png)

Expected:
The error text should be displayed.  Note that if the mime type `text/plain` is substituted, then the display appears:
![image](https://user-images.githubusercontent.com/926281/108142241-3dcb8080-707a-11eb-83be-6dba1e3df1b1.png)

The .NET Interactive extension currently sets the mime type to `text/plain` to force it to display, but by replacing [this line](https://github.com/dotnet/interactive/blob/c3b9a2ad2c24dbb48bd73a5267f4515643575d92/src/dotnet-interactive-vscode/src/vscode/insiders/src/functions.ts#L14) with the following, the display disappears:

``` diff
 const metadata = { mimeType };
-const newMimeType = mimeType === interfaces.ErrorOutputMimeType ? 'text/plain' : mimeType;
+const newMimeType = mimeType; // keep it as `application/x.notebook.error-traceback`
 return new vscode.NotebookCellOutputItem(newMimeType, value, metadata);
```

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
As discussed offline, the output value should be `{ ename, evalue, traceback }`
