### ISSUE TITLE
Window scrolls up as I type

### ISSUE THREAD

**Issue by darrow97** [microsoft/vscode#116893]
Issue Type: <b>Bug</b>

My editor window scrolls up as I type. It is similar to this issue https://github.com/Microsoft/vscode/issues/65504, with the exception of using a markdown language. I am coding in Elm.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.85GB free)|
|Process Argv|--crash-reporter-id db88d16c-e0bf-41c0-ac1c-fc401aa25f1e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
elm-ls-vscode|elm|2.0.3
python|ms-|2021.1.502429796
jupyter|ms-|2021.2.0
vsliveshare|ms-|1.0.3784
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-maven|vsc|0.27.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Do you have any "preview" tabs open?

**Comment by darrow97** [comment]
It is not reproducible with all the extensions disabled.
That makes me think it has something to do with the Elm extension... That being said, the scroll-as-I-type does not occur 100% of the type... probably more like 80% of the time.

**Comment by weinand** [comment]
Please file issue against Elm extension.
