### ISSUE TITLE
Default Keybind Mapping for action.toggleMaximizedPannel

### ISSUE THREAD

**Issue by RabinSamaroo** [microsoft/vscode#116891]
Seeing as how `ctrl+j` toggles the terminal/debug panel, a good fit to maximize the panel (`workbench.action.toggleMaximizedPanel`) would be `ctrl+alt+j`.

When trying to quickly glance at an error message this hotkey would fit right in with the current hotkeys. Let me know what you think

**Comment by sbatten** [comment]
feel free to assign this keybinding yourself, but I think we should reserve assigning keybindings by default to heavily used commands
