### ISSUE TITLE
Pasting via right click gives bad error when clipboard.readText isn't supported

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#116801]
Repro:

1. Open a Codespace in Firefox
2. Copy something from editor
3. Set `"terminal.integrated.rightClickBehavior": "paste"`
3. Open terminal
4. Right click to paste

![image](https://user-images.githubusercontent.com/2193314/108112278-b74b7a80-704a-11eb-8d23-2f5d9974b742.png)

Fixed in https://github.com/microsoft/vscode/commit/197f453aa9560872370e4b8e4b3b2f9a93c4ad68 with a better message

**Comment by sandyarmstrong** [comment]
Maybe also add "Try ctrl-v" (or whatever the platform shortcut is) to the message, since that apparently works?
