### ISSUE TITLE
Invalid path when dragging files into terminal

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#116822]
Issue Type: <b>Bug</b>

When dragging files that contain spaces into the VSCode terminal, spaces are escaped AND the path is quoted.

### Example
Dragging the following file into the terminal:
```
/Users/kasper/Downloads/Example file.mp3
```
Results in this:
```
'/Users/kasper/Downloads/Example\ file.mp3'
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|-psn_0_4953273 --crash-reporter-id ae7777ee-c64c-4b3e-aa57-8ec8dc4c2a8f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
stylus|Ala|0.0.4
svelte-intellisense|ard|0.7.1
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.15
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.23.1
sass-lint|gle|1.0.6
go|gol|0.22.1
gc-excelviewer|Gra|3.0.41
vscode-edit-csv|jan|0.5.4
eml|lei|0.4.0
node-module-intellisense|lei|1.5.0
coffeelinter|lky|1.4.0
git-graph|mhu|1.28.0
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.10.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
remote-wsl|ms-|0.53.4
hexeditor|ms-|1.4.0
debugger-for-chrome|msj|4.12.12
gradle-language|nac|0.2.3
color-highlight|nau|2.3.0
vetur|oct|0.32.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
color-manager|roy|0.6.1
rust|rus|0.7.8
crates|ser|0.5.6
stylelint|shi|0.51.0
fish-vscode|sky|0.2.1
svelte-vscode|sve|104.4.1
sass-indented|syl|1.8.15
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.11
quokka-vscode|Wal|1.0.343
HCL|who|0.0.5
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15
vscode-open-in-github|ziy|1.3.6

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by meganrogge** [comment]
related to #116583
