### ISSUE TITLE
I CANNOT WRITE IN LANGUAGE EYES

### ISSUE THREAD

**Issue by JanettePalacios** [microsoft/vscode#116867]
Issue Type: <b>Bug</b>

The program does not let me write on any sheet of any language in what respects to search for downloads and dmas everything fine, including writing.

it just won't let me write in the files where it is programmed, I can't do anything, I already uninstalled it and reinstalled it, restart and everything but nothing still doesn't solve my problem.

What I can do?
please help.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.40GB free)|
|Process Argv|--crash-reporter-id 898dcc2b-ce9d-49b2-a521-37723afbf3e9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ng-template|Ang|11.2.1
vscode-intelephense-client|bme|1.6.3
vscode-css-modules|cli|0.2.3
dart-code|Dar|3.19.2
vscode-eslint|dba|2.1.14
css-minify|Die|0.1.13
es7-react-js-snippets|dsz|3.1.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.2
go|gol|0.22.1
vscode-drawio|hed|1.3.0
html-tag-wrapper|hwe|0.2.3
icon-fonts|idl|2.4.0
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
css-snippets|joy|1.0.2
kite|kit|0.140.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-language-babel|mgm|0.0.30
dotenv|mik|1.0.1
vscode-azurefunctions|ms-|1.2.1
vscode-docker|ms-|1.10.0
vscode-language-pack-es|MS-|1.53.2
mssql|ms-|1.10.1
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
azure-account|ms-|0.9.6
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular-console|nrw|16.0.2
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.1.0
java|red|0.75.0
LiveServer|rit|5.6.1
rust|rus|0.7.8
bunker|sld|1.1.6
php-live-server|Teo|0.0.1
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vim|vsc|1.18.9
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by yorickvP** [comment]
Our best guess is that this issue is about an alternative input method (eye tracking?) failing to work in the VSCode text field (but not the other text inputs).

@JanettePalacios What device are you attempting to write with?

**Comment by IllusionMH** [comment]
I guess that it's because of Vim extension that makes most of thing to behave like Vim editor including command and edit modes
