### ISSUE TITLE
Wrong border of active markdown cell with custom renderer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#116817]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. add setting `"notebook.experimental.useMarkdownRenderer": true`
2. 
![image](https://user-images.githubusercontent.com/876920/108140532-1921d980-7077-11eb-92e2-45c356c5e3bf.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Should be fixed by #116813
