### ISSUE TITLE
Windows menu [Mac only?] add setting to change menu item order 

### ISSUE THREAD

**Issue by wshostak** [microsoft/vscode#116831]
It would be nice to have a setting to change the windows menu items order, on mac. Currently the order is **current file — workspace** but the windows menu is only useful, and convenient, for switching between workspaces allowing **workspace — current file** instead of default would make it a lot easier to use.

**Comment by sbatten** [comment]
The entries in this list are controlled by the title of the window. That value is customizable via `window.title`.
