### ISSUE TITLE
List view single click does not expand anymore

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#116804]
Issue Type: <b>Bug</b>

In latest Insiders, single click on a parent no longer expands/collapses the tree item anymore while it does in Stable.

VS Code version: Code - Insiders 1.54.0-insider (5e74ad5430203eadf89fd8e99695f4ebdb0e62ad, 2021-02-16T10:26:28.625Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.91GB free)|
|Process Argv|--crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
codespaces|Git|0.7.2
vscode-pull-request-github-insiders|Git|2021.2.22625
vscode-language-pack-zh-hans|MS-|1.53.2
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.1.502429796
jupyter|ms-|2021.1.499599561-dev
remote-containers|ms-|0.160.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
hexeditor|ms-|1.4.0
vscode-github-issue-notebooks|ms-|0.0.66
vsliveshare|ms-|1.0.3629
999-extension-update|reb|1.4.0
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
coreuntitledfile:30249963
wslfolderdoccf:30257852

```

</details>

**Comment by gjsjohnmurray** [comment]
@rebornix is this a consequence of the change described in #115873 ?

**Comment by joaomoreno** [comment]
@rebornix, as @gjsjohnmurray pointed out, this is the consequence of https://github.com/microsoft/vscode/issues/115873

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/115873#issuecomment-781967348
