### ISSUE TITLE
Editor view port jumps without a need

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#11689]
I got into a state where the editor jumps around without a need. 

I got into this state after I've inserted the `for loop` snippet.

![scroll](https://cloud.githubusercontent.com/assets/172399/18350669/37087ee4-75d7-11e6-9242-15d73a78ce5c.gif)

**Comment by alexandrudima** [comment]
@egamma Any errors in the console, do you still have this state? I've tried inserting a for loop and I didn't see anything like this.

**Comment by egamma** [comment]
It was trivial to repro, but I can no longer do it. Closing, I'll reopen, when I see the issue again.
