### ISSUE TITLE
Markdown for spinning built-in icon not working

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#116898]
Version: 1.54.0-insider
Commit: 3f0d8a14759cddea93f0dbddc12a4ef1e5586e86
Date: 2021-02-17T07:37:22.767Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

We are using the VS Code Markdown label to include a spinning icon in the status bar to show progress on one of our building processes.

To do this we set the status bar icon text to : `$(loading~spin) ${text}`

Seems that recently this spinning functionallity got broken since I don't see our status bar icon spinning anymore.
By looking at the developer tools it seems to be constructing correctly.

`<a tabindex="-1" role="button" aria-label="loading~spin $ oryx build" style=""><span class="codicon codicon-loading codicon-modifier-spin"></span> $ oryx build</a>`

Steps to Reproduce:
This is noticeable in Codespaces.

1.  Create a new codespace with a long running `postCreateCommand`
2. Once inside VS Code, look at the status bar showing the running process.

![Screen Shot 2021-02-17 at 4 21 21 PM](https://user-images.githubusercontent.com/48293249/108285590-45535e00-713c-11eb-8968-5a4afdd115f5.png)

**Comment by roblourens** [comment]
It looks like spin is only allowed for certain codicons, why is that? Need `codicon-loading` here too: https://github.com/microsoft/vscode/blob/0795762a8f02a7588cc51b1ae41520b50fe081ff/src/vs/base/browser/ui/codicons/codicon/codicon-modifiers.css#L16-L16

**Comment by misolori** [comment]
Looks like there was a typo and missed a comma when we [updated the list](https://github.com/microsoft/vscode/commit/0795762a8f02a7588cc51b1ae41520b50fe081ff#diff-ddd28eb22c29800d23b496f6982f61ae4416086782607d943f442b92ac891d49) a week ago. Fixed now.
