### ISSUE TITLE
[FR] Show number of selected characters in the left diff editor

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#116825]
Currently, only the right diff editor shows the number of selected characters:

![image](https://user-images.githubusercontent.com/28700378/108157014-c4d13500-711c-11eb-96ad-54289b280146.png)

I hope we could do that in the left diff editor as well:

![image](https://user-images.githubusercontent.com/28700378/108157079-e8947b00-711c-11eb-880b-617d54bac3ec.png)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/116011
