### ISSUE TITLE
Can not assign "Show Opened Editors" command to a keyboard shortcut

### ISSUE THREAD

**Issue by weijarz** [Microsoft/vscode#11685]
- VSCode Version: 1.4
- OS Version: Linux

The commnd is described here: <https://code.visualstudio.com/docs/editor/tabs>

> When you have more open items than can fit in the title area, you can use the **Show Opened Editors** command (available through the ... More button) to display a dropdown of tabbed items.

But this command is not shown in the command list, and can't assign a shortcut to it.

**Comment by bpasero** [comment]
<img width="743" alt="screen shot 2016-09-08 at 13 56 38" src="https://cloud.githubusercontent.com/assets/900690/18348527/16373dfa-75cc-11e6-98da-7b64992d1aad.png">

In the command list this is: Show All Editors

**Comment by lukeaus** [comment]
Actually the ShowAllEditors command shows all editors from **all** panes, whereas in the screenshot above the "Show Opened Editors" only shows the opened editors from the **current** pane. There does not appear to be a shortcut for the "Show Opened Editors" in this pane, as per the screenshot above.

I do prefer the "workbench.action.showAllEditors" (i.e. from all panes) so I will be using that!

Thanks
