### ISSUE TITLE
Sub menus by extensions in explorer context menus,item menus

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#11682]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
![Uploading _$CQ1XEFL8S{Q{R_R)_P3E5.png…]()

2. 
This extension adds two new context menus to the Explorer Viewlet:

Open New Workbench Here: Opens a new instance of VS Code scoped to the selected folder OR to the folder containing the selected file.
Reopen Workbench Here: Reopens VS Code scoped to the selected folder. This feature only works on folders, it has no effect when a file is selected. 
now i want to add two new context menus to the Open New Workbench Here how do i do @

**Comment by ramya-rao-a** [comment]
Sub Menus are tracked in #9827
