### ISSUE TITLE
Webviews can prevent keyboard shortcuts from working in quick picks

### ISSUE THREAD

**Issue by tspence** [microsoft/vscode#116897]
- VS Code Version: 1.50
- OS Version: Windows 10 && Mac OSX Catalina

Steps to Reproduce:

1. Open a full-editor webview in the main editor area
2. Open a text file in the editor
3. Close the text file using a keyboard shortcut (Cmd+W or Ctrl+F4); the full-editor webview should now receive focus
4. Press Cmd+P to open the quick-pick file selector
5. Select a file from the quick pick editor; VS Code will jump you to that file
6. While editing this file, press Cmd+P again to open the quick-pick file selector

Expected Results:
* I can use keyboard shortcuts for Cut / Copy / Paste while in the quick pick editor

Actual Results:
* All keyboard shortcuts are disabled in this quick pick window.

Root Cause:
During step 5 of the reproduction, VS Code switches focus to the code file you selected from the quick pick.  Additionally, a delayed action fires as the quick pick closes.  The delayed action tells the system to return focus to the element that previously had focus, which was the full-editor webview.

The full-editor webview thinks it has focus, and as a result it absorbs all cut/copy/paste commands that are defined in webview.contribution.ts.

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Looks like you are on an old VS Code version. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by tspence** [comment]
@mjbvz I've been working on this in the Facebook build of VS Code, and we're usually a release or two behind.  Prior to submitting this, we tried checking the latest branches to see if there were any changes in the pipeline that would fix it for us.

I tried pulling in this change into my current branch, which seemed very promising:
https://github.com/microsoft/vscode/commit/aa73c2d435d45dcee7f843164a2b7f8a0018e3d6#diff-d290cb6d05c11d900910c208855317e2ba58816f563a4c2a6fd781564381e68e

Unfortunately, this change by itself didn't fix the problem, but it was that change that helped me identify that the root cause was the difference between `document.activeElement` and `webview.isFocused`.  @evangrayk and I spent some time reviewing possible fixes before we decided to submit it upstream to you.

Let me know if you'd like me to record a walkthrough on a different build :)

**Comment by mjbvz** [comment]
Yes as a starting point, please test using the insiders VS Code release to see if this happens there as well. Then you will know if there are commits or not that would fix this issue for your custom VS Code build

**Comment by mjbvz** [comment]
Reverted due to a regression: #117595. Reopening

**Comment by tspence** [comment]
Thanks for the feedback!  I'll investigate and see what's happening here.

**Comment by tspence** [comment]
Re-developing a fix for this now.  I think the original idea of "check to see if a webview really has focus" was the wrong approach.  As documented in #117595 there are cases where a webview has focus but there is a DOM tree of elements and it is not always clear whether that indicates a problem.

The next test we are developing involves:
* Add blur() method to webviews
* When the editor group view service shows an editor, notify the currently active webview (if there is one) that it has lost focus

In testing, this works correctly in the following scenarios:
* Focus is currently on a webview, then use a quick-pick to jump to an editor window.  Result: Showing the editor window removes focus from the webview.
* Focus is on a webview and you use keyboard navigation to tab through it.  Result: Webview retains focus even when navigating through a tree of elements.

We are going to test this more internally before we submit a second patch.
