### ISSUE TITLE
Copy logged objects from debug console.

### ISSUE THREAD

**Issue by tophmey** [microsoft/vscode#116883]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by having to select individual properties of objects to share values with someone else. I'd like to be able to share dynamically constructed objects in node.js, by copying a logged value and pasting it somewhere else.

**Describe the feature you'd like**
When using console.log or logpoints, I can inspect an object in the debug console, but right clicking the object and selecting "copy" does nothing. I can select part of a string and copy, but I'd like to be able to right click the logged value (arg1 from a logpoint) and select "copy" or "copy value",  as I could by copying from variables in the debug sidebar or using copy() in the debug REPL if I was paused in a breakpoint.

**Comment by connor4312** [comment]
This is something debuggers could support automatically if there was a "copy" context menu action on items in the console that used the existing copy mechanism on the variablesReference of the associated data.

**Comment by isidorn** [comment]
There is already a `Copy` in the context menu, however that `Copy` only works on selection.
So we could improve it: if there is no selection -> we check the row where the user clicked and we then use the existing copy mechanism using the `variableReference` as the Copy Value action does [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/variablesView.ts#L416)

@connor4312 let me know what you think

![Screenshot 2021-02-18 at 09 49 53](https://user-images.githubusercontent.com/1926584/108331064-aaf02a80-71ce-11eb-8555-b702d2bcfe46.png)

**Comment by connor4312** [comment]
That would be perfect 🙂

**Comment by isidorn** [comment]
Ok, let me assign optimistically to this milestone to look into this.
If I do not find time, I will push out to March.

**Comment by isidorn** [comment]
I have pushed a simple approach which I think will work nicely: if there is no selection we will just copy the whole `element.toString()`.
I do not send an evaluation request to the adapter because this should not only copy the value of the variable for example but the name + value.
Anyways try it out and let me know how it goes.

Marking this as a bug so the endgame police does not arrest me for pushing "feature requests" this late in the release.

**Comment by tophmey** [comment]
I just tried this in the February update, and unfortunately it's not working as expected in Windows.

Right clicking a logged inspectable value from the Debug Console and clicking Copy just copies the printed line, not the underlying value, as opposed to using "Copy" in the REPL which gives you the whole value as a string. 

Here is a gif:

![116883](https://user-images.githubusercontent.com/589529/110137369-63ed6200-7d96-11eb-8d53-d9fd466109e3.gif)

**Comment by isidorn** [comment]
Thanks for trying it out, however next time it would be great if you can try it out with vscode insiders.
Now I would not change this feature, as the Copy behaves as copy line. Not evaluate than copy content - which you would like.
If we get more requests that the copy should evaluate then I would be open to changing it

**Comment by tophmey** [comment]
Thanks. Unfortunately, I'm not able to run VS Code Insiders on my Windows machine. I understand, not wanting to change the behavior that was released, what about a feature request for a "Copy Value" option in the context menu? As it turns out, I'm not sure that I'm able to get this to work on macOS either as right clicking the line automatically selects the text underneath the click, anyway. Seems like a dedicated "Copy Value" might be the best approach after all?

**Comment by isidorn** [comment]
Copy Value in the context menu makes sense. I would probably tackle that by opening up the debug console context menu for extensions so then the js-debug could add this if it wants.

**Comment by tophmey** [comment]
Should I create a separate feature request for opening up the debug console context menu for extensions?

**Comment by tophmey** [comment]
Also, thank you so much for your effort and attention here. I really appreciate it.

**Comment by isidorn** [comment]
Yes, please do. Thank you.

**Comment by tophmey** [comment]
Thanks again! Here's the new issue, if you'd like to check it out:

https://github.com/microsoft/vscode/issues/118230
