### ISSUE TITLE
Source Control, "Repository from Here in New Window" does not work

### ISSUE THREAD

**Issue by rollingage** [microsoft/vscode#116828]
Issue Type: <b>Bug</b>

1. Clone a repository
2. Open Source Control tab
3. Open "COMMITS" tab
4. Right click an old commit, -> Browse -> "Repository from Here in New Window"

Expected:
The repository commit was opened in a new VS Code window

Actual:
A new VS Code window was opened, but it's empty

Note, "Repository from Here" works.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21286
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (0.92GB free)|
|Process Argv|--crash-reporter-id cc698249-6adb-490a-8e0d-1860e3d606cc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (1.16GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (1.16GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|7.73GB (1.16GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
es7-react-js-snippets|dsz|3.1.0
vscode-react-typescript|inf|1.3.1
vscode-ai-remote|ms-|0.1.0
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
snapshot-tools|asv|0.4.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
vscode-docker|ms-|1.10.0
python|ms-|2021.1.502429796
jupyter|ms-|2020.12.414227025
vscode-ai|ms-|0.6.20
vscode-ai-remote|ms-|0.1.0
azure-account|ms-|0.9.6
advanced-new-file|pat|1.2.2
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt875:30251590

```

</details>

**Comment by gjsjohnmurray** [comment]
Is that command contributed by the GitLens extension you have installed? If so please report the issue on the extension's repository. VS Code's 'Report Issue' dialog (see Help menu) makes doing that easy.
