### ISSUE TITLE
Code Settings Sync - Jumps to "OUTPUT" Tab

### ISSUE THREAD

**Issue by imt-telliott** [microsoft/vscode#116878]
Issue Type: <b>Bug</b>

- Enable Code Settings Sync w/ Github
- Open integrated terminal
- Wait X amount of time for next settings sync

Actual:

The focused tab is switched from the terminal to the "OUTPUT" tab and the "CODE SETTINGS SYNC UPLOAD SUMMARY" is displayed. This happens even when the "OUTPUT" tab is hidden.

Expected:
I'm unsure I have the appropriate answer for this, but it is a bit jarring to be in the middle of using the terminal and abruptly switching tabs. 

Perhaps instead of switching tabs it can display an indicator of sorts.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id dfe8b280-b627-4e46-b990-c19376ec1adb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.1
swagger-viewer|Arj|3.0.1
vscode-django|bat|1.3.0
vscode-custom-css|be5|4.0.1
vscode-intelephense-client|bme|1.6.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-phpmd|eco|1.2.0
vscode-great-icons|emm|2.1.64
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
file-icons|fil|1.0.28
code-runner|for|0.11.2
format-python-docstrings|ian|1.2.1
phpcs|ika|1.0.5
php-cs-fixer|jun|0.1.158
vscode-simple-icons|Lau|1.13.5
bash-ide-vscode|mad|1.11.0
MagicPython|mag|1.1.0
vscode-docker|ms-|1.10.0
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
vscode-remote-extensionpack|ms-|0.20.0
vsliveshare|ms-|1.0.3629
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
php-docblocker|nei|2.1.0
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.15.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.16
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
jinja|who|0.0.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by sandy081** [comment]
Please file issue against code settings sync extension
