### ISSUE TITLE
File get's saved when run

### ISSUE THREAD

**Issue by pjaden** [microsoft/vscode#116871]
Version 1.53.2
Setting "Auto Save" to "off" does not work.  Any change made to edit windows will force a file save.
Version 1.52.1 works.

**Comment by bpasero** [comment]
Can you check what you have configured in settings exactly? Maybe you configured it in workspace settings?

**Comment by pjaden** [comment]
Here’s what I’ve tried today.

Created a new clean Windows 10 Enterprise VM, I installed VSCode 1.53.2.
Then within VSCode, Powershell Preview 2020.9.0. package.

Ctrl, (Open Settings)  = Files:Auto Save = off

I did not have a workspace.json file because I have never made any changes.

There are only 4 .json files in my Roaming\Code folders: 
rapid_render.json
storage.json
languagepacks.json
Backups\workspaces.JSON

I check settings Ctrl+,   Auto Save = off.  (I have never changed any settings with this setup.)

I created a PowerShell test file, Test.ps1 on my desktop and open it with VSCode.
The Test.ps1 file contained: 
Write-Output ‘Testing’
# 

I also created a “Test.txt” file with the word “Hello” in it.  I opened it with VSCode and added a character to the file to make it dirty.
I also added a character in the comment line of the PowerShell file to make it dirty.

I then do Ctrl-F5 (i.e. Run without Debug).
Both files were saved before running the PowerShell file, then it runs within the terminal without errors.

This says that Auto Save is “on” in all cases.

I have an earlier VSCode Version 1.52.1 on another computer, set up the same way that works fine, i.e. it does NOT save the file before executing it.

If I close VSCode with dirty files.  They stay dirty, i.e. when I open VSCode again the file remains dirty.

Running the PowerShell file causes it to be saved first.  This is not the previous behavior.

Thanks for your help!

**Comment by bpasero** [comment]
Ok so this seems to be debug related then:

> Running the PowerShell file causes it to be saved first. This is not the previous behavior.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/114890
