### ISSUE TITLE
ошибка в терминале 

### ISSUE THREAD

**Issue by SEMESNOV** [microsoft/vscode#116802]
& : Имя "C:/Users/Семен ванов/AppData/Local/Programs/Python/Python38-32/python.exe" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильно 
сть пути, после чего повторите попытку.
строка:1 знак:3
+ & "C:/Users/Семен ванов/AppData/Local/Programs/Python/Python38-32/pyt ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:/Users/Семен ...8-32/python.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
![image](https://user-images.githubusercontent.com/79168335/108114012-4d15f280-70a9-11eb-99c8-d6b8af50c141.png)

**Comment by rzhao271** [comment]
This seems like an issue with the Python extension.

First, try running the command `python.setInterpreter` in the Command Palette (F1) and choosing another interpreter.

If that doesn't work, please file an issue with https://github.com/Microsoft/vscode-python.
