### ISSUE TITLE
Jupyter Notebook doesn't load on Insiders 1.54.0 updated today (Apple Silicon)

### ISSUE THREAD

**Issue by goncalolalmeida** [microsoft/vscode#116868]
- VS Code Version: 1.54
- OS Version: macOS 11.2 (Apple Silicon)

Steps to Reproduce:

1. Open some file *.ipynb
2. It won't load the notebook
3. Error given on a specific notebook: https://imgur.com/a/IAtNoIH 
4. Not all notebooks give this error, instead they simply keep loading (and somehow they can't)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
Possible duplicate of #116844 but your message is different.

Tip 1: open issue reports from Help\Report Issue and they will automatically include your exact version and platform details.
Tip 2: images can be dropped/pasted direct into GH. No need to use an external site which some people may not want to visit.

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/116844
