### ISSUE TITLE
Extension keybindings with false "when" conditions still change the top level app shortcut keys

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#116882]
- VS Code Version: 1.53.2 (also repros in current Insiders)
- OS Version: macOS Big Sur 11.2 (also repros on Windows 10)

Steps to Reproduce:

1. Download the vscode-extensions-samples repo
2. Open and build the helloworld-sample extension
3. Open package.json for that extension
4. Add the following keybinding block into that extension contributes section
```
                "keybindings": [
			{
        		"key": "ctrl+shift+alt+s",
				"when": "!editorTextFocus && editorTextFocus",  // Exact when doesn't matter here as much as getting something false
				"command": "workbench.action.files.save"
			}
		],
```
5. Launch the extension to debug VS Code (initially I though that you had to activate helloworld, but it seems to happen just on loading vs code)
6. Open up the VS Code top level file menu
7. 
![image](https://user-images.githubusercontent.com/812783/108274238-770ef980-7129-11eb-9ea6-c91f49776270.png)
8. The top level VS Code menu has the contributed keybinding for save, even if the when condition is false

Ran into this while working with our extension. It might be intentional? The contribution documents here do mention that UI elements would be updated:
https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings
However it did seem wrong that the UI elements would be updated before activation and updated regardless of the state of the when condition associated with the keybinding. I would expect that the keybinding would only apply and update UI elements if the when was true.

Does this issue occur when all extensions are disabled?: No, because it requires an extension to contribute a keybinding.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/40389
