### ISSUE TITLE
Problema ao salvar configurações

### ISSUE THREAD

**Issue by gbsant** [microsoft/vscode#116854]
Quando realizo alguma alteração nas configurações o app sempre apresenta um erro dizendo "Não é possível gravar nas configurações do usuário. Abras as configurações do usuário para corrigir erros/avisos e tente novamente."
![Screenshot_1](https://user-images.githubusercontent.com/72055515/108221070-27730280-7116-11eb-90d3-911168d4f6a1.png)

**Comment by rzhao271** [comment]
If you click on the button in the error notification, does it take you back to the user settings? If so, are there any JSON errors within those settings?
