### ISSUE TITLE
About splitting the terminal

### ISSUE THREAD

**Issue by Magkinh** [microsoft/vscode#116833]
Issue Type: <b>Feature Request</b>

Not just the horizontal you want to split vertically

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment]
You can do this by running the command `Move Panel Right` and then splitting the terminals.
