### ISSUE TITLE
Select and Start Debugging missing

### ISSUE THREAD

**Issue by cdacamar** [microsoft/vscode#116800]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open directory with a simple .cpp file.
2. Add launch.json.
3. Add at least two configurations.
4. `ctrl+shift+P` (no option to select configuration).

Does this issue occur when all extensions are disabled?: Yes

**Comment by ArturoDent** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/116299  Fixed in Insiders already.

**Comment by cdacamar** [comment]
Are there any workarounds in the current released version?
