### ISSUE TITLE
Keyboard short cut for switching between Integrated terminals

### ISSUE THREAD

**Issue by rkrgithub** [microsoft/vscode#116890]
Issue Type: <b>Feature Request</b>

Keyboard short cut for switching between Integrated terminals is required

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment]
set a keybinding for `workbench.action.terminal.focusNext` also known as `Terminal: Focus Next Terminal`

**Comment by meganrogge** [comment]
for example:
`{ "key": "ctrl+shift+j", "command": "workbench.action.terminal.focusNext" }`

**Comment by rkrgithub** [comment]
What if we provide a key binding by default for this?
