### ISSUE TITLE
Incorrect PHP 8 attributes syntax highlight

### ISSUE THREAD

**Issue by juanrgm** [microsoft/vscode#116847]
- VS Code Version: 1.52.1

Steps to Reproduce:

```php
<?php

#[Attribute]
class Test {
	function __construct(array $data) {}
}

$data = [
    'value' => true
];

function method1(#[Test(['value' => true])] $data) {}

function method2(
	#[Test(['value' => true])]
	$data
) {}

function method3(
	#[Test([
        	'value' => true
	])]
	$data
) {}
```

![php-attribute-screen](https://user-images.githubusercontent.com/54169354/108202820-fa2c5180-7121-11eb-9107-6be15328959d.PNG)

**Comment by danny007in** [comment]
at line number 20-23 syntax is wrong 😃

**Comment by juanrgm** [comment]
> at line number 20-23 syntax is wrong 😃

That code runs correctly in PHP 8 (https://sandbox.onlinephpfunctions.com/code/85bb5e77242fadee33796497bd9ac036fe0a38f7).

**Comment by juanrgm** [comment]
The syntax highlight is broken when you use an attribute and write code in the same line (method1) but also is incorrect when you write code in a param (method2) or you use line break (method3).

**Comment by roblourens** [comment]
Noticed that this is better in the latest version of vscode, but they are missing tokens to be fully colored. Filed https://github.com/atom/language-php/issues/415
