### ISSUE TITLE
Panel tabs cut off unnecessarily

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#116872]
Feel like this has to be pretty new, I cant see all my panel tabs unless I close the sidebar, even though there's plenty of space. This is only if the debug panel is open

![image](https://user-images.githubusercontent.com/8586769/108259308-c9deb600-7115-11eb-98b8-6f4e2eb29e8a.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/116423
