### ISSUE TITLE
Is it possible to set the color of the content output from the VS Code internal terminal?

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode#116832]
In VS Code, the content of its internal terminal is all white, which is not convenient to distinguish the path and output result. Can the color of the terminal output result be set separately to distinguish it?

![image](https://user-images.githubusercontent.com/61971386/108167061-1636ef80-7130-11eb-9985-44d0c070ff6d.png)

Thanks a lot!

**Comment by meganrogge** [comment]
You can set terminal colors like this in your settings.json

```
"terminal.background":"#20201D",
"terminal.foreground":"#A6A28C",
"terminalCursor.background":"#A6A28C",
"terminalCursor.foreground":"#A6A28C",
"terminal.ansiBlack":"#20201D",
"terminal.ansiBlue":"#6684E1",
"terminal.ansiBrightBlack":"#7D7A68",
"terminal.ansiBrightBlue":"#6684E1",
"terminal.ansiBrightCyan":"#1FAD83",
"terminal.ansiBrightGreen":"#60AC39",
"terminal.ansiBrightMagenta":"#B854D4",
"terminal.ansiBrightRed":"#D73737",
"terminal.ansiBrightWhite":"#FEFBEC",
"terminal.ansiBrightYellow":"#AE9513",
"terminal.ansiCyan":"#1FAD83",
"terminal.ansiGreen":"#60AC39",
"terminal.ansiMagenta":"#B854D4",
"terminal.ansiRed":"#D73737",
"terminal.ansiWhite":"#A6A28C",
"terminal.ansiYellow":"#AE9513"
```

**Comment by Jill-Cheng** [comment]
No, I mean just change the color of the output result to distinguish it from the color of the path.

**Comment by meganrogge** [comment]
It's not possible to just set the color of the output

**Comment by Jill-Cheng** [comment]
Okay, thank you very much!
