### ISSUE TITLE
Can't write Vietnamese text in editor with UniKey software

### ISSUE THREAD

**Issue by lyquocnam** [Microsoft/vscode#1168]
this not for vietnamese programer ? i can not write vietnamese language: "Tôi yêu Việt Nam" on editor, please fix !

**Comment by thyeun** [comment]
i been try to copy and paste "Tôi yêu Việt Nam" into VS code, i manage to save it with the change from encoding from others language to UTF-8

will you possible to change the encoding from your current language to UTF-8 inside VS code? because i been using version 0.10.3 VS code for chinese language and korea language with UTF-8.

hope this might be helping you!!

**Comment by egamma** [comment]
@alexandrudima fyi.

**Comment by alexandrudima** [comment]
@lyquocnam Can you please provide more details:
 * what is your OS
 * Is there a problem with typing vietnamese (i.e. if you paste the text, does it work)
 * Is there a problem with opening a file containing vietnamese (econding or font rendering)

**Comment by lyquocnam** [comment]
it work only for copy and paste, but can not write directly 
vietnamse people use this tool to write vietnamse character: http://unikey.vn/vietnam/
but any special char: ê, ô, í, ì... has been removed.. 
I'm using windows 10 and lastes version of VSCode.
i tested on utf-8 new file. :(

**Comment by alexandrudima** [comment]
Relevant video from @lyquocnam : https://youtu.be/Hb4tLqiyuNs

**Comment by alexandrudima** [comment]
Steps for those not familiar with the software:
* install [UniKey](http://www.unikey.org/bdownload.php#uk)
* click the Thu nhô button
* get the following settings:
![image](https://cloud.githubusercontent.com/assets/5047891/12548960/93727266-c362-11e5-8e17-f7e3cf589ffc.png)

* From the taskbar (next to the date) click on its small icon to toggle on Vietnamese mode (you should get a V)
* Type Tooi => it should transform to => Tôi

**Comment by EmYeuCoGiao** [comment]
I still can't type
When i type oo => it should transform to => null not ô
same, I type Tooi => Ti, not Tôi
![screenshot 4](https://cloud.githubusercontent.com/assets/14220005/12549173/fb9d0c40-c38d-11e5-8d5d-f36177882449.png)

**Comment by alexandrudima** [comment]
@EmYeuCoGiao The fix will be in the January update.
