### ISSUE TITLE
Light color theme not persisted on macOS

### ISSUE THREAD

**Issue by marcheimendinger** [microsoft/vscode#116866]
Issue Type: <b>Bug</b>

It looks like the light color theme is not persisted after auto-switching to Dark and then back again to Light.

1. Set macOS appearance mode to "Auto" (in General tab of System Preferences).
2. Set a custom Color Theme in VS Code (different from the default "Light+").
3. Wait for macOS to auto-switch to dark appearance and back again to light appearance.
→ You'll see the Color Theme in VS Code is now back to the default "Light+" theme.

You can emulate the auto-switchting appearance mode of macOS using this JS script (for whatever reason, the described issue does not appear to be present using the System Preferences buttons "Light" and "Dark" from the General tab, you absolutely have to set it to "Auto"):
```js
function run(args) {
    var systemEvents = Application("System Events")
    systemEvents.appearancePreferences.darkMode = !systemEvents.appearancePreferences.darkMode()
}
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (8.11GB free)|
|Process Argv|--crash-reporter-id 9bb3d03b-b919-4d3e-852b-0ee1dfa38dee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
color-info|bie|0.5.1
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
vscode-html-css|ecm|1.10.2
LogFileHighlighter|emi|2.11.0
nasc-touchbar|fel|1.12.0
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-comment-blocks|kev|1.0.1
vscode-moodle-snippets|Mat|1.0.346
php-docblocker|nei|2.1.0
sails-js-snippets|Osi|2.1.0
format-html-in-php|rif|1.7.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscode-counter|uct|2.2.2
markdown-pdf|yza|1.4.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by aeschli** [comment]
We have the setting `workbench.preferredLightColorTheme` that is used when the Light OS scheme is detected.

`Specifies the preferred color theme for light OS appearance when Window: Auto Detect Color Scheme is enabled.`

You need to set this to your preferred light theme.
