### ISSUE TITLE
Add Ability to Hide Certain Tasks

### ISSUE THREAD

**Issue by herrberk** [microsoft/vscode#116892]
We have a variety of VSCode Tasks that are run as part of Debug targets via `PreLaunchTask` and these tasks pollute the dropdown list making it difficult to find other tasks. It would be super helpful if we could hide them. Here is my proposition:

```
{
            "label": "build task for launch target",
      ----> "hidden": true,
            "type": "shell",
            "command": "bash build.sh",
            "problemMatcher": []
}
```
or
```
{
            "label": "build task for launch target",
            "options": {
           ----> "hidden": true
             },
            "type": "shell",
            "command": "bash build.sh",
            "problemMatcher": []
}
```

Thoughts?

**Comment by gjsjohnmurray** [comment]
Previously requested in #110928 which failed to attract enough upvotes.

**Comment by alexr00** [comment]
Thanks for the duplicate pointer @gjsjohnmurray . Closing as a duplicate.
