### ISSUE TITLE
Unable to use Right click to paste into terminal in Windows app

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#116850]
Issue Type: <b>Bug</b>

Looks like feature detection is broken in latest Insiders builds.

Steps to reproduce:
1. Set `"terminal.integrated.rightClickBehavior"` to `"copyPaste"` or `"paste"`
1. Open terminal
1. Do right click in terminal view with mouse

Notification "This browser doesn't support the clipboard.readText API needed to trigger a paste" appears.

Root cause is added check in https://github.com/microsoft/vscode/commit/197f453aa9560872370e4b8e4b3b2f9a93c4ad68 for #116801

VS Code version: Code - Insiders 1.54.0-insider (3f0d8a14759cddea93f0dbddc12a4ef1e5586e86, 2021-02-17T07:39:48.715Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (16.88GB free)|
|Process Argv|--crash-reporter-id cf52dbde-2c94-45c3-9bf3-45d8b9966b04|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt600cf:30251589
core-portspanel:30257802
coreuntitledfile:30249963
wslfolderdoccf:30257852

```

</details>

**Comment by Tyriar** [comment]
Well that was a silly mistake. Thanks for the quick report!

**Comment by IllusionMH** [comment]
WOW! Thanks for swift fix.

P.S. I was thinking that Electron's Sandbox breaks feature detection 🤦‍♂️
