### ISSUE TITLE
Provide access to system capslock, numlock and scrolllock keystates through the VSCode Extension API

### ISSUE THREAD

**Issue by dominicpalmer** [microsoft/vscode#116869]
It would be useful for extension developers to be able to retrieve the keystate of capslock, numlock and scrolllock in code. This would allow VSCode extensions to implement keystate dependent functionality in any context. Example uses cases:

1. A status bar indicator for lockable keys, for those who frequently use these keys but lose track of the state. This was actually a feature request in and of itself for capslock back in 2020: https://github.com/microsoft/vscode/issues/90120
2. Keybindings that depend on the keystates, thus adding an additional layer over existing keybindings
3. Any other alteration to existing VSCode functionality depending on the individual or combined keystates

My own personal reason for this feature request is a combination of points 1 and 2 above. I currently use my own two mode keymap that is toggled system wide using numlock. However I currently have no way to get visual feedback of the mode in use when in VSCode. My end goal is to develop an extension that displays a personalised indication of the numlock state on the status bar.

**Comment by jrieken** [comment]
fyi @alexdima
