### ISSUE TITLE
App Freeze on huge JS files

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#11687]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 10.0.10586

Having multiple large (3000+ lines) JavaScript files open seems to crash the language server. The code colorization goes haywire coloring single letters randomly and the whole app freezes.
ReOpen or Wait does not work, only Close will kill the app.

**Comment by waderyan** [comment]
@con-ssc thank you for opening this issue. Do you have a repo I can clone to reproduce? We have not observed this on our end and we regularly test with many large repositories. I can't speak to the size of each file though.

**Comment by con-ssc** [comment]
No I cannot since it is for a customer. I also guess that it might have something to do with some code lens extensions and not with vscode directly maybe. I don't know how to monitor the crashes though.

**Comment by waderyan** [comment]
@con-ssc can you test your theory by running code from the command line with `--disable-extensions`

![image](https://cloud.githubusercontent.com/assets/2449568/18451237/f351354e-78ea-11e6-903a-fd3394a378c0.png)

**Comment by waderyan** [comment]
Closing until more info is provided.
