### ISSUE TITLE
VSCode integrated terminal text overlap

### ISSUE THREAD

**Issue by VincentDondain** [microsoft/vscode#116870]
# System

CPUs | Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 4, 3
Memory (System) | 64.00GB (15.64GB free)
Process Argv | --crash-reporter-id a89ac4a4-a92a-483e-9532-9b18b01d1b98
Screen Reader | no
VM | 0%

# Extensions

Extension | Author (truncated) | Version
-- | -- | --
codespaces | Git | 0.7.2
remote-containers | ms- | 0.160.0
vim | vsc | 1.18.9
codespaces | Git | 0.7.2
vscode-pull-request-github | Git | 0.23.1

# Steps to Reproduce:

In Codespaces (but don't think it's the cause) the integrated terminal text can overlap.

If you resize VSCode to a smaller screen size and type in the integrated terminal you'll have the text that keeps showing up on the same line (eventually erasing the promt and other text).

<img width="1409" alt="Screen Shot 2021-02-17 at 2 18 30 PM" src="https://user-images.githubusercontent.com/7839202/108256452-8f801380-712b-11eb-83c1-347c421f8142.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by thistlillo** [comment]
Any news on this?  I am experiencing the same problem with a remote terminal connected via ssh. It started all of a sudden after a while, with no apparent reasons. Till few days ago it was fine.

**Comment by klijakub** [comment]
I have the same problem.
