### ISSUE TITLE
"Focus on X View" command doesn't work as expected in the Remote Explorer

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#116815]
- Open Remote Explorer, select "SSH Targets"
- Run the command "Focus on Github Codespaces View"
- The Github Codespaces view is added below the SSH Targets view, when I expect it to switch to Codespaces in the dropdown

I guess this works differently for the remote explorer than every other view. I think we want this command for Codespaces though, because we want to have the remote explorer hidden by default.

**Comment by alexr00** [comment]
Now, the dropdown will correctly change when a view is shown that doesn't belong in the currently selected dropdown category.
