### ISSUE TITLE
Selection.anchor in VS Code API seems doesn't working

### ISSUE THREAD

**Issue by stunpix** [microsoft/vscode#116810]
Issue Type: <b>Bug</b>

In my extension, I'm trying to get the `Selection.anchor` position created in the editor with `Ctrl+K` and `Ctrl+B` hotkeys. For some reason `Selection.anchor` doesn't reflect the position of anchor and always reflects either the current cursor position or the start of the selection.

**Steps to reproduce**:
1. Set anchor with `Ctrl+K` and `Ctrl+B`
2. Move cursor a few lines up/down
3. Check `Selection.anchor` and `Selection.active`

**Observed**:
`Selection.anchor` is equal to `Selection.active` despite the anchor is visible on another line than the cursor.

**Expected**:
`Selection.anchor` isn't equal to `Selection.active` and points to the line where `Ctrl+K` `Ctrl+B` were pressed.

If I'll make a selection from the anchor to the current cursor position with `Ctrl+K` `Ctrl+K` then `Select.anchor` will be the same as `Selection.start` so the overall situation looks like `Selection.anchor` is useless or not working.

Perhaps I'm wrong but such behavior looks incorrect.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Ubuntu 20.04.2 Linux x64 5.8.0-43-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|15.63GB (12.92GB free)|
|Process Argv|--no-sandbox --disable-gpu --unity-launch --crash-reporter-id 64e68cf6-7dc4-49be-821a-1a73c83056e6|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.7
gitlens|eam|11.2.1
vscode-macros|EXC|1.2.0
plantuml|jeb|2.14.3
python|ms-|2021.1.502429796
vscode-pylance|ms-|2021.2.2
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.0
rewrap|stk|1.14.0
pdf|tom|1.1.0
cmake|twx|0.0.17

</details>

**Comment by jrieken** [comment]
The API for selection.anchor only comes into play when having a non empty selection, it's only partially related to the set selection anchor command. Do get a non empty selection from there you need to another command, like select from anchor to cusor

**Comment by stunpix** [comment]
@jrieken Thank you for answering my request. One more point. From my findings `selection.anchor` with non-empty selection always equals to `selection.start` or equals to `selection.active` if there is no selection so what the purpose of having `selection.anchor` in the API since it never gets its own unique values?

**Comment by jrieken** [comment]
> From my findings selection.anchor with non-empty selection always equals to selection.start or 

Or are probably selection from left to right only and never from right to left
