### ISSUE TITLE
[Getting Started] Make first page more welcoming

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#116976]
With #116570 we open to the first section when no items have been completed. This means the first screen new users see is:
![image](https://user-images.githubusercontent.com/8586769/108410315-1d1b3c00-71dc-11eb-997a-ed45776c5300.png)

This could be more welcoming... on Codespaces on the other hand the first screen will be:
![image](https://user-images.githubusercontent.com/8586769/108410659-8dc25880-71dc-11eb-91ce-51f92a38616e.png)

Which seems reasonable to me.

**Comment by JacksonKearl** [comment]
(cc @digitarald for possible content updates, @misolori for design tweaks)

**Comment by digitarald** [comment]
I had https://github.com/microsoft/vscode/issues/116580 filed for this but can close as dupe.

**Comment by JacksonKearl** [comment]
Oh sorry didn't see that one. This is a bit different now because we only ever open the first category (Codespaces / Quick Setup)

**Comment by misolori** [comment]
I was thinking maybe we could adjust the layout and add a title + move the more button, but only for when this opens as the landing page:

![image](https://user-images.githubusercontent.com/35271042/108427412-fa941d80-71f1-11eb-80ab-7953e1f35dc5.png)

**Comment by digitarald** [comment]
@misolori I like context it adds. Might be also useful if the header could stick around across index and each sections. Depending on viewport size, it could responsively shrink/grow.

**Comment by JacksonKearl** [comment]
Now that we've changed the header, this doesn't really make sense. Going to just close this out.
![image](https://user-images.githubusercontent.com/8586769/120725346-989eb180-c48a-11eb-902e-d2e4d73cf998.png)
