### ISSUE TITLE
Broke after update

### ISSUE THREAD

**Issue by JOHNNIKHIL** [microsoft/vscode#116924]
We have written the needed data into your clipboard be
Issue Type: <b>Bug</b>

Mam/Sir,
Greetings from me.
 After the update my php programs are not running anymore. Like I have idea how to fix my issue . Hope you can fix my issue.
Contact me on johnnikhil204@gmail.com

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.44GB free)|
|Process Argv|--crash-reporter-id d6e9bfe0-fe15-4d3c-8635-1c726d7cebf6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer|Coe|1.0.61
es7-react-js-snippets|dsz|3.1.0
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
php-pack|fel|1.0.2
phpcs|ika|1.0.5
react-native-snippet|jun|0.5.6
vscode-react-native|msj|1.4.0
LiveServer|rit|5.6.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

cause it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Please start Extension Bisect from Command Palette to try to discover if one of your extensions is causing the issue.

**Comment by weinand** [comment]
We can only fix your issue if we know what your issue is.

Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions to learn how to write a bug report.

**Comment by JOHNNIKHIL** [comment]
Dear Mam | Sir,
         Thank you for your response.
My issue was resolved and so thats why I pulled back the complaint...
Thanks for answering my question. Have a nice day.
