### ISSUE TITLE
window crashes when trace logging and toggle shared process 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#116979]
Steps to Reproduce:

1. Launch VS code
2. in OSS, check flow control is enabled
3. Toggle Shared Process
4. run the command: `Developer: Set Log Level` - select trace
5. In a terminal, type `tree`
6. Now click in the editor and switch between editor tabs back and forth a few times
7. See the window become unresponsive then crash

**Comment by deepak1556** [comment]
Unable to repro the issue with latest source tree.
