### ISSUE TITLE
editor.snippetSuggestions = none disables JSDoc auto generation

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#116941]
Issue Type: <b>Bug</b>

When setting `editor.snippetSuggestions` to `"none"`, the auto-completion of JSDoc comments `/** */` no longer works.

This is unexpected, because this auto-completion is not a user-authored snippet.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (33.53GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.77GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.77GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.77GB free)|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.3.1
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.1.0
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.6.0
vscode-esformatter|how|1.6.0
template-string-converter|meg|0.4.7
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.10.0
js-debug-nightly|ms-|2021.2.1017
vscode-js-profile-flame|ms-|0.0.14
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.21
speckle|rbu|1.4.3
vscode-xml|red|0.15.0
vscode-yaml|red|0.15.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> When setting editor.snippetSuggestions to "none", the auto-completion of JSDoc comments /** */ no longer works.

Yes - the "no snippets" setting applies to all suggestions that use the snippet type.

@mjbvz forwarding to you for considering to use another completion item kind

**Comment by mjbvz** [comment]
Yes I'll make it a text completion instead. If someone  really wants to disable JS Doc completions, we have a `javascript.suggest.completeJSDocs` setting
