### ISSUE TITLE
console.log() items are added to tasks list

### ISSUE THREAD

**Issue by TheColorRed** [microsoft/vscode#11699]
- VSCode Version: 1.4.0
- OS Version: Windows 10

Steps to Reproduce:
1. Create a `gulpfile.js`
2. Add `console.log()` commands

When I Add `console.log()` in my `gulpfile.js` it adds them to my task `list`

``` js
var gulp = require('gulp');

var settings = {};
try {
    settings = require('./settings.json');
    console.log('The "settings.json" file was found.');
} catch (e) {
    console.log('Could not find the "settings.json" file.');
}
var sdkpath = settings.publicSdkPath || './build';
var buildDoc = settings.buildDoc || false;
console.log('sdkpath: ' + sdkpath);
console.log('builddoc: ' + buildDoc);

// Other gulp tasks below
gulp.task('build', function(){
    // Do some stuff
});
```

![tasks-extra](https://cloud.githubusercontent.com/assets/1571806/18358893/f5b6be5c-75bc-11e6-881d-19fb747e7b17.jpg)

**Comment by dbaeumer** [comment]
There is not so much I can do about this since I can't distinguish between a task printed and a console.log statement. Gulp 4.x has a --tasks-json which I can use as soon as 4.x is more commonly used.

**Comment by TheColorRed** [comment]
I see that gulp has a autocomplete for tasks, so I tried it via command line and was having the same problem. I then opened a bug on gulp's [issue tracker](https://github.com/gulpjs/gulp/issues/2044#issuecomment-344753151) and they say to install `gulp-cli`. Would using that instead be a fix? (I am not sure what vscode is currently using)

```
npm install gulp-cli -g
```

**Comment by dbaeumer** [comment]
I first look for a local install gulp and then call the global one. So if you have gulp-cli installed globally it should be fine according to https://github.com/gulpjs/gulp/issues/2044#issuecomment-344753151

**Comment by TheColorRed** [comment]
So, I uninstalled my local and global version of `gulp` and installed a global version of `gulp-cli`, it doesn't suggest any gulp tasks at all. The only tasks it suggests are the ones in `tsconfig.json` and the ones in `package.json`.

Git bash shows this:

```
$ which gulp
/c/Users/rnaddy/AppData/Roaming/npm/gulp

$ gulp -v
[09:25:31] CLI version 1.4.0
```

**Comment by dbaeumer** [comment]
@TheColorRed what happend when you execute gulp --task-simple from the terminal ?

**Comment by TheColorRed** [comment]
With `gulp-cli`, I get this:

```
$ gulp --task-simple
[11:36:57] Local gulp not found in ~\Documents\www\gamesmartsdk
[11:36:57] Try running: npm install gulp
```

With `gulp`, It runs the task fine

**Comment by dbaeumer** [comment]
Thanks. Can you install gull locally so that the gulp-cli can find it.

**Comment by TheColorRed** [comment]
Okay, so I have `gulp-cli` installed globally:

```
$ which gulp
/c/Users/rnaddy/AppData/Roaming/npm/gulp
```

I then have it installed locally in the project `${workspaceRoot}/node_modules/.bin/gulp`

Then running the same command gives me this:

```
$ gulp --task-simple
The "settings.json" file was found.
[10:02:58] Using gulpfile ~\Documents\www\gamesmartsdk\gulpfile.js
[10:02:58] Starting 'default'...
[10:02:58] Finished 'default' after 67 μs
```

**Comment by dbaeumer** [comment]
OK. That looks good. Can you do one more thing. Run `${workspaceRoot}/node_modules/.bin/gulp --task-simple`. Does this print the console statement ?

**Comment by TheColorRed** [comment]
* `gulp-cli` installed globally
* `gulp` installed locally

results:

```
rnaddy@A1188 MINGW64 ~/Documents/www/gamesmartsdk (v2)
$ ./node_modules/.bin/gulp --task-simple
The "settings.json" file was found.
[16:06:34] Using gulpfile ~\Documents\www\gamesmartsdk\gulpfile.js
[16:06:34] Starting 'default'...
[16:06:34] Finished 'default' after 60 μs
```

**Comment by dbaeumer** [comment]
That basically means I should prefer a global gulp-cli over a local gulp. Need to see if I can do this in a pleasant way.

@TheColorRed thanks for all the investigation.

**Comment by TheColorRed** [comment]
@alexr00 Won't that only fix the issue on windows? I haven't tested on Linux if this issue happens, but shouldn't all OS's be covered anyways?

**Comment by alexr00** [comment]
You're right, this is a Windows only fix. I was under the mistaken impression that this was a windows only bug. Thank you for catching!

**Comment by alexr00** [comment]
Looks like if you update to gulp 4 this issue is resolved.

**Comment by dbaeumer** [comment]
@alexr00 very good to know.
