### ISSUE TITLE
[markdown-language-features] Rendering a Document Containing Pictures Throws a TypeError

### ISSUE THREAD

**Issue by manuth** [microsoft/vscode#116987]
Issue Type: <b>Bug</b>

When trying to run `mdParser.render()` with a markdown-code which contains a picture, a `TypeError` is thrown:

```log
rejected promise not handled within 1 second: TypeError: Cannot read property 'push' of undefined
c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
stack trace: TypeError: Cannot read property 'push' of undefined
    at Object.image (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:98373)
    at s.renderInline (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:141683)
    at s.render (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:142055)
    at h.render (c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\dist\extension.js:1:103730)
```

My extension uses the vscode-parser for converting markdown-files to pdf, so my extension depends on the vscode-parser and needs it to work.

Steps to Reproduce:

1. Create a new extension
2. Add `"markdown.markdownItPlugins": true` to the `package.json`-file
3. Add following code to the extension:
   ```ts
   import { ExtensionContext } from "vscode";

   export let activate = async (context: ExtensionContext): Promise<unknown> => {
       return {
           extendMarkdownIt: (md: any) => {
               md.render("![test-caption](https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png)"); // This throws an error
           }
       };
   };
   ```

VS Code version: Code - Insiders 1.54.0-insider (6eaef7d42f982a0e9b22ac465245fc2c27721fd0, 2021-02-18T05:14:01.684Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 2950X 16-Core Processor  (16 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (46.52GB free)|
|Process Argv|--crash-reporter-id 8e630db1-57b2-4cfa-bb88-f64a7a613eb7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
silverstripe|adr|1.0.6
ts-loader-problem-matcher|alq|0.3.0
markdown-emoji|bie|0.0.9
markdown-mermaid|bie|1.9.2
better-toml|bun|0.3.2
arm|dan|1.5.0
javascript-ejs-support|Dig|1.3.1
vscode-reveal|evi|4.0.3
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
cshtml-tm|fir|1.0.0
coldfusion|ili|1.0.1
reg|ion|1.0.2
vscode-edit-csv|jan|0.5.4
vscode-peacock|joh|3.9.1
languague-renpy|Luq|1.0.6
eslint-language-service|man|1.0.8
rainbow-csv|mec|1.8.1
git-graph|mhu|1.28.0
vscode-apache|mrm|1.2.0
csharp|ms-|1.23.9
remote-containers|ms-|0.160.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
hexeditor|ms-|1.4.0
powershell|ms-|2020.6.0
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
php-docblocker|nei|2.1.0
material-icon-theme|PKi|4.5.0
ejs-language-support|Qas|0.0.1
ruby|reb|0.28.1
vscode-yaml|red|0.15.0
vbsvscode|Ser|1.2.0
vscodeintellicode|Vis|1.2.11
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt600cf:30251589
core-portspanel:30257802
pythontb:30258533
openwsldoc:30257849

```

</details>

**Comment by mjbvz** [comment]
We'd take a PR. However this looks specific to how your extension is using the markdown extension point in an unsupported way so this is not something we'll prioritize fixing

**Comment by manuth** [comment]
Thanks a lot for your rapid answer.
I found myself able to refactor the `markdown-language-features` package to make rendering work again out of the box.
I'll open up a PR asap.
