### ISSUE TITLE
Source Control replaces the message that user just typed for next commit.

### ISSUE THREAD

**Issue by rlayton6** [microsoft/vscode#116983]
Issue Type: <b>Feature Request</b>

In "Source Control" view, using GIT, the message that was just typed in, ready for the next commit, was replaced with message from the history of commits when you press 'up arrow' at top of message box. Even though I discovered I could get it back, this was an unnerving experience. Should at least show visually the list of check-ins been stepped over with a way to immediately go back to the "unknown next check-in", or better yet remove the feature.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.15.0-135-generic

**Comment by gjsjohnmurray** [comment]
Previously reported in #111555

I posted a workaround there, but maybe the underlying issue needs reviewing.

**Comment by eamodio** [comment]
You can get back to the typed message by navigating back "down". So in this case it is by-design.
