### ISSUE TITLE
Single click to expand folder doesn't work

### ISSUE THREAD

**Issue by someone857** [microsoft/vscode#116961]
Issue Type: <b>Feature Request</b>

Since a recent Insiders build, you cannot single click a folder to expand it, requiring you to double-click it.

VS Code version: Code - Insiders 1.54.0-insider (6eaef7d42f982a0e9b22ac465245fc2c27721fd0, 2021-02-18T05:17:08.142Z)
OS version: Darwin arm64 20.3.0

**Comment by IllusionMH** [comment]
/duplicate of #116804

See #115873 for details
