### ISSUE TITLE
ExceptionBreakpointsFilter.description should support links

### ISSUE THREAD

**Issue by gregg-miskelly** [microsoft/vscode#116902]
In 1be536d, support was added to be able to provide hover text for an exception filter. This is a good start, but I would really like to be able to include a link so that users can be pointed at documentation like with hover tips in launch.json. However, the hover tips for exception filters disappear if you try and navigate into them and also don't support links.

Example:
![image](https://user-images.githubusercontent.com/11078489/108286325-b9dacc80-713d-11eb-8205-369a0e4c1d74.png)

Expected result:
![image](https://user-images.githubusercontent.com/11078489/108286576-2e157000-713e-11eb-8a63-253aed45c138.png)

**Comment by gregg-miskelly** [comment]
CC @isidorn

**Comment by isidorn** [comment]
@gregg-miskelly makes sense. I think we use the native hover in the Breakpoints view which does not allow to be clicked on.

@Tyriar @alexr00 I believe the custom hover also behaves like this. But do we have some special solution for this when there are links? To be able to click on the hover? Or we should tackle this as part of https://github.com/microsoft/vscode/issues/115034
