### ISSUE TITLE
Can't find or install theme that's in the Marketplace on Arch

### ISSUE THREAD

**Issue by Jesuszilla** [microsoft/vscode#116959]
- VS Code Version: 1.53.2
- OS Version: Linux x64 5.10.16-arch1-1

Steps to Reproduce:

1. Try to search for "an old hope" in the Marketplace in VSCode. It won't show up, let alone let me install it.
2. Try to enter the command from this web page, it won't work either:

https://marketplace.visualstudio.com/items?itemName=dustinsanders.an-old-hope-theme-vscode

Does this issue occur when all extensions are disabled?: N/A this IS an extension

**Comment by gjsjohnmurray** [comment]
I guess your distro's VS Code package is one that goes to Open VSX for extensions, not to Marketplace.

Download the VSIX from Marketplace then install it from the menu on the Extensions view in VS Code.
