### ISSUE TITLE
When I close a second terminal on VS-Code the window stops responding

### ISSUE THREAD

**Issue by Hasintha-Jayasinghe** [microsoft/vscode#116949]
- VS Code Version: 1.53.2
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Open 2 terminals
2.Close the second one

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
