### ISSUE TITLE
Can't disable Code Lens

### ISSUE THREAD

**Issue by jimpudar** [microsoft/vscode#116974]
Issue Type: <b>Bug</b>

I've added `"editor.codeLens": false` in my settings.json file, but the code lens does not get disabled. I've also tried adding it into my user settings file. I've tried restarting VS Code after adding the setting but the code lens still is showing.

I've tried manually editing the settings.json file and also using the settings UI to uncheck the checkbox with the same results.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3245 CPU @ 3.20GHz (32 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|192.00GB (118.72GB free)|
|Process Argv|--crash-reporter-id 2bda7918-a405-4001-a665-1e099ac0b3b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|3.10.0
armview|ben|0.4.5
gitignore|cod|0.6.0
rest-client|hum|0.24.4
azure-pipelines|ms-|1.183.0
vscode-apimanagement|ms-|0.1.8
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.2.1
vscode-azureresourcegroups|ms-|0.2.0
vscode-azurestorage|ms-|0.11.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.15.1
vscode-docker|ms-|1.10.0
vscode-logicapps|ms-|1.0.5
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.576440691
remote-containers|ms-|0.158.0
azure-account|ms-|0.9.6
azurecli|ms-|0.5.0
powershell|ms-|2020.6.0
vscode-node-azure-pack|ms-|0.1.0
azurerm-vscode-tools|msa|0.14.1
vscode-gitignore-generator|pio|1.0.2
vscode-yaml|red|0.15.0
rewrap|stk|1.14.0
vim|vsc|1.18.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you certain that what you're seeing not disappear **are** CodeLens items?

I suggest you use the Extension Bisect to determine which extension is adding the items.

If that doesn't help, please paste a screenshot here.

**Comment by jimpudar** [comment]
🤦 I thought the minimap was called code lens. Disabling the minimap works as expected 😄
