### ISSUE TITLE
Feature Request: like style-token of notepad++  

### ISSUE THREAD

**Issue by wenhailong** [Microsoft/vscode#11696]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. 
2.

**Comment by ramya-rao-a** [comment]
This is a good candidate for an extension. @alexandrudima thoughts?

**Comment by alexandrudima** [comment]
@wenhailong Can you please describe the feature you would want. Maybe everyone else does, but I don't know what style-token is?

**Comment by etiktin** [comment]
@alexandrudima Notepad++ "style token" allows you to highlight all occurrences of the currently selected text. There are several styles so you can highlight multiple tokens in different colors. It's really useful when you're trying to analyze/scan data (e.g. highlight "ERROR" and "WARNING" in logs or highlight certain fields in a JSON document).
You can see example screen-shots at:
https://github.com/vcharnahrebel/style-token
http://stackoverflow.com/questions/7238349/eclipse-highlighting-the-same-occurrence-of-the-word

Notepad++ also allows you to "Mark" matching text from the search dialog with regex support (the text will remain marked even if you start a new search). See example at:
http://superuser.com/a/567704

**Comment by etiktin** [comment]
@wenhailong you might want to try:
https://marketplace.visualstudio.com/items?itemName=ryu1kn.text-marker

It's not an exact match for style-token, but it might suit your needs.

**Comment by mjbvz** [comment]
Closing as extension-canidate

**Comment by ramya-rao-a** [comment]
_Adding the missing statement from our bot for issues that have the `extension-candidate` label:_


We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
