### ISSUE TITLE
Notebook Run state gets updated with the runDuration value

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116900]
- VS Code Version: OSS
- OS Version: Mac

Steps to Reproduce:

1. Repro steps can be found here  https://github.com/microsoft/vscode/pull/116901
@rebornix /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/116901

**Comment by rzhao271** [comment]
Is the runDuration value the part I circled below?

![red-circle-duration](https://user-images.githubusercontent.com/7199958/109217223-6e8e7280-776a-11eb-8fc7-b12dbd4e409b.PNG)
