### ISSUE TITLE
Vscode window breaks layout on multiple monitors

### ISSUE THREAD

**Issue by ifalex** [microsoft/vscode#116952]
- VS Code Version: 1.53.2
- OS Version: Windows 10 Enterprise 10.0.18363 Build 18363

Steps to Reproduce:

1. Have 2 desktop monitors, one of them enters in stand-by(my second monitor), after getting it out of stand-by the vscode window loses its layout. Shifts the button to the right (minimize button ( _ )becomes x (close button) and so on)
2. Looks like a visual rendering issue.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ifalex** [comment]
So here you have a illustration of how the image is rendered:
![image](https://user-images.githubusercontent.com/16538208/108714256-02213280-7522-11eb-9e9b-5f8f9a06031a.png)
As mentioned above:
To reproduce:
1) If my pc goes to standby, when I log back in one of my desktop monitors is still in standby, one is working(I'm working with a 2 desktop monitors setup)
2) Maximize vscode and observe the rendering issue. Vscode window size is not resized accordingly pixels from the monitor desktop
Can't explain better than that.
If there is a log I can attach gladly will attach. Or debug command I can issue.

**Comment by bpasero** [comment]
Do you also see this when you configure `window.titleBarStyle: native`?
