### ISSUE TITLE
Custom markdown renderer: folded cell are still rendered

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#116918]
Issue Type: <b>Bug</b>

* open `endgame.github-issues`
* fold `Preparation`
* reload window

![image](https://user-images.githubusercontent.com/876920/108311157-75652600-7169-11eb-82b2-1e4354a04dc6.png)

I'm not seeing this issue with builtin markdown renderer.

VS Code version: Code - OSS Dev 1.54.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.00GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|0.3.1
dotnet-interactive-vscode|ms-|1.0.160901
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.1.502429796
notebook-renderers|ms-|0.0.1
remote-ssh|ms-|0.58.0
remote-ssh-edit|ms-|0.58.0
remote-wsl|ms-|0.52.0
vscode-github-issue-notebooks|ms-|0.0.58
vscode-markdown-notebook|ms-|0.0.13
jupyter-notebook-renderer-geojson|reb|0.0.1

</details>

**Comment by alexr00** [comment]
I still see this:
![image](https://user-images.githubusercontent.com/38270282/109311000-85ee5e00-7845-11eb-87cb-085f14a26935.png)

Version: 1.54.0-insider (user setup)
Commit: 59c31364c707ee962cc594389966801af4ce69bd
Date: 2021-02-25T07:44:40.955Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
Yea happens in the first five markdown cells due to `initializeMarkdown`. May also be fixed by #117723

**Comment by mjbvz** [comment]
Fixed by #117723 in my testing
