### ISSUE TITLE
Unable to reset executionOrder of cells

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116956]
- VS Code Version:OSS
- OS Version:Mac

Steps to Reproduce:

1.Steps can be found here 
https://github.com/microsoft/vscode/pull/116957

@rebornix @jrieken /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by DonJayamanne** [comment]
Solution - create new object instead of using `.with`

**Comment by jrieken** [comment]
Let's keep this open. I still wanna look into a fix, I just don't know how and metadata might change with future changes that we have in mind

**Comment by DonJayamanne** [comment]
@jrieken please see my comments here https://github.com/microsoft/vscode/pull/116957#discussion_r579550975

**Comment by RMacfarlane** [comment]
Maybe I'm just missing something in the linked PR, but I don't see repro steps there.

@jrieken what's a good way to verify this?

**Comment by jrieken** [comment]
This cannot be verified because the code that I fixed doesn't exist anymore. We significantly refactored how execution works and it isn't represented as metadata anymore. Moving this off the milestone
