### ISSUE TITLE
Button to Reveal in Sidebar next to New File button

### ISSUE THREAD

**Issue by jpnieto** [microsoft/vscode#116969]
Hi!
My suggestion is to add a button next to the New File/New Folder buttons to "Reveal in Sidebar" for the currently open file. It could be very useful specially in large projects and when there are many files open.

**Comment by isidorn** [comment]
This suggestion makes sense, however I would prefer to tackle this by making the title bar in the explorer contributable https://github.com/microsoft/vscode/issues/108271
Thus closing as duplicate
