### ISSUE TITLE
FAILURES ON SCOPE SELECTORS

### ISSUE THREAD

**Issue by JDPT93** [Microsoft/vscode#11697]
@aeschli 

- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

1. DOWNLOAD [index.txt](https://github.com/Microsoft/vscode/files/462044/index.txt) AND CHANGE .txt TO .php

2. OPEN THE FILE USING [theme-vs-light.zip](https://github.com/Microsoft/vscode/files/462029/theme-vs-light.zip) THEME

![1](https://cloud.githubusercontent.com/assets/22055946/18356501/807814ce-75b2-11e6-9cd3-43736a004150.png)
![2](https://cloud.githubusercontent.com/assets/22055946/18356500/802e7652-75b2-11e6-951f-35468d430739.png)
![3](https://cloud.githubusercontent.com/assets/22055946/18356502/813ced58-75b2-11e6-8745-c4870fdcac12.png)

THE FILE CONTAIN THINGS THAT I CONSIDER AS FAILURES IN SCOPE SELECTORS.

I SOLVE MANUALLY SOMETHING FAILURES ON 

> /resources/app/extensions/php/syntaxes/php.json

A) support.class.php should match the class name and class alias but shouldn't match for function or constants

ADDING IN LINE 1030

`{
    "begin": "(?i)\\s*\\b(use)\\s+[a-z_0-9\\\\]+\\\\\\{?((\\s*[a-z_0-9]+(\\s+as\\s+[a-z_0-9]+)?\\s*,?)+)\\s*\\}?",
    "beginCaptures": {
        "1": {
            "name": "keyword.other.use.php"
        },
        "2": {
            "patterns": [
                {
                    "captures": {
                        "1": {
                            "name": "support.class.php"
                        },
                        "3": {
                            "name": "keyword.other.use-as.php"
                        },
                        "4": {
                            "name": "support.class.php"
                        }
                    },
                    "match": "(?i)([a-z_0-9]+)(\\s+(as)\\s+([a-z_0-9]*))?"
                }
            ]
        }
    },
    "end": "(?=;|(?:^\\s*$))",
    "name": "meta.use.class.php"
}`

B) storage.type.php should match bool, int, float, string and self for function arguments AND string.php should match the strings on default values for type hinted function arguments

> "constant.language.php should match the language constants on default values for type hinted function" SOLVED BUT NOT WORKING FOR ARRAY VALUES...

REPLACING LINE 424

`"match": "(?xi)\n\t\t\t\t\t\t\t\\s*(array|callable) # Typehint\n\t\t\t\t\t\t\t\\s*(&)? \t\t\t\t\t# Reference\n\t\t\t\t\t\t\t\\s*((\\$+)[a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*) # The variable name\n\t\t\t\t\t\t\t(?:\n\t\t\t\t\t\t\t\t\\s*(?:(=)\\s*(?:(null)|(\\[)((?>[^\\[\\]]+|\\[\\g<8>\\])*)(\\])|((?:\\S*?\\(\\))|(?:\\S*?))))\t# A default value\n\t\t\t\t\t\t\t)?\n\t\t\t\t\t\t\t\\s*(?=,|\\)|/[/*]|\\#|$) # A closing parentheses (end of argument list) or a comma or a comment\n\t\t\t\t\t\t\t",
`

TO

`"match": "(?xi)\n\t\t\t\t\t\t\t\\s*(array|bool|callable|float|int|self|string) # Typehint\n\t\t\t\t\t\t\t\\s*(&)? \t\t\t\t\t# Reference\n\t\t\t\t\t\t\t\\s*((\\$+)[a-z_\\x{7f}-\\x{ff}][a-z0-9_\\x{7f}-\\x{ff}]*) # The variable name\n\t\t\t\t\t\t\t(?:\n\t\t\t\t\t\t\t\t\\s*(?:(=)\\s*(?:(\"[^\"]*\"|\\'[^\\']*\\')|(TRUE|FALSE|NULL|__(FILE|DIR|FUNCTION|CLASS|METHOD|LINE|NAMESPACE)__|ON|OFF|YES|NO|NL|BR|TAB)|(\\[)((?>[^\\[\\]]+|\\[\\g<8>\\])*)(\\])|((?:\\S*?\\(\\))|(?:\\S*?))))\t# A default value\n\t\t\t\t\t\t\t)?\n\t\t\t\t\t\t\t\\s*(?=,|\\)|/[/*]|\\#|$) # A closing parentheses (end of argument list) or a comma or a comment\n\t\t\t\t\t\t\t",
`

AND REPLACING "captures" OBJECT

`{
          "captures": {
            "1": {
              "name": "storage.type.php"
            },
            "2": {
              "name": "storage.modifier.reference.php"
            },
            "3": {
              "name": "variable.other.php"
            },
            "4": {
              "name": "punctuation.definition.variable.php"
            },
            "5": {
              "name": "keyword.operator.assignment.php"
            },
            "6": {
              "name": "string.php"
            },
            "7": {
              "name": "constant.language.php"
            },
            "8": {
              "name": "punctuation.section.array.begin.php"
            },
            "9": {
              "patterns": [
                {
                  "include": "#parameter-default-types"
                }
              ]
            },
            "10": {
              "name": "punctuation.section.array.end.php"
            },
            "11": {
              "name": "invalid.illegal.non-null-typehinted.php"
            }
          }`

THANK YOU, EXCUSE MY BAD ENGLISH.

**Comment by aeschli** [comment]
Hi @JDPT93, thanks for your findings. The PHP grammar is from https://github.com/textmate/php.tmbundle. Please make the pull request there and let us know when we should update our grammar with the latest version from there. Thanks!
