### ISSUE TITLE
Non-obvious error message when a contributed command fails

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#116953]
vscode: 1.53.2
vscode-languageclient: 7.0.0-next.12

The Go extension has a codelens that triggers a command execution run by the go language server.
When the command fails and the language server returns an error, vscode shows a notification with rather mysterious error message. (`'_vscode_delegate_cmd_klaxycmt' failed`)

![Screen Shot 2021-02-18 at 9 16 01 AM](https://user-images.githubusercontent.com/4999471/108370766-002a3d00-71cb-11eb-9da4-94bb596c1e37.png)

Showing the original command (and the error message if possible) from the command will be ideal.

The LSP trace is
 
```
[Trace - 09:15:50.467 AM] Sending request 'workspace/executeCommand - (124)'.
Params: {"command":"gopls.tidy","arguments":[{"URIs":["file:///Users/hakim/projects/google/w/go.mod"]}]}

[Error - Received] 09:15:50.468 AM #124 All files must be saved first

[Error - 9:15:50 AM] Request workspace/executeCommand failed.
  Message: All files must be saved first
  Code: 0 
```

**Comment by ganni** [comment]
Hi, 

I just reported same bug few hours ago. Let's continue the discussion there.

Duplicate of #116932

**Comment by hyangah** [comment]
Thanks. Closing in favor of the other issue.
