### ISSUE TITLE
Reports wrong errors from ts when using js files

### ISSUE THREAD

**Issue by fcole90** [microsoft/vscode#116937]
Issue Type: <b>Bug</b>

I have a react-redux reducer file with the following content:
```js
const initialState = []


export default (state = initialState, { type, payload }) => {
  switch (type) {

  case ADD:
    return { ...state, ...payload }

  default:
    return state
  }
} as formReducer
```

The last line gets highlighted as an error:
```
';' expected.ts(1005)
```

Which doesn't make sense to me, as I'm not using typescript in this project and I configured ESlint to not require semicolons. This is the only instance I could find of a similar error.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 3993)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.28GB (2.48GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 46c7c48f-03b4-43f8-bf56-47aef80f4b91|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.18.0
markdown-preview-github-styles|bie|0.1.6
npm-intellisense|chr|1.3.1
jsrefactor|cms|2.20.6
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.1
github-actions|for|0.0.1
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.23.1
go|gol|0.22.1
vscode-graphql|Gra|0.3.15
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
vscode-github|Kni|0.30.4
bash-extension-pack|liz|0.0.4
bash-ide-vscode|mad|1.11.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
python|ms-|2021.2.576481509
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
cpptools|ms-|1.2.1
powershell|ms-|2020.6.0
debugger-for-chrome|msj|4.12.12
shellman|Rem|4.10.0
bash-debug|rog|0.3.9
shebang-snippets|rpi|0.1.4
shellcheck|tim|0.13.2
quokka-vscode|Wal|1.0.343
ReactSnippets|xab|2.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by fcole90** [comment]
P.S. Adding a `;` doesn't make the message disappear.

![image](https://user-images.githubusercontent.com/1292230/108348673-c10be400-71ea-11eb-9fe3-83dfd1146f01.png)

**Comment by IllusionMH** [comment]
Is it JS file?
`as <type>` not allowed in JS it's TS construction.

**Comment by fcole90** [comment]
It's a js file, and `type` here is just the name of a variable. Changing the name to something else, like `mytype` didn't change anything

**Comment by IllusionMH** [comment]
Oops missed `export` and confused `as formReducer` with type assertion from TS.

Anyway there is no construction in JS `export default (...) as something` Babel [reports same issue](https://babeljs.io/repl/#?browsers=ie%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAlmOU4EMA2BlKKoFMYC8MA2gLoBQluAHgA4gBOsAJrgGYoCuasAFNDnxEESVJmx4ANDADeMKAE9auabRQK0IFMxgBfAJSEAfLPIwYEAO5JgACxi9FywzMrngKCPgCCAEV8AXGbmMAy4UJwMYLIwAHTxAlJx8WoaWjq6bjCsHNxQQSGh4ZHRibjBmbownjBsjAC2AEq4zJzAuAxAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.12.14&externalPlugins=)

You either have default export or named export (`export const formReducer = ...`)

**Comment by fcole90** [comment]
Oh, I mixed different syntaxes, and likely VS Code confused it like you for a type assertion :sweat_smile:
