### ISSUE TITLE
vs code caches connection to remote DB

### ISSUE THREAD

**Issue by artemitcraft** [microsoft/vscode#116933]
Version: 1.52.1
Node.js: 12.14.1
OS: Windows_NT x64 10.0.19041

hi, I use remote mongodb connection for our nodejs app. Connection vars are configured in launch.json. It seems that when I change this vars for connection string, debuger "caches" connect to mongo with the old ones. It reproduces on restart button, but if I stop the app and then run it, it works ok. does anyone have such issue?

**Comment by weinand** [comment]
Yes, by design changes to the launch.json are not picked up by the restart.
