### ISSUE TITLE
Ctrl+P Opens a file in a same tab.

### ISSUE THREAD

**Issue by shubhendur** [Microsoft/vscode#11694]
- VSCode Version: 1.4
- OS Version: Windows 7

Steps to Reproduce:

1. Ctrl+P Opens a file in a same tab.
2. It should open in a different tab.

**Comment by tjalex** [comment]
Is your current tab set to stay open? (It probably isn't if you just opened a file and haven't made any changes.)

Try pressing Ctrl+K, Enter (or Ctrl+Shift+P and search for 'keep') to keep that editor open. Then, try to Ctrl+P and open another file--it should appear in a new tab.

**Comment by bpasero** [comment]
`"workbench.editor.enablePreviewFromQuickOpen": false`
