### ISSUE TITLE
使用VScode链接服务器，无代码提示

### ISSUE THREAD

**Issue by lfydegithub** [microsoft/vscode#116944]
使用Remote-SSH登录服务器，python环境，发现无代码提示，ctrl+左键无法进入函数定义， 有大佬知道怎么处理吗

**Comment by adfnekc** [comment]
here is the translation 

> i am python user.when i use Remote-SSH to log in to the server, , there isn`t code prompt and ctrl+left key can not enter the function definition.

here is my suggestion
> highly recomend you check python enviroment in remote server and python vscode extention

这是我的建议
> 强烈建议您检查远程服务器中的python环境以及python vscode扩展

**Comment by roblourens** [comment]
Please check out the Python extension, file an issue on their repo if it's not working, thanks
