### ISSUE TITLE
Error while editing markdown 

### ISSUE THREAD

**Issue by sanketbh** [microsoft/vscode#116921]
command 'markdown.showPreviewToSide' not found
![Screenshot from 2021-02-18 11-34-21](https://user-images.githubusercontent.com/72594303/108312842-50aa9600-71dd-11eb-9421-82bf3a6b6152.png)

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo how about version and platform for a start? And whether you still have the problem when you run with all extensions disabled.
