### ISSUE TITLE
Fails to start on Windows Terminal Server

### ISSUE THREAD

**Issue by hjrb** [microsoft/vscode#116950]
Issue Type: <b>Bug</b>

We still have quite a large number of Windows Terminal Server users. We would like to provide VS Code for those users. We tried a system installation of VS Code using VSCodeSetup-x64-1.53.1.exe. The installation works without any error message.
But when we try to start VS Code it won't start. We ran a diagnostic session using the command line "code --disable-gpu --prof-startup --log debug --verbose"
I attached the log files. We also saw some errors in the windows application event log, related to ntdll.dll.
Maybe this is due to some configuration of our WTS servers. 
Any help is very appreciated!

[prof-b41c.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6003256/prof-b41c.renderer.cpuprofile.txt)
[vsc-start.log](https://github.com/microsoft/vscode/files/6003257/vsc-start.log)

[prof-b41c.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6003253/prof-b41c.extHost.cpuprofile.txt)
[prof-b41c.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6003254/prof-b41c.main.cpuprofile.txt)

the log files.

**Comment by deepak1556** [comment]
Does the registry key workaround help for your case https://github.com/microsoft/vscode/issues/84914 ?

**Comment by hjrb** [comment]
> 
> 
> Does the registry key workaround help for your case #84914 ? It was originally reported for citrix but other remote desktop users also commented to work with that.

Hello, thank for your feedback and sorry for the late reply. Yes: creating the registry keys:
            HKEY_LOCAL_MACHINE\SOFTWARE\Citrix\CtxHook\AppInit_DLLs\SfrHook\code.exe
            HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Citrix\CtxHook\AppInit_DLLs\SfrHook\code.exe
fixes the issue :-)
