### ISSUE TITLE
Drag tag system no response

### ISSUE THREAD

**Issue by linxiaoyun12** [microsoft/vscode#116927]
Issue Type: <b>Bug</b>

Drag and drop the tag of the split view

![recording](https://user-images.githubusercontent.com/25984068/108439577-85c1f180-728c-11eb-9562-89f7b32d6f99.gif)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.72GB free)|
|Process Argv|--crash-reporter-id 4149ea8c-bae2-4875-a909-724a43c55b11|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.14
vscode-npm-script|eg2|0.3.16
vscode-element-helper|Ele|0.5.6
prettier-vscode|esb|5.9.2
vscode-firefox-debug|fir|2.9.1
code-runner|for|0.11.2
docthis|joe|0.7.1
vscode-language-pack-zh-hans|MS-|1.53.2
env-cmd-file-syntax|Nix|0.2.2
vetur|oct|0.32.0
docthis|oou|0.8.2
vscode-xml|red|0.15.0
LiveServer|rit|5.6.1
vue-helper|she|2.4.7
vscode-webhint|web|1.5.11
vuter|yoy|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by linxiaoyun12** [comment]
![share2](https://user-images.githubusercontent.com/25984068/108339754-c715bb00-7212-11eb-8299-7a1e50958d4e.gif)

**Comment by weinand** [comment]
Sorry, but I do not understand what you mean.

And your animated gif is not really helpful. May I suggest to use a better screen recording tool, e.g. https://gifcap.dev
