### ISSUE TITLE
NotebookCellOutput.metadata returned by content provider does not end up in Notebook document

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#116967]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Create a Notebook content provider and return cells with output and the output containing metadata
2. The Notebook document generated by VS Code will not contain the metadata in the outputs
@jrieken @rebornix /cc

Tests can be found here https://github.com/microsoft/vscode/pull/116968/files

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
Actually fixed via #116968
