### ISSUE TITLE
Allow relative path when adding file to project folder

### ISSUE THREAD

**Issue by bgse** [Microsoft/vscode#1169]
Similar like Atom does it when adding a file to a project folder, allow us to specify a path relative to the project folder.

This would be a much more convenient way to add files compared to navigating a file tree and clicking buttons, especially useful for those of us who like to disable trackpads on their laptops and use keyboard only.

Say I have in my project folder the subfolder 'foo', and inside 'foo' I have 'bar', allow me to create a new file directly giving this:

foo/bar/newfile.ts

Ideally, we would have autocompletion using [tab] for folder names, and it would create subfolders if needed, e.g. this

foo/bar/newfolder/newfile.ts

would also create 'newfolder'.

**Comment by bpasero** [comment]
Sounds like a cool opportunity for an extension too.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12893
