### ISSUE TITLE
Same fonts rendered differently between Win10 and Mac

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#116997]
- VSCode version: 1.54.0-insider
- OS: Win10 1909 / macOS Catalina 10.15.7

Steps to Reproduce:

1. Install the font here: https://drive.google.com/file/d/0B3laO4yuXZrnUkpyWXhaSjZyT2s/view?usp=sharing
2. Set the font family in VS Code to `Tsentsiu Mono HG`

Fonts previewed in Win10:
![image](https://user-images.githubusercontent.com/17170199/108453808-524c8a80-72bf-11eb-8f8e-cac84acc6e02.png)

Fonts rendered in Win10 (Pay attention to `r`, `c`, `t`, `i`, `l`, `0`, etc., it also look much thicker as if it's reading the bold version from `.ttc` by default):
![image](https://user-images.githubusercontent.com/17170199/108453547-ce929e00-72be-11eb-8e1e-09762a44757d.png)

Fonts rendered in Mac:
![image](https://user-images.githubusercontent.com/17170199/108454090-e0287580-72bf-11eb-9dd4-7fd4247f536e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
All font rendering in the editor is delegated to Chromium. @pingshunhuangalex Can you also reproduce at https://vscode-web-test-playground.azurewebsites.net/ when opening that website on Chrome ?

**Comment by pingshunhuangalex** [comment]
I can still reproduce it in the playground.

Although it doesn't look as thick as what's displayed in the editor (probably just a Window Clear Type thing cuz VS Code doesn't support `anti-aliasing` in Windows, the font rendered still seems wrong.

If there's nothing VS Code can do since it's a Windows Chromium issue, feel free to close the ticket. It'd be nice if you can report this bug to Chromium but I understand it will be a long shot if it's on the Chromium level. Thanks.

**Comment by alexdima** [comment]
@pingshunhuangalex Thank you for trying. This confirms that it is indeed an upstream issue. If you wish to pursue this further, you can create a test HTML page with just `<div style="font-family:'Tsentsiu Mono HG'">hello</div>` at https://jsfiddle.net/ and then compare this across Chrome and Firefox on Windows or across Chrome on Windows vs Chrome on macOS. You can then create an issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list and someone from there might be able to investigate this further or at least explain better what is going on.
