### ISSUE TITLE
OSS wrong zoom level after window reload

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#116917]
Issue Type: <b>Bug</b>

Currently when I reload OSS, it always has a wrong zoom level. Resetting it only works for current session.

![recording (11)](https://user-images.githubusercontent.com/876920/108310673-9d07be80-7168-11eb-88f3-fc6c4e62e7fb.gif)

VS Code version: Code - OSS Dev 1.54.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (13.55GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|0.3.1
dotnet-interactive-vscode|ms-|1.0.160901
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.1.502429796
notebook-renderers|ms-|0.0.1
remote-ssh|ms-|0.58.0
remote-ssh-edit|ms-|0.58.0
remote-wsl|ms-|0.52.0
vscode-github-issue-notebooks|ms-|0.0.58
vscode-markdown-notebook|ms-|0.0.13
jupyter-notebook-renderer-geojson|reb|0.0.1

</details>

**Comment by deepak1556** [comment]
Refs https://github.com/microsoft/vscode/pull/104779#issuecomment-675168735

Merging to https://github.com/microsoft/vscode/issues/108920
