### ISSUE TITLE
formatting jsx files stopped working

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#11698]
- VSCode Version: 1.4.0
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. open jxs file with improper formatting
2. press shift+alt+f, or click Format Code in command palette
3. formatting doesn't work

**Comment by ramya-rao-a** [comment]
@anvish I am able to format jsx files just fine in VS Code 1.4.0 in Windows. Can you give more details?

- Was this working before in VS Code 1.4.0?
- What extensions do you have? Can you try with extensions disabled? `code --disable-extensions .` 
- What is the file mode? You can see that in the bottom right corner.
- Does formatting work for other file types? 
- Can you try the insiders build and see if you still see the issue?

**Comment by anvish** [comment]
Thank you for response.
I've found what causing formatting to stop working - it's apostrophe in jxs.
This piece of code breaks formatting:
`    return  <div>'</div>`
And this does not:
`    return  <div>1</div>`
After trying to format the former, formatting stops working for all jsx, js and tsx files untill VS Code restart.

**Comment by ramya-rao-a** [comment]
@anvish That is interesting. I was able to repro now. With the `'` formatting breaks for current file and all other files.
The fact that formatting fails for all other files is suspicious.

The output window shows the below error for every subsequent formatting in other or same file even after fixing the `'`

![image](https://cloud.githubusercontent.com/assets/16890566/18396066/8359853c-7676-11e6-9d02-cc7785da0777.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10817

**Comment by waderyan** [comment]
Yep. Just moved over.
