### ISSUE TITLE
[Propose] multi-select in Breakpoints section panel

### ISSUE THREAD

**Issue by jerryzhoujw** [microsoft/vscode#116911]
I usually add lots of breakpoints when debug a bug which is not so sure which part of code is the root cause.

In that case, there will be lots of breakpoints added.

After the bug fixed, or after one part of code is excluded for that bug. I would like to select some of the breakpoints quickly, and disable / remove them quickly.

<img width="479" alt="breakpoint_popup" src="https://user-images.githubusercontent.com/6405390/108299691-d75d7400-71d9-11eb-9292-2c3b869dcc78.png">

My propose is:

1. Can select the breakpoints with `Shift` / `Ctrl`  keyboard.  which just like select files in folder on mac.
2. Or can select breakpoints of same files.

I prefer the first one. 

What do you think ?

**Comment by isidorn** [comment]
Yeah having multi selection in Breakpoints view makes good sense.
For now assigning this to On Deck and we might look into adding this in the future.
Thanks!

**Comment by FelixVaughan** [comment]
Hi, can we re-open this issue? Seems like a super useful feature and I was surprised it wasn't already implemented

**Comment by RauerJ** [comment]
Hi! I also think that this would be very useful.

**Comment by MarkusSeubelt** [comment]
Hello, I would also like to see this feature. Please reopen the issue.
