### ISSUE TITLE
Debug Console does not show line numbers if an object is in the output

### ISSUE THREAD

**Issue by jgreen-linx** [microsoft/vscode#116934]
Issue Type: <b>Bug</b>

same issue seen here 
https://stackoverflow.com/questions/65623994/vs-code-debug-console-not-showing-line-number-for-logs
![AARxf](https://user-images.githubusercontent.com/43069621/108342007-328b6880-71d2-11eb-8bfd-aa59e39ca0be.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.55GB free)|
|Process Argv|C:\\Users\\jgreen\\Documents\\IOT\\PrinterNet2\\PrinterNet2_Web --crash-reporter-id 958af838-57b0-4c12-8841-a0dfa18e60b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
angulardoc-vscode|Ang|6.1.3
atlascode|atl|2.8.5
vscode-browser-preview|auc|0.6.7
doxdocgen|csc|1.1.0
githistory|don|0.6.14
tslint|eg2|1.0.44
vscode-npm-script|eg2|0.3.16
bitbake|Eug|1.1.2
align-mode|Gru|0.0.21
todo-tree|Gru|0.0.196
beautify|Hoo|1.5.0
svg|joc|1.4.5
Angular2|joh|11.0.0
Angular-BeastCode|Mik|10.0.3
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.576440691
cpptools|ms-|1.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
printcode|nob|3.0.0
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.15.0
bash-beautify|sha|0.1.1
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
vscode-counter|uct|2.2.2
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by isidorn** [comment]
I acknowledge this issue. The js-debug extension properly sends the source location, but we do not render the source for objects coming from output.
Reason being: we re-use the variables renderer from the variables view and that one does not render source objects.
We could improve this in the future

**Comment by barrard** [comment]
> Also this was never working.

As far as I can recall, it did work at one point and it was very nice to have.  It stopped about 10 months ago I think.

**Comment by jgreen-linx** [comment]
> > Also this was never working.
> 
> As far as I can recall, it did work at one point and it was very nice to have. It stopped about 10 months ago I think.

Yes it did use to work with no issues. I see it as a regression in what they used to do

**Comment by grv87** [comment]
Looks that it was reopened as #137100
