### ISSUE TITLE
Git Source Control not working

### ISSUE THREAD

**Issue by RifanAmrozi** [microsoft/vscode#116936]
After the last update, my source control VS Code is not working properly, it shows blank. no number no description, just the name of git branch.
I hope it will be solved. Thanks.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo and in particular what platform you are running on. Use Help\About, copy the info, then paste it here.

If you are on CentOS 7 / RHEL 7, VS Code 1.53 is no longer supported.

Tip: for future issues, use the Report Issue option on the Help menu.

**Comment by RifanAmrozi** [comment]
This is my spec

Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by popovas** [comment]
Same on
OS: Red Hat Enterprise Linux Workstation 7.8
all addons work perfectly fine with VS Code 1.52.1

> /needsMoreInfo and in particular what platform you are running on. Use Help\About, copy the info, then paste it here.
> 
> If you are on CentOS 7 / RHEL 7, VS Code 1.53 is no longer supported.
> 
Where can more information be found about support for RHEL 7?

Thank you!
