### ISSUE TITLE
Git: ssh_askpass: exec(/opt/homebrew/Cellar/openssh/8.4p1_2/libexec/ssh-askpass): No such file or directory

### ISSUE THREAD

**Issue by marvinruder** [microsoft/vscode#116978]
- VS Code Version: 1.53.2
- OS Version: Darwin x64 20.4.0

I installed `ssh-askpass` using Homebrew a while ago and updated it today. After this update, the binary moved to a different location, but VS Code looks for the binary in the original location. I cannot find a way to tell VS Code where it moved to. Reinstalling VS Code and deleting all settings file I could find (e.g. via https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vscode-on-mac) did not solve the issue. Accessing git from terminal works fine.

Steps to Reproduce:

1. Open a project with a git server which we connect to via a PKCS#11-Token (which renders the solution in #32097 useless, since I cannot simply use `ssh-add 'some-key-file'` and save the PIN to my token somewhere)
2. Select “Git Pull” in the Source Control section.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
@marvinruder, apologies for not getting back to you on this until now. Are you still experiencing this issue? I am asking as VS Code does not invoke `ssh-askpass` but spawns a process running `git.exe` which I suspect that in turn invokes `ssh-askpass`. I suspect that there might be some difference in environment variables between VS Code and the terminal.

**Comment by marvinruder** [comment]
Today I am no longer using a git workflow which involves PKCS#11-Tokens requiring a PIN, so I cannot reproduce. But I think even before that the issue was no longer present with newer versions of either VSCode, OpenSSH, ssh-askpass, git or my operating system; or other configuration changes which I do not remember anymore.
