### ISSUE TITLE
SCM refresh causes focus in SCM panel to jump between random repositories

### ISSUE THREAD

**Issue by blindrood** [microsoft/vscode#116930]
Issue Type: <b>Bug</b>

If save file and quickly put focus on commit message in SCM panel I'll do it before automatic refresh happens , that lists files to include in commit. I start typing, then refresh happens causing focus to jump to different message boxes for different repositories

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.35GB free)|
|Process Argv|--crash-reporter-id 1b97c16b-d777-4022-a0e3-811def29e77a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vagrant|bbe|0.5.0
better-toml|bun|0.3.2
vscode-junos|cod|0.1.7
vscode-zonefile|Com|0.0.4
vscode-markdownlint|Dav|0.39.0
ansible|haa|0.2.8
terraform|has|2.6.0
rest-client|hum|0.24.4
vscode-docker|ms-|1.10.0
mssql|ms-|1.10.1
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.576440691
remote-wsl|ms-|0.53.4
azure-account|ms-|0.9.6
powershell|ms-|2020.6.0
docker-compose|p1c|0.3.5
jinjahtml|sam|0.16.0
vcl|tho|0.1.2
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by epsitec** [comment]
I am suffering from this issue too. In my case, I have a main git module with about 50 submodules. While VS refreshes the status of the submodules, trying to type a message will often result in part of the text appearing in the wrong submodule.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/135143
