### ISSUE TITLE
RST language support

### ISSUE THREAD

**Issue by Firehawke** [Microsoft/vscode#117]
I'd love to see support for ReStructuredText ( http://docutils.sourceforge.net/docs/user/rst/quickref.html ) as it would make one of my current projects a lot simpler. It's similar but not identical to Markdown.

**Comment by bpasero** [comment]
@Firehawke how about an extension for this :)

**Comment by lextm** [comment]
@bpasero I'd like to work on such an extension, but is there any guidance?

For example, I think I might get started from the markdown language support. Will it be enough to follow these?

* https://github.com/lextm/vscode/tree/master/extensions/markdown
* https://github.com/lextm/vscode/tree/master/src/vs/languages/markdown

**Comment by bpasero** [comment]
Our docs are a good start: https://code.visualstudio.com/docs/extensions/overview

**Comment by lextm** [comment]
@bpasero Thanks. Will spend some time on that.

A few tasks before attacking on,

- [ ] follow Microsoft's materials (doc+sample) to learn the extension model
- [ ] find a suitable language parser to feed the extension
- [ ] write the glue code to bridge the parser to the extension
- [ ] pack up and test

There seem to be [a few options](http://stackoverflow.com/questions/2746692/restructuredtext-tool-support) but it takes a while to be familiar with them.

**Comment by bpasero** [comment]
Just so that you know: It is currently not possible to open a preview in HTML from an extension like it is possible for markdown.

**Comment by lextm** [comment]
@bpasero Thanks for the tip. I glanced at the markdown language support and found that,

1. It happens to be based on an open source Markdown parser in JavaScript.
2. The glue code not only links that parser to VS Code, but also makes the preview work.

It would be difficult to find a reStructuredText parser in JavaScript right now. Existing ones rely on either Python or JVM.

Probably I will refer to languages such as PowerShell or Python to provide syntax highlighting first.

**Comment by lextm** [comment]
Finished some reading on [this article](https://code.visualstudio.com/docs/customization/colorizer) and also found [TextMate reST syntax highlighting support files](https://github.com/textmate/restructuredtext.tmbundle). So I think I will revise the task list accordingly.

**Comment by lextm** [comment]
I just published 0.0.1 on the gallery, which implements the very basic feature set,

https://marketplace.visualstudio.com/items/lextudio.restructuredtext

**Comment by lextm** [comment]
@bpasero @egamma I think we can close this now. I created such an extension and published its 0.0.2 version a few hours ago. Syntax highlighting and code snippets have been supported. @Firehawke you can try it out.

**Comment by egamma** [comment]
:clap: thank you

**Comment by Firehawke** [comment]
Thank you, by the way. Work blocked me from replying until now, but this is definitely a good start and it looks like it'll be better than using Notepad++. Now I just need to work out a way to quick compile this through Sphinx+RTD, but that's a subject for a different thread.

**Comment by lextm** [comment]
@Firehawke Though not related to this, but you might learn from both RTD documentation and existing doc sites.

I have learned a lot from [ASP.NET](https://github.com/aspnet/docs), and then started [my very first for DockPanel Suite](https://github.com/dockpanelsuite/dockpanelsuite_docs) a few days ago. Well, actually that's why I am now using reStructuredText and decided to work on this VS Code extension :)

**Comment by egamma** [comment]
@Firehawke regarding 'Now I just need to work out a way to quick compile this through Sphinx+RTD'. I suggest that you look into the VS Code Task support https://code.visualstudio.com/docs/editor/tasks

**Comment by pgerell** [comment]
@lextm Thank You. Just what I was looking for.
I am having problems with the section header snippets. Do they work for anyone else?
According to https://code.visualstudio.com/docs/customization/userdefinedsnippets regex replacements are not supported (yet).

Maybe a command that underlines the current line could be used instead. If the line is already a header, it could modify it to use the next header level. This is how the emacs rest-mode works.

**Comment by lextm** [comment]
@pgerell Can you open a new issue at https://github.com/lextm/vscode-restructuredtext so that I can better track it?

I am still digging into VS Code documentation to see how to further improve ReST support, so progress might be slow.

**Comment by lextm** [comment]
The repo has been moved to https://github.com/vscode-restructuredtext/vscode-restructuredtext and preview feature has been added since 0.0.7.

**Comment by lextm** [comment]
True sphinx-build enabled live preview is now available in 0.0.14+,

https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext

**Comment by mountgellert** [comment]
@lextm , you can try looking at https://www.npmjs.com/package/restructured and try doing a javascript based renderer. Won't be the same fidelity as sphinx, but would be considerably faster.

**Comment by lextm** [comment]
Thanks @mountgellert I will evaluate it but the design goal of vscode-restructuredtext is to show the actual sphinx output (no matter how slow it is). This JS library however can help me improve intellisense.
