### ISSUE TITLE
Make sure the terminal cli ipc handle feature works in local terminals under pty host

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117087]
I think it's currently broken. Deferring in https://github.com/microsoft/vscode/pull/116449

**Comment by meganrogge** [comment]
To verify:

- Launch VS Code
- In Code - OSS, open vscode folder
- In the terminal, run:
```./scripts/code-cli.bat --wait somefile```
- Confirm there are no errors and a file opens called somefile
