### ISSUE TITLE
Investigate how tunnel package avoids the proxy override

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#117054]
Customer feedback: The HDInsights extension continues using a proxy when HTTP_PROXY and NO_PROXY are set such that no proxy should be used because it depends on packages that do not support NO_PROXY.

We need investigate how the tunnel package avoids our proxy override and improve on it. Should also investigate which package exactly supports HTTP_PROXY, but not NO_PROXY and file an issue for them.

**Comment by chrmarti** [comment]
Fixed and filed a feature request for `@azure/ms-rest-js`: https://github.com/Azure/ms-rest-js/issues/439

**Comment by RMacfarlane** [comment]
@chrmarti how can this fix be verified?

**Comment by chrmarti** [comment]
To verify: In an extension use, e.g., the sample code at https://www.npmjs.com/package/http-proxy-agent with a non-existing proxy address and verify that the request fails with the Proxy Support user setting set to 'On' and it succeeds when set to 'Override'.

**Comment by chrmarti** [comment]
Reverting due to #120354.

**Comment by chrmarti** [comment]
Fixing again with a check to detect the docker-modem case from https://github.com/microsoft/vscode/issues/120354.

**Comment by TylerLeonhardt** [comment]
@chrmarti are the verification steps the same?

**Comment by chrmarti** [comment]
To verify (also verifying #120354 is still fixed):
- In an extension use, e.g., the sample code at https://www.npmjs.com/package/http-proxy-agent with a non-existing proxy address and verify that the request fails with the Proxy Support user setting set to 'On' and it succeeds when set to 'Override'.
- Verify #120354 is still fixed:
  - Set up a Docker context using SSH (e.g., using https://github.com/microsoft/vscode-remote-containers/tree/main/test-remotes/ssh-publickey).
  - Verify that the Docker extension's viewlet shows no error when that context is active and creating a container with that context makes the container show up in the Docker viewlet. (Note that Remote-Containers was not affected and cannot be used to verify the fix.)

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/117072898-0453fa00-ace6-11eb-8eb6-09fe2f8aad54.png)
![image](https://user-images.githubusercontent.com/2644648/117072948-17ff6080-ace6-11eb-9278-859ea8c862e4.png)

@chrmarti I see no difference doing the verification for the first bullet.

I took the quick pick sample and added the http-proxy-agent example to it:

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { window, commands, ExtensionContext } from 'vscode';
import { showQuickPick, showInputBox } from './basicInput';
import { multiStepInput } from './multiStepInput';
import { quickOpen } from './quickOpen';
import { simpleMultiStepInput } from './simpleMultiStepInput';
var url = require('url');
var http = require('http');
var HttpProxyAgent = require('http-proxy-agent');

export function activate(context: ExtensionContext) {
	context.subscriptions.push(commands.registerCommand('samples.quickInput', async () => {
		const options: { [key: string]: (context: ExtensionContext) => Promise<void> } = {
			showQuickPick,
			showInputBox,
			multiStepInput,
			quickOpen,
			simpleMultiStepInput
		};
		const quickPick = window.createQuickPick();
		quickPick.items = Object.keys(options).map(label => ({ label }));
		quickPick.onDidChangeSelection(selection => {
			if (selection[0]) {
				options[selection[0].label](context)
					.catch(console.error);
			}
		});
		quickPick.onDidHide(() => quickPick.dispose());
		quickPick.show();
	}));
	
	// HTTP/HTTPS proxy to connect to
	var proxy = 'http://localhost:3128';
	console.log('using proxy server %j', proxy);
	
	// HTTP endpoint for the proxy to connect to
	var endpoint = process.argv[2] || 'http://nodejs.org/api/';
	console.log('attempting to GET %j', endpoint);
	var opts = url.parse(endpoint);
	
	// create an instance of the `HttpProxyAgent` class with the proxy server information
	var agent = new HttpProxyAgent(proxy);
	opts.agent = agent;
	
	http.get(opts, function (res: any) {
		console.log('"response" event!', res.headers);
		res.pipe(process.stdout);
	});

}
```

**Comment by chrmarti** [comment]
What is the exact `opts` objects? I forgot to mention: If the hostname to connect to (not the proxy) is empty, localhost or 127.0.0.1, we still fall back to the agent in the options. This is to avoid #120354. So to verify, make sure the hostname is something else, like `nodejs.org` above. (Your code worked when I tried after removing the reference to `process.argv[2]`.)
