### ISSUE TITLE
Should staged colors default to non-staged ones?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#117043]
At some point new colors were introduced like `gitDecoration.stageModifiedResourceForeground`, bust most color themes have only colors set for ordinary `gitDecoration.modifiedResourceForeground`.

I think staged should default to normal variants unless they are specified.

**Comment by eamodio** [comment]
@misolori what do you think on this one?

**Comment by misolori** [comment]
I don't think I ever noticed that there were specific colors for staged + modified so I feel indifferent, but it must be in there for some reason. @joaomoreno thoughts since you looked at [the pr that added this](https://github.com/microsoft/vscode/pull/107318)?

**Comment by usernamehw** [comment]
They became much more noticeable since editor tabs support decorations now.
