### ISSUE TITLE
Flaky WorkspacesManagementMainService.getUntitledWorkspaceSync

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117032]
https://github.com/microsoft/vscode/runs/1934815343?check_suite_focus=true

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=106112&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=9f64420a-c490-5fef-d5f3-2bef0000fb37&l=7867
