### ISSUE TITLE
vscode cannot connect to the internet through my enterprise proxy. When attempting to update, I get error: net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by ryblogs** [microsoft/vscode#117065]
vscode cannot connect to the internet behind my enterprise proxy, I cannot update vscode or search for or install extensions. When attempting to update, I get error: 
net::ERR_CERT_AUTHORITY_INVALID  Source: Update Service. 

When attempting to install an extension I get error: 
We cannot connect to the Extensions Marketplace at this time, please try again later.

I tried disabling Http: Proxy Strict SSL. This does not solve the problem.

I tried entering my enterprise proxy under Http: Proxy. This also does not work. (My http_proxy and https_proxy environment variables are already set correctly).

- VS Code Version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
- OS Version: Windows_NT x64 10.0.18363 (Windows 10 Enterprise version 1909)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (3.60GB free)|
|Process Argv|--disable-extensions --crash-reporter-id da172840-e6e0-41db-ba95-fa22aa3e47c8|
|Screen Reader|no|
|VM|0%|
</details>

Steps to Reproduce:

1. Open vscode
2. Click on the settings gear on the bottom left
3. Click "Check for updates..."
4. Error "net::ERR_CERT_AUTHORITY_INVALID , Source: Update Service" appears
5. Click on Extensions on the left panel, Error "We cannot connect to the Extensions Marketplace at this time, please try again later." appears under RECOMMENDED

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by deepak1556** [comment]
This would be a case of missing CA cert from your system certificate store. Did this break only with version `1.53` or is this an issue with older versions too ?

Can you attach the log following these steps

* Clear any http(s)_proxy settings in vscode
* launch vscode with `code.cmd --log-net-log=<some-absolute-path>/netlog.json`
* Add the proxy settings
* Search for extensions
* Quit the application
* Attach the generated `netlog.json`, thanks!
