### ISSUE TITLE
Splitting terminal ignores "terminal.integrated.splitCwd": "inherited" and instead starts in workspace root

### ISSUE THREAD

**Issue by chrisdakin** [microsoft/vscode#117079]
- VS Code Version: 1.53.2
![image](https://user-images.githubusercontent.com/21347228/108551106-7313e080-72bd-11eb-86ab-4455359b93f3.png)

- OS Version: 11.2.1
![image](https://user-images.githubusercontent.com/21347228/108551151-8626b080-72bd-11eb-8087-dbdde71e31c2.png)

Steps to Reproduce:

1. Make sure `terminal.integrated.splitCwd` is set to `inherited`
2. Change directory
3. Split terminal (hotkey or by clicking split terminal)

Expected: New terminal starts in previous terminal's directory
Actual: New terminal starts in workspace directory

https://user-images.githubusercontent.com/21347228/108550527-ae61df80-72bc-11eb-9dc2-483b1ab132d8.mov

Does this issue occur when all extensions are disabled?: Yes

Additional notes: This happens 100% of the time for me. It first started happening when I updated both to the newest version of VS Code (January) and to Big Sur (updated both at the same time). This happens when the default integrated terminal is `bash` and when it is `zsh`.

**Comment by Tyriar** [comment]
This was disabled on Big Sur only as a workaround for https://github.com/microsoft/vscode/issues/105446

**Comment by Tyriar** [comment]
I see it was reverted upstream, we will eventually enable it again when it's definitely fixed in Electron @deepak1556 ?

**Comment by deepak1556** [comment]
@Tyriar the libuv fix is not reverted in vscode, I haven't responded to the last comment in https://github.com/microsoft/vscode/issues/105446, tl:dr; I have evaluated the failing scenarios in the libuv case and added workarounds for them.

**Comment by ebeloded** [comment]
With every VSCode I hope this issue is fixed. In the latest release - it still isn't. I'm experiencing this on Mac.

**Comment by Tyriar** [comment]
Splitting is working fine on the latest macOS now. Please open a new issue with specific repro steps if you see this issue again.
