### ISSUE TITLE
Setting "editor.hover.enabled" to false disables fading of unused variables

### ISSUE THREAD

**Issue by alanhett** [microsoft/vscode#117044]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a Javascript file with some unused variables
2. Go to settings and un-check "Editor > Hover: Enabled"

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is by-design since the `this variable is unused` message is shown by a hover 

With hovers disabled, we still fade out unused variables (and show them in the problems panel if you have made unused variables an error. You can also trigger the hover manually with the hover command
