### ISSUE TITLE
Regression: Unable to bypass ssl verification any more for corp firewall

### ISSUE THREAD

**Issue by ericanderson** [Microsoft/vscode#11702]
- VSCode Version: 1.5
- OS Version: 10.11.6

Steps to Reproduce:

1. Install a transparent man-in-the-middle firewall with a self signed cert and be sure that all traffic is being intercepted.
2. Install VSCode 1.4.
3. Notice that VSCode can't update extensions due to MITM.
3. Set http.proxyStrictSSL=false
4. Notice that VSCode can now update extensions or search extensions, etc.
5. Upgrade to 1.5
5. Notice that VSCode can no longer speak to the internet when trying to search for an extension

**Comment by mderriey** [comment]
The same issue happens to me after updating to 1.5. Using Windows 7 SP1.

**Comment by joaomoreno** [comment]
@ericanderson Can you show me how I can do step 1?

> Install a transparent man-in-the-middle firewall with a self signed cert and be sure that all traffic is being intercepted.

This has been the major problem in fixing proxy issues: I don't know how to reproduce all these scenarios.

**Comment by vlan-saxo** [comment]
@joaomoreno The same issue is reproduced with http/https proxies with self-signed certificates, I also reproduce this issue in our corporate network since the update.

**Comment by joaomoreno** [comment]
Awesome, was able to reproduce this using [Charles](https://www.charlesproxy.com). Will definitely buy this to keep the proxy issues in control.

**Comment by joaomoreno** [comment]
Found the issue, pushed to master. Will try to get it into a recovery build asap.

**Comment by mderriey** [comment]
Thanks for being so responsive! Keep up the good work!

**Comment by darron-haworth** [comment]
Thank you for the update! 👍

**Comment by seanmcbreen** [comment]
While we wait for a broad update you can use Insiders to work around this...
http://code.visualstudio.com/insiders

**Comment by joaomoreno** [comment]
@seanmcbreen The latest insiders doesn't have the fix yet, since last build happened Friday morning (CET). I'm triggering new insider builds and releasing them, so people get it.

**Comment by joaomoreno** [comment]
Verification: use [Charles](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) to proxy SSL requests to/from `https://marketplace.visualstudio.com/. Set up Code to use Charles as a proxy and set `strictSSL` to `false`.

**Comment by sbromberger** [comment]
Just wanted to say - bravo and many thanks for the quick fix!! 👍

**Comment by mrichman** [comment]
Confirm fixed on Windows 10.

**Comment by mderriey** [comment]
Thanks for fixing this so quickly and getting it out in a matter of days!

**Comment by joaomoreno** [comment]
Thanks for the confirmation guys.
