### ISSUE TITLE
Test: reveal in test explorer needs polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117073]
Have a test file open

1. Right click on a test -> `reveal in test explorer` it is nicely shown
2. Now scroll a bit in the test explorer, and trigger again the reveal action -> it is not shown 🐛 

Also reveal in test explorer should focus and select the item in the tree to make it obvious which one it is. Similar to how explorer does it for "reveal in sidebar"

**Comment by connor4312** [comment]
Reveal actually didn't do anything before, so I'll use this as a feature-request for verification. Summary:

- You can right click test icons in the gutter and "reveal" a test
- This should open the test explorer, if it's not already open, and show the test
- In the event that tests are not yet discovered (e.g. in a fresh window in the vscode window) the reveal action should happen once the requested test is discovered and displayed in the tree

**Comment by isidorn** [comment]
Thanks, I'll verify this.
