### ISSUE TITLE
Selected menu item background is no longer controlled by the theme

### ISSUE THREAD

**Issue by pingshunhuangalex** [microsoft/vscode#117001]
- VSCode version: 1.54.0-insider
- OS: macOS Catalina 10.15.7

Steps to Reproduce:

1. Pick a theme (I use `Community Material Theme Darker High Contrast`, but I don't think it matters)
2. Open the command menu
3. The background of the selected menu item now always uses a navy blue colour. Previously, it was light grey (may or may not be overridden by the theme I used)
4. If this is expected, just wondering what theme colour property I should use to override it back again

![image](https://user-images.githubusercontent.com/17170199/108457829-609ea480-72c7-11eb-8798-2ab0525ca8f3.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
> If this is expected, just wondering what theme colour property I should use to override it back again

Yes. It's part of #115873. Ping @joaomoreno for correct color token.

**Comment by joaomoreno** [comment]
The right change would be to swap customizing the `list.focusBackground` color and simply customize the `quickInput.list.focusBackground` one. This will be clearly laid out in our Release Notes. If you do that change today I suggest to target your extension to Code >= 1.54.
