### ISSUE TITLE
intellisense widget

### ISSUE THREAD

**Issue by heilerm** [microsoft/vscode#117048]
Issue Type: <b>Feature Request</b>

Hello,
I'd like to know where I can find a good description how to read
the cryptic thing in intellisese that comes up for example when I use
nodeJS and have for example the line app.get(). 
I often have a good feeling, but what exactly can I get out of the content 
written her. Sometomes I understand what parameter for example the
get() has, but sometimes I'm really lost, what I can/must use to make 
a useful get() call.

BR
Matthias Heiler

VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

**Comment by jrieken** [comment]
Check out this: https://code.visualstudio.com/docs/editor/intellisense

**Comment by heilerm** [comment]
Hello Johannes,
thanks for your reply.
It helped quite a lot but I’m still struggling with texts like: (from nodejs)
(method) NodeJS.EventEmitter.on(event: string | symbol, listener: (...args: any[]) => void): EventEmitter

I’m reading it as follows:
I can use the function “on()” on the Class (cause EventEmitter is written in UpperCase)  EventEmitter and pass two paramaters in.
First: a string or a symbol and second a listener. The on() Method returns an object of class EventEmitter
What I’m struggeling with is: how do I have to interpret the (… args: any[])?
I would read it as:  you can add to the listener a list or arguments which are of type any[], which is to me any array.
How do I know that the listener is a callback function? That’s what I found in other examples. But I would not interpret it from the stuff I’m getting from intellisense
And what does the “=> void:” mean? The listener is something that calls a method which returns nothing? Here I have the most trouble to read it.
And also what is the other option for the event? I can pass in a string and a symbol. What is a symbol? How nice would it be to get more details to for example
For the symbol with a mouse over or to args:any[].
In general: is there a description how to get further in reading that (for me) rather cryptic info.
I know it’s very helpful information , but I can’t make the best out of it.

BR
Matthias Heiler
