### ISSUE TITLE
API: one to one mapping between notebook document and kernel

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117077]
Currently `NotebookKernel` is attached to an editor, and reasoning behind this was kernels might need to talk to the web view for output and we don't have a story for multi webview <--> kernel communication at that time (or mostly I don't understand how it work at that time being). Now Jupyter already implements support for ipywidgets, which is the major user of the webview communication channel, we found the limitation of kernel being dependent on notebook editor is not necessary.

The new proposal will be

* 1 to 1 mapping between `NotebookDocument` and `NotebookKernel`
* Kernel is resolved when users want to execute the document/cell. It doesn't require the editor being opened
* When a notebook document is attached to an editor, the kernel provider will get a `comm` object tied to the editor.
  * If there are multiple editors for the same document, the kernel provider should get multiple `comm` objects. The kernel is responsible for broadcasting messages to multiple `comm`s
 * Execution results, including execution count, state, ellapsed time and outputs are all applied to the `NotebookDocument`, so the changes will be picked up by all editors opened for the same document.

**Comment by jrieken** [comment]
This has happened with the new notebook controller API. Internally, a notebook can have only one kernel (tho a kernel can be associated to many notebooks if it wants)

**Comment by jrieken** [comment]
Tho, there are still UI glitches and this only works for the new API. The glitches should be remove next week
