### ISSUE TITLE
Crashes upon launching, "perforce: invalid configuration"

### ISSUE THREAD

**Issue by chloesheen** [microsoft/vscode#117082]
- VS Code Version: 1.53
- OS Version: MacOS Big Sur 11.1

Steps to Reproduce:

1. uninstalled previously crashing VSCode (deleted .NET, mono. etc following the support article)
2. reinstalled latest version 1.53, opened it, crashes immediately with "Perforce: invalid configuration" message (screen recording attached)

https://user-images.githubusercontent.com/16697772/108554464-1d8e0280-72c2-11eb-8347-15a38f62c980.mov

Does this issue occur when all extensions are disabled?: **Yes**/No
I uninstalled and reinstalled, so the "code" command doesn't work anymore.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Does it happen if you launch code from CLI as `code --disable-extensions`?
Does it happen if you try to launch Insiders build? https://code.visualstudio.com/insiders/

**Comment by chloesheen** [comment]
1) It still crashes using code --disable-extensions
2) launching Insiders build seems to be working fine. Is this my only option, or is there a way to repair VSCode on my machine?

Thanks!

**Comment by deepak1556** [comment]
Does it crash when you start with `code --user-data-dir /tmp/vscode` ? 

> launching Insiders build seems to be working fine

Insiders version will get promoted to stable at the end of every iteration. So you would get the fix in version `1.54`. But to confirm if this is not an issue with settings cache, please try the above.

**Comment by chloesheen** [comment]
Yup, still crashes that way.

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash report.

**Comment by chloesheen** [comment]
[490315f1-3dbf-417d-957a-5d646fc2e85b.dmp.zip](https://github.com/microsoft/vscode/files/6039795/490315f1-3dbf-417d-957a-5d646fc2e85b.dmp.zip)

**Comment by deepak1556** [comment]
Thanks for the report, its a `SIGABRT` from the `vscode-encrypt` module same as https://github.com/microsoft/vscode/issues/116690 . The module is mainly used for storing authenticated credentials from extensions, settings sync, proxy auth. Starting with a new data dir should eliminate settings sync and proxy auth as potential cause.


Can you also check if it crashes with a new user data dir and disabling extensions, `code --user-data-dir /tmp/vscode-new --disable-extensions` ,

**Comment by deepak1556** [comment]
Additionally can you confirm if you had enabled settings sync or performed authentication with any extension ?

Merging to https://github.com/microsoft/vscode/issues/116690

**Comment by chloesheen** [comment]
Thanks, it still crashes with `--user-data-dir /tmp/vscode-new --disable-extensions`. I did use the remote ssh extension which required authentication.
