### ISSUE TITLE
vscode-references-view does not de-duplicate results like the built in ReferencesModel

### ISSUE THREAD

**Issue by atscott** [microsoft/vscode#117095]
The built-in "go to references" command in vscode uses the `ReferencesModel` to de-duplicate reference results: https://github.com/microsoft/vscode/blob/36dd567011eda09317a76d5dcb820fa9961eb786/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L171-L182
Equal uri's and ranges constitute duplicate results:
https://github.com/microsoft/vscode/blob/36dd567011eda09317a76d5dcb820fa9961eb786/src/vs/editor/contrib/gotoSymbol/referencesModel.ts#L293-L295
The `ReferencesModel` of the extension does not de-duplicate results at all, but instead always pushes each location to the containing `FileItem`'s references list: https://github.com/microsoft/vscode-references-view/blob/f1b526b39c97981c81d52a98d6e66f8f699dc38a/src/references/model.ts#L73

**Comment by atscott** [comment]
Hi @jrieken, I was wondering what the ETA for a fix for this would be (#117424 if approved). We're getting a lot of reports in the Angular Language Service extension repo for duplicate results in "find all references". If this will take some time to agree on a fix and get it into a release, I think we'll want to implement a workaround on our end for now.  Thanks for your help!

**Comment by jrieken** [comment]
> Hi @jrieken, I was wondering what the ETA for a fix for this would be (#117424 if approved).

This is scheduled for March, meaning it will ship as stable early April and in insiders as soon as it is merged

**Comment by RMacfarlane** [comment]
@jrieken what's a good way to verify this?

**Comment by atscott** [comment]
Hi @RMacfarlane - I can verify this today. You'd need to know about an extension that provides reference results that would be duplicates of another extension and then run the "find all references" action from the built in [Reference Search View](https://marketplace.visualstudio.com/items?itemName=ms-vscode.references-view) extension (which does not de-duplicate results)

I can verify this with the angular language service by reverting https://github.com/angular/angular/commit/10aa5641dd85a5eb89f1d1590b9df4119015c29f

**Comment by RMacfarlane** [comment]
Thanks @atscott!
