### ISSUE TITLE
Shared process: reduce or remove delay

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117067]
With the change of hosting terminals in the shared process, we should revisit our 3s delay of spawning the shared process on startup.

This came originally in as https://github.com/microsoft/vscode/commit/80278f8e8bfe1e231529fc1c1833091fa481f02f. However later we added lifecycle phases on the main side and I think as such we could remove the delay entirely:

https://github.com/microsoft/vscode/blob/608e8791ff194e81a10ac0d963471922ddc9b6e0/src/vs/code/electron-main/app.ts#L518-L518

//cc @Tyriar
//cc @jrieken for startup perf

**Comment by bpasero** [comment]
The 3s delay is removed, we still wait for "after window open" before spawning it though: https://github.com/microsoft/vscode/commit/92c0878f39e8d8cad9c41615f96b4b4867687645

**Comment by Tyriar** [comment]
Sounds great, thanks!
