### ISSUE TITLE
Add `onFileSaveAs` event

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#117083]
When a file is renamed in VS Code, the `onDidRenameFiles` event fires, but it would be useful to have a similar event `onDidSaveAs` that has the same shape as the rename event, namely it has both `oldUri` and `newUri` properties.  This event should fire when:

1. The user clicks File -> Save As (or Ctrl+Shift+S).
2. A new untitled document (or notebook, or custom editor, etc.) is saved for the first time.  In this scenario, `oldUri` would be of the form `untitled:Untitled-1.txt` and `newUri` would be `file:///C:/path/to/file.txt`.

**Comment by brettfo** [comment]
How do we know we're properly mapping the notebook that comes in via `onDidCloseNotebookDocument` to the new one in `onDidSaveNotebookDocument`?  How can that be distinguished from the case where a user closes one notebook then immediately saves another?  Similarly, if I listen to these events now, just the act of closing a notebook seems to fire both `Close` and `Save` events; in this case I _do_ want to shut down the backing process, but I have no way of distinguishing these cases.

**Comment by bpasero** [comment]
Tracking as feature request for normal editors, but if you need specific notebook API I suggest opening a separate issue.
