### ISSUE TITLE
Call stack debug actions aren't keyboard accessible

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117006]
Unless the mouse is hovering over that row, the actions don't show up, so you can't access them with the keyboard

![image](https://user-images.githubusercontent.com/641685/108465933-de739900-7250-11eb-9bc6-4c0fded0d79c.png)

**Comment by isidorn** [comment]
Great catch. They should also show up on line focus. I will look into fixing that.
Thanks for reporting this!
