### ISSUE TITLE
Cannot collapse Handlebars tags, only the HTML

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#117025]
- VS Code Version: 1.53.2
- OS Version: macOS Big Sur

<img width="817" alt="Screenshot 2021-02-19 at 5 06 03 PM" src="https://user-images.githubusercontent.com/9585787/108489975-c8a7b780-72d4-11eb-9b62-1c949d826493.png">

Steps to Reproduce:

1. see screenshot, on line 1055 I should be able to collapse it. should work on all handlebars helper groups like ```#each```, ```#if``` etc

**Comment by aeschli** [comment]
We only support HTML out-of the box. Full Handlebars support would have to come from an extension with a proper understanding of the Handlebar syntax.
