### ISSUE TITLE
[FR] Option to configure word-based suggestion triggering number

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#117000]
Currently, the word-based suggestion shows up when reaching 7 letters, would like an option to change the triggering number, so it could show up faster.

![image](https://user-images.githubusercontent.com/28700378/108457163-0395f500-72ad-11eb-95d7-dd199cf3c07f.png)

**Comment by jrieken** [comment]
> the word-based suggestion shows up when reaching 7 letters,

No such condition exists in vscode. Please add full repo steps and actual code samples, no screen shots
