### ISSUE TITLE
Debugging tests does not work for me 

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117068]
Debugging tests does not work for me in latest insiders. 

1. `link.detector.test.ts` 
2. add breakpoints for example on line 89
3. right click on margin -> debug test

Test is run but not stopped at breakpoints

**Comment by connor4312** [comment]
If you add a delay before hitting your breakpoint, does it work then? Currently tests don't wait for the debugger to attach before running; for me this almost never prevents me from debugging, but it is timing-based and might be different for you.

If that doesn't work, make sure there's no old OSS/test processes stranded listening on the port and preventing the new instance from starting. This happens to me on OSX sometimes, though I haven't looked into it yet...

**Comment by isidorn** [comment]
There was a process lying around. Once I killed everything it was ok.

**Comment by connor4312** [comment]
Ok, thanks. I can try to look at this during debt week, @bpasero could you toss some code pointers on where to start investigating the issue with the orphaned process after running tests?

**Comment by bpasero** [comment]
> start investigating the issue with the orphaned process after running tests?

What process is it?

**Comment by connor4312** [comment]
The main process, launched as `eleectron test/unit/electron/index.js --no-sandbox ... --remote-debugging-port=9222`

**Comment by connor4312** [comment]
I was able to reproduce this by:

1. Playing around and running tests. Eventually on one of the runs, the renderer crashed
2. The main process, launched as `electron test/unit/electron/index.js .... --remote-debugging-port=9222`, was still running. VS Code was "stuck" in a running state since the provider was still looking for data.
3. I reloaded VS Code. The main process was still running and I could no longer debug. (Confirmed in lsof that the main process was indeed still listening on 9222)

**Comment by bpasero** [comment]
Ah this is about unit tests, I think that support was [originally](https://github.com/microsoft/vscode/commit/bb1e72c7341d86856434b18f2c27f99dfce04941#diff-6bf0ec0f0c8f266db0ef29ea6a542a84d1d9493305be25dd428e476c6b683a30) added by @jrieken .

**Comment by jrieken** [comment]
Accepting PRs 😆 The electron test world wasn't really designed to be used like that, tho I am proud of how far you could take it. I can walk you through things if you like

**Comment by connor4312** [comment]
I put in a fix that seems to work with my simulated crash -- exiting the app with a status code whent he renderer goes away, if completion was not already gracefully signalled. Let me know if you hit this again.

**Comment by isidorn** [comment]
This works great now, thanks -> verified
