### ISSUE TITLE
Code Lens cannot find the reference in Object Shorthand property names

### ISSUE THREAD

**Issue by nztraveler** [microsoft/vscode#117021]
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
There are three simple javascript files, and the code lens of the module a.js can only find 1 reference in c.js.
In the b.js, the a is referenced in the way of Object Shorthand property names, which is not be found in code lens.

a.js
<pre>
const a = '123';  
export default a;
</pre>

b.js
<pre>
import a from './a.js';  
// referenced in the way of Object Shorthand property names, cannot be found by code lens.  
console.log({a});
</pre>

c.js
<pre>
import a from './a.js';  
console.log(a);
</pre>

![image](https://user-images.githubusercontent.com/22699159/108482387-62bb3000-72d4-11eb-95b8-500fee942a9d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Also happens in the single file:

```js
export const abc = 123;

console.log({ abc });
```

**Comment by mjbvz** [comment]
Should be fixed by updates TS change

To verify:

1. Install typescript@next in a workspace
2. Switch to the workspace version of TypeScript
3. Confirm that you now see the correct reference count for the examples above
