### ISSUE TITLE
Comment Block/Line Action not Working from F1 or with keyboard shorcut

### ISSUE THREAD

**Issue by miguelvalente** [microsoft/vscode#117031]
- VS Code Version: 1.53.1
- OS Version: Kernel: 5.10.16-arch1-1

Steps to Reproduce:

1. Select Line or Block Text 
2.Press F1
3.Select Toggle Line Comment or Toggle Block Comment
4.It does not work 

Does this issue occur when all extensions are disabled?: Yes/No

Yes. I even deleted settings.json to no avail.

**Comment by IllusionMH** [comment]
/needsMoreInfo

What language?
Do you have any error notifications before that?

**Comment by miguelvalente** [comment]
> /needsMoreInfo
> 
> What language?
> Do you have any error notifications before that?

I'm writing in python. I don't think its a keybinding issue I'm directly calling the actions.

Ctrl+A works for example.

**Comment by rzhao271** [comment]
I'm unable to reproduce the issue with a Python file. Does it still show up for you when trying VS Code Insiders? Also, do you have the Python extension installed?
