### ISSUE TITLE
TypeScript: nested generic detail incorrect

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#11706]
- VSCode Version: 1.4.0
- OS Version: latest
- TS version: latest 2 beta

Steps to Reproduce:

Given:

``` ts
type Foo<T> = { foo: T };
const y = <X, T>(t: Foo<T>) => t;
y({ foo: 2 })
```

When I inspect `y` by hovering over it, I expect it to have the type: `<{}, number>(t: Foo<number>) => number`, but it actually has the type `<{}, number>(t: Foo<{}, number>) => number`.

Where is `Foo` shown to receive more generics that it has asked for?

**Comment by waderyan** [comment]
@OliverJAsh thank you for opening this issue. This falls under TypeScript language service. Moving to their repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10793
