### ISSUE TITLE
Test: Review new Pull Model Diagnostic proposal

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#117042]
Refs: https://github.com/microsoft/language-server-protocol/issues/737

- [x] anyOS @aeschli 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117042%0A%0A)

---

There is not a proposed implementation for a document diagnostic pull model. The proposal is here:

https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/proposed.diagnostic.ts#L1

Please review the proposal and provide feedback. Open issues in the https://github.com/microsoft/vscode-languageserver-node repository

In case you want to test it there are next libraries that implement the proposal. They are `vscode-languageclient@7.1.0-next.4` and `vscode-languageserver@7.1.0-next.4`. 

The pull model got also adopted in ESLint and can be seen here: https://github.com/microsoft/vscode-eslint/blob/dbaeumer/pullModel/server/src/eslintServer.ts#L1089

**Comment by w0rp** [comment]
Thank you for putting this proposal together. I think this pretty much does hits the nail on the end in terms of the problem I was describing for language clients and how it can be solved.

I had a look through the proposed types, and the all seem to make sense. Should clients detect if the "pull" model is supported at all with `typeof diagnosticProvider === 'object' && typeof diagnosticProvider.mode === 'number' && diagnosticProvider.mode > 0`? It might be worth briefly explaining how to detect which servers support the "pull" mode or not in the documentation.

**Comment by aeschli** [comment]
The proposal is simple and makes sense to me. It will enable programmatic computation for diagnostics w.g. on virtual documents. 

Some questions:

What is the benefit for `DiagnosticContext.triggerKind`? How does that help the server when evaluating diagnostics? Will it serve as a replacement to the existing open/change/save events on documents?

Is the plan to also support a onDidChangeDiagnostic event and a way to turn off the current push model (for clients that prefer a pull only model)

The copyright says TypeFox. Is that intended?

**Comment by dbaeumer** [comment]
@aeschli good catch about the copyright. This was copy paste from call hierarchy were the initial PR came from them. I fixed it.

> What is the benefit for DiagnosticContext.triggerKind? How does that help the server when evaluating diagnostics? Will it serve as a replacement to the existing open/change/save events on documents?

Yes, it is a replacement for the server to listen for open/change and save events and triggering a validation. Instead the client pulls and manages cancellation and ensures that there is only one active pull for a document for a given point in time.

> Is the plan to also support a onDidChangeDiagnostic event and a way to turn off the current push model (for clients that prefer a pull only model)

The change event is already there. See https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/common/proposed.diagnostic.ts#L195 and the implementation https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/proposed.diagnostic.ts#L102

And a server can now only use pull. I converted the ESLint extension to only use pull. No push of diagnostics anymore.

**Comment by dbaeumer** [comment]
@w0rp Your suggested check is basically hidden here: https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/proposed.diagnostic.ts#L107. This returns [undefined, undefined] if a server doesn't support pull.

**Comment by aeschli** [comment]
@dbaeumer Still puzzled on the benefits of triggerKind. Can you give an example how the server would use the information?
The server needs to return a new set of diagnostics on request, and have to be accurate and the same set of dialognistics, regardless how the request was triggered.. I'm guessing here: Can it return cached diagnostics if it gets DiagnosticTriggerKind.Invoked? Sounds risky to me to rely on the client here.

Oh, `workspace/diagnostic/refresh` is a change event, that was unclear to me. Maybe the method name could be improved; something with `did.  Also I would have expected an Notification instead of a request.

Can the client ask for all errors in the whole workspace? (without knowing the URIs of all resources)

**Comment by dbaeumer** [comment]
@aeschli the reason I added it is as follows: if pull is configured on save the server could use the file on disk instead of syncing the file content (in case things are file URIs). In principal a server can register for `type` and `save` in case it wants to do some different analysis (more expensive validations on save only). To ease this for a server I thought it would be good for a server to know which from of diagnostic to run without inferring it from previous notifications / requests.

I also got feedback from the VS team about it and they mention that we should two more modes `active` and `inactive` to trigger the pull when the editor changes.

> `workspace/diagnostic/refresh`

I named it that way since I used the same naming for semantic tokens refresh. When I added it for semantic tokens I wanted to ensure that this is not a event a server should fire (eg. onDid...). It is basically a request to refresh.

I made it a request so that a server can know if the client reacted on it. It is hard with notifications to determine that.
