### ISSUE TITLE
"Unable to attach to browser" when using pwa-edge launch config to launch a browser if VSCode is run with Administrator

### ISSUE THREAD

**Issue by a1exwang** [microsoft/vscode#117005]
- VS Code Version: 
Tested on these two versions:(code --version output)
```
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```
and 
```
1.54.0-insider
6eaef7d42f982a0e9b22ac465245fc2c27721fd0
x64
```

- OS Version: Windows 10 19042.804

See the video for more detailed info

https://user-images.githubusercontent.com/9698542/108463973-49a58580-72ba-11eb-8b16-4bb726ee4d67.mp4

1. Create a empty folder, create a .vscode folder in it and create a launch.json in .vscode with the following content:
```
{
    "version": "1.0.0",
    "configurations": [
        {
            "name": "Launch browser",
            "type": "pwa-msedge",
            "request": "launch",
            "url": "https://www.google.com",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
2. Open VSCode with Administrator and go to `Run` and click `Launch browser`

3. It will pop up a box saying `Unable to attach to browser". However, it launch VS Code without Administrator access, it will work.

Does this issue occur when all extensions are disabled?: Yes(Open `cmd.exe` with Administrator and start with `code --disable-extensions`)

**Comment by alexr00** [comment]
I followed the steps in the original issue. Edge opens in admin mode, but I also get this dialog from VS Code:

![image](https://user-images.githubusercontent.com/38270282/112476646-6b3ed480-8d72-11eb-9cdc-5cc135fc71d0.png)

**Comment by connor4312** [comment]
@alexr00 I'm not able to repro this, can you share the launch config you're testing with?

**Comment by connor4312** [comment]
Closing to see if someone else is able to verify. This is the launch config I'm using: 

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-msedge",
      "request": "launch",
      "name": "test",
      "url": "http://localhost:8080",
    },
  ]
}

```

**Comment by roblourens** [comment]
Works for me
