### ISSUE TITLE
Applying Icon theme BSD

### ISSUE THREAD

**Issue by sbowler** [Microsoft/vscode#11703]
- VSCode Version: 1.5.0
- OS Version: Windows 10 Enterprise version 1511 , OS build 10586.494

Steps to Reproduce:

1. Go to file -> preferences -> Icon Theme
2. Try to apply the Seti Theme

It appeared to apply the theme, but I immediately got a BSD with Bad Pool Header. I do appear to have a tsc compiler mismatch version with a globally installed version, but I'm not sure that could be related in any way.

After rebooting the system and trying again it worked without a BSD. There could be an issue related to having it(vscode) open, doing the update and then having it re-open after the update and then doing this. I wish I could provide more information. Also curious if this happens to anyone else.

**Comment by aeschli** [comment]
BSD is a blue screen? That wouldn't be related to tsc, but a bug in Electron.
Updating while VSCode still open could definitely be an an issue.
@joaomoreno Should the installer prevent that?

**Comment by joaomoreno** [comment]
This just sounds like a random Electron crash, which gets sent to us via the crash reporter. Has nothing to do with updates.

**Comment by sbowler** [comment]
To clarify, I meant BSOD so yes. No, it did not update while open, it was open, closed to update, then re-opened automatically like you would expect when you auto-update from within vscode. 

There was no indication that a crash report was sent anywhere, but if you're saying you get reports for any blue screens than that makes sense to close this issue and open another issues if needed from a report.
