### ISSUE TITLE
Allow to set an access token to login into Github 

### ISSUE THREAD

**Issue by vymarkov** [microsoft/vscode#117011]
I didn't found a way how I can login into Github from VS Code by using the access token. The reason why is I need this, that I want to use VS Codium / GitPod to not be limited by usage only VS Code.

May be it's already implemented, but it is not obvious for user.

**Comment by vymarkov** [comment]
Hi! Any updates on that?

**Comment by TylerLeonhardt** [comment]
Sorry, you'll have to ask VS Codium or GitPod for such a feature as we are not planning on supporting this ability in vscode itself.
