### ISSUE TITLE
Files appear empty after August 2016 updated

### ISSUE THREAD

**Issue by jwoodhull** [Microsoft/vscode#11701]
- VSCode Version: August 2016 Update
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Update to the latest version of VSCode
2. Open any text file.

Notice that the file appears to be empty.

**Comment by ahejlsberg** [comment]
I'm seeing the same thing!

**Comment by jailsonayogo** [comment]
I got the same issue and to fix it I just deleted my `settings.json`. Then, I restored my settings file and it seems that the issue was caused by this line on my settings: `  "editor.fontSize": -4 `

**Comment by JCarran0** [comment]
Same problem here.  My settings.json editor.fontSize was set to 0. Thanks @jailsonayogo for saving me some time.

**Comment by kieferrm** [comment]
@ahejlsberg similar issue for you?

**Comment by percyabrown** [comment]
I am experiencing the same thing on Windows 10 and my setting.json file only has 
  "php.validate.executablePath": "C:/PHP53/php.exe"

**Comment by jwoodhull** [comment]
Thanks for the heads up.  My fontSize and lineHeight were set to 0

**Comment by mjkeating** [comment]
I had the same issue. I removed the 'fontSize: 0' line from my user settings file (settings.json) to fix it - thanks to this thread.

**Comment by kieferrm** [comment]
`0` literally setting the font size to `0`, and you need to open the file in some other editor. The locations are:
Windows: `%APPDATA%/Code/User/settings.json`
Linux: `~/.config/Code/User/settings.json`
Mac: `~/Library/Application Support/Code/User/settings.json`

**Comment by percyabrown** [comment]
Thanks @kieferrm ! Using Notepad++ changed the settings in %APPDATA%/Code/User/settings.json   from "editor.fontSize": 0, "editor.lineHeight": 0, to "editor.fontSize": 14, "editor.lineHeight": 14 and I can now see the text.

**Comment by kieferrm** [comment]
#11715 reports the same issue. We currently test a fix.

**Comment by kieferrm** [comment]
We have released a recovery build. It's 1.5.1.

**Comment by kieferrm** [comment]
Duplicate of #11715 .
