### ISSUE TITLE
Better Folder Explorer

### ISSUE THREAD

**Issue by jrcsdev** [microsoft/vscode#117046]
VSCode could improve your File Explorer. It could include 2 things Microsoft Visual Studio has.

1. An always visible text field to filter the list of files.
2. When filtering is used, the file listing must also include files from unexplored subfolders.

Currently when filtering is used (an option that exists, but well hidden), the output skips files from subfolders that have not yet been opened in the browser.

I know that pressing CTRL + P can access the top bar and we can achieve the same, but this bar only allows to select one file at a time, and it becomes infectious if I need to open several or all the files that match the filter.

Thanks for taking the time to read this idea. Greetings.

PD:
Microsoft Visual Studio (Solution Explorer) is a good reference for this enhancement.
![visual-studio-solution-explorer](https://user-images.githubusercontent.com/765950/108518878-1271ad00-7297-11eb-8130-4a66db8607f8.png)

**Comment by isidorn** [comment]
Thanks for sharing this feedback, however this is already captured by quite some issues. There is already issues that filtering should first resovle all folders which would bascially solve this.
Since this issue is covered by that one I will have to close it as a duplicate.

All the best

**Comment by jrcsdev** [comment]
I understand that this can solve the main problem, but it would still be nice to consider that the text field to filter should always be visible, because I had been using vscode for a long time and, I found out that I could filter the file listing because I read it in a forum. It's confusing to think that if you click on a filename, or on an empty area, you can start typing to filter.

Anyway thanks for answering.

**Comment by isidorn** [comment]
Does not align with our UI imho

**Comment by jrcsdev** [comment]
I understand, thanks for responding. I'll see if I'm able to create an extension.
