### ISSUE TITLE
Quick pick focus color is incorrect

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117007]
Since the changes in the list/tree widget focus work, the quick pick has a different focus color

![image](https://user-images.githubusercontent.com/641685/108467878-e2ed8100-7253-11eb-9883-84ab73401eef.png)

**Comment by gjsjohnmurray** [comment]
Is this #117001?

**Comment by joaomoreno** [comment]
Yeah: https://github.com/microsoft/vscode/issues/117001#issuecomment-782081399

Unfortunately I don't see a clear way forward to get this fixed without having themes adopting the change. We will make sure they get notified in the release notes.
