### ISSUE TITLE
Which problem matcher have you attached to the build task. The standard $mscompile matcher actually hanldes this. It has the following regex

### ISSUE THREAD

**Issue by selassje** [microsoft/vscode#117076]
Which problem matcher have you attached to the build task. The standard $mscompile matcher actually hanldes this. It has the following regex
```js
/^(?:\s+\d+\>)?([^\s].*)\((\d+|\d+,\d+|\d+,\d+,\d+,\d+)\)\s*:\s+(error|warning|info)\s+(\w{1,2}\d+)\s*:\s*(.*)$/
```

_Originally posted by @dbaeumer in https://github.com/microsoft/vscode/issues/50426#issuecomment-430179198_

**Comment by selassje** [comment]
This regex does not match >2FileName, due to ^(?:**\s+**\d+\>)

**Comment by alexr00** [comment]
Can you provide the full output of the task?

**Comment by selassje** [comment]
Output:
![image](https://user-images.githubusercontent.com/42682959/108729360-b921ac00-752a-11eb-95e7-d8d807b72008.png)

And the "Problems" tab:

![image](https://user-images.githubusercontent.com/42682959/108729615-030a9200-752b-11eb-89b2-6530616ea8e7.png)

in my tasks.json:

 "problemMatcher": "$msCompile",

**Comment by alexr00** [comment]
Can you also please share the full tasks from your `tasks.json` file?
