### ISSUE TITLE
vscode start printing errors in the terminal when launched from it

### ISSUE THREAD

**Issue by ecruzolivera** [microsoft/vscode#117056]
Issue Type: <b>Bug</b>

Since last update each time that is launched from terminal it opens, starts printing this logs in the console and dont returns the prompt,  if the terminal is closed is closed vscode is also closed.

```bash
code .
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[main 2021-02-19T16:16:27.275Z] update#setState idle
(node:25727) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:25727) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-02-19T16:16:57.286Z] update#setState checking for updates
[main 2021-02-19T16:16:57.369Z] update#setState idle
```

the curious part is if open a second vscode in another terminal, it prints only this and returns the prompt control

```bash
code .                           
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3400G with Radeon Vega Graphics (8 x 2560)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|29.40GB (20.55GB free)|
|Process Argv|. --crash-reporter-id 303e193c-687a-4906-9665-f5cf51203703|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (48)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.1
vscode-eclipse-keybindings|alp|0.12.0
vscode-browser-preview|auc|0.6.7
QML|bbe|1.0.0
vscode-tailwindcss|bra|0.5.9
better-toml|bun|0.3.2
cmake-format|che|0.6.11
doxdocgen|csc|1.1.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
vscode-shell-snippets|Dee|0.3.1
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
shell-format|fox|7.0.1
go|gol|0.22.1
plantuml|jeb|2.14.3
dupchecker|jia|0.1.7
hex-fmt|ker|1.0.0
language-cmm-vscode|kho|1.2.0
graphql-for-vscode|kum|1.15.3
tailwind-sass-syntax|mac|1.2.1
cortex-debug|mar|0.3.12
rust-analyzer|mat|0.2.489
rainbow-csv|mec|1.8.1
git-graph|mhu|1.28.0
hg|mrc|1.7.1
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.576440691
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
cargo|pan|0.2.3
vcast-lang|Pat|0.2.0
material-icon-theme|PKi|4.5.0
vscode-qt-for-python|sea|0.6.1
crates|ser|0.5.6
gitconfig|sid|2.0.1
numbermonger|sof|0.5.0
code-spell-checker|str|1.10.2
ninja|sur|0.0.1
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.1
srecord|xia|0.0.3
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by deepak1556** [comment]
Crash reporter log has been fixed in https://github.com/microsoft/vscode/issues/115888

Can you test with latest insiders https://code.visualstudio.com/insiders

**Comment by ecruzolivera** [comment]
in the latest insiders (using ubuntu snap packages) is launching fine from the terminal.

**Comment by deepak1556** [comment]
Thanks for checking, merging to https://github.com/microsoft/vscode/issues/115888
