### ISSUE TITLE
Explorer: Folders open only with double click

### ISSUE THREAD

**Issue by tsabolov** [microsoft/vscode#117055]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Open any folder with subfolders
- Click on any of subfolders

Expected:
* Folder is expanded

Actual:
* Folder does not expand. Double click is needed to expand the folder.

VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:17:50.205Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id 14003d70-0772-4ffd-a913-83e3926021af|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.23.1
gitlab-workflow|Git|3.13.0
todo-tree|Gru|0.0.196
vscode-favorites|how|1.8.3
dotenv|mik|1.0.1
vscode-docker|ms-|1.10.0
python|ms-|2021.2.576481509
jupyter|ms-|2021.2.576440691
vetur|oct|0.32.0
rust|rus|0.7.8
vscode-icons|vsc|11.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15

</details>

**Comment by isidorn** [comment]
This should be fixed in latest insiders from next week
fyi @joaomoreno
