### ISSUE TITLE
Emoji Panel Does Not Work Properly Anymore

### ISSUE THREAD

**Issue by d-e-v-esh** [microsoft/vscode#117023]
Issue Type: <b>Bug</b>

# Steps to Reproduce

 - Windows Key + . (period) => Opens up the emoji panel
 - Writing anything while the panel is showing searches an emoji that matches the text that is being written.
 - The emoji panel reacts correctly to whatever emoji we search for but the search text being written doesn't show up like it used to before.
 - It used to show up covered in a highlighted way so it is distinct from other letters that doesn't come under the emoji search query.
 ---
 -  This stopped working after the recent updates.
 - Writing anything does not show up while the emoji panel is on.
 - Disabling all the extensions does not help the problem.
 - This was not a problem on earlier versions.
 - I noticed it while putting emojis in the commit messages but it doesn't work on the normal code area either

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (1.65GB free)|
|Process Argv|--crash-reporter-id 3ac050ed-0dbb-4ec8-b92d-2b91c4699d0f|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
notes|can|1.1.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-styled-components|jpo|1.5.0
react-native-snippet|jun|0.5.6
kite|kit|0.141.0
graphql-for-vscode|kum|1.15.3
vscode-language-babel|mgm|0.0.30
vscode-docker|ms-|1.10.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
vscode-css-peek|pra|4.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-scss-formatter|sib|2.1.0
js-jsx-snippets|sky|10.1.0
code-spell-checker|str|1.10.2
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
omi-snippets|Wsc|2.2.8
material-theme|zhu|3.9.15
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589
pythontbcf:30258532

```

</details>

**Comment by jeff-r-koyaltech** [comment]
Same issue on Mac OS Big Sur (v 11.4) and VS Code 1.57.0.
The keyboard shortcut is Control + Command + Spacebar. It used to work, but stopped working after my Big Sur upgrade.
Other apps (like my browser) still allow that shortcut to show the emoji widget. 🤔

**Comment by alexdima** [comment]
@jeff-r-koyaltech For macOS, please see https://github.com/microsoft/vscode/issues/135480#issuecomment-963946617 . If you use a laptop with a Touch Bar, then the keybinding is changed dynamically, by macOS to be the globe symbol that is displayed on the Touch Bar.

**Comment by alexdima** [comment]
@d-e-v-esh With the steps from #135153 , I was able to reproduce something similar to what you describe also in Chrome and in Notepad, not just in VS Code. If I switch my keyboard layout to Chinese - Pinyin, open the emoji picker using <kbd>win</kbd>+<kbd>.</kbd>, and press <kbd>A</kbd>, nothing happens. The emoji picker does not react to my pressing <kbd>A</kbd>. Only pressing `Escape` will dismiss the emoji picker. If I try the same steps with the English keyboard layout, then the emoji picker appears to filter based on <kbd>A</kbd>. Given this issue reproduces in all kind of other software on Windows, not just VS Code, I will close this issue as `upstream`.
