### ISSUE TITLE
The terminal process failed to launch: path to shell executable "path"

### ISSUE THREAD

**Issue by mimamulhassankhan** [microsoft/vscode#117036]
After updating powershell via microsoft store, it shows me this error while I am trying to open terminal: The terminal process failed to launch: Path to shell executable "C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.1.0_x64__8wekyb3d8bbwe\pwsh.exe" does not exist. Now I can't access my terminal. Please quickly fix this. I have a deadline tomorrow. Before update, my default shell was powershell.

**Comment by TylerLeonhardt** [comment]
@mimamulhassankhan to unblock you, update the `"terminal.integrated.shell.windows"` to `"C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.2.0_x64__8wekyb3d8bbwe\pwsh.exe"`

I'll look into this

**Comment by TylerLeonhardt** [comment]
@mimamulhassankhan do you remember how you set this as your default shell? If you click the drop down for the terminals and select "Select Default Shell" that should discover the Store install and set your default shell to something like:

```
"terminal.integrated.shell.windows": "C:\\Users\\YOURUSERNAME\\AppData\\Local\\Microsoft\\WindowsApps\\Microsoft.PowerShell_8wekyb3d8bbwe\\pwsh.exe",
```

in the settings
