### ISSUE TITLE
Empty view buttons sizings are weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117030]
Stable:
![image](https://user-images.githubusercontent.com/900690/108495637-54a3ea00-72a9-11eb-9f2a-ed167151fc60.png)

vs insiders:

![image](https://user-images.githubusercontent.com/900690/108495598-4786fb00-72a9-11eb-86da-732937c66043.png)

**Comment by isidorn** [comment]
I believe @joaomoreno broke this via https://github.com/microsoft/vscode/commit/699cc6abd39459857c664ce86320bcc66b534524

Thus also assigning to him

**Comment by joaomoreno** [comment]
Lol how did you know I was working on this today?
