### ISSUE TITLE
Add configuration to remove group labels from "Opened Editors" view

### ISSUE THREAD

**Issue by tracker1** [Microsoft/vscode#11708]
It would be nice to see something like a `workbench.editor.unifyOpenFilesList` option that is false by default, but if true, will have the older behavior of a single list, that updates the current pane on clicking.

If the setting is set while `workbench.editor.showTabs` is `true`, then it should add the file to the tab-group, and set it to current.  When showTabs is `false`, it should update the current pane to the selected file (old behavior).

---

Per #11612, and #9097, The following options are available for getting close to the pre-tabs behavior... The above mentioned feature would close the loop on this.

```
"explorer.openEditors.visible": 10,
"workbench.action.closeEditorsInGroup" :true,
"workbench.editor.showTabs": false, 
"workbench.editor.enablePreview": false,
"workbench.editor.enablePreviewFromQuickOpen": false,
```

**Comment by be5invis** [comment]
+1 for this.
And the "LEFT | CENTER | RIGHT" labels also took too much space.

**Comment by bpasero** [comment]
@tracker1 @be5invis are you talking about the "Opened Editors" list on top of the files explorer?

**Comment by be5invis** [comment]
@bpasero yes.

**Comment by bpasero** [comment]
@isidorn this is a feature request asking to drop the group labels and just show the list flat. I am not a big fan of that, but I know we had a similar issue where people complained that the group labels take too much space.

**Comment by tracker1** [comment]
I realize that you may not be a fan of it, but that's the old behavior that I and a lot of other desire... the way it is now, you set the options above, and when you click on a file it changes the wrong pane, not the current one, which was the old behavior...   Also, files will be duplicated in each pane that has opened the file... it's a waste and harder to navigate/manage... I know tabs was a heavily requested feature, and I was one of them that had wanted it... once I got used to how the behavior was before tabs, I feel it was a much better UX overall, and I miss it.

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
