### ISSUE TITLE
File Explorer Icon Disappears in Activity Bar

### ISSUE THREAD

**Issue by jonnyhork** [microsoft/vscode#117064]
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:
Not sure this reproducible but I have tried downloading a new version of VS Code and the File Explorer still disappears.
1. Open VS Code
2. click on any other activity bar icon
3. explorer will disappear.
4. cmd + shift +E will make the icon reappear
5. click on any icon again, explorer is gone.
6. cmd + B opens side bar but does not contain Explorer.

![Explorer Icon Missing](https://user-images.githubusercontent.com/25188632/108535188-48fbf780-7298-11eb-99d3-cf9f795a3c38.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jonnyhork** [comment]
I have tried to enable software rendering but it did not fix the issue.
```json
// Use software rendering instead of hardware accelerated rendering.
        // This can help in cases where you see rendering issues in VS Code.
        "disable-hardware-acceleration": true,
 ```

**Comment by isidorn** [comment]
Looks like some activity bar issue.
Though I can not reproduce. For now forwarding to @sandy081

**Comment by yume-chan** [comment]
Please right click on the activity bar and make sure "Explorer" is checked.

**Comment by sandy081** [comment]
@jonnyhork Please follow the suggestion from @yume-chan and let us know if it works

**Comment by jonnyhork** [comment]
@sandy081 @yume-chan Thanks, "Explorer" was not checked 😬 Duh, I can't believe I didn't notice that for longer than I care to admit. Fixed now, lets pretend this never happened haha

Thanks!
