### ISSUE TITLE
Test: feedback around inline error decorations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117019]
Talking about:

![image](https://user-images.githubusercontent.com/900690/108481613-b3149c80-7298-11eb-93d2-2bb1e69d78ad.png)

Some feedback:
* if clicking on the error reveals the inline editor box, clicking again should also hide it
* I would not preserve and restore this decoration between reloads
* there seems to be a bug that the decoration looses its range when I make edits:
![image](https://user-images.githubusercontent.com/900690/108481756-d9d2d300-7298-11eb-90a6-3518ed6f29fa.png)

**Comment by connor4312** [comment]
- Added the toggle
- Inline decorations are not shown for "retired" tests (all tests are retired on reload)
- Inline decorations will now get hidden when the line they're on is edited in any way. I think this is a good behavior in general.
