### ISSUE TITLE
Extension Host Crash

### ISSUE THREAD

**Issue by corentinclichy** [microsoft/vscode#117090]
Issue Type: <b>Bug</b>

Hi,

the extension host just keep crashing. I assume it's because of a conflict with an extension but no way to know which one.. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 1943663a-83f4-4f9c-beb1-c696ef4b9b4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
emoji-snippets|dev|1.5.3
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
svg|joc|1.4.5
vscode-styled-components|jpo|1.5.0
vscode-colorize|kam|0.10.0
auto-comment-blocks|kev|1.0.1
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.12.12
vscode-css-peek|pra|4.1.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.2.7
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
quokka-vscode|Wal|1.0.343
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589
pythontb:30258531

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Extension Bisect command from Command Palette

**Comment by rzhao271** [comment]
@corentinclichy any updates on this issue?
