### ISSUE TITLE
Ability to integrate a textbox into a treeview

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117139]
As an extension developer, I'd love to be able to integrate a textbox into a treeview node so I can compose more elaborate user interfaces

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/97190

**Comment by gplumb** [comment]
The duplicate issue you linked to is closed. This is still a valid ask, can
you re-open the linked ticket before shutting this one down?

**Comment by alexr00** [comment]
@gplumb the duplicate is an open issue.

**Comment by gplumb** [comment]
My apologies, this looked closed when I checked!

Thanks!
