### ISSUE TITLE
the `viewport width` too small

### ISSUE THREAD

**Issue by twbworld** [microsoft/vscode#117176]
- VS Code Version:v1.53.2
- OS Version:windows10-20H2

Steps to Reproduce:

1. set `{"editor.wordWrap": "on"}`
2.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/52546134/108623275-0e04ea00-7479-11eb-9620-315f84f252dc.png)

![image](https://user-images.githubusercontent.com/52546134/108623235-e01fa580-7478-11eb-8722-f39d8b4f059b.png)

**Comment by alexdima** [comment]
@twbworld You can try `editor.wrappingStrategy: advanced` when using a non-monospace font.
