### ISSUE TITLE
ctrl+B shortcut doesn't work while terminal focused

### ISSUE THREAD

**Issue by hiredtocode** [microsoft/vscode#117150]
- VS Code Version:Version: 1.53.2 (system setup)
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Ctrl+` (to open built in terminal)
2. Ctrl+b ( to open the side bar)

I've tried to edit the keybindings.json / gui and change the "when" property to && and || terminalFocus and !terminalFocus but nothing works. 
I've tried reloading VSCode after changing the settings too. 
In the terminal it shows ^B every time I press Ctrl+B keys but won't toggle the side panel.

Is this a bug or is this programmed this way on purpose? Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please check the information at https://code.visualstudio.com/docs/editor/integrated-terminal#_forcing-key-bindings-to-pass-through-the-terminal

**Comment by hiredtocode** [comment]
Thank you @gjsjohnmurray

**Comment by hiredtocode** [comment]
@gjsjohnmurray I've tried adding 
```
"terminal.integrated.commandsToSkipShell": [
		// Ensure the toggle sidebar visibility keybinding skips the shell
		"-workbench.action.toggleSidebarVisibility",
		// Send quick open's keybinding to the shell
		"-workbench.action.quickOpen"
	]
``` 
to the settings saved, reloaded the VSCode and it still does the same thing. =/ I've tried adding "-" and removing "-" as well. Any idea why it keeps displaying ^B every time I press ctrl + B ?

**Comment by gjsjohnmurray** [comment]
@hiredtocode adding this to my settings.json works for me:

```	"terminal.integrated.commandsToSkipShell": [
			// Ensure the toggle sidebar visibility keybinding skips the shell
			"workbench.action.toggleSidebarVisibility"
	]
```

Presumably Ctrl+B toggles your sidebar visibility when you aren't focused on Terminal? For example, when you are editing your settings.json

**Comment by hiredtocode** [comment]
@gjsjohnmurray Fixed it, the culprit was the key binding setting I've assigned earlier. Thank you!
