### ISSUE TITLE
Unable to use Sogou Pinyin on Terminal

### ISSUE THREAD

**Issue by zznan0o0** [microsoft/vscode#117157]
- VS Code Version: 1.53.2
- OS Version: windows 10

Steps to Reproduce:
Unable to use Sogou Pinyin on Terminal
1.
![image](https://user-images.githubusercontent.com/13981470/108614124-10dcec00-7433-11eb-9799-f9ab5f4ef322.png)

2.
![image](https://user-images.githubusercontent.com/13981470/108614129-1df9db00-7433-11eb-825f-7ef1c06e85f1.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
Duplicate of #115814

**Comment by meganrogge** [comment]
Duplicate of #115814
