### ISSUE TITLE
Markdown: list and checklist continuation

### ISSUE THREAD

**Issue by Geobert** [microsoft/vscode#117119]
Hi, maybe it is possible already but I can't find the feature: in markdown mode, while starting a list, I'd like the list to continue when I hit `enter`.

If the list is marked with `-` then on `enter`, add `- ` (with the space) already.
If the list is marked with `*` then start with `* `
If the list is marked with `- [ ] ` then start with `- [ ] `

If nothing is input on this new line starting with a list and `enter` is hit again, then delete the list marker, cursor being on start of the line.

Such behavior can be found in the Joplin note taking application for instance, and I find it very productive :)

**Comment by BettyJJ** [comment]
You can achieve this with an extension, for example https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#list-editing

**Comment by Geobert** [comment]
Thank you!
