### ISSUE TITLE
React 17 and typescript 4.1 doesn't need suggestion to import React with JSX

### ISSUE THREAD

**Issue by Navipro70** [microsoft/vscode#117177]
- VS Code Version: 1.53.2
- OS Version: macOS catalina 10.15.5
- React version: 17.0.1
- TypeScript version: 4.1.5

Steps to Reproduce:

1. Create project with React 17 v. and TypeScript 4.1.
2. When you try use new feature of React 17 (JSX without importing React by default), and you wanna import your own/lib JSX element, VScode suggest you import React first, and then your own/lib JSX component.

On screenshot I try import only Navlink without React, because I don't need React to compile. But VScode suggest only React without Navlink.

<img width="564" alt="Screen Shot 2021-02-21 at 14 21 46" src="https://user-images.githubusercontent.com/60893275/108623442-2f051500-7450-11eb-8a95-1c2399431e30.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Related: microsoft/TypeScript#41762
