### ISSUE TITLE
Adding Accept Mechanism to Git Compare Page

### ISSUE THREAD

**Issue by ArunEdathadan** [microsoft/vscode#117170]
Issue Type: <b>Feature Request</b>

the git compare page is the very useful page to understand the file difference, if you can add the accept mechanism in that page, it will increase the productivity

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
The page you refer to sounds like something an extension is adding. If you aren't sure, use the Extension Bisect command from Command Palette to discover when the page appears/disappears from your VS Code. Then raise the issue with the extension author.

/causedByExtension
