### ISSUE TITLE
Home key not working as global shortcut when terminal is focused

### ISSUE THREAD

**Issue by Dimfred** [microsoft/vscode#117127]
- VS Code Version: 1.53.2
- OS Version: ManjaroLinux 20.2.1

Bug:
The home key gets passed down to the terminal instead of being caught by VSCode.

Steps to Reproduce:
1. Create Keyboard Shortcut
`{ "key": "home", "command": "cursorDown" }`
2. Open VSCode integrated terminal
3. Press "home"

What should happen:
Cursor should move down whether you are in terminal or not.

Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
I'm confused about what you want.

`cursorDown` command ONLY works in text editors, no matter what key you bind it to, it will not move cursor in terminal.

If you want pressing "Home" in terminal will move your cursor in (last) active text editor, add `cursorDown` to `terminal.integrated.commandsToSkipShell` setting. Terminal doesn't skip particular keys, but commands.

**Comment by Dimfred** [comment]
The `cursorDown` is just a placeholder for an arbitrary command. The point is I want an editor command to get triggered when I press home, but instead the terminal catches the home NOT the editor. 

If you try the binding that I posted you will see the the cursor will NOT move down a line. Instead the home button will reset the cursor inside the terminal.

If you e.g. replace the `key` with `space` it will work. The editor will catch the space and not the terminal.

**Comment by yume-chan** [comment]
> If you try the binding that I posted you will see the the cursor will NOT move down a line. Instead the home button will reset the cursor inside the terminal.

Add `cursorDown` (or your arbitrary commands) to `terminal.integrated.commandsToSkipShell` setting will achieve what you want.

> If you e.g. replace the `key` with `space` it will work. The editor will catch the space and not the terminal.

That's wired. I never know terminal will skip a key to Code itself.  @Tyriar

**Comment by Dimfred** [comment]
Ahh thanks a lot! Had to do some dirty workarounds to mitigate that. Problem solved.
