### ISSUE TITLE
Update downloads but fails to apply

### ISSUE THREAD

**Issue by spicydonuts** [Microsoft/vscode#11710]
- VSCode Version: 1.4.0
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Open vscode, wait for it to download 1.5 update
2. Click "Update now" in the dialogue that appears once the update is ready
3. vscode reopens, but it's still version 1.4.0.  It will detect the update again and redownload it, then repeat.

**Comment by joaomoreno** [comment]
Is this #3520?
