### ISSUE TITLE
Code-insiders crashes on launch

### ISSUE THREAD

**Issue by binyamin** [microsoft/vscode#117156]
- VS Code Version: 1.54.0-insider
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Launch vscode ( I used `code-insiders -n --disable-extensions --sync=off --verbose`)
2. wait 3-5 seconds...

Does this issue occur when all extensions are disabled?: **Yes**/No

I ran `code-insiders --crash-reporter-directory <dir>`, and zipped the resulting file: [dmpfile.zip](https://github.com/microsoft/vscode/files/6016990/dmpfile.zip). Also, here's the log from the console: 
[vscode-crash.log](https://github.com/microsoft/vscode/files/6016996/vscode-crash.log).

**Comment by binyamin** [comment]
I downgraded to version 1.52.0-1607352923, and it still crashes. I was previously using code-insiders via snap, and then I removed the snap and installed the .deb package. Crashes happened soon after that.

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by deepak1556** [comment]
Thanks for the dump, crash is from the `vscode-encrypt` module. Merging to https://github.com/microsoft/vscode/issues/116690
