### ISSUE TITLE
"candidatePortSource" API sets a user setting

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117189]
Was looking into how `candidatePortSource` works for resolvers, and it looks like if Remote-SSH sets it to `Output`, then the setting `"remote.autoForwardPortsSource": "output"` is set. If Remote-SSH changed that property, then the setting wouldn't be changed. That probably won't happen but this is confusing from an extension API perspective because a resolver could change that property at any point in it's lifecycle.

I think what I would expect is that the user can set that setting, and it would override what the resolver set, but the resolver's value would only be respected for one vscode remote session.

**Comment by alexr00** [comment]
I did this deliberately so that the change would be completely transparent to the user. If a user opens settings and is looking at the `remote.autoForwardPortsSource` setting, then it looks like the default is `process`. If we silently change the default, then that is confusing. By setting the setting, we are making the change explicit.

**Comment by roblourens** [comment]
That makes sense. You could also solve that with a third enum value which means "use the resolver's default", and the user can override it by setting one of the other values.

**Comment by roblourens** [comment]
From an extension API perspective, this is fine because it's probably effectively internal API, but if it's supposed to be a static property of the resolver, it could be an option passed to the "register" call

**Comment by alexr00** [comment]
I like the "use the reosolver's default" setting option. Will add for March!

**Comment by alexr00** [comment]
@roblourens the new behavior is that the default value of the setting is controlled by the `candidatePortSource`. The setting will not be set as a machine setting going forward and users will still be able to look at the settings and see what the behavior is.
