### ISSUE TITLE
Cannot click on folder names to expand it

### ISSUE THREAD

**Issue by BerkeAras** [microsoft/vscode#117183]
Issue Type: <b>Bug</b>

1. Open VSCode
2. In the file tree, try clicking on the title of a folder
3. See that it is not opening, just when you click on the arrow or the folder-icon

VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:17:50.205Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 5, 5|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 1af1fdcf-15de-4945-afa4-32646716712e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-intelephense-client|bme|1.6.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
live-sass|gle|4.4.1
beautify|Hoo|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.16
tabnine-vscode|Tab|3.2.7
es6-string-html|Tob|2.1.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoccf:30257852
vscoresta800:30259386

```

</details>

**Comment by sp11ff** [comment]
@BerkeAras try Workbench > List: Open Mode
<img width="815" alt="image" src="https://user-images.githubusercontent.com/41512733/108629801-4c46dd00-746a-11eb-8797-b79258f4c39c.png">

**Comment by BerkeAras** [comment]
@sp11ff Thanks for your reply. Open Mode is already on singleClick

**Comment by yume-chan** [comment]
See #115873

**Comment by BerkeAras** [comment]
Thanks @yume-chan. I searched for another issue but I could not found. Thanks.
