### ISSUE TITLE
`workbench.list.openMode` not respected

### ISSUE THREAD

**Issue by NoNameProvided** [microsoft/vscode#117167]
Issue Type: <b>Bug</b>

Since the latest VsCode insider update, the `workbench.list.openMode` is not respected. I have `singeClick` (the default value) option set, but I have to double-click folder names in the explorer to open them (or click the little arrow on the left once).

VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:14:28.632Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.24GB free)|
|Process Argv|--crash-reporter-id 0de59323-56c7-4cd7-80fe-6152182e3cac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
project-manager|ale|12.0.1
vscode-angular2-files|ale|1.6.4
markdown-preview-github-styles|bie|0.1.6
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
terraform|has|2.6.0
vscode-drawio|hed|1.3.0
vscode-peacock|joh|3.9.1
i18n-ally|lok|2.4.22
bash-ide-vscode|mad|1.11.0
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-scss|mrm|0.9.0
vscode-azurefunctions|ms-|1.2.1
vscode-docker|ms-|1.10.0
vscode-edge-devtools|ms-|1.1.3
remote-containers|ms-|0.161.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.6
debugger-for-edge|msj|1.0.15
angular-console|nrw|16.0.2
indent-rainbow|ode|7.5.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
sass-indented|rob|1.5.1
rust|rus|0.7.8
code-spell-checker|str|1.10.2
vsfire|tob|1.4.1
codetour|vsl|0.0.44
gitdoc|vsl|0.0.6
gitblame|wad|6.0.2
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoc:30257851
vscoresta800:30259386

```

</details>

**Comment by gjsjohnmurray** [comment]
#115873 added `workbench.tree.expandMode` to 1.54. Initially its default changed existing (1.53.2) behaviour, but Monday's Insiders should see the default switch back. Meanwhile, try changing the setting.

**Comment by NoNameProvided** [comment]
Thanks! Explicitly setting `workbench.tree.expandMode` to `singleClick` solves the issue.
