### ISSUE TITLE
ArrayBuffer from vscode.workspace.fs.readFile returns random data

### ISSUE THREAD

**Issue by misode** [microsoft/vscode#117148]
Issue Type: <b>Bug</b>

I'm writing a custom editor, [NBT Viewer](https://marketplace.visualstudio.com/items?itemName=Misodee.vscode-nbt).

When [reading certain files](https://github.com/misode/vscode-nbt/blob/master/src/NbtDocument.ts#L21), I get random data. Strangely enough only in the `ArrayBuffer` and not in the `Uint8Array`.
```ts
let array = await vscode.workspace.fs.readFile(uri)
console.log(array[0]) // 10 (expected)
console.log(new Uint8Array(array.buffer)[0]) // 1 (wrong)
```

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.99GB free)|
|Process Argv|--crash-reporter-id 3fefe209-6816-4295-879f-d912656b9ab1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
language-mcfunction|arc|0.17.0
tsl-problem-matcher|eam|0.3.1
code-runner|for|0.11.2
godot-tools|gee|1.1.2
vscode-pull-request-github|Git|0.23.1
Kotlin|mat|1.7.1
vscode-nbt|Mis|0.3.2
vscode-nbtdoc|Mis|1.0.0
vscode-language-pack-ru|MS-|1.53.2
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
hexeditor|ms-|1.4.0
vsliveshare|ms-|1.0.3784
subtitles-editor|pep|1.1.3
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
datapack-language-server|SPG|3.3.0
pdf|tom|1.1.0
sort-lines|Tyr|1.9.0
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by jrieken** [comment]
Please provide a full repro sample.

**Comment by misode** [comment]
@jrieken I created an extension with simple reproduction steps: https://github.com/misode/vscode-117148/releases/tag/v0.0.1

**Comment by jrieken** [comment]
Only, looked that the sources so far. This line/statement is highly fishy: `const b = new Uint8Array(array.buffer)[0];` The result from the readFile-function is already a Uint8Array and use its backing `ArrayBuffer` without respecting the `byteOffset` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteOffset)

**Comment by misode** [comment]
Thanks, that was the issue! I totally didn't consider it could have a `byteOffset` other than `0`.
