### ISSUE TITLE
"Change all Occurrences" in a string with stop or whitespace chars

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#1171]
"Change all Occurrences" doesn't work if the text selection contains stops, spaces or such. Furthermore, if the text was selected from L->R - it just doesn't do anything, but if R->L - it automatically selects the most left word and then invokes the "Change all Occurrences".

**Comment by egamma** [comment]
Please provide an example so that we can reproduce the problem.

**Comment by Spown** [comment]
![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2015-12/2015-12-10_16-40-23.gif)

**Comment by LittleSaya** [comment]
I just met the same problem like you. The "Change All Occurrences" doesn't work if the string I select has whitespace or any other character which is not a letter.
Here is the screenshots:

Original:
![1](https://cloud.githubusercontent.com/assets/16049823/12037924/9859f2ec-ae8e-11e5-92e8-581243326334.png)

If I want to replace all the " << endl;" to ";", and I select the 3rd(from L to R):
![2](https://cloud.githubusercontent.com/assets/16049823/12037930/abe31e9c-ae8e-11e5-9059-60ed3f30d7a1.png)

Right click and select "Change All Accurrences":
![3](https://cloud.githubusercontent.com/assets/16049823/12037934/b27ca55c-ae8e-11e5-889b-d77561b6f400.png)

It just comes back to..
![4](https://cloud.githubusercontent.com/assets/16049823/12037977/2661ccd6-ae8f-11e5-8255-4ec67c851586.png)

![5](https://cloud.githubusercontent.com/assets/16049823/12037995/3da9981a-ae8f-11e5-844f-555d0139d701.png)

And if I select from R to L:
![6](https://cloud.githubusercontent.com/assets/16049823/12038081/00019912-ae90-11e5-9980-eaef4a742a61.png)

Right click:
![7](https://cloud.githubusercontent.com/assets/16049823/12038090/0e562d3e-ae90-11e5-9bd9-d43cf7f8cf05.png)

And it becomes:
![8](https://cloud.githubusercontent.com/assets/16049823/12038158/9b6e6e70-ae90-11e5-8a83-87a406f3959d.png)

![9](https://cloud.githubusercontent.com/assets/16049823/12038162/a64b63ca-ae90-11e5-85df-9cc124723a8c.png)

Version of VS Code: 0.10.6

**Comment by alexandrudima** [comment]
Thank you for the detailed repro steps!
