### ISSUE TITLE
Vscode 1.53.2(system setup) Javascript intellisense is not working on my windows 10

### ISSUE THREAD

**Issue by olatoweb** [microsoft/vscode#117168]
![object](https://user-images.githubusercontent.com/26550928/108620544-1800fb80-742d-11eb-8450-ecac28376b60.png)
We have written the needed data into your clipboard This issue always occur whenever i want to use a javascript object or array propertise and methods. For instance:
const number = {1, 2, 3};
number. (after the dot, the propertise and methods of the object suppose to show but unfortunately is not showing so please help to fix this issue. Thanks!

About my pc:
model: Dell Inspiron 3558
Processor: Intel(R) Core(TM) i3-55015U CPU @ 2.10GHz 
Installed Ram: 12.0 GB
system type: 64-bit operating system, x64-based processor

windows specifications:
Edition: Windows 10 Pro
Version: 1903
Installed on: 9/30/2019
OS build: 18362.10024

ard because it was too large to send. Please paste.

**Comment by djmisterjon** [comment]
take a look on https://devhints.io/jsdoc
jsdoc is required when you work in js, also take a look in vscode guide.
https://code.visualstudio.com/docs/languages/jsconfig
You need a jsconfig or tsconfig (both work for js project)

for you case try .
```js
/** @type {Object.<number, string>} */
const a = {1,2};
```
but `const a = {1,2}` it not a valide syntaxe in js
you need define key value in literal  `const a = {1:void 0,2:void 0}`
