### ISSUE TITLE
Git extension askpass https host parsed incorrectly

### ISSUE THREAD

**Issue by sargreal** [microsoft/vscode#117152]
- VS Code Version: 1.53.2
- OS Version: Manjaro unstable
- Git Version: 2.30.1

Steps to Reproduce:

1. Execute git.clone command
2. Enter https git url for a private repository (does not even need to exist, so for example `https://gitlab.com/haasef/test.git`)
3. Askpass pops up with `Git: https://gitlab.com': (Press 'Enter' ...)` (The last two characters `':` are from the host string and not the template)

Why is this an issue?
1. It does not create a problem when using the direct clone or github credentials provider (since that one does not check equality but only if `github.com` is contained)
2. **But:** when adding a new credentials provider that checks for the explicit url, it fails (see [gitlab-vscode-extension](https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/merge_requests/172#note_513068345))
3. This should have been fixed in #115037 but the fix does not handle a `:` in the end

More Information:
   * askpass-main recieves: 
     ```
     [
       "/home/felix/Documents/coding/vscode/.build/electron/code-oss",
       "/home/felix/Documents/coding/vscode/extensions/git/out/askpass-main.js",
       "Username",
       "for",
       "'https://gitlab.com':",
     ]
     ```
   * and parses the host as `https://gitlab.com':` instead of `https://gitlab.com`

Suggested fix: 
```diff
diff --git a/extensions/git/src/askpass-main.ts b/extensions/git/src/askpass-main.ts
index c15dd583fa..f17dc63463 100644
--- a/extensions/git/src/askpass-main.ts
+++ b/extensions/git/src/askpass-main.ts
@@ -30,7 +30,7 @@ function main(argv: string[]): void {
 
        const output = process.env['VSCODE_GIT_ASKPASS_PIPE'] as string;
        const request = argv[2];
-       const host = argv[4].replace(/^["']+|["']+$/g, '');
+       const host = argv[4].replace(/^["']+|["':]+$/g, '');
        const ipcClient = new IPCClient('askpass');
 
        ipcClient.call({ request, host }).then(res => {
```

Does this issue occur when all extensions are disabled?: Yes (Was tested and debugged on master)

**Comment by joaomoreno** [comment]
Great catch, and details! Can you subit a PR with that fix? It is a great fix.

**Comment by sargreal** [comment]
> Great catch, and details! Can you submit a PR with that fix? It is a great fix.

Thanks! I created the merge request: #117230
