### ISSUE TITLE
VScode Emmet missing HTML "hgroup" tag

### ISSUE THREAD

**Issue by BradBailey-web** [microsoft/vscode#117154]
It appears that emmet on vscode is missing this HTML tag (hgroup).
It is part of the living standard of HTML and therefore I think it was just overlooked (as it is rarely used.)
It is however an important tag for accessibility reasons.

Here is the MDN documentation for hgroup.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup

I am using Ubuntu 20.04
`$ code -- version` 1.53.2
Extensions:
Auto Rename Tag
EJS language support 
ES7 React/Redux/GraphQL/React-Native snippets
Live Server
Prettier - Code formatter
SQLTools
Template String Converter
Deno

Reproducible steps:
1) open html document
2) type `hgroup`
3) ctrl + space (or alternative to trigger suggestions)
4) look in horror at no suggestions 

I expected to see hgroup tag suggestion that would then make it create an opening and closing tag.

**Comment by rzhao271** [comment]
Code pointer if anyone's interested: check out https://github.com/microsoft/vscode/issues/114923

**Comment by OBITORASU** [comment]
@rzhao271 the approach for this issue should be identical to the approach taken for ```figcaption``` am I right? I would like to work on this one if that is the case.

**Comment by rzhao271** [comment]
@OBITORASU yep, it should be the same.

**Comment by OBITORASU** [comment]
Thank you I will send a PR then.

**Comment by rzhao271** [comment]
\closedWith b629d88
