### ISSUE TITLE
鼠标不能选择文本

### ISSUE THREAD

**Issue by littleShy** [microsoft/vscode#117196]
Issue Type: <b>Bug</b>

vscode刚打开时鼠标能够正常拖动并选择文本，过几分钟后再点击拖动鼠标无法选中文本，我尝试重新打开vscode，问题恢复，但是过几分钟仍然会出现。
在其他程序中没有这个问题

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.70-amd64-desktop

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.54GB (0.16GB free)|
|Process Argv|--folder-uri file:///media/xiaoyl/办公/Code/Work/YuYouGame/src/branches/dev/Server2.0-Git/GameServer.code-workspace --no-sandbox --crash-reporter-id 8ce89732-07e4-47d3-8283-25f57bd06541|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
go|gol|0.22.1
vscode-language-pack-zh-hans|MS-|1.53.2
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2-insiders2
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by yume-chan** [comment]
Translation:

> ## Can't select text with mouse
>
> When Code first starts, I can drag and select text with my mouse normally. But after several minutes I can't select text anymore. Restart Code, the problem is gone, but it reappears again minutes later.
>
> Other programs work fine.

**Comment by littleShy** [comment]
no longer exists

**Comment by landv** [comment]
> Issue Type: Bug
> 
> vscode刚打开时鼠标能够正常拖动并选择文本，过几分钟后再点击拖动鼠标无法选中文本，我尝试重新打开vscode，问题恢复，但是过几分钟仍然会出现。
> 在其他程序中没有这个问题
> 
> VS Code version: Code 1.53.2 ([622cb03](https://github.com/microsoft/vscode/commit/622cb03f7e070a9670c94bae1a45d78d7181fbd4), 2021-02-11T11:48:44.518Z)
> OS version: Linux x64 5.4.70-amd64-desktop
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 3394)
> GPU Status	2d_canvas: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> oop_rasterization: disabled_off
> opengl: enabled_on
> protected_video_decode: unavailable_off
> rasterization: disabled_software
> skia_renderer: enabled_on
> video_decode: disabled_software
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> Load (avg)	2, 2, 2
> Memory (System)	15.54GB (0.16GB free)
> Process Argv	--folder-uri file:///media/xiaoyl/办公/Code/Work/YuYouGame/src/branches/dev/Server2.0-Git/GameServer.code-workspace --no-sandbox --crash-reporter-id 8ce89732-07e4-47d3-8283-25f57bd06541
> Screen Reader	no
> VM	0%
> DESKTOP_SESSION	deepin
> XDG_CURRENT_DESKTOP	Deepin
> XDG_SESSION_DESKTOP	deepin
> XDG_SESSION_TYPE	x11
> Extensions (6)
> Extension	Author (truncated)	Version
> gitlens	eam	11.2.1
> go	gol	0.22.1
> vscode-language-pack-zh-hans	MS-	1.53.2
> cmake-tools	ms-	1.6.0
> cpptools	ms-	1.2.2-insiders2
> cmake	twx	0.0.17
> A/B Experiments
> ```
> vsliv368:30146709
> vsreu685:30147344
> python383cf:30185419
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> pythonvsdeb440:30248342
> pythonvsded773:30248341
> pythonvspyt875:30259475
> ```

https://bbs.deepin.org/post/203950#mod=viewthread&tid=203950&extra=
`今天才发现的一个bug，vscode下，讯飞输入法模式无法用鼠标拖动选择文本，输入法切换为英语以后就可以选择了。网上说是ibus和vscode不兼容的问题。`
A bug we just found today is that under vscode, iFLYTEK input mode can't select text by dragging the mouse. After the input mode is switched to English, you can choose it. It is said on the Internet that IBus and vscode are incompatible.
This is not a problem with vscode
