### ISSUE TITLE
"Find match" line highlight background colour not adhering to `editor.lineHighlightBackground` or not customisable

### ISSUE THREAD

**Issue by AndreasBackx** [microsoft/vscode#117193]
- VS Code Version: 1.53.2
- OS Version: 5.10.16-arch1-1 Linux

Steps to Reproduce:

1. Go to settings (JSON)
2. Add:

```
"workbench.colorCustomizations": {
    "editor.lineHighlightBackground": "#ff0000"
}
```

3. Search for something

You can see that currently highlighted line does get the red colour. Unfortunately the highlighted line from the search does not use this colour. There does not seem to be a colour anywhere in the settings that controls this. Video example: 

https://user-images.githubusercontent.com/1593486/108645237-0d387c00-74aa-11eb-9749-cdcf476e4ed9.mp4

None of the built-in or extension themes I tried have a custom colour for this. Therefore I assume that even after my search, that it not possible to change this colour.

Is it possible to make it possible to change this colour? Perhaps make it default to `editor.lineHighlightBackground`?

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
It's the "editor.rangeHighlightBackground"
