### ISSUE TITLE
JavaScript Debug Terminal takes ~2 minutes and ~2GB of RAM to start

### ISSUE THREAD

**Issue by stephenpassero** [microsoft/vscode#117141]
- VS Code Version: 1.53.2
- OS Version: MacOS Big Sur 11.2.1

Steps to Reproduce:

1. Add a breakpoint somewhere in the JS code
2. Open the JS Debug Terminal
3. Run a command that would execute the line with the breakpoint from within the debug terminal

Does this issue occur when all extensions are disabled?: **Yes**

When trying to run the JS Debug Terminal, it takes a few minutes while slowly using more RAM to actually run. I took a screen recording of the behavior, and you can see the process gradually consume more memory. Although the recording happens with extensions enabled, I did verify that the bug still occurs when starting VSCode with `--disable-extensions`.

https://user-images.githubusercontent.com/12648039/108603771-e0844780-7377-11eb-84e5-288cf91248eb.mp4

Also note that the video is at 2x playback speed, so the debugger will seem faster to start up than it was in real life.

**Comment by connor4312** [comment]
What does your workspace look like I'm guessing that this is likely due to parsing and scanning a bunch of sourcemaps.

If so, you can configure where (or if) sourcemaps are searched in the `debug.javascript.terminalOptions` setting. You could set in your workspace to `{ "outFiles": [] }` to disable sourcemap discovery entirely, or set it to an array of globs indicating specific locations to search.

**Comment by stephenpassero** [comment]
@connor4312 Ah, that makes sense. Verified that if I set `"outFiles": []`, then the debugger boots up instantly. I'll play around with what I include there, so thanks for your help!

**Comment by connor4312** [comment]
cool, thanks for confirming.

For normal debugging we show a warning when discovery is taking a while but maybe this doesn't work in the terminal. Will take a look.

**Comment by connor4312** [comment]
It looks like the notification does get shown. There's a "Don't show again" warning that may have been hit.

![](https://memes.peet.io/img/21-03-5f3160c5-ba19-4550-908c-0811465906b7.png)
