### ISSUE TITLE
Vscode terminal text does not show and the cursor is huge

### ISSUE THREAD

**Issue by aliseena** [microsoft/vscode#117120]

**Comment by aliseena** [comment]
While opening vscode, terminal is black and meanwhile, the text and directory does not show. The cursor is also bigger and taller than usual. Disabling extensions did not work

**Comment by meganrogge** [comment]
Are there errors in Dev tools (Help -> Toggle Developer Tools)

**Comment by aliseena** [comment]
> Are there errors in Dev tools (Help -> Toggle Developer Tools)

There is no error in Dev tools. Here is my settings json file as well.

[settings.txt](https://github.com/microsoft/vscode/files/6023576/settings.txt)
