### ISSUE TITLE
Workspaces. 

### ISSUE THREAD

**Issue by serheygmailcom** [microsoft/vscode#117165]
Issue Type: <b>Feature Request</b>

I have 2 projects (folders) inside 1 folder. 

when I chose add folder to workspace for first - it create worspace automatically with a name of root folder and I'm now in this new workspace.

when I chose add folder to workspace for second foleder- it does nothing, says nothing, now I'm just again inside a scond folder.

would be nice to see same app beahviour for 2 same actions. super confusing now

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Your second step gives you a multi-root workspace. If you intended to create two single-root workspaces, close the workspace after the first step. Remember to save it when prompted.
