### ISSUE TITLE
`registerCompletionItemProvider` with triggerCharacters '\n' makes strange code snippet behavior

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#117194]
版本: 1.53.2 (user setup)
提交: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
日期: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Here is the sample: https://github.com/sumneko/sample-2

![sample-2](https://user-images.githubusercontent.com/5213431/108648527-6f1ed300-74f6-11eb-8059-e6bcb0bc7e10.gif)

After using `registerCompletionItemProvider` with triggerCharacters '\n', every time you hit enter, VSCode will display user code snippets.
I tried some other triggerCharacters, such as spaces and tabs, but none of this happened.

**Comment by jrieken** [comment]
> After using registerCompletionItemProvider with triggerCharacters '\n', every time you hit enter, VSCode will display user code snippets.

What else should it do. You told it to trigger suggestions whenever a new line (`\n`) is inserted

**Comment by sumneko** [comment]
> What else should it do. You told it to trigger suggestions whenever a new line (`\n`) is inserted

IMO, it should only call my `provideCompletionItems` in line 5.
The `triggerCharacters` parameter should not affect other extensions. If they also want to care about `\n`, they should write in their own `registerCompletionItemProvider`.
If it is really necessary to modify the global `triggerCharacters`, a separate API should be provided, such as `addCompletionTriggerCharacters`.

**Comment by jrieken** [comment]
Thanks for clarifying. I'll push a change that prevents snippet completion from showing. That fixes this for snippets other extensions are free to also use '\n' as trigger character and we do not allow you to prevent that
