### ISSUE TITLE
terminal focus key binding is not working correctly after update to 1.5

### ISSUE THREAD

**Issue by pritimay** [Microsoft/vscode#11714]
- VSCode Version: 1.5
- OS Version: windows 10

Steps to Reproduce:

1. 
2.

**Comment by ramya-rao-a** [comment]
@pritimay Do you mean the terminal focus ley binding was working for you in 1.4 but is not working after update to 1.5 ?

**Comment by pritimay** [comment]
Yeah, just after update from 1.4 to 1.5 it is not working

**Comment by Tyriar** [comment]
@pritimay Can you paste in your settings.json and keybindings.json?

**Comment by apbendi** [comment]
I'm seeing the same problem. Below is `keybindings.json`. My `settings.json` is empty.

```json
// Place your key bindings in this file to overwrite the defaults
[{
    "key": "cmd+`",
    "command": "workbench.action.terminal.focus",
    "when": "editorTextFocus"
}]
```

**Comment by apbendi** [comment]
(also, if there is an easier way to toggle between the terminal and the editor without a custom keyboard, I'd love to know it! just started trying out VSCode earlier this week, so apologize if thats a dumb question!)

**Comment by pritimay** [comment]
@Tyriar This are my user settings.json and keybindings.json

{
    "terminal.integrated.cursorBlinking": true,
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 1000,
    "window.restoreFullscreen": true
}

[
    **{
        "key": "ctrl+q",
        "command": "workbench.action.terminal.focus",
        "when": "!terminalFocus"
    },**
    {
        "key": "ctrl+shift+x",
        "command": "extension.partialDiff.markSection1",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+d",
        "command": "extension.partialDiff.markSection2AndTakeDiff",
        "when": "editorTextFocus"
    }
]

**workbench.action.terminal.focus** is working only after killing the terminal.

**Comment by hashhar** [comment]
Can confirm the same issue. I tried this on a clean install. Both `settings.json` and `keybindings.json` are empty.

**Comment by oblin** [comment]
Comfirm this issue, too.
try this simple setting work in 1.4, but not 1.5.1：

{ "key": "ctrl+alt+t",            "command": "workbench.action.terminal.focus"}

**Comment by ivarref** [comment]
You can also reproduce this issue with: `ctrl-shift-p` and select `Terminal: Focus Terminal`
My keybindings.json is then an empty array.
This does not work for me in 1.5.1.

@apbendi It's not a dumb question. I think it would be an excellent feature to easily toggle between terminal and editor without a custom keyboard shortcut. I don't know of a way at present moment.

**Comment by ivarref** [comment]
PS @apbendi I'm using this config in VS Code 1.4 to focus text editor / terminal with the same shortcut:
```json
// Place your key bindings in this file to overwrite the defaults
[
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.focus",
        "when": "!terminalFocus"
    },
    {
        "key": "ctrl+`",
        "command": "workbench.action.openLastEditorInGroup",
        "when": "terminalFocus"
    }
]
```

**Comment by Tyriar** [comment]
Thanks all for the reports, fixed this in master and I'll mark this to be included in the upcoming translation build.

**Comment by pritimay** [comment]
Thanks @Tyriar really needed it

**Comment by Tyriar** [comment]
Also I love your setup @ivarref, I might have to steal it once the fix lands :smile:

**Comment by roblourens** [comment]
I like that toggle setup too. You can always collapse the bottom pane with cmd+j so you don't even need to replace the toggleTerminal binding to hide it.

**Comment by Tyriar** [comment]
Added it to my settings with a small tweak:

```ts
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus",
                            "when": "!terminalFocus" },
{ "key": "ctrl+`",          "command": "workbench.action.focusFirstEditorGroup",
                            "when": "terminalFocus" }
```

I created #11897 requesting to add a command that focuses the most recently used editor group so it feels better.

**Comment by Tyriar** [comment]
@roblourens @ivarref `workbench.action.focusActiveEditorGroup` is a thing now (#11904), so you can use this to reliably focus the most recently used file/editor:

```json
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus",
                            "when": "!terminalFocus" },
{ "key": "ctrl+`",          "command": "workbench.action.focusActiveEditorGroup",
                            "when": "terminalFocus" }
```
