### ISSUE TITLE
terminal select Git Bash can’t input Chinese

### ISSUE THREAD

**Issue by hqzh** [microsoft/vscode#117122]
- VS Code Version: v1.53.2
- OS Version: windows_NT x64 10.0.17763
- Node.js: 12.18.3
- gitbash: 

Steps to Reproduce:

1. terminal select Git Bash
2. Can’t input Chinese

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Maybe a duplicate of #115814

What IME do you use and does it work for other shells?

**Comment by hqzh** [comment]
Windows PowerShell  same won't work，I use the vscode previous version and both can be type

**Comment by hqzh** [comment]
#117157

**Comment by meganrogge** [comment]
Duplicate of #115814
