### ISSUE TITLE
CoffeeScript syntax highlighting doesn't handle quotes in JSX

### ISSUE THREAD

**Issue by edemaine** [microsoft/vscode#117143]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file with `.coffee` extension
2. Input the following text:

   ```coffee
   <code>
     Hello world's
     this is some {'text'}
   </code>
   ```

Resulting highlighting:

![image](https://user-images.githubusercontent.com/2218736/108604764-eaa94480-737d-11eb-8a8a-c20dfb6be330.png)

By contrast, this is the highlighting I expect, which is what I get when using JavaScript highlighting (`.jsx` extension):

![image](https://user-images.githubusercontent.com/2218736/108604780-ff85d800-737d-11eb-8d1c-fc9eabaee26b.png)

Does this issue occur when all extensions are disabled?: Yes

Quotes should not be processed when inside JSX blocks. I'm new to VSCode's JSON syntax files, so I don't quite know how to fix it, but given that it works in JavaScript, I imagine it is possible (and hopefully easy?) to fix.

**Comment by yume-chan** [comment]
1. It's not "VSCode's JSON syntax file", Code uses TextMate grammar format.
2. CoffeeScript syntax file is at https://github.com/microsoft/vscode/blob/main/extensions/coffeescript/syntaxes/coffeescript.tmLanguage.json
3. As stated in the file, it's synchronized from Atom's CoffeeScript syntax
    https://github.com/microsoft/vscode/blob/11cd76005bc7516dcc726d7389d0bce1744e5c85/extensions/coffeescript/syntaxes/coffeescript.tmLanguage.json#L2-L6
4. Sadly, same as many other synced syntax definitions, this one is also lack of maintains. https://github.com/atom/language-coffee-script
5. You may try to file an issue there, or pr there if you can fix it.

If the pr doesn't get processed, then I don't know. See #113206

**Comment by edemaine** [comment]
Thanks for the pointers!  I did look at https://github.com/microsoft/vscode/blob/main/extensions/coffeescript/syntaxes/coffeescript.tmLanguage.json but missed the comment at the top &mdash; sorry about that.  I filed https://github.com/atom/language-coffee-script/issues/174 and will see if I can figure out a solution and PR.

**Comment by bitsoflogic** [comment]
Not a great workaround, but you replace the single quote with `&apos;`. This'll give you the same browser output without breaking the syntax highlighting. This is how I'm dealing with it for now, so I can easily read the rest of my files.

```
<code>
  Hello world&apos;s
  this is some {'text'}
</code>
```

**Comment by alexr00** [comment]
@yume-chan thanks for providing all those details. 

@edemaine thanks for filing an issue in the upstream repo.

Closing in favor of the upstream issue.
