### ISSUE TITLE
"Organize Imports" adds/removes a new line every call

### ISSUE THREAD

**Issue by Androkai** [microsoft/vscode#117179]
Issue Type: <b>Bug</b>

I'm writing Java code in VS Code. Using the `Organize Imports` function I noticed that it always adds a second new line after the import statements before the class starts. Investigating this topic a bit I also noticed that if I run it again it will remove the second newline. If you continue you will notice that it adds a new line in one run, then removes it in the next one and so on.

I'm using the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) to format my Java code so maybe you normally have 2 empty lines after import statements and it works in that case, so nobody noticed, I don't know.
To apply the Google style I use the [Clang-Format Extension](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) as a formatter.

---

Expected behavior: Regardless of how often I call `Organize Imports` I always get the same formatting.

---

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.69GB free)|
|Process Argv|--crash-reporter-id 3e6f21e3-7afd-478a-8376-f2567e8f5e0d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.2.0
matlab-formatter|Aff|2.8.6
gitkraken-glo|axo|1.1.1
spellright|ban|3.0.56
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
git-project-manager|fel|1.7.1
vscode-lombok|Gab|1.0.1
matlab|Gim|2.0.0
vscode-pull-request-github|Git|0.23.1
latex-workshop|Jam|8.16.0
papyrus-lang-vscode|joe|2.23.1
dotenv|mik|1.0.1
vscode-nbt|Mis|0.3.2
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.6
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3784
gradle-language|nac|0.2.3
unicode-latex|oij|1.1.2
java|red|0.75.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.15.0
shellman|Rem|4.10.0
vscode-gradle|ric|3.5.2
shader|sle|1.1.5
sonarlint-vscode|Son|1.20.1
datapack-language-server|SPG|3.3.0
vscode-mc-shader|Str|0.9.5
latex-utilities|tec|0.3.7
shellcheck|tim|0.13.2
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-spring-initializr|vsc|0.6.1
vscode-icons|vsc|11.1.0
gitdoc|vsl|0.0.6
clang-format|xav|1.9.0
markdown-pdf|yza|1.4.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Androkai** [comment]
- Without at least the [Language Support for Java(TM) by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.java) extension I can not use `Organize Imports`.
- With only this one extension installed it's working as expected and I can use the `Organize Imports` function without being able to reproduce the issue.
- With also the [Clang-Format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) extension installed and set as default formatter the issue is happening again.
- With another Java formatter extension [Java prettier formatter](https://marketplace.visualstudio.com/items?itemName=mwpb.java-prettier-formatter) the `Organize Imports` call changes the formatting once to something different from what `Format Document` does but it stays like that and does not change anymore if you call it again.

I conclude that this must be a problem between the *Clang-Format* and *Language Support for Java(TM) by Red Hat* extension. Both extensions try to format the output in a different way at the same time.

To reproduce the following code can be used:
```java
package net.example.test;

import java.time.LocalDate;
import java.util.List;
import javax.annotation.Nonnull;

public class Example {
  private LocalDate date;
  private List<String> examples;

  public Example(LocalDate date, @Nonnull List<String> examples) {
    this.date = date;
    this.examples = examples;
  }

  public LocalDate getDate() {
    return date;
  }

  public List<String> getExamples() {
    return examples;
  }
}
```

I'm fine with closing this ticket here since it seems to be a plugin / event concurrency related problem.

**Comment by mjbvz** [comment]
Ah sorry, I missed that this was Java instead of javascript

Please file this against the Java extension since it is what implements organize imports
