### ISSUE TITLE
Add selection setting API to TextEditorEdit

### ISSUE THREAD

**Issue by Gregoor** [microsoft/vscode#117184]
In #116945 I ran into the issue of selection setting not happening as part of the same "transaction" when using `TextEditor.edit` or `WorkspaceEdit.applyEdit` and thus bugs related to intermediates keypress happening at the wrong locations. Fortunately @jrieken pointed me towards the snippet API which does allow me to set both at the same time. Unfortunately that seems to be limited to a single edit, which works for what I'm currently doing, i.e. replacing the whole document, but I want to move away from that wasteful approach. Thus my question: would it be feasible to add an API for setting the selection inside of a `TextEditorEdit`? I'd be happy to work on a PR for it!

**Comment by jrieken** [comment]
The question is how do you think this API should work? How do you want to express the "after" selection? Using numbers that are valid before or after the edit? When users hit undo I assume that you want the previous selection to be restored, right?

**Comment by Gregoor** [comment]
Could that depend on the order of operations, i.e. it'd be different between these two. The first would select after the change, the second before the change.
```javascript
editor.edit(builder => {
  builder.insert(location, value);
  builder.select(selections);
});
```
```javascript
editor.edit(builder => {
  builder.select(selections);
  builder.insert(location, value);
});
```

Wrt undo, afaik the current vscode behavior is not to have selections in the undo stack (whereas IntelliJ) does, so if a transaction only contains a selection change (without a text change), I'd then expect no undo-stop to be created.

**Comment by Gregoor** [comment]
I've spend some time reading the source, test-driving extending `TextEditorEdit` with a `select` method, which then gets added to its `_collectedEdits`, with `ITextEditOperation` extended for a `onlySelect: boolean`. Then I climbed further down the stack, making sure the field gets passed to the actual editor, through `MainThreadTextEditor.applyEdits`.
Now I am a bit stuck, reading `TextModel._doApplyEdits` and I'm floored by its complexity, not sure yet if my naive, top-down approach will slide in. Just putting this here, to re-express my interest in it, and also curious if people with more experience in that codebase have an opinion on this.

**Comment by Gregoor** [comment]
I changed my approach and just maintain my own edits queue now, by overriding `type` and other commands. So no more need for this API from my side anymore, feel free to close :v:

**Comment by jrieken** [comment]
ok, thanks for the heads up
