### ISSUE TITLE
The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'esnext', or 'system'.

### ISSUE THREAD

**Issue by xon52** [microsoft/vscode#117111]
In short, I can't seem to shake this IDE error around using `import.meta`. I've tried it using several very different projects so I'm sure it's the IDE, but not sure what.

```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
```

Steps to Reproduce:

1. Have a .env file
2. Reference "import.meta.env.SOME_KEY"

Does this issue occur when all extensions are disabled?: **Yes**

![](https://cdn.discordapp.com/attachments/807294895256502362/812529360879747112/unknown.png)

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    ...
```

**Comment by mjbvz** [comment]
Does the file part of that tsconfig project? With the file open, run `TypeScript: Go to project configuration` to check this

**Comment by xon52** [comment]
I'll have to close this as it's gone after a bunch of changes. If I see it again, I'll test and re-open.
