### ISSUE TITLE
Regression: Clicking sidebar items does not toggle properly on 1.54

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#117128]
- VS Code Version:  1.54.0 (insiders)
- OS Version: Windows 10

Steps to Reproduce:

1. Open a project (im using https://github.com/boa-dev/boa) with 1.54 and click on a folder in the side bar view
2. Clicking the side-chevron works ok , but anywhere else along that line only opens the folder on the 5th or 6th click
2. Open the same project with 1.53.1
3. Clicking anywhere along the line works

1.54:
It's hard to see in the gif but im clicking multiple times on the line
![Boa_WSL](https://user-images.githubusercontent.com/936006/108594741-a6b14200-7373-11eb-9c56-737d02b3ad58.gif)

1.53
![Boa_working](https://user-images.githubusercontent.com/936006/108594745-a9ac3280-7373-11eb-9022-dd6e2c6a0d0a.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Probably caused by #115873. Next Insiders should switch the default for the new `workbench.tree.expandMode` setting so it works the same as 1.53 unless you explicitly set that to the other value. Meanwhile you can use the setting to reinstate 1.53 behaviour.

cc @joaomoreno
