### ISSUE TITLE
Settings Sync

### ISSUE THREAD

**Issue by adamkgoldfarb** [microsoft/vscode#117197]
Issue Type: <b>Bug</b>

I was scrolling through my installed themes on a Sunday night as one does, and I think that was causing merge issues with the settings sync. Then that shut down the sync because of too many requests. Not a big issue but just FYI.

VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:13:45.061Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (47.40GB free)|
|Process Argv|--crash-reporter-id 90c2d959-9372-4691-a2f1-a5276c948a88|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
parquet-viewer|dvi|1.0.1
dotenv|mik|1.0.1
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
vscode-sanddance|msr|3.1.1
vscode-data-preview|Ran|2.2.0
vscode-yaml|red|0.15.0
ayu|tea|0.20.1

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoc:30257851
vscoresta800:30259386

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See #91286
