### ISSUE TITLE
OSX: Keybinding for cmd+e is wrongly mapped to "actions.find" instead of "workbench.action.quickOpen"

### ISSUE THREAD

**Issue by Penryn** [Microsoft/vscode#11711]
- VSCode Version: 1.5.0
- OS Version: OSX El Capitan

Steps to Reproduce:

1. Open keybinding preferences in OSX, find "cmd+e"
2. L148 reads `{ "key": "cmd+e",                 "command": "actions.find" },`

In Linux, the equivalent "ctrl+e" has the following mappings:
```
{ "key": "ctrl+e",                "command": "workbench.action.quickOpen" },
{ "key": "ctrl+e",                "command": "workbench.action.quickOpenNavigateNext",
                                     "when": "inQuickOpen" },
```

In OSX, `cmd+e` was formerly (prior to 1.5.0) mapped to these same bindings as Linux's`ctrl+e`.

**Workaround for users:**
1. Go to the application menu *Code => Preferences => Keyboard Shortcuts*
2. Paste the following into the keybindings.json file:
```
    {
        "key": "cmd+e",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "cmd+e",
        "command": "workbench.action.quickOpenNavigateNext",
        "when": "inQuickOpen"
    }
```

**Comment by david-mitchell** [comment]
This change is be design (see the [release notes](https://code.visualstudio.com/updates/v1_5)) because Command-E is a standard Mac keyboard shortcut.

**Comment by david-mitchell** [comment]
See also #3431

**Comment by Penryn** [comment]
Oh.
If it's by design it's not a bug. Thank you for the references.
