### ISSUE TITLE
OSX: ctrl+n/ctrl+p no longer cycle list item selection in command palette

### ISSUE THREAD

**Issue by camhux** [Microsoft/vscode#11716]
- VSCode Version: 1.5.0
- OS Version: OS X El Capitan 10.11.6

Before updating to VSCode 1.5.0, I used `ctrl+n`/`ctrl+p` to cycle through the list of suggestions in the command palette menu, identical to how those bindings behave in an IntelliSense/autocomplete menu within the editor. These bindings no longer work in the command palette despite working as expected in autocomplete menus within the editor; instead, they move the cursor in the command palette text input to the start (`ctrl+p`) or end (`ctrl+n`) of the text input itself.

Steps to Reproduce:

1. Open command palette with `cmd+p`.
2. Attempt to cycle to next item of list using `ctrl+n` keybinding. Observe no list cursor movement.
3. Attempt to cycle to previous item of list using `ctrl+p` keybinding. Observe no list cursor movement.
4. Enter any text in command palette input field and leave text cursor at the right edge of input.
5. Attempt to cycle to previous item of list using `ctrl+p` keybinding. Observe the text cursor jump to start of the input field.
6. Attempt to cycle to next item of list using `ctrl+n` keybinding. Observe the text cursor jump to the end of input field.

**Comment by camhux** [comment]
This looks like it could be a regression of changes included here: https://github.com/Microsoft/vscode/pull/7316

**Comment by ramya-rao-a** [comment]
@joaomoreno This is because we reverted the changes from #7316 ?

https://github.com/Microsoft/vscode/issues/10298#issuecomment-238266480

**Comment by joaomoreno** [comment]
Interesting.

- 05ee54fc52567a083a593f28fa90f49b9daa794f _fixed_ the issue, was shipped in 1.4
- 669064fb2e6016500488ac707fe04363db813731 reverted the fix for quick open only, because it broke stuff (#10298), was shipped in 1.5

I've reopened the original issue #7876 and am marking this as duplicate.
