### ISSUE TITLE
Indentation of files inside a folder in file browser

### ISSUE THREAD

**Issue by RichardSefton** [microsoft/vscode#117192]
I'd like to see the files contained inside a file browser indented slightly for and for more clarity between files and folders. This is because I and some colleagues have trouble working on larger projects in navigating the file browser. Often losing track of what folder we are looking in or what files belong to a folder.

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/issues/102025#issuecomment-656366713 help?

**Comment by RichardSefton** [comment]
Actually it does. It's exactly what I was looking for

**Comment by isidorn** [comment]
Great, let's close then
