### ISSUE TITLE
MacBook TB - Icon Colours dont match the UI debug bar colours 

### ISSUE THREAD

**Issue by preethamraj27** [microsoft/vscode#117185]
Hi, 
On a MacBook with a TouchBar (TB), the colour of the ICONS , dont match the GUI , especially in debugger, Play/Continue/Reset/Stop , would be nice to reflect the UI colours. 
Thanks for looking at this !
![Screenshot 2021-02-21 at 10 48 10 PM](https://user-images.githubusercontent.com/49123461/108632869-166c1d80-7497-11eb-8a62-96410af7b306.png)

**Comment by isidorn** [comment]
As far as I know the touchbar colors have to be black and white. Thus we are limited here what we can do.
@misolori or @bpasero can correct me if I am wrong

**Comment by preethamraj27** [comment]
![image](https://user-images.githubusercontent.com/49123461/108684323-c7ff6300-7518-11eb-88d2-0758404188c9.png)
Thank you for looking in to this, The Touch Bar does support colours , see the attached image. It would be great to have the same colours for debug tool bar too !

**Comment by bpasero** [comment]
I think our touchbar icons are just PNGs, so should be possible to support other colors. Code pointer of where they get added via Electron APIs:

https://github.com/microsoft/vscode/blob/6ecae6f5f946c925b01aec7422fdbc0cfd1c9bd3/src/vs/platform/windows/electron-main/window.ts#L1372-L1372

**Comment by isidorn** [comment]
Okey. Then I think maybe explicitly we decided for debug to be black and white. @misolori would know more.

**Comment by misolori** [comment]
This is true, appears that we can use color on the pngs:

![image](https://user-images.githubusercontent.com/35271042/108748496-83ad9c00-74f3-11eb-9fd6-f0fbea538c8c.png)

The background also does not change if you are on light theme, so we could roll this out easily.

**Comment by isidorn** [comment]
Cool. I like the change to use colors.
@misolori let me know if I can help somehow/

**Comment by isidorn** [comment]
@misolori just a reminder regarding this one. Do we want to add colors to our touchbar icons?

**Comment by misolori** [comment]
Updated these assets, the play button will be continue without debugging and the play + debug icon will be debugging:

![image](https://user-images.githubusercontent.com/35271042/117506407-64db7500-af3a-11eb-9629-8e9ad11121b2.png)

![image](https://user-images.githubusercontent.com/35271042/117506435-702ea080-af3a-11eb-838e-ef71be85bf43.png)

**Comment by misolori** [comment]
For verification: use a macOS touch bar or the [simulator](https://sindresorhus.com/touch-bar-simulator/) and debug a file. You should see the full debug toolbar when you start debugging.

**Comment by isidorn** [comment]
OMG looks amazing -> verified
@misolori great job
Please note this related bug that we are working on fixing https://github.com/microsoft/vscode/issues/123105
