### ISSUE TITLE
CLI arguments have no effect when running vscode built from source.

### ISSUE THREAD

**Issue by jarl-dk** [microsoft/vscode#117171]
- VS Code Version: 1.53.2 (built from source)
- OS Version: Ubuntu 20.04.2

Steps to Reproduce:

1. Biuld VScode from source
2. Run vscode with cli arguments, say `./scripts/code.sh --version`

Expected behaviour is that the version string is printed on standard out and nothing more.

Actual behaviour is that the cli argument is ignored and the UI is started.

**Comment by joaomoreno** [comment]
Please use `./scripts/code-cli.sh --version`

**Comment by jarl-dk** [comment]
OK. Thanks a lot, but what about arguments like project directories, such as
```
code path/to/my/project/
```
How is such a directory argument passed to the vscode UI?

**Comment by joaomoreno** [comment]
Same: use `code-cli.sh`.

**Comment by jarl-dk** [comment]
Thank you so much. That really made it. I think it would be very useful to mention this in the README.md file or the wiki: https://github.com/microsoft/vscode/wiki/How-to-Contribute
