### ISSUE TITLE
VSCode will not start--minimist module missing

### ISSUE THREAD

**Issue by rgmembreno** [Microsoft/vscode#11717]
- VSCode Version: Latest (applied update today)
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Auto-updated VSCode
2. Got an error saying VSCode failed to install, retried twice and then aborted install
3. Attempted to run code and same popup window from update appears

![vscodeupdaterrror](https://cloud.githubusercontent.com/assets/11397903/18367089/3c936a08-75ce-11e6-94c0-ac9bf67ffb23.png)

**Comment by rgmembreno** [comment]
Note that 1/5 updates I apply will fail midway with a popup window, and the fix before this was to just abort the install and re-open VSCode and everything worked fine.  Today is the first time that it fails to start.

**Comment by joaomoreno** [comment]
Next time you get the _popup window_, take a screenshot and show us in a new issue.

If installation fails, anything goes. If you reinstall successfully, it will work.

**Comment by rgmembreno** [comment]
Thanks @joaomoreno, I got the same error when re-installing VSCode, so I'll open a new issue right now.
