### ISSUE TITLE
MacBook external display VSCODE text blurred

### ISSUE THREAD

**Issue by ligouhai** [microsoft/vscode#117160]
When my MacBook Pro is connected to the Dell 2419h monitor, the font color is very light with VS Code on and very bright without the external monitor. I tried to find a solution online by following the instructions in this blog and typing on the command line:
defaults write com.microsoft.VSCode.helper CGFontRenderingFontSmoothingDisabled -bool NO
After that, I restarted vscode and still couldn't solve it. My MacBook Pro system is Big Sur. It is worth mentioning that Intelli J editor doesn't have such a problem

**Comment by bpasero** [comment]
Was this working better in previous version? You can download the previous one from: https://az764295.vo.msecnd.net/stable/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/VSCode-darwin.zip

**Comment by ligouhai** [comment]
Thank you very much.

发自我的iPhone


------------------ Original ------------------
