### ISSUE TITLE
Bug [VSCode Insiders]: Explorer folder expanding bug

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#117178]
Issue Type: <b>Bug</b>

Explorer folder expanding on single click does not happening, after click to folder and then double click can expand files of folder

VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:13:45.061Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.66GB free)|
|Process Argv|-psn_0_446573|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fish|bma|1.0.20
vscode-intelephense-client|bme|1.6.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-css-modules|cli|0.2.3
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
dprint|dpr|0.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.16
LogFileHighlighter|emi|2.11.0
prettier-vscode|esb|5.9.2
shell-format|fox|7.0.1
go|gol|0.22.1
rust-analyzer|mat|0.2.489
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.9.0
gather|ms-|2021.1.0
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
cpptools|ms-|1.2.1
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
java|red|0.75.0
vscode-yaml|red|0.15.0
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
vscode-stylelint|sty|0.86.0
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.11
vscode-todo-highlight|way|1.0.4

</details>

Settings: https://github.com/microsoft/vscode/issues/117134#issuecomment-782840412

**Comment by gjsjohnmurray** [comment]
#115873 added `workbench.tree.expandMode` to 1.54. Initially its default changed existing (1.53.2) behaviour, but Monday's Insiders should see the default switch back. Meanwhile, try changing the setting.

**Comment by dalisoft** [comment]
@gjsjohnmurray Thanks, it fixed my issue
