### ISSUE TITLE
Corrupted ZIP, no re-download occurs

### ISSUE THREAD

**Issue by oldium** [microsoft/vscode#117169]
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows 10 1909 build 18363.1316

Steps to Reproduce:

1. Have HTTP proxy with authentication.
2. Start VS Code and let auto-download try to install extension update.
3. Observe the „Corrupt ZIP: end of central directory record signature not found“ message.
4. Close VS Code.
4. Authenticate the proxy in normal browser.
5. Start VS Code and try to install the update again.
6. Immediately you see the „Corrupt ZIP: end of central directory record signature not found“.

Does this issue occur when all extensions are disabled?: Yes

### Root-cause analysis
The problem is that the invalid file got downloaded and kept in place. I found file `c:\Users\<user>\AppData\Roaming\Code\CachedExtensionVSIXs\ms-python.python-2021.2.582707922` with the following content:

```html
<html>
<body onload="document.forms[0].submit()">
<noscript>
<p>        You will be redirected to a ....
        </p>
</noscript>
<form action="..." method="post">
<input type="hidden" name="RelayState" value="..."/>
<input type="hidden" ... value="..."/>
<noscript>
<input type="submit" value="Continue"/>
</noscript>
</form>
</body>
</html>
````  

This file was re-used while retrying to update the extension. Even after uninstalling and trying to install the extension again the problem persisted.

Invalid downloaded files could be kept after download for investigation, but they should be re-downloaded when trying to update again. Solution could be to rename the downloaded file to something else (add “corrupted” prefix/suffix) when corruption is detected for example.

**Comment by joaomoreno** [comment]
@sandy081 This is a good suggestion. Invalid VSIX downloads should not be cached.

**Comment by connor4312** [comment]
Verified via code review
