### ISSUE TITLE
Some fonts do not work after restart PC

### ISSUE THREAD

**Issue by Valker-Vinicius** [microsoft/vscode#117137]
Issue Type: <b>Bug</b>

I wanted to use the JetBrains Mono font, so I downloaded the zip from the JetBrains's site, unzipped it and dragged all fonts in ttf folder to the "Fonts" folder on Windows 10.
At first, it worked fine when I went to Preferences > Settings > Fonts and selected JetBrains Mono as my font, however when I restart my PC and go again to my VS Code the font displayed is another that I can't recognize (I will put an uploaded image below). When I reinstall the font it comes to work again, but stops when I restart my PC.
I noticed that is not happens only with JetBrains Mono. Some fonts that I have installed also don't work also. I noticed also that these fonts are in the Windows's "Fonts" folder, but not in the "Font setting" screen, as well as JetBrains (who briefly appears on this screen when I reinstall it). I tested these fonts, including JetBrains, in other apps like LibreOffice Writer, GIMP and Visual Studio 2019 and all worked fine.
So I would like to know how to permanently set JetBrains Mono as my font in Visual Studio Code. I would appreciate it if you could help me.
Link to image of how the font is displayed when my PC is restarted: https://drive.google.com/file/d/1gBPefGR5T5L4bnBZRF4oE20EI-fXtOMH/view?usp=sharing

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.93GB (1.21GB free)|
|Process Argv|--crash-reporter-id a94b5f0b-fbb1-42df-853d-9484071110e0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
vscode-css-formatter|aes|1.0.1
Bookmarks|ale|13.0.1
vscode-sqlite|ale|0.11.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
nunjucks-template|ese|0.3.1
auto-rename-tag|for|0.1.6
rest-client|hum|0.24.4
vscode-styled-components|jpo|1.5.0
vscode-exec-node|mir|0.5.3
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
code-spell-checker-portuguese-brazilian|str|0.1.6
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30259261

```

</details>

**Comment by alexdima** [comment]
@Valker-Vinicius Our font rendering is eventually handled by Electron/Chromium. I honestly don't know what is the exact problem when you restart the machine. Maybe you have some Windows policy that deletes all the user-installed fonts on restart (organization managed)? I normally install fonts using right click > install on the font family and I never encountered any problems. Does that work for you:

![image](https://user-images.githubusercontent.com/5047891/108738936-664cf200-7534-11eb-8595-f518790d41ec.png)

**Comment by Valker-Vinicius** [comment]
@alexdima I already installed that way and the problem persists. This is my personal PC, so there are no organizations involved. I also think there are no policy with the Windows since other apps render the font fine. I also don't know what is happening; it is very weird cause the font was already installed in all possible ways that I know and works in other apps.
There is any other information that I could send to facilitate? Anyway I am sending my font configs in VS Code:
![image](https://user-images.githubusercontent.com/65914461/108757416-91314900-7528-11eb-86b6-2611d98e7c14.png)

**Comment by alexdima** [comment]
@Valker-Vinicius Did you try commenting out `editor.fontWeight`? Maybe that one confuses Chromium as to which font variant to select? Could you also try commenting out other font related settings like `fontLigatures` and `letterSpacing` ?

**Comment by Valker-Vinicius** [comment]
I tried to comment all fonts settings in the json but the result is the same 😕
Should I send all my settings.json file to see all configs?
![image](https://user-images.githubusercontent.com/65914461/108760191-1c600e00-752c-11eb-92c2-70cc986565fe.png)

**Comment by alexdima** [comment]
I'm sorry, I really don't know what the problem is. The only hint is that the font works until a restart. It could be an OS problem. Here is what I could find by searching online -- https://social.technet.microsoft.com/Forums/en-US/2da1189a-6533-486c-8185-044bea4b6221/fonts-getting-uninstalled-after-restart?forum=win10itprogeneral .

It could be a file permission problem, or who knows... Could you try uninstalling **all variants** of the font both using the Preferences and from the Fonts folder, restarting, and then installing all variants using their official steps documented at https://github.com/JetBrains/JetBrainsMono#or-manually (download from https://github.com/JetBrains/JetBrainsMono/releases/download/v2.225/JetBrainsMono-2.225.zip , Select all font files in the folder, right-click any of them, then pick "Install" from the menu.)

From my side, it looks like you're doing everything OK, so I really don't know what to say...

**Comment by Valker-Vinicius** [comment]
I have uninstalled and reinstalled the font this time for all users (even if there is only one) and for now it is working. After shut down and boot my PC tomorrow I will come here back to tell the results. Thanks a lot @alexdima.

**Comment by Valker-Vinicius** [comment]
@alexdima Apologies for the delay but it worked. I don't know if it happened due to the reinstallation or the installation for all users but  worked 😅
