### ISSUE TITLE
Copy/Paste text from web pages freezes the VSCode editor

### ISSUE THREAD

**Issue by P4radoX** [microsoft/vscode#117132]
Hello Team,

- VS Code Version: 1.53.2
- OS Version: Linux x64 5.10.16-200.fc33.x86_64

Steps to Reproduce:

1. Copy any text from any web page
2. Paste it on any text file format

Does this issue occur when all extensions are disabled?: Yes

The only way to go back in a stable situation is to copy anything else without pasting it.

Best regards,

**Comment by alexdima** [comment]
@P4radoX Sorry for the late reply, I tried this before and also tried it again, but I cannot reproduce. Does this always reproduce for you?
