### ISSUE TITLE
Terminal initially gets wrong size

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117188]
When I create a terminal, the cursor always blinks somewhere in the middle of the pane before it moves to the top. It seems like the terminal is being layed out at the wrong size for a moment. I think I first noticed this a month or so ago.

https://user-images.githubusercontent.com/323878/108637893-7c2dba80-7441-11eb-928d-4bcccd1c3310.mp4

It's hard to see in a recording. It happens pretty much every time so I can help debug.

**Comment by meganrogge** [comment]
seems this only happens if you increase the height of the panel beyond the normal dimensions

**Comment by roblourens** [comment]
My terminal is not unusually tall. Not sure what qualifies as "normal" 😁

**Comment by meganrogge** [comment]
When a terminal is the default height, I can't reproduce the issue on Windows. 

![recording (25)](https://user-images.githubusercontent.com/29464607/108772028-57a11380-7511-11eb-9f6b-bca63d53d076.gif)

**Comment by Tyriar** [comment]
All terminals seem to be getting created as 0x0 initially it seems:

![image](https://user-images.githubusercontent.com/2193314/112695833-ffc43800-8e41-11eb-83e5-28bddbc93f6a.png)
