### ISSUE TITLE
Replace keyboard shortcut does not work in MacOS

### ISSUE THREAD

**Issue by lflucasferreira** [microsoft/vscode#117151]
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z (1 wk ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Select a word that you need to replace
2. Press the shortcut <kbd>OPTION</kbd> + <kbd>COMMAND</kbd> + <kbd>F</kbd>.

Does this issue occur when all extensions are disabled?: **Yes (I disabled all of them)**

<img width="428" alt="Screen Shot 2021-02-20 at 19 33 45" src="https://user-images.githubusercontent.com/5920654/108610289-5bb71f00-73b3-11eb-853d-e5713fb86f86.png">

**Comment by gjsjohnmurray** [comment]
Please follow the guidance at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by lflucasferreira** [comment]
Hey guys, I am sorry for this issue. I found out that the [Spectacle](https://www.spectacleapp.com/) app is causing this problem because it uses the same shorcut. That's why I am closing this one.
