### ISSUE TITLE
Markdown : Keyboard shortcuts

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/vscode#11713]
- VSCode Version: 1.5
- OS Version: 14915

It would be great if you could provide keyboard shortcuts for Markdown file tags like for making the text bold, italic or wrap in code or change header level etc.

**Comment by ramya-rao-a** [comment]
Try the [Markdown Shortcuts](https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts) extension or [Markdown Helper](https://marketplace.visualstudio.com/items?itemName=joshbax.mdhelper) or any of the other extensions. For more features log a feature request in those extensions.

**Comment by ratishphilip** [comment]
Thanks!
