### ISSUE TITLE
JoinLines command jsdoc support

### ISSUE THREAD

**Issue by awerlogus** [microsoft/vscode#117144]
Version: 1.54.0-insider (system setup)
Commit: 192c817fd350bcbf3caecae22a45ec39bae78516
Date: 2021-02-19T05:14:28.632Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

editor.action.joinLines command needs some tuning to work with jsdoc. Currently if you will try to join multiline jsdoc comment into a single line, it won't remove star symbols at the beginning of each line.

Before:

```js
/**
 * @typedef {number} A
 */
```

Currently after:

```js
/** * @typedef {number} A */
```

Expected after: 

```js
/** @typedef {number} A */
```

**Comment by mjbvz** [comment]
@alexdima @rebornix Adding you since joinLine is a basic text editing feature
