### ISSUE TITLE
PHP Debug: When breakpoint is hit, tab is frozen for long time, unless vscode refresh happens

### ISSUE THREAD

**Issue by pamtbaau** [microsoft/vscode#117162]
- VS Code Version: 1.53.2  Note: Does NOT happen with 1.52.1
- OS Version: Windows 10 latest

Steps to Reproduce:

1. Set breakpoint in PHP  (Using PHP Debug v1.14.9)
2. Browse to webpage
3. VSCode icon highlights when breakpoint is hit
4. Click VSCode to the front
5. If current tab contains breakpoint, tab is frozen for 60+ seconds.
   1. Breakpoint is not highlighted 
   2. No editing possible , no selecting, etc.
6. Create any event in VSCode, eg. minimize/maximize, click other window, click other tab, ...
7. Breakpoint is highlighted and tab is unfrozen.

Does this issue occur when all extensions are disabled?: Yes/No
This cannot be determined since extension is required.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/114459

**Comment by pamtbaau** [comment]
@isidorn, With all due respect, but I fail to see any overlap between this issue and [#114459](https://github.com/microsoft/vscode/issues/114459).

Would you mind considering re-opening this issue?

**Comment by isidorn** [comment]
@pamtbaau use `code --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` to start the VSCode instance. If it still reproduces that is a proof it is a different issues and then let me know and we can reopen

**Comment by pamtbaau** [comment]
@isidorn, You are right. I cannot reproduce when using `code --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>`

**Comment by isidorn** [comment]
Thanks for trying, then it is a duplicate. Please follow that issue for details.
