### ISSUE TITLE
Auto port forwarding does not work with nodemon

### ISSUE THREAD

**Issue by i5heu** [microsoft/vscode#117118]
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Note: this bug happens in Codespaces

Steps to Reproduce:

1. Start express in nodemon and console.log "http://127.0.0.1:8080" from the app.listen function
2. the port is not auto forwarded

Code that the error is observable: https://github.com/i5heu/personal-edms/tree/529eae0b16c7aa4fe17b63318289ec8415c553cf
``npm i && npx nodemon``

Does this issue occur when all extensions are disabled?: Yes

**Comment by i5heu** [comment]
https://user-images.githubusercontent.com/22565269/108589526-f1748f00-735e-11eb-95af-0cf839b17884.mp4

**Comment by alexr00** [comment]
@i5heu can you please collect some logs? Steps:

1. Run the command Developer: Set Log Level. Choose Trace.
2. Repro your issue.
3. Open the Output panel and share the logs from Log (Window), Log (Extension Host), and Log (Remote Extension Host).
