### ISSUE TITLE
Customize the location of ".vscode" directory

### ISSUE THREAD

**Issue by xcetos** [microsoft/vscode#117161]
I found that VSCode will automatically create the `$HOME/.vscode` directory to store user data and extensions. I wonder if there is a way to customize the path of these files with environment variables, such as `$VIMRC` for vim and `$ZDOTDIR` for zsh. Currently I only see one [related solution](https://stackoverflow.com/questions/65559144/is-there-a-way-to-tell-vscode-where-the-vscode-folder-is), and it does not support macOS.

**Comment by plainerman** [comment]
I don't see any issue, why your related solution should not work on mac? However, it does not work in portable mode.
See related issue #32933

**Comment by xcetos** [comment]
Hey! Thank you for your comment. Let me elaborate on my problem. I checked #32933 and found it cannot fix my problem. Yet I can launch VS code in the terminal with options `--extensions-dir` and `--user-data-dir` to specify directories. But I don't know whether there is a way in macOS to pass these options every time VS code launches even not from the terminal. If you have solutions, I would appreciate it a lot.

I find many applications like to create dot folder in `$HOME`, e.g. `.conda`, `.vim`, `.jupyter`. Some of them did this because they need a location with write permission to store data and configurations. And most of them provide useful environment variables to help user customize their preferable location. In this issue, I would like to store user data in `$XDG_CONFIG_DIR/vscode` so that I can manage all my configurations with ease. I know that I can create a symlink to the `.vscode` directory, but I prefer a tidy home directory.

**Comment by plainerman** [comment]
If you are talking about launching it via macOS UI, you can take a look [here](https://superuser.com/a/116237).
If you want to open it via CLI with those arguments, you can add an alias in your `.zshrc`.

But such specific questions should be asked on StackOverflow, where the (VSCode) community will be happy to help.

@isidorn is passing (some) arguments via environmental variables to VSCode something we want to pursue? Or can we close this issue?

**Comment by sandy081** [comment]
Arguments can be passed via environment variables. but (`user-data-dir`) is not a valid env variable format. 

There are no plans to support these, hence closing.
