### ISSUE TITLE
Unable to use VS Code to debug Extension Host

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#117103]
- VS Code Version: 1.54.0-insider
- OS Version: Windows 10
![image](https://user-images.githubusercontent.com/11685408/108575171-3bf9fb00-72ce-11eb-9cc5-4d2c36d2ed3e.png)

Working with @rebornix to debug a problem in my extension, we got into a situation where we couldn't hit breakpoints in extension host. However, console.log() calls were definitely being made (which is how we ended up debugging the original problem). So it seems there's something not working right with the debugger.

Steps to Reproduce 1

1. Open the VS Code repo and build
2. Debug (F5) with Renderers and Extension Host process configuration
3. Manipulate OSS in some manner

Result: 
I have gotten this messagebox. I believe @rebornix was reproing on his machine as well.
![image](https://user-images.githubusercontent.com/11685408/108574889-5b445880-72cd-11eb-8882-8dc53f40c61e.png)

I have also gotten OSS to start and load my extension correctly. However, it's not hitting any breakpoints in extension host. 

Steps to Reproduce 2
1. Open the VS Code repo and build
2. Run OSS via code.bat
3. Back in Insiders set the configuration to Attach to Extension Host

Result: 
I see no processes in the CallStack tab. I should see two. No breakpoints are hit in the extension host. @rebornix did NOT repro this problem. 
![image](https://user-images.githubusercontent.com/11685408/108574809-2b955080-72cd-11eb-8d01-415794aaa602.png)

**Comment by rebornix** [comment]
We also tried 

* Open VS Code in OSS
* Launch "Renderer and Extension Host processes"

and then the UI crashed because of 

![image](https://user-images.githubusercontent.com/876920/108575433-16212600-72cf-11eb-832c-a640ca0a04d6.png)

Running VS Code in OSS and then launch "Attach to extension host" doesn't work on @greazer 's machine as well and that's the only working approach on my machine.

**Comment by connor4312** [comment]
I'm not able to reproduce either of these cases. E.g. the renderer and extension host connects to both 

![](https://memes.peet.io/img/21-02-b746b8e7-313c-42f5-a90c-0e165f63f4ac.png)

Make sure nothing else is running/listening the specific ports, and check the state of any antivirus or firewalls you have running. The errors reported are problems establishing or querying the websocket connection for the debugeee.

**Comment by rebornix** [comment]
@connor4312 can you provide a bit more info about what we should look for in firewall or antivirus?

When I launch from VS Code Insiders, I see these two entries from `chrome://inspect`

![image](https://user-images.githubusercontent.com/876920/108578251-d52d0f80-72d6-11eb-8dcc-e693a7b5060a.png)

however js debug can't connect to it and there is no info in Debug Console

![image](https://user-images.githubusercontent.com/876920/108577986-b7f84100-72d6-11eb-8b89-2c32fa9958b1.png)

**Comment by rebornix** [comment]
I also doubt if it has anything to do with antivirus or firewalls as sometimes it connects to the OSS I'm running and sometimes (like right now), it fails 100% of the time.

In OSS, I'm seeing

```
[Extension Host] debugger listening on port 5870
[Extension Host] debugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/ca5e0598-7d29-487b-89ea-1425e670f9bc

```

and I can debug directly in Edge/Chrome, but VS Code fails to connect to this. @connor4312 thoughts?

**Comment by connor4312** [comment]
Can you get a log file? That will include the reason/error from the connection

/jsDebugLogs
