### ISSUE TITLE
[html] infinite dots on script tag

### ISSUE THREAD

**Issue by sum424** [microsoft/vscode#117245]
When I create script tag and press ./ without space on opening tag. Infinite ../ appears until I press other keys. 
My code: 
<script./></script>
It shows: 
<script......................./ ></script......................>

**Comment by aeschli** [comment]
I can't reproduce. Did you try with extensions disabled?

**Comment by sum424** [comment]
I tried by disabling emmet extension but this issue still exists. Maybe this problem exists only on my device I don't know.

**Comment by aeschli** [comment]
You can run the command `Developer: Reload with Extensions Disabled`.
Do you have any strange keybindings defined?

**Comment by sum424** [comment]
Ok. I'll try on that

**Comment by sum424** [comment]
the bug or problem is still not fixed

**Comment by aeschli** [comment]
@sum424 Did you try if the problem also exists with extensions disabled?
`Developer: Reload with Extensions Disabled`
