### ISSUE TITLE
Repeated content text in the left sidebar of the main interface

### ISSUE THREAD

**Issue by zoain-it** [microsoft/vscode#117216]
Issue Type: <b>Bug</b>

Repeated content text in the left sidebar of the main interface
<img width="1028" alt="截屏2021-02-22 下午4 49 43" src="https://user-images.githubusercontent.com/43292634/108684564-07847a00-752e-11eb-8784-ced29636c385.png">

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T05:27:56.020Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id ce3871ec-e05f-41b3-8f88-1758a5ac7528|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.12.0
rust-analyzer|mat|0.2.497
java|red|0.75.0
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Can not repro this on the macOS.
Also assigning to @joaomoreno since I know he did some changes here

**Comment by joaomoreno** [comment]
Yeah... https://github.com/microsoft/vscode/commit/ea2c1e5991df4dd0097b7b80666ce37763de8695
