### ISSUE TITLE
Requesting session from auth provider that supports multiple accounts returns undefined

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117266]
Issue Type: <b>Bug</b>

Have an extension with the following:
```ts
	const session = await vscode.authentication.getSession('microsoft', ["https://management.core.windows.net/.default",
	"offline_access"], { createIfNone: true });
	console.log(session);

	const session2 = await vscode.authentication.getSession('microsoft', ["https://management.core.windows.net/.default",
	"offline_access"], { createIfNone: false });
	console.log(session2)
```

session2 should match the first session, but instead is undefined

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T06:44:36.656Z)
OS version: Darwin x64 19.6.0

**Comment by samrat-gavale** [comment]
@RMacfarlane thank you for the quick fix! Any ideas on when this commit will be released into an update?

**Comment by RMacfarlane** [comment]
@samrat-gavale It should be released in tomorrow's insiders version around 8am PST!
