### ISSUE TITLE
Add search to Outline panel

### ISSUE THREAD

**Issue by gsscoder** [microsoft/vscode#117235]
It would be handy to being able to search in the Outline pane.

![image](https://user-images.githubusercontent.com/1194228/108710258-1bbb7d80-7514-11eb-90fe-8bea65278aaa.png)

Thanks for awesome project!

Regards,
Giacomo S. S,

**Comment by jrieken** [comment]
All trees and lists of the same search which goes like this: focus the tree, start typing, select whether you want filtering or highlights

**Comment by jrieken** [comment]
<img width="383" alt="Screenshot 2021-02-22 at 14 24 43" src="https://user-images.githubusercontent.com/1794099/108714334-b7032180-7519-11eb-98d9-2124db6c139a.png">

**Comment by gsscoder** [comment]
I missed it, thank you @jrieken!
