### ISSUE TITLE
Pressing AltGr modifier key on German keyboard moves cursor one position left

### ISSUE THREAD

**Issue by meldorq** [microsoft/vscode#117218]
Issue Type: <b>Bug</b>

The AltGr key (right Alt) is needed on the German keyboard to input special characters like @,{,[,],}.
It is only a modifier key like shift or Ctrl. But since the latest upgrade of VS Code, it moves the cursor one character left, too.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3931)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.53GB (0.63GB free)|
|Process Argv|--log trace --no-sandbox --crash-reporter-id 3ec58370-c223-4cf2-9abf-526ec36037d9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
svn-scm|joh|2.13.5
vetur|oct|0.32.0
vue-vscode-snippets|sdr|2.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by alexdima** [comment]
Please take a look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

Do any of those scenarios / workarounds apply to you?

**Comment by meldorq** [comment]
> Please take a look at https://github.com/microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings
> 
> Do any of those scenarios / workarounds apply to you?

Thanks for your reply.
Yes, I'm working via RDP. Setting "keyboard.dispatch": "keyCode" helps.
