### ISSUE TITLE
Add version information to Mac and Windows distributables

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11722]
Suggested in https://news.ycombinator.com/item?id=12458003

So `VSCodeSetup-stable.exe` should be something like `VSCodeSetup-1.5.1.exe` or `VSCodeSetup-1.6.0-insiders.exe`, similar to Linux https://github.com/Microsoft/vscode/issues/6587 https://github.com/Microsoft/vscode/issues/6546

**Comment by joaomoreno** [comment]
Done for Windows. Need to update signing service for the macOS one.

**Comment by joaomoreno** [comment]
#3900
