### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117240]
- [x] Windows @stevencl
- [x] macOS @gregvanl
- [x] Linux @bpasero

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117240%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/master/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by bpasero** [comment]
Both @isidorn and me see weirdness on Linux, will investigate...

**Comment by stevencl** [comment]
I got a few timeout errors but was able to manually run the tests successfully.

  1) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies opened editors are restored:
     Error: Timeout: get element '.editor-instance > div > div.welcomePageFocusElement[tabIndex="0"]' after 20 seconds.
      at c:\src\vscode\vscode\test\automation\out\code.js:188:23
      at Generator.next (<anonymous>)
      at fulfilled (c:\src\vscode\vscode\test\automation\out\code.js:9:58)

  2) VSCode Smoke Tests (Electron)
       Stable vs Insiders Smoke Tests: This test MUST run before releasing by providing the --stable-build command line argument
         Datamigration
           verifies that 'hot exit' works for dirty files:
     Error: Timeout: get element '.editor-instance > div > div.welcomePageFocusElement[tabIndex="0"]' after 20 seconds.
      at c:\src\vscode\vscode\test\automation\out\code.js:188:23
      at Generator.next (<anonymous>)
      at fulfilled (c:\src\vscode\vscode\test\automation\out\code.js:9:58)

  3) "after all" hook in "{root}":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

**Comment by bpasero** [comment]
Opened https://github.com/microsoft/vscode/issues/117420 for investigation. As a workaround you can run without the `--stable-build` command line flag.

**Comment by bpasero** [comment]
I pushed a fix to be able to use smoke tests with `--stable-build` flag.

**Comment by bpasero** [comment]
@gregvanl since I also tested macOS you don't have to run the smoke test anymore.
