### ISSUE TITLE
Search: Horizontal scrolling is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117221]
When enabling horizontal scrolling the search viewlet is completely broken.

It might be doing some weird CSS which escapes the tree horizontal scrolling rules.

I'm pretty sure it was working just fine last time I touched horizontal scrolling.

Similar to https://github.com/microsoft/vscode/issues/69557

**Comment by roblourens** [comment]
This is probably from the other change we were discussing where now I call `tree.layout()` to let it measure its own container. Do I have to do something different there for horizontal scrolling?

**Comment by roblourens** [comment]
f1202da4a00a64d6fd685c22ec3b3de717a28673

**Comment by joaomoreno** [comment]
This seems like it's working now.

**Comment by andreamah** [comment]
@joaomoreno I see this when i enable horizontal scrolling. The action buttons are far to the right. Is this expected?

[![Image from Gyazo](https://i.gyazo.com/6273158ca9b1930b62509df0960e8203.gif)](https://gyazo.com/6273158ca9b1930b62509df0960e8203)

**Comment by roblourens** [comment]
Yes, there was another issue suggesting having the buttons float to the left when horizontal scrolling is enabled

**Comment by andreamah** [comment]
right, it's at #45717
