### ISSUE TITLE
npm scripts

### ISSUE THREAD

**Issue by sevensamurai** [microsoft/vscode#117209]
Issue Type: <b>Bug</b>

Getting this error while running any npm script:
The term  '-Command' is not recognized as the name of a cmdlet, function, script file, or operable program

This used to work fine, clean/reinstall didn't fixed it, still same issue

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
NodeJS 14.15.5 
NPM 6.14.11
NG 11.2.1

**Comment by sevensamurai** [comment]
![image](https://user-images.githubusercontent.com/26825888/108678032-6a3a3d80-754f-11eb-8f98-3c37162c1953.png)

**Comment by alexr00** [comment]
Thanks for the screenshot. Can you share any `terminal` and `task` settings that you have configured?

**Comment by sevensamurai** [comment]
Thanks for checking, @alexr00 
Sending you a copy of the system info/details below
I've uninstalled/cleaned all settings, reinstalled again, same story, it seems to be picking up old settings somewhere
Terminal/Task defaults/unchanged, it seems the terminal is PowerShell 6.2.3
Let me know if you need more info

____________________

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.40GB free)|
|Process Argv|X:\\SampleIonic|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>
Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.53.4
</details><details>
<summary>A/B Experiments</summary>
```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843
```
</details>

**Comment by sevensamurai** [comment]
hi @alexr00 or anyone running into the same problem, it turns out this can be fixed this way:
* check Task dropdown and pick "Select Default Shell"
* select "Git Bash" (you probably already have that)
Somehow updating VS code picked up a wrong shell
