### ISSUE TITLE
Autocomplete for file path

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11725]
In YouCompleteMe, when you type `'./`, it will suggest local files:

![image](https://cloud.githubusercontent.com/assets/4033249/18370126/8dea9532-75df-11e6-8984-4c486eadfad4.png)

I find it useful and wish it could be added to VSCode.

https://github.com/Valloric/YouCompleteMe

**Comment by ramya-rao-a** [comment]
Extension Candidate?

**Comment by hashhar** [comment]
See this [extension](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)

**Comment by octref** [comment]
@hashhar 

Wow, thank you!
