### ISSUE TITLE
Moving files folders sometime doesn't rename all relative and alias paths!

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#117201]
Maybe this will be hard to found why, but sometime vscode not rename symbols path's from all files in big projets when moving big folders.
I need manually fix this and can be a pain , lucky git linter and history help.
in this example i moving from **component** to **core** folder ! and vscode not fixed path !
![image](https://user-images.githubusercontent.com/24865815/108670656-3eff1200-74ad-11eb-911e-2c0fc349d6d3.png)
is there other people can confirm it also happened on they side when moving folder ?

also a little request, maybe hardcore feature, but are you working on the possibility to allow vscode take in account alias path from tsconfig or jsconfg when moving folders with multiple files hierarchy ?
![image](https://user-images.githubusercontent.com/24865815/108670945-ba60c380-74ad-11eb-8b76-89c70fe8ede8.png)

**Comment by isidorn** [comment]
This is done by the ts extension I believe thus forwarding to @mjbvz

**Comment by djmisterjon** [comment]
> This is done by the ts extension I believe thus forwarding to @mjbvz

ho, hum it could possibly be due to the `jsx` extension.
but it seems random behavior ! i remember move jsx files in another project and no problem ! 
maybe something broken since a update?! or inside the config of this project !
Need more test on others projects !

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue

**Comment by djmisterjon** [comment]
> Please share a minimal example project that demonstrates the issue

hum ! i not success to reproduce in a example project ! all go fine and also with Alias 🙄!! 
i will close and will reopen if i understand what wrong ! it maybe something in my project !
