### ISSUE TITLE
Disable format of plain text in HTML

### ISSUE THREAD

**Issue by BenjaVR** [Microsoft/vscode#11724]
Hello,
I work with OctoberCMS, and the html files are as following:
![](https://i.imgur.com/fMSHZKC.png)

Those lines above the `==` need to be under eachother if you want it to work. But if I format (even without any extensions!) this happens:
![](https://i.imgur.com/mdqv7dv.png)
Unfortunately this causes the code to break.

Is it possible to prevent this plain text from getting formatted inside html files?

**Comment by aeschli** [comment]
This looks like invalid HTML. Any chance you can add comments around it?
Otherwise select only the lines you want format and invoke format.

To solve that correctly you probably would need a specific language support for OctoberCMS file that never touch the lines before '====='

**Comment by mrmlnc** [comment]
@BenjaVR, I also sometimes use October CMS, so I can make the extension for support this syntax.

**Comment by BenjaVR** [comment]
@mrmlnc That would be great!

**Comment by mrmlnc** [comment]
@BenjaVR,

Well, I started work on the `octobercms` extension. Now I finished work on syntax highlighting. You can follow the progress in the [vscode-october](https://github.com/mrmlnc/vscode-octobercms) repository. Unfortunately, I now have a little time, so will work on this extension in their spare time.

![code_2016-09-21_04-02-33](https://cloud.githubusercontent.com/assets/7034281/18694139/684d8048-7fb0-11e6-8246-cebd3874e509.png)
