### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by hamzi-cell** [microsoft/vscode#117281]
- Issue Type: `Bug`
- Extension Name: `emmet`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.10240`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rzhao271** [comment]
@hamzi-cell can you give some steps so I can identify the Emmet issue? I'm wondering which file type you are using, and does the issue still persist when you use VS Code Insiders?
