### ISSUE TITLE
Test icons contribution point

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#117263]
Refs: https://github.com/microsoft/vscode/issues/114942

- [x] anyOS @misolori
- [ ] anyOS @eamodio

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117263%0A%0A)

---

The icon contribution point allow extensions to define a new icon by id, along with a default icon.
That icon id can then be used by the extension (or any other extensions that depend on the extension) at the places where `ThemeIcon` can be used.
- Product icon themes can redefine the icon (if they know about the icon id) 

Create an extension that contributes an icon and use it.

```
"contributes": {
	"icons": [
		{
			"id": "distro-ubuntu",
			"description": "Ubuntu icon",
			"default": {
				"iconFontId": "distro-icon-font",
				"character": "\\E001"
			}
		},
		{
			"id": "distro-fedora",
			"description": "Fedora icon",
			"default": {
				"iconFontId": "distro-icon-font",
				"character": "\\E002"
			}
		}
	],
	"iconFonts": [
		{
			"id": "distro-icon-font",
			"src": [
				{
					"path": "./distroicons.woff",
					"format": "woff"
				}
			]
		}
	]
}
```
In this example, an extension defines two new icon ids `distro-ubuntu` and `distro-fedora` along with default icon definitions. The icons are defined in an icon font at the given font character. The icon font is defined in a new contribution point `iconFonts`.

The [product-icon-theme-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/product-icon-theme-sample) can be used as the icon font. It also contains a script build create an icon font from svgs.

- test that the code completion, hovers and validation work when authoring an icon and icon font contribution
- test that the icon identifier must consist of at least two segments separated by minus (needs a new I-Build)
- test that that the icon ids (e.g. `distro-ubuntu` and `distro-fedora`) can be used in [markdown strings](https://github.com/microsoft/vscode/blob/e88863d191fed9c81a0087ff225ef7daf79c40b8/src/vs/vscode.d.ts#L2516) (`"$(distro-ubuntu)" Ubuntu 20.04"`) and at all places that take a [ThemeIcon](https://github.com/microsoft/vscode/blob/e88863d191fed9c81a0087ff225ef7daf79c40b8/src/vs/vscode.d.ts#L800) ( `new ThemeIcon("distro-ubuntu")`)
- test that the icon id can also be used by other extensions (if they know about the icon id)
- test that a product icon themes can redefine the icon (you can test this with the [product-icon-theme-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/product-icon-theme-sample) )

**Comment by misolori** [comment]
This is very cool and excited to see extensions use this:

![image](https://user-images.githubusercontent.com/35271042/108925409-68c15180-75f1-11eb-98e7-e9449020e5bf.png)

**Comment by eamodio** [comment]
Looks great! Can't wait for this to ship.
