### ISSUE TITLE
Peek/goto definition stop working after upgrading to 1.5

### ISSUE THREAD

**Issue by harrywangwork** [Microsoft/vscode#11726]
- VSCode Version: 1.5.1
- OS Version:Ubuntu 14.04

Steps to Reproduce:
1. Right click on a function and choose goto definition from the menu.
2. Error shows that the file cannot be found. 
The file exists on disk. Using find feature can find the file.

**Comment by ramya-rao-a** [comment]
@harrywangwork Which language and extensions are you using?

**Comment by harrywangwork** [comment]
I was using C/C++.
It worked fine with previous version.

**Comment by harrywangwork** [comment]
Trying to switch to 32-bit to see if there is luck.

**Comment by ramya-rao-a** [comment]
The Peek/Goto definition features are implemented by extension. Please log this issue in the repo for the C/C++ extension you are using. They will be able to find the root cause faster and re-open this issue here if there is any problem with the VS Code APIs

**Comment by harrywangwork** [comment]
sounds good.

**Comment by harrywangwork** [comment]
Issue resolved after updating C++ extension. Thanks for the tip.
