### ISSUE TITLE
Some forEach + async are not awaited on properly

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117205]
This maybe intentional, but I noticed a few instances of `...forEach(async` that are not fully awaited on. Note that `forEach` with `async` will execute all promises inside in parallel but return immediately.

A few calls inside this event handler, which probably are OK given this is an event handler:

https://github.com/microsoft/vscode/blob/3ee49fa3f860649a4150cbbf352b2780ccb7c7a5/src/vs/workbench/contrib/files/browser/explorerService.ts#L266-L266

But then these two which are maybe not properly awaited on:

https://github.com/microsoft/vscode/blob/59afea597bd88efcee15e93abaebe704d9dab889/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L659-L681

**Comment by isidorn** [comment]
Thanks for creating this issue, looks like an oversight on my end. I will fix.
