### ISSUE TITLE
Test: untitled editor language mode hints

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117253]
Refs: https://github.com/microsoft/vscode/issues/114307

- [x] anyOS @mjbvz
- [x] anyOS @meganrogge

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117253%0A%0A)

---

This milestone we have added hints in Untitled editors to help users set the language mode (since that is the thing that novice users struggle with the most).

Use the following setting `workbench.editor.untitled.hint` and verify:
* Having the value to `button` you get the famous blue button in the bottom right corner of every untitled file that has `plaintext` mode. Once you choose a language the button goes away
* Having the value to `text` you see an inline placeholder for untitled editors with `plaintext` mode. You can type over it, once you change the language mode the `text` goes away. And you can click to hide it.
* Having the value to `hidden` you do not see any changes to the current untitled file experience

Please note that the setting name is not final and that we will probably not ship this visible by default this stable. The setting is there just to simple try out different approaches for user studies.
Feedback and ideas are welcome - if you have time it would be good if you first read the linked issue and the discussions in the UX channel.

**Comment by meganrogge** [comment]
I prefer the `text` setting to the `button` because from the perspective of:
- someone experienced, the button feels large and intrusive and there's no way to get rid of it (whereas just typing I can get rid of the text)
- a beginner, I don't see it since it's at the bottom right and I'm focused on writing code in the top of the file

**Comment by isidorn** [comment]
@meganrogge thanks for providing feedback. We'll take that into account. Though we will probably ship this as hidden and in the future decide based on experiments and user studies
