### ISSUE TITLE
workbench.editor.enablePreview setting not working

### ISSUE THREAD

**Issue by varnk** [microsoft/vscode#117286]
Issue Type: <b>Bug</b>

Somehow I got my VSCode editor into a state where it is ignoring theworkbench.editor.enablePreview setting.  My editor tabs are always opening and staying open when I single-click on a file in the Exploer pane.

Not sure how to reproduce this and not sure how it got into this state.   My workbench.editor.enablePreview is enabled.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (2 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|6.06GB (3.12GB free)|
|Process Argv|--crash-reporter-id e98ffc5f-fa12-4a99-b5c3-44bae2bcdf58|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.1
xml|Dot|2.5.1
plantuml|jeb|2.14.3
vscode-ext-import-export|jos|0.0.9
stack-tabs|kyl|0.0.2
csharp|ms-|1.23.9
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
cpptools|ms-|1.2.1
powershell|ms-|2020.6.0
java|red|0.75.0
vscode-hexdump|sle|1.8.1
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by varnk** [comment]
I think I found the problem.  Looks like it was a plug-in that I installed called "stack-tabs"(https://marketplace.visualstudio.com/items?itemName=kylepaulsen.stack-tabs&ssr=false#qna).  There currently is an open-issue on their GitHub site that pertains to this problem.  See https://github.com/kylepaulsen/vscode-stack-tabs/issues/1
