### ISSUE TITLE
Test: Updated menu behavior for web / desktop

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117275]
Refs: #114200
- [x] macOS @lszomoru
- [x] linux @connor4312
- [ ] windows @devinvalenciano

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117275%0A%0A)

---

This milestone, we have tweaked the menu bar visibility settings in web and desktop. We have updated defaults, renamed the values, and even altered the behavior. There are several settings that impact the behavior of the menu bar.

Please test the following configurations, you can use the test matrices below for tracking.

platform | desktop | web
------------- | ------------ | -------------
**macOS** | not applicable | custom only
**windows** | native/custom | custom only
**linux** | native/custom | custom only

For a given configuration, set the titlebar style as appropriate.

**Relevant Settings (availability dependent on platform):**
Set visibility: `window.menuBarVisibility` (web default is compact, desktop default is classic)

**test on non-macOS only**
Set custom/native menu: `window.titleBarStyle`
Set alt-behavior: `window.customMenuBarAltFocus`
Set mnemonics enablement: `window.enableMenuBarMnemonics`

**Note:** For macOS, the alt-behavior is different. Instead of mnemonics and alt-key to focus the menu, there is a command **Focus Application Menu** bound to **F10** by default

Once in **fullscreen**:

visibility X alt-behavior | alt focus + mnemonics | alt focus + no mnemonics | no alt focus + mnemonics | no alt focus + no mnemonics
------------- | ------------ | ------------- | ------------- | -------------
**classic** | | | | 
**visible** | | | | 
**toggle** | | | | 
**hidden** | | | | 
**compact** | | | | 

Once **not in fullscreen**:

visibility X alt-behavior | alt focus + mnemonics | alt focus + no mnemonics | no alt focus + mnemonics | no alt focus + no mnemonics
------------- | ------------ | ------------- | ------------- | -------------
**classic** | | | | 
**visible** | | | | 
**toggle** | | | | 
**hidden** | | | | 
**compact** | | | | 

Please use the settings and description to learn what the expected behavior is. If it is not clear and you feel it is important to change, please file an issue. If you aren't sure if it is doing the right thing, file an issue, I will clarify and close as necessary.

**Comment by connor4312** [comment]
With menuBarVisibility: hidden, customMenuBarAltFocus seems to have no effect. I would expect the menu to be shown when focus is given to it via `alt`

**Comment by sbatten** [comment]
@connor4312 sounds like you are describing `toggle` behavior. That is the primary difference between `hidden` and `toggle`

**Comment by devinvalenciano** [comment]
One suggestion - is it possible/preferable to disable the 'compact' option is the user has 'native' style applied?

Also, if you have alt focus off and toggle on, should alt focus on the File pulldown (current behavior), or should it only make the menu visible?





Once in **fullscreen**:

visibility X alt-behavior | alt focus + mnemonics | alt focus + no mnemonics | no alt focus + mnemonics | no alt focus + no mnemonics
------------- | ------------ | ------------- | ------------- | -------------
**classic** |x |x |x | x
**visible** |x |x |x | x
**toggle** |x |x |x | x
**hidden** |x |x |x | x
**compact** |x |x |x | x

Once **not in fullscreen**:

visibility X alt-behavior | alt focus + mnemonics | alt focus + no mnemonics | no alt focus + mnemonics | no alt focus + no mnemonics
------------- | ------------ | ------------- | ------------- | -------------
**classic** |x |x |x | x
**visible** |x |x |x | x
**toggle** |x |x |x | x
**hidden** |x |x |x | x
**compact** |x |x |x | x
