### ISSUE TITLE
Test silent authentication `getSession` behavior

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117290]
Refs: https://github.com/microsoft/vscode/issues/111529

- [x] macOS @chrisdias
- [x] linux @jrieken
- [x] windows @fiveisprime

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117290%0A%0A)

---

When an extension is using the`vscode.authentication.getSession` API, it can include a set of options with a `createIfNone` flag, which indicates what the authentication provider should do if there is no session. This flag now additionally controls behavior around when users see any kind of prompt, vs simply seeing a badge get added to the accounts icon on the activity bar.

- When calling `getSession` with `createIfNone` set to true, if there is no session matching those, they should see a sign in prompt as before
- When calling `getSession` with `createIfNone` set to true, if there is a matching session but the extension has not been granted access to it, a modal prompt should show as before
- If options are not set or `createIfNone` is explicitly false, no prompts should be shown. Either a "Sign in" or a "Grant access" menu item should be added to the accounts menu
- The badge on the accounts menu should update if the user does sign in/grant access, and should clear grant access requests if the user signs out

Please try using both the Microsoft and GitHub authentication account providers, since they have different behavior around whether or not you can be signed into multiple accounts.

Example of using MS:
```ts
const session = await vscode.authentication.getSession('microsoft', ["https://management.core.windows.net/.default", "offline_access"], { createIfNone: true })
```
and GitHub, with same scopes as GHPRI:
```ts
const session = await vscode.authentication.getSession('github', ['read:user', 'user:email', 'repo'], { createIfNone: true })
```

**Comment by chrisdias** [comment]
LGTM
