### ISSUE TITLE
Top Menu List disappears before selection can be made

### ISSUE THREAD

**Issue by kae36** [microsoft/vscode#117243]
Issue Type: <b>Bug</b>

I updated VS Code Insiders and updated a couple of extensions. After that, I tried to exit by going to the "FIle" menu and choosing "Exit".  The File menu showed up, but as I moved my mouse to choose Exit, the menu disappeared.  I don't think I could ever get my mouse to move that fast to get to the exit before it disappears. This doesn't happen on all menus.  The disappearing menu only happens on File, Go, Run, Terminal menus.  The Other menus: Edit, Selection, View, Help are fine and don't disappear.

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T05:14:36.498Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (16.08GB free)|
|Process Argv|--crash-reporter-id 226c8bca-24df-4272-a7ea-2f683fd0c4a2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
LinkCheckMD|bla|0.3.1
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.39.0
racket|Dmy|1.2.0
docs-article-templates|doc|0.2.9
docs-authoring-pack|doc|0.1.11
docs-build|doc|0.3.1
docs-images|doc|0.0.9
docs-linting|doc|0.0.5
docs-markdown|doc|0.2.82
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.56
docs-yaml|doc|0.2.6
git-extension-pack|don|0.1.3
githistory|don|0.6.14
gitlens|eam|11.2.1
vscode-pull-request-github|Git|0.23.1
githd|hui|2.2.4
git-graph|mhu|1.28.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
remote-wsl|ms-|0.54.0
vetur|oct|0.32.0
vscode-yaml|red|0.15.0
code-spell-checker|str|1.10.2
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by IllusionMH** [comment]
Workaround you can click on File and move cursor to the side of dropdown (over editor) and not over disabled items.

/confirm

Happens for me when I move cursor from top to bottom over disabled menu item (e.g. Save all, or Forward and Go to... actions).
Works fine if I move cursor thought enabled items or from bottom to top over disabled items.
