### ISSUE TITLE
VSCode 1.53.* starts with disabled extensions on CentoS 7.3

### ISSUE THREAD

**Issue by JackLiar** [microsoft/vscode#117231]
- VS Code Version: 1.53.0, 1.53.2
- OS Version: CentOS 7.3.1611

Steps to Reproduce:

1. Create a complete new CentOS 7.3 virtual machine using VMware
2. Install Visual Studio Code, install any extension(for example [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)) and disable it, close VSCode
3. **Reopen VSCode using command line: `code .`**, all extensions are enabled.

Does this issue occur when all extensions are disabled?: No. Except the language pack extension(installed after the vim test), other extensions are all disabled.

Have run `Help: Start Extension Bisect`, but I think this is a Code problem.

**Comment by JackLiar** [comment]
I haven't test 1.53.1

**Comment by gjsjohnmurray** [comment]
Starting with 1.53 CentOS 7 is no longer a supported platform.

**Comment by JackLiar** [comment]
> Starting with 1.53 CentOS 7 is no longer a supported platform.

Well, this is sad :(

Thx for ur reply, I'll close this one
