### ISSUE TITLE
Test: multiple selections in notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117295]
Refs: https://github.com/microsoft/vscode/issues/114156, https://github.com/microsoft/vscode/pull/117204

- [x] anyOS @RMacfarlane 
- [ ] anyOS @meganrogge

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117295%0A%0A)

---

The notebook editor is built on top of the List Widget, thus it's natural to add multiple selection support to it. It needs careful design with the API and UX as the notebook interactions are somewhat different from the text editor or file explorer so we are adding multiple selection support gradually. Please test with GitHub Issue Notebook and play with following scenarios:

* Arrow keys
* Shift + Click multi selects
* Copy/Paste/Cut works with multi select
    * After Cut/Paste, the selections are correct
    * After Undo/Redo, the selections are correct
 * API. We are moving to the new `NotebookEditor.selections`  but please check if `NotebookEditor.selection` is always correct when you change cell selections in the UI. Code snippet you can use 

```ts
context.subscriptions.push(vscode.window.onDidChangeNotebookEditorSelection(e => {
	console.log(e.notebookEditor.selection);
}))
```

**Comment by sandy081** [comment]
Removed @joaomoreno as he is not available for testing
