### ISSUE TITLE
Run and Debug Error

### ISSUE THREAD

**Issue by Drakemaner** [microsoft/vscode#117249]
When i click in the "Run and Debug",  chrome doesn´t open and shows up a file named "launch,json" and i dont know what to do to fix that

**Comment by Drakemaner** [comment]
![image](https://user-images.githubusercontent.com/79467044/108758391-cbe7b100-7529-11eb-94f3-b284940d0a83.png)
that shows up and i cant run the code

**Comment by connor4312** [comment]
This is a launch configuration. You can find more info about debugging in VS Code here: https://code.visualstudio.com/docs/editor/debugging And you can read more about browser debugging specifically here: https://code.visualstudio.com/docs/nodejs/browser-debugging

Let us know if you have any more issues
