### ISSUE TITLE
TS unbound breakpoin

### ISSUE THREAD

**Issue by yilikun** [microsoft/vscode#117227]
![image](https://user-images.githubusercontent.com/23469392/108704396-eda36100-7546-11eb-9520-e1b2d9197154.png)
![image](https://user-images.githubusercontent.com/23469392/108704409-f2681500-7546-11eb-8e72-eb8fdc4b3b59.png)
[vscode-debugadapter-c2e7456c.json.gz](https://github.com/microsoft/vscode/files/6021696/vscode-debugadapter-c2e7456c.json.gz)

**Comment by weinand** [comment]
@yilikun
- Please note that your extension must be activated and loaded before a breakpoint becomes "bound".
- and make sure that the "outfiles" glob pattern matches all JS files, e.g. use something like `"${workspaceFolder}/webpack_dist/**/*.js"`

**Comment by connor4312** [comment]
You set a breakpoint in

```
d:\Projects\final\cyclone-designer-robot\product\cyclone_starter\main\main.ts
```

However, there were no files with the name "main" loaded by Electron.

As Andre said, your outfiles should generally be a glob as well.

**Comment by yilikun** [comment]
Thanks for replying so fast.
* My extension all activated and loaded.
* I have updated "ortFiles"
![image](https://user-images.githubusercontent.com/23469392/108792812-1d8d4b80-75bd-11eb-93c0-e39b300bf79b.png)
But it doesn't work.

**Comment by connor4312** [comment]
Please share a sample repo. I don't have enough info to find a solution from what's been provided so far.

**Comment by yilikun** [comment]
More infomation:
When I run `./node_modules/.bin/electron ./webpack_dist/product/cyclone_starter/main.bundle.js --inspect`,
then 
![image](https://user-images.githubusercontent.com/23469392/108796923-e3c04300-75c4-11eb-8093-6920becdb812.png)
![image](https://user-images.githubusercontent.com/23469392/108796935-e7ec6080-75c4-11eb-94fd-01fdc1316183.png)
It works.

**Comment by connor4312** [comment]
You can try just removing the outFiles. That will cause the entire workspace to be scanned which may be sufficient to pick up on your sourcemaps.

**Comment by yilikun** [comment]
sorry,you mean delete `outFiles` item in `launch.json`?
And my main.bundle.js is large, this file has 485143 lines.
![image](https://user-images.githubusercontent.com/23469392/108798670-52070480-75c9-11eb-9628-84146ec44701.png)

**Comment by connor4312** [comment]
Yes, delete the `outFiles`

**Comment by yilikun** [comment]
I have deleted `outFiles`, debugger launch slowly, breakpoint is also unbound...
More infomation:
![image](https://user-images.githubusercontent.com/23469392/108799499-6ea43c00-75cb-11eb-8676-10539a3f0bb7.png)

**Comment by connor4312** [comment]
It doesn't look like it's running any of your code. I notice that you're passing arguments when you run it from the CLI https://github.com/microsoft/vscode/issues/117227#issuecomment-783840130 but you don't inside your launch.json. You may want to provide these are `runtimeArgs`.

**Comment by yilikun** [comment]
`--inspect` is a electron command. I think it will launch a debugger.
But if I use vscode launch, maybe I can not use this command?
I still add this property
![image](https://user-images.githubusercontent.com/23469392/108806805-b0d67900-75dd-11eb-8777-5428f74546fb.png)
Then
![image](https://user-images.githubusercontent.com/23469392/108806821-bd5ad180-75dd-11eb-9ee9-769b4212039f.png)
### I'm going to cry...

**Comment by connor4312** [comment]
Okay, thanks. I'm not able to see what's going on from the info here. Are you able to push your project up to a Github repository (either public or private) or create a small sample of what you're facing so I can look into it? I can also screenshare with you.

**Comment by yilikun** [comment]
> Okay, thanks. I'm not able to see what's going on from the info here. Are you able to push your project up to a Github repository (either public or private) or create a small sample of what you're facing so I can look into it? I can also screenshare with you.

Thanks for your reply. I was a bit busy some time ago.I have created a small [sample](https://github.com/yilikun/electron-typescript-webpack-vscodedebug), but I can set the breakpoint smoothly...
So i think it might be because the real project file is too large?
As follow:
> sorry,you mean delete `outFiles` item in `launch.json`?
> And my main.bundle.js is large, this file has 485143 lines.
> ![image](https://user-images.githubusercontent.com/23469392/108798670-52070480-75c9-11eb-9628-84146ec44701.png)

**Comment by yilikun** [comment]
New discovery!!
When I upgrade electron version from 3 to 9, I can set the breakpoint!!
![image](https://user-images.githubusercontent.com/23469392/111758593-a73bea80-88d7-11eb-9188-c7391e21a8ae.png)
SO, maybe it is a electron bug.........

**Comment by yilikun** [comment]
![image](https://user-images.githubusercontent.com/23469392/111759483-9b9cf380-88d8-11eb-94f4-20ecac3b5bfd.png)
but when my mouse hover the variable, its value is not show............
