### ISSUE TITLE
Visual Studio Code General Failure

### ISSUE THREAD

**Issue by juliolugo96** [microsoft/vscode#117267]
Issue Type: <b>Performance Issue</b>

# Problem description

After my last update, I'm not able to drag my VSCode window because it just gets stuck. Also, I can't work with two VSCode windows opened as I used to do before. I tried disabling all my extensions, but my problem persists. Can you help me?

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.8.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 1769)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|7.65GB (0.12GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   125	 24522	code main
    0	    39	 24526	   zygote
    0	    78	 24577	     gpu-process
    0	    39	 24527	   zygote
    0	    78	 25059	     window (Issue Reporter)
    0	    55	 24587	   utility
    0	   204	 24604	   window (ignis-gravitas-landing - Visual Studio Code)
    0	   102	 24950	     extensionHost
    0	    63	 24952	     watcherService
    0	   110	 24932	   shared-process
    0	     0	 25076	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 25077	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (ignis-gravitas-landing - Visual Studio Code)
|    Folder (ignis-gravitas-landing): 65 files
|      File types: svg(26) html(11) js(7) png(4) css(3) md(1) eot(1) ttf(1)
|                  woff(1) woff2(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
\Duplicate https://github.com/microsoft/vscode/issues/115804

Can you try starting with `code --disable-gpu`
