### ISSUE TITLE
Split terminals should be remembered between sessions

### ISSUE THREAD

**Issue by Wintaru** [microsoft/vscode#117242]
If you split your terminals when you first start VS Code, then hit F5 to start debugging, your terminals are all blown away by the debugging run. Only after you have ran debugging once does it respect the terminals you created. Also, why can we not remember terminals between reloads of the editor? Every new plugin update and I have to set up my terminals again.

**Comment by Tyriar** [comment]
Can you elaborate a little on the terminals going away you're seeing? Do you mean debugging creates a new terminal and backgrounds the others (still accessible in the dropdown)? A [gif](https://gifcap.dev/) would be helpful. 

> Also, why can we not remember terminals between reloads of the editor?

Literally just pushed https://github.com/microsoft/vscode/pull/116449 🙂

**Comment by Wintaru** [comment]
Awesome on the push! 

I'm trying to make a gif, all I have is vokoscreen on this machine and it makes HUGE gifs. Trying to shrink it down now.

**Comment by Wintaru** [comment]
Let's see if an MP4 works...

https://user-images.githubusercontent.com/1441142/108732867-8f995e00-74f3-11eb-8a25-e6d4849cb1d1.mp4

**Comment by Wintaru** [comment]
@Tyriar Does this help?

**Comment by Wintaru** [comment]
It still happens.

**Comment by Tyriar** [comment]
Two things here:

- Restarting doesn't work for tasks right now, that's tracked in https://github.com/microsoft/vscode/issues/117408
- I don't think tasks let you integrate with regular terminal layouts, unless they're already marked with an open `group` in tasks ([example](https://github.com/xtermjs/xterm.js/blob/873dd76167b3c78cfa223633ba03df016d912445/.vscode/tasks.json#L23-L25)), AFAIK we're not planning changing this. But coming up you will be able to easily rearrange terminals using the new tabs feature that you can enable with `terminal.integrated.tabs.enabled`. Drop and drop is coming soon to insiders https://github.com/microsoft/vscode/issues/121500
