### ISSUE TITLE
Can't start extension host process from duplicate workspace windows

### ISSUE THREAD

**Issue by Tpuljak** [microsoft/vscode#117269]
- VS Code Version: 1.53.2
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open a workspace containing an extension in development (Let's call it `workspace  A`).
2. Duplicate the workspace (Command Palette -> Workspaces: Duplicate as Workspace in New Window) (call this `workspace B`)
3. Run the extension from `workspace A`. This opens a new VSCode window that runs the Extension and `workspace A` is debugging it.
4. Run the extension from `workspace B`. This uses the same VSCode window that `workspace A` used and shuts down the `workspace A` debug process. **(Previously `workspace B` would open its own new VSCode instance so the processes would run in parallel in `workspace A` and `workspace B`)**

Does this issue occur when all extensions are disabled?: Yes

I've been developing an extension for the last couple of months and it was very important for me to be able to run parallel extension host processes so they can communicate with each other.

I took a break from developing it since Jan 19th 2021 and returned to it today and discovered this issue. (In the meantime VSCode updated to version 1.53.2 so I presume the issue came with the changes applied with that version)

**Comment by Tpuljak** [comment]
I can confirm that the issue is not present in VSCode v1.52.

**Comment by bpasero** [comment]
Hm, this is not electron related, is it?

**Comment by deepak1556** [comment]
Does this issue repro with latest stable `1.74` ?
