### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by chris-warner** [microsoft/vscode#117238]
Issue Type: <b>Bug</b>

Opened visual studio, set language to Javascript React

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|89, 28, 13|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 0c1063c7-46e5-48c7-93f2-bb30ae0e8daa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
vue|jcb|0.1.5
vscode-mjml|mjm|1.0.4
vscode-azureappservice|ms-|0.20.0
azure-account|ms-|0.9.6
cordova-tools|msj|2.2.0
vscode-react-native|msj|1.4.0
vetur|oct|0.32.0
LiveServer|rit|5.6.1
WebTemplateStudio-dev-nightly|WAS|0.5.2104801

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What does "Failed to load" exactly mean?

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
