### ISSUE TITLE
Mac OSX Command E searches files, not open them

### ISSUE THREAD

**Issue by genzoman** [Microsoft/vscode#11720]
- VSCode Version: 1.5.0
- OS Version: OSX

Steps to Reproduce:

1. Commend e
2. Brings up the find in file bar instead of searching through files

I can no longer quickly open a file in VS Code, command e brings up the find in file menu.

**Comment by timdang** [comment]
It's in the [release notes](https://code.visualstudio.com/Updates):

Mac OS: Cmd+E no longer opens Quick Open
We decided to remove an (undocumented) key binding to bring up quick open for file search. You can bring back Cmd+E with the following key binding configuration:

{ "key": "cmd+e", "command": "workbench.action.quickOpen" }
The reason behind this change is that Cmd+E on Mac OS is typically associated with running a search in the current active file.

**Comment by genzoman** [comment]
@timdang what is the preferred way to open files now?

**Comment by timdang** [comment]
Command + P still works, right?

**Comment by genzoman** [comment]
@timdang yep, i never used that one. thanks.
