### ISSUE TITLE
Terminal: move workbench dependencies into electron-sandbox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117257]
Now that the terminals are managed from the shared process it would be great if this dependency here:

https://github.com/microsoft/vscode/blob/79a623d9767bb8bf428c9c577b6a230decf7f868/src/vs/workbench/workbench.desktop.main.ts#L133-L134

Could fully move into `electron-sandbox` (into `src/vs/workbench/workbench.sandbox.main.ts`) so that we can even test it from running `scripts/code.sh --__sandbox`

**Comment by bpasero** [comment]
It looks like we have a terminal contribution already in sandbox:

https://github.com/microsoft/vscode/blob/a9536c368c3176dc42df1ea2721daae792fca5cf/src/vs/workbench/workbench.sandbox.main.ts#L117-L117

But I guess those are just a few pieces of it.

**Comment by Tyriar** [comment]
Had this in mind for March already, closing https://github.com/microsoft/vscode/issues/116463 off in favor of this.

**Comment by bpasero** [comment]
Slightly related, we seem to still have a native module dependency `windows-process-tree` in renderer that then also should move.

**Comment by bpasero** [comment]
@Tyriar just noticed this one too:

https://github.com/microsoft/vscode/blob/c41922bf4270bcc075850ead9148b64cd29b61fc/src/vs/workbench/workbench.desktop.main.ts#L136-L136

Is that a separate issue to look at?

**Comment by Tyriar** [comment]
Yes let's track that separately

**Comment by bpasero** [comment]
👏
