### ISSUE TITLE
Editor getting freeze when resize

### ISSUE THREAD

**Issue by MuthuPandiS** [microsoft/vscode#117200]
Hi Team,

When I open the more than one VS code editor, If I resize(maximize or manually adjust width/height), the editor getting freezed. Not able to do any action.

If I open only one project, resize wont causing any issue.

Version: Version: 1.53.2

Steps:
1. Open more than one project in the VS code.
2. Recently open project comes as small window.
3. Click any resize button in top left cornor or manually resize the editor

Result:
Editor window getting freezed. Need to close both window and reopen it. 

Expected output:
Editor should resize, allow to edit the files.

**Comment by bpasero** [comment]
Would you be able to attach a screen recording of how this looks?

**Comment by sempasha** [comment]
https://user-images.githubusercontent.com/1610465/109307457-80534100-7862-11eb-8e85-c30eae39bee5.mov

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by sempasha** [comment]
With gpu acceleration disabled issue also reproduces.

**Comment by deepak1556** [comment]
Do you see the issue with latest insiders https://code.visualstudio.com/insiders ?

**Comment by sempasha** [comment]
Yes, it also reproduces with 1.54.0-insider.

Elementary OS 5.1.7 Hera, built on Ubuntu 18.04.4 LTS, linux 5.4.0-65-generic, GTK 3.22.30.

**Comment by sempasha** [comment]
Also I found application menu strange behavior, not sure it is related with described issue, but who knows.

https://user-images.githubusercontent.com/1610465/109457205-38a80180-7a7c-11eb-9016-c37fa75a5186.mov

**Comment by deepak1556** [comment]
Are you using x11 or wayland session ?

**Comment by sempasha** [comment]
@deepak1556, x11

**Comment by deepak1556** [comment]
Does the freeze happen when you switch to custom titlebar `"window.titleBarStyle": "custom"` and start the app with `--disable-gpu`

**Comment by deepak1556** [comment]
If it does, can you follow these steps to get the core dump

* Restart code
* Open process explorer from Help and check PID of the process with name of the open editor
* Perform resize to create the frozen state
* In the terminal run gcore -o <some-path> <PID-from-step-2>
* Send the dump to Deepak.Mohan@microsoft.com

**Comment by sempasha** [comment]
As I remember, disabling gpu acceleration and extensions was the first thing I tried to resolve an issue and that didn't work.

Now, disabling GPU acceleration completely resolves the issue, even without changing window title. Menu items work as normal, editor interface does not freeze while resizing in both common VS Code and VS Code Insiders edition.

@deepak1556, as I understand in that case you do not need core dump, right?

**Comment by deepak1556** [comment]
Thanks, yeah dump is not required but if possible I would like to see one to further understand the issue.

Merging to https://github.com/microsoft/vscode/issues/115868
