### ISSUE TITLE
Collapsing markdown notebook cell creates height issues

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117262]
https://user-images.githubusercontent.com/35271042/108743232-6fff3700-74ed-11eb-82e0-19c7f5a78fcd.mov

This is from the `vscode` repo, which I believe is using the new notebook markdown renderer.

Version: 1.54.0-insider
Commit: 11cd76005bc7516dcc726d7389d0bce1744e5c85
Date: 2021-02-22T06:44:36.656Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by mjbvz** [comment]
With the existing markdown support, when a markdown cell is folded, it seems that the cell remains visible but all of its children are hidden. Is that the expected behavior?

**Comment by mjbvz** [comment]
Ok, I think the new behavior better matches the existing markdown renderer's behavior. Please give it another test in the next insiders and let me know if something still seems off
