### ISSUE TITLE
Hangs on editing typescript

### ISSUE THREAD

**Issue by qutorial** [microsoft/vscode#117232]
Issue Type: <b>Bug</b>

Start editing typescript, write an "import * from" and then press back space a couple of times -> Freeze

VS Code version: VSCodium 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-12T00:32:13.710Z)
OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (2 x 1392)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|11, 5, 3|
|Memory (System)|1.94GB (0.29GB free)|
|Process Argv|code --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|tty|
</details>Extensions: none

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by mjbvz** [comment]
You can also try following [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information when the freeze happens. If you can share t output of `code-insiders --status`, that should help us track down what is freezing
