### ISSUE TITLE
Test: Emmet extensions path now supports multiple paths

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117277]
Refs: #116741

- [x] macOS @mjbvz
- [x] linux @JacksonKearl 
- [x] windows @tanhakabir (preferably with WSL)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117277%0A%0A)

---

The `emmet.extensionsPath` setting points to ~~an Emmet snippets file, or~~ a directory containing an Emmet snippets file. An example of such a snippets file is at https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets.

The `emmet.extensionsPath` variable can now take in an array! Thanks to @lancewl for implementing these changes as part of HackIllinois https://fellowship.hackillinois.org/. Some things to verify:

- If an array is passed, the first valid entry (valid meaning it's ~~an existing json file, or~~ a directory containing a snippets.json file) will be chosen. If none of the entries are valid, an error notification should show up.
- If a string is passed, and it is valid, it will be chosen. If this string is not valid, an error notification should show up.
- If null is passed, the custom snippets are reset and should not show up anymore.
- If there is a valid entry, but the snippets file corresponding to that entry is invalid, then a parse error notification shows up.

Bonus points if by using settings sync, you can set up the `emmet.extensionsPath` variable as a two-element array where one entry is only valid on your local setup, and the other entry is only valid on a remote setup (e.g. through Codespaces or Dev Containers).

**Comment by rzhao271** [comment]
Changed the description a bit because I forgot once again that the extensions path has to be to a folder (not directly to snippets.json)

**Comment by mjbvz** [comment]
I couldn't get errors to be reported on macOS: #117511

All the other issues I opened are polish items, so not essential to address this milestone
