### ISSUE TITLE
Test Inline Values Provider API

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#117288]
Refs: #105690

- [x] anyOS: @isidorn
- [x] anyOS @rzhao271

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117288%0A%0A)

---

**Make sure to use the latest version of VS Code (bd74308b5abbbb2f5a5df0f0d8a3bef606652d36, Date: 2021-02-23T05:14:25.355Z)**

Today the "Show Inline Values" feature of VS Code's debugger is based on a generic implementation in the VS Code core and provides neither customisability through settings, nor extensibility via extensions.

As a consequence, it is not a perfect fit for all languages (e.g. #101797) and sometimes even shows incorrect values because it doesn't understand the underlying language.

In this milestone we are [proposing an extension API](https://github.com/microsoft/vscode/blob/1cc57241cfea56198597cb74f91923fcc180cbed/src/vs/vscode.proposed.d.ts#L747-L889) that either replaces the built-in implementation completely or allows to replace parts of the implementation with custom code.

Inline Values Provider API in a nutshell:
- the `InlineValuesProvider.provideInlineValues` must be implemented by:
  - locating in the given document all language elements for which inline values should be provided
  - the `stoppedLocation` property of the passed `InlineValueContext` can be used to find the maximum line for which values need to be provided.
  - the `viewPort` passed into `InlineValuesProvider.provideInlineValues` can be used to limit the returned inline values to visible lines (but see note below).
  - three different types of inline values can be returned:
    - `InlineValueText`: the complete text to be shown at the end of the line,
    - `InlineValueVariableLookup`: the name of a variable that VS Code will try to lookup in the VARIABLES view,
    - `InlineValueEvaluatableExpression`: the name of an expression that VS Code will send to the debug adapter for evaluation.
- the `InlineValuesProvider` is registered for a language, not for a debugger (because source language and underlying debugger are independent). 

Test setup:

In order to simplify testing, an Inline Value Provider has been [added to Mock Debug](https://github.com/microsoft/vscode-mock-debug/blob/ef90572bd9427f195db4008d7843aecea061e36e/src/activateMockDebug.ts#L106-L132).

- Git clone the project and press F5 to run Mock Debug. 
- in the new VS Code instance press F5 to run the Mock debugger
- single step over the lines of the "Inlines Value Provider" section
- observe the shown inline values

Testing:

- Modify the Inline Values Provider and exercise the different InlineValue types.
- for `InlineValueVariableLookup` and `InlineValueEvaluatableExpression` omit the `variableName` and `expression` arguments and verify that they still work.
- test the `caseSensitiveLookup` argument.
- verify that VS Code sorts values based on their returned range's start column
- register a second provider and verify that inline values are properly merged and sorted.

Please note:
- `InlineValuesProvider.onDidChangeInlineValues` is not yet implemented.
- on scrolling the text editor, the inline value provider is not yet called again with a shifted `viewPort`.

**Comment by sandy081** [comment]
Removed  @TylerLeonhardt as he is not available for testing

**Comment by isidorn** [comment]
Overall this works great. Would be nice to get some feedback from @TylerLeonhardt once he is back from vacation and from @ahlinc

Also if two inline value providers are registered and they provide the variable with the same name -> it is displayed twice.
Also if they provide two value with different columns they end up not respecting the column but this issue already captures that https://github.com/microsoft/vscode/issues/117375
@weinand let me know if variables should be de-duplicated between different inline value providers and in that case I can file an issue. Thanks

**Comment by weinand** [comment]
@isidorn yes please, file an issue about the de-duping. My assumption was that this is left to the provider, but if there are multiple independent providers, then the de-duping needs to take place in VS Code.

**Comment by isidorn** [comment]
@weinand makes sense, I have filed this one https://github.com/microsoft/vscode/issues/117419

**Comment by TylerLeonhardt** [comment]
I've left this issue in my notifications. If I have time this week between DevDiv bootcamp sessions, I'll take a look.

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/109369641-ed120f80-7851-11eb-844c-da2ac8cef7be.png)

I created a separate extension to try this out with the PowerShell debugger. LGTM!

Code:
```ts
        context.subscriptions.push(vscode.languages.registerInlineValuesProvider('powershell', {

		provideInlineValues(document: vscode.TextDocument, viewport: vscode.Range, context: vscode.InlineValueContext) : vscode.ProviderResult<vscode.InlineValue[]> {
			const allValues: vscode.InlineValue[] = [];

			for (let l = 0; l <= context.stoppedLocation.end.line; l++) {
				const line = document.lineAt(l);

				// Skip over comments
				if (line.text.trimStart().startsWith('#')) {
					continue;
				}

				const variableMatches = /(?:\${(.*)})|(?:\$\S+:\S+)|(?:\$\S+)/gi;
				for (let match = variableMatches.exec(line.text); match; match = variableMatches.exec(line.text)) {
					// If we're looking at an "anything goes" variable, that has a capture group so use that instead
					let varName = match[0][1] === '{'
						? '$' + match[1]
						: match[0];

					// If there's a scope, we need to remove it
					const colon = varName.indexOf(':');
					if (colon !== -1) {
						varName = '$' + varName.substring(colon + 1);
					}

					// These characters need to be trimmed off
					if ([';', ',', '-', '+', '/', '*'].includes(varName[varName.length - 1])) {
						varName = varName.substring(0, varName.length - 1);
					}

					const rng = new vscode.Range(l, match.index, l, match.index + varName.length);
					allValues.push(new vscode.InlineValueVariableLookup(rng, varName, false));
				}
			}

			allValues.push(new vscode.InlineValueText(new vscode.Range(0,0,0,0), 'Hello Andre!'));

			return allValues;
		}
	}));
```

**Comment by weinand** [comment]
@TylerLeonhardt thanks a lot for sharing this example.

Does your provider actually improve the functionality of the PowerShell extension by fixing/supporting something that the built-in "inline values" feature doesn't do?

**Comment by TylerLeonhardt** [comment]
@weinand built-in "inline values" isn't currently supported in the PowerShell extension. I tried debugging without my extension and no inline values showed up (with `"debug.inlineValues": true,` set). How would it support them?

Also wanted to call out that PowerShell variables are case-insensitive.

**Comment by weinand** [comment]
@TylerLeonhardt if after setting `debug.inlineValues` to true no "inline values" show up for PowerShell, then this is an indication that VS Code's built-in "one-size-fits-all" approach for inline values doesn't work for PowerShell ;-)

The built-in approach works by breaking a source line into variables via a regular expression and then trying to find the variables in the VARIABLES view's model. If nothing is found by that approach you won't see any inline values.

I suspect that the hard-coded regular expression doesn't work for PowerShell.

But this means that your example could easily add inline value support for PowerShell. 

BTW, you are already using "case-insensitive" variable lookup by passing "false" to the "InlineValueVariableLookup" constructor.

**Comment by TylerLeonhardt** [comment]
> I suspect that the hard-coded regular expression doesn't work for PowerShell.

Where is this hard-coded regex? I wonder if it's because PowerShell variables start with `$`? Ideally if a small change could be made to the regex to support `$` variables, that'd also help out other languages like PHP too.

> BTW, you are already using "case-insensitive" variable lookup by passing "false" to the "InlineValueVariableLookup" constructor.

Yep. Just wanted to call that out in case it was important for the built-in one. Doesn't sound like our problem.

> The built-in approach works by breaking a source line into variables via a regular expression and then trying to find the variables in the VARIABLES view's model. If nothing is found by that approach you won't see any inline values.

Ultimately this won't work for _all_ of PowerShell's variables as I don't expect the built-in to support the "anything goes" PowerShell variable syntax like `${ any characters even spaces are valid in between braces }` (for example, `${     }` has a variable name of 5 spaces 🤯 (which renders a bit funny as you can see in line 7 of my screenshot above).

**Comment by weinand** [comment]
@TylerLeonhardt the hard-coded regex lives here: https://github.com/microsoft/vscode/blob/6c6caf678fe021609f9ec26d9caba8124649bc91/src/vs/editor/common/model/wordHelper.ts#L10-L27

But we do not want to change this in order to accommodate more languages. That's exactly the reason why we are opening up the built-in inline values functionality with "InlineValuesProvider" extension API.
With this you are able to use a better regular expression, or even your scanner/parser or AST.

**Comment by TylerLeonhardt** [comment]
@weinand yeah I think that makes sense.

> or even your scanner/parser or AST to find all the language elements for which inline values can be shown.

Yeah this is ideal. However, since there's no parser in TS for every language, then another process must be used. If a language already has a language server/debug adapter in the language that can parse the language you are lighting this up for, then ideally that should be reused. Is there plans to make Inline Values supported in DAP/LSP?

**Comment by weinand** [comment]
@TylerLeonhardt
- since "Inline Values" support depends on the **language**, it is independent from debuggers and there is no reason to add this to the DAP.
- since LSP is an implementation detail of a language extension, VS Code knows nothing about it. So there is no need to add this to LSP.

**Comment by TylerLeonhardt** [comment]
> What do you mean by "TS" in your statement

TypeScript... like since there isn't a javascript library to parse any language.

> the language extension might already have an LSP as an implementation detail so it can leverage the AST for the "InlineValuesProvider" API

Just out of curiosity, how would you do this? Would you create a custom message that you send to the language server that asks for the AST?

**Comment by weinand** [comment]
yes, neither VS Code nor an extension have a standardised way to access a parser or AST of the underlying language. That's the reason why functionality like "Inline Values" or "Debug Hover"  is pretty dumb in its "built-in" (generic) form and the proposed extension API cannot make use of a parser or AST API.

If a language extension already uses LSP, then a LSP protocol extension makes sense. But even with that it is difficult to come up with a "standard" way of doing this.

There are basically two scenarios:
- the language extension uses LSP but is completely independent from debugging, so it does not implement a corresponding debug adapter:
in this case the implementation of an `InlineValuesProvider` can only find the "value" of a variable by directly accessing the debug session via VS Code's extension API (or via DAP). To simplify this approach the API proposal offers the `InlineValueVariableLookup` and  `InlineValueEvaluatableExpression` classes which rely on generic DAP mechanisms to find the value in the context of the underlying debug session. The limitation of this approach is...
- the language extension uses LSP and DAP, so it implements both protocols at the same time. In this case the implementation of an `InlineValuesProvider` has access to an AST and the runtime at the same time so it might be able to use a "shortcut" to access the value for a variable located in the AST.
