### ISSUE TITLE
Downgrades after restart

### ISSUE THREAD

**Issue by Yuvix25** [microsoft/vscode#117212]
Issue Type: <b>Bug</b>

I have installed VS Code 1.53.2, but after every time that I open VS Code, it downgrades to 1.43.2, and then I have to click check for updates and update it back to 1.53.2, but then if I close it and open it again, it dowgrades again to 1.43.2.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
python-manifest-template|ben|1.0.1
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
vscode-command-runner|edo|0.0.116
ev3dev-browser|ev3|1.2.0
code-runner|for|0.11.2
go|gol|0.22.1
ev3-micropython|leg|2.0.0
restructuredtext|lex|144.0.0
vscode-antlr4|mik|2.2.4
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
vsliveshare|ms-|1.0.3784
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.5.0
JavaScriptSnippets|xab|1.8.0
masm-tasm|xsr|0.8.3
pytov-run|Yuv|0.0.7
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by gjsjohnmurray** [comment]
Does the downgrade also happen if you start VS Code from a command prompt like this?

```
code --disable-extensions
```

**Comment by Yuvix25** [comment]
Yes

**Comment by joaomoreno** [comment]
@Yuvix25 Can you show me the contents of the `Help > About` dialog?

**Comment by Yuvix25** [comment]
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?

**Comment by Yuvix25** [comment]
I have done that at least 20 times by now, let me know if you still want me to un and re install.

**Comment by joaomoreno** [comment]
Yeah let's try it once more.

**Comment by Yuvix25** [comment]
Ok I have uninstalled, before I reinstall do you want me to do anything?

**Comment by joaomoreno** [comment]
Good question. Can you do a file search for Code.exe, just in case you have another installation hanging around?

**Comment by Yuvix25** [comment]
There is no file named Code.exe on my computer, and when I do search it there are no files related to VS Code.

**Comment by Yuvix25** [comment]
Anything else or just reinstall?

**Comment by Yuvix25** [comment]
After a thorough search, I have found that I do have another VS Code installation, but thanks for your help!
