### ISSUE TITLE
Test various Ports view polish

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#117250]
Refs: https://github.com/microsoft/vscode/issues/116058 https://github.com/microsoft/vscode/issues/99997 https://github.com/microsoft/vscode-internalbacklog/issues/1757

- [x] macOS @sandy081
- [x] linux @bpasero
- [x] windows @meganrogge

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117250%0A%0A)

---

This test is mostly about testing the new table widget use in the Ports view.
1. Connect to your favorite remote where you can run some applications that listen on ports. (Cannot be WSL. SSH, Containers, and Codespaces are all good remotes to test with)
2. Open the Ports view and verify:
- that the table widget makes sense. Can you tell what each of the cells are? Are the actions associated with various cells appropriate? Can you still do everything you used to be able to do with the Ports view?
- that you can resize table columns, and your resizes are preserved across reloads.
- that all of the hovers/tooltips in the table make sense.
- that the table widget is accessible.
- that the actions with an input box ("Set Label" and "Change Local Port") work well.
- that each forwarded port has an icon that indicates whether there is a running process associated with that port.
- that there is an inline action to copy the local address of the port.

**Comment by sandy081** [comment]
@alexr00 Regarding following item

> that the table widget is accessible.

I do not think I can validate this correctly as I do not know what is expected here. I can check for keyboard accessibility but I think that is not enough. I would ask @isidorn our accessibility expert for help here.

**Comment by alexr00** [comment]
@sandy081 for testing accessibility I would test two things:
- Keyboard accessibility, as you suggested
- Install NVDA and test that the narration makes sense.

**Comment by isidorn** [comment]
I can test this out, but I already talked to @joaomoreno and he told me that for accessibility it is not yet 100% ready. 
So I suggested he gives me a ping when he would like me to try it out. So I guess this will happen next milestone.
