### ISSUE TITLE
Breakpoints not mapping correct between TS and JS files despite absolute or relative sourceMaps 

### ISSUE THREAD

**Issue by EliSchleifer** [microsoft/vscode#117211]
- VS Code Version: VS Code Insider 1.5.4
- OS Version: Ubuntu 20.10 remote, OSX as local host

Steps to Reproduce:

1. Using bazel to build extension in typescript.
2. I have noted that I have correctly compiled my JS files which end up placed in a symlink path. Next to the js files is the .map files. which If I open will correctly open a symlinked ts file. 
3. I have tried placing breakpoints in the symlinked ts file that lives at a location like

extension.js
/home/eli/.cache/bazel/_bazel_eli/6ab7f98a34b740eb8432b3beaaef9fee/execroot/trunk/bazel-out/k8-fastbuild/bin/trunk/vscode/extension.js
extension.js.map
{"version":3,"file":"extension.js","sourceRoot":"","sources":["../../../../../trunk/vscode/extension.ts"],....}

4. I have also tried with sourceMaps where I have set the sourceRoot in tsconfig to be an absolute path to avoid all the potential hiccups with a symlink
{"version":3,"file":"extension.js","sourceRoot":"/home/eli/GitHub/trunk/","sources":["trunk/vscode/extension.ts"],"....}

5. The basic hello world built with tsc directly with output directories directly below the source works without a problem. I can also attach debugger with debugger statement. I just want to be able to debug with the ts source code.

6 Launch .json looksl like this:
    {
      "name": "VS Code Extension Run",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
            "--extensionDevelopmentPath=${workspaceFolder}/trunk/vscode",
      ],
      "sourceMaps": true,
      "outFiles": [
        "${workspaceFolder}/bazel-bin/trunk/vscode/**/*.js"
      ],
      "trace": true
    }

7. Package.json looks like this:
....
  "main": "../../bazel-bin/trunk/vscode/extension.js",
  "contributes": {
    "commands": [
      {
        "command": "trunk.helloWorld",
        "title": "Hello World"
      },
      {
        "command": "trunk.goodbye",
        "title": "Goodbye"
      }
    ]
  }, 

I've attached trace log
[vscode-debugadapter-a94b88df.json.gz](https://github.com/microsoft/vscode/files/6020260/vscode-debugadapter-a94b88df.json.gz)

Yes. I disabled all installed extensions except the remote extension needed for SSH

**Comment by connor4312** [comment]
Since linked paths are resolved, I recommend setting your `outFiles` to point to the compiled bazel location on disk, and then also setting the `sourceRoot` in your tsc or tsconfig to point to the absolute path to your workspace location.

Better automatic handling may come with https://github.com/microsoft/vscode-js-debug/issues/776

**Comment by EliSchleifer** [comment]
@connor4312 - I have already attempted both of those changes
my outFiles are set to:
"${workspaceFolder}/bazel-bin/trunk/vscode/**/*.js" - bazel-bin is is symlink to the bazel cache out directory. All the js is compiled under trunk/vscode and should be globbed correctly

My sourceRoot was set to the absolute path "/home/eli/GitHub/trunk"

Any other debugging info I can provide to narrow down. I am happy to tweak our settings, just can't get anything that works.

**Comment by connor4312** [comment]
> "${workspaceFolder}/bazel-bin/trunk/vscode/**/*.js" - bazel-bin is is symlink to the bazel cache out directory.

The problem is that Node will automatically resolve these symlinks, so the URL for scripts that gets reported from the runtime is, in the case of the log,

```
file:///home/eli/.cache/bazel/_bazel_eli/6ab7f98a34b740eb8432b3beaaef9fee/execroot/trunk/bazel-out/k8-fastbuild/bin/trunk/vscode/extension.js
```

...instead of the path in your working directory. The debugger doesn't know these paths are equivalent--that's part of what the linked issue covers. But I think it would work if you (can know and pass) `file:///home/eli/.cache/bazel/_bazel_eli/6ab7f98a34b740eb8432b3beaaef9fee/execroot/trunk/bazel-out/k8-fastbuild/bin/**/*.js` in your outfiles, instead of what you do today.

**Comment by EliSchleifer** [comment]
Still no dice. Tried through several incarnations of that outFiles to the actual path. Still no luck.

I am happy to wait for the eventual fix here. Or I might try some resolution step to just land everything in actual paths for this use case.

If you need anyone to test a potential fix let me know. Also happy to post a sample repo with the problem although it sounds like you are well versed on the issue.

-Eli
________________________________

**Comment by connor4312** [comment]
If it's easy for you to do, a sample repo wouldn't hurt so I can make sure your use case is handled.
