### ISSUE TITLE
Test: Authentication provider registration API

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117299]
Refs: https://github.com/microsoft/vscode/issues/88309

- [x] macOS @roblourens
- [x] linux @aeschli
- [x] windows @rebornix
Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117299%0A%0A)

---

The milestone the `registerAuthenticationProvider` API and associated interfaces have been finalized.

Please read through the docs in `vscode.d.ts` and verify the descriptions make sense. Then, try to implement and register an `AuthenticationProvider`. If you're feeling extremely ambitious you could try to actually perform auth against a service, perhaps looking at the [GitHub auth provider](https://github.com/microsoft/vscode/blob/main/extensions/github-authentication/src/extension.ts) as an example. You could also simply create fake session data. The API should allow:

- other extensions to use the provider to get sessions using `vscode.authentication.getSession`
- other extensions to be able to create a new session with `getSessions` and the `createIfNone` flag
- account information to be listed under the accounts menu for sessions returned by the extension

**Comment by rebornix** [comment]
I successfully built an authentication provider for home assistant, it took me a while to understand how the API should be used but at the end it works pretty. Good work 🎉 .

While building the authentication provider (even after building one successfully), I'm confused how and when to specify which home assistant instance should users authenticate against. It seems the only solution is the authentication provider provide a quick pick to users to let them to choose the endpoint to use, and also embed the endpoint/instance info in `AuthenticationSession.id` and `AuthenticationSessionAccountInformation.label` , there isn't any other place for me to store the endpoint in the authentication session and share with third parties. It seems the work is left to extension authors. With this being said, the rest of the API are straightforward.
