### ISSUE TITLE
Test: Editor title overflow and run-submenu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117259]
Refs: https://github.com/microsoft/vscode/issues/115198, https://github.com/microsoft/vscode/issues/114123

- [x] macOS @misolori 
- [x] anyOS @devinvalenciano
- [x] Windows @joaomoreno

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117259%0A%0A)

---

Use `yo code` to generate an extension and use the `menus` contribution to add commands to the editor title. (see dummy snippet below) Test that:

* `editor/title` has an overflow behaviour. This means when in grand-total more than 9 items are contributed to the `navigation` group than additional commands move into the `...`-sub menu. Make sure this works, preserves the order, and that you cannot break it
* there is a new menu `editor/title/run` which is a submenu living in the editor title. Test that:
  * you can contribute commands into that sub menu
  * the sub menu is dynamic, e.g when it has a single entry the sub menu replaces itself with that entry and vice versa when having multiple entries

```json

"editor/title": [
    {
	"command": "extension.helloWorld",
	"group": "navigation"
    }
]

"editor/title/run": [
	{
		"command": "extension.helloWorld"
	},
	{
		"command": "extension.helloWorld2",
		"when": "editorHasSelection"
	},
	{
		"command": "extension.helloWorld3",
		"when": "editorLangId == typescript"
	}
],
```

**Comment by joaomoreno** [comment]
@jrieken All seems to work nicely. Just the `editor/title/run` icon is misleading, since it doesn't look like a dropdown at all. Maybe @misolori can help out here.

**Comment by jrieken** [comment]
>  since it doesn't look like a dropdown at all. 

I was wondering if there should a special icon, we the the run-all icon but maybe more explicit is even better

**Comment by misolori** [comment]
I was just going to comment that the icon feels like it needs a dropdown chevron, even a 12px version will do:

![image](https://user-images.githubusercontent.com/35271042/109078532-58bd7680-76b2-11eb-93e6-d3087625ddc7.png)

**Comment by misolori** [comment]
I can create a custom icon, but i think a better approach would be to allow for the chevron to be appended to the base icon as you can re-use the concept for other actions.

**Comment by devinvalenciano** [comment]
Saw a bit of weirdness on Windows - new run submenu can appear without being explicitly added to the product.json.  Additionally, the menu icons are not showing in the order defined by the product.json (although I don't know if this is expected behavior).  Issues referenced above.
