### ISSUE TITLE
Get started content becomes hidden on click

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117284]
https://user-images.githubusercontent.com/35271042/108772823-5b816580-7512-11eb-83c9-fbbf55d9886f.mov

Version: 1.54.0-insider
Commit: 11cd76005bc7516dcc726d7389d0bce1744e5c85
Date: 2021-02-22T06:44:36.656Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by JacksonKearl** [comment]
tru
