### ISSUE TITLE
[EXTENSION] Results from the debug session are different from the installed extension

### ISSUE THREAD

**Issue by jellypuno** [microsoft/vscode#117234]
- VS Code Version: 1.53.2
- OS Version: Windows 10

The results from the debug session are different from the one that I installed. I am trying to display quickpick items. It works during debug session but once I install the extension, it doesn't work. Your guidance on this is very much appreciated.

**Quickpick Results during Debug Mode:**
![ext](https://user-images.githubusercontent.com/45042840/108709243-b74bee80-7512-11eb-9005-346e74635c43.PNG)

**Quickpick Results after I installed it:**
![vsix](https://user-images.githubusercontent.com/45042840/108709294-c6cb3780-7512-11eb-962c-d6bb1876e9e4.PNG)

Does this issue occur when all extensions are disabled?: Yes/No
I don't know

**Comment by weinand** [comment]
@jellypuno sorry, but I don't understand your issue.

Please read this to learn how write helpful bug reports:
https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by jellypuno** [comment]
@weinand Thank you for getting back at me. 

**This is the gist of my project:**
I am writing a VSCode extension and in this extension I using vscode.quick[pick API. 
I am trying to gather some data and then I want to display it in the Quickpick dialog box as something that can be selected.

**My problem**
When I try to run my extension in Debug Mode, the data that I gathered is displayed in the Quickpick dialog box.
But when I try to package my extension in a vsix file and then install it in my VSCode IDE, the data is not displayed in the quickpick dialog box.

I am hoping that you can help me and point me in the right direction.

**Comment by chrmarti** [comment]
@jellypuno Could you add a `console.log(items)` before the showQuickPick call and compare its output between debug and vsix runs?
