### ISSUE TITLE
Welcome View shows informations multiple times

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#117226]
- VS Code Version: 1.54.0-insider (02/22/2021)
- OS Version: Windows 10 1909

Hi
I did find two issues in menus context, one in dropdown menus and one in some Welcome views. 

Steps to Reproduce: (Related: #117223, as you can see, its not about VM)

1. In a folder without launch.json, go to "Run and Debug" view
2. Select a menu (ex: Run) with some actions disabled
3. Hover a disabled action
4. Hovering another action closes dropdown

You will see as well an issue in "Welcome" view which prints four times (Git or Run/Debug). (It may not be related...)

Does this issue occur when all extensions are disabled?: Yes

![Capture_Insiders_Issue](https://user-images.githubusercontent.com/45362067/108698670-b0b67a80-7504-11eb-8563-796cc6939c2a.JPG)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/117237
