### ISSUE TITLE
Visual Studio Code Portable

### ISSUE THREAD

**Issue by andrecool-68** [microsoft/vscode#117270]
Visual Studio Code Portable 1.53.2
The portable version creates this directory:
`AppData\Roaming\Code\Dictionaries`
Is it possible to transfer the `Dictionaries` directory to the `data` directory?
The creation of the portable version was done according to this manual:
https://code.visualstudio.com/docs/editor/portable

The old version did not create this directory.
Visual Studio Code Portable 1.35.1

**Comment by IllusionMH** [comment]
Looks like caused by https://github.com/electron/electron/issues/26039

**Comment by andrecool-68** [comment]
@IllusionMH What does "Electron" have to do with it?

**Comment by IllusionMH** [comment]
VS Code is Electron based application - you can see this in Help > About

**Comment by andrecool-68** [comment]
@IllusionMH Теперь понятно)))

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/93828
