### ISSUE TITLE
takes ages to load

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#117215]
Issue Type: <b>Performance Issue</b>

just open vsc, it takes like, idk, 15 seconds sometimes

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.98GB free)|
|Process Argv|--crash-reporter-id f7231be8-388a-4ce3-bbec-851040fe046d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	 21300	code main
    1	   202	 14056	   gpu-process
    2	   115	 16020	   shared-process
    1	    77	 16488	   window (Issue Reporter)
    0	   184	 17512	   window (Cargo.toml - glitter - Visual Studio Code)
    0	    13	  4256	     watcherService 
    0	    11	   620	       console-window-host (Windows internal process)
    1	   220	 12872	     extensionHost
   12	   116	 11100	       electron_node server.js 
    0	    70	 16208	       "C:\Users\milo5\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\milo5\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12872
   12	   131	 16256	       c:\Users\milo5\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc.exe
    0	    11	  2636	         console-window-host (Windows internal process)
    0	     8	 17784	         "c:\Users\milo5\AppData\Roaming\Code\User\globalStorage\matklad.rust-analyzer\rust-analyzer-x86_64-pc-windows-msvc.exe" proc-macro
    1	     9	 20732	       C:\Users\milo5\scoop\shims\git.exe show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z fe2b3df2eb24d2e0bcea12a9b30984f6104e24e1
    0	    11	 20928	         console-window-host (Windows internal process)
    0	     6	 15520	     console-window-host (Windows internal process)
    0	    81	 18404	     C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    69	 20360	     searchService
    0	    23	 20660	   crashpad-handler
    0	    39	 21068	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Cargo.toml - glitter - Visual Studio Code)
|    Folder (glitter): 990 files
|      File types: o(133) json(96) timestamp(93) d(83) rmeta(65) rlib(36)
|                  pdb(29) exe(26) bin(18) yml(9)
|      Conf files: github-actions(4) launch.json(1) settings.json(1)
|      Launch Configs: lldb(3);
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-zipfs|arc|2.2.2
vscode-tailwindcss|bra|0.5.9
javascript-ejs-support|Dig|1.3.1
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
discord-vscode|icr|5.3.0
rust-analyzer|mat|0.2.497
template-string-converter|meg|0.4.7
vscode-scss|mrm|0.9.0
vsliveshare|ms-|1.0.3784
vetur|oct|0.32.0
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
crates|ser|0.5.6
even-better-toml|tam|0.10.0
vscode-wakatime|Wak|5.0.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Is it also slow if you start VS Code from a command prompt like this?
```
code --disable-extensions
```

**Comment by Milo123459** [comment]
not as slow but still notably slow

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by Milo123459** [comment]
I have...

**Comment by bpasero** [comment]
@Milo123459 what is the difference of startup time with extensions disabled vs all enabled?

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Milo123459** [comment]
Got my friend too, same issue.

**Comment by bpasero** [comment]
Can you follow this part of the wiki specifically for startup: https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by Milo123459** [comment]
Okay

**Comment by Milo123459** [comment]
[here](https://gist.github.com/Milo123459/4281c0115ffc101a11297a955dd113f7) you go

**Comment by Milo123459** [comment]
Couldn't it do something like, it loads up theme extensions then opens up the main vsc and loads everything else in the background?

**Comment by bpasero** [comment]
Looks like overall slowness across all numbers, though `require(workbench.desktop.main.js) | 2993` is quite high.

**Comment by Milo123459** [comment]
Hmmm, have we got any leads on what's causing this? Specifically some of the built-in process' that is taking a long time.

**Comment by npapapietro** [comment]
I'm experiencing this as well, both on windows and WSL. Opening a second window takes ages. I ran `code --prof-startup --disable-extensions` and it produces these results.

[prof-15e6.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6026078/prof-15e6.main.cpuprofile.txt)
[prof-15e6.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6026079/prof-15e6.renderer.cpuprofile.txt)
[prof-15e6.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6026081/prof-15e6.extHost.cpuprofile.txt)


Hope this helps!
