### ISSUE TITLE
Settings editor is partially unusable when configuring a custom editor for JSON

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117203]
Steps to Reproduce:

1. configure workbench editor associations to open *.json with a custom editor (e.g. HEX)
2. try to change this setting later

=> 🐛 you cannot because in order to edit the values, you need to go to the JSON but it will open the custom editor always:

![image](https://user-images.githubusercontent.com/900690/108674794-1e06e300-74e6-11eb-9246-ad84695889c0.png)

Imho we should have a way to prevent the override from happening fro built in files such as settings.

Only workaround is to entirely reset the setting.

//cc @lramos15

**Comment by lramos15** [comment]
I've made a PR to fix this issue, I've made it on my fork against the openWith refactor as I didn't want to make it against main and then have to fix all the conflicts given that the openWith refactor is being merged soon. @bpasero feel free to take a look if you'd like as I am unable to assign reviewers to my fork.
