### ISSUE TITLE
Add a setting to reveal a opened file in any window if opening from outside VS Code

### ISSUE THREAD

**Issue by tnaseem** [Microsoft/vscode#11728]
- VSCode Version: 1.5.1
- OS Version: OSX 10.11.6

Sorry for the strange title description there. I'm pretty crap at that :)

Not sure if this is a VSCode plugin issue or with Code itself...

In Split-View, if I have an error in the file in, say, the left view, and the last view I was in was the right one, when I click on the error in the Unity console, the same file will open up in a new tab in the right view, rather than selecting the same opened tab.

Steps to Reproduce:
1. Use Code in Split View.
2. Open a file (C# Monobehaviour) in the left view (file1.cs), and another in the second view (file2.cs).
3. Create an error in file1.cs, and save. Then switch to file2.cs in the right view.
4. Jump into Unity, and click on the error message in the console.

You'll now see file1.cs open another tab in the right view. Not sure if this is by design, but it would be good to have the option of just selecting the already opened tab. 

To illustrate what I mean...

![player_cs_-_buggyball](https://cloud.githubusercontent.com/assets/1317345/18370709/45b5866a-7683-11e6-807b-461af4107fc9.png)

**Comment by ramya-rao-a** [comment]
@tnaseem Is this a regression? i.e. Was this the same in 1.4.0 or happens only in 1.5.1?
What extensions do you have installed?

**Comment by tnaseem** [comment]
Ah Sorry, I should have said. It's always been there.

List of installed extensions...

![player_cs_-_buggyball](https://cloud.githubusercontent.com/assets/1317345/18375253/9f9c8528-76a8-11e6-94e9-452eea682064.png)

**Comment by ramya-rao-a** [comment]
This might be caused by the `Debugger for Unity` extension. I am not familiar with the extension. Can you share a screenshot of the console from where you click on the error message?
Is this console the same as the Debug console or a separate one?

**Comment by bpasero** [comment]
@tnaseem it is our design principle that we open editors in the group that is currently focussed, though we have a few places where we actually favour an already opened editor.

Where are you clicking to open the error? Is it an output channel? The debug console? Or the problems view?

**Comment by tnaseem** [comment]
It happens with and without the Unity Debugger extension (Just tried it now), and happens when I double click the error in the Unity console window.

Actually, the Unity console window is just a red herring. I just tried opening the same file from Finder (with another view in focus) and rather than just going to the existing tab in the other view, it opens another tab in the currently selected view.

Compare this with SublimeText which always works as expected (focusing on the existing tab), which is just seems more intuitive.

So, if this is by design, it'd be great to have this as an option to just reuse the same tab.

I actually thought this setting would solve my problems:

```
	// When enabled, will open files in a new window instead of reusing an existing instance.
	"window.openInNewWindow": false,
```
But alas, no :)

**Comment by bpasero** [comment]
@tnaseem to rephrase this is about opening files from outside VS Code into VS Code and you would like to have an option that if any opened VS Code window has the file open in an tab you want this window to become active and that tab to be revealed? Yes?

**Comment by tnaseem** [comment]
Yes. Exactly.

I originally thought it was a problem between Unity and VS Code, but since I've been playing around with it now, I realise I could have rephrased my question better in the original post :)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
