### ISSUE TITLE
Add dedentNextLinePattern to complement indentNextLinePattern

### ISSUE THREAD

**Issue by maxno-kivra** [microsoft/vscode#117278]
Issue Type: <b>Feature Request</b>

I was [recently working](https://github.com/erlang-ls/vscode/pull/69) on improving the Erlang LS language configuration, and stumbled upon the various indentation rules patterns.

However I couldn't quiet get it to behave. The issue is that in Erlang you want to dedent on the line _after_ `;` and `.`, and not the line itelf.

```erlang
map(_, [], Result) ->
    lists:reverse(Result);
map(Fun, [Head|Tail], Accumulator) ->
    map(Fun, Tail, [Fun(Head)|Accumulator]).

func() ->
    case Something of
        pattern ->
            foo(),
            bar(); % <- I want to dedent after this...
    end. % ...which would make `end` dendent correctly. Then dedent again after `.`
```

I saw https://github.com/microsoft/vscode/issues/17868 which lead me to `indentNextLinePattern`, but as stated there there's a difference between increase and decrease patterns. The first applies _after_ the second _directly_.

I also saw https://github.com/microsoft/vscode/issues/34621 amongst others, but that's far of into the future I believe. LSP also contain formatting, so maybe the truly future way :tm: is to do something there. But I digress. Right now I just want to be able to tweak the exisitng language configuration to be able to handle a bit more :smile:

_Note: Not all pattern types are documented, [filed an issue](https://github.com/microsoft/vscode-docs/issues/4348) for that as well._

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.2.0

**Comment by WatDuhHekBro** [comment]
What you could use instead is `onEnterRules`. This snippet for example unindents after pressing enter as long as it matches the regex patterns given (in this case, after a break statement).
```json
"onEnterRules": [
	{
		"beforeText": "^\\s*break;?$",
		"action": { "indent": "outdent" }
	}
]
```
If you want to take the previous line into account, there's `previousLineText` too.

**Comment by maxno-kivra** [comment]
Aha, cool. I thought they were just in the imperative API, but saw #114348 and #114948 now. Will take it for a spin. This is also not documented at the moment, but that's a separate issue.

Iff you can accomplish the above with `onEnterRules` alone, I guess it's just a matter of documentation. On one hand it would be _nice_ to have this for symmetry. On the other it might be easier to understand `onEnterRules` and the others could (should?) be deprecated,  perhaps just in the docs. So many questions, but not too many answers I'm afraid.

**Comment by maxno-kivra** [comment]
I got most of what I wanted out of the onEnterRules, so I'm going to close this. I think it's just a matter of documentation at this point. Thanks for the awesome work and making such a nice editor ❤️
