### ISSUE TITLE
IOpenEditorOverrideHandler is very weird

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117210]
I feel `IOpenEditorOverrideHandler` is weird.

Why does `open` return a `IOpenEditorOverride | undefined` where `IOpenEditorOverride#override` is optional? Why can we not directly return `Promise<IEditorPane | undefined>` from `open`.

And what is the purpose of `getEditorOverrides`. It seems weird to me that a contributor can return `IOpenEditorOverrideEntry[]` but in the `open` call there are no traces anymore of what override entry was used.

**Comment by bpasero** [comment]
My hope is that maybe with https://github.com/microsoft/vscode/issues/100281 all of this weird indirections could go away.

**Comment by jrieken** [comment]
Just for reference, the implementation of notebook's `open`. Maybe we aren't doing this right but I have the feeling this shouldn't be so much code

https://github.com/microsoft/vscode/blob/65e283212409e65a7c90b59831d671b7dd2ded9b/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L322-L476

**Comment by jrieken** [comment]
tab spying

https://github.com/microsoft/vscode/blob/1c755a4fca288524c8aa1d215de9349ca8447a1a/src/vs/workbench/contrib/notebook/browser/notebookEditorWidgetServiceImpl.ts#L74

**Comment by lramos15** [comment]
@jrieken I have fixed the tab spying with an `OnWillMoveEditor` event. However, the actual opening logic cannot be reduced without adding an intermediary opener that services just custom editors and notebooks as what they do is too specialized to enter into the EditorService.

**Comment by lramos15** [comment]
This "intermediary" service has been added and upon completion of https://github.com/microsoft/vscode/issues/121668 this handler will go away all together.

**Comment by bpasero** [comment]
The handler is gone 👏
