### ISSUE TITLE
Forward a Port action in command pallette and in the view are not same

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117396]
Testing #117250

<img width="653" alt="image" src="https://user-images.githubusercontent.com/10746682/108851599-e599fe80-75e4-11eb-87c3-b512dbf8b862.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/10746682/108851615-ec287600-75e4-11eb-8dbf-022f1d6963c1.png">

Above two entries with same name are not doing the same - one is opening the quick pick and the other is adding entry in the view

**Comment by alexr00** [comment]
This is a feature for folks who don't want to ever see the ports view :).  I can change the behavior for March and we will see if anyone complains in insiders.

**Comment by alexr00** [comment]
Based on  telemetry, I'm leaving this as is. There are still users who want this.
