### ISSUE TITLE
Diff editors show a bogus? run icon

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117329]
![image](https://user-images.githubusercontent.com/641685/108813613-61616000-757f-11eb-8ce5-f8f4561c5574.png)

**Comment by eamodio** [comment]
Not sure what else you need? Open a diff editor, e.g. from a file in the SCM view and a run icon shows up at the front of the editor toolbar.

**Comment by jrieken** [comment]
nope

<img width="483" alt="Screenshot 2021-02-23 at 09 54 33" src="https://user-images.githubusercontent.com/1794099/108820909-23832c80-75bd-11eb-8230-8ffd5e0a9479.png">

**Comment by eamodio** [comment]
I can't repo this with just a normal diff anymore, but I still see it with a GitLens diff between 2 revisions:

![image](https://user-images.githubusercontent.com/641685/109123384-c64fbe00-7717-11eb-8291-c4ac9a5f1770.png)

Steps:
1. Open a file and click the _Open Changes with Previous Revision_ button in the editor toolbar (or via the command palette)
2. When in the diff, repeat step 1 (so that there is a revision on both sides)
3. See the _Run_ button appear

**Comment by jrieken** [comment]
maybe the same as https://github.com/microsoft/vscode/issues/117640
