### ISSUE TITLE
Getting started: low contrast for activity bar image

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117341]
Refs: https://github.com/microsoft/vscode/issues/117313

Notice how the picture shows the activity bar, but due to low contrast it is impossible to see it 

![Screenshot 2021-02-23 at 10 45 43](https://user-images.githubusercontent.com/1926584/108826355-7ca28e80-75c4-11eb-86e7-0edc5e4e5b26.png)

**Comment by digitarald** [comment]
New SVG is used instead now.
