### ISSUE TITLE
Terminal stays black after reloads

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#117363]
Testing #117265

Version: 1.54.0-insider
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:17:41.287Z
OS: Linux x64 5.8.0-43-generic

- open a terminal
- Invoke several window reloads in a row. Once in a while the terminal stays black.
- The drop down can be either `1:bash` or just `1:`
- In the first case, resizing the window fixes the issue, in the second only a reload brings back the terminal

![terminal-reload](https://user-images.githubusercontent.com/6461412/108834486-88934e00-75ce-11eb-945c-ed6e07899a25.gif)

![terminal-reload2](https://user-images.githubusercontent.com/6461412/108835242-7f56b100-75cf-11eb-8974-665f19fd53c0.gif)

**Comment by miguelt1** [comment]
I got the same bug, it's very annoying actually

**Comment by meganrogge** [comment]
I'm not able to reproduce this issue. Are there any errors in dev tools?

**Comment by meganrogge** [comment]
couldn't repro on Windows, but just did on my mac.

**Comment by aeschli** [comment]
I could reproduce it many times. No messages in the dev tools, nor in any logs (not sure which logs are applicable)
