### ISSUE TITLE
Input box does not occupy complete cell

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117386]
Testing #117250

<img width="339" alt="image" src="https://user-images.githubusercontent.com/10746682/108850051-2c86f480-75e3-11eb-96d9-4d4f480e5a2c.png">

See the addition padding/space at the beginning of the cell

**Comment by alexr00** [comment]
@joaomoreno this is the 10px padding-right on .monaco-table-td:

https://github.com/microsoft/vscode/blob/26dff8f2cca845ee23c7bb77dc79fbbe5f48cc93/src/vs/base/browser/ui/table/table.css#L36-L43

I fixed this by overwriting the padding when the input is displayed (and putting it back later), but this isn't very nice. Do you have any other ideas?

https://github.com/microsoft/vscode/blob/5e16cc37c6b7c9ac9a64fa53b7b6272a2953cd28/src/vs/workbench/contrib/remote/browser/tunnelView.ts#L384-L385

**Comment by alexr00** [comment]
Based on discussion, the input box will no long fill the whole cell: https://github.com/microsoft/vscode-remote-release/issues/4729
