### ISSUE TITLE
With focus in terminal, can't open menus with Alt+access_key

### ISSUE THREAD

**Issue by JohnKlenk** [microsoft/vscode#117318]
Issue Type: <b>Bug</b>

With focus in the terminal, you can't open menus (from the main menubar) with the keyboard by pressing Alt and the menu access key (such as Alt-r for Run).  You have to press and release Alt, and then press the menu's access key.  So for example to open the Run menu, you have to press Alt, release Alt, and then press r.  (But worse is that you won't necessarily realize it will work even with that extra step, so you'll just assume keyboard access is broken.)

Happens on Win 10 even with the custom titlebar.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.79GB (10.90GB free)|
|Process Argv|--crash-reporter-id 42431fa7-02b8-4885-aa66-fb6b0034b665 --crash-reporter-id 42431fa7-02b8-4885-aa66-fb6b0034b665|
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
vscode-pull-request-github|Git|0.23.1
cpptools|ms-|1.2.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30258532

```

</details>

**Comment by sbatten** [comment]
@JohnKlenk please see setting: `terminal.integrated.allowMnemonics`


@Tyriar even with this setting, `workbench.action.terminal.toggleFindRegex` is conflicting with the menu bar

**Comment by Tyriar** [comment]
> @Tyriar even with this setting, workbench.action.terminal.toggleFindRegex is conflicting with the menu bar

@sbatten just like in the editor, I'd say this is by designed since it's allow not force.

**Comment by JohnKlenk** [comment]
Thanks for the info about that setting.  I just enabled it.
