### ISSUE TITLE
skipFiles has no effect on tslib.js

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#117347]
Issue Type: <b>Bug</b>

The issue is identical to #111301
I have captured the trace, but I'm not sure if @connor4312 is still responsible. Please let me know where to send it.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (28.28GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (25.27GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (25.27GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (25.27GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
output-colorizer|IBM|0.1.2
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.3.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
terraform|has|2.7.0
vscode-esformatter|how|1.6.0
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.21
vscode-yaml|red|0.15.0
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
@connor4312 I've sent the trace to your xbox.com address.

**Comment by connor4312** [comment]
`skipFiles` is a glob pattern, you probably want to use `**/tslib.js` rather than just `tslib.js`

**Comment by oliversalzburg** [comment]
![image](https://user-images.githubusercontent.com/1658949/108982364-023e4100-768e-11eb-8dcd-463e338de2fa.png)
Argh! Why?!

Thank you

**Comment by weinand** [comment]
@oliversalzburg because `skipFiles` expects glob patterns.

**Comment by oliversalzburg** [comment]
@weinand Yeah, thanks, Connor explained it to me too. My remark was referring to the diff I found in my VCS history, which was removing the globbing pattern.
