### ISSUE TITLE
System freezes on starting up VS code and also while working on it

### ISSUE THREAD

**Issue by gurkaran-s** [microsoft/vscode#117325]
On starting VS code, system freezes for 10-20min
And also while working, searching a file name or a text or opening a file, system hangs again for 5-10min.

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by deepak1556** [comment]
Please confirm the following,

* Does the issue happen with https://code.visualstudio.com/updates/v1_52 ?
* Can you start with `code --disable-extensions` and check if the issue continues
* When the hang occurs, can you get the output of `code --status`
* Lastly, can you check if starting with `code --disable-features=CalculateNativeWinOcclusion` helps
