### ISSUE TITLE
Sashes are not available some times

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117397]
Testing #117250

- Move panel to right and adjust the width of the panel

🐛 Sashes are not available

<img width="716" alt="image" src="https://user-images.githubusercontent.com/10746682/108852347-ca7bbe80-75e5-11eb-97e0-1d9e25bdf783.png">

**Comment by joaomoreno** [comment]
Just like every splitview: sashes are not enabled because all views are at maximum size, since there's no capacity in the container to fit them all. Real issue is https://github.com/microsoft/vscode/issues/117049.
