### ISSUE TITLE
SSH got disconnect after a while of unused, but the reconnection is not working

### ISSUE THREAD

**Issue by congzong** [microsoft/vscode#117311]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

When the shhed window got unused for a while, the ssh connection will get disconnected which is normal. But when I click the reconnect button on left down conner. The reconnection is not working. When I start a new connect in same window, it also not working.
The only way I can do is open a new window and connect from start again. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 3.10.0-1160.11.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 199d9707-045e-4133-87f8-06f46025b981|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: wheeler.allianc.unm.edu|
|OS|Linux x64 3.10.0-1160.11.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU           X5550  @ 2.67GHz (8 x 1600)|
|Memory (System)|47.00GB (0.28GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.23.1
better-cpp-syntax|jef|1.15.5
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.1
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3784
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
pdf|tom|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by roblourens** [comment]
This may be fixed now. Please try the  Remote-SSH Nightly extension to confirm, or wait for the next update, soon.
