### ISSUE TITLE
Notebook Screen cheese

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117334]
* open the `endgame.github-issues` notebook
* collapsed all cells under 'preparation'
* from the bottom upwards run cells and expanded cell above

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1794099/108820666-cbe4c100-75bc-11eb-8e04-752c703a0310.png">

**Comment by rebornix** [comment]
the root cause was the markdown renderer related and it was already fixed. Please reopen if you are still seeing it.
