### ISSUE TITLE
1.5 Release breaking React ES6

### ISSUE THREAD

**Issue by johnmullany** [Microsoft/vscode#11730]
- VSCode Version: 1.5 or 1.5.1
- OS Version: Windows 10

Steps to Reproduce:

1. using webpack (haven't tried gulp yet) npm start any project that has ES6 code in it and it will break. Same project works fine using Atom.
2. You'll get the module parse failed:  Unexpected token with the line number and You may need an appropriate loader to handle this file type.
I can go right back to Atom and use the exact same project with the integrated terminal in that program run npm start and everything loads perfectly, all tests, all linting passes, and hot loading starts.

**Comment by waderyan** [comment]
@johnmullany I can't recreate on my own projects with ES6 code nor can I recreate with a simple project. Can you provide a small sample of code reproducing the error?

**Comment by johnmullany** [comment]
I found someone else having the same issue but they were using brackets so it turned out to be an electron problem. I used npm install --runtime=electron and it solved it for me. Any project where you use ES6 for your webpack.config was causing the issue for me.

**Comment by waderyan** [comment]
@johnmullany thank you for your response.

@bpasero before I close this can you advise on this issue. OP problem was common between VS Code and Brackets, but not Atom. OP solved his issue by npm install --runtime=electron. Do you know why he would need to do that? I haven't seen this issue before, but if it happens for others I want to be able to give them guidance.

**Comment by bpasero** [comment]
The runtime option is only needed if you compile native NPM modules to run from within Code that executes in Electron. I do not think this would be needed for any development in VS Code, but cannot say for sure...
