### ISSUE TITLE
Extension tests no longer show output with color

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117364]
Steps to Reproduce:

1. run `scripts/test-integration.sh`
2. notice how the first integration test shows green checkmarks
3. notice how the second tests show black and white

![image](https://user-images.githubusercontent.com/900690/108835311-96959e80-75cf-11eb-9c8c-5220a17be01f.png)

**Comment by sandy081** [comment]
@bpasero colors for second tests were never supported - I double checked in 1.53.2.

First tests were run as normal mocha tests 

https://github.com/microsoft/vscode/blob/9de38fc9a8058f0b42057bb0076d989455b58edc/scripts/test-integration.sh#L64-L64

Rest of the tests are real extension API tests.

**Comment by bpasero** [comment]
OK, if you confirmed with how it was before, feel free to close, I didn't know that.
