### ISSUE TITLE
svg icon contributed for a view container doesn't show in web

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#117395]
Testing https://github.com/microsoft/vscode-internalbacklog/issues/1850 https://github.com/microsoft/vssaas-planning/issues/2448

1. Connect to a codespace.
2.. Install alefragnani.project-manager
3. This extension contributes a view container with an svg icon: https://github.com/alefragnani/vscode-project-manager/blob/master/package.json#L61
4. 🐛The icon doesn't display correctly (it's totally missing).
5. Reload, then the icon will appear.

**Comment by sandy081** [comment]
It works for me both in web and in desktop

![Kapture 2021-02-24 at 12 49 58](https://user-images.githubusercontent.com/10746682/108996577-d8d9e100-769e-11eb-8f6e-15ac6a03f862.gif)

Am I missing any steps here?

**Comment by alexr00** [comment]
No, those are all the steps. The icon was simply not there when I did the same steps.

**Comment by sandy081** [comment]
Can you please try to repro again and inspect the element and see if there is bg image url and to where it is pointed to?

**Comment by alexr00** [comment]
I am not able to repro now. I even tried with a new codespace since that is where it happened before.
