### ISSUE TITLE
Getting started: align with ActionBar navigation pattern

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117339]
Refs: https://github.com/microsoft/vscode/issues/117313

1. Getting started, focus on some button for example "Browse Recommended Extensions"
2. Press right key -> nothing happens 🐛 
3. Expected: focus moves to Next button

I suggest that you use the `ActionBar` when you have 2 or more actions.
Reason being that we have the action navigation consistent across the workbench. Only one tab stop for the action bar, left / right to navigate the actions. Tab always moves focus away

**Comment by JacksonKearl** [comment]
We may be moving way form the `next` button, but good to keep in mind as we plan on adding support for multiple buttons.

**Comment by isidorn** [comment]
Cool. If you add those multiple buttons let me know and I can try it out.

**Comment by bhavyaus** [comment]
We no longer have the Next button in the walkthroughs. Resolving this.
