### ISSUE TITLE
Restore/remember application size

### ISSUE THREAD

**Issue by RussKie** [microsoft/vscode#117320]
## Current

I have a 4K monitor and I size VS Code instances to a size I find comfortable. However whenever I open a new instances of VS Code it opens with a default size of 1024x768.

## Expected

VS Code remembers the location/windows size of the last closed instance, and a new instance is opened with the persisted dimensions at the persisted location.

## Technical

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz (12 x 3402)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (6.60GB free)|
|Process Argv|. --crash-reporter-id a46f8b5e-f39a-4bd6-90c7-4daff94735b3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
quick-html-previewer|dai|1.0.1
dotnet-test-explorer|for|0.7.5
csharp|ms-|1.23.9
powershell|ms-|2020.6.0
prettier-plus|svi|4.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475

```

</details>

**Comment by gudvinr** [comment]
This also happens when you open projects from welcome screen when "Always show the welcome screen" option enabled.  
Same with recent projects. You have to resize windows every time you open something.
