### ISSUE TITLE
Input box is not highlighted completely

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117385]
Testing #117250

<img width="385" alt="image" src="https://user-images.githubusercontent.com/10746682/108849638-af5b7f80-75e2-11eb-8563-867f9227ed82.png">

**Comment by alexr00** [comment]
@misolori is it ok to change the line height of the rows of the table? The issue here is that the input box doesn't fit in the table cell, and to fix it I can increase the `lineHeight` from 22 to 27. However, I'm not sure if that's ok given that `lineHeight` is almost always 22.
