### ISSUE TITLE
Terminal does not restore after opening on a new folder

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#117372]
Testing #117265

Version: 1.54.0-insider
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:17:41.287Z
OS: Linux x64 5.8.0-43-generic

- open a folder (e.g. the folder with the vscode repo) and open a terminal
- use the recent menu to open another folder
- use the recent menu again to open the first folder again
- the terminal does not restore correctly, can not be deleted, but recovers after switching to another view (Except of the `Starting...`)

![terminal-open-folders](https://user-images.githubusercontent.com/6461412/108838443-ed04dc00-75d3-11eb-8069-fba2930352b1.gif)

**Comment by eamodio** [comment]
Seeing the same.

**Comment by meganrogge** [comment]
Doing the above steps does not cause the issue:
![recording (28)](https://user-images.githubusercontent.com/29464607/108911741-846e2d00-75dc-11eb-8a89-2e2ea71635b9.gif)

One more step was needed for me to repro this:
- hide the panel in folder A 
- open folder B with the terminal revealed 
- open folder A and reveal the panel

**Comment by Tyriar** [comment]
My guess is we're not discarding of layout information when the window goes down but we are with the processes, so folder A terminals attempt to get restored and we're not handling it.

Probable steps to fix:

- Make sure we remove layout information for terminals being killed when closing the window
- Make sure we handle exceptions thrown when restoring terminals (just in case, this shouldn't happen after above)
