### ISSUE TITLE
API, `undefined` means false

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117381]
Testing #117307

The `TestItem.runnable` property is defined as optional but defaults to `true`. It means `undefined` equals `true` and try to avoid that

https://github.com/microsoft/vscode/blob/e4364e5f5da60e371f995001836175d81cd942c3/src/vs/vscode.proposed.d.ts#L2403

**Comment by connor4312** [comment]
Hm. I could make it required, but I definitely don't want to make a property for "notRunnable" since that is quite confusing.

**Comment by jrieken** [comment]
I think the challenge is to figure out what is a test that's not runnable. Is that really a test or some kind of leaf/container or whatnot. Once that's clear you have a name ;-) Tho, maybe it's also overloading the meaning of a `TestItem`, e.g how does the UI render not-runnable tests? Do I still get code lens for them?
