### ISSUE TITLE
Pressing enter on a row with a port is showing the input box in the port cell 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117387]
Testing #117250

- Press enter on the row -> port column shows input box
🐛 But Double click on the port column in the row -> nothing happens

Expected to show the input box 

![Kapture 2021-02-23 at 17 09 39](https://user-images.githubusercontent.com/10746682/108872125-24867f00-75fa-11eb-8b35-18b3acd1399e.gif)

**Comment by alexr00** [comment]
> Pressing enter on the row edits the port cell

Hmm, pressing enter on the row shouldn't be editing the port cell. I can't repro this though. Can you share a gif?

**Comment by sandy081** [comment]
@alexr00 Added the gif - Also reverted the summary - Expecting that on dbl clk on the port column to show input box.

**Comment by alexr00** [comment]
I don't think that enter or double click on cells should show the input box. This is not a pattern we have anywhere that I know of. For example, in the explorer double click doesn't allow you to rename.

**Comment by alexr00** [comment]
Also, it is a bug that enter is showing the input box.

**Comment by sandy081** [comment]
If `enter` is not supported then I think `dbl clk` is not needed. I filed this mainly because `enter` is editing.

**Comment by alexr00** [comment]
Ah, I do have `enter` as the label keybinding on mac. On Windows it's F2. This exactly matches the file explorer. However, the file explorer still does not do double click for re-name, so I will leave as is.
