### ISSUE TITLE
Welcome views are getting content duplicated

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117328]
![image](https://user-images.githubusercontent.com/641685/108813567-48f14580-757f-11eb-8216-8fcb97dccd7b.png)

**Comment by gjsjohnmurray** [comment]
/duplicate and expected to be fixed in new Insiders

**Comment by dcermak** [comment]
Just confirming that this has been fixed on main (I just checked out 53fc5f7bb598e594ce4b89646d2e5225dc192df0 and the issue is gone there).
