### ISSUE TITLE
Unable to login to Github for settings sync

### ISSUE THREAD

**Issue by shadycuz** [microsoft/vscode#117377]
- VS Code Version: 1.53.2
- OS Version: Amazon Linux 2

Steps to Reproduce:

1. Click settings sync
2. Click Github
3. Click authorize
4. Copy Token
5. Click `signing in to github....` in taskbar
6. paste token and hit enter (nothing happens)

Does this issue occur when all extensions are disabled?: Yes

From the Github Authentication log:

```
[Info  - 12:10:32.76] Logging in...
[Info  - 12:10:50.5] Treating input as token
```

**Comment by shadycuz** [comment]
Insiders build fixed it.
```
Version: 1.54.0-insider
Commit: bd74308b5abbbb2f5a5df0f0d8a3bef606652d36
Date: 2021-02-23T05:17:41.287Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.14.214-160.339.amzn2.x86_64
```

**Comment by RMacfarlane** [comment]
Thanks for confirming!
