### ISSUE TITLE
File menu bug

### ISSUE THREAD

**Issue by KevinFSW** [microsoft/vscode#117324]
Issue Type: <b>Bug</b>

When I click File menu, move mouse to select the menu of Close Folder, then File menu automatically and suddenly close.

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T05:14:36.498Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (23.04GB free)|
|Process Argv|--crash-reporter-id 079469c0-e3e1-4e7d-ace3-10b90f912a8a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
vscode-pull-request-github|Git|0.23.1
better-cpp-syntax|jef|1.15.5
svn-scm|joh|2.13.5
remote-containers|ms-|0.161.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2-insiders2
cpptools-extension-pack|ms-|1.0.0
vsonline|ms-|1.0.3076
java|red|0.75.0
sonarlint-vscode|Son|1.20.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in the next Insiders
