### ISSUE TITLE
The info of  "this"   is inconsistent  with log when debugging

### ISSUE THREAD

**Issue by sonic-github** [microsoft/vscode#117322]
The test class is not windows.It's my test class. 
![image](https://user-images.githubusercontent.com/57396304/108809857-b08dac00-75e4-11eb-9f0f-d8cc863a1599.png)

![image](https://user-images.githubusercontent.com/57396304/108810375-f72fd600-75e5-11eb-813c-716fa8a37380.png)

**Comment by connor4312** [comment]
How is your code being compiled? This is probably a result of downleveling arrow functions.

**Comment by sonic-github** [comment]
Is is probably a bug of the Plus-in.
