### ISSUE TITLE
Hope the default User Settings allow to use the "," in the last sentence

### ISSUE THREAD

**Issue by czmecho** [Microsoft/vscode#11736]
- VSCode Version: 1.5
- OS Version: win 10
just like this:
![sp160909_101348.png](https://ooo.0o0.ooo/2016/09/09/57d229d6d64d3.png)

if I add the setting sentence in the last ,I have to remove the ",".
the default User Settings allow to use the "," in the last sentence,I don't need to remove it.

**Comment by ramya-rao-a** [comment]
That wouldn't be valid json, and since we have to parse the json to read the settings, I don't think we will be making this change. @bpasero Can you confirm?

**Comment by bpasero** [comment]
Our JSON parser is tolerant to errors like that, but you should try to keep your JSON file valid...
