### ISSUE TITLE
Run VS Code with admin privileges so the changes can be applied

### ISSUE THREAD

**Issue by z442a9** [Microsoft/vscode#11739]
- VSCode Version: 1.5.1
- OS Version: Windows 10 64-bit (1607)

Steps to Reproduce:

1. Everytime I open VS Code without Administrator rights I get these errors. When I run it with Admin rights everything works. 

![2016-09-09 06_52_43-deploy-application ps1 - visual studio code](https://cloud.githubusercontent.com/assets/22090797/18374974/4a83f6d2-765a-11e6-9477-6d462320a108.png)

**Comment by hashhar** [comment]
I think you have installed the icons extension? If yes, then run code with admin privileges once. It will then popup a message telling you that icon support is now enabled. You can then run code normally.

**Comment by z442a9** [comment]
Yes I had that and I tried running the VS Code with admin privileges but it didn't help. I removed icons extension completely from standard user and now I don't get anymore "Run VS Code with admin privileges so the changes can be applied". If I have Powershell extension I will get those two error messages seen in the picture. It's kinda sad if you cannot run VS Code without administrative rights. I never use my computer as admin in daily tasks.

**Comment by gjstockham** [comment]
I get this with the git history extension whenever I try to use it.  I get the same message even when I'm running as admin.  I got the same message with icons, but after updating that now seems to work as expected.

**Comment by ramya-rao-a** [comment]
@z442a9 @gjstockham Can you log issues in the repos for the Powershell and Git History extensions respectively for this issue?

**Comment by DonJayamanne** [comment]
@ramya-rao-a , @z442a9 , @gjstockham 
I believe this is an issue related to the VS Code Icons extension. I say this because this error message is displayed by that extension and not VS Code, nor the Git history extension, I suspect its the same with the Powershell extension.

**Comment by Structed** [comment]
I get this message whenever I want to use the "Git History (Git log)" extension - no matter if I start VS Code with admin privileges or not.

OS: Windows 10 - Anniversary Edition (Version 1607)

**Comment by awitherow** [comment]
I got this as well with OS X and updated my VS Code Icons, reset the application and have not been able to replicate.
