### ISSUE TITLE
Input shall retain the existing value

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117390]
Testing #117250

- Press enter on an existing row
🐛 Input box appears but empty

Expected to retain the previous value

![Kapture 2021-02-23 at 17 09 39](https://user-images.githubusercontent.com/10746682/108872125-24867f00-75fa-11eb-8b35-18b3acd1399e.gif)

**Comment by alexr00** [comment]
@sandy081 can you share a gif? The only row that pressing enter should do anything for is the + row. Since there is no existing value on that row, we don't have anything to prepopulate the input box with.

**Comment by sandy081** [comment]
@alexr00 Done
