### ISSUE TITLE
characters lost on random locations

### ISSUE THREAD

**Issue by fengdasuk19** [microsoft/vscode#117323]
Issue Type: <b>Bug</b>

With VSCode opening, the computer has sleeped for at least 10 hours. When I wake the computer from sleep, I found that so many character lost, and the lines where the problem appears were random.

![90291614061391_ pic_hd](https://user-images.githubusercontent.com/11484001/108810260-b33cd100-75e5-11eb-97f7-80c77499140a.jpg)
![90301614061408_ pic](https://user-images.githubusercontent.com/11484001/108810267-b89a1b80-75e5-11eb-9d8f-17bbefc161ed.jpg)
![90311614061431_ pic](https://user-images.githubusercontent.com/11484001/108810272-bd5ecf80-75e5-11eb-8d4b-9d500d87e4cb.jpg)

VS Code version: Code - Insiders 1.53.0-insider (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T15:52:19.585Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 3249f918-f3fa-4a70-868b-2315621d215a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonviewer|cci|1.2.2
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
gc-excelviewer|Gra|3.0.41
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
vim|vsc|1.18.9
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
wslfolderdoc:30257851
vscoresta800:30259386

```

</details>

**Comment by rzhao271** [comment]
Can you check whether an extension caused this issue?
