### ISSUE TITLE
Test Getting Started Extension Point

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#117310]
Testing #116414

- [x] anyOS @rebornix 
- [x] anyOS @stevencl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117310%0A%0A)

---

This iteration we added a new (proposed api) contribution point for getting started items, test that it makes sense to use and works as expected. 

1. New extension with proposed API,
2. In `package.json` contributes clause, add a `gettingStarted` field. 
3. Verify that intellisense guides you through creating items for the getting started content
4. Verify that when running the extension, you see the contributed items in the `Help: Getting Started` page and can work through them

**Comment by stevencl** [comment]
This all worked, although there was no auto complete for adding the gettingStarted field itself (I got intellisense for the items within the gettingStarted field though).

**Comment by JacksonKearl** [comment]
Thanks! No autocomplete for the gettingStarted field is expected as it's still proposed.

**Comment by rebornix** [comment]
It works in overall but I'm not sure how one extension will clear the get started states other than changing the command ids used in the steps.
