### ISSUE TITLE
Auto format

### ISSUE THREAD

**Issue by pby28** [microsoft/vscode#117359]
Issue Type: <b>Bug</b>

When you input < / script >, the editor will format the rest of the code very disorderly, and it will also disrupt the code when repairing, which is very inconvenient. Can you repair it quickly? thank you.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.90GB (5.21GB free)|
|Process Argv|--crash-reporter-id f1277821-fdcf-45c2-b06a-799155158714|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
jsrefactor|cms|2.20.6
vbscript|Dar|1.0.4
prettier-vscode|esb|5.9.2
apk-locator|its|1.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
smalise|Loy|0.0.8
VBScript|lug|0.0.2
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
apklab|Sur|1.3.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30260844

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`


And provide code example.

**Comment by aeschli** [comment]
@pby28 Please a a small html code snippet that shows the problem.
