### ISSUE TITLE
Slightly unexpected tab stop behaviour

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117352]
Testing #116559

This was probably done for a reason because we used to stop at very action but maybe we should revisit this now?

![recording](https://user-images.githubusercontent.com/900690/108828667-6b0eb600-75c7-11eb-9c8a-d041fbde4fb5.gif)

**Comment by isidorn** [comment]
Agree 100%, however I already filed an issue for this https://github.com/microsoft/vscode/issues/116454
fyi @JacksonKearl would be cool if we find time next milestone for this
