### ISSUE TITLE
Getting started: low contrast for checkmark circles in dark theme

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117340]
Refs: https://github.com/microsoft/vscode/issues/117313

The contrast of the checkmark circles is not strong enough in dark theme. I barely noticed the checkmark.

![Screenshot 2021-02-23 at 10 45 05](https://user-images.githubusercontent.com/1926584/108826246-5bda3900-75c4-11eb-97fe-f8215f8a4932.png)

**Comment by misolori** [comment]
Updated

![image](https://user-images.githubusercontent.com/35271042/108947102-a8e5fb80-7614-11eb-9178-140f207e2408.png)
