### ISSUE TITLE
--user-data-dir does not allow relative paths on Windows

### ISSUE THREAD

**Issue by fengbjhqs** [Microsoft/vscode#11735]
- VSCode Version:1.5
- OS Version:windows 7

Steps to Reproduce:

1. run D:\vscode\Code.exe --user-data-dir="./user/data/"     is absolute paths 

Version:1.5  D:\user\data

Version:1.4  D:\vscode\user\data

**Comment by joaomoreno** [comment]
cc @bpasero ring any bells?

**Comment by bpasero** [comment]
@joaomoreno does minimist tamper with our arguments and maybe rewrites them?

**Comment by joaomoreno** [comment]
No, I was rather asking whether we touched something there lately.

**Comment by bpasero** [comment]
@joaomoreno not to my knowledge and we also did not update electron. Though I would give @Tyriar a ping because I know this is an area where he was also working in (not sure if last milestone though).

**Comment by Tyriar** [comment]
I don't think I've touched this recently, this is where it's used: https://github.com/Microsoft/vscode/blob/cd2cccfbde37ef218c0e98e4931137edd8e5f336/src/main.js#L125

Maybe an Electron update changed [`app.setPath`](http://electron.atom.io/docs/api/app/#appsetpathname-path)? I think I only ever used it with `~/` not `./` which is expanded out by bash so I wouldn't even have known this was a regression.

**Comment by Tyriar** [comment]
Relative works fine on Linux/bash, maybe it's a Windows-specific problem?

**Comment by bpasero** [comment]
@Tyriar last electron update was like 5 months ago.

**Comment by Tyriar** [comment]
Tested it out on Windows, I get an error and it doesn't launch unless it's an absolute path:

![image](https://cloud.githubusercontent.com/assets/2193314/18447874/50f063a4-78dd-11e6-853c-607964e2fc14.png)


Does not launch (error popup):

```
code --user-data-dir testuserdata
code --user-data-dir .\testuserdata
code --user-data-dir ./testuserdata
```

Launches:

```
code-insiders --user-data-dir c:\Users\daimms\Documents\testuserdata
```

**Comment by bpasero** [comment]
This might also be something that changes if we update to a newer Electron version.

**Comment by joaomoreno** [comment]
Thanks @Tyriar!

**Comment by Tyriar** [comment]
Something is still a little off, I can now reproduce on Linux if I launch using `./` and then try to open settings. It works just fine when I use the full path.

**Comment by Tyriar** [comment]
Found the root cause, `userDataPath` is defined in `environmentService.ts` which is in the `node` layer, meaning it doesn't have access to `app` so the arg needs to be recomputed over there. Ideally it would use `app.getPath('userData')` but that would mean pushing it to `electron-browser`.

**Comment by ramya-rao-a** [comment]
@Tyriar I no longer see the error in the pop up. But I dont see anything else either. Nothing gets launched

`code-insiders --user-data-dir="./GitRepos/vscode-go"`

**Comment by Tyriar** [comment]
@ramya-rao-a I'm not sure it supports quotes? Can you try without them?

**Comment by ramya-rao-a** [comment]
Tried it. Same result

**Comment by Tyriar** [comment]
@ramya-rao-a have you tried using an empty/non-existent directory?

**Comment by ramya-rao-a** [comment]
![image](https://cloud.githubusercontent.com/assets/16890566/18963765/1e031f44-862b-11e6-8f5d-f9cbaff53fde.png)

**Comment by joaomoreno** [comment]
Somehow the relative path in Windows is being taken from a wrong root.

**Comment by Tyriar** [comment]
To verify:

```
code --user-data-dir ./testdir
# Open settings.json and ensure it's using correct relative path
ls ./testdir
# Ensure chromium's user data is contained within; GPUCache, Local Storage, etc.
```
