### ISSUE TITLE
Add a Duplicate to the click-menu in the explorer pane

### ISSUE THREAD

**Issue by davidfig** [Microsoft/vscode#11734]
Feature request: 

When right/ctrl-clicking on a file in the explorer, it would be helpful to have a Duplicate selection. This would copy and paste the selected file into another new file in the same directory.

My ideal would be to allow for a rename immediately after duplicate; alternatively it would just create the file with the filename-n name.

Currently this can be done with a ctrl-click copy and then a ctrl-click paste in the directory.

**Comment by ramya-rao-a** [comment]
This would be a good candidate for an extension. @bpasero thoughts?

**Comment by hashhar** [comment]
See this [extension](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-duplicate)

**Comment by davidfig** [comment]
Awesome. Exactly how I envisioned it. Thanks!

**Comment by ramya-rao-a** [comment]
Thanks @hashhar
