### ISSUE TITLE
Test Getting Started Accessibility

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#117313]
Testing #115896

- [x] anyOS @isidorn 
- [x] anyOS @gregvanl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23117313%0A%0A)

---

This iteration we worked on improving the accessibility of the getting started editor, please verify that it is keyboard navigable and able to be understood with a screen reader.

1. Opened via `Help => Getting Started`
2. Opened via `"workbench.startupEditor": "gettingStarted"` on a new window

**Comment by isidorn** [comment]
Great progress from when I tried it out last time, though I could still find a couple of issues.
