### ISSUE TITLE
Untitled file keeps opening up on vs code startup or when no files are opened in untitled workspace

### ISSUE THREAD

**Issue by jojijoy15** [microsoft/vscode#117316]
Steps to Reproduce:

1. Open vs code
2. Add folder to untitled workspace
3. Open some files from the added folder
4. Close the vs code
5. Open the vs code again. It will have a new untitled file opened up.
6. Try to close the untitled file. Ask for save. Click `Dont save`. It will close the `current untitled file` and open a `new untitled file`

**Note:**
  1. I have set `Workbench: startupEditor` value to none. Still this happens. 
  2. Tried disabling extensions still the problem persists.
  3. When no files are open in an untitled workspace an untitled file keeps opening up, even when we try to close them.

#### My configuration 
```
  Version: 1.53.2
  Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
  Date: 2021-02-11T11:48:44.518Z
  Electron: 11.2.1
  Chrome: 87.0.4280.141
  Node.js: 12.18.3
  V8: 8.7.220.31-electron.0
  OS: Linux x64 5.4.0-65-generic
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I cannot reproduce when I configure this setting: `"workbench.startupEditor": "none"`

**Comment by jojijoy15** [comment]
Can you try the updated steps.

**Comment by bpasero** [comment]
I tried your steps, no repro for me:

![recording](https://user-images.githubusercontent.com/900690/108819251-e87ff980-75ba-11eb-8f1a-70e3f9cb7316.gif)

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jojijoy15** [comment]
No in the code insiders this problem doesn't seem to exist. But it exists in code version 1.53.2. I don't understand why I cant close the untitled files. Whenever I close them a new one pops up.

![vscode-recurring-file-open](https://user-images.githubusercontent.com/21302850/108899045-f4f96600-763d-11eb-8dfc-31afc5ec80e9.gif)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jojijoy15** [comment]
Hi,  here's the `gif`. I ran `code --disable-extensions` from an external terminal as you suggested. Still the problem persists. Please check `gif` 

![vs-code-terminal](https://user-images.githubusercontent.com/21302850/108960744-66680180-769c-11eb-8571-7062e724f76a.gif)

**Comment by bpasero** [comment]
@jojijoy15 you started with `--disable-extension` but it is `--disable-extensions`

**Comment by jojijoy15** [comment]
Yep Got it, thanks for the fix. I will check the extension. There doesnt seem to a problem now. Thanks for all the help.
