### ISSUE TITLE
Julia documentation highlighting

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#117388]
Testing #117283

Cloned this repo - https://github.com/JuliaLang/julia
Opened https://github.com/JuliaLang/julia/blob/3230aef393d23a75d6ad5793ca4ca2f8feb62f65/base/array.jl#L5
Looks like there is a documentation syntax with `"""` and I am wondering whether this should be coloured as comments

**Comment by aeschli** [comment]
Moved to https://github.com/JuliaEditorSupport/atom-language-julia/issues/241
