### ISSUE TITLE
Cannot use --goto parameter with paths that include a drive letter with a colon :

### ISSUE THREAD

**Issue by JordanMandel** [Microsoft/vscode#11731]
- VSCode Version: 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877)
- OS Version: Windows 10 14393.0.160715-1616

Steps to Reproduce:

1. Open a file with vscode, adding the --goto or -g parameter to navigate to a specific line number. Be sure to include the drive letter with a colon (:) in the path specified

Result: Failure to open file and an error:

```
C:\> code --goto C:\TestFile.txt:12
Arguments in `--goto` mode should be in the format of `FILE(:LINE(:COLUMN))`.
```

Whereas using a relative path that doesn't include the colon:
`C:\> code --goto .\TestFile.txt:12`
 is successful in opening the file.

It looks like commit c2da84de3ae965b4d3b093521c5c37eee94dcd8d caused the issue with a bad regular expression:
```
if (args.goto) {
    args._.forEach(arg => assert(/^[^:]+(:\d+){0,2}$/.test(arg), localize('gotoValidation', "Arguments in `--goto` mode should be in the format of `FILE(:LINE(:COLUMN))`.")));
}
```

**Comment by bpasero** [comment]
@joaomoreno I did not add the validation code there

**Comment by joaomoreno** [comment]
Oh, sorry, didn't read the issue until the end.

**Comment by joaomoreno** [comment]
Workaround: use relative paths for now. Or use the next build of insiders.

**Comment by bpasero** [comment]
@joaomoreno thanks 👍

**Comment by MeTaNoV** [comment]
@joaomoreno I still have the issue on 1.11.0, but the funny things is that it only happens with `cmd.exe` and not PowerShell or the Git Bash...
