### ISSUE TITLE
Ctrl+K, Ctrl+U does not work

### ISSUE THREAD

**Issue by slobo80** [Microsoft/vscode#11732]
- VSCode Version: 1.5.1
- OS Version: 1511 - Win10

Steps to Reproduce:

1. Go to a commented line starting with  '//'
2. Pres Ctrl+K, Ctrl+U
3. Nothing happens
Expected:
Line is uncommented.

**Comment by ramya-rao-a** [comment]
@slobo80 This works for me and I tried with VS Code 1.5.1 in Windows 10 on a javascript file.

- Which file were you trying on?
- Did this work before in 1.4.0 for you and just stopped working with the 1.5.1 update?
- What extensions do you have installed? Does this repro when extensions are disabled? Try `code --disable-extensions`

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
