### ISSUE TITLE
Port column and Set label actions are not matching

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117389]
Testing #117250

<img width="549" alt="image" src="https://user-images.githubusercontent.com/10746682/108850589-cfd80980-75e3-11eb-9e8c-65c4344d7dac.png">

It is not clear to me that I am updating the port here

**Comment by sandy081** [comment]
Also with Local Address and Change local port 

<img width="573" alt="image" src="https://user-images.githubusercontent.com/10746682/108852861-64436b80-75e6-11eb-99f7-425a1e3bd913.png">

**Comment by alexr00** [comment]
The feedback I received on this context menu was that it should show all the actions for the row, not just the actions for the column that you right clicked on.

**Comment by sandy081** [comment]
@alexr00 I agree that we shall show all actions belong to the row and not scoped to column but issue is about the name of the actions in the context menu. It was not clear to me that `Set Label` is to change the `Port` column value in that row. Similarly `Change Local Port` is not clear to me that it is to change `Local Address` column. These actions are not reflecting the columns they are being targeted to.

**Comment by alexr00** [comment]
Changing to "Set Port Label" and "Change Local Address Port". The Set Label and Update devcontainer.json is already very long, so I will leave it as is.
