### ISSUE TITLE
Not able to edit other columns while adding the port

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117399]
Testing #117250

- Click on forward port action
- Enter the port number and tab

🐛 New row with above port got added

Expected to edit Local address column

**Comment by alexr00** [comment]
By default, we don't want to make users enter a local address. Most of the time, a good local address will be chosen by default. However, if a user hits tab, then we should let them enter a local address.

**Comment by alexr00** [comment]
Setting to the "Backlog Candidates" milestone to gauge interest in the feature.
