### ISSUE TITLE
Getting started: Watch tutorial should auto play the video once site opens

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117344]
https://github.com/microsoft/vscode/issues/117313

Click on the Watch Tutorial button. The site is opened. Video should be auto played to make this whole experience smooth. Currently user has to click one more time.

**Comment by digitarald** [comment]
Adding `?autoplay=true` to the iframe seems to work for the red tiger videos. If we don't want to autoplay videos on those pages we could add a URL param to the docs page when opened from VS Code that switched on autoplay via a JS snippet.

@ornellaalt what do you think about autoplaying the videos on the introvideo pages? It seems to make sense as the video is the primary content.

**Comment by lramos15** [comment]
Added `?autoplay=true` to the embed. Looks like that should work.
https://github.com/microsoft/vscode-docs/commit/e63948a9be052ae9309ed485354f43607d4c34b5

**Comment by isidorn** [comment]
Yeey thanks 👏  Let's add verification-needed so I verify this.

**Comment by lramos15** [comment]
1. Open command palette
2. Get Started: Open Walkthrough
3. Learn the Fundamentals
4. Lean back and learn

**Comment by isidorn** [comment]
Thanks! Verified 👏
