### ISSUE TITLE
Spurious error: [ts] Duplicate function implementation 

### ISSUE THREAD

**Issue by garthk** [Microsoft/vscode#11733]
- VSCode Version: 1.5.0-insider `4fc690be310dd02e0ab6529c0b9bf348a8b26a19`
- OS Version: macOS 10.11.6 (15G1004)

Steps to Reproduce:

0. `vscode-insiders .` 
0. Edit `src/big-file.ts`, which is too long and stuffed with unrelated concerns
0. `vscode-insiders -r src/extracted-function.ts`
0. Cut a function out of `src/big-file.ts`
0. Paste it into `src/extracted-function.ts`
0. Observe red underline under the function name
0. Select it
0. Observe error: `[ts] Duplicate function implementation.` 
0. Close `src/extracted-function.ts`
0. Re-open `src/extracted-function.ts`
0. Observe no red underline under the function name

Perhaps unrelated to #9880.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10804
