### ISSUE TITLE
vs code interface freezes a lot

### ISSUE THREAD

**Issue by saeed-sufi** [microsoft/vscode#117319]
Issue Type: <b>Performance Issue</b>

vs code interface freezes a lot. Terminal window turns black and reset back to the root directory. I only use vs code for python development. It was like this before I install tailwind and plotly extentions.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.49GB free)|
|Process Argv|--crash-reporter-id 7defe003-c447-41ae-bd38-6ce7ce5c91af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    68	  9144	code main
    0	   151	  5308	   window (flightradar.py - Pythonista - Visual Studio Code)
    0	    29	  5476	     searchService
    0	     5	  6456	     winpty-process
    0	     3	  6264	       "C:\Program Files\Git\bin\bash.exe"
    0	     9	  7640	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	     6	  8056	           "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    1	    70	  6164	             C:\Users\s.soufi\Pythonista\general_env\Scripts\python.exe c:/Users/s.soufi/Pythonista/Python_Plotly_Dash/4.Milestone/milestone.py
    3	    72	  9556	               C:\Users\s.soufi\Pythonista\general_env\Scripts\python.exe c:\Users\s.soufi\Pythonista\Python_Plotly_Dash\4.Milestone\milestone.py
    0	     5	  8052	     winpty-process
    0	     3	  9596	       "C:\Program Files\Git\bin\bash.exe"
    0	     9	  1936	         "C:\Program Files\Git\bin\..\usr\bin\bash.exe"
    0	    97	  8260	     extensionHost
    0	    36	  7228	       c:\Users\s.soufi\Pythonista\general_env\Scripts\python.exe c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\pyvsc-run-isolated.py c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\completion.py
    0	    15	  6464	         c:\Users\s.soufi\Pythonista\general_env\Scripts\python.exe c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python 3.7.0
    0	    17	  8272	         c:\Users\s.soufi\Pythonista\general_env\Scripts\python.exe c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\s.soufi\.vscode\extensions\ms-python.python-2021.2.582707922\pythonFiles\lib\python 3.7.0
    0	    13	  9324	     watcherService 
    0	    74	  7428	   gpu-process
    6	    68	  8920	   shared-process
    0	    23	  9196	   utility
    0	    13	 10100	   crashpad-handler
    0	    50	 12036	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (flightradar.py - Pythonista - Visual Studio Code)
|    Folder (Pythonista): more than 22495 files
|      File types: py(7638) pyc(7480) pyi(1620) pxd(168) h(109) txt(99)
|                  pyd(78) c(63) json(38) js(31)
|      Conf files: settings.json(1) package.json(1);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.5.9
beautify|Hoo|1.5.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
plotly-dash-snippets|Plo|0.0.5
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by saeed-sufi** [comment]
This issue got better after I disabled GPU by adding `"disable-hardware-acceleration": true` in  `argv.jspon`.

**Comment by saeed-sufi** [comment]
The problem still persist. vs code window turns white for almost a second while changing tabs. Terminal window turns totally black or white and its content would not be visible even after closing console and reopening it.

It's getting so annoying.

**Comment by deepak1556** [comment]
Can you check if the issue is present with latest insiders https://code.visualstudio.com/insiders
