### ISSUE TITLE
Unexpected tab stop in debug view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117351]
Testing #116559

Here when you tab you end up with another tab stop within the dropdown, I would expect to tab over:

![image](https://user-images.githubusercontent.com/900690/108828399-14a17780-75c7-11eb-9cce-4687b8fe53a3.png)

**Comment by isidorn** [comment]
Natively HTML sets all select elements to be tabbable to. Not sure if we want to change this.
Will not change it this milestone, however assigning to next milestone to think more about this then.

**Comment by isidorn** [comment]
Good catch Ben. I have changed our select boxes to respect the focus rules when they are inside `ActionBar`.
