### ISSUE TITLE
Getting started: next button not needed?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117342]
Refs: https://github.com/microsoft/vscode/issues/117313

I do not really see the point for the next button? Since it is the same as pressing `down` or clicking on the next item.

I suggest to either remove the next, or that clicking on next checks of the current item.

**Comment by misolori** [comment]
It's mostly there for verbosity as it's not always clear how to proceed. Some might find clicking on the next card helps but having the "next" makes it explicit.

**Comment by digitarald** [comment]
> … or that clicking on next checks of the current item.

Related to #116799.
