### ISSUE TITLE
Getting started description next not accessibile

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117335]
Refs: https://github.com/microsoft/vscode/issues/117313

The description of each box is not read by the screen reader, only the title gets read.
For example focus on the `Limitless Extensibility` button only the `Limitless Extensibility` part gets read, and not the "Extensions are...". That description is not keyboard accessible as far as I could see.
I suggest to add the description to the end of the aria label of the whole button, so that part gets read at the end

![Screenshot 2021-02-23 at 09 54 53](https://user-images.githubusercontent.com/1926584/108820960-37c72980-75bd-11eb-94a8-52cd16f35644.png)

**Comment by JacksonKearl** [comment]
Which screen reader is this? Voiceover reads them fine: 
![image](https://user-images.githubusercontent.com/8586769/108889174-ecaf1580-75c0-11eb-8874-e6a953a0a5b1.png)

**Comment by isidorn** [comment]
I have VoiceOver set to be very concise, so that must have been the reason.
I just tried with NVDA and this works fine, thus closing
