### ISSUE TITLE
TestItemWithResults is bogus

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117376]
Testing #117307

I am toying with an extension that fails all tests as soon as they are discovered. That means I consuming the `vscode.TestItem` type in order to report failure. To achieve that I need to provide `TestItemWithResults`-instances which extend `TestItem`, forcing me to recursively clone the whole existing, foreign data structure (I assume so, I didn't get it working yet). 

This is some weird kind of coupling and I think it would be much better if I can say "this test result belongs to this test item", something like `publishTestResult(item: vscode.TestItem, result: vscode.TestResult)`

My current snippet

```ts

    const onEditor = (e: vscode.TextEditor | undefined): void => {
        if (!e) {
            return;
        }
        const obs = vscode.test.createDocumentTestObserver(e.document);
        function failTests() {

            const stack = [...obs.tests];

            while (stack.length > 0) {
                const test = stack.pop()!;

                stack.push(...test.children);

                const res: vscode.TestItemWithResults = {
                    result: {
                        state: vscode.TestRunState.Failed,
                        messages: []
                    },
                    ...test,
                    children: [],
                };

                vscode.test.publishTestResult({
                    completedAt: Date.now(), results: [res]
                });
            }

        }
        failTests();
        obs.onDidChangeTest(failTests)
    };
    vscode.window.onDidChangeActiveTextEditor(onEditor)
    onEditor(vscode.window.activeTextEditor);
```

**Comment by connor4312** [comment]
The downside of `publishTestResult(item: vscode.TestItem, result: vscode.TestResult)` is that it can only associate test results with the _current_ state of tests in the workspace. If you're reading test results from a file, the results and hierarchy might not match those currently in the workspace -- there could even be tests that don't exist at all in the workspace.

I think that your 'clone' scenario is uncommon -- in most cases where results are being read from an external source, that source will provide the necessary information about the test labels, location, and hierarchy, so a consumer would not need to use the observer APIs.

**Comment by jrieken** [comment]
> in most cases where results are being read from an external source, that source will provide the necessary information about the test labels, location, and hierarchy

Doesn't that mean tests are duplicated by that? E.g I have test discovered by my local test provider/runner and now I drag in test output file from CI. I don't want to see the "foo-test" twice, right? I want the CI "importer" to associate the results with the existing tests, or am I missing something?

**Comment by connor4312** [comment]
> I want the CI "importer" to associate the results with the existing tests

Generally yes, it does this via the test ID. However, if your current branch or working directory doesn't exactly match whatever was run in CI, I don't want you to have to stash or switch branches to be able to see results in a rich way. A low-priority feature I plan is to have a "results view" (or maybe editor) which can show results independently, that would allow reliably and precisely viewing specific test results outside of the "living" tests in the explorer.

This would be similar to what the Jetbrains IDEs have:

![](https://blog.jetbrains.com/wp-content/uploads/2018/10/webstorm-test-results-in-tool-window.png)

**Comment by sbatten** [comment]
> The downside of `publishTestResult(item: vscode.TestItem, result: vscode.TestResult)` is that it can only associate test results with the _current_ state of tests in the workspace. If you're reading test results from a file, the results and hierarchy might not match those currently in the workspace -- there could even be tests that don't exist at all in the workspace (imagine opening test results that ran in CI somewhere)
> 
> I think that your 'clone' scenario is uncommon -- in most cases where results are being read from an external source, that source will provide the necessary information about the test labels, location, and hierarchy, so a consumer would not need to use the observer APIs.

After reading this, I still don't understand why it is the way it is. You say that we can only associate with test items in the current workspace state but then say imagine that we have items that are not in the current state. If the current limitation is to associate with existing ids, I should not need to anything more than provide an id and the updated values, yes?

**Comment by connor4312** [comment]
>  If the current limitation is to associate with existing ids

This is not a limitation. We'll record test results that extensions provide regardless, but in the _current_ UI the results are only visible when there's a "living" test that matches on of the results, displayed either in the test explorer or inline decorations.

In future UI, I want to be able to view test results individually and completely, like how Jetbrains does in their screenshot. Because test results request a complete TestItem, we will be able to display this. If we only accepted `[id, result]` tuples, then we couldn't do this: if there are IDs that don't exist in the current workspace, we would have no idea how to display. Similarly if we took `[TestItem, result]` tuples it would only ever be possible to publish results for tests that are currently in the workspace, so examining external test results would be unreliable.

**Comment by sbatten** [comment]
Those are 2 separate cases though, right? If you already have a TestItem for me, I should only need to provide the options that I want to update. Right now the API lets me provide a duplicated TestItem with an arbitrary structure and just ignores it. It seems that you are storing the results provided regardless if you can display them, so if the extension doesn't provide a complete picture, can't you just skip displaying them as you do today?

**Comment by connor4312** [comment]
> if the extension doesn't provide a complete picture, can't you just skip displaying them as you do today?

I'm not sure I understand how this would work, can you clarify? I.e. today we demand a complete picture by requiring test items. Are you saying we would accept either IDs or items `string | TestItem`?

**Comment by connor4312** [comment]
Oh, I think I see what Joh was meaning about `publishTestResult(item: vscode.TestItem, result: vscode.TestResult)`. My mind was in the mode where we would require instance identity in the TestItem like we do in the "run" api. But if we just accept the standard TestItem there and form whatever "item with results" structure internally, that would make it easier for consumers 👍

**Comment by sbatten** [comment]
right now the api accepts the same type of interface that is provided to the users, but these values are readonly. instead, perhaps the publish api could:
* accept a light version of test item that doesn't require all the values. if the recorded version doesn't have everything needed to display, its stored until all the data is given
* alternatively, , the api could be more clear in that it splits publishing additional test results with updating existing ones (though again the api talks about results but allows other changes to the test item)

**Comment by connor4312** [comment]
Ah, yea. Properties like runnable/debuggable aren't relevant for test results and are optional, but it would still be cleaner to omit those. Then they can be derived from the living test, if any.

Kai also mentioned that the naming between a TestItem and the "snapshot" version in results was somewhat confusing.

**Comment by connor4312** [comment]
Having a `publishTestResult(item: vscode.TestItem, result: vscode.TestResult)` method would mean that we have it on some "test result builder" object, or have another way to associate the result with a specific run. The builder approach could work, and would also naturally provide a way to represent an ongoing test run rather than just publishing state, after-the-fact results.

We could actually use part of the same interface we use for `runTests` if we build the API like so:

```
export namespace test {
	// not sure what the name should be, but:
	export function applyTestRun(fn: (builder: TestResultBuilder) => Thenable<void>): Thenable<void>;
}

export interface TestResultBuilder<T = TestItem> {
	setState(test: T, state: TestState): void;
}
```

then we can get rid of the separate interface and also pass in the builder to `testProvider.runTests()`

```
runTests(options: TestRunOptions<T>, results: TestResultBuilder<T>, cancellationToken: CancellationToken): ProviderResult<void>;
```

An API like that would sort of lend to something where we could have an `onDidRequestTestRun` event where extension call `applyTestRun` themselves. This would be a fairly nice approach, but has downsides that:

- Once again extensions need to be able to figure out if they're able to run the requested tests, and not have false positives or that will lead to a pretty poor experience
- If we request a test run, do we ever need some way to figure out when it's done? That's no possible with an evented approach since extensions could delay calling `applyTestRun` an arbitrary length of time.

**Comment by jrieken** [comment]
I am wondering why a test item isn't identified by its source location? Shouldn't that make it easier to associate a result with a test? Are there tests that cannot be linked to a file & range?

**Comment by connor4312** [comment]
Depending on how 'test items' are organized, possibly. If they're file-based, they may not have specific locations.

More importantly, though, we don't want to have test states/results be cleared as soon as you put a line break in a file and move their location.

**Comment by connor4312** [comment]
Yea, we only trigger a reveal for tests that have an associated location

**Comment by connor4312** [comment]
Talking with Kai in my 1:1 I realized that we could actually get some good benefit by removing the 1:1 requirement for run tests. For example, even if I have a single 'runner' extension, it might want to report multiple sets of results -- for example a saucelabs runner that executes across many different environment.

Separating runners would be useful. Runners would still have to dedupe and avoid running tests they don't "own". One way around that would be having a `provideTestRunners` or some similar method on the test provider interface, though these are not static objects.

**Comment by connor4312** [comment]
This API has changed and improved quite a bit at this point,
