### ISSUE TITLE
Should Home/End, PageUp/PageDown also navigate in actions?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117350]
Testing #116559

You can arrow left/right to navigate in actions, but should PageUp/PageDown and Home/End also work? They do work in tab stripe.

**Comment by isidorn** [comment]
Yeah I like this suggestion. We can add it next debt week.

**Comment by isidorn** [comment]
I could not make pageUp and pageDown work in the tab title list. Also not sure how much it makes sense with the toolbar.
Also the toolbar example from here only implements the home/end functionality https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html
So I will also only support Home/End

**Comment by isidorn** [comment]
To verify: make sure that the `home` and `end` navigate the first and last item in the actionBar respectively.
And that the previous tab list navigation works as expected.

**Comment by isidorn** [comment]
Fixed via
