### ISSUE TITLE
Insider builds should use Native Notebooks as deafult

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117454]
This way when users open an ipynb even before extension actiavtes, it will open in notebook.
Else it will fist open in plain text, then extension activates & then we add settings into settings.json so that it always opens in notebook Editor.

For Stable VS Code we can ensure it is optional & for insider builds we make it the default.
I.e. pre-build just udpate the package.json file, just as we do today for updating of other files (pre-build).

**Comment by rebornix** [comment]
Not sure if I understand the problem. VS Code checks the content provider contribution to decide if a file should be opened with notebook editor, other than checking its own distro. If we want `ipynb` file to be opened by notebook editor always in Insiders, then its package json should contribute the content provider as `priority: default` then it will activate the extension first, and then open the document in notebook, other than text editor.

**Comment by DonJayamanne** [comment]
Ooops, wrong repo.
Apologies
