### ISSUE TITLE
Blank terminal after split and reload

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117432]
Testing #117265

Possibly the same thing as https://github.com/microsoft/vscode/issues/117363, but I very reliably see a blank terminal after I:
1. Split terminal
2. Run a command in only one of the terminals
3. Reload window

![blank_terminal](https://user-images.githubusercontent.com/3672607/108874871-735bf680-75b1-11eb-9393-00c2f73f00bc.gif)

Resizing the terminal causes the other prompt to appear again

**Comment by eamodio** [comment]
FWIW, this works fine for me on Windows.

**Comment by Tyriar** [comment]
Likely a duplicate of https://github.com/microsoft/vscode/issues/117363

**Comment by meganrogge** [comment]
Interesting, I was able to repro and about two minutes later the blank terminal got the expected data and became responsive

**Comment by Tyriar** [comment]
It seems the replay is never getting to the renderer, I'm guessing it's firing before a listener is set up
