### ISSUE TITLE
Application froze, but not shown in Task Manager after moving from downloads to application folder

### ISSUE THREAD

**Issue by annavosbigian** [microsoft/vscode#117428]
- VS Code Version: 1.54.0-insider (Apple chip)
- OS Version: 11.1 (Apple chip)

Steps to Reproduce:

1. VSCode was open
2. Moved the application from downloads folder to Application folder
3. VSCode stopped working, selected quit
4. Tried opening a README file with VSCode
5. VSCode opened, but didn't show up in the dock and when I hovered my mouse over the app window, it turned into the spinning wheel
6. Tried to force quit, but VSCode didn't show up

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Can follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash report.

Also do you see the issue when you avoid steps `1, 2` and instead open after moving the application.
