### ISSUE TITLE
Reduce padding for webview rendered markdown markdown cells

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117493]
Split from #117423

1. With `"notebook.experimental.useMarkdownRenderer": true`
2. Open a notebook with a markdown cell

**Bug**
The cells have a lot of extra padding compared to when `useMarkdownRenderer` is false

 ![image](https://user-images.githubusercontent.com/35271042/108867384-fd07c600-75a9-11eb-9a03-4c747e1ae97d.png)

**Comment by misolori** [comment]
Related to this, because the padding is off the folding is not centered:

Left is w/ the webview renderer vs Right default
![image](https://user-images.githubusercontent.com/35271042/109066318-bf866400-76a1-11eb-8c0c-5d21d961d896.png)

**Comment by mjbvz** [comment]
Worth noting that the existing markdown implementation also does not always focus the folding indicator:

![Screen Shot 2021-03-04 at 7 03 30 PM](https://user-images.githubusercontent.com/12821956/110061381-5c897280-7d1c-11eb-8048-786e53d98e7a.png)

I'm going to make it consistent with the existing code

**Comment by mjbvz** [comment]
Here's the result after the fix. Left is new, right is old:

![Screen Shot 2021-03-04 at 8 05 05 PM](https://user-images.githubusercontent.com/12821956/110065846-fa813b00-7d24-11eb-9b8d-f2a7ab321739.png)


They are pretty close (although not perfect). Instead of making them exactly match, at this point I think we should focus on tweaking the  new markdown renderer to look its best since it will eventually become the default
