### ISSUE TITLE
Suggestions for context menu actions and grouping

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117410]
Testing #117250

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/10746682/108858731-c56e3d80-75ec-11eb-913e-eb655820874d.png">

Seems actions ordering and groups are broken and confusing to me. I would suggest to have edit column actions together, open actions together, copy actions together and remove/add actions together

```
- Open in Browser
- Preview in Editor
------
- Copy Local Address
------
- Change Port
- Change Port and Update devcontainer.json
- Change Local Address
-----
- Stop Forwarding Port
- Forward a Port
```

**Comment by sandy081** [comment]
Its also fine, if Stop Forwarding Port action is moved to Change group.

**Comment by alexr00** [comment]
Will change it to:

```
- Open in Browser
- Preview in Editor
------
- Set Label
- Set Label and Update devcontainer.json
------
- Copy Local Address
- Change Local Address
---
- Stop Forwarding Port
- Forward a Port
```

**Comment by alexr00** [comment]
How the new ordering looks:
![image](https://user-images.githubusercontent.com/38270282/108868622-ae344d80-75f6-11eb-990d-d16f0f0b0102.png)
