### ISSUE TITLE
`Actionbar has failed` on hover, although test passed

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#117457]
Testing #117305

I ran both tests under the `ActionBar`: `prepareActions()` and `hasAction()`. The viewlet says each of them passed, but when I hover over the Actionbar or prepareActions() in the code, it says they've failed. See the `Actionbar has failed` message in the screenshot below:

![image](https://user-images.githubusercontent.com/25310137/108896088-4b788d00-75c9-11eb-96cb-abb03374ff8d.png)

Should I be getting these failure messages upon hover? Are they independent of the tests I just ran that passed?

This is my first time using the selfhost test provider - if this is a user error/understanding issue, please let me know!

**Comment by connor4312** [comment]
Going to merge with https://github.com/microsoft/vscode/issues/117429
