### ISSUE TITLE
'Select a language' text overlaps with minimap

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117485]
Testing #117253

1. With `"workbench.editor.untitled.hint": "text"`
2. Enable the minimap
2. Open a new untitled file
3. Shrink the editor down to that the `select a language ...` text wraps

**Bug**
The `select a language` text ends up slightly overlapping with the minimap:

![Screen Shot 2021-02-23 at 1 04 30 PM](https://user-images.githubusercontent.com/12821956/108907993-aca75d00-75d7-11eb-981b-fee3528a1e31.png)

**Comment by isidorn** [comment]
Yeah this also happens for regulard editor content.
Will not fix for now. If we decide to go with this approach then I can look into fixing it.
