### ISSUE TITLE
Show errors in the files explorer

### ISSUE THREAD

**Issue by akshaymagapu** [Microsoft/vscode#11749]
- VSCode Version: 1.5.1
- OS Version: Windows 7

Steps to Reproduce:
1. Type some error code in typescript file
2. shows redline near the error

-Better if it shows error near the filename also.

**Comment by ramya-rao-a** [comment]
@akshaymagapu near the filename where?

**Comment by whitecolor** [comment]
He means in Explorer's file tree. Better if this would be optional of course, but this would be very useful, as well as reflecting other file statuses (git status/exclusion, etc)

**Comment by akshaymagapu** [comment]
@ramya-rao-a @whitecolor   Yeah in Explorer's file tree.

**Comment by Attrash-Islam** [comment]
+1 for adding this feature

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/782
