### ISSUE TITLE
My extension broke the account menu

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117463]
Testing #117299

I have a simple auth provider that returns an empty array for `getSessions`. When I click the Accounts menu in the activity bar, nothing happens. When my auth provider is not registered, then it opens up and shows my github and msft accounts as usual.

![recording (2)](https://user-images.githubusercontent.com/323878/108898737-6dbfda00-75cc-11eb-94c4-e60ac674e986.gif)

Here's my extension code:

```ts
export async function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('extension.helloWorld', async () => {
		const s = await vscode.authentication.getSession('testAuthProvider', ['some scope'], { createIfNone: true });
		console.log(`Got ${s}`);
	}));
	vscode.authentication.registerAuthenticationProvider('testAuthProvider', 'My Cool Auth Provider', new AuthProvider());
}

class AuthProvider implements vscode.AuthenticationProvider {
	private _onDidChangeSessions: vscode.EventEmitter<vscode.AuthenticationProviderAuthenticationSessionsChangeEvent> = new vscode.EventEmitter();
	onDidChangeSessions: vscode.Event<vscode.AuthenticationProviderAuthenticationSessionsChangeEvent> = this._onDidChangeSessions.event;

	async getSessions(): Promise<readonly vscode.AuthenticationSession[]> {
		console.log(`getSessions`);
		return [];
	}

	async createSession(scopes: string[]): Promise<vscode.AuthenticationSession> {
		console.log(`createSession ${scopes}`);
		return {
			accessToken: 'accessToken',
			account: {
				id: 'me',
				label: 'My Account'
			},
			id: 'sessionId',
			scopes: [...scopes, 's1']
		};
	}

	async removeSession(sessionId: string): Promise<void> {
		console.log(`removeSession: ${sessionId}`);
	}
}
```

**Comment by roblourens** [comment]
Even if I return some session, it seems like the same thing happens.

**Comment by roblourens** [comment]
I noticed this error in devtools:

![image](https://user-images.githubusercontent.com/323878/108900633-afea1b00-75ce-11eb-8b76-f982f648f410.png)

But there is an auth provider with that id...

**Comment by RMacfarlane** [comment]
Ah, there's also a way to add a package.json contribution declaring an auth provider, which I was using to populate a list of auth providers immediately on `vscode.authentication`. That API didn't make it into stable but there are some traces of it I need to remove, this was trying to use the label from that. Nice catch!
