### ISSUE TITLE
'Select a language' text can end up overlapping with the scrollbar

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117484]
Testing #117253

1. With `"workbench.editor.untitled.hint": "text"`
2. Open a new untitled file
3. Shrink the editor down to that the `select a language ...` text wraps

**Bug**
The `select a language` text ends up overlapping with the scrollbar

![Screen Shot 2021-02-23 at 1 02 09 PM](https://user-images.githubusercontent.com/12821956/108907772-5c2fff80-75d7-11eb-98b6-e3cab7ae0b64.png)

**Comment by isidorn** [comment]
Yeah, regular editor content also overlaps with the scroll bar.
So this is not something I would fix for now, thus closing
