### ISSUE TITLE
Incorrect expansion state on Test suite

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#117471]
Testing #117305

See the screenshot below, the expansion state is shown as collapsed when it should be expanded
![image](https://user-images.githubusercontent.com/172399/108901679-74297280-761b-11eb-8b2d-333ea3dbc1db.png)

To reproduce
- Collapse the Array test suite
- In the filter box type 'first'
- Expand the Array test suite
--> the expansion state is incorrect

**Comment by connor4312** [comment]
It seems like there's something funny happening in the tree. This line ends up returning undefined when asking to re-render the twistie

https://github.com/microsoft/vscode/blob/1550171b26fe057f517bc3ac50638a326c7c26fb/src/vs/base/browser/ui/tree/abstractTree.ts#L391

and looking at the keys of `renderedNodes`, there are quite a few things missing, [for example](https://memes.peet.io/img/21-02-a1ae6dec-d336-4b8a-9a15-97c3491fcac6.png). This happens even if the diff identity provider isn't given, so I don't think it's related to my earlier changes.

Looking further, I see that the correct data is given into `listView.splice()`, including the missing "async". But while I see "async" does get rendered, it later gets disposed on [this line](https://github.com/microsoft/vscode/blob/1550171b26fe057f517bc3ac50638a326c7c26fb/src/vs/base/browser/ui/list/listView.ts#L524).

The `listView.items` array is correct and based on `this.getRenderRange(this.lastRenderTop, this.lastRenderHeight)` it _should_ be rendered, but `renderedNodes` has much fewer nodes than there should be.

fyi @joaomoreno

**Comment by joaomoreno** [comment]
Very likely it's this: https://github.com/microsoft/vscode/issues/116788

I've pushed a fix, can you check our of dev @connor4312?

**Comment by connor4312** [comment]
works for me in OSS, thanks! Will mark this as duplicate
