### ISSUE TITLE
toggleExplainMode stopped working

### ISSUE THREAD

**Issue by aditya-keri** [microsoft/vscode#117431]
- VS Code Version: 1.53.2
- OS Version: MacOS Catalina 10.15.7

Steps to Reproduce:

1. I add a variable. Add a dot (.) and then the suggestions come up.
2. When I do a `cmd + /`, it doesn't show the explain block anymore

It was actually working fine until a few hours ago. But then it suddenly stopped working.
I've tried completely uninstalling and installing vscode. I've tried this on a windows PC as well.
Same issue. I'm unable to toggle to explain mode anymore

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Maybe use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to check whether you somehow bound that keystroke to something else

**Comment by aditya-keri** [comment]
I tried the troubleshooting from above and I see that the keybinding is being detected. But the explain dialog box just doesn't appear.

![image](https://user-images.githubusercontent.com/49429259/108945792-411ac980-7683-11eb-8cc6-83d098b54810.png)

**Comment by aditya-keri** [comment]
Okay I got it to work now, I have no idea how. I didn't make any changes. It just started working again.

But can someone please tell me why these methods that I've added to completionItems list have a score of -100 ?
Because of this score, the methods are actually appearing at the bottom and global identifiers are at the top.
![image](https://user-images.githubusercontent.com/49429259/108954644-086bf780-7665-11eb-92b9-a99741e23683.png)

**Comment by jrieken** [comment]
The details widget must be visible for this work
