### ISSUE TITLE
Make added, removed, changed, optional in auth session change event

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117469]
Testing #117299

Minor thing, but implementing this, I noticed that it would be nice for added, removed, and changed, to be optional properties on the change event that the extension has to construct, because it's likely that only one of them is relevant at a time.

https://github.com/microsoft/vscode/blob/67ded11020014caf9f9627f3756d398adaeae848/src/vs/vscode.d.ts#L12352-L12352

**Comment by RMacfarlane** [comment]
Makes sense to me, but we seem to have a pattern of requiring these on other change events. For example `BreakpointsChangeEvent` and `WorkspaceFoldersChangeEvent` also have added/removed as required. @jrieken @mattbierner Any thoughts on this/historical reasons? Do we care about being consistent with these?

**Comment by jrieken** [comment]
I think it makes sense. The difference between `BreakpointsChangeEvent` and `AuthenticationProviderAuthenticationSessionsChangeEvent` is that the latter is created by us (and therefore should be complete and easy to work with) and the former is provided by the provider (and therefore should be easy to construct). This goes along the lines of this: https://github.com/microsoft/vscode/wiki/Extension-API-guidelines#strict-and-relaxed-data
