### ISSUE TITLE
Open in browser without a running process

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#117433]
Testing #117250

When I right click on a port with no running process, clicking `Open in browser` results in a 502 bad gateway error after loading for awhile.

I'm wondering if that option should be greyed out in the menu for ports without running processes?

**Comment by alexr00** [comment]
Interesting point! However, there are situations where we might not detect a running process, but there actually is one. If a user wants to connect to a port even when their application isn't running I don't think we should stop them.
