### ISSUE TITLE
Vertical Rulers off by 1

### ISSUE THREAD

**Issue by BillSkiCO** [microsoft/vscode#117462]
Running: Version 1.50.1

Within settings.json,

` "editor.rulers": [
    80, 120
    ]
`
results in the vertical ruler being rendered at the end of column 81 and column 121 instead of at the expected end of column 80 and 120

**Comment by IllusionMH** [comment]
Ruler is placed after given number of characters. So when you have `80` it means that length of string to the lest of ruler in 80 characters.

If you are saying that they are shifted based on status bar  - Col in status bar represents "start" of next character (if show 1 at the start of the string, 81 after 80 characters).

Do you see something different?

P.S. latest VS Code version is 1.53.2
