### ISSUE TITLE
Up/Down arrow keys don't work with collapsed viewlets

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117440]
Testing #116559

The up and down arrow keys don't switch focus in this case. Tab or Shift+Tab work.

![collapsed-panel](https://user-images.githubusercontent.com/7199958/108881919-ad7cc680-75b8-11eb-8c60-cd2413030cb6.PNG)

**Comment by isidorn** [comment]
Yeah I think this is a feature request against the split view. Which I think makes sense: up / down should move focus between collapsed views.
Assigning to @joaomoreno
