### ISSUE TITLE
Gitlens tab focus seems off

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117442]
Testing #116559

I'm unable to navigate to any of the actions within the focused area.

![gitlens-focus](https://user-images.githubusercontent.com/7199958/108884482-8378d380-75bb-11eb-8a0d-5ad454becf7e.PNG)

**Comment by isidorn** [comment]
This works for me, here are my steps:

1. Insiders, install git lens
2. Open the Commits view and focus title area, notice the focus outline
3. Press tab -> focus moved to actions

Do you do something differently?

**Comment by rzhao271** [comment]
It works fine for me after a reload. Previously, it was going straight to the commits.

**Comment by isidorn** [comment]
@rzhao271 okey, let me know if you find steps. For now closing this, and if you see it again let me know and I will reopen.
