### ISSUE TITLE
*.ipynb files alway opens in plain text editor & not Notebook Editor in latest insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117445]
- VS Code Version: Latest VSCode Insiders
- OS Version: Mac

Steps to Reproduce:

1. Install latest VS Code insiders
2. Install jupyter extension (2021.3.xxx)
Open an ipynb file and it will open as a text file.
FYI - in yesterdays insiders this would open the notebook, now it opens plain text editor.
We also add the followign into the settings file:
```typescript
	"workbench.editorAssociations": [
		{
			"viewType": "jupyter-notebook",
			"filenamePattern": "*.ipynb"
		}
	],
```

Looks like the latest insiders broken something here.

@rebornix @jrieken /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/8e8c6a07dfe31b6614854d72ee876b2cced12da6
