### ISSUE TITLE
Authentication prompt when requesting session from the same extension

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117486]
Testing #117299

It might be by design but it's weird to me that registering the authentication provider and requesting sessions from it prompts

![image](https://user-images.githubusercontent.com/876920/108910772-2d1b8d00-75db-11eb-9b00-f01a05c1c03b.png)

**Comment by RMacfarlane** [comment]
I think this is working as intended - even if the extension is the same one, the user should still see a dialog letting them know what is about to happen
