### ISSUE TITLE
Too many places to contribute icons

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117492]
Testing #117263

So we have product icon themes that can be defined via `theme.json` like:

```jsonc
{
	"fonts": [
		{
			"id": "fluent-icons",
			"src": [
				{
					"path": "./fluent-icons.ttf",
					"format": "truetype"
				}
			],
			"weight": "normal",
			"style": "normal"
		}
	],
	"iconDefinitions": {
		"files": {
			"fontCharacter": "\\2710"
		},
		"search": {
			"fontCharacter": "\\2711"
		},
		"source-control": {
			"fontCharacter": "\\2712"
		},
		...
	}
}
```

And now we also have product icon contributions that are defined in the `package.json`
```jsonc
"iconFonts": [
      {
        "id": "fluent-icon-font",
        "src": [
          {
            "format": "truetype",
            "path": "./theme/fluent-icons.ttf"
          }
        ]
      }
    ],
    "icons": [
      {
        "id": "fluent-logo",
        "description": "Fluent logo",
        "default": {
          "iconFontId": "fluent-icon-font",
          "character": "\\f101"
        }
      },
      ...
```

Each file uses a different naming structure for IDs, font characters, and I see there are duplications with paths. It would be nice if these were all consolidated to reduce the opportunity for user error.

**Comment by aeschli** [comment]
There's also file icon themes with a format similar to the product icon themes. Both are public API.

I see that we we use `fontCharacter` and `character`. That we can streamline. We can also use `fontId` at both places (for icon themes `fontId` is optional as it default to the first defined font).

The font declarations are identical. But icon fonts are never shared. In fact we prevent that by giving them unique internal names.  See https://github.com/microsoft/vscode/issues/114942#issuecomment-773479706 for the reasoning why sharing icon fonts is not preferable.
So I'm not sure what you mean by the duplication of paths.

Icon definitions and icon themes are two different things and have different target audiences (extension authors vs theme authors).
