### ISSUE TITLE
No visual indicator that cells have been multiselected

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117449]
Testing #117295

1. Open a github issues notebook file
2. Shift + click to multi-select cells

I'm not seeing any indicator that a cell has been multiselected, but I do see the `vscode.window.onDidChangeNotebookEditorSelection` event getting firing on click

![try_multiselect](https://user-images.githubusercontent.com/3672607/108891773-f38b5780-75c3-11eb-9191-6cede2ba6829.gif)

**Comment by meganrogge** [comment]
Seeing this also

**Comment by rebornix** [comment]
Verifier:

Please test against non default dark/light theme, e.g., Monokai.

**Comment by roydukkey** [comment]
Just wanted to verify this isn't a mistake, as it appears the defaults are here are not equivalent:

https://github.com/microsoft/vscode/blob/07340c27f59b922bfcb8cf841e394df5981ff725/extensions/theme-defaults/themes/dark_vs.json#L22

https://github.com/microsoft/vscode/blob/07340c27f59b922bfcb8cf841e394df5981ff725/extensions/theme-defaults/themes/light_vs.json#L25

https://github.com/microsoft/vscode/blob/3dd2d431a01ab750a59d8be5d291e099778649bf/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2270-L2271

I would expect equivalency between `Color.fromHex('#383B3D').transparent(0.5)` and `#383B3D80`.
