### ISSUE TITLE
Can't drag in full width of markdown notebook cell

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117489]
Split from #117423

1. With `"notebook.experimental.useMarkdownRenderer": true`
2. Open a notebook with a markdown cell
3. Try clicking and dragging to the left of the markdown cell

**Bug**
There's a gap where you can't actually drag the cell

**Comment by mjbvz** [comment]
@rebornix To fix this, we will need to make the back layer webview take up the entire width of the editor. Currently it has a large left padding:

<img width="679" alt="Screen Shot 2021-02-25 at 5 19 40 PM" src="https://user-images.githubusercontent.com/12821956/109241185-c2f71980-778d-11eb-838a-6c719394548a.png">

**Comment by lramos15** [comment]
This still happens for me, I can't drag the left margin next to a markdown cell. I get the drag cursor but actually dragging does nothing.

**Comment by mjbvz** [comment]
This happens when you try dragging over the folding indicator

**Comment by mjbvz** [comment]
For verification, clicking and dragging on the folding indicator itself still should not work but you should be able to click below it and around it 

Keep in mind that the folding indicator also has about 5px of padding that counts as a clickable area. Dragging on the folding indicator itself feels odd (and we don't show a drag cursor when the mouse is over it)
