### ISSUE TITLE
Select a language button only works if editor is focused

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117478]
Testing #117253

1. With `"workbench.editor.untitled.hint": "button"`
2. Open the settings editor
3. Open a new untitled file next to the settings editor and confirm the select language button is shown
4. Focus on the settings editor
5. With the settings editor still focused, click the `select a language` button

**Bug**
The language picker says: `no active language at this time`

![Screen Shot 2021-02-23 at 12 48 28 PM](https://user-images.githubusercontent.com/12821956/108906207-7963ce80-75d5-11eb-8128-8a924238542f.png)

**Comment by mjbvz** [comment]
This also happens with the `language` link with `"workbench.editor.untitled.hint": "text"`

**Comment by isidorn** [comment]
Great catch, we should first focus the editor.
