### ISSUE TITLE
Problems w/Intellisense & Find Usages

### ISSUE THREAD

**Issue by brooke-poweredbyliquid** [microsoft/vscode#117466]
Issue Type: <b>Bug</b>

I use VS code to edit both typescript/angular and C#.

Since the lastest update, intellisense is SUPER slow. I've set my preferences to show intellisense after 1 ms just to be safe, and still it's taking 5-10 seconds to load, which makes it unusable.

I've tried turning off all my plug-ins, and it doesn't make a difference.

Also, trying to find references from html no longer ever finds any references, OR it just takes me to html element references. Normally, I can find references of an angular component by right-clicking in the html. Also, properties and methods used in html can no longer be found in the ts files.

When finding references w/in ts files, the results are now duplicating every reference, but not necessarily in the same order, so it's very confusing.

This had all been generally working before. I would have issues from time to time, but restarting VS code would always resolve them.

Any help would be appreciated.
~b 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.23GB free)|
|Process Argv|--crash-reporter-id 453a394b-6d51-4765-bb08-ed11d1c009a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.3
gitlens|eam|11.2.1
vscode-firefox-debug|fir|2.9.2
csharp|ms-|1.23.9
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by mjbvz** [comment]
Please share some typescript code that demonstrates the issue

For C#, open an issue against the C# extension

/needsMoreInfo

**Comment by brooke-poweredbyliquid** [comment]
For typescript, an example of the code isn't really going to help b/c it's just all code. It just hangs there and intellisense doesn't appear for 5-10 seconds

![image](https://user-images.githubusercontent.com/78448713/108916698-7b348e80-75e3-11eb-9774-11908d745b51.png)

**Comment by mjbvz** [comment]
Please share an example project that demonstrates this. That little snippet doesn't tell us enough about what could be going wrong
