### ISSUE TITLE
Remove terminal.integrated.flowControl setting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117418]
We want flow control enabled all the time now since it's been battle tested

**Comment by radekwojpl2** [comment]
I would like to ask a question about this issue, is this issue can be closed by deleting this entry from line 406 to 410?
![image](https://user-images.githubusercontent.com/62394072/109210146-4b12fa00-7761-11eb-9c91-c9082b07e64f.png)

**Comment by Tyriar** [comment]
There's a little more to it than that as flowControl is referenced elsewhere. This sort of debt/clean up item is probably better handled by the core team as we have some more context on this.

**Comment by radekwojpl2** [comment]
Thank you for a quick update, there are a lot more references than those few lines.
