### ISSUE TITLE
No connection behind proxy since update 1.5.0

### ISSUE THREAD

**Issue by KUGA2** [Microsoft/vscode#11744]
- VSCode Version: 1.5.0
- OS Version: Win7

Today i got an automatic update to 1.5.0. My User Settings were kept. Configuration:
    "http.proxy": "http://XXX:80",
    "http.proxyStrictSSL": false,

VS Code start up with an error:
   self signed certificate in certificate chain

I have no Connection to the marketplace, but it worked before the update.

**Comment by joaomoreno** [comment]
#11702

**Comment by ThorQin** [comment]
I have the same error. Since I upgrade to 1.5.0, I can not connect to market place to download extensions.
