### ISSUE TITLE
Select text popup VSCode disable setting

### ISSUE THREAD

**Issue by eldoy** [microsoft/vscode#117412]
- VS Code Version: 1.52.1
- OS Version: MacOS 10.15.6

In this version of VSCode there is a popup in the upper right corner whenever I select some text. It seems like a bug as it doesn't seem to have any function and is extremely distracting. I constantly move my eyes up there when it pops up.

If it is a feature, how do I disable it? I have disabled all other popups, this seems like something new.

Steps to Reproduce:

1. Select some text
2. Get popup in upper right corner

![annoying popup](https://i.stack.imgur.com/khiId.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
> as it doesn't seem to have any function

It appears during multiselect to indicate and allow to change how selection will treat case and word boundaries. Same as search results.
![image](https://user-images.githubusercontent.com/1312662/108890501-573e7080-7616-11eb-809e-ae9d4650948a.png)
![image](https://user-images.githubusercontent.com/1312662/108890544-63c2c900-7616-11eb-84c8-a91fd42d95c2.png)
![image](https://user-images.githubusercontent.com/1312662/108890646-8228c480-7616-11eb-8bdf-e9a7a9b963ed.png)

**Comment by eldoy** [comment]
Ah ok, so how do I disable it? It still shows when I don't do multi-select, and it's pretty useless and extremely distracting.
