### ISSUE TITLE
Unsure what behavior of `terminal.integrated.confirmOnExit` setting should be

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117436]
Testing #117265

1. Set `terminal.integrated.confirmOnExit` to true
2. Have something long-running like `yarn watch` in a terminal
3. Reload window

See prompt asking if I want to kill active terminals - my initial expectation was that I wouldn't be prompted since the terminals will be restored.

4. Click "Yes"

The terminal with `yarn watch` shows as blank for a while before eventually loading, but the title in the dropdown remains empty and I can't seem to interact with it after that, I can't interrupt it.

![confirm_on_exit](https://user-images.githubusercontent.com/3672607/108879389-1282ed00-75b6-11eb-92b4-83fd6216d58d.gif)

**Comment by Tyriar** [comment]
We should ignore `confirmOnExit` when a reload is happening and call that out in the setting docs.
