### ISSUE TITLE
classic x native always focuses menu bar

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#117447]
Testing #117275

On Xubuntu with

```
    "window.menuBarVisibility": "classic",
    "window.titleBarStyle": "native",
    "window.customMenuBarAltFocus": false,
```

The menu bar acts like customMenuBarAltFocus: true

**Comment by connor4312** [comment]
Just parsed the name of the setting -- is this expected since the menu bar focus is no longer custom?

**Comment by sbatten** [comment]
@connor4312 yes, the setting only applies to custom, maybe I could add some additional text in the description

**Comment by connor4312** [comment]
I think the property name makes it obvious... I just looked at the matrix and started iterating through the combinations without thinking about it that much.
