### ISSUE TITLE
Change untitled file link span

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117480]
Testing #117253

With `"workbench.editor.untitled.hint": "text"`, the `language` link looks odd to me:

![Screen Shot 2021-02-23 at 12 56 07 PM](https://user-images.githubusercontent.com/12821956/108907148-98af2b80-75d6-11eb-83cd-b9814691f548.png)

I suggest that the link instead include the text `Select a language` instead of just `language`

**Comment by isidorn** [comment]
That's fair. I like that the verb is also part of the link.
