### ISSUE TITLE
workbench.editorAssociations no longer respected

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117451]
Issue Type: <b>Bug</b>

User's `workbench.editorAssociations` was no longer honored after https://github.com/microsoft/vscode/commit/413963c489fafa5163b5d6513731c7953de07fb3#diff-526c9917a850212febfac51bc2e8e64da14477f791d315cb134624a8941f4d8f

This broke custom/notebook editor contribution whose `priority` is `option`. For example, if user set Hex Editor or Jupyter Editor as the default editor in the settings, files are still opened in text editor.

VS Code version: Code - Insiders 1.54.0-insider (9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea, 2021-02-23T10:46:22.816Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.55GB free)|
|Process Argv|--crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
codespaces|Git|0.7.2
vscode-pull-request-github-insiders|Git|2021.2.24175
vscode-language-pack-zh-hans|MS-|1.54.0
vscode-dotnet-runtime|ms-|1.0.0
vscode-dotnet-sdk|ms-|0.0.1
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.593162453
remote-containers|ms-|0.161.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
hexeditor|ms-|1.4.0
vscode-github-issue-notebooks|ms-|0.0.68
vsliveshare|ms-|1.0.3784
999-extension-update|reb|1.4.3
vscode-todo-highlight|way|1.0.4

(2 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
Sorry I should've opened this bug this morning as I discovered it. Ben and I accidentally renamed one of the properties from `viewType` -> `editorType`. It should still respect them if you have the setting renamed correctly, but I need to fix the wording. Try setting the setting from the gear icon in the quickpick for now.

**Comment by rebornix** [comment]
I added fallback to `viewType` for now to unblock users. The proper fix should be we update the setting to the `editorType` if we see deprecated ones but I leave that to @lramos15 .
