### ISSUE TITLE
[file icon themes]Config to assign a separate icon to *.d.ts instead of *.ts

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#11740]
- VSCode Version: 1.5.1
- OS Version: Windows 10 x64, 14393.103

When making an icon theme, currently assigning an icon to *.ts is easy, but there is no way to assign a separate icon to *.d.ts.

**Comment by mrmlnc** [comment]
> `fileExtensions` associates file extensions to icons. The key in the set is the file extension name. The extension name is a file name segment after a dot (not including the dot). File names with multiple dots such as lib.d.ts can match multiple extensions; `d.ts` and `ts`. Extensions are compared case insensitive.

**Comment by mrmlnc** [comment]
@aeschli, strange behavior.

For example, I assign `ts` to `ts: _typescript` and `d.ts` to ` _javascript` and `d.ts` files will be have TypeScript icon. But if I assign `d.ts` to `_pdf` I will see PDF icon.

**Comment by aeschli** [comment]
Oops, the . is not escaped. Will fix ASAP
