### ISSUE TITLE
Include way to hide select language button in untitled files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117483]
Testing #117253

With `"workbench.editor.untitled.hint": "button"`, I suggest that we add a simple way to hide the `Select a Language` button

![Screen Shot 2021-02-23 at 12 59 23 PM](https://user-images.githubusercontent.com/12821956/108907468-f5124b00-75d6-11eb-830c-ea4f79f7ac96.png)

We already have a `don't show again` button for `"workbench.editor.untitled.hint": "text"`:

**Comment by isidorn** [comment]
I agree with this.
Do you have some good ideas?
How about right click on button to hide?

@misolori @sana-ajani for ideas

**Comment by misolori** [comment]
Not a lot of options here as it's either adding another button or link text, which I'd suggest to remove the keyboard shortcut to reduce the long strings (you can add it in the tooltip):

## Secondary button
![image](https://user-images.githubusercontent.com/35271042/109032495-91d9f480-767a-11eb-8679-8cb5fa0997bd.png)

## Link text
![image](https://user-images.githubusercontent.com/35271042/109032537-9acac600-767a-11eb-95df-e37d95fe9a50.png)

**Comment by isidorn** [comment]
Just having more buttons in order to hide does not sound nice to me. Since it ads heavyness to this approach.
I would prefer right click hide.

**Comment by misolori** [comment]
Only problem is right-click is not very discoverable nor accessible? I'd stick with the setting for now and if we get more feedback about this then we can adjust, i don't think we do this interaction (right-click to hide) in other areas.

**Comment by isidorn** [comment]
Makes sense. However for rigth click + hide we do in status bar and split view and acitivity bar
Accessible -> not importnant imho since setting can always be changed, and this button is not accessible in the first place which I plan to fix

**Comment by misolori** [comment]
Oh, sorry I thought you meant to instantly hide it, not bring up the context menu 😄  that would be better, but how'd you bring it back once it's hidden? Editor context menu?

**Comment by isidorn** [comment]
Yeah I meant the context menu -> sorry I was not clear :)
Once it is hidden you have to go to settings and change the setting.
But I think that scenario is not important -> if you figured out how to hide -> you are a pro -> why would you want it back.

**Comment by sana-ajani** [comment]
Are we able to mimic the same behavior that the editor hint does? Can the button disappear when the user starts typing in the editor?

**Comment by isidorn** [comment]
@sana-ajani yeah, let's do that.
Though in this case we could be smarter and only hide it when the user has typed a certain amount of text.
But yeah let's auto hide, next milestone we can figure out when exactly

**Comment by mjbvz** [comment]
We use split buttons on extension pages:

<img width="351" alt="Screen Shot 2021-02-24 at 11 11 17 PM" src="https://user-images.githubusercontent.com/12821956/109242734-8547c000-7790-11eb-8bca-562496e44831.png">

Could we use the same here?

**Comment by isidorn** [comment]
We decided to go with the untitled text, not the button thus closing this
