### ISSUE TITLE
Represent the port/address that opens the application differently

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#117400]
Testing #117250

- Run a node application in dev container
- Following is seen

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/10746682/108854016-ad47ef80-75e7-11eb-8e07-c7ffa698bc80.png">

- It is not clear in ports view on which entry opens the application in browser. It would be helpful to represent the application port differently so that it can be identifiable.

**Comment by alexr00** [comment]
We don't have a way of knowing which port is the "application" port. I use a heuristic to show the notification for the "best" port, but we don't actually have a way to tell for sure which port is the "best" one to show. Frequent users of forwarded ports can set a label for their application port in settings or in the `devcontainer.json`.
