### ISSUE TITLE
Feature Request: Support for Multiple Integrated Terminals

### ISSUE THREAD

**Issue by giech** [Microsoft/vscode#11748]
It would be great if we were able to open multiple types of integrated terminals (e.g. both bash and PowerShell) in the same session. These could, for instance, be specified as semicolon-delimited paths in the `terminal.integrated.shell.windows` property, and within the terminal window we could launch a new instance either via right-clicking the "+" button, or via a dropdown menu.

Note that this is not a high-priority issue, since there is a workaround: PowerShell can launch cmd.exe and bash (including proper path translation), but it would be nice to have for alternative default terminals and configurations.

**Comment by Tyriar** [comment]
Duplicate #10893
