### ISSUE TITLE
[Notebook] Execution timer starts with negative value

### ISSUE THREAD

**Issue by jonsequitur** [microsoft/vscode#117460]
Reported in [dotnet/interactive](https://github.com/dotnet/interactive/issues/1092) by @arkada38:

### Describe the bug
I've connected to raspberry pi 4 via ssh remote and vs code on windows 10.
I see negative exacution time on each cell.

### .NET Interactive
Version: 1.0.211906+4b8eb267854eb055ef2f7b16561ebbcd6cc69b2e
Build date: 2021-02-19T20:40:06.0000000Z

- OS: Linux (Raspberry Pi OS)
- Frontend: [x] Visual Studio Code Insiders Preview with SSH Remote

### Screenshots
![time1](https://user-images.githubusercontent.com/4335913/108623163-7f7b7300-744e-11eb-98cb-18a63e65f392.gif)

**Comment by rebornix** [comment]
I guess this can happen if the `runStartTime` is in the future but we don't want to render negative time.

**Comment by roblourens** [comment]
This is something that has made me nervous - it's good to use an absolute time so we can account for network latency, but there's no guarantee that clocks are in sync.

**Comment by roblourens** [comment]
If this is going to be an issue, we should just switch to the extension saying that execution started "now" with an optional + extra running duration.

Either that or our protocol includes this https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_synchronization_algorithm

**Comment by arkada38** [comment]
> Is the raspberry pi really 3 seconds ahead though? 🤔 Is it connected to the internet?

The raspberry pi is connected to the internet.  
The issue was gone after enabling the time synchronization on the raspberry.  

`sudo timedatectl set-ntp true`

**Comment by arkada38** [comment]
![time3](https://user-images.githubusercontent.com/4335913/109106957-f01dda80-7741-11eb-9858-37a4e495a57d.gif)

**Comment by roblourens** [comment]
Thanks for trying that. I had assumed this wouldn't really be an issue, but this makes me nervous.

**Comment by roblourens** [comment]
Pushed a workaround without complicating extension API or getting rid of the feature.

I could have added another property next to `startTime` which would be the current clock time, and we could use that in all cases to figure out the initial elapsed time, but would not include latency to the EH in the timer, which would be noticeable in a lot of cases.

Or we could include some complicated algorithm to synchronize clocks between the two processes...

Instead I check whether startTime is in the future, if so, figure out the offset and add it back to the computed elapsed time. This will basically patch it for cases like that (they won't get to include the network latency time anymore, that's ok), and shouldn't change anything for the typical case.
