### ISSUE TITLE
Search within installed extensions returns results from the online lists

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#11741]
- VSCode Version: 1.5.1

Steps to Reproduce:

1. Open `Installed Extensions`. 
2. Enter a search query.

Expected Output:
Return results from within installed extensions.

Actual Output:
Returns results from all available extensions.

**Comment by octref** [comment]
I think that's working as intended. Empty query shows all installed extensions, and non-empty query searches against marketplace.

**Comment by hashhar** [comment]
Okay. Didn't pay attention to that. Thanks.
