### ISSUE TITLE
Tabs in YAML comment cause syntax highlighting to not work

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode#117407]
Issue Type: <b>Bug</b>

Tabs prevent comments from being highlighted correctly in YAML.
```
redis:
  # good comment
  enabled: true
  # 	bad comment
  image:
    pullPolicy: IfNotPresent
```

![image](https://user-images.githubusercontent.com/15629116/108858143-d6518b80-75b9-11eb-9bd2-f98e628791cf.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|32.00GB (2.57GB free)|
|Process Argv|. --crash-reporter-id 87f5170f-46d6-4287-a618-c0e8a137aff7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
go|gol|0.22.1
vscode-docker|ms-|1.10.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by alexr00** [comment]
Since we get our yaml syntax highlighting grammar from another repo, I have opened an issue there: https://github.com/textmate/yaml.tmbundle/issues/36
