### ISSUE TITLE
Unable to tab into terminal side buttons on Windows

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117438]
Testing #116559

I have screenreader mode enabled.
After getting focus on the textbox, pressing tab doesn't focus on any of the buttons to the right of it. For example, pressing space or enter doesn't trigger any actions. However, pressing tab once more focuses on the terminal.

![terminal-side-buttons](https://user-images.githubusercontent.com/7199958/108881166-e1a3b780-75b7-11eb-9cf9-b8843ff5c6a8.PNG)

**Comment by Tyriar** [comment]
@isidorn made a change so that you access the panel actions with left/right, so you can no longer tab from the dropdown to the buttons.

**Comment by isidorn** [comment]
Let me get this steps clarified:
* you click on the select box and close it leaving focus there
* you press tab -> focus moves to terminal

This is expected. Since left - right move should move focus to the other actions there. Or you do not see that?

**Comment by rzhao271** [comment]
Just found out that left/right moves to the other actions there. That means there's an extra tabstop between those actions and the terminal.

**Comment by isidorn** [comment]
The extra tab stop is covered by this issue https://github.com/microsoft/vscode/issues/117353
Since action navigation seems to work as expected I will close this.
Feel free to reopen if I missed something here
