### ISSUE TITLE
VS Code winget install is missing product icon on certain launch

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#117439]
Testing #117222

Install VS Code using `winget install vscode-system-x64`. On first launch (and most launches), everything appears & functions fine.

Launch VS Code another time, notice the icon is blank:

![image](https://user-images.githubusercontent.com/25310137/108881065-c638ac80-75b7-11eb-90de-d3afd4d30680.png)

I close VS Code and launch again, and the icon returns.

![image](https://user-images.githubusercontent.com/25310137/108881483-37785f80-75b8-11eb-8afb-45fcce1577bb.png)

I'm not sure if this was a glitch on my computer or could come from the winget installation, so I figured I'd report.

**Comment by lszomoru** [comment]
Thanks! I do not believe that this is related to WinGet but I will keep an eye out for other reports.

**Comment by lszomoru** [comment]
Closing the issue as I did not see other reports of this issue.
