### ISSUE TITLE
 something that says Shift and Click to select more cells

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#117465]
Testing #117295

When I hold down shift in a notebook, it would be nice to see `Shift + Click to select more cells`.

Similar to how there's text that says Ctrl + Alt + Enter to run, but this would only appear if I have the shift key pressed

**Comment by misolori** [comment]
Something like this in the status bar of the cell?

![image](https://user-images.githubusercontent.com/35271042/109050919-ce175000-768e-11eb-93a2-5668ed870fed.png)

We can also replace the current placeholder with that bit:

![image](https://user-images.githubusercontent.com/35271042/109050989-e4251080-768e-11eb-9143-988ebe04bde0.png)

**Comment by rebornix** [comment]
I like the idea of showing different status based on modifier. One thing I'm not sure about is if users expect to see `shift+enter` to run cell and insert cell below.
