### ISSUE TITLE
Focus border when adding a port

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#117453]
Testing microsoft/vscode-remote-release#4515

1) Manually add a port in the Ports view

I would the focussed table cell to have a full focus border and not only on the sides:

![image](https://user-images.githubusercontent.com/4674940/108895252-32bba780-75c8-11eb-84c5-df87a8d603ca.png)

**Comment by alexr00** [comment]
The problem is that the input box is getting cut off. Duplicate of https://github.com/microsoft/vscode/issues/117385
