### ISSUE TITLE
Update Native Notebook Renderer API to align with the latest Notebook Cell Output structure changes

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117444]
- VS Code Version: OSS
- OS Version: Mac

Steps to Reproduce:

1. Today we have metadata in Cells, Output, & OutputItems
2. When rendering in custom renderer the following data is sent to the renderer extension:
```typescript
export interface NotebookOutput {
    data: { [mimeType: string]: any };
    metadata?: NotebookCellOutputMetadata;
}

export interface NotebookCellOutputMetadata {
    /**
     * Additional attributes of a cell metadata.
     */
    custom?: { [key: string]: any; };
}
```

Would be good to send the metadata from the output as well as output item or just the outputitem.
After all the data for rendering is coming from the outputitem, hence at a minimum we need the metadta associated with the output item.

@rebornix @jrieken /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DonJayamanne** [comment]
FYI - not a bug, but a request to change/update API.

**Comment by connor4312** [comment]
> Would be good to send the metadata from the output as well as output item or just the outputitem

This is what happens today, creating a `new vscode.NotebookCellOutputItem` with `{ some: 'metadata' }` I get that in the renderer event.

![](https://memes.peet.io/img/21-03-f396f0f2-b256-4d46-a227-6e86e4804f82.png)

Is there something else you're looking for?

**Comment by DonJayamanne** [comment]
Its not clear to me what properties (data & metadata) NotebookCellOutputItem maps to the data received in the renderer.
Looking at the above item:
**This is what we have in NotebookCellOutputItem:**
* Value: unknown
* metadta: Record<string, any>

I know this information is sent to the renderer.
This is the typing for renderer:
```
export interface NotebookOutput {
    data: { [mimeType: string]: any };
    metadata?: NotebookCellOutputMetadata;
}

export interface NotebookCellOutputMetadata {
    custom?: { [key: string]: any; };
}
```

Looking at the above API & document (comments) I have no idea what NotebookCellOutputItem.value maps to in NotebookOutput
Similarly where is NotebookCellOutputItem.metatadata in NotebookOutput.

There doesn't seem to be a 1-1 mapping.
Also to my knowledge there's no such thing as `custom` anymore in Notebook Outputs. It only exists in Notebook Cells.

Put another way, which one of these properties are sent to the renderer & how do i access them?
* NotebookCell.custom
* NotebookCellOutput.metadata
* NotebookCellOutputItem.metadata
* NotebookCellOutputItem.value

**Comment by connor4312** [comment]
Okay, I see the difficulty. A sensible way we can provide data is just having the same `NotebookCellOutputItem` interface provided to the cell. This will be breaking but I can have a back-compat patch to give transition time.

@rebornix any concerns with this approach? Is the `NotebookCellOutputItem` API stable enough to adopt in the renderer?

**Comment by jrieken** [comment]
>  Is the NotebookCellOutputItem API stable enough to adopt in the renderer?

Our confidence is high

**Comment by connor4312** [comment]
The `INotebookOutputEventParams` is now a supertype of the NotebookCellOutputItem

```ts
export interface INotebookOutputEventParams  {
	element: HTMLElement;
	outputId: string;

	readonly mime: string;
	readonly value: unknown;
	readonly metadata?: Record<string, any>;
}
```

**Comment by connor4312** [comment]
@vijayupadya @kjcho-msft please propagate these changes in AZNB too -- should be pretty simple, just some renames
