### ISSUE TITLE
Ability to set a custom icon in the right-hand gutter of vscode.TreeItem

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117499]
As a vscode extension author, I'd like to be able to programatically set a secondary icon for a vscode.TreeItem that sits on the right-hand gutter in a treeview:

![TreeviewGlyphs](https://user-images.githubusercontent.com/741350/108919995-d8ecc900-762b-11eb-99af-ef27c5b8f549.png)

For example, the first entry in this treeview would be the "M", followed by the a green "U" and another green "U" icon.

**Comment by alexr00** [comment]
You can do this with file decorations: https://github.com/Microsoft/vscode/blob/7222dfcffb52d3937a312cf88b518aa99004c01a/src/vs/vscode.d.ts#L5623-L5657

**Comment by gplumb** [comment]
Hi

Wouldn't this only help in the file explorer view, or are you saying that
decorators will be applied to a node if their uri is set in a custom
treeview?

**Comment by alexr00** [comment]
`FileDecorations` are applied in any tree that the uri is rendered in.

**Comment by gplumb** [comment]
Great! I'll have a play...

Thanks Alex!👍
