### ISSUE TITLE
show providerId in list of sign ins?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#117497]
Testing #117290

We don't show the provider in the list of extensions that want to sign in:

![image](https://user-images.githubusercontent.com/1487073/108919355-b638c100-75e7-11eb-8572-4cfbdfb51860.png)

In this case, test117290 wants to sign in using the `microsoft` provider and the others I assume want to sign in using GitHub.  It would be good to know what I am signing into.  

`Sign into GitHub to use GitHub Codespaces(1)`
`Sign into GitHub to use GitHub Pull Request Nightly(1)`
`Sign into microsoft to use test117290(1)`

**Comment by chrisdias** [comment]
or maybe "sign in with <<< provider >>>" to use ...

**Comment by TylerLeonhardt** [comment]
Verification steps:

* Install GHPR extension

See:
![image](https://user-images.githubusercontent.com/2644648/118340925-0f6f0d00-b4d2-11eb-8dbe-b4329d870e2b.png)

* Install GitHub Codespaces extension ("Cancel" any modals)
* Reload VS Code
* Once GitHub Codespaces activates you should see:

![image](https://user-images.githubusercontent.com/2644648/118340979-40e7d880-b4d2-11eb-8562-58337958bda8.png)
