### ISSUE TITLE
Terminal stuck on "starting"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117464]
I "Reload Window"'d an Extension Development Host window, and got this. Terminal is functional, but the title is stuck. I think the terminal was blank until I hid and showed the panel.

![image](https://user-images.githubusercontent.com/323878/108899410-3a317f80-75cd-11eb-9f94-a3f01eaf66a9.png)

Error in devtools:

![image](https://user-images.githubusercontent.com/323878/108899452-46b5d800-75cd-11eb-831b-38097e336d1d.png)

**Comment by roblourens** [comment]
Reload Window again did not fix it. Closing the window and launching the debug task again did not fix it. Same error in devtools each time.

**Comment by LeanderD** [comment]
I had the same issue. And it was indeed blank until I closed the panel and opened it again.
In todays update everything seems to be working again.

**Comment by Tyriar** [comment]
@roblourens can you try again on latest? We did a lot of fixes around this yesterday.

**Comment by roblourens** [comment]
I haven't seen it yet at least

**Comment by meganrogge** [comment]
Okay please re-open this if you see it again

**Comment by roblourens** [comment]
Make sure you set the appropriate labels on this
