### ISSUE TITLE
Test: hover with expected vs actual should be custom

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#117429]
Currently you use the native hover to show expected vs actual value. Which is fair, I just think it does not look that good

We should probably use the custom hover and give it some color and richness

![Screenshot 2021-02-23 at 17 18 50](https://user-images.githubusercontent.com/1926584/108873351-5815d900-75fb-11eb-84a2-e0c73461fedb.png)

**Comment by connor4312** [comment]
I started looking at implementing custom hovers, but realize what I wanted was just for '```diff'-like output, and we already support markdown strings. So I had the selfhost test provider format those

![](https://memes.peet.io/img/21-03-1b7e5f33-2a82-4b98-8a68-b622a060b7fe.png)

**Comment by isidorn** [comment]
Looks better!
