### ISSUE TITLE
No autofill template gettingStarted.button

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117476]
Testing #117310

After typing `"button":` and then pick suggestion will insert below content

```
{
				"id": "ext.hello3",
				"description": "tst",
				"button": {

				}
			}
```

but since `command` and `title` are required, we may want to insert 

```
{
				"id": "ext.hello3",
				"description": "tst",
				"button": {
						"command": "",
						"title": ""
				}
			}
```

**Comment by mjbvz** [comment]
Marked as verified because I don't think this property exists anymore
