### ISSUE TITLE
Can't unhide test/reveal back in explorer

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#117481]
Testing #117305

Hide a test (cancel despite...)

![image](https://user-images.githubusercontent.com/25310137/108906968-5d146180-75d6-11eb-803d-df76c568058e.png)

Open file where test is located, Reveal in Explorer to bring it back/unhide it

![image](https://user-images.githubusercontent.com/25310137/108907034-71f0f500-75d6-11eb-9440-1a934af90d5d.png)

I don't see it in the explorer? I expected it to appear back at the top of the section where it was hidden:
![image](https://user-images.githubusercontent.com/25310137/108907121-8fbe5a00-75d6-11eb-96d6-7c8a525efa39.png)

I scrolled to the bottom of the section and of all tests, and I don't see it there either.

**Comment by connor4312** [comment]
"Unhide" is a separate action taken in the "filter" menu. I didn't think about how "reveal" should work. Maybe revealing a hidden test automatically ticks the "Show hidden test" checkbox

**Comment by bamurtaugh** [comment]
Got it - I see the unhide path now from the "filter" menu. 

> Maybe revealing a hidden test automatically ticks the "Show hidden test" checkbox

That would make sense to me!
