### ISSUE TITLE
Can only configure `emmet.extensionsPath` using the settings.json editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#117517]
Testing #117277

**Bug**
Currently the `emmet.extensionsPath` setting can only be configured by editing the `settings.json` file. It would be nice if you could configure it using our settings UI as well

**Comment by JacksonKearl** [comment]
It'd make sense to me to deprecate the string/null potential values in favor of an array of strings. You could declare the settings as `string[]` (which settings editor can handle, see `terminal.integrated.commandsToSkipShell`), then transform existing `null`'s to the empty array and existing single string values to `[theValue]`.
