### ISSUE TITLE
Emmet snippets config selects folder with no snippets.json entry

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#117532]
Testing #117277
```
	"emmet.extensionsPath": ["./blop","./bloop"],
```

Folder structure:
```
./bloop
  - snippets.json
./blop
  - empty
```

The snippets are not read from ./bloop/snippets.json and instead no snippets are provided.

**Comment by rzhao271** [comment]
Just thought about this a bit.
- There could technically be a syntaxProfile.json under that directory, so in that case the folder can be selected still
- The folder can contain none of the Emmet-related json files. For this case, I'd rather leave it up to the user to make sure they're pointing to a good folder.

I guess what I can do is update the `emmet.extensionsPath` description to be more clear about these cases.

**Comment by rzhao271** [comment]
Closing in favour of #117515
