### ISSUE TITLE
code.visualstudio.com is down.

### ISSUE THREAD

**Issue by KG7QIN** [microsoft/vscode#117551]
- VS Code Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Visit https://code.visualstudio.com
2. Get SSL self-signed error
3. Look for error message:

    Not Found
    The requested URL was not found on this server.
    Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
    Apache/2.4.29 (Ubuntu) Server at code.visualstudio.com Port 443

**Comment by joaomoreno** [comment]
No I don't think this is correct. Can you show me a screenshot of the error?

**Comment by KG7QIN** [comment]
Looks to have been corrected. 

It was a typical 404 error from Apache server.  Something was wrong for a while so I filed this report.

**Comment by joaomoreno** [comment]
cc @gregvanl
