### ISSUE TITLE
Leading slash on implicitly saved WSL workspace path

### ISSUE THREAD

**Issue by ncoghlan** [microsoft/vscode#117514]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a workspace file for a WSL1 workspace (Fedora Remix in my specific case)
2. Save the workspace file on the *Windows* side of the filesystem (i.e. path to workspace is "C:\Users\Nick.Coghlan\...")
3. Have "Restore Windows" set to "All"
4. Restart VSCode
5. Instead of reopening the workspace, editor launches to the welcome screen. Top recent files list entry has a leading "/" on the workspace file path, following by the "[WSL: fedoraremix]" annotation, and does not work. 2nd entry has the correct Windows path to the workspace file, and works when selected directly.

Does this issue occur when all extensions are disabled?: Not checked

**Comment by aeschli** [comment]
I'm not able to reproduce with your steps. The restored window opens the workspace in a WSL window with the proper folder
- new WSL window
- add folder to workspace. add `vscode-remote://wsl+ubuntu/home/aeschli/workspaces/foo` to the workspace file
- save the workspace on the windows side
- close window
- restart vscode
- open is restored properly
