### ISSUE TITLE
Forwarding same port could warn

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117571]
Testing #117250

In this case I would have expected a validation warning that the port has already been forwarded:

![image](https://user-images.githubusercontent.com/900690/108996585-db3c3b00-769e-11eb-9f97-2d94a869b8d8.png)

**Comment by alexr00** [comment]
To verifier: An error is now shown when you try to forwarded a port that is already forwarded (either from the command palette or the view).
