### ISSUE TITLE
Revisit "viewType" in workbench.editorAssociations

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117546]
I understand that `viewType` is an internal concept and also surfaces in our extension API, but for a user I find the setting `workbench.editorAssociations` using `viewType` confusing. 

Here is my proposal:

```json
"workbench.editorAssociations": [
    {
        "editor": "hexEditor.hexedit",
        "filenamePattern": "*.js"
    }
]
```

**Comment by bpasero** [comment]
My understanding is that `viewType` is actually a secondary identifier to distinguish the editor. Basically:
* `editorInput.id` to figure out which editor to use (`CustomEditor` or `NotebookEditor` or anything else)
* `viewType` to figure out which extension to use within the editor

If we can make this a core workbench editor thing, then I would probably not call this `editorId` because we already have that today. We can come up with a different name, or even go with `editorType`, though that is a bit confusing too.

Maybe it would be possible to somehow include the current `viewType` into the editor input type identifier and then extract it from the editor so that we keep this exclusive to editors that have this concept? E.g. you end up with an editor type ID of `workbench.customEditor:<viewType>`

**Comment by lramos15** [comment]
I don't think that's quite right. `viewType` is the editor ID the way we determine what to use is based off of the editor input instance type. I.e. is it a `NotebookEditorInput` or a `CustomEditorInput`. The way we create the right one for a specific viewType is that we call open on all editors which subscribe to the override, therefore the custom editor / notebook will reject a `viewType` that it's not familiar with.

**Comment by bpasero** [comment]
Oh even better, then I would like to see change its name to `editorId` Or maybe `editorType` to be symmetric to `viewType` if we use that elsewhere for example for custom views?
