### ISSUE TITLE
Get Started: invisible tab stop when first entering Get Started page

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#117540]
Testing #117313

Tab around the editor with the Get Started page open.

Put tab focus on the Get Started split button

![image](https://user-images.githubusercontent.com/12818376/108948001-763d0280-7616-11eb-9d16-cba4e6982026.png)

Tab again and there is no focus or keyboard action.

![image](https://user-images.githubusercontent.com/12818376/108948070-98cf1b80-7616-11eb-9e64-d2772c149cfa.png)

Tab again to get to the first Get Started item.

![image](https://user-images.githubusercontent.com/12818376/108948103-b00e0900-7616-11eb-8757-d46116aa36df.png)

**Comment by JacksonKearl** [comment]
The single invisible tab stop is intentional (same thing exists in places like old welcome page, extension editor), the multiple when on a details page is a bug.
