### ISSUE TITLE
Remove peek view if associated test is destroyed

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117524]
Testing #117304

1. Run a test that fails
2. Show the peek view
3. Update/Fix the test (auto-run was enabled)
:bug: => After completion the peek still shows the old information

this could be due to the test id changing since I have it linked to the test content, but even if thats the case the peek should be dismissed then.

**Comment by RMacfarlane** [comment]
I'm still seeing this in the latest insider's, not sure if my autorun settings are correct:

1. Using the `test-provider-sample` extension within the `microsoft/vscode-extension-samples` repo
2. Have `"testing.autoRun.mode": "rerun"` in settings
3. Follow above, make a test fail, fix it, and save file

I see the gutter decoration immediately update for the test, but the peek view is still there:
![Screen Shot 2021-03-25 at 11 01 26 AM](https://user-images.githubusercontent.com/3672607/112521424-b7314f80-8d59-11eb-80eb-11ba4acd13fd.png)

and the parent tree decorations are also not yet updated:
![Screen Shot 2021-03-25 at 11 02 00 AM](https://user-images.githubusercontent.com/3672607/112521436-bbf60380-8d59-11eb-8c08-b786ee94197b.png)
