### ISSUE TITLE
Allow to copy/save/edit the search result occurrences

### ISSUE THREAD

**Issue by sdudnic** [microsoft/vscode#117552]
Actually the search result of a regex, by ex, contains all the file paths and whole lines where the resulting occurrences are meet. 

We would like to be able to copy (or/and) edit (or/and) save the pure list of regex occurrences, without additional meta information.

As an example of such a search would be all hard-coded strings from the application, when the user needs the strings, not the lines of code nor the files path.

See [this SO question](https://stackoverflow.com/q/66329930/961631) for more details:

I need to copy all occurrences of a regex expression strings from my application's code (from a solution **folder**) to translate them.

I open my solution in VS (or VS Code) and do a regex like `"[^"]+"`...

How to save my search results as text file?

I mean, not the whole lines containing the strings, but only strings!

The result of such a search in my solution folder (with a *.cs filter) would be like:

    > C:\MySolutionPath\MyToto.cs
    return "toto";
    button.Text = "Submit";

    > C:\MySolutionPath\MyBar.cs
    bar.Header = "My text to translate";

I need only the list of 

    "toto"
    "Submit"
    "My text to translate"

and not all the lines and files paths.

**Comment by roblourens** [comment]
Currently, no way to do this

**Comment by AndreiVettor** [comment]
It seems that a good solution was proposed on the [SO question mentioned above](https://stackoverflow.com/questions/66329930/copy-search-results-only).

1. Open the Find dialog
3. Enter the regex search: `"[^"]+"`
5. Press `Alt+Enter` (_Now all strings are selected_)
9. Press `Ctrl+C`
11. Press `Esc`
13. Leave Multi Cursor mode
15. Go to a New File
17. Press `Ctrl+V` (_Now every string is on a new line_)

**Comment by AndreiVettor** [comment]
The solution above only works for simple regex patterns. It is not possible to copy capture group occurrences.
A temporary workaround is to:
1. Copy the regex matches
2. Create a new file
3. Paste the matches 
4. Apply a new regex pattern (the initial capture group) on the matches

**Comment by sdudnic** [comment]
and where is that feature request to upvote it? @vscode-triage-bot
