### ISSUE TITLE
Feature flag for opening first incomplete section

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#117533]
We got this as an idea from usertesting on new users, but I can see the point in not hiding the full range of content from experienced users. @JacksonKearl to address @kieferrm's point, could we put the logic from f4ce983bcd70bf8ed0da1cad4abc9cb9fd138b05 behind an experiment feature flag to do more testing in the field? Shall I file a new issue?

_Originally posted by @digitarald in https://github.com/microsoft/vscode/issues/116570#issuecomment-783953713_

**Comment by JacksonKearl** [comment]
cc @digitarald if you give me a feature flag I can add this no problem

**Comment by JacksonKearl** [comment]
I guess just verify that after running a `getting started: reset all progress`, getting started opens to the index rather than the first category. Ideally we'd have some way to opt-into experiments via a config.

**Comment by connor4312** [comment]
@JacksonKearl "getting started" always opens the index page rather than the first category, even when I've made partial progress in one or more categories.

**Comment by JacksonKearl** [comment]
That is the correct behaviour.

**Comment by JacksonKearl** [comment]
The ideal verification would be to test that if you've been assigned the treatment then it will open. to the forst category if you've completed no items, but we can't opt into treatments yet.
