### ISSUE TITLE
Regression: --goto feature should accept empty line and column numbers

### ISSUE THREAD

**Issue by naumovs** [Microsoft/vscode#11753]
- VSCode Version: 1.5.1
- OS Version: MacOs

Steps to Reproduce:

1. Open terminal
2. run code . --goto somefile: 

Expected: VSCode opens the file.
Actual: throws an error `Arguments in `--goto` mode should be in the format of `FILE(:LINE(:COLUMN))`.`

The reason is simple - iTerm2 can be configured to run a program on a Cmd+click on filename in the terminal. It offers an ability to pass line number if it was identified, but it can't add colon conditionally if it identified the line number or not.

Feature was working on previous version

**Comment by ramya-rao-a** [comment]
@joaomoreno Root cause might be the same as that for #11731 ?
