### ISSUE TITLE
Settings are not universal, they are specific to Workspace

### ISSUE THREAD

**Issue by shubhendur** [Microsoft/vscode#11757]
- VSCode Version:1.5.1
- OS Version:Windows7

Steps to Reproduce:

1. File>Preferences
2. There are two options:
i. The UserSettings are not editable.
ii.The Workspace settings are editable.

The workspace settings are applied for a particular workspace. 

THERE SHOULD BE AN OPTION TO SAVE THE SETTINGS GLOBALLY.

**Comment by bpasero** [comment]
@shubhendur why are the user settings not editable for you?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
