### ISSUE TITLE
I am coding in visual studio code and learnig C programming language. In this extension named code runner is not working, it is showing that "scriptcs is not recognized as internal or external command", can anybody help and it is also showing that the "system cannot find the path specified" .

### ISSUE THREAD

**Issue by vi13sh** [microsoft/vscode#117586]

**Comment by jrieken** [comment]
> can anybody help and it is also showing that the system cannot find the path specified in vscode.

Sorry, but nobody will able to help you with given you have provided no information

**Comment by rzhao271** [comment]
Wondering if this is an extension issue or even a setup issue (like misconfigured PATH variable)?
If this has to do specifically with Code Runner, please file an issue for it at https://github.com/formulahendry/vscode-code-runner.

**Comment by vi13sh** [comment]
> > can anybody help and it is also showing that the system cannot find the path specified in vscode.
> 
> Sorry, but nobody will able to help you with given you have provided no information

Sir what all information should i provide.

**Comment by aeschli** [comment]
I looks like the error message comes from the [code runner extension.](https://github.com/formulahendry/vscode-code-runner)
The extension readme says: To run C# script, you need to install [scriptcs](http://scriptcs.net/). Did you do that and is the command on the PATH?

If that isn't the problem, please file an issue with steps to reproduce against https://github.com/formulahendry/vscode-code-runner/issues
