### ISSUE TITLE
Closing a conpty terminal hangs Code

### ISSUE THREAD

**Issue by spmeesseman** [microsoft/vscode#117599]
- VS Code Version: 1.53.2
- OS Version: Windows 10 (1909)

Steps to Reproduce:

1. Run a task to auto-open a terminal window (`Enable ConPTY` is ON)
2. Close the terminal window.  About 6-7 seconds later, Code freezes.  8 or 9 times out of 10.

Does this issue occur when all extensions are disabled?: Yes

Saw this was a past issue in #76548 (closed to collaboraters, I couldn't remark there), there's a note saying in Windows 1903 it should be addressed, but I'm on 1909 and it's happening "most" times when I close a terminal using the trash can icon button.  8 or 9 times out of 10 it happens, always 6-7 seconds later.  Switching back to old winpty terminal resolves issue, but I'd LOVE to keep using new conpty terminal, so much better with most people putting colors in the log output now.

I'm surprised to not see this reported somewhere else again, I thought I'd see it reported already when I popped in.

**Comment by IllusionMH** [comment]
#76548 has Open status for this reason.

See latest updates in upstream terminal issue: https://github.com/microsoft/terminal/issues/1810#issuecomment-776716448
And check Insiders build https://code.visualstudio.com/insiders/

**Comment by spmeesseman** [comment]
s*** my apologies, don't know how I missed that
