### ISSUE TITLE
right click menu disappeared

### ISSUE THREAD

**Issue by chatay** [microsoft/vscode#117567]
Issue Type: <b>Bug</b>

I do not know if it is related to that but once I installed C# extension, many menu items have been disappeared on the right click menu.

![image](https://user-images.githubusercontent.com/27813881/108996092-0af33f00-76af-11eb-8ffd-b0560b927a0b.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.65GB free)|
|Process Argv|--crash-reporter-id 17120a1a-f048-4c2d-aabe-b48938a9d772|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
/extC#

Most likely the extension is crashing the Extension Host, which prevents other extensions from working (including adding entries to menus).
