### ISSUE TITLE
Default keybindings.json has some `Missing property "args".` errors

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#117534]
Issue Type: <b>Bug</b>

1. Open default keybindings.json
2. Press F8

![image](https://user-images.githubusercontent.com/1330321/108940757-e38c7a00-768e-11eb-9a1d-783b7f1f6782.png)

VS Code version: Code - Insiders 1.54.0-insider (9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea, 2021-02-23T10:46:22.816Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (6.09GB free)|
|Process Argv|--crash-reporter-id 39b79841-23f2-4fc6-a5c1-ec0a901ec9aa|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
@alexdima This warning seems to be caused by this: https://github.com/microsoft/vscode/blob/3022afaeaa291fec298ffa86cefff6893ddb192c/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L805

It seems that whenever an argument has a required property the whole argument is becoming a required property. This is biting us as it prevents to properly define an argument that is optional

**Comment by alexdima** [comment]
@jrieken So the new use case is that the `args` field is optional, but if it is specified, then it must contain a certain argument? And the bad assumption is that a required argument means that `args` overall are required?

cc @aeschli for ideas

**Comment by jrieken** [comment]
> And the bad assumption is that a required argument means that args overall are required?

Yes

**Comment by aeschli** [comment]
In JSON schema, the `required` relates to the properties defined in the object.
I suggest to add a new property one level up, next to the name. Maybe `'optional` for background compatibility.
```
args: [
	{
		name: 'index',
		description: 'The cell index',
		schema: {
			'type': 'object',
			'required': ['index', 'direction'],
			'properties': {
				'index': {
					'type': 'number'
				},
				'direction': {
					'type': 'string',
					'enum': ['up', 'down'],
					'default': 'down'
				},
				'levels': {
					'type': 'number',
					'default': 1
				},
			}
		}
	}
]
```
