### ISSUE TITLE
Crashes on opening a specific 700kb png file

### ISSUE THREAD

**Issue by akshayat** [Microsoft/vscode#11752]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Get a png file ~700KB
2. Put it under root of the project
3. Try to open it by clicking from Explorer menu

**Comment by akshayat** [comment]
![image](https://cloud.githubusercontent.com/assets/2619644/18380837/ea933f34-7696-11e6-9b79-46dca11b36c5.png)

**Comment by bpasero** [comment]
@akshayat care to attach the PNG?

**Comment by akshayat** [comment]
Apparently having issue with that files only. I could not reveal the files. However files are successfully opening in other applications like windows photo viewer etc. 

Files were created by photoshop.

**Comment by bpasero** [comment]
@akshayat so you say an equal sized different PNG does not cause this?

**Comment by akshayat** [comment]
Yes, even bigger size does not cause this.

**Comment by bpasero** [comment]
Looks like an upstream issue with Chrome then. A future update might well fix this.

**Comment by bpasero** [comment]
@akshayat   we just released a new insiders build with a newer Electron. maybe you could give that build a try to see if it fixes this issue.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by akshayat** [comment]
Tried with Visual Studio 1.8.1 and it is not crashing. So issue seems resolved.
