### ISSUE TITLE
Menu Subitem Help cannot be dropped down by accelerator key comination Alt+H

### ISSUE THREAD

**Issue by CodingForFunToo** [microsoft/vscode#117550]
Issue Type: <b>Bug</b>

Every other sub menu, like File, Edit, Select can be invoked by its underlined accelerator key, but this does not work for Help.

 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icalendar|af4|1.0.1
githistory|don|0.6.14
reg|ion|1.0.2
csharp|ms-|1.23.9
mssql|ms-|1.10.1
powershell|ms-|2020.6.0
vscode-xml|red|0.15.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/confirmationPending

This works for me. Do you still have the problem if you launch with all extensions disabled? Do you have any conflicting keybindings? See https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice.

**Comment by sbatten** [comment]
I think GitLens registers an Alt+H keybinding with certain settings, unfortunately it is up to the user to reconcile these conflicts as we cannot choose for you which you would prefer. Please follow the advice of @gjsjohnmurray

**Comment by CodingForFunToo** [comment]
Yes, you are right, the ALT-H was intercepted by Extension _Git History_ by Don Jayamanne.
After removing this shortcut in the _Keyboard shortcuts_ editor, ALT+H is working again as intended.
Thanks for your help.
