### ISSUE TITLE
TreeView state out of sync

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117525]
Testing #117304

Repro: Not Sure

Test state shows passed in file but still running in tree view.

![image](https://user-images.githubusercontent.com/6561887/108932683-a082c600-75fe-11eb-8ccd-afa5d0e2a91e.png)

**Comment by connor4312** [comment]
Can you share your source? I've only seen this happen if IDs were mismatched.

**Comment by sbatten** [comment]
https://github.com/sbatten/test-provider-sample

**Comment by connor4312** [comment]
Repro steps are:

1. Open tree view and a test file
2. Make any change (e.g. add a new line at the end) of the test file and save
3. Run tests, the tree does not update
