### ISSUE TITLE
"Find in files" (CTRL-SHIFT-F)  only finds in the current file.

### ISSUE THREAD

**Issue by mike65535** [microsoft/vscode#117530]
- VS Code Version:
- OS Version:

I have about a dozen mixed .c, .h and .txt files open in VSC.

"Find in files" (CTRL-SHIFT-F)  does not find matches in open or non-open files - only in the current selected file.

I can have nothing, or add *.* or *.c etc. to the "Files to include" making no difference.
I have nothing in "Files to exclude".
The "Match Case" and "Match Whole Word " settings also do not matter.

Linux 5.10.16-200.fc33.x86_64 #1 SMP Sun Feb 14 03:02:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.16-200.fc33.x86_64

Does this issue occur when all extensions are disabled?: Yes

I'm having the same problem AFAIK.
I have about a dozen mixed .c..h and .txt files open in VSC.

"Find in files" (CTRL-SHIFT-F)  does not find matches in open or non-open files - only in the current file.

I can have nothing, or add *.* or *.c etc. to the "Files to include" making no difference.
I have nothing in "Files to exclude".
The "Match Case" and "Match Whole Word " settings also do not matter.
It's running in latest Fedora.

Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.16-200.fc33.x86_64

CPUs | Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 4000)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: disabled_software skia_renderer: enabled_on video_decode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 0, 0, 0
Memory (System) | 15.29GB (7.94GB free)
Process Argv | --no-sandbox --unity-launch --crash-reporter-id 6d522ad2-c5b1-47fa-852d-d5689b0c570f
Screen Reader | no
VM | 0%

Extension	Author (truncated)	Version
cmake-tools	ms-	1.6.0
cpptools	ms-	1.2.1
vscode-print	pdc	0.8.3
cmake	twx	0.0.17

**Comment by roblourens** [comment]
Please check whether any tips on this wiki page are helpful: https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by mike65535** [comment]
>>If there's an issue with search, do you see the same issue with quickopen, (or vice versa)?
**I don't use "quickopen" and don't know what it is or why I would want to.**

>> If you see an issue with search when you have folder A open, do you see a similar issue with other folders on your computer?
**I see this issue in all folders I use regularly**


>> Collecting search logs
>> Some details are logged for each search. To see these logs, run the command "Developer: Set Log Level...", select "Trace"

Do you want this info?  How does one "run" a "command"?

**Comment by mike65535** [comment]
And just like that - the "all files" search works.
