### ISSUE TITLE
Ability to assign additional commands to a vscode.TreeItem

### ISSUE THREAD

**Issue by gplumb** [microsoft/vscode#117500]
As a vscode extension author, I'd like to be able to programatically set commands for a specific vscode.TreeItem and have them visually represented in a treeview when an item is hovered over or selected:

![TreeviewGlyphs](https://user-images.githubusercontent.com/741350/108920284-4f89c680-762c-11eb-98a4-a578d2dcd479.png)

You'll see in the example here, extension.ts is offering up 3 additional commands (shown by the page, undo and add glyphs).

**Comment by alexr00** [comment]
Please see the API docs. You can do this with menu contributions: https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by gplumb** [comment]
Hi

This covers the wholesale aspect of nodes in a tree, but if I want to bind
commands to a node individually (which I do), this doesn't help.

My proposal to do this via the TreeItem object is still valid...

**Comment by alexr00** [comment]
The docs cover this. You must use `when` clauses. From the documentation:

> The menu item definition contains the command that should be invoked when selected **and the condition under which the item should show.** The latter is defined with the when clause, which uses the key bindings when clause contexts.

**Comment by gplumb** [comment]
I think the piece missing here is dynamically projecting state into that
clause from code. Is there any example of that in github samples repo?

**Comment by gjsjohnmurray** [comment]
> 
> I think the piece missing here is dynamically projecting state into that clause from code. Is there any example of that in github samples repo?

https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context

**Comment by gplumb** [comment]
Thank you both!

I can see the philosophy behind making this semantic, but I still feel that
there is a strong case for defining this at node level when using a custom
TreeDataProvider (particularly for more complex trees).

Thoughts?

**Comment by alexr00** [comment]
Since this can be completely controlled with `when` clauses, I don't see a enough benefit to having another way to add to menus.

**Comment by gplumb** [comment]
I see why you've said that, but still feel my suggestion is valid. If you
will humour me, I'll outline something more akin to my use-case and if you
wish to close it still, then so be it!

I have a tree with a taxonomy of different node types, each with their own
contextually sensitive commands. Based on the current implementation, the
"when" clauses balloon into mini essays as every permutation of command for
the entire tree needs to be encoded along with their various context
projections from code.

For even a basic taxonomy, this would become error-prone and unwieldy
pretty quickly - not to mention more difficult to test (not impossible, but
definitely more difficult).

Now compare that to a command array on a treeview item. Since more
elaborate scenarios require a custom tree data provider anyway, it's
trivial to just set a property on any given node when yielding them in the
getTreeItem method (and makes for simpler unit testing).

My use-case may ultimately be a little too niche, but I'd like to think
there's some merit in this approach as a compliment to the existing one.
