### ISSUE TITLE
Can't copy rich text properly when 'editor.fontFamily' has fallback fonts

### ISSUE THREAD

**Issue by Arriv9l** [microsoft/vscode#117537]
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

As a CJK user, I prefer to set `editor.fontFamily` to `Cascadia Code, PingFang SC Regular` rather than just single `Cascadia Code`. But then, I can’t copy rich text properly.

Steps to Reproduce:

1. Set your `editor.fontFamily` with fallback fonts, like `Cascadia Code, PingFang SC Regular`
2. Copy and paste it into Word
![before.gif](https://i.loli.net/2021/02/24/891JFgbIYVNLMSa.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I can no longer reproduce:

https://github.com/microsoft/vscode/assets/5047891/859fc79e-e16b-457a-aa13-8bbaa44efcef




 I think this might have been fixed via https://github.com/microsoft/vscode/commit/2e165500a6d5449fdd076f0ddbaa588f1e5743c7
