### ISSUE TITLE
Horizontal scroll doesn't work

### ISSUE THREAD

**Issue by benaltair** [microsoft/vscode#117501]
Issue Type: <b>Bug</b>

I'm trying to horizontally scroll in my main editor window. It doesn't work. It works on all other applications I've tested. If I hold Shift and normally scroll, it will horizontally scroll. Sometimes it horizontally scrolls once if I change lines and then try, but after one slight movement it stops again.

It's very weird behaviour. 

Brand new mouse, Logitech MX Master 3

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (15.37GB free)|
|Process Argv|--crash-reporter-id 9d5ea734-7a92-4510-a63f-82d9901fce55|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
smarty|imp|0.3.0
json2csv|kha|0.0.1
sftp|lix|1.12.9
language-gettext|mro|0.2.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-wsl|ms-|0.53.4
vscode-yaml|red|0.15.0
LiveServer|rit|5.6.1
netlify|sha|1.5.0
code-settings-sync|Sha|3.4.3
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.1.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30262999
pythontbcf:30260844

```

</details>

**Comment by rzhao271** [comment]
Some sanity checks:
- Is this caused by an extension? Try running Extension Bisect
- Does using another mouse or trackpad (if you have one) work?
- Does reloading the window work (press F1 then search 'Reload Window')?
- Does horizontal scroll work on VS Code Insiders edition, or on a Chromium-based web browser such as Chrome or Edge?

TIL shift + scroll horizontally scrolls. That's good to know; my mouse doesn't have a horizontal scrolling capability so I can't reproduce this issue directly.

**Comment by deepak1556** [comment]
\Duplicate https://github.com/microsoft/vscode/issues/84136
