### ISSUE TITLE
[python] strings in dictionary values incorrectly highlighted

### ISSUE THREAD

**Issue by aibolit** [Microsoft/vscode#1175]
When creating dictionaries with any values the strings in the value section are all hi-lighted blue and not red. 
e.g. for the following code snippet
```python
{"a":{"b":"c"}}
```
The string "a" will be highlighted red, while "b" and "c" will be highlighted blue even though they are both strings like "a" is.  "b" is also a key to a dict like "a" is 

Note: this is using the "Light" theme

**Comment by aeschli** [comment]
fix delivered

**Comment by isidorn** [comment]
So now I see "a" and "b" in red since they are keys, and "c" in blue since it is a value. I think this is expected.
