### ISSUE TITLE
Test: Run Test at Cursor doesn't provide any feedback

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#117587]
This is my first time trying out any of the test features, so maybe I missed something. 
1. I opened up extHostTreeViews.test.js from the vscode repo.
2. Put my cursor on a test.
3. Test: Run Test at Cursor

As far as I could tell, nothing happened. There was no notification saying something didn't work.

**Comment by connor4312** [comment]
Hi, to confirm did you use `extHostTreeViews.test.js` or `extHostTreeViews.test.ts`? The selfhost test provider only discovers tests in the `.ts` files, and if the command is run in a range outside of the test there will be no feedback (which is something I can improve).

**Comment by alexr00** [comment]
Nice catch. I was in the TS file when I got this behavior: exthostTreeViews.test.ts

**Comment by connor4312** [comment]
Thanks for confirming, closing as dupe of https://github.com/microsoft/vscode/issues/117634
