### ISSUE TITLE
Getting started seems to be hardcoding file protocol

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117592]
Steps to Reproduce:

1. set `"enable-browser-code-loading": "bypassHeatCheck"` in `argv.json`
2. restart
3. open getting started

```
Not allowed to load local resource: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/services/gettingStarted/common/media/colorTheme.png
```

**Comment by JacksonKearl** [comment]
We use: `FileAccess.asFileUri('vs/workbench/services/gettingStarted/common/media/' + path, require);`

https://github.com/microsoft/vscode/blob/840f19af066b9102b4ee1e852e2a6ad934298b6b/src/vs/workbench/services/gettingStarted/common/gettingStartedRegistry.ts#L144

**Comment by JacksonKearl** [comment]
`asBrowserUri` seems to do the trick.

**Comment by bpasero** [comment]
In almost all cases you want `asBrowserUri` 👍
