### ISSUE TITLE
Why not me the updated version

### ISSUE THREAD

**Issue by SFLAQiu** [Microsoft/vscode#11750]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

**Comment by ramya-rao-a** [comment]
@SFLAQiu sorry what??

**Comment by mousetraps** [comment]
@SFLAQiu looks like you're still on v1.3.0 - just to clarify, is the issue that you're not getting the updated version of VSCode? If so, what happens if you select `Help > Check for Updates`?

**Comment by joaomoreno** [comment]
Closing due to lack of details. @SFLAQiu please check @mousetraps's suggestion.
