### ISSUE TITLE
Ports: Add placeholder text in "New Port" row

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117589]
Looks somewhat strange without a placeholder text such as _`Port Number...`_ in _italic_:

![image](https://user-images.githubusercontent.com/22350/109010766-0c981500-7665-11eb-85b0-f81d6adf972a.png)

**Comment by alexr00** [comment]
With new text:
![image](https://user-images.githubusercontent.com/38270282/109017978-fbc4bf00-76b7-11eb-98a5-15db6ee2c40b.png)

**Comment by joaomoreno** [comment]
Maybe we add a verb...? Maybe _Expose port..._? _Add port..._?

**Comment by joaomoreno** [comment]
Maybe @misolori has a better idea? I just find it awkward to have the entire empty row with just a plus.

**Comment by misolori** [comment]
We do already use the `+` concept in keyboard shortcuts, so I didn't see an issue with this:

![image](https://user-images.githubusercontent.com/35271042/109035904-efbc0b80-767d-11eb-9930-382ef83bf333.png)

**Comment by joaomoreno** [comment]
Oh I really like that, never felt odd.

**Comment by alexr00** [comment]
I also like the button!

**Comment by alexr00** [comment]
To get a consistent looking button in there I'll need to change the row heights. Will do for March so that there aren't a whole bunch of alignment candidate issues!

**Comment by joaomoreno** [comment]
I would keep the row heights, just have the last one be taller.

**Comment by alexr00** [comment]
![recording (44)](https://user-images.githubusercontent.com/38270282/109287099-73632d00-7823-11eb-9b2d-09622fff0a0b.gif)
