### ISSUE TITLE
Compact menu focus border inconsistency

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#117575]
Testing #117275

* On a Mac, open a Codespace (ex: microsoft\vscode)
* Set `"window.menuBarVisibility": "compact"`
* Press F10 to focus the menu
  ![image](https://user-images.githubusercontent.com/3372902/108998916-e0e75000-76a1-11eb-88a8-217f0f5dd37f.png)
* Invoke the `View: Toggle  Full Screen` command from the palette
* Press F10 to focus the menu
  ![image](https://user-images.githubusercontent.com/3372902/108999052-10965800-76a2-11eb-9e14-9a20a0e6b7ac.png)

**Comment by sbatten** [comment]
activity bar uses an inset outline, we now match this which removes the risk of being cutoff
