### ISSUE TITLE
Another step needed on tracking repo after 'master' -> 'main' rename

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#117564]
After #116341 I followed the documented steps but was still getting this message in the Git output channel when running the Fetch From All Remotes command:
```
...
> git remote --verbose
warning: ignoring broken ref refs/remotes/origin/HEAD
...
```

I fixed this by running the following command in Terminal:
```
git remote set-head origin main
```

Maybe update the instructions?

/assign @joaomoreno

**Comment by joaomoreno** [comment]
It's good to know but I haven't seen this on any of my machines nor have I heard this from any team member. This could be very specific to your setup. I think we'll be fine without it.
