### ISSUE TITLE
Come up with more robust approach to detached processes in local reconnect

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117588]
Related #116467 

Right now on reload we explicitly tell pty service to detach the process, this does not detect when the window crashes ungracefully.

Repro:

1. Create 2 windows
2. Create a terminal
3. Crash one window (kill proc)

**Comment by Tyriar** [comment]
I think this is fixed now after adopting the code in remote and supporting attach to session which asks the renderers which processes are detached https://github.com/microsoft/vscode/issues/118241

**Comment by lramos15** [comment]
@Tyriar I'm not sure how to verify this one, I assume I follow the steps in https://github.com/microsoft/vscode/issues/118241 which is already verified meaning this one is good now too?

**Comment by Tyriar** [comment]
Yep those steps are the same 👍
