### ISSUE TITLE
Resizing and then reload does not restore columns

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117574]
Testing #117250

I resized the columns all the way to the right but after reload that was not restored.

**Comment by alexr00** [comment]
@joaomoreno  is this supposed to be restored?

**Comment by joaomoreno** [comment]
No, each reload restores the column weights. We don't save view state. I'd say we wait for more people to ask for this before polluting more view state. I really wonder how useful this will be.

**Comment by bpasero** [comment]
Then I don't understand what this test plan task was about:

> that you can resize table columns, and your resizes are preserved across reloads.

**Comment by alexr00** [comment]
@bpasero that was my mistake. I thought that the table was supposed to support this.
