### ISSUE TITLE
Toggle Auto Run Unclear

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117526]
Testing #117304

Do I have to enable auto run, run some test, then change them to trigger it? If I enable auto-run, then change a test that is visible in the test explorer, nothing happens. However, if I run any test first, then make the change it will start auto-running... though again, a lot of the test explorer state is out of sync.

**Comment by connor4312** [comment]
I explained it more here: https://github.com/microsoft/vscode/issues/116383#issuecomment-783785265 As referenced there, I'll probably have this behavior toggleable. The current setup works well for me developing in VS Code, but I realize is not super obvious and for small projects we could have the more obvious implementation.

Does that clear up your questions?

**Comment by sbatten** [comment]
Yea its clear now that the behavior is expected but as I am writing a provider it feels like a bug, and even as a user it feels like a bug. I think a clear setting for this would help.

**Comment by connor4312** [comment]
`testing.autoRun.mode` now configures this

**Comment by sbatten** [comment]
I set the value to `onlyPreviousRun` and enabled auto run. After that, I verified that nothing would autorun since I had not yet run anything. I then switched the setting to `allinWorkspace`, which immediately triggered them all to run. After that, only changes to the top entry are triggering runs and only for that item.

Note that I have also modified the sample to use line number as the identifier for a test since I want to be able to treat them as a single test no matter what numbers I use.

```ts
super(`markdown/${location.uri.toString()}/${location.range.start.line}`, `${a} ${operator} ${b} = ${expected}`, false);
```

![image](https://user-images.githubusercontent.com/6561887/112363657-fd6fab80-8c92-11eb-8d80-4a5302b853f6.png)

**Comment by connor4312** [comment]
@sbatten are you verifying with the extension sample? The sample doesn't implement invalidation at the moment (since test IDs are defined by the tests themselves, it's impossible to change a test)

**Comment by sbatten** [comment]
@connor4312 do you have a sample to verify with? the vs code repo isn't the nicest to test the allinworkspace option

**Comment by connor4312** [comment]
VS Code actually is the only working object.

Invalidation requires the extension call `testItem.invalidate()`. If you modify the sample to call that method on change, then it should work.

**Comment by sbatten** [comment]
I got it working with the sample. The descriptions are a bit off imo as I was still confused as to what I should expect, but it seems to do the right thing. Only the `onlyPreviouslyRun` value suggests that there is an on-change limitation when this seems to apply to the feature "auto-run" as a whole. 

The `allInWorkspace` description should say something like: Automatically runs all discovered test when auto-run is toggled. Re-run individual tests when they are changed."

The `onlyPreviouslyRun` description should say something like: "Re-runs individual tests when they are changed. Will not automatically run any tests that have not been already executed."

the names could also be simpler, like `all` and `rerun`

**Comment by connor4312** [comment]
Thanks for the suggestion, I've applied it 🙂 Feel free to mark `verified` if you think this is otherwise good to go.
