### ISSUE TITLE
Forwarding a port that has no associated process could warn or show info

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117572]
Testing #117250

Not sure how useful it is to forward a port that has no associated process, could maybe show a warning or info here:

![image](https://user-images.githubusercontent.com/900690/108996683-f909a000-769e-11eb-9e2f-51b80d0b69ad.png)

**Comment by alexr00** [comment]
We cannot always tell if there is a process associated with that port. Warning here would likely be too error prone.
