### ISSUE TITLE
terminal bug

### ISSUE THREAD

**Issue by qctxzwq** [microsoft/vscode#117531]
Chinese symbol sticky keyboard
![image](https://user-images.githubusercontent.com/46992318/108935420-a02f0d00-7688-11eb-80d3-c896f8967fbb.png)

**Comment by qctxzwq** [comment]
Chinese symbol sticky keyboard

**Comment by rzhao271** [comment]
Not sure if duplicate of #115814, assigning to @Tyriar

**Comment by Tyriar** [comment]
Closing as dupe, if it's not there isn't enough information in the report to know.
