### ISSUE TITLE
Chinese  characters input error

### ISSUE THREAD

**Issue by zzeshen** [microsoft/vscode#117562]
Issue Type: <b>Bug</b>

Duplicate input occurs when entering Chinese characters, and the repeated  character would automatically delete the previous character.
I'm using Microsoft Input Method. I edited many other file types and turned out the same(*.json, *.md, *.tex, *.txt), and I tested on other editors as well and they worked well. So I guess it was a VScode bug or mistaken configuration.How can I solve it please? 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (11.61GB free)|
|Process Argv|--crash-reporter-id 5335eb41-b8ad-4909-a377-59e0b36ae3e6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
Bookmarks|ale|13.0.1
vscode-markdownlint|Dav|0.39.0
python-extension-pack|don|1.6.0
code-runner|for|0.11.2
simple-dictionary|hod|0.1.0
latex-workshop|Jam|8.16.0
kite|kit|0.142.0
vscode-keyboard-counter|Max|0.0.1
vscode-language-pack-zh-hans|MS-|1.53.2
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.2.576440691
material-icon-theme|PKi|4.5.0
vscode-data-preview|Ran|2.2.0
background|Tho|1.0.2
vscodeintellicode|Vis|1.2.11
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475

```

</details>

**Comment by WEGFan** [comment]
I bisected your extensions and found that it's caused by `vscode-keyboard-counter` extension, [`overtype`](https://github.com/DrMerfy/vscode-overtype) also has this issue on my end.
