### ISSUE TITLE
Incorrect handling of git commit message template

### ISSUE THREAD

**Issue by agauniyal** [Microsoft/vscode#11756]
- VSCode Version:1.5.1
- OS Version: Linux

Steps to Reproduce:

1. Put a template with file name `.git_commit_msg.txt` in home directory
2. config git to use it globally
3. open vscode, make some change in git project, choose to use vscode git commit functionality
4. Instead of just putting the non-commented part, it fills the entire template in commit message.

```
~ ❯ cat ~/.git_commit_msg.txt 
# If applied, this commit will...


# Explain why this change is being made

# Provide links to any relevant tickets, articles or other resources
```

**Comment by joaomoreno** [comment]
Related to #11646
