### ISSUE TITLE
not clear when`createDocumentTestHierarchy` is called

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#117598]
Testing #117304

I started to write a stand-alone test provider extension from scratch by just following your introduction from #117304.

When trying to run this, I was not able to make my suite/testcase hierarchy showing up in the test explorer
and my `createDocumentTestHierarchy` method was never called.

After renaming it to `createWorkspaceTestHierarchy` everything started to work fine. 

I was mislead by the statement:
> VS Code will request tests for a document when it becomes visible,

This seems not to be the case.

And the fact that `createWorkspaceTestHierarchy` is optional made me believe that just implementing `createDocumentTestHierarchy` is sufficient. Shouldn't `createWorkspaceTestHierarchy` be made mandatory?

**Comment by connor4312** [comment]
Yes, I the workspace hierarchy should be required. I think I have another issue for that but cannot find it right now, so will track here.
