### ISSUE TITLE
Cannot see console.log on debug console

### ISSUE THREAD

**Issue by sugandhaC** [microsoft/vscode#117560]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. Open any JS file
2. Run console.log("hello"); there is no output in debug console

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.45GB free)|
|Process Argv|--crash-reporter-id 519c2690-c25f-4408-90f3-4b3da2f4fc0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
vscode-django|bat|1.3.0
vscode-standardjs|che|1.4.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
python-extension-pack|don|1.6.0
vscode-npm-script|eg2|0.3.16
vscode-firefox-debug|fir|2.9.2
vscode-test-explorer|hbe|2.19.5
d3-js-snippets|Hri|1.0.0
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
vscode-codemetrics|kis|1.24.0
d3-helpers-snippets|led|0.4.1
node-module-intellisense|lei|1.5.0
vscode-python-test-adapter|lit|0.6.6
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.30
vscode-exec-node|mir|0.5.3
vscode-azurefunctions|ms-|1.2.1
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
azure-account|ms-|0.9.6
js-debug-nightly|ms-|2021.2.1917
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|4.3.20210223
vsliveshare|ms-|1.0.3784
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
d3-skeletons|noa|0.0.2
vscode-for-node-js-development-pack|nod|2.0.1
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
code-settings-sync|Sha|3.4.3
python|tht|0.2.3
vscodeintellicode|Vis|1.2.11
nodejs-extension-pack|wad|0.1.9
jinja|who|0.0.8
vscode-import-cost|wix|2.15.0
eno|Wsc|2.3.53
omi-snippets|Wsc|2.2.8
JavaScriptSnippets|xab|1.8.0
D3Snippets|yoy|0.1.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by weinand** [comment]
How does your launch configuration look like?

**Comment by sugandhaC** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-msedge",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

**Comment by sugandhaC** [comment]
I added node.JS too
 // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/app.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node"
        },
        {
            "type": "pwa-msedge",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

**Comment by jorenbroekema** [comment]
I'm having the same issue, I straight up followed https://code.visualstudio.com/api/get-started/your-first-extension and I no longer get the console output in my debug console. This worked 1-2 months ago or so when I first tried this guide.

The launch.json is the default one scaffolded from yo:

```json
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		}
	]
}
```

**Comment by jorenbroekema** [comment]
[vscode-debugadapter-00f1da08.json.gz](https://github.com/microsoft/vscode/files/6117806/vscode-debugadapter-00f1da08.json.gz)
[vscode-debugadapter-26055751.json.gz](https://github.com/microsoft/vscode/files/6117807/vscode-debugadapter-26055751.json.gz)

**Comment by connor4312** [comment]
Thanks for the logs. I wonder if this reproduces if run with all other extensions disabled -- something else could be wrapping `console` methods to prevent them getting to the debugger.

**Comment by jorenbroekema** [comment]
I gave the information I could... I disabled all extensions and have the same issue.

**Comment by jorenbroekema** [comment]
I tried running this on Windows 10 with all extensions disabled. Console log works there.

However, I work in WSL2, so doing --disable-extensions won't work because you need the Remote - WSL extension. So instead, I went to extensions and clicked "Disable all extensions", then re-enabled Remote - WSL and reloaded the editor. Then, my console log does not show in my debug console.

So the cause of this problem may be related to Remote - WSL extension. Is there a way where I can report it there?

**Comment by jorenbroekema** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4699 reported it here
