### ISSUE TITLE
red color '<center>' tag

### ISSUE THREAD

**Issue by Harindulk** [microsoft/vscode#117582]
- VS Code Version: 1.53.2 (user setup) 
- OS Version:  Windows_NT x64 10.0.18363

Steps to Reproduce:

![](https://raw.githubusercontent.com/Harindulk/Test-Bootstrap/main/assets/img/Screenshot%20(1077).png)

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
The `<center>` tag was deprecated in [HTML 4](https://en.wikipedia.org/wiki/HTML#HTML_4) in 1997. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

**Comment by Harindulk** [comment]
> The `<center>` tag was deprecated in [HTML 4](https://en.wikipedia.org/wiki/HTML#HTML_4) in 1997. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

Thanks, I don't know that
