### ISSUE TITLE
Missing left focus border in notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117528]
It looks like it's there in the left-most editor, but when there are multiple split editors, it doesn't show up on any other editor.

![image](https://user-images.githubusercontent.com/323878/108933523-23f0e700-7600-11eb-869b-0f725628b800.png)

**Comment by misolori** [comment]
Nice catch, appears like the split pane border sits ontop of the left border. Updating the `z-index` for the cell focus:

![image](https://user-images.githubusercontent.com/35271042/108946495-62dc6800-7613-11eb-88b5-09d2e1b02b1a.png)
