### ISSUE TITLE
Revisit loose primary group check

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117593]
@jrieken it was a copy paste mistake for me. I will change in debt week to have a more precise check. I want only one primary group.

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/117456#issuecomment-785118927_

**Comment by jrieken** [comment]
Consider to change this so that `isPrimaryGroup` isn't a callback but just a string with the group name

**Comment by isidorn** [comment]
Started to look into this. I will change that the isPrimaryGroup is not a callback but just a string.

**Comment by jrieken** [comment]
@isidorn There is one other case (which you added) and that's a special 1_run group. It's used in editor titles and I am not sure what that's used for

**Comment by isidorn** [comment]
Yeah that is the only problem here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/titleControl.ts#L227

That was a previous recommendation for extensions how to add run editor title actions.
However since we now have a better recommendation (to use submenus which you introduced) I think we can remove that.
We just need to make sure all the extensions jump on your new approach.

fyi @weinand  in case I am missing something

**Comment by isidorn** [comment]
I have optimistically pushed this. Let's see if I broke somebody, it is first day of debt week so best time to do this...

**Comment by weinand** [comment]
@isidorn @jrieken I'll add an item to the release notes that deprecates the `"group": "1_run@20"` stuff in favour of the new "editor/title/run" submenu.

BTW, I've adopted the new feature in Mock Debug and it works great. Only minor issue I see is the missing visual cue for a submenu.

<img width="200" alt="2021-03-01_14-58-53" src="https://user-images.githubusercontent.com/1898161/109507208-c5fc4d80-7a9e-11eb-9f58-6c83af221a90.png">

What will happen if I press the play button? "Run" or a submenu? 

@isidorn what's about accessibility of the new submenu?

**Comment by isidorn** [comment]
@weinand great, thanks for adding it in the release notes!
I will check it out for accessibility. Once you push to mock-debug let me know so I can just try it out. I think submenus should just work for accessibility, since we already have them in other places.

**Comment by jrieken** [comment]
> @isidorn what's about accessibility of the new submenu?

fyi - this the default sub menu as it is used in different places. So if they are accessible than this should be too

**Comment by weinand** [comment]
But you never know whether there is a submenu behind the run icon...

**Comment by jrieken** [comment]
Yeah, that's a problem with our submenu

**Comment by isidorn** [comment]
Yeah from the accessibility point of view, if there is a submenu behind it we should set
`aria-haspopup=true` on the item. If it does not have a submenu it should be set to `false`
@jrieken is it possible to set this up front? Or the menu does not know?

**Comment by weinand** [comment]
@jrieken I've added this to your release notes item (instead of creating a new item):

https://github.com/microsoft/vscode-docs/commit/10539ca5940b99fd5dc6e7c831a75890c2df2ce1

<img width="730" alt="2021-03-01_15-30-55" src="https://user-images.githubusercontent.com/1898161/109511352-3dcc7700-7aa3-11eb-8a99-ce05c135638f.png">

**Comment by weinand** [comment]
@isidorn I've pushed the changes to Mock Debug.

**Comment by jrieken** [comment]
Thanks @weinand

**Comment by isidorn** [comment]
I tried it out, and even the `aria-haspopup=true` is there.
So seems to work great
![Screenshot 2021-03-01 at 15 39 30](https://user-images.githubusercontent.com/1926584/109512378-55582f80-7aa4-11eb-9849-a3202601098a.png)

**Comment by isidorn** [comment]
I am just not sure how to get into a case when there is only 1 action there
@jrieken can you just make sure that in that case `aria-haspopup` is false

**Comment by isidorn** [comment]
Actually I changed mock-debug to only have one action, and in that case the `aria-haspopup` is not there. It is not a submenu. So we are good in total

**Comment by weinand** [comment]
@isidorn thanks for verifying!

**Comment by connor4312** [comment]
Thanks for fixing it in testing as well 🙂
