### ISSUE TITLE
Text colouring garbled

### ISSUE THREAD

**Issue by pierreverbakel** [microsoft/vscode#117543]
Issue Type: <b>Bug</b>

When working on my files, of which some are maybe long like 8 Megabtyes (just mentioning). The colouring is garbled in the sense that within a it starts with the correct colour, but somewhere in the word it changes to another colour and maybe back again to the correct colour. But anything can happen.
The text seems to be coloured correctly when loading after a fresh start of Visual Studio Code. 

BTW the interpretation of the code gets very slow with these file sizes. 
Mind you I am using files that are a fraction of the memory available (32 Gigabytes). 
Thanks!

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (15.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.1.0
php-debug|fel|1.14.5
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.1
vscode-pull-request-github|Git|0.22.0
better-cpp-syntax|jef|1.15.5
jupyter|ms-|2020.12.414227025
remote-containers|ms-|0.154.2
remote-ssh|ms-|0.62.0
remote-ssh-edit|ms-|0.62.0
remote-wsl|ms-|0.52.0
cmake-tools|ms-|1.5.3
cpptools|ms-|1.2.0
cpptools-extension-pack|ms-|1.0.0
notepadplusplus-keybindings|ms-|1.0.5
vsliveshare|ms-|1.0.3375
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
platformio-ide|pla|2.2.1
geo-data-viewer|Ran|2.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including what language you are coding in, and whether Extension Bisect reveals anything. Also, can you paste a screenshot?

**Comment by pierreverbakel** [comment]
OK, it is an intermittent problem but regularly comes back. I believe it depends on the amount of editing I do. 
It is my first post here, and the form from within Visual Code did not have any image upload capability.
To put in words: It looks very 'festive' and random. The extension doing the colouring of the text based on the language I am using. I am not sure if that is IntelliSense or another module.  
I am coding in C/C++, filename is main.cpp (I guess it adapts to the .cpp to select the language for colouring). I will post a screenshot when it happens again, which I expect in the comming days.

**Comment by gjsjohnmurray** [comment]
If you capture a screen region onto your clipboard you should be able to paste it into the GitHub textarea field when you add a comment. Or drag a gif file and drop it onto that field.
