### ISSUE TITLE
Ports view: too many different font weights and sizes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117569]
Testing #117250

Compare the font, weight and size of the new table headers with the rest, I think they do not look like they belong there:

![image](https://user-images.githubusercontent.com/900690/108996203-6406a700-769e-11eb-96e2-7c03f9bacbe5.png)

**Comment by alexr00** [comment]
@joaomoreno do you think it is worth providing different defaults for the table?

**Comment by joaomoreno** [comment]
What is the suggestion? All caps? I'm not so sure that's such a good idea. And actually `8080` is the one that stands out the most for me, since it uses a lower font size than the workbench default.

I'd leave this for @misolori to tweak.

**Comment by bpasero** [comment]
In my picture we have 3 times "Port" and the one that should be the smallest imho stands out most. I would bring the font weight and style closer to the content of the table.

**Comment by alexr00** [comment]
Worth noting: @bpasero  you have an extra "Ports" in there, probably from moving the view about in the past:
![image](https://user-images.githubusercontent.com/38270282/109014752-b783ef80-76b4-11eb-993f-b7a638889c9d.png)

**Comment by bpasero** [comment]
Yeah I did that on purpose to show what kind of labels you can end up with.

**Comment by alexr00** [comment]
Font size is not specific to the ports view, it's coming from 

https://github.com/microsoft/vscode/blob/9394e571e5508d476a97acb937f422f9683edf24/src/vs/workbench/browser/media/part.css#L92-L94

**Comment by joaomoreno** [comment]
> In my picture we have 3 times "Port" and the one that should be the smallest imho stands out most. I would bring the font weight and style closer to the content of the table.

Font size is exactly the same, just bold.

**Comment by misolori** [comment]
All of our table headings are the same font-size and font-weight, so they are consistent in that regard:

![image](https://user-images.githubusercontent.com/35271042/109044684-8b05ae80-7687-11eb-8c89-6d3943b233f4.png)

I think this is more of an issue with **views** and **titles** and their hierarchy (which IMO is not a table issue). Ideally you'd want the highest items to have the highest font-size and then cascade down like:

![image](https://user-images.githubusercontent.com/35271042/109045979-159add80-7689-11eb-8fc6-dc5bcf698eb5.png)


But that's a different discussion 😄  happy to bring it up in the next ux sync or post in our ux channel
