### ISSUE TITLE
Support to show icons in more places (tabs, open editors, quick open)

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#11751]
- VSCode Version: 1.51

It would be great if VScode supported an option to show the icons in open tabs and editors.

**Comment by ramya-rao-a** [comment]
The [release notes](http://code.visualstudio.com/updates/v1_5#_workbench) does talk about eventually supporting icons for tabs. 

"Open editors" here refer to the opened editors as opposed to open editors section on the side bar in #11287

**Comment by bpasero** [comment]
Icons are now showing in these additional locations once you pick an icon theme:
* open editors view
* tabs
* title in editor when tabs are disabled
* search results
* problems
* quick open / editor pickers

**Comment by infinnie** [comment]
I wish we were able to configure its behavior on where icons can show up.

**Comment by bpasero** [comment]
@infinnie where do you want to not see icons?

**Comment by infinnie** [comment]
@bpasero wherever it seems too visually cluttered.

**Comment by bpasero** [comment]
@infinnie like?

**Comment by joshsleeper** [comment]
@bpasero I think what @infinnie is trying to say is that it'd be nice to be able to turn the icons on or off in each location based on one or more config entries.

That is, if I run a small screen with a lot of tabs for example, maybe I'm not keen on showing the icons on the tabs themselves.

I'm not sure how hard that would be to add support for a config entry per-icon-location (or maybe just one config entry that takes an array/dict/etc.), but I believe that's what he's suggesting.

**Comment by infinnie** [comment]
@joshsleeper BTW I am female. What a pity it is for GitHub not to be able to let us config and display our sexes (or genders?)

**Comment by joshsleeper** [comment]
@infinnie And I've been trying so hard to be more gender neutral with my comments too! Bah on me, super sorry about that, I promise it wasn't ill intended.

**Comment by bpasero** [comment]
@joshsleeper for that reason there is a setting to disable icons in tabs. that is the only setting we provide for now. I am still trying to find out where else @infinnie would want to configure this.

**Comment by infinnie** [comment]
@bpasero That would be fine!

**Comment by bpasero** [comment]
Ok then it looks like we are good.

**Comment by jtlowe** [comment]
Glad to see this setting! It wasn't immediately clear to me what the setting ".showIcons" actually did, even after reading the comment above it. Maybe "workbench.editor.showTabIcons" would be better.

**Comment by bpasero** [comment]
@jtlowe no, the icons also show up when tabs are disabled

**Comment by jtlowe** [comment]
@bpasero I see what you're saying. My last thought would be something like: "Controls if opened editors should show with an icon **next to their title** or not." I don't know if this would have helped me initially though. I need to improve on my vscode terminology. Thanks!
