### ISSUE TITLE
Jupyter Notebooks

### ISSUE THREAD

**Issue by webzest** [microsoft/vscode#117520]
Issue Type: <b>Bug</b>

After installing the latest updates, my jupyter notebooks no longer works.

VS Code version: Code - Insiders 1.54.0-insider (9ecd3fc3022e8c154aff868f74bd5d77f7d4a2ea, 2021-02-23T10:46:22.816Z)
OS version: Windows_NT x64 10.0.21313

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (19.29GB free)|
|Process Argv|--crash-reporter-id 67d8ba2a-36e3-401e-9d61-c01ba3911197|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
project-manager|ale|12.0.1
markdown-extension-pack|bat|0.6.0
vscode-django|bat|1.3.0
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.1.6
csharp-auto-formatter|bil|0.1.0
gitignore|cod|0.6.0
supersharp|cra|0.1.4
excel-to-markdown-table|csh|1.2.2
markdown-table-prettify|dar|3.2.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
git-extension-pack|don|0.1.3
githistory|don|0.6.14
python-extension-pack|don|1.6.0
gitlens|eam|11.2.1
code-runner|for|0.11.2
mdmath|goe|2.5.1
gc-excelviewer|Gra|3.0.41
vscode-test-explorer|hbe|2.19.5
gzipdecompressor|Hyu|1.2.0
r|Iku|1.6.4
r-pack|Iku|0.0.2
path-autocomplete|ion|1.17.1
vscode-edit-csv|jan|0.5.5
docomment|k--|0.1.20
km-csharp-extensions|kab|0.0.3
kite|kit|0.142.0
csharpextensions|kre|1.3.6
gzip-decompress|mao|1.0.0
markdown-shortcuts|mdi|0.12.0
r|Mik|0.0.19
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.3
jupyter|ms-|2021.3.593162453
debugger-for-chrome|msj|4.12.12
vscode-yaml|red|0.15.0
r-lsp|REd|0.1.14
markdown-preview-enhanced|shd|0.5.16
python-pack|Swe|0.1.15
vscode-markdown-paste-image|tel|0.12.3
html-preview-vscode|tht|0.2.5
rmarkdown|Tia|0.0.14
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.11
jinja|who|0.0.8
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
pythonvspyt602cf:30260315
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
core-portspanel:30257802
pythontb:30258533
openwslfolder:30257850
vscoresta800:30263253

```

</details>

**Comment by webzest** [comment]
Latest version killed Jupyter Notebooks.

**Comment by rebornix** [comment]
@webzest can you please try with today's Insiders and see if it works?
