### ISSUE TITLE
Add an API for a notebook kernel to modify its list of supported languages at runtime.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#117506]
The `NotebookKernel` interfaces exposes a `supportedLanguages: string[]` field, but for kernels that support a dynamic list of languages, there's currently no way for that list to be updated in a meaningful way at runtime.

E.g., the .NET Interactive notebook extension supports doing something like this: `#!connect -type=MySQL -name=sql -connectionString="abcd"` and from that point forward, a cell language of `SQL` should be supported, but not necessarily before.

One way to accomplish this would be to add an event on `NotebookKernel` called `LanguagesChanged` or similar that either contained a new string array of the supported languages _or_ instructed any listeners that a new string array was present in the `supportedLanguages` field; I don't have a strong preference either way.

**Comment by jrieken** [comment]
This has happened with the new `NotebookControllers` - properties like label, description, supported languages etc can be modified freely
