### ISSUE TITLE
Terminal too narrow: Output with long lines (wrapping) freezes/crashes vscode

### ISSUE THREAD

**Issue by Lesik** [microsoft/vscode#117682]
I hope I can help make vscode a better product with this report. I made the best efforts to search for duplicate issues and follow the submitting guide to include all relevant information. Please advise if more information is needed.

- VS Code Version: 1.53.0
- OS Version: Debian buster
- any shell should trigger this, I confirmed with bash and Debian's dash
- I tried setting `"terminal.integrated.rendererType": "dom"` [as described in a similar issue][similar-issue] with no avail

[similar-issue]: https://github.com/microsoft/vscode/issues/113247

#### Steps to Reproduce:

1. Open a fresh vscode window with extensions disabled
2. Doesn't need a project or file open, the welcome page suffices
3. Open the terminal (<C+`>)
4. Either resize the window so that the terminal is narrow, or right-click on the terminal's frame and select "move panel to right" (this step is important)
5. Run any command that produces a lot of single-line output. For example, `cat vscrash.json` from [vscrash.zip](https://github.com/microsoft/vscode/files/6043458/vscrash.zip) (extract first)
6. The whole vscode window will freeze for about 10 seconds, after which this popup will appear:

![Screenshot from 2021-02-25 14-13-13](https://user-images.githubusercontent.com/2021487/109163289-74d81b00-7779-11eb-95d8-379b4b40797e.png)

#### Why I think it's relevant

You might think: Ok, don't cat large files then and nobody is resizing their terminal to such a narrow size anyway (as it's too narrow to work in). But I actually stumbled upon this bug while debugging an API with `curl`, which printed a long single-line JSON into the terminal, which isn't uncommon. And you don't have to resize your vscode window manually to trigger this, you can just put the terminal pane to the right, which will make it narrow. I always use vscode with the terminal on the right, and the feature is built-in into vscode, so I imagine lots of people like to use it.

#### Does this issue occur when all extensions are disabled?

Yes

#### Process explorer

The process explorer (Help -> Open process explorer) stays active during the freeze, and shows the window consuming more and more CPU and memory until the point when the crash popup (pictured above) appear, then a bunch of processes disappear (including window) and the usage is back to normal:

Shortly after running the steps to reproduce:

![](https://user-images.githubusercontent.com/2021487/109163290-7570b180-7779-11eb-9ca0-94655bffb2d3.png)

A couple of seconds after running the steps to reproduce:

![](https://user-images.githubusercontent.com/2021487/109163291-7570b180-7779-11eb-894e-c5b35dad524d.png)

After about 10 seconds when the crash popup appears:

![](https://user-images.githubusercontent.com/2021487/109163293-76094800-7779-11eb-8b26-4bd7baf8bd96.png)

**Comment by jeanp413** [comment]
Created a PR #117734 fixing this
