### ISSUE TITLE
Extension menu items not appearing in order defined by product.json

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#117638]
Testing: https://github.com/microsoft/vscode/issues/117259

Version: 1.54.0-insider (user setup)
Commit: c47da720f351455681978a48edc4d9a0d095ea0e
Date: 2021-02-24T11:23:03.943Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Add the following to your product.json, when creating a new Typescript extension

```
"commands": [
			{
				"icon": "$(rocket)",
				"command": "extension.helloWorld",
				"category": "Fluent",
				"title": "Hello World"
			},
			{
				"icon": "$(search)",
				"command": "extension.quickInput",
				"category": "Fluent",
				"title": "Quick Input Samples"
			}
		],
"menus": {
			"editor/title": [
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				}
			]
		}
```

2.  You should see the following when you build and run the extension - 
![image](https://user-images.githubusercontent.com/1389808/109085800-38e07f80-76bf-11eb-897e-d976c827f838.png)

The icons should alternate between rocket and search, as defined by the order in the JSON.

**Comment by jrieken** [comment]
The order isn't defined by the position the package.json but must explicitly set or is inferred from the label. To explicitly set the order you use `<group>@<weight>`, e.g `"group": "navigation@9"` etc. When weights are equals (which they are in their absence) the label is used

**Comment by gjsjohnmurray** [comment]
@devinvalenciano please edit your issues so that they refer to the correct filename, package.json
