### ISSUE TITLE
Waking from sleep theme issues

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117653]
![image](https://user-images.githubusercontent.com/35271042/109103445-c46a0880-76df-11eb-98ba-0cb904ae8583.png)

I've got auto dark mode enabled on my mac and have the `window.autoDetectColorScheme` setting enabled. My computer was asleep in the afternoon (daytime) and when I returned in the evening the computer turned to dark mode, as well as my VS Code theme but the icons in the editor did not. Everything else remained the same. If I refresh my window it returns to normal.

**Comment by bpasero** [comment]
> but the icons in the editor

Which are those in the screenshot?

**Comment by misolori** [comment]
Too right actions, they’re a little hard to see because they’re using the light theme colors (because I was on light mode before closing my laptop)
