### ISSUE TITLE
Explorer

### ISSUE THREAD

**Issue by drcampbell** [microsoft/vscode#117630]
Issue Type: <b>Bug</b>

Explorer is impossible to use with extensions.  You can't resize the sections and the Source Control section is impossible to navigate for large amounts of files.  

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 66754dc5-ebd5-4ff4-afb8-94c56488f53c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.5
emojisense|bie|0.8.0
vscode-intelephense-client|bme|1.6.3
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
vscode-pull-request-github|Git|0.23.1
msgpack|hub|0.0.7
phpcs|ika|1.0.5
php-cs-fixer|jun|0.1.158
auto-dark-mode|Lin|0.1.7
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
github-issues-prs|ms-|0.9.2
debugger-for-chrome|msj|4.12.12
vscode-yaml-sort|Pas|3.1.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by drcampbell** [comment]
Here is a gif of the problem.  As you can see there is a ton of Git Lens
crap that I can't get rid of and I can't resize the windows, making the
explorer a total pain to use, because you can only see 10 lines at a time.

**Comment by gjsjohnmurray** [comment]
Unfortunately when images are sent to GitHub by replying to a notification email they get lost. Instead please visit the issue on the GH website and copy+paste or drag+drop your gif file into the comment field. You can then use the Preview tab to verify it before posting.

**Comment by isidorn** [comment]
This is caused by GitLens extension. Either uninstall it, or right click hide the views
