### ISSUE TITLE
Autorun runs whole suite when only single test was previously run

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117615]
Testing https://github.com/microsoft/vscode/issues/116383

Not sure if this is a bug or not, but this was unexpected to me:
- Followed steps in https://github.com/microsoft/vscode/issues/116383#issuecomment-783785265
- Turned on auto run
- Ran a single test within a suite
- Edited that test and saved the file

The entire suite ran after the delay, I was expectingly only the test I had edited and run previously to re-run.

**Comment by connor4312** [comment]
This is just a result of the test provider, which invalidates all tests in the file when any of them are changed. A smarter test provider might be able to trace dependencies and changes more exactly, but that's a large chunk of work.
