### ISSUE TITLE
Tabs or spaces should be considered when comparing python codes

### ISSUE THREAD

**Issue by mcwindy** [microsoft/vscode#117609]
In this image, tabs or spaces are ignored which is important for python codes.
![image](https://user-images.githubusercontent.com/40684304/109042425-25f39c80-770b-11eb-8c21-de28e6e961a3.png)

Moreover,
![image](https://user-images.githubusercontent.com/40684304/109041939-8e8e4980-770a-11eb-8703-31f2f19ee623.png)

**Comment by rzhao271** [comment]
Does disabling the `diffEditor.ignoreTrimWhitespace` setting help?

**Comment by mcwindy** [comment]
Yes, that's what I wanted. Thank you.
