### ISSUE TITLE
Markdown preview gets empty

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117600]
Testing #117279

1. Close all editors
2. Open a Markdown file
3. Open Preview to the Side
4. Focus text editor again
5. Use Quick Open to open the Preview editor on the left side

🐛 Right side Preview becomes empty

![recording (2)](https://user-images.githubusercontent.com/22350/109025097-4708ae80-7673-11eb-9954-c788a0fa41d7.gif)

**Comment by jeanp413** [comment]
This issue occurs with any `WebviewInput` for example release notes.
Pushed a PR #118397 with a possible fix

![webview_move](https://user-images.githubusercontent.com/25115070/110280612-1d238600-7fa9-11eb-89f2-71e6afa5f133.gif)
