### ISSUE TITLE
can't start from installed path alias without working python?

### ISSUE THREAD

**Issue by hedefalk** [microsoft/vscode#117690]
Issue Type: <b>Bug</b>

* install command alias for code-insiders
* try it:

✗ code-insiders                                                                                
Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
Python runtime state: preinitialized

/opt/homebrew/bin/code-insiders: line 10: ./MacOS/Electron: No such file or directory
~ 
✗  

Lookls like the python script to get the real path fails and then it can't find electron binary:

function realpath() { python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0"; }

Guess my nix/home-manager python3 might be broken, but hey, didn't know  that was a dependency. I removed it since I really don't want any globals anyway and then code will start using /usr/bin/python python instead.

VS Code version: Code - Insiders 1.54.0-insider (59c31364c707ee962cc594389966801af4ce69bd, 2021-02-25T07:45:36.865Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id d60689c6-ded9-49e3-a28a-43297a5a280a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
nix-env-selector|arr|1.0.2
Nix|bbe|1.0.1
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
scad|efb|1.0.1
prettier-vscode|esb|5.9.2
go|gol|0.22.1
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.51
monkey-patch|ioc|0.1.12
cypher-query-language|jak|1.0.2
latex-workshop|Jam|8.16.0
hoogle-vscode|jca|0.0.7
vscode-peacock|joh|3.9.1
language-haskell|jus|3.4.0
vscode-github|Kni|0.30.4
graphql-for-vscode|kum|1.15.3
marko-vscode|Mar|0.10.4
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.593162453
cpptools|ms-|1.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
vscode-paste-image|mus|1.0.4
ide-purescript|nwo|0.23.3
language-purescript|nwo|0.2.4
vetur|oct|0.32.0
vscode-jest|Ort|3.2.0
dhall-lang|pan|0.0.6
explorer-exclude-vscode-extension|Red|1.2.0
rust|rus|0.7.8
vscode-workspace-switcher|sad|1.15.3
scala|sca|0.5.2
metals|sca|1.10.0
crates|ser|0.5.6
fish-vscode|sky|0.2.1
haskelly|UCL|0.5.5
haskero|Van|1.3.1
prettify-selected-json|vth|1.0.3
debug|web|0.25.0
vscode-open-in-github|ziy|1.3.6

</details>

**Comment by joaomoreno** [comment]
> Guess my nix/home-manager python3 might be broken, but hey, didn't know that was a dependency. I removed it since I really don't want any globals anyway and then code will start using /usr/bin/python python instead.

Glad to know you got it fixed. Yes, in macOS, we depend on Python which is usually fine since the OS ships with it.
