### ISSUE TITLE
Can't Run C++ executable on Linux.

### ISSUE THREAD

**Issue by Karim-Fadi** [microsoft/vscode#117666]
I use vscode for c++ Development. However i can only run the executable files via terminal but when i double tap the executable in the files for example it does not run and it says it cant open shared libraries files. So any way how to do it. I am sure there is something i must do in the tasks.json file but i don't know what it is. So any help ?

**Comment by rzhao271** [comment]
This might be an extension issue. Can you list your extensions, and can you share a screencap of the situation (e.g. using https://gifcap.dev) or a sample repo?
