### ISSUE TITLE
Welcome page shifts as it is rendered

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117628]
I have had the welcome page disabled for a long time, so I don't know whether this is new. But I've had it enabled for a couple days and noticed that it shifts positions when it's rendered, which makes a window load feel not smooth.

It's hard to catch

![Feb-24-2021 14-45-00](https://user-images.githubusercontent.com/323878/109076085-e4cd9f00-76ae-11eb-8907-2a7906e57db5.gif)

State 1:

![image](https://user-images.githubusercontent.com/323878/109076122-f151f780-76ae-11eb-959e-0f8045be2617.png)

State 2:

![image](https://user-images.githubusercontent.com/323878/109076145-fc0c8c80-76ae-11eb-96cc-f720242882d8.png)

**Comment by JacksonKearl** [comment]
Good eye. When the recent list gets its entries the height of the main content increases, causing it to shift upwards to remain centered. Fixed by reserving more space for the recent list when the window is large enough for this to matter.
