### ISSUE TITLE
TestResults naming is redundant and confusing

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117613]
Testing #117307

A classic issue I have with APIs is nested objects having similar names down the line.

In this case, its something like: `vscode.test.testResults.results[i].result` and `vscode.test.testResults.results[i].children[j].result`.

The naming of `TestResults` and `testResults` on the `vscode.test` object implies this is a collection of results (and loosely implies that it is the complete list of test results for the workspace at a given time), but it isn't. It is more like a collection of test runs that in turn have a collection of items that were just run and results are provided. 

Another way to state the confusion is that the names imply that I'm getting an api shape that has quicker access to the results, but the effective api is just test items with extra things appended.

**Comment by sbatten** [comment]
This snippet shows the variable names highlighting the difference in function vs naming of each layer

```ts
    vscode.test.onDidChangeTestResults(() => {
      for (const testResultInfo of vscode.test.testResults) {
        for (const itemWithResults of testResultInfo.results) {
          printTestResults(itemWithResults);
        }
      }
    })
```

**Comment by connor4312** [comment]
Forgot to label this testing so missed it, but cleaned this up. The `TestResultSnapshot` now directly contains the results, so you will have `item.result.state` and `item.result.messages`. Much cleaner.
