### ISSUE TITLE
Typescript service dies right after opening VS Code

### ISSUE THREAD

**Issue by francescopalmiotto** [microsoft/vscode#117671]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:20.056Z)
OS version: Windows_NT ia32 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.83GB (8.14GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/frpalmio/Source/Repos/teams-modular-packages --crash-reporter-id ab65c35b-635b-45af-ae98-3490b93afc0b|
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
graphql-for-vscode|kum|1.15.3
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3784
teams-dyson|tea|0.0.2020081901
vscode-icons|vsc|11.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please use the Start Extension Bisect command and follow its instructions to try and discover if an extension is causing this.
