### ISSUE TITLE
[themes] confusing alignment of file in folders in folder-less themes

### ISSUE THREAD

**Issue by dylan-kerr** [Microsoft/vscode#11762]
The Seti icon theme released with VS Code 1.5 does not provide icons for folders (open or closed).

This causes a confusing misalignment between the names of folders and files at the same level of the hierarchy, making the files appear to be children of the last folder.

Would it be possible to enable folder icons with the Seti theme?
- VSCode Version: 1.5.1
- OS Version: Windows 10

**Comment by fhelwanger** [comment]
Here's a screenshot for reference:

![image](https://cloud.githubusercontent.com/assets/11396047/18390055/123b782a-767f-11e6-8866-b9f97b86ca14.png)

It's very confusing to me. I keep trying to collapse the `img` folder, but it's already collapsed :confused:

**Comment by aeschli** [comment]
@bpasero To find out if there are folder icons defined, use
`this.container.getElementsByClassName('explorer-item folder-icon');` should do the trick

**Comment by bpasero** [comment]
@aeschli let me know when you pushed the new CSS class for me to pick up.

**Comment by aeschli** [comment]
Think more about it I the css stylesheet rule does not help us.
- To find out if that css rule is defined, you need to iterate though all stylesheets and find it, or assign it to a DOM element and probe.
- you would have to have some kind of event listener that knows when a theme has changed

It's basically adds a coupling from the explorer to the theme service that we didn't had so far.
If we go that way I'd rather add real API (property and event) on the theme service.

Alternative is still that the theme service could style the tree.

**Comment by bpasero** [comment]
@aeschli yes you are right, needs more thinking. maybe you should just use a dummy folder icon that is transparent if a theme does not define one so that we get the same nice padding as all other icons?

**Comment by eamodio** [comment]
While I completely agree that the indenting can be confusing (and should be addressed), please don't add folder icons -- I love that Seti doesn't have them. Makes it much easier to scan for "important" things.

**Comment by arroyocode** [comment]
+1 for Minimal theme folder icon included in Seti theme. Is it silly to combine the folders into the Seti theme as a wholly new theme (i.e.: Maximum) to appease devs on either side of the fence?

**Comment by aeschli** [comment]
IMO a folder-less theme should work nicely as well and I want to fix that.
A folders on/off option is a good idea.

For all other requests, I'm sure the community will provide more themes, we don't need to cover it all with our built-in themes.

**Comment by dylan-kerr** [comment]
Although my original request did say "please add folder icons", it is really the indentation that's the issue. The existing open/close toggle is effectively a default folder icon, and I feel like it would make sense for the file icons to sit at the same place in the DOM (`.content:before`) to achieve the consistent indentation.

At the moment icon themes with a folder icon display both the open/close toggle and the folder icon - is this correct? They seem to be filling the same role.

**Comment by aeschli** [comment]
@dylan-kerr Yes, that correct. Good points!

**Comment by The-Smallest** [comment]
Hi, 
For those, who still search for solution: there is "seti"-theme extended with folder icon in marketplace: [qinjia.seti-icons](https://marketplace.visualstudio.com/items?itemName=qinjia.seti-icons)

**Comment by octref** [comment]
This issue is not limited to Seti only:

![image](https://cloud.githubusercontent.com/assets/4033249/19531932/6a521b20-95ee-11e6-9d02-0c58b13f709d.png)

I mistake `buildfile.js` as child of `test` every day, and I believe I'm not the only one.

Sublime shows the structure in a clear manner.

![image](https://cloud.githubusercontent.com/assets/4033249/19531980/a6abba7c-95ee-11e6-823a-2363a8715bef.png)
