### ISSUE TITLE
"TestRun" is a strange name as a subclass of "TestRunOptions" 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#117602]
Testing #117304

"TestRun" is a strange name as a subclass of "TestRunOptions".
May be "TestRunStateOptions"?

**Comment by connor4312** [comment]
Or perhaps make TestRunOptions `TestRequestOptions`? The options can be passed by other extensions when they want to request tests to be run, the 'TestRun' is the options plus mutation methods that is given to the test provider.
