### ISSUE TITLE
enumItemLabels key not exposed to the user

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode#117696]
You can localise many aspects of package.json, including config, but you cannot localise the options in an enum dropdown - you can but your extension will get the translated value. I think these should be translated, but the value the extension gets should be a fixed value no matter what langauge is enabled in the GUI. Currently I now have to keep the dropdown values in english and add enumDescriptions for each label explaining what those mean in other languages.

Can you add an enumLabels array to the enum configuration and use that for labels within the dropdown and use the enum array just for the values that a develop gets when accessing settings? Currently the enum array is used as both label and value.

**Comment by sandy081** [comment]
You can use `enumDescriptions` to explain about your enums and also translated. See how we use it at other places:

https://github.com/microsoft/vscode/blob/a799375663cf4677ba2e52a48ebb63229bf64344/extensions/git/package.json#L164-L1675

**Comment by sketchbuch** [comment]
I already use this, but it is not a very good solution. It should be possible to localise what users see in the dropdown @sandy081

**Comment by sandy081** [comment]
@sketchbuch I see, thanks for clarification.

@aeschli We already have `enumItemLabels` to use internally for Settings editor. Can this be extended to json language server so that user can see the labels in the file and also in the settings editor?

**Comment by aeschli** [comment]
@sandy081 Do you mean to also use the `enumItemLabels` in the JSON editor? Can you make an example of what should be seen there? IMO the labels seen in code complete should always correspond to the text that is typed.

**Comment by sandy081** [comment]
I see, makes sense and let's make it Settings Editor only feature and JSON shows the ids.

**Comment by KrabsWong** [comment]
What is the current progress of this issue?

**Comment by rzhao271** [comment]
It turns out `enumItemLabels` already exists, but we never exposed it to the user. 
See `workbench.iconTheme` in the Settings editor for an example of a setting that uses it.
