### ISSUE TITLE
VSCode crashes right after opening the windows terminal.

### ISSUE THREAD

**Issue by Dinuda** [microsoft/vscode#117673]
- VS Code Version: the latest release
- OS Version: Windows 10

No problem with wsl or powershell
Steps to Reproduce:

1. Open VSCode
2. Open windows termial

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please paste version info from Help\About dialog, plus a screenshot showing the crash.

Also answer the question about whether it happens when all extensions are disabled. One way of testing this is to launch VS Code from a command shell like this:
```
code --disable-extensions
```

**Comment by Dinuda** [comment]
Hi, Yes I figured out a workaround. Thanks. Ill be closing this issue.
