### ISSUE TITLE
Problems with the node intellisense

### ISSUE THREAD

**Issue by AlejoDLP** [microsoft/vscode#117636]
Issue Type: <b>Bug</b>

The intellisense of node in javascript file disappear an there is no intellisense for require, module.export, etc. But when I install with npm @types/node the intellisense

steps:

1. Open VsCode
2. Create an index.js file
3. start using built in module `const fs = require('fs')`
4. fs don't have intellisense

Actual result: It don't appear no intellisense if I don't install @types/node
Expected result: The intellisense appears without installing @types/node 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
flask-snippets|cst|0.1.1
vscode-eslint|dba|2.1.14
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
gc-excelviewer|Gra|3.0.41
json2ts|Gre|0.0.6
rest-client|hum|0.24.4
vscode-peacock|joh|3.9.1
vscode-colorize|kam|0.10.0
ts-extension-pack|loi|0.2.0
vscode-language-babel|mgm|0.0.30
dotenv|mik|1.0.1
vscode-language-pack-es|MS-|1.53.2
csharp|ms-|1.23.9
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.1
vscode-typescript-tslint-plugin|ms-|1.3.3
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
typescript-hero|rbb|3.0.0
trailing-spaces|sha|0.3.1
move-ts|str|1.12.0
vscode-djaneiro|the|1.4.2
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.9.15

**Comment by mjbvz** [comment]
Does your workspace have a `package.json` file?

Node IntelliSense works for me in a basic project with just a js file and a package.json:

![Screen Shot 2021-02-24 at 4 52 32 PM](https://user-images.githubusercontent.com/12821956/109086586-b1940b80-76c0-11eb-8ecf-6acdf42f4a22.png)

**Comment by AlejoDLP** [comment]
This is the problem
![2021-02-25](https://user-images.githubusercontent.com/74614668/109160372-b4841000-7743-11eb-8c61-23d194b99fd1.png)

but i can have intellisense when install @types/node

![2021-02-25 (3)](https://user-images.githubusercontent.com/74614668/109160703-20ff0f00-7744-11eb-83fe-7fd5aa072472.png)

**Comment by mjbvz** [comment]
Does your workspace have a `package.json` file?

**Comment by AlejoDLP** [comment]
Yes it have
