### ISSUE TITLE
Multiple instances cause Powershell parsing error.

### ISSUE THREAD

**Issue by JohnMarkHowell** [microsoft/vscode#117692]
Issue Type: <b>Bug</b>

I have not yet been able to reproduce this consistently, but when working with two instances of VSCode and having Powershell files open in each, (possible one of the files was the same in both instances), after a couple of hours of making changes in both instances, there appears to be an issue in VSCode that causes invalid Powershell script parsing syntax errors to appear in valid Powershell script. The area of code that I saw this occur was an if block.

The only way I could resolve it, was to close down all VSCode instances, and reopen two instances and reopen the desired files. Once done, the erroneous syntax parsing errors disappeared. Note: No Powershell code was changed between the erroneous syntax parsing errors and then reopening the files and they disappeared.

See above description for the only way I have to reproduce the issue.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (9.53GB free)|
|Process Argv|C:\\repos\\APIM --crash-reporter-id fc77968c-59ed-474e-8cec-8bd5b575889e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-wsl|ms-|0.53.4
azurecli|ms-|0.5.0
hexeditor|ms-|1.4.0
powershell|ms-|2021.2.2
azurerm-vscode-tools|msa|0.14.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by rzhao271** [comment]
Does this issue still occur without extensions?
I see you have a powershell extension so I wonder if it has to do with that extension.

**Comment by JohnMarkHowell** [comment]
It would likely be in the extension because that is the component that does the actual script parsing. My thought is that there is a shared process that the parser is using and that is using a variable/stack/queue/etc. that is not thread safe.

Disabling the extension would remove the parsing errors because it would no longer be parsing. ;)

**Comment by TylerLeonhardt** [comment]
Hi @JohnMarkHowell the parse errors are likely coming from the PowerShell extension for VS Code which can be found here:
https://github.com/PowerShell/vscode-powershell

Can you open an issue over there? Oh, also make sure you attach the logs to the issue. Info can be found here:
https://github.com/PowerShell/vscode-powershell/blob/master/docs/troubleshooting.md#providing-information-about-your-environment
