### ISSUE TITLE
Extensions: Product icons contribution is missing

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#117691]
![Screenshot (444)](https://user-images.githubusercontent.com/9638156/109196813-3eb48e80-77ad-11eb-9047-c71c6320e81b.png)

```
@tag:product-icon-theme
```

No padding for this message looks different from `Details` & `Changelog` that have a lot of empty space on the sides.

**Comment by isidorn** [comment]
I know get this which I think is expected, thus adding verified
![Screenshot 2021-03-23 at 15 56 35](https://user-images.githubusercontent.com/1926584/112166944-5fc3a000-8bf0-11eb-9535-2790860614d3.png)
