### ISSUE TITLE
 The result when "gtc" is expanded with emmet with the extension sass is strange.

### ISSUE THREAD

**Issue by mu60** [microsoft/vscode#117648]
- VS Code Version: 1.53.2
- OS Version: Windows10 Home

Steps to Reproduce:

1. Open the file with the extension sass.
2. Type `gtc` and then expand with emmet.
3. The result is `grid-template-columns: repeat ( )`. There is a space between `repeat` and `( )`, so it doesn't recognize it as a normal style of css.
4. `grid-template-columns: repeat()`. It is desirable to expand in this way. I also want the cursor to be between the parentheses.

Does this issue occur when all extensions are disabled?: No

I want to use Sass, so I haven't disabled Sass.
Also, the Japanese Language Pack could not be disabled.

**Comment by AnuBhar** [comment]
I am also able to repro this in a CSS file. 'repeat' is not recognized as a css function due to the space. I am willing to look into this issue.

**Comment by joshdavenport** [comment]
It's also very odd that `repeat` is in the expanded result at all, it's not a required value.
