### ISSUE TITLE
Can't get to cell toolbar in notebook

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#117693]
![notebook](https://user-images.githubusercontent.com/641685/109199973-06da2680-776e-11eb-81fb-81f3a85c78a2.gif)

Only happens on the first cell

**Comment by misolori** [comment]
Yea, Rob filed https://github.com/microsoft/vscode/issues/117618 for this one. Will close this one in favor of that one.

**Comment by misolori** [comment]
Sorry, I think this one is about the top cell toolbar for the first cell. Re-opening.

**Comment by rebornix** [comment]
Let's use this oldest one to track https://github.com/microsoft/vscode/issues/117676
