### ISSUE TITLE
Text rendered with markup in the file rename error modal box

### ISSUE THREAD

**Issue by Cloud11665** [microsoft/vscode#117667]
- VS Code Version: Insiders February 2021 (version 1.54)
- OS Version: Arco Linux v21.01.7

Steps to Reproduce:

1. try to rename a file with an invalid name
2. it renders markup in the modal box
![image](https://user-images.githubusercontent.com/59028866/109137783-e86a3000-7759-11eb-8d11-d3cac85f8fc1.png)
![image](https://user-images.githubusercontent.com/59028866/109137933-164f7480-775a-11eb-825d-19770ffc8f29.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I acknowledge this issue.
A PR that fixes this is welcome. Hopefully it should not be too hard
Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/fileActions.ts#L660

**Comment by Cloud11665** [comment]
@isidorn
https://github.com/microsoft/vscode/pull/117678, done
