### ISSUE TITLE
Problems with interface theme

### ISSUE THREAD

**Issue by shenxianyu** [microsoft/vscode#117641]
Issue Type: <b>Feature Request</b>

After upgrading this version，problems with interface theme.
Although the theme is set, the main interface is colorful, which is not conducive to coding.So I hope it can be solved as soon as possible.Thank you.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem still happen after you run the Command Palette command to Reload With All Extensions Disabled?

If it does, please paste a screenshot here.

If it doesn't, use the Extension Bisect command to investigate.
