### ISSUE TITLE
after setting git config remote.*.prune true, vscode prompts to choose remotes and includes * as a remote

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#117614]
Issue Type: <b>Bug</b>

1.  open a repo that has a remote called origin
2.  in your repo folder, run `git config remote.*.prune true`
3.  create a branch, add a commit and execute the `Git: Push` command in vscode
4.  your are prompted with an option to choose a remote which includes * and origin.

Expected:
configurations for * remotes are ignored with respect to determining remotes to which can be published.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.52GB free)|
|Process Argv|--folder-uri file:///c%3A/source/REDACTED --crash-reporter-id 38f81c6b-ee55-4a82-8c11-af11a67c55b4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.44
react-native-react-redux|EQu|2.0.6
php-debug|fel|1.14.9
auto-rename-tag|for|0.1.6
dotnet-test-explorer|for|0.7.5
vscode-mysql|for|0.4.0
gc-excelviewer|Gra|3.0.41
rest-client|hum|0.24.4
vscode-nuget-package-manager|jmr|1.1.6
vscode-mocha-sidebar|mat|0.22.2
vscode-apache|mrm|1.2.0
azure-pipelines|ms-|1.183.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
vscode-edge-devtools|ms-|1.1.3
mssql|ms-|1.10.1
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.576440691
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
azure-account|ms-|0.9.6
cpptools|ms-|1.2.1
powershell|ms-|2020.6.0
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-react-native|msj|1.4.0
vscode-sanddance|msr|3.1.1
vetur|oct|0.32.0
vscode-jest|Ort|3.2.0
vscode-nuget-gallery|pat|0.0.24
quicktype|qui|12.0.46
show-offset|ram|0.0.4
vscode-coverage-gutters|rya|2.6.0
html-preview-vscode|tht|0.2.5
vscode-icons|vsc|11.1.0
bootstrap-3-snippets|wcw|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by burtonrodman** [comment]
example of the prompt including * and origin:
![image](https://user-images.githubusercontent.com/7658657/110161487-6ada9b80-7dbb-11eb-9f81-ad0b83f95285.png)

**Comment by lszomoru** [comment]
@burtonrodman, apologies for not getting back to you on this. I went through the repro steps provided above but it's not clear to me whether `git config remote.*.prune true` is a valid command. I am running git version 2.37.0 and when I try to run that command I get an error `no matches found: remote.*.prune`. Am I missing something here? Thank you!

**Comment by burtonrodman** [comment]
i haven’t been using this config for some time so don’t even remember all the details.  i’d say we can just close it for now.

**Comment by alexr00** [comment]
Removed from milestone.
