### ISSUE TITLE
Unexpected file names in "SaveAs" dialog while saving untitled editors

### ISSUE THREAD

**Issue by dmitriklem** [microsoft/vscode#117617]
Issue Type: <b>Bug</b>

Use the following code in extension to create an editor:

```
export async function activate (context: ExtensionContext) {
const docUri = Uri.parse('untitled:myfile.json');
await commands.executeCommand('vscode.openWith', docUri, 'default');

const editor = window.activeTextEditor;
if (editor) {
    languages.setTextDocumentLanguage(editor.document, 'json');
}

```
Try to save myfile.json (Ctrl+S).  SaveAs dialog comes up suggesting file  name "composer.lock" of type lock.  Expected would be file name "myfile.json".

Stop the extension and restart it.  The problem reproduces without activating the extension.

Change file extension and languageId to jsonc and suggested file name in SaveAs dialog becomes "settings.json".  Expected - myfile.jsonc.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (13.72GB free)|
|Process Argv|--crash-reporter-id 997c6246-9091-403a-b6d1-1128094b0972|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.0.2
swagger-viewer|Arj|3.0.1
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
rest-client|hum|0.24.4
vscode-nuget-package-manager|jmr|1.1.6
import-sorter|mik|3.3.1
vscode-azurefunctions|ms-|1.2.1
csharp|ms-|1.23.9
azure-account|ms-|0.9.6
vscode-yaml|red|0.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475

```

</details>

**Comment by bpasero** [comment]
That is not how you can open untitled files with associated path, try this:

```
const document = await vscode.workspace.openTextDocument(vscode.Uri.parse('untitled:myfile.json'));
await vscode.window.showTextDocument(document);
```

//cc @jrieken wether we should document this better in API
