### ISSUE TITLE
Unclear why publishTestResults requires so much duplication

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#117616]
Testing #117307

This is probably in the same vein as https://github.com/microsoft/vscode/issues/117376, but it is unclear why an API called `publishTestResults` requires the full set of information about a test item. 

When using the API, I noticed that I could ignore the children of the test item and just publish results as a flat array. This makes me think, the nicer approach is closer to what @jrieken suggests. Since I can only update existing test items, why shouldn't I just provide an id and a result. Since other things can change by publishing results (like label and location), then the API is misleadingly named. It would be nicer to publish with and id and essentially a completely optional bag that let's me pick and choose what changes.

**Comment by connor4312** [comment]
Let's merge into #117376. I addressed Joh's query about this in https://github.com/microsoft/vscode/issues/117376#issuecomment-784353885
