### ISSUE TITLE
Revisit glob pattern usage in notebook api

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117684]
https://github.com/microsoft/vscode/blob/663159f2fa7662932e268a7e14a1854174f54dc2/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L769-L769

**Comment by jrieken** [comment]
Maybe the underlying issue is that `displayOrder` can be a glob pattern, which IMO a wrong usage of glob patterns

**Comment by rebornix** [comment]
@jrieken let's revisit the glob pattern usage in notebook, I'm sure I misuse it by a lot:

* Content provider, filenamePattern, excludeFileNamePattern
* Kernel provider, `NotebookDocumentFilter.filenamePattern`
* DisplayOrder

**Comment by jrieken** [comment]
Yeah, using a glob pattern on a filename makes sense, of a mime-type makes no sense. So, that makes display order an offender. I am wondering what you are trying to achieve why display order supports a patterns. I think I also don't understand displayOrder is being used for in the first place? Isn't this up to kernels to decide? Outputs do have an order in our world and shouldn't that order be winning?

**Comment by rebornix** [comment]
> of a mime-type makes no sense

What we need here is more or less just `RegExp` and we should move to this.

> I think I also don't understand displayOrder is being used for in the first place? Isn't this up to kernels to decide?

Now we separate kernel and content provider and it's the kernel which generates the output mime types, it makes sense to have this order from the kernel. We have order internally, which is used for builtin mime types. And lastly user configured display orders have highest priority.

**Comment by jrieken** [comment]
>  it makes sense to have this order from the kernel.

+1 on the kernel. But why spell it out when the (kernel) order can be derived from the actual output order, e.g why produce output in this order `[A, B]` and then say that the wanted order is `[B, A]`? Is this is funny duplication or invitation for confusion?

**Comment by rebornix** [comment]
> why produce output in this order [A, B] and then say that the wanted order is [B, A]?

That's simply because previously the multi-mimetype output is a dictionary, other than an array. With the new API, we can probably revamp it to

* No display order in the core
* When kernels generate `NotebookCellOutput`, make sure the preferred mimetype is the first `NotebookCellOutputItem`
* Users' display order setting has a higher priority, which is also the only customization of the display order

This way the display order info is embed into the order of `NotebookCellOutputItem`s.

**Comment by jrieken** [comment]
Ok, I added a note to remove displayOrder and will tackle that this month

**Comment by rebornix** [comment]
It seems that now `text/markdown` has higher priority than HTML when there is no user setting.

**Comment by DonJayamanne** [comment]
Unfortunately this doesn't seem to work as expected in the latest Insiders Build.

Steps to Reproduce:

1. Install Jupyter Extension from here 
2. Create a cell with latex as follows and run it against a Python kernel
```
%%latex
$e^2$
```
3. The output should display the latext output item, however it display the plain text.
4. When debugging you can see that the latex output item is first in the array.
Heres the debug view:
![Screen Shot 2021-03-05 at 13 10 22](https://user-images.githubusercontent.com/1948812/110174376-e4bb5680-7db4-11eb-8673-027c4a7ca148.png)
![Screen Shot 2021-03-05 at 13 12 30](https://user-images.githubusercontent.com/1948812/110174379-e5ec8380-7db4-11eb-9eca-5c61863b1e03.png)

**Comment by rebornix** [comment]
@jrieken FYI that when GH NB opens an existing notebook, it doesn't sort the mime types yet so markdown has higher order than the custom one.
