### ISSUE TITLE
Portable workspaces between OS's

### ISSUE THREAD

**Issue by FStefanni** [microsoft/vscode#117661]
Hi,

it would be nice to be able to use the same `*.code-workspace` files under different OS's (Windows and Linux in my case).
It is useful, since it can contain a lot of settings, root-folders, etc. that I like to have configured the same way on both OS's.
Moreover, it would came in handy to perform configuration backups, restore, and sharing (all stuff I do: so I am sure that
whatever happens, I am able to re-configure from scratch my PCs, laptops and VM's in few minutes).

For what I see right now, the first issue is the `folder` section, since the paths cannot be checked against the current OS.

For example under Linux:
```json
{
    "name": "MY PROJECT",
    "path": "/home/fstefanni/work/myproject"
}
```
But under Windows, the project is under a different path (obviously).
So a "combined" description could be useful, for example:
```json
{
    "name": "MY PROJECT",
    "linux": {
         "path": "/home/fstefanni/work/myproject"
    },
    "windows": {
         "path": "C:/Users/fstefanni/work/myproject"
    }
}
```

Or, a possible different syntax (if you prefer) could be:
```json
{
    "name": "MY PROJECT",
    "path": "/home/fstefanni/work/myproject",
    "os": "linux"
},
{
    "name": "MY PROJECT",
    "path": "C:/Users/fstefanni/work/myproject",
    "os": "windows"
}
```

Probably also other configurations could need to be "split" by OS, but I am not currently aware of
(but maybe you are aware...).

Regards

**Comment by FStefanni** [comment]
Hi,

thank you for the reply.
IMHO, this is **not** a duplicate, since environmental variables are a good help, but do not solve
the general case between different OS's since path could be unrelated/not affering to the same env vars.

Nevertheless, I am going to comment in the suggested issue.

Regards.

**Comment by dufferzafar** [comment]
I agree with @FStefanni that this won't get solved by environment variables, and is not really a duplicate.
