### ISSUE TITLE
Feature request: find a way to warn users they ran an outdated test?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117639]
Testing #115086 

I'm using the self-host extension on the vscode repo. I wasn't running yarn watch.

There are two tests in `uuid.test.ts`: `generation`, and `self-check`. I changed the self-check test, and ran it. The icons for the `generation` test and other tests became a dimmer green. I then changed the `generation` test to be invalid by changing one of the indices from 14 to 1447. I than ran that test, and it indicated that it passed, still. Also, it became a brighter green again.

Maybe there should be a way to warn the user that they just ran an outdated test.

**Comment by connor4312** [comment]
This is something the selfhost test provider could do by invaliding tests when the compiled version changes rather than when the source .ts changes

**Comment by connor4312** [comment]
Marking as out of scope since the mechanism is there for test providers now
