### ISSUE TITLE
Should run submenu icons be enforced?

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117631]
Testing #117259

https://user-images.githubusercontent.com/35271042/109078936-0b8dd480-76b3-11eb-9d22-2ef2549a3fbb.mov

I have a command that is contributed to the `editor/title/run` group that's using a `rocket` codicon:

```json
{
    "icon": "$(rocket)",
    "command": "extension.helloWorld",
    "category": "Fluent",
    "title": "Hello World 1"
},
```

but when multiple commands are added, like the when clause, it gets transformed into the run icon (as the title tells). Should this icon name be enforced when used in the `editor/title/run`?

**Comment by jrieken** [comment]
> Should this icon name be enforced when used in the editor/title/run?

I don't really understand what that means? Do you always want the rocket?

**Comment by misolori** [comment]
What I mean is should we throw an editor error/warning when a command that’s using a non-run icon is placed in the run group? In my video you can see how odd this looks.

**Comment by jrieken** [comment]
I see... I tend to agree but that's really hard to enforce. I could go after the codicon names (run, debug prefix) but extensions are free to use image icons and I can't know what they mean. My hope is that extension authors use this as we indented it to be used (that's maybe naive)

**Comment by jrieken** [comment]
Closing as we have no way to determine what an icon actually shows... Tho, there is a related issue to make submenu button more different from ordinary buttons
