### ISSUE TITLE
Don't remove extra spaces at the end of a line for Markdown

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#11769]
- VSCode Version: 1.5.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Create a markdown file with spaces at the end of a line
2. Save the file with "files.trimTrailingWhitespace" enabled

The spaces will be removed, but for Markdown documents that shouldn't happen.

From the [official documentation](https://daringfireball.net/projects/markdown/syntax#p):

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by mjbvz** [comment]
Configuring this should now be supported using language specific settings. Try adding:

```json
    "[markdown]": {
        "files.trimTrailingWhitespace": false
    }
```

to disable `"files.trimTrailingWhitespace"` just in markdown files
