### ISSUE TITLE
VS Code Terminal :: Crashes (Bug)

### ISSUE THREAD

**Issue by pu-coder** [microsoft/vscode#117660]
- VS Code Version:
- OS Version:

### Issues in VS Code Terminal
**1. Killing the terminal process crashes the whole IDE and slows down the OS. Please fix it.
2. When using the VS Code Terminal, the system gets unresponsive.
3. When using the terminal, it feels very bulky. Please fix it as well.
_Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042_
![Crash](https://user-images.githubusercontent.com/70443244/109118286-2458c180-7769-11eb-9661-10fd4304147b.PNG)
**

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
