### ISSUE TITLE
I can always tell when vscode is ready to restart for an update because weird things happen

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#117624]
Issue Type: <b>Bug</b>

Recently the most common symptom is that the toolbar continues to show the stop button even though I closed down my extension host instance (I'm developing an extension):
![image](https://user-images.githubusercontent.com/6913354/109070957-04ad9480-76a8-11eb-934b-7a1f51a06e91.png)

When when I see the debugger not shut down after closing the debugged vscode instance, I know to check the menu to see if it's wanting to restart to update.  Sure enough, that's exactly what's happened just about every single time.

![image](https://user-images.githubusercontent.com/6913354/109071129-2f97e880-76a8-11eb-9475-937d7ddf27b0.png)

Obviously downloading the installation is affecting something in the running instance.  Maybe an electron update?  No idea.  And no idea on what priority you want to give this.  It's obviously not blocking me.

VS Code version: Code - Insiders 1.54.0-insider (11cd76005bc7516dcc726d7389d0bce1744e5c85, 2021-02-22T06:44:36.656Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.99GB free)|
|Process Argv|-psn_0_7440152 --crash-reporter-id 28a909e2-0b30-47b4-bfa3-dcb1734aca95|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
todo-tree|Gru|0.0.197
vscode-azurefunctions|ms-|1.2.1
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.11.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.10.0
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.593162453
vscode-ai|ms-|0.6.20
vscode-ai-remote|ms-|0.1.0
azure-account|ms-|0.9.6
vscode-typescript-tslint-plugin|ms-|1.3.3
azurerm-vscode-tools|msa|0.15.0-alpha1
vscode-todo-highlight|way|1.0.4

(8 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
@isidorn @connor4312 Thoughts?

**Comment by isidorn** [comment]
@StephenWeatherford thanks for filling.
This sounds like debugging the EH somehow causes this
@StephenWeatherford since you use Insiders did you see this recently or it is happening for quite some time? Asking to see if maybe our Electron 11 update caused this. But if you use Insiders and you only see this now then it is something else

@connor4312 might have more ideas

**Comment by connor4312** [comment]
This is odd. I suspect it's more related to having a long session, and on Insiders there'll be an update available every 24h. I'm not sure what the deal could be. Please try running with trace logs and sharing the log with us when you eventually hit it again

/jsDebugLogs
