### ISSUE TITLE
Cell toolbar hides because of inter-cell toolbar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117676]
see attached recording

* have narrow notebooks editor
* try to move into the cell toolbar
* it hides and shows the inter-cell toolbar

https://user-images.githubusercontent.com/1794099/109152161-66830280-776b-11eb-835e-4393ba6df885.mov

**Comment by roblourens** [comment]
Yeah this is broken for the special top cell toolbar. I think that moving the cell toolbar up might have made it slightly worse, but basically the same issue exists in 1.53 fwiw. z-index hell

**Comment by roblourens** [comment]
Actually this really comes from changing the toolbar visibility to be based on hover rather than focus, when the special top insertion toolbar is also based on hover. I think the only way out is to change the implementation of that top insertion toolbar to be based on hovering the top cell instead of hovering the toolbar.

**Comment by misolori** [comment]
I adjusted the top cell toolbar height (the height wasn't properly set). This also was overlapping into the first cell which made the cell toolbar really hard to get to

|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/35271042/109229054-a3ed8d00-7777-11eb-9096-f14e63e86f72.png)|![image](https://user-images.githubusercontent.com/35271042/109229222-d7301c00-7777-11eb-8499-d01902a86501.png)|

**Comment by roblourens** [comment]
Is it supposed to be hovering above the cell instead of lined up with it though? Also we won't be able to get the top half of the toolbar. Probably an improvement though, thanks.
