### ISSUE TITLE
Content obstructed when in cells without status bar

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#117626]
The below is what I see when I use the markdown notebook. Since we show the toolbar no matter where the cursor is within the cell, the content is permanently obstructed.

![image](https://user-images.githubusercontent.com/4674940/109073981-f6fa0e00-76ab-11eb-97a5-022617cd0d89.png)

**Comment by misolori** [comment]
Moved the markdown bottom cell toolbar a bit:

![image](https://user-images.githubusercontent.com/35271042/109104700-532b5500-76e1-11eb-917f-a3755f88e9da.png)
