### ISSUE TITLE
VS Code ignores *.d directories in explorer and search

### ISSUE THREAD

**Issue by bryceschober** [microsoft/vscode#117619]
Issue Type: <b>Bug</b>

I have a unix file-system tree in a project, which has sources (bash scripts) under an */init.d/ sub-directory. VS Code refuses to show the init.d sub-directory or find-in-files text search or Ctrl-P file-find for any files in that sub-directory.

I've disabled all extensions.
I've noticed and checked the `files.exclude` and `search.exclude` settings, and they're all default.

If I only rename the `init.d` sub-directory to `init_d`, all explorer, text, and file search functions work exactly as expected.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-43-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 2|
|Memory (System)|15.56GB (1.51GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id d14eeb49-bbf6-4c96-8c77-d759ae075e8e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by gjsjohnmurray** [comment]
Have you followed all the advice at https://github.com/microsoft/vscode/wiki/Search-Issues yet?

**Comment by bryceschober** [comment]
This is a subversion project.  Does the subversion plugin contribute exclusion rules also? On the other hand, I've disabled all extensions with no change in behavior.

I have set `"search.useIgnoreFiles": false` with no change in behavior.

I turned off the "Use Exclude Settings and Ignore Files" button in the search viewlet, and now find-in-files will return results from files under `init.d`, but still no `Ctrl+P` completion.

\[Later...\] Oh crap, I guess I was overlooking a workspace settings with an ignore glob of `**/*.d`. I see from following the rabbit hole that you're using ripgrep, which supposedly uses [github glob patterns](https://git-scm.com/docs/gitignore#_pattern_format). Its docs say:

> A slash followed by two consecutive asterisks then a slash matches zero or more directories.

Which leads me to believe that maybe my pattern needs to be rooted by a `/` so that the `*.d` part doesn't match directories, only files, but no such luck. So here's a minimal experiment that I've done to reproduce my situation. I can't find a pattern that will exclude only `*.d` files as opposed to also including `*.d` directories. What am I missing?

```shell
$ rg --version
ripgrep 12.1.0 (rev 1980630f17)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
$ mkdir -p /tmp/example/foo/bar.d
$ echo "hello, cruel world" > /tmp/example/foo/bar.d/baz
$ cd /tmp/example
$ rg 'cruel'
foo/bar.d/baz
1:hello, cruel world
$ rg 'cruel' -g '**/*.d'
$ rg 'cruel' -g '!**/*.d'
$ rg 'cruel' -g '/**/*.d'
$ rg 'cruel' -g '!/**/*.d'
$
```

In fact, while the glob will happily `exclude` the file with a negated pattern, it won't *include* the file with a positive pattern. Wat?

I've submitted <https://github.com/BurntSushi/ripgrep/issues/1806>, but any pointers would be appreciated.

**Comment by roblourens** [comment]
You could do the opposite, exclude directories without excluding files, by excluding `**/*.d/**`. But `**/*.d` will match the file and the directory, so I don't know that there is a way to do what you want.

**Comment by roblourens** [comment]
Actually it looks like rg considers a trailing slash to be meaningful, and I can do this on the command line:

```
roblou@robfast:/tmp/example$ rg cruel
text.d
1:cruel

foo/bar.d/baz
1:hello, cruel world
roblou@robfast:/tmp/example$ rg cruel -g '**/*.d/' -g '**/*.d/**'
foo/bar.d/baz
1:hello, cruel world
```

So for text search, you could probably set those includes in "files to include" to get the result you want.  But this isn't exactly what you want. I don't know how to how to get the same result with only an exclude pattern in settings. We don't support negative globs but that's basically what you want.
