### ISSUE TITLE
Prevent env var relaunch from extension owned terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117649]
We don't want to relaunch these because then I believe the replacement terminal would no longer be owned by the extension.

**Comment by Tyriar** [comment]
To clarify this issue, this is specifically what we're trying to help: The SSH extension was having its terminal relaunched which killed the connection, at which point it needed to relaunch the terminal itself, slowing the initial connection time.

As for _reconnection_, I think we want to keep that for extension owned terminals as that would be beneficial to extensions like:

- https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher
- https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

I'm sure there are cases where we may not want to reconnect to some `createTerminal` terminals, but it's probably in the minority and extensions can always query the `terminals` object to see if it owned terminals in the previous session. If this does end up being a problem for several extensions we could look into adding a new `TerminalOptions` API that opts out of reconnection.

**Comment by Tyriar** [comment]
It looks like PowerShell is failing hard from this because they launch a terminal on startup by default, and when it gets relaunched it never attempts to restart it https://github.com/PowerShell/vscode-powershell/issues/3227. We should bring this into the recovery build

**Comment by andschwa** [comment]
Ah, I wondered what was going on. I'm still getting my feet wet with all this, thanks for tracking this down @Tyriar.

**Comment by Tyriar** [comment]
Verified by installing the PowerShell extension, and the terminal sample extension. Opening a PS file to launch the PS integrated console, and then triggering update environment to ensure thee warning shows up and not an automatic relaunch.
