### ISSUE TITLE
"Find all references" shows no results, but when repeated later, there are results

### ISSUE THREAD

**Issue by nik-gloy** [microsoft/vscode#117642]
Issue Type: <b>Bug</b>

Open a folder
Navigate to a .tsx file that has a Typescript enum
Right-click on one of the values in the enum and select "Find all references"
Actual result: Search results show a single reference, the one I just clicked on.
Expected result: It should also show 2 other references in other files

Later on, if I repeat this action, it does find all 3 references. Maybe it's because not all file in the folder are available to be searched? It's a problem because it wrongly claims that there are no references. Later it changes its mind. If it can't do a search immediately after opening a folder, then it should say so, not just silently fail.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.98GB free)|
|Process Argv|--crash-reporter-id 371107d5-ae9e-4da6-a9d6-2f2b690e40df|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2
beautify|Hoo|1.5.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475

```

</details>

ause it was too large to send. Please paste.

**Comment by mjbvz** [comment]
Please share code the demonstrates the issue 

Also, do you have a tsconfig defining a project?

**Comment by nik-gloy** [comment]
I'm not allowed to share the code because it's a work project.

Yes, there is a tsconfig I don't think that contains anything proprietary so here it is:

{
    "extends": "./node_modules/pcf-scripts/tsconfig_base.json",
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "CommonComponents/*": ["../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/CommonComponents/*"],
            "CustomControls/*": ["../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/CustomControls/*"],
            "PerformanceAutomation/*": ["../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/PerformanceAutomation/*"],
            "PerformanceEvents/*": ["../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/PerformanceEvents/*"],
            "PerformanceInterface/*": ["../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/PerformanceInterface/*"],
            "modern-admin-common/*": ["../../../../Shared/ModernAdminCommon/lib/*"]
        },
        "typeRoots": [
            "node_modules/@types",
            "../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/ts/es6/**/*.d.ts",
            "../../../../../packages/CRM.CustomControlsFramework.1.6.238-master/content/*.d.ts",
            "../../../../Shared/ModernAdminCommon/lib/*.d.ts"
        ]
    },
    "references": [
        { "path": "../../../../Shared/ModernAdminCommon/" }
    ]
}

**Comment by mgoldshteyn** [comment]
This happens constantly: Find all references is missing references. Then:

1. You open the source file where you know references exist, it gets processed by by Intellisense
2. You go back to the original source files and repeat _Find All References_ and now the reference in the previous source file you opened, containing the references, shows up with its references.

**Comment by mjbvz** [comment]
@nik-gloy  Please share a minimal project that demonstrates the issue. The project you shared is still quite complex and seems to reference files that don't exist (but it also seems to work fine for me after ):

<img width="1182" alt="Screen Shot 2021-02-25 at 4 50 58 PM" src="https://user-images.githubusercontent.com/12821956/109239162-b375d180-7789-11eb-990b-41fc07f10073.png">


@mgoldshteyn Please file your issue against the c++ extension
