### ISSUE TITLE
"View: Maximize editor group" doesnt work with dragged file between editors

### ISSUE THREAD

**Issue by tonoslav** [microsoft/vscode#117686]
Issue Type: <b>Bug</b>

Steps:
0. Open empty editor
1. Split editor right (icon right top)
2. 2x CTRL + n (new file/tab)
3. Middle click "Untitled-1" in right part (to close it)
4. Now you have 1 file (Untitled-1) on left, 2 (Untitled-2, Untitled-3) or right 
5. Click "Untitled-2"
6. Enable ">View: Maximize editor group" 
7. Drag and drop "Untitled-2" from right editor to left
PROBLEM:  "Untitled-2" is moved to left, and active there (lighter color in text) but left part of editor is minimized and right is maxed even it should be 

![max-error](https://user-images.githubusercontent.com/3399021/109174548-3a747b00-7785-11eb-9fc7-ddb53b801ecc.gif)

VS Code version: Code - Insiders 1.54.0-insider (c47da720f351455681978a48edc4d9a0d095ea0e, 2021-02-24T11:34:41.307Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (1.65GB free)|
|Process Argv|--crash-reporter-id d73c12a2-5f90-4f01-9db0-68daab1cae8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-phpunit|cal|1.5.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-css-modules|cli|0.2.3
vscode-eslint|dba|2.1.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
vscode-test-explorer|hbe|2.19.5
phpcs|ika|1.0.5
sftp|lix|1.12.9
change-string-case|max|1.1.2
php-namespace-resolver|Meh|1.1.8
ecdc|mit|1.4.0
quicksnippet|mou|0.0.1
easy-less|mrc|1.7.2
vscode-less|mrm|0.6.3
php-docblocker|nei|2.1.0
gulptasks|nic|1.3.1
vetur|oct|0.32.0
laravel-blade|one|1.25.0
vscode-jest|Ort|3.2.0
laravel-helpers|raf|0.2.2
vscode-yaml|red|0.15.0
code-settings-sync|Sha|3.4.3
stylelint|shi|0.51.0
vscode-blade-formatter|shu|0.7.1
php-phan|Tys|3.0.0

</details>

**Comment by bpasero** [comment]
Good catch, the issue is this:
* the dragged editor opens in the first group and will actually cause to maximize it
* however we then close the dragged editor in the right hand group which will active the first editor of that group
* we then proceed making the right group maximize because we typically do that when an editor gets opened

Should revisit this, by either:
* use the `EditorActivation` option
* should never change group sizes if `preserveFocus` is set?

**Comment by bpasero** [comment]
Similar issue:
* have 2 editors in the left group and 1 in the right
* have the right group active
* have the right group maximized
* middle-mouse-click into the active editor of the left inactive group
* => 🐛 the inactive group maximizes
