### ISSUE TITLE
Remote Extensions to use Remote-ssh and remote-container at the same time

### ISSUE THREAD

**Issue by xendren** [microsoft/vscode#117610]
First of all, the remote-ssh extension is a fantastic feature that allows our developers to seamlessly remote into our Linux development servers and develop in house applications.  
The only issue we have is that the remote Linux server still needs administrators to manage the needed software to support development on those dev servers.  This is one of the big problems that Docker solves.  We can build images that have standardized toolsets needed by the developers.  Unfortunately, if we have the developers log into the dev server and start up the container, they no longer have an awesome IDE to develop with.  

Currently, it appears that the VSCode remote extensions will only allow us to either remote-ssh into the remote linux server or remote-container into a docker container (requires Docker desktop).

What we really need is to be able to remote-ssh to the linux server, start up a container there, and remote-container into it.  This seems to be similar to how the new GitHub Codespaces work from my understanding.  

Maybe this is already possible, and I am not configuring it correctly.

**Comment by yume-chan** [comment]
I think it's possible to setup sshd IN the container and use remote-ssh extension to connect the container directly?

**Comment by xendren** [comment]
Thank you for the response.  Do you mean setup ssh inside the container on a non 22 port and adjust my ssh config to include the port for the container?  Would need to have the container running before remoting.  Would the vscode extensions (remote, language servers, etc) configure properly inside the container or would I need to make sure my user exists inside the container?

**Comment by chrmarti** [comment]
You can attach to an existing container while connected with Remote-SSH. (`F1` > `Remote-Containers: Attach to Running Container...`)

More general support is tracked as https://github.com/microsoft/vscode-remote-release/issues/2994.
