### ISSUE TITLE
Notebook reopens as text, not as notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117668]
* see attached recoding
* opened `endgame.github-issues` (for which I needed to run the Reopen with command)
* from breadcrumbs open another notebook
* from breadcrumbs open `endgame.github-issues` again
* :bug: the notebook opens as text file

https://user-images.githubusercontent.com/1794099/109138583-d1780d80-775a-11eb-921b-479081c65857.mov

**Comment by bpasero** [comment]
@jrieken possibly you have the notebook open as both text and notebook and when clicking on the breadcrumb it would pick the first one (text) and bring that to front?

**Comment by jrieken** [comment]
Yeah, that might be it. I don't see this anymore after closing all editors. Leaves the question why I had it open as text file in the first place and why my notebook editor isn't winning

**Comment by bpasero** [comment]
I defer to custom editor owners how this logic works.

**Comment by lramos15** [comment]
I don't see this @jrieken. My guess is it has to do with what @rebornix and I have been discussing about reopen with regarding notebooks. Currently reopen with in notebooks doesn't replace the active tab where with custom editors it does.

**Comment by lramos15** [comment]
Like many great things, I believe this has been fixed by the new `editorOverrideService` 🙂
