### ISSUE TITLE
Output rendering size changes aren't smooth

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#117670]
follow up from https://github.com/microsoft/vscode/issues/116786

* open GH issue notebook, run a query
* open an item from the query and modify it so that it doesn't match the query anymore (like verify a bug)
* re-run the query
* 🧀 there is a moment at which the new, shorter output is rendered but list isn't relayouted, leaving an awkward bottom padding

https://user-images.githubusercontent.com/1794099/109145528-e0fb5480-7762-11eb-9645-15548b3ce72f.mov

**Comment by rebornix** [comment]
We have a `min-height` protection for a second to avoid the height goes to 0 pixel (or maybe a couple of pixels) and jump back to the real height of the new output. For this particular case, the new output finishes rendering, its height is hundreds of pixels but shorter than the previous one and it finishes with one second, so visually there is whitespace at the bottom of the cell.

We should see if we can differentiate the height of output removal/init-layout, or the layout after rendering, and decide if the timer should be cancelled.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/f908389c0b15066caccc1572c041e9dbcb37fd7f
