### ISSUE TITLE
Git extension "File History" section does not show up

### ISSUE THREAD

**Issue by khan990** [microsoft/vscode#117680]
- VS Code Version: 1.53.2
- OS Version: Mac OS 11.2.1

Steps to Reproduce:
![2021-02-25 14-23-41 2021-02-25 14_27_11](https://user-images.githubusercontent.com/2551269/109160290-e3b37500-7775-11eb-9696-f31843c10005.gif)

> **Notice** that selection of **Line History** as well as **File History** creates **Line History** section. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
//causedByExtension those parts come from the GitLens extension
