### ISSUE TITLE
Seeing "editor/title/run" menu without adding to package.JSON

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#117640]
Testing #117259

I added the following to the package.json of a fresh typescript extension:

```
"commands": [
			{
				"icon": "$(rocket)",
				"command": "extension.helloWorld",
				"category": "Fluent",
				"title": "Hello World"
			},
			{
				"icon": "$(search)",
				"command": "extension.quickInput",
				"category": "Fluent",
				"title": "Quick Input Samples"
			}
		],
		"menus": {
			"editor/title": [
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				},
				{
					"command": "extension.helloWorld",
					"group": "navigation"
				},
				{
					"command": "extension.quickInput",
					"group": "navigation"
				}
			]
```

I run the extension, and see the following:
![image](https://user-images.githubusercontent.com/1389808/109086318-36caf080-76c0-11eb-89eb-0201a6876ad7.png)

The new run submenu is present, clicking on it does nothing, hovering shows the "Run" text.  **Having 9 or fewer items in the subbar will make the run submenu disappear, as desired.**

**Comment by jrieken** [comment]
I can reproduce. Thanks @devinvalenciano

**Comment by rzhao271** [comment]
A new button shows up now. It works when one clicks on it, but I'm not sure if it's supposed to be there.

![prmod](https://user-images.githubusercontent.com/7199958/109354727-1c655400-7833-11eb-9920-09d3677c1481.PNG)

**Comment by jrieken** [comment]
> A new button shows up now. It works when one clicks on it, but I'm not sure if it's supposed to be there.

 Your screen-shot doesn't show the Run icon? What's the issue that made you reopen this?

**Comment by rzhao271** [comment]
@jrieken I added in 5 rocket and 5 search icons to the package.json but the icon in the middle showed up. Wondering if that's expected?
