### ISSUE TITLE
Document tree and breadcrumbs no longer jump between matching files

### ISSUE THREAD

**Issue by rosenrodt** [microsoft/vscode#117651]
- VS Code Version: 1.53.2
- OS Version: Windows NT x64 10.0.18363

To quote from official [guide](https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree):
>You can type to filter the currently visible files in the File Explorer. With the focus on the File Explorer start to type part of the file name you want to match. You will see a filter box in the top-right of the File Explorer showing what you have typed so far and matching file names will be highlighted. **When you press the cursor keys to move up and down the file list, it will jump between matching files or folders.**

Steps to Reproduce:

1. Open a folder with VSCode
2. Go to "Explorer" and type a search pattern
3. Use arrow keys to navigate. It *should* jump between matching files but not it's not. 
4. This same wrong behavior is also on the breadcrumbs view.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in 1.54 which is due out next week.
