### ISSUE TITLE
Crash soon after launching vs code

### ISSUE THREAD

**Issue by tehloo** [microsoft/vscode#117652]
- VS Code Version:1.53.2 - 622cb03f7e070a9670c94bae1a45d78d7181fbd4 - x64
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. launch vs code with shortcut or on terminal with 'code' command
2. crash just after windows shown.

It left logs as below when it starts with 'code --verbose'

```
/dev/fd/3: No such file or directory
Server response:

```
[crash-reporter-vscode.tar.gz](https://github.com/microsoft/vscode/files/6040322/crash-reporter-vscode.tar.gz)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@deepak1556 there is a crash dmp file in the archive.

**Comment by deepak1556** [comment]
Same as https://github.com/microsoft/vscode/issues/116690, merging to it.

@tehloo do you have settings sync enabled or did you perform authentication with any extension ?
