### ISSUE TITLE
circular symlink breaks typescript intellisense

### ISSUE THREAD

**Issue by bedorlan** [Microsoft/vscode#11773]
Steps to Reproduce:

0. Before creating symlink, intellisense works:
![good](https://cloud.githubusercontent.com/assets/4246233/18388711/5364d6b4-7668-11e6-9b13-abc82cbc1849.png)

1. Inside some project folder, create symbolic link to parent folder
`$ ln -s ../../ baselibs`

2. Restart vscode
3. Now intellisense fails:
![bad](https://cloud.githubusercontent.com/assets/4246233/18388847/d33a7542-7668-11e6-8a36-9efda1d7d19f.png)

My project folder has 16942 files and 2944 folders. I try to reproduce the issue in a simpler folder structure, but i couldn't. 

I also tried to ignore the symlink in the settings.json, but this doesn't fix the issue.

Gladly i'll provide more info.

- VSCode Version:
Versión 1.5.1
Confirmación 07d663dc1bd848161edf4cd4ce30cce410d3d877
Fecha 2016-09-08T21:34:58.760Z
Shell 0.37.6
Representador 49.0.2623.75
Node 5.10.0
- OS Version:
Linux os006724 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux

**Comment by waderyan** [comment]
@bedorlan thank you for reporting this issue. Is it possible for you to share your project so we can try and reproduce on our end? 

@dbaeumer this is a tough one. He wasn't able to reproduce with a simpler structure. Any thoughts?

**Comment by bedorlan** [comment]
Finally, i was able to reproduce the issue. project attached.

[project.zip](https://github.com/Microsoft/vscode/files/464874/project.zip)

Steps to Reproduce:
1. uncompress project.zip & project.tgz (automatic symlinks)
2. open the folder `project`
3. open the file `0/1/2/test.ts`
4. try intellisense

tip: i'm using a custom typescript sdk:
```
{
    "typescript.tsdk": "./node_modules/typescript/lib"
}
```

**Comment by dbaeumer** [comment]
@waderyan pretty sure this is a tsserver issue. Since they load the whole project I don't know whether they 'normalize' links to avoid traversing the cycle endlessly.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10873
