### ISSUE TITLE
Access the fetch object in a vscode extension

### ISSUE THREAD

**Issue by dragonDScript** [microsoft/vscode#117763]
My extension needs to access window.fetch. Would this be possible?

**Comment by yume-chan** [comment]
No.

Your extension runs in Node.js context where there is no `fetch`.

**Comment by dragonDScript** [comment]
> No.
> 
> Your extension runs in Node.js context where there is no `fetch`.
> 
> EDIT: neither `window`

Alright. I managed to get a solution with node fetch. Thanks
