### ISSUE TITLE
终端无法打开

### ISSUE THREAD

**Issue by bigfatDone** [microsoft/vscode#117726]
Issue Type: <b>Bug</b>

终端无法打开

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.53GB free)|
|Process Argv|--crash-reporter-id c97ddc3f-47e9-433e-b63d-f2a471cfac6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
leek-fund|gis|1.9.5
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-colorize|kam|0.10.0
juejin|luz|0.2.24
vscode-language-pack-zh-hans|MS-|1.53.2
vetur|oct|0.32.0
vscode-css-peek|pra|4.1.0
minapp-vscode|qiu|2.2.2
postcss|ric|2.0.0
background|sha|1.1.26
element-ui-snippets|SS|0.7.2
open-in-browser|tec|2.0.0
highlight-matching-tag|vin|0.10.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by rzhao271** [comment]
My attempt at a translation: "Cannot open the terminal"
Can you add a screencap of the problem, for example using https://gifcap.dev/?
