### ISSUE TITLE
Task cwd not correct in multi-root workspace

### ISSUE THREAD

**Issue by hhanesand** [microsoft/vscode#117700]
Issue Type: <b>Bug</b>

Hello,

I've set up a task that builds the current pacakge the user has open in a multi-root workspace. I'm trying to set the task cwd, but it doesn't get the correct value.

task definition, inside `.code-workspace`:
```
{
    "label": "build active package",
    "type": "shell",
    "command": "${fileWorkspaceFolder}${pathSeparator}..${pathSeparator}..${pathSeparator}scripts${pathSeparator}run-rush-command.sh -c build",
    "options": {
        "cwd": "${fileWorkspaceFolder}"
    },
    "problemMatcher": [
        "$tsc"
    ],
    "dependsOn": [
        "setup"
    ],
    "presentation": {
        "reveal": "always",
        "focus": true,
        "panel": "shared",
        "showReuseMessage": true,
        "clear": false
    }
},
```

When I run the command, I get the following:
```
> Executing task in folder different-pacakge-name: ~/Developer/repo-name/packages/correct-package-name/../../scripts/run-rush-command.sh -c build <
```

As we can see in the `command` definition, I'm specifying `${fileWorkspaceFolder}`, which is correctly aliased to ` ~/Developer/repo-name/packages/correct-package-name`, but the task is run in an incorrect folder `different-pacakge-name`.

This causes the $tsc matcher to generate the wrong path, which mean's we're unable to click on the issue to open the file with the issue. `$tsc` thinks the file path is `~/Developer/repo-name/packages/different-pacakge-name/file-path.ts`. 

`different-pacakge-name` is coincidentally the alphabetically first root in the multi-root workspace. The same `different-pacakge-name` is used no matter what file I run the task from.

Have I messed something up here?

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id d24d936a-f597-42fd-9162-bf416dad3f45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
inline-parameters|lia|0.2.1
shellcheck|tim|0.13.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30260844

```

</details>

**Comment by alexr00** [comment]
@hhanesand I tried out your scenario with a multiroot workspaces and these tasks:
```json
			{
				"label": "echo fileWorkspaceFolder",
				"type": "shell",
				"command": "echo ${fileWorkspaceFolder}",
				"problemMatcher": []
			},
			{
				"label": "ls fileWorkspaceFolder",
				"type": "shell",
				"command": "ls",
				"options": {
					"cwd": "${fileWorkspaceFolder}"
				},
				"problemMatcher": []
			}
```

The text printed to the terminal when the tasks start is always:
```
> Executing task in folder different-pacakge-name
```

However, the based on the output from task `ls fileWorkspaceFolder` the task is actually executing in the correct directory. 

I think the problem matcher would still use the wrong path though. You might be able to work around this issue by doing something like the following for your problem matcher:
```json
				"problemMatcher": {
					"base": "$tsc",
					"fileLocation": [
						"relative",
						"${fileWorkspaceFolder}"
					]
				}
```

Please let me know if that works.

**Comment by hhanesand** [comment]
That workaround fixed the issue. Thanks!

**Comment by alexr00** [comment]
Fixed by using a multiroot workspace, so closing.
