### ISSUE TITLE
The readonly attribute of TextArea break `vscode.workspace.onDidChangeTextDocument` API on browser version vscode

### ISSUE THREAD

**Issue by conwnet** [microsoft/vscode#117755]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. open a browser version vscode
2. open a editor with readonly mode
3. any extension who use the `vscode.workspace.onDidChangeTextDocument` API would be invalid

This issue won't be occured on desktop version. Follow code show more details:
https://github.com/microsoft/vscode/blob/c57c05ea36/src/vs/editor/browser/controller/textAreaHandler.ts#L135-L137

the `readonly` attribute is used to disable keyboard popping in mobile devices, but it break the `vscode.workspace.onDidChangeTextDocument` event too.
 
Change the `platform.isWeb` to `platform.isIOS` may be better

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@conwnet Can you please give an example of how `vscode.workspace.onDidChangeTextDocument` behaves differently?  I am not 100% convinced that there is a bug here. I would expect that `vscode.workspace.onDidChangeTextDocument` is never called, not in desktop and also not in web.

**Comment by conwnet** [comment]
> @conwnet Can you please give an example of how `vscode.workspace.onDidChangeTextDocument` behaves differently? I am not 100% convinced that there is a bug here. I would expect that `vscode.workspace.onDidChangeTextDocument` is never called, not in desktop and also not in web.

There is a bug that are relatively easy to reproduce, when someone use **GitHub CodeSpaces** (because the bug only occured in browser version):

1. Install the `Vim` extension and the `GitLens` Extension. (the `VIM` extension require the `vscode.workspace.onDidChangeTextDocument` API for basic `hjkl` cursor motion, and the GitLens extension will provide can readonly mode editor)
2. Open any file which has at least two commit, click `Open Change with Previous Revision` in the editor menu title.

![image](https://user-images.githubusercontent.com/17734694/109374516-cc4cc700-78f0-11eb-8a25-434053561c0a.png)

3. then we will get a readonly editor, but `VIM` extension can not move cursor by pressing `hjkl` key here.

The readonly attribute was added in this commit: https://github.com/microsoft/vscode/commit/0040158a0d438bf9c1584edc9733bf8708e1360c As the message describe, it used to disable keyboard popping up on mobile devices, and there is no `isWeb` condition at the earliest time.

and then add the `isWeb` condition at this commit https://github.com/microsoft/vscode/commit/69ae6cdf2183dd8c7a7e845dec7f032ce9ff2af9 by you @alexdima 😂, I guess that's the readonly attribute cause some bug at desktop version?

Another thing, I think when we need consider the mobile devices, I think change the `platform.isWeb` to `platform.isMobile` may be better, but there is not a option named `isMobile` in `platform.ts`, so I just change it to `platform.isIOS` at #117758.

**Comment by alexdima** [comment]
To verify, use vim in the browser in a readonly editor.
