### ISSUE TITLE
presentation reveal never tasks don't reuse terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117794]
Not sure if this was by design in task land or whether it's a regression in tasks or terminal.

**Comment by Tyriar** [comment]
Looks like it's by design @eamodio, no recent changes.

https://github.com/microsoft/vscode/blob/d596c56845130cc76a791b332ef6c490f6b7d44c/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1135-L1149

**Comment by eamodio** [comment]
Hrm, the error notification seems undesirable to say the least tho

**Comment by Tyriar** [comment]
@eamodio oh I wasn't seeing the error notification 🤔
