### ISSUE TITLE
Can we have a unified command id to open a folder

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#117748]
As an extension author, many features require you to first open a folder. VS Code itself provide shortcuts to open a folder in file explorer's welcome view. So in welcome view contributed by extensions, it's also fair to provide a shortcut link to open a folder. 

For Mac and other platforms, the command IDs to open a folder are different. It seems that VS Code doesn't have a unified command id for that, but to pick the right one for different platform.
https://github.com/microsoft/vscode/blob/413963c489fafa5163b5d6513731c7953de07fb3/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L297

The problem is, in content of welcome view is statically written in package.json of the extension. I don't find a way to provide platform-specific markdown content there. It would be much helpful if you provide a unified command for that.

**Comment by bpasero** [comment]
You can just register your own command and call `commands.executeCommand` depending on the platform, no?

**Comment by Eskibear** [comment]
Yes, I can. Thank you for pointing out. I was just thinking VS Code might already have a unified command to do that because it's a widely used operation. 
So feel free to close it if you don't plan to provide such an alias command. 😄
