### ISSUE TITLE
Ports: Escaping from port rename should focus row

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117771]
1. Focus a port row
2. <kbd>F2</kbd> to rename
3. <kbd>Escape</kbd> to cancel the rename

🐛 Port row isn't focused

**Comment by alexr00** [comment]
@joaomoreno I'm trying to set the focus immediately after a splice, but I don't see it working. Should something like this work in the new table?

```typescript
			this.table.splice(0, Number.POSITIVE_INFINITY, this.viewModel.all);
			this.table.setFocus(this.lastFocus);
```

**Comment by joaomoreno** [comment]
It should. Does the DOM show the row has focus?

**Comment by alexr00** [comment]
No, even if I do 
```
			this.table.splice(0, Number.POSITIVE_INFINITY, this.viewModel.all);
			this.table.setFocus([0]);
```
it only works on the first render.

**Comment by joaomoreno** [comment]
You sure nothing else is clearing the focus right after?

**Comment by alexr00** [comment]
Figured it out. I needed to call `domFocus` on the table.
