### ISSUE TITLE
Automatic duplication of random file

### ISSUE THREAD

**Issue by UlyanaHashchuk** [microsoft/vscode#117754]
Issue Type: <b>Bug</b>

Hello,
This week after new update of VS Code this bug started. Sometimes VS Code randomly dublicating some files and adding number 2 in the end, e.g: I have file "sw.js" and it automaticaly creating copy "sw 2.js" or even "sw 3.js".  Never happen before. I am tired of deleting around 14 newly created dublicates every day(sometimes 2 times per day). As project is growing fast - amount of dublicated files also grows. 
Please fix this as soon as possible as or tell what can cause it.
Thank you.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.43GB free)|
|Process Argv|--crash-reporter-id 73982b50-f969-4b31-a1d9-3a5b88956e5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
vetur|oct|0.32.0
vscode-icons|vsc|11.1.0
quokka-vscode|Wal|1.0.343
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30260844

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

First it needs to be reproducible. When you have those I suggest you next use the command to reload with extensions disabled, to see if it still happens. If that solves the problem, enable your extensions and then use the Start Extension Bisect command to discover which one is causing it. Then report it to the extension developer.

**Comment by UlyanaHashchuk** [comment]
@gjsjohnmurray Thank you. I saw this suggestion for other users and they wrote it did not help them. Anyway, now I disabled everything, will see if it will happen again and let you know.

**Comment by UlyanaHashchuk** [comment]
Turned off all extensions except "vscode-icons" and duplication happened again. Now I am using "Start Extension Bisect command", so it turned off that icons extension and will see if issue will happen again.

**Comment by UlyanaHashchuk** [comment]
@gjsjohnmurray @isidorn Hello again. I was using Start Extension Bisect command for few hours and did not see duplications. After I pushed that everything okay(for Bisect) it gave this answer: "Extension Bisect is done and has identified vscode-icons-team.vscode-icons as the extension causing the problem." 
Maybe bug is in that extension.
What should I do now?

I will turn on all extensions I had except this one mentions above. Hope they will be working just fine.

**Comment by isidorn** [comment]
Hi, thanks for the info. However I doubt that extension is to blame.
I suggest you try to reproduce with vscode insiders and let us know if you also see it there
https://code.visualstudio.com/insiders/

**Comment by UlyanaHashchuk** [comment]
Okay, will try it

**Comment by UlyanaHashchuk** [comment]
Btw, project is working normally in WebStorm and not creating any duplicates.

**Comment by UlyanaHashchuk** [comment]
@isidorn I used VS insiders with all my previous extensions and do not see duplication bug here. 
But I would like to use VS Code as I used before, do you know why I could have bug there, but not in insiders?

**Comment by gjsjohnmurray** [comment]
@UlyanaHashchuk by the end of next week the current Insiders (1.54) will most likely have been released as Stable.

**Comment by UlyanaHashchuk** [comment]
Okay, I understand.
Will you try to fix that bug(or try to find why it is appearing) in VS Code?

**Comment by gjsjohnmurray** [comment]
First we need a repro. And if you can't repro it in Insiders then there's nothing to fix.
