### ISSUE TITLE
Promise.as/is wrongly typed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#11771]
Our type definitions for `Promise.is` and `Promise.as` are wrong because the implementation only checks for arguments being a `thenable` meaning they don't necessarily return winjs-promises. 

```
public static as<ValueType>(value:ValueType):TPromise<ValueType>;
```

should be 

```
public static as<ValueType>(value: Thenable<ValueType>): Thenable<ValueType>;
public static as<ValueType>(value: TPromise<ValueType>): TPromise<ValueType>;
public static as<ValueType>(value: ValueType): TPromise<ValueType>;
```

![screen shot 2016-09-09 at 14 29 49](https://cloud.githubusercontent.com/assets/1794099/18388027/219d3abc-76a0-11e6-9ea2-66dbd8997ba0.png)

The method that does what you would expect is `TPromise#wrap`.

**Comment by jrieken** [comment]
cause for https://github.com/Microsoft/vscode/issues/11754

**Comment by jrieken** [comment]
fyi Microsoft/vscode

**Comment by joaomoreno** [comment]
wow
