### ISSUE TITLE
Unable to Scroll on VS Code Terminal

### ISSUE THREAD

**Issue by jcitarello** [microsoft/vscode#117704]
- VS Code Version: 1.53.2
- OS Version: Windows 10 - 1909

Steps to Reproduce:

1. Open VS Code
2. Run anything in terminal window producing greater than 25 lines of output. Output appears to be restricted to 25 lines. Terminal buffer is set to 999 and I have checked all shell windows for possible restrictions.

Does this issue occur when all extensions are disabled?: Yes/No  Yes

**Comment by meganrogge** [comment]
Can you try to reproduce this in Insider's? I'm unable to

**Comment by jcitarello** [comment]
> 
> 
> Can you try to reproduce this in Insider's? I'm unable to

Hi! I am not familiar with "Insider's".  It's actually 19 or 20 lines best I can tell. 

settings.json: 
{
    "editor.suggest.maxVisibleSuggestions": 1,
    "terminal.integrated.scrollback": 999,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.automationShell.windows": "",
    "terminal.integrated.automationShell.osx": ""
}


![terminal_scroll](https://user-images.githubusercontent.com/6476294/109315593-4fe2b700-7810-11eb-9320-34c165c05738.JPG)

**Comment by jcitarello** [comment]
Some further info here. It doesn't actually seem to be limited to lines, but rather limited to the amount of window available. If I open the screen further it will capture the output to the height of the screen, but there is no scrollback buffer to speak of. 

I should also mention that I had my system re-imaged with fresh windows install and the problem still exists. I've added two more images. The first is the output before scrolling, and the second is when I pull up on the scroll bar. Note that it is empty. No buffer captured at all.

![fullscreen_1](https://user-images.githubusercontent.com/6476294/109316973-c6cc7f80-7811-11eb-891c-59b9b2413b1c.JPG)

![fullscreen_2](https://user-images.githubusercontent.com/6476294/109316983-ca600680-7811-11eb-9990-55ccf5cf5e58.JPG)

**Comment by meganrogge** [comment]
What happens if you delete this setting that you have?
"terminal.integrated.scrollback": 999,

**Comment by jcitarello** [comment]
No change. I also updated to pdk 2.0.0 and the issue is still present. Not sure if it's related to pdk or not, but other commands such as "tree" show the complete output. I have a similar case open with puppetlabs just in case.

https://github.com/puppetlabs/pdk/issues/829

![settings json](https://user-images.githubusercontent.com/6476294/109350549-49b6ff80-783d-11eb-9c03-25afe4f42c76.jpg)

**Comment by meganrogge** [comment]
what happens if you type `yes` in the teminal and then ctrl c after about 30+ lines have been printed? can you scroll then?

**Comment by jcitarello** [comment]
The behavior is just... odd. If I make the screen smaller, the output is limited to about 1 line less than is available in the window. Ie. I can scroll up, but it only shows one additional line of output...

![cntlc_small](https://user-images.githubusercontent.com/6476294/109352586-aff15180-7840-11eb-9f1a-89f5e353dca2.JPG)

If I expand the terminal window by pulling up on the upper border, I can see more lines that would normally be in the buffer. I can't see these additional lines in the smaller window, ie. I cannot scroll back through them as you normally would be able to.

![cntlc_large](https://user-images.githubusercontent.com/6476294/109352798-ff378200-7840-11eb-8ed1-4d134a4ae988.JPG)

**Comment by jcitarello** [comment]
I just discovered something else. "Clear" is only clearing the visible amount of the terminal. If I type "clear" and then scroll up, the lines that were not visible are still there. I did cntrl-c 50 times, can only scroll through about 25 lines. Typed "clear" and about 25 lines remained.

**Comment by meganrogge** [comment]
Can you try changing your renderer type?

`"terminal.integrated.rendererType"`

**Comment by jcitarello** [comment]
Tried all found of the rendering types, but there is no change. 

More oddness here. I type cntrl-c 50 times and I had all 50 lines in my buffer and could scrollback through them all the way back to the top of the screen. I ran the 'pdk validate' command after that, and what it appears to be doing is wiping out the scrollback buffer by as many lines as are being output to the screen by the pdk command.

The screenshot here shows the cntrl-c lines missing after running the command.

![pdk_capture](https://user-images.githubusercontent.com/6476294/109518518-ecef5b00-7a6f-11eb-890e-2fb3d2d37c36.JPG)

**Comment by jcitarello** [comment]
@meganrogge @Tyriar Just an update on this. Turns out is actually an issue with PDK. Please see the link below for details and thanks for looking into it!

https://urldefense.com/v3/__https://github.com/puppetlabs/pdk/issues/829*issuecomment-790983778__;Iw!!Ojd1I5wBFw!5hIV2_N9XjlBp86SgzNvRbxIdQNzEHRGf6yl66VQl_3FqibMxCVytfHAmR7p4co$

**Comment by meganrogge** [comment]
Great, thanks for letting us know!
