### ISSUE TITLE
[code improve] hard code is too small

### ISSUE THREAD

**Issue by fumingcui** [microsoft/vscode#117749]
- VS Code Version:
版本: 1.54.0-insider (user setup)
提交: 3290f9a73ba6fc3b1063ea32476067434ee91b1d
日期: 2021-02-26T05:13:29.656Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/70638039/109275048-2c8b2c80-784f-11eb-92a5-fea35e7281ed.png)

Steps to Reproduce:

1.set search in panel
2.open vscode-1.53.2 source by vscode insider
3.  \src\vs\workbench\contrib\search\common\searchModel.ts

`	preview(): { before: string; inside: string; after: string; } {
		let before = this._oneLinePreviewText.substring(0, this._rangeInPreviewText.startColumn - 1),
			inside = this.getMatchString(),
			after = this._oneLinePreviewText.substring(this._rangeInPreviewText.endColumn - 1);

		before = lcut(before, 26);
		before = before.trimLeft();

		let charsRemaining = Match.MAX_PREVIEW_CHARS - before.length;
		inside = inside.substr(0, charsRemaining);
		charsRemaining -= inside.length;
		after = after.substr(0, charsRemaining);

		return {
			before,
			inside,
			after,
		};
	}`
26 is too small for search panel(big panel small result like picture above)
can change to 80  or Match.MAX_PREVIEW_CHARS/2 or smart ?

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
You may be interested in search editors: https://code.visualstudio.com/updates/v1_43#_search-editors
