### ISSUE TITLE
Flickering when scrollbar fades out

### ISSUE THREAD

**Issue by Scratchcat1** [microsoft/vscode#117757]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Preview a PDF (e.g. with LaTeX Workshop)
- Open a document which has scrollbars.
- Hover over scrollbar.
- Move mouse so that the scrollbar fades away e.g. moving it to the bottom of the screen.

Expected result: 
Scrollbar fades out

Actual results:
Scrollbar fades out, UI has flickering black boxes for a second or two as the transition occurs.

Notes:
Started after an update to 1.53 from 1.52.
UI also sometimes stops rendering when resizing a window.

VS Code version: VSCodium 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-12T00:32:13.710Z)
OS version: Linux x64 5.8.0-3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 450  @ 2.40GHz (4 x 2632)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.46GB (2.10GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.16.0
svg|joc|1.4.1
python|ms-|2020.10.332292344
rust|rus|0.7.8
code-spell-checker|str|1.10.2

</details>

**Comment by rzhao271** [comment]
Can you attach a screencap showing the issue?

**Comment by Scratchcat1** [comment]
![flickering_rendering](https://user-images.githubusercontent.com/29149512/109349590-1c367a00-786e-11eb-9012-cd66ffd294b0.gif)

It appears this only occurs when using an external monitor.
Additionally any output on the laptop display freezes (even with Code not open) when connecting and disconnecting the monitor rapidly until the resolution is changed. Therefore I think it might be caused by some other component in the system and will close the issue for now.
