### ISSUE TITLE
Terminal API: Terminal object should include PID of the launched terminal

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#11775]
The new terminal API is looking great!  It'd be really helpful to me if I could get the process ID of the launched terminal as a property on the Terminal object.  I need this information in the PowerShell extension to help coordinate with my debug adapter. 

Also: could there possibly be a promise return type from createTerminal so that the Terminal only gets returned after the process is started, or maybe a different way like having an event on the Terminal object that is returned?

**Comment by Tyriar** [comment]
Exposing the PID and/or related info is to be explored in #11422. It would be useful if you could say on that issue exactly what you will do with the PID when you have it.

On `createTerminal` returning a promise, it was originally like this and @jrieken said that we normally hide the promise behind the scenes. So what happens now is that all calls on the `Terminal` returned by `createTerminal` are queued until the process is ready and then they're sent, so it should work roughly the same as a promise by just using it immediately after `createTerminal`. Example here: https://github.com/Microsoft/vscode-extension-samples/blob/70e8e730636549678703ba779aa2eaf5b309ecc4/terminal-example/src/extension.ts#L50

**Comment by daviwil** [comment]
Thanks Daniel!  The API approach you mention makes sense.  I left a comment on the other issue to explain what I'd use the PID for.
