### ISSUE TITLE
Edits all angle brackets when editing one

### ISSUE THREAD

**Issue by rizwanliaqat97** [microsoft/vscode#117761]
Issue Type: <b>Bug</b>

I'm coding in React  with JSX and noticed that when I typed equal character (=) after the logical less then operator (<) it also put the equal after other less then (<) characters at multiple places. The problem is depicted in the attached video below.

Wonderful IDE by the way. Love it. Regards.

**Problem's video depiction**
https://user-images.githubusercontent.com/50102771/109300782-cb685680-7858-11eb-8d6c-45ae8a4a656c.mp4

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.19.0-14-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3499)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.54GB (5.35GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
typingspeed|alb|0.0.2
project-manager|ale|12.0.1
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.14
git-extension-pack|don|0.1.3
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.23.1
todo-tree|Gru|0.0.197
rest-client|hum|0.24.4
docthis|joe|0.7.1
rainbow-csv|mec|1.8.1
template-string-converter|meg|0.4.7
vscode-typescript-tslint-plugin|ms-|1.3.3
material-icon-theme|PKi|4.5.0
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
json-schema-validator|tbe|0.1.0
ayu|tea|0.20.1
gitmoji-vscode|Vtr|1.0.4
vscode-open-in-github|ziy|1.3.6

(2 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please use the Start Extension Bisect command to investigate whether this is being done by one of your extensions.

**Comment by NotWearingPants** [comment]
It's obviously https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag ...
