### ISSUE TITLE
Minimum tab size

### ISSUE THREAD

**Issue by jpenna** [microsoft/vscode#117787]
Now with `workbench.editor.wrapTabs`, it would be really useful a midpoint between `workbench.editor.tabSizing: fit` and `workbench.editor.tabSizing: shrink`. 

If I don't shrink, they take too much space:

<img width="1184" alt="Screen Shot 2021-02-26 at 3 48 03 PM" src="https://user-images.githubusercontent.com/16005946/109342089-1d55b000-784a-11eb-8223-c0a891ec4046.png">

But if I shrink I can't read the file names:

<img width="1181" alt="Screen Shot 2021-02-26 at 3 46 45 PM" src="https://user-images.githubusercontent.com/16005946/109341911-dbc50500-7849-11eb-9c35-bc4cf9b0f4fe.png">

I guess a `workbench.editor.tabSizing: custom` and `workbench.editor.tabMinWidth: X` (in px?), which is only used when `tabSizing = custom` could solve this.

Edge case: if the full tab size (as in `fit`) is smaller than `tabMinWidth`, then the full tab size should be used regardless.

**Comment by bpasero** [comment]
Does https://github.com/microsoft/vscode/issues/115132 sound like it is what you are asking for?

**Comment by jpenna** [comment]
@bpasero it follows the same lines!

I am proposing a manual solution (you have to set the min width), and they are proposing an automatic solution. If that works, it would be good enough 👍
