### ISSUE TITLE
Reapply All Breakpoints not showing up in Command Palette

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#117712]
Testing #116101

I don't see anything show up under the Command Palette when I try searching 'Reapply All Breakpoints'. I can see commands like 'Toggle Activate Breakpoints', though.

**Comment by isidorn** [comment]
You need to be debugging.
Let me know if you do not see it while you are debugging and I can reopen

![Screenshot 2021-02-26 at 07 44 09](https://user-images.githubusercontent.com/1926584/109265208-74d22c80-7806-11eb-8fb0-6c438882458a.png)
