### ISSUE TITLE
Option to disable file formatting when file exceeds size or if formatter times out

### ISSUE THREAD

**Issue by Jarred-Sumner** [microsoft/vscode#117742]
If you save a minified JS bundle when Prettier is `editor.defaultFormatter`, saving stops working for up to a few minutes. I typically just force close VSCode at that point. The cancel button doesn't seem to work.

I definitely want to keep using Prettier, but it would be nice if there was an option to have the formatter skip files that exceed a certain size (say, 500 KB).

Potential option name: the closest-sounding option to this I can find is `editor.maxTokenizationLineLength`, so maybe something like `editor.maxFormatterFileLength`?

**Comment by jrieken** [comment]
We do have a limit in place and files larger than that won't be sync'd to the extension host process (and not formatted). Like this complained of the limit being too high, there are complains of the limit being too low. Therefore, you should take it to the prettier extension. They should not take soo long and bail out
