### ISSUE TITLE
"Kill Terminal"

### ISSUE THREAD

**Issue by techcom78** [microsoft/vscode#117775]
Does anybody know whether there is a setting which can "Kill Terminal" when the "Run....Terminal" is selected ? Having to press two buttons is becoming a joke. Even IF the button was NEXT to the "Run....Terminal" button it would certainly make it more useful than where it currently is positioned on the screen.

**Comment by Tyriar** [comment]
There is no run terminal button, you are probably using some extension. For kill terminal, I recommend setting up a keybinding, for example:

```
{ "key": "ctrl+shift+x",     "command": "workbench.action.terminal.kill" }
```

**Comment by techcom78** [comment]
![run_terminal](https://user-images.githubusercontent.com/34088809/109329264-48440200-7852-11eb-8bbf-0e5f62ca55c4.JPG)

I don't think it has anything to do with an extension.

**Comment by Tyriar** [comment]
It is, I'm guessing this one https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner
