### ISSUE TITLE
Quick open no longer selects first entry, on open

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#117750]
This seems to be a very recent regression:

1. <kbd>F1</kbd>

🐛 No entry is selected

This is a regression from at least Stable, but very likely introduced this week. It breaks certain power user scenarios such as <kbd>Ctrl E, E</kbd>. Or even the memory muscle of <kbd>F1, Enter</kbd> to rerun the last run command.

**Comment by bpasero** [comment]
For me the first entry is selected (pressing F1):

![recording](https://user-images.githubusercontent.com/900690/109278395-c5eb1c00-7818-11eb-9a25-7b9b54789926.gif)

**Comment by joaomoreno** [comment]
Yeah I can't repro in OSS. I also can't repro in Insiders any more... even though I just did 20 mins ago.

**Comment by joaomoreno** [comment]
Got it: I had screenreader mode enabled, somehow.
