### ISSUE TITLE
Git not installed error

### ISSUE THREAD

**Issue by cwpritt** [microsoft/vscode#117701]
- VS Code Version: 1.5.2
- OS Version: centos 7 

Steps to Reproduce:

1.  installed from rpm
2. open vsc, click on clone repository from welcome screen. says git not installed when it has been installed and is at /user/bin/git    

Does this issue occur when all extensions are disabled?: Yes/No
yes

**Comment by gjsjohnmurray** [comment]
Please clarify exactly what VS Code version number you have.

If it is 1.53.x then your problem may be this version isn't compatible with CentOS 7.

**Comment by cwpritt** [comment]
it is 1.53.2 the latest available from visual studio code.
git was installed a while back and i use it regularly in my bash command terminal window.

just installed vlc 1.53.2 rpm file and cannot git it to recognize that git is installed in centos7.

**Comment by cwpritt** [comment]
here is the info fromthe about:
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 3.10.0-1160.15.2.el7.x86_64

**Comment by lszomoru** [comment]
@cwpritt, are you still seeing this issue with the latest version of VS Code?
