### ISSUE TITLE
Unable to terminate Running Tasks manually

### ISSUE THREAD

**Issue by MBReddyEEPProd** [microsoft/vscode#117729]
Issue Type: <b>Bug</b>

Unable to terminate Running Tasks manually (When Right clicked the Running task and hit 'Cancel Task').

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.65GB (5.77GB free)|
|Process Argv|--crash-reporter-id 26c76c25-d30b-422f-b919-084dec9b2725|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.9.2
forcecode|Joh|3.22.9
vscode-xml|red|0.15.0
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|51.2.0
salesforcedx-vscode-apex|sal|51.2.0
salesforcedx-vscode-apex-debugger|sal|51.2.0
salesforcedx-vscode-apex-replay-debugger|sal|51.2.0
salesforcedx-vscode-core|sal|51.2.0
salesforcedx-vscode-lightning|sal|51.2.0
salesforcedx-vscode-lwc|sal|51.2.0
salesforcedx-vscode-visualforce|sal|51.2.0
sfdx-package-xml-generator|Vig|2.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubsetcf:30264245
pythontbcf:30260844

```

</details>

**Comment by alexr00** [comment]
Can you provide screen shots or a video/gif of where you are right clicking?
