### ISSUE TITLE
Can't debug node.js with `integratedTerminal` setting using MINGW64

### ISSUE THREAD

**Issue by akatechis** [Microsoft/vscode#11778]
- VSCode Version: 1.5.1
- OS Version: Windows 10 Home Edition

Steps to Reproduce:
1. I have MINGW64 installed (the one bundled with the Git installer).
2. I opened my node.js project in VSCode 1.5.1
3. Set up a `launch.json` file as follows:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/index.js",
      "stopOnEntry": false,
      "args": [],
      "cwd": "${workspaceRoot}",
      "preLaunchTask": null,
      "runtimeExecutable": null,
      "runtimeArgs": [
        "--nolazy"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "console": "integratedTerminal",
      "sourceMaps": false,
      "outDir": null
    }
  ]
}
```
1. When I launch, I see a MINGW64 window open up, the directory is set correctly, but it's not doing anything, just waiting for me to type a command.
2. After 10 seconds, the task in VSCode times out.

Things I've tried:
1. Running `npm start` in cmd.exe, or in mingw works fine.
2. Changing `integratedTerminal` to `"externalTerminal"` or `"internalConsole"` work fine.

**Comment by Tyriar** [comment]
#8429 may be the cause of this

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/19334
