### ISSUE TITLE
Double-clicking leading whitespace should select all leading whitespace

### ISSUE THREAD

**Issue by latkin** [Microsoft/vscode#1177]
In most editors, you can double-click anywhere in the leading whitespace of a line to select all such leading whitespace (even mixed tab/space).

In VS Code, double-clicking leading whitespace only selects that single whitespace character.

Examples of expected behavior in Notepad++ and VS, and unexpected behavior in Code:

![leadingwhitespace](https://cloud.githubusercontent.com/assets/5943573/11728708/256edbe2-9f40-11e5-9d99-6083e65eb1e5.gif)

**Comment by egamma** [comment]
fyi @alexandrudima

**Comment by csholmq** [comment]
+1

**Comment by alexandrudima** [comment]
We actually shipped with this behaviour already in February.
