### ISSUE TITLE
SFTP Sync fails in version 1.53

### ISSUE THREAD

**Issue by snehakrishnamurthy** [microsoft/vscode#117773]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. On VSCODE create a sftp.json to sync files, when tryin to syc remote to local or visa versa we get error: Extension host terminated unexpectedly. Need to downgrade to 1.52 for SFTP to work

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by gjsjohnmurray** [comment]
/duplicate and reported to be fixed in current Insiders (1.54), which is expected to release next week.

**Comment by snehakrishnamurthy** [comment]
can you please provide a link to the other issue

**Comment by gjsjohnmurray** [comment]
A GH filter with the term `sftp` gave me this as the third match in the Closed tab:

#116727
