### ISSUE TITLE
TSC / TS language server version mismatch can only be 'ignored' globally

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#11772]
- VSCode Version: 1.5.0

The check if the globally installed tsc version matches the TS version has a "Don't check again' message box. If pressed we never check again, even if the user opens another workspace. The reason why I did this is that the tsc is global. Now that I think about it again I am wondering if we should check once per workspace. 

@waderyan @egamma opinions?

**Comment by waderyan** [comment]
Let me make sure I understand. 

Status quo - We show a message indicating that there is a version mismatch between TSC / TS language server, but only for the globally installed version of tsc. We give the user the option to "Don't check again". If the user clicks "Don't check again" we will never show the message again for any workspace. 

The risk with the status quo is that users may have installed tsc locally to their workspace. Users may have different versions of tsc for each workspace. If this is the case then we should check for each workspace and let them know if their is a mismatch. 

Proposal - Run the check for each workspace. If a local version of tsc is detected and it is a different version than TS show the message for each workspace. Allow the user the option to "Don't check again." for the workspace. This handles the local tsc installation, but risks showing too many messages. 

Is my understanding correct?

**Comment by dbaeumer** [comment]
No. If there is a local version of the TS installed and used by tsdk setting then we don't perform any checks since we assume that the suer knows what he does (he was adding the setting). If we detect a local installed typescript and it is not used and differs from the version we ship we show a warning. However if the user pressed Don't check again we never check again on any workspace. This one should actually be done per workspace. The tsc check should may be stay globally since the tsc compiler is globally installed.

**Comment by waderyan** [comment]
@dbaeumer thank you for clarifying. My opinion is that the check per workspace makes sense. The message should be "don't check for this workspace" or something to indicate that the check will only be ignored for the workspace.

**Comment by dbaeumer** [comment]
Discussed with @egamma and we decided to not do something for 1.5.x. For 1.6 we will get settings API and can do much better anyways.

**Comment by dbaeumer** [comment]
Addressed for 1.6. I also update the settings files. Test plan item is here:  https://github.com/Microsoft/vscode/issues/12680

**Comment by sandy081** [comment]
Verified and also looks like this is part of the test plan item

**Comment by lushibi** [comment]
any steps to make them matching except clicking "don't show again"?
