### ISSUE TITLE
File Icon Theme: Better icon for HTML file

### ISSUE THREAD

**Issue by MarkSky** [Microsoft/vscode#11776]
- VSCode Version:1.5.1
- OS Version: Windows 10

Steps to Reproduce:

1. HTML檔的icon在vscode-icons擴充套件提供的圖示比1.5版內建的圖示容易知道這是HTML檔。希望能改善圖示。

**Comment by ramya-rao-a** [comment]
@MarkSky Can you please update the issue in English ?

**Comment by MarkSky** [comment]
Sorry!
I just have a suggestion.
After I update Visual Studio Code to version 1.5.1, I got it support file icon (File Icon Theme) in  it.
But I found the icon of html file in vscode-icons plugin is better and it is easier to know what the file is.
So I think maybe you can change the icon of html file in File Icon Theme.
Thanks.

**Comment by ramya-rao-a** [comment]
Thanks for the clarification

**Comment by aeschli** [comment]
@MarkSky We are using the Seti Ui theme icons from https://github.com/jesseweed/seti-ui/.
Please make icon requests there.

vscode-icons has also updated to the new icon selection dialog an now work without modifying VSCode!
