### ISSUE TITLE
Feature Request : Allow users to import eclipse/xml color themes to VSCode

### ISSUE THREAD

**Issue by EvandroLucas** [microsoft/vscode#117776]
Currently there is no way of editing a color theme or importing one from a xml file. Instead, users have to rely on extensions and built-in themes. The Eclipse Color Themes extension for the Eclipse IDE [allow users to make their own themes](http://www.eclipsecolorthemes.org) simply by editing and importing an user-friendly xml file. Allowing users to import such themes as xml's would be a great addition to the IDE, IMO. I don't know if the eclipse format is in itself compatible with how VSCode manages it's themes (would be really nice if it would), but anything close to just editing an xml file will already be a huge improvement over the current system. 

Let me know what you think, and thanks in advance!

**Comment by aeschli** [comment]
We'd rather not have a second theme definition file. But one could write an extension that lets you import an Eclipse theme and tune it. VSCode themes have many more colors which are specific to VScode and, in the end, all need to work together.

https://code.visualstudio.com/api/extension-guides/color-theme
https://code.visualstudio.com/api/references/theme-color
