### ISSUE TITLE
Depreciated warning in the wrong place

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#117745]
When writing javascript, vscode will put a strike through depreciated words found in object literal property declarations such as `const p = { name` until the colon is added. This seems like it is checking in the wrong place for this type of error as there are no depreciated words in this context.

**Comment by gjsjohnmurray** [comment]
See #114725 for information and links

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/18433
