### ISSUE TITLE
No visual indication that cells have been multiselected on high contrast theme

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#117705]
Verifying https://github.com/microsoft/vscode/issues/117449

1. Open a .github-issues notebook
2. Change theme to high contrast
3. Shift + click to multiselect some cells

The original active cell still shows the orange border, but the other select cells don't have any background change

**Comment by rebornix** [comment]
@misolori can you help with this, I didn't add colors for it as I found that we leave hc null in some other notebook color rules.

**Comment by misolori** [comment]
This should now match the explorer:

![image](https://user-images.githubusercontent.com/35271042/113534712-61914a00-9586-11eb-881e-2daf57283dcd.png)

![image](https://user-images.githubusercontent.com/35271042/113534719-62c27700-9586-11eb-9eb3-a2920f2d2abc.png)
