### ISSUE TITLE
File specific Git commands are available for files outside of repository

### ISSUE THREAD

**Issue by Marcono1234** [microsoft/vscode#117707]
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.9.2
vscode-codeql|Git|1.4.3
vscode-test-explorer|hbe|2.19.5

</details>

There are some Git commands which are specific to the current open file, e.g.:
- "Git: Rename"
- "Git: Add to .gitignore"
- "Git: Open File"
- "Git: Open File (HEAD)"
- "Git: Initialize Repository" (not directly related to open file, but still misleading)

The issue is that these commands also appear when opening a single separate file from outside the repository.

Steps to reproduce:
1. Create a folder `somefolder`
2. Initialize a Git repository (from VSCode or command line)
3. Open the folder in VSCode
4. Create a file `outside.txt` somewhere outside that folder
5. Open the file in VSCode (through "File" > "Open File...")
6. Have a look at the available Git commands

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
The latest version of Insiders contains improvements for the following commands.

The following commands are only available in the command palette if the file is under any of the opened repositories:
* "Git: Rename"
* "Git: Add to .gitignore"

The following commands are only available in the command palette if the files have any changes:
* "Git: Open File"
* "Git: Open File (HEAD)"

No changes were made to the "Git: Initialize Repository" as I can see scenarios in which the user would like to initialise a repository even though the folder/workspace that is currently opened already contains a git repository.
