### ISSUE TITLE
Unable to load some scripts in Notebook Renderer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#117809]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Install Jupyter Extension
2. Add a cell as follows
```html
%%html
<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@2.0.0"></script>
```
3. Select a Python kernel & run this.
FYI - In Jupyter this is a simple way to add HTML to the output (renderer).

This will add the above script tags to the renderer page.
Looking at the console logs, there are errors logged by VS Code

Here the output from the console log in the renderer tab
```
Uncaught Error: Can only have one anonymous define call per script file
    at r.enqueueDefineAnonymousModule (loader.js:1316)
    at p (loader.js:1803)
    at VM109 tfjs@2.0.0:17
    at VM109 tfjs@2.0.0:17
r.enqueueDefineAnonymousModule @ loader.js:1316
p @ loader.js:1803
(anonymous) @ tfjs@2.0.0:17
(anonymous) @ tfjs@2.0.0:17
```

Does this issue occur when all extensions are disabled?: N/A

@rebornix /cc

**Comment by rebornix** [comment]
see https://stackoverflow.com/questions/55057425/can-only-have-one-anonymous-define-call-per-script-file

one way to workaround this is

```
%%html
<script>
require(['https://cdn.jsdelivr.net/npm/@tensorflow/tfjs?noext'], function(tf) {
	console.log(tf);
});
</script>
```

**Comment by DonJayamanne** [comment]
Doesn't seem to be an issue anymore.
