### ISSUE TITLE
When inserting a snippet through registerCompletionItemProvider, the corresponding name is not displayed in the pop-up list

### ISSUE THREAD

**Issue by babycannotsay** [microsoft/vscode#117863]
1. version
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.4.0
```
2. reproducible step
snippet in snippet file
```
"snippet file div": {
    "prefix": "sf",
    "body": ["<div>${1:null}</div>"],
    "description":"from snippet file"
}
```
![image](https://user-images.githubusercontent.com/17975694/109478745-99533080-7ab4-11eb-9ab3-2e7522857ca7.png)

extention code
```typescript
vscode.languages.registerCompletionItemProvider('javascript', {
	provideCompletionItems () {
		const snippetCompletion = new vscode.CompletionItem('esf')
		const snippetBody = ["<div>${1:null}</div>"]
		snippetCompletion.insertText = new vscode.SnippetString(snippetBody.join('\n'))
		snippetCompletion.detail = 'from extension'
		snippetCompletion.kind = vscode.CompletionItemKind.Snippet
		return [ snippetCompletion ]
	},
})
```
![image](https://user-images.githubusercontent.com/17975694/109479352-4168f980-7ab5-11eb-95af-6463e5b6071f.png)

3. question
As you can see, it can show by snippet file, but not registerCompletionItemProvider.
Is there any means for registerCompletionItemProvider to display the name?

**Comment by babycannotsay** [comment]
I have updated the info @jrieken

**Comment by jrieken** [comment]
depends on this API being finalized: https://github.com/microsoft/vscode/issues/39441

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"needs more info"

**Comment by babycannotsay** [comment]
thanks
