### ISSUE TITLE
Is there any api that can format snippet code?

### ISSUE THREAD

**Issue by babycannotsay** [microsoft/vscode#117864]
1. version
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.4.0
```
2. reproducible step
snippet in snippet file
```
"snippet file div": {
    "prefix": "sf",
    "body": ["<div>${1:null}</div>"],
    "description":"from snippet file"
}
```
![image](https://user-images.githubusercontent.com/17975694/109479758-ade3f880-7ab5-11eb-89f0-7c7db9b3371a.png)

extention code
```typescript
vscode.languages.registerCompletionItemProvider('javascript', {
	provideCompletionItems () {
		const snippetCompletion = new vscode.CompletionItem('esf')
	        const snippetBody = ["<div>${1:null}</div>"]
	        snippetCompletion.insertText = new vscode.SnippetString(snippetBody.join('\n'))
	        snippetCompletion.detail = 'from extension'
	        const mdString = new vscode.MarkdownString('')
	        snippetCompletion.documentation = mdString.appendCodeblock(snippetBody.join('\n'))
	        snippetCompletion.kind = vscode.CompletionItemKind.Snippet
	        return [ snippetCompletion ]
	},
})
```
![image](https://user-images.githubusercontent.com/17975694/109480041-01564680-7ab6-11eb-9448-672f6cd5563a.png)

3.question
Inserting a snippet through registerCompletionItemProvider will not automatically format the code.
But configuring the snippet file will automatically format the code. Is there any api that can format snippet code?

**Comment by babycannotsay** [comment]
I find MarkdownString's instance method `appendCodeblock` which appends the given string as codeblock using the provided language. But can it parse snippet syntax?
![image](https://user-images.githubusercontent.com/17975694/109448525-1ebced80-7a81-11eb-885b-80d7c74526f1.png)

**Comment by babycannotsay** [comment]
I hava updated the info @jrieken

**Comment by jrieken** [comment]
Thanks for clarifying. 

There is no API for you. The snippet completion have access to the snippet parser and its description automatically becomes the text that will be inserted, e.g without tabstops or other snippet syntax.
