### ISSUE TITLE
Status bar overflow

### ISSUE THREAD

**Issue by alexreg** [microsoft/vscode#117861]
The status bar contents can become very long when certain extensions are active (e.g., Python). This pushes some very useful information like the line:column number off the right edge of the status bar such that it's not visible any more. Ideally, all the usual right-hand-side items in the status bar would still be visible, and the left-hand side items originating in extensions would 'spill over' into an overflow bar that appears on mouse-over or clicking a button in the status bar, perhaps.

**Comment by sbatten** [comment]
@bpasero are you owning the status bar layout?

**Comment by alexreg** [comment]
@rzhao271 How can I then make those parts reappear? That's good to know, but an overflow would still be nicer.

**Comment by sbatten** [comment]
@alexreg right click anywhere in the status bar and recheck them.

**Comment by alexreg** [comment]
Ah okay. Now that I'm by the computer, I can see that's obvious. Cheers.
