### ISSUE TITLE
Setting editor.accessibilityPageSize isn't working with macOS VoiceOver

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#117880]
- VS Code Version: 1.53.2 / Insiders 1.54.0
- OS Version: macOS Big Sur 11.2.2

Steps to Reproduce:
1. Apple menu > System Preferences > Accessibility > VoiceOver > Enable VoiceOver
2. Switch to any document with more than 10 lines (I suggest creating an untitled document with numbers from 1, 2, 3, ...)
3. Notice the VoiceOver utility keeps reading after the 10th line

Does this issue occur when all extensions are disabled? Yes, in both VS Code and Insiders.

**Comment by isidorn** [comment]
@andrecasal `editor.accessibilityPageSize` is a workaround setting for a Chrome issue which is only reproducable on windows. More details here https://github.com/microsoft/vscode/issues/89717

Why would you like to set this setting to any other value?
Also by default it might be 100 on macOS.

**Comment by andrecasal** [comment]
I'm trying to understand what this setting does to put it on my [VS Code settings playlist](https://www.youtube.com/watch?v=0P0mdawQ13A&list=PLVwLx67OHLu1HIbCihg3cohaM5eCarbiQ).

If I understand correctly, [we still don't have an answer regarding this being a NVDA or Chrome issue](https://github.com/nvaccess/nvda/issues/8781#issuecomment-580669608), correct?

Should we add the fact that this only affects Windows users with NVDA to the setting's description?
Also, would it be useful to add some kind of tag to temporary/workaround settings? VS Code has a few settings like this that only exist until a particular bug is fixed.

Should I open a request to clarify the settings description here and on the docs repo?

**Comment by isidorn** [comment]
No need for a new issue, I will use this one as a way to clarify the current setting.

As for the tag to temproary settings that might make sense, however I personally just deprecate settings once they are no longer needed.

This commit changes everything I have in plan 4de8cb29073
My plan is to deprecate that setting, which I might do this milestone
Thus closing this

**Comment by andrecasal** [comment]
Thanks @isidorn 👍

Is there a standard way to track these temporary/workaround settings and checks for when they are no longer needed?

Also, out of curiosity, which piece of software holds the Say All command? I don't see it in VS Code or macOS's VoiceOver so I'm guessing it's an NVDA command?

**Comment by isidorn** [comment]
@andrecasal no, we do not have a standard way for this, sorry.

Yes Say All is an NVDA command. I think Orca on Linux also has it. For VoiceOver I am not sure, if you did not find it there then VoiceOver might not support it.
