### ISSUE TITLE
Disabling "Copy With Syntax Highlighting" still keeps some garbage in clipboard

### ISSUE THREAD

**Issue by jihu** [microsoft/vscode#117879]
- VS Code Version:
- OS Version:

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

### Problem description:
Disabling the setting "_Copy With Syntax Highlighting_" (ie setting "**editor.copyWithSyntaxHighlighting**": **false**) does not work properly. I expect that having disabled this setting, anything I copy (using regular **Ctrl+C**) from the editor should be in pure plain text format. But my tests show that not to be the case. I had problems pasting the text in an online word document, edited in the Chrome browser. The text gets pasted with a bold format. If I paste it into notepad, then copying that text, then the text is clean when pasted into word.

Using the windows program **ClipView**, that shows technical details about the current clipboard content, I was able to identify the problem. When copying text in Visual Studio Code, even with "editor.copyWithSyntaxHighlighting": false, it adds a clipboard format called "**Chromium Web Custom MIME Data Format**". If I copy text from notepad this "Chromium Web Custom MIME Data Format" is not included. And some programs, like the Word web editor in Chrome it seems, sees this format and decides "this text should have a bold format!".

### Steps to reproduce:
1. Open Visual Studio Code with all extensions disabled
2. Write some text in some plain text format, select the text, and copy it using Ctrl+C
3. Inspect the clipboard content using ClipView (or some similar program)

### Expected result:
* Only regular plain text clipboard formats should be seen

### Actual result:
* A clipboard format called "Chromium Web Custom MIME Data Format" is included

I see this as a bug. With the setting "editor.copyWithSyntaxHighlighting": false, any copied text should be pure plain text in the clipboard, and nothing else. So the clipboard format called "Chromium Web Custom MIME Data Format" should be removed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@deepak1556 any idea?

**Comment by deepak1556** [comment]
Clipboard mime data is appended by the runtime, VSCode does not have control over it. Closing as not actionable.
