### ISSUE TITLE
Add Powershell as integrated terminal in VSC for Windows? [Feature Request] 

### ISSUE THREAD

**Issue by saifali96** [Microsoft/vscode#11785]
Guys I love the work you people are doing! Just make it more lovable by adding/allowing Powershell in integrated terminals.

**Comment by factormystic** [comment]
Put this in your user settings.json:
```json
"terminal.integrated.shell.windows": "\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"
```

**Comment by saifali96** [comment]
Well that breaks it, 
`The token '&&' is not a valid statement separator in this version`
I guess it won't work in PS, as the command that VSC debugger gives is another call to cmd (command prompt) so it won't work until VSC guys do something.

**Comment by factormystic** [comment]
It's working for me on v1.5.1 right now. I pasted that line out of my own settings.json. Something else is going on to produce that error.

**Comment by saifali96** [comment]
Well to be honest, doesn't matter if we put Powershell as integrated terminal, the issue is or perhaps it is intended, a call to cmd is made, even from cmd, first part is `cd drive:/dir/` and then `&&` to run the node script in debug mode and other things along with the previous command after changing dirs ofcourse, so I don't know how the change the command that's called from within VSC, if we are able to control that, then yes we can use Powershell to debug in the terminal without calling cmd for the REPL mode.
Correct me if I'm wrong.
```
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS D:\BFW\Casey Bot> cd "d:\BFW\Casey Bot" && cmd /C "set "NODE_ENV=development" && node --debug-brk=18993 --nolazy validated.js"
+ cd "d:\BFW\Casey Bot" && cmd /C "set "NODE_ENV=development" && node - ...
+                       ~~
At line:1 char:23
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

PS D:\BFW\Casey Bot>
```

**Comment by factormystic** [comment]
Oh, well there's the problem right there. You're trying to run `cmd` shell commands in a `powershell` shell. That's not going to work.

Your request in this issue is to be able to use powershell as an integrated terminal shell and that part is working fine. The part that isn't working fine is whatever program you're using to start node can only be run from a cmd shell. You didn't share that information or this node debugging scenario as your original problem.

**Comment by weinand** [comment]
Please suggest how to achieve the following with PowerShell:
- cd to a directory
- set some environment variables for the following command
- run 'node' (or any other program) with a set of arguments.

**Comment by saifali96** [comment]
@weinand Powershell is very similar to `cmd` and `bash`. It's a shell scripting language as well as a interactive/REPL shell for Windows and now also for other platforms. Anyhow to:

- to cd to a dir you use `cd [localdrive]:\parentdir\localdir`, of course you can remove localdrive thing if you are in that drive you want to cd into and also if the dirname contains spaces you should use `" "`.

- to set some environment variables, here's a great reference from MS, [env variables](https://technet.microsoft.com/en-us/library/ff730964.aspx).

- to run node it's simple, `$ node server.js arg1 arg2 argn`

Hope this helped.

**Comment by daviwil** [comment]
@saifali96 It seems your error is related to using `&&` to chain together commands.  This isn't valid syntax in PowerShell, expressions/commands should be separated on the same line using the semicolon character `;`.  So in your example it'd be:

`cd "d:\BFW\Casey Bot"; cmd /C "set "NODE_ENV=development"; node --debug-brk=18993 --nolazy validated.js"; cd "d:\BFW\Casey Bot"; cmd /C "set "NODE_ENV=development"; ...` etc

If that wasn't the problem, can you clarify what the current issue is?

**Comment by weinand** [comment]
@daviwil thanks for the example. I will try to detect that PowerShell is used and then create the appropriate code from above.

**Comment by saifali96** [comment]
@daviwil that would work but still we are calling `cmd` from within `PS` which doesn't make sense and we can't change the command that's being called when start debugging, do you know how to change change the command that's called?
I'll fork the repo and add that in codebase to allow for `PS` explicitly for debugging and then fire up a PR.

**Comment by daviwil** [comment]
Thanks for clarifying!  I understand now, the debugger client is sending the wrong commands to the console when you have selected powershell.exe as your integrated terminal app.  @weinand, let me know if there's any way I can help.
