### ISSUE TITLE
Is there any api that only listen to specific snippet selections, so that I can insert some text in other position?

### ISSUE THREAD

**Issue by babycannotsay** [microsoft/vscode#117884]
### version
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.4.0
```
### reproducible step
snippet in snippet file
```
"snippet file Icon": {
    "prefix": "sf",
    "body": ["<Icon>${1:null}</Icon>"],
    "description":"from snippet file"
}
```

for example:
1. type `sf` and Enter to select the `snippet file Icon`
2. at the same time, insert `import Icon from 'xx'` in other position

#### Is there any api that only listen to specific snippet selections, so that I can insert some text in other position?
I know it can be achieved through `CompletionItem.textEdit` or `CompletionItem.command`. But it lost [detail]#117863 and [formatted snippets]#117864.

**Comment by jrieken** [comment]
Sorry, I don't understand what you want. How does snippet insertion (user action) and code actions (user action) relate to API? Maybe it easier if you explain what you are trying to achieve?

**Comment by babycannotsay** [comment]
snippet is as follows
```
"snippet file Icon": {
    "prefix": "sf",
    "body": ["<Icon>${1:null}</Icon>"],
    "description":"from snippet file"
}
```
then
1. Create a empty javascript file
2. navigate to line 2
3. type sf and select the snippet
4. the content of the file is as follows
```
import Icon form 'xx'
<Icon></Icon>
```

what i try to achieve is automatic insert `import Icon from 'xx'` when I select the snippet `sf`

**Comment by jrieken** [comment]
> What i try to achieve is automatic insert import Icon from 'xx' when I select the snippet sf.

You cannot do that. A snippet is always static and doesn't involve any dynamic code action. What you should do instead is to implement a completion item provider which provides the snippet as completion. The completion will then also support an additional text edit that can insert the import

**Comment by babycannotsay** [comment]
> > What i try to achieve is automatic insert import Icon from 'xx' when I select the snippet sf.
> 
> You cannot do that. A snippet is always static and doesn't involve any dynamic code action. What you should do instead is to implement a completion item provider which provides the snippet as completion. The completion will then also support an additional text edit that can insert the import

But it lost [detail]#117863 and [formatted snippets]#117864.

**Comment by babycannotsay** [comment]
I mean when i select static snippet, can it trigger event like `onDidChangeTextDocument`?
