### ISSUE TITLE
Icon Per Project like chrome user

### ISSUE THREAD

**Issue by mostafaabobakr7** [microsoft/vscode#117889]
![image](https://user-images.githubusercontent.com/27288406/109502734-0a3d1d00-7aa2-11eb-8e37-98e76f3d4811.png)

# Icon per Project like chrome user

- Each project can assign icon to easily identify different projects
- Assigning icons Can depend on [Project Manager extension](https://github.com/alefragnani/vscode-project-manager) !

**Comment by misolori** [comment]
@deepak1556 is this even possible via the electron api?

**Comment by deepak1556** [comment]
Not possible, we currently open vscode instances in a singleton model (multiple instances of the app will connect to the same parent instance), we can't assign subicons in this scenario.

**Comment by rzhao271** [comment]
Assigning to @misolori since I'm not sure what the priority on this is, if any.
