### ISSUE TITLE
Open file and open settings have the same icon

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117801]
- VS Code Version: 1.54-Insiders
- OS Version: macOS

It's minor but weird when I see two same icons when viewing diff of settings

<img width="393" alt="image" src="https://user-images.githubusercontent.com/876920/109362003-02ca0980-783f-11eb-9e20-797dc1c7acd3.png">

**Comment by misolori** [comment]
@rebornix what are the steps to get to this state? Settings sync related?

**Comment by rebornix** [comment]
@misolori sorry for missing the details:

* Open VS Code repo
* Change workspace settings
* Open the setting file in diff editor

**Comment by rzhao271** [comment]
The diff editor nowadays only shows the Open File option, which makes sense to me.
