### ISSUE TITLE
Test Explorer progress should show me the number of total tests

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#117890]
Testing #117305

Currently the test explorer shows me the number of tests that have passed. Suggest that the progress feedback also shows the total number of tests that are executed

![image](https://user-images.githubusercontent.com/172399/109505466-ea572a80-7a9c-11eb-84bc-5a66272c126f.png)

**Comment by TylerLeonhardt** [comment]
@connor4312 something is a bit off with the selfhost test extension... first, I get 5 tests running:
![image](https://user-images.githubusercontent.com/2644648/112232790-6a813380-8bf6-11eb-8dc5-72ceb230e047.png)

but in the end, 2 were the result:
![image](https://user-images.githubusercontent.com/2644648/112232823-7ec53080-8bf6-11eb-8671-9c12324b1b9e.png)

**Comment by connor4312** [comment]
That's the same as https://github.com/microsoft/vscode/issues/119667
