### ISSUE TITLE
Remote terminal reconnect doesn't seem to work currently

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117896]
Just tried on main, also insiders with Remote - WSL doesn't work.

**Comment by roblourens** [comment]
Still not working for me

**Comment by roblourens** [comment]
I open a terminal, type something, reload the window, and get a fresh terminal

**Comment by meganrogge** [comment]
do you have enablePersistentSessions : true?

**Comment by roblourens** [comment]
I don't have any relevant settings set

**Comment by meganrogge** [comment]
any errors in dev tools?

**Comment by roblourens** [comment]
no

**Comment by Tyriar** [comment]
Something is a bit off, I tried and the restoration seems flaky now. This is what the server looks like after some testing, all the processes are still hanging around just they don't get attached:

![image](https://user-images.githubusercontent.com/2193314/109572628-70c23b00-7aa2-11eb-88f7-ba480a2c230c.png)

**Comment by Tyriar** [comment]
After shutting everything down it works fine for the first window, the second window it doesn't 😕 

@meganrogge can you look into this? Check what terminals are getting saving into the server layout info vs what the renderer gets.

**Comment by chrisdias** [comment]
Testing the fix... one of my terminals sometimes reattaches, the second one doesn't.

before:

![image](https://user-images.githubusercontent.com/1487073/109594762-366b9480-7ac8-11eb-85c0-161f6e124369.png)

after reload window:

![image](https://user-images.githubusercontent.com/1487073/109594822-48e5ce00-7ac8-11eb-8098-e747ea9befb0.png)

Here's the repo: https://github.com/chrisdias/gh-static-e2e

steps to reproduce:

`git clone https://github.com/chrisdias/gh-static-e2e`

In a terminal:

`npm install`
`npm run server`

split the terminal

`npm run start`

`F1` > `Developer: Reload Window`

**Comment by Tyriar** [comment]
It's failing here because `isOrphan` is false:

https://github.com/microsoft/vscode/blob/44955421ae71f1d0c6b0b49414fa6b36aaf6d2cf/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L195

This is the layout that comes back:

```js
[
  {
    terminal: {
      id: 1,
      title: 'pwsh.exe',
      pid: 6608,
      workspaceId: 'empty-window',
      workspaceName: '',
      cwd: 'C:\\Users\\Daniel',
      isOrphan: false
    },
    relativeSize: 0.5
  },
  {
    terminal: {
      id: 2,
      title: 'pwsh.exe',
      pid: 252,
      workspaceId: 'empty-window',
      workspaceName: '',
      cwd: 'C:\\Users\\Daniel',
      isOrphan: false
    },
    relativeSize: 0.5
  }
]
```

Still investigating...

**Comment by Tyriar** [comment]
The above seems to be an existing problem where empty-window is treated a little differently, so multiple empty windows on web share the same key and step on each others toes.

The actual problem is related to how reconnect interacts with env var relauches, remote terminals seems to be using the terminal instance ID, not the persistent terminal process ID. So if any terminals relaunch it ends up messing up everything. So this actually works fine because the terminal instance IDs and persistent terminal process IDs align until a relaunch occurs:

- Killing the restored terminal immediately on launch, before the git extension activates, then create terminals after extensions are activated.

**Comment by Tyriar** [comment]
Verification steps:

1. Open a new window that restores the terminal
2. Type `ls` into the first terminal _before_ extensions activate
3. Split the first terminal (ctrl+shift+5) _before_ extensions activate
4. Wait for extensions to activate
5. Type something into the second terminal so you can tell if it restores
6. Reload, **the terminals should restore**
7. Open a new window with a different folder
8. Create several terminals (ext host timing doesn't matter)
9. Run something in the terminals so you can tell they restore
10. Reload the window, **the terminals should restore**
11. Go back to the original window from step 1
12. Reload the window, **the terminals should restore**

**Comment by Tyriar** [comment]
Reopening until https://github.com/microsoft/vscode/pull/117972 is merged
