### ISSUE TITLE
Linux Snap package startup speed

### ISSUE THREAD

**Issue by Hans03430** [microsoft/vscode#117852]
Hello, are there any plans to use the LZO compression inside the snapcraft.yaml file in order to improve the startup speed of VS Code when installed as a Snap in Linux?

**Comment by joaomoreno** [comment]
There is currently no feature work planned for the snap package.

**Comment by roblourens** [comment]
What needs to be verified exactly?

**Comment by joaomoreno** [comment]
**Verification**

Download our snap package and make sure it has lzo compression.

```
$ unsquashfs -s code-insider-x64-*.snap | grep Compression
Compression lzo
```

**Comment by Hans03430** [comment]
Hello. I don't know where to download the .snap file but I installed Visual Code Insiders from the Snapcraft store and I can confirm that the startup speed of the Insiders version is far faster than the non Insiders one. VS Code Insiders cold starts in a second while the non Insider version takes far longer.

**Comment by joaomoreno** [comment]
Here's the latest snap package: https://az764295.vo.msecnd.net/insider/26a60dbecacc8bdacc06f7681ebe95398878a1cd/code-insider-x64-1617014928.snap

**Comment by Hans03430** [comment]
xxx@xxxxx:~/Descargas$ unsquashfs -s code-insider-x64-*.snap | grep Compression
Compression lzo

I can confirm that the package says it has lzo compression after running that command.
