### ISSUE TITLE
Codicons spinning off-center in custom tree view

### ISSUE THREAD

**Issue by cschleiden** [microsoft/vscode#117859]
- VS Code Version: 1.54.0-insider
- OS Version: OSX Big Sur

Steps to Reproduce:

1. Use `sync~spin` as an icon in a tree view, example here: https://github.com/microsoft/vscode-extension-samples/compare/main...cschleiden:cschleiden/spin-sync

Expected: the icon rotates around its center
Actual: the icon rotates off center

![CleanShot 2021-02-28 at 15 46 25](https://user-images.githubusercontent.com/2201819/109438007-bc121600-79dc-11eb-8e65-e02bb8f88b82.gif)

The same happens with other codicons that support the spin modifier (e.g., `gear~spin`). The `div` that the spin modifier is applied to, doesn't have its `width` and `height` fixed and includes a `padding-right` of `6px` which seems to cause this off-center rotation:

https://github.com/microsoft/vscode/blob/84a3473d324e562f373ef20eaa44ff81c6bfaa27/src/vs/workbench/browser/parts/views/media/views.css#L138

https://user-images.githubusercontent.com/2201819/109438670-d4376480-79df-11eb-9b98-1fd455370777.mp4

**Comment by misolori** [comment]
@joaomoreno @aeschli I also believe this happens in the tree view because the dimensions are not square. However this doesn't appear to happen on the tree loading icon (the one we control), why is that?

**Comment by joaomoreno** [comment]
I believe we simply minutiously tweaked the loading icon's paddings and margins so it works just fine.

**Comment by IanMoroney** [comment]
@joaomoreno @misolori , is there anything that needs to be done to correct this issue? Is it just as simple as updating views.css as indicated?

**Comment by misolori** [comment]
@IanMoroney it's a lot more involved since this would affect all of our tree views and need to account for the several other places where it is used. I'll see if can fix this next week.

**Comment by misolori** [comment]
Made a fix that adds padding to the loading spinning icon make it square and offsets it via margin (not a pretty fix but haven't found an alternate solution):

<img width="400" src="https://user-images.githubusercontent.com/35271042/116902980-aee9f100-abf0-11eb-9311-53acbf280dba.gif">

<img width="400" src="https://user-images.githubusercontent.com/35271042/116902954-a7c2e300-abf0-11eb-94c4-496d24407bf5.png">
