### ISSUE TITLE
Getting Started incorrectly opens Fundamentals section on first launch

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#117865]
Issue Type: <b>Bug</b>

STR: Opened Insiders after a a long time, let update install and restarted.

AR:  Fundamentals page opens.
ER: Getting Started opens with Quick Setup page.

Moving up to index page shows nothing from Quick Setup is completed.

VS Code version: Code - Insiders 1.54.0-insider (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:10.253Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475

```

</details>

**Comment by JacksonKearl** [comment]
I believe this was fixed with the recent changes to opening on first go. Please reopen or create a new issue if not
