### ISSUE TITLE
.CS file type description changed to "URL:vscode" after upgrade to 1.5.1 (or 1.5.0)

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [Microsoft/vscode#11780]
It looks like the windows file type description is getting clobbered by the new version of VSCode. I had VSCode as the default program for .cs files but now the description has been changed to "URL:vscode"
This might have happened after the upgrade to 1.5.0 yesterday but i just now noticed.

- VSCode Version: 1.5.1
- OS Version: Windows 8.1 x64

Steps to Reproduce: 
1. Update to VSCode 1.5.1 from 1.5.0 (or possibly from 1.4.0 to 1.5.0

![capture](https://cloud.githubusercontent.com/assets/10837869/18392645/2a61c8c0-7678-11e6-8591-877617829c62.PNG)

**Comment by joaomoreno** [comment]
It didn't happen on my machine. Do you still see this after restarting?

**Comment by AlgorithmsAreCool** [comment]
I restarted and I still see "URL:vscode" as the type description for any file extension that vscode was responsible for.

However, upon changing the default program to notepad and then back to vscode. The description changed back to "C# Source File".

This is a pretty harmless issue, and it has a very simple workaround. Should i just close it?

**Comment by thirdwaffle** [comment]
Had the same issue with a bunch of file types:
* *.js
* *.json
* .gitattributes

I agree that it's pretty harmless and easy to workaround, but it would be nice to know what caused it.

**Comment by joaomoreno** [comment]
Not really sure... but seems like a Windows problem.
