### ISSUE TITLE
Command "File: New File", trailing slash. Handle as "File: New Folder"

### ISSUE THREAD

**Issue by JohnGurin** [microsoft/vscode#117848]
https://github.com/microsoft/vscode/blob/413963c489fafa5163b5d6513731c7953de07fb3/src/vs/workbench/contrib/files/browser/fileActions.ts#L853

```javascript
const onSuccess = async (value: string): Promise<void> => {

        // possible patch
        const lastChar = value[value.length - 1];
        if (lastChar === '/' || lastChar === '\\')
                isFolder = true;
         // --------------

        try {
	// ...
```
The reason. Currently, if `File: New File` value is `aa/bb/`, vscode creates `aa` folder anyway but throws an error.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
