### ISSUE TITLE
node use too much cpu

### ISSUE THREAD

**Issue by Pascal66** [microsoft/vscode#117818]
Issue Type: <b>Performance Issue</b>

CPU usage is too high
![image](https://user-images.githubusercontent.com/3041616/109381601-9ea95300-78db-11eb-8f2c-ee7ab4d8b3bc.png)

VS Code version: Code - Insiders 1.54.0-insider (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:10.253Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.82GB free)|
|Process Argv|--crash-reporter-id f3477f81-f5f0-431a-b2c9-d63355346b54|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|31.92GB (12.82GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    81	 15516	code-insiders main
    0	    85	  7292	   shared-process
    0	    63	  1416	     ptyHost
    0	   102	 13076	   gpu-process
    0	   160	 16924	   window (config_allUSDT.json - freqtrade [WSL: Ubuntu-20.04] - Visual Studio Code - Insiders)
    0	    81	 17992	     extensionHost
    0	    62	 21768	       electron_node wslDaemon.js 
    0	     7	 22196	         C:\WINDOWS\System32\wsl.exe -d Ubuntu-20.04 sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" e590188f17162393f50feec19263398e6fe02d13 insider .vscode-server-insiders 5000  --disable-telemetry'
    0	     6	 10256	           C:\WINDOWS\system32\lxss\wslhost.exe {c42f1671-8915-4193-bc65-b78b14efecc6} 504 516 520
    0	    13	 17600	             console-window-host (Windows internal process)
    0	    11	 11544	           console-window-host (Windows internal process)
    0	    40	 19448	   utility
    0	    23	 19472	   crashpad-handler
    0	    82	 22824	   window (Issue Reporter)

Remote: WSL: Ubuntu-20.04
CPU %	Mem MB	   PID	Process
    5	     0	   277	remote agent
    0	     0	   308	   extensionHost
    0	     0	   333	     /home/speedoo/.vscode-server-insiders/bin/e590188f17162393f50feec19263398e6fe02d13/node /home/speedoo/.vscode-server-insiders/bin/e590188f17162393f50feec19263398e6fe02d13/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=308
    0	     0	   875	   /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	   876	     /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: WSL: Ubuntu-20.04|    Folder (freqtrade): more than 24255 files|      File types: py(6996) pyc(6592) pyi(1280) so(320) txt(193) o(153) h(109)
|                  cpp(96) hpp(94) c(69)
|      Conf files: cmake(11) makefile(3) package.json(1);
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.54.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.600686576

</details>

**Comment by deepak1556** [comment]
Can you provide the command line associated with the process by replacing PID below with process pid,

```powershell
Get-WmiObject win32_process -Filter ProcessId=<PID> | Select-Object CommandLine
```

**Comment by Pascal66** [comment]
No commandline displayed on task manager, or with get-wmiobject
```
PS C:\> Get-WmiObject win32_process -Filter ProcessId=9164 | Select-Object CommandLine

CommandLine
-----------



PS C:\>

```

**Comment by bpasero** [comment]
I am not sure what kind of binary we are executing from the `bin` folder in the server? @alexdima any idea?

**Comment by deepak1556** [comment]
Is it possible to get some logs from the server, this most often tends to be case that some native module has a bad CXXABI compatibility.

**Comment by Pascal66** [comment]
@deepak1556 are you asking me some logs ?
Or is it a general question ?

**Comment by deepak1556** [comment]
Sorry it was a general question to @alexdima , I would like to see the logs for any obvious errors before taking a profile of the process.

**Comment by tuminoid** [comment]
After updates to VSCode/extensions today (1.54.1), just enabling WSL extension (all other extensions are disabled) to open Ubuntu 18.04 remote consumes 4-5 full cores thanks to Node, and it will not go away by waiting. htop shows me node command line like [Pascal's](https://github.com/microsoft/vscode/issues/117818#issuecomment-788690456).

Downgrading to 1.53.2 and removing auto-update from settings helped.

**Comment by deepak1556** [comment]
@Pascal66 @tuminoid can you provide the following data,

1) Provide the output of `cat /proc/<PID>/cmdline` run from the wsl shell, where PID is of the process that is showing high cpu usage.
2) Can you attach the logs from `~/.vscode-server-insiders/data/logs/` or `~/.vscode-server/data/logs/` depending on if its insiders or stable

**Comment by Pascal66** [comment]
```
UID        PID  PPID  C STIME TTY          TIME CMD
speedoo    213   212  0 10:12 tty3     00:00:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 42e27fe5cdc58539dad9867970326a297eb8cacf insider .vscode-server-insiders 5000  --disable-telemetry
speedoo    214   213  0 10:12 tty3     00:00:00 sh /mnt/c/Users/Pascal/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.54.0/scripts/wslServer.sh 42e27fe5cdc58539dad9867970326a297eb8cacf insider .vscode-server-insiders 5000 --disable-telemetry
speedoo    240   214  0 10:12 tty3     00:00:00 sh /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/server.sh  --port=0 --use-host-proxy --without-browser-env-var --print-ip-address --enable-remote-auto-shutdown --fileWatcherPolling=5000 --disable-telemetry
speedoo    242   240  1 10:12 tty3     00:00:09 /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/node /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/out/vs/server/main.js  --port=0 --use-host-proxy --without-browser-env-var --print-ip-address --enable-remote-auto-shutdown --fileWatcherPolling=5000 --disable-telemetry
speedoo    273   242  0 10:12 tty3     00:00:01 /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/node /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/out/vs/server/uriTransformer.js --useHostProxy=
speedoo    284   242 99 10:12 tty3     00:37:07 /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/node /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/out/bootstrap-fork --type=watcherService
speedoo    298   273  0 10:12 tty3     00:00:00 /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/node /home/speedoo/.vscode-server-insiders/bin/42e27fe5cdc58539dad9867970326a297eb8cacf/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=273

```

**Comment by tuminoid** [comment]
This was closed as duplicate to Mac/Linux issue, yet we experience this on Windows. #3998 doesn't mention WSL at all, nor Windows. Can you elaborate why you deem this is a duplicate?

**Comment by Pascal66** [comment]
I agree. Reopen.


De : Tuomo Tanskanen
Envoyé le :lundi 8 mars 2021 09:41
À : microsoft/vscode
Cc : Priveyes; Mention
Objet :Re: [microsoft/vscode] node use too much cpu (#117818)

This was closed as duplicate to Mac/Linux issue, yet we experience this on Windows. #3998 doesn't mention WSL at all, nor Windows. Can you elaborate why you deem this is a duplicate?
