### ISSUE TITLE
Terminal Not opening

### ISSUE THREAD

**Issue by puddendoll** [microsoft/vscode#117816]
Issue Type: <b>Bug</b>

Terminal just stopped opening. I have tried to fix but nothing is working

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by markserlin-crucible** [comment]
Same issue
Steps:
Menu->Terminal->New Terminal.
Nothing happens.

Version: 1.56.0-insider (system setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19041
