### ISSUE TITLE
Comment/uncomment characters should honor the current mode of the TextMate grammar.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#117802]
Comment/uncomment key shortcuts (Ctrl+K, C; Ctrk+K, U) should switch based on textmate state and not only the editor language.

Consider the following example:

1. Install the [.NET Interactive extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Ctrl+Shift+P and invoke the command ".NET Interactive: Create new blank notebook".
3. Ignore that notebook; it was necessary to activate the extension.
4. Create a new file.
5. Set the language mode to `C# (.NET Interactive)`.
6. Set the contents to:
  ```
  var x = 1;

  #!pwsh
  $x = 'abcd'
  ```
7. Highlight line 1, Ctrl+K, C.  The line is commented to `// var x = 1;`.
8. Highlight the `$x = 'abcd'` line.
9. Ctrl+K, C.

Expected:
The line should be commented according to PowerShell commenting rules, e.g., `# $x = 'abcd'`

Actual:
The line was commented according to the editor's (C#) rules.

The `#!pwsh` line switches the textmate grammar into `PowerShell (.NET Interactive)` mode and according to its [language configuration](https://github.com/dotnet/interactive/blob/main/src/dotnet-interactive-vscode/syntaxes/powershell.language-configuration.json), should use `#` as the comment character.

**Comment by alexdima** [comment]
@brettfo If a grammar embeds other languages, then this needs to be specified in the `grammar` contribution point in `package.json`:

Here is for example how HTML specifies that certain TM scopes refer to an embedded language: https://github.com/microsoft/vscode/blob/8fd4a68845fb5e3c02989e954b97d6abdc2267e8/extensions/html/package.json#L53-L59

I think perhaps you are not defining that [here](https://github.com/dotnet/interactive/blob/1280decb921ff5cfb05cca8508717a44bded80d8/src/dotnet-interactive-vscode/package.json#L224-L270).
