### ISSUE TITLE
Custom code completion does not show anymore

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#11788]
- VSCode Version: 1.5.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Code your own CompletionItemProvider :-)
2. Try to use it...

It does resolve / return a list of CompletionItems but there are no suggestions displayed to the user.

The following code does not work:
```typescript
export class ResolveCompletionItemProvider implements CompletionItemProvider {

    provideCompletionItems(document: TextDocument, position: Position, token: CancellationToken): CompletionItem[] {
       
        return [new CompletionItem('testlable'), new CompletionItem('test2')];
    }
}
```

If I set a breakpoint to the return statement, it is hit, but the suggestions are never shown.

Am I doing something wrong?

Cheers
Chris

**Comment by ramya-rao-a** [comment]
@buehler You say "completion does not show anymore". Is this a regression for you? i.e was this working in 1.4.0 and stopped after updating to 1.5/1.5.1 ?

**Comment by buehler** [comment]
@ramya-rao-a Yea... before 1.5.1 (or 1.5) it worked like a charm. I did not use it in my code, because the "multiple edits" were not supported. But now that those are implemented (https://github.com/Microsoft/vscode/issues/6874) I did plan to use my code completion provider.

Problem is, that the breakpoint is hit on the return statement, but afterwards, no suggestions are shown. If I explicitly force completion to show (with the keybinding) it just says "no suggestions".

**Comment by buehler** [comment]
To clarify (and for more information):
I register the provider as such: https://github.com/buehler/typescript-hero/blob/feature/code-completion-provider/src/extensions/ResolveExtension.ts#L97

And use it like this: https://github.com/buehler/typescript-hero/blob/feature/code-completion-provider/src/provider/ResolveCompletionItemProvider.ts

The problem with that is, after the breakpoint is hit and "normally" ran through, the result looks like this:

![No suggestions](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/z19b6gqx.png)

**Comment by jrieken** [comment]
Your completions are being filtered because `MyC` doesn't match `test2` nor `testable`. If you actually want to *complete* `MyC` with `test2` you can control that by using the `TextEdit` and `filterText` of the completion item - that defines what portion is being overridden and what text is used to filter.

**Comment by buehler** [comment]
@jrieken Many thanks... 😱  It's kinda obvious...
