### ISSUE TITLE
Using up or down key can not navigate into filtering highlight files on explorer

### ISSUE THREAD

**Issue by yibhou** [microsoft/vscode#117824]
Issue Type: <b>Bug</b>
the setting is `workbench.list.keyboardNavigation: highlight`. When I filter out some highlight file on explorer, then I press a up or down key, but it can't navigate to highlights elements. This bug only appear in the vscode. Insiders version works well.

**Reproduce:**

<img width="350px" src="https://user-images.githubusercontent.com/10102594/109387917-ef05cc80-793e-11eb-8589-9ee2cba6b329.gif"/>

---
**Expect:**

<img width="350px" src="https://user-images.githubusercontent.com/10102594/109388076-cf22d880-793f-11eb-93d4-64646beb346a.gif"/>

Does this issue occur when all extensions are disabled?: **Yes**

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 5|
|Memory (System)|16.00GB (4.88GB free)|
|Process Argv|--crash-reporter-id a16de3c2-fc44-4f08-85d9-7a1d0e7afa00|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30262999

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate and fixed in 1.54 which is due out very soon.
