### ISSUE TITLE
VsCode Terminal alters color palette over SSH

### ISSUE THREAD

**Issue by mikeev261** [microsoft/vscode#117895]
- VS Code Version:1.53.2
- OS Version: Win10x64 10.0.19042

For some reason, VsCode's terminal changes the colors of the terminal. I have the same settings for both the client and server side (both Win10). If I reverse the direction I see the same thing (swap which machine is server vs. client).  

I'm using powershell core 7 with oh-my-posh extension, though this extension does not seem to be the cause. 

Steps to Reproduce:

1. Observe VsCode terminal colors (these are correct/expected). 
![image](https://user-images.githubusercontent.com/4935661/109515278-e9aa9e00-7a74-11eb-8013-5c3b49713425.png)

2. Observe how VsCode terminal colors change over SSH (these are incorrect)
![image](https://user-images.githubusercontent.com/4935661/109515228-db5c8200-7a74-11eb-8f9a-3bb98c7a2c03.png)

Does this issue occur when all extensions are disabled?: Yes

I do not see this problem if I use Windows Terminal, Pwsh7, and SSH. Only VsCode's terminal seems to have this problem. 

Any ideas?

**Comment by Tyriar** [comment]
Does this happen when you ssh into the same machine with Windows Terminal?

**Comment by Tyriar** [comment]
Can you try enabling the dom renderer in settings (`"terminal.integrated.rendererType": "dom"`) and then inspect the good cells and bad cells in devtools and paste in screenshots? I'm interested in the color class of each cell.

**Comment by mikeev261** [comment]
Apologies for the late reply on this @Tyriar - been swamped with work. I tried adding "terminal.integrated.rendererType": "dom" to my settings.json on the client side, but didn't observe any difference. I'm not sure what you mean about "good cells and bad cells in devtools" though. Can you provide some more info? And then I'll try to get those screenshots. 

FWIW, there is a similar thing going on in Windows Terminal with VIM. The colors are unaltered, but as soon as you launch VIM and restart the colors go all wrong. VScode + SSH, by comparison, just seems to do it all the time. So there seems to be some common code between how these two products render colors that goes off into the weeds in these situations. 

More info with the developer of the oh-my-posh extension: https://github.com/JanDeDobbeleer/oh-my-posh/discussions/472#discussioncomment-418219
