### ISSUE TITLE
Localhost

### ISSUE THREAD

**Issue by Asmarafique** [microsoft/vscode#117886]
Issue Type: <b>Bug</b>

My localhost isn't connecting and i don't know how to fix it. I think i have some problem in json file please check it as i wanted to create a website 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz (4 x 2660)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.86GB (1.00GB free)|
|Process Argv|--crash-reporter-id 05e080db-a99b-4c83-bd6d-bf171ee274b8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.12
live-sass|rit|3.0.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30264244
pythontbcf:30260844

```

</details>

**Comment by roblourens** [comment]
Sorry, I need more info, but this doesn't sound like an issue with vscode. Sounds like this might involve an extension or your own development environment.
