### ISSUE TITLE
Real-time code linting feedback not working properly for C++ code.

### ISSUE THREAD

**Issue by hssaluja25** [microsoft/vscode#117854]
- VS Code Version: 1.53.2
- OS Version:  Windows_NT x64 10.0.18363
- Does this issue occur when all extensions (except C/C++) are disabled?: Yes

When working on C++  files, the red squiggly lines are not highlighting syntax errors I make in my code. However, syntax errors I make in the preprocessor directive are being highlighted.  

![Bug(New)](https://user-images.githubusercontent.com/75522742/109701607-34cdc980-7bb9-11eb-91b5-7033160eaf3f.jpg)
![bug](https://user-images.githubusercontent.com/75522742/109425811-4627a200-7a10-11eb-9358-ef1473effbde.jpg)

### What I have tried?
Someone at StackOverflow wrote that I should delete my settings. I did that but still, the issue persists.
I also tried reinstalling the C/C++ Extension by Microsoft. (I uninstalled the C/C++ extension, restarted VSCode and installed the extension again.)

**Comment by alexr00** [comment]
Looks like this is caused by the C/C++ extension you are using. Please file an issue with that extension!
