### ISSUE TITLE
debugging bluebird promises

### ISSUE THREAD

**Issue by foobar8675** [Microsoft/vscode#1178]
Can vscode debug node code allowing one to step through promises without setting breakpoints? This is similar to clicking "Async" in the chome debug tools as described in this question.

http://stackoverflow.com/questions/32767721/how-to-step-through-debugger-with-promises

**Comment by egamma** [comment]
This is currently not supported. @weinand fyi

**Comment by weinand** [comment]
This is now possible (it might help to enable the "smartStep" feature).
