### ISSUE TITLE
Have a setting to control custom hover delay in trees

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#117894]
Over in https://github.com/microsoft/vscode-docker/issues/2677 there's a request to make the delay on markdown tree hovers configurable. Given that we expect extension authors to put lots of good info in markdown hovers it makes sense that these large hovers would obscure tree items if the delay is too short.

The current delay is hard-coded to closely match the OS defaults (about 1500ms on mac, about 500ms on Windows and linux).

We could make a setting similar to `editor.hover.delay` (eg. `workbench.hover.delay`). Then use that anywhere the custom hover is used.

**Comment by alexr00** [comment]
@bpasero, this could impact all icon label hovers so I'd like to get your feedback.

@Tyriar, you were exploring ways to keep the hover from getting in the way, so your feedback would be great too.

**Comment by bwateratmsft** [comment]
I like it! Bonus cool points if it's controllable on a per-extension basis, or even if it can somehow be part of the return signature from `resolveTreeItem`. I have no idea if that's actually possible, just spitballing.

**Comment by bpasero** [comment]
No objections from me, we already have `editor.hover.delay` btw. I think the default should match operating system defaults as close as possible even once we have that setting.

**Comment by alexr00** [comment]
> Bonus cool points if it's controllable on a per-extension basis, or even if it can somehow be part of the return signature from resolveTreeItem. I have no idea if that's actually possible, just spitballing.

I'm not a huge fan of making this extension specific. They "why" of it will be difficult to explain to users and will result in inconsistency between different views.

**Comment by Tyriar** [comment]
Sounds good to me

**Comment by alexr00** [comment]
I added the setting and adopted in custom trees/icon labels that use the custom hover. I'm not sure which setting makes more sense for the terminal hover.

**Comment by Tyriar** [comment]
@alexr00 I think we should use this setting everywhere, can you move it into the base hover component so it overrides the terminal ones too?

**Comment by Tyriar** [comment]
Nevermind, this should live within the terminal since the components manage the delay https://github.com/microsoft/vscode/issues/119329
