### ISSUE TITLE
Notebook output elements should be able to honor `prefers-color-scheme`

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#117804]
Notebook output elements are commonly HTML/CSS/JS and should be able to listen to the VS Code host theme and the CSS `prefers-color-scheme` media query.

E.g.,
1. Install the .NET Interactive extension.
2. Ctrl+Shift+P, ".NET Interactive: Create new blank notebook".
3. Change the first cell's language to "HTML (.NET Interactive)".
4. Set the contents to this:

  ``` html
  <style>
  @media (prefers-color-scheme: dark) {
      .mydiv {
          background: #FF0000;
      }
  }

  @media (prefers-color-scheme: light) {
      .mydiv {
          background: #00FF00;
      }
  }
  </style>

  <div>This is regular HTML</div>
  <div class='mydiv'>This is theme-aware HTML</div>
  ```
5. Execute that cell.

RESULT:
The output cell always applies the dark theme, e.g., a red background, regardless of the theme set in the parent VS Code.

EXPECTED:
Switching the host VS Code between light and dark themes should also trigger the appropriate change in the notebook output webview so the theme information can be honored.

From a dark theme:
![image](https://user-images.githubusercontent.com/926281/109363474-85ec5f00-7841-11eb-90c0-242b6de2f013.png)

From a light theme:
![image](https://user-images.githubusercontent.com/926281/109363431-681efa00-7841-11eb-83b1-9bd24c780866.png)

**Comment by rebornix** [comment]
@mjbvz any idea what extra we need to do to support `prefers-color-scheme ` in the notebook webview?

**Comment by mjbvz** [comment]
Webviews add a class based on the current color theme style: https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content

 `prefers-color-scheme` is controlled by the user's browser,  so we cannot make it match VS Code's color theme. You can use these css classes instead
