### ISSUE TITLE
Add option 'Keep output on terminal after run test'

### ISSUE THREAD

**Issue by IN00** [microsoft/vscode#117828]
Unfortunately open new session after each run test.

There have been times when I wanted to check the output of the first test I ran, when the first test I ran failed, and then after I fixed it, the test failed with a different exception.

I would love to see this option added.

My environment
- Mac OS
- zsh: 5.7.1
- VSCode: 1.53.2
- Always use RSpec in vscode-test

**Comment by connor4312** [comment]
I think this is more a request to keep the debug console contents around, @isidorn.

However this will also be solved by the work on [testing](https://github.com/microsoft/vscode/issues/107467), so I leave it up to you whether you think it's worth solving this issue.

**Comment by isidorn** [comment]
This is a fair request, however for now I would not do anything here.
If the work on testing solves this nicely in the future then as you say we would not need anything here.

So for now assigning to backlog with no plan of change.
