### ISSUE TITLE
Run/debugger not shown as on video

### ISSUE THREAD

**Issue by ehackett00** [microsoft/vscode#117843]
Issue Type: <b>Bug</b>

1 Launch VS Code
2 select a js file to run/debug
3 Select the debugger tab
==> The Run/Debugger buttons are not visible as in YouTube videos.  I just see "R..."

Screen shot
Screen Shot 2021-02-27 at 9.26.41 PM.png

I'm new to Java Script and have not coded anything since the 90's
I need help

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|--crash-reporter-id dd9896a9-49e2-4a58-b174-1bb0739bccfa|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.158.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30264245

```

</details>

**Comment by gjsjohnmurray** [comment]
Please paste your screenshot here. With most browsers you should be able to drag-drop a file onto the comment field.

**Comment by ehackett00** [comment]
Ok, I pasted it to the email before e but I guest the field is just text.  I am just trying to find an environment that lets me run Java Script..  I am doing this to work with Adobe Acrobat.  I also know C, C++ , and a few Scripting languages and shell scripts.

VS  Code seems like the perfect browser plus!

Ed

**Comment by weinand** [comment]
@ehackett00 instead of pasting the **name** of your screenshot ("Screen Shot 2021-02-27 at 9.26.41 PM.png") into the comments fields here on github, please paste the image file from the macOS Finder into the comment. The file will be automatically uploaded to github and a link is added in the comment.

**Comment by ehackett00** [comment]
Hello,

In the screen shot I saw an “R…”.  What is that?

Ed

**Comment by weinand** [comment]
@ehackett00 if there is not enough space to show a name, then the name is shortened and an ellipsis ("...") is appended. 
Typically this means that you'll have to make some view or panel larger in order to show the full name.

Since you cannot provide a screenshot, it is difficult for me to guess what you are seeing.

**Comment by ehackett00** [comment]
Hello,

Here is the screen shot for the third time!










Ed

**Comment by weinand** [comment]
Sorry, but there is no screenshot. May I suggest that you do not try continue the discussion by mail (which does not seem to handle your screenshots correctly), but open the issue in a browser and drag&drop an image into the comment text box.

**Comment by weinand** [comment]
You said:
> I am just trying to find an environment that lets me run Java Script..  I am doing this to work with Adobe Acrobat.

I'm not sure whether VS Code is a good fit for developing JavaScript for Adobe Acrobat.
I could not find a VS Code extension for JavaScript and Adobe Acrobat, which means that you would have to use the standard JavaScript support of VS Code which targets either Node.js or web browsers. So specific Adobe Acrobat functionality would not be available from within VS Code.

Is "JavaScript for Adobe Acrobat" still being used? 
Related information like https://acrobatusers.com/tutorials/javascript_console/ appears to be rather old...
