### ISSUE TITLE
VS Code lags after running for ~30 minutes

### ISSUE THREAD

**Issue by lilspelunker** [microsoft/vscode#117827]
- VS Code Version: 1.53.2 x64
- OS Version: Linux Mint (Cinnamon, 20.1)

Steps to Reproduce:

1. Launch VS Code. From my testing so far, it has happened to me on any kind of project. The last time it happened to me was in an expressjs project (using express and mongoose, only has 3-4 files and the node_modules folder)
2. Wait about 30 minutes, lag increases over time. For my case, it went from no typing delay and instant autocompletion to a lot of delay and 4-5 seconds for autocomplete.

Does this issue occur when all extensions are disabled?: Yes

**Comment by djmisterjon** [comment]
some app process in your environment can affect vscode and chromium !
proof here.
https://github.com/microsoft/vscode/issues/113553
So look in your OS process and try kill some background process and restart vscode.
you can also try `--disable-renderer-accessibility` but this is not a solution !
i know one so far, never open the Microsoft virtual keyboard app in you window session.
Vscode will lags until your restart your pc or logout.

**Comment by lilspelunker** [comment]
It might be Insomnia that is causing the lag, will see if I'm correct

**Comment by lilspelunker** [comment]
Idk if Insomnia changes anything but closing Discord seems to have fixed it. Interestingly, Discord doesn't cause lag on Windows. Closing the issue as I found the problem.

**Comment by djmisterjon** [comment]
look for disable overlay, discord have option for vscode.
![image](https://user-images.githubusercontent.com/24865815/109416066-0b7b2680-798a-11eb-943d-6650fec2cad8.png)

**Comment by lilspelunker** [comment]
The lag came back, this time the only thing open is Chrome

**Comment by djmisterjon** [comment]
try `--disable-renderer-accessibility` 

and check if the arg are apply by this command
`wmic process where caption="code.exe" get commandline`

i cant really help more, wait for a pro vscode :)

**Comment by lilspelunker** [comment]
Gonna try that `--disable-renderer-accessibility` option

**Comment by lilspelunker** [comment]
I get this warning:
```
Warning: 'disable-renderer-accessibility' is not in the list of known options, but still passed to Electron/Chromium.
```

**Comment by lilspelunker** [comment]
It doesn't seem to change anything, the lag started after 2 minutes

**Comment by djmisterjon** [comment]
> I get this warning:
> 
> ```
> Warning: 'disable-renderer-accessibility' is not in the list of known options, but still passed to Electron/Chromium.
> ```

yes is a valide chromium arg and should work
https://peter.sh/experiments/chromium-command-line-switches/

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information. Test using VS Code insiders and share the output of `code-insiders --status` when the problem happens

**Comment by lilspelunker** [comment]
Hey, sorry for the late response. Here's the output of the command:
```
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Version:          Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS Version:       Linux x64 5.4.0-58-generic
CPUs:             AMD A8-7410 APU with AMD Radeon R5 Graphics (4 x 2195)
Memory (System):  5.64GB (2.28GB free)
Load (avg):       7, 3, 1
VM:               100%
Screen Reader:    no
Process Argv:     --no-sandbox --crash-reporter-id e363e6c7-2c12-4ddb-9d1d-5fc9016806c5
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          disabled_off
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              disabled_software
                  skia_renderer:              enabled_on
                  video_decode:               disabled_software
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %	Mem MB	   PID	Process
    0	   133	  2323	code main
    0	    40	  2343	   zygote
    0	    92	  2379	     gpu-process
    0	    40	  2344	   zygote
    0	    58	  2382	   utility
    0	   237	  2392	   window (● console.log • Untitled-1 - Visual Studio Code)
    0	   133	  2437	     extensionHost
    0	   116	  2467	       electron_node tsserver.js 
    0	   121	  2468	       electron_node tsserver.js 
    0	    81	  2501	         electron_node typingsInstaller.js typesMap.js 
    0	   116	  2418	   shared-process
```

**Comment by mjbvz** [comment]
@deepak1556 Assigning you based on #107016. The user originally mentioned express, but I don't think this is TypeScript related

**Comment by deepak1556** [comment]
Can you check if the problem persists when launching with `code --disable-gpu`

**Comment by lilspelunker** [comment]
yes, it still seems to lag

**Comment by lilspelunker** [comment]
I haven't changed anything or install/uninstall anything but just opening VS Code today the issue seems to have disappeared.
