### ISSUE TITLE
Choosing between color themes disables auto sync feature

### ISSUE THREAD

**Issue by AsishKakumanu** [microsoft/vscode#117814]
Issue Type: <b>Bug</b>

Changing color themes in quick succession. Open color themes and have multiple themes installed. hold down up/down arrow which keeps changing color themes. 

Doing the above disables the auto sync. 
"Turned off sync because of making too many requests to server"
(Hope this can be solved by posting a request  to the server only after we set a color theme , not while choosing one)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 8908ec3a-ace9-49f6-8594-08ff92df9c28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (91)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
msg|ajs|0.1.1
ros|ajs|0.3.1
Bookmarks|ale|13.0.2
arepl|alm|2.0.1
ng-template|Ang|11.2.3
vscode-color|ans|0.4.5
teacode-vsc-helper|App|1.2.2
atlascode|atl|2.8.5
vscode-django|bat|1.3.0
vscode-custom-css|be5|4.0.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
python-snippets|cst|0.2.0
vscode-eslint|dba|2.1.14
vscode-dash|dee|2.4.0
devdocs|dei|0.2.0
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.0
viml|dun|0.1.7
vscode-npm-script|eg2|0.3.16
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.2
go|gol|0.22.1
vscode-test-explorer|hbe|2.19.5
angular2-switcher|inf|0.3.3
vscode-cdnjs|Jak|0.19.0
svg|joc|1.4.5
Angular2|joh|11.0.0
chat|kar|0.35.0
wrapSelection|kon|0.10.0
vscode-leetcode|Lee|0.17.0
vscode-fix-checksums|leh|1.1.0
vscode-python-test-adapter|lit|0.6.6
autodocblocker|mad|1.0.2
MagicPython|mag|1.1.0
fluent-icons|mig|0.0.6
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.2.4
jupyter|ms-|2021.2.603412351
vscode-ai-remote|ms-|0.1.0
azure-account|ms-|0.9.6
cpptools|ms-|1.2.2
node-debug2|ms-|1.42.5
powershell|ms-|2021.2.2
references-view|ms-|0.0.77
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
angular2-inline|nat|0.0.17
autodocstring|njp|0.5.4
angular-console|nrw|17.0.0
vetur|oct|0.32.0
ros-snippets|pij|0.3.1
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.1.0
java|red|0.75.0
vscode-yaml|red|0.15.0
LiveServer|rit|5.6.1
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.4.1
vscode-spotify|shy|3.2.1
autoimport|ste|1.5.3
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.11
vscode-arduino|vsc|0.3.5
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
quokka-vscode|Wal|1.0.343
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
glean|wix|5.1.1
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
vscode-surround|yat|1.0.2
material-theme|zhu|3.9.15
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30264244

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

See #91286

@sandy081 that issue has been open for a year now. Hoping it will be fixed soon...

**Comment by sandy081** [comment]
@gjsjohnmurray Yes, it is in my radar. I see the importance of it given that many users are hitting this. Thanks for rising this.
