### ISSUE TITLE
Shift key gets stuck on touch keyboard

### ISSUE THREAD

**Issue by vamsi-kleargroup** [microsoft/vscode#117885]
Issue Type: <b>Bug</b>

Steps to reproduce are only for touch screen laptop. This issue happens only with touch screen keyboard in touch screen laptop.

1: Start writing a progam. Eventually you'll end up requiring to use the 'Shift' key.
2: Now switch to another application like chrome by clicking on the app icon in the taskbar. This happens sometimes without switching apps also.
3: You may notice if you type in search bar, all input will be capitalized as if 'Shift' was held down. Clicking on any other application opens up a new window.

PS: My hotkeys are turned off.

I have to restart my PC everytime  this happens. And it happens quite frequently (every 15 mins).
I have a major disability and use a [mouthstick](https://www.google.com/search?q=mouth+stick+stylus&safe=off&rlz=1C1CHBF_enIN914IN914&sxsrf=ALeKk005A0jE1dKxSj5R64Kz1d-3lQvYdw:1614599351093&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjZzpqmg4_vAhXJc30KHaqaCOoQ_AUoAnoECAIQBA&biw=1094&bih=446&dpr=1.25#imgrc=TZ-xVXugO6O9yM) to use my laptop and work as a full stack engineer. This issue has been quite disturbing for past 1-2 months. I really would appreciate and mean a lot if someone suggest a solution. VsCode is the only thing that allowed me to do programming as it supported most of my accessibility isssues like touch navigation and with some workarounds allows me to do my job. 

Thanks in advance

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7130U CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.68GB free)|
|Process Argv|--crash-reporter-id 849cba87-969b-47aa-98b3-13172363d4db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
copy-relative-path|ale|0.0.2
expressjs|ama|2.0.0
dart-data-class-generator|Ben|0.4.4
dart-code|Dar|3.19.2
flutter|Dar|3.19.0
gitlens|eam|11.2.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
bloc|Fel|5.5.0
todo-tree|Gru|0.0.199
rest-client|hum|0.24.4
customize-ui|ioc|0.1.51
monkey-patch|ioc|0.1.12
pubspec-assist|jer|2.2.1
Kotlin|mat|1.7.1
vscode-docker|ms-|1.10.0
remote-wsl|ms-|0.53.4
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
awesome-flutter-snippets|Nas|2.0.4
material-icon-theme|PKi|4.5.0
java|red|0.75.0
LiveServer|rit|5.6.1
mongo-snippets-for-node-js|roe|1.3.5
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.11
expresssnippet|vla|0.2.4
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.0
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
dart-built-value-snippets|yon|1.1.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30260843

```

</details>

**Comment by isidorn** [comment]
@vamsi-kleargroup thanks for filling this issue. However VS Code does not do anything special here.
And this sounds like an Electron problem, thus also assigning to @deepak1556 
@deepak1556 are there similar issues maybe that you are aware of?

**Comment by deepak1556** [comment]
Not aware of a similar bug, will have to check this issue with electron fiddle as next step.

**Comment by isidorn** [comment]
I can not reproduce this with an ipad. Closing this for now as other users did not complain.
If more people see this please let me know and I can reopen
