### ISSUE TITLE
Workbench: Grid (2x2) mode should be enabled by manually splitting into that shape

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117866]
![Screen Recording 2021-02-28 at 8 45 10 PM](https://user-images.githubusercontent.com/35271042/109453190-4458e100-7a06-11eb-83fa-b576bd0e9e7f.gif)

Looks like when having a grid that is centered, I am unable to resize all 4 editors at the same time

**Comment by joaomoreno** [comment]
The 2x2 mode can only be enabled by running the `View: Editor Grid Layout (2x2)` or in `View > Editor Layout > Grid (2x2)`. That mode will stay until editor groups are added or removed.

You can't get into that mode by doing the splits yourself and accurately aligning the sashes.

**Comment by misolori** [comment]
Hmm...I'd imagine that creating the grid via the command is less common the manually splitting and just assumed this would work. Hoping we can do some magic someday and it just works.

**Comment by joaomoreno** [comment]
On second thought, I think you're right: it would be cool if this would just work.

**Comment by joaomoreno** [comment]
Easier than expected!

**Comment by joaomoreno** [comment]
Verification:

1. Open a new window
2. Open a file
3. Split horizontally
4. Split each view vertically, now you should have a 2x2 grid
5. Resize the vertical sash, all views should resize
6. Resize the horizontal sash, all views should resize
