### ISSUE TITLE
Easier way to hide files and folders from explorer

### ISSUE THREAD

**Issue by Dania99dev** [microsoft/vscode#117845]
As of now we can hide files and folders by editing files.exclude
But it would be very nice if we could right click and hide that file/folder from menu when things get very messy

**Comment by usernamehw** [comment]
I think there was a feature request that didn't get enough upvotes. There are some extensions that can help, though:

https://marketplace.visualstudio.com/items?itemName=RedVanWorkshop.explorer-exclude-vscode-extension

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by Milo123459** [comment]
+1, this would be very helpful for some other feature requests as well
