### ISSUE TITLE
Mouse Wheel Scroll Sensitivity invalid in built-in jupyter

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#117803]
@Force1ess commented on [Thu Feb 25 2021](https://github.com/microsoft/vscode-jupyter/issues/4964)

## Environment data
版本: 1.53.0-insider
提交: 8490d3dde47c57ba65ec40dd192d014fd2113496
日期: 2021-02-03T15:54:10.467Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.9.0-050900-generic
Jupyter extension:2021.2.576440691
Python:2021.3.600986985-dev
## Expected behaviour
My setting can nomarlly apply to my texteditor
## Actual behaviour
It doens't work
## Steps to reproduce:

1. XXX

## Details
<p>
By the way ,I used imwhell to control scroll speed. 
<p>
<p>
And I don't know if it's imwheel's problem, here's my imwheel setting
<p>
<img src="https://user-images.githubusercontent.com/72636351/109264448-f7c3a900-783f-11eb-9b38-9b7574fc7092.png">

**Comment by Force1ess** [comment]
Thank you very much for your reply : )
Any information @me if you need

**Comment by rebornix** [comment]
You can now use `workbench.list.mouseWheelScrollSensitivity` to change the scrolling sensitivity in the notebook editor.
