### ISSUE TITLE
Showing more inline hints like in IntellijIDEA

### ISSUE THREAD

**Issue by NaveenGali11** [microsoft/vscode#117882]
Recently i have moved to vscode editor from Intellij idea for its smooth and excellent speed and i think one feature that is lacking in vscode is showing more inline hints like in intelliidea.Here in vscode we are getting only 4 or 5 inline hints but i think it will be excellent if we have more inline hints showing as popup.
If this is already avaliable or a setting is needed just ignore it and please let me know how can i use it.

**Comment by rzhao271** [comment]
By inline hints, do you mean when debugging, or do you mean just in general?
Try searching in the setting to enable codelens. If you want git-related hints like per-line blame, there's also gitlens.
