### ISSUE TITLE
audio volume change

### ISSUE THREAD

**Issue by loveisglitchy** [microsoft/vscode#117850]
Issue Type: <b>Bug</b>

Open any app that outputs music.
Start the music.
Open visual studio code, or if already open, simply click inside the editor.

Expected results: able to hear music

Actual results: volume gets reduces by at least 50%

I have attempted to change all my system settings and had no result change.

Apps I've tested this with are as follows: 
Microsoft Edge (youtube.com) - every video
Spotify
Discord (with a music bot)
Google Chrome (youtube.com)
Pandora
Netflix
Grand Theft Auto

On vscode leave (close window or just click out of it):
volume gets set back to user desired.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 4050)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.05GB free)|
|Process Argv|--crash-reporter-id 2e2c8d01-41d9-4227-9450-b4e8923fb673|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: digitalocean-host|
|OS|Linux x64 5.4.0-65-generic|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (4 x 2294)|
|Memory (System)|7.78GB (5.44GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
discord-vscode|icr|5.4.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30260844

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by loveisglitchy** [comment]
Thanks for getting back so quickly, I actually resolved it quickly by just uninstalling and reinstalling the latest version available online. It's working as intended now.
