### ISSUE TITLE
Seti File Icon Theme: Show custom icon for files with no file extension in the file name

### ISSUE THREAD

**Issue by winuxue** [Microsoft/vscode#11787]
The icons for this filename (without extensions) are not working
- TODO
- LICENCE 
- Procfile

**Comment by ramya-rao-a** [comment]
@winuxue When you say "without extensions" do you mean "without any vscode extensions" or "the files do not have extensions like .md, .txt" ?

**Comment by winuxue** [comment]
I mean files with name but no extension.
I'm getting the same than you, the same icon than .txt file.
But it is supposed to show the custom icon for this kind of files, no the txt one.

**Comment by ramya-rao-a** [comment]
Can you share a screenshot of the custom icon that you expect?

**Comment by winuxue** [comment]
The ones of this picture:
https://github.com/jesseweed/seti-ui/raw/master/screenshot-icons.png

**Comment by aeschli** [comment]
They seem to work for me:
![image](https://cloud.githubusercontent.com/assets/6461412/18500899/69078ace-7a4c-11e6-9b1e-5d230f8b2e29.png)

**Comment by winuxue** [comment]
![issue](https://cloud.githubusercontent.com/assets/15930014/18618810/bb02f376-7db3-11e6-862f-43e85b6f216a.PNG)

Not for me.
Testing from Ubuntu.

**Comment by aeschli** [comment]
Can you try the insiders build? (https://code.visualstudio.com/insiders)?
