### ISSUE TITLE
Extension host uses 100% CPU, with all extensions disabled

### ISSUE THREAD

**Issue by entrope** [microsoft/vscode#117811]
- VS Code Version: 1.53.2
- OS Version: CentOS 7.9.2009

Steps to Reproduce:

1. Start Visual Studio Code, loading a folder with C++ source file.

Does this issue occur when all extensions are disabled?: Yes

Running Visual Studio Code on a CentOS 7.9 system with a number of security controls enabled, the extension host process consistently uses 100% CPU.  If I use the "Developer: Show Running Extensions" command to open a window and record a profile, the resulting profile -- whether I use "code --disable-extensions" or just manually disable all the extensions -- shows:

 * runMicrotasks getting about 75% "Self Time", and 98% "Total Time", called from(?) processTicksAndRejections().  If I click the arrow next to "runMicrotasks", it expands to show a line with processTicksAndRejections.
 * flush getting about 18% "Self Time", and the same "Total Time", called from (anonymous) and then (runMicrotasks).
 * (anonymous) getting about 6% "Self Time" and 24% "Total Time", called from runMicrotasks.

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/116359#issuecomment-776930569

Caused by 1.53 adopting Electron 11 which doesn't support CentOS 7
