### ISSUE TITLE
Cannot install/update VSCode to 9/8/2016 version

### ISSUE THREAD

**Issue by rgmembreno** [Microsoft/vscode#11783]
- VSCode Version: Latest
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Run VSCode Installer
2. The following window pops up saying the installation failed, and fails even after 3 retries.

I got a similar error when updating to the latest version of VSCode and opened issue 11717 because VSCode would not start after the auto-update failed.  I grabbed the latest stable release installer yesterday and got this error.

![vscodeinstallerror](https://cloud.githubusercontent.com/assets/11397903/18393641/1142989a-766b-11e6-9bbf-a663905b61f9.png)

**Comment by joaomoreno** [comment]
Can you restart your machine and reinstall? This is due to an old issue. Sorry for that...

**Comment by rgmembreno** [comment]
Thanks @joaomoreno that worked!  I also saw a bunch of Code processes were running after startup, so I had to kill them first and then the re-install worked fine!
