### ISSUE TITLE
code auto completion

### ISSUE THREAD

**Issue by dhruv31** [Microsoft/vscode#11786]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. code auto completion must be there
2. a run button for java code should be there

**Comment by ramya-rao-a** [comment]
@dhruv31 In which language are you developing your code?

From VS Code Docs

> It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (such as C++, C#, Python, PHP) and runtimes

If you are working in Java, then look for extensions for Java in the (marketplace)[marketplace.visualstudio.com/vscode]
