### ISSUE TITLE
export as namespace not presenting correctly within intellisense hover tooltip

### ISSUE THREAD

**Issue by thegaryroberts** [microsoft/vscode#117831]
- VS Code Version: 1.53.2
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. Create a namespace using traditional Typescript namespace syntax and check the intellisense hover tooltip, namespace is identified.

2. Create a namespace using ES module "export as namespace" and check the intellisense hover tooltip, namespace is not shown.

![namespace differences](https://user-images.githubusercontent.com/12859748/109397471-a34b2700-792e-11eb-8bb0-d0c093ea403b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
`namespace` is TS specific construct which are separate from ES modules and export objects.

**Comment by thegaryroberts** [comment]
While this documentation does not mention namespaces in the content at all, the final compatibility table refers to this syntax as: "export * as namespace"
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

So I think this is ES terminology. Does all javascript intellisense tooltip content come from TS repo? I'll raise the issue there if that is the case. Thanks.

**Comment by mjbvz** [comment]
The `namespace` keyword means something specific in TS. I think it would be confusing to start using it for es module namespaces as well

**Comment by thegaryroberts** [comment]
Maybe I could've worded this better. I just wanted the things before the dot to be shown in the tooltip when using this type of export. It would be helpful.
