### ISSUE TITLE
Variable shows as unread, even though its value is read

### ISSUE THREAD

**Issue by minceontoast** [microsoft/vscode#117872]
- VS Code Version: 1.53.2
- OS Version: macOS Catalina v10.15.7

Steps to Reproduce:

1. Paste the following code in a file set to LanguageMode: JavaScript:
```
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const json = require('../data/data.json');
```
2. Either immediately, or after a few seconds, the variable `require` will display greyed out. Hovering over it, it will say: `'require' is declared but its value is never read.`
3. It also seems to fluctuate between read and unread, and I haven't been able to discern what causes it to change.

Of note is that ESLint does **not** complain when the value is greyed out in the editor.

Does this issue occur when all extensions are disabled?: Yes

**Comment by minceontoast** [comment]
Below is another example I've come across, and again it appears to sometimes change to read if I save the file, before changing back to unread if I make any change such as add a space somewhere. The change can be completely unrelated to the variable in question.

<img width="701" alt="erroneous_unread_variable" src="https://user-images.githubusercontent.com/38411730/109488545-94a96f00-7aea-11eb-9e9d-256a201321ca.png">

**Comment by mjbvz** [comment]
This does not happen for me in a new js file using VS Code insiders:

![Screen Shot 2021-03-01 at 1 21 29 PM](https://user-images.githubusercontent.com/12821956/109560719-12409100-7a91-11eb-953c-7c228bb38c36.png)

Can you share a small example project that demonstrates this

**Comment by minceontoast** [comment]
I'm not sure if an example project would be of much use, since what you've done above is all that should be needed to reproduce it. If somebody could test it using the version of VS Code I mentioned, that could prove useful in determining if a particular build is the cause.

I've tested this at my end using the latest Insiders release, and it also works correctly for me:
<img width="385" alt="insiders_variable_showing_read" src="https://user-images.githubusercontent.com/38411730/109563423-9ef85700-7b44-11eb-8643-b6ddb0776beb.png">

**Comment by mjbvz** [comment]
Ah if it works in insiders, then I'm going to close this. The current insiders is 1.54, which should be come the next sable build sometime this week
