### ISSUE TITLE
Search view incorrectly complains about regex escaping

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117878]
I am trying to search for this regex: `\!\..+\(`

And I get:

![image](https://user-images.githubusercontent.com/900690/109480324-ad2e7080-7a7b-11eb-88fa-682390780828.png)

**Comment by thebinarysearchtree** [comment]
Ummm, ! does not need escaping. It should be !\..+\(

JavaScript only complains when you add the unicode flag, which I am assuming is what vscode is doing.

**Comment by bpasero** [comment]
Oh yeah thanks for noting. I made this issue because I saw other online regex sites not complain about this use of replacing so maybe they are more tolerant.

**Comment by bpasero** [comment]
From regexr.com

![image](https://user-images.githubusercontent.com/900690/109503119-263cc080-7a9a-11eb-8979-abc927692a5c.png)

![image](https://user-images.githubusercontent.com/900690/109503135-2b017480-7a9a-11eb-8077-fdea4a6edf5f.png)

**Comment by thebinarysearchtree** [comment]
Yeah, but I am assuming vscode adds the 'u' flag:

`new RegExp(`\\!\\..+\\(`); // good
new RegExp(`\\!\\..+\\(`, 'u'); // invalid escape`

The unicode flag changes the meaning of the regular expression in subtle ways, but that is another topic I guess.

**Comment by roblourens** [comment]
Yes, rg is also strict about this. We could rewrite your regex to fix it, this has come up before, but that just seems like a good way to cause more subtle issues.
