### ISSUE TITLE
CTRL+V SEEM VERY SLOW

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#117973]
- VS Code Version: 1.54.insider
- OS Version:win 10 64
i am using insider and stable  version vscode . and both have the same problem that ctrl+v to paste is very low.
may be same as https://github.com/microsoft/vscode/issues/115396

Steps to Reproduce:

1. `Ctrl+c`
2. `Ctrl+v`
3. can not paste and i usually click `ctrl+v` twice and more,
4. few second later., vscode paste twice or more.

Does this issue occur when all extensions are disabled?: Yes/No
yes

i just want to remind that it is slowing down my work, please fix it in 1.54,please

**Comment by aeschli** [comment]
Is that in an editor, or in the terminal?

**Comment by heartacker** [comment]
> Is that in an editor, or in the terminal?

In the editor. please fix it,thanks

**Comment by treeder** [comment]
Same thing here.

**Comment by alexdima** [comment]
When you encounter this, could you please follow the steps documented [here](https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process) and create a CPU profile.
