### ISSUE TITLE
tsx attribute formatting removes bracket spacing

### ISSUE THREAD

**Issue by bookman25** [Microsoft/vscode#11791]
- VSCode Version: 1.5.1
- OS Version: Windows 10

Steps to Reproduce:

1. TypeScript Version: 2.*
2. `<input value={ this.state.value } />`
3. Format document

**Expected behavior:**
In **1.8.10** the spacing inside the brackets was unchanged on format operation (closing bracket `}` or format document).
`<input value={ this.state.value } />`

**Actual behavior:** 
In **2.*** the space inside the brackets is always removed when formatting.
```ts
<input value={this.state.value} />
```

Looks like it might be related to: https://github.com/Microsoft/TypeScript/pull/9361

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10872

**Comment by jwbay** [comment]
@waderyan per @SaschaNaz's comment in the TS repo, I checked and the relevant option is not present in VSCode: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/formattingProvider.ts

Does it just need to be added there?

**Comment by waderyan** [comment]
@dbaeumer can you comment on the above? This might be something we want to add.

**Comment by dbaeumer** [comment]
Yes, makes sense to add the option. Can you open an issue and set it to September.

**Comment by waderyan** [comment]
Issue created [here](https://github.com/Microsoft/vscode/issues/12046)
