### ISSUE TITLE
command-control-arrow command causes audible bell

### ISSUE THREAD

**Issue by Mellbourn** [microsoft/vscode#117934]
Issue Type: <b>Bug</b>

Whenever I move an editor with the command "View: Move Editor into Next Group" using the standard keybinding cmd-ctrl-right, the audible bell sounds. If I bind it to another key (e.g. cmd-m) there is no bell sound. Is this intentional? Seems like a bug.

Same thing happens for cmd-ctrl-left ("View: Move Editor into Previous Group")

VS Code version: Code - Insiders 1.54.0-insider (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:49.367Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv|--crash-reporter-id 7ef2ec96-2ed7-4a14-8512-86fd60296170|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (58)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.2
copy-relative-path|ale|0.0.2
aws-toolkit-vscode|ama|1.20.0
vscode-apollo|apo|1.18.2
atlascode|atl|2.8.5
color-info|bie|0.5.1
vscode-toggle-quotes|Bri|0.3.4
turbo-console-log|Cha|2.1.6
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
vscode-dash|dee|2.4.0
vscode-faker|dee|1.5.0
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
copy-relative-path|eno|0.1.1
prettier-vscode|esb|5.9.2
rightclick-git|Eve|2.0.0
shell-format|fox|7.0.1
vscode-pull-request-github|Git|0.23.1
rest-client|hum|0.24.4
svg|joc|1.4.5
vscode-peacock|joh|3.9.1
string-manipulation|mar|0.5.1
template-string-converter|meg|0.4.7
git-graph|mhu|1.29.0
dotenv|mik|1.0.1
vscode-json5|mrm|1.0.0
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.162.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.6
vsliveshare|ms-|1.0.3784
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
polacode|pnp|0.3.4
merge-n-paste|RAW|1.1.0
vscode-yaml|red|0.15.0
vscode-sort-json|ric|1.19.2
datetime|rid|2.0.3
ActiveFileInStatusBar|Ros|1.0.3
partial-diff|ryu|1.4.1
vscode-gtm|s3r|0.2.0
jest-snippets-standard|sht|1.0.3
vscode-csstree|sme|1.1.0
code-spell-checker|str|1.10.2
errorlens|use|3.2.4
gitdoc|vsl|0.0.6
footsteps|Wat|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265450

```

</details>

**Comment by sbatten** [comment]
Looks like this issue was filed upstream on chromium but isn't necessarily specific to chromium. Some steps to get this to stop were posted here: https://bugs.chromium.org/p/chromium/issues/detail?id=916460
