### ISSUE TITLE
Add a when clause to the contributed explorer view such that it is only activated when the workspace has a package.json file

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode#117950]
As you can see below, I don't have a package.json file in my workspace. I am working in a Python project. This extension is still contributing its view however.

![image](https://user-images.githubusercontent.com/11936772/98385926-31647000-2015-11eb-854e-42d8fe9c325e.png)

Would it be possible to have the extension only contribute its view when a package.json is found at the root of the workspace?

This feature is talked about here https://github.com/microsoft/vscode-java-test/issues/793#issuecomment-723045656.

**Comment by egamma** [comment]
@alexr00 is this a regression from when the when clause was changed so that it is always visible in the Views menu?

**Comment by alexr00** [comment]
Since the npm view is hidden by default, and because https://github.com/microsoft/vscode/issues/104591 I removed the package.json check. I can re-introduce the package.json check and have it search all folders instead of just the roots of the workspace folder if we want to fix this.

**Comment by alexr00** [comment]
After discussing with @egamma we decided to add the package.json check back in and make it more comprehensive.

**Comment by roblourens** [comment]
Works but this search is very expensive!

**Comment by roblourens** [comment]
I see you added a 1s timeout, thanks! Always be careful with triggering a search on startup
