### ISSUE TITLE
 Chinese Character Encoding Error With .NET Output Pannel

### ISSUE THREAD

**Issue by wswind** [microsoft/vscode#117955]
- VS Code Version: 1.53.2
- OS Version: Win10 20H2

Steps to Reproduce:

1. open asp.net core .proj file
2. add nuget package
3. vscode  prompting for nuget restore
4. press yes
5. see output pannel
![image](https://user-images.githubusercontent.com/18399096/109613840-b1868680-7b6c-11eb-956f-2035c21f5bca.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Can you file this against the C# extension? https://github.com/OmniSharp/omnisharp-vscode

**Comment by wswind** [comment]
https://github.com/OmniSharp/omnisharp-vscode/issues/4419
