### ISSUE TITLE
Publicly accessible previous versions of VS Code

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#11796]
Request from #11766 

> Also, it would be nice if there was an official download source to downgrade to a prior version. Fortunately, I found one in my trash this time, but I will definitely be disabling auto update because of this for future releases.

**Comment by waderyan** [comment]
We could build a page on code.visualstudio.com to allow this.

**Comment by gregvanl** [comment]
For each previous release we include the download links at the top of the release notes.

**Comment by joaomoreno** [comment]
This is done on my side. Here are a few examples:

- https://vscode-update.azurewebsites.net/1.5.0/win32/stable
- https://vscode-update.azurewebsites.net/1.2.0/darwin/stable
- https://vscode-update.azurewebsites.net/1.3.1/linux-deb-x64/stable

**Comment by DerfOh** [comment]
Thank you @joaomoreno, you have no idea how hard it is to find these links.

**Comment by lainekendall** [comment]
https://code.visualstudio.com/updates/v1_16
click update on left, the top of each page has download links for vs code
