### ISSUE TITLE
OutputChannel show didn' t working some time,  reopen #113912

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#117957]
If you have reproducable steps that work all the time let me know and we can reopen this.
For now closing this
fyi @sandy081

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/113912#issuecomment-756050223_

**Comment by zhfnjust** [comment]
hello , i write demo project which just contains simple code to reproducable this bug

https://screencast-o-matic.com/watch/crenj8WEjU

**Comment by sandy081** [comment]
Thanks for the sample repo, will investigate.

**Comment by zhfnjust** [comment]
are this bug fixed ?

**Comment by sandy081** [comment]
It works for me with the following code

```ts
export async function activate(context: vscode.ExtensionContext) {
    const outputChannel = vscode.window.createOutputChannel('Hello World');
    vscode.commands.registerCommand('test.showOutputChannel', (uri) => {
        outputChannel.show(true);
    });
}```

Can you please keep a break point in your code at line 31 and check if the break point is hit when the command is executed.

**Comment by zhfnjust** [comment]
i cannot  reproduce it with latest vscode ` 1.65.2`, maybe it has been fixed
