### ISSUE TITLE
pywin39.dll

### ISSUE THREAD

**Issue by abdulwaheed5** [microsoft/vscode#117992]
Issue Type: <b>Feature Request</b>

ImportError: No system module 'pywintypes' (pywintypes39.dll)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't provide Python functionality out of the box so this error comes from one of extensions.

Also it might be sign of incorrect Python or modules installastion, see https://stackoverflow.com/questions/65573140/importerror-no-system-module-pywintypes-pywintypes39-dll
