### ISSUE TITLE
Lines with proportional font wrap early

### ISSUE THREAD

**Issue by breyed** [microsoft/vscode#117999]
Issue Type: <b>Bug</b>

1. Set the text editing font to a proportional font.
2. Create a line in a HTML document that fits within the window space, butnot by much (e.g. by 3 ems).
3. Turn on line wrapping.

Notice that the line wraps even though it doesn't need to. It appears that the line wrapping algorithm is assuming a non-proportional font.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 48752c8d-6b3c-43fd-8474-b62a2acc4933|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.20.0
armview|ben|0.4.5
githistory|don|0.6.14
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
Ionide-fsharp|Ion|5.3.2
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.20.0
vscode-azurefunctions|ms-|1.2.1
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
azure-account|ms-|0.9.6
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.1.0
vsliveshare|ms-|1.0.3784
azurerm-vscode-tools|msa|0.14.1
vscode-css-peek|pra|4.1.0
LiveServer|rit|5.6.1
code-spell-checker|str|1.10.2
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30264245
pythontbcf:30265426

```

</details>

**Comment by alexdima** [comment]
Please use `"editor.wrappingStrategy": "advanced"`. This delegates wrapping points computation to the browser. This is a slow algorithm, that might cause freezes for large files, but it works correctly in all cases.

**Comment by breyed** [comment]
Thanks. That worked. A nice out-of-the-box feature would be to default to the advanced strategy for small files displayed in a proportional font but fall back to simple for large files.
