### ISSUE TITLE
Menus are misaligned when using 'classic'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#117968]
When using the Menu Bar setting `classic` then the menus that pull down are misaligned with the menu bar, pls see the screenshot below

![image](https://user-images.githubusercontent.com/172399/109655066-2654c300-7b63-11eb-855d-eec896922bba.png)

Similarly when using the left and right cursor keys to navigate the menubar and when you start at the 'Help' menu, then you cannot get to the 'File' menu

![image](https://user-images.githubusercontent.com/172399/109655567-b5fa7180-7b63-11eb-8a3e-f203fbcd7f84.png)

**Comment by egamma** [comment]
@sbatten voila, this is on OS X

<img width="702" alt="image" src="https://user-images.githubusercontent.com/172399/109700407-fcff5b80-7b91-11eb-8fae-08ee7abcca21.png">

**Comment by sbatten** [comment]
The issue was the extra piece of UX that codespaces has on top of the workbench. We had to switch to fixed positioning for safari to render the menus properly but didn't account for this. 

Due to that, this can only be verified by offsetting the workbench from the top of the page
