### ISSUE TITLE
Per-folder remote configuration in workspace

### ISSUE THREAD

**Issue by dougmoscrop** [microsoft/vscode#117931]
Would it be possible to support mixed remote authorities in a workspace? I'd like to have a single, multi-root workspace with one folder from WSL and one from SSH, for example.

**Comment by roblourens** [comment]
This isn't supported, but I can't find an open issue about it, do you know @aeschli?

**Comment by aeschli** [comment]
No that's not possible. 
Right a remote window connects to one remote server. It would be major architectural change to run multiple remote extension hosts.

**Comment by roblourens** [comment]
I know, just didn't know if we are tracking it somewhere. I don't think we are considering this to be in scope though.
