### ISSUE TITLE
VS Code eats alias-expand-line key combination in git bash

### ISSUE THREAD

**Issue by dfoverdx** [microsoft/vscode#117921]
Issue Type: <b>Bug</b>

1. Open up an integrated terminal targeting git bash
2. `alias foo='echo hello world'` <kbd>enter</kbd>
3. `foo` <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>e</kbd>
4. Notice nothing happens

This is not the case using Windows Terminal + git bash, nor with opening git bash directly in Windows.  I have tried updating my `.inputrc` to set `alias-expand-line` to a different key input--one that I know works--to no avail.  I have no keybindings set to `ctrl+alt+e` in my Keybindings.  This also doesn't work if I disable the *Allow chords* setting.

VS Code version: Code - Insiders 1.54.0-insider (e590188f17162393f50feec19263398e6fe02d13, 2021-02-26T20:39:10.253Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.30GB free)|
|Process Argv|--crash-reporter-id 007f9f10-c4ef-458b-a674-6faaf4393697|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533

```

</details>

**Comment by ArturoDent** [comment]
Possibly related https://github.com/microsoft/vscode/issues/81268 and https://bugs.chromium.org/p/chromium/issues/detail?id=959110.  Unfortunately, the Chrome issue was not completed.

Fir what is worth, Chrome on W10 gives me this report:

![chromeEvent](https://user-images.githubusercontent.com/31813701/109716887-99aa0500-7b62-11eb-9259-b62ca1d8c0cc.jpg)

Both Edge and Firefox onW10 report this:


![EdgeEvent](https://user-images.githubusercontent.com/31813701/109716988-b9412d80-7b62-11eb-9b99-aefeff177b30.jpg)


So some extra keydown events in chrome seems odd.  Could that be the problem for Electron?

**Comment by ArturoDent** [comment]
Also see https://github.com/Microsoft/vscode/issues/68787 and the fixes mentioned there.

**Comment by bluefrog845** [comment]
I have the same issue on 1.56.2 when sending any Ctrl + alt + key to WSL. It works fine if I open a WSL terminal outside of vscode.
