### ISSUE TITLE
output console not showing process.stdout.write

### ISSUE THREAD

**Issue by rickmed** [Microsoft/vscode#1179]
**I have this on my tasks.json**

{
    "version": "0.1.0",
    "command": "cmd",
    "options": {
      "env": {
        "NODE_ENV": "development"
      }
    },
    "isShellCommand": true,
    "args": ["/C"],
    "tasks": [
        {
            "taskName": "Run node current file",
            "args": ["node ", "${file}"],
            "isBuildCommand": true,
            "suppressTaskName": true
        }
    ]
}

**when running this script using the node task:**

'use strict'

var os = require('os')
var eol = os.EOL
var nl = 'hola \r\n'

console.log(os.uptime() + nl)
console.log(os.type())
console.log('h', eol)
console.log(eol)
process.stdout.write('hello: x')

**the output is:**

185583.3875537hola 
Windows_NT
h 

**but on the console running node filename.js**

185603.0488328hola

Windows_NT
h

hello: x

**Comment by dbaeumer** [comment]
@ricmed205 which version of node are you using. There is a know problem with node not flushing stdio before the process exits which results in loosing output. There is not much VSCode can do about it since we are reading childProcess.stdout and never get the text.

**Comment by ricmed205** [comment]
V4.2.3

**Comment by ricmed205** [comment]
When I run the debug process (F5) it prints everything alright. I could use this to run node scripts although it's kind of annoying the messages of debugging in the console and that I need to stop the debugging process every time the script completes. Is there a way to auto stop the debugging process if a script completes ok?

**Comment by saeedtabrizi** [comment]
I have same issue that i explained in https://github.com/Microsoft/vscode/issues/28872 . :(

**Comment by dbaeumer** [comment]
@saeedtabrizi are you seeing this with debug or tasks. #28872 is about the debug console.

**Comment by AntSworD** [comment]
I have same issue when launch my node file

**Comment by dbaeumer** [comment]
This got addressed by the new terminal runner. To make use of the new terminal runner please see: https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200
