### ISSUE TITLE
Start a slightly larger Vue project and crash

### ISSUE THREAD

**Issue by lwm98** [microsoft/vscode#117940]
It's no use to change the vscode version.
The current version is 'VSCode-win32-x64-1.53.2'

![image](https://user-images.githubusercontent.com/48340898/109588059-1927dc00-7b43-11eb-83cb-102b8ce8fa9e.png)
![image](https://user-images.githubusercontent.com/48340898/109588161-47a5b700-7b43-11eb-9a0f-492f873890ac.png)
![image](https://user-images.githubusercontent.com/48340898/109587977-f269a580-7b42-11eb-8759-419e19b90d53.png)

How can I solve

**Comment by deepak1556** [comment]
Do you see this crash when you start with --disable-extensions ?

Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and provide the crash dumps.
