### ISSUE TITLE
VS Code won't update (Macbook Pro 2012 i5 )

### ISSUE THREAD

**Issue by mr-dignitty** [Microsoft/vscode#11797]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:41:29.513Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Open Visual Studio Code and then open Console.app 

2. From Console.app System Log Queries:
` 9/9/16 3:09:27.749 PM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt[939]) Service could not initialize: 15G1004: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
`
3. From Console.app System Log Queries:
`9/9/16 3:09:27.749 PM com.apple.xpc.launchd[1]: (com.microsoft.VSCode.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.`

**Comment by mr-dignitty** [comment]
I believe the issue is that I had 2 Visual Studio Applications installed side-by-side. Not sure how this happened? May have been post-update from 1.4.0 to 1.5.1 .. I was using 1.4.0 when Console.app Logged those Queries.

**Comment by ramya-rao-a** [comment]
@mr-dignitty Do you still have any issues or are you unblocked?

**Comment by joaomoreno** [comment]
#10718 #3520
