### ISSUE TITLE
Ubuntu: Ctrl+Shift+E cannot be used as a shortcut

### ISSUE THREAD

**Issue by mmatrosov** [microsoft/vscode#117966]
- VS Code Version:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-43-generic snap
```
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Open editor
2. Press Ctrl+Shift+E
3. A strange underlined input sequence begins starting with the letter "e". It terminates after 9 more characters are inputted.

Does this issue occur when all extensions are disabled?: Yes

Seems like the same issue as https://github.com/Microsoft/vscode/issues/48480, but the latter is old and I don't see a good solution for Ubuntu.

Seems like the GTK version should be with the fix included:
```
$ apt list --installed *libgtk-3*
Listing... Done
libgtk-3-0/focal-updates,now 3.24.20-0ubuntu1 amd64 [installed,automatic]
libgtk-3-bin/focal-updates,now 3.24.20-0ubuntu1 amd64 [installed,automatic]
libgtk-3-common/focal-updates,focal-updates,now 3.24.20-0ubuntu1 all [installed,automatic]
```

**Comment by alexdima** [comment]
I think this is a well known issue and some configuratin needs to be changed to stop doing Emoji input via ctrl+shift+E -- https://unix.stackexchange.com/questions/394655/ctrlshifte-causes-beeping/394767#394767
