### ISSUE TITLE
Always visible file path

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#11798]
- VSCode Version: 1.5.1
- OS Version: Windows 10

It would be nice if there was an option to toggle the visibility the file path at all times of the current tab.

So, when it is enabled, it would display like this (red is only to make it stand out in the example):

![with-name](https://cloud.githubusercontent.com/assets/1571806/18399540/1856f6cc-7697-11e6-8aa4-fb58367c057c.png)

**Comment by mrmlnc** [comment]
Have you tried this extension: https://marketplace.visualstudio.com/items?itemName=RoscoP.ActiveFileInStatusBar

**Comment by TheColorRed** [comment]
I have not... I will give it a try...

**Comment by ramya-rao-a** [comment]
@TheColorRed , the extension @mrmlnc has suggested should solve your needs to see the file path.
So closing this issue.

Apart from this, there is already another item that tracks showing the file path (or parts of it) in the tab when there are multiple files open in tabs with same name but different paths #8499
