### ISSUE TITLE
Non-editable notebook documents allow language changes 

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#117937]
- VS Code Version: 1.54.0-insiders
- OS Version: Win10

Steps to Reproduce:

1. Mark notebook document and individual notebook cells read-only by making `editable = false` in their metadata. 
2. Confirm read-only by trying to edit cells.
3. Try to change language

Expected: Guest cannot change the cell's language.

Actual: Guest can change cell's language.

![readonly-changelanguage](https://user-images.githubusercontent.com/22576531/109578422-fe565880-7aab-11eb-8d84-d3fe466216ca.gif)

cc @ rebornix

**Comment by rebornix** [comment]
This iteration we pushed a fix for disallowing change cell language through the cell language button.

**Comment by jrieken** [comment]
I can still change the language to markdown

* open GH issue notebook
* lock a code cell
* change language to markdown
* success

**Comment by rebornix** [comment]
ok, other than fixing the case just found above, we should have a good fix for all scenarios. Right now the `readonly` notion is adopted in multiple places (but not all) and not clear who has the final say (from users' perspective)

For example, a text editor

* If the file is readonly, you can't type in the Monaco editor (the cursor handles that specificaly)
* When you save, the file service checks if the file is readonly or not
* When you use workspace edit to update the document, it always works (also making the document dirty in the editor)

Now we have the same trouble with notebook document, in addition to the text model of cells

* Notebook document's readonly state is determined by `editable` metadata. When set to `false`, you should not be able to insert/delete cells
  * but we don't have such prevention for workspace edits, just like the text model
* We don't prevent it from saving. (we can check `editable`, but it's still not guaranteed as the file service may disallow)
* We prevent change cell language from the picker (with https://github.com/microsoft/vscode/issues/117937#issuecomment-806747368 fixed), but users can still use `setTextDocumentLanguage` to change the cell language. How do we prevent that from happening?

Short description of this debt is:

* Notebook document has its own text model + composite Monaco text models
* Notebook document has its own API to `applyEdits`
* Edits to cell text models can come from WorkspaceEdit or other API provided by the `textModelService`

**Comment by jrieken** [comment]
> When you save, the file service checks if the file is readonly or not

That's likely a different readonly, like a readonly file system, but many readonly text model don't make it to file service because they aren't from one, like virtual documents or "bare" models

>When you use workspace edit to update the document, it always works (also making the document dirty in the editor)

Yeah, there is a lengthly discussion about that and it is the way it is because of LiveShare - the wanna show certain files are readonly and yet be able to update them. 

> Now we have the same trouble with notebook document, in addition to the text model of cells

I wonder if we are just inventing trouble for ourself. Why don't we re-define this as "readMode" without any "correctness" guarantees? Today, I can edit a cell, lock it, press undo. Should undo be prevented? Should it undo the locking and then the edits? Do we really want all this trouble?

**Comment by rebornix** [comment]
We don't have `editable` metadata anymore.

**Comment by rzhao271** [comment]
@rebornix what are some steps to verify this issue?
I tried adding `"editable": false` to one of the cells while in plain text view, but noticed that data just got wiped out after saving the cell in notebook view, and then checking the plain text view again. This behaviour seems consistent with https://github.com/microsoft/vscode/issues/117937#issuecomment-854198308.

**Comment by roblourens** [comment]
We removed the editable metadata like Peng said, so this is basically n/a

**Comment by alyssajotice** [comment]
What is the new equivalent for marking cells read-only?
