### ISSUE TITLE
Why do we sync the command palettes MRU cache?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#117902]
Isn't this machine/folder specific?

![image](https://user-images.githubusercontent.com/2193314/109526650-a8f85800-7a67-11eb-8750-b25cc9ecb7aa.png)

**Comment by bpasero** [comment]
Why not? I think it would be nice to switch machines having the same environment around with regards to what commands have been used. Note that the MRU list was always global even before we had syncing.

**Comment by Tyriar** [comment]
Seems wasteful because then settings sync takes the slower path very often where it has to hit the DB for every client. We can close this out for now if you think there is value here, then maybe reconsider if we want to reduce writes for scalability reasons. cc @lszomoru

**Comment by bpasero** [comment]
I think the decision of value should not be driven by settings sync servicing implications. If the amount of data or frequency of syncing is an issue then we need to revisit what get's synced and when in total and not one by one for individual things imho. We also do not have a lot of control over this once extensions can signal the state that should be synced.
