### ISSUE TITLE
remove the excess output

### ISSUE THREAD

**Issue by parikshit14** [microsoft/vscode#117969]
Issue Type: <b>Performance Issue</b>

how to remove the excess output present in the terminal like path etc.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.50GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 71a6898d-2010-4965-a990-8410d9578118|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	  8913	code main
    0	    15	  8916	   zygote
    0	    77	  8941	     gpu-process
    0	    15	  8917	   zygote
    0	    69	 13181	     window (Issue Reporter)
    0	    23	  8952	   utility
    0	   231	  8975	   window (Settings - DSA - Visual Studio Code)
    0	     0	  9020	     /bin/bash
    0	   108	  9030	     extensionHost
    0	    46	  9073	       /home/parikshit/.vscode/extensions/ms-vscode.cpptools-1.2.2/bin/cpptools
    0	    23	  9990	         /home/parikshit/.vscode/extensions/ms-vscode.cpptools-1.2.2/bin/cpptools-srv 9073 {F2B58B73-9DDC-4946-8924-EF00B9CEAD34}
    0	    54	 10183	       /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9030
    0	    31	  9051	     watcherService
    0	    31	  9340	     searchService
    0	     0	  9420	     /bin/bash
    0	     0	  9926	     /bin/bash
    0	     0	 10012	     /bin/bash
    0	     0	 10028	     /bin/bash
    0	    69	  9135	   shared-process
    0	     0	 13210	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 13211	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - DSA - Visual Studio Code)
|    Folder (DSA): 9 files
|      File types: cpp(3) json(2)
|      Conf files: launch.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30265425

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
