### ISSUE TITLE
macOS help title bar flashes on startup

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#117989]
- VS Code Version: 1.54.0-insider
Commit: e7989863202eac0ec4e66ca82733d968bca7527a
- OS Version: macOS 11.2.2

Steps to Reproduce:

1. Start up VS Code on mac
2. Click the help tab at the top
3. 🐛 The search bar and context menu flashes quite a bit while VS Code initializes

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@lramos15 not a regression though right?

**Comment by lramos15** [comment]
Yeah this isn't a regression.

**Comment by bpasero** [comment]
I was curious and think its an Electron bug when using `role` attribute `Help`: https://github.com/electron/electron/issues/40099

**Comment by sbatten** [comment]
closing as upstream and inactionable for the time being
