### ISSUE TITLE
Portable mode ignored

### ISSUE THREAD

**Issue by Kein** [microsoft/vscode#117913]
- VS Code Version: 1.53.3
- OS Version: Win 10

Steps to Reproduce:

1. Unpack VSCode installer
2. Create `data\` alongside Code.exe
3. Launch
4. `data\` ignored, `.vscode` in %USER% created

Does this issue occur when all extensions are disabled?: Yes

_Different from #93828
Cannot b reproduced on 1.51.1_

**Comment by deepak1556** [comment]
`Unpack VSCode installer` are you referring to the zip or installer ? Portable mode will only work with the zip package.

I am unable to repro the issue with `1.53.2`

**Comment by Kein** [comment]
Zip package?

> Portable mode will only work with the zip package.

This seems misleading as the docs say nothing about zip package

**Comment by deepak1556** [comment]
Its mentioned here https://code.visualstudio.com/docs/editor/portable

```
Note: Do not attempt to configure portable mode on an installation from the Windows User or System installers. Portable mode is only supported on the Windows ZIP (.zip) archive. Note as well that the Windows ZIP archive does not support auto update.
```
