### ISSUE TITLE
Build still broken on ARM linux

### ISSUE THREAD

**Issue by ststeiger** [Microsoft/vscode#11792]
node --version
v6.5.0

npm --version
3.10.3

uname -a
Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:26:16 PDT 2016 armv7l armv7l armv7l GNU/Linux

lsb_release -rcd
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Built according to:
http://www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx

purged old nodejs, installed node 6, latest + npm
sudo apt-get install libx11-dev
git clone https://github.com/microsoft/vscode
cd vscode
./scripts/npm.sh install --arch=armhf

This is not a dupliate of https://github.com/Microsoft/vscode/issues/6442
My NodeJS +NPM version is the latest possible version. 
It still doesn't build. 
Why is it building windows mutexes on Linux ? That can't work...

./scripts/npm.sh install --arch=armhf
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.

> windows-mutex@0.2.0 install /root/sources/vscode/node_modules/windows-mutex
> node-gyp rebuild

make: Entering directory `/root/sources/vscode/node_modules/windows-mutex/build'
  CXX(target) Release/obj.target/CreateMutex/src/main.o
../src/main.cc:2:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
make: *** [Release/obj.target/CreateMutex/src/main.o] Error 1
make: Leaving directory `/root/sources/vscode/node_modules/windows-mutex/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.10.18
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/sources/vscode/node_modules/windows-mutex
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:windows-mutex@0.2.0 windows-mutex@0.2.0 install: `node-gyp rebuild`
npm WARN install:windows-mutex@0.2.0 Exit status 1
npm WARN lifecycle code-oss-dev@1.6.0~preinstall: cannot run in wd %s %s (wd=%s) code-oss-dev@1.6.0 node build/npm/preinstall.js /root/sources/vscode
npm WARN lifecycle code-oss-dev@1.6.0~postinstall: cannot run in wd %s %s (wd=%s) code-oss-dev@1.6.0 node build/npm/postinstall.js /root/sources/vscode
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8

**Comment by Tyriar** [comment]
You need to use npm < 3.9 as per https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source, this is happening due https://github.com/npm/npm/issues/12698 trying to installing windows-mutex even though it's an optional dependency.
