### ISSUE TITLE
Incorrect error type on auth cancellation (No authentication provider 'microsoft' is currently registered.)

### ISSUE THREAD

**Issue by olegoid** [microsoft/vscode#117908]
Version: 1.54.0-insider (user setup)
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:39:10.253Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

## Steps to Reproduce

1. Sing in to Sync Settings
2. Select Microsoft provider
3. Press "Allow" and go to the browser
4. Cancel auth in the browser by pressing "Back"

## Actual

VSCode throws:
```
No authentication provider 'microsoft' is currently registered.
```

The provider, however, is registered.

Previously, auth API threw "access_denied" error for this particular scenario.

**Comment by xisui-MSFT** [comment]
Not sure if this is related... We got the same error in our test using insiders without any sign in actions.

**Comment by olegoid** [comment]
@xisui-MSFT, I'm not sure what your scenario was but I believe that this error is still there:
https://github.com/microsoft/vscode/blame/main/src/vs/workbench/services/authentication/browser/authenticationService.ts#L713

From the consumer's perspective, it doesn't hurt to know what actually caused the authentication failure. So, maybe we can slightly change that try/catch block to be more transperent.

**Comment by xisui-MSFT** [comment]
@olegoid Again I'm not sure if this is the same issue. For me looks like that error causes all extension tests fail without running anything. Sample output:
```
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2021-03-18T10:08:53.916Z] update#setState idle

(node:17236) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(node:17236) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

No authentication provider 'microsoft' is currently registered.

Settings Sync: Accounts are not initialized

native-keymap: Could not create ITfThreadMgr.

Exit code:   1
Done

Assertion failed: Failed to run tests
```

You should be able to repro this easily by creating an extension + a test for the extension, and run the test on latest insider build.

**Comment by xisui-MSFT** [comment]
@olegoid @RMacfarlane Have you checked whether the test error the same as this issue? It's an important issue as it causes ALL extension tests to fail.

**Comment by RMacfarlane** [comment]
Hey @xisui-MSFT, that sounds like a different issue. I'm having trouble reproducing it with a sample extension, but I think the tests should continue to run even if settings sync doesn't initialize. The `native-keymap: Could not create ITfThreadMgr.` error sounds more suspicious to me. It would be great if you could open a new issue including details about what version of VS Code insider's you are using and what your test set up looks like. Thanks!

**Comment by xisui-MSFT** [comment]
@RMacfarlane Thanks for the info. I think I found the problems, and I'll open some bugs. (BTW, the native-keymap line isn't the problem, basically all the failures have that...)
