### ISSUE TITLE
Button focus state inconsistent

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117909]
In notifications we show an outline offset when the button is focused:

![image](https://user-images.githubusercontent.com/35271042/109537974-68eba200-7a74-11eb-91aa-ad246d5e0cf9.png)

But in other places the offset isn't applied correctly and blends in with the hover state:

![image](https://user-images.githubusercontent.com/35271042/109538023-730da080-7a74-11eb-8f33-ff2885b7d6bc.png)

We should add the offset to all of our buttons to make the focus state clearer and pass a11y.

fyi @joaomoreno @isidorn @bpasero

**Comment by hawkticehurst** [comment]
Heads up, the lack of button outline offset is also very prevalent on the settings page.

<img width="210" alt="Screen Shot 2021-03-01 at 10 03 03 AM" src="https://user-images.githubusercontent.com/39639992/109538909-75bcc580-7a75-11eb-8bbe-81860781d7ba.png">
<img width="194" alt="Screen Shot 2021-03-01 at 10 03 19 AM" src="https://user-images.githubusercontent.com/39639992/109538911-76555c00-7a75-11eb-880e-83cce4fe2d65.png">

**Comment by misolori** [comment]
This should now be fixed on all buttons:

![image](https://user-images.githubusercontent.com/35271042/110036692-3ea71800-7cf2-11eb-8656-4dd03ceaf194.png)
