### ISSUE TITLE
vscode/src/vs/workbench/contrib/debug/common/debug.ts is causing warnings during localization export

### ISSUE THREAD

**Issue by nexue2020** [microsoft/vscode#117910]
- VS Code Version: 1.54
- OS Version: Windows 10

Steps to Reproduce:

1. gulp --max-old-space-size=8192 vscode-translations-export
2. ![image](https://user-images.githubusercontent.com/73669577/109538522-0941c680-7a75-11eb-95e8-1297902c0b93.png)

The root cause most likely lies in the empty strings **callStackItemType** and **watchItemType**.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
@nexue2020 thanks for letting us know, I will push a fix right away. You are correct about the root cause.
