### ISSUE TITLE
Code Helper (Renderer) High CPU Use 

### ISSUE THREAD

**Issue by bmasters7** [microsoft/vscode#117981]
- VS Code Version: 1.54.0-insider (but was happening)
Commit: e590188f17162393f50feec19263398e6fe02d13
Date: 2021-02-26T20:39:12.763Z (3 days ago)
- OS Version: 11.2.1 (but was happening on previous OS versions since early fall)

Steps to Reproduce:

Reference https://github.com/microsoft/vscode/issues/110323 as this branched from that similar issue.

1. Open VSC with larger file 1000+ lines.
2. Intermittently CPU will start a large CPU Renderer process taking 140% of CPU persistently until closed.

Does this issue occur when all extensions are disabled?: Yes

Info provided on other bug, requested to be reported as a new issue by deepak1556.

FROM 2/20 post:

```
$ code-insiders --status
Conflict in settings file file:///Users/REDACTED/Library/Application%20Support/Code%20-%20Insiders/User/settings.json: Ignoring editor.defaultFormatter.possible as editor.defaultFormatter is "bmewburn.vscode-intelephense-client"
Version: Code - Insiders 1.54.0-insider (192c817, 2021-02-19T05:13:45.061Z)
OS Version: Darwin x64 20.3.0
CPUs: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
Memory (System): 32.00GB (0.28GB free)
Load (avg): 3, 3, 3
VM: 0%
Screen Reader: no
Process Argv: --crash-reporter-id 999a9c7d-ebba-4e31-b778-e2fbb6d70bec
GPU Status: 2d_canvas: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: enabled
opengl: enabled_on
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off_ok
video_decode: enabled
webgl: enabled
webgl2: enabled

CPU % Mem MB PID Process
0 98 3339 code-insiders main
0 66 3354 gpu-process
0 33 3366 utility
0 295 3372 window (Database.DeviceUsers.inc.php — Website)
0 98 3410 extensionHost
0 66 3455 electron_node server.js
145 2654 7733 watcherService
0 66 3417 shared-process
0 33 3419 ptyHost
0 0 3423 /bin/bash -l
0 0 11021 bash /usr/local/bin/code-insiders --status
0 33 11031 electron_node cli.js

Workspace Stats:
| Window (Database.DeviceUsers.inc.php — Website)
| Folder (Website): 8599 files
| File types: php(3509) png(528) po(433) test(280) js(191) md(142)
| jpg(108) json(104) rst(96) css(84)
| Conf files: launch.json(1) makefile(1)
| Launch Configs: php(2)

TODAY (on code-insiders version with extensions disabled):
ip-192-168-3-5[09:10:24]:[bmasters]:[~/Lab/2mmweb/Website]
$ code --status
Conflict in settings file file:///Users/bmasters/Library/Application%20Support/Code%20-%20Insiders/User/settings.json: Ignoring editor.defaultFormatter.possible as editor.defaultFormatter is "bmewburn.vscode-intelephense-client"
Version:          Code - Insiders 1.54.0-insider (e7989863202eac0ec4e66ca82733d968bca7527a, 2021-03-01T21:13:40.027Z)
OS Version:       Darwin x64 20.3.0
CPUs:             Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)
Memory (System):  32.00GB (1.25GB free)
Load (avg):       4, 4, 5
VM:               0%
Screen Reader:    no
Process Argv:     --disable-extensions --crash-reporter-id 999a9c7d-ebba-4e31-b778-e2fbb6d70bec
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    2      131   66452  code-insiders main
    2       66   66461     gpu-process
    0       33   66462     utility
    4      295   66465     window (ReportsHelper.inc.php — Website)
    0       98   66472       extensionHost
  129      754   66474       watcherService
    0       98   66473     shared-process
    0       33   66478       ptyHost
    0        0   66482         /bin/bash -l
    0        0   67716           bash /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code --status
    2       33   67726             electron_node cli.js 

Workspace Stats: 
|  Window (ReportsHelper.inc.php — Website)
|    Folder (Website): 8600 files
|      File types: php(3509) png(528) po(433) test(280) js(191) md(142)
|                  jpg(108) json(104) rst(96) css(84)
|      Conf files: launch.json(1) makefile(1)
|      Launch Configs: php(2)

```

**Comment by VitalieGobjila** [comment]
I have the same problem!
Below is my report:

> $ code --status
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Version:          Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS Version:       Darwin x64 20.3.0
CPUs:             Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
Memory (System):  32.00GB (3.38GB free)
Load (avg):       6, 5, 4
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 818b3008-a219-42a9-acc1-497800be4a28
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  metal:                      disabled_off
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              disabled_off_ok
                  video_decode:               enabled
                  webgl:                      enabled
                  webgl2:                     enabled
CPU %   Mem MB     PID  Process
    9      131    6869  code main
    3       66    6876     gpu-process
    0       33    6878     utility
   14      295    6879     window (DatabasePatchManager.inc.php — Website)
    0        0    6887       /bin/bash -l
    0        0    7864         bash /usr/local/bin/code --status
   10       33    7874           electron_node cli.js 
    0       98    6890       extensionHost
    0       33    6903         electron_node server.js 
  290      393    7824         electron_node intelephense.js 
  155     1016    6895       watcherService
    0       98    6899     shared-process
Workspace Stats: 
|  Window (DatabasePatchManager.inc.php — Website)
|    Folder (Website): 8459 files
|      File types: php(3473) png(508) po(433) test(280) js(186) md(142)
|                  jpg(107) json(105) rst(96) css(84)
|      Conf files: launch.json(2) makefile(1)
|      Launch Configs: php(2)

**Comment by aeschli** [comment]
In both cases a PHP file was open.  
@bmasters7 @vitalie8 Does it reproduce with extensions disabled? If yes, can you provide a PHP file where this happens?

@roblourens Has there been an update of the PHP grammar?

**Comment by bmasters7** [comment]
Yes Php file was open.

Also yes…used the extensions disable option and confirmed it continued to occur.

**Comment by roblourens** [comment]
You are saying "renderer process" but your data shows it's the file watcher process

`145 2654 7733 watcherService`

And in @vitalie8's it looks like the intelephense language server process, so you can file an issue on that extension's repo.

**Comment by bmasters7** [comment]
This is what is reported in Activity Monitor:

**Comment by roblourens** [comment]
@bmasters7 if you meant to attach an image, there is no image, that doesn't work through email unfortunately.

**Comment by roblourens** [comment]
I see, the Activity Monitor labels a lot of processes as "Renderer" that aren't what we are calling the Renderer process. But the stats you shared show the real situation.

Looks like you tried it with `--disable-extensions`, thanks. How long does the CPU stay high, does it go down after a couple minutes?

**Comment by bmasters7** [comment]
When it is in this mode it will go all day until VSC is shut down.  Not 100% occurrence (recommend trying with large PHP files, 1000-5000 lines) and haven’t been able to isolate if it is specific files but seems to happen with as few as 2-3 files open.
