### ISSUE TITLE
Zen mode center layout with up/down split

### ISSUE THREAD

**Issue by Relequestual** [microsoft/vscode#117977]
**Use case:**
I usually work with two tab groups open, split vertically, left/right.
I wanted to hide the right set to focus, but not remove them (ideally).
I found Zen mode, and centre layout (My true middle is not the middle of my screen, sadly... limited space at home).

**Problem:**
Zen mode with centre layout doesn't work with multiple tab groups.

**Feature I'd like:**
This is understandable when the split is vertical (left/right), but it should be possible with a horizontal split (up/down).
This would be very useful when working with test scripts that define a large array of tests in one section, and then execute those tests in another section using a loop.

I found https://github.com/microsoft/vscode/issues/94574 which seems to have prevented centre layout from working if there are more than one tab groups, regardless of the relative position/location of those tab groups.

I could not find any issue the same as this specific feature request.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by Relequestual** [comment]
Fair comment. I expect if I DID find time to help with PRs, I'd be focused on JSON Schema support!

**Comment by amogorkon** [comment]
I usually focus work on a single file on a wide monitor with zen mode, which works perfectly fine, but I also quite often need to compare two files, so I end up switching back and forth between tabs, which is anything but "zen".. Having them two vertically split and literally the right half of the screen blank is also not really useful.
I wished you reconsider and regard this issue as crucial for usability.

**Comment by jucor** [comment]
I have the same setup as @amogorkon -- it would be a lovely feature to have please. Thank you very much for reconsidering, and good luck with the avalanche of feature requests in VSCode!
