### ISSUE TITLE
Allow to change language mode in composite editors

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#117943]
Follow up of https://github.com/microsoft/vscode/issues/114554. The only bleeding of `notebook` is in [`ChangeModeAction`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/editorStatus.ts#L1052) as it only works currently in text editor but can show up in command palette when the editor is not text editor. However it makes sense to support composite editor (like notebook, walk through, etc).

Once we support that, the context key can be `editorFocus | inCompositeEditor`.

**Comment by bpasero** [comment]
Makes sense, I am open for a PR here if someone wants to chime in (from the team).
