### ISSUE TITLE
Terminal is not always focused when opening panel

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#117935]
- Focus the terminal, close the panel and reload the window
- Press cmd+J to show the panel, with the terminal persisted to be the active view
- The terminal should be created and focused. Sometimes, it's not

I think this is new in 1.54. Seems like it usually reproes the first time the panel is opened. But, if I kill all terminals, causing the panel to close, then press cmd+J again, it focuses the new terminal correctly.

**Comment by meganrogge** [comment]
repro:

- create a terminal
- kill it (panel closes)
- reload window
- open panel -> terminal isn't focused

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/9093f265a64f640c3fb385195f6b1883deea2b93/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L[…]8

isn't getting hit when I put a breakpoint there and open the panel
