### ISSUE TITLE
Force Quit when Visual Studio Code froze did not work on Mac

### ISSUE THREAD

**Issue by LynneMN** [microsoft/vscode#117993]
Issue Type: <b>Performance Issue</b>

The program was not responding and did not shut down even after Force Quit. I had to restart the OS to get rid of it. This is my first time running Visual Studio Code after Brackets.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 93375802-32f1-4941-9874-1c5a40344cc1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	  1083	code main
    0	    49	  1088	   gpu-process
    0	    25	  1092	   utility
    0	   221	  1093	   window (Welcome)
    0	    98	  1101	     extensionHost
    0	    33	  1117	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=1101
    0	    33	  1164	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1101
    0	    90	  1105	   shared-process
    0	     0	  1313	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	  1291	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2
live-server-preview|neg|0.1.4
live-preview|pro|0.0.3
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999

```

</details>

**Comment by aeschli** [comment]
I would be great to find out why VScode hang. Did you for example open a very large file?

https://github.com/microsoft/vscode/wiki/Performance-Issues has steps on how to get more information on hangs.

**Comment by LynneMN** [comment]
No, I only opened a style.css
Thank you,

Lynne

emasai.com
Tel: 858-373-8342

**Comment by aeschli** [comment]
Does it reproduce when you open the same file again? If yes, can you attach the file?

**Comment by LynneMN** [comment]
I only installed it 2 days ago in replacement of Brackets and have only
opened 3 style.css files. I opened them all today and the program didn't
freeze.
Thank you,

Lynne

emasai.com
Tel: 858-373-8342
