### ISSUE TITLE
Authorizing a Saleforce Org

### ISSUE THREAD

**Issue by tfranklin27** [microsoft/vscode#117906]
When trying to authorize an org, a localhost error is displayed. The org was authorized previously but the link used no longer exist. When trying to authorize the same org with a new link, the localhost error is shown. I'm not sure how to delete the original link from VScode to see if that would help.

**Comment by RMacfarlane** [comment]
@tfenster Is this from an extension? How are you authorizing an org?

**Comment by tfenster** [comment]
Wrong person, probably intended for @tfranklin27

**Comment by tfranklin27** [comment]
@RMacfarlane yes it is from the Salesforce extension pack. Authorizing by ctrl+shift+p, >SDFX:Authorize An Org, Sandbox (test.salesorce.com), input alias, it then sends me to chrome for the salesforce login, after entering my credentials, it will go to the next page like its going to authorize the org but never loads. It will stay on a white screen until I cancel in VScode, then I get the localhost error.

**Comment by RMacfarlane** [comment]
Thanks for confirming. Since this is a feature of the Salesforce extension pack, can you please open the issue on that extension? https://github.com/forcedotcom/salesforcedx-vscode

This repository only tracks issues with the core of VSCode.
