### ISSUE TITLE
Typescript and ESLint built-in extensions not working

### ISSUE THREAD

**Issue by bobness** [microsoft/vscode#117927]
Issue Type: <b>Bug</b>

I get the 'has crashed * times in the past 5 minutes' errors all the time, and my Typescript hover tips continue to say 'loading...'. Similarly, I need to reload the window to get eslint to reload, too. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (2.68GB free)|
|Process Argv|--crash-reporter-id f8d0ea8e-d06a-4674-a850-b2f5251c598f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
proto3-nav|bri|0.2.2
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
vscode-go-test-adapter|eth|0.1.5
vscode-jest-runner|fir|0.4.31
go|gol|0.22.1
vscode-test-explorer|hbe|2.19.5
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.158.0
vsliveshare|ms-|1.0.3784
quicktype|qui|12.0.46
vscode-xml|red|0.15.0
vscode-yaml|red|0.15.0
rewrap|stk|1.14.0
eno|Wsc|2.3.53
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
