### ISSUE TITLE
Prompt me to save the unrelated editor contents when triggering debugging

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#117949]
- VS Code Version: 1.53.2
- OS Version: macOS

Steps to Reproduce:
1. Make the current editor stop at a non Java file. For example, stop at a binary class file which is rendered by a custom content provider, or stop at an Untitled file.
2. F5 to trigger debugging, it will pop up a dialog to ask me to save the content provider or the Untitled file. This is weird. This behavior also applies to JS debugger and starts to happen since 1.53. 

![image](https://user-images.githubusercontent.com/14052197/109607199-d8d85600-7b62-11eb-8eb6-3444be847bd0.png)

**Comment by weinand** [comment]
A new setting `debug.saveBeforeStart` has been introduced in VS Code 1.54 to address this.
Please see https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_54.md#other-ui-improvements.

**Comment by isidorn** [comment]
Yeah this is just a decision we made, that we want to save all editors in the active group.
In the release notes as Andre mentioned we introduced a setting to control this.
So for now, no changes planned here thus closing this.
If you have good ideas feel free to comment 

More details here https://github.com/microsoft/vscode/issues/111850 and https://github.com/microsoft/vscode/issues/114890

**Comment by testforstephen** [comment]
I see. Setting it to `"debug.saveBeforeStart": "nonUntitledEditorsInActiveGroup"` can suppress the dialog, that satisfies my requirement. Thanks.
