### ISSUE TITLE
vscode.languages.setTextDocumentLanguage does not work on notebook cells

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#117936]
- VS Code Version: 1.54.0-insider
- OS Version: Win10

When coediting, the command `vscode.languages.setTextDocumentLanguage` does not work on notebook cells. It successfully updates the language services for the cell but does not change the label indicating the new language. 

![setTextDocumentLanguage](https://user-images.githubusercontent.com/22576531/109576915-87b85b80-7aa9-11eb-98b0-20c78f2a9a80.gif)

cc @rebornix

**Comment by rebornix** [comment]
I guess we miss a mode change listener on the cell.

**Comment by roblourens** [comment]
@rebornix is this the right way to change a cell's language, or should there a way to do it using a workspace edit? The status bar item only reflects what's in the cell model. Should that get set by this when the editor changes?

**Comment by rebornix** [comment]
> is this the right way to change a cell's language, or should there a way to do it using a workspace edit? 
Extensions should be able to use this API to change the language of a cell since it's a text document in ext host. Another use case is opening a notebook document through `openNotebookDocument` and the document is not attached to any editor.

 I wonder if it's a model change or mode change in the main thread since in ext host we get document close/open event. cc @jrieken

**Comment by jrieken** [comment]
This is how you change a language and the test asserts that that works: https://github.com/microsoft/vscode/blob/8d9b2e65bd9281cf467729ec7e39128e21433e2c/extensions/vscode-api-tests/src/singlefolder-tests/notebook.document.test.ts#L341

In the API we send a closed/open-event sequence because that's usually the simplest do consume, e.g you only listen to fooLang-files opening & closing. Internally, the text model fires a mode change event and consumers must listen to that event. I guess that's what's missing here

**Comment by roblourens** [comment]
I can't get this to work. Seems like a TextModel is not kept around unless it is bound to an editor. I run this code from a command

```
const lastCell = activeDoc.cells[activeDoc.cells.length - 1];
vscode.languages.setTextDocumentLanguage(lastCell.document, 'css');
```

When the last cell is scrolled out of view so it's not in an editor. I see a TextModel get created, have its mode set, then it is disposed.

Should we be creating TextModels for all notebook view models when the notebook is opened?

**Comment by jrieken** [comment]
> Should we be creating TextModels for all notebook view models when the notebook is opened?

I think that will become a perf problem. Tho, I think we should monitor when text models came and go and when they are alive we should treat them as source of truth, e.g modification on text models should be reflected in the cell model

**Comment by roblourens** [comment]
Ok but then how do you change the language of a cell that isn't visible?

**Comment by jrieken** [comment]
When using the `setTextDocumentLanguage` API we will [open/create](https://github.com/microsoft/vscode/blob/9fe7b6446dc4742b1a7edf624b93692d781094a6/src/vs/workbench/api/browser/mainThreadLanguages.ts#L43) the document. Notebooks can observe that and start listening on the document until it is closed again

**Comment by roblourens** [comment]
Ok, I'm getting it now. Is there a better way to do this than be notified of `onModelAdded` or `onModelModeChanged` for every single model, and have to check whether it's a model for a notebook cell in this notebook?

**Comment by jrieken** [comment]
> ...better way to do this than be notified of onModelAdded or onModelModeChanged for every single model, and have to check whether it's a model for a notebook cell in this notebook?

I don't think so... Tho, a fast and easy check is to look for the `vscode-notebook-cell`-scheme. That should rule out most models. The `CellUri#parse`-util can then help to know what handle a cell is (and to which notebook the cell belongs)

**Comment by roblourens** [comment]
Oh duh, I can look it up by handle

**Comment by roblourens** [comment]
Pushed more fix based on https://github.com/microsoft/vscode/issues/120284#issuecomment-813905132 and offline conversation.

**Comment by JacksonKearl** [comment]
When I trued to verify using the github issues notebook live shared to another instance of vscode on my same machine, changing the cell type in the source window did not change it in the mirror window.

**Comment by roblourens** [comment]
Should be fixed with #120284, moving to May for verification

**Comment by connor4312** [comment]
Notebooks don't work in liveshare for me, not sure how to verify the bug that Jackson saw: I got a notification that the "participant is not editing a shared document" when in a notebook

**Comment by alyssajotice** [comment]
Hey @connor4312, Live Share support for notebooks is currently not working because it's not caught up to the new VS Code APIs.  I'm working on a fix and it should be done soon.

**Comment by connor4312** [comment]
@alyssajotice can you verify that this is fixed for you when you get a chance? 🙂

**Comment by roblourens** [comment]
Steps: Use the `setTextDocumentLanguage` API on a cell document, see if it updates the UI

**Comment by alyssajotice** [comment]
Just verified this was fixed, thanks!
