### ISSUE TITLE
Jupyter: Use Notebook Editor Setting Issue

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode#117918]
- VS Code Version: 1.53.2
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. There is a setting that allows me to open the json of a Notebook instead of it always open the notebook directly, shown here: 
![image](https://user-images.githubusercontent.com/23587151/109547016-c20d0300-7a7f-11eb-8d34-055dc9b72eba.png)

2. One issue is that in order to see changes that made on the json to the notebook you have to go back to this setting to turn it on and then reload the notebook (by closing it and opening it). 

Why is there not a button or right click option to open as notebook viewer, since this setting is supposed to stop the ipynb file from being directly opened as notebook but the functionality from going from json ipynb to notebook does not seem to be present to me.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
> One issue is that in order to see changes that made on the json to the notebook you have to go back to this setting to turn it on and then reload the notebook (by closing it and opening it).


You can right click on the file from the editor title and click "Reopen with..." to open the document in text editor. This setting is contributed by the Jupyter extension used to control if the ipynb file should be opened in a web view editor, which might not be used with the new native notebook integration. @DonJayamanne can correct me if I was wrong.
