### ISSUE TITLE
Copy + Paste automatically open file in new tab

### ISSUE THREAD

**Issue by kuzlich** [microsoft/vscode#117967]
- VS Code Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

- OS Version: Windows 10 Pro 2004

- Steps to Reproduce:
1. Select files in the folder
2. Ctrl + C to copy the files
3. Open another folder
4. Ctrl + V to paste the files
5. Files open in new tabs

- Expected:
Files were just copied to the folder and did not open in new tabs.

Another [topic](https://github.com/microsoft/vscode/issues/44231) has already been opened on this issue. The last message says that the files are no longer opened after copying, and the issue is already closed.
But the problem still exists. Files continue to open in new tabs after copying. We checked with friends on several computers with Windows 10 and Mac OS.

Maybe I was looking crookedly, but I could not find where to disable this function. Can anyone please help?

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by isidorn** [comment]
I have changed it that we no longer open files when they are pasted.
Let's see if somebody will complain since we actually behaved like this for ages. But I do think that the new behaviour is nicer.

fyi @bpasero

**Comment by isidorn** [comment]
After recieveing negative feedback from users regarding this change I had to revert it.
More about the feedback can be found here https://github.com/microsoft/vscode/issues/120882

Reopening this as a feature request, and if enough users are interested I will add a setting.
