### ISSUE TITLE
Settings editor is losing settings options

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#117952]
Seems like this stopped working... I am trying to call openEditor with a custom EditorOptions subclass. But now seems like options are normalized to just EditorOptions. I don't see any relevant code that looks like it changed recently, do you know what happened?

Btw, in that case, cmd+f will put the cursor back in the search bar. But it makes sense for cmd+, to do that too.

_Originally posted by @roblourens in https://github.com/microsoft/vscode/issues/116167#issuecomment-788372270_

**Comment by bpasero** [comment]
@roblourens the issue is that we now seem to be using this pattern for opening settings:

https://github.com/microsoft/vscode/blob/be9c3901da5248e9cf01ee7f633f2c1408327193/src/vs/workbench/services/preferences/browser/preferencesService.ts#L367-L367

But you need to preserve your original `SettingsEditorOptions` instance so that the options are not lost.

Not sure if this warrants as a candidate, I think this is a recent regression from https://github.com/microsoft/vscode/commit/be9c3901da5248e9cf01ee7f633f2c1408327193

**Comment by lramos15** [comment]
Maybe I'm not understanding the problem. My change should still preserve the original settings and only override the override setting. If you look at the diff before it just doesn't do the object spread and then apply the override.

**Comment by bpasero** [comment]
@lramos15 the difference is this, previously you passed:

```ts
SettingsEditorOptions.create(options) 
```

and now it is 

```ts
{ ...SettingsEditorOptions.create(options), override: EditorOverride.DISABLED } : { override: EditorOverride.DISABLED }
```

So the object you pass over is no longer a typed object (`SettingsEditorOptions`) but a plain old JS object. In that case we only support the generic options, not all of them here:

https://github.com/microsoft/vscode/blob/413963c489fafa5163b5d6513731c7953de07fb3/src/vs/workbench/services/editor/common/editorService.ts#L182-L182

`options?: IEditorOptions | ITextEditorOptions`

**Comment by lramos15** [comment]
Ah, thank you. I think in this case we can safely just modify.create to automatically apply the disabled override to the SettingsEditorOptions object as I can't think of a case where you would want a settings override to be overridden.

**Comment by roblourens** [comment]
I think that's fine. Can you make that change and test it?

**Comment by roblourens** [comment]
This is a candidate because commands like "Open workspace settings" are broken. Will take it over since Logan is in training

**Comment by lramos15** [comment]
If you want a super safe fix you could always revert this fix and I could fix it in the march iteration. As the bug that this fixed wasn't a regression, it's always been there.

**Comment by roblourens** [comment]
In that case, I don't think that change should have gone in on Friday. I guess I signed off on the PR without looking at the issue carefully, and didn't realize that the editor service does an instanceof check here, but the result is that it bypassed all of our testing and verification and introduced a pretty serious regression.

**Comment by lramos15** [comment]
That was my bad, I didn't think it a was a huge fix and the bug seemed pretty annoying so I thought it was still safe to push it in before the branch was made into the release branch. Sorry about that!

**Comment by roblourens** [comment]
Pushed a safe fix, might do more refactoring in main

**Comment by roblourens** [comment]
Things to verify

- Open Workspace Settings command opens the right target
- Right click an extension -> Extension Settings opens with a query
- The "edit in settings.json" button
- https://github.com/microsoft/vscode/issues/116167
