### ISSUE TITLE
Explorer scrolls to top after deleting a file

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#11794]
- VSCode Version: 1.4.0
- OS Version: macOS

**Steps to Reproduce:**

1. Scroll down the list of files in the Explorer and delete a file.
2. Note that the after doing so you lose your scroll position and are sent to the top.

**Desired behavior**
Scroll position should be maintained IMO.  I may want to delete multiple files in the same general area.  So I would need to scroll back to the same spot each time I delete a file.

**Comment by bpasero** [comment]
![editors](https://cloud.githubusercontent.com/assets/900690/18408265/2a574d7e-772b-11e6-9a60-0b504066f8c8.gif)

@bgashler1 I cannot reproduce, do you have steps?

**Comment by bgashler1** [comment]
@bpasero to reproduce, make sure you already have opened a file that is located near the top of the explorer; then open another file located near the bottom of the Explorer.  Once you close the file you're on in near the bottom of the Explorer, then the previous one near the top is revealed (and hence the scroll behavior).  IMO, I'm not sure we want to have it auto scroll up to the previous file.  Users can do that manually if they want.  In my case, deleting a lot of files was challenging because of the autoscroll.

**Comment by bpasero** [comment]
Try `"explorer.autoReveal": true`
