### ISSUE TITLE
Unable to sign in to github from VSCode

### ISSUE THREAD

**Issue by RossBoylan** [microsoft/vscode#117926]
Issue Type: <b>Bug</b>

After installing gitlens I hit a point where it said it could provide more info if I logged in to github.  I said yes, and when it proceeded it launched Konqueror.

1. Konqueror is not my default browser; I don't think it should have been launched at all.  I'm running KDE, which might have something to do with why it was chosen.  My default is Firefox.

2. At the initial screen in Konqueror it showed a message that Konqueror was not a supported browser.  I filled in the other information it requested, but after giving it my credentials I got a blank or error screen.

Later the account icon on the left shows a 1; clicking on it asked me again if I wanted to let VSCode access github; I said yes and got Konqueror again.  There was no message about it being unsupported.  I signed in again, and this led to a blank screen (in the browser).  When I used the back button I got this message:
```

Success!
Authorization was successful. You will be redirected back to Visual Studio Code

Didn't work?
If you aren't redirected, you can add the token manually.

Your authorization token:

vscode://vscode.github-authentication/did-authenticate?windowid=1&code=xxx&state=yyy
✅ Copied
Copy the token.
Switch back to VS code.
Click Signing in to github.com... in the status bar.
Paste the token and hit enter.
```
I did so, but I still see the error "Sign in failed: Error: Unauthorized" in my notifications and the blue "1" on the accounts icon on the left.  When I click it it says I'm not signed into any accounts.

I have more than one github account, which might be part of the problem.

I'm guessing this is a VSCode issue, but it might be from an extension.
Disabling the extensions is not a practical test, since if I do that I assume I will have no access to github.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 4.19.0-14-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 6|
|Memory (System)|31.35GB (0.40GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
language-julia|jul|1.1.31
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
vscode-yaml|red|0.15.0
pdf|tom|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30264244

```

</details>

**Comment by RMacfarlane** [comment]
@deepak1556 Any ideas why the default browser wouldn't be opened? The auth provider uses the `openExternal` API, which should just call `shell.openExternal` from electron. 

@RossBoylan Can you try this again and copy any output from the "GitHub Authentication"  output channel?

**Comment by deepak1556** [comment]
@RossBoylan what browser does `xdg-open https://github.com`  open on your system ?

**Comment by RossBoylan** [comment]
Clicked accounts icon on lower left of VSCode.
Selected "Sign in to use GitLens".

A notification popped up on my desktop; when I clicked on it (which I don't think I did before) it opened Konqueror.
If the opening is being done by KDE's notifications, that might explain why KDE's Konqueror is getting used.  It still strikes me as an error, but that's more a desktop configuration issue.  Not sure if it defaults to opening after a long enough non-response, or if it was unknowingly hitting it before (because it grabbed focus).

Every time something different happens in the browser.  This time it immediately said

> Oh no! An error occurred!
> Please restart the sign in process from the editor.
> 
> Invalid URL:

The URL for the page is https://vscode-auth.github.com/authorize/?callba...&responseType=code&authServer=https://github.com.  I'm not sure what's up with the ... after callba; that's what's showing, not my shorthand.

Finally, here's the log for GitHub authentication:
```
[Info  - 18:55:56.339] Logging in...
[Info  - 20:38:18.189] Logging in...
[Info  - 20:40:11.649] Exchanging code for token...
[Info  - 20:40:11.652] Exchanging code for token...
[Info  - 20:40:13.861] Token exchange success!
[Info  - 20:40:13.888] Token exchange success!
[Info  - 20:40:13.888] Getting user info...
[Error  - 20:40:15.961] Getting account info failed: Unauthorized
[Error  - 20:40:15.962] Error: Unauthorized
[Info  - 22:07:27.659] Logging in...
```
Times are presumably UTC, and it includes my earlier attempts.
@deepak1556 xdg-open gets my Konqueror; it also shows a notification on my desktop.
x-www-browser opens Firefox without notification on desktop.

**Comment by deepak1556** [comment]
The electron api which vscode uses to open external application uses `xdg-open` on linux, hence the above behavior. This is not something vscode can control. Can you change the default browser via `xdg-settings` as a workaround ?

**Comment by RossBoylan** [comment]
I went into KDE settings and set the default application for the web to be Firefox.  It was previously "automatic".

xdg-open now gets FF.

Now I get to this page
```

Success!

Authorization was successful. You will be redirected back to Visual Studio Code
Didn't work?

If you aren't redirected, you can add the token manually.
Your authorization token:
vscode://vscode.github-authentication/did-authenticate?windowid=1&code=xxx&state=yyy
✅ Copied

    Copy the token.
    Switch back to VS code.
    Click Signing in to github.com... in the status bar.
    Paste the token and hit enter.
```
(as before I've obscured the values for code and state) and it asked me if I wanted to open a link to VSCode.  When I said yes I got a prompt for my password (local I think, for my secrets store) and apparent success.  More from the GitHub Authentication channel:
```
[Info  - 22:23:26.77] Logging in...
[Info  - 22:30:36.499] Logging in...
[Info  - 22:31:12.494] Exchanging code for token...
[Info  - 22:31:14.923] Token exchange success!
[Info  - 22:31:14.923] Getting user info...
[Info  - 22:31:14.924] Getting user info...
[Info  - 22:31:14.924] Getting user info...
[Info  - 22:31:16.327] Got account info!
[Info  - 22:31:16.345] Got account info!
[Info  - 22:31:16.347] Got account info!
[Info  - 22:31:24.465] Login success!
[Info  - 22:31:24.495] Login success!
[Info  - 22:31:24.557] Login success!
[Info  - 22:31:24.560] Removing session no longer found in keychain
[Info  - 22:31:24.560] Removing session no longer found in keychain
```
I'm not sure what's up with the "Removing session" messages, but I think I'm now connected.  The account icon no longer is showing a 1 with a blue circle around it, and it is showing my github account.

If my immediate problem is solved, I'll leave it to you to decide if any changes to VSCode to avoid this for others is in order.

**Comment by deepak1556** [comment]
Thanks for confirming, @RMacfarlane we can't change the behavior of openexternal. Closing the issue as such.
