### ISSUE TITLE
VS Code is running as root on macOS

### ISSUE THREAD

**Issue by larstomas** [microsoft/vscode#117959]
Hi,

I don't know if this is a bug, but here is it.

A few VS Code files inside my home library directory are owned by root. It dosen't look good.

MYUSERNAME@ronja ~ $ sudo find Library/Application\ Support/Code \! -user MYUSERNAME -exec stat {} \;
16777221 32305426 drwx------ 9 root staff 0 288 "Jan 19 10:54:10 2020" "Jan 19 07:40:09 2020" "Jan 19 07:40:09 2020" "Jan 19 07:40:06 2020" 4096 0 0 Library/Application Support/Code/Cache
16777221 32305428 drwx------ 3 root staff 0 96 "Jan 19 10:54:11 2020" "Jan 19 07:40:30 2020" "Jan 19 07:40:30 2020" "Jan 19 07:40:06 2020" 4096 0 0 Library/Application Support/Code/Cache/index-dir
16777221 32305673 -rw------- 1 root staff 0 168 "Jan 19 09:37:35 2020" "Jan 19 07:40:30 2020" "Jan 19 07:40:30 2020" "Jan 19 07:40:30 2020" 4096 8 0 Library/Application Support/Code/Cache/index-dir/the-real-index
16777221 32305434 -rw------- 1 root staff 0 5142 "Jan 19 09:37:35 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" 4096 16 0 Library/Application Support/Code/Cache/533a4ba6b465484d_0
16777221 32305429 -rw------- 1 root staff 0 7630 "Jan 19 09:37:35 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" 4096 16 0 Library/Application Support/Code/Cache/cbc42e4c979f69f0_0
16777221 32305441 -rw------- 1 root staff 0 10135881 "Jan 19 09:37:35 2020" "Jan 19 07:40:10 2020" "Jan 19 07:40:10 2020" "Jan 19 07:40:09 2020" 4096 21800 0 Library/Application Support/Code/Cache/26531fc1180f857e_0
16777221 32305427 -rw------- 1 root staff 0 24 "Jan 19 10:54:11 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" 4096 8 0 Library/Application Support/Code/Cache/index
16777221 32305440 -rw------- 1 root staff 0 1526429 "Jan 19 09:37:35 2020" "Jan 19 07:40:09 2020" "Jan 19 07:40:09 2020" "Jan 19 07:40:09 2020" 4096 2984 0 Library/Application Support/Code/Cache/3ca3e19c17f46dce_0
16777221 32305433 -rw------- 1 root staff 0 8025 "Jan 19 09:37:35 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" 4096 16 0 Library/Application Support/Code/Cache/024851657a48ee65_0
16777221 32305400 drwxr-xr-x 4 root staff 0 128 "Jan 19 10:54:12 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:04 2020" 4096 0 0 Library/Application Support/Code/User/workspaceStorage/1579416003803
16777221 32305678 -rw-r--r-- 1 root staff 0 12288 "Jan 19 09:37:35 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:34 2020" 4096 24 0 Library/Application Support/Code/User/workspaceStorage/1579416003803/state.vscdb.backup
16777221 32305402 -rw-r--r-- 1 root staff 0 12288 "Jan 19 07:40:34 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:34 2020" "Jan 19 07:40:04 2020" 4096 24 0 Library/Application Support/Code/User/workspaceStorage/1579416003803/state.vscdb
16777221 32307080 -rw------- 1 root staff 0 3357 "Jan 19 09:37:36 2020" "Jan 19 07:47:32 2020" "Jan 19 07:47:32 2020" "Jan 19 07:47:32 2020" 4096 8 0 Library/Application Support/Code/Network Persistent State
16777221 32305383 drwxr-xr-x 9 root staff 0 288 "Jan 19 10:54:13 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:03 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003
16777221 32305424 -rw-r--r-- 1 root staff 0 0 "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" "Jan 19 07:40:06 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/userDataSync.log
16777221 32305423 -rw-r--r-- 1 root staff 0 1833 "Jan 19 07:47:33 2020" "Jan 19 07:40:46 2020" "Jan 19 07:40:46 2020" "Jan 19 07:40:06 2020" 4096 8 0 Library/Application Support/Code/logs/20200119T074003/sharedprocess.log
16777221 32305417 drwxr-xr-x 4 root staff 0 128 "Jan 19 10:54:13 2020" "Jan 19 07:40:05 2020" "Jan 19 07:40:05 2020" "Jan 19 07:40:05 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/exthost1
16777221 32305419 drwxr-xr-x 3 root staff 0 96 "Jan 19 10:54:13 2020" "Jan 19 07:40:05 2020" "Jan 19 07:40:05 2020" "Jan 19 07:40:05 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/exthost1/output_logging_20200119T074005
16777221 32305420 -rw-r--r-- 1 root staff 0 181 "Jan 19 10:54:13 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:05 2020" 4096 8 0 Library/Application Support/Code/logs/20200119T074003/exthost1/output_logging_20200119T074005/1-Git.log
16777221 32305418 -rw-r--r-- 1 root staff 0 3243 "Jan 19 09:37:36 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:07 2020" "Jan 19 07:40:05 2020" 4096 8 0 Library/Application Support/Code/logs/20200119T074003/exthost1/exthost.log
16777221 32305411 drwxr-xr-x 4 root staff 0 128 "Jan 19 07:40:05 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/output_1_20200119T074004
16777221 32305415 -rw-r--r-- 1 root staff 0 0 "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/output_1_20200119T074004/extensions.log
16777221 32305414 -rw-r--r-- 1 root staff 0 0 "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/output_1_20200119T074004/tasks.log
16777221 32305401 -rw-r--r-- 1 root staff 0 0 "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" "Jan 19 07:40:04 2020" 4096 0 0 Library/Application Support/Code/logs/20200119T074003/renderer1.log
16777221 32305425 -rw-r--r-- 1 root staff 0 249 "Jan 19 07:47:33 2020" "Jan 19 07:40:08 2020" "Jan 19 07:40:08 2020" "Jan 19 07:40:06 2020" 4096 8 0 Library/Application Support/Code/logs/20200119T074003/telemetry.log
16777221 32305387 -rw-r--r-- 1 root staff 0 199 "Jan 19 07:47:33 2020" "Jan 19 07:40:35 2020" "Jan 19 07:40:35 2020" "Jan 19 07:40:03 2020" 4096 8 0 Library/Application Support/Code/logs/20200119T074003/main.log

**Comment by bpasero** [comment]
If you start VSCode as root (not recommended), then it is possible that files in the `user-data-dir` or `extensions-dir` are written to with the privileges of the user you are. I am not sure what else we could do then?

**Comment by larstomas** [comment]
I'm not intentionally running VSCode as root. That's why I thought this was strange. 

Can't say that I never have started VSCode as root. If you don't want to investigate this more it is fine with me to close this issue.
