### ISSUE TITLE
Allow Spaces While Creating User Snippets

### ISSUE THREAD

**Issue by Rishi0812** [microsoft/vscode#117919]
Hey,

Could you please allow the user to use spaces while creating user snippets inside quotes "",
This feature would be very useful especially for languages that use indentations, like python.

Thank You

**Comment by jrieken** [comment]
> Could you please allow the user to use spaces while creating user snippets inside quotes "",

I don't know what that means

**Comment by ArturoDent** [comment]
@Rishi0812 You can use spaces in snippets or `\n` or better `\t` to add indentation.  Is that what you mean?  

from https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

> Newlines and embedded tabs will be formatted according to the context in which the snippet is inserted.

**Comment by Rishi0812** [comment]
> @Rishi0812 You can use spaces in snippets or `\n` or better `\t` to add indentation. Is that what you mean?
> 
> from https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets
> 
> > Newlines and embedded tabs will be formatted according to the context in which the snippet is inserted.

**Comment by Rishi0812** [comment]
Yes @ArturoDent, Thank You very much!
