### ISSUE TITLE
Show errors from OpenerService

### ISSUE THREAD

**Issue by Mlocik97** [Microsoft/vscode#11802]
- VSCode Version: 1.5.1
- OS Version: Win 8.1

Steps to Reproduce:

https://youtu.be/D4lLsrKR9q8

1. I can not be redirected to a link when i use "ctrl + left click" (i cant follow link)...
2. When i use tab to complete, cursor is at the end of the line, in old version it was in "value".

> **iframe src=""|**
> **iframe src="|"**

| = cursor

**Comment by mrmlnc** [comment]
See #11763 and #11742.

**Comment by ramya-rao-a** [comment]
@Mlocik97 Like @mrmlnc has mentioned above your second issue is already being tracked.

Regarding your first issue, I notice that all the links you tried in your example are local files. Did this ever work for you before? I don't think this was ever supported.

**Comment by Mlocik97** [comment]
This link to local files work, only this 1.5.1 dont work.

**Comment by ramya-rao-a** [comment]
@Mlocik97 Thanks for the videos! That helps.

**Comment by alexandrudima** [comment]
The file gets opened if it exists. 

If it doesn't exist, the workbench used to show an error with an action to create the file. It no longer shows anything (which makes us think that ctrl+clicking is broken).

Giving to @bpasero to confirm if this is an intentional change and what the story is now with following links to missing files.

**Comment by bpasero** [comment]
Looks like opening links now goes through the opener service which seems to swallow errors: https://github.com/Microsoft/vscode/blob/master/src/vs/platform/opener/browser/openerService.ts#L48

**Comment by Mlocik97** [comment]
I can not click even if there is.

**Comment by Mlocik97** [comment]
When You fix it?

**Comment by ramya-rao-a** [comment]
@Mlocik97 This is fixed in the insiders version. You can either wait for VS Code 1.6.0 that should release some time next week or you can try out our insiders build from http://code.visualstudio.com/insiders

**Comment by Mlocik97** [comment]
thanks
