### ISSUE TITLE
Code on Fedora 33 armhfp

### ISSUE THREAD

**Issue by gbraad** [microsoft/vscode#118016]
- VS Code Version: 1.53.2
- OS Version: Fedora 33 (armhfp)

Steps to Reproduce:

0. get the distro from here: https://arm.fedoraproject.org

1. yum install code*.el7.armv7hl.rpm

1. `--nodeps`
2. `code`

1. you can yum install the dependencies manually, like libdrm, mesa-libgbm, libxkbfile, and about 30 other packages, but this is what not is supposed to happen. Even with this exercise it will segfault.

Does this issue occur when all extensions are disabled?: Yes/No
yes

Hi, I have tried to install the Armv7 release of both code as codium on my Fedora 33 installs (on an Arm rockchip based device), but for some reason it won't pull in dependencies/nothing is satisfied. Forcing the install with nodeps or unpacking the tarball will result in a segfault when trying to run. What is this package meant for?

Note; I have no issues running the release for aarch64 on another device

**Comment by gbraad** [comment]
So I am guessing just now what you might be doing; the code is built for armhfp on some kind of distro and a set of dependent libraries, this is tarballed and repackage as an RPM. So they are both the same binary, but not linked for the distro, hence the very generic dependencies to .so ?

**Comment by deepak1556** [comment]
\closedWith d572d6e9d1282b352227916cb8f95bb2b03ddcaa
