### ISSUE TITLE
Drag indicator wrong position in custom markdown renderer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#118002]
- VS Code Version: 1.54-Insiders
- OS Version: macOS

Steps to Reproduce:

1. enable custom markdown renderer `"notebook.experimental.useMarkdownRenderer": true`
2. drag and drop on different cells
3. it doesn't seem to happen in builtin markdown renderer

https://user-images.githubusercontent.com/876920/109735591-e0eec080-7b77-11eb-9626-1b4cbbc8404e.mov

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rzhao271** [comment]
Reopening because when I try to drag and drop, the entire screen has a semi-transparent overlay, as though I wanted to tile or snap something to half of the editor screen.

**Comment by mjbvz** [comment]
Should be fixed by f122b1096cfbd175930f74f1542694c822c5888a
