### ISSUE TITLE
Scrolling on wayland after moving mouse ignores first scroll event

### ISSUE THREAD

**Issue by WebFreak001** [microsoft/vscode#118057]
When moving the mouse on wayland (using KDE Plasma) the first scroll on the scrollwheel is ignored.

This causes the weird behavior that you can't scroll while moving the mouse. Might be an electron bug though.

VS Code version: Code - OSS 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T21:13:58.622Z)
OS version: Linux x64 5.11.1-zen1-1-zen

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|31.35GB (1.48GB free)|
|Process Argv|served-workspaced.code-workspace --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|plasmawayland|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by deepak1556** [comment]
Can you try launching the app with `--enable-features=UseOzonePlatform --ozone-platform=wayland` and verify. Thanks!
