### ISSUE TITLE
Output channel doesn't show editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118010]
I know I've seen this for awhile, but I think I've started seeing it more often recently. Don't really have good repro steps.

- Open a new window
- Open an output channel
- It's empty and there is no editor
- Hide and show the panel
- Now it shows up

![recording (3)](https://user-images.githubusercontent.com/323878/109751189-c7a73d80-7b92-11eb-8b45-fb2eb229a8e6.gif)

**Comment by zhfnjust** [comment]
yes we  have meet the same bug  https://github.com/microsoft/vscode/issues/117957
