### ISSUE TITLE
The commit message in the Source Control section displays permanently

### ISSUE THREAD

**Issue by kuzlich** [microsoft/vscode#118025]
- VS Code Version: 1.53.2
- OS Version: MacOS Catalina 10.15.7

After upgrading to version 1.53.2, in the Source Control section, the commit message field is displayed even if there are no changes in the repository. Previously, folders were expanded only when there were changes in them and something needed to be synchronized.

This doubles the list of repositories and gets in the way. Is it possible somewhere in the settings to return the previous view of the folders in the Source Control section, or is it a bug?

Steps to Reproduce:

1. Upgrade to version 1.53.2
2. Open Source Control in VSC
3. Surprised at the number of open folders. o_O

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/114396#issuecomment-761111271

**Comment by kuzlich** [comment]
> See [#114396 (comment)](https://github.com/microsoft/vscode/issues/114396#issuecomment-761111271)

I missed the old thread, but apparently, people there also complain about it.
It is a pity that the usual view was turned off, and no options were left for returning the old functionality. Empty commits are a rare event, and now my repositories do not fit on the screen. This is very inconvenient and noticeably overloads the interface.
