### ISSUE TITLE
Issue with HTML

### ISSUE THREAD

**Issue by markcoxsmith** [microsoft/vscode#118033]
Issue Type: <b>Bug</b>

1. Try to run an HTML file with my current configuration.

ER: Runs the HTML file

AR: No longer works and I get a message saying that the language is not supported

Note: This was working until very recently

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f045b034-fc5e-4799-b322-84267a45b51f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
csharp|ms-|1.23.9
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
vsliveshare|ms-|1.0.3784
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
quokka-vscode|Wal|1.0.343
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by markcoxsmith** [comment]
Resolved the issue

**Comment by aeschli** [comment]
Not sure what you mean by `Run the HTML file`.
Can you give the steps (What command to run, what button to click)?

**Comment by markcoxsmith** [comment]
Sorted it now - not actually an issue. 

For visibility, was just thrown by the message when running an HTML file saying that the language is not supported which I just hadn't noticed before. Definitely feel there could be a UX improvement here as I believe this just means that you can't run the file directly in VSCode. This could potentially reduce confusion.
