### ISSUE TITLE
Tasks should be marked as stopped when pty host becomes unresponsive

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#118073]
In OSS I very often have the PTY host freeze a few seconds after switching between workspaces. If I F5 to start debugging before this happens, the watch task terminal is created and (though it's marked as `disconnected`) I need to manually close it in order to start debugging again.

We should mark them as 'stopped', or even automatically close them, when the pty host is restarted.

**Comment by Tyriar** [comment]
I indicated they were disconnected as I was concerns about outright closing them. I think you're right that they don't fire an exit event though. Only the "disconnected" title label is added and stdin is disabled:

https://github.com/microsoft/vscode/blob/cf3faa404605db2e613a99da38000e1c1b2bd2fe/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L946-L950

**Comment by Tyriar** [comment]
I'm going to exit with undefined for all feature terminals so they can react properly:

<img width="686" alt="Screen Shot 2021-03-19 at 7 40 22 AM" src="https://user-images.githubusercontent.com/2193314/111797472-6ebff080-8886-11eb-97d3-3aa8b0a5f5f4.png">

Tasks will continue running when the pty host is unresponsive and only completely go away when it is _restarted_.

**Comment by connor4312** [comment]
I thought this was fixed but am seeing it still in OSS

![](https://memes.peet.io/img/21-03-44f1ab9b-f2db-4d10-9d55-4cb9535ad90a.png)

After restart:

![](https://memes.peet.io/img/21-03-d4bc96de-a1e1-42d0-88d7-f3f2f9172193.png)

**Comment by connor4312** [comment]
I hit this again today

**Comment by Tyriar** [comment]
I think this is fixed, Windows pty host unresponsiveness is also fixed

**Comment by connor4312** [comment]
I've not seen this for a couple weeks, thus marking verified
