### ISSUE TITLE
Use custom hover for activity bar tooltip

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#118077]
![Kapture 2021-03-03 at 13 31 26](https://user-images.githubusercontent.com/35271042/109875078-d1798100-7c24-11eb-905a-205803583a06.gif)

I think one of the areas that could benefit from quicker tooltips/custom hovers is the activity bar as it is a frequently used area and the native tooltip takes too long to load. We've seen this in user studies where new users are not sure what these items are and don't click on them.

cc @bpasero @alexr00

**Comment by digitarald** [comment]
Love the direction. I could not if browser tooltips had UX revisions; and most web-based apps I use replaced tooltips with custom tooltips to make them feel well integrated.

It should probably hook into the theming colors; which I think your mockup considers. The result will

To make it feel snappier, a common pattern that can be found in the wild is to not fade the tooltip in/out when moving between buttons that are aligned next to each other (horizontal & vertical). Figma as an example:
![recording(1)](https://user-images.githubusercontent.com/8599/109892072-1dd1ba80-7c3f-11eb-9790-f3cd03d86dcd.gif)

Since they will be HTML, it's an opportunity to think about a multi-line layout that breaks out the shortcut on a new line and maybe even leaves room for an additional one-liner that explains the feature.

**Comment by misolori** [comment]
Right, I think we've discussed this approach as Chrome does this on tabs as well, the first tooltip fades in and then as you move around the rest are instantly shown. I think @alexr00 looked into this?

**Comment by sana-ajani** [comment]
This was a more agreed upon idea when last brought up at a UX sync, instead of having labels under activity bar icons: https://github.com/microsoft/vscode/issues/104452#issuecomment-677451408

**Comment by digitarald** [comment]
> The first tooltip fades in and then as you move around the rest are instantly shown.

Right, Chrome tab hover cards even transitioning from one to the next tab.

![recording(2)](https://user-images.githubusercontent.com/8599/109909280-ad389700-7c5a-11eb-9653-3ad53af315b1.gif)

There are some animation best practices out there about this, but not sure if this one is too distracting, delightful, or actually a cognitive benefit. I personally am a fan of delightful animations that encourage exploration and don't get in the way of productivity.

**Comment by bpasero** [comment]
> Right, I think we've discussed this approach as Chrome does this on tabs as well, the first tooltip fades in and then as you move around the rest are instantly shown. 

Isn't that pretty much standard hover behaviour even with native ones? When the hover appears and I move my mouse to another location with a hover, the hover should appear instantly and not require another delay. The delay is only useful to not bring up the hover too quickly when the user moves the mouse.

**Comment by misolori** [comment]
@bpasero yes that is standard native behavior but our custom hover does not behave this way.

**Comment by misolori** [comment]
@sandy081 thoughts on moving this to April?

**Comment by digitarald** [comment]
I am ready to help run this as experiment to learn how improving UI affordance enhances the experience for new users.

**Comment by sandy081** [comment]
Sure, will look at this in April.

**Comment by sandy081** [comment]
Created the PR implementing this

![Kapture 2021-04-14 at 15 56 39](https://user-images.githubusercontent.com/10746682/114722424-16232c80-9d3a-11eb-96f0-7b4bbe7bcf77.gif)

**Comment by alexr00** [comment]
@sandy081 not sure if you're using it already, but there is a setting for the hover delay that should probably be used for the hovers you are changing `workbench.hover.delay`.

**Comment by Tyriar** [comment]
I think the quick hover was intentional here. 

I love the activity bar but not so much the panel ones as it's mostly repeating information and getting in the way.

**Comment by sandy081** [comment]
@alexr00 Thanks for mentioning about it. I have seen its usage but went without using it for quick hover as @Tyriar mentioned.

Re using hover delay in panel, went with consistency in activity bar and panels.

**Comment by sana-ajani** [comment]
Thoughts on using this to potentially rename the gear icon from "Manage" to "Settings" or "Preferences"? This is generally more common in apps like Edge, Slack, and Chrome as well.

**Comment by sandy081** [comment]
There is an ask to make this as an experiment and check and measure if this improves the experience. Any thoughts about making this default or change it to an experiment before making it default?

**Comment by sana-ajani** [comment]
Since we saw many users in the getting started user studies often hovering icons and clicking through menus, I think it could be useful to roll this out as an experiment to measure how much more engagement with the activity bar we see, and if it improves the new user experience specifically.

**Comment by Tyriar** [comment]
> Re using hover delay in panel, went with consistency in activity bar and panels.

Imo we should consistently show the hover near instantly for textless actions, and consistently use the workbench delay for actions with text.

**Comment by bpasero** [comment]
+1 on only showing the hover on a delay that is configurable.

**Comment by eamodio** [comment]
> Imo we should consistently show the hover near instantly for textless actions, and consistently use the workbench delay for actions with text.

I mostly agree though I might make an exception for the panel headers because of the shortcut key visibility.

Makes me also want this for all actionbar icons too.

**Comment by sandy081** [comment]
Here is how it behaves when uses default workbench hover delay

![Kapture 2021-04-14 at 21 33 10](https://user-images.githubusercontent.com/10746682/114768567-551ca680-9d69-11eb-8f12-954f00e95ff0.gif)

I prefer instant hover than this. Let me know others opinions and I can change accordingly.

Also please let me know if you want custom hovers as default or behind the experiment?

**Comment by eamodio** [comment]
I like the instant hover.

**Comment by sandy081** [comment]
Reopening it for discussion as it seems some of us does not like it

**Comment by jrieken** [comment]
For me there are two problems with the custom hover

* it shows to quickly
* it always shows at the same position, doesn't respect my relative mouse position and that makes it very alien

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/issues/121354:

* it should not use the custom hover unless there is a good reason (e.g. do we show markdown in there?)
* it should have a configurable color so that I have a way to disable it if I don't like it

The native hover seems to work well so far:

![image](https://user-images.githubusercontent.com/900690/114833417-d9a21000-9dcf-11eb-96c3-d65c04a7ac1a.png)

**Comment by eamodio** [comment]
I really like the new hovers, though I would recommend a very short delay -- just to avoid them showing up while the mouse is moving, but still very quickly. Similar to Slack's workspace bar.

I also really like that those hover go along with the theme now. Are we using a new theme color for the hover feedback? As I would like to theme that to look better.

![image](https://user-images.githubusercontent.com/641685/114918973-b4c09380-9df5-11eb-9af7-c4471070578a.png)

**Comment by eamodio** [comment]
Also it would be great if we could render the shortcut keys better now, again maybe similar to Slack's 
![image](https://user-images.githubusercontent.com/641685/114919431-3a444380-9df6-11eb-8c9a-0a2b6151b7f6.png)

**Comment by eamodio** [comment]
It seems like there is some unwanted flicker on the activity bar
![flicker](https://user-images.githubusercontent.com/641685/114963951-cfb5f680-9e3b-11eb-911a-64f88a5fe44f.gif)

**Comment by sandy081** [comment]
> it shows to quickly

Will introduce or reuse the delay setting.

> it always shows at the same position, doesn't respect my relative mouse position, and that makes it very alien

Right. We can make them position like native hovers. Personally I liked how it is currently and is also suggested as req. I will collect more feedback before getting to this.

> it should not use the custom hover unless there is a good reason

Reason is mentioned in the summary of the issue - just mentioning it again here

_I think one of the areas that could benefit from quicker tooltips/custom hovers is the activity bar as it is a frequently used area and the native tooltip takes too long to load. We've seen this in user studies where new users are not sure what these items are and don't click on them._

> it should have a configurable color so that I have a way to disable it if I don't like it

I do not know if hovers can be theme-able - @Tyriar ?

> Also it would be great if we could render the shortcut keys better now, again maybe similar to Slack's

**Comment by jrieken** [comment]
> Right. We can make them position like native hovers. Personally I liked how it is currently and is also suggested as req. I will collect more feedback before getting to this.

Now that someone has mentioned slack: I think they do better job because their "button-hover" is so different from the native hover that you don't get the confused feeling that the "native, not-native hover" is wrong.

**Comment by sandy081** [comment]
Introduced slight delay for showing custom hovers on activity bar/panel.

**Comment by misolori** [comment]
Trying this out after being gone for a week, I definitely like the hover feedback. However, it seems like there are a few things that could be improved for all hovers and not specific to the activity bar:

- The hover text is really large, especially when there's extra text in the title
  <img width="400" src="https://user-images.githubusercontent.com/35271042/115262856-c0f46b80-a0e9-11eb-92e0-327507e50335.png">
- It can be hard to tell where the hover is coming from when there is no "arrow" that is common in tooltips like
  <img width="300" src="https://user-images.githubusercontent.com/35271042/115263033-ed0fec80-a0e9-11eb-88bd-91a4924ca0b0.png">
  <img width="200" src="https://user-images.githubusercontent.com/35271042/115263170-0ca71500-a0ea-11eb-96f8-47d3cddf130c.png">

Since this hover is inheriting the default styles from the editor hover, I'd like to propose a different styling for non-editor hovers (we can also move this feedback into a separate issue):

<img width="400" src="https://user-images.githubusercontent.com/35271042/115265302-f39f6380-a0eb-11eb-88f2-2a13a718a20c.png">

**Comment by Tyriar** [comment]
A similar "flicker" also happens in the explorer.

> Now that someone has mentioned slack: I think they do better job because their "button-hover" is so different from the native hover that you don't get the confused feeling that the "native, not-native hover" is wrong.

> I do not know if hovers can be theme-able

Not yet, though I think we should have 2 different styles, maybe with a little arrow and/or the fade in animation to differentiate it. Then center the hover and for the panel put them on the top like this:

![image](https://user-images.githubusercontent.com/2193314/115265500-247f9880-a0ec-11eb-9488-2221843fe55f.png)

**Comment by sandy081** [comment]
As requested by @digitarald and @sana-ajani I moved custom hovers behind an experimental flag. So they are off by default and you can enable it using the setting `workbench.experimental.useCustomHover`.

I liked the suggestions provided by @misolori  and @Tyriar - will try to implement that in this milestone.

**Comment by digitarald** [comment]
@sandy081 the animation in https://github.com/microsoft/vscode/issues/118077#issuecomment-790194019 (which also applies to native tooltips) does not fade in and out while hovering between aligned buttons:

![recording(1)](https://user-images.githubusercontent.com/8599/109892072-1dd1ba80-7c3f-11eb-9790-f3cd03d86dcd.gif)

Would it be possible to not drop this affordance with custom tooltips, as we see a lot of users hovering across toolbars to quickly scan for specific features?

**Comment by pixieaka** [comment]
@sandy081 I have noticed this blue line in the left when mouse down only in file icon and this doesn't shows in the other icons. (0310f02)

![image](https://user-images.githubusercontent.com/17777237/115838239-bf90af00-a419-11eb-870f-da481c71db6a.png)

**Comment by sandy081** [comment]
@pixieaka  Can you please file a separate issue for it?

**Comment by misolori** [comment]
@pixieaka posting here as well, but the blue line is the focus state in the activity bar. If you tab into the activity bar you'll see the same thing so this by design.

**Comment by sandy081** [comment]
Did some improvements based on received feedback

![Kapture 2021-04-26 at 15 13 55](https://user-images.githubusercontent.com/10746682/116063059-23c5a400-a6a2-11eb-956f-23fd107e0c2b.gif)

**Comment by sandy081** [comment]
Closing this issue and will track any feedback in separate issues.
