### ISSUE TITLE
More flexible refactorings not included when code actions are manual triggered

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#118087]
1. For the TS:

```ts
const a = 123 + 456
```

2. Select `23 + 456` (don't select the `1`)
3. There should not be a lightbulb
4. Now request code actions using `ctrl+.`

**Bug**
No refactorings show up. 

Instead you have to run the refactoring command to get these refactorings

**Comment by RMacfarlane** [comment]
@mjbvz I see "No code actions available", what are the expected refactorings?

**Comment by mjbvz** [comment]
Oh forgot to note that you also have to be using TS@4.3+. Just `yarn add typescript@next` and then switch to the workspace version of TS
