### ISSUE TITLE
Scrollbar instead of overview ruler

### ISSUE THREAD

**Issue by aloispichler** [microsoft/vscode#118029]
Clicking the overview ruler positions the cursor at the absolute position within the document.
I am used to _page-up/ page-down_ when clicking in the scrollbar, rather than jumping to the clicked location.

So it would be nice to have a _scrollbar_ instead of the _overview ruler_.
Or did I really miss this in the settings?

Thank you!

**Comment by gjsjohnmurray** [comment]
Adding the unlisted setting `"editor.scrollbar.scrollByPage": true` to your user settings and restarting VS Code makes the **editor** scrollbar and minimap scroll by page when clicking above or below the slider. See #104923

**Comment by aloispichler** [comment]
Great! Very helpful, thank you indeed!
