### ISSUE TITLE
[BUG?] cursor jumped with expandLineSelection

### ISSUE THREAD

**Issue by kockok** [microsoft/vscode#118015]
- VS Code Version: the latest
- OS Version: the latest

Steps to Reproduce:

I think it's related to [this](https://github.com/microsoft/vscode/issues/95069#issue-598579725) issue and it's not yet solved.

1. press command + L
2. the cursor just jumped to the next line whilst the cursor should stay at the end of the selected line!

I don't know if it's intended to move the cursor to the next line, and I think it shouldn't do so.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
This works as designed. <kbd>Command</kbd>+<kbd>L</kbd> will select also the newline character at the end of the line, so the cursor will be positioned on the next line.

![image](https://user-images.githubusercontent.com/5047891/120855503-db41b600-c57e-11eb-99bc-3962716c5618.png)
