### ISSUE TITLE
Quick input should use a focus outline like the normal list

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#118079]
Refs: #117007

We recently added a nice focus outline to the lists, but the quick input isn't taking advantage of them.

**Comment by joaomoreno** [comment]
This is purposeful, because it's the input box that actually has focus. I don't think we should make it look like the list has focus. IMO it just behaves like the suggest widget (text editor has the actual focus, list just shows a background color).

I don't think this should be done.

**Comment by TylerLeonhardt** [comment]
Yeah I agree with @joaomoreno. The actual thing that has focus is the input. I'm gonna close this since there hasn't been much activity.
