### ISSUE TITLE
Search editor should continue searching when switching tabs

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#118050]
- VS Code Version: 1.53.2 (user setup) (622cb03f7e070a9670c94bae1a45d78d7181fbd4)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. open a search editor, do a search & let it finish
2. do another search, but before it finishes switch to another tab (or open a new file)
3. switch back to the search editor

There are several issues, as demonstrated in the demo below.
1. when entering the search query `maven`, the name of the search editor's tab isn't updated
2. when switching to another tab, the blue bar keeps running, which gives the impression that the search is continuing in the background
3. when switching back to the search editor eventually, the search query has reverted to the original value
4. also, even after switching back, the blue bar still keeps running, and it takes a long time before it disappears & the user realises that their search query hasn't executed

![issue](https://user-images.githubusercontent.com/15714253/109839543-7c9b3200-7c47-11eb-82ce-db2c28f33b90.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Thanks for the report!
