### ISSUE TITLE
"Relaunch Terminal" doesn't relaunch the terminal, it just closes it

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118014]
![recording (5)](https://user-images.githubusercontent.com/323878/109752219-d7c01c80-7b94-11eb-861a-bc99acc0b123.gif)

**Comment by meganrogge** [comment]
any errors in dev tools?

**Comment by meganrogge** [comment]
weird that it's even showing you that and not auto relaunching. wondering if my PR will fix this.
