### ISSUE TITLE
Switch the place of "Next Change" and "Open Changes with Next Revision" button

### ISSUE THREAD

**Issue by tongxian** [microsoft/vscode#118005]
I have mis clicked the button of "Next Change" when I check the changes, it changes to the button "Open Changes with Next Revision", I think we can change the place of those buttons to avoid this happens

**Comment by eamodio** [comment]
@tongxian Not sure I understand. Can you show a screenshot/gif of how these change location? FYI, the _Open Changes with Next Revision_ button are from GitLens, not VS Code.
