### ISSUE TITLE
Error on `remoteAuthority` in Local Workspace File

### ISSUE THREAD

**Issue by DocterDum** [microsoft/vscode#118023]
- VSCode Version: 1.53.0
- Local OS Version: Win 10 Pro 19042.746
- Remote OS Version: -
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a VS Code window
2. Connect to a Remote Server (E.g. using status bar shortcut)
3. Save workspace as... to local PC
4. Edit workspace file as JSON in VSCode
5. "remoteAuthority" setting appears faded and mousing over shows an error message

Without this line in the workspace file, upon opening the workspace the remote SSH session is not opened, however the error messages suggests the setting is not needed with a saved workspace file.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

![RemoteAuthorityError](https://user-images.githubusercontent.com/7615222/107136343-52ab6400-6956-11eb-9dbd-3b32a34dd17f.png)

**Comment by aeschli** [comment]
We initially didn't want remote workspaces to be saved on local, but now allow it.
The `remoteAuthority` property is there to capture the information about the remote server.

**Comment by roblourens** [comment]
The description on the property is not accurate now

![image](https://user-images.githubusercontent.com/323878/112397922-412cda00-8cc0-11eb-91a6-fd3d298630c8.png)

**Comment by aeschli** [comment]
Thanks @roblourens, I created #119858
