### ISSUE TITLE
Wrong left padding of outputs in webview in diff editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#118096]
- VS Code Version: OSS
- OS Version: macOS

Steps to Reproduce:

1. Run `endgame.github-issues` in vscode repo
2. Save
3. Open the file in diff editor

<img width="925" alt="image" src="https://user-images.githubusercontent.com/876920/109917102-99e0f800-7c69-11eb-8580-2a9461109ef3.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
For my reference, here's before:

![Screen Shot 2021-03-04 at 2 47 01 PM](https://user-images.githubusercontent.com/12821956/110041033-87fa6600-7cf8-11eb-91ca-ba4660e3955a.png)


Notice how the colored section of the output  lines up with the split shadow, while in the new version we have a large left margin
