### ISSUE TITLE
Provide API to access LSP functions

### ISSUE THREAD

**Issue by DarkTrick** [microsoft/vscode#118094]
- **Introduction**: 
  - VSCode provides the concept of LSP to solve the n:m problem for language-related functionality. 
- **Problem**: 
  - However, extensions cannot take part in this. Not all functionality provided through LSP are accessible by 3rd party extensions. Therefore, 3rd party extensions still have the n:m problem, where n = *number of extensions* and m = *number of languages* (see image below). 
  - Example: It's not possible for an extension to get full outlining information of a file.
- **Feature Request**: 
  - Provide an API to access all functionality provided by LSPs (see image below).

**Problem**:
![image](https://user-images.githubusercontent.com/46980694/109904780-1b27a180-7ce1-11eb-8702-57eb8d0f2d28.png)
**Feature Request**:
![image](https://user-images.githubusercontent.com/46980694/109904748-077c3b00-7ce1-11eb-8a9b-5da04001b4f1.png)

Side note: this FR is a generalization of https://github.com/microsoft/vscode/issues/117022

**Comment by dbaeumer** [comment]
You can talk form extension A to a language server from extension B using VS Code's API commands (https://code.visualstudio.com/api/references/commands)

What you can't do is current to call this from a server without custom messages. But we have an item for this in the LSP realm. 

Please ping if this doesn't clarify things.
