### ISSUE TITLE
Notebook context keys must not be global

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#118039]
* open a notebook
* focus find viewlet
* select `cmd+f`
* :bug: the notebook editor starts search

(the same is likely true for nb diff editors)

The culprit are these context keys: https://github.com/microsoft/vscode/blob/65e283212409e65a7c90b59831d671b7dd2ded9b/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L221-L223

The are updated in the global context key service, not in the context key service of the editor group. Without further testing I believe that  [NOTEBOOK_EDITOR_FOCUSED](https://github.com/microsoft/vscode/blob/1614e28a11c61de2b423fd92902f1ac6a35bb925/src/vs/workbench/contrib/notebook/browser/notebookBrowser.ts#L41-L41) is the better context key

**Comment by rebornix** [comment]
We don't have such context keys anymore.

**Comment by rebornix** [comment]
We now check `activeEditor` for active notebook. 

> focus find viewlet
> select cmd+f
> 🐛 the notebook editor starts search

This is actually the same as Text Editor. Focusing on the search viewlet will not change `activeEditor`.
