### ISSUE TITLE
Sometimes the Visual Studio Code doesn't display anything,

### ISSUE THREAD

**Issue by CaliInn-Li** [microsoft/vscode#118035]
- VS Code Version:x64-1.53.2
- OS Version:Windows 10 20H2 19042.804

Steps to Reproduce:

1.Open Visual Studio Code
2.Even if restarting VS Code still doesn't fix the problem, the problem will sometimes be resolved after restarting, but it may still reappear on the next boot.

[![6EegtH.png](https://s3.ax1x.com/2021/03/03/6EegtH.png)](https://imgtu.com/i/6EegtH)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
This will be fixed in the next release.

/duplicate https://github.com/microsoft/vscode/issues/114459
