### ISSUE TITLE
[Themes] - The themes affect the environment in total.

### ISSUE THREAD

**Issue by wideckop** [Microsoft/vscode#11801]
Would be great that it themes affect the environment in total and not just a part of the environment:

![image](https://cloud.githubusercontent.com/assets/12506535/18401065/acb441ee-76a6-11e6-821d-06e208c5705c.png)

1 - Theme does not affect.
2 - Theme affect.

*Nota: My English is very bad ;)

**Comment by ramya-rao-a** [comment]
Duplicate of #3112
