### ISSUE TITLE
Request for searching all texts or references

### ISSUE THREAD

**Issue by kamtungc** [Microsoft/vscode#11800]
- VSCode Version: 1.5.1
- OS Version: Windows 10 / Ubuntu

Steps to Reproduce:

1. Open C/C++ or other language folder
2. Open a file
3. Right click on a variable/function/class name

No option is for finding all texts or references.

Currently, Visual Studio Code supports "Change All Occurrences". Finding references or texts support in Visual Studio edition or eclipse, but not in Visual Studio Code.

**Comment by ramya-rao-a** [comment]
From VS Code Docs

> It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (such as C++, C#, Python, PHP) and runtimes

You need to install extensions to get support for C/C++.
You can find these extensions in the [marketplace](https://marketplace.visualstudio.com/)

**Comment by kamtungc** [comment]
None of C/C++ extensions work for searching all texts. I just don't see Visual Studio Code supports a searching feature as we have in either Visual Studio or eclipse. I am disappointed the issue was closed.

**Comment by ramya-rao-a** [comment]
@kamtungc Below is the feature "Find all References" implemented by the Go Extension for the Go language. I assumed this is what you were referring to and so closed the issue. The APIs for these have been supported by VSCode for a long time. You are always welcome to re-open an issue if you feel your concerns have not been addressed.

![image](https://cloud.githubusercontent.com/assets/16890566/18402865/7c0e30be-7696-11e6-895b-dbb0a3abb504.png)

If the C/C++ extension does not support "Find all References", then please log an issue in the repo for that extension

For searching just the text, you can always select the word/words and hit Ctrl+Shift+F which will open the `Find across Files` widget.

**Comment by kamtungc** [comment]
![search-vsc1](https://cloud.githubusercontent.com/assets/22105300/18403323/ed6613b0-7698-11e6-9711-3224791d8d6b.jpg)
![search-vsc](https://cloud.githubusercontent.com/assets/22105300/18403326/f1e8ed36-7698-11e6-8d7d-b697d46ac183.jpg)
![search-ec](https://cloud.githubusercontent.com/assets/22105300/18403327/f641d672-7698-11e6-9268-7e40b1077098.jpg)

**Comment by ramya-rao-a** [comment]
Will Ctrl+Shift+F give you the same result as "Search/Find Text" ?

**Comment by kamtungc** [comment]
![search-vs](https://cloud.githubusercontent.com/assets/22105300/18403419/80defeb8-7699-11e6-8f53-b1ecf77970f8.jpg)
Visual Studio Community 2015 has "Find References", but it supports to find the same file (xxx.h or xxx.c) only. eclipse shows correct entries in the "whole" workspace.

**Comment by ramya-rao-a** [comment]
To search a word/set of words in the "whole" workspace you can use `Ctrl+Shif+F` or click on the search icon in the side bar and use the Find widget. This is a VSCode feature agnostic of extensions/languages/filetype.

For issues with "Find All References", you will have to log an issue with the extension owner in the repo for the C/C++ extension.

Does this help?

**Comment by kamtungc** [comment]
ok. let me try it. so, I may not need to install 3rd party extension from marketplace if Visual Studio Code supports for searching texts. I don't want to "replace" all occurrences. I just want to find all occurrences.

**Comment by ramya-rao-a** [comment]
@kamtungc Did that work?

**Comment by kamtungc** [comment]
ok. It works now. I've also uninstalled "C++ Intellisense" extension. This extension does not work. Thanks for your help.

**Comment by ramya-rao-a** [comment]
@kamtungc Glad you are unblocked. Feel free to log an issue for the extension in the repo for the extension so that it can be made better :)
