### ISSUE TITLE
cannot install Java Project Manager in vscode 1.27.1

### ISSUE THREAD

**Issue by ConnectedReasoning** [microsoft/vscode#118038]
- VS Code Version:1.27.1
- OS Version:big sur

Steps to Reproduce:

1. install Java Project Manager from downloaded vsix file
2.get error Unable to install Extension 'vscjava.vscode-java-dependency-0.18.1' as it is not compatible with Code '1.27.1'.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by gjsjohnmurray** [comment]
Please update to the current VS Code release, which is 1.53.2 and later this week will probably be 1.54.
