### ISSUE TITLE
Renaming a folder adds it to history

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118080]
- Open vscode repo
- In the explorer, scripts to scripts2
- Open quickopen
- There is an entry called "scripts2" that errors if you open it
![image](https://user-images.githubusercontent.com/323878/109870679-447ff900-7c1f-11eb-8677-8648e93f71e3.png)

**Comment by bpasero** [comment]
Not sure this qualifies as candidate, will see how it goes once stable is released.
