### ISSUE TITLE
FileSystemProvider extension: throwing a FileSystemError in readFile does not report to user

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#118060]
Issue Type: <b>Bug</b>

1. Clone vscode-extension-samples
2. Open the fsprovider-sample folder
3. Modify readFile so it always throws:
```ts
    readFile(uri: vscode.Uri): Uint8Array {
        const data = this._lookupAsFile(uri, false).data;
        /*
        if (data) {
            return data;
        }
        */
        throw vscode.FileSystemError.FileNotFound();
    }
```
4. Build and run.
5. Use the usual MemFS commands to initialoze the workspace and create the files.
6. Open one of the files from Explorer.
7. A tab appears for the file but the progress indicator runs continually :bug:

This is not a 1.54 regression.

VS Code version: Code - Insiders 1.54.0-insider (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-02T19:09:10.315Z)
OS version: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
Ouch...

**Comment by gjsjohnmurray** [comment]
/verified

Version: 1.55.0-insider (user setup)
Commit: 567b82a0f9c31bd463af64997997730c5d0173cc
Date: 2021-03-05T05:22:52.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
