### ISSUE TITLE
Getting started page should have a period after "Redefined"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118076]
![image](https://user-images.githubusercontent.com/323878/109875773-b8250480-7c25-11eb-98b6-b06461d4607b.png)
![image](https://user-images.githubusercontent.com/323878/109875783-bb1ff500-7c25-11eb-83d6-f4c8db2c6784.png)

Also that message feels too close to the "Visual Studio Code" label?

**Comment by JacksonKearl** [comment]
Now just using the "Editing Evolved" text
