### ISSUE TITLE
"Open with Code" context menu is not localized

### ISSUE THREAD

**Issue by joao-fnunes** [Microsoft/vscode#11804]
- VSCode Version: 1.5.1
- OS Version: Windows 10 Enterprise Build 10240

Minor issue, but still:

![image](https://cloud.githubusercontent.com/assets/1964667/18404435/4d4126de-769f-11e6-8165-49730ae71479.png)

Steps to Reproduce:
1. Install VS Code in an OS with a language other than ENU (I used DEU), making sure you enable the context menu during installation.
2. Right-click a folder or file

**Comment by johnliu2016** [comment]
@joao-fnunes does this context menu have hotkey assigned? Can you provide a s/s of that?

**Comment by joao-fnunes** [comment]
Regarding the assignment of a hotkey, this is the Windows Explorer menu, I don't believe there's any hotkey assigned to it (are you talking about VS Code menus and hotkeys?). Also, would you kindly elaborate on s/s?

**Comment by johnliu2016** [comment]
@dbaeumer guessing the context menu is from system registry for VSCode, found following instances and they seem hard-coding

vscode-master\build\win32\code.iss
	Line 758: Root: HKCU; Subkey: "SOFTWARE\Classes\*\shell\{#RegValueName}"; ValueType: expandsz; ValueName: ""; ValueData: "Open with {#NameShort}"; Tasks: addcontextmenufiles; Flags: uninsdeletekey
	Line 761: Root: HKCU; Subkey: "SOFTWARE\Classes\Folder\shell\{#RegValueName}"; ValueType: expandsz; ValueName: ""; ValueData: "Open with {#NameShort}"; Tasks: addcontextmenufolders; Flags: uninsdeletekey
	Line 764: Root: HKCU; Subkey: "SOFTWARE\Classes\directory\background\shell\{#RegValueName}"; ValueType: expandsz; ValueName: ""; ValueData: "Open with {#NameShort}"; Tasks: addcontextmenufolders; Flags: uninsdeletekey

**Comment by joaomoreno** [comment]
This is long fixed.
