### ISSUE TITLE
Add "Get Started" content to extension detail

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#118055]
https://user-images.githubusercontent.com/35271042/109847662-51432380-7c04-11eb-9c00-9c77a2ee9d41.mov

Refs https://github.com/microsoft/vscode/issues/116414

This is based on the work of https://github.com/microsoft/vscode/issues/106715 and how we've added support for extensions to contribute to this (https://github.com/microsoft/vscode/issues/116414). One idea to bring this content more in context of where the user is at is when an extension is installed. Currently we show the readme in the "Details" tab, but I think showing the get started content for the extension on this page is more appropriate and can prevent extensions from creating their own "welcome pages".

**Comment by sandy081** [comment]
I assume that this extension getting start page shall be contributed by the running extension right thereby it is available only when extension is installed?

**Comment by misolori** [comment]
Correct, this would only appear if an extension contributes a getting started item.

**Comment by sandy081** [comment]
Makes sense. In such case we need to add API for extensions to contribute welcome pages. How about updates release notes for extensions?

**Comment by misolori** [comment]
@JacksonKearl would have a better answer for this, but we recently allowed extensions to contribute getting started content with https://github.com/microsoft/vscode/issues/116414. Next steps is to allow extensions to contribute multiple getting started content and extensions can set a property for the one that is shown on the extensions detail page post-install. The idea is that this can be used for both getting started and release notes/calling out new features.

**Comment by JacksonKearl** [comment]
My understanding is that we're no longer pursuing this route in favor of some alternative way of showing the content, such that the user doesn't need to open the getting started page or extension editor to see the content.
