### ISSUE TITLE
1.5 update crashed VS Code; required 'stable' reinstall

### ISSUE THREAD

**Issue by mmorrisuts** [Microsoft/vscode#11803]
- VSCode Version: 1.5 
- OS Version: Windows 7 Enterprise (64 bit)

Steps to Reproduce:

1. Press blue button while in VS Code to download newest version (my previous was v1.4).
2. It stalls, but doesn't have a real issues at this point.
3. Stop VS Code.  
4. Download the 1.5 upgrade.
5. Install 1.5 upgrade.
6. VS Code no longer works.
7. Download 'stable' 1.5 version.
8. Restart computer.
9. Install 'stable' 1.5 version.
10. Everything is back to normal.  (Yay!)

Apologies I didn't take a pictures of the error messages.  Very impressive and informative, but gone now.  My priority sadly was solving the issue.  :)

**Comment by joaomoreno** [comment]
Good to know that you are OK now. But without details I'll have to close this.
