### ISSUE TITLE
终端不能输入中文

### ISSUE THREAD

**Issue by rongxkai** [microsoft/vscode#118092]
Issue Type: <b>Bug</b>

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

on windows10 ,The terminal cannot input Chinese when using the Chinese input method, only the system's built-in input method can input successfully.

**Comment by rongxkai** [comment]
on windows10 ,The terminal cannot input Chinese when using the Chinese input method, only the system's built-in input method can input successfully

**Comment by Kong-PR** [comment]
I also encountered this problem.

**Comment by Kong-PR** [comment]
![3$5E9$URMEXIAIJ))~V2L](https://user-images.githubusercontent.com/45937622/109907144-b5d1b180-7cdc-11eb-8dd1-d941f008d91f.png)
![`@CZ`GAXK6K0UFWXDAA1BJF](https://user-images.githubusercontent.com/45937622/109907212-d568da00-7cdc-11eb-89e7-22c99b503ea2.png)

**Comment by Kong-PR** [comment]
When I finished typing in Chinese ,I pressed the space,but did not enter.

**Comment by LittleStoney** [comment]
经过测试，是最新版搜狗输入法不能输入中文，微软自带输入发可以，已经反馈给了搜狗
After testing, the latest version of sogou input method can not input Chinese, Microsoft's input can be sent,.It's been fed back to sogou

**Comment by rongxkai** [comment]
I have tried Baidu input method but can’t input,so I think it’s still a problem with vscode.
After a certain update of vscode, it doesn’t work. I forgot which version it was.

**Comment by yume-chan** [comment]
#115814

**Comment by lhrr** [comment]
> After testing, the latest version of sogou input method can not input Chinese, Microsoft's input can be sent,.It's been fed back to sogou

you are right！

**Comment by Kong-PR** [comment]
This problem may have been fixed , because I can use it again.
