### ISSUE TITLE
Add code folding to angle brackets in C++ templates

### ISSUE THREAD

**Issue by operativeF** [microsoft/vscode#118081]
For example, it often makes sense to separate parameters in using-declarations by line and indentation. This makes things easier to read and reason about.  There is no folding mechanism for these things, however, and it makes navigating the file arduous. 
See here: [Example](https://github.com/odinthenerd/tmp/blob/development/include/boost/tmp/algorithm/fold_left.hpp)

The feature idea would be to allow for folding between brackets, just like for the other bracket constructs. So one line lists won't get the option, but multiline lists will.

**Comment by aeschli** [comment]
Please file the request against the C++ extension: https://github.com/microsoft/vscode-cpptools/issues
