### ISSUE TITLE
Typescript crashed 5 times

### ISSUE THREAD

**Issue by woss** [microsoft/vscode#118053]
Issue Type: <b>Bug</b>

I was just minding my own business :( 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.86GB (18.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (8 x 3696)|
|Memory (System)|31.36GB (7.45GB free)|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
mermaid-markdown-syntax-highlighting|bpr|1.2.0
bracket-pair-colorizer|Coe|1.0.61
auto-rename-tag|for|0.1.6
react-apollo-snippets|lev|0.0.3
dotenv|mik|1.0.1
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
sql-snippets|sad|0.0.4
ReactSnippetsStandard|Tim|1.1.0
highlight-matching-tag|vin|0.10.0
vscode-icons|vsc|11.1.0
vscode-todo-highlight|way|1.0.4
vscode-nginx|wil|0.7.2
lua-debug|act|1.33.2
tasks|act|0.8.2
vscode-nginx-conf|ahm|0.1.3
vscode-apollo|apo|1.18.2
markdown-emoji|bie|0.1.0
markdown-mermaid|bie|1.9.2
prettier-toml|bod|0.1.0
pgformatter|bra|1.16.0
simple-react-snippets|bur|1.2.3
jsonviewer|cci|1.2.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.2.1
EditorConfig|Edi|0.16.4
json-to-gql|ele|0.0.1
json-tools|eri|1.0.2
prettier-vscode|esb|5.9.2
git-project-manager|fel|1.7.1
shell-format|fox|7.0.1
go|gol|0.22.1
vscode-graphql|Gra|0.3.15
vscode-nginx-conf-hint|han|0.1.0
css-to-jss|inf|1.0.6
vscode-gnupg-tool|JHe|1.3.9
vscode-styled-components|jpo|1.5.0
vscode-colorize|kam|0.10.0
vs-color-picker|lih|1.0.0
rust-analyzer|mat|0.2.505
git-graph|mhu|1.29.0
vscode-less|mrm|0.6.3
vscode-docker|ms-|1.10.0
hexeditor|ms-|1.4.0
vsliveshare|ms-|1.0.3784
npm-outdated|msk|1.4.1
vetur|oct|0.33.0
fix-json|oli|0.1.2
nginx-formatter|ray|0.0.13
vscode-yaml|red|0.15.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.1
crates|ser|0.5.6
code-spell-checker|str|1.10.2
lua|sum|1.17.3
language-stylus|sys|1.11.0
tabnine-vscode|Tab|3.2.8
even-better-toml|tam|0.11.1
vscode-lua|tri|0.12.4
vscode-lldb|vad|1.6.1
vscodeintellicode|Vis|1.2.11
docker|vsc|1.0.0
yaml|vsc|1.0.0
debug|web|0.25.0
vscode-nginx|wil|0.7.2
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
plsql-language|xyz|1.8.2
map-replace-js|Yuk|0.2.2
markdown-all-in-one|yzh|3.4.0
makefile-creator|zen|0.0.3

(5 theme extensions excluded)

</details>

**Comment by woss** [comment]
i checked the output and this is the only thing there
```
[Info  - 19:13:13.124] TSServer exited
[Info  - 19:13:13.124] Starting TS Server 
[Info  - 19:13:13.124] Using tsserver from: /home/USER/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 19:13:13.126] <syntax> Forking...
[Info  - 19:13:13.139] <syntax> Starting...
[Info  - 19:13:13.139] <semantic> Forking...
[Info  - 19:13:13.151] <semantic> Starting...
[Info  - 19:14:23.673] TSServer exited
[Info  - 19:14:23.673] Starting TS Server 
[Info  - 19:14:23.673] Using tsserver from: /home/USER/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 19:14:23.674] <syntax> Forking...
[Info  - 19:14:23.687] <syntax> Starting...
[Info  - 19:14:23.687] <semantic> Forking...
[Info  - 19:14:23.698] <semantic> Starting...
```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by woss** [comment]
i've opened with the Insiders and all ext disabled. so far nothing, if that's the case then there is an issue with some extension. thank you

**Comment by woss** [comment]
This is what i am getting in both Insiders and Stable version
<img width="338" alt="Screenshot 2021-04-07 154914" src="https://user-images.githubusercontent.com/80440/113877273-d8ae2480-97b8-11eb-91a0-35b043e19fc4.png">

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
