### ISSUE TITLE
Ask the user whether a custom editor should be made the default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118063]
Was having a discussion with @kieferrm and we were thinking the extension should not say it should be the default, but rather indicate that it makes sense and would like to be the default. That way VS Code can ask the user when one of these default extensions is installed when opening a supported file whether it would like to be the default (eg. Luna Paint), but not for "secondary" custom editors where that doesn't make as much sense (eg. Hex Editor).

This will help if we recommend installing Luna Paint from the image viewer (https://github.com/microsoft/vscode/issues/116120) as the default wouldn't be changed out from under the user.

**Comment by lramos15** [comment]
I'm not sure how we would know this is your first time opening a specific file type after a specific custom editor is installed. I think the easier flow would be something like themes which when installed shows you the current theme and gives you the option to switch your default.

**Comment by Tyriar** [comment]
@lramos15 the extensions list a set of extensions where it would make sense to be a default for. We could just keep a map in the storage service of the response the user gave to the question? eg.

```ts
answers['lunaPaint'] = {
  ".ico": true,
  ".bmp": false
}
```

Whether we ask on file open or extension install should probably be brought to the UX sync.

**Comment by lramos15** [comment]
Closing for now as I've added a notification to prompt the user when there are two conflicting defaults
