### ISSUE TITLE
Make the WebGL terminal renderer the default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118064]
Part of https://github.com/microsoft/vscode/issues/106202

We should also improve the fallback logic to do this:

- Try webgl
- If it threw an exception, try canvas
- If frame rendering averages > 50ms (existing detection), use DOM

We will keep the canvas renderer around for now mainly because Safari doesn't support webgl2 and can evaluate [whether we want to remove it](https://github.com/microsoft/vscode/issues/106202) again at a later date.

**Comment by connor4312** [comment]
It looks like canvas is still the default for me -- the `xterm-text-layer` is present unless I explicitly enable experimentalWebgl. I don't see any notifications of errors that could be causing it.
