### ISSUE TITLE
Not able to connect to internet from within vscode (terminal/install extentions) under VPN

### ISSUE THREAD

**Issue by vavdoshka** [microsoft/vscode#118075]
Issue Type: <b>Bug</b>

The strange thing is that I have no issue with non-vscode environment - chrome/Iterm can access DNS/internet without an issue. 

On vscode start I have this in Log (window):
```
[2021-03-03 22:02:21.146] [renderer5] [error] Network Error: Error: Network Error
    at e.exports (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/tas-client-umd/lib/tas-client-umd.js:1:7511)
    at XMLHttpRequest.p.onerror (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/tas-client-umd/lib/tas-client-umd.js:1:6478)
[2021-03-03 22:02:21.263] [renderer5] [error] net::ERR_NAME_NOT_RESOLVED: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:109:6508)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

when do
Developer Tools -> Network -> after execute "Install Extensions" it says "Cannot connect to Extensions marketplace" and there is an error in Developer Tools which shows `net::ERR_NAME_NOT_RESOLVED`

when do (as example `marketplace.visualstudio.com`, happens to any other URL)
terminal -> `curl -I https://marketplace.visualstudio.com` -> `curl: (6) Could not resolve host: marketplace.visualstudio.com`

when do same by IP 
`curl -v 13.107.42.18` got
```
*   Trying 13.107.42.18...
* TCP_NODELAY set
* Immediate connect fail for 13.107.42.18: Operation not permitted
* Closing connection 0
curl: (7) Couldn't connect to server
```

As I said I have no issue with accessing the mentioned FQDN/IP from non-vscode environment, also have no issue accessing any of this list of hostnames from chrome/ non-vscode terminal https://code.visualstudio.com/docs/setup/network. 
So I'm a bit lost and don't know how to troubleshoot further.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|--crash-reporter-id e9f182b5-69a9-4cab-a789-bfca3e15c5ef|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by vavdoshka** [comment]
guys please any thoughts?

**Comment by vavdoshka** [comment]
@deepak1556 please any guidance with troubleshooting this?

**Comment by deepak1556** [comment]
Sorry for the delayed response, couple of things to try

1) Does the issue happen when you start with `code --user-data-dir /tmp/vscode`
2) If above still repros the issue, start with `code --user-data-dir /tmp/vscode --log-net-log=/tmp/netlog.json`
  2.1) Install extensions that shows the host resolver error
  2.2) Quit the app and attach the netlog file.

**Comment by vavdoshka** [comment]
@deepak1556 perfect!
1. - fixed the issue for me, so easy.. 
So strange cause I was sure I already wiped everything about vsCode and reinstalled it cleanly, but it seems some user data stayed there.
so now after I did `rm -rf $HOME/Library/Application\ Support/Code` it started to work back again with just `code`. thanks!
