### ISSUE TITLE
Python code reports an warning 'Unnecessary Semicolon' NO semicolon in file

### ISSUE THREAD

**Issue by phedlund113** [microsoft/vscode#118047]
- VS Code Version:1.53.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1 in code editor i have

albet_lc = 'abcdefghijklmnopqrstuvwxyz'
#  albet_uc = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
The # symbol has a squiggle under it and when i hove over it i get the Unnecessary Semicolon Message.
.

Does this issue occur when all extensions are disabled?: Yes/No NO
I disabled all extensions then enabled them one by one
The extension that causes the issure is the Python extension from Microsoft v2021.2.582707922

**Comment by aeschli** [comment]
This issue needs to be filed against  https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
