### ISSUE TITLE
Codespaces: Add needed keys such as CTRL to iOS’s keyboard  

### ISSUE THREAD

**Issue by NightMachinary** [microsoft/vscode#118097]
Apps that work with code all implement their own special add-ons to iOS’s default keyboard, in order to make them usable without an external keyboard. For example:

![5666F511-1811-4358-AAC0-A9F1EA7B9597](https://user-images.githubusercontent.com/36224762/109917919-61720600-7ccb-11eb-85f7-e91403aade1f.png)

**Comment by alexdima** [comment]
@NightMachinary Is this something that web apps can do as well?

**Comment by NightMachinary** [comment]
[**@alexdima**](https://github.com/alexdima) commented on [Mar 4, 2021, 12:49 PM GMT+3:30](https://github.com/microsoft/vscode/issues/118097#issuecomment-790462714 "2021-03-04T09:19:03Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary) Is this something that web apps can do as well?

I have no idea, but worst-case scenario, can't codespaces publish a shim app on the app store?

**Comment by rebornix** [comment]
This can only be done by iOS apps but not web apps. However it's a good feature to have in GitHub iOS App.

**Comment by isidorn** [comment]
No plans to tackle this, let's close for now. If in the future web apps can do this we can reopen this
