### ISSUE TITLE
Add trigger reason to code actions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#118084]
## Problem

For JS/TS, if user makes a imprecise selection (such as only selecting part of an identifier name) and then manually requests code actions, we'd like to return refactorings as if the selection were expanded. However we don't want to do this automatically for implicitly requested code actions (which cause the light bulb to show up)

## Proposal
Add a trigger reason to the code action context. This would let you know if the code actions have been manually requested or were triggered automatically

**Comment by mjbvz** [comment]
Oddly I proposed doing this before (#50248) but ended up solving it a different way. I think it makes senes to add this though now

**Comment by mjbvz** [comment]
Ah, I think what we did instead before was have a `range | Selection` be passed to the current code action provider. If it's a selection, then it's a manual request. Will investigate further but could still  be worth having a more explicit field that tracks this

**Comment by mjbvz** [comment]
A few reasons why I think this api is worth adding even though we sort of have a proxy for it:

1. This api should handle commands better. When using commands to request code actions, those should count as `manual` requests. Right now I believe they end up being classified as automatic

2. Given that I was the author of the `Range | Selection` change and still forgot about the distinction, I think the existing API could be made more clear

**Comment by jrieken** [comment]
Manual -> Invoke

**Comment by mjbvz** [comment]
This was already tested with https://github.com/microsoft/vscode/issues/119217 without any changes

For verification, follow the steps in https://github.com/microsoft/vscode/issues/119217 but make sure you do not have proposed apis enabled
