### ISSUE TITLE
Debugger for Chrome extension broken after reinstall or update vscode every time

### ISSUE THREAD

**Issue by liesauer** [microsoft/vscode#118017]
- VS Code Version: 1.46.1
- OS Version: win10

Steps to Reproduce:

1. resintall or update vscode
2. debug any js project with `Debugger for Chrome` extension

![image](https://user-images.githubusercontent.com/8676741/109763872-bc552000-7c2d-11eb-985f-97e3a9dc2b3e.png)

**Comment by liesauer** [comment]
the sulotion is reinstall `Debugger for Chrome` extension after reinstall or update vscode, but this sucks.

**Comment by connor4312** [comment]
Looks like the user is reporting the debugger is getting uninstalled when they update?

**Comment by liesauer** [comment]
> Looks like the user is reporting the debugger is getting uninstalled when they update?

no, it still there. it just broken.
