### ISSUE TITLE
UWP Application - Feature request

### ISSUE THREAD

**Issue by OrbintSoft** [Microsoft/vscode#11807]
I think it should be great if we can have Windows Universal Application to use on mobile with continuum.

https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7762905-visual-studio-code-on-universal-app-platform

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #10759
@OrbintSoft @WangZishi Don't forget to up vote the original issue logged.
