### ISSUE TITLE
Bash variable substitution using VS Code variable lead to no substitution

### ISSUE THREAD

**Issue by moocan** [microsoft/vscode#118004]
- VS Code Version: Version: 1.53.2
- OS Version: Ubuntu LTS 20.04

This task does nothing but I did not understand why bash variable substitution using VisualStudio Code variable was not working.

Steps to Reproduce:

1. Create simple task with as command in task.json (unquoted or quoted):
Unquoted: `"command":  "shopt -s globstar; for prjfile in ${workspaceFolder}/**/*; do echo ${workspaceFolder}; echo ${prjfile//${workspaceFolder}/.}; done"`
Quoted `"command":  "shopt -s globstar; for prjfile in \"${workspaceFolder}\"/**/*; do echo \"${workspaceFolder}\"; echo \"${prjfile//\"${workspaceFolder}\"/.}\"; done"`
2. Execute task
3. Variable substitution `${prjfile//${workspaceFolder}/.}` is not made when you call `${workspaceFolder}` directly in the substitution or using a VisualStudio Code variables as `${workspaceRoot}` too.

Launching task but no substitution:
`> Executing task: shopt -s globstar; prjFolder=/myfolder/project-test; for prjfile in /myfolder/project-test/**/*; do echo /myfolder/project-test; echo ${prjfile//${workspaceFolder}/.}; done <`

Testing directly with `bash -c "shopt -s globstar; workspaceFolder="myfolder"; for prjfile in \"\${workspaceFolder}\"/**/*; do echo \"\${workspaceFolder}\"; echo \"\${prjfile//\"\${workspaceFolder}\"/.}\"; done"` is working

Working: 
Use of `${workspaceFolder}` for the for loop and echoing it's value and using another variable for substitution.

Unquoted : 
`"shopt -s globstar; prjFolder=${workspaceFolder}; for prjfile in ${workspaceFolder}/**/*; do echo ${workspaceFolder}; echo ${prjfile//${prjFolder}/.}; done"`
Quoted 
`"shopt -s globstar; prjFolder=\"${workspaceFolder}\"; for prjfile in \"${workspaceFolder}\"/**/*; do echo \"${workspaceFolder}\"; echo \"${prjfile//\"${prjFolder}\"/.}\"; done"`

Launching task and substitution is done:
`> Executing task: shopt -s globstar; prjFolder=/myfolder/project-test; for prjfile in /myfolder/project-test/**/*; do echo /myfolder/project-test; echo ${prjfile//${prjFolder}/.}; done <`

Working: 
Set the content of `${workspaceFolder}` to `prjFolder` and then use only this variable 
for all other steps.

Unquoted : 
`"shopt -s globstar; prjFolder=${workspaceFolder}; for prjfile in ${prjFolder}/**/*; do echo ${workspaceFolder}; echo ${prjfile//${prjFolder}/.}; done"`
Quoted : 
`"shopt -s globstar; prjFolder=\"${workspaceFolder}\"; for prjfile in \"${prjFolder}\"/**/*; do echo \"${workspaceFolder}\"; echo \"${prjfile//\"${prjFolder}\"/.}\"; done"`

Launching task and substitution is done:
`> Executing task: shopt -s globstar; prjFolder=/myfolder/project-test; for prjfile in /myfolder/project-test/**/*; do echo /myfolder/project-test; echo ${prjfile//${prjFolder}/.}; done <`

Does this issue occur when all extensions are disabled?: Yes

Regards,

**Comment by alexr00** [comment]
A very simple example that illustrates the issue:
```
		{
			"label": "My Task",
			"type": "shell",
			"command": "echo \"${test/${workspaceFolder}}\"",
			"problemMatcher": []
		}
```

**Comment by alexr00** [comment]
This is intended: https://github.com/microsoft/vscode/issues/77289
Anything that looks like an attempt to next variables is not allowed.
