### ISSUE TITLE
Allow variables in launch.json config

### ISSUE THREAD

**Issue by jeromu** [Microsoft/vscode#1180]
Allowing a variable like '${file}', in "launch.json" would open up nice workflows.

For example, I want to launch the debugger with the current file as a parameter, so that I can run a specific test.

Right now, I need to modify the launch.config every time I want to debug a single test.

**Comment by egamma** [comment]
@isdorn we already support this, can you check that we cover this in our documentation.

**Comment by isidorn** [comment]
Yes, this is already supported, please check 
https://code.visualstudio.com/docs/editor/tasks#_variables-in-tasksjson
I have updated our debug docs to make this more clear

**Comment by jgauffin** [comment]
It's not working in ***launch.json***. Is it really implemented in both tasks.json and lunch.json?

My setup:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch",
			"type": "chrome",
			"request": "launch",
			"file": "${fileBasename}"
		}
	]
}
```

**Comment by egamma** [comment]
@isidorn?

**Comment by isidorn** [comment]
This is a current limitation that we only support substitituion for a limited number of properties. Currently, those are `program` and `runtime`. The issue is that your are using the chrome debugger which uses the non standard `file` instead of the `program` attribute
We can also do the substituion for the `file` propertie but it is a bit hacky since we would need a nice mechanism for a debug adapter to contribute the names of properties which should be substituted
@weinand fyi

**Comment by weinand** [comment]
@isidorn we should no longer distinguish between standard and non-standard attributes. All attributes are the same and are defined via a contributed schema. We should use the same variable substitution rules as task.json (which I hope are: var substitution works in all string attributes).

**Comment by isidorn** [comment]
Yup substituting all strings makes sense to me, will do it after endgame so expect a fix in our January update.

**Comment by souptown** [comment]
This should not be closed. It looks like the only variable enabled is ${workspaceRoot}. 

Support for these variables is also needed:
${file} the current opened file
${fileBasename} the current opened file's basename
${fileDirname} the current opened file's dirname
${fileExtname} the current opened file's extension
${cwd} the task runner's current working directory on startup

**Comment by weinand** [comment]
@souptown I've just verified with VS Code 1.2.1 that the variables from above work fine.
Please provide more detailed information why this doesn't work for you.

**Comment by souptown** [comment]
@weinand You are absolutely correct. I forgot the curly braces in my launch.json file.
