### ISSUE TITLE
Telemetry and Insight ignore telemetry options (spyworks)

### ISSUE THREAD

**Issue by Kein** [microsoft/vscode#118054]
- VS Code Version: 1.53.2
- OS Version: Win10x64

**Steps to Reproduce:**

1.  Set up any proxy monitor/intercepter
2.  Launch VSCode with proxy settings
3.  Observe Telemetry/Insights/Recommendations (whatever buzzword MS calls it now just to diminish the issue) related connections that should NOT be there

**Does this issue occur when all extensions are disabled?: Yes/No**
YES.

**Settings**
```json
"workbench.settings.enableNaturalLanguageSearch": false,
"update.showReleaseNotes": false,
"json.schemaDownload.enable": false,
"extensions.autoCheckUpdates": false,
"extensions.showRecommendationsOnlyOnDemand": true,
"telemetry.enableCrashReporter": false,
"telemetry.enableTelemetry": false,
"code-runner.enableAppInsights": false,
"update.channel": "none",
"update.mode":"none",
"extensions.autoUpdate": false,
"extensions.ignoreRecommendations": true,
"settingsSync.ignoredExtensions": [
    "*.*",
],
"workbench.enableExperiments": false,
```

![image](https://user-images.githubusercontent.com/623756/109847582-69e12700-7c60-11eb-8b2b-901f0bde573a.png)

**Comment by Kein** [comment]
> chrmarti removed their assignment 2 hours ago
I see nobody wants to hold an answer for hideous direction from the MS top office about how we can insert more telemetry user data fathering that is not governed by "telemetry" options because we call it something else. I mean, A/B testing with unique user id is not telemetry, right? So we can easily send whatever, why bother trying to explain ourselves to a user?

**Comment by sbatten** [comment]
@Kein Your screenshot is quite useful here actually in diagnosing this issue. Last month, I explicitly addressed this issue for VS Code core, no telemetry means disabling everything about experiments. Unfortunately, the extensions use a slightly different module that needs to be updated to reflect this change. Note that we are still not sending any telemetry back, we are just requesting the list of experiments. However, that said, I will get this change in ASAP.

**Comment by sbatten** [comment]
@bamurtaugh @aeschli when the experiments module is updated, please update the extensions consuming it

**Comment by Kein** [comment]
@sbatten 
Hopefully this fix wont end up as `empty` as
#104293
#103159
#115818

> Note that we are still not sending any telemetry back

When normal users people say `telemetry`, they dont actually mean THE classic definition of telemetry, because both Google, MS and other big corpos diluted the meaning of this definition over the years with their corporate bullspeak.  So whey they say "telemetry" they talk about all user data that can be used to identify and/or track a user. Unique ID, taking place in that screenshot of a log - is part of said data.

**Comment by sbatten** [comment]
@Kein I am not sure what you mean by "empty" regarding the linked issues. Those issues resulted in actual code change to prevent the ping you talk about from core vs code. This issue will be tracked to resolve the same issue for extensions.

**Comment by aeschli** [comment]
@sbatten I updated `remote-wsl-recommender` & `remote-wsl` to use `vscode-tas-client@0.1.17` and added code to observe `workbench.enableExperiments`.

**Comment by sbatten** [comment]
@aeschli very cool, thanks, this will resolve the issue from OP, but I will leave this issue as a reminder to ping when `vscode-tas-client` is updated to do telemetry disablement detection automatically

**Comment by sbatten** [comment]
looks like we can close this issue now as the clients are up to date
