### ISSUE TITLE
Explorer side-tab missing

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#118048]
Issue Type: <b>Bug</b>

It's just gone when it's not selected. Selecting it makes it appear. Clicking Search makes it disappear. Not always, either.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (2.72GB free)|
|Process Argv|-psn_0_6870669 --crash-reporter-id aa77e851-0fc5-45a8-b2b6-6d32c4e1f3ee|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by sdegutis** [comment]
Notice its absence in top-left corner:

<img width="1136" alt="Screen Shot 2021-03-03 at 10 38 16 AM" src="https://user-images.githubusercontent.com/4399718/109839273-923f3600-7c0c-11eb-8a44-003552ceb3ba.png">

**Comment by IllusionMH** [comment]
Have you tried to do right click on Activity Bar and enable Explorer?

I guess I see same behavior if I disable it
![image](https://user-images.githubusercontent.com/1312662/109839711-1070fc00-7c50-11eb-8d30-508a56f13045.png)

**Comment by sdegutis** [comment]
Oh, yeah, that fixes it. Hmm, not sure how it got disabled. Never mind this. Thanks.
