### ISSUE TITLE
VSCode Typescript language extension ignores excludes in tsconfig.json when considering auto imports

### ISSUE THREAD

**Issue by snoozbuster** [microsoft/vscode#118072]
Issue Type: <b>Bug</b>

I have defined a [manual mock](https://jestjs.io/docs/en/manual-mocks.html) in a `__mocks__/` directory - but when I go to use VSCode's auto import functionality, it picks up both the real module and the mock one. I thought that maybe it could be ignored by excluding the `__mocks__` directory in `tsconfig.json` (specifically: `"exclude": ["node_modules", "src/**/__mocks__"]`), but this appeared to have no effect.

[![import from ts file][1]][1]

However, when importing from inside a .vue file (using language extensions provided by Vetur), the `__mocks__/` folder _is_ ignored! (Removing `__mocks__/` from the `"exclude"` files in tsconfig.json causes Vetur to suggest the import from `__mocks__/` alongside the other two.)

[![import from vue file][2]][2]

VSC's typescript language extension appears to be ignoring the tsconfig exclude setting when considering auto imports and suggestions from a `.ts` file.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 18.7.0

  [1]: https://i.stack.imgur.com/Ie7Rf.png
  [2]: https://i.stack.imgur.com/nau5p.png

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 11a29b96-40f4-4999-9ecd-8a1c588728c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
vscode-firefox-debug|fir|2.9.2
auto-close-tag|for|0.5.10
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.158.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vetur|oct|0.33.0
vscode-jest|Ort|3.2.0
project-snippets|reb|0.5.0
vscode-stylelint|sty|0.86.0
vscode-icons|vsc|11.1.0
vim|vsc|1.18.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30264244

```

</details>

**Comment by mjbvz** [comment]
Please share a minimal example project that demonstrates the issue

**Comment by snoozbuster** [comment]
@mjbvz I've been trying to create an example project that has the same issue but I cannot - a simple project doesn't seem to exhibit the same behavior (`"exclude": ["node_modules", "src/**/__mocks__"]` works to prevent the auto import from both `.vue` and `.ts` files). At the same time, I cannot get the same `exclude` to work in my actual project (which is a proprietary affair that I can't publish). Is there some way I can debug this so I can figure out what's really going on, and whether or not this is a bug or some bizarre confluence of misconfiguration?

**Comment by mjbvz** [comment]
First check that the file is part of your tsconfig project:

1. Open the ts file
2. Run `TypeScript: Go to project configuration`
3. Confirm this opens up your `tsconfig`

**Comment by mjbvz** [comment]
The project should be updated whenever you save the tsconfig. If you are not seeing this, can you please share steps to reproduce the problem?

**Comment by mjbvz** [comment]
I'm closing this as it sounds like a project configuration issue/question

**Comment by thw0rted** [comment]
The author should check out [solution-style tsconfig](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig), which lets the language server be pointed to multiple `tsconfig` files at once.  This way, you can have separate "build" and "test" tsconfig files and get appropriate suggestions in a given file based on which config(s) include it.

@mjbvz , thanks a lot for that "Go to project configuration" suggestion.  I didn't know that existed, and it's especially useful when you have multiple configs for different parts of your codebase.
