### ISSUE TITLE
Codespaces - cannot install several product icon themes

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#118018]
When trying to install the Material Product Icon theme

![image](https://user-images.githubusercontent.com/172399/109765050-99f2e080-7bf4-11eb-8216-47d29eafde50.png)

VS Code tells me that this is not supported in this context. Notice that the extension details editor has the label 'install locally'.

![image](https://user-images.githubusercontent.com/172399/109765162-c0188080-7bf4-11eb-8ecf-8a7074eab02d.png)

The same happens for the Fluent and Carbon product icon themes.
The Bootstrap icon theme works.

**Comment by sandy081** [comment]
It seems they tagged their extensions to be strict ui kind and hence they cannot be installed in web.

```
"extensionKind": [
		"ui"
]
```

Filed issues in corresponding repos:

https://github.com/PKief/vscode-material-product-icons/issues/9
https://github.com/misolori/vscode-fluent-icons/issues/11

**Comment by PKief** [comment]
Hi @egamma, I just fixed it for the Material Product Icons by removing the `extensionKind` attribute (as suggested by @sandy081) and I already published a new version on the Marketplace. As I don't use Codespaces at the moment, it would be cool if you could try it out to see if it works now. Feel free to reach out to me if any further adjustments need to be made.

**Comment by sandy081** [comment]
Thanks @PKief for the quick turnaround. I can verify that the extension can be installed and works in codespaces.
