### ISSUE TITLE
Keep remote server alive so remote SSH sessions can reconnect without losing work enviroment in terminals. 

### ISSUE THREAD

**Issue by bennetmei** [microsoft/vscode#118031]
I have switched from VNC to VS code for a year. I uses remote SSH to connect to my company's Linux server. Everything is great except when I shut down my laptop, I lose all my working environments next day. With VNC, I can keep the same terminals for months. I usually need to open many terminals and hate to lose my working terminals. I know there are some tools that can help save/restore terminals. Also I tried tmux within vscode teriminal, which doesn't work so well in some aspects. Is it possible to just keep vscode remote server alive even the host vscode session are closed?  So when host vscode restarts,  it just reconnects the terminals to the ones maintained by vscode server.  This would be similar to tmux and should not be hard to implement I guess?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/3096
