### ISSUE TITLE
Git - Ability to apply stash missing from Git extension API.

### ISSUE THREAD

**Issue by ckline-tryptic** [microsoft/vscode#118083]
When using [Repository.commit](https://github.com/microsoft/vscode/blob/05d3593f91eeffaab26d24f02d3a93a65912683f/extensions/git/src/git.ts#L1338) through the Git API extension [Repository](https://github.com/microsoft/vscode/blob/05d3593f91eeffaab26d24f02d3a93a65912683f/extensions/git/src/api/git.d.ts#L149) interface, it prompts to stash unstaged changes. However, the corresponding [Repository.applyStash](https://github.com/microsoft/vscode/blob/05d3593f91eeffaab26d24f02d3a93a65912683f/extensions/git/src/git.ts#L1764) is not exposed. Having access to this function would be very helpful, since using `await` with `executeCommand` returns early and doesn't provide useful errors.

**Comment by ckline-tryptic** [comment]
Thanks, @eamodio! Great extension by the way. 🔎

**Comment by EloB** [comment]
Will this ever be implemented?

**Comment by lszomoru** [comment]
Verification steps:
* Easiest way to verify this is to review the PR - https://github.com/microsoft/vscode/pull/235773
