### ISSUE TITLE
'The WebView must be attached to the DOM' — When switching away from notebook diff editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#118147]
Issue Type: <b>Bug</b>

**Repro**
1. Open a notebook in the diff view (tested with the github issues notebook)
2. Scroll down 
1. Switch to another file

**bug**
In dev tools, see:

```
  ERR The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.: Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.e.getWebContentsId (electron/js2c/renderer_init.js:131:3776)
    at HTMLElement.send (electron/js2c/renderer_init.js:131:4327)
    at file:///Users/matb/projects/vscode/out/vs/workbench/contrib/webview/electron-browser/webviewElement.js:150:84
```

VS Code version: Code - OSS Dev 1.55.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.47GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-view|bie|0.0.9
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.23.1
svg|joc|1.4.5
template-string-converter|meg|0.4.7
git-graph|mhu|1.29.0
vscode-language-pack-de|MS-|1.54.1
vscode-dotnet-runtime|ms-|1.0.0
vscode-edge-devtools|ms-|1.1.3
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.600686576
remote-containers|ms-|0.163.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.64.0
azure-account|ms-|0.9.6
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
vscode-github-issue-notebooks|ms-|0.0.68
vscode-markdown-notebook|ms-|0.0.14
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
shader-toy|ste|0.10.15

</details>

**Comment by mjbvz** [comment]
I believe that webviews in diff editors are being leaked at the moment. For normal notebooks, I see the webview disposed of in the `dispose` method:

https://github.com/microsoft/vscode/blob/0eca51a2dad7fec9dfe59e8a507cb851611230c0/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1828

However I don't see the same in notebookTextDiffEditor

**Comment by mjbvz** [comment]
Hm, now I'm just more confused. It seems the webviews are not disposed of when the diff editor is closed (and `.dispose` is not fired on the `NotebookEditorWidget` either). However they are disposed of when another notebook diff editor is opened

**Comment by rebornix** [comment]
I started to see leaks of `NotebookEditorWidget` recently, which is likely a regression, and probably in the `editorOverride` logic.
