### ISSUE TITLE
Pressing escape should always set focus to the text

### ISSUE THREAD

**Issue by cskilbeck** [Microsoft/vscode#11817]
- VSCode Version: 1.5.1
- OS Version: WIn10

Steps to Reproduce:
1. Press ctrl-shift-E 
2. Press escape, note that focus is not on the editor

**Comment by bpasero** [comment]
This is now possible with the upcoming release you can configure such a following keybinding:

`{ "key": "Escape", "command": "workbench.action.focusActiveEditorGroup", "when": "explorerViewletFocus" }`
