### ISSUE TITLE
on vscode start, ide freezes must manually force closed

### ISSUE THREAD

**Issue by friday963** [microsoft/vscode#118141]
- VS Code Version:
-1.54.0
42e27fe5cdc58539dad9867970326a297eb8cacf
x64
- OS Version:
Red Hat Enterprise Linux Server release 7.9 (Maipo)
Steps to Reproduce:

1. updated vscode to most recent version, shown above.
2. Start vscode

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by friday963** [comment]
I'm not sure how to check the last version I was on, but it worked fine.  Today after doing a yum update (where vscode was updated) I'm no longer to open the ide without it freezing and needs to manually be forced closed.

**Comment by IllusionMH** [comment]
Can be duplicate of #115784
See https://code.visualstudio.com/updates/v1_53#_electron-11-update and https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356 for details.

Linked issue also contained workaround, but no guarantees that it will work for everyone.

**Comment by friday963** [comment]
@IllusionMH  thanks for the response.  I ended up downgrading but thank you for making me aware of the issue!
