### ISSUE TITLE
After Update VSC to 1.54 emmet does not working! 

### ISSUE THREAD

**Issue by MarioG8** [microsoft/vscode#118185]
Issue Type: <b>Bug</b>

After update VSC to v1.54 there are problems with emmet.
The add-on has disappeared from the settings and the settings are greyed out in the JSON file. Emmet does not working :(
Does anyone have such problems after the update?
Can anybody help? Please :)

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.20GB free)|
|Process Argv|--crash-reporter-id d8abc7e1-3749-4628-8d30-3aa8e31cb985|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (99)</summary>

Extension|Author (truncated)|Version
---|---|---
emmet-keybindings|agu|0.0.6
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.0.3
electron-snippets|ant|1.0.3
vscode-django|bat|1.3.0
simple-react-snippets|bur|1.2.3
vscode-standardjs-snippets|cap|0.8.15
emmet-jss|car|1.0.0
turbo-console-log|Cha|2.1.6
handlebars-preview|cha|1.1.0
node-snippets|chr|1.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.14
vscode-faker|dee|1.5.0
javascript-ejs-support|Dig|1.3.1
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.16
async-switch|Eme|0.5.0
react-native-react-redux|EQu|2.0.6
vscode-express-snippets|Exp|1.1.1
mithril-emmet|Fal|0.7.6
git-project-manager|fel|1.7.1
vscode-firefox-debug|fir|2.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
terminal|for|0.0.10
pythonsnippets|frh|1.0.2
activitusbar|Gru|0.0.38
firebase-snippets|has|0.0.1
rest-client|hum|0.24.4
path-autocomplete|ion|1.17.1
vscode-edit-csv|jan|0.5.5
search-node-modules|jas|1.3.0
styled-components-snippets|jon|0.10.0
vscode-styled-components|jpo|1.5.0
react-native-snippet|jun|0.5.6
vscode-gutter-preview|kis|0.26.2
node-module-intellisense|lei|1.5.0
MagicPython|mag|1.1.0
start-git-bash|McC|1.2.1
rainbow-csv|mec|1.8.1
python-path|mge|0.0.11
vscode-language-babel|mgm|0.0.30
gitignore|mic|1.0.1
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.3
vscode-filesize|mkx|2.1.4
mongodb-vscode|mon|0.4.2
vscode-docker|ms-|1.10.0
mssql|ms-|1.10.1
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
awesome-flutter-snippets|Nas|2.0.4
reload|nat|0.0.6
prettier-standard-vscode|num|0.8.1
indent-rainbow|ode|7.5.0
EmberES6Snippets|pha|2.3.3
heroku-command|pko|0.0.8
quicktype|qui|12.0.46
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
synthwave-vscode|Rob|0.1.8
mongo-snippets-for-node-js|roe|1.3.5
gruvbox-material|sai|6.3.6
html5-boilerplate|sid|1.1.1
vscode-fileutils|sle|3.4.5
guides|spy|0.9.3
code-spell-checker|str|1.10.2
prettier-plus|svi|4.2.2
ejs-snippets|Tao|0.1.0
ayu|tea|0.20.1
ejs-snippets|The|0.7.0
python-extended-snippets|tus|0.0.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.11
vscode-svg-previewer|vit|0.7.0
vscode-icons|vsc|11.1.0
material-ui-snippets|vsc|3.3.3
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
txt-syntax|xsh|0.1.4
emmet-live|yse|1.0.0
markdown-all-in-one|yzh|3.4.0
bootstrap-v4-snippets|Zac|1.1.3
json|Zai|2.0.2

(12 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by Tarpsvo** [comment]
I noticed the same when using SCSS. Some things work, some don't. For example I can do `mr0` for `margin-right: 0`, but I can't do `fxd:c` for `flex-direction: column;`.

**Comment by rzhao271** [comment]
@Tarpsvo that issue with : in SCSS files is from https://github.com/microsoft/vscode/issues/112675. A workaround for now is to type `fxdc` instead, though I don't think that workaround works for all SCSS abbreviations.
@MarioG8 can you paste screenshots of the emmet settings and the extension being greyed out?

**Comment by MarioG8** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/66386548/110166759-194f0280-7df5-11eb-92f4-8f109fc6e05c.png)
![Screenshot (16)](https://user-images.githubusercontent.com/66386548/110166767-1ce28980-7df5-11eb-9a7d-4b35af94ee08.png)
![Screenshot (18)](https://user-images.githubusercontent.com/66386548/110166782-210ea700-7df5-11eb-9402-7c74511915b6.png)
![Screenshot (19)](https://user-images.githubusercontent.com/66386548/110167015-6f23aa80-7df5-11eb-98db-7d942be01bdd.png)
![Screenshot (21)](https://user-images.githubusercontent.com/66386548/110167194-b3af4600-7df5-11eb-926f-83a8e77c097a.png)

Emmet has disappeared from the setup extensions. when i try to use tab it shows a message command :'emmet.expand Abbreviation' not found' I only have two settings under the emmet name...:( Like on the screen shots...
Thank's for Yours Help ! Best regards and I am waiting for info...:)

**Comment by rzhao271** [comment]
If you go into the list of extensions and type `@builtin`, does Emmet show up? If yes, is it disabled?

**Comment by MarioG8** [comment]
Awesome !!! :) :D Great Job . Thank You Very Much and send you Fabulous vibes and Greetings ;)
