### ISSUE TITLE
Badge on Accounts icon - "Sign in to Sync Settings (1)" does nothing

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#118171]
Issue Type: <b>Bug</b>

This appeared after I restarted Insiders to install its update. I will paste a screenshot.

![image](https://user-images.githubusercontent.com/6726799/110083537-b888e100-7d86-11eb-9752-6a8c4320b3cb.png)

VS Code version: Code - Insiders 1.55.0-insider (567b82a0f9c31bd463af64997997730c5d0173cc, 2021-03-05T05:22:52.277Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.74GB free)|
|Process Argv|-n --enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 584c5b29-25dd-4f1c-a7c6-fb3b6998cbc6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
tsl-problem-matcher|eam|0.4.0
prettier-vscode|esb|5.9.2
thefoldingstuff|geo|0.1.2
vscode-serenji|geo|3.1.4-beta.1
vscode-favorites|how|1.8.3
rest-client|hum|0.24.4
objectscript-pack|int|1.0.3
servermanager|int|1.0.5
vscode-objectscript|int|1.0.9-beta.1
language-server|int|1.1.2
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
remote-ssh|ms-|0.65.0
remote-ssh-edit|ms-|0.65.0
remote-wsl|ms-|0.54.0
azure-account|ms-|0.9.6
hexeditor|ms-|1.4.0
vscode-github-issue-notebooks|ms-|0.0.68
vscode-js-profile-flame|ms-|0.0.14
vscode-markdown-notebook|ms-|0.0.14
vscode-typescript-tslint-plugin|ms-|1.3.3
vsonline|ms-|1.0.3076
debugger-for-chrome|msj|4.12.12
material-product-icons|PKi|1.0.2

(1 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
@gjsjohnmurray are you usually using MS account for sync?

It is missing for me completely from menu and Output. No errors in DevTools though.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/118194
