### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by AdamTeodoro** [microsoft/vscode#118170]
Tem alguns problemas no meu projeto e não condigo resolver, a usabilidade do marketplace dificulta muito, uma simples alteração no nome do meu projeto é muito difícil de ser feita, além de outros problemas como inserir uma imagem e fazer uma atualização, essas são funcionalidades simples e que não consigo fazer usando o marketplace:

https://marketplace.visualstudio.com/items?itemName=slim-coffe.slim-coffe

**Comment by joaomoreno** [comment]
Please file an issue in the VS Marketplace repository: https://github.com/microsoft/vsmarketplace/issues
