### ISSUE TITLE
Integrated terminal doesn't open

### ISSUE THREAD

**Issue by yazurita** [microsoft/vscode#118191]
Issue Type: <b>Bug</b>

The terminal window flashes and then closes, whether I open it via View -> Terminal (or the corresponding shortcut), or by trying to run any script.
This issue was present in older versions of VS code (#42711, #42627), and it is happening again in the latest one.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.94GB free)|
|Process Argv|--crash-reporter-id d44b3eb0-31b0-412e-b0dd-9c4832b3c9a6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by meganrogge** [comment]
Any issues in dev tools?

**Comment by yazurita** [comment]
> 
> 
> Any errors in dev tools?

I'm not familiar with dev tools, but I can see this error:

![image](https://user-images.githubusercontent.com/72736453/110146937-0c211c00-7dd3-11eb-8e4a-bd7d3ce9e0a7.png)

**Comment by yazurita** [comment]
The terminal now opens, after enabling compatibility mode (right click on Code.exe -> Properties -> Compatibility -> check Run this program in compatibility mode for Windows 8).
The issue now is that the terminal is blank, whether I run any script or try to type something in it. It happens with all shells (PowerShell, cmd, bash).

**Comment by yazurita** [comment]
Problem solved. I moved the VS Code folder from C:\Users\(YourUser)\AppData\Local\Programs to C:\Program Files. I also removed it form PATH. Now it works perfectly.
