### ISSUE TITLE
更新最新版本

### ISSUE THREAD

**Issue by zhangzhaosheng1993** [microsoft/vscode#118168]
In Chinese mode, click file and select new window. By default, the new window is English.

Open it on the computer desktop alone. The default is set before. No problem

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/110091376-560a0200-7dd3-11eb-9562-9bab4e1dd43a.png)

Stole a screenshot

**Comment by yume-chan** [comment]
@TylerLeonhardt IIRC I saw this screenshot in OP's Twitter, so I "stole" it and posted here. I personally don't have this issue.

**Comment by yume-chan** [comment]
Actually, it happened to me once in about ten tries. Forgot to take a screenshot, but there was a bunch of `[Extension Host] null` in DevTools console.
