### ISSUE TITLE
The .tsx files cannot display React icon

### ISSUE THREAD

**Issue by Caayu** [microsoft/vscode#118162]
![Captura de tela 2021-03-05 024301](https://user-images.githubusercontent.com/46906076/110059686-725e5e00-7d43-11eb-8168-acf686511471.png)

**Comment by misolori** [comment]
We use the [seti-ui icon theme](https://github.com/jesseweed/seti-ui) for the file icons, please file an issue in that repo as we depend on it and can't make any modifications. Thanks.
