### ISSUE TITLE
Format Code dosn't work with Javascript on OSX

### ISSUE THREAD

**Issue by jbecwar** [Microsoft/vscode#11810]
- VSCode Version: 1.5.1
- OS Version:  OS X 10.11.6

Steps to Reproduce:
1.   Open Javascript File
2.   Right click in editor window, select "Format Code"

Expected Action:
Code is formatted.

Actual Action:
Code doesn't change.

As a workaround I installed the extension beautify and it is able to format the code.

**Comment by ramya-rao-a** [comment]
@jbecwar @Treri I was able to format javascript code in VS Code 1.5.1 and in OS X El Capitan 10.11.6 without any extensions.

Can you share an example of javascript code that you were unable to format?

**Comment by Treri** [comment]
@ramya-rao-a No, I still can't format code in 1.5.1

But I found that, the same file, if it is in a project, it can't be formated via `format code`, but if it is a single file, it is correctly formated. And sorry, I can't provider the whole project.

**Comment by ramya-rao-a** [comment]
@Treri Do you mean that if you open a folder containing the js file in VS Code, you cannot format it, but you can format it if it is opened in VS Code as single file?

Can you share your customized workspace and user settings?

**Comment by Treri** [comment]
@ramya-rao-a I can reproduce. I will describe steps below

1. use Code open the javascript file in attachment, use `format code` to format code. It can't be formatted now.
2. copy the file's content, and then press `ctrl+n` to create a untitled file, then paste the content to it, change the language mode to javascript. **But do not save the file**, then use `format code` to format the file. It can be correctly formatted.
3. press `ctrl+z`, change the untitled file to compressed status, then save the whole file. And then use `format code` to formate it. Now, it can't be formatted again.

[app_c32294ea.js.zip](https://github.com/Microsoft/vscode/files/466406/app_c32294ea.js.zip)

**Comment by alexandrudima** [comment]
@Treri do you have installed extensions that contribute formatting? On my machine, in an untitled file, the Format action is not available. It has to do with the file being in memory and the language service not being able to pick it up. So I'm thinking the format for untitled files is handled by a 3rd party extension you have installed.

**Comment by konnorbeard** [comment]
I had this same issue. Couldn't format a javascript file within my project with shortcuts or >format code (failed silently). Created a new file on my desktop, copied+pasted the contents of the old file, saved it as a JS file, and then could format it. 

Same versions as @jbecwar.

**Comment by Treri** [comment]
@alexandrudima Yes, you are right. I uninstalled all my extensions, and fresh installed Code. Only saved javascript file will have `format code` option.

But the file still can't be formatted. Could you please download my attachment, and reproduce locally?

**Comment by alexandrudima** [comment]
@waderyan @dbaeumer  are TS/JS experts that can explain / understand how formatting works / doesn't work in JS

**Comment by dbaeumer** [comment]
@waderyan can you please investigate

**Comment by waderyan** [comment]
@dbaeumer yes will do.

**Comment by waderyan** [comment]
Using Insiders 1.6.0, I am unable to format code a file I have not saved. 

I am on the latest TS bits and no formatting will work. Going to send to language service team.

**Comment by waderyan** [comment]
Issue tracked here - https://github.com/Microsoft/TypeScript/issues/11101
