### ISSUE TITLE
freezes opening passphrase-protected ssh git repository

### ISSUE THREAD

**Issue by poidl** [Microsoft/vscode#11815]
- VSCode Version: 1.5.1
- OS Version: Arch linux 4.7.2-1-ARCH #1 SMP PREEMPT Sat Aug 20 23:02:56 CEST 2016 x86_64 GNU/Linux
Steps to Reproduce: 

1. open a folder containing an SSH git repo with passphrase-protected key
2. open konsole (a KDE terminal emulator), run `/opt/visual-studio-code/code &` 

Result: Vscode freezes. If I close the window, KDE says: "Application code is not responding" and giving me an option to terminate it.

Note:
If I run `/opt/visual-studio-code/code` in foreground, vscode does not freeze and I'm prompted for the passphrase:

    Enter passphrase for key '/path/to/id_rsa':

**Comment by poidl** [comment]
I'm using 1.5.3 now and the problem seems to have disappeared. For me this is solved. Thanks.

**Comment by joaomoreno** [comment]
Thanks!
