### ISSUE TITLE
Go to definition shortcut F12 doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by IgorKoshnarov** [microsoft/vscode#118149]
- VS Code Version:
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-44-generic snap
- OS Version:
Ubuntu 20.04
Steps to Reproduce:

1. Install fresh new Ubuntu 20.04
2. Install latest  stable VSCode editor
3. Add (erlang 0.6.9) Erlang language extension for Visual Studio Code extension (all extension settings are default).
4. Install erlang language.
5. Open any erlang project, place a cursor over some function call and press F12 key.

Expected behaviour: 
jump to the function definition.

Currently observed behaviour: 
jump to the end of the line where the cursor was placed before being pressed.

I checked that in VSCode Settings > Keyboard Shortcuts the Go to Definition is set to F12 and condition is editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor Default
Ctrl+(left mouse click) combo works the way F12 should (jumps to the function definition)
Ctrl+Shift+P and typing "Go to Definition" with selection of drop down option works as expected as well (the shortcut for the command in the list is displayed as F12).
In the upper menu under "Go" option the suboption "Go to Definition" is colored with more light grey (looks as disabled). The same is true for "Go to Declaration", "Go to Type Definition", "Go to Implementation". (But these list options look the same on my Windows 10 (64) machine and on that machine everything works fine).

The same installation (latest stable VSCode editor (I checked that is has the same version and commit hash), same erlang 0.6.9 extension, same extension settings) works as expected on my Windows 10 (64) machine. I can browse to the function definition by pressing F12 and I can get back by pressing Alt + leftArrow.
I also tested the F12 (Go to Definition) functionality on WSL2(Windows Subsystem Linux) with Ubuntu 20.04 Image with same VSCode settings and it works as expected.

I need the same to be working on my Ubuntu machine (Dell latitude 541, core I7). And it seems I can't get it to work.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> Open any erlang project, place a cursor over some function call and press F12 key.

Instead, please right click and see of there is a  "Go to Definition" entry in the context menu

**Comment by IgorKoshnarov** [comment]
> > Open any erlang project, place a cursor over some function call and press F12 key.
> 
> Instead, please right click and see of there is a "Go to Definition" entry in the context menu

Yes, the right click on the function call opens a context menu with "Go to Definition" option and when I select this option it leads to the function definition. The problem is only that the shortcut F12 doesn't work.

**Comment by jrieken** [comment]
Ok, please do this: 

* F1 > Set Log Level > Tace
* F1 > Show Logs > Window
* Press F12 on that symbol you are trying with
* In the log output search for messages like this: `[2021-03-05 16:50:45.876] [renderer2] [trace] KeybindingService#dispatch`

**Comment by IgorKoshnarov** [comment]
I went through all the steps and all I got was this:
[2021-03-05 17:56:52.997] [renderer1] [trace] KeybindingService#dispatch End cursorEnd
[2021-03-05 17:56:52.997] [renderer1] [trace] CommandService#executeCommand cursorEnd

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `F12`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`F12`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by IgorKoshnarov** [comment]
Hey, Thanks, guys! I've got the problem - on my new laptop the <end> key is at the same time the <F12> key, which is not the case for my windows machine. So I had to delete the default keymapping for the "end" and edit the keymapping for "Go to Definition", pressing F12 (which displayed the "end" in the popup's text field). And now I can't go to the end of the line by pressing the key but I can go to the function definition.

**Comment by alexdima** [comment]
@IgorKoshnarov This does not appear to be something under the control of VS Code. It looks like your keyboard has a key labeled physically as "f12", but the key sends the "end" key to the OS. I suggest that you contact the manufacturer, as this appears to be a system wide issue which is not specific to vscode.
