### ISSUE TITLE
February 2021 Recovery Endgame

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#118145]
**DO NOT USE AS TEMPLATE: Modified for this release only**

- [x] Create a milestone `<Month> <Year> Recovery` **owner**
- [x] Bump the version number **owner**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22February+2021+Recovery%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [ ] Build `stable` for all platforms from release branch **owner**
- [ ] Issues are verified on `stable` build and the `verified` label is added **owner**
- [ ] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [ ] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [ ] Sanity check of installable bits
  - [x] Windows 32 bit @rebornix 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit @meganrogge 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] Windows ARM64 @sbatten
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS @deepak1556 
    - [x] intel
    - [x] apple silicon
    - [x] universal
  - [x] Linux
    - [x] deb package 64-bit @rebornix 
    - [x] rpm package 64-bit @deepak1556 
    - [x] archives @rebornix 
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) @rebornix 
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux @RMacfarlane 
    - [x] macOS @mjbvz 
    - [x] Windows **owner**
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by gjsjohnmurray** [comment]
The candidate issues link is showing January Recovery ones.
