### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Fsouth** [microsoft/vscode#118190]
When the old version of VS Code is opened, it shows:Cannot activate the 'Python' extension because it depends on the 'Jupyter' extension, which is not loaded. Would you like to reload the window to load the extension?
When you open a new version of VS Code, you cannot change the background image

**Comment by aeschli** [comment]
Please only one problem per issue. Can you file a new issue for the `change the background image` problem? Please describe what you mean by that.

**Comment by sandy081** [comment]
Please check if you have Jupyter extension installed - Python extension depends on that extension.
