### ISSUE TITLE
After upgrading to 1.54.0 i have multiple duplicate git repositories and source control items.

### ISSUE THREAD

**Issue by jesseboydgsa** [microsoft/vscode#118151]
- VS Code Version:  1.54.0
- OS Version: Win10 20Q3

Steps to Reproduce:

1.  upgrade to 1.54.0
2.  open git tab in vs code
3.   NOTE we run inside a VDI with very limited internet access but our github repo is exposed correctly

Does this issue occur when all extensions are disabled?: Yes/No
yes issue occurs with extensions disabled

image -> all names are from just one get repo and repeat 

![image](https://user-images.githubusercontent.com/58823468/110045866-335ae900-7d00-11eb-9583-ff82fb8cbcc7.png)

in CMD git status in normal and shows file I just updated and no errors

in vs code git log ->
![image](https://user-images.githubusercontent.com/58823468/110046326-ac5a4080-7d00-11eb-98ba-27da3ff18ab5.png)

the rev-parse is in an endless loop

**Comment by jesseboydgsa** [comment]
downgrading to 1.53.2 the issue goes away on same folder and project

**Comment by srisinger** [comment]
I can also confirm this issue. I updated my git version, but I have the same result.
`$ git --version --build-options
git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
`

**Comment by marlag** [comment]
Having same issue - moreover it seems endless loop:

![image](https://user-images.githubusercontent.com/11375408/110233808-dc832880-7f26-11eb-88f1-b2bd97c9ad62.png)

**Comment by p3t3r5** [comment]
Some Issue... disable "Git: Detect Submodules" has no effect

**Comment by eamodio** [comment]
I'm going to close this one in favor of #118351, please add any more details there -- as I can reproduce this at all nor can I see any changes that could cause this.
