### ISSUE TITLE
'npm run dev' fails in VSC built-in terminal, succeeds in external terminal

### ISSUE THREAD

**Issue by alainlhostis** [microsoft/vscode#118154]
- VS Code Version: 1.54.0
Commit: 42e27fe5cdc58539dad9867970326a297eb8cacf
Date: 2021-03-03T02:17:39.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-53-generic snap
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. git clone https://github.com/theworldisnotflat/shriveling_world.git
2. open VSC
3. in built in terminal type: `npm i`
4. `npm run dev` => errno 134

1. navigate app folder
2. ctrl + T
3. `npm i`
4. `npm run dev` => app can be opened in browser http://localhost:3000

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
works for me

<img width="999" alt="Screenshot 2023-10-02 at 4 46 12 PM" src="https://github.com/microsoft/vscode/assets/29464607/56dde622-7b25-4335-bea7-62e2e4b3dd9a">
