### ISSUE TITLE
Files opening in different windows

### ISSUE THREAD

**Issue by sirajalam049** [Microsoft/vscode#11814]
- VSCode Version:
- OS Version:

1. When a open a file two times, so it opens in two windows, but it is supposed to show the same windows every time I open the same file.
2. When I open the two files they also open in separate windows, while it is supposed to open in the same window in separate tabs.

Thanku.
sirajalam049@gmail.com
Siraj Alam

**Comment by bpasero** [comment]
Try `"window.openFilesInNewWindow": false`

**Comment by ramya-rao-a** [comment]
@sirajalam049 Did that work for you?

**Comment by bpasero** [comment]
Assuming this is the right fix, closing.
