### ISSUE TITLE
Add support to get image size (width and height)

### ISSUE THREAD

**Issue by gitlovenotwar** [Microsoft/vscode#11813]
Hi, opening an image in vs code only shows the image. It would be great if it could show more details also, like its size, width and height. 

Also, if possible with x2 and /2 calculated also along with the original size.

ex. (It would show something like this)
width: 180px
height: 180px

width@2x: 360px
height@2x: 360px

width/2: 90px
height/2: 90px

**Comment by bpasero** [comment]
The image dimensions shows when you hover over the image.

**Comment by gitlovenotwar** [comment]
ah right, size of image shows on hover thanks. It would be awesome if it could easily be seen(may at the bottom there's so much space) without hovering, new developer would be wondering. And also, for automatic calculating of its size by half or by multiplied by 2... It's really helpful and fast than to compute it with calculator... but anyway, good work on vs, appreciated your work. thanks

**Comment by bpasero** [comment]
Moving into https://github.com/Microsoft/vscode/issues/3414
