### ISSUE TITLE
Markdown simultaneous edit and preview 

### ISSUE THREAD

**Issue by tinganho** [Microsoft/vscode#11812]
It would be awesome if you could provide simultaneous edit and preview on markdown files. Clicking on the preview button is not that UX friendly.

**Comment by ramya-rao-a** [comment]
@tinganho Do you mean you would like to open the preview by default when you open an markdown file?

@kieferrm maybe we can have a setting for this?

**Comment by ionutvmi** [comment]
You can actually open the preview and drag the tab to the right side so you have a 2 panes.
When you edit the markdown source it will automatically update the preview.

![preview](https://cloud.githubusercontent.com/assets/3531898/18426189/45f251a2-78c8-11e6-937c-d21e45db6af4.png)

**Comment by tinganho** [comment]
@ionutvmi never thought about that. But that was basically what I wanted.

**Comment by ramya-rao-a** [comment]
@ionutvmi You also have the command to open Preview to the side

![image](https://cloud.githubusercontent.com/assets/16890566/18444840/b66bf968-78cf-11e6-8ce4-40c4c6c665f0.png)
