### ISSUE TITLE
Non vscode related directory resources do not support loading?

### ISSUE THREAD

**Issue by AShujiao** [microsoft/vscode#118179]
Supports extensions directory：
file:///C:/Users/Administrator/.vscode/extensions/333.jpg
![image](https://user-images.githubusercontent.com/14969576/110090418-3b835900-7dd2-11eb-9edd-c338c4efe469.png)
Non extensions directories are not supported：
file:///d:/soft/vscode-img/2077/IMG_3331(20201223-161406).jpg
![image](https://user-images.githubusercontent.com/14969576/110090667-7f765e00-7dd2-11eb-861f-e494bae3762d.png)

The related extension does not work properly：
https://marketplace.visualstudio.com/items?itemName=manasxx.background-cover
https://marketplace.visualstudio.com/items?itemName=shalldie.background

**Comment by aeschli** [comment]
Please file the request against the background extension.
