### ISSUE TITLE
Remote: Can't download file outside of workspace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118161]
I opened a log file that I want to download. For files in my workspace I can right click in the explorer and run "Download". But there is no way to do this for other files outside of the workspace. It doesn't show up right clicking in Open Editors, or on the tab. There is a command which I expected to operate on the active editor, but it operates on the selected item in the Explorer, which wasn't expected.

**Comment by bpasero** [comment]
@roblourens File > Save as... ?

**Comment by roblourens** [comment]
That would let me save it somewhere else on the remote, I want the same functionality as the Download command

**Comment by isidorn** [comment]
I think no action is planned here. There is a good path to "Show Local".
Thus closing as designed
