### ISSUE TITLE
Open new file

### ISSUE THREAD

**Issue by bschauhan** [Microsoft/vscode#11819]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10240

Steps to Reproduce:

1. I have to open new file but current file is automatically close.
2. I have to open new file in new tab but not possible in current version.

**Comment by Mlocik97** [comment]
1.5.x version is hard bugged,, i had to download 1.4.0 version:
I recommend it to you until fix bugs.

**Comment by ramya-rao-a** [comment]
@bschauhan 

Are you trying to create a new file (File -> New File)?
When you create a new file, a new tab is always opened.

Or are you trying to open an existing file which is not opened in any editor yet?

If you single click on a file in the explorer in VS Code, then it is opened in [Preview mode](https://code.visualstudio.com/docs/editor/tabs#_preview-mode) and re-uses existing tab. Tabs in preview mode will have the file name in italics.

If you double click on a file in the explorer in VS Code, then it is opened in a new tab.

If you don't like the Preview feature, you can disable it by setting the below 2 settings to false in your User Settings

- workbench.editor.enablePreview
- workbench.editor.enablePreviewFromQuickOpen

**Comment by youngytj** [comment]
It looks like I got the same problem.  

See Images:  

![vsc](https://cloud.githubusercontent.com/assets/4630470/18458742/3b474eaa-7996-11e6-87e0-5e7e28d92384.gif)  
![qq 20160913094144](https://cloud.githubusercontent.com/assets/4630470/18458755/59fbbf66-7996-11e6-8218-6ae350530625.png)

**Comment by ramya-rao-a** [comment]
@youngytj 
Are you using single click or double click while selecting the files?
If single click then it is not a problem, it is the Preview mode feature. Read my previous comment https://github.com/Microsoft/vscode/issues/11819#issuecomment-246200339

**Comment by youngytj** [comment]
@ramya-rao-a 
Oh, I understand it now. Thank you for your comment.

**Comment by bpasero** [comment]
Configurable, please update your settings.
