### ISSUE TITLE
Autocomplete does not provide hints and completions for function parameters

### ISSUE THREAD

**Issue by goktugyil** [microsoft/vscode#118153]
- VS Code Version: 1.54.0
- OS Version: MacOS 10.15.7
- Language: Typescript

Our file:
```
const aVariable = 'asd'
const anotherVariable = 'asd'

console.log  // #1
console.log()  // #2 
```

Steps to Reproduce:

Setting False, does not autocomplete function, but autocompletes variable. 
1.
In `settings.json`, set:
 ```
   "javascript.suggest.completeFunctionCalls": false,
    "typescript.suggest.completeFunctionCalls": false,
``` 
2. Type `console.l`
3. Autocomplete it into `console.log`
4. Add paranthesis `console.log(`
5. Start typing variable `console.log(aVar`
6. It shows code hints and can autocomplete variable 

---

Setting True, autocompletes function, but does not auto complete variable. 
1.
In `settings.json`, set:
 ```
   "javascript.suggest.completeFunctionCalls": true,
    "typescript.suggest.completeFunctionCalls": true,
``` 
2. Type `console.l`
3. Autocomplete it into `console.log()`
4. Start typing variable `console.log(aVar)`
6. It does not give code hints and cannot autocomplete variable

Does this issue occur when all extensions are disabled?: Yes

Related:
https://github.com/microsoft/vscode-go/issues/3075#issuecomment-599326659
https://github.com/microsoft/vscode-go/issues/3037
https://github.com/microsoft/vscode-go/pull/3038

Notes: 
If there is another setting needed to make this work, feel free to point me out to the right direction. I absolutely have no idea how this IDE was coded with typescript and has so many users, but miss this simple feature. Am I doing something wrong?

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false`. 

You can also always manually trigger suggestions with ctrl+space

**Comment by goktugyil** [comment]
Thanks, that worked. 

I don't see any good reason why these 2 settings are not default.
