### ISSUE TITLE
Autocomplete not working in python file but works in interactive shell

### ISSUE THREAD

**Issue by berkdemir** [microsoft/vscode#118166]
Autocompletes work for objects in interactive shell, but not in python files. Is there a workaround for this? I am using pylance.
I know that interactive shell is already executed so that it knows the attribute of the object, however, is there a solution for a python file?

Interactive shell:
![image](https://user-images.githubusercontent.com/40423004/110073898-47026000-7d91-11eb-99cb-a0d7b91a795d.png)
Python file:
![image](https://user-images.githubusercontent.com/40423004/110073906-4cf84100-7d91-11eb-962e-4927849776d1.png)

**Comment by aeschli** [comment]
This issue needs to be filed against https://github.com/Microsoft/vscode-python/issues
Can you filing the issue there?
