### ISSUE TITLE
Sash: Control hover delay

### ISSUE THREAD

**Issue by tdgrubbs** [microsoft/vscode#118158]
- VS Code Version: 1.54.1
- OS Version: macOS Catalina 10.15.7

Steps to Reproduce:

1. Hover over sash that has customized color

In my settings.json I have the following included:

```json
"workbench.colorCustomizations": {
   "sash.hoverBorder": "#ff8c49"
}
```
How it looks on my machine now:
![sash_hover](https://user-images.githubusercontent.com/32615341/110056914-3fa56d00-7d25-11eb-9bbe-2509fbbc6e1a.gif)

In 1.52/1.53 the color change seemed instantaneous, as shown in the [release notes](https://code.visualstudio.com/updates/v1_52#_sash-hover-border-color)

Was a delay added?  Is this intended?  Any way to customize the delay?

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
If controlling the delay is desirable, we can add a setting for it.

**Comment by tdgrubbs** [comment]
> If controlling the delay is desirable, we can add a setting for it.

Sounds great, thank you!
