### ISSUE TITLE
view/item/context secondary actions not in ... menu

### ISSUE THREAD

**Issue by jiu-you** [microsoft/vscode#118180]
- VS Code Version:  1.53.2
- OS Version: win10

Steps to Reproduce:

1. Configure ‘view/item/contex’ secondary actions according to the documentation
2. It can be found not displayed in... meun
3. In fact the display can be triggered by right-clicking

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
The correct name is `context` - with a `t` at the end. Is your code missing that or was that an error when copy-pasting into this issue?
