### ISSUE TITLE
Find and Replace Issue

### ISSUE THREAD

**Issue by rahulmohan1986** [microsoft/vscode#118111]
Issue Type: <b>Bug</b>

Hello,
I was trying to edit my HTML page. I use Bootstrap 4 for styling. When I tried to replace a class named "mr-40" with a bootstrap class called "mx-auto". I found that when I tried to replace the texts they are replaced in capital letters, but it was supposed to be replaced in small letters because the class name is in small letters.
Steps I tried in VS Code given below;
Ctrl+F
Ctrl+H
Find - 'mr-40'
Replace with - 'mx-auto'
Result - 'mr-40' replaced with 'mx-AUTO'
Expected result - 'mr-40' replaced with 'mx-auto'
Expected all texts to be in small letters but the text after '-' is placed as capital letters.

I observed that it was happening to this particular class only.

Please help
Thanks

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.69GB (1.19GB free)|
|Process Argv|--crash-reporter-id 3d27e7ab-ab37-4b4b-9731-78ab43245e9c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>
![Capture](https://user-images.githubusercontent.com/49026893/109966542-67410900-7d16-11eb-8322-5ed172922df3.PNG)
![Capture1](https://user-images.githubusercontent.com/49026893/109966573-70ca7100-7d16-11eb-822e-1e3ed10234da.PNG)

**Comment by IllusionMH** [comment]
In your case you should get expected results if you disable "Preserve Case" in replace field.
![image](https://user-images.githubusercontent.com/1312662/109967782-8631a200-7cfa-11eb-8ccf-4bbd4338b306.png)

however it's still strange that it picked to replace buttons with uppercase

**Comment by rahulmohan1986** [comment]
It worked. Thanks a lot!
