### ISSUE TITLE
Built-in cross platform better file explorer

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#118193]
Hiya! Something that would be cool is rather then opening finder, or file explorer for example this could all be done via a window in VSCode, for example going to file -> open folder opens a window with the current folders. You can go back 1 directory by typing `..`, and, using something like `../..` would take you back 2 directories, and create folders by pressing the new button, and files as well. Overall, would mean you don't have to stick to opening file explorer and just do it inside VSCode.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog though we will probably not add it. Let's keep open to gather more feedback. Thanks

**Comment by Milo123459** [comment]
Sounds good!
