### ISSUE TITLE
System.ArgumentOutOfRangeException: Cannot use Double Quotation in Terminal 

### ISSUE THREAD

**Issue by deruta1992** [microsoft/vscode#118163]
When I typed double quotation("), System.ArgumentOutOfRangeException has occured.

------
直前 19 個のキー:
 g i t Space a d Backspace Backspace c o m m i t Space - m Space 
"

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの
次元のバッファー サイズ未満を指定しなければなりません。
パラメーター名:left
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)  
   場所 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()     
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)    
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()       
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace 
runspace, EngineIntrinsics engineIntrinsics)

**Comment by yume-chan** [comment]
Duplicate of PowerShell/PSReadLine#2268 and others

**Comment by meganrogge** [comment]
please see https://github.com/PowerShell/PSReadLine/issues/2268#issuecomment-791407692
