### ISSUE TITLE
"Git: Delete Branch..." should be on the Source Control context menu

### ISSUE THREAD

**Issue by robross0606** [microsoft/vscode#118138]
The context menu on the Source Control view has a whole section for "Branch" which contains most things you'd want to do except it does not contain "Delete Branch..."

![2021-03-04 16 17 45](https://user-images.githubusercontent.com/2965467/110032966-c6971d00-7d06-11eb-846f-03681774ab82.png)

This seems like a strange omission when the opposite ("Create Branch...") is there and the capability to do a branch delete is available from the action bar:

![2021-03-04 16 33 03](https://user-images.githubusercontent.com/2965467/110033564-900dd200-7d07-11eb-81a1-aae6f18fe43f.png)

Please add "Delete Branch..." to this menu.

**Comment by eamodio** [comment]
Good call!

**Comment by RPwnage** [comment]
I'll try to work on this issue. is it still up?

**Comment by RPwnage** [comment]
Added the Submenu Item in the linked pull request.

**Comment by nourhj99** [comment]
Hello, I am a new member of this community. 
I am trying to begin with this bug. 
Can you help me and tell me from where to begin please? Which file to look for?

**Comment by RPwnage** [comment]
I've already submitted a fix for this issue. #118542

**Comment by eamodio** [comment]
To Verify:

- Make sure _Delete Branch..._ shows up in the context menu below
![Context menu](https://user-images.githubusercontent.com/2965467/110032966-c6971d00-7d06-11eb-846f-03681774ab82.png)
