### ISSUE TITLE
Support to set selections on notebook editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#118108]
https://github.com/microsoft/vscode/blob/e56182e67f2d44ec926fbbd3be4a4cf3817ee664/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L631-L631

**Comment by rebornix** [comment]
We will support setting both `selection` and `focus`

**Comment by rebornix** [comment]
`options?.cellSelections` can be applied to the editor now already.
