### ISSUE TITLE
Be Brave and Remove Cut/Copy/Paste From The Right-Click Menu

### ISSUE THREAD

**Issue by louisreingold** [microsoft/vscode#118172]
Remove cut/copy/paste from the right click menu.

Developers know how to use these keyboard shortcuts.

If someone new to the game doesn't know about Command+X/C/V, you'll be doing them a favor when they right click, wonder where it is, Google, and learn to use their keyboard.

<img width="274" alt="Screen Shot 2021-03-04 at 11 50 10 PM" src="https://user-images.githubusercontent.com/6425257/110084095-645d0d00-7d44-11eb-9325-6b89bc3f1eff.png">

**Comment by gjsjohnmurray** [comment]
I disagree. If I am doing a bunch of work with the mouse why make me have to switch to the keyboard?

**Comment by Leo512bit** [comment]
And what's the upgrade anyway? It only looks like you want it  for the sake of removing it...

**Comment by deefdragon** [comment]
I mean, I am always in favor of adding options to customize I guess, but this just seems frivolous.

**Comment by alexdima** [comment]
Maybe we will add support to be able to customize the context menu and then you would be able to do this by yourself, but we have no plans to remove cut/copy/paste from the context menu for everyone.
