### ISSUE TITLE
Opening Files

### ISSUE THREAD

**Issue by ruchirpadhye** [microsoft/vscode#118165]
Issue Type: <b>Bug</b>

The file i click on doesn't open up on a new tab. Instead, it closes the previous file. I have to drag the file for the Expoler to open it without closing the previous files.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19043

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.2.603412351
tabnine-vscode|Tab|3.2.8
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0

</details>

**Comment by gjsjohnmurray** [comment]
This is called 'preview mode' 

Please search for information about it at code.visualstudio.com

**Comment by isidorn** [comment]
```
	"workbench.editor.enablePreview": false,
```
