### ISSUE TITLE
program is slowing down after 10,000 lines of code written.

### ISSUE THREAD

**Issue by furkankinyas** [Microsoft/vscode#11811]
- VSCode Version: 1.5.1
- OS Version: 10.11.6

**Comment by alexandrudima** [comment]
@furkankinyas Can you please provide a file that can help us reproduce the slowness you are experiencing. For example, here I am copy-pasting up to 10k lines and it works fine for me. Perhaps this is happening in a certain file type or in a certain file shape.

![10k](https://cloud.githubusercontent.com/assets/5047891/18433605/e28614c0-78e8-11e6-9e6d-104c5f040c2e.gif)

**Comment by alexandrudima** [comment]
@furkankinyas Do you have a laptop with a touchscreen?

**Comment by alexandrudima** [comment]
Closing after a number of days without a reply.
