### ISSUE TITLE
remote ssh portforward fail auto up

### ISSUE THREAD

**Issue by jjasoncool** [microsoft/vscode#118184]
relative to:
https://github.com/microsoft/vscode-remote-release/issues/4601

- VS Code Version:1.54
- OS Version: fedora 33

Steps to Reproduce:

1. install Remote - SSH ms-vscode-remote.remote-ssh
2. install PHP Debug
3. before upgrade to 1.54 debug will auto start port forwarding.
![圖片](https://user-images.githubusercontent.com/24731867/110095752-31fcef80-7dd8-11eb-870d-0cf50ab6047b.png)

4. bug in new 1.54 this will fail. (need manual add, the new version seems change the UI or other things?)
![圖片](https://user-images.githubusercontent.com/24731867/110095817-43de9280-7dd8-11eb-8b66-62dbae2be3b5.png)

Does this issue occur when all extensions are disabled?: No

**Comment by alexr00** [comment]
For SSH remote connections we changed the default for how we discover ports to forward. 
Old "process" behavior: VS Code looks at your running processes and finds ports to forward there.
New "output" behavior: VS Code looks at your debug and terminal output and finds ports to forward there.

You can change back to the "process" behavior using the setting `remote.autoForwardPortsSource`.

**Comment by jjasoncool** [comment]
> For SSH remote connections we changed the default for how we discover ports to forward.
> Old "process" behavior: VS Code looks at your running processes and finds ports to forward there.
> New "output" behavior: VS Code looks at your debug and terminal output and finds ports to forward there.
> 
> You can change back to the "process" behavior using the setting `remote.autoForwardPortsSource`.

I have change `remote.autoForwardPortsSource` to process, same behavior.

**Comment by eugenebnd** [comment]
This also breaks port-forwarding for `kubectl port-forward`

**Comment by alexr00** [comment]
Where did you change `remote.autoForwardPortsSource`? It will need to be changed in your remote user settings, not just your regular user settings. Example (yours would say something about SSH, not Dev Container)

![image](https://user-images.githubusercontent.com/38270282/110343026-58b36400-802c-11eb-8b21-3b59fc2599e9.png)

**Comment by jjasoncool** [comment]
> Where did you change `remote.autoForwardPortsSource`? It will need to be changed in your remote user settings, not just your regular user settings. Example (yours would say something about SSH, not Dev Container)
> 
> ![image](https://user-images.githubusercontent.com/38270282/110343026-58b36400-802c-11eb-8b21-3b59fc2599e9.png)

I'm using settings.json, direct add string in the settings.json file.
![圖片](https://user-images.githubusercontent.com/24731867/110403259-c193ee00-80b7-11eb-8688-5f239da1f721.png)

**Comment by alexr00** [comment]
You'll need to edit your Remote settings.json file, not your usual local user settings.json file.
