### ISSUE TITLE
Direct Calling variable from console for checking that specific variable output like spyder after running the code.

### ISSUE THREAD

**Issue by sabbir-ahamed-maruf** [microsoft/vscode#118122]
At first take my SALAM. Hello everyone. I am here with my first query to developers , for adding this features in vs code. If it already present let me know. Actually i am new on vs code.

I have been using spyder for a while. The features i missed in vs code is there any way to check specific variable by calling it from console. I know there is debugging option but i am more familiar with console calling. 

Understanding:
suppose i type  a = 2 in a python file. Now if i wanted to see the result then i have to print by typing print(a)
Now i wanted to see this "a" variable result from console by calling the variable name and console will show me the ans 2.

I think i can clearly describe to you what i want. I have include and image for understanding. Sorry for my bad English. 

![image](https://user-images.githubusercontent.com/77874084/110010664-c0299500-7d48-11eb-9f61-e1be78e679fb.png)

**Comment by IllusionMH** [comment]
Partially looks like Jupyter Notebooks. Have you seen https://code.visualstudio.com/docs/python/jupyter-support ?

**Comment by sabbir-ahamed-maruf** [comment]
Yeah It seems like that. I also used jupyter notebook. Do you have another suggestion like console type extension for python.
