### ISSUE TITLE
Improve Info Dialog when an extension cannot be installed in VS Code Web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#118104]
Improve following info dialog while installing the extension in web

![image](https://user-images.githubusercontent.com/25310137/109086455-71348d80-76c0-11eb-9e55-c1e694c061f2.png)

Suggestion from @chrisdias: 

"The 'Debugger for Microsoft Edge' extension is not available in VS Code Web. Click 'More Information' to learn more."

With two buttons: <<< More Information >>> <<< OK >>>

Even better, I should not be able to click on "Install" at all.  The Extension UX could disallow installation in the Web for UI/Desktop extensions with helpful text there.

**Comment by sandy081** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/10746682/112025964-0860f980-8b36-11eb-89d5-d1001414f27b.png">

**Comment by sandy081** [comment]
@chrisdias @egamma FYI

**Comment by alexr00** [comment]
The dialog looks good. However, the "More Information" link goes to https://code.visualstudio.com/docs/remote/codespaces which doesn't seem correct. Intended?

**Comment by sandy081** [comment]
Yes, planning to add a FAQ there for this.
