### ISSUE TITLE
vscode-typescript temp files still not deleted properly

### ISSUE THREAD

**Issue by ariccio** [microsoft/vscode#118150]
- VS Code Version: 1.53.2
- OS Version: 10.0.19042

Steps to Reproduce:

1. Use vscode under heavy system load on Windows.

Does this issue occur when all extensions are disabled?: Yes/No

(This is an Algorithmic mistake)

I'm opening this as a tracking type bug. My `vscode-typescript` temporary files are still not *reliably* being deleted despite the change in https://github.com/microsoft/vscode/pull/73801

I strongly suspect this is because of an almost universally common mistake seen in rimaf - almost nobody ever actually deletes files correctly on windows, it's not obvious at all how to do it correctly unless you know how the windows filesystem works inside the kernel - that I've already filed a bug for:
https://github.com/isaacs/rimraf/issues/226

I do not recommend vscode fixing this issue itself.

**Comment by ariccio** [comment]
As a curious and entertaining side note, I discovered this while ETW boot profiling. This interacted with the Windows User Profile service profile loading to cause a 5 second slowdown at boot, because it's enumerating the temporary directory. Spooky action at a distance!
![vscode-typescript](https://user-images.githubusercontent.com/2142308/110045155-47124980-7d18-11eb-8a7d-57c9f9b414b6.png)
![vscode-typescript_2](https://user-images.githubusercontent.com/2142308/110045164-4974a380-7d18-11eb-8458-3b9004ca5d65.png)

**Comment by mjbvz** [comment]
We switched to use `fs.rmdirSync` instead of rimraf: https://github.com/microsoft/vscode/commit/a0855b30c702532d43926c0a120302a39aea2fcc

Are you seeing this with the latest VS Code builds?
