### ISSUE TITLE
file preview scroll bar no text

### ISSUE THREAD

**Issue by MirceaS** [microsoft/vscode#118148]
Issue Type: <b>Bug</b>

Sometimes, when I open new files, or switch from one file to another via jumps, the text on the "scroll-bar" previews of files in all my opened tabs disappears, but not the coloured markers.

![Screenshot from 2021-03-05 01-05-04](https://user-images.githubusercontent.com/5909705/110042977-4517ad00-7d4f-11eb-877d-b7d1eeb9db10.png)

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1349)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.65GB (0.21GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id fb0187f1-e035-463e-9c01-7991c574579a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
haskell|has|1.2.0
haskell-linter|hoo|0.0.6
language-haskell|jus|3.4.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351
cpptools|ms-|1.2.2
java|red|0.75.0
scala|sca|0.5.2
metals|sca|1.10.0
sourcegraph|sou|1.2.3
stylish-haskell|vig|0.0.10
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
gitblame|wad|6.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by alexdima** [comment]
This looks like a gpu rendering problem. Does this issue reproduce when launching `code --disable-gpu` ?
