### ISSUE TITLE
Prompt to save untitled file before run/debug #111850

### ISSUE THREAD

**Issue by RickBankers** [microsoft/vscode#118127]
Follow up on the recent change put in from [#111850](https://github.com/microsoft/vscode/issues/111850#). I feel like this was forced on us because of new coders. Saving your code regularly is part of being a good developer and implementing a big change like this to accommodate people learning seems like a step in the wrong direction. You're teaching new coders to "assume" the code is saved automatically.

I'd like to see this as a flag that can be enabled/disabled. From a powershell perspective you can run scripts from ISE without saving which is a workaround depending on the powershell execution policy. It would also help new coders understand "saving" at certain points is important, regardless of whether you are going to debug or not.

**Comment by gjsjohnmurray** [comment]
Please update to 1.54 (just released) and use the new `debug.saveBeforeStart` setting.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for answering
