### ISSUE TITLE
Links Broken in Markdown Preview Custom Editor

### ISSUE THREAD

**Issue by BeatLink** [microsoft/vscode#118176]
- VS Code Version: 1.53.2
- OS Version: Linux Mint Cinnamon 20.1

Issue created in response to https://github.com/microsoft/vscode/issues/84520#issuecomment-724910644

Steps to Reproduce:

1. Add the following code to your settings.json:
```json
"workbench.editorAssociations": [
    {
        "viewType": "vscode.markdown.preview.editor",
        "filenamePattern": "*.md"
    }
]
```
2. Start VSCode
3. Open a markdown file with a link
4. Click on the link
5. Nothing Happens (preview page should navigate to the link)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I just tested this but it seems to work for me. Can you please share an example where it does not work?

**Comment by oskude** [comment]
markdown filesystem links like:

- `[foo](./foo/foo.md)` (should open foo.md in the same preview tab)
- `[bar](./bar/bar.js)`(should open bar.js in new editor tab)

worked yesterday* in the markdown preview, but not anymore with:
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-22T15:03:39.218Z
Electron: 11.4.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.16-arch1-1
```
*sorry, i don't keep package logs so dunno what my previous version was >.<

**Comment by oskude** [comment]
seems to be fixed already in latest git ~~master~~main (at time of writing: 6c747e75dad2fb2cc43fc39f64e012af956a3bbc)

**Comment by mjbvz** [comment]
Closing. Let me know if there's a case that's not working
