### ISSUE TITLE
Terminal goes black with no reason :(

### ISSUE THREAD

**Issue by jesusgn90** [microsoft/vscode#118183]
- VS Code Version: 
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-7642-generic
```
- OS Version: Ubuntu 20.04 (Pop!_OS 20.04 LTS)

Steps to Reproduce:

1. Open VSCode, and open a terminal
2. Ramdonly face the bug :S

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/8860227/110094762-779bc700-7d9c-11eb-88ab-2079b5cd73aa.png)

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by jesusgn90** [comment]
It happens randomly, this time I switched my view to Slack and when I come back, here it is, the dark terminals problem :( 

![image](https://user-images.githubusercontent.com/8860227/110767883-fee2b200-8256-11eb-8d38-0e596cfb89d3.png)

**Comment by sspleo** [comment]
This happens to me as well. I face this problem whenever I logged out for a night and get back.

**Comment by meganrogge** [comment]
duplicate #69665
