### ISSUE TITLE
Jupyter (Insider) Output Cell Scrollbar not working/showing

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#118117]
@Tomiha commented on [Thu Mar 04 2021](https://github.com/microsoft/vscode-jupyter/issues/5027)

## Environment data

-   VS Code version: 1.54.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): 2021.2.582707922
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro (10.0.19041)
-   Python and/or Anaconda version: Python 3.7.6 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour
Having a vertical scrollbar in the Notebook Output Cells when contents exceed a certain value.
Related Jupyter settings are set:
 - Jupyter: Enable Scrolling For Cell Outputs (TRUE)
 - Jupyter: Max Output Size (100, Default was 200)

## Actual behaviour
Jupyter settings related to output cell scrolling seem to be ignored.
No scrollbar is added to a long output cell (must use the main scrollbar to scroll all the way down to the next input cell).

## Steps to reproduce:
INPUT:
for i in range(0.1000):
  print(i)

OUTPUT:
Values from 0 to 1000 printed to output, but without scrollbar in the output cell.
Results in an output that is over 4 pages long.
(Scrollbar visible in GIF is the main document scrollbar, what I want is an individual Output Cell scrollbar)

![vscode_jupyter_scollbug](https://user-images.githubusercontent.com/2349894/109940205-1b6c7080-7cd2-11eb-8ceb-49e3307f72cc.gif)

---

@DonJayamanne commented on [Thu Mar 04 2021](https://github.com/microsoft/vscode-jupyter/issues/5027#issuecomment-790719294)

> Jupyter settings related to output cell scrolling seem to be ignored.

Thanks for filing this issue. Unfortunately the new Notebook in Insiders does't respect all of the settings. We'll try to get this functionality in.

**Comment by DonJayamanne** [comment]
This is a feature request. 
In our old implementation of (webview) notebooks, we used to add scrollbars into the output so users could scroll the output instead of having to scroll the entire notebook.
As you can see above the user is scrolling he entire notebook.

Classic Jupyter does the same thing, see below.

![Screen Shot 2021-03-04 at 07 57 42](https://user-images.githubusercontent.com/1948812/109991656-5c0ebe80-7cbf-11eb-91aa-d02557d6f02a.png)


@rebornix /cc

**Comment by joyceerhl** [comment]
A user just opted out of the native notebooks interface due to this issue: https://github.com/microsoft/vscode-jupyter/issues/5629

**Comment by DonJayamanne** [comment]
Closing this issue for now as we believe this is the a good UX, will re-review in Jupyter extension repo.
