### ISSUE TITLE
Snippets: auto import

### ISSUE THREAD

**Issue by Mangatt** [microsoft/vscode#118130]
I think that it would be great if user snippets could support auto-importing of required modules like this:

```json
{
	"react.useEffect": {
		"prefix": "eff",
		"body": [
			"useEffect(() => {'",
			""
			"}, [])",
		],
		"import": ["react.useEffect"]
	},
}
```

which would add `useEffect` import from `react` at beginning of file when required.

Ideally it would extend current import when present instead of creating new entry (`import React from 'react'` would become `import React, { useEffect } from 'react'`.

**That would be huge time-saver for a lot of developers, as this is thing that we are dealing with on daily basis.**

**Comment by Mangatt** [comment]
@vscodebot This is not duplicate.

Just to clarify - this is just simple example that really does not need this feature and is just fine with auto imports. But there are more complicated snippets that would benefit from this.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"
