### ISSUE TITLE
Provide API to change Notebook cell language

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#118278]
Currently the only way to update the notebook cell language is to replace the cell.

In Jupyter we have things call cell magics.
1. Create a cell with the following text
```
%%html
<h1>Hello</h1>
```
2. Run this cell with a python kernel and HTML will be displayed.
Similarly there are other magics, HTML, Bash, SVG, JavaScript, ruby, etc...
Basically its an easy way to write code in another langauge and get that script executed and results displayed in the output.

I would like Jupyter users with cell magics to get the benefits of VS Code.
* Syntax highlighting
* Code completion & the like

Today the user will have to manually change the language of the cell to `html` or other.
A better experience would be (my suggestion) is for Jupyter to automatically detect such cell magics & change the language as the user is typing the code in the cell.

I.e. as soon as the use types in `%%html` we could change the cell langauge to `html` & voila user now has syntax highlighting & the like for HTML in this cell.

Unfortunately this can only be done via `Cell Replace` API today, & I feel that's a very destructive & heavy API.
If while the user is typing in the text editor we change the cell language, then the focus changes.

I was hoping for a simpler API where we could just change the language.

FYI - Today we use this same API to change the cell language when users select different kernels and there's a single empty cell (we change the langauge of the cell to reflect the language of the kernel).

Realted to https://github.com/microsoft/vscode-jupyter/issues/4588

@rebornix /cc

**Comment by rebornix** [comment]
`NotebookCell` has a `TextDocument` attached so you can use `vscode.languages.setTextDocumentLanguage` to update its language.

**Comment by rebornix** [comment]
With that being said, there is an issue with cell language status item not reflecting the language used in the cell editor https://github.com/microsoft/vscode/issues/117936
