### ISSUE TITLE
Unable to open Getting Started

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#118255]
Version: 1.55.0-insider
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:41:28.520Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Now every time I open a new empty window in Insiders, I see this error:
![image](https://user-images.githubusercontent.com/9721254/110166572-92813200-7dc2-11eb-8212-3765b0e06dd6.png)

I have these two settings:
```
"workbench.experimental.gettingStarted": true,
"workbench.startupEditor": "gettingStarted"
```

**Comment by JacksonKearl** [comment]
Same as the earlier issue, you can run Getting Started: Reset progress as workaround.
