### ISSUE TITLE
Provide platform "Copy As..." submenu

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118208]
Provide a `editor/context/copy` core submenu, in the editor context menu.

cc @alexr00, @eamodio (gitlens) for adoption once this is in.

**Comment by rebornix** [comment]
Quick question, once we have this sub menu. Should "Copy as Plain Text" and "Copy as Rich Text" (w/ syntax highlighting) as part of the menu? Also these two are builtin commands, do they always show at the very top?

**Comment by joaomoreno** [comment]
Yes, I think so. cc @egamma

**Comment by eamodio** [comment]
I'd think the Copy Relative Path should too

**Comment by joaomoreno** [comment]
@alexr00 I forgot to update the original post in this issue: there's also the `menuBar/edit/copy` submenu, in case you're interested in being there as well.

**Comment by alexr00** [comment]
@joaomoreno  👍 already adopted both menu entries in GHPRI.

**Comment by joaomoreno** [comment]
This will be verified via @alexr00's feature. @alexr00 can you mark this as verified?
