### ISSUE TITLE
Notebook API: Allow the kernel of a notebook document to be updated when executing a cell

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#118280]
We have a problem right now where the kernel used to execute cell changes once the cell executes. The reason for this is it becomes a 'live' version of the original kernel definition. 

This may help:
![image](https://user-images.githubusercontent.com/19672699/110188776-bac45d00-7dd1-11eb-8c66-dd0b6c41ebfb.png)

The current kernel is Python 3. However as soon as I execute any code, we create a connection to the remote jupyter server (this is in our remote case) and the kernel is now a 'live' kernel (the first kernel in the list. It is based on the Python 3 kernel but is now running)

The current API (well as far as I can tell) only allows us to refresh the entire list of kernels. This may update the preferred kernel but it doesn't change the kernel currently active for this notebook. 

We need to update it to the 'live' version.

**Comment by rebornix** [comment]
This can be solved by the push model of kernel api. @jrieken can confirm.

**Comment by jrieken** [comment]
This has happened with the new NotebookControllers - properties like label, description, supported languages etc can be modified freely
