### ISSUE TITLE
Latex Support

### ISSUE THREAD

**Issue by larissaford** [microsoft/vscode#118262]
Hello, I tried to make sure there aren't any duplicates of this feature request.

I would really like more support for latex. What I mean is supporting the conversion of things within a $ symbol into latex. For an example, check out how anaconda does this with their jupyter notebooks. Without this feature, the jupyter notebook in vs code isn't worth using for me since I primarily use it for math and need to type equations in a readable format. I also tried searching for any latex support within this insiders version but I didn't see any. Thank you.

**Comment by IllusionMH** [comment]
Most likely combination of work in progress feature https://code.visualstudio.com/updates/v1_54#_extensible-markdown-renderers-for-notebooks and maybe extension to support required formula format https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview should do the trick.

**Comment by gusbemacbe** [comment]
Actually it is not VSCode's problem, but VSCode's Jupyter extension. You should ask at https://github.com/microsoft/vscode-jupyter.

**Comment by rebornix** [comment]
yup we are already working on this.

**Comment by colombod** [comment]
Issue #dotnet/interactive/issues/1143 is asking for this too

**Comment by gusbemacbe** [comment]
@larissaford, check https://github.com/microsoft/vscode-jupyter/issues/1216.

**Comment by rebornix** [comment]
Let's merge the discussion into https://github.com/microsoft/vscode/issues/119536, thank you all for the feedback.
