### ISSUE TITLE
Default newUntitledFile keybinding is invalid

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118246]
Open default keybindings json and you'll see problems. The schema requires args, we should follow our own rules:

![image](https://user-images.githubusercontent.com/2193314/110158564-6358c980-7d9e-11eb-885e-dd898b166cb7.png)

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/commit/89d0406f06404dd5f7b0fe0541e05464a348c1e7

**Comment by rebornix** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/117534 and already fixed.
