### ISSUE TITLE
PowerShell Fails to Load

### ISSUE THREAD

**Issue by InteXX** [microsoft/vscode#118289]
Issue Type: <b>Bug</b>

Since the most recent update, PowerShell now fails to load at startup.

**VSCode version**
```
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**PowerShell startup logs**
```
3/5/2021 6:09:39 PM [NORMAL] - Visual Studio Code v1.54.1 64-bit
3/5/2021 6:09:39 PM [NORMAL] - PowerShell Extension v2021.2.2
3/5/2021 6:09:39 PM [NORMAL] - Operating System: Windows 64-bit
3/5/2021 6:09:39 PM [NORMAL] - Language server starting --
3/5/2021 6:09:39 PM [NORMAL] -     PowerShell executable: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
3/5/2021 6:09:39 PM [NORMAL] -     PowerShell args: -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615000179-2421435c-f00a-4631-8137-216a2f9766e01615000169526\EditorServices.log' -SessionDetailsPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-13416-430208' -FeatureFlags @() 
3/5/2021 6:09:39 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2021.2.2' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2021.2.2 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\logs\1615000179-2421435c-f00a-4631-8137-216a2f9766e01615000169526\EditorServices.log' -SessionDetailsPath 'c:\Users\Work\.vscode\extensions\ms-vscode.powershell-2021.2.2\sessions\PSES-VSCode-13416-430208' -FeatureFlags @() 
3/5/2021 6:09:39 PM [NORMAL] - powershell.exe started.
3/5/2021 6:09:39 PM [NORMAL] - Waiting for session file
3/5/2021 6:09:41 PM [NORMAL] - Session file found
3/5/2021 6:09:41 PM [NORMAL] - Registering terminal close callback
3/5/2021 6:09:41 PM [NORMAL] - Registering terminal PID log callback
3/5/2021 6:09:41 PM [NORMAL] - powershell.exe PID: 21400
3/5/2021 6:09:41 PM [NORMAL] - Language server started.
3/5/2021 6:09:41 PM [NORMAL] - {"status":"started","languageServiceTransport":"NamedPipe","languageServicePipeName":"\\\\.\\pipe\\PSES_zxrkrteq.iku","debugServiceTransport":"NamedPipe","debugServicePipeName":"\\\\.\\pipe\\PSES_se3oujrs.ani"}
3/5/2021 6:09:41 PM [NORMAL] - Connecting to language service on pipe \\.\pipe\PSES_zxrkrteq.iku...
3/5/2021 6:09:41 PM [NORMAL] - Language service connected.
3/5/2021 6:09:42 PM [ERROR] - Could not start language service: 
3/5/2021 6:09:42 PM [ERROR] - Error: Connection to server got closed. Server will not be restarted.
```

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.32GB free)|
|Process Argv|--crash-reporter-id e69e24da-8cea-4231-bfc0-80f4f0d6711b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.2.2
code-settings-sync|Sha|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by TylerLeonhardt** [comment]
Hi @InteXX. The issue you are seeing is with the PowerShell extension for VS Code and not VS Code itself.

I believe you may want to go comment on this issue:

https://github.com/PowerShell/vscode-powershell/issues/3227

Which is in the PowerShell extension's repo.

**Comment by InteXX** [comment]
@TylerLeonhardt 

Please reopen. The issue, while it manifests in the extension, is caused by VSCode. The extension was working properly until the latest VSCode update was applied. Therefore, the issue was caused by VSCode.

**Comment by TylerLeonhardt** [comment]
@InteXX just to be sure, can you please verify that by grabbing the last version of VS Code which can be found here:

https://code.visualstudio.com/updates/v1_53

The download link is at the top of this page.

**Comment by InteXX** [comment]
@TylerLeonhardt 

> please verify that by grabbing the last version

Certainly, but it's unclear what the different download labels mean. I'm not seeing where `User | System | Arm` is explained. Also, could you clarify that I should downgrade from 1.54.1 to 1.53 as your link suggests.

_____
p.s. I relaxed the tone of my previous post a bit, as I realized it was sounding a bit demanding. Pardon me, please.

**Comment by TylerLeonhardt** [comment]
> I'm not seeing where User | System | Arm is explained. 

User - install VS Code for just this user
System - install VS Code for the whole System (if you have multiple users)
Arm - install the Arm version of VS Code (doesn't apply because you're on Windows x64)

I'd recommend the `User`. Our team always recommends `User`, generally. But we offer a System install if you need something like that.

> Also, could you clarify that I should downgrade from 1.54.1 to 1.53 as your link suggests.

Yeah so you said `Version: 1.54.1 (user setup)` in your issue so I'd like you to downgrade to the last minor version which is 1.53.

**Comment by InteXX** [comment]
> I'd like you to downgrade

Very well. I'm tied up for the rest of the day today, but I'll get to this tomorrow.

**Comment by meganrogge** [comment]
@InteXX if this is now working for you, please close this issue

**Comment by InteXX** [comment]
This is working now, thank you.
