### ISSUE TITLE
Init height of markdown cell in editing mode is wrong

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#118283]
- VS Code Version: 1.55-Insiders
- OS Version: macOS

Steps to Reproduce:

* Open endgame.github-issues
* Edit markdown cel
* Reload

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/110191125-b4d37980-7ddb-11eb-8ee0-77a9e656d78c.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Sorry, missed that you had already opened this.

Fixed in #118581
