### ISSUE TITLE
Horrible lag and MacOS Freezing on updating to 1.54

### ISSUE THREAD

**Issue by eselkin** [microsoft/vscode#118296]
Issue Type: <b>Bug</b>

Just opening any project will cause the system to lag and the spinner to appear. OS becomes unresponsive until all windows of VS code are closed.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 9, 6|
|Memory (System)|32.00GB (4.61GB free)|
|Process Argv|--crash-reporter-id b5d0a7ea-4fcb-4a46-8101-17d5ba57d68f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Handlebars|and|0.4.1
vscode-apollo|apo|1.18.2
handlebars-preview|cha|1.1.0
gitignore|cod|0.6.0
vscode-eslint|dba|2.1.14
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
github-actions|for|0.0.1
vscode-styled-components|jpo|1.5.0
kite|kit|0.142.0
vscode-github|Kni|0.30.4
graphql-for-vscode|kum|1.15.3
theme-monokai-pro-vscode|mon|1.1.18
vscode-docker|ms-|1.10.0
python|ms-|2021.2.625869727
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
remote-wsl|ms-|0.54.0
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.5.0
markdown-preview-enhanced|shd|0.5.16
markdown-all-in-one|yzh|3.4.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30265443
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
Please review advice at https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by eselkin** [comment]
The only difference was 1.54 (all extensions were the same)

**Comment by TylerLeonhardt** [comment]
Were you able to repro without extensions installed?

/needsMoreInfo
