### ISSUE TITLE
Keep track of function call chain

### ISSUE THREAD

**Issue by moonlight16** [microsoft/vscode#118236]
Many code languages have the feature "Go to Definition".  Many times you want to drill lower to see the code for the underlying functions/methods, but then you want to walk your way backwards to where you started.  I find myself copying/pasting the names of the methods into a notepad so I can remember.   In particular if you have long call chains.  

It would be nice if there was a navigation that kept track of the call chain as you navigate lower in the call stack.  The navigation would allow you to click on the function/method to jump back to the call.

**Comment by IllusionMH** [comment]
There is existing feature Call Hierarchy which can show incoming and outgoing calls for functions.
See https://code.visualstudio.com/updates/v1_43#_call-hierarchy-support-for-javascript-and-typescript or search "Call Hierarchy" in docs.

Have you tried this feature?

**Comment by moonlight16** [comment]
It seems this feature is only supported with JS and TS.  I mostly code in C, C++, Golang, and Python.

**Comment by IllusionMH** [comment]
VS Code doesn't support these languages out of the box so extensions need to provide support for this feature - VS Code provides API.

Here's for example request for Python https://github.com/microsoft/python-language-server/issues/888, however Pylance should have support https://github.com/microsoft/pylance-release/issues/109.

You can check repositories of extensions that provide support for other languages, support/monitor existing requires or create new feature requests if there are no existing.

**Comment by moonlight16** [comment]
Ok, your right.   The "Go to Definition" feature is specific to the language extension, in this case the C/C++ extension I'm using.  

I'm using `vscode-cpptools`, and found this request:  https://github.com/microsoft/vscode-cpptools/issues/16

I'll close this feature request.
