### ISSUE TITLE
Default notebook.fold/unfold keybindings are invalid

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118245]
Open default keybindings json and you'll see problems. The schema requires args, we should follow our own rules:

![image](https://user-images.githubusercontent.com/2193314/110158449-41f7dd80-7d9e-11eb-8cb9-1ecc7ffc20fb.png)

**Comment by rebornix** [comment]
They should be optional, good catch ;)

**Comment by rebornix** [comment]
I don't how to express this with the keybinding args: what I did

```
args: [
	{
		name: 'index',
		description: 'The cell index',
		schema: {
			'type': 'object',
			'required': ['index', 'direction'],
			'properties': {
				'index': {
					'type': 'number'
				},
				'direction': {
					'type': 'string',
					'enum': ['up', 'down'],
					'default': 'down'
				},
				'levels': {
					'type': 'number',
					'default': 1
				},
			}
		}
	}
]
```

I want to make the args optional, but when a arg is provided, it must at least has `index` and `direction` properties. However, it seems that if the arg has required property, the arg is then required for the command, which IMHO is not correct.

@aeschli may I ask what's the right thing to do here?

**Comment by aeschli** [comment]
@jrieken Looks like what we talked about lately. Did you find a solution?

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/117534
