### ISSUE TITLE
Allow ${env:XXX} expansions in more places

### ISSUE THREAD

**Issue by aivazis** [microsoft/vscode#118232]
I would like to be able to use environment variable expansions in more places. As an example, I have attached a snippet from my `c_cpp_properties.json`, which uses information from the environment to improve the way the editor integrates with my build procedure. There are obvious workarounds, but they all involve manual expansion and multiple almost entirely identical configuration sections.

{
    "configurations": [
        {
            "name": "macports - mm",
            "includePath": [
                "${workspaceFolder}/**",
                "${env:USER_TOOLS_DIR}/mm/${env:mm_bld_abi}/include/**",
                "/opt/local/include/**"
            ],
            "defines": [],
            "macFrameworkPath": [
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "compilerPath": "/opt/local/bin/${env:mm_bld_compiler}",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "macos-${env:mm_bld_compiler}-arm64"
        }
    ],
    "version": 4
}

In this example, `intelliSenseMode` complains that the setting is not in the approved set, clearly because it doesn't perform the ${env:XXX} expansion before comparing the supplied value against the canonical set

**Comment by aeschli** [comment]
Please file the request against the cpp extension: https://code.visualstudio.com/docs/languages/cpp
