### ISSUE TITLE
Integrated Terminal is not working

### ISSUE THREAD

**Issue by sgrant0225** [microsoft/vscode#118286]
My VS integrated terminal is not working.  it keeps saying starting and it has been doing this for an hour now.  Still researching on how to fix this.  I restarted my computer, upgraded my computer, killed the terminal, close VS code and opened it back again.  I'm using Macbook pro Big Sur 11.2

VS Version: 1.54.1

**Comment by meganrogge** [comment]
Hi are there any errors if you go to Help -> Toggle Developer Tools and click the console tab?

**Comment by meganrogge** [comment]
And when did this start happening? 

Also, do you have any extensions installed? If so, please run the command (cmd + shift + p) `Help: Start Extension Bisect` to see if any of your extensions might be causing this issue.

**Comment by BuiChiTrung** [comment]
Same problem, I installed Live Server(via terminal) and Updated to vscode 1.54 yesterday and don't know which one causes the issue.

**Comment by BuiChiTrung** [comment]
Try openning vs code via terminal(not the icon) fixes my issue

**Comment by sgrant0225** [comment]
@meganrogge  Hello, thanks for responding.  I went to Help -> Toggle Developer Tools -> Console and there's one error that says, unable to resolve your shell environment in a reasonable time. Please review your shell configuration

**Comment by sgrant0225** [comment]
@BuiChiTrung I tried what you suggested and it did not work.

**Comment by sgrant0225** [comment]
The issue is resolved.  one of my schools tech specialist recommend that I uninstalled the VS code and reinstalled it and updated the control line in my computer terminal and it seemed to fix the issue.
