### ISSUE TITLE
Liveshare

### ISSUE THREAD

**Issue by ankit039** [microsoft/vscode#118223]
Issue Type: <b>Extension Not Available</b>

Cannot find liveshare extension, please provide some solution. 

VS Code version: Code - OSS 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T21:13:58.622Z)
OS version: Linux x64 5.10.18-1-MANJARO

**Comment by aeschli** [comment]
Please provide more information. Describe your steps and maybe add a screenshot.

**Comment by ankit039** [comment]
![image](https://user-images.githubusercontent.com/44525721/110193178-716b2080-7e58-11eb-9db7-84fb8481e9a3.png)
I am trying to get liveshare in my vscode but it cannot be found at extension marketplace.

**Comment by aeschli** [comment]
You are running Code OSS. To access to the Marketplace, you need to use VS Code (stable or insiders).
