### ISSUE TITLE
Localhost 1717

### ISSUE THREAD

**Issue by ParagArora27** [microsoft/vscode#118209]
Issue Type: <b>Bug</b>

I am getting the Localhost 1717 error while authorizing a Salesforce org. Please assist.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (4.67GB free)|
|Process Argv|--crash-reporter-id efb89a1e-9993-4c62-bd07-5726a1273b42|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-pmd|chu|0.5.3
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.9.2
lana|Fin|1.3.5
java|red|0.75.0
vscode-xml|red|0.15.0
LiveServer|rit|5.6.1
salesforce-vscode-slds|sal|1.4.1
salesforcedx-vscode|sal|51.3.0
salesforcedx-vscode-apex|sal|51.3.0
salesforcedx-vscode-apex-debugger|sal|51.3.0
salesforcedx-vscode-apex-replay-debugger|sal|51.3.0
salesforcedx-vscode-core|sal|51.3.0
salesforcedx-vscode-lightning|sal|51.3.0
salesforcedx-vscode-lwc|sal|51.3.0
salesforcedx-vscode-visualforce|sal|51.3.0
sfdx-package-xml-generator|Vig|2.0.5
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by aeschli** [comment]
Can you file this against the Salesforce extension?
