### ISSUE TITLE
Add option to sort files in Explorer side-bar by date modified

### ISSUE THREAD

**Issue by SenH** [Microsoft/vscode#11823]
I'm using VS Code as a simple notebook with text files in a folder. Would be handy if we could sort files by date modified so last edited files are easily accessible.
- VSCode Version:  1.5.1
- OS Version: Win 10 Pro

**Comment by bpasero** [comment]
Landed via https://github.com/Microsoft/vscode/pull/29509

Setting to use: `"explorer.sortOrder": "modified"`
