### ISSUE TITLE
A single task can launch many times if running multiple times while window is loading

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118238]
I had a particularly slow start up just now and I hit ctrl+shift+b a bunch of times, once everything settled it launched 3x for each task:

![image](https://user-images.githubusercontent.com/2193314/110154553-3d7cf600-7d99-11eb-8f48-3701be9e9858.png)

Version: 1.55.0-insider (user setup)
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:40:03.281Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by alexr00** [comment]
This is going to require a lot of refactoring to solve. Will try to tackle next debt week.

**Comment by alexr00** [comment]
Found a simple way to solve it.

**Comment by Tyriar** [comment]
If I try to repro now the default build task no longer works, ctrl+shift+b only shows this now:

![image](https://user-images.githubusercontent.com/2193314/115203852-bbc4fb80-a0ac-11eb-9006-728de3533617.png)

**Comment by alexr00** [comment]
I had reverted the fix since it broke something else. Will try another fix.

**Comment by alexr00** [comment]
Re-applied the fix and fixed the test that it revealed a bug in.

**Comment by Tyriar** [comment]
@alexr00 the issue I hit is still happening in:

Version: 1.56.0-insider (user setup)
Commit: 633562da380f9161ea2fd783e561eed508cfbbea
Date: 2021-04-26T05:14:38.204Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Repro:

1. Reload vscode repo
2. ctrl+shift+b quickly

![image](https://user-images.githubusercontent.com/2193314/116092567-c2c6ad80-a65a-11eb-891f-8baedf4ed7ae.png)
