### ISSUE TITLE
plotly have stopped working, charts do not display after VSCode update 

### ISSUE THREAD

**Issue by deep-learning-newbie** [microsoft/vscode#118297]
- VS Code Version:
- Version: 1.55.0-insider (user setup)
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:40:03.281Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. just plot any chart - for instance 

fig = go.Figure()
fig.add_trace(go.Scatter(x=df['close_TT'], y=df['price'], name='price',  mode="lines",line=dict(color="darkgreen", width=2))) #rgb(67,67,67)
fig.add_trace(go.Scatter(x=df['close_TT'], y=df['sma_short'], name='sma_short',  mode="lines",line=dict(color="lawngreen", width=1)))
fig.add_trace(go.Scatter(x=df['close_TT'], y=df['sma_long'], name='sma_long',  mode="lines",line=dict(color="lightseagreen", width=1)))
fig.show()

as result you will see grey rectangle. it worked today before update
BTW in VSCode it renders takes really long time. 

Does this issue occur when all extensions are disabled?: Yes/No
i can't disable all extensions because at list i can't connect to remote server and can't work with jupyter notebook

**Comment by deep-learning-newbie** [comment]
as i figure out - output mime type should be changed to application/vnd.plotly.v1+json in that case it works but the problem is - it always text/html and i menualy have to chand it every time when run the cell
![image](https://user-images.githubusercontent.com/63535316/110199091-73f35900-7e0b-11eb-88e8-62d2394c6473.png)

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-python/issues
Would you mind filing the issue there?
