### ISSUE TITLE
How to tell vscode do not sort my CompletionItems?

### ISSUE THREAD

**Issue by richard1122** [Microsoft/vscode#11820]
- VSCode Version: 1.6 insider
- OS Version: win10

I'm working on youcompleteme vscode extension. Ycmd provides well ordered completion items.
Is there any way to tell vscode do not sort my completionItem array?

Or could you add sortNumber (or sth like this) to CompletionItem for numeric compare?

**Comment by jrieken** [comment]
There is `CompletionItem#sortText` which we will use instead of the label, however since completions can come from multiple sources sorting is lexical along those two properties
