### ISSUE TITLE
VS Code can only show one tab on apple silicon

### ISSUE THREAD

**Issue by Zieng** [microsoft/vscode#118284]
- VS Code Version: 
```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:45:03.974Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```
- OS Version: 11.2.1 on M1 macbook air

Steps to Reproduce:

1. open one file
2. open another file

Does this issue occur when all extensions are disabled?: Yes

No matter how many files are open, the vs code editor can only show one tab. For example, I open two files but the tab only show the current focused one:

![vscode_tab_display_issue](https://user-images.githubusercontent.com/9816923/110191260-63ba9880-7e62-11eb-81ef-d1c5d651197d.png)

The issue happens when I switched from the intel version to the apple silicon version.

**Comment by bpasero** [comment]
You probably turned tabs of in settings?

**Comment by Zieng** [comment]
> You probably turned tabs of in settings?

Ah Yes! I don't remember I manually turned it off, all I do is just upgrade vs code to the apple silicon one. No idea how it got turned off. Anyway after I turn it on, everything works smoothly. So it's not vs code issue, thanks!
