### ISSUE TITLE
Syntax prompts no

### ISSUE THREAD

**Issue by iOSwang** [Microsoft/vscode#11821]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:34:58.760Z)
- OS Version: Linux x64 4.4.0-36-generic

Steps to Reproduce:

1.totay i update v1.5.1,my grammer tip can`t use
2.i checked go package,i download again,it can`t use

**Comment by ramya-rao-a** [comment]
@iOSwang Can you share a screenshot of the error you get?
Are you having issues with VS Code in general or with an extension?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this.

@iOSwang Please let us know if you are still seeing this issue in VSCode 1.8.1. If you are, please provide some additional information to help us investigate

Thanks
