### ISSUE TITLE
Where are the options for adding a new path like #include armadillo on VS Code 2019?

### ISSUE THREAD

**Issue by chrisriderr** [microsoft/vscode#118254]
Issue Type: <b>Feature Request</b>

I have been trying for weeks to add the Armadillo library but am not able to find anything. All the answers online are for VS 2017 or older. There is no help either. Please provide a simple navigation to add  #include paths.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
Do you mean VS 2019 or VS Code?
If it's VSCode, please file issue against the C++ extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
