### ISSUE TITLE
personal key binding doesn't work

### ISSUE THREAD

**Issue by markDem25** [Microsoft/vscode#11822]
- VSCode Version: windows
- OS Version: 1.5.1

Steps to Reproduce:
the personal key binding doesn't work.
this is my personalization 
[{
    "key": "ctrl+t",
    "command": "workbench.action.terminal.focus",
    "when": "editorTextFocus"
}]

In the previous versions works correctly

**Comment by pericazivkovic** [comment]
OS linux 64, v.1.5.1 does not work also

**Comment by ramya-rao-a** [comment]
@markDem25 Are you having issues while setting key bindings to other commands as well or only with `workbench.action.terminal.focus` ?

**Comment by bpasero** [comment]
This is now: `workbench.action.focusPanel`
