### ISSUE TITLE
Text selection finished above Terminal Window makes loosing focus on Editor Window

### ISSUE THREAD

**Issue by ivan-marinov** [Microsoft/vscode#11825]
- VSCode Version: Version 1.5.1 (1.5.1) 07d663dc1bd848161edf4cd4ce30cce410d3d877 2016-09-08T21:25:39.888Z
- OS Version: OS X El Capitan 10.11.6 (15G1004)

Steps to Reproduce:

1. Have a source editor with some file (tried with js, css) and the internal terminal open
2. Start selecting a text block with track pad, tap and start dragging selection
3. While selecting move pointer above terminal window
4. Finish selecting text by pulling up finger from track pad - make sure you are above terminal window

Expected:
Text is selected and source editor in focus, so next key press will overwrite selection

Actual:
Text is selected but internal terminal window is in focus, so next key press will not overwrite selection, but will input a character in terminal.

Note: When the same steps tried with explorer window instead of terminal, it works as expected. Low priority.

**Comment by Tyriar** [comment]
To clarify, the mouse down event occurs in the editor then mouse up in the terminal which triggers terminal focus. May be an upstream issue.

**Comment by Tyriar** [comment]
This is an issue both in vscode and xterm.js.

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/267
