### ISSUE TITLE
Something is terribly wrong with Powershell debugging

### ISSUE THREAD

**Issue by illusive-man** [microsoft/vscode#118203]
- VS Code Version: 1.55.0 (same for 1.54.0)
- OS Version: 20H2

This behavior is pretty much random. One time it works, next second it doesn't... 

Steps to Reproduce:

1. Open powershell file (after creating basic launch.json file) and run the debug. 
2. If you add vars watch now it's generally working, including updating watch(es) values in real time while pressing Step Over/Step In etc. buttons.
3. Stop debugging and start again. 
4. Add couple variables to watch. Sometimes at this point already new watches don't add in watch pane and existing vars don't update their values. BTW Variables pane works perfectly fine.
5. Sometimes you need to stop and start debugging couple more times (which is perfectly normal when debugging) before Watch pane freeze (not updating values anymore) and adding new watches become impossible. Hitting + sign to add new watch does nothing. 

What's interesting is after VS Code being relaunched and debug has started the Watch pane shows values from previous run not the current! JFYI Script is using CLI executables (namely tf.exe and git.exe) several times, but none of that calls is erroneous. I've disabled all extensions except Powershell one, and tried same steps on both 1.54 regular version and 1.55 Insiders.

And please bear with me, as I don't know if that's VS Code or Powershell extension issue. But since something doesn't update in interface I suppose it's VS Code issue. If not, I will report this issue to Powershell Extension team. I need working debug pretty badly as I'm working on pretty big project. Main question is am I missing something or this indeed is a bug?

Does this issue occur when all extensions are disabled?: Impossible to repro without Powershell extension

**Comment by weinand** [comment]
@isidorn since watches are not part of DAP at all, we should look into this first...

**Comment by isidorn** [comment]
@illusive-man thanks for reporting however this does not happen with other languages, for example js-debug.
So best would be to file this against the powershell extensino and they should investigate and report it back to vscode in case it is a vscode issue. Thank you
