### ISSUE TITLE
Error while turning on Settings Sync - validating Corrupt ZIP

### ISSUE THREAD

**Issue by bugs181** [microsoft/vscode#118291]
Error popup: "Error while turning on Settings Sync. Please check [logs](command:workbench.userDataSync.actions.showLog) for more details." 

Description: Error while turning on Settings Sync. Lots of validating Corrupt ZIP errors. Oddly enough, even with the popup being displayed, the log continues to say "Installed extension" one after another.

Potentially related: #84869

OS: Pop!_OS 20.10 64-bit 
Gnome: 3.38.3
Windowing System: X11

VS Code about:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z (3 wks ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-7642-generic
```

Steps to Reproduce:

1. CTRL + Shift + P -> Settings Sync: Turn on
2. Watch log for errors

Does this issue occur when all extensions are disabled?: Yes (Ran with `code --disable-extensions`, with similar results)

[userDataSync.log](https://github.com/microsoft/vscode/files/6094612/userDataSync.log)

**Comment by sandy081** [comment]
@bugs181 Yeah seems related to #84869. 

Can you please try installing the extensions manually from extensions view and confirm if you are getting same error?

Please follow this link https://github.com/microsoft/vscode/issues/84869#issuecomment-558248561 and provide the info requested in that link
