### ISSUE TITLE
Debugger Step Over into skipFiles

### ISSUE THREAD

**Issue by re4388** [microsoft/vscode#118282]
## VS Code Version:
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

## OS Version: 
- win10 1909

- Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce:

1. npm install -g @angular/cli
2. ng new my-dream-app
3. cd my-dream-app
4. ng serve

launch.json setting (both 2 settings are not working)
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**/*.js"
      ],
    }
  ]
}
```

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:4200",
      "webRoot": "${workspaceFolder}",
      "skipFiles": [
        "${workspaceFolder}/node_modules/**/*.js",
        "${workspaceFolder}/lib/**/*.js",
        "<node_internals>/**/*.js"
      ],
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:/*": "${webRoot}/*",
        "/./*": "${webRoot}/*",
        "/src/*": "${webRoot}/*",
        "/*": "*",
        "/./~/*": "${webRoot}/node_modules/*"
      }
    }
  ]
}
```

5. set breakpoint
![image](https://user-images.githubusercontent.com/5414334/110189465-1d613b80-7e5a-11eb-8775-e8d5138b6e4c.png)

6. Start debuggining by click the below panel
![image](https://user-images.githubusercontent.com/5414334/110189500-38cc4680-7e5a-11eb-96bf-9680cb6d9290.png)

7.Stop at breakpoint
![image](https://user-images.githubusercontent.com/5414334/110189517-4aade980-7e5a-11eb-9c5c-96e17e9dd7f2.png)

8. After 3 Step Over, we end up in the below screenshot (**sometimes, it seems to skip, but sometimes not)**
On the right, we see those files are indeed skipped in the call stack? But the Step Over still stop inside the file.
![image](https://user-images.githubusercontent.com/5414334/110189542-61544080-7e5a-11eb-8489-1c7a9f912910.png)

--

I apologize for my mistake if this is more about Angular specific not Vscode, but I think maybe Vscode debugger shall work as well?

**Comment by sinapis** [comment]
This is happening to me as well with nodejs backend with typescript.

**Comment by sinapis** [comment]
I have a breakpoint that is hit on the call site of an async function, and even though i have all js files added as skipped in launch.json file, when i press F11, debugger goes into the js file.
![index ts-debugger-not-skipping-_WSL_-Ubuntu_-Visual-Studio-Code-2021-03-07-21-21-37](https://user-images.githubusercontent.com/15230040/110252063-408c0800-7f8c-11eb-85ab-04167e218cd3.gif)

here is the repro https://github.com/sinapis/vscode-118282

**Comment by connor4312** [comment]
Thank you for the good issue and repro steps! Turn out this bit of functionality never worked as it was intended...

**Comment by connor4312** [comment]
@roblourens can you share steps? I don't repro this https://memes.peet.io/img/21-04-ed599b74-21dd-48ae-8928-dbb50e256b9d.mp4

**Comment by roblourens** [comment]
I was using the https://github.com/sinapis/vscode-118282 test repo, not the OP

**Comment by connor4312** [comment]
That was actually a separate issue that affected attach without an `--inspect-brk`. If we parsed all scripts before the query for built-in modules returned and never parsed any additional scripts afterwards, skipfiles would never be sent.
