### ISSUE TITLE
JS died 5 times last 5 min

### ISSUE THREAD

**Issue by amaziero** [microsoft/vscode#118272]
Issue Type: <b>Bug</b>

Javascript reporting error constantly during coding

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.16GB free)|
|Process Argv|--crash-reporter-id 3bd9adbd-791c-422d-a30d-39313fee9703|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|Memory (System)|15.89GB (4.16GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
es7-react-js-snippets|dsz|3.1.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
dotenv|mik|1.0.1
remote-wsl|ms-|0.54.0
mq4|ner|1.0.4
mql-over-cpp|nic|0.0.3
mql-snippets|nic|0.1.2
material-icon-theme|PKi|4.5.0
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
html-snippets|wsc|1.0.6
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-sqlite|ale|0.11.1
vscode-eslint|dba|2.1.14
python-preview|don|0.0.4
githistory|don|0.6.14
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.2
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
beautify|Hoo|1.5.0
elixirlinter|iam|0.4.1
elixir-ls|Jak|0.6.5
vscode-styled-components|jpo|1.5.0
vscode-exec-node|mir|0.5.3
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.619093157
cpptools|ms-|1.2.2
reload|nat|0.0.6
color-highlight|nau|2.3.0
mq4|ner|1.0.4
mql-over-cpp|nic|0.0.3
mql-snippets|nic|0.1.2
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.5.0
vscode-css-peek|pra|4.1.0
LiveServer|rit|5.6.1
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
watch-in-chrome|sne|0.0.2
vscode-wakatime|Wak|5.0.1
html-snippets|wsc|1.0.6
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
