### ISSUE TITLE
Feb 2021 build: How to remove the highlight border on the file explorer?

### ISSUE THREAD

**Issue by darkguy2008** [microsoft/vscode#118258]
- VS Code Version: 1.54.1
- Commit: f30a9b73...
- OS Version: Win10 LTSC ( Microsoft Windows [Version 10.0.17763.1757] )

Steps to Reproduce:

1. Open VSCode
2. Click a file/folder on the sidebar

Does this issue occur when all extensions are disabled?: Yes

So basically I was using VSCode happily until it updated to Feb 2021 build and now I get this **ugly** border everytime I click on something or the focus is on an element:

![image](https://user-images.githubusercontent.com/6304136/110169285-1b499f00-7dbe-11eb-9b99-027b7f50cf6d.png)

Any ideas how to remove this? Using Default (Dark+):

![image](https://user-images.githubusercontent.com/6304136/110169463-521fb500-7dbe-11eb-96ed-37b7c04399ea.png)

**Comment by IllusionMH** [comment]
This is focus outline for keyboard navigation to make focused element distinct enough from active element (previously it was slight change in background color).

You can make it transparent with
```
"workbench.colorCustomizations": {
    "list.focusOutline": "#0000"
}
```
or pick color that will match your theme.

/cc @joaomoreno

**Comment by darkguy2008** [comment]
Awesome, that fixed it, thanks @IllusionMH ! Transparent looks good enough, it's back to how it was prior to the update. I don't think the border was needed... Maybe I'd add it **only** when you've started to use the keyboard to navigate. If you're using the mouse (I do, a lot) I wouldn't show the border at all.

To me, it looks like an accessibility feature that, while appreciated when it's required, I don't think should be enforced. I prefer my UI slim and clean like that.

Thanks!

**Comment by IllusionMH** [comment]
IMHO that's great improvement that makes it consistent with other VS Code element, OS, and apps behavior which worth to bring to default themes. And focus outline looks much cleaner (at least when moved) than background from previous versions.

Can you tell which file is currently selected and which is selected with keyboard with quick glance? What if it will be not so much familiar theme?
![image](https://user-images.githubusercontent.com/1312662/110176583-34793c80-7e0c-11eb-9e4f-3dc446f7953d.png)

With outline it's much easier.

Those who want old behavior can use overrides to set background
```json
"workbench.colorCustomizations": {
    "list.focusOutline": "#0000",
    "list.focusBackground": "#062f4a",
}
```

**Comment by darkguy2008** [comment]
Well, taking the OS in consideration, the behavior is a bit different:

![image](https://user-images.githubusercontent.com/6304136/110178812-9dd95b00-7dcc-11eb-8a87-2cf9c4cd5673.png)

As you can see, and it's what I expect from the OS: (1) is the selected element, and (2) is the **hover** from my mouse. Regardless if I use the keyboard, or the mouse, (1) moves as a whole. I can understand having the border stand out like that works pretty well for a light UI theme, but not so much for a dark UI theme.

I don't mean to say that the new change is bad, but I'd enable the border **only** if an arrow key is pressed, because you expect the selection to be highlighted in a striking way.

As per your screenshot, in my experience I think the arrow keys moved the dim blue one while the lighter one was the current file you were working on, but I might be mistaken. I agree that sometimes it was a bit hard to see, and again, if using the keyboard navigation, I'd enable the border - definitely an UI/UX improvement - but when using the mouse, it burns my eyes, and stands out **a lot** more than the rest of the theme UI, which burns my eyes ;)

**Comment by isidorn** [comment]
@IllusionMH thanks for answering and for answering how to customise this.
This is coming from the tree thus forwarding to @joaomoreno

**Comment by joaomoreno** [comment]
Closing as a user configuration workaround was provided.
