### ISSUE TITLE
Cmd+r to rename a folder/file when focused

### ISSUE THREAD

**Issue by timc1** [microsoft/vscode#118263]
It would be wonderful to be able to have a folder/file selected in the explorer and hit `cmd+r` to rename 💭 

<img width="251" alt="Screen Shot 2021-03-05 at 4 31 32 PM" src="https://user-images.githubusercontent.com/12195101/110175735-40dfa400-7dd0-11eb-92d2-ceeb9acc5d21.png">

**Comment by IllusionMH** [comment]
There is default shortcut for this <kbd>F2</kbd> but you can use [Keyboard Shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor) to set <kbd>Ctrl</kbd>+<kbd>R</kbd> for `renameFile` command.
Not that <kbd>Ctrl</kbd>+<kbd>R</kbd> already used for other global action like Recent Files

**Comment by timc1** [comment]
Thanks @IllusionMH 💯
