### ISSUE TITLE
Error taking into account a numeric character keystroke

### ISSUE THREAD

**Issue by aristot** [microsoft/vscode#118228]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.In the editor, it happens that when you type a numeric character, for example 3, it is replaced by #. In the terminal the same numeric character is perfectly taken into account.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<3>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`<3>`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by aristot** [comment]
Sorry I don't know how to run the command ! in a specific terminal, I use a french version of VSC.
Thanks

**Comment by alexdima** [comment]
@aristot Here it is. You can also copy-paste the English string I provided above and the command will be found:

![image](https://user-images.githubusercontent.com/5047891/111982719-983c7e80-8b09-11eb-8d5c-c13338cfb3ab.png)

**Comment by aristot** [comment]
Thanks, in concordance with your recommendation,  I have produce the following result:

![shift_4](https://user-images.githubusercontent.com/11194635/111985271-b22b9080-8b0c-11eb-9c40-800b1fa35a5c.PNG)

**Comment by alexdima** [comment]
You can right click and remove those. It looks like an extension you have installed is defining these keybindings and preventing you from typing properly.

**Comment by aristot** [comment]
Thank you very much for your quick response. I followed your advice by removing the annoying keyboard shortcuts
