### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by apestats1906** [microsoft/vscode#118239]
Issue Type: <b>Performance Issue</b>

Error: Environment failed to become available. Please check the Docker container logs for more details.

VS Code version: Code - Insiders 1.55.0-insider (04770364fdc1bebeca9d1a257df2cacce06b35d6, 2021-03-05T15:40:03.281Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	    86	 17204	code-insiders main
    2	    85	  3672	   window (Issue Reporter)
    0	   100	  5076	   window (undefined)
    0	   195	  8376	   window (A2: Creating a smart contract (Basic tutorials) - Visual Studio Code - Insiders [Administrator])
    0	   155	 12484	     extensionHost
    0	    74	 17020	       "C:\Program Files\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=12484
    0	    25	  8600	   crashpad-handler
    0	    92	  9380	   shared-process
    0	    69	  2948	     ptyHost
    0	    69	 10900	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 16036	       console-window-host (Windows internal process)
    0	    94	 11192	   window (undefined)
    0	    48	 12476	   utility
    0	   201	 16688	   gpu-process
    0	    96	 17452	   window (undefined)
    0	    94	 19324	   window (undefined)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.16
ibmcloud-account|IBM|1.0.4
ibm-blockchain-platform|IBM|2.0.2
vscode-docker|ms-|1.10.0
javascript-test-runner|osh|1.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwsldoc:30268767
vscoresta800:30265947
vspre833:30267464

```

</details>

**Comment by aeschli** [comment]
Can you add steps and more details how do you get this error? A screenshot could help.
