### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#118222]
1) Notebook API tests
       change cell language:
 Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\1\s\extensions\vscode-api-tests\out\singlefolder-tests\notebook.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

https://monacotools.visualstudio.com/Monaco/_build/results?buildId=107717&view=logs&j=ca7250c6-0e2d-5a52-28a2-5c6aea023c92&t=ecafce82-b377-508c-0af4-b6b1aa68a502

**Comment by sandy081** [comment]
Skipped the failing test temporarily. Please fix it and enable.

**Comment by rebornix** [comment]
This is no longer needed since now you can only change language through `TextDocument`.

**Comment by rebornix** [comment]
aaf6287ecccebda0eba6f78c86670aeb3d8dfe22
