### ISSUE TITLE
Notification filter by extension source

### ISSUE THREAD

**Issue by JCKodel** [microsoft/vscode#118249]
There are many many VSCode extensions that abuse or displays wrong notifications. Sometimes, the notification is useless and spammy, sometimes, it is just bugged.

Examples:
![image](https://user-images.githubusercontent.com/379339/110159357-5d2c1280-7dc9-11eb-8c6d-19fdada4b1e5.png)

Those 2 notifications pops up every time I save a file in VSCode. There is a bug on dart-import extension and the  project seems dead (but the extension is still useful and relevant).

![image](https://user-images.githubusercontent.com/379339/110159641-bdbb4f80-7dc9-11eb-84a7-d35af7c8261c.png)

In this case, the notification is useless. When triggering this extension on save, those notifications fills the entire queue and occupy the bottom space of the screen.

I had to install a 3rd extension just to fix things on save:
```json
"multiCommand.commands": [
  {
    "command": "multiCommand.fixAndSave",
    "interval": 250,
    "sequence": [
      "dart-import.fix",
      "workbench.action.files.save",
      "notifications.hideToasts"
    ]
  },
],
```

If the extenion is `.dart`, I call the `dart-import` extension to do its magic, then I save the file, then I hide all toasts to clear the spam (and losing useful toasts, if there is any).

It is impossible to ask for each extension developer to not misuse the notification system, nor can I fork and fix EVERY extension I use, so...

What I'm proposing is something like this:

```json
hideToastsFromExtensions: {
  "dart-import": "block",
  "some-other-extension": "hide"
}
```

`block` will prevent that extension of showing toasts (nothing happens, the toasts simply doesn't appear, hidden or not).
`hide` will not display the notification on screen, but will trigger the unread notification icon: 
![image](https://user-images.githubusercontent.com/379339/110160224-7da89c80-7dca-11eb-99f2-40a04e47ecba.png)

**Comment by sana-ajani** [comment]
cc @devinvalenciano @meganrogge
