### ISSUE TITLE
list.focusBackground not working

### ISSUE THREAD

**Issue by bimbo1989** [microsoft/vscode#118213]
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:

1. Press F1 to open the dropdown list in VSCode
2. The color is the default pale blue instead of the color defined in the theme itself, or in the workbench.colorCustomizations

Does this issue occur when all extensions are disabled?: Yes

For example, this is the json part
``` json
  "workbench.colorCustomizations": {
    "list.focusBackground":"#ff0000"
  }
```

And this is how it looks
https://i.ibb.co/DLvBc7L/error-color.png

**Comment by joaomoreno** [comment]
Does it work if you use `quickInput.list.focusBackground`?

**Comment by bimbo1989** [comment]
Yes, it does!
Is this expected behaviour? What is list.focusBackground for then?
Do I need to edit my theme and publish a new version of it?
Thank you!

**Comment by joaomoreno** [comment]
Merged into https://github.com/microsoft/vscode/issues/118214

**Comment by joaomoreno** [comment]
> Yes, it does!
> Is this expected behaviour? What is list.focusBackground for then?
> Do I need to edit my theme and publish a new version of it?
> Thank you!

Yes, this is part of the new release. But we'll push a recovery candidate which should make this migration automatic.
