### ISSUE TITLE
Move search app out of renderer into shared process or extension host

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118200]
We need to remove node dependencies of the renderer for our sandbox effort. Search is currently a process that is triggered from the renderer (via `vs/workbench/services/search/electron-browser/searchService` et al). Going forward, we should move this into one of the processes that is allowed to execute node:
* shared process
* extension host

Filing this to get a discussion starting how to tackle this. With terminals moved, @Tyriar and @meganrogge have demonstrated that the shared process is a viable host for native processes and the patterns used for terminals can be applied to this one as well. 

https://github.com/microsoft/vscode/issues/116337 has a diagram for how the shared process today is being used as host for privileged processes.

**Comment by roblourens** [comment]
It has been the plan for awhile to move this to the EH. I can't find the old discussion about the architecture and the possible perf issues of running search in the EH, but I think this has been proved in Remote, and we can revisit this. @jrieken @kieferrm

**Comment by bpasero** [comment]
I verified the `search.forceSearchProcess` setting. It needs a restart and we do not tell the user, but my understanding is this setting goes away in October anyway.
