### ISSUE TITLE
Support detaching terminal processes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118276]
We have a `Terminal: Attach to Session` command which attaches the orphaned remote processes, I think it would be good for testing in particular if we a command to enable detaching sessions. This would allow us to do something very similar to what happens on reload by detaching and attaching, greatly improving test coverage around terminal reconnection.

**Comment by Tyriar** [comment]
The PR only added the command for local terminals

**Comment by Tyriar** [comment]
Detach/attach allows moving terminals across windows - we could maybe support drag and drop between windows with this

**Comment by meganrogge** [comment]
do not think this should be on release notes 😆

**Comment by Tyriar** [comment]
Added it to the preview features section as it enables moving terminals across windows.
