### ISSUE TITLE
Ability to add multiple open folders to a single project

### ISSUE THREAD

**Issue by kattkieru** [Microsoft/vscode#11826]
- VSCode Version: 1.5.1
- OS Version: macOS

Feature Request

It would be nice to be able to add / remove multiple folders to / from a project, not unlike Sublime Text. (Gif attached).

![multiple-folders](https://cloud.githubusercontent.com/assets/1939040/18410253/d9c6e068-772a-11e6-9d2b-1685493f660a.gif)

This is one of the few things keeping a number of people I know from using Code, and to be honest as much as Code is killing it right now, this is one of the missing features keeping me from using it for all of my editing.

**Comment by alefragnani** [comment]
Hi @kattkieru . This is already in the [Roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap), and it's being tracked in https://github.com/Microsoft/vscode/issues/396.

Stay tuned :smile:

**Comment by ramya-rao-a** [comment]
Closing as duplicate.
@kattkieru Don't forget to vote the original issue logged.
@alefragnani Thanks for finding that original issue.
