### ISSUE TITLE
cannot run simple node program after update 1.54.x

### ISSUE THREAD

**Issue by asanoic** [microsoft/vscode#118221]
- VS Code Version: 1.54.0, 1.54.1
- OS Version: Windows

Steps to Reproduce:

1. create any simple index.js like
```javacsript
function Car() {
    this.xyz = 789;
    return {abc: 123};
}

let a = new Car();
console.log(a);
```
2. press F5
3. 
![Capture](https://user-images.githubusercontent.com/70875479/110135366-0c4df700-7d94-11eb-97a9-085520593b42.PNG)
 
launch.json is 
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}",
            "runtimeExecutable": "Q:/node/node.exe",
            "cwd": "${fileDirname}",
            "args": ["D:/Json", "q:/aa.json"]
        }
    ]
}
```

I do not have any other extensions installed. and this bug cannot be reproduced on 1.53.x.

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Can you use the **Developer: Toggle Developer Tools** command and check if there are any errors in the console?

**Comment by asanoic** [comment]
> Can you use the **Developer: Toggle Developer Tools** command and check if there are any errors in the console?

sorry @connor4312, I donot have any Windows machine anymore, I tried on Linux, everything looks good. it seems this is only happen on Windows, hope this is helpful.

**Comment by connor4312** [comment]
Okay. Please give a shout if you (or anyone else) runs into this again
