### ISSUE TITLE
Multiple Crash WSL VSCODE

### ISSUE THREAD

**Issue by arrudaricardo** [microsoft/vscode#118216]
Issue Type: <b>Bug</b>

Mutiple Crashes (Typscript an Javascript Langague Extension) using WSL (ubuntu) on vscode WSL plugin.

Project: Javascript, eslint.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.23GB (2.28GB free)|
|Process Argv|--crash-reporter-id 59e88b5d-3700-4eab-b063-a24d2f6852d1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2095)|
|Memory (System)|3.84GB (0.98GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2095)|
|Memory (System)|3.84GB (0.98GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2095)|
|Memory (System)|3.84GB (0.98GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650U with Radeon Graphics (12 x 2095)|
|Memory (System)|3.84GB (0.98GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
Lua|key|0.0.9
eml|lei|0.4.0
remote-containers|ms-|0.158.0
remote-wsl|ms-|0.53.4
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
svg-preview|Sim|2.8.3
vscode-icons|vsc|11.1.0
vim|vsc|1.18.9
vscode-todo-highlight|way|1.0.4
vscode-ruby|win|0.28.0
gitlens|eam|11.2.1
vscode-docker|ms-|1.10.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.2.603412351

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by aeschli** [comment]
Can you give more information about the crashes?

**Comment by arrudaricardo** [comment]
I'm editing a javascript code on VSCODE under WSL, and  the Typscript an Javascript Langague Extension is crashing multiple time.

**Comment by aeschli** [comment]
Can you make a screenshot that show the crash or paste a log? 
Where do you have your sources, on a`/mnt/..?

**Comment by arrudaricardo** [comment]
<img width="597" alt="error" src="https://user-images.githubusercontent.com/35773631/110296517-54feed80-7fea-11eb-9d2b-3abb0adc1ce6.png">
<img width="505" alt="error2" src="https://user-images.githubusercontent.com/35773631/110296523-55978400-7fea-11eb-84e9-6a23342a0231.png">
![image](https://user-images.githubusercontent.com/35773631/110296625-7233bc00-7fea-11eb-953d-320c327eb92f.png)
![image](https://user-images.githubusercontent.com/35773631/110296818-ab6c2c00-7fea-11eb-8c11-5f6cca21bd6a.png)

**Comment by arrudaricardo** [comment]
I installed VS Code insider build and disabled all extension and the still same problem: 

![image](https://user-images.githubusercontent.com/35773631/110821047-9bbd4380-8287-11eb-92a5-b858b76184e8.png)

![image](https://user-images.githubusercontent.com/35773631/110821182-bdb6c600-8287-11eb-877e-5f575d06d8b3.png)

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
