### ISSUE TITLE
files not editing

### ISSUE THREAD

**Issue by Anandupr2000** [microsoft/vscode#118244]
Issue Type: <b>Bug</b>

I do all my projects using VSCode,but those day editing had no issues.But nowadays its not writing the code on to the file opened.Plz help...

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.84GB (5.98GB free)|
|Process Argv|--crash-reporter-id 6e527908-c10f-43d5-825c-692811454d28|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-django|bat|1.3.0
python-preview|don|0.0.4
python-extension-pack|don|1.6.0
vscode-pydev|fab|0.2.4
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-npm|fkn|3.3.0
ghoul007-puppeteer-snippet|gho|1.1.2
kite|kit|0.142.0
MagicPython|mag|1.1.0
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.619093157
remote-wsl|ms-|0.54.0
live-server-preview|neg|0.1.4
puppeteer-snippets|nit|1.6.1
npm-install|ore|0.0.1
vscode-css-peek|pra|4.1.0
java|red|0.76.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.2.8
php-live-server|Teo|0.0.1
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
jinja|who|0.0.8
vscode-java-saber|You|0.1.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes516:30244333
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
