### ISSUE TITLE
`ESC` key no longer closes the output window

### ISSUE THREAD

**Issue by db666** [Microsoft/vscode#11829]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Run any sort of code (in my case Golang code) and watch the "Output" window pop up with the program output
2. Press `ESC` to close the window; it doesn't work.
3. This was working fine before the latest update so possibly a regression?

**Comment by isidorn** [comment]
Yes this was removed since it was a big hack on our side (it was not a registered keybinding).
Please use ctrl + J to toggle the output panel, or set any other keybinding for `workbench.action.togglePanel` in your `keybindings.json`
