### ISSUE TITLE
Cannot find module 'worker_threads' using js debugger auto attach

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#118259]
- Version: 1.55.0-insider (user setup)
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:40:03.281Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

I think this might be the same problem, showing up two ways.  First, auto attach of the JS debugger doesn't seem to do anything. Second, if I run from a JavaScript debug terminal an exception is thrown.

In `settings.json`:

`"debug.javascript.autoAttachFilter": "smart",`

Simple JavaScript file `test.js` contains:

![image](https://user-images.githubusercontent.com/1487073/110170650-69a37180-7daf-11eb-81fb-a47d3eb66637.png)

Expectation is when I launch the app, debugging will start and break on line 3.

In a normal terminal, the app runs but debugger does not start, no breakpoint is hit.

![image](https://user-images.githubusercontent.com/1487073/110170887-b424ee00-7daf-11eb-8ae2-30de4d3dde50.png)

In a JavaScript debug terminal, I see this:

![image](https://user-images.githubusercontent.com/1487073/110170910-c141dd00-7daf-11eb-8335-bf03b3a9b8a4.png)

**Comment by chrisdias** [comment]
node version `10.19.0`

**Comment by chrisdias** [comment]
works ok in Stable 

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

I should also note that I'm running Remote WSL.

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-js-debug/commit/fdcab32cd03d6d40340a1d7e3bd1e4681f1d88cd

**Comment by sujayvenaik** [comment]
@connor4312 When will a new version with this fix be released?
