### ISSUE TITLE
Jupyter files

### ISSUE THREAD

**Issue by oscardog** [microsoft/vscode#118353]
Issue Type: <b>Bug</b>

Hi,

files with several charts - esp ones with pairplots tend to cause the .ipynb to bloat. Opening the same file and saving it in jupyterlab (with output) reduces the file size dramatically (~20x)

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.3.0

**Comment by gjsjohnmurray** [comment]
Your VS Code version is three releases behind current. Are you able to update and retest?

**Comment by oscardog** [comment]
Updated and same issue persists

Shall file with extension repository as suggested

Warm Regards,
Tushar
