### ISSUE TITLE
Terminal errors in remote window after disconnection

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118324]
A remote window disconnected overnight and these error notifications are shown:

![image](https://user-images.githubusercontent.com/323878/110214621-47b2f900-7e5a-11eb-8b8a-14b8713be5b5.png)

**Comment by Tyriar** [comment]
Local/remote OS + version info? The notifications may be coming from the local side.

**Comment by roblourens** [comment]
Mac/Linux, I think Thursday's insiders build. Did not see them in the disconnected window this morning.

**Comment by Tyriar** [comment]
In that case, it's probably fixed on Friday with https://github.com/microsoft/vscode/issues/117990, this was also a candidate.
