### ISSUE TITLE
Extension host terminated unexpectedly.

### ISSUE THREAD

**Issue by OOOHA** [microsoft/vscode#118394]
Issue Type: <b>Bug</b>

Extension host terminated unexpectedly always pop up when I am coding. It started from the latest update. When this happend, I need to use . code to open a new  Vscode Window or the Bug report function is disable too.
The restart of vscode does not help with this issue. 
I am using Windows 10Pro 1909 with the latest update.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.08GB free)|
|Process Argv|--crash-reporter-id 6e0a0302-b09c-4c20-8e81-5fa91decd80f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.0.3
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
git-project-manager|fel|1.7.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.2
code-runner|for|0.11.2
vscode-javac|geo|0.2.37
vscode-tree-sitter|geo|0.1.26
vscode-pull-request-github|Git|0.24.0
go|gol|0.23.0
go-nightly|gol|2021.3.218
todo-tree|Gru|0.0.201
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.5
flutter-tree|mar|1.0.0
git-graph|mhu|1.29.0
Angular-BeastCode|Mik|10.0.3
vscode-clang|mit|0.2.3
csharp|ms-|1.23.9
python|ms-|2021.2.625869727
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
java|red|0.76.0
LiveServer|rit|5.6.1
document-tree|sac|1.0.1
sonarlint-vscode|Son|1.20.1
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
windows-terminal|Tyr|0.6.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vscode-icons|vsc|11.1.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by OOOHA** [comment]
Still sometimes pop up  after I try this.

**Comment by OOOHA** [comment]
@gjYou mean 

> Please run the Extension Bisect command from Command Palette to try and discover which of your extensions is crashing the EH.


you mean don't run the Extension Bisect through F1?
I use the F1 > Help: Start Extension Bisect
And it's still have some problems so I press "This is bad".
It shows that there are no problem.
After I tried this the error pop up about 40%.

And my MacBook(intel) after these steps is still in a big trouble.
Therefore, I had reported  another issue.
At last, it makes me thought that maybe it's because the latest update.

**Comment by aeschli** [comment]
When you run VSCode with all extensions disabled, do you still see the problem?
You can easy do that with `Developer: Run with Extensions Disabled`

**Comment by OOOHA** [comment]
> When you run VSCode with all extensions disabled, do you still see the problem?
> You can easy do that with `Developer: Run with Extensions Disabled`

I'll try it next time it happens.
It has no problem at the last few hours.
I'll get so test next time.Thanks!

**Comment by OOOHA** [comment]
> When you run VSCode with all extensions disabled, do you still see the problem?
> You can easy do that with `Developer: Run with Extensions Disabled`

With all Extensions disable, there are no error.
But after Reload and Enable Extensions, the error pops up again

**Comment by aeschli** [comment]
Ok, so the problem is in one of the extensions and an issue needs to be filed against the problematic extension.
The Extension Bisect feature can help you to find out which extension has the problem.
