### ISSUE TITLE
make suggest list supports fuzzy matching

### ISSUE THREAD

**Issue by weijarz** [Microsoft/vscode#11836]
- VSCode Version: 1.5

> For example, searching `view_cn` brings up `view_class_name`.

For example, create a new document:
```
django
view_class
view_class_name
view
    ^
```
After typing `view`, the suggest list will appear ([`view_class`, `view_class_name`]), but VSCode does not support continue type a `n` to filter down this list to [`view_class_name`].

Atom has this feature:
![atom-complete](https://cloud.githubusercontent.com/assets/8944061/18414214/72aa691c-77f3-11e6-90a7-7afca277205b.png)

**Comment by joaomoreno** [comment]
It does support it.

![image](https://cloud.githubusercontent.com/assets/22350/18428266/43787190-78cd-11e6-869a-b86e811f4b7e.png)

It does **not** support suggesting `python` when you type `pythn` since that would cause way too many false positives in a regular workflow.

**Comment by weijarz** [comment]
@joaomoreno What's your vscode version?
My version seems not work (v1.5.1 / Linux). The popup list will close when type 'n'.

![screenshot from 2016-09-12 16-18-38](https://cloud.githubusercontent.com/assets/8944061/18429195/cc86dd82-7904-11e6-8a0b-756571903163.png)
![screenshot from 2016-09-12 16-18-55](https://cloud.githubusercontent.com/assets/8944061/18429200/d1b5eb72-7904-11e6-83b3-b71a7a6b4c22.png)

**Comment by joaomoreno** [comment]
That's because your are filtering against textual suggestions, which [only match by their prefix](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/supports/suggestSupport.ts#L23). cc @jrieken

**Comment by weijarz** [comment]
@joaomoreno I think an option should be added to allow partial matching.

**Comment by jrieken** [comment]
Yeah - we did that to have less suggestions in textual completions - mostly in comments etc. Once we have a better story for that we should align the filtering.

**Comment by weijarz** [comment]
@jrieken A better Atom like .tmLanguage based suggestion is useful for languages that without intellisense support (like Vue.js support for VSCode <https://marketplace.visualstudio.com/items?itemName=seanwash.vue> which provides a  .tmLanguage file only).
