### ISSUE TITLE
Disable by default the Compact Folders

### ISSUE THREAD

**Issue by drigovz** [microsoft/vscode#118329]
Please. I suggest to disable by default the "Compact Folders" mode. In my opinion, this feature it could optional.

**Comment by isidorn** [comment]
Thanks for sharing your opinion but we have no plans to change this at the moment.
I can leave this issue open for some time to gather more feedback, but we have no plans to change this.

**Comment by drigovz** [comment]
Ok. Anyway thank you so much

**Comment by Eoic** [comment]
I hope this will get addressed in the future. This feature is awful and should be disabled by default.
