### ISSUE TITLE
VS Code sucks up hours of developer time trying to simply get an Anaconda virtual environment to successfully be accessible in VS Code Jupyter Notebook.  Why?!!!

### ISSUE THREAD

**Issue by cpoptic** [microsoft/vscode#118342]
Absolute frustration after hours of trying to debug this.

Why in God's name is it so hard to simply have a newly created conda environment appear in VS Code?
I have created a virtual environment.
I have activated that environment.
I have installed packages in that environment.
I can run `python` interpreter from terminal and import those packages.

But for some goddamn reason every time I try to select the environment's kernel in the lower left corner, it shows the kernel successfully loaded (as it clearly appears in the lower left corner by name), but then running the EXACT SAME IMPORT STATEMENTS AS IN THE TERMINAL ABOVE, it says "package not installed" or "could not be found".  Why?  The packages clearly *ARE* installed.  Why can I import these libraries with zero issues from terminal but then when I try to import them in a Juptyer notebook in VS Code, VS Code decides to suck up hours of my Saturday afternoon.  Why Microsoft?  Why?

**Comment by rebornix** [comment]
/extJupyter

Please report this issue to the Jupyter extension http://github.com/microsoft/vscode-jupyter, which provides the kernel detection feature, thanks!
