### ISSUE TITLE
Cannot attach to .Net Functions (coreclr)

### ISSUE THREAD

**Issue by rbdalvi** [microsoft/vscode#118343]
Issue Type: <b>Bug</b>

Getting error "Cannot read property 'map' of undefined'" after hitting F5 on a .Net Function (coreclr) written in C#. This started to happen after VS Code automatically upgraded to 1.54.1 on restart. Downgrading to earlier version resolves this issue. But then VS Code auto-upgrades on restart and the problem returns.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.21GB free)|
|Process Argv|C:\\func-xxx--member-code --crash-reporter-id b4eb7def-abb2-4547-80fc-c8ac81d47846|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.1.1
Bookmarks|ale|13.0.3
swagger-viewer|Arj|3.0.1
aadb2c|Azu|1.2.104
armview|ben|0.4.5
githistory|don|0.6.14
xml|Dot|2.5.1
gitlens|eam|11.3.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
dotnet-test-explorer|for|0.7.5
vscode-test-explorer|hbe|2.19.5
rest-client|hum|0.24.4
vscode-peacock|joh|3.9.1
vscode-apimanagement|ms-|1.0.0
vscode-azureappservice|ms-|0.21.1
vscode-azurefunctions|ms-|1.2.1
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.10.0
vscode-logicapps|ms-|1.0.6
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
remote-containers|ms-|0.163.0
remote-wsl|ms-|0.54.0
azure-account|ms-|0.9.7
azurecli|ms-|0.5.0
js-debug-nightly|ms-|2021.3.517
powershell|ms-|2021.2.2
vscode-node-azure-pack|ms-|0.1.0
team|ms-|1.161.1
azurerm-vscode-tools|msa|0.14.1
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.16.0
open-in-browser|tec|2.0.0
find-then-jump|tra|2.0.4
vscodeintellicode|Vis|1.2.11
application-insights|Vis|0.4.2
vscode-icons|vsc|11.1.0
vscode-json-path|wei|2.4.0
vscode-nxunit-test-adapter|wgh|0.1.3
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
pythonvspyt602:30265442
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by dochoss** [comment]
Same thing here.  Downgrading to 1.53.2 makes it work.  I'm working on a Static Web App with C# Functions API.  F5 works fine in 1.53.2, returns the same error as above in 1.54.1.

**Comment by rbdalvi** [comment]
Are we sure this is a  C# extension issue? This is occurring in the new version of VS Code only. The C# extension has not changed.

**Comment by weinand** [comment]
No, I'm not but the usual procedure is that extension authors investigate first.
