### ISSUE TITLE
Jupyter Notebooks - cursor issue

### ISSUE THREAD

**Issue by Laxmi530** [microsoft/vscode#118306]
- VS Code Version: 1.54.0 
- OS Version: Windows 10pro

Steps to Reproduce:

1. If i left the cursor at line 10 and if i change the tab that means from vs code to edge and again i come back to vs code then i need the cursor at line 10 but this is not available. When i come back to vs code and i started typing so it opens menus unwantedly.
2. Please do something for this issue or if you have any option please tell me.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Laxmi530** [comment]
yes

**Comment by FilipePintoReis** [comment]
I can not reproduce this locally.

**Comment by aeschli** [comment]
I'm also not able to reproduce. When I give the go back to the VSCode window, e.g. by At+Tab) the focus in the editor and at the cursor.

How do you switch windows? Can you make a screencast?

**Comment by rebornix** [comment]
@Laxmi530 can you please provide a screenshot, with which we can figure out if it's a native notebook issue or a custom webview one.

**Comment by Laxmi530** [comment]
![after changing the tab_LI](https://user-images.githubusercontent.com/76505459/112710858-35246080-8eea-11eb-9a9b-cb096da326c7.jpg)
![before changing the tab_LI](https://user-images.githubusercontent.com/76505459/112710863-3ce40500-8eea-11eb-998f-b4c48839bd8e.jpg)



I have attached the image please have a look. The first image is after changing the tab and the 2nd image before changing the tab where you can see clearly  before change the tab the cursor is in that cell but after change the tab the focus is not in that cell it is in the file menu.

**Comment by Laxmi530** [comment]
Hai Team,
@vscode-triage-bot @rebornix 
The issue is still not resolved. I just want the resolution if any information is missed from my end then tell me I will provide more information about the issue.

**Comment by Laxmi530** [comment]
Yes the issue got resolved.
