### ISSUE TITLE
Terminal process failed to launch.

### ISSUE THREAD

**Issue by subi54** [microsoft/vscode#118378]
- VS Code Version: 1.54.1
- OS Version: Windows 10 Home x64

Steps to Reproduce:

Got a new laptop. Installed VS Code. Launched it and I get the following error notification: `The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" failed to launch (exit code: 3221225794).`

I tried launching from the given path, it works okay. Elevated permission doesn't work either. 

This also happens when I change the default terminal to Command Prompt or Bash.

Does this issue occur when all extensions are disabled?: Yes

**Comment by TylerLeonhardt** [comment]
@subi54 can you try some of the steps in this thread to see if any of them help?

https://github.com/microsoft/vscode/issues/43169#issuecomment-365143720

**Comment by subi54** [comment]
I searched and tried all that before opening this issue. I also installed Cmder, that doesn't work either. I made sure PATH and environment is set up correctly.

**Comment by TylerLeonhardt** [comment]
Thanks for confirming. Do you get that same exact error code when using Command Prompt or Bash? It's not different at all.

**Comment by subi54** [comment]
Yes, exact same (exit code: 3221225794).

**Comment by TylerLeonhardt** [comment]
@subi54 what is that CMDER part? That seems unusual. Can you add what's in your settings.json here?

**Comment by subi54** [comment]
That is just [Cmder](https://cmder.net/). I was trying it out. My issue came up earlier on a fresh install, on a fresh Windows 10 Home on a fresh PC.

Here are the Cmder related settings:

```json
    "terminal.integrated.shell.windows": "cmd.exe",

    "terminal.integrated.env.windows": {
    "CMDER_ROOT": "[cmder_root]"
    },
    "terminal.integrated.shellArgs.windows": [
      "/k",
      "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"
```

**Comment by TylerLeonhardt** [comment]
ah so if you get rid of the `"terminal.integrated.shellArgs.windows"` the issue still repros?

**Comment by subi54** [comment]
Yeah. Cmder was me trying to see if it'd work.

**Comment by TylerLeonhardt** [comment]
Did Cmder work? What about the new Windows Terminal? That error code says that the shell failed to initialize but I'm not really sure why... do you have Developer Mode turned on in Windows 10? I'm just shooting in the dark at this point since I can't repro.

**Comment by TylerLeonhardt** [comment]
Did you try the new Windows Terminal? https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab

Does that work?

**Comment by subi54** [comment]
Yes, I have it installed. It opens Powershell and Command Prompt tabs alright. How does that associate with VSCode?

**Comment by subi54** [comment]
Yeah, it launches Powershell and Command Prompt normally.

**Comment by TylerLeonhardt** [comment]
Hmm... ok where are you launching vscode from? And where is the code.exe installed to?

**Comment by TylerLeonhardt** [comment]
Can you run through these:
https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_common-issues-on-windows

Legacy console mode, anti-virus and compatibility mode in particular

**Comment by subi54** [comment]
Legacy mode doesn't work. Powershell closes after opening up.
`wslconfig.exe /l` gives this:
```
wslconfig.exe : The term 'wslconfig.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wslconfig.exe /l
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (wslconfig.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by subi54** [comment]
So, I reinstalled Windows and everything was working fine until I installed [Mactype](https://github.com/snowie2000/mactype). Uninstalled it and everything works fine. Thanks for all the help and apologies for the inconvenience.

**Comment by TylerLeonhardt** [comment]
@subi54 do you wanna get an issue going in Mactype about this? It seems odd that it's scoped to just vscode.

**Comment by subi54** [comment]
I will do it. Chrome Beta, Edge Dev, Edge Canary don't even start if Mactype is enabled on those processes. You have to disable Mactype to include those processes for them to open up.
