### ISSUE TITLE
freeses after latest update

### ISSUE THREAD

**Issue by frangiskos** [Microsoft/vscode#11834]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 6.3.9600

Steps to Reproduce:

1. After upgrading to the latest version I get a blank screen and I cannot load any file or folder. I tried uninstalling and reinstalling and still the same. see screenshot.

![image](https://cloud.githubusercontent.com/assets/5845584/18413061/b235635e-77a6-11e6-8dd8-431adfa08d40.png)

**Comment by ramya-rao-a** [comment]
@frangiskos Do you have the extension **vscode-icons** installed?
Do you see any errors in your console after enabling the developer tools?

@djbu saw this error in the console: http://prnt.sc/cg4unv in your console. Do you see the same?

**Comment by frangiskos** [comment]
Hi
Yes, I get the same errors.
I have uninstalled vscode-icons extension and disabled all others using the
following commands, but I still get the same error.
I thing the uninstall command is not running properly due to the mentioned
problem

code --uninstall-extension robertohuertasm.vscode-icons
code --disable-extensions

**Comment by ramya-rao-a** [comment]
In that case this would be the duplicate of #11790 

Can you share your `keybindings.json` file as described in [11790#issuecomment](https://github.com/Microsoft/vscode/issues/11790#issuecomment-246321827)

**Comment by frangiskos** [comment]
Hi, keybindings.json looked ok.
I have uninstalled code again, deleted %APPDATA%\Code and then reinstalled code.
It works fine now.
