### ISSUE TITLE
adjusting font size using Ctrl/Cmd and - stop working when you signed in github live share

### ISSUE THREAD

**Issue by lesdidev** [microsoft/vscode#118376]
Issue Type: <b>Bug</b>

Steps to replicate the issue:

1. Start with fresh installation. Ctrl/Cmd and - will work initially.
2. Sign in live share using github. After this Ctrl/Cmd and - will stop working.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.03GB free)|
|Process Argv|--crash-reporter-id 88798c33-abb8-4569-9d7f-1ef104f03122|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.2.625869727
jupyter|ms-|2021.3.619093157
remote-wsl|ms-|0.54.0
vs-keybindings|ms-|0.2.0
vsliveshare|ms-|1.0.3912
vetur|oct|0.33.1
vscodeintellicode|Vis|1.2.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by bpasero** [comment]
They possibly take over these keys? Can you check the keybindings editor if someone adds a command to be used with `Ctrl/Cmd + - `?

**Comment by lesdidev** [comment]
> They possibly take over these keys? Can you check the keybindings editor if someone adds a command to be used with `Ctrl/Cmd + - `?

Yes there is two commands that use Ctrl/Cmd + - one is the default and the other is from extension.
