### ISSUE TITLE
Could not create publisher

### ISSUE THREAD

**Issue by taoqf** [microsoft/vscode#118301]
- VS Code Version:1.54.1
- OS Version:Fedora 33

Steps to Reproduce:

1. open <https://marketplace.visualstudio.com/manage/createpublisher> to create publisher
2. timeout while getting `https://www.google.com/recaptcha/api.js`.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

You may know the gov is blocking the network from google. so I wish I could create publisher in other way.

**Comment by gjsjohnmurray** [comment]
I think this issue belongs better at https://github.com/microsoft/vsmarketplace/issues

**Comment by taoqf** [comment]
Thanks.
