### ISSUE TITLE
Link Head/Header/Body/Footer

### ISSUE THREAD

**Issue by mantivo** [microsoft/vscode#118337]
I would like to be able to link the head, header, body, footer, etc. portions of my .html pages so I can easily change one part on one page and it will change it for all of my pages. I have looked everywhere and cannot seem to find this function, so I am not sure if maybe I just haven't found it yet or if it's not a thing yet. I don't want to make a separate file because I want some pages to be different, but it would be nice to be able to link/unlink different sections to different pages so when I change one, they all change accordingly.

**Comment by aeschli** [comment]
The built-in HTML extension does not have such a functionality. You can use the search/replace functionality though.

Closing the issue as this is out-of-scope for the VSCode built-in extension.
