### ISSUE TITLE
Terminal missing

### ISSUE THREAD

**Issue by Dezzygee** [microsoft/vscode#118332]
Every time I start/debug my program, I get the same error: Configuration 'Create JavaScript Debug Terminal' is missing in 'launch.json'. I'm not sure if it is just a file is missing, or if I just need to do something.
![Capture](https://user-images.githubusercontent.com/80174943/110219336-c79d8b00-7e7b-11eb-971c-35510609c37d.PNG)

**Comment by connor4312** [comment]
How are you debugging/starting your program? Can you share your launch.json, if any?

**Comment by Dezzygee** [comment]
I'm not too sure but I just click f5, I'm new to coding

**Comment by Dezzygee** [comment]
> How are you debugging/starting your program? Can you share your launch.json, if any?

I'm sorry I fixed it
