### ISSUE TITLE
Can't edit or write code in visual code

### ISSUE THREAD

**Issue by harris12121** [microsoft/vscode#118311]
Issue Type: <b>Bug</b>

i was input alphabet and number but in vs code can't write code please help me.thank you all

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 450  @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.80GB (0.95GB free)|
|Process Argv|--crash-reporter-id e574ebe7-f485-4b88-bff8-f4d1dee5654a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
emulate|Die|1.4.0
cpptools|ms-|1.2.2
vscode-typescript-next|ms-|4.3.20210305
vim|vsc|1.18.9
omi-snippets|Wsc|2.2.8

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`


Most likely caused by Vim extension,
