### ISSUE TITLE
Unit testing README is missing a flag

### ISSUE THREAD

**Issue by thebinarysearchtree** [microsoft/vscode#118399]
- VS Code Version: 1.55
- OS Version: MacOS Big Sur

The unit testing readme instructions for running unit tests from node is missing the --ui tdd flag and doesn't work without it.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@thebinarysearchtree What page is that? Can you please provide a link?

**Comment by thebinarysearchtree** [comment]
Yeah see pull request sorry. I just lumped it into something else.
