### ISSUE TITLE
Deployment issue after latest update

### ISSUE THREAD

**Issue by adarshashu96** [microsoft/vscode#118328]
Issue Type: <b>Bug</b>

Step 1: Create project with manifest
Step 2: Retrieve source from org
Step 3: Edit some LWC code and deploy to org, it will work fine
Step 4: Make some more changes to the same LWC, nothing will be deployed
Changes will not reflect in Org, It will show that source is deployed successfully but nothing will happen, after tracing the issue I found that FilePath is becoming null after first deployment

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.08GB free)|
|Process Argv|--crash-reporter-id ccd9f00f-6169-481e-8790-8185f203faa1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.14
prettier-vscode|esb|5.9.2
vscode-xml|red|0.15.0
salesforce-vscode-slds|sal|1.4.0
salesforcedx-vscode|sal|51.3.0
salesforcedx-vscode-apex|sal|51.3.0
salesforcedx-vscode-apex-debugger|sal|51.3.0
salesforcedx-vscode-apex-replay-debugger|sal|51.3.0
salesforcedx-vscode-core|sal|51.3.0
salesforcedx-vscode-lightning|sal|51.3.0
salesforcedx-vscode-lwc|sal|51.3.0
salesforcedx-vscode-visualforce|sal|51.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by adarshashu96** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Can not retrieve source from org (#115364)](https://www.github.com/microsoft/vscode/issues/115364)

Not covered

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the authors of the Salesforce extension.
