### ISSUE TITLE
Can't forward port in remote VS Code

### ISSUE THREAD

**Issue by jigar288** [microsoft/vscode#118395]
- VS Code Version: 1.54.1
- OS Version: Ubuntu 20.04.1 LTS

Issue: I am trying to forward a port but it keeps telling me its not available. Even though it is available. Its also not forwarded yet. 

Screenshot: https://i.imgur.com/mZPnWFJ.png

Steps to Reproduce:
1. Login to Github Codespace or Remote Environment with VS Code
2. Try to forward a port

Error message: `Unable to forward localhost:8000. The host may not be available or that remote port may already be forwarded`

My terminal throws this error even though it wasn't previously in use: `Error: listen EADDRINUSE: address already in use :::8000` 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
I'm not able to repro this issue. 

> My terminal throws this error even though it wasn't previously in use: Error: listen EADDRINUSE: address already in use :::8000

What terminal are you referring to here? I want to understand where this error is coming from.

**Comment by jigar288** [comment]
> I'm not able to repro this issue.
> 
> > My terminal throws this error even though it wasn't previously in use: Error: listen EADDRINUSE: address already in use :::8000
> 
> What terminal are you referring to here? I want to understand where this error is coming from.

I am referring to the terminal in vs code that lets you run Linux commands. I am using  Ubuntu 20.04.1 LTS for my remote development environment. 

In order to resolve the `EADDRINUSE` issue I just manually killed the port so that I can run my node js application. Now my terminal is able to run my app and I got a message `Express server listening on port 8000`.

However, I still can't forward my port and VS Code show this error: Screenshot: https://i.imgur.com/mZPnWFJ.png 

I would like to think that something is wrong with my node js code. However, I didn't have this problem before the VS Code Update of Version: 1.54.1 with the same exact codebase.

This port forwarding issue is not present on applications that automatically forward the port for you. For example a simple react app. You can try setting one up. 

https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

**Comment by jigar288** [comment]
I am now VS Code 1.55.

I was able to get logs. You can find the logs in my public microsoft one drive folder (https://1drv.ms/u/s!AgwAH2eNQuq2iM4sXYWx2tK-LjUSTg?e=hoFrEe)

@alexr00, Responding to your previous post on Mar 9th. I dont have a left over process from previous time. I compeltely shut down my remote machine and restarted it.

I am still getting this error: `Error message: Unable to forward localhost:8000. The host may not be available or that remote port may already be forwarded`

**Comment by alexr00** [comment]
The link for the logs doesn't work for me. Could you copy and paste them into a comment here?

**Comment by jigar288** [comment]
> The link for the logs doesn't work for me. Could you copy and paste them into a comment here?

@alexr00 there are many lines of logs and I don't want to avoid pasting them here. I put the logs in a public github repo: https://github.com/jigar288/vs-code-logs. Please see the .rtf text files

**Comment by jigar288** [comment]
`Steps to Reproduce:

Login to Github Codespace or Remote Environment with VS Code
Try to forward a port`

**Comment by alexr00** [comment]
@jigar288 thanks for the logs.

@wachaudh and @cmbrose this appears to be an issue with Codespaces providing an undefined tunnel. Is there a place that this issue can be moved to for you to take over investigation?

**Comment by cmbrose** [comment]
This sounds like an issue @klvnraju reported which @wachaudh was investigating last week `Unable to forward localhost:8000. The host may not be available or that remote port may already be forwarded`. Do we have an issue to track that already? If not, let's create one.

**Comment by jigar288** [comment]
@alexr00 I recently downloaded `VS Code April 2021 (version 1.56)` for mac. I used the universal version. I don't have port forwarding issues with github codespaces anymore. I am closing the issue now.
