### ISSUE TITLE
!!!Need two or more search bar!!!!

### ISSUE THREAD

**Issue by V0idk** [microsoft/vscode#118390]
I already opened a search result, and want to search another word but keep last search result opened.  This scene is really common in code review to find reference

**Comment by IllusionMH** [comment]
If they are separate searches you can open results in search editors or use them from start.
Have you tried this approach?

**Comment by V0idk** [comment]
@IllusionMH I mean search in the folder, not editor

**Comment by IllusionMH** [comment]
I'm taking about different view for functionality as Find in files
https://code.visualstudio.com/updates/v1_43#_search-editors

After you perform search on a line with number of total matches/files found you should see Open in editor which will create Search Editor with your current search query and results. You can keep several editors open with different queries and switch between them

**Comment by roblourens** [comment]
Thanks @IllusionMH, I recommend using search editors for this use-case too. Supporting multiple searches in the tree view is probably not something that we will support soon.
