### ISSUE TITLE
Workspace trust is based on path, not authority + path

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118333]
- Connect to two different remotes that happen to have folders with the same path
- Trust one of them
- The other gets automatically trusted

Would be the same with a local folder + remote folder with the same path. Seems like the authority (remote name) also needs to be considered

https://user-images.githubusercontent.com/323878/110219622-417e4600-7e75-11eb-8f08-2da0f8f11f27.mp4

**Comment by sbatten** [comment]
ssh remote trusted paths should probably be stored on the remote instead of using any paths on the local machine. that would resolve this issue and makes sense so if you connect to a remote box from multiple devices you don't have to retrust.

what do you think?

**Comment by roblourens** [comment]
I would assume that trust data would be subject to settings sync anyway. Do we store any other user data besides remote settings on the remote? I'm not sure. And should I be able to untrust a workspace from a local window?

**Comment by sbatten** [comment]
> I would assume that trust data would be subject to settings sync anyway.

No, we trust on the machine level (we talk about folder paths, not repositories)

> And should I be able to untrust a remote workspace from a local window?

Perhaps, though I'm not sure how that should work. The SSH scenario has 2 machines that need to trust the source I suppose but it is a user's choice. e.g. I would not expect that I connect to a remote and open a folder that is shared between users on the remote and it is already trusted due to another user's choice.

**Comment by roblourens** [comment]
> Perhaps, though I'm not sure how that should work

I bring it up because it would be a point in favor of only keeping trust data locally. If that data is kept on the remote, then consider this scenario. If I have trusted folders on some remote, and I want to untrust them then open them, here is what I do:

- Have some local window already open
- Open the workspace trust manager
- I don't see my remote folders
- I have to know that I can open an empty window on the remote, then open the workspace trust manager where I see my folders on that remote, and now I can un-trust them

**Comment by sbatten** [comment]
> Data on the remote is stored per remote user. If people are sharing accounts, that's on them, they will already be sharing settings and extensions.

Good to know thanks for clarifying.

If the only benefit to having the setting remote is so that the user doesn't have to re-trust on a new machine, I suppose local management wins out. Let's see if there are other arguments for each and what @lszomoru thinks.

**Comment by sbatten** [comment]
The UX for remotes gets pretty confusing though. Right now we try to make it simple and being able to think about the local folder path keeps it that way. A user having to figure out which machine a path applies to and how to input that information gets more dicey.

**Comment by roblourens** [comment]
I wouldn't worry about displaying it, we already have to do that kind of thing. But if we want to support them editing and entering paths on remotes from scratch, that might be complicated.

![image](https://user-images.githubusercontent.com/323878/110372602-5ab4fd00-8003-11eb-8da0-15a967a9b7d8.png)

**Comment by sbatten** [comment]
We'd need something different than this for remotes and how to deal with multiple remotes

![image](https://user-images.githubusercontent.com/6561887/110372819-9ea80200-8003-11eb-9937-c40e5fd4f886.png)
