### ISSUE TITLE
Feature request: Add shortcut to resize sidebar left or right

### ISSUE THREAD

**Issue by eret9616** [microsoft/vscode#118377]
In vscode key bindings, there is terminal resize shortcuts, but no sidebar resize shortcuts, I'd like to see vsc add this feature...
![image](https://user-images.githubusercontent.com/12445095/110247785-e483ac80-7fa8-11eb-97af-461eee4efbd7.png)

**Comment by sbatten** [comment]
Do these commands do what you expect?
![image](https://user-images.githubusercontent.com/6561887/110362011-99dc5180-7ff5-11eb-8193-25bcfbff55d2.png)
