### ISSUE TITLE
VScode

### ISSUE THREAD

**Issue by Akira1985** [microsoft/vscode#118302]
Full Remote Development support
Improved Multi-root support
Adds Cross-platform support
Improved Side Bar usability
Adds automatic Label suggestion options
Full Multi cursor support
Support for workbench.colorCustomizations settings

**Comment by Akira1985** [comment]
Eliminate context switching and costly distractions. Create and merge PRs and perform code reviews from inside your IDE while using jump-to-definition, your keybindings, and other IDE favorites.

**Comment by IllusionMH** [comment]
Please create separate request for separate features. Also check for duplicates.

**Comment by aeschli** [comment]
Also explain what exactly you suggest to be added.
