### ISSUE TITLE
Close terminal warning shows even if no terminal is open

### ISSUE THREAD

**Issue by mjswensen** [microsoft/vscode#118321]
Issue Type: <b>Bug</b>

If you have the setting enabled to prompt before closing when there is an active terminal session, the following behavior is observed as of 1.54.1:

1. Launch VS Code
2. Quit VS Code
3. See the prompt even though there is no terminal session

Other notes:

* This also happens with extensions disabled.
* If you open a terminal and then close it again, the prompt doesn't occur.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 0eeae0c1-9660-483b-a13a-7d577c597ecd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by Tyriar** [comment]
I can reproduce this, it appears that `confirmOnExit` is working correctly, just there's a actual terminal getting initialized on launch even when the panel isn't visible.
