### ISSUE TITLE
Missing Font

### ISSUE THREAD

**Issue by PrimaIVoid** [microsoft/vscode#118382]
From "File->Open Folder->" or "File->Open File" or "File->Open Workspace" Instead of showing the text of my Files and Folders, every character is replaced by a Blank square. I suppose this is due to a missing Font. However i only have this visual bug while i'm in the browse/open file/window. Any other menu or tooltip within VSCodium works as intended. I freshly installed VSCodium through Snap. My Os is Fedora 33

**Comment by IllusionMH** [comment]
Is it reproducible in installation ov VS Code https://code.visualstudio.com/Download ?
Issue tracker for VSCodium is in different repo.

**Comment by PrimaIVoid** [comment]
Trying to install VSCode through snap or package manager didn't gave me this visual bug, so it must be related to the snap version of VSCodium. I'm closing this Issue
