### ISSUE TITLE
vscode auto import will add prefix node_modules/<package_name>

### ISSUE THREAD

**Issue by Lanseria** [microsoft/vscode#118347]
版本: 1.54.1 (user setup)
提交: f30a9b73e8ffc278e71575118b6bf568f04587c8
日期: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/14802764/110227714-43f4a480-7f36-11eb-893f-8bed17799315.png)
![image](https://user-images.githubusercontent.com/14802764/110227842-40ade880-7f37-11eb-90ac-c3219be8e27c.png)

```
import { useVModel } from "node_modules/@vueuse/core/dist";
import { uniqBy } from "node_modules/@types/lodash";
```
2. Is this my configuration problem? Or a bug
3.  I expect 
```
import { useVModel } from "@vueuse/core";
import { uniqBy } from "lodash";
```
4.  This situation will only appear in Vue file, TS file will not appear

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Please file this against the Vetur extension
