### ISSUE TITLE
TypeScript crashes while developing on devcontainer

### ISSUE THREAD

**Issue by ItsEcholot** [microsoft/vscode#118368]
Issue Type: <b>Bug</b>

I don't why this is happening at all... Just randomly freezes up while saving (running typescript formatter) or stops providing intellisense. After 10s or so it continues to work... Rinse and repeat.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 4.19.121-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 4265a63b-c93a-44e8-95b4-1d6a8dac18a9|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 4.19.121-linuxkit|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (4 x 2900)|
|Memory (System)|1.94GB (0.36GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.0
twig|wha|1.0.2
python|ms-|2021.2.625869727
jupyter|ms-|2021.3.619093157

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by ItsEcholot** [comment]
Yes it can be reproduced.
It seems this is probably more of a docker issue: https://github.com/docker/for-mac/issues/1835
So this can be closed.
I managed to lessen the hanging impact by increasing the docker CPU core count to 6 in the settings, although this doesn't completely fix it, it does help a lot.
