### ISSUE TITLE
process.env.TOKEN returns undefined

### ISSUE THREAD

**Issue by jeanenchanted** [microsoft/vscode#118352]
- VS Code Version: 1.54.1
- OS Version: 20H2

Steps to Reproduce:

1. do `npm install dotenv`
2. make an `.env` file
3. put `TOKEN=whatever` in the `.env` file
4. do `console.log(process.env.TOKEN)`
5. returns undefined

Does this issue occur when all extensions are disabled?: Yes

**Comment by delivey** [comment]
This is not a VS Code issue. You have to import dotenv before using it. You can do so by putting `require('dotenv').config()` at the top of your file. I've tested, and this fixes your problem.
