### ISSUE TITLE
outline should remember position

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#118369]
outline should remember setup inside each file.
It a pain to always lose the focus.
thanks .
![a3tg3g](https://user-images.githubusercontent.com/24865815/110243622-32f16680-7f29-11eb-9e75-bac2dc9c8556.gif)

---
Version : 1.54.1 (user setup)
Commit : f30a9b73e8ffc278e71575118b6bf568f04587c8
Date : 2021-03-04T22:38:31.419Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

**Comment by jrieken** [comment]
@joaomoreno Did the tree view state logic change? I don't recall any changes but I know that this used to work

**Comment by jrieken** [comment]
Turns out this is something wrong with the outline pane itself
