### ISSUE TITLE
Separated "Zen Mode " editer

### ISSUE THREAD

**Issue by chenxizhou233** [microsoft/vscode#118355]
Sometimes I want just look through some code in an editer and don`t want to use all of the full functions of Vscode.
So I just want something like "Windowed Zen Mode  Editer ".

**Comment by dschuessler** [comment]
You can use the [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) extension to run all the commands to make activity bar, sidebar and status bar disappear:

```
"workbench.action.toggleActivityBarVisibility",
"workbench.action.toggleSidebarVisibility",
"workbench.action.toggleStatusbarVisibility",
```

See this answer on StackOverflow on how to use the extension: https://stackoverflow.com/a/49612562/5388264

**Comment by isidorn** [comment]
F1 > toggle zen mode
