### ISSUE TITLE
Sometimes help menu disappears and there is no three-dots

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#118326]
- VS Code Version: 1.54.1 (user setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open VS Code and try shrink/expand the window

![steps](https://user-images.githubusercontent.com/5412540/110216256-5da8d400-7ec3-11eb-82e8-2519a76c1e5e.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by a5hk** [comment]
I did further tests and noticed that it can happen to other menu items. Though I never shrink my window that much, thus I never encountered that.

![1](https://user-images.githubusercontent.com/5412540/110216678-afeaf480-7ec5-11eb-8062-af97bf10b5b3.png)

![2](https://user-images.githubusercontent.com/5412540/110216683-baa58980-7ec5-11eb-9f88-3a75f47079b6.png)

**Comment by sbatten** [comment]
Reproducible with negative zoom level on latest builds.
