### ISSUE TITLE
Move away from electron

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#118308]
Hey,

This is not really a feature request, but more of an overall suggestion. I've been interested in something called [tauri](https://tauri.studio) for a while now, it's basically electron but written in Rust and is extremely lightweight, but not yet stable. It is also a lot more secure.

Moving away from electron and moving to tauri would be a big performance upgrade, allowing for more low-end devices to use VSC.

Obviously, this'd be a lot of work but I think it'd be worth it. I'm pretty sure something inside the `vscode` package for making extensions would have to change. I'd be happy to help if need be. 

This is not urgent at all, but, would be worth it in my opinion.

**Comment by pixieaka** [comment]
Sounds good!
Detail | Tauri | Electron
-- | -- | --
Installer Size Linux | 3.1 MB | 52.1 MB
Memory Consumption Linux | 180 MB | 462 MB
Launch Time Linux | 0.39s | .80s
Interface Service Provider | Varies | Chromium
Backend Binding | Rust | Node.js (ECMAScript)
Underlying Engine | C/C++ | V8 (C/C++)
FLOSS | Yes | No
Multithreading | Yes | Yes
Bytecode Delivery | Yes | No
Multiple Windows | Soon | Yes
Auto Updater | Soon | Yes (1)
Cross Platform | Yes | Yes
Custom App Icon | Yes | Yes
Windows Binary | Yes | Yes
MacOS Binary | Yes | Yes
Linux Binary | Yes | Yes
iOS Binary | Soon | No
Android Binary | Soon | No
Desktop Tray | Soon | Yes
Sidecar Binaries | Yes | No

Notes
Electron has no native auto updater on Linux, but is offered by electron-packager

**Comment by Milo123459** [comment]
Yea, it's quite an amazing piece of technology. I'm happy to help out making it!

**Comment by Milo123459** [comment]
Oh, tauri is also more secure as it's harder to inject code into applications.

**Comment by Milo123459** [comment]
Also, I'm not entirely sure how VScode renders things, like, if it uses a framework like React or something. AFAIK tauri works by using bundled code from a framework, don't quote me on that tho.

**Comment by pixieaka** [comment]
@Milo123459 https://www.youtube.com/watch?v=gnKzJRr-rd0

**Comment by Milo123459** [comment]
I'll check that out when I get home. What is the video on?

**Comment by pixieaka** [comment]
@Milo123459 The answer for your questions from VS Code team. What frontend framework does VS Code use?

**Comment by Milo123459** [comment]
Oh 😅
Will checkout later, 👍

**Comment by Milo123459** [comment]
Ah, I see, it doesn't use a framework. It just needs to be compiled to html/css/js

**Comment by Swise-Haymann** [comment]
Front end framework is different.. were are talking about the native run time of the VS code app . Which i think Tauri is a very compatible rust (most loved language of programmers) framework for...

**Comment by Milo123459** [comment]
I've done some initial research, and realised *it's easier than I thought™*. I might be able to create a PR soon.

**Comment by swise0** [comment]
Should you require a frontend framework with huge Performance and low memory overhead, I'd recommend Solidjs on your journey

**Comment by Bananaman** [comment]
> Should you require a frontend framework with huge Performance and low memory overhead, I'd recommend Solidjs on your journey

He's trying to replace the web browser wrapper/executable. Not rewrite the entire HTML GUI, lol.

**Comment by Milo123459** [comment]
If rewriting the entire GUI was *easier than I thought:tm:* then I think someone else would've done that haha. Currently, this is in my personal backlog of things I'm working on, and, is requiring another project I've been working on that can safely (at build-time) convert Electron to Tauri, no config required. It runs tests etc, to ensure it runs the same, but it's pretty massive and taking a while. I'll run this tool on this app when the tool is done.

**Comment by Milo123459** [comment]
Haha, currently 15K LOC into it; it's going pretty well with full interop for all electron APIs. I'll opensource it once it works, and well, I'll test it on VSCode :)

**Comment by Milo123459** [comment]
Update: Started working on it with a friend. Decided to double down and add some more technologies into it (Tauri + GPU acceleration). It's coming together, but, taking a while. This project is massive, and well, hope it'll be used!

**Comment by quentincaffeino** [comment]
Glad to hear that!

> This project is massive, and well, hope it'll be used!

If it would be basically a drop-in replacement or at least support >=50% of main features I'll definitely switch cause I have to run very low-end devicss from time to time.

**Comment by Milo123459** [comment]
Drop-in replacement; one command and generates it for you. It runs all the tests to ensure the app runs smoothly and stuff like that.

**Comment by NoelJacob** [comment]
@Milo123459 Any progress? I'm intending to try making a fork.

**Comment by Milo123459** [comment]
Sadly no

**Comment by TheFireCircle** [comment]
I am very curious about the current state too.
Are there any problems?

**Comment by Milo123459** [comment]
Well, I haven't been able to work on it all that much. I have covid rn which is a bit of a blocker, along with lots of API changes. In the current state of the project, I can't just make it work. I think the best course of action is just manually migrating the vscode repo to use Tauri.

**Comment by Milo123459** [comment]
Yeah, good point. It'll be like debugging issues on the browser version.

Unfortunately, I have had to move away from working on this (a while ago) due to some important IRL things going on for me. If anyone wants to take a stab at this, feel free.

**Comment by Milo123459** [comment]
Tauri 1.0 has been released!

https://tauri.app/blog/tauri_1_0

**Comment by Blyxyas** [comment]
Is there any project porting VSCode from Electron to Tauri? I haven't found any

**Comment by tgross35** [comment]
Hey @Milo123459 is the app you were working on posted anywhere? If not, would you maybe interested in making what you have public, even if not running/finished?

Tauri is gaining a ton of steam, I feel like there is quite a need for the kind of thing you discussed (not sure how far you've gotten)

**Comment by Milo123459** [comment]
I don't have much progress because it was using a super outdated version. I might start working on it again, not sure.

**Comment by MrNossiom** [comment]
Even though, migrating such a codebase that is deeply rooted in Electron might take a while, it could offer the opportunity to port parts of the code to Rust, like compute intensive tasks... Also no VS Code Core team members expressed their thoughts on this PR. I guess this has been discussed in intern, but I would be willing to get their point of view.

**Comment by Craig-Macomber** [comment]
There was a related issue here: #142194 which was closed as [out of scope](https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests). That was well before the "Tauri 1.0".

By the provided definitions of scope, it seems like this issue could be considered in scope now (It has a lot of responses, and is actionable in the short term).

Since VSCode also supports running in the browser, I suspect there shouldn't be too much compatibility work that is not also bug fixes for other browsers. Hopefully that helps address the "affordability" aspect of scoping this.

**Comment by NoelJacob** [comment]
Would it be easier to change to nutralino.js instead of Tauri? 
https://github.com/Elanis/web-to-desktop-framework-comparison

**Comment by arun-cm** [comment]
> Tauri uses different browser engines on different platforms, so it'll be Edge/Chromium on Windows, WebKit on macOS, etc. For a large & complex project like VSCode, I guess issues caused by nuanced inconsistencies across different browser engines are hard to investigate... one more layer to worry about.

![image](https://user-images.githubusercontent.com/20558853/192206574-5c06fca9-a11b-4713-9af5-8e19fa99f1a2.png)

**Comment by arun-cm** [comment]
Now [tauri ](https://github.com/tauri-apps)is using [https://github.com/tauri-apps/wry ](https://github.com/tauri-apps/wry ) - Cross-platform WebView library in Rust

**Comment by MrNossiom** [comment]
Always has been

**Comment by vdvman1** [comment]
The references to the webview used on each platform is talking about what wry ultimately uses under the hood

**Comment by Anutrix** [comment]
[Milo123459](https://github.com/Milo123459) Any updates? Any draft MRs might also be good.

**Comment by Milo123459** [comment]
Me and a friend have started working on this again. No ETA, but progress is good.

**Comment by plutoniumm** [comment]
Hey @Milo123459 it seems the demand for a Rust VSC is significant, would you consider open sourcing? So maybe the community can join in? The VSC team in an issue before marked it as out of scope so it seems like for now this will have to be a community effort

If its a matter of monetisation then maybe you could try sponsorships on it I'm sure some money would start trickling in very soon

**Comment by Milo123459** [comment]
Unfortunately, progress has kinda stopped. I don't think I intend on working on this again, but our approach was reading the `.asar`, converting all the APIS to tauri compatible APIs and scaffold it into a tauri project that could be built.

**Comment by tgross35** [comment]
Publish what you have if you can! Even if it’s very incomplete, you’ve don’t some trial and error that will help others figure it out

**Comment by sirus20x6** [comment]
Yes please just release the fork. let people have a stab at finishing it

**Comment by AbhijithGanesh** [comment]
Can anyone tell me, where I can find the fork?

**Comment by pbarnum** [comment]
It doesn't seem like @Milo123459  wants to open source their work, or no longer has the ability to do so. Either way it is unfortunate and someone else will need to start this from scratch.

**Comment by Milo123459** [comment]
We never started it other than a few ways of finding out the ASAR file (which is extremely easy) and we were more working on theoretical things. We stopped working on this because we realised this would mean it would be hell to maintain, primarily because of changing APIs all the time. It's not that I don't want to share, it's literally that we have nothing.

**Comment by AbhijithGanesh** [comment]
I'd like to start work with this again, I might be an entire newbie to the dev-side of VSCode but I would like to try giving this a shot

**Comment by AbhijithGanesh** [comment]
As a first thing, I would like to open a draft PR tagging this issue. I hope this is the process

**Comment by Milo123459** [comment]
Also, seeing how you wanted to do it: our work would be completely useless. You're trying to convert VSCode, we're trying to convert all Electron projects.

**Comment by AbhijithGanesh** [comment]
@lramos15 I think this issue deals with electron only, @Milo123459 has mentioned it. Please open the closed issue

**Comment by Milo123459** [comment]
No, you've opened a duplicate issue. My project was more advanced but you can use this as an issue for replacing electron in vscode.

**Comment by AbhijithGanesh** [comment]
Thanks @Milo123459 I will use this issue as a reference then.

**Comment by deepak1556** [comment]
Hi all, thanks for your interest in exploring an alternative runtime for VSCode desktop. Although Tauri has its advantages over Electron, it is not yet the right alternative for VSCode based on our current desktop integration with the Chromium and Nodejs runtime, you can learn more about our process architecture and some of the customizations made to the runtime for our not too recent Sandbox effort at https://code.visualstudio.com/blogs/2022/11/28/vscode-sandbox. We are following alternative desktop framework projects like Tauri, Flutter, Webview2 etc., but we are not at the point of considering a runtime migration. Please follow our roadmap https://github.com/Microsoft/vscode/wiki/Roadmap for these major updates.

**Comment by Milo123459** [comment]
I think this issue should be left open as a tracking issue. This is not just about Tauri, this is just simply about moving away from Electron.

**Comment by deepak1556** [comment]
Tracking issue will be created when we start exploring alternatives, currently there is no plan in the upcoming milestones. Closing this issue as part of our issue grooming, refs https://github.com/microsoft/vscode/issues/167999.
