### ISSUE TITLE
Residual pixels after collapsing the activity bar

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/vscode#118340]
Issue Type: <b>Bug</b>

When collapsing the activity bar, there are pixels rendered at the left border of the editor. As far as I can tell, the pixels come from the content inside the activity bar. They disappear if I resize the VS Code window.

![Screenshot from 2021-03-06 19-51-39](https://user-images.githubusercontent.com/26806995/110225717-1ec05180-7eb6-11eb-89c3-d17779196990.png)

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.10.19-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 1867)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (1.41GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 38feb786-e2b9-4ece-99f6-56c240b31583|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (95)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.0
rtf|ale|2.2.0
vscode-sqlite|ale|0.11.1
pug|ama|1.0.1
ng-template|Ang|11.2.5
toml|be5|0.5.1
vscode-tailwindcss|bra|0.5.9
better-toml|bun|0.3.2
path-intellisense|chr|2.3.0
crystal-lang|cry|0.7.3
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-eslint|dba|2.1.14
githistory|don|0.6.14
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.16
elm-ls-vscode|elm|2.0.3
emberjs|emb|1.0.1
vsc-ember-cli|fel|0.3.3
vscode-ember|emb|0.2.1
prettier-vscode|esb|5.9.2
nunjucks-template|ese|0.3.1
crystal-lang|fau|0.4.0
vscode-solution-explorer|fer|0.3.11
vscode-firefox-debug|fir|2.9.2
vscode-jest-runner|fir|0.4.31
go|gol|0.23.0
vscode-graphql|Gra|0.3.15
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
angular2-switcher|inf|0.3.3
elixir-ls|Jak|0.6.5
latex-workshop|Jam|8.16.1
Angular2|joh|11.0.0
ember-related-files|jos|1.5.0
csharpextensions|kre|1.3.6
rust-analyzer|mat|0.2.505
vscode-dbml|mat|0.3.5
postcss-language|mhm|2.1.0
fluent-icons|mig|0.0.7
Angular-BeastCode|Mik|10.0.3
xml-format|mik|1.1.2
dotenv|mik|1.0.1
vscode-mjml|mjm|1.0.4
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
python|ms-|2021.2.625869727
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
remote-wsl|ms-|0.54.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
debugger-for-chrome|msj|4.12.12
nativescript|Tel|0.11.0
nimvscode|nim|0.1.17
angular-console|nrw|17.0.0
vetur|oct|0.33.1
vscode-nuget-gallery|pat|0.0.24
EmberES6Snippets|pha|2.3.3
vscode-spring-boot|Piv|1.24.0
material-icon-theme|PKi|4.5.0
material-product-icons|PKi|1.0.2
prisma|Pri|2.18.1
java|red|0.76.0
LiveServer|rit|5.6.1
lit-plugin|run|1.2.1
jinjahtml|sam|0.16.0
vue-vscode-snippets|sdr|2.2.0
crates|ser|0.5.6
markdown-preview-enhanced|shd|0.5.16
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
svelte-vscode|sve|104.6.2
sass-indented|syl|1.8.16
mako|tom|0.2.0
cmake|twx|0.0.17
highlight-matching-tag|vin|0.10.0
vscode-svg-previewer|vit|0.7.0
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.12.1
vscode-java-test|vsc|0.28.0
vscode-maven|vsc|0.27.1
vim|vsc|1.18.9
vscode-wakatime|Wak|5.0.1
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
nativescript-ng2-snippets|www|2.0.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
pythonvspyt602cf:30265443
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
Your screenshot shows the Activity Bar. Did you mean Side Bar? See https://code.visualstudio.com/docs/getstarted/userinterface#_basic-layout and the annotated screenshot above that section.

I suggest you run the Start Extension Bisect command to investigate whether the problem is being caused by one of your many extensions.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by HymanZHAN** [comment]
@gjsjohnmurray You are right. The residual pixels are related to the content in the sidebar when it's not hidden (the more content it contains the more residual pixels).
@bpasero I will try that when I have time tomorrow (using Windows at work). If I cannot reproduce it I will report back.

**Comment by HymanZHAN** [comment]
Ok, I finally got time to do some more digging. Two new GIF attached:

![gpu_enabled](https://user-images.githubusercontent.com/26806995/110708265-6dc4fa00-81c8-11eb-8643-a38ac0831d6d.gif)

Things might be better illustrated in this GIF above. The residual pixels are fixed and will move down as you scroll down.

![gpu_disabled](https://user-images.githubusercontent.com/26806995/110708500-c4cacf00-81c8-11eb-98b3-e739f6997d5e.gif)

When running code with GPU disabled, the residual pixels seem to go away. But instead, a new dark thin line will be present when the sidebar is hidden. I've chosen a light theme to better show the line.
