### ISSUE TITLE
Expanding/autocompleting named imports in jsx/tsx files removes brackets instead

### ISSUE THREAD

**Issue by darsain** [microsoft/vscode#118363]
- VS Code Version: 1.54.1
- OS Version: Win 10

Steps to Reproduce:

1. Create jsx/tsx file.
2. Import any module with named exports.
3. Try expanding/autocompleting any.
4. VSCode removes brackets instead... 😢 

![vscode_new_tab_behavior](https://user-images.githubusercontent.com/538801/110237816-5b379000-7f3e-11eb-9c0e-3ac59d53fe9b.gif)

Occurs when all extensions are disabled.
Also occurs on a clean insiders 1.55.0 build.

This started happening in one of the most recent updates, since I remember it working not too long ago just fine.

Configuring:
```json
"emmet.excludeLanguages": [
	"typescriptreact"
]
```
stops this from happening, so I guess emmet is the culprit.

**Comment by rzhao271** [comment]
Regression caused by https://github.com/microsoft/vscode/issues/115946

**Comment by rzhao271** [comment]
Was about to make this into a candidate, but it seems vscode-emmet-helper has changed a bit. I'd prefer to just keep this change for the next release, though it will be in Insiders edition most likely tomorrow.

**Comment by rzhao271** [comment]
\closedWith bdbf585
