### ISSUE TITLE
Add more OCaml related file extensions to the OCaml group

### ISSUE THREAD

**Issue by smorimoto** [microsoft/vscode#118309]
As the title says. Some extensions haven't been added yet, so we need to add them.

**Comment by isidorn** [comment]
@aeschli this does not really work for me
Am I doing something wrong?

![Screenshot 2021-03-23 at 15 05 52](https://user-images.githubusercontent.com/1926584/112159297-4cf99d00-8be9-11eb-92bd-a72405b664e6.png)

**Comment by smorimoto** [comment]
Is it the latest development build? If so, I think you need to wait until the next release.

**Comment by isidorn** [comment]
This is the latest VS Code insiders from 5 hours ago.

**Comment by smorimoto** [comment]
I may have forgotten to update this file:
https://github.com/jesseweed/seti-ui/blob/master/styles/components/icons/mapping.less

**Comment by isidorn** [comment]
Let's reopen and @aeschli can comment

**Comment by aeschli** [comment]
Yes, sorry for not paying attention.

The file extension list in `update-icon-theme.js` is used when we generate the vscode-seti theme from the `https://github.com/jesseweed/seti-ui` repo. It is used to find an icon for a language (`ocaml`) that is not part of our built-in languages, based on the file extension associations defined in `jesseweed/seti-ui`

You still need to install an extension that defines the `ocaml` language, and it's file associations. E.g. https://marketplace.visualstudio.com/items?itemName=ocamllabs.ocaml-platform

Or you define the associations in the settings: 
```
"files.associations": {
  "*.mll": "ocaml"
  "*.eliom": "ocaml"
}
```

**Comment by aeschli** [comment]
To verify check that our seti theme has a language icon for `ocaml`:
https://github.com/microsoft/vscode/blob/2d9069014eb12609766b80a99066eaf9d5a3382e/extensions/theme-seti/icons/vs-seti-icon-theme.json#L1797

**Comment by smorimoto** [comment]
@aeschli Is there any way to enable all "ocaml. *" as well?

**Comment by aeschli** [comment]
@smorimoto Not sure what you mean. Associate all files that start with `ocaml.` to the `ocaml` language?
