### ISSUE TITLE
Simple Browser refresh button pulls from cache

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#118389]
here's a video of what I'm seeing:
https://user-images.githubusercontent.com/2644648/110261960-fb091400-7f66-11eb-9624-965cfdeba041.mp4

Version: 1.55.0-insider
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:41:28.520Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. create an HTML file with `foo` in it and use `http-server` node module to serve the HTML file
2. Open the port in the Simple Browser
3. Change the HTML file to `bar` and save the file
4. Hit the refresh button in the simple browser

I expect it to say `bar` but it still says `foo`.

Now get rid of the trailing `/` and hit enter in the address bar.

`bar` is displayed.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This happens because iframes are just the worst. I'll try add the same cache busting logic I already added for navigating to new pages

**Comment by mjbvz** [comment]
For testing: refresh always pulls from the url in the input bar. This bar does not update when you navigate on a page. I have not been able to find a way around this due to security limitations of iframes
