### ISSUE TITLE
Git Status Not Updating for Mac M1

### ISSUE THREAD

**Issue by awadell1** [microsoft/vscode#118314]
Issue Type: <b>Bug</b>

Basically what the title says, making changes (commiting, updating gitignore) does not update the source control status (Files still show as untracked).

Things I've tried:
- Reloading Window: Works but clunky
- Hitting Refresh button: Does not work

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (3.85GB free)|
|Process Argv|--crash-reporter-id d79ab85b-182c-41bd-9ebe-bab963baca74|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
make-lsp-vscode|ale|2.0.2
vscode-bazel|Baz|0.4.0
toml|be5|0.5.1
touch-bar-display|bla|1.5.0
vscode-markdownlint|Dav|0.39.0
gitlens|eam|11.2.1
prettier-vscode|esb|5.9.2
sort-json-array|fvc|3.0.0
matlab|Gim|2.0.0
vscode-pull-request-github|Git|0.24.0
latex-workshop|Jam|8.16.1
language-julia|jul|1.1.32
json2csv|kha|0.0.1
git-graph|mhu|1.29.0
python|ms-|2021.2.582707922
vscode-pylance|ms-|2021.3.0
jupyter|ms-|2021.2.603412351
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.65.0
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
vscode-coverage-gutters|rya|2.7.0
vscode-open|san|0.1.0
rewrap|stk|1.14.0
code-spell-checker|str|1.10.2
windows-terminal|Tyr|0.6.0
vscode-icons|vsc|11.1.0
grammarly|znc|0.14.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
pythonvspyt602cf:30265443
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by eamodio** [comment]
Does running `git status` on the command line work appropriately?
