### ISSUE TITLE
Microsoft Authentication on Start Fails

### ISSUE THREAD

**Issue by BarnabasMakkay** [microsoft/vscode#118362]
Issue Type: <b>Bug</b>

With each new session, I get signed out (not signed in) for the Sync Settings and Live Share features, I can successfully sign in if I click on the profile icon and sign in for my Microsoft account for both Live Share and Settings Sync, but I have to do that every time I close VSCode and open it again. GitHub account can log in on start with no issue. This problem persisted a few updates now and is getting really annoying. 

On opening VSCode I get the following error in the Microsoft Authenticator output winow:

[Error  - 10:37:32.781] Getting token failed: Error: Unable to transform input.

I'm also getting these errors while I'm logging in:

[Info  - 10:55:22.926] Exchanging login code for token
[Info  - 10:55:23.254] Exchanging login code for token success
[Error  - 10:55:23.255] Unexpected token � in JSON at position 0
[Info  - 10:55:23.255] Failed to fetch token claims from access_token. Attempting to parse id_token instead
[Info  - 10:55:23.256] Login successful

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.82GB free)|
|Process Argv|--crash-reporter-id 7c42bbe9-f41a-4350-ac27-9bdd8387e1f8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
naysayer88|dav|1.1.3
gitlens|eam|11.3.0
vscode-pull-request-github|Git|0.24.0
theme-monokai-pro-vscode|mon|1.1.18
csharp|ms-|1.23.9
vsliveshare|ms-|1.0.3912
rust|rus|0.7.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by ddzy** [comment]
same issue

**Comment by BarnabasMakkay** [comment]
The issue seems to be fixed here on latest update.
