### ISSUE TITLE
Ability to resolve patch conflicts in VS Code

### ISSUE THREAD

**Issue by EnderDev** [microsoft/vscode#118385]
Currently the resolve conflict UI only shows up for merge conflicts with Git. I think it would be awesome if we could resolve .patch conflicts using the same/similar UI.

![image](https://user-images.githubusercontent.com/42723993/110254905-1dac2480-7f89-11eb-9c17-04cd46499f71.png)

**Comment by eamodio** [comment]
Wouldn't applying a patch generate the same merge conflict (assuming of course there are conflicts)? Can you explain more about what you are trying to do and would like to see? Thanks!

**Comment by EnderDev** [comment]
Nevermind, it's fine!

I found an extension that does this, thank you!
