### ISSUE TITLE
Stop changing my workspace setting after update

### ISSUE THREAD

**Issue by Bandito11** [microsoft/vscode#118336]
Issue Type: <b>Bug</b>

Each and everytime the software self updates via de VS code update process the workspace settings go back to default.

I don't want that, I want my workspace settings to stay as it is. 

Thanks. 
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

**Comment by Bandito11** [comment]
Each and everytime the software self updates via de VS code update process the workspace settings go back to default.

I don't want that, I want my workspace settings to stay as it is. 

Thanks.

**Comment by sandy081** [comment]
Is it for all workspaces or only for a specific workspace ?

**Comment by Bandito11** [comment]
For all workspaces

**Comment by sandy081** [comment]
Strange, May I know if your user settings are retained?

Can you please disable all extensions and see if you still see the issue?

**Comment by Bandito11** [comment]
My user settings are not retained.

I cannot do disable the settings because I already set my settings back manually.

**Comment by sandy081** [comment]
> I cannot do disable the settings because I already set my settings back manually.

Not sure what you mean here? Are you able to repro the issue by disabling all extensions?
