### ISSUE TITLE
Prevent startup access to 238.172.191

### ISSUE THREAD

**Issue by pmcoz** [Microsoft/vscode#11837]
- VSCode Version: 1.5.1
- OS Version: Win 7 Home Pro 64

Steps to Reproduce:

1. Configure all privacy options to false as per [https://code.visualstudio.com/Docs#privacy](https://code.visualstudio.com/Docs#privacy)
2. Block VSCode at firewall
3. Start VSCode
4. VSCode reports 'connect EACCES 191.238.172.191:443' error

I would like to be able to control internet access without having this error message. This problem did not occur in VSCode 1.4. It would be good if there was a privacy setting to prevent this attempted access.

**Comment by joaomoreno** [comment]
We will not prevent access, but omit the message instead.

**Comment by pmcoz** [comment]
Thank you. I think it is unfortunate that VSCode no longer provides privacy settings to allow opting out of internet accesses.

**Comment by joaomoreno** [comment]
Opting out of internet access is not a privacy issue.

**Comment by pmcoz** [comment]
Gotta wonder why it's phoning home if it's been configured not to report anything nor update anything.

**Comment by joaomoreno** [comment]
As mentioned above, it's not phoning home, nor pinging the main spaceship and neither is it calling the motherland. It is looking for extension updates. This is **not** a privacy issue, so it is not included in the **privacy issues** list.

**Comment by octref** [comment]
Search for extension causes this if VSCode blocked by firewall.

It's expected, but I guess we still should show a more descriptive message.

![image](https://cloud.githubusercontent.com/assets/4033249/18972538/66590f10-864e-11e6-9d7b-7471a6810244.png)

**Comment by joaomoreno** [comment]
No, I think the message is pretty good.
