### ISSUE TITLE
Console and Tools are very far

### ISSUE THREAD

**Issue by jngm8** [microsoft/vscode#118346]
Issue Type: <b>Bug</b>

I dont know what I pressed but the terminal and the bar tools at the left look really far, and the letters are very small. I want to know what to do for those things to return normal

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.76GB (4.33GB free)|
|Process Argv|--crash-reporter-id 4e07405a-9a88-4fac-a1de-3592279f13bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.24.0
unity-code-snippets|kle|1.3.0
vscode-github|Kni|0.30.4
git-graph|mhu|1.29.0
csharp|ms-|1.23.9
python|ms-|2021.2.625869727
jupyter|ms-|2021.3.619093157
unity-debug|Uni|3.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by jngm8** [comment]
blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64

**Comment by jngm8** [comment]
blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64 sorry is this one

**Comment by jngm8** [comment]
[blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64](url)

**Comment by jngm8** [comment]
[](blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64)

**Comment by jngm8** [comment]
blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64

**Comment by jngm8** [comment]
[blob:https://gifcap.dev/8834aecf-f5b4-453f-b089-91f0561acf64](url)

**Comment by jngm8** [comment]
![recording](https://user-images.githubusercontent.com/68575075/110244045-e575f900-7f2a-11eb-83ac-bc6957f98bd4.gif)

**Comment by gjsjohnmurray** [comment]
There are two different types of zoom in VS Code. Here are the options in English in the Command Palette:

![image](https://user-images.githubusercontent.com/6726799/110257899-d0837f00-7f97-11eb-99b9-cf79c884d52f.png)

It looks like you have been using the first of these, zooming only the editor font.

**Comment by jngm8** [comment]
Thanks! Its working now.
