### ISSUE TITLE
Code Intellisense doesn't work on Macbook Pro M1

### ISSUE THREAD

**Issue by daviddesar** [microsoft/vscode#118349]
Javascript and other code intellisense don't work on Macbook Pro M1. Auto suggest is not working as well.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and whether the problem still occurs if you run with all extensions disabled.

**Comment by daviddesar** [comment]
> /needsMoreInfo including version and whether the problem still occurs if you run with all extensions disabled.

VS code version: version 1.54;
Mac OS version: Big Sur v11.2.1 (Macbook Pro M1 Silicon)
I tried disabling all extensions and tying but the intellisense didnt work;
**Update**: I know the root cause of this issue: when I switch to the typing source (from ABC to simple telex), the intellisense doesn't work; but when switching to ABC, the intellisense works correctly.

**Comment by mjbvz** [comment]
Please provide steps to reproduce the issue and describe the expected behavior
