### ISSUE TITLE
1.5.1 .deb package misses depencies

### ISSUE THREAD

**Issue by mverwijs** [Microsoft/vscode#11835]
- VSCode Version: 1.5.1
- OS Version: Ubuntu GNU/Linux 16.04

Summary: VSCode package for Ubuntu 16.04 requires several i386 packages to be installed on the system, but does not specify them as a dependency. End result is `code` not running due to missing dependencies, even though the package installs without error.

Steps to Reproduce:

1. Install the .deb package
2. Open a terminal
3. Run `code`

Expected result: VSCode opens up

Actual result: Missing dependencies:

```
mverwijs@x230 ~> code
/usr/share/code/bin/../code: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

mverwijs@x230 ~> code
/usr/share/code/bin/../code: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory

mverwijs@x230 ~> code
/usr/share/code/bin/../code: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

```

Workaround: 
```
sudo apt-get install libgtk2.0-0:i386 libxtst6:i386 libgconf-2-4:i386
```

**Comment by mverwijs** [comment]
PEBKAC. Accidentally downloaded and installed the i386 version. Which exists.

**Comment by W7PEA** [comment]
I installed the 64bit version of vscode and still had this problem. I don't think that PEBKAC is true.
