### ISSUE TITLE
Windows stops redrawing after a window resize on specific environment.

### ISSUE THREAD

**Issue by YPetremann** [microsoft/vscode#118339]
- VS Code Version: 1.53 to 1.54.1
- OS Version: Debian with awesomewm

Steps to Reproduce:

1. start vscode in an awesomewm environement
2. resize the vscode window, the window stops redrawing

Does this issue occur when all extensions are disabled?: Yes

**Comment by ruanda** [comment]
I noticed the same issue in Ubuntu 18.04 with Mate environment in anything newer than 1.52.1.
