### ISSUE TITLE
Issue Reporter is blank

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118480]
- Run "Report Issue":

![image](https://user-images.githubusercontent.com/323878/110378998-20e7f480-800b-11eb-8a66-857a98d9f834.png)

This is today's insiders

**Comment by RMacfarlane** [comment]
what's in the console if you press F12? are you connected to a remote or anything?

**Comment by roblourens** [comment]
Yeah, remote

![image](https://user-images.githubusercontent.com/323878/110386438-23e7e280-8015-11eb-8b92-a121e9ea1de8.png)
