### ISSUE TITLE
unable to conect

### ISSUE THREAD

**Issue by ashokkumar9892** [microsoft/vscode#118479]
Issue Type: <b>Bug</b>

unable to connect

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041
Fetching remote diagnostics for 'WSL: demr-stack' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (6.89GB free)|
|Process Argv|--crash-reporter-id 511dc9c4-8aa1-4d3d-8ff0-c7de62122c42|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: demr-stack' failed: VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
