### ISSUE TITLE
vscode should have its own orgnization on github.

### ISSUE THREAD

**Issue by javagg** [Microsoft/vscode#1184]
As more extensions  added to vscode, it is reasonable that all the vscode related stuff goes to one place that allow people to easily work with it.

**Comment by egamma** [comment]
Thanks for your feedback, we have considered a separate organization when we opened the code at github and decided against a separate organization. We can revisit this at a later point in time. For now the convention is to prefix vscode related repositories with `vscode-`.

**Comment by egamma** [comment]
@chrisdias fyi
