### ISSUE TITLE
Expose an API to launch a url in browser

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11848]
VSCode uses `shell.openExternal` from `electron` to launch urls in the browser. There are some places I'd like to do the same but it seems doing it manually requires platform-specific code (or another third party package to hide that).

Is it possible vscode could provide a wrapper for eletron's `shell.openExternal`? Taking a dependency on Electron directly seems crazy (if it'd even work) because we'd have to manually keep the version in sync with VSCode (not to mention it's a lot of API to pull in for one method).

**Comment by ionutvmi** [comment]
At the moment we can use a node module like [node-open](https://www.npmjs.com/package/open), but it would be nice to have it by default in the vscode api as well.

**Comment by DanTup** [comment]
I saw that one .. and that it had 19 open issues on GH (some of which seem pretty basic)! That's what got me curious about what Code did and I looked in the code to find Electron already had it :)

**Comment by mrmlnc** [comment]
(maybe) If you only need a browser, try https://github.com/sindresorhus/opn

**Comment by DanTup** [comment]
I'm trying to avoid external dependencies if I can help it; vscode extensions run on end users machines with access to a lot of stuff; I think it's irresponsible to pull in third party code from relatively-unknown devs without reviewing it. That package has two of its own dependencies and one of those has another! This is all literally so I can have a button to link the user to a download page! I'd rather just write the little xplat code myself; but since Electron already has it I thought I should ask before I re-implemented it :-)

**Comment by yairhaimo** [comment]
wouldnt this do it?
`vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('http://www.google.com'));`

**Comment by DanTup** [comment]
> wouldnt this do it?
> `vscode.commands.executeCommand('vscode.open', vscode.Uri.parse('http://www.google.com'));`

Oooooh, quick test and this seems to work!

However, the [docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) say (emphasis mine):

> vscode.open - Opens the provided resource *in the editor*. Can be a text or binary file, or a http(s) url

If it opened inside the editor, that wouldn't be what I want. I'm not why it does what I want and not what it says, but maybe someone can confirm and/or update the docs with the real logic?

**Comment by yairhaimo** [comment]
from my testing, if its an external webpage it will open it in the default browser.
if its a file it will open it in the editor.
i would *love* to find a way to open an external webpage inside the editor itself :)

**Comment by jrieken** [comment]
The recommendation is to use a node module or the aforementioned command
