### ISSUE TITLE
Sandbox: move externalTerminal.contribution to a better place

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118405]
Similar to https://github.com/microsoft/vscode/issues/117257, we have a [`externalTerminal.contribution`](https://github.com/microsoft/vscode/blob/1264c0dfbfd8a1d3d1c85293803af75bad7f95c0/src/vs/workbench/contrib/externalTerminal/node/externalTerminal.contribution.ts#L6-L6) that has lots of node.js dependencies. 

I am not sure what the best place for this would be, some ideas:
* move this where terminal services live in shared process
* introduce a new `IExternalTerminalMainService` that is running either off of main process or shared process that the renderer talks to via IPC

**Comment by Tyriar** [comment]
I think `IExternalTerminalMainService` is the right approach since this is a desktop-only feature.

**Comment by bpasero** [comment]
@meganrogge thanks, but can we try to preserve support for "Open in Integrated Terminal" for web? I think you removed that support in https://github.com/microsoft/vscode/commit/de4e9067e80f079f092006929dab05516e27c70e#diff-fbe76ba1e5f770dddb2126d52a32e8fdaf09a0723c5028aa7b62034d0f22a559. If you need a browser only solution that does not conflict with desktop, you can add an import to `src/vs/workbench/workbench.web.main.ts`.
