### ISSUE TITLE
C Run without debugging

### ISSUE THREAD

**Issue by homandiy** [microsoft/vscode#118414]
Issue Type: <b>Bug</b>

I am trying to build the C code without the debugging, but the vscode keeps showing me the debugger message for GDB. How do I stop vscode to run the debugger?

```
Homan@LAPTOP-THUV2CQ5 MINGW64 /d/VC/projects/gtk_test
$  /usr/bin/env 
c:\\Users\\Homan\\.vscode\\extensions\\ms-vscode.cpptools-1.2.2\\debugAdapters\\bin\\WindowsDebugLauncher.exe 
--stdin=Microsoft-MIEngine-In-he4d44mu.cif 
--stdout=Microsoft-MIEngine-Out-yiat4sr3.kzo 
--stderr=Microsoft-MIEngine-Error-qupwimzi.bhy 
--pid=Microsoft-MIEngine-Pid-ez1d1s12.5xt 
--dbgExe=C:\\msys64\\mingw64\\bin\\gdb.exe 
--interpreter=mi
```
I have to manually stop the debugger.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (20.58GB free)|
|Process Argv|--crash-reporter-id 88b1f9be-5eb7-4510-a761-22590ebe9339|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
include-autocomplete|ajs|0.0.4
ng-template|Ang|11.2.5
kivy-vscode|Bat|0.5.5
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
dart-code|Dar|3.20.1
vscode-terminal-for-ubuntu|Doc|0.0.2
vsc-material-theme-icons|equ|1.2.2
vscode-firefox-debug|fir|2.9.2
code-runner|for|0.11.2
kotlin|fwc|0.2.22
vscode-pull-request-github|Git|0.24.0
hclappscancodesweep|HCL|1.1.3
live-html-previewer|hdg|0.3.0
json-to-dart|hir|2.6.3
better-cpp-syntax|jef|1.15.5
Kotlin|mat|1.7.1
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-zh-hans|MS-|1.54.2
python|ms-|2021.2.625869727
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
vetur|oct|0.33.1
platformio-ide|pla|2.3.0
tsimporter|pmn|2.0.1
LiveServer|rit|5.6.1
Vite|Rui|0.0.4
pykv-snippets|Tak|1.0.8
cmake|twx|0.0.17
material-theme|zhu|3.9.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833:30267464

```

</details>

helloworld.c

```
#include <stdio.h> 
  
// main function - 
// where the execution of program begins 
int main() 
{ 
  
    // prints hello world 
    printf("Hello World"); 
  
    return 0; 
}  
```

tasks.json

```{
	"version": "2.0.0",
	// "windows": { // this is the only place where VSCode allows to add `windows`
    //     "options": {
    //         "shell": {
    //             "executable": "C:/msys64/usr/bin/bash.exe"
    //         }
    //     }
    // },
	"tasks": [
		{
			"type": "cppbuild",
			"label": "Msys64 Bash Shell",	
			"command": "C:/msys64/usr/bin/build.bat",
			"group": "build",
			"detail": "Start Msys64 Bash Shell",
			"args": [
				// "-c",
				// "sh C:/msys64/usr/bin/build.sh",
				// "-g",
				"${file}",
				// "-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe",
				"\"`pkg-config", "--cflags", "gtk+-3.0`\"", 
				"\"`pkg-config", "--libs", "gtk+-3.0`\""	
			]
		},
		{
			"type": "cppbuild",
			"label": "Msys64 Bash Old",	
			"command": "C:/msys64/usr/bin/build.bat",
			"group": "build",
			"detail": "Start Msys64 Bash Shell",
			"args": [
				// "-c",
				// "sh C:/msys64/usr/bin/build.sh",
				"-g",
				"${file}",
				"-o",
				"${fileDirname}\\${fileBasenameNoExtension}.exe",
				// "\"`pkg-config", "--cflags", "gtk+-3.0`\"", 
				// "\"`pkg-config", "--libs", "gtk+-3.0`\""	
			]
		}
	]
}
```
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - GTK C Build",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "C:/msys64/mingw64/bin",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\msys64\\mingw64\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            // "preLaunchTask": "C/C++: gcc.exe build active file"
            // "preLaunchTask": "Msys64 Bash Shell"
            "preLaunchTask": "Msys64 Bash Shell"
        }
    ]
}
```

build.bat
```
@echo off

FOR /f "tokens=* delims=" %%A in ('cygpath -u %1') do @set "file=%%A"
FOR /f "tokens=* delims=" %%A in ('cygpath -u %2') do @set "dest=%%A"
FOR /f "tokens=* delims=" %%A in ('cygpath -u %3') do @set "flag=%%A"
FOR /f "tokens=* delims=" %%A in ('cygpath -u %4') do @set "libs=%%A"

echo file = %file%
echo dest = %dest%
echo flag = %flag%
echo libs = %libs%


C:\msys64\usr\bin\bash.exe -c "sh build.sh %file% %dest% %flag% %libs%"
```

build.sh
```
#!/bin/bash
echo "gcc -g $1 -o $2 $3 $4"
gcc -g $1 -o $2 `pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
```

**Comment by aeschli** [comment]
Please file the issue against the C++ extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
