### ISSUE TITLE
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code

### ISSUE THREAD

**Issue by Sdy344** [microsoft/vscode#118404]
![1](https://user-images.githubusercontent.com/55384079/110285218-e0de3d00-801d-11eb-979e-fc3c27b97d31.jpg)
![1615186124(1)](https://user-images.githubusercontent.com/55384079/110285221-e20f6a00-801d-11eb-8381-31cb5eee91f1.jpg)
When I download the python extension to a remote server, it will report an error.
Does anyone know why？

**Comment by sandy081** [comment]
/duplicate

#117986
