### ISSUE TITLE
debugConfigurationType is not set when picking a launch config in the debug view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#118472]
Decided https://github.com/microsoft/vscode/issues/49855 has hung out long enough and am making it work in js-debug.

I noticed the `debugConfigurationType` is no longer set, because the `type` here is always undefined when selecting a config via the dropdown

https://github.com/microsoft/vscode/blob/78cb4cfc32b9f35e484cce1216897e74b8f3f50a/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L415

ultimately because there's no 3rd argument passed here

https://github.com/microsoft/vscode/blob/78cb4cfc32b9f35e484cce1216897e74b8f3f50a/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L203

Should the `config` always be retrieved from the `launch` if the former is present and the latter is undefined?

**Comment by connor4312** [comment]
I put in a fix for it, let me know if you have concerns on it

**Comment by isidorn** [comment]
Looks good, thanks for the fix, and good that we push this start of milestone to catch potential issues.

**Comment by connor4312** [comment]
To verify:

1. Select a launch config in the Debug view
2. Use the `Inspect Context Keys` command (logs to the console) to verify `debugConfigurationType` is set
3. Change the launch config to a different type
4. Verify it changes

**Comment by isidorn** [comment]
I can verify this
