### ISSUE TITLE
JSX Comments (mixed modes)

### ISSUE THREAD

**Issue by eladcandroid** [Microsoft/vscode#11844]
- VSCode Version: 1.5.1
- OS Version: Fedora 24

Steps to Reproduce:
1. Try to put a comment on a JSX row
2. The comment is "//" instead of "{/*".

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/7658

**Comment by mjbvz** [comment]
Closing as duplicate of #7658
