### ISSUE TITLE
Missing emmet command

### ISSUE THREAD

**Issue by lissien** [microsoft/vscode#118408]
Issue Type: <b>Bug</b>

The emmet command Wrap Individual Lines With Abbreviation simply went missing. I updated to the latest version, but to no avail.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (6.65GB free)|
|Process Argv|--crash-reporter-id 55f08489-67f7-4b64-acc2-b7693aed6e89|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-random|jre|1.9.0
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
wordpress-toolbox|wor|1.3.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by rzhao271** [comment]
That command is now just `Wrap with Abbreviation`. See https://github.com/microsoft/vscode/issues/109191

**Comment by Voydfox** [comment]
I have tried this command to wrap individual lines of text with a li tag but it does not work. It used to work with the old individual lines emmet command. Any ideas?

**Comment by rzhao271** [comment]
@Voydfox try using `li*`. The `*` part makes it so that it applies to each line. If that doesn't work, please file a new issue.

**Comment by Voydfox** [comment]
I was using the *, but odd enough it's now working! Must have been a one-off. Appreciate the response.
