### ISSUE TITLE
Terminal Fails to Load When Launching From Gnome Desktop

### ISSUE THREAD

**Issue by phea** [microsoft/vscode#118444]
- VS Code Version: 1.55.0-insider
- OS Version: Fedora Rawhide (Linux x64 5.12.0-0.rc0.20210225gitc03c21ba6f4e.160.fc35.x86_64)
- Gnome Desktop: 2.32.0

Steps to Reproduce:

1. Launch Code Insiders from Gnome Desktop
2.

Does this issue occur when all extensions are disabled?: Yes/No

When I launch code-Insiders from the Gnome Desktop it does not load the terminal. I have to change the Exec field to link directly to the code-insiders bin as follows for it to work.

```
[Desktop Entry]
Name=Visual Studio Code - Insiders
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code-insiders/bin/code-insiders
Icon=com.visualstudio.code.insiders
Type=Application
StartupNotify=false
StartupWMClass=Code - Insiders
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-code-insiders-workspace;
Actions=new-empty-window;
Keywords=vscode;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/share/code-insiders/bin/code-insiders
Icon=com.visualstudio.code.insiders
```

What's interesting is that if I run the original Exec `/usr/share/code-insiders/code-insiders --no-sandbox --unity-launch %F ` from a cli it does load the terminal properly.

**Comment by meganrogge** [comment]
If you go to `Help -> Open Developer Tools` what are the errors in the console?
