### ISSUE TITLE
Support subdir re-inclusion in {files,search}.exclude settings

### ISSUE THREAD

**Issue by hunterknepshield** [microsoft/vscode#118497]
I've got a directory structure like this:
```
vendor/                 <- for the most part, I don't want this dir's content to be searchable
  third_party/
  another_third_party/
  my_stuff/             <- I *do* want this content to be searchable
  .../
```

Based on the nature of `search.exclude` using booleans to control whether or not a dir is excluded, I'd expect an incantation like this to do what I want:
```
"search.exclude": {
  "vendor": true,
  // "Re-include" this subdir, even though the parent dir was excluded more generally
  "vendor/my_stuff": false,
}
```

But that doesn't have the desired effect - `vendor/my_stuff` is still excluded from search results. I've tried various permutations of changing the rule ordering and adding `/**` at the end of the patterns to no avail. Is there a magic incantation I'm missing, or does this need some change in the IDE to work?

**Comment by roblourens** [comment]
`false` only overrides the exact same key in other scopes, it doesn't work the way you expect. Currently the only way to get that would be to exclude all other folders by name except `my_stuff`.
