### ISSUE TITLE
Ctrl+Shift+E in editor creates a non-accessible textarea

### ISSUE THREAD

**Issue by KristjanTammekivi** [microsoft/vscode#118432]
Issue Type: <b>Bug</b>

1. Open an editor in Manjaro (Doesn't happen on windows, not sure about other linux distros)
2. Put the cursor anywhere in the code
3. Press ctrl+shift+e (that should switch to the explorer)
4. See it make a small textarea where you can type a few letters in but as soon as it hits the 10th letter the textarea disappears

I managed to grab the element that it creates from developer tools, here it is
```html
<textarea data-mprt="6" class="inputarea monaco-mouse-cursor-text ime-input" wrap="off" autocorrect="off" autocapitalize="off" autocomplete="off" spellcheck="false" aria-label="The editor is not accessible at this time. Press Shift+Alt+F1 for options." tabindex="0" role="textbox" aria-roledescription="editor" aria-multiline="true" aria-haspopup="true" aria-autocomplete="list" style="font-family: &quot;Fira Code&quot;; font-weight: normal; font-size: 14px; font-feature-settings: &quot;liga&quot;, &quot;calt&quot;; line-height: 19px; letter-spacing: 0px; top: 166px; left: 71px; width: 51.6924px; height: 19px;" aria-activedescendant="suggest-aria-id:0"></textarea>
```

This started happening a couple months ago.
Happens to my coworker who's on a similar setup (although uses KDE instead of Gnome)
I tried developer: toggle keyboard shortcuts troubleshooting but it doesn't show as if I pressed anything other than the modifiers being pressed
```[2021-03-08 14:02:58.609] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 16, key: Shift
[2021-03-08 14:02:58.610] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2021-03-08 14:02:58.611] [renderer3] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-03-08 14:02:58.623] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 17, key: Control
[2021-03-08 14:02:58.624] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ControlLeft, keyCode: 5 ('Ctrl')
[2021-03-08 14:02:58.625] [renderer3] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2021-03-08 14:03:07.542] [renderer3] [info] [KeybindingService]: + Storing single modifier for possible chord ctrl.
[2021-03-08 14:03:07.844] [renderer3] [info] [KeybindingService]: + Clearing single modifier due to 300ms elapsed.
```

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.10.18-1-MANJARO snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 2, 2|
|Memory (System)|31.00GB (16.09GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id e41b4f9f-5f01-4c35-b9cc-c6df9d4d49f3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by KristjanTammekivi** [comment]
I think it started happening after the january release

**Comment by KristjanTammekivi** [comment]
![image](https://user-images.githubusercontent.com/8754356/110319392-77f3c680-8017-11eb-852c-56b2b315ca40.png)
Also here you can see that I don't have anything extra bound on those keys

**Comment by alexdima** [comment]
I have heard about this before. I think this is a well known issue and some configuration needs to be changed to stop doing Emoji input via ctrl+shift+E -- https://unix.stackexchange.com/questions/394655/ctrlshifte-causes-beeping/394767#394767

See #117966 , #99508 , #72947, #70285, #70277 , #56473 , #48480

**Comment by KristjanTammekivi** [comment]
Just tested it, You're right, pressed ctrl-shift-e and typed kiss and it brought in the emoji, thanks for the quick reply this was driving me insane. Closing the issue, not a bug in vscode.

Side note: it's still weird that this doesn't happen in the OSS version of vscode

**Comment by KristjanTammekivi** [comment]
For anyone else unfortunate to find this issue, go to ibus-setup and modify emoji keyboard shortcuts from there 
![image](https://user-images.githubusercontent.com/8754356/110337474-a16c1c80-802e-11eb-8bcd-9b2ae3bd735f.png)
