### ISSUE TITLE
VSCode Source Control: open infinite repository windows

### ISSUE THREAD

**Issue by debprotim** [microsoft/vscode#118481]
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:
This issue causes CPU to reach 100%.
1. Updated the VSCode to new patch release of February 2021(version 1.54)
2. Restart VSCode
3. Open the Source Control section

Does this issue occur when all extensions are disabled?: Yes

![2021-03-08 15_42_45-DCNDS0151628 - Desktop Viewer](https://user-images.githubusercontent.com/8632083/110379767-3cf88f80-8025-11eb-83c6-31f82db6afca.jpg)

**Comment by gjsjohnmurray** [comment]
Similar to #118351 

/assign @eamodio
