### ISSUE TITLE
new Snippet is not reactivate after run Restart Extension Host

### ISSUE THREAD

**Issue by xiaosu12138** [microsoft/vscode#118416]
- VS Code Version: 1.54.1
- OS Version: macOs Catalina 10.15.5

Steps to Reproduce:

![plugin](https://user-images.githubusercontent.com/42687259/110302757-8bf9f100-8034-11eb-8064-3f6309323673.gif)

1. my snippet change in my extension
2. I run Restart Extension Host
3. my new snippet is not reactivate
4. reload window can make snippet reactivate, but my terminal restart at the same time
5. after reload window, new snippet reactivate only in current window, others still do not reactivate, but before v1.52, all window will reactivate

so, how to reload snippets without reload VS Code window by extension

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by jrieken** [comment]
What snippet file are you editing? One of an extension that you have installed or one of an extension that you are authoring?

**Comment by xiaosu12138** [comment]
> n

I have a file server and my extension is not in the market. I request new snippets from server in function "activate" and write to snippet file when extension activated

**Comment by jrieken** [comment]
> and write to snippet file when extension activated

That's not supported. The file that declares snippets is only read when the editor starts. It isn't monitored for changes. For such dynamically fetched snippets you must implement a completion item provider.

**Comment by xiaosu12138** [comment]
> > and write to snippet file when extension activated
> 
> That's not supported. The file that declares snippets is only read when the editor starts. It isn't monitored for changes. For such dynamically fetched snippets you must implement a completion item provider.

After reload window, new snippet reactivate only in current window, others still do not reactivate, but before v1.52, all window will reactivate.
About this question, can you gave me some advising please? I can through reload window or open a new window to reactivate new snippet, but it only active in current window after v1.52.
