### ISSUE TITLE
Viewing git changes of a workspace file shows a small piece of a toast window

### ISSUE THREAD

**Issue by douira** [microsoft/vscode#118461]
Issue Type: <b>Bug</b>

1. Make a new folder with a workspace file that only contains the folder itself
2. Init the folder as a git repo
3. View the changes on the untracked workspace file
4. In the bottom left corner about 10 pixels worth of toast are visible
I'm not sure what this toast does since the text isn't visible. Here's a screenshot https://imgur.com/GKfIEUB 
![Screenshot 2021-03-08 at 18 29 55](https://user-images.githubusercontent.com/17120022/110361588-83a7b300-8040-11eb-8e45-518f35c9bad5.png)

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4009)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (12.30GB free)|
|Process Argv|--crash-reporter-id 8394a6dc-72f1-4e5b-9e25-8ac7df5c1dfc|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
This looks similar to #118340

Please see https://github.com/microsoft/vscode/issues/118340#issuecomment-792508638 from @bpasero for a suggestion to try.

**Comment by douira** [comment]
Still happens with `--disable-gpu`. This issue might be different from that issue since this box is clickable.

**Comment by isidorn** [comment]
I do not think that widget has an owner.
But probably @alexdima can take a look, since the issue might be how he is using the `FloatingClickWidget` in the `diffEditorHelper` [here](https://github.com/microsoft/vscode/blame/main/src/vs/workbench/contrib/codeEditor/browser/diffEditorHelper.ts#L26)

**Comment by alexdima** [comment]
This is the "Open Workspace" floating widget:

To get it, you need to compare a `.code-workspace` file with any other file and then switch the diff editor to inline view.

![image](https://user-images.githubusercontent.com/5047891/111999668-7baa4180-8b1d-11eb-8bcf-7ce05e8c69b8.png)
