### ISSUE TITLE
`getProcessList` returns undefined for `windows-process-tree`

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode#118465]
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a .NET Function project in the Azure Functions extension
2. Debug the project which launches the `Attach to .NET Functions` task
3. After the build process finishes, this error is thrown: 
![image](https://user-images.githubusercontent.com/5290572/110365632-1b35e300-7ffa-11eb-8b1f-1963bc1373e5.png)

This windows process is returning undefined here: https://github.com/microsoft/vscode-azurefunctions/blob/aec556f026193e855e3dafb706eafb8db2782aca/src/commands/pickFuncProcess.ts#L161

I believe the source of it is coming from this code: https://github.com/microsoft/vscode-azurefunctions/blob/main/src/utils/windowsProcessTree.ts#L11

All repros have been on Windows machines so far; here's the issue where it was originally reported. https://github.com/microsoft/vscode-azurefunctions/issues/2737

Does this issue occur when all extensions are disabled?: Yes

**Comment by TylerLeonhardt** [comment]
couple things...

1. Can you confirm that this code actually returns `undefined`:
```
windowsProcessTree.getProcessList(Number(pid), resolve, ProcessDataFlag.None);
```
found here: https://github.com/microsoft/vscode-azurefunctions/blob/aec556f026193e855e3dafb706eafb8db2782aca/src/commands/pickFuncProcess.ts#L159

or is it that `windowsProcessTree` is itself `undefined` and that `new Promise` isn't handling the `reject` case?

2. Try to repro this outside of VS Code by using the npm package directly:
https://github.com/microsoft/vscode-windows-process-tree

**Comment by ejizba** [comment]
This should be closed in favor of https://github.com/microsoft/vscode/issues/118256, which is the actual root cause of our issue.
