### ISSUE TITLE
Unable to search the command palette with special characters

### ISSUE THREAD

**Issue by joglr** [microsoft/vscode#118469]
- VS Code Version: 1.54.1
- OS Version: Windows 10 Pro build 19042.804

Steps to Reproduce:

1. Install, for example, [the ionide F# extension](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp)
2. Search the command palette for F#

Does this issue occur when all extensions are disabled?: Not relevant

![image](https://user-images.githubusercontent.com/1959615/110368167-f157dd00-8048-11eb-8333-d560fa628132.png)

**Comment by chrmarti** [comment]
quickInputList.ts is using matchesFuzzy in filters.ts for filtering.
