### ISSUE TITLE
Problem on #include <arduino.h>

### ISSUE THREAD

**Issue by Electronix48** [microsoft/vscode#118415]
Nous avons écrit les données nécessaires dans votre presse-papiers, car elles étaient trop volumineuses à envoyer. Veuillez les coller.
Issue Type: <b>Bug</b>

I 've got a problem on the #include line, i can't build my project because of the #include <arduino.h> is red underlined.Is someone help me please.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.77GB free)|
|Process Argv|--crash-reporter-id d6643b23-d84d-4765-8c97-4a2f42e1519c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.2
vscode-language-pack-fr|MS-|1.54.2
cpptools|ms-|1.2.2
platformio-ide|pla|2.3.0
vscode-arduino|vsc|0.3.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by aeschli** [comment]
Please file the issue against the C++ extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
