### ISSUE TITLE
Where are error highlights?

### ISSUE THREAD

**Issue by Irinova** [microsoft/vscode#118457]
I have a problem, any of incorrect strings are not highlighting as error in js file. Example: test() without importing test looks like correct. What do I need to install to highlight this?

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform. Maybe also paste a screenshot.

Tip: for future reports, use Report Issue from the Help menu, which will automatically include version and platform information.

**Comment by Irinova** [comment]
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.36GB free)|
|Process Argv|--crash-reporter-id c757c0ef-4e09-4fa7-825e-81553a745a50|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
vscode-toggle-quotes|Bri|0.3.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
jsrefactor|cms|2.20.6
jshint|dba|0.11.0
vscode-eslint|dba|2.1.14
EditorConfig|Edi|0.16.4
prettier-vscode|esb|5.9.2
vscode-svelte-snippets|fiv|0.5.0
rest-client|hum|0.24.4
svelte-vscode|Jam|0.9.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
remote-containers|ms-|0.163.0
custom-autoimport|rul|0.1.2
vs-code-prettier-eslint|rve|0.4.1
autoimport|ste|1.5.3
errorlens|use|3.2.4
vscodeintellicode|Vis|1.2.11
quokka-vscode|Wal|1.0.345
vscode-js-import|wan|0.15.5
twig|wha|1.0.2


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
When you run VSCode with all extensions disabled, do you still see the problem?
`Developer: Run with Extensions Disabled` command from the palette will help you check this.
