### ISSUE TITLE
PHP Syntax Highlighting Bug

### ISSUE THREAD

**Issue by m3ow0rk** [microsoft/vscode#118450]
Issue Type: <b>Bug</b>

Write following Code:
```
<?php

/*** GET ***/
$System->Router('DELETE /push/*', function ($self, $variables) {
    ...
});
$System->Router('GET /push', function ($self, $variables) {
    ...
});
```
---

Now you can see, that everything after /push/* will be handled as a comment in highlighting. But it's not. Is this a known issue?

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0 (macOS Big Sur 11.2.2)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 69e80782-52da-46e5-9b3f-4263165c9e57|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
swagger-viewer|Arj|3.0.1
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
html-snippets|gey|0.2.3
unibeautify-vscode|Gla|0.8.2
gc-excelviewer|Gra|3.0.41
beautify|Hoo|1.5.0
vscode-picture|Jak|1.0.0
vscode-sshfs|Kel|1.19.4
tag-inserter|l7s|1.4.0
prettify-json|moh|0.0.3
jupyter|ms-|2021.3.619093157
hexeditor|ms-|1.4.0
vscode-yaml|red|0.16.0
html5-skelton|sha|1.0.1
html5-boilerplate|sid|1.1.1
sonarlint-vscode|Son|1.20.1
HTML5-extension-pack|wal|0.0.3
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by roblourens** [comment]
We have had other sql highlighting bugs but I don't see one for this exactly. Filed https://github.com/atom/language-php/issues/418 upstream
