### ISSUE TITLE
(File, Edit, Selection, View, etc.) menus after F11

### ISSUE THREAD

**Issue by SilasPDJ** [microsoft/vscode#118475]
They don't show up after activating full screen with F11

**Comment by IllusionMH** [comment]
Looks like you are describing intended behavior - hide OS view and menu bar (merged with window title and controls).
If you need to access them in Full Screen mode - you can press <kbd>Alt</kbd> to show them.

See https://www.youtube.com/watch?v=IKCSYhX1o3k

**Comment by SilasPDJ** [comment]
> Looks like you are describing intended behavior - hide OS view and menu bar (merged with window title and controls).
> If you need to access them in Full Screen mode - you can press Alt to show them.
> 
> See https://www.youtube.com/watch?v=IKCSYhX1o3k
> 
> Do you see different behavior?

I saw, and thanks, you solved my issue
