### ISSUE TITLE
The terminal process terminated with exit code: 127. and Extension host terminated unexpectedly. on Mac

### ISSUE THREAD

**Issue by OOOHA** [microsoft/vscode#118401]
Issue Type: <b>Bug</b>

I'm using vscode on my MacBook Pro 2017(intel) with Mac OS Big Sur 11.2.1

After I update to the latest vscode version the issue below always happend nomatter how many times I restart vscode.
First it pop up "Extension host terminated unexpectedly."
I try to use . code to open a new window in terminal then the error pop up "The terminal process terminated with exit code: 127. "
While these errors showed up all functions in vscode are  down even the report an issue.
Then I run F1 > Help: Start Extension Bisect I can use the issue reporter again.But it's still not solve my problem and again the error "The terminal process terminated with exit code: 127". pop up again. 
If I go to Ternimal > new ternimal the error pop out immediately. 

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 11, 10|
|Memory (System)|8.00GB (0.63GB free)|
|Process Argv|--crash-reporter-id 3f12e0b1-128d-4528-9fb3-29fc2b9c754f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by albas99** [comment]
I'm also struggling with the exact same issue, same computer, same OS version, and same vscode version.

I've opened the developer tools and I'm getting the following message in the console:

`workbench.desktop.main.js:2765 events.js:292      throw er; // Unhandled 'error' event      ^Error: read ENOTCONN    at tryReadStart (net.js:573:20)    at Socket._read (net.js:584:5)    at Socket.Readable.read (_stream_readable.js:467:10)    at Socket.read (net.js:624:39)    at new Socket (net.js:376:12)    at Object.Socket (net.js:267:41)    at createSocket (internal/child_process.js:314:14)    at ChildProcess.spawn (internal/child_process.js:437:23)    at Object.spawn (child_process.js:557:9)    at Launcher.launch (/Users/faisalalbasu/.vscode/extensions/auchenberg.vscode-browser-preview-0.7.0/node_modules/puppeteer-core/lib/Launcher.js:132:40)    at Browser.launchBrowser (/Users/faisalalbasu/.vscode/extensions/auchenberg.vscode-browser-preview-0.7.0/ext-src/browser.ts:54:20)    at Browser.newPage (/Users/faisalalbasu/.vscode/extensions/auchenberg.vscode-browser-preview-0.7.0/ext-src/browser.ts:63:7)    at BrowserViewWindow.launch (/Users/faisalalbasu/.vscode/extensions/auchenberg.vscode-browser-preview-0.7.0/ext-src/BrowserViewWindow.ts:36:26)    at BrowserViewWindowManager.create (/Users/faisalalbasu/.vscode/extensions/auchenberg.vscode-browser-preview-0.7.0/ext-src/BrowserViewWindowManager.ts:78:5)Emitted 'error' event on Socket instance at:    at emitErrorNT (internal/streams/destroy.js:92:8)    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)    at processTicksAndRejections (internal/process/task_queues.js:84:21) {  errno: 'ENOTCONN',  code: 'ENOTCONN',  syscall: 'read'}`

**Comment by OOOHA** [comment]
I test my M1 Mac mini as well.
It's Mac OS Big Sur 11.2.1 and using the latest VSCode arm version.
The Error is the same with my laptop.

**Comment by Tyriar** [comment]
I'm guessing these two errors are unrelated. For the terminal one, what's in your settings.json file?

**Comment by OOOHA** [comment]
This one is my Mac mini's.

{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "code-runner.runInTerminal": true,
    "C_Cpp.updateChannel": "Insiders",
    "python.jediEnabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "todo-tree.tree.showScanModeButton": false,
    "code-runner.saveFileBeforeRun": true,
    "cSpell.language": "en,en-US",
    "java.home": "/Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "python.languageServer": "Pylance",
    "go.toolsManagement.autoUpdate": true,
    "cmake.configureOnOpen": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "window.zoomLevel": 2,
    "workbench.editorAssociations": [],
    "sonarlint.rules": {
        "java:S106": {
            "level": "off"
        }
    }
}

**Comment by OOOHA** [comment]
This one is on My MacBook Pro 2017.
`{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "code-runner.runInTerminal": true,
    "C_Cpp.updateChannel": "Insiders",
    "python.jediEnabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "todo-tree.tree.showScanModeButton": false,
    "code-runner.saveFileBeforeRun": true,
    "cSpell.language": "en,en-US",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "python.languageServer": "Pylance",
    "go.toolsManagement.autoUpdate": true,
    "cmake.configureOnOpen": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "window.zoomLevel": 2,
    "workbench.editorAssociations": [],
    "sonarlint.rules": {
        "java:S106": {
            "level": "off"
        }
    }
}{
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-icons",
    "code-runner.runInTerminal": true,
    "C_Cpp.updateChannel": "Insiders",
    "python.jediEnabled": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.errors.incompleteClasspath.severity": "ignore",
    "todo-tree.tree.showScanModeButton": false,
    "code-runner.saveFileBeforeRun": true,
    "cSpell.language": "en,en-US",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "python.languageServer": "Pylance",
    "go.toolsManagement.autoUpdate": true,
    "cmake.configureOnOpen": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "window.zoomLevel": 2,
    "workbench.editorAssociations": [],
    "sonarlint.rules": {
        "java:S106": {
            "level": "off"
        }
    }
}`

**Comment by Tyriar** [comment]
> `"terminal.integrated.shell.osx": "/bin/zsh"`

@OOOHA Does zsh exist on both machines and does it launch correctly without erroring out?

**Comment by OOOHA** [comment]
Yes.
I think Zsh is the default shell for MacOS science 2019.
They launch normally in the previous version.

**Comment by OOOHA** [comment]
I found out something today might have help.
But I'm not sure if it's correct.
