### ISSUE TITLE
File search can exceed max string length

### ISSUE THREAD

**Issue by baoziv587** [Microsoft/vscode#11842]
# - VSCode Version: 1.5.1
# - OS Version:mac OS X 10.11.6

Steps to Reproduce:

1. open file search window (command+p)
2. input something 

I can not get any file search result in my project  after updating The latest version of vscode(1.5.1).

And i noticed that when i am typing some keyword of file name ,CODE will generate some subprocess do these search job with  `80 percent of the CPU cost`

![vs-pic](https://cloud.githubusercontent.com/assets/7347513/18415860/b97c13b4-7833-11e6-8b42-dcfa553fa091.png)

Function decodeData(invoked by Class FileWalker) always got same   error`('vs/workbench/services/search/node/fileSearch.ts'). `

I did not find out the reason , hope these info is helpful.

![errinfo](https://cloud.githubusercontent.com/assets/7347513/18415883/97cb413a-7834-11e6-951a-255408828e55.png)

**Comment by bpasero** [comment]
@chrmarti fyi

**Comment by shaoshuai0102** [comment]
Same problem here. Find processes take nearly 100 percent of my CPU.

**Comment by chrmarti** [comment]
The error appears to indicate the process ran out of memory. It looks like the find command doesn't always terminate or is spawned multiple times. Not sure if decoding might play a role here.

@baoziv587 could you run `time (find -L . -type f | wc -c)` in your project folder and paste the output here? That might allow us to assess if it is something with the find command itself.

@bpasero are there known issues with node's built-in string_decoder module, should I be using iconv-lite instead?

**Comment by baoziv587** [comment]
@chrmarti 

the output 
-----------
 672575727
( find -L . -type f | wc -c; )  3.90s user 21.72s system 108% cpu 23.625 total

**Comment by bpasero** [comment]
@chrmarti iconv is only used to decode non-utf8 to utf8 and when utf8 is set it falls back to use the node.js decoder. You think this is an encoding issue?

**Comment by chrmarti** [comment]
Not encoding related then. That string is simply too long.

@baoziv587 Could you also run `time (find -L . -type f | wc -l); echo $?`? That will tell us how many files your project folder has and what exit code the find command has. This is to better understand why the output of find is so large.

**Comment by baoziv587** [comment]
@chrmarti ,my project total 2,164 files.

# the output
----
 3285397
( find -L . -type f | wc -l; )  2.43s user 19.93s system 103% cpu 21.554 total
0

**Comment by baoziv587** [comment]
@chrmarti  Perhaps because of these floders. If  skip these folders ,there are alright

@shaoshuai0102 you also install node_modules with cnpm?

![image](https://cloud.githubusercontent.com/assets/7347513/18479482/c86a50f4-7a07-11e6-9285-26c302571ca7.png)

**Comment by chrmarti** [comment]
Thanks @baoziv587. I will use this report to track the string size problem and #11874 the underlying problem that we retrieve the entire file list before applying the exclusion filters.

**Comment by chrmarti** [comment]
The underlying problem is fixed in the latest insiders build. Will still address this one.

**Comment by baoziv587** [comment]
ok,thanks @chrmarti

**Comment by roblourens** [comment]
Verified by code review
