### ISSUE TITLE
F5 on a virtual document pop FileDialog

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode#118428]
Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. open a virtual document, such as the office [virtual-document-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/virtual-document-sample)

2. press F5, it pop a FileDialog that is not expected, i just want to debug my code, not save file. I think it's a bug.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/995909/110313030-d8e3c480-8040-11eb-8c4f-82a26db99f36.png)

**Comment by isidorn** [comment]
Use this setting 	
```
"debug.saveBeforeStart": "nonUntitledEditorsInActiveGroup",
```
