### ISSUE TITLE
Ability to add links to diagnostics and render them as links in problems view

### ISSUE THREAD

**Issue by darkred** [microsoft/vscode#11847]
For example, linting `var test = 1`
results in these warnings in the Problems panel:
![2016-09-11_185535](https://cloud.githubusercontent.com/assets/723651/18418560/614fcde8-7851-11e6-95e1-eb620d3ef8c2.jpg)
My suggestion:
the `no-unused-vars` and `semi` to be clickable and to link to
http://eslint.org/docs/rules/no-unused-vars and to 
http://eslint.org/docs/rules/semi
respectively.

_(I've found this feature in AtomLinter and it's really useful)_

cc: @dbaeumer 

<br>
PS. Using vscode-eslint 1.10.18 with ESLint 3.5.0 
in VSCode 1.5.1 using win10 x64.

**Comment by dbaeumer** [comment]
Like the idea of having a link in the problems panel to point to documentation. @sandy081

**Comment by sandy081** [comment]
@dbaeumer Does the problem diganostics have information about these external links?

**Comment by dbaeumer** [comment]
@sandy081 no we would need to add it.

**Comment by bpugh** [comment]
I would like to take a stab at this if no work has already been done. FYI looks the Atom linter-eslint folks pulled this logic out into a standalone module we could use pretty easily: https://github.com/jfmengels/eslint-rule-documentation

**Comment by sandy081** [comment]
@bpugh That would be great. No work has not been started. Let me know if you need any assistance.

**Comment by bpugh** [comment]
Thanks! I did have one question though. It looks pretty straightforward to add the url to the message from `vscode-eslint` but we're currently using the diagnostics api to display the messages in the problems panel but it doesn't seem to allow anyway to link to an external url. Would this require a PR to vscode as well?

**Comment by rmartins90** [comment]
+1

**Comment by kuschti** [comment]
👍

**Comment by gerrywastaken** [comment]
@sandy081 I believe @bpugh was asking you that question but didn't tag you.

p.s. @rmartins90 @kuschti  You thumbs up comments directly instead of adding spam.

**Comment by sandy081** [comment]
@bpugh Yes, this needs to be implemented in VS Code too, to detect and render links in Problems view.

**Comment by selrond** [comment]
No progress on this one? 
Would be totally handy!

**Comment by jeffwilcox** [comment]
I'd be a fan, too, including linking to optional external URLs... for example, I have an extension that integrates with known vulnerabilities for certain components; I'd love to be able to link in the problem space to the actual advisory URL with more details... today folks have to copy/paste from the `Diagnostic` message/text to get the URL out.

**Comment by callagga** [comment]
+1

**Comment by LitileXueZha** [comment]
Hey guys, how are things going

**Comment by thibaudcolas** [comment]
Progress update – I think I figured out all of the places that would/could support those links:

<img width="751" alt="diagnostic-link-ui" src="https://user-images.githubusercontent.com/877585/46998655-db6db880-d12b-11e8-895e-e1c4e6e4b196.png">

- The hover modal, where at the moment content is displayed as a code block (I added the link shown in the screenshot)
- The F8 panel
- The Problems tree viewer, with its highlighted labels for filtering

If anyone has thoughts on how to handle the URLs in each of these, please let me know.

**Comment by thibaudcolas** [comment]
Attempted a PR (well, 3 PRs) for this over at:

- https://github.com/Microsoft/vscode/pull/61436
- https://github.com/Microsoft/vscode-languageserver-node/pull/432
- https://github.com/Microsoft/vscode-eslint/pull/562

Feedback welcome, especially on the UI side! If anyone wants to try it out locally, the instructions are at the end of https://github.com/Microsoft/vscode/pull/61436.

**Comment by dbaeumer** [comment]
Nice work. I am willing to cover the LSP & eslint work if we decide to support this. One thing I noticed by quickly looking at the change. I would name the property docUrl to make it clear that this refers to a documentation and not to a resource.

**Comment by jrieken** [comment]
Stupid question, but why isn't [`DiagnosticRelatedInformation`](https://github.com/Microsoft/vscode/blob/34ee4b8daafaf75a08d9d430542400a11f10f8d4/src/vs/vscode.d.ts#L4028) sufficient for this? The `url` property looks a little like some bolt on API to me and nothing that I would naturally expect in this domain. 

Also, if the sole purpose is to render a link with a diagnostic message then we should consider 
https://github.com/Microsoft/vscode/issues/54272 which is about allowing diagnostic messages to be markdown formatted text.

**Comment by thibaudcolas** [comment]
@jrieken definitely not a stupid question – you probably understand those APIs much more than I ever will. My understanding is that `DiagnosticRelatedInformation` is meant to point to code locations. It feels strange to use this for a URL that's always going to point at the same location than the diagnostic.

**Comment by thibaudcolas** [comment]
https://github.com/Microsoft/vscode/pull/61436#issuecomment-437942788

My PR(s) got closed pending further discussion, so I won't work on this further.

**Comment by glen-84** [comment]
If we have to use the message to include the linked code, then the code is going to be displayed twice (once in the message and once separately) – not sure if that's a good idea.

I tend to agree with @thibaudcolas – it makes sense to associate the code with a URL.

**Comment by sandy081** [comment]
After going through all comments, it seems there is a need to link error code to a location that has information about the error code. Since this is very specific to error code, it does not makes sense to add URI property to diagnostic. Instead the `code` property should contain the link. Example:

```
code?: string | number | { code: string | number, link: Uri };
```

@jrieken What do you think?

**Comment by jrieken** [comment]
I think that's overloading the `code` property too much. Why don't we use `DiagnosticRelatedInformation`?

**Comment by dbaeumer** [comment]
That would for ESLint add a child for every diagnostic object. Not sure if that will look nice.

**Comment by sandy081** [comment]
> Why don't we use DiagnosticRelatedInformation?

Not sure if it's a good idea to use a property for an unrelated purpose. I think `code` property is the right one to have information about link that explains `code`.

**Comment by sandy081** [comment]
From @DanTup 

using RelatedInformation sounds wonky to me, and I don't think supporting formatted content in errors solves the problem (I don't want to clutter the error list even more with visible links, the context menu is an idea place for it).

**Comment by glen-84** [comment]
Since no one agrees with using `relatedInformation`, are there any further objections to @sandy081's suggestion? It seems like the most logical option.

**Comment by DanTup** [comment]
@sandy081 has there been any more discussion on this? It would be really nice for users to get these links in somewhere (and I think your proposal of joining them with code makes a lot of sense).

**Comment by DanTup** [comment]
> `code?: string | number | { code: string | number, link: Uri };`

Thinking about this again - for LSP I think this would be breaking and need an opt-in flag/capability (existing clients would choke on the new format). If `url` was added as its own optional property, that would be simpler?

**Comment by sandy081** [comment]
No discussions.

**Comment by DanTup** [comment]
@sandy081 I don't suppose there's been any progress on this? I think this would be a neat feature for all languages and there's no easy workaround (if we inject our own code actions for this we have to mark them as quick-fixes, which will cause them to show up in places that don't make sense - like if the user has a quick-fix keybind).

**Comment by ChuckJonas** [comment]
Seems like a trivial thing to implement and would make the user experience soo much better.  Please add

**Comment by is-joshua** [comment]
Doesn't the new MDN reference link that was recently added to the hover message make this a little easier?

MDN Reference for HTML and CSS
VS Code now displays a URL pointing to the relevant MDN Reference in completion and hover of HTML & CSS entities
- [Release Notes](https://code.visualstudio.com/updates/v1_38#_languages)

**Comment by sandy081** [comment]
I was thinking to link this with #54272 and support links in diagnostic message. But looks like it won't be feasible as rendering a markdown message in problems panel is not trivial. 

@dbaeumer @jrieken Please let me know your opinion about adding links to `code` property?

**Comment by jrieken** [comment]
> @dbaeumer @jrieken Please let me know your opinion about adding links to code property?

I already did: https://github.com/microsoft/vscode/issues/11847#issuecomment-444918802

**Comment by DanTup** [comment]
If the link is added to related information, how would it be rendered? I'd really like to have a context-menu action to launch help documentation for an error, but I really do not want every message to become expanded with a visible hyperlink in the problems view - that would be incredibly spammy (especially when many of them are the same links).

**Comment by octref** [comment]
### Proposed API

```ts
export interface Diagnostic {
	/**
	 * Will be merged into `Diagnostic#code`
	 */
	code2?: {
		/**
		 * A code or identifier for this diagnostic.
		 * Should be used for later processing, e.g. when providing [code actions](#CodeActionContext).
		 */
		value: string | number;

		/**
		 * A link to a URI with more information about the diagnostic error.
		 */
		link: Uri;
	}
}
```

### Sample usage

```ts
const fooErrors = vscode.languages.createDiagnosticCollection('foo');
let disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
	fooErrors.clear();

	const activeDocUri = vscode.window.activeTextEditor!.document.uri;

	fooErrors.set(activeDocUri, [
		{
			range: new vscode.Range(0, 0, 0, 5),
			message: 'You should always use semicolon;',
			source: 'eslint',
			code: '@typescript-eslint/semi',
			code2: {
				value: '@typescript-eslint/semi',
				link: vscode.Uri.parse('https://eslint.org/docs/rules/semi')
			},
			severity: vscode.DiagnosticSeverity.Error,
		},
		{
			range: new vscode.Range(1, 0, 1, 5),
			// message: 'Ensures that double quoted strings are passed to a localize call\nto provide proper strings for\ndifferent locales',
			message: 'Ensures that double\nquoted strings are passed to a localize call to provide proper strings for different locales',
			source: 'eslint',
			code2: {
				value: 'code-no-unexternalized-strings',
				link: vscode.Uri.parse('https://github.com/microsoft/tslint-microsoft-contrib/blob/master/src/noUnexternalizedStringsRule.ts')
			},
			severity: vscode.DiagnosticSeverity.Error,
		}
	]);
});
```

### Behavior

- The link is rendered in Problems Panel, Diagnostics Hover and Goto Error View.
- The click behavior is similar to other link clinks: https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier
- The tooltip updates as you change `editor.multiCursorModifier`

![demo](https://user-images.githubusercontent.com/4033249/73058447-f634ee00-3e93-11ea-8643-55ea970e707a.gif)

**Comment by sandy081** [comment]
Moving this to finalisation phase as this is a simple addition.

**Comment by jrieken** [comment]
> Moving this to finalisation phase as this is a simple addition.

There is no API sync this week, we will not finalise this during January. Please keep the item open and schedule the finalisation for Feb

**Comment by jrieken** [comment]
wrt to the API proposal, we should use `target` (or `uri`) instead of `link`. The former would align this with the `DocumentLink`-api.

**Comment by henryju** [comment]
In SonarLint we are already allowing users to open rule description (using a code action), so this feature would be useful as a replacement. But we are displaying rule description directly inside VSCode (using a web view panel). Do you know if this feature would support URI with custom scheme, so that we could use our own handler and not open an external browser?

**Comment by jrieken** [comment]
Yeah, using whatever uri-scheme should be supported by this but I do wonder why SonarLint uses a web view and not just a browser? Is that your help text is dynamic or private?

**Comment by henryju** [comment]
Our help text is indeed [dynamically generated](https://github.com/SonarSource/sonarlint-vscode/blob/bcd7c7a6d0d142496ef2c976e4e6ad3122afbe39/src/rulepanel.ts#L14) from metadata coming from the embedded analyzer (rule name, severity, markdown description converted to HTML, ...). This is better for us to rely on embedded analyzer metadata than trying to host online content, since it will perfectly match the analyzer version, and also this will work when user has no internet connexion.

**Comment by jrieken** [comment]
Ok, that makes sense. For us it is important that the link has a direct connection to the error-code, hence the shape of the API and that it isn't a generic link

**Comment by jvilk-stripe** [comment]
👋 would this be added to the language server protocol? This is a very useful feature for surfacing documentation for errors.

**Comment by dbaeumer** [comment]
Yes, this will be added to the LSP as well.

**Comment by octref** [comment]
Steps:

- Read this API: https://github.com/microsoft/vscode/blob/bddc5ef7019edf0a1c2d8be9ba2cba832cd614cb/src/vs/vscode.d.ts#L4676-L4691
- Write an extension that uses this API. Make sure if you provide `target`, a link is rendered with the `value` as text and upon clicking opens the link in problems-view/inline-error-view/error-hover. Here's how it works roughly: https://github.com/microsoft/vscode/issues/11847#issuecomment-578055139

**Comment by ChuckJonas** [comment]
Is this update live?  

I see the new types in the API, but I'm not seeing the actual link show up in the diagnostic UI.

I followed the implementation (same as #11847 (comment))
