### ISSUE TITLE
Github issues notebook uses markdown renderer by default

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#118463]
1. Open my-work.github-issues
2. Run a query
3. Markdown output is displayed by default 🐛 

![](https://memes.peet.io/img/21-03-284f43a3-1ba7-491f-9f68-a14e041619f9.png)

It also reverts to markdown whenever I re-run the cell

**Comment by mjbvz** [comment]
Seems to be working fine for me. I think the GitHub issues notebook extension just needed to be updated after we changed some notebook apis
