### ISSUE TITLE
Quick fix to implement interface does not work if interface contains certain external references

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#118467]
Working in js debug in the latest Insiders (TS 4.2.3):

**x.ts**

```ts
export interface IFoo {
  bar(): void;
}
```

**y.ts**

```ts
import { IFoo } from './x';

export class Foo implements IFoo {

}
```

1. Trigger a quick fix on `Foo`
2. You have the option to implement the interface
3. Add `import { ExtensionContext } from 'vscode'` to x.ts and change the interface to `bar(x: ExtensionContext): void`
4. There is no longer an option to quick fix

**Comment by mjbvz** [comment]
Works fine for me in a simple project with just those files and `@types/vscode`

![Screen Shot 2021-03-08 at 11 04 20 AM](https://user-images.githubusercontent.com/12821956/110368541-09eed580-7ffe-11eb-9c25-6da9d28674d5.png)

Any extra steps?
