### ISSUE TITLE
When I changed the font size of the editor, the font of the Output window was also changed, which is not good, but I also can't find a configuration to change the font of the Output window

### ISSUE THREAD

**Issue by gitQqqHs** [microsoft/vscode#118411]
I have used VS Code for a long time, when I changed the font size of the editor, the font of the Output window was also changed, which was not good, but I did not find the configuration to change the font of the Output window.The Output window is mainly for message Output and does not follow the editor to change the font size.Smaller fonts provide more output and reduce scrolling.A strong Output can provide better information.
Can you provide font size and font configuration in the configuration?

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/21489
