### ISSUE TITLE
work with .tpl files

### ISSUE THREAD

**Issue by meteoros** [microsoft/vscode#118449]
- VS Code Version: 1.54.1
- OS Version: windows x64 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

I want to work in a .tpl file but i need the auto complete html like an html or php file, is there a solution for this?

**Comment by aeschli** [comment]
I'm not familiar with tpl. If it's a new language, maybe there's an extension in the marketplace. Otherwise you can associate the extension with a an language with the `files.associations` setting.

Closing the issue as the support would have to come from an extension.

**Comment by meteoros** [comment]
Thanks for you help...i can see extensions to work with .tpl files, what i want is when i open a .tpl file (i lose the html highlight) and i'm working on it a want VSC to highlight the html code that i'm writing on a .tpl file...
