### ISSUE TITLE
Missing images in Marketplace

### ISSUE THREAD

**Issue by b3nk3** [microsoft/vscode#118519]
Issue Type: <b>Bug</b>

I have noticed, that a fair amount of images are broken on the extension.

I have traced this to the fact, tha "master" is hardcoded into the template displaying the Readme in VS Code/Marketplace website however many people have swapped over to GitHub's default "Main" branch.

Would you be able to fix this?

Marketplace links to this: https://raw.githubusercontent.com/b3nk3/hotline-vice-vscode-theme/master/media/banner.png

Correct link: https://raw.githubusercontent.com/b3nk3/hotline-vice-vscode-theme/main/media/banner.png

VS Code version: Code 1.54.1 (Universal) (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 05f450e1-1c1a-439b-beca-8442cae83eb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.16
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
vscode-firefox-debug|fir|2.9.2
vscode-pull-request-github|Git|0.24.0
vscode-graphql|Gra|0.3.15
vscode-cfn-lint|kdd|0.16.1
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.163.1
debugger-for-chrome|msj|4.12.12
vscode-yaml|red|0.16.0
synthwave-vscode|Rob|0.1.8
serverless-ide-vscode|Thr|0.5.30
vscodeintellicode|Vis|1.2.11

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
vspre833:30267464

```

</details>

**Comment by b3nk3** [comment]
Hi @joaomoreno, indeed it seems you have. However having installed from NPM, it still uses master. 

I went to dig a bit deeper, and ended up downloading the zip file from: https://github.com/microsoft/vscode-vsce/releases/tag/v1.85.1 which, in the package.ts has `master` still...

I'm a bit puzzled as to why. Could there be a gremlin in your CI pipeline?

**Comment by joaomoreno** [comment]
You're absolutely right: I forgot to actually release something. 1.86.0 is currently being baked, will be release in a couple minutes.

**Comment by b3nk3** [comment]
Happens to all of us, haha 😉. Thanks for your speedy responses
