### ISSUE TITLE
Provide the code hint for css(include inline css) & javascript in HTML files plz...

### ISSUE THREAD

**Issue by hyingreborn** [Microsoft/vscode#11857]
- VSCode Version: 1.5.1
- OS Version: win10

Example：
----------------------------
```
<style type="text/css">
.myClass { ... }
</style>
```
----------------------------
`<div style="color: #fff; ...">inline css</div>`
----------------------------
```
<script type="text/javascript">
console.log('my log');
</script>
```

**Comment by sander76** [comment]
Was about to open an issue, but this is about the same thing I am experiencing (?)

css code inside a `style` tag inside an html file has no intellisense suggestions.... Am I right ?

**Comment by hyingreborn** [comment]
Sometimes I need to write CSS and JS in HTML, but no intellisense, coding efficiency is very low

**Comment by aeschli** [comment]
duplicate of #8928
