### ISSUE TITLE
Add optional timeout to MessageBox (Information, Error, Warning)

### ISSUE THREAD

**Issue by Jakobud** [Microsoft/vscode#11858]
Just simply an optional timeout in milliseconds that can be specified to make a messagebox dismiss itself after that amount of time.

Alternatively provide a way of dismissing message boxes manually so that one might do this with `setTimeout`.

**Comment by jrieken** [comment]
closing as duplicate of #12615 which has already a little more context. Long story short is that the info/warn/error messages are so intrusive a user should acknowledge them. So less disruptive messages the status bar should be used
