### ISSUE TITLE
TERMINAL ISSUE

### ISSUE THREAD

**Issue by zaladigvijay** [microsoft/vscode#118520]
Issue Type: <b>Bug</b>

The connection to the terminal's pty host process is unresponsive, the terminals may stop working.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.11GB free)|
|Process Argv|--crash-reporter-id cd0e8107-b72c-4b52-8c79-689cce76a61e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-align|bla|0.0.13
simple-react-snippets|bur|1.2.3
node-snippets|chr|1.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.14
es7-react-js-snippets|dsz|3.1.0
vscode-npm-script|eg2|0.3.16
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
search-node-modules|jas|1.3.0
vscode-exec-node|mir|0.5.3
tscompileonsave|mom|0.2.1
typescript-auto-compiler|mor|0.7.0
remote-wsl|ms-|0.54.2
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
react-redux-es6-snippets|tim|2.1.0
vscodeintellicode|Vis|1.2.11
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
vspre833:30267464

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
