### ISSUE TITLE
Mini map scrolling faster with scrolling middle mouse button

### ISSUE THREAD

**Issue by junkes** [microsoft/vscode#118538]
Mini map scrolling faster with scrolling middle mouse button.
Thank you.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including version and platform.

Hint - start your future issue reports from Report Issue off the Help menu.

**Comment by junkes** [comment]
The middle mouse button over the minimap takes the same time that scrolling the code page.
Please change the scroll button in the middle of the mouse over the minimap to scroll faster than the code page. Times faster.

**Comment by junkes** [comment]
Issue Type: Feature Request

The middle mouse button over the minimap takes the same time that scrolling the code page.
Please change the scroll button in the middle of the mouse over the minimap to scroll faster than the code page. Times faster.

VS Code version: Code 1.54.1 (f30a9b7, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic snap
