### ISSUE TITLE
SCSS to CSS Addons are all crashing: "Extension host terminated unexpectedly."

### ISSUE THREAD

**Issue by Fantasterei** [microsoft/vscode#118527]
After Visual Studio Code updated itself to Version 1.54.1 (Universal) on my Mac (BigSur 11.2.1) my old Scss2Css (https://marketplace.visualstudio.com/items?itemName=cyyvs.Scss2Css) addon stopped working by the error message:
"Extension host terminated unexpectedly."

I tried to install several other plugins, even Live Sass Compiler which was downloaded over a million times. I tried to disable any other plugin and run one of those Converters, also a downgrade of my VS Code to the older version, I was using before, and even using the VS Code Insiders Version. Nothing helps.

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Diagnosing and fixing issues that cause the Extension Host to crash usually needs the involvement of extension authors. Please start by reporting it to them.
