### ISSUE TITLE
Embedded language support in Markdown

### ISSUE THREAD

**Issue by vstirbu** [Microsoft/vscode#11851]
I'm developing an [extension](https://github.com/vstirbu/vscode-mermaid-preview) that enables preview of [mermaid diagrams](http://knsv.github.io/mermaid/) inside Visual Studio Code.

My workflow assumes that the mermaid diagrams are embedded as github fenced code blocks inside Markdown documents:

<pre>
# Markdown document

next is a mermaid sequence diagram...

```mermaid
%% Example of sequence diagram
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```
</pre>

I would like to provide a `mermaid` language extension for the content inside the fenced block but the extension sees the document as `markdown`. The extension docs are not that useful for this situation.

What is the proper way to handle the embedded language with an extension?

**Comment by mjbvz** [comment]
With #22916, we are exploring allowing the markdown preview to be extended. I've created a prototype markdown preview extension that adds support for rendering mermaid diagrams: https://github.com/mjbvz/vscode-markdown-mermaid

The other part of this would be syntax highlighting of the mermaid fenced code block itself in the editor. This is possible using a grammar injection. I've created another example extension that shows how this can be achieved: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example This one requires the next VSCode insiders build

Please let me know if you have any questions about these examples or interested in leveraging the new markdown extension API
