### ISSUE TITLE
Workspace file with no folders listed results in vscode.workspace.workspaceFolders = [ ] 

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#118566]
Version: 1.55.0-insider (user setup)
Commit: 04770364fdc1bebeca9d1a257df2cacce06b35d6
Date: 2021-03-05T15:40:03.281Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
1. Create a workspace file
2. Make the contents of the file `{ "folders": [ ] }`
3. Go to VS Code -> Open Workspace -> open the workspace file
4. Make a test extension to run the command `vscode.workspace.workspaceFolders`

Expected:
According to the docs, if no folder is open this will return `undefined`: 
![image](https://user-images.githubusercontent.com/22576531/110514391-1afe1c00-80bc-11eb-9e83-7d8e71d31916.png)

Actual:
VS Code returns an empty array.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Good point, I updated the JSDoc: https://github.com/microsoft/vscode/commit/a19fac2442cd372a79cb799ed3635ac808b0a7c4
