### ISSUE TITLE
"N unsaved" editor badge appears when there are none unsaved (e.g. no open editors)

### ISSUE THREAD

**Issue by mnoorenberghe** [microsoft/vscode#118556]
Issue Type: <b>Bug</b>

"1 unsaved" editor badge is shown even though I have no open editors.

I believe this is caused by a git-rebase-todo file from using vscode for git interactive rebases but this seems like a bug in vscode itself since it should never show unsaved editors if there are no editors open.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|-psn_0_94231 --crash-reporter-id f823149d-6b95-4d49-a476-ada041992a90|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.14
gitlens|eam|11.2.1
vscode-npm-script|eg2|0.3.16
vscode-firefox-debug|fir|2.9.2
vscode-docker|ms-|1.10.0
vscode-postgresql|ms-|0.3.0
remote-containers|ms-|0.158.0
vscode-typescript-tslint-plugin|ms-|1.3.3
rewrap|stk|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by mnoorenberghe** [comment]
Note that "Close All Editors" or "Save All" do not remove the "N unsaved" badge. The only way to remove it is to close the window.

**Comment by bpasero** [comment]
Would be great if you can distill accurate one by one step by step instructions for how to reproduce.

**Comment by mnoorenberghe** [comment]
Sorry, I think the problem is with the GitLens extension. It's somewhat related to https://github.com/eamodio/vscode-gitlens/issues/1387
