### ISSUE TITLE
Wrap and/or add a scroller for debugger variables/watches

### ISSUE THREAD

**Issue by chrissyast** [microsoft/vscode#118579]
Even with the debug panel extended as far as possible, I can't read the whole of this message. Copying the value and pasting it into another editor is tiresome.
![image](https://user-images.githubusercontent.com/31564153/110543856-bfb34480-8122-11eb-8d31-cdce22afaf00.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
