### ISSUE TITLE
Strange behavior of files.exclude in workspace with nested folders

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode#118557]
**Related Issues**:
#116418 
#114869
#114447
#102147
#98205
#96782
#95056
#45470
#45399

- **VS Code Version**: 1.54.1
- **OS Version**: Linux x64 5.8.0-44-generic

**Steps to Reproduce**:

1. Create a root folder (**files-exclude-sample**)
2. Inside that folder create two nested folders (**child1**, **child2**)
3. In root folder (**files-exclude-sample**), create a workspace definition file (**files-exclude-sample.code-workspace**)
```json
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "child1"
    },
    {
      "path": "child2"
    }
  ]
}
```
4. In root folder (**files-exclude-sample**), create a **.vscode** folder
5. Inside **.vscode** folder create a **settings.json** file
```json
{
  // Configure glob patterns for excluding files and folders.
  "files.exclude": {
    "child1": true,
    "child2": true
  }
}
```
6. Alternatively to previous steps, just clone this GitHub repo: https://github.com/rubensa/files-exclude-sample
7. In VSCode, open the workspace (**files-exclude-sample.code-workspace**)
8. Everything looks ok.  You have tree root folders (**files-exclude-sample**, **child1** and **child2**)
![Screenshot from 2021-03-09 17-03-02](https://user-images.githubusercontent.com/1469340/110500302-5a972900-80f9-11eb-83ad-11909233be05.png)
9. If you expand all three folder you can see something like
![Screenshot from 2021-03-09 17-03-45](https://user-images.githubusercontent.com/1469340/110500363-6b479f00-80f9-11eb-8cd8-afd255d5c984.png)
10. As specified in root folder **.vscode/settings.json**, **child1** and **child2** are excluded
11. Open **file.txt** from **child1** folder
12. **child1** folder is collapsed (not removed from explorer tree) and it appears inside root folder (**files-exclude-sample**) folder
![Screenshot from 2021-03-09 17-04-07](https://user-images.githubusercontent.com/1469340/110500430-7ac6e800-80f9-11eb-9e92-0347c851bf3f.png)
13. The expected behavior is that **child1** is not collapsed and it does not appear inside root folder

**Does this issue occur when all extensions are disabled?**: Yes

**Comment by bpasero** [comment]
@TylerLeonhardt the owner of the file explorer is @isidorn

**Comment by isidorn** [comment]
I acknowledge this issue. MR workspace support with when one root folder is a subfolder of another root folder has some issues.
If somebody is passionate about fixing this let me know and I can provide pointers

**Comment by jeanp413** [comment]
Created #118777 fixing this

**Comment by isidorn** [comment]
Thanks to a great pr by @jeanp413 this is now fixed ☀️
