### ISSUE TITLE
.ts and .d.ts files sharing the same filename interfere with each other

### ISSUE THREAD

**Issue by DCoderLT** [Microsoft/vscode#1185]
I have an in-house library written in TypeScript. It consists of two files: `promises.ts` and a `promises.d.ts` exposing related interfaces globally. The TypeScript compiler has no problem with this setup, and neither does IntelliJ, but VSCode seems to only "be aware" of the `promises.d.ts` content while I have it open as the active file. As soon as I close it or switch to another file, the interfaces declared in `promises.d.ts` get flagged as unknown.
I have seen this on two different computers running VSCode. Both VSCode installations are currenty up to date. It also happens with other libraries using the same naming pattern.
We are not using TypeScript's "generate declaration files" setting.

**Comment by dbaeumer** [comment]
@DCoderLT can you provide a small test case showing the behavior. The interesting question is how your tsconfig.json file looks like which the tsserver is relying on.

**Comment by DCoderLT** [comment]
Here's a minimal test case with a trivial interface and implementation: https://gist.github.com/DCoderLT/8a6df3fdddf8d3484900 .

After some debugging, it seems I missed a key detail earlier, and VS Code is probably doing the right thing - the TypeScript compiler did not have a problem with my setup because I was invoking it via gulp and giving it a file list that included both the .ts and the .d.ts files. Running plain `tsc -p .` produces the exact same behaviour as VSCode.
If I amend the `tsconfig.json` in the test case to explicitly include both .ts and .d.ts under `"files"`, both VSCode and `tsc -p .` recognize the interface just fine.
If I rename the .d.ts file, again both VSCode and `tsc -p .` recognize the interface just fine.

Given this info, it looks like `tsc` treats such paired .d.ts files as the output from an earlier "generate declaration files" run and ignores them when collecting the files for compilation. IntelliJ's parser treats them like regular files. When I think about it, tsc/VS Code's behaviour is quite reasonable, although not completely intuitive.

I think I will remove those interfaces from the global scope and export them from the module, so the `.d.ts` file won't be necessary any longer.

**Comment by egamma** [comment]
@DCoderLT ok to close?

**Comment by DCoderLT** [comment]
Yes, I think this can be closed.

**Comment by egamma** [comment]
@DCoderLT thanks, closing.

**Comment by dbaeumer** [comment]
Setting verified label. Close approved by creator.
