### ISSUE TITLE
Slow workspace loading with 100+ root folders.

### ISSUE THREAD

**Issue by s-jeckel-mxn** [microsoft/vscode#118533]
Issue Type: <b>Bug</b>

I've set up a generated .code-workspace file for a modular project with about 300 root folders, one per module.
The issue is that VSCode is very slow to load this project and displays
"Setting up workspace: Loading packages..."
for several minutes. Also fetching the tasks is quite slow. Basically every operation that potentially scans all root folders takes a long time.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3175X CPU @ 3.10GHz (56 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|94.67GB (78.83GB free)|
|Process Argv|D:\\Perforce\\s_jeckel_MXDEWIN1072_2\\dev\\cinema\\buildserver2\\buildserver2.code-workspace --crash-reporter-id f36a6036-1228-4ea1-a97c-82e556a009ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-bazel|Baz|0.4.0
go|gol|0.23.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.633441544
jupyter|ms-|2021.3.619093157
cpptools|ms-|1.2.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
java|red|0.76.0
perforce|sle|3.2.0
vscode-lldb|vad|1.6.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.27.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by s-jeckel-mxn** [comment]
I did the same without extensions disabled as you instructed, and the behavior is the same.

**Comment by bpasero** [comment]
@s-jeckel-mxn but it seems to me that `Setting up workspace` message is coming from an extension, are you still seeing that? And you say tasks are slow specifically?
