### ISSUE TITLE
Default sidebar width should not trigger narrow mode for extensionsViewlet

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#118511]
The default sidebar width is dynamically calculated but ends up being 251px for most window sizes I tested. The `narrow` mode for the `extensionsViewlet` is triggered for ⪬ 300px.

<img width=200 src="https://user-images.githubusercontent.com/8599/110428517-3afef280-805e-11eb-8175-dcbe1d1db283.png">

<img width=200 src="https://user-images.githubusercontent.com/8599/110428620-6aadfa80-805e-11eb-9c23-fa4e2651750d.png">

While `narrow` is great for small spaces, it hides key information like the icon, rating and download numbers. For users who don't discover the resizing, important context is lost for extensions. I noticed this during my work on getting started, as it guides users early into the extension panel; which looks no very inviting without expanded.

Ideas for solutions

- Trigger narrow for ⪬ 250px
- Add a size before narrow that allows more context like a smaller extension icon and simpler rating, or other redesign ideas.

Tooltips on descriptions to read cut off text.

<img width=200 src="https://user-images.githubusercontent.com/8599/110429461-da70b500-805f-11eb-99e6-f9bcf49c90ef.png">

cc @sana-ajani @misolori @fiveisprime

**Comment by sana-ajani** [comment]
Good observation! Strongly agree that that showing icons, the starred recommended ones, and download count would provide a richer view and catch new users' eyes.

**Comment by misolori** [comment]
I think your proposal is to change the default width of the sidebar (not just for the extensions view). I can't remember if @sbatten or @isidorn owns the sidebar?

**Comment by isidorn** [comment]
Please note that the SideBar probably takes the "optimal" width of the explorer since that is the initial view shown.
When we change the active view in the sidebar the sidebar does not change size. Not sure if that would be strange.

Anyways leaving this up to @sbatten to decide

**Comment by digitarald** [comment]
> I think your proposal is to change the default width of the sidebar (not just for the extensions view).

I am leaning towards the lower hanging proposal to change the min-width for narrow. For changing the default sidebar width I'd have to dig deeper into seen window sizes. I am also not aware that other panels have problems with narrow width; which would otherwise strengthen the case. The middle-ground would be increasing sidebar default width a bit and making the narrow min-width a bit wider.

**Comment by sbatten** [comment]
@sandy081 for the narrow breakpoint in extensions viewlet

**Comment by misolori** [comment]
Ah, ok I see what you mean now. That makes sense to me as well, this is handled here:

https://github.com/microsoft/vscode/blob/17c67963f3245c7e6c753ac4a223a2e5f07b61f0/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts#L564-L572

**Comment by digitarald** [comment]
And the initial default width comes from https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/views/viewPaneContainer.ts#L708-L721

**Comment by sandy081** [comment]
It seems showing icon, title, version, rating & downloads in 250 px is too clumsy - title and version are shown partially with ellipsis. 

What do you think not showing `version` instead of `rating` & `downloads` in narrow version?

**Comment by misolori** [comment]
@sandy081 I think when you are installing an extension for the first time you are less concerned about the version so that sounds good to me. Screenshot?

**Comment by digitarald** [comment]
Download numbers seem the best indicator (and are also used in _Popular_), as ratings can mislead.

If the entries use a grid layout, it could shift the icon from top-row to the left:

![image](https://user-images.githubusercontent.com/8599/110831458-1b7aec00-824f-11eb-93ac-105819820007.png)

**Comment by sandy081** [comment]
Improved the viewlet representation when the width is small. It also has other improvements which are part of #126479. Feedback is appreciated


https://user-images.githubusercontent.com/10746682/125800803-8c9d5785-9d0f-4057-818d-8a84f9c2560c.mp4
