### ISSUE TITLE
black screen in windows 10

### ISSUE THREAD

**Issue by ahmed-gtr** [microsoft/vscode#118553]
Issue Type: <b>Bug</b>

when i open it black screen appears , i tried cmd method code--disable-gpu
and also from properties --disable gpu method its not working what should i do?. i created one more user and also at the starting  its also not showing later it opened in new user acnt.  

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by ahmed-gtr** [comment]
[image: Screenshot 2021-03-10 091225.jpg]

**Comment by TylerLeonhardt** [comment]
Unfortunately, you can't upload files from email...can you attach on the website?
