### ISSUE TITLE
integrated Terminal setting fallback

### ISSUE THREAD

**Issue by AleksanderEvensen** [microsoft/vscode#118551]
When using settings sync between my devices, I don't always have the same terminal or path to terminal on all my devices. I would like to have a feature where the "terminal.integrated.shell.<os>" setting could be an array of paths, where visual studio would check the paths one by one to see if they're valid, if not use the default shell of the OS.

![image](https://user-images.githubusercontent.com/19311856/110495104-79df8780-80f4-11eb-832c-3ecbbba0662e.png)

**Comment by meganrogge** [comment]
we're actually working on this right now https://github.com/microsoft/vscode/issues/45444
