### ISSUE TITLE
Terminal link hover shows up in the wrong spot in web

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118587]
https://user-images.githubusercontent.com/323878/110554687-24a17700-80f0-11eb-943a-09f71c5fa1fb.mp4

When I hover the link with the cursor, the hover widget pops up under my cursor. Seems like it's off by a line, because it highlights the line below. Works fine on desktop

**Comment by meganrogge** [comment]
Do you know if this is a recent change?

**Comment by meganrogge** [comment]
does not happen for me when running web locally or in WSL. only codespaces

**Comment by roblourens** [comment]
I don't know if it's recent. Just noticed it today randomly

**Comment by Tyriar** [comment]
I used to see this occasionally but haven't in months, guessing it's fixed.
