### ISSUE TITLE
Cannot disable linting

### ISSUE THREAD

**Issue by tristanbrown** [microsoft/vscode#118507]
Issue Type: <b>Bug</b>

In the Settings, disable Pylint. Then type in the editor. The red wavy lines still show up while typing. 

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.20GB free)|
|Process Argv|--crash-reporter-id 558879d9-4e0c-47d8-9bc1-f42e3423ea06|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: turf|
|OS|Windows_NT x64 10.0.19041|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|31.93GB (17.17GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.633441544
jupyter|ms-|2021.3.619093157
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by roblourens** [comment]
Please file this issue on the extension you are using/trying to disable
