### ISSUE TITLE
Math not rendered in Jupyter Notebooks

### ISSUE THREAD

**Issue by pietrodantuono** [microsoft/vscode#118561]
- VS Code Version: 1.55.0-insider
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Ctrl + Shift + P
2. Jupyter: Create New Blank Notebook
3. Add a Markdown cell
3. Type in some math (e.g. $x^2$ or \[ x^2 \], etc)
4. Ctrl + Alt + Enter

Does this issue occur when all extensions are disabled?: Yes (obviously, python extension needs to be enabled)

![image](https://user-images.githubusercontent.com/17992358/110507404-46a2f580-8100-11eb-8bf2-32a9855e7fa5.png)

P.S. The issue happened since Version 1.53.0-insider

EDIT:

adding the following to settings.json partially solves the issue (thanks to [#106701](https://github.com/microsoft/vscode/issues/106701)):
`"notebook.experimental.useMarkdownRenderer": true`

In fact now the dollars math syntax seems working 
![image](https://user-images.githubusercontent.com/17992358/110508567-6be43380-8101-11eb-8e44-f272a05e6d05.png)

**Comment by IllusionMH** [comment]
I think this is duplicate of #118262 and work is in progress there
