### ISSUE TITLE
Enable c# object dump in debugger console from code

### ISSUE THREAD

**Issue by ghisguth** [Microsoft/vscode#11854]
- VSCode Version: 1.5
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Install c# extension
2. Create .net core application
3. Write complex object to console
  1. `Console.WriteLine(new Dictionary<string, string>{{"foo", "bar"}});`
  2. `Debug.WriteLine(new Dictionary<string, string>{{"foo", "bar"}});`
  3.  `Console.WriteLine(Newtonsoft.Json.JsonConvert.SerializeObject(new Dictionary<string, string>{{"foo", "bar"}}));`
4. Run program
5. Inspect debugger console

Result:

1. Debugger console contains string representation of the object:  
   
    System.Collections.Generic.Dictionary`2[System.String,System.String]

    or

    {"foo":"bar"}

Expected result:

1. Debugger console contains object which can be interacted with. Same as if `new Dictionary<string, string>{{"foo", "bar"}}` would be executed in debugger console:
    
    Count = 1
    [0] [KeyValuePair]:{[foo, bar]}
    Raw View

Notes:

LinqPad has extension method called Dump. It allows to render complex objects in form of tables. It would be great to have something similar in vs code. Yes, I can put breakpoint and manually dump object. But I want to be able to do that from code. So I can re-run program and instantly see complex object in debugger log. Don't really care what would be the method to dump objects.

**Comment by bpasero** [comment]
@isidorn not sure if this should be reported to C# extension repository.

**Comment by isidorn** [comment]
@ghisguth please report this issue to the c# extension here https://github.com/OmniSharp/omnisharp-vscode

The C# extension would need to return an object with a reference > 0 when the user evaluates an expression like this. Then vscode will display that the object can be expanded and on expansion ask for children from the debug adapter for the given reference.

**Comment by ghisguth** [comment]
Thank you. Reported here: https://github.com/OmniSharp/omnisharp-vscode/issues/763
