### ISSUE TITLE
VS Code doesn't lauch on Windows with no error or any message

### ISSUE THREAD

**Issue by escamoteur** [microsoft/vscode#118525]
- VS Code Version: 1.54.1 32 Bit
- OS Version: Windows 10 Home 

Steps to Reproduce:
I installed VS code 32 Bit System installer (I also tried the user installer) on a small notebook with 2GB RAM and an Intel Atom processor which I want to donate to a CS student in Africa.

When trying to start it either over the start menu or on the console nothing happens at all. No Error Message, just nothing. Also in the Task Manager no process appears or you can see that more memory is used. I'm honestly stunned and have no idea what to to. I really wanted to preinstall VS Code for her so that she don't have to make a bid download over a bad internet connection.

As I use Code on several computers with different OSes so far without any problem I'm really surprised.

Does this issue occur when all extensions are disabled?: Yes/No
Yes, I also tried with --verbose, nothing happens, no message

**Comment by deepak1556** [comment]
It is very likely runtime was unable to allocate sufficient virtual memory, closing as not actionable.
