### ISSUE TITLE
Confusing error message about workspaceFolder

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118590]
![image](https://user-images.githubusercontent.com/323878/110561735-1148d880-80fd-11eb-944a-80bd9fb6acd3.png)

- Have a workspace with one folder, and a launch config in the code-workspace that uses `${workspaceFolder}`
- Add a second folder
- Now I get this error message that tells me to open a folder
- Really I need to use the `${workspaceFolder:vscode}` syntax

**Comment by roblourens** [comment]
Now the behavior of this is that the variable resolves to whatever the first workspace folder is, that seems wrong

**Comment by alexr00** [comment]
We can't wait for user interacting to choose a folder for this. We could show some other error and fail variable resolving instead of choosing the first folder.

**Comment by alexr00** [comment]
Error has been improved with https://github.com/microsoft/vscode/pull/157788
