### ISSUE TITLE
Search: Replace, match previous case

### ISSUE THREAD

**Issue by helzgate** [microsoft/vscode#11853]
While doing a search and replace:  If I don't have match case selected, could the find and replace, replace the appropriate words based on their previous case?

example:  I have several references to "HomeComponent", "HomeService", "homeService", "homeModel", "homeRef", etc.

If I want to change the word "Home" to "Portal", why can't I just add the word "portal" in the replace input and it automatically change all the above to:
"PortalComponent", "PortalService", "portalService", "portalModel", "portalRef", etc ???

Nobody should complain about this new functionality because you clearly don't care about case when you have "Match Case" unselected!

**Comment by sandy081** [comment]
This is a good feature to have but I think this would change the existing behavior while replacing `matchCase` is disabled. Its true that when you do not select `matchCase` you do not care case while searching, but it won't be expected if you do not replace the word with what is provided. I would rather wait to see if we get more feedback for this request before we implement. Also, we have to consider what should be done with change in existing behavior if gets complained.

Thanks

**Comment by helzgate** [comment]
@sandy081 Yeah, i realize this request is a bit of a long-shot, lol.  Oh well, thx anyway!

**Comment by wolfgangmeyers** [comment]
@sandy081 I think that if matchCase option is off by default, there shouldn't be any change to the existing behavior.

**Comment by bmjsmith** [comment]
IntelliJ does this well.  There's a separate switch called Preserve Case in the replace line.  That would be ideal.

**Comment by BillDenton** [comment]
Any updates on preserving case during replace?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/9798
