### ISSUE TITLE
minmax showing up as an error

### ISSUE THREAD

**Issue by hditano** [microsoft/vscode#118598]
Issue Type: <b>Bug</b>

minmax CSS function is showing up as an error even tho still works perfectly.

![image](https://user-images.githubusercontent.com/6069906/110580257-06b33100-8147-11eb-85e5-e1b2a1ec6f98.png)

VS Code version: Code 1.54.0 (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-03T02:17:36.640Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.40GB free)|
|Process Argv|--crash-reporter-id d3220fa1-fb0c-4736-a6e6-552dd13cc3d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.5.9
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.16
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.16
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
gc-excelviewer|Gra|3.0.41
unity-code-snippets|kle|1.3.0
rainbow-csv|mec|1.8.1
csharp|ms-|1.23.9
vetur|oct|0.33.1
LiveServer|rit|5.6.1
markdown-preview-enhanced|shd|0.5.16
swdc-100-days-of-code|sof|1.0.22
swdc-vscode|sof|2.5.3
code-spell-checker|str|1.10.2
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
vscodeintellicode|Vis|1.2.11
vscode-wakatime|Wak|5.0.1
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by aeschli** [comment]
I'm not able to reproduce:
```
.foo {
    grid-template-columns: repeat(auto-fill, minmax(100px, 800px));
    
}
```
Does it reproduce with extensions disabled?
What is the error exactly saying?
