### ISSUE TITLE
Onboard me to ownership of our quick picker code

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#118586]
This means several things:

* The actual quick pick widget (currently owned by @bpasero)
* The quick pick API (currently owned by @chrmarti)
* Cmd+P file search (currently owned by @roblourens)

I will work with each of these individuals to become more familiar with those parts... potentially work on any bugs/small features to get acclimated... and then update any ownership docs/bots to reflect the change.

**Comment by TylerLeonhardt** [comment]
This will probably span multiple milestones.

**Comment by bpasero** [comment]
@TylerLeonhardt fyi the quick pick widget is owned by @chrmarti . I am the author of the related quick access providers:

https://github.com/microsoft/vscode/blob/50d9f05334aee7bbc416f675cceccd9a174de8c7/src/vs/platform/quickinput/common/quickAccess.ts#L158-L158

E.g. the actual pickers for things like file search, symbol search, etc. Anything that can be found here:

![image](https://user-images.githubusercontent.com/900690/110583153-894ee700-816d-11eb-99be-85e1747b0f44.png)

**Comment by TylerLeonhardt** [comment]
This will be closed in May 😄

**Comment by TylerLeonhardt** [comment]
I guess I can be called the owner :)
