### ISSUE TITLE
Add angle brackets to `surroundingPairs` in Rust `language-configuration.json`

### ISSUE THREAD

**Issue by duongdominhchau** [microsoft/vscode#118521]
## Feature description
Typing `<` wraps the selection into `<>` pair. This is useful when I want to write the turbofish or wrap the type inside `Result`/`Option`.

**Comment by alexdima** [comment]
We usually avoid defining a pair for `<>` because of the ambiguity when using the `<` comparator, e.g. when typing code like `a < 3` it might result in `a < 3>`.

**Comment by duongdominhchau** [comment]
Hi, my suggestion is about [surroundingPairs](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#autosurrounding) which only applies when there is at least one non-whitespace character selected. If the ` 3` is not selected before typing `<`, the final result should still be `a < 3`. This behavior is already provided by `rust-analyzer`, but it is too heavy when the project is large and all I need is reading a single source file and possibly making some trivial changes.

**Comment by alexdima** [comment]
To verify, open a rust file, make a selection and type `<`. The selection should be surrounded with `<>`.
