### ISSUE TITLE
VS Code 1.54.x fails to redraw window contents after switching between virtual desktops in i3 window manager

### ISSUE THREAD

**Issue by zambal** [microsoft/vscode#118549]
- VS Code Version: 1.54.1
- OS Version: Ubuntu 20.04.1 LTS with i3 window manager
- Hardware: Lenovo Thinkpad T480, using Intel integrated GPU.

This issue seems to occur only when using the i3 window manager. Other than using i3, my Ubuntu install is pretty standard. I just upgraded totday from 1.52.1 to 1.54.1, so this issue may have been introduced before 1.54.1.

Steps to Reproduce:

1. Open a vscode instance
2. Open a new window in vscode (Ctrl + x Ctrl + n)
3. Navigate to another virtual desktop in i3
4. Navigate back to the virtual desktop with the two vscode windows.
5. If the issue occurs, you should see the contents of the previous virtual desktop, instead of the contents of the vs code windows.

As a workaround, you can switch the i3 container layout to stacked or tabbed and back again to force a redraw.

This is how it looks on my desktop:

![Screenshot from 2021-03-09 15-28-15](https://user-images.githubusercontent.com/158447/110490896-0720dd00-80f1-11eb-81e3-bb806f82f39e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Does launching with `--disable-gpu` help ?

**Comment by zambal** [comment]
I see this is labeled as upstream, so I assume it'll take a while before this is tackled. Could someone give a broad estimate when this is addressed (days, weeks, or maybe even months)?

**Comment by Spikatrix** [comment]
`--disable-gpu` does fix the issue for me

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.74` on Ubuntu 22.04
