### ISSUE TITLE
Issue reported submit button is missing

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#118575]
- VS Code Version: 1.54.1
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Open the Issue Reporter

Does this issue occur when all extensions are disabled?: Yes

----

Screenshot is pretty self-explanatory:

![image](https://user-images.githubusercontent.com/376842/110534990-993bdc00-8117-11eb-8400-03a12d9720c9.png)

Where's the submit button? It seems to have had its height set very small but I can't click it.

**Comment by nourhj99** [comment]
Hello, I am new to this community.
I want to help with this issue.
Can you please help me begin? Which files should I look at? Thank you in advance.

**Comment by RMacfarlane** [comment]
Hi @nourhj99! I haven't been able to reproduce this issue, but I have a suspicion about what is going on. I would be happy to take a PR for this.

You can find the code for this in `src/vs/code/electron-sandbox/issue/issueReporterMain.ts`. There's a function there called `updatePreviewButtonState` that sets the text of this button. I think a call to this was accidentally removed from the issue reporter constructor, so it's only set after all data is received.

**Comment by alexr00** [comment]
verified by code review

**Comment by isidorn** [comment]
Adding verified label based on Alex's code review 😊
