### ISSUE TITLE
Native Notebooks - Hover function signature/docstring moving on scroll

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#118582]
Steps to Reproduce:

1. Get hover function signature/docstring to come up using autocomplete
2. Move mouse away and into context of notebook
3. Scroll down 

Actual Behavior:
1. As you scroll, the autocomplete list and function signature/docstring move away from the code it was generated from. 
2. If you scroll far enough down such that the code is out of frame, the information disappears. Scrolling back up does not bring it back 

Expected Behavior:
1. As you scroll, the autocomplete list and function signature/docstring stay attached to the code it was generated from. 
2. If you scroll far enough down such that the code is out of frame, the information disappears but if you scroll back up it comes back into view. (Like it behaves for a regular python file) 

![Docstring Hover ](https://user-images.githubusercontent.com/19276747/110551929-4d733d80-80eb-11eb-8a41-9e2eece65d6f.gif)

**Comment by rebornix** [comment]
We have attempts before to fix this issue but turned this off. We can revisit.

**Comment by rebornix** [comment]
Fixed in main.
