### ISSUE TITLE
SFDX:Deploy Source In Menifest to Org is Not Working But It Show Exit Code 0

### ISSUE THREAD

**Issue by VidishSharma1** [microsoft/vscode#118517]
I am trying to push the metadata of package.xml, when I click on the SFDX:Deploy Source In Menifest to Org than it ends with 14:02:09.161 sfdx force:source:deploy --manifest d:\ss org Backup 21012021\manifest\package.xml --json --loglevel fatal
14:03:13.175 sfdx force:source:deploy --manifest d:\ss org Backup 21012021\manifest\package.xml --json --loglevel fatal
 ended with exit code 0 

But i am not able to see any deployment process in destination salesforce org in the Deployment Status Section. 2 Out Of 100 times it works but for 98 times it don't. Kindly help to Fix this issue. It is really Urgent.

Thanks,
Vidish
![Screenshot (527)](https://user-images.githubusercontent.com/36029210/110442814-3b8c9d00-80e1-11eb-87b9-bc58cfa64643.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report to the SFDX extension author
