### ISSUE TITLE
postDebugTask not found in MR workspace

### ISSUE THREAD

**Issue by movl03** [microsoft/vscode#118528]
Issue Type: <b>Bug</b>

In my code-workspace file I have two tasks (task A and task B) and a launch configuration defined. All of them are designed to run in the same workspace folder. 
The launch configuration uses task A as a preLaunchTask and task B as a postDebugTask. I get the error that "Task 'B' can not be referenced from a launch configuration that is in a different workspace folder".

It works if I create a {$workspaceFodler}/.vscode/tasks.json and {$workspaceFodler}/.vscode/launch.json with the exact same tasks and launch configurations.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.6.13-100.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.63GB (1.66GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id b6573aea-31f0-4c41-811a-3490a0f0ae84|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
latex-workshop|Jam|8.16.1
python|ms-|2021.2.633441544
jupyter|ms-|2021.2.603412351
remote-containers|ms-|0.158.0
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
java|red|0.76.0
command-variable|rio|1.13.0
vscode-coverage-gutters|rya|2.7.2
errorlens|use|3.2.4
vscode-java-debug|vsc|0.31.0
vscode-java-dependency|vsc|0.18.1
vscode-java-test|vsc|0.28.1
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by isidorn** [comment]
Interesting. We do the same thing for the `preLaunchTask` and the `postDebugTask`, so those things should not differ.
However the issue you are hitting for task B, you could also hit if you set that task as the `preLaunchTask`. We currently do not allow to reference tasks from different workspaces.
This is a current limitation, thus we can keep this request open as a way to lift this limitation. Though we have no plans to tackle right now, so assigning to backlog.

**Comment by mmarczell-graphisoft** [comment]
I hit this problem with the following minimal example:

```
{
	"folders": [
		{
			"path": "."
		}
	],
	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "Foo",
				"type": "shell",
				"command": "echo Foo"
			},
			{
				"label": "Bar",
				"type": "shell",
				"command": "echo Bar"
			}
		]
	},
	"launch": {
		"configurations": [
			{
				"type": "chrome",
				"request": "launch",
				"name": "Debug in Chrome",
				"url": "http://localhost",
				"preLaunchTask": "Foo",
				"postDebugTask": "Bar"
			}
		]
	}
}
```
As you can see there is zero difference between the tasks themselves.
I believe this means this is not a feature request, but a bug, since the preLaunchTask runs successfully.
Could this be reopened and fixed?
