### ISSUE TITLE
Update electron to a supported version

### ISSUE THREAD

**Issue by user414** [microsoft/vscode#118532]
The Electron project is closing issues that were sent upstream because V 8.x is no longer supported

https://www.electronjs.org/docs/tutorial/support#supported-versions

Upgrade vscode to a supported version to see if any outstanding electron related issues are now resolved.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo what version of VS Code are you using? The current release 1.54.1 already uses Electron 11

**Comment by user414** [comment]
@gjsjohnmurray That is my fault, I was looking at the wrong place and did not realise we jumped from electron 9 to 11 from 1.51 to 1.54. Please close to issue I will reopen the closed issues with reference to newer electron version in the electron project.
