### ISSUE TITLE
Tasks: Task `label` and `detail` should evaluate variables.

### ISSUE THREAD

**Issue by nitz** [microsoft/vscode#118504]
Currently, [variables](https://code.visualstudio.com/docs/editor/variables-reference) used in `task.json`'s task labels do not get evaluated before being shown to the user in the task run flow. Instead, they're left as `${theirRawString}`. Ideally, they should be evaluated so that the task about to be run could dynamically show what it's about to do, based on ${config}, ${env}, or other variables.

Since `label` is used for `dependsOn`, this could introduce a bit of a quirk with that. My thoughts to how to avoid such an issue were:

- Introduce an `id` for `TaskDescription` that could be set and optionally used to reference from `dependsOn`.
  - Would introduce no backwards compatibility issues, as `dependsOn` could just fall back to checking `label` if `id` wasn't found.
  - Would be unnecessary for users to add if they didn't want to make use of it.
- Rather than expanding `label`, offer a new option perhaps named `display` or similar, that *would* be expanded, and used in the user interface in lieu of `label`, if set.
  - Perhaps a little more obvious than the first option.
  - Muddies the name and purpose of the `label` property.  `label` is already doing double-duty being the task's selector as well as the display for it, so this isn't my favorite option.
- Do nothing: If a user sets `label` to `Build ${env:MYPROJECT}`, then they can use `"dependsOn": ["Build ${env:MYPROJECT}"]`
  - Easiest to implement
  - Would lead to more noise in users' `tasks.json`
  - Feels like it's putting even more lifting on the `label` property.

The `display` property, since it's not keyed on by anything wouldn't suffer the same issue, and should just be expanded when it is drawn in the UI.

**Comment by alexr00** [comment]
@nitz I appreciate the use-case for this feature request, but you can fulfill your use-case by writing an extension that provides tasks. In fact, this kind of situation is exactly what a [Task Provider](https://code.visualstudio.com/api/extension-guides/task-provider) is for: reading your project/environment and creating tasks based on that information. `${}` variable resolution provides a nice shortcut, but it doesn't solve everything.

**Comment by nitz** [comment]
> @nitz I appreciate the use-case for this feature request, but you can fulfill your use-case by writing an extension that provides tasks. In fact, this kind of situation is exactly what a [Task Provider](https://code.visualstudio.com/api/extension-guides/task-provider) is for: reading your project/environment and creating tasks based on that information. `${}` variable resolution provides a nice shortcut, but it doesn't solve everything.

I can definitely appreciate that, and that's definitely what I should do long term. I suppose the "gotcha" for me was that the documentation definitely doesn't specify keys/values where it doesn't work, which actually is what inspired me to write this issue. I spent a while (admittedly far too long 😅) trying to get variables to expand in the label/details in an effort to see if I was building commands the way I wanted to. I later did use the tip [to use echo](https://code.visualstudio.com/docs/editor/variables-reference#_how-can-i-know-a-variables-actual-value). I had nearly opened a ticket wondering why variables didn't work at all before that though.

Perhaps it at least calls for a documentation clarification in the [Variable Substitution](https://code.visualstudio.com/docs/editor/tasks#_variable-substitution) section of Tasks, and in the [Variables Reference](https://code.visualstudio.com/docs/editor/variables-reference) that variables only work in `command` and `args` of `tasks`?

**Comment by alexr00** [comment]
Good request. Added with https://github.com/microsoft/vscode-docs/commit/cecd07b60d7c23f882fe7e67c655260501e253d8

Next time the website is updated the change will be picked up.

**Comment by nitz** [comment]
Wonderful! Thanks, Alex!
