### ISSUE TITLE
Command link in hover no longer works after updated to 1.54

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#118541]
Issue Type: <b>Bug</b>

Im a author of extension, my extension provide a hover with command link `[View Document](command:extension.lua.doc?["en-us/54/manual.html/pdf-debug.getregistry"])`.
I have set `markdown.isTrusted` to `true`, and it works before updating to 1.54.
After updating to 1.54, nothing happens when I click the link.

![link-click](https://user-images.githubusercontent.com/5213431/110476553-10c03a00-811d-11eb-9487-16a39c0fff21.gif)

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.20GB free)|
|Process Argv|--crash-reporter-id 3f5990f0-ecc4-439e-881c-b2e6c5f5fcb2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
extension-path|act|0.0.3
lua-debug|act|1.34.0
tasks|act|0.8.2
daily-anime|dee|1.2.0
gitlens|eam|11.3.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-drawio|hed|1.3.0
vscode-preview-mdl|Jai|0.1.1
git-graph|mhu|1.29.0
vscode-language-pack-zh-hans|MS-|1.54.2
remote-wsl|ms-|0.54.2
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
wurst|pet|0.5.10
bangumiopen|SDT|2.2.4
lua|sum|1.18.0
w3-asset|sum|0.0.5
ayu|tea|0.20.1
vscode-icons|vsc|11.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by jrieken** [comment]
I am using the snippet below and I am not able to reproduce this. 

```

    vscode.languages.registerHoverProvider('fooLang', {
        provideHover() {
            return new vscode.Hover(markupContent)
        }
    })

    const markupContent = new vscode.MarkdownString('[Hello World](command:extension.helloWorld)')
    markupContent.isTrusted = true;
```

**Comment by sumneko** [comment]
![link-click2](https://user-images.githubusercontent.com/5213431/110568024-5e748b00-818d-11eb-8b91-5aeb5629110f.gif)
It’s strange that I still can’t click here, I will try to check my local setting.

**Comment by sumneko** [comment]
https://github.com/sumneko/sample-2
Here you are.

**Comment by sumneko** [comment]
> Your sample doesn't register the command

Thank you, the sample works.
So it seems that there is a problem with my registration command, and I will conduct further checks.
In addition, is it possible to prompt in this case, such as "command not found"?

**Comment by sumneko** [comment]
I found this is due to an error `Error: [sumneko.lua]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api sumneko.lua`.
I will try to fix this, sorry for the noise.
