### ISSUE TITLE
webview use iframe can't trigger drop event

### ISSUE THREAD

**Issue by newby1** [microsoft/vscode#118516]
vscode version: 1.53.2
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

code example:
```
const panel = vscode.window.createWebviewPanel('xxx', 'xxx', vscode.ViewColumn.One, { enableScripts: true})
panel.html = '<!DOCTYPE html>
<html lang="en">
<body>
<iframe  src="https://developer.mozilla.org/en-US/docs/Web/API/Document/dragstart_event"></iframe>
</body>
</html>'
```

issue description:
drag  a div of  'Examples'  should be able to  find the problem

Does this issue occur when all extensions are disabled?: No

**Comment by mjbvz** [comment]
Please share a minimal example extension that demonstrates the problem

/needsMoreInfo

**Comment by newby1** [comment]
> Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.
> 
> Happy Coding!

I added some information

**Comment by mjbvz** [comment]
Does this work if you aren't using an iframe inside a webview?

**Comment by dlacjfgus12** [comment]
_[[[div]()]()]()_</div> 
html index.html
<lang ko>
<div>HEROPY</div>
<span>
</span>

<img href ('HEROPY') src 'Logo> </img>

**Comment by newby1** [comment]
> Does this work if you aren't using an iframe inside a webview?

that's ok

**Comment by mjbvz** [comment]
I'm closing this as out of scope then. If you can avoid it, don't use iframes inside of webviews
