### ISSUE TITLE
Cannot creat a blank jupyter file

### ISSUE THREAD

**Issue by SanyouWu** [microsoft/vscode#118501]
Hi, I cannot create a jupyter file use vscode. But if I can open a .ipynb file which created by jupyterlab. 
The bug in right hand corner is :Unable to open 'main.ipynb': Unexpected token i in JSON at position 0.

**Comment by sambradbury** [comment]
I ran into this same issue. The instructions provided by the Python Extension homepage are incorrect. 

1. Open the command palette with the shortcut: `Ctrl/Command` + `Shift` + `P`
2. Search for the command `Create New Blank Jupyter Notebook` (this command does not work)

The actual command is:
'Jupyter: Create New Blank Notebook' alternatively you can just type 'Create New Blank...' and it will autofill the proper command for you.
