### ISSUE TITLE
Option to completely disable or hide the integrated terminal panel

### ISSUE THREAD

**Issue by ronilaukkarinen** [microsoft/vscode#118537]
For some reason the terminal is persistent in versions 1.54 and later. I'd like to **completely** hide the integrated terminal yet keep the Problems tab for more space. Yes, you can "minify" the terminal but the extra collapsed toolbar bothers me (I'm kinda OCD). Any way to completely disable or visually hide the terminal panel?

![Screen-Shot-2021-03-09-14-12-09](https://user-images.githubusercontent.com/1534150/110468927-a3db7e80-80e1-11eb-8250-d410ef1437e8.png)

![Screen-Shot-2021-03-09-14-12-20](https://user-images.githubusercontent.com/1534150/110468937-a76f0580-80e1-11eb-8e45-b229a3a10ef6.png)

**Comment by gjsjohnmurray** [comment]
You seem to have docked your Terminal pane alongside the Problems pane on the Problems tab.

Try this:
1. Right-click on its TERMINAL caption and choose "Reset Location" to make it a separate tab on the Output Panel.
2. Right-click on its tab and choose "Hide 'Terminal'"

/question

**Comment by ronilaukkarinen** [comment]
Oh, didn't realize there's a setting under the caption... I must have docked it by accident indeed. Searched for hours about this without results. Thank you very much @gjsjohnmurray.
