### ISSUE TITLE
[Regression] - Trigger suggest broken and overlapping text (TypeScript)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#118526]
- VS Code Version: 1.54.1
- OS Version: MacOS 10.15.7

Steps to Reproduce:
_You can see the video below_

1. Checkout https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example and open in VSCode
2. install dependencies
3.  In `[id].tsx` try to import `Welcome`
4. Remove the top import line and try to use the trigger suggest to import instead
5. `Welcome` gets overwritten from where the cursor is and causes the variables to be messed up unless you do it at the end of the word

## Screenshot
![Kapture 2021-03-09 at 10 14 34](https://user-images.githubusercontent.com/936006/110456132-1ee06d00-80c1-11eb-904e-6d3736c9e679.gif)

This didn't used to happen so I think a recent release has broken it somehow

**Comment by IllusionMH** [comment]
I think this is behavior for default value for `editor.suggest.insertMode` which is `"insert"` for JS/TS etc. (and I don't think is had different behavior before), however it's `"replace"` for HTML/CSS language.
So it's opposed to be overwritten inserted instead leaving other part hanging.

You can add settings to change it for all or specific languages to `"editor.suggest.insertMode": "replace"` or hold <kbd>Shift</kbd> to perform replace when confirming suggestion. e.g. <kbd>Shift</kbd>+<kbd>Enter</kbd> or <kbd>Shift</kbd>+<kbd>Tab</kbd>

**Comment by jasonwilliams** [comment]
Thanks @IllusionMH forcing “replace” seems to fix it. I don’t understand how it reverting back to “insert”, I don’t think I’ve ever seen that setting before, so either an update changed it or an extension?

would “replace” not make a better default for JS/TS? Why do JS/TS prefer “insert”?

**Comment by mjbvz** [comment]
Yes sounds like you need to set the setting here. Let me know if there are any cases where insert/replace do not seem to be working as expected
