### ISSUE TITLE
Update: make sure to apply latest possible version

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#118523]
Currently it can happen that I update VS Code immediately afterwards there is another update notification (since you probably downloaded the previous update before and only after applying the update you figure out there is an even newer update)
Could we somehow improve this? Before applying the downloaded update that you check one more time if there is a newer version?

I think this would improve these cases when we have multiple stable + recovery releases and users are needlesly updating multiple times.

**Comment by joaomoreno** [comment]
Unfortunately this isn't possible with the built-in Squirrel in Electron and the API it provides. This issue comes up once a month.
