### ISSUE TITLE
Remove use of assert.equal from the code

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#118667]
The code base currently uses a mixture of `assert.strictEqual` and `assert.equal` for mocha testing. However, `assert.equal` is deprecated meaning overtime it may break or cease to work. We also see ugly strike throughs in many of our tests. See https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message for more info on the deprecation. 

**Proposal**
My suggestion is that we make an effort to remove all `assert.equal` use cases from our code base since it's been deprecated since version 9.9 of node. We currently have 3,697 uses of assert.equal.

# Progress

- [x] `assert.equal` removed
- [x] `assert.notEqual` removed
- [ ] `assert.deepEqual` removed
- [x] `assert.notDeepEqual` removed
- [x] Remove deprecated asserts from built-in extensions.

**Comment by lramos15** [comment]
First PR went in for this, still additional deprecations to resolve. See comment on #120125 for more details

**Comment by jrieken** [comment]
@lramos15 What about `notEqual`, `deepEqual`, `notDeepEqual` etc?

**Comment by lramos15** [comment]
@jrieken Yeah I put that as a comment on #120125, I will be doing those as well but just wanted incremental steps so the changes wouldn't be as large.

**Comment by lramos15** [comment]
The following were unable to be converted to `deepStrictEqual` easily. Most were due to prototype mismatches but I believe some had to do with type mismatches as well.
@weinand and @alexr00 `configurationResolverService.tests.ts`
@bpasero `objects.test.ts`
@alexdima `tokenization.test.ts`
@sandy081 `configurationModels.test.ts`, `codeeditor.tests.ts`
@connor4312 `search.test.ts` (there's also an uncommented test in there from 2 yrs ago from @roblourens)
@roblourens `searchHelpers.test.ts`, `mainThreadWorkspace.test.ts`, `queryBuilder.test.ts`

**Comment by lramos15** [comment]
I finished all the extensions. @roblourens if you could finish your few files we could close this out this milestone :)
