### ISSUE TITLE
Status Bar Entry shows when unknown and trust has not been requested

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118684]
- Open a new workspace, work for awhile
- This indicator shows up at some point
![image](https://user-images.githubusercontent.com/323878/110720700-e5dcf100-81c3-11eb-9878-92d7528b7e23.png)

- Click it, see this:
![image](https://user-images.githubusercontent.com/323878/110720586-b3cb8f00-81c3-11eb-9eee-2e5fc2df451b.png)

But I can't figure out what triggered this, because I am not using the workspace TS version and I don't know how else the extension will be "limited". Is there a way to get more details?

**Comment by roblourens** [comment]
On the gear icon? I don't think so

**Comment by sbatten** [comment]
closing as obsolete
