### ISSUE TITLE
Copy All copies text from Debug Console with ANSI color codes

### ISSUE THREAD

**Issue by ristiisa** [microsoft/vscode#118646]
Issue Type: <b>Bug</b>

Copy All copies text from Debug Console with ANSI color codes but Copy does not.

Version: 1.55.0-insider (system setup)
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:13:14.184Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

VS Code version: Code - Insiders 1.55.0-insider (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f, 2021-03-08T05:13:14.184Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-74-generic
Remote OS version: Darwin x64 20.3.0
Remote OS version: Darwin x64 20.3.0

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
LogFileHighlighter|emi|2.11.0
dotenv|mik|1.0.1
remote-ssh-edit-nightly|ms-|2021.3.12420
remote-ssh-nightly|ms-|2021.3.12420
remote-wsl|ms-|0.54.2
python|ms-|2021.4.637492490-dev
jupyter|ms-|2021.4.625511240

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwsldoc:30268767
vsget980:30265949
vspre833:30267464

```

</details>

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by ristiisa** [comment]
> This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

Not having a bug is not a "feature request".
