### ISSUE TITLE
Add a 'View: Show All Editors By Name' option

### ISSUE THREAD

**Issue by ruudhanegraaf** [microsoft/vscode#118625]
I really like the option to sort the opened editors in the Explorer pane. It would be nice however to also have this option for the 'View: Show All Editors By' commands. The 'By Appearance' only shows them the way the tabs are sorted, but an option to have them shown the exact same order as the 'Open Editors' would be really appreciated.

Thanks for all your effort!

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

fyi @bpasero this requests for the editors to always be sorted as they are in Open Editors (once sorting is enabled)

**Comment by ruudhanegraaf** [comment]
Hi bpasero. Yep, that's right. I mean the picker (workbench.action.showAllEditors). Sorry if my explanation was a bit confusing.

Thanks!
