### ISSUE TITLE
git push message reference to 'upstream' may be confusing

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#118617]
After creating a new local branch in a repo with two remotes named 'origin' and 'upstream', with 'origin' as the default remote, when I use the Push option from the SCM context menu I receive a warning message about my new local branch having no **upstream** branch. It seems to come from here:

https://github.com/microsoft/vscode/blob/94303f8e574f719ad7af848ed68894fc0ca3c749/extensions/git/src/commands.ts#L2132

or here:

https://github.com/microsoft/vscode/blob/94303f8e574f719ad7af848ed68894fc0ca3c749/extensions/git/src/commands.ts#L2282

Could it talk about no **remote** branch instead?

**Comment by eamodio** [comment]
I'm not convinced that this should be changed. Most Git tools talk about setting an "upstream". Git itself is inconsistent when talking about upstream/remote/tracking branches.

**Comment by gjsjohnmurray** [comment]
In a recent livestream @RMacfarlane mentioned the GHPRI extension and I think made a point about how it now does a better job when a local repo deals with two remotes (conventionally named 'origin' and 'upstream'). So I still think it'd be better for these two messages to use the generic term 'remote' than the more specific 'upstream'.

**Comment by gjsjohnmurray** [comment]
@eamodio please reconsider merging the PR I offered for this.

**Comment by lszomoru** [comment]
@alexr00, do you know by any chance what Rachel was referring to ([see comment](https://github.com/microsoft/vscode/issues/118617#issuecomment-821587000)).

**Comment by alexr00** [comment]
Not sure what Rachel was referring too, but by default in GHPRI we look for remotes called `origin` and `upstream`, so I agree with it being confusing to use the word "upstream" when discussing git. With git alone it's perhaps not confusing, but if you start talking about OSS projects, "upstream" becomes overloaded.
