### ISSUE TITLE
Add an option to have pinned tabs get a higher sorting order

### ISSUE THREAD

**Issue by ruudhanegraaf** [microsoft/vscode#118626]
I really like the option for sorting tabs by name in the Explorer pane. It would be really nice to also have the option to have pinned tabs being ranked higher. So if have have opened editors File1, File2, File4, and SomethingElse, in which File2 and SomethingElse were pinned tabs, the order would be: 
:pushpin: File2
:pushpin: SomethingElse 
File1
File4

I pin my most important tabs, so if they would always be at the top of the list, that would make it easier to switch back to them.

Thanks for all your effort!

**Comment by bpasero** [comment]
@ruudhanegraaf you mean in the "Open Editors" view? They should be on top sorted, no?

**Comment by ruudhanegraaf** [comment]
Hi bpasero. Yes, that's right. The Open Editors view in the Explorer pane of the side bar. And the pinned tabs sorted on top, and then the non-pinned sorted below that.

So instead of:

![image](https://user-images.githubusercontent.com/48607712/110676894-ca2e1680-81d4-11eb-8950-1fd0c1f53466.png)

This:

![image](https://user-images.githubusercontent.com/48607712/110676944-d7e39c00-81d4-11eb-8843-2d61e8ed2fc0.png)

Does that help?

Thanks for looking into it!

**Comment by ruudhanegraaf** [comment]
Hi @bpasero. And you're sure you have explorer.openEditors.sortOrder set to alphabetical? 🤔 
Because if so, the order isn't right for the unpinned tabs. If they were propperly sorted by name it would be:
Features.ts
Game.ts
Position.js
Postion.ts

This is how the same files looks in my VSCode.

![image](https://user-images.githubusercontent.com/48607712/110750322-97bb0280-8242-11eb-881f-4d3ab5b1b0d5.png)

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. 
Thanks
