### ISSUE TITLE
Navigation Buttons Dissapeared And Do Not Show Up After Reinstall - Also Unable To Move Window

### ISSUE THREAD

**Issue by bonedaddy** [microsoft/vscode#118685]
Issue Type: <b>Bug</b>

Not sure how to reproduce but im unable to get this to go away even after purging the `code` package using `apt` and reinstalling a newer version. I'm also unable to move the window around at all which basically makes this application impossible to use.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.08GB (22.21GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
gopium|1pk|1.2.3
bracket-pair-colorizer-2|Coe|0.2.0
vbscript|Dar|1.0.4
gitlens|eam|11.3.0
go|gol|0.23.0
solidity|Jua|0.0.108
vscode-language-babel|mgm|0.0.30
vscode-docker|ms-|1.10.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
platformio-ide|pla|2.3.0
rust|rus|0.7.8
markdown-preview-enhanced|shd|0.5.16
fish-vscode|sky|0.2.1
vba|spe|1.7.1
zig|tie|0.2.5
markdown-pdf|yza|1.4.4
vscode-proto3|zxh|0.5.3

</details>

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose` and also provide a screen recording of the issue you are facing.

**Comment by bonedaddy** [comment]
It appears this issue was unrelated to vscode, and due to "Pop Shell Extensions" on my Pop!_OS laptop. Closing this as it seems unrelated to a vscode bug. Sorry for the confusion.
