### ISSUE TITLE
Can't work in ubuntu16.04 - vagrant

### ISSUE THREAD

**Issue by hikidd** [Microsoft/vscode#11861]
- VSCode Version: 1.5
- OS Version: ubuntu 16.04 - vagrant

Steps to Reproduce:
1.  Download and install an ubuntu box in vargrant
[Ubuntu Desktop 16.04 Xenial Xerus (64-bit)](https://vagrantcloud.com/boxcutter/boxes/ubuntu1604-desktop/versions/2.0.18)
2. Download vscode. [download] (https://code.visualstudio.com/Docs/?dv=linux64_deb)
3. Run it, but black screen as below.
![unnamed_20160901_105618_632](https://cloud.githubusercontent.com/assets/17465708/18427439/a028e8fc-78fa-11e6-87a4-714db8e3bc64.png)

And I tried VSCode-linux-x64, but still black.

**Comment by joaomoreno** [comment]
Something is wrong with your VM or VM host.

Works for me when running vagrant through Parallels.

![image](https://cloud.githubusercontent.com/assets/22350/18475597/4f7a2fce-79c7-11e6-8d78-e36c1dbe061c.png)

**Comment by hikidd** [comment]
After I unchecked this, it is ok now!!! hahaha! Thanks!
![unnamed_20160919_024713_772](https://cloud.githubusercontent.com/assets/17465708/18624186/20a63e80-7e78-11e6-9728-2f560d70a9a4.png)

![unnamed_20160919_024951_481](https://cloud.githubusercontent.com/assets/17465708/18624219/5e6d0c80-7e78-11e6-83cc-f069a203932e.png)
