### ISSUE TITLE
I have no access to my Automator Services from contextual menus

### ISSUE THREAD

**Issue by hepcat72** [microsoft/vscode#118672]
Issue Type: <b>Feature Request</b>

I'm just trying out Visual Studio code for the first time and I wanted to run one of my custom services I wrote on some selected text.  I right-clicked the selected text and there was no services sub-menu provided by the system.  It's going to get old real quick to copy text out into a different editor to be able to run services in it.

VS Code version: Code 1.54.1 (Universal) (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0

**Comment by hepcat72** [comment]
Is there a way to access the system contextual menu from right-clicks of selected text?  Like, is there a modifier key to hold down which right-clicking?

**Comment by JacksonKearl** [comment]
I assume you're referring to this item in the macOS native context menu? cc @deepak1556 for if electron can do this.

**Comment by hepcat72** [comment]
Yes, exactly.  I'm a computational biologist and I have lots of string processing code, such as blasting sequences that might be included in a file I'm working on, or reverse complementing, or... well, let me just paste a screenshot of my services:

<img width="269" alt="services" src="https://user-images.githubusercontent.com/2300532/110813308-63e9d800-8256-11eb-8cd9-d7cb0d0c40e0.png">

I use these every day.

**Comment by deepak1556** [comment]
Runtime does not support this feature, closing as not planned.
