### ISSUE TITLE
semanticTokens not being applied in editor when implementing textDocument/semanticTokens/full

### ISSUE THREAD

**Issue by fabioz** [microsoft/vscode#118636]
- VS Code Version: 1.54.1
- OS Version: Windows

I'm in the process of implementing semantic tokens for a language server, but something seems to be off as the semanticTokens seem to be requested but aren't being applied.

The steps I did were:

1. Use `"vscode-languageclient": "^7.0.0"` as a dependency (it seems that with older versions the semanticTokens request is not made) -- also, upgraded to use `"vscode": "^1.54.0"` as the engine.

2. Make the language server return `semanticTokensProvider` in the server `capabilities`:

```
"semanticTokensProvider": {
    "legend": {
        "tokenTypes": TOKEN_TYPES,
        "tokenModifiers": TOKEN_MODIFIERS,
    },
    "range": False,
    "full": True,
}
```

For simplicity the token types being returned are the token types accepted by default in the client (so, no other custom token is being contributed). Thus:

`TOKEN_TYPES = ["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"]` 

`TOKEN_MODIFIERS = ["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"]`

3. Make the language server return something for `textDocument/semanticTokens/full`. For simplicity I decided to just hard-code the return to be `[1, 0, 10, 1, 0, 1, 0, 10, 1, 0]` for anything (and then I tested opening with a file where those ranges are always there).

By the spec I believe that should mean something as:
```
deltaLine: 1 (abs line: 1), deltaCol: 0, len: 10, tokenType: 2 (class), tokenModifier: 0 (none)
deltaLine: 1 (abs line: 2), deltaCol: 0, len: 10, tokenType: 2 (class), tokenModifier: 0 (none)
```

So, at this point I expected semanticTokens to be available with some coloring. I can see that VSCode is calling `textDocument/semanticTokens/full`, but it doesn't seem like the semanticTokens are being applied.

The actual messages are something as:
```
{'jsonrpc': '2.0', 'id': 4, 'method': 'textDocument/semanticTokens/full', 'params': {'textDocument': {'uri': 'file:///x%3A/minimal/tasks.robot'}}}

{'jsonrpc': '2.0', 'id': 4, 'result': [1, 0, 10, 1, 0, 1, 0, 10, 1, 0]}
```

i.e.:

![image](https://user-images.githubusercontent.com/117621/110636464-0c326a80-818b-11eb-8b0f-5ff9a5941379.png)

I tried to remove the existing textmate grammar to see if it did any change (so that only the semanticTokens would be there) and it didn't seem to make any difference (in the example the only thing with a different color is what's gotten from the textmate grammar).

I think that with that it should work, but it doesn't... is this a bug in VSCode or am I missing something?

**Comment by aeschli** [comment]
Do you happen to have a repo that you can share that contains the small sample project?

**Comment by fabioz** [comment]
You can reproduce it by following the instructions at:

https://github.com/robocorp/robotframework-lsp/blob/syntax_259/example-vscode/docs/README_issue_118636.md

Note: the project is part of a mono-repo, but the `example_vscode` (plus the `robocorp-python-ls-core`, which is vendored in the process) should have all the contents (that's the more minimal reproduction I could come up with... most of the things there are just related to getting the communication and the language server in place in python + a vscode client extension to start up the communication).

**Comment by fabioz** [comment]
I'm sorry, this was a problem on my side (the message was wrong, it seems I misread the spec).
