### ISSUE TITLE
Manually providing PAT to GitHub auth not working

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#118675]
1. Install an extension needing GitHub authentication, like GitHub Codespaces
2. Generate a personal access token on GitHub - go to your settings > developer settings > personal access tokens (if creating for codespaces, scopes are `repo`, `user:email` and `read:user`)
3. Start sign in process in VS Code using accounts menu
4. Ignore browser window that opens and instead go back to vscode and use the "Signing into github.com" item in the status bar
5. In the quickpick that opens, enter your PAT from step 2

The sign in process does not complete.

**Comment by Mikezett** [comment]
Seems settings sync still broken.

![VSInsSignIn](https://user-images.githubusercontent.com/16895352/111813196-eecb7200-88e9-11eb-92e2-28cef817e4cd.JPG)

**Comment by RMacfarlane** [comment]
@Mikezett Can you please provide repro steps? Did you sign in using a PAT?

**Comment by Mikezett** [comment]
Yes i used PAT.
I copy token. 
Sign In to Sync Settings => SignIn with GitHub => Jump to browser => Open VSCI again => Press "Sing in ..." in the bottom => Insert my token to field "Token (Press Enter..."

**Comment by petrxpx** [comment]
Hi!
I have the same problem with using PAT:
In VScode stable can't sign in with PAT.
In VSCode insiders sign in is correct with error sync  "Error while turning on Settings Sync: Authentication failed."

**Comment by RMacfarlane** [comment]
@petrxpx Can you create a new issue to track the settings sync error? It sounds like the sign in portion is now working as expected, which is what this bug tracks.
