### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by clhess** [microsoft/vscode#118658]
- VS Code Version: 1.54.1
- OS Version: Fedora 30

Steps to Reproduce:

1. install latest version of code
2. run code via XRDP/XVNC (connecting to linux from win10)

Does this issue occur when all extensions are disabled?: Yes

The last version that worked/rendered correctly is 1.52.1
![VSCodeRenderIssue](https://user-images.githubusercontent.com/22080225/110668394-801f4380-8188-11eb-91eb-31a76d393b4e.PNG)

**Comment by clhess** [comment]
looks like 1.54.3 is better but still an issue rendering some of the menus

![image](https://user-images.githubusercontent.com/22080225/112198053-f5980480-8bc9-11eb-9794-af9f3ff4d6f4.png)

**Comment by clhess** [comment]
But some of the menus are fine which is weird

![image](https://user-images.githubusercontent.com/22080225/112198285-3132ce80-8bca-11eb-9001-f4a84e874416.png)

**Comment by clhess** [comment]
i also noticed that when i resize the window it's gets skewed and resizing some more makes it render normal again but I don't know the correlation to size vs skewing.

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/116402

This is an issue with native titlebar on particular remote setup, as workaround you can use custom titlebar by setting `"window.titleBarStyle": "custom"`

or use vscode remote development suite https://code.visualstudio.com/docs/remote/remote-overview#_getting-started for better experience.

**Comment by clhess** [comment]
The windot.titleBarStyle did it.... it's still skews when i'm resizing the window but it renders correctly when resizing is done.  Thanks for the tips.
