### ISSUE TITLE
Snippets IntelliSense can't show description

### ISSUE THREAD

**Issue by 2016geek** [microsoft/vscode#118696]
- VS Code Version: 1.54.1
- OS Version: mac OS Catalina 10.15.7

Steps to Reproduce:

1. The custom snippets configuration is complete
2. The description is not displayed in the smart prompt
3. code is
<code>
{
  "$green11": {
    "prefix": "$green11",
    "body": [
      "green"
    ],
    "description": "#00C792"
  }
}
</code>
4. 
![image](https://user-images.githubusercontent.com/20659607/110745208-e209a700-8275-11eb-8a0c-526a2f50f6fd.png)
5. I remember showing '#00C792' in the old version instead of '$green11'

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
<img width="694" alt="Screenshot 2021-03-11 at 09 05 06" src="https://user-images.githubusercontent.com/1794099/110755117-e1a6e700-8248-11eb-8f08-e9d35e3dbf2d.png">

The description is shown in the details windows. The suggestion view shows name and prefix (we are the same in your case)
