### ISSUE TITLE
Rename operation aborted without user interaction in 1.54.1

### ISSUE THREAD

**Issue by nflorentin** [microsoft/vscode#118697]
- VS Code Version: 1.54.1
- OS Version: Mac OS 10.15.7

Hi,

I just upgraded to 1.54.1 and I'm still experiencing the same problem as in:
- https://github.com/microsoft/vscode/issues/112555
- https://github.com/microsoft/vscode/issues/111652
- https://github.com/microsoft/vscode/issues/112438
- https://github.com/microsoft/vscode/issues/111652

Thanks for your help

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo can you reproduce the issue after running the command to reload with all extensions disabled? If so please provide clear steps.

**Comment by nflorentin** [comment]
Arg, can't reproduce it anymore with extensions disabled or not...
