### ISSUE TITLE
Fail to load SVG files on hover

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#118678]
Version: 1.55.0-insider
Commit: 5d80c30e5b6ce8b2f5336ed55ad043490b0b818f
Date: 2021-03-08T05:24:34.127Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Execute the following extension sample.
2. Move a mouse cursor to any text.
3. Fail to load SVG files out of the extension path and on remote servers.

We want to display dynamically generated SVG files on hover. They are rendered math equations and thumbnails of PDF files. They are typically generated in a temporary directory out of the extension directory.

Console says:
```
tiger.svg:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

Does this issue occur when all extensions are disabled?: Yes

```ts
import * as vscode from 'vscode';
import * as path from 'path';

export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "helloworld-sample" is now active!');
	context.subscriptions.push(
		vscode.languages.registerHoverProvider({ scheme: '*' }, new HoverProvider(context.extensionPath))
	)
	const disposable = vscode.commands.registerCommand('extension.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World!');
	});
}

class HoverProvider implements vscode.HoverProvider {
	path: string
	constructor(path: string) {
		this.path = path
	}
	provideHover(): vscode.Hover {
		const insideExtensionUri = vscode.Uri.file(path.join(this.path, 'tiger.svg'))
		const fileUri = vscode.Uri.file('/Users/tamura/Downloads/tiger.svg')
		const serverUri = vscode.Uri.parse('https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/tiger.svg')
		const md = `ext: ![svgimg](${insideExtensionUri.toString(true)}) local: ![svgimg](${fileUri.toString(true)}), server: ![svgimg](${serverUri.toString(true)})`
		const mdString = new vscode.MarkdownString(md)
		const hover = new vscode.Hover(mdString)
		return hover
	}
}
```

![スクリーンショット 2021-03-11 9 00 53](https://user-images.githubusercontent.com/10665499/110715574-d94eac00-8248-11eb-9d5b-3c64a66d711c.png)

**Comment by jrieken** [comment]
cc @mjbvz
