### ISSUE TITLE
The CPU usage is high - Mac 16inch

### ISSUE THREAD

**Issue by vcalderon2009** [microsoft/vscode#118610]
Issue Type: <b>Bug</b>

After the last update, the CPU gets overwhelmed whenever the "Insider's" version of VS Code is used. 

VS Code version: Code - Insiders 1.55.0-insider (5d80c30e5b6ce8b2f5336ed55ad043490b0b818f, 2021-03-08T05:24:34.127Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|32.00GB (4.02GB free)|
|Process Argv|--crash-reporter-id dd29e9de-1505-466f-9ad2-e40f89b4cfdb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
aws-toolkit-vscode|ama|1.20.0
clock|ang|1.0.1
toml|be5|0.5.1
git-easy|bib|1.11.0
better-toml|bun|0.3.2
gitignore|cod|0.6.0
git-extension-pack|don|0.1.3
githistory|don|0.6.15
gitlens|eam|11.3.0
json-pretty-printer|eus|1.1.0
gitlab-workflow|Git|3.14.0
gc-excelviewer|Gra|3.0.41
git-graph|mhu|1.29.0
vscode-docker|ms-|1.10.0
python|ms-|2021.3.612345846-dev
jupyter|ms-|2021.4.625511240
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
preview-vscode|sea|2.2.5
bash-beautify|sha|0.1.1
gitblame|wad|6.0.2
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoccf:30268770
vsget980:30265949
vsc_aa:30263845
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please see https://github.com/microsoft/vscode/wiki/Performance-Issues

Probably also worth using the Extension Bisect command to investigate.
