### ISSUE TITLE
Close vscode with confirm

### ISSUE THREAD

**Issue by MortezaHeydari97** [microsoft/vscode#118619]
Hi, I think a feature is missed in vscode.
Supose you're runing a project like react using vscode terminal. Accidentally you clicking on close button. Then the vscode window will close.
What will happen ?
You will get angry and this is a negative score for vscode.
Please set a confirmation for close vscode window.
With respect and thanks.

**Comment by gjsjohnmurray** [comment]
Maybe try this setting:
```
"terminal.integrated.confirmOnExit": true
```

**Comment by usernamehw** [comment]
Possible duplicate of #14710

**Comment by MortezaHeydari97** [comment]
It works, so thanks !
@gjsjohnmurray
