### ISSUE TITLE
Awfully slow pylance.

### ISSUE THREAD

**Issue by ayagrwl** [microsoft/vscode#118698]
Issue Type: <b>Performance Issue</b>

The suggestions and highlighting provided by pylance takes about 5 mins after opening a workspace. (the workspace folder contains no more than 5 files). After reloading window, most of the time pylance stops working without any error. no more colors in code :'(    I have tried reinstalling vscode, but after a week, the problem still returns. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:44.518Z)
OS version: Linux x64 5.9.8-050908-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2399)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.56GB (1.29GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 87349d20-8215-4d80-9076-4b205105765c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
yash|dao|0.2.6
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
gitlens|eam|11.2.1
code-runner|for|0.11.2
latex-workshop|Jam|8.16.1
python|ms-|2021.2.633441544
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.2.603412351
cpptools|ms-|1.2.2
rust|rus|0.7.8
even-better-toml|tam|0.11.1
vscode-icons|vsc|11.1.0

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension please report this to the extension author
