### ISSUE TITLE
Keytar causes crash on Stable, but not Insiders?

### ISSUE THREAD

**Issue by marceau-maubert** [microsoft/vscode#118630]
Issue Type: <b>Bug</b>

I don't know at which point this started happening, but starting an instance of Stable now crashes a few seconds after, with parameters `code --verbose -n` I get this:

```
terminate called after throwing an instance of 'char const*'
/dev/fd/3: No such file or directory
Server response:
```

I figured out after looking through the issues that it might be related to Keytar and that there was a new command line parameter to turn it off, which did resolve the issue. My credentials are however no longer being saved, of course, so that's not really a nice solution, considering how Insiders works just fine somehow. 

I'm not using Snap to install either. I tried upgrading `libsecret-1-0` manually since that seems to be something Keytar depends on and Ubuntu might be behind, but to no avail, and that was really just a shot in the dark.

Is this something on my end that I should fix? Is there any way I could get more useful information to debug?

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2820)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.35GB (13.93GB free)|
|Process Argv|--no-sandbox --disable-keytar --unity-launch --crash-reporter-id a86d776a-41fe-4222-8b46-cd5253dde5b1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by craftsman777** [comment]
f

**Comment by wjs4572** [comment]
What is the current method for implementing extensions using keytar in vscode.  The method that azure uses, doesn't appear to be working as keytar is not loading.

Thank you,

**Comment by RMacfarlane** [comment]
@marceau-maubert Are you still seeing this on the latest stable version as well?

**Comment by marceau-maubert** [comment]
I haven't had an issue with this in a while, I don't really know what solved it however.

**Comment by RMacfarlane** [comment]
Ok, thanks! I'm going to go ahead and close this since I don't think there is anything actionable for us to do right now, but please let us know if you see this again.
