### ISSUE TITLE
Installing extensions in Linux through authenticated proxy fails (Server returned 407)

### ISSUE THREAD

**Issue by DentCop** [Microsoft/vscode#11860]
- VSCode Version: 1.5.1
- OS Version: Debian 8.5

Steps to Reproduce:

1. Have proxy which requires authentication (in my case simple auth)
2. Add proxy server to user settings:
    "http.proxy": "http://username:password@proxy1.domain.com:80", 
3. Optionally also setup proxy in env: 
    export http_proxy=http://username:password@proxy1.domain.com:80
4. Run vscode and display extensions - extensions are displayed with option to install
5. Click on install (any extension) - Error - Server returned 407

**Comment by joaomoreno** [comment]
I'm guessing it worked in 1.4? #11702 Fix is already out in 1.5.2.

**Comment by joaomoreno** [comment]
Can you check using the `http.proxyAuthorization` setting? We could maybe split that setting into username and password, but for now you'll need to put in there whatever value your proxy would accept as the `Proxy-Authorization` header. [See more](https://httpstatuses.com/407).

**Comment by DentCop** [comment]
What do you enter into http.proxyAuthorization field? Is this a string? Do I need to find out what the response header from the proxy is?

**Comment by joaomoreno** [comment]
That actually depends on your proxy. Can you ask your system administrator what authentication methods it supports?

[This user](https://github.com/Microsoft/vscode/issues/6480#issuecomment-240989815), for example, only needed to base64-encode his username and password. Some other cases require NTLM (which we don't support #10461 yet), and more.

**Comment by DentCop** [comment]
I have updated to v1.5.2 this morning to make sure I'm testing the latest version of code. 

I have changed my configuration by removing Username:Password from `"http.proxy":` line in the config file and added `"http.proxyAuthorization":` line in the format `Basic <base64 string>` (our proxy does support Basic authentication). This `base64 string` was captured from a successful authentication in Firefox.

```
    "http.proxy": "https://proxy.domain.com:80",
    "http.proxyAuthorization": "Basic VXNlcm5hbWU6UGFzc3dvcmQ="
```

Next onto some Wireshark captures...

First captures using **Firefox as a baseline**:

Accessing URL for C# extension: `https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.4.1/assetbyname`

**Unsuccessful** Request:
```
SYN
SYN, ACK
ACK
CONNECT ms-vscode.gallery.vsassets.io:443 HTTP/1.1 (no Proxy-Authorization in the header)
ACK
HTTP/1.1 407 Proxy Authentication Required ( Forefront TMG requires authorization ...
ACK
FIN, ACK
ACK
```

**Successful** Request:
```
SYN
SYN, ACK
ACK
CONNECT ms-vscode.gallery.vsassets.io:443 HTTP/1.1 (with Proxy-Authorization in the header)
ACK
HTTP/1.1 200 Connection established
ACK
SSL negotiation follows
GET /_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.4.1/assetbyname
is issued within SSL session
....
```

Now this is what i see when I capture same request in **Vscode**

```
SYN
SYN, ACK
ACK
CONNECT ms-vscode.gallery.vsassets.io:443 HTTP/1.1 (no Proxy-Authorization in the header)
ACK
HTTP/1.1 407 Proxy Authentication Required ( Forefront TMG requires authorization ...
ACK
GET /_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.4.1/assetbyname (this has Proxy-Authorization in the header)
ACK
RST, ACK
```

Vscode is not including Proxy-Authorization in the CONNECT request and this gets rightfully rejected by the proxy.

Instead of trying another CONNECT request with Proxy-Authorization, Vscode then follows up with a GET request (this has Proxy-Authorization, but it's pointless now).
After this, proxy resets the connection.

This repeats two times and then I get "Server returned 407" in the GUI.

I will have a look at the code (I'm no programmer...), but I thing the problem is that `Proxy-Authorization` is not included in the initial CONNECT request. Second problem is that a failed CONNECT request is not detected and followed by a GET request.

**Comment by DentCop** [comment]
So, the above is still true if you try to use `"http.proxyAuthorization":` field. Looks like it needs more work.

But, after changing my configuration back to including `username:password` in `"http.proxy":`, installing extensions now works! This is code v1.5.2. 

Working config is:
```
"http.proxy": "http://username:password@proxy.domain.com:port#`"
```
Which is what I stated with.

**Comment by joaomoreno** [comment]
Ah, good to know! Yeah that is the preferred use. 👍
