### ISSUE TITLE
Tab stops disappearing

### ISSUE THREAD

**Issue by wienkesh** [microsoft/vscode#118657]
Issue Type: <b>Bug</b>

I am losing my 4 space tab stops in the code editor after a few minutes of VS Code being open.  Below is how a new script looks currently after VS code has been open for several minutes.  As you can see, when I tab the SELECT and FROM in they are going to position 8:

![image](https://user-images.githubusercontent.com/35665098/110666870-b1534000-8197-11eb-9df1-ead34b651643.png)

But if I close and re-open VS code, it works for awhile they way it is supposed to - tabbing in to position 4.  
![image](https://user-images.githubusercontent.com/35665098/110667095-e95a8300-8197-11eb-9634-9961ec56837a.png)

This only started happening after the last update.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|-psn_0_98328 --crash-reporter-id 1aecde6a-55f5-4988-a465-b3d9589c43bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt617cf:30253240
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627cf:30244335
pythonvspyt875:30259475
dockersubset:30265998
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by JacksonKearl** [comment]
Do you have any extensions installed that might be affecting SQL formatting? You can try running with all extensions disabled to see if the bug reproduces then (`F1` => `Developer: Reload with Extensions Disabled`). If you don't see it then, you can try running an extension bisect (`F1` => `Help: Start Extension Bisect`) to determine the root cause.

**Comment by wienkesh** [comment]
> Do you have any extensions installed that might be affecting SQL formatting? You can try running with all extensions disabled to see if the bug reproduces then (`F1` => `Developer: Reload with Extensions Disabled`). If you don't see it then, you can try running an extension bisect (`F1` => `Help: Start Extension Bisect`) to determine the root cause.

I might, yes.  I'll try that.  Thanks

**Comment by alexdima** [comment]
Caused by `EditorConfig`. That extension is actively changing the indentation settings of vscode. This can be tricky, especially if you have forgotten by any chance some `.editorconfig` files in your user folder or somewhere up the folder hierarchy.
