### ISSUE TITLE
Synchronize dirty files across multiple windows

### ISSUE THREAD

**Issue by netrounds-joakim** [Microsoft/vscode#11866]
- VSCode Version: 1.5.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open a file
2. Create a new window
3. Drag the file to the second window (opens a second copy)

Is there any plans to have a "live sync" when a file is opened in two windows at the same time? Right now the second window only gets updated when one saves. It is very easy to accidentally start editing an out of date version of the file.

Editors such as sublime fully support this and I was expecting the same behavior.

**Comment by bpasero** [comment]
@netrounds-joakim if I have the same file open in 2 windows I do not see the files show the same content until I save. Are you saying you expect to see both files turn dirty while you type or after you save?

**Comment by netrounds-joakim** [comment]
@bpasero Hello, I don't know what you mean by "turn dirty".

To be clear I will communicate in pictures :)

I open a file `myfile.txt` and type something in it.
![2016-09-13 15_25_49- myfile txt - visual studio code](https://cloud.githubusercontent.com/assets/5442827/18475377/7b659b56-79c6-11e6-8ad7-3f2383d50e2b.png)

I split the editor **in the same window** and the same file is opened in a second pane. 
![2016-09-13 15_27_56-greenshot plugin](https://cloud.githubusercontent.com/assets/5442827/18475677/a67de374-79c7-11e6-93bc-31a517dae36e.png)

Typing in the file in one pane changes the contents of it in the other:
![2016-09-13 15_28_06-greenshot plugin](https://cloud.githubusercontent.com/assets/5442827/18475701/b8b7f692-79c7-11e6-8973-1f50f1779f7b.png)

**Everything is fine and as expected so far**.

I then open a new window.
![2016-09-13 15_36_09-untitled-1 - visual studio code](https://cloud.githubusercontent.com/assets/5442827/18475782/12a98dbe-79c8-11e6-9e98-3e6c073cde7d.png)

And drag the file there:
![2016-09-13 15_36_25-untitled-1 - visual studio code](https://cloud.githubusercontent.com/assets/5442827/18475806/26973916-79c8-11e6-8467-f6bbe95a3581.png)

 If I did not save the file in the previous window, it will now appear without the changes I performed in the new Window:
![2016-09-13 15_40_00-myfile txt - visual studio code](https://cloud.githubusercontent.com/assets/5442827/18475882/633a536c-79c8-11e6-9fd5-69441e486c91.png)

Only when I save the file in the first window, it will get updated in the second one. This applies to any future changes as well. The danger with this is that I might accidentally change the file in both windows in different ways, and then save over one of those changes without realising it.

As this works in other editors (for example Sublime or Visual Studio). There is **no difference** between moving a second "view of a file" to a new pane or a new window, they behave in the exact same way.

With this approach, in my example above all 3 panes would update if I made a change in either of them.

So my question is:

**Is there any plans to support this behaviour** or is this due to some inherent limitation on how VSCode works at the core?

Thanks

**Comment by bpasero** [comment]
Ok got it thanks 👍

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
