### ISSUE TITLE
[Feature Request] Add Fluent Design Theme in VS Code for Windows 10

### ISSUE THREAD

**Issue by feradr** [microsoft/vscode#118645]
First of all I would like to thank this wonderful editor, I use it a lot on Windows and Linux, thank you very much to the project and to the project contributors, I wish only the best for you.

Now about my feature request: the VS Code project could give us a treat for Windows 10, the possibility to apply the Fluent Design White or Dark theme manually or even automatically according to the theme applied in Windows 10, it would be Beautiful with everything Fluent Design ecosystem in conjunction with Windows 10.

**Comment by aeschli** [comment]
We already have the feature to automatically switch the theme based on the OS theme. See setting `window.autoDetectColorScheme`.

You would like to have new 'Fluent' color themes. We currently have no plans to add more built-in theme. 
It would be great id this could be added by an extension.
