### ISSUE TITLE
Broken TypeScript grammar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118640]
On latest Insiders: https://github.com/microsoft/vscode/blob/13070015bddbca61ad566d1abb8aa3ea95edf9cb/src/vs/platform/contextkey/common/contextkey.ts#L1287

![image](https://user-images.githubusercontent.com/22350/110642646-0e370200-8168-11eb-9cca-81cd56bfdd3b.png)

**Comment by mjbvz** [comment]
Tracked in https://github.com/microsoft/TypeScript-TmLanguage/issues/858
