### ISSUE TITLE
Evaluate input to launch config after preLaunchTask

### ISSUE THREAD

**Issue by movl03** [microsoft/vscode#118612]
I have been trying to use a `preLaunchTask` in my launch configuration to execute a shell script which creates a file with information which I need in my launch configuration. I want to retrieve the content of the file using an input variable of the type "command". Unfortunately the `preLaunchTask` appears to be executed after the input variable is evaluated resulting in the use of an old file. Could it be possible to execute the `preLaunchTask` before the evaluation of input variables?

**Comment by weinand** [comment]
Sorry, since the "preLaunchTask" relies on having all variables resolved, we cannot change the order.

But instead of executing the shell script from the "preLaunchTask", you could run it from the command-variable that you have introduced.
