### ISSUE TITLE
Feb version release 1.54 broke ts-code node_modules library

### ISSUE THREAD

**Issue by jelyware** [microsoft/vscode#118600]
Issue Type: <b>Bug</b>

in node_modules/ts-node/src/index.ts:513
   return new TSError(diagnosticText, diagnosticCodes)

TSError: x Unable to compile Typescript

I already updated ts-code version to 9.1.1, and still failing with above error.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.15.0-135-generic

<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.2
vscode-remote-extensionpack|ms-|0.20.0
vscode-eslint|dba|2.1.16
gitlens|eam|11.3.0
docker-explorer|for|0.1.7
vscode-docker|ms-|1.10.0
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
vsliveshare|ms-|1.0.3912
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.33.1
vscode-yaml|red|0.16.0
sonarlint-vscode|Son|1.20.1

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Can you specify how `ts-node` is related to VS Code? 
How are you running it?

**Comment by jelyware** [comment]
Was the typescript library moved in this 1.54 release?  My project's ability to run 'npm run lint' has also been negatively impacted.  Error says typescript library not found.

**Comment by IllusionMH** [comment]
Still not clear what is your setup, what TS installation you are using.
Is it same problem if you are executing these actions from external terminal?

Also not clear how are you performing these actions - are you launching tasks from VS Code integrated terminal, using Run  task or how's it related to VS Code?
