### ISSUE TITLE
file tree view disorder

### ISSUE THREAD

**Issue by xuguruogu** [Microsoft/vscode#11865]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:27:44.726Z)
- OS Version: Darwin x64 15.6.0

![image](https://cloud.githubusercontent.com/assets/6092236/18429108/56c36412-7904-11e6-8c46-7f1c2efac237.png)

**Comment by ramya-rao-a** [comment]
@xuguruogu Can you provide more details?

- Are you using the **vscode-icons** extension or the new File Icon Theme released in 1.5.1?
- Is your issue with the space between the arrow and the folder icon or the alignment?

**Comment by robertohuertasm** [comment]
@xuguruogu this seems like you have the old vscode-icons functionality enabled along with the new File Icon functionality. Try this: F1 > `Icons Disable`. Let me know if it works.

**Comment by xuguruogu** [comment]
@robertohuertasm Thx, it works.

**Comment by xuguruogu** [comment]
The right view comes back when disable icons. 

![image](https://cloud.githubusercontent.com/assets/6092236/18457085/7be1ba80-7988-11e6-9ca6-8305a08583b8.png)

**Comment by ramya-rao-a** [comment]
Closing as resolved
