### ISSUE TITLE
Terminal not working and name is empty

### ISSUE THREAD

**Issue by MaskeZen** [microsoft/vscode#118632]
- VS Code Version: 1.54.1
- OS Version: KDE neon User Edition 5.21 x86_64 (ubuntu 20.4)

When open the terminal panel nothing is displayed and the name of the terminal is empty, ":".

![terminal_not_working](https://user-images.githubusercontent.com/13751832/110633897-1acb5280-8188-11eb-8d1c-32213b4e248e.png)

Steps to Reproduce:

1. open vscode.
2. open terminal tab.

Does this issue occur when all extensions are disabled?: *Yes*

**Comment by MaskeZen** [comment]
This seem to be a problem when I open it from the terminal, like I to do.

`code path/to/repo`

not if I open it from the launcher.

**Comment by meganrogge** [comment]
Are there errors in the dev tools?

**Comment by MaskeZen** [comment]
yes:

`  ERR A system error occurred (EACCES: permission denied, open '/proc/1/environ'): Error: EACCES: permission denied, open '/proc/1/environ'`

There is a clue...

**Comment by MaskeZen** [comment]
Yes... I found that [issue](https://github.com/microsoft/vscode/issues/108369#issuecomment-706602897).

Set `terminal.integrated.inheritEnv` to true in settings seems to solve the problem.
