### ISSUE TITLE
Settings sync disabled because of too many request

### ISSUE THREAD

**Issue by raikusy** [microsoft/vscode#118673]
Issue Type: <b>Bug</b>

I was changing themes to preview and other setttings and suddenly got this message.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (2.41GB free)|
|Process Argv|. --crash-reporter-id d4f608b6-87bc-48d7-b6ec-ea9e88934fff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.2.0
better-comments|aar|2.1.0
vscode-apollo|apo|1.18.2
swagger-viewer|Arj|3.0.1
tailwind-docs|aus|1.4.0
vscode-tailwindcss|bra|0.5.9
vscode-toggle-quotes|Bri|0.3.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.16
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
vscode-pull-request-github|Git|0.24.0
gitlab-workflow|Git|3.14.0
vscode-graphql|Gra|0.3.15
todo-tree|Gru|0.0.203
headwind|hey|1.7.0
fluent-icons|mig|0.0.7
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.10.0
vscode-typescript-next|ms-|4.3.20210309
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
docthis|oou|0.8.2
vscode-yaml|red|0.16.0
LiveServer|rit|5.6.1
mdx|sil|0.1.0
vscode-icons|vsc|11.1.0
gitdoc|vsl|0.0.7
markdown-all-in-one|yzh|3.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

Many others point to #91286
