### ISSUE TITLE
Consider to move vs/workbench/services/extensionRecommendations/common/extensionIgnoredRecommendationsService into workbench/contrib

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118604]
The `vs/workbench/services/extensionRecommendations/common/extensionIgnoredRecommendationsService` seems only used from `contrib` so I suggest to move it into contrib and out of core.

**Comment by sandy081** [comment]
I have the recommendation services all together and one of them is used by multiple contribs. It will be easy if they are all together unless there is a strong reason.

**Comment by bpasero** [comment]
Ok no strong feelings just thought I would bring it up.

**Comment by sandy081** [comment]
No worries. Would prefer existing way.
