### ISSUE TITLE
[Feature] Manually control hover tooltip display

### ISSUE THREAD

**Issue by metal-gabe** [microsoft/vscode#118655]
I'd like to have a setting that allows me to turn off the hover delay and allows me to open the menu/tooltip manually. 

Basically, it would be the same thing as how the `Quick Fix...` keybind/setting works now. 

I would be able to select some text, a method, whatever, perform my keyboard shortcut, and then if there's something to display, the tooltip shows up. 

![hover-01](https://user-images.githubusercontent.com/53348382/110664904-b35bd580-817c-11eb-8c1c-023da4c3a813.png)
![hover-02](https://user-images.githubusercontent.com/53348382/110664909-b48d0280-817c-11eb-95ae-e4cdcf7ed809.png)

**Comment by jrieken** [comment]
There are these settings

<img width="868" alt="Screenshot 2021-03-11 at 09 06 58" src="https://user-images.githubusercontent.com/1794099/110755356-2468bf00-8249-11eb-973b-ff0f0a2d453b.png">

**Comment by jrieken** [comment]
And this command

<img width="800" alt="Screenshot 2021-03-11 at 09 07 33" src="https://user-images.githubusercontent.com/1794099/110755422-3c404300-8249-11eb-84af-b9f62139dd6d.png">
