### ISSUE TITLE
Opening VS Code with administrator privileges causes window crash

### ISSUE THREAD

**Issue by lor3k** [microsoft/vscode#118641]
- VS Code Version: 1.54.1 (the same with 1.55.0-insider)
- OS Version: Windows 10 Enterprise

Steps to Reproduce: 

1. Opening VS Code with administrator privileges causes window crash for 10-15 seconds, then prompt "The window has crashed".
2.  _Reopen_ button click opens window immediately.

Info:
1. It seems irregular - first VSC opening and sometimes further window openings. 
2. I uninstalled all extensions, tried with "files.hotExit": "off", "window.restoreWindows": "none", also with/without internet connection - but it doesn't matter for this error - still exists.
3. I suppose problem has appeared ~ 2 months ago.

Does this issue occur when all extensions are disabled?: **Yes**

<img src="https://user-images.githubusercontent.com/33831537/110643464-6ac00e80-81b4-11eb-8c0d-7f05cf2f754b.PNG" width="700px"/>

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash reports. Thanks!

**Comment by lor3k** [comment]
Here they are:
[fcd25ca2-6cc8-45a4-afc3-9ad570051182.zip](https://github.com/microsoft/vscode/files/6121901/fcd25ca2-6cc8-45a4-afc3-9ad570051182.zip)

**Comment by deepak1556** [comment]
Thanks for the report, the process was crashed because it remained unresponsive. Based on the stack trace, the main thread was blocked on trying to establish a communication channel to the gpu process. There is something I would like to try before further debugging, can you launch the app with `--disable-gpu` and see if the crash happens.

**Comment by lor3k** [comment]
I can't reproduce this error with `--disable-gpu` flag. Everything is working fine, also in **VS Code-Insiders**

**Comment by Tr-st-n** [comment]
Highly doubt anyone who gets this far would not have tried this, but, make sure after using Windows to "force" VS Code to be launched as Admin, you close down all your VS Code instances (before trying to open new ones). Worked for me.

**Comment by mattiaskagstrom** [comment]
Mine simply closes without error when running as admin.
[VsCodeCrash.zip](https://github.com/microsoft/vscode/files/9849622/VsCodeCrash.zip)

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/118641#issuecomment-797364471
