### ISSUE TITLE
Switching branches invalidates Explorer view

### ISSUE THREAD

**Issue by iqapps** [microsoft/vscode#118699]
Having a workspace open and then switching to another branch not having the opened workspace, the explorer switches to the "no workspace"m ie a bad state, which is expected.

But when switching back to the previous branch having the workspace, and trying to open workspace from file/open_recent, you cannot get the explorer out of the bad state.

The expected behaviour is to get back to the workspace as before the first branch switch.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (19.50GB free)|
|Process Argv|--crash-reporter-id 937b32ac-d42d-4d5c-8600-a5390f81789c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-color-pick|ada|0.6.2
vscode-base64|ada|0.1.0
Bookmarks|ale|13.0.3
ignoregit|And|1.0.1
code-gnu-global|aus|0.2.2
css-theme-completions|con|0.0.4
doxdocgen|csc|1.1.0
xml|Dot|2.5.1
gitlens|eam|11.3.0
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.5
hex-fmt|ker|1.0.0
quick-notes|Lia|1.8.0
linecounter|lyz|0.2.7
git-graph|mhu|1.29.0
csharp|ms-|1.23.9
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.4.0
powershell|ms-|2021.2.2
vsonline|ms-|1.0.3076
text-power-tools|qcz|1.21.0
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.8.1
vscode-multiclip|sle|0.1.5
vscode-arduino|vsc|0.3.5
clang-format|xav|1.9.0
hex-ascii-converter|yrp|0.0.1
vscode-asciiflow2|zen|0.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by isidorn** [comment]
We probably did not write code to catch this case.
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
