### ISSUE TITLE
"File" > "New File" results in "New Window" when VS has not the focus on a Mac

### ISSUE THREAD

**Issue by tonsnoei** [microsoft/vscode#118621]
Issue Type: <b>Bug</b>

1. Use a OSX device with multiple screens (e.g. MacBook)
2. Open VS Code on the primary screen
3. Open a folder in VS Code.
4. Now put the focus on another Mac application on one of the secondary screens.
5. Click in the VS Code menu of the primary screen "New File"
6. VS Code act as if "New Window" was pressed.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id e0f8e46c-5ad7-4eb5-bb83-a11c02a98ac4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.2.4
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.16
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.16
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|5.9.2
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
todo-tree|Gru|0.0.202
name-that-color|gui|0.1.4
search-node-modules|jas|1.3.0
plantuml|jeb|2.14.3
vscode-styled-components|jpo|1.5.0
rn-full-pack|kel|0.7.0
regionfolder|map|1.0.12
vscode-language-babel|mgm|0.0.30
vscode-docker|ms-|1.10.0
vscode-typescript-next|ms-|4.3.20210308
vscode-react-native|msj|1.4.0
color-highlight|nau|2.3.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.16
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
code-spell-checker-dutch|str|0.2.6
iconfont-preview|stx|0.0.4
highlight-matching-tag|vin|0.10.0
gitblame|wad|6.0.2
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by bpasero** [comment]
I wonder if doing so would break other flows where people expect a new window? It is actually something I am not entirely sure what to do best... Would be also interesting to see how any other native macOS app behaves here if possible.

**Comment by sbatten** [comment]
I don't have multimon mac setup at home to verify with other apps.

perhaps @tonsnoei could test a few apps with their setup?

**Comment by tonsnoei** [comment]
I tested the behavior with the Firefox browser on my multi-screen Mac. Firefox behaves correctly (IMHO). I tested the difference between opening "New Tab" (similar to New File in VS Code) and opening a "New Window" (similar to New Window in VS Code). Firefox opens a new tab correctly within one of the open FireFox windows.
