### ISSUE TITLE
Visual Studio Code wrongly highlights char pointer as being an incompatible parameter with winapi's LPWSTR. 

### ISSUE THREAD

**Issue by Vasil-Kirov** [microsoft/vscode#118650]
- VS Code Version: 1.54.1
- OS Version: Windows 10 Insider Preview 10.0.21327.1010 (rs_prerelease)

Steps to Reproduce:

1. Simply type in the function in the image I provided with the same parameter.

Does this issue occur when all extensions are disabled?: Yes

![VisualStudioCodeBug](https://user-images.githubusercontent.com/72518143/110659156-fe9cd500-81ca-11eb-8066-99d1fa941207.png)

In my command prompt you can see how I have compiled the file with no errors, even though VSCode is showing an error.

I believe this has happened with other similar typedef data types but this is the one that stood out the most because fixing it in VSCode with a cast actually resulted in not being able to compile.

**Comment by Vasil-Kirov** [comment]
> /extCpp
> 
> VS Code doesn't support C++ out of the box so this functionality and error comes from extension.

Weird because I ran it with --disable-extensions and still showed up. maybe I messed something up.

**Comment by IllusionMH** [comment]
If you clicked on button in this notification of performed Reload Window - extensions will be restored.
![image](https://user-images.githubusercontent.com/1312662/110661840-9f8c8f80-81cd-11eb-8d73-f2be0739719c.png)

There is built-in extension that provides default highlights, snippets, folding, however not type checks etc.
https://github.com/microsoft/vscode/blob/3ac310d1cf937e0c7bf82e6cb01df1f15c094f03/extensions/cpp/package.nls.json#L3
