### ISSUE TITLE
Invalid keyboard bindings file causes editor to not load

### ISSUE THREAD

**Issue by mikegoatly** [Microsoft/vscode#11868]
- VSCode Version: 1.5.1
- OS Version: Windows 10 Pro build 14393.105

Steps to Reproduce:

1. Overwrite everything in your keyboard bindings file with this (i.e. without the array brackets):
{"key": "ctrl+shift+alt+F", "command": "stylefmt", "when": "editorTextFocus"}

2. Try to open VS code - the editor fails to load and you end up with a blank window.

Expected outcome: The editor should still load and I should be informed that my keyboard bindings are invalid and have been ignored.

**Comment by bpasero** [comment]
I can reproduce.
