### ISSUE TITLE
VS Code crashes during debugging whenever I hit play

### ISSUE THREAD

**Issue by damckinn-microsoft** [microsoft/vscode#118671]
Issue Type: <b>Bug</b>

I have a known working program, which I am debugging. No matter where I put a breakpoint, two things always happen:
1. VS Code takes at least 30 seconds to break on this and load locals
2. When I hit play, after inspecting things, the program dies. Anywhere the breakpoint is. 
This program does not crash on its own, it runs fine. I have stepped through this program before, and others can do it right now. But I can't play after hitting a breakpoint, and it takes far too long to load locals

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.21327

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz (36 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (29.19GB free)|
|Process Argv|--crash-reporter-id e2f024d7-04c0-4e32-ba7e-da62379116cf|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by weinand** [comment]
What debugger are you using?

**Comment by damckinn-microsoft** [comment]
"configurations": [
        {
            "name": "Debug",
            "type": "cppvsdbg",
            "request": "launch",

**Comment by damckinn-microsoft** [comment]
@weinand I disagree that it is the c++ extension, since others who have this working are using the same extension, but I will file there
