### ISSUE TITLE
Save before formatting code

### ISSUE THREAD

**Issue by WeebNetsu** [microsoft/vscode#118662]
I would like if VSCode can save the code **before** formatting it, I have a relatively slow laptop and it sometimes takes up to 10 seconds to format code less than 10 lines, it can get quite annoying and forces me to disable the format on save feature. There was a closed duplicate, I was hoping this one will have a better chance of getting seen.

**Comment by jrieken** [comment]
> it can get quite annoying and forces me to disable the format on save feature. 

If you save before formatting you are basically disabling format on save. Which makes me wonder what you are asking for?

**Comment by WeebNetsu** [comment]
> If you save before formatting you are basically disabling format on save. Which makes me wonder what you are asking for?

I want it to save the code before it formats it, so:
Save -> Format
Instead of
Format -> (wait 5-10 seconds) -> Save

It can be confusing to press ctrl+s and try to run the application (from the terminal) and then seeing no difference (because I ran it while it was formatting and it hasn't gotten to saving it yet)

**Comment by jrieken** [comment]
And when formatting is done, what should happen then? Save again? Keep the file dirty?

**Comment by WeebNetsu** [comment]
:/
I just wanted an option you can tick that said "save before format" so my slow computer can save the file and while I execute the file it can format it instead of me forgetting that it is being formatted and hasn't saved yet and execute the old version...
But I understand where you're coming from, if you save before formatting then when you open it up again later you'll have to format it first...

Thank you for the help tho

**Comment by jrieken** [comment]
I think the really issue is that formatting is so slow for you. You should reach out to the extension that does formatting and see how they can improve performance
