### ISSUE TITLE
WinSCP open files in VSCode but don't show VSCode window

### ISSUE THREAD

**Issue by ro78** [Microsoft/vscode#11867]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Define VSCode as default WinSCP editor
2. Open any file from WinSCP - file is opened and VSCode window is displayed
3. Keep VSCode open and open another file from WinSCP - file is opened but VSCode window is not displayed (stays in background, WinSCP remain the opened window).

I've checked issues #159 and #167 but can't fix this problem.

Romain

**Comment by bpasero** [comment]
Looks like https://github.com/Microsoft/vscode/issues/929
