### ISSUE TITLE
Stuck on Initializing JS/TS language features

### ISSUE THREAD

**Issue by nfantone** [microsoft/vscode#118643]
Issue Type: <b>Bug</b>

After upgrading to `1.54.1` (2021-03-04) some of my workspaces are now permanently stuck on "Initializing JS/TS language features" upon firing VSCode up. I say "some" because I noticed that, for me, it's only happening on monorepos with a nested `packages/` directory with multiple `package.json` files.

- Deleting all `node_modules` within the project **does not solve the issue**.
- `--disable-extensions` **does not solve the issue**.
- Reverting back to previous VSCode version **makes the issue go away**.
- CPU and RAM usage seems normal.
- I am using `yarn` `2.4.1`.
- Some of my packages define `"exports"` in `package.json`. 

Here's the [full `tsserver.log`](https://pastebin.com/5sp553m9).

I don't see any obvious errors or warnings in there, though.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (16.89GB free)|
|Process Argv|--disable-extensions .|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by mjbvz** [comment]
Can you share a project that seems to cause this issue? It looks like the server could be freezing because the logs look incomplete

**Comment by nfantone** [comment]
@mjbvz Ok, while trying to put together a fresh project to reproduce the issue I ended up narrowing it down to certain settings in `.vscode/settings.json`.

```json
"typescript.disableAutomaticTypeAcquisition": true
```

As soon as I remove that (or set it to `false`) and reload Code, the "Initializing JS/TS language features" spinner completes as expected.

**Comment by mjbvz** [comment]
I can't reproduce this even with that setting disabled. Can you please share a minimal project that seems to cause this?

**Comment by adjenks** [comment]
https://github.com/microsoft/vscode/issues/109847
