### ISSUE TITLE
Double badge on gear icon looks off

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118682]
I have an update pending, and also "manage workspace trust", seems like it's trying to show both badges

![image](https://user-images.githubusercontent.com/323878/110718666-4ff39700-81c0-11eb-9f36-c5683c4ddc38.png)

![image](https://user-images.githubusercontent.com/323878/110718707-613ca380-81c0-11eb-956a-8a68b037ac57.png)

**Comment by roblourens** [comment]
Actually I don't know why the trust badge shows up, because the workspace is already trusted

![Uploading image.png…]()

**Comment by roblourens** [comment]
Running Insiders from a couple days ago, when we updated Insiders this afternoon.

**Comment by roblourens** [comment]
Remember that we missed builds for a couple days so if you fixed it this week, probably missing the fix

**Comment by gjsjohnmurray** [comment]
> Actually I don't know why the trust badge shows up, because the workspace is already trusted
> 
> ![image](https://user-images.githubusercontent.com/323878/110718779-79142780-81c0-11eb-8724-9ab1bba97066.png)

@sbatten typo in that message: inheret -> inherit

**Comment by sbatten** [comment]
if this bug is still out, this will likely repro again since we update so often, I'll keep my main repo in unknown for a while to get this to repro.

@gjsjohnmurray thanks, I've since replaced that whole message in insiders

**Comment by sbatten** [comment]
the double badge has not occurred for me since this issue was opened and my folder is consistently in the unknown state to encourage both badges. please re-open if you still see it.
