### ISSUE TITLE
Menu icons are not shown in light type color themes

### ISSUE THREAD

**Issue by cpsdev** [microsoft/vscode#118609]
Issue Type: <b>Bug</b>
This extension needs to be installed:
https://marketplace.visualstudio.com/items?itemName=Autodesk.hsm-post-processor

With the Jan2021 update menu icons disappeared in light type color themes. 
![image](https://user-images.githubusercontent.com/9111243/110598189-c329e880-8181-11eb-88d2-20441d802e82.png)

In previous versions icons were shown with no issues:
![image](https://user-images.githubusercontent.com/9111243/110598351-efde0000-8181-11eb-94ef-5f4e3ea1dba3.png)

Seems that only the icon is not shown, tooltips are there. 

When you switch to any dark type theme, icons are shown as desired:
![image](https://user-images.githubusercontent.com/9111243/110598430-05532a00-8182-11eb-8cae-aa9bdccc6468.png)

Same problem with latest insiders version.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.57GB free)|
|Process Argv|--crash-reporter-id 1e770513-f2a6-42fd-9fa3-ae054a0d9f32|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
The action item references `var(--menu-entry-icon-light)`, but only `--menu-entry-icon-dark` is defined 

Repro steps: install the extension above, switch to light theme, move the mouse at the `CNC Selector` header in the explorer

**Comment by aeschli** [comment]
Extension defines:
```
		{
				"command": "cncList.addFolder",
				"title": "Add folder",
				"icon": "res/icons/add.svg"
			},
```
The icon we create will only have `dark` set: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/menusExtensionPoint.ts#L542

**Comment by jrieken** [comment]
@cpsdev I have pushed a fix which will be in next insiders. You can actually workaround this on your end by defining the command icons explicitly for dark and light themes

**Comment by cpsdev** [comment]
@jrieken WOW, that was quick, excellent! Thanks a lot for that quick fix! 
Can you pls tell me how i can define it for the two different themes?

**Comment by jrieken** [comment]
The `icon` property can be a string or an object, like so 

```json
"command": "cncList.addFolder",
"title": "Add folder",
"icon": {
	"dark": "res/icons/add.svg",
	"light": "res/icons/add.svg"
}
```

**Comment by cpsdev** [comment]
Superb! Thanks again! Very impressive!
