### ISSUE TITLE
Gutter icon: Refused to load resource

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#118623]
In **1.54** custom gutter icon stopped working. I don't see anything in release notes that would indicate what kind of feature this is (Result of work on Sandbox?).
```
[error] file: Refused to load resource c:\add.svg from file: protocol (original URL: file:///C:/add.svg)
```

1. Create a text editor decoration with `gutterIconPath` set it as a string to local file path `"errorLens.errorGutterIconPath": "C:\\add.svg"`
2. It's not loaded

Icons in extension directory are loaded without problems. Only outside files refuse.

This was working from vscode version maybe **<1.20** to **>=1.53**.

**Comment by bpasero** [comment]
@usernamehw this is an extension providing that setting? As part of our sandbox effort we start to block resources that are outside these locations for security reasons:
* installation dir
* extensions dir
* user data dir

It is rather unlikely we would relax this restriction going forward.

//cc @deepak1556

**Comment by usernamehw** [comment]
> this is an extension providing that setting?

Yes. Just a minor feature.

It's just a breaking change that doesn't seem to be in the release notes. The only issues I was able to find with this description are the ones about webviews.

Right now the workaround is to copy those files using NodeJS `copyFile()` into extension directory. Is sandboxing endgame going to prevent me doing that?

**Comment by bpasero** [comment]
@usernamehw yeah I actually forgot to document that. As an extension you will have full node.js API access even when sandbox is enabled, nothing changes for extensions.

**Comment by usernamehw** [comment]
Ok. Closing then.

**Comment by alefragnani** [comment]
Hi @bpasero ,

What if the extension is updated? Wouldn't you lose the _copied resources_ because the older release will be deleted after you restart VS Code? Or will VS Code leave these files there, because aren't from the original `vsix` file?

I guess in this case we should use `context.globalStorageUri`, which is _"a directory in which the extension can store global state"_ . 

Thank you

**Comment by bpasero** [comment]
Yes, use `context.globalStorageUri`, it will be accessible within VSCode.
