### ISSUE TITLE
SCM view with multiple repositories has multiple Expand/Collapse All buttons

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#118660]
Issue Type: <b>Bug</b>

1. Clone microsoft/vscode-extension-samples.
2. Open the source-control-sample folder.
3. Build and run the extension.
4. Follow the README instructions to create a single source control provider.
5. Repeat step 4 to add a second folder to the workspace, which adds a second source control provider.
6. Observe that the Expand / Collapse All button appears three times.

![image](https://user-images.githubusercontent.com/6726799/110674682-09a33580-81ca-11eb-9139-d2c50fcd225c.png)

I don't think it used to do this. Perhaps a consequence of this commit by @joaomoreno which first shipped in 1.54

https://github.com/microsoft/vscode/commit/2402c94e8ea806c9f85bd4a135a065ac779bd550

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

**Comment by joaomoreno** [comment]
@eamodio This is due to my refactorings from last month, let me know if you want me to jump on it.

**Comment by eamodio** [comment]
Sure if you don't mind - thanks!

**Comment by gjsjohnmurray** [comment]
How about keeping the extra expand/collapse buttons but make them act on only their SourceControl rather than on all SourceControls?

For bonus points, maybe add 'alt'-command variants that make the expand/collapse operation recursive. In my SourceControlProvider I add a varying number of ResourceGroups, each of which can have many ResourceStates. When I add the ResourceStates the tree expands automatically. If one alt-click on Collapse let me collapse all ResourceGroups as well as collapse the SourceControl, then a single regular click on the button (now called Expand) would reveal tthe ResourceGroup nodes in their collapsed state (i.e. hiding all their ResourceStates). And since https://github.com/microsoft/vscode/pull/116211 merged the alt-variants of command buttons are now more discoverable.

🙏

**Comment by joaomoreno** [comment]
I think it's fine to just fix the issue for now and make it appear only once.

The `alt-` variations already work if you click the tree node while holding `alt-`.
