### ISSUE TITLE
 open a certain plugin by default when you enter vscode

### ISSUE THREAD

**Issue by ZMRWEGO** [microsoft/vscode#118691]
Each time i enter vscode, open a certain plugin by default. Is there currently support for this? 
Is it possible to modify some configurations of the plug-in to meet this requirement?

**Comment by TylerLeonhardt** [comment]
The extension author should take a look at our docs on [Activation Events](https://code.visualstudio.com/api/references/activation-events). The best one to use for this scenario is: `onStartupFinished` because it won't slow down VS Code, but it will activate the extension once VS Code is ready.
