### ISSUE TITLE
Select language in empty file is duplicated on debug sessions

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#118694]
![image](https://user-images.githubusercontent.com/35271042/110740738-644b8a00-81e8-11eb-942b-3b4784b69ee5.png)

Steps to Reproduce:

1. Start a debug session 
2. Create a new file
3. Restart debug session
4. 🐛  The "select a language" is shown twice

**Comment by isidorn** [comment]
Thanks for nice steps but I can not reproduce with them
@sandy081 is also seeing this, so there is definitely something going on. I will try to look into the code to figure out how this could theoretically happen, and if someobdy gets steps that repro 100% of the time let me know. Thanks!

**Comment by isidorn** [comment]
I can reproduce this - thanks @sandy081 

Steps:

1. New untitled file, type something
2. Set language mode to some language (for example Python)
3. Reload (do not save the untitled file)
4. Button is rendered on first line 🐛

**Comment by isidorn** [comment]
Pushed a fix for this, please let me know if you still see this.
