### ISSUE TITLE
The new icon does not look good, it's less distinctive and the actual VSCode logo is smaller and harder to see

### ISSUE THREAD

**Issue by Yzrsah** [microsoft/vscode#118688]
- VS Code Version: Insiders
- OS Version: macOS

<img src="https://i.imgur.com/tYwMPZa.png"></img>

The new icon looks much worse than the old icon.

- Now there's a white rounded square background.
- The white rounded square serves no other purpose than to force the actual real VSCode icon to be smaller, less detailed, less distinct.
- The blue/green VSCode logo is now so small that you might as well convert it into a single color because the shadowing effect has been damaged. Inevitable, huh?
- The new logo therefore effectively becomes the shape of the white rounded square contrasting against the blue/green VSCode logo which is the "hole" in the logo.
BUT
- This white rounded square has nothing to do with VSCode logo design, it's a design from someone else's brand.
- Therefore someone hijacked your design and took over the shape of your logo.

What is lost:
- A nice big distinctive icon.
- Clarity of the shadowing and 3D effect.

What is gained:
- It is more generic and average.
- We benefit from having a white rounded square so we can be more like the other companies.

**Thanos snaps the detail out of every icon:** https://www.youtube.com/watch?v=DX0SUm1Uupw

But this new VSCode icon takes snapping the detail out of every icon to a new level of meta, because the logo isn't just simplified, it now has to be simplified even further in order to fit it inside someone else's frame.

It seems like they're trying to make the VSCode icon look like the XCode icon. I don't think Microsoft should try to copy Google and Apple on everything.

**Comment by misolori** [comment]
Thanks for the feedback, please see https://github.com/microsoft/vscode/issues/101014 and [our explanation](https://github.com/microsoft/vscode/issues/101014#issuecomment-791624535), which follows the [Apple's app icon guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/).
