### ISSUE TITLE
Open Recent goes to wrong workspace from remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118683]
I have `vscode-github-issue-notebooks` on an SSH remote and also locally. Both should be in Recently Opened. I have a remote window open. From that remote window, I see three entries:

![image](https://user-images.githubusercontent.com/323878/110719755-3fdcb700-81c2-11eb-9efb-798dee5971dc.png)

which look like the local one. If I pick one, it opens a window on that remote, but with the local path.

From a local window, I see this

![image](https://user-images.githubusercontent.com/323878/110719861-73b7dc80-81c2-11eb-8c6b-9f0f80338464.png)

which is correct, and opening either does the right thing.

**Comment by bpasero** [comment]
@roblourens remote is owned by @aeschli
