### ISSUE TITLE
Extension search can't find all extensions

### ISSUE THREAD

**Issue by Rafii2198** [microsoft/vscode#118681]
Issue Type: <b>Bug</b>

When I search for extensions for example Quokka.js (I have this one installed manually via .vsix) or Live Share (I doesn't have it installed) and many other, the search shows me no results. Even when I used command to install it (e.g ext install MS-vsliveshare.vsliveshare - it comes from the website itself) it opened the search and told me again that it couldn't be found.
It is happening when launching with all extensions disabled and even on fresh install of vs code.

VS Code version: Code - OSS 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T21:13:58.622Z)
OS version: Linux x64 5.11.1-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600X Six-Core Processor (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.34GB (22.63GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.1.4
cweijan-personal-material-icon-theme|cwe|5.0.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|5.9.2
comment-anchors|Exo|1.9.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.22.0
live-sass|gle|4.4.1
discord-vscode|icr|5.4.0
vscode-github|Kni|0.30.4
python|ms-|2020.10.332292344
debugger-for-chrome|msj|4.12.6
vscode-css-peek|pra|4.1.0
LiveServer|rit|5.6.1
sass-indented|syl|1.8.16
quokka-vscode|Wal|1.0.343

(1 theme extensions excluded)

</details>

**Comment by Rafii2198** [comment]
To be more precise: Searching for example Live Share it will show me some random stuff that doesn't exactly match what I have searched. And it is searching for like a minute
![image](https://user-images.githubusercontent.com/26695327/110718894-29f3e400-820c-11eb-880d-33979eb3b796.png)
And using command will again do something for few seconds, then it will show me message to press Enter to search it 
![image](https://user-images.githubusercontent.com/26695327/110719112-8bb44e00-820c-11eb-8fa4-83e3ede53d4a.png)
And then the search results are even less accurate
![image](https://user-images.githubusercontent.com/26695327/110719198-b30b1b00-820c-11eb-81ab-2c403373daaf.png)

**Comment by gjsjohnmurray** [comment]
/duplicate

Manjaro package uses Open VSX for its extensions instead of Marketplace
