### ISSUE TITLE
Intellisense 

### ISSUE THREAD

**Issue by agryashu23** [microsoft/vscode#118648]
Issue Type: <b>Feature Request</b>

HTML intellisense function function is not working in my vs code. It shows no suggestions while working on html file

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
Is the mode of your editor `HTML`? (see in the status bar).

If yes, can you share a small code sample and a screenshot?
