### ISSUE TITLE
Install failure error message should not appear in all windows

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#118797]
Please see the screenshot below

![image](https://user-images.githubusercontent.com/172399/110904826-d667c000-8309-11eb-83fc-7a0014175a60.png)

**Comment by joaomoreno** [comment]
@egamma This is a notification from the LiveShare extension, not our core. I would file them an issue, but I think they can't fix it since there are 3 extension host instances, they do not communicate between each other.
