### ISSUE TITLE
Downloading an extension with no home disk space results in unrecoverable error

### ISSUE THREAD

**Issue by LucienMP** [microsoft/vscode#118711]
Issue Type: <b>Bug</b>

Downloading an extension with no home disk space results in unrecoverable error.

My home /home/lucienmp was about down to 5MB when I tried to install the C++ extensions.  After attempting this I was met with a "Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found" type of message.

Clearing up some home disk space didnt help.

I had to clean out ~/.config/Code/Cache* folders and restart.

This seems a failure to check the installed plugin size before attempting a download / or install.

Then partially install some junk, and enter an unrecoverable situation.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 3.10.0-1160.15.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (4 x 4007)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|22.88GB (1.10GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 58c9747e-11be-4ff5-83b6-8e88bcdda34e|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
systemverilog|eir|0.11.3
language-cmm-vscode|kho|1.2.0
cpptools|ms-|1.2.2
makefile-tools|ms-|0.2.0
veriloghdl|msh|1.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464

```

</details>

**Comment by sandy081** [comment]
/duplicate

There is already an issue to remove the downloaded vsix from the cache if it is corrupted.
