### ISSUE TITLE
M1 Mac is heating when using Universal version VScode

### ISSUE THREAD

**Issue by FutureMathematician** [microsoft/vscode#118704]
- VS Code Version: 1.54.1
- OS Version:  11.2.3 (M1)

Steps to Reproduce:

1. Open VScode
2. Wait 2 minutes
3. Touch the 'MacBook Air' logo

Does this issue occur when all extensions are disabled?: No, when I disable ms-python.python

**Comment by deepak1556** [comment]
> Does this issue occur when all extensions are disabled?: No, when I disable ms-python.python

Do you mean the cpu usage is normal when the python extension is disabled ?

**Comment by FutureMathematician** [comment]
Yes, I'm pretty sure ms-python.python extension is the problem.

**Comment by deepak1556** [comment]
Can you paste the output from devtools.

I would suggest to open the issue with python extension. It would help the extension authors if you can attach some cpu profile.

* Disable all extensions except python
* Follow https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions to get the profile

**Comment by FutureMathematician** [comment]
I've already put an issue on the python extension project, cool
