### ISSUE TITLE
Haxe support is broken since version 1.53

### ISSUE THREAD

**Issue by arethk** [microsoft/vscode#118752]
Issue Type: <b>Bug</b>

I'm able to use Haxe with no issues in version 1.52.1-1608137084.el7 but as soon as I update with yum, haxe stops working. I just tried version v1.54 and the entire app locked up. I ran the top command and vs code was running at 100%+ cpu. Something is up. I'm using haxe version 4.1.3. You can see the installed extensions I am using below. I am on the latest CentOS 7 as of todays date.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 3.10.0-1160.15.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 3140)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|31.01GB (21.74GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 4d2b94ce-65bd-4cf8-93bc-a21ec77d53bb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
haxe-hl|Hax|1.1.1
formate|Mik|1.1.6
vshaxe|nad|2.22.1
haxe-debug|vsh|1.2.3
haxe-extension-pack|vsh|1.3.0
hxcpp-debugger|vsh|1.2.4
vscode-meteor|vuh|0.1.1
codedox|wig|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30270786

```

</details>

**Comment by TylerLeonhardt** [comment]
Let's start in the extension issue and go from there. Perhaps the extension author can provide more context as to how the haxe extension uses VS Code APIs.

**Comment by gjsjohnmurray** [comment]
Maybe because you are on CentOS 7, and starting with 1.53 VS Code is no longer compatible.
