### ISSUE TITLE
Emmet CSS expand doesn't work for Handlebars style blocks

### ISSUE THREAD

**Issue by evenfrost** [microsoft/vscode#118714]
- VS Code Version: 1.54.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open/create a Handlebars file.
2. Add `style` tag.
3. Input some Emmet CSS abbreviation and try to expand.
4. Fail.

Emmet HTML abbreviations in Handlebars files work fine.

See HTML vs Handlebars example:

![emmet-hbs-bug](https://user-images.githubusercontent.com/3055750/110777818-9bff1400-8272-11eb-910c-b5dadf2275b8.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by abhijeet75** [comment]
@rzhao271 I think I have found the issue. In `defaultCompletionProvider.ts::provideCompletionItemsInternal`, we check `document.languageId == "html"`, we should be checking `syntax == "html"` instead. I will raise a PR.
