### ISSUE TITLE
Duplicate tab option / command

### ISSUE THREAD

**Issue by jakevossen5** [microsoft/vscode#118791]
Sometimes when working on a file, I quickly want to open up a second tab to view the document in two places at the same time. If I could open the command pallet (or right click on the tab) and say "duplicate tab", it would save me from having to find it in the left hand side again.

**Comment by jakevossen5** [comment]
After some expierementation, cmd + p -> cmd + enter does what I want, but I still feel like "duplicate tab" is a reasonable feature to have

**Comment by bpasero** [comment]
We have a limitation in tabs that the same file cannot be opened more than once in an editor group so this is unlikely to happen.
