### ISSUE TITLE
In Markdown file , Mouse right click menu doesn't respond

### ISSUE THREAD

**Issue by arjunelabs** [microsoft/vscode#118795]
Issue Type: <b>Bug</b>

In latest version of VScode , if opens a .md file and right click using mouse, after many times of clicking it responds to once and displays the menu. As I am using Ubuntu 20.04. Please fix this bug.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 1353)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.72GB (3.27GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 44b4f2da-9746-4f84-b559-1649e556b777|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.3
color-info|bie|0.5.1
emojisense|bie|0.8.0
markdown-checkbox|bie|0.1.3
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.6.3
multi-cursor-case-preserve|Car|1.0.5
json-tree-view|Cha|2.6.0
bracket-pair-colorizer|Coe|1.0.61
vscode-mysql-client2|cwe|3.6.0
vscode-markdownlint|Dav|0.39.0
vscode-quick-select|dba|0.2.9
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|5.9.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.24.0
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.204
vscode-auto-open-markdown-preview|hnw|0.0.4
path-autocomplete|ion|1.17.1
kite|kit|0.142.0
Kotlin|mat|1.7.1
rainbow-csv|mec|1.8.1
template-string-converter|meg|0.4.7
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
JavaScriptSnippets|nat|0.2.0
indent-rainbow|ode|7.5.0
advanced-new-file|pat|1.2.2
vscode-php-getters-setters|php|1.2.3
polacode|pnp|0.3.4
vscode-css-peek|pra|4.1.0
LiveServer|rit|5.6.1
px-to-rem|sai|1.3.1
svg-preview|Sim|2.8.3
vsc-quokka-statusbar|ske|1.3.6
default-keys-windows|smc|0.0.7
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.2.8
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.1.0
codetour|vsl|0.0.46
gistfs|vsl|0.2.2
quokka-vscode|Wal|1.0.349
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
eno|Wsc|2.3.53
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465
vsfjg287:30270788

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by arjunelabs** [comment]
Thanks for your reply. As I used start-bisect command, in 4th or 5th iteration , it shows 8 extensions are bad. After 7th iteration the start-bisect command stopped and it showed this message "Extension bisect is done but no extension has been identified. This might be a problem with code". And magically after restart, the problem solved, there is not even a disabled extension and I am happy. I dont know what happens but it worked for me. Now as I right-click the mouse button, the menu appears in one click. **Start Extension bisect command** is very helpful command.
