### ISSUE TITLE
Hope to strengthen the native debugging features of vsocde combined with gdb

### ISSUE THREAD

**Issue by altair-kilin** [microsoft/vscode#118709]
Can vscode support more gdb features, just like a real gdb GUI. For example, when I want to debug the self-compiled clang-debug, it is not convenient to use the gdb command line to watch the source code and variables. I prefer a light editor like VScode to an IDE like CLion. Besides, I don’t want to Perform code compilation before debugging. In some cases, I don't have source code.

**Comment by weinand** [comment]
VS Code doesn't know anything about clang or gdb. Please file this feature request against the (debugger) extensions related to clang or gdb.
