### ISSUE TITLE
Permission for microphon

### ISSUE THREAD

**Issue by HoBu23** [microsoft/vscode#118768]
missing permission for microphon an mac big sur

**Comment by TylerLeonhardt** [comment]
Can you provide a bit more of an explanation? Perhaps a screenshot?

/needsMoreInfo

**Comment by yume-chan** [comment]
#95062 ?

**Comment by TylerLeonhardt** [comment]
Yeah, I think you're right @yume-chan. Dupe of #95062

**Comment by HoBu23** [comment]
> Yeah, I think you're right @yume-chan. Dupe of #95062

Thank's @yume-chan . for your link :)
