### ISSUE TITLE
Unable to establish SSL connection

### ISSUE THREAD

**Issue by pengzhen80** [microsoft/vscode#118778]
Connecting to vscode.cdn.azure.cn (vscode.cdn.azure.cn)|116.162.88.66|:443... connected.
 Unable to establish SSL connection.

**Comment by nimula** [comment]
I've the same problem since yesterday.

**Comment by TylerLeonhardt** [comment]
duplicate of https://github.com/microsoft/vscode-remote-release/issues/4648 this should be fixed now. Please give it another go.
