### ISSUE TITLE
EULA ID dated 2018 in 1.54.2 installer (downloaded today)

### ISSUE THREAD

**Issue by PDeBonte** [microsoft/vscode#118787]
Issue Type: <b>Bug</b>

### Steps to Reproduce
1. Go to the ["Download Visual Studio Code"](https://code.visualstudio.com/Download) page
2. Click the Windows button (= User Installer) or the "System Installer" "64 bit" button
3. Receive and launch "VSCodeSetup-x64-1.54.2.exe"
4. When the EULA is displayed, scroll to the bottom
5. Note on the last line: "EULA ID: Visual Studio Code 14 November 2018"
 
### Analysis

- With the exception of formatting and trivial URL changes (e.g. master vs. main in the GitHub URL and http vs. https in some other URLs), the installer EULA seems to be a match to [latest EULA on the website](https://code.visualstudio.com/license), which is required to download the installer ("By downloading and using Visual Studio Code, you agree to the license terms and privacy statement.")
- In contrast, it seems much less similar to a [2018-11 EULA that I found on Archive.org](http://web.archive.org/web/20181111155202/https://code.visualstudio.com/License), so I’m presuming that the 2018 “EULA ID” string is erroneous.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18363

**Comment by joaomoreno** [comment]
AFAIK that's OK, it's just the date when the EULA was created. I don't think we need to bump that date just for the sake of things.

Up to you @chrisdias

**Comment by PDeBonte** [comment]
Wasn't the EULA created [in 2015](http://web.archive.org/web/20150429205127/https://code.visualstudio.com/License)?

**Comment by PDeBonte** [comment]
Note that my last comment, about remains unanswered:

1. My issue was that the 2018 in the EULA ID seemed to be incorrect/outdated.
2. joaomoreno replied that the 2018 in the  EULA was "when the EULA was created."
3. I noted that the EULA existed [in 2015](http://web.archive.org/web/20150429205127/https://code.visualstudio.com/License) [which would mean that 2018 wouldn't be "when the EULA was created." unless I'm missing something].

**Comment by PDeBonte** [comment]
Note that my last comment, about remains unanswered:

1. My issue was that the 2018 in the EULA ID seemed to be incorrect/outdated.
2. @joaomoreno replied that the 2018 in the EULA was "when the EULA was created."
3. I noted that the EULA existed [in 2015](http://web.archive.org/web/20150429205127/https://code.visualstudio.com/License) [which would mean that the 2018 in the EULA ID wouldn't be "when the EULA was created" unless I'm missing something].

**Comment by chrisdias** [comment]
I not sure we even need need the `EULA ID: Visual Studio Code 14 November 2018` but I will check further.

**Comment by PDeBonte** [comment]
Thanks for your response Chris!
If you drop the EULA ID, then it would be great if there was some easy way to verify that the EULA in the installer matches [the latest EULA on the website](https://code.visualstudio.com/license) (which as I noted in my original post, is required to download the installer). That was actually my motive for this issue:

1. I invested time reviewing the EULA on the Web before downloading.
2. The downloaded installed then appeared to have a different EULA.
• The 2018 date contributed to the confusion, so fixing/removing that would help;
• but the significant formatting changes between the Web & installer further complicated verifying that the two matched.

 **★ Instead of the EULA date, how about matching the EULA's text formatting between [the website](https://code.visualstudio.com/license) and the installer, so the two copies can be easily pasted into a diff program to confirm a match or find changes?**

**Comment by chrisdias** [comment]
I submitted a PR to @joaomoreno to fix the LICENSE files for the setup - removing the EULA ID footer (confirmed not needed), fixing the http -> https URLs, and updating the GDPR URL.  

I wish we could easily make the website and in product format match, but one is in RTF format (setup) and the website is in handlebars. Neither is good for diffing.

**Comment by alexr00** [comment]
Verified by code review. The links still have `master` as the branch instead of `main`.

**Comment by chrisdias** [comment]
Thanks @alexr00 I will make the fixes

**Comment by chrisdias** [comment]
fixed
