### ISSUE TITLE
Throw function should return by default never instead of returning void <Typescript>

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118774]
- VS Code Version: 1.54.1
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

1. Example below

![image](https://user-images.githubusercontent.com/17777237/110874043-b15c5880-82db-11eb-9df7-5feef25bd464.png)

**It should recognize that it return never**

![image](https://user-images.githubusercontent.com/17777237/110874163-f4b6c700-82db-11eb-8902-9577627e3b0a.png)

**Another case Infinity loop the editor should warning user it infinity loop and set return type to never**
```
function infinityLoop(): never {
    while (true);
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a bug upstream](https://github.com/microsoft/TypeScript/issues/new/choose)
