### ISSUE TITLE
项目打开问题

### ISSUE THREAD

**Issue by Yfk587964** [microsoft/vscode#118786]
Issue Type: <b>Bug</b>

我没有使用gomod，但是我已经把gopath设置成为我的项目地址了，我的项目中有src,pkg,bin目录了，所以我把gopath改成了我的项目名称，怎么还会报错不在模块或者不在gopath的src中

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.00GB free)|
|Process Argv|--crash-reporter-id 94df8d54-fe2e-497a-8d7a-63264076272d|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.17
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
go|gol|0.23.1
styled-components-snippets|jon|0.10.0
vscode-styled-components|jpo|1.5.0
vscode-language-pack-zh-hans|MS-|1.54.2
vscode-icons|vsc|11.1.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by yume-chan** [comment]
Caused by Go extension
