### ISSUE TITLE
code cant render ui

### ISSUE THREAD

**Issue by e7** [microsoft/vscode#118710]
- VS Code Version: 1.54.1
- OS Version: debian 10

Steps to Reproduce:

1. just open vscode
![sc_20210311180640](https://user-images.githubusercontent.com/608194/110770784-b5b15300-8294-11eb-8a58-ec2b76bd1192.png)

Does this issue occur when all extensions are disabled?: No, I deleted $HOME/.vscode directory

**Comment by deepak1556** [comment]
Are you running inside a vm ?

Disable gpu acceleration to workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by e7** [comment]
> Are you running inside a vm ?
> 
> Disable gpu acceleration to workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
Yes. OK, I will try it later

**Comment by e7** [comment]
> Are you running inside a vm ?
> 
> Disable gpu acceleration to workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Yes. OK, I'll try it later

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/111290
