### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hashininirasha** [microsoft/vscode#118701]
Failed to save 'style.css': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes.

What is that error

**Comment by gjsjohnmurray** [comment]
Something else changed the file.

Tip for future issue reporting: use the Report Issue option from the Help menu

**Comment by aeschli** [comment]
Some other program (e.g. git) must have changed the file content while you were editing without saving.

**Comment by Hashininirasha** [comment]
Thank you
