### ISSUE TITLE
Not able to create Kotlin file

### ISSUE THREAD

**Issue by shuchi19** [microsoft/vscode#118750]
We have written the needed 
Issue Type: <b>Bug</b>

Created a new file and tried to Save as Kotlin but haven't found the option, though java, closure, groovy, yaml and many file types found and working fine.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.58GB free)|
|Process Argv|--crash-reporter-id 818c6a77-0bb2-48a5-9e7c-bf88dba956a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.8.5
ebox|Ebo|0.0.6
vscode-yaml|red|0.16.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464

```

</details>

data into your clipboard because it was too large to send. Please paste.

**Comment by TylerLeonhardt** [comment]
This just means that we don't have built-in syntax highlighting for Kotlin. I found this 3rd party Kotlin extension:
https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin

If you install that then you should have a nice Kotlin experience :)
