### ISSUE TITLE
Quick pick issue

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode#118713]
- VS Code Version: 1.54.1

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/211268/110775932-5ad81700-8214-11eb-9b19-fefd7c159c42.png)
1. I expect the file send_to_self.txt should be the first item in the result
2. I don't expect to see the send_to_lf.txt in the result.

Does this issue occur when all extensions are disabled?: Yes

**Comment by th3void** [comment]
And because it orders in reverse, and a very annoying bug.

**Comment by bpasero** [comment]
Using spaces treats each query as separate query.
