### ISSUE TITLE
Tooltip does not let me hover over it to perform command on it by click

### ISSUE THREAD

**Issue by ranavale** [microsoft/vscode#118755]
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:

1. Try any extension that has a action/command to execute in tooltip
![VSCode tooltip update](https://user-images.githubusercontent.com/47042862/110844729-9e577300-825e-11eb-9b77-d1e8b5bb78fa.gif)
I have seen this working and letting user hover over tooltip and perform the command on tooltip by click action. Am I missing something or something has changed?

Does this issue occur when all extensions are disabled?: This question is irrelevant for this bug/issue. The issue I have observed with extension having command in tooltip

**Comment by alexr00** [comment]
@Tyriar it looks like default behavior to not hide on hover when the content `IMarkdownString` is no longer working. I also tried to set `hideOnHover: false` and that appeared to be ignored.

**Comment by bwateratmsft** [comment]
It's working nicely now in Insiders. I don't know if this is new or existed previously but it looks like all of the tooltips have horizontal scrollbars, sometimes they obstruct the contents slightly:

![image](https://user-images.githubusercontent.com/36966225/111780044-3f60b200-888d-11eb-9648-62d1f55ed8ed.png)
![image](https://user-images.githubusercontent.com/36966225/111780082-4d163780-888d-11eb-9714-9a9dca956c15.png)

**Comment by ranavale** [comment]
- Verified that this looks like fixed and fix is available in VSCode Insider 1.55.0.

**Comment by alexr00** [comment]
@bwateratmsft the scroll bar appears to be specific to the Docker extensions hovers. The GitHub Pull Requests and Issues extension uses markdown hovers too, but I'm not seeing the scrollbar:

![image](https://user-images.githubusercontent.com/38270282/111797007-08a88d00-88c9-11eb-810c-88f47b37ea9c.png)

**Comment by bwateratmsft** [comment]
Interesting, it might be because of the `<hr />` (well, `---` because Markdown) that we're using. I'll see what happens without those.

**Comment by alexr00** [comment]
That sounds like it could be an issue with our markdown rendering...

**Comment by Tyriar** [comment]
It is rendering of `hr`, can repro:

![image](https://user-images.githubusercontent.com/2193314/111856048-53380280-88e5-11eb-9d21-59920d02e59a.png)

Tracking in https://github.com/microsoft/vscode/issues/119374
