### ISSUE TITLE
TreeItem Icon not loading in 1.54 (VSCode Extension)

### ISSUE THREAD

**Issue by ranavale** [microsoft/vscode#118773]
- VS Code Version: 1.54.1
- OS Version: Windows 10

Steps to Reproduce:
I have a vscode extension that loads a File/Folder in TreeItem. Tree-Item icon is not loading in 1.54 released version.
If I load the extension on 1.52 older version, the icon is visible.
Are there any update on Icon loading?

![Capture](https://user-images.githubusercontent.com/47042862/110873732-43864180-8287-11eb-9e5b-4860f20ebde1.PNG)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. I see icons in extension provided tree view loading as expected:
![image](https://user-images.githubusercontent.com/38270282/111152877-8a2eb100-8591-11eb-9dfd-4307e3fe9a4f.png)
If this is an issue with a specific extension, I would recommend that you file an issue with that extension.

**Comment by ranavale** [comment]
Just for information.
I think the issue got resolved with vscode update **1.55.0.**
Nothing changed from the extension, but now the icons are loading correctly after this vscode update. not sure if anything else caused this issue.
