### ISSUE TITLE
Consider to surface the new "hitBreakpointIds" property of the DAP StoppedEvent in the UI

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#118743]
With the arrival of https://github.com/microsoft/debug-adapter-protocol/issues/178 in DAP, we should discuss whether and how to surface this information in the UI.

E.g. on hitting a breakpoint we could highlight the breakpoint(s) in the BREAKPOINT view.

**Comment by isidorn** [comment]
Yes, using some visual cue in the BREAKPOINTS view makes sense to me.

Highlighting the breakpoint in the editor glyph margin does not make a lot of sense since the call stack decoration is already there making it clear.

fyi @misolori @connor4312 for ideas

**Comment by weinand** [comment]
A more subtle approach would be to make the "stopped reason" in the call stack view a link that highlights the breakpoint in the BREAKPOINT view.

**Comment by isidorn** [comment]
@weinand that's a good idea. Clicking on the "stopped reason" could focus the corresponding breakpoint in the BREAKPOINTS view.

**Comment by connor4312** [comment]
Some visual cue could be nice. Nothing comes to mind for other cases in which I would want to use this as a user -- the editor already takes me to the line and 'highlights' the breakpoint in the gutter. That's where I usually interact with breakpoints, maybe some commands to remove or disable the 'current breakpoint' would be useful though.

**Comment by connor4312** [comment]
There was a twitter request for this too, good timing: https://twitter.com/MagnetismER/status/1381693425163116545

**Comment by isidorn** [comment]
I could look into this next milestone. Until then ideas are welcome :)

**Comment by connor4312** [comment]
Adopted this in https://github.com/microsoft/vscode-js-debug/issues/994

**Comment by isidorn** [comment]
Starting to look into this.
Once there is a stop event with a breakpoint id I plan to:
1) focus that breakpoint in the breakpoint view 
2) clicking on the call stack PAUSED ON reason does not work, since if it is shown on a session - on hover we show the debug toolbar, and if it is in the title area, click on it collapses the view.

I am not sure if the focus decoration will be strong enough (since the dom focus will not be in the breakpoints view but in the editor since we auto focus it). But let's start with that and I can make this visually stronger if needed

![Screenshot 2021-05-18 at 16 29 13](https://user-images.githubusercontent.com/1926584/118669696-40af4c00-b7f6-11eb-9abc-430ea87f8fde.png)

**Comment by isidorn** [comment]
I pushed an initial version for this, however I am not getting the `hitBreakpointIds` field from js-debug
@connor4312 did you release js-debug with the change you did?

**Comment by connor4312** [comment]
It's only in [nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) right now.

**Comment by isidorn** [comment]
@connor4312 cool, I see with nighly that I get back the `hitBreakpointIds`, however I always get an array of two elements. And only the second elements seems to have the correct breakpoint id.
Do you know why that is the case? I would expect that the array has only one element, and that only in corner cases the array has multiple elements as specified [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L146)

**Comment by connor4312** [comment]
I'm not seeing this in a single Node program, can you add `trace: true` and share your logs?

**Comment by isidorn** [comment]
@connor4312 here are the steps:

1. Debug a simple console.log three line app. Add breakpoint on every line. Start debugging
2. Stop on first breakpoint. Remove second breakpoint, add it again
3. Next stop event will contain both the removed breakpoint and the new breakpoint

Actually looks pretty cool.

![recording](https://user-images.githubusercontent.com/1926584/118703542-80862b80-b816-11eb-89a3-22e943a4a68a.gif)

**Comment by connor4312** [comment]
Hm, I still have trouble getting that. However, I _do_ get it if I remove the statement on the second line. In this case the breakpoint on line 2 resolves to the next statement (line 3) so the breakpoint is doubled. [Video](https://memes.peet.io/img/21-05-3cdcc7a7-457e-4572-8f9d-d14d651322f1.mp4)

Is that possibly what you're seeing?

**Comment by isidorn** [comment]
@connor4312 no. I can see double breakpoints sent without doing any code edits at all.
Here are the logs:
[vscode-debugadapter-c4c93f4f.json.gz](https://github.com/microsoft/vscode/files/6507552/vscode-debugadapter-c4c93f4f.json.gz)

**Comment by connor4312** [comment]
I think this is due to a casing issue, VS Code sees the file as `/Users/isidor/Development/w/march/hello.js` while Node sees it as `/Users/isidor/Development/w/March/hello.js`. We treat OSX as case sensitive, which causes the issue. The case sensitivity behavior is a behavior the old debugger did as well and I'm kind of hesitant to change that.

**Comment by isidorn** [comment]
@connor4312 thanks for investigating. Yes I agree, no change needed here

**Comment by isidorn** [comment]
Verification steps:
* Have a simple javascript program and have mulitple breakpoints. Every time a breakpoint gets hit make sure it is selected in the breakpoints view. Similar to the gif I posted in the above [comment](https://github.com/microsoft/vscode/issues/118743#issuecomment-843421100)

@connor4312 not sure if js-debug nightly is still needed in order to verify this?

**Comment by connor4312** [comment]
[Nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension) will be needed until the next Insiders, yes

**Comment by bpasero** [comment]
It works. Not sure if breakpoint selection should be cleared as soon as I go off a breakpoint (e.g. with Step Over). I also see the breakpoint still selected when I terminate the debug session.

**Comment by isidorn** [comment]
I think both of those cases are similar: debugger is no longer stopped on that breakpoint (first case step over, second terminate happened). I am fine with the current behaviour however I can change to what you are suggesting: that we clear the selection in that case. However then we would not be aligned with the explorer - Explorer keeps the file selected when it is closed in the editor view.

@connor4312 @weinand what do you think?

**Comment by connor4312** [comment]
Deselection like Ben expects makes sense to me. I think of the breakpoints view as a browser for a small subset of locations in the program. If you stop debugging or step off, you're no longer at that location -- so like if you opened a different file, it should get deselected.

**Comment by isidorn** [comment]
Makes sense, I have created this issue to tackle that https://github.com/microsoft/vscode/issues/125528

**Comment by weinand** [comment]
I agree that the breakpoint highlight should be removed if debugging has moved away.
But I wonder whether this means that we can no longer use the "selection" as a means to highlight breakpoints.
If the user has selected a breakpoint manually (for whatever reason), and then steps to the next statement, the selection will be lost.
Maybe we should introduce an independent visual cue to indicate a "hit breakpoint"?

**Comment by isidorn** [comment]
We can remember if we automatically set it and only clear it if it was automatically set.
That should solve this corner case.

**Comment by connor4312** [comment]
👍 on have some alternative, non-selection way to indicate where we're paused. Maybe replace the breakpoint icon on the items with the "hit" combination of the arrow plus icon?

**Comment by isidorn** [comment]
Not a bad idea of changing the icon... I like that.
Bold - we do not use in other trees, so I would not introduce a new concept.
Yellow color - it was a bit hard to get the coloring right for the editor background and tree usually has a different background color..
