### ISSUE TITLE
Record Keys shortcut not updating

### ISSUE THREAD

**Issue by PellegattaSimone** [microsoft/vscode#118765]
- VS Code Version: 1.54.1 (latest)
- OS Version: Windows 10

Steps to Reproduce:

1. Open the key binding settings (File > Preferences > Keyboard Shortcuts)
2. Bind "Record keys" from "Alt K" to something else
3. When you hover on "Record keys", it still shows "Alt K" as shortcut

The new keys are working, but the problem is that "Record keys" still shows the default shortcut on hover.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Looks similar to #118134

**Comment by sandy081** [comment]
@PellegattaSimone Is the issue happening only with this action or other actions too?

**Comment by PellegattaSimone** [comment]
Only for this specific action
