### ISSUE TITLE
Search (find) request not finding things 

### ISSUE THREAD

**Issue by rwgreene999** [microsoft/vscode#118756]
- VS Code Version: 1.54.1
- OS Version: windows 10 

Steps to Reproduce:

1. open file with a search term in it (like 'test') 
2. ctrl-F to open search 
3. enter search term (like 'test') that you know is in the file 
4. VS Code says **No Results** and does not locate the search term in the file

Does this issue occur when all extensions are disabled?: Yes
![Image 20210311123648](https://user-images.githubusercontent.com/2169212/110845027-5b4dcd80-8267-11eb-8d5e-3d323f71a8d7.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo
You have Search in selection enabled (three lines next to close button).
Does it work if you turn it off?

**Comment by rwgreene999** [comment]
" Find in selection " is that supposed to be the default condition when code start up and this is the first search? 

Everything works fine once I turn this off, should I always have to turn it off?

**Comment by rwgreene999** [comment]
Closing this issue as it is related to " Find in selection " which seems to be the default and was unknown as an option by me.

**Comment by IllusionMH** [comment]
I don't think that it's default however it will be remembered between searches and can be turned on by accident (miss click or <kbd>Alt</kbd>+<kbd>L</kbd> ).

@rebornix do you know if it's expected that if Find in selection is not "skipped" when there are no selections (just cursor) in editor? I would expect to have regular full file search unless I have selection that is at least 1 character long.
