### ISSUE TITLE
VSCode has become too slow

### ISSUE THREAD

**Issue by induratized** [microsoft/vscode#118708]
Issue Type: <b>Bug</b>

It hass become too slow. Actions like.
- Git explorer section takes to much time for any action
- manipulating files
navigation etc..etc.. 

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 7|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|-psn_0_57358 --crash-reporter-id 1b654aa6-c989-4e2c-b14d-a372c2ec3eb5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.1.0
vscode-eslint|dba|2.1.16
gitlens|eam|11.3.0
vscode-pull-request-github|Git|0.24.0
todo-tree|Gru|0.0.202
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
vsliveshare|ms-|1.0.3912
material-icon-theme|PKi|4.5.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.16.0
code-settings-sync|Sha|3.4.3
sonarlint-vscode|Son|1.20.1
rewrap|stk|1.14.0
svelte-vscode|sve|104.6.2
vscode-webhint|web|1.5.11
material-theme|zhu|3.9.15

(9 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for advice about performance issues.

I also suggest you use the Start Extension Bisect command to investigate whether one of your extensions is causing this.

/needsMoreInfo

**Comment by induratized** [comment]
> Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for advice about performance issues.
> 
> I also suggest you use the Start Extension Bisect command to investigate whether one of your extensions is causing this.
> 
> /needsMoreInfo

Tried this approach. found out that extensions were the root cause. Could not make out which one exactly just disabled a bunch of them I don't use often. 
VSCode now works as smooth as before. Thanks for your input
