### ISSUE TITLE
Tensorboard pane blank

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode#118733]
Issue Type: <b>Bug</b>

1. Start TensorBoard from VSCode, specifying log directory.
2. Run Tensorflow model, using the same directory as the model_dir
3. Observe nothing in TensorBoard pane

The TensorBoard pane is never populated with a TensorBoard interface even with a directory full of TF output.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 5.4.0-1037-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 7dfc0449-544b-4fa5-917f-21b04190e4ed|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: NYYAWS|
|OS|Linux x64 5.4.0-1037-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (4 x 2758)|
|Memory (System)|59.86GB (10.91GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|0.8.2
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.3
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.5.0
rainbow-csv|mec|1.8.1
python|ms-|2021.2.636928669
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.3.619093157
html-preview-vscode|tht|0.2.5
docker|vsc|1.0.0
yaml|vsc|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464

```

</details>

**Comment by fonnesbeck** [comment]
I just confirmed that this is not a TensorBoard issue. If I start TensorBoard manually from the command line it works fine using a browser window, so the issue is with VSCode.

**Comment by IllusionMH** [comment]
/needsMoreInfo

From your description its not clear how do you launch it from VS Code what is your setup and config around it.

If support comes from Python extension - please fill this issue in extension's repo.

**Comment by fonnesbeck** [comment]
The issue was created directly from your bug reporting feature in VSCode.

**Comment by fonnesbeck** [comment]
Sorry, did not realize this comes from an extension. Closing.
