### ISSUE TITLE
Won't run in a xrdp session

### ISSUE THREAD

**Issue by jtlivio** [Microsoft/vscode#11873]
- VSCode Version: 1.5.1
- OS Version: Lubuntu 16 LTS

Steps to Reproduce:

1. Activate XRDP in Lubuntu
2. Remote from Windows 10 1670
3. Run VSCode

**Comment by bpasero** [comment]
@jtlivio what happens if you try to run?

**Comment by jtlivio** [comment]
Hi @bpasero . If you hit "code ." nothing happens, if you try to open directly from the Icon, a status bar message is fired "starting visuual studio...." for a few seconds, VSCode don't open and the status disappear.

![vsc](https://cloud.githubusercontent.com/assets/2190606/18478111/fec75880-79c7-11e6-87b4-b37aad7b31a5.png)

**Comment by bpasero** [comment]
@jtlivio can you run from the command line "`code --verbose`" to see if there is any output printed?

**Comment by jtlivio** [comment]
@bpasero sorry for image, I don't have Copy/Paste between host and guest yet.

![vscerr](https://cloud.githubusercontent.com/assets/2190606/18480570/0ef82e2e-79d1-11e6-9096-bf5725536610.png)

**Comment by bpasero** [comment]
Hm, the Xlib output is suspicious, are you sure everything is installed to open that window?

**Comment by jtlivio** [comment]
I was able to resolve from issue #3451 (vscode)

**Comment by bpasero** [comment]
Ok, lets close as duplicate then.
