### ISSUE TITLE
Debug console does not auto-scroll to the very bottom

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#118702]
Issue Type: <b>Bug</b>

- Use Python extension
- Create `bug.py`:

```python
import numpy as np

arrays = [[1], [2]]
np.stack(arrays) == np.array(arrays)
print("Done")
```
- Place breakpoint in last line
- Start debugging
- Copy `np.stack(arrays) == np.array(arrays)`
- Paste into Debug Console and execute a few times
- When the bottom of Debug Console is reached, automatic down-scrolling stops one line short of the true bottom at one point.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.3.18-lp152.44-default

**Comment by bersbersbers** [comment]
![d19mFLhAtQ](https://user-images.githubusercontent.com/12128514/110755051-cb992680-8248-11eb-99ea-dab9ff115f88.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/117674

**Comment by zxl777** [comment]
Fixed it by set

![image](https://user-images.githubusercontent.com/816448/113525450-97b2e600-95e7-11eb-8c63-98d359f670de.png)
