### ISSUE TITLE
VSC crashed trying to load http://localhost:5000/

### ISSUE THREAD

**Issue by ccnarvaez** [microsoft/vscode#118717]
Hey There!

1. I am trying to load last changes on my code on google chrome
2.  I followed local link in terminal
3. The changes started to load in google chrome
4. Then, when I tried to open Console (ctrl+shift+i) it crashes down

What i tried to solve this issue:
1. Erase cookies and history data
2. Clean up my PC documents
3. Erase some programs to get more memory space
4. Restart PC two or more times

Please help!

**Comment by ccnarvaez** [comment]
BTW... This could seem a google chrome issue, but i can open console in other pages. The problem start when I try to open console from VSC local link

**Comment by chrmarti** [comment]
I'm not sure how VS Code is involved. What happens when you close VS Code, start your server from a terminal window and then open the link in Chrome and open the dev tools?

**Comment by ccnarvaez** [comment]
Hi Christoph!

Thanks for your answer! Indeed the problem was nos related to VSC, but I
understood later I wrote to VSC support.

Sorry for inconvenience

Greetings!

Claudia
