### ISSUE TITLE
FRUITS

### ISSUE THREAD

**Issue by Loycevelma** [microsoft/vscode#118723]
Issue Type: <b>Bug</b>

i opened a folder named FRUITS and a file called fruits.js but it was in an autosave mode so i just cancelled it unknowingly but i want to use it but cant find it what should i do

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.8.0-44-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2685)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 1|
|Memory (System)|3.54GB (0.10GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id ac1a1159-6879-444d-b7dd-fb1c08d7ec3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by TylerLeonhardt** [comment]
Go into the settings (File -> Preferences -> Settings) or `ctrl+,`  search for "autosave" and then change the setting to whatever you'd like.

If you need it to apply to just that specific folder, click on the "Workspace" tab under the search bar.

![image](https://user-images.githubusercontent.com/2644648/110827972-6eeb3b00-824b-11eb-80aa-6e52640ccf7c.png)
