### ISSUE TITLE
Unable to click on disconnect button in Codespaces view when disconnected from Codespace

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#118772]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Let your codespace disconnect:
![image](https://user-images.githubusercontent.com/2644648/110871469-54cd4f00-8283-11eb-840e-a7f8550b22ac.png)

2. Click cancel
3. Go into Codespaces view and click the disconnect icon:
![image](https://user-images.githubusercontent.com/2644648/110871554-775f6800-8283-11eb-8b31-3be3d863c116.png)

For me, nothing happens... I remember seeing an "activating extensions..." popping up in status bar but I'm not sure if it was related.

A comment from @roblourens:

> It used to be that the local EH would be shut down when reconnecting failed. Then we changed it to keep it around. But now it seems like I can’t run commands for local EH extensions in this state

**Comment by alexdima** [comment]
> It used to be that the local EH would be shut down when reconnecting failed. Then we changed it to keep it around. But now it seems like I can’t run commands for local EH extensions in this state

@TylerLeonhardt @roblourens I cannot reproduce this. This appears to be a problem with the Codespace extension and perhaps with this particular command. I can execute commands on the local extension host just fine when the window is disconnected. 

Here is what I have tried:
* `package.json`:
```js
{
    "name": "118772",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": { "vscode": "^1.22.0" },
    "activationEvents": ["*"],
    "main": "index.js",
    "extensionKind": [ "ui" ],
    "contributes": { "commands": [ { "command": "test1", "title": "Test1"} ] }
}
```
* `index.js`:
```
const vscode = require("vscode");
exports.activate = function (context) {
  vscode.commands.registerCommand('test1', () => {
    console.log(`My command is running fine!`);
  });
};
```

I then proceed to use the test resolver, then kill the server and enter disconnected mode. The command (which is implemented by a UI extension running on the local extension host) executes just fine:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/110944038-31b2a600-833c-11eb-8be7-ce6dfe638338.gif)

**Comment by roblourens** [comment]
I can still repro this in Insiders by following essentially the same steps but with Remote-SSH, and a command in Remote-SSH other another UI extension. I'll try with the test resolver.

**Comment by alexdima** [comment]
@roblourens What is the implementation of `Remote-SSH: Open Configuration File`? What vscode API are you using there? (maybe that part is not working anymore?)

**Comment by roblourens** [comment]
Got it, add the `onCommand` activation event to your test code and it will repro. Then the command service tries to verify that activations have happened, we get to this point

https://github.com/Microsoft/vscode/blob/5f451c6670d3995eec4c595a0028c3dbc4c6a012/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L558-L558

and that never resolves. But if no extension wants to activate on that command, or if the command was already run before disconnecting, it doesn't repro.

**Comment by alexdima** [comment]
To verify, you can use:
* `package.json`:
```
{
    "name": "118772",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": { "vscode": "^1.22.0" },
    "activationEvents": [
        "*",
        "onCommand:test1"
    ],
    "main": "index.js",
    "extensionKind": [
        "ui"
    ],
    "contributes": {
        "commands": [
            { "command": "test1", "title": "Test1"}
        ]
    }
}
```
* `index.js`:
```
const vscode = require("vscode");

exports.activate = function (context) {
  vscode.commands.registerCommand('test1', () => {
    console.log(`My command is running fine!`);
  });
};
```
* open a test resolver folder
* run `Remote-TestResolver: Kill server and trigger error handler`
* run `F1 > test`
* check that the console has the output
