### ISSUE TITLE
JavaScript function not working

### ISSUE THREAD

**Issue by Mubashir-Mohamed647** [microsoft/vscode#118796]
Issue Type: <b>Bug</b>

There is a problem with JS, where one of the in-built functions is not working. It was my mistake as when you press ctrl+click on any in-built function, it goes into lib..dom.ts file, and I accidentally deleted part of the code which was there , which included the json.  I think it was in line 2700 something, not too sure. Please fix this problem and restore the function there.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.78GB free)|
|Process Argv|--crash-reporter-id edafc6f9-d901-4d7c-b965-2437af8fa5f9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tomcat|ada|0.11.3
xd|ado|1.1.4
stories|bar|2.23.0
markdown-emoji|bie|0.1.0
vscode-eslint|dba|2.1.17
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|5.9.2
mithril-emmet|Fal|0.7.6
codespaces|Git|0.8.2
vscode-pull-request-github-insiders|Git|2021.3.4863
vscode-gutter-preview|kis|0.27.1
auto-save|mcr|1.0.3
vs-media-player|mkl|3.1.0
theme-monokai-pro-vscode|mon|1.1.18
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.3968
color-highlight|nau|2.3.0
LiveServer|rit|5.6.1
tabnine-vscode|Tab|3.2.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you reinstall VS Code and see if doing that reinstates the library file that you accidentally modified.

**Comment by Mubashir-Mohamed647** [comment]
Yes, I just realized it was just an nonexistent object. I accidentally deleted some on the code in lib.dom.ts, and thought it was my mistake, but then it got restored, and I realized it was because I called the function on a object that doesn't exist. Thank you anyways. Happy coding
