### ISSUE TITLE
vscode-file: allow different zoom levels per window

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118740]
Once we enable `vscode-file` protocol as origin, we need a patch to stop Chrome from persisting the zoom level for this origin so that we can still allow different zoom levels for multiple windows.

**Comment by nickpapoutsis** [comment]
Best case scenario, when will we be able to have different zoom levels in insider builds?

(Having monitors with different resolutions zoom's killing me...)

**Comment by bpasero** [comment]
It looks like this also needs the changes from https://github.com/microsoft/vscode/compare/ben/108920 to be an issue.

**Comment by bpasero** [comment]
I think we can go ahead and close this as wontfix given we can use the `webFrame` module even from the renderer. This seems to be required to allow for different zoom. levels per window.
