### ISSUE TITLE
Cannot start gulp with BrowserSync: `address already in use`

### ISSUE THREAD

**Issue by sdhayalan** [microsoft/vscode#118746]
- VS Code Version: 1.54.1
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Update to the latest VSCode.
2. Start gulp service (browsersync) in the built-in Terminal
2. Close VSCode without stopping gulp or closing the terminal
3. Reopen VSCode, and try running `gulp` again.
4. It was working fine until the last update.
4. The following error happens:

```
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1256:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1392:7)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by sdhayalan** [comment]
I restarted VSCode, WAMP server (which is the main server which browsersync proxies). I know for sure restarting the computer would solve the issue but this has been working right before the update. In the new update, vscode introduced the feature to restore terminal state to how it was before closing, I think that causes this issue.

**Comment by meganrogge** [comment]
You can turn off the local reconnection with the setting `enablePersistentSessions`
