### ISSUE TITLE
执行powershell显示乱码

### ISSUE THREAD

**Issue by agentwx** [Microsoft/vscode#1187]
执行powershell时，output区域显示的中文乱码
��ʹ�� -Command ����ָ���ˡ�-����������Ϊ -Command ָ�������κβ�����

PowerShell[.exe] [-PSConsoleFile <�ļ�> | -Version <�汾>]
    [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
    [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
    [-WindowStyle <��ʽ>] [-EncodedCommand <Base64 ����������>]
    [-File <�ļ�·��> <args>] [-ExecutionPolicy <ִ�в���>]
    [-Command { - | <�ű���> [-args <��������>]
                  | <�ַ���> [<�����в���>] } ]

PowerShell[.exe] -Help | -? | /?

-PSConsoleFile
    ����ָ���� Windows PowerShell ����̨�ļ���
    Ҫ��������̨�ļ������� Windows PowerShell ��ʹ�� Export-Console��

-Version
    ����ָ���汾�� Windows PowerShell��
    ͨ���˲��������汾�ţ��� "-version 2.0"��

-NoLogo
    ����ʱ���ذ�Ȩ��־��

-NoExit
    �����������������˳���

-Sta
    ʹ�õ��̵߳�Ԫ���� Shell��
    Ĭ��ֵΪ���̵߳�Ԫ(STA)��

-Mta
    ʹ�ö��̵߳�Ԫ���� Shell��

-NoProfile
    ������ Windows PowerShell �����ļ���

-NonInteractive
    �����û���ʾ����ʽ��ʾ��

-InputFormat
    �������͵� Windows PowerShell �����ݵĸ�ʽ��
    ��ЧֵΪ "Text" (�ı��ַ���)�� "XML" (���л��� CLIXML ��ʽ)��

-OutputFormat
    ȷ���������� Windows PowerShell �������ݵĸ�ʽ��
    ��ЧֵΪ "Text" (�ı��ַ���)�� "XML" (���л��� CLIXML ��ʽ)��

-WindowStyle
    ��������ʽ����Ϊ Normal��Minimized��Maximized �� Hidden��

-EncodedCommand
    ���� Base 64 �����ַ����汾�����
    ʹ�ô˲����� Windows PowerShell �ύ��Ҫ��������
    �������ŵ����

-File
    �ڱ���������("dot-sourced")������ָ���Ľű���
    �Ա��ű������ĺ����ͱ��������ڵ�ǰ�Ự��ʹ�á�
    �����ű��ļ�·�����κβ�����
    File �����������е�����һ��������
    ��Ϊ�� File �������ƺ����������ַ���������Ϊ
    �������нű������Ľű��ļ�·����

-ExecutionPolicy
    ���õ�ǰ�Ự��Ĭ��ִ�в��ԣ�
    �����䱣���� $env:PSExecutionPolicyPreference ���������С�
    �ò�������������ע������
    ���õ� Windows PowerShell ִ�в��ԡ�

-Command
    ִ��ָ��������(���κβ���)��
    �ͺ����������� Windows PowerShell ������ʾ���¼�����һ����Ȼ���˳���
    ����ָ���� NoExit��Command ֵ����Ϊ "-"���ַ�����
    �ű��顣

    ���� Command ֵΪ "-"�����ӱ�׼�����ж�ȡ
    �����ı���

    ���� Command ֵΪ�ű��飬���ű�������
    �ô�����({})��������ֻ���� Windows PowerShell ������ PowerShell.exe ʱ��
    ����ָ���ű��顣�ű�����������Ϊ�����л��� XML ����
    (���ǻ����)���ص��� Shell��

    ���� Command ֵΪ�ַ������� Command �����������е�����һ��������
    ��Ϊ���������������������ַ�
    ��������Ϊ����������

    Ҫ��д���� Windows PowerShell �������ַ�������ʹ�����¸�ʽ:
	"& {<����>}"
    ���У����ű�ʾһ���ַ�����
    ����������(&)ʹ�������ᱻִ�С�

-Help, -?, /?
    ��ʾ����Ϣ�������� Windows PowerShell �м��� PowerShell.exe ���
    ������������ǰ���������ַ�(-)��
    ������������б��(/)���������� Cmd.exe ��ʹ�����ַ�����б�ܡ�

**Comment by egamma** [comment]
I'm sorry, but please file this issue again in English.
