### ISSUE TITLE
"cmd + /" is not recognized with Dvorak on macOS

### ISSUE THREAD

**Issue by swawa-yu** [microsoft/vscode#118789]
Keybinding "cmd + /" is not recognized (Dvorak keyboard layout on macOS(Big Sur 11.2.2)).
Other Keybindings are OK.

You can test like this:
- (mac) System Preferences > Keyboard > Input Source > English > Dvorak
- (VSCode) Keyboard Shortcuts > Record Keys(icon is at the right side of the searching box)

"cmd + /" works with input source "ABC"( = Qwerty).

**Comment by alexdima** [comment]
@swawa-yu I cannot reproduce, `cmd+/` works for me using the Dvorak keyboard layout:


https://user-images.githubusercontent.com/5047891/121080470-c0b84880-c7db-11eb-87be-1d9b83f63aee.mp4
