### ISSUE TITLE
Allow to configure settings per file type

### ISSUE THREAD

**Issue by rothskeller** [Microsoft/vscode#11879]
- VSCode Version: 1.5.1
- OS Version: OS-X 10.11.6

Currently, the configuration switches that control indentation (editor.tabSize, editor.insertSpaces) can be configured globally or per-workspace.  But it's not unusual to work on different types of files within the same workspace that need different indentation styles.  For example, Go source files always use tabSize=8, insertSpaces=false (it's a language standard), but the same workspaces very often contain other types of files (e.g. Markdown, HTML, JavaScript, etc.) where those are not the desired settings.  It is irritating to have to set the indentation style manually whenever creating a new file.  Instead, the indentation settings should be language-specific, rather like snippets.

**Comment by DanTup** [comment]
This is a similar issue to #2765 where the response was for the Go extension to explicitly set the indent settings. I have to do [the same for Dart](https://github.com/Dart-Code/Dart-Code/blob/master/src/dart_indent_fixer.ts) but I think it's a bit naff and would be a good feature for Code to support natively.

**Comment by rothskeller** [comment]
Well, there's two problems with that.  First, I raised that request with the Go extension author. @lukehoban , (see [here](https://github.com/Microsoft/vscode-go/issues/384)), and he indicated that he didn't think it was possible — or advisable — for an extension to override core customization settings in this way.  So if the vscode maintainers think that's the right answer, it would be nice if they could connect with him and make sure he knows that and knows how.

More importantly, that might be a reasonable answer for Go where the language dictates the indentation style, but it's less desirable for other, more flexible languages.  Suppose that I want to have my Python sources with four-space indent but by YAML sources with two-space indent.  Does the author of *every* language extension need to provide ways to override the core settings for their language?  Wouldn't it make more sense to centralize that — especially since the core already has a way to do language-specific things (e.g. snippets)?

**Comment by DanTup** [comment]
Like I said, I completely agree. I think both users and extension authors should be able to set it (the current mechanism is absolutely a hack)!

**Comment by anurse** [comment]
This is also essential when trying to edit `Makefile`s since they MUST use tabs, regardless of the user's preference.

**Comment by gwk** [comment]
Another concrete example: I like the `files.trimTrailingWhitespace` option for most source files, but for some file types (e.g. patch files) stripping out whitespace introduces errors.

**Comment by nomaed** [comment]
I am using `.editorconfig` for this and it works great. Also compatible across different editors and IDEs.

Extension: https://github.com/editorconfig/editorconfig-vscode
Spec: http://editorconfig.org/

**Comment by bwinton** [comment]
I'm also running into this editing Javascript (2-space tabs), HTML (4-space tabs), and README.md (word-wrap on)…  Sadly, editorconfig doesn't support wrapping yet, although it looks like it does most of the other stuff I want.

**Comment by mkurnikov** [comment]
It also could be helpful with disabling IntelliSense for the plain text files, like `.txt` and `.md`, it was mentioned here:
https://github.com/Microsoft/vscode/issues/10819

Or disable similar matches to the selection for the same files. 
Plain text files aren't really semantically the same as source code files, there has to be a way to override settings specifically for them.

**Comment by fredrikaverpil** [comment]
This would be useful in order to take advantage of the vertical rulers set to

    {
        "editor.rulers": [72, 79]
    }

which applies to anyone who are working with Python files and wish to follow PEP8 guidelines.

**Comment by exdeniz** [comment]
And another example: disable quickSuggestions for specific file types.

**Comment by eromoe** [comment]
I am using https://github.com/tzvetkoff/sublime_stupid_indent in sublime, which can force html,js ,css, scss , json  in size 2, others in 4 by config,  maybe vscode can take a similar way like that.

PS: though it can't not recognise current file is plain javascript or es6(babel), I hope vscode can do this too.

**Comment by eromoe** [comment]
I find vscode have a similar extention: 
https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
But it isn't global settings, need generate editorconfig for each project.

**Comment by sandy081** [comment]
Will be implemented by #1587.
