### ISSUE TITLE
Unable to submit a jira issue

### ISSUE THREAD

**Issue by MrMedTech** [microsoft/vscode#118721]
- VS Code Version:1.54.1
- 
- OS Version: wsl2 ( Ubuntu-20.04)

Problem:
I try to create a new Jira issue. The problem is, that I don't find users for assignment ( stays empty) but I can find users to mention them with  @...
I can also find parameters like components , projects and labels as expected.

Another thing is, that I always get the hint:
![image](https://user-images.githubusercontent.com/41990590/110794818-6eb46500-8276-11eb-8128-b298ee7bf25e.png)

while there is no external link I want to mention. If I use a random url, the submit executes but does not come up on my board.

In addion, the following popup appears everytime I am searching for users for assignment.
![image](https://user-images.githubusercontent.com/41990590/110794979-999eb900-8276-11eb-8292-705070c3005c.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/causedByExtension

Please report this problem in repo of extension that provides integration with Jira. This repo for VS Code editor itself.
