### ISSUE TITLE
Task with type "npm" and script "build" does not show up in menu

### ISSUE THREAD

**Issue by mscain** [microsoft/vscode#118761]
Issue Type: <b>Bug</b>

1. My `package.json` file:
```
    "scripts": {
        "build": "nwb build-react-component --copy-files --no-demo",
        "XbuildX": "nwb build-react-component --copy-files --no-demo",
    }
```

2. My `tasks.json` file:
```
{
	"version": "2.0.0",
             "tasks": [
		{
			"label": "foo",
			"type": "npm",
			"script": "build",
			"group": "build",
			"problemMatcher": [],
			"detail": "nwb build-react-component --copy-files --no-demo"
		},
		{
			"label": "bar",
			"type": "npm",
			"script": "XbuildX",
			"group": "build",
			"problemMatcher": [],
			"detail": "nwb build-react-component --copy-files --no-demo"
		}
    ]
}
```
3. cmd-shift-b to show build tasks, only XbuildX shows up

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-66-generic
Fetching remote diagnostics for 'SSH: 192.168.0.17' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 13f14d73-375d-499a-a0d8-ed36e5ebdafd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: jean-beta.mattcain.com|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|DO-Regular (2 x 2199)|
|Memory (System)|3.84GB (0.72GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: 192.168.0.17' failed: Canceled
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.3
vscode-remote-extensionpack|ms-|0.20.0
vscode-pull-request-github|Git|0.24.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833cf:30267465

```

</details>

**Comment by mscain** [comment]
Not the same as #93001, the "build" task doesn't show up even if it's the only one

**Comment by mscain** [comment]
I will also note that if another task `dependsOn` "foo", it silently skips that one and goes on to other steps, so it's not simply a menu issue

**Comment by alexr00** [comment]
I'm not able to repro this issue. Are there additional steps or do you have any npm or task related settings set?
![image](https://user-images.githubusercontent.com/38270282/110920808-1d5fb080-831e-11eb-8823-b3ce2f5bd2d7.png)
