### ISSUE TITLE
Korean words start with 'ㄱ' and consonant are broken.

### ISSUE THREAD

**Issue by bluedskim** [microsoft/vscode#118788]
- VS Code Version:1.54.1
- OS Version:Ubuntu 20.10
- GNOME version : 3.38.3
- input method : uim-byeoru

Steps to Reproduce:

1. create a new file
2. copy and paste this word : 각간갇감갑갓갔강갖갗같갘갛
3. compare with title bar. check the differences.
![vscode_korean_display_issue](https://user-images.githubusercontent.com/1418601/110890295-198a5900-8333-11eb-8afd-be34fca6d8c2.png) don't have any problem with other words start not 'ㄱ' character.

Does this issue occur when all extensions are disabled?: Yes

I don't have this issue with other editors in the same machine.

Anyway, thank you very much for the great IDE.
Hope this helps to improve vs code.

**Comment by alexdima** [comment]
Thank you, I can reproduce. This seems to be a problem with `Droid Sans Mono`, which is the default value for `"editor.fontFamily"` on Linux. After installing Fira Code and configuring `"editor.fontFamily: "Fira Code"`, the Korean text renders correctly:


https://user-images.githubusercontent.com/5047891/120893089-99158480-c611-11eb-8928-403d80d6b347.mp4

Given this does not reproduce with Fira Code, I believe this is an issue with the font family `Droid Sans Mono`. I am not sure what the project page is, but a bug should be created against that project.

**Comment by bluedskim** [comment]
> Thank you, I can reproduce. This seems to be a problem with `Droid Sans Mono`, which is the default value for `"editor.fontFamily"` on Linux. After installing Fira Code and configuring `"editor.fontFamily: "Fira Code"`, the Korean text renders correctly:
> 
>  Kapture.2021-06-05.at.15.20.14.mp4 
> Given this does not reproduce with Fira Code, I believe this is an issue with the font family `Droid Sans Mono`. I am not sure what the project page is, but a bug should be created against that project.

@alexdima Thank you very much :-)
