### ISSUE TITLE
Hide unused folder and files 

### ISSUE THREAD

**Issue by anaskoara** [microsoft/vscode#118798]
Issue Type: <b>Feature Request</b>

Hi
When you have fairley large project with large number files and folder, 
I think there sould be way to hide folder and files that I don;t work on them 
to increase preformance and and reduce time looking for file 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kmvan** [comment]
.gitignore?

**Comment by gjsjohnmurray** [comment]
Please look at the `files.exclude`setting.

See also #117845 for pointers to extensions that help update that setting. You might also want to support that proposal for an enhancement to make it a built-in feature. If you do, add 👍 to the issue (not to any subsequent comments on the issue, as your vote won't count there).

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for answering
