### ISSUE TITLE
Request timeout while updating VSCode on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by yisenliu** [microsoft/vscode#118785]
Issue Type: <b>Bug</b>

1. open vscode
2. check update from the menu 'Code'

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|8.00GB (2.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.17
vscode-great-icons|emm|2.1.67
prettier-vscode|esb|5.9.2
auto-rename-tag|for|0.1.6
rest-client|hum|0.24.4
vscode-language-pack-zh-hant|MS-|1.54.2
vetur|oct|0.33.1
indent-rainbow|ode|7.5.0
LiveServer|rit|5.6.1
vscode-workspace-switcher|sad|1.15.3
vue-vscode-snippets|sdr|2.2.0
markdown-preview-enhanced|shd|0.5.16
sass-indented|syl|1.8.16

(3 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you show me a screenshot of the error? Are you behind a proxy? IS this a new issue or has it happened for a while?
