### ISSUE TITLE
option to disable explorer filtering

### ISSUE THREAD

**Issue by yoyoys** [microsoft/vscode#118712]
Filtering is a good feature for search something at left panel, but it also harm keyboard shortcuts.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/22124891/110773452-b8fa0e00-8297-11eb-97a7-c431c9932200.png">
For example, if I'm filtering something at Source Control panel, I can't use hotkeys like `Cmd + shift + G` to focus commit message input, it's so annoying.

**Comment by joaomoreno** [comment]
Change `workbench.list.keyboardNavigation` to `simple`.
