### ISSUE TITLE
Select a Language button is at the top

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#118719]
I opened my codespace today and I saw following - **Select a Language** button is on top

![image](https://user-images.githubusercontent.com/10746682/110792800-2136f880-8274-11eb-9ab6-94b08613b3de.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/118694
But I can not reproduce, neither locally nor in codespaces


![Screenshot 2021-03-11 at 14 20 08](https://user-images.githubusercontent.com/1926584/110793434-e5e8f980-8274-11eb-8a7f-9ebeb6e331ee.png)
