### ISSUE TITLE
Opens old version of program

### ISSUE THREAD

**Issue by smprov22** [microsoft/vscode#118775]
Issue Type: <b>Bug</b>

I have the newest version of VS Code downloaded on my computer.  Whenever I click the icon on the taskbar, it opens the November 2020 version instead of the February 2021 update.  I have to go into my program files and open the Application file from there to get the correct version.  I tried pinning to the taskbar once the correct version is open, but the same issue happens next time I open the program.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (17.98GB free)|
|Process Argv|--crash-reporter-id 8abcc16c-9fa5-4401-bac8-aa686ace361c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|3.1.0
prettier-vscode|esb|5.9.2
csharp|ms-|1.23.9
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by joaomoreno** [comment]
I suggest you hunt down all versions installed in your system, uninstall them and finally reinstall VS Code.
