### ISSUE TITLE
Ctrl + c in find field doesnt work

### ISSUE THREAD

**Issue by b3wii** [microsoft/vscode#118732]
- VS Code Version: 1.54.1
- OS Version: Win10

Steps to Reproduce:

1. Click in find field (right top corner)
2. Mark all text in find field
3. Press ctrl + c to copy
4. Find out that vs code didnt copy the marked text

Does this issue occur when all extensions are disabled?: Who knows..

**Comment by rebornix** [comment]
@b3wii can you please run “Toggle Keyboard Shortcut Troubleshooting” command from command palette and then try to reproduce this issue and share the log?

**Comment by b3wii** [comment]
> @b3wii can you please run “Toggle Keyboard Shortcut Troubleshooting” command from command palette and then try to reproduce this issue and share the log?

I did run the command "Toggle Keyboard Shortcut Troubleshooting" but the problem still persists..
Ctrl + c works everywhere in vscode except in "find in file search field" (top right corner).

**Comment by b3wii** [comment]
Btw, this also happens to the replace field below.

**Comment by b3wii** [comment]
I accidentally closed the ticket. Btw, its not only the find field but also the replace field below.
