### ISSUE TITLE
Allow extension-owned terminals to opt out of being a persistent terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118726]
Currently we enable the persistent terminal/reconnect feature if a terminal is launched by an extension, unlike the env var relaunch where we disable outright because it can cause issues with the extension as it loses access to the terminal upon relaunch.

Relaunching the PowerShell extension right now for example is a bit of a weird experience though because it creates the "PowerShell Integrated Console", and that reconnects upon reload but is no longer managed by the extension.

Before reload:

![image](https://user-images.githubusercontent.com/2193314/110803154-bfef3500-8233-11eb-988a-357a56da9cee.png)

After reload it is restored, but no longer owned by the extension:

![image](https://user-images.githubusercontent.com/2193314/110803196-cda4ba80-8233-11eb-97f1-54244d8ee1c2.png)

Assigning to March for exploration.

Thoughts @TylerLeonhardt @andschwa?

**Comment by TylerLeonhardt** [comment]
> Currently we enable the persistent terminal/reconnect feature if a terminal is launched by an extension

I think just allowing opt-out/opt-in on this behavior would be more than enough for PowerShell's case.

**Comment by andschwa** [comment]
Has there been any progress on this? Now that persistent terminals are the default, this gets quite annoying and bothers users when extension-owned terminals come back but aren't actually connected.

**Comment by Tyriar** [comment]
No progress, we'll try get it in the next version

**Comment by meganrogge** [comment]
proposal:

```
export interface TerminalOptions {
      /**
	* Opt-out of the default terminal persistence on restart and reload
        */
      disablePersistence?: boolean;
}
```

**Comment by andschwa** [comment]
@meganrogge Is this still ongoing and targeted for February?

**Comment by meganrogge** [comment]
Yes it is
