### ISSUE TITLE
Hanging 

### ISSUE THREAD

**Issue by Maniiish2** [microsoft/vscode#118805]
Issue Type: <b>Bug</b>

I'm facing problem . its too laggey

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.4.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1448)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.67GB (0.30GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 191f1378-a3dc-4410-b7f6-2112fa417138|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pantheon|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pantheon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (115)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
node-essentials|afr|1.1.0
html-class-suggestions|And|1.0.7
ng-template|Ang|11.2.6
vscode-color|ans|0.4.5
vscode-icontheme-nomo-dark|be5|1.3.6
node-json-autocomplete|bhs|0.1.3
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.9
node-snippets|chr|1.3.2
path-intellisense|chr|2.3.0
bracket-select|chu|2.0.2
ccs-flutter-color|cir|1.0.1
rainbow-highlighter|cob|0.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
vscode-mac-color-picker|dae|1.0.1
auto-dark-mode-windows|dan|1.0.9
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.16
githistory|don|0.6.15
es7-react-js-snippets|dsz|3.1.0
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.45
vscode-npm-script|eg2|0.3.17
react-node-snippets|ej|0.0.2
vue-format|feb|0.1.8
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
php-file-types|fet|1.3.0
node-version|fiv|0.0.1
flow-for-vscode|flo|1.5.0
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.24.0
vscode-test-explorer|hbe|2.19.5
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscodefy|iag|0.0.11
vscode-php-snippets|jar|0.0.9
search-node-modules|jas|1.3.0
react-component|jer|1.0.4
wanwu-goto-node-modules|jin|1.0.1
php-cs-fixer|jun|0.1.158
rn-full-pack|kel|0.7.0
kite|kit|0.142.0
php-add-property|kot|1.1.0
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
node-pack|mal|0.0.1
identical-sublime-monokai-csharp-theme-colorizer|max|0.11.1
pretty-formatter|mbl|0.2.2
php-constructor|Meh|0.1.2
php-namespace-resolver|Meh|1.1.8
mez-editor|mez|0.23.0
vscode-language-babel|mgm|0.0.30
php-server-vars-snippets|Mih|0.0.3
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.10.0
vscode-kubernetes-tools|ms-|1.3.0
remote-containers|ms-|0.163.2
sublime-keybindings|ms-|4.0.7
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.3912
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.0
color-highlight|nau|2.3.0
php-docblocker|nei|2.1.0
html-fmt-vscode|Nik|0.7.0
php-productive-pack|one|1.0.0
phpunit-snippets|one|1.1.0
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.5.0
highlight-counter|ram|1.6.0
vscode-phpunit|rec|2.0.76
fabric8-analytics|red|0.3.2
vscode-commons|red|0.0.4
vscode-yaml|red|0.16.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
php-debug|rob|1.14.0
mongo-snippets-for-node-js|roe|1.3.5
hackmud-color|Sam|0.3.4
code-settings-sync|Sha|3.4.3
vue-helper|she|2.4.7
prettier-vscode|Sim|2.0.7
php-formatter|Sop|0.2.4
autoimport|ste|1.5.3
code-spell-checker|str|1.10.2
node-pack|Swe|0.1.16
node-dependencies|tsc|1.2.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.11
angular-node-pack|viv|0.1.1
gitblame|wad|6.0.2
quokka-vscode|Wal|1.0.347
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
delete-node-modules|Wsc|1.0.6
vue|Wsc|1.0.26
better-align|wwm|1.1.6
sublime-commands|Zar|0.1.0
html-css-class-completion|Zig|1.20.0
vue|znc|0.6.3

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Also please follow https://github.com/microsoft/vscode/wiki/Performance-Issues to provide info that needed to investigate performance issues.
