### ISSUE TITLE
super slow vscode 

### ISSUE THREAD

**Issue by darwin808** [microsoft/vscode#118861]
Issue Type: <b>Performance Issue</b>

super slow vscode 

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:11.840Z)
OS version: Linux x64 5.8.0-44-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3899)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|7.72GB (1.83GB free)|
|Process Argv|--disable-gpu --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   134	  2533	code main
    0	    40	  2557	   zygote
    1	    79	  2589	     gpu-process
    0	    40	  2558	   zygote
    3	    95	  3404	     window (Issue Reporter)
    0	    63	  2598	   utility
    0	   127	  2667	   shared-process
    0	    63	  2700	     ptyHost
    0	     0	  3182	       /usr/bin/zsh
    0	     0	  3453	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  3454	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   277	  2941	   window (.gitpod.Dockerfile - darwin - Visual Studio Code)
    0	    95	  2963	     extensionHost
    0	   111	  3000	       electron_node tsserver.js 
   12	   340	  3001	       electron_node tsserver.js 
    0	    79	  3079	         electron_node typingsInstaller.js typesMap.js 
    0	   997	  2975	     watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (.gitpod.Dockerfile - darwin - Visual Studio Code)
|    Folder (darwin): more than 21267 files
|      File types: cache-7(142) ICEauthority(1) Xauthority(1) Xdefaults(1)
|                  Xresources(1) bash_history(1) bash_logout(1) bashrc(1)
|                  46(1) TAG(1)
|      Conf files:;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by dougalg** [comment]
I am also experiencing the same issue, on MacOS 11.2.2, same version of VS Code.

**Comment by darwin808** [comment]
I just noticed if I toggle the developer tools and start recordiong for performance the lag is gone.Why ?

**Comment by Teemneem** [comment]
super slow

**Comment by dbaeumer** [comment]
Without a trace or additional information this is very hard to execute on. Please see https://github.com/microsoft/vscode/wiki/Performance-Issues on how to reprot performance problems with VS Code.

**Comment by sgehrman** [comment]
super slow.  I'm on linux.  Just started happening.  I just got a new machine, so I'm not sure if it's the machine or the VSCode update. But VSCode is almost unusable on a 5ghz 5950x 32 core.  So slow. Go to definition.  Format on save.  Everything.
