### ISSUE TITLE
Please update the variable explorer like Spyder... I'm waiting

### ISSUE THREAD

**Issue by Ikhwansong** [microsoft/vscode#118890]
I have searched, is there any extension or feature to alternate the default variable explorer built in vscode.

But there were nothing. In terms of a brief test or to checking the variables produced by running a main code, the spyder's variable explorer is very convenient.

why is there not yet like that?

**Comment by jsh9** [comment]
+1 to this issue.  Even for non-scientific developments, being able to view a Python list/set like a vertical table and a Python dict like a two-column table is a big boost to productivity.

**Comment by connor4312** [comment]
Extensions can build alternative variable explorers if they want. If you have specific requests for improvements to the Variables view in VS Code, please let us know 🙂
