### ISSUE TITLE
VS Code is automatically taking my C Drive in explorer.

### ISSUE THREAD

**Issue by Bhabesh02** [microsoft/vscode#118875]
Issue Type: <b>Feature Request</b>

Hello Team,

I am having issue while installing application Visual Studio Code Application. I want someone's guidance in installing it as it is taking my C drive name directly.

Regards,
Bhabesh Dutta

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/editor/portable for how to set up a VS Code instance without using any C-drive space.

**Comment by dbaeumer** [comment]
@gjsjohnmurray thanks.

Will close the issue. Please ping if there is still something unclear with clear steps about what you try to achieve and why it fails.
