### ISSUE TITLE
Add `multipleSelectionSupport` to `IWorkbenchAsyncDataTreeOptionsUpdate`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#118829]
Extension provided tree views are in a tricky state right now. 
On one hand we need to make sure that all the tree properties are set correctly, like multiple selection support. This can only be set after the extension has activated. However, waiting for all extensions to activate in response to `onView` might be slow and is hard to wait for.
On the other hand, extension trees are now created too eagerly (https://github.com/microsoft/vscode/issues/117679), which was originally done to solve the first problem.

If `multipleSelectionSupport` can be updated, then this solves all problems.

**Comment by joaomoreno** [comment]
@alexr00 Sorry for the delay here. I pushed it but haven't really tested it out. Let me know if something doesn't work in your land.

**Comment by alexr00** [comment]
@joaomoreno I'm not seeing it work. Should it be as simple as calling `updateOptions` with the new `multipleSelectionSupport` value?

Branch with my change: https://github.com/microsoft/vscode/tree/alexr00/instantiateTreeLater
You can use the tree-veiw-sample's test view (it gets added in the explorer viewlet) to test against.

**Comment by joaomoreno** [comment]
Some things are working (<kbd>Ctrl A</kbd>) but others aren't (mouse gestures). On it!

**Comment by alexr00** [comment]
Works great, thank you!

**Comment by joaomoreno** [comment]
@alexr00 Verified? 🚀

**Comment by alexr00** [comment]
Verified.
