### ISSUE TITLE
File/Character Encoding

### ISSUE THREAD

**Issue by reasoning** [microsoft/vscode#118895]
Issue Type: <b>Bug</b>

This occurs with VS Code under Linux.

Open a text file in vi/notepad or similar basic editor.

Paste the text from the "escape" BNF grammar found here into the text file as a C++ comment (or code, see below) and save as a .cpp file.  Verify that you can compile this with GCC/Clang.

https://www.w3.org/TR/CSS1/#appendix-b

escape		{unicode}|\\[ -~¡-ÿ]

i.e.
```
bool CssParser::IsEscaped()
{
	// @reference [http://www.w3.org/TR/CSS1#appendix-b]
	// unicode		\\[0-9a-f]{1,4}
	// escape		{unicode}|\\[ -~¡-ÿ]

	return (Is('\\') && (IsHex(1) || IsPrintable(1) || IsRange(1,'¡','ÿ')));
}
```
Open the same file in VS Code then modify something and then save, the text will have been converted into UTF8 with 3 bytes being used to represent the Latin1 ASCII character that was previously there.

This then becomes un-compilable since C++ doesn't natively compile UTF8 strings.
```
bool CssParser::IsEscaped()
{
	// @reference [http://www.w3.org/TR/CSS1#appendix-b]
	// unicode		\\[0-9a-f]{1,4}
	// escape		{unicode}|\\[ -~�-�]

	return (Is('\\') && (IsHex(1) || IsPrintable(1) || IsRange(1,'�','�')));
}
```
You will get a compiler error similar to the following:
``
error: character too large for enclosing character literal type
        return (Is('\\') && (IsHex(1) || IsPrintable(1) || IsRange(1,'�','�')));
```                                                                     ^



VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:11.840Z)
OS version: Linux x64 5.9.0-kali1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|7.75GB (0.13GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
cpptools|ms-|1.2.2
material-theme|zhu|3.9.15

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464

```

</details>

<!-- generated by issue reporter -->

**Comment by reasoning** [comment]
Replacing the literals with \x encoded C++ characters allows me to continue to compile, but this is not an issue on Windows or in Visual Studio (not Code) as the characters remain ASCII Latin1 encoded as they should.

bool CssParser::IsEscaped()
{
	// @reference [http://www.w3.org/TR/CSS1#appendix-b]
	// unicode		\\[0-9a-f]{1,4}
	// escape		{unicode}|\\[ -~\xa1-\xff]
	
	return (Is('\\') && (IsHex(1) || IsPrintable(1) || IsRange(1,'\xa1','\xff')));
}

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by reasoning** [comment]
Thanks for looking into it, that's great that its configurable.

I guess a reasonable argument could be made that the default encoding for .cpp .hpp .c .h files should not be UTF-8 though ?

And also, why was a file that only has high ASCII bytes (\xa1,\xff) auto detected as UTF-8 and not Windows 1250 (Latin1)  ??

**Comment by reasoning** [comment]
That wasn't a question.  I was politely pointing out an obvious bug.  C++ source files are not UTF-8, ill spell it out.
