### ISSUE TITLE
Reduce Sash Minimum size

### ISSUE THREAD

**Issue by DRSDavidSoft** [microsoft/vscode#118852]
## Current Issue
Currently, the minimum allowed value for `workbench.sash.size` is **`4`**, which I believe to be _too_ **thick**.

## Feature Request
I would like to ask that the user would be able to set the `workbench.sash.size` to **`2`**, if desired by the user.  I believe **2** is an acceptable level for the display I'm using, and it's more pleasant than the thick **4** value.

I'm also fine with a value of **1**.

## Alternative feature request
Provide an alternative option for `workbench.sash.displaySize` that would define how thick should the line appear, while keeping the original parameter to a greater value.  This would allow the user to resize the panels more freely, but still display a thin line.

If it is _not_ accepted to use a value below **4** for the actual setting, this would also be highly appreciated.

**Comment by sbatten** [comment]
It looks like @joaomoreno and @lszomoru have set the minimum, leaving to them to decide if 2 is safe

**Comment by DRSDavidSoft** [comment]
If it's possible to implement the alternative method (`displaySize` thinner than actual `size`), I'd also appreciate it (in fact, as a user, I prefer this).

**Comment by joaomoreno** [comment]
I'd go with lowering the minimum for `workbench.sash.size`, but when `< 4` it would only affect display size.

**Comment by joaomoreno** [comment]
Verification:

- Setting has new value range: `[1, 20]`
- UI size will clamp the setting value to `[1, 4]`
- Grabbing area size will clamp the setting value to `[4, 20]`
