### ISSUE TITLE
terminal exists with error message

### ISSUE THREAD

**Issue by PeterIsaac-luftborn** [microsoft/vscode#118884]
Issue Type: <b>Bug</b>

open vscode
open terminal
try to write anycommand 
the following message will appear
The connection to the terminal's pty host process is unresponsive, the terminals may stop working

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (21.61GB free)|
|Process Argv|--crash-reporter-id 1f68ef10-fdeb-4a34-9f8b-992e80f2318e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
svelte-intellisense|ard|0.7.1
armview|ben|0.4.5
gitlens|eam|11.3.0
docker-explorer|for|0.1.7
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
azure-account|ms-|0.9.7
azurecli|ms-|0.5.0
cpptools|ms-|1.2.2
vscode-node-azure-pack|ms-|0.1.0
azurerm-vscode-tools|msa|0.15.0
svelte-vscode|sve|104.6.4
custom-xml-formatter|tho|1.2.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
