### ISSUE TITLE
Cannot set display language to Simplified Chinese on macOS

### ISSUE THREAD

**Issue by ybw0014** [microsoft/vscode#118834]
Issue Type: <b>Bug</b>

After disabled all extensions and remove SC lang pack, close vscode.
Then open vscode and install SC lang pack, then configure display language to zh-cn. After I restart vscode, the display language is still English.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 20.4.0

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.54.2

</details>

**Comment by dbaeumer** [comment]
@ybw0014 ybw Is the SC language pack enabled after you installed it. Might be VS Code still tracks the extension as disabled?

**Comment by ybw0014** [comment]
@dbaeumer I believe the language packs are always enabled, since I can neither enable nor disable them. 
I have tried some other language packs, they all work fine.

**Comment by dbaeumer** [comment]
@ybw0014 you are correct. Sorry for that. 

When running the command `Configure Display Language` is the SC LP in the list?

**Comment by ybw0014** [comment]
@dbaeumer The installed language packs are all displayed. I tried es, zh-tw, these two language packs work fine, but zh-cn does not.

**Comment by dbaeumer** [comment]
@ybw0014 that is very wired. Might be a corrupted cache. Is there anything in the developer console (Help -> Toggle Developer Tools?)

**Comment by dbaeumer** [comment]
Just tested it and it is not a general problem.
<img width="1128" alt="capture" src="https://user-images.githubusercontent.com/1931590/111451536-d274dd00-8711-11eb-89ed-696166bf8e3a.png">

**Comment by ybw0014** [comment]
@dbaeumer I think you tested it on windows. The SC language pack on windows works fine, but not on macOS.

**Comment by dbaeumer** [comment]
@ybw0014 yes, but they are the same language packs so usually the OS doesn't make a difference.

@isidorn can you please check whether the SC language pack works for you on Mac OS.

**Comment by isidorn** [comment]
Simplified Chineese works for me on my macOS 

![Screenshot 2021-03-18 at 09 58 41](https://user-images.githubusercontent.com/1926584/111599445-8fc60a00-87d0-11eb-8987-20f710394beb.png)

**Comment by ybw0014** [comment]
I tried fully uninstall vscode and reinstall it, the SC language pack now works.

**Comment by dbaeumer** [comment]
@isidorn thanks.

@ybw0014 glad that fixed it but still doesn't explain why?
