### ISSUE TITLE
postinst script adds vscode repo on Raspberry Pi OS, although the packages are present in the existing repo

### ISSUE THREAD

**Issue by XECDesign** [microsoft/vscode#118825]
- VS Code Version: any
- OS Version: Raspberry Pi OS

Steps to Reproduce:

1. `apt install code`
2. postinst adds vscode repo and MS key although it's not required

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
I don't think we can e2e verify this until stable is released, so marking as verified after code review.
