### ISSUE TITLE
[Bug] Command `Git: Stage Change` has no effect

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#118898]
- VS Code Version: v1.54.2
- OS Version: Windows 10

Steps to Reproduce:

1. Please see https://stackoverflow.com/q/65606564/7881859

Does this issue occur when all extensions are disabled?: Yes

**Comment by wenfangdu** [comment]
@lramos15 Have you tried `git.stageChange`? It has no effect whatsoever.

**Comment by wenfangdu** [comment]
@lramos15 If you bind it to a shortcut, then you can use the shortcut:

![image](https://user-images.githubusercontent.com/28700378/137258374-221011bb-c27b-4e06-af9d-607c1be4c6e6.png)

**Comment by lszomoru** [comment]
The `git.stageChange` command only appears (it is explicitly configured not to show up in the command palette) in the in-line diff editor, that can be accessible by clicking on the SCM editor decoration (added/edited/deleted lines) available in the left hand gutter of the editor (screenshot). 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/3372902/151370089-625d7fab-bef4-49bc-b4be-1fe93e9c68db.png">

The `Git: Stage Changes` and `Git: Stage All Changes` are the commands means to be used to stage changes for one/all file(s).
