### ISSUE TITLE
Escape on multiple select may shrink to focus

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#118835]
Issue Type: <b>Feature Request</b>

With the new `selectionNavigation` mode, users can easily go from single selection mode to multi selection by press shift+arrows. I would expect pressing `escape` key to revert back to single focus/selection mode but now it  clears focus and all selections. Something we can consider

* Users select mutiple cells 
* Escape will shrink selections to single focus/selection
* Another escape will then clear all selections + focus

VS Code version: Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:15:23.749Z)
OS version: Darwin x64 20.3.0

**Comment by joaomoreno** [comment]
So pressing <kbd>Escape</kbd> would have two stages? That could work for all lists/trees actually.

**Comment by isidorn** [comment]
I think this makes good sense for all trees. Also for consistency we should do it in all trees.

**Comment by rebornix** [comment]
Regarding a11y, I also believe shrinking is better than list view goes focus/selection-less, unless users rely on `Escape` to move focus back to the list view. but again, with the two steps, users can still go to the list view by pressing escape twice, but it's hard to deselect and move focus back to its original position.

**Comment by roblourens** [comment]
Thanks for tackling this, it's been bugging me. Noticed a couple issues:

- It doesn't work when focus=0
- It reduces the multiselection to one selected item. I'd rather it clear the selection entirely and leave the focused item. For example a side effect of this is that in the explorer it opens the file under focus when you press escape.

I'll push a commit to fix these but feel free to revert it or do it differently

**Comment by roblourens** [comment]
Had to update it to not break the selection for notebooks, checking `WorkbenchListSelectionNavigation`

**Comment by haaami01** [comment]
> Probléma típusa: Funkciókérés
> 
> Az új `selectionNavigation`móddal a felhasználók könnyedén válthatnak az egyszeri kiválasztás módból a többszörös kiválasztásba a Shift+nyilak megnyomásával. Azt várnám, hogy a `escape`gomb megnyomásával visszatérjen az egyszeri fókusz/kiválasztás módba, de most törli a fókuszt és az összes kijelölést. Valami, amit megfontolhatunk
> 
> * A felhasználók több cellát választanak ki
> * Az Escape funkció egyetlen fókuszba/kiválasztásra csökkenti a kijelöléseket
> * Egy másik menekülés ezután minden kijelölést és fókuszt töröl
> 
> VS Code verzió: Code - Insiders 1.55.0-insider ( [9b2ee7f](https://github.com/microsoft/vscode/commit/9b2ee7fb7d970b9a628fdb3545bdd01d67078d16) , 2021-03-11T05:15:23.749Z) OS verzió: Darwin x64 20.3.0

**Comment by joaomoreno** [comment]
@roblourens Makes sense! Thanks for verifying and fixing! ❤️
