### ISSUE TITLE
Hide "Update to x.x.x" in extensions downgraded manually

### ISSUE THREAD

**Issue by tomma5o** [microsoft/vscode#118831]
- VS Code Version: 1.54.2
- OS Version: macOS Big Sur 11.2.1

### Steps to Reproduce:

1. Open the extension panel
2. Choose an extension and install a specific version (older one)
3. The "Update to x.x.x" green label appears

![image](https://user-images.githubusercontent.com/8134038/110971289-f6739f80-835a-11eb-8c82-7d04df8659a3.png)

### Expected Result:

After I manually downgraded to an older version the extension hide the "Update to x.x.x" green label,
 after another update occurs

![image](https://user-images.githubusercontent.com/8134038/110971456-35095a00-835b-11eb-8688-aae60ab147f9.png)

**Comment by TylerLeonhardt** [comment]
@tomma5o it sounds like you just don't wanna see the button? Why not? If VS Code had an issue that broke the latest version of X version of Y extension, and then VS Code does a release that fixes that version, you may want to update to version X.

**Comment by tomma5o** [comment]
Hi @TylerLeonhardt,
Yeah right, if the extension releases another version after I downgraded yes, the button must show up.

But IMO for example, the GitHub theme doesn't release an update for one year, I see the icon for one year and that keeps me looking at the version manually if there is really another update.

I think is more correct when from the latest version I downgrade to another one, the badge and the button is hidden until there is another update.

Make sense?
