### ISSUE TITLE
No crash report is generated for our extension's cpptools-srv child process

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#118850]
- VS Code Version:1.54.2
- OS Version: Windows or Mac.

Steps to Reproduce:

1. Issue https://github.com/electron/electron/issues/20234#event-4452251253 referred me to https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports so I followed those steps, i.e. run `"code --crash-reporter-directory <absolute-path>" `
2. Install the C/C++ extension, version 1.2.2.
3. Do the repro steps at https://github.com/microsoft/vscode-cpptools/issues/7085, which are "git clone https://github.com/thedmd/imgui-node-editor", open imgui_node_editor_internal.h, click the "Link" identifier on line 739. That should cause VS Code to launch cpptools, which in turn launches cpptool-srv (which crashes).
4. Wait for it to crash -- it'll need to out-of-memory (so you should see memory increasing by the GB).

Bug: No crash report is generated at the crash-reporter-directory-folder (it gets populated with some other files by VS Code).

Does this issue occur when all extensions are disabled?: N/A

**Comment by sean-mcmanus** [comment]
The repro described above won't repro with 1.3.0-insiders of the C/C++ extension, so you'd need to set the C_Cpp.updateChannel to "Default" if you're using VS Code Insiders (i.e. make sure you're using 1.2.2 of our extension).

**Comment by deepak1556** [comment]
I am unable to repro the OOM issue with `1.55-insiders` on MacOS, some follow-ups:

* Can you provide the contents of the crash folder
* Can you start the app with `--disable-crash-reporter`, this should default to the system console report

**Comment by sean-mcmanus** [comment]
What version of the C/C++ extension are you using? You need to make sure you have 1.2.2 and not 1.3.0-insiders (the default is 1.3.0-insiders if you're using VS Code Insiders). Setting the C_Cpp.updateChannel to "Default" and/or setting autoUpdate to "false" and manually downgrading should work.

If not, let me know, and I can get you the info you requested.

**Comment by deepak1556** [comment]
I am on `1.3.0-insiders` but did set `C_Cpp.updateChannel to "Default"` when testing.

**Comment by sean-mcmanus** [comment]
Setting the updateChannel to "Default" is supposed downgrade from 1.3.0-insiders to 1.2.2. It might be hitting some issue. Can you manually downgrade to version 1.2.2?

**Comment by deepak1556** [comment]
```
CPU %	Mem MB	   PID	Process
    0	   360	 31669	   window (imgui_node_editor_internal.h)
    0	   131	 31670	     extensionHost
    0	   131	 31729	       /Users/demohan/.vscode/extensions/ms-vscode.cpptools-1.2.2/bin/cpptools
    0	   229	 31777	         /Users/demohan/.vscode/extensions/ms-vscode.cpptools-1.2.2/bin/cpptools-srv 31729 {705D3DE0-E5AB-41A0-A231-9E720AFB1F25}

```

**Comment by sean-mcmanus** [comment]
You're not reproing the out of memory crash?

Does your repro look like this screenshot? You may need a C++ compiler that supports C++17 installed or it may not be able to parse up to the required point correctly.

![image](https://user-images.githubusercontent.com/19859882/112207498-6f34f000-8bd4-11eb-9480-efa3c33de76f.png)

**Comment by deepak1556** [comment]
No OOM crash, the compiler supports c++17. But the cpp configuration file was defaulting to c++11, after adjusting it was able to repro the memory leak.

Not sure if the chromium crash reporter is installed/ can work correctly on the leaf node process like since it is not spawned by the app. These processes should default to system crash handlers, it is a bug that doesn't happen.

```
Browser process
  - Workbench Render process
    - Extension Host
      - cpptools
        - cpptools-srv
```

Please use the following to disable crashpad handler

* Start the app with `--disable-crash-reporter`

or

* Open Command Palette
  * Configure Runtime Arguments
  * "enable-crash-reporter": false

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/118767
