### ISSUE TITLE
toggle line coment does not 

### ISSUE THREAD

**Issue by nm7427** [microsoft/vscode#118863]
Issue Type: <b>Feature Request</b>

I am not able add # using any short cut keys previously it was working now it does 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by nm7427** [comment]
I am not able comment the line in VSCode ctrl+/ used work previously now it does not

**Comment by gjsjohnmurray** [comment]
Please check your keybindings as described in https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by buffet-time** [comment]
> Please check your keybindings as described in https://github.com/microsoft/vscode/wiki/Keybinding-Issues

My Ctrl + / works in all my file types except .TS now for some reason.

**Comment by alexdima** [comment]
@nm7427 @buffet-time 

Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+/`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`ctrl+/`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
