### ISSUE TITLE
Crooked menus in VSCode 1.54.2

### ISSUE THREAD

**Issue by Youcodekid1** [microsoft/vscode#118814]
- VS Code Version: 1.54.2
- OS Version:  Linux Mint 19.3 Cinamone (4.4.5 Cinamon version )

Steps to Reproduce:

1. I had started VScode
2. I saw these crooked  #menus 

Does this issue occur when all extensions are disabled?: Yes/No

Hello, there is strange performance of context menus in Linux Mint 19.3 Cinamone (4.4.5 Cinamon version ). Default menus: "Selection, View, Go, Run, Terminal, Help " are crooked like this:

![obraz](https://user-images.githubusercontent.com/80458838/110934417-4720d380-832e-11eb-82fe-14643db92458.png)

"File" and "Edit" menus are ok . No meter if I have used fresh install from snap or offical download webpage. 
 Cheers, Kris

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/116402

Please use custom titlebar as workaround `"window.titleBarStyle": "custom"`

**Comment by Youcodekid1** [comment]
thx, It is ok now
