### ISSUE TITLE
Failing notebook integration test

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118889]
If you run this test by itself, it fails: https://github.com/microsoft/vscode/blob/eac163c061119e1cc80bde5dd94b6508185b4cc1/extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts#L1135

```
    1) Opening a notebook should fire activeNotebook event changed only once
  0 passing (5s)
  1 failing
  1) Notebook API tests
       Opening a notebook should fire activeNotebook event changed only once:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:130:11)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

Is `openNotebookDocument` supposed to open an editor? Seems like maybe not. I think it only passes normally because it gets the event from some previous test. Also it's not testing that the event is only fired once, it's testing that it's fired at all.

cc @DonJayamanne

**Comment by jrieken** [comment]
> Is openNotebookDocument supposed to open an editor? Seems like maybe not.

Right. It should be _show_NotebookDocument. I didn't see the test failing but I am pushing some optimistic changes that use `show` and make sure it actually that notebook that's showing
