### ISSUE TITLE
::-webkit-details-marker pseudo element selector is deprecated

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118818]
Open https://vscode-web-test-playground.azurewebsites.net/?enter=true

`::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.`

**Comment by mjbvz** [comment]
@sandy081 This seems to come from the extension page css:

https://github.com/microsoft/vscode/blob/3006ac8e9406b31e1e55d5226df5ce477f7675c8/src/vs/workbench/contrib/extensions/browser/media/extensionEditor.css#L371
