### ISSUE TITLE
Git rebase stuck after resolving conflicts

### ISSUE THREAD

**Issue by apradhan12** [microsoft/vscode#118886]
VSCode Version: 1.54.2
OS Version: Windows 10

Steps to Reproduce:
1. Check out a branch that has conflicts with master/main branch
2. Run `git rebase master`
3. Resolve conflicts in VS Code
4. Click the ✔️ icon in VS Code Git side panel

Result: the progress bar keeps rolling but never successfully rebases. I have to go to console and manually run `git rebase --continue`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Kurt-von-Laven** [comment]
Our team has also encountered this issue frequently on both Linux and Windows. We do use GitLens and haven't tested with all extensions disabled.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/114461
