### ISSUE TITLE
Turning off tab completions does not turn off the tab completions when editor.sugest.snippetsPreventQuickSuggestions setting to be true

### ISSUE THREAD

**Issue by taoeer** [microsoft/vscode#118810]
#114427

I think this can be better user experience that only move cursor to next position when press tab . Insert suggestion when press enter.

**Comment by jrieken** [comment]
Sorry but we cannot change this anymore. I do understand the frustration and confusion but you have to understand that there are many users that want the exact opposite of this, namely suggestions off. "On by default" breaks snippet interactions, like tab for next place holder, and therefore the default is off
