### ISSUE TITLE
Icon for .eslintcache

### ISSUE THREAD

**Issue by Yash-Singh1** [microsoft/vscode#118849]
Add an icon for the `.eslintcache` file:
![Screenshot from 2021-03-12 15-28-52](https://user-images.githubusercontent.com/53054099/111009159-afc87a00-8347-11eb-984f-9b063839690a.png)

**Comment by dbaeumer** [comment]
@aeschli can I do that from my extension or how do we define these icons.

**Comment by aeschli** [comment]
You need to make a feature request to https://github.com/jesseweed/seti-ui
