### ISSUE TITLE
D instead of d in the windows profile folder stopped the PowerShell extension from running

### ISSUE THREAD

**Issue by DanaMW** [microsoft/vscode#118816]
Issue Type: <b>Bug</b>

I have two windows 10 machines. I synced ALL the settings for code from one machine completely to the other. Both the .vscode directory and the ...\dana\AppData\Roaming\Code directories.
On one machine I am Dana and the other I was dana. I spent 4 days solid trying to find why PowerShell extension would not run when code  loaded causing cascading failures. `C:\Users\Dana` needed to be `C:\Users\dana` for the nightmare to end. I would not have imagined until now that on a windows machine case was a killer. But I understand FULLY now. We are green. 
I am reporting it only to make sure you want it to be that way. Seems unnecessary. Thank you for all you do. VS Code is WOW.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.63GB free)|
|Process Argv|D:\\bin --crash-reporter-id 82695f77-3f76-4146-8535-f37ce5e36e3c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
vscode-color|ans|0.4.5
statusbar-commands|anw|1.2.0
vscode-custom-css|be5|5.0.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.39.0
jshint|dba|0.11.0
vscode-eslint|dba|2.1.17
jquerysnippets|don|0.0.1
xml|Dot|2.5.1
vscode-PSStackoverflow|Dou|0.0.2
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.17
windows-explorer-context-menu|ele|2.1.0
vscode-great-icons|emm|2.1.67
prettier-vscode|esb|5.9.2
file-icons|fil|1.0.28
vscode-firefox-debug|fir|2.9.2
vs-code-http-server-and-html-preview|Fli|2.2.2
html-preview-vscode|geo|0.2.5
lintlens|ghm|3.0.0
vscode-pull-request-github|Git|0.24.0
vscode-stylint|Haa|0.1.3
svgeditor|hen|2.9.0
jquery-snippets|Hri|1.0.0
path-autocomplete|ion|1.17.1
search-node-modules|jas|1.3.0
NodeAssertionSnippets|jay|0.1.0
shortcut-menu-bar|jer|3.0.1
svg|joc|1.4.5
codeshell|Kip|0.2.2
vscode-codemetrics|kis|1.24.0
vscode-gutter-preview|kis|0.27.1
node-module-intellisense|lei|1.5.0
mirc|lol|0.0.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-beautifier|mic|2.3.3
msl|mir|0.3.0
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
remote-wsl|ms-|0.54.3
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
vscode-for-node-js-development-pack|nod|2.0.1
simple-html-template|pho|0.0.4
seti-icons|qin|0.1.3
vscode-workspace-switcher|sad|1.15.3
vscode-zipexplorer|sle|0.3.1
code-spell-checker|str|1.10.2
spellchecker|swy|1.3.0
language-stylus|sys|1.11.0
shellcheck|tim|0.13.3
vscodeintellicode|Vis|1.2.11
nodejs-extension-pack|wad|0.1.9
ws-rainmeter|wil|0.2.7
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by bpasero** [comment]
This sounds a lot like https://github.com/microsoft/vscode/issues/118562
