### ISSUE TITLE
Typescript crashes over and over

### ISSUE THREAD

**Issue by willryan** [microsoft/vscode#118827]
Issue Type: <b>Bug</b>

Open a large codebase, and sometimes typescript just exits and restarts over and over.  I don't have a ton of insight into why.  I do think it is slighly more likely if you switch branches.

This only started to happen recently (last 2 weeks?), but I'm not sure if that's to do with the size of our codebase, an update to visual studio, or what.  We are on Typescript 4.1.5 (and telling VS Code to use that version).

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (4.31GB free)|
|Process Argv|--crash-reporter-id ac58bee8-6abd-4b51-a5ce-6d08547be162|
|Screen Reader|no|
|VM|31%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.64GB (6.08GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|15.64GB (6.08GB free)|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.7.0
bracket-pair-colorizer|Coe|1.0.61
vscode-peacock|joh|3.9.1
dotenv|mik|1.0.1
vscode-edge-devtools|ms-|1.1.4
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
highlight-matching-tag|vin|0.10.0
vim|vsc|1.18.9
vscode-ruby|win|0.28.0
atlascode|atl|2.8.5
pgformatter|bra|1.17.0
indented-block-highlighting|byi|1.0.7
solargraph|cas|0.21.1
vscode-postgres|cko|1.1.17
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.17
vuerd-vscode|din|0.7.8
githistory|don|0.6.15
gitlens|eam|11.3.0
elm-ls-vscode|elm|2.0.3
prettier-vscode|esb|5.9.2
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.24.0
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.204
vscode-test-explorer|hbe|2.19.5
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
vscode-jest-test-adapter|kav|0.8.0
vscode-gutter-preview|kis|0.27.1
graphql-for-vscode|kum|1.15.3
template-string-converter|meg|0.4.7
ruby-rubocop|mis|0.8.5
vscode-postcss-sorting|mrm|3.0.1
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
vscode-js-profile-flame|ms-|0.0.14
vsliveshare|ms-|1.0.3968
vsliveshare-pack|ms-|0.4.0
ruby|reb|0.28.1
vscode-yaml|red|0.16.0
html-preview-vscode|tht|0.2.5
es6-string-html|Tob|2.2.0
docker|vsc|1.0.0
yaml|vsc|1.0.0
vim|vsc|1.18.9
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also does it happen with the latest TS version (4.2.3)?

**Comment by willryan** [comment]
@mjbvz Sorry just saw your message now; github didn't make the notification very prominent.  Anyway I will test on Friday with Insiders and 4.2, don't really have time to try prior to that.

**Comment by mjbvz** [comment]
Closing this as not actionable without more information. Please let us know if you see this on insiders with all extensions disabled
