### ISSUE TITLE
tasks.json hiding dozens of smaller tasks

### ISSUE THREAD

**Issue by altruios** [microsoft/vscode#118837]
I have a lot of tasks. So many!
I have one task to run them all...
But I have trouble finding it scrolling through the sea of smaller helper tasks.
These helper tasks will never run on their own.

It would be wonderful to have a bool on the options object that is 'hiddenFromTaskList' which would filter searchable and viewable tasks. 

I have read through the docs and I see nothing like this. This seems like a really useful feature.

**Comment by gjsjohnmurray** [comment]
Previously requested in #110928 which failed to attract enough upvotes.
