### ISSUE TITLE
Source control window showing many modifications

### ISSUE THREAD

**Issue by jms19** [microsoft/vscode#118809]
I have just installed VSC, opened a couple of files by their UNC paths but the source control left bar icon indicates "96 pending changes" and clicking on it shows the source control window showing (source) files in the same and parallel working directories. Some with a "U" but most "M". I have in fact edited about a dozen files which are listed but do not stand out at all. The others listed haven't been touched for several years. If I restrict my investigation to one particular short file (which is checked in but untouched for years) I see a scroll-sychronised matching pair of windows of that file.

The output window shows that for one particular 14 line script it does

Using git 2.29.2.windows.3 from C:\Program Files\Git\cmd\git.exe
.
> git show --textconv HEAD:\\server\share\....\a-sourcefile.ext
then twice > git ls-tree -l HEAD -- \\server\share\....\a-sourcefile.ext

At least it hasn't gone and actually staged stuff without asking which is what Atom did when I tried it a few years back.

I am baffled as to why it thinks I have modified files. If I point TortoiseGit at the same UNC (rather the parent working directory) it does correctly interpret things.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465

```

</details>

**Comment by lszomoru** [comment]
@jms19, apologies for not getting back to you on this issue until now. I was wondering if you are still able to reproduce the problem. The contents of the "Source Control" view are rendered by parsing the contents of the `git status -uall` command. If you still have a repro for this, I was wondering if you would be able to run this command and see whether the output of it is consistent with the list of changes presented in the "Source Control" view. Thank you very much!
