### ISSUE TITLE
A Search feature like in Web Storm

### ISSUE THREAD

**Issue by thisurathenuka** [microsoft/vscode#118873]
Hi, I love VS Code for being smooth and fast without complicating things.
I am a full-stack developer and when I'm developing frontend applications I currently use Web Storm.
The one and the only reason why I am unable to switch to VSCode from Web Storm is your Search feature.
The way you show search results just does not help. IMO, It is not user-friendly enough. 
I mean if anyone has used IntelliJ or webstorm for a while, he would spot the difference in a flash

If you can hopefully add something like this, or at least improve on what you guys have right now, that would be amazing. 

![image](https://user-images.githubusercontent.com/39618801/111029039-8e878c80-8420-11eb-8616-a1a64acfbb37.png)

Thanks and Cheers

**Comment by roblourens** [comment]
We don't plan to implement language-specific search features or syntax highlighting in results

https://github.com/microsoft/vscode/issues/92781
