### ISSUE TITLE
powershell terminal does not default to cwd

### ISSUE THREAD

**Issue by phrankie81** [microsoft/vscode#118848]
All, I'm a noob so bear with me. There are 3 terminal types in vscode. Cmd, powershell and bash. When I run my python files in the terminal with either bash or cmd it defaults to the cwd as expected. However when I try to use powershell it always defaults to C:\  I need a way to configure such that powershell also defaults to the cwd. I have tried changing the settings for “terminal.integrated.cwd" to “${workspaceFolder}” and "${fileDirname}" but I’m not getting much luck. I know that leaving the "terminal.integrated.cwd": "" is supposed to default to cwd but the fact that both cmd and bash terminals are behaving as expected suggests to me that the issue may not be in vscode. Please help!

**Comment by julee** [comment]
After upgrading my vscode to latest version, I found different vscode window, terminal opens with the same current directory.
I can sure the old version always use workspace folder of the current window as current directory. 
Is this a bug?

**Comment by phrankie81** [comment]
We didn't get a response to this, did we? I still have the same issue.
