### ISSUE TITLE
【bug】git.stageSelectedRanges will change my file-encoding

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#118857]
- VS Code Version: 1.45.2
- OS Version:win 7/10

Steps to Reproduce:

1. file encoding is `gbk`,`gb18030` `gb2320`
2. open a diff view from git-scm view
2. select some changed-lines
3. execute `git.stageSelectedRanges` through menu
4. file-encoding will change to `UTF-8`
5. aaaaaaaaaaaaaaaaaaa:c

please help me

Does this issue occur when all extensions are disabled?: Yes

**Comment by Lemmingh** [comment]
#111915

**Comment by lszomoru** [comment]
Closing this issue in favour of the duplicate - #111915
