### ISSUE TITLE
Python default interpreter is not reacting to changes in settings

### ISSUE THREAD

**Issue by jonohewitt** [microsoft/vscode#118891]
Issue Type: <b>Bug</b>

Set the "Python: Default Interpreter Path" to /usr/local/bin/python3 - on my system this is version 3.9.2

The Python version in the bottom corner remains 3.8.8

Restarting doesn't update it.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.17
prettier-vscode|esb|6.2.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.24.0
applescript|idl|0.20.0
vscode-pigments|jas|2.0.0
vscode-mdx|Jou|0.2.2
vscode-styled-components|jpo|1.5.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
color-manager|roy|0.6.2
material-theme|zhu|3.9.15

</details>

**Comment by GNUSheep** [comment]
Did you select right interpreter?

**Comment by jonohewitt** [comment]
I think so, does this look correct? 

<img width="608" alt="Screenshot 2021-03-13 at 21 29 14" src="https://user-images.githubusercontent.com/47791294/111043547-6bba9f80-8443-11eb-9edd-72daa36c7d3b.png">
<img width="708" alt="Screenshot 2021-03-13 at 21 29 30" src="https://user-images.githubusercontent.com/47791294/111043548-6d846300-8443-11eb-9a1c-ae696e19ad93.png">
<img width="347" alt="Screenshot 2021-03-13 at 21 00 17" src="https://user-images.githubusercontent.com/47791294/111043549-6d846300-8443-11eb-94a4-74cb0f555001.png">

Selecting the 3.9.2 option after clicking the interpreter label in the bottom left corner does change it to 3.9.2 but only by creating a `.vscode` folder with a `settings.json` containing: ` "python.pythonPath": "/usr/local/bin/python3"` - the same location as I had specified as default. If I delete this folder it returns to 3.8.8

**Comment by GNUSheep** [comment]
Are you tried to change it, in default settings.json? On MacOs should be in: $HOME/Library/Application Support/Code/User/settings.json

**Comment by jonohewitt** [comment]
Looks like the change was automatically saved to that file. `"python.defaultInterpreterPath": "/usr/local/bin/python3",` is already included.

**Comment by GNUSheep** [comment]
hmm, maybe try restart vscode, you can also try to delete a settings.json file.

**Comment by jonohewitt** [comment]
Fixed by changing `python.pythonPath` as well as `python.defaultInterpreterPath`. Thanks for trying to help @GNUSheep!
