### ISSUE TITLE
You can make compilation and testing easier

### ISSUE THREAD

**Issue by AndreyITicha** [microsoft/vscode#118877]
Hello! I wanted to run the code with the command yarn watch and it throws the **error**: 
```
"npm-run-all" is not internal or external
command, executable program, or batch file. error Command failed with exit code 1. 
```
Can you do testing and compilation not through **yarn**, but through **npm**?
If you can **help me**, please **write** me on my Discord: _IThackpe#4756_

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Are you trying to compile and test VS Code itself? If so, have you seen https://github.com/microsoft/vscode/wiki/How-to-Contribute?

**Comment by AndreyITicha** [comment]
> / needsMoreInfo
> 
> Вы пытаетесь скомпилировать и протестировать сам VS Code? Если да, то видели ли вы https://github.com/microsoft/vscode/wiki/How-to-Contribute ?

Yes

**Comment by AndreyITicha** [comment]
> /needsMoreInfo
> 
> Are you trying to compile and test VS Code itself? If so, have you seen https://github.com/microsoft/vscode/wiki/How-to-Contribute?

Yes, I see this page. But I can't find a command for testing and contibure 😢 (I find a command `yarn watch` but it doesn't moving. Do you know how to test or contibure or solve the problem?)

**Comment by dbaeumer** [comment]
@connor4312 can you please help with the testing.

**Comment by connor4312** [comment]
We do not have any plans to make VS Code run using npm instead of yarn.
