### ISSUE TITLE
Multiline select

### ISSUE THREAD

**Issue by avjgit** [Microsoft/vscode#11881]
Please introduce multiline select (Ctrl + Shift + L).

**Comment by Bill-Stewart** [comment]
It already has this - [http://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections](http://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections)

**Comment by avjgit** [comment]
I was not specific enough. I meant ability to select a block of text, then press Ctrl+Shift+L to split it into one selection per line.

**Comment by Bill-Stewart** [comment]
I would suggest to open a new issue, use a better subject line, and give specifics of the behavior you'd like to see. A use case would also be helpful (why do you need it?).

**Comment by avjgit** [comment]
Found! It is implemented as `Alt + Shift + i`.
