### ISSUE TITLE
Styles tag colour format issue

### ISSUE THREAD

**Issue by DanielFerreira011102** [microsoft/vscode#118896]
![stylestagcolour](https://user-images.githubusercontent.com/76625406/111052467-e17a3780-8452-11eb-96ff-f09135bad298.PNG)

It used to show the usual colors but now it's just white.  In a CSS file, the selector's color is yellow, etc. But in an HTML file, there is no color. This isn't a major issue but if there is an easy solution, to whoever sees this, please feel free to let me know.

P.S : I just realized that the style tag is not inside the head tag in the .PNG, but that isn't the issue.

**Comment by aeschli** [comment]
Can you verify that the editor mode (in the status bar on the right) is HTML?

**Comment by DanielFerreira011102** [comment]
That's it. I had it on Django HTML. Must have forcefully changed when I downloaded the extension. Thanks.
