### ISSUE TITLE
Add a way to make the preview editor tab more visually distinct

### ISSUE THREAD

**Issue by QAston** [microsoft/vscode#118881]
I like the preview editor tab feature (single click to open a file in a preview mode), but currently the preview tab is not visually distinct enough for me. I'd love to be able to configure the preview tab title/content/open-editors-entry to be a different colour, have a separate icon or somehow more easily distinguished from other tabs as italics in the title isn't very noticable.

This should also reduce the confusion of people new to the editor about how the editor tabs behave.

**Comment by dbaeumer** [comment]
Assuming this is about previewing markdown.

**Comment by QAston** [comment]
No, this is about the `"workbench.editor.enablePreview": true` feature.
