### ISSUE TITLE
wget download failed for vscode-server-linux-x64.tar.gz

### ISSUE THREAD

**Issue by eugenelet** [microsoft/vscode#118801]
- VSCode Version: 1.54.0
- Local OS Version: Windows 10.0.18363
- Remote OS Version: Linux (Ubuntu 20.04)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connecting to remove server using remote SSH on VS Code
2. log returns:

```
[12:21:16.400] > wget download failed
> failed: Connection timed out. failed: Connection timed out. failed: Connection t
> imed out. failed: Connection timed out. failed: Connection timed out. failed: Co
> nnection timed out. failed: Connection timed out. failed: Connection timed out. 
> failed: Connection timed out. failed: Connection timed out. failed: Connection t
> imed out. failed: Connection timed out. failed: Connection timed out. failed: Co
> nnection timed out. failed: Connection timed out.
```

Then I check to see which file it's trying to download and it returns:

` wget https://vscode.cdn.azure.cn/stable/42e27fe5cdc58539dad9867970326a297eb8cacf/vscode-server-linux-x64.tar.gz`

I tried to manual download it on my server and it will be stuck at:

`Resolving vscode.cdn.azure.cn (vscode.cdn.azure.cn)... 112.90.58.219, 112.65.212.110, 112.65.212.105, ...
Connecting to vscode.cdn.azure.cn (vscode.cdn.azure.cn)|112.90.58.219|:443...`

Is the download server down right now? It has been working flawlessly before.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by lolikung** [comment]
It's working, thanks. 🎉

**Comment by eugenelet** [comment]
It's working now! Thanks for the prompt response!
