### ISSUE TITLE
editor.multiCursorModifier does not work correctly on Ubuntu 20.04

### ISSUE THREAD

**Issue by Megamouse** [microsoft/vscode#118820]
- VS Code Version: Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:50.094Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version: Ubuntu  20.04

Steps to Reproduce:

1. Set editor.multiCursorModifier to alt
2. use alt+mouse left -> box select does not work (**wrong** ! )
    use ctrl+mouse left -> box select does not work
    use ctrl to follow code -> works
    use alt to follow code -> does not work
3. Set editor.multiCursorModifier to ctrlCmd
4. use alt+mouse left -> box select works (**wrong** ! )
    use ctrl+mouse left -> box select does not work
    use ctrl to follow code -> does not work (**wrong** ! )
    use alt to follow code -> works (**wrong** ! )

Does this issue occur when all extensions are disabled?: Yes (although i can't follow code links if I don't have c++ extensions)

**Comment by alexdima** [comment]
Jump to Definition uses the **other** modifier. 

Here is how things should work:
* `"editor.multiCursorModifier": "alt"` => then alt+click does multicursor and ctrl+click does jump to definition.
* `"editor.multiCursorModifier": "ctrlCmd"` => then ctrl+click does multicursor and alt+click does jump to definition.

AFAIK some Linux distributions are configured to have alt+click&drag move the window and in those distros no application can consume alt+click.

**Comment by Megamouse** [comment]
In my distro "windows_key+click&drag" moves the windows.
So alt+click should do box select by default. But maybe that's an ubuntu issue? Because apart from online gdb, alt+click does not work anywhere

**Comment by alexdima** [comment]
> In my distro "windows_key+click&drag" moves the windows. So alt+click should do box select by default

In VS Code, <kbd>Alt</kbd> + click will not do column selection by default. The following setting is needed: `"editor.multiCursorModifier": "ctrlCmd"`.

**Comment by Megamouse** [comment]
I literally gave you all the info in the original description

**Comment by Megamouse** [comment]
The issue is not that it does not do column selection by default.
The issue is that multiCursorModifier does not work correctly (see the parts that I marked with "**wrong !**")

**Comment by alexdima** [comment]
@Megamouse I think you might be mixing things. Multi cursor is a different feature than column selection (often called box selection in other editors). Column selection is implemented using multi-cursor but multi-cursor is a more general feature where cursors can be placed anywhere in the text.

Let me use the same format as yours in my answer, maybe that will bring clarity:

1. Set editor.multiCursorModifier to alt
2. use alt+mouse left -> box select does not work (~~**wrong**~~ ! ) **this is as designed !** alt+click adds multiple cursors
    use ctrl+mouse left -> box select does not work
    use ctrl to follow code -> works
    use alt to follow code -> does not work
3. Set editor.multiCursorModifier to ctrlCmd
4. use alt+mouse left -> box select works (~~**wrong**~~ ! ) **this is correct** now alt+click can be used for column selection
    use ctrl+mouse left -> box select does not work
    use ctrl to follow code -> does not work (~~**wrong**~~ ! ) **this is correct** ctrl+click now adds multiple cursors and alt+click can be used to jump to definition
    use alt to follow code -> works (~~**wrong**~~ ! ) **this is correct** alt+click now jumps to definition

Again, multiple cursors and column selection are very similar, but distinct features. Absolutely everything works correctly. Please read about the feature named multi cursor in our documentation here -- https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

**Comment by Megamouse** [comment]
Thanks for the clarification.
But then how can I do box select with ctrl+leftclick as in any other editor ?
