### ISSUE TITLE
accounts toogle doesnt open

### ISSUE THREAD

**Issue by jonetxe13** [microsoft/vscode#118894]
Issue Type: <b>Bug</b>

just doesnt work, it says "loading..." and after a while with that message shows "you are not signed in to any accounts" but doesnt show any options

VS Code version: Code - OSS 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T21:13:58.622Z)
OS version: Linux x64 5.11.4-zen1-1-zen

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3100 4-Core Processor (8 x 3882)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.77GB (3.25GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/qtile|
|XDG_CURRENT_DESKTOP||
|XDG_SESSION_DESKTOP||
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|5.9.2
code-runner|for|0.11.2
python|ms-|2020.10.332292344
debugger-for-chrome|msj|4.12.6
LiveServer|rit|5.6.1
vscode-icons|vsc|11.1.0
vim|vsc|1.18.9
material-theme|zhu|3.9.15

</details>

**Comment by RMacfarlane** [comment]
This is expected - a feature or extension has to request authentication information to trigger the sign in flow. For example, turning on setting sync will request sign in. We don't have a general sign in button since there isn't a reason to sign in if nothing needs that information
