### ISSUE TITLE
"remote.autoForwardPortsSource": "output" maybe not respected?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#118858]
- Have `"remote.autoForwardPortsSource": "output"` set from Remote-SSH
- Connect to an SSH host
- Run `./scripts/code.sh &> /dev/null`
- No terminal output is produced, but ports 5870 and 5876 are still auto-forwarded and I get a notification
- From what I understand, they shouldn't be forwarded, unless vscode is actually treating that setting like it's `"process"`. I'm happy to do some debugging if that's easier

**Comment by alexr00** [comment]
I can't repro this, so yes, let's debug.

**Comment by roblourens** [comment]
This hasn't happened at all since, have tried many times 🤷
