### ISSUE TITLE
[folding] Preserve comment folding for developer UX and sanity

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [microsoft/vscode#118853]
Problem: commenting blocks of code makes them unfoldable due to placement of comment delimiter, e.g. `#` characters, in uniform row, prior to one leading space at outermost indentation level. Editor seems to understand JavaScript well enough to retain folding there; fluency in Python also likely good enough. Wouldn't know; my work is overwhelmingly in substandard, castoff languages. <sup><a href="#footnore-tldr" name="anchor-tldr">[tl;dr]</a></sup>

(a picture is worth a thousand words; therefore, imagine 2,000 words written here, but that you can ignore, due to comment folding)

![A sample method in Ruby, unfolded and informing developers of very mission critical workflow via self-commenting code](https://user-images.githubusercontent.com/850082/111015612-a26aba00-835e-11eb-9926-f2aa42cebfe9.png)

![That same Ruby method, folded and unobtrusive now that the developer understands its very mission critical nature and can focus on the rest of the file. Comment follows, expressing state of bliss developer feels at ability to fold now-understood business logic](https://user-images.githubusercontent.com/850082/111015665-e067de00-835e-11eb-9534-f3c4727028c6.png)

However, when commenting is introduced, chaos and outrage slip in behind comment, while the door is closing.

![The previous Ruby method, now a comment, unfoldable and demanding valuable vertical screen space (VVSS) of the user's, because commented blocks despise you and want to see you suffer. Comment follows, expressing lamentation and woe at interloping comment block's refusal to spark joy by neatly folding away into an obedient ellipse](https://user-images.githubusercontent.com/850082/111016056-a26bb980-8360-11eb-8508-f93e131ca74e.png)

Oh no, a developer as committed a taboo and added the `#` character on the final line, one level of indentation in. Worse, committed taboo was committed to the repo. And _pushed._ Allowing entire codebase to fester and disintegrate into nothingness in the cloud<sup><a href="#footnote-1" name="anchor-1">[1]</a></sup>, all because this rogue developer, assuredly some intern, did not run Rubocop and uniformly align their `#` with the rest of the `#`s in their neat uniform uniformity, within the first column of every line.

But wait? What is this? The folding arrow appears in the gutter? What sourcery? What trickery‽ Burn the heretic! Before we can discover anything useful about the...

![The previous, unfoldable comment block, now partially folded due to the indented nature of some of the octothorpes](https://user-images.githubusercontent.com/850082/111017231-f7aac980-8366-11eb-8f22-cd4ee088dc77.png)

WAIT, HOLD YOUR FIRE(s). Perhaps commenting code in a similar fashion could possibly... 

![The formerly unfoldable comment block, now, due to the octothorpes on the lines of indented code now being placed after that indentation instead of at the beginning of each line, fully folded with full bliss fulfillingly filling the VVSS that was once full of useless comment lines](https://user-images.githubusercontent.com/850082/111016475-173ff300-8363-11eb-89dd-b2d55a1d2060.png)

It worked! Torches down, everyone. Three cheers for the intern, for bravely saving our block folding from that angry, torch-wielding mob!

<sup><a href="#anchor-tldr" name="footnote-tldr">[tl;dr]</a>:</sup> Solution: create a preference setting, such as `editor.preserveBlockFoldingWhenCommenting`, which inserts the working language's comment delimiter at the level of indentation each line has when the developer triggers the `Toggle Line Comment` command. Bonus effect of commenting this way: Not only is every level of indentation preserved for the commented block, but if a surrounding block is toggled as a comment later on, the comment blocks preserve the **nested** code folding as well 😌

---

<sup><a href="#anchor-1" name="footnote-1">[1]</a>: Honestly, we're lucky the entire cloud didn't disintegrate too.</sup>

**Comment by aeschli** [comment]
Thanks for the entertaining description of the problem and proposed solution.

May I suggest to experiment with that idea and implement it in an extension? Maybe a new command that adds comments in the special way? Note, it will only work with languages that still use folding based on indentation...
