### ISSUE TITLE
Feature request: contextless diffs

### ISSUE THREAD

**Issue by NeilMacMullen** [microsoft/vscode#118807]
The compare window is great but when performing simple  refactoring (e.g. renaming or performing simple transformations) it's common to end up with a large number of modified files where the the diff in each may only be a few sections, each of a single line.  It would be much more convenient to review these changes prior to staging if the "compare" window offered an option to hide or limit the amount common context.   

For example in this screenshot, all I'd really like to see is the 4 "Panic" lines (as well as a couple that are are scrolled out of view in the current display mode)

![vscdiff](https://user-images.githubusercontent.com/9131337/110922549-b7702a80-8317-11eb-8924-3732c91e5de1.png)

It seems like this _ought_ to be common request but I couldn't find any related issues.  If there are,  please feel free to close as duplicate.

**Comment by IllusionMH** [comment]
Looks like #3562 but more aggressive in removing context.

When you perform rename refactoring etc. there is preview of changes https://github.com/microsoft/vscode/issues/77728#issuecomment-573559307

**Comment by NeilMacMullen** [comment]
Yes, agree it looks very similar.  (Regarding second comment I'm actually using VSCode to review changes made by Resharper in VS Studio, simply because the the VSCode experience is considerably more pleasant !)
