### ISSUE TITLE
Integrated terminal behavior inconsistent with external terminal - PAM group change is not applied

### ISSUE THREAD

**Issue by pengsiya** [microsoft/vscode#118828]
- VS Code Version: 1.54.2
- OS Version: Ubuntu 20.04 LTS (Linux x64 5.4.0-66-generic snap)

Steps to Reproduce:

1. Setup pam-group:
    1. edit "/etc/security/group.conf", adding a line:
        \*;\*;\*;Al0000-2400;docker
    2. Create a file "/usr/share/pam-configs/pam-group" with the following content
        Name: activate /etc/security/group.conf
        Default: yes
        Priority: 900
        Auth-Type: Primary
        Auth:
                required                        pam_group.so use_first_pass
    3. enable the pam setting:
        sudo pam-auth-update --enable pam-group
2. Reboot and then Open Terminal and then run "id"
    
![image](https://user-images.githubusercontent.com/46474466/110963085-85a29800-8306-11eb-80ae-54560490e921.png)
3. Open VScode and open the integrated terminal and then run "id"
    
![image](https://user-images.githubusercontent.com/46474466/110963211-a965de00-8306-11eb-95ac-9dcf3a8bf956.png)

**EDIT (see also comment below):**
I am using xfce desktop and the way I open VSCode is through the "Application Finder" and then search for the app:

![image](https://user-images.githubusercontent.com/46474466/110980906-37e45a80-831b-11eb-867a-ea8a36f1d1f0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pengsiya** [comment]
An interesting update:

when I launch "code" from external terminal, and then if I launch terminal, I can see the group membership is correctly assigned:

![image](https://user-images.githubusercontent.com/46474466/110980641-e936c080-831a-11eb-95ca-aa3953fdbaef.png)

![image](https://user-images.githubusercontent.com/46474466/110980699-ffdd1780-831a-11eb-9111-7a1dc73308ec.png)

**Comment by pengsiya** [comment]
Another update:

I modified the launching option to use "run in terminal"
![image](https://user-images.githubusercontent.com/46474466/110982964-05882c80-831e-11eb-853a-525c963a7366.png)

Now it works

**Comment by Tyriar** [comment]
When launching via the launcher (not terminal) we source the environment by running `$SHELL -ilc`, it's probably that which is causing the issues. But it looks like you found what's probably the right workaround for this.
