### ISSUE TITLE
My screen reader does not find information about a remote connection in the status bar

### ISSUE THREAD

**Issue by jvesouza** [microsoft/vscode#118839]
Issue Type: <b>Bug</b>
CC: @isidorn
1. Open VSCode and activate the orca screen reader.
1. Create and activate a remote connection.
1. Move the focus to the status bar by pressing the f6 key a few times.
1. Explore the status bar using the arrows.

None of the information read by the orca identifies the remote connection.

VS Code version: Code - Insiders 1.55.0-insider (06b54543d660353a04cdab6554d1f27266a537fd, 2021-03-12T05:14:36.439Z)
OS version: Linux x64 5.11.4-arch1-1
Remote OS version: Linux x64 5.4.0-1039-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.68GB (0.30GB free)|
|Process Argv|-n --no-sandbox --crash-reporter-id bcecf5e0-97d1-4830-b28c-0943c4adab1c|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: node1.prakna.com|
|OS|Linux x64 5.4.0-1039-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2593)|
|Memory (System)|7.78GB (3.84GB free)|
|VM|0%|
</details>

**Comment by isidorn** [comment]
@jvesouza I just tried this out and the Screen Reader reads "Remote Host" properly for me. Which is the aria-label which we set on the status bar remote item.
Are you saying that even the "Remote Host" part is not read for you? Or would you like something more specific? Since "Remote Host" might not be the best label

Also assigning to @aeschli since he owns the remote status bar

**Comment by isidorn** [comment]
I also get "Remote Host" if I am not connected to the remote.
@aeschli I think we should update the aria label of this status bar item based on the remote connection. Do we currently do this?

Oh I see that we simply always set `Remote Host` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L261)
Is it possible to make this more dynamic based on connection?

**Comment by jvesouza** [comment]
> @jvesouza I just tried this out and the Screen Reader reads "Remote Host" properly for me. Which is the aria-label which we set on the status bar remote item.
> Are you saying that even the "Remote Host" part is not read for you? Or would you like something more specific? Since "Remote Host" might not be the best label
The remote label is read correctly, but I'd like if possible, an identification about the remote connection.
>

**Comment by isidorn** [comment]
@jvesouza makes perfect sense, thanks for feedback.
This would be tackled if we use a more dynamic aria label for the remote status bar item
@aeschli can help here. Let me know if you are busy and I can also look into it. Thanks!

**Comment by aeschli** [comment]
@isidorn That would be fantastic if you can just go ahead and improve the remote indicator. I don't have that much experience with good aria labels.

**Comment by isidorn** [comment]
For the aria label I just went with the text that we use for the status bar, since I think it is fitting just fine. I am just stripping codicon special characters `$(`.

@jvesouza try it out from tomorrow with vscode insiders and let me know how it goes. Thanks

**Comment by jvesouza** [comment]
Tested and approved! It was excellent.
It is now possible to easily identify the current connection, which is of great value especially if we are connected to more than one remote host.

**Comment by isidorn** [comment]
@jvesouza lovely, thanks a lot for letting us know! Adding verified label based on your feedback.
