### ISSUE TITLE
 javascript/typescript references codelens  not work in  script module or vue sfc 

### ISSUE THREAD

**Issue by houfeng0923** [microsoft/vscode#118854]
When enable codelens in js/ts, it work well normally. 

But if project is a vue based project , or you use es script module , the code references in those regions is ignored .
now i test it only work in language:javascript and language:typescript . language:html and language:vue (after installed   [veture](https://github.com/vuejs/vetur)) ,not work well .

So , does team has plan to enhance this codelens features, or can u give me some extension api point  which can resolve it.
thanks.

```
<script type="module">
import isEmpty from '@/utils/is';

function xxx() { isEmpty(); }
</script>

```
<template></template>
<script lang="ts">
import isEmpty from '@/utils/is';
function xxx() { isEmpty(); }

</script>
```

**Comment by mjbvz** [comment]
Please file a feature request against the Vetur extension
