### ISSUE TITLE
The TypeScript language service died 5 times right after it got started.

### ISSUE THREAD

**Issue by Peeja** [microsoft/vscode#118887]
Issue Type: <b>Bug</b>

* Repo is using Yarn 2 (PnP).
* Problem occurs with extensions disabled.
* Poking at settings has occasionally fixed the problem, only to have it recur after a restart. The same settings appear to sometimes succeed and sometimes fail, so this may be some sort of race condition. It fails more often than it succeeds. It has both succeeded and failed with the Yarn TSDK appearing in the logs as the targeted tsserver.
* Problem began immediately after updating VS Code. Previous version worked perfectly with exact same setup. Previous version may have been before February 2021 (1.54). Will attempt downgrading and report findings.
  * **Confirmed:** Problem is not present in 1.53.2.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 41b834df-c95f-4a92-ae99-058563a1c261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
increment-selection|alb|0.2.0
Bookmarks|ale|13.0.3
project-manager|ale|12.0.1
jest-snippets|and|1.8.0
vscode-zipfs|arc|2.2.2
quitcontrol-vscode|art|3.1.3
code-gnu-global|aus|0.2.2
clojure|avl|0.13.1
calva|bet|2.0.179
clj-kondo|bor|2021.3.3
jsrefactor|cms|2.20.6
vscode-storybook|cst|0.0.5
vscode-jq|dan|1.2.0
vscode-jq-playground|dav|3.3.1
vscode-eslint|dba|2.1.17
javascript-ejs-support|Dig|1.3.1
yarn-task-provider|dkn|0.2.2
binary-plist|dni|0.5.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
find-related|eam|0.9.0
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
prettier-vscode|esb|5.9.2
vscode-todo-plus|fab|4.18.3
nasc-touchbar|fel|1.12.0
auto-rename-tag|for|0.1.6
vscode-yarn|gam|1.7.1
macros|ged|1.2.1
vscode-pull-request-github|Git|0.24.0
go|gol|0.23.2
vscode-graphql|Gra|0.3.15
terraform|has|2.8.2
applescript|idl|0.20.0
bats|jet|0.1.7
vscode-styled-components|jpo|1.5.0
jq-syntax-highlighting|jq-|0.0.2
auto-comment-blocks|kev|1.0.1
graphql-for-vscode|kum|1.15.3
expand-region|let|0.1.4
caddyfile-support|mat|0.1.1
rainbow-csv|mec|1.8.1
xcodestrings|mhc|1.0.0
vscode-docker|ms-|1.10.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
cpptools|ms-|1.2.2
vscode-js-profile-flame|ms-|0.0.14
debugger-for-chrome|msj|4.12.12
gulptasks|nic|1.3.1
abracadabra|nic|5.0.1
incrementor|nms|1.0.3
vscode-jest|Ort|3.2.0
vscode-react-native-storybooks|Ort|2.7.1
jq-vscode|pet|0.1.1
vscode-yaml|red|0.16.0
vscode-coverage-gutters|rya|2.7.2
vscode-javascript-booster|sbu|14.0.1
mdx|sil|0.1.0
vscode-zipexplorer|sle|0.3.1
rewrap|stk|1.14.0
vscode-open-in-github|sys|1.15.0
shellcheck|tim|0.13.3
zip-file-system|Tom|2.0.0
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.11
quokka-vscode|Wal|1.0.349
wallaby-vscode|Wal|1.0.274
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
