### ISSUE TITLE
Bug in How-to-Contribute#build-and-run-from-source documentation

### ISSUE THREAD

**Issue by ststeiger** [Microsoft/vscode#11880]
I've now successfully built vscode on Ubuntu 14.04 ARMhf. 
Note the documentation is wrong. 
It states one needs NPM < 3.9. 
This is wrong. I installed 3.8 (3.8.4), and it still failed. 
Then i installed 3.7 and it still failed. 
Then I installed 3.5 and it still failed. 
Then I installed 3.1, and the build ran, but not vscode 
==> error Cannot find module 'jsonc-parser'. 
==> +subsequent errors
One needs to manually 
npm install jsonc-parser  
then it ran (so far without bug) 

Also, electron downloaded a second time after i just installed jsonc-parser. 
I don't know if you just download it, or just when there are changes, but if it's that large and takes that long, it shouldn't download a second time. 

Also tell Scott hanselmann to fix his blog article on
http://www.hanselman.com/blog/BuildingVisualStudioCodeOnARaspberryPi3.aspx 
it should definitely reference a fixed version of 
https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source

- VSCode Version:
git clone https://github.com/microsoft/vscode
as per 20160912, 11:40 CEST

- OS Version:
uname -a
Linux localhost 3.10.18 #1 SMP Tue Aug 2 21:26:16 PDT 2016 armv7l armv7l armv7l GNU/Linux

lsb_release -cds
Ubuntu 14.04.5 LTS
trusty

# nodejs --version 
v6.5.0

npm --version
3.1.3

Steps to Reproduce:
cd ~
mkdir sources
cd sources
sudo apt-get purge nodejs npm
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get update
sudo apt-get install -y nodejs
nodejs --version ==> v6.5.0
npm --version  ==> 3.10.3
# Downgrade NPM to < 3.9 !WRONG!
npm install npm@3.1 -g
npm --version ==> 3.1.3

(trusty)root@localhost:~/sources# git clone https://github.com/microsoft/vscode
(trusty)root@localhost:~/sources# cd vscode/
# Fix bug: Cannot find module 'jsonc-parser'.
(trusty)root@localhost:~/sources# npm install jsonc-parser  
(trusty)root@localhost:~/sources/vscode# ./scripts/npm.sh install --arch=armhf
(trusty)root@localhost:~/sources/vscode# ./scripts/code.sh

**Comment by joaomoreno** [comment]
For Linux, 5.10 is recommended, as mentioned in the docs. It's also what we use in [our builds](https://github.com/Microsoft/vscode/blob/master/.travis.yml).
