### ISSUE TITLE
Add support for `"log": "<level>"` to the argv.json

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#118824]
Or `"verbose": true` if that makes more sense.

From https://github.com/microsoft/vscode/issues/118372#issuecomment-797466580_

**Comment by bpasero** [comment]
@sandy081 leaving this up to you if you think this makes sense. The ask is for a permanent way to enable a log level across restarts. I am not sure if people by accident would forget that they had enabled this and then see horrible performance as a consequence.

To add to `argv.json`, you could follow along the lines here:

https://github.com/microsoft/vscode/blob/1cd0c3376720bde257f9e0cdf13852c0650012f6/src/main.js#L196-L212
