### ISSUE TITLE
No Such File or Directory & No Input Files - Mainly code isn't running

### ISSUE THREAD

**Issue by mdimrannazir** [microsoft/vscode#118811]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/39686923/110931358-59ae0380-8354-11eb-93c6-483a9d2f243e.png)

I tried with CodeBlocks it's working fine there.

**Comment by TylerLeonhardt** [comment]
How are you running this code? Are you using the C/C++ extension for vscode? If so, you should file an issue over here: https://github.com/microsoft/vscode-cpptools
