### ISSUE TITLE
Create Webview Panel without a tab

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#118914]
I have a webapp that has tabs and It seems weird when running from vscode because it opens the panel with a tab. It would be nice if we could create a webview panel without a Tab.

![image](https://user-images.githubusercontent.com/55927613/111070065-dc0b0480-84c7-11eb-9ec0-bc289ad51ca2.png)

This is what I would like it to be

![image](https://user-images.githubusercontent.com/55927613/111070234-9864ca80-84c8-11eb-89a8-e0036e216825.png)

The reason for my app to have tabs is because it also runs outside of vscode to enable "window mode"

![image](https://user-images.githubusercontent.com/55927613/111070142-1d031900-84c8-11eb-82de-99cba89b1a3a.png)

**Comment by mjbvz** [comment]
This api is for created editor based webviews. I suggest refactoring your app's UI so it fits better into one of these or switch to a webview view if you don't want an editor based webview
