### ISSUE TITLE
Poor recognizability of folder structure with icons

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11898]
![image](https://cloud.githubusercontent.com/assets/4033249/18445380/2d25e4cc-78d2-11e6-83a3-a1bc61909a9b.png)

Quick questions:
- Where is `buildfile.js`?
- Where is `buildunit.json`?

I mistook `buildfile.js` as child of `test`, and `buildunit.json` child of workbench.
I believe I'm not the only one.

Atom and Sublime:

![image](https://cloud.githubusercontent.com/assets/4033249/18445504/bed29988-78d2-11e6-8d64-487d2f8a3169.png)

I believe folder icons for opened/closed folders should be added, like Sublime:

![image](https://cloud.githubusercontent.com/assets/4033249/18445922/b8563144-78d4-11e6-9787-57fb318dbfcc.png)

Another cool idea is to have indent guide lines that shows the scope of folder

(I added the red lines)
![image](https://cloud.githubusercontent.com/assets/4033249/18445839/50319176-78d4-11e6-928d-3519b2cfb6ea.png)

- VSCode Version: 1.5.1
- OS Version: OS X 10.11.6

**Comment by octref** [comment]
Seems we already have it in Minimal

![image](https://cloud.githubusercontent.com/assets/4033249/18446210/32731f4a-78d6-11e6-957e-0418c825ff10.png)

But this still should be fixed for Seti.

**Comment by ramya-rao-a** [comment]
The issue of a folder and file which are siblings appearing as parent-child is tracked in #11762

**Comment by octref** [comment]
@ramya-rao-a 
I upvoted it.
Can this issue still be kept open for the adding indent-guide to file-explorer feature request?

![](https://cloud.githubusercontent.com/assets/4033249/18445839/50319176-78d4-11e6-928d-3519b2cfb6ea.png)

**Comment by ramya-rao-a** [comment]
@octref Sure, you can re-open it. Also update the title to reflect the request for indent-guide

**Comment by octref** [comment]
@ramya-rao-a 
I'll just open a new issue.
