### ISSUE TITLE
dirty shutdown when update pending causes errors

### ISSUE THREAD

**Issue by BMBurstein** [microsoft/vscode#118907]
Issue Type: <b>Bug</b>

If VSCode has an update downloaded, and is pending a restart (of VSCode) to install it, and I restart my computer without closing vscode first, the next time I open vscode, I get a long string of JS errors in a messagebox and it won't start. I had to reinstall vscode.
This happened to me with the upgrades from 1.54.0->1.54.1, 1.54.1->1.54.2, and at least in one other recent upgrade, but I didn't pay attention at the time to what version it was, thinking it was some one-time glitch.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.9.0-0.bpo.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.27GB free)|
|Process Argv|--crash-reporter-id 6949b6e9-d952-4b8f-a136-284374926c80|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: mews7748|
|OS|Linux x64 4.9.0-0.bpo.6-amd64|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4074)|
|Memory (System)|15.54GB (1.02GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
material-icon-theme|PKi|4.5.0
gitlens|eam|11.3.0
todo-tree|Gru|0.0.205
me-vscode|ME-|0.0.13
git-graph|mhu|1.29.0
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by joaomoreno** [comment]
#52855
