### ISSUE TITLE
Deactivating extensions do not always have enough time to clean up

### ISSUE THREAD

**Issue by MSLaguana** [Microsoft/vscode#11895]
- VSCode Version: 1.5.1
- OS Version: Windows 10

Steps to Reproduce:
1. Check out https://github.com/MSLaguana/vscode_deactivate_process_issue
2. Run the extension in that project
3. In the command palette, run "Spawn child process"
4. Navigate to `localhost:8080` and verify that a webserver is running
5. In the command palette, run "Kill child process"
6. Navigate to `localhost:8080` and verify that no webserver is running; the cleanup command works correctly.
7. In the command palette, run "Spawn child process", then close the experimental vscode instance
8. Navigate to `localhost:8080` and verify that the webserver is still running

We ran into this issue at https://github.com/Microsoft/vscode-react-native/issues/300 where during normal usage of the extension, we start a long-running child process which we want to clean up when the extension stops.

Specifically we are trying to run `child_process.spawn("react-native.cmd", ...)`, which ends up creating an instance of `cmd /c react-native.cmd` that in turn creates the desired `node cli.js ...`. We would like to make sure that descendant process is cleaned up, but because there is an extra layer of indirection we cannot simply call `child_proc.kill()` since that kills the `cmd` process but not the `node` process.

To work around this, on windows we use `taskkill /T` to kill the `cmd` process and all its descendants. This works fine during normal operation, but when the extension is terminating invoking `taskkill` is an async exec operation and so it does not complete. I also tried using `exec-sync` but that didn't help either.

Any suggestions on how to improve our behaviour here instead of leaking processes?

**Comment by alexandrudima** [comment]
Apologies for not answering here sooner, the `deactivate` method can return a promise and the extension host process will self-destruct when all the `deactivate` promises have completed or when 4 seconds have elapsed.
