### ISSUE TITLE
Ignore language should use git icon

### ISSUE THREAD

**Issue by baincd** [microsoft/vscode#118912]
- VS Code Version: 1.54.1
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Execute command "Change Language Mode"
2. Search for language "ignore"  
**The "ignore" language uses the npm icon**
[
![Screenshot1_languagemode](https://user-images.githubusercontent.com/5075659/111069618-49a53980-84a4-11eb-81b4-6b3933f9fc96.png)
](url)
3. Change language of current file to "ignore"  
**The editor tab uses the npm icon when the language type is ignore**
![Screenshot2-editortab](https://user-images.githubusercontent.com/5075659/111069629-5590fb80-84a4-11eb-8d52-1a498ddeef93.png)

The ignore language should use the git icon

Does this issue occur when all extensions are disabled?: Yes

**Comment by baincd** [comment]
I searched and did not find any duplicate issues

**Comment by dbaeumer** [comment]
@aeschli do you know where this is coming from. How do we map these icons?
