### ISSUE TITLE
floating search bar has higher z index than the info panel

### ISSUE THREAD

**Issue by ibraheemsaoud** [microsoft/vscode#118979]
Issue Type: <b>Bug</b>

when auto completing some props in an object, it displays a list with the possible props, some of the props have description and how to use them, if the edito's screen is small enough, and the description is long enough then it goes below the search input, instead of above it (currently part of the description then is unreadable)

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (3.20GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Ibraheem/Documents/fitogram/neo --crash-reporter-id 980a5f95-f337-41e6-b50d-0e6638d1ce70|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.18
githistory|don|0.6.16
indent-rainbow|ode|7.5.0
vscode-xml|red|0.15.0
vscode-scss-formatter|sib|2.1.0
code-spell-checker|str|1.10.2
gitblame|wad|6.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464
vsdfh931:30275552

```

</details>

![image](https://user-images.githubusercontent.com/4976047/111166107-12b44e00-85a0-11eb-8283-a93d8b6d039b.png)

**Comment by dbaeumer** [comment]
@alexdima starting with you. Not sure who should handle this (completion or find).
