### ISSUE TITLE
The latest version of vscode always crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by Aisuko** [microsoft/vscode#118941]
- VS Code Version:

```
➜  osm git:(feat/list) ✗ code --version
1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64

```

- OS Version:

```
➜  osm git:(feat/list) ✗ uname -a 
Linux redthirteen 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

Steps to Reproduce:

1. Downloading the latest version of VScode `.deb` from the official website and install it.

Does this issue occur when all extensions are disabled?: Yes/No

I recorded the screen of the process, please see below
https://youtu.be/UaYl95WKzJ8

**Comment by deepak1556** [comment]
Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues and attach the crash logs. Thanks!

**Comment by Aisuko** [comment]
I'm not sure, the same version of VScode which was installed with Ubuntu software works for me. 
(But there is another issue VScode can not check the `go.path` and I saw someone's feedback on the issue that the original VScode from the website can work well.) 

```
➜  layer5 git:(feat/release-v0.5) snap version                                       
snap    2.49
snapd   2.49
series  16
ubuntu  20.04
kernel  5.8.0-44-generic
```


![Screenshot from 2021-03-16 09-37-12](https://user-images.githubusercontent.com/8053949/111246131-b1908700-8640-11eb-8d43-f9b598c86bdd.png)


Please kindly check the dump file below

[399c4859-e4c6-4685-1f60b2ab-a55b4e27.zip](https://github.com/microsoft/vscode/files/6145553/399c4859-e4c6-4685-1f60b2ab-a55b4e27.zip)

**Comment by deepak1556** [comment]
Thanks for the crash logs, can confirm you are hitting the same issue as https://github.com/microsoft/vscode/issues/116690

Sorry about this, but to workaround please delete the following keys from your keyring https://github.com/microsoft/vscode/issues/116690#issuecomment-791064392

I will merge this issue to the other one, you can follow it for updates.

**Comment by Aisuko** [comment]
@deepak1556 Thanks
