### ISSUE TITLE
cli.contribution.ts: isInstalled misses check?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118951]
Saw this code:

https://github.com/microsoft/vscode/blob/dbf6147c01ed2554ec70b025a916d38d4204f2eb/src/vs/workbench/contrib/cli/node/cli.contribution.ts#L114-L120

You check for symbolic link but then still call `realpath` it seems?

Btw we have a handy utility for working with symbolic links: [`SymlinkSupport.stat`](https://github.com/microsoft/vscode/blob/0740b4a313488392942a5cf33ae0faf81b1ad5a4/src/vs/base/node/pfs.ts#L249-L249)

**Comment by joaomoreno** [comment]
I only want that code to return `true` *if* it's a symbolic link which points to the expected place.

**Comment by bpasero** [comment]
I think I dont understand how the return type of the code `isSymbolicLink` is used here:

```
.then(stat => stat.isSymbolicLink()) 
.then(() => extpath.realpath(target)) 
```

**Comment by joaomoreno** [comment]
Yeah for sure, now I see it, thanks! I wish I learned how to code 5 years ago, we should have a bug bounty program. If bug is over 5 years, you get a 5k run for free. https://github.com/microsoft/vscode/commit/d2a151fcc69bc3307fa3b75d167841177cbb9f41
