### ISSUE TITLE
Cannot find replace large multiline text

### ISSUE THREAD

**Issue by cdalexndr** [microsoft/vscode#118988]
- VS Code Version: 1.54.2
- OS Version: Win10 19041.867

Steps to Reproduce:

1. find or replace large multiline text (~ 100 line stacktrace containing ~14.000 chars)
2. Result: bottom right warning `Invalid regular expression:` containing text.

![image](https://user-images.githubusercontent.com/22418250/111179894-2d44f200-85b5-11eb-9ad1-11b08f08e2fd.png)
![image](https://user-images.githubusercontent.com/22418250/111180105-60878100-85b5-11eb-9b2a-ab9bb65c3e2e.png)

Note that selecting fewer lines (ex: 10 lines) works.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@cdalexndr How long is your search string? By using binary search I found that the regex length limit is `41943041` (41MB). Does this reproduce with any search string or only this specific one?

**Comment by cdalexndr** [comment]
[sample.log](https://github.com/microsoft/vscode/files/6172861/sample.log)
1. Ctrl-A
2. Ctrl-C
2. Ctrl-F
3. Ctrl-V => No results (invalid!)
4. Esc
5. Ctrl-F
6. Invalid regular expression:...

**Comment by cdalexndr** [comment]
Need to remove label `needs more info`

**Comment by alexdima** [comment]
Given this is native v8 / JS behavior, this is a limitation that we will have to live with. We want to keep using JS regexes for searching.
