### ISSUE TITLE
RunTime error is not showing of C++

### ISSUE THREAD

**Issue by pblencho** [microsoft/vscode#118985]
I have tried so many C++  programs in VS Code and it is not showing any runtime error.
![Screenshot from 2021-03-15 20-37-03](https://user-images.githubusercontent.com/53457662/111175394-63db3680-85ce-11eb-8981-1c0f7f1500e0.png)

**Comment by dbaeumer** [comment]
This looks like a problem with the CPP extension. Please report the issue there.
