### ISSUE TITLE
Improve announcement when cursor is added.

### ISSUE THREAD

**Issue by MarcoZehe** [microsoft/vscode#118964]
Issue Type: <b>Bug</b>

1. With NVDA, make a sure you have an empty line below the current one.
2. Press NVDA+F2 to pass the next key through, then press CTRL+Alt+DownArrow to add a cursor below. If you don't pass the key through, NVDA interprets it as a table navigation command erroneously.
   * Actual behavior: NVDA speaks "Cursor added: 13:1" (or whatever the current line number is).
   * Expected behavior: The numbers could be better formatted. Depending on the synthesizer and the numbers, this could be interpreted as a time stamp. Would be better if it said "Cursor added on line x column y" or similar.

VS Code version: Code - Insiders 1.55.0-insider (84fe402d655e029eb1a5c04e675bf64788fa7fcf, 2021-03-15T05:14:29.836Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.89GB free)|
|Process Argv|--crash-reporter-id af385ced-002b-4d51-928c-05d733e674ab|
|Screen Reader|yes|
|VM|40%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
gitignore|cod|0.6.0
doxdocgen|csc|1.1.0
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.17
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|6.2.0
vscode-pull-request-github|Git|0.24.0
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.5
jstl|jsx|1.0.4
flutter-intl|loc|1.14.0
vscode-docker|ms-|1.10.0
vscode-edge-devtools|ms-|1.1.4
python|ms-|2021.2.636928669
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.4.641214696
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.3
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vscode-github-issue-notebooks|ms-|0.0.72
vscode-markdown-notebook|ms-|0.0.14
vsliveshare|ms-|1.0.3968
vsliveshare-audio|ms-|0.1.91
debugger-for-edge|msj|1.0.15
indent-report|ogo|1.0.0
nunjucks|ron|0.3.0
cmake|twx|0.0.17
vscode-webhint|web|1.5.11
omnipascal|Wos|0.18.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vsget980:30265949
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by isidorn** [comment]
@MarcoZehe thanks for feedback, we can easily change this. I just went with `LINE:COLUMN` to be concise.
So let's go with
`Cursor added on line x column y`

Alternative

`Cursor added: line x column y`

**Comment by MarcoZehe** [comment]
Either would be fine with me.
