### ISSUE TITLE
Find Next Selection Command behaviour improvement

### ISSUE THREAD

**Issue by DVMirchev** [microsoft/vscode#118986]
Currently, when you execute Ctrl+F3 (Find Next Selection) **without** selection it selects the whole line an tries to search it. See:

![Find-Next-Selection](https://user-images.githubusercontent.com/12948830/111177204-af7fe700-85b2-11eb-941e-a7a0d7c67642.gif)

This is inefficient and unuseful as one will rarely need to search a whole line as it is. This behaviour is also different in Visual Studio where Ctrl+F3 without selection selects the current word and then search for it.

Please, make the behaviour of the **Find Next Selection** command when there is no selection similar to what Visual Studio does - select the word that is under the cursor and search for it.

**Comment by ArturoDent** [comment]
I cannot reproduce this in Stable or Insiders.  What is your system information?  Perhaps an extension issue?

**Comment by DVMirchev** [comment]
> I cannot reproduce this in Stable or Insiders. What is your system information? Perhaps an extension issue?

Damn. You are correct. I've tried it on a clean VM with a clean installation and its working as I want. Thanks! Closing.
