### ISSUE TITLE
Auto reveal: Revert revealed directory back to collapsed when file is closed

### ISSUE THREAD

**Issue by cmawhorter** [microsoft/vscode#118927]
I've learned to love auto reveal but one thing is still bothersome when it comes to typescript dev.

**The problem:**
If I click through to a dependency type definition, it auto reveals the node_modules directory which is almost always massive. Then when I close the definition file, the node_modules directory stays open completely taking over the explorer and I have to spend a second or two scrolling up to close it.  

**The solution:**
If a directory is being auto revealed and the file is closed (possibly within some amount of time), the auto revealed directory should be collapsed if that was its previous state.  If the directory was already expanded, then do nothing.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks

**Comment by cmawhorter** [comment]
At first I shrugged about the closure but this has continued to be a source of pain for me and I haven't found a workaround. 

Perhaps instead of my original convoluted suggestion I can throw out an alternative: Adding a `reveal_ignore: ["**/node_modules"]` preference.
