### ISSUE TITLE
skipFiles ignored in settings.json

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#118955]
Issue Type: <b>Bug</b>

According to the [documentation](https://code.visualstudio.com/docs/nodejs/nodejs-debugging) it should be possible to prevent the launch debugger from entering node_internals by setting the following in settings.json:
```
"debug.javascript.terminalOptions": {
  "skipFiles": [
    "<node_internals>/**"
  ]
},
```
This has no effect however (neither does `"<node_internals>/**/*.js"`) and the debugger steps into internal node code.

The only thing which works is adding the following to each and every launch.json:
```
      "skipFiles": [
        "<node_internals>/**/*.js"
      ]
```

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.69GB free)|
|Process Argv|--crash-reporter-id 99d3b629-6268-4b22-b1e2-fc798573c577|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
vscode-eslint|dba|2.1.17
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.17
autoscrolldown|fox|1.1.1
seito-openfile|Fr4|1.8.7
macros|ged|1.2.1
todo-tree|Gru|0.0.205
vue|jcb|0.1.5
vscode-abap|lar|0.5.4
git-graph|mhu|1.29.0
xml-format|mik|1.1.2
vscode-docker|ms-|1.10.0
mssql|ms-|1.10.1
hexeditor|ms-|1.4.0
powershell-preview|ms-|2021.2.1
vscode-typescript-next|ms-|4.3.20210314
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
vscode-yaml|red|0.16.0
html-preview-vscode|tht|0.2.5
vscode-json-stable-stringify|Tra|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833cf:30267465
vsdfh931:30275552

```

</details>

**Comment by weinand** [comment]
@cawoodm the `skipFiles` property is neither a setting nor a terminal option, but it is an option of the launch/debug configuration for the JS debugger. As such it can only be controlled by putting it in the launch configs.

So the behavior you are seeing is correct.

**Comment by cawoodm** [comment]
If you will see the documentation:

> For example, to add node internals to your skipFiles, you could _**add the following to your user or workspace settings**_

![image](https://user-images.githubusercontent.com/498834/111135697-4336c080-857d-11eb-933c-4a069d9efa35.png)

**Comment by cawoodm** [comment]
I've reproduced the issue and debugged by stepping into an async await function. I end up in node_internals/ unless I add that skipFiles setting to my launch.json - settings.json has no effect. The log has been mailed to @connor4312

**Comment by connor4312** [comment]
Thanks for the email. It looks like for the logs you sent, the launch config was

```
{
  "type": "node",
  "request": "launch",
  "name": "DEBUG DEV",
  "program": "${workspaceFolder}\\src\\index.js",
  "env": {
    "DEBUG_MODE": "true"
  },
  "trace": true,
  "cwd": "${workspaceFolder}",
}
```

Please send a launch config with the `skipFiles` set so that I can see the issue. Thanks!

**Comment by cawoodm** [comment]
The issue here is that skipFiles *doesn't work in settings,json* as the documentation states.

`skipFiles` *does work in launch.json* so we have to add it to every launch task of every project.

That is why I am showing you a log with `skipFiles` only set in settings.json.

**Comment by cawoodm** [comment]
Quoting the [docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging):
> You can apply other properties normally found in launch.json to auto attach in the debug.javascript.terminalOptions setting. For example, to add node internals to your skipFiles, you could add the following to your user or workspace settings:

Are you saying "your user or workspace settings" is not referring to settings.json?

**Comment by connor4312** [comment]
It does, but that is only relevant if you're using auto attach or the debug terminal. From the log you provided it looks like you're using the traditional launch.json configurations. For these, you want to add the skipFiles into the relevant configuration object in that file.
