### ISSUE TITLE
Repaint get buggy when resizing a X11 VSCode to more than half the 4k display area

### ISSUE THREAD

**Issue by akaztp** [microsoft/vscode#118908]
Environement:
- VS Code Version: 1.54.2  or 1.55.0-insider
- OS Version: Linux x64 5.4.0-66-generic
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0

Steps to Reproduce:

1. Have Ubuntu 20 (no desktop) on virtualbox, install VSCode, assign DISPLAY to windows 10 PC running VcXSrc or X410 on a 4k display.
2. Open VSCode
3. Resize VSCode window to more than half display area
4. Window repaint gets completly messed up, VSCode is unusable
5. Resize window to less than half display area: VSCode becomes usable again

If window width is full display width, it behaves nice until height is half of display height. More than that, becomes unusable.
If window height is full display height, it behaves nice until width is half of display width. More than that, becomes unusable.
Open file dialogs resize correctly.
Webstorm works awesomely (in terms of window resizing) on the same remote display setup.

Does this issue occur when all extensions are disabled?: Yes
Combinations of `--disable-gpu`, `--force-cpu-draw` and `--ignore-gpu-blacklist` didn't have any effect.

**Comment by deepak1556** [comment]
This looks similar to https://github.com/microsoft/vscode/issues/115868 but weird that disabling hw acceleration didn't help. Can you follow these steps https://github.com/microsoft/vscode/issues/115868#issuecomment-779502873 and provide the trace log. 

As a workaround or better alternative you can try the remote development setup https://code.visualstudio.com/docs/remote/remote-overview

**Comment by akaztp** [comment]
Thanks for your reply. Here is the log.
[vscode_trace_event.log](https://github.com/microsoft/vscode/files/6144815/vscode_trace_event.log)

Yes, I've start using the remote SSH which seems nice!!

**Comment by deepak1556** [comment]
Thanks for the trace, first thing the gpu process message loop exited very early, right after trying to initialize EGL layer. Can you provide the output of `code --verbose` , also can you check if the issue repros with `code --use-gl=swiftshader`

**Comment by akaztp** [comment]
Here is the output of  `code --verbose`:
[code.verbose.log](https://github.com/microsoft/vscode/files/6289984/code.verbose.log)

And `code --use-gl=swiftshader` does not show the bug, except presents very, very slow rendering.

**Comment by deepak1556** [comment]
If the issue continues with latest insider, can you check if running with `--ignore-gpu-blocklist --use-gl=egl --no-xshm` helps.
