### ISSUE TITLE
命令行终端中文字符显示不全

### ISSUE THREAD

**Issue by ufowiner** [microsoft/vscode#118937]
Issue Type: <b>Bug</b>

 在命令行终端中，中文字符有部分不显示，在我的系统终端中可以正常显示

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.4.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (4 x 1799)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.75GB (1.03GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by mamil** [comment]
translation：

Chinese character doesn't show correctly in terminal

Issue Type: Bug

Chinese character doesn't show correctly in vscode terminal, but it shows correctly in the system terminal.

VS Code version: Code 1.54.1 (f30a9b7, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.4.0-66-generic

System Info
...
