### ISSUE TITLE
Getting Started page Open a folder in Recent section didn't work.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118958]
- VS Code Version: 1.55.0 Insider 84fe402d655e029eb1a5c04e675bf64788fa7fcf
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

1. Getting Started page Open a folder in Recent section didn't work. @JacksonKearl

![image](https://user-images.githubusercontent.com/17777237/111133760-8b58e180-8583-11eb-82ca-51488959d69e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Thanks! Fixed the typo too. (my `a` key doesn't work sometimes)
