### ISSUE TITLE
HTML - No autocomplete for target property.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118903]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

1. Form tag with target property.

![0](https://user-images.githubusercontent.com/17777237/111056747-2f5e6200-848a-11eb-86ba-66421fd097db.gif)

![image](https://user-images.githubusercontent.com/17777237/111056707-e5757c00-8489-11eb-87a1-943a7cce98d8.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pixieaka** [comment]
@aeschli  Is it solved already ?

**Comment by aeschli** [comment]
Yes, in the next build
