### ISSUE TITLE
Debugger runtime shown against an extension seems confusing

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#11896]
In the latest update there's a contributions tab that shows things that an extension contributes. For Dart Code it shows `node` as the debugger runtime:

![Debugger runtime](https://cloud.githubusercontent.com/assets/1078012/18445096/d948e98e-7913-11e6-80f5-738c42991283.png)

I guess this is because our debug adapter is written in TS (and is therefore invoked via `node`). The adapter then launches Dart with debug flags and interacts with it.

Have we done something incorrectly or is this expected? If it's expected, is showing this runtime here useful to the extension user? It seems a bit confusing to me.

**Comment by joaomoreno** [comment]
Yeah, I see the problem. Let's remove the `Runtime` column then.
