### ISSUE TITLE
Error when trying to rename or delete folder with git repo inside

### ISSUE THREAD

**Issue by Shaddaaa** [microsoft/vscode#118938]
Issue Type: <b>Bug</b>

1. Open some folder A with VSC
2. Create a new folder B inside that folder A.
3. Initialize a new empty git repository inside folder B.
4. Try to delete or rename B from inside VSC. Either through the VSC-Explorer or through the embedded command line tool. Rename will fail completely, resulting in a permission error. Deleting is not able to move to recycle bin, only deleting permanently. Elevating permission level to admin does not fix the issues.

Error when renaming:  
```Error: EPERM: operation not permitted, rename 'e:\path\to\folder' -> 'e:\path\to\renamedfolder'```  

Errors/Dialogs when deleting:
1. Dialog asking if I'm sure I want to delete? (I click yes)
2. Win-Dialog saying that access was denied, it needs elevated permission. (I grant permission)
3. typical Win-Dialog to give VSC admin permission (I grant permission)
4. Dialog saying deletion failed, asking if I want to permanently delete instead.

I tried integrated powershell, terminal and right click folder -> rename, all fail inside of VSC.  
Strangely deleting and renaming do work if I do them fast enough after starting VSC, while it is still loading my folder I assume?  
On the other hand using the Windows Explorer or the Windows Terminal to delete or rename works flawlessly, without any need for admin permissions.  

My guess would be it's something about Source Control doing weird things?

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.82GB (19.05GB free)|
|Process Argv|--crash-reporter-id 9c313a6d-e4c2-4cdc-a41f-3d018a6dd994|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by xuiang** [comment]
Because inside other files had referenced the file or inside referenced path had that file name. You can annotation those referenced before the change that filename

**Comment by lszomoru** [comment]
When the git repository is created in the `B` directory, VS Code sets up a file watcher on the `.git` folder inside the `B` folder. This file watcher is necessary to update the "Source Control" view. What I believe is happening here is that the file watcher locks the `B` directory and that is why it cannot be renamed nor deleted. To delete/rename the folder you would have to close the VS Code window to release the lock. This is currently by design on Windows, and I am not aware of any plans to make any changes to this in the near future.
