### ISSUE TITLE
Syntax coloring for __init__ is broken when changed in settings.json 

### ISSUE THREAD

**Issue by philmorefield** [microsoft/vscode#118936]
I'm setting up a custom color scheme for Python. I'm trying to set the color for the "__init__" keyword to #407090.

Upon inspection, VS Code tells me the the textmate scope is: support.variable.magic.python

After I specify the appropriate textmate settings, the change is not immediately reflected in my code, which is unusual. If I restart VS Code, the change will be reflected briefly, but a few seconds after the Python extension finishes loading, the color of "__init__" reverts back to black (apparently).

**Comment by gjsjohnmurray** [comment]
Sounds like semantic token highlighting taking effect after a few seconds. This trumps Textmate scope colouring.

**Comment by aeschli** [comment]
The `Developer: Inspect editor tokens and scope` command will show you how the coloring at the given cursor position was computed. If you feel something is wrong, please add a screenshot of the that hover

**Comment by gjsjohnmurray** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance makes me think maybe you need to add an entry under `editor.semanticTokenColorCustomizations` for the custom semantic token type named `magicFunction`
