### ISSUE TITLE
Search editor: investigate to use file working copies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118947]
In the context of https://github.com/microsoft/vscode/issues/117873 I was doing a quick research how working copy providers that are text file model based are implemented today and found 2 examples:
* custom text based editors
* search editors

When you look at `CustomTextEditorModel` you can see how every IO related method (like `save` or `revert`) is going into the manager of text file models, e.g.:

https://github.com/microsoft/vscode/blob/5d5b9dd0a8bb3351a544cf3084c619dfd62ebf8f/src/vs/workbench/contrib/customEditor/common/customTextEditorModel.ts#L95-L95

This has the advantage that a lot of corner cases for saving are being taken care of that prevent data loss or corruption.

When looking at search editors, I see that a (code editor) model is being resolved or created here:

https://github.com/microsoft/vscode/blob/71776589163b831768c408bcad2a87d73941bbb6/src/vs/workbench/contrib/searchEditor/browser/searchEditorModel.ts#L61-L61

But the IO logic is all implemented custom, e.g.:

https://github.com/microsoft/vscode/blob/57488b5430311ecdd7111d15ea4df5b489187807/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L128-L128

As such, your custom search editor is a good candidate for adopting the text file model approach, similar to custom text editors.

I am inclined to mark this `important` because I think you really should not implement the IO logic yourself, but maybe there are no issues with your implementation either, so I leave it as `debt`.

**Comment by bpasero** [comment]
Ok, not good. There is an easy way to produce dirty overwrites which is something we protect the user from when it comes to text editors, steps:
* open a search editor that is saved on disk and make it dirty
* open the same search editor in a new window and modify it
* go back to the original window and just save your changes

🐛 you have essentially overwritten the changes that you made before

**Comment by devuxer** [comment]
@bpasero , Would this also solve a (much lesser critical issue) I'm having where hovering a word fails to show the definition (e.g., I do not get type info for a TS type if I hover)? I was tempted to open a feature request for this, but will not if this covers it. Thx.

**Comment by JacksonKearl** [comment]
@devuxer this would not change that behavior, you can open a new feature request for that.

**Comment by devuxer** [comment]
@JacksonKearl, Thanks. Just posted a new [feature request](https://github.com/microsoft/vscode/issues/119917).

**Comment by JacksonKearl** [comment]
@bpasero thanks for this report, much of this logic was written custom because the model as exists to the model service only contains the actual text inside the editor, but what we work with on disk has the search configuration serialized and prepended to that model's contents. Thus I call the `textFileService.write` and `.create` commands explicitly with the serialized text:

https://github.com/microsoft/vscode/blob/5e3df4ce3013ae653ec6829cb3131fe62cdce7c3/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L148-L149

https://github.com/microsoft/vscode/blob/5e3df4ce3013ae653ec6829cb3131fe62cdce7c3/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L128


It's not clear to me how the `.save` and `.saveAs` commands can be made to work with this model, do you have any suggestions?

**Comment by bpasero** [comment]
@JacksonKearl maybe you could benefit from the file working copy concept if you do not want to leverage text file models. We will polish the API during this month for notebooks, some things are not yet there. But the gist is that you get the full support of what text file models have today without actually instantiating any text models. The API is simple byte based and you only need to implement `IFileWorkingCopyModel` to leverage it:

https://github.com/microsoft/vscode/blob/7f9835ac43382b942b57b9d8df50344e2a4737a1/src/vs/workbench/services/workingCopy/common/fileWorkingCopy.ts#L46-L46

**Comment by bpasero** [comment]
The file working copy API is now in good shape to be used.

**Comment by bpasero** [comment]
After a 1on1 with Jackson, there is some homework on my end to figure out if file working copies can also help for the untitled case and also to provide some guidance how to actually use file working copies.

Since the majority of users seem to use untitled search editors and from my testing I could not find issues with that, removing important label, since this is only about saved search editors.

I also suggest to move this to May, so that I can investigate for how to support untitled working copies if possible.

**Comment by JacksonKearl** [comment]
IMO the risk/benefit of this change is too large at this point, there have been no issues regarding the potential for desync here and migrating things over would touch quite a lot of otherwise solid search editor code.
