### ISSUE TITLE
Find a interesting bug in code about include

### ISSUE THREAD

**Issue by keerm-code** [microsoft/vscode#118982]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Now I use the newest VScode in Linux (debian deb version),when I include my .hpp file and this .hpp file include a qt headfile(QLineSeries),I find that "#include<my.hpp>" is wrong with rad line showing that 
 cant find QLineSeries.But in my.cpp,everything is OK.And,in the end I can run this program successfully.
2.So what happened , why,and how can I solve it?

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by keerm-code** [comment]
my os is Ubuntu 20.10 and code version is 1.54.1 amd64

**Comment by dbaeumer** [comment]
This sound like an issue with the CPP extension. Please report the issue with them.
