### ISSUE TITLE
Flaky Unit Tests: IndexedDB File Service

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#118953]
Check macOS, Attempt #1:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=108844&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb&s=d26761af-f5e8-5e3e-3ed3-ef1ee2069094

```
  1) IndexedDB File Service
       "before each" hook for "root is always present":
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) IndexedDB File Service
       "after each" hook for "root is always present":
     TypeError: Cannot read property 'delete' of undefined
      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/vs/platform/files/test/browser/indexedDBFileService.test.js:62:35)
```

**Comment by JacksonKearl** [comment]
Looks like `this.retries` doesn't apply to the setup hook, updated it to increase it's timeout as acquiring the indexeddb lock can take some time on the build machines.
