### ISSUE TITLE
it doesnt show the option of new project and external class

### ISSUE THREAD

**Issue by hussain-mir** [microsoft/vscode#118943]
Issue Type: <b>Feature Request</b>

it doesnt show the option of new project and external class

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
VS Code doesn't have a 'project' concept quite like you may be familiar with from other tools.

Have you seen https://code.visualstudio.com/docs/editor/multi-root-workspaces ?

Also, please clarify what you mean by 'external class'.
