### ISSUE TITLE
Search dialog string auto-replacement (?!) without undo

### ISSUE THREAD

**Issue by working-name** [microsoft/vscode#118928]
Issue Type: <b>Bug</b> or **Feature Request** (depending on how you look at it)
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 18.5.0

This is very annoying guys, I'm sorry. **Not useful.** Why are you overwriting the search string when pressing CMD + F ?! And secondly, why is the replacement permanent? My old search string does not come back with CMD + Z inside the search box. 

Now I have to go back to copy whatever string I had before. The annoyance this creates is directly proportional to the amount of work I put in to create that search string; think long regex or something I've grepped for in the cli.

If this is meant to save someone a CMD + C when selecting some new string in the current file to search for - it's a very minor convenience first off, and it's at the cost of one's workflow and dare I say, sanity.

## Proposed fixes:
a) disable auto-replacement of search string based on whatever text is nearest to the cursor when one activates search. Maybe leave current behavior on if there is an active selection? But even then I'm having a hard time being sold on its benefits vs just letting the user have control.
b) make auto-replacement undo-able if the above behavior is close to someone's heart

**Comment by roblourens** [comment]
You can set `"editor.find.seedSearchStringFromSelection": false` or navigate history with arrow keys

**Comment by working-name** [comment]
My vote is to ship `editor.find.seedSearchStringFromSelection` with a default value of false.

Never heard of arrows navigate search history, maybe that should get a bit of a hint in the UI?

Either way, thanks, this will save my sanity.
