### ISSUE TITLE
New Update Stops Project build 

### ISSUE THREAD

**Issue by AllTracking** [microsoft/vscode#118906]
The automatic update just updated my VSC to 1.54.2 , I'm using the ESp-IDF to build Embedded Project. the Building process stopped working immediately after the update. (The build process never change from the photo below)

![image](https://user-images.githubusercontent.com/40141992/111057854-c1ff0100-848a-11eb-9690-c5de5e140486.png)

 I still can do the build from the command line but not from VSC anymore

![image](https://user-images.githubusercontent.com/40141992/111057867-dba04880-848a-11eb-9117-da7f87efb3e4.png)

I hope I can find a sloution other than reinstalling the whole thing.

**Comment by gjsjohnmurray** [comment]
What platform do you use? Please copy full information from the Help, About dialog.

Which version of VS Code did you last build successfully on? 

Have you reported the issue to the extension author yet? In my experience, doing that can be an effective way to get VS Code regressions resolved or to identify situations where extension authors have relied on undocumented behaviour.

**Comment by AllTracking** [comment]
@gjsjohnmurray My platform information is :

Version: 1.54.2 (user setup)
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041


No, I actually didn't report that yet to the extension author, I'll do it now.

**Comment by AllTracking** [comment]
@gjsjohnmurray I'm suspecting one thing before i do any uninstalling, i noticed that my C/C++ dependency gives a new message like:

`For C source files, IntelliSenseMode was changed from "windows-clang-x64" to "windows-gcc-x86" based on compiler args and querying compilerPath: "C:\MinGW\bin\gcc.exe"`


How I can revert back this to the original C/C++ compiler of the extension?

**Comment by gjsjohnmurray** [comment]
/extC++

See also #112104
