### ISSUE TITLE
activity bar, side bar and status bar all missing

### ISSUE THREAD

**Issue by CHEESEFIST** [microsoft/vscode#118900]
activity bar, side bar and status bar all missing. I reinstalled VSC but they're still gone. Please advise.
![vsc](https://user-images.githubusercontent.com/78562578/111053669-b03e3f00-8433-11eb-9902-b573682c8965.jpg)

**Comment by gjsjohnmurray** [comment]
I'm seeing your side bar on the right edge of your screenshot. Does the 3-dot button alongside the EXPLORER header have any useful commands?

Did you look for 'reset' commands in the Command Palette? 

Please also add version and platform information. 

/needsMoreInfo 

Tip:for future issue reporting start from Report Issue of the Help menu.

**Comment by sbatten** [comment]
@CHEESEFIST please take a look at your `settings.json`. You can open this by pressing `Ctrl+Shift+P` and running the command `Open Settings (JSON)`. Verify your settings for `workbench.statusBar.Visible` and `workbench.activityBar.visible`

**Comment by CHEESEFIST** [comment]
This worked  once I found user>workbench>zen mode settings


Thank you,


Michael Lepley

________________________________

**Comment by sbatten** [comment]
If I understand correctly, you had zen mode enabled? I am closing this issue, can re-open if I am mistaken
