### ISSUE TITLE
Integration test: Opening a notebook should fire activeNotebook event changed only once

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#118972]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=108876&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=88928627-a399-54e7-2f20-a03c2cf00dcd&l=458

**Comment by jrieken** [comment]
All these tests have been disabled...

**Comment by rebornix** [comment]
This is a dup of https://github.com/microsoft/vscode/issues/138683 and has been fixed.
