### ISSUE TITLE
Incorrect window focus

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#118954]
Issue Type: <b>Bug</b>

- Open a browser window
- Open two vscode windows
- Note the last vscode window that has focus
- Use cmd + tab to switch focus to the browser
- Use cmd + tab to switch back to vscode
- Note the vscode window that has focus is not the same as the last vscode window that had focus before switching to the browser

VS Code version: Code 1.54.2 (Universal) (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.75GB free)|
|Process Argv|. --crash-reporter-id cba1ab8c-4d7d-4ea3-8a66-ff3f14637674|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.17
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.2.0
vscode-styled-components|jpo|1.5.0
dotenv|mik|1.0.1
azure-pipelines|ms-|1.183.0
azure-account|ms-|0.9.7
vscode-gradle|ric|3.6.1
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscode-java-debug|vsc|0.32.0
vscode-java-test|vsc|0.28.1
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by bpasero** [comment]
This does not sound like something that we control, rather OS behaviour or possibly an Electron issue. Leaving to @deepak1556 to see if he is aware of known duplicates.

**Comment by badsyntax** [comment]
I've been using the insiders edition, which was not showing this behaviour, then noticed this behaviour change with an update, so i don't believe it's an OS issue.

**Comment by badsyntax** [comment]
I just tried on the latest insiders and I'm not able to replicate using my instructions. I'm also not able to replicate on Universal anymore. I will close this issue and re-open once I figure out the exact steps needed to replicate. I'm really sorry for wasting time.
