### ISSUE TITLE
Provide command to focus most recently used editor group

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#11897]
In order to create custom keybindings to toggle focus between the editor and something such as the terminal panel, a command to focus the active/most recently used editor group needs to be added. I believe this is the best that can be accomplished currently:

Focuses the first group, meaning if the second or third editor groups were focused this would feel wrong:

```json
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus",
                            "when": "!terminalFocus" },
{ "key": "ctrl+`",          "command": "workbench.action.focusFirstEditorGroup",
                            "when": "terminalFocus" }
```

Or this which focused the most recently used editor group but opens the last editor/file in the group:

```json
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus",
                            "when": "!terminalFocus" },
{ "key": "ctrl+`",          "command": "workbench.action.openLastEditorInGroup",
                            "when": "terminalFocus" }
```

Some context on request: https://github.com/Microsoft/vscode/issues/11714#issuecomment-245859561

**Comment by bpasero** [comment]
@Tyriar isn't that as easy as providing a global command that just puts focus into the active editor? E.g. IEditorService.getActiveEditor().focus()?

PR welcome if you wanna give it a try.

**Comment by Tyriar** [comment]
@bpasero yes, I expect it to be pretty easy.

**Comment by Tyriar** [comment]
@bpasero got a better name than `workbench.action.focusActiveEditorGroup`?

**Comment by bpasero** [comment]
@Tyriar works for me 👍
