### ISSUE TITLE
Blocked: VS Code hangs at startup after 1.54.2 upgrade (including insiders build)

### ISSUE THREAD

**Issue by appurist** [microsoft/vscode#118987]
- VS Code Version: 1.55.0-insider (code-insiders-1.55.0-1615526749.el7.x86_64.rpm)
- OS Version: CentOS Linux release 7.9.2009 (Core)

Steps to Reproduce:

1. Upgrade to code-1.54.2
2. Start VS Code.

or install the nightly code-insiders release and start code-insiders.

Does this issue occur when all extensions are disabled?: Yes

I start VS Code and after about a second I see the welcome screen. At that point, the process is locked up hard (hung). Does not respond. There is no obvious crash; the process does not exit, but interaction with the app causes the system present a "not responding" dialog where you can choose to force-kill it. Choosing to instead wait does not change the status of the process, even after a lengthy wait.

This is a show-stopper problem for me as I cannot use VS Code _at all_ anymore.

I have downloaded and installed the insiders nightly version. I have followed the instructions on https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports but it does not seem very helpful as only the clientid files are generated (because the app does not actually crash).

I have tried waiting longer, but that doesn't seem to help. Symptoms are that you cannot close the welcome page, you cannot uncheck the "show welcome" checkbox, the window close box does nothing, i.e. the application does not respond to events.

I also tried:
- used `ps axc | grep code` to find and kill any code processes
- deleted `~/.config/Code` and `~/.config/Code - Insiders`
- ran `code-insiders --disable-extensions .` from an empty folder
- rebooted the machine and repeated all this

Three possible clues:
1. Note that when I start `code-insiders` with `--disable-extensions`, I **do** get the small popup that tells me extensions are disabled, and even more telling is that seconds after the app is unresponsive, the popup auto-closes itself normally, meaning something there is still running normally. Just that all input and interactivity is blocked. For example, I cannot close that dialog or press the Reload Extensions button.
2. When I clean up previous runs for another test attempt, a `kill <pid>` on the first process ID is sufficient, I do not need to force-kill it with a `kill -9 <pid>`
3. A `code-insiders --version` reports the version after starting and cleanly exiting:
```
$ code-insiders --version
1.55.0-insider
06b54543d660353a04cdab6554d1f27266a537fd
x64
```

An attempt to resize the window does resize the frame (see image below) but does not resize the contents, as the app is frozen hard. (See whitespace on right and bottom of window in image below.):

![vscode1](https://user-images.githubusercontent.com/1620487/111175208-ef30d980-8586-11eb-9100-b1022c1308d0.png)

A short time after attempting to interact, the system displays a "not responding" dialog and offers a forced quit.

This is the latest nightly insider as of Sunday March 14th 3pm, I used `code-insiders-1.55.0-1615526749.el7.x86_64.rpm` to install, and created an empty folder and used the following command to launch VS Code:
`code-insiders --crash-reporter-directory ~/crashes .`

VS code seems to be leaving process instances running, but I verified that none were running  using `ps axc | grep code` (or killed any that were) prior to launching the insiders build above.

The contents of the `~/crashes` folder only contains a `client_id` file with an ID in it:
`69c31889-2c99-4fed-94e2-f3275f581566`
and a folder named `exthost Crash Reports` with another `client_id` file with an ID in it:
`17b573a4-9c8a-47e0-9c6a-11c680d6e828`
Note they are different IDs in spite of being named `client_id`, not sure if that is expected.

The machine is a CentOS 7 installation with the latest Chrome installed and it runs fine (I'm using it to submit this report):
`Chrome 89.0.4389.82 (Official Build) (64-bit)`

If there is a file-based way to disable the welcome screen before starting code, I could do that too, to determine if it is something related to rendering that page.

**Comment by appurist** [comment]
I assumed it was related and reported this in #118522, and it may be related, but now I think this is a separate problem. According to the original poster in that issue, VS Code actually crashes. That report is on Windows so may be a different issue since it actually crashes.

**Comment by appurist** [comment]
Note that I was not having an issue prior to my upgrade to 1.54.2, and the problem occurred on the very first launch after upgrading. I have not had a successful run since that upgrade, including after uninstalling 1.54.2, cleaning up the .config folder and reinstalling it, uninstalling it again, and installing the Insiders build. It is very likely a regression of some kind was introduced in 1.54.2. I do not know what version I was running before that, but I tend to keep Code very up to date, probably within a few days at least.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`, does version `1.53` https://code.visualstudio.com/updates/v1_53 work fine ?

**Comment by appurist** [comment]
More info:
- Launching with `code-insiders --disable-extensions --sync off --disable-gpu --verbose .` on the empty folder produces several tracebacks (all appear to be the same), included below.
- After launching the above, running `code-insiders -s` from another shell also hangs (or is blocked).

```
[main 2021-03-15T15:40:18.418Z] [uncaught exception in main]: Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/code-insiders/resources/app/node_modules.asar.unpacked/vscode-sqlite3/build/Release/sqlite.node)
```
I'll get you the full output next.

**Comment by appurist** [comment]
Here is the output from the above run with `code-insiders --disable-extensions --sync off --disable-gpu --verbose .`:

[verbose.log](https://github.com/microsoft/vscode/files/6142644/verbose.log)

**Comment by bpasero** [comment]
I think the culprit is `/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found`

**Comment by appurist** [comment]
After googling that error, one of the replies is:
> CXXABI_1.3.9 is associated with gcc version 5.1. CentOS 7 has gcc 4.8.5. If you cannot find the software of your interest that is not linked against the newer version, your best bet will be to use a newer OS such as Fedora.

I am working on a government-provided laptop on a government project where CentOS 7 is (currently at least) the required platform. This kind of implies that maybe VS Code lost support for CentOS 7 in the 1.54.2 update.  Dependency ripple effect perhaps with an Electron upgrade?

I'll see if I can resolve the CXXABI library on CentOS 7 with an additional install.

**Comment by deepak1556** [comment]
Thanks for the details, reason to drop support is mentioned here https://github.com/microsoft/vscode/issues/115784#issuecomment-775364356 ,  workaround would be to install version of gcc that has required CXXABI support.

Merging to https://github.com/microsoft/vscode/issues/115784
