### ISSUE TITLE
While adopting the new const enum CharCode, I noticed this weird thing

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#11891]
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/search/common/replace.ts#L10

```
const BACK_TICK_CHAR_CODE = '`'.charCodeAt(0);
const SINGLE_QUOTE_CHAR_CODE = '`'.charCodeAt(0);
```

Notice how they have the same value.

I didn't want to touch those two lines in case something was forgotten there?

P.S. Please use `CharCode`, TypeScript will inline the values and will make it fast & readable.

**Comment by sandy081** [comment]
Looks like a copy paste and over-sight issue. Thanks for pointing this out. Will fix it for September milestone as it is not critical.
