### ISSUE TITLE
February Recovery 3

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#118962]
- [x] Create a milestone `<Month> <Year> Recovery` @bpasero 
- [x] Bump the version number @bpasero 
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22February+2021+Recovery+3%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **owner**
- [x] Issues are verified on `stable` build and the `verified` label is added **owner**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **owner**
- [ ] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits
  - [x] Windows 32 bit @isidorn 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
  - [x] Windows 64 bit **@bpasero**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
  - [x] Windows ARM64 @joaomoreno 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] OS X - @jrieken 
    - [x] arm
    - [x] intel
    - [x] universal
  - [x] Linux
    - [x] deb package 64-bit @connor4312
    - [x] rpm package 64-bit **owner**
    - [x] archives **owner**
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) @connor4312
  - [x] Server ([instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
    - [x] Linux @connor4312
    - [x] macOS @jrieken 
    - [x] Windows @alexr00 
- [x] Publish website **@gregvanl**
- [x] Publish stable build **owner**
- [x] Create an official release **owner**
  - [x] Create a tag: `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)

**Comment by connor4312** [comment]
Sanity failure: https://github.com/microsoft/vscode/issues/119008
