### ISSUE TITLE
Global search ignores git ignored files

### ISSUE THREAD

**Issue by mick62** [microsoft/vscode#118960]
Issue Type: <b>Bug</b>

Unfortunately "global search" and "global replace" don't cover the files which are ignored due to .gitignore (unless when currently opened in an editor). 

Problem:
When renaming an environment variable globally, then the git-ignored files will still use the old names.

There is no reason for this scope-expansion of .gitignore because if files should be excluded from the global search/replace this can be done via the separate "files to exclude" field.

Many thanks for your amazing work.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:11.840Z)
OS version: Linux x64 5.8.0-44-generic snap

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results which includes pointer to the button to toggle this.

**Comment by roblourens** [comment]
You can also disable this with `"search.useIgnoreFiles": false`
