### ISSUE TITLE
Javascript now reads as Plain Text

### ISSUE THREAD

**Issue by idavidson12** [Microsoft/vscode#11893]
Update to v. 1.5.1 leaves auto detect not detecting js files. Other files work fine.

**Comment by ramya-rao-a** [comment]
@idavidson12 Can you share your file associations if any in your settings?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
