### ISSUE TITLE
[FR] `typescript.suggest.paths` show js files

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#118984]
Currently, the default typescript path completion doesn't show js files, could this be improved?

![image](https://user-images.githubusercontent.com/28700378/111168747-54afb500-85dd-11eb-8a7e-c65d46078029.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is your `tsconfig.json`? Does it have ` "allowJs": true`?

If it allows JS then is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by wenfangdu** [comment]
After adding `"allowJs": true`, the suggestions did show up, thanks!
