### ISSUE TITLE
Allow `Explorer` to be docked on the bottom/top

### ISSUE THREAD

**Issue by RayBenefield** [microsoft/vscode#118926]
Related to #49923 and #10121

## Feature Request

Allow `Explorer` to be docked on the bottom/top similar to other panels and not explicitly only a sidebar to support cases where vertical monitors are used. 

## Context

I use a vertical monitor for my work, normally Kakoune, but I'm using VS Code to work with a client. I spent a bit trying to shift the `explorer`/sidebar to the bottom and realized it was only able to be docked on the left or right. Would be nice to have `explorer` work like other panels to be shifted where we need it. I'd personally like the bottom.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by genesis-algorithms** [comment]
+1. Just started to code on a vertical monitor and that's indeed a necessary feature IMO. You can already move search and source control to the bottom where the terminal is, If the same is possible for explorer it would be superb.

**Comment by convertra** [comment]
I switched to Webstorm because of this.

**Comment by drfunctor** [comment]
Is there really no way to do that currently? Can an extension solve this?

**Comment by ryan-archetype** [comment]
Adding a +1 to this, as I just started using a vertical monitor and was looking for a way to move the sidebar to the bottom.

**Comment by rtkshahwar** [comment]
Adding a +1 I am also looking for a way to move the explorer bar to the bottom amid usage of vertical monitor.

**Comment by jamesfranklinnetsec** [comment]
> 

what

**Comment by daanmlab** [comment]
+1 Would also highly appreciate this

**Comment by alexnguyennz** [comment]
+! It would be great to be able to dock explorer/search to the bottom.

**Comment by duyhnguyen1** [comment]
+1 Highly appreciate this, please make this happen

**Comment by rileyjsumner** [comment]
Yes, myself and many devs on my team use vertical monitors for code, allowing explorer to be horizontal on bottom pane would be super helpful

**Comment by chrisdicarlo** [comment]
This seems like a simple request given it's already possible to move other views into the panel.  I also just switched to a vertical orientation and this is a big inconvenience.  If PHPStorm supports this, it might be time to have another look at it... Disappointed in the vscode teams response.

**Comment by luisWZ** [comment]
+1 As all people have mentioned, it could be super useful to have the ability to move the explorer to the bottom panel for vertical monitor orientation.

**Comment by jerryav** [comment]
i too use a vertical monitor and it would be really helpful to have the contents of activity bar like explorer,extensions docked to bottom in the panel .

**Comment by ronbot-58** [comment]
I'm just surprised that they called it not important... Portrait mode makes coding so much easier for me as well... but that darn Primary & Activity Side Bar takes up too much room at the side when using Portrait mode monitors.

**Comment by Saussky** [comment]
Would really appreciate this feature to free up space for vertical monitors

**Comment by ryansand20** [comment]
+1 This feature is needed for use with vertical monitors

**Comment by krokodok** [comment]
+1 Would really appreciate this!!

**Comment by rafaelmaruta** [comment]
+1 Would really appreciate this as well!

**Comment by mkwoodburn** [comment]
+1 I This would be a great feature!!

**Comment by nithinkr1shna** [comment]
+1, Would be a great feature!

**Comment by alexnguyennz** [comment]
+1 This would be really nice to have.

**Comment by Marsel-marsel** [comment]
It will be a good feature!

**Comment by sreerag-ms** [comment]
It'd be a great feature to have.

**Comment by geniusnut** [comment]
Get here for my new portarit monitor in office!

**Comment by Brockenstein** [comment]
+1 on the use of a verticle monitor and it being advantageous for the explorer to be moved to the top as I actually want the code only up so high on the screen anyway. So being able to move that to the top instead of having to keep closing and reopening the explorer would be very helpful.

**Comment by rohitramu** [comment]
+1

**Comment by ACoolmanBigHealth** [comment]
+1

**Comment by krokodok** [comment]
Guys, they did it!!! 😮 

https://code.visualstudio.com/updates/v1_76#_moveable-explorer-view

**Comment by chrisdicarlo** [comment]
OMG!  Sweet!

**Comment by xianghongai** [comment]
Nice! For Portrait!

**Comment by xianghongai** [comment]
![image](https://user-images.githubusercontent.com/2075006/229723429-cfa9ebd1-2173-4a90-a007-745a85ca350b.png)

need to support icons, leave more space~

**Comment by Lambdaphile** [comment]
> need to support icons, leave more space~
> 
> ![image](https://user-images.githubusercontent.com/2075006/229723429-cfa9ebd1-2173-4a90-a007-745a85ca350b.png)

You can toggle the activity bar from settings.
