### ISSUE TITLE
usage vscode in window& ubuntu cause file broken!

### ISSUE THREAD

**Issue by kinglintianxia** [microsoft/vscode#118957]
I use vscode editor mostly in ubuntu, but some time I need modify some files in windows install on the same labtop, there was two times of file broken happend to me. After I modified the file in windows,  I switch to ubuntu open the same file use vscode, it  shows that the file becomes binary or unsupported text encoding. Please fix it!

**Comment by bpasero** [comment]
Are you using WSL to connect to the Linux or how do you edit the same file?

**Comment by kinglintianxia** [comment]
> Are you using WSL to connect to the Linux or how do you edit the same file?

My laptop is installed with dual systems(win+ubuntu), and sometimes the same file is modified, which may be caused by switching between two systems, not by vscode maybe..

**Comment by bpasero** [comment]
Is there some special file system driver used to use the same file system for Windows and Linux?
