### ISSUE TITLE
Executing terminal > run task two times will not terminate the original task when restart is selected

### ISSUE THREAD

**Issue by depeter** [microsoft/vscode#118963]
- VS Code Version: 1.54.2 (system setup)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Start a long running task defined in your package.json using Terminal > Run Task > select the long running task
2. Repeat step 1, a popup will ask you to restart the task: click restart
3. The task starts running but the first running task is never terminated it seems
4. A bit later you'll get the notification: "The connection to the terminal's pty host process is unresponsive, the terminals may stop working."

Expected result: 
The first task should be terminated and the new task should start without crashing the pty host process.

In my case I am working on an electron - angular 10 application and am running the electron app as an npm task.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by alexr00** [comment]
I'm not able to reproduce this issue. When I choose to "Restart" I see that the original task terminates, then the new task starts. Is your project in an open source repo that I can look at? If you open the developer tools (command Developer: Toggle developer tools), are there any errors in the console?

**Comment by depeter** [comment]
Thank you for taking the time to look into this. 

Unfortunately it's not an open source project but I could also reproduce it with a skeleton app of electron and angular. You can find it here: https://github.com/maximegris/angular-electron

Commands to run:
```
git clone https://github.com/maximegris/angular-electron.git

npm install

npm start
```

Once installed follow the repro steps with 'npm start' as the long running task.

![image](https://user-images.githubusercontent.com/8808339/111161088-07125880-859b-11eb-93aa-f0965d818c5a.png)

Here is the dev tools log:

![image](https://user-images.githubusercontent.com/8808339/111161335-56f11f80-859b-11eb-9d17-15b18cce181a.png)

**Comment by depeter** [comment]
Ok, turns out I just had to restart my PC. That weirdly enough resolved the issue. I can now no longer reproduce this issue with the steps I mentioned.
