### ISSUE TITLE
sync failed

### ISSUE THREAD

**Issue by biniyam112** [microsoft/vscode#118980]
Issue Type: <b>Bug</b>

changed theme

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:50.094Z)
OS version: Linux x64 5.10.0-kali3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 1995)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|11.61GB (2.14GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 8297ad89-36bb-485d-8557-b0ade98c4e64|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
ng-template|Ang|11.2.7
code-gnu-global|aus|0.2.2
vscode-django|bat|1.3.0
vscode-intelephense-client|bme|1.6.3
phpserver|bra|3.0.1
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
vscode-postgres|cko|1.1.17
bracket-pair-colorizer-2|Coe|0.2.0
c-cpp-compile-run|dan|1.0.13
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-eslint|dba|2.1.18
githistory|don|0.6.16
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.17
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.2.0
git-project-manager|fel|1.7.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.24.0
gc-excelviewer|Gra|3.0.41
beautify|Hoo|1.5.0
monkey-patch|ioc|0.1.12
fontawesome-autocomplete|Jan|1.1.2
vue|jcb|0.1.5
pubspec-assist|jer|2.2.1
vscode-hacker-typer|jev|0.1.1
Angular2|joh|11.0.0
solidity|Jua|0.0.108
theme-dark-plus-contrast|k3a|0.1.101
vscode-github|Kni|0.30.4
dart-import|lua|0.3.1
MagicPython|mag|1.1.0
font-awesome-codes-html|med|0.0.7
vscode-language-babel|mgm|0.0.30
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
vscode-docker|ms-|1.10.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
debugger-for-chrome|msj|4.12.12
awesome-flutter-snippets|Nas|2.0.4
vetur|oct|0.33.1
material-icon-theme|PKi|4.5.0
java|red|0.76.0
LiveServer|rit|5.6.1
color-manager|roy|0.6.2
bootstrap4-vscode|the|6.1.0
python|tht|0.2.3
lorem-ipsum|Tyr|1.2.0
adb-interface-vscode|vin|0.21.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-icons|vsc|11.2.0
jinja|who|0.0.8
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0
clang-format|xav|1.9.0
json|Zai|2.0.2
material-theme|zhu|3.9.15
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by sandy081** [comment]
Can you please add more information that what failed? Is there an error message or notification?
