### ISSUE TITLE
VSCode unable to exit when open across multiple W10 desktops

### ISSUE THREAD

**Issue by cipher982** [microsoft/vscode#118922]
- VS Code Version: 1.54.1
- OS Version: Windows 10 Pro - 21292.1010

Steps to Reproduce:

1. Click `Update Now` to restart VSCode and update when prompted.
2. Click `Yes` when prompted `There is an active terminal session, do you want to kill it?` (due to setting `"terminal.integrated.confirmOnExit": true`).
3. VSCode will close the current window, but if there is another active session on another virtual Windows 10 desktop, another prompt will stay open on that desktop where a user may be unaware of.
4. All virtual desktops must be cycled through to be sure all instances are manually closed before being able to update.

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Do you get the same behavior if you simply run `File > Exit`?

**Comment by cipher982** [comment]
Yes. It brings up a prompt for whether I want to kill my active terminal sessions as it does during the update process, where I have to move across multiple virtual desktops to find each individual prompt for the related window/instance. And since Windows does not show VSCode open in the taskbar if it's on another desktop, the only way to know is check task manager or scroll through each desktop.

**Comment by Tyriar** [comment]
This is acting as designed to make sure you don't lose your terminal sessions. It would be improved when we get https://github.com/microsoft/vscode/issues/23808

/duplicate
