### ISSUE TITLE
macOS crashes when opening vscode with sidecar plugged in

### ISSUE THREAD

**Issue by atxy-blip** [microsoft/vscode#118920]
Issue Type: <b>Bug</b>

Hello, I am currently working on hackintosh. After I plugged in my iPad and turned on Sidecar, the streaming worked perfectly. However, when I tried to launch VS Code, it only showed the frame of the program window, then the display blacked out and the system reboot instantly. I'm wondering if this is caused by graphics rendering problem, although the system is running on a compatible RX560. Thanks for any help.

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 0|
|Memory (System)|16.00GB (10.48GB free)|
|Process Argv|--crash-reporter-id 2426d3cd-ca1a-43c0-987c-b75e7d25e5e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
latex-workshop|Jam|8.16.1
vscode-clang|mit|0.2.3
vscode-language-pack-zh-hans|MS-|1.54.2
python|ms-|2021.2.636928669
jupyter|ms-|2021.3.619093157
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cmake|twx|0.0.17
vscode-icons|vsc|11.1.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by deepak1556** [comment]
Does the issue happen when you disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration ?
