### ISSUE TITLE
No option to change color of URL string in code like in other editors. Please don't ignore.

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode#118966]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open this code in vs code : https://pastebin.com/gxd27Cg6
2. Here we can not see any difference that there is a link opened here.
3. And yes, this is not a theme specific issue, I tried it out with different themes out in the market.
2. Compare results by opening same in ATOM CODE EDITOR.
4. Attaching Image for reference:

![Screenshot (20)](https://user-images.githubusercontent.com/54276661/111019146-50b84300-83e3-11eb-8f43-45c290e7ff21.png)

_I also tried to use **Developer: Inspect Editor Tokens and Scopes** and tried some things in settings.json file, but they were of no use_

**So what I want is that there should be a option out there to change the color, so anybody who wants that can do that.** 

**Thank You**

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The `Developer: Inspect Editor Tokens and Scopes` tool shows you the scopes generated by the html grammar

![image](https://user-images.githubusercontent.com/6461412/111174737-f74d4100-85a7-11eb-875d-a582cf3e428f.png)

![image](https://user-images.githubusercontent.com/6461412/111174643-e3094400-85a7-11eb-8b83-6c1e710610ff.png)

They are not the same, so you can write a coloring rule to give one of them a different color:

![image](https://user-images.githubusercontent.com/6461412/111175833-16000780-85a9-11eb-80fe-06935da658d7.png)

```
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": ["meta.tag.metadata.script.start string.quoted.double.html", ],
				"settings": {
					"foreground": "#FF0000",
				}
			}
		]

	}
```
I don't know why Atom is different. It might use a different HTML grammar than VSCode, or the themes are different.

Closing as with the information above you can customize your themes or create a new theme.

**Comment by lakshits11** [comment]
Ya but why does it not color the https://www/google.com

**Comment by aeschli** [comment]
You can also color https://www/google.com by looking at the TextMate scope and add it to you customization. I somehow understood you only want links in `src`.

Maybe I misunderstood your request then. What do you want to have colored differently?
