### ISSUE TITLE
Typescript - Problem with IntelliSense with no suggestions inside decorator function 

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#118971]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:
![12](https://user-images.githubusercontent.com/17777237/111150780-2effbd00-8597-11eb-8c81-1fed0174c031.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

/needsMoreInfo

**Comment by pixieaka** [comment]
@mjbvz

```
// autobind decorator
function AutoBind(_target: any, _methodName: string, descriptor: PropertyDescriptor) {
    const originalMethod = descriptor.value;
    const adjastedDiscriptor: PropertyDescriptor = {
        configurable: true,
        get() {
            const boundFn = originalMethod.bind(this);
            return boundFn;
        }
    };

    return adjastedDiscriptor;
}
// autobind decorator
```

**Comment by mjbvz** [comment]
This is expected because the type of `PropertyDescriptor.value` is `any`. If you have over `originalMethod `, you can also see it's type is `any`
