### ISSUE TITLE
The error is not marked with a red background box when inputting an invalid ACR name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode#118945]
- VS Code Version: **VS Code Insider 1.55.0-insider** (**Not reproduce** in **VS Code 1.54.2**)
- OS Version: Wind 10

**Steps to Reproduce:**

1. Install Docker extension and try to create a new Azure Container Registry with an invalid name.
2. Check the error.

**Expect:**
The error is marked with a red background box.
![image](https://user-images.githubusercontent.com/45614674/111111928-2eb4f100-859a-11eb-8494-cd8f1ad6b7b6.png)

**Actual:**
The error is not marked with a red background box.
![image](https://user-images.githubusercontent.com/45614674/111111932-31afe180-859a-11eb-8144-e029055e0a09.png)

Does this issue occur when all extensions are disabled?: Yes

**More Info:**
1. This issue also reproduces when creating a web app.
2. This issue does not reproduce in VS Code: 1.54.2.

**Comment by bwateratmsft** [comment]
@weinand I think this might be due to VSCode actually, not the Docker extension--

- The issue appears in VSCode insiders but not main
- The validation function _is_ being called, hence the error message, but the message does not have the red border / background it used to have

**Comment by weinand** [comment]
@bwateratmsft thanks for investigating this.

**Comment by fbricon** [comment]
I can confirm the bug, coming from vscode-insiders
