### ISSUE TITLE
Option to always show webview developer tools while developing a custom editor extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#118919]
I have set up this keybinding to lessen the pain of opening up the webview's devtools every time I open an image tab:

```json
{ "key": "ctrl+shift+i",     "command": "workbench.action.webview.openDeveloperTools", "when": "activeCustomEditorId == 'luna.editor' && !isMac" },
{ "key": "cmd+alt+i",        "command": "workbench.action.webview.openDeveloperTools", "when": "activeCustomEditorId == 'luna.editor' &&isMac" },
```

It would be much nicer if we could have some way while developing an extension to open the webview devtools for a particular webview automatically when the webview is shown. This would probably make the most sense as part of the launch.json, eg:

```json
    {
      "name": "Extension",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=${workspaceFolder}/..",
        "--autoOpenDevtoolsForWebview=luna.editor"
      ],
      "outFiles": [
        "${workspaceFolder}/out/**/*.js"
      ]
    },
```

**Comment by Tyriar** [comment]
@connor4312 is there a better way to do this? I see https://github.com/microsoft/vscode/issues/96626, is there a way to debug extension contributed webviews within VS Code?

**Comment by connor4312** [comment]
Yes, you can do this. Check out https://github.com/microsoft/vscode/issues/101320

**Comment by Tyriar** [comment]
@connor4312 `"webview.experimental.useIframes": true` seems to break the extension, there's no errors in the console and debugging doesn't want to work.

Maybe I'm doing something wrong wrt debugging though, I do have a warning in launch.json still:

![image](https://user-images.githubusercontent.com/2193314/111155104-3c925400-8551-11eb-9949-af3a167de4ea.png)

**Comment by connor4312** [comment]
Set your launch type to `pwa-extensionHost` isntead of `extensionHost`

> "webview.experimental.useIframes": true seems to break the extension,

cc @mjbvz

**Comment by mjbvz** [comment]
Please open a separate issue if something about iframe based webviews is not working

**Comment by Tyriar** [comment]
It works 😍 I'm having issues getting ts breakpoints bound but that's likely a sourcemaps issue on my end since js breakpoints are hit. Thanks for the help!
