### ISSUE TITLE
TypeScript: Code styling broken when no EOL semi-colons

### ISSUE THREAD

**Issue by madaz** [Microsoft/vscode#119]
v 0.10.1
Theme: Dark

Code styling is broken when not using semi-colons ";" for end of line.
I have my tslint to force excluding ";"

If I add a semi-colon to line 6, it all works again

![capture](https://cloud.githubusercontent.com/assets/1139901/11255957/e2d53968-8e94-11e5-9af9-00bff41199d9.PNG)

**Comment by dbaeumer** [comment]
This is a problem with the textmate grammar provided by the TypeScript team. Opened https://github.com/Microsoft/TypeScript-Sublime-Plugin/issues/399
