### ISSUE TITLE
Go-to definition on a event goes to Event-type

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119086]
* using 4.3.0-dev-20210305
* go to [onDidSaveDocument](https://github.com/microsoft/vscode/blob/a6d7d86e85799e6d243aed4430456627c76f7782/src/vs/workbench/api/common/extHost.api.impl.ts#L826)
* press F12
* instead of going to the definition of that event ([here](https://github.com/microsoft/vscode/blob/9cc276648eb03bd5256f9c2595245f2fc47e2ff7/src/vs/workbench/api/common/extHostDocuments.ts#L28)), TypeScript brings you to the definition of `Event`

**Comment by mjbvz** [comment]
Opened https://github.com/microsoft/TypeScript/issues/43276 to track upstream

**Comment by jrieken** [comment]
likely because https://github.com/microsoft/vscode/pull/117424 and eager sorting
