### ISSUE TITLE
Add css colors applied to Webview Iframe on the event handled by Window.onDidChangeActiveColorTheme

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#119072]
Add css colors applied to Webview Iframe on the event handled by Window.onDidChangeActiveColorTheme.
Currently this event is not useful because it only says if the color is light, dark or hight contrast. Every time a webview is created vscode theme colors are applied to its iframe. You could grab those same colors and add to the event that is dispatched when the theme color has changed. Like, 

````json
{
    " type": "light",
     "colors": {
         "--vscode-editor-background" : "#ffffff"
     }
}
````

or

````json
{
    " type": "light",
     "colors": {
         "editor.background" : "#ffffff"
     }
}
````

**Comment by mjbvz** [comment]
`Window.onDidChangeActiveColorTheme` is a generic dom api and tracks the user's system color theme. To access VS Code color theme color, use [the css variables](https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content)

**Comment by AllanOricil** [comment]
You did not understand. window.onDidChangeActiveColorTheme is not standard, it was implemented to wrap the standard method, but its event is kind not that useful. What can I do just knowing if the colors are light, dark or highcontrast? The idea that I'm proposing is to grab those css colors you add to the iframe of the webview and emit them on the onDidChangeActiveColorTheme event. Like, just reading the method's name I bet that every developer would be expecting to get the current vscode colors, not just light, dark or highcontrast.

**Comment by mjbvz** [comment]
Oh ok, so its not even inside the webview then? There should be not reason to sync the theme colors across to the webview since the css variables already have these

**Comment by AllanOricil** [comment]
I have a use case where I would like to use those css colors outside of vscode. I created a feature to my extension that I called "window mode". Basically I'm serving the same extension as a PWA. One thing that my app does is that it changes its color when the user selects a new theme inside vscode. This way I was able to maintain the same looking and feel. But at the moment I implemented it using a hack. To determine the current colors I spawn a new webview, then I extract the colors applied to its dom, and finally I emit these colors to my webapp. It works really well. But the problem is that I have to open an close a webview very quickly just to extract the colors, because there is no API to grab the current colors. I thought it is kind weird we have an API that listen to theme color changes but does not emit the colors. Another weird thing is that if those colors are calculated and applied to the webview at runtime, why couldnt  you emit those inside the onDidChangeActiveColorTheme() event? It would make this method more useful and I would not need to use this hack I mentioned.

**Comment by AllanOricil** [comment]
This is how I got the colors


````js
this._panel = vscode.window.createWebviewPanel(
                this._name,
                this._name,
                vscode.ViewColumn.Three,
                {
                    enableScripts: true,
                }
            );

            this._panel.webview.html = `<!doctype html>
            <html>
            <body>
                <script>
                const vscode = acquireVsCodeApi();
                const colors = {};
                Object.values(document.getElementsByTagName('html')[0].style).forEach(
                    (rv) => {
                    colors[rv] = document
                        .getElementsByTagName('html')[0]
                        .style.getPropertyValue(rv)
                    }
                )
                vscode.postMessage(colors);
                </script>
            </body>
            </html>`;

            this._panel.webview.onDidReceiveMessage((colors)=>{
                this._colors = colors;
                this._panel.dispose();
                this._panel = null;
                this.sendColors()
            })

````

**Comment by mjbvz** [comment]
Then this is a duplicate of #32813. It does not seem webview related
