### ISSUE TITLE
Bad suggestion sorting for TS compared to JS

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#1190]
Going for the for loop snippet:

## JavaScript (snippet is close by):
![forjs](https://cloud.githubusercontent.com/assets/5047891/11741172/7d04981c-9ff7-11e5-81c8-e99c45a0723c.gif)

## TypeScript (snippet is after many non relevant suggestions):
![forts](https://cloud.githubusercontent.com/assets/5047891/11741199/9802b338-9ff7-11e5-80d0-3bd0512679aa.gif)

**Comment by alexandrudima** [comment]
@jrieken I still see on master the exact behaviour from the second gif: The for loop snippet is after a lot of other stuff at the end of the suggestion list.

**Comment by jrieken** [comment]
yeah, actually TypeScript provides a non-clever `sortText` which breaking this...
