### ISSUE TITLE
Running extension tests on "Run and Debug" show no output

### ISSUE THREAD

**Issue by luyuhuang** [microsoft/vscode#119062]
- VS Code Version: 1.54.3
- OS Version: Windows_NT x64 10.0.18363 / WSL Ubuntu-18.04

I have ever written a vscode extension https://github.com/luyuhuang/vscode-rss. But today I found that it didn't output any test results when I run "Extension Tests" on "Run and Debug".

![image](https://user-images.githubusercontent.com/10300685/111288495-326e7380-867f-11eb-97a5-84662227cade.png)

This is my `launch.json`:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "npm: compile"
		}
	]
}
```

And the output looks like this:

```
> Executing task: npm run compile <


> rss@0.9.3 compile /home/luyuhuang/PROJECT/JavaScript/vscode-rss
> rm -rf ./out && tsc -p ./


Terminal will be reused by tasks, press any key to close it.

> Executing task: npm run compile <


> rss@0.9.3 compile /home/luyuhuang/PROJECT/JavaScript/vscode-rss
> rm -rf ./out && tsc -p ./


Terminal will be reused by tasks, press any key to close it.
```

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
@joaomoreno was seeing something similar, forwarding to @connor4312 since it seems like the output is not coming from the js-debug extension.

**Comment by connor4312** [comment]
You're looking at the terminal where the build task is running. Neither `rm` nor `tsc` will produce output unless there are any errors. You want to be looking at the Debug Console for your output:

![](https://memes.peet.io/img/21-03-4454a607-3a20-40eb-b9ce-a6ae18319849.png)

**Comment by luyuhuang** [comment]
> You're looking at the terminal where the build task is running. Neither `rm` nor `tsc` will produce output unless there are any errors. You want to be looking at the Debug Console for your output:

Thanks for your reply. On Windows, It's OK. But On Windows + WSL, I cannot see any outputs on the Debug Console neither.

**Comment by connor4312** [comment]
Thanks, I can repro

**Comment by connor4312** [comment]
This'll be fixed in the next release, and on Insiders tomorrow most likely

**Comment by luyuhuang** [comment]
Thanks!
