### ISSUE TITLE
simple-browser is not restored on page reload

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#119057]
I can reproduce it in Gitpod and Codespaces:
- run a command `Simple Browser: Show`
- open some URL, i.e. localhost
- reload the page

The simple browser is gone. It would be nice if it implements `WebviewPanelSerializer`.

**Comment by mjbvz** [comment]
Just a note about this: we can only restore the last url the user explicitly navigated to. With the security restrictions of iframes, we can't detect when the user navigates on a page (this is also why the address bar doesn't update)
