### ISSUE TITLE
VS Icons are not displaying

### ISSUE THREAD

**Issue by nitinbansal1989** [Microsoft/vscode#11903]
- VSCode Version: 1.5.2
- OS Version:  Mac OS 10

Just got update for 1.5.2 vs code. After update vs-icons are not displaying.

**Comment by ramya-rao-a** [comment]
@nitinbansal1989 Are you referring to the icons in the explorer from the **vscode-extension** extension?

**Comment by nitinbansal1989** [comment]
yes

**Comment by ramya-rao-a** [comment]
@nitinbansal1989 If icons from the ** vscode-icons** are not appearing, please log an issue in the repo for that extension.

You can also try the new File Icon Themes feature that has been released in the latest VS Code version.
![image](https://cloud.githubusercontent.com/assets/16890566/18483641/caff2f06-7999-11e6-9277-48e6be726828.png)

**Comment by bpasero** [comment]
Please do NOT install the vscode-icons extension, we strongly advise against it. You can use our official icon themes that got available starting with 1.5.
