### ISSUE TITLE
Test: multi cursor accessibility

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#119082]
Refs: https://github.com/microsoft/vscode/issues/109918

- [x] anyOS @sana-ajani
- [x] anyOS @alexr00
- [ ] anyOS @chrisdias (Optional)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119082%0A%0A)

---

* Turn on Screen Reader, open an editor (make sure you say you have are using a screen reader, or simply put `editor.accessibilitySupport: "on"`)
* Add an additional cursor: verify that the new cursor line and column is announced by the screen reader
* Add multiple additional cursors at once (for example via large selection and Add Cursor To End Lines command): verify that all the new cursor line and columns are announced
* Try to add an additional cursor when it is not possible to add it(for example Add Cursor Line Below on the last line): verify nothing gets read out
* When having multiple cursors press `Esc` and verify that it is announced that additional cursors have been removed

Try to be creative and think what could improve this experience.

**Comment by dbaeumer** [comment]
@isidorn assigned you to fix test plan item.

**Comment by alexr00** [comment]
Tested with Windows + NVDA.

**Comment by TylerLeonhardt** [comment]
Closing for bookkeeping but feel free to test @chrisdias
