### ISSUE TITLE
setting "complete function calls" does not add parentheses

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#119035]
- VS Code Version: Version: 1.54.2
- OS: Linux x64 5.4.67-09356-gf3ed4c0c4a31
- OS Version: Debian 9 via Chromebook Crostini

Steps to Reproduce:

1. Create a .js file
2. Begin typing a function, either a built in, or one already existing in the file.  
3. Accept the intellisense suggestion.
4. No automatic parentheses or function signature is created, even when settings > javascript: complete function calls is enabled.  

Does this issue occur when all extensions are disabled?: Yes

Note, this also occurs on my other machine, which is a Mac running latest stable.  

I don't believe I have any setting that conflicts with "complete function calls," but I'm happy to provide any additional info that might help!

**Comment by mjbvz** [comment]
Please share an example where this doesn't work

**Comment by ultraGentle** [comment]
@mjbvz Re: Example, what's most useful?  A gif?  Just want to make sure I'm understanding correctly what info you need.

**Comment by ultraGentle** [comment]
Here's a GIF demoing the cases where it works and doesn't: https://gfycat.com/carefulvibrantblackbuck

In <script> tags, never works
In .js file, works for functions, but not methods

**Comment by mjbvz** [comment]
Please share a code example (as text) where it does not work in a JS file.

Also this setting only applies to JS files so it would not work html script tags at the moment

**Comment by ultraGentle** [comment]
For example, if you have the function `function test(a,b) {return a+b;},` and you type `tes` and accept the suggestion, you'll get the full `test(a,b)` completed, not just `test`.

However (see gif at bottom for demos), 
1. it appears not to work in `<script>` tags 
2. it appears not to work for methods, e.g. `document.getElementById()`
3. it appears not to work for built-ins, like `new Date()`

thus restricting its usefulness.

**Comment by ultraGentle** [comment]
I discovered that the `()` completion is connected to using "Enter" to accept the suggestion.  

I had a custom keybinding for "accept suggestion" instead, with "Enter" disabled for that purpose; 

When I re-enabled the default keybinding, `document.getElementById()` did complete parentheses in the `.js` document.  

But notably, `new Date()` did not, still.

**Comment by ultraGentle** [comment]
I've opened a FR (#119336) for the <script> tag aspect, and I'll leave this open for the seeming bug of the setting not working when it should.  

Please feel free to close this one if they are too similar!

**Comment by mjbvz** [comment]
Built-in methods work fine in my testing:

![Mar-19-2021 14-34-47](https://user-images.githubusercontent.com/12821956/111844439-494fd880-88c0-11eb-9cda-d2fc620a9604.gif)

Please share an example where it does not

Also this setting does not apply to constructors, only calls (but also `Date` can take zero parameters, so even if we did support constructors, there would not be a change in behavior)

**Comment by ultraGentle** [comment]
Example: 25 seconds into the GIF https://gfycat.com/carefulvibrantblackbuck `document.getElementById` does not complete.  

Just prior, `test(a,b)` does -- so the setting is on and working, but not consistently.  

(Note: The first part of the gif was for <script> tags, now addressed in #119336.)

Maybe useful for debugging this: I had the "Enter" keybinding disabled for accepting suggestions, instead replaced by a custom keybinding.  But, **when I re-enabled the default accept-suggestion keybinding**, the setting did complete as expected on my Linux machine, but not my Mac.

**Comment by ultraGentle** [comment]
Nothing new to report on this.
