### ISSUE TITLE
The "SOURCE CONTROL" panel cannot recognize the git repository when using the git executable from MSYS2.

### ISSUE THREAD

**Issue by fengyoulin** [microsoft/vscode#119041]
- VS Code Version: 1.54.3
- OS Version: Windows 10 x64, [10.0.19042.867]

Steps to Reproduce:

1. Install MSYS2, with the installer downloaded from it's homepage [https://www.msys2.org/](https://www.msys2.org/)
2. Install git in MSYS2's command prompt, use the command `pacman -S git`
3. Set `git.path` in VSC's preferences to the path of the git executable file just installed
4. In VSC, open any folder containing a git repository, the "SOURCE CONTROL" cannot recognize

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by lszomoru** [comment]
As of right now, VS Code does not support the version of git that gets installed through MSYS2 (feature request is tracked [here](https://github.com/microsoft/vscode/issues/143165)). To leverage the git functionality in VS Code please install [Git for Windows](https://gitforwindows.org/).
