### ISSUE TITLE
"php.validate.executablePath": "c:/php/php.exe"

### ISSUE THREAD

**Issue by ebprince-tech** [microsoft/vscode#119029]
I have tried everything to get the php 8 and then the stable 7 version including xaamp installations and this pathway page and suggestions DO NOT WORK!  I just want to edit a php script and this is now day 4 trying.  Please help me!

**Comment by roblourens** [comment]
Can you give some more details about exactly what you are trying? The builtin PHP support is very simple, you may want to install an extension for better intellisense.

**Comment by ebprince-tech** [comment]
Hello and thank you for replying to this huge frustration of mine.

The objective is to get php working in Visual Studio.  Actually, it is IntelliSense and another extension that informs me that I need to go to settings in a JSON file to correct the pathway.
It seems simple when reading the Lint screen in VS, but nothing has worked so far.

What have I tried to do?  I have downloaded and placed php on C: directly and changed the pathway in windows to the same.  Then, I did the same with xampp as c: xampp/php and tried c:xampp/php/php.  Then, I changed the php development file to a php ini file after viewing a youtube video on installations etc.,

That is why I needed to reach out, as I am completely miffed!

Earle

________________________________

**Comment by ebprince-tech** [comment]
Hi, here are attachments for the json file that the extension tells me to correct!

________________________________

**Comment by roblourens** [comment]
There are no attachments, they are not sent with email. But if you are trying to use a PHP extension, then please file this issue on the extension's repo.
