### ISSUE TITLE
Unable to launch VSCode after macOS unexpected reboot

### ISSUE THREAD

**Issue by peterflynn** [microsoft/vscode#119027]
- VS Code Version: 1.52.1
- OS Version: macOS 10.15.7

Steps to Reproduce:

1. macOS unexpected crash (e.g. kernel panic, or battery dies... or possibly also scheduled/auto-reboot to install updates, see #110202)
2. When computer reboots, it tries to restore / reopen all apps that were open before the crash
3. Click VSCode icon to launch it

Result: Dock icon bounces for a second, then immediately closes again. Looks like VSCode is crashing on launch.

Does this issue occur when all extensions are disabled?: Yes

```
code --verbose  --log trace --disable-extensions                                    
[main 2021-03-15T23:05:13.631Z] Sending env to running instance...
[main 2021-03-15T23:05:13.635Z] Sent env to running instance. Terminating...
[main 2021-03-15T23:05:13.636Z] Lifecycle#kill()
```

**Workaround**

1. Open Activity Monitor and kill the process generically named "Electron"
2. Verify that any "Code Helper" & "Code Helper (GPU)" processes have disappeared after this
3. Relaunch VSCode the normal way (e.g. from Dock icon)

**Comments**

This appears to be the same issue as #81970, where a number of comments at the bottom are expressing confusion about how to apply the workaround – but I can't comment there to clarify the workaround since it's locked 😢

It wasn't explicitly mentioned there that you have to kill a process called "Electron," and if you interpret the workaround as killing processes named "Code" then you get into an infinite whack-a-mole trying to kill the lingering "Code Helper" & "Code Helper (GPU)" processes – they change PID every few seconds. Even if you multi-select in Activity Monitor and Force Quit all of them at once, more are respawned a moment later.

**However,** regardless of the workaround I believe this is a real bug that should be kept open.  OS reboots are not _that_ rare, and if it's common for VSCode to inexplicably become un-launchable afterward, that really should be fixed.

(#22449 and #110202 seem likely to be other reports of this this same issue as well. _Possibly_ #8119, #18521 too).

**Comment by bpasero** [comment]
I don't know enough how the macOS restarts applications after a reboot but the symptoms here are that a first instance of VSCode is running and as such the second invocation tries to send data to the running instance and then terminates.

When this happens: can you capture the full list of processes running for VSCode and possibly check for any logs (F1 > Open Logs Folder) that could hint to errors on that happened on startup.

**Comment by peterflynn** [comment]
@bpasero 

> I don't know enough how the macOS restarts applications after a reboot but the symptoms here are that a first instance of VSCode is running and as such the second invocation tries to send data to the running instance and then terminates.

Yep, that seems like the technical explanation – the problem being since VS Code doesn't show as active in the dock it's not obvious to users why it can't be launched nor is it clear what to do to resolve it.
<br>

> can you capture the full list of processes running for VSCode

At the time I was hitting this, running `ps aux | grep Code.app` gave:
```
pflynn           27133   6.1  0.2  4507816  30736   ??  S     4:07PM   0:00.05 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app/Contents/MacOS/Code Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,7270836167948267380,953309328641694485,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --disable-color-correct-rendering --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAACAEAACAAAAAAAQAAAAAAAAgBAAAAAAAAEAEAAAAAAAAYAQAAAAAAACABAAAAAAAAKAEAAAAAAAAwAQAAAAAAADgBAAAAAAAAQAEAAAAAAABIAQAAAAAAAFABAAAAAAAAWAEAAAAAAABgAQAAAAAAAGgBAAAAAAAAcAEAAAAAAAB4AQAAAAAAAIABAAAAAAAAiAEAAAAAAACQAQAAAAAAAJgBAAAAAAAAoAEAAAAAAACoAQAAAAAAALABAAAAAAAAuAEAAAAAAADAAQAAAAAAAMgBAAAAAAAA0AEAAAAAAADYAQAAAAAAAOABAAAAAAAA6AEAAAAAAADwAQAAAAAAAPgBAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAIAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAAAAAAABwAAABAAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAAAAAA0AAAAQAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAAAgAAABAAAAAAAAAAAQAAAAYAAAAQAAAAAAAAAAEAAAAHAAAAEAAAAAAAAAABAAAACAAAABAAAAAAAAAAAQAAAAoAAAAQAAAAAAAAAAEAAAALAAAAEAAAAAAAAAABAAAADQAAABAAAAAAAAAABAAAAAAAAAAQAAAAAAAAAAQAAAACAAAAEAAAAAAAAAAEAAAABgAAABAAAAAAAAAABAAAAAcAAAAQAAAAAAAAAAQAAAAIAAAAEAAAAAAAAAAEAAAACgAAABAAAAAAAAAABAAAAAsAAAAQAAAAAAAAAAQAAAANAAAAEAAAAAAAAAAGAAAAAAAAABAAAAAAAAAABgAAAAIAAAAQAAAAAAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAABwAAABAAAAAAAAAABgAAAAgAAAAQAAAAAAAAAAYAAAAKAAAAEAAAAAAAAAAGAAAACwAAABAAAAAAAAAABgAAAA0AAAA= --shared-files
pflynn           13117   5.3  0.3  9282392  52192   ??  S     3Feb21  32:32.43 /Applications/Visual Studio Code.app/Contents/MacOS/Electron --crash-reporter-id fd69010a-e9d0-452b-bd90-c57db9f3da91
pflynn           13125   0.0  0.0  4427276    600   ??  S     3Feb21   0:02.66 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --no-upload-gzip --monitor-self-annotation=ptype=crashpad-handler --database=/Users/pflynn/Library/Application Support/Code/Crashpad --metrics-dir=/Users/pflynn/Library/Application Support/Code --url=appcenter://code?aid=860d6632-f65b-490b-85a8-3e72944f7774&uid=fd69010a-e9d0-452b-bd90-c57db9f3da91&iid=fd69010a-e9d0-452b-bd90-c57db9f3da91&sid=fd69010a-e9d0-452b-bd90-c57db9f3da91 --annotation=_companyName=Microsoft --annotation=_productName=VSCode --annotation=_version=1.52.1 --annotation=prod=Electron --annotation=ver=9.3.5 --handshake-fd=27
pflynn            3820   0.0  0.0  4435468    676   ??  S     2Feb21   0:02.18 /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Helpers/chrome_crashpad_handler --no-rate-limit --no-upload-gzip --monitor-self-annotation=ptype=crashpad-handler --database=/Users/pflynn/Library/Application Support/Code/Crashpad --metrics-dir=/Users/pflynn/Library/Application Support/Code --url=appcenter://code?aid=860d6632-f65b-490b-85a8-3e72944f7774&uid=fd69010a-e9d0-452b-bd90-c57db9f3da91&iid=fd69010a-e9d0-452b-bd90-c57db9f3da91&sid=fd69010a-e9d0-452b-bd90-c57db9f3da91 --annotation=_companyName=Microsoft --annotation=_productName=VSCode --annotation=_version=1.52.1 --annotation=prod=Electron --annotation=ver=9.3.5 --handshake-fd=27
pflynn           27142   0.0  0.0  4277556    760 s008  S+    4:07PM   0:00.00 grep Code.app
```

One seemingly odd thing about this is that the OS had just hard-rebooted on March 15, so it's pretty strange that `ps` thinks three of those processes had been running since early February?? Perhaps this is some quirk of how macOS restarts processes after a crash/restart?
<br>

> check for any logs (F1 > Open Logs Folder) that could hint to errors on that happened on startup

In `~/Library/Application Support/Code/logs` I can see a whole bunch of _empty_ folders on the day I hit this – I'm guessing one per failed launch attempt? – followed by one final folder that seems to correspond to the time I successfully relaunched VS Code after finally killing the generic "Electron" process.  I'm assuming those logs are not relevant, though...

It seems like most useful would be logs for the original zombie process that was hanging around headlessly, blocking subsequent launch attempts from doing anything.  If this happens again is there anything I can try to do to force the zombie VS Code process to dump some useful info?

**Comment by bpasero** [comment]
Maybe @deepak1556 could have a look, this seems like hanging crash reporter processes.

**Comment by peterflynn** [comment]
@bpasero thanks for the response! Should this go back to Open or is there not enough info to look into it further?

If anyone has time free to try hitting this more reproducibly, #110202 suggests this might occur with a scheduled restart for macOS updates, too.  Which means it might also repro if you just manually go to _Apple menu > Restart_ while VS Code is left open.
