### ISSUE TITLE
could not install python and pylance extension in remote machine

### ISSUE THREAD

**Issue by ROGERDJQ** [microsoft/vscode#119073]
- VSCode Version:1.54.3
- Local OS Version:  window10
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
0. A totally new local machine with windows 10; and remote ubuntu which winstall these extensions before; 
1. Install vscode in local windows machine and use ssh extension to get access to remote ubuntu;
2. try to install python and pylance extension;
3. get error "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'."

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

<Some information>
I notice that this issue has been proposed here(https://github.com/microsoft/vscode/issues/117986). Yet after I get a totally new machine and install the newest vscode, the bug remains, which makes me very disappointed.

**Comment by ROGERDJQ** [comment]
[renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
at /remote-home/jqdai/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by sandy081** [comment]
Can you please try installing `ms-toolsai.jupyter` extension and let me know if you are seeing this?

**Comment by ROGERDJQ** [comment]
0. Try to solve this issue, I uninstall all the python, pylance, and jupyter extensions in both local and remote machine. 
1.  I try to install the  `ms-toolsai.jupyter`  locally----> successful; install the  `ms-toolsai.jupyter` in remote machine ----> successful.
2. install the `ms-python.python` locally ---> successful;  install the `ms-python.python` in remote machine---> get error msg "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3' but get successful installation after few seconds.
3. install the `ms-python.vscode-pylance` locally ---> successful,  install the `ms-python.python` in remote machine---> get error msg "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
4. I try to install `ms-python.python` and `ms-python.vscode-pylance`  from **VSIX**. **BOTH WORK WELL.** 
I guess that is the solution to this strange issue.

**Comment by sandy081** [comment]
I cannot repro this when using remote containers. Can you please provide following logs at step 2 (Please enable log level to trace before doing so)

- Log (Window)
- Log (Remote Server)

- Do you have setting `remote.downloadExtensionsLocally` set to `true` ?

- How are you trying to install the extension on remote window? Can you please provide a video of how you are doing this?

**Comment by ROGERDJQ** [comment]
I am not sure how to get the log. Yet for the last two questions. I get the following things:
0. Yes, the `remote.downloadExtensionsLocally` is true
1. the following gif records the installation of the python extension in my remote machine. Please be patient to wait until the ending of this gif. 
![pylance_debug_2](https://user-images.githubusercontent.com/25008973/111629041-d72db400-882b-11eb-877b-17513d3963c9.gif)

**Comment by ROGERDJQ** [comment]
It seems not allowed to upload files larger than 10 MB here. I am figuring how to upload the video since I can repro this issue every time unless of the vsix installation.

**Comment by sandy081** [comment]
Can you please try setting `remote.downloadExtensionsLocally` to `false`?

**Comment by hamptons** [comment]
@sandy081 I get the same error trying to install the Python extension in a container, regardless of whether `remote.downloadExtensionsLocally` is set to `true` or `false` . 

`[2021-03-19 12:48:56.188] [remoteagent] [error] Error: Failed Installing Extensions: ms-python.python
    at w.installExtensions (/vscode/vscode-server/bin/x64/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:79:121)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Installing the Jupyter extension standalone seems to be ok because it installs v2021.3.619093157, which I assume is the latest stable version. But my guess is that for some reason it is trying to install the insiders preview (v2021.4.641214696) when installed by the Python extension.

I have copied the vsix for an older version of the Python extension into the container and this installs successfully and installs Jupyter v2021.3.619093157.

The behaviour is the same whether installing via devcontainer.json, the extensions pane in the UI or using the cli.

I'm not sure where you set the log level. If you can point me in the right direction I will set the level to trace and provide the logs.

**Comment by ROGERDJQ** [comment]
> Can you please try setting `remote.downloadExtensionsLocally` to `false`?
It seems to work well if  set `remote.downloadExtensionsLocally` to false for me

**Comment by passionsfrucht** [comment]
Looks like I posted the [comment to the wrong bug](https://github.com/microsoft/vscode/issues/117986#issuecomment-803472481)? (https://github.com/microsoft/vscode/issues/117986)

Anyway, `remote.downloadExtensionsLocally` was set as true on the remote server, not locally and not in the workspace, though. Disabling it remotely did indeed help.

**Comment by RobCannon** [comment]
We have a situation where the remote does not have internet access and remote.downloadExtensionsLocally must be set to true to install other extensions.

**Comment by sandy081** [comment]
Assigning to March for investigating by using `remote.downloadExtensionsLocally` setting

**Comment by EmbeddedBacon** [comment]
Was following [this issue](https://github.com/microsoft/vscode-jupyter/issues/4992), but it was closed by upstream issue tracker [here](https://github.com/microsoft/vscode/issues/117986).   Though did find this issue.  The output logs show

```
[2021-03-23 16:00:01.900] [renderer1] [error] Error while installing 'ms-python.python' extension in the remote server. unable to get local issuer certificate
[2021-03-23 16:00:01.900] [renderer1] [info] Trying to download 'ms-python.python' extension locally and install
[2021-03-23 16:00:34.148] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.","    at /users/_user_/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-23 16:00:34.200] [renderer1] [error] ["downloading: unable to get local issuer certificate","    at Ee.downloadInstallableExtension (/users/_user_/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:103266)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-23 16:00:34.275] [renderer1] [error] unable to get local issuer certificate: downloading: unable to get local issuer certificate
    at Ee.downloadInstallableExtension (/users/_user_/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:103266)
```

**Comment by ROGERDJQ** [comment]
Since I report this issue, there is one pylance update(3.2), one python update(v2021.3.680753044), I have installed them quite well after I change the `remote.downloadExtensionsLocally` to false. I guess this can be one solution to those who have same issue.

**Comment by sandy081** [comment]
Thanks everyone for confirming that you can repro it with when you set `remote.downloadExtensionsLocally` to `true`. I tried it and I **can repro** it in stable (**not** in insiders though). 

By enabling this setting, I download the extensions on the client side and stream downloaded vsixs to remote server to install. There is a bug that I am not downloading compatible extensions (deps) which caused this. Fixed it.

**Comment by sandy081** [comment]
To verify:

This cannot be verified on insiders as this happens only on stable. So I would recommend to verify **running from sources**:

- Set the version of VS Code in `package.json` to `1.54.3`
- Enable extensions gallery in `product.json` - please ping me in slack if you do not know how to do this.
- Start VS Code from sources
- Open settings and enable `remote.downloadExtensionsLocally` to `true`
- Open `Remote-TestResolver: New Window`
- Install `Python` extension - make sure it succeeds
-

**Comment by anied** [comment]
@sandy081 Thanks Sandeep for addressing this-- I've tried @ROGERDJQ 's [proposed workaround to this issue](https://github.com/microsoft/vscode/issues/119073#issuecomment-800839617) but it did not work for me, so I am looking forward to this fix.  Do you have any idea when it will be released into VSCode stable?

**Comment by sandy081** [comment]
We will be releasing this is coming stable which is planned next week.

**Comment by EmbeddedBacon** [comment]
So, v1.55 was release a bit early, compared to previous release history, and I was able to install Python and Jupyter on my remote machine without any issues.  Looks like Jupyter was updated also.

**Comment by bjayakumar** [comment]
HI My remote machine is not connected to the internet, so I am trying to install `ms-toolsai.jupyter` using VSIX, but I got struck. 
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.55.2'.

**Comment by Stephanevg** [comment]
Hi guys, I do have the same issue as @bjayakumar 

In my case, I am not even remote. This is a fresh VSCode installation, followed immediatley by the installation of my-python.python extension.

I wanted to run a python debugger, and had a message saying i needed ``ms-toolsai.jupyter`` exension. 

I went ahead with that, and it said that it is not compatible with vscode '1.55.2'. 

(I have done all the installation offline, as i need this on a server that doesn't have internet access).

I am blocked, as I cannot run a debug mode for any pythong script. Please advice on how to fix this.


ms-python.python

![image](https://user-images.githubusercontent.com/6302961/115857586-26b85e80-a42e-11eb-9367-fadae7782cf9.png)


![image](https://user-images.githubusercontent.com/6302961/115857096-8f530b80-a42d-11eb-9625-476db899605e.png)

![image](https://user-images.githubusercontent.com/6302961/115857162-a3970880-a42d-11eb-8327-d45b49ffd829.png)

ms-toolsai.jupyter --> 2021.6.777186939

**Comment by odhran-o-d** [comment]
I am having the ame issue as @bjayakumar when attempting to install ms-tools.ai.jupyter. 
![image](https://user-images.githubusercontent.com/39832722/115892438-0cdb4380-a44f-11eb-9ae4-aa2d037454b5.png)

**Comment by GMetola** [comment]
I have a computer that is not allowed to connect to internet. To install extensions I have to download .vsix files.
After many errors in different versions triggering `Unable to install extension 'ms-toolsai.jupyter' as [...]`

I **successfully installed** this group:
- VSCodeSetup-x64-1.55.2.exe
- jupyter-2021.3.619093157_vsixhub.com.vsix
- python-2021.3.658691958_vsixhub.com.vsix

<img width="344" alt="working" src="https://user-images.githubusercontent.com/47193318/115989552-459a2a80-a5bf-11eb-99cd-8b625cc46de4.png">

I hope it helps someone. Have a nice day. :-)

**Comment by bskp** [comment]
Thank you so much, @GMetola! Had the same issue on my airgapped VS Code installation and the same combination of versions did it for me.
