### ISSUE TITLE
float graphics painting !

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#119077]
this is random and rare but here a screen , sometime i getting weirds graphics elements floating in my workspace.
![image](https://user-images.githubusercontent.com/24865815/111306081-260dfa80-862e-11eb-93b4-6192d12556ed.png)

i have no more info sorry, is happen randomly and rarely
i put this here to see if am the only one.
It disappear after ~2 min by toggle focus activity window many time!!! 

---

Version : 1.54.2 (user setup)
Commit : fd6f3bce6709b121a895d042d343d71f317d74e7
Date : 2021-03-11T00:56:19.848Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/24865815/111306332-79804880-862e-11eb-9883-de43fc605e5a.png)

**Comment by deepak1556** [comment]
Can you check if the issue happens after disabling hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by djmisterjon** [comment]
> Can you check if the issue happens after disabling hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
i will wait some days to see if it happening against, am trying understand why this can happen ! sometime by switching monitors , i get weird behavior from electron app, not only vscode.

**Comment by djmisterjon** [comment]
cant reproduce with explaination
