### ISSUE TITLE
Something peculiar with the search engine

### ISSUE THREAD

**Issue by suprunyasha** [microsoft/vscode#119044]
Seems like search engine cannot fine the word that is actually in the file. Will send over the screenshot as soon as the case will be opened
![image](https://user-images.githubusercontent.com/72506123/111266310-6627aa00-863b-11eb-8a91-f08ba498d2a3.png)

**Comment by usernamehw** [comment]
You have case sensitive search checkbox enabled:

![111266310-6627aa00-863b-11eb-8a91-f08ba498d2a3](https://user-images.githubusercontent.com/9638156/111272701-0386dc00-8644-11eb-8458-cd421bcd6343.png)

**Comment by suprunyasha** [comment]
That was so obvious, yet I was not attentive enough :D thanks a lot!
