### ISSUE TITLE
git changes do not show up until restarted

### ISSUE THREAD

**Issue by nExoRek** [microsoft/vscode#119058]
- VS Code Version:
- OS Version:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. change file
2. see that changes are not refleceted
3. restart VSC to see list of changed files

Does this issue occur when all extensions are disabled?: Yes

this is duplicate to https://github.com/Microsoft/vscode/issues/70312 but this one has been closed and locked. i do not have any additional entries in setting.json. moreover - i'm working on two VSC on two computers, very similar configuration (nuance differences) and i don't have the issue on one, but have on another. i think it started after recent big Windows update but not sure. adding info on the system config where the is no issue:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by nExoRek** [comment]
just to add: it behaves randomly by stopping and starting to work, while using git from commandline. 
(have to use from commandline since VSC is so grumpy...)
no visible pattern i can notice.

**Comment by lszomoru** [comment]
@nExoRek, are you still experiencing this issue with the latest version of VS Code? Thanks!
