### ISSUE TITLE
Workbench navigation commands do not work inside extension WebView panels

### ISSUE THREAD

**Issue by infokiller** [microsoft/vscode#119076]
This issue is a resurrection of https://github.com/microsoft/vscode/issues/100536 which wasn't fixed.

- VS Code Version: 1.54.3
- OS Version: `Linux 5.11.2-arch1-1`

## Steps to reproduce

- Set the following keybindings:

  ```json
  [
    {
      "key": "f1",
      "command": "workbench.action.navigateLeft"
    }
  ]
  ```

- Open any file you want
- Use  to split the editor to the right
- Use  to open the Release Notes WebView
- Type <kbd>F1</kbd> from the WebView to navigate to the left editor

Does this issue occur when all extensions are disabled?: Yes

**Comment by infokiller** [comment]
Note that the issue is inconsistent but can be reliably reproduced if you navigate back and forth quickly in succession (takes me less than 20 seconds to repro).

**Comment by mjbvz** [comment]
Not for testing the key is that you press `f1` before clicking into the release notes. Clicking into the release notes focuses them, after which point `f1` should start working

**Comment by infokiller** [comment]
I can verify this is fixed after clicking into the release notes, but the issue seems to persist whenever you navigate to a new webview. I will open a new issue for this.
