### ISSUE TITLE
Markdown: Code blocks lose colorization sometimes

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#11906]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2012R2

Steps to Reproduce:

1. Create a markdown file with the following contents:

    ```
    asdf
    
    `qwer` `zxcv`
    ```

1. Both `qwer` and `zxcv` should be colorized.

    ![1](https://cloud.githubusercontent.com/assets/1096010/18449965/1ecd4780-78e6-11e6-8b90-acc63d9f11b9.png)

1. Delete the empty line (line 2).

1. `qwer` remains colorized. `zxcv` loses color.

    ![2](https://cloud.githubusercontent.com/assets/1096010/18450006/4d2e2e5a-78e6-11e6-8a8b-ce29173b3f7a.png)

**Comment by mjbvz** [comment]
This does not seem to be inline code specific but also applies to other inline elements, such as bold and italic:

Example md:

```md
`b`
`b` `b` *b*

*b*
*b* *b* `b`


**b**
**b** **b** `b`
```


<img width="228" alt="screen shot 2016-09-19 at 5 57 40 pm" src="https://cloud.githubusercontent.com/assets/12821956/18654100/5cd39b44-7e93-11e6-9b64-4cb98fd4d87c.png">

**Comment by mjbvz** [comment]
Fixed by https://github.com/Microsoft/vscode-textmate/pull/24 which we took into vscode with 966e89535b2127cdbc285534171575b0d5b2841a
