### ISSUE TITLE
Cannot open BBEdit from VSCode via macOS Spotlight

### ISSUE THREAD

**Issue by alanwilter** [microsoft/vscode#119074]
- VS Code Version:
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
- OS Version:
```
macOS Big Sur
11.2.3
```
- Problem
If using `code .` (command line), this issue is not present.
If starting VSCode from e.g. macOS Spotlight, `BBEdit` will fail with this error:
```
$ git -c core.quotepath=false -c color.ui=false difftool --no-prompt --tool=bbdiff -- app.py
You must allow `bbdiff` to send events to the BBEdit application.
Use `tccutil reset AppleEvents` to reset the system's permissions, and try again.
bbdiff: error: -1743
fatal: external diff died, stopping at app.py
```
Steps to Reproduce:

1. Use a git project, e.g., `git clone https://github.com/alanwilter/flask-pytest-example`
2. Add to your `~/.gitignore`:
``` bash
git config --global diff.tool bbdiff
git config --global difftool.bbdiff.cmd 'bbdiff --wait --resume "$LOCAL" "$REMOTE"'
git config --global difftool.prompt false
```
2. Start VSCode via Spotlight
3. Change file `app.py` and save it.
4. Open a terminal (cmd-J) inside VSCode
5. Run this command:
``` bash
git -c core.quotepath=false -c color.ui=false difftool --no-prompt --tool=bbdiff -- app.py
```

Does this issue occur when all extensions are disabled?:
Can't test this way.

- Possible Solution:
Please see https://github.com/desktop/desktop/issues/9050 for details but, essentially, VSCode is using the macOS Hardened Runtime, but does not have a code-signing entitlement to allow it to send Apple Events to other applications.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/119787

This is fixed in our insiders version and will be fixed in the next stable release.
