### ISSUE TITLE
how to prevent "shift" from changing my CTFMON(input method)

### ISSUE THREAD

**Issue by wqdsg** [microsoft/vscode#119061]
Background：There are two methods to highlight the following words

B1111111111111111111111111111111111111111111111111111
1111111111111111111111111111111111111111111111X

Method 1：			
1. Move the pointer to be front of "B"；		
2. Press the mouse Left  and hold on；		        
3. Move the pointer to be behind of "X"
4. Release the mouse left.

Method 2:
1. Move the pointer to be front of "B"；
2. Click the mouse Left ；	
3. Press "shift" and hold on;
4. Move the pointer to be behind of "X";
5. Click the mouse Left
6. Release the "shift"

I am used to use the method 2. 

Problem:
In vscode, this method will make my CTFMON（输入法，input method）change from English mode to Chinese mode, or Chinese mode to Eng mode.
However, in editing softwares, such as Word, PowerPoint, notepad(txt), chrome, DingDing, using method 2 would not make the CTFMON change.
How can I fix this?

ps: I am used to use the "shift" to change Chinese to English, and not used to use method 1. Please dont advise me to shut down the  function that "shift" changes CTFMON or to use method 1. Thx very much!

**Comment by yume-chan** [comment]
Presumedly you are using Windows.

I tested with Dingtalk, Word and Notepad, they all switch Chinese input mode when pressing Shift and click to select text.

The only exception is when not focusing on an input box, for example selecting webpage text in Chrome.
