### ISSUE TITLE
VS Code consuming 100% CPU, 5GB RAM

### ISSUE THREAD

**Issue by infoash1** [microsoft/vscode#119042]
VS Code is consuming 100% CPU, 5GB RAM soon after I open it. This is happening since 3/12/2021.
Here is the screenshot:
![Task Manager CPU 100% Memory 5GB](https://user-images.githubusercontent.com/75107481/111261973-955cfd80-85e0-11eb-8a94-5feaa05ae562.png)

Here is the version info:
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Performance-Issues for advice about investigating and reporting performance issues.

**Comment by tastypurgen** [comment]
Have the same issue but only after "git checkout". 
It started since the end of previous week, probably since 3/12/2021 as author mentioned

**Comment by Minifish57** [comment]
same on mac os Big Sur , after every git checkout (monorepo project) I have an infinite rg processes that takes up all of my cpu ... i've disabled follow symlinks , i've add pattern in watcher , disabled all the extensions , but nothing seems to work

**Comment by dbaeumer** [comment]
@infoash1 which extensions do you have installed. The process consuming CPU is a Java VM hence I assume you are doing Java development. Is this correct?

**Comment by infoash1** [comment]
I have installed a few extensions and I uninstalled them all after the issue started occurring. But still I am facing the same the issue.  I am working on the Salesforce, not Java.

**Comment by dbaeumer** [comment]
You can use extension bisect to find the extension that causes this described here https://code.visualstudio.com/blogs/2021/02/16/extension-bisect (VS Code itself doesn't ship any Java Runtime). If you have tracked down the extension please report the issue there.

**Comment by infoash1** [comment]
I have uninstalled all the extensions except the Salesforce Extension Pack. But the issue still exists.
I will uninstall the VS Code entirely along with the Java and redo it.

**Comment by infoash1** [comment]
I did not uninstalled VS Code, but I downgraded Java. Here are my steps.
1. Uninstalled Java 11 and installed a lower version of Java 8.
2. Restricted the Java memory allocation by updating the setting in VS Code. Here is the screenshot.
![Java Memory Allocation](https://user-images.githubusercontent.com/75107481/111921269-f3f70100-8a50-11eb-8236-9774c17c478b.jpg)

**Comment by dbaeumer** [comment]
@infoash1 this is a problem with the Salesforce extension pack and you need to report the issue with their issue tracker.
