### ISSUE TITLE
Up/down after selecting text moves text cursor corresponding to end of selection, not its current position

### ISSUE THREAD

**Issue by Arnavion** [microsoft/vscode#11905]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2012R2

Steps to Reproduce:
1. Type multiple lines of text:
   
   ```
   asdf
   qwer
   ```
2. Position text cursor at line 1 column 4, i.e. between `d` and `f`, then hold <kbd>Shift</kbd> and press <kbd>Left arrow</kbd> twice to select `s` and `a`. Now `asd` should be selected and text cursor should be at line 1 column 1.
3. Release <kbd>Shift</kbd> and press <kbd>Down arrow</kbd>

Expected:

Selection is cleared and text cursor is at line 2 column 1, i.e. before `q`.

Actual:

Selection is cleared and text cursor is at line 2 column 3, i.e. between `e` and `r`.

**Comment by Bill-Stewart** [comment]
The behavior described here would be preferable to me also (it seems more intuitive based on the visible location of the cursor). It would be nice to have this as an editor option.
