### ISSUE TITLE
Typescript: '__spreadArrays' helper is being ignored

### ISSUE THREAD

**Issue by peter-meinhardt** [microsoft/vscode#119078]
Issue Type: <b>Bug</b>

- Install "typescript": "3.5.3" and "tslib": "^1.10.0"
- Use a spread operator on an array
- Error "This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'." is being displayed

Expected Behavior:
tslib@1.10.0 uses the helper '__spreadArrays' instead of '__spreadArray' for spread operators. This helper is deprecated in newer versions and has been replaced with '__spreadArray', but it should not be ignored by VS Code if an older version of tslib has been installed. VS Code 1.53.2 doesn't display the error.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|-psn_0_499834 --crash-reporter-id 8c94e34a-2a1e-4491-8dc3-3b53f9f817b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
ng-template|Ang|11.2.8
regex|chr|0.4.0
gitignore|cod|0.6.0
vscode-svgviewer|css|2.0.0
git-extension-pack|don|0.1.3
githistory|don|0.6.16
gitlens|eam|11.3.0
vscode-great-icons|emm|2.1.67
prettier-vscode|esb|6.2.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
sass-lint|gle|1.0.6
vscode-angular2-emmet|jak|2.0.3
docthis|joe|0.7.1
Angular2|joh|11.0.0
HTMLHint|mka|0.10.0
vscode-typescript-tslint-plugin|ms-|1.3.3
angular2-inline|nat|0.0.17
vscode-versionlens|pfl|1.0.9
typescript-hero|rbb|3.0.0
autoimport|ste|1.5.3
vscode-icons|vsc|11.2.0
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by mjbvz** [comment]
This doesn't sound like an editor issue to me. Please file it against TypeScript instead

**Comment by peter-meinhardt** [comment]
I am pretty sure it _is_ an editor issue. This error appears only after updating VS Code from version 1.53.2 to 1.54.3. It doesn't appear in any other IDEs either and neither does it while building my application. I also didn't update any packages in the project. In fact, I currently have several projects opened with both VS Code 1.53.2 and 1.54.3. The error only appears in 1.54.3 and nowhere else.

**Comment by mjbvz** [comment]
Are you using eww rosacea version of TypeScript?

**Comment by peter-meinhardt** [comment]
Well, didn't know that was a thing. Now it works, thank you very much :)
