### ISSUE TITLE
Markdown preview not working

### ISSUE THREAD

**Issue by mojaveazure** [Microsoft/vscode#11901]
- VSCode Version: 1.5.1
- OS Version: Ubuntu 16.04 64-bit

Every time I try to use the preview for Markdown in Code on Ubuntu 16.04, I get `command 'markdown.showPreviewToSide' not found` or `command 'markdown.showPreview' not found`

Steps to Reproduce:
1. Open Markdown document
2. Press `ctrl+shift+v` or `ctrl+k, v` to preview formatted markdown

**Comment by vlad-saling** [comment]
I see the same issue. 
OS: macOS 10.12.1
VScode: Version 1.8.0-insider

**Comment by leaxoy** [comment]
Same +1

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15184
