### ISSUE TITLE
Notebook files do not handle all onFocusChange situations correctly

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#119026]
- VS Code Version: 1.55.0-insiders
- OS Version: Mac BigSur 11.2.1

Steps to Reproduce:

1. Open a .py file
2. Open an .ipynb file (Jupyter extension)
3. Open VS Code settings
4. Change File: Auto Save to onFocusChange
5. Edit the .py file and click in the terminal window
6. Result: .py file is saved
7. Edit a cell of the .pynb file and click in the terminal window
8. Result .pynb is not saved

Note: The save does seem to work when clicking out to another editor. So moving to the .py does save the .ipynb.

![image](https://user-images.githubusercontent.com/812783/111233478-4ac08e80-85aa-11eb-8f7f-8822df4053f1.png)
Typing focus is in terminal here. Dirty .ipynb is not saved. .py files does save in the same setting / circumstances.

There was an existing issue here #96673. But I wasn't sure about re-activating an old issue. 

Does this issue occur when all extensions are disabled?: Jupyter extension needed to open the .ipynb

**Comment by rebornix** [comment]
@IanMatthewHuff can you help verify if you can still reproduce? I tried with latest but didn't reproduce anymore.

**Comment by IanMatthewHuff** [comment]
@rebornix I do still see the issue with today's insiders. I've attached a GIF. A .py file with the same steps does save.

![AutoSave](https://user-images.githubusercontent.com/812783/112555147-d85b6580-8d84-11eb-8619-25c21bc08a21.gif)

Need me to collect any logging or other info?

**Comment by rebornix** [comment]
@IanMatthewHuff best gif ever, I can reproduce with your steps. 

* Auto save set to onFocusChange
* Open the integrated terminal
* Open a notebook and then modify
* Click on the terminal

File not saved.

**Comment by rebornix** [comment]
@bpasero any idea? If I have notebook in one editor group and have a text editor in another editor group, clicking between them will trigger save but moving focus from notebook to terminal doesn't. Is this handled by workbench or the notebook editor doesn't give workbench the right focus event?

**Comment by bpasero** [comment]
@rebornix notebooks doing something wrong, the code to save relies on the `onDidBlur` of editor panes:

https://github.com/microsoft/vscode/blob/a830cb5f74e5a487dd8a764c84e1fa38f3e763dd/src/vs/workbench/browser/parts/editor/editorAutoSave.ts#L85-L87

**Comment by rebornix** [comment]
This turns out to be non-trivial and custom editors have the same issue.

**Comment by rebornix** [comment]
I'm not seeing https://github.com/microsoft/vscode/issues/119026#issuecomment-807832325 anymore.
