### ISSUE TITLE
Python discover tests failing with json parser error

### ISSUE THREAD

**Issue by ajaythompson** [microsoft/vscode#119068]
- VS Code Version: 1.54.3
- OS Version: Windows 10 enterprise

Steps to Reproduce:

1. Install python extension.
2. Create any pytest and run discovery tests.

Does this issue occur when all extensions are disabled?: NA

# Error from output
Error 2021-03-16 15:43:09: Python Extension: displayDiscoverStatus [SyntaxError: Unexpected token S in JSON at position 4208
	at JSON.parse (<anonymous>)

**Comment by aeschli** [comment]
This issue needs to be filed against https://github.com/Microsoft/vscode-python/issues
