### ISSUE TITLE
ALT + Arrows does not work in integrated terminal 

### ISSUE THREAD

**Issue by BobReid** [Microsoft/vscode#11908]
Alt and arrow keys insert characters into the terminal buffer instead of navigating to the begging and ends of words in the integrated terminal

Environment:
OS: OS X El Capitan 
Version: VSCode 1.5.2

Repro:
1. Open Integrated terminal 
2. Type 'cd ~/'
3. Press Alt + Left Arrow

Expected:
Cursor should jump to begin of ~/ so ~ is highlighted

Actual 
;5D is inserted into the buffer at cursors current location

**Comment by Tyriar** [comment]
I think this will be fixed when we uplevel xterm.js via https://github.com/sourcelair/xterm.js/commit/8324b43cc25a60d0f6088bfd5d5c20170f9ece77

**Comment by BobReid** [comment]
Is this fixed? I Just updated to 1.6.0 and am still seeing the issue in the integrated terminal.

**Comment by Tyriar** [comment]
It doesn't seem to be on Mac only. I reopened the upstream issue https://github.com/sourcelair/xterm.js/issues/225

**Comment by viztastic** [comment]
Issue still exists for me as well.

**Comment by Tyriar** [comment]
There is a PR put out upstream for this today https://github.com/sourcelair/xterm.js/pull/417

**Comment by BobReid** [comment]
Upstream PR was merged

**Comment by jonhoo** [comment]
Is this related to `Alt+Backspace` not working?

**Comment by Tyriar** [comment]
@jonhoo we need a generic solution for this, here's the issue https://github.com/Microsoft/vscode/issues/11314
