### ISSUE TITLE
When write html code with emmet, inline element can't spread out in a vertical row.

### ISSUE THREAD

**Issue by zhibisora** [microsoft/vscode#119088]
Issue Type: <b>Feature Request</b>

When write html code with emmet, inline element can't spread out in a vertical row.
Does VScode have this function? I want the inline element can spread out in a vertical row instead of a line.

For example,
btn*3 => 
&lt;button&gt;&lt;/button&gt;
&lt;button&gt;&lt;/button&gt;
&lt;button&gt;&lt;/button&gt;

But now, it is
btn*3 => &lt;button&gt;&lt;/button&gt;&lt;button&gt;&lt;/button&gt;&lt;button&gt;&lt;/button&gt;

That's not very intuitive.

![微信截图_20210316222454](https://user-images.githubusercontent.com/73344387/111327732-98232580-86a8-11eb-9e1a-15d711905241.png)

![微信截图_20210316224528](https://user-images.githubusercontent.com/73344387/111328625-5e065380-86a9-11eb-8283-f5c9b5ad04da.png)

Also,block element can spread out in a vertical row like &lt;div&gt;.

![微信截图_20210316222524](https://user-images.githubusercontent.com/73344387/111327771-a113f700-86a8-11eb-9179-6dad4c0818dc.png)

![微信截图_20210316222533](https://user-images.githubusercontent.com/73344387/111327783-a40ee780-86a8-11eb-8b44-b1d16c0c8a15.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

**Comment by rzhao271** [comment]
We need to add `'output.inlineBreak': number;` to the extension in the preferences so that the parameter can be passed upstream, for example see https://github.com/emmetio/emmet/blob/master/src/config.ts#L129

**Comment by ArturoDent** [comment]
There is an emmet setting for this:

```jsonc
"emmet.syntaxProfiles": {

  "html": {
    "inline_break": 1
  },
}
```  

With that setting inline elements will break to a newline after one such element.

**Comment by rzhao271** [comment]
Yeah, that's using an older config type (which we still support, but `emmetio/emmet` itself doesn't). My change just adds support for the newer config type.

Verifier:
In `settings.json` add the following setting:
```json
"emmet.preferences": {
  "output.inlineBreak": 3
}
```

Verify that in an HTML file, `span*3` ends up with each `<span></span>` on its own line, and that `span*2` ends up expanding to `<span></span><span></span>`.
