### ISSUE TITLE
Add simplified notebook data provider

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119089]
Todays `NotebookContentProvider` is putting lots of responsibilities onto extensions. In return, it allows for notebooks that aren't stored on disk or are composed of multiple files (like a directory is a notebook). However, the internals that connect to the content provider assume that one notebook is one file. Making this assumption (once it is correctly implemented) makes the life of notebook extension authors much simpler: vscode can take care of file watching, concurrent write etc etc. However,  when the internals take soo much responsibilities than the current API is too complex: it can be a simple as converting bytes to notebook data and vice versa. 

This issue is about adding such a new simplified API. This is the proposal

```ts
export interface NotebookSerializer {
  dataToNotebook(data: Uint8Array): vscode.NotebookData | Thenable<vscode.NotebookData>;
  notebookToData(data: vscode.NotebookData): Uint8Array | Thenable<Uint8Array>;
}
```

**Comment by jrieken** [comment]
Current work happens in the `joh/nbSerialize` branch

**Comment by jrieken** [comment]
Will finish this early April

**Comment by DonJayamanne** [comment]
> In return, it allows for notebooks that aren't stored on disk or are composed of multiple files (like a directory is a notebook)

I can see this being used in scenarios where one might want to use Jupyter Notebooks as a scratch pad (or just displaying output).

**Comment by jrieken** [comment]
Closing as we have shipped this and are at a stage at which we recommend this over the content provider API
