### ISSUE TITLE
VS Code is very slow

### ISSUE THREAD

**Issue by msalmankarim** [microsoft/vscode#119055]
VS code is very slow for last 2 days. Didn't installed any new extension. Even disabled all the extensions but no improvement in performance.

[prof-2373.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6147114/prof-2373.main.cpuprofile.txt)
[prof-2373.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6147115/prof-2373.renderer.cpuprofile.txt)
[prof-2373.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6147116/prof-2373.extHost.cpuprofile.txt)

**Comment by dbaeumer** [comment]
@msalmankarim which OS are you on?

**Comment by msalmankarim** [comment]
Edition	        Windows 10 Pro
Version	        20H2
Installed on	‎2020-‎06-‎12
OS build	        19042.844
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by jrieken** [comment]
@msalmankarim the profiles don't show anything specific. What you problem? Do you see slow startup or slowdowns while using VS Code?

**Comment by msalmankarim** [comment]
@jrieken On startup VS code is always slow but once the extensions are loaded it works fine. But for the last couple of days whenever I use the vscode it takes lot of memory and became very hard to code on and use my windows. Once I close the vscode, everything works fine.

Yesterday I uninstalled the vscode completely and removed the folders from AppData and re-installed it again but performance was same.

**Comment by jrieken** [comment]
Let's start with the following. Please select "F1 > Startup Performance" and copy-paste the readings here

**Comment by msalmankarim** [comment]
## System Info

* Code: 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8)
* OS: win32(10.0.19042)
* CPUs: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz(12 x 2904)
* Memory(System): 31.74 GB(14.01GB free)
* Memory(Process): 197.25 MB working set(177.67MB private, 0.27MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------ |
| start => app.isReady                                            | 93       | [main]                    | initial startup: true                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                      |
| require(main.bundle.js)                                         | 74       | [main]                    | initial startup: true                      |
| app.isReady => window.loadUrl()                                 | 167      | [main]                    | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 962      | [main->renderer]          | NewWindow                                  |
| require(workbench.desktop.main.js)                              | 291      | [renderer]                | cached data: YES, node_modules took 0ms    |
| wait for shell environment                                      | 0        | [renderer]                | -                                          |
| init storage (global & workspace)                               | 0        | [renderer]                | -                                          |
| require & init workspace storage                                | 24       | [renderer]                | -                                          |
| init workspace service                                          | 45       | [renderer]                | -                                          |
| register extensions & spawn extension host                      | 740      | [renderer]                | -                                          |
| restore viewlet                                                 | 13       | [renderer]                | workbench.view.explorer                    |
| restore panel                                                   | 0        | [renderer]                | -                                          |
| restore editors                                                 | 449      | [renderer]                | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 604      | [renderer]                | -                                          |
| workbench ready                                                 | 2164     | [main->renderer]          | -                                          |
| renderer ready                                                  | 951      | [renderer]                | -                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                          |
| extensions registered                                           | 2530     | [renderer]                | -                                          |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 5         | 0             | 6               | *                                                     | vscode.debug-auto-launch                |
| vscode.git                              | true  | 22        | 5             | 83              | *                                                     | vscode.github                           |
| vscode.github                           | true  | 6         | 0             | 8               | *                                                     | vscode.github                           |
| PKief.material-icon-theme               | true  | 7         | 0             | 7               | *                                                     | PKief.material-icon-theme               |
| vscode.css-language-features            | false | 44        | 9             | 0               | onLanguage:scss                                       | vscode.css-language-features            |
| vscode.emmet                            | false | 13        | 2             | 19              | onLanguage:html                                       | vscode.emmet                            |
| vscode.extension-editing                | false | 37        | 1             | 181             | onLanguage:typescript                                 | vscode.extension-editing                |
| vscode.github-authentication            | false | 10        | 2             | 225             | onAuthenticationRequest:github                        | vscode.github-authentication            |
| vscode.html-language-features           | false | 16        | 11            | 8               | onLanguage:html                                       | vscode.html-language-features           |
| vscode.markdown-language-features       | false | 42        | 5             | 0               | onLanguage:markdown                                   | vscode.markdown-language-features       |
| vscode.merge-conflict                   | false | 5         | 2             | 16              | onStartupFinished                                     | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 15        | 4             | 167             | onAuthenticationRequest:microsoft                     | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 12        | 2             | 14              | onStartupFinished                                     | ms-vscode-remote.remote-wsl-recommender |
| ms-vscode.js-debug                      | false | 101       | 8             | 0               | onCommand:extension.js-debug.clearAutoAttachVariables | ms-vscode.js-debug                      |
| vscode.testing-editor-contributions     | false | 2         | 0             | 14              | onStartupFinished                                     | vscode.testing-editor-contributions     |
| vscode.typescript-language-features     | false | 70        | 181           | 8               | onLanguage:typescript                                 | vscode.typescript-language-features     |
| Angular.ng-template                     | false | 302       | 3             | 5               | onLanguage:html                                       | Angular.ng-template                     |
| esbenp.prettier-vscode                  | false | 48        | 14            | 1               | onStartupFinished                                     | esbenp.prettier-vscode                  |
| rafaelsalguero.csharp2ts                | false | 888       | 2             | 0               | onCommand:extension.cs2ts                             | rafaelsalguero.csharp2ts                |
| txava.region-marker                     | false | 229       | 1             | 1               | onCommand:region-marker.markNamedRegion               | txava.region-marker                     |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615886485134	0	0
code/didStartMain	1615886485228	94	94
code/mainAppReady	1615886485321	93	187
code/willLoadMainBundle	1615886485323	2	189
code/fork/willLoadCode	1615886485341	18	207
code/registerFilesystem/file	1615886485396	55	262
code/didLoadMainBundle	1615886485397	1	263
code/willOpenNewWindow	1615886485488	91	354
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615886485490	0	0
code/didStartRenderer	1615886486441	951	951
code/willShowPartsSplash	1615886486441	0	951
code/didShowPartsSplash	1615886486444	3	954
code/willLoadWorkbenchMain	1615886486450	6	960
code/willWaitForShellEnv	1615886486741	291	1251
code/didWaitForShellEnv	1615886486741	0	1251
code/didLoadWorkbenchMain	1615886486741	0	1251
code/registerFilesystem/file	1615886486742	1	1252
code/registerFilesystem/vscode-userdata	1615886486742	0	1252
code/willInitWorkspaceService	1615886486743	1	1253
code/willInitWorkspaceStorage	1615886486751	8	1261
code/didInitWorkspaceStorage	1615886486775	24	1285
code/didInitWorkspaceService	1615886486788	13	1298
code/willStartWorkbench	1615886486788	0	1298
code/LifecyclePhase/Ready	1615886486789	1	1299
code/registerFilesystem/trustedDomains	1615886486836	47	1346
code/willRestoreEditors	1615886486942	106	1452
code/willRestoreViewlet	1615886486944	2	1454
code/didRestoreViewlet	1615886486957	13	1467
code/willResolveExplorer	1615886486973	16	1483
code/willLoadExtensions	1615886487018	45	1528
code/didRestoreEditors	1615886487391	373	1901
code/LifecyclePhase/Restored	1615886487392	1	1902
code/didStartWorkbench	1615886487392	0	1902
code/didRemovePartsSplash	1615886487392	0	1902
code/willConnectSharedProcess	1615886487403	11	1913
code/didResolveExplorer	1615886487552	149	2062
code/willHandleExtensionPoints	1615886487629	77	2139
code/didHandleExtensionPoints	1615886487750	121	2260
code/didLoadExtensions	1615886487758	8	2268
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615886487049	0	0
code/fork/start	1615886487151	102	102
code/fork/willLoadCode	1615886487174	23	125
code/extHost/willConnectToRenderer	1615886487366	192	317
code/extHost/didConnectToRenderer	1615886487368	2	319
code/extHost/didWaitForInitData	1615886487918	550	869
code/extHost/didCreateServices	1615886487939	21	890
code/extHost/willWaitForConfig	1615886487945	6	896
code/extHost/didWaitForConfig	1615886488059	114	1010
code/extHost/didInitAPI	1615886488059	0	1010
code/extHost/didInitProxyResolver	1615886488064	5	1015
code/extHost/ready	1615886488064	0	1015
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1615886488076	12	1027
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1615886488091	15	1042
code/extHost/willLoadExtensionCode/vscode.emmet	1615886488091	0	1042
code/extHost/didLoadExtensionCode/vscode.emmet	1615886488104	13	1055
code/extHost/willLoadExtensionCode/vscode.html-language-features	1615886488105	1	1056
code/extHost/didLoadExtensionCode/vscode.html-language-features	1615886488121	16	1072
code/extHost/willLoadExtensionCode/Angular.ng-template	1615886488122	1	1073
code/extHost/didLoadExtensionCode/Angular.ng-template	1615886488424	302	1375
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1615886488424	0	1375
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1615886488429	5	1380
code/extHost/willLoadExtensionCode/vscode.git	1615886488429	0	1380
code/extHost/didLoadExtensionCode/vscode.git	1615886488451	22	1402
code/extHost/willLoadExtensionCode/PKief.material-icon-theme	1615886488452	1	1403
code/extHost/didLoadExtensionCode/PKief.material-icon-theme	1615886488459	7	1410
code/extHost/willActivateExtension/vscode.microsoft-authentication	1615886488568	109	1519
code/extHost/willActivateExtension/vscode.emmet	1615886488572	4	1523
code/extHost/willActivateExtension/vscode.html-language-features	1615886488574	2	1525
code/extHost/willActivateExtension/Angular.ng-template	1615886488585	11	1536
code/extHost/willActivateExtension/vscode.debug-auto-launch	1615886488588	3	1539
code/extHost/willActivateExtension/vscode.git	1615886488588	0	1539
code/extHost/willActivateExtension/PKief.material-icon-theme	1615886488593	5	1544
code/extHost/didActivateExtension/vscode.emmet	1615886488594	1	1545
code/extHost/didActivateExtension/vscode.html-language-features	1615886488594	0	1545
code/extHost/didActivateExtension/Angular.ng-template	1615886488594	0	1545
code/extHost/didActivateExtension/vscode.debug-auto-launch	1615886488594	0	1545
code/extHost/didActivateExtension/PKief.material-icon-theme	1615886488600	6	1551
code/extHost/didActivateExtension/vscode.git	1615886488676	76	1627
code/extHost/didActivateExtension/vscode.microsoft-authentication	1615886488739	63	1690
code/extHost/willLoadExtensionCode/vscode.github	1615886488768	29	1719
code/extHost/didLoadExtensionCode/vscode.github	1615886488774	6	1725
code/extHost/willLoadExtensionCode/ms-vscode.js-debug	1615886488776	2	1727
code/extHost/didLoadExtensionCode/ms-vscode.js-debug	1615886488877	101	1828
code/extHost/willActivateExtension/vscode.github	1615886488895	18	1846
code/extHost/willActivateExtension/ms-vscode.js-debug	1615886488895	0	1846
code/extHost/didActivateExtension/vscode.github	1615886488903	8	1854
code/extHost/didActivateExtension/ms-vscode.js-debug	1615886488903	0	1854
```

## Node Cached Data Stats


### cached data used

* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\BufferUtil-3c281630fc6a83f45532cb4b14775928.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\Constants-6151cbd0f34a4712d4c030ac0a3d6731.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\ErrorCodes-c18463f12c33f2b1984cbd1989c257d6.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\EventTarget-746c810c065e2fb1c60baea93cb730d5.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\Extensions-9ec484f973dd4e18b45a0f06a224a8a1.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\PerMessageDeflate-d8aad809a354fc0fad0155c40a743e4d.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\Receiver-5de915dc0a4d7e456df2e36563c93e46.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\Sender-d61ac8a292570ada1b75e2d039bc38af.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\Validation-f2db962ba8253427c12111ad45d7504f.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\WebSocket-e695484cfb743934a2a64e51fa3fa401.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\WebSocketServer-8ad3ff98db9cf213454a3d00385e3ef1.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\api-841e948090e4ca7206df43cbc6c9cd16.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\chrome-d0b8d2d0b6404d500d037bc6b0a87e49.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\clone-80620580ffde5f334776b866df936a48.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\defaults-12c72aa69f2b0c7ed2d25204d5fe1d6f.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\devtools-417e16bf90c2bc764e754c7efee950e3.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\external-request-ab10458b784f80cecbbd10c487085295.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\graceful-fs-82a6ea8d4163c83d9aabc30972a51adb.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-0239c4185ed101070cc608d8f9d812ae.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-396f1b9a1885ce6996044ff8a0af8a91.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-c57a8efe1d99d34f7b543e6ee851e166.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-ce55b4cfe8f738daf1f523b73c0b61b5.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-e73557111ea260a34478210c3e8f0dc8.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\index-ecd404cc7f7e73ca850930df79835ead.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\legacy-streams-fbbf4a8fad87ef474daca7f0ffd192ce.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\main-49833a29b0a8fb679437ed42258acee7.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\main-faa56fcde87a5a6ef73e13dcae34fbff.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\polyfills-8a6085ce3354b74920d4fba4834610a8.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\sqlite3-35c089784d51703f3d6f9e859425ef89.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\tas-client-umd-c40ab326d37a8fcc2cfdbc57ef6bf4bc.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\workbench.desktop.main-21b08531ba1c5e5c582ef5f6d4a0378b.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\workbench.desktop.main.nls-792a82b83b518c54b223f21409829d2d.code

### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)

**Comment by jrieken** [comment]
Alright, there we go. It looks like opening the renderer window is very slow and also launching the extension host process is too slow. This can be caused by AV software, so please make sure you have the latest version of that or try with AV disabled


<img width="525" alt="Screenshot 2021-03-16 at 14 58 58" src="https://user-images.githubusercontent.com/1794099/111321459-3ba01600-8668-11eb-8a50-e51155756639.png">

**Comment by msalmankarim** [comment]
I am using default AV of windows i.e. Windows Defender and updated my windows last week. I am using vscode for last 3 years on the same machine and didn't had any performance issues. Why all of sudden AV is effecting the performance of vscode?

**Comment by pattarika** [comment]
What does AV stand for?  My vscode is slower too.  But I have something strange going on in my source control where the repository is showing empty infinitely.   I uninstall all related git extension (only git history and gitlen) but the issue didn't go away..  Could you please point me where I can report this? 
![image](https://user-images.githubusercontent.com/41967412/111323737-26ab8e80-8638-11eb-8c6e-3de749f58762.png)

**Comment by jrieken** [comment]
> Why all of sudden AV is effecting the performance of vscode?

First, it must not be AV but we have seen this in past and, second, your AV constantly updates and sometimes the signatures falsy blame valid apps

**Comment by msalmankarim** [comment]
> > Why all of sudden AV is effecting the performance of vscode?
> 
> First, it must not be AV but we have seen this in past and, second, your AV constantly updates and sometimes the signatures falsy blame valid apps

I think this is not a solution to deactivate the AV on laptop and expose it for external threats.

**Comment by deepak1556** [comment]
There are two issues reported here,

1) Startup is slow
2) Memory usage is high

For 1) as @jrieken mentioned, you don't have to disable AV but just ignore vscode and its installation path from the AV, please provide the output of https://github.com/microsoft/vscode/issues/119055#issuecomment-800261753 once you do that. We can debug 2) once the startup issue is narrowed down.

**Comment by msalmankarim** [comment]
Here is the performance readings after adding vscode in AV eclusions.

## System Info

* Code: 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8)
* OS: win32(10.0.19042)
* CPUs: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz(12 x 2904)
* Memory(System): 31.74 GB(10.49GB free)
* Memory(Process): 205.11 MB working set(181.23MB private, 0.22MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------ |
| start => app.isReady                                            | 279      | [main]                    | initial startup: true                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                      |
| require(main.bundle.js)                                         | 168      | [main]                    | initial startup: true                      |
| app.isReady => window.loadUrl()                                 | 412      | [main]                    | initial startup: true                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 1108     | [main->renderer]          | NewWindow                                  |
| require(workbench.desktop.main.js)                              | 627      | [renderer]                | cached data: YES, node_modules took 0ms    |
| wait for shell environment                                      | 1        | [renderer]                | -                                          |
| init storage (global & workspace)                               | 0        | [renderer]                | -                                          |
| require & init workspace storage                                | 49       | [renderer]                | -                                          |
| init workspace service                                          | 98       | [renderer]                | -                                          |
| register extensions & spawn extension host                      | 3979     | [renderer]                | -                                          |
| restore viewlet                                                 | 23       | [renderer]                | workbench.view.explorer                    |
| restore panel                                                   | 0        | [renderer]                | -                                          |
| restore editors                                                 | 1381     | [renderer]                | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 1866     | [renderer]                | -                                          |
| workbench ready                                                 | 4397     | [main->renderer]          | -                                          |
| renderer ready                                                  | 2613     | [renderer]                | -                                          |
| shared process connection ready                                 | 1785     | [renderer->sharedprocess] | -                                          |
| extensions registered                                           | 7312     | [renderer]                | -                                          |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 7         | 0             | 11              | *                                                     | vscode.debug-auto-launch                |
| vscode.git                              | true  | 24        | 6             | 106             | *                                                     | vscode.github                           |
| vscode.github                           | true  | 26        | 1             | 0               | *                                                     | vscode.github                           |
| alexiv.vscode-angular2-files            | true  | 567       | 3             | 2               | *                                                     | alexiv.vscode-angular2-files            |
| PKief.material-icon-theme               | true  | 80        | 0             | 25              | *                                                     | PKief.material-icon-theme               |
| vscode.emmet                            | false | 25        | 19            | 209             | onStartupFinished                                     | vscode.emmet                            |
| vscode.extension-editing                | false | 42        | 1             | 61              | onLanguage:typescript                                 | vscode.extension-editing                |
| vscode.github-authentication            | false | 32        | 5             | 56              | onAuthenticationRequest:github                        | vscode.github-authentication            |
| vscode.html-language-features           | false | 38        | 17            | 0               | onLanguage:html                                       | vscode.html-language-features           |
| vscode.markdown-language-features       | false | 42        | 3             | 0               | onLanguage:markdown                                   | vscode.markdown-language-features       |
| vscode.merge-conflict                   | false | 17        | 8             | 201             | onStartupFinished                                     | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 44        | 6             | 4256            | onAuthenticationRequest:microsoft                     | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 27        | 15            | 189             | onStartupFinished                                     | ms-vscode-remote.remote-wsl-recommender |
| ms-vscode.js-debug                      | false | 351       | 29            | 0               | onCommand:extension.js-debug.clearAutoAttachVariables | ms-vscode.js-debug                      |
| vscode.testing-editor-contributions     | false | 10        | 0             | 189             | onStartupFinished                                     | vscode.testing-editor-contributions     |
| vscode.typescript-language-features     | false | 71        | 46            | 17              | onLanguage:typescript                                 | vscode.typescript-language-features     |
| Angular.ng-template                     | false | 9213      | 6             | 11              | onLanguage:typescript                                 | Angular.ng-template                     |
| esbenp.prettier-vscode                  | false | 2225      | 186           | 20              | onStartupFinished                                     | esbenp.prettier-vscode                  |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615966447738	0	0
code/didStartMain	1615966447966	228	228
code/mainAppReady	1615966448245	279	507
code/willLoadMainBundle	1615966448249	4	511
code/fork/willLoadCode	1615966448284	35	546
code/registerFilesystem/file	1615966448415	131	677
code/didLoadMainBundle	1615966448417	2	679
code/willOpenNewWindow	1615966448657	240	919
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615966448663	0	0
code/didStartRenderer	1615966449750	1087	1087
code/willShowPartsSplash	1615966449751	1	1088
code/didShowPartsSplash	1615966449754	3	1091
code/willLoadWorkbenchMain	1615966449765	11	1102
code/willWaitForShellEnv	1615966450391	626	1728
code/didWaitForShellEnv	1615966450392	1	1729
code/didLoadWorkbenchMain	1615966450392	0	1729
code/registerFilesystem/file	1615966450394	2	1731
code/registerFilesystem/vscode-userdata	1615966450394	0	1731
code/willInitWorkspaceService	1615966450397	3	1734
code/willInitWorkspaceStorage	1615966450408	11	1745
code/didInitWorkspaceStorage	1615966450457	49	1794
code/didInitWorkspaceService	1615966450495	38	1832
code/willStartWorkbench	1615966450497	2	1834
code/LifecyclePhase/Ready	1615966450499	2	1836
code/registerFilesystem/trustedDomains	1615966450599	100	1936
code/willRestoreEditors	1615966450981	382	2318
code/willRestoreViewlet	1615966450985	4	2322
code/didRestoreViewlet	1615966451008	23	2345
code/willResolveExplorer	1615966451034	26	2371
code/willLoadExtensions	1615966451299	265	2636
code/didRestoreEditors	1615966452362	1063	3699
code/LifecyclePhase/Restored	1615966452362	0	3699
code/didStartWorkbench	1615966452363	1	3700
code/didRemovePartsSplash	1615966452363	0	3700
code/willConnectSharedProcess	1615966452407	44	3744
code/didResolveExplorer	1615966453321	914	4658
code/didConnectSharedProcess	1615966454192	871	5529
code/willHandleExtensionPoints	1615966454714	522	6051
code/didHandleExtensionPoints	1615966455230	516	6567
code/didLoadExtensions	1615966455278	48	6615
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1615966451364	0	0
code/fork/start	1615966451749	385	385
code/fork/willLoadCode	1615966451847	98	483
code/extHost/willConnectToRenderer	1615966452521	674	1157
code/extHost/didConnectToRenderer	1615966452535	14	1171
code/extHost/didWaitForInitData	1615966455714	3179	4350
code/extHost/didCreateServices	1615966455761	47	4397
code/extHost/willWaitForConfig	1615966455778	17	4414
code/extHost/didWaitForConfig	1615966457011	1233	5647
code/extHost/didInitAPI	1615966457013	2	5649
code/extHost/didInitProxyResolver	1615966457026	13	5662
code/extHost/ready	1615966457027	1	5663
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1615966457081	54	5717
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1615966457124	43	5760
code/extHost/willLoadExtensionCode/vscode.extension-editing	1615966457125	1	5761
code/extHost/didLoadExtensionCode/vscode.extension-editing	1615966457167	42	5803
code/extHost/willLoadExtensionCode/vscode.typescript-language-features	1615966457168	1	5804
code/extHost/didLoadExtensionCode/vscode.typescript-language-features	1615966457239	71	5875
code/extHost/willLoadExtensionCode/Angular.ng-template	1615966457240	1	5876
code/extHost/didLoadExtensionCode/Angular.ng-template	1615966466453	9213	15089
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1615966466454	1	15090
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1615966466461	7	15097
code/extHost/willLoadExtensionCode/vscode.git	1615966466461	0	15097
code/extHost/didLoadExtensionCode/vscode.git	1615966466485	24	15121
code/extHost/willLoadExtensionCode/alexiv.vscode-angular2-files	1615966466485	0	15121
code/extHost/didLoadExtensionCode/alexiv.vscode-angular2-files	1615966467052	567	15688
code/extHost/willLoadExtensionCode/PKief.material-icon-theme	1615966467052	0	15688
code/extHost/didLoadExtensionCode/PKief.material-icon-theme	1615966467132	80	15768
```

## Node Cached Data Stats


### cached data used

* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\clone-80620580ffde5f334776b866df936a48.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\graceful-fs-82a6ea8d4163c83d9aabc30972a51adb.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\legacy-streams-fbbf4a8fad87ef474daca7f0ffd192ce.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\main-49833a29b0a8fb679437ed42258acee7.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\main-faa56fcde87a5a6ef73e13dcae34fbff.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\polyfills-8a6085ce3354b74920d4fba4834610a8.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\sqlite3-35c089784d51703f3d6f9e859425ef89.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\tas-client-umd-c40ab326d37a8fcc2cfdbc57ef6bf4bc.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\workbench.desktop.main-21b08531ba1c5e5c582ef5f6d4a0378b.code
* C:\Users\Salman Karim\AppData\Roaming\Code\CachedData\2b9aebd5354a3629c3aba0a5f5df49f43d6689f8\workbench.desktop.main.nls-792a82b83b518c54b223f21409829d2d.code

### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)

**Comment by msalmankarim** [comment]
![image](https://user-images.githubusercontent.com/11595290/111431327-f1687480-86fb-11eb-89b5-82777f3fed6d.png)

**Comment by angusgraham** [comment]
I'd like to add a little "me too" here.
Even though this is a Visual Studio shop I've been using VSCode as my default file viewer in Perforce instead of notepad because it only took one or two seconds to open a file which is something I can live with.
.. but a few days ago it changed to taking around five or six seconds to open a file which just aint it.
Let me know if you want another capture of that stuff as mentioned above to get another data point and I'll jump on it.

**Comment by msalmankarim** [comment]
@deepak1556 Any update?

![VS Code memory consumption](https://user-images.githubusercontent.com/11595290/112139597-3fd1b380-8bd3-11eb-8b49-baaab561b698.PNG)

**Comment by deepak1556** [comment]
Sorry I am slow to respond before testing week. Thanks for eliminating the idea that might AV have caused the slow startup. Based on the last comment, you are also reporting high CPU usage and not just slow startup. Lets first tackle the cpu issue, can you provide the output of following replacing the PID of the processes that showed the high cpu usage

```
Get-WmiObject win32_process -Filter ProcessId=<PID> | Select-Object CommandLine
```
