### ISSUE TITLE
Chocolatey vscode.portable package is not updated since 1.53.2

### ISSUE THREAD

**Issue by comodoro** [microsoft/vscode#119085]
Issue Type: <b>Bug</b>

Last approved Chocolatey package is 1.53.2. Two newer versions are "waiting for maintainer":

https://chocolatey.org/packages/vscode.portable#versionhistory

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.2.1
python|ms-|2021.2.633441544
jupyter|ms-|2021.2.603412351
remote-wsl|ms-|0.53.4
cpptools|ms-|1.2.2
rust|rus|0.7.8
tabnine-vscode|Tab|3.2.8

</details>

**Comment by joaomoreno** [comment]
As it says on that page:

> Welcome to the Chocolatey Community Package Repository! The packages found in this section of the site are provided, maintained, and moderated by the community.

We do not publish this package.

**Comment by comodoro** [comment]
Sorry, my bad. Seems to be resolved by now anyway.

čt 18. 3. 2021 v 20:14 odesílatel João Moreno ***@***.***>
napsal:
