### ISSUE TITLE
Vue.js intellisense, code completion, suggestions crashing with some files

### ISSUE THREAD

**Issue by mirozahorak** [microsoft/vscode#119056]
On M1 mac in VUE project, after a moments use of code completion it stops working. It behaves strange, seems like it depends on position in the file. When testing at the begining of the file, it works, but when i move deeper in the code, it doesn't and stops working completely.

Tried last 3 versions of VSC, it is the same. Installed just a few basic vue and vuetify extensions.

**Comment by dbaeumer** [comment]
You can try to use the new extension bisect tool https://code.visualstudio.com/blogs/2021/02/16/extension-bisect to find which extension is causing the issue. When detected please file the issue against the corresponding extension.

**Comment by mirozahorak** [comment]
i have run bisect and this is the result> mdi-vuetify-intellisense is causing the problem
i have submited the issue to project.
thanks for help
