### ISSUE TITLE
Setup different color themes across multiple windows

### ISSUE THREAD

**Issue by nikhilnxvverma1** [microsoft/vscode#119079]
There are times when I would have 2-3 VSCode windows open at the same time(for different projects etc). Currently, if I change the color theme in 1 window, it universally changes it across all opened windows. I would prefer if I could setup different color themes for each. That way, context switching becomes much easier aesthetically speaking.
Thanks for all the great work.

**Comment by gjsjohnmurray** [comment]
You can already do this by setting a theme per workspace:

![image](https://user-images.githubusercontent.com/6726799/111309975-68e2c900-8654-11eb-924d-23ada4623851.png)

/question
