### ISSUE TITLE
Notebook flicker

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119093]
* todays insider
* open GH issue notebook
* while opening there is flicker and split-second screen cheese

<img width="674" alt="Screenshot 2021-03-16 at 16 28 10" src="https://user-images.githubusercontent.com/1794099/111335574-c7b83a80-8674-11eb-9864-26154d02c164.png">

https://user-images.githubusercontent.com/1794099/111335563-c4bd4a00-8674-11eb-9d4f-00ee51bc5cc6.mov

**Comment by rebornix** [comment]
This is the side effect of the custom markdown renderer. I wonder when we warm up, whether we should render outputs as well.

**Comment by rebornix** [comment]
This one is the same as https://github.com/microsoft/vscode/issues/119582 .
