### ISSUE TITLE
Behave the same for some functionalities (like lint, file change watch etc)  in "logically the same paths".

### ISSUE THREAD

**Issue by BIAOXYZ** [microsoft/vscode#119080]
The concrete scenario I met is described below: 

1. My dev machine is a VM and the following two paths are in essence the same:
  - `/data00/home/biaoxyz/gitrepos/my_proj_root` (call it `path1` later) = `/home/biaoxyz/gitrepos/my_proj_root` (call it `path2` later)
2. I do not know the concrete mount conditions, but the block devices I can see is:
  ```sh
  $ lsblk -a
  NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  sda      8:0    0  120G  0 disk
  └─sda1   8:1    0  120G  0 part /
  sdb      8:16   0  500G  0 disk /data00
  sr0     11:0    1  478K  0 rom
  ```
However, I am sure that `path1` and `path2` are the same.
3. Then I use vscode's remote access to connect to the VM. After successfully establish the connection, two phenomena will appear:
- 3.1 If in the open workspace step, I choose `path1`, then functionalities like `lint`, `file change watch` can work.
- 3.2 But if in the open workspace step, I choose `path2`, then these functionalities cannot work.

At last, I am not sure if it is more like a bug rather than a feature...

**Comment by roblourens** [comment]
Do you see any errors? What happens when you try to use an extension or whatever to lint?

**Comment by BIAOXYZ** [comment]
> Do you see any errors? What happens when you try to use an extension or whatever to lint?

No, did not see any error message. Since it's a remote development machine, the extensions I use are very few: `C/C++`, `C/C++ Advanced Lint`, `Go`, `Diff`.

**Comment by roblourens** [comment]
So when you run the Lint command, nothing happens? And can you expand on the issue with file watching?

Do you see any errors in the devtools console? (Help > Toggle Developer Tools > Console)

**Comment by BIAOXYZ** [comment]
There is warning in vscode `PROBLEMS`, I copy it here:
```json
{
	"resource": "/data00/home/biaoxyz/gitlabrepo-vm1/psi_server/.vscode/c_cpp_properties.json",
	"owner": "/data00/home/biaoxyz/gitlabrepo-vm1/psi_server",
	"severity": 4,
	"message": "Cannot find \"/data00/data00/home/biaoxyz/gitlabrepo-vm1/psi_server/build64_release/compile_commands.json\".",
	"startLineNumber": 13,
	"startColumn": 32,
	"endLineNumber": 13,
	"endColumn": 97
}
```

For `Help > Toggle Developer Tools > Console`, I saw this:

> workbench.desktop.main.js:sourcemap:310 [Extension Host] (node:3296420) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by roblourens** [comment]
So when you run the Lint command, nothing happens? And can you expand on the issue with file watching?

**Comment by BIAOXYZ** [comment]
> So when you run the Lint command, nothing happens? And can you expand on the issue with file watching?

Sorry, I've never manually run Lint cmd. What cmd should I run in (vscode terminal)?

For the file watching part, see the picture bellow:

After a commit, the git working space is clean. Then I add one line of code `int a;`, vscode successfully track this change and use Green vertical line to display it. However, this only happens when I remotely open `/data00/home/biaoxyz/gitrepos/my_proj_root`, if I choose to open `/home/biaoxyz/gitrepos/my_proj_root` (even if they are actually the same), vscode will not use the Green vertical line to display the code change.

![image](https://user-images.githubusercontent.com/6740021/111768390-d73cbb00-88e2-11eb-9857-bf3eed4253c0.png)

**Comment by roblourens** [comment]
That's ok - I guess you mean that underlines don't show up automatically. I wonder whether we can get any useful logs git, can you go to the Output tab, pick Git from the dropdown, share that log?
