### ISSUE TITLE
Arrow keys randomly stop working

### ISSUE THREAD

**Issue by TravisLlado** [microsoft/vscode#119099]
Issue Type: <b>Bug</b>

Frequently, probably every 10-20 hours of use, VSCode randomly stops responding to the right & down arrow keys. Up & left keep working normally. No alternate function replaces the normal navigation function; VSCode just doesn't respond to those keys at all. I can switch to other windows for other applications and the arrow keys work normally there, and then I switch back to VSCode and the arrow keys still don't work there. I can open and close different files within VSCode, and VSCode still does not respond to those keys. I have to close and restart VSCode in order to restore arrow key functionality.

VS Code version: Code - Insiders 1.55.0-insider (892a1083cb2b9b3987ff7edc85376b5d9764433d, 2021-03-16T05:11:50.271Z)
OS version: Darwin x64 20.3.0
Remote OS version: Linux x64 4.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.01GB free)|
|Process Argv|--crash-reporter-id 59b5e7e7-e7ff-454f-9611-dce47e33f26c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.67.10.21|
|OS|Linux x64 4.4.0-31-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 1393)|
|Memory (System)|62.85GB (18.73GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
vscode-bazel|Baz|0.4.0
gitlens|eam|11.3.0
dbc|lha|1.2.3
python|ms-|2021.4.643775328-dev
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.4.641214696
cpptools|ms-|1.2.2
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265947
vsc_aa:30263845
vspre833cf:30267465
vsfjg287:30275553

```

</details>

**Comment by alexdima** [comment]
If you are able to enter this state again, please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`<arrow_down>`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
