### ISSUE TITLE
`git.autofetch` not editable in settings UI

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119032]
It seems to only have three potential states: `false`, `true`, `"all"`. Ideally this would be an enum string so theres a dropdown in the UI, rather than kicking folks over to settings.json.

**Comment by eamodio** [comment]
Unfortunately, that would be a breaking change. I think maybe the settings editor should handle the mix of bool and enums. 

/cc @roblourens

**Comment by JacksonKearl** [comment]
the code can still map `true`/`false` to some internal representation, the registry specifying it as an enum shouldn't break existing values. @roblourens not sure what the expectation is if the setting's value does not match it's declared schema

**Comment by roblourens** [comment]
We do handle this for some other settings... have to check how that setting is registered

**Comment by roblourens** [comment]
This works

```json
"myproperty.foo": {
	"type": ["string", "boolean"],
	"enum": [true, false, "hello"]
}
```

![image](https://user-images.githubusercontent.com/323878/114763641-e19e7900-9d17-11eb-933f-b1f41a52c86b.png)
