### ISSUE TITLE
Feature Request: Drag item to terminal to paste path

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11907]
iTerm:

![drag-to-terminal](https://cloud.githubusercontent.com/assets/4033249/18450268/284e8656-78e7-11e6-8ebd-05f7d1efbe0b.gif)

Would be great if I can 
- Drag File Explorer items to Integrated Terminal.
- Drag any file/folder into Integrated Terminal.

**Comment by Tyriar** [comment]
`gnome-terminal` adds single quotes around files dragged in.

**Comment by jportela** [comment]
I'd like to work on this feature, as my first contribution to this project. @Tyriar can I get this assigned to me so I can get started?

**Comment by Tyriar** [comment]
@jportela we can't assign issues outside the organization unfortunately, that would be great though. A comment is enough :smiley: 

I haven't dealt with drag and drop much but once you get the text, you'll want to call `TerminalInstance.sendText(<text>, false)` to send the text to the shell process.

**Comment by Tyriar** [comment]
Fixed in https://github.com/Microsoft/vscode/pull/24951
