### ISSUE TITLE
Join Cells with multiple selections

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#119004]
Now that multi-select lands in notebook core, we want to support Join Cells (merging selected cells). A few open questions for implementation:

* Should we allow cells of different kinds/languages be merged?
* Should cells from two distinct selections be merged into one cell or separate cells (one cell per selection)

## Run action on all selected cells

The simplest solution is merging all selected cells into one. It's intuitive as all cells in the selections will be merged, which is never ambiguous. 

## Run action per distinct selection

Imagine we have a notebook with 5 cells 

```
  python_1,
  python_2,
  md_1,
  python_3,
  python_4
```

Python cells 1, 2, 3 and 4 are selected, so we have 2 distinct selections, `{ start: 0, end: 2 }`, `{ start: 3, end: 5 }`. After users run Join Cells:

```
  'python_1
  md_1,
  'python3
```

Each distinct selection shrinks into a single cell.

**Comment by frank-yifei-wang** [comment]
Was searching for a way to quickly merge cells (similarly to "Shift+M" in JupyterLab) and found this open thread. Please consider my suggestions:

- **Should we allow cells of different kinds/languages be merged?**
    - No. Why: the merged cells with mixed languages/Markdown won't be executable/readable
    - Suggestion: Simply abort the operation and prompt the user as this is more often than not an accidental selection

- **Should cells from two distinct selections be merged into one cell or separate cells (one cell per selection)**
    - One cell. So with the given example the end result becomes `python_1` (with content of all 4 `python_x` cells), `md_1`
    - Why: the users need this function to consolidate/refactor code cells. If not consolidated into one cell then it defeats the purpose. If instead the user really just wants to get `python_1`, `md_1`, `python_3`, then he/she can simply merge `python_1` and `python_2` first and then repeat for `python_3` and `python_4`. The process is still efficient with shortcut keys (Shift+Down, Shift+M, ESC, Down, Down, Shift+Down, Shift+M)

**Comment by aymather** [comment]
Would really love to see this feature implemented. Currently I see that you can merge the highlighted cells with `ctrl` + `alt` + `j` but that feature also merges the cell "below" the selected cells. I get the need to have something that "merges cell below" but I mostly just use the feature to "merge only highlighted cells".

Any timeline on this?

**Comment by rebornix** [comment]
@frank-yifei-wang @aymather thank you both for the suggestions. I pushed a new command Join Selected Cells which will be available in Insiders soon.
