### ISSUE TITLE
Vscode is pushing a bunch of <<<<<<< HEAD to my github

### ISSUE THREAD

**Issue by zejunli** [microsoft/vscode#119052]
- VS Code Version: 
- OS Version: Mac Big Sur

Steps to Reproduce:

1. try to get some git pull conflict, then accept all incoming changes or current changes
2. then git add ., git commit -m <msg>, git pull, git push
3. all the files that had conflict will have <<<<<<< HEAD shown on github, while these are resolved locally
4. The file doesn't show <<<<<<< HEAD, but if I run python3 myfile.py, it throws error saying I have <<<<<<< HEAD in my file, resulting SyntaxError, why do I not see this in vscode but it's actually in the file? I tried to reboot vscode, it still has this issue, it says <<<<<<< HEAD is in myfile.py line 10, however in vscode it's not there, why is vscode doing this?

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by eamodio** [comment]
Can you show a video of this happening? You should definitely be able to see any conflict markers in your staged files before committing if they exist.
