### ISSUE TITLE
Windows won't redraw properly after update to 1.54 (linux)

### ISSUE THREAD

**Issue by SophieHerbst** [microsoft/vscode#119098]
VScode version: 1.54
OS: Ubuntu 16.04

Since the latest update, windows won't properly redraw, for instance when minimizing or maximizing. 
The first window works fine as long as I do not maximize it or switch to another window. 
But when I do, black or white squares remain on the screen, or bits of the original display are scattered. 
When I start a second window, it always has the drawing problem, no matter whether opened as minimized or maximized.

I am working on Ubuntu 16.04, Intel HD Graphics 630 (Kaby Lake GT2). 

Any suggestions what I could try?

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/118549

Disable hw acceleration as a workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
