### ISSUE TITLE
Linux Debugging (gdb) - Debug Console should reappear after prelaunch task output

### ISSUE THREAD

**Issue by jacdavis** [Microsoft/vscode#11900]
_From @aaiyer on September 10, 2016 9:46_

My launch.json has a preLaunchTask and the output of this task is shown, if it is successful, this output should be hidden and the Debug Console shown. Right now, the output is shown and you have to go and reopen the Debug Console

_Copied from original issue: Microsoft/vscode-cpptools#220_

**Comment by isidorn** [comment]
This can be configured, an output after a task launch is configured via https://code.visualstudio.com/docs/editor/tasks#_output-window-behavior

Some details about configuring debug console showing https://github.com/Microsoft/vscode/issues/4045
