### ISSUE TITLE
Feature Request: Sort options for folders in side bar.

### ISSUE THREAD

**Issue by rhibner** [microsoft/vscode#119119]
It would be nice to be able to sort folders in the sidebar by name, file type, size, etc., etc.

**Comment by isidorn** [comment]
Try this setting
`"explorer.sortOrder"`

**Comment by rhibner** [comment]
Thanks! That was what I needed!


From: Isidor Nikolic ***@***.***>
Sent: Wednesday, 17 March 2021 0444
To: microsoft/vscode ***@***.***>
Cc: Hibner, Rhian A ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode] Feature Request: Sort options for folders in side bar. (#119119)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Try this setting
"explorer.sortOrder"

-
