### ISSUE TITLE
Typescript| Ref snippet adds unnecessary new line after it

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119147]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:
![12](https://user-images.githubusercontent.com/17777237/111402417-d7b33700-86d3-11eb-83e5-f5203abc34e3.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is consistent with many of the existing snippets, such as the one for `console.log`: https://github.com/microsoft/vscode/blob/6d0798457765a2e24234557ee5738004ca6ce300/extensions/typescript-basics/snippets/typescript.code-snippets#L68

**Comment by pixieaka** [comment]
@mjbvz  But why VS code adds this extra lines in all these snippets ?

**Comment by mjbvz** [comment]
They are complete statements. After completing them, you want to immediately go the next line so you can continue writing code
