### ISSUE TITLE
Snippets of Emmet stopped working

### ISSUE THREAD

**Issue by unbywyd** [microsoft/vscode#119120]
Issue Type: <b>Bug</b>

Snippets of Emmet stopped working with the latest updates!

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (23.36GB free)|
|Process Argv|--crash-reporter-id c6a19d99-7bea-405c-bc99-4477bfbc251c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-JS-CSS-HTML-formatter|lon|0.2.3
web-accessibility|Max|0.2.83
vscode-language-pack-ru|MS-|1.54.2
vetur|oct|0.33.1
wordpress-toolbox|wor|1.3.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vscoresta800:30276761
vspre833cf:30267465
vsfjg287:30275553

```

</details>

<details>
<summary>Settings: </summary>

```
{
    "emmet.extensionsPath": "C:\\emmet",
    "emmet.includeLanguages": {
        "scss": "css",
        "markdown": "html"
    },
    "editor.snippetSuggestions": "top",
    "emmet.showExpandedAbbreviation": "always",
    "emmet.triggerExpansionOnTab": true,
    "emmet.showSuggestionsAsSnippets": true
}
```
</details>

<details>
<summary>C:\\emmet\\snippets.json: </summary>

```JSON
{
  "html": {
    "snippets": {
      "ull": "ul>li[id=${1} class=${2}]*2{ Will work with html, pug, haml and slim }",
      "oll": "<ol><li id=${1} class=${2}> Will only work in html </ol>",
      "ran": "{ Wrap plain text in curly braces }"
    }
  },
  "css": {
    "snippets": {
      "cb": "color: black",
      "bsd": "border: 1px solid ${1:red}",
      "ls": "list-style: ${1}"
    }
  }
}
```
</details>

**Comment by rzhao271** [comment]
Can you give examples of which snippets stopped working, and the languages you're trying those snippets in?
Also, does your `emmet.extensionsPath` variable point to `C:\emmet`?

**Comment by unbywyd** [comment]
> Can you give examples of which snippets stopped working, and the languages you're trying those snippets in?
> Also, does your `emmet.extensionsPath` variable point to `C:\emmet`?

I have indicated all the data, you can open the details list "Settings" or "C: \\emmet\\snippets.json" and see the contents of the files, doesn't work for all languages, the file (snippets.json) is not read, before updates, this worked for me.

**Comment by rzhao271** [comment]
It should be fixed in Insiders, can you check using that version?
See https://github.com/microsoft/vscode/issues/117517

**Comment by unbywyd** [comment]
> It should be fixed in Insiders, can you check using that version?
> See #117517

Issue Type: <b>Bug</b>

I checked the insiders 1.55.0 version, and this doesn't work for me, i checked the source code and found the following:

[util.ts](https://github.com/microsoft/vscode/blob/stable-insiders/extensions/emmet/src/util.ts) line: 56, vscode.workspace.workspaceFolders === undefined 

```JS
if (!vscode.workspace.workspaceFolders || vscode.workspace.workspaceFolders.length === 0) {
	return; //  i get here
}
```

If I remove this if, i will get an error because the absolute path will be processed as relative:

```JS
// dist/node/emmetNodeMain.js
 function Bi(e, t, n, r) {
                console.log(e); // ["C:\em"]
                return ui(this, void 0, void 0, function* () {                    
                    if (!e.length) return Vi(), Promise.resolve();
                    let o,
                        i = !1;
                    for (let s of e) {
                        if ((s && (s = s.trim()), !s)) return Vi(), Promise.resolve();
                        "~" === s[0] ? r && (o = We(r, s.substr(1))) : Be(s) ? (o = _e.file(s)) : n && (o = We(n, s));                        
                        console.log(o); // {$mid: 1, path: "/C:/em", scheme: "file"}

```

VS Code version: Code - Insiders 1.55.0-insider (892a1083cb2b9b3987ff7edc85376b5d9764433d, 2021-03-16T08:28:11.592Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.70GB (20.09GB free)|
|Process Argv|--crash-reporter-id fcea720f-d93c-4745-aa4a-12c8530d255a|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800:30265947
vspre833cf:30267465
vsfjg287:30275553

```

</details>



<details>
<summary>settings.json</summary>

```json
{
    "workbench.colorTheme": "Default Light+",
    "emmet.extensionsPath": ["C:\\em"], 
    "emmet.includeLanguages": {
        "scss": "css",
        "markdown": "html"
    },
    "editor.snippetSuggestions": "top", 
    "emmet.showExpandedAbbreviation": "always",
    "emmet.triggerExpansionOnTab": true,
    "emmet.showSuggestionsAsSnippets": true
}
```
</details>

**Comment by rzhao271** [comment]
Turns out `workspaceFolderPath` isn't even a required parameter for `updateExtensionsPath` https://github.com/microsoft/vscode-emmet-helper/blob/main/src/emmetHelper.ts#L975
Thanks for the details!

**Comment by rzhao271** [comment]
Verification steps:

1. Create two Emmet snippet files in two different directories. Change around the abbreviations in each so that you can tell which file is being used.
2. Close all workspaces.
3. Change `emmet.extensionsPath` to point to one of the directories.
4. Open a new blank HTML file and make sure the snippets work.
5. Close the file, and change `emmet.extensionsPath` to point to the other directory.
6. Open a new blank HTML file and make sure the new snippets work.
