### ISSUE TITLE
Problem While trying to full screen {F11 key} Vscode in Ubuntu 20.04 

### ISSUE THREAD

**Issue by mrrobot1o1** [microsoft/vscode#119137]
- VS Code Version: 1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64

- OS Version: Ubuntu 20.04

Steps to Reproduce:

1.Open The Vscode in Ubuntu 20.04
2.Press F11 Key for Full screen Mode

Does this issue occur when all extensions are disabled?: Yes/No
Yes
![Screenshot from 2021-03-17 04-19-39](https://user-images.githubusercontent.com/66872759/111390257-73df3d00-86d8-11eb-82a3-8c2fb30bab3b.png)

**Comment by isidorn** [comment]
Looks like full screen electron rendering issue, forwarding for now to @bpasero and @deepak1556

**Comment by bpasero** [comment]
We delegate to electron here for fullscreen handling.

**Comment by mrrobot1o1** [comment]
Finally I managed to solve My problem..
## To solve the Problem Just Edit the ~/.vscode/argv.json end Uncomment 
**"disable-hardware-acceleration": true,**

![image](https://user-images.githubusercontent.com/66872759/111790487-41a42a00-88e8-11eb-9d21-d699bf405c14.png)
