### ISSUE TITLE
Spacebar in kakoune breaks the integrated terminal

### ISSUE THREAD

**Issue by JacobTravers** [microsoft/vscode#119134]
Issue Type: <b>Bug</b>

When pressing the spacebar in insert mode in kakoune, the entirety of the integrated terminals contents are shifted and cut off in the container.

I like using kakoune to edit my commit messages so I looked for a solution and set the renderer type to dom which worked fine for a while but has become incredibly slow. I'm not sure if I should also create another bug report for that as well.

VS Code version: Code - Insiders 1.55.0-insider (9b2ee7fb7d970b9a628fdb3545bdd01d67078d16, 2021-03-11T05:13:39.061Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.43GB free)|
|Process Argv|--crash-reporter-id 05c7b98e-6194-4b3c-96c5-318557bf8e75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
insertnumbers|Asu|0.9.1
vscode-fish|bma|1.0.20
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
javascript-ejs-support|Dig|1.3.1
gitlens-insiders|eam|2021.3.1104
vscode-npm-script|eg2|0.3.17
vscode-npm|fkn|3.3.0
dance|gre|0.4.0
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
latex-workshop|Jam|8.16.1
vscode-colorize|kam|0.11.0
theme-monokai-pro-vscode|mon|1.1.18
remote-wsl|ms-|0.54.5
vsliveshare|ms-|1.0.3968
material-icon-theme|PKi|4.5.0
LiveServer|rit|5.6.1
vscode-stylelint|sty|0.86.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.11
vscode-surround|yat|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
vscoresta800cf:30265948
vsc_aa:30263845
vspre833cf:30267465
vsdfh931:30275552

```

</details>

**Comment by Tyriar** [comment]
I can't reproduce:

![recording (1)](https://user-images.githubusercontent.com/2193314/113003812-ef54db80-9127-11eb-8d02-00cff757858c.gif)

I notice you're on Windows, are you building it via cygwin or something? If so does this also happen in Windows Terminal?
