### ISSUE TITLE
Add context keys for cell execution state (to be used in cell toolbars)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119132]
Would it be possible to restore the cell executed context state so we can have cell level toolbars that are visible/enabled based on the cell execution state:
State = Idle, Executing, Success, Failed.

In VSCode Gather extension we use some of these states to enable/disable cell toolbar icons (we do this in the webview version of notebooks).
In Native Notebooks we only had Idle and Executing, from what I understand these contexts were removed in this PR https://github.com/microsoft/vscode/issues/106747

@jrieken @roblourens  /cc

**Comment by roblourens** [comment]
These should only be changed in https://github.com/microsoft/vscode/pull/116416, and I will fix it as part of that.
