### ISSUE TITLE
Documentation issue for update code with dnf

### ISSUE THREAD

**Issue by wes-novack** [microsoft/vscode#119100]
Documentation bug report:

Regarding this page and the Redhat based Linux section in particular: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions

If you already have Code installed, the dnf update command should be:
`sudo dnf update code`

NOT
sudo dnf install code

Please update the docs to address this.

**Comment by Tyriar** [comment]
We don't mention how to update it, only install. I think it's out of scope for us since if you use red hat based linux you should learn how to update your system packages. We don't explain how to update on apt/snap-based either.

**Comment by wes-novack** [comment]
Here's the issue, when you "Check for Updates" and/or get notified that an update is available inside of VS Code, it takes you to the VS Code homepage:  https://code.visualstudio.com

This homepage has a big download rpm button on it. If you click this button, it takes you to the install instructions that I linked above.

So perhaps your install instructions aren't meant to provide guidance on updates, but the VS Code UX/homepage/links are directing folks to this install page for updates.

**Comment by Tyriar** [comment]
The check for updates problem you mention is tracked in https://github.com/microsoft/vscode/issues/43671

But running those instructions registers the repository so it acts like any other software on the system.
