### ISSUE TITLE
notebook smoke test failures

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119164]
see https://dev.azure.com/monacotools/Monaco/_build/results?buildId=109190&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea

**Comment by roblourens** [comment]
Also https://github.com/microsoft/vscode/issues/113882 and https://github.com/microsoft/vscode/issues/119744

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/126371
