### ISSUE TITLE
Editor formatter is `null` by default?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119157]
Opening settings I see `null` as editor formatter?

![image](https://user-images.githubusercontent.com/900690/111422809-9466c180-86ef-11eb-85a1-c6c1f4b21d18.png)

**Comment by jrieken** [comment]
Yeah, that's the default "none" value in JSON. We have the all over settings. Assigning to @aeschli  for better ideas

**Comment by aeschli** [comment]
You can customize the labels shown in the Settings UI dropdown with `enumItemLabels`. See [example](https://github.com/microsoft/vscode-distro/blob/ba61d25cf002e9a939ea098bba278e965df7a6e7/src/vs/workbench/services/themes/common/themeConfiguration.ts#L92).

**Comment by jrieken** [comment]
wow
