### ISSUE TITLE
Please move the debug button bar

### ISSUE THREAD

**Issue by dancancro** [microsoft/vscode#119115]
Issue Type: <b>Feature Request</b>

When debugging, a small, horizontal bar with some buttons appears at the top of the screen. I am able to move it left and right. I would like for it to instead appear vertically and on the left side of the screen in the space with Search, Source Control and Debug buttons. It would be movable vertically and I would put it in the lower part of this strip where there is currently nothing else. 

As it is, I need to keep moving it left and right to expose things. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

**Comment by yume-chan** [comment]
Related: #117326

**Comment by isidorn** [comment]
Closing as dup
Also try this setting	"debug.toolBarLocation": "docked",
