### ISSUE TITLE
Getting started recents should have a max-width/height

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119116]
In codespaces the list gets really long, we should set a max width/height:

![image](https://user-images.githubusercontent.com/35271042/111358850-0c79ac80-8648-11eb-9e81-0f9b2cb239ec.png)

**Comment by JacksonKearl** [comment]
Yeah, going to do what the current welcome page does and just `...` them

**Comment by JacksonKearl** [comment]
`...`ing them in insiders.
