### ISSUE TITLE
Current Branch label at bottom left is showing old branch even if we created and switched to new branch

### ISSUE THREAD

**Issue by rvjalamy** [microsoft/vscode#119156]
- VS Code Version:
-  1.54.3
- 
- OS Version:
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. checkout a remote repo ( git checkout origin/main
2. create a new branch (git checkout -b feat-branch

Does this issue occur when all extensions are disabled?: Yes/No

[](url)

**Comment by lszomoru** [comment]
@rvjalamy, are you able to reproduce this with the latest version of VS Code Insiders?  
If you are, do not mind recording a gif using https://gifcap.dev to illustrate the issue? Thanks!
