### ISSUE TITLE
separator in 'files to exclude' is not obvious, should be communicated to the user

### ISSUE THREAD

**Issue by kg** [microsoft/vscode#119107]
- VS Code Version: 1.54.2
- OS Version: windows 10

Steps to Reproduce:

1. Type ```*.md;*.cs``` into Files To Exclude

Does this issue occur when all extensions are disabled?: 

Was #39549 reverted? It doesn't seem to work anymore.

P.S. there should really be a tooltip or something explaining the required syntax for this field. I shouldn't have to search github issues to understand how to use this feature.

**Comment by gjsjohnmurray** [comment]
#39549 was closed as out-of-scope, so I don't think semicolon has ever worked as a separator there.

**Comment by kg** [comment]
It had a commit at the end in the github UI, which made me think it was fixed. In that case this can be fixed by a tooltip or something.

**Comment by gjsjohnmurray** [comment]
> It had a commit at the end in the github UI, which made me think it was fixed

The PR reference is red, and its icon also denotes that it wasn't merged.

I agree re having a clue in the UI. The Filter field in the Problems panel uses a placeholder hint for this kind of thing.

**Comment by roblourens** [comment]
Would like to add a placeholder, this has come up before.
