### ISSUE TITLE
Couldn't start client Java Language Server

### ISSUE THREAD

**Issue by OOOHA** [microsoft/vscode#119181]
Issue Type: <b>Bug</b>

I always got the "Couldn't start client Java Language Server" on my Windows.
I don't think it's because the extension, after I tried a lot of ways.
I have reported a [#119181 ](https://github.com/georgewfraser/java-language-server/issues/182)
I reinstall the java SDK and reinstall all the java extensions.
I use the [https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack](url).
But this issue is Windows only.
My Macs with sync runs perfect.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.85GB free)|
|Process Argv|--crash-reporter-id 6e0a0302-b09c-4c20-8e81-5fa91decd80f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.0.4
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
vscode-eslint|dba|2.1.19
githistory|don|0.6.16
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
git-project-manager|fel|1.7.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.2
code-runner|for|0.11.3
vscode-javac|geo|0.2.37
vscode-tree-sitter|geo|0.1.26
vscode-pull-request-github|Git|0.24.0
go|gol|0.23.2
go-nightly|gol|2021.3.1218
todo-tree|Gru|0.0.205
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.5
flutter-tree|mar|1.0.0
git-graph|mhu|1.29.0
Angular-BeastCode|Mik|10.0.3
vscode-clang|mit|0.2.3
csharp|ms-|1.23.9
python|ms-|2021.3.658691958
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.5
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.3968
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
java|red|0.76.0
LiveServer|rit|5.6.1
document-tree|sac|1.0.1
sonarlint-vscode|Son|1.20.1
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
windows-terminal|Tyr|0.6.0
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-icons|vsc|11.2.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension I see you have already reported it to the extension author. That's where it needs to be handled.
