### ISSUE TITLE
When I open vscode, it almost always shows files are un-saved, which I know that I saved before closing. Are they saved?

### ISSUE THREAD

**Issue by dannychase2004** [microsoft/vscode#119186]
When I open vscode, it almost always shows files are un-saved, which I know that I saved before closing. Are they saved? I spent some time comparing the files in another editor with what is on disk, and they appear to have saved, but I'm unsure if I were to save, if it will over-write the on-disk version with an incorrect one? What's going on? How would it know/think it's unsaved when I just now opened the editor, and what are the odds if I forget and hit save-all that it'll mess up my work from Friday? It actually happened to me this morning when I opened vscode, which prompted me to post this.

Right now it did re-open editors from yesterday, and it says "1 UNSAVED" with a dot next to the file. If I right-click and hit compare with save, there don't appear to be any differences. 

Also, besides a possible bug, is there a way to disable whatever functionality is getting this wrong?

Adding a screenshot in case it helps.
![Capture3](https://user-images.githubusercontent.com/14045486/111488734-e6b7da80-870f-11eb-998e-6111a5bb757e.png)

Adding a screenshot of extensions currently enabled, I have also tried disabling. 
![image](https://user-images.githubusercontent.com/14045486/111495379-b1ae8680-8715-11eb-9455-e9056e8b0be5.png)

I can make this occur over and over again in it's current state, for this file, just by closing and re-opening vscode, never failing. Where is this state stored? must be going stale?

**Comment by Mlocik97** [comment]
You will propably want to set these settings... italic text in tab show "untouched" files in specific session, not "unsaved" files.

```
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
```

**Comment by dannychase2004** [comment]
> You will propably want to set these settings... italic text in tab show "untouched" files in specific session, not "unsaved" files.
> 
> ```
>     "workbench.editor.enablePreview": false,
>     "workbench.editor.enablePreviewFromQuickOpen": false,
> ```

Here is a screenshot in case it helps, doesn't appear to be italics?
![Capture2](https://user-images.githubusercontent.com/14045486/111486053-8758cb00-870d-11eb-91f2-b4e40bffcc62.PNG)

**Comment by gjsjohnmurray** [comment]
Screenshot implies you have turned tabs off via `"workbench.editor.showTabs": false`, though that shouldn't be a significant factor.

Does the issue happen if you disable all extensions? Maybe one of those is doing some event-triggered formatting?

Please also add your version and platform info from Help\About.

Tip for future reports: use Help\Report Issue to get that info included automatically.

**Comment by dannychase2004** [comment]
> Screenshot implies you have turned tabs off via `"workbench.editor.showTabs": false`, though that shouldn't be a significant factor.
> 
> Does the issue happen if you disable all extensions? Maybe one of those is doing some event-triggered formatting?
> 
> Please also add your version and platform info from Help\About.
> 
> Tip for future reports: use Help\Report Issue to get that info included automatically.

Thanks, I'll try disabling all extensions to see if the issue re-appears. Also, I don't know if it's relevant, but I run the angular tooling, and use git - is there any way that tooling is modifying a file during the close process (like re-save or something) if I forget to stop it first? Or could I be checking something in to git that's saving the "unsaved" status? I've verified .vscode is in gitignore. 

I wonder how it detects, does it take a hash? Maybe it's taking a hash prior to the tooling doing a final save or something? Back to, I wonder how it knows it's modified. 

I'll disable extensions as the next step, but if you or anyone have any information it'll definitely be helpful I'm sure!

**Comment by dannychase2004** [comment]
> > Screenshot implies you have turned tabs off via `"workbench.editor.showTabs": false`, though that shouldn't be a significant factor.
> > Does the issue happen if you disable all extensions? Maybe one of those is doing some event-triggered formatting?
> > Please also add your version and platform info from Help\About.
> > Tip for future reports: use Help\Report Issue to get that info included automatically.
> 
> Thanks, I'll try disabling all extensions to see if the issue re-appears. Also, I don't know if it's relevant, but I run the angular tooling, and use git - is there any way that tooling is modifying a file during the close process (like re-save or something) if I forget to stop it first? Or could I be checking something in to git that's saving the "unsaved" status? I've verified .vscode is in gitignore.
> 
> I wonder how it detects, does it take a hash? Maybe it's taking a hash prior to the tooling doing a final save or something? Back to, I wonder how it knows it's modified.
> 
> I'll disable extensions as the next step, but if you or anyone have any information it'll definitely be helpful I'm sure!

Ok I have disabled extensions, and can reproduce this by just closing vscode and re-opening over and over, still says modified, never failing! Granted, I have not tried editing, saving or anything, trying to keep it in it's current state to troubleshoot.

To clarify, shows modified even though I didn't modify it, close vscode, re-open, still shows modified. Same after disabling extensions.


Where is the save state stored? It must be stale?

**Comment by dannychase2004** [comment]
Cloned the repo looking for the code, if anyone has any pointers of where to find this let me know.. also looking, not just expecting any else to find it :) I'm sure if I can see where it's stored, I can confirm quickly.

**Comment by bpasero** [comment]
I would need steps to reproduce at least. Does it reproduce in insiders?

**Comment by dannychase2004** [comment]
Ok figured it out, if it loads from "backup" it sets dirty = true regardless. It looks like from that point, you can close/reopen all you want and until you close it or save it, will remain dirty regardless of what's on the disk.

I reproduced by opening a file, typing a space, and killing the code process. Going back in and it's dirty. From that point I can close/reopen and it will remain dirty.

In my situation, I'm guessing I shut down, or there was an unclean shutdown that caused vscode to read a backed-up copy when it loaded.

Anyone know how to disable the backup?

**Comment by bpasero** [comment]
@dannychase2004 yeah via setting: `files.hotExit: "off"`. Note that you will see data loss though in case there are unsaved changes and VSCode crashes.

**Comment by dannychase2004** [comment]
@bpasero Thanks, yes, and confirmed, once the file is pulled from backup, the disk version is ignored. I closed vscode so that it could not detect any changes, added "This is a test" to the file in question, and re-opened vs code, it indeed took from backup and my new changes were not in the editor, and it said unsaved. So in that case, if I save I would "ruin" the file.

I'll let you guys decide if this is a bug, complicated corner-case, or expected, because I don't know the ins and outs of the real use case :)

**Comment by dannychase2004** [comment]
You guys rock, when I tried to save it warned me the file was different. Great job to the team who did this!!!
