### ISSUE TITLE
Notebook errors from renamed file persist

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119191]
![image](https://user-images.githubusercontent.com/35271042/111506589-01d21c80-8707-11eb-81c6-77149aaf75dd.png)

1. Create a notebook with syntax errors, execute cells
2. Rename notebook
3. :bug: Errors show up for that previous file

You can see in the example above, I renamed `peng.ipynb` => `setup.ipynb` but somehow errors persist for `peng.ipynb` and clicking on it brings up the file that no longer exists.

**Comment by jrieken** [comment]
When logging how documents are closed and opened (see snippet below) I see that the extension emits _close_ events for the cells of the before (old) name and it emits _open_ events for the cells of the after (new) name. The trace below is from me rename `oneCell.github-issues` to `threeCell.github-issues`

<img width="635" alt="Screenshot 2021-03-18 at 09 14 44" src="https://user-images.githubusercontent.com/1794099/111593608-67d3a800-87ca-11eb-9768-551358052102.png">


```ts
vscode.workspace.onDidCloseTextDocument(e => { console.log('CLOSED: ' + e.uri.toString()) })
vscode.workspace.onDidOpenTextDocument(e => { console.log('OPEN: ' + e.uri.toString()) })
```
