### ISSUE TITLE
Changes does not occur while editing for html and css codes

### ISSUE THREAD

**Issue by Shubham-808** [microsoft/vscode#119180]
Changes does not occur while editing for html and css codes. No matter how many times i do the changes and try to refresh the page but changes are not showing in vscode. when i copy paste the same file to other location then the changes are shown

**Comment by aeschli** [comment]
Did you save after the changes after editing? There's the auto save setting that is helpful, if you don't want to do that yourself: `files.autoSave`

**Comment by Shubham-808** [comment]
Yes of course sir. I have saved it many times. I am using scss to create
css and in php file, but changes do not show when I refresh. But when I
copy the complete file to a different folder and I also don't change
anything in it, but when I run the file the changes show there completely.
It is very annoying. Could you please help me with this issue?
Thanks and Regards
Shubham Kumar

**Comment by aeschli** [comment]
Can you explain where do you expect the changes to show up? Maybe can you take a screenshot?

**Comment by Shubham-808** [comment]
Sir please have a look.
In screenshot 36
i have marked the line that states i have linked the correct css file.

in screenshot 37
the html code is marked on which i want to apply the change.

in screenshot 38
i have marked the scss that i want to perform.

in screenshot 40
i want to change the color of the icon but it does not change

in screenshot 41
see there is no change in the color

And now when I copy these files to a new location the changes appear.
This is the problem I was talking about.
Please resolve this issue as soon as possible.
thanks and regards
Shubham Kumar

**Comment by Shubham-808** [comment]
I have attached the screenshots in my previous reply. Please check those.

**Comment by aeschli** [comment]
@Shubham-808 Sorry, that didn't work. Adding images by mail attachments might not work.
I always do it in the browser: https://github.com/microsoft/vscode/issues/119180
