### ISSUE TITLE
"Focus Next Search Result" just stays on the same result

### ISSUE THREAD

**Issue by coffenbacher** [microsoft/vscode#119199]
- VS Code Version: 1.55.0-insider
- OS Version: Linux x64 5.8.0-43-generic snap

Steps to Reproduce:

1. Search for a string in project with multiple results
2. Command Palette > "Focus Next Search Result"
3. instead of focusing the next result, it highlights the search box

OR

1. Search for a string in project with multiple results
2. Use keyboard shortcut for "Focus Next Search Result"
3. Goes to first result only
4. Use keyboard shortcut for "Focus Previous Search Result"
5. Goes to last result only

I have used these keyboard shortcuts for a long time, so I feel like this is a recent change in behavior. I noticed it a few days ago, not sure how long it has been like this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by coffenbacher** [comment]
I don't think either of those is a duplicate, but thanks for checking @vscodebot.

**Comment by roblourens** [comment]
Thanks - we are fixing this in https://github.com/microsoft/vscode/issues/118045
