### ISSUE TITLE
Preserve case find replace appears broken

### ISSUE THREAD

**Issue by floreseken** [microsoft/vscode#119123]
- VS Code Version: 1.54.3
- OS Version: Windows 10 20H2

Steps to Reproduce:

1. Make a file with the same words with different casing
2. Do a find replace with preserve casing switched on
3. Watch the preview does not work properly (and the replace also doesn't)
4. Toggling preserve casing does not do anything

![image](https://user-images.githubusercontent.com/6927344/111368905-b718bc00-8696-11eb-901e-c05a743782f0.png)

I'm pretty sure this worked as expected before..

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
The feature came via #60311

**Comment by roblourens** [comment]
This case is not handled. When the match is mixed-case and starts with a lowercase character, I think the replace pattern should have its first character lowercased. Would take a PR that adds this.
