### ISSUE TITLE
Missing setting

### ISSUE THREAD

**Issue by scotch83** [microsoft/vscode#119175]
Issue Type: <b>Bug</b>

After update I cannot seem to find the organize import command anymore.
Also it looks like extensions are becoming a bit of a jungle where we install a lot of stuff, making this IDE just heavier and not behaving uniformly throughout the different used languages and frameworks.

It is great to have open source extensions, but I believe they should reflect some standards and be better controlled by vscode team.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id ecfb4639-3893-4598-9636-57e49a2c5fbb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
cucumberautocomplete|ale|2.15.1
ng-template|Ang|11.2.8
atlascode|atl|2.8.5
cake-vscode|cak|1.0.0
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.17
vs-code-xml-format|fab|0.1.5
shell-format|fox|7.0.1
aio-docs-utils|gka|0.2.1
gc-excelviewer|Gra|3.0.41
node-module-intellisense|lei|1.5.0
render-crlf|med|1.5.17
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
material-icon-theme|PKi|4.5.0
java|red|0.76.0
vscode-yaml|red|0.16.0
bash-debug|rog|0.3.9
comment-ts|sal|1.0.21
yo|sam|0.9.3
vscode-javascript-booster|sbu|14.0.1
slim|sia|0.1.2
vscode-scss-formatter|sib|2.1.0
simontest|Sim|1.9.9
sass-indented|syl|1.8.16
markdown-jira-preview|tra|0.0.1
lorem-ipsum|Tyr|1.2.0
highlight-matching-tag|vin|0.10.0
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
change-case|wma|1.0.0
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
propertylist|zho|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

**Comment by scotch83** [comment]
Typescript

Mattia Collalti

**Comment by mjbvz** [comment]
Organize imports works fine for me

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
