### ISSUE TITLE
Latex in notebook markdown not rendering correctly

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119195]
### Snippet
```
To insert a mathematical formula we use the dollar symbol $, as follows:

Euler's identity: $ e^{i \pi} + 1 = 0 $

To isolate and center the formulas and enter in math display mode, we use 2 dollars symbol:

$$
...
$$

Euler's identity: $$ e^{i \pi} + 1 = 0 $$
```

### Jupyter
![image](https://user-images.githubusercontent.com/35271042/111508804-55de0080-8709-11eb-9c61-44feeabacfe5.png)

### VS Code
![image](https://user-images.githubusercontent.com/35271042/111508596-1c0cfa00-8709-11eb-9dad-e4188e15012d.png)

Notice how the two places where latex is used doesn't render using latex and there is a duplication with the `...`

**Comment by IllusionMH** [comment]
Isn't is same as #118262 ?

**Comment by mjbvz** [comment]
This is because there are spaces around the `$`. This is a limitation of the library [we use for math formulas](https://github.com/iktakahiro/markdown-it-katex)

Closing as upstream. Long term, we don't want to maintain math support as part of VS Code core

**Comment by misolori** [comment]
Removing the milestone since this comes up during endgame testing
