### ISSUE TITLE
On Linux, attempting to start custom Task using user inputs causes error of: Undefined input variable 'myVar' encountered. Remove or define 'myVar' to continue, but works on Windows.

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode#119153]
Issue Type: <b>Bug</b>

Attempt to run the following custom task on Linux results in `Undefined input variable 'commentLength' encountered. Remove or define 'commentLength' to continue.`
I have tested the same task on Windows 10 in a VM and it worked as expected.

<details open>
<summary>Bugged custom input</summary>

```json5
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "inputs": [
        {
            "id": "commentLength",
            "type": "promptString",
            "description": "Enter comment character value:",
            "default": "65",
        },
    ],
    "tasks": [
        {
            "label": "Format_Comment",
            "type": "process",
            "command": "/mnt/x/GitHub/instance-id/FormatComments/build/fcomment",
            "windows": {
                "command": "C:/files/fcomment.exe",
            },
            "args": [
                "${file}",
                "${lineNumber}",
                "${input:commentLength}"
            ],
            "presentation": {
                "reveal": "silent",
                "revealProblems": "always"
            }
        },
        {
            "label": "ReloadFile",
            "type": "shell",
            "command": "code-insiders \"${file}\"",
            "windows": {
                "command": "pwsh.exe C:/files/reloadvs.ps1 \"${file}\"",
            },
            "presentation": {
                "reveal": "silent",
                "revealProblems": "always"
            },
        },
        {
            "label": "DoFormat",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Format_Comment",
                "ReloadFile"
            ]
        }
    ]
}
```

</details>

VS Code version: Code - Insiders 1.55.0-insider (892a1083cb2b9b3987ff7edc85376b5d9764433d, 2021-03-16T05:14:00.223Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor (32 x 2214)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 10, 10|
|Memory (System)|62.81GB (0.39GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id a61367b7-e8a4-4da6-905e-411623666a3a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
shell-syntax|bma|1.0.1
better-toml|bun|0.3.2
systemd-unit-file|coo|1.0.6
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
shell-format|fox|7.0.1
go|gol|0.23.2
todo-tree|Gru|0.0.205
terraform|has|2.8.3
Theme-TurnipUltimate|ins|0.0.1
stylua|Joh|1.1.1
kite|kit|0.142.0
vscode-lua-format|Koi|1.3.7
l13-sh-snippets|L13|0.15.1
aw-watcher-vscode|lin|0.4.1
bash-ide-vscode|mad|1.11.0
regionfolder|map|1.0.12
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
python|ms-|2021.4.655182705-dev
vscode-pylance|ms-|2021.3.1
jupyter|ms-|2021.4.641214696
remote-containers|ms-|0.164.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.5
powershell-preview|ms-|2021.2.1
linux-desktop-file|nic|0.0.14
vscode-autohotkey-plus-slimcode|raf|2.1.18
bash-debug|rog|0.3.9
bash-beautify|sha|0.1.1
lua|sum|1.18.1
vscodeintellicode|Vis|1.2.11
vscode-wakatime|Wak|5.0.1
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1
go-snippets|zsh|0.0.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
vsget980:30265949
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by MostHated** [comment]
Hey Alex,
    I appreciate you getting back to me on this. I am not sure exactly what the deal is, but there had been some updates to code-insiders since I placed this ticket and it started working properly (yesterday), but I just installed another update and now it is not working again, and I have not changed anything with the configuration of the task or my settings between the attempts.

Using the task configuration that you provided, I am experiencing the issue. 


<details>
<summary>Demonstration</summary>

![](https://i.imgur.com/aQXK7xp.gif)

</details>

<details>
<summary>Task Used</summary>

```json5
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "inputs": [
        {
            "id": "commentLength",
            "type": "promptString",
            "description": "Enter comment character value:",
            "default": "65",
        },
    ],
    "tasks": [
        {
			"type": "shell",
			"command": "echo",
			"args": [
				"${file}",
				"${lineNumber}",
				"${input:commentLength}"
			],
			"label": "Test Variable",
			"problemMatcher": []
		},
		{
			"type": "shell",
			"command": "echo hello",
			"label": "Just Echo",
			"problemMatcher": []
		},
		{
			"label": "Parent task",
			"dependsOrder": "sequence",
			"dependsOn": [
				"Test Variable",
				"Just Echo"
			],
			"problemMatcher": []
		}

    ]
}
```

</details>

**Comment by alexr00** [comment]
Interesting. What distro are you using?

**Comment by MostHated** [comment]
Here are OS specs

```sh
OS: Pop!_OS 20.10 x86_64
Kernel: 5.8.0-7642-generic
Shell: zsh 5.8
DE: GNOME 3.38.3
WM: Mutter
WM Theme: Pop
Theme: Pop-dark [GTK2/3]
Icons: Pop [GTK2/3]
Terminal: alacritty
```
