### ISSUE TITLE
Test: Extension vscode.Pseudoterminal in the web worker extension host

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119109]
Refs: https://github.com/microsoft/vscode/issues/116022

- [x] web @isidorn
- [x] web @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119109%0A%0A)

---

`vscode.Pseudoterminal` should now work in the web worker extension host, even when it's the only extension host available.

1. Clone `main`, build and run yarn web
2. Create a `vscode.Pseudoterminal` ([eg1](https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample), [eg2](https://github.com/microsoft/vscode/issues/116022#issue-802901430)) in a bundled extension - an easy way to do this is to just add it to an already included extension like image-preview
3. Load the web UI and make sure you can launch pty terminal(s) and they behave correctly

**Comment by isidorn** [comment]
This works for me. However I suggest to run
`resources/server/web.sh` instead of `yarn web`, since the second did not load all extensions for me

**Comment by bamurtaugh** [comment]
Thanks to @isidorn's great help, I was able to test this as well (Chrome, Windows OS): 

![image](https://user-images.githubusercontent.com/25310137/112198693-a0a8be00-8bca-11eb-9e75-37dd695c6fc1.png)

I tried activating on * and specific events.

Please let me know if there is anything else I should be seeing/verifying here.
