### ISSUE TITLE
Command-tilde hotkey with caps lock enabled does not switch between windows

### ISSUE THREAD

**Issue by dfcowell** [microsoft/vscode#119149]
- VS Code Version: 1.53.2
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Launch Code with more than one window open
2. Turn on Caps Lock
3. Press command-tilde (MacOS switch application window hotkey)

Expected outcome: switch focus between open windows.
Actual outcome: nothing happens.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@dfcowell I could not reproduce. Are you using the US keyboard layout or another one?

**Comment by dfcowell** [comment]
This is strange, I was able to reproduce consistently when I created this report, but I just tried again now and I can't. Closing until I can reliably reproduce. Sorry for wasting time.
