### ISSUE TITLE
Typsescript service has died 5 minute

### ISSUE THREAD

**Issue by ma-za-kpe** [microsoft/vscode#119102]
Issue Type: <b>Bug</b>

Typsescript service has died 5 minutes after it has been created, Typescript will not be restarted

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (3.03GB free)|
|Process Argv|. --crash-reporter-id 08449219-a283-4bdd-80aa-24acee8c8c06|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.2.1
chronicler|arc|0.1.11
vetur|oct|0.33.1
java|red|0.76.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vspre833:30267464
vsfjg287:30275553

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

What is error if reported from TS Server notification?
