### ISSUE TITLE
SQL block comments won't nest

### ISSUE THREAD

**Issue by paul-golabowski** [microsoft/vscode#119128]
Issue Type: <b>Bug</b>

In SQL, if a block comment includes within it another block comment, the outer block ends with the inner block, instead of continuing until its own termination string.

Ex:
This is the current behavior
/* --commented
/* --commented
*/ --uncommented
*/ --uncommented, displays as an error because it thinks there's no starting comment block

This is the desired behavior
/* --commented
/* --commented
*/ --commented
*/ --uncommented

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql|ms-|1.10.1

</details>

**Comment by dbaeumer** [comment]
This looks like a problem with the SQL extension. Please report the issue with their issue tracker.
