### ISSUE TITLE
Restart vscode, all my settings are lost

### ISSUE THREAD

**Issue by sylver** [microsoft/vscode#119173]
- VS Code Version: 1.54.3
- OS Version: macOS Catalina 10.15.7 

Steps to Reproduce:

1. Restart VSCode to apply the last update
2. Have a factory settings reset without any warning nor reason once update is done.

`/Users/[username]/Library/Application Support/Code/User/settings.json` was hundreds of config and now looks like this : 
```json
{
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue"
}
```

Does this issue occur when all extensions are disabled?: Yes (the file is definitely trashed)

Fortunately I was able to recover it from a Timemachine backup.

**Comment by sandy081** [comment]
We are very sorry about that. We would need some information to know what caused this. 

Can you please provide the list of extensions you have? 

Also I will provide you the link to previous version of VS Code and can you please try to repro it again?

https://az764295.vo.msecnd.net/stable/fd6f3bce6709b121a895d042d343d71f317d74e7/VSCode-darwin.zip

**Comment by sylver** [comment]
Hi @sandy081,

Thanks for your answer.

I tried several times with the app you provided, trying to reproduce exactly how it happened (I accidentally closed vscode and when I restarted it, it was updated with my settings reset), but was unable to reproduce the problem.

Looks like a random, one time, weird issue.

Here's my extensions just in case (nothing changed in my setup for a while btw):

42Crunch.vscode-openapi@4.2.0
alexdima.vscode-lcov@0.2.0
benvp.vscode-hex-pm-intellisense@0.3.0
bierner.markdown-emoji@0.1.0
BriteSnow.vscode-toggle-quotes@0.3.4
bubersson.theme-hop-light@0.0.4
christian-kohler.npm-intellisense@1.3.1
christian-kohler.path-intellisense@2.3.0
CoenraadS.bracket-pair-colorizer-2@0.2.0
dbaeumer.vscode-eslint@2.1.19
deerawan.vscode-dash@2.4.0
eamodio.gitlens@11.3.0
EditorConfig.EditorConfig@0.16.4
eg2.vscode-npm-script@0.3.17
forbeslindesay.vscode-sql-template-literal@0.1.0
GitLab.gitlab-workflow@3.15.0
Gruntfuggly.todo-tree@0.0.205
iampeterbanjo.elixirlinter@0.4.1
James-Yu.latex-workshop@8.16.1
jpoissonnier.vscode-styled-components@1.5.0
kumar-harsh.graphql-for-vscode@1.15.3
mjmcloug.vscode-elixir@1.1.0
ms-azuretools.vscode-docker@1.11.0
ms-kubernetes-tools.vscode-kubernetes-tools@1.3.0
ms-python.python@2021.3.658691958
ms-python.vscode-pylance@2021.3.1
ms-toolsai.jupyter@2021.3.619093157
ms-vscode-remote.remote-containers@0.163.2
ms-vscode.vscode-typescript-tslint-plugin@1.3.3
msjsdiag.debugger-for-chrome@4.12.12
msjsdiag.vscode-react-native@1.4.1
octref.vetur@0.33.1
oderwat.indent-rainbow@7.5.0
onecrayon.theme-quietlight-vsc@1.1.0
PKief.material-icon-theme@4.5.0
redhat.vscode-yaml@0.16.0
robinbentley.sass-indented@1.5.1
ronnidc.nunjucks@0.3.0
streetsidesoftware.code-spell-checker@1.10.2
streetsidesoftware.code-spell-checker-french@0.1.10
uloco.theme-bluloco-light@3.3.7
VisualStudioExptTeam.vscodeintellicode@1.2.11
vscodevim.vim@1.18.9
wayou.vscode-todo-highlight@1.0.4
whizkydee.material-palenight-theme@2.0.1
xabikos.JavaScriptSnippets@1.8.0
xaver.theme-ysgrifennwr@1.0.0

**Comment by sandy081** [comment]
Might be that you are hitting this issue - https://github.com/microsoft/vscode/issues/47763

**Comment by sylver** [comment]
@sandy081 
Seems like it could be related. 

As a final note, In my case, here's exactly happened: 
- no change in settings, nor extensions, nor theme, nor anything in VSCode for a very long time
- my theme is always Palenight Operator, no light/dark switch of any kind
- the new version was already downloaded and ready to be applied but i didn't restart it yet
- I accidentally hit Command+Q instead of Command+A which closed the app
- when launching back the app, the update applied, and It changed the theme back to the default one after a few seconds
- I was surprised and opened my settings to understand what happened and I noticed they have been cleared

Hope that can help !

**Comment by sandy081** [comment]
Thanks for more info, I will investigate in the lines of your steps and see if I can repro this.

**Comment by farfromrefug** [comment]
I have the same exact issue. Happened 3 times already in the last 2 weeks. I am running vscode insiders.
Let me know if i can help
