### ISSUE TITLE
Pressing End in terminal also sends keycode

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#119106]
Issue Type: <b>Bug</b>

When I'm running a program in the built-in terminal, and scroll up, and press Home, the program receives the key-press and prints `^[[F`. It should probably not pass that keycode on.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|-psn_0_27085267 --crash-reporter-id aa77e851-0fc5-45a8-b2b6-6d32c4e1f3ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-csv|mec|1.8.1
dotenv|mik|1.0.1
vscode-js-profile-flame|ms-|0.0.14
material-icon-theme|PKi|4.5.0
rewrap|stk|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244cf:30256637
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vspre833:30267464
vsdfh931:30275552

```

</details>

**Comment by Tyriar** [comment]
Can you share a [gif](https://gifcap.dev/) and your settings.json file?

Also do you have `terminal.integrated.sendKeybindingsToShell` set?
