### ISSUE TITLE
VS Code using too much energy on Mac, even though it's not running

### ISSUE THREAD

**Issue by aintyourcupoftea** [microsoft/vscode#119190]
![Screenshot 2021-03-17 at 10 08 55 PM](https://user-images.githubusercontent.com/79439692/111504159-658f3080-876d-11eb-9f33-29ac2af50bde.png)
![Screenshot 2021-03-17 at 10 08 30 PM](https://user-images.githubusercontent.com/79439692/111504174-6922b780-876d-11eb-90b9-77796b9278ce.png)
![Screenshot 2021-03-17 at 10 08 21 PM](https://user-images.githubusercontent.com/79439692/111504179-6a53e480-876d-11eb-8256-788de7c7f0a3.png)
- VS Code Version:Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
- OS Version: macOS Big Sur 11.2.3 (20D91)

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
If you see this issue again, please run the following for a minute and attach the `powermetrics.log`

```
sudo powermetrics -a 0 -s tasks --show-process-energy -u /tmp/powermetrics.log
```
