### ISSUE TITLE
Typescript| Support Ref path autocompletion like Import Statement.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119155]
- VS Code Version: 1.54.2
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:
![12](https://user-images.githubusercontent.com/17777237/111415399-82365480-86ea-11eb-89f6-d8c53e65a361.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Reference paths should not be used in modern code (unless you are authoring a d.ts file). Not worth trying to fix IMO
