### ISSUE TITLE
Webview - Hide webview developer tools access with a config in the manifest

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vscode#119177]
I would like to have a configuration that disables the option to access the webview developer tools for my extension. I was thinking it could be a prop called "allowDeveloperTools" somewhere in the package.xml. Then vscode would use it to show or hide developer tools. Or in the end user machines disable the access to this option automatically.

**Comment by bpasero** [comment]
@dbaeumer webviews are owned by MattB.

**Comment by mjbvz** [comment]
What is the use case for this?

**Comment by AllanOricil** [comment]
Dont let people read the code

**Comment by mjbvz** [comment]
No plans to support this use case on desktop and it would not be possible on web (or once VS Code migrates to iframe based webview on desktop)
