### ISSUE TITLE
Unbound BreakPoint while debugging node.js vscode 1.54.3

### ISSUE THREAD

**Issue by XinmengLyu** [microsoft/vscode#119151]
- VS Code Version:  1.54.3
- OS Version: Darwin x64 19.6.0

Steps to Reproduce:

1. Launch debugger by pressing F5
2. set a breakpoint in node js code

My launch.json: 
`
{

  "version": "0.2.0",

    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "AMA Node dev",
        "cwd": "${workspaceRoot}",
        "program": "${workspaceRoot}/src/server/index.js",
        "env": {
          "NODE_ENV": "development",
          "PORT": "3000",
          "WEBPACK_DEV-HOST": "localhost",
          "NODE_TLS_REJECT_UNAUTHORIZED": "0",
          "ONEOPS_ENVPROFILE": "dev"
        },
        "runtimeArgs": [
            "--nolazy"
        ],
        "preLaunchTask": "npm",
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen",
        "trace": true
      }
    ]
}
`

also tried `"debug.javascript.usePreview": false`, but still the same

Does this issue occur when all extensions are disabled?: Yes

**Comment by XinmengLyu** [comment]
[debugadapter-legacy.txt](https://github.com/microsoft/vscode/files/6214167/debugadapter-legacy.txt)
@connor4312

**Comment by connor4312** [comment]
@XinmengLyu it looks like you turned the new debugger off. We no longer support the old one. Please set `debug.javascript.usePreview: true`, and if you're still having issues on the new debugger then share its logs. Thanks!

**Comment by XinmengLyu** [comment]
[vscode-debugadapter-f7d08dbe.json.gz](https://github.com/microsoft/vscode/files/6214343/vscode-debugadapter-f7d08dbe.json.gz)
@connor4312 The issue still persist after I turn the new debugger back on

**Comment by connor4312** [comment]
It looks like you have a build process running in your repo, such as babel, but it isn't configured to create sourcemaps. Therefore we can't find the right place to set breakpoints. See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_tool-configuration for some pointers.

**Comment by alexpmorris** [comment]
I've had all sorts of issues with the past few releases of VSCode (Windows 10) trying to debug nodejs scripts. From VSCode opening a second file of the exact same name on a breakpoint, to `unbound breakpoints`, to debug/breakpoint support completely non-functional, to no longer seeing any console output unless setting `"console": "integratedTerminal"` in `launch.json`. 

It seems **there are certain versions of `node`** that the latest VSCode base simply **does not like**.
Apparently `node v8.8.1` that I was using is one of them. 

SOLUTION: Installing `nvs` from https://github.com/jasongin/nvs solved the problem, and everything worked again right after installing it along with the latest node release. In `launch.json` you can also easily target any version:

for newer `"type": "pwa-node"` --> `"runtimeVersion": "15"` or `"runtimeVersion": "15.13.0"`
for `"type": "node"` --> `"runtimeVersion": "15.13.0"`

**Comment by connor4312** [comment]
Yea, Node 8 has been end of life for a couple years now and is a little buggy
