### ISSUE TITLE
No autosuggestion / autocompletion for Chinese variables / identifiers

### ISSUE THREAD

**Issue by laowu2019** [microsoft/vscode#119154]
- VS Code Version: 1.54
- OS Version: Windows 10 1909

I am using lots of Chinese variables in writing Python codes, but early this month, I found these is no more autosuggestion / autocompletion for variables / identifiers started with Chinese character. I suspect it might be caused by the update of Code, so I tried older version (1.51), but the problem persists.

Same problem is encountered by programmers using Chinese variables like me. This is very upsetting. Please fix it. Thanks.

Does this issue occur when all extensions are disabled?: Yes

**Comment by dbaeumer** [comment]
@laowu2019 this is a problem with the Python extension you are using. Please report the issue there since VS Code out of the box has no Python code complete support.
