### ISSUE TITLE
Changing the "dirty close" icon in product icons shows normal close instead

### ISSUE THREAD

**Issue by RubenVerg** [microsoft/vscode#119192]
Issue Type: <b>Bug</b>

1. (As a sample) install my [Bootstrap Product Icons](https://marketplace.visualstudio.com/items?itemName=RubenVerg.bootstrap-product-icons) extension
2. Create a new unnamed file
3. Write something
4. The tab shows a normal `×` icon instead of the dirty one.

<small>Note that the icon set defines `close-dirty` as `\\f159`, which should show a backspace-like icon</small>

VS Code version: VSCodium 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-16T00:26:40.437Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-icalendar|af4|1.0.1
vscode-sqlite|ale|0.11.1
vsc-prolog|art|0.8.23
stories|bar|2.23.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.19
scala-lsp|dra|0.2.3
gitlens-insiders|eam|2021.3.1104
vscode-pull-request-github|Git|0.24.0
pico8vscodeeditor|Gru|0.2.3
todo-tree|Gru|0.0.205
vscode-coding-tracker|han|0.6.0
pico8-lang|ian|0.1.1
discord-vscode|icr|5.4.0
mediawiki|jak|2.1.0
aural-coding-vscode|jen|1.1.3
vscode-peacock|joh|3.9.1
pico8-vscode|joh|0.0.1
chat|kar|0.35.0
mcjson|Lev|0.4.1
banner-comments-plus|lun|0.3.1
rainbow-csv|mec|1.8.1
gitignore|mic|1.0.1
vscode-edge-devtools|ms-|1.1.4
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-wsl|ms-|0.54.6
powershell|ms-|2021.2.2
powershell-preview|ms-|2021.2.1
vsliveshare|ms-|1.0.3968
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-edge|msj|1.0.15
gradle-language|nac|0.2.3
vetur|oct|0.33.1
binary-viewer|Qia|1.1.1
vscode-xml|red|0.15.0
vscode-gradle|ric|3.6.1
vscode-gradle-extension-pack|ric|0.0.2
bootstrap-product-icons|rub|1.0.2
randomgen|Rub|1.0.1
xcompose|Rub|1.1.1
scala|sca|0.5.2
scala-snippets|sca|0.1.0
vscode-scss-formatter|sib|2.1.0
vscode-pegjs|tam|0.1.2
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.11
vscode-icons|vsc|11.2.0

(1 theme extensions excluded)

</details>

**Comment by RubenVerg** [comment]
Using official Code also doesn't solve the issue.

**Comment by RubenVerg** [comment]
It looks like commenting `close-dirty` isn't enough, I also need to comment `close` for it to show the correct icon.

**Comment by misolori** [comment]
This is due to the dirty icon referencing the direct unicode instead of the icon name in our source code. See https://github.com/microsoft/vscode/issues/116136 where we are tracking this. Will close this as a duplicate to consolidate the issues, thanks for reporting!

FYI @aeschli

**Comment by RubenVerg** [comment]
Oh, ok, that's pretty weird. Thanks!
