### ISSUE TITLE
Scroll jiggering when previewing Markdown 

### ISSUE THREAD

**Issue by bruno-brant** [microsoft/vscode#119184]
Issue Type: <b>Bug</b>

0. Install the plantuml plugin.
1. Create a new markdown file. 
2. Add some random text, then create a plantuml markdown:

```plantuml
@startuml
class MyClass {
    field1: string;
    field2: string;
}
@enduml
```
3. Open the markdown preview
4. Go back to the plantuml code, and edit it so that it keeps updating (add a new field, remove, etc.). 

*Current behavior:*
The plantuml image keeps re-rendering. Most of those times, the main window (the source window, not the preview) will *adjust scroll*. 

*Expected behavior:*
The source window should *never* change its scroll to accomodate for the preview. It's the preview window responsibility to find out where to position itself.

---- 

This isn't an issue with PlantUML AFAICT, because:

* PlantUML didn't cause this behavior until recently - I downgraded it a few versions to make sure.
* It's looks like some behavior of the preview window adjusting scroll to try to fix positions. 

VS Code version: Code - Insiders 1.55.0-insider (b353f063393226ffc0e70f6b1afe3f362734071e, 2021-03-17T08:38:18.747Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.27GB free)|
|Process Argv|--crash-reporter-id 4e347825-8035-44ec-905f-4159d9ffe78f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.3.0
vscode-pull-request-github|Git|0.24.0
plantuml|jeb|2.14.4
vscode-todo-parser|min|1.9.1
vscode-icons|vsc|11.2.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
vscoresta800cf:30265948
vsc_aa:30263845
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by bruno-brant** [comment]
This will probably help:

![Error](https://user-images.githubusercontent.com/1890900/111487868-78771600-8717-11eb-84a0-d4272b74d32a.gif)

**Comment by mjbvz** [comment]
If this only happens when the plantuml extension is installed, then it is caused by that extension
