### ISSUE TITLE
Test: data breakpoints access types

### ISSUE THREAD

**Issue by yannickowow** [microsoft/vscode#119197]
Refs: #113922 

- [x] anyOS @gregvanl
- [x] anyOS @alexr00

Complexity: 3
Authors: @yannickowow, @isidorn, @weinand

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119197%0A%0A)

---

1. Clone `https://github.com/microsoft/vscode-mock-debug`, `yarn` and hit `F5` to start running mock-debug in a new window out of source
2. New window opens with a `test.md` file. Press `F5` now you are debugging the `test.md` file with mock-debug out of source.
   
Verify the following:
- You can see data breakpoints actions in the VARIABLES view context menu (`Break When Value Is Read`, `Break When Value Changes`, `Break When Value Is Accessed`)
- Data breakpoints get shown in the breakpoints view once you add them via these context menu actions
- Once a data breakpoint is set for a local mock debug variable, and the name of that variable appears in the .md file concatenated with "_" + accessType value, the breakpoint gets hit. For example for variable `local_i` you need `local_i_read` to appear in `test.md` for the read data breakpoint to be hit
- Data breakpoints can be disable / enabled / removed like all other breakpoints

#### Example 1 

- Right click on local_i
- Select `Break When Value is Read`
- Right click on local_f
- Select `Break When Value Is Accessed`
- Continue execution
- Expect debuggee stops at each line containing `local_i_read`
- Expect debuggee stops at each line containing `local_f_readWrite`
- Finish debuggee

#### Example 2

- Disable breakpoint on `local_i`
- Continue execution
- Expect debuggee does not stop at line containing `local_i_read`
- Expect debuggee stops at each line containing `local_f_readWrite`

**Comment by isidorn** [comment]
@yannickowow thanks a lot. I will edit your initial comment to match the test plan template that we have and to try to simplify it for all testers.
If we get support for mock-debug then that would be great @weinand

**Comment by yannickowow** [comment]
Currently, mock-debug supports "read" access type. 
See : https://github.com/microsoft/vscode-mock-debug/blob/baa34fe11802cce90b38dd8a3b5b5f690516e087/src/mockDebug.ts#L553

I did some minor modifications on my side to test accessType implementation.

**Comment by isidorn** [comment]
Okey, thanks. Then let's wait and see what @weinand thinks, it might be easy to add this to mock debug to make testing easier.

**Comment by weinand** [comment]
@yannickowow since you seem to have a modified mock-debug that implements exactly what this testplan item requires, it would be helpful if you could submit a PR with the changes.

By default "F5" opens the test.md file in the "sampleWorkspace". It would be great if you could add a section "Date breakpoints" that explains the syntax and has the possible examples.

Thanks a lot!

**Comment by yannickowow** [comment]
Right, I will do it asap

**Comment by weinand** [comment]
I think it makes sense to support all three data access types.

**Comment by yannickowow** [comment]
Ok, I did a minor update about that in my last commit

**Comment by weinand** [comment]
@isidorn I've merged @yannickowow's PR. But I will not release that version to the marketplace (for other reasons).
So testers will have to run mock-debug out of source.
But the advantage is that "F5" will automatically open a test.md that already has examples for all access-types.

**Comment by isidorn** [comment]
@weinand @yannickowow great work, running from source makes sense, I will update the test plan item.

Tomorrow I will also delete all of our comments in this issue, so testers are not confused by them. Hope that is ok.

**Comment by alexr00** [comment]
Tested using Windows.

**Comment by gregvanl** [comment]
Tested on Linux Debian
