### ISSUE TITLE
Integrated github

### ISSUE THREAD

**Issue by BossFriend** [microsoft/vscode#119258]
It would be cool if there was a way to get access to github in vs-code with a Markdown preview. Where you can push commits and review code as well as live share.

**Comment by IllusionMH** [comment]
Have you seen https://code.visualstudio.com/docs/editor/github ?

**Comment by BossFriend** [comment]
no?
But thank you

**Comment by IllusionMH** [comment]
This is extension that provides integration with GH. Does it solve your request?
If there is something missing, most likely it should be request in extension repo.

**Comment by RPwnage** [comment]
I think that’s what he was looking for
