### ISSUE TITLE
New CLI option --wait-for-files

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#119220]
As opposed to `--wait` which also waits for the entire VS Code window to be closed in case a folder is supplied as parameter, this new option would only wait if files are supplied. In case a folder is supplied, with `--wait-for-files`, the `code` binary would return as soon as the window is opened.

Or, which seems reasonable to me, the behavior of `--wait` should not be applied to folders as the cli's help says:

```
  -w --wait                         Wait for the files to be closed before returning.
```

This is needed because of https://github.com/twpayne/chezmoi/issues/1068.

**Comment by felipecrs** [comment]
What about the second option (change the behavior of the current `--wait` option)? I can send a PR if you agree.

**Comment by aeschli** [comment]
Isn't that already how its implemented and working?

`--wait pathToFile` opens hat file in an editor and when you close that editor, vscode is closed.

**Comment by felipecrs** [comment]
> Isn't that already how its implemented and working?
> 
> `--wait pathToFile` opens hat file in an editor and when you close that editor, vscode is closed.

I'm talking about folders, not files.
