### ISSUE TITLE
[remote cli] support --wait with folders

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#119221]
- VS Code Version: 1.54.3
- OS Version: Windows 10 21H1 and Ubuntu 20.04.2 on WSL2.

Steps to Reproduce:

1. Open a VSCode window through WSL.
2. Open a Terminal inside of VSCode.
3. Type:
   ```
   ❯ code --wait ~/.dotfiles
   At least one file must be provided to wait for.
   ```

Does this issue occur when all extensions are disabled?: Yes

Additional details:

```sh-session
❯ which -a code
/home/felipesantos/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/bin/code
/mnt/c/Program Files/Microsoft VS Code/bin/code
❯ /home/felipesantos/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/bin/code --version
1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64
```

**Comment by aeschli** [comment]
In remotes, we currently only support waiting on files.

**Comment by felipecrs** [comment]
> In remotes, we currently only support waiting on files.

In such case, the `--wait` option should be at least ignored so. Many users have `EDITOR='code --wait'` in their environment.

**Comment by aeschli** [comment]
Isn't the EDITOR variable normally used with files? Most editors don't support folder as inputs

**Comment by felipecrs** [comment]
Yes, but there are some cases where third party programs may need to open folders, still relying on the `EDITOR` env. Such as https://github.com/twpayne/chezmoi/issues/1068.
