### ISSUE TITLE
Ctrl + Click is not working

### ISSUE THREAD

**Issue by JEETcodes** [microsoft/vscode#119252]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

ctrl + click on any function should go to the function definition.
VS Code version: Code 1.53.2
OS: RHEL 8.2

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:11.840Z)
OS version: Linux x64 4.18.0-240.15.1.el8_3.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2216)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 4|
|Memory (System)|31.17GB (0.43GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6396d1d8-1d9a-40d2-9792-366dd4843804|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.16
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
vsc-python-indent|Kev|1.12.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.11.0
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
reload|nat|0.0.6
material-icon-theme|PKi|4.5.0
vscode-data-preview|Ran|2.3.0
vscode-yaml|red|0.16.0
partial-diff|ryu|1.4.1
text-marker|ryu|1.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontb:30265425
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by mjbvz** [comment]
What language is this for? Please share example code

/needsMoreInfo

**Comment by JEETcodes** [comment]
I was using Python 3.6
This is the code:
```
def print_text(text_from_user):
    return print(str(text_from_user))
```
I tried to ctrl + click on "print()" function. It should have opened the function definition for print() but it didn't. Instead, the loading bar is seen continuously for 15 mins.
