### ISSUE TITLE
Dedupe auto detected profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119277]
If there are multiple paths registered for a shell in `/etc/shells` they come up as separate profiles, we should pick only one (whichever is the default? maybe the last? should see if we can find what is meant to be the primary one)

![image](https://user-images.githubusercontent.com/2193314/111690240-2ce16c80-87ea-11eb-89a4-0447f826787e.png)

**Comment by meganrogge** [comment]
I think that's fixed by this https://github.com/microsoft/vscode/pull/119213/files#diff-1225c767b5c19130ced195b0cd520a93a19aa7adb08979b77c8cc197eb4c1bf3R224

The first valid path is accepted.
