### ISSUE TITLE
"Go to definition" is slower when using Cmd+Click than shortcut/menu option

### ISSUE THREAD

**Issue by Bringoff** [microsoft/vscode#119212]
Issue Type: <b>Performance Issue</b>

This happens when I try to navigate to class/field definition using Cmd+Click shortcut. Progressbar under tab bar appears for a couple of seconds and then VS Code proceeds to an expected file/line. But when I try to do the same by pressing F12 or choosing this option from the context menu, the VS Code performs this navigation immediately, without any delays and progress bars. This is true at least for Dart code, don't have other projects that can be opened in VS Code at the moment. But this indeed is frustrating as I use Cmd+Click more often than the F12 shortcut.

<img src="https://habrastorage.org/webt/k3/13/lk/k313lkeinz0_00ccmzwb2uu1npy.gif" width="500" />

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id ffd7793e-e2b4-4f89-bdc3-4f633ec70a5e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   23	   623	 87305	code main
    3	   221	 87315	   gpu-process
    0	    98	 87319	   utility
    8	   680	 87519	   shared-process
    0	    82	 87522	     ptyHost
    0	     8	 90372	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	  1319	 90030	   window (master_data_gateway.dart — flutter-mvp)
    1	   754	 90038	     extensionHost
    0	  2744	 90099	       /Users/bringoff/fvm/versions/1.22.3/bin/cache/dart-sdk/bin/dart /Users/bringoff/fvm/versions/1.22.3/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id=VS-Code --client-version=3.20.1
    0	     8	 90101	       bash /Users/bringoff/fvm/versions/1.22.3/bin/flutter daemon
    0	   508	 90123	         /Users/bringoff/fvm/versions/1.22.3/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/bringoff/fvm/versions/1.22.3/packages/flutter_tools/.packages /Users/bringoff/fvm/versions/1.22.3/bin/cache/flutter_tools.snapshot daemon
    0	     8	 90198	           /usr/bin/script -t 0 /dev/null xcrun xcdevice observe --both
    0	   131	 90199	             /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	   164	 90113	       electron_node server.js 
    0	   246	 90166	       electron_node server.js 
    0	   303	 90039	     watcherService
    0	   164	 90084	     searchService
    7	   311	 90366	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (master_data_gateway.dart — flutter-mvp)
|    Folder (flutter-mvp): 5540 files
|      File types: h(2384) dart(342) m(321) plist(156) svg(155) json(121)
|                  modulemap(90) xcconfig(84) png(46) xcfilelist(38)
|      Conf files: tasks.json(15) launch.json(1) settings.json(1) makefile(1)
|      Launch Configs: dart(3);
```

</details>
<details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.56
dart-data-class-generator|Ben|0.5.0
unique-lines|bib|1.0.0
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
vscode-eslint|dba|2.1.19
emulate|Die|1.4.0
eslint-disable-snippets|drK|1.3.0
find-related|eam|0.9.0
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
gitlab-mr|jas|1.4.3
pubspec-assist|jer|2.2.1
intellij-idea-keybindings|k--|1.4.2
vscode-gutter-preview|kis|0.27.1
camelcasenavigation|map|1.1.3
flutter-tree|mar|1.0.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.2.2
awesome-flutter-snippets|Nas|2.0.4
material-icon-theme|PKi|4.5.0
total-lines|pra|0.0.1
java|red|0.76.0
vscode-coverage-gutters|rya|2.7.2
partial-diff|ryu|1.4.1
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.5
code-spell-checker|str|1.10.2
errorlens|use|3.2.5
vscodeintellicode|Vis|1.2.11
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30277039
dockersubset:30270708
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by IllusionMH** [comment]
Does it depend on order of operations or <kbd>Ctrl</kbd>+<kbd>Click</kbd> is always slow?

If LS uses lazy initialization and cache then first non-cached operation will be slow.

In JS/TS project first navigation/autocompletion is slow (either with <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Click</kbd>) and then there is no difference between two.

**Comment by Bringoff** [comment]
> In JS/TS project first navigation/autocompletion is slow (either with F12 or Ctrl+Click) and then there is no difference between two.

Unfortunately, it's a bit different for Dart. Even the first navigation after restart is quick when using F12. On the other hand, most of the subsequent navigations to the same class using Cmd+Click are still slow. Looks like about 1 out of 5 navigations to the same place may be performed quickly with a click, but then it slows down again.

**Comment by dbaeumer** [comment]
@Bringoff can you please report this to the Dart extension first (https://github.com/Dart-Code/Dart-Code) since we don't see this with other languages.
