### ISSUE TITLE
TS server continue to run forever

### ISSUE THREAD

**Issue by BnayaZil** [microsoft/vscode#119236]
Issue Type: <b>Bug</b>

Initially the TS server manage to generate Intellisense but after sometime crushes and I can see endless loading of the TS server.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (3.72GB free)|
|Process Argv|--crash-reporter-id 67b1aece-fe14-48b4-82fc-e3b961d2c16a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
stories|ben|2.22.0
vscode-intelephense-client|bme|1.6.3
turbo-console-log|Cha|2.1.6
vs-code-semicolon-insertion|chr|0.0.6
source-viz-vscode|cow|0.2.8
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
haml|kar|1.3.1
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.3.3
typescript-hero|rbb|3.0.0
ruby|reb|0.28.1
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
mdx|sil|0.1.0
code-spell-checker|str|1.10.2
vscode-ruby|win|0.28.0
glean|wix|5.1.1
stylable-intelligence|wix|0.7.3
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
pythonvspyt943cf:30277002
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
