### ISSUE TITLE
Remote SSH terminal alongside existing local terminal?

### ISSUE THREAD

**Issue by proimage** [microsoft/vscode#119273]
(I feel like I must be missing something obvious, because this seems like such a no-brainer, but I can't for the life of me find out how to do this.)

VSCode already has a local terminal at the bottom, which is superb. I'd like to be able to have a remote SSH terminal right alongside the local one. I don't want or need to connect to an entire remote development environment as with "Remote - SSH". I just want a simple remote terminal view.

Features:
- Globally saved ("Favorites") servers
- Per-Workspace customization of those global servers, including but not restricted to:
    - Starting directory
    - Background & foreground colors
- Side-by-side / tiled view, as well as tabs (speaking of which: Seriously? We switch between multiple terminals via a _dropdown box_? O.o ). Honestly, the system you have going on with the code editors' tabs & panes is so superb, you might as well straight-up use that for the terminals.
- Dunno if this is a thing, but some sort of indicator (a colored dot in the tab, perhaps) when a long-running command finishes (> 1s? 5s?) would be useful.
- Some sort of quick-action, toolbar buttons for mapping frequently used commands to a simple, time-saving click (or a click and `enter`).

Someone, please tell me I'm missing something obvious here and that this basically already exists... 🙃

**Comment by roblourens** [comment]
You can always type the ssh command yourself in any terminal. It sounds like that's really what you want. We are focusing development efforts on the full Remote-SSH development experience, not reinventing the wheel by customizing a basic ssh terminal.

> Globally saved ("Favorites") servers

This is what the ssh config file is https://www.ssh.com/ssh/config/

> terminal tabs

Working on this https://github.com/microsoft/vscode/issues/10546. Side-by-side terminals already exist

**Comment by proimage** [comment]
I'm on Windows; it looks like all that is for *nix systems, with the forward slashes in paths.

**Comment by proimage** [comment]
Ok, so turns out after some digging that Windows does support an SSH config file, under the `C:\Users\[username]\.shh\` directory. It's all very Linux-oriented stuff, though, which begs the question that if VSCode already provides a wonderful "GUI abstraction layer" or sorts for git, why not a similar GUI abstraction layer for SSH?
