### ISSUE TITLE
files.associations

### ISSUE THREAD

**Issue by helibin** [Microsoft/vscode#11920]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 1.5.2
2. osx 10.11.5

1、files.associations 匹配.bash_xxx为powershell模式无效，怎么能默认使用powershell模式而不是纯文本

**Comment by Campanula** [comment]
try this in your settings.json

```
"files.associations": {
        "*.bash_xxx": "powershell"
        },
```

**Comment by bpasero** [comment]
Please comment in english and reopen when the suggestion by Campanula does not work.

**Comment by helibin** [comment]
does not work, I tried before

**Comment by Campanula** [comment]
@helibin I misread the file name, try the following

```
"files.associations": {
        ".bash_*": "powershell"
        },
```
