### ISSUE TITLE
How to deal with error "connect ECONNRESUDED" when I don't have a internet connection

### ISSUE THREAD

**Issue by william54wp** [Microsoft/vscode#11929]
- VSCode Version: 1.5.1
- OS Version: win7x64

I got an error " connect ECONNREFUSED 127.0.0.1:443" when starting VSCode in a computer without internet connection
i konw it reports error for cann't conect to EXT servers
How can I stop VSCode report this error every time?
Thanks for Help

**Comment by isidorn** [comment]
Verified by disabling wi-fi, however found #13074 while verifying this
