### ISSUE TITLE
Can't use shortcut Alt + A to click "Don't save" on Brazilian Portuguese

### ISSUE THREAD

**Issue by awvalenti** [microsoft/vscode#119222]
Issue Type: <b>Bug</b>

1. Use Brazilian Portuguese translation
2. Create new file and insert any text
4. Close tab. A dialog will appear with options "Salvar", "Não salvar" and "Cancelar".
5. Try triggering "Não salvar" using the keyboard shortcut Alt + A (letter A is underlined, indicating the shortcut)

The problem occurs because the a letter has a tilde on it (and it should have), which makes it impossible to use only the A key.

A simple solution would be to underline 'N' instead of 'ã', producing the Alt + N shortcut

**Comment by dbaeumer** [comment]
We should adjust that in the translation. The character to use is usually denoted with a `&`

**Comment by v-mholloway** [comment]
Fix implemented - Note: it will take a few days to make it into the build
Resource ID:	0;"Xliff file"\0;"Xliff Resources"\0;"src/vs/workbench/services/dialogs/browser/abstractFileDialogService.dontSave"
Relative File Path:	vscode-loc-drop/loc/en/src/en/vscode-workbench/vs_workbench_services_dialogs.xlf.lcg
Project:	VSCode
Subtenant:	VSCode

**Comment by v-mholloway** [comment]
fix should be in the build now
