### ISSUE TITLE
Ability to update extension packs through VSIXs

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#119265]
Currently installing a VSIX is always considered as fresh install and in case of an extension pack we install completely. It would be nice if one can update extension packs through VSIX and install only newly added extensions to extension pack.

**Comment by egamma** [comment]
//CC @jakebailey

Python insiders uses the installExtension command to install prerelease versions of the extension. They are now looking for an install command that has the same behaviour as the VS Code's builtin update already has:
- Any extension in the pack that has been uninstalled is not reinstalled on update. 
- Any extension in the pack that is new is now installed.

**Comment by sandy081** [comment]
Added an install option `installOnlyNewlyAddedFromExtensionPackVSIX` to the existing install command. Enabling it will install only newly added extensions in the extension pack. This flag is considered only while installing VSIX.

Eg:
```ts
vscode.commands.executeCommand('workbench.extensions.installExtension', vscode.Uri.file('/users/sandy081/downloads/ms-python.python-2021.5.842923320.vsix'), { installOnlyNewlyAddedFromExtensionPackVSIX: true })
```
