### ISSUE TITLE
Is it possible to get text suggestions as I type in VS Code?

### ISSUE THREAD

**Issue by septsea** [microsoft/vscode#119232]
There is an option called _Show text suggestions as I type_ in Windows 10:

![image](https://user-images.githubusercontent.com/57337516/111593369-d2093e80-8804-11eb-84c6-44f4fd810f22.png)

I am not a native speaker of the English language, so this feature really helps me a lot. I could get suggestions in Word:

![image](https://user-images.githubusercontent.com/57337516/111593549-067cfa80-8805-11eb-8fd3-1c2832ae40b7.png)

I mainly use Visual Studio Code as a Markdown and LaTeX editor, so I wish I can get text suggestions as I type in VS Code!

![image](https://user-images.githubusercontent.com/57337516/111594559-2a8d0b80-8806-11eb-9995-d8035976eb57.png)

**Comment by dbaeumer** [comment]
@septsea the setting you are pointing to are for the Windows OS. VS Code has its own settings (File->Preferences->Settings)

This being said VS Code doesn't have out of the box support for what you are looking for. It has suggestions only for programming languages and words not for human languages. But you might find an extension in VS Code's marketplace. There are at least spell checkers for Markdown.
