### ISSUE TITLE
Feature Request: allow for groups of open editors quick switching

### ISSUE THREAD

**Issue by Davidsastresas** [microsoft/vscode#119241]
I think it would be very useful to be able to arrange groups of open editors ( including split screens, etc ) in vscode. Similar to how you can arrange groups of screen divisions in tmux. 

So for instance, you could have a group consisting of a window split by half with different groups of files on each of them, and then have another group with another set of files with no split screen. 

I use this feature extensively on tmux, and I think it can contribute to improve a lot the experience in vscode, as sometimes you are studying a large project and you need to keep track of several files at the same time, but with the current functionality you can get your current screen view super crowded of opened files.

Thanks!

**Comment by isidorn** [comment]
Sounds like a feature request for editors, thus forwarding to @bpasero
We already have editor groups, but it sounds like you want something more permanent.
