### ISSUE TITLE
Organize imports throw the error: Running the contributed command: '_vscode_delegate_cmd_kmel0ckh' failed.

### ISSUE THREAD

**Issue by molly-w** [microsoft/vscode#119234]
- VS Code Version: 1.54.3
- OS Version: Microsoft Windows [Version 10.0.19041.572]
- Installed extension: Java Extension Pack(v0.13.0)

Steps to Reproduce:

1. Add the following code in Settings.json:
```
"java.format.settings.url": "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml",
"java.format.settings.profile": "GoogleStyle"
```
2. Press **Shift+Alt+O** to show the yellow bulb,
3. Click the bulb and choose **Organize imports**, the error occured:
![c](https://user-images.githubusercontent.com/63043224/111601355-3d570e80-880d-11eb-8cbc-71ea84bb135a.gif)

Does this issue occur when all extensions are disabled?: No

When i check **Log(Extension Host)**, it showed: `actual command NOT FOUND _vscode_delegate_cmd_kmel0ckh`
![屏幕截图 2021-03-18 143340](https://user-images.githubusercontent.com/63043224/111601584-78594200-880d-11eb-83f0-7c30c4ec7626.png)

Orignial Post: https://stackoverflow.com/questions/66676438/google-style-formatting

**Comment by jdneo** [comment]
@gjsjohnmurray This issue can be reproduced in TS as well.

Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

![test](https://user-images.githubusercontent.com/6193897/113120407-24eee700-9244-11eb-9c29-902ed3e7fa46.gif)

Though the yellow bulb will disappear very quickly after `alt+shift+o`, as long as you click on it before it disappears, and then click `Organize Imports`. you can see the error message.

**Comment by gjsjohnmurray** [comment]
pinging @mjbvz for decision about reopening and assigning.
