### ISSUE TITLE
Cannot search/filter by snippet description in the Command Palette/Insert Snippet

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#119261]
Steps to Reproduce:

1.  trigger the Command Palette: `Insert Snippet` command
2.  Try to search by a snippet's "Description" field for a word not in the prefix - does not work.

The description field can be seen in the Command Palette but cannot be searched for successfully.

Seems to be a regression, see https://github.com/microsoft/vscode/issues/31768

@jrieken 

Tested in Stable and Insiders.

Version: 1.55.0-insider (user setup)
Commit: 111a6cec70f9562cdd31a5fd8cdea4b3a9b7bd82
Date: 2021-03-18T05:14:49.087Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.21332

Does this issue occur when all extensions are disabled?: Yes

**Comment by jakiro2017** [comment]
I confirm this issue is happened on 1.54, while it worked on 1.43
