### ISSUE TITLE
Reopen notebook in smaller window than previously opened feels broken

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#119205]
Issue Type: <b>Bug</b>

1. Open a notebook do some work
2. Scroll all the way to the bottom cell. Then close the notebook and resize the window to be smaller
3. When you open the notebook again I find that you will have been scrolled so that no content is on your screen and it feels as if the notebook didn't load at all since the scroll bar disappears. 

<img width="1454" alt="Screen Shot 2021-03-17 at 3 56 23 PM" src="https://user-images.githubusercontent.com/4544166/111530965-504cde80-873a-11eb-995e-b80d5464fb63.png">

VS Code version: Code - Insiders 1.55.0-insider (b353f063393226ffc0e70f6b1afe3f362734071e, 2021-03-17T08:48:26.411Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 7170f6db-7270-442f-945e-4508c02991d4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-track-build-errors|aes|0.0.3
vscode-eslint|dba|2.1.19
gitlens-insiders|eam|2021.3.1104
EditorConfig|Edi|0.16.4
codespaces|Git|0.8.4
vscode-pull-request-github|Git|0.24.0
rainbow-csv|mec|1.8.1
python|ms-|2021.4.661730536-dev
jupyter|ms-|2021.4.641214696
remote-containers|ms-|0.164.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
vscode-remote-extensionpack|ms-|0.20.0
js-debug-nightly|ms-|2021.3.1617
vscode-github-issue-notebooks|ms-|0.0.72
vscode-markdown-notebook|ms-|0.0.14
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
vscoresta800cf:30265948
vsc_aacf:30263846
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by rebornix** [comment]
Good point, we should never show a full viewport of whitespace to users.
