### ISSUE TITLE
Go to definition no longer working for non-js/ts files

### ISSUE THREAD

**Issue by binury** [microsoft/vscode#119203]
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

In the past it *was* possible to follow any `require` statement to the source file. About a year ago I noticed that it was no longer working *if the file was not an actual Javascript module*. I held off reporting as I figured it would be noticed easily and fixed… This is a minor annoyance when using, e.g., Webpack because there are statements that require html/css/etc. Is this an intended change to how module resolution is handled when using `go to definition`?

```js
const html = require('./markup.html');
const config = require('./config.json');
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This has never been supported out of the box so it's likely that you had an extension that provided this functionality

**Comment by binury** [comment]
Thanks @mjbvz I went back to build 1.33 (March 2019) to confirm; it doesn't

For anyone reading through issues in the future: I found a plugin which provides this functionality to go-to-definition
https://marketplace.visualstudio.com/items?itemName=abierbaum.vscode-file-peek
