### ISSUE TITLE
@see tag not clickable in hover window

### ISSUE THREAD

**Issue by jasonkuhrt** [microsoft/vscode#119288]
- VS Code Version: 1.54.2
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Define a valid @see tag
2. Notice it working in the source code

    ![image](https://user-images.githubusercontent.com/284476/111706887-76957b80-8819-11eb-8d05-d60c94250e82.png)

2. Notice it not working in the tooltip

    ![image](https://user-images.githubusercontent.com/284476/111706923-8745f180-8819-11eb-8b6b-cc98da253498.png)

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/35524
