### ISSUE TITLE
Cannot update on Mac "while running on a read-only volume" ...

### ISSUE THREAD

**Issue by melissamarchand** [microsoft/vscode#119210]
Get this error even with the new February 2021 version of visual studio code on my MacBook Pro with Big Sur on it. "Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. This might mean the application was put on quarantine by macOS. See this link for more information." "This link" goes to 
https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469 where it states:

"This is due to a well known Squirrel issue: Squirrel/Squirrel.Mac#182
Workaround: Move Code out of Downloads and into the Applications folder.
Workaround 2: If updates still don't work after moving Code to the Applications folder, you can fix it with xattr:
sudo chown $USER ~/Library/Caches/com.microsoft.VSCode.ShipIt/*
xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app
Closing this issue since the fix for #57664 allows us to inform users of this situation, instead of failing silently."

BUT THIS DOES NOT FIX MY PROBLEM.  Any new ideas since this article is from 2018?

<img width="1021" alt="Screen Shot 2021-03-17 at 5 14 13 PM" src="https://user-images.githubusercontent.com/51327089/111539444-44661a00-8744-11eb-8d26-585f94b761ef.png">

**Comment by ddzy** [comment]
Same issue..

**Comment by deepak1556** [comment]
Can you provide steps or screen recording of what you did to hit this issue (i-e) where did you download the app and where was it moved to ?
