### ISSUE TITLE
Can not install the 1.54.3 vscode  on the centos 7.

### ISSUE THREAD

**Issue by JWleo** [microsoft/vscode#119244]
- VS Code Version:1.54.3
- OS Version:CentOS 7

Steps to Reproduce:

1.get the file of VSCode-linux-x64 from the code-stable-x64-1615806628.tar.gz;
2.run the /bin/code, and the window shut down just like this below.

<img width="540" alt="5ddd29befa79060d3492cfd89d38b65" src="https://user-images.githubusercontent.com/32316654/111623611-8adf7580-8825-11eb-9d8b-8122103fe45d.png">

**Comment by JWleo** [comment]
@gjsjohnmurray this is not duplicate one ,please read it carefullly.

**Comment by gjsjohnmurray** [comment]
@JWleo people using 1.54.3 on CentOS 7 are reporting several different issues. Bottom line seems to be that it's not a supported platform.
