### ISSUE TITLE
Custom Sort Order in File Explorer

### ISSUE THREAD

**Issue by KyleMit** [microsoft/vscode#119207]
I'd like to specify a custom sort order in the file explorer. For example sorting folders like this:

<pre><code>
components
├── <b>layout</b>
├── <b>ui</b>
├── <b>utils</b>
├── other-folder
└── another-folder
</code></pre>

Where the bold folders have an an explicit sort order specified, and then everything else is sorted alphabetically.

Currently, there's a setting for `explorer.sortOrder` which takes in `default | mixed | filesFirst | type | modified`, but doesn't allow explicit lists.

### API Proposal 1

`sortOrder` could potentially be extended to take a value of `custom` with an additional array passed in like this:

```json
{
  "explorer.sortOrder": "custom",
  "explorer.sortCustom": ["layout", "ui", "utils"]
}
```

### API Proposal 2

Another place this shows up in when cloning a wiki project in Azure Dev Ops, which specifies an [**`.order` file**](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file) that provides a custom sort order on their UI

eg. `.order`
```
Welcome
Home
Boards
More Articles
```

### Extension

If there's a way to accomplish this with an extension, I'd be willing to take a pass at it if folks have any ideas about where to start or if it's possible

### Workaround

You could rename folders, `1 - layout`, `2- ui`, `3-utils`, but this approach is much noisier

### Further Reading

* [How can I manually change the order that folders are listed in Visual Studio Code Explorer?](https://stackoverflow.com/q/54968639/1366033)

**Comment by isidorn** [comment]
Makes sense, however closing as dup of https://github.com/microsoft/vscode/issues/27286
