### ISSUE TITLE
Native Notebooks - Editor + Output font size do not match (Add setting to change output font size) 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#119214]
# Steps to Repro: 
1. Open settings (UI) 
2. Set editor font size to 8
3. Open notebook, run simple print statement

# Actual Behavior: 
Output does not honor set editor font size
![image](https://user-images.githubusercontent.com/19276747/111547881-129a8680-8737-11eb-98be-3687ee78f845.png)

**Comment by rebornix** [comment]
> Output does not honor set editor font size

Yup, that's why it's called "editor font size", which will only change font size of the text editor.

**Comment by claudiaregio** [comment]
@rebornix Are there plans to add a setting for the output font size?

**Comment by rebornix** [comment]
> @rebornix Are there plans to add a setting for the output font size? Or some setting to have the editor font size match the output font size? Believe the customer expectation for something like a notebook would be that they are the same (by default at least)


We would need to explore what's the impact on the overall look of the notebook editor.

**Comment by claudiaregio** [comment]
I see. I had two users bring this up this past week. The most recent one this weekend mentioned that they tried out vs code is because of support for Julia and theyre in search of a mathematica replacement. They like a package that Julia offers but the rendered output is too small. They provided the photo below and mentioned how the lines are thin and the terms can get small. They are aware of the ability to zoom in on the entire vsc screen but do not like that the entire UI also gets upscaled and crowds the screen. 

![image](https://user-images.githubusercontent.com/19276747/112051944-befdb380-8b0f-11eb-9ce8-55864063a43e.png)

The first user very specifically just wanted the size to match but did not necessarily want the default size in output that was provided.

**Comment by misolori** [comment]
This might be more of an output rendering request as opposed to font-size, it might be interesting to see if we could enable controls that allows users to make the output smaller/bigger and persist those.

**Comment by claudiaregio** [comment]
I agree @misolori , think im tracking two different pain points here. I think the input/output general size customer expectation would be that they are same font size. For something like the math equations that is more likely rendering related.

**Comment by claudiaregio** [comment]
+1 from customer 
![image](https://user-images.githubusercontent.com/19276747/115273494-7a583e80-a0f4-11eb-92ac-aeaf13bd312c.png)

**Comment by claudiaregio** [comment]
+1 from customer: 
https://github.com/microsoft/vscode-jupyter/issues/4031#issuecomment-830089581

Hi!

This issue has been closed but I cannot find anything that describes how I can change the font family and/ or size for the code cell execution output!?

Can someone point me to an according setting, please?

Thank you,
Jamil

**Comment by claudiaregio** [comment]
+1 from survey monkey 

![image](https://user-images.githubusercontent.com/19276747/117376246-9ba38380-ae85-11eb-921e-65449ba4eab2.png)

**Comment by claudiaregio** [comment]
+1 customer feedback 

![image](https://user-images.githubusercontent.com/19276747/117401455-7892c700-aeb9-11eb-8f08-0fe037b7e0b9.png)

**Comment by rebornix** [comment]
Pushed changes to align the editor font size and output font size, which look pretty good


<img width="605" alt="image" src="https://user-images.githubusercontent.com/876920/119198703-a130ca00-ba3e-11eb-9ead-be6e149b012a.png">

**Comment by Queuecumber** [comment]
I don't think this quite addresses [microsoft/vscode-jupyter#403](https://github.com/microsoft/vscode-jupyter/issues/4031), that was asking for a way to change the font size of specific elements rather than pointing out that there are size inconsistencies. 

Is that something that is being worked on or should an issue be opened? In my case, the editor font size and output font sizes all look fine but the markdown is really small for some reason: 

![markuphero-4zRacRnMAp92uSoD1B2U-1](https://user-images.githubusercontent.com/5865387/119748284-8e652d80-be62-11eb-9bdd-82136e193914.png)

I've tried changing the "Markdown > Preview: Font Size" setting but it seems like that isnt being used here

**Comment by misolori** [comment]
@Queuecumber this issue was for: `Editor + Output font size do not match`, so this does not cover rendered markdown content. Please create a new issue.

**Comment by claudiaregio** [comment]
@Queuecumber I have filed the second issue here: https://github.com/microsoft/vscode/issues/124872
