### ISSUE TITLE
Saving mementos in deactivate does not work 

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#119254]
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. In extension deactivate function, set the value of a memento and check the value
2. Reload VS Code window
3. In extension activate function, check the value of the memento

Expected: The value in activate will match the value set in deactivate
Actual: The value in activate is always undefined. 

![deactivate-mementos](https://user-images.githubusercontent.com/22576531/111648794-f8a58600-87c0-11eb-894b-6551d2ed980d.gif)

Repro Extension:
[mementoactivate.zip](https://github.com/microsoft/vscode/files/6165126/mementoactivate.zip)

**Comment by bpasero** [comment]
Since this seems to be about extensions, adding some more folks to determine what exactly happens when a window reloads with regards to extension deactivation.

**Comment by bpasero** [comment]
@alyssajotice can you please attach a reusable extension code snippet (preferably minimal) to showcase the issue and for us to reproduce?

**Comment by alyssajotice** [comment]
The extension is in the `mementoactivate.zip` attached above, but here are the individual files:

extension.ts

```import * as config from './config';
import * as vscode from 'vscode';
import { MementoConfig } from './MementoConfig';

export function activate(context: vscode.ExtensionContext) {
	MementoConfig.initAsync(context);
	console.log("(Ativate), memento = " + MementoConfig.get(config.Key.memento));
}

export function deactivate() {
	MementoConfig.save(config.Key.memento, true);
	console.log("(Deactivate) Memento = " + MementoConfig.get(config.Key.memento));
}
```


MementoConfig.ts
```
import * as vscode from 'vscode';

export class MementoConfig {
	
    private static globalState: vscode.Memento | undefined;

    static initAsync(context: vscode.ExtensionContext): void {
        this.globalState = context.globalState;
    }

    static get<T>(key: string): T | undefined {
        return this.globalState ? this.globalState.get<T>(key) : undefined;
    }

    static async save(key: string, value: any): Promise<void> {
        if (!this.globalState) {
            throw new Error('Not initialized.');
        }
        this.globalState.update(key, value);
    }
}
```

Config.ts
```
export enum Key {
    memento = 'memento'
}
```

**Comment by alexdima** [comment]
Unfortunately, this is not something we support. The memento is implemented on the renderer process. At the time when deactivate is called on extensions, the renderer process could have already exited (the window does not wait for the extension host process before exiting), so when deactivate is called there is nobody there to write the memento values to workspace or global storage. This is true for many of the vscode APIs, which will not function normally during deactivate.

As it stands right now, we think that the `deactivate` function should only be used for cleaning up important OS or server-side resources (e.g. shutdown a server that is costing money, kill a spawned process) and is not a time to save state or implement hot-exit. We think that state should be saved continuously, during runtime.

**Comment by alyssajotice** [comment]
Thank you for the explanation. I had also been trying to execute commands during deactivate, so this is good to know.

**Comment by alyssajotice** [comment]
@alexdima is __reading__ mementos during deactivation supported?

**Comment by alexdima** [comment]
I don't quite know. @jrieken do you know if reading mementos is sync on the ext host or needs the renderer?
