### ISSUE TITLE
Format code not working on #vars

### ISSUE THREAD

**Issue by JoseChris2911** [microsoft/vscode#119246]
Issue Type: <b>Bug</b>

In a JS file, when I format the code (shift + alt + F) the variable identifier (#) separates from the variable name 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G    (2 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.39GB (3.72GB free)|
|Process Argv|--crash-reporter-id b479c517-cabd-487d-914a-720459e32518|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide code example that causes issue. Code below doesn't change format.

```js
class A {
	#num = 1;
	#str = 'qwe';
	constructor(a) {
		this.#num = a;
	}
}
```

Also check if it is reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by JoseChris2911** [comment]
Ok i reload it with all extensions disabled and it works fine again
