### ISSUE TITLE
Function calls with function arguments tab-complete incorrectly

### ISSUE THREAD

**Issue by yhaskell** [Microsoft/vscode#11926]
- VSCode Version: 1.5.2
- OS Version: OS X (El Capitan) 10.11.6

Steps to Reproduce:

1. Create a new file and save it as (anyname).ts
2. Enter the following code:
```ts
var arr = [1, 2, 3];
arr.map
```
3. Press &lt;TAB>
4. Result would be 
```ts
var arr = [1, 2, 3];

arr.map(callbackfn, value, index, array, thisArg)
```
Which is incorrect, since Array.map accepts 2 arguments -- callbackfn and thisArg.

In fact, any funcall with functional argument tab-completes into a call with more arguments then it should be.

Expected behaviour would be completion to
```ts
arr.map(callbackfn, thisArg)
```

**Comment by jrieken** [comment]
@bpasero Please do not assign JS or TS issues to me

**Comment by bpasero** [comment]
@jrieken this should be documented in the inbox tracking page if there is a rule. I asked @dbaeumer and he told me that @waderyan should get them, so I updated the wiki.

**Comment by waderyan** [comment]
@yhaskell thanks for opening this. Good find! I believe this is a TypeScript Service issue so moving to them.

**Comment by waderyan** [comment]
It looks like we are folding the paramaters of the call back up to the map method. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

![image](https://cloud.githubusercontent.com/assets/2449568/18480811/e7ac7cea-798e-11e6-8ad8-d9262f3002ca.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10896
