### ISSUE TITLE
Builtin Markdown extension does not respect editor.wordWrap/editor.wordWrapColumn settings

### ISSUE THREAD

**Issue by xiata** [microsoft/vscode#119262]
Issue Type: <b>Bug</b>

1. Apply these settings in your settings.json:
```
"editor.wordWrap": "wordWrapColumn",
"editor.wordWrapColumn": 100,
"editor.rulers": [ 100 ],
```
2. Open a markdown file, e.g. README.md
3. Write this line: 
```
This is some text that will cross the ruler which we have set to 100 characters. This should wrap at this point.
```
4. Toggle word wrapping on and off.
5. Notice that it did not wrap at 100 characters, as specified by `editor.wordWrapColumn` setting.
6. Edit the line so it extends beyond the right edge of the view port.
7. Toggle word wrapping on and off.
8. Notice it wraps at the edge of editor viewport instead of the `editor.wordWrapColumn` setting.
9. Change language of file to `Plain Text`.
10. Toggle word wrapping on and off.
11. Notice it wraps at the 100 character mark instead of the viewport, respecting user configuration.

Word wrap, with a wrap to column value, should always be respected. Users can turn off word wrapping for specific languages when it makes sense to do so.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id b1f4fe7d-1c9f-4299-964b-19ef3dc69a94|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
vscode-intelephense-client|bme|1.6.3
ndjson-colorizer|bus|1.0.0
postcss|css|1.0.9
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
php-debug|fel|1.14.9
vsliveshare|ms-|1.0.3968
react-proptypes-intellisense|OfH|1.0.3
vscode-jest|Ort|3.2.0
vscode-sanity|san|0.1.4
sass-indented|syl|1.8.16
errorlens|use|3.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
Try using a language specific setting:

```js
  "[markdown]": {
    "editor.wordWrap": "wordWrapColumn"
}
``` 

Markdown provides a default language specific setting so you must specifically override it using your own language setting

**Comment by xiata** [comment]
Markdown should not have a default setting that overrides the user's setting by default.

That information is not conveyed **anywhere** in settings which is an extremely poor experience for the user. I personally wouldn't have wasted time filing this ticket otherwise since when a user specifies a setting, the default behavior is that it would be respected everywhere unless the user **themself** wrote an exception to the rule.

**Comment by mjbvz** [comment]
See #74195
