### ISSUE TITLE
#3 on keypad opens up a delete request window

### ISSUE THREAD

**Issue by j9haslett** [microsoft/vscode#119284]
when I press 3 on the keypad (not the number row on top, just the keypad to the right), it opens up a window on top that says, "select a branch to delete". It's some kind of a shortcut or something. I'm not sure how it happened, but it is a problem because I use the keypad all the time and after I press 3, anything I type afterwards ends up in the window. I have to watch it all the time because if I press enter, things get deleted.

**Comment by AUnicornWithNoLife** [comment]
if you go to preferences, then keybinds, you can search for delete branch. you can then change the keybind

**Comment by gjsjohnmurray** [comment]
See also https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `numpad3`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`numpad3`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by j9haslett** [comment]
[2021-03-23 10:12:15.760] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Numpad3, keyCode: 34, key: PageDown
[2021-03-23 10:12:15.761] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Numpad3, keyCode: 12 ('PageDown')
[2021-03-23 10:12:15.762] [renderer1] [info] [KeybindingService]: | Resolving PageDown
[2021-03-23 10:12:15.762] [renderer1] [info] [KeybindingService]: \ From 5 keybinding entries, matched cursorPageDown, when: textInputFocus, source: built-in.

**Comment by gjsjohnmurray** [comment]
> [KeybindingService]: \ From 1 keybinding entries, matched git.deleteBranch, when: no when condition, source: user

This shows that the key is bound to that command. If you don't want it to be, remove the setting.

**Comment by alexdima** [comment]
@j9haslett You can open up your `keybindings.json` file using `F1 > Preferences: Open Keyboard Shortcuts (JSON)` and remove/review/edit the contents such that you remove this keybinding of `Numpad3` to `git.deleteBranch`.
