### ISSUE TITLE
Help users use the search viewlet by providing a contextual reference 

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119263]
The basic idea is to use the existing error/warning/info popups but also for regex and blob syntax references: 

![image](https://user-images.githubusercontent.com/2193314/111657064-54274200-87c8-11eb-89e5-49e090c0ad25.png)

If we did start using this UI element more we should consider how it can obscure the content/inputs underneath. A possible solution to this is to use `pointer-events: none` and then either hide it or set a low opacity on mouse hover. We could also link this to my proposal in https://github.com/microsoft/vscode/issues/115034#issuecomment-767592803 where ctrl+hover will force hovers not to hide and allow interaction.

This would help with the placeholder contrast issue and allow us to hide information when it's not relevant:

<img width="326" alt="Screen Shot 2021-03-18 at 9 09 36 AM" src="https://user-images.githubusercontent.com/2193314/111658544-aae14b80-87c9-11eb-8f32-4bef182e8d6e.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/121925
