### ISSUE TITLE
Source control pane no longer remembers which repos were closed

### ISSUE THREAD

**Issue by x6herbius** [microsoft/vscode#119276]
- VS Code Version: 1.54.3
- OS Version: Windows 10

For a while now (I think since sometime last year), the source control pane has stopped remembering which repos have been closed manually, and brings up all of the repos in my workspace up whenever I start the program. This is annoying since all of these are Git subrepos, so I only ever need to commit to the very first one in the list. The lower ones also have a habit of stealing focus when I'm trying to write a commit message (though not in a consistent enough way for me to be able to write a bug report about it yet). I have to close all the subrepos in the list manually each time I start the application.

I personally classify this as a bug since it seems like state that used to be remembered is now forgotten, but it's possible that the behaviour change could have been a natural consequence of a recent feature.

Steps to Reproduce:

1. Open a Git repo with one or more subrepos.
2. Go to the source control pane. All subrepos should show up.
3. Close all but the first in the list.
4. Close and re-open VS Code.
5. All subrepos will reappear in the source control pane.

Does this issue occur when all extensions are disabled? Yes

**Comment by gjsjohnmurray** [comment]
The focus stealing sounds like #116930

**Comment by x6herbius** [comment]
Yeah, it could well be that one.

**Comment by x6herbius** [comment]
Just to clarify - is this considered a duplicate because of the mention of #116930? Because although that's a ticket about behaviour that's referenced by this one, it's not the core issue as described here.
