### ISSUE TITLE
multiline string break colouring

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1192]
![screen shot 2015-12-11 at 11 44 03](https://cloud.githubusercontent.com/assets/1794099/11741951/8aed44c4-9ffc-11e5-8738-03478944eebf.png)

**Comment by aeschli** [comment]
@jrieken please include a snippet of the source code that shows the problem

**Comment by jrieken** [comment]
```javascript
var a = "fdfff\n\
sss/*";

console.log('I am not a comment');
```

**Comment by aeschli** [comment]
I verified that this is an issue of the grammar and not our textmate engine.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#26
