### ISSUE TITLE
Bug Report: Jupyter Data Viewer Filter will generate duplicated data in the viewer

### ISSUE THREAD

**Issue by znzhao** [microsoft/vscode#119271]
When there are many columns and many rows in the data (for example in the sample data I have more than 50 columns and more than 5000 rows), using the filter in the data viewer will display a wrong line of duplicated data.
Screenshot:
When using the filter (looking up for ID = 1):
![image](https://user-images.githubusercontent.com/46983185/111668911-44b5f200-87e4-11eb-9555-7e3f2a4624fc.png)
 Actually, the data in line 1852 is:
![image](https://user-images.githubusercontent.com/46983185/111669127-76c75400-87e4-11eb-93eb-c66fd8dbc31f.png)

The bug can be replicated by the following file:
[testbug.zip](https://github.com/microsoft/vscode/files/6166045/testbug.zip)

The Python extension version that I use: v2021.3.658691958
VS code Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by joyceerhl** [comment]
Issue moved to [microsoft/vscode-jupyter #5200](https://github.com/microsoft/vscode-jupyter/issues/5200) via [**ZenHub**](https://www.zenhub.com/)
