### ISSUE TITLE
JS debug terminal broke when we merged in quick profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119283]
![recording (1)](https://user-images.githubusercontent.com/2193314/111698686-5bfcdb80-87f4-11eb-8e3c-08ae2b0029af.gif)

fyi @connor4312

**Comment by TylerLeonhardt** [comment]
This seems to just open my default shell:
![image](https://user-images.githubusercontent.com/2644648/112534626-83a9f180-8d68-11eb-97b1-908ce9ddef63.png)

FWIW, I think I've seen this bug before profiles were a thing.

**Comment by Tyriar** [comment]
@TylerLeonhardt  that's right, it should attach a debugger when you run a node program though:

![image](https://user-images.githubusercontent.com/2193314/112537286-be615900-8d6b-11eb-8270-70bf26d9d5b0.png)
