### ISSUE TITLE
Feature Request: File->Print

### ISSUE THREAD

**Issue by sbscomp** [Microsoft/vscode#11922]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:
Open the File Menu

Expected Result:
There is an option to print the currently open buffer.

Actual Result:
No option to print.

Why it's important:
Sometimes, you have a need to print some code out - either as a reference, or to aid in debugging, or for other reasons.

It's rather disappointing to not find a "print" option in the editor.

**Comment by catchmyfame** [comment]
Isn't this a dupe of https://github.com/Microsoft/vscode/issues/5953?
