### ISSUE TITLE
Allow extensions to be easily hooked with error reporting service (Sentry or similar)

### ISSUE THREAD

**Issue by JiriTrecak** [microsoft/vscode#119266]
Currently, we were not able to find any way how to integrate the extension host with our own crash reporting. This is problematic because any more complex extension (especially if it is a core business component) needs proper software tools such as reporting - I believe this is not just our problem, but could potentially prevent large companies from making their own plugins where they can't guarantee a certain level of quality and stability. 

In this regard, we would love to have the ability to use Sentry or a similar service to observe crashes happening in both the language server (if present) and in the client extension. The only current workaround we are able to think of right now is to try to cover all entry points (ie. autocomplete callbacks, all user actions, all commands, etc.) with try/catch and report to the loggers manually. Unfortunately, that is both tedious and in many cases can't provide a full picture of what was happening.

Sidenote: IF there isn't any way how to do that, then this feature request is at least to cover this topic in the extension documentation, with suggested workarounds.

Keep up the great job, VSCode is a fantastic project.

Sincerely

Jiri
Supernova.io

**Comment by dbaeumer** [comment]
For LSP there is a middleware layer through which all requests go. There is also a single method through which all failed requests go `handleFailedRequest` which you could override in a subclass.

**Comment by riotrah** [comment]
Could you explain what Sentry isn't able to do for you already in your extension?

I'm currently working on an extension with an LS as well, and with Sentry, the default breadcrumbs for http requests and console statements, plus unhandled rejections/exceptions seems to work. 

However, we're having an issue with the console integration picking up statements from other extensions, and the unhandled error handlers reporting on errors from other extensions - not sure why/how. Is that your challenge?
