### ISSUE TITLE
Notebook Markdown cell does not render image

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#119280]
@CIA-Trash commented on [Thu Mar 11 2021](https://github.com/microsoft/vscode-jupyter/issues/5133)

## Environment data

-   VS Code version: Version: 1.55.0-insider (Universal); Commit: 11d5e82c80c6151e3f6d9da10429582b589c16ba
-   Jupyter Extension version: v2021.4.641214696
-   Python Extension version: v2021.4.637492490-dev
-   OS and version: macOS 11.2.1 (20D74)
-   Python 3.7.9
-   conda 4.9.2
-   Jupyter server running: Local

## Attempt 0

<img width="821" alt="Screen Shot 2021-03-12 at 14 17 33" src="https://user-images.githubusercontent.com/37474731/110877205-ebf6dd00-833d-11eb-896e-b1f88229a04e.png">

### Expected behaviour

The line here should render a image.

### Actual behaviour 

However, the image is not rendered
<img width="1001" alt="Screen Shot 2021-03-12 at 14 20 02" src="https://user-images.githubusercontent.com/37474731/110877381-2fe9e200-833e-11eb-8e05-bb16e5aeca67.png">

## Attempt 1

I also tried the markdown way
<img width="848" alt="Screen Shot 2021-03-12 at 14 33 48" src="https://user-images.githubusercontent.com/37474731/110878442-15b10380-8340-11eb-9648-574610d6e805.png">

### Expected behaviour

This is what it should look like, the screenshot is taken from vscode stable build
<img width="553" alt="Screen Shot 2021-03-12 at 14 36 41" src="https://user-images.githubusercontent.com/37474731/110878599-5f015300-8340-11eb-905e-12cf131d78da.png">

### Actual behaviour
But insider build renders it like this
<img width="676" alt="Screen Shot 2021-03-12 at 14 38 12" src="https://user-images.githubusercontent.com/37474731/110878725-94a63c00-8340-11eb-9465-db42d28848e3.png">

**Comment by mjbvz** [comment]
Both styles of images seem to work fine for me. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

If not, can you please share a small project that demonstrates this

**Comment by CIA-Trash** [comment]
> Both styles of images seem to work fine for me. Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?
> 
> If not, can you please share a small project that demonstrates this

Yes, this only happens to insiders build. 
The stable build is fine.

**Comment by mjbvz** [comment]
Looks like you're on an old insiders build though. Make sure you are on commit 111a6cec70f9562cdd31a5fd8cdea4b3a9b7bd82

**Comment by CIA-Trash** [comment]
Danke, all looks good now

**Comment by mjbvz** [comment]
Thanks for checking. Let us know if see this again with latest insiders
