### ISSUE TITLE
Ask to reload codespace on resume

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#119332]
I just resumed a codespace and I get:

![image](https://user-images.githubusercontent.com/4674940/111798347-3836a580-8887-11eb-821c-8af587385ac5.png)

This is highly unexpected. I'm guessing what's happening is that setting sync brings in a value that requires us to reload the window.

**Comment by sandy081** [comment]
Yeah I see how ugly it is, but I am not sure how settings sync can handle this unless it knows the setting that is getting changed required reload or restart. It requires to wire in all this info and show a notification & badge (like conflict) so that user can accept the change and reload.
