### ISSUE TITLE
Test new markdown renderers in notebooks

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#119367]
Refs #116393

- [x] Mac @jrieken
- [x] Linux @roblourens
- [x] Windows @RMacfarlane

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119367%0A%0A)

---

## Background 
With #116393, we've made the markdown renderer in notebooks extensible so that we can add support for math and other markdown syntax. To enable this, we had to completely change how markdown is rendered in notebooks. The main change is that markdown cells are now rendered inside of the back layer webview instead of inside the main workbench dom

## Testing
This is an exploratory test plan item to catch potential regressions caused by the changes.

Start by setting `"notebook.experimental.useMarkdownRenderer": true` to force the new markdown renderer to be used by default for all notebooks. You can confirm the new render is being used by entering `:smile:` in a markdown cell. With the new renderer, this should be rendered as 😄 

Using both the GitHub issues and jupyter notebooks extensions, explore some of the following scenarios to see if there is any unexpected behavior or regression:

* Basic editing. Make sure you can edit markdown cells

* Keyboard navigation and keyboard shortcuts. Confirm you can still use 

* Cell drag and drop

* Make sure the state is correctly restored after reloading the window and reopening the notebook

* Accessibility. When screen reader mode is enabled, make sure the new renderer is NOT used

**Comment by jrieken** [comment]
fyi and if that matters: I did all my testing with `"webview.experimental.useIframes": true` since my understand is that that's where we are heading at

**Comment by roblourens** [comment]
Accessibility - do you mean `editor.accessibilitySupport`? The new renderer is still used when I set that to "on", although I don't actually have a screen reader installed on this linux machine.

**Comment by mjbvz** [comment]
@roblourens Yes I believe so. Make sure to restart after enabling it

**Comment by roblourens** [comment]
Yeah, vscode prompted me to restart

**Comment by Chisomo-Chiweza** [comment]
Do we set this by typing it in settings.json?
