### ISSUE TITLE
Mac: Keybinding conflicts detected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1193]
With latest I see this:

Conflict detected, command `cursorBottom` cannot be triggered by cmd+down
//Users/bpasero/Development/monaco/out/vs/platform/keybinding/common/commonKeybindingResolver.js:70 Conflict detected, command `cursorTop` cannot be triggered by cmd+up
//Users/bpasero/Development/monaco/out/vs/workbench/services/thread/electron-browser/threadService.js:196 [Plugin Host] debugger listening on port 5870
//Users/bpasero/Development/monaco/out/vs/platform/keybinding/common/commonKeybindingResolver.js:70 Conflict detected, command `cursorBottom` cannot be triggered by cmd+down
//Users/bpasero/Development/monaco/out/vs/platform/keybinding/common/commonKeybindingResolver.js:70 Conflict detected, command `cursorTop` cannot be triggered by cmd+up

**Comment by alexandrudima** [comment]
@jrieken pushed a fix for this default keybinding conflict
