### ISSUE TITLE
Fail to download VSCode

### ISSUE THREAD

**Issue by CathyCathyFan** [microsoft/vscode#119317]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Click download link from VSCode website and the download timed out
2. The link is https://az764295.vo.msecnd.net/stable/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/VSCodeUserSetup-x64-1.54.3.exe 

Does this issue occur when all extensions are disabled?: N/A

**Comment by joaomoreno** [comment]
@CathyCathyFan Where in the world are you? Is this still happening? What tool/browser are you using to download the url?

**Comment by CathyCathyFan** [comment]
Thank you, @joaomoreno . I finally get this downloaded. Probably due to network issue.
