### ISSUE TITLE
.then help

### ISSUE THREAD

**Issue by IBZx7x** [microsoft/vscode#119387]
Issue Type: <b>Bug</b>

I had a ".then" statement, and visual studio code says it is wrong. So instead, I wrote "then". The JS console says Visual Studio is wrong and said "then" is not defined.
Visual Studio error: Expected identifier before statement
Console Error: "then" is not defined

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
Please share a code example that demonstrates this issue
