### ISSUE TITLE
Auto rename HTML tag in all frameworks

### ISSUE THREAD

**Issue by AbdulSamadMalik** [microsoft/vscode#119399]
Issue Type: <b>Feature Request</b>

Dear VS Code Team, please  add support for  auto rename HTML tag and highlighting in all frameworks as it was added in HTML, Thank you. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19043

**Comment by aeschli** [comment]
What do you mean `in all frameworks` ? Examples?

**Comment by AbdulSamadMalik** [comment]
I mean it works fine in HTML tags but not in JSX tags in React

**Comment by aeschli** [comment]
See https://github.com/microsoft/vscode/issues/85707
