### ISSUE TITLE
Replace the no-update dialog box with a pop-up notification

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#119310]
I suggest making a message about the lack of updates for vs code in the form of a pop-up notification, as it is done for extensions. It's annoying to press the "OK" button every time
![image](https://user-images.githubusercontent.com/75433721/111764986-6b545580-88d6-11eb-94ee-69a1950ae617.png)

**Comment by joaomoreno** [comment]
Actually this was a purposeful decision, since it's a message due to an explicit user action: it should be a dialog, not a notification.

**Comment by AlexDev2020** [comment]
> Actually this was a purposeful decision, since it's a message due to an explicit user action: it should be a dialog, not a notification.

Why is there no dialogue when we check for updates for extensions?

**Comment by joaomoreno** [comment]
@sandy081 I remember we already had that discussion.
