### ISSUE TITLE
Notification center buttons (clear list, chevron) not working on latest Insiders

### ISSUE THREAD

**Issue by devinvalenciano** [microsoft/vscode#119331]
Version: 1.55.0-insider (user setup)
Commit: e4b1e9ac57ab3cc942ab9bff09967bf3238a7910
Date: 2021-03-19T05:14:28.175Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open notification center by clicking bell in status bar (with or without notifications present).
2. Try to use "Clear Notifications" or the chevron button in the notification center - it currently does not work.

![recording (2)](https://user-images.githubusercontent.com/1389808/111797595-87c8a180-8886-11eb-83c8-7c8e65621eb7.gif)
![recording (3)](https://user-images.githubusercontent.com/1389808/111797612-8ac39200-8886-11eb-9b5e-3d63e48d075e.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
GH is so parallel!

**Comment by isidorn** [comment]
ahahah

**Comment by isidorn** [comment]
Let me first investigate if it was my change

**Comment by bpasero** [comment]
Ok

**Comment by bpasero** [comment]
Nice talking to you here btw 👍

**Comment by isidorn** [comment]
Yeah, better than Clubhouse

**Comment by isidorn** [comment]
@devinvalenciano great catch!
@bpasero I was actually breaking it.
