### ISSUE TITLE
Add support for recording double modifier keypress

### ISSUE THREAD

**Issue by ganeshramc** [microsoft/vscode#119361]
In Intellij to do a symbol search (file/class/variables/etc.) the typical key binding is "shift+shift" but vscode does not allow to do double shift. I see it allows double backspace but not double shift. Would love if this combo is introduced, so i can use the same shortcuts I use in IntelliJ.

Here's a sample recording:

https://user-images.githubusercontent.com/15274817/111846316-c16bcd80-88c3-11eb-99b7-194f008ba50b.mov

Shift + Shift does not work but backspace + backspace does

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/pull/115190 suggests this should already be possible in 1.54. What version are you using, and on which platform?

**Comment by ganeshramc** [comment]
This is the version I'm using. I'm on MacOS
```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by ArturoDent** [comment]
You can make a keybinding manually by using `"key" : "shift shift"`  (note no `+` between them.  That will work.  

But it seems that the `Add Keybinding...` widget should work to enter a quick <kbd>Shift</kbd> <kbd>Shift</kbd> , but doesn't. Same with the other doubled keys: Alt, Ctrl, Win, etc.

**Comment by alexdima** [comment]
:+1: . The keybinding `"shift shift"`, `"alt alt"`, etc. can be added manually in `keybindings.json`, but not yet using the widget.
