### ISSUE TITLE
Support JSDoc @link tags 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#119357]
Tracks the VS Code side of https://github.com/microsoft/TypeScript/issues/35524

This would include supporting `{@link}` tags in hovers, completions, and quick info

**Comment by mjbvz** [comment]
For verification: 

1. make sure you are using TypeScript@next in your workspace: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

1. Try creating a few simple js functions/classes and using `{@link symbolName}` in jsdoc comments to reference them. Confirm this produces clickable links in: intellisense, parameter hints, and hovers

**Comment by jrieken** [comment]
Using TS 4.3.0-dev.202104017 and adding adding links in [vscode.proposed.d.ts](https://github.com/microsoft/vscode/blob/5688d75ef95fce42ede3c0212670e9fb0ed67290/src/vs/vscode.proposed.d.ts#L1576) but I don't get this to work... Only http-links seem to work, this is my sample

```ts
/**
		 * An array of language identifiers that are supported by this
		 * controller. Any language identifier from {@link NotebookController} [`getLanguages`](#languages.getLanguages)
		 * is possible. When falsy all languages are supported.
		 *
		 * {@link http://www.sne.ch }
		 * {@link viewType }
		 * {@link vscode.notebook }
		 *
		 * Samples:
		 * ```js
		 * // support JavaScript and TypeScript
		 * myController.supportedLanguages = ['javascript', 'typescript']
		 *
		 * // support all languages
		 * myController.supportedLanguages = undefined; // falsy
		 * myController.supportedLanguages = []; // falsy
		 * ```
		 */
		supportedLanguages?: string[];
```

**Comment by mjbvz** [comment]
Thanks @jrieken. This is a TS bug: https://github.com/microsoft/TypeScript/issues/43868

Let me know if you come across any other cases that do not work with this feature. To verify basic `@link` support, you can use:

```ts
class Foo {
    /** {@link Foo} */
    bar(): void {}
}
```

**Comment by connor4312** [comment]
Super cool, found one annoying bug but this'll make life a lot easier.
