### ISSUE TITLE
Flaky test: onTitleChanged event is fired by the process on creation (Linux & OSX):

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11930]
Seeing this in one build:

```
1 failing
  1) Workbench - TerminalInstance TerminalInstance - onTitleChanged event is fired by the process on creation (Linux & OSX):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
```

Refs: https://travis-ci.org/Microsoft/vscode/jobs/159423971#L3903

**Comment by bpasero** [comment]
@Tyriar I commented out the failing test for now. I also noticed many warnings in that file.

**Comment by Tyriar** [comment]
Thanks, I'll look at this tomorrow. Not sure why it let me commit it with the warnings though.
