### ISSUE TITLE
git pane list repos of hidden folders when other vscode window open the hidden folder

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode#119389]
- VS Code Version: 1.52.1
- OS Version: Windows 10.0.19042.0

Steps to Reproduce:

1. should exist a folderA without git repo that contains (at n hierarchical level) a folderB with a git repo
2. create folderA.code-worksapce with "files.exclude": {"folderB": true}
3. open one vscode windows with folderA.code-worksapce 
4. open other vscode window at the folderB
4. at folderA.code-worksapce  window, the git pane will list folderB (or any other repo at descendent folder from folderA )

My concreate case is that I created a dotfiles.code-worksapce to edit my dotfies at my home folder. Then, although I hide all subfolders, the git pane list descendent repos.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
I think the best option here would be turn turn off repository searching in your workspace file settings. Try setting `git.autoRepositoryDetection` to `false` or `openEditors`

**Comment by alanlivio** [comment]
Thanks @eamodio. It worked.
