### ISSUE TITLE
Images in hover preview are broken with vscode 1.53/1.54

### ISSUE THREAD

**Issue by svsool** [microsoft/vscode#119384]
- VS Code Version: 1.54.3
- OS Version: macOS 11.2.1

Does this issue occur when all extensions are disabled?: Yes/No

Hi, I'm dev of [vscode-memo](https://github.com/svsool/vscode-memo) extension and noticed that images are no longer rendered in hover preview in latest versions, it used to work in 1.52 version though.

This is how it looks in 1.54 (should show backlinks panel image on link hover instead of broken image icon):

![image](https://user-images.githubusercontent.com/1452141/111870271-5c2fdf00-898c-11eb-8ca8-1d91155d77c6.png)

When I try to open img src by copying it from DevTools (notice that network tab shows this src in red and status = cancelled) directly in Chrome, it opens just fine and shows an image, so path is valid at least.

![image](https://user-images.githubusercontent.com/1452141/111870369-03147b00-898d-11eb-85df-2ab040cd15cd.png)

This is how it used to look in 1.52:

![image](https://user-images.githubusercontent.com/1452141/111870223-183cda00-898c-11eb-9afa-253a375dc881.png)

Related code: https://github.com/svsool/vscode-memo/blob/92e869c81d4ce9906564438eec8af242ff644c85/src/features/ReferenceHoverProvider.ts#L56

Steps to Reproduce:

Install [vscode-memo](https://github.com/svsool/vscode-memo) (ensure to choose "install another version" = 0.3.3, 0.3.4 has a patch to disable hover functionality 😞) and open [help](https://github.com/svsool/vscode-memo/tree/master/help) folder as workspace and hover any image link for instance inside `Embed files.md`.

Any ideas what's changed?

Related issue: https://github.com/svsool/vscode-memo/issues/306

**Comment by svsool** [comment]
It seems that img src did not change between versions.

This is screenshot with 1.52:

![image](https://user-images.githubusercontent.com/1452141/111870721-ff81f380-898e-11eb-88af-f249ddd2c1e3.png)


And 1.54:

![image](https://user-images.githubusercontent.com/1452141/111870752-36580980-898f-11eb-9776-0c72891254c3.png)

So I wonder why image load is cancelled in 1.54, maybe some CSP related changes were done? 🤔 

![image](https://user-images.githubusercontent.com/1452141/111870825-8afb8480-898f-11eb-8716-f35381968526.png)

**Comment by BettyJJ** [comment]
I've come to report the same problem. I have another extension that shows images in hover preview. It used to work in 1.52 and it is broken now in 1.54. (I skipped 1.53 so don't know about that version.)
PS: net images are ok. only local images are broken.
The syntax that used to work is
```
![](file://path/to/the/image.png)
```
In 1.54, I've tried `file:///` `file:/` and without the `file:` path, all failed.

**Comment by deepak1556** [comment]
@bpasero same root cause as https://github.com/microsoft/vscode/issues/118623

```
[error] file: Refused to load resource /Users/demohan/github/vscode-memo/help/Attachments/Backlinks panel.png from file: protocol (original URL: file:///Users/demohan/github/vscode-memo/help/Attachments/Backlinks%20panel.png)
```

**Comment by svsool** [comment]
Thanks for linking it here. 👍 

> Right now the workaround is to copy those files using NodeJS copyFile() into extension directory. Is sandboxing endgame going to prevent me doing that?

Seems that copying the whole workspace to the extension folder isn't a solution in case of vscode-memo 😅, so good if it can be fixed a proper way.

And it would be great to see such things mentioned in breaking changes in the update notes.

**Comment by svsool** [comment]
Any alternatives other than copying images to extension directory?

**Comment by bpasero** [comment]
As part of https://github.com/microsoft/vscode/issues/92164 we also look into stricter rules for what kind of files are allowed to be loaded into our product. Limiting files to load to the application folder itself, the data folder and the extensions directory seems like a sensible choice for an application so we went with that. If you need to load images into VSCode from an extension, then these should be provided from the extension itself.

**Comment by svsool** [comment]
Thanks for the answer and providing more context.

Security is great, what it does to product does not sound that great though. It would be nice loading images from the workspace, not extension. Most of the extensions without workspace are useless. I still see no reason why workspace with images solely would be an untrusted thing in Electron. VS Code allows opening images in separate tabs from workspace, hover shouldn't be an exception in my opinion.

**Comment by BettyJJ** [comment]
At least loading files from the current workspace should be allowed. I mean, security is great and all, but forbidding loading files from the current workspace the user is working in just does not make sense.

**Comment by bpasero** [comment]
> I mean, security is great and all, but forbidding loading files from the current workspace the user is working in just does not make sense.

Just to clarify: we are talking about allowing files to load / coexist in the same context / process as the core VSCode runs which has access to the entire node.js API, can do anything on behalf of the user purely by being displayed. If there is a non-disclosed security issue with loading an image in the window / hover (which is pretty much a Chrome renderer) every VSCode user is immediately potentially impacted just by hovering and by opening a workspace that contains such a malformed image.

**Comment by BettyJJ** [comment]
If I understand correctly, this new restriction can't prevent extensions from copying the malformed image to the extension folder and displaying it, right? Not to mention other much worse things extensions can do...

**Comment by bpasero** [comment]
Yes you are right, as soon as a user has installed an extension the extension can pretty much do anything on behalf of the signed in user, so the users machine is compromised from that moment. 

Unfortunately the filtering of which files can be loaded into the core context does not know about extensions it is on a very high level simply blocking access:

https://github.com/microsoft/vscode/blob/eb21069624c0996f8c985b2ab8c5552be83ceff0/src/vs/code/electron-main/protocol.ts#L44-L44

As such we can currently not distinguish if a file is loaded because an extension added it or because of a different issue that can be a possible attack not involving any extension installation.

Given how easy it is for an extension to copy an image to the extension location for usage, is that not an option to enable loading custom images? What is the scenario here for loading workspace images into the core workbench? I think I missed that part.

**Comment by svsool** [comment]
> What is the scenario here for loading workspace images into the core workbench? I think I missed that part.

With memo this scenario used to be the following:

![Notes and images preview](https://user-images.githubusercontent.com/1452141/112277145-1f186500-8c8a-11eb-96c5-e74e2cffd4e6.gif)

User can hover a link to an image in workspace and see an immediate preview, pretty common thing for the knowledge bases.

**Comment by bpasero** [comment]
Thanks for the screen recording, that seems like a good feature to have and it would not make a lot of sense to ask the extension to copy these images over, I agree.

On the other hand, I wonder if we need to isolate the hover better and use a similar approach as we do for when an extension has full control over the HTML contents (as in this case the markdown preview does have full support for HTML). E.g. put the hover into a little `iframe` and load the image there. 

Reopening for now to think about solutions.

**Comment by bpasero** [comment]
We discussed this in the team and decided to push a tactical fix: we now allow image extensions to load even if they end up in the same context as the core window.

**Comment by bpasero** [comment]
**Verification**

1. Clone https://github.com/svsool/vscode-memo
2. `yarn`
3. comment out the line that reads `Image preview is currently not supported`
4. Run 
5. open a markdown document with a reference to a PNG in the workspace
6. retype it as `memo` notation (e.g. `[[images/1_54/macOS-universal-download.png]]`)
7. hover over it

**Comment by svsool** [comment]
Thanks @bpasero for a quick fix! 🚀

**Comment by BettyJJ** [comment]
Thank you so much! You are the best! 🤩
