### ISSUE TITLE
VS Code Task with CustomExecution blocks other other tasks

### ISSUE THREAD

**Issue by a1exwang** [microsoft/vscode#119311]
- VS Code Version:

```
1.54.3
2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
x64
```
- OS Version: Ubuntu 20.04.1

Steps to Reproduce:

Video to reproduce:

https://user-images.githubusercontent.com/9698542/111767916-3c43e100-88e2-11eb-924e-8b5ee7018a1d.mp4

1. Clone this [vscode example repo](https://github.com/microsoft/vscode-extension-samples/tree/ee16257d90f4a23f7bc45274ffc72c942e00b0de/task-provider-sample)

2. Create another directory with these two files. Let's call this directory "sample-code"

sample-code/.vscode/tasks.json
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "wont-finish-task",
            "dependsOn": [
                "custombuildscript2",
                "echo-task"
            ],
            "dependsOrder": "sequence"
        },
        {
            "label": "custombuildscript2",
            "type": "custombuildscript",
            "flavor": "64",
        },
        {
            "label": "echo task",
            "type": "shell",
            "command": "echo hello",
        }
    ]
}
``` 

sample-code/.vscode/launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome",
            "type": "pwa-chrome",
            "request": "launch",
            "preLaunchTask": "wont-finish-task",
            "url": "https://www.google.com",
        },
    ]
}
```

3. Launch debug of the sample extension project and open the "sample-code" directory. It will launch another instance of VS Code

4. Launch debug in the newly opened VS Code instance. It will stuck on the "custombuildscript2" task. However you can see the task has already finished, from the terminal.
    - If you comment out this task, the browser can be opened normally.
    - If you register this task with "background = true" and write a ProblemMatcher and use a pattern to match the end of task, the task won't stuck.
```
        "background": {
          "activeOnStart": true,
          "beginsPattern": ".*",
          "endsPattern": "^.*some end pattern.*"
        }
```

Does this issue occur when all extensions are disabled?: Don't know how to use this with the extension debugger

**Comment by alexr00** [comment]
This is actually a bug in the Custom Execution task sample! A task should fire a close event of 0 to signal that it has completed successfully (a bit weird, but needed since this is normal for terminal processes).
