### ISSUE TITLE
Cannot use 'Enter' to move between search results

### ISSUE THREAD

**Issue by rectified95** [microsoft/vscode#119362]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Press `Ctrl+f`
2. Type a string to search that has occurrences in the current file.
3. Press `Enter` to move to subsequent search results.

Expected behavior - can move between string occurences using `Enter` and `Shift+Enter`
Actual behavior - pressing `Enter` doesn't accomplish the above, even though it did quite recently.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.21322

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-flow-ide|gca|1.2.0
devinsights|Mic|2021.2.19-1
tdpcode|Mic|1.6.4
vscode-nmake-tools|Mic|2.0.200218004
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833:30267464
vsdfh931:30270786

```

</details>

**Comment by roblourens** [comment]
Are you sure you don't have a conflicting keybinding?
