### ISSUE TITLE
JSON Settings editor do not show remote settings

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#119316]
Compare the settings GUI:
![image](https://user-images.githubusercontent.com/30827238/111775146-a80d5600-88b0-11eb-83be-b735d7fc9370.png)

To the settings (JSON):
![image](https://user-images.githubusercontent.com/30827238/111775176-b196be00-88b0-11eb-8f17-17cf9da7f8ff.png)

As can be seen, the `Remote [SSH: vm]` is not visible in the JSON settings editor. But I want it to be. I prefer the JSON editor because of its superior overview of all settings.

**Comment by roblourens** [comment]
Unfortunately that editor is deprecated. You can still open the JSON file directly with the button in the settings UI editor

**Comment by thernstig** [comment]
@roblourens What  is meant by deprecated? It is still there and there is no note anywhere it is deprecated?

I remember the discussions where it was tried to remove the JSON settings editor in an inside release, and there was a huge backlash against that decision. We are many who like that more than the GUI. If you are not planning to actually remove it, how can it be deprecated? It was one of the greatest inventions when VS Code came and I do not think the entire community agrees the GUI editor is better.

**Comment by roblourens** [comment]
I probably won't remove it in the near future, but I don't have the capacity to maintain two settings interfaces so I don't plan to implement new features in it.

**Comment by thernstig** [comment]
That I understand. It is unfortunate though that it will not be maintained. Afaik this feature request is the only thing missing. But do all feature request require the core maintainers to be able to handle them, or why can they not stay open if someone wants to give it a go to send an MR?

**Comment by roblourens** [comment]
To be honest, I don't even want to take a PR for it, because that's still likely to lead to me spending more time maintaining this feature.

**Comment by thernstig** [comment]
If you do not have the capacity to maintain this, I feel there is another flaw somewhere if noone else can help maintain this. If the JSON editor is still used by many users, it feels sad it cannot evolve due to a single persons capacity issue. The same reasoning could be said about any feature that users like that if the current capacity is not enough, we will not continue to maintain it. I'm very saddened by this lack of understanding of UX and the principle that their are newbies (who might like GUI) and powerusers alike (that might like JSON editing).

This discussion has turned into something I wish it had not. Is there any chance a poll could be opened about the JSON editor to see what users feel about keeping it? I mean, let's pretend I am alone in this then I understand completely that there is no point in maintaining it anymore.

**Comment by roblourens** [comment]
Ideally we would remove it, I don't think there is any reason for us to maintain 3 separate settings editor experiences. My compromise is that I will leave it alone but not delete it for now.

**Comment by thernstig** [comment]
Could we create a petition for that, or involve some more VS Code developers/product owners in regards to this as I feel it is quite a big decision to remove a feature (and not maintain it) that many are using. I completely respect the work you do here, but I have a different opinion here that I do not think I am alone in, so it would be nice to nail down what users feel about this. If it turns out there is a huge user base for the JSON editor then possibly others could start help maintaining it.

**Comment by roblourens** [comment]
It's already been discussed, I'm not interested in revisiting it. I can tell you from telemetry that a tiny minority of users are using it.
