### ISSUE TITLE
minimap appears with scrollbar

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode#119390]
Issue Type: <b>Bug</b>

1. Enable minimap
2. Open some code
3. Observer both minimap and scroll bar

Desired berhavior: minimap replaces scroll bar.

Questions:

Why is the minimap shaded area the full length of the edit window and not just the length of the code?

What does the "T" symbol mean in the scroll bar?

Why is there both a minimap and a scroll bar?  Ideally want just one or the other, not both.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.25GB free)|
|Process Argv|--crash-reporter-id 982ba36c-2648-444f-a455-5d46c3de801b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.16
xml|Dot|2.5.1
gitlens|eam|11.3.0
code-runner|for|0.11.3
gc-excelviewer|Gra|3.0.41
mssql|ms-|1.10.1
vscode-postgresql|ms-|0.3.0
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-wsl|ms-|0.54.6
powershell|ms-|2021.2.2
partial-diff|ryu|1.4.1
vscode-hexdump|sle|1.8.1

</details>

**Comment by gbritton1** [comment]
![image](https://user-images.githubusercontent.com/12263288/111883883-61912780-8994-11eb-8c1f-a16e0b93ee01.png)

**Comment by gbritton1** [comment]
This issue is not covered in any of the issues found by the bot

**Comment by alexdima** [comment]
The scrollbar contains an overview ruler under it. The overview ruler represents the entire file and contains symbolic representations (boxes) for various interesting editor decorations. The overview ruler is split into 3 vertical areas. The left side shows SCM decorations (added lines, modified lines, etc.), the center side shows decorations like find results, highlighted occurrences (e.g. the brackets you're sitting on), the right side shows errors or warnings.

The horizontal line in the overview ruler is a cursor. You can have multiple cursors and they will each render a horizontal line. The rendering of cursors in the overview ruler can be disabled using `"editor.hideCursorInOverviewRuler"`.

The minimap has multiple modes. The default `"editor.minimap.size": "proportional"` implies that each editor line gets a certain amount of pixels, depending on DPI settings or on `"editor.minimap.scale"`. Under this default settings, it means that the minimap height is not restricted at the viewport height, so in a file with 2000 lines, it is possible that the minimap will be 4000px high. Under this mode, the minimap also scrolls. There are two other modes called `"editor.minimap.size": "fit"` which means that the minimap will use the same strategy until the viewport height is hit, at which point it will switch to sampling such that the minimap never scrolls. The final mode is called  `"editor.minimap.size": "fill"` which means that the lines in the minimap will also be stretched to occupy the entire viewport height.

There are other `minimap` settings and overview ruler settings, I recommend to experiment with them until you find something that works for you.
