### ISSUE TITLE
Outdated "Translations" section in the "How to Contribute" page in the wiki

### ISSUE THREAD

**Issue by Maxpxt** [microsoft/vscode#119396]
The link in [How-to-Contribute#Translations](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#Translations) (section reproduced below) in the wiki is broken. Also, shouldn't this section redirect readers to [vscode-loc](https://github.com/microsoft/vscode-loc)?

> We appreciate your localization contributions, either by providing new translations, voting on translations, or suggesting process improvements. We take translations through a community localization service, not through the vscode repo. See [our localization site](https://github.com/Microsoft/Localization/wiki) to get started.

**Comment by gjsjohnmurray** [comment]
I think this issue belongs at github.com/microsoft/vscode/wiki

**Comment by Maxpxt** [comment]
I does indeed. Opened it there (https://github.com/microsoft/vscode-wiki/issues/178).
