### ISSUE TITLE
Start vscode from binary will execute .zshrc more than once

### ISSUE THREAD

**Issue by lingsamuel** [microsoft/vscode#119302]
- VS Code Version: 1.54.3, 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, x64
- OS Version: Arch Linux Rolling, Linux 5.11.7-arch1-1 # 1 SMP PREEMPT Wed, 17 Mar 2021 16:59:58 +0000 x86_64 GNU/Linux

Steps to Reproduce:

1. close all vscode instances
2. Add this to `.zshrc`, it prints a counter variable:

```bash
echo "COUNTER: $ZSH_COUNTER"
export ZSH_COUNTER=$((ZSH_COUNTER+1))
```

3. start vscode by: `env -u ZSH_COUNTER /opt/visual-studio-code/code` (the path points to the vscode binary)

Then, the vscode terminal output shows that the counter is 1:
![image](https://user-images.githubusercontent.com/14567045/111754959-8a051d00-88d3-11eb-86a0-93b8aa27163a.png)

4. start vscode by: `env -u ZSH_COUNTER /opt/visual-studio-code/bin/code` (the path points to the vscode script)
or the equivalent command: `ELECTRON_RUN_AS_NODE=1 env -u ZSH_COUNTER /opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/cli.js`

The output shows that the counter is unset:
![image](https://user-images.githubusercontent.com/14567045/111754997-94271b80-88d3-11eb-81dd-26fa88ccba52.png)

(This step doesn't need to close previous vscode)

---
But if we start a "clean" vscode first, the env will keep clean even if we start other vscode from binary.

1. close all vscode instances. Start vscode by `env -u ZSH_COUNTER /opt/visual-studio-code/bin/code`
2. start second vscode by `env -u ZSH_COUNTER /opt/visual-studio-code/code`

The output shows that the counter is unset, too:
![image](https://user-images.githubusercontent.com/14567045/111755807-773f1800-88d4-11eb-965a-5ab44d00c06d.png)

---

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
You can read a little bit about why this is here: https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

The fix for this is to use the `"terminal.integrated.inheritEnv": false` setting, which unfortunately fails on some distros right now due to lack of permissions to the `/proc` file
