### ISSUE TITLE
Hover doesn't handle hr from markdown well

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119374]
![image](https://user-images.githubusercontent.com/2193314/111856054-664ad280-88e5-11eb-8e14-8bed026ac98f.png)

**Comment by Tyriar** [comment]
Caused by https://github.com/microsoft/vscode/issues/96795, @eamodio can you take a look at this? The fix does indeed look strange and you probably have more context on the issue.

To get the above screenshot I added some test markdown here:

https://github.com/microsoft/vscode/blob/4bcf96223a77c25ccd93813e2885e5f30c55a2f1/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L263

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/111856154-14567c80-88e6-11eb-8cc8-06baaf7e0a44.png)

**Comment by Tyriar** [comment]
Not sure what the original problem is, but I change this back to `min-width: 100%` and it looks fine:

<img width="938" alt="Screen Shot 2021-04-14 at 12 59 37 PM" src="https://user-images.githubusercontent.com/2193314/114771427-6215a780-9d21-11eb-9813-3062be895faf.png">

@eamodio I'm going to revert your fix, if it's still an issue in gitlens let's discuss the fix.

**Comment by eamodio** [comment]
I'll keep an eye on it

**Comment by connor4312** [comment]
verified in docker containers view

![](https://memes.peet.io/img/21-04-7166ef19-625d-476c-afcf-5708b8e4f6fe.png)
