### ISSUE TITLE
Intelisesnse loading bug

### ISSUE THREAD

**Issue by vlttnv** [Microsoft/vscode#11932]
- VSCode Version: Version 1.5.2
- OS Version: OSX 10.11.6 (15G31)

Steps to Reproduce:

1. Write in Python
2. Have the default Python extension installed
3. Grow old waiting for iltelisens to load suggestions

![screen shot 2016-09-13 at 10 09 29 am](https://cloud.githubusercontent.com/assets/867160/18464516/348b369a-799a-11e6-8535-dedba4a14705.png)

Sometimes it works and sometimes it doesn't. I haven't found a pattern. Maybe the size of the file where it usually happens (2000 lines).

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
