### ISSUE TITLE
Unknown first argument is passed to an extension's command when using keyboard entry point

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#119369]
Issue Type: <b>Bug</b>

## Repro Steps

1. Starting with a simple hello world extension, add the helloWorld command to a "view/title" navigation menu:

    ```json
    "contributes": {
        "commands": [
            {
                "command": "helloworld.helloWorld",
                "title": "Hello World"
            }
        ],
        "menus": {
            "view/title": [
                {
                    "command": "helloworld.helloWorld",
                    "group": "navigation"
                }
            ]
        }
    },
    ```

1. Add some code just so you can inspect the value of the first argument passed in to the command:

    ```typescript
    let disposable = vscode.commands.registerCommand('helloworld.helloWorld', (arg1) => {
        console.log(JSON.stringify(arg1));
        vscode.window.showInformationMessage('Hello World from helloworld!');
    });
    ```

1. F5 the extension and you should see hello world in the title bar:
    <img width="408" alt="Screen Shot 2021-03-19 at 6 11 47 PM" src="https://user-images.githubusercontent.com/11282622/111851491-5af5a800-88e1-11eb-9236-29f9e498b862.png">

1. Tab to the "Hello World" button and hit enter

## Expected:
The first argument is undefined (just like if I had clicked "Hello World" instead of used the keyboard)

## Actual:

The first argument is this JSON object:
```json
{"_standardKeyboardEventBrand":true,"browserEvent":{"isTrusted":true},"target":{},"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"keyCode":3,"code":"Enter","_asKeybinding":3,"_asRuntimeKeybinding":{"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false,"keyCode":3}}
```

It causes problems with some of our Azure extension commands because we don't expect that object. I know `registerCommand` doesn't make any guarantees about the type of arguments passed in to the command, but I couldn't find any VS Code API matching that object and I'm guessing you didn't mean to pass that along. We could adjust all of our commands to handle that object, or y'all could just pass undefined and fix it for us. 😊

VS Code version: Code - Insiders 1.55.0-insider (e4b1e9ac57ab3cc942ab9bff09967bf3238a7910, 2021-03-19T05:12:46.929Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 63154ab5-ba0e-419a-aa36-bd67d86db27f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
@sandy081 these menus shouldn't forward "random" arguments. Only types that are defined in the API should be used, mostly this is `Uri`.

**Comment by sbatten** [comment]
@sandy081 I think the original fix is a bit of a hammer. `MenuEntryActionViewItem` is overriding the `BaseActionViewItem`'s `onClick` but that `onClick` has the handling I think you might be looking for https://github.com/microsoft/vscode/blob/7031abadeafec54c8876231e3579c938dee6e1a5/src/vs/base/browser/ui/actionbar/actionViewItems.ts#L160-L165

**Comment by sandy081** [comment]
Thanks @sbatten for investigation. I should not have stopped forwarding args for all views and changing `actionViewItem` is risky as this is a general view item that is being used by all core components. 

Safe and proper fix is to let views decide to forward args or not.
