### ISSUE TITLE
Not consistent C++ code highlighting

### ISSUE THREAD

**Issue by azynheira** [Microsoft/vscode#11934]
- VSCode Version:
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
Date 2016-09-12T13:22:54.636Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0
- OS Version:
 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
 
See the slightly different code highlighting for the 2 identical code blocks:
1.
![screenshot from 2016-09-13 09 57 58](https://cloud.githubusercontent.com/assets/346780/18465851/509de158-7999-11e6-868e-022197ae8016.png)

2.
![screenshot from 2016-09-13 10 03 00](https://cloud.githubusercontent.com/assets/346780/18465856/5a48e554-7999-11e6-8a6c-8788c8870ff8.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by azynheira** [comment]
You are correct, it is Microsoft C/C++ extension from Microsoft. I will open an issue there.

Thanks,
Pedro
