### ISSUE TITLE
Minor syntax highlighting / selection issue for C/C++

### ISSUE THREAD

**Issue by ashmorep** [microsoft/vscode#119342]
Issue Type: <b>Bug</b>

Minor syntax highlighting bug and selection of variables and functions in VSCode for C/C++.

I think it applies to all version of VSCode.

It's valid to have "$" (dollar) signs in variable names and functions.
For instance "Func$$Find$$Some()"
VSCode doesn't select the whole function name, it treats the dollar signs as some kind of "break" and if you were to "cut" the selection the variable or function name would be corrupted.

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-53-generic

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
vscode-pull-request-github|Git|0.24.0
vscode-github|Kni|0.30.5
python|ms-|2021.2.582707922
jupyter|ms-|2021.3.619093157
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
cmake|twx|0.0.17
gitblame|wad|6.0.2

</details>

**Comment by alexr00** [comment]
@ashmorep can you please provide a copy/pastable code snippet that illustrates the problem?
