### ISSUE TITLE
We cannot connect to the extensions Marketplae at this time, please try again later

### ISSUE THREAD

**Issue by BbIKTOP** [microsoft/vscode#119375]
- VS Code Version:Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (4 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
- OS Version:

macOS 11.2.3 (20D91)

Steps to Reproduce:

When I try to search for extensions, I am getting this error.Log:
```
extensionsViews.ts:317 Error querying extensions gallery Cannot read property 'toLowerCase' of undefined
query @ extensionsViews.ts:317
async function (async)
query @ extensionsViews.ts:314
(anonymous) @ extensionsViews.ts:235
y @ async.ts:24
show @ extensionsViews.ts:233
(anonymous) @ extensionsViewlet.ts:648
onDidAddViewDescriptors @ extensionsViewlet.ts:647
(anonymous) @ viewPaneContainer.ts:527
fire @ event.ts:622
triggerOnDidAddVisibleViewDescriptors @ viewContainerModel.ts:447
onDidChangeContext @ viewContainerModel.ts:634
(anonymous) @ viewContainerModel.ts:329
fire @ event.ts:622
(anonymous) @ event.ts:74
fire @ event.ts:622
fire @ event.ts:682
setContext @ contextKeyService.ts:326
set @ contextKeyService.ts:200
doSearch @ extensionsViewlet.ts:635
(anonymous) @ extensionsViewlet.ts:600
(anonymous) @ async.ts:261
Promise.then (async)
trigger @ async.ts:255
triggerSearch @ extensionsViewlet.ts:600
(anonymous) @ extensionsViewlet.ts:501
fire @ event.ts:624
(anonymous) @ suggestEnabledInput.ts:173
(anonymous) @ textModel.ts:263
fire @ event.ts:622
endDeferredEmit @ textModel.ts:3361
pushEditOperations @ textModel.ts:1284
_innerExecuteCommands @ cursor.ts:783
executeCommands @ cursor.ts:741
_executeEditOperation @ cursor.ts:446
(anonymous) @ cursor.ts:651
_executeEdit @ cursor.ts:606
type @ cursor.ts:639
(anonymous) @ viewModelImpl.ts:949
_withViewEventsCollector @ viewModelImpl.ts:1016
_executeCursorEdit @ viewModelImpl.ts:935
type @ viewModelImpl.ts:949
_type @ codeEditorWidget.ts:1065
type @ codeEditorWidget.ts:1591
type @ viewController.ts:70
(anonymous) @ textAreaHandler.ts:266
fire @ event.ts:622
(anonymous) @ textAreaInput.ts:351
```

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Can you please record a video/gif trying to reproduce the issue and share with us. This will help us understanding how the issue happens.

**Comment by BbIKTOP** [comment]
Don't think it is really required. I simply pressed "Extensions" icon on the left toolbar, then started to type text I wanna search:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/24525137/112070196-e25b4980-8b75-11eb-910d-04999e8386ec.png">

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by BbIKTOP** [comment]
Did you read my first message? There's a log, which clearly states where it failed. Anyway:
1. Nothing wrong, no failed requests
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/24525137/112303994-a1fae900-8ca5-11eb-9be2-1ff4b726302e.png">
2. As there are no failed requests, I have nothing to check
3. My network works like a swiss watch, of course. I see the image on the URL provided, here's more convenient check:
```
viktor@Black-pro-6:~ $ telnet ms-python.gallerycdn.vsassets.io 80
Trying 68.232.34.200...
Connected to ms-python.gallerycdn.vsassets.io.
Escape character is '^]'.
GET / HTTP/1.0

HTTP/1.0 404 Not Found
Content-Type: text/html
Date: Wed, 24 Mar 2021 11:36:52 GMT
Server: ECAcc (wmi/FEC0)
Content-Length: 345
Connection: close

<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>
Connection closed by foreign host.
viktor@Black-pro-6:~ $
```
4. Developer Tools Console: 
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/24525137/112304738-817f5e80-8ca6-11eb-9c68-8fd8ad43b0c6.png">
Shared Process: 
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/24525137/112304971-cf946200-8ca6-11eb-9fe1-c8f1e98bae25.png">
Log (Shared): 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/24525137/112305119-ff436a00-8ca6-11eb-8b5f-6d250128e624.png">
Log (Window):
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/24525137/112305188-11250d00-8ca7-11eb-893c-68a63b2003bb.png">

**Comment by sandy081** [comment]
Assigning to April for investigation

**Comment by sandy081** [comment]
It seems like following error is coming from recommendations.

`querying extensions gallery Cannot read property 'toLowerCase' of undefined`

**Comment by BbIKTOP** [comment]
> It seems like following error is coming from recommendations.
> 
> `querying extensions gallery Cannot read property 'toLowerCase' of undefined`

What would you advice me to do to solve this? I tried complete removal/reinstall with no success.

**Comment by yto60** [comment]
Hi, I had the same problem with my VSCode (version 1.56.0).

The error seems to have come from https://github.com/microsoft/vscode/blob/1.56.0/src/vs/workbench/contrib/experiments/common/experimentService.ts#L500 at `local.manifest.publisher.toLowerCase()`.
Indeed, I had a local extension installed which didn't have a `manifest.publisher` set. The extension was one which I created for personal use, so I just set `manifest.publisher` for it.

As a workaround, disabling experimental stuff by setting
```
  "workbench.enableExperiments": false
```
in settings.json and reloading the window solved the problem too.

**Comment by sandy081** [comment]
I cannot repro the bug but I investigated in the code that if there is an error while getting experiments, this is impacting the extensions view. So please review the fix especially this change - https://github.com/microsoft/vscode/commit/fd6adaf30a2c56ed2d5f92f10903dfb056ad4b83#diff-911e37f13f52205cd492d9ccc7d8021e8d62c6783943f938cf236b3f1723a32dR702-R710

Errors from experiments service are ignored.
