### ISSUE TITLE
Download Update

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#119378]
Your "Download Update" notification has been harrassing me for days! Leave me be, I don't want your update! Put a "Don't ask again" or "Skip this version" there.

**Comment by gjsjohnmurray** [comment]
/gifPlease

Please also post your version and platform details from Help, About dialog. 

Tip for future issue reporting is to use Report Issue from the Help menu, which will add the information automatically.

**Comment by sandorvasas** [comment]
Like I'm talking to droids.

**Comment by joaomoreno** [comment]
The `update.mode` setting will let you control update notifications.
