### ISSUE TITLE
Closing a terminal via `exit` shows an error notification

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119306]
Steps to Reproduce:

1. split a terminal
2. close it by typing `exit` 

=> 🐛 
![image](https://user-images.githubusercontent.com/900690/111763443-6f668000-88a2-11eb-9523-cb72fa218b3f.png)

I am on macOS ARM.

**Comment by Tyriar** [comment]
This has always happened on mac. For some reason `exit` may return a non-zero exit code. `terminal.integrated.showExitAlert` was added for this reason (launch failures should still show up when you set this to true).
