### ISSUE TITLE
Extension installation dependencies

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#11937]
We want to support extensions depending on other extensions and having that transitive closure installed when installing the first one. Eg. `vscode-go` could depend on `vscode-go-syntax`.

This requires `vsce` work:

- [x] Figure out a syntax for `package.json` to indicate extension dependencies: `extensionDependencies`
- [x] Map dependencies to version properties, _queriable_ from the Marketplace: Microsoft/vscode-vsce#124
  - Property: `Microsoft.VisualStudio.Code.ExtensionDependencies` 

For `vscode`:

- [x] Figure out extension transitive closure, from version properties.
- [ ] Render that in the extension editor. Tracked in #12869 
- [x] Figure out how to notify user that more extensions will be installed (`Install all`, `Install this extension only`, `Cancel`)

We're leaving _Uninstall_ out of the story for now.

**Comment by joaomoreno** [comment]
@seanmcbreen @waderyan 

As discussed with @egamma, we're going with an approach in which 100% of this work in on our side. An extension can list other extensions it wants to be installed in the user's machine, when installing itself. As a consequence, this _connection_ won't surface in the Marketplace, only at extension installation time, within VS Code itself.

Any other approach would require cooperation with the Marketplace to create a first class concept of extension dependencies or packs.

**Comment by waderyan** [comment]
> An extension can list other extensions it wants to be installed in the user's machine, when installing itself.

Will this be done in the manifest file or where will it be done? 

I am not opposed to the approach, but I can see some benefit to having dependent extensions surface in the Marketplace's UI.

**Comment by joaomoreno** [comment]
We decided to use the (already existing) `extensionDependencies` property in `package.json`. It is a list of extension names.

**Comment by waderyan** [comment]
Cool sounds good to me.
