### ISSUE TITLE
Can't open untitled notebooks in test

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119363]
- Run vscode-jupyter tests against Code-OSS
- Ones that use untitled files fail because we pick the wrong provider type

![image](https://user-images.githubusercontent.com/323878/111847961-342a7800-88c7-11eb-8c1b-56d91c44f7a5.png)

I think this is because we don't check the path of untitled files, so we pick our test provider that isn't really registered and doesn't want .ipynb files, instead of the jupyter provider which is properly registered.

https://github.com/microsoft/vscode/blob/0eff78fc42e1a3b9445496610ee2a5c8179e94d5/src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts#L188

**Comment by jrieken** [comment]
> I think this is because we don't check the path of untitled files, 

Usually untitled files don't have a path but I can change this to two phases where we first pick a provider based on path and then try what we do today.

**Comment by jrieken** [comment]
I have pushed a fix - assuming the code location you have pointed out is the right one
