### ISSUE TITLE
The hover service should hide the hover when the element it's tied to is clicked

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119330]
This is currently done by consumers of the hover service (https://github.com/Microsoft/vscode/blob/a255250be89b8208dd219e778f0b2743e198e371/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L232-L235), but could be moved into the hover widget.

**Comment by Tyriar** [comment]
Repro:

Hover a link in the terminal and then click the link (no ctrl), the hover should hide immediately.

**Comment by bpasero** [comment]
I think we are doing this now @benibenj ?

**Comment by benibenj** [comment]
@bpasero This is the case for the managed hover (updateable hover), but I don't think it is the case when using `HoverService.show()` directly.

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/204965

**Comment by Tyriar** [comment]
This isn't so black and white since we also want to support selecting text, especially -but not exclusively- when the hover is locked. Closing as designed for now. @benibenj let me know if you have ideas
