### ISSUE TITLE
Code deleting on save (Golang). 

### ISSUE THREAD

**Issue by swanwhite** [microsoft/vscode#119356]
- VS Code Version: 1.54.3
- OS Version: windows/amd64

Steps to Reproduce:

1.  Type code in the editor.
2. Press Ctrl + S or File>Save. Then some characters delete.  

See video below to see the problem. It only deletes characters from the final function 'unixMillis' as shown in video. 

https://user-images.githubusercontent.com/63259916/111835102-6dc1aa00-88ec-11eb-82bd-95ec7af438f9.mp4

Does this issue occur when all extensions are disabled?: No

**Comment by swanwhite** [comment]
Can someone help me please?

**Comment by dbaeumer** [comment]
@swanwhite this looks like a problem of the Go extension. Please report the issue with their issue tracker here:  https://github.com/golang/vscode-go
