### ISSUE TITLE
please allow for column select by holding ALT

### ISSUE THREAD

**Issue by cbartholomew** [microsoft/vscode#119348]
Issue Type: <b>Feature Request</b>

normally in other VS platforms, including SSMS, I can hold "ALT" and do a column select. I can not do this - it's a basic and important feature that event something like notepad++ has. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alexdima** [comment]
This can be done by configuring `"editor.multiCursorModifier": "ctrlCmd"`. Then you can do mouse down and drag with the mouse and press alt to toggle between regular selection and column selection.
