### ISSUE TITLE
Use recommended git bash args in default detected profile

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119346]
We should use these defaults: https://code.visualstudio.com/docs/editor/integrated-terminal#_windows

Context: https://github.com/microsoft/vscode/pull/118790#issuecomment-800976242

**Comment by Tyriar** [comment]
We decided against doing this because it seems like `git-cmd.exe --command=usr/bin/bash.exe -l -i` and `bin/bash.exe -l` are equivalent and both run `.bash_profile` which was the original reason it was changed in the docs https://github.com/microsoft/vscode-docs/pull/4066. We'll update the docs this release https://github.com/microsoft/vscode-docs/issues/4406

**Comment by karlhorky** [comment]
Great, thanks for checking into that (and the simplification)!

**Comment by karlhorky** [comment]
By the way, thanks @meganrogge and yourself @Tyriar, now we have simplified the System Setup guide for our bootcamp students with your simplified start command:

https://github.com/upleveled/system-setup/commit/568f3df837f3bc906174d067d6919b3f1df6465b
