### ISSUE TITLE
Would not run.

### ISSUE THREAD

**Issue by LetsGoWolve** [microsoft/vscode#119397]
Issue Type: <b>Performance Issue</b>

(Please note that I am new to coding and a student just starting to learn, so I do not know that this is just a simple fix I can do by myself.)

I've been trying to run this for an hour. This issue just happened this day, when I am finally using it to complete an activity in our class. I placed proper coding (To my friend's standard, who's a legend and also uses this program.) and tried to debug it several times and run without debugging but they all ended up with this result. What am I doing wrong/What is the problem here?

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3100 4-Core Processor               (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.95GB (3.04GB free)|
|Process Argv|--crash-reporter-id f4065bcc-80a0-435d-a894-62273ba09c89|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 13180	code main
    0	    94	  2292	   shared-process
    0	    67	  2796	     ptyHost
    0	     6	 11224	       console-window-host (Windows internal process)
    0	    82	 13144	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    37	  3920	   utility
    0	   191	  5968	   window (WE - .vscode - Visual Studio Code)
    0	    78	  8688	     "E:\Microsoft VS Code\Code.exe" "e:\Microsoft VS Code\resources\app\out\bootstrap-fork" ms-vscode.pwa-chrome "{\"common.vscodemachineid\":\"a0fda109700595ffebe12b7d4f2599febef4b252150f3e18e321cad64beba8af\",\"common.vscodesessionid\":\"3574fb35-72df-4303-ad80-ca4123d63c551616290735045\"}" AIF-d9b70cd4-b9f9-4d70-929b-a071c400b217
    0	    14	  9980	     watcherService 
    0	    10	  6292	       console-window-host (Windows internal process)
    0	   109	 10292	     extensionHost
    0	    82	 10976	       "E:\Microsoft VS Code\Code.exe" "e:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10292
    0	    84	 13612	       electron_node ms-vscode.js 
    0	    42	  2348	         window (undefined)
    0	    22	  3848	         window (undefined)
    0	    25	  9724	         utility
    0	    55	 10272	         gpu-process
    0	     8	 11396	         crashpad-handler
    0	    15	 14192	         utility
    0	   109	  8860	   gpu-process
    0	    23	  9352	   crashpad-handler
    0	    80	 14300	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (WE - .vscode - Visual Studio Code)
|    Folder (.vscode): 5 files
|      File types: json(2)
|      Conf files: launch.json(1)
|      Launch Configs: pwa-chrome(2);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by weinand** [comment]
Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions to learn how to write bug reports.
