### ISSUE TITLE
Run Without Debug never terminates if uncaught exceptions breakpoint is enabled

### ISSUE THREAD

**Issue by dinofx** [microsoft/vscode#119340]
When using CTRL+F5 to launch a node app without debugging it, the launched app never exits if either caught or uncaught exceptions breakpoint is enabled.

- VS Code Version:
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (4 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1.  In a new workspace, create a simple hello.js file that logs hello to the console
2.  Create a launch config for it:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "console": "integratedTerminal",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/hello.js"
    }
  ]
}
```
3. CTRL+F5 to launch it, notice it exits normally:
```
Debugger attached.
hello
Waiting for the debugger to disconnect...
```
4. Now check the "Uncaught Exceptions" in the breakpoints view and try again.

The terminal shows only:
```
Debugger attached.
```

and the program never runs.  Stop button on the debug toolbar kills it, but VSCode thinks the launch is still active and the toolbar never goes away.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Thanks for the issue, good find
