### ISSUE TITLE
Privacy invasive extension of unknown origin built in 

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#119394]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

I noticed that vscode comes bundled with an extension called "ms-vscode-remote.remote-wsl-recommender", that I did not install. 
I also can't find the source code for it in the repository. 

If this crap comes bundled with vscode, why isn't it in the repo?

**Comment by aeschli** [comment]
`ms-vscode-remote.remote-wsl-recommender` adds commands to VSCode that let you open a folder or workspace located in the [Windows Subystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about). When invoked, it also will guide you on how to enable the WSL feature in Windows, if necessary.

`ms-vscode-remote.remote-wsl-recommender` is part of the remote development feature which is not in the OSS repo, but only part of the Microsoft Visual Studio Code distribution. You can find detailed information on why this is like that and what the differences between the repo and VS Code are, [here](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code).

VS Code an all extensions from Microsoft (including `ms-vscode-remote.remote-wsl-recommender`) follow the privacy guidelines described [here](https://privacy.microsoft.com/en-us/privacystatement). You can disable the collection of the anonymized usage and crash data as described [here](https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting).

The commands added by `ms-vscode-remote.remote-wsl-recommender` are currently part on an A/B experiment, so not all users will see the new commands. If you do not which to participate in any experiment, you can set `workbench.enableExperiments` to `false`.

**Comment by aeschli** [comment]
@chrisdias Do you think we should explicitly mention `ms-vscode-remote.remote-wsl-recommender` in https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code ? 

We should also document the `workbench.enableExperiments` setting. I created https://github.com/microsoft/vscode-docs/issues/4412.

**Comment by aeschli** [comment]
We discussed the issue and decided that we will open source the `ms-vscode-remote.remote-wsl-recommender` extension as it does not contain any proprietary code. It will made available under the normal MIT license at https://github.com/microsoft/vscode-remote-wsl-recommender.
