### ISSUE TITLE
    "workbench.startupEditor": "readme_but_not_for_loaded_extensions",

### ISSUE THREAD

**Issue by gilescope** [microsoft/vscode#119305]
"workbench.startupEditor": "readme", is in theory great but in practice deeply flawed.

If I open up a new project it shows the readme - good behaviour.
But if I then edit a python file, it starts up the python extinsion which has a readme and guess what I get to read that too.

I really don't want extension readmes to auto load. I do not see that as desirable and very distracting.

**Comment by gilescope** [comment]
not a dupe of the above.

**Comment by dbaeumer** [comment]
@sbatten are you the right person for this?

**Comment by sbatten** [comment]
@JacksonKearl most recently touched this setting

**Comment by JacksonKearl** [comment]
Hey @gilescope, when you say:
> if I then edit a python file, it starts up the python extinsion which has a readme and guess what I get to read that too.

Are you referring to this page:

![image](https://user-images.githubusercontent.com/8586769/112044130-ad63de00-8b06-11eb-8422-9efb2a30d295.png)

If so this is independent of the `workbench.startupEditor` property, and instead is contributed by the python extension. There should be a checkbox at the bottom you can uncheck to not see it again. 

Let me know if that helps!

**Comment by gilescope** [comment]
ah yes. ok my bad. good spot.
