### ISSUE TITLE
Console does not preserve the right output colors

### ISSUE THREAD

**Issue by withmask** [microsoft/vscode#119380]
- VS Code Version: 1.54.3/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/x64

- OS Version: Ubuntu 20.04.2 LTS x86_64 

Steps to Reproduce:

1.Run a program on console that prints colorized ouput to stdout
2.See that reset is replaced with blue and most of colors (such as green) are also replaced with blue

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
@withmask Is this the integrated terminal? Could you attach a screenshot?

**Comment by Tyriar** [comment]
Also if it is the terminal, is it just the theme setting the wrong color?
