### ISSUE TITLE
Intellisense doesn't work on JavaScript file until I change language mode

### ISSUE THREAD

**Issue by kai23** [Microsoft/vscode#11938]
- VSCode Version: 1.5.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Create folder `Hello`
2. In `Hello`, create file `app.js`
3. `code .` or open this folder in VSCode
4. In app.js, type : `console.` - No Intellisense
5. Change the language mode to "JavaScript React"
6. Type `console.` - Intellisense is present

Gif to show what happen : 

![ezgif-340640585](https://cloud.githubusercontent.com/assets/796803/18466732/1b3e3158-799d-11e6-9258-b714fa50cbd3.gif)

No Extension, brand new VSCode

**Comment by NeilAllen** [comment]
Same here...

**Comment by waderyan** [comment]
@kai23 thank you for opening this issue. I have observed similar behavior and think it could be related to [Microsofty/TypeScript #10735 ](https://github.com/Microsoft/TypeScript/issues/10735).

I cannot reproduce right now

![intellisense_simple](https://cloud.githubusercontent.com/assets/2449568/18480430/8155ba34-798d-11e6-9202-54bc93900b0d.gif)

Can you help me track this down? 

Add this to your settings

```json
"typescript.tsserver.trace": "verbose"
```

Additionally, set the environment variable TSS_LOG=-level verbose. there should be a log file written next to tsserver.js that would have the form of .log[0-9]+

**Comment by kai23** [comment]
Here is the full log. I did the exact same thing as shown in the gif : http://pastebin.com/pr32P8j8

**Comment by kai23** [comment]
maybe that's the part which you may like ? 
```
[Trace - 9:12:34 PM] Sending request: completions (3). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "/Users/XXXX/Hello/app.js",
    "line": 1,
    "offset": 2
}
[Trace - 9:12:34 PM] Response received: completions (3). Request took 3 ms. Success: false . Message: Error processing request. No Project.
[Error - 9:12:34 PM] 'completions' request failed with error.
Error processing request. No Project.
```

**Comment by waderyan** [comment]
@kai23 thanks for logging this for us. Sending to TS team to look into further.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11043

**Comment by lzantal** [comment]
Same issue here. Adding the jsconfig.json file removed all intellisense for me. Not even document or window objects have anything.

**Comment by waderyan** [comment]
@lzantal did you reload the window?

**Comment by lzantal** [comment]
@waderyan yes I did. I even closed everything out and restarted VSCode. Removing the jsconfig.json file brought back full intellisense even for my custom es6 classes.

**Comment by waderyan** [comment]
Very strange. Can you open a separate issue and do the following?

1. Try your setup with v1.6 (released yesterday). 
2. Create and share a minimal repo that reproduces the behavior. 
3. Add `"typescript.tsserver.trace": "verbose"` to your settings file. 
4. Send me the output of the TypeScript log (you can see that in the output window as seen below). 

![image](https://cloud.githubusercontent.com/assets/2449568/19280739/0256a32c-8f9c-11e6-9785-6da7fe036e0d.png)

**Comment by lzantal** [comment]
@waderyan Absolutely! Thank you for the detailed instructions!! I need them ;)
