### ISSUE TITLE
It takes forever to delete a file

### ISSUE THREAD

**Issue by Xenfo** [microsoft/vscode#119326]
Issue Type: <b>Performance Issue</b>

It takes 5-10 seconds to delete 1 file. If I'm deleting many it takes minutes. On windows I can delete instantly.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.40GB (2.03GB free)|
|Process Argv|--no-sandbox --new-window --crash-reporter-id 70a9a96e-bece-4fc0-a120-fe69bb1a4cae|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   158	 20396	code main
    0	    32	 20398	   zygote
    0	   126	 20422	     gpu-process
    0	    32	 20399	   zygote
    0	    79	 22510	     window (Issue Reporter)
    0	    47	 20429	   utility
    0	   126	 20847	   shared-process
    0	    47	 20883	     ptyHost
    0	     0	 21476	       /usr/bin/zsh
    0	     0	 22528	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 22529	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   205	 21162	   window (First Project - Visual Studio Code)
    0	   205	 21192	     extensionHost
    0	     0	 21317	       /bin/sh -c rustup run stable-x86_64-unknown-linux-gnu rls
    0	    47	 21318	         /home/xenfo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls
    0	    63	 21199	     watcherService
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (First Project - Visual Studio Code)
|    Folder (First Project): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
cypress-snippets|and|1.2.0
jest-snippets|and|1.8.0
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
vscode-firefox-debug|fir|2.9.2
vscode-jest-runner|fir|0.4.31
shell-format|fox|7.0.1
helium-icon-theme|hel|1.0.0
discord-vscode|icr|5.4.0
fluent-icons|mig|0.0.7
dotenv|mik|1.0.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.3968
vscode-jest|Ort|3.2.0
material-icon-theme|PKi|4.5.0
vscode-yaml|red|0.16.0
logos-vscode|Ren|0.5.1
rust|rus|0.7.8
vs-code-prettier-eslint|rve|0.4.1
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.14.0
vscode-counter|uct|2.2.2
clang-format|xav|1.9.0
commandlist|yam|1.0.3
material-theme|zhu|3.9.15

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by isidorn** [comment]
I can not reproucce
 Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by Xenfo** [comment]
VSCode Insiders crashes for me on startup.

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #101920

**Comment by Xenfo** [comment]
Yes it seems to be
