### ISSUE TITLE
Test: Window Indicator for Virtual workspaces

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#119313]
Refs: #118813

- [x] anyos @Tyriar
- [x] anyos @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119313%0A%0A)

---

We now show the window indicator (status bar on the left) also for virtual workspaces.

To be a virtual workspace, the window needs to be opened on
- a folder with a scheme from a contributed FS (nor `file` or `vscode-remote`)
- a workspace where the workspace config file is located on a contributed FS (does not include workspaces saved on the file system but pointing to a folding on a virtual fs (what LiveShare does in Guest mode))

Also there needs to be a ResourceLabelProvider for the given FS, defining a host name (`workspaceSuffix`)

- Install [RemoteHub](https://marketplace.visualstudio.com/items?itemName=eamodio.remotehub) 
- Open a folder and verify that the window indicator shows `GitHub`
- Test other extension with virtual file systems: SSH FS, Remote FS, LiveShare Guest mode, ...) and see if it looks bad.

**Comment by aeschli** [comment]
@eamodio Feel free to add more to test

**Comment by alexr00** [comment]
Tested with RemoteHub on Windows.

I couldn't get LiveShare to connect so I couldn't test with that.

I SSH FS working, but I couldn't get it to open the window on the remote filesystem or get it to open a workspace that was saved remotely.
