### ISSUE TITLE
Allow to change Visual Studio Code icon

### ISSUE THREAD

**Issue by corwin-of-amber** [microsoft/vscode#119324]
* VSCode version: 1.55.0-insider
 * macOS version: Big Sur 11.2.3 (20D91)

This issue #26839 has been closed but not fixed. I am trying to change the VSCode application icon on my macOS, but every time VSCode installs an update, the icon reverts back to the stock icon. I am using the Insiders build so updates are *very* frequent, I wouldn't like to add "Change VSCode app icon" to my daily routine.

Please, the Big Sur-style icon with the white squircle background is **unbearable**. At least as long as the update has nothing to do with the update, VSCode can keep the user's preferred one.

**Comment by misolori** [comment]
Thanks for the feedback. We understand that this is frustrating but unfortunately this isn't possible to do. This also occurs in other applications when there is an update so it's not specific to VS Code. Will have to close this issue, sorry for the trouble.

**Comment by corwin-of-amber** [comment]
😢 😢

**Comment by corwin-of-amber** [comment]
Can you at least tell me where VSCode is saving the downloaded updates on macOS? Should they be saved in `/Library/Updates`? At the very moment, there is no pending update so I cannot check.
