### ISSUE TITLE
@jokro you are absolutely right: `vertical-align` is a CSS property, `horizontal-align` is not.

### ISSUE THREAD

**Issue by Afvanjaffer** [microsoft/vscode#119337]
@jokro you are absolutely right: `vertical-align` is a CSS property, `horizontal-align` is not.

_Originally posted by @shiftgeist in https://github.com/microsoft/vscode/issues/70116#issuecomment-471489128_

but vs code is alerting error on vertical-align: middle

**Comment by jokro** [comment]
Dit email adres houdt op te bestaan. 

Gebruik vanaf nu ***@***.***

**Comment by shiftgeist** [comment]
This issue is incomplete. Please fill out the issue template. It is not clear in what environment you are getting this error.

---

> Dit email adres houdt op te bestaan.

translates to `This e-mail address no longer exists`. Might want to check your github mail settings.

**Comment by Afvanjaffer** [comment]
"Property is ignored due to the display. With 'display: block', vertical-align should not be used."

vs code out this error 
on usage of 
'vertical-align: middle'

**Comment by shiftgeist** [comment]
> The vertical-align property can be used in two contexts:
> 
> To vertically align an inline element's box inside its containing line box. For example, it could be used to vertically position an <img> in a line of text: [...]
>
> To vertically align the content of a cell in a table: [...]

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

When setting `display: block` the element is no longer an inline element. Therefore the given warning from vscode is correct imo.

You could however inline the element:

```diff
.test {
- display: block;
+ display: inline-block;
  vertical-align: middle;
}
```
