### ISSUE TITLE
Test: backups migrated to new hash function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119301]
Refs: 

- [x] macOS @rebornix
- [x] linux @TylerLeonhardt
- [x] windows @deepak1556

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119301%0A%0A)

---

Backups are being persisted in the `user-data-folder/Backups/` folder for each window you open for:
* single folder workspaces
* multi root workspaces
* empty windows

For any file you have dirty:
* files that are backed by a file system provider
* untitled files

Because we want a unique backup file per backup, the backup file names are a hashed representation of the file name. So far we had been using node.js `crypto` module to create MD5 hashes but for sandboxing the renderer, we need to move away to a non-node.js hash function. This milestone the backups start to use our own hash method:

https://github.com/microsoft/vscode/blob/673c1adcb0621ddc12e793c56be93d831fe7ff1d/src/vs/base/common/hash.ts#L45-L51

Because we obviously have a lot of existing backups with the old format, there is a migration step when starting VSCode for the first time when old backups are encountered, where the backups are being renamed to the new format.

**Bootstrap**
* use the `--user-data-dir <some empty folder>` CLI argument to ensure testing happens on a fresh data directory
* start VSCode stable `1.54.x` on that user data folder and open some files (also untitled) and make them dirty so that backups are created
* make sure you have multiple windows open to cover single-folder, multi-root and empty window cases
* close VSCode stable

**Test**
* use insiders on the same user data folder directory as before
* verify the dirty files appear with their contents as you left them in all of the windows
* close and restart again
* verify again that the dirty files are still there

**Comment by rebornix** [comment]
Tested empty workspace, single workspace and multi workspace with dirty files and untitled files. The migration from Stable to Insiders work as expected. Once it's migrated, opening the workspaces in older VS Code stable will not recover the backups, which I think is expected.

**Comment by bpasero** [comment]
Oh yeah that is a good point. This is unfortunate but nothing that can be fixed easily unless we would keep the old backup around...
