### ISSUE TITLE
[Getting Started] Switching to and fro Getting Started doesn't maintain state

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#119339]
STR:

1. On Getting Started, go to the welcome overview
2. Switch to a different tab and back

![recording (1)](https://user-images.githubusercontent.com/8599/111813729-cebe9300-8896-11eb-8a21-e87140cff474.gif)

AR: Switched back to _Quick Setup_ (even though it is partially done).
ER: Maintain state.

**Comment by JacksonKearl** [comment]
I haven't been able to reproduce this, have you seen it since?

**Comment by digitarald** [comment]
Still reproducible. Just opened a fresh Insiders without any profile data:

![recording (2)](https://user-images.githubusercontent.com/8599/112416746-8282b100-8ce3-11eb-93c7-2acad058eec2.gif)
