### ISSUE TITLE
Finalize 'statusBar/windowIndicator' menu contribution point

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#119349]
The `statusBar/windowIndicator` menu contribution point lets extensions add commands to the quickpick that appears when the user clicks on the window indicator.

At the moment it is still proposed API, so my extension can only use it if it jumps through the `enableProposedApi` hoops.

Please finalize this contribution point.

Version: 1.55.0-insider (user setup)
Commit: e4b1e9ac57ab3cc942ab9bff09967bf3238a7910
Date: 2021-03-19T05:14:28.175Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
You are right, it's about time we do that. I will bring it up for discussion.

**Comment by gjsjohnmurray** [comment]
Looks like this is underway in #121180 so I'm closing this one.
