### ISSUE TITLE
Question: Is it possible to "merge" completion provider results

### ISSUE THREAD

**Issue by buehler** [Microsoft/vscode#11935]
Hey guys

I was wondering if the following scenario is possible:
When I register my custom `CodeCompletionProvider` (which now works like a charm, thanks to Johannes Rieken), the default provider from VSCode is kinda deactivated.

When I explicitly call the suggestions, it more or less works, but not on all scenarios.

I'd like to merge the results of my provider with the original providers of vscode. Or at least extend the base result with my results.

The problem is, if I overwrite the default provider and deliver non imported symbols to complete, stuff like `[].some` or other array functions are not completable anymore. My completionprovider does not index those functions, so there are not visible anymore.

It would be cool if both information would be there.

Cheers
Chris

**Comment by jrieken** [comment]
The default is merging and it's actually hard to disable that. I'd interested in learning more about your provider and how it overrides?

**Comment by buehler** [comment]
Of course :-) I'd be happy to help.
Have a look at it here: https://github.com/buehler/typescript-hero/blob/feature/code-completion-provider/src/provider/ResolveCompletionItemProvider.ts

Registering it here: https://github.com/buehler/typescript-hero/blob/feature/code-completion-provider/src/extensions/ResolveExtension.ts#L97

And if I use this provider I don't see any other providers results in the suggestions window. I don't know the exact mechanics of vscode, but my assumption was, that the results are merged.

But you can try it for yourself, you'll only see the results of "my" provider when you are typing, but afterwards when you call the provider "by force" with the keybindings, the results are kind of merged.

Cheers

**Comment by jrieken** [comment]
Yeah, that's because of the [long](https://github.com/buehler/typescript-hero/blob/feature/code-completion-provider/src/extensions/ResolveExtension.ts#L97) list of auto trigger characters. When a auto trigger character is seen we only ask those providers - usually that is just a few special characters like `.`. If there a special reason you use the whole alphabet? As long as the `quickSuggest` setting is true (which is default) you will be asked anyways.

**Comment by buehler** [comment]
Alright. Yea there is a special reason: When I remove the trigger characters, my provider never gets called in the first place. Only if I use the keybinding of the suggestions. At least, all other stuff works again (like Array.some), but my suggestions are never shown.

My completion provider works as such that is only delivers a result when the user is typing the first word of a assignment or stuff. The usecase is to add the import to the document when it's not already imported.

So if you write "MyC" it should suggest "MyClass". But when I don't use the trigger characters, it looks like this:

![foo](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/atjebr30.png)

Only when I call the suggestions with `ctrl+space` it looks like this:

![bar](https://dl.dropboxusercontent.com/spa/agn3r6rkwi4rxn7/5kq8z499.png)

When I used all the trigger characters, the suggestions would automatically pop up if you write anything.

Is this the wrong way to accomplish this goal?

**Comment by buehler** [comment]
Hey @jrieken 

Do you still need more information? I'd be happy to provide you with any information that I can.

Cheers

**Comment by jrieken** [comment]
Can you check for this setting `"editor.quickSuggestions": true`? By default we keep asking for completions while the user types (24x7 intellisense) - if that is turned off we still use trigger characters (unless turned off `"editor.suggestOnTriggerCharacters": true|false`)

**Comment by buehler** [comment]
Well I just checked, `quickSuggestions` is on (`true`) and `suggestOnTriggerCharacters` is true as well.

The behaviour is still the same. On normal typing, only the normal suggestions of vscode are visible. Only if I explicitly call the suggestions with the keycombo, my suggestions show up.

**Comment by jrieken** [comment]
So, putting a breakpoint [here](https://github.com/buehler/typescript-hero/blob/master/src/provider/ResolveCompletionItemProvider.ts#L26) and I see it being hit on type as well as on ctrl+space. Unsure what comes then but if the provider is being hit, its result (iff available) will be merged

**Comment by buehler** [comment]
Alright, let me check again if the line https://github.com/buehler/typescript-hero/blob/master/src/provider/ResolveCompletionItemProvider.ts#L38 is causing those troubles. Maybe because I drop out of completion if less than 2 characters are typed, this is deactivating my suggestions.

I'll come back to you with more info, thanks for the help!

**Comment by buehler** [comment]
Hooray!

Alright, my bad 😉 
Since I deactivated the "minimum characters", it does work like a charm!

I really appreciate the help!

Cheers
