### ISSUE TITLE
Do not keep `IEditor` in memory

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119308]
I just came across this one:

https://github.com/microsoft/vscode/blob/5510ee9c51d94a871626a61a1c944a70acc123ec/src/vs/workbench/browser/layout.ts#L235-L235

I think it is very dangerous to keep instances of `IEditor` in memory because they resemble the actual editor widget (to my knowledge). So I would rather not want to keep these in-memory on a somewhat global object.

Can we find an alternative that does not require keeping instances of code editors in memory outside the lifecycle of the editor?

**Comment by isidorn** [comment]
Good find. I can look into cleaning this up in debt week.

**Comment by isidorn** [comment]
Removed the smartness, so we now do not keep the editors in memory.
Downside there might be some corner cases when going out of zen mode that line numbers are not restoring. I could not find this corner case right now, but I remember that was the initial reason why we had this logic
