### ISSUE TITLE
body and head tag not indenting

### ISSUE THREAD

**Issue by nxsmcaspani** [microsoft/vscode#119323]
Issue Type: <b>Bug</b>

Hello,

Despite having enabled the option to indent head & body html tags, every time I save a file, the indent is removed. I have also disabled the option to check syntax on save, so I don't know why it behaves, seems like a bug for that preference ?

Thank you

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.84GB free)|
|Process Argv|--crash-reporter-id 398a21a0-a39a-4585-a734-5372f9f149b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-eslint|dba|2.1.19
vscode-html-css|ecm|1.10.2
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-JS-CSS-HTML-formatter|lon|0.2.3
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
java|red|0.76.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943:30277001
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by nxsmcaspani** [comment]
Hello,

Thank you for your answer!

Yes I tried to disable the extensions I installed and the behavior was still present and body & head tags weren't indented.

That being said I just tried your tip F1: Developer: Reload Window With Extensions Disabled , which actually helped with the indentation, but then it prevents newlines from being kept, not sure why.

Anyway sorry I should have tried to disable each extension one after the other, so I would have detected that the ESLint one was the gulty.

I let you decide what to do with that request, if at some point it is expected that such extension can overwrite the setting or not.

Thank you again!

**Comment by aeschli** [comment]
Yes, each extension has it's own settings. the `html` settings are for the built-in HTML extension and the built-in HTML formatter.
I understand that's a bit confusing. 

Looking at the extension list, you were likly using the `vscode-JS-CSS-HTML-formatter` formatter.
