### ISSUE TITLE
(feat) Debug tool bar position.

### ISSUE THREAD

**Issue by y0nd0** [microsoft/vscode#119421]
# Feature

## Description

**Suggestion:**

Please add a new option for `debug.toolBarLocation` like `free` or `custom` or / and `bottom` (docked; like the "Problem" / "Terminal" panel. Or just like the current "floating" behavior. But just also on bottom.). I think the botton position is optimal. Because there is nothing important to overlap.

**Current state:**

```js
{
  // Possible values: "docked" | "floating" | "hidden"
  "debug.toolBarLocation": "docked",
}
```

![image](https://user-images.githubusercontent.com/68586847/111922859-a902db00-8a9c-11eb-84e6-a12c3ca7e3c6.png)

><sub>I found some existing issues about this issue. But closed and a bit messy. So please forgive me if this is a duplicate. I'm not sure. But I hope that this issue finally solves the problem.</sub>

## Visual Studio Code Info

Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by y0nd0** [comment]
@isidorn @weinand I can't find an open duplicate. Could you refer the issue please?

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode/issues/117326

**Comment by y0nd0** [comment]
@isidorn Why voted down? Usually you should link duplicates. I feel negative vibes. :D
