### ISSUE TITLE
Status Bar border

### ISSUE THREAD

**Issue by YungYoku** [microsoft/vscode#119404]
Issue Type: <b>Bug</b>

White border around status bar appears on click.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
![image](https://user-images.githubusercontent.com/63597891/111898719-a6ae6b80-8a1f-11eb-874e-f8d83ff73ab2.png)
![screen](https://user-images.githubusercontent.com/63597891/111898791-fe4cd700-8a1f-11eb-8bcf-86b3e8fe2ed4.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (10.18GB free)|
|Process Argv|--crash-reporter-id 35d97aa2-e288-4a94-97ac-748cefebe54b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
All-Autocomplete|Ati|0.0.23
prettier-vscode|esb|6.3.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
helium-icon-theme|hel|1.0.0
theme-monokai-pro-vscode|mon|1.1.18
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
I think this border indicates focus, which is important to meet accessibility needs.

**Comment by sbatten** [comment]
@YungYoku I believe this is as designed. Can you provide your theme for me to verify?
