### ISSUE TITLE
Delete Control Character (U+007F / &#127; ) displayed as space

### ISSUE THREAD

**Issue by myfonj** [microsoft/vscode#119416]
Version: 1.55.0-insider
Commit: e4b1e9ac57ab3cc942ab9bff09967bf3238a7910
Date: 2021-03-19T05:14:28.175Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.16299

### Steps to Reproduce:

1. Have Delete Character in document

### Actual outcome:

Character has display identical to space character. (See testcase and screenshots.)

### Expected outcome:

When `"editor.renderControlCharacters": true`, character is displayed as "␡" (symbol for delete U+2421).
When `"editor.renderControlCharacters": false`, character is displayed as substitute symbol, like other control characters.

Does this issue occur when all extensions are disabled?:
Yes.

### Testcase

Plaintext file, lines of text in `[(control character)] symbol for (control character) from "control pictures" Unicode block, name (notes)` format in reversed code point order (Delete control character on the first line, Null on the last):

    data:text/plain;charset=utf-8,[%7F] %E2%90%A1 Delete character.%0D%0A[%20] %E2%90%A0 Space character.%0D%0A[%1F] %E2%90%9F Unit Separator.%0D%0A[%1E] %E2%90%9E Record Separator.%0D%0A[%1D] %E2%90%9D Group Separator.%0D%0A[%1C] %E2%90%9C File Separator.%0D%0A[%1B] %E2%90%9B Escape.%0D%0A[%1A] %E2%90%9A Substitute.%0D%0A[%19] %E2%90%99 End of medium.%0D%0A[%18] %E2%90%98 Cancel.%0D%0A[%17] %E2%90%97 End of Transmission Block.%0D%0A[%16] %E2%90%96 Synchronous Idle.%0D%0A[%15] %E2%90%95 Negative Acknowledge.%0D%0A[%14] %E2%90%94 Device Control Four.%0D%0A[%13] %E2%90%93 Device Control Three (XOFF).%0D%0A[%12] %E2%90%92 Device Control Two.%0D%0A[%11] %E2%90%91 Device Control One (XON).%0D%0A[%10] %E2%90%90 Data Link Escape.%0D%0A[%0F] %E2%90%8F Shift In.%0D%0A[%0E] %E2%90%8E Shift Out.%0D%0A[%0D] %E2%90%8D Carriage Return.%0D%0A[%0C] %E2%90%8C Form Feed.%0D%0A[%0B] %E2%90%8B Line Tabulation, Vertical Tabulation.%0D%0A[%0A] %E2%90%8A Line feed (normalized to line break upon paste).%0D%0A[%09] %E2%90%89 Character Tabulation, Horizontal Tabulation (regular tab).%0D%0A[%08] %E2%90%88 Backspace.%0D%0A[%07] %E2%90%87 Bell, Alert.%0D%0A[%06] %E2%90%86 Acknowledge.%0D%0A[%05] %E2%90%85 Enquiry.%0D%0A[%04] %E2%90%84 End of Transmission.%0D%0A[%03] %E2%90%83 End of Text.%0D%0A[%02] %E2%90%82 Start of text.%0D%0A[%01] %E2%90%81 Start of Heading.%0D%0A[%00] %E2%90%80 Null character.%0D%0A

### Screenshots of the testcase

`"editor.renderControlCharacters": true`:

![image](https://user-images.githubusercontent.com/1761395/111917147-b0b38700-8a7e-11eb-9799-b94bb6d95b88.png)

`"editor.renderControlCharacters": false`:

![image](https://user-images.githubusercontent.com/1761395/111917172-c923a180-8a7e-11eb-918c-8fa10d19e949.png)

(Also, I don't think it is OK to render Control Pictures for control characters (i.e. not control characters per se) as `[?]` substitute symbol; see `␟␞␝␜␛␚␙␘␗␖␕␔␓␒␑␐␏␎␌␋␈␇␆␅␄␃␂␁` are now `[?]` compared to first screenshot, just ␀␉␊␍␠␡ remained.  Probably subject for other issue.)(Also Null Control Character is strangely converted to `�`.)

**Comment by alexdima** [comment]
Here is the file: [control-characters.txt](https://github.com/microsoft/vscode/files/6181404/control-characters.txt)
