### ISSUE TITLE
Have to press enter twice after typing out full completion

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11944]
If I have a variable, say `set`, and type `set` in the debug console, then the completions popup is visible with `set` and any other completions. Then the user has to press enter twice - once to close the completions popup, and again to eval `set`.

![image](https://cloud.githubusercontent.com/assets/323878/18468282/8a05fa5c-79a3-11e6-8654-89b8aad2555a.png)

I think that if the user has typed the full name of the completion, then pressing enter once should close the popup and eval that value. But if the user only types part of the completion like `se`, it should work as it does now.

**Comment by isidorn** [comment]
This is how the suggest widget accept on enter behaves also in the editor.
We should be consistent. Thus assigning this to @jrieken to consider if it should be changed everywhere.

**Comment by jrieken** [comment]
Disagree - the editor and the repl are different beasts and accepting inserting a new line whenever you auto complete doesn't make sense in the editor. I am pretty sure @isidorn is aligned on that. Either change the default for the repl or tell users to do so - the change should be trivial, just preprint `^` to key. That tells the service to trigger listeners but still handle the event as it would do without keybindings

**Comment by isidorn** [comment]
> preprint `^` to key

@jrieken Thanks for the tip, but what exact key do you mean? I tried preprinting it to the [currentWord](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes.ts#L339) but that did not work.

**Comment by jrieken** [comment]
Sorry, prepend to the command id, like we do it [here](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L198) in TypeScript which means. Bind `.` to run the command *and* insert dot-character.

**Comment by isidorn** [comment]
Thanks @jrieken this works however as you said this makes the suggestion be accepted and the listeners triggered - which in my world means a new line is added on enter(editor reacted on the listener). I would need two of my actions to be exectued, suggestion accepted and repl input accepted and only in the special case that the input matches the whole selection. Not sure if this is possible.

For comparison chrome dev tools always evalutes on enter and never acceppts the suggestion - I am also against that since it is much different behavior than our editor. Also the user can configure this via `"editor.acceptSuggestionOnEnter": false`

**Comment by jrieken** [comment]
I wasn't trying to say what the repl should do. Surely this isn't a default for the *normal* text editor, for the repl maybe and iff not it the configuration users have to do

**Comment by isidorn** [comment]
Decided that this is less frustrating than #18751
So reopening and will have to do a proper solution for this one in the future - something similar to what chrome dev tools are doing

**Comment by isidorn** [comment]
fyi @jrieken this is the issue I was mentioning in the standup
I was searching through suggest widget feature requests but could not find the one you mentioned that people already want this.

**Comment by isidorn** [comment]
Assigning also to @jrieken and moving to the next milestone to potentially look into it then

**Comment by jrieken** [comment]
related to https://github.com/Microsoft/vscode/issues/15702. There is two options: Hide items that will result in a no-op or make Enter insert a newline for those items

**Comment by jrieken** [comment]
I have now implemented this, which is keeping perfect matches but not binding Enter for those.

![apr-03-2017 14-59-15](https://cloud.githubusercontent.com/assets/1794099/24610247/245cdc50-187e-11e7-94b2-0f51a637d208.gif)

**Comment by isidorn** [comment]
@jrieken OMG awesome. I owe you at least one beer for this!
