### ISSUE TITLE
Empty state for getting started

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119496]
When there are no items on the getting started it is a bit empty:

![image](https://user-images.githubusercontent.com/35271042/112032924-1f81f600-8afa-11eb-966a-6caa328bbd20.png)

We should try adding some placeholder text like Recents:
![image](https://user-images.githubusercontent.com/35271042/112033090-4ccea400-8afa-11eb-9c73-27ec591c84df.png)

Something like `You've finished all of your items` or `All done! New content will show up automatically.`? @digitarald can probably provide a better example 😄

**Comment by digitarald** [comment]
> When there are no items on the getting started it is a bit empty:

If users really x out all content getting started, I would interpret their intent as "give me back that space". Therefor, would it make sense for the right column to collapse when there is no content?

> Something like You've finished all of your items or All done! New content will show up automatically.? @digitarald can probably provide a better example 😄

Related, I did have an action item on my list to make completing items more rewarding. Reaching the end of a category right now does not celebrate the accomplishment right now.

In this area specifically we might already start celebrating achievements when some or all of the categories are completed; maybe pointing to our docs page to continue learning if they want to.

**Comment by misolori** [comment]
@digitarald yea let's create an issue for completing items and we can brainstorm some ideas
