### ISSUE TITLE
Debug: allow ctrl/cmd-click to run into a method/property

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119491]
One of my favorite features from Eclipse was being able to ctrl/cmd+click into a method/property to debug into that thing and stop right there. You basically could navigate the code while debugging very efficiently 👍

**Comment by isidorn** [comment]
So the implementation on eclipse would probably put an invisble breakpoint inside the method and continue.
Something like a smart Run to Cursor.

I think this is a fair feature request
fyi @weinand

**Comment by bpasero** [comment]
Yes, it is pretty much a smart version of "Run to Cursor".

**Comment by hediet** [comment]
Mentioning myself so I can find this issue later again. @hediet
I think this is a very nice extension of "Run to Cursor" and might be doable when there is support for customizable mouse buttons/key combinations.

**Comment by isidorn** [comment]
Let's not reopen this and try to merge discussion with https://github.com/microsoft/vscode/issues/123879
