### ISSUE TITLE
Improved visibility of high CPU extensions / language servers

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#119457]
Lately while I'm using VSCode it's basically always 100% CPU. Pretty annoying. I have a few projects open but nothing extreme (I'm not editing the Typescript compiler for example). If I check in `top` the culprit is almost always `Code Helper (Renderer)`. Not very useful.

Using `htop` or similar you can see the full command, e.g. the one that is currently at 100% CPU for me is Pylance:

```
/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer) /Users/timh/.vscode/extensions/ms-python.vscode-pylance-2021.3.1/dist/server.bundle.js --cancellationReceive=file:480af1fc50513db33a8cfd8bd43722210c2d8e8010 --node-ipc --clientProcessId=11234
```

However I have observer 100% CPU with basically all languages I use: Rust-analyzer, Pylance, cpptools and ESlint/Typescript. I'm guessing they're just buggy.

It's probably infeasible to fix all of those extensions, but it would be nice if VSCode at least worked around their bugginess. Currently the only effort it goes to here is the Process Explorer, but it usually doesn't even show these processes!

![image](https://user-images.githubusercontent.com/376842/111989381-9672bb00-8b09-11eb-8496-302bc3ccb351.png)

No mention of pylance there! In fact it's not even showing the right window - I have several open but it's showing some random window that isn't even focused. It should surely show all windows?

I suggest the following:

1. Fix the Process Explorer so it actually shows all windows & processes
2. Add a dedicated CPU usage view for language servers/extensions.
3. If a language server/extension is detected as using 100% CPU for more than a certain amount of time, show a notification with an offer to restart it.
4. If possible, add an option to throttle language servers/extensions (e.g. using `nice`).

**Comment by jrieken** [comment]
We have all of that for extensions (F1 > Running Extensions) and automatic extension profiling

**Comment by Timmmm** [comment]
> We have all of that for extensions (F1 > Running Extensions) and automatic extension profiling

Are you sure? That list just seems to show activation time. It doesn't show CPU usage at all. And what do you mean by automatic extension profiling? I have yet to see any notifications about extension CPU usage despite several bugs that cause 100% CPU in various extensions.

Also that is not very discoverable. It should probably be in the Help menu or at least linked from the Process Explorer (which is discoverable).
