### ISSUE TITLE
Sash on Safari on iPadOS

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#119412]
This is the sash between views on Safari on iPadOS:

<img width="1194" alt="vscode-internalbacklog  Codespaces" src="https://user-images.githubusercontent.com/4674940/111910682-a31ae480-8a1f-11eb-8712-374c1bcc529c.png">

**Comment by joaomoreno** [comment]
@kieferrm I'm guessing this is only when you drag it and not its default state?

Would be fixed by https://github.com/microsoft/vscode/issues/118852#issuecomment-800056857

**Comment by kieferrm** [comment]
Yes, this is when hovering over a sash.
