### ISSUE TITLE
Unexpected [ts] errors in JavaScript files (revival)

### ISSUE THREAD

**Issue by dylanh724** [microsoft/vscode#119405]
https://github.com/microsoft/vscode/issues/54261

^ This was closed without any form of documentation or summary - what was the result of this? I'm still having this error in 2021.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo please post version and platform information, confirm that the problem also happens when you launch with all extensions disabled (code --disable-extensions), then post as text a small code sample to reproduce your issue with.
