### ISSUE TITLE
can't type letter l (as in word - help)

### ISSUE THREAD

**Issue by primerov** [microsoft/vscode#119484]
We have written the needed data into your clipboard because it was
Issue Type: <b>Bug</b>

letter l (small letter L) is not typed, for example, a word help, would be hep. When i press l key on my keyboard nothing happens. When I press Shift+l i can type capital L, but i can't type normal l. 

When I run Jupyter notebook in VSC I can type small l without any issues. 

I tried all kinds of keyboards in Windows (French, German, English) nothing helps, i can't type l anywhere in vsc. Not for the file name nor somewhere inside the code. Only in Jupyter notebooks

I can also type l properly in Terminal

I tried to uninstall and reinstall VSC, the problem still persists. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (23.71GB free)|
|Process Argv|--crash-reporter-id 782d57f0-b71d-42b7-bd5b-e40c5e9bc4d1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
bracket-pair-colorizer-2|Coe|0.2.0
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

 too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate whether your 'l' key is bound to a command.

**Comment by primerov** [comment]
Thanks! indeed it was bounded to a command.
