### ISSUE TITLE
TS compiler to compile only changed files

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode#11948]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. TS compiler to compile only changed files
2. for eg 100 files  only one changed

**Comment by waderyan** [comment]
@ydcoming thank you for opening this issue. Can you provide me with a simple example I can use to recreate the issue you are seeing?

**Comment by waderyan** [comment]
Closing until more info is given.
