### ISSUE TITLE
Allow font-family selection in Preferences through substrings and/or regexp

### ISSUE THREAD

**Issue by afeinman** [microsoft/vscode#119498]
Feature request:

Allow users to optionally specify font names by unambiguous substring or by regex, for example, "Fantasque" or /Fant.*Sans.*Nerd/ for "FantasqueSans Mono Nerd Font".

This would simplify switching between font families, which today is an exercise in frustration if you get a font name subtly wrong. (e.g. the string above is wrong; you need to say "FantasqueSansMono Nerd Font").

**Comment by IllusionMH** [comment]
CSS doesn't allow this kind of matches and AFAIK VS Code just add Font Family string as font-family for component with code etc.

**Comment by Tyriar** [comment]
Yeah I don't think this sort of thing isn't really possible without a lot of work, and hardly anyone would discover it's possible in the end anyway.
