### ISSUE TITLE
Debug: callstack view has weird behaviour with showing line/col info

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119488]
This is somewhat weird:
* the info hides when I click on a line
* the info comes back at a different location when I hover out

![recording](https://user-images.githubusercontent.com/900690/112027023-16fbe080-8b37-11eb-90cd-8a6c7e3f826d.gif)

**Comment by isidorn** [comment]
Yes this is a legitimate bug. The issue is that the restart frame action should be there, thus we have this smart hideing.
However in this case the Restart Frame action is not supported since it is an async stack frame. And if the restart is not supported we should not hide stuff.
