### ISSUE TITLE
Default terminal profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119454]
The current default set of profiles are:

```json
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell"
    },
    "Git Bash": {
      "source": "Git Bash"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": []
    },
    "Windows PowerShell": {
      "comment": "note that this will not be included in the quickSelect drop down if another version of powershell is installed",
      "path": [
        "${env:windir}\\Sysnative\\WindowsPowerShell\\v1.0\\powershell.exe",
        "${env:windir}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
      ],
      "args": []
    },
    "WSL": null,
    "Cygwin": null
  }
```

I don't think we should have Cygwin, WSL or Windows PowerShell here. For Cygwin/WSL is doesn't really add much especially now since we have the create quick launch profile button which we should recommend as the main way of creating these profiles:

![image](https://user-images.githubusercontent.com/2193314/111984701-f301b600-8ac8-11eb-8565-2d332116b72a.png)

For Windows PowerShell, I think we should roll that fallback into the PowerShell source which I think is already happening. If then someone wants to add a "Windows PowerShell" item to their quick launch profiles they can do so manually via the add quick launch profile button, which will get the correct path for the system automatically. Currently it looks like it's hardcoded to hide this in the quick launch list.

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/commit/76b1ad1d1dcc841b1e85060bd48777f3570ac091

**Comment by TylerLeonhardt** [comment]
Is it expected that the WSLs should be in the list on the right if they are not defined in the settings?
![image](https://user-images.githubusercontent.com/2644648/112550378-8282bf80-8d7c-11eb-9be0-94ba4980410d.png)

**Comment by TylerLeonhardt** [comment]
I'm slightly concerned with not having Windows PowerShell, but I think we should wait for users to tell us otherwise.

**Comment by Tyriar** [comment]
@TylerLeonhardt wsl is driven by a separate setting since they're picked up dynamically, we can't statically define all current and future WSL distros.
