### ISSUE TITLE
"Recent Folders & Workspaces" shows named workspaces as "Untitled (Workspace)"

### ISSUE THREAD

**Issue by LeCyberDucky** [microsoft/vscode#119418]
Hi, I'm experiencing some trouble with using workspaces. When I save a workspace with a specific name, I used to be able to open it again from the "Recent Folders & Workspaces" section when righ-clicking VS Code or just searching for it in the Windows start menu. Now, however, any such workspaces that I create just show up as "Untitled (Workspace)". This behavior has only started within the last couple of weeks, I would say. I liked using this for launching VS Code in a specific workspace. This happens on the normal stable build of VS Code, but to be sure, I also downloaded a fresh copy of the newest insider build and managed to recreate the issue directly after installing it, without changing any settings or installing any extensions. 

- VS Code Version: 1.54.3 (also tested on 1.55.0-insider)
- OS Version: Windows 10 build 19042.868

Steps to Reproduce:

1. Open VS Code as a New Window
2. File --> Save Workspace As...
3. Specify a name and save the workspace
4. Right-click VS Code in the task bar or search for it in the Windows start menu
5. See that a workspace with the name specified isn't listed under "Recent Folders & Workspaces". Instead, it is listed as "Untitled (Workspace)"

Does this issue occur when all extensions are disabled?: It occurs with a completely fresh insider build without any extensions installed.

I tired searching for similar issues, but I wasn't able to find anything similar, so I hope somebody can help me out with this, as this issue has turned out to be quite annoying. I'm happy to provide more information or perform further steps if needed.

**Comment by bpasero** [comment]
Can you try to run `code-insiders --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by bpasero** [comment]
Opening up for "help wanted" if someone can confirm on Windows.

**Comment by LeCyberDucky** [comment]
Thanks for getting back to me. I created an empty folder and did what you suggested, but the same thing happens. This first image shows what happens when I right-click VS Code in the taskbar before creating/saving my workspace: 

![image](https://user-images.githubusercontent.com/19520383/111961709-aa122780-8af1-11eb-90fc-f19e830db5c8.png)

The next image shows what I see after saving the workspace: 

![image](https://user-images.githubusercontent.com/19520383/111961826-cf9f3100-8af1-11eb-91b3-69be83426469.png)

The name of the workspace I created is shown correctly at the top of VS Code: 

![image](https://user-images.githubusercontent.com/19520383/111961864-db8af300-8af1-11eb-8673-805ec2c34cd7.png)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/7a1302a2b6c77147670cf707f992e82670ef09f8/src/vs/platform/workspaces/electron-main/workspacesHistoryMainService.ts#L405

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/a233c8683a2ba5b212c28d15d5374643aa6921bf

**Comment by aeschli** [comment]
@bpasero Thanks for looking into the issue and pushing a233c86. Can we close the issue then?

**Comment by LeCyberDucky** [comment]
I just updated to the newest insider version, and it seems to be working as intended now, so I'll close the issue. Thank you very much for working this out so quickly 😀

**Comment by isidorn** [comment]
Adding verified per @LeCyberDucky comment
