### ISSUE TITLE
Insider new welcome page| Getting started header displayed even with hidden all categories.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119456]
- VS Code Version: 1.55.0 Insider 469e4f6e2755b220dae3eccb04d1ddc587b84a5a
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:
Getting started header displayed even with hidden all categories.

```
  "workbench.welcomePage.hiddenCategories": [
    "Setup",
    "Beginner"
  ]
```

![image](https://user-images.githubusercontent.com/17777237/111988376-19e7d880-8b19-11eb-8ec6-b5c019db008e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
Thanks for the report! Going to track this with #119496
