### ISSUE TITLE
@optional services are risky

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119440]
I think we recently introduced a lot more `@optional` services and none of them declare the service as ` | undefined` which essentially breaks our strict null benefits:

![image](https://user-images.githubusercontent.com/900690/111957424-476a5d00-8aec-11eb-9160-125e9192e962.png)

Assigning a few people based on usages and @jrieken to comment whether we should maybe get rid of this concept altogether because it is easy to introduce runtime errors with it.

Imho no service should be optional, rather if one does not exist in a certain environment it should be stubbed as a no-op implementation.

**Comment by Tyriar** [comment]
> none of them declare the service as | undefined

Many of them do FYI, note that you cannot declare this `| undefined` in the ctor as you end up with a compile error:

```ts
@optional(ILocalTerminalService) localTerminalService: ILocalTerminalService | undefined,
```

Results in:

```
[04:14:10] Error: E:/GitHub/microsoft/vscode/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts(933,26): No overload matches this call.
  Overload 1 of 10, '(descriptor: SyncDescriptor2<number, TerminalConfigHelper, ITerminalProcessManager>, a1: number, a2: TerminalConfigHelper): ITerminalProcessManager', gave the following error.
    Argument of type 'typeof TerminalProcessManager' is not assignable to parameter of type 'SyncDescriptor2<number, TerminalConfigHelper, ITerminalProcessManager>'.
      Property 'ctor' is missing in type 'typeof TerminalProcessManager' but required in type 'SyncDescriptor2<number, TerminalConfigHelper, ITerminalProcessManager>'.
  Overload 2 of 10, '(t: typeof TerminalProcessManager, ...args: never): TerminalProcessManager', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'never'.
[04:14:10] Error: E:/GitHub/microsoft/vscode/src/vs/workbench/contrib/terminal/test/browser/terminalProcessManager.test.ts(37,13): No overload matches this call.
  Overload 1 of 10, '(descriptor: SyncDescriptor2<number, TerminalConfigHelper, TerminalProcessManager>, a1: number, a2: TerminalConfigHelper): TerminalProcessManager', gave the following error.
    Argument of type 'typeof TerminalProcessManager' is not assignable to parameter of type 'SyncDescriptor2<number, TerminalConfigHelper, TerminalProcessManager>'.
      Property 'ctor' is missing in type 'typeof TerminalProcessManager' but required in type 'SyncDescriptor2<number, TerminalConfigHelper, TerminalProcessManager>'.
  Overload 2 of 10, '(t: typeof TerminalProcessManager, ...args: never): TerminalProcessManager', gave the following error.
    Argument of type 'number' is not assignable to parameter of type 'never'.
```

The current way I handle this is to set the service to another nullable property that has the correct type. It looks like these are the actual problem cases:

![image](https://user-images.githubusercontent.com/2193314/111981809-67d2f100-8ac5-11eb-9498-edd6003bd09b.png)

**Comment by Tyriar** [comment]
Also I much prefer this setting to a private member than stubbing out no-op services. I'd expect a lint rule to ban this regex would prevent this from happening in the future:

```
@optional.+(private|readonly|public)
```

**Comment by jrieken** [comment]
> to comment whether we should maybe get rid of this concept altogether because it is easy to introduce runtime errors with it.

Yes, optional service dependencies should be used super rarely, likely never. The original intend for optional service dependencies is Monaco vs VS Code, e.g a contribution that's shared between both "products" might work better with an additional, non-essential service. This usually only applies to things in 'editor/contrib' but can also be interpreted as sign of bad/tight coupling.

One sample is @sbatten's `ITASExperimentService` which is marked optional everywhere. However, the service is registered in [this file](https://github.com/microsoft/vscode/blob/efb75d7262e90503f72b658b6b4ce2aab40c2ced/src/vs/workbench/services/experiment/common/experimentService.ts#L312) (which is imported in `src/vs/workbench/workbench.common.main.ts`) and only used inside the workbench-layer.

**Comment by sbatten** [comment]
removed via https://github.com/microsoft/vscode/commit/60e3fd6a01f11fbec83c6db8b2b3420d49b7eb18

**Comment by jrieken** [comment]
ping @sandy081

**Comment by jrieken** [comment]
Remaining usages

- [ ] src/vs/platform/extensionManagement/common/extensionGalleryService.ts @sandy081 
- [ ] src/vs/platform/extensionManagement/node/extensionManagementService.ts @sandy081 
- [ ] src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts
- [ ] src/vs/workbench/contrib/terminal/browser/terminalEditorService.ts
- [ ] src/vs/workbench/contrib/terminal/browser/terminalInstanceService.ts
- [ ] src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts
- [ ] src/vs/workbench/contrib/terminal/browser/terminalService.ts

**Comment by sandy081** [comment]
@jrieken My usage of optional services is because they (`IStorageService` & `IDownloadService`) are not available in CLI environment. 

Added DownloadService to CLI but we do not have support for StorageService in CLI. @bpasero any recommendations?

**Comment by bpasero** [comment]
@sandy081 then we add it? since workspace storage moved to `electron-main` years ago, we have full access to all storage from the main process.

**Comment by sandy081** [comment]
Seems its not trivial to add based on the comment from here https://github.com/microsoft/vscode/issues/63903#issuecomment-470836331

**Comment by bpasero** [comment]
Yes, CLI needs to join the running instance for such a call to storage. 

Since it was optional so far in the CLI, I would just throw in an in-memory storage service that does nothing to get away with it. Looks like we never needed it in the first place...

**Comment by sandy081** [comment]
I felt using in-memory storage service is error-prone especially there is no any hint in the code about it and going forward we might wrongly develop features in cli assuming storage service is available. 

Hence I had two versions of my service one with storage service and the other without and instantiating the right one in the given environment.

**Comment by jrieken** [comment]
@Tyriar this is now just terminal land

**Comment by Tyriar** [comment]
Terminal part is done 🎉 moving back to @jrieken to remove the decorator and any other related code

**Comment by jrieken** [comment]
Done. Thanks everyone for helping to clean this up 👯
