### ISSUE TITLE
VSCode opens unsaved deleted files

### ISSUE THREAD

**Issue by carrotfarmer** [microsoft/vscode#119460]
# Issue Type
**Bug**

# Details
- **VS Code Version**: 1.54.3
- **OS Version**: Ubuntu 20.04.2 LTS (Focal Fossa)

# Steps to Reproduce:

1. Create a folder & create a file inside that folder
2. Open the folder in VSCode
3. Edit the file
4. Close VSCode without saving the file
5. Delete the file/folder

You'll see that the file is still open in VSCode.

![image](https://user-images.githubusercontent.com/66675022/111991598-7f988c80-8b3a-11eb-90e6-a6b2fd506fd9.png)
![image](https://user-images.githubusercontent.com/66675022/111991690-96d77a00-8b3a-11eb-91da-5bfb106d5ac5.png)
![image](https://user-images.githubusercontent.com/66675022/111992564-92f82780-8b3b-11eb-9b48-8c4d3a9e8bb4.png)

### After deleting the folder:
![image](https://user-images.githubusercontent.com/66675022/111992825-e1a5c180-8b3b-11eb-9a21-fb876b744a5d.png)

# Does this issue occur when all extensions are disabled?:
**Yes**

This happens to me quite a few times. Is this is a feature? If it is, then is there any way to disable it?

**Comment by isidorn** [comment]
This is just how vscode behaves, I think this is by design.
However, forwarding to @bpasero so he can decide what to do here
