### ISSUE TITLE
Test workbench.hover.delay

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119470]
Refs: https://github.com/microsoft/vscode/issues/117894

- [x] macOS @digitarald
- [x] linux @chrmarti
- [ ] windows @fiveisprime (Optional)
- [x] windows @connor4312

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119470%0A%0A)

---

1. The delay before custom tree view hovers show is now configurable via `workbench.hover.delay`. Currently, only custom trees use this setting. Verify that the setting name and description are clear.
2. Verify that the default on mac is 1500 ms or verify that the default on other systems is 500 ms.
3. Verify that the setting is respected.

**Comment by digitarald** [comment]
Confirmed with Issues list in the GitHub extension.

**Comment by TylerLeonhardt** [comment]
Closing for bookkeeping but feel free to test @fiveisprime
