### ISSUE TITLE
resolveTask on a TaskProvider returns a ProviderResult, but returning a Thenable always fails

### ISSUE THREAD

**Issue by nborko** [microsoft/vscode#119465]
Issue Type: <b>Bug</b>

According to the API docs, TaskProvider.resolveTask returns a ProviderResult<Task> (which could be a Thenable), but returning a Promise seems to always fail. Removing all asynchronous code and returning a valid Task object seems to be the only value the caller will accept.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.89GB free)|
|Process Argv|--crash-reporter-id 560cea1a-d5a4-459f-8172-cc4addf61b61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
vscode-monorepo-workspace|fol|1.3.1
csharp|ms-|1.23.9
vetur|oct|0.33.1
subtitles-editor|pep|1.1.3
rewrap|stk|1.14.0

</details>

**Comment by alexr00** [comment]
One of the our built in extensions returns a `Promise` and it is working as expected:

https://github.com/microsoft/vscode/blob/3da9f36645d70bb35da19b4667ed0d2a285ff5cf/extensions/npm/src/tasks.ts#L60-L61

**Comment by nborko** [comment]
Here are the steps I am doing, in resolveTask which causes the behavior:

1) create a new TaskDefinition from the passed task.definition
1) check the definition for any uninitialized or empty properties
2) call window.showInputBox to get the values needed
3) return a new Task with the new definition and same task.scope and task.name, which contains a CustomExecution

If no tasks are defined in tasks.json, a default from provideTasks that has all of the empty properties gets resolved when running any pre-definied task. The input box prompts the user for each of the empty TaskDefinition properties.

Then, create a definition in tasks.json with some, not all of the prompted properties filled in (anything except a default that is also returned from provideTasks).  resolveTask ends up being called twice, the input boxes shown twice, and ends in an error that there is no task provider for the task. If ALL the required properties have a value in tasks.json, causing no prompts (and therefore no asynchronous calls), same result. Commenting out all the asynchronous calls and returning only a new task, same result. Removing async from the resolveTask definition, works just fine.

So removing the asynchronous code from resolveTask works in any case, which is what I ended up doing, and moved the user prompts to the CustomExecution code. It just seems like reolveTask should have worked as it was, but it doesn't resolve the

**Comment by alexr00** [comment]
> create a new TaskDefinition from the passed task.definition

Can you check the developer tools console (command Developer: Toggle Developer Tools)? It is a requirement of `resolveTask` that you use the _exact same_ `definition`. There should be in error in the console to that effect.

**Comment by nborko** [comment]
The error on the console is:

Error: The *taskname* task detection didn't contribute a task for the following configuration:
(excerpt of task.json follows)
The task will be ignored.

This behavior makes sense in light of the fact that the definition of the returned task must be the exact definition on the incoming task argument. However, that requirement is not documented anywhere as far as I can tell.

The API docs read, "Tasks are often created from information found in the tasks.json-file. Such tasks miss the information on how to execute them and a task provider must fill in the missing information in the resolveTask-method." Apparently that does *not* include the definition, and I would suggest noting in the docs the requirement that the `task.definition` passed to resolveTask must be the *exact same* definition in the resolved Task.

By the same token, it's unclear from the docs if other values passed to the Task constructor must also match the incoming task object exactly, i.e. `scope` and `name` (since clearly the task type must match, and execution is what resolveTask is aiming to resolve). The example code in https://github.com/microsoft/vscode-extension-samples/blob/main/task-provider-sample/src/customTaskProvider.ts implies that neither `scope` nor `name` need match, since the resolved task always has a scope of `TaskScope.Workspace` and a deterministic name that may or may not match the name in tasks.json.

Thanks for your time.

**Comment by alexr00** [comment]
👍 Updated documentation with 684a4526059fd58f19a6d0f1ee59699e40c6084a
