### ISSUE TITLE
Please support Command-E on macOS for initiating find

### ISSUE THREAD

**Issue by bpietsch** [microsoft/vscode#119431]
On macOS, there is a standard idiom for searching in the form of selecting the text to search for and typing command-E (generally followed by command-G to iterate through the results). VSCode seems to only support initiating search via command-F. It would be great if VScode conformed to this standard idiom on the macOS platform like all other text editors do. (Bonus points for also not bringing extra find UI in the upper right corner when using command-E as well)

Thanks!

**Comment by ArturoDent** [comment]
You can associate those keys with the commands yourself with the following keybindings:

	{
		"key": "cmd+e",
		"command": "actions.find",
		"when": "editorFocus || editorIsOpen"
	},
	{
		"key": "cmd+g",
		"command": "editor.action.nextMatchFindAction",
		"when": "editorFocus && findInputFocussed"
	},

It will bring up the Find widget, I don't think there is a way to avoid that.

Of course, those key sequences have other associated commands by default so you may want to have a look at what you are over-riding.

**Comment by bpietsch** [comment]
Thank you ArturoDent, looking at the keybindings, I realized I had an extension installed that had taken over cmd-E as the first key of several two key chords and that the default behavior for cmd-E is actually what I was asking for. Changing the bindings of the extension re-enabled the behavior. Thanks!
