### ISSUE TITLE
"Go to beginning of file" shortcut is triggering "second key of chord"

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode#119445]
Issue Type: <b>Bug</b>

When I use the "go to beginning of file" shortcut, I get the notice "waiting for second key of chord":

<img width="405" alt="Screenshot 2021-03-22 at 08 35 25" src="https://user-images.githubusercontent.com/102141/111962186-e9d51100-8ae9-11eb-8df0-7f3a256f34ae.png">

This seems to conflict with the shortcuts as documented here: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

Note that this does not happen when I use the "go to end of file" shortcut. 

VS Code version: Code 1.54.3 (Universal) (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|../../ --crash-reporter-id cba1ab8c-4d7d-4ea3-8a66-ff3f14637674|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
vscode-styled-components|jpo|1.5.0
syntax-project-pbxproj|mar|0.1.3
dotenv|mik|1.0.1
azure-pipelines|ms-|1.183.0
azure-account|ms-|0.9.7
vscode-gradle|ric|3.6.1
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscode-java-debug|vsc|0.32.0
vscode-java-test|vsc|0.28.1
codetour|vsl|0.0.47
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by badsyntax** [comment]
I've figured out this is due to the [codetour](https://github.com/microsoft/codetour) extension. Disabling that extension fixes this. I will create an issue in that repo.

**Comment by gjsjohnmurray** [comment]
:+1:

/causedByExtension
