### ISSUE TITLE
Debug: show statement that is stopped

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119485]
Here is how a stopped line looks like:

![image](https://user-images.githubusercontent.com/900690/112026067-1f9fe700-8b36-11eb-896f-ceab76547bda.png)

Compared to devtools:

![image](https://user-images.githubusercontent.com/900690/112025963-0860f980-8b36-11eb-904c-bae0e27480fc.png)

It really helps me to see at what part of the line the debugger is currently at.

**Comment by bpasero** [comment]
Especially useful when we break inline:

![image](https://user-images.githubusercontent.com/900690/112027683-b3be7e00-8b37-11eb-81dd-130f9a8dc070.png)

**Comment by isidorn** [comment]
We can do this, we just decided to only show the inline decoration when the stop is on the same line as the previous stop.
Assigning to this milestone to investigate this week

**Comment by isidorn** [comment]
I just tried this out to always show this decoration and I really like it. However I prefer to push start of debt week to have a whole milestone to gather feedback

![Screenshot 2021-03-24 at 12 43 58](https://user-images.githubusercontent.com/1926584/112305177-ad96e180-8c9e-11eb-9961-08a8ffe16851.png)
![Screenshot 2021-03-24 at 12 44 01](https://user-images.githubusercontent.com/1926584/112305186-ae2f7800-8c9e-11eb-973d-3a0c92509f0e.png)

**Comment by isidorn** [comment]
Pushed this. Let me know your thoughts.

**Comment by stefanhaller** [comment]
I see how this can be useful in languages that actually support stepping throw multiple statements on a single line.

In languages that don't, though, this is unnecessary and distracting. I do most of my debugging in C++ these days, and now the lines of source code wiggle right and left as I step through them, for no benefit. This is quite annoying. The current statement indicator in the gutter on the left is totally sufficient for such languages.

I would like to be able to turn this off (ideally per language). Or better yet, it should be off automatically for C++. (I don't see breakpoints in the middle of a line either in C++, which is good.)

**Comment by isidorn** [comment]
Please try vscode insiders from today, it should be better. Though this build might not yet be out since we froze it for another reason. Anyways next build should be better.
We now only render this when the language provides a column > 1. C++ probably provides column = 1

**Comment by stefanhaller** [comment]
I _am_ using today's insiders (30dcb112b4), I was hoping that 6a1404a6f80e3 would fix this.

It doesn't though, the column is usually > 1 in C++. It does actually put the indicator at the beginning of statements (e.g. after the opening `(` of an `if` statement). It's still useless though, as it's not possible to break on different columns of a line.

**Comment by isidorn** [comment]
Ok thanks. So it seems like the C++ debugger sends the correct column even though it does not support stepping on mulitple statements on a line.

@weinand @connor4312 let me know you think here. I see two options:
1) We go back to previous approach
2) We introduce a capability for this (debugger supports step into column or something)

I guess 1) is the easiest solution

**Comment by stefanhaller** [comment]
Actually I take that back. It turns out that it is actually possible to get the indicator to show up at different positions in a line, for example with chained function calls, and using combinations of Step Into and Step Out to move through the chain. In this situation the indicator could actually be useful to show you where you are. I suppose I'll try a bit longer to get used to the wiggling.

**Comment by isidorn** [comment]
@stefanhaller previously we had heuristic to only show the indicator when the previous step location is the same as the current one (which means that you stepped and remained on the ine)

**Comment by stefanhaller** [comment]
Ah, I see. But that means that you don't get the indicator in this one, somewhat rare situation where it could actually be useful even in C++: for a statement like `obj.method().othermethod();`, and then stepping into `method` and out again.

**Comment by isidorn** [comment]
Correct.

**Comment by isidorn** [comment]
Adding bug so we get this verified in the endgame
