### ISSUE TITLE
What is this new control?

### ISSUE THREAD

**Issue by smlombardi** [microsoft/vscode#119459]
Issue Type: <b>Bug</b>

I just updated to latest Insiders and this control appeared at the left of the status bar.  What is it, and can I override the workspace theme to not be so prominent?

![libssettingsuisrclibpage-carrierspage-carriers component html — sendpro-web-apps-20210322_084845](https://user-images.githubusercontent.com/835148/111992405-c57a3400-8aeb-11eb-87d1-9865a7a77c28.png)

VS Code version: Code - Insiders 1.55.0-insider (469e4f6e2755b220dae3eccb04d1ddc587b84a5a, 2021-03-22T05:14:29.671Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 2989f78b-23b4-466d-ae73-bbe6c5fe1c40|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.0.1
Bookmarks|ale|13.0.4
project-manager|ale|12.0.1
ng-template|Ang|11.2.8
json-flattener|App|1.0.2
change-color-format|bbu|1.0.0
vscode-multi-line-tricks|big|0.0.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.17
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
todo-tree|Gru|0.0.208
helium-icon-theme|hel|1.0.0
json-to-ts|Mar|1.7.5
rainbow-csv|mec|1.8.1
ecdc|mit|1.4.0
HTMLHint|mka|0.10.0
theme-monokai-pro-vscode|mon|1.1.18
vscode-edge-devtools|ms-|1.1.4
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.0.3
vscode-versionlens|pfl|1.0.9
quicktype|qui|12.0.46
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0
vscode-stylelint|sty|0.86.0
vscode-input-sequence|tom|0.2.0
sort-lines|Tyr|1.9.0
errorlens|use|3.2.5
vscode-icons|vsc|11.2.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwslfolder:30278404
vscoresta800cf:30265948
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by ArturoDent** [comment]
If you hover over it, it says `Open a Remote Window`.  Right-click on it and you can choose to `Hide Remote Host`.
