### ISSUE TITLE
WorkspaceConfiguration.update API will remove the existing comments of launch.json

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#119439]
Our Java Debugger uses `WorkspaceConfiguration.update` API to insert more debug configurations into launch.json, but one problem with this API is that it reformats launch.json and remove the user's comments as well. The reformatting is not a big issue, but remove the existing comments looks like a bug.

**Comment by bersbersbers** [comment]
For anyone following this issue, duplicates are #110295, #99305 (both also closed as duplicates) and finally #29453.
