### ISSUE TITLE
In the Windows split screen mode, the document window of idea IDE will float and overflow, so the code hint list is not covered, which is great! 

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#119407]
Issue Type: <b>Bug</b>

In the Windows split screen mode, the document window of idea IDE will float and overflow, so the code hint list is not covered, which is great! 

VS Code version: Code - Insiders 1.55.0-insider (e4b1e9ac57ab3cc942ab9bff09967bf3238a7910, 2021-03-19T05:14:28.175Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.59GB (3.82GB free)|
|Process Argv|--crash-reporter-id 2babb761-7191-4446-a8f7-6fa7d0bbde1b|
|Screen Reader|no|
|VM|0%|
</details>

Please see VsCode
![111](https://user-images.githubusercontent.com/54253524/111905917-1442b200-8a89-11eb-855c-aae3ed0c5a14.png)
Look at idea IDE again 
![222](https://user-images.githubusercontent.com/54253524/111905955-3ccaac00-8a89-11eb-9067-1cf9c245158e.png)

**Comment by dbaeumer** [comment]
@zhouxinghong can you please attached the screen shot. I can't access it.

**Comment by zhouxinghong** [comment]
Hello there! I don't know why the screenshots can't be displayed directly in GitHub. You can visit the following: URL to get image information. They are different performances of VSCode and IDEA in the same operation.
vscode
https://user-images.githubusercontent.com/54253524/111905917-1442b200-8a89-11eb-855c-aae3ed0c5a14.png
idea IDE
https://user-images.githubusercontent.com/54253524/111905955-3ccaac00-8a89-11eb-9067-1cf9c245158e.png
![code](https://user-images.githubusercontent.com/54253524/112081139-22deb580-8bbe-11eb-8a08-52871632dab3.png)

idea IDE
![idea](https://user-images.githubusercontent.com/54253524/112081185-34c05880-8bbe-11eb-9ac1-c3bed260d228.png)

**Comment by zhouxinghong** [comment]
Additional question 2: The code hint list cannot be stretched from the left. At present, it can only be stretched from the right side, so it is not easy to use in some cases, and I hope it can be improved. Allow users to freely extend the code prompt list whether it is on the left or on the right
Please see the operation diagram:
![code](https://user-images.githubusercontent.com/54253524/112084740-4c9adb00-8bc4-11eb-8481-d09976275532.png)

**Comment by jrieken** [comment]
Thanks for reaching out. I understand and share your pain. Unfortunately we cannot (easily) render widgets outside the editor window. Closing as wont-fix

**Comment by zhouxinghong** [comment]
You are Welcome! I hope you can record this problem and fix it if you have the ability to do so in the future.
