### ISSUE TITLE
Comment align Golang 

### ISSUE THREAD

**Issue by ilGobbo00** [microsoft/vscode#119410]
Issue Type: <b>Bug</b>

After written some code and after aligned all comments, save the file with ctrl+s cause that all comments are displayed immidiately after all row of code (all alignment disappear) 

Example:

```
func f(){		// Create a function
	var a int = 0	// Create a variable
	a = 2 		// Change value
}
```

--after ctrl-s-->

```
func f() { // Create a function
	var a int = 0 // Create a variable
	a = 2 // Change value
}
```

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7410 APU with AMD Radeon R5 Graphics     (4 x 2196)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.95GB (2.79GB free)|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
god|bas|0.0.100
code-runner|for|0.11.3
go|gol|0.23.2
kite|kit|0.142.0
vscode-language-pack-it|MS-|1.54.2
cpptools|ms-|1.2.2
java|red|0.76.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by dbaeumer** [comment]
@ilGobbo00 this looks like an issue caused by the Go extension. Please report the issue there.
