### ISSUE TITLE
Settings Sync silently stops syncing

### ISSUE THREAD

**Issue by Svish** [microsoft/vscode#119497]
Issue Type: <b>Bug</b>

From time to time I discover that VS Code has stopped syncing my settings, as far as I've noticed, without letting me know.

It seems to be because the authentication expires or something, so re-authenticating seems to get it started again. Either way, I find it really annoying that VS Code doesn't give me a super obvious error/warning when I have Settings Sync enabled, and it for some reason suddenly can't sync anymore.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (19.60GB free)|
|Process Argv|--folder-uri file:///d%3A/projects/bibelstudiet.no-next --crash-reporter-id 621382b3-0882-41de-9f1c-f6ee37660320|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
preview-pdf|ana|0.0.3
color-info|bie|0.5.1
vscode-styled-jsx|bla|2.0.0
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.5.9
npm-intellisense|chr|1.3.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
search|dba|1.1.3
vscode-faker|dee|1.5.0
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.17
vsc-material-theme|Equ|33.1.2
prettier-vscode|esb|6.3.1
php-debug|fel|1.14.9
php-pack|fel|1.0.2
vscode-text-pastry|jkj|1.2.0
svg|joc|1.4.5
vscode-gutter-preview|kis|0.27.1
sftp|lix|1.12.9
ecdc|mit|1.4.0
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vsliveshare|ms-|1.0.3968
debugger-for-chrome|msj|4.12.12
gremlins|nho|0.26.0
hide-gitignored|npx|1.1.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.6.0
vscode-sort-json|ric|1.20.0
vscode-sanity|san|0.1.4
mdx|sil|0.1.0
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-mermaid-preview|vst|1.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by sandy081** [comment]
You shall see a badge in the bottom left corner when settings sync authentication fails, please let me know if you see that? If not can you please provide us settings sync logs (F1 > Open View > Log (Settings Sync))

![image](https://user-images.githubusercontent.com/10746682/112059975-dadb7680-8b5c-11eb-9c96-b75a5a6325c4.png)
