### ISSUE TITLE
,    g  

### ISSUE THREAD

**Issue by Hasintha-Jayasinghe** [microsoft/vscode#119411]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by dbaeumer** [comment]
@Hasintha-Jayasinghe please provide a detailed description about your issue and steps on how to reproduce. When done I will reopen the issue.

**Comment by Hasintha-Jayasinghe** [comment]
Yeah this issue was resolved into the last release of vscode
