### ISSUE TITLE
[Web] Character duplicating when using IME Chinese inputs on Safari

### ISSUE THREAD

**Issue by bummoblizard** [microsoft/vscode#119469]
- VS Code Version: Web Playground
- OS Version: macOS 11.1

I cannot reproduce this issue on Chrome, so it's probably related to Safari.

Steps to reproduce the issue:
- Enable Sucheng Input method (or any other Chinese IME input method) `System Preferences > Keyboard > Input Sources > Add > Chinese, Tranditional > Sucheng`
- Switch OS input method to Sucheng
- Visit https://vscode-web-test-playground.azurewebsites.net/ with Safari
- Type `f` and press Enter twice. 
- The character is input twice

https://user-images.githubusercontent.com/38398443/112003599-feea8800-8b5b-11eb-8693-218ee82e9762.mov

Here's how electron VS Code (or Chrome) behaves: 

https://user-images.githubusercontent.com/38398443/112003620-027e0f00-8b5c-11eb-9fef-0b9ea7891d4c.mov

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Fixed via 0d26b20c7cb8b1d4935f4e79c5e798c0c9437523
