### ISSUE TITLE
Unable to Open From system problems tab of line, will generate to read double addres From File

### ISSUE THREAD

**Issue by PutuSuhartawan** [microsoft/vscode#119422]
![image](https://user-images.githubusercontent.com/71969427/111923857-429dad00-8adc-11eb-8862-c485d7ec7cd7.png)

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
These diagnostics are generated by the extension and so the links associated to them. It seems the extension is creating invalid or not existing links. So please file the issue against the extension.
