### ISSUE TITLE
Remote Desktop Can't Input

### ISSUE THREAD

**Issue by oneplusdash** [microsoft/vscode#119400]
VS Code Version: 1.54.3
Remote Machine OS Version: Windows_NT x64 19042.868
Local Machine OS Version: Windows_NT x64 19042.868
After I use the mstsc.exe remote desktop connection ( VS Code window is on the remote machine), I use vscode to find that he often gets stuck and can’t input.

**Comment by dbaeumer** [comment]
Not sure who should own this @deepak1556 @sbatten

**Comment by sbatten** [comment]
@oneplusdash are you saying the VS Code window is on the remote machine or these things are happening in parallel?

**Comment by oneplusdash** [comment]
> @oneplusdash are you saying the VS Code window is on the remote machine or these things are happening in parallel?

S Code window is on the remote machine

**Comment by oneplusdash** [comment]
> > @oneplusdash are you saying the VS Code window is on the remote machine or these things are happening in parallel?
VS Code window is on the remote machine

**Comment by oneplusdash** [comment]
> @oneplusdash are you saying the VS Code window is on the remote machine or these things are happening in parallel?
VS Code window is on the remote machine

**Comment by a351399739** [comment]
Same problem in my vscode and other software base in vscode.
An other phenomenon is: when I went back to the remote computer and use it directly, the  stuck will not disapper so I must restart these software.
It  happen EVERYTIME.

my vscode and os version :
![image](https://user-images.githubusercontent.com/23499622/112123590-593b2580-8bfc-11eb-9586-953363f37d82.png)

**Comment by sbatten** [comment]
@oneplusdash @a351399739 I am still unclear on your scenario. Could you please provide repro steps or a recording of your experience?

**Comment by oneplusdash** [comment]
> @oneplusdash @a351399739 I am still unclear on your scenario. Could you please provide repro steps or a recording of your experience?

Run VSCODE on computer A, and computer B connects to computer A through remote desktop. Then you will find that the VSCODE in A is stuck and cannot be entered. (The remote desktop connection tool uses mstsc.exe)

**Comment by deepak1556** [comment]
Remote desktop support is highly untested in the Electron runtime vscode uses, there is not much we can do here.  Please use our remote development setup as alternative which is well-tested https://code.visualstudio.com/docs/remote/remote-overview#_remote-development-extension-pack

**Comment by yanyuandaxia** [comment]
I use vscode to write python program. I also meet this problem every time. The windows openssh server service dose not support GUI, so I use pycharm now.
