### ISSUE TITLE
Debug: toggling inline breakpoints sometimes flashes the line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119486]
Unfortunately I cannot really record this in a gif, but I see the line flashing briefly sometimes when toggling inline breakpoints.

**Comment by isidorn** [comment]
Yes, the issue with this is that we are not doing delta's on a breakpoint line, but we get rid of them all and set them again.
I believe this is not an easy fix, thus for now assigning to next milestone and I might tackle it in debt week - though I am moving then so we'll see.

**Comment by isidorn** [comment]
Duplicate of issue Joh filled. I can find it if you care.
