### ISSUE TITLE
Extension command Description column is very narrow when there are custom menu contributions

### ISSUE THREAD

**Issue by qcz** [microsoft/vscode#119414]
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

The Description column of the Feature Contributions tab for an extension is very narrow when there are custom menus defined for the extension. All custom menu contributions show up with an `undefined` entry with a very wide content in the Menu Contexts column:
![Code_2021-03-21_19-01-27](https://user-images.githubusercontent.com/304384/111915777-3da71200-8a78-11eb-8ad7-6403577ca21a.png)
Normal commands show up like this:
![Code_2021-03-21_18-54-34](https://user-images.githubusercontent.com/304384/111915893-bd34e100-8a78-11eb-9c70-ebd9f8ee55c0.png)

Steps to Reproduce:

1. Open the Extensions sidebar and search for the "Text Power Tools" extension. This extension contributes custom menus for the editor context menu.
2. Switch to the "Feature Contributions" tab.
3. See that there is an undefined entry at the end of the Commands table with a very wide Menu Contexts value. A new menu context value is appended here for every custom submenu reference in the `menus` entry of the [package.json of this extension](https://github.com/qcz/vscode-text-power-tools/blob/master/package.json#L850-L914): `editor/context textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain textPowerTools.editorContextMain`
4. See that the Description column of the commands table is very narrow because of this.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/119495
