### ISSUE TITLE
showUnused: false not working, getting ts(6138) is declared but its value is never read with grayed out property

### ISSUE THREAD

**Issue by jlabaj** [microsoft/vscode#119473]
- VS Code Version:
- Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363
- OS Version:
Win 10

Steps to Reproduce:

1.compiler options in tsconfig are set as following:
"noUnusedLocals": false,
"noUnusedParameters" :false,
2. settings.json from vscode are set as following:
```
"[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true,
      "source.organizeImports": true
    },
    "editor.formatOnSave": true,
    "editor.showUnused": false,
  },
"editor.showUnused": false,
```

![image](https://user-images.githubusercontent.com/5179937/112006534-17d74700-8b24-11eb-89ba-cb5225c7e996.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Please share a small example project that demonstrates this issue

**Comment by jlabaj** [comment]
@mjbvz the issue is that the contractor parameter is private and it should't be because its a contractor parameter used only in the constructor in the super call.
