### ISSUE TITLE
Window scrolls down every time I type

### ISSUE THREAD

**Issue by KolyaIvankov** [microsoft/vscode#119493]
Issue Type: <b>Bug</b>

Every time I start typing a sequence of symbols, or press or hold Del or Backspace, the eidtor moves one line down. Restarting doesn't mitigate the problem. 

And by the way, the window in which I type this text to submit to GitHub also constantly changes this vertical size in a haphazard manner.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.83GB free)|
|Process Argv|--crash-reporter-id de5def01-989b-41de-ab17-25d5ebdcc01d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-tools|gee|1.1.2
vscode-mesh-viewer|mic|0.0.10
vscode-language-pack-de|MS-|1.54.2
csharp|ms-|1.23.9
cpptools|ms-|1.2.2
mono-debug|ms-|0.16.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to see if this is being caused by one of your extensions.

**Comment by KolyaIvankov** [comment]
@gjsjohnmurray Thanks for the reply. The culprit, as expected, is chsarp ms-1.23.9.

**Comment by KolyaIvankov** [comment]
I have posted the issue in omnisharp, and has gotten the following reply:

[OmniSharp issue #4451](https://github.com/OmniSharp/omnisharp-vscode/issues/4451)

> the extension doesn't engage in any line shifting activities - UI rendering is done by VS Code, so this looks like a VS Code problem. I guess one of the VS Code providers (code lens, references provider, completion provider etc) that C# extension register handlers for exhibits weird behavior under some circumstances specific to your machine (zoom level, localization, resolution etc). You can try resetting zoom level to default and if it doesn't help you should open a VS Code issue (https://github.com/microsoft/vscode) instead.

The issue was marked as closed and vscode was declared to have responsibility for it.

I have restored zoom to default - in fact, it was never changed from default, it didn't mitigate the issue. I have informed OmniSharp developers that I will repost their answer here.
