### ISSUE TITLE
Add right-click menu option to collapse folders on current node

### ISSUE THREAD

**Issue by claytongulick** [microsoft/vscode#119499]
When you have a project that has a deep structure and many (sometimes hundreds) of folders, expanding and collapsing folders is a core part of the development flow.

Frequently, it's desirable to collapse all of the folders in a subfolder, while leaving the current state of expanded / collapsed folders intact.

The current "collapse" functionality is all-or-nothing - when you select 'collapse folders in Explorer' it collapses everything, which destroys some painstaking folder expand / collapse activity you may have done.

It would be a great enhancement to be able to right click on a node in the explorer and select "collapse subfolders".

Update for clarity: this feature should recursively collapse-all at the folder level, the same way "Collapse Folders In Explorer" does, but at a subfolder level.

Thanks!!!

Edit: Bonus points for "expand subfolders" the same way 😄

**Comment by gjsjohnmurray** [comment]
If you click on the folder to focus it, then press the <kbd>LeftArrow</kbd> key this should do what you want.

**Comment by claytongulick** [comment]
Thanks @gjsjohnmurray ! It does indeed collapse the folder you're on when you do that - but not quite the feature I'm requesting.

I'm requesting a recursive "collapse all" / "expand all" at the folder level, not just collapsing the indicated folder - unless I'm missing something?

Though I do think it would be a nice additional enhancement to make a CTRL-LeftArrow CTRL-RightArrow (or similar) do this in addition to the context menu option.

**Comment by isidorn** [comment]
I think this is a request towards the tree, thus forwarding to @joaomoreno
My 2 cents: alt + click could collapse both the node and all children

**Comment by joaomoreno** [comment]
> My 2 cents: alt + click could collapse both the node and all children

Did you try it?

**Comment by isidorn** [comment]
@joaomoreno yes I tried alt + click and it is not working. Did you try? Does it work for you?

**Comment by joaomoreno** [comment]
Sure: https://github.com/microsoft/vscode/blob/771b0192f433e6cad6a06c9a62c5415ba9c3b713/src/vs/base/browser/ui/tree/abstractTree.ts#L1132

But note that in async trees (eg explorer):

- Recursive collapse works
- Recursive expand only works on nodes which were already resolved, since expanding unresolved nodes could potentially be infinite

**Comment by isidorn** [comment]
@joaomoreno it works fine. My mistake. When expanding I was mistakenly still holding down `alt`.


@claytongulick so this works, just use `alt` + click.
We will not change the explorer context menu
