### ISSUE TITLE
Make Updating Extensions Easier

### ISSUE THREAD

**Issue by martinpeck** [Microsoft/vscode#11943]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

At present, whenever I get an update to an extension I have to click "update" for each one, and then "enable" for each. Each time I enable an extension I'm prompted to restart VS Code.

In general, I just want to update and re-enable all of the extensions that have updates. A single "update and enable all" option would be really helpful. Even if this were to only be possible on already installed/enabled extensions, this would save a lot of time.

**Comment by joaomoreno** [comment]
This is already fixed and released.

![image](https://cloud.githubusercontent.com/assets/22350/18475328/512a331a-79c6-11e6-828e-b4c7ee0ff23f.png)

![image](https://cloud.githubusercontent.com/assets/22350/18475330/552c9e30-79c6-11e6-9af0-9ea01997ec4f.png)

There's even a setting that lets Code update them automatically:

![Uploading image.png…]()

**Comment by martinpeck** [comment]
Fantastic. I hadn't spotted the menu for extensions.
Thanks for the quick response.
