### ISSUE TITLE
Clicking URL/link in terminal leads to incorrect page

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode#119449]
- VS Code Version: `1.54.3 (user setup)`
- OS Version: `Windows_NT x64 10.0.19042`

Steps to Reproduce:

1. (Hard part) Trigger an error in the JS Debug Bootloader in VSCode terminal.
Note that clicking the URL to which the user should report opens the browser to URL `https://www.microsoft.com/de-de/?ref=aka`, which is not the correct report URL. Manually copying the URL and pasting it into browser instead works correctly.
````
Error in the js-debug bootloader, please report to https://aka.ms/js-dbg-issue: Error [ERR_INSPECTOR_ALREADY_ACTIVATED]: Inspector is already activated. Close it with inspector.close() before activating it again.
````

Does this issue occur when all extensions are disabled?: Yes, except the `Remote - WSL` extension as VSCode should run on WSL.

### Related issue
https://github.com/microsoft/vscode-js-debug/issues/947

**Comment by connor4312** [comment]
Thanks for the issue, but I'm having a hard time reproducing it. It should be reproducable just by console.log'ing that url -- can you any specific environment set up, such as the shell you're using?
