### ISSUE TITLE
Add .bicep seti icon to VSCode

### ISSUE THREAD

**Issue by anthony-c-martin** [microsoft/vscode#119467]
`.bicep` file icon was added in https://github.com/jesseweed/seti-ui/pull/586. VSCode should support it.

More information about Bicep: https://github.com/Azure/bicep

**Comment by misolori** [comment]
Thanks for the ping, we're currently in [endgame mode](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game) so this will have to be added next month.

**Comment by anthony-c-martin** [comment]
> Thanks for the ping, we're currently in [endgame mode](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game) so this will have to be added next month.

Thanks for the info!

**Comment by misolori** [comment]
For verification: create a `.bicep` file and ensure the file icon looks like this:

![image](https://user-images.githubusercontent.com/35271042/113533723-76b8a980-9583-11eb-84fe-dfceca63e155.png)
