### ISSUE TITLE
TypeScript file indexer is not exposed to extension developers

### ISSUE THREAD

**Issue by Ciantic** [Microsoft/vscode#11949]
In order to implement auto-import by symbol name in TypeScript one needs to have a file indexer available, or some way to get the filenames and paths of the given symbol.

There is a great extension for TypeScript by @buehler called [TypeScript Hero](https://github.com/buehler/typescript-hero/) but it needs to re-implement file indexer just to get auto-import working reliably, obviously this is hard task and should not be done lightly. [I opened an issue to his extension, and he mentioned this.](https://github.com/buehler/typescript-hero/issues/42)

Problem is easily illustrated by this screenshot: 

![image](https://cloud.githubusercontent.com/assets/64731/18434892/a696e948-78f8-11e6-9e36-451393c04039.png)

Apparently there is no way to get the filepath as underlined in above screenshot at the extension level.

**Comment by dbaeumer** [comment]
@waderyan correct. We had discussion around this and we do have plans to do something here. But we have not decided yet what exactly we will expose and when it will happen.

**Comment by mjbvz** [comment]
Try looking into using a [TS server plugin](https://github.com/RyanCavanaugh/sample-ts-plugin) for this sort of functionality. TS server plugins allow you to extend TypeScript's built-in functionality directly.

We are working on allowing extensions to contribute these plugins as well. Here's a prototype: https://github.com/mjbvz/test-vscode-tsserver-plugin
