### ISSUE TITLE
Allow debug adapter to list dynamic scripts in the file explorer

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11947]
It would be interesting if a debug adapter could send a list of files that can't be resolved to source files on disk - either because they are not associated with a file on disk (eval scripts) or can't be, because of sourcemap or other config issues, etc. This would allow the user to browse and set breakpoints in these scripts, which current you can only do if you use a `debugger` statement or manage to step into it from another script. It would also allow more transparency with config issues - if a breakpoint fails to bind in `app.ts`, but an `app.ts` with the wrong path shows up in the dynamic scripts section, then that would give you a better hint on how to fix your config. Currently you can only guess or dig through log files from the debug adapter.

The modules UI would be a good place to prototype this once that's supported. Then if it makes sense, we could try it in the file explorer.

**Comment by weinand** [comment]
since we got #20355 we are getting closer to this functionality.
