### ISSUE TITLE
Sometime my integrated terminal( Crtl + "~" ) doesnt print text. 

### ISSUE THREAD

**Issue by vivasvan1** [microsoft/vscode#119409]
Issue Type: <b>Bug</b>

it is not disconnected just doesnt show text.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-45-generic snap
Remote OS version: Linux x64 5.4.0-66-generic
Remote OS version: Linux x64 5.4.0-66-generic
Remote OS version: Linux x64 5.4.0-66-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|7.61GB (0.42GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 233e6692-c5f8-4e76-9250-1f271b3c296c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: ludwig|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 800)|
|Memory (System)|187.57GB (22.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ludwig|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 800)|
|Memory (System)|187.57GB (22.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ludwig|
|OS|Linux x64 5.4.0-66-generic|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 800)|
|Memory (System)|187.57GB (22.66GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
jinjahtml|sam|0.16.0
bootstrap4-vscode|the|6.1.0
vscode-office|cwe|2.0.1
vsc-python-indent|Kev|1.12.0
python|ms-|2021.3.658691958
vscode-pylance|ms-|2021.3.2
jupyter|ms-|2021.3.619093157
autodocstring|njp|0.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30277037
pythontb:30265425
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by vivasvan1** [comment]
I dont think it is reproducable but I will try to add a clip of it when it happens.

**Comment by vivasvan1** [comment]
https://user-images.githubusercontent.com/21074796/111994989-b8276e80-8b18-11eb-81b7-0b66c9fed04d.mp4

**Comment by vivasvan1** [comment]
https://user-images.githubusercontent.com/21074796/111995287-0b99bc80-8b19-11eb-84f4-be11dda4251d.mp4

**Comment by vivasvan1** [comment]
any reason why this could be happening?

**Comment by meowao** [comment]
It is happen in windows 10 with last version vscode

**Comment by meowao** [comment]
It's also happen when i run task and terminal dosen't show all text;

**Comment by meganrogge** [comment]
Any errors in dev tools when this happens? (Help > Open Developer Tools > Console)

**Comment by meowao** [comment]
> Any errors in dev tools when this happens? (Help > Open Developer Tools > Console)

There is not has any errors when output is incorrect;
![3](https://user-images.githubusercontent.com/13918627/113380511-03f6d500-93af-11eb-9651-4511216cd136.gif)
But there has some errors when output is correct;
![4](https://user-images.githubusercontent.com/13918627/113380572-28eb4800-93af-11eb-8155-9a06ee494eeb.gif)

**Comment by vivasvan1** [comment]
@meganrogge This is the console output.


console.ts:137 [Extension Host] (node:3902) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
v @ console.ts:137
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: blade
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: ejs
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: latte
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: tpl
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: twig
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: vue
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: vue-html
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: django-html
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: erb
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: HTML (Eex)
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: volt
_logMessageInConsole @ abstractExtensionService.ts:796
abstractExtensionService.ts:796 [thekalinga.bootstrap4-vscode]: Unknown language in `contributes.bootstrap4-vscode.language`. Provided value: nunjucks
_logMessageInConsole @ abstractExtensionService.ts:796
workbench.html:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by meganrogge** [comment]
Because of this line, 
> workbench.html:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

I'd suggest setting `terminal.integrated.gpuAcceleration` to off because your system might not be equipped for that and it's set to on by default now. 

Let me know if that helps.
