### ISSUE TITLE
Visual Studio Code isn't working correctly!

### ISSUE THREAD

**Issue by loowdev** [microsoft/vscode#119413]
Issue Type: <b>Performance Issue</b>

I have been using Visual Studio Code for the past three years plus, and I have never face this kind of issue before.

<b>My Issue:</b> When I start up VSCode it will work perfectly but after some hours of coding, VSCode will start to misbehave, VSCode will stop saving changes no matter how I hit CTRL + S, or File > Save, or File > Save All, and I'm also using auto-save but none of them work when VSCode start to misbehave, the only way to save my codes is to copy them and then restart VSCode then I will paste each code back to the files I copied them from, and this behavior is annoying, this behavior makes me lose so many codes, imagine working for hours just for VSCode to discard the changes, and whenever I hit CTRL + S, I believe my codes are save, and if not I believe auto-save will automatically save my codes.

Please resolve this issue, my ass is sweating, I'm losing too many codes.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.95GB (2.19GB free)|
|Process Argv|--crash-reporter-id 8ef6d2c6-3a67-473a-a920-868748b0b8a7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    71	 11976	code main
    2	    55	  3308	   window (Issue Reporter)
    0	    11	  6260	   crashpad-handler
    0	    23	  6264	   utility
    0	    65	 11484	   shared-process
    0	    27	  8696	     ptyHost
    0	   182	 11676	   window (index.js - editor - Visual Studio Code)
    0	    22	   360	     searchService
    0	    98	  9936	     extensionHost
    0	   337	  1824	       electron_node tsserver.js 
    0	    39	  2840	         electron_node typingsInstaller.js typesMap.js 
    0	    36	  7140	       electron_node tsserver.js 
    0	    24	  8932	       electron_node eslintServer.js 
    0	    24	 11536	       electron_node serverMain.js 
    0	    14	 11476	     watcherService 
    0	     5	 11012	       console-window-host (Windows internal process)
    0	    88	 12000	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.js - editor - Visual Studio Code)
|    Folder (editor): 38 files
|      File types: js(8) png(4) css(4) DS_Store(3) json(3) svg(2) zip(1)
|                  gitignore(1) html(1) txt(1)
|      Conf files: package.json(1);
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
php-debug|fel|1.14.9
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-todo-highlight|jgc|2.0.1
vscode-react-native|msj|1.4.1
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
mdx|sil|0.1.0
highlight-matching-tag|vin|0.10.0
vscode-import-cost|wix|2.15.0
material-theme|zhu|3.9.15

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by loowdev** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I have downloaded and installed VSCode insider, and I setup my IDE by importing my settings for the necessary extensions, and other settings.

But nothing seem to be improved, in the image below you will see the response from VSCode while trying to exit the application.

![Capture.PNG](https://user-images.githubusercontent.com/51025764/112071202-afae5280-8b6f-11eb-9325-21397b873647.PNG)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
