### ISSUE TITLE
web extension: Output from Extension Dev Host not shown in Debug Console

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#119417]
Latest insiders

- create a web extension with `yo code --insiders` and pick 'New Web Extension`, fill out details
- open the extension in code 
- in the generated `src/web/extension.ts` add a line `console.log('globalThis', globalThis);` to the command handler
- Run `F5` to start the extension (I did some work to improve the development experience for web extensions. The setting `extensions.webWorker` is no longer needed)
- Run the 'Hello World' command. The dev tools in the `Extension Dev Host` window show the globalThis, but not the Debug Console in the first window

**Comment by hombyk-nevzi2-dAxzyd** [comment]
src/vs/workbench/api/worker/extHostExtensionService.ts

**Comment by rzhao271** [comment]
I'm not sure if this is the expected output -- I still see `globalThis` show up in the debug console, but it shows different information than what the extension window devtools show.

![globalthis](https://user-images.githubusercontent.com/7199958/116729219-c54b3f00-a99b-11eb-8322-5f3cb31c0b27.png)

**Comment by connor4312** [comment]
Yep, that's very much intended 🙂 What you see logged there is a JSON serialization of globalThis send to the main thread/renderer. The console will show you the raw object from the runtime.
