### ISSUE TITLE
EOL-sensitive files.insertFinalNewline

### ISSUE THREAD

**Issue by thdoan** [microsoft/vscode#119423]
For people developing on Windows, it would be nice if there's an option to enable `files.insertFinalNewline` only when working with LF line endings. Maybe add one of the following options:
```
"files.insertFinalNewlineInLF": true
```
_or_
```
"[files.eol.lf]": {
  "files.insertFinalNewline": true
}
```

**Comment by alexdima** [comment]
cc @sandy081
