### ISSUE TITLE
Tab click automatically changes tree view

### ISSUE THREAD

**Issue by ptraceur** [Microsoft/vscode#11945]
- VSCode Version: 1.5.2
- OS Version: OS X

Hi, this is a function present in vscode since the top tabs are available, but for me it is an issue because I don't want it to act like that. I'm sure that there exists some developers who think the same, I'm not asking to remove this, but is there a way to enable and disable this option? If not, would be great to have one.

Thanks,
have a nice day.

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`

**Comment by ptraceur** [comment]
Thanks @bpasero, its good now. I went trough the Default Settings file, but since I'm not and english native speaker I didn't understand it was that flag. 

Thanks again.
