### ISSUE TITLE
mac 点击"检查更新报错"

### ISSUE THREAD

**Issue by gitWenLi** [microsoft/vscode#119447]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See this link for more information.
![image](https://user-images.githubusercontent.com/49370476/111970112-e6677700-8b35-11eb-8c98-c012224d753a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
If you follow the link you will find solutions for that problem.
