### ISSUE TITLE
Using ' or " in JSX crashes code formatting

### ISSUE THREAD

**Issue by tomaash** [Microsoft/vscode#11946]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Create a JSX or TSX file
2. Try to format code, it will work
3. Add `<h1>Let's go</h1>` to JSX block
4. Try to format code
5. Nothing will happen, and from now on, code formatting does not work anywhere until restart of vscode

**Comment by ramya-rao-a** [comment]
Duplicate of #11698

**Comment by waderyan** [comment]
@tomaash thank you for opening this issue. 

Copied to https://github.com/Microsoft/TypeScript/issues/10817#issuecomment-246728771
