### ISSUE TITLE
Use editor.fontFamily value for editor.codeLensFontFamily and editor.inlineHints.fontFamily

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#119406]
Vs code there are the following options to customize the font:
editor.codeLensFontFamily
editor.inlineHints.fontFamily

The problem is that the above options don't use the default editor.fontFamily option, which in turn is annoying. I would like for these parameters to have the same behavior as for debug.console.fontFamily, scm.inputFontFamily, terminal.integrated.fontFamily. If no font is specified, then we use the editor.fontFamily value.

I think you need to bring everything to one form.

**Comment by dbaeumer** [comment]
Not sure who owns this @alexdima @jrieken

**Comment by jrieken** [comment]
fyi - the default font for code lens is _not_ the editor font anymore. the change has been reverted, more details here: https://github.com/microsoft/vscode/issues/133912
