### ISSUE TITLE
Offer to rename -- A file or folder with the name already exists in the destination folder. Do you want to replace it?

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#119513]
Currently moving a file into a folder that has a file by the same name only offers replacing or canceling:
![VSCode Version: 1.54.3](https://user-images.githubusercontent.com/2119212/112051644-93d38e00-8b28-11eb-880f-d00b49ac361d.png)
> A file or folder with the name 'auditlog.go' already exists in the destination folder. Do you want to replace it?
> This action is irreversible!

It'd be nice if there were a third option to rename the file:
![Finder macOS Catalina 10.15.7](https://user-images.githubusercontent.com/2119212/112052149-2bd17780-8b29-11eb-9452-ea80543230e2.png)
> An older item named “auditlog.go” already exists in this location. Do you want to replace it with the newer one you’re moving?

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog and we might add this in the future. Thanks
