### ISSUE TITLE
Test test provider async apis

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119546]
Refs: https://github.com/microsoft/vscode/issues/115089 (last comment is the design)

- [x] anyOS @weinand
- [x] anyOS @eamodio

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119546%0A%0A)

---

This iteration involved a major refactor of testing APIs to support asynchronous loading.

- Play with the new API for the TestProvider and TestItem. Note any comments, concerns, or problems.
- Read the docs and make sure things make sense.

There are two existing test provider implementations you can use as a basis:

- The selfhost test provider https://github.com/microsoft/vscode-selfhost-test-provider
- The test provider sample https://github.com/microsoft/vscode-extension-samples/tree/master/test-provider-sample

**Comment by weinand** [comment]
I'm seeing this problem with the https://github.com/microsoft/vscode-extension-samples/tree/master/test-provider-sample:

<img width="1281" alt="2021-03-24_12-25-00" src="https://user-images.githubusercontent.com/1898161/112303149-424c1000-8c9c-11eb-8631-26b32daddc75.png">

**Comment by connor4312** [comment]
Thanks for the ping, I fixed the compilation error but was unable to reproduce the issue with tests not showing up on my windows or osx machine.

![](https://memes.peet.io/img/21-03-70092b13-a1ef-4a33-8e1f-e61d6aa8aed5.png)

Can you confirm that you were on the latest Insiders?

**Comment by weinand** [comment]
yes, I'm on and running the sample out of source:

Version: 1.55.0-insider
Commit: 8437d38d364ba93b53c1e659c20b1c86f710ec28
Date: 2021-03-24T08:10:36.007Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

The tests show up in the editor gutter but not in the test explorer.
If a switch between editors, I'm losing the test icons:

![2021-03-24_17-56-26 (1)](https://user-images.githubusercontent.com/1898161/112351713-69213b00-8cca-11eb-8bef-802f2dfd5bc2.gif)

**Comment by weinand** [comment]
Ok, I see: I was looking at the "Sample test explorer" and not at the test explorer in the "Test" viewlet.

**Comment by connor4312** [comment]
Ah, right, I'll remove that

**Comment by connor4312** [comment]
@eamodio, if you haven't started yet: I just pushed a change to the sample which will require an Insiders update as a result of changed APIs. Use the commit prior to https://github.com/microsoft/vscode-extension-samples/commit/7b920cdf15b29b0c272f65831ddc521d85335f2f if you test this today.

**Comment by eamodio** [comment]
@connor4312 I can't get the selfhost sample to run -- there looks like some issue with missing uris and calling toString on them in core.

https://github.com/microsoft/vscode/blob/a0e0324a8daad1b7f5a9e2ed7f174ded9186a3aa/src/vs/workbench/contrib/testing/browser/explorerProjections/locationStore.ts#L67
