### ISSUE TITLE
All problems disappear when closing file

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119585]
Testing #119471

Well basically the exact steps of #119471 on Windows:

* execute `Run Build Task`
* open `codeEditorWidget.ts`
* type `const x = 1+aa;`
* close the file, no problems appear:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/112148308-00f52b00-8bde-11eb-8d28-63a0e2276583.gif)

**Comment by alexr00** [comment]
Two things are happening here:
- https://github.com/microsoft/vscode/issues/119631 can be worked around with `"terminal.integrated.localEchoLatencyThreshold": -1`
- The Build Extensions task is causing errors to clear 🤦‍♀️

**Comment by TylerLeonhardt** [comment]
It's interesting, I noticed that upon closing, the problems go away for a second, but then they come back:

![image](https://user-images.githubusercontent.com/2644648/112531152-7985f400-8d64-11eb-94ed-2be607754556.png)

@alexr00 Is that ok?

**Comment by alexr00** [comment]
@TylerLeonhardt yep, that is ok (and expected).
