### ISSUE TITLE
[Getting Started] Task action for installing extensions

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#119502]
Getting started can help to set users up with the right extensions early on, making them more contextual and reducing prompts.

As the current command-driven actions don't work for installing extensions, having an action for installing specific extension that also triggers the _done_ state would solve this.

**Comment by digitarald** [comment]
This was also brought up from @jureid for the C++ walkthrough, recommending CMake/Makefile for when those configurations are detected. A good point was that this action should check if the extension is installed, so it doesn't show for users who already got the extension. cc @JacksonKearl

**Comment by JacksonKearl** [comment]
cc @sandy081 is there any command currently for installing extensions? Would you be opposed to adding something like that? I ask because we could either implement this via adding an `installExtension(id)` command and using the existing `[Install Foo](command:installExtension?foo)` style contributions, or add some new syntax like `[Install Foo](installExtension:foo)`

**Comment by sandy081** [comment]
Yes there is a command to install an extension passing extension id - `workbench.extensions.installExtension`. But this will ask for user consent to sync or not if settings sync is enabled.

**Comment by JacksonKearl** [comment]
Neat thanks! Asking user for sync consent is fine. Cc @digitarald would this work for the C/C++ folks?

**Comment by digitarald** [comment]
As the action on the button, yes 👍. To avoid confusion VS Code needs to support some `doneOn` clause that checks the step off when the extension is already installed.

**Comment by JacksonKearl** [comment]
Tracking improving `doneOn` in #122570.

The act of installing is possible today with `[Install The Thing](command:workbench.extensions.installExtension?%22extension.id%22)`.

**Comment by sbatten** [comment]
I'm not sure what the scope of verification includes for this. Yes, you can create a button that installs an extension, but it happens silently behind the scenes and feels like nothing happened. Maybe when the task automatically checks off the task it will feel better, but even then, there is no progress shown so larger extensions will feel broken for a few seconds.

I think having a way to show progress, either through progress notifications or directly in the step widget would improve this.

**Comment by JacksonKearl** [comment]
@sandy081 would you consider it in-scope for the `workbench.extensions.installExtension` to show a progress notification? Otherwise I can create my own command for getting started that calls out to that one but shows progress as well.

**Comment by digitarald** [comment]
> happens silently behind the scenes and feels like nothing happened

I see the same issue for extension recommendation installations in usertesting. Without the extension viewlet visible, the progress context is completely missing. A progress notifications seems useful, especially on slower connections.
