### ISSUE TITLE
Add an "official" or "highlight" label for extensions

### ISSUE THREAD

**Issue by DaCookie** [microsoft/vscode#119523]
I think the title is quite clear: it could be great to add an "official" label (or any other name, you get the point) for extensions in VSCode, meant to highlight official frameworks, languages or even packages extensions.

As an example, if you search extensions for C#, the first extension you should see in the list is the `C#` extension by Microsoft, which add some core features for the language like syntax highlighting. But there's a lot of other extensions named `C# something`, which are great, but "only" meant to add additional features, and created by users, not the language authors. I fiind it confusing, especially for new users.
And this is also real for many frameworks, languages, engines or packages: Unity, Node.js, Java, C++, Angular, React, ...

I don't know right now how it can be achieved (should authors be able to claim for the label or only VSCode team can set it, what exactly is considered official, ...), I'm just dropping the idea here for now :)

**Comment by sandy081** [comment]
Moved and tracked here - https://github.com/microsoft/vsmarketplace/issues/37
