### ISSUE TITLE
Error when creating a Fiori App

### ISSUE THREAD

**Issue by hmbontuyan** [microsoft/vscode#119551]
Create an app on Fiori: Open Application Generator and "Yeoman is not installed or available in your executable file" error is displayed.

![image](https://user-images.githubusercontent.com/81214067/112102856-db6b2000-8be3-11eb-8d3e-c64eabd7e93f.png)

**Comment by Tyriar** [comment]
This is caused by an extension, but it looks like it's telling you how to fix it.

**Comment by hmbontuyan** [comment]
I already tried reinstalling all the extension. I also uninstalled and reinstalled vscode. I can create fiori apps previously but now that error is still popping. I already clicked the extension on the popup but extension is already enabled and nothing works

**Comment by Tyriar** [comment]
VS code doesn't talk to Yeoman, it's an extension showing that notification. You can expand it to see the source extension creating that notification.
