### ISSUE TITLE
Implicitly invoke start when appending output etc

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119597]
My toy sample didn't call `start` on an execution task and I have received this error: ` Must call start before modifying cell output`. Given that a valid start invocation is parameterless, e.g needs no further information, we should implicitly set the started-bit when append output and friends are called

**Comment by roblourens** [comment]
It's weird that calling start would be optional? It has a side-effect in the UI so extensions should be encouraged to call it at the right time when the cell starts running.

**Comment by jrieken** [comment]
> It feels weird that calling start would be optional?

I'd say it's an convenience feature of the API

**Comment by roblourens** [comment]
Then they still have to remember to call end even though they forgot to call start. I think they should just make the call, then they'll make sure that pending actually means pending and executing means executing.

**Comment by jrieken** [comment]
Sorry, still disagree. Why make life harder for extension authors

**Comment by roblourens** [comment]
This would only be useful for kernels that can set outputs immediately without having to wait for some execution or request to complete, right? How many kernels can do something like that?

**Comment by jrieken** [comment]
Isn't the right question why set up hurdles for kernels that have immediate output?

**Comment by roblourens** [comment]
Because it seems more likely to lead to mistakes, like not calling start while code is running and leaving cells in the Pending state, or kernels assuming that if start is optional then end is too.

**Comment by roblourens** [comment]
I think the current behavior is stable and ok
