### ISSUE TITLE
Inline values provider isn't called when a variable is set

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#119564]
from https://github.com/microsoft/vscode/issues/105690#issuecomment-804710058

**Comment by isidorn** [comment]
So the gist of the issue is: Inline Values are not refreshed when a variable is set

**Comment by weinand** [comment]
yes, correct. 
I think we never did this.

**Comment by isidorn** [comment]
I know @testforstephen has tried this out and confirmed it is good now -> verified

**Comment by testforstephen** [comment]
yes, it's fixed in insider.
