### ISSUE TITLE
Accessing context.extensionn throws proposed API exception.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#119562]
Testing #119548

Not sure if it is expected. Was not mentioned in the test plan item.

**Comment by eamodio** [comment]
Was this with the latest build? I thought I removed that check.

**Comment by dbaeumer** [comment]
Build is:

Version: 1.55.0-insider (user setup)
Commit: 469e4f6e2755b220dae3eccb04d1ddc587b84a5a
Date: 2021-03-22T05:14:19.452Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by dbaeumer** [comment]
Works on latest.
