### ISSUE TITLE
Small but annoying regression - credentials dialog opens every few minutes on OS X

### ISSUE THREAD

**Issue by ddotlic** [Microsoft/vscode#11952]
- VSCode Version: 1.6.0-insider 2016-09-13T11:07:19
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open Visual Studio Code - Insiders
2. Suffer through incessant bugging 😢  of the dialog below (every few minutes)

<img width="416" alt="credential-helper" src="https://cloud.githubusercontent.com/assets/1737586/18474423/33b2b9c8-79c2-11e6-9111-b7885530e17c.png">

**Comment by joaomoreno** [comment]
Why don't you `Always Allow`?

You can disable automatic fetching with the `git.autofetch` setting, which is what's causing that pop-up.

But ultimately this is a problem with the `git-credential-osxkeychain` program, not Code.

**Comment by ddotlic** [comment]
@joaomoreno It might be (_not really_ 😉) a coincidence but the issue started **exactly** after I've updated Code to the version listed in the bug.

IOW, `git-credential-osxkeychain` must have been the same before and after the upgrade, no?

If the version of Code prior to the yesterday's one did not use `git.autofecth`, how do you explain change in behavior (I was not bugged before but am now)?

I'm not trying to argue to keep this a bug or not, just trying to understand. Thanks in advance for any info.

**Comment by joaomoreno** [comment]
It's a very good question. Nothing comes to mind, though, as very little changed in the git world recently. So it could very well be a coincidence that `git-credential-osxkeychain` changed at the same time... did you update `git` with Homebrew recently?

**Comment by ddotlic** [comment]
@joaomoreno I was just checking that and if I see correctly, I did not (I do use homebrew to keep git up to date). I have git 2.10.0 which has been out almost 2 weeks and I've updated it almost as soon as it became available (by accident, not that diligent 😉). On the other hand I update Code (well it updates itself) daily since I'm using insider, hence my suspicion that something in Code changed.
Anyway, like you said this is not Code issue, thanks for having patience with me 😄.

**Comment by joaomoreno** [comment]
Strange indeed. I'll keep an eye out for more people talking about this, maybe we can correlate it with something. Thanks!

**Comment by aried3r** [comment]
I am facing this issue again with

![screen shot 2017-05-05 at 14 04 36](https://cloud.githubusercontent.com/assets/1301152/25744826/20cb17f0-319c-11e7-820e-ce5bd0663bee.png)

I know I could "Always Allow", but the same as @ddotlic I don't think it's a coincidence since it happened only after updating VSCode.

git version 2.12.2 and I only recently updated git-lfs, but I don't think that's it.

**Comment by joaomoreno** [comment]
You get the prompt because VS Code tries to fetch from the remote every now and then. Please disable `git.autofetch` in the settings if you don't want this behaviour.
