### ISSUE TITLE
files.assocations setting seems to ignore `~` or other variables like ${env:HOME}

### ISSUE THREAD

**Issue by phaseOne** [microsoft/vscode#119522]
Issue Type: <b>Bug</b>

If this is "not a bug," could someone please point me to relevant source files if this is something we need to build support for?

1. Insert either of the following into your settings.json
    ```json
    "files.associations": {
      "~/.aws/config": "properties"
    }
    ```
    ```json
    "files.associations": {
      "${env:HOME}/.aws/config": "properties"
    }
    ```
2. Open your `~/.aws/config` and check that the file type is still "Plain Text"

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.99GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 31fa842c-194f-4fcc-806b-b36b936ebf52|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vscoresta800cf:30276762
vspre833:30267464
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by bpasero** [comment]
We currently neither support variables nor `~` for language associations as far as I can tell. The lookup happens here: `src/vs/base/common/mime.ts`
