### ISSUE TITLE
Test VS Code picks extensions when installed/uninstalled from CLI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#119518]
Refs: https://github.com/microsoft/vscode/issues/38607

- [ ] macOS @alexdima (Also test vscode server setup)
- [x] windows @Tyriar
- [x] linux @JacksonKearl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119518%0A%0A)

---

VS Code window now detects extensions installed by CLI. 

- Open VS Code window
- From terminal (inside or outside VS Code) install or uninstall extensions
- Test that installed extensions are enabled in VS Code
- If an extension is uninstalled test that extensions view reflects the state. 
- Try with different types of extensions like themes and language features.
- VS Code does not detect automatically if you copy/paste an extension manually into extensions folder. It needs window reload to load that.

**Comment by alexdima** [comment]
Very nice! :heart:
