### ISSUE TITLE
VSCode releases 1.53 and 1.54 hang on startup on Centos 7 VM

### ISSUE THREAD

**Issue by roybooth777** [microsoft/vscode#119584]
- VS Code Version: 1.53 and 1.54
- OS Version: Centos 7 - CentOS Linux release 7.8.2003 (Core)

Steps to Reproduce:

1. sudo yum update code
2. restart code
3. vscode hangs and has to be killed

Does this issue occur when all extensions are disabled?: Yes

**Comment by mahob** [comment]
I do have the same issue, same steps to reproduce.

My setup is:
- VS Code version: `1.54.3 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8 x64`
- OS version: CentOS Linux release 7.9.2009 (Core)
- Kernel version: `3.10.0-1160.21.1.el7.x86_64`
