### ISSUE TITLE
Fail to start debugging in extension test

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#119532]
- VS Code Version: 1.55.0-insiders
- OS Version: Win 10

Steps to Reproduce:

1. Create or install an extension with a debugger adapter (not sure if built in debugger adapter works though).
2. In the test for this extension, do something like:
    ```
    await vscode.debug.startDebugging(vscode.workspace.workspaceFolders![0], launchTargetName);
    ```
3. Test succeeds in the public version, but fails in the insider version.

Does this issue occur when all extensions are disabled?: N/A. An extension is required to repro this issue.

**Comment by weinand** [comment]
@xisui-MSFT in what way does "startDebugging" fail?

**Comment by xisui-MSFT** [comment]
Added more logs and tried again. Seems to be an issue caused by #119529. An extension isn't activated when that command is invoked.
