### ISSUE TITLE
Delayed extension activation in insiders

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#119529]
- VS Code Version: 1.55.0-insider
- OS Version: Win 10

Steps to Reproduce:
Actually not sure if this is intended, but looks like extension activation happens at a later time than the public version.
1. Create an extension + test, make the extension activate on `workspaceContains:foo.txt`, and make sure the test asset contains `foo.txt`.
2. Build and install the extension.
3. In the test suite, add
    ```
    suiteSetup(async () => {
        const extension: vscode.Extension<any> | undefined = vscode.extensions.getExtension('extension.name');
        assert(extension && extension.isActive);
    });
    ```
4. Run the test via command line (would NOT repro if tests are invoked in VS Code).
5. Assertion succeeds in the public version of VS Code, and fails in the insider version.

Does this issue occur when all extensions are disabled?: N/A, an extension is required.

**Comment by aeschli** [comment]
I used https://github.com/aeschli/ext-mar-2021a to verify

npm test works, but when run with F5, I get an error

![image](https://user-images.githubusercontent.com/6461412/112514324-7820ef80-8d95-11eb-988f-f7e1e724f28a.png)

As seen, the extension is activated, but the test fails on `extension.isActive`

**Comment by aeschli** [comment]
@alexdima Le me know if you want a new issue instead.

**Comment by alexdima** [comment]
I tried around 10 times on macOS and could not reproduce:
![image](https://user-images.githubusercontent.com/5047891/112535502-a958ea00-8dac-11eb-9318-48cb18bd0280.png)

I will also try on linux.

**Comment by alexdima** [comment]
I also tried Ubuntu and it works there:

![image](https://user-images.githubusercontent.com/5047891/112535783-f937b100-8dac-11eb-84e1-063c20bdf8d7.png)

**Comment by alexdima** [comment]
@aeschli Let's connect tomorrow

**Comment by aeschli** [comment]
So sorry @alexdima,  I was running with an older insiders. With the latest all works.
