### ISSUE TITLE
When expression input box should take 100% cell width

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#119573]
Testing #119503

Currently the when expression input box takes 90% of the cell width. I think taking the full cell width might be nicer. What do you think?

![Screenshot 2021-03-23 at 12 12 03](https://user-images.githubusercontent.com/1926584/112137813-05ffad80-8bd1-11eb-8ab1-8db8e4fae079.png)

**Comment by sandy081** [comment]
Followed the similar solution here - https://github.com/microsoft/vscode-remote-release/issues/4729
