### ISSUE TITLE
Big Sur 11.2.3 Can't open VS Code 2021

### ISSUE THREAD

**Issue by theranch** [microsoft/vscode#119516]
- VS Code Version: 1.54.1
- OS Version: MacOS Big Sur 11.2.3

Steps to Reproduce:

1. Download, unzip and moved VS Code to Applications.
2. Double clicked on VS Code and get the message "You do not have permission to open the application “Visual Studio Code”."
3. I open Security and Permissions pane in System prefs and VS Code bypass is not shown when selecting Allow from "App Store and identified developers"

This is frustrating because I was using Adobe Brackets for years and now that is going to be discontinued. It was suggested by Adobe to use VS Code. I'm eager to get up and running. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by deepak1556** [comment]
Please provide the output for the following commands

```
* codesign -vvvv <path-to>/Visual\ Studio\ Code.app/
* spctl --verbose --assess --type execute --v <path-to>/Visual\ Studio\ Code.app/
* xattr -lv <path-to>/Visual\ Studio\ Code.app/
```

**Comment by theranch** [comment]
First command:
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (GPU).app
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveObjC.framework/Versions/Current/.
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveObjC.framework/Versions/Current/.
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
/Applications/Visual Studio Code.app/: valid on disk
/Applications/Visual Studio Code.app/: satisfies its Designated Requirement

Second Command:
/Applications/Visual Studio Code.app/: accepted
source=Notarized Developer ID
origin=Developer ID Application: Microsoft Corporation (UBF8T346G9)

Third Command: Nothing returned

**Comment by deepak1556** [comment]
App is notarized, codesigned and there are no quarantine bits from the download, not sure why the app is prevented from opening. Is this a M1 device ?

Lets confirm the following as well,

```
* file /Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron
* ls -l /Applications/Visual\ Studio\ Code.app/
* open /Applications/Visual\ Studio\ Code.app/
```

**Comment by theranch** [comment]
Command one:
/Applications/Visual Studio Code.app/Contents/MacOS/Electron: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Applications/Visual Studio Code.app/Contents/MacOS/Electron (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Applications/Visual Studio Code.app/Contents/MacOS/Electron (for architecture arm64):	Mach-O 64-bit executable arm64

Command two:
total 0
drwxr-xr-x@ 9 gerry  staff  288 Mar 15 07:06 Contents

Command three:
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10826 "kLSNoLaunchPermissionErr: User doesn't have permission to launch the app (managed networks)" UserInfo={_LSFunction=_LSLaunchWithRunningboard, _LSLine=2508, NSUnderlyingError=0x7fe65a61cd90 {Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x7fe65a61d550 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Launchd job spawn failed with error: 1}}}}}

I am the admin and owner. I'm using a MacBook Pro (15-inch, 2018)

**Comment by deepak1556** [comment]
Permission looks good and executable type looks good. Can you check if the issue happens with x64 app https://code.visualstudio.com/docs/?dv=darwinx64

**Comment by theranch** [comment]
@deepak1556 I get the same error message when I try to launch..."You do not have permission to open the application “Visual Studio Code”."

**Comment by deepak1556** [comment]
What app are you using to uncompress the archive ?

**Comment by theranch** [comment]
@deepak1556 I'm using the Unarchiver.

**Comment by theranch** [comment]
Ahhh...that must have been the issue. I uncompressed using Archive Utility and was able to open Visual Studio Code.

**Comment by deepak1556** [comment]
Thanks for confirming, closing as issue is not with the app.
