### ISSUE TITLE
Color of block in terminal is not very visible when finding text

### ISSUE THREAD

**Issue by hyunsik-yoon** [microsoft/vscode#119570]
Hi.

While performing `find` in terminal to, e.g., analyze complex log with a lot of text, 
Code shows text found in gray block color. (see `3` in the figure below) When there are many text, it's hard to find gray blocked text. If VS Code provides feature to change the color of gray block to, e.g., yellow block, it will be awesome!

Thanks in advance!

![image](https://user-images.githubusercontent.com/63768207/112130541-ee91e600-8c0b-11eb-9d85-cf76f6df42c6.png)

**Comment by meganrogge** [comment]
There are extensions that let you customize this
