### ISSUE TITLE
"none" quoting in tasks.json

### ISSUE THREAD

**Issue by jerryc05** [microsoft/vscode#119567]
Related to #45576, #22589.

I have a command to execute in a string, which seems like the following format:
```
./program arg1 arg2 arg3
```

I cannot separate this string and pass each `arg` into `args` because the string is generated by a `${command:...}`. However, if I pass the string directly as `command` into `tasks.json` with any of `weak`, `strong`, or `escape` quoting, the string as a whole will be quoted and produces `failed to launch (exit code: 127)` error.

Is there a way to execute the string __AS-IS__? Or is there a workaround?

I got it working by using `sh` as command and `"-c", "${command:...}"` as args, but this is ugly and not cross-platform.

**Comment by alexr00** [comment]
There is no current way to do this, but it is a valid feature request.
