### ISSUE TITLE
Support text editing keybindings customization for quick open input

### ISSUE THREAD

**Issue by benmosher** [Microsoft/vscode#11950]
- VSCode Version: 1.5.2
- OS Version: maxOS 10.11.6 

Steps to Reproduce:
1. define a key binding, such as 

``` json
    { "key": "ctrl+w",               "command": "deleteWordLeft" },
```
1. open command palette 
2. type some text
3. attempt to use defined key binding on text entered into command palette

Looking at the docs, I can't find a `when` clause that would cause keybindings to apply there. I mostly want `ctrl+n`\+ `ctrl+p` for up/down + `ctrl+w` for delete-word.

All three work great in the editor, but are ignored in the command palette.

Thanks!

**Comment by ramya-rao-a** [comment]
The up/down in command pallete is tracked in #7876

**Comment by benmosher** [comment]
#7876 does fix some of the specific issue I mentioned, but wouldn't it be simpler to have edit-related keybindings behave the same way in the command palette as the editor panes?

I believe this is true for Sublime. Seems like a more general fix for all future "this works in Sublime/OSX/etc." keybinding issues. I have no idea how substantial of a code/product change that would be, though.

That is: I wouldn't suggest that _everyone_ have `ctrl-w` mapped to `deleteWordLeft`, I would just like the command palette to respect my personal keybindings (even if that means a different, explicit `when` predicate, such as

```json
 { 
  "key": "ctrl+w",
  "command": "deleteWordLeft",
  "when":  "editorTextFocus || commandPaletteFocus"
}
```

Thanks for your quick response. I know y'all can't do everything for everyone. Just thought I'd bring it up.

**Comment by bpasero** [comment]
Keybindings are currently not hooked up to the quick open widget.

**Comment by ichirika** [comment]
want too

**Comment by benmosher** [comment]
closing because 2019. cheers. 😁
