### ISSUE TITLE
Test: Smoke Test

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#119524]
- [x] Windows @meganrogge
- [x] macOS @egamma
- [x] Linux @roblourens 
- [ ] Windows @fiveisprime (Optional)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119524%0A%0A)

---

**NOTE:** Desktop & Web tests MUST run with `--build` argument

**NOTE:** Desktop tests MUST run with `--stable-build` argument additionally

Documentation: https://github.com/Microsoft/vscode/blob/main/test/smoke/README.md#run.

If the automated tests fail, create and issue for that and run the tests manually: https://github.com/microsoft/vscode/wiki/Smoke-Test

**Comment by roblourens** [comment]
When I run the smoketest, it keeps enabling accessibility mode, causing tests to fail. I don't have the setting for that enabled, and I don't have a screenreader running. Works when I force it to be disabled. Never seen that before but I'm sure it's something with my machine, not vscode...

**Comment by TylerLeonhardt** [comment]
Feel free to test whenever @fiveisprime
