### ISSUE TITLE
Typo when debugger times out

### ISSUE THREAD

**Issue by Pavlos-Efstathiou** [microsoft/vscode#119558]
Issue Type: Typo

- VS Code Version: 1.54.3
- OS Version: Windows 10 20H2 (Windows NT x64 10.0.19042)

Steps to Reproduce:
1. Install Python extension (If you don't you can't debug python code) 
2. Debug Python code 
3. Make debugger time out

Typo:
![Code_LlZNt8MJCu](https://user-images.githubusercontent.com/60986328/112114789-1f006280-8bc1-11eb-9287-1fcf30023972.png)

Does this issue occur when all extensions are disabled?: No

**Comment by weinand** [comment]
@Pavlos-Efstathiou I do not see a typo. What do you think is a typo?

**Comment by Pavlos-Efstathiou** [comment]
@weinand It says waiting for debugee to spawn

**Comment by Pavlos-Efstathiou** [comment]
@weinand Click the image to see it with a bigger resolution

**Comment by weinand** [comment]
Yes, that's correct and the "debuggee" is the  program to debug, not the "debugger".

**Comment by Pavlos-Efstathiou** [comment]
@weinand Sorry for wasting your time

**Comment by weinand** [comment]
np
