### ISSUE TITLE
Pasting Formatted Text into Terminal has Inconsistent Behavior

### ISSUE THREAD

**Issue by bramankp** [microsoft/vscode#119511]
![2021-03-22 (1)](https://user-images.githubusercontent.com/19915618/112048363-b4014e00-8b24-11eb-98da-eae2cc20d818.png)

Steps to Reproduce:

0. Copy formatted text from somewhere. In my case, from ADLM Jira ticket title. Not sure where else this might work to reproduce.
1. VSCode in Windows using Git for Windows (Git Bash).
2. Open Terminal and run "git commit" (which, in my case, opens GNU Nano as the editor in the terminal).
3. Paste text using either CTRL-SHIFT-V or right-click mouse.
4. Tilde is appended to text (new, hasn't done this before).
5. Same thing but now do this in Remote WSL.
6. Upon pasting text, editor complains about a weird sequence and locks up. (Again, this is new ... been doing this for ages.)

This seems like it's going to be really annoying to track down because of the weirdly inconsistent behavior. If I just to an "echo <paste>" it seems to work fine in the terminal.

Does this issue occur when all extensions are disabled?: Yes, but I can't reproduce without enabling Remote Development: WSL.

**Comment by meganrogge** [comment]
potentially related to #115396

**Comment by bramankp** [comment]
Well, the weird thing is that as mysteriously as it *started* being a problem now I am unable to reproduce it.

I'm suggesting we just drop this completely and I'll enter another issue with better steps to reproduce or something? (I don't want to leave open issues lying around no one can reproduce.)
