### ISSUE TITLE
Cancel cell execution task when cell is deleted

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119504]
- Create a cell execution task
- Delete that cell
- The task should probably be canceled

**Comment by DonJayamanne** [comment]
Today, I'm trying to handle this myself, by checking if the cell is still valid (`cell.document.isClosed`).

**Comment by roblourens** [comment]
Haven't really been able to decide whether we should do this or at what level it should be implemented.

When do you do that check?

**Comment by DonJayamanne** [comment]
> When do you do that check?

When ever we deal with cells/output/updates. 

Basically the cell could be missing at any point of the execution, hence we try to ensure we don't end up in a situation when things could bomb out because the cell is now missing.

**Comment by roblourens** [comment]
This is basically part of https://github.com/microsoft/vscode/issues/125668
