### ISSUE TITLE
Automatically show inline values if an inline values provider is registered

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#119560]
If a user does not have an explicit "debug.inlineValues" setting, we should automatically enable inline values if an inline values provider is registered.

see https://github.com/microsoft/vscode/issues/105690#issuecomment-804710058

**Comment by isidorn** [comment]
Yes this makes sense, for this we can change the `debug.inlineValue` to be `true` | 'false' and add a new default value 'auto'.

'auto' would mean it is off unless there is a value provider registered.
That way we will still give the option for the user to turn it off even if a provider is registered.

**Comment by testforstephen** [comment]
I like the idea of adding a new default value `auto`.

**Comment by isidorn** [comment]
I just pushed this change as we agreed upon, `debug.inlineValue` can now be `true | false | "auto"`. `"auto"` is the default

@testforstephen would be great if you can verify this with vscode insiders starting from Friday (once we release a new Insiders build). Thanks!

**Comment by testforstephen** [comment]
Tried 04-02 insider version, it works well. Thanks.

The new `auto` will enable the inline values by default if Java debugger uses the API to provide inline values.
And `true` and `false` will also turn on/off the inline values.

**Comment by isidorn** [comment]
@testforstephen great, thanks for trying, adding verified label.
