### ISSUE TITLE
Drag&drop of code cell uses default font 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119581]
Testing #119367

* (see attached screen capture)
* have a custom code font  (FiraCode for me)
* have a code cell
* drag the cell
* the drag preview uses a different font face

<img width="698" alt="Screenshot 2021-03-23 at 12 37 37" src="https://user-images.githubusercontent.com/1794099/112140731-aefbd780-8bd4-11eb-963c-eb17d55b4c22.png">

**Comment by roblourens** [comment]
Can't repro on mac or linux with different fonts. Does it happen all the time? If so maybe I can debug on your machine.

**Comment by jrieken** [comment]
Yeah, happens all the time. Maybe worth noting is that I am using `"webview.experimental.useIframes": true,`

**Comment by roblourens** [comment]
That shouldn't make a difference. Do you see this @rebornix?
