### ISSUE TITLE
Extension returning completion items with text edits being discarded

### ISSUE THREAD

**Issue by kitsonk** [microsoft/vscode#119553]
- VS Code Version: 1.54.3
- OS Version: OSX 20.3.0

When trying to send completion items with a `textEdit` to vscode, vscode appears to be rejecting ranges where the start is less than the position, which seems illogical.

For example in the following document:

```ts
import * as b from "./"
```

When responding to a `textDocument/completion` request of:

```json
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "textDocument/completion",
  "params": {
    "textDocument": {
      "uri": "file:///a/file.ts"
    },
    "position": {
      "line": 0,
      "character": 22
    },
    "context": {
      "triggerKind": 2,
      "triggerCharacter": "/"
    }
  }
}
```

With:

```json
{
  "isIncomplete": false,
  "items": [
    {
      "label": "example",
      "kind": 19,
      "sortText": "1",
      "textEdit": {
        "range": {
          "start": {
            "line": 0,
            "character": 20
          },
          "end": {
            "line": 0,
            "character": 22
          }
        },
        "newText": "./example"
      }
    }
  ]
}
```

VSCode will ignore the completion item, but if the following is sent:

```json
{
  "isIncomplete": false,
  "items": [
    {
      "label": "example",
      "kind": 19,
      "sortText": "1",
      "textEdit": {
        "range": {
          "start": {
            "line": 0,
            "character": 22
          },
          "end": {
            "line": 0,
            "character": 22
          }
        },
        "newText": "example"
      }
    }
  ]
}
```

The completion will be shown.  The only problem is that I want to replace the whole specifier with the `"newText"` to ensure the value is always _correct_.

Further experimentation has led to discover that `"end"` can be past the requested position, but `"start"` must be equal to the requested position.

The [language server protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion) indicates that:

> *Note:* The range of the edit must be a single line range and it must
> contain the position at which completion has been requested.

But it does not indicate the `"start"` of the range must be equal to the position.

I have been unable to find any logging of why the completions are being discarded by vscode, it has only been through sending various values that I narrowed it down, so it is still a guess on my part.

Does this issue occur when all extensions are disabled?: N/A

**Comment by jrieken** [comment]
> But it does not indicate the "start" of the range must be equal to the position.

That is not true. This is usually an indication that the "selected" text doesn't match the filter criteria: 

A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.

**Comment by jrieken** [comment]
Please review your code after reading the sample/explainer above. Also, use vscode-API, not LSP, for your samples. Thanks

**Comment by kitsonk** [comment]
@jrieken thank you for the explainer, it was the lack of a `filterText`.  The interaction with the range of the `textEdit` and how VScode processes stuff is very opaque.

> Also, use vscode-API, not LSP, for your samples.

That is hard to do when you are writing a LSP server. 🤷
