### ISSUE TITLE
"Discard Changes" button on an untracked file does not remove file

### ISSUE THREAD

**Issue by zbs** [microsoft/vscode#119542]
- VS Code: 1.54.3
- OS and version: Windows 10 Enterprise 20H2, using Remote SSH onto an RHEL 7 Host
- Python version (& distribution if applicable, e.g. Anaconda): Python 2.7 on Miniconda 3

Steps to Reproduce:
1. Create a new file in a git repo
2. Click "Discard Changes" next to that file in the Source Control sidebar

**Expected Result:**
File is deleted 

**Actual Result:**
File is not deleted. Looking in the Git output logs, it ran this:
```
git clean -q -f filename
```
That doesn't even work from my command-line. I think it needs to run `rm -rf filename`.

**Comment by eamodio** [comment]
What version of Git are you using? That command works for me.

**Comment by zbs** [comment]
Version 2.25.0. I noticed this only repros if the file I'm deleting is in an untracked directory.

```
cd repo_root
mkdir new_dir
touch new_dir/test_fiel
```
then attempt to revert that file via the Discard Changes button.

**Comment by zbs** [comment]
Anything I can provide to help out?
