### ISSUE TITLE
Update shells immediately if profile config is changed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119505]
Repro:

1. Create a new profile in settings.json
2. Open dropdown, it's out of date for up to 10 seconds.

**Comment by meganrogge** [comment]
fixed with 
https://github.com/microsoft/vscode/blob/f934e058c7546d97ab0a380370f37aaffaa47fda/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L340-L340
