### ISSUE TITLE
I CANNOT HIGHLIGHT TEXT ANYMORE

### ISSUE THREAD

**Issue by gbenj** [microsoft/vscode#119583]
Issue Type: <b>Bug</b>

I cannot highlight any text in my workspace, regardless of the file format. 
The press aned hold the left mouse button to highlight text isnt working, but the keyboard "shift and arrow keys is"
I tried uninstalling the extensions and even the app itself and reinstalling them but the problem  still persists.
I will greatly Appreciate your help

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:56:11.670Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz (2 x 2261)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.93GB (0.57GB free)|
|Process Argv|C:\\Users\\DADZIE\\Desktop\\ben\\learning_open_close_botton --crash-reporter-id 5a434358-bde8-4632-9408-be2b6cb7a9c6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
save-typing|akh|0.1.0
save-as-snippet|art|0.0.1
bracket-pair-colorizer-2|Coe|0.2.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|5.9.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
reload|nat|0.0.6
vscode-css-peek|pra|4.1.0
LiveServer|rit|5.6.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30277002
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by alexdima** [comment]
@gbenj Does this reproduce in any file, like a simple `.txt` file? Does this reproduce when disabling all extensions? (`F1 > Developer: Reload with Extensions Disabled`)

**Comment by gbenj** [comment]
No, it doesn't..
I can select text perfectly fine in other text editors.
Its only in VS code that this happens..

**Comment by gbenj** [comment]
Yes.. It also occurs when i disable all entension.

**Comment by alexdima** [comment]
@gbenj Can you please try the following:
- close all instances of VS Code
- create a new folder e.g. `C:\newfolder`
- launch `code --user-data-dir=C:\newfolder`

Does selecting with the mouse work with this fresh environment?

**Comment by gbenj** [comment]
Hey!
Where should i run the code from? I do not know where i should.
I tried cmd but it still isnt selecting text.
it doesnt work.
It works with other text - editors, window screen and browsers. Only in vs
code.
I have removed all extensions and the problem still persists..

**Comment by alexdima** [comment]
@gbenj Does selecting text work in the editor at https://vscode-web-test-playground.azurewebsites.net/ when you open that in Chrome or latest Edge ?

**Comment by gbenj** [comment]
whoaaa... Strangely, it doesn't work there either.  I cannot highlight text
there too.

**Comment by alexdima** [comment]
@gbenj Given selection works using shift + arrow keys, but not when using the mouse, this might indicate that the mouse is giving unexpected UI events. Do you perhaps press another mouse button while dragging (intentionally or otherwise)? For example, starting dragging and pressing the middle mouse button will effectively cancel the mouse operation. Do you perhaps have another physical mouse that you could try and check if it still reproduces?
