### ISSUE TITLE
Multi-select on markdown notebook cells breaks selection

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119515]
The new markdown cell renderer seems to break multi-select. Here I start selecting via holding the `Shift` key and only when I select a markdown cell, my selection is cleared. This goes away when i disable the new markdown renderer. 

![Kapture 2021-03-22 at 13 15 42](https://user-images.githubusercontent.com/35271042/112053343-79da8100-8b11-11eb-8e7c-c9f0dc67ffdb.gif)

**Comment by mjbvz** [comment]
We likely need to update this code:

https://github.com/microsoft/vscode/blob/2cde743fe2159a14dcd0c30bcef419c5d115f746/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L891

Currently it always focuses the cell, but if shift or mata is held down, we should instead add the cell to the selection. I made sure the event data is passed back to the renderer, but wasn't sure how to actually update the selection in a notebook programatically. Let's take a look for April

**Comment by rzhao271** [comment]
I'm still seeing some strange behaviour while shift+clicking on cells.
I wonder if there's a difference between how the markdown cells and the code cells are being handles right now that results in the following:

![recording (2)](https://user-images.githubusercontent.com/7199958/116464853-4e8a3680-a821-11eb-83fc-f9be82907621.gif)

**Comment by mjbvz** [comment]
Shift is fixed by 40a268505754cc0ff4b7a9e514ccce57b2dc433e
