### ISSUE TITLE
Empty markdown cell isn't rendered nice

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119576]
Testing #119367

* create a new markdown cell
* enter no text and go to preview mode
* the cell looks funny, we should render a placeholder like "empty cell"

<img width="703" alt="Screenshot 2021-03-23 at 12 24 08" src="https://user-images.githubusercontent.com/1794099/112139143-b621e600-8bd2-11eb-8404-feba4b9ef01a.png">

**Comment by mjbvz** [comment]
Fixed by de4b1cf9dca19b3ebd663ae492ade42a0a6c72a0
