### ISSUE TITLE
Displeasing gap between selected cells

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119594]
Testing #119118

When selecting multiple cells, there is an esthetically displeasing "gap" between adjacent selected cells:

This makes it difficult to immediately say if the selection is contiguous or there is an item not selected:

![image](https://user-images.githubusercontent.com/5047891/112152843-01dc8b80-8be3-11eb-878c-aa9e8ec6036b.png)

**Comment by rebornix** [comment]
Starting from @misolori

**Comment by misolori** [comment]
Yea this is because of the spacing between the cells and the bottom "add new cell" toolbar. Will see what we can do ti improve this. cc @jilljac

**Comment by rebornix** [comment]
This issue should be gone now

![Image](https://github.com/user-attachments/assets/2e35529f-06c1-42c6-9da8-a918ea24cfd6)
