### ISSUE TITLE
[macOS Big Sur] Cannot connect to Extensions Marketplace, ERR_CERT_INVALID

### ISSUE THREAD

**Issue by microdee** [microsoft/vscode#119540]
- VS Code Version: 1.54.3
  * Version: 1.54.3
  * Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
  * Date: 2021-03-15T11:00:52.911Z
  * Electron: 11.3.0
  * Chrome: 87.0.4280.141
  * Node.js: 12.18.3
  * V8: 8.7.220.31-electron.0
  * OS: Darwin arm64 20.3.0
- OS Version: macOS Big Sur 11.2.3

**Issue:**

Cannot install or list extensions, extensions sidebar says "We cannot connect to the Extension Marketplace at this time, please try again later". When network error is checked in devtools, it complains about certificate being invalid.

Steps to Reproduce:

1. Go to extensions sidebar
2. It displays "We cannot connect to the Extension Marketplace at this time, please try again later" instead of the list of Popular extensions.
3. F1 -> `Developer: Toggle Developer Tools`
4. Refresh the Extensions Sidebar which should result in this:
![Capture](https://user-images.githubusercontent.com/1009962/112075667-374c8f00-8b79-11eb-92b3-871e319af76a.PNG)
![Capture1](https://user-images.githubusercontent.com/1009962/112075890-a9bd6f00-8b79-11eb-96f1-d7e82bd05726.PNG)

VSCode on Windows has no problem loading extensions at the same time.

Does this issue occur when all extensions are disabled?: Yes, I cannot install any :P

**Comment by sandy081** [comment]
I see `ERR_CERT_INVALID` error - you seem to have proxy set up, please check your proxy settings and retry

@chrmarti FYI

**Comment by chrmarti** [comment]
@microdee Can you access https://marketplace.visualstudio.com using Chrome/Chromium?

**Comment by microdee** [comment]
yeah it appears that I cannot access that URL from chromium either. but I don't understand, this is a brand new machine I've never touched or even looked at proxy settings. I'll see what I can do in that regard

**Comment by microdee** [comment]
![Capture2](https://user-images.githubusercontent.com/1009962/112315040-fe600780-8ca9-11eb-9eb2-ee3b35e3d494.PNG)

yeah I cannot see anything enabled in the proxy settings

**Comment by chrmarti** [comment]
When you click on the icon to the left of the URL in the location bar in Chromium, you can get additional details on the certificate. What does that show?

**Comment by microdee** [comment]
I hope this includes info which helps. This is chromium:
![image](https://user-images.githubusercontent.com/1009962/112498964-4f91f900-8d87-11eb-8150-c8f390692fdb.png)
<details><summary>DNS names</summary>
<p>

DNS names continued:
![image](https://user-images.githubusercontent.com/1009962/112499277-9c75cf80-8d87-11eb-82a4-6c3039b18fe5.png)
More DNS names:
![image](https://user-images.githubusercontent.com/1009962/112499373-b1eaf980-8d87-11eb-90da-686bf3256f8d.png)

</p>
</details>

End of certificate:
![image](https://user-images.githubusercontent.com/1009962/112499465-c929e700-8d87-11eb-98ec-4a3103f0f342.png)

**Comment by microdee** [comment]
Oh yeah! one detail which I forgot to mention. I have an annoying situation where I'm forced to use the **root** user against my better judgement. Maybe that can mess up chromium certificate checks, which would be very disappointing. And it actually does, in fact I cannot load any https website on root in chromium. bummer.

**Comment by chrmarti** [comment]
This looks like a Chromium bug, it says the certificate is "valid", but it still doesn't trust it.

I don't have the trust section when I look at this in Chrome on Mac (Catalina), what do these options do?
![image](https://user-images.githubusercontent.com/9205389/112536991-70217980-8dae-11eb-9d78-5e949a3e673e.png)

**Comment by microdee** [comment]
well I can set them as "Always Trust" and then nothing changes. I agree this seems to be a deeper problem of chromium on the root user. However I can also see why Google would decide to just not trust anything on the root user of MacOS. I can try installing extensions on root from VSIX files maybe.

**Comment by chrmarti** [comment]
Ok, closing as upstream since we don't plan to follow up with Chromium in this case. Thanks.
