### ISSUE TITLE
an argument of "--" causes formatting issues

### ISSUE THREAD

**Issue by ryuanchen** [microsoft/vscode#119547]
Issue Type: <b>Bug</b>

 regexp -inline -all -- {\S+} $string
The "--" in the above expression causes all lines below to become mostly orange, as if they were in quotes. If I comment the above line or change the "--" to something else, the formatting looks okay. Please fix!

VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.19041

**Comment by ryuanchen** [comment]
Hi, thanks for the quick response. Here is more info. The language is Tcl. I am using an extension to highlight the Tcl. Looks like the issue is most likely with that extension and not with the base VS Code. Here is my code for completeness but likely this is probably the wrong place to report the bug.

# Tcl testcase for issue in VS Code:
# Version: 1.54.3 (system setup)
# Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
# Date: 2021-03-15T10:55:45.459Z
# Electron: 11.3.0
# Chrome: 87.0.4280.141
# Node.js: 12.18.3
# V8: 8.7.220.31-electron.0
# OS: Windows_NT x64 10.0.19041
regexp -- {-[a-z]+} "some string"

puts "this syntax highlighting following the previous regexp is not working properly"
set foo bar
puts "highlighting is still showing orange"
# comments are still orange instead of green
puts "comment out regexp line above to see highlighting fixed"

**Comment by alexr00** [comment]
@ryuanchen thanks for the additional info. As you say, since VS Code doesn't have any built in support for Tcl, this issue is coming from the extension that provides this support.
