### ISSUE TITLE
Command "Add Cursors to Bottom" doesn't cause screen reader to narrate cursor information

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119580]
Testing #119082

1. Turn on screen reader.
2. Place your cursor 10ish lines from the bottom of a file.
3. Run the command "Add Cursors to Bottome"
4. Expected: All the new cursors are announced. Actual: None of the new cursors are announced.

**Comment by isidorn** [comment]
Great catch! I missed those two commands. Thanks for letting me know.
