### ISSUE TITLE
Selfhost test provider w/ async APIs

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119545]
Refs: https://github.com/microsoft/vscode/issues/115089 (last comment is the design)

- [x] anyOS @jrieken
- [x] anyOS @Tyriar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119545%0A%0A)

---

This iteration involved a major refactor of testing APIs to support asynchronous loading.

- Install the [selfhost test provider](https://github.com/microsoft/vscode-selfhost-test-provider) extension 
- Try out test functionality in the UI (decorations and explorer)
- Try out the different commands -- run all, run all in file, re-run failed and re-run test commands. Try refreshing in between these to force re-discovery as well.

There are two known quirks you don't need to create issues about:
- There is a test decoration shown on the first line of all test files. This'll be fixed with a minor upcoming API change.
- The selfhost provider publishes tests using their full file path. This is rather ugly, not sure if/what solution I will use to fix this.

**Comment by Tyriar** [comment]
> The selfhost provider publishes tests using their full file path. This is rather ugly, not sure if/what solution I will use to fix this.

Perhaps the common parts of the path should be removed, leaving enough to identify them uniquely, similar to how tab disambiguation works:

![image](https://user-images.githubusercontent.com/2193314/112180588-ebb9d580-8bb8-11eb-9d16-5964e22257d5.png)

For VS Code this would let us remove `src/vs` I think

**Comment by jrieken** [comment]
> The selfhost provider publishes tests using their full file path. This is rather ugly, not sure if/what solution I will use to fix this.

Another alternative is the "<basename> <dirname>". That's what SCM, search, and references view does

<img width="341" alt="Screenshot 2021-03-24 at 08 41 28" src="https://user-images.githubusercontent.com/1794099/112272616-bc6c9c80-8c7c-11eb-8699-c81b5edfba93.png">
