### ISSUE TITLE
Inconsistency in the execution API and Kernel Provider

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119544]
- VS Code Version: Insiders
- OS Version:N/A

Today the cell execution task is as follows:
`export function createNotebookCellExecutionTask(uri: Uri, index: number, kernelId: string): NotebookCellExecutionTask | undefined;`

Note how the `kernelId` is mandatory in the above API call.
However in `NotebookKernel` the `id` property is optional.
This automatically means the KernelId is no longer optional. Unless someone creates kernel and doesn't even use the execution cell task, seems unlikely.

@jrieken @roblourens /cc

**Comment by roblourens** [comment]
Hm, when does a kernel need/not need an id?

`kernelId` on that task method is currently ignored so you can ignore it if this is an issue for you right now. But the idea is that only the active kernel can create an execution task.

**Comment by jrieken** [comment]
Let's revisit this when revisiting how kernels come into the system. If kernels become managed objects (push model) than the create-function could be a member of that type

**Comment by jrieken** [comment]
Closing as we have now the notebook controller API which comes with its factory function for execution tasks
