### ISSUE TITLE
'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#11953]
Running with Chrome 52 I see this in the console. 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M54, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

Seems to be used in `nativeKeymap.ts`

**Comment by bpasero** [comment]
Looks like it will be removed in M54, not 53

**Comment by alexandrudima** [comment]
@bpasero Please let me know when/if this blocks updating.

**Comment by bpasero** [comment]
@alexandrudima it blocks us as soon as we update to a newer electron version. latest electron bundles Chrome 56.

**Comment by bpasero** [comment]
@alexandrudima fyi I created a build with Electron 1.6.2 for Windows here: https://az764295.vo.msecnd.net/insider/d42d4467e681308a5f82b61cb11ee6b91f1b9864/VSCode-win32-1.11.0-insider.zip
