### ISSUE TITLE
Bad syntax highlighting when using template strings in TypeScript

### ISSUE THREAD

**Issue by lukaseder** [Microsoft/vscode#11951]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

The following code 

```typescript
// (ironically, GitHub has the same issue as can be seen below)
let a = `a b ${(new Date).getFullYear()} c`
let b = 0;
```

... breaks syntax highlighting for TypeScript:

![image](https://cloud.githubusercontent.com/assets/734593/18473540/d704742c-79bd-11e6-86ac-a978791e2576.png)

The problem appears as soon as the function call to `getFullYear()` has parentheses. Removing the parentheses partially "fixes" the problem:

![image](https://cloud.githubusercontent.com/assets/734593/18473571/f0aca188-79bd-11e6-9977-24b1ce11e789.png)

**Comment by waderyan** [comment]
I believe this will be fixed with the latest grammar update. @aeschli can you speak to this?

**Comment by vilic** [comment]
The TmLanguage file of TypeScript just does not work well, and the repository (TypeScript-TmLanguage) is lack of maintenance. Please let us know you are going to move to a better way of syntax highlighting like something based on language server.

**Comment by waderyan** [comment]
@vilic a new grammar is being released soon (like very soon, could be today). Please stand by.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#269
