### ISSUE TITLE
update with less prompts

### ISSUE THREAD

**Issue by RedDragonWebDesign** [microsoft/vscode#119549]
Consider adding an option to Settings -> Update -> Mode called "automatic", that simply installs updates automatically, without prompting the user.

It shouldn't be the default, but it would be good to have as an option.

This would get rid of 2 bottom right of screen message boxes: one to ask if you want to download the update, and one that reminds you that you need to restart to finish installing the update.

Instead, when set to automatic, VS Code should quietly check for and background download the update when VS Code opens. Then the next time VS Code completely closes and re-opens, it can automatically do the install.

**Comment by joaomoreno** [comment]
The default update mode requires no user interaction: the update will be automatically installed just by quitting VS Code.
