### ISSUE TITLE
Keyboard shortcuts with `ctrl+alt+arrow` don't work over Remote Desktop

### ISSUE THREAD

**Issue by psclkhoury** [microsoft/vscode#119571]
I connect on a remote machine where I run vscode, but keyboard shortcuts with `ctrl+alt+arrow` don't work over Remote Desktop.

e.g.
```json
{
    "key": "ctrl+alt+left",
    "command": "cursorWordPartLeft"
},
```

Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
Most likely these keybinding are intercepted by Remote Desktop.
See steps https://github.com/microsoft/vscode/wiki/Keybinding-Issues to confirm whether VS Code receives this combination.

See https://superuser.com/questions/327866/remote-desktop-sending-ctrl-alt-left-arrow-ctrl-alt-right-arrow-to-the-remote-p for possible solutions.

**Comment by psclkhoury** [comment]
Vscode does not receive the whole combination.
