### ISSUE TITLE
examples/markdownExamples fields for boolean and enum settings UI

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#119530]
This is a request to add 'examples' fields for values of boolean and enum extension settings.  This would allow an example/preview to be visible in the settings UI, illustrating the current effect of the setting.

In the C/C++ Extension, we have some boolean and enum settings for code formatting.  We would like to provide code example for each potential value, to display its effect.  This is based on similar behavior in VS.

In VS:
![image](https://user-images.githubusercontent.com/49173979/112063150-31759000-8b1e-11eb-9c3c-b1d633a27e5f.png)

![image](https://user-images.githubusercontent.com/49173979/112063185-3afef800-8b1e-11eb-9c7f-993b3acdb5dc.png)

We had planned to create our own UI for editing these settings, using a webView.  ( https://github.com/microsoft/vscode-cpptools/issues/5953 )  Though, doing so would introduce a second UI for editing these same settings, which could be confusing for users.

The fields I'm suggesting might look something like:

```
        "C_Cpp.vcFormat.space.beforeComma": {
          "type": "boolean",
          "default": false,
          "description": "%c_cpp.configuration.vcFormat.space.beforeComma.description%",
          "scope": "resource"
          "markdownExamples": [
            "```cpp\nvoid Function1(int a, int b)\n{\n    Function2(a, b);\n}\n```",
            "```cpp\nvoid Function1(int a , int b)\n{\n    Function2(a , b);\n}\n```",
          ]
        },
        "C_Cpp.vcFormat.indent.multiLineRelativeTo": {
          "type": "string",
          "enum": [
            "outermostParenthesis",
            "innermostParenthesis",
            "statementBegin"
          ],
          "enumDescriptions": [
            "%c_cpp.configuration.vcFormat.indent.multiLineRelativeTo.outermostParenthesis.description%",
            "%c_cpp.configuration.vcFormat.indent.multiLineRelativeTo.innermostParenthesis.description%",
            "%c_cpp.configuration.vcFormat.indent.multiLineRelativeTo.statementBegin.description%"
          ],
          "markdownExamples": [
            "```cpp\n<outermostParenthesis code example>\n```",
            "```cpp\n<innermostParenthesis code example>\n```",
            "```cpp\n<statementBegin code example>\n```"
          ],
          "default": "innermostParenthesis",
          "description": "%c_cpp.configuration.vcFormat.indent.multiLineRelativeTo.description%",
          "scope": "resource"
        },
```

The examples would be displayed in the settings UI, after the setting, for the selected option.  i.e.:

![image](https://user-images.githubusercontent.com/49173979/112069248-bc5b8800-8b28-11eb-8abd-568e2a82dc87.png)

![image](https://user-images.githubusercontent.com/49173979/112067177-e01ccf00-8b24-11eb-8f1a-96c94747d4b5.png)

**Comment by roblourens** [comment]
This is a good suggestion. I will merge it into https://github.com/microsoft/vscode/issues/70589 which has similar suggestions. I would like to do this but don't have an ETA for you.
