### ISSUE TITLE
Vs Code Display Issue

### ISSUE THREAD

**Issue by Pegasus005** [microsoft/vscode#119552]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

![1616481158281](https://user-images.githubusercontent.com/31448606/112105821-de114980-8bd2-11eb-8c1d-9825bca3a45f.JPEG)

This Display problem showing only when working on VS Code And its latest version installed in my system

**Comment by Pavlos-Efstathiou** [comment]
I think that's your GPU's fault

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/92379

Please disable hw acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
