### ISSUE TITLE
Type of variable breakpoint not clear in Breakpoints view

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119588]
Testing #119197

I can see no way to tell that one of my variable breakpoints is for "Read" and the other is for  "Access"

![image](https://user-images.githubusercontent.com/38270282/112150403-54687880-8be0-11eb-8a17-b1f686a492ee.png)

Also, if I right click on one of these breakpoints and choose "Edit Condition" nothing happens.

**Comment by isidorn** [comment]
For the edit condition we have this feature request https://github.com/microsoft/vscode/issues/114903
For showing the type of access. I think we should render it. Similar in style to how breakpoints show the breakpoint path..

@yannickowow let me know if you are interested in providing a PR that would tackle this issue. If you do not have time I can also look into this. Thus for now assigning to April

**Comment by yannickowow** [comment]
@isidorn I can investigate if you want. 
Would it be better to see it like breakpoint paths or breakpoints line ? 
And it would be a sentence like : `Break On: Read` or something like "R", "W", "A" ? 

For the first case, here is a prototype :
![image](https://user-images.githubusercontent.com/45362067/112192901-acff3c00-8c07-11eb-9bec-a9a5453952c7.png)

**Comment by isidorn** [comment]
Yeah styling exactly like that. It should be like breakpoint paths.
However I think we can just say: "Read", "Write", "Access"
"Break On" part is not needed

**Comment by isidorn** [comment]
Fixed via https://github.com/microsoft/vscode/pull/119817
Thanks a lot @yannickowow 👏
