### ISSUE TITLE
Pinning Tabs - Keep Pinned Tabs in Sight 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#119512]
Today when you pin a tab at the top and scroll through the tabs, the pinned tab ends up being hidden. 

![Pinning Tab](https://user-images.githubusercontent.com/19276747/112050526-329ec100-8b0e-11eb-91d6-9f7795b12e2e.gif)

Request from Customer Interview:
Keep the pinned tab in view even through scroll - used to the Visual Studio implementation of pinning tabs. 

Could this be done via user setting for pinning tabs?

**Comment by IllusionMH** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/108355#issuecomment-706514266
it is intentional for default value of `workbench.editor.pinnedTabSizing` which inherits behavior from regular tabs.
Chanhing this value will keep them always in fixed position.

**Comment by claudiaregio** [comment]
Thanks for the quick response! I actually ended up finding that setting but the option names did not intuitively explain the behavior to me, thought it just reduced the size, not changed the behavior

**Comment by bpasero** [comment]
PR welcome to update the settings description 👍

**Comment by mcanepa** [comment]
If I pin a tab, I expect it to be pinned, regardless of the tab size.

Tha tab size setting should be a complement to the pin feature.
