### ISSUE TITLE
Terminal menu automatically closes

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#119589]
Testing #119427

macOS Catalina

The menu closes automatically after a while (not always the same duration, maybe some background refresh?)

![Mar-23-2021 13-54-39](https://user-images.githubusercontent.com/9205389/112150460-69dda280-8be0-11eb-81b9-12d2c8c3fb8d.gif)

**Comment by Tyriar** [comment]
Yeah this is really annoying, we definitely need to fix this.
