### ISSUE TITLE
Hide sidebar when debug panel opens

### ISSUE THREAD

**Issue by elkebirmed** [microsoft/vscode#119510]
Is there a feature to toggle between sidebar and (debug, terminal,..etc)?
I really want to have my debug panel on the right side shows when sidebar is hidden and closed when sidebar on the left is open.

**Comment by ArturoDent** [comment]
You could set up a toggle in a keybinding with a macro extension (here using multi-command), like :

```jsonc
{
    "key": "alt+r",
    "command": "extension.multiCommand.execute",
    "args": {
      "sequence": [
        "workbench.action.togglePanel",
	"workbench.action.toggleSidebarVisibility"
      ]
    },
  },
```

This assumes a starting point of one or the other open but not both. 

 If you are looking for a way to have vscode detect you have opened the Panel, for example, and then it will close the Side Bar or vice versa that is a different feature request.  But perhaps you could use this keybinding in the meantime.

**Comment by elkebirmed** [comment]
@ArturoDent  Yes, it helps but still a feature like so will be awesome

**Comment by isidorn** [comment]
For now please use the workaround @ArturoDent provided.
Closing this as duplicate as we have other feature requests for more flexible layouts
