### ISSUE TITLE
intellisense in comments

### ISSUE THREAD

**Issue by xucaen** [Microsoft/vscode#11954]
- VSCode Version: 1.5.2
- OS Version: windows 7 professional sp1

Steps to Reproduce:

1.  create a .js or .php file
2.  type in a comment

Intellisense should be disabled while typing in a comment.

**Comment by ramya-rao-a** [comment]
Duplicate of #11704 

@xucaen Please go through the discussions in #11704 and other issues mentioned there to get to know the latest on this issue
