### ISSUE TITLE
Formatting code no longer works

### ISSUE THREAD

**Issue by Ghost---Shadow** [Microsoft/vscode#11957]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 6.1.7601

Formatting code no longer works

**Comment by mrmlnc** [comment]
Please, provide more details. For example, what language are you using?

**Comment by Ghost---Shadow** [comment]
C#

**Comment by ramya-rao-a** [comment]
Formatting for C# is supported via extensions. What extensions do you have installed?
Also is this a regression? Was this working for you before and stopped with the latest update?
Do you see the `Format Code` option in the context menu when you right click in your code?

**Comment by Ghost---Shadow** [comment]
I just updated to 1.5.2 it got fixed again.

The only C# related extension I have installed is 
C# for Visual Studio Code (powered by OmniSharp)

Anyways, thanks for the quick response.

**Comment by mindgrub-rkoch** [comment]
I'm having the same issue with C#. Format Code does not appear in the context menu for me and whenever I use the shift+alt(option)+F, I get the character `Ï`. I did a fresh install through homebrew and it did not help. I've also tried installing clang-format, which also did not work.

**Comment by ramya-rao-a** [comment]
@mindgrub-rkoch Are you referring to the [Clang-Format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) extension? According to the link, this extension is for C/C++/Java/JavaScript/Objective-C/Protobuf  and not C#

What other extensions do you have?

**Comment by mindgrub-rkoch** [comment]
I've also tried Uncrustify (1.3.3). I installed uncrustify via homebrew and set the `uncrustify.executablePath` in my settings to `/usr/local/bin/uncrustify` which did not work. I also tried `/usr/local/Cellar/uncrustify/0.63` as the path which still did not work. According to the docs for that, I don't necessarily need to set the `uncrustify.configPath` 

> An uncrustify configuration file should be set, although on Linux and OS X it will try to use a default config file.

**Comment by ramya-rao-a** [comment]
@mindgrub-rkoch  The C# extension should have provided formatting feature for you. Can you log an issue in the repo for the C# extension? They should be able to help you narrow down on the issue.

**Comment by mindgrub-rkoch** [comment]
Will do. Thanks.

**Comment by Xelnath** [comment]
I am also having difficulty getting the uncrustify plugin to work with vs code. 

... could you guys just release the same settings you have for the JS code formatting for CSharp?

**Comment by ramya-rao-a** [comment]
@Xelnath C# formatting is controlled by extensions, can you provide a detailed feature request there? If the extension owner determines that they need something from VS Code APIs, they will get in touch with us.
