### ISSUE TITLE
html.autoClosingTags isn't respected when language mode is Plain Text

### ISSUE THREAD

**Issue by manicmachine** [microsoft/vscode#119520]
Issue Type: <b>Bug</b>

Closing tags are automatically inserted into a document when entering words enclosed in <>'s regardless of how html.autoClosingTags is configured when the language mode is Plain Text.

Since there's no other option to disable these automatic closing tags beyond the aforementioned setting, I assume it's the correct one to use.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.64GB free)|
|Process Argv|--crash-reporter-id 0c2487ee-4d38-4010-b1f8-ae2a8a85187e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.8
better-toml|bun|0.3.2
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
javascript-ejs-support|Dig|1.3.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|6.3.1
auto-close-tag|for|0.5.10
code-runner|for|0.11.3
vscode-angular-html|gha|1.7.0
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
mips|kda|0.0.6
unity-code-snippets|kle|1.3.0
electron-debug|kod|18.11.1
rust-analyzer|mat|0.2.529
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
python|ms-|2021.3.658691958
vscode-pylance|ms-|2021.3.2
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.3.0-insiders
powershell|ms-|2021.2.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular2-inline|nat|0.0.17
angular-console|nrw|17.0.3
material-icon-theme|PKi|4.6.0
java|red|0.76.0
vscode-xml|red|0.15.0
crates|ser|0.5.7
rust-pack|Swe|0.2.29
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
vscode-lldb|vad|1.6.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.0
vscode-java-dependency|vsc|0.18.1
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-todo-highlight|way|1.0.4
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.9.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by yume-chan** [comment]
Caused by `formulahendry.auto-close-tag` extension

**Comment by aeschli** [comment]
Please file against the formulahendry.auto-close-tag extension: https://github.com/formulahendry/vscode-auto-close-tag
