### ISSUE TITLE
Multi-select in notebooks causes text selection in markdown

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119500]
When trying combinations of cmd + shift click, I sometimes notice that text gets selected accidentally:

![Kapture 2021-03-22 at 10 57 42](https://user-images.githubusercontent.com/35271042/112036211-98368180-8afd-11eb-832f-f00e84aa8c6a.gif)

**Comment by mjbvz** [comment]
As a side note, I've always found it weird I can't select text in markdown cells. Clicking and dragging moves the cell itself, while double click opens edit mode
