### ISSUE TITLE
Format nested arrays

### ISSUE THREAD

**Issue by xucaen** [Microsoft/vscode#11958]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

In php (and I would assume javascript as well), I am defining an array which has a nested array.

Steps to Reproduce:

1.  Enter this code:

$temp = array(
'label1' => 'this is a test'
,'label2' => array(
'inner1' => 'test1'
,'inner2' => 'test2'
,'inner3' => 'test3'
,'inner4' => 'test4'
)
,'label3' => 'another test'
);

2. press Shift+Alt+F

The arrays are not formatted as I would expect. Should look something like:

$temp = array(
    'label1' => 'this is a test'
    ,'label2' => array(
        'inner1' => 'test1'
        ,'inner2' => 'test2'
        ,'inner3' => 'test3'
        ,'inner4' => 'test4'
    )
    ,'label3' => 'another test'
);

[test.zip](https://github.com/Microsoft/vscode/files/469914/test.zip)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by xucaen** [comment]
Thank you. Upon further research, it would seem that the author of that
extension has abandoned the extension. I would kindly ask that it be
removed from the extensions repository.

Thank you.
