### ISSUE TITLE
Flicker while executing cell

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119582]
Testing #119367

* open GH issue notebook with code and markdown cell
* run code cell
* when the result is rendered (for the first time) there is split-second screen cheese where the result overlays the rendered markdown

<img width="910" alt="Screenshot 2021-03-23 at 12 46 13" src="https://user-images.githubusercontent.com/1794099/112141779-09e1fe80-8bd6-11eb-86d6-8ca571b062f5.png">

https://user-images.githubusercontent.com/1794099/112141802-0fd7df80-8bd6-11eb-90ad-bdd526536b81.mov

**Comment by mjbvz** [comment]
Seems like there's a frame where the output overlaps with everything (including code cells):

![Screen Shot 2021-03-31 at 4 34 40 PM](https://user-images.githubusercontent.com/12821956/113223903-0f2af300-923f-11eb-9f08-172ce6f2f1c0.png)

That doesn't seem to be regression.

Then there's a frame where the output just overlaps with the markdown cells:

![Screen Shot 2021-03-31 at 4 35 23 PM](https://user-images.githubusercontent.com/12821956/113223945-2669e080-923f-11eb-820d-0bd182e91e7e.png)

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/issues/120384#issuecomment-816888198 ensured that there is no overlap between code cell and outputs. Events to update the scroll top of markdown cells and reset output's max height is sent as a single event into the webview now, not sure though if you can still see the overlap between markdown cells and output, please double check.

**Comment by mjbvz** [comment]
There's still a single frame of overlap between the markdown and the output. It's only really visible while profiling but will keep this open to see if there's anything we can do

**Comment by mjbvz** [comment]
I think it's looking pretty good now overall. There is a frame or two of overlap when profiling, but I don't notice it much in normal usage

If you find any cases that cause noticeable jitters, please open a new issue with steps to reproduce so we can fix it
