### ISSUE TITLE
functionality to search commits when you trigger the action to cherry pick

### ISSUE THREAD

**Issue by danielo515** [microsoft/vscode#119575]
There is an action to cherry pick a commit on the omnibar, which opens a dialog where you should input the commit sha you want to pick. It will be awesome if such input allow you to lazily search a commit by commit message. That will ease the task of picking the right commit a lot

![image](https://user-images.githubusercontent.com/2270425/112138480-d7360700-8bd1-11eb-85ed-3d2dfd07dfd2.png)
![image](https://user-images.githubusercontent.com/2270425/112138506-e0bf6f00-8bd1-11eb-9423-5cd78ba8faf2.png)

**Comment by eamodio** [comment]
FYI, if you use GitLens, you can use its cherry-pick support from its _Git Command Palette_ and it offers richer functionality for choosing what to cherry pick

**Comment by danielo515** [comment]
> FYI, if you use GitLens, you can use its cherry-pick support from its _Git Command Palette_ and it offers richer functionality for choosing what to cherry pick

Can you specify a bit more? The only other options I found are, to do a lot of clicks to get to this UI, search and then cherry pick (very tedious process):
![image](https://user-images.githubusercontent.com/2270425/112268920-fc7d5080-8c77-11eb-8a96-1180d9cb734a.png)

And this other command that simply does nothing:
![image](https://user-images.githubusercontent.com/2270425/112268983-1159e400-8c78-11eb-8004-9e01b18f1f82.png)

Thanks
