### ISSUE TITLE
Test getting started auto-opening and new contribution model

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119543]
Refs: https://github.com/microsoft/vscode/issues/119097 (still proposed, but it's what'll be in this iteration)

- [ ] anyOS @lszomoru
- [x] anyOS @bamurtaugh

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119543%0A%0A)

---

This iteration we added the ability for extensions to contribute to the welcome page and have their contributions auto-opened on install.

Testers:

* set `workbench.welcomePage.experimental.extensionContributions` (hidden setting) to `open`, `openToSide`, or `openInBackground`
* Try out contributing to the welcome page using new contribution api. The Top-Level entry "walkthroughs" is hidden from suggest while this is under review, but beyond that the intellisense should guide you and give snippets where relevant. Sample extension: https://github.com/JacksonKearl/md-to-html/
* Try marking one or more top level categories as `primary`, then experiment with what happens when you install its vsix under the above `extensionContributions` values. 
  * If no getting started page is active, it should open the extension's contributions in a new editor either in the active group, in a group to the side, or in the background. 
  * If some getting started page is active, it should auto-scroll to the newly added extensions contributions.

**Comment by lszomoru** [comment]
Nice work 👏🏻
