### ISSUE TITLE
Test new title option in `showInputBox` and `showQuickPick` API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#119526]
Refs: #77423

- [x] anyOS @lszomoru
- [x] anyOS @kieferrm

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23119526%0A%0A)

---

> NOTE: This is a proposed API but there is no enableProposedApi gate because the API change is tiny, won't change, and uncontroversial so I'm writing a test plan item for it now.

Grab the quickinput-sample extension and open this file:
https://github.com/microsoft/vscode-extension-samples/blob/main/quickinput-sample/src/basicInput.ts

Include a `title: "Hello world"` property in the options of both the `showInputBox` call and `showQuickPick` call.
Here's the diff of what I changed to make tsc stop yelling:
![image](https://user-images.githubusercontent.com/2644648/112066470-a13a4980-8b23-11eb-97f7-a6c006445e25.png)

run the extension and run this command
![image](https://user-images.githubusercontent.com/2644648/112066281-4c96ce80-8b23-11eb-9618-f2446e08f427.png)
then run through both of these:
![image](https://user-images.githubusercontent.com/2644648/112066334-60dacb80-8b23-11eb-9a5b-d5f7bd335b2d.png)

They should give you a title, in my case `Hallo`:
![image](https://user-images.githubusercontent.com/2644648/112067003-96cc7f80-8b24-11eb-8af4-551beffdf4b9.png)

**Comment by lszomoru** [comment]
Works as advertised 👏🏻
