### ISSUE TITLE
Shift + Click does not create a selection

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119605]
Testing #119118

* on macOS
* click on a markdown cell
* shift+click on another markdown cell
* I would have expected this to create a selection, like it does in Finder.
* I think right now I must use the keyboard to do multiple selections

**Comment by rebornix** [comment]
Tested that it doesn't reproduce with builtin markdown with `"notebook.experimental.useMarkdownRenderer": false` in settings.

**Comment by mjbvz** [comment]
Duplicate of #119515 I believe
