### ISSUE TITLE
not notified before using workspace terminal profile

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119682]
Testing #119427

On Linux, when I modify a workspace's `terminal.integrated.profiles.linux`, I see the entry immediately usable without needing to trust the workspace or even notifying me that it is coming from a workspace:

![image](https://user-images.githubusercontent.com/8586769/112199136-14e36180-8bcb-11eb-9cc9-5ab1db6f6b7c.png)

I have not modified `terminal.integrated.shell` or `terminal.integrated.shellArgs`, but I think even if those are modified I should be warned before running a workspace-contributed profile.

**Comment by gjsjohnmurray** [comment]
See also #119600
