### ISSUE TITLE
Search on workspace with encoding cp850

### ISSUE THREAD

**Issue by bernatrm** [microsoft/vscode#119659]
Issue Type: <b>Bug</b>

Search don't work if you have encoding CP850 defined on User o Workspace currently active

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.04GB free)|
|Process Argv|--folder-uri file:///c%3A/Datos/GIT/Viva.DynamicsNav --crash-reporter-id 51cbdb43-bc83-405f-b0a9-fd5cd23a4a15|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.39.0
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
gitlens|eam|11.3.0
json-tools|eri|1.0.2
gc-excelviewer|Gra|3.0.41
AWK|lug|0.0.2
vscode-docker|ms-|1.11.0
mssql|ms-|1.10.1
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
azurecli|ms-|0.5.0
powershell|ms-|2021.2.2
team|ms-|1.161.1
salesforce-vscode-slds|sal|1.4.0
salesforcedx-vscode|sal|51.5.0
salesforcedx-vscode-apex|sal|51.5.0
salesforcedx-vscode-apex-debugger|sal|51.5.0
salesforcedx-vscode-apex-replay-debugger|sal|51.5.0
salesforcedx-vscode-core|sal|51.5.0
salesforcedx-vscode-lightning|sal|51.5.0
salesforcedx-vscode-lwc|sal|51.5.0
salesforcedx-vscode-soql|sal|51.5.0
salesforcedx-vscode-visualforce|sal|51.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943:30277001
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by roblourens** [comment]
Did you set the `files.encoding` setting? That is required to search in files with that encoding, and it will only search with that encoding, it can only search with one encoding at a time.

**Comment by bernatrm** [comment]
Yes, I've this setting on the .vscode folder, on the file settings.json.

 "files.encoding": "cp850"

**Comment by roblourens** [comment]
What exactly is the problem, can you give more details?
