### ISSUE TITLE
Not asked for confirmation using workspace profile

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#119600]
Testing #119427

macOS Catalina

I expected there to be a confirmation dialog when opening a profile configured in the workspace settings:
![image](https://user-images.githubusercontent.com/9205389/112156855-ee332400-8be6-11eb-928c-09fdf3494f0a.png)

**Comment by Tyriar** [comment]
@chrmarti you may have already opted into workspace shells previously, it shares the same mechanism as shell/shellArgs

**Comment by chrmarti** [comment]
@Tyriar I used a new user data dir. 🤔

**Comment by Tyriar** [comment]
I can repo on mac
