### ISSUE TITLE
Cell overlap when dropping at top of notebook

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119652]
Testing https://github.com/microsoft/vscode/issues/119367

Drag cell 2 to become the first cell in the notebook. It overlaps with cell 1. Doesn't happen when not using the new markdown renderer.

![image](https://user-images.githubusercontent.com/323878/112189187-009a6700-8bc1-11eb-8aab-7218b4893e03.png)

**Comment by mjbvz** [comment]
Duplicate of #119604
