### ISSUE TITLE
Can't run npm scripts using WSL from vs code

### ISSUE THREAD

**Issue by gratiae** [microsoft/vscode#119619]
- VS Code Version: 1.49.1
- OS Version: 19042.868

Node installed on wsl.
When I try to run npm scripts from vs code window "NPM SCRIPTS", I get an error: "The terminal process "C:\WINDOWS\System32\wsl.exe -e npm run watch" failed to launch (exit code: 1)"
If I type this command manually in the terminal, then everything works. 

I've tried running the example script as advised [here ](https://github.com/microsoft/vscode/issues/80875#issuecomment-545025214)- but I get the same error. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
Can you try running the following task and share the output?

```json
		{
			"type": "process",
			"command": "C:\\WINDOWS\\system32\\wsl.exe",
			"args": [
				"-e",
				"which",
				"npm"
			],
			"label": "Which npm",
			"problemMatcher": []
		}
```

Are you using nvm to manager your node version? Using nvm doesn't always work with tasks because it adds things to your shell start up scripts, which don't run with tasks.
