### ISSUE TITLE
Extension contribution in getting started page didn't get checked off

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#119697]
Testing #119543

- Set `"workbench.welcomePage.experimental.extensionContributions": "open"`
- Install https://github.com/JacksonKearl/md-to-html/
- The new welcome/getting started page opens
- Open an example folder through getting started page (first option). The folder opens, and when I execute command to reopen getting started page, this first checkbox is completed.
- Attempt to complete second checkbox to "Preview your Markdown," however, it doesn't get checked off:

![image](https://user-images.githubusercontent.com/25310137/112208341-7ad4e680-8bd5-11eb-9c78-2d1d4c6f92bc.png)

![image](https://user-images.githubusercontent.com/25310137/112208267-68f34380-8bd5-11eb-98c1-b1742f44d8c1.png)

![image](https://user-images.githubusercontent.com/25310137/112208306-70b2e800-8bd5-11eb-801d-423e96bff28c.png)

Since I believe just opening a folder was enough to check off the first item, I thought just opening a .md file would be enough to check off the second.

**Comment by bamurtaugh** [comment]
When I tried the remaining steps (selected the blue call to action), 3 out of 5 ended up getting checked off:

![image](https://user-images.githubusercontent.com/25310137/112209321-8f65ae80-8bd6-11eb-87a9-936192edb1ed.png)

However, perhaps that's because this is a test extension/due to extension implementation? i.e. I see how in "Create your .html file," the call to action is "Open Markdown File" again:

![image](https://user-images.githubusercontent.com/25310137/112209401-a3a9ab80-8bd6-11eb-8fcc-39648a395c57.png)

**Comment by JacksonKearl** [comment]
Yes, you need to actually do the thing specified in the task description for it to get checked off. Extensions can choose what the events required for checking off are

**Comment by bamurtaugh** [comment]
I see - I interpreted opening a markdown file to be sufficient based on the button, but I see now that I'd need to do the specific complete steps in the description. And as a backup if users were confused, they can manually check off the items anyways. I'll close this one as user misunderstanding then, thanks for the clarification :)
