### ISSUE TITLE
Getting started theme selection image looks broken to me

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#119692]
In the getting started theme selection step, the image looks sort of broken to me: 

![Screen Shot 2021-03-23 at 12 16 26 PM](https://user-images.githubusercontent.com/12821956/112205229-d4d3ad00-8bd1-11eb-8f9a-8e0c80505ac9.png)

When I first saw it, I thought it was a rendering error

**Comment by JacksonKearl** [comment]
cc @digitarald

**Comment by digitarald** [comment]
New buttons are used now instead of the image.
