### ISSUE TITLE
Too clever (i.e., lousy) editor behavior

### ISSUE THREAD

**Issue by CaymanTurtleBeach** [microsoft/vscode#119665]
Issue Type: <b>Bug</b>

Cannot type 'else' after an ending brace without getting ElementScanner (no space - just pressing enter) OR equals(object) (space after 'else' then enter.
Absurd. Quit trying to be clever. I should not have to dig through every editor setting to get basic behavior (what I type is what I want). Let the people who like to customize every detail dig through the settings and customize to their heart's content.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
remote-wsl|ms-|0.54.6
azure-account|ms-|0.9.7
fabric8-analytics|red|0.3.2
java|red|0.76.0
vscode-commons|red|0.0.4
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details>

**Comment by Tyriar** [comment]
This is likely due to an extension, is this Java as you have a lot of Java extensions installed?
