### ISSUE TITLE
Drag and drop of sparse multiple selected cells does not work

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119610]
Testing #119118

* spend quite some time to use shift+arrow up/down to select 3 code cells
* drag and drop to a different location
* I would expect that all 3 code cells will now be adjacent

https://user-images.githubusercontent.com/5047891/112161483-7ca9a480-8beb-11eb-8d37-6d5ef2fcae28.mp4

**Comment by rebornix** [comment]
It's kind of current limitation. We support dnd on a single selection (which can contain more than one cell) but it doesn't work with multiple distinct selections.

**Comment by roblourens** [comment]
Seems to work now, I'm pretty sure I fixed it this year
