### ISSUE TITLE
Test Explorer: What's the sidebar called?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119674]
Testing #119545

I think we typically call it the "Test Explorer" internally, but it's called "Test" when right clicking the icon and the header is "Testing":

![image](https://user-images.githubusercontent.com/2193314/112197237-16138f00-8bc9-11eb-90aa-bf729191d788.png)

**Comment by NotWearingPants** [comment]
`Test` is a verb and a "call to action" much like `Run and Debug`, but it being a noun makes it sound more confusing. I still vote for `Test` rather than `Test Explorer`

**Comment by connor4312** [comment]
I went with `Testing`
