### ISSUE TITLE
Difficult to merge cells using multi selection + actions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119609]
Testing #119118

* today there are the actions "Join with next/previous cell"
* but this is awkward to operate when wishing to join let's say 3 cells
* special care must be taken to only select the first two cells and then invoke the command Join with next cell, which will actually merge the 3 cells
* you could add a new action "Join Selected cells"
* alternatively the commands could be tweaked to work only on selected cells and ignore the next/prev cells

e.g.

https://user-images.githubusercontent.com/5047891/112160681-b037ff00-8bea-11eb-8239-ea85e6cbae4d.mp4

**Comment by rebornix** [comment]
> you could add a new action "Join Selected cells"


👍  https://github.com/microsoft/vscode/issues/119004
