### ISSUE TITLE
Previous terminal contents aren't cleared when a refresh happens

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119678]
Testing #119108

![](https://memes.peet.io/img/21-03-c7fe60d8-3c68-4cff-9405-e3bcbd81c2ef.png)

**Comment by connor4312** [comment]
Executing `clear` also only removes the second prompt

**Comment by Tyriar** [comment]
Any other details on a repro here? I thought I fixed this bug already but I guess not. Is it consistent?

**Comment by connor4312** [comment]
It happens 100% of the time for me.

```
Version: 1.55.0-insider
Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e
Date: 2021-03-23T05:02:44.557Z (13 hrs ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
```

**Comment by Tyriar** [comment]
Does disabling local echo help?

**Comment by connor4312** [comment]
no, same thing happens with it set to -1
