### ISSUE TITLE
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119627]
@Roccoriu commented on [Tue Mar 23 2021](https://github.com/microsoft/vscode-jupyter/issues/5244)

## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): 2021.4.678042391
-   Python Extension version (available under the Extensions sidebar): 2021.3.658691958
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20h2 build 19042.867
-   Python and/or Anaconda version: 3.6.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A: both remote and local

## Expected behaviour

Extension installs, as latest versions for every extension is used.

## Actual behaviour

Installation fails because of incompatible version. But latest version of VS Code is used
![image](https://user-images.githubusercontent.com/25778176/112129107-583bd100-8bc7-11eb-8608-294d15977a15.png)

## Steps to reproduce:
Unable to reproduce on other machines. 

## Logs
No log was displayed. Just the little error message shown above.

---

@DonJayamanne commented on [Tue Mar 23 2021](https://github.com/microsoft/vscode-jupyter/issues/5244#issuecomment-805002536)

Thanks for filing this issue, I'm going to move this to VS Code as I cannot replicate this and we do not control how Jupyter is installed into VS Code.
**For VS Code:**
* We have an insider build of extension in the marketplace, with engine set to `"vscode": "1.55.0-insider"`
* The other build in the marketplace has engine set to `"vscode": "^1.54.0"`

Hence, if user is in VS Code Stable, VS Code should only download & install the version thats compatible with Stable, & similarly for VS Code Insiders.

**Comment by DonJayamanne** [comment]
**For VS Code:**
* We have an insider build of extension in the marketplace, with engine set to `"vscode": "1.55.0-insider"`
* The other build in the marketplace has engine set to `"vscode": "^1.54.0"`

Hence, if user is in VS Code Stable, VS Code should only download & install the version thats compatible with Stable, & similarly for VS Code Insiders.

**Comment by rebornix** [comment]
@Roccoriu can you reproduce this issue if you uninstall the extension, reload the window and then install from the marketplace again?

**Comment by Roccoriu** [comment]
> @Roccoriu can you reproduce this issue if you uninstall the extension, reload the window and then install from the marketplace again?

Yes, the issue even persisted through a complete reinstall of VS Code including all the extensions. But so far I wasn't able to reproduce this on other machines.

**Comment by imjiangjun** [comment]
I met the same problem when updating python on remote machine through Remote Development.
`[2021-03-24 14:31:42.593] [renderer1] [error] connect ECONNREFUSED 127.0.0.1:10809: Error: connect ECONNREFUSED 127.0.0.1:10809
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

[2021-03-24 14:35:48.106] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.","    at /home/jiangjun/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]

[2021-03-24 14:35:48.130] [renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
    at /home/jiangjun/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by sandy081** [comment]
/duplicate

This is being discussed and investigated here https://github.com/microsoft/vscode/issues/119073
