### ISSUE TITLE
Check marks use for radio group

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119629]
Testing #119545

<img width="285" alt="Screenshot 2021-03-23 at 16 38 24" src="https://user-images.githubusercontent.com/1794099/112173839-37d73b00-8bf6-11eb-82e6-4406cdca6b52.png">

The test view filter menu uses check marks to select filters but the semantics seems to be those of a radio group, e.g I can only select one element in that group. Unsure if that's a limitation of the native menus but it surely is confusing

**Comment by connor4312** [comment]
This is similar to what the SCM view does. I do not know of a better way in menus 

![](https://memes.peet.io/img/21-03-19d48df5-470d-4ef5-90c0-ecdad85f8f68.png)

**Comment by jrieken** [comment]
True story, tho the wording is much clearer. In the test view I was repeatedly selecting a checked item to get out of this. So maybe: Show Failed, Show Executed, Show All
