### ISSUE TITLE
Terminal `onLineData` is inserting extra white space characters into lines that get broken

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119631]
To repro:
1. Start the VS Code build task.
2. Make the terminal small.
3. Put a breakpoint at
 
https://github.com/microsoft/vscode/blob/ba117e60c20f3e97eb4bdeaab9d11b24815c57d2/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L788-L788

4. Cause an error in the build task in a file where the file name wraps to a new terminal line.
5. Observe that when the breakpoint is hit, wrapped lines have extra spaces, often in the middle of file names which is particularly bad for the terminal tasks system.

Discussed with @Tyriar, and it seems that setting `"terminal.integrated.localEchoLatencyThreshold": -1` fixes the issue.

**Comment by Tyriar** [comment]
I think this always happened in remote when local echo was enabled, just the pty host changes caused higher latency on Windows.

Local echo is causing `onLineData` to fire because of how the cursor move happens. A potential fix is to only fire `onLineData` if the cursor move changes the row.

**Comment by Tyriar** [comment]
@alexr00 there was a bug fix recently that fixed a bunch of local echo issues, does this still happen?

**Comment by alexr00** [comment]
I reset the setting and tried to repro. Looks like the issue is fixed 🎉
