### ISSUE TITLE
Test explorer: I don't know what dark green ticks mean

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119643]
Testing #119545

![image](https://user-images.githubusercontent.com/2193314/112185401-6d136700-8bbd-11eb-9418-58902626edf9.png)

**Comment by Tyriar** [comment]
If this means it's stale which I'm beginning to suspect then grey would be better and a change in the tooltip to explain it. It's pretty weird how it doesn't show up on the parent though.

**Comment by connor4312** [comment]
Yes, these are [retired](https://github.com/microsoft/vscode/issues/115086) tests. I can have the tooltip update.

Subtrees are marked as outdated, in this case just the suite was marked as outdated rather than the entire file, which is something that I should tweak in the test provider.

**Comment by Tyriar** [comment]
@connor4312 "stale" seems like a better word for that, I wouldn't know what retired means. Also if it is stale then the top-level item should also show that status (if any of its children are stale) and grey would make more sense to me than dark green.

**Comment by connor4312** [comment]
I'll add the tooltip label for these
