### ISSUE TITLE
Run python in terminal with path having spaces

### ISSUE THREAD

**Issue by jinhw1989** [Microsoft/vscode#11965]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. create a folder with spaces in its name, and create a simple python file
2. ctrl+shift+p to run the file in VSCode, it will pop up an error which related to the path of the folder. which should have quotes on that path. 

```bash
> python c:\test - test\test.py
# error
can't find '__main__' module  in 'c:\test'
```

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/pythonVSCode#308
