### ISSUE TITLE
Overlap after reloading window with new markdown renderer

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119661]
Testing #119367

- Open vscode's README in the markdown notebook
- Edit `## Contributing`
- Reload the window

Cells overlap with the image, only happens with the new renderer

![image](https://user-images.githubusercontent.com/323878/112193498-2cb7e700-8bc5-11eb-8587-f9b141a1a325.png)

**Comment by rebornix** [comment]
I can reproduce this by 

* scroll the markdown notebook a bit down, and the image is displayed partially

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/113349467-f11bcc00-92ec-11eb-8817-c84ac7e4ba65.png">

* reload

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/876920/113349507-02fd6f00-92ed-11eb-86a3-489dab14ceb7.png">
