### ISSUE TITLE
Dragging a cell sometimes doesn't work

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119683]
Testing #119118

It looks like either the cursor or the hit target aren't correct, since it makes it look like you can drag, but you can't
![drag](https://user-images.githubusercontent.com/641685/112199278-5e8c7600-8be4-11eb-95f4-3742b90d2355.gif)

**Comment by rebornix** [comment]
oh no, it's the `+ code` toolbar ;(

**Comment by misolori** [comment]
@eamodio does this repro is you disable the new notebook markdown renderer `"notebook.experimental.useMarkdownRenderer": false`?

**Comment by rebornix** [comment]
Verified that I can reproduce with `useMarkdownRenderer` to `true` but not reproduce when it's set to `false`.

**Comment by eamodio** [comment]
Yeah, I can only repro with the new renderer

**Comment by mjbvz** [comment]
Duplicate of #117489
