### ISSUE TITLE
Using `shift` to select cells feels off sometimes

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119676]
Testing #119118

When `shift` selecting cells, you see to be in a "paint" or "unpaint" mode (e.g. selecting or unselecting). Although sometimes depending on the current selection, the last item of a selection doesn't behave the same way.

![selection](https://user-images.githubusercontent.com/641685/112198100-26386800-8be3-11eb-842f-725416caf143.gif)

Also there are other times where it seems like a cell's selection almost gets stuck, and you can't unselected it other than clearing all of the selections using `esc`

**Comment by rebornix** [comment]
Good point that sometimes it's not clear that how you end up with multiple selections and how to clear them. I'm also seeing the same in file explorer.


https://user-images.githubusercontent.com/876920/112238724-6e1ab780-8c02-11eb-96ee-7a6ac873aeca.mov


As you see from above screen recording, I select two distinct selections first, and then from the very top, try to select all cells, the original selections are now being "deselected".

cc @joaomoreno @isidorn

**Comment by joaomoreno** [comment]
Any suggestions how to solve this?

I can make it that shift-navigation only adds to selection. And removing from selection needs to be done one-by-one via the already existing ctrl-shift-enter.
