### ISSUE TITLE
VSCode freezing laptop when debugging against  chrome V89 

### ISSUE THREAD

**Issue by erikswed** [microsoft/vscode#119647]
Issue Type: <b>Bug</b>

Yesterad it starter happening. I starting debugging against Chroma Version 89.0.4389.90 (Officiell version) (64 bitar). It takes 5-20 minutes until:

entire PC freezes
system clock in the lower right corner just stops
sometimes after 5-15 minutes it comes back I can close all apps and start over.
Sometimes I get blue screen restart.
Sometimes a message wait or reopen VSCode after 10 minute.
When it happens if I'm quick I can close VSCode and restart.
I have not installed any new VSCode extentions in a long time. If I start VSCode and leave it open nothing happens. As Soon as I do "npm start" this problem starts

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (0.62GB free)|
|Process Argv|--crash-reporter-id 891b8aa0-d991-49f5-9bfe-20210929839e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|3.3.1
vscode-icontheme-nomo-dark|be5|1.3.6
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
vscode-pull-request-github|Git|0.24.0
svgeditor|hen|2.9.0
plantuml|jeb|2.14.4
git-graph|mhu|1.29.0
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
vscode-scss-formatter|sib|2.1.0
unique-window-colors|stu|1.0.51
html-preview-vscode|tht|0.2.5
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943cf:30277002
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by connor4312** [comment]
Please provide reproduction steps if you are able.

**Comment by erikswed** [comment]
> Please provide reproduction steps if you are able.

That's it wh.

**Comment by erikswed** [comment]
> Please provide reproduction steps if you are able.

I debug this [my repo](https://github.com/erikswed/Greta-100-React-Web-App) locally on my laptop that's it been working on this for 6 month but I dont think it has to do with this specific project. Maybe there's some log files from Chrome or Vscode that I can dump here

**Comment by erikswed** [comment]
I get the WDF_VIOLATION

![image](https://user-images.githubusercontent.com/3285249/112206224-f9517880-8c15-11eb-90df-81f7fcd6d5d3.png)

**Comment by connor4312** [comment]
This is unlikely to be an issue with VS Code, and more likely a hardware or OS issues

**Comment by erikswed** [comment]
Here's the Blue Screen crash dmp file with the WDF_VIOLATION crash 

https://drive.google.com/file/d/1agsbUJp3tlbyfbuUD_13C05eSORFtHS7/view?usp=sharing

**Comment by erikswed** [comment]
![image](https://user-images.githubusercontent.com/3285249/112208414-9d3c2380-8c18-11eb-80f2-8330bc4f5329.png)

**Comment by erikswed** [comment]
> This is unlikely to be an issue with VS Code, and more likely a hardware or OS issue

Thanks I will report back after trying to fix it

**Comment by erikswed** [comment]
I now use debugger for Edge and problem resolved, I disabled Chrome Debugger


![image](https://user-images.githubusercontent.com/3285249/112226232-2f9af200-8c2e-11eb-88ab-cce06d37eb1b.png)
