### ISSUE TITLE
Feature request: add tabName field

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#119672]
Testing #119427

I added the following profile:
```json
"Test": {
            "source": "Git Bash"
        },
```

And noticed that it showed up, but when I clicked on it, the tab name switched to `bash` again.
I wonder if tabName can be another field:
```json
"Test": {
            "source": "Git Bash",
            "tabName": "Test"
        }
```

**Comment by Tyriar** [comment]
`tabName` won't work because it doesn't define the tab's name since it could be made up of multiple splits.

@meganrogge had the idea of using `overrideName?: boolean` to define this which I like, that would just use the profile name (the key) so no need to redefined "Test" in your example.

**Comment by Tyriar** [comment]
Let's use a `boolean?` instead of `string?`

**Comment by meganrogge** [comment]
to verify, set `overrideName: true` in a terminal profile and change the profile name (the key of the object). It should now be reflected in the auto detected list and dropdown with that name.

**Comment by Tyriar** [comment]
Also try running git log in the new terminal and make sure it doesn't switch to "git"
