### ISSUE TITLE
Discovering tests takes forever and doesn't give progress

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119679]
Testing #119545

I know VS Code is big but this has been running for minutes:

![image](https://user-images.githubusercontent.com/2193314/112198375-43147180-8bca-11eb-93bc-d5d27e83d9a6.png)

Any indicator when you click to open the notification would be better than none, eg. `<files checked>/<files discovered so far>`

**Comment by connor4312** [comment]
This is probably a bug in the selfhost provider not signalling completion for something...

**Comment by Tyriar** [comment]
It's still going 😉 if there was progress it would be clearer that it was stuck and not just taking a long time

**Comment by connor4312** [comment]
How can you tell it's still going, is it still discovering files? Discovery and expanding any single file is nearly instant for me.

**Comment by Tyriar** [comment]
Still:

![image](https://user-images.githubusercontent.com/2193314/112200661-adc6ac80-8bcc-11eb-8c5d-1e92ff774a2e.png)

**Comment by connor4312** [comment]
Oh, yea. I mean that is probably still shown because I forgot to `report({ busy: false })` in the selfhost provider at some point🙂

**Comment by connor4312** [comment]
I think this was probably a result of uncaught errors being thrown which aborted the promise before lack of business was reported. Let me know if this still happens in the next Insiders.
