### ISSUE TITLE
Screen cheese when doing drag & drop at the top

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119604]
Testing #119118

* open `endgame.github-issues`
* drag the 6th cell "Open Issues on the Milestone" to the top of the file
* observe screen cheese

https://user-images.githubusercontent.com/5047891/112158864-df4d7100-8be8-11eb-8d27-1a6449f94757.mp4

**Comment by rebornix** [comment]
Not seeing this with builtin markdown, might be related to the custom renderer.

**Comment by eamodio** [comment]
![image](https://user-images.githubusercontent.com/641685/112223171-efbd1600-8bff-11eb-94ea-ea377b92c61c.png)

**Comment by rebornix** [comment]
yeah, it seems that even if the setting is set to `false`, it still uses the custom markdown renderer.

**Comment by rebornix** [comment]
@eamodio  can you confirm you have `"notebook.experimental.useMarkdownRenderer": false` in `.vscode/settings.json` other than removing it or commenting it out? If it's deleted, it will still use the custom markdown renderer by default (we will flip this before we ship to stable).

**Comment by eamodio** [comment]
I'm pretty sure that was the case -- but I was only able to repro this issue once.

**Comment by rebornix** [comment]
I think it's already fixed.
