### ISSUE TITLE
getPathLabel(): Cannot read property '1' of null

### ISSUE THREAD

**Issue by vavans** [Microsoft/vscode#11962]
- VSCode Version: 1.5.2
- OS Version: windows 8

Steps to Reproduce:

1. Install a fresh vs code from https://code.visualstudio.com/Docs/?dv=win, with no extension installed
2. Follow the extension tutorial until the first F5: https://code.visualstudio.com/docs/extensions/example-hello-world
3. The new vscode instance is launching with the extension but we get an error :

`/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:115 Cannot read property '1' of null: TypeError: Cannot read property '1' of null
    at Object.s [as getPathLabel] (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:29:17760)
    at t.getDescription (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:85:7799)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:103:21871
    at Array.forEach (native)
    at t.getUniqueTabLabels (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:103:21710)
    at t.doUpdate (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:103:20917)
    at t.doRefresh (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:103:22330)
    at t.e.onSchedule (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:100:22145)
    at t.e.refresh (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:100:22443)
    at e.createTitleControl (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:104:12264)`

I unintalled/installed vscode. I tried with insider build too, always the same error.

**Comment by vavans** [comment]
I manage to hack the workbench.main.js to continue working on my addon while waiting for a fix.
For those who encounter the same issue, here is how to hack this:

- open ...\Microsoft VS Code (Insiders)\resources\app\out\vs\workbench\workbench.main.js
- replace 
```javascript
 s.refresh(!0)
``` 
by 
```javascript
/*s.refresh(!0)*/undefined
```
- save and restart all instances of vscode

**Comment by vavans** [comment]
It has to do with the layout of the Host instance of vscode (where the plugin in development is tested).
With the hack, i managed to launch the host. 
I closed all the documents and side editors, then i closed all vscode instances, **removed the hack from workbench**, then relaunch a Host instance with my plugin in: tada! no error.
So i think the default Host layout (opened folder, and open documents, etc) survives a vscode uninstall.

Where are those information stored ? And how can we reset the Host layout ?

**Comment by bpasero** [comment]
@vavans I am clueless what kind of error you see. does it reproduce now anymore?

**Comment by vavans** [comment]
@bpasero Hi, i guess it's quite difficult to reproduce due to the fact that the host instance crash depends on its  layout (opened documents, side editors, etc.) and i didn't figure out what exact layout is causing the crash. 

I have a second machine where the bug is still visible, if you tell me where is stored the host instance layout, i could analyze its content and come back with more information.

**Comment by bpasero** [comment]
Actually from the stacktrace this seems to happen in `getPathLabel()`

**Comment by vavans** [comment]
Ok, i think i got it.
First we can reproduce the issue **without** launching an extension development host.

The issue comes from a key in the local storage used by vscode : 
`storage://workspace/c%3A/Users/VANNESJU/Documents/Langages/Haskell/VSCode-haskell-intero/test/sample/editorstacks.model`

This key stores the layout state of a workspace. 
Here is JSON setted:
```json
{
    "groups": [
        {
            "label": "Left",
            "editors": [
                {
                    "id": "workbench.editors.files.fileEditorInput",
                    "value": "{\"resource\":\"file://c%3A%5CUsers%5CVANNESJU%5CDocuments%5CLangages%5CHaskell%5CVSCode-haskell-intero%5Ctest%5Csample%5Csrc%5CLib.hs\"}"
                }
            ],
            "mru": [
                0
            ]
        }
    ],
    "active": 0
}
```

We can see there is a problem with the resource file uri :
`file://c%3A%5CUsers%5CVANNESJU%5CDocuments%5CLangages%5CHaskell%5CVSCode-haskell-intero%5Ctest%5Csample%5Csrc%5CLib.hs`

This uri causes the crash at startup described in this issue (when you open the related workspace of course).

The next question is, how this uri could be setted here ?

It comes from a language server extension.
When a `goto definition` request is sent from vscode to the language server, the location response can contains an "almost invalid" file uri (like this one). However, VSCode manages to parse the "almost invalid" uri and satisfies the goto definition by opening the file, and setting the localstorage key accordingly.

**Comment by bpasero** [comment]
@vavans very good find and indeed I think @jrieken made a change in 1.5 to return `null` for `fsPath` when asking for `fsPath` on such malformed resources. In the end the extensions have to fix this on their end.

I pushed a fix on my end to handle this case, but I think there can be many more places where this will bubble up in errors.

**Comment by vavans** [comment]
Great, thanks !

**Comment by isidorn** [comment]
Adding verified based on code review
