### ISSUE TITLE
无法打开终端

### ISSUE THREAD

**Issue by SonnySwolf** [Microsoft/vscode#11964]
- VSCode Version: 1.4.0
- OS Version: win10

Steps to Reproduce:
无法打开终端，输出Ctrl ~，  提示 ”通过退出代码 1 终止的终端进程“
1. 输出   Ctrl + ~
2. 出现错误信息    ”通过退出代码 1 终止的终端进程“

**Comment by octref** [comment]
@SonnySwolf 

This should be fixed in 1.5. Can you update and see if this problem still exists?

Please use English in the repository. Thank you.

**Comment by NewFuture** [comment]
@SonnySwolf 

This bug exists in all Windows.

When the `path` contains Chinese encoding (or other non-ascii characters) , it can't open the terminal.

I guess this bug  is due to the **encoding** of Windows terminal (**not uft-8**).

**Comment by NewFuture** [comment]
an example for Folder path:
>C:\中文路径\

**Comment by Tyriar** [comment]
Duplicate of #7727

**Comment by SonnySwolf** [comment]
是的，这个问题是由于中文路径引起的。

**Comment by HotHunter** [comment]
there are no Chinese encoding in my `path` , but i still get this error

> "terminal.integrated.shell.windows":"E:\\cmder\\Cmder.exe",
