### ISSUE TITLE
Ctrl+arrows give unexpected behavior

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119681]
Testing #119118

Ctrl+[Right|Left] &mdash; doesn't seem to do anything, kind of expected it to behave the same as [Right|Left]
Ctrl+Up &mdash; put the cell in edit mode and focused the editor, I expected it to move the focus to the preview cell without changing the  selection (like Windows Explorer)
Ctrl+Down &mdash; seems to scroll down slowly. Again I expected it to move the focus to the next cell without changing the selection

**Comment by rebornix** [comment]
It seems the ctrl+arrows are already being used by actions.

**Comment by roblourens** [comment]
> Ctrl+[Right|Left] — doesn't seem to do anything, kind of expected it to behave the same as [Right|Left]

Meaning expand/collapse headers? Why?

> Ctrl+Up — put the cell in edit mode and focused the editor, I expected it to move the focus to the preview cell without changing the selection (like Windows Explorer)

If I understand correctly, this is basically what arrow up/down by themselves are already doing, right? ctrl+up/down are matching the editor by scrolling without moving focus. Except that they are double-booked with focus in/out of output, which maybe should only happen when focus is in the editor

**Comment by roblourens** [comment]
I think the only thing to fix here is that ctrl+up invokes `focusOutOutput` when focus is not in the output, and focuses the editor.
