### ISSUE TITLE
Getting Started: Reset Progress doesn't seem to do anything

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#119699]
Testing #119543

I have various steps completed on my getting started page:

![image](https://user-images.githubusercontent.com/25310137/112209547-d2c01d00-8bd6-11eb-88db-548564e32ea7.png)

I try the command to reset progress:

![image](https://user-images.githubusercontent.com/25310137/112209586-dce21b80-8bd6-11eb-9664-fb8d02970c30.png)

But nothing seems to have changed:

![image](https://user-images.githubusercontent.com/25310137/112209654-ecf9fb00-8bd6-11eb-9d1e-b354f5d553a8.png)

**Comment by JacksonKearl** [comment]
Yeah, that's started as a debugging aid and needed reload, but the infra is now in place that it shouldn't anymore.
