### ISSUE TITLE
uninstalling extension via cli doesn't update extension editor actions

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119660]
Testing #119518

![image](https://user-images.githubusercontent.com/8586769/112192862-94b9fd80-8bc4-11eb-8e5a-3cd7b38b7029.png)

**Comment by JacksonKearl** [comment]
Similar for remote-containers but the viewlet doesn't update either

![image](https://user-images.githubusercontent.com/8586769/112194251-e6af5300-8bc5-11eb-9552-89237413e0cb.png)

**Comment by JacksonKearl** [comment]
Also cc @Tyriar the "inappropriate ioctl for device" and "no job control in this shell" messages are new versus stable, not sure if you know anything about that.

**Comment by Tyriar** [comment]
No idea, was it just a one off?

**Comment by JacksonKearl** [comment]
Every time I use the cli for extension management

**Comment by Tyriar** [comment]
@JacksonKearl but only `--uninstall-extension`, not `--install-extension`?

**Comment by JacksonKearl** [comment]
No, it can happen either way: 
![image](https://user-images.githubusercontent.com/8586769/112202044-2d08b000-8bce-11eb-824b-7ab45de4499e.png)

Not sure why it didn't in the earlier screenshot

**Comment by Tyriar** [comment]
@deepak1556 this may be caused by Electron starting as part of the extension management events and inheriting the console?

**Comment by deepak1556** [comment]
@Tyriar this was not obvious to me either, strace clarified it. Firstly, the issue repros outside vscode terminal, so the following tests were done in system shell.

```sh
$ strace --env=ELECTRON_RUN_AS_NODE=1 /snap/code-insiders/current/usr/share/code-insiders/code-insiders /snap/code-insiders/current/usr/share/code-insiders/resources/app/out/cli.js --install-extension ms-python.python

clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLDstrace: Process 5839 attached
, child_tidptr=0x7f0f867d7e50) = 5839
[pid  5839] set_robust_list(0x7f0f867d7e60, 24) = 0
[pid  5831] close(29 <unfinished ...>
[pid  5839] close(5 <unfinished ...>
[pid  5831] <... close resumed>)        = 0
[pid  5839] <... close resumed>)        = 0
[pid  5831] read(28,  <unfinished ...>
[pid  5839] close(6)                    = 0
[pid  5839] pipe2([5, 6], O_CLOEXEC)    = 0
[pid  5839] write(6, "*", 1)            = 1
[pid  5839] setsid()                    = 5839
[pid  5839] open("/dev/null", O_RDONLY) = 30
[pid  5839] dup2(30, 0)                 = 0
[pid  5839] fcntl(0, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid  5839] close(30)                   = 0
[pid  5839] dup2(27, 1)                 = 1
[pid  5839] fcntl(1, F_GETFL)           = 0x2 (flags O_RDWR)
[pid  5839] close(26)                   = 0
[pid  5839] fcntl(2, F_GETFD)           = 0x1 (flags FD_CLOEXEC)
[pid  5839] fcntl(2, F_SETFD, 0)        = 0
[pid  5839] fcntl(2, F_GETFL)           = 0x8002 (flags O_RDWR|O_LARGEFILE)
[pid  5839] close(27)                   = 0

......

[pid  5839] execve("/bin/bash", ["/bin/bash", "-ilc", "/snap/code-insiders/current/usr/"...], 0x2cbd41b9f7b0 /* 1 var */ <unfinished ...>

.......

[pid  5839] ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid  5839] dup(2)                      = 3
[pid  5839] prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=1024*1024}) = 0
[pid  5839] fcntl(255, F_GETFD)         = -1 EBADF (Bad file descriptor)
[pid  5839] dup2(3, 255)                = 255
[pid  5839] close(3)                    = 0
[pid  5839] ioctl(255, TIOCGPGRP, 0x7ffd0fc5c904) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  5839] getpid()                    = 5839
[pid  5839] ioctl(255, TIOCGPGRP, 0x7ffd0fc5c904) = -1 ENOTTY (Inappropriate ioctl for device)
[pid  5839] fstat(2, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x2), ...}) = 0
[pid  5839] write(2, "bash: cannot set terminal proces"..., 77bash: cannot set terminal process group (-1): Inappropriate ioctl for device
) = 77
[pid  5839] write(2, "bash: no job control in this she"..., 35bash: no job control in this shell
) = 35

```

The output is actually from a child process that does the `execve` step. Its from https://github.com/microsoft/vscode/blob/05ce54df77c242b1b8ea5fd93d720c62fdb183e6/src/vs/platform/environment/node/shellEnv.ts#L85 that is invoking the bash script in interactive mode from a detached child process,

Minimal repro:

```sh
ELECTRON_RUN_AS_NODE=1 /snap/code-insiders/current/usr/share/code-insiders/code-insiders -e "const cp = require('child_process'); const child = cp.spawn('/bin/bash', ['-ilc', '/snap/code-insiders/current/usr/share/code-insiders/code-insiders -p \"console.log(process.versions)\"'], {env: {ELECTRON_RUN_AS_NODE: 1}, detached: true, stdio: ['ignore', 'pipe', process.stderr]}); child.on('exit', () => console.log('child exited'))"
```

Issue can be fixed by removing the `-i` from the above command. But I have a follow-up question, does the code cli to install extension now spawn the app ? If so, why does it have to get shell env using the child process hack above, can they be short-circuited ?

**Comment by Tyriar** [comment]
@deepak1556 I think some CLI commands (like ext management) need to start Electron to initialize important services that can't be used within the CLI (without larger refactoring. @joaomoreno perhaps we can just remove the `-i`?

**Comment by joaomoreno** [comment]
I no longer remember why `-i` is it. But there's one thing I can guarantee: things will break for users if you remove it.

> does the code cli to install extension now spawn the app

AFAIK `--install-extension` (and friends) shouldn't spawn Electron, but just Node (with `ELECTRON_AS_NODE`), unless @sandy081 changed this recently?

**Comment by joaomoreno** [comment]
> Also cc @Tyriar the "inappropriate ioctl for device" and "no job control in this shell" messages are new versus stable, not sure if you know anything about that.

Yeah these are definitely weird. What does `which code-insiders` return?

**Comment by deepak1556** [comment]
I should have added this info as well, this is a new behavior with insiders cli that invokes the probing code, the current stable does not have a similar trace.

Two things to be fixed:

1) Child process created in detached mode should not invoke bash with interactive mode as the process does not have a controlling terminal, see minimal repo in https://github.com/microsoft/vscode/issues/119660#issuecomment-806430824 , executable can be replaced with node

```sh
node -e "const cp = require('child_process'); const child = cp.spawn('/bin/bash', ['-ilc', 'node -p \"console.log(process.versions)\"'], {detached: true, stdio: ['ignore', 'ignore', process.stderr]}); child.on('exit', () => console.log('child exited'))"
```

2) Cli app should not invoke the shell probing code

**Comment by chrmarti** [comment]
> I no longer remember specifically why -i is there. But there's one thing I can guarantee: things will break if you remove it.

`-l` (login shell) makes Bash source `.bash_profile` (or if that doesn't exist `.profile`) and that often sources `.bashrc`. `.bashrc` often first checks if it is in an interactive shell (`-i`) and exits if not. We have been using the combination `-il` in `shellEnv.ts` for a long time to make sure we get all the user customizations from `.bash_profile` and `.bashrc`.

I think the CLI should set VSCODE_CLI=1 like `code` does. That will let shellEnv.ts skip the probing. /cc @bpasero

**Comment by deepak1556** [comment]
@chrmarti thanks for the context on the use of interactive mode for the shell probing. Our current shell probing is launched via child process in a detached mode `{detached: true}`, node basically does setsid call to accomplish that https://github.com/libuv/libuv/blob/master/src/unix/process.c#L294. From the documentation of setsid

```
setsid() creates a new session if the calling process is not a
       process group leader.  The calling process is the leader of the
       new session (i.e., its session ID is made the same as its process
       ID).  The calling process also becomes the process group leader
       of a new process group in the session (i.e., its process group ID
       is made the same as its process ID).

       The calling process will be the only process in the new process
       group and in the new session.

       Initially, the new session has no controlling terminal.  For
       details of how a session acquires a controlling terminal, see
       credentials(7).
```


Since there is no controlling terminal unless we open, invoking the bash command in interactive mode will result in `inappropriate ioctl for device" and "no job control in this shell"`.

Question:

why is the shell probing code launched as a detached process ? Can it just run in the same session as parent process, that way it will also get the controlling terminal of the parent.

**Comment by bpasero** [comment]
> I think the CLI should set VSCODE_CLI=1 like code does. That will let shellEnv.ts skip the probing. /cc @bpasero

If you think there is something wrong with `VSCODE_CLI`, please open a separate issue with steps to reproduce.

**Comment by joaomoreno** [comment]
> I think the CLI should set VSCODE_CLI=1 like `code` does. That will let shellEnv.ts skip the probing. /cc @bpasero

That's what confuses me. `VSCODE_CLI` was created specifically for the CLI.

> why is the shell probing code launched as a detached process ? Can it just run in the same session as parent process, that way it will also get the controlling terminal of the parent.

Also unsure why anymore. It's there since the Big Bang: https://github.com/microsoft/vscode/blame/3d5e0586528e4439e41d06f960ec295b9de46492/src/vs/base/node/env.ts#L18

Lots of info in these issues:

- https://github.com/microsoft/vscode/issues/21655
- https://github.com/microsoft/vscode/issues/22400
- https://github.com/microsoft/vscode/issues/14229
- https://github.com/microsoft/vscode/issues/7644

**Comment by bpasero** [comment]
So here is the deal: we set `VSCODE_CLI` properly for the normal vscode launch here:

https://github.com/microsoft/vscode/blob/d96f34c867bbcc7991bd1b60f3f8c933a27a7b7c/src/vs/code/node/cli.ts#L121-L121

But for some reason we don't set it for extensions management:

https://github.com/microsoft/vscode/blob/d96f34c867bbcc7991bd1b60f3f8c933a27a7b7c/src/vs/code/node/cli.ts#L56-L62

So someone forgot to move it up I guess.

**Comment by joaomoreno** [comment]
`shouldSpawnCliProcess` is a misleading name. Nothing gets spawned: it just loads up a bunch of more code and runs functions on them and exists. Only that Node process is ever alive in that case. No full Electron comes up.

**Comment by bpasero** [comment]
Either way, we need to set `VSCODE_CLI` properly.

**Comment by joaomoreno** [comment]
Now I get it, what @bpasero points at is: maybe there is code loaded from `vs/code/node/cliProcessMain` which eventually goes into `shellEnv.ts`. In that case, `VSCODE_CLI` wouldn't be set and the user env would be wrongfully probed. Might that be what's happening here?

**Comment by deepak1556** [comment]
> Also unsure why anymore. It's there since the Big Bang: https://github.com/microsoft/vscode/blame/3d5e0586528e4439e41d06f960ec295b9de46492/src/vs/base/node/env.ts#L18

Thanks, I will remove it for the next iteration, if anything breaks can revisit, would be surprising if it did.

**Comment by joaomoreno** [comment]
![brave](https://media.giphy.com/media/ZF2vOJpNZBXU8TgS5D/giphy.gif)

**Comment by bpasero** [comment]
With https://github.com/microsoft/vscode/commit/3a2a24e452c5e79781e71cda0c7eb1153899f041, `VSCODE_CLI` is now defined earlier to ensure any code executing in `cli.ts` will correctly inherit this.
