### ISSUE TITLE
A few suggestions to make this the best code editor ever!

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#11966]
A few suggestions that will make this the best code editor out there.  I mainly use it for PHP.

I would love to have a line go vertically from opening and closing elements like in notepad++. 
Example. <div></div>  { }

It would be nice if you made CTRL-D to duplicate lines like in notepad++.   Then your Code editor would be all I hope for.   

Also one last thing,  When you have a lot of tabs open make the horizontal (left to right) scrolling bar bigger (it is 3 pixels tall  and would be nice if it was 6 pixels - it only shows up when you hover over it anyways).  Then we don' have to strain our eyes to move it.

Thanks!  I love this editor the most!

**Comment by soljohnston777** [comment]
Also, if you could keep the code colors the same even if it is inside an echo "(code)"; or print "(code)"; quotation.

**Comment by alefragnani** [comment]
Hi @soljohnston777 ,

I will try to help you with some of your suggestions:

* You can have **Line Indent Guides**, but for that you should configure with: `editor.renderIndentGuides: true`. For now, it is based in _indentation_, not _semantics_
* It already exists a **duplicate line** command, but with different name. You could try `Copy Line Down` and `Copy Line Up`. Both with different keybinding, that you also can customize.
* Could you update a print about your **color issue**? In the meantime, you could try different **Themes**, maybe some of them will better fit your PHP experience.

For the **scrolling bar**, there is no option to customize, so it should be evaluated by the VS Code team. Personally, I don't use tabs :smile: 

Hope this helps.

**Comment by bpasero** [comment]
I am closing this because it violates our submission guidelines (1 issue per issue, not multiple). Also it seems you got some help so please file new issues (plural) for the remaining issues.

**Comment by soljohnston777** [comment]
Thanks!  This really helped.
