### ISSUE TITLE
Notebook diff does not use Longest Common Substring algorithm

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119603]
Testing #119118

* open a notebook e.g. `endgame.github-issues`
* drag a single cell (e.g. 6th "Open Issues on the Milestone" heading) to the top of the file
* open the diff editor

Observe how this results in a huge diff:
![image](https://user-images.githubusercontent.com/5047891/112158366-62ba9280-8be8-11eb-87fb-5cada726c491.png)

The best would be to adopt the `diffComputer`, which could be enhanced to accept rich objects (not just `number[]` or `string[]`).

**Comment by rebornix** [comment]
> The best would be to adopt the diffComputer, which could be enhanced to accept rich objects (not just number[] or string[]).

👍 , we are now using `LcsDiff(new CellSequence(original), new CellSequence(modified))` to do the diff computation, by generating hash for every cell. I'll see if diffComputer is better.

**Comment by alexdima** [comment]
That's very interesting. Using `LcsDiff` sounds good, but that should work better than what I observe. Are you by any chance taking the cell index as part of the hash computation? IMHO moving a single cell from position 6 to position 1 should give two changes: a single insertion and a single deletion rather than 6 changed cells. e.g. with text:

![image](https://user-images.githubusercontent.com/5047891/112200023-19ca0480-8c0f-11eb-900a-ef0a239d04d5.png)

**Comment by rebornix** [comment]
@alexdima I wonder if you have other changes in the document (unintentionally, like running a cell, copy/paste and then undo, which can lead to some metadata change of cells), which can lead into this weird diffing result. I tried to reproduce with your steps


https://user-images.githubusercontent.com/876920/112396611-afbc6880-8cbd-11eb-9e90-c0049be7322d.mov


As you can see that the diff is as expected. Can you try to reproduce again, and when you successfully reproduce, please click the third button on the editor toolbar to open it in the text diff editor, and then share the diff with me

<img width="285" alt="image" src="https://user-images.githubusercontent.com/876920/112396686-d5497200-8cbd-11eb-9468-98fc7a000c6a.png">

**Comment by alexdima** [comment]
@rebornix It no longer reproduces on latest insiders. Not sure if it's related, when I created the issue I was also seeing https://github.com/microsoft/vscode/issues/119604 . So maybe it has to do with the custom markdown renderer?

**Comment by rebornix** [comment]
@alexdima it's very likely that. Let's close it for now and reopen if we run into this again.
