### ISSUE TITLE
context.extension props don't work

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119636]
Testing #119548

- Call `context.extension.isActive` -> Get error `Uncaught TypeError: Be(...).isActivated is not a function`
- Debugging, I see that the `extensionService` is not a `IExtHostExtensionService`
- I think `this` should be `that`

https://github.com/microsoft/vscode/blob/4b3ba3ea44c20f019dec0e42bba5209edf18aff2/src/vs/workbench/api/common/extHostExtensionService.ts#L420

**Comment by eamodio** [comment]
Doh -- thanks!
