### ISSUE TITLE
New markdown renderer still used in accessibility mode

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119669]
Testing #119367

Linux

![image](https://user-images.githubusercontent.com/323878/112195975-ca141a80-8bc7-11eb-82fe-1dc5386a8a7b.png)

Yes those are emoji in the Linux font

**Comment by mjbvz** [comment]
Ah, so currently the `notebook.experimental.useMarkdownRenderer` setting overrides any of the other considerations. We should likely make it so that `accessiblitySupport` has higher precedence

**Comment by mjbvz** [comment]
To verify, make sure that if `accessiblitySupport`, the new renderer is not used even if you have set `"notebook.experimental.useMarkdownRenderer": true`
