### ISSUE TITLE
Error when using custom profile with string arg on linux

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119677]
Testing #119427

Maybe update the json schema to disallow string argument on linux?

The terminal process failed to launch: A native exception occurred during launch (args as a string is not supported on unix.).

![image](https://user-images.githubusercontent.com/8586769/112198331-3a23a000-8bca-11eb-884b-af4fed8d074f.png)

**Comment by Tyriar** [comment]
👍 we should ignore args when it's a string for linux/macos, on `main` this will give a warning as well.
