### ISSUE TITLE
Most actions don't work with sparse multiple selected cells

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#119614]
Testing #119118

* spend some time to use shift+arrow up/down to select 2 distinct cells
* use an action like duplicate cells down (also duplicate cells up doesn't work on all cells)
* only one cell gets duplicated

https://user-images.githubusercontent.com/5047891/112162084-0194be00-8bec-11eb-91d6-bb80e0526a30.mp4

**Comment by rebornix** [comment]
Similar to https://github.com/microsoft/vscode/issues/119610

**Comment by rebornix** [comment]
Let's ask each command author to handle this if they see it fit.
