### ISSUE TITLE
NotebookCellExecutionTask#appendOutput should support on array case

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119601]
The `appendOutput`-functions should support to be called with output not an array of outputs. Maybe that should be the only way to do it..

**Comment by roblourens** [comment]
Could take `output | output[]`. Since each will trigger a call to the main thread so I want to allow batching for a bunch of outputs. For replace too or just append?

**Comment by jrieken** [comment]
Yeah, maybe for append as well. And yeah, I would do this API-only, e.g leave the IPC call with an array and even consider a tiny debounce in the extension host. I noticed that printing numbers `0` to `1000` isn't super fast

**Comment by jrieken** [comment]
@roblourens What about output items?

**Comment by roblourens** [comment]
Sure 👍
