### ISSUE TITLE
Make a pass over all places where we show paths and use white-space: pre

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#11960]
![sep-13-2016 16-18-32](https://cloud.githubusercontent.com/assets/323878/18477413/e5ead458-79cd-11e6-9979-0dac2203d965.gif)
This is a totally dumb case but I encountered it while testing something in Node with spaces in paths and it feels worth fixing to me.

If you edit leading or trailing whitespace in the file explorer, the change isn't saved. If you add some outside of vscode, it won't be displayed in the tree. If there are multiple spaces between letters, it's collapsed to look like one. And, if you edit the file name in some other way, then all leading/trailing spaces are removed.

**Comment by bpasero** [comment]
@roblourens I split this issue up into 2. See also https://github.com/Microsoft/vscode/issues/12013

**Comment by bpasero** [comment]
Already fixed for explorer, open editors and tabs by using the newly introduced file labels. Will be adopted more thorughout the workbench.
