### ISSUE TITLE
Getting started - empty list

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119617]
Testing #119543

If there are not items in the "Getting Started" section we should either provide a "congratulations" message, or remove the section altogether as it currently looks weird when it is empty (see screenshot). 

![image](https://user-images.githubusercontent.com/3372902/112164980-a1534b80-8bee-11eb-9cc4-d0641b599c23.png)

**Comment by JacksonKearl** [comment]
Thanks, duplicate of #119496
