### ISSUE TITLE
Refresh Tests should not show the test welcome page/button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119675]
Testing #119545

A progress bar or something to indicate things are happening would also be nice.

![recording (12)](https://user-images.githubusercontent.com/2193314/112197997-e913ac00-8bc9-11eb-94c5-4bfd66e3ab6b.gif)

**Comment by lramos15** [comment]
Seems better than what it was in the gif above, but I still do see the button flash briefly

**Comment by connor4312** [comment]
@lramos15 do you see it on refresh or just when the view is first opened?

**Comment by lramos15** [comment]
![recording](https://user-images.githubusercontent.com/4544166/116452540-d4ab7a80-a82b-11eb-96e3-de985faf9949.gif)
On refresh. You can't see my click the refresh button as I didn't share my whole screen, but here's me clicking refresh

**Comment by connor4312** [comment]
I think this was the same root cause behind the test view occasionally getting stuck on the welcome.
