### ISSUE TITLE
Right click context menu disappears quickly while debugging python

### ISSUE THREAD

**Issue by mfiro** [microsoft/vscode#119656]
Issue Type: <b>Bug</b>

I noticed that on my linux (Ubuntu 20.04) computer, while debugging a python code, I'm not able to choose an option from the context menu. It appears but before I can choose anything, it disappears.

Here is a gif regarding this issue:
![Vscode_bug](https://user-images.githubusercontent.com/51599115/112190337-306b5e00-8c05-11eb-89fa-b82cb71d2404.gif)

[EDIT]:
I am not sure, if an option is automatically selected from the context menu. It disappears really quickly.

[EDIT 2]:
Actually it does auto select the highlighted option under the mouse cursor. If I keep the right click the menu I see the menu. It makes working with context menu really difficult. 

[EDIT 3]:
It doesn't only happen in debug mode, but also in normal mode.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 2153)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.56GB (7.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id a75ac558-5c3d-41fc-afce-fc875f2b0a66|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157
ayu|tea|0.20.1

(1 theme extensions excluded)

</details>

**Comment by scottfurry** [comment]
I can confirm this happens to me also. However, the problem only occurs when the cursor is in block comment text. Type of quotes (single or double) surrounding text doesn't matter.

For the rest of the code, the context menu behaves normally.

VS Code 1.54.3
OS Linux x86_64 5.4.97

**Comment by isidorn** [comment]
This seems to be the issue with custom context menus, thus forwarding to @sbatten 
Debug is not doing anything special here

**Comment by sbatten** [comment]
this is a duplicate issue for native menus on linux. #113175
