### ISSUE TITLE
Adjust cursor position on new line or don't emit empty spaces

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#11961]
- VSCode Version: Code - Insiders 1.6.0-insider (67a46126c83aac8c715d4c318fcfd18a183658bf, 2016-09-13T11:09:28.863Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

TypeScript code 
```ts
class Test {

    test() {

    }
}
```

1. Put cursor on line `2:0`
2. Hit enter

Initial:
![image](https://cloud.githubusercontent.com/assets/1723815/18477365/717dd642-799b-11e6-847b-0c1ca9a39288.png)

User presses Enter:

![image](https://cloud.githubusercontent.com/assets/1723815/18477384/7eb03a1c-799b-11e6-97a4-186930cd7571.png)

Notice how cursor is at `3:0` but there are spaces in front of cursor
Natural thing is to use tab to get to proper indent location which will leave empty spaces in front:

![image](https://cloud.githubusercontent.com/assets/1723815/18477416/9f91e5fa-799b-11e6-9b6b-297055261097.png)

(Users might not be aware there are extra whitespaces if they dont have `renderWhitespace`)

So seems like it should put cursor at the end of that whitespaces or not append whitespaces

FYI - Both Atom and Sublime - do not append whitespaces

**Comment by Bill-Stewart** [comment]
It seems like option `editor.trimAutoWhitespace` should do this automatically (unless I misunderstand what this option does). As a workaround you can use command `editor.action.trimTrailingWhitespace` (default `ctrl+k ctrl+x`) to do it manually. You could also try the option `files.trimTrailingWhitespace` that is supposed to automatically remove trailing whitespace when writing a file.

**Comment by wallverb** [comment]
Thanks @Bill-Stewart  

I do have `"editor.trimAutoWhitespace": true` and it does not affect it

`files.trimTrailingWhitespace` and `editor.action.trimTrailingWhitespace` do help - but still - it seems like an issue that should be addressed

**Comment by Bill-Stewart** [comment]
Agree, it seems `editor.trimAutoWhitespace` should address this, unless (as I said) I don't understand what it does.

**Comment by Bill-Stewart** [comment]
See #8145 (https://github.com/Microsoft/vscode/issues/8145) - "The `editor.trimAutoWhitespace` trims automatic whitespace inserted by the editor when you press `Enter` or `Tab`."

**Comment by wallverb** [comment]
Wow, so it should work then but it doesn't. Thanks for finding that

**Comment by Bill-Stewart** [comment]
I just tested your use case on the Windows platform and can't reproduce it.

**Comment by wallverb** [comment]
Please try with `editor.formatOnType: true` - seems like the issue is related to that

**Comment by Bill-Stewart** [comment]
Enabled `editor.formatOnType` in my settings. Still can't repro.

**Comment by wallverb** [comment]
Thanks - maybe OSX issue - would appreciate if someone could test on OSX - both insiders and stable are having this issue with `editor.formatOnType: true`

**Comment by alexandrudima** [comment]
![ts-format-on-type](https://cloud.githubusercontent.com/assets/5047891/18750731/1083834a-80e5-11e6-8a07-e20beff96104.gif)

It appears to be caused by the format on type TS language provider.

**Comment by waderyan** [comment]
Migrated to TS repo. https://github.com/Microsoft/TypeScript/issues/11074
