### ISSUE TITLE
Run tests in file doesn't update editor gutter icons

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119644]
Testing #119545

![recording (5)](https://user-images.githubusercontent.com/2193314/112185732-be235b00-8bbd-11eb-9a66-6aa62ea059c7.gif)

**Comment by connor4312** [comment]
This is actually a bug in the selfhost test provider, there are multiple files with that same-named suite and tests and only the first-discovered one is actually in the tree and valid.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-selfhost-test-provider/commit/d6c4069abca3802c67fb944b3a54ef86752f9aee
