### ISSUE TITLE
Test Runner allows you to spam rerun button while the test is running

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#119655]
Steps to Reproduce:

1. Start a long running test through the test panel
2. Click the re-run button next to the test
3. 🐛  You can queue up infinite amounts of that test.

**Comment by connor4312** [comment]
This is somewhat intentional. VS Code doesn't make assumptions about any kind of concurrency support the runner has. In the selfhost test provider I do queue runs, but you could imagine a simpler test runner would happily execute all of them in parallel.

**Comment by lramos15** [comment]
Let's assume the two cases 
1. Parallel
2. Serial

If I'm queuing up the exact same test again and again what benefit do you gain? Even if it can execute them all at once a test should not return a separate result.

**Comment by connor4312** [comment]
You could have made code changes between your queues, particularly if the test takes a little while to run. Though in the case of spamming the button with <1s between queues that's less likely.

**Comment by lramos15** [comment]
If you make code changes between your queues shouldn't you stop that test since the initial run is now invalid? It seems a little wonky to me, but if it's intentional I'm fine closing this.

**Comment by connor4312** [comment]
I think I'll add a small debounce here for those who like double clicking on things 🙂
