### ISSUE TITLE
New cursors not always announced via screenreader Command + Option + Up/Down 

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#119654]
Testing #119082

Testing on Mac with Voiceover. When I use `command + option + up/down` to set multiple cursors quickly, it seems that the screenreader swallows up the middle cursors and only ends up announcing the last one. I think I expected the screenreader to announce all of them after the keyboard operation is completed, but I am not totally sure if this is just how screenreaders read actions when they happen so quickly. 

![recording (9)](https://user-images.githubusercontent.com/9721254/112189236-33048e00-8bda-11eb-9ed3-719dc5c4ca39.gif)

**Comment by isidorn** [comment]
Thanks for filling this, however this is just how Screen Readers read things.
We are sending the correct data to be read, just VoiceOver decides to act like this.
For example NVDA reads both - you can see it if you turn on Tools > Speech Viewer

Thus closing as designed
