### ISSUE TITLE
Getting started - extension installation notification

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119624]
Testing #119543

If the extension is contributing a getting started walkthrough, and the setting is `openInBackground` I was wondering if the notification that is being displayed when the extension installation completes, should have a button to open the walkthrough so that one can easily access it.

**Comment by JacksonKearl** [comment]
The notification only displays for .vsix installs so far as I know, so I don't think that would work in general. (Part of the problem is notification overload so I'd rather not have a bunch of them.
