### ISSUE TITLE
Remove recent item in open recent will reset scroll to top

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119623]
Repro:

1. Open recent command
2. Scroll down
3. Click the `X` icon on one, the list will scroll to the top

This makes it too frustrating to clear out my open recent list\*. I think I created an issue on this before that was eventually closed out of scope but I can't find it, and it still bugs me.

\* I want to do this to removed things that no longer exist to make results more relevant.

**Comment by TylerLeonhardt** [comment]
dupe of https://github.com/microsoft/vscode/issues/76193

**Comment by Tyriar** [comment]
There it is 😆
