### ISSUE TITLE
[Cancel] buttom should in [Don't Save] buttom's right

### ISSUE THREAD

**Issue by zcyzcy88888** [Microsoft/vscode#1196]
In version 0.10.3, order like this:
![360 20151211200033](https://cloud.githubusercontent.com/assets/15178410/11743502/029f08cc-a043-11e5-9515-535c0de97d11.png)
This is different from other app:
![paint-save-dialog](https://cloud.githubusercontent.com/assets/15178410/11743680/5a6e5732-a044-11e5-8898-cbb09981f6fc.png)

**Comment by egamma** [comment]
fyi: @bpasero
