### ISSUE TITLE
Getting started tiles have a shadow

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119633]
![image](https://user-images.githubusercontent.com/35271042/112177888-8c5ac600-8bb6-11eb-8d3d-b17b4da23878.png)

Not sure if this is intentional or not but we don't use shadows like this anywhere. We previously tried to use this for notebook cells and the team felt like it did not fit our current aesthetic.

**Comment by JacksonKearl** [comment]
Yeah... I really quite like the shadow in some themes but it's definitely not for every one, especially dark themes. I'll make the color themeable.

**Comment by misolori** [comment]
I think the feedback from the past has been that shadows are for items that appear above other elements in space, like the editor scroll/notifications/hovers. Here I don't think the metaphor works well as it's inside of the page.

**Comment by JacksonKearl** [comment]
Made it way more subtle, not really noticeable except in the case where the tile/background color has very little contrast. Also themeable.
