### ISSUE TITLE
Pop Up Message

### ISSUE THREAD

**Issue by Erenius2** [microsoft/vscode#119693]
Issue Type: <b>Bug</b>

There is a PopUp Message that says i need to put my Password in there.
I dont know which password.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 5405U @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.41GB free)|
|Process Argv|--crash-reporter-id 59b409c4-b685-4460-95df-09b4095d9b08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sftp|lix|1.12.9
HTMLHint|mka|0.10.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30265426
vspre833:30267464
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you use the Start Extension Bisect command to try and discover if the prompt is coming from one of the extensions you have installed.
