### ISSUE TITLE
Uninstalling extension that needs reload via cli doesn't notify

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#119662]
Ref #119518

Uninstall remote-containers:

![image](https://user-images.githubusercontent.com/8586769/112194251-e6af5300-8bc5-11eb-9552-89237413e0cb.png)
Switch tabs away from extension editor then back to it.
![image](https://user-images.githubusercontent.com/8586769/112194626-4f96cb00-8bc6-11eb-980f-0ae73c837f94.png)

**Comment by sandy081** [comment]
/duplicate

#119660
