### ISSUE TITLE
Outputs are not hidden and restored properly

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#119690]
Testing #119533

Repro:
1. Open a github issues notebook
2. Make changes and run some cells
3. Open the diff editor from SCM
4. Hide outputs
🐛 => The Outputs changed elements are removed but the rendered outputs remain

![image](https://user-images.githubusercontent.com/6561887/112202797-08f99e80-8bcf-11eb-8c26-b345f1f76b54.png)

5. Repeat the steps above after switching output rendering to json 
🐛 => output cells are rendered as huge empty blanks cells
6. Re-show outputs
🐛 => output cells are STILL rendered as huge empty blanks cells

**Comment by mjbvz** [comment]
@rebornix I believe Joh disabled output persistence so is there an easy way to test this? I wasn't able to get outputs to show in the diff view with the latest insiders

**Comment by rebornix** [comment]
@mjbvz can you try 0.74 which stores output in the document?

[ms-vscode.vscode-github-issue-notebooks-0.0.74.zip](https://github.com/microsoft/vscode/files/6208318/ms-vscode.vscode-github-issue-notebooks-0.0.74.zip)

**Comment by mjbvz** [comment]
Thanks @rebornix! Verified that it works with that version
