### ISSUE TITLE
Feature request: terminal profile schema validation

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#119687]
Testing #119427

I'm wondering if there's a way to add a schema so that users can get descriptions on the various fields they can use while creating a new profile.

I also realize that the keys represent profile names, so that might make it harder to validate/provide descriptions for them. I guess the description for the keys would go under `terminal.integrated.profiles.windows` in that case, though there already is a long description for that field.

**Comment by Tyriar** [comment]
@rzhao271 this would be nice, @meganrogge looked into it a big but we're not sure how to set it up for such an object. We essentially want to enforce something like `{ [key: string]: ISourceProfile | IPathProfile }`

**Comment by aeschli** [comment]
You can use the `additionalProperties` property to specify the shape of all properties regardless of the key.
An example is the `files.exclude` setting: https://github.com/microsoft/vscode/blob/27fc3b41ed4898ee27989f26af4690838f1b196e/src/vs/workbench/contrib/files/browser/files.contribution.ts#L138

If there are constraints on the key, you can use `patternProperties`: https://github.com/microsoft/vscode/blob/771b0192f433e6cad6a06c9a62c5415ba9c3b713/src/vs/workbench/api/common/configurationExtensionPoint.ts#L99
