### ISSUE TITLE
Test icon on first line is unexpected

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119634]
Testing #119545

I'm guessing this runs the whole file, but it looks weird and probably isn't worth having imo:

![image](https://user-images.githubusercontent.com/2193314/112178192-d2b02500-8bb6-11eb-87f3-9e549849493e.png)

**Comment by Tyriar** [comment]
Also it shows up on non-test files 😕 

![image](https://user-images.githubusercontent.com/2193314/112178483-02f7c380-8bb7-11eb-9434-cadc43a7086c.png)

**Comment by connor4312** [comment]
This is one of the known issues I mentioned, but I don't have an issue for this so I'll keep it open

**Comment by Tyriar** [comment]
Oh yeah, I have a habit of starting to test before I read the whole thing so I'm going in more blind 🙂

**Comment by connor4312** [comment]
Moving into this iteration after feedback from Joh
