### ISSUE TITLE
Do not autocomplete bracket if bracket pair is already there

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#119612]
Both vscode insdiers or stable, no settings. Have the following content:
```
]
```

Type [ at the very start. Notice that it will get closed, resulting in
```
[]]
```

I would expect
```
[]
```

**Comment by alexdima** [comment]
I think this gets auto-closed to handle cases like this e.g.

Here I type `(`, `3`, `-`, `5`

https://user-images.githubusercontent.com/5047891/112163327-37867200-8bed-11eb-8295-084ba2a4eb4d.mp4

But I see how your case is also unexpected, since you start with an unbalanced closed bracket... But why do you have unbalanced closed brackets in your file? :)

**Comment by isidorn** [comment]
I see the case why it is useful.
I guess I did not really have an unbalanced closing bracket, I was just trying to break the algorithm ;)
I suggest to leave this open and if nobody else complains after some time feel free to close as designed.

**Comment by alexdima** [comment]
https://github.com/microsoft/vscode/blob/85f8ebf1687661c45fe2633bdd7f640164a20cc2/src/vs/editor/common/controller/cursorTypeOperations.ts#L633

**Comment by hediet** [comment]
What should happen here (1):
```
[
    ≪Cursor≫]
]
```
Note that the closing bracket at the cursor technically has a matching opening bracket.
Then type "[".

So this feature would only be useful when there are no surrounding pairs that could absorb any seemingly unpaired bracket.

However, this feature could surprise the user, as they might expect the situation (1) to be equivalent to:
```

    ≪Cursor≫]

```
However, in this case, `]` has no matching bracket.

What do you thing?

**Comment by alexdima** [comment]
@isidorn Given https://github.com/microsoft/vscode/issues/119612#issuecomment-833395538 , I think we should close this, it is just too much magic to figure out if a bracket is unmatched or not and it is better to have the same behavior all the time to not surprise users.

**Comment by isidorn** [comment]
Yes I agree. Thanks for looking into this though.
