### ISSUE TITLE
Add default keybindings for switching terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119653]
I didn't end up making defaults for focusNext/focusPrevious and use ctrl+shift+j/k personally, but maybe it's time to make it act more like the editor tabs when the terminal is focused since it will be much clearer what terminal is focused when tabs come (https://github.com/microsoft/vscode/issues/10546).

**Comment by NotWearingPants** [comment]
So you're suggesting <kbd>Ctrl</kbd>+<kbd>Page Up/Down</kbd> like normal tabs?
I like <kbd>Alt</kbd>+<kbd>Left/Right</kbd>.

**Comment by Tyriar** [comment]
Essentially yeah, also ctrl+1-9 and ctrl+(shift+)tab. Though I'm not sure I want to navigate my terminals via an MRU list like editors and I'm sure I'll have a hard time getting used to ctrl+tab _not_ moving the editor 🤔

**Comment by pixieaka** [comment]
@Tyriar In my opinion terminal key bindings can inherit from editor to unify user experience in all aspects. For example `ctrl + tab` When terminal section focused to switch between opens terminals and `ctrl + w` for close current terminal.

**Comment by pixieaka** [comment]
@Tyriar In my opinion terminal key bindings can inherit from editor to unify user experience in all aspects. For example `ctrl + tab` When terminal section focused to switch between opens terminals and `ctrl + w` for close current terminal.
This gonna be awesome because tabs got to terminal to unify editor experience, And this 'll be a plus to unify editor shortcuts as possible. This 'll effect the user at the end so he doesn't remember many shortcuts for editor and for terminal.

**Comment by Tyriar** [comment]
Editor shortcuts:

https://github.com/Microsoft/vscode/blob/601dec633b08a5184375b127d014967e90ae1954/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L324-L325

@pixieaka I'm not sure we want to touch the ctrl+(shift+)tab shortcuts because some people like me use it to move focus from the terminal to the editor, plus we don't have the concept of MRU terminal navigation currently. For ctrl+w I'm hesitant to add because it's a shell shortcut.

**Comment by Tyriar** [comment]
I went with:

- Linux/Windows: Ctrl+Page Up/Down
- macOS: Cmd+Shift+[/]

Mac also has cmd+alt+left/right to navigate tabs but that's already used to navigate split panes and this aligns with iterm.

**Comment by helloguille** [comment]
Hi, so ffedback:

I'm on Version: 1.56.2 and the new "next pane" default shortcut is not working on Mac or it is so complicated that is imposible to remember in some layouts like Spanish International layout.:
![Screen Shot 2021-05-25 at 17 59 52](https://user-images.githubusercontent.com/17315/119530349-34da0180-bd83-11eb-822c-57ccbe792194.png)

**Comment by helloguille** [comment]
Sorry if I'm overloading you- I just feel like this should be the natural "next terminal" shortcut, now that they are shown vertically:

CMD+ALT+DOWN
CMD+ALT+UP
