### ISSUE TITLE
Display language identifier in Language Mode drop down

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#11977]
Many user settings need to know a language's language id. Examples include files.associations, emmet.syntaxProfiles, emmet.excludeLanguages. Some settings display the language id list in suggestions (ex. files.associations) but not others (ex. emmet.syntaxProfiles).
vscode-docs issue https://github.com/Microsoft/vscode-docs/issues/572 recommends documenting the most commonly used language ids but this list will be long and need to be maintained.
We could display the language id in the Language Mode drop down list. Perhaps in parentheses:
JavaScript (javascript)
C++ (cpp)
The "languages" message on the upper right of the dropdown could be changed to something like "languages (language identifier)" or expand to a full description of language ids.
This way the list will be scoped to only languages the user has installed and always up to date. The list will also be discoverable in the product and not require the user to search our doc website

**Comment by bpasero** [comment]
Sounds like an easy enough area for a PR 👍

**Comment by mrmlnc** [comment]
> Perhaps in parentheses:
JavaScript (javascript)
C++ (cpp)

Maybe so?

![](https://cloud.githubusercontent.com/assets/7034281/18305885/2046e460-74f2-11e6-8294-897060a443be.png)

**Comment by bpasero** [comment]
@mrmlnc happy to review a PR if you wanna give it a shot 👍

**Comment by bpasero** [comment]
@gregvanl @egamma here is how it looks like after @mrmlnc PR

<img width="763" alt="screen shot 2016-09-14 at 17 46 32" src="https://cloud.githubusercontent.com/assets/900690/18519193/3f0c3fb0-7aa3-11e6-9a47-727b4c75a2c7.png">

**Comment by gregvanl** [comment]
@bpasero I think I like the parentheses and dash for Configured Language better.  I would also add some explanation in the upper right where now it just says "languages".  Maybe "languages and language identifiers" or "languages (language identifier)" if we use parentheses.

**Comment by egamma** [comment]
Another rendering would be to right align the language IDs on the right, same as we do it with the key bindings

**Comment by bpasero** [comment]
Not such a big fan of that:

<img width="677" alt="screen shot 2016-09-16 at 05 46 18" src="https://cloud.githubusercontent.com/assets/900690/18574819/ecfc8994-7bd0-11e6-8f73-631598644b18.png">

**Comment by gregvanl** [comment]
Reopening as I think we need to explain that language identifiers are in parentheses. Maybe changing the upper right text from "languages" to "languages (language identifier)"

**Comment by bpasero** [comment]
Makes sense.
