### ISSUE TITLE
Cannot install VS Extensions from Command Line Offline

### ISSUE THREAD

**Issue by excelsi** [microsoft/vscode#119755]
I try to install VSIX Extensions in an offline scenario with code command line and it stucks forever i this state:
![image](https://user-images.githubusercontent.com/8747559/112272818-f342b280-8c7c-11eb-8761-f26bb29942ba.png)

VS Code opens but nothing more happens.
I tried also other extensions the same happens.
I disabled VS Code Updates but this doesn't help here also, i think he is still trying to reach a URL for whatever reason.

I use the actual Version 1.54.3

**Comment by sandy081** [comment]
Seems the cli is not getting triggered as the user says it opens VS Code.

**Comment by bpasero** [comment]
CLI does not work when you run the `.exe` directly, only when running our scripts.

//cc @joaomoreno

**Comment by excelsi** [comment]
> CLI does not work when you run the `.exe` directly, only when running our scripts.
> 
> //cc @joaomoreno

How do i run the code CLI correctly (from CMD or Powershell)?
Thanks!
