### ISSUE TITLE
Mouse wheel events get canceled when scrolling on top of custom rendered math

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119761]
Testing #119715

Repro:

Add `$O(h)$` to a custom markdown cell and execute. Try scroll while the mouse is over the custom rendered markdown

(this was with `"notebook.experimental.useMarkdownRenderer": true`)

**Comment by mjbvz** [comment]
This no longer happens for me. Tested with both touchpad and mouse on MacOS

Let me know if you still see this

**Comment by connor4312** [comment]
Good on Windows as well
