### ISSUE TITLE
Getting started - contributed task button label should be truncated

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119765]
Testing #119543

The contributed button should have a max-width:

![image](https://user-images.githubusercontent.com/3372902/112287681-e8901980-8c8c-11eb-9630-aad69c881120.png)

**Comment by JacksonKearl** [comment]
Still a bit of screen cheese at the bottom of the button, seems to be a webkit bug, I don't think this case will be hit very often at all.
![image](https://user-images.githubusercontent.com/8586769/115941636-0e126d80-a45b-11eb-9bd0-f567831ac45a.png)
