### ISSUE TITLE
Remote indicator NPE

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119752]
https://github.com/microsoft/vscode/blob/a53ce8af3b5e410142a5b3e68d2a9048abdb6383/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L248-L248

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/7a1302a2b6c77147670cf707f992e82670ef09f8

**Comment by aeschli** [comment]
@bpasero Do yo have steps? Is our typing wrong (getWorkspace() can be undefined)?

**Comment by bpasero** [comment]
@aeschli just open an empty folder and save workspace as

**Comment by aeschli** [comment]
I can't reproduce it with your steps (Linux, Version: 1.55.0-insider, Commit: 2b66dfe0218cc18333ba92429218b33802b186bc, Date: 2021-03-24T05:15:53.792Z)

Maybe it's timing related.

Is `workspace` undefined? Or `workspace.folders` ? 
What is undefined here `workspace`

**Comment by bpasero** [comment]
@aeschli `workspace.folders[0]` can be `undefined`. The underlying problem is that TypeScript does not `strictNull` check array access...

**Comment by aeschli** [comment]
Oh, now I see, this needs brackets, `||` is stronger than `?`

Your commit changed the semantics. For workspaces it's the URI of the workspace config files which defines the host.

**Comment by bpasero** [comment]
Yeah that is why I reported this, feel free to change my fix.

**Comment by aeschli** [comment]
To verify:
Open a multi folder workspace and remove all folders in it. Check that there's no error in the dev tools from `getWorkspaceLabel`.
