### ISSUE TITLE
Focus on a sub-folder in Explorer view

### ISSUE THREAD

**Issue by bz-wow** [microsoft/vscode#119746]
Issue Type: <b>Feature Request</b>

If we open a large directory in VS code, and the dir has lots of sub folders, other dirs are noise when we only want to focus on one dir. Request to add the  feature, that only show the focused dir in Explorer view, and enable go back to the whole dir.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by nrolland** [comment]
has anybody found a way to make this less painful ? maybe some extension exists ?

**Comment by Wilsontomass** [comment]
One trick is to use "add folder to workspace" (right click in explorer window) and only add the one subfolder you want.
