### ISSUE TITLE
[Proposal] Keyboard shortcut to duplicate a line

### ISSUE THREAD

**Issue by yahiko00** [Microsoft/vscode#11975]
This would be quite convenient if we could duplicate a line with a single shortcut, since it is quite a  common practice when coding to reuse a previous line. This quite simple proposal may help to bring some productivity.

## Overview of the workflow

When the cursor is on a line, the current line, we could imagine to be able to duplicate the current line by pressing a shortcut. In _Notepad++_ it is CTRL+D. It seems this key combination is still available in VS Code so we could use it as a shortcut to duplicate lines.

Also, it could be convenient to have this command in the _Edition_ menu, maybe between the copy/paste related commands and the search/replace commands.

**Comment by camhux** [comment]
A pair of bindings exists for duplicating the cursor line, or a selection of lines, upward or downward:
```
{ "key": "shift+alt+down",        "command": "editor.action.copyLinesDownAction",
                                     "when": "editorTextFocus && !editorReadonly" },
{ "key": "shift+alt+up",          "command": "editor.action.copyLinesUpAction",
                                     "when": "editorTextFocus && !editorReadonly" },
```
This shortcut can be customized in your `keybindings.json`.

**Comment by willdzeng** [comment]
default 
{
  "command": "editor.action.copyLinesUpAction",
  "key": "ctrl+shift+alt+up",
  "when": "editorTextFocus && !editorReadonly"
}
doesn't work for me in linux for some reason, but alt+shift+up works.
