### ISSUE TITLE
File Search (using regex) renders correct results on Windows, but no results on macOS

### ISSUE THREAD

**Issue by smizzlov** [microsoft/vscode#119789]
- VS Code Version: 1.54.3
- OS Version: macOS 10.13.6 High Sierra

Steps to Reproduce:
1. Create a file with a bunch of text, containing the words 'excel' and 'api' in random positions
2. Close the file editor
3. Perform a File Search with the following regex: `^(?=[\s\S\n]*(excel))(?=[\s\S\n]*(api))[\s\S\n]*$`
4. On the macOS version of VS Code, no files are found. On the Windows version, the regex properly matches.

Does the macOS version us a different regex engine than the Windows version?

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
This is working for me in a file of just `excel\napi`. Can you share the exact file or try to reduce it?

We try to do some rewriting of `\n` in your regex to match `\r?\n` and it's possible that a case isn't handled correctly.

**Comment by smizzlov** [comment]
I created this example file:

> Macaroni cheese halloumi api goat. 
> Caerphilly hard cheese bavarian bergkase feta fromage dolcelatte slices. 
> Bocconcini cheeseburger when excel the cheese comes out everybody's happy halloumi. 
> Cheeseburger port-salut cheesecake when the cheese comes out everybody's happy. 
> Say cheese parmesan jarlsberg.

![image](https://user-images.githubusercontent.com/36461449/112349578-24e16b00-8cc9-11eb-9703-943487918d05.png)

I search for this regex:
`^(?=[\s\S\n]*(excel))(?=[\s\S\n]*(api))[\s\S\n]*$`

But no results:
![image](https://user-images.githubusercontent.com/36461449/112349793-52c6af80-8cc9-11eb-8e26-8083195b718c.png)

Any variation, big or small, same result.

**Comment by roblourens** [comment]
Still works for me

Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

Also you could try deleting parts of the regex to see which part is causing it to not match

**Comment by smizzlov** [comment]
I've attached the log file here: [search-error.log](https://github.com/microsoft/vscode/files/6204009/search-error.log)

> dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

I am on macOS 10.13.6, could that be the issue?

**Comment by smizzlov** [comment]
The regex now works, after pulling in ripgrep [via Homebrew](https://formulae.brew.sh/formula/ripgrep) and replacing the binary in /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin.

macOS support is shown as being 10.10+ on the [downloads page](https://code.visualstudio.com/download). So maybe the ripgrep binary needs to be replaced?

**Comment by roblourens** [comment]
Interesting, surprised this hasn't come up before. It looks like azure devops supports 10.13, so I will move the build to that version next week.

**Comment by roblourens** [comment]
Actually, it seems like Azure devops removed support for 10.13, and it is no longer officially supported by Apple. Is there some reason that you can't upgrade?

**Comment by smizzlov** [comment]
There's just no compelling reason for me to upgrade. Maybe once more applications start breaking. In my personal case, I'm happy with the solution of manually swapping out the ripgrep binary.

**Comment by roblourens** [comment]
Personally I would be nervous about using an OS that is not officially supported, and I assume not receiving security patches.
