### ISSUE TITLE
Need multi-monitor session support

### ISSUE THREAD

**Issue by pbower** [microsoft/vscode#119718]
Issue Type: <b>Feature Request</b>

Please add support for dragging window elements to any monitor. This is the most essential feature for a developer to have a solid workflow, and amazed it has not been added yet.

This should be the NUMBER ONE priority please!

Everything great from Spyder has been copied except this. 

Put the nail in the coffin, and let VSCode reign supreme!

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-45-generic snap

**Comment by bpasero** [comment]
> This should be the NUMBER ONE priority please!

It literally is: https://github.com/microsoft/vscode/issues/10121

**Comment by pbower** [comment]
Thanks, though out of interest, if it is #1 priority, why is something so relatively simple outstanding since 2016 that every coder needs in 2021?

Thanks
Peter

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
