### ISSUE TITLE
Focus/scroll position often jumps to the top on many operations

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119729]
Testing #119118

Drag and dropping often causes focus to be lost and the scroll position to be reset to the top.

Duplicating a cell (shift+alt+down), causes focus to be lost and the scroll position to be reset to the top -- so it is really hard to see where new items are being inserted

Join with previous cell seems to do the same.

**Comment by rebornix** [comment]
This is a duplicate of https://github.com/microsoft/vscode/issues/119767 , which has more details, let's merge into that.
