### ISSUE TITLE
Support a more traditional style tutorial in getting started

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119709]
I'd like to teach my extension using the getting started walkthrough contribution but I see the following problems:

- I'm forced to have a button - I think this should be optional such that just opening the item is enough to check it off
- The right side only supports a single image, if this was markdown support with images+scrolling then I could inline my documentation into the tool

With the above I might be able to get rid of the docs in the readme and instead point them to the show docs command which would open the getting started for my extension.

**Comment by Tyriar** [comment]
Here's an example of the type of thing I'd be able to move to getting started:

![image](https://user-images.githubusercontent.com/2193314/112219262-fa68b280-8be1-11eb-88e3-957d13cfbc7e.png)

**Comment by JacksonKearl** [comment]
Rough sketch hacked together from extension editor and getting started editor:

![image](https://user-images.githubusercontent.com/8586769/112220769-db6b2000-8be3-11eb-92a7-57db81157eae.png)

**Comment by digitarald** [comment]
@Tyriar the screenshot reminds me of content that is traditionally in end user documentation. I'd be curious what you imagine the biggest pain points of new Luna users are.

The two thoughts of problems/solutions here:
- Ability to link to longer longer docs, guides and tutorials. Getting Started links to video tutorials for VS Code, which gets used a lot. It would be interesting to experiment with that content in VS Code (vs opening a browser), so panels and features can link to it.
- Allow tasks to open a search in Command Palette. Allows users explore specific groups of commands.
- Ability to trigger UI overlays/tours. If UI elements could declare their own help meta data, an approach like's Edge's [help overlay](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/whats-new/2021/02/devtools#learn-about-devtools-with-informative-tooltips) could guide users through more complex UI state. Not sure how useful that is in VS Code when a lot of functionality is keyboard-driven.

**Comment by Tyriar** [comment]
@digitarald some people aren't very familiar with image editing, so I'd like the basics to be covered in tool. I don't have a website for the tool (right now at least), and I don't think the readme is the place for this info dump as right now it's just way too much information when I think it would be best to just cover the high level basics of what it's capable of, then drill in a little more on the _how_ after install.

The actual content I'd imagine would be:

- Interface overview (this could be just an image)
- Image editing basics
- Dealing with the selection
- Using layers and blend modes

The last topic could be a huge doc, diving into what all the blend modes are and what they're used for. But I think the right amount of content here would be a little bit of text explaining blend modes are available to apply to layers, and then a small image of maybe the bg, fg and then what it looks like blended together with a particular blend mode.

> Ability to trigger UI overlays/tours. If UI elements could declare their own help meta data, an approach like's Edge's help overlay could guide users through more complex UI state. Not sure how useful that is in VS Code when a lot of functionality is keyboard-driven.

This is essentially what my interface overview would be, similar to VS Code's existing one. It might be hard to declaring such metadata and get it to work within custom editors.

**Comment by JacksonKearl** [comment]
Yes, links to markdown files would also help to not have massive package.json files as we don't want to incur the cost of parsing the data until its needed, we do something similar for snippets.

**Comment by Tyriar** [comment]
Queued a product build so I can hopefully test this out over the weekend.
