### ISSUE TITLE
Settings feature : By default, don't keep file previews or git merge preview as opened tabs

### ISSUE THREAD

**Issue by zipang** [microsoft/vscode#119726]
Issue Type: <b>Feature Request</b>

This was a great (sublime) feature of Sublime Text Editor : when navigating files in the file explorer panel on the left, when you click on a file you can view its content. When you click on another file, this preview is replaced by the new file selected. 
But, to really open a _persistent_ file editor tab, you have to DOUBLE CLICK on it inside the file explorer. 
This eliminates ALL the clutter of multiple editor tabs that you don't really want to work with.

The same should be said about the editor tabs that are automaticaly opened when you preview a git comparaison of the files you want to commit : once it's done you don't want to have all these (Working Trees) tabs opened and have to close them one by one.

This should be be in the settings (i've looked for it, and maybe it's already here) : but where is it ?? 
By default, _all these previews should not remain as opened tabs_.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-67-generic

**Comment by gjsjohnmurray** [comment]
Have you set `"workbench.editor.enablePreview": false`? The default is `true`.

**Comment by zipang** [comment]
Thanks a lot !
Setting  `"workbench.editor.enablePreview": true` solves the issue !
But i don't know why it was that way.. Maybe loading a preset !
This issue can be closed as the setting exists !
