### ISSUE TITLE
Custom markdown renderer: show cell background only when there is muti selection

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#119704]
Issue Type: <b>Bug</b>

* Disable custom markdown renderer
  * Single click on a cell, no background color, only borders
  * Shift+arrow down, they have both bg color and borders
* Enable custom markdown renderer
  * Single click on a markdown cell, it has bg color

VS Code version: Code - Insiders 1.55.0-insider (a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, 2021-03-23T05:13:33.822Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.08GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoccf:30278406
vsc_aa:30263845
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
This was a simple regression. I removed the check because I didn't realize the expected behavior
