### ISSUE TITLE
Sash drag handle can appear over the top of the cell menu

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119732]
Testing #119118

![image](https://user-images.githubusercontent.com/641685/112229508-7fb38d80-8c09-11eb-843a-85bcff94c9a7.png)

**Comment by rebornix** [comment]
cc @sbatten , it's weird that when you click on the sash, the context menu doesn't hide.

**Comment by sbatten** [comment]
not sure how the sash elements are positioned and rendered but for context from the menu side, that menu is a child of the ... button and in a shadow dom element.

**Comment by rebornix** [comment]
@sbatten shouldn't the context menu dismiss when the focus leaves?

**Comment by joaomoreno** [comment]
@sbatten @rebornix The real question is why isn't the entire workbench blocked from pointer events when the notebook `...` menu comes up, the same way it is when the context menu or editor toolbar `...` menus are?

**Comment by joaomoreno** [comment]
From what I can tell all menus use the `monaco-menu-container` global DOM element, while that one uses something more local. 🤔

**Comment by joaomoreno** [comment]
Here we go:

https://github.com/microsoft/vscode/blob/d5abce78ab70e899adc90433b12aac3864a9502d/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L716-L716

**Comment by joaomoreno** [comment]
@sbatten I think when menus are rendered in shadow DOM we still need some work to prevent the workbench from being interacted with. Right now it appears as most of it is actually prevented, but not sashes.

**Comment by sbatten** [comment]
The sash has a z-index of 35 and the notebook cell toolbar has a z-index of 30. The containing element needs to add to its z-index of the sash needs to move down. @rebornix @joaomoreno

**Comment by rebornix** [comment]
A bit off topic, I might want to write a CSS parser for VS Code to provide decorations/hints of all z-index used in the workbench when one decides to update `z-index`.

**Comment by joaomoreno** [comment]
I would raise the notebook cell toolbar z-index.... simply because it interacts with less elements than the sash does. 🤔

**Comment by rebornix** [comment]
cool, 36 it is.
