### ISSUE TITLE
Should "openInBackground" for Getting Started work when extension isn't installed from vsix?

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#119707]
Testing #119543

The primary walkthrough opens successfully for me with `"workbench.welcomePage.experimental.extensionContributions": "open"`. For instance, when I have the Getting Started editor already open and `settings.json` as the focused tab:

![image](https://user-images.githubusercontent.com/25310137/112216072-54677900-8bde-11eb-897f-2b142a8ba300.png)

I'm also able to open it to the side with the Getting Started page already open, `settings.json` in focus, and `"workbench.welcomePage.experimental.extensionContributions": "openToSide"` set:

![image](https://user-images.githubusercontent.com/25310137/112215714-ecb12e00-8bdd-11eb-9878-be8714be5e77.png)

However, when I have `"workbench.welcomePage.experimental.extensionContributions": "openInBackground"` set, when I install https://github.com/JacksonKearl/md-to-html/ from the Extensions viewlet, the walkthrough opens up and takes the primary view. I thought it would've opened a tab but that tab wouldn't have taken over the focus.

![recording (8)](https://user-images.githubusercontent.com/25310137/112216896-46febe80-8bdf-11eb-96fa-0a863be1547f.gif)

I tried uninstalling the extension, reloading the window, and installing from a vsix instead, and now getting started loaded in the background: 

![image](https://user-images.githubusercontent.com/25310137/112217308-b674ae00-8bdf-11eb-8e86-05dd0e7edf65.png)

Is this intended? I would have thought "openInBackground" would apply to any method of extension installation, not just from vsix (especially since I'd anticipate more folks would install from the Extensions viewlet than vsix).

**Comment by JacksonKearl** [comment]
that's weird, I think because installing from the viewlet opens the extension editor for a flash.
