### ISSUE TITLE
chromium: drag and drop in the wayland

### ISSUE THREAD

**Issue by hiukky** [microsoft/vscode#119799]
- VS Code Version: 1.54.3
- OS Version: Arch Linux x64 
- Kernel Version: 5.11.8

Steps to Reproduce:

1. Open Code and load project.
2. Drag a file and place it with other open files.

Does this issue occur when all extensions are disabled: Yes

Description:

I recently opened a problem in Bugs Chromium regarding the Drag and Drop api. For more details follow:

https://bugs.chromium.org/p/chromium/issues/detail?id=1164766

This seems to be a problem with the Wayland graphics server and Chromium itself. This was tested with Chrome stable and Firefox.

In Chrome or any other browser that uses Chromium, there were flaws, but not in Firefox.

Running Chrome enabling Ozone works well:

google-chrome-stable -enable-features = UseOzonePlatform -ozone-platform = wayland

Now in the version of Code 1.54.3 I found the same problem, and debugging all the errors in relation to Chrome as VSCode boil down to this line:

[8518: 0324 / 115202.621701: ERROR: gl_surface_presentation_helper.cc (259)] GetVSyncParametersIfAvailable () failed for 3 times!

As I saw some other issues related to Drag Drop in this version I decided to report, maybe with a few more details. In case the problem does not make a direct reference to the VS Code, I will be continuing with it in the chromium bug report and maybe reporting this in Wayland, since I am not sure which part of the solution is responsible for the solution.

Version:
![image](https://user-images.githubusercontent.com/26740246/112336202-a4584580-8c9b-11eb-9c9d-4fae7291a787.png)

Reproduction:
https://user-images.githubusercontent.com/26740246/112338551-a4594500-8c9d-11eb-95f5-a7e27cb15ee0.mp4

**Comment by deepak1556** [comment]
Wayland support is not yet available in latest stable vscode, it is currently tracked in https://github.com/microsoft/vscode/issues/109176. Merging to it.
