### ISSUE TITLE
Need a margin on the right edge so cells don't overlap the scroll bar

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119717]
Testing #119118

![image](https://user-images.githubusercontent.com/641685/112225487-437d2e80-8c03-11eb-8bc4-8332fac04aa3.png)

**Comment by rebornix** [comment]
It seems more noticeable and an issue after we introduced the vertical border around the cell. @misolori maybe we should shrink the cell width a bit?

**Comment by misolori** [comment]
This is by design. The editor works the same way with the current line indicator & debugging with the current line highlighted. 

Shrinking the width will introduce new issues with the cells looking odd.
