### ISSUE TITLE
Getting started - contributed task title should be truncated when collapsed

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#119766]
Testing #119543

We should probably limit the title to at most two rows when the task is collapsed
![image](https://user-images.githubusercontent.com/3372902/112287954-2d1bb500-8c8d-11eb-8430-47863e5dcf0d.png)

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/115941629-0357d880-a45b-11eb-983a-3d4aa6aa4ada.png)

**Comment by lszomoru** [comment]
A long title still seems to push the contents outside. Am I missing something?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/3372902/116552811-ba3fd280-a8f9-11eb-81d4-ab4e1ca3c254.png">

**Comment by JacksonKearl** [comment]
Hm yes, that seems to be a browser bug where the height of elements using the `-webkit-line-clamp` isn't measured properly initially (if I delay the height read by 10ms everything works, but it can cause desynchronization). I thought it only affected the button being long, seems like the title gets broken too. I may have to just implement multiline ellipses myself, shame it's not possible in standard css.
