### ISSUE TITLE
Stray console processes at 100% of a core

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#119747]
I noticed there were stray two console processes both eating 100% of a core (24 vcore system)

![](https://memes.peet.io/img/21-03-6ef67b36-47f7-44f4-ab63-4dfd1284e12b.png)

Killing these didn't directly affect my running terminals in VS Code, so I'm guessing they were leaked at some point today (perhaps related to https://github.com/microsoft/vscode/issues/119711?). A few minutes after killing them I did get the "The connection to the terminal's pty host process is unresponsive" error, but that pops up somewhat frequently so I'm not sure it's directly related.

**Comment by Tyriar** [comment]
If it's just conhost hanging around and not the shell as well I think you likely hit https://github.com/microsoft/vscode/issues/71966
