### ISSUE TITLE
Short flicker/lack of progress when showing test explorer for the first time

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119754]
Testing #119545

* open vscode's folder
* reload window
* open test explorer

For a split second I see the green "getting started" button, then comes tests. It seems that there is no "Loading..." indication and that the default content shows to eagerly, eg. it could know that discovery is happening and therefore show something else

https://user-images.githubusercontent.com/1794099/112272158-1ae54b00-8c7c-11eb-9cde-6f8be8595025.mov

**Comment by jrieken** [comment]
I also see this when revealing the test explorer after a short while of inactivity

**Comment by connor4312** [comment]
Merging into https://github.com/microsoft/vscode/issues/119675
