### ISSUE TITLE
Scrolling in notebooks feels slow and non-native

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119764]
Testing #119715

Open `my-work.github-issues` and scroll up and down on Windows, I observe:

- Much slower framerate than in the editor.
- Sometimes the scroll bar jumps much more than it should - this seems very random and I can't figure out what causes it. It also seems to happen much more when scrolling towards the top and bottom edges of the notebook.

I tried to take a webview perf profile but it didn't reveal anything useful, and when I take a non-webview perf profile the webview freezes (I've created an issue on this in the past).

**Comment by rebornix** [comment]
> Sometimes the scroll bar jumps much more than it should

Do you have outputs in any cell?

**Comment by Tyriar** [comment]
It happens without output

**Comment by Tyriar** [comment]
Mac profile:

<img width="637" alt="Screen Shot 2021-04-01 at 4 57 48 AM" src="https://user-images.githubusercontent.com/2193314/113290683-d9215980-92a6-11eb-9635-f7f7dcb86275.png">

[Profile-20210401T045824.json.zip](https://github.com/microsoft/vscode/files/6243295/Profile-20210401T045824.json.zip)

**Comment by rebornix** [comment]
this is the same as https://github.com/microsoft/vscode/issues/126880 .
