### ISSUE TITLE
model name and hover

### ISSUE THREAD

**Issue by y912765390** [microsoft/vscode#119741]
For example, if I use a third-party library xterm-addon-web-Links. Xterm-addon-web-Links. D.ts, it says declare module 'xterm-addon-web-Links' ****, but when I float it, it prompts the path instead of' xterm-addon-web-Links'

**Comment by chrmarti** [comment]
Could you attach a screenshot?

**Comment by y912765390** [comment]
![微信图片_20210330165333](https://user-images.githubusercontent.com/34642268/112963115-a3328700-9179-11eb-8fa4-0351225e8afd.png)
I was wondering how to do that and the path of the file is not the same as the name that was introduced

**Comment by mjbvz** [comment]
Please fill in the issue template and share steps to reproduce the issue 

/needsMoreInfo
