### ISSUE TITLE
[Getting Started] Reaching the end of a walkthrough is lackluster

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#119722]
Follow up from #119496.

Finishing a getting started walkthrough (or all of them) does neither celebrate the occasion nor engage the user to continue their journey. It's a missed opportunity to raise the energy and tie in the next walkthrough.

Ideas:
- Engaging copy
- Pitch next walkthrough
- Bring back to Welcome page

**Comment by chrisdias** [comment]
![image](https://user-images.githubusercontent.com/1487073/112703472-491d8300-8e54-11eb-801c-d62cae9b69f4.png)

**Comment by misolori** [comment]
Here's a quick example of something we can do:
- Show an "All Done" screen
- Use the next item's description as a way to draw the user into continuing
- Removing the completed item from the list

![CleanShot 2021-04-08 at 10 34 55](https://user-images.githubusercontent.com/35271042/114071767-5c6a1e80-9856-11eb-981c-eb28c583628c.gif)

**Comment by digitarald** [comment]
As Eric pointed out – not all walkthrough's tie into the next. The built-in will go from setup to fundamentals to tips; but even there the last one will probably go back to the index. So still celebrating, but a version that just sends the user back to Welcome page.

UI-wise, I have not seen many other places with emojis. Would codicon feel more native but potentially less whimsical?

(Also, confetti?)

**Comment by misolori** [comment]
Based on discussions from today's sync, we discussed showing additional actions below the list of actions that would allow the user to mark all items as "Done" and then go back to the welcome screen, as well as an action to go to the next item:

![image](https://user-images.githubusercontent.com/35271042/118180134-0e16e500-b3eb-11eb-867d-9c1159b32c27.png)

And as soon as someone 1) finished all the items in the list OR 2) hits "All Done", the item should be removed the main Getting Started list.

**Comment by JacksonKearl** [comment]
Implemented as described above

**Comment by andreamah** [comment]
Not sure if this is intentional, but clicking `More` after checking off all of the items causes the item to stay on the main page. Only clicking `Mark Done` removes it. According to the comment above, seems like checking all of the items should remove the item?

> And as soon as someone 1) finished all the items in the list OR 2) hits "All Done", the item should be removed the main Getting Started list.

[![Image from Gyazo](https://i.gyazo.com/2771742639929eb63ed8faa1148ad7c4.gif)](https://gyazo.com/2771742639929eb63ed8faa1148ad7c4)

**Comment by misolori** [comment]
> According to the comment above, seems like checking all of the items should remove the item?

Yes, that was the original design so maybe this was missed @JacksonKearl?

**Comment by digitarald** [comment]
It makes sense to hide completed items as _Mark Done_ does the same.

<hr>

Tangential, one exploration would be to make the completed items more todo-list-like (like MS Todo "Completed items", as just making them disappear does not address the original intent of this specific issue – to make the end of a walkthrough more interesting.

<img src=https://user-images.githubusercontent.com/8599/120528631-87717a00-c390-11eb-8b58-3a123720669d.png width=500>

**Comment by alexr00** [comment]
Verified that:
- There's an "all done" option and that it does what I expect.
- There's a next section option and it does what I expect.
- When I'm done with a section it goes back to the main page.

However, finishing everything is still pretty lackluster:

![image](https://user-images.githubusercontent.com/38270282/120795245-862f8100-c539-11eb-805b-50c5affc35a7.png)
