### ISSUE TITLE
VS Code AWS ESP32 FreeRTOS-ESP-IDF development 

### ISSUE THREAD

**Issue by Yoimer** [microsoft/vscode#119791]
Steps to compile, build. flash and monitor AWS ESP32 FreeRTOS on ESP32 boards.
How can I pass commands like these from VSCODE?:
(Let's say I am on `FreeRTOS` folder)
`cmake -DVENDOR=espressif -DBOARD=esp32_devkitc -DCOMPILER=xtensa-esp32 -GNinja -S . -B demos/ota/build`
`cmake --build demos/ota/build --target flash`
`python %IDF_PATH%/tools/idf.py monitor -p COM4 -B demos/ota/build`

From this link https://www.freertos.org/2021/01/using-visual-studio-code-for-freertos-development.html, it is not quite clear yet.

I want to use VSCODE as my IDE for AWS FreeRTOS ESP32 projects, including debugging capabilities

Thanks in advance.

**Comment by Yoimer** [comment]
I made some progress on this. I commented here. Two more questions around and that's it.
https://github.com/aws/amazon-freertos/issues/3002#issuecomment-810437254

**Comment by Tyriar** [comment]
I think you'd be best to ask this over there
