### ISSUE TITLE
Support dark theme in Gnome

### ISSUE THREAD

**Issue by andreyorst** [Microsoft/vscode#11979]
- VSCode Version: 1.5
- OS Version: Linux

I do use light theme on my linux distribution, but in VScode i prefer standard dark theme for editor, so i desired to try to change a gtk theme for single window as i do often with several applications modifying their launchers and .desktop files, and had no success. As i figured out VScode doesn't use gtk for window decorations, so i tried xprop to change theme variant to dark. What i got is that window decoration changed to dark, but menu is still using old light style.

It would be great if VScode will start to use CSD (client side decorations) like in most native and not native gnome apps, so i request this feature too

Steps to Reproduce:
0. Use light gtk theme, that support dark variant, like Arc-GTK
1. Type in terminal: xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT "dark"
2. Click VScode window
3. Notice that decorations turned to dark, but menu is still light
3. Cry.

**Comment by jhasse** [comment]
This would be a lot easier to fix when https://bugs.chromium.org/p/chromium/issues/detail?id=79722 is implemented. Especially client side decorations.

**Comment by bpasero** [comment]
@andreyorst does it help if you add the following option to the window creation in https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/window.ts#L162

`darkTheme: true`

See here how to build and run out of sources: https://github.com/Microsoft/vscode/wiki/How-to-Contribute

**Comment by cra0zy** [comment]
https://github.com/electron/electron/issues/2927

**Comment by Tyriar** [comment]
Chrome v59 uses gtk3 which hits the stable channel in June https://bugs.chromium.org/p/chromium/issues/detail?id=79722#c110 https://www.chromium.org/developers/calendar

**Comment by MattSturgeon** [comment]
Any update? It seems all the upstream blockers are gone now, but I can still reproduce this issue:

![image](https://user-images.githubusercontent.com/5046562/28543015-49a4c17c-70b6-11e7-801a-1e5fe6821456.png)

This isn't so bad with `"window.menuBarVisibility": "toggle"`, but it is still an issue.

**Comment by cra0zy** [comment]
@MattSturgeon Wrong, #9946

**Comment by Paviluf** [comment]
This one https://github.com/Microsoft/vscode/issues/30031 is the same kind of request. It will allow us to use a dark variant without the hacky xprop way.

**Comment by cra0zy** [comment]
Starting with GNOME 3.26 the "global dark theme" feature will get removed.

**Comment by Paviluf** [comment]
That's not a problem :
https://jeremy.bicha.net/2017/08/29/gnome-tweaks-3-25-91/#comment-384

**Comment by cra0zy** [comment]
I did mention it because of that, #30031 and this request are different, this can be closed while #30031 should be the one left open.

**Comment by MattSturgeon** [comment]
Surely GLOBAL Dark Theme being removed has no impact on either issue. You
can still set Dark Theme on a per-app basis.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16363

**Comment by jhasse** [comment]
> Surely GLOBAL Dark Theme being removed has no impact on either issue. You can still set Dark Theme on a per-app basis.

Even a global dark theme is still supported, simply by selecting a dark theme.
