### ISSUE TITLE
Execution count looks odd that it is always visible

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119720]
Testing #119118

Why is the execution count always visible? While the play button isn't?

![image](https://user-images.githubusercontent.com/641685/112226063-0f563d80-8c04-11eb-95ec-f93b27fda492.png)

**Comment by roblourens** [comment]
This is presumably something that you would want to be able to read across the document easily. Just following Jupyter's lead here, I think.

**Comment by tanhakabir** [comment]
Closing this since there hasn't been any more discussion here and the empty Execution Order is also in Jupyter Classic and Colab
