### ISSUE TITLE
Collapsed cell input doesn't look great

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119776]
Testing #119715

Not sure how to improve it, maybe centering the line would be a minor improvement? It just doesn't look like it fits to me

![image](https://user-images.githubusercontent.com/2193314/112290261-49e3c880-8c4c-11eb-88e4-28a310975f8e.png)

**Comment by misolori** [comment]
We've had this design for a few months now and haven't seen much complaints about it but will leave it open for others to chime in.

**Comment by rebornix** [comment]
Did we ever consider rendering the first line of the model in collapse state? We found this annoying in interactive window as expanded input in the iw seems too long but the collapsed state doesn't really give any hint what code users write.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/876920/124368791-a7a78980-dc19-11eb-91c7-6a83bb0592b9.png">

**Comment by claudiaregio** [comment]
+1 to @rebornix's suggestion -- I've heard the solution of displaying the first line of code requested a few times from customers

**Comment by misolori** [comment]
We did explore showing the first line originally but don't remember why we didn't go with that. We should at least show the ellipsis (similar to code folding).

**Comment by joyceerhl** [comment]
Got user feedback asking for this in the interactive window: https://github.com/microsoft/vscode-jupyter/issues/6474#issuecomment-875862461

**Comment by StevenLi-DS** [comment]
Does icon this really necessary. You could just double click to expand a cell anyway. It looks ugly.
![image](https://user-images.githubusercontent.com/33796896/125177702-fe7a0980-e1ab-11eb-91c9-0bd14f8b7ce8.png)

**Comment by roblourens** [comment]
It's possible @rebornix, we already do something like this for DND by pulling the HTML out of the editor, so you get colorization without worrying about having a live editor with just the one line of text

**Comment by rebornix** [comment]
Yup, in the screenshot I showed above is from my local branch, which renders only the first line instead of rendering an editor. Will try this.

**Comment by rebornix** [comment]
Based on the feedback we received from offline discussions, I pushed the preview of the first line of cell to main.

![image](https://user-images.githubusercontent.com/876920/125995854-a4c24e01-9074-4390-a91b-12b41401cbff.png)


Instead of showing the collapse icon, we may still want to show the run button for it (or just hide it) but it's more work (require some decent amount of refactoring) so I'll do that in a follow up commit.

**Comment by StevenLi-DS** [comment]
@rebornix This does seem nice, but I wonder if it is possible to just let user decide how many lines they wanna show up. PLS do hide the collapse icon or show the run button as the `...` already indicates it's collapsed.

**Comment by rebornix** [comment]
@StevenLi-DS thanks for the feedback. I can see the value of allowing users to control the amount of visible lines, considering it depends a lot on the coding style. I'll suggest we start with one line and see how it works.

> PLS do hide the collapse icon or show the run button as the ... already indicates it's collapsed

Yup, working on it now.

**Comment by rebornix** [comment]
We now use `...` as the universal icon for expanding code/output. Single click on the icon will expand the area and double click on the collapse preview will also expand.

![image](https://user-images.githubusercontent.com/876920/128787889-6dcd11ec-1645-49b4-b987-b31a48e7a132.png)
