### ISSUE TITLE
Unable to update VS code on Windows - 2021

### ISSUE THREAD

**Issue by tjohnson4** [microsoft/vscode#119743]
- VS Code Version: 1.54.2
- OS Version: Windows 10 Home - 10.0.19043

Steps to Reproduce:

1. Goto Help 
2. Select `Check for Updates...`
3. Select `Update now` on popup in lower right corner 

Result 
2 exceptions are raised in system alerts 
![exception 1](https://user-images.githubusercontent.com/1960683/112254684-391c5e00-8c1e-11eb-93b9-b23bbd5bb5d7.png)
![exception 2](https://user-images.githubusercontent.com/1960683/112254689-3b7eb800-8c1e-11eb-8f89-ce01ffececb4.png)
![vs code version](https://user-images.githubusercontent.com/1960683/112254693-40436c00-8c1e-11eb-8afe-85799aa46b68.png)
[vscode-inno-updater-1616558867.log](https://github.com/microsoft/vscode/files/6194391/vscode-inno-updater-1616558867.log)

log with extensions off 
[vscode-inno-updater-1616559655.log](https://github.com/microsoft/vscode/files/6194396/vscode-inno-updater-1616559655.log)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
It seems like Eclipse is writing some files into VS Code's installation directory. We don't own those files. I suggest you file an issue on them instead.
