### ISSUE TITLE
Only showing Ubuntu WSL terminal profile

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#119731]
Issue Type: <b>Bug</b>

Environment details
I have pwsh-preview installed as my default shell via Microsoft Store
I have WSL installed as well
I have git installed via scoop

VS Code version: Code - Insiders 1.55.0-insider (a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, 2021-03-23T05:15:17.057Z)
OS version: Windows_NT x64 10.0.19042

**Comment by sbatten** [comment]
Select default profile only shows this option:
![image](https://user-images.githubusercontent.com/6561887/112229665-a3b6a500-8bf0-11eb-98dc-2ff605068f5d.png)

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/112229722-bcbf5600-8bf0-11eb-89c5-e1552f086ba2.png)
