### ISSUE TITLE
macOS: custom title can be zoomed in

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119757]
I am always running with zoom level `1` and noticed that the custom title seems to zoom as well:

![image](https://user-images.githubusercontent.com/900690/112280670-8a136d00-8c85-11eb-80cc-ea18d9299bb4.png)

This is a native macOS app with native title on the right and VSCode on the left.

When I zoom out (to `0`) once and then zoom back in, the title is proper:

![image](https://user-images.githubusercontent.com/900690/112280738-9ef00080-8c85-11eb-817f-3e4ca216aea1.png)

**Comment by sbatten** [comment]
I could not repro. Please take a look at your settings and see if there are any related settings that might be contributing to this or if you have a set of steps that reliably reproduces the issue.

**Comment by bpasero** [comment]
Let's give this April to look into steps to reproduce from my end and otherwise close. The only thing I know for sure is that this is not a recent regression.

**Comment by bpasero** [comment]
I think this was actually caused by an issue I fixed with https://github.com/microsoft/vscode/commit/242bea8c8f03a6ea8e42d29cec62b1cb9698e70c just now.

**Comment by bpasero** [comment]
I have not seen it since.
