### ISSUE TITLE
Internel terminal inputs capital letter when using Simplified Chinese + CapsLock

### ISSUE THREAD

**Issue by Eric217** [microsoft/vscode#119748]
Issue Type: <b>Bug</b>

Using Simplified Chinese as input source
Toggle CapsLock (on)
Editor and this issue reporter will input lowercase letters, while internel terminal capital 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.0.0

**Comment by Eric217** [comment]
not fixed in Version: 1.55.0-insider
<img width="376" alt="Screen Shot 2021-04-08 at 13 09 38" src="https://user-images.githubusercontent.com/27217414/113971624-b1fcf600-986b-11eb-80ca-8f6df18cd75c.png">

**Comment by Eric217** [comment]
> > I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
> 
> not fixed in Version: 1.55.0-insider
> <img alt="Screen Shot 2021-04-08 at 13 09 38" width="376" src="https://user-images.githubusercontent.com/27217414/113971624-b1fcf600-986b-11eb-80ca-8f6df18cd75c.png">

using Simplified-Chinese, with CapsLock on, behave diff 👆

**Comment by gqbre** [comment]
still not fix in 1.56.2 more than 2 years
