### ISSUE TITLE
Counter incrementing by 2

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#119763]
Testing #119715

The counter on the left is missing a tooltip (what does it indicate?). Also: It increments by 2 whenever I execute the cell, not sure if that can be correct.
![Mar-24-2021 10-32-14](https://user-images.githubusercontent.com/9205389/112287302-8505ec00-8c8c-11eb-89e0-e0369fb9cb07.gif)

**Comment by roblourens** [comment]
That's by design, it's also executing the cell that defines those constants. The second time this has been mentioned though https://github.com/microsoft/vscode/issues/119721
