### ISSUE TITLE
Drag and drop of expanded headers doesn't drag the children too

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#119716]
Testing #119118

I found it unexpected that when dragging a header with children, that its children didn't move along with the header. I think they be should dragged together, as they feel like a unit, and that is the behavior when they are collapsed.

**Comment by roblourens** [comment]
I disagree. A header cell is still an independent single cell, and I will want to be able to rearrange it on its own, at least that is my own mental model.
