### ISSUE TITLE
Selection border has high priority than focus border

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#119705]
Issue Type: <b>Bug</b>

* Open `endgame.github-issues`
* Set customized colors

```
            "notebook.cellBorderColor": "#899ba636",
            "notebook.cellInsertionIndicator": "#83afe5",
            "notebook.cellStatusBarItemHoverBackground": "#ffffff26",
            "notebookStatusErrorIcon.foreground": "#df8c8c",
            "notebookStatusRunningIcon.foreground": "#cccccc",
            "notebookStatusSuccessIcon.foreground": "#a8ce93",
            "notebook.focusedCellBorder": "#83afe5",
            "notebook.focusedEditorBorder": "#83afe5",
            "notebook.inactiveFocusedCellBorder": "#83afe599",
            "notebook.selectedCellBorder": "#a8ce93",
            "notebook.selectedCellBackground": "#6a7d89"
```

* Click on the cell container, it shows the focus border
  
<img width="771" alt="image" src="https://user-images.githubusercontent.com/876920/112213211-13219a00-8bdb-11eb-8b72-da4a5dcf8d09.png">

* Click on the cell editor, it shows the selection border

<img width="766" alt="image" src="https://user-images.githubusercontent.com/876920/112213240-1a48a800-8bdb-11eb-911d-952b506c83af.png">

VS Code version: Code - Insiders 1.55.0-insider (a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e, 2021-03-23T05:13:33.822Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoccf:30278406
vsc_aa:30263845
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by misolori** [comment]
This is because your selection cell color is green:

`"notebook.selectedCellBorder": "#a8ce93",`

This is the color of the cell when it's selected and the focus is in the editor. My suggestions is to use a less strong color here like:

`"notebook.selectedCellBorder": "#899ba636",`

![image](https://user-images.githubusercontent.com/35271042/112364050-5f301580-8c93-11eb-8375-8690e2479c3e.png)

**Comment by misolori** [comment]
Will close this as `as-designed` but feel free to re-open if you disagree.
