### ISSUE TITLE
Disable auto open file when moving that to vscode explorer

### ISSUE THREAD

**Issue by elch10** [microsoft/vscode#119768]
Periodically I move files from OS Explorer to vscode explorer. Sometimes I connect using Remote-SSH and also moving files to vscode explorer, as it easy way to copy files from local to server I connected to. 

After copying files vscode automatically tries to open that files, even if they binary/archive etc. If file is large then vscode long time tries process that. If I connected via ssh vscode seems to send file back to open in new tab. If I close tab beforehand then vscode "hangs up" and tries to reconnect endlessly with password request (to SSH host).

**Comment by isidorn** [comment]
This is fixed in latest vscode
