### ISSUE TITLE
Should filter out markdown cells from full notebook execute requests

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#119734]
- "Run all cells"
- The kernel gets one execute request for the full notebook
- It should get ranges that do not include markdown cells

**Comment by roblourens** [comment]
Executing markdown cells was causing issues in the github issues notebook

**Comment by mjbvz** [comment]
@roblourens To verify, I debugged the GitHub issues notebook extension and placed a breakpoint in `executeCellsRequest`. After executing `run all cells`, I don't see any markdown cells being included in the list of ranges

Let me know if these verification steps are incorrect

**Comment by roblourens** [comment]
Perfect, thanks!
