### ISSUE TITLE
Editor hover: markdown links should use their own custom scheme

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#119786]
Steps to Reproduce:

0. Set `"enable-browser-code-loading": "bypassHeatCheck"` in `~/argv.json` and restart
1. Clone https://github.com/svsool/vscode-memo
2. `yarn`
3. comment out the line that reads `Image preview is currently not supported`
4. Run 
5. open a markdown document with a reference to a PNG in the workspace
6. retype it as `memo` notation (e.g. `[[images/1_54/macOS-universal-download.png]]`)
7. hover over it

=> 🐛 it looks like the resulting image tag uses `file` protocol and not `vscode-file` protocol:

![image](https://user-images.githubusercontent.com/900690/112303246-5c85ee00-8c9c-11eb-8465-20ede651f85b.png)

We need to make sure to use the `FileAccess` utility to properly convert to a URL that the browser can handle.

Slightly related: @deepak1556 expressed some interest that the generated HTML from markdown uses a custom scheme so that we can distinguish markdown content from our core content. I had to push https://github.com/microsoft/vscode/commit/a34297a60858cf43f4bc92aae48b72e3ea37754a now as a workaround.

**Comment by deepak1556** [comment]
To clarify, I am proposing to keep `vscode-file` only deal with resources for the core, we create a separate scheme (ex: `vscode-hover`) to load resources for the hover html. That way we can keep the restrictions around `vscode-file` stricter and additionally there is no added cost to having multiple schemes in an app, offering cleaner separation for resource loading.

**Comment by bpasero** [comment]
After looking a bit closer into what the extension does, I realised that the extension is actually returning `file://` URIs as hover contents from here:

https://github.com/svsool/vscode-memo/blob/5dc4fe035b7c4474d29c6cd24afd33f5e13a1a6e/src/features/ReferenceHoverProvider.ts#L56

As such, we probably just take the contents as is and rely on the fact that we currently still support to embedd `file` URIs for rendering. 

But going forward this will not be possible anymore, because once we set our origin to `vscode-file://`, Chrome disallows any `file://` URIs to be loaded. 

I think we almost have to detect absolute URIs that are `file` based and rewrite them to a custom scheme like Deepak suggests to resolve this going forward.

**Comment by jrieken** [comment]
We already use the FileAccess-util for uris that have been transformed and it should be easy to use them for all, tho I am unsure how a unified scheme can be achieved because some need the special "this is from a remote" scheme already

**Comment by jrieken** [comment]
// @roblourens unsure what the snippet below is for but it will be broken once we don't use the file-scheme anymore

https://github.com/microsoft/vscode/blob/55393229982b2ef32d68b766fc69f06585be596b/src/vs/base/browser/markdownRenderer.ts#L105-L108

**Comment by bpasero** [comment]
Regarding `FileAccess` utility: the right method to call is `FileAccess.asBrowserUri` because this is a URI we want to embedd in the browser renderer. And that one already takes care of `vscode-remote` scheme:

https://github.com/microsoft/vscode/blob/7a9867c841e0222a08d29cbe6d0cc1512ba4c6e0/src/vs/base/common/network.ts#L159-L161

I think a good first step is to see whether `FileAccess.asBrowserUri` can be adopted for hovers or not. However, what Deepak is referring to with regards to a new custom scheme is the fact that yesterday I added this code to enable images to load even when their file paths point into the workspace:

https://github.com/microsoft/vscode/blob/a34297a60858cf43f4bc92aae48b72e3ea37754a/src/vs/code/electron-main/protocol.ts#L23-L23

Arguably this weakens our filtering and allows any images to load in the same context as the workbench. Hence the idea to introduce a new custom scheme specifically for images that the hover inlines through markdown rendering.

@jrieken though I think you mentioned yesterday in the standup that we have more places where images get inlined, not just the hover? I think you talked about editor decorations in the gutter as well?

**Comment by jrieken** [comment]
> I think a good first step is to see whether FileAccess.asBrowserUri can be adopted for hovers or not. 

That's easy - we partially already do that (today only for uris that have been transformed): https://github.com/microsoft/vscode/blob/55393229982b2ef32d68b766fc69f06585be596b/src/vs/base/browser/markdownRenderer.ts#L79-L85

> However, what Deepak is referring to with regards to a new custom scheme is the fact that yesterday I added this code to enable images to load even when their file paths point into the workspace:

Yeah, maybe. Pretty sure `asBrowserUri` returns different schemes depending on the input. We need to ensure that stays true. So a resource for a remote workspace will be having a different uri-scheme than one of a local workspace.

**Comment by jrieken** [comment]
> @jrieken though I think you mentioned yesterday in the standup that we have more places where images get inlined, not just the hover? I think you talked about editor decorations in the gutter as well?

Yeah, this place @jrieken though I think you mentioned yesterday in the standup that we have more places where images get inlined, not just the hover? I think you talked about editor decorations in the gutter as well?

**Comment by bpasero** [comment]
Ok, so `dom.asCssUrl` has already adopted `FileAccess` a while ago:

https://github.com/microsoft/vscode/blob/f1d92e789602f9389114760636f21c1b6b91ec32/src/vs/base/browser/dom.ts#L1230-L1230

> Yeah, maybe. Pretty sure asBrowserUri returns different schemes depending on the input. 

`FileAccess.asBrowserUri` will leave any URI untouched that is not `file://` scheme, the rule currently is:
* `vscode-remote`: use `RemoteAuthorities`
* `file`: rewrite to `vscode-file`
* anything else: pass through

**Comment by DanTup** [comment]
This is probably known, but just in case, this has become broken in the documentation shown in the completion/suggest widget too, not only hovers (I suspect they're using the same code though).

Is there any workaround extensions can use in the meantime to have images render again?

**Comment by DanTup** [comment]
@bpasero is there any known workaround for this? I'm getting a lot of issues from users that are now seeing broken images in tooltips/completion documentation that used to work. It's not clear from this issue if this is likely to be fixed in the near-term so I'm wondering if I should remove some of the image/icon previews to avoid the reports.

**Comment by SuporteSysrs01** [comment]
This issue is affecting Dart Code's icon previewing, which is something really useful while developing a Flutter application. I'm sticking to an older version of VSCode just to prevent this from happening, as having to

**Comment by SuporteSysrs01** [comment]
This issue is affecting Dart Code's icon previewing, which is something really useful while developing a Flutter application.

I'm sticking to an older version of VSCode just to prevent this from happening, as having to open a separate documentation just to see what an icon looks like is a pain.

Is there any plan to fix this in the near-term?

**Comment by mjbvz** [comment]
@DanTup Can you please test out the next VS Code insiders build (1.60) and let me know if this still isn't working. The commit I pushed seems to fix this for markdown strings with links in my test extension

**Comment by ArunPrakashG** [comment]
> @DanTup Can you please test out the next VS Code insiders build (1.60) and let me know if this still isn't working. The commit I pushed seems to fix this for markdown strings with links in my test extension

It is working fine on insiders build.

![build](https://user-images.githubusercontent.com/10849725/129071774-a7beaefd-79da-408d-83d9-d4e9363c7755.png)
![icon](https://user-images.githubusercontent.com/10849725/129071779-a53b9030-9c20-4f21-9f88-89c9df90c629.png)

**Comment by DanTup** [comment]
Sorry, I thought I replied to this but remember that it was while GitHub was having issues so I guess it never sent. I also verified in Insiders it was good, thanks! :-)
