### ISSUE TITLE
Move cell up sometimes focuses a random other cell

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119775]
Testing #119715

![recording (2)](https://user-images.githubusercontent.com/2193314/112290072-1c971a80-8c4c-11eb-8509-7355640c2bc0.gif)

**Comment by rebornix** [comment]
Good catch! Another case I didn't cover when fixing the focus issue last time.

Verifier: 

* Open endgame notebook
* Click into the second cell's editor (the one under macros)
* Scroll to the bottom
* Click on the last cell
* Keep pressing arrow up

The focus should never go into the second cell
