### ISSUE TITLE
After debugging tests is done, restore my "view state"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119756]
Testing #119545

* start debugging a unit test
* drill deep into some dependent code
* stop debugging

I am now "lost" as the editor is still show the last place at which I have debugged. I would like things to cleaned to the state that I had before debugging, e.g close all editor that where opened during debug

**Comment by isidorn** [comment]
I guess this is a general debug feature request. After debugging is done close all automatically opened editors.
We could add a setting for this.

**Comment by connor4312** [comment]
I would not turn this on in my editor, since when I'm debugging I often debug to the place there's a problem and then want to make changes there. It may take some delicacy to make this work well.
