### ISSUE TITLE
Go to file - repeated word searches incorrectly

### ISSUE THREAD

**Issue by FredrikSeidl** [microsoft/vscode#119779]
Issue Type: <b>Bug</b>

1. Create a new folder
2. Create a file `index.js` in that folder
3. Open the folder in VSCode
4. Open Go To File (cmd+p)
5. Type "index.js" (the file shows up)
6. Type "index.js index.js" the same result still shows up

Expected result - the next word should search further down the path and not in the full path again. So the file should dissappear

VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|-psn_0_9410809 --crash-reporter-id 68a37123-a7ca-423a-9f91-dba7c67a080e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.3.0
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
vscode-pull-request-github|Git|0.24.0
jsonnet|hep|0.1.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.4
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
vscode-docker|ms-|1.11.0
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vsliveshare|ms-|1.0.4018
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
java|red|0.76.0
vscode-yaml|red|0.16.0
jenkinsfile-support|sec|0.1.0
shellcheck|tim|0.14.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-icons|vsc|11.2.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vspre833cf:30267465
vshan820:30276952

```

</details>

**Comment by bpasero** [comment]
Query separated by space are individual queries matching on the entire path.
