### ISSUE TITLE
Reorder Tab should show indicator as to where the tab goes

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#11970]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

![reorder-tab](https://cloud.githubusercontent.com/assets/4033249/18484601/fd6cd002-799d-11e6-9ec5-8530171d0c5e.gif)

Atom:

![reorder-tab-atom](https://cloud.githubusercontent.com/assets/4033249/18484602/fd80e84e-799d-11e6-8061-80d41d5e7bfb.gif)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8544
