### ISSUE TITLE
UI indicator for pending cells in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119739]
- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1. Install Jupyter Extension
2. Enter value `1` in a cell
3. Select a Python kernel
4. Click run to start a cell
5. Depending on the OS and a number of other factors, the spinner might not appear for a few seconds.
At this point the Jupyter kernel is starting (this can take some time, in the case of Julia kernels, its very slow).

Would be good to have some UI indicator to show that something is happening.
Suggestion:
* Can we have the spinning icon without the timer?
* & When the real execution starts, then extension can initialize the timer.
I.e. the spinner & timer do not have to go hand in hand, its possible for the spinner to appear (spin) before the timer starts.

**Here's how it used to work (you can see a busy indicator, something is happening)**
![gettingstartOld](https://user-images.githubusercontent.com/1948812/112241893-0d8e7900-8c08-11eb-963d-52e6a565b589.gif)

**Here's how it works today (for some time it looks like the UI is frozen, on Windows & slower kernels the delay is even longer)**

![gettingstart](https://user-images.githubusercontent.com/1948812/112241946-26972a00-8c08-11eb-8ee7-84e9da4d4f55.gif)

@rebornix @roblourens @jrieken  /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
I'll leave the call to @misolori - to me it feels like "pending" should not have animation. You can have every cell "pending" all at once, then there will be a lot of animation on the page. It's not good to feel frozen either. The icon has a Pending tooltip though.

**Comment by misolori** [comment]
I think either the spinning sync icon or maybe we use an alternative icon like the clock:

![image](https://user-images.githubusercontent.com/35271042/112254327-a8de1900-8c1d-11eb-9a50-33f7260d84b6.png)

My only concern here is where it happens so fast that there's a blip of icons changing that can be distracting. I think the spinning icon would be a smoother transition. cc @jilljac to see if AZNB has a similar concept.

**Comment by roblourens** [comment]
Oh yeah, I like that clock. If it is the same size as the spinner, the blip is probably not noticeable, I can try it 

@jrieken also suggested spinning backwards to differentiate

**Comment by jrieken** [comment]
I like the clock but I also like the spinning counter-clockwise thing. That's what some browser do: while establishing a connection spin counter-clockwise, while fetching data spin clockwise.

**Comment by claudiaregio** [comment]
+1 for clock, think average user may not notice the difference in spinning directions.

**Comment by roblourens** [comment]
Going with a clock for now, we can see how we feel about it

**Comment by misolori** [comment]
Verified and it looks good 👍 

![image](https://user-images.githubusercontent.com/35271042/112682039-c7662f00-8e2c-11eb-8c8c-64e89d551737.png)
