### ISSUE TITLE
Provide a command to launch getting started for a particular extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119725]
When I adopt getting started in Luna Paint I'd like to tell the users that they can access the getting started guide/feature overview from within the tool by running some command. As such I'd like to be able to run some command with an arg being my extension ID to open it directly. That way I could wrap it in my own command.

Perhaps this should open to the side by default?

**Comment by JacksonKearl** [comment]
Added a `workbench.action.openWalkthrough(fullyQualifiedWalkthroughID: string, toSide?: boolean)`:

```ts
vscode.commands.executeCommand('workbench.action.openWalkthrough', 'jakearl.md-to-html#exampleProject', true);
```

**Comment by Tyriar** [comment]
When I call either of these:

```ts
// <extid>#<stepid>
commands.executeCommand('workbench.action.openWalkthrough', 'tyriar.luna-paint#luna.interfaceOverview', true);
// <extid>#<walkthroughid>
commands.executeCommand('workbench.action.openWalkthrough', 'tyriar.luna-paint#exampleProject', true);
```

This is the result:

<img width="1070" alt="Screen Shot 2021-05-25 at 5 39 36 AM" src="https://user-images.githubusercontent.com/2193314/119499460-98304900-bd1b-11eb-8a3e-2a0af5967391.png">

Am I doing something wrong? Also should open to side only open to side when there is an existing editor in the first group?

**Comment by Tyriar** [comment]
I was missing the capital T

**Comment by Tyriar** [comment]
Actually I think this should be case insensitive just like `workbench.action.openIssueReporter`

**Comment by JacksonKearl** [comment]
Going to close this out for verification this milestone, opened #125414 to track case insensitivity

**Comment by karrtikr** [comment]
Can anyone here help me with how to highlight a specific step/tile in a walkthrough? That does not seem to be documented but according to a quoted text it seems it should be possible:

>  you can run the command `workbench.action.openWalkthrough` with args
> `{ "category": "walkthroughID" (with hash separating ext id and walkthrough name)', "step": "stepID" }`. They need to be URI encoded... so something like %7B%22category%22%3A%22notebooks%22%2Cstep%3A%22notebookProfile%22%7D (I used https://www.urlencoder.org/)

**Comment by Tyriar** [comment]
@lramos15?
