### ISSUE TITLE
Notebook Icons in Editor titlebar go missing

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119706]
Version: 1.55.0-insider
Commit: a6f6b4aa8e3a688d9a5cbcd5df14af511ce2bd8e
Date: 2021-03-23T05:13:33.822Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Install Jupyter Extension
2. Open a notebook & watch how sometimes the `RUn All` button vanishes & never re-apperas.
Seems quite flaky, sometimes its tehre, sometimes not.
Even after running a cell it doesn't appear.

![recording](https://user-images.githubusercontent.com/1948812/112217374-cbe9d800-8bdf-11eb-8a3f-a5f0daf8947d.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DonJayamanne** [comment]
@rebornix /cc

**Comment by rebornix** [comment]
Good catch!

**Comment by DonJayamanne** [comment]
Yup works now, /verified.
