### ISSUE TITLE
Search view in text editor occupies space of code after scrolling

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#119781]
- VS Code Version: 1.52.1
- OS Version: Mac OS 11.2

Steps to Reproduce:

1. trigger searching using `cmd+f` 
2. scroll down
3. scroll back
4. you can see the space of first line is occupied by the search window

https://user-images.githubusercontent.com/8640918/112293716-64aa5180-8ccd-11eb-996c-d0f188c0e04c.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Please start by updating to the current release, 1.54.3, in case this has already been fixed.

**Comment by IllusionMH** [comment]
This is intended behavior so Find widget won't hide text on the first line.
You can disable it with `"editor.find.addExtraSpaceOnTop": false`

**Comment by roblourens** [comment]
That's correct, thanks @IllusionMH!
