### ISSUE TITLE
flaky execution smoke test

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#119744]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=110168&view=logs&jobId=3792f238-f35e-5f82-0dbc-272432d9a0fb&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4

**Comment by roblourens** [comment]
I was debugging this last night. It was flaky in web for me but totally fine in desktop. Will debug more
