### ISSUE TITLE
Clear notebook output button showing in TS files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119852]
* todays insiders
* open a TS file
* it shows the notebook clear all command

<img width="573" alt="Screenshot 2021-03-25 at 08 30 34" src="https://user-images.githubusercontent.com/1794099/112434994-711dc100-8d44-11eb-8257-30b60ebe808f.png">

**Comment by rebornix** [comment]
Once a notebook is opened, the run all button doesn't go away too.

```
	when: ContextKeyExpr.and(executeNotebookCondition, ContextKeyExpr.or(NOTEBOOK_INTERRUPTIBLE_KERNEL.toNegated(), NOTEBOOK_HAS_RUNNING_CELL.toNegated()))
```

**Comment by jrieken** [comment]
Unrelated-related question: why is the [menu contribution](https://github.com/microsoft/vscode/blob/ce9298464e48c8b52197f1a007b5b80d21fb06ca/src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts#L629-L638) not part of the [action definition](https://github.com/microsoft/vscode/blob/ce9298464e48c8b52197f1a007b5b80d21fb06ca/src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts#L544)

**Comment by rebornix** [comment]
@jrieken 👍 , created https://github.com/microsoft/vscode/issues/119885
