### ISSUE TITLE
add  "clear buffered data from terminal console" option 

### ISSUE THREAD

**Issue by loveyandex** [microsoft/vscode#119869]
we must able to clear texts written in consoles from anywhere
and a shortcut like Ctrl K+ C or  Ctrl + delete

**Comment by loveyandex** [comment]
no this is not that ..that is bug but what i am saying here is the ability to clear all console when running a app 
like python or node js app in terminal ..you must be clever than this when you are working for microsoft

**Comment by Tyriar** [comment]
There's an existing `Terminal: Clear` command, you can set up a custom keybinding for it like this:

```
{ "key": "ctrl+delete", "command": "workbench.action.terminal.clear" }
```

**Comment by loveyandex** [comment]
@Tyriar 
i dont see any Terminal: Clear command,

**Comment by Tyriar** [comment]
Negative

![recording (19)](https://user-images.githubusercontent.com/2193314/113311836-8eabd700-92be-11eb-9268-6abbe2a07221.gif)
