### ISSUE TITLE
Output não mostra resultado

### ISSUE THREAD

**Issue by JSouza27** [microsoft/vscode#119833]
Issue Type: <b>Bug</b>

Hoje percebi que o Output só mostra o resultado vazio em arquivo .js como visto abaixo. Tentei um simples código "console.log('teste');" e mostra o mesmo resultado.

"[Running] node "/home/jonathan/Documentos/turma_10_tribo_b/trybe-exercises/Bloco  7/7.2/objParte1.js"

[Done] exited with code=0 in 0.14 seconds"

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-45-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz (4 x 2463)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.34GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 2e1905d3-a168-4b30-86e7-0588124e2da6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|6.3.1
code-runner|for|0.11.3
beautify|Hoo|1.5.0
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
wslfolderdoc:30280164
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by JSouza27** [comment]
Today I realized that Output only shows the empty result in a .js file as seen below. I tried a simple code "console.log ('test');" and shows the result below.

_**[Running] node "/home/jonathan/Documentos/turma_10_tribo_b/trybe-exercises/Bloco 7/7.2/objParte1.js"

[Done] exited with code=0 in 0.14 seconds**_

**Comment by JSouza27** [comment]
Today I realized that Output only shows the empty result in a .js file as seen below. I tried a simple code "console.log ('test');" and shows the result below.

_**[Running] node "/home/jonathan/Documentos/turma_10_tribo_b/trybe-exercises/Bloco 7/7.2/objParte1.js"

[Done] exited with code=0 in 0.14 seconds**_

**Comment by JSouza27** [comment]
every result of javascript code comes out like this, even "console.log ('hello world')

- I use the code run extension to run javascript
- I noticed that if I use the F5 keyboard it runs the debug code and gives me the result but in console mode it doesn't work

**Comment by JSouza27** [comment]
![Captura de tela de 2021-03-25 18-06-26](https://user-images.githubusercontent.com/49069814/112543713-e7e2aa80-8d94-11eb-91da-d5e8d6835b58.png)

**Comment by JSouza27** [comment]
using debugging with F5

![Captura de tela de 2021-03-25 18-07-47](https://user-images.githubusercontent.com/49069814/112543815-08126980-8d95-11eb-8d25-ef3ab9943b57.png)

**Comment by connor4312** [comment]
This is caused by the Code Runner extension, please open an issue there https://github.com/formulahendry/vscode-code-runner
