### ISSUE TITLE
"window.menuBarVisibility": "classic" can show on desktop

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#119835]
Issue Type: <b>Bug</b>

1. On MacOS
1. In your settings, add `"window.menuBarVisibility": "classic",`

**Bug**
The menubar is now showing on top of the standard OS X one

<img width="567" alt="Screen Shot 2021-03-24 at 6 36 17 PM" src="https://user-images.githubusercontent.com/12821956/112405797-3712d780-8cd0-11eb-9a71-cf8c6ddd6d1d.png">

VS Code version: Code - Insiders 1.55.0-insider (8437d38d364ba93b53c1e659c20b1c86f710ec28, 2021-03-24T08:10:36.007Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
docs-view|bie|0.0.9
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
codespaces|Git|0.9.0
vscode-pull-request-github-insiders|Git|2021.3.34507
vscode-postfix-ts|ipa|1.9.3
template-string-converter|meg|0.4.7
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.4.678042391
remote-containers|ms-|0.165.0
remote-ssh-edit-nightly|ms-|2021.3.25381
remote-ssh-nightly|ms-|2021.3.25380
azure-account|ms-|0.9.7
hexeditor|ms-|1.4.0
vscode-github-issue-notebooks|ms-|0.0.74
debugger-for-chrome|msj|4.12.12
java|red|0.76.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
markdown-all-in-one|yzh|3.4.0

</details>

**Comment by mjbvz** [comment]
How I hit this:

1. In a codespace in a browser
2. Set ` "window.menuBarVisibility": "classic"`
3. This setting was then synced to my desktop VS Code instances by setting sync

**Comment by sbatten** [comment]
duplicate #119854
