### ISSUE TITLE
Click on breadcrum scrolls the editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#119898]
Issue Type: <b>Bug</b>

* Open a markdown file
* Scroll to the bottom
* Click on the breadcrumb

https://user-images.githubusercontent.com/876920/112518744-e8f4e700-8d56-11eb-9f87-c3e412065b00.mov

Escape restores the scroll position, but it's a bit weird that clicking on the breadcrumb to review the TOC has impact on the scroll top of the editor itself.

VS Code version: Code - OSS Dev 1.55.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (1.00GB free)|
|Process Argv|. --no-sandbox --enable-proposed-api ms-vsliveshare.vsliveshare|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Unsure, clicking an item of breadcrumbs opens the picker and reveals the selected element. That's how it is intended to work. Why else would you click on breadcrumbs? You also have the 'breadcrumbs.focus' command (`cmd+shift+;`) to only focus and navigate breadcrumbs and selecting an item requires pressing `Enter`
