### ISSUE TITLE
node_modules not showing in tree

### ISSUE THREAD

**Issue by primelos** [microsoft/vscode#119847]
Issue Type: <b>Bug</b>

I working on a cloned server in node.js.  When I run npm install the node_modules folder does not show on the left side with the other files and folders.  At first I thought it was not working but when i check the folder using the finder in my mac I can see the node_modules was created.  If I close vscode and reopen it then I can see the folder.  

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.93GB free)|
|Process Argv|. --crash-reporter-id 359e203e-d012-4e54-9a51-cec18058ba16|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
es7-javascript-class-snippets|abr|0.4.0
arepl|alm|2.0.1
vscode-browser-preview|auc|0.7.0
mongogo|bag|0.1.2
package-json-upgrade|cod|1.3.0
compulim-vscode-dictionary|Com|0.0.5
mern-snippets|dev|1.5.0
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
prettier-vscode|esb|6.3.1
vscode-graphql|Gra|0.3.15
mongo-runner|Joe|0.6.2
vscode-styled-components|jpo|1.5.0
graphql|mqu|0.1.2
mssql|ms-|1.10.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
LiveServer|rit|5.6.1
mongo-snippets-for-node-js|roe|1.3.5
js-jsx-snippets|sky|10.1.0
code-spell-checker|str|1.10.2
vscode-icons|vsc|11.2.0
quokka-vscode|Wal|1.0.351
ReactSnippets|xab|2.4.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by isidorn** [comment]
I can not reproduce this. 
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

**Comment by IllusionMH** [comment]
Do you have `node_modules` in your `files.exclude` configuration for User or Workspace level?

**Comment by primelos** [comment]
now when i clone a project and run npm install I get this error?
<img width="960" alt="Screen Shot 2021-03-25 at 10 27 59 AM" src="https://user-images.githubusercontent.com/29004494/112518707-de3a5200-8d56-11eb-9a11-1e710b2384a1.png">
