### ISSUE TITLE
localization smoke test failing and one pending on remote

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#119816]
On remote, 

Localization
        pending: starts with 'DE' locale and verifies title and viewlets text is in German
      Launch
        failure: verifies that application launches when user data directory has non-ascii characters

with this message:
```
  2) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Launch
           verifies that application launches when user data directory has non-ascii characters:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\merogge\repos\vscode\test\smoke\out\main.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

If it matters, this fails before that with a timeout
```
  1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Multiroot
           shows results from all folders:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.
      at poll (C:\Users\merogge\repos\vscode\test\automation\out\code.js:173:19)
      at async Code.waitForElements (C:\Users\merogge\repos\vscode\test\automation\out\code.js:250:16)
      at async QuickInput.waitForQuickInputElements (C:\Users\merogge\repos\vscode\test\automation\out\quickinput.js:24:9)
      at async Context.<anonymous> (out\areas\multiroot\multiroot.test.js:39:13)

```

**Comment by TylerLeonhardt** [comment]
> verifies that application launches when user data directory has non-ascii characters:

@bpasero any thoughts? I mention you because of the new hash function (https://github.com/microsoft/vscode/issues/119301) but it could be totally unrelated.

**Comment by bpasero** [comment]
I just ran that particular test and it succeeds for me:

![image](https://user-images.githubusercontent.com/900690/112430376-58aaa800-8d3e-11eb-8b52-78beecf75231.png)

So I would not think that the new hash function fails over special characters.

**Comment by bpasero** [comment]
And btw, we do run smoke tests with every build now on macOS both local and against remote and they do not fail:

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=110388&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=b4255493-5d6b-5e5c-80d7-ebab0307fbf4

**Comment by dbaeumer** [comment]
I reenabled the test locally and they run fine under Linux:

<img width="490" alt="capture" src="https://user-images.githubusercontent.com/1931590/112451040-530c8c80-8d55-11eb-8c1d-718c73351917.png">

@meganrogge any additional info?

**Comment by dbaeumer** [comment]
Tested Windows as well. Same result.

**Comment by dbaeumer** [comment]
@isidorn tested under Mac and things look good as well.

![Screenshot 2021-03-25 at 14 55 05](https://user-images.githubusercontent.com/1931590/112484465-4189ab80-8d7a-11eb-8f26-15f133f46985.png)

I will close the issue.
