### ISSUE TITLE
UX meeting agenda 14 September, 2016

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#11989]
- Refactoring extensibility feedback

If we have the right people in attendance, we should also discuss the following issues.
- Close button for horizontal panel #9638
- Debugging sidebar remains open #1931

**Comment by bgashler1** [comment]
@Microsoft/vscode team please let me know anything else that should be discussed.  Meeting is at 8:00am Redmond time (5:00pm Zurich).

**Comment by bgashler1** [comment]
# Notes

## Refactoring extensibility feedback
The Zurich team feels that the _preview experience_ is unneeded for the refactoring and that it doesn't solve the underlying problem of discoverability.  However, Steven made a good point that a preview might help new users trust using the feature, since they could validate how it works before it touches their code.  Later these users may feel no more need for it and turn it off.  The peek view seems to be the least interruptive UI we currently have to handle the preview.

In a perfect world, a language service could handle a refactor without incident and with no preview, but since that isn't always the case, we could also show a preview for changes where the language service was not 100% confident it got right for users to accept, reject or modify manually.  We need to do more UX exploration in this.  Ben suggested that refactoring feels a lot like Find/Replace.  Steven and I will get more feedback from him to help refine this experience.

Universally liked was the _lightbulb experience_ for suggesting corrections to broken symbols.  The team believes this would also help with refactoring discoverability for new users.  We should, of course, make sure our undo experience to avoid painful mistakes.

## Horizontal panel
### Close or chevron button
Some on the team fear that the "X" button's purpose will be misunderstood as to terminate tasks and other context when closing the panel.  Sean says that he is reluctant to change the UI without customer feedback first.  We will most likely leave the chevron in for now, since it's been in for months with no problems, and because removing it may cause a problem.

### Panel
Erich did not like the _status bar icon toggles_ nor the _sub-activity bar toggles_ concepts:

![image](https://cloud.githubusercontent.com/assets/11839736/18530120/e2a5573e-7a84-11e6-974c-e78cec852df6.png)
![image](https://cloud.githubusercontent.com/assets/11839736/18530238/752fc620-7a85-11e6-89cd-53465a453c29.png)

For a more conservative first-step, we should plan on using the earlier concept of using just the text tabs in the horizontal panel to switch between panels:

![image](https://cloud.githubusercontent.com/assets/11839736/18530164/11bc5266-7a85-11e6-83db-fb508f526138.png)
We then can validate how that does with users.

**Comment by Tyriar** [comment]
FYI @kieferrm
