### ISSUE TITLE
Extension icons missing

### ISSUE THREAD

**Issue by jacobweber** [microsoft/vscode#119820]
Issue Type: <b>Bug</b>

None of the extensions have icons anymore. Tried disabling all extensions, but same results.

![image](https://user-images.githubusercontent.com/542988/112374552-7a088700-8c9f-11eb-9a40-8f593e758498.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.78GB free)|
|Process Argv|--disable-extensions --crash-reporter-id ee98133f-4180-44b0-86f2-150582a5f918|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by lramos15** [comment]
Did you ensure that your panel is wide enough? Try dragging it to be larger as if it is too small the icons will be hidden which is what your screenshot depicts.

**Comment by IllusionMH** [comment]
Just make it wider to see icons. 

Also see #118511

**Comment by jacobweber** [comment]
Yep, sorry — didn't realize that.
