### ISSUE TITLE
Notebook diff editor shows "internal" metadata

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119853]
* changed GH issues notebooks to not store output
* run a notebook
* open in rich diff editor
* internal metadata leaks into the diff view

<img width="1147" alt="Screenshot 2021-03-25 at 08 41 19" src="https://user-images.githubusercontent.com/1794099/112436143-edfd6a80-8d45-11eb-816c-1b333b9f644d.png">

**Comment by jrieken** [comment]
I assume this issue also caused GH issue notebook to become dirty when running a cell (due to internal metadata changing)

**Comment by rebornix** [comment]
@roblourens we used to store all info in the `metadata` property, didn't we move them out with the new execution api?

**Comment by rebornix** [comment]
though I'm not seeing it in latest Insiders with the new extension.

**Comment by rebornix** [comment]
I can reproduce when I keep running cells and clearing outputs.

**Comment by roblourens** [comment]
Looking at this code, we might rethink mixing the internal and extension metadata. lmk what you think.

**Comment by jrieken** [comment]
> Looking at this code, we might rethink mixing the internal and extension metadata. lmk what you think.

Yeah, in my mind that is a temporary workaround that has made the change simpler but IMO we should model execution separate for the "content" metadata
