### ISSUE TITLE
Getting blurry code

### ISSUE THREAD

**Issue by P0NC1K** [microsoft/vscode#119828]
Issue Type: <b>Bug</b>

When I type I the text randomly becomes blurish . Even when I write this issue report it's getting blurry little by little

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.71GB free)|
|Process Argv|--crash-reporter-id e2f8b804-3617-4158-88fd-c7792e1d467c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
terminal|for|0.0.10
powershell|ms-|2021.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833:30267464
vshan820cf:30276953

```

</details>

**Comment by l33tli3s** [comment]
<img width="858" alt="Screenshot 2021-05-25 050547" src="https://user-images.githubusercontent.com/74946081/119512335-11ce3400-bd28-11eb-9ab9-6cab8548974d.png">

**Comment by l33tli3s** [comment]
<img width="850" alt="Screenshot 2021-05-25 050524" src="https://user-images.githubusercontent.com/74946081/119512459-2ca0a880-bd28-11eb-89f7-b3131484a2cf.png">


I took these while I was using VSCode. I'll get a screen recording next time I run it. 

Thanks!

**Comment by deepak1556** [comment]
@l33tli3s can you try launching with `code --force-device-scale-factor=1` and check if the issue happens.
