### ISSUE TITLE
Handle invalid custom terminal profile

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#119830]
Issue Type: <b>Bug</b>

1. Add a custom profile that uses an older schema to settings:
```
"terminal.integrated.profiles.osx": {
  "bash (login)": {
    "pathOrPaths": "bash",
    "args": ["-l"]
  }
}
```
2. Run the `Select Default Profile` command

Nothing happens, but there's an error in the console:
```
ERR The "path" argument must be of type string. Received type undefined: Error: The "path" argument must be of type string. Received type undefined
```

Would be nice to show an error notification

VS Code version: Code - Insiders 1.55.0-insider (8437d38d364ba93b53c1e659c20b1c86f710ec28, 2021-03-24T08:10:36.007Z)
OS version: Darwin x64 19.6.0

**Comment by meganrogge** [comment]
Since the settings schema tells the user what's wrong with that profile, I'm going to just ignore the profiles from config that don't contain `path` or `source` values.

**Comment by meganrogge** [comment]
![recording (62)](https://user-images.githubusercontent.com/29464607/112403917-966ee880-8ccc-11eb-8d71-42793c792b9b.gif)

**Comment by meganrogge** [comment]
fine with you @Tyriar ?

**Comment by Tyriar** [comment]
Looks good
