### ISSUE TITLE
Click to run tests appears on HTML document

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#119800]
Steps to reproduce
1. Have VS Code test runner installed
2. Create a new HTML file within the vscode project
3. 🐛 Start typing, it shows a button to run tests even though there are none in that file
<img width="1067" alt="Screen Shot 2021-03-24 at 11 43 36 AM" src="https://user-images.githubusercontent.com/4544166/112339841-699fde80-8c96-11eb-8ca0-9a55f018cb87.png">

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/119634
