### ISSUE TITLE
Support richer rendering of markdown, such as rendering links as their link name only (hiding link url) while not under cursor

### ISSUE THREAD

**Issue by koenlek** [microsoft/vscode#119897]
**Context**
Currently, markdown rendering seems to be strictly limit to always render each character position, with some flexibility within that position (such as changing color, bold, italic, underline). This makes sense as VS Code editing at its core is about plain text editing. 

Some other markdown renderers, such as Zettlr, are striking a nice balance between plain text and WYSIWYG. They keep all the properties of plain text (every property that affects rendering is explicitly visible to the user) while providing some nice enhancements to rendering. Some of the features of editors like Zettlr that I like:

1. Render links (`[text](http://url)`) as link-name by default (`text`), only expanding it when the cursor is at the link.
2. Render images. Again, as soon as you select it, it turns into raw markdown again.
3. Render latex to render formulas. 
4. Render headers at a larger font.

I very much like it that the editor and the rendered output are in the same view. I strongly prefer that over the two column approach that VS Code currently has (left column editor, right column a rendered markdown preview), as that is much less effective use of my screen real estate. 

**Request**

Could we add such richer rendering to VS Code markdown editor (either native or as an extension)? I doubt if it would even be possible as an extension today, as it would need to allow the extension to tamper with the rendered content of the editor window in a way that hides characters or other fancy stuff (like img rendering). 

The 4 examples above are already in order of priority to me. **I care by far the most about rendered links**. I often add long links to my markdown (with huge BASE64 encoded settings in the URL) and they totally clutter the editor for me, loosing overview of the overall document structure. This also seems the simplest, as it can be done without breaking a grid-like monospace character layout.

Example screenshot of the rendered links:
![image](https://user-images.githubusercontent.com/6514289/112518202-666c2780-8d56-11eb-9462-77ae95ce4124.png)

![image](https://user-images.githubusercontent.com/6514289/112518252-7257e980-8d56-11eb-9f9a-99c15a4bc61c.png)

**Possibly related**

I found https://github.com/microsoft/vscode/issues/91987 and based on some discussions I read I was hoping that this could unblock my needs. I deed a quick try with the Insiders release and the [Markdown Notebook extensions](https://github.com/microsoft/vscode-markdown-notebook), but that doesn't seem to address my feature request yet.

**Comment by mjbvz** [comment]
Some of these features may be possible to add with extensions. However VS Code's built-in markdown support is focused on text editing instead of offering a wysiwyg-lite experience
