### ISSUE TITLE
`QuickPickItem.picked` does not work when used with `createQuickPick`

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#119834]
- VS Code Version: 1.54.3
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Clone microsoft/vscode-extensions-sample repo
2. Open the quickinput-sample
3. Change `multiStepInput.ts` in order to make `showQuickPick` function to work with multi select. Add `input.canSelectMany = true` and update `resourceGroups` adding `picked: true` for all of them
4. Debug the extension
5. Choose the `multiStepInput` option
6. See that even displaying the resource groups with _checks_, they are not _picked_

This has been reported in https://github.com/microsoft/vscode/issues/103084, but instead of a fix to the code snippet or description if it was an error at `createQuickPick`, it was suggested to use `showQuickPick`. I would love to be able to use `showQuickPick`, but I need to add `QuickInputButton` on my pick component, and `showQuickPick` does not support `Buttons`.

Thank you

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by TylerLeonhardt** [comment]
As a workaround, you can do this:

```
input.selectedItems = items.filter(item => item.picked);
```

**Comment by TylerLeonhardt** [comment]
This actually asks a very interesting question... if you set items with the `picked` attribute, should that _also_ impacted the `selectedItems` property?

There might be customers out there that have set `selectedItems` to some array and then set `items` to all their items... but if those items have the `picked` property, should it overwrite what they set for `selectedItems`?

I'm more leaning towards "no" as it could potentially break existing customers.

**Comment by alefragnani** [comment]
It actually works 🎉 . 

I just have to change a small piece, but this wouldn't be a problem if I create a new `showQuickPickMultiSelect` function. Because with your snippet, the `onDidChangeSelection` is automatically called, and the `QuickPick` goes to the next step. So instead, I used `onDidAccept` event.

```ts
  input.items = items;
  input.canSelectMany = true;
  if (activeItem) {
      input.activeItems = [activeItem];
  }
  input.selectedItems = items.filter(i => i.picked)
  input.buttons = [
      ...(this.steps.length > 1 ? [QuickInputButtons.Back] : []),
      ...(buttons || [])
  ];
  disposables.push(
      input.onDidTriggerButton(item => {
          if (item === QuickInputButtons.Back) {
              reject(InputFlowAction.back);
          } else {
              resolve(<any>item);
          }
      }),
      // input.onDidChangeSelection(items => resolve(items[0])),
      input.onDidAccept(async () => {
          console.log(`Number of picked items: ${input.selectedItems.length}`);
      }),

```

I just wonder why it was choosed `picked` instead of `selected` in `QuickPickItem`. Ah, I see...  `Quick_Pick_Item` -> picked 😄 

About your question, I'm seeing two concurrent APIs, and that's may be the reason it is not working properly. I would say the `selectedItems` property should be deprecated and/or turned _read only_, making `QuickPickItem.picked`  _the only way_ to define if an item is picked/pre-selected or not.

In the end `showQuickPick` works very different from `createQuickPick`, when you have multi selection.

In fact, I would prefer `showQuickPick` supporting `QuickInputButton`, just like `showInputBox` does. It would be simpler 😉

**Comment by TylerLeonhardt** [comment]
> In the end showQuickPick works very different from createQuickPick, when you have multi selection.

Yeah this is the reality of the APIs unfortunately. They are really quite different. I don't think we can really deprecate it at this point because there are extensions out there that depend on this. @chrmarti, do you have any thoughts on this?

**Comment by alefragnani** [comment]
I totally understand, and respect, about the API deprecation _care_. I remember in one of the Extension Authors Call I participated where Connor Peet talked about that. If it is widely used, or in the wild for a long time, it's harder to deprecate.

Maybe in this case, an improvement in the documentation (`vscode.d.ts`) would also help.

Thank you

**Comment by chrmarti** [comment]
`createQuickPick` is taking the approach of returning a `QuickPick` object that can be changed and observed over time and changes to its properties (e.g., `selectedItems`) are reflected in the UI even when the picker is already visible for some time. Making `QuickPickItem.picked` behave similar to the `QuickPick` object to be consistent would require us to support some kind of event on the `QuickPickItem`, so the extension could fire that to tell us that we need to read `QuickPickItem.picked` again. In that light using `selectedItems` seems like a simpler approach than using `QuickPickItem.picked`.

**Comment by alefragnani** [comment]
@chrmarti Thanks for the additional explanation. I understand both API has different approaches, so I guess an update to the documentation would be enough.

@TylerLeonhardt Thanks for your help too. It is working perfectly with the solution you provided

Closing ...
