### ISSUE TITLE
unbound breakpoint in Angular project

### ISSUE THREAD

**Issue by alanmfeldstein** [microsoft/vscode#119804]
Issue Type: <b>Question</b>

Open casedata-search.component.ts in the editor and click the left gutter to add a breakpoint.  It is displayed as a red circle.

Here's launch.json (comments omitted):

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:4200",
            "webRoot": "${workspaceFolder}",
            "outFiles": [
                "${workspaceFolder}/**/*.js",
                "!**/node_modules/**"
            ],
            "trace": true
        }
    ]
}
```

ng serve state-portal-ui
Start Debugger
Chrome launches my application.
Note that the breakpoint has become unbound.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.25GB free)|
|Process Argv|--crash-reporter-id f2a1c9ac-88a4-4eac-b5f6-fc9be5425aab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.12.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by alanmfeldstein** [comment]
See [https://github.com/microsoft/vscode-js-debug/issues/872](url)

There, Connor Peet focuses attention on angular.json. I too had considered angular.json but got into issues I didn't know how to solve quickly. Instead, I chose
ng build state-portal-ui --source-map=true

That does create the source maps and Chrome sees them. However, it doesn't solve the unbound breakpoint problem. Is the 'ng build' option an invalid alternative to angular.json? It is my understanding that command line options override angular.json options.

**Comment by alanmfeldstein** [comment]
[vscode-debugadapter-70b3b99c.json.gz](https://github.com/microsoft/vscode/files/6200707/vscode-debugadapter-70b3b99c.json.gz)

**Comment by connor4312** [comment]
It looks like your build is coming out of a subdirectory of `${workspaceFolder}/projects/<something>`, so you want to make sure the `webRoot` in your launch.json is set to that folder that so that paths resolve correctly. You can run the `Create Diagnostic Information` command while debugging to see the helper. Let us know if you have any other questions.
