### ISSUE TITLE
Code version not latest after download

### ISSUE THREAD

**Issue by ryanp76** [microsoft/vscode#119894]
Issue Type: <b>Bug</b>

Remove older instance of vscode (rm -ef VSCode-linux-x64)
Download linux x86 tarball from vscode download site.
untar new version
run new version
Notifications informs that I am not running the latest version
Check of version in help/about shows 1.52.1, but the version showed as the latest on the download site says 1.54 is now available.

Is the latest linux version 1.52?  

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 3.10.0-1062.1.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz (2 x 1999)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|7, 3, 2|
|Memory (System)|3.67GB (0.11GB free)|
|Process Argv|--no-sandbox --crash-reporter-id d068e89a-78fc-44d1-ba0f-5162986c9fd8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
go|gol|0.23.3
fluent-icons|mig|0.0.2
remote-containers|ms-|0.155.1
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.52.0
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.2.2
code-spell-checker|str|1.10.2
statusbar-format-on-save|tre|1.1.2
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943:30280189
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment]
For RHEL 7 / CentOS 7 I think the latest compatible version is 1.52.

**Comment by ryanp76** [comment]
It would be nice if the IDE knew that, for the OS it is running on, it has the latest version.  I like that vscode tells me when it an update is available, but now I don't know if there really is one unless I actually download and install the latest tarball and check the version in the help/about window.
