### ISSUE TITLE
Process exited with code 3221225477

### ISSUE THREAD

**Issue by cybairfly** [microsoft/vscode#119871]
I'm sorry to report but this bug is far from solved and should not be closed - it's been driving me crazy, constantly, for as long as I can remember - regardless of latest updates of everything and trying to also disable AV:

https://github.com/microsoft/vscode/issues/91044
https://github.com/microsoft/vscode/issues/94499
https://github.com/microsoft/vscode/issues/95111

- VS Code Version:
```
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

- OS Version:
```
Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎25/‎2020
OS build	19042.867
Device name	Pro
Processor	Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.81 GHz
Installed RAM	8.00 GB (7.89 GB usable)
System type	64-bit operating system, x64-based processor
```

Steps to Reproduce:
1. Launch debugger

It even seems to be getting worse and more frequent with time, rather than improve. The recent rate of these errors has been almost unbearable. Only happens with the debugger, not without.

Most often the sequence to trigger this seems to be:
- edit code while running debugger (sometimes this will completely mess up breakpoints and shift them around to different lines)
- re-run code in debug mode

Workaround, not really a solution though - discard all breakpoints.

![image](https://user-images.githubusercontent.com/18344357/112474147-8bb95f80-8d6f-11eb-98f4-1bce8cba2660.png)
![image](https://user-images.githubusercontent.com/18344357/112474155-8fe57d00-8d6f-11eb-8691-f6fa944b80b3.png)
![image](https://user-images.githubusercontent.com/18344357/112474179-92e06d80-8d6f-11eb-9bb1-c99752b18d76.png)

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch via NPM",
            "type": "pwa-node",
            "request": "launch",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "start"
            ],
            "skipFiles": [
                "<node_internals>/**"
            ],
        },        
        {
            "name": "Run npm start",
            "command": "npm start",
            "request": "launch",
            "type": "node-terminal",
        }
    ]
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by connor4312** [comment]
Please:

1. Try updating to the latest version of Node.js to see if that fixes the problem
2. Open an issue on https://github.com/nodejs/node. The error that's being printed is something going wrong in Node.js or V8

Thanks!

**Comment by cybairfly** [comment]
@connor4312 thanks! After updating to Node 14 the issue did not fully disappear but it seem to be much less frequent right now.
