### ISSUE TITLE
Request: option for find/nextMatchFindAction to search forward only, previousMatchFindAction to search backward only

### ISSUE THREAD

**Issue by Bill-Stewart** [microsoft/vscode#11981]
- VSCode Version: 1.6.0

Steps to Reproduce:
1. Position cursor near bottom of a file.
2. Press <kbd>ctrl</kbd>+<kbd>f</kbd> and search for something that is before the cursor.
3. Cursor jumps "backwards" and finds term before original cursor position - this is counterintuitive (so "next" means "before"?).

This request is to have an option to have `actions.find` and `editor.action.nextMatchFindAction` to search forward in the file only. If no more matches, do not reposition cursor and inform user no more matches (just like if search term is not found in the file at all).

Included in this option would be to have `editor.action.previousMatchFindAction` to search backward in the file only. If no previous matches, do not reposition cursor and inform user no previous matches.

This should also apply to other actions such as `editor.action.addSelectionToNextFindMatch`, `editor.action.addSelectionToPreviousFindMatch`, etc.

**Comment by Bill-Stewart** [comment]
This can also be accommodated if there are find APIs available; e.g.: https://github.com/Microsoft/vscode/issues/14855

**Comment by rebornix** [comment]
This can now be disabled by setting `editor.find.loop`.
