### ISSUE TITLE
Emmet extensions does not exist

### ISSUE THREAD

**Issue by Shartzzz-work** [microsoft/vscode#119843]
i tried to install custom snippets from snippets.json
it didn't work for me 
i deleted the file  snippets.json
and emmet stopped working completely. Emmet is missing from extension vscode global
![image](https://user-images.githubusercontent.com/79984948/112419032-b12c7600-8d3b-11eb-8199-e6240e4dfc36.png)
I turned off all extensions and still it is not there
no tips 
![image](https://user-images.githubusercontent.com/79984948/112419261-2730dd00-8d3c-11eb-84d8-73e66fc68aa5.png)
help please, i don't know what to do

**Comment by Shartzzz-work** [comment]
and i tried to reinstall  vsCode

**Comment by Shartzzz-work** [comment]
fixed
copied my settings.json to a another file 
del folder "Code" from C:\Users\User\AppData\Roaming
reload vscode and past old settings

**Comment by rzhao271** [comment]
Closing for now. Reopen if it comes up again
