### ISSUE TITLE
Dropdown menus disappear when hovering in 4K screen

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#119829]
Issue Type: <b>Bug</b>

When running vscode in a 4K multi-monitor setup, the dropdown menus will flicker random option highlighting in the root dropdown, when you hover over sub-menu options. Then the whole menu will randomly close as you keep moving your mouse to cause the flickering. So to select any sub-menu option, you have to be quick and click on it regardless of the currently highlighted option, before the whole thing closes by itself.

This issue was introduced only in the last 2 months or so, I think.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-7642-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.09GB (6.65GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id eb1c688b-c4e3-4232-85a1-c01025d91995|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.18.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
restore-terminals|Eth|1.0.6
vscode-firefox-debug|fir|2.9.2
gauge|get|0.0.19
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.163.2
vsliveshare|ms-|1.0.4018
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.33.1
indenticator|Sir|0.7.0
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsfjg287:30275553
vshan820cf:30276953

```

</details>

**Comment by deepak1556** [comment]
Is this issue present with latest stable `1.73` ? If so, please try running with `--disable-gpu`.

**Comment by Hadakajime** [comment]
Unfortunately I don't have access to 4K screens anymore.
