### ISSUE TITLE
Poor UX re. the VCS context menu: Stage/Stash Changes entries are hard to tell apart

### ISSUE THREAD

**Issue by tlemo** [microsoft/vscode#119827]
Issue Type: <b>Bug</b>

The VCS context menu has the barely distinguishable "Stage Changes" and "Stash Changes" next to each other:

![Screenshot from 2021-03-24 16-03-44](https://user-images.githubusercontent.com/13824553/112395317-61a66580-8cbb-11eb-9cf3-a8bcf4ee178a.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 4.15.0-139-generic

**Comment by eamodio** [comment]
GitLens adds this menu item. You can turn it off: https://github.com/eamodio/vscode-gitlens#menus--toolbars-
