### ISSUE TITLE
Allow to drop windows shortcuts into editor area

### ISSUE THREAD

**Issue by nmbell** [microsoft/vscode#119836]
Issue Type: <b>Bug</b>

Repro steps:
Create a shortcut to a file.
Drag the shortcut to the editor window.

Actual behavior:
Editor shows the following message: "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?". 

Expected behavior:
When dropping a shortcut (.lnk file), the editor should attempt to open the file that the shortcut points to, not the shortcut file itself.

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

**Comment by bpasero** [comment]
As far as I know, there is no way to read a windows shortcut using node.js, but I fail to find an issue for that now.
