### ISSUE TITLE
Settings sync not doing anything after consolidation

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#119805]
I'm on Codespaces and turned on settings sync.
After manually merging the entries and saving locally on Windows, the consolidate button is still not enabled.

<img src="https://user-images.githubusercontent.com/7199958/112343178-1c187700-8c80-11eb-953c-ea1512ea1e50.PNG" alt="Screenshot showing image is not synced" width=300>

**Comment by sandy081** [comment]
Do you see a scroll bar on the entries so that you can scroll down to see for more entries that you can merge? Or try to increase the width of the view and see if there are other entries?

**Comment by rzhao271** [comment]
I just tried it again and it worked this time, though I just accepted local in both cases.
I'll close this for now.
