### ISSUE TITLE
Empty file links are not themeable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#119825]
![image](https://user-images.githubusercontent.com/35271042/112388264-22264c00-8cb0-11eb-8006-c0658be991e7.png)

Compare link color to welcome page on the right

Version: 1.55.0-insider
Commit: 8437d38d364ba93b53c1e659c20b1c86f710ec28
Date: 2021-03-24T08:10:36.007Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by isidorn** [comment]
We use the editor link color to be aligned with what how editor styles links.
So if you compare this link to any other link in the editor I think we are fine.

Anyways let me know what you think, and if you prefer the welcome color let me know the name of that one.

**Comment by misolori** [comment]
Do you have an example of where we use that editor link color? I don't think I've seen it.

**Comment by isidorn** [comment]
Have a link in the editor
Hover over it and hold the `cmd` key

![Screenshot 2021-03-25 at 14 58 10](https://user-images.githubusercontent.com/1926584/112484776-8877a100-8d7a-11eb-9daf-ce720ca20884.png)

**Comment by misolori** [comment]
Ah, ok I see that now. I think because this text isn't style like editor text (it's not monospace) then I think it's better for it to be styled like regular links. Using `textLink.foreground` should work here.

**Comment by isidorn** [comment]
That makes sense. Assigning to April to clean it up then.

**Comment by isidorn** [comment]
![Screenshot 2021-03-29 at 12 56 43](https://user-images.githubusercontent.com/1926584/112827144-3b534200-908e-11eb-9e1b-4ecd436d82cf.png)
