### ISSUE TITLE
Snippet placeholder transform place inversion

### ISSUE THREAD

**Issue by Boulkiess** [microsoft/vscode#119864]
- VS Code Version: 1.54.3 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Write the following code snippet:

```
	"dummy": {
		"scope": "python",
		"prefix": "dummy",
		"body": [
			"${3:${1:Hi} ${2:Mark}}",
			"${3/(.+)/He said ${1} to ${2}/}"
		]
	}
```

2. Test it in a .py file.
3. When entering values to $1 and $2, result is :

```
Hi Mark
He said Hi Mark to 
```

where "He said Hi to Mark" is expected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
There seems to be a misunderstanding. The `${N}` tokens have a different meaning inside transformations. They refer to the capturing group of the regular expression. Your regex only defined one group and there the output is `He said valueOf[(.+)] to`
