### ISSUE TITLE
(F2) Rename does not work

### ISSUE THREAD

**Issue by randym127** [microsoft/vscode#119812]
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Change Typescript version to 2.9,2
2. Try to rename a system (F2), nothing happens.
3. Change Typescript version to 4.2.3
4. rename now works

Moving files also does not fix imports anymore.  

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Closing as it works with the latest TypeScript. Many bugs have been fixed on the TS side since 2.9, so please try updating your workspace to use it (or just don't use the workspace version of TS)

**Comment by randym127** [comment]
> 
> 
> Closing as it works with the latest TypeScript. Many bugs have been fixed on the TS side since 2.9, so please try updating your workspace to use it (or just don't use the workspace version of TS)

So my project/workspace is 2.9.2, I can't just update it to the latest version.  And when I have typscript set to the latest version in vs code I get linting warnings from 4.3.2 changes.  Not a huge deal but sort of sucks I can't use the version of typescript I want to use.
