### ISSUE TITLE
Open Folder dialog doesn't show

### ISSUE THREAD

**Issue by meaning-matters** [microsoft/vscode#119876]
Issue Type: <b>Bug</b>

Open Folder dialog doesn't show!

When trying again error appears: "A file open dialog is already or will be showing for the window with the same configuration"

VS Code version: Code 1.54.3 (Universal) (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id ca2fdfc3-5276-4c8f-a9a3-828b697379e3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.14.4
csharp|ms-|1.23.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30280384
pythontb:30265425
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by isidorn** [comment]
I can not reproduce on my macOS, though this sounds like Electron does not open the native file dialog on your machine.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
