### ISSUE TITLE
Have a max zoom level

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#119890]
I accidentally set zoom level to 9 and it was really hard to do anything in the window. Luckily before the change took effect, I was able to set it to 0. But if I hadn't, I don't think there would've been a way to find the setting to change it based on what I saw briefly at a zoom level of 9.

I think there should probably be a max number, but maybe that's an accessibility issue?

**Comment by bpasero** [comment]
We actually have a max zoom level:

https://github.com/microsoft/vscode/blob/b5b059d2e2b3fe8ff1ca5542b27347284a9fbb2e/src/vs/workbench/electron-sandbox/actions/windowActions.ts#L64

We can reduce it to 8 if needed.
