### ISSUE TITLE
Unable to uninstall vscode

### ISSUE THREAD

**Issue by devanlooches** [microsoft/vscode#119889]
- VS Code Version: 1.54.1
- OS Version: MacOS (Big Sur) 11.2.3

I have tried using app cleaner, I have deleted all relevant VScode directories but it still exists as an app.

Steps to Reproduce:
Install vscode and then try to uninstall.
Then search for the app through spotlight search.

Does this issue occur when all extensions are disabled?: Yes/No
no (command `code` not found)

**Comment by joaomoreno** [comment]
> Then search for the app through spotlight search.

What shows up? Can you share a screenshot? Can you launch it?

**Comment by devanlooches** [comment]
Here is a screenshot of it launched.
![image](https://user-images.githubusercontent.com/50296057/112644549-cae4c080-8e02-11eb-9fb1-f9afb383040a.png)

**Comment by devanlooches** [comment]
It also keeps asking me to install a helper tool.
![image](https://user-images.githubusercontent.com/50296057/112650738-ef439b80-8e08-11eb-806a-3f4c0c89ecc7.png)

**Comment by joaomoreno** [comment]
Just use the search feature in Finder to find VS Code. When you find it, delete it. It's very likely inside your Downloads folder.

**Comment by devanlooches** [comment]
I have tried that and the search doesn't find anything with the name vscode in it.

**Comment by devanlooches** [comment]
I have tried restarting my computer. That doesn't help either.

**Comment by joaomoreno** [comment]
When VS Code is running, right click the Dock icon and choose `Show in Finder`.

**Comment by devanlooches** [comment]
That worked thank you!
