### ISSUE TITLE
Project Explorer display error

### ISSUE THREAD

**Issue by ycjcl868** [microsoft/vscode#119839]
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:57:12.728Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

![image](https://user-images.githubusercontent.com/13595509/112408991-f1f1a400-8cd5-11eb-8878-76deece6606f.png)

I tried `code --disable-gpu`, but not working.

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by IllusionMH** [comment]
/duplicate #106429

Check comments in that issue for possible workaround.
