### ISSUE TITLE
Getting started page shows enable settings sync even when already enabled

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#119896]
Steps to Reproduce:

1. Open getting started page
2. Go through quick setup
3. 🐛  It wants me to enable setting sync, and clicking the button brings up the sign in option even though I already have settings sync enabled.

**Comment by JacksonKearl** [comment]
Is this latest insiders? I saw that yesterday and beleive I fixed it but possibly not.

**Comment by lramos15** [comment]
Yes this is latest insiders.

**Comment by JacksonKearl** [comment]
cc @sandy081 I listen on:

https://github.com/microsoft/vscode/blob/5c6836eb44d676cf7a80df0ba2f1c92c163f21af/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStartedService.ts#L187-L190

 but this seems to not always catch sync being active, do you know a better way to check this?

**Comment by sandy081** [comment]
This should be enough. `IUserDataAutoSyncEnablementService` is the truth for settings sync enablement. Can you repro it from sources?

**Comment by lramos15** [comment]
I can reproduce this sometimes from sources. It seems to be pretty hit or miss with that event.
For example enabling settings sync and then opening the getting started page will show the entry but have it checked. Disabling settings sync and then restarting oss will not unhide the entry. I'm not sure what's going on or what's a good repro for it.

**Comment by sandy081** [comment]
@JacksonKearl I just debugged running from sources and line 187 and line 189 above are getting executed as expected when settings sync is on/off or enabled/disabled.

**Comment by JacksonKearl** [comment]
Okay, interesting. May be that the enablement message gets delivered before the tsk is around to be marked complete.

**Comment by JacksonKearl** [comment]
Going to take this as part of #122570
