### ISSUE TITLE
Add CSS Built-in formatter like HTML and JavaScript

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119877]
Web is all about ( HTML / CSS / JavaScript ) and vscode has built-in formatter for HTML and JavaScript except CSS. It's make sense to have embedded formatter for CSS also because ( HTML / CSS / JavaScript ) they are the kernel of the web. And CSS formatters in extensions section isn't good like built-in HTML and JavaScript formatter from Microsoft.

![image](https://user-images.githubusercontent.com/17777237/112491201-c24fa400-8d88-11eb-84ed-1321dbab429f.png)

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/19166. See https://github.com/microsoft/vscode/issues/19166#issuecomment-409928738 for why we can't cover all functionality for all languages.

> CSS formatters in extensions section isn't good like built-in HTML and JavaScript formatter from Microsoft.

Please consider filing issues against the formatter that you use, so it can improve.

**Comment by pixieaka** [comment]
@aeschli I respect your point. But In my opinion (HTML, CSS and JavaScript/TypeScript) all should be fully supported out of the box.

My question here what's the difference between (HTML, JavaScript/TypeScript) and CSS to include support for one without another? I mean they all main languages and essential for all projects.

Regards.

**Comment by aeschli** [comment]
It's really about sharing the work as maintaining a formatter, investigating and answering all incoming issues is a lot of work.
