### ISSUE TITLE
Allow overwriting mouse events inside the extension.

### ISSUE THREAD

**Issue by ArtemRozovyk** [microsoft/vscode#119867]
Hello, 
Following @sandy081  comment in [`vscode-extension-samples/vim-sample/README.md`](https://github.com/microsoft/vscode-extension-samples/blob/8140d3854c7683ee26c927e2dec58b9a16756502/vim-sample/README.md#typing)

> There are other internal VS Code editor commands (such as those coming in from **mouse operations**) that are not dispatched and cannot be at this time overwritten from an extension. From writing this sample, I haven't found the need to overwrite them, but if you have a use-case where that would make sense, please open an issue on the vscode repo.

I would like to request a way to overwrite mouse events inside the extension. The introduction of  [Custom Editors](https://github.com/microsoft/vscode/issues/77131#issuecomment-611282903) gives us the possibility of viewing documents in all sorts of ways. For instance, my use case is a live abstract syntax tree explorer which looks like following:
![Imgur Image](https://i.imgur.com/Ruar0Gx.gif)

As you can see it is currently possible to treat mouse events one way (from `Webview` to the editor) using  `onDidReceiveMessage`, but it also makes sense to do it the other way, for example: on left click inside the regular editor, reaveal (unfold and focus)  the corresponding `AST` node in the explorer (custom editor) which would simplify the navigation alot in case of large trees.

**Comment by jrieken** [comment]
We have no plans to expose low-level UI gestures in the extension API
