### ISSUE TITLE
Not able to run my c++ code

### ISSUE THREAD

**Issue by amrit2611** [microsoft/vscode#119881]
Issue Type: <b>Performance Issue</b>

minGW has been installed successfully.    path in system variables has been updated.   But my c++ code is not running in vscode.   I am a beginner.   Please help me.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 3092)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.80GB free)|
|Process Argv|--crash-reporter-id 83c51763-7cc2-430a-9996-9a98d3a7f29d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    67	  7288	code main
    0	    22	  4900	   utility
    0	    46	  5828	   window (Issue Reporter)
    0	   173	  6260	   window (tut1.cpp - code - Visual Studio Code)
    0	    93	  2184	     extensionHost
    0	    26	  6432	       "E:\Microsoft VS Code\Code.exe" "e:\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=2184
    0	    17	  7352	       c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.3.0-insiders\bin\cpptools.exe
    0	    11	  4228	         c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.3.0-insiders/bin/cpptools-srv.exe 7352 {768926EF-57E4-4682-A83E-DE338D1F2037}
    0	    11	  4904	     watcherService 
    0	    65	  7004	   shared-process
    0	    25	  6336	     ptyHost
    0	     3	  6420	       winpty-process
    0	    39	  7612	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     4	  7648	       winpty-process
    0	    51	  6256	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     8	  7360	   crashpad-handler
    0	   102	  7816	   gpu-process
    0	   105	  7976	   "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --single-argument https://aka.ms/vcpkg
    0	    14	  3544	     utility
    0	    62	  5296	     gpu-process
    0	    72	  6860	     window (undefined)
    0	     6	  7096	     crashpad-handler
    0	    29	  8084	     utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (tut1.cpp - code - Visual Studio Code)
|    Folder (code): 4 files
|      File types: json(1) cpp(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.3.1
code-runner|for|0.11.3
cpptools|ms-|1.3.0-insiders

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30280383
pythontbcf:30265426
pythonvspyt943:30280189
wslfolderdoc:30280164
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by justinemojal** [comment]
Please see stackoverflow link: https://stackoverflow.com/questions/30269449/how-do-i-set-up-visual-studio-code-to-compile-c-code#:~:text=To%20Build%2Frun%20C%2B%2B%20projects%20in%20VS%20code%2C%20you,press%20enter%2C%20it%20will%20take%20you%20to%20tasks.json
