### ISSUE TITLE
Crash when opening TS file

### ISSUE THREAD

**Issue by mjstelly** [microsoft/vscode#119823]
Issue Type: <b>Bug</b>

Open a typescript file. I received the crash message.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|. --crash-reporter-id 57c8b954-bd5f-48f2-99c5-b8a68419bd26|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.0.1
vscode-apollo|apo|1.18.2
god|bas|0.0.100
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.3.0
vscode-npm-script|eg2|0.3.17
prettier-vscode|esb|6.3.1
relativepathrefactor|jak|0.9.0
atom-keybindings|ms-|3.0.9
vsliveshare|ms-|1.0.4018
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.3
alphabetical-sorter|ue|2.0.1
vscode-js-import|wan|0.15.5
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is the error and stack trace?
