### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by 20anas11** [microsoft/vscode#119814]
Issue Type: <b>Feature Request</b>

VS code ne trouve pas le dossier Git, car il est installé dans mon autre disque dur. Je ne sais pas comment sélectionner le dossier où chercher.
Merci

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.10240

**Comment by trileminh94** [comment]
Translate to english: 

VS code can't find the Git folder because it's installed in my other hard drive. I don't know how to select the folder to search.
Thank you

**Comment by justinemojal** [comment]
Would setting the PATH ENV variable help?

**Comment by eamodio** [comment]
You can either add git to your path or set the `git.path` setting to the location of the git executable
