### ISSUE TITLE
Alternative increments when undoing in cell

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119866]
* have code to monitor the alternative version id of notebooks
* add a cell, undo -> all good ✅, alternative id goes 1 to 0
* type a character in cell, undo -> alternative id goes 1, 2 etc

**Comment by rebornix** [comment]
This one is hard, not sure yet it requires some knowledge of the undo/redo service as the undo happens in text editor.

**Comment by jrieken** [comment]
> not sure yet it requires some knowledge of the undo/redo service as the undo happens in text editor.

Different idea: the alternative id of a notebook could be a "composition" of cell alternative ids and the actual notebook alternative id (without cells).

**Comment by bpasero** [comment]
The file working copy is currently tracking the `versionId` as a increment each time content changes:

https://github.com/microsoft/vscode/blob/91e41167e52c318c6bab9010a66f049f655855c8/src/vs/workbench/services/workingCopy/common/fileWorkingCopy.ts#L771-L771

Every time a save is succesfull it keeps the alternate version ID as "saved version id": 

https://github.com/microsoft/vscode/blob/91e41167e52c318c6bab9010a66f049f655855c8/src/vs/workbench/services/workingCopy/common/fileWorkingCopy.ts#L1098-L1098

Whenever the model content changes, the "saved version id" is compared with the current alternative version id to figure out if the file can be marked as "non dirty":

https://github.com/microsoft/vscode/blob/91e41167e52c318c6bab9010a66f049f655855c8/src/vs/workbench/services/workingCopy/common/fileWorkingCopy.ts#L788-L788

I am honestly not super happy with all of this and happy to change it in any way as we need it, but that is how the text file model works today. It is possible that this concept does not apply so easily for composite editors.

**Comment by jrieken** [comment]
I think a better name would "stateIdentifier" or "stateHash" because it is a unique value that describes a certain state. We can tweak names but the only "real" change would be to change `getAlternativeVersionId()` to return a `string`. With that we can do the combined state identifier of the notebook structure and the cells

**Comment by bpasero** [comment]
@jrieken yes I like that a lot, I can do an API change on the file working copy in debt week

**Comment by bpasero** [comment]
Actually the type of alternate version ID could even be `unknown` as long as I can do a `===` to compare. Not sure what the best type should be.

**Comment by bpasero** [comment]
@jrieken in https://github.com/microsoft/vscode/commit/f4449876e4a9c23b6b45876093e80b57732353b4 2 changes are pushed:
* I renamed `getAlternativeVersionId()` to just `versionId` because the fact that it is "alternative" is an implementation detail of the model. as far as the file working copy cares, it just needs a `versionId` to compare with (the JSDoc tries to make that clear)
* the type changed to `unknown`

I made the adoption in notebook land, let me know if something should change further.

**Comment by rebornix** [comment]
Verifier:

* Change auto save to off
* Open a notebook
* Insert a new cell
* Undo, the dirty indicator should go away
* Type a character in a cell editor
* Undo, the dirty indicator should go away

**Comment by jrieken** [comment]
verified, but there is still an issue with output: https://github.com/microsoft/vscode/issues/121807
