### ISSUE TITLE
Running "Terminal: Attach to session" when there are no sessions dead-ends

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#119803]
Verifying https://github.com/microsoft/vscode/issues/118241

After I no longer had terminal session still around I ran the "Attach to session" command. The quick pick/input stays empty, and gives no indication that anything is happening or that there are no sessions:

![image](https://user-images.githubusercontent.com/38270282/112341769-fb711100-8cc1-11eb-949c-5f3971b052e0.png)

**Comment by meganrogge** [comment]
to verify, in local vscode, run attach to session w no orphaned processes. you should see an informational message that tells you that's what happened and shouldn't see the quick pick.
