### ISSUE TITLE
built-in extension notebook-markdown-extensions doesn't work

### ISSUE THREAD

**Issue by ZhiZe-ZG** [microsoft/vscode#119861]
- VS Code Version: 1.54.3
- OS Version: WIndows 10.0.19042

Steps to Reproduce:

1. Open any markdown file with katex math or emoji. They won't be rendered
2. The source code of this extension seem to provide formula rendering and emoji rendering for markdown. If it's useless, why keep this extension in release edition?
3. At the same time, the naming and description of this plug-in is quite confusing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The new markdown render is experimental and for testing purposes only. You can force enable if with `"notebook.experimental.useMarkdownRenderer": true`. However we only commit to supporting this in the latest VS Code insiders builds, not in stable releases
