### ISSUE TITLE
[Getting Started] Improve positioning for images on large screens

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#119844]
If the images get smaller (in this case too small, just used it for testing) the positioning is awkward.

![image](https://user-images.githubusercontent.com/8599/112418265-616f8f80-8ce6-11eb-9eeb-35bad3fbaebe.png)

@misolori any ideas on general placement fo the images. Your mockups seem to use mostly top-left-aligned, but maybe you can think or other best practices for the CSS positioning and sizing.

**Comment by JacksonKearl** [comment]
Recent improvements here, this is on a big ol' 5k display. 

![image](https://user-images.githubusercontent.com/8586769/114256646-85ca9d80-996f-11eb-9ce7-f408f9da870d.png)

**Comment by JacksonKearl** [comment]
\closedWith b2cc8487aed1a2df99d6b3252670269a93736a56

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/120697074-1dc1a080-c462-11eb-819d-b307813041ab.png)
Images now are anchored to top-right of steps as before
