### ISSUE TITLE
Terminal is keep compiling the project and it is getting hard to view the errors in that loop compilation. Please help me to resolve this ASAP! thanks!

### ISSUE THREAD

**Issue by nvalla304** [microsoft/vscode#119924]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

<img width="785" alt="visual studio bug" src="https://user-images.githubusercontent.com/51371927/112555066-d05bef80-8d9d-11eb-921b-99ebfcefa7b3.PNG">

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it some request for integrated terminal  functionality? If yes then you need to specify problem and expected terminal behavior.

If it's general question - please ask it in appropriate places like Stackoverflow.com . This issue tracker is for VS Code editor itself.
