### ISSUE TITLE
Icon is not visible in the list of applications in Settings in Windows 10

### ISSUE THREAD

**Issue by rakleed** [microsoft/vscode#119927]
Issue Type: <b>Bug</b>

1. Setup VS Code production build on Windows 10
2. Open Settings
3. Go to Apps
4. Go to Apps & features
5. Scroll to VS Code

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) X4 860K Quad Core Processor      (4 x 4189)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.11.0
vscode-language-pack-ru|MS-|1.54.2
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-wsl|ms-|0.54.6
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9

</details>

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/112561620-a37ffa80-8de6-11eb-9597-18ea0ff59ddb.png)

</details>

Most likely, you need to force a more contrasting background color for the icon in the Settings.

**Comment by joaomoreno** [comment]
Looks OK here:

![image](https://user-images.githubusercontent.com/22350/112805690-384c5780-9076-11eb-8936-538b768dbee5.png)

Can you show me how yours looks like?

**Comment by rakleed** [comment]
@joaomoreno In your screenshot, the background almost merges with the image on the left side.

I also attached a screenshot in the original post. And on it you can see that in the original scale the icon is poorly distinguishable from the background.

Can't you just change the background for the icon?

**Comment by joaomoreno** [comment]
I don't think we can, since that's the Windows color you have picked for your system.

**Comment by rakleed** [comment]
@joaomoreno Well UWP apps (installed from Microsoft Store) can change this color. And by default, the accent color is just blue in Windows Settings.

**Comment by joaomoreno** [comment]
We're not UWP unfortunately. Also, I'd say this is a bug on Windows rather than Code. We don't control the number of ways our icon will be displayed. Sorry, but I'm going to have to close this. Feel free to submit an issue to Windows and get some pressure for them to render icons better over there.
