### ISSUE TITLE
Auto compete not working properly with mongoose schema

### ISSUE THREAD

**Issue by zeyad-shaban** [microsoft/vscode#119941]
Why auto complete here is not working correctly? Even tho it used to work in the past

```
const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    username: {
        {ctrl + space should show intellesense with things I can add to mongoose schema like type, required, max, min, etc...}
    }
});
```

but instead, I'm getting completely irrelevant results, vs code doesn't show me the available options I can do in mongoose schema

Node.js related extensions I have: `EsLint` `JavaScript and TypeScript Nightly` <a href="https://marketplace.visualstudio.com/items?itemName=swellaby.node-pack">Node extension pack</a> `npm intellesense` `path intellesense` `REST Client` `Visual studio Intellicode`

(I used WebStorm before and auto-complete there was working fine)

a self-contained project, here it's: https://github.com/zeyad-shaban/node-issue-self-contained-project

My settings.json:
```
{
    "terminal.integrated.shell.osx": "/bin/zsh",
    "workbench.iconTheme": "material-icon-theme",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features",
    },
    "editor.formatOnSave": false,
    "workbench.startupEditor": "none",

    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4,
        "editor.autoIndent": "advanced"
    },
    "git.autofetch": true,
    "explorer.confirmDragAndDrop": false,
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "react-native.packager.port": 19001,
    "terminal.integrated.localEchoLatencyThreshold": 0,
    "javascript.format.semicolons": "insert",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true,
    "editor.suggestSelection": "first",
    "editor.linkedEditing": true,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.tabWidth": 4,
}
```

**Comment by mjbvz** [comment]
/needsMoreInfo

Please share a self contained example that demonstrates the issue (as text)

**Comment by zeyad-shaban** [comment]
Ok I have done it, any further info needed?

**Comment by mjbvz** [comment]
Seems to work for me:

![Screen Shot 2021-04-02 at 3 43 01 PM](https://user-images.githubusercontent.com/12821956/113459351-20ecd180-93ca-11eb-8f2d-bc4f69e3cb0c.png)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by zeyad-shaban** [comment]
Sadly no :(

![Screen Shot 2021-04-04 at 10 40 52 AM](https://user-images.githubusercontent.com/64459068/113503459-4563bd80-9532-11eb-9f05-e9f130755e90.png)

**Comment by mjbvz** [comment]
Until we can repo it, we need more information

Have you disable settings related to JavaScript? Please share a self contained example project that demonstrates the issue

**Comment by zeyad-shaban** [comment]
for a self-contained project here it's: https://github.com/zeyad-shaban/node-issue-self-contained-project
tho I think it's completely unnecessary as I have only one file and it contains all of the code, anyway I will leave the code here

```
const express = require('express')
const app = express()
const mongoose = require('mongoose')


// The Mongoose Stuff

const userSchema = new mongoose.Schema({
    username: {
        // I don't get auto complete for any of those properties
        type: String,
        required: true,
        min: 5,
        max: 25,
        // END
    }
})

// END The Mongoose Stuff




app.get('/', (req, res) => {
    res.send("Hello World")
})

app.listen(5000)

// This is not my way of writing code neither comments :)
```

here is my settings.json that can cause this issue (please note that I deleted everything, restarted vs code and the issue was still there

```
{
    "terminal.integrated.shell.osx": "/bin/zsh",
    "workbench.iconTheme": "material-icon-theme",
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features",
    },
    "editor.formatOnSave": false,
    "workbench.startupEditor": "none",

    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4,
        "editor.autoIndent": "advanced"
    },
    "git.autofetch": true,
    "explorer.confirmDragAndDrop": false,
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "react-native.packager.port": 19001,
    "terminal.integrated.localEchoLatencyThreshold": 0,
    "javascript.format.semicolons": "insert",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "[jsonc]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "files.autoSave": "afterDelay",
    "files.trimTrailingWhitespace": true,
    "editor.suggestSelection": "first",
    "editor.linkedEditing": true,
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "prettier.tabWidth": 4,
}
```


Any info else needed?

**Comment by zeyad-shaban** [comment]
Can this issue occur due to my OS?

**Comment by zeyad-shaban** [comment]
Will you ever fix this issue?! It has been 13 days!

I'm closing this issue cuz I got tired of opening Github every day to check if the problem got solved! Bye vscode I guess
