### ISSUE TITLE
Wasted screen real estate in bottom panel if "Test: Python" tab is added

### ISSUE THREAD

**Issue by StefanBrand** [microsoft/vscode#119948]
Issue Type: <b>Bug</b>

When I drag the "Test: Python" tab into the bottom panel, not all tabs are shown anymore. There is plenty of space though and I'd like to have all tabs displayed.

![image](https://user-images.githubusercontent.com/8948865/112624705-3e4ff780-8e2e-11eb-8780-90cae8c60e26.png)

When I remove the tab again, everything is back to normal:

![image](https://user-images.githubusercontent.com/8948865/112624853-6dfeff80-8e2e-11eb-86d3-aa3d10dd2b49.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-48-generic snap
Remote OS version: Linux x64 5.8.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2357)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.30GB (0.74GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 9f44f085-df3c-48bc-ac0c-65e0090f6a3e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: <container>|
|OS|Linux x64 5.8.0-48-generic|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2357)|
|Memory (System)|15.30GB (0.74GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.2
vscode-pytest|Cam|0.1.1
gitlens|eam|11.3.0
goto-next-previous-member|mis|0.0.5
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.3
jupyter|ms-|2021.3.684299474
vscode-status-bar-format-toggle|tom|2.0.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@StefanBrand, we have pushed a fix around this behavior in the latest insiders. Can you confirm if it still exists https://code.visualstudio.com/insiders/?

cc @sandy081 as I believe you pushed the recent fix.

**Comment by sandy081** [comment]
My recent change was about fixing missing `...` action. I was looking for steps to repro this issue so that I can fix it

https://github.com/microsoft/vscode/issues/116423

**Comment by StefanBrand** [comment]
Just tried it out and looks good in insider build! :)
