### ISSUE TITLE
Code doesn't execute

### ISSUE THREAD

**Issue by zekgt** [microsoft/vscode#119965]
Issue Type: <b>Bug</b>

when i press play button on upper right, it will not execute, instead it will print this "PS C:\Users\LENOVO\Desktop\python scripts xd programmer> & c:/users/lenovo/python38/python.exe "c:/Users/LENOVO/Desktop/python scripts xd programmer/main.py""

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 4300U with Radeon Graphics          (4 x 2695)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.37GB (0.38GB free)|
|Process Argv|--crash-reporter-id 0f2a31df-80a2-40e7-af4e-b4fc9f9ca6f5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
lua|sum|1.19.1
tabnine-vscode|Tab|3.2.13

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
vspre833:30267464
vshan820cf:30276953

```

</details>

**Comment by chrmarti** [comment]
@jrieken Is this on our or the extension side? (Assuming you're involved on our side.)

**Comment by jrieken** [comment]
I'd say extension side

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
