### ISSUE TITLE
Mouse response sluggish in the text editor with higher DPI mouse

### ISSUE THREAD

**Issue by alegrigoriev** [microsoft/vscode#119922]
- VS Code Version: 1.54.3
- OS Version: Windows 10 10.0.19042

Steps to Reproduce:

1. Have a high DPI mouse. I'm using Jelly Comb Ergonomic BueTooth/2.4GHz mouse model MV045. I'm working on 4K TV monitor, 30 fps.
2. I'm working on a AC-powered laptop, so CPU throttling doesn't seem an issue.
3. Open any code file. I'm working with Python, although the issue is still noticeable with a plaintext file.
4. Move the mouse in the text editor. You will notice that the cursor movement lags noticeably behind the physical movement. It does quite impair the pointing precision, because it really breaks visual feedback. Very aggravating.
5. The  mouse (described above) has a DPI switch. When switched to lower dpi, the lag is reduced, but then mouse needs very wide movement.
6. Lower DPI mouse (for example low end Dell wireless mouse) doesn't suffer from this.
7. Other software, such as Visual Studio, doesn't suffer from such lag.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alegrigoriev** [comment]
To add: Mouse movement in other panels, such as file list or git changed file list, doesn't seem to lag.

**Comment by alexdima** [comment]
@alegrigoriev Could you please record a screen capture of the problem, that might help me understand the problem better. Do you use `editor.cursorSmoothCaretAnimation` ?
