### ISSUE TITLE
Support pasting of images from clipboard in markdown cells of Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119961]
@randomuserrr commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5321)

**when i want to insert local image into a cell nothing happens :(**

Extension version: 2021.5.685944597
VS Code version: Code - Insiders 1.55.0-insider (6ebe2a14f3722bc2582ecd8108d0a71dfdd46036, 2021-03-25T16:25:06.257Z)
OS version: Windows_NT x64 10.0.19042

---

@DonJayamanne commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5321#issuecomment-807867161)

Thanks for filing this issue, please could you provide some steps on what you have tried and what you mean by inserting local image? I.e. steps for us to be able to repro this issue.

---

@randomuserrr commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5321#issuecomment-807932068)

I took a screenshot and want to insert an image via ctrl + v.  this works in jypiter notebook but doesn't work in vscode

**Comment by rebornix** [comment]
This is what's inserted into the cell when pasting.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/876920/112682235-11e7ab80-8e2d-11eb-8e37-03401d9256fc.png">

It's a generic request for pasting images in markdown editor but can also be a special paste handler for notebook.

**Comment by randomuserrr** [comment]
> This is what's inserted into the cell when pasting.
> 
> <img alt="image" width="452" src="https://user-images.githubusercontent.com/876920/112682235-11e7ab80-8e2d-11eb-8e37-03401d9256fc.png">
> 
> It's a generic request for pasting images in markdown editor but can also be a special paste handler for notebook.

now i have a new problem. the image is not displayed
![image](https://user-images.githubusercontent.com/63656568/112691593-99193b80-8e8e-11eb-82ae-bf3f9537cdd3.png)

**Comment by mjbvz** [comment]
This probably falls under #30066

instead of implementing a notebook specific solution, it would be great if our markdown language features supported this in any markdown files

**Comment by jucor** [comment]
Would be extremely helpful, I have been using it all the time in JupyterLab to paste content from multiple sources: tables with classnames for datasets, tables with required format from the end-user of the data, etc etc. Quite handicapping not having it!
Thanks for considering :)

**Comment by greazer** [comment]
This request has been referenced in the Jupyter extension's marketplace review on 4/11/2022.

**Comment by mariandumitrascu** [comment]
This would be such a great addition. Copy/pasting images from clipboard is the only thing that makes me switch some times to JupyterLab from VSCode.

**Comment by mjbvz** [comment]
Once we expose an api for copy/paste, this should be handled by Jupyter (I'll leave it up to you if this means our built-in simple extension or by the full one)

**Comment by rchiodo** [comment]
I believe @amunger was looking at this this month.

**Comment by DonJayamanne** [comment]
Rendering pasted images in Jupyter Notebook markdown cells will be blocked on https://github.com/microsoft/vscode/issues/121256

**Comment by Yoyokrazy** [comment]
Pasting images from the clipboard into a markdown cell is released! It requires enabling the following two settings:
```
"ipynb.experimental.pasteImages.enabled": true,
"editor.experimental.pasteActions.enabled": true,
```
