### ISSUE TITLE
🚔 copy-paste police: gettingStarted.ts and walkthrough.ts should share code

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#119946]
<img width="1071" alt="Screenshot 2021-03-26 at 11 13 17" src="https://user-images.githubusercontent.com/1794099/112616655-486cf880-8e24-11eb-9b1d-2843b0695c9c.png">

**Comment by JacksonKearl** [comment]
Yes, walkthroughs is a snapshot of getting started from earlier this iteration before we overhauled getting started to look like welcome. Definite debt item here as we figure out more of the story.
