### ISSUE TITLE
Insider new welcome page| Prevent close all tabs in the same time

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119911]
- VS Code Version: 1.55.0 Insider 6ebe2a1
- OS Version: Windows 10 20H2 Build 19042.572

Should prevent close on click for selected tab, Because Isn't make sense to show photo on the right side and all tabs are closed at the same time.

![2](https://user-images.githubusercontent.com/17777237/112540126-7a497500-8dba-11eb-8ef7-b06e6494d6ba.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
I think this changed when keyboard a11y was improved, we should be able to still respect that and just enforce 1 visible element.

**Comment by JacksonKearl** [comment]
@Tyriar added because you reported it was odd for Enter on an item to not do anything. The alternative suggested at the time was to trigger the button's action instead, though now that we're planning on allowing multiple buttons per item I'm not sure what a good action for the button should be.

**Comment by Tyriar** [comment]
@JacksonKearl yeah you're right.

What if instead the item expands on focus (click or tab) and enter doesn't toggle visibility at all? So track the active item and switch it whenever focus changes (`:focus` + `:focus-within`?). As for what enter should do if we did that, maybe move focus to the first button if it exists?

**Comment by JacksonKearl** [comment]
Changed a bit ago so that clicking will now toggle the item's completion. Tried having triggering the button move focus to the first inner button but it felt strange to click on one area and have a different area focused.
