### ISSUE TITLE
Projects search "match whole word" ignores language-specific editor.wordSeparators 

### ISSUE THREAD

**Issue by maxrothman** [microsoft/vscode#119906]
- VS Code Version: 1.54.3
- OS Version: Mac OS 10.15.7

Steps to Reproduce:

1. Create a file with the `.clj` that contains the string "foo-bar"
2. Add the following to your settings (notice no hyphen in the string!):
    ```
    "[clojure]": {
        "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?"
    }
    ```
3. In the sidebar, click "Search", enable "Match whole word", and search for the string "foo"

### Expected behavior
The string "foo" is not matched because it is not a whole word

### Actual behavior
The string "foo" is matched, it seems that the search treats "-" as a word separator

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
It's not really possible for us to apply language-specific options to search, which is language-agnostic. The global wordSeparators setting should probably be applied, but isn't currently: https://github.com/microsoft/vscode/issues/27280
