### ISSUE TITLE
Auto Attach not working

### ISSUE THREAD

**Issue by govindrai** [microsoft/vscode#119986]
Issue Type: <b>Bug</b>

Set Auto Attach: Always
Ensure Auto Attach: Always appears in status bar
create node.js module called greet.js
```javascript
function greet() {
    console.log("hello");
}

greet();
```
put a breakpoint on line 2.
Run node script in Javascript Debug Terminal via node greet.js

program runs through without debugger attaching.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (1.38GB free)|
|Process Argv|--disable-extensions --crash-reporter-id db7f3e56-f6f4-4f30-9b91-8b22930c271a|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontbcf:30265426
wslfolderdoc:30280164
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by weinand** [comment]
your program is too short. It has terminated before the debugger had a chance to attach.

**Comment by govindrai** [comment]
@weinand is there a way to auto attach and wait until the debugger is connected (i.e. `node --inspect-brk`)?

**Comment by connor4312** [comment]
What version of Node.js are you using? Can you echo the `NODE_OPTIONS` environment variable in your terminal to see if and what value it has?

**Comment by govindrai** [comment]
v14.16.0 and --max_old_space_size=8196

**Comment by connor4312** [comment]
Okay, I see. It looks like you probably have something in your .bashrc/.zshrc file which is overwriting NODE_OPTIONS, with `export NODE_OPTIONS=--max_old_space_size=8196`. I suggest changing that to:

```
export NODE_OPTIONS="$NODE_OPTIONS --max_old_space_size=8196
```

in order to preserve the options we set that enable auto attach to work.
