### ISSUE TITLE
Test explorer momentarily thinks it'll run all the tests

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#119902]
Testing https://github.com/microsoft/vscode/issues/117633

1. Open the test explorer
2. Go to a file with tests
3. Run the `Run Tests in Current File` command
4. 🐛 For an instant, it seems the test explorer is about to test everything

![recording (10)](https://user-images.githubusercontent.com/7199958/112524073-a59d7700-8d5c-11eb-9a83-50f113990a5e.gif)

**Comment by connor4312** [comment]
I'm not able to repro this, can you confirm you're on the latest Insiders and extension version?

![](https://memes.peet.io/img/21-03-bf4010ec-ad49-4f3d-a849-41872b11cae7.png)

**Comment by rzhao271** [comment]
I'm using the latest https://github.com/microsoft/vscode-selfhost-test-provider on the main branch
My Insiders is up to date:

Version : 1.55.0-insider (user setup)
Commit : 6ebe2a14f3722bc2582ecd8108d0a71dfdd46036
Date : 2021-03-25T16:25:06.257Z

**Comment by connor4312** [comment]
I believe I fixed this issue, though I never repro'd it. Let me know if you see it again on or after the next Insiders tomorrow.
