### ISSUE TITLE
can not enable inline change for git repo on remote ssh servers.

### ISSUE THREAD

**Issue by liqilei** [microsoft/vscode#119928]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. can not enable inline change for git repo on remote ssh servers. Can not see the colour bar (green or red). But I can see it in my local environment. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by liqilei** [comment]
I found this problem was caused by symbolic link. i.e. ln -s

**Comment by lszomoru** [comment]
Closing as duplicate of https://github.com/microsoft/vscode/issues/5970.
