### ISSUE TITLE
Support Hovers and IntelliSense in search editor

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#119917]
I just started experimenting with search editors again after a few false starts where I just wasn't seeing the value in the feature yet. This time, I got far enough to actually think it has real promise, but I was surprised by how limited the editor was compared with an actual code editor (in my case, the JS/TS editor).

The first example I came across is not being able to hover a TypeScript type to see its definition. I soon also noticed the lack of intellisense and red error squiggles (is there an official name for these?). I'm sure there are other examples.

These deficiencies really limit the usefulness of the search editor. The particular use case that led me to submit this request was that I was trying to verify the return type of a bunch functions throughout my codebase. Not being able to just interrogate the type right in the search editor added a lot of clicks and made the process a lot more tedious than it could have been.

(I would also add that having to learn about and install "Search Editor: Apply Changes" is not ideal, but I think I saw that a more integrated, discoverable solution is in the works.)

So, my feature request is to make the search editor behave like a regular code editor, to the extent possible.

**Comment by JacksonKearl** [comment]
Hovers and Intellisense should be doable without too much trouble, the squiggles unfortunately would be a much larger ask. I'll scope this to just those two.

**Comment by devuxer** [comment]
@JacksonKearl , That would be a great start. Thank you!
