### ISSUE TITLE
VS code freezes on RHEL since the latest update (RHEL 'yum' repository)

### ISSUE THREAD

**Issue by hrishikeshkale4** [microsoft/vscode#119931]
I am working on a university computer cluster (with linux installed) where VS Code is installed through a RHEL 'yum' repository however, since the last update that was around March 13 - 16 2021 VS code is not working on Red hat linux and it freezes on opening and the only option is to forcefully quit. 

Could you please help me solve this issue ?

**Comment by rkeithhill** [comment]
I've updated to 1.54.3 on two RH machines (7.5 and 7.6) and VSCode starts but is completely unresponsive on both machines.  This is, to say the least, a major problem for those of us on RHEL7.
