### ISSUE TITLE
Python doesn't close after closing VSCode

### ISSUE THREAD

**Issue by mmattbtw** [microsoft/vscode#119934]
<img width="357" alt="Screen Shot 2021-03-25 at 11 28 26 PM" src="https://user-images.githubusercontent.com/30363562/112577144-cea42300-8dc1-11eb-9a42-bcc092a8c83c.png">

- VS Code Version: 1.54.3

- OS Version: macOS Big Sur 11.2.3

- M1 MacBook Air (16 GB RAM)

Steps to Reproduce:

1. Open a Python file
2. Debug it
3. Close VSCode (Cmd+Q)
4. Open Activity Monitor
5. Python is still there.

Does this issue occur when all extensions are disabled?: Yes

**Comment by laimaretto** [comment]
Same here. Using Ubuntu 20.04. Had to uninstall the Python extension in order to free CPU usage. Same symptoms as shown in here: python kept on running on jedi-language-server.
