### ISSUE TITLE
Keeping code navigation in one window only

### ISSUE THREAD

**Issue by VilhoRaatikka** [microsoft/vscode#119963]
I use C and typically use two vertical windows, and often navigate back and forth through call graphs by jumping into symbol definitions (F12) and then jump back and forth in the code (ctrl+alt+-/ctrl+shift+-).

What would be really helpful if navigation would occur only in the window it is started. As a consequence, the other window(s) would remain as they were. And often contents of other window(s) have meaning as a context for the work. 

So for example, jumping to a definition would happen in the same window instead of switching to one of the other windows.

Regards

Vilho Raatikka

**Comment by IllusionMH** [comment]
Do you mean Editor Groups when you say "two vertical windows"?

Setting `workbench.editor.revealIfOpen` to `false` should give result you are describing.

**Comment by VilhoRaatikka** [comment]
Hi, I guess that's what it is. I've split the window to two columns from
view->editor layout->split:two columns. Tried, and it seemed to work.

Many thanks!

Vilho Raatikka
