### ISSUE TITLE
Allow to "Save as..." workspace after making modifications without altering the current workspace

### ISSUE THREAD

**Issue by quadans** [microsoft/vscode#119953]
- VS Code Version: 1.54.3
- OS Version: latest windows 10

Steps to Reproduce:

1. File -> Save Workspace As...  any name
2. Change Workspace by adding or deleting any folder
3. Save again like in Step 1 with any other name
4. Open any of the two workspace and you will see it doesnt load the workspace, instead the latest workspace is open.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by quadans** [comment]
![recording](https://user-images.githubusercontent.com/47493031/112657007-415cdf00-8e52-11eb-87f4-1b40bc830bdd.gif)
Here is the gif.
As you can see, if using "save workspace as..." doesnt do anything. The files it saves doesnt restore anything, just the latest used workspace.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by quadans** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I downloaded and installed it. The same thing. Did the exact same thing as in the gif above.

**Comment by bpasero** [comment]
I cannot reproduce:

![recording](https://user-images.githubusercontent.com/900690/112717651-64d56780-8eee-11eb-9d0b-d43ed85b1a86.gif)

My steps:
* start from an empty folder
* save workspace as `1.code-workspace`
* add folder `test-ts`
* save workspace as `2.code-workspace?
* add folder `test-js`
* remove folder `test-ts`

=> ✅  I can open each workspace individually and the correct folders restore

**Comment by quadans** [comment]
I did many tests now. It seems that the workspace saves itself automatically after each change. 
So if you work on Workspace A, "Save as Workspace..." with the Name B,   A and B are equal.
I have to manually change one of the Workspace and override the Workspacefile A or B.
Autosave seems to be the culprit. 
So I googled and found this [on stackoverflow](https://stackoverflow.com/questions/52130236/how-do-i-disable-visual-studio-code-auto-save/54779045#:~:text=To%20edit%20your%20Workspace%20settings,vscode%20folder%20of%20your%20solution.&text=Vscode%20version%201.34%20onwards%20just,to%20enable%20or%20disable%20Autosave.)
But for me it is already turned off. So, the question is how to really turn off auto save function of workspace directory changes?

**Comment by quadans** [comment]
Here you can see the only solution is to work with 3 workspaces to have 2 usable workspace. Autosaving makes this problem is my guess.
![recording](https://user-images.githubusercontent.com/47493031/112719251-53915880-8ef8-11eb-951e-bcd1eac764b5.gif)

**Comment by quadans** [comment]
And here is the proof
![recording (1)](https://user-images.githubusercontent.com/47493031/112719577-db2b9700-8ef9-11eb-87e1-6bdcb6e9a34a.gif)

If you delete the latest workspace, you can not save an empty workspace, because it is depending on the last one.

**Comment by bpasero** [comment]
@quadans I cannot follow. anytime you add or remove a folder to the workspace, the workspace file is saved, anything else would be very confusing imho. And when you "Save Workspace As...", the workspace gets duplicated.

I feel there is no issue here, rather a question.

**Comment by quadans** [comment]
If you use "Save Workspace as..." you want the older saved workspace file to be unaffected. I dont know a single program which does it, because it makes no sense.

**Comment by bpasero** [comment]
@quadans I agree with you for the example you provide, but how does that relate to the VSCode workspace file? The VSCode workspace file is never "dirty", any change you do is immediately saved to disk. Anytime you add/remove a folder the file is saved directly.

I do not really understand what the ask here is, are you suggesting a workspace file should become dirty when you add/remove folders and you must save it?

**Comment by quadans** [comment]
I dont really understand what you mean with dirty, but

> The VSCode workspace file is never "dirty", any change you do is immediately saved to disk. Anytime you add/remove a folder the file is saved directly.

So in other words, autosave! Yes, Any change should only be saved if you manually save it, why otherwise? You see the problem it causes, you cannot create a second workspace without affecting the first one.

**Comment by quadans** [comment]
The solution seems to be by starting off with "Save Workspace As...", giving it a name, and then changing the workspace as desired. In oppose to change the workspace and saving it in the end.
