### ISSUE TITLE
CSS in custom renderer messes up markdown rendering

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#119971]
- VS Code Version: 1.55.0-insiders
- OS Version:  Darwin x64 19.6.0

Steps to Reproduce:
1. Use the yeoman generator to create a Notebook or use the Notebook here: https://github.com/tanhakabir/vscode-notebooks-demo at branch `complete`
2. Verify/Make the renderer render a list
3. Verify/Make the css of the list have a weird font
4. Run the Notebook in Extension Host
5. Create a markdown cell with a list
6. See that your css change for lists in the renderer was also applied to the list in the markdown

![recording (23)](https://user-images.githubusercontent.com/12758612/112666560-8c0e3500-8e19-11eb-8e82-11b10c9c5bad.gif)

**Comment by rebornix** [comment]
Output css bleeds to markdown ;(

**Comment by mjbvz** [comment]
The markdown output or the renderer output likely need to live inside a Shadow DOM. This is not specific to markdown either since an I believe an output renderer could set: `body { background: red; }` and effect the entire page
