### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Tert0** [microsoft/vscode#119914]
Issue Type: <b>Performance Issue</b>

VS Code Needs a lot of RAM

VS Code version: Code - OSS 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-12T19:27:39.374Z)
OS version: Linux x64 5.11.5-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|7.44GB (0.81GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (Dashboard - Unbenannt (Arbeitsbereich) - Code - OSS)
|    Folder (frontend): 43 files
|      File types: vue(8) ts(5) xml(4) json(3) js(2) browserslistrc(1) env(1)
|                  gitignore(1) iml(1) md(1)
|      Conf files: package.json(1) tsconfig.json(1)
|    Folder (Frontend.old.angular): 82 files
|      File types: ts(29) html(10) scss(10) json(8) js(2) browserslistrc(1)
|                  editorconfig(1) gitignore(1) md(1) gitkeep(1)
|      Conf files: tsconfig.json(2) package.json(1) tslint.json(1)
|    Folder (Bot): 6828 files
|      File types: py(2687) pyc(2678) txt(89) so(48) h(31) exe(22) LICENSE(17)
|                  rst(15) pyi(13) hash(11)
|      Conf files: makefile(2);
```

</details>
<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.8
vscode-django|bat|1.4.0
markdown-preview-github-styles|bie|0.1.6
dart-code|Dar|3.20.1
flutter|Dar|3.20.0
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.24.0
svg|joc|1.4.1
Angular2|joh|11.0.0
vscode-styled-components|jpo|1.5.0
kite|kit|0.142.0
unity-code-snippets|kle|1.3.0
vscode-github|Kni|0.30.5
Angular-BeastCode|Mik|10.0.3
vscode-language-pack-de|MS-|1.54.2
python|ms-|2020.10.332292344
vscode-typescript-tslint-plugin|ms-|1.2.2
vsliveshare|ms-|1.0.3121
debugger-for-chrome|msj|4.12.6
vetur|oct|0.33.1
vscode-yaml|red|0.17.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
tabnine-vscode|Tab|3.2.9

</details>

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Performance-Issues for advice on how you can make this report more valuable.

**Comment by Tert0** [comment]
Thanks I'll do that later but at the moment it doen't need a lot of RAM
