### ISSUE TITLE
cmd-shift-left/right triggers focusRightEditor warning

### ISSUE THREAD

**Issue by jefffriesen** [Microsoft/vscode#11991]
- VSCode Version:
1.5.2

- OS Version:
OS X 10.11.6

Steps to Reproduce:

1. Put your cursor in middle of text. Hit cmd-shift-left or cmd-shift-right with the intention of selecting it. This triggers the error: Command workbench.action.focusLeftEditor has been removed. You can use workbench.action.focusPreviousGroup instead

This is system-wide OS X default keybinding (I just realized how much I use now that it's broken). It even works in this textarea as I type this.

**Comment by bpasero** [comment]
@jefffriesen can you share your keybindings JSON file?

**Comment by jefffriesen** [comment]
@bpasero You just asked the right question. I had copied keybindings from this repo: https://github.com/waderyan/vscode-atom-keybindings/blob/master/package.json#L59

I deleted those and it works fine now. Thanks and sorry about the trouble
