### ISSUE TITLE
Improve logging when pty messages reach pty host for terminals that no longer exist

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#119989]
Instead of throwing here which shows up in tests and is expected to happen:

https://github.com/microsoft/vscode/blob/31f8118486d8dfbd8acb836f2552db3d39c3b2f0/src/vs/platform/terminal/node/ptyService.ts#L219

We should catch it, and log something along the lines of this when the pty has shutdown (we could track shutdown ids in a `Set`):

> "received message for pty id "x" which is shutdown"

**Comment by meganrogge** [comment]
@Tyriar  is thinking:

- The pty is shutdown (by recording what _lastPtyId is when PtyService is created, > that and <= the current value)
- The pty belonged to another pty host (if it's <= _lastPtyId's original value)
- Bad ID (<= 0 || > current _lastPtyId)

**Comment by meganrogge** [comment]
Consider adding  `(could throw pty error)` to the test suite description

**Comment by Tyriar** [comment]
Decided to just no-op the shutdown one since that's the main problem case. This way we will still throw when we expect the pty to be alive.
