### ISSUE TITLE
Powershell Write-Host/Output/Warning/Debug problem

### ISSUE THREAD

**Issue by szotyii** [Microsoft/vscode#11993]
- VSCode Version: 1.5.2
- OS Version: Windows 8.1 Ent x64

Powershell Write-Host/Output/Warning/Debug command not writing, only just Write-Error

Steps to Reproduce:
1. Create *.ps1 file
2. Add command Write-Host "SOMETHING"
3. Press F5 and it's not writing out anything.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
