### ISSUE TITLE
Cursor Shifts to left side of editor automatically

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#119957]
- VS Code Version: 
- OS Version: MacOS Big Sur 11.2.3

Steps to Reproduce:

1. Run VSCode with multiple files.
2. When I change files and move from one to another.
3. I see that the cursor is back to the leftmost side of the editor on that specific line it was.
4. Disabling extensions did not help.

Please assist its pretty annoying.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by iaxat** [comment]
VS code version: 1.54.3

**Comment by alexdima** [comment]
@iaxat Can you please provide more clear steps, like e.g. "open file1.txt", "open file2.txt", etc. I think perhaps you are doing a certain pattern that might trigger an issue. I tried switching files, but the cursor remains at its correct stop for me.

**Comment by iaxat** [comment]
Sure, the thing is that the files are under the network drives attached to the computer using Rclone.

**Comment by alexdima** [comment]
@iaxat I have modified our FS provider sample from https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample to make the file reading really slow (always takes >5s). However, I could not reproduce any problem with the cursor position. The cursor position is restored to where it was when the file was closed:


https://user-images.githubusercontent.com/5047891/120894469-cb76b000-c618-11eb-8abb-f775209c765a.mp4
