### ISSUE TITLE
ArgumentOutOfRangeException clicando em "Run"

### ISSUE THREAD

**Issue by manoel-lopes** [microsoft/vscode#119958]
Últimas 132 Chaves:
 t s - n o d e Space " c : \ U s e r s \ m a n o e l \ D o c u m e n t s \ G i t H u b \ I m p l e m e n t a t i o n s \ d a t a - s t r u c t u r e s - a n d - a l g o r i t h m s \ T y p e S c r i p t \ d a t a - s t r u c t u r e s \ s t a c k \ i n d e x . t s " Enter

Exceção:
System.ArgumentOutOfRangeException: O valor deve ser maior ou igual a zero e menor que o tamanho do buffer do console nessa dimensão.
Nome do parâmetro: left
Valor real era -1.
   em System.Console.SetCursorPosition(Int32 left, Int32 top)
   em Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   em Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   em Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   em Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   em Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   em Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   em Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by chrmarti** [comment]
Duplicate of https://github.com/PowerShell/PSReadLine/issues/863.
