### ISSUE TITLE
Python interpreter in Debug Tests configuraion marked as not allowed

### ISSUE THREAD

**Issue by pauloneves** [microsoft/vscode#119903]
We have written the ne
Issue Type: <b>Bug</b>

When I have this configuration in my launch.json file

```
        {
            "name": "Debug Tests",
            "type": "python",
            "request": "test",
            "console": "integratedTerminal",
            "python": "${command:python.interpreterPath}",
            "justMyCode": true
        }
   
```

VSCode complains in the PROBLEMS tab:

Launch.json:
Property python is not allowed.

or in more detail:

{
	"resource": "/c:/dev/api-ckan-pda/.vscode/launch.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Property python is not allowed.",
	"startLineNumber": 21,
	"startColumn": 13,
	"endLineNumber": 21,
	"endColumn": 21
}

If I change the property to "pythonPath" it does not complain anymore, but also the debugging does not work anymore.

I have other python configuration (not the Debug Tests) that has a python property and it does not complains:

        {
            "name": "Python: Arquivo Atual",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "python": "${command:python.interpreterPath}",
            "cwd": "${fileDirname}"
        },

T

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (0.81GB free)|
|Process Argv|--crash-reporter-id bd96bacd-8f73-4ab2-8bf6-5e9fb781a8f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gitlens|eam|11.3.0
vscode-firefox-debug|fir|2.9.2
restructuredtext|lex|146.0.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.2
jupyter|ms-|2021.3.619093157
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
shellcheck|tim|0.14.0
vscodeintellicode|Vis|1.2.12
markdown-all-in-one|yzh|3.4.0

</details>
eded data into your clipboard because it was too large to send. Please paste.

**Comment by pauloneves** [comment]
![the annoying message](https://user-images.githubusercontent.com/221084/112525769-fe323b80-8d7f-11eb-8a32-a4ba7b1625eb.png)

Here is the annoying message

**Comment by weinand** [comment]
@pauloneves the property "request" has an incorrect value "test". Correct values are "launch" or "attach".

**Comment by pauloneves** [comment]
This is the recommended configuration for [python tests debugging](https://code.visualstudio.com/docs/python/testing#_debug-tests) and the error is in another line. 

Screenshot from link above:
