### ISSUE TITLE
CTRL-SHIFT-F doesn't work; takes me to a completely different application minimized in my tray.

### ISSUE THREAD

**Issue by pranavsharma** [microsoft/vscode#119995]
- VS Code Version: 1.54.3
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open any code folder and type CTRL-SHIFT-F
2. Doing so takes me to a completely different application minimized in my tray.

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/2732907/112702488-e24a9a80-8e50-11eb-983b-457908229f9d.png)

**Comment by Tyriar** [comment]
The other application is probably intercepting the hotkey before VS Code can handle it.

**Comment by roblourens** [comment]
You probably need to fix this in configuration for the OS or the other application
