### ISSUE TITLE
Chrome debugger extension - debugger always stops in main.js for Angular 10 project

### ISSUE THREAD

**Issue by politicsruinseverything** [microsoft/vscode#119909]
If this is not the right forum I apologize. I could not find a chrome debugger forum that was open to posts. 

Using "ng serve" to serve my project code on port 4200, I launch my Chrome debugger using Run - Start Debugging in VS Code 1.54.3. 
Other software:
Chrome 87.0.4280.141. 
Node.js 12.18.3. 
Windows 10 (10.0.17134). 
Electron 11.3.0. 
V8: 8.7.220.31-electron.0

The code always stops on line main.js:4002 which contains this code only:
/**/ }),

There is no breakpoint set on this line. There are no breakpoints set in main.ts. There are no breakpoints listed in the Run/Debug sidebar. There are no breakpoints set in Chrome's F12 console.

I've tried editing my main.ts file and adding / removing carriage returns just to "touch" the file. This seemed to get the code to execute one time without hitting the breakpoint but I was unable to reproduce this behavior. Prior to a few days ago, this was not happening. However, many months ago it did happen. I do not recall what made it stop.

If anyone knows why this happens and if anything can be done to reset it short of something drastic like reinstalling VS Code, Chrome, or heaven-forbid Windows, I'd appreciate learning about it. This is super annoying when developing and debugging a sizable application. Thanks a bunch.

**Comment by politicsruinseverything** [comment]
After examining the trace log, there is a lot of personal information in there, namely urls with querystring params for my local organization. Do you have any suggestions for scrubbing these files before uploading? I do not want to be the guy who uploaded sensitive information and ends up on the 5 o'clock news :)

**Comment by connor4312** [comment]
You can unzip the file to text, and then remove or redact the sensitive parts. Alternately, if you can create a small sample repo where this problem happens, that would also work well 🙂

**Comment by politicsruinseverything** [comment]
I think it would be impossible to repro since it involves some sort of unique circumstance under which it happens. But I will eliminate any personal info and re-zip. Thanks for the fast response!

**Comment by politicsruinseverything** [comment]
I attached the trace file.

To restate what I am experiencing, during the launch of the Angular application, the code breaks on line 4010 of main.js. This is the last line of a section that looks like this:

```
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony default export */ __webpack_exports__["default"] = ("<div class=.........
/***/ }),   <-- this is line 4010

```
Other info:
Line 4008 is enormous. It is so long that VS Code will not even render the end of the line if I put my cursor on it and press END. The cursor just disappears somewhere. 

When I press F5 to allow the app to continue to load, then clear the debug console and re-load the browser page, these are the only three debug lines that are printed before the 4008/4010 breakpoint is hit:

```
Could not read source map for chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/commons.js: Unexpected 503 response from chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/commons.js.map: Unsupported protocol "chrome-extension:"
Could not read source map for chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/timestampManager.js: Unexpected 503 response from chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/timestampManager.js.map: Unsupported protocol "chrome-extension:"
Could not read source map for chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/documentStartIndex.js: Unexpected 503 response from chrome-extension://olpofapmbejnopkdjkdejhomgkbbdojd/documentStartIndex.js.map: Unsupported protocol "chrome-extension:"
```


[vscode-debugadapter-b30f9523.gz](https://github.com/microsoft/vscode/files/6213952/vscode-debugadapter-b30f9523.gz)

**Comment by connor4312** [comment]
Thanks for the log. In there I'm not seeing an "stopped" events which is what is sent to signal to VS Code that it's paused on a line. Did those get removed? Without them it's hard to see where the issue is happening.

**Comment by politicsruinseverything** [comment]
I don't think so unless those same lines would have a url on them. What is the search string I can look for? I will look at the original log text.

Also, the extension that is throwing the 503 errors is something called WalkMe. It apparently lets IT support monitor or overlay information onto the browser window. I'd like to remove it but I don't think I can. It's odd that it was just added to my computer in the last couple of weeks. This sort of corresponds to the time I started fighting this break issue.

**Comment by politicsruinseverything** [comment]
Maybe this will help. While the code was frozen at the "breakpoint", I decoded the trace file. These are the last four lines while VSCode is waiting on me to press F5 (continue):

```
{"tag":"cdp.receive","timestamp":1616789869475,"metadata":{"connectionId":0,"message":{"id":1368,"result":{"result":[]},"sessionId":"7E51AB92BE538C9A20C32396EE200EFA"}},"level":0}
{"tag":"cdp.receive","timestamp":1616789869476,"metadata":{"connectionId":0,"message":{"id":1369,"result":{"result":[{"name":"module","value":{"type":"object","className":"Object","description":"Object","objectId":"5225363507310389409.2.52","preview":{"type":"object","description":"Object","overflow":false,"properties":[{"name":"i","type":"string","value":"C9SC"},{"name":"l","type":"boolean","value":"false"},{"name":"exports","type":"object","value":"Module"}]}},"writable":true,"configurable":true,"enumerable":true,"isOwn":true},{"name":"__webpack_exports__","value":{"type":"object","className":"Module","description":"Module","objectId":"5225363507310389409.2.53","preview":{"type":"object","description":"Module","overflow":false,"properties":[{"name":"default","type":"string","value":"<div class=\"content-container\" id=\"top\">\n    <nav …nConfirmed($event)\"></confirmation-dialog>\n</div>"},{"name":"__esModule","type":"boolean","value":"true"},{"name":"Symbol(Symbol.toStringTag)","type":"string","value":"Module"}]}},"writable":true,"configurable":true,"enumerable":true,"isOwn":true},{"name":"__webpack_require__","value":{"type":"function","className":"Function","description":"function __webpack_require__(moduleId) {\n/******/\n/******/ \t\t// Check if module is in cache\n/******/ \t\tif(installedModules[moduleId]) {\n/******/ \t\t\treturn installedModules[moduleId].exports;\n/******/ \t\t}\n/******/ \t\t// Create a new module (and put it into the cache)\n/******/ \t\tvar module = installedModules[moduleId] = {\n/******/ \t\t\ti: moduleId,\n/******/ \t\t\tl: false,\n/******/ \t\t\texports: {}\n/******/ \t\t};\n/******/\n/******/ \t\t// Execute the module function\n/******/ \t\tmodules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\n/******/\n/******/ \t\t// Flag the module as loaded\n/******/ \t\tmodule.l = true;\n/******/\n/******/ \t\t// Return the exports of the module\n/******/ \t\treturn module.exports;\n/******/ \t}","objectId":"5225363507310389409.2.54"},"writable":true,"configurable":true,"enumerable":true,"isOwn":true}]},"sessionId":"7E51AB92BE538C9A20C32396EE200EFA"}},"level":0}
{"tag":"dap.send","timestamp":1616789869479,"metadata":{"connectionId":1,"message":{"seq":1927,"type":"response","request_seq":31,"command":"variables","success":true,"body":{"variables":[{"name":"module","value":"{i: 'C9SC', l: false, exports: Module}","evaluateName":"module","type":"object","variablesReference":3},{"name":"__webpack_exports__","value":"Module {default: '<div class=\"content-container\" id=\"top\">\\n   …irmed($event)\"></confirmation-dialog>\\n</div>', __esModule: true, Symbol(Symbol.toStringTag): 'Module'}","evaluateName":"__webpack_exports__","type":"object","variablesReference":4},{"name":"__webpack_require__","value":"ƒ __webpack_require__(moduleId) {\\n/******/\\n/******/ \\t\\t// Check if module is in cache\\n/******/ \\t\\tif(installedModules[moduleId]) {\\n/******/ \\t\\t\\treturn installedModules[moduleId].exports;\\n/******/ \\t\\t}\\n/******/ \\t\\t// Create a new module (and put it into the cache)\\n/******/ \\t\\tvar module = installedModules[moduleId] = {\\n/******/ \\t\\t\\ti: moduleId,\\n/******/ \\t\\t\\tl: false,\\n/******/ \\t\\t\\texports: {}\\n/******/ \\t\\t};\\n/******/\\n/******/ \\t\\t// Execute the module function\\n/******/ \\t\\tmodules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\\n/******/\\n/******/ \\t\\t// Flag the module as loaded\\n/******/ \\t\\tmodule.l = true;\\n/******/\\n/******/ \\t\\t// Return the exports of the module\\n/******/ \\t\\treturn module.exports;\\n/******/ \\t}","evaluateName":"__webpack_require__","type":"function","variablesReference":5},{"name":"this","value":"Module","evaluateName":"this","type":"object","variablesReference":6},{"name":"Return value","value":"undefined","evaluateName":"Return value","type":"undefined","variablesReference":0}]}}},"level":0}
{"tag":"dap.send","timestamp":1616789872308,"metadata":{"connectionId":1,"message":{"seq":1928,"type":"event","event":"output","body":{"category":"telemetry","output":"js-debug/dap/operation","data":{"errors":[],"breakpointLocations":{"operation":"breakpointLocations","totalTime":2.9,"max":2.9,"avg":2.9,"stddev":null,"count":1,"failed":0},"!breakpointLocations.errors":[],"threads":{"operation":"threads","totalTime":0.7,"max":0.7,"avg":0.7,"stddev":null,"count":1,"failed":0},"!threads.errors":[],"stackTrace":{"operation":"stackTrace","totalTime":16.8,"max":15.7,"avg":8.4,"stddev":10.3,"count":2,"failed":0},"!stackTrace.errors":[],"source":{"operation":"source","totalTime":95.6,"max":95.6,"avg":95.6,"stddev":null,"count":1,"failed":0},"!source.errors":[],"scopes":{"operation":"scopes","totalTime":25.5,"max":25.5,"avg":25.5,"stddev":null,"count":1,"failed":0},"!scopes.errors":[],"variables":{"operation":"variables","totalTime":7.6,"max":7.6,"avg":7.6,"stddev":null,"count":1,"failed":0},"!variables.errors":[]}}}},"level":0}

```

**Comment by politicsruinseverything** [comment]
Okay, I figured out what was causing it. One of the breakpoints in my list on the sidebar was considered "unbound" even though when I clicked on it, it took me to one of my Angular html templates (line 22 or whatever). When I disabled this unbound breakpoint, the app ran fine without stopping. When I re-enabled it, it stopped the app in main.js. So it appears that the VSCode debugger will stop when there's an unbound breakpoint. It also appears this is not being reflected in the trace.

**Comment by connor4312** [comment]
It's hard for me to tell what's happening with the limited info/logs.

It is by design that the debugger pauses when evaluating scripts with sourcemaps, but it should then unpause after parsing the sourcemap. However stopping in an html template would indicate to me that something else is also problematic with your sourcemaps, which _could cause us to remain paused (if a breakpoint evaluates to the currently-paused position).

**Comment by politicsruinseverything** [comment]
Interesting. Since the "ng serve" command is responsible for doing a debug compile and presumable providing any source maps for a template / component, I'm not sure what could be happening there. Those are some deep weeds I've never wander into :)  

For testing purposes, it may be possible to create an "unbound breakpoint" (maybe by putting a breakpoint on a line of an html template and then replacing that line with, say, just a carriage return) and recreate a condition that causes VSCode to break and fail to resume. If so, I suppose the VSCode team would have to decide what to do about that scenario.

Anyway, I'll try it and see what happens.

**Comment by politicsruinseverything** [comment]
Sure enough, it seems easy enough to reproduce the scenario. Stackblitz usually takes me forever to set up an example so, while I try to do that, here's all I think you'd need to see this happen.

Make an Angular 2+ component that is not involved in the startup of the app or on the main page in any way. In the HTML, put these three lines and set a breakpoint on the second one:

```
<div *ngIf="myVariable===true">
  {{myVariable}}  <-- set breakpoint on this line
</div>
```

After saving, start "ng serve". Start the VSCode debugger which should try to load the app. If you have a breakpoint listed as "unbound" for this component (clearly it should not be considered unbound since it is in the template), you should see VSCode stop in main.js before it even tries to display anything.
