### ISSUE TITLE
Open Editor closing everything

### ISSUE THREAD

**Issue by R4DD** [microsoft/vscode#119901]
Issue Type: <b>Bug</b>

This may be intended, but while working in a folder using the 'open folder' or 'add folder to workspace', opening any singular file not associated with the folder(s) I've open will close all open workspaces and folders forcing me to open or add them again

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (26.58GB free)|
|Process Argv|--crash-reporter-id 1cacfab9-39ab-4a22-8a70-88279ee7bd98|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
prettify-json|moh|0.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vsget980:30279783
vspre833cf:30267465
vsdfh931:30280409
vshan820cf:30276953

```

</details>

**Comment by isidorn** [comment]
I believe this is as designed. Can you please post a short video, or a more precise repro steps so we are sure?
