### ISSUE TITLE
Debug output vanished

### ISSUE THREAD

**Issue by RakeshMalik-42** [microsoft/vscode#119991]
Issue Type: <b>Bug</b>

While debugging some Node.js code, between runs, the console output ceased. I have not been able to find out why, but now the Logger.info() and Console.log() messages that used to print to the debug console suddenly don't. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 1997)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (1.03GB free)|
|Process Argv|--crash-reporter-id 5cb021b0-2201-4f5c-bc27-56e547c90e4b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19
code-runner|for|0.11.3
vscode-cfn-lint|kdd|0.18.0
csharpextensions|kre|1.3.6
node-module-intellisense|lei|1.5.0
nodejs-repl|los|0.5.15
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-wsl|ms-|0.54.6
vsliveshare|ms-|1.0.4018
vscode-yaml|red|0.17.0
scala|sca|0.5.2
shader|sle|1.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
openwsldoc:30280162
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by connor4312** [comment]
Please provide an example for us to reproduce with. Thanks!
