### ISSUE TITLE
`Reopen Editor With...` picks wrong notebook editor

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#119954]
Verifying  #115631

Version: 1.55.0-insider
Commit: 6ebe2a14f3722bc2582ecd8108d0a71dfdd46036
Date: 2021-03-25T16:24:13.227Z

 - clone https://github.com/microsoft/vscode-markdown-notebook and open in vscode 
 - add a `console.log('openContext', openContext);` to `openNotebook`
 - F5 to run the extension
 - Open an untitled file
 - In the editor's tab, choose `Reopen Editor With...` from the context menu, pick `Markdown Notebook`
 
![image](https://user-images.githubusercontent.com/6461412/112644058-49fae880-8e45-11eb-8b28-d3d8de45d980.png)

- a different notebook is opened, no console log statement printed
![image](https://user-images.githubusercontent.com/6461412/112644117-5b43f500-8e45-11eb-91f0-7301e8a1713c.png)

**Comment by lramos15** [comment]
@aeschli Are you able to open markdown notebooks without issue on non untitled files?

**Comment by aeschli** [comment]
@lramos15 Yes, that works. 

I also tried to open a GitHub issue notebook on an untitled file and while an notebook seems to open, the `openNotebook` function is never reached. So I'm quite confused.

**Comment by lramos15** [comment]
@rebornix I did some investigation with this and I can't reproduce it out of sources. When I select it through the reopen with dialog the `NotebookEditorService` receives the correct viewtype, although it always fails to open with the error `Unable to open 'Untitled-1': NO provider registered for view type: 'notebookCoreTest'.`. I'm not sure why it is failing as the inputs get created correctly and everything seems to be passing through the right way. Let me know if you want to investigate together.
