### ISSUE TITLE
Pressing Command + = doesn't increase the font size

### ISSUE THREAD

**Issue by ketakahashi** [Microsoft/vscode#11995]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Creating a new file
2. Pressing Command + Shift + - doesn't makes the font size increasing but decreasing.

**Comment by octref** [comment]
`Cmd + Shift + -` defaults to decrease the font size. You can see the default keybindings in `Code -> Preferences -> Keyboard Shortcuts`.

Here is the relevant bit:

```
{ "key": "shift+cmd+=",           "command": "workbench.action.zoomIn" },
{ "key": "cmd+=",                 "command": "workbench.action.zoomIn" },
{ "key": "shift+cmd+-",           "command": "workbench.action.zoomOut" },
{ "key": "cmd+-",                 "command": "workbench.action.zoomOut" },
```

But in the title you said you pressed `Cmd + =`. Which key exactly did you press?

**Comment by ketakahashi** [comment]
I see. It's my misunderstanding. I press Cmd+Shift+- keys because I usually do so when I see Cmd+= on the menu...How can I input '=' just press a key?

**Comment by ketakahashi** [comment]
By using the keyboard with numeric keypad which has '=' key, I could do zoom-in operation. But I usually use the keyboard with no numeric one. I edited keybindings.json like "cmd+shift+;". Thank you for your information.

**Comment by octref** [comment]
Cmd + plus sign = bigger font
Cmd + minus sign = smaller font

**Comment by octref** [comment]
@ketakahashi 
By the way, do you have a different keyboard layout? I guess you are using Japanese layout?

Here is how it looks on my keyboard.

![image](https://cloud.githubusercontent.com/assets/4033249/18499481/30e3c6ec-79f4-11e6-89ef-18a5a498bdd3.png)

**Comment by ketakahashi** [comment]
@octref Yes, I use JIS layout keyboard. It looks like below. I see from your picture that's why there is no problem with - and = keys. The keys are adjacent with US layout.

![2016-09-14 17 40 52](https://cloud.githubusercontent.com/assets/449141/18505534/a8103904-7aa2-11e6-8a61-d7e4197cbd8b.png)
