### ISSUE TITLE
Editor scrolls several lines up each time a button is pressed

### ISSUE THREAD

**Issue by KolyaIvankov** [microsoft/vscode#119955]
Issue Type: <b>Bug</b>

The editor scrolls several lines up in a .cs file whenever a stroke of text or Delete/Backspace is pressed. The behavior ceases when OmniSharp extension is disabled or uninstalled and does not occur in .cpp or .html files. The behaviour kicks in as soon as a part of code recognized as erroneous (even if it is not).

The issue was reported to OmniSharp (https://github.com/OmniSharp/omnisharp-vscode/issues/4451), but OmniSharp developers deny their responsibility, claim vscode to be responsible, and have closed the issue. Restoring default settings, reinstallation of vscode, reinstallation of OmniSharp (including previous versions of OmniSharp) do not mitigate the issue. 

This issue has previously been reported (https://github.com/microsoft/vscode/issues/119493), closed as caused by extension, reported to OmniSharp and - as indicated - blamed on vscode by OmniSharp developers.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.21GB free)|
|Process Argv|--crash-reporter-id de5def01-989b-41de-ab17-25d5ebdcc01d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
godot-tools|gee|1.1.2
vscode-mesh-viewer|mic|0.0.10
vscode-language-pack-de|MS-|1.54.2
csharp|ms-|1.23.9
cpptools|ms-|1.2.2
mono-debug|ms-|0.16.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30280383
vspre833cf:30267465
vshan820cf:30276953

```

</details>

**Comment by alexdima** [comment]
@KolyaIvankov I have seen this before in https://github.com/microsoft/vscode/issues/113384 , but I could not reproduce. Could you perhaps give some minimal sample that reproduces for you? What are your settings? Does this reproduce when commenting out all your `editor.*` specific settings in your `settings.json` ?
