### ISSUE TITLE
Additional surrounding pairs for markdown

### ISSUE THREAD

**Issue by jasper-zanjani** [microsoft/vscode#119982]
Currently, the Markdown [language configuration](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/language-configuration.json) supports surround with parentheses `(` `)`, square brackets `[` `]`, backtick, underscore, and asterisk.

Selection surround support should also be extended to curly brace `{` `}`, single quote `'`, and double quote `"`.

I can certainly fork and make a PR myself if that is all that's needed.

Suggested:
```json
	"surroundingPairs": [
		["(", ")"],
		["[", "]"],
		["`", "`"],
		["_", "_"],
		["*", "*"],
                ["{", "}"],
                ["'"],
                ["\""]
	],
```
I'm submitting here after submitting [#924](https://github.com/yzhang-gh/vscode-markdown/issues/924) on the [yzhang-gh/vscode-markdown](https://github.com/yzhang-gh/vscode-markdown/) extension and being informed this upstream change is needed.

**Comment by leemun1** [comment]
@jasper-zanjani 
Hello, are you already working on a PR for this issue? If not, is it okay If I go ahead and take a stab at it?

**Comment by jasper-zanjani** [comment]
Yes please do
