### ISSUE TITLE
Cannot edit markdown files after opening a moderately large text file

### ISSUE THREAD

**Issue by uber6** [microsoft/vscode#119925]
Issue Type: <b>Bug</b>

I had several .md files open for edit. And if I open a text file (~500k - 2m in size) while editing .md files, a lot of special keys on the keyboard (enter, backspace, del, space, etc) stop working. Only solution to this is to close vscode completely and opening again, and never opening the text file. It used to work fine in the past, but suddenly started to happen recently. I have not installed/removed any extensions in past 4 weeks or so.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (45.03GB free)|
|Process Argv|--crash-reporter-id 4fa35b3c-33d7-4775-a717-bca151c8dd1d|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
regex|chr|0.4.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
docs-markdown|doc|0.2.85
python-extension-pack|don|1.6.0
foam-vscode|foa|0.12.0
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.24.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.3
jupyter|ms-|2021.3.684299474
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.4018
vscode-print|pdc|0.9.2
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.2.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by uber6** [comment]
Tried with all extension disabled. Haven't tried with insider version. I'll get back to you when I try, but it works fine on Linux vs code.

**Comment by mjbvz** [comment]
Please test with insiders too
