### ISSUE TITLE
Notebook sometimes covers bottom panel

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#119951]
- VS Code Version: 1.55.0-insider (6ebe2a14f3722bc2582ecd8108d0a71dfdd46036)
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Open a notebook
2. Reload the window
3. 🐛 The notebook briefly covers the bottom panel tabs

Sometimes, especially on opening a new VS code window for the first time with a notebook being restored, the notebook will not resize and remain covering the bottom panel until I do a resize on the bottom panel. 

Here's a gif to show you what I see, notice the bottom panel tabs.

![recording](https://user-images.githubusercontent.com/4544166/112641676-f83c6900-8e18-11eb-8340-6ef6fc9a2c86.gif)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/119910, https://github.com/microsoft/vscode/issues/119923 which I thought was fixed.

**Comment by lramos15** [comment]
Looks like the newest insiders released just 14 minutes ago with the fix for that issue let me test it.

**Comment by lramos15** [comment]
Fixed in the latest insiders 😄
