### ISSUE TITLE
[folding] make the folded code notifier more noticeable (like in VS) 

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#119969]
In my opinion, the folding code indicator is inconspicuous, it can be hard to notice. The vs code has an editor.foldingHighlight parameter, but I don't really like highlighting the entire line. I propose to make the folding code indicator more noticeable.

Vs code
![image](https://user-images.githubusercontent.com/75433721/112665949-32941d80-8e8e-11eb-8c77-550ec4928c03.png)

Visual studio 2017
![image](https://user-images.githubusercontent.com/75433721/112666102-6111f880-8e8e-11eb-8657-50cdaa75e029.png)

**Comment by aeschli** [comment]
We could easy add the box around. The content inside `{ ... }` is harder we would need this information from the folding provider.

**Comment by AlexDev2020** [comment]
> The content inside `{ ... }`

**Comment by AlexDev2020** [comment]
I apologize for accidentally closing the task.

**Comment by AlexDev2020** [comment]
> We could easy add the box around. The content inside `{ ... }` is harder we would need this information from the folding provider.

If it is possible to implement it like in Visual studio 2017, then that would be cool.

If you have problems with adding content inside `{...}`, then you can try something else to improve  folding code indicator. Сan try increasing the size of '...', add a  box around, which, in my opinion, is better than selecting the entire line. Do you have any suggestions for solving this problem?
