### ISSUE TITLE
Clearer UI indicators for native notebooks cell edit mode

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#119912]
@joyceerhl commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5306)

Was just in a QP where a customer who is accustomed to Jupyter notebooks keyboard shortcuts was trying to use the `b` keyboard shortcut to insert a cell below the current cell and didn't realize that he had the cell in edit mode. Once he pressed the esc key to select the cell, the `b` shortcut worked, but I needed to point it out for him to notice the difference.

**Comment by claudiaregio** [comment]
I find myself running into this issue quite often as well :( I like using light themes but its really hard to see the super thin lines that indicate edit mode vs command mode. I end up squinting at my screen to figure out where I am in the notebook

**Comment by claudiaregio** [comment]
+1 customer feedback 
![image](https://user-images.githubusercontent.com/19276747/119209248-6f2d6100-ba5a-11eb-9e7e-51b3ccc3e4ba.png)

**Comment by claudiaregio** [comment]
+1 customer feedback
![image](https://user-images.githubusercontent.com/19276747/119209294-b3b8fc80-ba5a-11eb-95c5-07f0a0f067c0.png)

**Comment by claudiaregio** [comment]
+1 customer feedback
![image](https://user-images.githubusercontent.com/19276747/119881913-a8465500-bee2-11eb-98d4-e3d4af0b0191.png)

**Comment by rebornix** [comment]
Maybe we can introduce a active cell editor background color.

**Comment by misolori** [comment]
Adding comparisons to other notebooks:

## VS Code
<img width="536" alt="CleanShot 2021-11-04 at 22 25 15@2x" src="https://user-images.githubusercontent.com/35271042/140462607-4f4f6bd3-69bc-4cff-b4fe-7c20b26e87a8.png">
<img width="519" alt="CleanShot 2021-11-04 at 22 25 50@2x" src="https://user-images.githubusercontent.com/35271042/140462640-bb3e86fd-7fc5-47df-ba8b-bb2ff926b320.png">



## Jupyter Lab
<img width="593" alt="CleanShot 2021-11-04 at 22 22 49@2x" src="https://user-images.githubusercontent.com/35271042/140462386-c3975d85-c21d-499f-baaf-9cafe32814b5.png">
<img width="570" alt="CleanShot 2021-11-04 at 22 23 00@2x" src="https://user-images.githubusercontent.com/35271042/140462406-ccb23374-1782-4a3f-87d5-25a80e8976c3.png">

## Colab
<img width="560" alt="CleanShot 2021-11-04 at 22 23 28@2x" src="https://user-images.githubusercontent.com/35271042/140462459-6a0f7c13-4580-4e14-adf2-22357a160483.png">
<img width="646" alt="CleanShot 2021-11-04 at 22 23 39@2x" src="https://user-images.githubusercontent.com/35271042/140462471-700dc1bc-85e3-4c6d-b204-69c878015173.png">
