### ISSUE TITLE
Certain characters inside the file corrupt new filenames

### ISSUE THREAD

**Issue by domino14** [microsoft/vscode#119933]
- VS Code Version: 1.54.3
- OS Version: Mac OS Big Sur 11.2.3

Steps to Reproduce:

1. `echo -e "\xe2\x80\x8c" | pbcopy` in your terminal, which will copy a weird unprintable character into your clipboard
2. Open a new VS Code file and paste the contents of your clipboard
3. Command + S to save the file, and enter a printable filename (for example `wtf.txt`)
4. `ls` in your computer's terminal. The filename will look like `?wtf.txt`. I didn't insert any extra characters to the filename myself. Trying to tab-auto-complete the filename doesn't work at all.

Does this issue occur when all extensions are disabled?: Yes

**Comment by meganrogge** [comment]
I can't reproduce this issue. 
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
