### ISSUE TITLE
VSCode wraps files with disabled "Word Wrap" setting 

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119947]
VS Code Version: 1.55.0 Insider 6ebe2a1
OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

**With "Word Wrap" setting is off**

![image](https://user-images.githubusercontent.com/17777237/112619157-a8b56780-8e2f-11eb-9a58-70976bd5fa3e.png)

**Every time any '.min' file is gets opened vscode wrap the entire file**

![image](https://user-images.githubusercontent.com/17777237/112619306-d69aac00-8e2f-11eb-8228-b9052d0eb9f3.png)

**And user should press toggle wrap option every time after opens these kind of files to display these files right**

![image](https://user-images.githubusercontent.com/17777237/112619475-0d70c200-8e30-11eb-91df-f748f18141fb.png)
![image](https://user-images.githubusercontent.com/17777237/112619560-26797300-8e30-11eb-80c7-5243e80803ba.png)

**And vscode didn't remember word wrap toggle setting. Can this option added to settings and vscode respect this option value?**

----------

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
This is basically a workaround for https://github.com/microsoft/vscode/issues/7772

Basically, if a file is opened and more than 50% of its content lies on lines with the length > 10k, then the file is considered "minified". These files get word wrapping turned on (even if `settings.json` defines word wrapping to be off) and word wrapping can be toggled off only using the action. In this particular case, the action also renders in the editor action bar.

We could add an editor option to opt out of this behavior.
