### ISSUE TITLE
Insider Getting Started| Image can be drag and it's not aligned to center horizontally

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#119964]
- VS Code Version: 1.55.0 Insider d06d2f1d6245ce00b1c36a9cd81a9087d225173e
- OS Version: Windows 10 20H2 Build 19042.572

Problems:
1. Image not aligned to center horizontally
2. Image can be drag

![3](https://user-images.githubusercontent.com/17777237/112657507-2c387e00-8e5b-11eb-8afd-3258cc68d47d.gif)

![image](https://user-images.githubusercontent.com/17777237/112658279-efb95200-8e5b-11eb-89a9-9ccde791bcc0.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
The dragging is a bit odd, cc @misolori for the alignment, I think that's expected?

**Comment by pixieaka** [comment]
@JacksonKearl  I think alignment photos center vertically will be much better to match entire page experience.

**Comment by pixieaka** [comment]
@JacksonKearl  I think if photos aligned center vertically will be much better to match entire page experience.

**Comment by misolori** [comment]
I don't think it was that intentional, we assumed most images would take up the entire space. We could center it though, would make smaller images look better:

![image](https://user-images.githubusercontent.com/35271042/112680873-29259980-8e2b-11eb-9135-5b76dff63b82.png)

In terms of making it horizontally centered, it actually is centered. Here's an example that highlights the same margin applies on all sides:

![image](https://user-images.githubusercontent.com/35271042/112681032-5f631900-8e2b-11eb-975d-c2574b9fb442.png)

**Comment by pixieaka** [comment]
@misolori Is it better to move "Show welcome page on startup" checkbox to the bottom of the page and replace text to "Show getting started page on startup"

![image](https://user-images.githubusercontent.com/17777237/112691286-c44b5d00-8e85-11eb-9bad-bd7310e8becf.png)

**Comment by JacksonKearl** [comment]
This page will be renamed to welcome page :)

**Comment by pixieaka** [comment]
@JacksonKearl  Oh sorry I didn't know that. But if this checkbox move to the bottom it's will be better in my opinion.

**Comment by JacksonKearl** [comment]
Now looks something like this:
![image](https://user-images.githubusercontent.com/8586769/114256274-10f66400-996d-11eb-886d-af2111b5b9a7.png)

**Comment by pixieaka** [comment]
@JacksonKearl  Insider 01466cf692c3e54f0eeb82ef0539a42391f185de

Weird margin at top.

![image](https://user-images.githubusercontent.com/17777237/114399773-96625a00-9ba1-11eb-9c2c-b35f215a7e73.png)

But works fine in main view

![image](https://user-images.githubusercontent.com/17777237/114399880-b265fb80-9ba1-11eb-97d4-934adfec978d.png)

**Comment by JacksonKearl** [comment]
This is the grid layout: 
![image](https://user-images.githubusercontent.com/8586769/114417625-9bee7e80-9b66-11eb-8a7d-a41a60b8a5e6.png)

Generally optimizing keeping things steady as the image size changes and the length of the list changes, if the image positioning depends on the length of the content (as is the case if it's to be centered vertically against the left column), things look really weird. Similarly, if different aspect ratio images cause the whole page to shift left and right, things also look weird. If you have suggestions for changes under those constraints I'm happy to hear them

**Comment by pixieaka** [comment]
@JacksonKearl

### Current insider
![Untitled](https://user-images.githubusercontent.com/17777237/114443798-67aea880-9bce-11eb-94c9-6de51a403873.png)

### Previous insider
The problem was in image align vertically here, but this get worse in all aspects in the latest insider

![Untitled2](https://user-images.githubusercontent.com/17777237/114444342-0affbd80-9bcf-11eb-98f9-35b1931c2fbd.png)

**Comment by JacksonKearl** [comment]
Hm, I agree it can be aligned a bit better in the large case, I was focusing more on the narrow case. Still some work needed there too.

**Comment by pixieaka** [comment]
@JacksonKearl The secret here in symmetric aspects because the image size may change and the length of the list may change too.

**Comment by JacksonKearl** [comment]
I'm not sure what you mean there - if the margins on both sides of the content are the same, the content must shift around as it's own size changes. If however the top and left margins are fixed, the content will remain stationary as its own size changes. I'd prefer the content to be a bit off-center but fixed in place than perfectly centered but shifting around as different sections are selected.

**Comment by pixieaka** [comment]
@JacksonKearl I agree 👍 Thanks for the clarification.

**Comment by JacksonKearl** [comment]
Pushed a new change, should look a bit nicer.

**Comment by pixieaka** [comment]
@JacksonKearl In my opinion it's still looks messy and needs another retouch.
- The margin under `more` link it's huge and useless.
- Photos should has minimum dimension rules to be accepted [ width / height ] to unify all pages theme.
- The margin after `Editing evolved` it's to small compare to the margin under `more` link in my first point. But this page looks perfect beside that.

![image](https://user-images.githubusercontent.com/17777237/115945808-a0e3f400-a4bd-11eb-9d6d-091e78017a53.png)

![image](https://user-images.githubusercontent.com/17777237/115945955-7181b700-a4be-11eb-8ce8-009410df9119.png)
