### ISSUE TITLE
Stop icon in Notebook Editor title bar doesn't go away after cell has completed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#119921]
Version: 1.55.0-insider
Commit: 6ebe2a14f3722bc2582ecd8108d0a71dfdd46036
Date: 2021-03-25T16:23:16.288Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Install Jupyter Extension
2. Create a cell and run the cell
3. Wait for cell to complete execution
4. The status of cell has changed back to `play` icon, but on the editor title bar, the `stop` button is still visible

@roblourens @rebornix /cc

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
I can reproduce this issue by

* Create an empty Jupyter notebook
* Run a cell
* Before it connects the kernel (jupyter kernel) / finishes execution, cancel
* The Stop button in the cell turns into Run button again, the Stop button on the editor toolbar doesn't go away.

**Comment by roblourens** [comment]
Pushed a fix that adds a lightweight new property to the cell vm state change event that says whether the run state changed.

Also considered

- Rechecking all cells in the document to avoid counting issues - too expensive
- A more generic diff of metadata with list of changed props - too expensive

Can consider whether we want something more general purpose for metadata here. Or, this is another case for not storing run info in internal metadata
