### ISSUE TITLE
support to pass arguments to debug adapters

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1199]
I would like to configure debug adapters to run in trace mode.
Since passing a trace flag from the launch config would be too late, I would like to be able to configure command line arguments in the package.json of a debug extension.

**Comment by daviwil** [comment]
I need this as well since my debug adapter has a '/waitForDebugger' flag so I can debug my debugger :)

**Comment by isidorn** [comment]
Andre I just verified this does not break anything, but did not verify the arguments get nicely passed to the debugger - can you just verify that please.

**Comment by daviwil** [comment]
My debug adapter configuration uses `program` instead of `runtime` and it looks like this change only passes along arguments for adapters using `runtime`.  Is that the case?  Here's my configuration:

```json
				"type": "PowerShell",
				"enableBreakpointsFor": { "languageIds": ["powershell"] },
				"program": "bin/Microsoft.PowerShell.EditorServices.Host.DebugAdapter.cmd",
```

I'd like for it to be:

```json
				"type": "PowerShell",
				"enableBreakpointsFor": { "languageIds": ["powershell"] },
				"program": "bin/Microsoft.PowerShell.EditorServices.Host.exe",
				"args": ["/debugAdapter"]
```

I currently have to use a .cmd file to pass along the `/debugAdapter` parameter to my host process.

**Comment by isidorn** [comment]
The change is intended to pass both. So your case should work, checkout 
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/rawDebugSession.ts#L284

**Comment by daviwil** [comment]
Cool!  I think I was misunderstanding the Promise flow there but it makes sense now.  Thanks!

**Comment by isidorn** [comment]
Yeah I should simplify that..
