### ISSUE TITLE
Keep dirty contents when renaming a dirty file or its parent

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#11997]
- VSCode Version: 1.5.2
- OS Version: OS X

Steps to Reproduce:
1.  Make a new file
2. Type some content in it
3. While it's still dirty rename the file on the sidebar

Content of the file is lost.

**Comment by bpasero** [comment]
@mohsen1 are you not seeing this warning?

<img width="464" alt="screen shot 2016-09-14 at 07 00 13" src="https://cloud.githubusercontent.com/assets/900690/18500578/ec7413cc-7a48-11e6-980b-294fa1e81b6c.png">

**Comment by mohsen1** [comment]
I see the dialog but why you can't keep the files content?

**Comment by bpasero** [comment]
@mohsen1 fair request, this was done to fix many issues when deleting a folder that contains dirty files. In this case we could maybe be smarter.

**Comment by bpasero** [comment]
In 1.9 you can move or rename files or parent folders that contain dirty state. The dirty state will be preserved after the operation. Note that unfortunately currently the undo stack is not preserved, this is something we still have to look into (https://github.com/Microsoft/vscode/issues/7536).
