### ISSUE TITLE
Polymorphic this (TS 1.7)

### ISSUE THREAD

**Issue by tomlarkworthy** [Microsoft/vscode#120]
is not accepted as valid TS. See https://github.com/Microsoft/TypeScript/pull/4910

**Comment by bpasero** [comment]
@tomlarkworthy for this to work you will need to set the `typescript.tsdk` property (in preferences) to a 1.7 TS version. Are you doing that?

**Comment by tomlarkworthy** [comment]
No I was not! Thanks, it all works!

**Comment by bpasero** [comment]
Great
