### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by sayfelanjos** [microsoft/vscode#120061]
Issue Type: <b>Bug</b>

My terminal not able open shell bash.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.0-70-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200G with Radeon Vega Graphics (4 x 1615)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 1, 2|
|Memory (System)|5.73GB (0.73GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id eff21fd9-45e5-4315-a5a9-7ced0db4b365|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.3.1
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.3
jupyter|ms-|2021.3.684299474
cpptools|ms-|1.3.0-insiders2
platformio-ide|pla|2.3.1
vscode-nand2tetris-hdl|rob|0.1.1
pdf|tom|1.1.0
vscode-icons|vsc|11.2.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
riscv|zhw|0.0.8

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
