### ISSUE TITLE
ENOENT from Update Service

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#120075]
Issue Type: <b>Bug</b>

After manually triggering an update check.

VS Code version: Code - Insiders 1.55.0-insider (6f726bcdf6a4d6cb518a3fcdb03c21be7293f417, 2021-03-25T08:19:33.237Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|24.00GB (13.91GB free)|
|Process Argv|--crash-reporter-id cced66f0-5748-4955-9966-94e42e300c57|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
![image](https://user-images.githubusercontent.com/9205389/112798322-071b5980-906d-11eb-923a-c36e05c2e43e.png)

**Comment by chrmarti** [comment]
The update then worked on retry.

**Comment by joaomoreno** [comment]
Weird, first time I see this. It just worked on retry? No issues since?

**Comment by chrmarti** [comment]
No issues so far.

**Comment by joaomoreno** [comment]
Closing it as a fluke. 🙈
