### ISSUE TITLE
Unable to use character 'a' and brackets '{}' often

### ISSUE THREAD

**Issue by Natarajanraju** [microsoft/vscode#120014]
Hi

Often am unable to type alphabet letter 'a' and flower brackets '{}'.

I tried re-installing VS Code and disabled the extensions. But nothing helped. Please look into this

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `a`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
