### ISSUE TITLE
Getting Started: Guidance around ideal image size

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120048]
I tried adding an image and it gets restricted quite a bit:

![image](https://user-images.githubusercontent.com/2193314/112756647-02867080-8f9b-11eb-8fe1-a50e2008c623.png)

The pixel size seems pretty random:

![image](https://user-images.githubusercontent.com/2193314/112756659-13cf7d00-8f9b-11eb-8f6b-177f6ffaec3f.png)

As a result of this, the image above is overly blurry. I could use a 531x470 image to fix this but that number could change and it would also look bad on hdpi.

Ideally we'd tell people what the ideal image size is as well as how to deal with hdpi monitors (optional separate set of images?). Extra points for showing the guidance on hover/autocomplete of the `media` entry.

**Comment by JacksonKearl** [comment]
We currently treat images as 1.5x scale (797 = 531 * 1.5), as all the builtin images have been designed for this. We could perhaps support multiple images and use src-set, I didn't want to do that at first because you end up bundling more bits for all the different sizes (unlike in the web case where src-set saves you bandwidth). 

cc @digitarald

**Comment by Tyriar** [comment]
If images are all 1.5 scale aren't they going to look not great in both x1 and x2 scale displays?

**Comment by digitarald** [comment]
So far the hdpi (1.5) versions have looked acceptable on mdpi and xhdpi screens as most images are downscaled screenshots and don't need to be pixel-perfect (compared to icons).

If we want crisper screenshots, I'd like to try 2x images and see how they scale down to 1x and 1.5x. I'd assume that browser resizing does as good of a job as doing specific DPI exports from Figma. Maybe others are aware of performance trade offs here that we also need to consider on top of the additional asset size in the installer.

**Comment by JacksonKearl** [comment]
Added some text in the intelisense:
depending on context, the image will be displayed from 400px to 800px wide, with similar bounds on height. To support HIDPI displays, the image will be rendered at 1.5x scaling, for example a 900 physical pixels wide image will be displayed as 600 logical pixels wide.
