### ISSUE TITLE
Sandbox compatible way to access environment and product configuration inside the renderer

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120096]
# Synopsis

Today a VSCode window depends on some environmental information and configuration to function. We currently send this data into the renderer by adding a [`?config=<data>`](https://github.com/microsoft/vscode/blob/c0fa3dfd3e252792efbae044c44c3bbb90c5b093/src/vs/platform/windows/electron-main/window.ts#L896) URL query parameter and [later reading it from there](https://github.com/microsoft/vscode/blob/c0fa3dfd3e252792efbae044c44c3bbb90c5b093/src/bootstrap-window.js#L194-L201). This has been working fine for the longest time, but there is a maximum URL length in Chrome that might hit us (https://source.chromium.org/chromium/chromium/src/+/master:url/url_constants.cc;l=37). It is also not very clear how well Chrome behaves for very large URLs and might not be the best fit to send data over from the main process to the renderer.

In addition to that, we have a file `src/vs/platform/product/common/product.ts` that currently is not fit for sandbox use because it synchronously reads our `product.json` and `package.json` file:

https://github.com/microsoft/vscode/blob/c0fa3dfd3e252792efbae044c44c3bbb90c5b093/src/vs/platform/product/common/product.ts#L49-L50

Going forward we need a solution that:
* does not depend on node.js but electron and/or web standards
* is fast (i.e. no waterfall)
* is robust (i.e. does not fail if the data is >2 MB)
* is unified (i.e. product configuration and other environmental information are both handled)

# Solutions

## Query Parameter
This expands our current use of the URL query parameter to include our product configuration.

**Pro:** already used today
**Con:** ✋ we are more likely to hit the 2 MB limit

## IPC renderer <-> main process
Right before loading renderer code we do a IPC call to the main process to resolve the environmental and product configuration.

**Pro:** will work for any amount of data
**Con:** ✋ blocks the entire startup until the IPC message is resolved (waterfall)

## Custom Protocol and `script` tag
We could add a `<script src="vscode-config://app/product"></script>` to our HTML that simply assigns all product configuration to a global `window` variable. 

**Pro:** this should be fast because browsers load `script` tags in parallel
**Con:** ✋ this will not work for dynamic environmental data because the URL is static

## Custom Protocol and `script` tag and cookie/header identifier
This expands on the previous solution but makes sure that the request to `vscode-config://app/product` includes some identifier (session ID?) that allows to provide dynamic environmental data too.

**Pro:** this should be fast and cover all our data
**Con:** ❓ so far I have not found a way to include a identifier from a renderer when requesting a custom protocol

## Inline the environmental data into the build output
The idea is that the build process simply replaces some well defined variable in our source code with the environmental information. We already do this today for our web build.

**Pro:** fastest solution that does not require any IPC communication
**Con:** ✋ this will not work for dynamic environmental data and also break running out of sources

## Inline the environmental data into the HTML
We could enrich our HTML with some template variables that get filled with content when served from the main process

**Pro:** does not require any IPC communication and aligns with what web servers typically do
**Con:** ❓ the performance impact is unknown because this means we have to implement a custom protocol handler that patches our HTML contents when requested

## Add data as command line argument
We could encode the entire environment data as a command line argument via the `additionalArguments` option of a window in Electron.

**Pro:** fast solution that does not require any IPC communication
**Con:** ✋  uncertain max-length restrictions and questionable from a security point of view

## Add data as process environment
We could encode the entire environment data into a process environment variable that get's inherited down to the renderer process.

**Pro:** fast solution that does not require any IPC communication
**Con:** ❓ uncertain max-length restrictions and questionable from a security point of view as well as needing to ensure that the environment does not inherit further down to child processes.

//cc @deepak1556

**Comment by bpasero** [comment]
Setting as "help wanted" mainly to open this issue to anyone that has more ideas for how to solve this.

**Comment by deepak1556** [comment]
For the `Custom Protocol and script tag` option, can the environmental data be obtained in preload script via a fetch which can be done while the document is loading ?

```js
// main.js

const window = new BrowserWindow({
  webPreferences: {
     additionalArguments: ['--windowId=someId'],
    preload: 'preload.js'
  }
})

// preload.js

const windowId = // someId parsed from command line

window.fetch(`vscode-config://${windowId}/environment').then(() => {
  // Pass the data to the page
})

// window.html

<script src="" async></script>
<script src="vscode-config//app/product" async></script>
```

**Comment by deepak1556** [comment]
That was the first thing @bpasero was looking for, it would have been helpful for this scenario. But I think we can accomplish a solution for the issue at hand with api available today via `ipc.invoke`, the handler `ElectronBrowserInterface` is not associated so we get a separate message pipe and calling it in the preload script can help get the data while the document is loading since the response callback is invoked on the same interface.

**Comment by bpasero** [comment]
@miniak yeah official support via APIs for this would be great, I am sure every Electron app out there faces this problem too.

**Comment by bpasero** [comment]
This landed with the following strategy:
* `electron-main` process adds a `additionalArgument` to the renderer process (pretty much a UUID)
* `preload` script in renderer runs `ipcRenderer.invoke` to fetch the config from the main side
* renderer awaits the promise to return before continuing to load

@miniak little update to my comment in https://github.com/microsoft/vscode/issues/120096#issuecomment-810785154, I think the nicest would actually be a way to pass additional context from the `loadUrl` call because the browser window construction options wouldn't allow to pass different context in after the window has loaded once.
