### ISSUE TITLE
[default-theme] Python 3 gets highlighted as Python 2

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/vscode#120052]
- VS Code Version: 1.54.3
- OS Version: KaOS rolling

Steps to Reproduce:

1. See screenshot
2.

Python 2 highlighting (see the **_file_** highlight)

![Screenshot_20210328_172536](https://user-images.githubusercontent.com/6344099/112758062-bf54ed80-8fec-11eb-8c4b-d8c0c86e253e.png)

Correct highlight

![Screenshot_20210328_172430](https://user-images.githubusercontent.com/6344099/112758084-d398ea80-8fec-11eb-9c7a-cac9e61fce28.png)

Python 2 is unmaintained

**Comment by alexr00** [comment]
@ShalokShalom how did you achieve the Python 3 highlighting from your second screenshot?

**Comment by ShalokShalom** [comment]
I switched to Dracula 😜

**Comment by alexr00** [comment]
@ShalokShalom thanks for the additional info. In that case, this is by design. Our default themes are designed to work well-enough with most languages, but they aren't perfect. 

@aeschli FYI in case you want to make changes to the default themes to better highlight python.

**Comment by ShalokShalom** [comment]
Incorrect highlighting is 'by design' when a third party theme can do it correct?
