### ISSUE TITLE
Error commands not found

### ISSUE THREAD

**Issue by Crash4you** [Microsoft/vscode#12002]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more detailed information.

**Comment by bpasero** [comment]
@Crash4you can you provide more details?

**Comment by Crash4you** [comment]
I am using VS code, anytime i open a folder or try to work on a project, none of my commands are found.
Here is what is displayed.

**Comment by Crash4you** [comment]
![vs error](https://cloud.githubusercontent.com/assets/15949281/18521402/fe02a532-7a79-11e6-8fe1-d55bebca5fea.PNG)

**Comment by bpasero** [comment]
@Crash4you are all commands from PowerShell?

**Comment by Crash4you** [comment]
powershell,java,C++, most of the extension/commands

**Comment by Crash4you** [comment]
if i do ctrl+p/ctrl+shift+p,none of the commands are found that are used in the setup videos

**Comment by bpasero** [comment]
@Crash4you maybe they only work if you open a folder?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
