### ISSUE TITLE
Copy As menu shouldn't have an ellipsis

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#120066]
Refs #118208

I don't think the new _Copy As..._ menu should have an ellipsis at the end. Typically, ellipsis are added to indicate a dialog or confirmation will be shown on click, not for a submenu expansion. I also don't know of any other cases where `...` is used on a menu item with a submenu (in our app or any others).

**Comment by misolori** [comment]
That's actually a good point, from looking at other apps and how we use submenus, the ... only applies for a single item that requires user input.

**Comment by joaomoreno** [comment]
I don't think this is severe enough to be a candidate, so assigning to April.

**Comment by joaomoreno** [comment]
After endgame discussion, this is wanted for release, merging it in!
