### ISSUE TITLE
Files automatically get deleted

### ISSUE THREAD

**Issue by iaxat** [microsoft/vscode#120007]
- VS Code Version:1.54.3 (Universal)
- OS Version: MacOS 11.2.3 Big Sur

Steps to Reproduce:

1. Connect Gdrive as a local drive using Rclone
2. Clone GitHub repo to gdrive
3. Start editing files and after some modifications, it automatically shows as deleted in the source control extension.
4. When you close the file after it shows as deleted, it disappears from the directory, and also terminal can not find it.
5. Creating a new file does solve the problem but happens in a while.

This error does not use to exist before, also overwrite settings are on, if that is not on it does gives a notification every once in a while to compare or overwrite.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by bpasero** [comment]
> Connect Gdrive as a local drive using Rclone

That sounds to me like it could result from this setup. Does it reproduce without this setup?
