### ISSUE TITLE
"editor.acceptSuggestionOnEnter": "smart" stopped working.

### ISSUE THREAD

**Issue by mikatpt** [microsoft/vscode#120070]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. In settings.json, "editor.acceptSuggestionOnEnter": "smart" 
2. Type out any full suggestion and press enter
3. Expect newline, but instead it accepts the suggestion you have already fully typed.

At first, I thought this issue was isolated to a single language, as I noticed it malfunctioning on my first day learning Go. However, I then tested with TypeScript and Python and experienced the same bug. Maybe it's just on my end? Appreciate the help!

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.63GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-16.04/home/mikatpt/coding/goLearn --remote=wsl+Ubuntu-16.04 --crash-reporter-id f2feabda-a890-4bf1-b2b9-8b46a1635038|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-16.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2303)|
|Memory (System)|12.38GB (9.67GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-firefox-debug|fir|2.9.2
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
vscode-eslint|dba|2.1.19
vscode-html-css|ecm|1.10.2
go|gol|0.23.3
cql|Law|0.8.7
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.3
jupyter|ms-|2021.3.684299474
js-debug-nightly|ms-|2021.3.2417
vsliveshare|ms-|1.0.4018
vscode-jest|Ort|3.2.0
open-html-in-browser|pea|2.1.3
sass-indented|syl|1.8.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
pythonvspyt943cf:30280190
wslfolderdoccf:30280165
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by jrieken** [comment]
@mikatpt What language/suggestion do you see this with? Can "reproduce" for TypeScript but TS seems to be having a completion command which is a reason to mute this feature

**Comment by mikatpt** [comment]
All three languages seemed to have the same problem.
As an example: I was re-implementing a linked list in Go to get more familiar with syntax. I noticed that every time I typed `node.next`, following up with enter caused the described behavior. 
However, even in Python, I’m getting the same issue with other syntax - simply assigning a variable to ‘None’ causes the error as well.

**Comment by jrieken** [comment]
The underlying logic didn't change, maybe extension suggestions changed (fyi @mjbvz). The logic always was and is tricky because the insert text is only one part of a suggestion. They might have additional text edits or commands that do whatever. In those (and other) cases we cannot do the smart insert. 

https://github.com/microsoft/vscode/blob/aacafc75b3703a5d471836a4afb4c4dc167fa18a/src/vs/editor/contrib/suggest/suggestController.ts#L166-L173

Adding @mjbvz so check if this has recently changed of TS/JS suggestions

**Comment by ssmooncoder** [comment]
I've have the same issue with js/ts/python. No textual change but pressing `enter` doesn't insert a new line. Seems like [#59044](https://github.com/microsoft/vscode/issues/59044) didn't fix it?
