### ISSUE TITLE
Any plans for snippets interpolation?

### ISSUE THREAD

**Issue by rickalex21** [microsoft/vscode#120065]
Hello, are there any plans to allow calling external commands from snippets? 

Backticks call an external command. It would look something like this: 

```json
"External python command": {
  "prefix": "lorem",
  "body": [
    "${`lorem.py 2s 3p`}"
  ],
  "description": "External python command"
}
```

The program would need to return a list with empty items for new lines ['paragraph1','','paragraph2','','paragraph3']. 

```python
for n in range(n_para):
		p1 = [random.choice(sentences) for p in range(n_sent) ]
		wrapstr = ''.join(p1)
		word_list = word_list + wrapper.wrap(text=wrapstr) + ['']

return word_list
```

Result: This is just a simple example but it would open up the doors for more things.

```text
Duis tempus convallis urna eget rhoncus. Etiam tempor fermentum leo vitae
tincidunt.

Aenean porta, magna ut dignissim egestas, ligula nisi volutpat tellus, id
imperdiet enim nisl nec est. In hac habitasse platea dictumst.

Phasellus commodo auctor lacus. Phasellus aliquet dui eget dui sagittis dapibus.
```

Thanks

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"snippets"
