### ISSUE TITLE
Files and folders not showing in explorer tree

### ISSUE THREAD

**Issue by brikibsw** [Microsoft/vscode#12004]
- VSCode Version:

  1.6.0-insider 
  commit  6fa85223efb25ad7ce3e534c7eb07edd9524bd6d
  date 2016-09-14T06:10:40.320Z

- OS Version:
Win 10.0.14393 x64
Steps to Reproduce:

1. Update to latest insider build when asked by VS Code insider

this is from DevTools

Cannot read property 'fsPath' of undefined: TypeError: Cannot read property 'fsPath' of undefined
    at t.renderContents (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:116:5057)
    at t.render (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:50:10041)
    at t.e.renderElement (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:49:25672)
    at e.render (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:47:21969)
    at e.insertInDOM (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:47:22405)
    at t.insertItemInDOM (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:48:11942)
    at t.refreshViewItem (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:48:3927)
    at t.onInsertItem (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:48:3534)
    at t.onInsertItems (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:35:22313)
    at t.onItemChildrenRefreshed (file:///C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:48:1260)e.onUnexpectedError @ fake:1
telemetry.ts:56Ctrl+Alt+ keybindings should not be used by default under Windows. Offender:  40999  for  nativescript.runIos

In Vs Code 1.5.2 files and folders are showing

![vscode-files](https://cloud.githubusercontent.com/assets/408346/18503520/97c09cfa-7a5d-11e6-9752-1d1e4c3fee54.png)

**Comment by bpasero** [comment]
@brikibsw is it possible to share this workspace with me?

**Comment by brikibsw** [comment]
@bpasero No problem, by workspace do you mean my repo ??

**Comment by bpasero** [comment]
@brikibsw yes!

**Comment by brikibsw** [comment]
@bpasero I could send you a zip of repo and should i nuke node_modules folder ??

**Comment by bpasero** [comment]
@brikibsw zip is good with nuked node_modules.

**Comment by brikibsw** [comment]
@bpasero here you go

[CountItCalendarWeb.zip](https://github.com/Microsoft/vscode/files/471571/CountItCalendarWeb.zip)

**Comment by bpasero** [comment]
@brikibsw crazy, I am not able to reproduce this. does it happen for all workspaces you open or only this one? Did you ever try to run VS Code out of source code? This would help debug this a bit more.

**Comment by brikibsw** [comment]
@bpasero  I have tried to open another folder with same symptoms, but from explorer right click Open with Code - insider file is opened, 

I have not tried running from source code but I am willing to try, tell me which branch to clone

**Comment by bpasero** [comment]
@brikibsw so you can ONLY reproduce from this one folder is that true?

Would help a lot if you could follow https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source and run VS Code out of sources and try to open the problematic folder.

Thanks 👍

**Comment by brikibsw** [comment]
@bpasero  No, files and folders does not show in any folder I open, only when i open a file from windows explorer right click context menu, file is shown in editor

I will try to run from source

**Comment by bpasero** [comment]
@brikibsw ok that is interesting, should be easy enough to reproduce then once you run out of sources 👍

**Comment by bpasero** [comment]
@brikibsw you do not have the vscode-icons extension installed, do you?

**Comment by brikibsw** [comment]
@bpasero i have uninstalled all extensions, but yes i had vscode-icons ext, 

Running from source is showing files and folders in navigator tree :), and after uninstalling and deleting "C:\Program Files (x86)\Microsoft VS Code Insiders" folder and installing clean now everything is showing in navigator

**Comment by bpasero** [comment]
@brikibsw great to hear. We STRONGLY advice against installing vscode-icons extension as it can cause issues that are extremly hard to find out. There should be no reason to install vscode-icons extension anymore since we added support for icons in 1.5.

**Comment by brikibsw** [comment]
@bpasero Yes you have icon support, but vscode-icons are prettier and have icons for folders and on tabs to, but i can live without that ext :) and yes it is definitely vscode-icons ext that caused problem

**Comment by bpasero** [comment]
@brikibsw we plan to show more icons in more areas of VS Code for the current release so that there is no reason to use vscode-icons anymore.

**Comment by robertohuertasm** [comment]
@brikibsw, @bpasero opened [this issue](https://github.com/robertohuertasm/vscode-icons/issues/308) in vscode-icons' repo. 

vscode-icons now supports official icons so I wouldn't say that installing it could cause any potential issue per se. It's just the combination of using the custom functionalities and the Insiders build together. If you just want the icons you can install it and use the official way of using icons.

@bpasero, thanks for reporting that. @brikibsw, thanks for your nice words regarding the extension. I'll be looking into it asap and let you know in [vscode-icons' repo](https://github.com/robertohuertasm/vscode-icons/issues/308).
