### ISSUE TITLE
How does files.exclude work?

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#120082]
Hi!

I've been working on a pull request for a feature that I wanted and was already suggested (hide files defined in gitignore) and I've spent the good part of an hour trying to figure out 2 things:
How do I make a new setting?
And how do I exclude files (ie, hide them in the side bar)?

Any help appreciated. Thanks!

**Comment by Tyriar** [comment]
Settings are all defined like this:

https://github.com/microsoft/vscode/blob/f554a745505474ba031a79f5ab4a5c9d1ed3af39/src/vs/workbench/contrib/files/browser/files.contribution.ts#L127

Typically in a `something.contribution.ts` file.

For exclude files, I'd recommend doing a text search of `files.exclude` and using find references for the results to find where it's being used.

**Comment by Milo123459** [comment]
I did a text search of files.exclude and couldn't find anything. I found where the files colour gets changed but not how to exclude it. Is there a disposable I need to push?

Also, how would I get the value of a setting? I don't see how.

**Comment by Milo123459** [comment]
Oh also thanks @Tyriar for the original help! Just need to finish the other stuff off and I'll be able to make my first contribution!

**Comment by Tyriar** [comment]
This is where it's defined https://github.com/microsoft/vscode/blob/f554a745505474ba031a79f5ab4a5c9d1ed3af39/src/vs/workbench/contrib/files/browser/files.contribution.ts#L133-L157

I don't actually know much more than that, if I was diving into this I'd start there and with `files.exclude` search across all files and look around to understand how it works:

![image](https://user-images.githubusercontent.com/2193314/112817918-d40aa300-9037-11eb-9a53-eb55e6aa6084.png)

**Comment by Milo123459** [comment]
Ah, I see. I still am not 100% sure how it hides the file but I'll look for FILES_EXCLUDES_CONFIG - Thanks!

**Comment by Milo123459** [comment]
@Tyriar sorry but I'm still kinda stuck on this :(
I've so far made the configuration (which is a step in the right direction) but still have some questions.
How does the configuration API work? I need to figure out how to get the value of the config I created but I'm not sure how.

**Comment by Tyriar** [comment]
You'd use `IConfigurationService` to get/update the config value

**Comment by Milo123459** [comment]
Thank you!
