### ISSUE TITLE
Python runs headless on Linux until I manually set DISPLAY

### ISSUE THREAD

**Issue by anna-naden** [microsoft/vscode#120067]
Issue Type: <b>Bug</b>

Whenever I exit vscode and come back in, matplotlib doesn't produce any display. Attempting to set the backend elicits a message saying that I am running headless. If I open a VS code terminal window and export DISPLAY=:0, then plotting works until the next time. Disabling extensions (except Pythion) does not make a difference

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 2405)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|46.78GB (36.33GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id ff06dec4-92b5-4ec4-955c-d866f2466883|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
markdown-toc|Ala|1.5.6
arepl|alm|2.0.2
vscode-django|bat|1.4.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.39.0
python-extension-pack|don|1.6.0
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
RunOnSave|eme|0.2.0
prettier-vscode|esb|6.3.1
vscode-pydev|fab|0.2.4
code-runner|for|0.11.3
vscode-test-explorer|hbe|2.19.6
vscode-test-explorer-liveshare|hbe|1.0.5
python-essentials|Jil|0.0.3
vscode-python-test-adapter|lit|0.6.7
MagicPython|mag|1.1.0
pyright|ms-|1.1.126
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
cpptools|ms-|1.2.2
vsliveshare|ms-|1.0.4018
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.5.4
vscode-yaml|red|0.17.0
code-settings-sync|Sha|3.4.3
html5-boilerplate|sid|1.1.1
guides|spy|0.9.3
code-spell-checker|str|1.10.2
tabnine-vscode|Tab|3.2.15
python|tht|0.2.3
vscodeintellicode|Vis|1.2.12
vscode-wakatime|Wak|5.0.1
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943:30280189
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by meganrogge** [comment]
This sounds like an issue with that extension. Could you pls file an issue for that extension?
