### ISSUE TITLE
Debug broken or changed?

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#12009]
- VSCode Version: latest over-night build
- OS Version: latest OSX

Steps to Reproduce:

1. Debug an existing Node.js project that worked yesterday
2. `Debug adapter process has terminated unexpectedly`
3. Copy and paste and get: `Error: Debug adapter process has terminated unexpectedly (occurred again)`

**Comment by bpasero** [comment]
@leegee can you share your project?

@weinand fyi this might either be node-debug update or electron update related.

**Comment by weinand** [comment]
The problem is unrelated to the Electron upgrade.
Some npm modules are missing in the node-debug extension.
The workaround is to `cd` into the node-debug extension of the Insider build and run `npm install`.

**Comment by 4kochi** [comment]
Thanks for the hint with the workaround. Works fine now.

**Comment by weinand** [comment]
A new Insider build with a fix is available now.
