### ISSUE TITLE
Unable to write file 'file path\index.html' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open file_path\'ndex.html')

### ISSUE THREAD

**Issue by GeetaGhanti0** [microsoft/vscode#120041]
I have Node Js project, and under the folder public I have index.html file, and when I load the folder structure or project into VS code, neither I am able to see the Index.html file in project files, and I am facing this error - (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open

**Comment by Tyriar** [comment]
Can you show a screenshot and also fill in version info from Help > About?
