### ISSUE TITLE
Feature request: automatically expand repositories with changes in the Source Control view

### ISSUE THREAD

**Issue by tyzbit** [microsoft/vscode#120029]
I believe this or something like it may have been a feature or default behavior previously.

## Current behavior
Users must manually collapse or expand source repositories regardless of if there are changes in that repository.  Users only have the option to collapse or expand all source repositories at will.

## Desired behavior
A user could choose a 3rd option, called "Expand repositories with changes" for example, that collapses the repositories that do not have changes and automatically expands the repositories that do.  This option could also replace the "Expand all repositories" option so users still only have to pick between two options, "Collapse all repositories" and "Expand all repositories".

### Before making a change to a file in a tracked repository
<img width="334" alt="image" src="https://user-images.githubusercontent.com/3319104/112734189-8c422980-8f1a-11eb-988d-2bdcd8fe24a7.png">

### After making that change, the repository with the change automatically expands
<img width="333" alt="image" src="https://user-images.githubusercontent.com/3319104/112734240-eb07a300-8f1a-11eb-8841-421a71a70e38.png">

### If that change is discarded, the repository collapses back
<img width="334" alt="image" src="https://user-images.githubusercontent.com/3319104/112734189-8c422980-8f1a-11eb-988d-2bdcd8fe24a7.png">

(The repository also collapses if the change is staged and committed and there are no other detected changes in the repository)

**Comment by gjsjohnmurray** [comment]
Are you aware of the `scm.providerCountBadge` setting? It doesn't do what you are proposing but it can show you which collapsed rows are worth expanding.

**Comment by tyzbit** [comment]
That does help with being able to see which repositories have changes, but does not fulfill the desire to save screen real estate and conserve attention with collapsing repositories that don't have changes.
