### ISSUE TITLE
VS Code became very slow on startup after the last windows update. Takes ~10 sec now, 1-2 before.

### ISSUE THREAD

**Issue by johannesgaebler** [microsoft/vscode#120078]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-557c.extHost.cpuprofile.txt`
-`prof-557c.main.cpuprofile.txt`
-`prof-557c.renderer.cpuprofile.txt`

[prof-557c.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6220061/prof-557c.main.cpuprofile.txt)
[prof-557c.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/6220063/prof-557c.renderer.cpuprofile.txt)
[prof-557c.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/6220065/prof-557c.extHost.cpuprofile.txt)

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/22087
