### ISSUE TITLE
macOS: One or two Python processes are always launched whenever VSCode quits

### ISSUE THREAD

**Issue by microwish** [microsoft/vscode#120033]
- VS Code Version: 1.54.3
- OS Version: macOS Big Sur Version 11.2.3 (Darwin x64 20.3.0)

Steps to Reproduce:

1. Open VSCode
2. Edit a Python file
3. Quit VSCode
4. CPU will be soaring up immediately after VSCode quits (ALWAYS reproducible)
5. From the `top` command or Activity Monitor, we can see the one or two Python processes are consuming the most of CPU

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by microwish** [comment]
I have screenshots of this issue.

**Comment by microwish** [comment]
The latest output of `top` command:
```
Processes: 507 total, 3 running, 504 sleeping, 2191 threads                                                                                                           17:31:44
Load Avg: 1.34, 1.30, 1.22  CPU usage: 5.28% user, 2.4% sys, 92.66% idle   SharedLibs: 439M resident, 90M data, 57M linkedit.
MemRegions: 109076 total, 4049M resident, 177M private, 2900M shared. PhysMem: 15G used (2235M wired), 1182M unused.
VM: 3155G vsize, 2305M framework vsize, 8704(0) swapins, 8896(0) swapouts. Networks: packets: 5496258/4958M in, 3675425/1803M out.
Disks: 1040605/19G read, 1202182/19G written.

PID    COMMAND      %CPU TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS PGRP  PPID  STATE    BOOSTS          %CPU_ME %CPU_OTHRS UID  FAULTS   COW   MSGSENT    MSGRECV
37301  Python       94.3 01:38.90 3/1    0    16    48M+   0B     0B    37205 1     running  *0[1]           0.00000 0.00000    501  18813+   649   127        32
456    iTerm2       5.0  12:33.76 12     9    447+  232M+  13M+   24M-  456   1     sleeping *0[2331]        0.19115 0.24350    501  5649850+ 2618  1737664+   863849+
```

**Comment by microwish** [comment]
The latest output of Activity Monitor:
```
 Python	102.7	2:40.38	4	10651	0.0	0.00	37301	gcao	0 bytes	0 bytes	0 bytes		0 bytes	0 bytes	0 bytes	Intel	No	No	No	(null)	No	0 bytes	0	0 bytes	0	0 bytes	0 bytes	No	-	No	(null)	
 Activity Monitor	12.4	2.52	9	10	0.0	0.00	37612	gcao	0 bytes	0 bytes	0 bytes		0 bytes	0 bytes	0 bytes	Intel	No	No	Yes	(null)	No	0 bytes	0	0 bytes	0	0 bytes	0 bytes	No	-	No	(null)	
```

**Comment by edouardroger** [comment]
Same issue here.

<img width="1072" alt="Capture d’écran 2021-03-30 à 08 05 22" src="https://user-images.githubusercontent.com/5379899/112941346-b8ce8f00-912e-11eb-846f-d65c2b0d9ad7.png">

I'm using Python through Pyenv (installed via Homebrew) with ms-python.python extension.

It seemed fixed for a while but I believe a new version of this extension broke it.

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
