### ISSUE TITLE
Offer a way to adjust the "acceptSelectedSuggestion" command

### ISSUE THREAD

**Issue by SilenceX12138** [microsoft/vscode#120035]
## The feature I'm looking for
When I'm coding in VSCode, the auto suggestion is helpful. 

However, after pressing the `Enter` button to select one suggestion, the text I'm going to type seeming to be selected **automatically**. As a result, the editor **cannot** offer suggestions about the variable names.

Meanwhile, if I use keyboard to **move the cursor** and **go back**(the selection will **disappear**), then the variable names **can be offered**.

So is there any way to make the process easier?

Thx a lot.

## Visual description
![show](https://user-images.githubusercontent.com/47887520/112740688-97946400-8fb1-11eb-806c-c7f98e015ad8.gif)

**Comment by jrieken** [comment]
>  the text I'm going to type seeming to be selected automatically. As a result, the editor cannot offer suggestions about the variable names.

Sorry, but I don't understand what that means

**Comment by SilenceX12138** [comment]
Maybe I can describe it in another way.

PS: below is the **sequence of keyboard buttons**.

* situation 1(Line `4`): `o`->`s`->`.`->`l`->`i`->`down arrow`->`enter`(choose the `listdir` option)->`d`->`i`->`r`->...

  > If I code in this way, var name `dirname` cannot be automatically provided like function name `listdir`.

* situation 2(line `5`): `o`->`s`->`.`->`l`->`i`->`down arrow`->`enter`(choose the `listdir` option)->`right arrow`->`left arrow`->`d`->`i`->`r`->'enter`

  > In this situation, var name `dirname` option can be offered like function name.

Hope this can help make it clearer.

**Comment by jrieken** [comment]
Please to set this setting to false: `ditor.suggest.snippetsPreventQuickSuggestions: "false"`

**Comment by SilenceX12138** [comment]
It works!

Really thx~

**Comment by SilenceX12138** [comment]
It works!

Really thx~
