### ISSUE TITLE
[simple browser] icons are broken in firefox

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#120036]
Originally reported in Gitpod: https://github.com/gitpod-io/gitpod/issues/3474

But I can reproduce in Codespaces with latest Firefox as well:
<img width="1100" alt="Screenshot 2021-03-28 at 08 04 43" src="https://user-images.githubusercontent.com/3082655/112743988-652c3c00-8f9c-11eb-990d-039a32602c5f.png">

**Comment by misolori** [comment]
@mjbvz seems like a simple browser issue, codicons in the screenshot above appear to have been loaded.
