### ISSUE TITLE
tab size not working

### ISSUE THREAD

**Issue by calidion** [microsoft/vscode#120072]
Issue Type: <b>Bug</b>

Tab size not working. Tab size is set to 2 spaces, but still be formatted in 4 spaces.

VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-64-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 1770)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (1.45GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 9cc3893b-361e-4ca7-8513-c98a43defcee|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.39.0
prettier-vscode|esb|5.8.0
nunjucks-template|ese|0.3.4
vscode-medium-to-markdown|mos|0.2.0
vscode-docker|ms-|1.10.0
remote-containers|ms-|0.155.1
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
prisma|Pri|2.19.0
markdown-preview-enhanced|shd|0.5.17
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontbcf:30265426
openwsldoc:30280162
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by Tyriar** [comment]
You have prettier installed, that might be overriding what you set in settings.json or something?
