### ISSUE TITLE
Popup disappears while hovering

### ISSUE THREAD

**Issue by olegKusov** [microsoft/vscode#120016]
- VS Code Version: Version: 1.54.3
- OS Version: macos 11.2

Steps to Reproduce:

1. hover to error
2. try to click on eslint 'quick fix' button

https://user-images.githubusercontent.com/28058268/112720796-a75c6b80-8f11-11eb-95b7-9e215b11e3dd.mov

I understand that user must first move mouse up. But often I'm making this straight movement and each time popup disappears. Maybe we can make transparent padding bottom or smth. I don't know.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
See also #97328
