### ISSUE TITLE
vscode-side logging for DAP message exchange

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#120069]
Is there already a way to enable vscode-side DAP message tracing?

We are currently using `vscode.DebugAdapterServer` to directly connect our DAP server over the network. So, the client is the vscode. Our server has logging, but sometimes we need to debug cases where server didn't handle messages from client on time, client didn't receive messages from the server timely, etc.

Ability to inspect what happened on the client side (= vscode) will help DAP server development/debugging.

**Comment by weinand** [comment]
@hyangah Please file VS Code issue in the VS Code repository.
