### ISSUE TITLE
show double File Icon Themes

### ISSUE THREAD

**Issue by chanzig** [Microsoft/vscode#12003]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1.  I use `VSCode Icons`,when I choose defalut,all well done;
2.  I select  `VSCode Icons` again, restart!  Then choose others will show double icon.
3.  I uninstall this icons ,it always show.

![image](https://cloud.githubusercontent.com/assets/1364025/18502560/4d61af00-7a8a-11e6-9717-e2539ba264a1.png)

**Comment by bpasero** [comment]
@chanzig did you install the vscode-icons extension?

**Comment by robertohuertasm** [comment]
@chanzig see [#292](https://github.com/robertohuertasm/vscode-icons/issues/292) 

Basically, you have to choose to use the official api by following  [#292](https://github.com/robertohuertasm/vscode-icons/issues/292) or choose the custom functionality by selecting `none` in your File Icon theme. 

For more information, please read the [vscode-icons readme](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md).
