### ISSUE TITLE
notebook: undo/redo cell creation does not re-select the created cell

### ISSUE THREAD

**Issue by arnobl** [microsoft/vscode#120085]
- VS Code Version: main branch, commit c0fa3df (28 march)
- OS Version: Linux
- Component: notebook

When a user adds a new cell in a notebook, this created cell is automatically selected.
This selection happens in the class `InsertCellCommand` (`coreActions.ts`):

```ts
const newCell = context.notebookEditor.insertNotebookCell(context.cell, this.kind, this.direction, undefined, true);
if (newCell) {
	context.notebookEditor.focusNotebookCell(newCell, 'editor');
}
```

However, when the user undoes and redoes this action, this new cell is not selected any more.
This may be considered as an issue since undo/redo must be an identify function.

I think that this issue takes sources in the method `createCell` (`notebookViewModel.ts`) where the current selection operation to do after the cell creation is `() => undefined`.

If I replace this arrow function by:
`() => ({ kind: SelectionStateType.Index, focus: {start: index, end: index+1}, selections: [{start: index, end: index+1}] })`

and I removed the `if (newCell)` block of `InsertCellCommand` it works as expected (build, tests, integration tests OK).

Steps to Reproduce:
To reproduce the issue automatically, adds this test in `extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts` (executed by `scripts/test-integration.sh`):

```ts
	test('correct cell selection on undo/redo of cell creation', async function () {
		const resource = await createRandomFile('', undefined, '.vsctestnb');
		await vscode.commands.executeCommand('vscode.openWith', resource, 'notebookCoreTest');
		await vscode.commands.executeCommand('notebook.cell.insertCodeCellBelow');
		await vscode.commands.executeCommand('undo');
		const selectionUndo = [...vscode.window.activeNotebookEditor!.selections];
		await vscode.commands.executeCommand('redo');
		const selectionRedo = vscode.window.activeNotebookEditor!.selections;

		// On undo, the selected cell must be the upper cell, ie the first one
		assert.strictEqual(selectionUndo.length, 1);
		assert.strictEqual(selectionUndo[0].start, 0);
		assert.strictEqual(selectionUndo[0].end, 1);
		// On redo, the selected cell must be the new cell, ie the second one
		assert.strictEqual(selectionRedo.length, 1);
		assert.strictEqual(selectionRedo[0].start, 1);
		assert.strictEqual(selectionRedo[0].end, 2);
	});
```

I will open a PR to detail the proposal.

Does this issue occur when all extensions are disabled?: Yes (in development mode).

**Comment by lramos15** [comment]
I created a cell, and then undo/redo a bunch on that cell and the selection isn't always the recreated cell

**Comment by rebornix** [comment]
@lramos15 any chance you can do a screen recording of the reproduce?

**Comment by lramos15** [comment]
Can't repro this anymore. Marking as verified. Don't know what happened before. Although there is some screen cheese on many undo redos it's very brief.
