### ISSUE TITLE
Uninstaller should have option to remove all data

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#12008]
Perhaps behind a prompt, but IMHO we should offer to remove:
- all the folder C:\users\xxx.vscode-insiders
- all the folder %APPDATA%\Code-Insiders

oftentimes people try to reinstall us if they get in trouble, but that doesn't really do anything since all the settings + extensions + Chrome cache thing (localstorage, etc) are all maintained/left behind

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
