### ISSUE TITLE
Getting Started: Consider supporting stripped down version of markdown in walkthrough descriptions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120050]
I tried to use _italics_ and `code` within the walkthrough tasks but it seems to be just plain text.

**Comment by JacksonKearl** [comment]
Yes, my thinking is to adopt something very similar to the views welcome contribution point based on general feedback about wanting more flexibility.

**Comment by JacksonKearl** [comment]
now support
```
``code``,  __italics__, and **bold** , along with [Commands](command:blah), [Links](https://aka.ms), and

[Buttons](command:blah or https://blah)
```

in addition we have the `command:toSide:blah` syntax to attempt to make some other editor group active before running the command, creating it if it does not exist already (and theres enough room to do so)

**Comment by JacksonKearl** [comment]
Oh, and the command syntax above should support URI-encoded arguments, just as the openerservice would.

**Comment by Tyriar** [comment]
Does this toSide thing only work with quickOpen? Should it be a quickOpenToSide command instead?

**Comment by JacksonKearl** [comment]
Works with anything! It's just a signal to split the editor if it's not already split, then set some group besides the getting started one as active. It wont split if the display is too narrow to begin with (~700px). 

There's a bug that quick open wont actually place the new editor in the active group if you select the item with `Enter`, but it will if you click on it.

**Comment by JacksonKearl** [comment]
https://github.com/microsoft/vscode/issues/121395
