### ISSUE TITLE
electron-12.x.y branch, IME don't work when on Wayland

### ISSUE THREAD

**Issue by karuboniru** [microsoft/vscode#120084]
- VS Code Version: commit hash: 6a7aba19d040dc16d67e549d8a866ff0b5b1c64f
- OS Version: `Fedora 34 (Workstation Edition Prerelease)`

Steps to Reproduce:

1. Compile code-oss from source, package as rpm, install it.
2. `code-oss --enable-features=UseOzonePlatform --ozone-platform=wayland`
3. Input method don't work, here specifically `fcitx5`

Does this issue occur when all extensions are disabled?: Yes
***

additional information:
Seems that IM module (like `/usr/lib64/gtk-3.0/3.0.0/immodules/im-fcitx5.so` or `/usr/lib64/gtk-3.0/3.0.0/immodules/im-ibus.so`) isn't loaded at all, when using Wayland.

**Comment by tinywrkb** [comment]
Might be related:

* [Issue 1022724: \[ozone/wayland\] Keyboard and IME issues](https://bugs.chromium.org/p/chromium/issues/detail?id=10227240)
* [Issue 1183262: Add support for gtk im module on ozone wayland platform](https://bugs.chromium.org/p/chromium/issues/detail?id=1183262)
* [Issue 1039161: Ozone-wayland: support text_input_v3 protocol](https://bugs.chromium.org/p/chromium/issues/detail?id=1039161)

**Comment by karuboniru** [comment]
Still present in https://github.com/microsoft/vscode/pull/120034#issuecomment-815095172
Maybe waiting a newer electron 12.x release?

**Comment by 12101111** [comment]
It may get support in electron 14 ( chromium 93 ) or later. electron 12 ( chromium 89 ) or electron 13 ( chromium 91 ) don't support it.

**Comment by stalkerg** [comment]
ibus not working at all under wayland because not support the latest version of the protocol.

**Comment by konan8205** [comment]
> ibus not working at all under wayland because not support the latest version of the protocol.

Does Electron or Chromium currently supports `text_input_unstable_v3`?

**Comment by 12101111** [comment]
> Does Electron or Chromium currently supports `text_input_unstable_v3` or `text_input_unstable_v1` protocol?

It support `text_input_unstable_v1`: https://github.com/chromium/chromium/blob/master/ui/ozone/platform/wayland/host/zwp_text_input_wrapper_v1.h

**Comment by stalkerg** [comment]
Basically, current Wayland protocols not enough for normal IME but developers working on it - https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/39

**Comment by microcai** [comment]
using gtk-4 will solve it. but how to use gtk-4 ? chrome has command flag for it.

**Comment by deepak1556** [comment]
`gtk-4` is not supported in electron yet, so the command line flag cannot be used. 

Is this issue present with latest insiders https://code.visualstudio.com/insiders which comes with newer runtime version ?

**Comment by karuboniru** [comment]
This problem still exist with `code-1.67.1-1651841920` and `code-insiders-1.68.0-1652420254` version. Chromium's input method support can be enabled by `--gtk-version=4`, while this is not possible since follow error will be generated when running `code --enable-features=UseOzonePlatform --ozone-platform=wayland --gtk-version=4 --verbose`
```
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'gtk-version' is not in the list of known options, but still passed to Electron/Chromium.
[15673:0514/001526.813128:WARNING:wayland_object.cc(94)] Binding to gtk_shell1 version 4 but version 5 is available.
[15673:0514/001526.813180:WARNING:wayland_object.cc(94)] Binding to zwp_pointer_gestures_v1 version 1 but version 3 is available.
[15673:0514/001526.813208:WARNING:wayland_object.cc(94)] Binding to zwp_linux_dmabuf_v1 version 3 but version 4 is available.
[15673:0514/001526.813499:WARNING:wayland_drm.cc(96)] Failed to get drm magic
(process:15673): Gtk-ERROR **: 00:15:26.816: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
[0514/001526.837255:ERROR:directory_reader_posix.cc(42)] opendir /home/yan/.config/Code/Crashpad/attachments/797ac066-0ea9-4880-b687-1ea6d3156a9a: No such file or directory (2)
```
