### ISSUE TITLE
Integrationt tests: colorize: test-92369.cpp (15251ms) takes 15s to finish

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120095]
At least for me on macOS the ` colorize: test-92369.cpp (15251ms)` takes 15s to complete, I think that is quite a bit for a single unit test, even for integration.

**Comment by alexr00** [comment]
We do this on purpose to make sure that a stuck grammar will not cause VS Code to hang. 

Alex Dima made the fix that prevents the hang a while ago so we can probably remove the test.
