### ISSUE TITLE
Installer shows EULA garbled text

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#12007]
![eula-broken](https://cloud.githubusercontent.com/assets/5047891/18504484/be30dd96-7a62-11e6-96f9-15402dab7001.PNG)

**Comment by joaomoreno** [comment]
You have your system in english right?

**Comment by alexandrudima** [comment]
Yep, our EULA contains some French text towards the end, I found it funny too, something for Canada.

**Comment by joaomoreno** [comment]
Ahhhhh, got it!

**Comment by ramya-rao-a** [comment]
I still see this

![image](https://cloud.githubusercontent.com/assets/16890566/18937640/f3413eaa-85a6-11e6-914c-608188d2b0d2.png)

**Comment by joaomoreno** [comment]
@ramya-rao-a Make sure you use a recent commit like [this](https://az764295.vo.msecnd.net/insider/ab6357b397481734e40edab607700c6421e5ea2f/VSCodeSetup-insider.exe), which I've built manually yesterday.

![image](https://cloud.githubusercontent.com/assets/22350/18943660/4665dddc-8621-11e6-9ae1-9b596b97747f.png)
