### ISSUE TITLE
Crashing on start

### ISSUE THREAD

**Issue by Mike-OxHuge** [microsoft/vscode#120024]
- VS Code Version:  code_1.54.3-1615806378_amd64.deb
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Complete uninstall
2. Install and run.

Does this issue occur when all extensions are disabled?: **Yes**

I can't even run it. It crashes like 5 seconds after I run it.
[a869fbcb-6ef6-4fe9-5e711685-e5f258aa.zip](https://github.com/microsoft/vscode/files/6215986/a869fbcb-6ef6-4fe9-5e711685-e5f258aa.zip)

**Comment by gjsjohnmurray** [comment]
/duplicate see https://github.com/microsoft/vscode/issues/116690#issuecomment-791064392

Said to be fixed in 1.55, which is available as Insiders and expected to release within a week.
