### ISSUE TITLE
Git: takes a long time to load vscode-docs repository in changes view

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120089]
When reloading a window with a multi root workspace where one of the repos is `vscode-docs` I see it takes a long time to resolve:

![recording (3)](https://user-images.githubusercontent.com/900690/112820773-3db19e00-9086-11eb-8bf1-00c74f51412c.gif)

@joaomoreno idea was to change this to a faster git call if possible.

This is actually causing the changes view to forget my last selected repository.

**Comment by joaomoreno** [comment]
@eamodio I can take this.

**Comment by eamodio** [comment]
Which git call is slow?

**Comment by joaomoreno** [comment]
We could potentially delay [this call](https://github.com/microsoft/vscode/blob/88655de6104955462e376a2a0bda252a3635280d/extensions/git/src/model.ts#L286-L286) and not make it part of the discovery async loop. That way, git repos can be given to SCM as soon as they're detected by [this call](https://github.com/microsoft/vscode/blob/88655de6104955462e376a2a0bda252a3635280d/extensions/git/src/model.ts#L282-L282).

**Comment by bpasero** [comment]
Isn't this the underlying cause of https://github.com/microsoft/vscode/issues/113803 ?

**Comment by joaomoreno** [comment]
No, I believe it's a separate issue.

**Comment by bpasero** [comment]
I am still seeing this.

**Comment by bpasero** [comment]
Now I don't know if I should rather reopen https://github.com/microsoft/vscode/issues/113803

**Comment by joaomoreno** [comment]
Let's keep it here. Can you show me a gifcap of it today?

**Comment by heartacker** [comment]
always selected all repos
@joaomoreno  here you are
![git-repos](https://user-images.githubusercontent.com/1876302/142867834-5e94d6d5-4854-4319-bc84-5775345d7b5e.gif)

**Comment by bpasero** [comment]
@joaomoreno the first time after a fresh startup and then I do a window reload:

![recording](https://user-images.githubusercontent.com/900690/142867995-7da51815-7883-4439-b73a-f8df60cbc9df.gif)

**Comment by joaomoreno** [comment]
@bpasero It doesn't seem like you still have the same issue that this GH issue describes. I see the `vscode-docs` appears immediately, correct?

If so, let's close this and reopen https://github.com/microsoft/vscode/issues/113803

**Comment by bpasero** [comment]
Yeah this is really the fact that all my repositories are selected on startup when I only ever have 1 selected. I lost track of all the issues around this, feel free to merge into one.

**Comment by meganrogge** [comment]
Still seeing this

![recording - 2021-12-03T074421 205](https://user-images.githubusercontent.com/29464607/144630826-eef2e534-f8ce-478c-801b-c1c53de07c19.gif)

**Comment by meganrogge** [comment]
I don't have gitlens installed

**Comment by meganrogge** [comment]
oh wait yes I do  will try

**Comment by meganrogge** [comment]
took ~22 seconds still
![recording - 2021-12-03T075024 084](https://user-images.githubusercontent.com/29464607/144631783-37a7b1a2-22a7-4993-9a36-2731b74768ca.gif)

**Comment by joaomoreno** [comment]
Something else in your machine stealing time from the Git extension being activated. You can use Extension Bisect to find it.

From that recording, as soon as the `vscode` repo is found, the `vscode-docs` repo appears within less than a second. That's exactly what was fixed here, as the `vscode-docs` repo would take much longer to appear, after the `vscode` repo did.

**Comment by meganrogge** [comment]
my machine is really slow in general ☹️ , but I agree looks like this specific issue is solved

**Comment by joaomoreno** [comment]
> my machine is really slow in general ☹️ , but I agree looks like this specific issue is solved

😢 @kieferrm let's get @meganrogge a beefier machine!

**Comment by meganrogge** [comment]
I'm switching to my MacBook 👍🏼
