### ISSUE TITLE
fail open new project when it has same name but from diffrent path and diffrent file

### ISSUE THREAD

**Issue by pooooriya** [microsoft/vscode#120022]
- VS Code Version:1.53.2
- OS Version: windows_nt 864 10.0.19042
- Version: 1.53.2 (system setup)
-Date: 2021-02-11T11:48:04.245Z
-Electron: 11.2.1
-Chrome: 87.0.4280.141
-Node.js: 12.18.3
-V8: 8.7.220.31-electron.0
-OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. create directory for ex : microsoft and clone or create some files into it
2.then create same name "microsoft" to another path not in same path and put some of an other files
3. when you want switch between these you cant switch and always show the first project beacuse has same name and vs code doesnt care about files into this project only check for same names and if its not same doesnt change directory

Does this issue occur when all extensions are disabled?: No

iI describe bug in number 3

**Comment by isidorn** [comment]
This works just fine for me.
Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
