### ISSUE TITLE
Tabs disappear after closing context menu in keybindings editor

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#120062]
- VS Code Version: From sources

![contextmenu_scrolling](https://user-images.githubusercontent.com/25115070/112767674-b4469100-8fdd-11eb-9d27-2406fabda01a.gif)

**Comment by bpasero** [comment]
That looks grid related to me.

**Comment by bpasero** [comment]
Web bisect points out this commit range which includes the move to the new table widget: https://github.com/microsoft/vscode/compare/567b82a0f9c31bd463af64997997730c5d0173cc...04770364fdc1bebeca9d1a257df2cacce06b35d6

**Comment by bpasero** [comment]
@sandy081 fyi, not sure if anything within the keybindings editor could have caused this other than adopting the table widget.

**Comment by jeanp413** [comment]
Can also be reproduced by focusing the search input and then tabbing until the table is focused
Created a PR #120102 fixing this.

**Comment by sandy081** [comment]
Tagged this as candidate as the experience is bad with custom menu.
