### ISSUE TITLE
やはり、改善の動きはないように見えます

### ISSUE THREAD

**Issue by hiroshi-nakajima345** [microsoft/vscode#120017]
必要なデータが送信するには大きすぎたため、クリップボードに書き込みました。フォームに英語で記入してください。

バグ報告

Visual Studio Code
やはり、改善の動きはないように見えます
類似の問題は見つかりませんでした
問題を再現するための正確な手順を共有します。このとき、期待する結果と実際の結果を提供してください。GitHub-flavored Markdown に対応しています。GitHub 上で確認するときに問題を編集してスクリーンショットを追加できます。
やはり、動きは遅々としています.quicksetupも基礎の学習も急流の動きはありません
 貼り付けてください。

**Comment by hiroshi-nakajima345** [comment]
thank you very much for your kind answer.
My English ability is very poor, so  I can't  express technical mater ,well please forgive me .


----- 元のメッセージ -----
From: "VS Code Issue Triage Bot" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Author" ***@***.***>
送信済み: 2021年03月27日 午後 10:09
件名: Re: [microsoft/vscode] やはり、改善の動きはないように見えます (#120017)

>  この問題を作成してくれてありがとう!しかし、説明は英語ではないため、私たちはそれに取り組むのが難しいです。もし、可能であれば、英語で行くように編集してください。新しいコメントを追加したり、新しい懸案事項を作成したりするのではなく、既存の懸案事項を編集してください。残念ながら、自動翻訳サービスはソフトウェアの問題について効果的にコミュニケーションを取るために必要な技術言語を扱うことはできないので、翻訳を支援する技術に精通している人の翻訳者を見つけることをお勧めします。それ以外の場合、この問題は翻訳が必要であるとマークされており、コミュニティメンバーが翻訳を支援できる場合があります。Thanks for creating this issue!Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.Otherwise, we have marked this as needing translation and a community member may be able to help out.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tyriar** [comment]
We don't have enough info with computer translation unfortunately. It just looks like "no improvements made, some particular component is slow" (not sure which one).

**Comment by hiroshi-nakajima345** [comment]
Thank you very much for you kind inquire. From that time the condition had changed .See added screenshot.
I can not describe correctly but now changed the condition.
I can create  one servlet project(もちろん中身は借りものです-日本語で申しわけなし)
nevetheless.it does not work well.
 So I can not get the letter of  conclusion (127.0.0.1?) of any letters in a text box.
How many time is it necessary to get conclusion. necessary long time?
This is the state of my condition .
I want to continue & resolve this problem.
If you can ,Help me.



----- 元のメッセージ -----
From: "Daniel Imms" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Author" ***@***.***>
送信済み: 2021年03月29日 午後 6:24
件名: Re: [microsoft/vscode] やはり、改善の動きはないように見えます (#120017)

>  We don't have enough info with computer translation unfortunately. It just looks like "no improvements made, some particular component is slow" (not sure which one).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Tyriar** [comment]
> See added screenshot.

Screenshots don't work when replying with email, can you upload it via github.com?

**Comment by hiroshi-nakajima345** [comment]
①In eclipse such as this comment are revealed(see-added screenshot 213).
How am I able to change  the port number of visual studio code? or is there any other way exist.
I am thanks full to teach me the method.
This case may be appeared when we use the same code in eclipse & visual studio code or  apache NetBeans.
②I cancel my first inquiry. pardon me.

----- 元のメッセージ -----
From: "VS Code Issue Triage Bot" ***@***.***>
宛先: "microsoft/vscode" ***@***.***>
Cc: "hiroshi-nakajima345" ***@***.***>, "Author" ***@***.***>
送信済み: 2021年04月07日 午後 8:28
件名: Re: [microsoft/vscode] やはり、改善の動きはないように見えます (#120017)

>  Closed #120017.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
