### ISSUE TITLE
CLI tools (`code.cmd`) won't run without code signing

### ISSUE THREAD

**Issue by serverhorror** [microsoft/vscode#120088]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Activate Windows Defender
2. Install VS Code (user install)
3. Install CLI tools
4. run cli tools (`C:\Users\marcherm\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd`)
5. Receive error message

```powershell
> code .
This program is blocked by group policy. For more information, contact your system administrator.
```

Does this issue occur when all extensions are disabled?: Yes

(I am unable to run the command due to the restrictions from Windows Defender)

I believe if the CLI tools where signed, just like the VS Code binary itself, this would allow the CLI tools to run. Our setup has a specific `PATH` where scripts can run from, being able to install to a specific location would also allow to use CLI tools again.

**Comment by joaomoreno** [comment]
Are you sure `.cmd` files can be signed?

**Comment by serverhorror** [comment]
> Are you sure `.cmd` files can be signed?

To be honest, I have no clue. I was told by the IT admins that this is the solution. I'm sorry if that points in the wrong direction.

If I could configure the place where VS Code generates/places its scripts that would work as well.

**Comment by serverhorror** [comment]
What might be interesting:

I am using the user installation, so the actual binaries run fine from `$env:LOCALAPPDATA\Programs\Microsoft VS Code\Code.xe`, but the scripts:

* `$env:LOCALAPPDATA\Programs\Microsoft VS Code\bin\code` and
* `$env:LOCALAPPDATA\Programs\Microsoft VS Code\bin\code.cmd`

fail. Like this:

```
PS C:\Users\...\AppData\Local\Programs\Microsoft VS Code> code
This program is blocked by group policy. For more information, contact your system administrator.
PS C:\Users\...\AppData\Local\Programs\Microsoft VS Code> code.cmd
This program is blocked by group policy. For more information, contact your system administrator.
```

**Comment by joaomoreno** [comment]
Right, can you ask your system administrators to allow Code's cmd script to run on your system?

**Comment by serverhorror** [comment]
I did, won't happen. That's why I thought it would be good idea to let users place it somewhere or -- if possible -- sign it (if that helps).

It's a corporate setting where the outlook of changing their ways is way below VS Code changing it (I know...).

I do have a workaround and copied the CLI tools to the "endorsed" place, would be just more convenient to have a setting for this.

**Comment by joaomoreno** [comment]
That's too bad, but I'm glad you found a workaround! It's hard to get a setting for it, since a setting can't affect where the CLI script is located, and signing CMDs isn't really a thing AFAIK. Closing for now.
