### ISSUE TITLE
HELP opening vscode from powershell opens cli.js

### ISSUE THREAD

**Issue by bckelley** [microsoft/vscode#120099]
Cross Posted
- VS Code Version: 1.54.3
- Powershell Version: 5.1.18362.752
- OS Version: 10.18362.0

![terminal-(code  )](https://user-images.githubusercontent.com/15696431/112847462-b7d52900-906c-11eb-8ef6-5c6eaeb1c79f.JPG)
![code](https://user-images.githubusercontent.com/15696431/112847484-bdcb0a00-906c-11eb-82a9-a19ec9c04fe8.JPG)

Steps to Reproduce:

1. Go to powershell `cd` to the working directory and type `code .`
2.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
Is `code` pointing to `code.cmd` or something else?

**Comment by bckelley** [comment]
well since it opens something in vscode I'm assuming it's pointing to code.exe

**Comment by Tyriar** [comment]
The issue may be you have VS Code's root install dir on your `$PATH` then, not the `bin` dir

**Comment by bckelley** [comment]
yea that's it. I just deleted that but how do I fix that? VSCode isn't installed to the C drive

Installed drive is: `D:\Program Files\Microsoft VS Code\`

**Comment by Tyriar** [comment]
You can edit your system's environment variables through the start menu, make sure `D:\Program Files\Microsoft VS Code\bin` is there instead of `D:\Program Files\Microsoft VS Code\`

**Comment by bckelley** [comment]
> D:\Program Files\Microsoft VS Code\bin

wait that's what I had before. I know that vscode shouldn't open cli.js so how does this get fixed??

**Comment by bckelley** [comment]
Sure,

```
❯ Get-Command code
Get-Command: The term 'code' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
