### ISSUE TITLE
VSCode updates fail to update since upgrading to native ARM version

### ISSUE THREAD

**Issue by pogilvie** [microsoft/vscode#120020]
- VS Code Version: Version: 1.54.1 (Universal
- OS Version: 11.2.3 (M1)

Steps to Reproduce:

1. Start VSCode a popup says 'restart to apply new update
2.Restart VSCode and it does another download and starts the cycle again.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Since upgrading to the M1 native vscode updates have been broken.   To be fair vscode is not the only app on my Mac which is having update troubles on Big Sur M1.    Before I try it are there any workarounds short of deleting the app and reinstalling from scratch?

Thank you for all your work on this software which is the center of my professional life.

**Comment by pogilvie** [comment]
<img width="1028" alt="Screen Shot 2021-03-27 at 6 37 17 AM" src="https://user-images.githubusercontent.com/628688/112723385-6c374980-8ecb-11eb-8fd6-9af967e20456.png">

**Comment by aksdevac** [comment]
for me issue is still present on intel mac (late 2016). on Mac OS `11.2.3` , it downloads the update & then does not restart & If I manually restart it starts download again, this was on latest `1.54.x`, today manually updated on `1.55.0` so not tested on this version.

**Comment by pogilvie** [comment]
hum sounds like it might be Big Sur issue then

**Comment by aksdevac** [comment]
today checked on `1.55.0` MacOS `11.2.3` intel MBP  , restart to update is still not working. it never restarts & starts download again on manual restart.

**Comment by pogilvie** [comment]
Yes, I'm still stuck too.  Interesting that my intel laptop is having no issues.    I'm looking at the vscode logs and I'm seeing.

```
Apr  9 19:04:48 Peter-Ogilvie com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[99332]): Service could not initialize: 20D91: xpcproxy + 23712 [839][75A06642-92A3-341F-9E53-0360AAB45CA0]: 0xd
Apr  9 19:04:48 Peter-Ogilvie com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[99332]): Service exited with abnormal code: 78
Apr  9 19:04:48 Peter-Ogilvie com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
```

I'm not sure what the normal logs look like.   Are you seeing these errors?

**Comment by deepak1556** [comment]
Are you launching vscode as root ? Can you confirm who owns `~/Library/Caches/com.microsoft.VSCode.ShipIt` and `/Applications/Visual Studio Code.app`

**Comment by aksdevac** [comment]
@deepak1556 for my case (intel mac & VS code version `1.55.2` ) ownership is with my user only (its not root) & here are some logs (its similar to what @pogilvie  sent) :
```log
May  6 11:23:17 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.502.100008.Aqua): com.microsoft.VSCode.ShipIt (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
May  6 11:23:17 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12451]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:17 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12451]): Service exited with abnormal code: 78
May  6 11:23:17 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
May  6 11:23:18 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0200-0000-0000-000000000000[12421]): Service exited due to SIGKILL | sent by mds[88]
May  6 11:23:19 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12452]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:19 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12452]): Service exited with abnormal code: 78
May  6 11:23:19 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
May  6 11:23:21 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12453]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:21 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12453]): Service exited with abnormal code: 78
May  6 11:23:21 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
May  6 11:23:23 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12455]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:23 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12455]): Service exited with abnormal code: 78
May  6 11:23:23 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
May  6 11:23:25 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12456]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:25 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12456]): Service exited with abnormal code: 78
May  6 11:23:25 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
May  6 11:23:25 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0A000000-0300-0000-0000-000000000000[12445]): Service exited due to SIGKILL | sent by mds[88]
May  6 11:23:27 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12458]): Service could not initialize: 20E241: xpcproxy + 23787 [839][174A7403-B45C-3AF2-B778-6E7D0C20363B]: 0xd
May  6 11:23:27 Akashs-MacBook-Pro com.apple.xpc.launchd[1] (com.microsoft.VSCode.ShipIt[12458]): Service exited with abnormal code: 78
```

& this messages are repeated continuously & vscode never restarts automatically after downloading update.

**Comment by aksdevac** [comment]
@deepak1556 btw for now manually updated to `1.56.0`, & now tried this solution will report it issue exists when next update arrives;
https://github.com/Microsoft/vscode/issues/43793#issuecomment-403040446

**Comment by pogilvie** [comment]
@deepak1556 

```
peter::/Applications-> ls -ld Visual\ Studio\ Code.app/
drwxr-xr-x@ 3 peter  staff  96 Apr 13 10:03 Visual Studio Code.app//
```

BTW I finally gave up and deleted the old copy that was not updating and downloaded the latest and re-installed.   I don't think there's been an update since I did this.

**Comment by deepak1556** [comment]
>  downloaded the latest and re-installed

Understood, please also delete `~/Library/Caches/com.microsoft.VSCode.ShipIt`.

**Comment by pogilvie** [comment]
Thank you!  I've deleted the ShipIt cache. This issue popped up after I installed the first vscode universal binary (with ARM support).   I didn't delete this cache after I did that.   I'm hopeful that the updates will start working again after this step.  

I'll try and remember to let you know if the next universal update goes well.

**Comment by aksdevac** [comment]
@deepak1556 Hi, it is now working now (updated to `1.56.0` to `1.56.1`) deleting cache solution from https://github.com/microsoft/vscode/issues/43793#issuecomment-403040446 worked for me.

**Comment by pogilvie** [comment]
It's been working well for me across several releases on both intel and arm.    Issue appears resolved to me.
