### ISSUE TITLE
Terminals created in the background by the API will not display/retain any output until the terminal panel is initialized

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12000]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/266

**Comment by Tyriar** [comment]
@dbaeumer FYI you will likely hit this eventually due with background tasks. Output will not be recorded until the terminal panel has been pulled up at least once.

**Comment by dbaeumer** [comment]
@Tyriar thanks for pointing this out. Yes, would not be nice since we would loose output parsing...
