### ISSUE TITLE
Getting Started: Allow arguments to be passed to the command

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120047]
Was experimenting with getting started in Luna Paint, and while I still think I typically won't need any buttons (https://github.com/microsoft/vscode/issues/119709) if I did have a button I'd expect the most comman command I'd use it to open an image editor which with width/height auto filled which can only be done via args. Something like this is what I'm after:

```json
"button": {
  "title": "Open editor",
  "command": "luna.file.new",
  "args": {
    "width": 800,
    "height": 600
  }
}
```

I can work around this for my case, but it seems like a good addition in general.

**Comment by JacksonKearl** [comment]
Using new MD contribution model, able to pass arguments as URI-encoded JSON-encoded values, using same logic as opener service...

[Open Markdown File](command:toSide:workbench.action.quickOpen?%22.md%22)
[Open Markdown File](command:toSide:workbench.action.quickOpen?%22.md%22)
[Open HTML File](command:toSide:workbench.action.quickOpen?%22.html%22)
[Add a keybinding](command:workbench.action.openGlobalKeybindings?%22md-to-html.convertToHTML%22)
