### ISSUE TITLE
Getting Started: Consider changing use of "tasks"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120049]
I'm not sure we want to overload this term? Tasks already have strong meaning in vscode.

![image](https://user-images.githubusercontent.com/2193314/112756833-bd167300-8f9b-11eb-885f-eca38d7a459f.png)

Maybe too late to change?

**Comment by JacksonKearl** [comment]
Steps? Not too late, still "experimental" :)

**Comment by Tyriar** [comment]
Steps, entries, items all good candidates

**Comment by JacksonKearl** [comment]
Using `steps` now, `tasks` will still work but is deprecated.
