### ISSUE TITLE
VSCode gets transparent and shows what's behind it when minimize and re maximize it

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120027]
- VS Code Version: 1.55.0 Insider d06d2f1
- OS Version: Windows 10 20H2 Build 19042.572

**Steps to Reproduce:**
In this example chrome in the back with GitHub website and vscode in the front. When minimize and re maximize vscode gets transparent and shows chrome behind it. I don't know if that's Electron issue or VSCode specific.

![X](https://user-images.githubusercontent.com/17777237/112728828-d256b780-8f31-11eb-8ba3-48f220c40f80.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This sounds more like an Electron and/or Chrome behaviour to me.

**Comment by deepak1556** [comment]
Unable to repro with recent versions.
