### ISSUE TITLE
PHP "static" keyword with wrong scope

### ISSUE THREAD

**Issue by andregalastri** [microsoft/vscode#120042]
- VS Code Version: 1.54.3
- OS Version: Ubuntu Desktop 20.04

Steps to Reproduce:

1. Create a new PHP file
2. Paste the example code below
```php
<?php
class Authentication
{
    private static $authTag;
    
    public static function setTag($authTag)
    {
        session_start();
        self::$authTag = $authTag;
    }
}
```

Does this issue occur when all extensions are disabled?: **Yes**

## Explanation
When used with a property, `static` keyword is setted as `support.class.php` scope.
When used with a method, `static` keyword is setted as `storage.modifier.php` scope.

Print without extensions, default Dark+ theme.
![image](https://user-images.githubusercontent.com/49572917/112748050-ab2ed300-8f8f-11eb-9471-94aa09c73f05.png)
![image](https://user-images.githubusercontent.com/49572917/112748548-a586bc80-8f92-11eb-8aee-53b6fb130f61.png)

## Suggestion
I don't understand much about syntax highlight, but I was looking in the [php.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/php/syntaxes/php.tmLanguage.json) file and this bug, apparently, has something with this line.
https://github.com/microsoft/vscode/blob/c0fa3dfd3e252792efbae044c44c3bbb90c5b093/extensions/php/syntaxes/php.tmLanguage.json#L1170

When I change its value to `storage.modifier.php`, the bug is gone.
![image](https://user-images.githubusercontent.com/49572917/112748594-129a5200-8f93-11eb-8cf4-89e264f24fbd.png)

Please, note that I'm not saying that this is the fix to this bug. I didn't tested anything more than just changing the value of the parameter.  I'm just guessing that this line has something to do with the bug.

Thank you!

**Comment by roblourens** [comment]
Moved this to the upstream repo: https://github.com/atom/language-php/issues/419
