### ISSUE TITLE
Error installing vscode.d.ts: Request returned status code: 404

### ISSUE THREAD

**Issue by itowlson** [microsoft/vscode#120064]
- VS Code Version: 1.54.3
- OS Version: Ubuntu 18.04 on Windows 10

Steps to Reproduce:

1. I cloned a VS Code extension repo and did `npm install --no-save`
2. NPM reported the following error:
```
etected VS Code engine version: ^1.30.0
Error installing vscode.d.ts: Error: Request returned status code: 404
Details: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/releases/stable</pre>
</body>
</html>
```

Similar to https://github.com/microsoft/vscode/issues/74732 but that is closed and locked so I can't report the current issue there,

If I visit https://vscode-update.azurewebsites.net/api/releases/stable in the browser it also gives me `Cannot GET /api/releases/stable`.

Does this issue occur when all extensions are disabled?: N/A

**Comment by IllusionMH** [comment]
> I cloned a VS Code extension repo and did npm install --no-save

What repo is it?

Looks like duplicate of #119822 if that extension uses old `vscode` package.
See https://github.com/microsoft/vscode/issues/119822#issuecomment-806489621 for details

/cc @joaomoreno

**Comment by joaomoreno** [comment]
What's the VS Code extension? They should update to the latest `vscode` module, if possible.

**Comment by itowlson** [comment]
Thanks @joaomoreno - updating the package reference fixed it.
