### ISSUE TITLE
Terminal environmentVariableCollection should respect clearing entries

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120077]
https://github.com/microsoft/vscode/runs/2216043935?check_suite_focus=true#step:15:431

```
1 failing
  1) vscode API - terminal
       Terminal
         environmentVariableCollection
           should respect clearing entries:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode\vscode\extensions\vscode-api-tests\out\singlefolder-tests\terminal.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by Tyriar** [comment]
Confirmed still flaky, 7 failures in last 30 days:

![image](https://user-images.githubusercontent.com/2193314/143913956-d080868f-6ed0-43a5-9e1d-4b790ec27a6b.png)

**Comment by Tyriar** [comment]
This sort of thing is really hard to diagnose as the timeout is the test one, I'll try tweak the terminal integration tests to make any polling throw its own exception after a short period of time.
