### ISSUE TITLE
c_cpp_properties.json includePath is not finding C++ header files in project folder.

### ISSUE THREAD

**Issue by kdemello1980** [microsoft/vscode#120184]
When creating a C++ source and header file pair, the header file is not found, resulting in an error being shown in the source.  Despite the error, intellisense is able to parse the content for code completion.  If I hard-code the relative path in the source file the error goes away.

`#include "foo.h" // Error.`
`#include "../include/foo.h" // No error.`

It seems like `${workspaceFolder}**` in the `includePath` of c_cpp_properties.json is not being parsed properly, but the problem persists if the include path is hard coded in c_cpp_properties.json (see Screenshot_2021-03-30_11-18-30.png), so it seems like it applies to all header files in the project folder.  Include paths to libraries outside of the project folder are included properly.

I have created a minimal C++ project that replicates the problem, and uploaded it, a screenshot, and the associated .vscode directory and made it available at [https://github.com/kdemello1980/vscode_bug](https://github.com/kdemello1980/vscode_bug).

**Comment by IllusionMH** [comment]
/extCpp

Functionality for C++ provided by extension and should be reported in extension repo.
