### ISSUE TITLE
Add skip button inside new welcome page.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120160]
For example here if user for some reason doesn't want to sync his settings and at the same time want to check this card it's not possible now, In this case if there's a button to skip/dismiss this card it 'll be convenient.  

![image](https://user-images.githubusercontent.com/17777237/112962552-ca239580-9146-11eb-873f-c83b4e70fa79.png)
![image](https://user-images.githubusercontent.com/17777237/112963254-7b2a3000-9147-11eb-8ef9-cc5e85e0d784.png)

**Comment by pixieaka** [comment]
@JacksonKearl  Aha!. But this can be hard to find

**Comment by pixieaka** [comment]
@JacksonKearl If you don't tell me about it I can't find it with my self.

**Comment by pixieaka** [comment]
@JacksonKearl I have an idea about this. Can this automatically checked if user display the card. Because indication here about deliver the user information not to force him to do action or hardly checked by his self.

**Comment by JacksonKearl** [comment]
I'd rather not check off immediately on open, as that makes it hard to keep track of which items you might want to revisit. Thinking some about it I don't really know any better area to have the skip button, especially as we're planning on removing the "next" button to help declutter the tile. 

As such I'm going to close this as-designed. If you really want, feel free to submit a design proposal and I may re-open. 🙂
