### ISSUE TITLE
Insiders icon becomes garbled

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#120193]
Version: 1.55.0-insider
Commit: d06d2f1d6245ce00b1c36a9cd81a9087d225173e
Date: 2021-03-26T13:57:45.993Z (4 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.2.0

I'm not sure how to reproduce this. I downloaded VSCode insiders and everything was fine. At some point later, maybe a couple days, the icon became garbled. I am developing extensions, so maybe that's related somehow?

To make it weirder, only certain scales of the icon are garbled. As in, if the icon is displayed at ~64x64 or less, it is garbled. But when displaying at larger scales, it is fine.

The issue is still present when the app is not running, or when running with extensions disabled.

**Comment by IllusionMH** [comment]
Could you please provide screenshots of the problem as it's hard to understand what actually happens.

**Comment by misolori** [comment]
This is an electron issue, upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=1068170. I am not aware of any workarounds at the moment.

We already have this issue https://github.com/microsoft/vscode/issues/118754 so closing as a duplicate.
