### ISSUE TITLE
Automaticly assign Tab name from file content

### ISSUE THREAD

**Issue by EnolCook** [Microsoft/vscode#12017]
One really usefull feature of Sublime Text (and some other Text Editor) is that the tabs are automaticly named by the beginning of a file openned in it.
You can easly create new tab and write things and find them between other openned tabs.

As the Hot File saving feature is comming, this feature is also really important to find the tab you want faster than seeking trough your openned tab.

How it works right now in VSCode:
![vscode](https://cloud.githubusercontent.com/assets/10771995/18511880/97cfe4c0-7a86-11e6-91d2-534df02cf4f8.PNG)

How Sublime Manage tabs:
![vscode_sublime](https://cloud.githubusercontent.com/assets/10771995/18511887/9f8b3e4e-7a86-11e6-96f7-4b1b4a16b397.PNG)

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
