### ISSUE TITLE
Marketplace: Show what version of VS code an extension is for in the version history page

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#120197]
Our extension has this list currently:

![image](https://user-images.githubusercontent.com/19672699/113047104-bd5a6e00-9155-11eb-8ca0-da95e8de6252.png)

Some of these work with insiders and some of these work with VS code. Users frequently try installing the latest version and don't realize why it doesn't work with their version of VS code. 

Some indication of the version a vsix works with would be nice (or some way for us to put it into the version information).

**Comment by sandy081** [comment]
Moved to https://github.com/microsoft/vsmarketplace/issues/43
