### ISSUE TITLE
Opend python files displayed in wrong way.

### ISSUE THREAD

**Issue by royfhs** [microsoft/vscode#120155]
Issue Type: <b>Bug</b>

正常打开python工程，部分python文件会显示为乱码。

Sometimes, open py file as usual, you'll see py files displayed in wrong ways, whole editor window is filled with marks unreadable.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.36GB free)|
|Process Argv|--crash-reporter-id 759ce638-b9e1-4708-b3d3-8c07cc3e1e51|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
jslint|ajh|1.2.1
vscode-django|bat|1.4.0
shell|bbe|0.3.0
python-extension-pack|don|1.6.0
shell-format|fox|7.0.1
go|gol|0.23.3
mysql-syntax|jak|1.3.1
protobuf|kan|1.1.6
vscode-leetcode|Lee|0.17.0
MagicPython|mag|1.1.0
vscode-docker|ms-|1.11.0
vscode-language-pack-zh-hans|MS-|1.54.2
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
go-critic|nev|0.1.0
vscode-protolint|ple|0.5.1
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.2.0
jinja|who|0.0.8
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontbcf:30265426
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by chrmarti** [comment]
Could you attach a screenshot of how it should look like and how it sometimes is shown incorrectly?

**Comment by royfhs** [comment]
I checked py files again, I think it's my fault which I pulled wrong files and opened it as py files. Sry for mistaken it. Have a good
