### ISSUE TITLE
PowerShell not showing up in Profiles on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#120135]
![image](https://user-images.githubusercontent.com/2644648/112908406-50d36680-90a4-11eb-8108-c9aac42e4fbb.png)
![image](https://user-images.githubusercontent.com/2644648/112908435-6183dc80-90a4-11eb-8b52-1a7eb30caa69.png)

terminal related settings:

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": []
```

PowerShell's installed:

PowerShell 7.2.0-preview.4 (`pwsh-preview`)
Windows PowerShell

**Comment by Tyriar** [comment]
Can you turn on trace logging and check the ext host output channel for profile-related logs?

**Comment by TylerLeonhardt** [comment]
```
[2021-03-29 15:44:49.624] [exthost] [info] WSL is not installed, so could not detect WSL profiles
[2021-03-29 15:44:51.593] [exthost] [trace] profile not validated Cygwin ["C:\\cygwin64\\bin\\bash.exe","C:\\cygwin\\bin\\bash.exe"]
[2021-03-29 15:44:51.637] [exthost] [info] WSL is not installed, so could not detect WSL profiles
``` 

not much...

**Comment by TylerLeonhardt** [comment]
verification steps: PowerShell should be detected in Profiles

**Comment by Tyriar** [comment]
@TylerLeonhardt did we get this fix cherry picked to main?

**Comment by TylerLeonhardt** [comment]
@Tyriar oops will do!
