### ISSUE TITLE
Can't open image diff editor left side

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120110]
I hit this in Remote WSL, not sure if relevant.

1. Have an image committed to a git repo
2. Change it
3. Open the diff editor from the SCM view

🐛 Left side is unopenable.

![image](https://user-images.githubusercontent.com/22350/112860024-4abf9480-9068-11eb-8303-a3a59eeae469.png)

**Comment by mjbvz** [comment]
Duplicate of #86611
