### ISSUE TITLE
Cannot download a VSCode instance for testing

### ISSUE THREAD

**Issue by kysewtts** [microsoft/vscode#120171]
While downloading a VSC instance from https://vscode-update.azurewebsites.net/api/releases/stable to run some tests, an error pops in with code 404. It says "Cannot GET /api/releases/stable"

**Comment by IllusionMH** [comment]
/duplicate of #119822
See https://github.com/microsoft/vscode/issues/119822#issuecomment-806489621 for details and migration steps
