### ISSUE TITLE
Workspace trust extension API

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#120173]
## Extension API
As described above, the first step to using the API is adding the static declarations to your `package.json`. The easiest method of onboarding would be to use the *onStart* value for the `required` property. Once again, this is the default behavior even if you do nothing, but it's a great signal to the user that you have made a deliberate choice. In this case, your extension does not need to do anything else. It will simply not be activated until trust is given and your extension can know that it is executing with the consent of the user. However, if your extension only requires trust for part of its functionality, this is likely not the best option.

For extensions that wish to gate their features on Workspace Trust, they should use the *onDemand* value for the `required` property, and we provide the following API:

```typescript
export enum WorkspaceTrustState {
  /**
   * The workspace is untrusted, and it will have limited functionality.
   */
  Untrusted = 0,

  /**
   * The workspace is trusted, and all functionality will be available.
   */
  Trusted = 1,

  /**
   * The initial state of the workspace.
   *
   * If trust will be required, users will be prompted to make a choice.
   */
  Unspecified = 2
}

/**
 * The event data that is fired when the trust state of the workspace changes
 */
export interface WorkspaceTrustStateChangeEvent {
  /**
   * New trust state of the workspace
  */
  readonly newTrustState: WorkspaceTrustState;
}

/**
 * The object describing the properties of the workspace trust request
 */
export interface WorkspaceTrustRequestOptions {
  /**
   * When true, a modal dialog will be used to request workspace trust.
   * When false, a badge will be displayed on the Setting activity bar item
   */
  readonly modal: boolean;
}

export namespace workspace {
  /**
   * The trust state of the current workspace
   */
  export const trustState: WorkspaceTrustState;

  /**
   * Prompt the user to chose whether to trust the current workspace
   * @param options Optional object describing the properties of the
   * workspace trust request
   */
  export function requestWorkspaceTrust(options?: WorkspaceTrustRequestOptions): Thenable<WorkspaceTrustState | undefined>;

  /**
   * Event that fires when the trust state of the current workspace changes
   */
  export const onDidChangeWorkspaceTrustState: Event<WorkspaceTrustStateChangeEvent>;
}
```

The crux of the API surface is at the bottom. We provide a property to get the current Workspace Trust state, an asynchronous method to request Workspace Trust to the user, and finally an event for listening to Workspace Trust state changes.

You will notice that the method to require Workspace Trust `requireWorkspaceTrust(options?: WorkspaceTrustRequestOptions)` takes an optional argument with a `modal` property. This `modal` value describes how the request should be surfaced to the user. It should be set to:
- **true** - when the requirement is in response to an explicit user action. For example, suppose you have a command that requires Workspace Trust to run. When the user explicitly runs this command, you should require workspace trust with this value set to *true* and await the result. This will trigger a prompt to the user with a modal dialog and should be used for explicit actions only.
- **false** - when the requirement is for a background feature of your extension. For example, suppose you want to use the workspace version of a node module to provide errors. In this case, it is best to call the function with this value set to *false* and await the result. This will trigger a UX indication that Workspace Trust is being requested but will not interrupt the user.

## Extension manifest

Extension authors will be able to declare in the extension manifest the workspace trust requirements for the extension:

```typescript
workspaceTrust: { request: 'never' } | {
  request: 'onDemand' | 'onStart',
  description: string
}
```

For the `required` property, the following values are accepted:
- **false** - The extension does not require workspace trust to perform any functionality.
- **'onDemand'** - The extension functions partially without workspace trust. Some features will be disabled until workspace trust is granted. The extension can use API to gate features.
- **'onStart'** - The extension cannot function without workspace trust. It will remain disabled until workspace trust is given.

For the `description` property, a description of why trust is needed may be provided to help the user understand what features will be disabled or what they should review before granting or denying workspace trust.

For the `safeSettings` property, a list of settings may be provided that the extension can safely read from the workspace even when the workspace is not trusted. More detail is provide on this topic below. Note that this value is relevant only when the `required` property is set to `false` or `'onDemand'` as the extension will be disabled in untrusted workspaces for `'onStart'`.

**Comment by mjbvz** [comment]
From our discussion this morning:

- Rename `requireWorkspaceTrust` -> `requestWorkspaceTrust`
- `requestWorkspaceTrust` should return undefined if the user cancels. This makes it consistent with our other input apis
- Properties on `WorkspaceTrustRequestOptions` and `WorkspaceTrustStateChangeEvent` should be readonly

Other ideas we discussed but did not settle on:

- Potentially rename `WorkspaceTrustState.Unknown` to `WorkspaceTrustState.Undecided`? 
- Instead of `onDidChangeWorkspaceTrustState`, should we use have an `onDidGainTrustEvent`

**Comment by lszomoru** [comment]
Thanks @mjbvz. The three items listed in the first group are all now in the `main` branch. 

Some comments on the ideas that were discussed in the meeting:
> Potentially rename WorkspaceTrustState.Unknown to WorkspaceTrustState.Undecided?

This sounds like a reasonable suggestion.

>  Instead of `onDidChangeWorkspaceTrustState`, should we just have an `onDidGainTrustEvent` event?

Exposing only a `onDidGainWorkspaceTrustEvent` event to extensions certainly simplifies things and makes things more transparent. In the future as we make improvements to workspace trust state transitions, we will have to add a new event for revoking workspace trust. 
 
 @sbatten, any thoughts on this?

**Comment by lszomoru** [comment]
@mjbvz, we have closed on the two suggestions. What should be the next step here? Thanks!

**Comment by sbatten** [comment]
Proposal to simplify
https://github.com/microsoft/vscode/pull/121141

**Comment by sbatten** [comment]
Simplified version of API has been merged
