### ISSUE TITLE
Global search spawn error (v1.54.3)

### ISSUE THREAD

**Issue by j-low** [microsoft/vscode#120114]
Trying to run a global search immediately fails and renders the following error:
![Screen Shot 2021-03-25 at 9 21 26 PM](https://user-images.githubusercontent.com/6320333/112863835-e0fdb580-907c-11eb-8c12-3ed403c59f0d.png)

Threads for a couple similar-seeming issues suggested checking that the file at the indicated URL actually exists which I have confirmed.

- VS Code Version: 1.54.3 (Universal)
- OS : Darwin x64 ~19.6.0~ 20.3.0 / Big Sur 11.2.3 (upgraded OS during troubleshooting)
- Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
- Date: 2021-03-15T11:57:12.728Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0

Steps to Reproduce:

1. Simply run any global search

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Is there any reason you wouldn't have permission to access that binary? Can you run it from a terminal?

**Comment by j-low** [comment]
> Is there any reason you wouldn't have permission to access that binary? Can you run it from a terminal? 

None that I'm aware of.  When I run from terminal it seems to at least execute:
```
$. /rg
error: The following required arguments were not provided:
    <PATTERN>

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help
```

> Did you install VS Code in an unusual way or as a different user?

Not that I am aware of; certainly not as a different user.  I recently re-installed VS Code for troubleshooting purposes but did so strictly through the the normal download/install flow.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by roblourens** [comment]
I think the next possibility is that the problem is with one of those folders. Do you get the same error when searching other folders?

You can also try running the exact command yourself to see if you get the same result. For example,

```
cd /Users/jlow/Dev/random-scripts
/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --hidden --case-sensitive -g '**/*.tsx/**' -g '**/*.tsx' -g '!**/.git' -g '!**/.svn' -g '!**/.hg' -g '!**/CVS' -g '!**/.DS_Store' -g '!**/node_modules' -g '!**/bower_components' -g '!**/*.code-search' --max-filesize '17179869184' --no-ignore-parent --follow --crlf --auto-hybrid-regex --regexp 'test' --no-config --no-ignore-global --json -- '.'
```

**Comment by j-low** [comment]
Ok looks like your intuition was correct.  Removing the problem folder solved the issue.  Thanks for your help, @roblourens.

**Comment by roblourens** [comment]
Great, out of curiosity, where did the issue come from?

**Comment by j-low** [comment]
The `cockroachdb/ui` and `dsa` paths broke search.  I don't have the slightest clue as to why but adding/removing each of them toggles search between broken/working state.
