### ISSUE TITLE
Multi-Root task provider (Add root-directory and workspace-name properties to Task)

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode#120133]
This issue is related to task provider behaviour in a multi-root workspace set up.
Consider this multi-root workspace:
![image](https://user-images.githubusercontent.com/16143955/112901049-1c0de200-9099-11eb-8cb3-ae4025b36cc7.png)

and let's say I want to configure a new task for a .cpp file in `Root3`. This is what I get by running "Configure Task" (the other root's tasks will be shown as well).
![image](https://user-images.githubusercontent.com/16143955/113948520-e916cd00-97c1-11eb-8e56-96ede09b5fb8.png)

A similar issue arises when trying to set a default task in `Root3`. there can be other defaults in every root. but the default is picked from `root1`.
![image](https://user-images.githubusercontent.com/16143955/113948685-4f035480-97c2-11eb-83d5-f48f336f2d0a.png)

@alexr00  I know you are tracking this issue already. Just for having it all in one place, I put the related issues here:
https://github.com/microsoft/vscode/issues/111037 
https://github.com/microsoft/vscode/issues/99276 (possibly showing the tasks for the working directory on the top of the list of the tasks, e.g. https://github.com/microsoft/vscode/issues/89448).
https://github.com/microsoft/vscode/issues/35312 

The same issue may need to be resolved if multiple workspaces is going to be supported:
https://github.com/microsoft/vscode/issues/43188

**Comment by alexr00** [comment]
@elahehrashedi you can provide a `WorkspaceFolder` as the `Task` scope. Does that solve this for you?

https://github.com/microsoft/vscode/blob/02d38098249bfaff610704d74031a2530126eb6f/src/vs/vscode.d.ts#L6576-L6577

**Comment by elahehrashedi** [comment]
@alexr00 kindly, no, that doesn't solve the issue. I have tried both WorkspaceFolder and TaskScope.Workspace.

**Comment by elahehrashedi** [comment]
@alexr00 I modified the issue report to show the results when using `WorkspaceFolder ` instead of `TaskScope.Workspace`.
The issue is still there.

**Comment by alexr00** [comment]
> let's say I want to configure a new task for a .cpp file in Root3. This is what I get by running "Configure Task" (the other root's tasks will be shown as well).

It is expect that we show all tasks from all sources when you run "Configure Task". I think this is the correct behavior, though the grouping/sorting could be improved as said in the issue linked (https://github.com/microsoft/vscode/issues/89448).

The issue you show with default build task is definitely a deficiency. Tracked by https://github.com/microsoft/vscode/issues/35312, which will investigate fixing for the June release. Thank you @elahehrashedi for bringing it to my attention!
