### ISSUE TITLE
Sidebar panels should have individual widths

### ISSUE THREAD

**Issue by jakeparis** [microsoft/vscode#120177]
Issue Type: <b>Feature Request</b>

Various panels in the sidebar work best at different widths. For example, extensions sidebar is helpful at a very wide width, while the file explorer doesn't need to be so wide. 

It would be a great setting if each sidebar panel would remember it's own width and automatically switch to it when switching to that panel. 

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
@chrmarti SteVen owns the workbench. layout.

**Comment by jakeparis** [comment]
@sbatten For the record, in regards to your https://github.com/microsoft/vscode/issues/100318#issuecomment-656209711  about the UI when the panel shrinks and grows: this exact UI is already implemented in the Vivaldi browser in the sidebar panels. The UI is not bad.

In terms of process, it seems unfair to auto-close the old feature-request due to lack of votes, and then close this one because the issue had been previously requested. Why don't you leave this one open to see if it can garner more support?

**Comment by sbatten** [comment]
@jakeparis Thank for the pointer to Vivaldi as an example UI for reference. I am happy to re-open this issue to follow the same process as #100318, however I want to remind that even if it makes it onto our backlog, it is not guaranteed to be scheduled for work.

**Comment by jakeparis** [comment]
In case you don't want to download Vivaldi just to see this in action (though there are plenty of other good reasons to do so): here's what it looks like: 

![2021-03-31_13-27-50](https://user-images.githubusercontent.com/7408985/113186039-25c45080-9225-11eb-86c6-a38effbc8ff9.gif)
