### ISSUE TITLE
[liveshare][node(preview)]: Node.js debugger initializes twice causing duplication in call stack

### ISSUE THREAD

**Issue by smvanderweide** [microsoft/vscode#120194]
When the new in-preview node debugger is used, the debugger initializes twice. This duplication is easiest to see in the call stack of a Live Share guest (_See images below for the difference between the new and legacy node debuggers in the Live Share guest UI_). It also happens when no Live Share session is running, though it does not appear in the UI. The two processes have different names, IDs, and trace information, but it appears that vscode is handling this so that only one process appears. 

Is this duplicate initialization an intentional part of the new node debugger? If so, how should we be handling it so that the processes appear correctly in the UI?

Call stack of Live Share guest using legacy node debugger
![image](https://user-images.githubusercontent.com/54870310/113042517-28a14180-9150-11eb-9564-97045769710e.png)

Call stack of Live Share guest using new node debugger 
![image](https://user-images.githubusercontent.com/54870310/113042641-466ea680-9150-11eb-9995-999cc3a446f3.png)

- VS Code Version: 1.54.3 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
(Using current Live Share extension)
1. Open a node.js console application in vscode and set a breakpoint. 
2. Start a Liveshare session in that vscode window, and join it from a new vscode window. We’ll call this new window the guest.
3. In the original window, start debugging. Make sure you are using the new node debugging and not node legacy.
4. Observe the call stack on the guest. Note the duplication.

Does this issue occur when all extensions are disabled?: Yes/No
N/A

**Comment by weinand** [comment]
Without LiveShare the second session would become a child of the first session. And in this case VS Code will collapse the nodes into one. So the CALLSTACK of the new debugger would look almost identical as the legacy debugger.

The linking of parent and child sessions happens outside DAP via VS Code Extension API. Could it be that LiveShare misses that?

**Comment by connor4312** [comment]
/duplicate https://github.com/MicrosoftDocs/live-share/issues/3515

**Comment by smvanderweide** [comment]
It is very likely that LiveShare is not linking the processes properly. @weinand could you point me to where the linking of parent and child sessions is happening in the VS Code Extension API, so that I can correct the behavior on the LiveShare guest. Thanks!

**Comment by weinand** [comment]
@smvanderweide the parent/child linking is done via the [`DebugSessionOptions`](https://github.com/microsoft/vscode/blob/1c27a2851752f1fcdaf266127752081048499934/src/vs/vscode.d.ts#L11939) argument of the [`vscode.debug.startDebugging`](https://github.com/microsoft/vscode/blob/1c27a2851752f1fcdaf266127752081048499934/src/vs/vscode.d.ts#L12076) method.
