### ISSUE TITLE
GDB/MinGW64 doesnt work/start

### ISSUE THREAD

**Issue by Yachter** [microsoft/vscode#120165]
Issue Type: <b>Bug</b>

... with no errors. The Exe file was compiled and is executable. All config was done following instructions from https://code.visualstudio.com/docs/cpp/config-mingw.

Regards

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.88GB free)|
|Process Argv|--crash-reporter-id a06e6d09-c5cf-4173-a98c-d690cac8b1d6|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
c-cpp-compile-run|dan|1.0.13
code-runner|for|0.11.3
msys2|fou|0.7.0
vscode-pull-request-github|Git|0.24.0
Kotlin|mat|1.7.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0-insiders2
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4018
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontbcf:30265426
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by eamodio** [comment]
You will need to open an issue on the C/C++ extension. Thanks!
