### ISSUE TITLE
JS intellisense not working with require but working with import

### ISSUE THREAD

**Issue by stilllife00** [microsoft/vscode#120191]
Issue Type: <b>Bug</b>

1. Install a node module in a clean project

        yarn add @sanity/client

2. In a `.js` file import the module using the require syntax

       const sanityClient = require('@sanity/client')

3. Use the imported library

        const client = sanityClient({})
        client.

## Expected result
After typing the dot, intellisense should suggest the object methods.

## Actual result
Intellisense does not suggest them

*Note*: This works when using the `import` syntax

    import sanityClient from '@sanity/client'

Also works when explicitly selecting the default export

    const { default: sanityClient } = require('@sanity/client')

VS Code version: Code - Insiders 1.55.0-insider (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T12:45:45.302Z)
OS version: Linux x64 5.4.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|15.60GB (0.23GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwsldoc:30278403
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebutton:30280634
vshan820:30276952
vscoregs2formal2:30281058

```

</details>

**Comment by IllusionMH** [comment]
This might be because their `.d.ts` files suggests that module has [`export default SanityClientConstructor`](https://github.com/sanity-io/sanity/blob/v2.7.1/packages/@sanity/client/sanityClient.d.ts#L2085) but implementation is actually `module.exports = SanityClient` which I think should be `export = SanityClientConstructor` to be compatible with CommonJS usage (according to [Module: Class template](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html))

**Comment by stilllife00** [comment]
I have tried also with `node-fetch` and `got`.
`node-fetch` does not have a `.d.ts` file, so I guess intellisense relies on the actual js source code and works well.
`got` has a `.d.ts` file and I am experiencing a similar problem:

```
import got from 'got'
got( <--- intellisense shows me the arguments types and info
```

```
const got = require('got')
got( <-- intellisense does not show anything
```

It might be that those modules typings files are not proper (I haven't fully investigated) but there seems to be a pattern related to the default export and having a `.d.ts` file

As a workaround, is there a way to force intellisense to look into the `.js` source instead, so to ignore the `.d.ts` in some cases?

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/113122133-01b04180-921c-11eb-8e31-43111e809d75.png)
`node-fetch` doesn't work for me for same reason - [`export default fetch;` in @types/node-fetch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/da942ceaed4aa6bc1d0d97531444db75df7c930d/types/node-fetch/index.d.ts#L222) which is pulled with automatic-types acquisition (ATA).

In case of packages that don't have built-in definitions it's possible to use `typeAcquisition` with `exclude` array (see https://code.visualstudio.com/docs/nodejs/working-with-javascript#_typings-and-automatic-type-acquisition)
or completely disable ATA with `"typescript.disableAutomaticTypeAcquisition": true` (however this will affect all packages).

I'm not aware how to do that for projects with built-in definitions.

**Comment by pdsuwwz** [comment]
```
Version: 1.55.1 (Universal)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
I happened to have the same problem, my CommonJS automatic detection is invalid :(

I'm not sure if this is normal, it seems that this problem hasn't happened before.

![Snipaste_2021-04-09_13-49-59.png](https://i.loli.net/2021/04/09/SoK7PnGM1zOesrH.png)

**Comment by IllusionMH** [comment]
@pdsuwwz this is different problem not related to difference in definitions provided for ES and expected CommonJS in modules.
Your code has no CommonJS in it yet and there is no `require` in built-in libraries as it is not part of ES.
You need `@types/node` which are usually fetched by ATA when existing calls are detected.

**Comment by mjbvz** [comment]
Thanks @IllusionMH!

Yes I think this is expected given how this library's `d.ts` file is written. @stilllife00 Please follow up with the library since they author their own types file
