### ISSUE TITLE
Search all files does not work

### ISSUE THREAD

**Issue by mike65535** [microsoft/vscode#120121]
Issue Type: <b>Bug</b>

Fedora.

Open Code.
Create a workspace.
Open several files in it.
Close/save workspace.
Quit "Code".

Start Code, and Open previous workspace
"Search All Files" does not work. (Using a short cut CTRL-SHFT-F)

It only works on files I've viewed (clicked on)  after re-opening the workspace.

https://github.com/microsoft/vscode/issues/115315
*seems* to discuss this or something similar.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.10.21-200.fc33.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 3860)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.29GB (7.91GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 6d522ad2-c5b1-47fa-852d-d5689b0c570f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
vscode-print|pdc|0.9.2
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontbcf:30265426
openwslfolder:30280163
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953

```

</details>

**Comment by roblourens** [comment]
Any tips in here help? https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by mike65535** [comment]
No, those tips don't help and I've been through this before.
I reported this problem previously buy closed the report as it had seemed to fix itself.

I only just realized the search works **_IF_** I've already viewed the files in the current workspace session.  So the problem is not solved.  The workaround for the bug is to open the workspace then manually click each file to view it. Of course, that's a bit annoying and certainly not obvious.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)
