### ISSUE TITLE
semantic highlighting no longer works for js/jsx files

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#120103]
From https://github.com/aeschli/typescript-vscode-sh-plugin/issues/22#issuecomment-809244268

As far as I know. typescript's built-in semantic highlighting doesn't work with js files. 
https://github.com/microsoft/TypeScript/blob/b1571fcb71501d16f21173979365d4c4d53a11cb/src/services/services.ts#L1888

I checked with the insider version of vscode. Semantic highlight no longer show up on js files on 1.55.0 insider with commit d06d2f1d6245ce00b1c36a9cd81a9087d225173e. 

insider version:
![圖片](https://user-images.githubusercontent.com/36730922/112819395-2212bb80-90b7-11eb-88ca-f770b475f694.png)

1.54:
![圖片](https://user-images.githubusercontent.com/36730922/112819812-8afa3380-90b7-11eb-8451-0b09298fc2e6.png)

_Originally posted by @jasonlyu123 in https://github.com/aeschli/typescript-vscode-sh-plugin/issues/22#issuecomment-809244268_

**Comment by mjbvz** [comment]
Tracked upstream by https://github.com/microsoft/TypeScript/issues/43350
