### ISSUE TITLE
Debug Console log stops working after a few lines and formatting is messed up

### ISSUE THREAD

**Issue by canpoyrazoglu** [microsoft/vscode#120152]
Issue Type: <b>Bug</b>

My Vscode Debug Console output is completely messed up. When I run my app it does show several console outputs (which used to be correctly formatted/colored before, now starting with prefixes like `[0m[38;5;247m[1m`) then hangs there any doesn't display any more console output. Also, when expanding logged objects, I get various "middle steps" to expand like `arg1` which weren't there before. Here is a screenshot of the messed up output (nothing else is printed afterwards, this is the end of the output):

![Screen Shot 2021-03-30 at 08 17 53](https://user-images.githubusercontent.com/4348413/112937944-55922c00-9131-11eb-980e-6645c411f189.jpg)

I also can't try without extensions disabled because then I can't start my app within Vscode. This problem is occuring only on Vscode debugger and there's no issue if I use e.g. standalone React Native Debugger. This happens persistently every time I debug my app and stays the same even if I stop the debug session. When I start a new debug session, nothing changes (output isn't cleared and stays as in the screenshot). When I click `Clear Console` button on Vscode nothing happens (the output is NOT cleared). The only way to clear is to restart/reload Vscode window. I've also observed that the crash happens when I log many objects (e.g. using redux-logger) into the console and doesn't occur if I disable redux-logger. Though the "bad formatting with arg1" is still there. I don't think the issue is caused by redux-logger but Vscode itself because the debug console stays hung up even after I finish my debug session and clear button etc. doesn't work.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (35.08GB free)|
|Process Argv|--crash-reporter-id 61520765-68a9-4877-bb92-92fa245a771b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-npm-script|eg2|0.3.18
spark-ar-studio|fac|1.1.0
vscode-graphql|Gra|0.3.15
customize-ui|ioc|0.1.51
monkey-patch|ioc|0.1.12
vscode-language-babel|mgm|0.0.30
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1
color-highlight|nau|2.3.0
vetur|oct|0.33.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontbcf:30265426
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

If you can, can you create a repository on GitHub which reproduces this issue? So I can simply clone it and investigate further on my machine?

**Comment by canpoyrazoglu** [comment]
@isidorn I've just downloaded the latest insiders build. I confirm that it occurs also on the Insiders build.

**Comment by isidorn** [comment]
If you can, can you create a repository on GitHub which reproduces this issue? So I can simply clone it and investigate further on my machine?

**Comment by canpoyrazoglu** [comment]
I will try to but it might take some time.

**Comment by isidorn** [comment]
Great, thanks!

**Comment by fnicastri** [comment]
I have the same issue.
It is unusable.
Any help?
