### ISSUE TITLE
Add indicator for minimized/current window within the window list of Switch Window...

### ISSUE THREAD

**Issue by wayou** [microsoft/vscode#120175]
<kbd>control</kbd> + <kbd>w</kbd> to pop up the window list for quick switch. It's better that just like the chrome tabs, add indicators for windows which are minimized or current window within the window list.

![image](https://user-images.githubusercontent.com/3783096/112991189-6ecec300-9199-11eb-827a-541a32923fb4.png)

![image](https://user-images.githubusercontent.com/3783096/112990696-eb14d680-9198-11eb-9876-4190e8cac66b.png)

**Comment by bpasero** [comment]
@wayou to clarify, you want to see the minimized state in the quick picker right?

**Comment by wayou** [comment]
> @wayou to clarify, you want to see the minimized state in the quick picker right?

Yes.

**Comment by bpasero** [comment]
OK, one thing I do not fully understand yet is why VSCode does not show windows in the right click dock menu by default, I thought the OS would provide this, like Chrome has:

![image](https://user-images.githubusercontent.com/900690/112999049-e3403c80-916e-11eb-8a11-e2e266976929.png)

@deepak1556 any ideas?

**Comment by bpasero** [comment]
Oh, nevermind, we have it:

![image](https://user-images.githubusercontent.com/900690/113027804-c9145780-918a-11eb-9402-023bbec4a8b0.png)
