### ISSUE TITLE
Allow metadata to be marked as transient

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode#120127]
Live Share notebooks requires adding a custom piece of metadata with a cell id to each NotebookCell so that we can track cells while coediting. Opening a notebook results in a change where the file is marked dirty because it has different metadata, but everything else about the file is the same. I am not sure if VS Code does not support this, but it often results in a broken state where VS Code says there are dirty editors but Save All does not make them not dirty, and the wrong editors show up in the open editors list. I am going to file a separate sample extension and bug for this issue.

However, to simplify our use case, I propose that we add custom metadata that only exists in the context of the VS Code session and is not written to disk.

cc @rebornix

**Comment by rebornix** [comment]
Does `NotebookDocumentContentOptions#transientMetadata` help?

**Comment by alyssajotice** [comment]
The `NotebookDocumentContentOptions` is a property of the `NotebookContentProvider`. We need to be able to add our own transient metadata for each cell. Also, we only need it for our specific metadata, not all of the metadata on a notebook.

**Comment by rebornix** [comment]
@alyssajotice it's content provider's responsibility about what should be saved to disk and what's not. In Live Share's scenario, I would suggest:

* on host machine, always use a `cell#uri` to `customCellId` mapping.
* on guest machine, the content provider is contributed by LS. When LS contributes the mirror content provider, add something like `_live_share_custom_cell_id` to the `NotebookDocumentContentOptions#transientMetadata` (which is used to control whether a cell metadata properly will be saved to disk/trigger dirty state)

Does it make sense?

**Comment by daytonellwanger** [comment]
@rebornix is `cell#uri` guaranteed to be persistent and unique? I.e. a given cell will have the same fragment for its life (even if it's moved), and no other cell will ever have the same fragment (even if the previous one is deleted)?
