### ISSUE TITLE
Webview-Search don't work correctly

### ISSUE THREAD

**Issue by rufus-fr** [microsoft/vscode#120158]
Issue Type: <b>Bug</b>

Open a Webview (for example: Help -> Release Note) and start the search (Ctrl+F) and write the search term (for example: "Update") 

Only "u" (first letter) is selected on the view and not the current tipped search term. 
![WebviewSearch](https://user-images.githubusercontent.com/81615818/112959562-d65a2380-9143-11eb-84a5-38a94559e490.gif)

Notice: If i pressed "enter" then the full term is selected on the view. This behavier was other in the previous version (1.52.1)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
mock-debug|and|0.45.4
cortex-vsc|aud|2.1.0
npm-intellisense|chr|1.3.1
vscode-markdownlint|Dav|0.40.1
jshint|dba|0.11.0
vscode-eslint|dba|2.1.19
vscode-npm-script|eg2|0.3.18
vscode-firefox-debug|fir|2.9.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.3
vscode-test-explorer|hbe|2.19.6
code-coverage|mar|1.2.3
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.3
jupyter|ms-|2021.3.684299474
cpptools|ms-|1.2.2
powershell|ms-|2021.2.2
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
java|red|0.76.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
markdown-preview-enhanced|shd|0.5.17
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details>

**Comment by rzhao271** [comment]
The search behaviour changed between Electron 9.3.5 and Electron 11.4.1.
The `findNext` parameter should now be `true` whenever we're doing a search for the first time.
