### ISSUE TITLE
TS intellisense bug

### ISSUE THREAD

**Issue by mhesham93** [microsoft/vscode#120149]
Issue Type: <b>Bug</b>

sometimes typescript keeps on showing an error and intellisense is unable to display correct suggestions, the only way to fix that is to restart VS Code.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 1e4f7003-bec0-4d44-b888-cc5ac976793a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.18
prettier-vscode|esb|6.3.1
vscode-npm|fkn|3.3.0
csharp|ms-|1.23.9
debugger-for-chrome|msj|4.12.12
material-product-icons|PKi|1.0.4
prisma|Pri|2.19.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Also please provide steps to reproduce the issue

**Comment by mhesham93** [comment]
It does reproduce with all extensions disabled, I'm working with prisma.io and when I update my database and refresh my schema in visual studio it won't reflect the updates unless I restart VS Code (for example if I added a table/column IntelliSense  won't suggest the properties unless I restart it)

**Comment by mjbvz** [comment]
Please share steps (and code) to reproduce the issue
