### ISSUE TITLE
Opening a folder with custom scheme does not work

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode#120130]
- VS Code Version: 1.55.0-insider
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

I'm running into the same problem reported in https://github.com/microsoft/vscode/issues/110352.

Steps to Reproduce: (Running an extension in Codespaces)

1. Execute this command to open a folder in the current window. The URI is from a [custom file system](https://github.com/microsoft/vscode-azurestorage/blob/4f15c16b60cdc9aff790343c4f69654a5e50d440/package.json#L34).
```typescript
await commands.executeCommand('vscode.openFolder', uri, false /* forceNewWindow */);
```
Here's what the URI looks like:
<img width="1142" alt="Screen Shot 2021-03-29 at 1 18 45 PM" src="https://user-images.githubusercontent.com/22795803/112894962-625f4300-9091-11eb-87a2-ad11589b0283.png">

2. An error is thrown
<img width="464" alt="Screen Shot 2021-03-29 at 1 07 52 PM" src="https://user-images.githubusercontent.com/22795803/112894010-342d3380-9090-11eb-960f-016f071afed4.png">

Hovering over the workspace folder shows this warning:
<img width="361" alt="Screen Shot 2021-03-29 at 1 08 13 PM" src="https://user-images.githubusercontent.com/22795803/112894022-37c0ba80-9090-11eb-97cc-d200809d7c53.png">

Clicking on the workspace folder throws this error:
<img width="465" alt="Screen Shot 2021-03-29 at 1 08 36 PM" src="https://user-images.githubusercontent.com/22795803/112894036-3becd800-9090-11eb-950f-38f9b2888f1d.png">

Running VS Code locally works as expected:
![Screen Shot 2021-03-29 at 1 12 26 PM](https://user-images.githubusercontent.com/22795803/112894256-81a9a080-9090-11eb-9cf2-b0ed146eaf63.png)

Does this issue occur when all extensions are disabled?: N/A

**Comment by aeschli** [comment]
The command to open the virtual resource ends up with a call to the workspaceProvider:
``this.workspaceProvider.open('azurestorage:/awesomefoosbot8465?...')`

The workspaceProvider (implemented by codespaces) then opens a new window with the initial folder
`"vscode-remote://codespaces%2Baeschli-ext-ts-mar2020-fresh-338r/awesomefoosbot8465"`

Should be `azurestorage:/awesomefoosbot8465?...`

**Comment by aeschli** [comment]
Moved to https://github.com/github/codespaces/issues/2662
