### ISSUE TITLE
`Report Issue` button not working in version `1.54.3`

### ISSUE THREAD

**Issue by SilenceX12138** [microsoft/vscode#120154]
- VS Code Version: 1.54.3 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Click `Help` in the navigation bar
2. Click `Report Issue` but nothing gonna take place
![image](https://user-images.githubusercontent.com/47887520/112942722-25fc1780-9163-11eb-8dd0-8696d30a1c74.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by SilenceX12138** [comment]
Umm...

It seems no error info was put forward by the Developer Tools.😥

![show](https://user-images.githubusercontent.com/47887520/113418307-cff3d200-93f7-11eb-851b-27a418a4433b.gif)

**Comment by RMacfarlane** [comment]
@SilenceX12138 Can you open the "Console" tab at the top of the Developer Tools window?

**Comment by SilenceX12138** [comment]
Here it is~😀

![show](https://user-images.githubusercontent.com/47887520/113668384-bea31200-96e4-11eb-9ff9-e2dcb82818ca.gif)

**Comment by RMacfarlane** [comment]
Hmm, I'm not sure what's going on. Do you also see this when all extensions are disabled? Do you have any extensions installed which tamper with VS Code itself, like Custom CSS?

**Comment by SilenceX12138** [comment]
Hi, I tried opening vscode **with all extensions disabled** like this:

```shell
code . --disable-extensions
```
Here is the outcome.

![new_navi](https://user-images.githubusercontent.com/47887520/118218301-c6a35e00-b4a9-11eb-85f2-5aa789d2b163.gif)

**P.S. environment infomation is listed below.**

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Really great thx to you.

**Comment by TylerLeonhardt** [comment]
Hi @SilenceX12138 👋

I recently gained ownership of the Report Issue feature and so I'm getting ramped up!

It's been few versions now... Can you confirm if you're still seeing this issue?

Thanks!

**Comment by SilenceX12138** [comment]
Hi @TylerLeonhardt, this [message](https://github.com/microsoft/vscode/issues/120154#issuecomment-840985408) contains current situation of my VSCode.

Really thx for your efforts to make it better~

**Comment by TylerLeonhardt** [comment]
@SilenceX12138 I just want to rule this out just in case... but the Report Issue window isn't _behind_ the VS Code window, is it? (this has happened before for folks so I just wanna rule that out :) )

**Comment by SilenceX12138** [comment]
@TylerLeonhardt I'm quite sorry for this problem bothering you for such a long time. Actually, it doesn't stop me from using VS Code as ususal. 

So I may close this tiny issue. If it happens in the next version, I would like to **reinstall** my VS Code.

Hope you can focus on those really important ones!

Best wishes~

**Comment by TylerLeonhardt** [comment]
No problem! We are here to help no matter how small the issue!
