### ISSUE TITLE
VSCODE does not respect AWS Named Profiles

### ISSUE THREAD

**Issue by travis-jorge** [microsoft/vscode#120113]
- VS Code Version: 1.54.3
- OS Version:Windows_NT x64 10.0.19042

Steps to Reproduce:

1.Create an AWS Named profile Not Default with AccessKey, Secret, and Session Token
2. In VS CODE set the profile to your new named profile
3. Run a python script to do anything with that profile
4. It will use the Default profile not the named one

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
How is this related to VS Code?

**Comment by chrmarti** [comment]
It sounds like the Python library you are using doesn't read the current profile. Please contact the authors of that library, thanks.
