### ISSUE TITLE
Getting Started "Clone Git Repository..." silently fails if you don't have git installed 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#120112]
Version: 1.55.0-insider (user setup)
Commit: 26a60dbecacc8bdacc06f7681ebe95398878a1cd
Date: 2021-03-29T10:27:14.607Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Uninstall git if you have it
2. Open getting started/welcome page
2. Click "Clone Git Repository..."

Expected some friendly error message or something but the user sees nothing. Here's what is in dev tools:

```
  ERR command 'git.clone' not found: Error: command 'git.clone' not found
    at C._tryExecuteCommand (file:///C:/Users/Tyler/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1558:3364)
    at file:///C:/Users/Tyler/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1558:3245
```

Looks like maybe the git extension isn't activated until git is installed?

Does this issue occur when all extensions are disabled?: N/A

**Comment by eamodio** [comment]
Yeah, we abort really early if Git is missing. We do set the `git.missing` context key, so maybe we should key off of that in the getting started?

**Comment by TylerLeonhardt** [comment]
I notice the option is still there for a split second then goes away, but it's not bad so marking as verified.
