### ISSUE TITLE
Terminal wraps too early in a codespace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#120136]
- Open a codespace in desktop
- Open the terminal
- Type and notice that it wraps on a narrow width, on the same line
- But the output wraps to the correct width, interestingly

https://user-images.githubusercontent.com/323878/112913935-a7926d80-90af-11eb-88e7-051e08931946.mp4

**Comment by PanosBougas** [comment]
I have the same issue, but it's only happening on Remote-SSH.

Steps to recreate:

1. close Remote connection, kill VS Code server on remote host 
2. Open Remote connection, create/open a terminal
3. The terminal will have the wrapping issue and if you try to create more terminals they will have that issue too
4. Destroy the terminal and create a new one without using any profile, just by Ctrl + `
5. Issue is gone

**Comment by MadeleineRoberts-WellSky** [comment]
I am having the same issue with Remote - WSL.

**Comment by carterbryden** [comment]
Same issue with remote over ssh, on ubuntu bash

**Comment by PanosBougas** [comment]
I think I found a way to bypass the issue.

Open or close the editor's Side Bar, you can also do this by pressing `Ctrl + B`
