### ISSUE TITLE
editor.wordHighlightStrongBackground and editor.wordHighlightBackground cause incorrect word highlights in notebooks

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#120148]
@alexdauenhauer commented on [Mon Mar 29 2021](https://github.com/microsoft/vscode-jupyter/issues/5350)

## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: macOS Catalina 10.15.7
-   Python and/or Anaconda version: any (observed in 3.6.12, 3.6.13 and 3.8.6)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv via pyenv
-   Jupyter server running: Local

## Expected behaviour

`editor.findMatchBorder` would properly highlight the match borders

## Actual behaviour

borders drawn are incorrect
![image](https://user-images.githubusercontent.com/11903445/112903334-37c6b780-909c-11eb-866f-242e276eef4f.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. open a notebook. Highlight a word or variable you want to highlight and see the border match fail

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-03-29 10:57:16: Jupyter Kernel Spec not found for a local connection
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.pyenv/versions/mercury/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.6 64-bit ('qs')
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py pip list
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.pyenv/versions/qs/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

</p>
</details>

---

@joyceerhl commented on [Mon Mar 29 2021](https://github.com/microsoft/vscode-jupyter/issues/5350#issuecomment-809807149)

Sorry for the trouble @alexdauenhauer. Although this seems to be working for me:
![image](https://user-images.githubusercontent.com/30305945/112914680-6f8c2a00-90b1-11eb-902d-c52e98528a1e.png)

Did you have to work in this notebook for some time before this behavior appeared?

**Comment by rebornix** [comment]
need more info as @joyceerhl mentioned above not reproducing.

**Comment by alexdauenhauer** [comment]
Hi @joyceerhl thanks for the reply. I may have not properly identified which setting is causing the issue, but here are some additional screenshots. The `find` function works fine and as expected which seems to be what you have shown in your screenshot. I am honestly not sure what setting it is that is causing the issue, I have tried to find it, but it is related to `editor.wordHighlightBackground`. This is the case when you simply place your cursor on a word and vs code automatically highlights (or borders depending on your theme) matching words. The first screenshot was a theme I made and I am no expert so here is one with a well established theme (noctis uva). Trying to rule out theme

**behavior in notebook**

![image](https://user-images.githubusercontent.com/11903445/113009965-4c9f5b80-912d-11eb-9f43-1208c708fef5.png)


![image](https://user-images.githubusercontent.com/11903445/113009924-414c3000-912d-11eb-81e9-369a5d32f77d.png)

**same snippet, behavior in .py file**

![image](https://user-images.githubusercontent.com/11903445/113011819-05b26580-912f-11eb-8e93-e8e88c434fd1.png)

![image](https://user-images.githubusercontent.com/11903445/113011854-0e0aa080-912f-11eb-8c42-eab430fffcd7.png)

**Comment by joyceerhl** [comment]
@rebornix I have a repro for incorrect word highlights that is likely related and doesn't require changing the settings that @alexdauenhauer mentioned.

Create a new blank Jupyter notebook like so:

![image](https://user-images.githubusercontent.com/30305945/113048284-38705400-9157-11eb-94c0-cfa6998787bb.png)

Then double click on `df` in cell 0 to select it. Note the ghost highlights in cell 0 overlap perfectly with the locations of the matching word `df` in cell 1. It seems like the highlights are being applied to the wrong notebook document.

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124499495-f6b50200-dd72-11eb-8cdd-2864dcd11978.png)
