### ISSUE TITLE
Problem with packaging ProposedApi 

### ISSUE THREAD

**Issue by badetitou** [microsoft/vscode#120117]
- VS Code Version: 1.55.0-insider
- OS Version: ArchLinux

Steps to Reproduce:

1. package my extension using `vsce package`
2. Install the extension
3. Open a file name `*.moosebook`
4. Got the error
   ```
   Cannot open resource with notebook editor type 'moosebook', please check if you have the right extension installed or enabled.
   ```

Does this issue occur when all extensions are disabled?: Yes

The Notebook API can not be used. It reports the following error: 

```
Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api badetitou.pharo-language-server
```

But, I'm using the insider version, and I have set `"enableProposedApi": true,` in package.json.

Note: I do not have the problem in debug mode (F5), only when installing the package.

The [GitHub repo](https://github.com/badetitou/vscode-pharo/tree/proposed) (in proposed branch)

I suppose it is a problem when packaging the extension. But I'm out of ideas and the error message does not help me more.
Any hints? 

Edit: I've also tried starting vscode insider with `--enable-proposed-api` but without more success

**Comment by jrieken** [comment]
> Edit: I've also tried starting vscode insider with --enable-proposed-api but without more success

Did you try this with `--enable-proposed-api badetitou.pharo-language-server` or just `--enable-proposed-api`?

**Comment by jrieken** [comment]
> However, I don't get why I do not need to use --enable-proposed-api with the https://github.com/microsoft/vscode-github-issue-notebooks example

We have an allow-list for some extensions. Those can use proposed API without further constraints, but authors "sign in blood" that they adopt each breakage immediately.

**Comment by badetitou** [comment]
Ok, thanks for the quick answer. I understand ;-)
