### ISSUE TITLE
black screen problem

### ISSUE THREAD

**Issue by ngdlmk** [Microsoft/vscode#12016]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.When i left vs code opened for a while all window is going to be dark and this happend every time.

**Comment by bpasero** [comment]
@ngdlmk can you share a screenshot?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by ngdlmk** [comment]
Sorry, I had no chance to connect to internet that is why i couldn't reply your message. I added the screenshot below

![untitled](https://cloud.githubusercontent.com/assets/5893467/18814778/ed19b26a-8325-11e6-8d2f-8ab293662703.png)

**Comment by bpasero** [comment]
@ngdlmk are you running within a VM?

**Comment by ngdlmk** [comment]
No @bpasero

**Comment by bpasero** [comment]
@ngdlmk does it help if you run `code --disable-gpu` from the command line?

**Comment by ngdlmk** [comment]
I'm using vmware workstation 12 but this screenshoot doesn't belong to vm's os this is my current os.

**Comment by bpasero** [comment]
Flagging as upstream because I have not heard from others yet. 

@ngdlmk Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
@ngdlmk ping

**Comment by ngdlmk** [comment]
with lastest update problem is solved thanks for all help
