### ISSUE TITLE
Settings Sync: Support syncing “additional resources” 

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#120142]
Today, Settings Sync only _syncs_ VS Code settings and UI State. Issue #113996 asks to sync workspace state, but I would like to sync other resources used/generated by extensions.

My Project Manager extension uses `globalStorageUri` to store a few `JSON` files (projects and cache). At least the `projects.json` file would be useful to be _synced_, specially when dealing with Codespaces and Remotes.

I’m not saying the entire `globalStorageUri` content should be synced, but at least the possibility to add _additinoal resources_ to the syncing process.

BTW, the original Settings Sync extension has this feature, but the resources are defined by the user, not the extension developer.

Thanks in advance

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/113774
