### ISSUE TITLE
Find in Files's shortcut is broken

### ISSUE THREAD

**Issue by slorg1** [microsoft/vscode#120174]
# Environment data
Visual studio code Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-48-generic snap
Pylance: v2021.3.3
Python: 3.7
Eclipse Keymap: v0.12.0
Ubuntu 20.20

# Expected behaviour
ctrl+H should trigger the Find in Files functionality with anything highlighted prefilled in the search bar

# Actual behaviour
ctrl+H now opens the Find in Files without prefilling anything and only selects the "panel" (does not focus on the search bar).

I believe this stopped working a couple of weeks ago. It seems like a recent release broke it.

I tested with the VSCode shortcuts:

it seems now that in Edit the Find in Files is set to ctrl+shift+F (that is what I see in the menu
![image](https://user-images.githubusercontent.com/5043518/112990124-b3c00e80-9133-11eb-9eee-9856791f1a32.png)
)
if I use this set of keys for the shortcut after selecting some text: it tries to trigger formatting and I get Black does not support the "Format Selection" command
if I select some text and use the menu (Edit->Find in Files) then it works correctly

I also filed this issue with Eclipse Keybinding as I do not know where the issue comes from: https://github.com/alphabotsec/vscode-eclipse-keybindings/issues/38

**Comment by IllusionMH** [comment]
/needsMoreInfo

Why <kbd>Ctrl</kbd>+<kbd>H</kbd> should be Find in files?
Default shortcut is<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> even on Linux
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-linux.pdf

Do you have any extensions enabled?

**Comment by slorg1** [comment]
Hi,

Yes, I am using `Eclipse Keymap` as mentioned in the report's description.

Also, see that the `ctrl+shift+f` also does not work for me (see in the report's description)

Thank you

**Comment by IllusionMH** [comment]
Sorry it was unexpected to see keymap in content of About window.

As I can see in that this keymap has <kbd>Ctrl</kbd>+<kbd>H</kbd> mapped to `workbench.view.search` which only shows Find in Files instead of `workbench.action.findInFiles` which seeds search field and triggers new search (if current not dirty).
So either Keymap or you should change command for <kbd>Ctrl</kbd>+<kbd>H</kbd>.

As for displayed keybindings in meny - it looks like keymap doesn't remove default keybindings (not sure about best practices here) and just adds new. So VS Code will show first matching keybinding which is default.

**Comment by slorg1** [comment]
Hi,

Thank you, I made a PR to Eclipse KeyBindings following your recommendation: https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/39

**Comment by JacksonKearl** [comment]
Modifying the keybindings extension is the correct solution here, looks like the update is already out. A recent version changed `workbench.view.search` to open the search view, then `workbench.action.findInFiles` performs the whole set of opening the search view (or editor, depending on `search.mode`) and inserting text and running the query.

**Comment by slorg1** [comment]
Hi @IllusionMH ,

The suggested changes are now live in the extension, thank you!

I do have 1 more quick question: 

the focus now works but if I have a selection, it does not get prefilled into the search box (it does if I use the menu manually).
Would you know how to address that issue with the keybinding?

Thank you in advance for your help!

**Comment by JacksonKearl** [comment]
The change was documented here, https://code.visualstudio.com/updates/v1_54#_changes-to-workspace-search-actions based on the PR it looks like you're correctly using `workbench.action.findInFiles`. Trying out the eclipse keymap myself I see the correct behaviour that `ctrl+h` opens the search view, puts the active editor's selected text in it if it exists, and runs the search. What is happening in your case?

**Comment by slorg1** [comment]
Hi Jackson, thank you for following up. I tested it again today and it does work.

The extension updated yesterday (so I saw it was up-to-date). But I might have forgotten to reload it.

Thank you and sorry for the confusion!!
