### ISSUE TITLE
Refresh test breaks run all

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#120179]
Issue Type: <b>Bug</b>

This is using the VS Code test runner
1. Run all tests
2. Click the refresh test button in the ... menu
3. Click run all tests again
4. :bug: Nothing happens.

VS Code version: Code - Insiders 1.55.0-insider (c71be15869a673c5ed7bfd3fe171757d2ba48142, 2021-03-30T02:56:15.808Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|32.00GB (2.70GB free)|
|Process Argv|--crash-reporter-id 7170f6db-7270-442f-945e-4508c02991d4|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
I couldn't repro this, but the test provider has several unpublished changes/fixes. Please let me know if you continue to hit this after updating. If so, try to capture a console log and see if there are any errors.
