### ISSUE TITLE
Feature Request: Smart Copy/Paste

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#120167]
## Context
Currently (VS Code 1.54), *copy* and *paste* copies and pastes the text as is.

However, quite often I don't want to copy the text literally, but *semantically*, especially in string literals with escape sequences.
This would be very useful when dealing with windows paths in JSON config files, as every single backslash needs to be escaped when pasting a path into a JSON string or unescaped when copying from a JSON string.

Similar to smart select, I propose a smart copy/paste that considers the context of the document the user wants to copy from / paste into.

This feature request in inspired by IntelliJs smart copy feature.

## Proposal
Smart Copy/Cut/Paste commands are introduced and bound to Ctrl+C/Ctrl+X/Ctrl+V.
The existing Copy/Cut/Paste commands are bound to Ctrl+Shift+C/Ctrl+Shift+X/Ctrl+Shift+V.

**Smart Copy/Cut** asks the currently active language to provide an optional clipboard value for a given range, as well as some optional metadata. If a clipboard value is provided, it replaces the text that would be put into the clipboard.
In multicursor scenarios, this is done for every range. For cut operations, VS Code removes the selected text after asking the language.

Implementations can use this hook to lookup the given range in some AST and provide an unescaped text of the selection (they should only do this if the selection is entirely contained in a string).
If a symbol (e.g. a classname) is copied, implementations can lookup the full qualified name of that symbol and put it into the metadata.

**Smart Paste** asks the currently active language to process the paste operation.
The language gets the clipboard value (which can be a text value or even other content, like images or files), the target range and the metadata (if available) and indicates if it could apply the paste operation.
If it cannot, VS Code pastes the text as is.

Implementations should use the `workspace.edit` API to perform the paste operation. They can escape the text if required or add some imports. The metadata of the smart copy command can be used to resolve import ambiguities.

## Covered Use-Cases
* *Copy escaped text*
    * The user opens a JSON document with the following content:
    ```json5
    {
        "path": "C:\\users\\joe\\Documents\\my-project\\foo.js"
    }
    ```
    * The user wants to open the containing folder of `foo.js` in the windows file explorer.
    * They copy the path into the clipboard, open a new windows file explorer and enter the copied path.

* *Paste unescaped text*
    * The user uses VS Codes "Copy Path of Active File" command
    * The user pastes the path into a JSON string in a JSON document
    * The JSON language service escapes the path and inserts a valid JSON string segment.

* *Paste images into markdown files*
    * The user takes a screenshot by pressing Shift+Windows+s. It gets copied into the clipboard.
    * The user opens a markdown file in VS Code and presses Ctrl+V to paste the copied image.
    * The markdown language service saves the file next to the markdown file and inserts a link.
    * [Like this extension](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image), but for Ctrl+V (and not Ctrl+Alt+V).

* *Moving code from one file into another file*
    * Imports can be added automatically by using metadata.
* *Pasting indented code*
    * Indention can be fixed automatically.

**Comment by yume-chan** [comment]
Similar to #30066, plus modifying what will be copied.

**Comment by hediet** [comment]
@yume-chan, thanks, I didn't find that issue when I was searching for similar issues! Will close this one.
Being able to modify the copied data would be nice though.
