### ISSUE TITLE
Test Runner output is blank

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#120118]
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Use the vscode test runner
2. Run some failed tests
3. 🐛 The test output is blank for the failed tests, but the output channel has output 

<img width="947" alt="Screen Shot 2021-03-29 at 1 46 16 PM" src="https://user-images.githubusercontent.com/4544166/112877798-2fb74980-9095-11eb-88d4-b0fa04453d1c.png">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
What is the output in the output channel?

**Comment by lramos15** [comment]
> x OpenerService delegate to commandsService, command:someid
> AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
> 
> 123 !== '123'
> 
>     at Context.<anonymous> (file:///Users/lramos15/upstream/vscode/out/vs/editor/test/browser/services/openerService.test.js:68:20)
> Test process exited with code 1
