### ISSUE TITLE
Keyboard Shortcuts editor: using del-key to remove mouse-selected text when editing When-expression deletes whole shortcut

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode#120180]
Issue Type: <b>Bug</b>

BUT ONLY when releasing the mouse button outside of the input field but in the same row as the targeted shortcut (i.e. when you quickly select a portion on the end or beginning of the text and not look at where your cursor ended up when releasing the mouse button)

1) right click on any keybinding and click Change When Expression
2) select any portion of the expression you want to delete with your mouse and release the mouse button with the cursor outside of the input field but still in the same row as the keybinding (for example just quickly left-drag-select some text at the beginning without precisely timing the release of your mouse button)
3) press del-key
=> Keybinding is completely removed/unset instead of just deleting the selected text in the When-input

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (10.52GB free)|
|Process Argv|--crash-reporter-id f88d64be-4345-4275-b2bd-d984644ea1a3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|2.1.0
calculate|aca|2.1.0
c-cpp-makefile-project|adr|1.1.0
Bookmarks|ale|13.0.4
project-manager|ale|12.0.1
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
whitespace-plus|dav|0.0.5
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
comment-anchors|Exo|1.9.1
php-debug|fel|1.14.12
vscode-firefox-debug|fir|2.9.2
vscode-pull-request-github|Git|0.24.0
vscode-edit-csv|jan|0.5.6
better-cpp-syntax|jef|1.15.5
lorem-whatever|job|1.0.2
json2csv|kha|0.0.1
vscode-phpfmt|kok|1.0.30
banner-comments-plus|lun|0.3.1
rainbow-csv|mec|1.8.1
git-graph|mhu|1.29.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0-insiders
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.4.0
vsliveshare|ms-|1.0.4018
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
sqltools-driver-sqlite|mtx|0.2.0
easyzoom|Nab|0.1.0
bar|olb|0.2.0
csv-to-table|php|1.2.3
color-manager|roy|0.6.2
better-pageup-pagedown|rus|0.0.1
numbermonger|sof|0.5.0
regexworkbench|ste|2.0.5
snippets|tah|1.0.0
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.0
faster-new|wen|1.1.20
markdown-all-in-one|yzh|3.4.0
vscode-asciiflow2|zen|0.2.0
makefile-creator|zen|0.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontbcf:30265426
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953

```

</details>

**Comment by sandy081** [comment]
> select any portion of the expression you want to delete with your mouse and release the mouse button with the cursor outside of the input field but still in the same row as the keybinding (for example just quickly left-drag-select some text at the beginning without precisely timing the release of your mouse button)

It seems you are removing the focus out of the when input box - this will take you out of edit mode. After that `del` keybinding is associated to remove the keybinding and hence it is getting removed. In order to edit the when text you have to be inside input box and pressing delete then will clear the input box. This is how any input box works.

**Comment by sandy081** [comment]
Thanks for the gif, I was thinking you are clicking outside after selection. But it is clear now.

**Comment by stuartleeks** [comment]
Verified that I can repro on latest stable release, and also that it no longer occurs on the current insiders build

```
Version: 1.59.0-insider (user setup)
Commit: 0f22f2d343e33b03e8033d1083513072f58ece21
Date: 2021-07-29T05:13:10.735Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043
```
