### ISSUE TITLE
Pressing the up or down arrow on output channels change channel and focus

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#120188]
Currently if you keyboard focus to the output channel dropdown and press the up or down arrow, it will select the previous/next channel, but then also move focus into the channel. I would rather the focus to stay on the dropdpwn, so I could continue to use the up/down arrows.

**Comment by isidorn** [comment]
Yeah I think this makes sense. Especial since the output is read only.  Current jumping focus behavior is weird and unexpected for keyboard users. I can look into fixing this.

fyi @sandy081

**Comment by isidorn** [comment]
@eamodio can you please verify this? Thanks!

**Comment by eamodio** [comment]
Perfect! Thanks!
