### ISSUE TITLE
vscode does not respect diagnostic codeDescription property?

### ISSUE THREAD

**Issue by FractalBoy** [microsoft/vscode#120146]
Issue Type: <b>Bug</b>

I wrote a language server and I have it sending diagnostics back. I included the codeDescription property with a link to documentation about the diagnostic, but it doesn't seem to show anywhere in the UI. Am I missing something? Hovering over the problem in the UI / holding Ctrl while hovering doesn't do anything, as other issues seem to indicate should work.

```json
{
   "method":"textDocument/publishDiagnostics",
   "jsonrpc":"2.0",
   "params":{
      "uri":"file:///home/mreisner/projects/perl-language-server/server/lib/PLS/Server.pm",
      "diagnostics":[
         {
            "code":"Perl::Critic::Policy::Subroutines::ProhibitExplicitReturnUndef",
            "message":"\"return\" statement with explicit \"undef\"",
            "range":{
               "end":{
                  "line":79,
                  "character":17
               },
               "start":{
                  "line":79,
                  "character":4
               }
            },
            "source":"perlcritic",
            "severity":1,
            "codeDescription":{
               "href":"https://metacpan.org/pod/Perl::Critic::Policy::Subroutines::ProhibitExplicitReturnUndef"
            }
         }
      ]
   }
}
```

![image](https://user-images.githubusercontent.com/2024233/112931302-8480b180-90e1-11eb-85b0-03cb4a298c2a.png)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.94GB free)|
|Process Argv|--crash-reporter-id 7d9c799a-95e8-41d0-a51a-63d76fbabd7b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2711)|
|Memory (System)|5.98GB (5.37GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
debugger-for-chrome|msj|4.12.12
vim|vsc|1.19.3
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.19
prettier-vscode|esb|6.3.1
pls|Fra|0.0.4
svn-scm|joh|2.13.5
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
cpptools|ms-|1.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
rust|rus|0.7.8
vscode-scss-formatter|sib|2.1.0
vscode-lldb|vad|1.6.1
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30280190
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by sandy081** [comment]
There is no `codeDescritpion` property on vscode diagnostic @dbaeumer is it related to language server?

**Comment by dbaeumer** [comment]
The codeDescription property gets converted into a diagnostic code having a `{ value: string | number; target: Uri; }`.

@FractalBoy you have to Ctrl+Click on the error code that is in parenthesis in `perlcritic(....)`

**Comment by FractalBoy** [comment]
@dbaeumer As I mentioned in the original post, that does nothing besides select multiple diagnostics.

Here is a GIF of me doing that:

![codedescription](https://user-images.githubusercontent.com/2024233/113311789-4812a880-92cf-11eb-9a9c-30b5e02a7e0c.gif)

**Comment by dbaeumer** [comment]
I tested this with my ESLint extension and it works as expected. Which versions of the LSP libraries are you using?

**Comment by FractalBoy** [comment]
Ah, thank you! I didn't realize that I should be regularly updating the LSP client.

I upgraded from 6.1.3 to 7.0.0 and the links now work.
