### ISSUE TITLE
Explore using hints with getting started

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#120147]
We explored these in the early days of the onboarding flow and wanted to bring this back to explore to see if using it with Getting Started will help make the path clearer for the user or when an action is not needed.

![image](https://user-images.githubusercontent.com/35271042/112934419-94df5f00-90d6-11eb-97fb-06baa14d0973.png)

**Comment by digitarald** [comment]
Other use cases on top of UI tours (chaining hints together) that recently came up:

1. **Replace onboarding notifications** with a _ephemeral_ hints on important UI elements.
   - Notebooks pointing to kernel switcher in status bar
2. **Replace error notifications** with hints on the interactive UI element, until the OK button on hint or the element is clicked.
   - Python pointing to interpreter switcher when no default or a problematic kernel was set
3. **Replace extension recommendation notifications** with a hint + counter on the extension activity bar
  - Important extension recommendations
  - Workspace extensions #121802

@misolori should we keep iterating in this issue or file separate issues for chained vs one and done hints? The UX for them should be very similar overall.

**Comment by misolori** [comment]
I think keeping them together makes sense here since one would have a CTA of "Done" and the other would be "Next" with a counter.

**Comment by JacksonKearl** [comment]
> ![image](https://user-images.githubusercontent.com/8586769/116733321-cb8fea00-a9a0-11eb-9f85-01b63dadc776.png)

This is very much not a convex hull.

**Comment by misolori** [comment]
Here's a few variations I drew up this week:

![image](https://user-images.githubusercontent.com/35271042/116735625-a3ee5100-a9a3-11eb-9397-7142b501651a.png)

![image](https://user-images.githubusercontent.com/35271042/116735638-a94b9b80-a9a3-11eb-8435-471751b8fed6.png)

![image](https://user-images.githubusercontent.com/35271042/116735652-aea8e600-a9a3-11eb-86aa-641fec855ce0.png)

![image](https://user-images.githubusercontent.com/35271042/116735677-ba94a800-a9a3-11eb-9e12-459591b25518.png)

![image](https://user-images.githubusercontent.com/35271042/116735700-c1231f80-a9a3-11eb-8c3b-8db2f6523366.png)

**Comment by daviddossett** [comment]
Closing this in favor of discussion in #165846
