### ISSUE TITLE
vscode python comment problem

### ISSUE THREAD

**Issue by talent-nansy** [microsoft/vscode#120224]
Issue Type: <b>Bug</b>

Code as below:

```python
class RPSLFieldListMixin:
    """
    Mixin to allow fields to support list values, like 'AS1, AS2, AS3'.

    For example, if you have an RPSLASNumberField that validates a single
    AS number, you can create RPSLASNumbersField that allows a list of
    AS numbers by creating:

        class RPSLASNumbersField(RPSLFieldListMixin, RPSLASNumberField):
            pass
    
    """
    def parse(self, value: str, messages: RPSLParserMessages, strict_validation=True) -> Optional[RPSLFieldParseResult]:
        pass
```

However, in my client-side, the comment parts haven't been marked as comments.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.88GB (3.68GB free)|
|Process Argv|--crash-reporter-id 77d5688d-ddbc-4442-a2a3-69bb71eef5e2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.4.0
code-runner|for|0.11.3
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
gotestexplorer|pre|0.1.13
vscode-yaml|red|0.17.0
python|tht|0.2.3
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30265425
pythonvspyt943:30280189
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952

```

</details>

**Comment by talent-nansy** [comment]
![image](https://user-images.githubusercontent.com/16119436/113102217-5067d680-9230-11eb-9c5d-2083a7a70a10.png)

**Comment by chrmarti** [comment]
There are also error/warning underlines under `class` and `def`. What does the tooltip say when you hover over these? Could you attach the entire file (the part you posted renders correctly for me)?

**Comment by chrmarti** [comment]
Could you check with the just released VS Code 1.55? I can't reproduce. Also check the language name in the statusbar's lower right, maybe that's using the wrong language to colorize.

**Comment by alexr00** [comment]
I also can't repro. I'm betting that one of the extension you have installed is causing this.

**Comment by talent-nansy** [comment]
It was a problem caused by an extension "Python for VScode".
Thank you all for your responses.
