### ISSUE TITLE
Clarify single-folder workspace settings tab name

### ISSUE THREAD

**Issue by itsVyasi** [microsoft/vscode#120294]
In the Settings editor...

In a Single-folder workspace there are User and Workspace tabs, which map to the global settings and .vscode/settings.json respectively.
In a Multi-root workspace there are User, Workspace, and folder tabs, but Workspace now maps to settings within .code-workspace, and the previous settings.json is accessed by the folder selection tab.

This seems unnecessarily confusing, especially for someone who may be new to vscode.

I suggest making the Single-folder settings editor align with the usage and terminology of Multi-root by making the Single-folder editor show User and folder tabs, ie. in the "myFolder" workspace there would be a User tab and a myFolder tab.

**Comment by gjsjohnmurray** [comment]
An earlier attempt by me to get this changed was turned down by @roblourens

https://github.com/microsoft/vscode/issues/90981#issuecomment-588609826

**Comment by roblourens** [comment]
There was related discussion and we have this page which might be new since that last discussion https://code.visualstudio.com/docs/editor/workspaces

**Comment by itsVyasi** [comment]
@roblourens Thank you, I had previously found that page and I thought it explained well. My issue was more that the Single-folder setup feels to me to be contrary to the paradigm, and unintuitive when switching between the two. Particularly, I tend to use Single-folder workspaces and whenever I switch I tend to select the wrong settings because I am used to the 'Workspace' tab targeting settings.json.
