### ISSUE TITLE
The scroll bar in the Find in Files pane is too small and scrolls the wrong way

### ISSUE THREAD

**Issue by acidhelm** [microsoft/vscode#120277]
- VS Code Version: 1.55.0
- OS Version: OSX Big Sur

Steps to Reproduce:

1. Do a search in the Find in Files pane that returns at least one result
2. Move the mouse cursor down to the horizontal scroll bar.  The scroll bar's width is very small.
3. Drag the scroll bar.  The text in the pane scrolls the wrong way; dragging the scroll bar left scrolls the text left, and dragging right scrolls the text right.

Does this issue occur when all extensions are disabled?: Yes

More info: I just got 1.55.0 today, but I have been seeing this bug for a week or so, so it was present in 1.54.x.

![small scroll bar](https://user-images.githubusercontent.com/26553622/113220330-db989a80-9237-11eb-9851-a3e2d132e78b.png)

**Comment by alexr00** [comment]
I'm not able to repro the original issue to verify. I set `workbench.list.horizontalScrolling` to `true`, but in 1.55 on Windows the scrollbar is still the correct size.

**Comment by roblourens** [comment]
It reproes for me in 1.55, I don't know what the trick is. I'll just mark it as verified.

**Comment by acidhelm** [comment]
This is fixed, thanks!
