### ISSUE TITLE
Save file to disk even if not changed when saving

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#12028]
Maybe this is more of a feature request, but I would like the editor to touch the saved file even though there has not been any change in the contents of the file. This is useful in a scenario where for example a test is run when you save/change a file. 

Steps to Reproduce:

1. save unchanged file
2. observe file not being touched

- VSCode Version: 1.52
- OS Version: Win 10 64bit

**Comment by jhasse** [comment]
I wouldn't want this on `File: Save All` though. Some build system use timestamps instead of hash sums to know which files have changed since the last build.

**Comment by PunchyRascal** [comment]
Sure, that is not the case for me either. Also it can be driven by a setting such as "alwaysTouchSavedFile" or something along those lines and be turned off by default.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7470
