### ISSUE TITLE
Drag-dropping a file onto terminal both quoted and escaped

### ISSUE THREAD

**Issue by hzpc-joostk** [microsoft/vscode#120246]
Issue Type: <b>Bug</b>

Working remotely, when dragging a file from the integrated explorer to the integrated terminal, the filename is both quoted and escaped. 

So a name like `path/to/folder with spaces/file.txt` becomes `'path/to/folder\ with\ spaces/file.txt'` in the terminal.
Whereas, IMHO, it should only be quoted to work properly.

Extension version: 0.65.1
VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-1040-azure

**Comment by Tyriar** [comment]
Unconfirmed, might only be an issue in remotes.

**Comment by hzpc-joostk** [comment]
I can't reproduce either... No idea what caused it. 

Never mind 😇
