### ISSUE TITLE
Emmet suggestion fails to show when user writes self-closing abbreviation

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#120203]
From https://github.com/microsoft/vscode/issues/118904#issuecomment-809808334

1. In an HTML file, type `div/`
2. Notice that suggestions show up to expand `div`, but when `/` is typed, suggestions stop showing up.

Potential code pointers:
- Try adding `/` for relevant languages (everything other than css to stylus) here https://github.com/microsoft/vscode/blob/main/extensions/emmet/src/util.ts#L86
- If that doesn't work, we might need to add `/` to some regexes for https://github.com/microsoft/vscode-emmet-helper/blob/main/src/emmetHelper.ts#L33

**Comment by pixieaka** [comment]
@rzhao271 @hantatsang Can you add `>` character to expand suggestions also? For example `MyComponent>` and `ctrl + space` to show suggestion list for `<MyComponent></MyComponent>`.

![2](https://user-images.githubusercontent.com/17777237/113508383-0b091900-9550-11eb-99a8-00710c36511f.gif)

**Comment by rzhao271** [comment]
@pixieaka I don't think that's a common use case, considering `MyComponent` works.

**Comment by pixieaka** [comment]
@rzhao271 Any custom HTML element + `>` expanded to full element not only `MyComponent`.

**Comment by pixieaka** [comment]
@rzhao271 I think it's a useful shortcut to have.

**Comment by pixieaka** [comment]
@rzhao271 `MyComponent` + `tab` or `MyComponent` + `ctrl + space` doesn't expand anything. I must write `MyComponent` + `>` + `ctrl + space` to expand this.

**Comment by rzhao271** [comment]
@pixieaka can you set `emmet.triggerExpansionOnTab` to `true`?

**Comment by pixieaka** [comment]
@rzhao271 It works perfect, thanks.

**Comment by rzhao271** [comment]
@pixieaka please file that issue with Vetur https://github.com/vuejs/vetur
