### ISSUE TITLE
Windows: --user-data-dir argument no longer supports relative paths

### ISSUE THREAD

**Issue by FaustVX** [microsoft/vscode#120269]
Issue Type: <b>Bug</b>

Since this last update (1.55.0), the argument `--user-data-dir` is not taken into account anymore.

I use a sortcut on my windows machine, which set `--user-data-dir` and `--extensions-dir` arguments, and it worked well up to this last version.

The extensions still works well.

So my settings doesn't "exists" anymore for vscode.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.99GB free)|
|Process Argv|--extensions-dir .\\.vscode\\Extensions --user-data-dir .\\.vscode\\Data --crash-reporter-id ce3f7bc3-e5a0-4e29-b66f-d9c31d663e22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
arm|dan|1.5.0
gitlens|eam|11.3.0
cortex-debug|mar|0.3.12
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
hexeditor|ms-|1.4.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30280190
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by FaustVX** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Extension debug: --user-data-dir must be used for debug launch (#44734)](https://www.github.com/microsoft/vscode/issues/44734)

No it's not related to debugging.

**Comment by bpasero** [comment]
I tried this on Windows and macOS and cannot reproduce passing `code --user-data-dir <some dir>` from the command line.

**Comment by FaustVX** [comment]
After some testing, it's when the path is relative, the `--extensions-dir` is relative to current directory, but `--user-data-dir` is relative to the executable.

With `code --extensions-dir .vscode.Extensions --user-data-dir .vscode.Data`, the `.vscode.Extensions` folder is created in the current directory, but `.vscode.Data` is created in `%localappdata%\Programs\Microsoft VS Code\` (where the `code.exe` is located). And the default directory (without any arguments passed in) is in `%appdata%\Code`.

And again, everything worked fine in the previous version (1.54.3).

**Comment by FaustVX** [comment]
In the shortcut file I have, In `Target` I have: `"%localappdata%\Prograams\Microsoft VS Code\Code.exe" --extensions-dir ".\.vscode\Extensions" --user-data-dir ".\.vscode\Data"`,
and in `Start In` I have: `D:\Documents\Development\RpiPico\` (it's the current directory of the lnk file)

**Comment by FaustVX** [comment]
As a workaround, I put both arguments as absolute path.

But it's not a perfect solution.
Also it's not symmetrical between the 2 arguments, and it's a different behavior from previous versions.

**Comment by bpasero** [comment]
A consequence of https://github.com/microsoft/vscode/commit/1441ba91f0e3fd82ac6860aacda83befe9d176e3 and calling `process.chdir` very early now:

https://github.com/microsoft/vscode/blob/9cd4712b35237611cd1f9aa92d8fea605b41ebda/src/bootstrap-node.js#L43-L43

We probably need to take the `VSCODE-CWD` variable into account when resolving the user data path and the provided argument is relative here:

https://github.com/microsoft/vscode/blob/8f1b7a36defa22da806a4af5d208629c9c340251/src/vs/platform/environment/node/userDataPath.js#L44-L44
