### ISSUE TITLE
Indicate Problem When Opening Folder Already Open in Another Instance

### ISSUE THREAD

**Issue by ardalis** [microsoft/vscode#120272]
I just had an experience where I was trying to open a folder in VS Code, which I've done a million times before. But it wouldn't open. It just... did nothing. I tried a few times - no luck. So I opened Windows Explorer, went to the folder, and tried again. Windows Explorer disappeared (minimized), but VS Code didn't launch. Nothing. Finally [I tweeted my frustration](https://twitter.com/ardalis/status/1377370741541371907) and someone led me in the right direction: I already had that folder open in another VS Code window (which I hadn't noticed).

Request:
Pop up an error dialog saying "Cannot open multiple instances of the same folder"
or
Pop up the already available instance of VS Code that has that folder open.

Don't just silently do nothing and confuse users as to why.

**Comment by ardalis** [comment]
Checked. It's related to #12541 but not the same. It's unrelated to the other one. Not a duplicate, IMO.

**Comment by tebeco** [comment]
That would be nice yes.

The "Bring up to front" would be the best overall approach

But in some situation like a Modal being opened, there's some glitches I observed
* "Bring up to Front", in some scenario have no effect, not sure why
* `Alt+Tab` also just don't list/render it because of that modal

As these kind of glitches can be on Windows team side, it's still frustrating not to understand what's going on.
Would it be possible to add a yellow `WARN: ....` in `stdout` as a minimal "notification" thingy ?

I also wonder if it is possible to force the Icon in the TaskBar to "yellow blink" ?
So that
* if the "Bring up to front" works, then the blink goes away
* if it "bug" then it still attempt to get user attention

**Comment by bpasero** [comment]
@ardalis this sounds like the window that had the folder opened was just not moved to the front? Does it reproduce if you run code from the command line: `code <folder path>`?

**Comment by ardalis** [comment]
Trying to reproduce it now, when I use `code .` from an already-opened-in-vs-code folder, it does nothing visible if the window is up, but will open it if it is minimized. Same for File Explorer - Right Click - Open in VS Code.

I think in my case the issue was pretty much user error. I had right clicked on a file that wasn't in the folder in question and opened it with code. So, my code editor was editing a file that wasn't in the folder in question, and time (days in this case) had passed since I'd opened the editor. I didn't see that I had an editor open to that folder (since it was editing some other file from some other location) so I first tried to tell a different instance of VS Code to open the folder. It failed without any apparent messaging. Then I tried command line. Then I tried File Explorer. All the while in another window my VS Code editor was already open, showing a file from another folder.

So, I don't know what would prevent this aside from maybe flashing the active window or something. Thanks!

**Comment by bpasero** [comment]
@ardalis can you try to do this please:
* open code on a folder
* move it side by side to a terminal so that both windows are visible on the same desktop
* run `code <folder>` from the terminal
* does the code window get keyboard focus and become active or not?

**Comment by ardalis** [comment]
It does.

**Comment by bpasero** [comment]
Then I do not understand the issue when it does not behave like that.

**Comment by ardalis** [comment]
Like I said - probably user error. The confusion stemmed from the fact that it was editing a document that wasn't in that folder, and it probably doesn't help that I have 2 very large screens with a lot of windows open so the fact that one of them changed color slightly didn't register with me. Probably an edge case that can be closed.

**Comment by tebeco** [comment]
It's definitely not a user error 
it CAN happen when there's a model open
like "File > Open folder" and don't select anything. Just let that "Open folder" modal open

though it's not always happening
the fact that a top modal / blocking window is open is not properly handled by OS/vscode itself
