### ISSUE TITLE
Syntax Highlighting for Interpolated Strings in C# Incorrect for Some Characters Inside Brackets

### ISSUE THREAD

**Issue by tapiester** [microsoft/vscode#120204]
Issue Type: <b>Bug</b>

1. Open a new file
2. Set language to C#
3. Type a line including an interpolated string  
   Ex: `var string = $"interpolatedValue={valueList.Select(value => value.ToString())}";`

The actual colors produced have some characters (for me, `{`, `}`, `.`, `(`, and `)`) colored as though they were part of the string, not the C# code in the brackets. The expected result is that all code between the brackets (and also the brackets themselves) are colored as though they were normal code outside a string.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 2794)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.84GB free)|
|Process Argv|--crash-reporter-id b3b52f6e-4546-44d7-8236-8b59620aefbe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.40.1
mdmath|goe|2.5.1
plantuml|jeb|2.14.4
python|ms-|2021.3.680753044
jupyter|ms-|2021.3.684299474
code-spell-checker|str|1.10.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontbcf:30265426
wslfolderdoccf:30282075
vsget980:30279783
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by tapiester** [comment]
Here's a screenshot of what I see:

![image](https://user-images.githubusercontent.com/49066264/113056209-7e3e1400-9179-11eb-9483-a6d34d7d4e72.png)

**Comment by alexr00** [comment]
The scopes for one of these parentheses are:
```
punctuation.parenthesis.open.cs
meta.interpolation.cs
string.quoted.double.cs
source.cs
```

The first scope that matches for a theme color is `string.quoted.double`, which is why it is colored as a string. 

To fix this, we could add `punctuation.parenthesis` to our built-in themes to get the `default` color. @aeschli is this something we should do? Or should we leave this up to theme extensions to do better?

**Comment by aeschli** [comment]
Maybe `meta.interpolation.cs` can be set to default instead? That way we don't need to list all scopes that have the default color (which would be hard to do)
