### ISSUE TITLE
html syntax issue in vs_code

### ISSUE THREAD

**Issue by SurajLodh** [microsoft/vscode#120239]
{{name|safe}}   this syntax  is perfact format but vs code showing imperfact and auto spreade syntax. 

please as soon as fix this. #107467

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please follow issue/request template on github and provide examples what is wrong and what is expected.

**Comment by SurajLodh** [comment]
https://twitter.com/Mr_SurajLodh/status/1377245440890920967?s=20

please look into this

**Comment by IllusionMH** [comment]
Your issue is unactionable with current description and linking to twitter instead of providing info in one place doesn't help maintainers to work on this issue.

**Comment by SurajLodh** [comment]
The purpose for sharing is to connect with tester and vs community group not for the instead solution or help. 
The Second reason is to share picture link with you and its shows the more detail.

**Comment by aeschli** [comment]
Thanks @IllusionMH for the support.
@SurajLodh As mentioned by Andrii, it appears that you have JavaScript code in a style element. That's strange. To be able to investigate I'd need a small, selfcontained code sample that shows the issue. 
Please add all information (steps, code sample, screenshots) to the description of the issue.

**Comment by SurajLodh** [comment]
[https://github.com/SurajLodh/Dashboard/blob/main/app1/templates/new.html](url)

sir, I'm attaching my index.html link please look into this 

https://twitter.com/Mr_SurajLodh/status/1377245440890920967?s=20

and this link(picture) is clearly showed my problem 

if its correct then leave.

and large thank to you guys for taking my problem and finding better solution for us.

**Comment by aeschli** [comment]
Hi @SurajLodh, thanks for the source code.
```ts
{
            labels: {{lable1|safe}}
}
```
is not valid HTML/JavaScript but Django.

You have to look for a Django extension and you have to set the editors language mode to Django.
Alternatively you can try to continue to work with the HTML editor and disable JavaScript validation: 
`"html.validate.scripts": false`

**Comment by SurajLodh** [comment]
thank you sir its working fine !
