### ISSUE TITLE
"Shift+Alt+RightArrow" keyboard shortcut is detected as "Shift+Right"

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#120206]
Issue Type: <b>Bug</b>

Hello, i am using KDE Plasma. I have the issue that the "Shift+Alt+RightArrow" keyboard shortcut is detected as "Shift+Right" in the Keyboard Shortcuts settings. Probably this is also the reason why "Expand selection" doesn't work via the keyboard. The issue reproduces also with extensions disabled.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-48-lowlatency

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2438)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (0.35GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 09e1fe7e-5025-42d9-95b2-a79a8a841663|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
laravel-extra-intellisense|ami|0.6.1
html-class-suggestions|And|1.1.1
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer-2|Coe|0.2.0
githistory|don|0.6.16
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.4.0
vscode-colorize|kam|0.11.0
typelens|kis|1.9.6
vscode-gutter-preview|kis|0.27.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
remote-containers|ms-|0.163.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.11.0
vscode-versionlens|pfl|1.0.9
laravel-artisan|rya|0.0.27
partial-diff|ryu|1.4.2
vscode-javascript-booster|sbu|14.0.1
indenticator|Sir|0.7.0
laravel-goto-controller|ste|0.0.12
code-spell-checker|str|1.10.2
sort-lines|Tyr|1.9.0
vscode-icons|vsc|11.2.0
vscode-jumpy|wma|0.3.1
material-theme|zhu|3.9.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvspyt943:30280189
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952

```

</details>

**Comment by IllusionMH** [comment]
Looks similar to #120097

You can use https://github.com/microsoft/vscode/wiki/Keybinding-Issues to see if VS Code event receives this shortcut properly and check if you have similar settings that prevents VS Code to receive this event as mentioned in https://github.com/microsoft/vscode/issues/120097#issuecomment-809556085.

**Comment by mystiquewolf** [comment]
Oh, thank you very much for the fast reply. Yes, my issue is the same. So what i've done is that i've removed Alt+Shift as the shortcut for switching languages but not from the config file mentioned in the other issue but from KDE's own settings.

Now what i'm thinking is that Windows also has this shortcut for changing its keyboard input language, but this key combination may be delivered to VS Code on Windows no matter this fact. If you're using Windows, could you please check if that's the case?

**Comment by mystiquewolf** [comment]
Nevermind, i found which bug it is: https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/1245473

I am closing this bug as it seems to be an OS issue.

**Comment by IllusionMH** [comment]
As I can see on Windows <kbd>Shift</kbd> and <kbd>Alt</kbd> are still passed to applications (tested in Edge Chromium and Edge Legacy). I see no problems with <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>LeftArrow/RightArrow</kbd> working on Windows even with <kbd>Shift</kbd>+<kbd>Alt</kbd> to switch languages.

Windows will only switch language on release (key up) and only if there were no other keys pressed.

UPD. I see that you've found issue, hope it will be resolved soon.
