### ISSUE TITLE
typescript tips is not work 

### ISSUE THREAD

**Issue by haoqichongtian** [microsoft/vscode#120253]
- VS Code Version:1.54.3
- OS Version:window64

Steps to Reproduce:

1.My typescript tips is not work（it should give some ideas when the cursor hovers），In the beginning ，it work when i download vscode .now it does not work. 

Does this issue occur when all extensions are disabled?: yes

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should provide more details about project setup and code that causes problems, otherwise it's hard to tell what may be wrong.

**Comment by haoqichongtian** [comment]
sorry .it fixed. 

step1: Disable all Installed extensions 
step2: Enable all extensions
