### ISSUE TITLE
CSS: `!important` completion is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120245]
![recording (8)](https://user-images.githubusercontent.com/22350/113156979-55f0fc80-91ef-11eb-9ebb-9caa120912d1.gif)

cc @jrieken

**Comment by pixieaka** [comment]
@joaomoreno And after this suggestions stop working.
![1](https://user-images.githubusercontent.com/17777237/113162478-a09a6500-923f-11eb-91fc-8c9bf4259f2c.gif)

**Comment by aeschli** [comment]
It's an emmet completion

**Comment by rzhao271** [comment]
Upstream issue here https://github.com/emmetio/emmet/issues/650

**Comment by joaomoreno** [comment]
This is a pretty bad paper cut in the CSS experience IMO.

**Comment by rzhao271** [comment]
Now that I think about it, I could've just patched it directly in `vscode-emmet-helper` as a temp fix. 🤦‍♂️

**Comment by rzhao271** [comment]
\closedWith 551daf4
