### ISSUE TITLE
Problem to type exclamation '!'.

### ISSUE THREAD

**Issue by AngeloBonini** [microsoft/vscode#120236]
Issue Type: <b>Bug</b>

Just try to type 'shift + 1' while editing any type of file.
when I search or type inside the integrated terminal, it goes well, the '!' appears. But when I try to reproduce it inside any file, nothing happens. I've been having this problem since november/2020.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.8.0-43-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 3219)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (7.68GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch /media/gelo00/AngeloHD/typescript/javascript-algorithms --no-sandbox --crash-reporter-id fb13f047-a4cb-478e-8d46-bd370886efbd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
codesnap|adp|1.2.1
vscode-icalendar|af4|1.0.1
ng-template|Ang|11.2.9
vscode-color|ans|0.4.5
All-Autocomplete|Ati|0.0.23
vscode-browser-preview|auc|0.7.0
god|bas|0.0.100
vscode-intelephense-client|bme|1.6.3
solargraph|cas|0.21.1
nebula-theme|Chi|1.3.2
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
angular-schematics|cyr|4.13.0
c-cpp-compile-run|dan|1.0.13
vscode-eslint|dba|2.1.19
vscode-elixir-syntax|dun|0.0.17
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.18
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
php-intellisense|fel|2.3.14
vscode-jest-runner|fir|0.4.31
vscode-elixir-snippets|flo|0.2.36
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-graphql|Gra|0.3.15
ruby|gro|0.1.0
CppSnippets|har|0.0.15
vetur|hik|0.24.1
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
rails-snippets|Hri|1.0.8
elixir-ls|Jak|0.6.5
vue|jcb|0.1.5
vscode-rufo|jnb|0.0.4
vscode-rufo|mbe|0.2.1
vscode-language-babel|mgm|0.0.30
git-graph|mhu|1.29.0
ruby-symbols|mig|0.1.8
vscode-elixir|mjm|1.1.0
vscode-docker|ms-|1.11.0
vscode-kubernetes-tools|ms-|1.3.0
remote-containers|ms-|0.163.2
cpptools|ms-|1.3.0-insiders
typescript-javascript-grammar|ms-|0.0.55
vscode-typescript-next|ms-|4.3.20210330
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
react-proptypes-intellisense|OfH|1.0.3
vue-beautify|pea|2.0.4
vscode-versionlens|pfl|1.0.9
prisma|Pri|2.20.1
ruby|reb|0.28.1
vscode-yaml|red|0.17.0
redwood|red|0.0.21
prettier-now|rem|1.4.9
prisma-schema-tool|Sam|1.2.0
rufo-vscode|sil|0.0.3
prettier-vscode|Sim|2.0.7
prettier-plus|svi|4.2.2
vscodeintellicode|Vis|1.2.12
quokka-vscode|Wal|1.0.353
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether this is being caused by one of your 71 extensions.

**Comment by AngeloBonini** [comment]
![image](https://user-images.githubusercontent.com/50537258/113144431-9c505680-9203-11eb-98fc-e6485e9b7a24.png)
When I typed again this message appears: 
`command 'extension.formatRuby' not found`
then Ive disabled all my Ruby extensions, but it still happens.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice on checking your keybindings.

**Comment by AngeloBonini** [comment]
Thank you, I got, there was a keybinding for "shift+1" that formats ruby files. My fail.
I will close the issue.
