### ISSUE TITLE
Diff margins for collapsed code blocks

### ISSUE THREAD

**Issue by adomasbaliuka** [microsoft/vscode#120238]
VSCode shows which lines of a file were changed relative to the last Git commit in the margins for that editor window.

However, if the editor contains collapsed code blocks that have changes inside, these changes are not visible. This is counterintuitive and may lead users to miss some changes while reviewing them.

Proposal: The diff margins should also indicate changes inside collapsed code blocks.

**Comment by joaomoreno** [comment]
This is related to preserving line decorations even when folding areas are collapsed.
