### ISSUE TITLE
Provide a "Open with..." for settings.json

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120220]
Similar to the search editor, I think we should have an enry "Open with... > Settings editor" for `settings.json` inside `.vscode` folder.

//cc @roblourens @sandy081

**Comment by lramos15** [comment]
These are a lot more complicated than the search editor as they don't consume the same override API meaning their open flow would also have to be adapted which I'm not familiar enough with to do. I'll defer to @roblourens and @sandy081 if they want to take up adopting `this.editorService.overrideOpenEditor`.

**Comment by roblourens** [comment]
We already have a dedicated button for that, and I don't know whether this fits the same flow, because the Settings editor is not a different editor for the same resource, it has its own URI.

**Comment by lramos15** [comment]
Yeah, you would basically only populate the settings editor in the open with panel if it was that URI scheme. It's a bit weird, like right now if I try to go from the settings UI to text editor using reopen with I get an error. The question becomes should we allow reopen with in the settings editor as another avenue to switching between hex, json, UI, etc.

**Comment by bpasero** [comment]
Feel free to close this if not straightforward, I don't think this is very important, just nice to have.

**Comment by lramos15** [comment]
Closing due to the amount of complexity this would add to a niche use case.
