### ISSUE TITLE
ctrl + click in terminal when in Data (D:) drive

### ISSUE THREAD

**Issue by JeanMarc-R** [microsoft/vscode#120298]
the ctrl + click in terminal doesnt work when I'm not in the drive (C:)

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
