### ISSUE TITLE
Bug after opening .conf file

### ISSUE THREAD

**Issue by piluprior** [microsoft/vscode#120228]
Hello,

The problem occurred when I was working on the css-grid-layout folder. This folder was open in VSCode.

Then I wanted to access the httpd.conf file. This one opened in the current project folder (css-grid-layout).

I made my changes in the httpd.conf file and closed the file tab.

I then closed VSCode which also closed my project folder.

After a Windows update, I rebooted my machine.

It was when I tried to access the css-grid-layout folder again that I encountered the problem.

I could not display the content of my folders and files in the editor. Only the title of the file appeared (httpd.conf) in the title bar and no content was displayed. So this file blocked access to my entire project folder. I restarted VSCode without success. The problem remains the same.

When I open another project folder with VSCode, I don't encounter any problem.

It seems that there is a connection between my open project folder and the opening of the .conf file.

I hope I have made myself clear. If not, I could give you more information.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by piluprior** [comment]
ok I'm testing

**Comment by piluprior** [comment]
It seems that installing vscode insiders solved the problem. I can open my project folder again. The httpd.conf file is gone.

Thank you very much.
