### ISSUE TITLE
Terminal and output dropdowns don't work on main

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#120273]
Steps to Reproduce:

1. Pull main 
2. Launch VS Code
2. Terminal and output dropdowns do not work when you select items

@Tyriar and I investigated this and have pinpointed the issue to here:

https://github.com/Microsoft/vscode/blob/ece0761b33f5195969950536b66136bd48db7556/src/vs/platform/actions/common/actions.ts#L418-L420
options is undefined here so the args never get forwarded. 

![recording (70)](https://user-images.githubusercontent.com/29464607/113217627-0af8d880-9233-11eb-85e3-54e5572c1f3e.gif)

**Comment by meganrogge** [comment]
@sbatten has determined this commit caused the issue 
eece236bbd68f28daac8e543409765d2a9d7cbfa

**Comment by sandy081** [comment]
Oh sorry about that - removed forwarding args to fix this - https://github.com/microsoft/vscode/issues/119369. I will revisit the fix and scope it only for custom view. Since this is fixed, closing this.
