### ISSUE TITLE
Extension host terminated unexpectedly 

### ISSUE THREAD

**Issue by sumneko** [microsoft/vscode#120293]
- VS Code Version: 1.55.0
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Install extension https://marketplace.visualstudio.com/items?itemName=SDTTTTT.bangumiopen
2. Wait ~10 sec
3. Extension host terminated unexpectedly.

This is indeed a problem caused by the extension, and I have reported it to the author of the extension.
It’s just that I’m not sure if it’s normal for the extension host to terminate unexpectedly in this case.
If yes, you are free to close this issue.

**Comment by sdttttt** [comment]
I am the author of this extension, this is indeed the issue that BangumiOpen caused, this issue can now be closed.
