### ISSUE TITLE
Add a method to allow the extension to rename the terminal

### ISSUE THREAD

**Issue by detihoronyatkonya** [microsoft/vscode#120258]
I would like to have a [terminal ](https://code.visualstudio.com/api/references/vscode-api#Terminal)object method to manage the name of terminals through my vscode extension. At this time, as far as i know it can be done only via executing workbench.action.terminal.renameWithArg command and only for active terminal

**Comment by meganrogge** [comment]
you can do this via the `name` property when you create the terminal.

**Comment by detihoronyatkonya** [comment]
@meganrogge Maybe I didn't express myself accurately enough, I meant to change the name of the integrated terminals already created by the user, and not at the time of their creation via vscode api. The name of already created integrated terminals cannot be changed through the name field, since it is a constant
