### ISSUE TITLE
Alt+tab on ipynb goes to file menu 

### ISSUE THREAD

**Issue by surajsoni5** [microsoft/vscode#120257]
1. open a ipynb notebook & start editing a cell
2. Switch apps using Alt + Tab from visual studio code to other app & then back to visual studio code
3. the cursor control moves to the file menu rather than the cell

**Comment by rebornix** [comment]
@surajsoni5 can you please provide more info to help troubleshoot? Like what OS you are on, the version of VS Code, the version of the notebook extension you are using. A screen recording will be better.

**Comment by VulumeCode** [comment]
I have the same issue on Windows 10, VCode 1.56.0, Jupyter v2021.6.811652604
