### ISSUE TITLE
support running from CLI with :line:collumn

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#12025]
I'd like to request a new CLI feature to match Atom and Sublime text. These editors both can start from cli and jump to line and collumn.

For example when I run:
```
code /home/capaj/git_projects/error-pitcher/test/error-thrown.js:3:10
```
I would expect to have the file opened and my cursor on line 3 column 10.
Currently the file is not opened, because VScode thinks those double dots are a part of file name.

It would be great to have this. If you're interested in my usecase- I am developing a hyperterm plugin https://github.com/capaj/hyperterm-clicky and it would be awesome if users could open up files easily straight from their terminal for VS code as well as they do now for Atom and Sublime text.

**Comment by bpasero** [comment]
Try `code -g`

**Comment by capaj** [comment]
works, thanks
