### ISSUE TITLE
Render notebook outputs as text if the mime type is text and there is no registered renderer

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#120267]
Currently, if a notebook kernel outputs `text/csv` or some other mime type for which there is no registered renderer, a message is shown instead of the output.

For `text/*` mime types, the output should be rendered as plain text.

**Comment by rebornix** [comment]
This is a really good idea.

**Comment by rebornix** [comment]
After more than a year, I still think this is a very interesting idea that's worth a try. We might need to add `glob/regex` match for mimetypes for the output renderer contribution.

@amunger I assigned this to you for now.
