### ISSUE TITLE
notebook browser integration test failure

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120214]
The notebook browser integration tests completely time out right now. It seems as long as the custom renderer is turned on, the notebook editor doesn't open. Currently have it disabled correctly https://github.com/microsoft/vscode/commit/00c1ca5afcbd2d64a74a1f75d766d668ae001267

**Comment by mjbvz** [comment]
Fixed by #124557 (will take a look at the individually disabled tests too)
