### ISSUE TITLE
syncing between version does not really work

### ISSUE THREAD

**Issue by duytrung** [microsoft/vscode#120222]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Use an insider along with the released version, both home and workplace.
2.use sync function to sync the installed extensions and settings.

Sync does work between Insider versions but not between the insider and the final release version.

Does this issue occur when all extensions are disabled?: Not applicable

 Can anyone explain this? I know that the insider version have some new features but the extensions/plugins are all for both experimental and final release version. I can not update the installed plugins in the official release of vscode.

Thanks a lot :-)

**Comment by sandy081** [comment]
Insider - stable are not synced by default, but you can enable insiders to sync with stable. Please see - https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders
