### ISSUE TITLE
Text editor is opened when changing cell textmodel language when notebook is not open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#120284]
- Put this code in some command
 
```ts
const docUri = vscode.Uri.file('/pathToVscode/vscode/.vscode/notebooks/api.github-issues');
const cellUri = docUri.with({ scheme: 'vscode-notebook-cell', fragment: 'ch0000001' });
const cellDoc = await vscode.workspace.openTextDocument(cellUri);
await vscode.languages.setTextDocumentLanguage(cellDoc, 'css');
```

- Run the command (make sure that file wasn't open already)
- The text editor opens with that file
- It should open the notebook editor because it is now dirty

This actually worked fine in my PR branch last week. Then merging with the latest, it doesn't work. Debugging it, I don't know at what point we are supposed to decide to open in the notebook editor. Could it be related to some of your changes @jrieken?

**Comment by jrieken** [comment]
> The text editor opens with that file

Maybe because the workbench believes that file is dirty and needs to be shown? I will debug

**Comment by jrieken** [comment]
The opening happens here: https://github.com/microsoft/vscode/blob/88c58b011c06233c8fb1a61a79a8fffd22ba7ee2/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L724

The question is why a text editor and not a notebook editor is opening. @lramos15 Did something change? I see that [onEditorOpening](https://github.com/microsoft/vscode/blob/88c58b011c06233c8fb1a61a79a8fffd22ba7ee2/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L307-L307) isn't called

**Comment by jrieken** [comment]
I have pushed a workaround for this - instead of resource editor inputs it uses now notebook editor inputs but something still feels wrong about the original case

**Comment by jrieken** [comment]
@roblourens with my fix/workaround I now see another problem

* run the command -> notebook editor opens as dirty 👍 
* reset cell language, save, close the editor
* re-run the command
* 😢 the editor doesn't open again because it there is no dirty event being fired

**Comment by roblourens** [comment]
Well, first I am not actually writing the new language back to the text model, yikes. Fixed that and it still doesn't work.

Listening on `_modelService.onModelAdded` is not enough because right after you closed the notebook, the TextModel is still there and that event won't be fired. So I can listen on `_modelService.onModelModeChanged` as well, done.

But I was thinking about other cases. What if I change the text of a cell with a workspace edit? There is no equivalent global event for a model content changing. If I do this with the notebook closed, it opens the editor but I don't see the content change. I only see it if the editor is open when the workspace edit is applied. This has something to do with the cell textmodel having it's own textbuffer which I don't fully understand.

**Comment by roblourens** [comment]
Pushed a fix, a couple remaining issues

- If there is another editor open, when I run the command to change the language, the notebook editor opens in the background and doesn't show the dirty indicator until I click on it. Maybe that's intended.
- If I close the dirty editor and say "Don't Save", it doesn't reset the text model language, I don't know how that's supposed to work

**Comment by roblourens** [comment]
A consequence of our redundant cell type + language, who is supposed to say No if I change the language of a markdown cell  with setTextDocumentLanguage? I don't think that should convert it to a code cell

**Comment by roblourens** [comment]
Pushed another change based on what we talked about this morning. And opened https://github.com/microsoft/vscode/issues/120771 for remaining issues so I don't push this issue off track because it looks like there is still an open question for this issue: https://github.com/microsoft/vscode/issues/120284#issuecomment-813891508

**Comment by jrieken** [comment]
re https://github.com/microsoft/vscode/issues/120284#issuecomment-813891508

ping @lramos15 ⬆️

**Comment by rebornix** [comment]
right now running the code above with auto save turned off will not open the notebook editor, though it should be dirty.

**Comment by connor4312** [comment]
There is still a bug here: with autosave off, the file is not marked as dirty until it is focused the first time

![](https://memes.peet.io/img/21-06-20ed646c-f20e-4da2-8e33-7bf972a45827.gif)

**Comment by jrieken** [comment]
Shelling this out into a separate issue. I have debugged this till the point where the working copy is marking itself as dirty but somehow the workspace doesn't catch that. fyi @bpasero
