### ISSUE TITLE
NPM Script Explorer side panel has vanished

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#120279]
- VS Code Version: 1.55.0-insider and 1.55.0
- OS Version: Windows 10 19042.867

Steps to Reproduce:

1. Open VSCode
2. Try to find the NPM Script Explorer in the side panel
3. Wonder why it's not there 🤔

Does this issue occur when all extensions are disabled?: Yes

Possibly related: I had previous separated this panel from the File Explorer and made it it's own icon. However, it seems to be gone from Insiders, which I just downloaded and installed without configuring it this way.

![image](https://user-images.githubusercontent.com/1298521/113223411-f706a400-923d-11eb-9897-5c17d68373eb.png)

**Comment by IllusionMH** [comment]
Hard to tell with this small indentation in tree but I think that you have `package.json` only in nested folder.
If yes, then it looks like duplicate of #119868

**Comment by marvey11** [comment]
Same issue after the VS Code update. 

This happens in several TypeScript/Node.js/Angular projects with the `package.json` definitely in the root of the project (straightforward project layouts, no monorepo or similar). Furthermore, it was working normally yesterday in the same projects.

As a workaround I can still open the `package.json` and right-click on (or hover over) the script name and execute "Run Script".

**Comment by devuxer** [comment]
> Hard to tell with this small indentation in tree but I think that you have `package.json` only in nested folder.
> If yes, then it looks like duplicate of #119868

I saw that issue, but I observed this behavior in projects with package.json is in the root as well as nested.

**Comment by bvanderneut** [comment]
Just letting you know that I have the same issue. Also having the package.json in the root and the menu is not showing just like described in the ticket.

**Comment by XanderUZZZER** [comment]
The same situation. After vs code updated, NPM scripts panel disappeared, and can not be found in any context menus. But,  the interesting thing: I opened empty folder in vs code, run npm init, default package.json was created, and NPM scripts panel showed. After folder reopening, panel did not appear...

At least  scripts can be run directly from package.json via context menu

**Comment by wandingistaken** [comment]
Same issue. Found a temporary fix #120292 and wait for updates.

**Comment by Da13Harris** [comment]
Same issue here. No NPM SCRIPTS menu to be found anywhere.

![image](https://user-images.githubusercontent.com/11934898/113329235-2b2ba480-92d2-11eb-83db-76c0f2dc8e8f.png)

**Comment by devuxer** [comment]
> Same issue. Found a temporary fix #120292 and wait for updates.

@wandingistaken, Showing release notes didn't make any difference for me 😢

**Comment by wandingistaken** [comment]
> > Same issue. Found a temporary fix #120292 and wait for updates.
> 
> @wandingistaken, Showing release notes didn't make any difference for me 😢

😂 One other approach would be that after you opened your project with vscode, you can add a random folder to your workspace. My npm scripts bar popped out after this. Then remove the random folder as you like.
![image](https://user-images.githubusercontent.com/54961146/113362451-0526f400-9314-11eb-860a-7fa4a743794f.png)

**Comment by devuxer** [comment]
> 😂 One last approach works for me: after you opened your project with vscode, you can add a random folder to your workspace. My npm scripts bar popped out after this. Then remove the random folder as you like.
> ![image](https://user-images.githubusercontent.com/54961146/113362451-0526f400-9314-11eb-860a-7fa4a743794f.png)

Thanks again, but also didn't work for me 💔

**Comment by vasia123** [comment]
https://github.com/microsoft/vscode/issues/120292 and `>Reload Window` works for me.

**Comment by dariodotcom** [comment]
Same here. I've tried with two clean portable installs of 1.54.3 and 1.55 with the same folder, and the panel is missing only in the newer one.

 ![image](https://i.imgur.com/VgHhVtV.png)

**Comment by kczx3** [comment]
Ditto

**Comment by kczx3** [comment]
Seems to me this be in the list for the March Recovery

**Comment by jeanmathieupotvin** [comment]
Same issue for me here. All my projects have a single `package.json` file in root folder. NPM Scripts Explorer just vanished right after updating 1.55.

**Comment by Flavio78** [comment]
Hllo. I have the same problem. I tried the workaround with the random folder in workspace, but it needs to be done after each vscode startup. Thanks for your support.

**Comment by Flavio78** [comment]
Hello. I have the same issue. I tried the workaround with the random folder in workspace, but it seems it has to be done after each vscode startup. Thanks for your support.

**Comment by ezeartigas** [comment]
With the command `> Reload window` the npm script will shown again, but this need to be fixed.

**Comment by charlwillia6** [comment]
I confirm that the NPM Scripts bar is missing from the EXPLORER, and `> Reload Window` does nothing for me.

**Comment by nieuwefn** [comment]
Same problem here. A trick that is working for us is opening a package.json, then either the NPM Scripts Explorer automatically is shown, or after using `> Reload Window` it is availaible.

**Comment by mkoestner** [comment]
I had the same problem. After changing the position of the script node in the package.json in front of the dependencies, the npm scripts view appeared again after > Reload Window.

**Comment by itsems** [comment]
Same problem here.
Showing Release Note & Creating random folder & `> Reload Window` doesn't work for me.
I've reinstalled to [v 1.53.2](https://code.visualstudio.com/updates/v1_53) which has normal npm scripts shown in panel.

**Comment by sibeliuz** [comment]
Same issue. But "Reload window" shows NPM Scripts again.

**Comment by amadeusz-chomiak** [comment]
Same problem here. Until it's fixed just use [NPM-Scripts](https://marketplace.visualstudio.com/items?itemName=jianglinghao.vscode-npm-scripts) extension. It works in the same way as the built-in one.

**Comment by gitbrent** [comment]
None of the solutions above are working for me on Win10 v1.55

**Comment by devuxer** [comment]
@egamma, Can you give us an idea or whether a fix for this will be coming soon? Thx.

**Comment by khalafalla** [comment]
Same problem here

**Comment by khalafalla** [comment]
Right click on "EXPOLRE" and you will find it there
![Untitled](https://user-images.githubusercontent.com/52414233/113944058-32880c00-9804-11eb-8d23-092e41e485d7.png)

**Comment by sammok83** [comment]
Same issue for me as well. After a few restarts it appears randomly...

**Comment by charlwillia6** [comment]
> Right click on "EXPOLRE" and you will find it there
> ![Untitled](https://user-images.githubusercontent.com/52414233/113944058-32880c00-9804-11eb-8d23-092e41e485d7.png)

Not in my case. It's not an option and no amount of window reloads brings it back.

**Comment by mobilotronic** [comment]
For what is worth and if it helps anyone I did this (doesn't mean that 100% will work for you):

- I installed manually the extension NPM-Scripts by traBpUkciP
![image](https://user-images.githubusercontent.com/77811893/113998094-a3edac00-9850-11eb-825c-1a0de7f4e8b3.png)
- I then got two NPM Scripts panels
![image](https://user-images.githubusercontent.com/77811893/113998174-b7007c00-9850-11eb-9934-80edafed5369.png)
- I then uninstalled the extension I manually added, a reload was required. After that the built-in NPM Scripts is still there and showing up in the [...] menu

**Comment by joserubicon** [comment]
Same here, it seems to fail (most cases) randomly.

**Comment by gizmo2342** [comment]
Same here. 

On MacOS I was able to bring it back with `> Window Reload`, on Windows 10 it did not work.

**Comment by manst** [comment]
Same here, 1.55.1 win 10 x64

**Comment by JLa2r** [comment]
Same here. Been off-and-on for a while but today I can't get it to display at all.
Windows 10 x64

**Comment by oguh43** [comment]
> Same here.
> 
> On MacOS I was able to bring it back with `> Reload Window`, on Windows 10 it did not work.

Same, although I can (sometimes) restore it with `Reload Window`

**Comment by Aleinbanger** [comment]
> Same here, it seems to fail (most cases) randomly.

Same. Randomly reappeared today, then disappeared again on next launch.

**Comment by sebu10n** [comment]
Since the update I do `> Developer: Reload Window` every day...

(Windows 10)

**Comment by fuxichen** [comment]
我今天升级了vscode 1.55.2。这个问题还是没有修复
但是我发现每次使用`File > Close Folder` 然后 `File > Open Folder`，就能显示npm script
I upgraded vscode 1.55.2 today. This problem has not been fixed。
But I find that every time I use `File > close folder` and then `File > Open Folder`, NPM script can be displayed

**Comment by yubaoquan** [comment]
Will this be fixed in next month?

**Comment by SpreadTriad** [comment]
In 1.55.2 on MacOS, I switched on "Npm: Enable Run From Folder" in the settings, which opened the panel. On restarts it is opening consistently, so far. I have the package.json in the root folder, not sure if it works in other cases. Also not sure if this is the expected behaviour for this option, but it's something.

It seems that on Windows this works only occasionally and the "reload window" is a more reliable workaround (if you can call it that).

**Comment by alexh00** [comment]
Glad its not just me that is getting this problem, hope it gets fixed soon

**Comment by devuxer** [comment]
Just did some experimenting with @SpreadTriad's workaround, and I now wonder if the NPM Script Explorer bug may actually be caused a bug with the `npm.enableRunFromFolder` setting.

Before I tried anything, I checked my user and workspace Settings.json file. I already had `npm.enableRunFromFolder` set to `true` in my **user** Settings.json, and this setting was not listed in my workspace Settings.json.

In my mind, this **should** mean that the workspace setting would take on the value of the use setting and also be `true`. However, when I opened the settings editor, the setting was checked in my user settings but unchecked in my workspace settings.

So, I clicked the checkbox on in the workspace settings, which caused an entry to be added to my workspace Settings.json, then when I reloaded my window, and script explorer was back!

So, to me, this indicates the setting is not being properly inherited from the user to the workspace.

cc @egamma, perhaps this will help in isolating the problem.

**Comment by yubaoquan** [comment]
> Just did some experimenting with @SpreadTriad's workaround, and I now wonder if the NPM Script Explorer bug may actually be caused by a bug with the `npm.enableRunFromFolder` setting.
> 
> Before I tried anything, I checked my user and workspace Settings.json file. I already had `npm.enableRunFromFolder` set to `true` in my **user** Settings.json, and this setting was not listed in my workspace Settings.json.
> 
> In my mind, this **should** mean that the workspace setting would take on the value of the user setting and also be `true`. However, when I opened the settings editor GUI, the setting was checked in my user settings but unchecked in my workspace settings.
> 
> So, I clicked the checkbox on in the workspace settings, which caused an entry to be added to my workspace Settings.json, then when I reloaded my window, and script explorer was back!
> 
> So, to me, this indicates the setting is not being properly inherited from the user to the workspace.
> 
> cc @egamma, perhaps this will help in isolating the problem.
> 
> EDIT: Well, maybe that was a fluke because I just opened VSCode again, and I once again can't get the NPM Script Explorer to show no matter what I do with `npm.enableRunFromFolder` and reloading the window. Back to the drawing board I guess.

Not working for me.

**Comment by jeff-a-andersen** [comment]
For me, the problem was the presence of the setting "workbench.sash.size" in ".vscode/settings.json" or in my ".code-workspace" file I use to open my workspaces.  Removing that specific setting makes NPM Scripts explorer load every time for me now.

It had always worked in those files since the "workbench.sash.size" setting was released in May 2020, but broke after the March 2021 release for some reason.

**Comment by devuxer** [comment]
@jeff-a-andersen , I don't have that setting in any of my settings files.

**Comment by ayoubsousali** [comment]
still have the problem in v1.55.2 (win10)

the work around
- Help -> Release Notes
-  > Developer: Reload Window
is working for me and I don't know why!

**Comment by petersendidit** [comment]
😕 Doing `Help -> Release Notes` results in the NPM Scripts side bar showing back up for me.  🤯 

No clue why.

**Comment by sibeliuz** [comment]
Help -> Release Notes doesn't work for me
Developer: Reload Window works fine (usually after 2-3 attempts)

**Comment by jeff-a-andersen** [comment]
The NPM script explorer just seems to be unstable now.  Sometimes it comes up, sometimes it doesn't.  For a while, not having the "workbench.sash.size" setting seemed to fix it but then it sporadically occurs again.  At this point, I find that I pretty much have to "click my heels 3 times", "cross my fingers", "rub my rabbit foot" and hope it loads.

**Comment by GU0FORY1** [comment]
Same here, 1.55.2 win 10 x64

**Comment by alexr00** [comment]
👋Hi folks. I think I see where the problem is, and I've pushed a change to address the issue. If you could download the insiders build and try it out it would help me verify that the issue is solved!

**Comment by jeff-a-andersen** [comment]
> 👋Hi folks. I think I see where the problem is, and I've pushed a change to address the issue. If you could download the insiders build and try it out it would help me verify that the issue is solved. A bot will leave a comment when the fix is available in insiders.

Thanks @alexr00! I'll give insiders a whirl tonight when I can and let you know how it works for me.

**Comment by jeff-a-andersen** [comment]
Just tried insiders build and the problem seems to be fixed now.  Thanks @alexr00!

**Comment by alexr00** [comment]
Thanks for verifying!

**Comment by itsems** [comment]
Just downloaded insider and it works, 
Thank you @alexr00 !

**Comment by exhesham** [comment]
it is not the first time this poor feature is damaged! Please check yourself before pushing a change.
