### ISSUE TITLE
Up and down arrows do not work in Notebook renderers

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#120259]
- VS Code Version:Insiders
- OS Version:Mac

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=donjayamanne.kusto
2. Ensure you start VS Code with the following cli `code-insiders --enable-proposed-api=donjayamanne.kusto`
3. Run a simple kusto query that outputs a table `StormEvent take 10`
4. In the data table rendered, select a row & use the up/down arrow & you'll notice that it doesn't work.
Here's a gif
![issue](https://user-images.githubusercontent.com/1948812/113184207-c4db4f00-9209-11eb-829e-75efc20a5772.gif)

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
We may need to add `!outptufocus`  to arrow keys but not sure if it leads to weird issues (like focus in the output, arrow key does nothing, now that the arrow key is kind of trapped)

**Comment by DonJayamanne** [comment]
I can how this would be a problem with Jupyter notebook output as well (Widgets).

**Comment by roblourens** [comment]
We shouldn't block our commands from running if focus is in the webview, that will happen a lot. But in my testing, the renderer's keyboard event handler will be hit, and if they call stopPropagation, vscode will not get the event. Does your renderer do this @DonJayamanne? Where's that code in your repo?
