### ISSUE TITLE
notebook.cell.execute command never returns

### ISSUE THREAD

**Issue by daytonellwanger** [microsoft/vscode#120209]
`vscode.commands.executeCommand('notebook.cell.execute', ...)` never returns. It doesn't throw either. However, it's unclear when this command should return. Should it return as soon as the kernel is invoked? When all cells are done executing?

**Comment by roblourens** [comment]
Works for me. It should return once the kernel has been called but it won't wait for execution to complete. Can you give some more details? Is this Insiders?

**Comment by daytonellwanger** [comment]
Version: 1.55.0-insider (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T12:48:52.547Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
Can you give me a code sample or some more context? I see it completing

**Comment by daytonellwanger** [comment]
This will do it:
```
context.subscriptions.push(
		vscode.commands.registerCommand('notebook-renderers.runCell', async () => {
			console.log('Executing');
			try {
				await vscode.commands.executeCommand('notebook.cell.execute', { start: 1, end: 2 }, vscode.window.visibleNotebookEditors[0].document.uri);
			} catch (e) { console.log('Error: ', e); }
			console.log('Done');
		})
	);
```

Output:
```
Executing
```

Here's the full repro extension (includes some extras)
[repro.zip](https://github.com/microsoft/vscode/files/6240269/repro.zip)
.

**Comment by roblourens** [comment]
This is probably because your `executeCellsRequest` returns a promise that does not resolve

```
executeCellsRequest(document: vscode.NotebookDocument, ranges: vscode.NotebookCellRange[]): Thenable<void> {
		const task = vscode.notebook.createNotebookCellExecutionTask(document.uri, ranges[0].start, this.id);
		task!.start();
		return new Promise((resolve, reject) => {
			task!.appendOutput(new vscode.NotebookCellOutput([new vscode.NotebookCellOutputItem('text/html', 'Hello!')]));
			setTimeout(() => {
				task!.appendOutput(new vscode.NotebookCellOutput([new vscode.NotebookCellOutputItem('text/html', 'Goodbye')]));
				task!.end();
			}, 3000);
		});
	}
```
