### ISSUE TITLE
Improve syntax highlighting facilities for notebook output renderers

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#120219]
Ideally, I'd like a way for a notebook output renderer to say, "Render `<block of code>` as `<some language>` using VS Code's syntax highlighting machinery." For example:

```typescript
interface NotebookRendererApi<T> {
    renderAsLanguage(lang: string, params: NotebookOutputEventParams);
}
```

This method would cause the cell output to be rendered as the specified language. For example, if I called `notebookApi.renderAsLanguage('xml', e)`, the user would see beautifully rendered XML, using whatever color theme and language support they have installed, similar to how the default renderer for `application/json` works.

Barring that, or in the meantime, I want the editor token colors to be exposed to WebViews as CSS variables. That way, while I still have to include some other highlighter like highlight.js, I can match the user's color theme:

```css
.hljs-string {
    color: var(--vscode-editorToken-stringColor);
}
```

**Comment by connor4312** [comment]
Thanks for the issue, this has been a question for custom editors as well. Currently, we don't provide anything out of the box, but for notebooks specifically I think we can be smarter here: https://github.com/microsoft/vscode/issues/120260

In general, if you wanted a webview custom editor to look the same as VS Code:

- embed a monaco editor in the renderer
- you need to load wasm textmate tokenizer (which we provide)
- register it as a tokenizer for monaco
- check the theme used in vscode
- find its theme extension folder, get its token/color files, send them over to the webview
- lastly/finally, tokenize the code
- and then listen to theme change
