### ISSUE TITLE
TypeScript/JavaScript| Indentation after `break;` in `case` statement

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120235]
- VS Code Version: 1.54.3
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

Should `enter` after `break;` start new line with cursor aligned to `case` not to `break;` as GIF shows. Because any line after `break;` is useless.

![1](https://user-images.githubusercontent.com/17777237/113135828-ea288700-9222-11eb-97b1-1ce5dbe29ca5.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by justinemojal** [comment]
https://github.com/microsoft/vscode/issues/104836#issuecomment-736204829

**Comment by mjbvz** [comment]
I'm closing this because we don't expect to get around it in the near future

You can enable format on type to work around this
