### ISSUE TITLE
Debt - Revisit and improve the use of the editor inside the debug console

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12020]

**Comment by egamma** [comment]
One issue is that once you install the VIM extension, then line numbers show up in the text input field in the debug console.

![image](https://cloud.githubusercontent.com/assets/172399/19071444/71c11240-8a30-11e6-9c6c-747c7275780d.png)

**Comment by isidorn** [comment]
Let's close this as a duplicate of https://github.com/Microsoft/vscode/issues/46112
Since that one is already referenced on the plan
