### ISSUE TITLE
word wrap

### ISSUE THREAD

**Issue by emm3arose** [microsoft/vscode#120223]
Issue Type: <b>Feature Request</b>

the shortcut for "toggle word wrap" is alt+z, which is also a nvidia shortcut for geoforce options. Geoforce overrides vscode, so it's annoying and you should switch the shortcut, especially since geoforce is getting more prevalent so it will get more and more inconvenient for your users. 

VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19041

**Comment by alexdima** [comment]
Unfortunately, it is not feasible for us to change our default keybinding so late, because there are millions of developers that might be used to the default `alt+z` and breaking all of them would not be helpful.
