### ISSUE TITLE
Proxy-bypass-list is not working

### ISSUE THREAD

**Issue by StephanMuenzberg** [microsoft/vscode#120231]
**Specs:**
- VS Code Version: 1.54.3
- OS Version: Windows 10 Enterprise, 10.0.17763

**Steps to Reproduce:**
1. Start VS Code from Powershell with https_proxy set
`code . --proxy-server="https_proxy=https://user:pass@corpproxy:8080" --proxy-bypass-list="https://marketplace.visualstudio.com" --log-net-log="netlog.json" `
2. Open Marketplace in VS Code

Does this issue occur when all extensions are disabled?: Yes

**Description:** 
I am sitting behind a corporate firewall and need to use a proxy to use specific VS Code extensions like VS Code for Databricks. Unfortunately, if I set the proxy as shown below, the marketplace (& some other Extensions) fail due to

`ERR_CONNECTION_TIMED_OUT`.

Therefore, I thought I could define an exception for the marketplace using the proxy-bypass-list option. Nonetheless, it does not work and the error stays.

I even tried star versions of the market place address without any success. Furthermore, I tried to set the log-net-log flag, but no file can be found in the specific folder for some reason.

Do you have any ideas what I could try further? Without the proxy the Marketplace works like expected, but VS Code for Databricks does not.

Best regards,
Stephan

**Comment by chrmarti** [comment]
Tried on Mac and this is working fine for me. Could you try without the quotes? (Haven't tried with PowerShell or cmd on Windows.)

**Comment by StephanMuenzberg** [comment]
Hi chrmarti, 

thank you for you help. As I have multiple quotes in the line, I checked the following alternatives.

`code . --proxy-server=https_proxy=https://user:pass@corpproxy:8080 --proxy-bypass-list=https://marketplace.visualstudio.com --log-net-log=netlog.json`

`code . --proxy-server="https_proxy=https://user:pass@corpproxy:8080" --proxy-bypass-list=https://marketplace.visualstudio.com --log-net-log=netlog.json`

`code . --proxy-server=https_proxy=https://user:pass@corpproxy:8080 --proxy-bypass-list="https://marketplace.visualstudio.com" --log-net-log=netlog.json`

`code . --proxy-server=https_proxy=https://user:pass@corpproxy:8080 --proxy-bypass-list="https://marketplace.visualstudio.com" --log-net-log="netlog.json"`

All with the same result as before - no connection to the marketplace.

**Comment by chrmarti** [comment]
Testing with VS Code 1.55 (please update if you haven't already to make sure we compare the same versions) on Windows with both PowerShell and cmd.exe I have to remove `https_proxy=` to get the proxy to work. The proxy bypass list then works for me in both shells:
```
code . --proxy-server="https_proxy=https://user:pass@corpproxy:8080" --proxy-bypass-list="https://marketplace.visualstudio.com"
```

`--log-net-log` uses the install folder if the filename is not an absolute path (this might be different on other platforms). Might be best to use an absolute path then.

Make sure you close all VS Code windows before launching with these options. If it doesn't work, check with the Task Manager if there is any VS Code process hanging around after you closed the last window and terminate it (or just reboot the machine to be sure).

**Comment by StephanMuenzberg** [comment]
> I have to remove `https_proxy=` to get the proxy to work. 

Just to make sure, does this mean your command looks like this?

```
code . --proxy-server="https://user:pass@corpproxy:8080" --proxy-bypass-list="https://marketplace.visualstudio.com"
```

The problem persists. I even updated to v1.55

**Comment by chrmarti** [comment]
The DNS lookup succeeds, but then the SSL connection times out. Can you access https://marketplace.visualstudio.com using Chrome/Chromium?

**Comment by StephanMuenzberg** [comment]
In general yes, but if I start chrome with the same proxy switch it is not connecting. 

I found some reference saying that Chromes proxy configuration is not working with non-transparent proxies, which need user:pass combinations. https://superuser.com/questions/902620/google-chrome-proxy-settings-with-username-and-password

Might this be the reason?

I know I could set the proxy in VS Code as well, but we have a policy to avoid passwords on our local machines. Therefore we thought about putting the credentials in an Azure KeyVault, query them via Azure CLI and to pass them to VS Code on start. 

I saw you are also working on Azure CLI projects, so maybe you can comment if something like this would be possible.

**Comment by chrmarti** [comment]
You could try using the `HTTP_PROXY` and `NO_PROXY` environment variables to get your configuration passed in. That should apply to extensions, but not to the Extensions viewlet.

**Comment by StephanMuenzberg** [comment]
Just to make sure, this would mean to define them as $Env:HTTP_PROXY and $Env:NO_PROXY in Powershell, correct? Or do you mean their definition within VS Code Settings?

**Comment by chrmarti** [comment]
Correct, as environment variables `$Env:HTTP_PROXY` and `$Env:NO_PROXY`. `HTTP_PROXY` should be the URI (without the `https_proxy=` prefix) and `NO_PROXY` should be just the hostname (or domain name with a leading `.`).

**Comment by StephanMuenzberg** [comment]
Sorry for the delay. I tested setting proxies via $Env. Unfortunately still no real effect. It looks exactly like if I would have not set proxies. 

This means, Databricks does not work, but the marketplace is fine.

See attached the netlog file.
[netlog.json.txt](https://github.com/microsoft/vscode/files/6294626/netlog.json.txt)

**Comment by chrmarti** [comment]
Make sure you use `Override` for `Proxy Support` in the user settings. The netlog shows the PAC file applied. Could you try using the `HTTP Proxy` user setting (although the env variables should have worked too)? You would set that to `http://user:pass@corpproxy.com:8080`, using `https` instead if the proxy is using SSL.
