### ISSUE TITLE
Drag tab will cause freeze

### ISSUE THREAD

**Issue by ahdung** [microsoft/vscode#120283]
vscode: 1.55.0 x64 (system setup), **actually it happed long time, not only this version**
commit: c185983a683d14c396952dd432459097bc7f757f
date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.1.7601 (Windows server 2008 R2 sp1)

`--disable-gpu` not work.

**Comment by ahdung** [comment]
![recording](https://user-images.githubusercontent.com/12094247/113267142-9728ff80-9308-11eb-8f56-163778b100d7.gif)

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by ahdung** [comment]
not work

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ahdung** [comment]
Sorry i'm late, insider build still same issue.
