### ISSUE TITLE
Make Jupyter Notebook changes visible on Source Control before commit

### ISSUE THREAD

**Issue by ikivanc** [microsoft/vscode#120229]
I use Jupyter Notebook extension.

As a developer/data scientist I would like to see jupyter notebook code changes when I check on source control before commit my code. 

![image](https://user-images.githubusercontent.com/118657/113120137-f0663580-9219-11eb-8b99-77e87e9700b3.png)

Suggestion:
Jupyter Notebook extension can preview my Jupyter Notebook in `Files` section when I open it, but before commit to my repo in `Source Control` section it can only show Jupyter Notebook file as code where I can see my changes in the file.

**Comment by rebornix** [comment]
/extJupyter

you are now currently using the custom editor version of Jupyter notebook, there is a bug on their side which blocks you from seeing the diff editor.
