### ISSUE TITLE
Feature Request: Open error window when errors are found

### ISSUE THREAD

**Issue by sqrtroot** [Microsoft/vscode#12027]
- VSCode Version: 1.5.2

I would like the problems window to automatically open when a problem is found by the task runner.
Would it be possible to implement this feature?

**Comment by sandy081** [comment]
Thanks for filing the feature request.

I think I am not favourable to this feature. There are multiple indications when there is a problem. They are shown on the status bar at the bottom. Also there are squiggles in the editor to indicate them. This is just my opinion.

But, I would rather wait to see if there is similar feedback/requests from the community before going forward.

**Comment by joeferraro** [comment]
Is is possible to programmatically show the error panel?

**Comment by sqrtroot** [comment]
It would be nice if we had some kind of interface between programming and errors. To do thinks like check for errors, show the panel, add/remove errors etc.

**Comment by sandy081** [comment]
>>Is it possible to programmatically show the error panel?

There is no command to show the error panel but there is one to toggle `workbench.actions.view.problems`

>> It would be nice if we had some kind of interface between programming and errors. To do thinks like check for errors, show the panel, add/remove errors etc.

You can use the default key-binding <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd> to toggle the panel. Panel is just a read only view to show errors/warnings. IMO the correct way is to remove errors/warnings is to fix it or configure (if supported) the source of them.
