### ISSUE TITLE
Context menu won't close.

### ISSUE THREAD

**Issue by abelqwerty** [microsoft/vscode#120287]
The context menu appears when I click s. Upon further investigation it was proven to be a fault in my computers automatically chosen language why the context menu opened on s. However, after fixing this the menu still refuses to close and I've been unable to work use VSCode. As its always there even after rebooting and reopening. The menu just refuses to die now.

**Comment by abelqwerty** [comment]
After back checking some more times it seems to activate on s, right click and left click

**Comment by sbatten** [comment]
@abelqwerty can you provide some more info about what menu is not closing and provide a screenshot?
