### ISSUE TITLE
Improve toolbar UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120226]
Here's a couple of variations from @misolori:

## Toolbar hovers

![CleanShot 2021-03-30 at 11 42 32](https://user-images.githubusercontent.com/22350/113105017-ffb39780-91b5-11eb-8406-723fd33321cc.gif)

## Run split button

![CleanShot 2021-03-31 at 12 56 49](https://user-images.githubusercontent.com/35271042/113203389-d845e480-9220-11eb-9c10-4c914fada2ef.gif)

<img width="600" src="https://user-images.githubusercontent.com/35271042/113203841-5f935800-9221-11eb-9371-0b95b156474d.gif">

![image](https://user-images.githubusercontent.com/22350/113105080-0e01b380-91b6-11eb-9448-f2f4f172fc88.png)

**Comment by jrieken** [comment]
duplicates https://github.com/microsoft/vscode/issues/117722?

**Comment by joaomoreno** [comment]
@jrieken I would keep things separate and just have this affect the UX of existing actions.

**Comment by kytosai** [comment]
I can't see hover feedback on collapse arrow in folder left sidebar :(

**Comment by misolori** [comment]
@kytosai the tree view chevrons were not included in this original change as this was scoped to toolbar actions. Will try to get this in the next iteration.
