### ISSUE TITLE
Unable to locate python interpreter

### ISSUE THREAD

**Issue by Ad1000** [microsoft/vscode#120254]
Visual studio code is unable to locate any python interpreters. Nothing is showing up in the View command palette.

**Comment by Ad1000** [comment]
I was able to resolve the issue.

**Comment by rajavsoni** [comment]
> Visual studio code is unable to locate any python interpreters. Nothing is showing up in the View command palette.

@Ad1000 I am experiencing the same issue, how did you resolve it?
