### ISSUE TITLE
Split intellisense icon sprite

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12029]

**Comment by joaomoreno** [comment]
@bgashler1 Can we get these svg icons separated?

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/browser/symbol-sprite.svg

**Comment by bgashler1** [comment]
Sure.

**Comment by bgashler1** [comment]
@joaomoreno I think we have some other sprites like this that are slightly different.  Do we need those separated as well?

**Comment by joaomoreno** [comment]
This is the only one causing pain right now afaik.

**Comment by chryw** [comment]
I'm on it. The light theme ones are done. Will finish the dark theme version soon.

**Comment by chryw** [comment]
@bgashler1 @joaomoreno The original sprite has a mix of full size and medium size (intelliSense dropdown version) icons. I included both size for each icon. If these icons are for dropdown list, please use the version has "_left" or "_16xMD" in filename. If used for a regular button, please use the full size version. 

[264213_Brad_VSCodeSplitIconSprite_ToClient.zip](https://github.com/Microsoft/vscode/files/475836/264213_Brad_VSCodeSplitIconSprite_ToClient.zip)

**Comment by bgashler1** [comment]
@joaomoreno closing this issue for now.  Feel free to open if you need anything else.

**Comment by joaomoreno** [comment]
I wanna adopt it.

**Comment by joaomoreno** [comment]
@bgashler1 @chryw That icon set seems to be missing the snippet SVG icons. Please send them my way once you get a hold of them.

**Comment by joaomoreno** [comment]
Never mind, I extracted it from the sprite.
