### ISSUE TITLE
Allow to theme keybindings widgets in quick open command palette

### ISSUE THREAD

**Issue by schittli** [microsoft/vscode#120201]
The Command Palette is almost perfect - thanks a lot!: 
it even displays **keyboard shortcuts. Unfortunately, they are sometimes not readable**:

![image](https://user-images.githubusercontent.com/8282673/113052284-39c96d00-91a7-11eb-99a6-c110311aa0cb.png)

According to the theme-color reference: https://code.visualstudio.com/api/references/theme-color
it is not possible to adjust the keyboard shortcut color 😞. 

Can you please allow us to configure it by something like:
```
   "workbench.colorCustomizations": {
        "[Color Scheme Name]":{
            "symbolIcon.hotkeyForeground": "#ff0011"
        }
    }
}
```

Thanks a lot, kind regards,
Thomas

**Comment by bpasero** [comment]
@aeschli the keybindings editor is owned by @sandy081

**Comment by TylerLeonhardt** [comment]
@bpasero I looked into this a bit today, I think I need a bit more hand-holding to understand how to theme things. Also, I would guess that the keybindings editor should also have this since it also uses KeybindingLabels. Should those be themed the same? I feel like they should

**Comment by bpasero** [comment]
@TylerLeonhardt oh actually seems the widget itself is not yet themed:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/base/browser/ui/keybindingLabel/keybindingLabel.css#L14

That makes this task a bit more involved, and you are right it would apply to all places where we show keybindinglabel, not just quick open. 

We can split this issue up maybe, or rename this one to reflect the intent better.

**Comment by TylerLeonhardt** [comment]
@bpasero Maybe this coming with we can talk about what the plumbing looks like for theming something?

I gave it a good look on Friday and found the color registry and where parts of the quick pick are themed, but I couldn't quite work out how to theme items in the quick pick list.

I might have been over complicating it.

**Comment by bpasero** [comment]
Yeah we can sync on this. I think the best strategy is to copy what we do for other themeable components of quick input and apply that to keybindinglabel widget. For example buttons define overridable colors here to declare it is theme ready, which is pretty much the first step:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/base/browser/ui/button/button.ts#L26

And quickinput declares these styles too:

https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/base/parts/quickinput/browser/quickInput.ts#L58

**Comment by TylerLeonhardt** [comment]
@bpasero that makes sense. Does the button theming you linked apply to both buttons in the quickpick title bar and buttons inline (for example the X button in the recently opened quick pick)?

If so, that's probably the best example to go off of since the key bindings are also inline.

The part I struggled with was that the keybings are really inside of a list widget inside of a quickinput widget (I think). Previously I was looking at the count badge which is themable and tried to copy off that, but the keybindings being a part of the list widget added an extra layer of complexity.

I _think_ I need to pass the themes from the quickinput widget down to the list widget and then down to the keybinding label widget... But I didn't quite see where the best place to do that was in the list widget code.

Maybe I'm totally off though.

**Comment by bpasero** [comment]
@TylerLeonhardt maybe this one is a good one to look at:

https://github.com/microsoft/vscode/blob/874d19930e3200b4ceb23520f59c99d653d4dc3d/src/vs/base/parts/quickinput/browser/quickInput.ts#L60

It defines some additional colors for the list widget that only occur in the quick input control but nowhere else. I think the keybindinglabel being embedded to the list is similar and only applies to the quick input. These options would then have to be passed down to the keybindinglabel widget when created here:


https://github.com/microsoft/vscode/blob/874d19930e3200b4ceb23520f59c99d653d4dc3d/src/vs/base/parts/quickinput/browser/quickInputList.ts#L136

**Comment by TylerLeonhardt** [comment]
### Verification steps:

#### New high contrast value

1. set the theme to High Contrast
2. Open the Command Palette
3. You should visually see keybinding labels with no background, only a border.

#### Themable labels

1. Override your theme's keybinding label colors:
```
"workbench.colorCustomizations": {
    "[Color Scheme Name]": {
        "keybindingLabel.background":"[PICK A COLOR]",
        "keybindingLabel.foreground":"[PICK A COLOR]",
        "keybindingLabel.border":"[PICK A COLOR]",
        "keybindingLabel.bottomBorder":"[PICK A COLOR]"
    }
}
```

2. Verify you see your color changes in the following places:
    * Command Palette
    * "Keyboard Shortcuts" editor
    * "Keyboard Shortcuts" chord reader modal (just edit a keybinding in the editor to see the modal)
    * In the "Commands" section of the "Feature Contributions" section of an extension (ex. search for the PowerShell extension in the marketplace (you don't have to install it) and view the Extension editor)

**Comment by bpasero** [comment]
@TylerLeonhardt works fine, don't forget to document the new color keys in release notes and our theming reference 👍
