### ISSUE TITLE
Avoid redundant view update on metadata change

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120282]
Issue Type: <b>Bug</b>

Currently when rendering a cell, we might read the `offsetHeight` of cell output twice as there is a metadata change which leads to `updateForCollapseState`

https://github.com/microsoft/vscode/blob/b41213c5735cca9030bb761594a8492d01ad52e1/src/vs/workbench/contrib/notebook/browser/view/renderers/codeCell.ts#L102-L105

<img width="549" alt="image" src="https://user-images.githubusercontent.com/876920/113227912-94ff6c00-9248-11eb-80f4-3b3ffdb163da.png">

VS Code version: Code - Insiders 1.55.0-insider (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T12:47:00.900Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoccf:30278406
vsc_aa:30263845
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
vscoregs2cf2:30281057
vstes263cf:30280005

```

</details>

**Comment by rebornix** [comment]
We can probably cache `inputCollapse/outputCollapse` state.

**Comment by roblourens** [comment]
I have a fix but will wait for https://github.com/microsoft/vscode/issues/120513 so I can test properly
