### ISSUE TITLE
"Reopen With... " from search editor to text editor no-ops,

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#120221]
https://github.com/microsoft/vscode/pull/120198

**Comment by lramos15** [comment]
A bigger issue is that going from Text Editor -> Search closes the tab. For example I went Search -> Hex -> Text -> Search. It transitions all fine but it seems like the Text to Search and the Search to Text transition are both very broken.

**Comment by bpasero** [comment]
Isn't this related to https://github.com/microsoft/vscode/issues/121708 ?
