### ISSUE TITLE
Be smarter about when we render notebook output in monaco editors

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#120260]
Peng and I were talking about https://github.com/microsoft/vscode/issues/120219 by @firelizzard18.

Currently, in notebooks we special case the `application/json` mimetype to be rendered with syntax highlighting in an editor. In the issue, Ethan requested a way to render code in the same way within the renderer, but this is hard for a number of reasons. Instead, it would be nice if there was a way to render other languages in the same way we special-case application/json.

Currently, language contributions already list their mimetypes

https://github.com/microsoft/vscode/blob/cdab314713b80fef92c2f9593d4a3d2dd8b9cf27/extensions/json/package.json#L38-L41

so instead of special casing JSON, we could have generic logic that can render mimetypes for any installed language in an editor.

Another way would be an optional property on the cell output...

```diff
export class NotebookCellOutputItem {

-  constructor(mime: string, value: unknown, metadata?: Record<string, any>);
+  constructor(mime: string, value: unknown, metadata?: Record<string, any>, languageId?: string);
```

but I think this is overkill where the mime type mapping could 'just work'.

@jrieken @rebornix @roblourens

**Comment by firelizzard18** [comment]
> Another way would be an optional property on the cell output...
> 
> ```diff
> export class NotebookCellOutputItem {
> 
> -  constructor(mime: string, value: unknown, metadata?: Record<string, any>);
> +  constructor(mime: string, value: unknown, metadata?: Record<string, any>, languageId?: string);
> ```
> 
> but I think this is overkill where the mime type mapping could 'just work'.

This would be useful for languages that don't have a mime type mapping. For example, from golang/vscode-go:

```json
{
  "contributes": {
    "languages": [
      {
        "id": "go",
        "extensions": [
          ".go"
        ],
        "aliases": [
          "Go"
        ]
      }
    ]
  }
}
```

**Comment by firelizzard18** [comment]
@rebornix in what way is this out of scope?
