### ISSUE TITLE
vscode Can't shut down

### ISSUE THREAD

**Issue by qq1121368078** [microsoft/vscode#120335]
Issue Type: <b>Bug</b>

Click the top right corner,
tip :'Waiting for the updated editor to save' 
Will be waiting forever

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-js-vscodeext-fixed|710|0.3.8
vscode-javascript-snippet-pack|aka|0.1.6
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.6.3
thief-book|C-T|0.0.9
githistory|don|0.6.16
jquerysnippets|don|0.0.1
vscode-npm-script|eg2|0.3.18
vscode-great-icons|emm|2.1.72
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
ilovejuejin|ezs|0.0.16
todo-tree|Gru|0.0.209
minify|Hoo|0.4.3
vscode-gutter-preview|kis|0.27.1
theme-monokai-pro-vscode|mon|1.1.18
vscode-autoprefixer|mrm|3.0.1
vscode-language-pack-zh-hans|MS-|1.55.2
sublime-keybindings|ms-|4.0.8
vetur|oct|0.33.1
vuehelper|oys|0.1.0
convert-css-in-js|pau|1.1.3
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
any-rule|rus|0.3.8
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.1.0
html5-boilerplate|sid|1.1.1
code-spell-checker|str|1.10.2
sass-indented|syl|1.8.16
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
codelf|unb|11.7.0
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.0.2
sort-js-object-keys|zen|1.0.6
material-theme|zhu|3.9.15

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by qq1121368078** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

It's all right now.
I changed the system time caused the problem
