### ISSUE TITLE
Stop using `api.npms.io` in npm VS Code extension and only use npm registry for reliability & privacy

### ISSUE THREAD

**Issue by Jolg42** [microsoft/vscode#120315]
Hi 👋 

So I noticed that the autocomplete is slow to update or can sometimes return wrong/outdated information.
For example: if a package releases a patch / new version, it can take hours, maybe days until the autocompletion also suggests that version.

My second concern about this is that it's actually using `npms.io` which is not run by npm and they have a separate [Privacy Policy](https://npms.io/privacy) which users are not aware of when using this VS Code extension.
Source code https://github.com/microsoft/vscode/blob/0b8a7ca21a9376ead94c6fa8fecb436c8e8e1000/extensions/npm/src/features/packageJSONContribution.ts

From a privacy policy perspective / GDPR and also reliability issues it seems appropriate to remove all usage of this third-party API and only use npm's.
 

Relevant past issues about npms from this repository (I found many more in other repositories):
https://github.com/microsoft/vscode/issues/105334
https://github.com/microsoft/vscode/issues/108159
https://github.com/microsoft/vscode/issues/95130
https://github.com/microsoft/vscode/issues/81280

**Comment by aeschli** [comment]
To verify, 
- check that code completion in dependencies of `package.json` work as expected.
- run VSCode in a environment where `npm` is not on the path, and use hovers over dependencies of `package.json`.
- ` "@types/react-select"` as dependency and verify that the hover shows the actual latest version (currently
4.0.15)
