### ISSUE TITLE
终端异常显示

### ISSUE THREAD

**Issue by 1059811622** [microsoft/vscode#120331]
ort Issue' from the 'Help' menu in VS Code to pre-fill useful information. -->
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SashiRin** [comment]
I do not know whether my issue is the same. But actually after updating to 1.55, display of vscode terminal changed.

Terminal of vscode: 
![image](https://user-images.githubusercontent.com/37045113/113290112-2267bc80-932c-11eb-853a-e22c0b6102dc.png)

Terminus:
![image](https://user-images.githubusercontent.com/37045113/113290147-2f84ab80-932c-11eb-922f-c54ba6243ed8.png)

You could find unnatural vertical line in the output of vscode.

* VS Code Version: 1.55.0 (user setup)
* OS Version: Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. install oh-my-zsh
2. change theme to "agnoster"
3. open terminal of vscode

**Comment by gavxin** [comment]
Had same issue as @SashiRin .  Try change terminal setting "Integrated: Renderer Type" from "auto" to "canvas", it fixed mine.

**Comment by SashiRin** [comment]
@gavxin change renderer type to "canvas" also works for me. But I found "dom" is better. Anyway, thank you!
