### ISSUE TITLE
Settings sync account removed after March update installed

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/vscode#120330]
- VS Code Version: 1.55.0
- OS Version: Windows 10

Steps to Reproduce:

1. Have settings sync enabled and connected to your GitHub account to save data
2. Install at least one extension and sync it
3. Update VS Code to march update 1.55.0

# The problem itself
Settings sync should seem to be reset (it asks again for sign-in, authorization...)
However sync log is not erased

# Expected behavior
VS Code keeping settings sync data

**Comment by tonibofarull** [comment]
I had to re-login to my Microsoft account.

**Comment by sandy081** [comment]
Seems to be related to authentication token

**Comment by RMacfarlane** [comment]
This is expected behavior unfortunately, we made a change to how data is encrypted on Windows which requires users to re-auth there. This should be a one time thing. I meant to include this in the release notes, will update them now to mention it.
