### ISSUE TITLE
VS Code shows warning when using multiple scopes in a textmate grammar

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#120365]
- VS Code Version: 1.55.0 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Use multiple scopes separated by spaces

like this:
```json
"1": {
    "name": "keyword.declaration.struct.rust storage.type.rust"
},
```

![image](https://user-images.githubusercontent.com/5412540/113333500-c1de7c80-9337-11eb-8d28-f672d2f893e0.png)

Using multiple scopes seems working, and I have seen it used in some grammars like JavaScript [here](https://github.com/microsoft/vscode/blob/main/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L481)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@a5hk I wonder, where does that warning come from? When I open the file `extensions/javascript/syntaxes/JavaScript.tmLanguage.json` I see no warnings.

**Comment by a5hk** [comment]
@alexdima I think it comes from this line:
`"$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",`
It is not present in that JavaScript syntax, but `yo code` includes this by default when creating new grammar extension.

**Comment by alexdima** [comment]
@a5hk :+1: Thank you for that extra piece of information! I think the problem is then with that particular schema. Can you please report directly against https://github.com/martinring/tmlanguage , @martinring appears to be very responsive. 

cc @aeschli

**Comment by martinring** [comment]
I have removed the pattern check from the schema, since it seems to cause more problems than it solves. Thank you for linking me here @alexdima.
