### ISSUE TITLE
"Choose a repository" dialog if only one repository is selected in SCM view

### ISSUE THREAD

**Issue by jopfeffe** [microsoft/vscode#120347]
- VS Code Version: 1.55.0
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Open SCM  view
2. Select only one Repo from the list
3. stage a change
4. add a message and try to commit

Result: "Choose a repository dialog" dialog is displayed. 

Expected: Staged change is committed.

Same behavoir when commited change is pushed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
Can you show a screen capture of what you are seeing?
