### ISSUE TITLE
Get a mocha runner worker with the test UI for increased selfhosting

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#120388]
Either writing a standalone mocha provider, or updating the [bridge](https://github.com/hbenl/vscode-test-adapter-api) to the latest API changes.

**Comment by connor4312** [comment]
Done with https://github.com/microsoft/vscode-test-adapter-converter

**Comment by alexr00** [comment]
I installed the extension from https://github.com/microsoft/vscode-test-adapter-converter/releases.
Then I opened the test view but didn't see any tests. Are there additional steps required?

**Comment by connor4312** [comment]
@alexr00 make sure to install the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) and appropriate test adapter that works with the Test Explorer UI extension.

**Comment by alexr00** [comment]
I installed the following:

ms-vscode.test-adapter-converter
hbenl.vscode-test-explorer
hbenl.vscode-mocha-test-adapter

Then I opened the test view:

![image](https://user-images.githubusercontent.com/38270282/116530439-552ab380-a8de-11eb-8f0e-99462709077f.png)

And the error is:

```
Error: Cannot find module 'tape'
Require stack:
- d:\repos\Microsoft\vscode\test\automation\node_modules\call-bind\test\callBound.js
- d:\repos\Microsoft\vscode\node_modules\mocha\lib\esm-utils.js
- d:\repos\Microsoft\vscode\node_modules\mocha\lib\mocha.js
- d:\repos\Microsoft\vscode\node_modules\mocha\index.js
- c:\Users\alros\.vscode-insiders\extensions\hbenl.vscode-mocha-test-adapter-2.11.0\out\worker\bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (d:\repos\Microsoft\vscode\test\automation\node_modules\call-bind\test\callBound.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'd:\\repos\\Microsoft\\vscode\\test\\automation\\node_modules\\call-bind\\test\\callBound.js',
    'd:\\repos\\Microsoft\\vscode\\node_modules\\mocha\\lib\\esm-utils.js',
    'd:\\repos\\Microsoft\\vscode\\node_modules\\mocha\\lib\\mocha.js',
    'd:\\repos\\Microsoft\\vscode\\node_modules\\mocha\\index.js',
    'c:\\Users\\alros\\.vscode-insiders\\extensions\\hbenl.vscode-mocha-test-adapter-2.11.0\\out\\worker\\bundle.js'
  ]
}
```

I have zero knowledge of the test work that has been going on in VS Code, so even steps that are embarrassingly basic will be helpful.

**Comment by alexr00** [comment]
Just to add, I want to be able to test this because running tests is currently the only dev task I can't/don't use VS Code for and it will be great to have modern tools for this.

**Comment by connor4312** [comment]
The mocha runner doesn't work in vscode since our setup is 'special'. You can use a more generic project like https://github.com/connor4312/cockatiel (make sure to npm run watch, as it only detects off compiled files) where it should work.

**Comment by connor4312** [comment]
Also, make sure to check the documentation for the mocha test adapter (or whatever test adapter you're using.) The converter only converts from that adapter into native testing, so you'll need to make sure your tests work in it first https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter

**Comment by alexr00** [comment]
Works well!
![image](https://user-images.githubusercontent.com/38270282/116713602-3e1abd00-a9d5-11eb-8e3c-d6a79729194a.png)
