### ISSUE TITLE
VS Code 1.55 tfs issue of teams not able to sign in : unauthorized, check your credentials and try again

### ISSUE THREAD

**Issue by hirvavithlani2426** [microsoft/vscode#120344]
- VS Code Version: 1.55
- OS Version:

Steps to Reproduce:

1. download latest code version
2. you are not able to sign in teams tfs

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by hirvavithlani2426** [comment]
tfs extension was not working properly with latest vs code version. We had to turn off proxy support which seems like a temporary fix. please look into it

**Comment by RMacfarlane** [comment]
@hirvavithlani2426 Which TFS extension is this? Did the extension update to a new version as well or did nothing change there?

**Comment by onelifenyc** [comment]
I wanted to second this issue. It is the Azure Repos extension which is deprecated but it has not changed in a long time. @RMacfarlane 

It prompts you to login and it fails silently. 

![image](https://user-images.githubusercontent.com/4038782/113621127-44618780-9629-11eb-8d37-276518cfdc76.png)

**Comment by hirvavithlani2426** [comment]
> @hirvavithlani2426 Which TFS extension is this? Did the extension update to a new version as well or did nothing change there?

@RMacfarlane : TFS v2.0.0 is the version, and no it did not get updated, just update in vs code

**Comment by RMacfarlane** [comment]
@hirvavithlani2426 Can you include specific details about what commands you're running, or what error message you see?

**Comment by onelifenyc** [comment]
Since I also have this issue, I wanted to answer that for my case with the most popular TFS extension Azure Repos. No obvious error is reported, however VSCode fails to work with the TF.exe it seems on the surface, however, for me changes are being tracked. Yet I can't use features like DIFF because it keeps telling me I am signed out. 

![image](https://user-images.githubusercontent.com/4038782/117372312-55572000-ae97-11eb-9847-4eae765296ff.png)
 
@RMacfarlane

**Comment by onelifenyc** [comment]
@RMacfarlane I’m sorry but Why would you close the issue if the previous version of vscode worked fine with azure repos extension which is not receiving any updates and hasn’t changed. Only thing that’s changed is vscode. This happens often too. New version of vscode comes out and doesn’t play well with an extension that used to work. I could be wrong but something was broken with regards to that extension. If we go open an issue with the azure repos extension, they’ll just forward us back here. I would have preferred a more specific answer like “azure repos was deprecated and as such vscode doesn’t support it any more, use this or that other extension”. We, who use classic TFS (not voluntarily), are pretty much abandoned by this team.
