### ISSUE TITLE
Terminal's pty host process is unresponsive. Terminal crashes and Remote SSH disconnected.

### ISSUE THREAD

**Issue by gencer** [microsoft/vscode#120398]
- VS Code Version: 1.55.0 (Stable)
- OS Version: Windows 10 21H1 x64

Steps to Reproduce:

1. Use VSCode a while or open few VSCode instances close few reopen few. Basically make sure terminal is opened in each instance by default then close.
2. Terminal will crash. SSH will disconnect.

![113049202-5b0f6680-9171-11eb-813f-66d436697acb](https://user-images.githubusercontent.com/1711576/113374398-bc078c00-9375-11eb-8274-fffcc810f979.png)

Honestly, I wouldn't mind the crashes for terminal but this causes my **Remote SSH disconnects from the server and I have to reload all windows one by one.** Even local VSCode crashes, all other open windows disconnects if they are connected to a SSH Server.

Does this issue occur when all extensions are disabled?: Yes

## Update

In my case, If I open second VSCode instance i got this error and all SSH sessions are terminated. No need to open few or close few. Just second instance triggers.

And sometimes, I had to restart my Windows because after receiving this error, even If I open 1 (one) instance of VSCode at a time, it stills disconnect from remote and unresponsive terminal error given. So, to be clear, once you get this error, its permanent. Since 2 hours I'm using single VSCode instance but I keep getting same issue every few minutes. I am going insane here.

**Comment by shawinder** [comment]
I am also getting this error occasionally since last 2-3 updates after the VSCode team did major changes to make the terminal faster. 
![image](https://user-images.githubusercontent.com/2242439/114262135-30a08300-9993-11eb-8d11-5446c2313753.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
