### ISSUE TITLE
Improve handling of webgl context loss

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120393]
We should adopt https://github.com/xtermjs/xterm.js/pull/3276. An easy fix is to just fallback when this happens, we need to make sure we don't save suggested renderer type if the webgl renderer is good though.

**Comment by connor4312** [comment]
Can you add verification steps?

**Comment by meganrogge** [comment]
To verify:

Using VS code stable - create as many terminals as needed to trigger context loss you'll see ![context loss](https://user-images.githubusercontent.com/29464607/116621693-6e405e00-a8f8-11eb-8d70-e28b807fbf8c.PNG)

Context loss is achieved at a diff't limit for each computer. Now in Insider's, create the same number of terminals. You shouldn't see any of those context loss images.

**Comment by connor4312** [comment]
very nice, I like how the fallback magically works
