### ISSUE TITLE
[1.55.0] Terminal name does not change when a new task shares the terminal with a previous task

### ISSUE THREAD

**Issue by kuojianlu** [microsoft/vscode#120329]
- VS Code Version: 1.55.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a workspace with the following `.vscode/taks.json`:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Task 1",
            "type": "shell",
            "command": "echo 'Task 1'",
            "dependsOn": "Task 2"
        },
        {
            "label": "Task 2",
            "type": "shell",
            "command": "echo 'Task 2'"
        },
    ]
}
```
2. Click **Terminal** -> **Run Task...** -> **Task 1**, the result will be:
![image](https://user-images.githubusercontent.com/37978464/113273461-4072f400-930f-11eb-9379-eaf644035027.png)
The expected terminal name should be **Task 1**.

By the way, the result on version 1.54.3 is right.

Does this issue occur when all extensions are disabled?: Yes

**Comment by haugerbr** [comment]
I have noticed this behavior also as of 1.55.0

**Comment by alexr00** [comment]
I can also repro. Tasks uses the terminal re-use internal api, and debugging I could see the correct `name` is passed in shell launch config here:

https://github.com/microsoft/vscode/blob/d05d8ca4c2590e26517ec87c30892b1b10ef89b1/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1221-L1222

It seems that the terminal is not respecting the name that is passed in `reuseTerminal`.

**Comment by alexr00** [comment]
@Tyriar On days where I use many tasks, this makes it difficult to tell which terminal I actually want to open. I end up having to go through each terminal and open it to check.
