### ISSUE TITLE
Allow extensions to contribute terminal profiles

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#120369]
The new terminal profiles are fantastic! It would be great if extensions could automatically add entries to the list of profiles. This would essentially be a similar feature to [Windows Terminal fragments](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions).

Here is a use-case: the Julia extension adds a command `Julia: Start REPL`, and that then starts a Julia REPL in a new terminal. In my mind, with the new terminal profile UI, that command should really just appear as another terminal profile in the UI, alongside all the other terminal profiles that show up in the terminal drop down. So essentially I would like to see the ability for our extension to add an entry in this list

![image](https://user-images.githubusercontent.com/1036561/113341925-aac16f80-92e2-11eb-9e95-ca235ab1cc31.png)

that reads `New Julia REPL`, and then calls a function in our extension that executes all the necessary steps to start a new Julia REPL in a terminal window.

Ideally that would also help with a "restart" scenario. Right now, if a user starts a new Julia REPL, has that open and then restarts VS Code, VS code starts a new shell that wasn't open in the previous instance. With this feature idea here, I could imagine that VS code at shutdown "remembers" which terminal profile was used to create which terminal instance, and then at restart uses the correct terminal profile to recreate the same terminal that was open in the previous instance.

**Comment by Tyriar** [comment]
We've essentially had this available for the JS Debug terminal for several iterations, just never thought about stabilizing it. My thinking:

- I'll bring this up in the next API sync to see if we can move towards officially stabilize this
- We need to make sure users can remove them by setting the profile name to `null` in their settings
- Right now the API is `terminal.types`, it should be `terminal.profiles`
- Extensions should not include "Create" or "New" in the profile name, we should fix this in JS Debug this iteration

**Comment by davidanthoff** [comment]
Yes, that sounds perfect.

Just out of curiosity: Could we do the same thing that the JS Debug terminal does right now already and it would work? Or is this that just works with internal extensions?

**Comment by Tyriar** [comment]
@davidanthoff missed your last message, you could do that but since it's proposed you couldn't ship an extension with that - it's for internal only until we stabilize it.

**Comment by Tyriar** [comment]
@connor4312 feedback welcome for the new more advanced terminal profile contribution below.

Current simple contribution:

```json
{
	"contributes": {
		"terminal": {
			"types": [
				{
					"command": "extension.js-debug.createDebuggerTerminal",
					"title": "%debug.terminal.label%",
					"icon": "$(debug)"
				}
			]
		}
	}
}
```

---

New contribution:

```json
{
	"contributes": {
		"terminal": {
			"profiles": [
				{
					// type? profileType?
					"id": "js-debug.debugger-terminal",
					"title": "%debug.terminal.label%",
					"icon": "$(debug)"
				}
			]
		}
	}
}
```

API:

```ts
export interface vscode {
	export interface window {
		/**
		 * Registers a provider for a contributed terminal profile.
		 */
		export function registerTerminalProfileProvider(id: string, provider: TerminalProfileProvider);
	}
	export interface TerminalProfileProvider {
		/**
		 * Provide terminal profile options for the requested terminal.
		 */
		provideProfileOptions(): ProviderResult<TerminalOptions | ExtensionTerminalOptions>;
		/**
		 * The terminal was created, let the extension handle/own it.
		 */
		handleProfileTerminal?(terminal: Terminal): ProviderResult<void>;
	}
}
```

Example usage:

```ts
window.registerTerminalProfileProvider('julia.repl', {
	provideProfileOptions() {
		return {
			shellPath: detectedPath,
			icon: 'circle-filled' // #120538
		};
	}
	handleProfileTerminal(terminal: Terminal) {
		this._terminals.push(terminal);
	}
});
```

**Comment by connor4312** [comment]
The provider with provideProfileOptions and handle seems weird. I think a Factory-style that returns a Terminal, like `DebugAdapterTrackerFactory`, would be more natural here. I'm not sure what the `profileType` is, is it used for grouping?

Functionality-wise it seems fine for js-debug's relatively unsophisticated needs 🙂

**Comment by Tyriar** [comment]
> The provider with provideProfileOptions and handle seems weird. I think a Factory-style that returns a Terminal, like DebugAdapterTrackerFactory

This came up in the api call, we're going to just do this:

```ts
export interface TerminalProfileProvider {
		/**
		 * Provide terminal profile options for the requested terminal.
		 */
		provideTerminalOptions(): ProviderResult<TerminalOptions | ExtensionTerminalOptions>;
}
```

Then for the extension to get the handle of the terminal it would listen for terminal open and compare the creationObjects (which I need to make sure aren't getting cloned so it's the same ref).

> I'm not sure what the profileType is, is it used for grouping?

This is the ID of the provider you register: `window.registerTerminalProfileProvider('js-debug.debugger-terminal', { ...`

**Comment by connor4312** [comment]
I see, you mean `id` should be renamed `type`.

That works. Getting the terminal instance directly would be easier, but the listening pattern is something I need to do for lots of other resources so it's not uncommon.

**Comment by Tyriar** [comment]
> I see, you mean id should be renamed type.

Maybe yeah, didn't discuss this in the call though.

> That works. Getting the terminal instance directly would be easier, but the listening-for-creation pattern is something we do for lots of other resources so it's not uncommon.

Yep, seems more intuitive to me to have it on the provider, but providers have a strict definition. I was going to call out how to do it properly in a jsdoc example.

**Comment by Tyriar** [comment]
We'll also need the `onTerminalProfile` activation event for this

**Comment by connor4312** [comment]
Adopted this in js-debug. After using it I was pushed back to feeling that we should have more control or knowledge of the terminal lifecycle. In js-debug, to create the terminal I create a "launcher" instance that's then waiting on the created terminal to show up in `onDidOpenTerminal`. If an error occurs that prevents it from happening, that will leak resources. Or cause the launcher to "attach" to some other random terminal that the user might later open. _Currently_ I don't think this would cause visible side-effects but it could lead to surprises in the future.

**Comment by Tyriar** [comment]
@connor4312 the way I was thinking to recommend was to check the options object, something like this:

```ts
const myOptions: [];
provideTerminalOptions(): ProviderResult<TerminalOptions | ExtensionTerminalOptions> {
myOptions.push(options);
return options;
}

onDidOpenTerminal(e => {
if (myOptions.includes(e.creationOptions)) {
// attach
}
});
```

Did you have an idea on the shape/naming of the API if we were to expose that? Joh wasn't a fan of `handle*` inside a provider.

**Comment by connor4312** [comment]
> which I need to make sure aren't getting cloned so it's the same ref

ah, I forgot about that. That could work, but is not very obvious and doesn't handle the error case (so I would not attach incorrectly, but could have a leak if a terminal failed to open.)

Not sure on naming, some kind of `handle` would be the simplest way to go about it. The leak case could be covered by firing `onDidCloseTerminal` (with some stubbed object) in the event that the initial opening fails.

**Comment by Tyriar** [comment]
Still need to fix:

> ProviderResult explicitly allows returning undefined or null. If you don't want to support this, use : TerminalProfile | Thenable<TerminalProfile> instead

**Comment by Tyriar** [comment]
Will keep it as a `ProviderResult` since it's a provider and all others do this. It will throw and error out correctly if this happens.

**Comment by 4086606** [comment]
Can a trigger or execute method be provided for terminal providers? Would be useful for extension tests 🧪🔬

**Comment by Tyriar** [comment]
@4086606 not sure what you mean?

**Comment by 4086606** [comment]
A `vscode.window.executeTerminalProvider(id: string): ProviderResult<Terminal>` method. Call it with terminal profile id and it spits out the resulting terminal. Sorta like `vscode.commands.executeCommand`!

**Comment by Tyriar** [comment]
@4086606 oh I see, instead of a new API which has a lot of overhead in implementing, I'd recommend just exposing your own command that returns the result of your profile provider.

**Comment by 4086606** [comment]
True. It occurs to me that an `executeProfileProvider` function falls out of the scope of extension tests because it's testing a core functionality of the VSC API. Alrighty
