### ISSUE TITLE
UX - Left margin is way bigger than right margin in Key Bindings page and table width not equal search box.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120316]
- VS Code Version: 1.55.0
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

@misolori  Left margin is way bigger than right margin in Key Bindings page.

![image](https://user-images.githubusercontent.com/17777237/113264731-96c24180-92d3-11eb-8ad5-7af1b2abf66b.png)
![image](https://user-images.githubusercontent.com/17777237/113337061-8b990100-9327-11eb-9275-e4fcaf45158f.png)

And table is bigger than search box on the right and is equal it on the left.

![image](https://user-images.githubusercontent.com/17777237/113266050-14d31800-92d5-11eb-8277-6d2d3a37801d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
- Its not margin on the right, its the width given for that column. 
- Search box (including tools inside) and table are made sure the are aligned

I am not aware of the UX standards for table and it has been like this from beginning and seems to work :) 

So, I am not planning any changes and probably wait for more feedback before acting upon.
