### ISSUE TITLE
Terminal hangs on output longer than Terminal › Integrated: Scrollback settings

### ISSUE THREAD

**Issue by KenYN** [microsoft/vscode#120300]
Issue Type: <b>Bug</b>

1. Set Terminal › Integrated: Scrollback to 1000
2. Run Docker inside Remote SSH session
3. Build cmake application (our particular application has a very lengthy set of installs) with `reset && cmake ...whatever...`
4. After 1000 lines, Terminal hangs

If I set Terminal › Integrated: Scrollback to 10000, for instance, this gives enough space for `cmake` to complete without problems. The original setting of 1000 worked in previous versions of VSCode, so this looks like a regression bug.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.08GB free)|
|Process Argv|--crash-reporter-id 748d1f39-bf08-4a28-8f42-1c13fb33e1ce|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: GTune|
|OS|Linux x64 5.4.0-70-generic|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (8 x 3248)|
|Memory (System)|15.58GB (8.14GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
msg|ajs|0.1.1
vscode-empy|dir|0.1.1
vscode-docker-syntax|dun|0.1.5
vscode-cudacpp|kri|0.1.1
theme-monokai-pro-vscode|mon|1.1.18
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
vscode-gatsby-snippets|nic|1.1.2
remote-x11-ssh|spa|1.5.0
Bookmarks|ale|13.0.4
code-gnu-global|aus|0.2.2
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2
vscode-gatsby-snippets|nic|1.1.2
vscode-qt-for-python|sea|0.6.1
cmake|twx|0.0.17
docker|vsc|1.0.0
yaml|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
pythonvspyt943:30280189
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by chozandrias76** [comment]
This might explain what is happening to me. I had my setting at 10_000, but it would just take 1/2 of a day to get there 😆

**Comment by chozandrias76** [comment]
If I set scrollback to 0 then my VScode crashes with out of memory after a few minutes.

**Comment by RamiHg** [comment]
I'm also getting this. Surprised it's not more common! Downgrading to the previous version was my only workaround.

**Comment by RamiHg** [comment]
I was actually able to 100% reproduce this in 1.54.3 by setting `terminal.integrated.rendererType` to `experimentalWebgl`! I then tried upgrading to 1.55 again to see if setting rendererType to `canvas` would fix it, but strangely enough, it did not.

**Comment by DadEngineer** [comment]
I'm seeing the same issue. I have vscode server running on linux machine and get random terminal hangs for large amount of outputs to terminal that far exceed the Scrollback setting.

**Comment by mill1000** [comment]
Hope this gets fixed soon. It's making the integrated terminal useless when building large projects.

**Comment by Tyriar** [comment]
I can't repro either hanging on output that exceeds scrollback (local or remote) or OOM when scrollback is set to 0. Maybe something was fixed in the meantime?

**Comment by mill1000** [comment]
I have not seen this issue in the last few weeks either. Hopefully it's gone.
