### ISSUE TITLE
TypeScript quick fixes for import should suggest closer ones first

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120313]
I often see TypeScript suggesting or auto-importing a type from a totally different module that is unrelated to my current one. Popular examples are `Disposable` and `URI` or here `IProductConfiguration`:

![image](https://user-images.githubusercontent.com/900690/113261600-f28acb80-92cf-11eb-9050-d725a5b6448e.png)

It would be great if TS could be smart and suggest the right import first based on where I am at. E.g. when I am in a `vs/...` module, do not suggest imports from `vscode.d.ts` or even `xterm`. And if there are multiple results like in the screenshot, suggest the one that is closest in distance.

**Comment by bpasero** [comment]
For `Disposable`:

![image](https://user-images.githubusercontent.com/900690/113261744-1cdc8900-92d0-11eb-834a-3ddd4b0632c0.png)

**Comment by mjbvz** [comment]
Falls under https://github.com/microsoft/TypeScript/issues/41083
