### ISSUE TITLE
Scrollbar cannot be clicked when cell is selected

### ISSUE THREAD

**Issue by tonibofarull** [microsoft/vscode#120348]
- VS Code Version: 1.55.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a Jupyter Notebook
2. Click on the space containing a cell and put the mouse in the scrollbar.

Does this issue occur when all extensions are disabled?: Yes

### Description of the problem
If the ceil is selected the mouse cannot select the scrollbar properly.

### Expected behavior
Ignore the cell and be able to select the scrollbar properly.

![scrollbar](https://user-images.githubusercontent.com/10214431/113312411-8bd6d380-930a-11eb-9504-4acddc85030b.png)

**Comment by rebornix** [comment]
The between cell toolbar has higher view order than the scrollbar it seems.
