### ISSUE TITLE
Failing api test: active editor not always correct... #49125

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#120355]
https://github.com/microsoft/vscode/runs/2247251230?check_suite_focus=true

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/5236d3446048c8c08c9ceb46e1b63d438ab5bd75/extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts#L160-L163

This test shouldn't run our build machines...
