### ISSUE TITLE
Load snippet suggestions faster than import suggestions on autocomplete trigger

### ISSUE THREAD

**Issue by abhijit-hota** [microsoft/vscode#120399]
Consider the `log` snippet for JavaScript that gives us `console.log()`. When I type `log`, it takes anywhere around 2-10 seconds for the imports *AND* the snippets to show up.

The delay for import suggestion is understandable but if there could be a setting* or something which enabled us to **load snippet suggestions quicker than the import suggestions, 'lazy loading' the latter**, it would feel more snappy and fast. 

Simplifying it further, I basically want the snippet suggestions (red arrow in below image) to come up instantly and the autocomplete suggestions (green curly brace-ish) to be appended in the menu whenever they have loaded.
![image](https://user-images.githubusercontent.com/8116174/113374653-2a0a7e00-938b-11eb-9636-f1f950e2a8a6.png)

*I don't know if any such setting exists. Please feel free to note it out and close it if it's available. It can also be the default behavior for suggestions.

**Comment by abhijit-hota** [comment]
> /needsMoreInfo

The autocomplete is slow for snippets too. Is there any way to make snippet suggestions load faster than import suggestions?

**Comment by mjbvz** [comment]
Please fill in the issue template and provide steps to reproduce (such as an example project)

**Comment by abhijit-hota** [comment]
@mjbvz I don't believe it's an issue as such. Maybe I'm proposing a feature without knowing how it works. 

My thinking is *fetching snippet suggestions on autocompletion trigger take lesser amount of time than import suggestions*. The reason I think this **might** be the case is, snippets can be "fetched" from a single source directly but for import suggestions, VSCode has to traverse the files and stuff. Is this thought correct? 

If yes, I'm proposing to display the snippet suggestions as soon as they are loaded and append the import suggestions to the list when they are loaded 2-3 seconds later. If no, then maybe the overall performance is slow on my pc and you can close the issue.

If this still fails to convey the meaning, you may close the issue.

**Comment by mjbvz** [comment]
You jumped to recommending a solution while I want to understand the root cause problem that triggers the issue in the first place. Please share more details so we can understand why suggestions take 2-3 seconds to load in the first place

Also just to be clear: I don't think the proposed solution would work well. It would require resorting/changing the suggestion list after it has already been shown to the user, which would be a frustrating experience for them

**Comment by abhijit-hota** [comment]
> You jumped to recommending a solution while I want to understand the root cause problem

Because I did not know that this was a problem. I thought it was natural for the suggestions to take some time. Apologies for that.

----

> Please share more details

It happens ocassionally. 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.70GB free)|
|Process Argv|--crash-reporter-id 06fc848e-2896-4c4b-87d0-9adcb4b0dd82|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
increment-selection|alb|0.2.0
Bookmarks|ale|13.0.4
simple-react-snippets|bur|1.2.3
vscode-eslint|dba|2.1.19
vscode-notes|dio|1.1.0
vscode-great-icons|emm|2.1.73
prettier-vscode|esb|6.3.2
vscode-import-formatter|hen|0.1.8
vscode-random|jre|1.9.0
dotenv|mik|1.0.1
csv-to-table|php|1.2.3
partial-diff|ryu|1.4.2
transpose|v4r|0.0.5
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details>


----
> Also just to be clear: I don't think the proposed solution would work well. It would require resorting/changing the suggestion..

Ok, thank you for clarifying,

**Comment by mjbvz** [comment]
Can you share your project?

**Comment by abhijit-hota** [comment]
I cannot directly share the code but this is the info:
- **Create React App** Project with the **PWA template**. ([NPM Page](https://www.npmjs.com/package/cra-template-pwa))
- Package Manager: **Yarn**
-  Dependencies
     - "anchorme": "2.1.2", 
    - "antd": "4.13.1",
    - "axios": "0.21.1",
    - "chart.js": "2.9.4",
    - "dayjs": "1.10.4",
    - "firebase": "8.2.10",
    - "json2csv": "5.0.6",
    - "react": "^17.0.1",
    - "react-dom": "^17.0.1",
    - "react-icons": "4.2.0",
    - "react-router-dom": "5.2.0",
    - "react-s3": "1.3.1",
    - "react-scripts": "4.0.3",
    - "react-swipeable": "6.1.0",
    - "workbox-background-sync": "^5.1.3",
    - "workbox-broadcast-update": "^5.1.3",
    - "workbox-cacheable-response": "^5.1.3",
    - "workbox-core": "^5.1.3",
    - "workbox-expiration": "^5.1.3",
    - "workbox-google-analytics": "^5.1.3",
    - "workbox-navigation-preload": "^5.1.3",
    - "workbox-precaching": "^5.1.3",
    - "workbox-range-requests": "^5.1.3",
    - "workbox-routing": "^5.1.3",
    - "workbox-strategies": "^5.1.3",
    - "workbox-streams": "^5.1.3"
- To give you an idea about the project size: Around 40 total files (`.js` and `.jsx`) in the `src` folder. Total LOC: 3200. 

P.S. I have noticed one more thing: The snippet suggestions load up instantly before the `Initializing JS/TS language features` is complete. Import suggestions are not shown in this case. After the language features are initialized (which btw, takes a lot of time again), the suggestions start to slow down.

**Comment by szkrd** [comment]
Not that it matters much, but I understand the problem: when I type "log" and press tab, I want the snippet called "log" to expand - but since the autocomplete suggestion takes a couple of seconds to "arrive", this doesn't happen (and instead the editor just inserts a tab / soft tab, yay).

Even with all extensions disabled, with a medium sized typescript project the autocomplete still takes a couple of seconds to pop up (even if the delay is set to zero and all suggestions are disabled, except snippets).

I tried writing an extension that decouples snippet expand from the autocomplete, but I didn't like the result and imho it can't be done in a sane fashion with the current extension api. 🤷‍♂️
