### ISSUE TITLE
Proxy agent is hijacking requests and redirecting them to localhost

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#120354]
The recent update is causing some weird behavior with proxy agent, perhaps due to the fix for #117054. It is causing the following downstream issues:

https://github.com/microsoft/vscode-docker/issues/2831
https://github.com/microsoft/vscode-remote-release/issues/4800

- VS Code Version: 1.55.0
- OS Version: Win10 20H2

Steps to Reproduce:

1. Install the Docker extension
1. Set up an SSH Docker context
1. Switch to that context
1. Open the Docker explorer tab

When the docker-modem agent tries to make a request to the remote Docker host, the request is instead sent to localhost:80, which typically fails due to either connection refused (if nothing is listening on that port) or 404 (if something is). Other errors can occur, of course.

**Comment by chrmarti** [comment]
docker-modem appears to use its own agent to control how the connection is established. The fix for #117054 breaks that.

**Comment by chrmarti** [comment]
To verify:
- Set up a Docker context using SSH (e.g., using https://github.com/microsoft/vscode-remote-containers/tree/main/test-remotes/ssh-publickey).
- Verify that the Docker extension's viewlet shows no error when that context is active and creating a container with that context makes the container show up in the Docker viewlet. (Not Remote-Containers which was not affected.)

**Comment by chrmarti** [comment]
Fixing https://github.com/microsoft/vscode/issues/117054 again with a check to detect the docker-modem case.
