### ISSUE TITLE
Use resolveAsync in terminal Variable Resolver

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#120328]
With https://github.com/microsoft/vscode/issues/108804 we are trying to remove process.env from the configuration resolver service. The new way to get the environment is async and requires that the all the configuration resolver methods be async. I have started the adoption of the new async methods in https://github.com/microsoft/vscode/pull/120326, but there's one use in terminal that looks like it will require more work:

https://github.com/microsoft/vscode/blob/02d38098249bfaff610704d74031a2530126eb6f/src/vs/workbench/contrib/terminal/common/terminalEnvironment.ts#L266-L271

Option 1: Convert that use of `resolve` to use `resolveAsync`.
Option 2: I provide a new `resolveWithEnv` method on the configuration resolver service that is sync, but requires you to pass in your own `IProcessEnvironment`. 

Which option makes the most sense here?

**Comment by Tyriar** [comment]
I think the usage of `VariableResolver` in `extHostTerminalService` must remain sync since it's used as part of the extension API. Is this a problem there since `process.env` is fine to use? The main purpose of this `VariableResolve` type was to share code between variable processes.

**Comment by alexr00** [comment]
Sounds like Option 2 is the way to go then. I will add a new `resolveWithEnv` method that is sync and lets you pass in your own `IProcessEnvironment`.

**Comment by alexr00** [comment]
Added: 

https://github.com/microsoft/vscode/blob/d06df602de821ffd737e722d45d814e2a8242964/src/vs/workbench/services/configurationResolver/common/configurationResolver.ts#L37-L38

will that let you keep your code reuse?
