### ISSUE TITLE
Cannot open settings editor JSON running from sources

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#120301]
Steps to Reproduce:

1. Run from sources
2. Set `"workbench.settings.useSplitJSON": true`
2. Try opening settings editor in JSON
3. :bug: A notificacion shows `Unable to open 'User Settings': Cannot read property 'textEditorModel' of undefined.`

This broke in df6d78a1695bdf9a1d4984231242ff1fd65247bb
cc @bpasero

**Comment by bpasero** [comment]
@jeanp413 cannot really reproduce, can you report more steps or attach gif?

**Comment by bpasero** [comment]
@roblourens I see quite a few `any` got introduced in https://github.com/microsoft/vscode/commit/8e00f39c5e3b47ab8affc5f91c33266567aeb2e0 and this essentially means, my refactoring got unnoticed for the settings editor. Do you want to take this and make a pass over `any` usages in preferences editor, I think there are more places than that one.

PS: I tried all ways of reproducing this and still cannot, so I assume it will not impact many users and probably needs a custom settings enabled.

**Comment by jeanp413** [comment]
@bpasero Forgot to mention you also need to set this setting
```
"workbench.settings.useSplitJSON": true,
```

**Comment by jeanp413** [comment]
duplicate of #120343 so I'm closing this
