### ISSUE TITLE
VSCode markdown render equation of different height in fraction (denominator)

### ISSUE THREAD

**Issue by sirlis** [microsoft/vscode#120396]
- VS Code Version:
- OS Version:

See the below figure. Both `sqrt` have the same structure at the denominator. The first `sqrt` is lower than the second one. because there is a `x_ik` in it instead of `x_qk`. (`q` is taller than `i`). This makes it less comfortable to view.

default preview:
![image](https://user-images.githubusercontent.com/12960298/113373821-47951300-939e-11eb-82f5-9b64d4317318.png)

Markdown Preview Enhanced:
![image](https://user-images.githubusercontent.com/12960298/113373491-84143f00-939d-11eb-8f47-d57804e4f19b.png)

Steps to Reproduce:

1. open a markdown file.
2. type the following equation
```
$$
sim_c(\boldsymbol x_i,\boldsymbol x_q) = cos(\boldsymbol x_i,\boldsymbol x_q)=\frac{\boldsymbol x_i\cdot \boldsymbol x_q}{\vert\vert\boldsymbol x_i\vert\vert\vert\cdot\vert\boldsymbol x_q\vert\vert} = \frac{\sum_{k=1}^n x_{ik}x_{qk}}{\sqrt{\sum_{k=1}^n x_{ik}^2} \sqrt{\sum_{k=1}^n x_{qk}^2}}
$$
```
3. see the render result

Does this issue occur when all extensions are disabled?: Yes
It happens both under default preview and in `Markdown Preview Enhanced` extension.

**Comment by mjbvz** [comment]
The default markdown preview does not support math equations. This must be coming from an extension

**Comment by sirlis** [comment]
> The default markdown preview does not support math equations. This must be coming from an extension

yes. Thank you. It is related to Markdown All In One.
