### ISSUE TITLE
rust grammar does not assign keyword scope to some keywords

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#120363]
This issue is related to #108254 .  Can we have keyword scope too? Something like this:

```json
{
    "comment": "struct declarations",
    "match": "\\b(struct)\\s+([A-Z][A-Za-z0-9]*)\\b",
    "captures": {
        "1": {
            "name": "keyword.declaration.struct.rust storage.type.rust"
        },
        "2": {
            "name": "entity.name.type.struct.rust"
        }
    }
}
```
which results in:

![image](https://user-images.githubusercontent.com/5412540/113331136-cc4b4700-9334-11eb-8f5e-88b8337a9b13.png)

I used the scope from [https://www.sublimetext.com/docs/3/scope_naming.html#storage](url).

**Comment by alexr00** [comment]
Moved to the upstream repo: https://github.com/dustypomerleau/rust-syntax/issues/16
