### ISSUE TITLE
Cannot open split json settings editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#120343]
Enable split json editor using setting `"workbench.settings.useSplitJSON": true` and open settings file and following error is shown

```
Unable to open 'User Settings': Cannot read property 'textEditorModel' of undefined.
```

**Comment by sandy081** [comment]
@bpasero It seems this df6d78a1695bdf9a1d4984231242ff1fd65247bb broke this, but I would say its not your fault as it was not properly typed - Fixed it.

**Comment by bpasero** [comment]
@sandy081 thanks, we had https://github.com/microsoft/vscode/issues/120301#issuecomment-811662870 already opened and I noticed the excessive `any` usage in that code. 

There is still a few `<any>` in that file, I do not think we should have explicit `any` in our code. Filed: https://github.com/microsoft/vscode/issues/120545
