### ISSUE TITLE
Typo - "Check for Extensions Updates" Not "Check for Extension Updates"

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120360]
- VS Code Version: 1.55.0
- OS Version: Windows 10 20H2 Build 19042.572

Steps to Reproduce:

It's typo issue. It should be "Check for **Extensions** Updates" Not "Check for **Extension** Updates".

![image](https://user-images.githubusercontent.com/17777237/113327651-7f0eab80-931b-11eb-908e-c32766371cbd.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
@gregvanl your opinion please.

**Comment by gregvanl** [comment]
Hi @pixieaka Thank you for your interest in VS Code and taking the time to enter an issue.
The current text is fine and reads easier. The thing VS Code is checking for is an "extension update" and the plural should be "extension updates".
