### ISSUE TITLE
yarn create react-app --template typescript

### ISSUE THREAD

**Issue by nzoLogic** [microsoft/vscode#120346]
Issue Type: <b>Bug</b>

Run the following:
yarn create react-app my-app --template typescript
cd my-app && code .
yarn start

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 5, 3|
|Memory (System)|8.00GB (0.29GB free)|
|Process Argv|. --crash-reporter-id 53fb6d80-29bd-403b-9a80-16ff066e8cb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.1
vscode-eslint|dba|2.1.19
auto-close-tag|for|0.5.10
graphql-for-vscode|kum|1.15.3
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontbcf:30265426
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify what problem is and how it's related to VS Code editor itself.
