### ISSUE TITLE
Broke icon on MacOS (socondary monitors only)

### ISSUE THREAD

**Issue by tobiaswaelde** [microsoft/vscode#120387]
- VS Code Version: 1.55.0
- OS Version: Big Sur 11.2.3

Steps to Reproduce:

1.  View Icon anywhere on built in screen -> No issue
2. View icon on any other connected screen -> Icon broke

|Mac display|Secondary displays|
|---|---|
|<img width="792" alt="Screen Shot 2021-04-02 at 00 17 33" src="https://user-images.githubusercontent.com/31882463/113458332-43a2d880-9412-11eb-984c-7f78e91248ab.png">|![Screen Shot 2021-04-02 at 00 17 15](https://user-images.githubusercontent.com/31882463/113458385-5e754d00-9412-11eb-82d3-ba4f4f0d180f.png)|
|<img width="1054" alt="Screen Shot 2021-04-02 at 00 16 00" src="https://user-images.githubusercontent.com/31882463/113458457-9aa8ad80-9412-11eb-8ced-f5ca99926cba.png">|![Screen Shot 2021-04-02 at 00 16 13](https://user-images.githubusercontent.com/31882463/113458452-97152680-9412-11eb-88b7-829d7c8467ad.png)|

The issue occured first after an update of VS Code Insiders and now after the last update of VS Code.

I am using a MacBook Pro 2019. The issue occurs on every connected screen (testet with Dell DisplayLink and without).

Does this issue occur when all extensions are disabled?: Not testet

**Comment by SeeringPhil** [comment]
Was just about to come and create the same issue! 

VS Code Version 1.55.0 & macOS Big Sur 11.2.3 as well, macbook pro 2017

**Comment by ddzy** [comment]
Same issue

**Comment by SuvinLin** [comment]
Same issue!
VS Code Version 1.55.0 & macOS Mojave 10.14.6 as well.

**Comment by twentyonedot** [comment]
Same issue!
VSCode - Version: 1.55.0 (Universal)
Macos - Version: BigSur 11.2.3 (20D91)
MacBook pro 13in (2017)
But issue is happening on both the screens, monitor and mac book screen

**Comment by EasonRen** [comment]
Same issue!
VSCode - Version: 1.55.0 (Universal)
Macos - Version: BigSur 11.2.3 (20D91)
Mac mini (2018)

**Comment by widersky** [comment]
Having the same issue on 11.2.3 in Launchpad Folder and Spotlight. VSCode v 1.55 on Mac Mini 2020

**Comment by nuruddinsyah** [comment]
Same issue on me. I use macOS Sierra 10.12.4. Issue appers on built-in screen.

![Screen Shot 2021-04-02 at 11 22 18 PM](https://user-images.githubusercontent.com/29025381/113433937-4d284280-940a-11eb-8e94-2535bb976b47.png)
