### ISSUE TITLE
PHP Comment Tags for HTML Content

### ISSUE THREAD

**Issue by yourbudweiser** [Microsoft/vscode#12037]
- VSCode Version: 1.5.2
- OS Version: Windows 8.1Pro

Steps to Reproduce:
1. Highlight HTML code on a .php page
2. Press Control+K, Control+C
3. VS Code inserts PHP comment tags instead of HTML comment tags

`// <h1>This is a PHP comment</h1>`
`<!-- <h1>This is an HTML comment</h1> -->`

**Comment by yourbudweiser** [comment]
Any chance this will get addressed?

**Comment by mjbvz** [comment]
I'm unable to repo this in VSCode 1.7+

![nov-18-2016 16-08-45](https://cloud.githubusercontent.com/assets/12821956/20450939/3b3db7ae-ada9-11e6-96f6-a5b3b8ee9d44.gif)

Can you please give this a try again and let me know if you still see this issue. Thanks.
