### ISSUE TITLE
100% CPU usage on Mac when update is available

### ISSUE THREAD

**Issue by RMeli** [microsoft/vscode#120361]
- VS Code Version: 1.55.0
- OS Version: macOS 10.15.7

Every time there is a new VSCode update (edit: at least the latest ones), the following window opens:

![Screenshot 2021-03-31 at 21 37 37](https://user-images.githubusercontent.com/11348981/113328071-0d832d00-931c-11eb-8772-956513b1ed5c.png)

This causes 100% CPU usage 

![Screenshot 2021-03-31 at 21 38 25](https://user-images.githubusercontent.com/11348981/113328134-225fc080-931c-11eb-88be-e5e2aba0686b.png)

and therefore the fans start spinning like crazy after a while.

This has been happening for a few releases now. I'm at the point where I know there is an update for VSCode if I'm not at my screen because the fans start spinning.

Looks like the number of threads is way off?

Does this issue occur when all extensions are disabled?: Can't reproduce.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/95534

Please ensure the permissions of the application as mentioned in the above issue https://github.com/microsoft/vscode/issues/95534#issuecomment-620132855
