### ISSUE TITLE
ExtensionManagementCLIService.installExtensions does not respect isMachineScoped for vsix URIs

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#120340]
Probably for `file` scheme it can always be `false`, but for other should be respected?

**Comment by sandy081** [comment]
I think right solution is that vsix install shall also respect the passed `--do-not-sync` flags

**Comment by connor4312** [comment]
@sandy081 can you add steps here?

**Comment by sandy081** [comment]
To verify:

- Install an extension from CLI using `--do-not-sync` flag. Eg: `code-insiders --install-extension pub.name --do-not-sync`
- Make sure this extension is not synced - Verify that in extensions view this extension is marked as not synced.
