### ISSUE TITLE
vscode cannot fold xml file correctly for special multi-lines element

### ISSUE THREAD

**Issue by bz-wow** [microsoft/vscode#120309]
Issue Type: <b>Bug</b>

vscode doesn't fold the following xml correctly:

&lt;div&gt;
  &lt;p&gt;line1
line2
  &lt;/p&gt;
&lt;/div&gt;

The above 'p' element has 2 lines, **the 2nd line doesn't have space before the content**. When fold the 'div' element, vscode shows incorrectly.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.80GB (4.39GB free)|
|Process Argv|. --crash-reporter-id bbbf0b3b-5669-43ef-a693-95e933c433fd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
githd|hui|2.2.4
csharp|ms-|1.23.9
uuid-generator|net|0.0.4
vscode-nuget-gallery|pat|0.0.24

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833:30267464
vshan820:30276952

```

</details>

**Comment by aeschli** [comment]
The built-in basic XML language support only supports indentation-based folding. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To get language aware folding, install a XML extension like https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml
