### ISSUE TITLE
JSX self-closing style should use XHTML by default, not XML

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#120356]
In a JSX file, expand `MyComponent/`. The result should be `<MyComponent />`, not `<MyComponent/>`.

CC @pixieaka

**Comment by pixieaka** [comment]
@rzhao271 I'm on 5500358 in new `index.html` for example inside header
`link:css` expanded to `<link rel="stylesheet" href="style.css">` not to `<link rel="stylesheet" href="style.css" />`
`meta/` expanded to `<meta>` not to `<meta />`
And inside body also `option/` expanded to `<option>` not to `<option />`
