### ISSUE TITLE
Option to disable only the "U" "M" on tab title of git extension

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#120308]
Currently the option Git->Decorations enables/disables the tab title and explorer color altogether. Is there a way to disable only the "U" and "M" on tab titles? This is annoying after latest vscode update. It is a waste of space and "U"gly "M"ess. Previous version only changes color , which is well enough.

**Comment by gjsjohnmurray** [comment]
Did you try the `workbench.editor.decorations.badges` setting that the release notes mention?

**Comment by xgdgsc** [comment]
Thanks. This one works.

**Comment by gjsjohnmurray** [comment]
:+1: please close the issue.
