### ISSUE TITLE
Microsoft repository no longer signed?

### ISSUE THREAD

**Issue by fbnlsr** [microsoft/vscode#120383]
- VS Code Version: 1.54.3
- OS Version: Pop!_OS 20.10

I tried running `sudo apt update` in order to get the latest version of VS Code and got a message saying that the repository is no longer signed.

Steps to Reproduce:

1. run `sudo apt update`
2. get this message:

```
Err:8 http://packages.microsoft.com/repos/code stable InRelease
  403  Forbidden [IP: 212.95.74.75 80]
Reading package lists... Done            
E: Failed to fetch http://packages.microsoft.com/repos/code/dists/stable/InRelease  403  Forbidden [IP: 212.95.74.75 80]
E: The repository 'http://packages.microsoft.com/repos/code stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Yzrsah** [comment]
All updates are failing at the moment.

**Comment by connor4312** [comment]
Likely related to the current Azure outage https://status.azure.com/en-us/status

**Comment by fbnlsr** [comment]
Looks like your're right. I'm now able to run `sudo apt update` but VS Code does not seem to be upgradeable anymore. Maybe I need to wait for the release to be pushed again on the repo?

**Comment by chrmarti** [comment]
Just checked and I get the latest version (1.55.0). Could you try again and let us know if the problem persists?

**Comment by fbnlsr** [comment]
@chrmarti the problem is still here for me. Is there something I could do to force the update? I do get the update notification inside VS Code but there's nothing when I run `sudo apt update`. Or maybe it has something to do with Pop!_OS' repository?

**Comment by chrmarti** [comment]
What's the latest version you see with `sudo apt show -a code | less`?

**Comment by fbnlsr** [comment]
This is an excerpt of the result:

```
Package: code
Version: 1.55.0-1617120720
Priority: optional
Section: devel
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Installed-Size: 278 MB
Provides: visual-studio-code
Depends: libnss3 (>= 2:3.26), gnupg, apt, libxkbfile1, libsecret-1-0, libgtk-3-0 (>= 3.10.0), libxss1, libgbm1
Conflicts: visual-studio-code
Replaces: visual-studio-code
Homepage: https://code.visualstudio.com/
Download-Size: 71.0 MB
APT-Sources: http://packages.microsoft.com/repos/code stable/main amd64 Packages
Description: Code editing. Redefined.
 Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for 
the core edit-build-debug cycle. See https://code.visualstudio.com/docs/setup/linux for installation instructions and FA
Q.

Package: code
Version: 1.54.3-1615854707~pop1~1616051153~20.10~137c820
Priority: optional
Section: editors
Maintainer: Michael Aaron Murphy <michael@system76.com>
Installed-Size: 281 MB
Download-Size: 71.9 MB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
Description: Microsoft Visual Studio Code
```

Something seems odd, no?

**Comment by generalredneck** [comment]
I'm not getting an unsigned error, but my vscode version is definitely not upgrading... it appears that I'm stuck on the version that popos released. Trying to install the .deb from the vscode website asks me if I want to downgrade.

![Screenshot from 2021-04-07 09-36-58](https://user-images.githubusercontent.com/526491/113884832-ee095b80-9784-11eb-8fe5-b0e9badbbb84.png)

```
Package: code
Version: 1.55.0-1617120720
Priority: optional
Section: devel
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Installed-Size: 278 MB
Provides: visual-studio-code
Depends: libnss3 (>= 2:3.26), gnupg, apt, libxkbfile1, libsecret-1-0, libgtk-3-0
 (>= 3.10.0), libxss1, libgbm1
Conflicts: visual-studio-code
Replaces: visual-studio-code
Homepage: https://code.visualstudio.com/
Download-Size: 71.0 MB
APT-Sources: http://packages.microsoft.com/repos/code stable/main amd64 Packages
Description: Code editing. Redefined.
 Visual Studio Code is a new choice of tool that combines the simplicity of a co
de editor with what developers need for the core edit-build-debug cycle. See htt
ps://code.visualstudio.com/docs/setup/linux for installation instructions and FA
Q.

Package: code
Version: 1.54.3-1615854707~pop1~1616051153~20.04~137c820
Priority: optional
Section: editors
Maintainer: Michael Aaron Murphy <michael@system76.com>
Installed-Size: 281 MB
Download-Size: 71.9 MB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packa
ges
Description: Microsoft Visual Studio Code
```

This may be something we need to take to pop-os support.

**Comment by chrmarti** [comment]
Does 1.55.0 list any dependencies that are not available from the apt sources? It looks like 1.54.3 is packaged by pop-os, so maybe they will soon do the same for 1.55.0?

**Comment by generalredneck** [comment]
Something I noticed about both @fbnlsr and my output is that the Apt-Manual-Installed flag is set to yes. I personally don't know how it got there...

As a work around for now. I ran `sudo apt install code=1.55.0-1617120720` and then set the package to auto install with `sudo apt-mark auto code`. all went well... :man_shrugging: 

We will see if I upgrade the next version when ever it comes out...

**Comment by fbnlsr** [comment]
> Something I noticed about both @fbnlsr and my output is that the Apt-Manual-Installed flag is set to yes. I personally don't know how it got there...

Well I did try and installed it manually at some point because I encountered the bug where the executable `code` was not found on my machine. I distinctly remember uninstalling / reinstalling from PopShop to solve this issue though.

> Does 1.55.0 list any dependencies that are not available from the apt sources?

Is there a way to know this?

**Comment by chrmarti** [comment]
> > Does 1.55.0 list any dependencies that are not available from the apt sources?
> 
> Is there a way to know this?

@generalredneck 's success with installing a specific version suggests that all dependencies are available. Have you tried running that same apt command?

**Comment by generalredneck** [comment]
> Well I did try and installed it manually at some point because I encountered the bug where the executable code was not found on my machine. I distinctly remember uninstalling / reinstalling from PopShop to solve this issue though.

Correct... any time you do an `sudo apt install` or use the shop to install something from an apt repository, it marks is as manually installed. That said, give `sudo apt install code=1.55.0-1617120720` a try... as for the dependencies... if you check the output of `sudo apt show -a code`, you will see the dependencies there. Specifically, the popos version has none. Yet another way to see the dependencies are with `sudo apt-cache depends`

See the output below for me:

```
$ sudo apt-cache depends code=1.55.0-1617120720
code
  Depends: libnss3
  Depends: gnupg
  Depends: apt
  Depends: libxkbfile1
  Depends: libsecret-1-0
  Depends: libgtk-3-0
  Depends: libxss1
  Depends: libgbm1
  Conflicts: <visual-studio-code>
  Replaces: <visual-studio-code>
    code
$ sudo apt-cache depends code=1.54.3-1615854707~pop1~1616051153~20.04~137c820
code
```

**Comment by fbnlsr** [comment]
OK so if I understand correctly, by specifying the version I wish to install, `apt` will download it from Microsoft's repository, right?

OR it could "fix itself" whenever PopOS decides to update the package on their official repository, right again?

Can't I just tell the OS to always use Microsoft's repository for this app? Also, isn't it a bit counterintuitive that VS Code tells me there's an update waiting where I just can't update it?

I'm sorry if this has derailed the original issue I've opened, also I'm aware this might be a PopOS thing. I'm just trying to understand the mechanics behind all this.

**Comment by chrmarti** [comment]
VS Code checks Microsoft's update server for VS Code for new versions. So currently the update indicator is not aware of your apt sources.

**Comment by fbnlsr** [comment]
Closing this issue as it's more a Pop!_OS problem than anything. Besides, v1.55.3 was just released and the repo was finally updated, so I was able to update through `apt`.

Thanks everyone for your contribution !
