### ISSUE TITLE
Bot: output format of duplication detection bot can be improved

### ISSUE THREAD

**Issue by yume-chan** [microsoft/vscode#120327]
On GitHub Web, hovering over an issue number will bring up a popup containing:

* State (open vs closed)
* Summary
* Labels

![image](https://user-images.githubusercontent.com/1330321/113271982-b4140180-930d-11eb-8e56-33b7da35c20e.png)

----

However, hovering on links in duplication detection bot's comment does nothing.

![image](https://user-images.githubusercontent.com/1330321/113272161-ec1b4480-930d-11eb-96e1-a2c650beff1d.png)

----

So maybe the bot should print like:

```
* #XXXXX: ISSUE TITLE
```

So we can quickly get more information without clicking each one.

**Comment by chrmarti** [comment]
The problem with making these fully functional links would be that they establish backlinks from the linked issues. Closing as I haven't found any other way to avoid the backlinking.
