### ISSUE TITLE
Notebook performance improvements for April

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#120384]
- [ ] Keep view model on webview side  (https://github.com/microsoft/vscode/issues/119582)
     - needs to acknowledge height 
   
- [x] Warmup viewport for all cells 
    - Preload outputs like we already do for the markdown cells

- [X] Adjusting the structure so that the container uses `top` while outputs are relative position  @mjbvz

**Comment by rebornix** [comment]
A bit more details of why/how:

> Keep view model on webview side

Currently we store all the layout info in main frame, and we send `scrollTop` position update requests to the webview whenever there is a layout change, even if the layout change is coming from the webview. For example, say we have a code cell with one output in the webview, followed by a markdown cell. 

1. When the output height increases, it sends a `dimension` update event to main frame
2. In main frame, we will adjust the `top` position of the markdown cell (view model info), which will send a `scrollTop` adjustment request for the markdown cell 
3. The webview receives the event, and the change the `top` of the markdown cell

Though the latency between main frame and webview is low, it can still be tens of milliseconds between step 1 and 3, then the outputs and webview overlap with each other: https://github.com/microsoft/vscode/issues/119582.

One idea we have is we keep a copy of layout info in the webview, and update them first when output or markdown layout changes, the workflow will be

1. Output height increases, update the markdown cell `top` property immediately, and send a `dimension` update event to main frame
2. In main frame, update the `top` position of the markdown cell in view model, invalidate the cache of markdown/output, send an acknowledge message to the webview, which contains the offset of cells affected
3. The webview receives the message, update the `top` property of each cell affected again. Ideally, this update is effortless as the `top` position doesn't change at all

**Comment by mjbvz** [comment]
Pushed changes to the notebook dom structure. This include:

- Flattening the structure of markdown cells
- Use relative offsets for output cells

**Comment by rebornix** [comment]
@mjbvz discussed another approach to avoid outputs overlapping with markdown cells and code cells in a split second:

* Output rendered, size grow. Broadcast the height to UI but set `maxHeight: 0; overflow: hidden` on its container. Thus the outputs are not overlapping with any cell
* UI receives the event, adjust offset of code cells
* UI sends events to the webview to adjust the offsets of markdown cells
* UI sends an `ack` event to the webview
* Webview receives `ack`, reset `maxHeight` of the output container, the output will then become visible.



A comparison of OSS with this experiment and Insiders

**Video**


https://user-images.githubusercontent.com/876920/114227064-55f8a700-9929-11eb-983e-d00fdf1d8802.mov


**Insiders** (right)

When the output is rendered, it will overlap with code cells
<img width="1774" alt="image" src="https://user-images.githubusercontent.com/876920/114227027-48432180-9929-11eb-98df-057f0b2eb0ea.png">


And in next tick, code cells are pushed down, but markdown cells are not yet

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/876920/114227015-40837d00-9929-11eb-96b1-34c1e1c8c74a.png">


**OSS** (left)

We pushed down code cells first

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/876920/114226970-33668e00-9929-11eb-9326-2ad2c82e71f2.png">


and then next tick 

<img width="1774" alt="image" src="https://user-images.githubusercontent.com/876920/114226881-13cf6580-9929-11eb-9846-1800b2aef148.png">

**Comment by rebornix** [comment]
The above experiment is now in main https://github.com/microsoft/vscode/commit/d3394d21773bfdd4ab30f8e408b9a25ecccd3c13 .

**Comment by mjbvz** [comment]
@rebornix Anything left on this issue? I believe we agreed that moving the view model to the webview may be unnecessary after you most recent changes

**Comment by mjbvz** [comment]
Closing this since I think we've handled the cases we originally discussed
