### ISSUE TITLE
Allow dedicated activity button for Terminal/Output/etc. frame

### ISSUE THREAD

**Issue by nvaranki** [microsoft/vscode#120386]
I use ESP-IDF toolkit and found that I frequently need to open-close bottom frame where Terminal/Output/etc. reside, mostly for the Terminal. There's Ctrl-J shortcut for this purpose. However, I think one more button on Activity bar could help a lot, because it allows to use one click mouse operation. The bar has a lof of free space. I've marked possible location on attached snapshot.
Thanks
![abar-term-2](https://user-images.githubusercontent.com/23263557/113359375-505ef800-9350-11eb-8c5e-9e470fa0fe1c.png)

**Comment by sbatten** [comment]
@nvaranki I think the status bar would be a better UX fit for this which you can do via an extension. It looks like this does this https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar already
