### ISSUE TITLE
WSL distros wrongly detected in locales other than English after 1.55.0

### ISSUE THREAD

**Issue by DervishD** [microsoft/vscode#120321]
- VS Code Version: 1.55.0
- OS Version: Windows 10 Home 20H2 19042.867

Steps to Reproduce:

1. Just run latest version of VS Code, 1.55.0
2. Show the list of default WSL profiles and you will find something like "Ubuntu (predet.)" instead of just "Ubuntu".
3. The profile is impossible to launch, because there is NO distro named "Ubuntu (predet.)".

This happens because src/vs/workbench/contrib/terminal/node/terminalProfiles.ts, at line 178 of latest snapshot I'm checking, does this:  `distroName = distroName.replace(/ \(Default\)$/, '');`. It should remove other locales, too. I know this is difficult to do because... well, there's plenty of locales. So, in order to get the distribution name, another way should be used. I think it's safe to remove any last element within parentheses from the distro name as returned by `wsl -l`, but really another method is available which I think it's safer, but I'm not sure how to write it in TypeScript.

I have the following code already written in Python, for a system maintenance script I use in my own system, where I retrieve the installed distribution names from the registry:
```
    lxss_key = r'Software\Microsoft\Windows\CurrentVersion\Lxss'
    distros = set()
    with ConnectRegistry(None, win32con.HKEY_CURRENT_USER) as registry_handler:
        with OpenKeyEx(registry_handler, lxss_key, 0, win32con.KEY_READ) as key:
            for i in range(QueryInfoKey(key)[0]):
                subkey_name = EnumKey(key, i)
                with OpenKeyEx(key, subkey_name) as subkey:
                    try:
                        distros.add(QueryValueEx(subkey, 'DistributionName')[0])
                    except FileNotFoundError:
                        pass
```

It's a partial code but well, I think it's self explanatory, and I can provide further information if needed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by tonibofarull** [comment]
Same happens to me with the new version 1.55.0

**Comment by mpasteur** [comment]
hi,
at first glance it looks that adding a -q argument to the 'wsl -l' command would be safe...

```
❯ wsl -l
Distributions du sous-système Windows pour Linux :
Ubuntu-18.04 (par défaut)
docker-desktop-data
docker-desktop
```

```
❯ wsl -l -q
Ubuntu-18.04
docker-desktop-data
docker-desktop
```

regards

**Comment by DervishD** [comment]
Thanks for the suggestion and the fix.

Still, I'll keep an eye on this, just in case Microsoft decides to change `wsl` command line interface. But so far, so good, and it's simpler than having to read the registry 👍🏼

**Comment by strarsis** [comment]
Just encountered this issue today (after updating Docker for Desktop, but not sure if this has something to do with the issue).

**Comment by Tyriar** [comment]
Verified in https://github.com/microsoft/vscode/pull/120382#issuecomment-816669204
