### ISSUE TITLE
Make inactive tab title color look different from active tab when decorations are visible

### ISSUE THREAD

**Issue by fernandopsilveira** [microsoft/vscode#120345]
Now that lint errors are reflected on tab title foreground color, it's much more harder to me to find the active tab, since inactive tabs title foreground color do not get darkened.

Please, make inactive tab title color look different when it reflects lint status.

**Comment by ArturoDent** [comment]
I think you are referring to https://code.visualstudio.com/updates/v1_55#_tab-decorations-on-by-default

It is the git status.  You can disable those if you want.

**Comment by fernandopsilveira** [comment]
Nope. I was talking about linting status, not git status, but anyway...
I don't want to disable it, I'm suggesting an improvement

**Comment by bpasero** [comment]
@fernandopsilveira to clarify, you refer to the tab color for when an error or warning is present in the file of a tab? Can you post a screenshot of where you find it hard to distinguish inactive from active tab then?

**Comment by fernandopsilveira** [comment]
Without tab decorations (easy to find active tab)
![001](https://user-images.githubusercontent.com/1727562/113516639-bd8dab80-9551-11eb-90cc-fff07789afba.png)

With tab decorations (not so easy to find active tab, since there's no color difference)
![002](https://user-images.githubusercontent.com/1727562/113516638-bcf51500-9551-11eb-8bbd-0f80f296c038.png)

**Comment by dancherb** [comment]
`lint errors are reflected on tab title foreground color`

How can we disable or customise this behaviour completely? It's really obstructive in some cases.

![tab active error foreground](https://user-images.githubusercontent.com/32280121/113708736-f03bcd80-9724-11eb-828e-c8564e801730.png)

**Comment by fernandopsilveira** [comment]
@dancherb, you can easily disable editor decorations on VSCode settings:

![image](https://user-images.githubusercontent.com/1727562/113711787-c26e6e80-96bb-11eb-9994-d90e9f78437a.png)


> 
> `lint errors are reflected on tab title foreground color`
> 
> How can we disable or customise this behaviour completely? It's really obstructive in some cases, particularly depending on theme.
> 
> ![tab active error foreground](https://user-images.githubusercontent.com/32280121/113708736-f03bcd80-9724-11eb-828e-c8564e801730.png)

**Comment by bpasero** [comment]
I think this needs a similar fix as was done with https://github.com/microsoft/vscode/issues/43179 where colors for list decorations were introduced.
