### ISSUE TITLE
VS Code rollback does not preserve update mode setting

### ISSUE THREAD

**Issue by olderor** [microsoft/vscode#120377]
As the recent update (1.55.0) broke some functionality for me, I'm trying to rollback to 1.54.3. However, the VS Code keeps updating to the latest 1.55.0 even though the updates setting is set to none.

- VS Code Version: 1.54.3, 1.55.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Install VS Code 1.54.3, get an update to 1.55.0, and install it.
2. Close VS Code 1.55.0, install an older version (1.54.3 in my case https://code.visualstudio.com/updates/v1_54).
3. Open VS Code 1.54.3, go to User Settings, search for 'update'.
4. Set update mode to none instead of the default (disables all updates as per description).
![image](https://user-images.githubusercontent.com/11135046/113350982-127db780-92ef-11eb-955a-0e48e1011824.png)

5. Save and restart VS Code.
6. Done. Observe the VS Code is updated from 1.54.3 to 1.55.0, a release notes page appears even though the update mode is set to none.
7. Go to user settings, observe the update mode is set to none, but VS Code was still updated. You can also repeat steps 2-5 and observe the same.

Expected behavior:
After setting update mode to none and restarting VS Code, the app should prevent itself from installing any updates and keep the version that was used in the previous launch.

**Comment by joaomoreno** [comment]
Does this happen if you change the `update.mode` before you roll back to 1.54.3?

**Comment by olderor** [comment]
@joaomoreno same thing. If you set update mode to none in 1.55.0, close vs code 1.55.0, install 1.54.3, open vs code 1.54.3, close vs code 1.54.3, open vs code again, observe the vs code is updated to 1.55.0.

You can repeat the steps multiple times, the result will be the same, vs code will update itself to 1.55.0.

My guess that there is some automated process that is able to find the already downloaded update, and it just installs the update regardless of the new update setting. Probably if you delete the cached update, maybe the update won't be downloaded because of the setting, but idk how to do it and it's not obvious. I believe the whole update process must be controlled by the setting, and even if the update was cached, it should not be applied with the new launch if the setting is set to none.

P.S. It doesn't really matter in which version you set update mode to none in old or new, as it's not guaranteed that you can do it, e.g. if a new version of vs code has a critical issue and crashes, you won't be able to set update mode to none, you can only rollback to old working version and update it there.

**Comment by joaomoreno** [comment]
Is this the user setup or the system setup?
