### ISSUE TITLE
TypeScript `this` Type Information Dosen't Surface Properly in Editor

### ISSUE THREAD

**Issue by thoughtentity** [Microsoft/vscode#12032]
### Environment Information

* VS Code Version: 1.6.0-insiders (f31a4)
* OS Version: Windows 10 1607 (Build 14393.105)
* TypeScript Version: 2.0.2 (Release Candidate)

### Problem

In TypeScript 2.0, the shape of `this` for functions can be described using [type annotations](https://github.com/Microsoft/TypeScript/pull/6739). However, the VS Code TypeScript editor does not properly surface this information. The `this` variable in the function gets typed as `any` within the function but the editor still enforces that use of `this` in the function conform to the type information used to describe `this` for the function. This results in the odd issue of the editor not providing any intellisense for the `this` due to it being typed as `any` but still expects it conform to the shape of `this` described by the `this` type annotation for the function.

![image](https://cloud.githubusercontent.com/assets/208549/18518597/7bc87732-7a55-11e6-8cc4-731fb5d86e11.png)

### Reproduction

The following minimum TypeScript file will reproduce the issue in VS Code.

> index.ts

```typescript
type ctxA = {
    funB: (paramA: string) => void
}

interface TestObj {

    propA: {
        funA: (this: ctxA) => void
    }

}

let objA: TestObj = {

    propA: {
        funA: function() {
            // errors since funB dosen't match the signature (missing paramA) of funB in ctxA even though the editor types it as any
            this.funB();
        }
    }

}
```

### Expected Result

The VS Code TypeScript editor should properly surface the type information for `this` in functions and not just type it as `any` to provide proper intellisense.

**Comment by waderyan** [comment]
@thoughtentity thank you for the excellent bug report. One of the best explained and demonstrated I have ever seen 👍. I have reproduced. As this issue is a TypeScript language service issue I will migrate to their repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10937
