### ISSUE TITLE
Split view location shifts with side bar visibility

### ISSUE THREAD

**Issue by steveoh** [microsoft/vscode#120372]
The split view location shifts with side bar visibility. This is jarring to me as all of my content shifts. A better UX would not move the window split location and let the sidebar take up the space it wants from the open window.

```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

Steps to Reproduce:

1. Split windows to have a side by side view
2. open the side bar (left or right side doesn't matter)
3. adjust the split window line
4. hide the side bar
5. notice the split bar location shifts

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
This is intentional as we maintain the proportions of the split editors when toggling the side bar.

**Comment by sbatten** [comment]
cc @bpasero
