### ISSUE TITLE
Integrated Terminal does not show first line when switched into focus

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12038]
- VSCode Version: 1.6.0 Insider
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. Download and open https://github.com/Microsoft/vscode-extension-samples
2. Run the terminal sample

![terminal](https://cloud.githubusercontent.com/assets/4033249/18523809/b7f88dae-7a6a-11e6-9046-fa093ce43c32.gif)

**Comment by Tyriar** [comment]
That change didn't actually fix this one, must be to do with the font height not being calculated or a rounding error.

**Comment by Tyriar** [comment]
`.xterm-rows` is not being correctly aligned to the bottom. When the viewport is filled it gets aligned correctly though.

**Comment by Tyriar** [comment]
`.xterm-rows` is not positioned correctly because `.terminal-outer-container` is not being layed out correctly. It seems to be put in the wrong spot when a new terminal is created.

**Comment by Tyriar** [comment]
The layout breakage seems to be related to focus.

**Comment by Tyriar** [comment]
This is still happening in Insiders on Mac.

**Comment by Tyriar** [comment]
Somehow attaching xterm.js to the DOM will shift `.terminal-outer-container` (the parent of the parent of the parent of the xterm.js element) ~20px up. A forced refresh (resizing the window) will fix the problem.

**Comment by Tyriar** [comment]
Setting `width: 100%` to all elements form `.terminal-outer-container` to `.xterm-rows` does not change fix the issue so it doesn't appear to be anything to do with the `&nbsp;` characters wrapping or something like that.

**Comment by Tyriar** [comment]
Seems to be related to xterm.js' hidden `textarea` when it's focused. The bug reproduces only when the terminal has focus, it goes away if I set the `textarea` to `display: none`.

**Comment by Tyriar** [comment]
Adding `top:-9999em` to .xterm-helpers` also fixes it.

**Comment by Tyriar** [comment]
IME behavior is quite broken before and after this change, it's related to the underlying issue though.

**Comment by Tyriar** [comment]
Cherry picked to release/1.6 after testing and checking with @kieferrm & @chrmarti

**Comment by chrmarti** [comment]
Marking verified after testing on all 3 platforms.
