### ISSUE TITLE
The "Follow link" link when hovering over href linking to local files doesn't work

### ISSUE THREAD

**Issue by Zenoo** [microsoft/vscode#120341]
Issue Type: <b>Bug</b>

Create a `<link>` tag with an `href` linking to a local file

Should look like this:  
![](https://i.imgur.com/VXJOoJW.png)

Instead it looks like this:
![](https://i.imgur.com/yeJGzmz.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|23.89GB (14.85GB free)|
|Process Argv|--folder-uri file:///d%3A/Sostag/Clients/Self%20Stockage%20Mobile/self-stockage-mobile.com --crash-reporter-id 2761c1f9-2c67-4cf4-9ede-665af1e547c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
markdown-preview-github-styles|bie|0.1.6
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
php-intellisense|fel|2.3.14
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.25.0
Scala|itr|0.1.7
fontawesome-autocomplete|Jan|1.1.2
code-beautifier|mic|2.3.3
easy-less|mrc|1.7.2
vscode-apache|mrm|1.2.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.9.0
color-highlight|nau|2.3.0
indent-rainbow|ode|7.5.0
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.6.0
java|red|0.76.0
bbcode|ric|0.0.2
code-stats-vscode|riu|1.0.18
comment-ts|sal|1.0.21
code-settings-sync|Sha|3.4.3
java-generate-setters-getters|soh|7.0.2
tabnine-vscode|Tab|3.2.16
es6-string-html|Tob|2.2.0
lorem-ipsum|Tyr|1.2.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-pack|vsc|0.13.0
vscode-playframework-syntax|lan|0.0.1
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30265425
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by peter-fb** [comment]
Can confirm, it's also the same with Markdown images:

![2021-04-09 09_46_17_markdown_image](https://user-images.githubusercontent.com/7101417/114147104-a3204d00-9918-11eb-8a76-ae48f6b3d209.png)

**Comment by contradictionary** [comment]
this kind of link also does not work, even though the file is there in the local path 
`<script type="text/javascript" src="js/Index/main.js?V=2.2"></script>`

**Comment by rebornix** [comment]
Verifier: please test a local file link with space in file path.

**Comment by rchiodo** [comment]
/verified:

![image](https://user-images.githubusercontent.com/19672699/135359506-b7c1f4ca-91aa-47f5-b264-6cb15be12c16.png)

works
