### ISSUE TITLE
Jumping symbols in tab

### ISSUE THREAD

**Issue by iSpid3r** [microsoft/vscode#120319]
Issue Type: <b>Bug</b>

Line it up, please.

https://i.ibb.co/VLP8Ktr/01-04-2021-11-34-29.png

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

**Comment by jrieken** [comment]
<img width="563" alt="Screenshot 2021-04-06 at 09 02 33" src="https://user-images.githubusercontent.com/1794099/113671631-ea0f0800-96b6-11eb-9665-7b02e97e24df.png">

Please provide more information

**Comment by iSpid3r** [comment]
> Please provide more information

![Group 1](https://user-images.githubusercontent.com/20419104/113675044-98b94580-96c3-11eb-9148-dfbb34ba72ec.jpg)

![06-04-2021 10-34-59](https://user-images.githubusercontent.com/20419104/113675174-c0101280-96c3-11eb-9648-ed519c893cac.png)

**Comment by bpasero** [comment]
I had filed something similar in https://github.com/microsoft/vscode/issues/113223.

**Comment by jrieken** [comment]
@iSpid3r please check #113223, esp do you use a non default zoom level?

**Comment by iSpid3r** [comment]
Checked. Default zoom level. Sybmols still jumping...
