### ISSUE TITLE
Support configuring environment via terminal profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120366]
Suggested in https://github.com/microsoft/vscode/issues/45444#issuecomment-812012094

**Comment by pszlazak** [comment]
Using [Terminal profiles](https://code.visualstudio.com/updates/v1_55#_terminal-profiles) (introduced via #45444) I managed to prepare dedicated env for terminals in following way:
* general VS Code config:
```
    "terminal.integrated.env.linux": {
        "ENVIROMENT": "test"
    },
    "terminal.integrated.profiles.linux": {
        "bash - production": {
            "path": "bash",
            "args": [
                "--rcfile",
                "~/bashrc-prod"
            ],
            "overrideName": true
        },
        "bash - dev": {
            "path": "bash",
            "args": [
                "--rcfile",
                "~/bashrc-dev"
            ],
            "overrideName": true
        },
    },
```
where [`terminal.integrated.env.linux`](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuring-working-directory-or-environment) sets common variable(s) for all Linux terminals
* content of `~/bashrc-prod`:
```
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

TYPE=prod
```
* content of `~/bashrc-dev`:
```
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

TYPE=dev
```

In my `bash - production` I have following variables:
```
$ echo $ENVIROMENT
test
$ echo $TYPE
prod
```

In my `bash - dev` I have following variables:
```
$ echo $ENVIROMENT
test
$ echo $TYPE
dev
```

Nevertheless it would be great if something similar to `terminal.integrated.env.linux` can be used inside definition of profile. E.g.
```
    "terminal.integrated.env.linux": {
        "ENVIROMENT": "test"
    },
    "terminal.integrated.profiles.linux": {
        "bash - production": {
            "path": "bash",
            "env": [
                "TYPE": "prod"
            ],
            "overrideName": true
        },
        "bash - dev": {
            "path": "bash",
            "env": [
                "TYPE": "dev"
            ],
            "overrideName": true
        },
    },
```

**Comment by Tyriar** [comment]
fyi @meganrogge
