### ISSUE TITLE
Terminal API: Allow initial text to be shown

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120368]
Proposal: `TerminalOptions.initialText: string`

Example use case: GitLens running a git command and when it fails, create a new terminal which includes the error message in the header and the failed command ready to be run manually. This is generally useful for other applications (eg. welcome to the blah debug terminal, this is how it works, ...)

cc @eamodio

**Comment by Tyriar** [comment]
```ts
vscode.window.createTerminal({
	name: `Ext Terminal #${NEXT_TERM_ID++}`,
	initialText: '\x1b[3;1mSome custom message\x1b[0m'
});
```

<img width="725" alt="Screen Shot 2021-04-01 at 12 25 57 PM" src="https://user-images.githubusercontent.com/2193314/113344025-6b485280-92e5-11eb-86dc-bece1b687ffd.png">

**Comment by Tyriar** [comment]
This is in main, very little to do since initialText is already an option. Will bring this to next API sync.

**Comment by jrieken** [comment]
alternative names: message, placeholder, placeHolder

**Comment by Tyriar** [comment]
Will probably go with `message` to match `TreeView.message`.

**Comment by Tyriar** [comment]
Proposed API TPI: https://github.com/microsoft/vscode/issues/122215

**Comment by Tyriar** [comment]
Code:

```ts
vscode.window.createTerminal({
	name: `Ext Terminal #${NEXT_TERM_ID++}`,
	message: '\x1b[3;1mSome custom message\x1b[0m'
} as any);
```

Result:
<img width="398" alt="Screen Shot 2021-05-04 at 6 36 08 AM" src="https://user-images.githubusercontent.com/2193314/117011762-047ed600-aca3-11eb-9352-ccd91cc3c4c4.png">
