### ISSUE TITLE
Convert Text to Simplified ↔ Traditional Chinese

### ISSUE THREAD

**Issue by cHaLkdusT** [microsoft/vscode#120394]
Issue Type: <b>Bug</b>

Prerequisite:
System Preferences > Keyboard > Shortcuts tab > Services > Text
* Convert Text to Simplified Chinese (CTRL + OPT + SHFT + CMD + C)
* Convert Text to Traditional Chinese (CTRL + SHFT + CMD + C)
should be enabled.

Keyboard shortcuts doesn't work, but in TextEdit "Chinese Hanzi character conversion" works

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
pythonvspyt943cf:30280190
openwslfolder:30282073
vscoresta800:30284044
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by alexdima** [comment]
Thanks to https://github.com/microsoft/vscode/pull/156717, this works for me in latest VS Code. Steps:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/5047891/206878812-c9ff4058-752a-48ab-b00b-85cbc188a1ae.png">
* open a file with the content `「…」` (my understanding is that these are used in Traditional Chinese)
* select the text and press `ctrl+shfit+option+cmd+c`
* this converts the text to `“…”` for me:


https://user-images.githubusercontent.com/5047891/206878912-c979cad9-983e-487e-9452-ca1df0e64258.mp4
