### ISSUE TITLE
Crash prompt to reload window does not work in all cases

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#12043]
- VSCode Version: 1.5.2
- OS Version: Windows 10 (AU)

Steps to Reproduce:
1. Hangs VS somewho (see #12042 for example)
2. Wait until the promp window ask you what to do. 
3. Select "restart" editor.

The editor doesn't restart itself. Have to close it manually, and open again.

**Comment by bpasero** [comment]
I noticed this too but it seems to depend on what kind of crash you are ending up with.

**Comment by michaeljota** [comment]
It appears to be fixed in last insider. At least it did reload the windows. I don't know if, as you said, it's still reproducible with other scenarios.
