### ISSUE TITLE
Breakpoint placeholder does not wrap when not enough horizontal space

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#120446]
Version: 1.55.0-insider
OS: Mac

Steps to Reproduce:

1. Move activity bar to the right and show explorer 
2. Add a log point
3. Hide explorer and the default codelens/message in the Log Point is cut off

![recording (10)](https://user-images.githubusercontent.com/9721254/113455095-cd818000-93d7-11eb-8de9-2714b1945192.gif)

**Comment by isidorn** [comment]
Yeah, that's just life.
We could wrap the placeholder message, but then the breakpoint input could take potentially more lines.
We do no do this in other places (SCM Commit box for example).
So I would for now not change anything here
