### ISSUE TITLE
How other extensions use git extension api

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode#120448]
Is the way to use the git extension api in another extension still to copy the git.d.ts file into my extension as described in the [README](https://github.com/microsoft/vscode/blob/main/extensions/git/README.md)? It would be nice if there was an easier way to consume it so that I don't have to copy the changes when the api gets updated.

**Comment by eamodio** [comment]
I agree it would be nice to have the types wrapped up in a module or something more easily accessible
