### ISSUE TITLE
Split Cwd setting is not respected

### ISSUE THREAD

**Issue by ebeloded** [microsoft/vscode#120442]
In the last two releases of VSCode, the **Split Cwd** setting has not been respected. When a terminal is split, the working directory resets to workspace root, instead of being inherited from the parent terminal, even if the setting is

`"terminal.integrated.splitCwd": "inherited"`

I wasn't aware of this setting, being used to splitting terminal and remaining in the same directory. But at some point it stopped working. 

I also confirmed this behavior in the most recent Insiders build, without any extensions installed.

**Env Info**
```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```

**Comment by matthias-ccri** [comment]
This is also happening to me. With a monorepo in a subfolder, It's annoying when you're running a process and you want to run another command. You used to be able to split the terminal and have it keep the current working directory, but now you have to `cd` up to it again.

The recent [Terminal Tabs](https://code.visualstudio.com/updates/v1_57#_terminal-tabs) update seemed to introduce it.

Why haven't more people seen this issue? I searched for existing tickets but I didn't notice this one, but when I was typing mine up, this one popped up in "similar issues". @ebeloded can you put "Terminal" in the ticket title to try to get more visibility?

```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:26:56.255Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 4.15.0-147-generic
```
