### ISSUE TITLE
Feature Request: Scroll Off

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#12048]
In Vim, you can set a scrolloff so it keeps at least N lines below the cursor:

![scrolloff](https://cloud.githubusercontent.com/assets/4033249/18530654/6bb338c8-7a87-11e6-85c7-deab2d060d48.gif)

Currently Code has a scrolloff of 1. Would be great if this is made an option.

**Comment by Bill-Stewart** [comment]
Does VS Code have a "scroll window leaving cursor in view" command? The scroll commands I see in the default keymapping all scroll the cursor out of view.

**Comment by Bill-Stewart** [comment]
The answer to my question is yes - `editorScroll` function can do this, but behavior is a little different than vim behavior shown in the animated GIF. I believe request is for `scrollLineDown` but maintain the cursor position.

**Comment by Chadehoc** [comment]
> I believe request is for scrollLineDown but maintain the cursor position.

Not exactly. The feature is to scroll sooner, to always show context lines around the cursor. Currently, when moving down, scrolling ensures 1 context line left below the current line, and when moving up, none at all (scrolling does not begin until the cursor hits the top of the panel).

It is very comfortable to always keep 4 or 5 visible lines above/below the current line, after all moves that move it (next search hit, go to matching parenthesis, etc.).

This feature is called `scrolloff` in Vim and `scroll-margin` in Emacs.

**Comment by semanser** [comment]
There is extension [vscode-scrolloff](https://github.com/TickleForce/vscode-scrolloff) that provide similar functionality.

**Comment by octref** [comment]
I've removed Vim label since I see Sublime also have it.
Although @semanser's extension works well, I still hope this can make it into the editor itself since it's a common feature.

![soff](https://user-images.githubusercontent.com/4033249/32907324-7d4d64e0-cab4-11e7-917c-93022f1afd69.gif)

**Comment by xlucas** [comment]
So is this being considered at all? Really missing this :'(

**Comment by Garviell** [comment]
> There is an extension [vscode-scrolloff](https://github.com/TickleForce/vscode-scrolloff) that provides similar functionality.

That extension misbehaves badly when your have lines longer than your working window.

**Comment by spiffytech** [comment]
The extension also doesn't work with the Vim extension's `zb`  / `zt` commands.

**Comment by CodingPapi** [comment]
Come on, we need this common feature

**Comment by rebornix** [comment]
You should be able to set `editor.scrollOff` later this week with Insiders.

**Comment by rebornix** [comment]
Considering that this feature in VS Code is slightly different from Vim's scrollOff (for example, you can scroll the viewport without moving the cursor in VS Code, which is not affected by this feature), it's being named as `editor.cursorSurroundingLines`.

**Comment by eddylin** [comment]
Can you consider adding this to Integrated terminal too?

**Comment by waldyrious** [comment]
> It's being named as `editor.cursorSurroundingLines`.

How does this interact with `editor.scrollBeyondLastLine`, if at all? I have considered requesting a change to the latter to support numeric values in addition to boolean ones (which is actually how I came across this issue), and this new setting seems to partially address the reason why I'd want that: to prevent meaningful context to be scrolled entirely out of view.

**Comment by rebornix** [comment]
@waldyrious it's a different feature request https://github.com/microsoft/vscode/issues/56174

**Comment by waldyrious** [comment]
Thanks for the pointer, @rebornix. I've subscribed to that issue.

**Comment by Otiel** [comment]
@rebornix Thanks for implementing this!
