### ISSUE TITLE
Emmet not picking up `output.selfClosingStyle` setting

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120417]
The problem is the most popular formatter extension `prettier` uses `self-closing tags`. From user perspective every new line will be added with VSCode suggestions user should reformat the code to match. (https://github.com/prettier/prettier/issues/5246)

For example:
`input` expanded to `<input type="text">` Can this be customizable to be `<input type="text" />`

**Comment by aeschli** [comment]
The completion comes from emmet.

**Comment by rzhao271** [comment]
In your settings, add the following:

```json
"emmet.preferences": {
    "output.selfClosingStyle": "xhtml"
}
```

However, I also noticed that the extension doesn't pick up this setting properly, so this is a bug.

**Comment by pixieaka** [comment]
@rzhao271 And there's no option in suggestions for "xhtml" also. Can this option adds also to suggestions?

![image](https://user-images.githubusercontent.com/17777237/113778562-d9997480-972c-11eb-91dc-a48d3db1d559.png)
