### ISSUE TITLE
Add workspaceTrust to package.json schema

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#120489]
The workspaceTrust property should be in the schema so I get intellisense and a description and so on

**Comment by lszomoru** [comment]
Fixed with 5d94a7c95508c8a9f73dfdbac9b0cc68d2506ac8

**Comment by lszomoru** [comment]
Verification steps:
1. Settings UI
  - Search for `trust` and locate the setting workspace trust setting
  - Confirm that modifying the setting will prompt to restart the application
2. Settings JSON
  - Should be get intellisense when adding the `security.workspace.trust.enabled` setting
  - Confirm that modifying the setting will prompt to restart the application
