### ISSUE TITLE
Hide a file in the file explorer in the side bar programatically

### ISSUE THREAD

**Issue by Milo123459** [microsoft/vscode#120447]
I'm working on a feature request and I was wondering, how can I programmatically hide a file in the explorer in vscode? Basically what files.exclude does, but I need to access it somewhere else without updating that setting.

Any ideas? Thanks!

**Comment by Milo123459** [comment]
I would add the dev-question label but I can't.. @isidorn do you think you could do that?

**Comment by Milo123459** [comment]
@Tyriar you helped me before mind helping me again?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/117845
And making the filtering in the explorer public API. There is another issue tracking this.
