### ISSUE TITLE
Unknown error with no information when attempting to turn on "settings sync" with extensions disabled

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode#120486]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Disable built-in Github authentication and Microsoft Account for [performance and privacy reasons](https://github.com/microsoft/vscode/issues/98333). - I use the awesome [code settings sync extension](https://github.com/shanalikhan/code-settings-sync) from whom Microsoft stole the name to embed it's own invasive and buggy proprietary service. 
2. Click "manage gear"
3. Click "Turn on settings sync"

Does this issue occur when all extensions are disabled?: Yes

There is an unhelpful, useless, message saying that there was an error turning on settings sync, and asking users to check the logs for more detais. 

The logs contains absolutely no information at all. 

![image](https://user-images.githubusercontent.com/2473545/113495091-40b4f000-94c5-11eb-8d7c-ee688ccb8ab0.png)

**Comment by phgmacedo** [comment]
It's not a dupe.

**Comment by phgmacedo** [comment]
This one is another [one of those issues ](https://github.com/microsoft/vscode/issues/119395) that happen because vscode now just assumes that users are sending all their data to microsoft services through the auth extensions.

**Comment by gjsjohnmurray** [comment]
I am unclear whether anything is forcing you to to stop using the settings sync extension that you like and requiring you to use the integrated settings sync which apparently has dependencies that you are unwilling to accept.

**Comment by phgmacedo** [comment]
Nope. I clicked it. Accidentally, and seemed like a bug to me, so I opened the bug report.
