### ISSUE TITLE
Do not add to recent files list when running with "--diff"

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#12049]
- VSCode Version:152
- OS Version:10Ann

Steps to Reproduce:

1.  [Setup vscode as the default difftool for git](https://code.visualstudio.com/docs/editor/versioncontrol)
2. Run: `git difftool <commit>^ <commit>`
3. Check recent files list to see it populated with temp files

**Comment by bpasero** [comment]
Makes sense 👍
