### ISSUE TITLE
VScode generates a copy of my file with the suffix [conflicted]

### ISSUE THREAD

**Issue by Samy0412** [microsoft/vscode#120434]
Issue Type: <b>Bug</b>

I am just working on a js file (usually a react component), and suddenly it adds a suffix to my file (deleted) and creates a copy of it with the suffix [conflicted]. I delete it but it keeps doing it over and over again as long as I am working on this file. I have a lot of other components but it happens ony when I am working on this specific one. It has already happened to me before on another project. A clue of what is happening?

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|8.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id c704dbcf-7a2d-417f-abae-32288f8d74fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-database|baj|2.2.3
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
es7-react-js-snippets|dsz|3.1.1
css-flexbox-cheatsheet|dzh|3.2.2
gitlens|eam|11.3.0
vsc-material-theme|Equ|33.1.2
vsc-material-theme|Equ|33.2.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.1
auto-close-tag|for|0.5.10
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.5.0
chat|kar|0.35.0
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
elmmet|nec|1.0.1
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.3
ejs-snippets|The|0.7.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
