### ISSUE TITLE
Add ability to change color of currently selected code completion item.

### ISSUE THREAD

**Issue by safield** [microsoft/vscode#120476]
I am reviewing the color theme reference. https://code.visualstudio.com/api/references/theme-color

I am trying to change the color of the current item being highlighted in the code completion window. More specifically, when I start typing a method name, a box shows up next to where I am typing. Within this box is a list of completion suggestions. When typing, one list entry has a different background that the other to indicate that it is the current selection (pressing enter will use this suggestion.

After looking through the color reference, there is no item listed there to change this color. 

I have tried:

list.hoverBackground
list.focusBackground
list.inactiveSelectionBackground
list.activeSelectionBackground
listFilterWidget.background

Potentially the docs are just missing the value.

**Comment by gjsjohnmurray** [comment]
Try `quickInputList.focusBackground`

**Comment by ArturoDent** [comment]
`"editorSuggestWidget.selectedBackground"`
