### ISSUE TITLE
The code fold feature is bad in HTML file included pre and code tag

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#12044]
- VSCode Version: 1.5.2  (66f37fd, 2016-09-12T 13:30:03.456z)
- OS Version: Windows 7  6.1.7601

Steps to Reproduce:
1.  There is an HTML file in VSCode like this:(it include a `pre` ,a `code` tag and some other language code inside the `code` tag)
   
   ![2016-09-15_033153](https://cloud.githubusercontent.com/assets/4303130/18526925/294cec18-7af5-11e6-976c-65296341fd21.png)
2.  And I click the fold button beside line number 8 or line number 9, Then the VSCode could not fold code correctly, just like the screenshot below:
   
   ![2016-09-15_033211](https://cloud.githubusercontent.com/assets/4303130/18527122/0168cb80-7af6-11e6-80cc-3798a29b9022.png)

:pray: Waiting for response.

**Comment by hangxingliu** [comment]
@aeschli I think that this bug not only exists in the HTML file but also in other type of files

**Comment by hangxingliu** [comment]
@aeschli I think that this bug not only exists in the HTML file but also in other types of files.
And It seems that wrong indent format could affect fold and  unfold function in VSCode

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand HTML elements, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
