### ISSUE TITLE
Command icon doesn't show in editor/title

### ISSUE THREAD

**Issue by dmitriklem** [microsoft/vscode#120406]
Issue Type: <b>Bug</b>

The following code stopped working in 1.55.0 while running under extensionHost.  Worked in 1.54.2

`      {
        "command": "myextension.ExecuteRequest",
        "icon": {
          "light": "resources/light/play.svg",
          "dark": "resources/dark/play.svg"
        }
      }`
       `      "editor/title": [
        {
          "command": "myextension.ExecuteRequest",
          "group": "1_run",
        }
      ]`

Icon "play" doesn't show up in the editor/title and there is no area in editor/title that would be respond to a click with corresponding functionality.  Keybindings works.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (15.45GB free)|
|Process Argv|--crash-reporter-id 997c6246-9091-403a-b6d1-1128094b0972|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
azurite|Azu|3.11.0
vscode-eslint|dba|2.1.19
tsl-problem-matcher|eam|0.4.0
rest-client|hum|0.24.4
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
azure-account|ms-|0.9.7
debugger-for-chrome|msj|4.12.12
vscode-yaml|red|0.17.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833:30267464
vshan820cf:30276953

```

</details>

**Comment by gjsjohnmurray** [comment]
See #117259 for the testplan item for two related issues that may be relevant. However these changes landed in 1.54

**Comment by gjsjohnmurray** [comment]
Probably #117593

Since you appear to be an extension developer I recommend that you use Insiders regularly. Doing this should give you early warning of changes that impact your extensions, and time to adapt or get changes made before the next Stable.

**Comment by dmitriklem** [comment]
Yes, using "editor/title/run" fixed the problem.  I will definitely switch to Insiders.

Thank you gjsjohnmurray.

**Comment by gjsjohnmurray** [comment]
👍 please close the issue then.

**Comment by jrieken** [comment]
Yeah, the `1_run` doesn't exist anymore
