### ISSUE TITLE
Typescript Code Lens is shown above all type declarations

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#120465]
- VS 1.55.0, TS stable & nightly

```ts
export const foo = 1;

const bar = 2;

export type foo = 1;

type bar = 2;
```

<img width="263" alt="Code_2021-04-03_14-12-32" src="https://user-images.githubusercontent.com/30108880/113478223-cfa31780-9487-11eb-8ae7-15ccd0d07ead.png">

Expected no Code Lens above `type bar`

Expected Code Lens behavior to be the same for all declarations

**Comment by mjbvz** [comment]
This is by-design. We do the same with classes and interfaces, even if they are only used in the current file

We don't do this on locals (non-exported) variables because it would be very noisy
