### ISSUE TITLE
Add support for InsertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#12046]
## Feature Request

**User Scenario**

Steps to Reproduce:

1. TypeScript Version: 2.*
2. `<input value={ this.state.value } />`
3. Format document

**Expected behavior:**
In **1.8.10** the spacing inside the brackets was unchanged on format operation (closing bracket `}` or format document).
`<input value={ this.state.value } />`

**Actual behavior:** 
In **2.*** the space inside the brackets is always removed when formatting.
```ts
<input value={this.state.value} />
```

**Discussion**
- [Original Issue](https://github.com/Microsoft/vscode/issues/11791)
- [Fix on TypeScript's End](https://github.com/Microsoft/TypeScript/pull/9361)

Recommendation from @dbaeumer was to have this added to September's milestone.

**Comment by dbaeumer** [comment]
@waderyan I am not sure what you expect me to do here. I looked at the tsserver and it doesn't have any support for that options. Is this something we think the tsserver needs to provide. If so we need to open a request against them.

**Comment by waderyan** [comment]
Hey @dbaeumer - this issue was created per your comment [here](https://github.com/Microsoft/vscode/issues/11791#issuecomment-247144018).

**Comment by dbaeumer** [comment]
@waderyan yes I remember. But somehow I thought the tsserver introduced a new setting we have to adopt which doesn't seem to be the case. Sorry for that.

**Comment by jwbay** [comment]
@dbaeumer TypeScript did introduce a new setting. It's in the linked TypeScript PR in the original issue. If VSCode ships the September release with TS2.0 and doesn't adopt the new setting, VSCode will start stripping spaces from JSX expressions on format and users will not have any way to turn this off. This is especially painful for people with lint rules enforcing spaces in JSX expressions.

**Comment by dbaeumer** [comment]
The problem is that the TS team forgot to expose the setting in the tsserver which we use for formatting. I opened https://github.com/Microsoft/TypeScript/issues/11314 to fix this.

**Comment by dbaeumer** [comment]
I will traget this for October since this first needs work on the TS side.

**Comment by dbaeumer** [comment]
Got addressed for 1.7 but requires TS 2.0.6.
