### ISSUE TITLE
CANT ACCESS MARKETPLACE

### ISSUE THREAD

**Issue by TonyStark1234** [microsoft/vscode#120484]
Issue Type: <b>Bug</b>

Cant Access Marketplace due to proxy error of my VSCode

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.92GB (0.53GB free)|
|Process Argv|--crash-reporter-id a9b10827-db2f-4162-bb27-869572f9121c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2

</details>

**Comment by chrmarti** [comment]
Could you start VS Code with `--log-net-log=<some-folder>\netlog.json`, retry the failing feature and then post the created netlog.json here?
