### ISSUE TITLE
Typescript language service crashing on @flow files

### ISSUE THREAD

**Issue by martinorona-classy** [microsoft/vscode#120440]
Issue Type: <b>Bug</b>

I keep getting notifications that the Typescript language service crashed 5 times in the last 5 minutes. I'm working on a Flow file annotated with `// @flow` at the top, so Typescript should know to leave it alone.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id c9cb20cf-3f27-454d-9c63-b3d4528d89f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
project-manager|ale|12.0.1
atlascode|atl|2.8.6
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.19
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.3.0
prettier-vscode|esb|6.3.1
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.24.0
plantuml|jeb|2.14.4
vscode-colorize|kam|0.11.0
git-graph|mhu|1.29.0
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.163.2
vsliveshare|ms-|1.0.4070
vscode-css-peek|pra|4.1.3
vscode-yaml|red|0.17.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vs-code-prettier-eslint|rve|2.1.0
vscode-todo-highlight|way|1.0.4
JavaScriptSnippets|xab|1.8.0
yog-plantuml-highlight|Yog|0.0.5
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt943:30280189
wslfolderdoccf:30280165
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by mjbvz** [comment]
Make sure to follow the setup instructions for Flow: https://marketplace.visualstudio.com/items?itemname=flowtype.flow-for-vscode
