### ISSUE TITLE
VSCode Exploration app icon isn't matching the Big Sur theme

### ISSUE THREAD

**Issue by KittyX29** [microsoft/vscode#120401]
![image](https://user-images.githubusercontent.com/81065901/113376540-97b8a900-938f-11eb-9929-6427cc885302.png)

**Comment by misolori** [comment]
@KittyX29 what Exploration version are you on?

**Comment by KittyX29** [comment]
@misoguy 
![image](https://user-images.githubusercontent.com/81065901/113513513-c5684280-9587-11eb-96b5-336d959ed8fd.png)

Download link : https://github.com/Microsoft/vscode/issues/52629

**Comment by KittyX29** [comment]
![image](https://user-images.githubusercontent.com/81065901/113513551-eb8de280-9587-11eb-9732-3e235f9065e3.png)

**Comment by KittyX29** [comment]
Everything in this build seems very off - The color scheme, menu etc

**Comment by KittyX29** [comment]
nvm resolved in https://github.com/microsoft/vscode/issues/111543

**Comment by KittyX29** [comment]
![image](https://user-images.githubusercontent.com/81065901/113513717-ad44f300-9588-11eb-9f11-33e4fadf5d15.png)

**Comment by KittyX29** [comment]
The logo tho

**Comment by misolori** [comment]
@KittyX29 you are on an outdated version of the exploration build, the download in the issue you linked to is from 2018. We haven't released an updated exploration in 3mo, ping on @deepak1556 as to when there will be an updated version. The updated big sur icons start in version 1.55

**Comment by KittyX29** [comment]
@misoguy I updated VSCode Exploration and I am now on the January 2021 update

Version: 1.53.0-exploration
Commit: 0c9e2dadd986d0bc085f1c5352245531eef65e84
Date: 2021-01-07T06:28:46.730Z
Electron: 11.1.0
Chrome: 87.0.4280.88
Node.js: 12.18.3
V8: 8.7.220.29-electron.0
OS: Darwin arm64 20.3.0

Im unable to fing the march update tho. Please help!

Btw the logo isnt matching the theme 

![image](https://user-images.githubusercontent.com/81065901/113529282-b06bcd80-95e0-11eb-9c3b-ddfef177ebf2.png)

**Comment by misolori** [comment]
@KittyX29 As I mentioned above, the new icons appeared last month and the exploration build hasn't been updated since January so you'll have to wait until a new exploration build is out.

**Comment by KittyX29** [comment]
tysm closing this
