### ISSUE TITLE
VSCode unresponsive on some operations with SSH remote

### ISSUE THREAD

**Issue by genericmoniker** [microsoft/vscode#120451]
Issue Type: <b>Bug</b>

I'm working over ssh to a Vagrant-created VM (host is Ubuntu 20.04, guest is CentOS 7). Various operations seem to hang indefinitely (with a progress indicator "spinning"), such as searching within my workspace, staging files in the source control window, discovering tests, etc. This seems to have started happening with v.1.55.

The "Log (Remote Server)" output window has messages like this:

```
[2021-04-02 16:16:21.046] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-04-02 16:16:26.719] [remoteagent] [error] No ptyHost heartbeat after 12 seconds
[2021-04-02 16:17:56.419] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-04-02 16:21:50.558] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-04-02 16:32:39.671] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2021-04-02 16:33:35.685] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
```

On the VM, I notice that there is a node process with high CPU use. Here is an example from top:

```
27661 vagrant   20   0 1463260 380932  18912 R 108.8  1.1  63:37.16 /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/node /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/uriTransformer.js                                                                                                           
29977 vagrant   20   0 1038324  85148  17664 S   3.7  0.2   1:21.46 /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/node /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/uriTransformer.js                                                                                                           
29885 vagrant   20   0  926912  49372  17284 S   0.5  0.1   0:08.46 /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/node /home/vagrant/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/main.js --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret /home/vagrant/.vscode-server/.c185983a683d14c396952dd432459097bc7f757f.token                                                                                    
```

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.8.0-48-generic snap
Remote OS version: Linux x64 3.10.0-1127.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (32 x 3690)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|62.74GB (5.87GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 468fc44b-1c92-4baf-935d-763ca4095fd3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: jarvis-centos7|
|OS|Linux x64 3.10.0-1127.el7.x86_64|
|CPUs|AMD Ryzen Threadripper 1950X 16-Core Processor (16 x 3393)|
|Memory (System)|34.36GB (30.67GB free)|
|VM|50%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
systemd-unit-file|coo|1.0.6
VS-code-vagrantfile|mar|0.0.7
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vs-keybindings|ms-|0.2.0
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by genericmoniker** [comment]
May be related to installing the Python extension on the remote host? CPU usage % for node processes without any extensions is in the single digits. As soon as I install the Python extension, it jumps to > 100% and stays there. But I don't immediately see broken functionality with search, source control, etc. so not sure if they're related.

**Comment by roblourens** [comment]
> As soon as I install the Python extension, it jumps to > 100% and stays there

Thanks for identifying that. Please open an issue on the Python extension's repo, hopefully they can narrow it down.
