### ISSUE TITLE
Mac not ready for Go extension on reboot due to Saved Application State

### ISSUE THREAD

**Issue by benguild** [microsoft/vscode#120479]
Pulling this in from https://github.com/golang/vscode-go/issues/1339 because it's seemingly an application issue.

I can't get any more information out of this. The only solution is to quit the application entirely before using it if it reopens at login on my Mac. I can reproduce 100%, and it works fine after being restarted.

> Issue Type: Bug
> 
> Hey guys I noticed that if I restart my Mac with Visual Studio Code open, it screws up my Go environment due to the "Saved Application State."
> 
> See attached screenshot... it expects me to reinstall all of the Go tools in my non-GOPATH. (it defaults to `~/go` but I have it somewhere else... so using these options here creates a duplicate Go path)
> 
> Restarting the app works around this, but I would imagine this could be fixed.
> 
> Extension version: 0.23.1
> VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
> OS version: Darwin x64 20.3.0
> 
> <img alt="Screen Shot 2021-03-11 at 13 34 50" width="469" src="https://user-images.githubusercontent.com/1185659/111085140-a6701680-84db-11eb-9a92-148b5b6c2001.png">

**Comment by bpasero** [comment]
/duplicate https://github.com/microsoft/vscode/issues/108804

see also https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-is-slow-error-warning
