### ISSUE TITLE
Settings sync - Map modifier keys between platforms

### ISSUE THREAD

**Issue by patrikturi** [microsoft/vscode#120472]
I use the built-in Settings Sync with `"settingsSync.keybindingsPerPlatform": false` to sync between a Mac and a Linux machine.

I get the following key mapping:
```
# Mac -> Linux
cmd -> super (windows key)
ctrl -> ctrl
alt (option) -> alt
```

However, I would expect the following mapping:
```
# Mac -> Linux
cmd -> ctrl
ctrl -> super (windows key)
alt (option) -> alt
```

I think the majority of users would also prefer the 2nd option. This is the common understanding, because of `cmd + C` -> `ctrl + C` is true in most applications.

Would it be possible to do such mapping (search&replace) in `keybindings.json` before (or after) syncing?

**Comment by sandy081** [comment]
Changing keybindings according to platform while syncing is not feasible. Instead you can use when conditions like `isMac` to define platform specific keybindings - https://github.com/microsoft/vscode/issues/8962
