### ISSUE TITLE
`file.trimTrailingWhitespace` should have a per-language configuration

### ISSUE THREAD

**Issue by Deophius** [microsoft/vscode#120468]
Hi, I have turned this option on, but I find it a little difficult to work with `git add -p` 's "manually edit hunk".

This opens a file `addp-hunk-edit.diff` in Code and this is full of trailing whitespaces that must be preserved. Otherwise, git will not function correctly. So I have to turn this option off every time I want to manually edit a hunk.

I think it would be more convenient if this option can be turned on or off depending on the language mode or filename. For example, I can add a rule that says `*.diff` files should not have trailing whitespaces trimmed while `*.cpp` files should.

Thanks!

**Comment by ArturoDent** [comment]
"[diff]": {
         "files.trimTrailingWhitespace": false
        },

And then turn it on for all other files with the main setting.

**Comment by Deophius** [comment]
Thanks!
