### ISSUE TITLE
Notebooks output not working in code spaces

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#120409]
- VS Code Version:
- Version: 1.56.0-insider
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:18:23.302Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63
- OS Version:
- default container image

Steps to Reproduce:

1. open a notebook with .NET Interactive
2. evaluate code `display(1)`
3. no output is rendered
the same operation using local vscode connected to remote codespaces will produce output
this is code spaces with web client 
![image](https://user-images.githubusercontent.com/375556/113396684-cf295480-9393-11eb-81ce-8d01fed8c5e8.png)

This is same version of vscode connected to remote
![image](https://user-images.githubusercontent.com/375556/113396794-03047a00-9394-11eb-9960-e5c0c7b71250.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by colombod** [comment]
After testing with the python extension team we both realised that only "text/plain" mimetype goes on display while other mimetypes are dropped

**Comment by DonJayamanne** [comment]
FYI - We can replicate this with Jupyter extension as well.

**Comment by rebornix** [comment]
Not seeing this anymore on latest Codespace

<img width="880" alt="image" src="https://user-images.githubusercontent.com/876920/114478536-4f7d6000-9bb3-11eb-9909-8cfdad4af8fe.png">
