### ISSUE TITLE
I don't like new icon...

### ISSUE THREAD

**Issue by isfk** [microsoft/vscode#120410]
版本: 1.55.0
提交: c185983a683d14c396952dd432459097bc7f757f
日期: 2021-03-30T16:01:05.981Z (2 天前)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

My macos version is 10.15.7 (19H114) 

Now the new icon is ugly on my macbook

**Comment by wiecznyPoszukiwacz** [comment]
Upgrade your macbook.

**Comment by nuruddinsyah** [comment]
This is the same on my Mac. I use macOS Sierra 10.12.4.

![Screen Shot 2021-04-02 at 9 54 59 PM](https://user-images.githubusercontent.com/29025381/113427400-244e8000-93ff-11eb-84df-99a40cc7edb4.png)

**Comment by heismauri** [comment]
> This is the same on my Mac. I use macOS Sierra 10.12.4.
> 
> ![Screen Shot 2021-04-02 at 9 54 59 PM](https://user-images.githubusercontent.com/29025381/113427400-244e8000-93ff-11eb-84df-99a40cc7edb4.png)

Same issue here on MacOS Catalina 10.15.7

**Comment by alexgwolff** [comment]
Same issue here and very slow after update. 
Mac OS Sig Sur 11.2.3

**Comment by DeveloperWOW64** [comment]
there is a way to fix this, one sec

**Comment by DeveloperWOW64** [comment]
There are 2 ways to fix this. First way:

1. go [here](https://macosicons.com/vscode) and click on the one you like
2. follow the steps from [this website](https://macosicons.com/how-to)
3. Voila!

Second way:
1. Right-click (control+click) the Finder from the dock. Then click Go
2. Enter in `/Applications/Visual Studio Code.app/Contents/Resources/`
3. Then find `Visual Studio Code.icns`
4. Open a new Finder window
5. Go to the Applications Folder
6. Find Visual Studio Code
7. Right-click it and select `Get Info`
8. A new window should open, with a small corrupted icon in the corner of the window.
9. Drag `Visual Studio Code.icns` from the other window, and place it on top of corrupted icon from the `Info` window
10. It *should* look fine now.

**Comment by DeveloperWOW64** [comment]
hopefully that should solve it

**Comment by misolori** [comment]
Thanks for the feedback. Please see https://github.com/microsoft/vscode/issues/120305 if you are seeing the icon appear glitched.

**Comment by DeveloperWOW64** [comment]
Oh dear, the link i gave, (macosicons.com) has been hacked, and the icons are being restored
