### ISSUE TITLE
0.10.3: Changes in filesystem structure not always reflected in VSC

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#1204]
e.g. adding a controller using ember-cli on a command line. One needs to restart VSC in order to see the changes.

Mac OSX El Capitan.

EDIT: Found the refresh button. Maybe this is a non-issue now. 
Closed

**Comment by egamma** [comment]
Also you do not have to restart VS Code you can also run 'Reload Window' from the command palette.

Closing as requested.
