### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by imaginarymuffin72** [microsoft/vscode#120427]
We have written the needed data into your clipboard because it was too large to send. Please paste
Issue Type: <b>Bug</b>

Terminal becomes non-responsive, while typing text suddenly restarts on same line 

VS Code version: Code - Insiders 1.55.0-insider (Universal) (6f726bcdf6a4d6cb518a3fcdb03c21be7293f417, 2021-03-25T08:17:34.093Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 3.10.0-862.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id f4add8c9-000d-4d9d-b653-7175124e62b4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: quest.it.northwestern.edu|
|OS|Linux x64 3.10.0-862.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (28 x 2399)|
|Memory (System)|124.11GB (39.71GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
stata-enhanced|kyl|1.6.1
remote-containers|ms-|0.166.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoccf:30278406
vscoresta800:30283263
vspre833:30267464
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfilebuttoncf:30280635
vshan820:30276952
pythondataviewer:30283452

```

</details>

**Comment by meganrogge** [comment]
Hello, please include steps to reproduce this as I cannot.

**Comment by imaginarymuffin72** [comment]
Hi, this cannot be reproduced because it's a matter of typing in the
terminal.
When I type ANYTHING in the terminal it looks funky and words overlap.

**Comment by VanderSP** [comment]
Im going crazy weeks, randomly my terminal starts to put random characters like
;1R 1;0 :C0qe0pofijadgoishdgadg

**Comment by gencer** [comment]
@meganrogge About writing to same line, see below:

![1](https://user-images.githubusercontent.com/1711576/113642632-ed8b9a80-9688-11eb-9147-7dbd14d19542.gif)


P.S.: Using `bash` on WSL. But happens on local `bash` or SSH's `bash` too. Including powershell.

**Comment by VanderSP** [comment]
yes this also happens too... and sometimes hangs at bottom
and sometimes when word wrap it makes a space                   like this

**Comment by coreylista** [comment]
> Im going crazy weeks, randomly my terminal starts to put random characters like
> ;1R 1;0 :C0qe0pofijadgoishdgadg

Have you been able to find a solution to this issue? I have disabled all extensions and it still happens, on two different Macs

**Comment by Tyriar** [comment]
Line wrapping badly: https://github.com/microsoft/vscode/issues/116029
1R appearing: https://github.com/microsoft/vscode/issues/120825

/duplicate
