### ISSUE TITLE
Add context awareness in regards to Windows 10's "task view"

### ISSUE THREAD

**Issue by DamonStamper** [microsoft/vscode#120433]
When using Windows "Task View" to get virtual desktops then opening a file should result in VSCode using an existing VSCode window or creating a new one in that task view context. 

- Version of VS Code: 
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
- Your operating system
Window 10 Enterprise (10.0.18363 N/A Build 18363)
- List of extensions that you have installed
N/A
- Reproducible steps (1... 2... 3...) that cause the issue
1 create a new task view.
2 on the first task view open vscode
3 switch to the 2nd task view
4 using windows explorer in the 2nd task view, open a file that will open in vscode
5 notice that you are switched back to task view 1, and the file is opened in addition to any other files that were open in VSCode on taskview 1 resulting in unintentional context switching.

Please note that you are able to open VSCode manually in whatever context you desire and are able to open a file from VSCode. You can also ensure that your context's VSCode window is the last VSCode window that was selected then opening a file through Windows Explorer will send the file to that VSCode instance.
- What you expected to see, versus what you actually saw
Opening a file is not aware of which "task view" to use when opening VSCode
- Images, animations, or a link to a video showing the issue occurring
N/A
- A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
N/a
  - Note: Because the developers need to copy and paste the code snippet, including a code snippet as a media file (i.e. .gif) is not sufficient.
  - Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)
N/A

**Comment by yfwz100** [comment]
This has been fixed now. (I'm using VSCode 1.64.2)

> Another requirement, let me know if you want this as a seperate issue:
> 
> Situation:
> 
> * Desktop 1 I have 3 VS Code Windows
> * Desktop 2 I have 1 VS Code Window
> 
> While I'm in Desktop 2 if I hover over the VS Code icon in the task bar it reveals all 4 window icons, but it should only show me the one window that is active in that desktop.
> 
> **Note:** Alt + Tab works correctly. I see a single VS Code window.

**Comment by ozten** [comment]
+1, fixed for me as well. @yfwz100 thanks the update.

**Comment by deepak1556** [comment]
Closing per https://github.com/microsoft/vscode/issues/120433#issuecomment-1048403699
