### ISSUE TITLE
Unable to open pdf by internal tab on windows

### ISSUE THREAD

**Issue by Ddddavid-he** [microsoft/vscode#120493]
Issue Type: <b>Bug</b>

I have some pdf files generated by xelatex, vscode worked well with them previously. However, after the updates I cannot open them anymore. Vscode show me a blank tab instead of pdfviewer.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor            (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.54GB free)|
|Process Argv|--crash-reporter-id a4fbf1e6-3a24-4f76-bf8e-d8d80b7bd530|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 2600X Six-Core Processor (12 x 3600)|
|Memory (System)|12.45GB (11.68GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
bracket-pair-colorizer-2|Coe|0.2.0
swift|Kas|0.2.0
vscode-language-pack-zh-hans|MS-|1.55.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
shellman|Rem|5.4.0
githistory|don|0.6.16
matlab|Gim|2.0.1
latex-workshop|Jam|8.16.1
vscode-gutter-preview|kis|0.27.1
git-graph|mhu|1.29.0
vscode-language-pack-zh-hans|MS-|1.55.2
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30283453

```

</details>

**Comment by mjbvz** [comment]
VS Code does not have built-in pdf support. It sounds like you used to have a pdf extension installed and no longer do
