### ISSUE TITLE
When update new version of VS Code, I lost the sign in account

### ISSUE THREAD

**Issue by chenxizhang** [microsoft/vscode#120458]
When update new version of VS Code, I lost the sign in account, so I need to sign in to Github again to sync the settings

**Comment by Thomas1664** [comment]
After updating to version 1.55.0 I experienced the same issue. In particular, I had to sign in again to settings sync and GitHub extension.

**Comment by RMacfarlane** [comment]
This is expected, please see the release notes: https://code.visualstudio.com/updates/v1_55#_encryption-update-on-windows

This should not happen for future releases
