### ISSUE TITLE
Disable or handle VS Code updates check

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#120456]
Looks like there are certain cases where updates are checked when starting to run test. And this update check prevents the tests to run for some reason... Only happens on Windows for us. Sample output for timeout and succeeding cases attached (not exactly sure when it checks for update and when not).

It would be great if there is a way to disable VS Code update check during testing as a test run option, or handle the update check somehow, or just disable update check in tests since the VS Code version can be specified when running the tests anyway. 

Timeout: 
```
[16:01:23] Starting 'test'...
[16:01:23] Starting 'runUnitTests'...
Downloading VS Code 1.55.0 from https://update.code.visualstudio.com/1.55.0/win32-archive/stable
Downloaded VS Code 1.55.0 into .vscode-test/vscode-1.55.0


Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2021-04-02T23:02:05.926Z] update#setState idle

(node:7396) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

[main 2021-04-02T23:02:35.940Z] update#setState checking for updates

[main 2021-04-02T23:02:36.070Z] update#setState idle

***Time Out***
```

Expected:
```
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.

[main 2021-03-31T00:28:04.018Z] update#setState idle

(node:15100) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(node:15100) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information

(node:22316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Exit code:   0
Done
```

**Comment by xisui-MSFT** [comment]
It's not the same issue as in the duplicate detection.

Tried to disable the update check but test run still hang at the start. Can't see the real behavior since the CI agent runs as a service, but I don't know how to repro this locally.

In the CI, if I start test, and then terminate the test run by setting a short timeout like 1 minute, and then run the test again, all the test in the second pass will execute normally.

**Comment by joaomoreno** [comment]
@bpasero This is a great finding, right? Is there a way for me to detect VS Code is currently being run as part of a test suite? Do we have any flag in the env service I could check?

**Comment by bpasero** [comment]
@joaomoreno how about checking if a [`extensionTestsPath`](https://github.com/microsoft/vscode/blob/19f6f3103606da3fe5d8be4b722d96fe8e18271a/src/vs/platform/environment/common/argv.ts#L43-L43) is provided. 

A more complete check is implemented here that also takes running from debugger into account:

https://github.com/microsoft/vscode/blob/ff0f7f3cf24251a4921eb5c467c1dd2f805094a3/src/vs/platform/windows/electron-main/window.ts#L143-L143

**Comment by joaomoreno** [comment]
I suggest making sure Code gets spawned with `--disable-updates` instead.
