### ISSUE TITLE
Debug codicons are colored with a CSS selector that's excessively broad

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#120429]
In theory codicons can be used in statusbar items, except for the debug ones basically as they are colored badly via CSS, meaning they won't have their default color in the statusbar because the CSS overrides it.

<img width="1440" alt="Screen Shot 2021-04-02 at 16 18 55" src="https://user-images.githubusercontent.com/1812093/113429030-c22a5680-93cf-11eb-9c24-bac427c5d7f5.png">

Those selectors should be rewritten to only change the color of those icons within the debug toolbar thing, so that extensions like mine can start using the right icons in the statusbar too.

**Comment by gjsjohnmurray** [comment]
This interests me.

Forcing the color of the debug disconnect icon is explicitly only done for `.debug-view-content` and `.debug-toolbar`

https://github.com/microsoft/vscode/blob/b88f1ede0ec42c5a08e747c26bd137b874fcf172/src/vs/workbench/contrib/debug/browser/debugColors.ts#L281

But for all the other debug icons it is unconditional, e.g.

https://github.com/microsoft/vscode/blob/b88f1ede0ec42c5a08e747c26bd137b874fcf172/src/vs/workbench/contrib/debug/browser/debugColors.ts#L276

@isidorn would it be reasonable to make all of the color-forcing conditional upon `:not(.part.statusbar)` instead? When I built a local branch with that change it seemed to resolve the issue for @fabiospampinato's extension without adverse effects elsewhere.

If this sounds good I will submit a PR.

**Comment by misolori** [comment]
IMO the colors should only be scoped for the area they are intended to be used in. This reduces the unnecessary additions of :not that could break in the future with other new areas. I'd just scope the rest.

**Comment by gjsjohnmurray** [comment]
@misolori fair point. I have submitted a PR that I think does exactly that, though i's possible I have overlooked some other context(s) in which the colored debug codicons are currently validly used.

**Comment by fabiospampinato** [comment]
I don't quite understand how this is out of scope, isn't it just a bug in the app?

**Comment by misolori** [comment]
These actually already got fixed incidentally via https://github.com/microsoft/vscode/pull/127044

<img width="211" alt="CleanShot 2021-08-16 at 08 22 01@2x" src="https://user-images.githubusercontent.com/35271042/129587983-890da788-d628-4474-b634-2b8f8aeb064a.png">

**Comment by anandbibek** [comment]
I don't think it got fixed
![image](https://github.com/microsoft/vscode/assets/1944248/4ec7c367-9c04-4530-8c2f-91404d29f8a7)

**Comment by gjsjohnmurray** [comment]
@anandbibek I recommend you open a new issue about this, using Report Issue from the Help menu so your issue includes details of version, extensions and platform.

Please also use the Start Extension Bisect command to identify which extension is adding the coloured button, and give repro steps.
