### ISSUE TITLE
VSCode Completion wrong suggestions in plaintext file

### ISSUE THREAD

**Issue by ThaddeusJiang** [microsoft/vscode#120495]
- VS Code Version: 1.55.0
- OS Version: macOS 11.1

Steps to Reproduce:

1. install this extension, https://github.com/ThaddeusJiang/Reproducing-VSCode-completion-bug
2. create a `.txt` file, type `con-so`
3. `CMD`+`i`  trigger completion

Should only show `con-sole`, but show `sole` and `con-sole`

![image](https://user-images.githubusercontent.com/17308201/113501699-3268e180-9562-11eb-8c82-8a3e7ba6f839.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
A completion item provider is invoked, returns completions but they don't show up! 😕  What's the issue? Filtering! Filtering compares completions with a prefix and hides those that don't match.

#### Example

* trigger completions here: `say.he|` (`|` is the cursor)
* provider returns `abc`, `help`, `hood`
* the editor takes the `he`-prefix and scores it against `abc`, `help`, and `hood`. 
* scoring yields these result: 
  * `abc` - no match, don't show
  *  `help` - good match, show
  * `hood`  - no match, only `h` occurs, don't show
* editor shows `help` suggestion, does *not* show `abc` and `hood` suggestion

#### Extensions Rule!

The above sample was using "defaults" to determine the prefix and the filter criteria. 

 * `prefix:`  each completion can define its very own prefix via [`vscode.CompletionItem#range`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3803). Taking the example above, valid prefixes can be `say.he` or `.he` or ` ` (the empty string). Any range is valid as long as it includes the cursor position and is single line only.
* `filter:` each completion can define what string to use when filtering. The default is the label but via [`vscode.CompletionItem#filterText`](https://github.com/microsoft/vscode/blob/47b1183dfda519c32d78b591cfa721d3b0b874ae/src/vs/vscode.d.ts#L3776) any string can be defined

When to use what? It depends on the language, its word definition, and if you control/understand the word definition or not. The defaults usually work well enough but some languages might use a non-intuitive word definition, or completions span multiple words, or completions include non-word character etc. In all those cases the `range`-property should be used.
