### ISSUE TITLE
Markdown doesn't recognize pycon as a language

### ISSUE THREAD

**Issue by tusharsadhwani** [microsoft/vscode#120411]
- VS Code Version: 1.54.3
- OS Version: Pop OS 20.04

Funnily, the "Markdown Preview" mode recognizes it just fine.

Steps to Reproduce:

1. Write a code block with language "pycon"
2. Example:

![image](https://user-images.githubusercontent.com/43412083/113396746-a9af4180-93b9-11eb-9172-9176bd3bbb26.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by tusharsadhwani** [comment]
BTW, those colorized brackets are due to another extension, without any extensions the whole code block has no syntax highlighting.

**Comment by tusharsadhwani** [comment]
@mjbvz I opened this issue because markdown code block syntax highlighting is built into the vscode's default markdown extension. Other code block languages like `python`, `dart`, `go`, even `bash` etc. all get highlighted just fine, which is why i thought this would be a bug. Let me know if `pycon` is somehow an exception, or can't be implemented. Thanks.

**Comment by mjbvz** [comment]
The markdown editor highlights known language modes. pycon isn't a built-in language mode so it would have to come from an extension 

The preview uses greatly simplified `highlight.js` highlighting for code blocks

**Comment by tusharsadhwani** [comment]
okay! thanks for clarification
