### ISSUE TITLE
Terminal tab showing up twice in the bottom panel

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoft/vscode#120445]
Issue Type: <b>Bug</b>

Apologies, I do not have clear steps to reproduce the problem. I happen to notice this today when opening a new VS Code instance from the task bar. The "Output" pane is getting the title "Terminal". Problem persists on reloading the VS Code window. When clicking on the second "Terminal" tab, the name gets changed correctly to "Output". 

![image](https://user-images.githubusercontent.com/16890566/113454627-86869100-93bd-11eb-83a1-758a5ca5e0d1.png)

Feel free to close it if you cannot reverse engineer the problem :)
I have no repro steps for you :(

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.93GB free)|
|Process Argv|--crash-reporter-id 144fc73b-ca59-4c79-9dc3-e0102dfb1b0c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.3.1
vscode-pull-request-github|Git|0.25.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
vscode-versionlens|pfl|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833:30267464
vshan820cf:30276953

```

</details>

**Comment by sbatten** [comment]
@ramya-rao-a can you right click both tabs and check to see if you can "Reset Location"?

**Comment by ramya-rao-a** [comment]
Sorry! After clicking on the second tab, it took me to the output pane and changed the title to Output. I cannot reproduce the issue anymore. Feel free to close the issue. Thought I would report regardless if this is related to something else the team is working on

**Comment by sbatten** [comment]
Thanks for reporting, I'll close for now but hopefully remember this case if something similar appears.
