### ISSUE TITLE
Cannot remove debug configuration

### ISSUE THREAD

**Issue by enjustli** [microsoft/vscode#120408]
- VS Code Version:
![image](https://user-images.githubusercontent.com/11613633/113392842-52649d80-93c8-11eb-9b79-5850465ede47.png)

- OS Version: 
    Linux version 5.4.0-67-generic (buildd@lcy01-amd64-010) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))#75~18.04.1-Ubuntu SMP Tue Feb 23 19:17:50 UTC 2021

Steps to Reproduce:

NOTE: I can't reproduce the problem exactly, I use remote ssh to develop code.

1. I manually delete the configuration in the file
2. add some configuration
3. delete old configuration

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/11613633/113392760-35c86580-93c8-11eb-918b-9a25877a1666.png)

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

What I think might be a possible bug is that the dynamic configuration is left in the debug dropdown but can not be launched, though I do not thin this is what you are seeing, since you say that the configuration existed in the `launch.json`.

**Comment by dreznicek** [comment]
I am seeing the same behavior using: 
![image](https://user-images.githubusercontent.com/382124/114089501-d8c32880-987b-11eb-9e2b-d87dded552b3.png)

It doesn't matter if I create a new launch.json or don't even have one at all, like here...

![image](https://user-images.githubusercontent.com/382124/114089805-36f00b80-987c-11eb-86f2-89d9c43a4ee9.png)

when I go to _Run and Debug_ you will see a configuration that I've had in a previous launch.json that I cannot get rid of...

![image](https://user-images.githubusercontent.com/382124/114089952-6868d700-987c-11eb-9363-cedc28d6fb15.png)

I'm on a deadline and can't change much about my vscode environment right now, but wanted to confirm that I'm seeing it as well.

**Comment by enjustli** [comment]
> I can not reproduce this. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
> 
> What I think might be a possible bug is that the dynamic configuration is left in the debug dropdown but can not be launched, though I do not thin this is what you are seeing, since you say that the configuration existed in the `launch.json`.

if I open a new workspace, it won't recur.

**Comment by isidorn** [comment]
Lets close as dup of https://github.com/microsoft/vscode/issues/121148
