### ISSUE TITLE
The Update feature results in linkage and Default App problems

### ISSUE THREAD

**Issue by OutsourcedGuru** [Microsoft/vscode#12045]
- VSCode Version: 1.5.2
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:
1. Open an existing installation of vscode and select the Update link
2. Upon updating, note that the newly-downloaded .app file is within the ~/Downloads folder rather than in Applications, making it not readily available for the Launchpad nor to the Open With... lookup within the Finder application.  This will show (only) the previous version of vscode rather than the freshly-downloaded version.
3. Also note that it is typical to "Keep in Docker" something you use a lot, similar to Windows's "Pin this to Taskbar" feature.  After an update the Docker's location is now for an earlier version, causing problems.

**Comment by joaomoreno** [comment]
@OutsourcedGuru is this #3520?
