### ISSUE TITLE
Windows painting with green stripes.

### ISSUE THREAD

**Issue by bruce-mccorkendale** [microsoft/vscode#120450]
Issue Type: <b>Bug</b>

Not sure how to repro, but I have two main windows open on different workspaces - one a Node.js project, and the other a Rust project - the Rust window's panes are paiting with the green stripes (looks like an old analog TV having signal problems).  I have attached a screenshot.

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (17.63GB free)|
|Process Argv|--crash-reporter-id 09dde8b2-4592-4fce-81cd-5c8489e88f7f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.22.0
cloudformation-yaml-snippets|dst|3.14.0
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.18
json-pretty-printer|eus|1.1.0
code-runner|for|0.11.3
kotlin|fwc|0.2.22
live-html-previewer|hdg|0.3.0
Ionide-fsharp|Ion|5.4.1
csharpextensions|jch|1.3.1
kite|kit|0.142.0
csharpfixformat|Leo|0.0.84
vscode-JS-CSS-HTML-formatter|lon|0.2.3
aws-cli-configure|mar|0.3.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
vs-keybindings|ms-|0.2.0
debugger-for-chrome|msj|4.12.12
vscode-codedeploy|mzi|0.5.3
gradle-language|nac|0.2.3
printcode|nob|3.0.0
fix-json|oli|0.1.2
vscode-yaml|red|0.17.0
vscode-gradle|ric|3.6.1
rust|rus|0.7.8
kotlin-on-vscode|set|0.0.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.3.0
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30265425
pythonvspyt943cf:30280190
openwslfolder:30282073
vscoresta800:30279781
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952

```

</details>

<img width="1159" alt="Screen Shot 2021-04-02 at 3 38 16 PM" src="https://user-images.githubusercontent.com/71354089/113459185-81c7da00-93c9-11eb-914f-74ce86c98610.png">

**Comment by IllusionMH** [comment]
/duplicate #106429

Comments have couple of potential workarounds.

**Comment by bruce-mccorkendale** [comment]
Thanks!
