### ISSUE TITLE
vscode.window.ActiveTextEditor is no longer texteditor

### ISSUE THREAD

**Issue by cedric05** [microsoft/vscode#120526]
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:02:21.560Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-70-generic
Steps to Reproduce:

1. toggle/open output channel, 
2. check `vscode.window.activeTextEditor?.document.fileName!`, its giving `extension-output-#4` or `extension-output-#3`

Does this issue occur when all extensions are disabled?: 
Yes

**Comment by chrislun16** [comment]
Any idea where to find this issue? Would this be achievable by a newcomer?

**Comment by jrieken** [comment]
Output channel windows are also text editors. You can differentiate them by the scheme and the lack of a viewColumn
