### ISSUE TITLE
Changing quick open of group specific editor key shortcuts to non-group specific breaks quick open navigatoin

### ISSUE THREAD

**Issue by jmholla** [microsoft/vscode#120584]
Issue Type: <b>Bug</b>

1. Delete shortcuts for the following:
    * "View: Quick Open Least Recently Used Editor in Group"
    * "View: Quick Open Least Previous Recently Used Editor in Group"
2. Set the following shortcuts:
    * "View: Quick Open Least Recently Used Editor": Ctrl+Shift+Tab
    * "View: Quick Open Least Previous Recently Used Editor": Ctrl+Tab
3. Use one of the above shortcuts.
4. Observe that you cannot navigate the quick open menu with Ctrl+Tab and Ctrl+Shift+Tab

VS Code version: VSCodium 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-04-01T14:57:53.176Z)
OS version: Linux x64 5.4.0-67-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.52GB (0.48GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.10.332292344

</details>

**Comment by TylerLeonhardt** [comment]
@jmholla when you set these shortcuts in step 2, did they have any other existing shortcuts?

![image](https://user-images.githubusercontent.com/2644648/117087982-0463f200-ad06-11eb-9bd7-44d37d00cffa.png)


Also, I don't see `Quick Open Least Previous Recently Used Editor`:
![image](https://user-images.githubusercontent.com/2644648/117088133-6e7c9700-ad06-11eb-8383-49295716cdac.png)

Where is that coming from?
