### ISSUE TITLE
Right-click in file picker crashes vscode

### ISSUE THREAD

**Issue by wntiv-main** [microsoft/vscode#120533]
- VS Code Version: VSCode 1.54.3
- OS Version: Windows 10 Pro 20H2 19042.867 Windows Feature Experience Pack 120.2212.551.0 (no clue what any of that means, but hope it's helpful)

Steps to Reproduce:

1. File > Open Folder...
2. Right-click something

Does this issue occur when all extensions are disabled?: Yes

**Comment by tymsai** [comment]
No my vscode did'nt crash

**Comment by gjsjohnmurray** [comment]
/gifPlease to show us the exact place where a right click triggers your crash. Also one to show what the crash looks like.
