### ISSUE TITLE
BackSpace key is Invalid

### ISSUE THREAD

**Issue by YamingZ** [microsoft/vscode#120509]
Issue Type: <b>Bug</b>

BackSpace key is Invalid in vscode，but in other software ，this key always be ok。

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.80GB free)|
|Process Argv|--crash-reporter-id e9242230-233b-45a6-b8a9-b2a117156246|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
gitlens|eam|11.3.0
vscode-html-css|ecm|1.10.2
code-runner|for|0.11.3
todo-tree|Gru|0.0.209
latex-workshop|Jam|8.16.1
vscode-language-pack-zh-hans|MS-|1.55.2
csharp|ms-|1.23.9
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0-insiders3
debugger-for-chrome|msj|4.12.12
korofileheader|OBK|4.8.5
material-icon-theme|PKi|4.6.0
markdown-preview-enhanced|shd|0.5.17
shader|sle|1.1.5
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes516:30244333
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
pythonvspyt943:30280189
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

If it isn't, see https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Backspace`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`Backspace`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
