### ISSUE TITLE
Add "Reveal in Explorer", "Copy path", etc actions to the context menu of the tabs as well

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#12052]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2012R2

Steps to Reproduce:

Currently the "Reveal in Explorer", "Copy path", etc actions are only shown in the context menu of items in the Explorer sidebar. When I'm not in a workspace I usually have this bar closed to save screenspace, so opening it just to do one of these actions is annoying. It would be nice if all these actions were also present in the context menu of the tabs themselves.

![1](https://cloud.githubusercontent.com/assets/1096010/18534934/d3f00b6a-7aa4-11e6-8d32-0e9e1a2e63be.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11942
