### ISSUE TITLE
Curly braces' position of c code is changed after using 'shift-alt-f' to format the code block.

### ISSUE THREAD

**Issue by aoyulong** [Microsoft/vscode#12053]
- VSCode Version: 1.5.2
- OS Version: win10 64bit.

When I use the 'shift-alt-f' to format the code block I have selected,  the curly braces' position is changed and they aren't on their own lines any more.

The code before formatting:
![image](https://cloud.githubusercontent.com/assets/3069790/18537348/756b0354-7b37-11e6-9558-a8683dfb18ce.png)

The code after formatting:
![image](https://cloud.githubusercontent.com/assets/3069790/18537353/7da92afa-7b37-11e6-8714-115077cfb53b.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
