### ISSUE TITLE
Crostini: can't move files with drag and drop

### ISSUE THREAD

**Issue by alexsapps** [microsoft/vscode#120580]
Issue Type: <b>Bug</b>

Note: My OS is Crostini (Linux on Chrome OS)

To reproduce:
1. Drag file to another folder

File should be moved, but nothing happens. Had to install an extension to move files between folders. (Tried disabling all extensions already.)

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 5.4.74-10576-gb6cc41974db3

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|06/8e (2 x 1607)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|14.21GB (14.19GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 54ba1345-626a-4537-b5f8-59f37c8702e4|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|6.3.2
go|gol|0.23.3
csharp|ms-|1.23.9
cpptools|ms-|1.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
java|red|0.76.0
vscode-fileutils|sle|3.4.5
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by isidorn** [comment]
Yeah we do not support that OS. No plans to tackle this, however I can leave this issue open for now. Thanks

**Comment by alexsapps** [comment]
Thanks!

Also noticed I can't drag/drop to re-order editor tabs, just for the record. (Same thing - I see the drag animation on mousedown but nothing happens on mouseup) May be related.
