### ISSUE TITLE
Is there any shortcuts to switch between editors and the integrated terminal.

### ISSUE THREAD

**Issue by aoyulong** [Microsoft/vscode#12054]
- VSCode Version: 1.5.2
- OS Version: win 10, 64 bit

My qustion is that is there any shortcuts to switch between editors and the integrated terminal? Here I can  only use the CTRL+1, CTRL+2... to switch the open editor tabs.

**Comment by Tyriar** [comment]
ctrl+\` toggles the terminal by default, there is also the `workbench.action.terminal.focus` command which you can add a keybinding for if you just want to focus it.

**Comment by jcrben** [comment]
To clarify since Markdown got in the way, ctrl+backtick: i.e. `ctrl+``` toggles the panel.

However, not sure about switching back to the editor yet.

**Comment by Tyriar** [comment]
If you want ctrl+\` to toggle back and forth, add this to your keybindings.json:

```
{ "key": "ctrl+`",          "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus" },
{ "key": "ctrl+`",          "command": "workbench.action.terminal.focus", "when": "!terminalFocus" },
```

**Comment by ModernWebService** [comment]
Updated question to add to this thread. Is there a way to click between terminals rather than moving the mouse to the selection dropdown. Similar to how iterm allows you to hold cmd+ ( 1, 2, 3, 4, etc) Obviously using cmd and number on vscode doesn't work the terminal, it added splits and filters between left, right and middle.

**Comment by Tyriar** [comment]
@ModernWebService you can add [custom keybindings](https://code.visualstudio.com/docs/getstarted/keybindings) for these:

<img width="680" alt="screen shot 2017-08-16 at 9 41 32 am" src="https://user-images.githubusercontent.com/2193314/29374695-2dbcf386-8267-11e7-9063-6695e36eb579.png">

**Comment by jsta** [comment]
These entries will create RStudio-style `Ctrl 1`/ `Ctrl 2` switching.

```
{ "key": "ctrl+1",          "command": "workbench.action.focusActiveEditorGroup", "when": "terminalFocus" },
{ "key": "ctrl+2", "command": "workbench.action.terminal.focus", "when": "!terminalFocus" },
```

**Comment by eric-burel** [comment]
For our fellow azerty user, `ctrl+7` will be usable instead of `ctrl+`` or `ctrl+è`.
