### ISSUE TITLE
Visual Studio Code icon broken in MacOS spotlight search 

### ISSUE THREAD

**Issue by jota12x** [microsoft/vscode#120525]
### Environment specs
- VS Code Version: 1.55 (latest)
- OS Version: macOS Big Sur

### Steps to Reproduce:

1. Update to the latest stable version (1.55) from some old version (1.3~).

### Screenshots:
![image](https://user-images.githubusercontent.com/6154802/113531321-6811d700-9603-11eb-845f-d0063d28b20d.png)

**Comment by misolori** [comment]
Thanks for reporting, we already have https://github.com/microsoft/vscode/issues/120305 that is covering this so I'll close this as duplicate.
