### ISSUE TITLE
Keywords not recognized after type name declarations in generics, mapped indices in a .ts file in a JS project

### ISSUE THREAD

**Issue by landisdesign** [microsoft/vscode#120530]
Issue Type: <b>Bug</b>

When creating a `.d.ts` file in a JavaScript project to improve Intellisense, keywords are considered errors in generic name declarations and mapping indices. Examples include:

```ts
type Foo<O extends Bar> = { // Error: Parsing error: Unexpected token, expected ","
           ^
```

```ts
type Foo<O> = {
  [K in keyof O]: boolean; // Error: Parsing error: Unexpected token, expected "]"
     ^
```

Currently I have the following jsconfig.json:
```json
{
  "allowJS": true,
  "compilerOptions": {
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true
  }
}
```

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 8|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 63330695-c671-494d-acae-76dedaa0109b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-flow-ide|gca|1.2.0
macros|ged|1.2.1
vscode-nginx-conf-hint|han|0.1.0
vscode-language-babel|mgm|0.0.31
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
errorlens|Phi|1.1.3
scala|sca|0.5.2
markdown-preview-enhanced|shd|0.5.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by mjbvz** [comment]
Works fine for me in normal TS:

![Screen Shot 2021-04-02 at 3 43 01 PM](https://user-images.githubusercontent.com/12821956/113615312-8dedaa80-9608-11eb-842c-343551e878dd.png)

Where are the errors coming from? Please share a screenshot. They are likely from an extension you have installed

**Comment by landisdesign** [comment]
... I completely forgot about needing to update my ESLint config. Thank you for prodding my brain and apologies for wasting your bandwidth!
