### ISSUE TITLE
Custom title bar caption buttons blurry at 4K 175% scaling

### ISSUE THREAD

**Issue by Dynakarp** [microsoft/vscode#120517]
- VS Code Version: 1.55.0
- OS Version: 10.0.20317.1

Steps to Reproduce:

1. Have a 4K display
2. Set Windows scaling to 175%
3. Open Visual Studio Code
4. Look at the title bar caption buttons (with Custom title bar enabled)

Does this issue occur when all extensions are disabled?: Yes

For reference, here is a comparison between VS Code's caption buttons, and caption buttons elsewhere

VS Code:
![image](https://user-images.githubusercontent.com/69023488/113521224-b53b6d80-955d-11eb-9939-3ac0f5f53484.png)

Edge:
![image](https://user-images.githubusercontent.com/69023488/113521241-cf754b80-955d-11eb-94bd-6e62b40f5e1e.png)

UWP App:
![image](https://user-images.githubusercontent.com/69023488/113521251-e2881b80-955d-11eb-9f96-572d496463ec.png)

**Comment by sbatten** [comment]
this will be resolved with https://github.com/microsoft/vscode/issues/127449
