### ISSUE TITLE
Issue VSC Icon appearance

### ISSUE THREAD

**Issue by jaimeviloriogreen** [microsoft/vscode#120555]
The VS Code icon on macOS Big Sur it appear distorted.

![Captura de Pantalla 2021-04-05 a la(s) 10 08 26 a  m](https://user-images.githubusercontent.com/52844268/113582874-e74cde00-95f6-11eb-9dbf-0a65d241d5d9.png)

![Captura de Pantalla 2021-04-05 a la(s) 10 07 29 a  m](https://user-images.githubusercontent.com/52844268/113583039-1f542100-95f7-11eb-88eb-6bfaa3840bfa.png)

**Comment by chungweileong94** [comment]
Yeah, I'm facing the same issue as well.

**Comment by misolori** [comment]
Thanks for reporting, we have an open issue tracking this https://github.com/microsoft/vscode/issues/120305 and will have a fix ready this week. Closing as duplicate.
