### ISSUE TITLE
VSCode's showInputBox is wrongly escaping entities

### ISSUE THREAD

**Issue by mauricioszabo** [microsoft/vscode#120593]
- VS Code Version: 1.55.0-1617120720
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Try to use `vscode.window.showInputBox({prompt: "Watch & go", value: ""})`

Does this issue occur when all extensions are disabled?: Can't reproduce, the only way to have the prompt to appear is by using in an extension

Screenshots:

```js
vscode.window.showInputBox({prompt: "Watch & go", value: ""})
```

Renders:
![image](https://user-images.githubusercontent.com/138037/113635110-687f9180-9646-11eb-995c-dd4cf7f264e9.png)

It's also happening on my Clover package (it's ClojureScript, but translates 1-1 to JS). The code that causes the error is the following:
https://github.com/mauricioszabo/clover/blob/master/src/clover/commands/connection.cljs#L198

```clojure
(defn prompt [prompt placeholder]
  (.. vscode -window (showInputBox #js {:prompt prompt
                                        :value placeholder})))

(prompt "Connect to Clojure: inform <host>:<port>" ...)
```

On version 1.51.1:
![image](https://user-images.githubusercontent.com/138037/113635285-beecd000-9646-11eb-8e4e-914ab5379fb9.png)

On version 1.55.0:
![image](https://user-images.githubusercontent.com/138037/113635305-c6ac7480-9646-11eb-9fda-8ac4c5485888.png)

**Comment by TylerLeonhardt** [comment]
Yep! Looks like a bug to me. It also happens in validation of input.

**Comment by TylerLeonhardt** [comment]
issue description is good enough for verification steps.
