### ISSUE TITLE
The key binding `Ctrl+.` for `editor.action.quickFix` does not work

### ISSUE THREAD

**Issue by iskcal** [microsoft/vscode#120536]
- VS Code Version:  1.55.0
- OS Version: Windows 10 Pro 20H2

Steps to Reproduce:

1. Writing a C# code.
2. I want to press `Ctrl+.` to activate the quick fixes panel, but these is no response.

For example,
![image](https://user-images.githubusercontent.com/11767514/113554828-7d4f2b80-962c-11eb-9d9a-b60622bc1170.png)

When I click on the bulb with the mouse, the panel pops out, but using the key binding `Ctrl+.` cannot.

If I change the keybinding of `editor.action.quickFix` to another one, the key binding can work well. Besides, when setting a key binding, pressing control and dot buttions only shows the control button.

![image](https://user-images.githubusercontent.com/11767514/113555766-06b32d80-962e-11eb-96c9-b5848fd28fcb.png)

The dot key cannot display in the input box when pressing control button.

Does this issue occur when all extensions are disabled?: No, C# extension is necessary. But I think this maybe an issue for vscode, because the combination `Ctrl+.` still cannot be set as a key binding when disabling the extension.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues for advice on how to diagnose keybinding issues.

**Comment by alexdima** [comment]
@iskcal This indicates that `ctrl+.` is not reaching VS Code from the OS. There is nothing we can do on our side, it is possible that the OS is configured to do something on `ctrl+.` or that you have installed some other software or driver that is using `ctrl+.` as a global hotkey.

**Comment by iskcal** [comment]
@alexdima Thanks. From your perspective, I find the default input software of Windows 10 adopts `ctrl+.` as a switch between Chinese and English punctuation. The hotkey can be work properly when disabling the switch.
