### ISSUE TITLE
mac os: terminal invisible text

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode#120594]
Hi,
Since the march update, the text doesn't show on the terminal. It happens on Mac Os Big Sur.
Actually it sort of shows randomly. At first it doesn't show, but i can see the cursor, then if i write more lines, some pieces will be visible, then invisible...
I attach 2 screenshots.

Precision: I haven't set any terminal option on vsc.
Oh and I forgot: If i change the setting about bright characters, it shows on the current terminal, and only for the session.

Regards
![mac-new-terminal](https://user-images.githubusercontent.com/78134277/113638037-3e45c800-9676-11eb-8751-ce7c28ae5a52.png)
![mac-terminal](https://user-images.githubusercontent.com/78134277/113638049-4271e580-9676-11eb-99bc-b1952247eab5.png)

**Comment by meganrogge** [comment]
Does changing the renderer type help?

**Comment by bonjourjoel** [comment]
Oh yes, this is the correct setting! It works with canvas & dom renderers. It doesn't with auto and experimentalWebgl. Thanks. Issue solved on my side.
Regards.
