### ISSUE TITLE
Collapsing a node in a hover placed above the line shouldn't make the hover to close

### ISSUE THREAD

**Issue by olivierr91** [microsoft/vscode#120552]
- VS Code Version: 1.55.0
- OS Version: Windows_NT x64 10.0.19042

When hovering a variable during debug, for example an object or an array, VS code nicely shows a navigable inline tree in a hover. Problem is, when collapsing node, if the hover appears above the line, the popup moves during the collapse, which makes the cursor to go out of the hover and makes the hover disappear. This should be fixed with a small, maybe configurable, delay where the hover  does not disappear when the cursor is out.

Steps to Reproduce:

1. In a TypeScript project, during debug, hover an array or object with nested information. Make the pop-up to appear at the top of the line, by scrolling your code up a bit if necessary.
2. Expand the top node.
3. Collapse the top node.
4. The hover moves back to it's collapsed size and the cursor is out of the hover.
5. Try to move the cursor back into the hover.

Actual results:
1. The hover disappears.

Expected results:
1. The hover shouldn't disappear.

Does this issue occur when all extensions are disabled?: Yes

https://user-images.githubusercontent.com/6403705/113579104-d188ea00-95f1-11eb-8d26-cf733f7e5bb7.mp4

**Comment by isidorn** [comment]
We already had a bit of a delay before and that would actually make the hover hard to get rid off.
Maybe we need a middle ground. Like 100ms timeout.

Let's keep this open for now and I would be open to change this in the near future

**Comment by olivierr91** [comment]
Yes 100-300 ms would be a good timeout. Maybe it should be configurable. There is already a setting that "Controls the delay in milliseconds after which the hover is shown.", it would make sense to have a setting that "Controls the delay in milliseconds after which the hover is hidden."

**Comment by isidorn** [comment]
Nah, I personally dislike setting for tiny things like this. I think we can find a value that works for everyone

**Comment by olivierr91** [comment]
I don't understand why is this out-of-scope? I think you should reconsider this. This is a pretty frustrating usability issue. And it's a quick fix you just have to change a number in the code for the timeout.
