### ISSUE TITLE
Excluded folders in "peek" popup

### ISSUE THREAD

**Issue by nunoperalta** [microsoft/vscode#120528]
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Does this issue occur when all extensions are disabled?: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (4.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

---

I have these in the workspace settings:

```
		"files.watcherExclude": {
			"**/.git/**": true,
			"**/.svn/**": true,
			"**/build/**": true,
			"**/node_modules/**": true,
			"**/vendor/**": true
		},
		"files.exclude": {
			"**/.git/**": true,
			"**/.svn/**": true,
			"**/build/**": true,
			"**/node_modules/**": true
			// "**/vendor/**": true - don't exclude this
		},
		"intelephense.rename.exclude": [
			"**/.git/**",
			"**/.svn/**",
			"**/build/**",
			"**/node_modules/**",
			"**/vendor/**"
		],
		"intelephense.files.exclude": [
			"**/.git/**",
			"**/.svn/**",
			"**/build/**",
			"**/node_modules/**"
			// "**/vendor/**" - don't exclude this
		],
		"search.exclude": {
			"**/.git/**": true,
			"**/.svn/**": true,
			"**/node_modules/**": true,
			"**/build/**": true,
			"**/vendor/**": true,
			"**/pkgs/**": true
		},
```

However, when I try to "go to definition" of a JavaScript function, I always see the "peek" popup with suggestions from the "build" folder:

![image](https://user-images.githubusercontent.com/487079/113536524-3d595b80-95ce-11eb-9cdc-3e1dd1324958.png)

I have tested opening VSCode with all extensions disabled, and this still happens.

Just in case, I also tried to "clear recently opened" files.

![image](https://user-images.githubusercontent.com/487079/113536615-65e15580-95ce-11eb-9fab-c6b00527dfa1.png)

**Comment by mjbvz** [comment]
You need to exclude these files from your `jsconfig` or `tsconfig` project as well

Use the `excludes` section for this: https://code.visualstudio.com/docs/languages/jsconfig#_using-the-exclude-property
