### ISSUE TITLE
cant run the app from within the Applications folder on my Mac

### ISSUE THREAD

**Issue by dreed47** [Microsoft/vscode#1205]
vscode Version 0.10.3 (0.10.3)  Mac OS version 10.11.2

**Comment by vtbassmatt** [comment]
I'm having the same issue - I get 'The application "Visual Studio Code" can't be opened.'. From a command prompt, I can run /Applications/Visual Studio Code/Contents/MacOS/Electron just fine. There's no obvious 'mark of the web'-style blocker. Right-clicking the icon gives the usual "Open" and "Show package contents" options. This is a 2012 Retina MacBok Pro running 10.11.1; VS Code 0.10.3.

For what it's worth, I had a previous version of Code on this machine. When I ran it, it said it was too old to auto-update and helped me download the latest. When that didn't work, I blew it away and re-downloaded the zip from visualstudio.com. Same problem.

**Comment by vtbassmatt** [comment]
Further notes: From Finder, I'm able to run the Electron executable. The first time I did so, I got a Gatekeeper (or whatever Apple calls that tech now) prompt and authorized it. I still cannot simply double-click the VS Code icon, though.

**Comment by vtbassmatt** [comment]
OK, I was able to finally fix this. From Terminal, running "open -b com.microsoft.VSCode" somehow went down a different launch path which triggered the GUI Gatekeeper warning. Now I can run VS Code by simply double-clicking the icon in Applications. Probably a bug on Apple's side, but maybe there's something wrong with your code-signing or some other piece of security infrastructure?

**Comment by joaomoreno** [comment]
Attributing this to Gatekeeper.
