### ISSUE TITLE
`vscode-windows-ca-certs` seems no longer being used

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120546]
![image](https://user-images.githubusercontent.com/900690/113567529-140cef80-960f-11eb-96d2-68422173426d.png)

**Comment by rzhao271** [comment]
`crypt32.node` under `vscode-windows-ca-certs` is still appearing under the extensionHost process when using Windows Process Explorer.
I'm wondering whether it's still being loaded just because of the tests?

**Comment by bpasero** [comment]
Maybe it is now a dependency of one of our top level modules?

**Comment by chrmarti** [comment]
`vscode-windows-ca-certs` is used by `vscode-proxy-agent`. I need to move the dependency there.

**Comment by bpasero** [comment]
And `vscode-proxy-agent` only exists on the node.js layer right? Or where is that being used?

**Comment by chrmarti** [comment]
That is used in the extension host to transparently add proxy support to `http` and `https` built-in modules.

**Comment by chrmarti** [comment]
Fixing with vscode-proxy-agent 0.10.0. Keeping the test in nativeModules.test.ts to not loose test coverage.
