### ISSUE TITLE
Also prepend closed files to the "Open Recent" list as they're closed

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#12050]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2012R2

Steps to Reproduce:
1. Create a new file, save it as test.txt and close the tab.
2. Look in `File -> Open Recent` - test.txt is not there.

Similarly
1. Open files foo.txt, bar.txt, baz.txt
2. Close foo.txt
3. Look in `File -> Open Recent` - foo.txt is not at the top of the list.

This behavior is present atleast in NPP, and is very useful. Say I have four or five files that I've had open for days, so they've been pushed out of the "Open Recent" list. Now if I close them but then realize I need one of them back, there is no way to reopen it except the long way of "Open File..."

Note that "Reopen closed editor" is not a good solution because the file I want to reopen may not be the last closed file, and also because this menu option gives no indication which file it's going to open when I click it anyway (maybe that's another bug).

**Comment by michaeljota** [comment]
I think this should not be listed in the same `"Open Recent..."` menu, but one for files only. Also, it would be great if it can be done with a keybinding, I'm thinking `ctrl+shift+t` here. ;)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by michaeljota** [comment]
I understand that the number of issues in this repo are growing too fast, and it's perfectly acceptable to close those that will not get any attention soon, but maybe put them with a label or a separate project to not forget about them would be nice. Thanks! :D
