### ISSUE TITLE
Capitalizing File

### ISSUE THREAD

**Issue by harryalbert** [microsoft/vscode#120554]
Issue Type: <b>Bug</b>

Create a file with a non-capital first letter (ex. "settingsButton.js").  Open the file in vscode.  Now, rename the file within vscode, now capitalizing the first letter ("settingsButton.js" -> "SettingsButton.js").  Vscode will now say that there is no file with the name you are trying to open.  I'm guessing this is because vscode does not store files as case specific, which seems like a larger issue.  Thanks!

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 18.7.0

**Comment by harryalbert** [comment]
Hey, here's a gif of the problem, hope this helps.
![vsCodeGlitch](https://user-images.githubusercontent.com/65182701/114415307-918baf00-9b7d-11eb-8100-652007a4a57d.gif)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
