### ISSUE TITLE
Clone Repository button doesn't work

### ISSUE THREAD

**Issue by tqacyp** [microsoft/vscode#120557]
- VS Code Version:March 2021 (version 1.55)
- OS Version: Windows 10.0.19043.906

The "Clone repository" button is OK when language is English, but it doesn't work when language is Chinese.
![English.png](https://image.kysic.com.cn/89f87bd763971bd7ed92b91058772916/426d586d41d15.png)  
![Chinese.png](https://image.kysic.com.cn/f5551da9a96120d3be722156da1f1ccc/885d6198e7f98.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by v-mholloway** [comment]
@tqacyp could you sent on screen shots again if this still persists?

**Comment by tqacyp** [comment]
It's now OK.

[![4R8dpQ.png](https://z3.ax1x.com/2021/09/27/4R8dpQ.png)](https://imgtu.com/i/4R8dpQ)

**Comment by v-mholloway** [comment]
closing as issue no longer persists
