### ISSUE TITLE
Unable to update VSCode Exploration to the march update. Its stuck at the January Update

### ISSUE THREAD

**Issue by KittyX29** [microsoft/vscode#120523]
Unable to update VSCode Exploration to the march update. Its stuck at the January 2021 Update. The logo is also not changing. 

Device : M1 MAC, BIG SUR 11.2.3

Screenshots : 

![image](https://user-images.githubusercontent.com/81065901/113530496-d2b31a80-95e3-11eb-84c6-745c57f6cc4d.png)

![image](https://user-images.githubusercontent.com/81065901/113530528-e3639080-95e3-11eb-94dd-d2dd0a4f0263.png)

**Comment by KittyX29** [comment]
![image](https://user-images.githubusercontent.com/81065901/113530567-fd9d6e80-95e3-11eb-9d09-dd702c18d2ed.png)

**Comment by KittyX29** [comment]
Where can i find the installer for the MArch 2021 update?

**Comment by deepak1556** [comment]
New updates have been released, also any reason you are using exploration instead of insiders https://code.visualstudio.com/insiders ?
