### ISSUE TITLE
Duplicated Cursor in Debug Mode

### ISSUE THREAD

**Issue by cvcore** [microsoft/vscode#120518]
- VS Code Version: 1.56.0-insider
- Commit: 550035808407c15252e581e8abe1b820b9d311ee
- Electron: 11.4.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Darwin arm64 20.3.0

Date: 2021-04-02T05:23:43.134Z

Here you can find a video where the bug occur:

https://imgur.com/01EGWC8

Steps to Reproduce:

1. Set up a breakpoint in a python file
2. Run debug

Does this issue occur when all extensions are disabled?: Yes/No
Can't launch debug in this case, because python extension is required.

**Comment by isidorn** [comment]
That is not a cursor, but an inline indicator where the stop event happened.
However pushed a heuristic to only render it when the column is defined and > 1
