### ISSUE TITLE
Intellisense is not working very well

### ISSUE THREAD

**Issue by RpxdYTX** [microsoft/vscode#120549]
Intellisense only show snippets sometimes when i try programming on it, it doesn't show everything based on the letter and current situation like Visual Studio does, like when i try to type things such as "Console" it does not appear, the only things intellisense want to appear are things like "try-catch" or "for" (curly brackets gang) and other things that i already used, also the icons of classes, methods and fields don't show up (just like they don't appear)

Note: this might be duped from other issues, however it is still a recent issue, and i searched into other forums like stackoverflow but nothing fixed here, so i'll thank if someone help me.

- VS Code Version: 1.55.0
- OS Version: Windows 7 SP1 Professional

Steps to Reproduce:

1. idk if it is just for me, but just entering in vscode

Does this issue occur when all extensions are disabled?: Yes/No = Yes

**Comment by gjsjohnmurray** [comment]
What language is the file? Look at the indicator near the right end of the status bar.

**Comment by RpxdYTX** [comment]
is a .cs file (c#- C-Sharp language)

**Comment by RpxdYTX** [comment]
but the only extension i was with was the C# one every other i completely uninstalled

**Comment by jrieken** [comment]
Sure, but the c# extension is tracked in another repo: https://github.com/OmniSharp/omnisharp-vscode/issues

**Comment by RpxdYTX** [comment]
oh ok
