### ISSUE TITLE
intellisense is bit effy

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#120543]
Issue Type: <b>Bug</b>

i am observing intellisense is not working in a expected way.
when i start typing i see spelled words first, then snippets and then 'starred suggestions" and then normal code suggestions.
i think the stars should go first and then normal code/snippets.

till a few days ago the intellisense worked as i expected. now i feel something is missing.

note: i have VS intellicode and VS intellicode insiders extensions and also code spell checker extension installed. i disabled them (individually and collectively) to verify the issue and can see the issue after disabling these extensions.

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:15:44.248Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.77GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.9
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.1
vscode-pull-request-github|Git|0.25.0
output-colorizer|IBM|0.1.2
vscode-dotnet-runtime|ms-|1.0.0
github-issues-prs|ms-|0.9.3
typescript-javascript-grammar|ms-|0.0.55
vscode-js-profile-flame|ms-|0.0.14
vscode-typescript-next|ms-|4.3.20210404
cordova-tools|msj|2.2.0
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1
fabric8-analytics|red|0.3.2
vscode-commons|red|0.0.4
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
swdc-vscode|sof|2.5.11
sonarlint-vscode|Son|1.21.0
code-spell-checker|str|1.10.2
vscode-stylelint|sty|0.86.0
vscodeintellicode|Vis|1.2.12
vscodeintellicode-insiders|Vis|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoc:30278405
vscoresta800:30283263
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebutton:30280634
vshan820cf:30276953
pythondataviewer:30283452

```

</details>

**Comment by gjsjohnmurray** [comment]
I assume 'starred suggestions' are contributed by an extension and don't appear after you run the command to reload with all extensions disabled. In which case please report the issue to the extension developer.
