### ISSUE TITLE
windows-process-tree needs to be context-aware

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#120570]
See https://github.com/microsoft/vscode/issues/120431#issuecomment-812875438

We need to make https://github.com/microsoft/vscode-windows-process-tree context-aware.

**Comment by rzhao271** [comment]
To verify: code review, or clone the windows-process-tree repo and ensure tests pass locally.

**Comment by bpasero** [comment]
@rzhao271 see https://github.com/microsoft/vscode-windows-process-tree/pull/31 which is a PR to add automated GH action to run tests on Windows.

**Comment by bpasero** [comment]
Oh, only now I saw appveyor was already setup to run the tests, but then I think this is verified?

**Comment by rzhao271** [comment]
Yeah it's a weird case. The CI did already verify it, then, and the PR was reviewed anyway.
Marking this as verified, especially since only the ptyHost (under the shared process) and main process use this module, and neither of them are affected by the process render reuse branch 🤷
