### ISSUE TITLE
Debug Call Stack inline step-in/over/out commands are always enabled

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#120578]
Issue Type: <b>Bug</b>

Compare the appearance of the step-in/over/out buttons on the main debug toolbar with the same buttons that appear in the call stack. 

![image](https://user-images.githubusercontent.com/6726799/113610394-f78baa00-9644-11eb-9019-ab4f82f7c4f8.png)

The ones in the call stack are enabled even when execution hasn't been suspended.

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:15:44.248Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
Great catch, and thanks for the fix 👏
