### ISSUE TITLE
Add ability to reverse to icon to old form on MacOS

### ISSUE THREAD

**Issue by nk-dm** [microsoft/vscode#120507]
Recently, the VSCode icon was updated for MacOS to be consistent with the new BigSur-Style.
While this may be good for most, as it doesn't stand out, it is actually bad for a fair share of people -- The people who still use Catalina (or earlier). And, before someone says "Just Update": Many people can't. It's been an issue for some time now and it has not been resolved yet for many. We just can't Update.
Please add an option to reverse the VSCode icon with the transparent background.

**Comment by misolori** [comment]
Unfortunately this is not possible, please see https://github.com/microsoft/vscode/issues/86756 as any updates the user makes will be overridden on the next update.

**Comment by elgandoz** [comment]
> Recently, the VSCode icon was updated for MacOS to be consistent with the new BigSur-Style.
> While this may be good for most, as it doesn't stand out, it is actually bad for a fair share of people -- The people who still use Catalina (or earlier). And, before someone says "Just Update": Many people can't. It's been an issue for some time now and it has not been resolved yet for many. We just can't Update.
> Please add an option to reverse the VSCode icon with the transparent background.

You can easily override any app icons on MacOS: https://9to5mac.com/2020/12/01/change-mac-icons/
Just update!

**Comment by misolori** [comment]
Also please see https://github.com/microsoft/vscode/issues/120604 if you want to configure the app icon

**Comment by vasilenka** [comment]
@misolori where can I get the previous icon of Insiders for macOS, please?
I can't find it
I've tried converting from .png, but it doesn't look as good as the previous icon
