### ISSUE TITLE
Being able to change keyboard shortcut to run commands in the console of the interactive window 

### ISSUE THREAD

**Issue by GitHunter0** [microsoft/vscode#120511]
Hi folks, I hope you are doing well.

So, my issue is that I cannot find a way to change the keyboard shortcut to run commands in the console of the interactive window (see picture below)  

![image](https://user-images.githubusercontent.com/26294221/113515208-726f9a80-9549-11eb-9633-2d978001e5bc.png)

I would like to modify from `Shift-Enter` to just `Enter` (the standard for terminals and consoles), and use `Shift-Enter` to insert line break. This is the standard for several message apps, precisely because it is quicker and simpler.

Is there a way to accomplish that?  

Thank you

**Comment by andycraig** [comment]
This is for the Python Interactive Window, right? There is an open issue for this over at the Jupyter extension repo: https://github.com/microsoft/vscode-jupyter/issues/4073

**Comment by GitHunter0** [comment]
Right @andycraig . Thanks man, I will close this one then.
