### ISSUE TITLE
Show errors in the files explorer

### ISSUE THREAD

**Issue by mbeckenbach** [Microsoft/vscode#12059]
- VSCode Version: 1.5.2
- OS Version: Win10

Steps to Reproduce:

1. create a compile time error in some file
2. watch the file list

It would be cool if the file list on the left would show errors inside ts or cs files. Very helpful when refactoring or updating libraries with breaking changes.

**Comment by mbeckenbach** [comment]
my full vs does that. not sure if it's an extension or by default

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/782
