### ISSUE TITLE
show color picker for id of a div in object

### ISSUE THREAD

**Issue by pooooriya** [microsoft/vscode#120532]
Hello Guys , Thanks for This Cool Editor I have an issue :
Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1.create object like image and then copy past it into your codes
2.its auto create pallate for it allthough its a id of div not color

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/65160744/113543440-a73c2a00-95fb-11eb-83c0-080d7f739de2.png)

**Comment by gjsjohnmurray** [comment]
Please paste your object as copyable text.

**Comment by aeschli** [comment]
It is just an updating issue? Or does the color indicator stay?

**Comment by pooooriya** [comment]
> Please paste your object as copyable text.

I dont have access to my code , I,ve Just Take Shot From It

**Comment by pooooriya** [comment]
> It is just an updating issue? Or does the color indicator stay?

its show color picker and you can change 5 or 6 first charecter if you select color from color picker allthough its just a normal string and its for Id of div not a color

**Comment by mjbvz** [comment]
We don't have built-in color pickers in JavaScript files so this is very likely caused by an extension
