### ISSUE TITLE
TQDM output looks odd after stderr stdout change

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#120577]
@IanMatthewHuff commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5299)

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a1934967-be11-416b-9d89-3d563a7facf5)

With the new change to vscode handling stderr and stdout differently TQDM now looks funny. Per Don it is writing to stderr, so the red is expected. However the blue elements might either be writing to stdout or explicitly colored blue. Should investigate.

---

@greazer commented on [Thu Mar 25 2021](https://github.com/microsoft/vscode-jupyter/issues/5299#issuecomment-807444249)

Seems more likely to be a core VS Code problem.

---

@DonJayamanne commented on [Mon Apr 05 2021](https://github.com/microsoft/vscode-jupyter/issues/5299#issuecomment-813558489)

```pyhton
import sys
sys.stdout.write('stdout')
sys.stderr.write('stderr')
sys.stdout.flush()
sys.stderr.flush()
```

Here's the expected output from classic Jupyter:
<img width="606" alt="Screen Shot 2021-04-05 at 11 24 17" src="https://user-images.githubusercontent.com/1948812/113610065-7e1e9800-9601-11eb-961e-e0ea9cab15e0.png">

Requested change = Set background color instead of changing the foreground color.
Else it looks weird.

**Comment by DonJayamanne** [comment]
@jrieken @rebornix /cc

**Comment by rebornix** [comment]
I'm not seeing the weird color anymore, for changing the background, let's discuss in June.

![image](https://user-images.githubusercontent.com/876920/120716969-a4cf4280-c47b-11eb-9374-e519c46bded3.png)

**Comment by greazer** [comment]
Yep, seems to be working fine for me too.

**Comment by rebornix** [comment]
closing for now.
