### ISSUE TITLE
Replace "marching ants" with shimmer/skeleton view when loading extension search results.

### ISSUE THREAD

**Issue by clocky** [microsoft/vscode#120589]
When scrolling through unloaded search results from a Marketplace search, the "marching ants" pattern is shown on unloaded items, creating a peculiar visual effect. (This is likely to be more noticeable on slower connections.)

![marching-ants](https://user-images.githubusercontent.com/1550587/113629341-2ab94380-961b-11eb-8112-478ffa24ada0.gif)

As an alternate solution, it may be less visually distracting to use a "skeleton" or "shimmer" object as a placeholder until the metadata is returned and loaded, e.g.:

![skeleton](https://user-images.githubusercontent.com/1550587/113629788-bc28b580-961b-11eb-97b5-a06bfde269e3.png)

cc @misolori

**Comment by misolori** [comment]
@sandy081 thoughts on updating this view?

**Comment by sandy081** [comment]
👍 for change if it improves the experience.
