### ISSUE TITLE
"Always on top" rules for commonly used filenames

### ISSUE THREAD

**Issue by jamietdavidson** [microsoft/vscode#120534]
This issue is a duplicate of https://github.com/Microsoft/vscode/issues/49773. I would have commented on it, but it was closed and not open for further discussion.

I frequently have `index.tsx` files in my project. None of the default sort options for the file tree allow these to always be at the top. Additionally, the file tree does not seem to make any distinction between uppercase and lowercase files (a solution I could work with). As a result, I am constantly searching for my `index.tsx` file in my file tree.

I have spent over an hour looking for a solution. I am about to throw in the towel, and restructure my project to allow for something that works better with this limitation, but that does not feel like the right solution to me.

If there is an extension that solves this problem that doesn't rely on custom icons (as all my files are `.tsx`), please point me to it, but I cannot find anything of the sort.

**Comment by gjsjohnmurray** [comment]
Maybe try some of the extensions that implement favorites.

**Comment by jamietdavidson** [comment]
Hi @gjsjohnmurray, 

Off the top of your head, do you know of any extensions that accomplish this/ could you link them to me? I can't seem to find any in the sea of options available. Perhaps it would help others who stumble into the same problem too.

Thanks!
