### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lottarantala** [microsoft/vscode#120502]
Issue Type: <b>Performance Issue</b>

I am loading a bunch of pictures for my game using os.path.join. It works in cmd just fine, but in Visual Studio Code I get a FileNotFoundError even though the pictures are in the same directory as the code file

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (1.65GB free)|
|Process Argv|C:\\Users\\lotta\\Desktop\\matopeli\\matopeli.py --crash-reporter-id f4cb427a-66f4-42f5-8b75-c22071ffbace|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 15936	code main
    0	    39	  4396	   utility
    0	    89	  9044	   shared-process
    0	    68	 16708	     ptyHost
    0	     6	 18396	       console-window-host (Windows internal process)
    0	    69	 18732	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	   185	  9408	   window (matopeli.py - Visual Studio Code)
    0	   215	  3468	     extensionHost
    0	    44	 17916	       "C:\Program Files\Python38\python.exe" c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\pyvsc-run-isolated.py c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\completion.py
    0	    10	 10992	         console-window-host (Windows internal process)
    0	    27	 16660	         "C:\Program Files\Python38\python.exe" c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python 3.8.1
    0	    11	 14520	           console-window-host (Windows internal process)
    0	    27	 18692	         "C:\Program Files\Python38\python.exe" c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python\jedi\inference\compiled\subprocess\__main__.py c:\Users\lotta\.vscode\extensions\ms-python.python-2021.3.680753044\pythonFiles\lib\python 3.8.1
    0	    10	 11020	           console-window-host (Windows internal process)
    0	    85	 15512	   window (Issue Reporter)
    0	    23	 19972	   crashpad-handler
    0	   198	 20036	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
pythonvspyt943:30280189
openwslfolder:30282073
vscoresta800:30284044
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by chrmarti** [comment]
Try checking what `process.cwd()` is, relative paths are resolved against that or use absolute paths to your files.
