### ISSUE TITLE
MacOS Full Screen Mode - Menu Awareness

### ISSUE THREAD

**Issue by jmbldwn** [microsoft/vscode#120512]
VSCode's full screen mode on MacOS has one annoying flaw.  When you move your mouse to the top of the screen to click on  a toolbar button or window tab, it's easy to go a little too far and trigger MacOS' menu bar to slide down over the VSCode window, which forces you to move down and back up to get to the toolbar or tab you were going for.  This happens a lot to me when debugging and the menu bar occludes the debug controls.  Sometimes it takes a few swings at it before I can hit the toolbar without causing the menu bar to slide down.

For example, before the menu slides down:
<img width="471" alt="Screen Shot 2021-04-04 at 10 48 49 AM" src="https://user-images.githubusercontent.com/855911/113517322-10f10100-9534-11eb-9381-84a41920a8a5.png">
and after:
<img width="528" alt="Screen Shot 2021-04-04 at 10 49 01 AM" src="https://user-images.githubusercontent.com/855911/113517321-0fbfd400-9534-11eb-96db-9d880bbc91ad.png">

Other mac apps like mail handle this a little differently.  In Mail, the application toolbar slides down with the menu bar when it appears, so if i do accidentally pull down the menu, I can easily course-correct to hit the toolbar button I am going for.

Here's the Mail toolbar before the menu slides down:
<img width="580" alt="Screen Shot 2021-04-04 at 10 56 22 AM" src="https://user-images.githubusercontent.com/855911/113517402-907ed000-9534-11eb-8377-ba97b4d696f6.png">
And after:  you see the toolbar is basically attached to the bottom of the menu bar.
<img width="550" alt="Screen Shot 2021-04-04 at 10 56 36 AM" src="https://user-images.githubusercontent.com/855911/113517400-8f4da300-9534-11eb-9ecf-a8bac265bb7d.png">

It would be great to make VSCode aware of this and have the toolbars at the top slide down with the menu bar.

**Comment by sbatten** [comment]
@deepak1556 is this something we can control with electron?

**Comment by deepak1556** [comment]
Fullscreen menu behavior cannot be controlled via the runtime, closing as not actionable.
