### ISSUE TITLE
Debugging Protractor tests stopped working on 1.55 VSC version

### ISSUE THREAD

**Issue by sebaKwiat** [microsoft/vscode#120539]
Issue Type: <b>Bug</b>

I used to debug protractor tests by adding debugger; keyword then VS Code used to stop at that line.
It stopped to work on 1.55 VSC version, when i reverted back to previous version it started to work again.
Below is my configuration:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "type": "node",
            "request": "launch",
            "name": "Web UI Automation",
            "program": "${workspaceFolder}/node_modules/protractor/bin/protractor",
            "args":[
                "${workspaceFolder}/tmp/protractor.conf.js"
            ],
            // "protocol": "inspector",
            "preLaunchTask": "tsc: build - tsconfig.json",
            "outFiles": [
                "${workspaceFolder}/tmp/**/*.js"
            ],
            "console": "integratedTerminal",
            "trace": true,           

        }
    ]
}

VS Code version: Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:38:31.419Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.54GB free)|
|Process Argv|--crash-reporter-id c3a0a34e-47ea-428d-a35e-1c5a51b66c58|
|Screen Reader|no|
|VM|50%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30283453

```

</details>

**Comment by connor4312** [comment]
Are you using WSL2? If so, you may be hitting https://github.com/microsoft/vscode/issues/120227#issuecomment-812007561. Otherwise, please collect logs using these instructions:

/jsDebugLogs
