### ISSUE TITLE
Add TerminalOptions.icon API to support tabs in terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120538]
https://github.com/microsoft/vscode/issues/120241

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/16cff9cff93539b87a0a16ccc8dd09ddf542e7d5/src/vs/vscode.d.ts#L9165

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/16cff9cff93539b87a0a16ccc8dd09ddf542e7d5/src/vs/vscode.d.ts#L7436

**Comment by Tyriar** [comment]
New proposal:

```ts
interface TerminalOptions {
  iconPath?: Uri | { light: Uri; dark: Uri } | ThemeIcon;
}
```

**Comment by Tyriar** [comment]
We should also add it to `ExtensionTerminalOptions`
