### ISSUE TITLE
[Suggestion] Markdown: Indentation inside code blocks should not affect indentation detection for the rest of the document

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/vscode#12051]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2012R2

Steps to Reproduce:
1. Set `editor.tabSize` to `4` and `editor.detectIndentation` to `true`.
2. Create a markdown file with the following contents:
   
   ```
   asdf
       qwer
   
   ***
   asdf
     qwer
   ***
   ```
   
   Replace the \* with markdown backticks so that the second `asdf` and `qwer` are in a code block.
   
   To clarify, the `qwer` outside the code block is indented by a tab character, and the `qwer` inside the code block is indented by 2 spaces.
3. Close and reopen the file to force VSCode to re-render it.
4. The tab that indents the first `qwer` (the one outside the code block) is rendered as two columns wide instead of four columns as the setting specifies. Also, if I add new lines and indent them with <kbd>Tab</kbd> they'll be indented by two spaces, not even a tab.

I hit this while writing a document that embeds code snippets from various locations, and some of those snippets use two spaces for indentation. I want to maintain the original indentation since it's significant, but I also don't want the rest of the document to be affected by it.

**Comment by jmlane** [comment]
In #7682 you can see how this behaviour came to pass.

For what it's worth, I would not expect my indentation preferences to change the character the tab key returns to the editor, only my line indentation characters. This has implications beyond markdown, but it is certainly important for the formatting in this file format.
