### ISSUE TITLE
Improving single line comments: Indent //

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#120568]
I am using the following comment settings:
"editor.comments.ignoreEmptyLines": false,
"editor.comments.insertSpace": true,

Atom:
![image](https://user-images.githubusercontent.com/75433721/113602564-f66e7300-966c-11eb-8884-9fd81005d6af.png)

Vs code:
![image](https://user-images.githubusercontent.com/75433721/113602685-19008c00-966d-11eb-95ff-0b2e5395156d.png)

I wanted the commenting result to be like in Atom.

**Comment by ArturoDent** [comment]
Your two pictures look identical to me.

**Comment by Jaeiya** [comment]
@ArturoDent Atom indents the comments, while vscode does not.

**Comment by AlexDev2020** [comment]
I really dislike the behavior of vs code. I expect there to be a line indent before the comment followed by a comment character and a space, but I get a comment character, a space and a line indent, which in turn looks bad. Also note the selecting of the text after inserting comments.

**Comment by AlexDev2020** [comment]
Here's another example.

Atom:
![image](https://user-images.githubusercontent.com/75433721/113752630-5fbab880-9737-11eb-8aae-9b85ff64f726.png)

Vs code:
![image](https://user-images.githubusercontent.com/75433721/113752776-8d076680-9737-11eb-8bf4-3b0c27da0dde.png)

**Comment by AlexDev2020** [comment]
Hi. There is progress in this task, otherwise it is not comfortable to use comments
