### ISSUE TITLE
New cells are created in the wrong Notebook document

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#120641]
- VS Code Version: latest Stable & insiders
- OS Version: Mac

Steps to Reproduce:

1. Install jupyter extension
2. install kusto notebook extension 
3. Open jupyter notebook
4. open a kusto notebook on the side
5. set focus to jupyter notebook
6. Click on add code/markdown cell in kusto notebook & watch how cells are created in the other notebook

![wrongNb](https://user-images.githubusercontent.com/1948812/113730628-e7a7b080-96ac-11eb-862a-624fa40d831c.gif)

@rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by rebornix** [comment]
fixed via https://github.com/microsoft/vscode/commit/3d6f3002545c224fd8c6b34f872256d128c9b3ad
