### ISSUE TITLE
Settings option to disable comment continuation

### ISSUE THREAD

**Issue by armandsLa** [microsoft/vscode#120697]
Recently a comment continuation feature was added, but without a way to disable it. It's a great feature, but it's not for everyone. Please consider adding a setting option to disable it.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Could you please describe which comments you are talking about? Screenshot will be helpful.

**Comment by DJSL1NKY** [comment]
@IllusionMH I have the same Issue/Problem.

For clarification, with comment I mean "//" before the Code. For example` // if (1 == 1)`
I use a Mac and when i want to comment out a Line, i push following keys "command+shift+7(/)" to comment out the Line. Before the recent Update, when i pressed the Comment out keys and then the Enter key i can normally type, code in the new line without a comment, but now (after the recent Update), when i press enter at the line i commented out some code the new  Line will be also commented out.

Is there any Setting to disable these Feature?

**Comment by armandsLa** [comment]
I'm talking about two forward slash comments - `//`

I've noticed that this comment continuation doesn't happen for every language.

Comment continued with Dart:
<img width="611" alt="comment_dart" src="https://user-images.githubusercontent.com/6855713/114146572-6ce6cb80-9920-11eb-82ef-208062934b83.png">

Comment didn't continue with Swift:
<img width="586" alt="comment_swift" src="https://user-images.githubusercontent.com/6855713/114146801-b2a39400-9920-11eb-8428-fa9635a193fc.png">

**Comment by yume-chan** [comment]
@armandsLa Thanks for the hint, I found https://dartcode.org/releases/v3-21/#editor, Dart-Code/Dart-Code#3203 and Dart-Code/Dart-Code#3248

**Comment by IllusionMH** [comment]
Thanks for clarifications about languages and thanks you @yume-chan for nice find.

Looks like this one has nothint to do with editor itself.
/causedByExtension

@DJSL1NKY if you have this issue not with Dart extension - try to reproduce it with all extensions disabled (<kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`) and then open new issue with details.
