### ISSUE TITLE
Don't open ignored files in the Explorer 

### ISSUE THREAD

**Issue by alexkreidler** [microsoft/vscode#120679]
I often use Go to Type Definition to dive into a file that's in an ignored directory (e.g. `node_modules` or `$GOPATH/pkg/mod`).

It would be great if when these files are opened they are **not selected or focused in the Explorer**, because then the ignored parent folder gets expanded, which interrupts the editing workflow (e.g. returning to other files).

This should be probably be configurable.

Thanks!

**Comment by gjsjohnmurray** [comment]
See also #81236 and #56063

**Comment by alexkreidler** [comment]
Ah, I knew this might have already been discussed. Thanks for linking those here.

I'll also link to #38878 which is about hiding excluded folders from the Explorer tree more generally.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks
