### ISSUE TITLE
Do not hide markdown cells when it's out of viewport

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120672]
Right now the visibility of markdown cells are set to hidden when it's scrolled out of the viewport. Maybe we can just keep it as is if it's not folded or deleted, otherwise when we are scrolling fast, we can see some blank markdown cells as they are hidden and the requests to change them to `visible` are not applied yet

<img width="548" alt="image" src="https://user-images.githubusercontent.com/876920/113789857-dbdfdc80-96f4-11eb-9595-935f863311a8.png">

**Comment by mjbvz** [comment]
I believe this is already happening. We only hide the previews now when you fold cells
