### ISSUE TITLE
Source Control Malfunction

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#120692]
Issue Type: <b>Bug</b>

I have opened a folder, and it is *NOT* a git repository. Even so, Source Control seems active from my last opened folder, which was a repository. When I run 
```
git init
```
and make some changes and stage and commit them, source control is not updated, it continues to show the changes before the commit

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:15:44.248Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|5.95GB (0.88GB free)|
|Process Argv|D:\\Python\\Django-Todo-App --crash-reporter-id bfffbe94-005d-491f-a5cd-cca13086bd12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|1.4.0
path-intellisense|chr|2.3.0
vscode-html-css|ecm|1.10.2
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.0
kite|kit|0.142.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.6.718745073
cpptools|ms-|1.2.2
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.6.0
java|red|0.76.0
vscodeintellicode|Vis|1.2.12
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vim|vsc|1.19.3
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwsldoc:30278403
vscoresta800:30283263
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820cf:30276953
pythondataviewer:30283452

```

</details>

**Comment by Satwik29** [comment]
This could also be a performance issue, so I will have to see about that

**Comment by ashiyo** [comment]
@eamodio @Satwik29 , I'm facing the same issue. https://stackoverflow.com/questions/66980159/vscode-not-showing-changes-in-source-control , Source control is not updating changes made. I'm on version 1.55.2 , commit ending f30d.

**Comment by eamodio** [comment]
Can you post logs from the _Git_ output channel when this happens?

**Comment by ashiyo** [comment]
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/xxxx refs/remotes/xxxx
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%B -z -n21 -- /Users/xx/xx/xx/xx/xx/xx/xx.json
