### ISSUE TITLE
Lag with Keyboard

### ISSUE THREAD

**Issue by DonRichards** [microsoft/vscode#120653]
Issue Type: <b>Performance Issue</b>

While navigating up and down with keyboard the keyboard will stop moving for long periods of time. It does not look like it freezes. When I use the scroll wheel that seems to work but not the arrow keys at times. I can be sitting on a line and press the up arrow key and it might take upwards of 6 seconds before it starts moving. Other times it move without delay. I don't see this in any other app. 

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:13:21.003Z)
OS version: Linux x64 5.8.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2602)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|31.15GB (1.02GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 2540cff0-8230-4d16-9f63-d54f9572c09d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   160	953753	code-insiders main
    0	    32	953763	   zygote
    0	   128	953851	     gpu-process
    0	    32	953764	   zygote
    0	    32	953846	   utility
    0	   255	953890	   window (Makefile - umaine-fap-i8 - Visual Studio Code - Insiders)
    0	   128	954121	     extensionHost
    0	    64	954679	       electron_node server.js 
    0	    64	3517184	       electron_node server.js 
    0	   255	954160	     watcherService
    0	   319	953897	   window (● field.html.twig - bd-base-i8 - Visual Studio Code - Insiders)
    0	   128	954124	     extensionHost
    0	    64	954510	       electron_node server.js 
    0	    64	955888	       /snap/code-insiders/674/usr/share/code-insiders/code-insiders /snap/code-insiders/674/usr/share/code-insiders/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=954124
    0	    64	954155	     watcherService
    2	   128	954098	   shared-process
    0	    64	954223	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● field.html.twig - bd-base-i8 - Visual Studio Code - Insiders)
|  Window (Makefile - umaine-fap-i8 - Visual Studio Code - Insiders)
|    Folder (bd-base-i8): 3788 files
|      File types: yml(1883) py(563) pyc(540) scss(70) png(45) txt(35)
|                  twig(32) whl(28) csv(27) jpg(24)
|      Conf files: makefile(2) gulp.js(2) package.json(2) settings.json(1)
|    Folder (umaine-fap-i8): more than 20167 files
|      File types: php(9072) yml(2914) twig(1049) md(571) inc(503) xml(385)
|                  phpt(304) json(283) fixed(271) scss(181)
|      Conf files: makefile(6) package.json(3) gulp.js(2);
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
drupal-check|bbe|0.0.4
shell-format|fox|7.0.1
gc-excelviewer|Gra|3.0.41
VS-code-drupal|mar|0.0.12
twig-language-2|mbl|0.9.2
vscode-docker|ms-|1.11.0
remote-containers|ms-|0.166.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwsldoc:30278403
vscoresta800:30283263
vsc_aacf:30263846
vspre833cf:30267465
pythonptprofiler:30281269
vshan820cf:30276953
pythondataviewer:30283452

```

</details>

**Comment by alexdima** [comment]
@DonRichards Does this reproduce when disabling all extensions? Does this reproduce in any file type like in a `.txt` file?

**Comment by DonRichards** [comment]
Will do

**Comment by DonRichards** [comment]
Here's the profile https://gist.github.com/DonRichards/22d0e407ed467a9d9ee660f33dd17fb6
This is with all extensions off and is 2 profiles (txt, twig).

**Comment by alexdima** [comment]
@DonRichards Thank you for the profiles. They don't show any problems on the renderer process, so I think this might be a problem with the main process not handling the keyboard events.

@deepak1556 Do you have any insights on how to proceed investigating the apparent lack of handling of keyboard events?
