### ISSUE TITLE
Use modal dialog for initial trusted workspace

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#120661]
## Overview
When opening a folder that I've previously used that had several split editors and then enabling trusted workspaces, the page opens up in a small view that does not look great:

![image](https://user-images.githubusercontent.com/35271042/113755989-c69f8980-96c5-11eb-86b3-5d276660e6ae.png)

What is worse is you have a tiny small area to scroll through that makes it unusable.

## Proposal
Proposal would be to surface our custom dialog that allows for better focus and use of space, while still providing the same options and clicking on "see more" shows a more compact view of the page:

![CleanShot 2021-04-06 at 11 29 34](https://user-images.githubusercontent.com/35271042/113761002-cb673c00-96cb-11eb-8edf-e391ed5e9ce2.gif)

## North Star

And just to throw out this long shot, I think morphing the custom dialog to support webviews would also be good to keep this step contained without opening another tab:

![CleanShot 2021-04-06 at 11 39 41](https://user-images.githubusercontent.com/35271042/113762034-0027c300-96cd-11eb-8c25-c6ee7806e42d.gif)

**Comment by sbatten** [comment]
My personal vote is to not show anything except the badge but the north star dialog would be nice if I have to see one.

**Comment by misolori** [comment]
@sbatten this is for when you open a workspace for the first time after trust has been turned on. Currently we show the workspace trust tab, like in my OC, which is where the source of the issue stems from.

**Comment by sbatten** [comment]
@misolori yes, we are testing this out (showing the editor on startup), my vote would be to not show it at all like we used to. in the end, there is no "the first time you turn the feature on", it will be on for most when we enable it

**Comment by sbatten** [comment]
we do this now, I think this item should be closed
