### ISSUE TITLE
VISUAL STUDIO CODE fails to detect installed GIT and integrate it with the app.

### ISSUE THREAD

**Issue by algosig** [Microsoft/vscode#12069]
**Information Displayed:**
_It looks like git is not installed on your system.  You can either install it with Chocolatey or download it from fit-scm.com. Once git is installed, please restart Visual Studio Code_
While I have:
**git-gui version 0.20.GITGUI
git version 2.7.2.windows.1
Tcl/Tk version 8.6.4**
installed in my machine.
>> How can I integrate it with Visual Studio Code?

- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

**Comment by joaomoreno** [comment]
Where is your git installed? Is it in the `PATH`?

**Comment by dgileadi** [comment]
I ran into this same issue on my OS X El Capitan system. In my OS X Terminal, `which git` returns `/usr/bin/git`. In Visual Studio Code's user settings I set the `"git.path"` to that value and it solved the issue for me, but that seems like a workaround for a VS Code bug.

**Comment by polizz** [comment]
This same message has been seen on OSX 10.11.6 after doing the Xcode update and before accepting the EULA. In this situation, git command line tools will tell you as much.

**Comment by dgileadi** [comment]
In my case I indeed had updated to the latest Xcode, but I believe I had already accepted the EULA.

**Comment by joaomoreno** [comment]
@dgileadi Is that a belief or are you sure?

**Comment by dgileadi** [comment]
I can't be sure.

**Comment by algosig** [comment]
The issue was resolved after doing following things:

- Specified `git.exe` installation location from the setting.json
-   Restarted VSCode and I saw "Create New Repository on the VSCode Sidebar.
Cheers :)
:+1:
