### ISSUE TITLE
Flaky: active editor not always correct... #49125

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120622]
https://github.com/microsoft/vscode/runs/2277693425?check_suite_focus=true

```
  1) vscode API - window
       active editor not always correct... #49125:

      AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: ACTIVE editor should be doc: fake-fs:/gowv, column: 1, active: false, BUT HAVING doc: fake-fs:/gowv, column: 1, active: false, doc: fake-fs:/uaciosa, column: 2, active: true
      + expected - actual

      -false
      +true
      
      at assertActiveEditor (extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:173:11)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts:186:4)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by bpasero** [comment]
Prior art: #49125

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"integration-test-failure"

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/runs/2278434407?check_suite_focus=true#step:12:418

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/120355

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"integration-test-failure"
