### ISSUE TITLE
editors not coming on the screen to build pc softwares

### ISSUE THREAD

**Issue by Dhyan557** [microsoft/vscode#120645]
- VS Code Version:
- OS Version:windows 10

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Issue Type: <b>Bug</b>

I am not getting editing panel at the top of the screen just what we have to edit in ms word,powerpoint,excel etc..That same thing using which we create pc application and design them.I am not getting that please address my issue.For more details regarding this you can contact me at dhyan641@gmail.com.
Thanking you                                                             Your honest costumer 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.77GB (2.97GB free)|
|Process Argv|--crash-reporter-id 602af558-bd92-42b0-900e-41fbe6b17466|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.6.3
vscode-eslint|dba|2.1.19
code-runner|for|0.11.3
vscode-docker|ms-|1.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by Dhyan557** [comment]
pls make it fast

**Comment by Dhyan557** [comment]
worst costumer service by microsoft

**Comment by Dhyan557** [comment]
Please provide link of such recorder where even my voice would be able to
record.Because with voice I would easily communicate and you could address
my issue.
Thanking You
           Yours Faithfully

                 A microsoft costumer

**Comment by connor4312** [comment]
https://obsproject.com/

**Comment by Dhyan557** [comment]
even i am getting a new problem in microsofet access;it is telling this is
designed by microsoft and it is not allowing me to create a database.could
you please help me;

**Comment by Dhyan557** [comment]
this i will send you shortly because i am out know but the vs code one and
the access one both are serious issue;pls address it as fast as possible
and resolves both the issues

**Comment by Dhyan557** [comment]
Thank you for your response. Microsoft costumer service is very very
very good.I got it by some conversation with you. You are so kind. Thank
you for kindness.I will definitely go there on the website URL you provided

**Comment by Dhyan557** [comment]
When i Run my code on chrome from my VS code it always just opens
WWW.GOOGLE.COM   and nothing else.could please tell me why this is
happening and could you fix it?
