### ISSUE TITLE
Can I custom double-click and triple-click selection behavior

### ISSUE THREAD

**Issue by Phil-Channing** [microsoft/vscode#120681]
For `a_b_c` style word selection , sometimes I want to select single word like 'a', while in other situations I prefer to select the whole phrase `a_b_c`. I know the {"editor.wordSeparators": "_"} setting could work to select the single word separated by underline. But when I set this I can't select the whole phrase any more.

Can I just custom triple-click to select the whole phrase, and use `ctrl + L` to select the whole line, thank you.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/3130
