### ISSUE TITLE
Search editor and scoped context key service weirdness

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120699]
I came across this change that I found confusing:

https://github.com/microsoft/vscode/pull/99478/files#diff-065e97bed92a257652167bf976061c9d942dba9d6ecba94333f9588587d06bf1

It looks like the search editor is actually overriding the instantiation service from above for a scoped context key service:

https://github.com/microsoft/vscode/blob/19f6f3103606da3fe5d8be4b722d96fe8e18271a/src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts#L110-L111

But then we have this in the base class:

https://github.com/microsoft/vscode/blob/bb6014df3b4312272ec741be1d794649f6a0b71e/src/vs/workbench/browser/parts/editor/textEditor.ts#L55-L57

Can we unwind this and have proper support for a custom scoped context key service on the level of the base text editor so that we can get rid of the weird instantiation service override?

**Comment by bpasero** [comment]
@JacksonKearl after your changes the search editor no longer opens, did you see that too?

I pushed https://github.com/microsoft/vscode/commit/1df6bc657355f6f56d205f095d339aa071a40662 to be able to open search editor again, can you please check?

**Comment by JacksonKearl** [comment]
Oh weird, I tried it out and it seemed fine but after reverting your change it doesn't work. My build may have been stale. Though after your change I don't see the context keys actually set -- Inspect Context Key doesn't have inSearchEditor defined, and the keybindings don't work. Investigating.

**Comment by JacksonKearl** [comment]
Issue was the components in the query editor widget weren't getting their context key services to parented to the base text editor's. 

Pushed 6d8142e to fix, the gist of it is to create the base text editor first, then use it's scoped context key service to craft a new instantiation service which I use to create the query editor widget. So now the scoped instantiation service I create lives only inside Search Editor world.
