### ISSUE TITLE
The vscode icon is sometimes garbled 

### ISSUE THREAD

**Issue by stolenzc** [microsoft/vscode#120601]
- VS Code Version: 1.55.0
- OS Version: Macos 10.15.7

Steps to Reproduce:

1. when I use spotlight
![image](https://user-images.githubusercontent.com/42373706/113646866-46c0f180-96bc-11eb-99d1-ba287c903c69.png)

2. when I choose the app to open file
![image](https://user-images.githubusercontent.com/42373706/113646912-60623900-96bc-11eb-8d5d-779c853fc450.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by yume-chan** [comment]
Duplicate of #120305

**Comment by stolenzc** [comment]
> Duplicate of #120305

I got it!
