### ISSUE TITLE
Add "Commit and Push" option in UI for Git

### ISSUE THREAD

**Issue by RandomEngy** [microsoft/vscode#120647]
Visual Studio has an option to Commit and Push:

![image](https://user-images.githubusercontent.com/9450861/113737044-82ef5480-96b2-11eb-9d45-19555f090fef.png)

This is really handy because I don't have to sit around and wait for the commit to go through before pushing. It all happens in one batch. In large repositories it can be 10+ seconds before you see the commit go through and the "Changes" list clear out.

It's also more useful than setting up a Git commit hook, because I also still have the option to commit without pushing.

**Comment by amaynez** [comment]
+1 on this
