### ISSUE TITLE
Add `gitignore` file when user runs `Initialize Repository` command. 

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120665]
I have an idea when user initialize repository in new project it will be nice if vscode ask him to add `gitignore` file or not and this file can contain some basic configuration like `node_modules` folder for example.

**Comment by cl-ement05** [comment]
> I have an idea when user initialize repository in new project it will be nice if vscode ask him to add `gitignore` file or not and this file can contain some basic configuration like `node_modules` folder for example.

Well when initializing a repo a info/exclude file is automatically created by git and IIRC it is almost same as .gitignore. so this feature wouldn't be **that** useful
