### ISSUE TITLE
Alert same name when rename a variable

### ISSUE THREAD

**Issue by fujitatakesh** [microsoft/vscode#120668]
Issue Type: <b>Feature Request</b>

It'll be useful that alert same name already exists when rename a variable.
```
var a = 0;
var b= 0;
alert(a + b);

```
1. Rename "b"=>"a"
2. Alert "'a' is exists already" near the rename box

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

**Comment by geekley** [comment]
Yes, but please make it still possible to rename it anyways despite the warning. Sometimes I pick the same name on purpose.
