### ISSUE TITLE
vscode download link is broken

### ISSUE THREAD

**Issue by thenewpark** [microsoft/vscode#120688]
- VS Code Version: latest
- OS Version: macOS Catalina 10.15.7
- Browser: Chrome 89.0.4389.90
- Country: South Korea

Steps to Reproduce:

1. Try download via link from https://code.visualstudio.com/download & via homebrew
2. Network timeout error occurs 
    (request url is `https://az764295.vo.msecnd.net/stable/c185983a683d14c396952dd432459097bc7f757f/VSCode-darwin-universal.zip`)

I'm trying to download vscode since last week but keep failed.
It seems like there's some issues with CDN.  
If there's any recommendation to download the product before this problem is solved, 
please let me know :)

Does this issue occur when all extensions are disabled?: N/A

**Comment by thenewpark** [comment]
Checked the referenced issue above, but couldn't figure out the solution since the issue creator's network seems somehow fixed itself. 🤔

**Comment by joaomoreno** [comment]
Closing as temporary network failure.

**Comment by thenewpark** [comment]
It works! Thank you for checking :)
