### ISSUE TITLE
Update Service Failing

### ISSUE THREAD

**Issue by christophercutajar** [microsoft/vscode#120635]
Issue Type: <b>Bug</b>

After latest upgrade `Update 1.45.1`, I'm experiencing plugins such as Kubernetes plugin is not working and I'm seeing `Update Service` error when opening VS Code

![image](https://user-images.githubusercontent.com/60098546/113717359-d4680580-96eb-11eb-87eb-510593ccc0cf.png)

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 20.3.0

**Comment by joaomoreno** [comment]
Have you clicked the `this link` link? It will show you how you can fix it.

**Comment by christophercutajar** [comment]
Issue solved! Managed to perform a VS code updaate
