### ISSUE TITLE
Code cache corruption with V8 option bypassHeatCheck

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#120655]
started getting this issue again after the latest update.
#114459

i tried the `code-insiders --disable-gpu .` and  `code-insiders --disable-features=CalculateNativeWinOcclusion <path to workspace/folder>` option but they don't work.

**Comment by bpasero** [comment]
@sanket-bhalerao can you run `code-insiders --version` and print the output here? What do you see when you run `code-insiders --verbose --open-devtools` ?

**Comment by bpasero** [comment]
@sanket-bhalerao we are seeing this too and it looks like with an issue with that specific insiders version. Can you reinstall insiders please, we have halted the update for now. It should work then again.

**Comment by sanket-bhalerao** [comment]
@bpasero re-install is working, thanks for the quick response.

**Comment by chrmarti** [comment]
@bpasero This is still an issue with the build from https://github.com/Microsoft/vscode/commit/05b52df98a547be59a8fce5a1f5a8fb09750bba0. Would you expect it to be fixed with your change?

**Comment by bpasero** [comment]
Yeah it is fixed with https://github.com/microsoft/vscode/commit/2b6df1bba957fb924c8f9ae5b2f904ef092aa899. Try to delete the "Code Cache" folder maybe. And see if you have enabled `vscode-file` protocol explicitly in runtime args.

**Comment by chrmarti** [comment]
@bpasero Yesterday's 550035808407c15252e581e8abe1b820b9d311ee still works. Shouldn't the new build work too?

**Comment by chrmarti** [comment]
Deleting "Code Cache" helped. I also just realized that I went from the Universal to the x64 build, not sure if that might have affected this.

In case someone else needs this, I did `rm -rf ~/Library/Application\ Support/Code\ -\ Insiders/Code\ Cache` to move forward.

**Comment by bpasero** [comment]
Yeah, I never saw this in ARM builds, only X64 macOS.

**Comment by bpasero** [comment]
Pushed a "workaround" to delete the `Code Cache` folder on every startup.

If you still hit this in the current insiders version, the workaround is to delete this folder before starting:
* **Windows** `%APPDATA%\Code - Insiders\Code Cache`
* **macOS** `$HOME/Library/Application Support/Code - Insiders/Code Cache`
* **Linux** `$HOME/.config/Code - Insiders/Code Cache`

**Comment by bpasero** [comment]
The latest released insider version `bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a` should fix these issues. It deletes the `Code Cache` folder on startup.

**Comment by sanket-bhalerao** [comment]
@bpasero i updated insiders to latest update and it worked fine.
I'm not getting the blank window issue anymore.

**Comment by bpasero** [comment]
**Discussion input:**
* are we able to figure out what was causing the code cache corruption with V8 tooling or V8 help
* can we understand whether V8 runs with different flags when running in a sandboxed renderer (issue reporter, process explorer) vs. non sandboxed (workbench, shared process)?
  * and if so, could that explain a code cache issue?
* can we add a way for VSCode to signal to V8 that a cache should be dropped
  * via specifying the `Code Cache` folder? there is a [`--disk-cache-dir`](https://peter.sh/experiments/chromium-command-line-switches/#disk-cache-dir) argument it seems, but not working

**Comment by bpasero** [comment]
Next steps:
* @deepak1556 provide an API on `session.defaultSession` to set the code cache path
* @bpasero to use this API in debt week to measure perf numbers
* @bpasero to adopt the automated cache cleanup

**Comment by bpasero** [comment]
Optimistically closing as we now use a cache dir per commit.
