### ISSUE TITLE
Editing file using `code  -w` in terminal does not return focus to terminal when closed

### ISSUE THREAD

**Issue by leighmcculloch** [microsoft/vscode#120695]
- VS Code Version: 1.55.0
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Open terminal
2. Run command `code -w file`
3. `file` will open in the editor
4. make some changes or add text to `file`
5. Close file, such as with `CMD-W`
6. Focus remains in the editor, and does not return to the terminal

Does this issue occur when all extensions are disabled?: **No**. This problem doesn't seem to occur when have my extensions disabled.

I used the extension bisect but it failed on the first attempt. It said it disabled 62 extensions, I tried reproducing the problem, and it succeeded, so I clicked "This is bad" and the bisect ended immediately saying it might be a problem with VS Code. The unique thing is that my project was running inside a remote container.

**Comment by meganrogge** [comment]
Based on your testing, it seems an extension is to blame for this
