### ISSUE TITLE
Assigning undefined to commentThread.contextValue doesn't reset the backing context key

### ISSUE THREAD

**Issue by hunterknepshield** [microsoft/vscode#120680]
- VS Code Version: 1.54.3 (commit 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8)
- OS Version: macOS 11.3 Beta

Steps to Reproduce:
1. From `package.json`, have a menu contribution registered for `comments/commentThread/context` to show some command with `"when": "commentThread != sentinelForPackageJson"`
2. From extension, call commentController.createCommentThread
3. Leave the thread's `contextValue` unassigned for now
4. Observe that the command from `package.json` is currently visible in a comment thread; type a reply and click the button for that command
5. Within the handling code for that command, assign the thread's `contextValue` to `"sentinelForPackageJson"` (similar to the example extension in `microsoft/vscode-extension-samples/blob/main/comment-sample/src/extension.ts` when handling `mywiki.startDraft`). My extension also sets the thread's `canReply` value to `false` at the same time.
6. Have another command to effectively discard the comment created with the prior command. It will set the thread's `canReply` value to `true` and set its `contextValue` to `undefined`. Observe that in this case, the command from 1 is not rendered, but the textbox to type a reply has reappeared.

I've been playing around with it, and if instead of setting the `contextValue` to undefined in step 6, I set some other random arbitrary value, then the context key is updated correctly and the command does reappear. I believe it has something to do with the slight difference in `commentThreadWidget.ts`, specifically around `_commentThreadContextValue`:
```typescript
		if (this._commentThread.contextValue) {
			this._commentThreadContextValue.set(this._commentThread.contextValue);
		} else {
			this._commentThreadContextValue.reset();
		}
```

Using the inspect context keys tool, the `commentThread` context key is still set to `"sentinelForPackageJson"`, even though the object's property is definitely `undefined` after the command in 6 runs. For some reason, it seems the lifecycle of the comment thread is latching on to `"sentinelForPackageJson"` as the default value, even though it wasn't assigned anywhere near the thread's creation time, and was only done so later after user action had taken place + the thread was updated to append a new comment.

Does this issue occur when all extensions are disabled?: No

This is an extension I've been writing.

**Comment by roblourens** [comment]
I added a second button so I can get the context of the menu, and it seems like `sentinelForPackageJson` is not set after running through the steps. Code looks roughly like this


```
	let thread: vscode.CommentThread;
	context.subscriptions.push(vscode.commands.registerCommand('extension.helloWorld', async (arg1) => {
		const commentController = vscode.comments.createCommentController(
			'id',
			'label'
		);
		const comment: vscode.Comment = {
			body: 'body',
			author: {
				name: 'name',
			},
			mode: vscode.CommentMode.Preview
		};
		thread = commentController.createCommentThread(vscode.window.activeTextEditor.document.uri, new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), [comment]);
		thread.contextValue = 'sentinelForPackageJson';
		thread.canReply = false;
});

	context.subscriptions.push(vscode.commands.registerCommand('extension.helloWorld2', async (arg1) => {
		thread.canReply = true;
		thread.contextValue = undefined;
	}));

```

**Comment by rebornix** [comment]
@roblourens I didn't quite follow the issues you ran into. Did you mean that after running "hello World", the context key for the comment thread is not set to `sentinelForPackageJson`?

**Comment by roblourens** [comment]
I run the first command `helloWorld`, everything is correct, then I run the second command `helloWorld2`, and the button should show up now that the contextValue has cleared but the button does not show up.
