### ISSUE TITLE
Additional terminals not showing full commands

### ISSUE THREAD

**Issue by subhamkedia799** [microsoft/vscode#120608]
Issue Type: <b>Bug</b>

open a second terminal, try writting something long on terminal, the cursor keeps cycling on display but when pressesd enter the command executes

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.17763
Remote OS version: Linux x64 4.15.0-133-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.94GB free)|
|Process Argv|--crash-reporter-id 655306f3-0a27-4e8c-86e7-ad97eea655a2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: subhkedi-linux|
|OS|Linux x64 4.15.0-133-generic|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 1649)|
|Memory (System)|31.03GB (3.29GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
llvm-tablegen|jak|0.0.2
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
cmake-tools|ms-|1.6.0
cpptools|ms-|1.2.2
rst-vscode|tht|3.0.1
cmake|twx|0.0.17
clang-format|xav|1.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
pythonvspyt943:30280189
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
