### ISSUE TITLE
Settings (UI) - Cursor jumps around when clicking between text boxes and making changes

### ISSUE THREAD

**Issue by rjb3977** [microsoft/vscode#120687]
- VS Code Version: 1.55.0
- OS Version: Windows 10 20H2 (OS Build 19042.870)

Steps to Reproduce:

1. Open Settings (UI)
2. Scroll somewhere where there are two different text box settings visible
3. Click in the first text box
4. Change the value in the first text box
5. Click in the second text box
6. (Try to) change the value in the second text box
7. ??? (probably a race condition with saving and reloading the settings.json file)
8. a. You're fast enough to change the second text box, and the changes in the first text box will be undone when you click away
b. You're too slow, your cursor has returned to the first text box, and you've inadvertently changed it again

If you're having trouble reproducing 8.a, try it in an SSH session, preferably one with high latency. Saving the settings is slower, so there's more time for you to make the change. I'm not sure if settings are actually saved on the remote host, but either way it seems to add enough delay to make it easily reproducible.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Yes... I am using a not great strategy here in trying to refresh the list when changes come in. https://github.com/microsoft/vscode/issues/106577
