### ISSUE TITLE
The code completion is jammed together

### ISSUE THREAD

**Issue by huoxingyun** [microsoft/vscode#120650]
![F02CE6C7-2AC1-4B21-A291-01B4BDD8D418](https://user-images.githubusercontent.com/10088060/113748705-677c5c00-973b-11eb-9773-dc12a0992387.jpeg)

**Comment by huoxingyun** [comment]
![126B2680-4A0D-4027-8F12-57C9F2B97DCD](https://user-images.githubusercontent.com/10088060/113749056-c5a93f00-973b-11eb-89e1-5c98bb615b77.png)

setting.json is wrong

hope that may help you

**Comment by jrieken** [comment]
There are two settings that should be tweaked: `editor.suggestFontSize` and `editor.suggestLineHeight`
