### ISSUE TITLE
Remove outline on non-interactive element when using mouse

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#120606]
I undertand that the outline is there for accessibility reason, but since these elements are non-interactive, the focus style should only be shown when using the keyboard navigation.
On a website that would usually be done using what-input or custom JS.
https://www.npmjs.com/package/what-input
https://ten1seven.github.io/what-input/
<img width="2032" alt="Capture d’écran, le 2021-04-06 à 02 30 47" src="https://user-images.githubusercontent.com/17392251/113668450-3c810200-9680-11eb-851f-f4dc54bbdaf9.png">
<img width="2032" alt="Capture d’écran, le 2021-04-06 à 02 30 43" src="https://user-images.githubusercontent.com/17392251/113668452-3db22f00-9680-11eb-8c53-ccfb81896d42.png">

**Comment by roblourens** [comment]
They are interactive, and you can use the keyboard on them at this point. It is typical to show where focus is like this even if it's not always necessarily useful. Thanks for the suggestion but I'm not interested in trying to customize it, I know it will be a pain.

**Comment by mrleblanc101** [comment]
I mean a random div should not be focusable. Div have no semantic meaning.
Also as I said, I have nothing against the focus style, but it should only appear when using the keyboard navigation and not when using a mouse unless it's an interactive element like a form input, a link or a button.

**Comment by mrleblanc101** [comment]
Why not keep it open and let a member of the community that actually has interest in this issue take care of it ?
Just because you don't want to do it, doesn't mean the issue has to be closed.

**Comment by roblourens** [comment]
It's not a random div, it's the list. You can now interact with the lists and all lists in vscode are consistent in this. I'm closing it because I'm not interested in a PR for this either for the reasons I gave
