### ISSUE TITLE
Hint shows up and file is found but "auto import" option is not shown

### ISSUE THREAD

**Issue by Dylan-Kerler** [microsoft/vscode#120616]
I want to import `Card` - As you can see the `Card` component and file are found but there is no option to auto import. For some components it shows up and for others it doesn't. How can I fix this?

![Screenshot from 2021-04-06 10-01-13](https://user-images.githubusercontent.com/37438950/113686397-20e91c00-96bf-11eb-9ea2-bc572106a742.png)

**Comment by fila90** [comment]
Same, here!
It can find exported function from one module, but won't import them automatically as it used to.

```
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
```
running on macOS Bis Sur 11.2.3
