### ISSUE TITLE
Expose drag and drop event to `Decorators` just like Breakpoints will have

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#120674]
As requested by @isidorn , I'm creating this issue to ask for exposing the same _drag and drop_ capability/event to `Decorators`. 

This capability is being added in #88227  for Breakpoints, in the core.

Thank you

**Comment by isidorn** [comment]
I think this is a fair feature request, we just do not have it on the plan at the moment. Thus assigning to backlog.
Also assigning to @alexdima since he owns the editor decorations and he might know if there are duplicates for this issue.

**Comment by zimonitrome** [comment]
Low-key bumping because I still think this could be relevant.

For [my extension](https://github.com/zimonitrome/vscode-color-blocks) I would like to implement draggable handles for colored ranges but I believe it's currently impossible.
