### ISSUE TITLE
HTML Language Server and JSON Server built-in plugins gives errors

### ISSUE THREAD

**Issue by mehmetsefabalik** [microsoft/vscode#120621]
Issue Type: <b>Bug</b>

HTML Language Server and JSON Server built-in plugins gives errors like this: `Connection to server is erroring. Shutting down server.`

VS Code version: Code - Insiders 1.56.0-insider (Universal) (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:13:17.592Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|storefront --crash-reporter-id 4d0be1ae-a96f-4505-a582-563a2bebae37|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
color-info|bie|0.5.1
vscode-styled-jsx|bla|2.0.0
better-toml|bun|0.3.2
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
vscode-eslint|dba|2.1.19
githistory|don|0.6.16
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|11.3.0
el-vsc-product-icon-theme|ElA|0.1.8
vscode-jest-runner|fir|0.4.31
intellij-idea-keybindings|k--|1.4.4
node-module-intellisense|lei|1.5.0
kubernetes-templates|lun|1.1.2
rust-analyzer|mat|0.2.546
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.6.718745073
js-debug-companion|ms-|1.0.9
js-debug-nightly|ms-|2021.4.517
vscode-typescript-next|ms-|4.3.20210405
vscode-typescript-tslint-plugin|ms-|1.3.3
reload|nat|0.0.6
tosnippet|nsf|0.1.3
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.17.0
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.5.17
vscode-scss-formatter|sib|2.1.0
sass-indented|syl|1.8.16
open-in-browser|tec|2.0.0
vscode-lldb|vad|1.6.1
vscode-icons|vsc|11.4.0
gitblame|wad|6.0.2
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
wslfolderdoccf:30278406
vsget980:30283264
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
pythondataviewer:30285072

```

</details>

**Comment by aeschli** [comment]
Does it always reproduce? Or after a while?
Can you turn on logging for the servers, e.g. `"json.trace.server": "verbose",`

**Comment by mehmetsefabalik** [comment]
It reproduced always. I couldn't stand this issue and removed all files related to vscode and then installed it from scratch. This issue is never happened after reinstallation. I followed the steps described in [here](https://stackoverflow.com/a/53839847/6642195)

**Comment by aeschli** [comment]
Hm, interesting. So now all works again?
From the error message alone it's difficult to say what could have been the problem.
Please reopen the issue if you see it again.
