### ISSUE TITLE
Array range nodes cannot be expanded

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#12067]
- VSCode Version: 1.6.0 Insider
- OS Version: macOS

Steps to Reproduce:

1. create array with more 1000 elements
2. start debugging and try to expand the range [0..99]

Observe:

the node has no twisty and cannot be expanded:
![2016-09-15_10-08-36](https://cloud.githubusercontent.com/assets/1898161/18545207/71901192-7b38-11e6-9784-9f5fbe796639.png)

/cc @roblourens

**Comment by weinand** [comment]
This is caused by the fix for #10215. I've reverted the fix.

**Comment by isidorn** [comment]
@weinand you have fixed this by reverting the other commit, thus closing this.
