### ISSUE TITLE
Consider surfacing mapped variable names

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#12066]
Sourcemaps can represent variable name mappings, like when they're changed in minified code, or TypeScript's `this => _this`. Chrome DevTools shows the original variable names in their variables sidebar: https://bugs.chromium.org/p/chromium/issues/detail?id=327092

One problem is that if you don't know the original names, you can't inspect them in the console or with watches. But I think it would still make debugging easier to have them just in the variables pane.

We could go one step further by showing both names, in the variable name space, just like `myArray (t)`. And another step by adding this to the protocol so that the context menu "Add to Watch" would work. I don't know if it's a useful concept outside of JS though.

**Comment by isidorn** [comment]
This is a great feature request, however after discussing with @weinand we would need an AST understanding of the language in order to support this feature. Since the source map talks about the location in the file and there is no other correlation between the minified name and the original one.

We should investigate in the future what it would take for us to have a better understanding of the AST and decide if that logic should live on the vscode or the debug adapter side.
Unassigning myself since I am not a fan of multi-assigned issues :)

Other areas which would profit from a better AST understanding are the debug hover and showing evaluted variables inlined.

**Comment by nojvek** [comment]
Does the debug adapter expose an api to get mapped names per line? 

I believe source map does expose how a variable in source code is mapped to transpiled code, right?

**Comment by roblourens** [comment]
The debug adapter returns the list of variables to vscode, so if we wanted to show the variables from TS, the debug adapter would do that mapping. The `source-map` library that vscode-chrome-debug-core uses exposes an API for this.

**Comment by weinand** [comment]
@nojvek source map support is an implementation detail of a debug adapter that does not leak through the API to VS Code. So VS Code does not know anything about source maps.

The source map specification defines naive support for symbol mappings (as opposed to range mapping), but I do not see how that can be used in practice without scope information. So something is missing here...

In addition I do not see broad support for symbol mappings in transpile tools. E.g. TypeScript (tsc) leaves the symbol mapping always empty and I'm not aware of a tsc option to turn symbol mappings on.

**Comment by nojvek** [comment]
This seems like a bug in Typescript not emitting names. Filed:
https://github.com/Microsoft/TypeScript/issues/14688

So are you saying, once you have names correctly outputted in sourcemaps
(babel does this), you are able to make this work?

For my scenario, I will try to bypass ES5 output and just go directly to
ES6.



With babel

**Comment by roblourens** [comment]
Maybe, I think we don't yet have a good understanding of the work involved to make it work.

**Comment by roblourens** [comment]
https://github.com/Microsoft/TypeScript/issues/9627

**Comment by Lazarencjusz** [comment]
@roblourens can the problem with sourcemaps be fixed now? It's been half of the year since last activity here and many TypeScript versions came in.

**Comment by gynet** [comment]
I still observer many related issues related when typescript got compiled. e.g typescript rename this to _this, or the variable names got minified. This issue is really annoying to customers and this feature should be considered with higher priority.

**Comment by themaskedavenger** [comment]
This is true - I'm trying to switch from Webstorm to VSCode and this makes the debugger virtually useless...how can you debug typescript code if you can't see the actual variables as they are named in the ts code?! Webstorm does this no problem.

**Comment by connor4312** [comment]
We now support this. There is even limited in the REPL (completions don't work).

![image](https://user-images.githubusercontent.com/2230985/118340116-ad150d00-b4cf-11eb-8f4d-dda2348f7b37.png)
