### ISSUE TITLE
Task framework should show status icon about watching tasks

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#12065]
- VSCode Version: 1.5.0

We do have a status icon however this is only visible if the task is actively running. We should show the task in watch mode as well and allow certain actions (like terminate) on the status bar icon.

**Comment by jonburger** [comment]
The octicon icon set in use by VS Code even has a lovely 'Eye' icon that would work well for this.

I hope this is implemented, it would be a great little friendly feature to have.

**Comment by alexr00** [comment]
We show the tools codicon in the status bar for this.
