### ISSUE TITLE
JavaScript - No suggestions for object with number index without quotes.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120671]
- VS Code Version: 1.55.0
- OS Version: Windows 10 20h2

Steps to Reproduce:

![2](https://user-images.githubusercontent.com/17777237/113788459-40268e80-973d-11eb-81c1-0e63a294d1e1.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by pixieaka** [comment]
@mjbvz But object with numeric index can access without quotes why suggestions doesn't support this case?

**Comment by pixieaka** [comment]
@mjbvz But object with numeric indexes can access without quotes. Why suggestions doesn't support this case?

**Comment by mjbvz** [comment]
The keys are strings. Yes JavaScript auto converts the bracketed value to a strings, but that does not mean we want show IntelliSense suggesting to use a number literal here. As a more extreme example, consider:

```js
const  b = { 5: 'xyz' }
b[{ toString: () => '5' }] // 'xyz'
```

Instead we show IntelliSense inside brackets when you start typing a string key:

<img width="421" alt="Screen Shot 2021-04-06 at 5 48 24 PM" src="https://user-images.githubusercontent.com/12821956/113794847-4ea28500-9700-11eb-9812-0a58795b8495.png">
