### ISSUE TITLE
Remove window.sessionId

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120696]
Referring to: 

https://github.com/microsoft/vscode/blob/28a55539bb940913190035e8264d4253b1724b24/src/vs/platform/windows/electron-main/window.ts#L839-L839

Which seems to be used only in update from `IEnvironmentService#sessionId`.

This seems it could just use the `windowId` directly?

Filing this because I am revisiting properties in `INativeWindowConfiguration` to clean them up.

**Comment by joaomoreno** [comment]
From what I can recall from that discussion with you, I believe we did it like that because we didn't want to expose something like `windowId` in `IEnvironmentService`.

**Comment by bpasero** [comment]
@joaomoreno meanwhile you can get the `windowId` from this `INativeHostService`: 

https://github.com/microsoft/vscode/blob/5a8936ae639316163e89e08920d2120515ab55e6/src/vs/platform/native/common/native.ts#L37-L37

This is OK to call from any window.

**Comment by joaomoreno** [comment]
@bpasero There is code in `browser` which needs it. It seems that `INativeHostService` is `electron-sandbox` only?

https://github.com/microsoft/vscode/blob/7031abadeafec54c8876231e3579c938dee6e1a5/src/vs/workbench/browser/parts/titlebar/menubarControl.ts#L467-L467

https://github.com/microsoft/vscode/blob/108616d3590004ad20879903949f5d445be79998/src/vs/workbench/contrib/update/browser/update.ts#L251-L251

**Comment by bpasero** [comment]
@joaomoreno yeah I think the web variant makes more sense to me:

https://github.com/microsoft/vscode/blob/e9b7b5d25b8423e5397b7f022e01afbf0421b98e/src/vs/workbench/services/environment/browser/environmentService.ts#L29-L29

Does it need to be an identifier that stays stable within the window or could it be a UUID in desktop too?

I think in general the session ID makes sense, I was just wondering why it needs the window ID.

**Comment by bpasero** [comment]
![Uploading image.png…]()
