### ISSUE TITLE
Right clicking Recycle Bin on Windows has the option to "Open with Code - Insiders"

### ISSUE THREAD

**Issue by Equinox** [Microsoft/vscode#12063]
- VSCode Version: Insider build (1.6.0-insider, commit fad6a894c197ee791403ac694c9316b0654f31a4)
- OS Version: Windows 10.

Steps to Reproduce:

1. Right click on the Recycle Bin icon on the desktop.
2. Notice there's a "Open with Code - Insiders" option.
![](https://i.imgur.com/g7L8Cug.png)

3. When clicked, nothing happens.

Potentially unwanted functionality and possibly added by https://github.com/Microsoft/vscode/commit/cc728e7bc6a60d7e6c00e254c3c2773fa68802b4.

**Comment by joaomoreno** [comment]
Wow! That was really fast. This likely happened due to #11870. @Romanito, any clue on how to prevent this?

**Comment by Romanito** [comment]
@joaomoreno I did some tests and found another way of adding the context menu entry for drives and not the recycle bin. Should be better now.

**Comment by joaomoreno** [comment]
Thanks a lot @Romanito !
