### ISSUE TITLE
Treat Notifications Window as Normal "Pane"

### ISSUE THREAD

**Issue by langdon** [microsoft/vscode#120640]
The other day, I had the darndest time trying to find a notification I missed. As a person who is more "word based" than "picture based," I just glossed over the notification icon at the bottom right as something that would have "history" and spent a while looking in the View menu for a "Notifications Window." Finally asked someone on the internet and they pointed out the obvious.

However, my proposal here is, why is the Notifications Window "special"? Why can't I use it like any other window? In particular, I am thinking about scenarios where I get an error as a notification and need to do a lot of navigation through code, the IDE, etc, to rectify it. Would be nice if I could just add it as a tab like "Problems." I also don't know why it isn't just another "View" in terms of navigation of the IDE.

For all I know, you can do this and I am just bad at finding features (as evidenced by the first graph). However, I don't think so and when I asked around, i didn't get any answers.

**Comment by bpasero** [comment]
//cc @isidorn @misolori @devinvalenciano
