### ISSUE TITLE
Selection in "search in files panel" and shown editor are not always in sync anymore

### ISSUE THREAD

**Issue by CombeeMike** [microsoft/vscode#120637]
Issue Type: <b>Bug</b>

* Open search panel
* Enter some search which yields results in multiple files
* Navigate through search results using arrow keys
  -> ✅ All ok, as the selected result & the shown editor are kept "in sync"
* Delete entry from search results with `del` key
* Navigate through search results using arrow keys
  -> ❌ Selected result & editor are not "in sync" anymore
* Sync can be "re-established" by clicking `space` (or `enter`) on the selected search result

https://user-images.githubusercontent.com/30658772/113722829-147db700-96f1-11eb-8cab-ade832e0d124.mp4

VS Code version: Code - Insiders 1.56.0-insider (550035808407c15252e581e8abe1b820b9d311ee, 2021-04-02T05:15:44.248Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by roblourens** [comment]
@joaomoreno I was trying a better fix for this like adding this in SearchView

```ts
this._register(this.tree.onDidChangeSelection(() => {
	if (!this.tree.getSelection().length) {
		this.tree.setSelection(this.tree.getFocus());
	}
}));
```

and it's strange, this event is never fired when the selection becomes empty, only when it changes to a different element, any idea why that would be?

Otherwise I have to set the selection manually in another place, which is ok but I'm worried about maintaining it and missing more cases.

**Comment by vielhuber** [comment]
I experience the same issue.
It was very convenient if you delete a search item on the left, it jumps and focuses automatifcally the next item in the list.
This behaviour is now gone.

**Comment by akbyrd** [comment]
Just ran into this as well. Searching and deleting results as I deal with them is one of the main ways I navigate. This workflow is completely broken now.

**Comment by joaomoreno** [comment]
> Otherwise I have to set the selection manually in another place, which is ok but I'm worried about maintaining it and missing more cases.

I think this is the right way to go here, for now. I'll push a commit with the code paths that I found.
