### ISSUE TITLE
Enable noImplicitOverride in our codebase

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#120675]
## `--noImplicitOverride `
TS 4.3 adds a new strictness option: [`--noImplicitOverride`](https://github.com/microsoft/TypeScript/pull/39669). This requires that you use the `override` keyword when overriding and method:

```ts
class Foo {
   foo() {...}
}

class SubFoo extends Foo {
    foo() { ... } // ERROR: missing override specifier
}
```

To fix this, simply add the `override` keyword:

```ts
class SubFoo extends Foo {
    override foo() { ... } 
}
```

The override keyword does not change runtime behavior but can help programmers in a few ways:

- When reading code, it alerts you that a method is overriding one from the base class

- It is an error to try to override a method that does not exist on the base class. This can help catch errors caused by renaming a method in a base class but forgetting to update the method name in the subclasses.

## Enabling 
I propose enabling this new flag for both VS Code code and extensions.

Enabling it currently causes ~2200 compile errors, however unlike the previous strictness checks we enabled, I believe should simply use a script to automatically fix the vast majority of them (by inserting `override` in the necessary location)

**Comment by mjbvz** [comment]
Here's the simple python script I used to automate most of the rewrites:

```py
from os import path
import re


def fixThisMember(file, line, col):
    with open(file, 'r') as f:
        lines = f.readlines()

    lineContent = lines[line - 1]

    # public? async? method(
    lineContent = re.sub(
        r'^(\s+)((?:public|private|protected) )?(async )?([\w_$]+[\(<])',
        r'\1\2\3override \4',
        lineContent)

    # public? get|set prop(
    lineContent = re.sub(
        r'^(\s+)((?:public|private|protected) )?(get|set) ([\w_$]+)\(',
        r'\1\2override \3 \4(',
        lineContent)

    # public? readonly? prop =
    lineContent = re.sub(
        r'^(\s+)((?:public|private|protected) )?(readonly )?([\w_$]+) =',
        r'\1\2\3override \4 =',
        lineContent)

    # public? readonly? prop:
    lineContent = re.sub(
        r'^(\s+)((?:public|private|protected) )?(readonly )?([\w_$]+):',
        r'\1\2\3override \4:',
        lineContent)

    if lineContent != lines[line - 1]:
        print(file)
        lines[line - 1] = lineContent
        with open(file, 'w') as f:
            f.writelines(lines)


# file containing tsc error text
with open('override-errors.text') as f:
    for line in f:
        pMatch = re.match(r'.+Error: (.+)\((\d+),(\d+)\): (This member must have an)',
                          line, flags=re.I)
        if pMatch:
            file = pMatch.group(1)
            line = int(pMatch.group(2))
            col = int(pMatch.group(3))
            fixThisMember(file, line, col)
```

This is a pretty simple script but takes us from 2200 errors to 200 or so.

The remaining errors fall into a few buckets:

- Cases where the property is declared in a constructor.
 
    Many of these seem to be errors (such as a subclass re-declaring a protected property)

    The rest need to be re-written  manually

- `declare readonly _serviceBrand: undefined`

     https://github.com/microsoft/TypeScript/issues/43566 

     We should likely just change these to `override readonly _serviceBrand: undefined`

- Static properties overriding non-static property

    https://github.com/microsoft/TypeScript/issues/43563

    Seems to be a bug on the TS side

**Comment by Kingwl** [comment]
Cool! But... Are there any tools could batch apply quickfix?

**Comment by mjbvz** [comment]
@Kingwl Not that I know off. For source actions, you can use https://marketplace.visualstudio.com/items?itemName=bierner.folder-source-actions

Hooking up individual quick fixes would be a little more difficult but should be doable (writing a simple python find/replace script was a lot quicker in this case)

**Comment by mjbvz** [comment]
## Current status

I've automatically added `override` to simple cases with methods/properties with #120755. This does not change runtime behavior and just annotates a pattern that already exists in the code. You can review the changes in your areas of the codebase by searching for the `override` keyword. This automation took us from 2200 errors to around 200.

I also made two passes at the remaining errors. There were two types of issues I addressed here:

- Simple cases the automation missed

- Cases where a constructor was overriding a property with the same type. This was happening fairly often for services. [Here's an example](https://github.com/microsoft/vscode/commit/86bf027920105f0a9af3de25fc3da3bf2648a104#diff-6b18e481ac1a388aa42788d603fa01462ebe8a108f9505bcb80ef4dfee5cf42fL212)


## Next steps
The remaining 100 errors need to new reviewed manually so I'm going to assign area owners. Please re-assign if needed

To test building with `--noImplicitOverride` so that you can fix these errors, simply run `yarn no-implicit-override-watch`. After making the change, be sure to check the code compiles with our normal `yarn watch` too

- [ ] `src/vs/base/browser/ui/dropdown/dropdownActionViewItem.ts`
- [ ] `src/vs/base/browser/ui/tree/asyncDataTree.ts` @joaomoreno 
- [ ] `src/vs/base/browser/ui/tree/dataTree.ts` @joaomoreno 
- [ ] `src/vs/base/browser/ui/tree/indexTree.ts` @joaomoreno 
- [ ] `src/vs/base/browser/ui/tree/objectTree.ts` @joaomoreno 
- [ ] `src/vs/editor/browser/core/editorState.ts` 
- [ ] `src/vs/editor/browser/services/codeEditorServiceImpl.ts`
- [ ] `src/vs/editor/common/services/editorSimpleWorker.ts`
- [ ] `src/vs/editor/contrib/quickAccess/gotoSymbolQuickAccess.ts`
- [ ] `src/vs/editor/contrib/suggest/suggestController.ts` @jrieken 
- [ ] `src/vs/platform/actions/browser/menuEntryActionViewItem.ts`
- [ ] `src/vs/platform/configuration/common/configurationModels.ts` @sandy081 
- [ ] `src/vs/platform/contextkey/common/contextkey.ts`
- [ ] `src/vs/platform/extensionManagement/test/common/extensionGalleryService.test.ts` @sandy081 
- [ ] `src/vs/platform/list/browser/listService.ts`
- [ ] `src/vs/platform/quickinput/browser/commandsQuickAccess.ts`
- [ ] `src/vs/platform/userDataSync/common/userDataSync.ts` @sandy081 
- [ ] `src/vs/workbench/api/browser/mainThreadTunnelService.ts` @alexr00 
- [ ] `src/vs/workbench/api/common/extHostApiCommands.ts` @jrieken 
- [ ] `src/vs/workbench/browser/parts/compositeBarActions.ts`
- [ ] `src/vs/workbench/browser/parts/editor/breadcrumbsPicker.ts`
- [ ] `src/vs/workbench/browser/parts/editor/titleControl.ts`
- [ ] `src/vs/workbench/browser/parts/views/viewPane.ts`
- [ ] `src/vs/workbench/browser/parts/views/viewPaneContainer.ts`
- [ ] `src/vs/workbench/browser/parts/views/viewsViewlet.ts`
- [ ] `src/vs/workbench/common/editor/diffEditorInput.ts`
- [ ] `src/vs/workbench/contrib/bulkEdit/browser/bulkCellEdits.ts` @jrieken 
- [ ] `src/vs/workbench/contrib/debug/common/debugModel.ts` @isidorn 
- [ ] `src/vs/workbench/contrib/extensions/electron-browser/reportExtensionIssueAction.ts` @RMacfarlane 
- [ ] `src/vs/workbench/contrib/notebook/browser/contrib/clipboard/test/notebookClipboard.test.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/diff/diffComponents.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/diff/diffElementViewModel.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/view/renderers/cellActionView.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/view/renderers/codeCell.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/notebook/browser/viewModel/markdownCellViewModel.ts` @rebornix
- [ ] `src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/tasks/common/tasks.ts` @alexr00 
- [ ] `src/vs/workbench/electron-browser/desktop.main.ts` @bpasero 
- [ ] `src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts`
- [ ] `src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts` @sandy081 
- [ ] `src/vs/workbench/services/textfile/common/textfiles.ts` 
- [ ] `src/vs/workbench/services/textfile/electron-sandbox/nativeTextFileService.ts`
- [ ] `src/vs/workbench/test/browser/api/extHostConfiguration.test.ts`
- [ ] `src/vs/workbench/test/browser/api/extHostWorkspace.test.ts`

**Comment by bpasero** [comment]
Down to 80

![image](https://user-images.githubusercontent.com/900690/114135785-0b1b6700-990a-11eb-9175-cd2223af3c85.png)

**Comment by isidorn** [comment]
@mjbvz Thanks for doing this, I tackled mine via 845efe5d8e3 
Down to 75 errors...

**Comment by jrieken** [comment]
> Static properties overriding non-static property, microsoft/TypeScript#43563

We aren't tackling those given TS has acknowledge the issue and has a fix ready, right?

**Comment by Kingwl** [comment]
> > Static properties overriding non-static property, microsoft/TypeScript#43563
> 
> We aren't tackling those given TS has acknowledged the issue and has a fix ready, right?

Agreed.

**Comment by Kingwl** [comment]
Hi folks!

Seems the fix has already merged.

**Comment by mjbvz** [comment]
@alexdima @sbatten Just 6 errors remaining! Please take a look when you have a chance

@jrieken Do you have any idea about why `MirrorModel.version` is causing issues with the esm build? After adding `override` to `version`, `yarn gulp editor-esm-bundle` results in:

```
Launching the TS compiler at /Users/matb/projects/vscode/out-editor-esm...
vs/editor/common/services/editorSimpleWorker.ts(94,22): error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'MirrorTextModel'.
```

**Comment by mjbvz** [comment]
Done with 66fd0cba91ba903ebb5086f48175c18a5cdd6b84

Thanks everyone!
