### ISSUE TITLE
Show error messages in a better way when the message is very long

### ISSUE THREAD

**Issue by Zarel** [Microsoft/vscode#12060]
- VSCode Version: 1.5.2
- OS Version: macOS Sierra beta

Steps to Reproduce:
1. Open a file/directory with an error

![image](https://cloud.githubusercontent.com/assets/551184/18540631/ec3f26da-7ad4-11e6-8703-a9ccca784260.png)

Expected: The error is readable

Result: The error is cut off and there's no way to read the rest of the error

**Comment by bpasero** [comment]
@Zarel hovering over the message should show the full error, does it not?

**Comment by Zarel** [comment]
I'm pretty sure that was one of the first things I tried, but it's possible I forgot to...

**Comment by Zarel** [comment]
Oh, hey, it does.

It seems like it'd be better if the error message were taller so I could read it without a tooltip.

**Comment by hxegon** [comment]
This might seem like a minute thing (because it is 😄 ) but it interrupts keyboard flow because it requires a mouse action. As someone migrating from vim, I'd really appreciate a mouseless way to read long error messages. 🙏

**Comment by s-h-a-d-o-w** [comment]
Plus, it's not exactly convenient to manuall type the error into Google instead of being able to copy/paste...

**Comment by Yang09701194** [comment]
I hope I can get complete message by right click on it and there's copy full message menuitem to select, or it can be expanded to see the complete message.  Complete message is important to search the answer in the internet.
