### ISSUE TITLE
vscode for mac cannot use del key

### ISSUE THREAD

**Issue by Albert1102** [microsoft/vscode#120693]
When SSH connects to the Linux server, when del is used in the terminal, the key is replaced with a space, which cannot be deleted normally.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
