### ISSUE TITLE
Hex value and default value for `notebook.selectedCellBackground` appear inconsistent.

### ISSUE THREAD

**Issue by roydukkey** [microsoft/vscode#120643]
Just wanted to verify this isn't a mistake, as it appears the defaults are here are not equivalent:

https://github.com/microsoft/vscode/blob/07340c27f59b922bfcb8cf841e394df5981ff725/extensions/theme-defaults/themes/dark_vs.json#L22

https://github.com/microsoft/vscode/blob/07340c27f59b922bfcb8cf841e394df5981ff725/extensions/theme-defaults/themes/light_vs.json#L25

https://github.com/microsoft/vscode/blob/3dd2d431a01ab750a59d8be5d291e099778649bf/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2270-L2271

I would expect equivalency between `Color.fromHex('#383B3D').transparent(0.5)` and `#383B3D80`.

_Originally posted by @roydukkey in https://github.com/microsoft/vscode/issues/117449#issuecomment-796283068_

**Comment by rebornix** [comment]
@misolori can you help take a look?

**Comment by misolori** [comment]
The `notebook.selectedCellBackground` now inherits a new default:

https://github.com/microsoft/vscode/blob/dd37fc58cad260aae2c84a48a4c02bf89dd506d5/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2458-L2462

What issue are you seeing?

**Comment by roydukkey** [comment]
Maybe my concern is no longer valid then. It just seems that someone might have misequated `0x50 == .transparent(0.5)`, whereas, if it was desired for the theme json values to have been equivalent to the TypeScript, I would have expected `0x80 == .transparent(0.5)`.

**Comment by misolori** [comment]
Gotcha. Thanks for the ping, will close this as it's no longer relevant then. If you see any other issues please feel free to create a new issue.
