### ISSUE TITLE
A OOM issue occurred when VSCode only consumed 355MB/16GB physical Mem

### ISSUE THREAD

**Issue by JackABlack** [microsoft/vscode#120686]
- VS Code Version:March 2021 (version 1.55)
- OS Version: Win10_Home_2004_Build_19041.867

Steps to Reproduce:

1. Run my code
2. It Crushed

My code:
```python
dataset_list[1] is a numpy n-dimension-array(ndarray) with shape (2848,2048)

from pywt import dwt
import matplotlib.pyplot as plt
x,y = dwt(dataset_list[1].T,'db1')  # -> crush on this step
plt.scatter(x, y, alpha=0.6)
plt.show()
```

dump file is attached, but in folder "report" there is nothing, don't sure why.

Does this issue occur when all extensions are disabled?: Yes/No
Cannot do as I runs it inside Microsoft Jupyter Extension (One can not run jupyter code without Jupyter Notebook right :D)

[crush_dump.zip](https://github.com/microsoft/vscode/files/6268751/crush_dump.zip)

**Comment by JackABlack** [comment]
BTW, the code runs well on Conda-Jupyter, and the python kernel I used in VSCode is the same one I used in conda.
It quickly boomed my memory:
![Uploading image.png…]()

**Comment by rebornix** [comment]
@JackABlack can you share the screen shot of the notebook editor you are using to help troubleshoot?
