### ISSUE TITLE
Title bar style custom: title overlaps with menu bar

### ISSUE THREAD

**Issue by tohghua** [microsoft/vscode#120624]
* Window title bar style set to custom
* Open some code tabs, toggle between them, a blue title shows on left top corner, overlap with the menu bar. The title also show normally on center top.

Expected: title not show on left top corner.
![image](https://user-images.githubusercontent.com/12222062/113707816-093b8300-9713-11eb-8ef2-27b1d3fe2ca3.png)
![image](https://user-images.githubusercontent.com/12222062/113707913-28d2ab80-9713-11eb-8fec-c7713204183b.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.56GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 5589d2fa-ba96-4ae3-87c1-6d8e9c4009d2|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071

```

</details>

**Comment by sbatten** [comment]
upstream electron but looks to be win7 (unsupported)

**Comment by deepak1556** [comment]
Windows 7 is no longer supported, please check https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7 for additional context.
