### ISSUE TITLE
Linting is not working (Enable lint is not working)

### ISSUE THREAD

**Issue by francescowang** [microsoft/vscode#120623]
Issue Type: <b>Bug</b>

Linting is not enabling. I tried so many times. I can't see the error messages. 

VS Code version: Code 1.55.0 (Universal) (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id b6de9344-fce9-4a77-a3fe-ec449140e856|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
arepl|alm|2.0.2
python-preview|don|0.0.4
gc-excelviewer|Gra|3.0.41
vscode-test-explorer|hbe|2.19.6
vsc-python-indent|Kev|1.13.1
vscode-python-test-adapter|lit|0.6.7
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.3.4
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.0
vsliveshare|ms-|1.0.4070
autodocstring|njp|0.5.4
indent-rainbow|ode|7.5.0
errorlens|use|3.2.5
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
pythonvspyt943cf:30280190
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by dbaeumer** [comment]
@francescowang what kind of linting are you trying to enable?

**Comment by francescowang** [comment]
No worries. I sorted it out. I didn't elevate it in the global environment. 

sudo pip3 install pylint
