### ISSUE TITLE
Less linting not working for mixins with rulesets

### ISSUE THREAD

**Issue by jcdekoning** [Microsoft/vscode#12061]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

Steps to Reproduce:
1. Create a .less file with a mixin that has a ruleset as argument

`.tablet-and-larger(@rules){
    @media (min-width: @screen-sm) { @rules(); }
}
`
2. Less linting underlines @rules() on the @media line and also the last curly brace. The errors returned are
- } expected
- at-rule or selector expected 

http://lesscss.org/features/#detached-rulesets-feature

**Comment by davidcie** [comment]
Could be related to #12720 perhaps?

**Comment by rdennis** [comment]
Here is an example snippet taken from [lesscss.org](http://lesscss.org/features/#detached-rulesets-feature). It illustrates both issues with detached rulesets used in a nested media query, and rulesets passed directly as a mixin parameter.

<img width="534" alt="screen shot 2017-01-12 at 8 44 03 pm" src="https://cloud.githubusercontent.com/assets/1097629/21916712/f5f681a0-d907-11e6-91b1-d9c5e1570ce4.png">

<img width="343" alt="screen shot 2017-01-12 at 8 37 59 pm" src="https://cloud.githubusercontent.com/assets/1097629/21916655/9f9d8844-d907-11e6-8efb-2d3f115ef6d5.png">

**Comment by aeschli** [comment]
Fixed in the meantime. Verified in the January build.
