### ISSUE TITLE
Option to use old VS Code icon

### ISSUE THREAD

**Issue by mrgrieves4** [microsoft/vscode#120612]
Issue Type: <b>Feature Request</b>

As a visually impaired user, the new Big Sur icon set is really bad for me because all icons now look very similar (indistinguishable white blobs until I zoom right up close).

The old vs code icon was nice and distinct, and now it just looks like Chrome, Safari etc.

An option to use the old icon instead would be helpful.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

**Comment by misolori** [comment]
Thanks for the feedback. Please subscribe to https://github.com/microsoft/vscode/issues/120604, will close this as duplicate.
