### ISSUE TITLE
vscode 1.6 broke Git changes in gutter

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#12062]
- VSCode Version: 1.6insider
- OS Version: Win10

Steps to Reproduce:

1. Make changes to some version-controlled file 
2. Notice the absence of markings in the gutter which showed which lines have changed.
3. Despair, come to senses, wait while this issue is resolved & install vscode stable in the meanwhile.

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/18548966/dc654a2e-7b4b-11e6-89cd-17013446393c.png)

Does it reproduce when you run with `--disable-extensions`?

**Comment by gerane** [comment]
@joaomoreno I have this same issue and it persists with --disable-extensions

**Comment by kumarharsh** [comment]
I inspected the gutter and compared it with what vscode-stable has, and it seems like the marker for change is not even there in the DOM.

**Comment by joaomoreno** [comment]
I can totally reproduce this in Windows. Thanks guys.

**Comment by joaomoreno** [comment]
It doesn't reproduce when running from source though. Hm...

**Comment by joaomoreno** [comment]
I take it back, it does repro through source.
