### ISSUE TITLE
> v1.53, on CentOS 7 - locks up at startup, with 100% CPU

### ISSUE THREAD

**Issue by amachanic** [microsoft/vscode#120648]
- VS Code Version: 1.54, 1.55
- OS Version: CentOS 7

Steps to Reproduce:

1. Upgrade from 1.53 to either 1.54 or 1.55
2. Launch VS Code

Does this issue occur when all extensions are disabled?: Yes, the issue still occurs.

On startup, I can see two processes in 'top', each of which are consuming 100% of a CPU. The VS Code window is totally non-responsive. After some time a box pops up asking if I'd like to Wait or Force Quit.

I tried both 1.54 and 1.55. Earlier versions are working perfectly.

**Comment by gjsjohnmurray** [comment]
/duplicate

Since 1.54 CentOS 7 is no longer a supported platform. See #115784 for more information.
