### ISSUE TITLE
node_modules/.bin/tsc is used on an untrusted workspace

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#120677]
Version: 1.56.0-insider
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:13:17.592Z
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. Set `"workspace.trustEnabled": true` in the global `settings.json`
2. `git clone git@github.com:James-Yu/LaTeX-Workshop.git`
3. Open the LaTeX-Workshop directory.
4. Select `Don't Trust`
5. Select Terminal > `Run Build Task`
6. Select `tsc: build - tsconfig.json`
7. `> Executing task: /Users/tamura/src/github/LaTeX-Workshop/node_modules/.bin/tsc -p /Users/tamura/src/github/LaTeX-Workshop/tsconfig.json <` is executed without any warning.

`./node_modules/.bin/tsc` should not be used without any warning. Related to #106488.

**Comment by sbatten** [comment]
@alexr00 this will be handled by the task prompting experience i believe

**Comment by alexr00** [comment]
All tasks commands will soon require workspace trust. As workspace trust is a new feature, I just haven't gotten to add it to tasks yet.
