### ISSUE TITLE
WorkspaceConfiguration.get Returns Undefined For Nested Dotted Name

### ISSUE THREAD

**Issue by SilvioMarcovic** [microsoft/vscode#120634]
- VS Code Version: 1.55.0
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:
Accessing a local workspace config (.vscode/settings.json) via a dotted name returns undefined when the name is nested in the JSON.

1. Create local workspace config with above example config in `\.vscode\settings.json`
```json
{
    "a.b": "1",
    "c": {
        "x": "2",
        "y.z": "3"
    }
}
```
2. Execute `vscode.workspace.getConfiguration().get("c.y.z");` to see that value cannot be retrieved.

See the example screenshot where the path `x.y.z` is returning undefined while `a.b` returns the expected value `1`.
![image](https://user-images.githubusercontent.com/4059205/113715211-84883f00-96e9-11eb-8aef-a1d0aab1674c.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
This is designed. Dotted representation is only supported for settings keys and not for keys in values.

**Comment by SilvioMarcovic** [comment]
And how is it then possible to retrieve/change a value?

I am specifically looking at changing the default formatter for a specific language.

```json
{
    "[xml]": {
        "editor.defaultFormatter": "redhat.vscode-xml",
    }
}
```
I could not find a way to get/update the value of the key  `editor.defaultFormatter`.
Is this simply not supported or is there some other way how to access the values?

**Comment by sandy081** [comment]
You shall use the language configuration scope to get the language overridden values.

```
/**
	 * The configuration scope which can be a
	 * a 'resource' or a languageId or both or
	 * a '[TextDocument](#TextDocument)' or
	 * a '[WorkspaceFolder](#WorkspaceFolder)'
	 */
	export type ConfigurationScope = Uri | TextDocument | WorkspaceFolder | { uri?: Uri, languageId: string };

export function getConfiguration(section?: string | undefined, scope?: ConfigurationScope | null): WorkspaceConfiguration;
```

You can do the same for update

```
update(section: string, value: any, configurationTarget?: ConfigurationTarget | boolean, overrideInLanguage?: boolean): Thenable<void>;
```

**Comment by SilvioMarcovic** [comment]
oh, I totally missed that. Thanks for the help
