### ISSUE TITLE
Allow using variables as part of path and args values in terminal settings

### ISSUE THREAD

**Issue by pszlazak** [microsoft/vscode#120667]
Using [Terminal profiles](https://code.visualstudio.com/updates/v1_55#_terminal-profiles) introduced in `1.55` (via #45444) I tried to use system variables as part of `path` and `args` values but w/o success.

Example for `path`:
* this one **works**:
```
"terminal.integrated.profiles.windows": {
        "Yet Another PowerShell": {
            "path": "c:\\Users\\Piotr\\AppData\\Local\\Microsoft\\WindowsApps\\pwsh.exe"
        }
}
```
* this one **does not work** - it's not even listed on the list of available profiles:
```
"terminal.integrated.profiles.windows": {
        "Yet Another PowerShell": {
            "path": "%LOCALAPPDATA%\\Microsoft\\WindowsApps\\pwsh.exe"
        },
}
```

Same thing is observed if variable is used as part of value of `args`. Following configuration:
```
"terminal.integrated.profiles.windows": {
        "Yet Another PowerShell": {
            "path": "c:\\Users\\Piotr\\AppData\\Local\\Microsoft\\WindowsApps\\pwsh.exe"
            "args": [
                "-noexit",
                "-file",
                "%APPDATA%\\PowerShell\\oh-my-posh.ps1"
            ]
        }
}
```
fails with error:
```
The terminal process "c:\Users\Piotr\AppData\Local\Microsoft\WindowsApps\pwsh.exe '-noexit', '-file', '%APPDATA%\PowerShell\oh-my-posh.ps1'" terminated with exit code: 64.
```

**Comment by Tyriar** [comment]
This is supported but using a different cross-platform syntax:

```
"terminal.integrated.profiles.windows": {
        "Yet Another PowerShell": {
            "path": "${env:LOCALAPPDATA}\\Microsoft\\WindowsApps\\pwsh.exe"
        }
}
```

The `%VAR%` syntax may work but only if your _shell_ resolves them, VS Code will not by design.

You can read more about the variables at https://code.visualstudio.com/docs/editor/variables-reference

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode-docs/issues/4661 to add to the documentation

**Comment by dhgsg** [comment]
This example still does not work, though:

`        "tmux test": {
            "path": "tmux",
            "args": [ "new-session", "-A", "-s", "${workspaceFolderBasename}" ]`

The session ends up being named "${workspaceFolderBasename}" instead of using the name of the folder.

**Comment by Tyriar** [comment]
@dhgsg I'll look into it in the similar sounding https://github.com/microsoft/vscode/issues/126066. Can you post that example with machine information there? (OS, version, remote info if any, etc.)

**Comment by Tyriar** [comment]
@dhgsg you might also be seeing https://github.com/microsoft/vscode/issues/115560

**Comment by dhgsg** [comment]
Both of those look like they are related to what I see, thanks.
