### ISSUE TITLE
Visual Studio Code editor freezes randomly while editing CSS files

### ISSUE THREAD

**Issue by jsmasher** [Microsoft/vscode#12068]
- VSCode Version: 1.3.0 - 1.5.2
- OS Version: Windows 7

Steps to Reproduce:
1. Open any project with CSS files
2. Start editing CSS files

Visual studio code freezes after sometime discarding any changes made during that period.
![capture](https://cloud.githubusercontent.com/assets/19794992/18545218/cddb3cfc-7b55-11e6-8614-984b7ab52875.PNG)

**Comment by simonrozsival** [comment]
I have the same issue with both PHP and JS files - VS freezes and shows the same warning. Also the process uses 30% of the CPU time while frozen.

**Comment by kikemx78** [comment]
Same thing here

**Comment by Applicafroguy** [comment]
same issue with angular 2

**Comment by aeschli** [comment]
Haven't been able to reproduce this issue. Closing for now.
Please speak up or file a new issue if you still have random freezes.
