### ISSUE TITLE
Extension recommendations get downloaded although disabled

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode#120716]
After updating to v 1.55.0 and updating all installed extensions, extension recommendations are getting downloaded and displayed although disabled:

![Extensions Recommended](https://user-images.githubusercontent.com/9283914/113844527-dcc84b00-9794-11eb-9346-ad8bfd00ec8b.png)

- VS Code / OS Version:
   Version: 1.55.0 (user setup)
   Commit: c185983a683d14c396952dd432459097bc7f757f
   Datum: 2021-03-30T16:01:55.261Z
   Electron: 11.3.0
   Chrome: 87.0.4280.141
   Node.js: 12.18.3
   V8: 8.7.220.31-electron.0
   Betriebssystem: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Update to VS Code to version 1.55.0
2. Update all extensions

**Comment by sandy081** [comment]
It is just the recommendations view is shown and none of them are downloaded or installed. The setting is to disable the notifications for extension recommendations not for the view. You can hide the view as follows:

![image](https://user-images.githubusercontent.com/10746682/114410889-037aed00-9bac-11eb-871c-80e8f64f63ea.png)

**Comment by SetTrend** [comment]
@sandy081: Thank you for clarifying.

The help text in Setting tells differently (at least in the German localization): "No recommendations are shown." This is confusing.

Shouldn't the help text get updated then at least, so it won't be misleading?
<br/>

What are the recommendations based on? Does VS Code send any information about my repository to receive recommendations? If so, can I disable sending any information to servers in VS Code?

**Comment by sandy081** [comment]
Help text shall be following, probably the language packs you installed are not up to date.

```
When enabled, the notifications for extension recommendations will not be shown.
```

> What are the recommendations based on? Does VS Code send any information about my repository to receive recommendations? If so, can I disable sending any information to servers in VS Code?

I would ask @sbatten help to answer this, since I am not sure about some recommendations (experiments & workspace tags),

**Comment by sbatten** [comment]
Experiments can be disabled with `workbench.enableExperiments` and the worskpace configuration recommendations are pulled from the marketplace and calculated locally, not the other way around AFAIK
