### ISSUE TITLE
Debug console does not scroll to bottom reliably

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#120737]
Issue Type: <b>Bug</b>

While debugging, the debug console will very often not scroll to the bottom of the output and get stuck somewhere, leaving the user to scroll to the bottom manually.

To reproduce, you can load the following code into VS Code and just start a debugging session with the Node.js debugger.

```js
(async() => {
  for (let i = 0; i < 200; ++i) {
    console.info(`[] - Visible ${i}`);
  }

  await new Promise(resolve => setTimeout(resolve, 100));

  console.info("Hidden");
  console.info("Hidden");
  console.info("Hidden");
  console.info("Hidden");
  console.info("Hidden");
  console.info("Hidden");
})();
```

For me, this reliably will not show the `Hidden` log lines.

![image](https://user-images.githubusercontent.com/1658949/113884485-4c533000-97bf-11eb-96ff-d105332571da.png)

Confusingly, the exact logged text seems to be relevant. If you change the logged line to `XX - Visible ${i}`, this will not reproduce.

---

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (28.32GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Code - OSS|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (26.40GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.2.2
vsc-prolog|art|0.8.23
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-graphql|Gra|0.3.15
terraform|has|2.9.1
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
template-string-converter|meg|0.4.7
vscode-docker|ms-|1.11.0
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.27
vscode-yaml|red|0.17.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/117674
