### ISSUE TITLE
Add CURRENT_TZDIFF to snippet variables

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode#120715]
When doing snippets, [we have *almost* all required tools to indicate current time](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables). However, what's still missing is timezone info.

My proposal is to add `CURRENT_TZDIFF`, which resolves to `+01:00`, `-00:30`, etc.

This way, we can represent an absolute time in a snippet, such as `${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}+${CURRENT_TZDIFF}`

**Comment by ericthomas1** [comment]
Need a way to get ideas like this more visibility. Upvoting a Github issue is one way, but having a more visible "Ideas list" would be ideal.
