### ISSUE TITLE
Extension bisect whitelist

### ISSUE THREAD

**Issue by Yajo** [microsoft/vscode#120799]
I'm having a performance problem with python debugging. The debugger takes about 15s to connnect to the container.

When I disable all extensions except the python one, it connects immediately.

However, when I run extension bisect, the results are unreliable, because when bisecting disables the python extension itself, I have to say "It works" to continue with the next iteration.

My proposal is that there should be a way to whitelist some extensions while bisecting. For this particular case, I'd need to whitelist the Python one because, without it, I cannot debug and thus I cannot test if there's the problem or not.

**Comment by IllusionMH** [comment]
/duplicate of #113568

See https://github.com/microsoft/vscode/issues/113568#issuecomment-759334161 for current workaround
