### ISSUE TITLE
Editor Decoration Badges appear to be incorrect

### ISSUE THREAD

**Issue by fbehrens** [microsoft/vscode#120732]
Issue Type: <b>Bug</b>

My Git status is clean, but in the Editor Tab it appears to show some information as if the file has been modified. I do not know exactly if it is the git status, which should be displayed.

![image](https://user-images.githubusercontent.com/13704/113877655-33478080-97b9-11eb-9ea4-a304c5e3dfe1.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.09GB free)|
|Process Argv|x:\\scripts2\\wbadocs\\workspaces\\wba\\0t0x.code-workspace --crash-reporter-id 7daf0f5a-afda-4756-8500-6d6a66df5ae7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: by0t0x|
|OS|Windows_NT x64 10.0.14393|
|CPUs|Intel(R) Xeon(R) CPU E7-8867 v3 @ 2.50GHz (8 x 2494)|
|Memory (System)|32.00GB (26.57GB free)|
|VM|100%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
codeswing|cod|0.0.16
bracket-pair-colorizer-2|Coe|0.2.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
markdown-mermaid|bie|1.9.2
xml|Dot|2.5.1
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
graphviz-preview|EFa|1.5.0
agili|fbe|0.1.0
vscode-drawio|hed|1.4.0
git-graph|mhu|1.30.0
csharp|ms-|1.23.9
mssql|ms-|1.10.1
hexeditor|ms-|1.5.0
powershell-preview|ms-|2021.4.1
vsliveshare|ms-|1.0.4070
vscode-sort-json|ric|1.20.0
svelte-vscode|sve|104.9.0
workspace-explorer|tom|1.7.0
sql|vsc|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoccf:30282075
vscoresta800:30284044
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by gjsjohnmurray** [comment]
Do you have a non-zero Warnings count on the statusbar? And any entries on the Problems panel?

**Comment by fbehrens** [comment]
I have. I have tons of problems, as I am not bothered much about those reported by powershel Script Analyser

So the number should reflect the count of problems ? Does `9+` means more than 9 problems?

I have not figured out what the badges should say. I tend to deactivate and not care about them, but I care about VSCODE and that the features should work reliable.

**Comment by gjsjohnmurray** [comment]
> So the number should reflect the count of problems ? Does `9+` means more than 9 problems?

Correct. If you don't want the editor tabs to show this information, toggle the `workbench.editor.decorations.colors` and `workbench.editor.decorations.badges` settings.

**Comment by ArturoDent** [comment]
Related, see https://github.com/microsoft/vscode/issues/120345

**Comment by fbehrens** [comment]
Thanks, I close for now, until I can be more specific in my report
