### ISSUE TITLE
Tab moves focus permanently

### ISSUE THREAD

**Issue by amykapernick** [microsoft/vscode#120712]
Issue Type: <b>Bug</b>

I have the "Tab moves focus" accessibility setting (https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping) off, but when I try and use the tab key within an editor window it moves to another pane. I'm not in a read only file

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (2.79GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/amy/web/portal --remote=wsl+Ubuntu-20.04 --crash-reporter-id 73f7d234-e805-4a26-bb0d-1bbaf0002b04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|2.92GB (0.70GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-cloak|joh|0.3.0
dotenv|mik|1.0.1
remote-wsl|ms-|0.54.6
vsonline|ms-|1.0.3076
material-icon-theme|PKi|4.6.0
nunjucks|ron|0.3.0
markdown-yaml-preamble|bie|0.0.4
better-toml|bun|0.3.2
path-intellisense|chr|2.3.0
twitch-highlighter|cla|1.0.2
vscode-eslint|dba|2.1.19
githistory|don|0.6.16
nunjucks-vscode-extensionpack|dou|0.0.1
nunjucks-template|ese|0.3.4
vs-code-xml-format|fab|0.1.5
vscode-graphql|Gra|0.3.15
stylelint-plus|hex|0.53.1
path-autocomplete|ion|1.17.1
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestaticwebapps|ms-|0.5.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
azure-account|ms-|0.9.8
vsliveshare|ms-|1.0.4070
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-yaml-sort|Pas|4.0.0
ngrok-for-vscode|phi|1.9.0
vscode-yaml|red|0.17.0
vscode-stylelint|sty|0.86.0
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by amykapernick** [comment]
Seems to be the same issue as https://github.com/microsoft/vscode/issues/106755 has occurred since updating VS Code

**Comment by isidorn** [comment]
@amykapernick I can not reproduce this. Can you reproduce with VS Code insiders https://code.visualstudio.com/insiders/

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `Tab`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`Tab`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
