### ISSUE TITLE
Add "new line at end of file" option

### ISSUE THREAD

**Issue by Mag-Stellon** [Microsoft/vscode#12076]
- VSCode Version: 1.5.2
- OS Version: Windows 8.1

It would be cool to add the possibility to add a new line at the end of a file systematically :).

**Comment by mrmlnc** [comment]
Have you tried to use **Editorconfig** extension?

**Comment by bpasero** [comment]
Can be done in 1.8 via `"files.insertFinalNewline": true`

**Comment by codeithuman** [comment]
Anyone know if there is a way to removed extra newlines at the end of a file on save? `"files.insertFinalNewline": true` will add a new line if one doesn't exist, but I'd like to remove extra new lines. For example I have four new lines at the bottom of my file, I'd like only one to remain after saving.

**Comment by codeithuman** [comment]
This extension does what I want, https://marketplace.visualstudio.com/items?itemName=jmlntw.vscode-ensure-single-final-newline. 

And there is an open issue to add it to vscode, https://github.com/Microsoft/vscode/issues/16599.

**Comment by dewetblomerus** [comment]
That extension was deprecated, use the following instead:
```
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
```

`trimTrailingWhitespace` was not asked for in this thread but all three of these could be considered a sensible default.
