### ISSUE TITLE
Opening latest VSCode Insider results in a completely gray window without controls

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/vscode#120725]
- VS Code Version: 1.56.0-insider
- OS Version: Windows 10 (1909)

![image](https://user-images.githubusercontent.com/5993909/113863199-afd26300-97a9-11eb-817e-e084162f2ff4.png)

Steps to Reproduce:

1. Open VSCode

Does this issue occur when all extensions are disabled?: Yes

I have tried with the following flags after reading some issues:
--disable-extensions
--disable-gpu
--disable-features=CalculateNativeWinOcclusion

**Comment by KaoImin** [comment]
Same case.

**Comment by gjsjohnmurray** [comment]
Probably #120655

**Comment by gjsjohnmurray** [comment]
pinging @bpasero

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/114459#issuecomment-814846486

**Comment by gjsjohnmurray** [comment]
See also https://github.com/microsoft/vscode/issues/114459#issuecomment-814846486

**Comment by JonWallsten** [comment]
Confirmed working after clearing cache! Thanks!
