### ISSUE TITLE
Error when inserting new cell

### ISSUE THREAD

**Issue by jorislimonier** [microsoft/vscode#120738]
- VS Code Version: 1.55.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Open a Jupyter Notebook running julia
2. Click the `+` button to "Insert cell below"

Does this issue occur when all extensions are disabled?: Yes

The following occurs when I follow the "Steps to reproduce" above (one such error per times clicked the `+` button)

![image](https://user-images.githubusercontent.com/43946637/113885014-c4b9f100-97bf-11eb-8ddc-10d89f50d097.png)

However if I close VS Code and reopen it, the cells are there, well formatted.

**Comment by rebornix** [comment]
@jorislimonier can you share the screen shot of the whole editor so we can tell if it's using a custom webview editor or the native one?

**Comment by jorislimonier** [comment]
Here is the screenshot

![image](https://user-images.githubusercontent.com/43946637/113963625-33cc2f80-982a-11eb-8ba2-3de221a320b5.png)

Please let me know if you need anything else.

**Comment by rebornix** [comment]
/extJupyter

Please file against the Jupyter team as this is contributed by them.
