### ISSUE TITLE
[Regression insiders] UI for button is misplaced in quickpick

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#120786]
Version: 1.56.0-insider (user setup)
Commit: bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a
Date: 2021-04-07T12:30:14.880Z
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

Set up a quickpick with a button.

![image](https://user-images.githubusercontent.com/13199757/113982389-8c390800-97fd-11eb-8ac2-0ccbfe35e714.png)

While in stable VSCode, button appears normally,
![image](https://user-images.githubusercontent.com/13199757/113982565-c4404b00-97fd-11eb-94d9-8104080f926b.png)

**Comment by gjsjohnmurray** [comment]
Perhaps a consequence of #120247 so pinging @joaomoreno

**Comment by pixieaka** [comment]
@joaomoreno Insider 5904b7b686e9274631893d560fdbc55a5567f878

Insider
![image](https://user-images.githubusercontent.com/17777237/114094742-f4025800-98bc-11eb-9a5a-f5e972ea040e.png)
Stable
![image](https://user-images.githubusercontent.com/17777237/114094772-fd8bc000-98bc-11eb-92a8-ed6efc0f42f4.png)
