### ISSUE TITLE
Improve creation of launch.json JSON scheme

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#120711]
Today the JSON scheme for the launch.json is dynamically created from all debug extension contributions and predefined common propoerties. This results in a typical size of 42000 lines.

Most of these lines are duplicated because the schema has 3 sub-schemas for the platform sections "osx", "windows", and "linux". Instead of replicating the schema 3 times, we should use JSON's reference mechanism `$ref`.
With this approach we could easily bring down the size to 14000 lines.

Another area for improvement are the duplicated predefined properties. Instead of duplicating them into every sub-schema, we could try to make the sub-schema inherit from some base schema. But it could be that this is not possible in JSON schema.

**Comment by isidorn** [comment]
@weinand this makes sense, do you have an example of a json schema that uses the `$ref` syntax? That way I could copy that approach.

**Comment by weinand** [comment]
@isidorn the DAP spec is a good example for the `$ref` syntax.

We could just collect all schema contributions from the extensions in a "definitions" section like [here]( https://github.com/microsoft/debug-adapter-protocol/blob/3fa97489e227fdf933e8dd0325123f9bf74570d5/debugAdapterProtocol.json#L8) and refer to them in the real schema like [here](https://github.com/microsoft/debug-adapter-protocol/blob/3fa97489e227fdf933e8dd0325123f9bf74570d5/debugAdapterProtocol.json#L29).
As definition names we could use the debug type name (which should be unique).

With this our big "oneOf" would just have a small list of `$ref`s to the "definitions".

**Comment by isidorn** [comment]
@weinand this makes good sense.

Adding help wanted in case there is a JSON schema wizard willing to help.
Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/common/debugger.ts#L259

If not I can look into this in May.

**Comment by isidorn** [comment]
Thanks to @aeschli help we have improved this a lot by using references to definitions.

**Comment by weinand** [comment]
@isidorn I haven't seen an example of a resulting schema but from reviewing your changes it looks like you could fully implement my proposal. Thanks, great work!

I expect a size reduction by 4...

**Comment by isidorn** [comment]
@weinand Thanks for finding this!
We use references wherever possible. I think the size reduction will be quite a bit
