### ISSUE TITLE
New version of visual studio: blank screen

### ISSUE THREAD

**Issue by Cliff0317** [microsoft/vscode#120772]
- VS Code Version: Insiders version
- OS Version: Windows 10, latest

Steps to Reproduce:
1. Open visual studio code insiders version. Update it.
2. I just see a blank screen. No X buttons. Did it crash?
![image](https://user-images.githubusercontent.com/59384254/113952117-a0a1f280-9847-11eb-9f61-8101cf382f82.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/114459#issuecomment-814846486 for how to recover.
