### ISSUE TITLE
Save all keyboard short cut feature

### ISSUE THREAD

**Issue by timlind** [Microsoft/vscode#12070]
With Javascript compile watchers, saving all files at once is crucial for avoiding unnecessary build failures.

On Mac OS there is no keyboard shortcut to "Save All" files.

**Comment by rozzzly** [comment]
https://github.com/Microsoft/vscode/issues/1760

Google is your friend, my friend.

**Comment by timlind** [comment]
Thanks @rozzzly, I've subsequently noticed duplicate issues. This one gives some motivation for baking it in as a default.

**Comment by bpasero** [comment]
`{ "key": "ctrl+shift+s", "command": "workbench.action.files.saveAll" }`
