### ISSUE TITLE
Insiders version is broken on a mac

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [microsoft/vscode#120723]
- VS Code Version: latest insiders updated April 7
- OS Version: MacOS Big Sur 11.2.3

Steps to Reproduce:

1. Update to latest insiders version
2. Restart
3. Observe views are not initialized. Only shows main empty app window. None of main menu items work.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
see https://github.com/microsoft/vscode/issues/114459#issuecomment-814846486
