### ISSUE TITLE
Load snippets asynchronously in autocompletion before IntelliSense results

### ISSUE THREAD

**Issue by Ares9323** [microsoft/vscode#120746]
Hello, I've been using Visual Studio Code with Unreal Engine for a while, moving from Visual Studio 2019 for a main reason: Snippets.

IntelliSense with Unreal is a real pain in both softwares (It can take up to 30s to load suggestions), it's not a hardware problem (I have a Ryzen 3900x  and a PCIE 4.0 NVME Drive, both at less than 20%)

I tried disabling all the extensions and enabling them one by one, the problem is the [C/C++ Official Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) obviously, because Unreal tends to include a billion of folders into the project.

I Mainly use my snippets rather than IntelliSense suggestions but I would like to keep it enabled, but it's really annoying that I have to wait up to 30s for autocompletion to pop up so I had this idea, is it possible to make snippets appear and then wait for the IntelliSense to provide its results? It would be a great solution for large projects!

Thank you in advance! I'm available for any further information you need!

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest"

**Comment by Ares9323** [comment]
> This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title 😳 Anyways, searching for issues with the same labels will likely help you 👉
> [https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"suggest](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22suggest)"

Thank you for your answer, I tried to look for a duplicate before opening an issue (like I always do) but unfortunately I had no success, I also tried to look for alternative solutions (like adding a secondary shortcut in addition to CTRL + SPACE to use two separate autocompletion boxes).

I'll try again to search a solution in between the issues you linked me,
Thank you again, have a nice day!
