### ISSUE TITLE
yarn web not work and Error: ENOENT: no such file or directory, stat '~/vscode/out/semver-umd.js'

### ISSUE THREAD

**Issue by vagusX** [microsoft/vscode#120784]
- VS Code Version: vscode oss source code commit@1f8643ef7
- OS Version:

Steps to Reproduce:

1. yarn web
2. open localhost:8080

![image](https://user-images.githubusercontent.com/6828924/113981410-39516600-987a-11eb-86c1-8975a86b8e95.png)

and copy `src/vs/base/common/semver/semver.js` to `out/semver-umd.js`
and everything works

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by connor4312** [comment]
Make sure you're running `yarn watch` and `yarn watch-web` is running.
