### ISSUE TITLE
antivirus alert

### ISSUE THREAD

**Issue by kartikeysharma98281** [microsoft/vscode#120720]
Issue Type: <b>Feature Request</b>

when i run my c++ code in terminal then the code run smothly but affter a few seconds my antivirus alert me with a warning of virus in the file where my code is . please check it 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

**Comment by meganrogge** [comment]
Sounds like this is a problem with your antivirus software, not VS code
