### ISSUE TITLE
VSCode's Icon display wired in Finder.app's toolbar.

### ISSUE THREAD

**Issue by imeteora** [microsoft/vscode#120708]
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Open macOS's `Finder.app`. 
2. Open quick menu, and click `Customize toolbar...`, drag `VSCode` onto toolbar. 
3. You will find `VSCode` icon is shows abnormal, like abrasion.

Does this issue occur when all extensions are disabled?: Yes/No

![Screen Shot 2021-04-07 at 3 50 01 PM](https://user-images.githubusercontent.com/1861511/113830172-eb285e00-97b8-11eb-970d-02ec486db610.png)

**Comment by gjsjohnmurray** [comment]
/duplicate and will be fixed in upcoming 1.55.1
