### ISSUE TITLE
Environment not retrieved when launching VS Code from the macOS dock when default shell is PowerShell

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#120768]
Steps that should work but don't (these will be verification steps):

1. get PowerShell for macOS if you don't have it
2. see what path was added to `/etc/shells` (`cat /etc/shells`)
3. set it as your default shell: `chsh -s /path/to/pwsh`
4. launch VS Code from the dock/finder
5. Create a workspace with the below task
6. Run the task
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "My Task",
			"type": "shell",
			"command": "$env:PATH",
			"problemMatcher": []
		}
	]
}
```
> All this does is spit out what's on your PATH

**Actual**
```
/YOUR/POWERSHELL/PATH:/usr/bin:/bin:/usr/sbin:/sbin
```

**Expected**
Something like:
```
/YOUR/POWERSHELL/PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
> Note the inclusion of /usr/local/bin

This is because we fail to get the UnixShellEnvironment. You can confirm this by looking in ` Log (Main) `output, you should see:
```
[2021-04-07 15:06:09.107] [main] [error] getUnixShellEnvironment#error Failed to get environment
```

**Comment by TylerLeonhardt** [comment]
another great verification step is replacing the command in the task and putting something like `docker --version` or `node --version`. This will likely fail saying it couldn't find the command `docker`... because the environment wasn't set up properly.

**Comment by rzhao271** [comment]
I'm still getting the actual output instead of the expected output when I repeated the verification steps on my Mac.
