### ISSUE TITLE
Rename file with "Git: Rename" not working ?

### ISSUE THREAD

**Issue by moocan** [microsoft/vscode#120773]
- VS Code Version: 1.55.0
- OS Version: Ubuntu 20.04 with git 2.31.0

Steps to Reproduce:

1. Rename a file or folder in a git repository with Visual Studio Code
2. Renamed file is marked as a `deleted (untracked)` file and as a `new (untracked)` file

Using directly in git repository `git mv fileoldname filenewname` has a different behavior. 
File is marked as `renamed (staged)` and not as `deleted (untracked)` and `new (untracked)`.

I found this closed issue [Rename file with "Git: Rename"](https://github.com/microsoft/vscode/issues/93299) but it is locked (and all related issues are closed too) and I cannot find any documentation on it.

It seems that the pull request [97486](https://github.com/microsoft/vscode/pull/97486/commits/31ee5b96449103913998a073686fe69f1f6e3eef) has been marged on November 2020, but I don't  find any `git context menu` or `Git: Rename` anywhere (even with ctrl+shift+P) but only the standard `Rename file` (even inside a valid Git repository which is at the root of the workspaceFolder and seen by Visual Studio Code Source Control).

Does this issue occur when all extensions are disabled?: Yes

Regards

**Comment by DennieMello** [comment]
i have a similar problem

**Comment by DennieMello** [comment]
> * VS Code Version: 1.55.0
> * OS Version: Ubuntu 20.04 with git 2.31.0
> 
> Steps to Reproduce:
> 
> 1. Rename a file or folder in a git repository with Visual Studio Code
> 2. Renamed file is marked as a `deleted (untracked)` file and as a `new (untracked)` file
> 
> Using directly in git repository `git mv fileoldname filenewname` has a different behavior.
> File is marked as `renamed (staged)` and not as `deleted (untracked)` and `new (untracked)`.
> 
> I found this closed issue [Rename file with "Git: Rename"](https://github.com/microsoft/vscode/issues/93299) but it is locked (and all related issues are closed too) and I cannot find any documentation on it.
> 
> It seems that the pull request [97486](https://github.com/microsoft/vscode/pull/97486/commits/31ee5b96449103913998a073686fe69f1f6e3eef) has been marged on November 2020, but I don't find any `git context menu` or `Git: Rename` anywhere (even with ctrl+shift+P) but only the standard `Rename file` (even inside a valid Git repository which is at the root of the workspaceFolder and seen by Visual Studio Code Source Control).
> 
> Does this issue occur when all extensions are disabled?: Yes
> 
> Regards

Studied the issue in more detail. github realizes that the file has been renamed. But there are no changes in the vscode version history. Install the Gitlens extension and all changes will be visible in the file history section. (Must be enabled in the block settings)

![Снимок экрана 2021-04-08 в 08 13 45](https://user-images.githubusercontent.com/39631512/113971940-67b34f00-9842-11eb-88d5-e77c80b892bc.jpg)

**Comment by eamodio** [comment]
Are you not seeing _Git: Rename_ in the command palette? It only shows if there's an open file (as it renames the open editor).

But what you describe is expected and how git works. The only difference with renaming a file directly vs with `git mv` is that `git mv` auto-stages the file at the end. If you staged the add/delete after the rename, you will see the same behavior.

At the same time, I've just fixed an issue with paths (in some cases) with _Git: Rename_ in tomorrow's insiders build.

**Comment by moocan** [comment]
@eamodio 

Hello,
Thank you very much for your explanations.

Regards
