### ISSUE TITLE
Update toolbar actions with hover feedback

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#120753]
Now that https://github.com/microsoft/vscode/issues/120226 has added hover feedback, we should look at improving the other areas that use this to make them feel consistent. Here's an idea to update the notebook toolbar and status bar items to also have matching corners:

![CleanShot 2021-04-07 at 07 47 33](https://user-images.githubusercontent.com/35271042/113919147-19e20c80-9798-11eb-9766-fee09bb211c5.gif)

We'd need to account for when items in the status bar that have a bg color (like the remote indicator or error bg) 

cc @bpasero for status bar, @rebornix for notebooks

**Comment by misolori** [comment]
Also worth looking at the activity bar as well, but that seems like it needs more consideration as we have the active indicator and active background color token cc @sandy081 

<img width="400" src="https://user-images.githubusercontent.com/35271042/113920524-bd7fec80-9799-11eb-887f-b27f0f7f1b29.gif">

**Comment by sandy081** [comment]
@misolori hover backgrounds in activity bar and panel are handled here - https://github.com/microsoft/vscode/issues/118077#issuecomment-819549234

**Comment by joaomoreno** [comment]
@misolori After playing around with it today, I'm not entirely convinced that the hover background color on activity actions and panel titles works as well as it does in tiny 16px actions. I would simply keep a foreground hover change on those, what do you think?

**Comment by sandy081** [comment]
Removed hover background until we come to a conclusion.

**Comment by sandy081** [comment]
I liked the hover background with custom hovers. I felt they go well along together.

**Comment by bpasero** [comment]
I like the hover feedback on toolbar actions a lot, but feel they are not so nice in activity bar and panel given we already have hover feedback there for a long time. 

I would decouple the idea of custom hovers there from the hover feedback imho. You can do custom hovers but keep the current hover feedback.

**Comment by joaomoreno** [comment]
My opinion copied from Slack is almost @bpasero's verbatim:

> there are two distinct UI features here that I wish we decouple asap:
> - tooltips
> - hover background color on activity and panel
> the tooltips are great for discoverability: that should be behind a setting. but the hover background color on activity and panel gives a heaviness to the workbench: that should just be reverted. when I added hover background color to actions I tried activity bar and panel and did not push that on purpose, since it looks really odd. please consider just removing this @sandy081

**Comment by misolori** [comment]
Closing in favor of #118077
