### ISSUE TITLE
vscode 图标显示异常

### ISSUE THREAD

**Issue by evil123** [microsoft/vscode#120798]
- VS Code Version:1.55.0
- OS Version:big sur 11.2.3
1.vscode 图标显示异常

**Comment by evil123** [comment]
VS Code Version:1.55.0
OS Version:big sur 11.2.3
1.vscode Icon display is abnormal

**Comment by wujunchuan** [comment]
https://github.com/LeekHub/leek-fund/issues/207

vscode Icon display abnormal like this

```json
// from package.json
  "commands": [
      {
        "command": "leek-fund.viewFundRank",
        "title": "基金排行榜",
        "icon": {
          "light": "resources/light/rank.svg",
          "dark": "resources/dark/rank.svg"
        }
      },
]
```

**Comment by yzhou15** [comment]
![111](https://user-images.githubusercontent.com/27675355/116798413-b55d6780-ab21-11eb-9428-1096e7fe12e5.png)
The icon display of activity bar and menu bar doesn't look normal. I don't know why?

**Comment by phonzia** [comment]
The same issue appeared at vscode stable version 1.56.0, macos Big sur

**Comment by giscafer** [comment]
same issue.
