### ISSUE TITLE
New Multiple-cursor feature and goToImplementation

### ISSUE THREAD

**Issue by kg-currenxie** [microsoft/vscode#120788]
- VS Code Version: 1.55.0
- OS Version: MacOS 10.15.6

Steps to Reproduce:

1. Upgrade to 1.55.0
2. Alt-click on a definition (react component in this case)

- Expected: Go to implementation (as it did previously, with my goto settings)
- Actual: Goes to definition

So I went into settings, and changed the new `Editor › Goto Location: Alternative Declaration Command` things.

![Screenshot 2021-04-08 at 15 00 15](https://user-images.githubusercontent.com/48229166/113983622-b382ea00-987c-11eb-9d23-a08489f4af25.png)
![Screenshot 2021-04-08 at 15 00 21](https://user-images.githubusercontent.com/48229166/113983629-b54cad80-987c-11eb-90e1-227f684d4080.png) 

But it still goes to the definition.

Keyboard debug events:
```
[2021-04-08 15:06:19.278] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [alt], code: AltLeft, keyCode: 18, key: Alt
[2021-04-08 15:06:19.279] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [alt], code: AltLeft, keyCode: 6 ('Alt')
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

Is it supposed to work? Or am I missing something with the new settings? :)

**Comment by alexdima** [comment]
Did you perhaps change this setting?

```
	// The modifier to be used to add multiple cursors with the mouse. The Go To Definition and Open Link mouse gestures will adapt such that they do not conflict with the multicursor modifier. [Read more](https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier).
	//  - ctrlCmd: Maps to `Control` on Windows and Linux and to `Command` on macOS.
	//  - alt: Maps to `Alt` on Windows and Linux and to `Option` on macOS.
	"editor.multiCursorModifier": "alt",
```

**Comment by kg-currenxie** [comment]
@alexdima not sure how it matters, it just flips the modifier key?
Anyway, I did try, alt+click or ctrl+click still goes to the definition, and not implementation

**Comment by alexdima** [comment]
@jrieken Can you also help here please? It looks like these settings might not be honored.

**Comment by jrieken** [comment]
Can you try this with [VS Code Insiders](https://code.visualstudio.com/insiders/)? Specifically for TS there was a bug with bogous result sorting which can cause this

**Comment by kg-currenxie** [comment]
Sure i can try :)

**Comment by kg-currenxie** [comment]
@jrieken insiders works as intended!

**Comment by jrieken** [comment]
Alright. Thanks for the update. 

> Update: I will move over all my other settings and extensions, just to make sure :P

fyi - setting sync should be able to do that for you. you say what data source to use: stable or insiders

**Comment by kg-currenxie** [comment]
Yes, i did setup sync! very good and fast :D
