### ISSUE TITLE
Error loading workspace in vscode 

### ISSUE THREAD

**Issue by AnannyaShanmugam23** [microsoft/vscode#120783]
- VS Code Version:latest
- OS Version: Ubuntu virtual box
- Error loading workspace: err: exit status 1: stderr: unexpected directory layout: import path: github.com/ root:  expand root:  expand dir:  separator: / : packages.Load error
Source :Go(Extension)

Due to this error i cant jump between files in the repo and vscode doesnt show any errors in code 

Does this issue occur when all extensions are disabled?: Yes/No
No it doesnt show any error but i need those extensions for the code to work

**Comment by hyangah** [comment]
It looks like an issue of the extension. Please file an issue in [the extension's issue tracker](https://github.com/golang/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=).
