### ISSUE TITLE
Automatically attach cpuprofile to issues when extension causes high cpu load 

### ISSUE THREAD

**Issue by go-nelango** [microsoft/vscode#120767]
`Extension causes high cpu load` issues that are filed for extensions often do not have `cpuprofile.txt` attached which makes them non-actionable. Instead of just indicating to the user about attaching this file, can vscode automate this attachment if user provides consent?

**Comment by RMacfarlane** [comment]
No, this unfortunately isn't possible. GitHub does not provide a public API for uploading files.
