### ISSUE TITLE
Copy button in web marketplace of extensions doesn't copy on Linux

### ISSUE THREAD

**Issue by DanieleMar** [microsoft/vscode#120793]
When I click the copy button on the marketplace of vscode extensions on Linux, it doesn't copy anything
It happens with all extensions on the web marketplace.

![12](https://user-images.githubusercontent.com/13423042/113986877-0a24ff80-984e-11eb-8a14-35d3a5381ac2.jpg)
- OS Version: Ubuntu, Google Chrome
- Extension in the picture: https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense

**Comment by connor4312** [comment]
Please open an issue on https://github.com/microsoft/vsmarketplace
