### ISSUE TITLE
终端显示异常，每个字母之间都有个空格，每个中文之间有两个空格，而光标位置在原处

### ISSUE THREAD

**Issue by 1059811622** [microsoft/vscode#120721]
Issue Type: <b>Bug</b>

将vscode升级到了最新版本
![image](https://user-images.githubusercontent.com/76728400/113857431-191b9b80-97d5-11eb-9798-4e8d7ab5d8b0.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.64GB free)|
|Process Argv|--crash-reporter-id d6f4f826-b8a7-4e36-bf47-70cc7ca5cfee|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.6
wechat-snippet|Cha|0.4.11
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
wxml-vscode|cny|0.1.2
vscode-eslint|dba|2.1.19
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
beautify|Hoo|1.5.0
vscode-language-pack-zh-hans|MS-|1.55.2
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
vetur|oct|0.33.1
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.25.1
vscode-manifest-yaml|Piv|1.25.1
vscode-spring-boot|Piv|1.25.1
view-in-browser|qin|0.0.5
minapp-vscode|qiu|2.2.2
java|red|0.76.0
LiveServer|rit|5.6.1
vue-helper|she|2.4.7
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-spring-boot-dashboard|vsc|0.2.0
vscode-spring-initializr|vsc|0.7.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
vscoreces:30285483
pythondataviewer:30285071

```

</details>

**Comment by 1059811622** [comment]
这个问题是在将vscode全屏下并且左侧打开了某个栏框出现的，如果将栏框关闭就可以解决，或者是退出全屏再进入全屏就可以解决了。

**Comment by jasonlyu123** [comment]
>终端显示异常，每个字母之间都有个空格，每个中文之间有两个空格，而光标位置在原处 

Terminal rendering error. There are two spaces between each Chinese character. But the cursor stays at the same place.

>将vscode升级到了最新版本

When updating vscode to the latest version

>这个问题是在将vscode全屏下并且左侧打开了某个栏框出现的，如果将栏框关闭就可以解决，或者是退出全屏再进入全屏就可以解决了。

This issue only happens when the vscode is in full screen and there's a left sidebar opened. It can be solved after one closed the sidebar. Or it can be solved after exiting full screen and re-enter full screen again.

**Comment by bearx3f** [comment]
happen to me too

![image](https://user-images.githubusercontent.com/9717561/120929254-89ca3000-c712-11eb-8676-b22c00784662.png)

![image](https://user-images.githubusercontent.com/9717561/120929235-74ed9c80-c712-11eb-947e-9e3c39aec405.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
