### ISSUE TITLE
about paste

### ISSUE THREAD

**Issue by hytim** [microsoft/vscode#120787]
Issue Type: <b>Feature Request</b>

Hello! I cann't find a shortcut or setting that is similar to ctrl + shift +v in Sublime Text3. I wonder if there is  such a setting or a shortcut or I have to install a extention to implement it.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

**Comment by connor4312** [comment]
https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-paste-and-indent
