### ISSUE TITLE
vscode does not display any panel and does not repond to any operation except start and shutdown

### ISSUE THREAD

**Issue by feilengcui008** [Microsoft/vscode#12075]
- VSCode Version:  1.5.2
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. download vscode 1.5.2 for macos from official site  
2. unzip and move to /Application, start vscode
![2016-09-15 21 32 25](https://cloud.githubusercontent.com/assets/4131736/18551664/f80b35aa-7b8b-11e6-809f-e6fcc38f0965.png)

any operation is not working except creating new window
(I have tried cleaning the ~/.vscode and reinstall all software, it is still not working...is there any logs of vscode?)

**Comment by feilengcui008** [comment]
@bpasero I have tried both 1.5.2 and 1.5.1, and both failed, but version 1.4 works well for me

**Comment by feilengcui008** [comment]
@bpasero I know little about the vscode internal, is there any log output of vscode on macos? So maybe I can provide more details.

**Comment by feilengcui008** [comment]
@bpasero weird...I tried vscode version v1.4, it works, and then I tried insider version, it works, then I turn back to v1.5.2 and now it works!

**Comment by bpasero** [comment]
@feilengcui008 next time you can try to see the output in the developer console (Help > Toggle Developer Tools) to see if something gets logged.

Let's close this one until you see it again.
