### ISSUE TITLE
Errors from run npm script are not showed in 'Problems' pane

### ISSUE THREAD

**Issue by psulek** [Microsoft/vscode#12073]
- VSCode Version: 1.5.2
- OS Version: Windows 10, 64bit

Steps to Reproduce:

1. File `package.json` with scripts section like this `"start": "webpack --config webpack.config.production.js"`

2. File `tasks.json`, command set to `npm` and task set to "start" (to run npm start)

After executing such task, npm runs webpack which in turns builds typescript via loader (ts-loader). Output from webpack build is written to `OUTPUT` pane (which is ok). When typescript compile fails it is written to OUTPUT pane but it is not detected in 'Problems` pane (main menu View -> Problems).

Is this possible to support such error OUTPUT to be parse to Problems pane automatically by vscode?

**Comment by dbaeumer** [comment]
@psulek yes, for now you can even add your own problem matcher to the tasks.json file. See here on how to do this: https://code.visualstudio.com/docs/editor/tasks#_defining-a-problem-matcher

Dups #4363
