### ISSUE TITLE
Ubuntu 20.04: Unable to open X display

### ISSUE THREAD

**Issue by shimst3r** [microsoft/vscode#120714]
- VS Code Version: 1.55.0, c185983a683d14c396952dd432459097bc7f757f, x64
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Open VSCode
2. Open integrated terminal
3. `code -r /some/path`
4. VSCode doesn't reopen at `/some/path`

Verbose output:

```shell
$ code --r /some/path --verbose                                                                                                               09:56:05
[70390:0407/095620.279822:ERROR:browser_main_loop.cc(1434)] Unable to open X display.
The futex facility returned an unexpected error code.
/dev/fd/3: No such file or directory
```

Running the same command from e.g. `gnome-shell` opens VSCode as expected. I installed VSCode via `snap`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by viktomas-gitlab** [comment]
We get the same error in the CI for [gitlab-vscode-extension](https://gitlab.com/gitlab-org/gitlab-vscode-extension) when we use `vscode-test` to run tests.

https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/jobs/1159684595#L1150

It started happening with the release of `1.55.0`.

The CI uses `node:12-slim` docker image which is based of [debian docker image](https://github.com/nodejs/docker-node/blob/a7fad0c1bee6a47790e38c0e398972edc6fd63c0/12/stretch-slim/Dockerfile).

**Comment by meganrogge** [comment]
Let us know if you have a way to reproduce this.

**Comment by shimst3r** [comment]
Hey @meganrogge, the issue is still existent for me with the above steps. Do you need more information from my side?
