### ISSUE TITLE
Auto detect Windows PowerShell profile

### ISSUE THREAD

**Issue by Govind-Keshri** [microsoft/vscode#120756]
if power shell 7.1.3 installed default power shell v1.0 cannot detect to check
(1) install vscode (2) open terminal select default profile shows two option cmd+powershell (3) install power shell 7.1.3 check again it shows only two options power shell v1.0 not showing

**Comment by TylerLeonhardt** [comment]
Just to summarize this issue is asking for there to be a PowerShell profile that detects PowerShell 7 _and_ a Windows PowerShell profile that detects Windows PowerShell.

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/114175006-54f65400-98ee-11eb-9404-b4a9ac2b080a.png)
