### ISSUE TITLE
add serch code option

### ISSUE THREAD

**Issue by luismalvin4** [microsoft/vscode#120726]
add serch codes option from that devloper can serch that code easyly

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/113876548-bebc1400-97af-11eb-8c7a-35657709bef3.png)

**Comment by UnrealApex** [comment]
See [https://code.visualstudio.com/docs/getstarted/userinterface#_activity-bar](https://code.visualstudio.com/docs/getstarted/userinterface#_activity-bar) for more information. If you do not see the search tool on the Activity Bar, right click on it and see if you get an option to enable it or press `ctrl + shift + f`. By default it should look like this:

![](https://code.visualstudio.com/assets/docs/getstarted/userinterface/activity-bar-context-menu.png)
