### ISSUE TITLE
Notebook cell textmodel/textmodel lifecycle issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#120771]
Continuing from https://github.com/microsoft/vscode/issues/117936 and https://github.com/microsoft/vscode/issues/120284

Remaining issues

1. WorkspaceEdit on the content of a cell in a notebook that isn't open doesn't work:

```ts
const docUri = vscode.Uri.file('/datadrive/vscode/.vscode/notebooks/api.github-issues');
const cellUri = docUri.with({ scheme: 'vscode-notebook-cell', fragment: 'ch0000001' });
const edit = new vscode.WorkspaceEdit();
edit.insert(cellUri, new vscode.Position(0, 5), 'hello new text');
await vscode.workspace.applyEdit(edit);
```

The notebook editor is opened as expected, but the content change is not applied. I think what's happening is that the textmodel gets the change applied, but then is disposed before the notebook editor opens because nothing is holding a reference to it. How do we keep that from happening?

2. If I run setTextDocumentLanguage on a notebook that isn't open, then close the dirty editor and say "Don't Save", it doesn't reset the text model language, I don't know how that's supposed to work

**Comment by jrieken** [comment]
>  I think what's happening is that the textmodel gets the change applied, but then is disposed before the notebook editor opens because nothing is holding a reference to it.

That shouldn't be happening. The [`CellContentProvider`](https://github.com/microsoft/vscode/blob/6b67774b756d4a2103fa6af672a59f8a9bfb0300/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L507-L507) is responsible to materialise the textmodel for a cell and it does that by creating a notebook model ([here](https://github.com/microsoft/vscode/blob/6b67774b756d4a2103fa6af672a59f8a9bfb0300/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts)). When the textmodel is disposed it un-references the notebook model but as soon as the notebook model is turning dirty it should automagically referenced via [logic in the notebook resolver service](https://github.com/microsoft/vscode/blob/38fed2435582eb71250facc2b6a8ea92931b5d61/src/vs/workbench/contrib/notebook/common/notebookEditorModelResolverServiceImpl.ts)

**Comment by jrieken** [comment]
> The notebook editor is opened as expected, but the content change is not applied.

I was curious and tried this - for the snippet works, e.g the notebook opens is dirty and the change is applied

**Comment by jrieken** [comment]
> then close the dirty editor and say "Don't Save", it doesn't reset the text model language, I don't know how that's supposed to work

That should be handled in the workbench editor model land, e.g some kind of revert happens and then the document closes without further changes. For me that also seemed to work

**Comment by roblourens** [comment]
Thanks for trying it. Today it works for me too, definitely didn't a couple days ago 🤷‍♂️

**Comment by roblourens** [comment]
Spoke too soon. This still doesn't work.

- Run this

```ts
const docUri = vscode.Uri.file('/datadrive/vscode/.vscode/notebooks/api.github-issues');
const cellUri = docUri.with({ scheme: 'vscode-notebook-cell', fragment: 'ch0000001' });
let cellDoc = await vscode.workspace.openTextDocument(cellUri);
cellDoc = await vscode.languages.setTextDocumentLanguage(cellDoc, 'css');
```

- Close the tab, "Don't Save"
- Run the command again
- The editor doesn't open because the textmodel language was not actually reverted

The editor model does the revert correctly, and creates a new cell textmodel, but the textmodel's language is never reverted, and the new cell textmodel is never assigned a textmodel. It's confusing where the source of truth should be at this moment.

**Comment by jrieken** [comment]
> The editor model does the revert correctly, and creates a new cell textmodel, but the textmodel's language is never reverted, and the new cell textmodel is never assigned a textmodel

I can repro. I'd say the problem is that `NotebookCellTextModel` instances are created without checking if already a corresponding (monaco) text model exists. The [revert](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L146-L146)-flow eventually ends up doing a big replace-all [edit]([revert](https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L146-L146)) which creates new cell model but they don't operate on the existing monaco model. So, when creating a [cell model](https://github.com/microsoft/vscode/blob/d8e1c802f74d0b717b59119f11ac3cc63bcfde19/src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts) we should maybe check if a text model exists and use that as source of truth

**Comment by jrieken** [comment]
> So, when creating a cell model we should check if a text model exists and use that as source of truth

Oh, wait... That will never happen because cell uris use an increasing handle id which is never reused

**Comment by jrieken** [comment]
I have pushed a change which should fix this. Basically there is now a `reset` method that allows to correctly revert a notebook and with that existing text models for cells are picked up. My testing was happy but @roblourens please review

**Comment by jrieken** [comment]
On a related note: Maybe I am not seeing it but for me [_mapping](https://github.com/microsoft/vscode/blob/b7d7aaca741402c722c5d5aceb3521b11adb4832/src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts#L462-L462) is leak. We seem to store cell instances in that map but never remove anything from it... Also not seeing how/where we dispose cells at all

**Comment by roblourens** [comment]
> Maybe I am not seeing it but for me _mapping is leak. 

cc @rebornix
