### ISSUE TITLE
File not removed from file explorer if deleted permanently

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#12071]
- VSCode Version: 1.52
- OS Version: Win 10 64bit

Steps to Reproduce:

1. delete file, that is on a remote drive, confirm moving to bin
2. vscode issues a message it cannot be moved to recycle bin
3. have vscode delete it altogether
4. file is deleted, but not removed from the tree in directory panel (file explorer panel)

**Comment by bpasero** [comment]
@PunchyRascal does it go away after you refresh the file explorer?

**Comment by PunchyRascal** [comment]
Yes

**Comment by bpasero** [comment]
@PunchyRascal hard to reproduce for me, here is how it looks like for me:

![editors](https://cloud.githubusercontent.com/assets/900690/18575112/363252d0-7bd4-11e6-8908-61fb24189401.gif)

Something different for you?

**Comment by PunchyRascal** [comment]
Hm... it's weird, I can't reproduce it now either. So I guess I'll just close this for now.

**Comment by bpasero** [comment]
Sounds good.
