### ISSUE TITLE
Getting started: should track my settings and keybindings better?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120742]
Here for example:

![image](https://user-images.githubusercontent.com/900690/113894435-46158180-97c8-11eb-9a49-44edb08d9cfb.png)

I do have a theme configured in settings and I have custom keybindings. Shouldn't that lead to some of the entries getting a checkmark?

**Comment by digitarald** [comment]
Makes sense! We might want multiple "doneOn" checks that are not system events but when clauses that check for extensions & settings.

**Comment by JacksonKearl** [comment]
Tracking in #122570
