### ISSUE TITLE
[insiders]Cursor wont head to right any more in editor 

### ISSUE THREAD

**Issue by Emeryao** [Microsoft/vscode#12072]
- VSCode Version:
1.6.0-insider 
Commit fad6a894c197ee791403ac694c9316b0654f31a4
Date 2016-09-14T11:13:18.419Z
- OS Version: Win10 x64 14926

Steps to Reproduce:

1. open editor and move the cursor to the head of one line (over the line number)
2. the cursor won't change to a head to right style in recent insider releases (i think this issue is from this week)

this is what it is now in vs code insiders build:
![img_20160915_184415919](https://cloud.githubusercontent.com/assets/3591899/18547220/deb1eaac-7b74-11e6-8cd9-dccf473210ef.jpg)

and this is how it behaves in stable build:
![img_20160915_184436545](https://cloud.githubusercontent.com/assets/3591899/18547236/ece13f74-7b74-11e6-970b-873dff2d5dcf.jpg)

missing of this feature really bothered me :sob:

**Comment by bpasero** [comment]
Duplicate: https://github.com/Microsoft/vscode/issues/8708

/cc @bgashler1

**Comment by Emeryao** [comment]
I got a TEMPORARY solution  for this issue:
change the css class of `.monaco-editor .margin-view-overlays .line-numbers` in file `workbench.main.css`
with the style below:
```css
cursor: -webkit-image-set(url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' height='45' widht='30' viewBox='0 0 15 21'%3E%3Cpath fill='%23fff' stroke='%23000' d='M14.5 1.2L1.9 13.8h5.2l-2.6 5.3 3.2 1 2.6-5.2 4.2 3.1z'/%3E%3C/svg%3E") 2x) 30 0,default;
```
the key of this TEMPORARY solution is the `height` and `width` attribute of the svg tag.

**Comment by bpasero** [comment]
@Emeryao great insights, can you add this to the still open issue where we track it now? https://github.com/Microsoft/vscode/issues/8708
