### ISSUE TITLE
Improve extensions representation under extensions pack / extension dependencies tab 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#120702]
Improve extensions representation under extensions pack / extension dependencies tab. 
Use the grid view to represent the extensions.

**Comment by savannahostrowski** [comment]
Just spotted this thread on Reddit. Users are getting confused about what the badge means.

https://www.reddit.com/r/vscode/comments/ncwruq/what_does_the_number_badge_on_the_extension_mean/

cc: @qubitron @luabud

**Comment by egamma** [comment]
Extension Packs are rendered like this
![image](https://user-images.githubusercontent.com/172399/125270130-a822dd00-e309-11eb-8d07-57559752c00a.png)

The Python extension pack is rendered like this and does not support actions to install an extension individually
![image](https://user-images.githubusercontent.com/172399/125270281-cc7eb980-e309-11eb-95c7-f6ac5e290d77.png)

**Comment by sandy081** [comment]
extensions shown in the extension pack tab are now shown similar to how they are shown in details tab (if categorized as extension pack)

![image](https://user-images.githubusercontent.com/10746682/126173616-2d146be9-783b-4677-8346-2be5016ef1c0.png)

Also the badge is not shown if the extension is not categorized as extension pack

**Comment by sandy081** [comment]
To verify:

- Search for Python extension
- Make sure number badge is not shown on the extension icon
- Open the extension and go to Extension Pack tab
- Make sure you can install/uninstall the extensions listed there independently.

**Comment by stuartleeks** [comment]
Just tested this. Installing the Jupyter extension succeeds without installing the Python or Pylance extensions. Installing the Pylance extension results in all the extensions being installed (presumably because Pylance has a dependency on the Python extension). Confirmed with @sandy081 that this is the expected behaviour
