### ISSUE TITLE
Always show a notification toast even if height exceeds available height (crop message)

### ISSUE THREAD

**Issue by viktomas-gitlab** [microsoft/vscode#120713]
- VS Code Version: 1.56.0-insider
- OS Version: Darwin x64 19.6.0

I found this issue when the extension I maintain tried to show a large error message. When the message contains multiple long lines, VS Code silently fails to show the error message.

### Steps to Reproduce:

1. execute ```vscode.window.showErrorMessage(`${'x'.repeat(100)}\n`.repeat(100), 'Action');``` in extension code (this code creates 100 lines, each containing 100 `x` characters)
2. VS Code doesn't show any message

This issue happens for `showInformationMessage`, `showWarningMessage`, and `showErrorMessage`. The issue only occurs when you pass the `...items` argument to the function (`Action` in the example above)

Does this issue occur when all extensions are disabled?: No, it is an error in the Extension API implementation

### More system info

```
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:13:17.592Z (5 days ago)
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
```

**Comment by bpasero** [comment]
Up for grab if someone has time to investigate why this happens. I would have expected that we show a truncated version of the message at least.

**Comment by bpasero** [comment]
Actually nevermind, it shows for me:

![image](https://user-images.githubusercontent.com/900690/114269018-bad4ff80-9a04-11eb-9905-c4d558f9eb8d.png)

If the toast height is too large based on available space we may decide to not show it. That is the case here where the toast grows very large.

However allowing to show it with a way to expand it would probably make sense, and we have that, but not if the notification shows an action.
