### ISSUE TITLE
insiders new issue - only see menu bar, does not respond to menu actions

### ISSUE THREAD

**Issue by bkcsfi** [microsoft/vscode#120730]
- VS Code Version: 1.56.0-insider  30dcb112b46595657695d14c2cd6a37f783fbed2  x64
- OS Version: Ubuntu 16.04.7 LTS

Steps to Reproduce:

1. apt-get update to latest code-insiders
2. run code-insiders

Does this issue occur when all extensions are disabled?: Yes

I update to the latest code-insiders every day before I start working. Today, I will not be working (heh!)

after updating to this version and starting code-insiders, I see a menu bar, but there is nothing in the window itself

My last session had 5 windows open, they all open, but they are all 'empty'. I use awesome wm, every app is a fullscreen tile

![image](https://user-images.githubusercontent.com/6412502/113875101-6c193280-9784-11eb-9f9a-ae4a7ce74ddf.png)

I try menu choices such as open dev tools, report issue and quit. None of those do anything.

I tried running with options  `--verbose  --disable-extensions --disable-gpu`  but it still doesn't work.

[insiders-1.log](https://github.com/microsoft/vscode/files/6271965/insiders-1.log)

I just downgraded to the next oldest package and it works

so, non-working is ubuntu 1.56.0-1617786726 which is 1.56.0-insider  30dcb112b46595657695d14c2cd6a37f783fbed2  x64

working is ubuntu 1.56.0-1617705898 which is:

```
Version: 1.56.0-insider
Commit: 58186680eb97fe979e1d986bcfa983ab0a6228e4
Date: 2021-04-06T10:32:50.846Z
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.8.0-41-generic
```

**Comment by t-ricci-enhancers** [comment]
I have the same problem on last update of vscode insiders of today (mac, can't even check the version because the menù won't work)

**Comment by t-ricci-enhancers** [comment]
I redownloaded vscode-insiders for mac from the website and it started to work again

**Comment by gjsjohnmurray** [comment]
Probably https://github.com/microsoft/vscode/issues/114459#issuecomment-814846486

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/120655#issuecomment-814868944

**Comment by bkcsfi** [comment]
confirmed this is fixed in latest code-insiders w/ cache clearing fix
