### ISSUE TITLE
Internal themes are updated without increasing their version number

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#120736]
- VS Code Version: 1.54
- OS Version: current win 10

Steps to Reproduce:

1. Check the default themes history (which is only partial possible because of the move in to this repo)
2. Different changes, last one from @aeschli, version stays at 1.0.0

Question: Should we expect this to be always the case or can we expect theme changes to also get an increased version number?

**Comment by aeschli** [comment]
We don't maintain the version number for built-in extensions. They are not uploaded to the Marketplace so the version number is not used.

**Comment by GitMensch** [comment]
I'd have assumed that if the Javascript and Node Debug plugins have version 1.0.0, too, but those actually do increase.
While I'm aware that those plugins are not one the marketplace a version number is also helpful for letting users know about updates and what they actually use. ... and for bug reports ... and stuff.
Please reconsider using incrementing version numbers for the integrated plugins, too.
