### ISSUE TITLE
Tasks: Support that a problem matcher can define the 'source'

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#12074]
To support that a task can produce errors that have a `source` attribute. The Problem matcher should support a `source` attribute.

**Comment by dbaeumer** [comment]
@egamma this slipped through the cracks. I can look into this during fixing if necessary. Should be straight forward. If not urgent I will move to June.

**Comment by egamma** [comment]
Moving to June is fine.

**Comment by alexr00** [comment]
Looks like this already happened since problem matchers have a source attribute.
