### ISSUE TITLE
NPM Scrips are mising after last update

### ISSUE THREAD

**Issue by Vylda** [microsoft/vscode#120789]
- VS Code Version: 1.55.0
- OS Version: Windows x64 10.0.19042

Steps to Reproduce:

1. Open VSCode with package.json
2. No NPM scripts in explorer sidebar
![noNPM scripts](https://user-images.githubusercontent.com/47244408/113984414-5f134680-984b-11eb-86a8-0bc77ac207cd.png)

**Comment by saraful** [comment]
I have the same problem，After upgrading version 1.55, NPM scripts are gone

**Comment by ozplugin** [comment]
Same problem. after After upgrading to ver. 1.55
