### ISSUE TITLE
building docker container in one vscode instance, completely freezes the other vscode instance

### ISSUE THREAD

**Issue by scalavision** [microsoft/vscode#120819]
- VS Code Version: 1.54.2
- OS Version: NixOS 20.09

Steps to Reproduce:

1. Build Dev Docker container in one instance of vscode
2. Try to use the other vscode instance on some other project

Shouldn't the processes be independent? All other applications I use works without
any problems.

Does this issue occur when all extensions are disabled?: Yes/No
Not applicable since I need extensions to be able to do this

**Comment by chrmarti** [comment]
Do you mean 'freeze' in the sense that the UI does not move at all? Or are there only specific actions that don't work?

Is the frozen window connected to a Docker container?

**Comment by scalavision** [comment]
It is possible to get the other vscode instances to respond, but every mouse click etc. has a huge lag. it seems to be just usage in general, clicking any button is very unresponsive.

Don't know, but it feels that building the docker devcontainer inside vscode takes all the cpu from the other vscode instances running. All the other applications in my desktop is responsive.

Thanks for looking into this.

The devcontainer is defined in this project, if that is of any help:

https://gitlab.com/alleles/ella

**Comment by chrmarti** [comment]
Please check which processes use the most CPU and list them here including their command line arguments (to distinguish between the various VS Code processes). That should give us a hint towards what is going on.
