### ISSUE TITLE
Light bulb in problems view makes entry jump

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120840]
I had the `streetsidesoftware.code-spell-checker` extension installed (in a Codespace):

![recording](https://user-images.githubusercontent.com/900690/114046982-9a346a80-9889-11eb-9313-4189933b4220.gif)

**Comment by sandy081** [comment]
Can you please check if you can repro this with stable?

**Comment by bpasero** [comment]
@sandy081 does not seem to reproduce, so maybe a regression from the changes Joao did?

**Comment by sandy081** [comment]
Probably but let me check with @joaomoreno for confirmation.

**Comment by joaomoreno** [comment]
I fix. 👌

**Comment by bpasero** [comment]
A lot better but somehow still a maybe 1px shift for me?

![recording](https://user-images.githubusercontent.com/900690/116216527-03045980-a749-11eb-8e53-124cd23f1e8b.gif)

@joaomoreno can you reproduce?

**Comment by joaomoreno** [comment]
I can't no 😢

![recording (10)](https://user-images.githubusercontent.com/22350/116259652-d5a8b300-a72a-11eb-98ff-edfdcfaeabd5.gif)

**Comment by bpasero** [comment]
This was in Codespaces web btw.
