### ISSUE TITLE
Display icons in the IntelliSense suggestions like breadcrumb.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120880]
Icons in breadcrumb is way better than icons in IntelliSense suggestions. Can this adds also to IntelliSense? It 'll be great improvement to unify user experience.

**Breadcrumb Icons**
---
**Class and Constructor Icons in breadcrumb**

![image](https://user-images.githubusercontent.com/17777237/114109016-a98cd580-98d4-11eb-99e8-6d4decc97a80.png)

**IntelliSense Icons**
---
**Class icon in IntelliSense suggestions**

![image](https://user-images.githubusercontent.com/17777237/114109091-d50fc000-98d4-11eb-9c8c-d5b20d080f63.png)

**Constructor icon in IntelliSense suggestions**

![image](https://user-images.githubusercontent.com/17777237/114109063-c32e1d00-98d4-11eb-8467-26d03aad75d8.png)

**And there's a lot the same**

![image](https://user-images.githubusercontent.com/17777237/114112548-e361da00-98dc-11eb-835f-2f295899f150.png)

**Comment by jrieken** [comment]
There is a difference: IntelliSense suggest keywords like `constructor, public, private, set, get, static` and breadcrumbs shows members like methods or constructor.
