### ISSUE TITLE
Terminal buffer doesn't span full width

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#120810]
Issue Type: <b>Bug</b>

When VS Code opens, the usable buffer of the terminal will be severely truncated in width. Using the terminal beyond the limited width, will result in display corruption:

![image](https://user-images.githubusercontent.com/1658949/114006447-bbcd2c00-9860-11eb-8fe8-aa011590cb61.png)

Closing the terminal and opening it again, restores the buffer to full width. This is very cumbersome, as logging out from the terminal often produces an error message that has to be manually closed as well, before ultimately opening the terminal in its desired state.

![image](https://user-images.githubusercontent.com/1658949/114006654-eb7c3400-9860-11eb-88dd-1690ad39332b.png)

When _restoring_ the window down from maximized state, the terminal buffer fits perfectly into the new bounds of the window. This suggests that this restored window size (or VSCs handling of window state during startup) is also the reason for this glitch.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (35.81GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.95GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (35.95GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-graphql|Gra|0.3.15
terraform|has|2.9.1
vscode-esformatter|how|1.6.0
innosetup|idl|1.6.0
template-string-converter|meg|0.4.7
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.11.0
js-debug-nightly|ms-|2021.4.717
vscode-js-profile-flame|ms-|0.0.14
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.29
speckle|rbu|1.4.3
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by JohnRThomas** [comment]
Seeing this as well on:
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

Width is incorrect, and height becomes incorrect when I split the terminal. Started happening with the latest update.

**Comment by jandem** [comment]
I noticed the same issue, especially with pager commands like `less`. I have the VSCode window split in terminal on the left side, editor on the right side. A workaround is slightly resizing the terminal/editor with the divider in the middle.

**Comment by dattrax** [comment]
I believe this is the same issue I'm facing in the latest 1.55 release.  Terminal goes into an 80 column wrap mode.  To restore I have to close that terminal instance and start a new one.

Looks like a regression as I've not had this problem with prior versions

**Comment by S-aiueo32** [comment]
I've had the same one since the update to v1.55.

**Comment by biro456** [comment]
I noticed this today as well.

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mykter** [comment]
These all appear to be related: #120136, #120427, #116174

**Comment by xdhmoore** [comment]
I noticed a similar thing with the maximizing/unmaximizing and the terminal width. See [this comment](https://github.com/microsoft/vscode/issues/116174#issuecomment-824195735)

**Comment by hayzey** [comment]
If this helps with troubleshooting: when this issue occurs for me, I can quickly fix it by resizing the terminal window a little, which I guess forces some sort of terminal width recalculation.

**Comment by oliversalzburg** [comment]
I feel like this might be fixed in latest Insiders build. Terminal is coming up full-width pretty reliably today.

Version: 1.56.0-insider (user setup)
Commit: 85f8ebf1687661c45fe2633bdd7f640164a20cc2
Date: 2021-05-04T08:04:43.323Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by oliversalzburg** [comment]
I can't reproduce the behavior in Stable on the machine I'm currently working on, but I have already noticed the change in behavior on the workstation I've originally seen the issue on. So I'm inclined to call this /verified
