### ISSUE TITLE
Git changes are extremely slow

### ISSUE THREAD

**Issue by jasperswallen** [microsoft/vscode#120883]
Issue Type: <b>Performance Issue</b>

The past couple releases have significantly decreased the speed at which git updates.

Opening changes takes at least 10 seconds, and line highlights for diffs take about 5 seconds to show up. Staging/unstaging/committing all also take much longer than typical.

Disabling all extensions makes no difference in this performance. Command-line git behaves normally.

VS Code version: Code - Insiders 1.56.0-insider (5904b7b686e9274631893d560fdbc55a5567f878, 2021-04-08T17:51:28.503Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.48GB free)|
|Process Argv|--crash-reporter-id 89b86966-4aba-4e50-8b6d-be924117f05f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    95	  1712	code-insiders main
    0	   200	  2692	   window (<redacted> - Visual Studio Code - Insiders)
    0	    20	 18120	     watcherService 
    0	    15	 20708	       console-window-host (Windows internal process)
    0	   343	 18776	     extensionHost
    0	    33	 11684	       "C:\Users\jswallen\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" "c:\Users\jswallen\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=18776
    0	    59	 22816	       c:\Users\jswallen\.vscode-insiders\extensions\ms-vscode.cpptools-1.3.0-insiders4\bin\cpptools.exe
    0	    15	  3060	         console-window-host (Windows internal process)
    0	    84	 18184	         c:\Users\jswallen\.vscode-insiders\extensions\ms-vscode.cpptools-1.3.0-insiders4/bin/cpptools-srv.exe 22816 {46CF1D1D-AB23-40B4-96EF-18162A89D2BA}
    0	    34	 21500	     searchService
    0	    60	  3536	   utility
    0	   190	 12868	   gpu-process
    1	    96	 17820	   shared-process
    0	    32	 19736	     ptyHost
    0	    17	 22196	   crashpad-handler
    1	    56	 23376	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (<redacted> - Visual Studio Code - Insiders)
|    Folder (<redacted>): 1922 files
|      File types: cpp(371) hpp(174) <custom>(166) o(158) obj(152) c(65)
|                  txt(54) make(54) cmake(53) h(30)
|      Conf files: cmake(53) makefile(3) settings.json(1);
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-bazel|Baz|0.4.0
doxdocgen|csc|1.1.0
vscode-markdownlint|Dav|0.40.1
gitlens|eam|11.3.0
vscode-pull-request-github|Git|0.25.0
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.15.5
python|ms-|2021.3.680753044
jupyter|ms-|2021.6.728949111
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
cpptools|ms-|1.3.0-insiders4
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4116
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
vscode-yaml|red|0.17.0
<custom>|sel|0.0.1
trailing-spaces|sha|0.3.1
cmake|twx|0.0.17
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.11
vscode-proto3|zxh|0.5.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vsdfh931cf:30280410
vscnewfilebutton:30280634
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by ziofil** [comment]
I'm observing this also on 1.55.1 (Universal)

**Comment by Nekuin** [comment]
I had the same problem, but after a reboot it went back to normal... can't really say what the cause was. I'm on windows 10, latest version of VS code and had an uptime of about 7 days.

**Comment by ziofil** [comment]
I'm on macOS, a reboot did't help ☹️

**Comment by eamodio** [comment]
Can you please post the contents of the _Git_ output channel in the _Outputs_ view? Thanks!

**Comment by ziofil** [comment]
There doesn't seem to be anything weird there, but each line takes seconds to appear in the console output
```
...
> git status -z -u
> git symbolic-ref --short HEAD
> git ls-files --stage -- /Users/[redacted]
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/main refs/remotes/main
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git cat-file -s [redacted]
> git config --get commit.template
> git show --textconv : [redacted]
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
> git status -z -u
git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/main refs/remotes/main
> git ls-files --stage -- /Users/[redacted]
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git cat-file -s [redacted]
> git config --get commit.template
> git show --textconv : [redacted]
> git config --get commit.template
> git fetch
...
```

**Comment by jaymegordo** [comment]
I was experiencing the same issue in code-insiders for a few weeks with:
```
Version: 1.56.0-insider
Commit: 0123d26aaa393bccf99f31f1eac07df6c9e218ce
Date: 2021-04-29T06:21:54.461Z
Electron: 12.0.5
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0
```

But after an update to the following, git commands are working fast again:
```
Version: 1.56.0-insider
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:55:28.605Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
```
