### ISSUE TITLE
Empty sidebar - no files listed

### ISSUE THREAD

**Issue by simplenotezy** [microsoft/vscode#120854]
- VS Code Version: 1.55.1
- OS Version: 11.2.3

I have a bug where the sidebar is empty. It happened after switching macbook and restoring from backup. I tried updating vscode to latest version.

The issue is perfectly described here: https://github.com/Microsoft/vscode/issues/37693

When I do as [suggested](https://github.com/Microsoft/vscode/issues/37693#issuecomment-342124397) I don't have any files under `file://`:

![image](https://user-images.githubusercontent.com/3786627/114081267-a251d180-98ac-11eb-967a-78d83a6ce5fd.png)

Steps to Reproduce:

1. Open a project (e.g. `code ~/my-project`
2. Sidebar is empty:
![image](https://user-images.githubusercontent.com/3786627/114081340-b5fd3800-98ac-11eb-9cfe-42f51870fab7.png)

It does not happen to all my projects though.

Does this issue occur when all extensions are disabled?: Yes

**Comment by simplenotezy** [comment]
Issue got resolved by moving the file out of my ~/Downloads folder into my ~/Projects folder

**Comment by misolori** [comment]
@simplenotezy thanks for reporting back!
