### ISSUE TITLE
quickOpenPreviousRecentlyUsedEditorInGroup search/filter

### ISSUE THREAD

**Issue by ceuk** [microsoft/vscode#120849]
When switching between files using the above action it would be great if there was an option to enable the search bar in order to be able to filter the results.

**Comment by bpasero** [comment]
That is typically not the intent of these commands that show quick pick without input field because they idea is to select the entry when releasing the key so that searching is not needed.

**Comment by ceuk** [comment]
> That is typically not the intent of these commands that show quick pick without input field because they idea is to select the entry when releasing the key so that searching is not needed.

That makes sense. I just find it becomes cumbersome to page through all open files when I have 5+ or so. Is there another way to quickly search/active already open files?

For context: I find the other quick opens (e.g. ctrl+p) quite unreliable as in a large project there's often numerous files with predominantly generic names such as config, controller etc etc. Whilst Ctrl+p does it's best to weight recently opened files, in practice I often end up opening the wrong file which means I have I slow down and check the full path of the file before I open it. Which is fairly disruptive when all you want to do is quickly switch between 2-5 files.

This is why keeping files open works well for me. "One-off" edits can be closed whilst the rest form a context for my quick open activities. I could just type something like "styles" in this situation and be confident that the file it matched was the one I wanted to open.

Is this a problem with the way I'm trying to use VSCode or would there be interest in supporting this (and similar) workflows? Unless you consider having 5+ tabs open some kind of usage anti-pattern it would be nice to provide some way to quickly select a tab that wasn't so manual.

Hope that makes sense

**Comment by bpasero** [comment]
You can use the `workbench.action.showAllEditorsByMostRecentlyUsed` which shows the search box.

**Comment by ceuk** [comment]
Aha! fantastic, thanks!
