### ISSUE TITLE
HTML Mixed Mode Support

### ISSUE THREAD

**Issue by JoshClose** [Microsoft/vscode#1208]
I'm looking at having DustJS files syntax highlighted. It's just like PHP/ASP/etc, where it's an HTML file, with another language mixed in.

Is this supported? I'm not getting any highlighting for HTML in my file. There are no errors in the console either.

I created an extension using `yo code` and selecting `New Language Support`. I then used this URL as the tmLanguage file. https://raw.githubusercontent.com/jimmyhchan/Dustjs.tmbundle/master/Syntaxes/DustJS.tmLanguage This language has an include for `text.html.basic`. 

When doing a search in this repo for `text.html.basic` I get several other syntaxes that reference it. If I try using those languages with an html or dust file, it doesn't highlight the html. If I change the language to html, everything highlights as expected.

This is my package.json file. The tmLanguage file is the one referenced above.

```json
{
	"name": "dustjs",
	"displayName": "dustjs",
	"description": "dustjs language support",
	"version": "0.0.1",
	"publisher": "anonymous",
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"languages": [{
			"id": "dustjs",
			"aliases": ["DustJS", "dustjs"],
			"extensions": [".dust",".tl",".dustjs"],
			"configuration": "./dustjs.configuration.json"
		}],
		"grammars": [{
			"language": "dustjs",
			"scopeName": "text.html.dustjs",
			"path": "./syntaxes/dustjs.tmLanguage"
		}]
	}
}
```

**Comment by JoshClose** [comment]
I also saw this. https://github.com/Microsoft/vscode/issues/543

**Comment by aeschli** [comment]
#543 fixes this.
