### ISSUE TITLE
Repeated horizonal rules after some periodical rows

### ISSUE THREAD

**Issue by piranna** [microsoft/vscode#120836]
Similar to https://github.com/microsoft/vscode/issues/113458, but instead of as separator between classes and methods, do it after some fixed number of rows, similar to the vertical rules. This is intented to mark number of rows per printed page of code, or page scroll. Having the hability to have multiple horizontal rows also can be useful for example when writting RFCs, where they have a fixed format of 50 rows per page of plain text counting header and footer.

**Comment by AndreasLuckert** [comment]
There is an extension available in the market place:

https://marketplace.visualstudio.com/items?itemName=stackbreak.comment-divider

**Comment by piranna** [comment]
> There is an extension available in the market place:
> 
> [marketplace.visualstudio.com/items?itemName=stackbreak.comment-divider](https://marketplace.visualstudio.com/items?itemName=stackbreak.comment-divider)

This is not the same thing, that extension add dividers in the source code itself, I'm asking for "row wrap" lines in the editor to mark end of pages.
