### ISSUE TITLE
unusual memory usage increase

### ISSUE THREAD

**Issue by takayama-lily** [microsoft/vscode#120806]
- VS Code Version: 1.55
- OS Version: win10

Memory usage will increase observably when open an extension's README with a large .gif image on the page.

Steps to Reproduce:

1. find an extension with a large .gif image on its README page (for example, search by the keywords "gif")

**Comment by mjbvz** [comment]
Please follow [these instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues) to collect performance information

**Comment by takayama-lily** [comment]
`Does this issue occur when all extensions are disabled?: Yes`
@mjbvz I found the `gpu-process` memory usage raised while the extension page opening.
Maybe the reason is that there is a big-size gif image on the page.
![screenshot](https://user-images.githubusercontent.com/12014361/114111856-fd6bde80-9915-11eb-9945-4eeac6fab1f1.png)

**Comment by mjbvz** [comment]
Tested in insiders. There's a memory increase in the gpu process, but it more or less matches what I see when viewing the same page in a browser: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl
