### ISSUE TITLE
Sash highlight showing by itself

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#120828]
Not entirely show when/how this happens but I have seen ghost sash feedback. See recording, the seems that the sash for the (invisible) details pane shows despite the mouse being far away

https://user-images.githubusercontent.com/1794099/114030170-8cc3b400-987a-11eb-845f-4253da5ab8fd.mov

**Comment by jrieken** [comment]
//cc @misolori

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/120865

**Comment by joaomoreno** [comment]
Ugly bug. Ugly fix. @jrieken can you code review and verify?

**Comment by jrieken** [comment]
Thanks @joaomoreno. Changes look good, I will keep an eye on this
