### ISSUE TITLE
Color Theme: add `button.border`

### ISSUE THREAD

**Issue by avoonix** [microsoft/vscode#120868]
It's not possible to add a border to buttons. 

Without this, it can be difficult telling text and buttons apart.

![image](https://user-images.githubusercontent.com/63160225/114092621-61f95000-98ba-11eb-810a-654afd8f59f5.png)

There is one, if the button is focused, but the color can't be changed independently of the foreground color and it won't be shown at all times.

![image](https://user-images.githubusercontent.com/63160225/114092649-6d4c7b80-98ba-11eb-9188-eb4f088b87b5.png)

**Comment by aeschli** [comment]
The border is set to the color `contrastBorder`.

**Comment by aeschli** [comment]
Verify the new color `button.border`
