### ISSUE TITLE
Remove fs.statSync call

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12088]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/window.ts#L159

I don't see a reason to have this there, can we make this async?

**Comment by joaomoreno** [comment]
Nevermind... I see why now... dnd is hard.

**Comment by joaomoreno** [comment]
Actually... couldn't we make the (async) call after you drop? And show a hover feedback any way?

**Comment by bpasero** [comment]
Now using async, I think it is fast enough that you do not notice any delay in the hover.
