### ISSUE TITLE
contributed command's error do not get surfaced in the toast message

### ISSUE THREAD

**Issue by sriv** [microsoft/vscode#120898]
- VS Code Version: 1.53.2
- OS Version: Linux, popOS 20.04 LTS

Steps to Reproduce:

1. In a vscode extension, register a command with `commands.registerCommand('myTest:run', () => Promise.reject(new Error('This is a test error')))`
2. Run `myTest:run` in vscode host version 1.52.1 => There's an error toast with message `This is a test error`
3. Run `myTest:run` in vscode host version >= 1.53 => There's an error toast with message `Running the contributed command: 'myTest:run' fail...`

Does this issue occur when all extensions are disabled?: No

**Comment by jrieken** [comment]
Please try this with the latest version of VS Code which is 1.55.x

**Comment by sriv** [comment]
Tried with this version (1.55.1):

```
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:01:24.315Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.0-7612-generic
```

I still get this error message in the notif: `Running the contributed command: 'myTestrun' failed.`

**Comment by sriv** [comment]
I've pushed a sample extension with tests passing against `1.52.1` and failing against `1.55.1` - perhaps it could help identifying the cause. Please let me know if you need anything more. Thanks.

**Comment by jrieken** [comment]
This was caused https://github.com/microsoft/vscode/commit/3ba967fd7eb97621b0e2a4fb0267b70323ffcf5f
