### ISSUE TITLE
1.55 Wrong Gui initialized on Ubuntu 20.04 . Same as before, see #116682

### ISSUE THREAD

**Issue by giorgioborri** [microsoft/vscode#120851]
With this new version 1.55 on ubuntu 20.04 gnome, I don't see the correct gui.
I need to start with --disable-gpu as suggested as workaround in #116682 by deepak1556

**Comment by deepak1556** [comment]
We haven't updated the runtime in `1.55`, please continue to follow https://github.com/microsoft/vscode/issues/115868 for updates. Thanks!
