### ISSUE TITLE
Slow 

### ISSUE THREAD

**Issue by mohithsairamreddy** [microsoft/vscode#120857]
Issue Type: <b>Bug</b>

Very slow output

VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (10.32GB free)|
|Process Argv|--crash-reporter-id 82972ce4-4eef-411b-8efa-33822866007a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
competitive-programming-helper|Div|5.0.1
code-runner|for|0.11.2
python|ms-|2021.2.633441544
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.1.3
LiveServer|rit|5.6.1

</details>

**Comment by gjsjohnmurray** [comment]
/needMoreInfo - see https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by gjsjohnmurray** [comment]
Also, is there some reason why you are four releases out of date?

**Comment by mohithsairamreddy** [comment]
Issue resolved thank you
