### ISSUE TITLE
Support trusted workspace settings

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#120860]
Support trusted workspace settings

**Comment by RandomFractals** [comment]
@sandy081 what is a trusted workspace setting?

does that apply to extension workspace settings too?

Could you please provide more information for additions like this that are added to the next monthly release?

Thanks!

**Comment by RandomFractals** [comment]
is this for #106488 ?

**Comment by sandy081** [comment]
Yes this is related to trusted workspaces. Will update more information soon.
