### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mahmoudabdulmuty** [microsoft/vscode#120852]
- Issue Type: `Bug`
- Extension Name: `js-debug`
- Extension Version: `1.55.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please describe issue and steps to reproduce
