### ISSUE TITLE
Unable to find the HTML Matching Element Highlight Color in the Theme Reference

### ISSUE THREAD

**Issue by ahmadawais** [microsoft/vscode#120817]
Issue Type: <b>Bug</b>

I'm trying to figure out where is the reddish color of matching highlighted elements coming from and so far reading through the theme reference multiple times hasn't been fruitful. 

![image](https://user-images.githubusercontent.com/960133/114015609-4d4d9580-9883-11eb-937f-45e35f8c6cb2.png)

This was also reported on my theme repo: https://github.com/ahmadawais/shades-of-purple-vscode/issues/107

Can anyone help point in the right direction — or check if this is missing the theme reference?

I'd love to help add this to the ref if it's missing.

Thank you! 

---

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.64GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (96)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
pug|ama|1.0.1
conflict-squeezer|ang|1.0.1
spellright|ban|3.0.56
markdown-preview-github-styles|bie|0.1.6
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.10
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
vscode-html2pug|dba|4.0.0
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
es7-react-js-snippets|dsz|3.1.1
css-flexbox-cheatsheet|dzh|3.2.2
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.19
LogFileHighlighter|emi|2.11.0
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|6.3.2
vscode-debug-launcher|fab|2.1.0
vscode-git-history|fab|2.0.5
vscode-open-in-github|fab|1.3.0
vscode-optimize-images|fab|1.1.0
vscode-terminals|fab|1.12.9
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
shell-format|fox|7.0.1
macros|ged|1.2.1
gc-excelviewer|Gra|3.0.41
vscode-graphql|Gra|0.3.15
timing|Haa|2.5.1
rest-client|hum|0.24.5
output-colorizer|IBM|0.1.2
composer|ika|0.7.1
phpcs|ika|1.0.5
search-node-modules|jas|1.3.0
vscode-lebab|jer|1.0.5
svg|joc|1.4.5
vscode-cloak|joh|0.3.0
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.5.0
node-module-intellisense|lei|1.5.0
expand-region|let|0.1.4
php-symbols|lin|2.1.0
rainbow-csv|mec|1.8.1
vscode-wrap-console-log|mid|1.7.2
xml-format|mik|1.1.2
dotenv|mik|1.0.1
ecdc|mit|1.4.0
HTMLHint|mka|0.10.0
vscode-apache|mrm|1.2.0
vscode-duplicate|mrm|1.2.1
vscode-jade-snippets|mrm|1.0.1
vscode-scss|mrm|0.9.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
azure-account|ms-|0.9.8
sublime-keybindings|ms-|4.0.8
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
subtitles-editor|pep|1.1.3
ruby|reb|0.28.1
shellman|Rem|5.4.0
html-to-jsx|ria|0.0.1
LiveServer|rit|5.6.1
vscode-javascript-booster|sbu|14.0.1
mdx|sil|0.1.0
vscode-fileutils|sle|3.4.5
auto-correct|syg|0.2.2
tabnine-vscode|Tab|3.2.17
open-in-browser|tec|2.0.0
sort-lines|Tyr|1.9.0
remove-empty-lines|use|0.0.6
sensitive-replace|vil|0.1.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
snippet|vsc|0.8.1
vscode-todo-highlight|way|1.0.4
vscode-js-console-utils|wht|0.7.0
vscode-ruby|win|0.28.0
fig|wit|0.0.1
vscode-import-cost|wix|2.15.0
save-and-run|wk-|0.0.22
wordpress-toolbox|wor|1.3.9
JavaScriptSnippets|xab|1.8.0
searchwpdocs|yog|2.0.1
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0
grammarly|znc|0.14.0

(2 theme extensions excluded)

</details>

**Comment by aeschli** [comment]
The colors active there are "editor.wordHighlightBackground` but also `"editor.linkedEditingBackground"` if you have linked editing enabled.

![image](https://user-images.githubusercontent.com/6461412/114020339-c5aa5b80-986f-11eb-9c05-ee21aaf80ce6.png)

**Comment by aeschli** [comment]
Please reopen if that didn't solve your request.

**Comment by ahmadawais** [comment]
Hi @aeschli thanks for the quick response. 

Adding this context for anyone else looking into this.

For `editor.wordHighlightBackground` I have the following dull purple color: `#FFFFFF0D`

```json
		"editor.wordHighlightBackground": "#FFFFFF0D", // Same words other places.
```

And it works as expected: Look for the word `search` in the image below:

![image](https://user-images.githubusercontent.com/960133/114022789-90136b80-988b-11eb-9938-db2ffb732fa4.png)

But adding `"editor.linkedEditingBackground"` helped change the color of matching highlights.

![image](https://user-images.githubusercontent.com/960133/114023984-f220a080-988c-11eb-90ad-637a081346ec.png)
