### ISSUE TITLE
Quick pick: Checkboxes not stylable

### ISSUE THREAD

**Issue by avoonix** [microsoft/vscode#120866]
- VS Code Version: 1.55.0
- OS Version: Linux x64 5.11.6-1-MANJARO

Steps to Reproduce:

Create a new theme:
```
{
  "$schema": "vscode://schemas/color-theme",
  "name": "theme",
  "type": "dark",
  "colors": {
    "checkbox.background": "#ff0000",
    "checkbox.border": "#ff0000",
    "checkbox.foreground": "#ff0000"
  }
}
```
Those should be red (only settings checkboxes are currently affected):

Multiple selection:
![image](https://user-images.githubusercontent.com/63160225/114091187-a84daf80-98b8-11eb-981f-9681b65acfc4.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
Fyi I do not think you can change the color of native checkboxes. Best I found is `accent-color` for the background when the checkbox is checked, but not sure that is clever to do.

**Comment by TylerLeonhardt** [comment]
Really we should just use our Checkbox widget so we get styling "for free" but I gave it a look and Checkbox isn't robust enough to handle the quick pick so I need to make changes there too.

**Comment by TylerLeonhardt** [comment]
Closing this in favor of a newer one with a bit more info
