### ISSUE TITLE
Text colors in editor window sometimes randomly change

### ISSUE THREAD

**Issue by sunnyape** [microsoft/vscode#120800]
Issue Type: <b>Bug</b>

When editing code in an editor window, on very rare occasions, if VSC is in full screen mode, the text coloring that is based on the code content type will randomly change as you scroll down the page, as per this screen grab:

![VSC text colors changing 20210408](https://user-images.githubusercontent.com/32824881/113996712-c4daef00-989a-11eb-93c3-2d5d54b9c752.png)
Closing and re-opening VSC fixes the issue.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (3.38GB free)|
|Process Argv|--crash-reporter-id 48295c43-09c7-4fe1-a1b1-8cd40ec319e8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2021.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by dbaeumer** [comment]
Looks like a problem with the Powershell extension. Please open an issue here: https://github.com/PowerShell/vscode-powershell
