### ISSUE TITLE
Terminal inserts strange characters when pressing Ctrl R

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#120825]
This started pretty recently: when I use <kbd>Ctrl R</kbd> to access my shell history in fzf, the VS Code terminal _sometimes_ inserts `1R1R` right after the sequence, which messes up its usage.

This doesn't repro on a fresh new terminal, but as soon as I run something like `docker ps`, it starts reproducing always.

I can't repro this in stable 1.54, but I can definitely repro on the new stable 1.55, so this can definitely be a candidate, given it's a regression.

![recording (12)](https://user-images.githubusercontent.com/22350/114025672-3af33d80-982a-11eb-8446-0b9372c60a2a.gif)

**My setup:**

- Use ZSH with oh-my-ZSH
- `sudo apt install fzf`
- Add `fzf` to the `plugins=(...)` list in `.zshrc

**Comment by gencer** [comment]
I'm using bash. I've entered rails console by `bundle exec rails c` and this is whats happening:

![1](https://user-images.githubusercontent.com/1711576/114309874-69ef0500-9af1-11eb-8958-a09d7a07375b.gif)

**Comment by meganrogge** [comment]
Related to webgl as the default? @Tyriar

**Comment by joaomoreno** [comment]
From our chat:

> Daniel Imms  14:28
> does it happen when you set terminal.integrated.localEchoLatencyThreshold to -1?
> 
> João Moreno  14:29
> no, it doesn't!!!

**Comment by Tyriar** [comment]
@joaomoreno can you see if this still happens? It's probably fixed with https://github.com/microsoft/vscode/issues/120352

**Comment by joaomoreno** [comment]
I've reset the setting value and haven't hit the issue in 5 minutes, will report back if I see it.
