### ISSUE TITLE
JavaScript - Weird behavior in IntelliSense suggestions with no suggestions.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120881]
- VS Code Version: 1.55.1
- OS Version: Windows 10 20h2

Steps to Reproduce:

✔**With class keyword before completed**

![image](https://user-images.githubusercontent.com/17777237/114109714-1eacda80-98d6-11eb-9529-9cea0354bfba.png)

✔**After completed and press `ctrl + space`**

![image](https://user-images.githubusercontent.com/17777237/114109689-105ebe80-98d6-11eb-9a2e-b0785eeab689.png)

---

✔**With constructor keyword before completed**

![image](https://user-images.githubusercontent.com/17777237/114109737-2bc9c980-98d6-11eb-940f-f0fa528cf23e.png)

❌**After completed and press `ctrl + space`**

![image](https://user-images.githubusercontent.com/17777237/114110208-45b7dc00-98d7-11eb-80b9-2d67c40e852d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The first looks like normal fuzzy suggestion matching. Once you type the second `s`, there are no longer any matching suggestions

Extracted the second to https://github.com/microsoft/TypeScript/issues/43650
