### ISSUE TITLE
Trust icon with number badges uses default font

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#120897]
(See attached screen capture)

* I have enabled trust (via the setting)
* this morning I have a pending update and it seems that the number uses the default font (I guess because those aren't defined in the codicon font)

<img width="548" alt="Screenshot 2021-04-09 at 08 43 05" src="https://user-images.githubusercontent.com/1794099/114139704-a8c56500-990f-11eb-9a90-b1d8abaef445.png">

**Comment by sbatten** [comment]
ugh this is reproing again, the badge should not be showing both at the same time and its not consistent, investigating

**Comment by lszomoru** [comment]
Closing the issue, as the soft notification is being deprecated.
