### ISSUE TITLE
Stage Selected Ranges still not working

### ISSUE THREAD

**Issue by leecollings** [microsoft/vscode#120823]
- VS Code Version: 1.55.0
- OS Version: Windows 10 1909

Steps to Reproduce:

1. View file with changes, select lines to stage.
2. Click three dots in top right, and click 'Stage Selected Ranges'.

Does this issue occur when all extensions are disabled?: Yes/No - I have no extensions.

It seems this has been reported several times online, and all the issues I've found state they are resolved without actually giving any real detail.

The issue is real, and very frustrating. I can only stage entire files, not selections within files.

**Comment by leecollings** [comment]
This is not a duplicated issue, there are no other open issues relating to this (they've all been closed)

**Comment by eamodio** [comment]
Can you post a video showing what isn't working? I stage and unstage lines in VS Code daily and I don't see any issues.
