### ISSUE TITLE
Inconsistent and non-themeable button in search

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120899]
![recording](https://user-images.githubusercontent.com/900690/114141615-21c5bc00-9912-11eb-9f80-17b9418d26d5.gif)

Hardcoded colors from:

https://github.com/microsoft/vscode/blob/23d1a967cfd717d34bfc851e1442ac926d740dfb/src/vs/workbench/contrib/search/browser/media/searchview.css#L292-L300

**Comment by roblourens** [comment]
Should this one have rounded corners?

**Comment by roblourens** [comment]
I don't think so unless the input box gets rounded corners too
