### ISSUE TITLE
Color Theme: Some icons not stylable

### ISSUE THREAD

**Issue by avoonix** [microsoft/vscode#120862]
- VS Code Version: 1.55.0
- OS Version: Linux x64 5.11.6-1-MANJARO

Most icons are stylable with `foreground`, but certain icons (from extensions) are not.

Steps to Reproduce:

Create a new theme:
```
{
  "$schema": "vscode://schemas/color-theme",
  "name": "theme",
  "type": "dark",
  "colors": {
    "foreground": "#ff0000",
  }
}
```

Result:
![image](https://user-images.githubusercontent.com/63160225/114089920-08dbed00-98b7-11eb-88da-da9ff28f3e52.png)
![image](https://user-images.githubusercontent.com/63160225/114089957-17c29f80-98b7-11eb-8802-c6acfc24828c.png)
![image](https://user-images.githubusercontent.com/63160225/114089972-1beebd00-98b7-11eb-87ac-c607a01aafc5.png)

Every icon should be red, but some are white. (Used extensions: mhutchie.git-graph, eamodio.gitlens, ms-vsliveshare.vsliveshare)

Does this issue occur when all extensions are disabled?: No

**Comment by gjsjohnmurray** [comment]
/causedByExtension You will need to report this to the extension authors and try to convince them to change what they're doing.

**Comment by avoonix** [comment]
> /causedByExtension You will need to report this to the extension authors and try to convince them to change what they're doing.

I don't think this should be each individual extension's responsibility. Extensions can only provide a dark and light icon: 
https://code.visualstudio.com/api/references/contribution-points#command-example
```
{
  "contributes": {
    "commands": [
      {
        "command": "extension.sayHello",
        "title": "Hello World",
        "category": "Hello",
        "icon": {
          "light": "path/to/light/icon.svg",
          "dark": "path/to/dark/icon.svg"
        }
      }
    ]
  }
}
```

The icons in the activity bar can be styled by color themes like builtin icons. Is there a reason this doesn't work for other icons?

**Comment by gjsjohnmurray** [comment]
pinging @misolori

**Comment by avoonix** [comment]
![image](https://user-images.githubusercontent.com/63160225/114096782-7c81f800-98bf-11eb-8e4c-0924ca1a8181.png)
(ie I don't see why the Git Graph extension creator should be responsible for adding a pink icon)

**Comment by misolori** [comment]
Extensions need to contribute the icon via an icon font in order for it to be themeable.
