### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by j-marcon** [microsoft/vscode#120879]
Issue Type: <b>Bug</b>

Hi, I'm trying to open different PNGs and get the following error message every time:
An error occured while loading the image.
Open file using VS Code's standard text/binary editor?

These are PNGs that I was able to view as of a few days ago. I'm on today's Insiders version. I'm not even sure where to check what went wrong as I'm not seeing anything in any log but I might be looking in the wrong place. Thanks for any help/thought on this.

VS Code version: Code - Insiders 1.56.0-insider (5904b7b686e9274631893d560fdbc55a5567f878, 2021-04-08T18:10:39.613Z)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1030NG7 CPU @ 1.10GHz (8 x 1100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv|--crash-reporter-id a0562944-c67b-46c7-b9a4-7d461326db2d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: pfe|
|OS|Linux x64 4.12.14-122.63.1.20210309-nasa|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (32 x 1200)|
|Memory (System)|62.37GB (24.62GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.5
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.3076
githistory|don|0.6.16
latex-workshop|Jam|8.16.1
svg|joc|1.4.5
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.6.728949111
cpptools|ms-|1.3.0-insiders4
vsliveshare|ms-|1.0.4116
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
hide-gitignored|npx|1.1.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.12
gitblame|wad|6.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30278404
vscoresta800:30283263
vsc_aa:30263845
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfilebutton:30280634
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554

```

</details>

**Comment by mjbvz** [comment]
Please test out the next insiders build (it should be out in 12 hours orso)  and let me know if you still see this error

**Comment by j-marcon** [comment]
It works on the new Insiders build. Thanks for the quick fix!

**Comment by j-marcon** [comment]
I've just realised a new issue. Now, when I try to split the tab right (Cmd + \), it transfers the image preview to the right but I lose the preview on the left.

**Comment by mjbvz** [comment]
This is unrelated so please open a separate issue
