### ISSUE TITLE
Fill out a Voluntary Product Accessibility Template (VPAT)

### ISSUE THREAD

**Issue by jfredrickson5** [Microsoft/vscode#12082]
Please consider filling out a VPAT for VS Code. This is a form that outlines the accessibility features and Section 508 compliance of a product. VS Code would be more readily adopted throughout the federal government if it has a VPAT available.

Current list of Microsoft VPATs, could serve as examples: https://enterprise.microsoft.com/en-us/industries/government/section-508-vpats-for-microsoft-products/

**Comment by chrisdias** [comment]
We are working on this...

**Comment by jfredrickson5** [comment]
I see that a VPAT [has been posted](https://enterprise.microsoft.com/en-us/industries/government/section-508-vpats-for-microsoft-products/). Thank you!
