### ISSUE TITLE
[Feature - Additional CLI API] A way to invoke extension functions / internal calls (basically anything you can currently run through the command palette) in a headless manner for use with automated setup and build processes

### ISSUE THREAD

**Issue by MostHated** [microsoft/vscode#120837]
Hey there,
 I have been trying everything under the sun that I can find in order to accomplish this, but have yet to find anything that works. I have been looking for a way to invoke extension functions / internal calls (basically anything you can currently run through the command palette) in a headless manner for use with automated setup and build processes. Similar to how you can run `code --install-extension ext.name.here` but expanded to allow for once an extension is installed, to be able to invoke one of the extensions commands directly using the same text string that would be used to run it from the command palette or when creating a new hotkey. An example being `code --run-command extensionname.extensioncommand` or `code --run-command task.taskname`, etc.

Thanks,
MH

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/105487

**Comment by MostHated** [comment]
While it seems pretty similar, that request was for actions to occur upon the window first opening. My request was the ability to run commands headlessly, aka without the need for the window to be opened at all, similar to the --install-extension command.
