### ISSUE TITLE
Create Branch button - fails to execute the 'create branch' function

### ISSUE THREAD

**Issue by sscholle** [microsoft/vscode#120805]
Issue Type: <b>Bug</b>

when using the button to create a branch, it fails to execute further after typing in the branch name.
but when using the 'command palette' function to 'create branch', then it works flawlessly

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.95GB free)|
|Process Argv|--crash-reporter-id deebe882-3b10-4aca-8f70-23083afda11f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.9
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
gitlens|eam|11.3.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.19
prettier-vscode|esb|6.3.2
angular-essentials|joh|11.0.0
Angular2|joh|11.0.0
vscode-peacock|joh|3.9.1
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
angular-console|nrw|17.1.0
material-icon-theme|PKi|4.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
vscorecescf:30285484
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by eamodio** [comment]
What button are you using that fails?

**Comment by sscholle** [comment]
![branch-button-fails-to-create-branch](https://user-images.githubusercontent.com/2486065/114724881-4bc91500-9d3c-11eb-8ffa-8fac033570d2.png)
the button click opens the 'toast' to enter the branch name, but then nothing happens after pressing 'enter'. 

![then-no-work](https://user-images.githubusercontent.com/2486065/114725288-abbfbb80-9d3c-11eb-93ee-e1871ef438f9.png)

**Comment by eamodio** [comment]
Ah, that is from GitLens not VS Code directly. And the issue is that the first input you need to select which branch to create the branch from. The next input is for the name of the new branch. 

I am planning to change that so you can just quickly create a new branch from the current one.
