### ISSUE TITLE
Improve UX of completed and hidden items and the recent workspaces list

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#120855]
## Overview
This is to track improving the way that Getting Started items are displayed when there are no items left.

## Concept
One idea is to shift the content to make better use of the space. This would move the "Recents" list to the right and place "Getting Started" below it. We'd also have some way to trigger resetting items if someone accidentally dismisses one.

![CleanShot 2021-04-08 at 11 53 01](https://user-images.githubusercontent.com/35271042/114081399-5d547d80-9861-11eb-85c6-5c8f0eb72dc2.gif)

And in the case we want to have a setting to completely hide "Getting Started", it would like this:

![image](https://user-images.githubusercontent.com/35271042/114081381-57f73300-9861-11eb-85b6-aa085ecca566.png)

**Comment by JacksonKearl** [comment]
Currently:
![image](https://user-images.githubusercontent.com/8586769/114223061-390da500-9924-11eb-9e3b-a5f14bf664c5.png)

![image](https://user-images.githubusercontent.com/8586769/114223170-5773a080-9924-11eb-82b6-16ab14fcea90.png)

![image](https://user-images.githubusercontent.com/8586769/114223191-5d698180-9924-11eb-84cc-733984b6ea77.png)

Using a top-level "configure" button as opposed to one mounted on the getting started list, could go either way with this. I was thinking that once we add a section for changelogs it'd be nice to have a single way to configure everything, though that might be confusing... will revisit when the time comes.

**Comment by JacksonKearl** [comment]
An aside, it could be neat to render the recent list more like the getting started tiles, perhaps with an icon corresponding to the remote provider, or if its a file vs workspace vs folder or something.
