### ISSUE TITLE
Debug Listener Crashes when TCP Connection is Closed

### ISSUE THREAD

**Issue by digipedia** [Microsoft/vscode#12086]
- VSCode Version: 1.5.2
- OS Version: Windows 8.1

Steps to Reproduce:
1.  Launch a Visual Studio Code Node Project. 
2.  Close the TCP connection of the debug listener (currPorts freeware utility is helpful for this http://www.nirsoft.net/utils/cports.html).

The following error was encountered sporadically (approximately once a week) when debugging in Visual Studio Code:

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at TCP.onread (net.js:552:26)

I was able to reproduce this error by closing the TCP connection of the debug listener when debugging in Visual Studio Code.

I believe it should be possible to handle and recover from this error, because the node express application I am debugging is able to reconnect when I close its TCP connection.

**Comment by weinand** [comment]
Cannot reproduce.
