### ISSUE TITLE
Ability to disable commit message length warning.

### ISSUE THREAD

**Issue by JoshMcCullough** [Microsoft/vscode#12089]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. In the Git panel/tab, enter a commit message which is longer than 50 characters.
2. Note that a warning is displayed.

![image](https://cloud.githubusercontent.com/assets/4859660/18557943/f864b974-7b3e-11e6-9e5f-ec6fecf4b8c3.png)

I find this warning to be a bit controlling, and would like to disable it. The opinion that a commit message should be < 50 characters may not work for every user, or every team.

**Comment by jhasse** [comment]
That's already implemented: `"git.enableLongCommitWarning": true,` in the settings.

**Comment by JoshMcCullough** [comment]
Thanks! I couldn't find it.
