### ISSUE TITLE
Can't 👀 popup full text

### ISSUE THREAD

**Issue by senyai** [microsoft/vscode#120833]
Hi!

  I think that popup should allow text scrolling. For example, I have no idea what the extension is asking:
![image](https://user-images.githubusercontent.com/76137/114034856-3f9a0f00-9887-11eb-9ad7-4988683d61f1.png)

- VS Code Version: 1.55.0
- OS Version: fedora 33

Steps to Reproduce:

1. Install johnstoncode.svn-scm extension;
2. Open revisioned svn directory;
3. Delete many files in from the directory.

**Comment by bpasero** [comment]
If you hover over the notification does that reveal more? I do think though that we trim the message at one point. 

I do not think that notifications are the right place to show lots of content. Extensions can leverage a output channel e.g. for diagnostic messages.
