### ISSUE TITLE
add an icon for the "crud" folder

### ISSUE THREAD

**Issue by pibuxd** [microsoft/vscode#120814]
Add an icon for the "crud" folder similar to e.g. the "models" folder
![image](https://user-images.githubusercontent.com/60739485/114012187-4d8b6800-9866-11eb-9973-70532e64e5e9.png)

**Comment by IllusionMH** [comment]
/causedByExtension

These icons are provided not by built-in theme.
See https://github.com/PKief/vscode-material-icon-theme#folder-associations or request this change in extension repo.
