### ISSUE TITLE
Sash hover screen cheese on suggest details

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#120865]
![image](https://user-images.githubusercontent.com/35271042/114090667-9514f280-986c-11eb-99fb-89eb86e6f4a8.png)

This one is a gnarly one:

1. Open suggestion with description open and have cursor above bottom of description
  ![image](https://user-images.githubusercontent.com/35271042/114090750-aeb63a00-986c-11eb-99b7-57e394c04a8d.png)
2. Hit enter
3. :bug: sash stays behind 

Tried this via css with `margin-bottom`

**Comment by misolori** [comment]
@jrieken What's the duplicate issue?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/120828
