### ISSUE TITLE
In the latest insiders build, using the LaTeX Workshop extension makes it impossible to type an opening curly brace directly after "\end"

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#120842]
Issue Type: <b>Bug</b>

1. Create a file
2. Set language to `latex`
3. Type `\end`
4. Try to type `{`

This is likely an issue in VS Code itself, as it does not occur on stable non-insider versions (I have tested this)

VS Code version: Code - Insiders 1.56.0-insider (58186680eb97fe979e1d986bcfa983ab0a6228e4, 2021-04-06T10:32:50.846Z)
OS version: Linux x64 5.11.0-7612-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (1.18GB free)|
|Process Argv|--no-sandbox --crash-reporter-id dbbd25fe-3f4e-426a-9c89-45e060834124|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-fish|bma|1.0.20
vscode-markdownlint|Dav|0.40.1
vscode-deno|den|3.2.0
gitlens|eam|11.3.0
vscode-pull-request-github|Git|0.25.0
haskell|has|1.2.0
discord-vscode|icr|5.4.0
latex-workshop|Jam|8.16.1
language-haskell|jus|3.4.0
powershell-preview|ms-|2021.4.1
linux-desktop-file|nic|0.0.14
stardog-rdf-grammars|sta|0.1.2
change-case|wma|1.0.0

(4 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
Please report directly against https://github.com/James-Yu/LaTeX-Workshop
