### ISSUE TITLE
Material theme not working

### ISSUE THREAD

**Issue by SR-22** [microsoft/vscode#120812]
-Version: 1.55.0 (user setup)
-OS Version: Windows_NT x64 10.0.19042

Often using VS code my material theme doesn't work especially on start. I tried uninstalling it and reinstalling the theme and that fixed the problem but it still happens. Closing vs code and reopening helps it. This seems odd  so I decided to create an issue about it. The problem still happened even after uninstalling vs code and reinstalling it again

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
The material theme comes from an extension as we don't ship one out of the box. Which extension is it?

**Comment by SR-22** [comment]
Hey there Martin,
That couldn't wrap around my head. I use this extension
![image](https://user-images.githubusercontent.com/79589166/114049078-c27f9180-98a8-11eb-932d-95a61c30571e.png)

**Comment by SR-22** [comment]
Thanks it is solved BTW
