### ISSUE TITLE
Option to enable colour decorators for more file types

### ISSUE THREAD

**Issue by 0x5c** [microsoft/vscode#120838]
Colour decorators help users seeing what colour hex codes are.
As stated in #109852, it's by-design that colour decorators are only shown where highlighting defines a token as a colour, and when a JSON schema declares a property to be a colour. It makes sense as a lot of things that aren't actually colours would get a swatch, including the ID of that issue.
But it would be great to have an option to force it to be shown to all/more filetypes, and/or on a per-file basis. That would help when no schema exists and in one-off cases.

**Comment by aeschli** [comment]
There's an API that lets extensions define color decorators: https://code.visualstudio.com/api/references/contribution-points#contributes.colors
That's what's used by the built-in extensions for JSON, CSS and HTML based on their language/schema knowledge.
If you miss the support for a language, look for language extensions and if color decorators missing there, I recommend you to file an issue against the language extension.
Or you can implement your own extension that uses a different approach, e.g. based on regular expressions.
