### ISSUE TITLE
Garbled characters cannot be avoided

### ISSUE THREAD

**Issue by tomgin** [microsoft/vscode#120888]
Issue Type: <b>Bug</b>

Open the file, set the encoding to EUC-JP, and type double-byte "~" in Japanese to save. Open it in another code editor (either Atom or sublime text) and
If you change from UTF8 to EUC-JP, what is the previous ~? It has changed

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 18.7.0

**Comment by bpasero** [comment]
If there is issues with other editors, I suggest to report that issue to them. Let me know if you see an issue purely within VSCode.
