### ISSUE TITLE
Debugger keeps stepping into skipped files

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#120807]
We have written the needed data into your clipboard bec
Issue Type: <b>Bug</b>

I have set my launch configuration up with:
```json
      "skipFiles": [
        "<node_internals>/**",
        "*/.vscode-server/**",
        "*\\.vscode-server\\**"
      ]
```

Yet, while debugging a VS Code extension, VS Code keeps stepping into `/home/oliver/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/out/vs/server/remoteExtensionHostProcess.js`

The slashes sometimes appear as backslashes in the VSC UI. No idea why, but I figured that could be related to the problem.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (34.37GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (34.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (34.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (34.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.14GB (34.64GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.2.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
eslint-disable-snippets|drK|1.3.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
vs-code-xml-format|fab|0.1.5
generateuuid|Fir|0.0.5
shell-format|fox|7.0.1
vscode-graphql|Gra|0.3.15
terraform|has|2.9.1
vscode-esformatter|how|1.6.0
innosetup|idl|1.6.0
template-string-converter|meg|0.4.7
code-beautifier|mic|2.3.3
vscode-puglint|mrm|2.3.0
vscode-docker|ms-|1.11.0
js-debug-nightly|ms-|2021.4.717
vscode-js-profile-flame|ms-|0.0.14
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.28
speckle|rbu|1.4.3
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>
ause it was too large to send. Please paste.

**Comment by oliversalzburg** [comment]
While looking into this again, I'm also again reminded of https://github.com/microsoft/vscode/issues/117347

I was trying to add `"/home/oliver/.vscode-server/**"` to my `skipFiles` to see if that makes a difference. Now I'm again stepping into node internals, even though `"<node_internals>/**",` is in my `skipFiles` as well.

This makes some sense, because VS Code seems to believe the path of the file I'm looking at is `\<node_internals>\buffer.js`. I don't understand why VS Code displays a backslash here. I am working on WSL.

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode-js-debug/issues/1085
