### ISSUE TITLE
Notebook screen cheese with experimental markdown cell renderer

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#120845]
When using the experimental notebook markdown cell renderer and collapsing a renderer markdown cell you end up with a visually corrupted notebook. Below is one example. Expanding a collapsed cell causes similar issues.

![nftfhhmWvo](https://user-images.githubusercontent.com/4674940/114056163-3b013680-9846-11eb-9235-d81f8b2a8882.gif)

**Comment by mjbvz** [comment]
Similar to #120513

Not math specific
