### ISSUE TITLE
Collapse All button for extension's TreeDataProvider should keep focus

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode#120990]
Issue Type: <b>Bug</b>

_originally filed in https://github.com/microsoft/vscode-azurefunctions/issues/2689_

## Repro Steps

1. F5 the tree-view-sample extension here: https://github.com/Microsoft/vscode-extension-samples/tree/main/tree-view-sample
2. Use the tab/arrow keys so that your keyboard focus is on the "collapse all" button for the "Test View" pane
    <img width="242" alt="Screen Shot 2021-04-09 at 4 19 11 PM" src="https://user-images.githubusercontent.com/11282622/114249404-5d32ab80-994f-11eb-98f7-e2dc5402dc0f.png">
3. Hit enter

## Expected

Keyboard focus stays on the "collapse all" button.

NOTE: If I follow the same repro steps for the standard file explorer's "collapse all" button, this _is_ what happens.

## Actual

Keyboard focus moves to the first item in the tree

VS Code version: Code - Insiders 1.56.0-insider (845efe5d8e31079cc858131c95c36103d9439e74, 2021-04-09T09:50:42.652Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 5, 4|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 63154ab5-ba0e-419a-aa36-bd67d86db27f|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
From the description it sounds like the `collapse` action in the custom tree passes focus to the custom tree.
The focus should stay on the `collapse` action.

Forwarding to @alexr00
