### ISSUE TITLE
iPad: read mode should be the default

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#120943]
iPad, safari or Chrome

As soon as you tap on the editor and focus is moved into the editor the keyboard is shown below thus reducing screen real estate.
I believe that the best experience for an iPad would be that the keyboard appearing would be a much more explicit gesture.
This is because I also believe that most of the iPad use case is code reading, not actually code writing.

I think we could tackle this by:
* Make all editors readonly by default on ipad, and there is a specific user action to make them read write
* Be more careful when automatically pasing focus to the editor, and try to not do this at all on an iPad

Or if there are other tricks for this? I do not think a web page can disable a on screen keyboard.

fyi @bpasero @alexdima

**Comment by bpasero** [comment]
I somehow recall that we had an explicit button in the editor to reveal the keyboard, but Alex would know best. Maybe instead of making all editors readonly, we could simply not show the keyboard until that button is pressed. I recall it was like one of the floating click widgets in the bottom right of the editor.

**Comment by isidorn** [comment]
Yeah I think that would be best. I was just not aware if we could control showing of the keyboard. If we can than a floating blue button is a good start.

**Comment by rebornix** [comment]
> I believe that the best experience for an iPad would be that the keyboard appearing would be a much more explicit gesture.
> This is because I also believe that most of the iPad use case is code reading, not actually code writing.

👍 , I think the experience would be much better if the editor/workbench is in reader mode by default. But this might not be true if iPad has a keyboard attached. For example, I have being using iPad Pro for 3 years, keyboard attached all the time. Whenever I open safari, I use the keyboard (in other words, I never open codespace without using the keyboard). Having once more action to turn the editor to non-readonly mode feels redundant.

> Or if there are other tricks for this

If we receive a keyboard event and `visualViewport  === viewport`, it might mean users are typing through an external keyboard, maybe we can switch to editing mode automatically?

**Comment by isidorn** [comment]
Good points.
I think a good starting point would be just to have a setting. So by default we are readonly, there is a blue button to be read write, and for those "pro" users which have the keyboard and want to edit they can change the setting.

**Comment by isidorn** [comment]
Thinking a bit more about the iPad experience I really like our Activity bar as a perfect touch UI.
I think another very important part of our UI is not that accessible on the iPad - the Command Palette. Easiest way is to touch on the Gear -> Command Palette

Due to that I am thinking about enriching the acivity bar on the iPad with having two more icons, one for the command palette (like in the good old times) and one to toggle read only mode (like a big checkbox).
They would be down since they do not have views attached to them

Let me know what you think about this.
also fyi @misolori

**Comment by isidorn** [comment]
I have verified that setting `readonly` on the textarea makes the keyboard not popup.

Having a blue floating widget for each editor sounds like one optoin. Downside is that it takes screen real estate and that it is per editor.
I might actually prefer to have an entry in the activity bar
@misolori is it possible to design an activity bar icon which would convey read-only ness? It might need to be a toggle?
Another icon for the quick pick might also make sense. These are just idea, let me know what you think

**Comment by gjsjohnmurray** [comment]
The ability to toggle an editor between edit and readonly is something I think there have been many requests for over the years. So maybe don't limit it solely to iPad users.

**Comment by isidorn** [comment]
@alefragnani might you have an idea if it possible to control collapsing the keyboard programmatically from the browser on the iPad?
I googled around and was unsuccessful to find anything useful.

**Comment by alefragnani** [comment]
@isidorn unfortunately not. 

The only references I found where about checking for touch capabilities on `document` (so it would, in theory, be possible to decide if the editor must be read-only or writeable) or firing `.blur` on the textField to hide the keyboard. But as you said, I'm not sure these are useful, or even effectively works.

I'll google a bit more and comment here if I find anything useful.

**Comment by isidorn** [comment]
I actually would not change anything regarding making the editor read only by default.
My current thinking is that this should be handled by the iPad (hiding the keyboard). Also the current experience if you have an external keyboard is actually ideal (nothing pop ups).

On our side is that we should just not automatically focus the editor. Not doing that is captured as part of other issues.

So I would only introduce a global setting or something once we receive feedback from users that the keyboard is too aggressive.

**Comment by isidorn** [comment]
Upon more thinking I think we should not do this, but instead strive to not auto open the virtual keyboard.
Thus closing this as no action is planned
