### ISSUE TITLE
MacOS (x86) binary not in PATH after restart

### ISSUE THREAD

**Issue by marklabrecque** [microsoft/vscode#120980]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Run the command "Install code in PATH" from the command palette.
2. Check the terminal, it should find the 'code' binary.
3. Restart the computer and check again - "command not found: code"

Does this issue occur when all extensions are disabled?: Yes

It looks like running that command palette operation mentioned above adds a symlink to the /usr/local/bin directory, which is what I would expect it to do. However, the target of the symlink is a bit odd. I just checked and I see the following in /usr/local/bin:

code -> /private/var/folders/mt/fmkgwzfj1kvg8s105b7znrfh0000gn/T/AppTranslocation/A37EC2BC-124B-4A46-A943-464286617262/d/Visual Studio Code.app/Contents/Resources/app/bin/code

Once rebooting, it looks like the symlink target is no longer a valid path. In my case, when I rebooted, the path segment after AppTranslocation changed to a different UUID, but the rest of the PATH looked correct.

A workaround for now was for me to manually add the following entry to my PATH env var: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin which of course persists over a reboot, as it is a direct link to where the application lives.

OS Platform: MacOS 11.2.3 (x86 architecture)
VS Code version: 1.55.0 (Universal)

Feel free to contact me for more information/details @ mark.labrecque@gmail.com

**Comment by joaomoreno** [comment]
macOS seems to have put VS Code into quarantine in your system. Here's how you can solve it: https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469
