### ISSUE TITLE
Unable to disable Jupyter diff preview without disabling Python extension

### ISSUE THREAD

**Issue by de-code** [microsoft/vscode#120900]
- VS Code Version: 1.55.0
- OS Version: Linux

Steps to Reproduce:

1. Install / Enable Python extension
2.  Create a notebook
3. Stage / Commit changes
4. Change notebook
5. Review the diff output

It is showing two rendered Jupyter notebooks side-by-side with no indication of what has changed.
I also tried enabling / disabling the "enhanced diff".

Expected: Being able to use simple JSON file diff

That seems to be possible by disabling the `Jupyter` extension. Unfortunately that also requires disabling the `Python` extension (as `Python` has a dependency on `Jupyter`).
(Previously I was still able to use the JSON diff while using the `Python` extension)

Does this issue occur when all extensions are disabled?: No

**Comment by rebornix** [comment]
@de-code can you share a screen shot of what it looks like?

**Comment by de-code** [comment]
Default diff view with Jupyter enabled and enhanced diff disabled (it renders Jupyter notebooks side by side without indication of change):

![image](https://user-images.githubusercontent.com/1016473/114263477-99145200-99dd-11eb-9646-95d18b82510c.png)

It looks pretty much the same with "enhanced diff" enabled:

![image](https://user-images.githubusercontent.com/1016473/114263555-1fc92f00-99de-11eb-8cc5-403405ee3b6d.png)

After disabling the `Jupyter` extension (and with it `Python`), the JSON is not ideal but at least it is showing exactly what has changed:

![image](https://user-images.githubusercontent.com/1016473/114263589-66b72480-99de-11eb-8405-623a80727ab8.png)

**Comment by de-code** [comment]
I guess two main things have changed since the issue was raised:
- the Jupyter extension can be disabled without disabling Python
- the notebook diff has significantly improved, by highlighting the changes, as well as showing metadata

It would still be nice to be able too choose the way the diff work, but that seems to be minor now.

Therefore I will close the issue.

Screenshot of new diff:

![image](https://user-images.githubusercontent.com/1016473/124027596-f91e0180-d9ea-11eb-9e3d-a782d000f502.png)
