### ISSUE TITLE
UI - Padding problem in Activity bar views.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#120917]
- VS Code Version: Stable and latest insider builds.
- OS Version: Windows 10 20h2

Steps to Reproduce:

@joaomoreno  **And this padding difference also in Explorer, Search, Tiimline, Extensions,,,, etc.** 

**Insider**

![image](https://user-images.githubusercontent.com/17777237/114167267-04531b00-992f-11eb-86d1-45c9be77eb94.png)
![image](https://user-images.githubusercontent.com/17777237/114169916-7b3de300-9932-11eb-97fb-e01aaa47c336.png)

**Stable**

![image](https://user-images.githubusercontent.com/17777237/114167451-3bc1c780-992f-11eb-8eb8-824a34aa09e5.png)
![image](https://user-images.githubusercontent.com/17777237/114169944-8133c400-9932-11eb-90f2-d3ffe5e9f263.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
There might be slight changes, but the current state in `main` is decent. Thanks for the issue.
