### ISSUE TITLE
Open file to the side from file explorer always opens file in text editor

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120948]
Issue Type: <b>Bug</b>

Right click on a github issue notebook file, click "Open to the side", it opens github issue notebook in text editor.

VS Code version: Code - Insiders 1.56.0-insider (Universal) (845efe5d8e31079cc858131c95c36103d9439e74, 2021-04-09T09:50:42.652Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.75GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Same cause as #116259. Fixing with the refactoring

**Comment by lramos15** [comment]
This has since been fixed :)
