### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by tango-one** [microsoft/vscode#120912]
Issue Type: <b>Feature Request</b>

When I create a folder, its hard to see where I am in the folder structure.

would be mutch bet to use a "+" before the drawer if there is sub drawers/folders.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 6.1.7601

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks
