### ISSUE TITLE
Focus order is not logical while navigating to the 3 controls "next previous problem" and "close button"

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode#120921]
1. have a file with an error
2. press shift+ F8
3. Tab into the error message popup and tab to the 3 controls "next previous problem" and "close button" and view the order of tab navigation.

![image](https://user-images.githubusercontent.com/24580570/114171114-79374c80-9951-11eb-89ce-9fd006287838.png)

**Comment by sandy081** [comment]
Can you please test with latest version of VS Code - you can now navigate using arrow buttons instead of tab
