### ISSUE TITLE
PHP void keyword is highlighted as support.class

### ISSUE THREAD

**Issue by andregalastri** [microsoft/vscode#120954]
- VS Code Version: 1.55.1
- OS Version: Ubuntu 20.04

- Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce:

1. Create a new .php file
2. Paste the following code
  ```php
<?php
class MyClass
{
    public static function methodA() : void
    {
    }

    public static function methodB() : string
    {
        return "I'm a string";
    }
}
  ```
3. Check the editor tokens and scopes
![image](https://user-images.githubusercontent.com/49572917/114222951-9bc36880-9945-11eb-98a9-07e0036d4b02.png)

You will see that the void type declaration is hightlighted as a support.class. I understand that it is a keyword, like `string`, `int` and others, not a class.

**Comment by roblourens** [comment]
Filed upstream: https://github.com/atom/language-php/issues/422
