### ISSUE TITLE
Higlighting of jsx file is inconsistent

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#12093]
- VSCode Version: 1.5.2 (run with --disable-extensions)
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Open .jsx file
```
import React from 'react'
function render() {
    return (
        <div>
            <table >
                <thead>
                    <tr>
                        <th className="b"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td className="b"></td>
                        {this.items.map(item =>
                            <td key={item.code} className="b">{item.value}</td>
                        ) }
                    </tr>
                    <tr>
                        <td className="b"></td>
                        {this.items.map(item =>
                            <td key={item.code} className="b">{item.value}</td>
                        ) }
                    </tr>
                </tbody>
            </table>
        </div>
    )
}
render()
```
Note a space in `<table >` tag.
2. Remove a space in `<table >` tag.
Color of last `<td>` content changes

![2](https://cloud.githubusercontent.com/assets/1114090/18559438/e5f954ca-7b7f-11e6-8a9a-8028a4e869e5.png)
![1](https://cloud.githubusercontent.com/assets/1114090/18559439/e7d5d2f0-7b7f-11e6-81d2-c2c8f59f261f.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10955

**Comment by waderyan** [comment]
@anvish thank you for opening this issue. This is likely a TypeScript language service issue so I've passed on to them.
