### ISSUE TITLE
Error when installing Apex extension

### ISSUE THREAD

**Issue by alexandra7611** [microsoft/vscode#120949]
Issue Type: <b>Bug</b>

I get an error when I am trying to install the Salesforce Extension pack. It seems to be with the Apex* extensions. I opened a ticket with the Salesforce team and they said it was an issue with VSCode: https://github.com/forcedotcom/salesforcedx-vscode/issues/3132

[2021-04-09 11:33:46.662] [renderer1] [error] ["validating: extension/package.json not found inside zip.","    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)","    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-04-09 11:33:46.701] [renderer1] [error] extension/package.json not found inside zip.: validating: extension/package.json not found inside zip.
    at H.downloadInstallableExtension (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217845)
    at async H.doInstallFromGallery (file:///C:/Users/ITA36/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (18.78GB free)|
|Process Argv|--crash-reporter-id fc0ee0cd-3039-4ad0-bdc4-473378bc7fcd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoccf:30282075
vscoresta800:30284044
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by gjsjohnmurray** [comment]
I suggest you download the VSIX file manually from Marketplace and try installing that. If it still fails, send the downloaded file to the extension developer and ask them to verify that the contents are as expected. It's possible that something is mangling the file en route to you. Maybe antivirus?

**Comment by sandy081** [comment]
Can you please try above suggestion and let me know if it works?

**Comment by alexandra7611** [comment]
@sandy081 Working with my company to do this. We do not have access to download.

**Comment by sandy081** [comment]
Ok please let us know once you get the VSIX

**Comment by alexandra7611** [comment]
@sandy081 We get this error when trying to download it directly:

When i navigated to that URL i saw this:
"{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}"

That doesn't look like it was blocked by us... I sent it to my personal home device and saw the same.

**Comment by sandy081** [comment]
I am sorry that I can be helpful here as it seems to be your network issue
