### ISSUE TITLE
Improve terminal tabs + button

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#120960]
See https://github.com/microsoft/vscode/pull/120878#discussion_r610622560

**Comment by eamodio** [comment]
IMO the + button is too close to the terminal tabs and its heigh doesn't match the others so it looks kind of visually off to me. It also only gets focus feedback _after_ the menu is dismissed.

I would also love to see the + button be a split button or something, where you can open a new default terminal in a single click, and only open the menu if you want to select a different one
