### ISSUE TITLE
iPad: can not trigger context menu outside of Editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#120956]
iPad

Currently you can trigger a context menu on the editor by holding a click.
However you can not trigger a context menu anywhere else in the workbench.

@rebornix is there something special that we do for this in the editor?
Might we need to do that in all the places?

fyi @joaomoreno for tree

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/rebornix/optimize-outputs-grow-height/src/vs/base/browser/touch.ts#L210-L216 

We can listen to the custom touch/context menu events from `touch`

**Comment by isidorn** [comment]
@rebornix oh that's great!
@joaomoreno could you adopt this in the List? I can also look into this if you prefer
@bpasero do we have one central place in the workbench where we trigger a context menu on right click? So I can look into changing that to listen on touch/context as @rebornix suggests

**Comment by bpasero** [comment]
@isidorn please sync with @sbatten who owns our custom menus

**Comment by isidorn** [comment]
@sbatten ping regarding this issue

**Comment by isidorn** [comment]
Ok, so a bunch of components listen to `contextmenu` event. They will now have to listen to the touch context menu event as well.
I can do a pass and adopt it across the workbench. Assigning to May to do it then.

fyi @joaomoreno for list / tree

**Comment by isidorn** [comment]
Might be a bit of bigger task since the list does not seem to recognize from the touch event on what element it is being triggered.
Apart from that transforming a touch event to a BrowserMouseEvent might not work

**Comment by isidorn** [comment]
fyi @joaomoreno just in case you are in an iPad bug destroying mode...

**Comment by joaomoreno** [comment]
Pushed a fix for all list/tree/tables. 🚀

**Comment by isidorn** [comment]
Awesome 👏 
We are actually now covered for most of the workbench.
Let's assign to June so I go through all the workbench and just make a list of places where it still does not work.

**Comment by isidorn** [comment]
Here's are some places where the long press still does not trigger a context menu:

- [ ] Activity bar @sandy081 
- [ ] View title area @sandy081 
- [ ] Split view title area @sandy081 
- [ ] Status bar @isidorn

@sandy081 could you maybe look into some of the above and just do the same fix as @joaomoreno did for the list / tree. That is to listen to `TouchEventType.Contextmenu`.
If you prefer I can also do it. Let me know what works best

Most of the other context menu usages are inside the list and tree and I think we are already good there.

**Comment by isidorn** [comment]
@sandy081 I actually started looking into the other areas. So you can hopefully just review my work once I push 😊

**Comment by isidorn** [comment]
I think I captured most of the cases in my list above. I just fixed them and this seems to work fine.
There are probably still some cases where we are not properly listening on touch context menu event but for now I am very happy with what we have and we will tackle the other issues as they come.

**Comment by isidorn** [comment]
fyi @Tyriar @meganrogge if they would like to do the same thing for the terminal (even though we do not support the terminal  for web cases it would be nice to have this for touch laptops). So the fix is just to add you element to Gesture targets and listen on Gesture context menu. Let me know if you would prefer that I create an issue for you for this.
