### ISSUE TITLE
Prompt user for opening all tabs for replace all

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12097]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

Currently, if someone is doing a project-wise replace, VSCode opens all modified files after the change.

If 100 files are changed, VSCode opens 100 tabs. Should prompt user.

**Comment by jhasse** [comment]
Prompting would be annoying for me. VSCode should just replace the text in all the files and don't bother to open any tabs at all IMHO.

**Comment by bpasero** [comment]
@sandy081 fyi

**Comment by Tyriar** [comment]
Might make sense after a certain threshold is hit?

**Comment by octref** [comment]
I feel the current behavior is fine.
