### ISSUE TITLE
Editor toolbar icons miss paddings

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120905]
Stable:
![image](https://user-images.githubusercontent.com/900690/114146698-31e09a00-9918-11eb-82db-2283642ffc6f.png)

Insiders:
![image](https://user-images.githubusercontent.com/900690/114146711-360cb780-9918-11eb-908e-bff291d2bedd.png)

I think we can probably reduce the padding a bit, but I find the current insiders one way too narrow.

**Comment by joaomoreno** [comment]
Yeah there are customizations for when there are tabs and otherwise... our CSS is a huge mess.
