### ISSUE TITLE
Allow updating a configuration by ID

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120940]
I'd like to dynamically update a configuration's enum at runtime based on the environment and user settings. This will help with https://github.com/microsoft/vscode/issues/119366

Something like this:

```ts
configurationRegistry.updateConfiguration('terminal.integrated.profiles.windows.default', {
  type: 'string',
  enum: ...
});
```

**Comment by sandy081** [comment]
@bpasero @Tyriar @JacksonKearl Can one of you please verify that your components are working after adopting to this new API.

**Comment by JacksonKearl** [comment]
verified welcome page change

**Comment by lramos15** [comment]
Marking as verified due to Jackson's approval
