### ISSUE TITLE
codicon's not working when hover over codespace

### ISSUE THREAD

**Issue by fara-nak** [microsoft/vscode#120988]
i'm trying to implement below design:

![image](https://user-images.githubusercontent.com/48534922/114245919-3de35080-9946-11eb-81be-68fe3ecf2292.png)

the icons are [codicons](https://code.visualstudio.com/api/references/icons-in-labels), I tried to pass them to the treeview toolpits as MarkdownStrings as mentioned [here ](https://code.visualstudio.com/api/references/vscode-api#668:~:text=When%20created%20with%20supportThemeIcons%20then%20rendering,icons%20via%20the%20%24(%3Cname%3E)%2Dsyntax%20is%20supported.) asn set the `supportedThemeIcon `to `ture`

but vscode doesn't seem to be able to parse it correctly and returns a normal string:
![image](https://user-images.githubusercontent.com/48534922/114246670-0bd2ee00-9948-11eb-926e-a1ffaf4c92ee.png)

**Comment by fara-nak** [comment]
@alexr00  in case you need to look at the code: [PR](https://devdiv.visualstudio.com/DevDiv/_git/Cascade/pullrequest/316263?_a=files)

**Comment by alexr00** [comment]
We use codicons in tree hovers in the GitHub Pull Requests and Issues extension here: 

https://github.com/Microsoft/vscode-pull-request-github/blob/a1dc3abf08bd755dd1b3388e4aa4a9703102ee33/src/issues/util.ts#L276-L277

Looks like that is still working well. Can you use that as a reference?

**Comment by alexr00** [comment]
It looks like you call several other methods on your strings before adding them to your markdown string using `.appendMarkdown`. Maybe one of those calls is escaping the `$()`?

**Comment by fara-nak** [comment]
from what I see it has been used for [treeView ](https://github.com/microsoft/vscode-pull-request-github/blob/a1dc3abf08bd755dd1b3388e4aa4a9703102ee33/src/issues/issuesView.ts#LC121:~:text=tooltip%20%3D%20await)not treeViewItem. 
we don't escape the `$()` anywhere, I just directly added `$(arrow-down)` to `treeViewItem.toolpit` [here ](https://devdiv.visualstudio.com/DevDiv/_git/Cascade?path=%2Fvscode%2Fcodespaces%2Fsrc%2FtreeView%2FEnvironmentExplorer.ts&version=GBmain&line=242&lineEnd=242&lineStartColumn=13&lineEndColumn=42&lineStyle=plain&_a=contents)and still not working.
![image](https://user-images.githubusercontent.com/48534922/114591549-e04d4d80-9c3e-11eb-8229-35a58dd7b330.png)

**Comment by alexr00** [comment]
@fara-nak I have updated the tree view sample extension to include an example of how to use codicons here: https://github.com/microsoft/vscode-extension-samples/commit/b338bca265ce33b774242cc82c645dd30014e152

Please try out the sample and let me know if you can repro the behavior you're seeing with the sample!
