### ISSUE TITLE
meta+n shortcut not working

### ISSUE THREAD

**Issue by SalmanAlSaigal** [microsoft/vscode#120933]
- VS Code Version: 1.55
- OS Version: macOS 11.2.3

Steps to Reproduce:

1. Create a keyboard shortcut with "alt+n"

Does this issue occur when all extensions are disabled?: Yes

I'm trying to map the "meta+n" shortcut to the command "workbench.action.nextEditorInGroup". But when I press the "meta+n" shortcut, it inserts the symbol ˜ instead. I verified that the shortcut works perfectly with "meta+m".

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/41024
