### ISSUE TITLE
[web/remote] cannot download folders

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#120908]
I cannot download folders in Gitpod and Codespaces:
<img width="1788" alt="Screenshot 2021-04-09 at 10 19 51" src="https://user-images.githubusercontent.com/3082655/114151313-483d2480-991d-11eb-8fb4-1ebeb9660c7c.png">

It asks me to select a folder and after that displays the dialog above. I would expect that it creates a folder (or an archive with the content) in `Downloads` on my disk.

**Comment by bpasero** [comment]
You cannot pick a system folder directly. This is a decision Chrome makes.

**Comment by akosyakov** [comment]
@bpasero I was wondering whether you consider to tar selected resources (if there are multiple) and stream the archive while downloading? It should resolve the issue and also have less data to transfer.

**Comment by bpasero** [comment]
I think if there was a way to compress and zip directly from the browser and stream to disk without involving server knowledge, that could be an alternative. Otherwise, we typically do not encode server side knowledge into VSCode unless there is no other way.
