### ISSUE TITLE
Use Git rather than GitHub icon for Git-related files in default icon set

### ISSUE THREAD

**Issue by PranayAgarwal** [Microsoft/vscode#12096]
Love the new file icons feature, but have one minor issue: Git-related file types are mapped to the GitHub icon:

![image](https://cloud.githubusercontent.com/assets/341507/18561439/b78bc546-7b34-11e6-8b90-ebef9707d432.png)

This can be seen in extensions/theme-seti/icons/vs-seti-icon-theme.json:
```json
"gitignore": "_github",  
"gitkeep": "_github",  
"gitattributes": "_github",
```

A little nitpicky, I know, but Git != GitHub. A Git icon ![image](https://cloud.githubusercontent.com/assets/341507/18561363/5d115f4a-7b34-11e6-8099-1e1dc1a01f9b.png) (also available in Seti) would be more appropriate.

**Comment by Tyriar** [comment]
If the icon is available in Seti then we should absolutely do this imo.

**Comment by aeschli** [comment]
It's what the Seti theme does. See https://github.com/jesseweed/seti-ui/blob/6c6e63900105d326bd1b7475b8c04af57986ece2/styles/icons/mapping.less

Please file your suggestion there, VSCode will then pick it up from there.
