### ISSUE TITLE
Electron: crash reporter slows down startup

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120902]
There is a new perf mark to measure the impact of the crash reporter on the startup which is a sync blocking call. 

Even on my fast macOS ARM machine, this seems to consume a considerable amount of time:

![image](https://user-images.githubusercontent.com/900690/114145845-2b055780-9917-11eb-8288-d7fcd13dd8d1.png)

Given the crash reporter does not provide any async API, I see no good way of fixing this unless we can start the crash reporter after the window has opened, which I think is not an option?

//cc @jrieken

**Comment by bpasero** [comment]
Hm, maybe this is a red herring: we do start the crash reporter before the `ready` event is fired. That makes it somewhat hard to know:
* is the crash reporter basically blocking the `ready` event from firing
* or is the `ready` event not impacted by the crash reporter and we are basically having some free time to do stuff without impacting startup perf?

**Comment by jrieken** [comment]
I believe this is much worst than we initially though, esp. on mac. For that, even the 50th percentile is close to half a second. p90 is bad on windows and really bad on mac, only linux seems to be fine.

<img width="606" alt="Screen Shot 2021-06-30 at 14 26 14" src="https://user-images.githubusercontent.com/1794099/123960047-23ea6480-d9af-11eb-8e4e-e37fb18799d0.png">

I would suggest to understand why it is so slow and/or disable the crash reporter by default. Today we are paying a very high price for it being always on

**Comment by bpasero** [comment]
I added it as topic to discuss for our next Electron sync 👍

**Comment by bpasero** [comment]
I think I had asked this before: is it a design limitation of the crash handlers that we cannot start the crash reporter after the window has opened? It would be great if the crash reporter could observe existing processes after they have been created instead of requiring it to be started first.

**Comment by deepak1556** [comment]
It is a design limitation from crashpad. For ex: the mach port created on macOS is only done once and registered on the main process, this is because the OS will take care of inheriting this port to all child processes spawned from it, thereby making it easier for the crashpad handler to monitor all processes without additional effort. Starting the crash reporter in a later stage would not work with this modal to monitor existing processes.

**Comment by jrieken** [comment]
Given it has such negative impact on users we consider to

* have it off by default
* only enable it for X% of our users (flip a coin on startup)
* allow user to enable/disable it

**Comment by bpasero** [comment]
Maybe one idea is to have it only enabled for our insider users? That is still an OK number of users (>30k?) and would still give us a chance to see a trend of crashes over time.

**Comment by bpasero** [comment]
I wonder if https://github.com/electron/electron/pull/34609 has addressed this.

**Comment by bpasero** [comment]
The author states that there is even more room for improvement but the second PR is pending: https://chromium-review.googlesource.com/c/crashpad/crashpad/+/3711503

**Comment by bpasero** [comment]
Comparing stable to insiders on my machine:
<img width="634" alt="insiders" src="https://user-images.githubusercontent.com/900690/185731372-034d3c96-71ed-4476-8cc2-cdefa95b72e7.png">
<img width="722" alt="stable" src="https://user-images.githubusercontent.com/900690/185731376-855a6bee-52dd-4d4e-a9f1-807328945ac5.png">

**Comment by bpasero** [comment]
Anyway, this is still somewhat slow on Windows, and `50ms` probably translates to more than `100ms` on our perf bot, so worthwhile investigating further here.

**Comment by jrieken** [comment]
> Comparing stable to insiders on my machine:

Is that windows or mac?

**Comment by bpasero** [comment]
Yeah I updated the comment: it was macOS and the perf gains are macOS only unfortunately.

**Comment by bpasero** [comment]
Disabling crash reporter on Windows seems to bring a `30-50ms` gain on perf bot (tried with a special exploration build with disabled crash reporter).

**Comment by jrieken** [comment]
@bpasero Can you check locally? E.g does that build run faster on your machine too?

**Comment by bpasero** [comment]
@jrieken it is actually more significant on my machine, `80-100ms`. It is easy to compare when you pass in `--disable-crash-reporter` which will disable crash reporter. And then in the perf editor we actually print out the duration:

![image](https://user-images.githubusercontent.com/900690/187199623-b0b833d5-1063-4dad-b8a8-5ca1bada1573.png)

**Comment by bpasero** [comment]
👍 , one thing to note is that crash reporter starts before `app.on("ready")` and thus races with that event, so it is possible that the main process is actually somewhat idle only busy with the crash reporter while other processes in Chromium get ready. That could explain why disabling the crash reporter is not giving us back more time than those `30ms`.

**Comment by deepak1556** [comment]
There have been improvements with crashpad launching times in upstream https://github.com/electron/electron/pull/34609, closing as we don't plan to disable crash reporter and investigating other areas in startup for perf gains.
