### ISSUE TITLE
Formatting jsx file adds and removes meaningful spaces

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#12092]
- VSCode Version: 1.5.2
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Open .jsx file
```
import React from 'react'
class Sample extends React.Component {
    render() {
        return (
            <div>
                <div>Joe&apos;s Text</div>
                <div>Joe. Text.</div>
            </div>
        )
    }
}
export default Sample
```

2. Run formatting

`Joe&apos;s Text` changes to `Joe&apos; s Text` (space is added),
`Joe. Text.` changes to `Joe.Text.` (space is removed)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by waderyan** [comment]
@bpasero can you comment on the reopen? I don't believe this is an extension issue. It seems likely to be a language service issue. I'll migrate to them, once I hear from you.

**Comment by bpasero** [comment]
@waderyan yes I think so too that is why I reopened it 👍

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11010
