### ISSUE TITLE
The application “Visual Studio Code” can’t be opened on Mac Catalina

### ISSUE THREAD

**Issue by stephenmatoo** [microsoft/vscode#120924]
- VS Code Version:
- OS Version: Mac Catalina

Steps to Reproduce:

1. Download Visual studio code darwin/universal
2. Unzip using default utility 
3. Click on the app icon
4. Pop up appears with the text "The application “Visual Studio Code” can’t be opened."

I have tried redownloading it several times and it has not worked. Did a complete uninstall and tried again yet it did not work

**Comment by deepak1556** [comment]
Can you provide the output of

```
* spctl --verbose --assess --type execute --v <path-to>/Visual\ Studio\ Code.app/
* open <path-to>/Visual\ Studio\ Code.app/
```

**Comment by stephenmatoo** [comment]
spctl --verbose --assess --type execute --v /Visual\ Studio\ Code.app//Visual Studio Code.app/: invalid API object reference

open Visual Studio Code.appThe files /Applications/Visual, /Applications/Studio, and /Applications/Code.app do not exist.

**Comment by deepak1556** [comment]
> spctl --verbose --assess --type execute --v /Visual\ Studio\ Code.app//Visual Studio Code.app/: invalid API object reference
> open Visual Studio Code.appThe files /Applications/Visual, /Applications/Studio, and /Applications/Code.app do not exist.

Make sure the path to the app is correct in both the commands, for ex: 

```
spctl --verbose --assess --type execute --v Visual\ Studio\ Code.app/
open Visual\ Studio\ Code.app
```

**Comment by stephenmatoo** [comment]
spctl --verbose --assess --type execute --v Visual\ Studio\ Code.app/
Visual Studio Code.app/: cannot find code object on disk

open Visual\ Studio\ Code.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/300041360/Installers/Visual Studio Code.app.

**Comment by deepak1556** [comment]
What is the output of `codesign -dv --verbose=4 <path-to>/Visual\ Studio\ Code.app`

**Comment by stephenmatoo** [comment]
codesign -dv --verbose=4 Visual\ Studio\ Code.app/
Executable=/Users/300041360/Installers/Visual Studio Code.app/Contents/MacOS/Electron
Identifier=com.microsoft.VSCode
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=1760 flags=0x10000(runtime) hashes=46+5 location=embedded
VersionPlatform=1
VersionMin=657920
VersionSDK=720896
Hash type=sha256 size=32
CandidateCDHash sha1=5647d9ed0f5271fda9314a5b0b997edd9b3874d0
CandidateCDHashFull sha1=5647d9ed0f5271fda9314a5b0b997edd9b3874d0
CandidateCDHash sha256=12965fa7328891745a00428a0f7e5bdbe9181e17
CandidateCDHashFull sha256=12965fa7328891745a00428a0f7e5bdbe9181e17b049977f406da7695a5858f0
Hash choices=sha1,sha256
CMSDigest=590b8b4b4ebda54ed3883b2822dc134f7623350ff517eb894db73f4a1a04530a
CMSDigestType=2
Page size=4096
CDHash=12965fa7328891745a00428a0f7e5bdbe9181e17
Signature size=9061
Authority=Developer ID Application: Microsoft Corporation (UBF8T346G9)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=15-Mar-2021 at 7:13:32 PM
Info.plist entries=33
TeamIdentifier=UBF8T346G9
Runtime Version=11.0.0
Sealed Resources version=2 rules=13 files=1569
Internal requirements count=1 size=180

**Comment by stephenmatoo** [comment]
Hey the issue still persists although I have started using vs codium as an alternative to vs code
