### ISSUE TITLE
Debug console not readable because of the size of file links.

### ISSUE THREAD

**Issue by sebRomeo** [microsoft/vscode#120971]
Issue Type: <b>Bug</b>

Hi, 

In this screenshot you can easily see my problem. Links lines are too big compared to content.

![image](https://user-images.githubusercontent.com/17770809/114231663-03e07180-997b-11eb-824b-5ed0333a9f36.png)

It would be great that we can simply have an option **to disable those file links**. As you can guess they are useless to me because they always point out to the logger file, which I think is the case of many developers too.

***

<details>
<summary>Vscode and OS versions</summary>
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)  

OS version: Linux x64 5.4.0-66-generic
</details>

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 4479)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.40GB (5.88GB free)|
|Process Argv|--no-sandbox --unity-launch /home/seb/Bureau/CAWITA/dibsteur/doc|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by isidorn** [comment]
This is fixed in latest insiders. Please update to at least the latest stable
If you can still repro with https://code.visualstudio.com/insiders/ let us know and we will reopen this

**Comment by sebRomeo** [comment]
Hi, it didn't change. However I noticed the update, now the file links are not full as before but truncated with an ellipsis. But it is still unreadable

Here is the insiders screenshot

![image](https://user-images.githubusercontent.com/17770809/114390711-e4259500-9b96-11eb-85be-80c20b8117f0.png)

**Comment by isidorn** [comment]
Ok, reopening
