### ISSUE TITLE
Trusted workspaces style issues

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120946]
- The focus border around the editor is unexpected
- No padding on bottom
- Hover feedback on the trusted/untrusted folder sections is unexpected

![recording](https://user-images.githubusercontent.com/2193314/114209844-f217b380-9913-11eb-91b9-6020d628b01b.gif)

**Comment by sbatten** [comment]
The hover feedback mimics the settings editor as it is the same type of widget

**Comment by Tyriar** [comment]
It does something there though in that the gear shows up when focused. For workspace trust it seems to only be there to support keyboard navigation, so it could just not have the hover feedback since clicking essentially does nothing.
