### ISSUE TITLE
Getting Started: Allow click to toggle completion

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#120996]
I swear there have been a number of issues raised about this but I can't find them. The gist of it is that it's unclear how to explicitly toggle the completion of an item (currently, clicking the codicon, but thats not very discoverable), and it's odd that clicking an item collapses it. The solution: allow clicking an item to toggle it's completion state.

**Comment by JacksonKearl** [comment]
cc @misolori , @digitarald , @Tyriar  for input, I think this makes sense but not 100% sure.

**Comment by rzhao271** [comment]
I find it interesting how clicking the opened item toggles the round checkbox, but it means I don't have to move my mouse around as much 🙌 
I guess we'll see next iteration if people expect clicking the item to collapse it again.

**Comment by digitarald** [comment]
> I think this makes sense but not 100% sure.

It does feel very easy to close items; which I am ok with as I don't want the items to cause friction. Only concern would be UX-wise that this behavior isn't indicated at all with pointer changes.

**Comment by misolori** [comment]
I'm open to try this out. I assume we don't take the number of "checked" items into consideration for completion telemetry as opposed to performing the action?

**Comment by JacksonKearl** [comment]
There's a different event for `toggleTask` vs `runStepAction`
