### ISSUE TITLE
Notebook cell focus border issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#120986]
I really like that we have the focus border but it still bothers me that the left and right ones are so close to the edge of the editor. Since my sidebar is on the right, the left border pretty much aligns with the edge of the window. The right border is drawn over the scroll bar. It feels like it should not touch the scrollbar. I'm wondering whether 1) we should add some margin around the border, 2) experiment with a broader border.

![image](https://user-images.githubusercontent.com/4674940/114246343-3a03fe00-9947-11eb-8b8a-bf36f9ea2276.png)

**Comment by misolori** [comment]
I think this has been discussed before and I think it could make it look a little nicer, here's an example with a 20px margin all around. @rebornix @roblourens @jrieken thoughts?

![image](https://user-images.githubusercontent.com/35271042/114247860-0e831280-994b-11eb-84f7-d23c46803c8e.png)

**Comment by roblourens** [comment]
The outline under the scrollbar doesn't bother me that much. Same as the explorer

![image](https://user-images.githubusercontent.com/323878/114257900-de059d80-9977-11eb-9f38-0cf77d7dc444.png)

 but it feels like the content of the cell is moved over to make room for the scrollbar but the outer outline isn't, which is maybe inconsistent.

**Comment by misolori** [comment]
This is no longer an issue with our default:

![image](https://user-images.githubusercontent.com/35271042/133131629-ae6470ac-790f-4f4e-a588-e0aad7598022.png)

But the border does still appear when the gutter is disabled but it's also the same as our tree view so I'm closing this since we haven't heard more feedback about this
