### ISSUE TITLE
Inline Values Should be Themable

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#120936]
The inlines values colors are currently hardcoded:
https://github.com/microsoft/vscode/blob/1ed73408cd2a9229dfd67de33ccd8a3a801bdcd5/src/vs/workbench/contrib/debug/browser/debugEditorContribution.ts#L74-L88

These should be abstracted to a themable color, either its own dedicated color or one of the [Testing View Colors](https://code.visualstudio.com/api/references/theme-color#testing-view-colors), I would recommend hint or info.

**Comment by isidorn** [comment]
I agree with this.
Let's put a help wanted, sounds like a good thing to be tackled by the community.
If nobody is interested I can also look into this in the future

**Comment by isidorn** [comment]
Thanks to @nrayburn-tech this is now fixed 👏 
@JustinGrote can you maybe try this out with VS Code insiders from tomorrow and let us know how it works for you. The new color names are:
```
editor.inlineValuesBackground
editor.inlineValuesForeground
```

**Comment by JustinGrote** [comment]
Thank you, will test. Cc @TylerLeonhardt
