### ISSUE TITLE
Start Integrated Terminal in the same location as the active file

### ISSUE THREAD

**Issue by carlin-q-scott** [Microsoft/vscode#12094]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open a file
2. Open the Integrated Terminal (View > Integrated Terminal)

It should work similar to: right-click on file > Open with command prompt.

**Comment by guivho** [comment]
Here are a number of easy ways that would either open an integrated terminal in a user selected location or change the working directory of an existing integrated terminal:

1) via 2 right click menu entries in file editors:
  - new integrated terminal here
  - chdir integrated terminal here

2) same 2 menu entries in explorer right click menu

3) drag a directory from the explorer to a terminal to set its current directory

**Comment by Tyriar** [comment]
The context menu request is captured in #8132

As for dragging, I think I like iTerm's feature where it pastes the path of the file into the terminal. #11907

As for this actual feature request, you should be able to do this in an extension now through the recently introduced terminal API. In fact... I just did it! :wink: https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here you will need VS Code 1.5+ to install the extension, if you have any improvements in mind file issues over at https://github.com/Tyriar/vscode-terminal-here

**Comment by guivho** [comment]
Works fine except with paths with embedded spaces.
I have quoted the pathname to care for that case.
Created a pull request.

Guido

**Comment by carlin-q-scott** [comment]
Thanks for the rapid response guys. That was tremendously quick.
