### ISSUE TITLE
"This page isn’t working", F5 - no more choices for start debugging

### ISSUE THREAD

**Issue by ReySys** [microsoft/vscode#120947]
F5 to run any html file gives me the error "This page isn’t working" but Chrome opens directly.

Previously after F5 ask for the browser or other Enviroments.

In the upper left corner of Visual Studio Code appeared  "Launch Chrome only"

In the option below appear add another option or edit json, a json file appeared. I tried to add more browsers without solution.

I deleted all the json file content, that solved the issue and again have my F5 options.

Some finger error in somewhere, mayve the "create a launch json file" in Run and Debug.

**Comment by isidorn** [comment]
I am sorry but I am not 100% sure what you are trying to say.
Can you please paste a gif which shows the problem? Thank you
