### ISSUE TITLE
Implement VSIX drag and drop to extension viewlet

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#12090]
VSIX can now be installed via `code --install-extension extension.vsix` and via the action in the dropdown of the extension viewlet.

All that's left is the drag and drop onto the viewlet itself.

@bpasero Need your help here since the workbench seems to gobble the whole area for the drop feedback 👎

**Comment by bpasero** [comment]
@joaomoreno sure, the workbench global drop handler needed to take care of *.vsix files to show drop feedback. I took this out with https://github.com/Microsoft/vscode/commit/0619ede1e469ed23fbb214eaa0377625a402ca87 so that you should be able to do the drop yourself.

**Comment by joaomoreno** [comment]
Thanks!

**Comment by f111fei** [comment]
I can't install the extensions now by dragging it to vscode.  Hope to repair as soon as possible.
