### ISSUE TITLE
I can't run the project twice because of Arabic diacritic I used when I made my MS account

### ISSUE THREAD

**Issue by DumbestThan** [microsoft/vscode#120977]
Issue Type: <b>Bug</b>

I have a problem that whenever I try to run a project for the 2nd or third time (before ending the terminal by the rubbish icon) I got an error. It's appears that the first used the arabic diacritic when going to $PATH or something but the second didn't recognize it. I will pics and video

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.39GB free)|
|Process Argv|--crash-reporter-id f3c09210-45f3-4351-b912-f49ff1ae3fe6|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
material-icon-theme|PKi|4.6.0
java|red|0.76.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-maven|vsc|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

https://user-images.githubusercontent.com/82240394/114239613-f59c5080-998e-11eb-8b43-94c159b470bc.mp4

<img width="647" alt="Untitled" src="https://user-images.githubusercontent.com/82240394/114239640-ffbe4f00-998e-11eb-90b4-42e274f1e91d.png">

**Comment by DumbestThan** [comment]
I don't get it

**Comment by weinand** [comment]
I don't understand what you mean by "Just installed the extension and it didn't helped!"
You seem to use the Java extension and the problem you are having is related to the Java extension (and not a VS Code issue). So please file the issue against the Java extension at:  https://github.com/redhat-developer/vscode-java/issues

**Comment by DumbestThan** [comment]
Ok thanks very much
