### ISSUE TITLE
NPM tasks using the same script name from different cwd's cannot be used distinctively in WSL

### ISSUE THREAD

**Issue by piejanssens** [microsoft/vscode#120913]
- VS Code Version: 1.55.1 
- OS Version: Linux BE-PC1HY22Y 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Version: 1.55.1 (user setup)
- Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
- Date: 2021-04-07T15:06:02.360Z
- Electron: 11.3.0
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

Use VS Code in WSL. I cannot reproduce the issue when I reopen the same project window under [Windows.](url
[tasks-issue.zip](https://github.com/microsoft/vscode/files/6284717/tasks-issue.zip)
)

You can find the sample project structure attached and skip steps 1-4

1. Create the project structure

```
mkdir tasks-issue && cd tasks-issue
mkdir subfolder
npm init --yes
cd subfolder
npm init --yes
```

2. Open `/package.json` and replace the echo script with this
```
    "test": "echo \"NPM script from root\" && exit 1"
```
3. Open `/subfolder/package.json'  and change the echo text from the test script to indicate this echo comes from the subfolder package script
```
    "test": "echo \"NPM script from subfolder\" && exit 1"
```
4. Create a .vscode/tasks.json with the following contents

```json
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Start root",
      "type": "npm",
      "script": "test",
      "presentation": {
        "reveal": "always",
        "panel": "new",
        "group": "ensemble"
      }
    },
    {
      "label": "Start subfolder",
      "type": "npm",
      "script": "test",
      "path": "dummy", //uncomment path to 'fix' the issue
      "options": {
        "cwd": "${workspaceFolder}/subfolder"
      },
      "presentation": {
        "reveal": "always",
        "panel": "new",
        "group": "ensemble"
      }
    },
    {
      "label": "Run Both",
      "dependsOn": ["Start root", "Start subfolder"],
      "group": "test"
    }
  ]
}

```
5. Use global menu and select "Run Task"

Observations:
1. Task "Start subfolder" is missing
2. Run task "Run Both" and notice that it only executes "Start root"
3. Uncomment line 20 in tasks.json and notice that both issues from the observations 1 and 2 are gone

Does this issue occur when all extensions are disabled?: Yes

**Comment by piejanssens** [comment]
The bot guessed it right (impressive! - I didn't find that issue with a manual search),  #116705 seems very similar.
The author has reported it https://github.com/microsoft/vscode-npm-scripts/issues/147
He is reporting the issue on native macOS, so this might be a unix issue, not directly WSL related.

Since the npm extension is now built-in, I hope my issue doesn't get closed and banned to report it in the extension vscode-npm-scripts as there is not much activity going on if I look at the open issues and PR's...

**Comment by alexr00** [comment]
@piejanssens the `path` value for your `subfolder` task actually needs to be the path to the subfolder for the npm extension and the tasks system to be able to tell which task you're trying to configure in your `tasks.json` file.
```json
		{
			"type": "npm",
			"script": "test",
			"path": "subfolder/",
			"group": "test",
			"problemMatcher": [],
			"label": "npm: test - subfolder",
		}
```
