### ISSUE TITLE
Trust icon and status entry issues

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#120901]
![image](https://user-images.githubusercontent.com/900690/114145485-bfbb8580-9916-11eb-8ce8-5589126d8785.png)

* low contrast in status bar
* icon badge seems off

**Comment by sbatten** [comment]
The badge issue has a duplicate so ignoring that here.

**Comment by sbatten** [comment]
status bar entry is using promiment status bar entry theme colors
