### ISSUE TITLE
Cannot drag and drop onto an editor that uses webview/iframe

### ISSUE THREAD

**Issue by angusgraham** [microsoft/vscode#120973]
- VS Code Version:
1.55.0
- OS Version:
windows 1903
Steps to Reproduce:

1. Create c:\test.lua
2. Create c:\test2.lua
3. Open VSCode and close and documents
4. drag test.lua over editor pane - observe it opens
5. Close it
6. Use Help | Welcome to open Welcome page
7. drag test.lua over editor pane - observe it opens
8. Close it
9. Use Help | Release Notes to open Release Notes page
10. drag test.lua over editor pane - nothing happens - file is not opened
11. Close Release Notes
12. drag test.lua over editor pane - observe it opens
13. drag test2.lua over editor pane - observe it opens

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by diminutivesloop** [comment]
I’m happy to take a look at this. Any pointers on where to start? I did look at the latest insiders and this seems to be fixed for files dragged from the built-in explorer but it’s still broken for files dragged directly from the Finder (I’m on Mac OS).

**Comment by mjbvz** [comment]
Should be fixed by #146967 I beleive

Please test the next insiders build and let me know if this doesn't appear to work as expected
