### ISSUE TITLE
Help: Wrong terminal font

### ISSUE THREAD

**Issue by arnoldcui** [microsoft/vscode#120927]
- VS Code Version:

>1.55.1
08a217c4d27a02a5bcde898fd7981bda5b49391b
x64

- OS Version:
> ubuntu20.04

Steps to Reproduce:

1. install zsh,oh my zsh,use `ZSH_THEME="agnoster"`
2. install powerline fonts

![Screenshot from 2021-04-09 20-10-02](https://user-images.githubusercontent.com/40977489/114177956-9bd85e00-996f-11eb-9119-f5a42064e633.png)

The font in vscode terminal seem not right.
If i change any setting of `terminal.integrated`, it will show right

![Screenshot from 2021-04-09 20-12-19](https://user-images.githubusercontent.com/40977489/114178171-ece85200-996f-11eb-9440-8127ea1b8795.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Incorrect render of powerless ne glyphs is duplicate of #120129
Are you describing this problem? 

Please check if it's still reproducible in Insiders build https://code.visualstudio.com/insiders/

**Comment by arnoldcui** [comment]
> Incorrect render of powerless ne glyphs is duplicate of #120129
> Are you describing this problem?
> 
> Please check if it's still reproducible in Insiders build https://code.visualstudio.com/insiders/

yes,Thank you.
