### ISSUE TITLE
Markdown preview is not working

### ISSUE THREAD

**Issue by laujan** [microsoft/vscode#120982]
Issue Type: <b>Bug</b>

1. I have the latest version of vsc and the docs authoring pack
2. I'm working on an includes markdown file
3. I can open the file
4. When I use alt-m or ctrl kv a blank preview window opens. 
5. I restarted my pc, uninstalled/reinstalled the doc pack, and the entire vsc program
6. still getting a blank preview.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.85GB free)|
|Process Argv|--crash-reporter-id ac44cd64-7910-472f-a9cc-cc9296a64012|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
vscode-languagetool|ada|3.8.0
birdseye-vscode|alm|0.0.6
armview|ben|0.4.5
LinkCheckMD|bla|0.3.1
vs-code-semicolon-insertion|chr|0.0.6
vscode-markdownlint|Dav|0.40.1
docs-article-templates|doc|0.2.11
docs-authoring-pack|doc|0.1.13
docs-build|doc|0.3.4
docs-images|doc|0.0.9
docs-linting|doc|0.0.7
docs-markdown|doc|0.2.85
docs-metadata|doc|1.0.6
docs-preview|doc|0.3.57
docs-scaffolding|doc|0.0.6
docs-yaml|doc|0.2.6
prettier-vscode|esb|6.3.2
auto-close-tag|for|0.5.10
go|gol|0.24.0
markdown-shortcuts|mdi|0.12.0
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.11.0
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.5.702919634
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
vscode-node-azure-pack|ms-|0.1.0
azurerm-vscode-tools|msa|0.15.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
printcode|nob|3.0.0
java|red|0.76.0
vscode-yaml|red|0.17.0
markdown-preview-enhanced|shd|0.5.17
sonarlint-vscode|Son|1.21.0
code-spell-checker|str|1.10.2
ms-teams-vscode-extension|Tea|1.2.2
python|tht|0.2.3
indent-one-space|use|0.2.6
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833:30267464
vshan820cf:30276953
vscus158cf:30286554

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo

**Comment by laujan** [comment]
Hello @mjbvz. Yes, I have the latest VS Code insides build and all extensions except Doc authoring packet disabled. I am still unable to see the markdown preview.

**Comment by mjbvz** [comment]
Yes, please file an issue against whatever extension is causing this

You can use [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to help with this
