### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by SevKos** [microsoft/vscode#120944]
Issue Type: <b>Performance Issue</b>

As soon as I start Visual Studio Code my system slows down extremely. Task Manager shows 98% RAM usage. Situation improves very slightly when I close internet browser.
The problem disappears once I uninstall Visual Studio Code.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4014)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (19.44GB free)|
|Process Argv|--crash-reporter-id 2a2b302b-8307-4662-b1ee-b98446c9297e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
undefined
```

</details>
<details>
<summary>Workspace Info</summary>

```
undefined;
```

</details>
<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-html-css|ecm|1.10.2
auto-rename-tag|for|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by connor4312** [comment]
Please collect information using these instructions: https://github.com/microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code

**Comment by SevKos** [comment]
Version:          Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04
-07T15:06:02.360Z)
OS Version:       Windows_NT x64 6.3.9600
CPUs:             AMD FX(tm)-8350 Eight-Core Processor            (8 x 4014)
Memory (System):  31.90GB (23.61GB free)
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id 2a2b302b-8307-4662-b1ee-b98446c9297e
GPU Status:       2d_canvas:                  enabled
                  gpu_compositing:            enabled
                  multiple_raster_threads:    enabled_on
                  oop_rasterization:          enabled
                  opengl:                     enabled_on
                  protected_video_decode:     unavailable_off
                  rasterization:              enabled
                  skia_renderer:              enabled_on
                  video_decode:               enabled
                  vulkan:                     disabled_off
                  webgl:                      enabled
                  webgl2:                     enabled

CPU %   Mem MB     PID  Process
    2       67    7096  code main
    0       10    5372     crashpad-handler
    0       55    5912     shared-process
    0       25    3344       ptyHost
    2       24    7216     utility
    0       60    8376     gpu-process
    0      135    9408     window (styles.css - Learning - Visual Studio Code)
    0       90    6760       extensionHost
    0       22     204         electron_node serverMain.js
    0        3    8832         "C:\Program Files (x86)\Git\cmd\git.exe" --versio
n
    0        4    6992           console-window-host (Windows internal process)
    0        3    9404           git.exe --version
    0        3    9120             git.exe --version
    0        3    9452               git.exe --version
    0        3    8904                 git.exe --version
    0        3    7092                   git.exe --version
    0        3    5724                     git.exe --version
    0        3    9716                       git.exe --version
    0       27    8860         "C:\Users\Seweryn\AppData\Local\Programs\Microsof
t VS Code\Code.exe" "c:\Users\Seweryn\AppData\Local\Programs\Microsoft VS Code\r
esources\app\extensions\css-language-features\server\dist\node\cssServerMain" --
node-ipc --clientProcessId=6760
    0        9    7616       watcherService
    0        4    9712         console-window-host (Windows internal process)

Workspace Stats:
|  Window (styles.css - Learning - Visual Studio Code)
|    Folder (Learning): 1767 files
|      File types: svg(1619) less(32) scss(32) css(16) js(15) eot(4) ttf(4)
|                  woff(4) woff2(4) yml(4)
|      Conf files: settings.json(1)


There are lots of files in the workspace they do not seem to be the problem because deleting them all did not improve the situation. Memory usage keeps going up until the system stops responding even after I close the Visual Studio Code.

The same thing happens when I try to use Atom. The system enters an endless loop of starting background processes for "Git for Windows".

Is Git the problem here?

**Comment by connor4312** [comment]
Possibly, in what you showed VS Code looks to be using <300MB of memory

**Comment by SevKos** [comment]
Yes. Uninstalling Git solved the problem. Everything works fine now, even after reinstalling Git. Thanks for support.
