### ISSUE TITLE
git.autorefresh user setting being overridden by default workspace setting

### ISSUE THREAD

**Issue by bdharrington7** [microsoft/vscode#120953]
Issue Type: <b>Bug</b>

This started happening on a recent update of VSCode, where git autofetch was triggering (I get prompted for credentials on every check), despite the git.autorefresh setting being disabled in User settings. When I view the workspace settings, git.autofetch is enabled (by default), so when I disable it, the `.vscode/settings.json` file is modified with the key `git.autorefresh: false`

If the User setting is set, and the workspace setting is *not* set (even if the default is "enabled"), shouldn't the feature be disabled unless the feature is explicitly enabled in the workspace settings (I understand workspace settings override user settings)? 

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.4.0
vscode-css-formatter|aes|1.0.1
vscode-intelephense-client|bme|1.6.3
vscode-postgres|cko|1.1.17
vscode-eslint|dba|2.1.19
xml|Dot|2.5.1
gitlens|eam|11.4.0
EditorConfig|Edi|0.16.4
php-debug|fel|1.14.12
vscode-sql-tagged-template-literals|fri|0.0.18
vscode-sql-tagged-template-literals-syntax-only|fri|0.0.19
MagicPython|mag|1.1.0
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vscode-js-profile-flame|ms-|0.0.14
debugger-for-chrome|msj|4.12.12
gremlins|nho|0.26.0
show-offset|ram|0.0.4
vscode-yaml|red|0.17.0
code-settings-sync|Sha|3.4.3
change-case|wma|1.0.0

</details>

**Comment by bdharrington7** [comment]
Not a duplicate of the referenced issue

**Comment by sandy081** [comment]
It seems you have enabled `git.autofetch` in workspace settings - I do not think it is default as the default is disabled. 

> If the User setting is set, and the workspace setting is not set (even if the default is "enabled"), shouldn't the feature be disabled unless the feature is explicitly enabled in the workspace settings (I understand workspace settings override user settings)?

Yes that's correct. I suspect in your case the workspace has the value set to true (enabled). Please check and confirm - also check by opening the underlying json file .
