### ISSUE TITLE
Source control view shows progress on each keystroke

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#120930]
* todays insiders
* open TS file, open SCM view
* type in the file, SCM view updates
* continue typing and notice that each keystroke triggers an update

https://user-images.githubusercontent.com/1794099/114181523-e642e600-9941-11eb-891c-1dd194018345.mov

**Comment by jrieken** [comment]
@alexr00 adding you because this is in a branch for which a PR exists (`joh/kernel-push`)

**Comment by eamodio** [comment]
@jrieken can you still reproduce this?

**Comment by jrieken** [comment]
yes

**Comment by alexr00** [comment]
This happens even when GHPRI is not enabled.

**Comment by lszomoru** [comment]
Closing this issue as the original issue seems to have been resolved.
There is a new regression that has a similar end result but different cause - https://github.com/microsoft/vscode/issues/137870
