### ISSUE TITLE
Remote user not able to edit the code

### ISSUE THREAD

**Issue by s1234ri** [microsoft/vscode#120942]
Issue Type: <b>Bug</b>

Hi,

Visual studio code edit option is not available to the remote user. Is there any way to fix this?
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.18363

**Comment by IllusionMH** [comment]
/needsMoreInfo

Are you using Live Share extension?
Then you should not create Read-only sessions: https://docs.microsoft.com/en-us/visualstudio/liveshare/quickstart/share#6-optional-enable-read-only-mode

Or provide more details about what do you mean under "remote user" if it's not about Live Share.
