### ISSUE TITLE
Fix clipboard permissions requests in iframe based webviews

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#120978]
Luna Paint's paste command also breaks probably because of this.

_Originally posted by @Tyriar in https://github.com/microsoft/vscode/issues/118181#issuecomment-816972240_

**Comment by mjbvz** [comment]
See #115925 for original report

**Comment by mjbvz** [comment]
@Tyriar Please test out the next insiders build and let me know if this still doesn't work

**Comment by Tyriar** [comment]
It's working again, thanks!
