### ISSUE TITLE
No syntax highlighting in XML

### ISSUE THREAD

**Issue by sitefinitysteve** [Microsoft/vscode#1209]
On both Win10 and OSX my XML is not syntax highlighted at all.  If I swap the language over to HTML it looks fine, but this is a NativeScript .xml document, not an html page.

![image](https://cloud.githubusercontent.com/assets/1542376/11754298/5bf049a2-a018-11e5-8c32-717d40a9ec4b.png)

Thoughts?

**Comment by Tyriar** [comment]
Dupe of https://github.com/Microsoft/vscode/issues/23, this should be fixed in the next version.

**Comment by egamma** [comment]
@Tyriar thanks.
Closing as a dupe of #23
