### ISSUE TITLE
Disable icons on cell toolbar other than hiding to avoid flickering

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#120972]
https://user-images.githubusercontent.com/876920/114232039-20a38780-9930-11eb-95a9-dc9286cfcf8c.mov

**Comment by rebornix** [comment]
I updated the behavior of Split Cell Action to support splitting at the begin and end of the model then it is always visible on the toolbar.

**Comment by roblourens** [comment]
I don't think there's anything remaining to do then?
