### ISSUE TITLE
The old VS Code icon is back on macOS Big Sur with version 1.55.1

### ISSUE THREAD

**Issue by eiskalteschatten** [microsoft/vscode#121002]
Version 1.55 brought a new icon for macOS Big Sur that fit in with the style of icons that Apple introduced. With 1.55.1, however, the old icon is back in the Dock and About dialog, although the new icon shows up in the Finder:

<img width="1920" alt="Screenshot 2021-04-10 at 09 45 09" src="https://user-images.githubusercontent.com/3677693/114262675-8d2a8f00-99e1-11eb-8b6e-2aa34473f673.png">
<img width="377" alt="Screenshot 2021-04-10 at 09 45 22" src="https://user-images.githubusercontent.com/3677693/114262677-91ef4300-99e1-11eb-9d60-c02ba6d06090.png">

- VS Code Version: 1.55.1
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Upgrade from 1.55 and let VS Code automatically relaunch.
2. Close VS Code.
3. Open VS Code again.
4. The icon in the dock is the old one.

Does this issue occur when all extensions are disabled?: Yes

**Comment by eiskalteschatten** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Old VS Code Icons (#116547)](https://www.github.com/microsoft/vscode/issues/116547)
> * [Option to use old VS Code icon (#120612)](https://www.github.com/microsoft/vscode/issues/120612)

Nope, those don't cover it.

**Comment by eiskalteschatten** [comment]
**Update**

This seems to be an issue on Retina displays. The screenshots above were taken on my MacBook's internal Retina display. As soon as I plugged it into my external screen though, the new icon showed up.

![Screenshot 2021-04-10 at 10 44 09](https://user-images.githubusercontent.com/3677693/114264201-dda5ea80-99e9-11eb-8604-9b5ab04420d1.png)

I can consistently reproduce this by unplugging and plugging in my external monitor.

**Comment by deltamualpha** [comment]
Same, it reverted for me as well. Icon management on MacOS appears to be surprisingly complex!

**Comment by jirsbek** [comment]
I've been having the same issue with the icon since 1.55 update on macOS Big Sur. What helps me is clearing the icon cache as suggested here https://github.com/microsoft/vscode/issues/101014#issuecomment-808368475
```
sudo touch /Applications/Visual\ Studio\ Code.app;
sudo touch /Applications/Visual\ Studio\ Code.app/Contents/Info.plist;
sudo touch /Applications/Visual\ Studio\ Code.app/Contents/Resources/Code.icns;
killall Dock Finder
```

**Comment by misolori** [comment]
@eiskalteschatten please try [clearing your icon cache](https://github.com/microsoft/vscode/issues/101014#issuecomment-808368475) to see if this fixes it. Feel free to open a new issue if other things come up.

**Comment by eiskalteschatten** [comment]
Clearing the cache did solve the problem. 👍🏻  Thank you!
