### ISSUE TITLE
VS Code cannot start without internet

### ISSUE THREAD

**Issue by bleakley** [microsoft/vscode#121018]
- VS Code Version: 1.55.1
- OS Version: Windows 10

Steps to Reproduce:

1. When internet is on, VS Code detects an update.
2. Internet is turned off.
3. VScode is turned off.
4. Attempt to start VScode.
```
bleakley@LAPTOP-D2RUJG43:~$ code .
Updating VS Code Server to version 08a217c4d27a02a5bcde898fd7981bda5b49391b
Removing previous installation...
Installing VS Code Server for x64 (08a217c4d27a02a5bcde898fd7981bda5b49391b)
Downloading: 100%
Failed
--2021-04-10 10:29:11--  https://update.code.visualstudio.com/commit:08a217c4d27a02a5bcde898fd7981bda5b49391b/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘update.code.visualstudio.com’
ERROR: Failed to download https://update.code.visualstudio.com/commit:08a217c4d27a02a5bcde898fd7981bda5b49391b/server-linux-x64/stable to /home/bleakley/.vscode-server/bin/08a217c4d27a02a5bcde898fd7981bda5b49391b-1618072141.tar.gz
```
5. Try to start it without updating, realize you don't know what, if any, command line flag will launch it without updating.
6. Try `code . --help`
7. Realize you can't even view the view available options because you can't start it without updating.
8. Realize you can't google how to start it because the internet is disconnected.

This is 100% unambiguously a bug. I'm aware it's possible to disable this behavior within VS Code. The user needs to be able to disable this on the command line, and the user needs to be able to view the help on the command line whether or not the internet is available.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by joaomoreno** [comment]
How did you install VS Code?

**Comment by bleakley** [comment]
It was originally installed with the VSCodeUserSetup-x64-1.46.1.exe download from the website. I'm running it with WSL 2 on Windows 10.

**Comment by joaomoreno** [comment]
Oh now I get it. Yes, it's correct: VS Code doesn't ship with VS Code Server, the latter needs to be downloaded from the internet. This needs to happen only the very first time you start VS Code after an update and connect to a WSL environment, in the case of WSL. Successive launches of the same VS Code version won't require being online.
