### ISSUE TITLE
Native Notebooks - Undo 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121056]
https://github.com/microsoft/vscode-jupyter/issues/5441
- VS Code Version: 1.56.0-insider
- OS Version: WIndows

### Steps to Reproduce:

1. Create new notebook 
2. Add something in first cell
3. Add something in second cell
4. Add something in first cell again
5. Put focus back on editor in second cell
6. Undo

### Actual Behavior: 
![VSC Undo](https://user-images.githubusercontent.com/19276747/114315462-f8449600-9ab3-11eb-84ff-9fbe1d670cb8.gif)

### Expected Behavior: 
Undo at the cell level
![Jupyter Undo](https://user-images.githubusercontent.com/19276747/114315548-49548a00-9ab4-11eb-9b1e-5a262f879e70.gif)

**Comment by claudiaregio** [comment]
Looks like dupe of https://github.com/microsoft/vscode/issues/121041?

**Comment by rebornix** [comment]
@claudiaregio yes, they are the same. This is how current undo/redo implemented in notebook, notebook document and cells share the same undo/redo history stack.

**Comment by Syndorik** [comment]
Hi, as mentionned in [vscode-jupyter/5441](https://github.com/microsoft/vscode-jupyter/issues/5441), I think it woud great to have an undo per cell basis as it exists in jupyter notebook (when in edit mode)

**Comment by DonJayamanne** [comment]
I too have struggled at times with info, then again I don't have suggestions to improve this (never looked into this). It's a tough one.

**Comment by rebornix** [comment]
technically we can support this and maybe we can have an experimental setting for ppl to try out to see which one makes more sense.

**Comment by claudiaregio** [comment]
+1 customer feedback

![image](https://user-images.githubusercontent.com/19276747/117400780-3026d980-aeb8-11eb-81d0-f1ea190a93f7.png)

**Comment by samialsindi** [comment]
+1
Please allow us to configure/change this.
The fact that the focus does not change to the cursor makes this behaviour useless (what cell is it undoing stuff from?)
Let alone the difference between previous VSCode versions and Jupyter itself.
I rely a LOT on local undo (at a cell level) almost to the point that I might have to abandon VSCode for notebooks, I would really hate to do this as I have loved using a holistic solution!

I was about to post a ticket with my issue, but here's the text:

'Hi, I used to rely heavily on the 'local' undo, i.e. Cmd+Z works specifically within a given JupyterNotebook cell.
Unfortunately, a recent update to VSCode appears to have changed it to a 'global' undo, i.e. Cmd+Z undoes changes across the whole notebook.
As one jumps around in editing notebooks this isn't very helpful.

I just wanted to ask if anyone else has encountered the same issue, and if it's possible to fix/change?

Thanks in advance.'

**Comment by rebornix** [comment]
You can set `"notebook.experimental.undoRedoPerCell": true` in your settings to disable this feature, let's see how it works and revisit if we should make it the default behavior.

**Comment by samialsindi** [comment]
@rebornix Where do I add this?
I've updated to the latest update and it says 'setting not found' when I add it to the settings.json, but there appear to be a few places it could be added

**Comment by claudiaregio** [comment]
@rebornix I added this setting to mine too but it did not work for me :(

**Comment by claudiaregio** [comment]
![image](https://user-images.githubusercontent.com/19276747/120114640-f488d380-c134-11eb-8f79-ffb81eafe8b9.png)

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124499262-958d2e80-dd72-11eb-892a-f9a244955e7e.png)

**Comment by claudiaregio** [comment]
+1
![image](https://user-images.githubusercontent.com/19276747/124816575-84345580-df1d-11eb-8050-b2db7626f53a.png)

**Comment by claudiaregio** [comment]
Potential +1
![image](https://user-images.githubusercontent.com/19276747/124816698-a7f79b80-df1d-11eb-886c-0775917a6d8d.png)
