### ISSUE TITLE
WebGL renderer doesn't support ANSI underline/underscore

### ISSUE THREAD

**Issue by frankli0324** [microsoft/vscode#121023]
- VS Code Version: 1.55.1(08a217c4)
- OS Version: MacOS 11.2.3 < this existed long before I upgraded MacOS

sorry in advance for not going through the entire previous discussions, but the issue still seems to exists for me.

Steps to Reproduce:

NOTE THAT the "underscore" I'm referring to is not the character "_" but the escape character `echo -e "\e[4munderline\e[0m"`

![image](https://imgur.com/2fFMPOf.gif)

maybe related: 

#35901
#46900
#84440

Does this issue occur when all extensions are disabled?: Yes

**Comment by frankli0324** [comment]
any info on this plz?

**Comment by frankli0324** [comment]
please?

**Comment by Tyriar** [comment]
Underscore is one of the only things that the webgl renderer doesn't support over the others, this is tracked in https://github.com/xtermjs/xterm.js/issues/2251

You can revert to the slower DOM-based implementation with this setting to workaround the rendering problem until that's implemented:

```
"terminal.integrated.gpuAcceleration": "off"
```

**Comment by frankli0324** [comment]
thanks for pointing the way

**Comment by Tyriar** [comment]
This is done, merging this issue into https://github.com/microsoft/vscode/issues/128321
