### ISSUE TITLE
Syntax highlighting not working right.

### ISSUE THREAD

**Issue by ZCG-coder** [microsoft/vscode#121067]
The syntax highlighting feature does not highlight my code properly, it looks like this:
<img width="1062" alt="bug" src="https://user-images.githubusercontent.com/76037593/114344782-04535500-9b93-11eb-9d03-7a8f05007691.png">
Please fix this.

**Comment by gjsjohnmurray** [comment]
pinging @alexr00 for Python syntax

**Comment by alexr00** [comment]
@ZCG-coder can you please share a copy/pastable sample that I can use to reproduce this issue?

**Comment by ZCG-coder** [comment]
Sure! Here it is:
```
def _open(self, _=None) -> None:
        """Prompt the user to open a file when C-O is pressed"""
        self.open_file()

    def save_as(self, file: str = None) -> None:
        """Save the document as a different name."""
        if self.tabs:
            if file:
                file_dir = file
            else:
                FileSaveAsDialog(self.save_as)
                return
            curr_tab = self.get_tab()
            if not file_dir:
                return

            self.tabs[curr_tab].file_dir = file_dir
            self.nb.tab(curr_tab, text=os.path.basename(file_dir))
            with open(file_dir, "w") as f:
                f.write(self.tabs[curr_tab].textbox.get(1.0, "end"))
            self.update_title()
            self.reload()

    def _saveas(self, _=None):
        self.save_as()
```

**Comment by alexr00** [comment]
Thanks for the sample. I don't usually use python, so maybe I'm missing something, but it looks ok to me:

![image](https://user-images.githubusercontent.com/38270282/114715414-56cb7780-9d33-11eb-9ce1-3ff0d74e3dd8.png)

What version of VS Code are you using? Do you have any extension installed that may be causing this?

**Comment by ZCG-coder** [comment]
I started an extension bisect, and I found out that the extension "visualstudioexptteam.vscodeintellicode" is causing this issue.
