### ISSUE TITLE
wrong color

### ISSUE THREAD

**Issue by SR-22** [microsoft/vscode#121008]
Version: 1.55.1 (user setup)
OS: Windows_NT x64 10.0.19042

VS code is giving me this wrong color. I am using material theme:

![image](https://user-images.githubusercontent.com/79589166/114268934-858ada80-9a21-11eb-8705-d0534bca3f47.png)

whereas it should be this:

![image](https://user-images.githubusercontent.com/79589166/114268943-976c7d80-9a21-11eb-864b-b69b0e1fe5b7.png)

Kindly advice 

Does this issue occur when all extensions are disabled?: Yes

**Comment by SR-22** [comment]
hello @aeschli can you please help me with the issue?

**Comment by aeschli** [comment]
What exactly is wrong?

**Comment by SR-22** [comment]
it is showing wrong color lol
