### ISSUE TITLE
Blank lines should not be deleted in column selection mode

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#121013]
- VS Code Version: Version 1.56.0-insider
- OS Version: Window_NT x64 10.0.19042

Steps to Reproduce:
Edit the following with Visual Studio Code, Electron 11.4.2 or earlier.  Instructions are in the following.

//This is line 1.  Line 2 is blank since it only has a newline in column 1.

//This is line 3.  Click the cursor immediately before '//This' on line 1.

//This is line 5.  Shift-Alt-Click just after '//This' on line 7.

//This is line 7.  Hit 'Delete'.  How many lines are there now?  There should be 7.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mrmsbarnes** [comment]
Version 1.56.0-insider
Window_NT x64 10.0.19042

**Comment by mrmsbarnes** [comment]
Compare when lines 2, 4, and 6 have a single space character before the newline.

**Comment by alexdima** [comment]
Let's track in #115559
