### ISSUE TITLE
"In the event of a conflict with untrusted folders, the nearest parent will determine trust." not needed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121092]
The workspace trust is a new concept to the user, thus I think we want to keep the UI as simple as possible so the user can read up on the important information and not be worrying about the wrong things.
Due to that I suggest to remove the 
"In the event of a conflict with untrusted folders, the nearest parent will determine trust."

There are two places where we mention this. I think this is an advanced feature which can be shown either on hover, or when the user has at least 2 or more items add to the Trusted / Untrusted folders list

**Comment by sbatten** [comment]
With the removal of unspecified, we probably won't have an "untrusted" list anymore so this will also be no longer an issue

**Comment by isidorn** [comment]
Just to be sure we are on the same page here, I am talking about this text here.
I do not understand how the removal of "unpecified" will help here?

![Screenshot 2021-04-12 at 17 45 50](https://user-images.githubusercontent.com/1926584/114422893-f4e60300-9bb6-11eb-81b9-92c3b30a2bb8.png)

**Comment by sbatten** [comment]
Yes but there will be no "conflict with untrusted" to mention because there will only be one list

**Comment by isidorn** [comment]
Yes, makes sense. Thanks
