### ISSUE TITLE
Terminal prompt is skewed when using DankMono font and powerline10k 

### ISSUE THREAD

**Issue by gil-upstream** [microsoft/vscode#121037]
Issue Type: Bug

1. Open terminal with dank mono font and powerline10k prompt
2. Prompt apperears not straight and skewed as follows in the image

VS Code version: Code 1.55.1 (Universal) (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 [20.3.0](url
<img width="1552" alt="Screen Shot 2021-04-11 at 9 24 00" src="https://user-images.githubusercontent.com/67628584/114294584-684d1f00-9aa8-11eb-9926-5000945e2c88.png">
)

**Comment by IllusionMH** [comment]
Looks like duplicate of #120129

Please check if it's still reproducible in Insiders build https://code.visualstudio.com/insiders/

**Comment by gil-upstream** [comment]
It is indeed fixed in Code-Insiders. Thanks.
