### ISSUE TITLE
"Trust required for features" not needed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121096]
I do not understand why we render "Trust required for features" list of extensions. Isn't this the sort of default? Why would the user be interested if an extension wants workspace trust for some feature.

Showing the other list makes good sense, since those extension will be Disalbed and the user will be puzzled why the extensions are not working.
Showing just one list here will hopefully reduce the complexity of the view and reduce the duplication in the titles.

![Screenshot 2021-04-12 at 15 24 36](https://user-images.githubusercontent.com/1926584/114401525-4b494680-9ba3-11eb-8063-b0d205f3ee32.png)

**Comment by lszomoru** [comment]
The second list "trust required for features" (I think we can improve the title), is the list of extensions that are enabled but have limited functionality as some of their features (ex: use workspace version of TypeScript) require workspace trust before they can be executed.

**Comment by isidorn** [comment]
Yeah I understood that part. My point is why would the user ever want to know a list of extensions that require workspace trust before some feature.

**Comment by sbatten** [comment]
As a result of last week's discussions, we imagine that a majority of extensions that require trust will use a silent notification (the badge). 

In that flow a user sees a badge > clicks the gear > "Manage Workspace Trust (1)" > In the editor clicks the link to show limited extensions

They now need to see this list to understand what cares

Concrete example of this would be Prettier asking if it should use the workspace version or a bundled version of prettier

**Comment by sbatten** [comment]
This issue is out of date, the titles have been updated and I believe the current view makes it clearer what is happening than merging the lists.
