### ISSUE TITLE
A way to disable vscode debugging logs

### ISSUE THREAD

**Issue by withmask** [microsoft/vscode#121053]
When using the debug option with external terminal such logs appear: "Debugger attached." "Waiting for the debugger to disconnect..." which polute the logs and doesn't deal well with clusters specially when the master process fails or has an error.

**Comment by weinand** [comment]
I think these messages come from node.js and not VS Code (or js-debug).
So I don't think that we can do anything here.

But @connor4312 can give you the definitive answer.

**Comment by connor4312** [comment]
This is not possible to disable -- please file an issue for Node.js if you'd like to see this https://github.com/nodejs/node
