### ISSUE TITLE
Add setting editor.scrollCursorWithLine

### ISSUE THREAD

**Issue by Bill-Stewart** [microsoft/vscode#12106]
https://github.com/Microsoft/vscode/pull/1051 mentioned this setting. Where did it go?

---

Additionally, the setting "editor.scrollCursorWithLine" was added (defaults to false). When set to true, the caret will be moved up/down along with scrolling. This feature makes it possible for the user to scroll in a document by using keyboard shortcuts while keeping the same number of visible lines before and after the cursor.

**Comment by alexandrudima** [comment]
Looking through history, this is what I found: 965138ff61428be96d3779cbbcec3ac8291e0884 . I'm sorry I don't remember the details, we have daily standups where we discuss all that goes on, and the feedback from the team lead me to remove the setting. I'm sorry I didn't capture the exact discussion in any meaningful way.

**Comment by Bill-Stewart** [comment]
Thanks for checking! This option seems that it would be useful and I was wondering what happened to it (I would use it!).

**Comment by alexandrudima** [comment]
Perhaps once we add support for `args` in `keybindings.json`, this will be possible out of the box with one of the scroll commands introduced by @sandy081
