### ISSUE TITLE
Hex editor icon does not appear active like others

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121084]
See:

![image](https://user-images.githubusercontent.com/900690/114391812-3ca96200-9b98-11eb-93be-a57eb8673c50.png)

compared with e.g. explorer:

![image](https://user-images.githubusercontent.com/900690/114391831-429f4300-9b98-11eb-85c9-d61513d40aaa.png)

**Comment by lramos15** [comment]
Is there special logic that needs to be done here? I just contribute a view with an SVG icon.

**Comment by bpasero** [comment]
Ping @sandy081 @sbatten

**Comment by sandy081** [comment]
Difference is that core ones are codicons and this is not. For not codicons we set background color to give the same treatment like codicons. It works for other icons like Docker and not sure why this is not working for hex editor icon. 

@misolori Insights ?

**Comment by misolori** [comment]
Looking at the svg it appears there was an opacity set on the svg path:

![image](https://user-images.githubusercontent.com/35271042/115272957-d2db0c00-a0f3-11eb-9dd7-1dff1079ea87.png)

@lramos15 [looks like it was my mistake](https://github.com/microsoft/vscode-hexeditor/issues/218#issuecomment-799934826) as i gave you that svg (my bad), you can remove that part and it should work fine

**Comment by misolori** [comment]
Closing as it's not a vscode issue, @lramos15 [fixed it here](https://github.com/microsoft/vscode-hexeditor/commit/220fdc72e399b5550755afc26c1459930be60094)

**Comment by lramos15** [comment]
Thanks @misolori for the help :)!
