### ISSUE TITLE
"Do you trust the files in this folder" dialog feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121097]
Can we put the two paragraphs from this dialog into one. To me it feels like they are repetitive?

"A feature you are trying to use may be a security risk if you do not trust the source of the files or folders you currently have open.

You should only trust this workspace if you trust its source. Otherwise, features will be enabled that may compromise your device or personal information."

->

"You should only trust this workspace if you trust its source. Otherwise, features will be enabled that may compromise your device or personal information."

Especially since the "A feature you are.." might not be true, since the dialog appears for me when I click "enable for workspace" and not when I use a particular feature.

Also the Learn More button has no effect for me when I press it

![Screenshot 2021-04-12 at 15 29 00](https://user-images.githubusercontent.com/1926584/114402155-d88c9b00-9ba3-11eb-96f3-628b987e3dd2.png)

**Comment by sbatten** [comment]
> Especially since the "A feature you are.." might not be true, since the dialog appears for me when I click "enable for workspace" and not when I use a particular feature.

I would argue that enabling an extension is a feature.

Learn more should take you to the workspace trust editor, do you already have it open?

**Comment by isidorn** [comment]
There are improvements in this dialog, thus closing this issue

![Screenshot 2021-04-15 at 17 01 10](https://user-images.githubusercontent.com/1926584/114893540-17258e00-9e0e-11eb-8313-cbb121516784.png)
