### ISSUE TITLE
Host / Path should not be rendered if there are no Paths specified

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121089]
I find it weird that we render the `Host / Path` segment if there are no entries.
I suggest to not render this if no path has been specified.

Also I suggest to not render HOST unless there is something which is not `Local`.
Most of the users will just have `Local` and we should not clutter this view for them

![Screenshot 2021-04-12 at 15 03 35](https://user-images.githubusercontent.com/1926584/114398652-52bb2080-9ba0-11eb-9a75-a8eda99b0c7c.png)

**Comment by sbatten** [comment]
Will take a look at this after moving the button out of the table widget.
