### ISSUE TITLE
Test HTML/Razor/Handlebar

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#12100]
- [x] Linux @bpasero 
- [x] MacOS @sandy081
- [x] Win @bgashler1 

Complexity 3

The HTML language has been refactored from a legacy mode to an extension. Syntax highlighting is now using TextMate grammars.

Test for all 3 languages (HTML, Razor, Handlebar)
- syntax highlighting. Note: For Razor to highlight embedded C# code, a C# extension must be installed.
- Commenting, bracket matching, indentation after brackets, autoClosingPairs, Surround with brackets. See [html/language-configuration.json] (https://github.com/Microsoft/vscode/blob/master/extensions/html/language-configuration.json) for the brackets/comments to expect
- Code assist for html tags, attributes and values.
  - Type '<' to see tag proposals
  - verify that '</' will propose to close the most inner element
  - verify that picking a '</' proposal will fix the indent
  - test that in html you see also angular and ionic proposals and that you can disable them with the settings
- Highlighting of open and close tags
- That link detection for `src` and `href` works and that the links are correctly followed.
- Test HTML formatting. Also test that changing the formatter settings has an effect. Note: we use http://jsbeautifier.org/ as formatter. Use that page to compare.

**Comment by sandy081** [comment]
@chrmarti I do have only mac machine with me right now.. Is it possible to swap this with an other TPI on Mac?

Thanks

**Comment by chrmarti** [comment]
@sandy081 swapping you with @bgashler1 on this test item.
