### ISSUE TITLE
Local file navigation via  opt+click opens index.d.ts file in react lib  after the latest upgrade

### ISSUE THREAD

**Issue by dpkshrma** [microsoft/vscode#121003]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. create a react project using create-react-app
2. create a parent and child component
3. import child component inside parent component and use it in render function
4. (opt+click) on child component usage

Expected Result:
Child component file should be opened

Current Result :
index.d.ts file in react module in node_modules folder is opened.

Similar issue might be present in other projects where typescript is being used.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:05.981Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 121d7851-959f-4441-802b-dd6be8d1efee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
increment-selection|alb|0.2.0
cucumberautocomplete|ale|2.15.1
vscode-sql-beautify|cla|0.1.29
vscode-clock|Com|0.0.1
vscode-eslint|dba|2.1.19
vscode-faker|dee|1.5.0
devschool|dpk|0.0.1
xml|Dot|2.5.1
vsc-shortid|dpk|0.0.1
insert-iso-timestamp|dpk|0.0.1
gitlens|eam|11.4.0
json-tools|eri|1.0.2
prettier-vscode|esb|6.3.2
vscode-todo-plus|fab|4.18.3
battery-indicator|fbo|1.0.0
auto-close-tag|for|0.5.10
gitignore-templates|has|1.0.1
beautify|Hoo|1.5.0
vscode-styled-components|jpo|1.5.0
vscode-sshfs|Kel|1.20.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
atom-keybindings|ms-|3.0.9
vscode-react-native|msj|1.4.1
es6-css-minify|olb|3.3.2
java|red|0.76.0
vscode-yaml|red|0.17.0
vscode-nginx|sha|0.6.0
mdx|sil|0.1.0
svg-preview|Sim|2.8.3
vscode-zipexplorer|sle|0.3.1
autoimport|ste|1.5.3
lorem-ipsum|Tyr|1.2.0
terminal-tabs|Tyr|0.2.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-nginx|wil|0.7.2
change-case|wma|1.0.0

(3 theme extensions excluded)

</details>

**Comment by ConneXNL** [comment]
Got the same issue when using Styled Components in react.
 When I ctrl-click on `<MyComponent/>` it goes to the `@types/styled-components` definition file instead of the defined component in an other file :  
const MyComponent = styled('div')``

**Comment by mjbvz** [comment]
Please share a complete code example

Also make sure to test on VS Code insiders

**Comment by kjetilhau** [comment]
I'm having the exact same issue. This happened recently, without any major changes in the code. (Or any new extensions for that matter)

**Comment by dready** [comment]
Same problem here. There is also a duplicate issue with a video in it: https://github.com/microsoft/vscode/issues/120627

**Comment by waynebloss** [comment]
Is there any way to set the functionality of what Ctrl+Click does for code navigation? I just want it to go to implementations, not definitions because going to definitions always opens up a useless `*.d.ts` file. It used to work all the time and recently it became very untrustworthy.

I just want it to do the same thing that I have set `F12` to do.

**Comment by mjbvz** [comment]
I believe this has the same root cause as #119086

It no longer reproduces for me in VS Code insiders with the example code
