### ISSUE TITLE
A project that I have developed with PHP and HTML Combined, all HTML tags are white, before I colored well the html code together with the php

### ISSUE THREAD

**Issue by jeansjave** [microsoft/vscode#121059]
Issue Type: <b>Bug</b>

Please describe the issue in 2-3 sentences. Include what you're trying to accomplish when the issue occurs.
Simply when I have PHP and HTML code combined, all the HTML tags turn white and if I change the theme, the white color persists and it does not color well.

When did it begin and how often does it occur?
Started 2 weeks ago

What errors do you see?
You do not see any error, it is only at the visualization level, I mostly occupy the topic "ayu dark", and I can't get the html tags to color, but if I open an .html file if the tags are colored well, just It happens to me when it recognizes that it is a .php file, and the htm codes are all blank and that is confusing.

What's the environment and are there recent changes?
I have tried to change the theme but nothing always shows the HTML tags in white color, being that it is a .php file

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 0e4892fa-58d2-45c3-a82a-9355a0bde5f6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (114)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
extension-path|act|0.0.3
stylus|Ala|0.0.4
project-manager|ale|12.1.0
laravel-extra-intellisense|ami|0.6.1
ACF-Snippet|ant|1.9.0
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.6.3
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
laravel-blade|cjh|1.1.2
laravel-goto-view|cod|1.3.4
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.19
wpy-beautify|doi|2.0.10
githistory|don|0.6.16
xml|Dot|2.5.1
Vue2|duc|0.1.3
gitlens|eam|11.4.0
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.19
vscode-great-icons|emm|2.1.73
prettier-vscode|esb|6.3.2
mithril-emmet|Fal|0.7.6
git-project-manager|fel|1.7.1
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
lana|Fin|1.3.5
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
svgeditor|hen|2.9.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
ftp-simple|hum|0.7.6
vscode-placeholder-images|Jak|0.1.0
vscode-wordpress-hooks|joh|0.5.4
php-cs-fixer|jun|0.1.158
prettier-php|kar|0.0.3
vscode-codemetrics|kis|1.24.0
vscode-phpfmt|kok|1.0.30
vue|liu|0.1.5
live-stylus-compiler|liv|0.0.3
vscode-JS-CSS-HTML-formatter|lon|0.2.3
twig-language-2|mbl|0.9.2
php-namespace-resolver|Meh|1.1.8
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.11.0
vscode-language-pack-es|MS-|1.55.2
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
sublime-keybindings|ms-|4.0.8
vscode-react-native|msj|1.4.1
vuejs-extension-pack|mub|1.2.1
php-html-in-string|Nic|0.1.3
vetur|oct|0.33.1
laravel-blade|one|1.25.0
laravel-extension-pack|one|1.0.0
laravel5-snippets|one|1.12.0
material-icon-theme|PKi|4.6.0
seti-icons|qin|0.1.3
java|red|0.76.0
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
format-html-in-php|rif|1.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
vscode-essentials-snippets|rob|2.0.0
sass-indented|rob|1.5.1
laravel-artisan|rya|0.0.27
vscode-format|rya|0.0.6
laravel-5-snippets|sac|2.0.1
salesforce-vscode-slds|sal|1.4.0
salesforcedx-vscode|sal|51.8.0
salesforcedx-vscode-apex|sal|51.8.0
salesforcedx-vscode-apex-debugger|sal|51.8.0
salesforcedx-vscode-apex-replay-debugger|sal|51.8.0
salesforcedx-vscode-core|sal|51.8.0
salesforcedx-vscode-lightning|sal|51.8.0
salesforcedx-vscode-lwc|sal|51.8.0
salesforcedx-vscode-visualforce|sal|51.8.0
vue-vscode-snippets|sdr|2.2.0
vscode-vue-typescript-snippets|Sha|0.0.1
markdown-preview-enhanced|shd|0.5.17
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
php-ci|sma|0.4.2
php-formatter|Sop|0.2.4
laravel-goto-controller|ste|0.0.12
language-stylus|sys|1.11.0
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
vscode-icons|vsc|11.4.0
gitblame|wad|6.0.2
quokka-vscode|Wal|1.0.354
vscode-todo-highlight|way|1.0.4
twig|wha|1.0.2
vscode-import-cost|wix|2.15.0
wordpress-toolbox|wor|1.3.9
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by jeansjave** [comment]
<img width="1917" alt="Captura de Pantalla 2021-04-11 a la(s) 15 21 25" src="https://user-images.githubusercontent.com/2192067/114318284-7caa0f80-9ada-11eb-8cd2-2052f34ad109.png">
<img width="1435" alt="Captura de Pantalla 2021-04-11 a la(s) 15 20 39" src="https://user-images.githubusercontent.com/2192067/114318289-83388700-9ada-11eb-86b2-b72eaa1a0faa.png">
<img width="1918" alt="Captura de Pantalla 2021-04-11 a la(s) 15 19 57" src="https://user-images.githubusercontent.com/2192067/114318293-87fd3b00-9ada-11eb-9b98-3fcdb8f4a02b.png">

**Comment by roblourens** [comment]
What theme is this? Does it happen with a default theme?

**Comment by jeansjave** [comment]
it happens to me with all the issues

[image: Ícono de validado por la comunidad]

**Comment by roblourens** [comment]
All the themes? Can you share the full file text or try to reduce it for me?

**Comment by jeansjave** [comment]
Te adjunto un archivo donde va el codigo de un php + html, y solo me pasa cuando uso esa combinacion, y todo el codigo HTML se me pone en blanco.
[consejos.php.zip](https://github.com/microsoft/vscode/files/6330361/consejos.php.zip)

**Comment by roblourens** [comment]
The file you shared is not the file in the screenshot and it works fine.

Please try this with a default theme and start with the flag `--disable-extensions`
