### ISSUE TITLE
Duplicated repos in SOURCE CONTROL tab

### ISSUE THREAD

**Issue by zhj0924** [microsoft/vscode#121020]
Issue Type: <b>Bug</b>

.workspace file store in one location,
folder stored in another location,
Source control showing 2 versions of same repo, one using absolute path and the other relative path.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.21354
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (12.59GB free)|
|Process Argv|--crash-reporter-id 4acc1094-1430-490d-8cdf-c6f078bf8474|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2807)|
|Memory (System)|15.58GB (4.21GB free)|
|VM|0%|
</details><details><summary>Extensions (59)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-great-icons|emm|2.1.73
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
file-icons|fil|1.0.29
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
better-cpp-syntax|jef|1.15.5
Kotlin|mat|1.7.1
theme-monokai-pro-vscode|mon|1.1.19
vscode-language-pack-zh-hans|MS-|1.55.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.6.0
shebang-snippets|rpi|0.1.4
code-settings-sync|Sha|3.4.3
rewrap|stk|1.14.0
ayu|tea|0.20.1
open-in-browser|tec|2.0.0
vscode-icons|vsc|11.4.0
vim|vsc|1.19.3
material-theme|zhu|3.10.12
doxdocgen|csc|1.1.0
githistory|don|0.6.16
gitlens|eam|11.4.0
EditorConfig|Edi|0.16.4
code-runner|for|0.11.3
vscode-pull-request-github|Git|0.25.0
todo-tree|Gru|0.0.211
vscode-test-explorer|hbe|2.19.6
better-cpp-syntax|jef|1.15.5
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.13.1
rainbow-csv|mec|1.8.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.11.0
vscode-kubernetes-tools|ms-|1.3.0
mssql|ms-|1.10.1
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.1-pre.1
jupyter|ms-|2021.5.702919634
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0-insiders5
cpptools-extension-pack|ms-|1.0.0
vscode-typescript-next|ms-|4.3.20210409
vsliveshare|ms-|1.0.4116
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.4.1
autodocstring|njp|0.5.4
vscode-yaml|red|0.17.0
cmake|twx|0.0.17
colonize|vms|2.2.2
vscode-wakatime|Wak|5.0.1
clang-format|xav|1.9.0

(19 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by zhj0924** [comment]
![image](https://user-images.githubusercontent.com/35902491/114280993-b868aa80-99f0-11eb-9813-9650089ece5d.png)
There should be 2 changes, not 4.

**Comment by eamodio** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/112231

**Comment by AnrDaemon** [comment]
Are you using Cygwin Git ?
Install window Git in a separate directory, don't add it to %PATH% and tell VS Code to use it specifically.
