### ISSUE TITLE
Integrated terminal breaks after resizing the window horizontally on Windows

### ISSUE THREAD

**Issue by chopetra** [Microsoft/vscode#12105]
- VSCode Version: 1.5.2
- OS Version: win10 

Steps to Reproduce:
1. turn on bottom console display(ctrl+`) and dotnet run 
   (~~ Application started. Press Ctrl+C to shut down....etc)
2. resizing width smaller vscode then broke console.
- before resizing 
  ![before](https://cloud.githubusercontent.com/assets/19626732/18569728/7de11ab6-7bdf-11e6-8766-81dde6327300.png)
- after resizing
  ![after](https://cloud.githubusercontent.com/assets/19626732/18569740/8fa6ae3c-7bdf-11e6-9b1b-50f851aa9fe1.jpg)

**Comment by Tyriar** [comment]
Similar to #8902 but it's likely a different issue. This issue has been around since the terminal was introduced but I don't think there is an issue tracking it yet.

**Comment by lrs** [comment]
Is there any progress on this? The same thing happens to me when resizing the sidebar rather than the whole window. Also if using powershell.

**Comment by Tyriar** [comment]
Duplicate #8336
