### ISSUE TITLE
Add path sometimes results in no action

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121095]
Workspace trust: Click on the Add Path button multiple times, notice the following:
* providing an invalid path fails with no error. A bit confusing
* Providing a valid path, nicely adds it.
* However provide a valid path again -> the element is not added to the table. It is only seen on reload

**Comment by lszomoru** [comment]
The work to add validation is being tracked through #122412. 
The issue mentioned in the last bullet point has been resolved. Closing the issue.
