### ISSUE TITLE
Cannot locate python interpreter

### ISSUE THREAD

**Issue by rajavsoni** [microsoft/vscode#121015]
Issue Type: <b>Bug</b>

VS Code does not show the option of Python: Select interpreter in command pallete

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
pylingo|dia|0.0.2
pyright|ms-|1.1.121
python|ms-|2021.2.633441544
jupyter|ms-|2021.2.603412351
remote-containers|ms-|0.158.0
remote-ssh|ms-|0.64.0
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.53.4
vscode-remote-extensionpack|ms-|0.20.0
vscode-ipython|pan|0.5.0

</details>

**Comment by IllusionMH** [comment]
/extPython

This command provided by estension. Make sure that you have proper config according to extension requirements and report in extension repo if needed.

Also 1.45.1 looks like really old version, please check if it still reproducible with latests VS Code version.
