### ISSUE TITLE
"Unspecified" should not be surfaced to the user

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121088]
I think that the "unspecified" workspace trust state should not be exposed to the user. This should be an internal state only, and the UI should instead say "untrusted". Since that is the default.

I do not see the benefits that the user would get by seeing "Unspecified".
Also just "Unspecified" is very broad, and in the case the user does not know the context it would be very hard for him or her to figure out what this is related to.

**Comment by sbatten** [comment]
In our effort to simplify the API the unspecified state is going away completely so it won't be an issue

**Comment by isidorn** [comment]
Great 👏
