### ISSUE TITLE
Writing the same code in two lines at once

### ISSUE THREAD

**Issue by SaloxiddinTursunaliev** [microsoft/vscode#121077]
Writing the same code in two lines at once on VSCode IDE

Visual Studio Code
Version: 1.55.1
Date: 2021-04-07T15:06:02.360Z (4 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
/needsMoreInfo

It is problem or feature request?
See https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor for multiline/multicursor editing tips

**Comment by SaloxiddinTursunaliev** [comment]
@IllusionMH  this is an issue.
I had that issue only once 3 days ago.
While I was writing a code in Dart, suddenly I started writing the same code in two line at the same time

**Comment by IllusionMH** [comment]
Maybe you hit shortcut that created second cursor?
<kbd>Esc</kbd> should exit multicursor mode.
