### ISSUE TITLE
Lagging of Kernel Execution

### ISSUE THREAD

**Issue by johncai117** [microsoft/vscode#121048]
- VS Code Version: 1.55.0
- OS Version: Darwin x64 19.5.0

Steps to Reproduce:

1. SSH to a remote computer (Not sure if relevant)
2. Using the VSCode Notebook, connect to a kernel created by Python venv.
3. Run a series of cells.
4. Successful output of some cells, and forced stopping of process by user.
5. Unable to execute any further cells when running cell using Shift + Enter.
6. Stopped all cell.
7. Experimented with simple printing of ("hello") in Python.
8. Cell does not execute. VS Code indicates at the bottom "Executing Cell".

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
> Successful output of some cells, and forced stopping of process by user.
> Unable to execute any further cells when running cell using Shift + Enter.
> Stopped all cell.

Can you explain what you are doing a little more, step by step? I can't repro an issue.

Also please include the logs from the Jupyter output channel, it might help.

cc @DonJayamanne
