### ISSUE TITLE
Can't Scroll to the Bottom of Terminal

### ISSUE THREAD

**Issue by sroyal-statsig** [microsoft/vscode#121017]
Issue Type: <b>Bug</b>

1. Create enough output in the terminal to make it scroll
2. Scroll up and down a few times until when scrolling down you can't see the prompt

VS Code version: Code - Insiders 1.56.0-insider (Universal) (845efe5d8e31079cc858131c95c36103d9439e74, 2021-04-09T09:50:42.652Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|--crash-reporter-id 51d7ad4a-5576-4fe7-8654-0a9d6ee53080|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19
gitlens|eam|11.4.0
prettier-vscode|esb|6.3.2
vscode-pull-request-github-insiders|Git|2021.4.12319
vscode-kubernetes-tools|ms-|1.3.0
cpptools|ms-|1.3.0-insiders2
java|red|0.76.0
vscode-yaml|red|0.17.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwsldoc:30278403
vsc_aa:30263845
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
vscorecescf:30285484
pythondataviewer:30285072
vscus158:30286553
vscgsv2ct:30286873

```

</details>

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by sroyal-statsig** [comment]
![recording](https://user-images.githubusercontent.com/76536058/114444472-cd297780-9b83-11eb-8197-dfe584830afd.gif)

Attached a gif showing the issue. At the end I'm trying to scroll down still but it won't scroll any farther to show the lines where I ran ls. Let me know if you need any more info

**Comment by Tyriar** [comment]
I've seen this as well. It's easy to workaround by just scrolling up and down but we should try fix this for April.

**Comment by Tyriar** [comment]
Can repro in xterm.js https://github.com/xtermjs/xterm.js/issues/3311
