### ISSUE TITLE
Menu bar and left bar are not showing 

### ISSUE THREAD

**Issue by kyn007** [microsoft/vscode#121079]
I was using vs code since last 3 months but I never faced this problem. My problem is that my Menu bar on top and bar on left is not showing and the auto complete feature is not working. I also tried fixing it with some videos on youtube but none of them helped. Please try to resolve this problem at the earliest. 

Thanks & Regards

**Comment by gjsjohnmurray** [comment]
/gifPlease

Maybe you accidentally toggled into [Zen mode](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_zen-mode).
