### ISSUE TITLE
EJS tags inside <Script> shows as error but the code works

### ISSUE THREAD

**Issue by eliezra236** [microsoft/vscode#121076]
- VS Code Version: 1.55.1
- OS Version: windows 10

Steps to Reproduce:

1. When writing EJS file I have this part:

```
<script type='text/javascript'>

  var rows =<%-JSON.stringify(data)%>

  console.log(rows);

</script>
```

data is a value that I pass when I render the page.
The code works but VSCODE flair the "<%-" and "%>" as error

I believe this is a pretty similar question - https://github.com/microsoft/vscode/issues/51118
But it's not entirely, as my problem only occurs when inside the <script> on the EJS file. In the end someone said he figured it out but didn't provide an explanation

**Comment by aeschli** [comment]
The HTML language extension only supports HTML, but this is a templating language.

You can either look out for an extension that understands the EJS file syntax, or disable script validation in html:

`"html.validate.scripts": false`

Yes, it's a dup of #51118
