### ISSUE TITLE
Open file dialog should start in the directory for the current active file

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/vscode#1210]
When using `File > Open File`, this will open the directory of the last file selected through `File > Open File`. This is sub-optimal, since the current active file may not have been opened through that dialog. The dialog itself should be context-aware.

**Comment by egamma** [comment]
@bpasero fyi

**Comment by bpasero** [comment]
Not convinced, but Sublime seems to do this too.

**Comment by sfms** [comment]
Definitely would like this behavior.

**Comment by DanielRosenwasser** [comment]
Yeah, Visual Studio and Notepad++ do this as well.

I was looking into this, but I backed off because I wasn't sure how to appropriately make windows depend on their contained editors (or whether it would even be appropriate to do so). If you guys had any guidance on it, I'd be glad to work on it.

**Comment by bpasero** [comment]
Pushed for opening files. I left this untouched for Mac because imho this does not make sense for opening folders.
