### ISSUE TITLE
Relative path patterns not supported by search api

### ISSUE THREAD

**Issue by Zardddddd60** [microsoft/vscode#121087]
- VS Code Version:1.55.1
- OS Version:macOS 10.15.5
- Node Version: 12.18.2

Steps to Reproduce:
I try to debug a package symlinked to an application, with breakpoints set in typescript, but failed.

Firstly, without symlinked package, just the application, it works.
![image](https://user-images.githubusercontent.com/52653926/114397132-ed335800-9bd0-11eb-9e6b-8c78ae7b3c0a.png)

![image](https://user-images.githubusercontent.com/52653926/114397077-dbea4b80-9bd0-11eb-9bd3-7664f46fafbb.png)

Then, with symlinked package, it dosen't work, even the package is not actually imported. Setting the path of testpackage in `outFiles` makes error.
![image](https://user-images.githubusercontent.com/52653926/114397546-616dfb80-9bd1-11eb-90fe-98fce8023446.png)
![image](https://user-images.githubusercontent.com/52653926/114397868-bb6ec100-9bd1-11eb-90ab-327dc2cfb75d.png)

I've made a reproductive example. Is there something I missed?

1.`git clone git@github.com:Zardddddd60/testpackage.git`, `git clone git@github.com:Zardddddd60/testapp.git`
2. symlink testpackage to testapp, and press debug in testapp

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Zardddddd60** [comment]
I think the key is how to set the `outFiles`. It works if I debug the javascript code of symlinked package with `program` pointing to typescript file. Is there is way to debug typescript code of symlinked package?

![image](https://user-images.githubusercontent.com/52653926/114412985-2fb06100-9be0-11eb-898a-48f4a57004c6.png)

**Comment by Zardddddd60** [comment]
> /jsDebugLogs

It seems that if I include compiled symlinked package path(`"${workspaceFolder}/node_modules/testpackage/**/*.js"`) into `outFiles`, debugger uses the typescript code of `program`.   

[vscode-debugadapter-bac42d5b.json.gz](https://github.com/microsoft/vscode/files/6300975/vscode-debugadapter-bac42d5b.json.gz)


When adding absolute path in `outFiles` like `"/Users/liudong/ldd/test__/testpackage/**/*.js"`, the debugger failed with `(node:60661) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`. 

[vscode-debugadapter-6d1bab09.json.gz](https://github.com/microsoft/vscode/files/6300976/vscode-debugadapter-6d1bab09.json.gz)

**Comment by connor4312** [comment]
Thanks for the logs and example repo! I think I can reproduce. It should only affect breakpoints that are passed very early on in the program, since the process that looks for sourcemaps ahead of time isn't finding results.

@roblourens although the path seems correct, it seems like setting this as a RelativePattern doesn't work:

![](https://memes.peet.io/img/21-04-aae51361-f6d8-424c-b5c8-019e042c7059.png)

As Zard reported, f I remove the extra outFiles pattern (so it's just `**/*.js`) then it works. Is this comma-delimiting the correct way to deal with these? Or should I just run separate searches for each include path? That would be easy to do.

**Comment by roblourens** [comment]
It should be like `{a, b}` if you have multiple patterns. But yeah, the search view has bonus features that don't show up other places. I think this would go all the way to our glob library. Did it come in from the user's config or your code?

**Comment by connor4312** [comment]
Ah, cool, thanks. That made it not break, but it looks like relative patterns still aren't applying correctly.

![](https://memes.peet.io/img/21-04-75c66ddf-cb4b-42be-8005-a39a58ad8ca7.png)

**Comment by andreamah** [comment]
> Ah, cool, thanks. That made it not break, but it looks like relative patterns still aren't applying correctly.
> 
> ![](https://camo.githubusercontent.com/23755cf6499b9a716d6933a0da986262cdfd1f5d3ec12697fc28662391c2cebf/68747470733a2f2f6d656d65732e706565742e696f2f696d672f32312d30342d37356336366464662d636234622d343262652d383030352d6133396135386164386361372e706e67)

see https://github.com/microsoft/vscode/issues/130992#issuecomment-1355186414

**Comment by connor4312** [comment]
This actually duplicates https://github.com/microsoft/vscode/issues/168635, and should be fixed with https://github.com/microsoft/vscode-js-debug/pull/1486 as well
