### ISSUE TITLE
Terminal opened by task doesn't inherit environment?

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#121082]
In my workspace settings, I've set
```
    "terminal.integrated.env.linux": {
        "REPO": "/home/gruntfuggly/workspace/build-area"
    }
```
When I open a new integrated terminal I can see the variable has been defined
```
REPO=/home/gruntfuggly/workspace/build-area
```

However when I run a task where I want to substitute the variable into the command, it doesn't appear to be defined.

Should this work as I would expect?

**Comment by alexr00** [comment]
Given 
```json
	"terminal.integrated.env.windows": {
		"TESTER": "itsatest"
	}
```
then this task will echo the value of the env var:
```json
		{
			"label": "TESTER",
			"type": "shell",
			"command": "echo %TESTER%"
		}
```
but this task will not echo the value of the env var:
```json
		{
			"label": "TESTER",
			"type": "shell",
			"command": "echo ${env:TESTER}"
		}
```
This is by design, since `terminal.integrated.env.*` values apply to terminals, and variable substitution with `${env:}` happens in VS Code before anything is sent to the terminal.
