### ISSUE TITLE
Improve C/C++ colorizer

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#12102]
The status quo:
![image](https://cloud.githubusercontent.com/assets/240091/18569129/5ead3190-7bd3-11e6-8eaf-91b91d869868.png)
![image](https://cloud.githubusercontent.com/assets/240091/18569133/6204f8aa-7bd3-11e6-8059-ff2874ab9374.png)

The problem:

- No special color for operators.
- No special color for user-defined types, like `caryll_buffer`.
- Pointers and references should be colored.

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
