### ISSUE TITLE
The edittor does not color the keyword properly

### ISSUE THREAD

**Issue by FelixXing** [microsoft/vscode#121064]
Issue Type: <b>Bug</b>

When I try to create a template class specilization for certain type, the editor do not color the keyword "class" in the specialize defination. It shold be color in blue
![Screenshot 2021-04-12 101737](https://user-images.githubusercontent.com/43862411/114409371-6357a080-9b78-11eb-9ce2-19e6462b354d.png)
![Screenshot 2021-04-12 101755](https://user-images.githubusercontent.com/43862411/114409375-6488cd80-9b78-11eb-9724-f5c433a1735e.png)

I am developing in C++

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.41GB free)|
|Process Argv|--crash-reporter-id 4836ccce-b60e-465d-99d7-54c841b2744f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.11
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-wsl|ms-|0.54.6
cpptools|ms-|1.2.2
pdf|tom|1.1.0
txt-syntax|xsh|0.1.5
local-history|xyz|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30286882

```

</details>

**Comment by alexr00** [comment]
Can you please provide a full copy/pastable example I can reproduce the issue with?

**Comment by felixxing** [comment]
see below:
![Screenshot 2021-04-13 133500](https://user-images.githubusercontent.com/43862411/114596066-244f4b00-9c5d-11eb-98ae-7f4fc7f2d10f.png)
When I try to break after the template, it backs to normal:
![Screenshot 2021-04-13 133511](https://user-images.githubusercontent.com/43862411/114596101-316c3a00-9c5d-11eb-8b0d-bdf8124df741.png)
