### ISSUE TITLE
New line after the equals sign for function assignment loses syntax highlighting

### ISSUE THREAD

**Issue by qdirks** [microsoft/vscode#121050]
Issue Type: <b>Bug</b>

Steps to reproduce:
Open a new tab (double click in the tab area) and use javascript syntax highlighting (ctrl+k, m javascript enter). Paste the code segment below into the tab. Syntax highlighting is not good. The assignments to the variables after a new line regain highlighting after saving the file. The assignments to the object members after a new line will remain unhighlighted even after saving the file.

```js
let fn1 = ()=>{};
let fn2 =
    ()=>{};
let fn3 = function() {};
let fn4 =
    function() {};

let obj = {};
obj.fn0 = ()=>{};
obj.fn1 =
    ()=>{};
obj.fn2 = function() {};
obj.fn3 =
    function() {};
```

Expected behavior:
The syntax highlighting should always be present, after a new line, and also before saving.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.32GB free)|
|Process Argv|--crash-reporter-id 5b5f3c56-4a55-488e-8884-427be77ca91e|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by mjbvz** [comment]
Looks fine to me:

<img width="507" alt="Screen Shot 2021-04-16 at 6 17 22 PM" src="https://user-images.githubusercontent.com/12821956/115097600-fe85a880-9edf-11eb-9cbb-6459b76ece85.png">


Please explain the issue

**Comment by qdirks** [comment]
fn2 and fn4 should be highlighted with yellow. Obj.fn1 and obj.fn3 should be highlighted with yellow. After you save the file, you will notice that fn2 and fn4 do highlight to yellow, but the fn1 and fn3 methods of obj do not; they are always in light blue. In your screenshot, I can see that the issue is present.
