### ISSUE TITLE
VSCode window always crashed.

### ISSUE THREAD

**Issue by qinxin0720** [microsoft/vscode#121063]
- VS Code Version: 1.55.1
- OS Version: macOS Big Sur 11.2 (Darwin x64 20.3.0)

Steps to Reproduce:

<img width="1792" alt="截屏2021-04-12 上午9 46 39" src="https://user-images.githubusercontent.com/28943828/114330643-bcbdd080-9b74-11eb-8a94-3466395ffc0a.png">

1.

2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Wintaru** [comment]
I am seeing this as well with my M1 Mac running BigSur. This happens any time a device is removed and it had a file that VS Code has open.

**Comment by connor4312** [comment]
Please collect a crash report using these instructions: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
