### ISSUE TITLE
Remove false-positive errors if there is an assertion

### ISSUE THREAD

**Issue by HerryYT** [microsoft/vscode#121007]
I would like to finally remove false-positive errors if i am doing an assertion using console.assert().
![Screenshot (212)](https://user-images.githubusercontent.com/34418030/114267920-d1785800-99fe-11eb-87fa-95e01753e2c7.png)
As we can see here, we have an assertion that will ensure that `Jukebox.getEncryption()` isn't null, and if it is, an error will be thrown; Then in the next line of code i am getting an error: "Object is possibly null" because `Jukebox.getEncryption()` is of type Encryption | null, enforcing the instance of Encryption with "!" (es: `Jukebox.getEncryption()!.myFunc()`), or doing an extra if to ensure it isn't null looks really ambiguos, so that's why i am doing that feature request. Thanks in advice!

**Comment by IllusionMH** [comment]
`console.assert().` has no effect on next statements.
```
let a;
console.assert(a!==undefined, 'incorrect a value');
console.log('Still executed and throws', a.toUpperCase());
```

I guess you mean that you are using `assert` module (and it's recent version that has proper typing).
You should use constant `const encryption = Jukebox.getEncryption();`, perform assertion on constant and use it.

It is unsafe to assume that `getEncryption` can't change state of object like `Array.prototype.pop`.
Also see https://github.com/microsoft/TypeScript/issues/9998 and issues related to narrowing and CFA.

**Comment by HerryYT** [comment]
Thanks so much for the support, I should actually have used the assert library instead of the console one. Thank you very much for the advice too, I'll take a look at it right away
