### ISSUE TITLE
Text selected in peek does not transfer to search when Ctrl+Shift+F entered

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#121060]
Issue Type: <b>Bug</b>

1. Be in any view other than Search (optional, but adds evidence about the problem later).
2. Open a file.
3. Open a peek (e.g. peek a definition).
4. Select some text in the peek.
5. Enter `Ctrl+Shift+F`

:bug: the selected text does not transfer into the Search field, though the Search view appears and focus moves to that field.

VS Code version: Code - Insiders 1.56.0-insider (845efe5d8e31079cc858131c95c36103d9439e74, 2021-04-09T09:50:06.816Z)
OS version: Windows_NT x64 10.0.19042

**Comment by roblourens** [comment]
@bpasero is this exposed in the editor service? Or is there any way for me to get the selected text out of the peek widget?

**Comment by bpasero** [comment]
@roblourens embedded editors are actually not exposed through `IEditorService`. You could try [`ICodeEditorService#listCodeEditors`](https://github.com/microsoft/vscode/blob/e66547a1d9f880747de81310764cf809639e462b/src/vs/editor/browser/services/codeEditorService.ts#L31-L31) to find it though.

**Comment by roblourens** [comment]
Cool, that was relatively easy, thanks
