### ISSUE TITLE
language server diagnostic dialogs should hint at what the (number) is

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#121055]
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Install ms-azuretools.vscode-docker 1.11.0 (newer versions will fix this specific flavor which means you'd have to find your own language server alert)
2. Create a Dockerfile with the content from https://github.com/check-spelling/check-spelling/blob/ce3aff0bfdf1cbabeffecb5afc28cf6b1c719e25/Dockerfile#L17-L22
3. Hover over the squiggly line
    ![image](https://user-images.githubusercontent.com/2119212/114314354-419ee080-9ac8-11eb-9a56-0022beac0d13.png)
4. Click `View Problem`
   ![image](https://user-images.githubusercontent.com/2119212/114314346-377ce200-9ac8-11eb-9873-7535dd0cdb86.png)
5. It isn't readily apparent what `(34)` is or why there's no space between it and `dockerfile-utils`.

I suppose I should define `is`. Both views already tell me what the warning is. They do not explain why they also show `(34)`. Letting one hover over this or click to see a hint indicating that this is a language-server specific identifier for this warning category would be quite elucidating.

For instance, can I use the `(34)` to ignore the alert? I have no idea. Maybe I can, but only for certain language servers? These views are a good way to teach me what I can do w/ the content they're presenting.

Also, while you're in the area, if there was a way to cause `dockerfile-utils` to explain which extension(s) contributed it, that'd be really helpful. I eventually figured out that I wanted to file a bug against microsoft/vscode-docker, but it wasn't remotely obvious. 

Does this issue occur when all extensions are disabled?: Yes/No
No (well, you need a language server, and I don't know if vscode has any built in)

This bug isn't about the language server (I already filed microsoft/vscode-docker#2865 about their contribution), it's about vscode's rendering of the report from the language server:
https://github.com/microsoft/vscode-docker/issues/2865#issuecomment-817340146

Fwiw, I currently use the reporter format for my GitHub Action, and at some point, I might look into making it available as a vscode extension, since I'm starting to live here, as do my colleagues.

GitHub Actions, afaict, do not render the identifier:

https://github.com/jsoref/examples-testing/commit/e4210b7459c477a3cbb04884d417823b7b34a8da
![image](https://user-images.githubusercontent.com/2119212/114315134-782a2a80-9acb-11eb-9fc7-e2f7fbb328bc.png)
https://github.com/jsoref/examples-testing/runs/2316332417#step:3:21
![image](https://user-images.githubusercontent.com/2119212/114315158-94c66280-9acb-11eb-8b02-123f11deb216.png)

**Comment by rcjsuen** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> No (well, you need a language server, and I don't know if vscode has any built in)

Visual Studio Code comes with built-in support for JavaScript and TypeScript so you can reproduce these "mystery numbers" without too much effort just by writing an incorrect JavaScript file.

![image](https://user-images.githubusercontent.com/15629116/114315392-cee43400-9acc-11eb-8714-c3fd23c47ce6.png)

**Comment by jrieken** [comment]
This is information showing the source and error as provided by extensions. The pattern is `<source>(<code>)`. I suggest to reach out to extensions individually, e.g VS Code has the ability to make the `code` portion a link for further explanation
