### ISSUE TITLE
Trust all dropdown polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121091]
Same as mentioned in Standup, not a fan of the Trust dropdown button since it is not symetric.
However if you decide to keep it, the very least is to have the parent folder name under quotes, so it is easier to read

`Trust All in 'Development'`

![Screenshot 2021-04-12 at 15 07 33](https://user-images.githubusercontent.com/1926584/114399236-f99fbc80-9ba0-11eb-9ac9-841fc9bcb61d.png)

**Comment by lszomoru** [comment]
Fixed.

**Comment by mjbvz** [comment]
Marking as verified since it looks like we are using generic message now: `Trust all in parent folder`
