### ISSUE TITLE
Terminal: code [directory] -r opens in all existing VS Code windows

### ISSUE THREAD

**Issue by mikatpt** [microsoft/vscode#121034]
Hoping for some insight here - not sure if this is expected behavior, or if I'm doing something incorrectly!

1. Open two windows of VS Code.
2. In the integrated terminal, navigate to another directory and type `code . -r`
3. Both VS Code windows will open to that directory.

Thank you!
Michael

**Comment by bpasero** [comment]
I cannot reproduce.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
