### ISSUE TITLE
WebView: Some specific links cannot be opened in the browser.

### ISSUE THREAD

**Issue by Frederisk** [microsoft/vscode#121045]
- VS Code Version: 1.56.0-insiders
- OS Version: Windows 10 20H2

Steps to Reproduce:

This is an issue about the WebView API.

Create a WebView and use the following HTML content:

``` html
<html>
 <head>
  <base href="https://en.wikipedia.org/wiki/" target="_blank">
 </head>
 <body>
  <a href="/wiki/a#a">click here</a>
 </body>
<html>
```

![image](https://user-images.githubusercontent.com/29837738/114302905-d4a63d80-9afd-11eb-9826-0bbd545f9da5.png)

But the browser cannot be opened after this link is clicked. As a test,

I tried several different styles:

``` html
<html>
 <head>
  <base href="https://en.wikipedia.org/wiki/">
 </head>
 <body>
  <a href="/wiki">/wiki</a><hr />
  <a href="/wiki/">/wiki/</a><hr />
  <a href="/wiki/a">/wiki/a</a><hr />
  <a href="/wiki/a#">/wiki/a#</a><hr />
  <a href="/wiki/a#a">/wiki/a#a</a><hr />
  <a href="/wiki#a">/wiki#a</a><hr />
  <a href="/#a">/#a</a><hr />
 </body>
</html>
```

![image](https://user-images.githubusercontent.com/29837738/114303125-05d33d80-9aff-11eb-843e-5a8b8d2dc989.png)

Only `/wiki/a#a` does not work. All others can open the browser normally and jump to the target webpage. Strangely enough, this link does not seem to be a problem when viewed in DEBUG mode:

![image](https://user-images.githubusercontent.com/29837738/114303226-a7f32580-9aff-11eb-9e47-c7158dd8eaa9.png)

**Comment by thunder-coding** [comment]
Probably a issue with Electron

See electron/electron#2242

**Comment by thunder-coding** [comment]
Probably a issue with Electron

See electron/electron#2242

**Comment by mjbvz** [comment]
The root cause is this line:

https://github.com/microsoft/vscode/blob/7a2f9014556b9447d6cd6044f33c7eb1437862a4/src/vs/workbench/contrib/webview/browser/pre/main.js
