### ISSUE TITLE
Install error under Fedora 22 Linux

### ISSUE THREAD

**Issue by jcassar** [Microsoft/vscode#12107]
- VSCode Version: Latest github
- OS Version: Fedora 22 Linux 4.4.14-200.fc22.x86_64

Received the following errors when installing vscode:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:bpasero/fsevents#vscode (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: windows-mutex@0.2.0 (node_modules/windows-mutex):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for windows-mutex@0.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.14-200.fc22.x86_64
npm ERR! argv "node" "/bin/npm" "install" "--arch=x64"
npm ERR! node v0.10.42
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! ghooks@1.0.3 install: `node ./bin/install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ghooks@1.0.3 install script 'node ./bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghooks package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghooks
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghooks
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jcassar/vscode/npm-debug.log

**Comment by Tyriar** [comment]
What version node and npm are you running? Is this an old workspace, if so have you tried re-cloning and starting again from scratch?

**Comment by jcassar** [comment]
Daniel,

I try to upload the log, but github refused the zip.
Yes, I updated to the latest, node v0.10.42 and npm  v3.10.8.
I attached the npm-debug.log in case you need to review it.

Best,

JP
Quoting Daniel Imms <notifications@github.com>:

**Comment by Tyriar** [comment]
node 0.10.42 is quite old now and is certainly not the latest. We recommend 6+ https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source
