### ISSUE TITLE
Countless git sign-in prompts during sleep

### ISSUE THREAD

**Issue by bekir-ozturk** [microsoft/vscode#121083]
Issue Type: <b>Bug</b>

- Checkout a private git repo into a folder on your machine.
- Change the password or clear your credentials so that the next git operation you want to perform will ask you to sign-in.
- Open the folder in vscode. 
- Vscode will automatically attempt to do "git fetch" and ask for your credentials using "Git Credential Manager for Windows". Ignore the prompt.
- Put your computer to sleep.

**Expected** Vscode stops asking for git credentials until you explicitely perform a git related operation.

**Actual** You have a hundred more popup windows opened, all asking for the credentials to the remote. See screenshots below.

![image](https://user-images.githubusercontent.com/60651445/114380496-707d8b00-9b8a-11eb-8e0f-3c1ecddae9f1.png)

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.88GB free)|
|Process Argv|--crash-reporter-id d7fcc2be-3d86-4881-998d-ee0fdb096f17|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-drawio|hed|1.4.0
csharp|ms-|1.23.11
remote-wsl|ms-|0.54.6
partial-diff|ryu|1.4.2

</details><details>
<summary>A/B Experiments</summary>

```
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt875:30259475
vspre833cf:30267465
vshan820cf:30276953
vscus158cf:30286554

```

</details>

**Comment by eamodio** [comment]
Sounds like an issue with `git.autoFetch`

**Comment by bekir-ozturk** [comment]
I wouldn't know as I haven't been using VSCode for development recently.

**Comment by lszomoru** [comment]
@bekir-ozturk, thanks for getting back to me on this. I will go ahead and close this issue for now, but in case you are still able to reproduce the problem please feel free to reopen it.
