### ISSUE TITLE
Allow "Find All References" to expand to a full tab

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#12101]
Right now "find all references" opens the code-lens pop-up. If I am in a large project and want to see all references to a symbol such as an interface, I might want to bounce between different implementations. This is made difficult by the fact that the list of references doesn't persist/can't be expanded.

It would be great if there was an option to expand the "find all references" results into the search tab, and navigate between them. Bad mspaint mockup below, with the references listed on the right and the referencing code in a tab on the right.

![image](https://cloud.githubusercontent.com/assets/2957173/18567386/2e37ccc2-7b98-11e6-9a8e-fe93752e24b7.png)

**Comment by jrieken** [comment]
@hoovercj There is an extension doing something very similar: https://marketplace.visualstudio.com/items?itemName=jrieken.references-plusplus

**Comment by dshook** [comment]
Agreed on this one. Right now if you find a reference, click on it to go to the file, the inline view of references obscures what you just clicked to view, so you close it, then find out that wasn't the reference you were looking for, then have to go and re-find all references.

**Comment by mbenkmann** [comment]
I think this issue should be merged with issue #22261. It seems to be the same thing.

**Comment by jrieken** [comment]
Agreed, closing as dupe
