### ISSUE TITLE
Terminal fonts problem

### ISSUE THREAD

**Issue by alitariqnet** [microsoft/vscode#121072]
- Extension version: 2.3.53
- VS Code Version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Open terminal.
2. And see.

Does this issue occur when all extensions are disabled?: Yes/No
![vscode3](https://user-images.githubusercontent.com/75094670/114354331-83429080-9b87-11eb-9ffc-f3cc2567660b.PNG)
![vscode4](https://user-images.githubusercontent.com/75094670/114354336-850c5400-9b87-11eb-8ad3-f6bbf9b28f9d.PNG)

![vscode1](https://user-images.githubusercontent.com/75094670/114354314-7c1b8280-9b87-11eb-8ffb-363068eccdff.PNG)
![vscode2](https://user-images.githubusercontent.com/75094670/114354325-80e03680-9b87-11eb-835d-5c009087906f.PNG)

Terminal fonts become blurry like zooming in a pixel image then I change the font size in settings file under terminal section to fix it.

Thanks
Ali

**Comment by meganrogge** [comment]
Does changing `terminal.integrated.gpuAcceleration` help?

**Comment by Tyriar** [comment]
@alitariqnet what font is that you're using?

**Comment by alitariqnet** [comment]
> Does changing `terminal.integrated.gpuAcceleration` help?

I will try this and let you know. I have tried disabling all extensions but that didn't work.

**Comment by alitariqnet** [comment]
> @alitariqnet what font is that you're using?

Probably the default VScode fonts.

> Does changing `terminal.integrated.gpuAcceleration` help?
Should I write "terminal.integrated.gpuAcceleration:true" in this file to enable it?

![pic12](https://user-images.githubusercontent.com/75094670/117531279-38d3f880-affb-11eb-8bf3-0797669844ec.PNG)

**Comment by alitariqnet** [comment]
> @alitariqnet what font is that you're using?

It's probably the default by VScode.

**Comment by alitariqnet** [comment]
> Does changing `terminal.integrated.gpuAcceleration` help?

OK found it it's on auto. I will try with other two options "on" and "off" and @Tyriar you can see the font settings in this image.
![pic13](https://user-images.githubusercontent.com/75094670/117531472-0b3b7f00-affc-11eb-9846-872ae244ff57.PNG)

**Comment by alitariqnet** [comment]
@meganrogge @Tyriar 
"terminal.integrated.gpuAcceleration": "off",
OK turning it "on" cause problem and turning it "off" cause it work fine.
Thanks
