### ISSUE TITLE
VS Code does render all UTF8 characters correctly

### ISSUE THREAD

**Issue by glennsarti** [Microsoft/vscode#12103]
- VSCode Version: 1.5.2
- OS Version: Windows Server 2016 RS1, Windows 10 AU

Steps to Reproduce:
1.  Copy these characters `ᚠᛇᚻᚠᛇᚻ` into any Visual Studio Code file.

These are the Rune characters from http://www.columbia.edu/~fdc/utf8/

2. In Visual Studio Code they will appear as blank rectangles, however if you paste them into Notepad they render correctly.

I tried Consolas, Courier New and monospaced and they all would not render the characters correctly.

![utf8](https://cloud.githubusercontent.com/assets/5819622/18569446/76df6bf6-7b57-11e6-9076-64386e9aed00.png)

**Comment by bpasero** [comment]
Font issue?

**Comment by glennsarti** [comment]
That's what I first thought.  As per my notes I tried the default fonts (Consolas, Courier New and monospaced).  Conemu2 which also uses `Consolas` also renders correctly.

**Comment by glennsarti** [comment]
Seems strange that notepad.exe (of all apps!) would render it ok and not VS Code.

**Comment by be5invis** [comment]
@bpasero Chrome's default font linking does not include Segoe UI Symbol, which contains Runes.

**Comment by glennsarti** [comment]
Ok.  So short version is, can't be fixed?

**Comment by alexandrudima** [comment]
Duplicate of #5696

Chromium knows about it and have already fixed it in May - https://bugs.chromium.org/p/chromium/issues/detail?id=607528

We will get the fix ... eventually.
