### ISSUE TITLE
Duplicate Selected File in Context Menu (Right Click)

### ISSUE THREAD

**Issue by abdollahkahne** [microsoft/vscode#121012]
As a developer these days we work with lots of boilerplate code. It is good to be able to duplicate files and change only name and some small content of code to generate for example a new component or a new html file or any thing else.
![Screenshot from 2021-04-10 18-27-56](https://user-images.githubusercontent.com/48277995/114272242-a4419f00-9a2a-11eb-98c9-9f54e99247a3.png)

**Comment by isidorn** [comment]
You can also use this extension

![Screenshot 2021-04-12 at 09 38 57](https://user-images.githubusercontent.com/1926584/114358567-55ebe780-9b73-11eb-994e-0b3fbde8083a.png)
