### ISSUE TITLE
Git changes not recorded after saving file so unable to commit.

### ISSUE THREAD

**Issue by amaynez** [microsoft/vscode#121033]
Issue Type: <b>Bug</b>

This has happened intermitently a couple of times in the last hour in different projects.
1. Make a change on a file
2. Sometimes, after the file is saved, the GIT change is not logged, and even if the file has clearly changed, it is impossible to commit from the IDE
In both cases I was able to commit using GIT's CLI.

VS Code version: Code 1.55.1 (Universal) (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (2.06GB free)|
|Process Argv|--crash-reporter-id ac9cdffb-426a-4453-bef1-fb07e46d7e09|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.19
vscode-html-css|ecm|1.10.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.0
svgeditor|hen|2.9.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
shopify-liquid|sis|2.3.0
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by eamodio** [comment]
Can you please post the contents of the _Git_ output channel in the _Outputs_ view when this happens again? Thanks!

**Comment by amaynez** [comment]
It just happened again, but the Git output channel recorded nothing relevant, it has information pertaining a previous change, nothing about the current changes:

Here is VS Code showing NO Changes, and the output of the Git channel:
![VSCodeError](https://github.com/the-mvm/the-mvm.github.io/blob/main/assets/img/screenshots%20issue/vsCode.png?raw=true)

And here is Github desktop showing correctly the changes:
![Girhub Desktop](https://github.com/the-mvm/the-mvm.github.io/blob/main/assets/img/screenshots%20issue/girhub-desktop.png?raw=true)
