### ISSUE TITLE
Focus is not returned to tabs with a webview inside

### ISSUE THREAD

**Issue by iatanas0v** [microsoft/vscode#121086]
- VS Code Version: 1.55.1
- OS Version: Linux x64 5.11.11-200.fc33.x86_64

Steps to Reproduce:

1. Open "Relase Notes" or other webview power tab
2. At this point shortcuts like "Ctrl+P" or even just the up/down arrows are working as expected
3. Open the integrated terminal via "Ctrl+`"
4. Close the integrated terminal via "Ctrl+`"
5. At this point no shortcuts work. This seems to happen only with webview tabs

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
I just tested this on VS Code insiders but am not able to reproduce this issue

Please test on the next VS Code insiders build and let me know if you are still seeing issue
