### ISSUE TITLE
Make Find in Selection not enabled by default

### ISSUE THREAD

**Issue by Turash** [Microsoft/vscode#12109]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@Turash Can you provide more details on which search are you referring to?

- Search in a file
- Search across files
- Quick open
- Find all references

There are different search features

**Comment by bpasero** [comment]
Needs more info.

**Comment by Turash** [comment]
Hi, It does not happen every time. Sometimes. I will paste right away when I experience.

**Comment by Turash** [comment]
![test](https://cloud.githubusercontent.com/assets/5880099/18582594/27899dec-7c06-11e6-82bd-338532dc1ede.png)

**Comment by chrmarti** [comment]
The screenshot shows a text search within a file. The file shows several occurrences of the text "marker" while the search box searching for "marking" says "No results".

@Turash:
- Does the problem always occur with this file and the search for "marker"?
- Does the problem go away when you close and reopen the search box?
- If not, does the problem go away when you close and reopen the editor tab?
- If not, does the problem go away when you restart VS Code?

**Comment by alexandrudima** [comment]
Those highlights are not coming from the find widget (they would show in the overview ruler).

@Turash Can you please provide exact reproducible steps, we would love to get to the bottom of this issue.

**Comment by chrmarti** [comment]
@alexandrudima Wouldn't you expect the find widget to show the number of results instead of "No results"?

**Comment by Turash** [comment]
Hi, 
I use the latest one for mac. I can never find the correct text at some point. I do not know if its for my cache memory. Should I sent you over my files or?

**Comment by alexandrudima** [comment]
@chrmarti Yes, there is something wrong (an event missing or ignored perhaps?) where the find widget in this case does not realize it gets a new model or something and does not research -- hence the lack of 'x of y' matches, the lack of find widget decorations, etc.

@Turash, sure we can start with the file that causes this issue, but is this happening all the time for you? As in, you open this specific file and `cmd+f` is never able to find anything in this file? Or is this happening after some certain steps, as in, you open a file, find in a file, then switch to a different file, etc. 

I would love any hints on how we can reproduce, thank you.

**Comment by Turash** [comment]
Hi @alexandrudima 
It happens after certain time. And no way back, but restart the ide.

**Comment by alexandrudima** [comment]
@Turash did you install extensions that modify and patch our sources (e.g. vscode-icons)?

**Comment by roblourens** [comment]
In case you guys didn't notice, 'find in selection' is selected in that screenshot. So there might be some selected text offscreen. I tend to trigger this on accident all the time. @Turash, next time can you try clicking that button in the find widget to the right of the arrows?

**Comment by alexandrudima** [comment]
@roblourens That is it! It is the find in selection.

@bgashler1 Should we emphasize somehow the find in selection toggle when there are no results and the toggle is on? The idea would be to bring attention to that toggle such that if you click it, you might get results in other areas of the file.

![image](https://cloud.githubusercontent.com/assets/5047891/18822551/cf185746-83b9-11e6-84a4-462a8561b45a.png)

**Comment by bgashler1** [comment]
I've experienced this problem as well.  It could definitely be improved.  Whenever I have text selected that's on screen, it eventually sort of becomes clear to me what's going wrong.  But if the selection is off screen this can be quite confusing.

I wonder if having this button enabled by default when there is a selection is good.  What is the reasoning behind having it automatically search within the selection only.  I think it's pretty easy to not know that this will happen by default if there is a selection.  Both Sublime and Atom require you to take an extra step to search only within a selection.

**Comment by roblourens** [comment]
@alexandrudima @bgashler1 @chrmarti Could we make Find in Selection not enabled by default for October? One of my pet peeves.

**Comment by chrmarti** [comment]
It is enabled when selecting multiple lines in the editor before opening the find widget. We could turn off that behavior.

**Comment by roblourens** [comment]
Right, that's what I mean

**Comment by Bill-Stewart** [comment]
I think it makes sense not to enable the "Find in selection" option by default, especially as other editors have established this as a behavioral precedent. The current behavior is inconsistent (it only enables by default if the selection contains a newline). I also think the message should say "No results in selection" to make this more explicit.

**Comment by dvlsg** [comment]
This change definitely threw me off, since I am used to selecting multiple lines, pressing ctrl+f, searching, pressing shift+enter, then typing my replacements intended for the current selection.

Now that "find in selection" is no longer enabled by default when multiple lines are selected, I have to take my hands off the keyboard to go click that button, usually after I realize I just replaced *way* more than I originally intended.

I can certainly understand how the reverse could be irritating as well, though. Is there a currently available way to re-enable "find in selection" by default whenever more than one line is selected (config / setting), so we can choose for ourselves? Something like `auto_find_in_selection` in sublime text.

**Comment by bgashler1** [comment]
@dvlsg I don't think we have a setting for this.  Could you create another issue requesting this (also reference this issue number in it)?

**Comment by Bill-Stewart** [comment]
My opinion: "Find in selection" should be enabled by default if there is _any_ selection at all (multi-line or not). If "find in selection" is enabled by default only for certain kinds of selections, this seems arbitrary and inconsistent. For users that don't like "find in selection" to be enabled by default when there is a selection, it makes sense to have an option to disable it.

**Comment by dvlsg** [comment]
@bgashler1 I actually ran across #8843 after posting -- it's not quite the same, but that issue / request would be sufficient for me. I'm really just looking for a way to fire up the find-in-selection using just my keyboard.

If you think there might be sufficient desire for the explicit setting on top of the direct shortcut, I certainly can take the time to create an issue request for that.

**Comment by bgashler1** [comment]
@Bill-Stewart we needed to remove the default find in selection behavior due to it being easy to misunderstand what was going on when no results were showing up.

Two solutions we will consider  are adding a setting to enable finding within selections by default or a new command as proposed in #8843 that you could rebind the keyboard shortcut for Find/Replace to.
