### ISSUE TITLE
Configuration list is corrupted.

### ISSUE THREAD

**Issue by harimsng** [microsoft/vscode#121025]
Issue Type: <b>Bug</b>
![화면 캡처 2021-04-11 072754](https://user-images.githubusercontent.com/77538894/114286249-fa006080-9a97-11eb-9a31-87de34f5f8dc.png)
two configurations in launch.json, 6 configurations in the list.

Nevertheless every Run and Debug configuration should be handled in launch.json, there's inaccessible configurations.
1. Add configuration on launch.json.
2. save the file and exit vscode.
3. turn on vscode and check the configuration list on 'Run and Debug' menu.
maximum number of those configurations is 3.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (9.69GB free)|
|Process Argv|--crash-reporter-id eb45cbc1-8e48-4a30-be2d-d7196f9be35c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|Memory (System)|12.42GB (11.80GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.54.6
cpplint|min|0.1.3
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
cpptools|ms-|1.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

**Comment by isidorn** [comment]
/extCPP

Please tell the CPP extension to use the same dynamic configuration name.
