### ISSUE TITLE
VSCode on Ubuntu 18.04 "create a launch.json file" button does not work (no response)

### ISSUE THREAD

**Issue by NickVH-MS** [microsoft/vscode#121038]
- VS Code Version: 1.55.0 (on Linux running in WSL2 container)
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install Ubuntu 18.04 on WSL2
2. Manage to get snap store working
3. Set up X11 forwarding
3. Install VSCode
4. Run 'code' to launch in X11 window
4. Open folder on my particular huge tented project directory
5. Go to debug and click "create a launch.json file"

Sadly "create a launch.json file" seems to be a completely busted control and will not open.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Can you reproduce this just in plain Ubuntu? Not under WSL?
Can you reproduce with VS Code insiders https://code.visualstudio.com/insiders/

Sorry but your steps are too specialised and I do not have that setup on my machine to investigate more.
You could investigate by F1 > developer tools > place a breakpoint [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L556) and see what is going on
