### ISSUE TITLE
Simple Browser not working when running from source

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#121028]
Steps to reproduce:

1. Build VS Code from source using Insiders
2. Launch Code - OSS Dev, either from Debug or from `.\scripts\code`
3. Open Command Palette, run `Simple Browser: Show` and enter a URL such as http://localhost

![image](https://user-images.githubusercontent.com/6726799/114286409-5347a000-9a56-11eb-89a1-81ebda232588.png)

Toolbar icons are missing and page doesn't load.

Resolve the problem by copying `codicon.css`, `codicon.ttf` and `index.js` into the extensions\simple-browser\media folder from `C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\simple-browser\media`

Presumably the build task is missing a step.

/assign @mjbvz

**Comment by mjbvz** [comment]
Work for me on MacOS. How are you compiling VS Code? I tested with `yarn watch`

**Comment by gjsjohnmurray** [comment]
Seems to be working for me now. Sorry for the noise. Closing.
