### ISSUE TITLE
Trust badge hides the 'new updates available' badge

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#121068]
Please see the screenshot below

![image](https://user-images.githubusercontent.com/172399/114346338-96436980-9b63-11eb-9ee1-20f81f3db7ed.png)

**Comment by sbatten** [comment]
Showing both is a bug which we have a duplicate for. Showing trust over update is by design.

**Comment by sbatten** [comment]
closing as obsolete, this badge is gone
