### ISSUE TITLE
Add desktop.ini to the default files.exclude list

### ISSUE THREAD

**Issue by tpiekarski** [microsoft/vscode#121006]
Visual Studio Code have a default set of excluded files:
```json
"files.exclude": {
  "**/.git": true,
  "**/.svn": true,
  "**/.hg": true,
  "**/CVS": true,
  "**/.DS_Store": true
}
```

**I would like to ask if we could add desktop.ini (and maybe thumbs.db as well) to this default list?**

desktop.ini files are created by the Windows Explorer when you customize a directory (for example adding a custom icon). For details please refer to [How to Customize Folders with Desktop.ini](https://docs.microsoft.com/en-us/windows/win32/shell/how-to-customize-folders-with-desktop-ini).

This file is imho a counterpart to the already added .DS_Store used on macOS. 
> In the Apple macOS operating system, .DS_Store is a file that stores custom attributes of its containing folder, such as the position of icons or the choice of a background image.
<https://en.wikipedia.org/wiki/.DS_Store>

**Should you agree with me, I would like to provide this little PR as my first one** 😃

**Comment by isidorn** [comment]
While this suggestion makes sense, changing the default can be quite unexpected to some users as some of their files might disappear.
I suggest to leave this open for now and if nobody objects and there are more interested users than we can add it.
Thanks

fyi @bpasero
