### ISSUE TITLE
Hitting CMD-D in the changes dialog on Mac doesn't work with other languages except the default english

### ISSUE THREAD

**Issue by Sevy007** [microsoft/vscode#121057]
- VS Code Version: 1.55.1
- OS Version: MacOS 10.15.7 (19H524)

Steps to Reproduce:

1. Install an additional language for VS Code (I tried with German and French)
2. Create a new tab and enter text
3. Close the tab which brings up the changes dialog
4. Try to not save changes by hitting CMD-D

The last step doesn't succeed. When switching the display language to English it works properly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
We do specify mnemonics properly so this seems like a localization issue to me:

https://github.com/microsoft/vscode/blob/b36bcfe1b4f0f507db9734ac0e20437bcc233fd2/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L130-L134

**Comment by v-mholloway** [comment]
for all other languages the key assigned to "Don't Save" is CMD-N
![image](https://user-images.githubusercontent.com/77055370/134660501-9f8a1ab1-a672-49c8-be9b-e082cdfb46f9.png)

**Comment by v-mholloway** [comment]
@danyeh is there a compelling reason to change this to 'D' for all non-english languages...?

**Comment by danyeh** [comment]
This looks like by design. Each language has a key map to their keyboard layout.

**Comment by Sevy007** [comment]
> for all other languages the key assigned to "Don't Save" is CMD-N
> ![image](https://user-images.githubusercontent.com/77055370/134660501-9f8a1ab1-a672-49c8-be9b-e082cdfb46f9.png)

How can a user see these shortcut assignments?
