### ISSUE TITLE
Native Notebooks - Add cell behavior 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121032]
@joyceerhl
- VS Code Version: 1.56.0 - insider
- OS Version: Windows

Steps to Reproduce:

1. Open new notebook - write any statement in first cell 
2. Leave cursor in first cell
3. Click +Code button 
4. Press enter

Actual Behavior: 
1.  Cursor remains on the first cell and adds a new line in the top cell 

![VSC Add Cell Bug](https://user-images.githubusercontent.com/19276747/114287889-b538e300-9a1f-11eb-989d-84120216d24e.gif)

Expected Behavior: 
1. Jupyter behavior for this scenario is that the cursor disappears from the top cell and when a user presses enter, they go from command mode to edit mode in the added cell. (This is for all versions of adding cell, whether it's using to click the button or 'a', 'b' shortcuts) 

![Jupyter Add Cell](https://user-images.githubusercontent.com/19276747/114287995-84a57900-9a20-11eb-9b0e-96b8232fe838.gif)

**Comment by rebornix** [comment]
I think the proper behavior should be inserting a new cell and also move focus into the editor of the new cell.

**Comment by claudiaregio** [comment]
At first I thought that too, but don't think there is enough to deviate from Jupyter behavior here

**Comment by jilljac** [comment]
@rebornix suggestion makes sense for efficiency, but I think breaking the defined pattern of keyboard shortcuts could be frustrating to customers. I agree with @claudiaregio that we should follow the expected Jupyter behavior here and look for feedback.

**Comment by rebornix** [comment]
@claudiaregio @jilljac thanks for the feedback. Thought about this again and agree that we don't necessarily need to change the behavior here.
