### ISSUE TITLE
Make hyphens uniquely distinguishable from minus signs

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [microsoft/vscode#121134]
It already happened several times to our dev crew that commands have been copied from another program like word or power point where those commands were accidentaly autocorrected to contain a hyphen instead of a minus sign. While everybody knows that it's not the smartest idea to copy commands from such programs, it still happens and the hyphens will find a way into the code where they are very hard to detect (depending on the font).

I suggest to somehow highlight or mark such unusual characters to make errors more obvious to users and save them a lot of trouble.

**Comment by connor4312** [comment]
This is something that the language server of the language you're using should report as a problem so that it's decorated as an error.
