### ISSUE TITLE
1.55 new icon is not updated everywhere on macOS

### ISSUE THREAD

**Issue by bflatmajor** [microsoft/vscode#121114]
- VS Code Version: 1.55.1
- OS Version: macOS 11.2.3

Steps to Reproduce:

Open VS Code, check the icon in Dock, Launchpad and "⌘ + tab" list, it's old.

But it's new in Finder and Spotlight.

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
@bflatmajor please try [clearing your icon cache](https://github.com/microsoft/vscode/issues/101014#issuecomment-808368475) to see if this fixes it. Feel free to open a new issue if other things come up.
