### ISSUE TITLE
Editor markdown link hover doesn't display correctly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121113]
Text: `- ![picture 1](../images/f7d2a6760719b8c0ade9c8f0ecd77b6015a330d0ecd53e768c5fddbd4cf2f218.png)  `

Pasted in via https://marketplace.visualstudio.com/items?itemName=hancel.markdown-image

![image](https://user-images.githubusercontent.com/2193314/114421588-4ddb7a00-9b6a-11eb-8ec4-de3ba1bef531.png)

**Comment by hantatsang** [comment]
Sorry, what's exactly wrong? I don't see the same issue:

![2021-04-14 11_21_00-TEST md - 121113-editor-markdown-link-incorrect - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/11912225/114640805-2fb17d80-9d14-11eb-9689-074ee9506a7b.png)

**Comment by mjbvz** [comment]
I'm also not able to reproduce this on MacOS

@Tyriar Could this be one of the extensions you have installed?
