### ISSUE TITLE
Search editor does not render box for Context Lines

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121193]
1. yarn web
2. safari or Chrome
3. Search view, click on the "Open Search Editor from View"
4. Notice how the Context Lines does not render a border

Bonus bug1: that action should be called "Open Search Editor", the user does not care from where it is being called.

Bonus bug2: the up / down chevron is not rendered on iPad

![Screenshot 2021-04-13 at 17 39 25](https://user-images.githubusercontent.com/1926584/114580524-35a94f00-9c7f-11eb-86ac-bbee5c612644.png)

**Comment by JacksonKearl** [comment]
Does iPad OS typically render up/down arrows for numeric inputs? That's a browser default UI, not something I implemented.

**Comment by isidorn** [comment]
Not sure about that, I am a new iPad user. Will let you know once I figure it out.

**Comment by JacksonKearl** [comment]
I verified plain numeric inputs do not render additional controls on iPadOS, and curiously plain numeric inputs do not render a border on desktop Safari:
![image](https://user-images.githubusercontent.com/8586769/114600149-e21c0e80-9c48-11eb-82c4-1bcd04908294.png)

**Comment by isidorn** [comment]
Agree for the arrows. Thanks for looking into this.

**Comment by isidorn** [comment]
Looks better with the border -> verified
