### ISSUE TITLE
Notebooks output not working in code spaces 

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#121168]
Version: 1.56.0-insider
Commit: 58186680eb97fe979e1d986bcfa983ab0a6228e4
Date: 2021-04-06T10:32:31.104Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68

Relates to #120409

Steps to Reproduce:

1.In code space insider I open the notebook from [here](https://github.com/dotnet/interactive/blob/main/samples/notebooks/csharp/Docs/HTML.ipynb)
2.run all cell

I get this 

![image](https://user-images.githubusercontent.com/375556/114529301-b77a8780-9c41-11eb-8901-2d76cff9f5e3.png)

While the local insiders
with version
Version: 1.56.0-insider (user setup)
Commit: 845efe5d8e31079cc858131c95c36103d9439e74
Date: 2021-04-09T09:50:06.816Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

produces this
![image](https://user-images.githubusercontent.com/375556/114529458-ded15480-9c41-11eb-8e73-5d7046a8f399.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by colombod** [comment]
@rebornix I still face same issue with this notebook as I did for issue  #120409

**Comment by rebornix** [comment]
I'll follow up with @joaomoreno on this.

**Comment by colombod** [comment]
I see the notification and then trust the notebook

**Comment by colombod** [comment]
Still I get this
![image](https://user-images.githubusercontent.com/375556/114575337-fa545380-9c71-11eb-8c71-0daf368cbe3b.png)

**Comment by colombod** [comment]
Forcing reload the window and disabling cache fixed the issue
