### ISSUE TITLE
Duplicate launch configuration are shown in debug dropdown

### ISSUE THREAD

**Issue by lolodi** [microsoft/vscode#121148]
- VS Code Version: 1.55.1
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

Don't know how I got in this state, I tried to repro without success.
![image](https://user-images.githubusercontent.com/18540925/114478174-8a32c880-9bb2-11eb-96b5-89a089564c63.png)

The launch.json has only one instance of Run Script: dev with Kubernetes, but in the debug dropdown it is shown twice (the bottom one doesn't work and seems to be pointing to something no longer existing).

This inconsistency persist across machine reboots and profile deletion and recreation.

Does this issue occur when all extensions are disabled?: Yes

**Comment by weinand** [comment]
@isidorn since we are seeing more of these, do you have an idea what the problem is?

IIRC, we are persisting dynamic launch configs with their name and their owning extension. In this case the name is identical and I assume that the extension ID did not change.

**Comment by isidorn** [comment]
I am not sure what changed here. But seems like it broke.

@lolodi do you have some steps for which I could reproduce this? Maybe a repo that I could clone and see this issue on my machine?

**Comment by panjiang** [comment]
The same problem in Golang. All my configurations in launch.json were copied into `automatic debug configurations`.

![Screenshot 2021-04-15 111650](https://user-images.githubusercontent.com/5714950/114809465-d06b7000-9ddc-11eb-8dd7-3493b716cac7.png)
![Screenshot 2021-04-15 111817](https://user-images.githubusercontent.com/5714950/114809468-d2353380-9ddc-11eb-9f97-fc844d51ecde.png)

**Comment by lolodi** [comment]
@isidorn unfortunately I tried multiple to repro it on the same machine with different projects, and with different machines with the same without success. I don't know how I got in this situation..

**Comment by miversen-mwl** [comment]
![image](https://user-images.githubusercontent.com/81823947/114884048-11f31f80-9dcb-11eb-8e00-d1cf68e0269f.png)

I am seeing the same issue. Is there any additional information that can be provided to help with this? This issue cropped up after I updated to the most recent version of Visual Studio Code

**Comment by xiaoxinw** [comment]
I'm running into the same issues with Python debug configuration.

**Comment by xiaoxinw** [comment]
> I'm running into the same issues with Python debug configuration.
> Version: 1.55.2 (user setup)
> Commit: [3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d)
> Date: 2021-04-13T09:35:57.887Z
> Electron: 11.3.0
> Chrome: 87.0.4280.141
> Node.js: 12.18.3
> V8: 8.7.220.31-electron.0
> OS: Windows_NT x64 10.0.19042

When I use the same environment and same machine to open a new project and create a new launch file for this new project, it seems that everything is fine, no duplicate entries, it is very strange.

**Comment by asteinba** [comment]
Also the same for me in a ASP .NET Core (devcontainer) project:
![image](https://user-images.githubusercontent.com/28343566/115526157-0b175180-a290-11eb-8b61-947d9dbb7eb5.png)

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.13-200.fc33.x86_64
```

**Comment by hashier** [comment]
Steps to reproduce in https://github.com/microsoft/vscode-remote-release/issues/4926

**Comment by hashier** [comment]
Callstack looks the same for both at https://github.com/microsoft/vscode/blob/2f077172cb0fcbd06f5820b0a5125215e8d38435/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L260

![image](https://user-images.githubusercontent.com/92332/115775942-d3a1c580-a3b3-11eb-8a7f-4f92f7bb527e.png)

**Comment by isidorn** [comment]
@hashier I meant try to do some debugging if you can. F1 > toggle developer tools  > sources > put breakpoint where I specified. Reload. Investigate once breakpoint gets hit

**Comment by wvolkov** [comment]
I have the same issue on VS Code 1.55.2:
![image](https://user-images.githubusercontent.com/49549154/115843247-4b5d0800-a427-11eb-94d9-5a89fc4b662f.png)
One may mention here, that I am using WSLv2 with Ubuntu 20.04.
Problem appeared after nearest update with VS Code.

What didn't help:
- erasing and complete recreating of `launch.json` file
- `ctrl`+`shift`+P -> `Developer: Reload Window`

**Comment by hashier** [comment]
@isidorn Yes I know. That's what I did and how I got the call stacks.

Unfortunately do I not have any experience with Electron nor TS and I had hoped a call stack might shine at least some light into it by showing what the path was to get the brkpoint triggered. I guess since the call stack is the same it doesn't look like directly like a cache vs config parse.

If I have some time on the weekend I might try again but I doubt I find anything helpful since I have literally zero experience with web development.

**Comment by lynn-orrell** [comment]
I'm running into the same issue as well. For me, it _**only**_ happens when opening a project in WSL2 as shown by the screenshots.

![image](https://user-images.githubusercontent.com/2810722/116165946-86c73300-a6c2-11eb-80cf-d183ef1d6f8c.png)

![image](https://user-images.githubusercontent.com/2810722/116165974-99da0300-a6c2-11eb-9e33-30c3f70ba0f9.png)

**Comment by isidorn** [comment]
Thanks @lynn-orrell for sitting down with me and helping me debug this problem.
I have pushed a potential solution for this I would ask anyone who is willing to help to try out vscode insiders tomorrow and try to reproduce the issue and let me know how it goes.

The current fix is intended as a way to stop this from happening again, it unfortunately does not fix it for the folders which already have the duplication.
Once somebody confirms that on insiders this looks good I can look into introducing some command which would clear the duplication.

**Comment by isidorn** [comment]
Just a friendly ping if somebody had a chance to try out latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by wvolkov** [comment]
@isidorn just tried insiders, now it seems to work well both for launch.json and tasks.json - no more duplicates:
|`launch.json`|`tasks.json`|
|---|---|
|![image](https://user-images.githubusercontent.com/49549154/116410299-4cce6c00-a83d-11eb-99a8-66dbfd75768c.png)|![image](https://user-images.githubusercontent.com/49549154/116410335-57890100-a83d-11eb-9a6c-040dd5a6ad9c.png)|

**Comment by isidorn** [comment]
@wvolkov that is great news, thanks for trying. Based on your comment adding verified label.
If somebody sees it not working please let me know.

Now as I said in my previous comment, this will not fix the workspaces which you already opened and had duplicates for.
For now I suggest the following workaround once the next stable is out in 7 days. Delete the local storage. This will loose some UI state but nothing too drastic. Here's the location's


```
Windows: C:\Users\<userid>\AppData\Roaming\Code\Local Storage
Linux: /home/<userid>/.config/Code/Local Storage
macOS: /Users/<userid>/Library/Application Support/Code/Local Storage
```

**Comment by lynn-orrell** [comment]
I can confirm as well... No more dupes! Nice work, @isidorn!

**Comment by isidorn** [comment]
@lynn-orrell thanks for help again 👏

**Comment by enjustli** [comment]
> @wvolkov that is great news, thanks for trying. Based on your comment adding verified label.
> If somebody sees it not working please let me know.
> 
> Now as I said in my previous comment, this will not fix the workspaces which you already opened and had duplicates for.
> For now I suggest the following workaround once the next stable is out in 7 days. Delete the local storage. This will loose some UI state but nothing too drastic. Here's the location's
> 
> ```
> Windows: C:\Users\<userid>\AppData\Roaming\Code\Local Storage
> Linux: /home/<userid>/.config/Code/Local Storage
> macOS: /Users/<userid>/Library/Application Support/Code/Local Storage
> ```

if you use vscode remote ssh, you will need to delete 
>```
> Windows: C:\Users\<userid>\AppData\Roaming\Code\User\workspaceStorage\<some id>
>```
