### ISSUE TITLE
Blank setting page on Web

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121147]
Currently seeing this on Codespace (switched the bits to Insiders)
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/876920/114477306-ded54400-9bb0-11eb-9d81-7eb8db0f4b3d.png">

**Comment by rebornix** [comment]
and once opened the page, enter stopped working as it always matches the setting page inptubox command.

**Comment by roblourens** [comment]
Just fixed in https://github.com/microsoft/vscode/issues/120939
