### ISSUE TITLE
Double selection weirdness when selecting with mouse

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121104]
iPad
Select some text with the mouse
After some time notice the selection being weirdly rendered. As if the native selection was also visible

Triggering a context menu while the selection is there might help repro this issue.
@rebornix are we doing something special for the editor selection that might cause this

![CC143917-71F0-4793-B4FE-BC5B4BA96E5C (1)](https://user-images.githubusercontent.com/1926584/114408946-391ed680-9baa-11eb-9389-927011494ba2.png)

**Comment by rebornix** [comment]
We select text in the hidden/small textarea too, I wonder if that contributes to this weird behavior.

**Comment by isidorn** [comment]
Oh it is not that, I just tried disabling the hidden textarea selection and I could still reproduce.
It looks like we still have native selection enabled visually, and we should just disable it. Do you know where and how we disable this for VS Code desktop? Maybe this approach does not work for iPad and we need something else.

**Comment by TylerLeonhardt** [comment]
I can't repro this issue anymore. Closing and will have a 2nd person verify just to double check
