### ISSUE TITLE
Failed to run build tasks when local area network only - Web or Remote

### ISSUE THREAD

**Issue by kkocdko** [microsoft/vscode#121116]
- VS Code Version: 1.55.1 | server-win32-x64-web/stable
- OS Version: Windows 10 x64 | Chrome/89.0.4389.90

First, is this build edition has offical support? It's not shown on the official website. I just download it from <https://update.code.visualstudio.com/latest/server-win32-x64-web/stable>

Steps to Reproduce:

1. Run `server.bat`, cut off the internet connect, open address.
2. Open a workspace which has `.vscode/tasks.json`, then Menu > Terminal > Run Build Task.
3. Status bar display `Activating Extensions...` and disappear. Nothing else happen.

Like this:
![image](https://user-images.githubusercontent.com/31189892/114423011-59ba5100-9be9-11eb-996d-2809d937a8ef.png)

Does this issue occur when all extensions are disabled?: 
This flag seems not avaliable for web server? I tried: New installed Chrome + New VSCode Web Server.

The DevTools display these url was timeout (because no Internet):
```
https://default.exp-tas.com/vscode/ab 
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json 
```

But when I connect the Internet, then block these domain using fire wall, everything well! Confusing...

**Comment by alexr00** [comment]
@alexdima is this a scenario that we're trying to support?

**Comment by alexdima** [comment]
This configuration is currently not supported.

**Comment by kkocdko** [comment]
The problem is in build config, not in this repo. The `webEndpointUrl` was set to `https://vscodeweb.azureedge.net`.
I wrote a patch to fix:
```js
modify.replaceText("out/vs/workbench/workbench.web.api.js", [
  { search: /webEndpointUrl:.+?\"/g, value: 'webEndpointUrl:"http://localhost:8109"' },
  { search: "+=`/${this._productService.commit}`", value: "+=``" },
  { search: "+=`/${this._productService.quality}`", value: "+=`/static`" },
]);
```

For temporary solution.
