### ISSUE TITLE
Unable to copy from HTML output of a Notebook

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121115]
- Version: 1.56.0-insider
- Commit: 01466cf692c3e54f0eeb82ef0539a42391f185de
- Date: 2021-04-12T05:14:36.459Z
- OS: Darwin x64 20.3.0

Steps to Reproduce:

1. Install Jupyter Extension
2. Run  the following cell
```
%%html
<div>Hello World</div>
```
3. Try to copy the output `Hello World`, and it doesn't work.

I'm certain I've seen a duplicate, but couldn't find this.
Also I believe this is a regression.

@rebornix /cc 

Does this issue occur when all extensions are disabled?: N/A

**Comment by rebornix** [comment]
I believe this is a regression.
