### ISSUE TITLE
Update to use Webpack 5 for bundling built-in extensions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#121145]
Related to #121144 

We are currently using webpack 4 for bundling our built-in extensions. This will cause issues as we start using compiling to JavaScript that [uses constructs like option chaining](https://github.com/webpack/webpack/issues/10227)

[Webpack 5 release notes](https://webpack.js.org/blog/2020-10-10-webpack-5-release/)

**Comment by jrieken** [comment]
I have merged #127874 which adopts webpack5 and updates lib/target TS config for extensions

**Comment by jrieken** [comment]
Turns out this breaks `yarn compile-web`. This doesn't run during CI and therefore went unnoticed... Adopting webpack 5 seems to be a bigger effort because there is no more automatic polyfilling
