### ISSUE TITLE
Allow to configure auto save per workspace

### ISSUE THREAD

**Issue by jskrepnek** [Microsoft/vscode#1211]
Version: 0.10.3

Auto save is either enabled or disabled for all open Code instances.  

In my case, I would like the setting simultaneously enabled in a window for a Go workspace, but not enabled in a window for a Web-based workspace watch by a live-reload server.

Suggest it be a setting that can be set at the user and workspace levels.

**Comment by egamma** [comment]
So my preference would be that auto save can also be enabled in the web-based workspace by making it less 'aggressive'. See  also #353 and #1055.

@bpasero fyi

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
This has landed and will be available in the January release. Two new settings are available: `files.autoSaveAfterFocusChange` and `files.autoSaveAfterDelay`.
