### ISSUE TITLE
Need status bar item for notebook cell selections

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#121194]
In the text editor, I get this status bar item which gives me some context for the cursor and selection.

![image](https://user-images.githubusercontent.com/323878/114582335-58167a80-9c35-11eb-846c-f47b8ff63576.png)

I want the same thing for the notebook editor. If I have focus on the 5th cell and 3 are selected, it would say `Cell 5 (3 selected)`

**Comment by rzhao271** [comment]
I'm clicking around and the numbers aren't updating consistently.
For example, sometimes the first cell would say Cell 1, but other times it'd say Cell 6.
I tested with the file `.vscode\notebooks\api.github-issues`

**Comment by roblourens** [comment]
Thanks @rzhao271 it was working reliably when using keyboard, but not mouse...
