### ISSUE TITLE
Expose a counterpart of `Uri.toJSON`

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121198]
Serializing objects with `Uri`s is a bit tricky today, because the `Uri` class has a `toJSON` method on it which changes the serialization behavior of `JSON.stringify` even if you are using the `replacer` feature (since the `toJSON` method will be called before the value is passed to the replacer). So it would be nice to expose a counterpart of `Uri.toJSON`, say `Uri.fromJSON` or something like that to make using `JSON.parse` with a `reviver` easier to handle.

/cc @jrieken

**Comment by jrieken** [comment]
> So it would be nice to expose a counterpart of Uri.toJSON, say Uri.fromJSON or something like that to make using JSON.parse with a reviver easier to handle.

In any case you need some kind of marker on the serialised object which tells you how to inflate it, right? That's why we have the `$mid` property or is your data structure static that you know at which property to expect a URI?

**Comment by eamodio** [comment]
Yeah, I look for known properties that are Uris

**Comment by eamodio** [comment]
I added the following to vscode.d.ts

```ts
/**
 * Create an URI from its component parts
 *
 * @see {@link Uri.toString}
 * @param components The component parts of an Uri.
 * @return A new Uri instance.
 */
static from(components: { scheme: string; authority?: string; path?: string; query?: string; fragment?: string }): Uri;
```

**Comment by jrieken** [comment]
Just noticed that we don't validate URI created like that: https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/common/uri.ts#L166

I believe we do that to make parsing faster but in this case we should add the check again
