### ISSUE TITLE
DocumentSymbolProvider does not work with VirtualDocuments

### ISSUE THREAD

**Issue by iantbutler01** [microsoft/vscode#121120]
Issue Type: <b>Bug</b>

1. Register a custom DocumentSymbolProvider for the language of your choice in this case we chose python (we tried with scheme: 'our custome scheme' and without).

2. Open a VirtualDocument provided by TextDocumentContentProvider, registered with a custom uri scheme.

 -The symbol provider will do nothing.

3. Open a local python file

 -The symbol provider will work.

I would love to see the DocumentSymbolProvider work with VirtualDocuments, especially because the documentation explicitly says document providers from VirtualDocuments are first class elements. I opened this as a bug because given that explicit mention I'd imagine this isn't working as intended.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:01:24.315Z)
OS version: Linux x64 5.8.0-7625-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|15.10GB (0.76GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 0ba0548d-5743-4a54-9c93-3810b6841207|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-django|bat|1.6.0
vscode-eslint|dba|2.1.19
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
scala-lsp|dra|0.2.3
gitlens|eam|11.4.0
tsl-problem-matcher|eam|0.4.0
prettier-vscode|esb|6.3.2
vscode-firefox-debug|fir|2.9.3
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
shell-format|fox|7.1.0
gitlab-workflow|Git|3.17.1
beautify|Hoo|1.5.0
Scala|itr|0.1.7
language-julia|jul|1.1.38
vscode-sshfs|Kel|1.20.0
vscode-sbt-scala|lig|0.2.4
MagicPython|mag|1.1.0
vscode-elixir|mjm|1.1.0
theme-monokai-pro-vscode|mon|1.1.19
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.11.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
cpptools|ms-|1.2.2
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
vscode-extension-auto-import|Nuc|1.4.3
vscode-jest|Ort|3.2.0
vscode-css-peek|pra|4.1.3
ruby|reb|0.28.1
vscode-elixir-formatter|sam|0.2.0
scala|sca|0.5.2
vscode-fileutils|sle|3.4.5
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.12
vim|vsc|1.19.3
quokka-vscode|Wal|1.0.354
jinja|who|0.0.8
vscode-ruby|win|0.28.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by iantbutler01** [comment]
My comment in that potential duplicate was marked off topic so I then opened this issue FWIW.

**Comment by iantbutler01** [comment]
I also just gave it a try on insiders and no luck there either.

**Comment by jrieken** [comment]
Extension register their language feature per scheme, like `file` or `vscode-remote`. Often language extensions only support the `file` scheme because the underlying tools operate with files on disk and therefore virtual documents cannot be supported.

**Comment by iantbutler01** [comment]
@jrieken Then virtual documents should be removed as first class elements from the documentation. How does this function across virtual file systems from ssh?
