### ISSUE TITLE
The connection to the terminals pty host process is unresponsive, the terminal may stop working.

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#121112]
Issue Type: <b>Bug</b>

the terminal very often stops working.
it wont start often
![image](https://user-images.githubusercontent.com/9264813/114420479-fc66d580-9bd1-11eb-9d45-59d62fd2bc4c.png)

VS Code version: Code - Insiders 1.56.0-insider (01466cf692c3e54f0eeb82ef0539a42391f185de, 2021-04-12T05:17:32.143Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.01GB free)|
|Process Argv|--crash-reporter-id 340e0eb9-5b34-4206-9e2e-bd86fc3b2cf3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
vscode-pull-request-github|Git|0.25.0
output-colorizer|IBM|0.1.2
vscode-dotnet-runtime|ms-|1.0.0
github-issues-prs|ms-|0.9.3
vscode-js-profile-flame|ms-|0.0.14
fabric8-analytics|red|0.3.2
java|red|0.76.0
vscode-commons|red|0.0.4
vscode-xml|red|0.15.0
vscode-yaml|red|0.17.0
vscode-checkstyle|she|1.4.0
swdc-vscode|sof|2.5.11
sonarlint-vscode|Son|1.21.0
code-spell-checker|str|1.10.2
rest-book|tan|0.3.2
vscodeintellicode|Vis|1.2.12
vscodeintellicode-insiders|Vis|1.0.6
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebutton:30280634
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2ct:30286873

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by sanket-bhalerao** [comment]
@meganrogge yes i can reproduce it in the insiders build.
i have the latest update for insiders. i however don't have a reliable way to reproduce it every time.

details for insiders 
Version: 1.56.0-insider (user setup)
Commit: 94d369e27d19f598228961e9feb0413f2edabe5d
Date: 2021-04-14T12:07:54.328Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Nisarg01-01** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

can you please help me with this statement as i m facing same issue "I believe this is already fixed, can you see if you can reproduce in the [Insiders build]"

my vscode details ::
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
