### ISSUE TITLE
Make href independent of file ending semantics.

### ISSUE THREAD

**Issue by Cole-Henrich** [microsoft/vscode#121151]
VSCode allows .html or .htm as file endings for html files, but when you href to (for example) file.html which is actually named file.htm, the link does not work. This is more a theory question, or a lazy request - someone please fix this!

**Comment by aeschli** [comment]
So the example is
```
<html>
<body>
	<a href="./x.htm"></a>
</body>
</html>
```

You are saying the link does not work because the file on disk/on the server is named `x.html` not `x.htm`?

**Comment by Cole-Henrich** [comment]
Correct! Thanks for considering this feature-fix.

**Comment by hardikshah197** [comment]
Shall I take up this issue? If it isn't resolved @Cole-Henrich
