### ISSUE TITLE
Terminal Tabs: Selecting a split terminal tab will only focus the split, not show the tab

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121172]
Repro:

With a setup like this:

![image](https://user-images.githubusercontent.com/2193314/114538304-17ecd300-9c08-11eb-888c-bd7e22a67e27.png)

The task split panes only work when either one of them is already visible.

**Comment by meganrogge** [comment]
Fixed by 

https://github.com/microsoft/vscode/blob/9cd8ff410e594d937723b7e75608d0af7eb77cd0/src/vs/workbench/contrib/terminal/browser/terminalTabsWidget.ts#L98-L111

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-04-edae2958-9d1d-42e0-becf-5edd019c65c6.gif)

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-04-a16b044a-766d-4989-94cf-6660dfc1901c.gif)

**Comment by connor4312** [comment]
Actually this might be the same as https://github.com/microsoft/vscode/issues/121282, hard to tell

**Comment by Tyriar** [comment]
Yep, same root cause
