### ISSUE TITLE
Put trusted/untrusted folders into single table

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121185]
* open workspace trust editor
* notice how there is a section for trusted/untrusted which identical wording and UI

Instead of the duplication the trust state should be inline, like a check box in front of a row or some toggle button as new trust column

<img width="864" alt="Screenshot 2021-04-13 at 16 24 18" src="https://user-images.githubusercontent.com/1794099/114568768-b6af1900-9c74-11eb-89e2-2729e2369ce1.png">

**Comment by lszomoru** [comment]
By getting rid of the `Unspecified` state, users will only have to manage one list of folders - "trusted folders".

**Comment by jrieken** [comment]
> All locations that are not covered by the list of trusted folders will default to 'Untrusted`.

I don't think that will work. I have trusted `/Users/jrieken/Code` but _untrusted_ `/Users/jrieken/Code/_samples` and I don't see how that will work with a simple trusted list

**Comment by jrieken** [comment]
> Yes this removes some fancy folder structures but it makes the question much simpler... where do you put your trusted source

I strongly disagree with this attitude. This already worked and a UI for this isn't rocket science. On the other hand we pushing a very disruptive change onto our users and our best answer shouldn't be that you need to move your folders around. I think this would have been acceptable when VS Code had started like that but given we are years into the project we shouldn't be that bold and more supportive to existing and working setups

**Comment by lszomoru** [comment]
@jrieken, sorry for not getting back to you on this until now. My hypothesis is that your response is mostly fuelled by the fact that something that was there, which was then taken away. If we would have shown workspace trust without the capability to specify untrusted folder, I am fairly confident that you wouldn't have had such a strong reaction. 

I am adding the `feature-request` label to the issue and will be looking out for similar requests in the future.

**Comment by jrieken** [comment]
> If we would have shown workspace trust without the capability to specify untrusted folder, I am fairly confident that you wouldn't have had such a strong reaction.

The attitude is causing my reaction. The old model really matched to how my source files are organised on disk. All source is `~/Code/`, random/untrusted stuff is in `~/Code/_samples`, "untrusted" extensions are in `~/Code/_allExtensions`. I wanna trust everything in `~/Code/` except for those two folders. 

<img width="701" alt="Screenshot 2021-04-23 at 19 09 31" src="https://user-images.githubusercontent.com/1794099/115906168-77987900-a467-11eb-8429-9a8f95b69f75.png">

I don't believe I am the only user of VS Code with such a structure and I don't understand the resistance to support such a cases. Sure, moving folders around is easy but I will lose my history of recent files/folders and I am not accepting that. Also, generally, VS Code should adapt to my setup and not the other way around.

**Comment by lszomoru** [comment]
Closing this issue in favor of #126311 which already received the necessary community votes.
