### ISSUE TITLE
failed to connect to remote extension

### ISSUE THREAD

**Issue by TinoFels** [microsoft/vscode#121103]
Issue Type: <b>Bug</b>

Just starting up VSC under WSL.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042
Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (22.92GB free)|
|Process Argv|--crash-reporter-id fd7d7308-606b-4f1b-a8b1-ccd32c1c6146|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'WSL: Ubuntu-18.04' failed: WebSocket close with status code 1006
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by aeschli** [comment]
Can you paste the WSL log here (Command: Remote-WSL: Show Log)?

**Comment by aeschli** [comment]
@alexdima Do you know more about the error `WebSocket close with status code 1006`?

**Comment by alexdima** [comment]
@TinoFels Are you using proxies?
