### ISSUE TITLE
(<%- %>) ejs syntax not working properly 

### ISSUE THREAD

**Issue by Fantasy618** [microsoft/vscode#121111]
const campground = <% - JSON.stringify(campground) %>
giving This Error text :-  Expression expected.
![2021-04-12 (2)](https://user-images.githubusercontent.com/56129994/114419179-d7be2e00-9bd0-11eb-9e55-978003c1b3b5.png)
![2021-04-12 (3)_LI](https://user-images.githubusercontent.com/56129994/114419206-dd1b7880-9bd0-11eb-8695-e4d81b9833e9.jpg)

**Comment by aeschli** [comment]
The HTML language extension only supports HTML, but not the syntax added by languages like EJS.

You can either look out for an extension that understands the EJS file syntax, or disable script validation in html:

`"html.validate.scripts": false`

Dupliate of #51118

**Comment by Varsha2629** [comment]
Hi, 
I have the Same Error But I add this script but It would not be helping me could you tell me how can I fix it. if you have done.

Thanks in Advance.
