### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ntthang-dev** [microsoft/vscode#121122]
- Issue Type: `Bug`
- Extension Name: `github-authentication`
- Extension Version: `0.0.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by RMacfarlane** [comment]
@ntthang-dev This issue is missing data, please paste the diagnostic information. It would also be helpful if you could describe what you were doing when this happened

**Comment by ntthang-dev** [comment]
Thank you for your help! In this problem I myself 😍 do not know what really happened on my VSCode😥, a message appears that my GitHub extension on VSCode is having a problem😵 as far as I can see it is related to the problem of starting VSCode 🤔. And I got a suggestion from my own IDE to report this bug 😭. Thank you. 😄
