### ISSUE TITLE
Why does going from unspecified to untrusted require a restart?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121110]
I clicked don't trust and it says it needs to restart? No extensions should have been enabled at this point?

![image](https://user-images.githubusercontent.com/2193314/114418659-95143b80-9b67-11eb-8c9f-76d27f881028.png)

**Comment by Tyriar** [comment]
Also clicking yes didn't restart 😕

**Comment by sbatten** [comment]
likely will just be fixed when we remove the unspecified state

**Comment by lszomoru** [comment]
The unspecified state has been removed, and transitioning from Trusted to Untrusted does not require a reload any more.

**Comment by mjbvz** [comment]
Marking as verified based on  https://github.com/microsoft/vscode/issues/121110#issuecomment-821525648
