### ISSUE TITLE
Shrinking item in previous viewport scrolls the list view

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121140]
Issue Type: <b>Bug</b>

* Open `api.github-issues` in a relative small viewport
* Run the second code cell
* Scroll it out of view
* Clear all outputs
* The view scrolls upwards a little bit

@joaomoreno we wrote this together near a year ago but not sure why I didn't run into this bug before (definitely another bug/defeat in notebook code). It seems the last call `this._rerender(this.lastRenderTop, this.lastRenderHeight);` will scroll the view upwards a bit but not sure why 

https://user-images.githubusercontent.com/876920/114461648-d6700f80-9b96-11eb-89c8-b4cc92cced32.mov

Ignore the flicker, it's a different issue of the custom markdown renderer (and has nothing to do with List View).

VS Code version: Code - Insiders 1.56.0-insider (Universal) (01466cf692c3e54f0eeb82ef0539a42391f185de, 2021-04-12T05:14:36.459Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (54)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.1
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.1.6
kusto|don|0.0.9
gitlens|eam|11.4.0
codespaces|Git|0.9.2
vscode-pull-request-github-insiders|Git|2021.4.16384
vscode-fluent-icons|mig|0.0.1
theme-monokai-pro-vscode|mon|1.1.19
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestaticwebapps|ms-|0.5.0
vscode-docker|ms-|1.11.0
vscode-language-pack-zh-hans|MS-|1.55.2
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.0.0
vscode-dotnet-sdk|ms-|0.3.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.6.740555125
notebook-renderers|ms-|0.0.1
remote-containers|ms-|0.167.0
remote-ssh-edit-nightly|ms-|2021.4.8100
remote-ssh-nightly|ms-|2021.4.8100
azure-account|ms-|0.9.8
hexeditor|ms-|1.5.0
js-debug-nightly|ms-|2021.4.717
powershell-preview|ms-|2021.4.1
vscode-github-issue-notebooks|ms-|0.0.76
vscode-markdown-notebook|ms-|0.0.16
vscode-notebook-history|ms-|0.0.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.1.0-dev
debugger-for-chrome|msj|4.12.12
geo-data-viewer|Ran|2.4.0
toggle|reb|0.0.1
java|red|0.76.0
kuskus-extensions-pack|ros|1.0.1
kuskus-kusto-language-server|ros|1.0.1
kuskus-kusto-syntax-highlighting|ros|1.1.8
vsc-nwjs|rua|1.0.18
rust|rus|0.7.8
luna-paint|Tyr|0.4.0
sourcekit-lsp|unp|0.0.1
vscode-lldb|vad|1.6.1
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.2
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.28.0
notebook-editing|vsc|1.0.0
vscode-test-resolver|vsc|0.0.1

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoccf:30278406
vsc_aa:30263845
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30280636
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by joaomoreno** [comment]
@rebornix After almost an hour I feel like I'm nowhere close to even finding out why this happens. Something very fishy is indeed happening here.

I also don't find any fault in the following line:

https://github.com/microsoft/vscode/blob/ee2fd0ea637f735eb13a20f03687edd507b3657d/src/vs/base/browser/ui/list/listView.ts#L415-L415

If you step through the code, that rerender call won't do a thing: no item requires probing for a new height, so no changes happen. Then, you press `Play` and the thing jumps.

I can't figure out, from the list view point of view, what is going wrong here.

**Comment by rebornix** [comment]
I'm a bit lucky today, though I don't know why I can't figure this out before. After the first `this.render(lastRenderRange, Math.max(0, this.lastRenderTop + heightDiff), this.lastRenderHeight, undefined, undefined, true);`, `lastRenderTop` is updated but `scrollTop !== renderTop` somehow, so I set `scrollTop = renderTop` again, and it works.

**Comment by joaomoreno** [comment]
Oh wow!
