### ISSUE TITLE
clickable relative paths in OUTPUT panel

### ISSUE THREAD

**Issue by duanyutong** [microsoft/vscode#121130]
Relative paths in the OUTPUT panel (e.g. when building with ninja for an in-source build) are not clickable. When using `make`, paths are absolute and click works. Whether holding down ctrl or not doesn't make a difference.

![image](https://user-images.githubusercontent.com/865317/114436685-9fe4c580-9b93-11eb-9598-c4c5bc6728f7.png)

**Comment by sandy081** [comment]
@isidorn I think you did the link detection here - so assigning to you. Please feel free to transfer to the right owner if you are not owning this.

**Comment by isidorn** [comment]
This does not really have an owner.
It is a fair feature request, and it can stay assigned to me.
