### ISSUE TITLE
"Workspace folder does not exist" when searching within a multi-root workspace window

### ISSUE THREAD

**Issue by rlabrecque** [microsoft/vscode#121142]
Issue Type: <b>Bug</b>

With a workspace like the following:

```json
{
	"folders": [
		{
			"name": "Team/project1",
			"path": "Team/project1"
		},
		{
			"name": "Team/project2",
			"path": "Team/project2"
		}
	]
}
```

When right clicking a folder and hitting "Find in folder" the "files to include" window gets filled with: "./Team/project2"

When entering a search string an error comes up: `Workspace folder does not exist: Tools`

This is likely due to the slash in the name?

VS Code version: Code - Insiders 1.56.0-insider (01466cf692c3e54f0eeb82ef0539a42391f185de, 2021-04-12T05:17:32.143Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor  (48 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (23.17GB free)|
|Process Argv|--crash-reporter-id d4fdf465-eabb-4e65-a042-c70cd5b1475c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 3792)|
|Memory (System)|50.11GB (40.89GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
bracket-pair-colorizer-2|Coe|0.2.0
mustache|daw|1.1.1
remote-containers|ms-|0.167.0
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
remote-wsl|ms-|0.54.6
vscode-icons|vsc|11.4.0
atlascode|atl|2.8.6
vscode-markdownlint|Dav|0.40.3
go|gol|0.24.0
todo-tree|Gru|0.0.211
vscode-cfn-lint|kdd|0.18.0
file-downloader|min|1.0.10
mindaro|min|1.0.120210408
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-kubernetes-tools|ms-|1.3.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.6.740555125
cpptools|ms-|1.2.2
vetur|oct|0.33.1
vscode-yaml|red|0.17.0
even-better-toml|tam|0.12.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfilebuttoncf:30280635
vshan820cf:30276953
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by roblourens** [comment]
Yeah, it's ambiguous with a slash in the workspace folder name: https://github.com/microsoft/vscode/issues/99512
