### ISSUE TITLE
Identify macOS download links

### ISSUE THREAD

**Issue by mwpowellhtx** [microsoft/vscode#121119]
Following up to my [initial question](https://github.com/microsoft/vscode/issues/109329), could I get feedback concerning `macOS` downloads:
- [x] _macOS universal_, `universal`
- [x] _macOS Intel Chip_
- [x] _macOS Apple Silicon_, `arm64`

Thank you...

**Comment by mwpowellhtx** [comment]
So, for instance, an educated guess on my part, correct my if I am wrong, or whether I am missing scenarios here, _specified version_, _latest_, _insider_, in several:

  * `https://update.code.visualstudio.com/1.55.1/darwin-universal/stable`, `https://update.code.visualstudio.com/latest/darwin-universal/stable`, `https://update.code.visualstudio.com/latest/darwin-universal/insider`
  * `https://update.code.visualstudio.com/1.55.1/darwin/stable`, `https://update.code.visualstudio.com/latest/darwin/stable`, `https://update.code.visualstudio.com/latest/darwin/insider`
  * i.e. `https://update.code.visualstudio.com/1.55.1/darwin-arm64/stable`, `https://update.code.visualstudio.com/latest/darwin-arm64/stable`, `https://update.code.visualstudio.com/latest/darwin-arm64/insider`

**Comment by mwpowellhtx** [comment]
Further elaboration, this issue is focused on the `macOS` downloads; IIRC the _Windows_ and _Linux_ downloads are consistent and have not changed.

**Comment by deepak1556** [comment]
https://github.com/microsoft/vscode/issues/121119#issuecomment-817977692 has the correct links, the `{platform}` values mentioned in https://github.com/microsoft/vscode/issues/109329#issuecomment-716479516 for macOS are as follows

```
Universal - darwin-universal
Intel Chip - darwin
Apple Silicon - darwin-arm64
```

hope that clarifies!

**Comment by mwpowellhtx** [comment]
Cool, sounds like my guesses were accurate, then. Thanks!
