### ISSUE TITLE
no more refactor/extract const available for php

### ISSUE THREAD

**Issue by trogne** [microsoft/vscode#121128]
- VS Code Version: 1.55.1
- OS Version: Windows 10
oring

Steps to Reproduce:

1. Right click code in php file
2. Look at the menu : missing "Refactor" and "Extract to const/var" option, as mentioned here : https://code.visualstudio.com/docs/editor/refactoring

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
This isn't supported out of the box, but it may be implemented by one of the PHP extensions

**Comment by trogne** [comment]
Can you tell which extension ?     In the link I provided, it says that "Visual Studio Code supports refactoring operations (refactorings) such as Extract Method and Extract Variable to improve your code base from within your editor.". So it sounds like a "out of the box" feature.

**Comment by roblourens** [comment]
VS Code doesn't implement this for every language in the world. We only provide support for extensions to add language features like this. Support for some languages like TS is included out of the box. I don't know whether any of the PHP extensions implement this or not.
