### ISSUE TITLE
Editor Service shouldn't trigger overrides on existing editors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#121101]
Currently even if the editor exists and is clicked on from the workbench, the editor service will trigger an override. This leads logic in the override opening code which just says "if this is already open ignore it". Focusing the tab etc should just be handled by the editor service / editorGroupView and overrides should not be triggered as no interaction is needed for currently existing editors.

//cc @bpasero

**Comment by bpasero** [comment]
@lramos15 I would say that overrides ideally only happen for untyped editors (e.g. `{ resource: URI }`) and not anything that extends `EditorInput`. That would probably help in a lot of cases, e.g. where an existing editor is opened (from a tab click).

**Comment by lramos15** [comment]
\duplicate #124351
