### ISSUE TITLE
Tree does not support horizontal scrolling using keyboard

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode#121132]
- VS Code Version: 1.55.1
- OS Version: macOS Catalina 10.15.7

Trees are not scrollable when using the keyboard. This is an accessibility problem since keyboard only users will face difficulty getting the information for long file names or when the window is zoomed. 

Steps to Reproduce:

1. Turn on "List: Horizontal Scrolling" in settings
2. Try to use keyboard to horizontal scroll in file explorer

**Comment by rv3392** [comment]
Hi, is anyone currently working on this? If not, I'd be interested in giving it a go.

**Comment by timfenney** [comment]
What should be done here? How should keyboard change focus between:

- different items in the explorer pane
- moving from the pane tree to effecting the scrolling of the container of the tree

How to indicate focus on the container containing the tree (highlighted border?)
How to maintain good a11y and consistency with the rest of the app?
For a11y this might need a bit of thoughtful design.

**Comment by danila-grobov** [comment]
@joaomoreno Hello, I would like to work on this issue. Do you have any insights, where in the code we could change this behavior? I was thinking of making ctrl + arrow keys scroll horizontally.
