### ISSUE TITLE
iPad new action style provides no feedback when action touched

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121192]
Currently we only render the action hover, and when the action gets clicked the hover background nicely changes.
I really like this new flow. However this does not work for the iPad because there is no hover when you are using touch.

What iOS seems to do for native actions is upon click show for 500ms inverted colors on the icon.
What do you think about using this approach for our actions for the iPad?

**Comment by joaomoreno** [comment]
On desktop we currently have styles for: none, hover and active. On touch devices we should just have none and active. If the active isn't working properly, that's a bug. But I would not create yet another style just for touch.

**Comment by isidorn** [comment]
Yeah it seems like the active is not working properly.
@joaomoreno let me know if you would like me to debug this further or if I can help?

**Comment by joaomoreno** [comment]
I can't repro this, I do see action style when clicking them.

**Comment by isidorn** [comment]
@joaomoreno can you double check when touching them?

**Comment by bpasero** [comment]
I see the action feedback when clicking (via touch) but it sometimes decides to not go away until something else is clicked.

**Comment by isidorn** [comment]
Yeah, we are aware of that corner case -> verified

**Comment by joaomoreno** [comment]
Not so much a corner case, we should fix it, feels so ugly. 😢

But at least something is there yeah!

**Comment by isidorn** [comment]
I created this issue so we track it 
https://github.com/microsoft/vscode/issues/125482
