### ISSUE TITLE
About replace to increment "\ n"

### ISSUE THREAD

**Issue by taC-h** [microsoft/vscode#121187]
Version: 1.55.1 (system setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:06:02.360Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create following text file
```

hoge
hoge
```
2. Edit->Replace `\nhoge`regex to `\n\nhoge`
3. Replace (not all)

The cursor remains pointing to the first "\ nhoge".

Does this issue occur when all extensions are disabled?: Yes

**Comment by amunger** [comment]
duplicate https://github.com/microsoft/vscode/issues/149243
