### ISSUE TITLE
M1 VSCode binary can be run on iOS?

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#121169]
- VS Code Version: v1.55.1
- OS Version: macOS 11.3.2

```
Version: 1.55.1
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T15:47:31.580Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0
```

## Steps to Reproduce:

1. Install VSCode via Homebrew via `brew install visual-studio-code`
2. Open Apps info from Storage info

## Actual

Shows **iOS** type

<img width="724" alt="image" src="https://user-images.githubusercontent.com/3511344/114532647-76489e80-9c66-11eb-92a0-aa911f076e8c.png">

## Excepted

Excepting **Apple Silicon** or **Universal**

<img width="904" alt="image" src="https://user-images.githubusercontent.com/3511344/114532816-a85a0080-9c66-11eb-9df3-aefd1d23367d.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by deepak1556** [comment]
Its just an issue with which attribute the storage info queries to decide the kind, the output of `system_profiler SPApplicationsDataType -xml` shows the `arch_kind` is `arch_ios`. I think these look for `CFBundleSupportedPlatforms` attribute and if not present default to the `ios` kind for `arm64` executables.

Given the universal and intel labels show up correctly, and considering the output of other apple silicon apps in the image posted. I don't think this needs a fix, but leaving it open for anyone to address as a good first issue.

**Comment by dalisoft** [comment]
Thank you for response and yes, it is not issue, just question, it is possible port to iPad and iPhone. If it’s possible, it will be amazing

**Comment by deepak1556** [comment]
Not possible, the support needs to come from the runtime for which I don't think there are plans. Closing as such.

However you can use codespaces https://github.com/features/codespaces

**Comment by shd101wyy** [comment]
Not very much related to this issue, but I am now trying to bundle vscode web version as a progressive web application and add some necessary features such as in-memory file system and git. 
Here is the repository: https://github.com/0xGG/vscode-pwa.   
You could try it out in your Safari at http://0xgg.io/vscode-pwa
