### ISSUE TITLE
Python Microphone Problem on Mac

### ISSUE THREAD

**Issue by conconheat** [microsoft/vscode#121182]
- VS Code Version: 1.55.1
- Python Version: 3.8.5

I'm using the library Speech_Recognition and for some reason when I use the line of code that is supposed to turn on the microphone and listen to me. It just goes on forever and I don't know if it isn't listening to me or not because it is supposed to print back the words I said        The line of code---->>>>>          audio = r.listen(source)       The line of code does not put out a error either .    This line of code is where it gets stuck on I also noticed that my microphone in the Mac settings dosen't have vscode as an option to turn on but don't know how to put the app on that list. If anyone could help that would be amazing.

**Comment by lramos15** [comment]
https://github.com/microsoft/vscode/issues/95062 Currently VS Code doesn't have access to your media devices, this is being added to the next version of VS code if you would like to try your code using our insiders version (which is our nightly build) you can find that here https://code.visualstudio.com/insiders/

**Comment by conconheat** [comment]
I did see #95062 the only problem is when I put that in the terminal it spits out an error saying this       zsh: parse error near `)'  and I also tried just putting it in a python file but that put out an error saying it didn't know what cv2 was but I will try the insider version and thanks for the help iramos15

**Comment by conconheat** [comment]
Ohhh My thank you so much it works! I spent so much time researching and all I had to do was get vscode insider thanks
