### ISSUE TITLE
Feature Request: Grouping multi-root workspaces in Explorer

### ISSUE THREAD

**Issue by rlabrecque** [microsoft/vscode#121127]
Hey there, we have a folder structure like:

```
   Build/
      buildteamproject1
      buildteamproject2
   Backend/
     backendproject1
   Tools/
      toolsproject1
      toolsproject2
   Websites/
      somewebsite
```

We've used folder view for a long time, and are switching to multi-root workspaces. The multi-root workspaces feature tends to work much better with extensions and such than just a giant folder view, but one thing that we're missing is the ability to collapse the areas we don't care about.

I wish there was a very light grouping feature with multi-root workspaces, so we could define which group a project was associated with and allow us to collapse them.

Largely the only thing that should change with such grouping is the Explorer view.

This is related to https://github.com/microsoft/vscode/issues/41860 but not quite the same.

Ideally we'd just be able to put in a group in the folder definition inside the .code-workspace file like such:

```json
{
	"folders": [
		{
			"name": "buildteamproject1",
			"path": "Build/buildteamproject1/",
			"group": "Build"
		},
		{
			"name": "backendproject1",
			"path": "Backend/backendproject1",
			"group": "Backend"
		},
	]
}
```

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on our immediate plan. Thus assigning to backlog for now. Thanks

**Comment by rlabrecque** [comment]
For posterity this seems to be a dupe of https://github.com/microsoft/vscode/issues/76904 👍

**Comment by Dini-25** [comment]
+1 for the grouping feature

**Comment by darkguy2008** [comment]
So no grouping this year?
