### ISSUE TITLE
Adopt `wasm-eval` CSP

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#121108]
https://github.com/electron/electron/pull/28535 brings support for using `wasm-eval` in Electron (something so far reserved for Chromium extensions). We should figure out which Electron version brings this support and adopt this instead of [the existing usage of `script-src 'self' 'unsafe-eval'`](https://github.com/microsoft/vscode/blob/765ce34320bf80042faf37ad47bbb1b24411c700/src/vs/code/electron-browser/workbench/workbench.html#L6) which was added only to be able to load WASM.

@deepak1556 How would I find out which precise Electron version contains that change? (The PR is marked `merged/11-x-y`).

cc @bpasero

**Comment by deepak1556** [comment]
It will be available with `11.4.3` and `12.0.3` both of which are not yet released. Will update here once the versions are available.

**Comment by deepak1556** [comment]
@alexdima main branch now has the fix from electron, `wasm-eval` can now be adopted.

**Comment by alexdima** [comment]
@deepak1556 I just tried to use this instead of `unsafe-eval` but get the following error:

![image](https://user-images.githubusercontent.com/5047891/124488707-71504280-ddb0-11eb-8e86-ef988738b927.png)

But event disregarding the `wasm-eval` error, it looks like the web worker extension host wouldn't work without `unsafe-eval`.

So I don't think this is something we can pursue anymore.

**Comment by deepak1556** [comment]
@alexdima `wasm-eval` csp is behind a runtime flag in the current chromium version we are on, the renderer process needs to be constructed with `enableBlinkFeatures: 'WebAssemblyCSP'` in the webPreferences option to use it. For example to use in the shared process renderer, it should be added here https://github.com/microsoft/vscode/blob/0a8a4b380b1da062cbcb352c06ad13fb87e21c12/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L166

**Comment by deepak1556** [comment]
> it looks like the web worker extension host wouldn't work without unsafe-eval.

Quick clarification, is this on the desktop ?

**Comment by alexdima** [comment]
> the renderer process needs to be constructed with enableBlinkFeatures: 'WebAssemblyCSP' in the webPreferences option to use it.

:+1: Thanks for the tip, I didn't know that.

> Quick clarification, is this on the desktop ?

Yes, I've only tested on desktop. The initial idea was to remove `unsafe-eval`, but now we have two consumers, wasm and the web worker extension host (which also executes on the desktop, currently behind a setting `extensions.webWorker`).
