### ISSUE TITLE
Stop debugger shortcut not wokring

### ISSUE THREAD

**Issue by targhs** [microsoft/vscode#121154]
Issue Type: <b>Bug</b>

I don't know how to reproduce this issue but I am not able to stop the running debugger using the keyboard shortcut (Shift + F5).
Tried with no terminal open and with terminal open but its not working for both the cases.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.62GB free)|
|Process Argv|--crash-reporter-id 4477b60a-34b1-4813-aad1-e352af993d95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: TaranQ3|
|OS|Linux x64 5.4.0-65-generic|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 1493)|
|Memory (System)|11.60GB (1.04GB free)|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
fluent-icons|mig|0.0.7
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.1
remote-ssh-edit|ms-|0.65.1
vscode-icons|vsc|11.4.0
gitlens|eam|11.4.0
vscode-docker|ms-|1.12.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.702919634
es6-css-minify|olb|3.3.2
vscode-yaml|red|0.17.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by isidorn** [comment]
This works just fine for me. Can you reproduce with VS Code insiders
https://code.visualstudio.com/insiders/
