### ISSUE TITLE
False positive errors highlighted

### ISSUE THREAD

**Issue by vikramiyer** [Microsoft/vscode#12117]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:05:12.065Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1. Very bad React Native or React support, Javascript Babel language setting shows a lot of red marks which annoyingly appears like an error. Actually it isn't an error, its just a lack of support.
2. Nuclide for Atom has very good support for React has to be ported to vscode.

<img width="532" alt="screen shot 2016-09-16 at 2 52 19 pm" src="https://cloud.githubusercontent.com/assets/287302/18575641/7751b47e-7c1d-11e6-905d-542b0dd48c49.png">

**Comment by bpasero** [comment]
Not sure if this is TS or an extension.

**Comment by waderyan** [comment]
@vikramiyer thank you for brining this to our attention. I am trying to isolate the issue to better aide the bug fixing process. Can you help me?

Copying the code you have provided I am not able to reproduce the issue. Could you provide more context and a simple example I can copy and paste to reproduce? If you can write down the exact steps you follow to reproduce the behavior and the code that will be helpful in getting this fixed.

**Comment by vikramiyer** [comment]
I am using RxJS in my code coupled with ES6 syntax for creating classes for a React Native project

<img width="726" alt="screen shot 2016-09-17 at 9 47 37 am" src="https://cloud.githubusercontent.com/assets/287302/18604130/196516cc-7cbc-11e6-8a81-2fed02fe9284.png">

1. ES6 class used for React Native project template
2. In a function method I have defined a const of RxJS streams and using the spread operator to combine the stream values. 
3. On tooltip error highlight I get this error

     `[js] 'property declarations' can only be used in a .ts `file.`
    `(property)` Home.roomStream: any`

4. File type association is Javascript(Babel). I do not have any ESLint or JSHint extensions installed.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11008
