### ISSUE TITLE
[remote] race between terminal create and initial resize

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#121270]
If create/attach/start requests take too long then initial term resize event is missed. It would be good to delay initial resize if `TerminalProcessManager.createProcess` was already called.

Below you can see that initial sizes 80 than they should be 110 columns (triggered by explicit resize later):

<img width="841" alt="Screenshot 2021-04-14 at 11 13 52" src="https://user-images.githubusercontent.com/3082655/114685842-828a3580-9d12-11eb-8712-6661adfd9b2e.png">

**Comment by Tyriar** [comment]
Repro steps in https://github.com/microsoft/vscode/issues/120136
