### ISSUE TITLE
Menu selection not rendered correctly on iPad

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121201]
iPad, I can repro both on Chrome and Safari - however only on an iPad

Notice how in the picture the click path is not properly selected and rendered in blue.
In the picture below "View" and "Editor Layout" should be in blue. "Command Palette" should not be in blue.

If I use the mouse on an iPad the bug does not reproduce.
So I would guess that you are clearing selection on Hover. Can you also make sure to update selection on Click (which is actually touch)

![FA143BF0-35F0-41CF-8EFB-81FD447809A6](https://user-images.githubusercontent.com/1926584/114588396-eff08480-9c86-11eb-83de-d93b75b32bec.png)

**Comment by isidorn** [comment]
@sbatten can you provide some pointers for this one. I would like to understand it better and potentially fix in June.

**Comment by sbatten** [comment]
This code (for submenus) lives here: https://github.com/microsoft/vscode/blob/e1f0f8f51390dea5df9096718fb6b647ed5a9534/src/vs/base/browser/ui/menu/menu.ts#L692
