### ISSUE TITLE
vscode API - env

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121261]
```
  1) vscode API - env
       env.remoteName:
     AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(knownUiAndWorkspaceExtension)

      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/env.test.ts:44:11)
      at processImmediate (internal/timers.js:456:21)

```

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=113384&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=fff0fe4e-512d-573e-9d0b-0e9f3e677ab7&l=695

**Comment by aeschli** [comment]
Caused by https://github.com/microsoft/vscode/commit/40a6563f9b0ba6b8f29e0d0396a823252471f7ac (FYI @chrmarti )

Pushed the fix, also tested the web build.

**Comment by chrmarti** [comment]
Thanks @aeschli. I missed how we run this locally.

**Comment by aeschli** [comment]
`./resources/server/test/test-web-integration.sh|bat`
