### ISSUE TITLE
Extension loading ignores extensionHomePath

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12129]
From @Tyriar 

I did notice that my normal extensions were being loaded in from the default directory with both of these:

```
code-insiders --user-data-dir ~/test-data-dir --extensionHomePath ~/test-extension-path .
code-insiders --user-data-dir ~/test-data-dir --extensionHomePath=~/test-extension-path .
```

**Comment by bpasero** [comment]
@joaomoreno I cannot reproduce this anymore. However I see it when you have a window already open, you cannot bring up another window with the extensions from that folder.

**Comment by joaomoreno** [comment]
Yes this seems to work fine for me too...

**Comment by Tyriar** [comment]
Likely the root cause for this: https://github.com/Microsoft/vscode/pull/15448
