### ISSUE TITLE
 Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12125]
Issue Id: <b>5f3b07e0-da7b-5491-db2e-332362d9b76d</b><br /><br />*Versions* <br />- 1.5.2<br />*Stack* <br />TypeError: Cannot read property 'metadata' of undefined<br />[/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L399:57 (metadata)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L399:57 (metadata))<br />    at Array.filter (native)<br />[/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L399:36 (filter)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L399:36 (filter))<br />[/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L236:94 (onDidInstallExtension)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#L236:94 (onDidInstallExtension))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L108:26 (call)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/event.ts#L108:26 (call))<br />[/vs/base/parts/ipc/common/ipc.ts#L331:42 (fire)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/parts/ipc/common/ipc.ts#L331:42 (fire))<br />[/vs/base/common/winjs.base.raw.js#L1244:0 (onProgress)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1244:0 (onProgress))<br />[/vs/base/common/winjs.base.raw.js#L1045:0 (_progress)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1045:0 (_progress))<br />[/vs/base/common/winjs.base.raw.js#L1244:0 (onProgress)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1244:0 (onProgress))<br />

**Comment by ramya-rao-a** [comment]
Same error in the same file in `onInstallExtension` method

Call Stack:
/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#416:54 (metadata) 
/vs/workbench/parts/extensions/electron-browser/extensionsWorkbenchService.ts#416:33 (filter)
