### ISSUE TITLE
terminal do not respond to keystroke

### ISSUE THREAD

**Issue by matsberg** [microsoft/vscode#121281]
Issue Type: <b>Bug</b>

Reinstalled VS Code -> Terminal -> New Terminal

I try to type in Terminal Area. -> Nothing happends.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 6.2.9200

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (22.21GB free)|
|Process Argv|--crash-reporter-id 952abbeb-642b-4d73-9cbf-90e4d9b07e77|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.0
vscode-html-css|ecm|1.10.2
resxformatter|gir|1.0.1
vscode-nuget-package-manager|jmr|1.1.6
font-awesome-5-codes-html|mrd|1.0.1
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestaticwebapps|ms-|0.6.0
vscode-azurestorage|ms-|0.12.0
csharp|ms-|1.23.11
remote-wsl|ms-|0.54.6
azure-account|ms-|0.9.8
js-debug-nightly|ms-|2021.4.1317
debugger-for-chrome|msj|4.12.12
resxpress|Pra|4.2.0
LiveServer|rit|5.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by matsberg** [comment]
Oki. Tried Extension bisect => Alert: "Extension Bisect is don but no extension has been identified. This might be a problem with Code"

**Comment by matsberg** [comment]
Hi. I performed a "clean install" after deleting all folders associated with V S Code. Unfortunately the problem is still there. When I press "Terminal" I get a powershell terminal but I cannot type anything in it.

**Comment by matsberg** [comment]
About VS Code:
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.2.9200

About Windows:
Utgåva	Windows 10 Education
Version	20H2
Installerad	‎2020-‎11-‎12
OS-version	19042.867
Gränssnitt	Windows Feature Experience Pack 120.2212.551.0

Would it help if I send you a renderer1.log ?

**Comment by matsberg** [comment]
Hi. Problem solved. Turned out that (how this can be, I don't know) VS Code was running in compatibility mode with win8. I unchecked this an now it seems to work as expected. :-)
