### ISSUE TITLE
Terminal tab actions don't always apply to the right instance

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121282]
![recording (23)](https://user-images.githubusercontent.com/2193314/114707596-44bfe980-9cdf-11eb-9b59-c224b972b80e.gif)

**Comment by connor4312** [comment]
![](https://memes.peet.io/img/21-04-25fe589c-4bc8-448c-b5c1-203a1cd5c1d9.gif)

**Comment by Tyriar** [comment]
Think this regressed because we switched to run the command which works based off the selection in the list
