### ISSUE TITLE
Running "code ." in Git Bash does not open the current folder in VSCode, but instead opens the VSCode install folder

### ISSUE THREAD

**Issue by randrade23** [microsoft/vscode#121276]
VSCode Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open Git Bash and change to any directory
2. Run "code ."
3. VSCode opens inside the VSCode install folder (C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code), and not the directory that was open in Git Bash.

Does this issue occur when all extensions are disabled?: Yes

This problem did not occur before 1.55. It would always open the directory where Git Bash was at. Could it be related to this change? https://github.com/microsoft/vscode/commit/1441ba91f0e3fd82ac6860aacda83befe9d176e3#diff-636e6ac1fe4b9b66ab5125c4b3a323aaabf2b1dbc931bccf3fd29c23e43e3985R13

**Comment by joaomoreno** [comment]
What does `which code` return?

**Comment by randrade23** [comment]
```
/c/Users/<user>/AppData/Local/Programs/Microsoft VS Code/bin/code
```

**Comment by joaomoreno** [comment]
Odd, I can't reproduce, it always opens the correct folder for me.
