### ISSUE TITLE
Working on a removable drive that is ejected now crashes the window

### ISSUE THREAD

**Issue by ehippy** [microsoft/vscode#121223]
Issue Type: <b>Bug</b>

open a window to a removable drive. edit a file some. Then remove the drive. the window crashes. It used to survive the disconnection and keep all the code up and editable, and then when the disk is available again, it would be able to sync right back up

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/106879

Can you follow these steps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports and attach the crash report. Thanks!
