### ISSUE TITLE
 r.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12122]
Issue Id: <b>c6fb6956-d489-b312-274b-cb99c1937800</b><br /><br />*Versions* <br />- 1.5.2<br />-  07d663dc1bd848161edf4cd4ce30cce410d3d877<br />*Stack* <br />TypeError: r.hasOwnProperty is not a function<br />[/vs/base/common/diff/diff.ts#L260:18 (hasOwnProperty)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/diff/diff.ts#L260:18 (hasOwnProperty))<br />[/vs/base/common/diff/diff.ts#L242:7 (ComputeUniqueIdentifiers)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/diff/diff.ts#L242:7 (ComputeUniqueIdentifiers))<br />[/vs/editor/common/diff/diffComputer.ts#L21:16](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/editor/common/diff/diffComputer.ts#L21:16)<br />[/vs/editor/common/diff/diffComputer.ts#L303:19 (computeDiff)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/editor/common/diff/diffComputer.ts#L303:19 (computeDiff))<br />[/vs/editor/common/services/editorSimpleWorker.ts#L221:34 (computeDiff)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/editor/common/services/editorSimpleWorker.ts#L221:34 (computeDiff))<br />[/vs/base/common/worker/simpleWorker.ts#L302:51 (apply)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/worker/simpleWorker.ts#L302:51 (apply))<br />[/vs/base/common/worker/simpleWorker.ts#L284:69 (_handleMessage)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/worker/simpleWorker.ts#L284:69 (_handleMessage))<br />[/vs/base/common/worker/simpleWorker.ts#L130:29 (handleMessage)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/worker/simpleWorker.ts#L130:29 (handleMessage))<br />[/vs/base/common/worker/simpleWorker.ts#L98:7 (_handleMessage)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/worker/simpleWorker.ts#L98:7 (_handleMessage))<br />[/vs/base/common/worker/simpleWorker.ts#L289:17 (handleMessage)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/worker/simpleWorker.ts#L289:17 (handleMessage))<br />[/vs/base/worker/vs/base/worker/workerMain.ts#L25:42 (onmessage)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/worker/vs/base/worker/workerMain.ts#L25:42 (onmessage))<br />

**Comment by alexandrudima** [comment]
Impossible as far as I'm concerned (living in a normal world where `{}.hasOwnProperty` is defined.

```ts
private ComputeUniqueIdentifiers(): void {
		let originalSequenceLength = this.OriginalSequence.getLength();
		let modifiedSequenceLength = this.ModifiedSequence.getLength();
		this.m_originalIds = new Array<number>(originalSequenceLength);
		this.m_modifiedIds = new Array<number>(modifiedSequenceLength);

		// Create a new hash table for unique elements from the original
		// sequence.
		let hashTable:{[key:string]:number;} = {};
		let currentUniqueId = 1;
		let i: number;

		// Fill up the hash table for unique elements
		for (i = 0; i < originalSequenceLength; i++) {
			let originalElementHash = this.OriginalSequence.getElementHash(i);
			if (!hashTable.hasOwnProperty(originalElementHash)) {
				// No entry in the hashtable so this is a new unique element.
				// Assign the element a new unique identifier and add it to the
				// hash table
				this.m_originalIds[i] = currentUniqueId++;
				hashTable[originalElementHash] = this.m_originalIds[i];
			} else {
				this.m_originalIds[i] = hashTable[originalElementHash];
			}
		}

		// Now match up modified elements
		for (i = 0; i < modifiedSequenceLength; i++) {
			let modifiedElementHash = this.ModifiedSequence.getElementHash(i);
			if (!hashTable.hasOwnProperty(modifiedElementHash)) {
				this.m_modifiedIds[i] = currentUniqueId++;
				hashTable[modifiedElementHash] = this.m_modifiedIds[i];
			} else {
				this.m_modifiedIds[i] = hashTable[modifiedElementHash];
			}
		}
	}
```

**Comment by alexandrudima** [comment]
@bpasero Are these stack traces finally reliable?

**Comment by bpasero** [comment]
@alexandrudima as far as I know @ramya-rao-a owns the error telemetry service and should be the one to talk to

**Comment by ramya-rao-a** [comment]
@alexandrudima We have been having stack traces working for quite some time now. AFIK the last issue with stack traces was that there was no demififed stack. Are you referring to any other issue?

**Comment by alexandrudima** [comment]
Sorry about it, I take it back. I thought it is impossible for this exception to occur in the above code (so I thought the stack trace must be wrong), but it can occur if `hasOwnProperty` is a key in `hashTable`.

**Comment by alexandrudima** [comment]
To reproduce:
* have a diff where you compare two files
* in one file have a line containing only `hasOwnProperty`
* Observe: the diff is not computed:
![image](https://cloud.githubusercontent.com/assets/5047891/18822299/066efba8-83b7-11e6-8bdf-4e765dc35381.png)

**Comment by ramya-rao-a** [comment]
@alexandrudima nice catch
