### ISSUE TITLE
Adding a file to workspace but it did not add .vscode and settings.json sub folders

### ISSUE THREAD

**Issue by jnardone64** [microsoft/vscode#121246]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Adding a file to workspace but it did not add .vscode and settings.json sub folders

This is a new, empty folder that I am adding to the workspace, but the the steps to add it listed in the Python for Dummies book implies that that those two subfolders should be there.  

I am very new to this and cannot find an answer in documentation or in Google.
Can you can tell me what I need to do to resolve this?
Thank you.
Joe Nardone
joseph.a.nardone@hotmail.com
6034869017
_____________________________________________________________

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.83GB free)|
|Process Argv|--crash-reporter-id 521fa201-c51c-4cf1-94c1-4706361f7360|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   116	 15896	code main
    0	    52	  1552	   window (Issue Reporter)
    0	   249	  3168	   gpu-process
    0	    73	  3968	   shared-process
    0	    30	  9716	     ptyHost
    0	     6	  1548	       console-window-host (Windows internal process)
    0	     5	  4524	       console-window-host (Windows internal process)
    0	    68	 10844	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    68	 12688	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    65	 13544	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 15980	       console-window-host (Windows internal process)
    0	    24	  6280	   utility
    0	   178	 13400	   window (My Python3 workspace.code-workspace - My Python3 workspace (Workspace) - Visual Studio Code)
    0	    11	  6792	     watcherService 
    0	    11	  5704	       console-window-host (Windows internal process)
    0	    75	 15748	     extensionHost
    0	    46	 13660	       "C:\Users\Josep\AppData\Local\Programs\Microsoft VS Code\Code.exe" "c:\Users\Josep\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=15748
    0	    13	 14552	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (My Python3 workspace.code-workspace - My Python3 workspace (Workspace) - Visual Studio Code)
|    Folder (MyCode): 0 files
|      File types:
|      Conf files:;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.6.0
python-extension-pack|don|1.6.0
MagicPython|mag|1.1.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
remote-wsl|ms-|0.54.6
vscode-yaml|red|0.17.0
vscodeintellicode|Vis|1.2.12
jinja|who|0.0.8
tconda|zhp|0.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30286882

```

</details>

**Comment by sandy081** [comment]
You can create them manually or when you try to add any workspace settings (from settings editor)

**Comment by jnardone64** [comment]
Thank you
