### ISSUE TITLE
Install button doesn't always show up for screen reader when navigating extensions list

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121220]
Install button doesn't always show up when navigating extensions list.

- open extension list with control+shift+x;
- press end to go to last entry
- press tab
   + should land on install button
   + focus moves to next thing in tab order which often is another editor or something

## Workaround

If the button doesn't show up, move to next item, then arrow back to this one and button should now show up. Not sure what to do if at end of list.

I am a newbie to vsCode, so forgive me if this has been addressed or has an open issue associated with it. A quick search didn't find anything related.

Using NVDA as my screen reader.

**Comment by sandy081** [comment]
It works for me when I am focused on last entry. Can you please record a video by enabling screen cast mode in the editor and share it? `F1 > Developer: Toggle Screen Cast Mode`
