### ISSUE TITLE
Git Sync Icon is not centered

### ISSUE THREAD

**Issue by JetLua** [microsoft/vscode#121248]
![image](https://user-images.githubusercontent.com/6738986/114640671-2cfa5c80-9d03-11eb-888f-da8a84188a03.png)

https://user-images.githubusercontent.com/6738986/114640906-9aa68880-9d03-11eb-8e2a-5e48b3c89cf5.mp4

版本: 1.56.0-insider
提交: 394a2e4779ff767e2761a59a51b15848dcd24173
日期: 2021-04-13T11:11:34.416Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by eamodio** [comment]
@joaomoreno I'm pretty sure this is fallout from the hover feedback work.
