### ISSUE TITLE
JavaScript - No IntelliSense suggestions for import function.

### ISSUE THREAD

**Issue by pixieaka** [microsoft/vscode#121247]
- VS Code Version: 1.55.2
- OS Version: Windows 10 20h2

cc/ @mjbvz 

Steps to Reproduce:

No suggestions first.

![image](https://user-images.githubusercontent.com/17777237/114640534-9f057e00-9cd0-11eb-8361-a015b0c64167.png)

Suggestions start after `.`

![image](https://user-images.githubusercontent.com/17777237/114640591-bc3a4c80-9cd0-11eb-96af-ba00391a1808.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by jasonwilliams** [comment]
This will be fixed when Typescript 4.3 reaches stable https://devblogs.microsoft.com/typescript/announcing-typescript-4-3-beta/#import-statement-completions

**Comment by mjbvz** [comment]
`import` is suggested as a keyword. It would not make sense IMO to have both this keyword suggestion and a second one (also just labeled `import`) for a function
