### ISSUE TITLE
Issue reporter doesn't work

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#121237]
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z (12 hrs ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open Help > Report Issue
2. Notice issue reporter is empty

![image](https://user-images.githubusercontent.com/484784/114624799-19e57f00-9c66-11eb-993a-2264a94f117e.png)

Alternative repro
1. Execute Reload with Extensions Disabled
2. Open Help > Report Issue
3. Notice issue reporter never appears at all

Does this issue occur when all extensions are disabled?: Yes

**Comment by RMacfarlane** [comment]
@akbyrd I'm having trouble reproducing this, can you bring up the dev tools when that window is focused with F12 and see if there is any error in the console?

**Comment by akbyrd** [comment]
![image](https://user-images.githubusercontent.com/484784/115751338-f6998e80-a34d-11eb-8a39-7d449c3b76b7.png)

**Comment by RMacfarlane** [comment]
@deepak1556 any ideas here?

**Comment by deepak1556** [comment]
@akbyrd in the issue reporter devtools, can you check the value of `window.location.origin`

**Comment by akbyrd** [comment]
`"file://"`

**Comment by akbyrd** [comment]
Updating to 1.56.0 fixed it. Then re-applying Monkey Patch broke it. Looks like it's caused by an extension after all.

Interestingly, I can remove all my patches and it still breaks. Just the presence of Monkey Patch breaks something.

Here's my patch in case you're curious
```
	"customizeUI.stylesheet": {
		".editor-actions": "display: none !important;",
		".pane-header .actions-container": "display: none !important;",
	},
```

**Comment by deepak1556** [comment]
@RMacfarlane this issue happened because we hit the check where we check if the scripts origin match the workbench before loading. For the issue reporter, the origin is `vscode-file://vscode-app`, @akbyrd thanks for confirming the extension that caused this issue, an extension should not be able to change the window origin, @RMacfarlane we should identify why it happened.
