### ISSUE TITLE
Can't use Markdown's user code snippet function correctly

### ISSUE THREAD

**Issue by QinHaoChen97** [microsoft/vscode#121286]
Issue Type: <b>Bug</b>

My markdown.json is as follows:

```
{
	 "tab": {
	 	"prefix": "tab",
	 	"body": [
	 		"&emsp;"
	 	],
	 	"description": "tab"
	 }		
}

```
But I didn’t get a response when I typed tab in the Markdown file.
I don't know if this is a bug or the attributes of the Markdown file itself make this phenomenon happen.
Thank you for reviewing my question and giving help.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.17763

<details>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.8.9
vscode-language-pack-zh-hans|MS-|1.55.2
csharp|ms-|1.23.11
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.0

**Comment by mjbvz** [comment]
Set:

```json
  "[markdown]": {
    "editor.quickSuggestions": true
  }
```

**Comment by QinHaoChen97** [comment]
> To make suggestions automatically show up, set:
> 
> ```json
>   "[markdown]": {
>     "editor.quickSuggestions": true
>   }
> ```
> 
> You can also manually trigger suggestions with ctrl+space

Thanks for your help, my problem has been solved through this setting.
