### ISSUE TITLE
 Cannot read property 'targets' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12120]
Issue Id: <b>8ec5b8ad-a8de-0ca4-6be0-8bd5bb61735d</b><br /><br />*Versions* <br />- 1.5.2<br />*Stack* <br />TypeError: Cannot read property 'targets' of undefined<br />[/vs/workbench/parts/debug/electron-browser/debugService.ts#L960:41 (targets)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L960:41 (targets))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L50:5 (completeDispatch)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L50:5 (completeDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L163:6 (clb)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L163:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L127:11 (dispatch)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L127:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L40:8 (handleData)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L40:8 (handleData))<br />    at emitOne (events.js:90:13)<br />

**Comment by isidorn** [comment]
fyi @weinand
