### ISSUE TITLE
(WSL 2 server) Open folder doesn't work (goes one directory up)

### ISSUE THREAD

**Issue by strarsis** [microsoft/vscode#121292]
- VS Code Version: `1.56.0-insider (user setup)`
- OS Version: `Windows 10 x64`

Steps to Reproduce:

1. Open a VSCode window connected to a VSCode server on WSL 2 distribution.
2. Open a folder in WSL 2, note that when trying to select a folder (by hitting enter), 
the folder selection goes one directory up instead. This also happens when using the `OK` button.

Does this issue occur when all extensions are disabled?: (WSL 2 doesn't work then, but unlikely as no special extensions are used).

**Comment by aeschli** [comment]
You are talking about our custom Open Folder dialog.
I can reproduce:
- use cursor down to set the selection to another folder
- Press OK and expect that that folder is opened
- Dialog stays open

**Comment by alexr00** [comment]
The "OK" button respects the selected item if there is one. If there isn't one, then it opens the folder.

**Comment by strarsis** [comment]
@alexr00: But in my case I actually selected an item (an existing folder) and selecting the OK-button/enter still caused the dialog to go one directory up instead confirming the selection.

**Comment by strarsis** [comment]
OK, so I also noticed that when using `Ctrl` + `o` shortcut, a file should be opened - and not a directory.
The file selection prompt states this, too (`Open File`) - but the user may not notice it.
Adding a notice like "The item you selected is a folder. Maybe you want to **_open a folder_** instead?" can be helpful.
