### ISSUE TITLE
Url encoded characters in Markdown relative paths

### ISSUE THREAD

**Issue by Guiorgy** [microsoft/vscode#121277]
- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.19042(.867)

Problem:

A link in markdown like `[some C# file](C%23)/some.file` doesn't work in the peview (does nothing when pressed).
However, it does work as intended on **github.com**

Does this issue occur when all extensions are disabled?: Yes

**Comment by jeanp413** [comment]
duplicate of #123228
