### ISSUE TITLE
Enable Create New File via Zen Mode's breadcrumbs

### ISSUE THREAD

**Issue by harisraharjo** [microsoft/vscode#121249]
When in Zen Mode, I think it would be nice to add a feature that let the user to create a new file via breadcrumbs by either right-click -> new File or just by simply click on a plus icon. The benefit of this is that user doesn't need to leave zen mode no more just to create a new file

**Comment by isidorn** [comment]
This feels like a breadcrumb feature request fyi @jrieken
Zen for now would not do anything special here. However you can create a new file from zen by F1 > "new file"

For now leaving this open as a feature request.
