### ISSUE TITLE
"Help us improve.." notification is displaying language IDs

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#121216]
- VS Code Version: 1.55.2
- OS Version: Windows

The survey notification in languageSurveys.contributions.ts is displaying the language ID, which may not be the best for a user facing notification.

For example, when displaying the survey notification for JavaScript, the text "Help us improve our support for javascript", which is not capitalized correctly. 

We should be using the display name instead of the language ID as we do in the Language Mode dropdown.

![image](https://user-images.githubusercontent.com/12818376/114600468-3a531080-9c49-11eb-9e1e-32d5e374a182.png)

**Comment by mjbvz** [comment]
@gregvanl Can you please verify this or let me know how to trigger this survey?

**Comment by gregvanl** [comment]
@mjbvz I can take this one. I only saw it once but I'll investigate how to get the survey to pop.

**Comment by gregvanl** [comment]
@bpasero @mjbvz I had no luck trying to display the language survey notification. 
Maybe someone who know more about playing with Local Storage could fool Insiders into displaying the notification?
Looks like VS Code displays the survey notification after a certain number of sessions (9?) across different days.

**Comment by JacksonKearl** [comment]
Still seeing this:
![image](https://user-images.githubusercontent.com/8586769/116763971-3f97b580-a9d4-11eb-94bd-98871d487ce0.png)

**Comment by bpasero** [comment]
@JacksonKearl does it reproduce if you open a Java file prior to getting the notification? Maybe the extension is not activated or so.

**Comment by JacksonKearl** [comment]
Well the notification only shows on opening a Java file, so I'm not sure how I could see it prior to opening one? The language services for it may not have been set up yet though.

**Comment by bpasero** [comment]
I pushed a fix, the notification was showing too early before extensions were registered, so the language names were not there.

**Comment by connor4312** [comment]
ping @gregvanl for verification
