### ISSUE TITLE
 Cannot read property 'scopes' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#12123]
Issue Id: <b>dbe188c1-e9c1-3611-2ccd-8815b5ab7dee</b><br /><br />*Versions* <br />- 1.5.2<br />-  07d663dc1bd848161edf4cd4ce30cce410d3d877<br />*Stack* <br />TypeError: Cannot read property 'scopes' of undefined<br />[/vs/workbench/parts/debug/common/debugModel.ts#L387:25 (scopes)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/common/debugModel.ts#L387:25 (scopes))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L50:5 (completeDispatch)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L50:5 (completeDispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L163:6 (clb)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L163:6 (clb))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L127:11 (dispatch)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L127:11 (dispatch))<br />[/vs/workbench/parts/debug/node/v8Protocol.ts#L40:8 (handleData)](https://github.com/microsoft/vscode/blob/66f37fd2a99eb9d628dd374d81d78835b410c39b/src/vs/workbench/parts/debug/node/v8Protocol.ts#L40:8 (handleData))<br />    at emitOne (events.js:90:13)<br />    at Socket.emit (events.js:182:7)<br />

**Comment by isidorn** [comment]
FYI @weinand
