### ISSUE TITLE
Investigate not including our loader in the notebook webview by default

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#121245]
Notebook webviews currently always loads [our loader script](https://github.com/microsoft/vscode/blob/3e22994cad3d1f97d56649fd23a06fc1a443c177/src/vs/loader.js). This allows output renderers to use amd style module loading, which I believe is how Jupyter renderers work.

However for non-Jupyter notebooks, it would be nice if we could use JavaScript modules instead. This would let us avoid loading/parsing an extra script inside the webview and also reduce the size of the custom api we give to output renderers

**Comment by jrieken** [comment]
I like. The amd-loader/requirejs-script seems like a good candidate for a preload-uri of the jupyter kernel

**Comment by mjbvz** [comment]
@DonJayamanne What work needs to happen on the python side before we can make this change in VS Code itself?

**Comment by jrieken** [comment]
ping @DonJayamanne

**Comment by DonJayamanne** [comment]
The Jupyter notebook needs and (specifically require.js define, config).

> What work needs to happen on the python side before we can make this change in VS Code itself?

Not sure what you mean by this.
How do you plan on leaving extension authors choose between the two?

**Comment by jrieken** [comment]
> How do you plan on having extension authors choose between the two?

Afaik the plans is no choice. If Jupyter needs require.js it's up to it to bring that in. We would not provide a loader anymore.

**Comment by DonJayamanne** [comment]
> We would not provide a loader anymore.

I think that should be ok, we do that in webview today.

Will preloads be  loaded before renderer scripts?
Assume a user opens an existing notebook, will the preload be loaded first? This needs to be guaranteed, as some renderers require require.js
