### ISSUE TITLE
input from file for debug code option in palette 

### ISSUE THREAD

**Issue by Navin009** [microsoft/vscode#121275]
![Annotation 2021-04-14 152225](https://user-images.githubusercontent.com/62857427/114691438-503dff80-9d35-11eb-9e3e-74a77388e769.png)

if you add an option below for enter input file location for input or debug argument for the compiler it help the debug code for for getting the output it help the lot of competitive programmer for the debugging the code for passing the test cases 

freopen("input.txt", "r" , stdin); 
if only for the getting input from file only during running but when we talk about debug it create big problem when input is large

**Comment by Navin009** [comment]
![Annotation 2021-04-14 155343](https://user-images.githubusercontent.com/62857427/114695778-9e550200-9d39-11eb-84b7-134578ba6ecc.png)

it create trouble for other program for to debug input every time need to manual changing the args if got option below for input args or show option before start debug

**Comment by weinand** [comment]
@Navin009 I do not really understand what you mean.

But maybe you are looking for "Input Variables"?
Please read this https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by Navin009** [comment]
![Uploading Annotation 2021-04-14 152225.png…]()

**Comment by Navin009** [comment]
![Annotation 2021-04-14 152225](https://user-images.githubusercontent.com/62857427/114701791-e4fa2a80-9d40-11eb-95c2-fa79f786e01b.png)

**Comment by weinand** [comment]
I still don't understand what you are trying to say.

**Comment by Navin009** [comment]
![Annotation 2021-04-14 195943](https://user-images.githubusercontent.com/62857427/114730343-67ddae00-9d5e-11eb-8f86-24ad768cf1b1.png)
![Annotation 2021-04-14 200355](https://user-images.githubusercontent.com/62857427/114730375-6f9d5280-9d5e-11eb-8b49-8b7af938225c.png)
![Annotation 2021-04-14 200900](https://user-images.githubusercontent.com/62857427/114730390-73c97000-9d5e-11eb-9510-4bf85210e382.png)

**Comment by weinand** [comment]
So you want to select an input file with through a file dialog?

**Comment by Navin009** [comment]
is you make this input file dialog done for me

**Comment by weinand** [comment]
Possible answers to my question were "yes" or "no".

**Comment by Navin009** [comment]
I thought maybe you not prioritize this issue or mitigate this

**Comment by weinand** [comment]
Sorry, I give up.
