### ISSUE TITLE
Additional views panel button has 2x hover feedback

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121297]
![recording (25)](https://user-images.githubusercontent.com/2193314/114730935-2c0efe00-9cf6-11eb-9a9b-3c17e0374357.gif)

**Comment by isidorn** [comment]
Also assigning to @joaomoreno
If he is busy I can also look into it.

@Tyriar thanks for reporting

**Comment by sandy081** [comment]
I have caused this, will fix it :)
