### ISSUE TITLE
Auto-detect and change vs code language to match system language

### ISSUE THREAD

**Issue by cl-ement05** [microsoft/vscode#121219]
It would be great if vs code automatically detected the language of the system on which it is installed. So that vs Code could start-up for first time set up with a language the user is comfortable with.

Or maybe add a step in setup like "auto detect language OR keep english as default"

**Comment by gregvanl** [comment]
Hi @cl-ement05 You can change the VS Code display language via the **Configure Display Language** command.
You can read more details at https://code.visualstudio.com/docs/getstarted/locales

**Comment by cl-ement05** [comment]
> Hi @cl-ement05,
> You can change the VS Code display language via the **Configure Display Language** command.
> You can read more details at https://code.visualstudio.com/docs/getstarted/locales

Oh I am so sorry I didn't know it. I changed my feature request
