### ISSUE TITLE
Tabs animating when typing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121284]
![recording (24)](https://user-images.githubusercontent.com/2193314/114714977-763cb300-9ce7-11eb-800a-b26b8e8d564f.gif)

Version: 1.56.0-insider
Commit: 394a2e4779ff767e2761a59a51b15848dcd24173
Date: 2021-04-13T11:11:34.416Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

**Comment by bpasero** [comment]
Does it reproduce if you disable tabs decorations? Do you have some more exact steps how to reproduce? Does it reproduce in stable with your steps?

**Comment by Tyriar** [comment]
It's been happening a bunch randomly all morning, the above was a case where I got it to happen consistently but it isn't happening anymore when I try.

**Comment by Tyriar** [comment]
Haven't seen since 🤷
