### ISSUE TITLE
iPad: not needed whitespace for keyboard rendered

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121206]
Sorry I do not have good steps for this.
Touch on the Gear -> Command Palette (now the keyboard appears), Touch the Editor, Additional Whitespace appears

It seems like double the space is taken for the keyboard.
Assigning to you @bpasero in case you have ideas, feel free to unassign yourself

On the vscode-web-test-playground iPad and Chrome I can 100% repro the issue, just the white space is much smaller.

fyi @rebornix 

![A7F4709B-3F39-4E5A-BBFA-044DAAA62E3B](https://user-images.githubusercontent.com/1926584/114591574-562ad680-9c8a-11eb-849c-a3271e4fc6b7.png)

**Comment by bpasero** [comment]
I think Pung worked on this specifically iirc.

**Comment by rebornix** [comment]
@isidorn we would need to debug https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/window.ts#L51-L52

**Comment by isidorn** [comment]
I started debugging today, but I can no longer repro.
Ever since I updated to the latest iPad OS beta. So it seems like it was a Safari bug, that safari was just giving us a wrong window layout. Thus closing this

**Comment by isidorn** [comment]
I can actually still reproduce this. Easy steps:
1. Open panel, touch on the OUTPUT

@rebornix I put a breakpoint where you asked and I get the following

```
VisualViewport {listeners: Object, offsetLeft: 0, offsetTop: 403, pageLeft: 0, pageTop: 403, …}
```

So it seems like the VisualViewport has a wrong `offsetTop 403`.
In other cases when this just works this is always 0.

@rebornix let me know what more data you need and I can provide it. Does it makes sense to simply ignore the offsetTop? Is there any way to make the window smaller on the iPad?

**Comment by isidorn** [comment]
I fixed this for the OUTPUT by making it readonly. With this fix I can no longer reproduce this issue for other parts of the UI.
