### ISSUE TITLE
Unable to run VSCode unit tests from debug on Windows

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#12128]
- VSCode Version: 1.6 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. run "Unit Tests" from within VS Code

=> I do not get any output
=> works on Mac

Note: maybe this is an issue with the launch config. As you can see this config executes Electron with the `ELECTRON_RUN_AS_NODE: true` flag:

```
{
	"name": "Unit Tests",
	"type": "node",
	"request": "launch",
	"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
	"runtimeExecutable": "${execPath}",
	"stopOnEntry": false,
	"args": [
		"--timeout",
		"999999"
	],
	"cwd": "${workspaceRoot}",
	"runtimeArgs": [],
	"env": {
		"ELECTRON_RUN_AS_NODE": "true"
	},
	"sourceMaps": true,
	"outDir": "${workspaceRoot}/out"
}
```

**Comment by weinand** [comment]
@bpasero this is working fine for me in the latest Insiders on Windows
