### ISSUE TITLE
[Request] - Allow unsplitting a terminal to a tab

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#121278]
VSCode has allowed us to have [split terminals](https://github.com/Microsoft/vscode/issues/7504) for a while now. However after splitting sometimes you want to move a terminal to its own tab so you can dedicate more space for the other terminal.
Currently its not possible to do this, you have to kill the terminal and re-open a new one which loses your session.

Can we have the option to move a split terminal to its own tab?

**Comment by Tyriar** [comment]
This will come with drag and drop which may get pushed to May https://github.com/microsoft/vscode/issues/121500

**Comment by Tyriar** [comment]
@jasonwilliams there will be a command to hook up your own keybinding. I don't believe unsplitting is an important enough action to warrant a default keybinding though, I could be proven wrong is several popular terminals do this and have common keybindings for it though.
