### ISSUE TITLE
UI ERROR

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#121253]
版本: 1.56.0-insider (system setup)
提交: 394a2e4779ff767e2761a59a51b15848dcd24173
日期: 2021-04-13T11:13:44.235Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/1876302/114652772-1e1ea480-9d19-11eb-971a-7bab5f7529b3.png)

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
@heartacker Can you take a screenshot of the entire window?

Can you reproduce if you fully reinstall VS Code Insiders?

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/115341313-f5942000-a1da-11eb-8c68-f6d7604b6d6d.png)

**Comment by joaomoreno** [comment]
Can you reproduce in another machine?
