### ISSUE TITLE
Tilde replacement adds trailing slash to file names

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode#121280]
- VS Code Version: 1.55.2
- OS Version: Windows 10 21H1, SSH-remoting into OpenSUSE LEAP 15.2

Steps to Reproduce:

On the Linux host, do:

1. `mkdir ~/dir.tmp && touch ~/dir.tmp/file.txt`

In VS Code:

2. Copy `~/dir.tmp/file.txt` to clipboard
3. Ctrl-O, A, V (open, select all, paste)
4. Hit Enter

What do I expect?
1. `file.txt` is opened

What do I observe?
1. After 3, I see `/home/bers/dir.tmp/file.txt/` in the "Open File" dialog, with `..` being the only option below and focused
2. After 4, I see `/home/bers/dir.tmp/` in the dialog.
3. If after 3, I press backspace once, I correctly see `/home/bers/dir.tmp/file.txt` in the dialog and `file.txt` appears, but `..` is still focused. Only if I press backspace once more, `file.txt` is focused and can be opened using Enter. In other words, the text input and the highlight are out of sync.

And this issue has even more facets:

5. Copy `~/tmp/file.txt` to clipboard (note that `~/tmp` does not exist)
6. Ctrl-O, A, V (open, select all, paste)
7. See `/home/bers/tmp/file.txt/` - note the extra slash. But note also that you have to press backspace nine times (until you see `/home/bers/tmp/`) before you see "The path does not exist".
8. This issue can also be reproduced by pasting `/home/bers/tmp/file.txt`

Does this issue occur when all extensions are disabled?: No (but only due to Remote SSH)

**Comment by bersbersbers** [comment]
![2QpXMMxKDy](https://user-images.githubusercontent.com/12128514/114975531-aec5c380-9e84-11eb-9353-34d60f1c80ba.gif)

**Comment by bersbersbers** [comment]
This is only partially solved.

1. After pasting the file path, I'd expect the file name to be highlighted, but is is not.

After pasting `/home/bers/dir.tmp/file.txt`
![image](https://user-images.githubusercontent.com/12128514/115223658-57398900-a10c-11eb-8f5b-a71449daa988.png)

After pasting `~/dir.tmp/file.txt`
![image](https://user-images.githubusercontent.com/12128514/115223734-6b7d8600-a10c-11eb-99e0-39dab281840d.png)

2. The cursor location is incorrect in the second example above - it should be at the end.

3. Similarly, when starting with `/home/bers`, and then pasting `/home/bers/dir.tmp/file.txt`, `file.txt` is not even shown - I still see `bers`, the contents of `/home`:
![image](https://user-images.githubusercontent.com/12128514/115225380-4a1d9980-a10e-11eb-8875-3802385bd546.png)

4. After pasting a path to a file in a non-existent directory, I do *not* get a message "The path does not exist":
![image](https://user-images.githubusercontent.com/12128514/115225079-f7dc7880-a10d-11eb-96cc-6bd751917dd8.png)

I only get it after deleting the file name, which should not be necessary:
![image](https://user-images.githubusercontent.com/12128514/115225185-13e01a00-a10e-11eb-8fc6-cded4e620399.png)


```
Version: 1.56.0-insider (user setup)
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:15:35.845Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by bersbersbers** [comment]
I think communication could be improved here. Please let me know how. 

I tested Version: 1.56.0-insider (user setup), Commit: 633562da380f9161ea2fd783e561eed508cfbbea
- Issues 1 and 2 from https://github.com/microsoft/vscode/issues/121280#issuecomment-822378002 seem resolved.
- Issues 3 and 4 from https://github.com/microsoft/vscode/issues/121280#issuecomment-822378002 are still there.

In addition, there's two more (new?) issues. I'll describe all open issues in the next post below for simplicity. Please let me know if I should file these separately.

**Comment by bersbersbers** [comment]
As before, `mkdir ~/dir.tmp && touch ~/dir.tmp/file.txt`. For me, `~` is `/home/bers`, adapt as needed.

1. Ctrl-O, see `/home/bers`. Ctrl-A, then paste `/home/bers/dir.tmp/file.txt` - `file.txt` is not focused (often not even shown). This works fine when pasting `~/dir.tmp/file.txt`. This is the inverse of the originally reported issue - before, `/home/bers` was working but `~` was not; now, `~` is working but `/home/bers` is not.

![TWG95CAGya](https://user-images.githubusercontent.com/12128514/116079677-65515180-a698-11eb-98ab-3995c5955585.gif)

Essentially the same example with a different start folder

![8Dnr47ZAsO](https://user-images.githubusercontent.com/12128514/116080218-10faa180-a699-11eb-919e-3d039453bae6.gif)

2. After pasting a path to a file in a non-existent directory, I do *not* get a message "The path does not exist":

![image](https://user-images.githubusercontent.com/12128514/115225079-f7dc7880-a10d-11eb-96cc-6bd751917dd8.png)

I only get it after deleting the file name, which should not be necessary:
![image](https://user-images.githubusercontent.com/12128514/115225185-13e01a00-a10e-11eb-8fc6-cded4e620399.png)

3. Typing `~` is generally weird now:

![1tXty49vXc](https://user-images.githubusercontent.com/12128514/116080632-9e3df600-a699-11eb-9a98-fca12cbd5c01.gif)

The same thing happens when pasting a path starting with `~`:

![iOks3oMzMp](https://user-images.githubusercontent.com/12128514/116080822-cb8aa400-a699-11eb-8132-9370889e64be.gif)

4. Typing `~` is different depending on whether a dir exists or not:

![pLNdAIu8W6](https://user-images.githubusercontent.com/12128514/116081025-07256e00-a69a-11eb-95c1-8c491d1d9206.gif)

**Comment by alexr00** [comment]
I pushed a fix for the broken `~` behavior when typing `~` at the end. 

I double checked with version 1.56, and pasting a full path in didn't update the items there either (though if you hit ok/enter it will open the file). However, now that pasting a path that begins with `~` works, this is confusing.

I think (please correct me if I'm wrong) that the other issues are all existing problems and not newly introduced bugs. Given that we are getting ready to start our endgame, I will look into addressing them at a later date.

**Comment by alexr00** [comment]
@bersbersbers thank you for testing the changes! Part of our endgame process involves testing all fixed bugs, which translates to all closed bug issues for the milestone. To ensure that the recent changes are tested, I'm going to close this issue. 

To track all the good points that I haven't addressed yet, I've opened https://github.com/microsoft/vscode/issues/122197.

**Comment by isidorn** [comment]
Adding verified based on user feedback and based on the fact there is a seperate issue for the other problems outlined here
