### ISSUE TITLE
Add ability to set file size limit for preview

### ISSUE THREAD

**Issue by PALuczak** [microsoft/vscode#121268]
I oftentimes read and generate csv files that are hundreds of megabytes in size, it would be very useful if VS Code did not try to preview them when clicked in file explorer since that freezes the editor for a couple of seconds. Basically what I would like to have is the equivalent to `hexeditor.maxFileSize` but for all files.

**Comment by lramos15** [comment]
If I remember correctly @bpasero, the file does have a concept of something that is too large but we don't allow the user to specify what that limit is. I wouldn't expect the UI to hang though as the file is loaded in since I would assume we only need what's in the viewport for rendering.

**Comment by bpasero** [comment]
Yeah we do:

https://github.com/microsoft/vscode/blob/5a8936ae639316163e89e08920d2120515ab55e6/src/vs/platform/files/common/files.ts#L1159-L1178

Not configurable atm iirc.
