### ISSUE TITLE
Support for extensions to specify they are deprecated

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#121251]
as user some ext has been deprecated ，but user never know

and author can't make a message or label to notify user that ext is gone.

like:
![image](https://user-images.githubusercontent.com/1876302/114647006-e7439100-9d0e-11eb-82d1-b725338bb4cd.png)
please

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/114647157-34276780-9d0f-11eb-98af-1070c5549b7c.png)

**Comment by heartacker** [comment]
after that, if ext is deprecated , vscode show notify or suggest user that whether uninstall or not

**Comment by isidorn** [comment]
Upstream issue https://github.com/microsoft/vsmarketplace/issues/23

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/4772
