### ISSUE TITLE
Folders randomly close when working in Go submodule, added as separate top-level folder

### ISSUE THREAD

**Issue by distinctdan** [microsoft/vscode#121217]
Issue Type: <b>Bug</b>

I have a Go project that has the following structure:
```
project
    <some files>
    subfolder
        <more files>
        go.mod
    go.mod
subfolder
```
VSCode recommends that I add the subfolder as a separate workspace folder in order for go autocomplete and error highlighting to work. However, when I do that, vscode starts behaving badly. In the Explorer pane, my open folders will randomly close. If I'm in the middle of creating a file, it cancels editing the name and saves it as is, which is pretty obnoxious. It's almost like the pane is resetting.

So to summarize the issues:
- VSCode shouldn't be randomly closing folders
- It shouldn't require me to add a subfolder as a separate top-level workspace folder (this issue may be with the go tooling rather than vscode itself.)

Thanks for the help

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id 656c6348-b102-4b6b-8ade-e7f56a3faa5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
go|gol|0.24.0
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.0
remote-containers|ms-|0.166.1
cpptools|ms-|1.2.2
vscode-yaml|red|0.17.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the random closing also happen with all your extensions disabled? One way to investigate this is to run the `Start Extension Bisect` command and follow its instructions.

**Comment by distinctdan** [comment]
Thanks, I started the extension bisect, and the issue still happens on the very first step, which it said means it's a problem with vscode. Here are the specific steps I took:
 - Double click a file in the main project
 - Expand the top-level subfolder
 - Don't click anything else and wait ~10 seconds
 - The subfolder will close on its own

**Comment by isidorn** [comment]
I can not reproduce on my machine. Might you have some file generating task in the background?
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by distinctdan** [comment]
I don't think I have any file generating stuff going on. I'm usually running a webpack server, but I've never seen that trigger anything in the Explorer pane when it rebuilds.

**Comment by distinctdan** [comment]
I'm sorry, but I'd rather not switch to using insiders. That's unfortunate that you aren't able to reproduce it.
