### ISSUE TITLE
Request to add command line editing function 

### ISSUE THREAD

**Issue by glike1** [microsoft/vscode#121287]
When I type "vi..." or "nano..." on the command line, the file will be displayed on the command line. But when I type "code..." in the command line, I can only open the GUI form of vscode, which is very inconvenient for remote connections. So I suggest adding command line editing functions, just like vim and nano. 

Thanks for watching my report !

**Comment by joaomoreno** [comment]
Also, since your situation is specific about remote, our [Remote features](https://code.visualstudio.com/docs/remote/remote-overview) might be helpful, especially the [Remote SSH](https://code.visualstudio.com/docs/remote/ssh) extension.
