### ISSUE TITLE
editor.action.reindentselectedlines does not indent correctly on second blank line

### ISSUE THREAD

**Issue by joeshaw** [microsoft/vscode#121214]
- VS Code Version: 1.55.1
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

This issue isn't limited to JSON, but it's an easy repro case.  Suppose you have a JSON document:

```
  12345
1 {
2     "hello": "world",
3
4
5     "goodbye": "for now"
6 }
```

Note that in this document, both lines 3 and 4 are completely blank.  No whitespace is on either line.

If you are anywhere on line 3 and run `reindentSelectedLines`, your cursor is moved to column 5.  This is good, and what I would expect.

If you are anywhere on line 4 and run `reindentSelectedLines`, your cursor is moved to column 1.  I would have expected it to be placed at column 5.

If line 3 has whitespace in it, then hitting tab on line 4 will indent to align with line 3.  I would still expect it to indent to column 5.

If you hit `Enter` on line 3, a new line is inserted and the cursor is indented to column 5.  So it seems like VSCode has the ability to indent to the correct place, but whatever the indent algorthims are in inserting a blank line and "reindent selected lines", they don't match up.

Does this issue occur when all extensions are disabled?: Yes

This may be related to #113288, but I think it's different.  I originally filed this as https://github.com/sakapoko/vscode-emacs-indent/issues/1 until I realized that it's a misbehavior of `editor.action.reindentselectedlines` and not of the extension.

**Comment by rebornix** [comment]
Currently the auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
