### ISSUE TITLE
Workspace Trust: No way to trust folders manually initially

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121289]
I'm scrolled dow to the bottom, no more add folder button? The message is also taking about a list of items that doesn't exist.

<img width="1233" alt="Screen Shot 2021-04-14 at 7 00 12 AM" src="https://user-images.githubusercontent.com/2193314/114722929-121ded00-9cef-11eb-8e74-1d257102f9e9.png">

**Comment by Tyriar** [comment]
Also I added the parent folder, the table appeared but it didn't contain any entries:

![Screen Shot 2021-04-14 at 7 01 33 AM](https://user-images.githubusercontent.com/2193314/114723150-498c9980-9cef-11eb-9967-a873cd1e97e7.png)

It showed up when I hid the terminal 🤷

**Comment by sbatten** [comment]
to summarize, was this a scroll issue? i.e. you weren't able to scroll low enough to see all the contents?

**Comment by lszomoru** [comment]
I can repro the scrolling issue:
1. Resize the window so that the content does not fit
2. Run the command to reload the window

After the window is reloaded, you cannot scroll to the "Add Path" button.
Resizing the window again, will make the "Add Path" button appear.

**Comment by lszomoru** [comment]
I will submit a fix for the scrolling issue, and we can then investigate the add parent issue.

**Comment by sbatten** [comment]
I think the add parent is the same issue, it was below the scrollable viewport
