### ISSUE TITLE
Quick open does not place new editor in active group if selected with `Enter`

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121395]
1. In vscode repo
2. Split workbench, one group with some file, the other with getting started opened to "Quick setup"
3. In getting started, select "quick open files", note that the active editor has switched to the other side of the split (verify by checking the vscode title, inspecting the dom, or seeing that the other side's tabs have become darker and the getting started tab has become gray)
4. Select an item with a mouse click - it gets opened in the active editor
5. Select an item with `Enter` - it gets opened covering the getting started editor

the code for this on my side is here, it looks pretty straight forward so I don't think I'm doing anything wrong, not sure
https://github.com/microsoft/vscode/blob/0a6309be1ee7446d3e085d5113d4cc6045c4ada2/src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts#L726-L748

**Comment by bpasero** [comment]
This looks like an issue from https://github.com/microsoft/vscode/issues/93055 where we first pass focus back to the original element that had focus. This will make the editor group active of "Getting Started" and thus open the editor there.

@JacksonKearl as a workaround you can probably first change the active group and then open quick pick.

**Comment by JacksonKearl** [comment]
> first change the active group and then open quick pick.

@bpasero In the above snippet I first call `this.groupsService.activateGroup(nonGettingStartedGroup);`, then use `this.openerService.open(command, { allowCommands: true });` with a `command:workbench.action.quickOpen` to open the quick pick. So it seems I'm already doing that?

Looking at #93055 I don't see why `enter` would be different from `click` here...

**Comment by bpasero** [comment]
Well, `enter` is probably executing after quick pick widget has closed (e.g. on key up and the widget closes on key down) while mouse is executing before that (this is my guess).

**Comment by bpasero** [comment]
Btw, activating a group does not move focus, so as far as quick pick widget is concerned, it still thinks the right hand group has focus?

**Comment by JacksonKearl** [comment]
I seem to get happy results by putting a:
```ts
(document.querySelector('div.editor-group-container.active') as any)?.focus?.();
```
after the `activateGroup` call. 

Any tips on making this less brittle?

**Comment by bpasero** [comment]
@JacksonKearl that sounds pretty bad, why can you not call the `group.focus()` method?

**Comment by JacksonKearl** [comment]
Ah, thanks. I was looking for it in the EditorGroupsService.
