### ISSUE TITLE
It seems to me there is a typo in documentation about settings

### ISSUE THREAD

**Issue by pstricks-fans** [microsoft/vscode#121320]
Quoted from [VS Code documentation about settings](https://code.visualstudio.com/docs/getstarted/settings).

> Language-specific editor settings in your user settings override workspace settings.

Is it correct or a typo?

I think it should be 

> Language-specific editor settings in your workspace settings override user settings.

because workspace settings has higher precedence than user settings.

**Comment by roblourens** [comment]
That seems correct to me. Your correction changes the meaning, is there a problem that you're seeing?

**Comment by pstricks-fans** [comment]
@roblourens : 

Sorry, what does `user settings` in 

> Language-specific editor settings in your user settings override workspace settings.

refer to?

Does it refer to the global user settings saved in `settings.json`?

**Comment by roblourens** [comment]
It refers to settings that are overridden for a particular language, as described in that section of settings

**Comment by pstricks-fans** [comment]
Hmm. It is confusing.

There are 3 settings defined in VS Code (pressing `Ctrl+,` shows the 3 tabs): 

 - Global User Settings
 - Workspace Settings
 - Folder Settings
  
  
  I thought the phrase "user settings" in 

  > Language-specific editor settings in your user settings override workspace settings.

refers to "Global User Settings". In my understanding, the inner settings override the outer settings.

OK. I close this issue. I might be the only reader who got confused with this.
