### ISSUE TITLE
Consider removing "Task - " from terminal title after the introduction of icons in tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121382]
Right now this is what tasks look like in tabs:

<img width="258" alt="Screen Shot 2021-04-15 at 4 55 36 AM" src="https://user-images.githubusercontent.com/2193314/114865300-e3fbe400-9da6-11eb-961c-4f1dfa976509.png">

Maybe since the icon will always be visible on the tab now we should remove it from the terminal's title.

The dropdown will still be available as a setting but we could expose a new dropdown-only title prefix or something so it still shows up there.

**Comment by alexr00** [comment]
That makes sense to me. It's extra text that is taking up valuable real-estate

**Comment by Tyriar** [comment]
Do you think we should have Task - still show up in the dropdown or drop that too? It's also somewhat problematic there too and normally truncated:

<img width="230" alt="Screen Shot 2021-04-15 at 5 00 15 AM" src="https://user-images.githubusercontent.com/2193314/114865690-78664680-9da7-11eb-9343-6dccbd8f32bd.png">

**Comment by alexr00** [comment]
I would still keep it in the dropdown. Maybe just for tasks not in a split pane though? I would have to see that's info I can correctly pass to the terminal.

**Comment by Tyriar** [comment]
I'll need to add something to `IShellLaunchConfig` first then

**Comment by Tyriar** [comment]
I just hardcoded the string since we want it basically everywhere else. Can make it more robust as needed.

<img width="253" alt="Screen Shot 2021-04-16 at 11 44 36 AM" src="https://user-images.githubusercontent.com/2193314/115069917-21489a80-9ea9-11eb-922f-bdfe7ffadb51.png">
