### ISSUE TITLE
Restart Extension Host sometimes

### ISSUE THREAD

**Issue by shadowgroundz** [microsoft/vscode#121351]
Issue Type: <b>Bug</b>

Code as usual and sometimes need to restart extension host. My device Macbook Pro M1

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:07:58.402Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 51b91535-451f-4683-9c9c-4c3e6ab8972a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
sort-imports|ama|6.2.4
clock|ang|1.0.1
vscode-color|ans|0.4.5
color-info|bie|0.5.1
vscode-intelephense-client|bme|1.6.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
hex-to-rgba|dak|1.0.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
vscode-mysql|for|0.4.0
vscode-power-mode|hoo|2.2.0
kite|kit|0.142.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
vscode-typescript-tslint-plugin|ms-|1.3.3
resourcemonitor|mut|1.0.7
color-highlight|nau|2.3.0
material-icon-theme|PKi|4.6.0
code-settings-sync|Sha|3.4.3
vscode-spotify|shy|3.2.1
swdc-vscode|sof|2.5.11
sort-lines|Tyr|1.9.0
vscodeintellicode|Vis|1.2.12
vscode-wakatime|Wak|5.0.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by deepak1556** [comment]
Can you use the extension bisect https://code.visualstudio.com/blogs/2021/02/16/extension-bisect and find out the problematic extension.

Also please provide the output from devtools when extension host crashes.

**Comment by shadowgroundz** [comment]
Okay thank you for your answer. After I inspect with bisect extension I have an error at 

1. Code Time (https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode#:~:text=Code%20Time%20is%20an%20open%20source%20plugin%20for%20automatic%20programming,time%20for%20focused%2C%20uninterrupted%20coding) 
2. Kite (https://marketplace.visualstudio.com/items?itemName=kiteco.kite)

After disable 2 this extension, everything work normal. Hope 2 this extension to optimized for M1 chip MacBook

**Comment by deepak1556** [comment]
Thanks for confirming, can you please open issues in the respective extensions to get them fixed. Close as issue is not related to the core.
