### ISSUE TITLE
Support routing vscode:// scheme to insiders

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121397]
Currently we have multiple schemes for insiders vs stable. It would be great to be able to have insiders masquerade as stable and handle `vscode://` links. For example, I always use insiders, and I want all `vscode://` links routed to it. Its less than ideal for websites/etc to have more than one link for different editions of vscode (unless there is a need to explicitly target).

**Comment by mjbvz** [comment]
@eamodio Are you primarily interested in links on extensions pages / webviews, or external links that you come across in the browser?

**Comment by eamodio** [comment]
For external links, so they will get routed to my preferred version of vscode.

**Comment by mjbvz** [comment]
@bpasero Assigning you since I am unsure who owns the `vscode:` uri opening logic

**Comment by joaomoreno** [comment]
Right, this was a purposeful decision a long time ago because you can have, as I often do, both Code versions installed. I might be over-worrying but somehow this seems like it will cause more trouble than the problems it will solve.

**Comment by bpasero** [comment]
👍  to keep `vscode` and `vscode-insiders` separate given users can have both installed.

**Comment by alexdima** [comment]
:+1: To keep the schemes separate. But it would be nice to have a new feature, where vscode stable can be configured via a boolean setting to delegate to insiders. Basically, when the boolean would be on, the stable version would take any `vscode:$VALUE` and do `open("vscode-insiders:$VALUE")`.

**Comment by joaomoreno** [comment]
Closing this discussion.
