### ISSUE TITLE
Unnecessary highlight "in" and "var"

### ISSUE THREAD

**Issue by longque** [Microsoft/vscode#12136]
- VSCode Version:1.5.2
- OS Version:Windows 10
- Language:Typescript

"in" in the next picture is highlighted, but it's unnecessary.
I have found a few bugs about highlight, so I think maybe there are or will be still other bugs about it.

![6](https://cloud.githubusercontent.com/assets/8530043/18581455/45d5fb10-7c33-11e6-9468-7d746b8e9a22.PNG)

**Comment by longque** [comment]
It appeared again just now. But it's unnecessary highlight "var".
![7](https://cloud.githubusercontent.com/assets/8530043/18582228/9a36dcc6-7c36-11e6-9b59-cb9ff67802cb.PNG)

**Comment by waderyan** [comment]
@longque thank you for opening this issue. There are a number of fixes coming out soon around the out of the box grammar. Many have found the [Atom JavaScript grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) as an excellent fix to these problems in the meantime. 

As this issue falls on the TypeScript language service I am migrating the issue there.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#10956
