### ISSUE TITLE
It takes forever to open VSCode on my PC 

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#121344]
When I installed VSCode was running ok (for about 4 Months) everything was running fast, but from a week it is  taking too long just to get start and Extensions also fail to start. 
Screenshot Below :  
![image](https://user-images.githubusercontent.com/76956612/114807964-fe44ba80-9dc4-11eb-9691-8d94ddcce92e.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by tymsai** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

sure i will try it

**Comment by tymsai** [comment]
the nightly insider build is working perfectly , 
it's blazing fast !
![Capture](https://user-images.githubusercontent.com/76956612/115113038-de202180-9fa5-11eb-8b93-381fdb6d06c4.PNG)

**Comment by deepak1556** [comment]
Can you attach the profiles following these steps https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by tymsai** [comment]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`/C:/Users/Admin/prof-080b.extHost.cpuprofile.txt`
-`/C:/Users/Admin/prof-080b.main.cpuprofile.txt`
-`/C:/Users/Admin/prof-080b.renderer.cpuprofile.txt`

**Comment by deepak1556** [comment]
Thanks for the profiles, most of the filesystem operations are quite slower than normal, not sure what is the cause. But can you try ignoring VSCode installation path from any AV software you have on the system ?

**Comment by tymsai** [comment]
" But can you try ignoring VSCode installation path from any AV software you have on the system ?  "
what is this I can't understand.
Please

**Comment by deepak1556** [comment]
I mean if you have any anti virus software running, can you exclude vscode installed path from it.

**Comment by tymsai** [comment]
There is no AV in my PC

**Comment by deepak1556** [comment]
Okay please provide the following trace based on the steps below,

1) Create a file `trace.json` somewhere on your disk with the following content:
```
{
 "result_file": "<insert-some-absolute-writable-path-here>\chrometrace.log",
 "trace_config": {
 "record_mode": "record-until-full",
 "included_categories": [
     "browser",
     "io",
     "loading",
     "renderer_host",
     "sequence_manager",
     "startup",
     "toplevel",
     "v8",
     "benchmark",
     "disabled-by-default-lifecycles",
     "disabled-by-default-system_stats"
 ],
 "excluded_categories": ["*"]
 }
}
```
2) Start code --trace-config-file="<insert-full-path-to-trace.json-here>"
3) Once the app has completely loaded
4) Quit the application, wait for the terminal to return control
5) Attach the file `chrometrace.log` generated at the path you had specified in step 1)

Note: make sure you add valid paths where mentioned with `<>` above

**Comment by tymsai** [comment]
I got that file but the size is larger than 10mb.
here's the drive link of `chrometrace.log` file.
https://drive.google.com/file/d/1UPNpIBOeH79QK4mZCCWJjlj7DwMuOlz-/view?usp=sharing

**Comment by tymsai** [comment]
now the insiders build is also taking tooo much time to open and get ready :-(
## System Info

* Code - Insiders: 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129)
* OS: win32(6.1.7601)
* CPUs: Intel(R) Pentium(R) CPU G2020 @ 2.90GHz(2 x 2900)
* Memory(System): 3.20 GB(0.90GB free)
* Memory(Process): 156.01 MB working set(139.46MB private, 0.43MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                         |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------------------------ |
| start => app.isReady                                            | 1980     | [main]                    | initial startup: true                                        |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                        |
| require(main.bundle.js)                                         | 861      | [main]                    | initial startup: true                                        |
| start crash reporter                                            | 104      | [main]                    | initial startup: true                                        |
| serve main IPC handle                                           | 33       | [main]                    | initial startup: true                                        |
| create window                                                   | 418      | [main]                    | initial startup: true, state: 0ms, widget: 391ms, show: 26ms |
| app.isReady => window.loadUrl()                                 | 3056     | [main]                    | initial startup: true                                        |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 4433     | [main->renderer]          | NewWindow                                                    |
| require(workbench.desktop.main.js)                              | 2250     | [renderer]                | cached data: YES, node_modules took 0ms                      |
| wait for window config                                          | 1        | [renderer]                | -                                                            |
| wait for shell environment                                      | 0        | [renderer]                | -                                                            |
| init storage (global & workspace)                               | 440      | [renderer]                | -                                                            |
| init workspace service                                          | 455      | [renderer]                | -                                                            |
| register extensions & spawn extension host                      | 2442     | [renderer]                | -                                                            |
| restore viewlet                                                 | 0        | [renderer]                | -                                                            |
| restore panel                                                   | 0        | [renderer]                | -                                                            |
| restore & resolve visible editors                               | 316      | [renderer]                | 1: PerfviewInput                                             |
| overall workbench load                                          | 1076     | [renderer]                | -                                                            |
| workbench ready                                                 | 13256    | [main->renderer]          | -                                                            |
| renderer ready                                                  | 3897     | [renderer]                | -                                                            |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                            |
| extensions registered                                           | 16856    | [renderer]                | -                                                            |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                                                 | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ----------------------------------------------------- | --------------------------------------- |
| vscode.debug-auto-launch                | true  | 44        | 0             | 4               | *                                                     | vscode.debug-auto-launch                |
| vscode.git                              | true  | 123       | 4             | 1007            | *                                                     | vscode.github                           |
| vscode.github                           | true  | 111       | 0             | 0               | *                                                     | vscode.github                           |
| vscode.configuration-editing            | false | 89        | 0             | 24              | onLanguage:jsonc                                      | vscode.configuration-editing            |
| vscode.emmet                            | false | 96        | 3             | 2               | onStartupFinished                                     | vscode.emmet                            |
| vscode.extension-editing                | false | 117       | 1             | 12              | onLanguage:markdown                                   | vscode.extension-editing                |
| vscode.json-language-features           | false | 132       | 19            | 10              | onLanguage:jsonc                                      | vscode.json-language-features           |
| vscode.markdown-language-features       | false | 324       | 4             | 8               | onLanguage:markdown                                   | vscode.markdown-language-features       |
| vscode.merge-conflict                   | false | 71        | 2             | 0               | onStartupFinished                                     | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 81        | 4             | 205             | onAuthenticationRequest:microsoft                     | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 75        | 0             | 0               | onStartupFinished                                     | ms-vscode-remote.remote-wsl-recommender |
| ms-vscode.js-debug                      | false | 674       | 17            | 0               | onCommand:extension.js-debug.clearAutoAttachVariables | ms-vscode.js-debug                      |
| vscode.testing-editor-contributions     | false | 63        | 0             | 0               | onStartupFinished                                     | vscode.testing-editor-contributions     |
| vscode.typescript-language-features     | false | 163       | 5             | 8               | onLanguage:jsonc                                      | vscode.typescript-language-features     |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618934453825	0	0
code/didStartMain	1618934456433	2608	2608
code/willStartCrashReporter	1618934456811	378	2986
code/didStartCrashReporter	1618934456915	104	3090
code/mainAppReady	1618934458413	1498	4588
code/willLoadMainBundle	1618934458481	68	4656
code/fork/willLoadCode	1618934458717	236	4892
code/registerFilesystem/file	1618934459199	482	5374
code/didLoadMainBundle	1618934459342	143	5517
code/willStartMainServer	1618934459440	98	5615
code/didStartMainServer	1618934459473	33	5648
code/willCreateCodeWindow	1618934460992	1519	7167
code/willRestoreCodeWindowState	1618934460992	0	7167
code/didRestoreCodeWindowState	1618934460992	0	7167
code/willCreateCodeBrowserWindow	1618934460992	0	7167
code/didCreateCodeBrowserWindow	1618934461383	391	7558
code/willMaximizeCodeWindow	1618934461383	0	7558
code/didMaximizeCodeWindow	1618934461409	26	7584
code/didCreateCodeWindow	1618934461410	1	7585
code/willOpenNewWindow	1618934461469	59	7644
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618934461470	0	0
code/didStartRenderer	1618934465792	4322	4322
code/willWaitForWindowConfig	1618934465793	1	4323
code/didWaitForWindowConfig	1618934465794	1	4324
code/willShowPartsSplash	1618934465794	0	4324
code/didShowPartsSplash	1618934465885	91	4415
code/willLoadWorkbenchMain	1618934465902	17	4432
code/willWaitForShellEnv	1618934468152	2250	6682
code/didWaitForShellEnv	1618934468152	0	6682
code/didLoadWorkbenchMain	1618934468152	0	6682
code/registerFilesystem/file	1618934468154	2	6684
code/registerFilesystem/vscode-userdata	1618934468154	0	6684
code/willInitWorkspaceService	1618934468156	2	6686
code/willInitStorage	1618934468157	1	6687
code/didInitStorage	1618934468597	440	7127
code/didInitWorkspaceService	1618934468611	14	7141
code/willStartWorkbench	1618934468613	2	7143
code/LifecyclePhase/Ready	1618934468613	0	7143
code/registerFilesystem/trustedDomains	1618934468706	93	7236
code/willRestoreEditors	1618934469373	667	7903
code/didRestoreEditors	1618934469689	316	8219
code/LifecyclePhase/Restored	1618934469689	0	8219
code/didStartWorkbench	1618934469689	0	8219
code/didRemovePartsSplash	1618934469689	0	8219
code/willConnectSharedProcess	1618934470019	330	8549
code/willLoadExtensions	1618934470847	828	9377
code/willHandleExtensionPoints	1618934472465	1618	10995
code/didHandleExtensionPoints	1618934473281	816	11811
code/didLoadExtensions	1618934473289	8	11819
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1618934477278	0	0
code/fork/start	1618934477447	169	169
code/fork/willLoadCode	1618934477479	32	201
code/extHost/willConnectToRenderer	1618934479266	1787	1988
code/extHost/didConnectToRenderer	1618934479268	2	1990
code/extHost/didWaitForInitData	1618934479429	161	2151
code/extHost/didCreateServices	1618934479553	124	2275
code/extHost/willWaitForConfig	1618934479556	3	2278
code/extHost/didWaitForConfig	1618934479591	35	2313
code/extHost/didInitAPI	1618934479606	15	2328
code/extHost/didInitProxyResolver	1618934479606	0	2328
code/extHost/ready	1618934479606	0	2328
code/extHost/willLoadExtensionCode/vscode.extension-editing	1618934479610	4	2332
code/extHost/didLoadExtensionCode/vscode.extension-editing	1618934479727	117	2449
code/extHost/willLoadExtensionCode/vscode.markdown-language-features	1618934479727	0	2449
code/extHost/didLoadExtensionCode/vscode.markdown-language-features	1618934480051	324	2773
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1618934480052	1	2774
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1618934480133	81	2855
code/extHost/willLoadExtensionCode/vscode.debug-auto-launch	1618934480133	0	2855
code/extHost/didLoadExtensionCode/vscode.debug-auto-launch	1618934480177	44	2899
code/extHost/willLoadExtensionCode/vscode.git	1618934480177	0	2899
code/extHost/didLoadExtensionCode/vscode.git	1618934480300	123	3022
code/extHost/willActivateExtension/vscode.extension-editing	1618934480304	4	3026
code/extHost/willActivateExtension/vscode.markdown-language-features	1618934480305	1	3027
code/extHost/willActivateExtension/vscode.microsoft-authentication	1618934480309	4	3031
code/extHost/willActivateExtension/vscode.debug-auto-launch	1618934480313	4	3035
code/extHost/willActivateExtension/vscode.git	1618934480313	0	3035
code/extHost/didActivateExtension/vscode.extension-editing	1618934480317	4	3039
code/extHost/didActivateExtension/vscode.markdown-language-features	1618934480317	0	3039
code/extHost/didActivateExtension/vscode.debug-auto-launch	1618934480317	0	3039
code/extHost/didActivateExtension/vscode.microsoft-authentication	1618934480518	201	3240
code/extHost/willLoadExtensionCode/ms-vscode.js-debug	1618934480523	5	3245
code/extHost/didLoadExtensionCode/ms-vscode.js-debug	1618934481197	674	3919
code/extHost/willActivateExtension/ms-vscode.js-debug	1618934481268	71	3990
code/extHost/didActivateExtension/ms-vscode.js-debug	1618934481285	17	4007
code/extHost/didActivateExtension/vscode.git	1618934481324	39	4046
code/extHost/willLoadExtensionCode/vscode.github	1618934481327	3	4049
code/extHost/didLoadExtensionCode/vscode.github	1618934481438	111	4160
code/extHost/willActivateExtension/vscode.github	1618934481440	2	4162
code/extHost/didActivateExtension/vscode.github	1618934481440	0	4162
```

## Node Cached Data Stats


### cached data used

* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\clone-03c5d9b1c367516025db02b3d47f969d.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\graceful-fs-0bbdb67c71c3ef702295f7d0745f852b.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\legacy-streams-ffdd5fe176626de51883fdad4c5eb1ff.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\main-26e7dc5c5a82c560ade04d83806e65b7.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\main-49d76817f05f66d31df9880d51f4f54a.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\polyfills-4ffdd9eeb88b7bb236cc5a62bfad401a.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\tas-client-umd-869f062774f187c829a2c67949c600c6.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\workbench.desktop.main-eb9fe03fa801798d1d14916f7d70865f.code
* C:\Users\Admin\AppData\Roaming\Code - Insiders\CachedData\ce791d27dc9889a392f4d29abefe9c53eb0b5129\workbench.desktop.main.nls-09d72af337855d651c7903e46a79fa52.code

### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)

**Comment by tymsai** [comment]
> Okay please provide the following trace based on the steps below,
> 
> 1. Create a file `trace.json` somewhere on your disk with the following content:
> 
> ```
> {
>  "result_file": "<insert-some-absolute-writable-path-here>\chrometrace.log",
>  "trace_config": {
>  "record_mode": "record-until-full",
>  "included_categories": [
>      "browser",
>      "io",
>      "loading",
>      "renderer_host",
>      "sequence_manager",
>      "startup",
>      "toplevel",
>      "v8",
>      "benchmark",
>      "disabled-by-default-lifecycles",
>      "disabled-by-default-system_stats"
>  ],
>  "excluded_categories": ["*"]
>  }
> }
> ```
> 
> 1. Start code --trace-config-file="<insert-full-path-to-trace.json-here>"
> 2. Once the app has completely loaded
> 3. Quit the application, wait for the terminal to return control
> 4. Attach the file `chrometrace.log` generated at the path you had specified in step 1)
> 
> Note: make sure you add valid paths where mentioned with `<>` above

I attached the `chrometrace.log` file.
drive link above as it is larger than 10mb.
