### ISSUE TITLE
Remove "please"

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#121312]
Issue Type: <b>Feature Request</b>

When software seems to *earnestly desire* that I accomplish some goal, by asking me with "please" before the action it recommends, it always seems strange to me.

Just now I was searching for something that shows up in a lot of data files, and it said "The result set only contains a subset of all matches. Please be more specific in your search to narrow down the results."

But I think it would be more reasonable to say "The result set only contains a subset of all matches. To narrow down results, be more specific in your search."

I get that the word "please" is an attempt to be polite, but it's software, nobody thinks it's rude when it tells you plainly that if you do this one thing, another thing will happen.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

**Comment by roblourens** [comment]
Thanks for the issue, but I feel like you're overthinking it, it's just a sort of meaninglessly polite expression. I count about 150 localized messages in vscode that contain "please", all along the same lines, I think it's fine.

**Comment by sdegutis** [comment]
I've thought this for decades, ever since I read a blog about it somewhere a long time ago. Can't find it now, but [this StackOverflow post](https://ux.stackexchange.com/questions/25500/why-avoid-the-word-please-in-error-messages) says that Microsoft has a guideline on avoiding it. Anyway just an idea, thanks for reading it.

**Comment by roblourens** [comment]
Thanks for the link, that's an interesting perspective. I changed a few messages and will mention it to the team.
