### ISSUE TITLE
Activity bar gear badge is not a perfect circle

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121358]
👀

![image](https://user-images.githubusercontent.com/22350/114826188-088e9680-9d7c-11eb-8722-2b1042c6a927.png)

I believe this got broken very recently, maybe with trusted work:

![image](https://user-images.githubusercontent.com/22350/114826319-32e05400-9d7c-11eb-93dc-280337c26fae.png)

**Comment by joaomoreno** [comment]
Actually @sbatten there's a much bigger issue here: the `1` on that last screenshot is about having an update available. It should not show with a shield.

**Comment by sbatten** [comment]
This was broken via https://github.com/microsoft/vscode/commit/7c3f60f86e6776c4a339c23f85fd9a11c3424bbb due to a conflict with padding in the activity bar badge and should be resolved in today's insiders, has a separate issue for tracking.

The (1) issue is also filed separately
