### ISSUE TITLE
File gets garbled characters when restored from backup

### ISSUE THREAD

**Issue by watermagpie** [microsoft/vscode#121347]
- VS Code Version: 1.55.2
- OS Version: Windows 20H2 (Build 19042.928)

Steps to Reproduce:

1. Type some characters with unicode encoding. 
(I recommend very long files, like some translation project, because it randomly occurs)
2. DO NOT SAVE and close vscode as hot exit enabled
3. Then, Some characters replaced with U+FFFD(replacement character)

Does this issue occur when all extensions are disabled?: Yes

**Comment by watermagpie** [comment]
p.s. I am Korean, and this problem reproduced only Korean and Japanese text. so I think this problem occurs with some asian character or some characters in extended table of unicode. plz check your own system and if it occurs, report it.

**Comment by watermagpie** [comment]
p.s.2. If somebody needs temporal solution, just disable "hot exit" or auto save. It works good. I recommend :D

**Comment by bpasero** [comment]
@watermagpie can you provide some more exact steps how to reproduce with the exact text you typed? Also, did you configure any encoding in VSCode settings?

**Comment by watermagpie** [comment]
> @watermagpie can you provide some more exact steps how to reproduce with the exact text you typed? Also, did you configure any encoding in VSCode settings?

That's only steps for my case. Type some character, hot exit, open, and crashed. I really wonder about this. 
I usually edit scripts have over a 10000 rows, it could be the cause of this problem 😢

Let me explain my actual case. I typed 【 <- this bracket, but as you see, it's broken.

![KakaoTalk_20210415_144706260](https://user-images.githubusercontent.com/61748622/114832620-a4b2af00-9e09-11eb-8ea6-4464c139b21e.png)

If you need some script, I can provide some text.
[sample.zip](https://github.com/microsoft/vscode/files/6316097/sample.zip)

And yeah, I set my default encoding as utf-8 with no BOM and set "auto guess encoding".

**Comment by bpasero** [comment]
Interesting, I am not able to reproduce though, even with `files.autoGuessEncoding: true`:

![recording](https://user-images.githubusercontent.com/900690/114835854-4e764980-9dd2-11eb-9ec3-5c13bbd9bf56.gif)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by watermagpie** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

OK. I'll check it.

**Comment by watermagpie** [comment]
@bpasero 

https://user-images.githubusercontent.com/61748622/114837727-fc9fe480-9e0e-11eb-868d-958bc39f1e12.mp4

Uhh... It didn't work.
You'd better to search "�" this character to find that one.

**Comment by bpasero** [comment]
> Uhh... It didn't work

Can you clarify, is it reproducible?

**Comment by watermagpie** [comment]
> Can you clarify, is it reproducible?

Sure. I already tried with my laptop, and my friend's PC, It always occurred. both of them.

**Comment by bpasero** [comment]
@watermagpie such a good bug, thanks again for filing. I pushed a fix and hope it is fine now. You can verify from tomorrows insider build.

**Comment by watermagpie** [comment]
Appreciate it!

**Comment by watermagpie** [comment]
/verified
Thanks to you guys support!
