### ISSUE TITLE
Can't enable Settings Sync when workspace is untrusted

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121361]
Notice how nothing happens when I try to enable it:

![recording (2)](https://user-images.githubusercontent.com/22350/114828610-fa8e4500-9d7e-11eb-8c9f-107d9463ed37.gif)

**Comment by lszomoru** [comment]
I believe that this is a temporary situation as the built-in extensions required for the authentication flow are not enabled in an untrusted workspace. As soon as those extensions are on-boarded, they should be enabled in an untrusted workspace and you should be able to turn settings sync on. @RMacfarlane, @sandy081 please correct me if I am wrong.

**Comment by joaomoreno** [comment]
If so, feel free to close it down.

**Comment by RMacfarlane** [comment]
I think that's the case as well, I just added the workspace trust property to the auth extensions so should be fixed in the next insider's

**Comment by lszomoru** [comment]
Thank you @RMacfarlane. Closing the issue for now.
