### ISSUE TITLE
Compact terminal tabs actions look a bit broken

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121357]
I do like the "+" very much, but the arrow down feels off:

![image](https://user-images.githubusercontent.com/900690/114824235-e8cf9080-9dc4-11eb-88fc-c896ba8ae7a4.png)

![image](https://user-images.githubusercontent.com/900690/114824325-056bc880-9dc5-11eb-9383-f797e1f80632.png)

Would be great if a design could be found that makes the "+" and dropdown look more aligned in this case.

**Comment by Tyriar** [comment]
We want to copy the +v of the combined run menu, also it will be a little nicer tomorrow as it'll be centered.

**Comment by Tyriar** [comment]
Fix coming in https://github.com/microsoft/vscode/pull/121704

**Comment by bpasero** [comment]
Fancy 👏 

![image](https://user-images.githubusercontent.com/900690/116215467-ff240780-a747-11eb-8521-5748249bc8e2.png)
