### ISSUE TITLE
Continue not obvious enough that actually means "trust"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121305]
The default button of `Continue` is not obvious enough that it actually means "Trust and Continue"
Due to that I suggest to rename it to be "Trust and Continue"

![Screenshot 2021-04-14 at 19 20 09](https://user-images.githubusercontent.com/1926584/114752707-e3d3f800-9d56-11eb-8eb7-36b571c8a900.png)

**Comment by weinand** [comment]
I like the new trust dialog for debugging:

<img width="559" alt="2021-04-15_16-57-12" src="https://user-images.githubusercontent.com/1898161/114891394-20156000-9e0c-11eb-9ff9-f1cd67c5a53c.png">

**Comment by sbatten** [comment]
resolved with changes above

**Comment by isidorn** [comment]
Yup, adding verified label
