### ISSUE TITLE
Gear icon trust badge is delayed

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121363]
The status bar shows the state immediately 👌 but the gear icon badge comes a couple seconds late 😶.

![recording (5)](https://user-images.githubusercontent.com/22350/114829222-a9cb1c00-9d7f-11eb-9216-6d7247f72b3f.gif)

**Comment by lszomoru** [comment]
The gear icon badge is displayed due to the fact that there are extensions that are using `onStart`. At the moment the badge is being showed on a code path that is being executed at `LifecyclePhase.Eventually`. Probably it is safe to switch this to be executed at `LifecyclePhase.Restored`.

**Comment by lszomoru** [comment]
Fixed with 220560dd404064259d38f86c235866282c5d9e2b

**Comment by mjbvz** [comment]
Marking verified since I don't think you can get into this state anymore with the new modal flow
