### ISSUE TITLE
Syntax highlighting of Java "properties" files is broken with array syntax

### ISSUE THREAD

**Issue by ZigZag59** [microsoft/vscode#121370]
The syntax highlighting of Java "properties" files do not work with properties mapped with lists.

I am using SpringBoot with the @ConfigurationProperties directive for property mapping. My Java file contains a property : `List<String> myValues;`.

##### Steps To Reproduce
1. Open file with the ".properties" extension
2. Add the following lines :
project.properties.my-values[0]=value1
project.properties.my-values[1]=value2

##### Current Result
![SyntaxHighlightingResult](https://user-images.githubusercontent.com/46565570/114827287-c6d80d00-9dc8-11eb-9786-ff80d1118a5e.jpg)

##### Expected Result
![SyntaxHighlightingExpected](https://user-images.githubusercontent.com/46565570/114827293-c770a380-9dc8-11eb-9cc9-56dc84e59428.jpg)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.93GB free)|
|Process Argv|--folder-uri file:///c%3A/develop --crash-reporter-id 32702fb6-6220-4585-8559-0210ba5fa97e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
aadb2c|Azu|1.3.0
vscode-postgres|cko|1.1.17
gitlens|eam|11.4.1
vscode-lombok|Gab|1.0.1
gitlab-workflow|Git|3.18.0
vscode-drawio-insiders-build|hed|1.4.3
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
remote-wsl|ms-|0.54.6
azure-account|ms-|0.9.8
gradle-language|nac|0.2.3
oracledevtools|Ora|19.3.4
fabric8-analytics|red|0.3.2
java|red|0.76.0
vscode-commons|red|0.0.4
vscode-community-server-connector|red|0.23.12
vscode-rsp-ui|red|0.23.8
vscode-xml|red|0.16.0
vscode-gradle|ric|3.6.1
vscode-gradle-extension-pack|ric|0.0.2
scala|sca|0.5.3
vscode-checkstyle|she|1.4.0
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by alexr00** [comment]
@ZigZag59 can you confirm what language you have this file set to use? It's in the bottom right corner in the status bar by default. Just putting your cursor in the file then taking a screen shot and sharing that will also give me that info.

**Comment by ZigZag59** [comment]
Hello,

The selected language mode is "Properties".

![SyntaxHighlightingVsCode](https://user-images.githubusercontent.com/46565570/114885208-ba72a500-9e06-11eb-86eb-bb0919f053d8.jpg)

**Comment by alexr00** [comment]
So "Properties" is intended for ini files and files with a similar syntax, so I'm not too surprised that there's a problem here. 

We get the grammar we use for properties syntax highlighting from https://github.com/textmate/ini.tmbundle. However, there hasn't been a commit in that repo since 2013, so I'm not going to bother filing an issue there. Instead, I'll leave this issue open to see if there's wider interest in finding a new grammar to use.
