### ISSUE TITLE
Closing terminal with zsh exit status prompts error

### ISSUE THREAD

**Issue by sdegutis** [microsoft/vscode#121323]
Issue Type: <b>Bug</b>

When I have an error in zsh like from `rm doesnt-exist`, and I close the terminal via zsh (ctrl-d or `exit`), VS Code shows:

> "The terminal process "/bin/zsh '-l'" terminated with exit code: 1."
> [ Open Help ]

And that's just not helpful. I'm not sure when it ever is? It makes sense when the *shell itself* crashes, but zsh seems to propagate the last command's error to its own caller, which in this case means I often get this message. Please make it stop.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (3.30GB free)|
|Process Argv|-psn_0_5334294 --crash-reporter-id aa77e851-0fc5-45a8-b2b6-6d32c4e1f3ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.12.0
rainbow-csv|mec|1.8.1
dotenv|mik|1.0.1
vscode-js-profile-flame|ms-|0.0.15
material-icon-theme|PKi|4.6.0
rewrap|stk|1.14.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by Tyriar** [comment]
macOS returns this exit code for some reason, so we show it. You can suppress the notification with `"terminal.integrated.showExitAlert": false`
