### ISSUE TITLE
Wrong init width for terminal tab

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121314]
- VS Code Version: Insiders
- OS Version: macOS

* Turn on terminal tab from settings

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/876920/114762023-1d384380-9d16-11eb-8993-c68a7d8def11.png">

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
