### ISSUE TITLE
[SERIOUS] VSCode insider version delete my data which in installed folder

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#121352]
- VS Code Version:edge of vscode-insider
- OS Version: win10

Steps to Reproduce:

1. install vscode insider
2. creat a folder in vscode insider installed folder named `data`
![image](https://user-images.githubusercontent.com/1876302/114821177-bfc5f480-9df2-11eb-870e-015eff85c475.png)
3.  i use `mklink ` to redirect extensions and user-data folder to that `data` folder
4. vscode-insider upgrade the night version
5. `data` will be deleted

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
If you want to use portable mode, please use the ZIP archive, instead of the Setup. Read more: https://code.visualstudio.com/docs/editor/portable
