### ISSUE TITLE
Entering text too quickly into F2 variable rename cancels popup, fudges text

### ISSUE THREAD

**Issue by OneLookSigns** [microsoft/vscode#121311]
Issue Type: <b>Bug</b>

I tested this with JavaScript.

Pressing F2 on a variable in order to show the renamer-popup and then immediately typing something or pasting in text will cause the popup to disappear (you have to do this within milliseconds of pressing F2).

Depending on whether the variable is fully highlighted or the text-cursor is just on the text, whatever was pasted/typed will be inserted where the text-cursor is positioned without replacing the variable... or the variable be replaced but none of its following keywords will be renamed along with it. Therefore this issue has the potential to cause a user to accidentally break their code without realising for some time.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"new release"+label%3A"rename"
