### ISSUE TITLE
Improve workspace extension recommendation UI

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#12133]
How about we change the extension viewlet dropdown menu to contain this:

```
- Extension Recommendations
  - Show Recommendations
  - _separator_
  - Show Workspace Recommendations
  - Configure Workspace Recommendations
```

The configure action is currently surfacing only through the global commands.

**Comment by sandy081** [comment]
Hmm My opinion is not to grow the drop down.. If possible have those (less) options which are more useful and prominent. Regarding configuring, I do not think it will be used more often, so Command pallette is the right place. Also selecting this action takes us to the editor where as others not.

How about merging Workspace and normal recommendations to one entry and distinguish it while showing? As an user, I would see all of them as just recommendations irrespective of where they are coming from

**Comment by joaomoreno** [comment]
I meant it as submenus, which wouldn't make the first level grow, but shrink. It would add structure to the menu.

Having the action only as a global command is hiding it, we want to make it visible.

Your last suggestion is good and tracked by #8421

**Comment by sandy081** [comment]
@joaomoreno Simplified the menu. Hence closing this.

**Comment by ramya-rao-a** [comment]
@sandy081 What is the final say here?
I see the "Configure Recommended Extensions (Workspace)" in the stable build of 1.7.2 but not in Insiders

**Comment by sandy081** [comment]
@ramya-rao-a Joao simplified the menu by moving some commands, like one you specified, to Command Pallette in #14384.

**Comment by ramya-rao-a** [comment]
Got it. thanks
