### ISSUE TITLE
VCS Refresh

### ISSUE THREAD

**Issue by SturmB** [microsoft/vscode#121308]
Issue Type: <b>Bug</b>

It seems that the VCS is no longer auto-refreshing in VS Code. I now have to manually click the refresh icon on the Source Control tab to get the current branch, files status, etc.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (10.15GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/sturm/sites/Sky_web_2018 --remote=wsl+Ubuntu-20.04 --crash-reporter-id 40e57a87-d02d-4086-882a-b61d82e62f64|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2903)|
|Memory (System)|25.03GB (20.37GB free)|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
haproxy|bma|0.1.2
bracket-pair-colorizer-2|Coe|0.2.0
auto-rename-tag|for|0.1.6
ansible|haa|0.2.8
discord-vscode|icr|5.6.1
vscode-peacock|joh|3.9.1
vbscript|kar|0.5.5
ignore-files|lde|0.1.0
dotenv|mik|1.0.1
remote-wsl|ms-|0.54.6
debugger-for-chrome|msj|4.12.12
vscode-nginx|sha|0.6.0
vscode-autohotkey|sle|0.2.2
bootstrap4-vscode|the|6.1.0
hosts|tom|1.2.0
vscode-icons|vsc|11.4.0
vuetify-vscode|vue|0.2.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-nginx|wil|0.7.2
Bookmarks|ale|13.0.4
vscode-intelephense-client|bme|1.6.3
gitignore|cod|0.6.0
vscode-markdownlint|Dav|0.40.3
xml|Dot|2.5.1
gitlens|eam|11.4.0
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
rest-client|hum|0.24.5
vscode-gutter-preview|kis|0.27.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.12.1
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.33.1
indent-rainbow|ode|7.5.0
advanced-new-file|pat|1.2.2
vscode-css-peek|pra|4.1.3
LiveServer|rit|5.6.1
vscode-fileutils|sle|3.4.5
wordpress-snippet|tun|1.1.5
docker|vsc|1.0.0
yaml|vsc|1.0.0
gitmoji-vscode|Vtr|1.0.5
markdown-all-in-one|yzh|3.4.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwsldoc:30282072
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by vystepanenko** [comment]
Same here. 
Reproduced with dissabled all extensios. Only remote extension is on

VS Code version: Code - Insiders 1.56.0-insider (b4816cfd1f4161a3bb272354d181a9947760ee26, 2021-04-20T07:23:51.425Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.43GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/cannibal/projects/api_crm_service --remote=wsl+Ubuntu-20.04 --crash-reporter-id cac02e12-1b29-4401-90b4-691c0715a32a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (12 x 3700)|
|Memory (System)|12.42GB (6.32GB free)|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
remote-containers|ms-|0.169.0
remote-wsl|ms-|0.56.0
laravel5-snippets|one|1.12.0
material-icon-theme|PKi|4.6.0
code-settings-sync|Sha|3.4.3
errorlens|use|3.2.6
vscode-openapi|42C|4.5.0
vscode-sqlite|ale|0.12.0
vscode-intelephense-client|bme|1.6.3
vscode-tailwindcss|bra|0.5.10
better-phpunit|cal|1.5.3
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12
php-cs-fixer|jun|0.1.158
twig-language|mbl|0.9.2
vscode-deploy-reloaded|mkl|0.89.0
vscode-docker|ms-|1.12.1
snippet-creator|nik|0.0.5
vetur|oct|0.33.1
laravel-blade|one|1.25.0
advanced-new-file|pat|1.2.2
vscode-yaml|red|0.18.0
laravel-artisan|rya|0.0.27
code-spell-checker|str|1.10.2
code-spell-checker-russian|str|0.2.9
code-spell-checker-ukrainian|str|0.1.7
tabnine-vscode|Tab|3.4.3
vscode-import-cost|wix|2.15.0
ascii-unicode-escape|yar|0.1.0

(3 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
@SturmB, @vystepanenko are you still experiencing this issue with the latest version of VSCode?

**Comment by SturmB** [comment]
Since I am not currently seeing this issue, I'll go ahead and close it. If it is still happening for @vystepanenko or anyone else, I recommend they open a new issue.
