### ISSUE TITLE
Source Control always shows symlinks as modifications

### ISSUE THREAD

**Issue by wolf99** [microsoft/vscode#121304]
In large and busy repos this extra noise in the change listing is incredibly annoying 😕 
In quieter repos it only drives me slightly crazy 😄 

- VS Code Version: 1.55.2 (though I can't remember this ever *not* happening on earlier versions)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new repository:
   ```console
   ~$ mkdir foo

   ~$ cd foo

   ~/foo$ git init
   Initialized empty Git repository in ~/foo/.git/
   ```
2. Create a file and link to it from another location within the same repository, then add some contents to the file:
   ```console
   ~/foo$ touch myfile

   ~/foo$ mkdir bar

   ~/foo$ cd bar

   ~/foo/bar$ ln -s ../myfile mylink

   ~/foo/bar$ echo "boo" > mylink
   ```
3. Commit the changes so that there are no uncommitted modifications:
   ```console
   ~/foo$ git add .

   ~/foo$ git commit -m "First commit"
   [master (root-commit) bff7eb5] First commit
   2 files changed, 2 insertions(+)
   create mode 120000 bar/mylink
   create mode 100644 myfile

   ~/foo$ git status
   On branch master
   nothing to commit, working tree clean  # Look Ma, clean repo!
   ```
4. Open the repo in VS Code and check the Source Control tab where (as per above `git status` output above) there should be no modified files... but oh look, changes!
![image](https://user-images.githubusercontent.com/281700/114745904-0eb65000-9d47-11eb-8a07-7ac8dc005868.png)
 

Does this issue occur when all extensions are disabled?: Yes

**Comment by nrayburn-tech** [comment]
@wolf99 can you test and see if this is still an issue with the latest insiders?  I am having trouble reproducing with your steps.  If it is still an issue for you, this may have to do with a specific os or git version.

My steps, which as far as I can tell match yours.
```bash
nrayburn@m255 desktop % mkdir test
nrayburn@m255 desktop % cd test
nrayburn@m255 test % git init
Initialized empty Git repository in /Users/nrayburn/Desktop/test/.git/
nrayburn@m255 test % touch file
nrayburn@m255 test % mkdir folder
nrayburn@m255 test % cd folder
nrayburn@m255 folder % ln -s ../file link
nrayburn@m255 folder % echo "content" > link
nrayburn@m255 folder % cd ..
nrayburn@m255 test % git add .
nrayburn@m255 test % git commit -m "commit"
[main (root-commit) 4a8bfdd] commit
 2 files changed, 2 insertions(+)
 create mode 100644 file
 create mode 120000 folder/link
nrayburn@m255 test % git status
On branch main
nothing to commit, working tree clean
nrayburn@m255 test % code-insiders .
```
Check scm tab > No changes found.

**Comment by wolf99** [comment]
Sorry I don't have insiders.

I have just updated to 1.56 stable however and the issue is no longer present when running VSCode remotely on WSL.

However, the issue is still present when running VSCode locally on Windows.
Although in this case, the Windows Git installation also gives the following result for the git status:
```console
C:\Users\{user}\test>git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   folder/link

no changes added to commit (use "git add" and/or "git commit -a")
```
Additionally when running on Windows there is a slight difference in that trying to open the link from the VSCode explorer results in a toast showing the following error:
>Unable to open 'link (Working Tree)': Unable to read file 'c:\Users\{username}\test\folder\link' (Unknown (FileSystemError): Error: EINVAL: invalid argument, readlink 'c:\Users\{username}\test\folder\link'). 

I assume this error is related to Git's or the OS's handling of symlinks rather than VSCode's. 
It would be nice if this worked properly on the Windows side too, but I think that is outside the scope of this issue.
Having said that, IIRC the test shown in my original post was done on Windows somehow 🤷‍♂️.

**Comment by wolf99** [comment]
Some more testing on what is happening on Windows and its really weird.

All of the following is running VSCode locally on Windows.

My original tests were on a work laptop that runs WSL2 on Windows 1909. 
On this one the initial issue is still there. 
The file is shown OK in VSCode explorer and opens fine in VSCode. 
In Windows file explorer the symlink shows as a file with a shortcut overlay (little blue curved arrow on bottom right corner of file icon)

I'm now on my personal laptop that runs WSL2 on Windows 20H2. 
Here VSCode wont even show the symlink in the VSCode  explorer! 
Additionally the Windows file explorer displays the link as just a file rather than a file with a shortcut overlay.

Links made via `mklink` in cmd work fine on both machines

Not strictly a VSCode problem on this part I know, but anyone any clues on what might be going on?

**Comment by nrayburn-tech** [comment]
This seems like a Windows/WSL issue, so I don't think I can help much more.  The only other thing I can offer, is try to update your git version.

Just for comparison, this is my info where I am not having the reported issue.
Version: 1.57.0-insider (Universal)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T18:11:54.098Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
Git: 2.31.0

**Comment by wolf99** [comment]
Thanks for the effort @nrayburn-tech .

Closing as the remaining issue seems to be unrelated to vscode.
