### ISSUE TITLE
Failed to Initialize JS/TS language features

### ISSUE THREAD

**Issue by NoumanMukhtar** [microsoft/vscode#121378]
Issue Type: <b>Bug</b>

Whenever I open my vscode, it starts initializing js/ts language features and after a while it shows an error message that it fails to initialize.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
