### ISSUE TITLE
Switching Themes = Sync turned off; reason = too many requests

### ISSUE THREAD

**Issue by stackmystack** [microsoft/vscode#121380]
Issue Type: <b>Bug</b>

I was switching between themes to see the new Github themes for vsc, when I got a notification telling me that Sync is turned off because I made too many requests.

VS Code version: Code - Insiders 1.56.0-insider (394a2e4779ff767e2761a59a51b15848dcd24173, 2021-04-13T11:13:44.235Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.53GB free)|
|Process Argv|--crash-reporter-id 25cfdb70-9d38-4ae5-acbe-04680378551b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.0
vscode-neovim|asv|0.0.78
calva|bet|2.0.187
emojisense|bie|0.8.0
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.1.0
transformer|dak|1.11.1
vscode-markdownlint|Dav|0.40.3
gitlens|eam|11.4.1
vscode-firefox-debug|fir|2.9.3
todo-tree|Gru|0.0.211
haskell|has|1.2.0
hoogle-vscode|jca|0.0.7
better-cpp-syntax|jef|1.15.5
svg|joc|1.4.5
language-haskell|jus|3.4.0
magit|kah|0.6.9
rust-analyzer|mat|0.2.554
Lisp|mat|0.1.11
git-graph|mhu|1.30.0
vscode-docker|ms-|1.12.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.6.751425733
remote-containers|ms-|0.167.0
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
remote-wsl|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0
hexeditor|ms-|1.5.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
poe-filter-language|Nev|1.3.0
polacode|pnp|0.3.4
subtle-brackets|raf|3.0.0
vscode-yaml|red|0.18.0
crates|ser|0.5.7
even-better-toml|tam|0.12.1
latex-support|tor|3.6.0
cmake|twx|0.0.17
luna-paint|Tyr|0.4.0
errorlens|use|3.2.5
vscode-lldb|vad|1.6.1
markdown-all-in-one|yzh|3.4.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoccf:30278406
vspre833:30267464
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfiletext:30288477
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

Many others point to #91286
