### ISSUE TITLE
Untitled model should not be resolved to open

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121359]
Seeing this code:

* [ ] https://github.com/microsoft/vscode/blob/090554355df53708754cd38910b6cce0b5312fbe/src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts#L583-L590
* [ ] https://github.com/microsoft/vscode/blob/5144d664926f23b137f24a5649f20981ca364fca/src/vs/workbench/contrib/notebook/browser/view/output/transforms/textHelper.ts#L32-L41

I think a better solution would be `editorService.openEditor({ contents: metadataSource, mode: 'json' })` for better lifecycle concerns.

**Comment by jrieken** [comment]
@rebornix Don't we already have virtual document provider for these resources? The `CellMetadataContentProvider`? Iff so we should be able to simply open them without going through the unititled-file world. Afaik you can also save-as those virtual documents

**Comment by bpasero** [comment]
> Afaik you can also save-as those virtual documents

Yes that is possible since a couple of months (or 1 year?).

**Comment by rebornix** [comment]
> Don't we already have virtual document provider for these resources

yes we do. I think I was not aware of editable virtual document provider when adding this code but yeah let's move to that.
