### ISSUE TITLE
Consider a dropdown menu for the terminal dropdown

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121355]
I find the distance here from action to quick pick quite long, especially since the icon seems to indicate it opens a menu right where I click:

![recording](https://user-images.githubusercontent.com/900690/114824137-c0479680-9dc4-11eb-95ca-4e85ba2cd3fb.gif)

**Comment by bpasero** [comment]
Similar problem for the "+" actually:

![image](https://user-images.githubusercontent.com/900690/114824188-d3f2fd00-9dc4-11eb-8b10-cc2e1264e369.png)

**Comment by meganrogge** [comment]
Yep this is our plan - was how we originally had it and we're going back to that 👍🏼
