### ISSUE TITLE
Unable to install the latest version

### ISSUE THREAD

**Issue by YowFung** [microsoft/vscode#121367]
Every day an automatic upgrade dialog pops up but fails every time. It always shows that I have other processes that haven't closed yet. But I've actually completely shut down all other processes related to Visual Studio Code (except this installer). 
Later I simply went directly to the official website to download the latest installation package and manually installed it. Not successful. And now I cannot start Visual Studio Code anyhow.

I didn't capture the picture about the error of auto-upgrade.

The screenshot for failed to manually install the latest version:
![image](https://user-images.githubusercontent.com/26346560/114832699-5c8f8e80-9e01-11eb-9a29-93440144b053.png)

After the manual installation fails, I will not be able to launch it again. It will pop up a dialog box like this:
![image](https://user-images.githubusercontent.com/26346560/114832100-afb51180-9e00-11eb-97ca-b5982d345e88.png)

**Comment by yume-chan** [comment]
Maybe manually delete the installation folder and re-install will help?

**Comment by YowFung** [comment]
@yume-chan Delete it manually and then reinstall it can be fixed. But now there is a new version of it I need to update, still can't automatically update. Do I have to do this every time a new version comes out? Can you tell me how to forbid it to pop up the automatic update dialog box?

**Comment by yume-chan** [comment]
> Can you tell me how to forbid it to pop up the automatic update dialog box?

Set `"update.mode": "none"`

**Comment by YowFung** [comment]
@yume-chan Thanks.
