### ISSUE TITLE
Add option to remove "Learn more about JS/TS refactorings"

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#121374]
There should be an option to remove this action item:
![image](https://user-images.githubusercontent.com/1658949/114843949-a0bb6880-9dda-11eb-9f13-6214baf7748c.png)

There is a time in the life of a TypeScript developer where they no longer need this tutorial hint every single time they want to apply a code action. In fact, it's getting in the way when navigating the menu.

Thus, it seems beneficial to be able to disable such onboarding elements.

**Comment by OoDeLally** [comment]
This would be great indeed!

Additionally, as mentioned in https://github.com/microsoft/vscode/issues/123948, it would be nice to be able to disable some of the unnecessary code actions provided by some of the built-in extensions.
