### ISSUE TITLE
Paste using CTRL-V stops working

### ISSUE THREAD

**Issue by LoungeFlyZ** [microsoft/vscode#121340]
Issue Type: <b>Bug</b>

Paste using CTRL-V stops working. Honestly, i dont know how to repro.  It will work for a while and then stop working (seemingly) randomly. 

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (13.38GB free)|
|Process Argv|--crash-reporter-id 3a3c243d-7b17-487d-995b-07a84f4a3f11|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.23.11
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by tymsai** [comment]
> Issue Type: Bug
> 
> Paste using CTRL-V stops working. Honestly, i dont know how to repro. It will work for a while and then stop working (seemingly) randomly.
> 
> VS Code version: Code 1.55.1 ([08a217c](https://github.com/microsoft/vscode/commit/08a217c4d27a02a5bcde898fd7981bda5b49391b), 2021-04-07T15:06:02.360Z)
> OS version: Windows_NT x64 10.0.19042
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)
> GPU Status	2d_canvas: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> oop_rasterization: enabled
> opengl: enabled_on
> protected_video_decode: unavailable_off
> rasterization: enabled
> skia_renderer: enabled_on
> video_decode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> Load (avg)	undefined
> Memory (System)	31.94GB (13.38GB free)
> Process Argv	--crash-reporter-id 3a3c243d-7b17-487d-995b-07a84f4a3f11
> Screen Reader	no
> VM	0%
> Extensions (2)
> Extension	Author (truncated)	Version
> csharp	ms-	1.23.11
> vscode-proto3	zxh	0.5.3
> A/B Experiments
> ```
> vsliv368:30146709
> vsreu685:30147344
> python383:30185418
> pythonvspyt700cf:30270857
> vspor879:30202332
> vspor708:30202333
> vspor363:30204092
> vswsl492:30256859
> vstry244:30276681
> pythonvsdeb440:30248342
> pythonvsded773:30248341
> pythonvspyt875:30259475
> pythonvspyt639:30281910
> pythontb:30283811
> wslfolderdoc:30282074
> vspre833:30267464
> pythonptprofiler:30281270
> vsdfh931:30280409
> vshan820cf:30276953
> pythondataviewer:30285071
> vscus158cf:30286554
> ```

It may be a mechanical problem of your keyboard.

**Comment by connor4312** [comment]
Please check out https://github.com/microsoft/vscode/wiki/Keybinding-Issues and share more info if the troubleshooting steps don't solve your problem

**Comment by gjsjohnmurray** [comment]
Looks like #115396
