### ISSUE TITLE
Support automatically updating URL import references when using `new URL(<file>, import.meta.url)`

### ISSUE THREAD

**Issue by TimvdLippe** [microsoft/vscode#121391]
- VS Code Version:1.55.1
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

Given the following files:

`folder/file1.ts`
```ts
console.log('file1');

export const foo = 42;
```

`different-folder/file2.ts`
```ts
new URL('../folder/file1.js', import.meta.url);
import('../folder/file1.js');

export const bar = 5;
```

1. Create a new directory `sub-folder/` in root
2. Move `different-folder/` into `sub-folder/` so that the layout becomes `sub-folder/different-folder/file2.ts`
3. When prompted for "Update imports for 'different-folder'?" click "Yes"

Expected result:

Similar to the dynamic import, a file reference based on `import.meta.url` that points to a different TypeScript file should correctly be renamed accordingly.

`sub-folder/different-folder/file2.ts`
```ts
new URL('../../folder/file1.js', import.meta.url);
import('../../folder/file1.js');

export const bar = 5;
```

Actual result:

`sub-folder/different-folder/file2.ts`
```ts
new URL('../folder/file1.js', import.meta.url);
import('../../folder/file1.js');

export const bar = 5;
```

The same is true if `folder/file1.js` is moved to a different location.

Does this issue occur when all extensions are disabled?: Yes

**Comment by TimvdLippe** [comment]
I am confused as to why this issue was closed as a candidate for an extension. VS Code supports the standard dynamic import to handle file renaming. Since `import.meta.url` and `URL` are a standard way of resolving files, I would expect VS Code to natively support it as well. For example, Parcel compatibility is implemented in https://github.com/parcel-bundler/parcel/issues/5473, is implemented in Webpack 5 https://github.com/webpack/webpack/pull/11075 and is scheduled for implementation in ESBuild https://github.com/evanw/esbuild/issues/312#issuecomment-800730525

@mjbvz Given the above, do you mind reopening the PR given that this is standard way of importing relative files and supported in various bundlers?

**Comment by mjbvz** [comment]
If you feel this has enough adoption, please file an issue against TypeScript

**Comment by TimvdLippe** [comment]
Done: https://github.com/microsoft/TypeScript/issues/43759 Thanks!
