### ISSUE TITLE
Unable to write to User Settings because terminal.integrated.shell.windows is not a registered configuration.

### ISSUE THREAD

**Issue by PiccoloYu** [microsoft/vscode#121349]
- VS Code Version:1.55
- OS Version:win10

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/44945137/114819494-2269c100-9df0-11eb-840a-1e8dd750c694.png)

2.
![image](https://user-images.githubusercontent.com/44945137/114819508-2ac1fc00-9df0-11eb-9692-6dd29ad70a34.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Simon7520** [comment]
I also had this issue， how to solve it ?
