### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by pratikkute** [microsoft/vscode#121381]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.55.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 185,
		"activateCallTime": 376,
		"activateResolvedTime": 103,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:javascriptreact"
		}
	},
	"runtimeErrors": []
}
```

**Comment by Luke-zhang-04** [comment]
I'm getting the same problem.

- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Linux x64 5.11.13-arch1-1`
- VS Code version: `1.55.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 34,
		"activateCallTime": 94,
		"activateResolvedTime": 34,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": []
}
```

![image](https://user-images.githubusercontent.com/55749227/114889255-f2162880-9dd7-11eb-9475-e06a8bd11c39.png)

The extension is unresponsive and freezes typing

My console looks like this
`WARN UNRESPONSIVE extension host, 'vscode.typescript-language-features' took 94% of 7349.783ms, saved PROFILE here: 'file:///tmp/exthost-b57b90.cpuprofile'`

And 
`WARN Error: Aborted onWillSaveTextDocument-event after 1750ms at mainThreadSaveParticipant.ts:39`

This is what `code --status` looks like while the editor is frozen

![image](https://user-images.githubusercontent.com/55749227/114889815-71a3f780-9dd8-11eb-9849-c63ded1c5b40.png)

**Comment by Luke-zhang-04** [comment]
Process explorer:
![image](https://user-images.githubusercontent.com/55749227/115316171-d51a8600-a146-11eb-83b6-779a41483ab7.png)

![image](https://user-images.githubusercontent.com/55749227/115316471-6d186f80-a147-11eb-9451-593976c8f034.png)

Run with Extensions Disabled: works fine. Also works when I disable TS and JS language features

[CPU profile](https://github.com/microsoft/vscode/files/6339661/CPU-20210419T235050.812Z.cpuprofile.txt)

**Comment by mjbvz** [comment]
@Luke-zhang-04 Please open a separate issue with those logs

**Comment by Luke-zhang-04** [comment]
So I just ran extension bisect and it looks like the issue was actually with the Vim extension, which is weird considering everything else pointed to the typescript extension, and disabling the typescript extension fixed my problems. Disabling the Vim extension seems to have fixed the problems. Sorry for the bother.

**Comment by mjbvz** [comment]
Closing since this is not useful without more info
