### ISSUE TITLE
Pined search tabs should not be reused

### ISSUE THREAD

**Issue by Trismegistos84** [microsoft/vscode#121365]
In every IDE I know pinning search tab freezes it and cause new searches to be launched in new tab. This is very convenient when you search for multiple things. VSC has option to pin search tab but it only moves it to the left of tab bar. It would be convenient if clicking "find in files" or "ctrl-shift-f" would not reuse pinned tab.

**Comment by JacksonKearl** [comment]
I'm guessing you're using `search.mode: reuseEditor`? If so this is as-designed. You can set up a keybinding to run `search editor: new search editor` and use that to create new editors, or change the search mode to use a new editor. It's not clear to me that pinned tabs should not be reused - what if I want to do all my searches in one tab and keep that tab pinned for easy access?
