### ISSUE TITLE
vs code don't open erroe

### ISSUE THREAD

**Issue by JDBHATT007** [microsoft/vscode#121375]
Issue Type: <b>Bug</b>

when i start the vscode i need to wiat for sometimes because it will prompt me that unable to load vs code please reopen it or close it.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that prompt?
