### ISSUE TITLE
Remote-SSH is now broken for me

### ISSUE THREAD

**Issue by vrmerlin** [microsoft/vscode#121327]
Issue Type: <b>Bug</b>

My VSC is now broken on the latest update (version 1.55.2), because my remote RH7 linux system has too old of a version of wget (1.14).  it's failing because I dont have the "--no-hsts" option. It's preventing me from using remote SSH at all. 

I don't have the ability to upgrade my wget version.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 6305f91a-23c6-4810-b097-0cbcdb3d23ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.2
remote-ssh-edit|ms-|0.65.2
puppet-vscode|pup|1.2.0
vscode-gradle|ric|3.6.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by thechairman007** [comment]
Same for our whole team.

**Comment by PanosBougas** [comment]
Same issue here.

Just downgraded back to 0.65.1 for both `Remote - SSH` and `Remote - SSH: Editing Configuration Files` extensions, that solved the issue for me.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4416
