### ISSUE TITLE
Trust related settings don't show up the first time

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121362]
1. Open an untrusted workspace
2. Open the trust editor
3. Click the settings link
4. 🐛 Settings editor shows no settings related to trust
5. Close settings editor
6. Click the settings link again, works ✔️

![recording (4)](https://user-images.githubusercontent.com/22350/114829012-6d97bb80-9d7f-11eb-90d9-659593001585.gif)

**Comment by lszomoru** [comment]
Adding @sandy081 as well since he has added the settings link.

**Comment by sandy081** [comment]
Seems to be the bug in Settings tree editor - When trying to open workspace settings with a filter, filter is applied on user settings and then switched to workspace settings. 

@roblourens Added a fix. Hope it's ok. Please feel free to change it if there is a better fix.

**Comment by roblourens** [comment]
Thanks @sandy081!
