### ISSUE TITLE
I can't disable all :hover-like snippets/labels in the editor

### ISSUE THREAD

**Issue by kyssproject** [Microsoft/vscode#12131]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Try to eliminate any help, suggestion, hint or so that appears when you locate your mouse over any word in the editor by adding this to the settings.jsono file

// Place your settings in this file to overwrite default and user settings.
{
        "editor.quickSuggestions": false,
	"editor.quickSuggestionsDelay": 1000,
	"editor.suggestOnTriggerCharacters": false,
	"editor.wordBasedSuggestions": false,
	"editor.parameterHints": false,
	"editor.snippetSuggestions": "none",
}

2. See that you still have at least one help panel

**Comment by alexandrudima** [comment]
Do you want to also shut down the hover via `editor.hover: false` ?

**Comment by kyssproject** [comment]
Well, by adding `editor.hover:false` there's nothing more appearing there. The question is .... I didn't know of this one, it doesn't appear in the Default Settings file, is there any other place I should look for commands?

**Comment by alexandrudima** [comment]
The editor has lots of knobs. Some are hard-coded to some values in VSCode and others we don't expose to prevent settings nausea :).

The `IEditorOptions` is the definitive list (in https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts).

Are you in a happy spot now? (i.e. ok to close this issue?)

**Comment by kyssproject** [comment]
Yes, completely happy, thanks a lot :)
