### ISSUE TITLE
New window, Open File should replace untitled file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#12134]
1. Open a new window
2. Open an existing file

You'll have 2 tabs open: the original Untitled file and the selected file.

In the case the Untitled file is unmodified, it should be replaced by the selected file.

**Comment by bpasero** [comment]
In the end what we really want is Sublimes "untitled editor" as background:

![image](https://cloud.githubusercontent.com/assets/900690/18581634/c3dee2d8-7c01-11e6-9f2c-d2e241ddd1c0.png)

This one is not even a tab until you start typing:

![image](https://cloud.githubusercontent.com/assets/900690/18581641/ce7f59b6-7c01-11e6-9fde-adaa46d389f8.png)
