### ISSUE TITLE
Word selection is incomplete for C++ identifiers containing certain allowed characters

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#121343]
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Use the following code in a C++ file (test.cpp) :

```cpp
int main()
{
    int abc$$$xyz;
    abc$$$xyz = 1;
    return 0;
}
```

This code compiles.

2. Double-click within "abc".  Note that only "abc" is selected.  The "$"'s are valid within identifiers in C++, so should have been included in the selection.
3. (With the C/C++ Extension also installed) Right-click anywhere in the identifier, and select "Rename Symbol" from the context menu.  Note that the identifier is not fully included in the rename field.

Does this issue occur when all extensions are disabled?: Yes (Step 2)

Based on https://github.com/microsoft/vscode/issues/51084 , it looks this could be solved by the `wordPattern` in the language configuration.  Looking in the `language-configuration.json` for built-in `cpp` extension, I don't see a `wordPattern` specified there.  Maybe it's using the default?

Perhaps a `wordPattern` should be added to `cpp` that reflects allowable characters in C++ identifiers?

**Comment by aeschli** [comment]
@Colengms I'm a bit puzzled as searching for 'valid characters c++ identifier' doesn't mention `$` (https://en.cppreference.com/w/cpp/language/identifiers) or even says it is not permitted. https://fresh2refresh.com/cpp-tutorial/cpp-identifiers-and-keywords/

But I'm happy to add it. We currently use the same language configuration c and c++. What's with `$` i plain c ?

**Comment by Colengms** [comment]
It looks like the dollar sign is special, and support has crept into most C++ compilers.  https://stackoverflow.com/questions/7926394/dollar-sign-in-variable-name

I've tested the example on cl.exe, gcc, and clang, on Windows, Mac, and Linux, x64 and x86, and they all accept it.

MSDN mentions that it's supported in cl.exe (but implies it's non standard).  https://docs.microsoft.com/en-us/cpp/cpp/identifiers-cpp?view=msvc-160

GCC supports it (unless not supportable due to the target assembler): https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html#Dollar-Signs  "because many traditional C implementations allow such identifiers"

Clang supports it likely due to its high level of compatibility with gcc.

It looks like it's an extension and not part of the standard, but would be accepted by the compilers used by most users.
