### ISSUE TITLE
Select git remote to push to, when upstream is configured

### ISSUE THREAD

**Issue by vchegwidden** [Microsoft/vscode#12135]
For some projects I have multiple remotes set up. 
It would be really nice to have an option to choose the remote to push to like in git-gui and visual studio team explorer

**Comment by joaomoreno** [comment]
When a branch has an upstream configured, it will just pushed to that. Otherwise, Code will ask you to which remote do you want to push.

I assume you want to push to a different remote, even when the branch has an upstream configured.

**Comment by vchegwidden** [comment]
@joaomoreno  yes that is correct

**Comment by Krzysztof-Cieslak** [comment]
Can be closed, released in 1.7 (October 2016)

**Comment by joaomoreno** [comment]
Thanks for the ping!
