### ISSUE TITLE
Webviews should use onWillMoveEditor

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#121322]
Currently Webviews (and by extension custom editors) require the input to know what group they're being opened in to handle the moving of the webview without a re-render. I recently added `onWillMoveEditor` for notebooks to handle this case. This should be adopted to remove the dependency on knowing about the group.

**Comment by mjbvz** [comment]
@lramos15 I looked into this but it seemed like adopting onWillMoveEditor would actually complicate the webview code (we'd have to move the webview into a pool where it can then be adopted by another editor?)

Does webviews not adopting this block your work in any way?

**Comment by lramos15** [comment]
> Does webviews not adopting this block your work in any way?

No, it's just more debt. It was weird to me that WebviewEditorInputs are the only ones that need to know about the group. All other editor inputs don't need the group.

**Comment by mjbvz** [comment]
Ok thanks for the background. We expose the group in the public webview API. Adopting `onWillMove` would make that a bit easier, but we'd still have the problem of transferring the webview itself between editors. IMO the current implementation is simpler for that so I'm going to close this issue for now. May revisit it in the future though
