### ISSUE TITLE
Scrolling through Themese causes sync storm on setting sync....

### ISSUE THREAD

**Issue by wdarm** [microsoft/vscode#121394]
Issue Type: <b>Bug</b>

Enable setting sync...
Open Visual Theme List
Use arrow keys to scroll through to select a new theme.

You will get a message box that setting sync is being disabled due to too much activity.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 21|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id fcdc629f-02ab-4802-ad34-2c6091354db8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
makeRunner|ale|0.1.2
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.1.0
algorithm-mnemonics-vscode|dav|1.0.3
vscode-dash|dee|2.4.0
gitlens|eam|11.4.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-pull-request-github|Git|0.25.1
CppSnippets|har|0.0.15
vscode-power-mode|hoo|2.2.0
better-cpp-syntax|jef|1.15.5
vscode-clang|mit|0.2.3
prettify-json|moh|0.0.3
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
vscode-remote-extensionpack|ms-|0.20.0
cpptools|ms-|1.3.0
cpptools-extension-pack|ms-|1.0.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
code-spell-checker|str|1.10.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12
material-theme|zhu|3.10.13

(56 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30286881

```

</details>

**Comment by gjsjohnmurray** [comment]
/duplicate

Many others point to #91286
