### ISSUE TITLE
File too large to open - but only 700meg

### ISSUE THREAD

**Issue by ZtrevorZ** [microsoft/vscode#121301]
Issue Type: <b>Bug</b>

Hi when opening a 700meg file it says "file cannot be opened in the editor because it is too large". I already set set memory for large files = 8192. It used to work well for files of 2gig+ before this update. Would be nice if this can be fixed

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.5.745244803

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30286881

```

</details>

**Comment by bpasero** [comment]
Can you make that file available somehow?

**Comment by ZtrevorZ** [comment]
[Sample_file - first 100 lines.txt](https://github.com/microsoft/vscode/files/6315863/Sample_file.-.first.100.lines.txt)

Hi thanks for replying. I see now the cause are some unicode "control characters". If I change those to ordinary ASCII then the file opens in VC. Here is a file with the first 100 lines. A file consisting of simply the first line repeated 1367846 times, will recreate the problem. The resulting file is then 684 meg or 718 119 150 bytes. If you would rather like the full file, you can say what the best way would be for me to upload it. We could also change the title of this thread to something like "file with unicode control characters won't open" I guess. Much appreciated!

**Comment by bpasero** [comment]
>  I see now the cause are some unicode "control characters". 

Can you prepare a file that contains those characters? We have some logic to detect if a file is binary or not, mainly looking for zero-bytes and then refuse to show the file in the text editor.

**Comment by ZtrevorZ** [comment]
Hi the small sample file above has the characters. They are at col 308 (4 chars) and then on about 7 subsequent places (4 chars each). When I try to open the small file above, VC says at first "this file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway". When I click on "anyway" the funnies show as NUL. I only realised later that these chars are the problem, sorry. It would be nice though to have seen the encoding warning before the big file warning. I can easily upload the big file somewhere if you like .. Github won't allow me to do it here in this thread, but maybe there is an alternative location we could use e.g. my own main (sadly a bit empty) Github page? What do you suggest. Thanks again

**Comment by bpasero** [comment]
I decided to simply remove the logic that would try to check on the size of the file and now we always show the message that allows to open the editor differently, given we have protections in place that guard against opening too large files.

**Comment by bpasero** [comment]
**Verification:** open a file > 200 MB containing a `0x00` zero byte sequence and verify you are offered to open it in the text editor.

**Comment by ZtrevorZ** [comment]
Hi thank you so much for the effort! Yes this is a good solution, then one knows what is going on. 
Would I have to download a test version of VC for this ... or is it already in the latest update?

**Comment by ZtrevorZ** [comment]
Works now in VC insiders! Thanks so much /verified
