### ISSUE TITLE
Make setting up a tuned TypeScript project easy as 🥧

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121345]
Currently it takes quite a bit of product knowledge to set up a TypeScript project and get all the nice features VS Code has to offer. Examples:

- What should my tsconfig.json include?
- How can I run my project?
- How can I get debugging to work?
- How should I run my build/watch?
- How can I set up tests?
- How should I lint/format the code?

And probably lots more...

This issue tracks making these questions easy to answer, the starting point for this will be developing `start` list contributions to instantiate template folders that have been tuned to make the development/build/test/debug process as seamless as possible.

**Comment by JacksonKearl** [comment]
cc @gcrev93, @DanielRosenwasser

**Comment by connor4312** [comment]
Something that would remove one toekick for generic TS setup would be in the compiler would create sourcemaps by default. I'm sure there's reasoning behind why it's not the case, but I couldn't find it and I think sourcemaps are desired in vastly more cases nowadays than they're undesired.

**Comment by digitarald** [comment]
Adding to the list of ideas:

- Detecting/installing Node/NPM & typescript package
- TS Playground

**Comment by gcrev93** [comment]
Just chiming in:

I think we can help with the tsconfig question by using the basic tsconfig created when you run `tsc --init` ! Its well commented and gives explanation on each option in the file

It would also be great for Compile and Running your projects to potientially be as easy as a button click.

I do agree node packages being detected/installed as well.
