### ISSUE TITLE
The menu tree on the left is really great. Can you open source it

### ISSUE THREAD

**Issue by stjava** [microsoft/vscode#121366]
The performance of this menu is very good. At the same time, it supports right-click menu and is beautiful enough. I really like it

![image](https://user-images.githubusercontent.com/20898173/114830541-e1c57400-9dfe-11eb-9905-c9cd774962a6.png)

**Comment by sbatten** [comment]
This is an open source repository, so I am not sure what the issue is about.

**Comment by joaomoreno** [comment]
Thanks for the praise, we put in a lot of effort into it. Unfortunately creating a component out of the list/tree view isn't in the nearby future for us. Sorry about that!
