### ISSUE TITLE
Re-layout the terminal tabs as you drag the sash

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121333]
Currently, the terminal tabs view doesn't update until you release the sash, and imo it should be updating live.

**Comment by Tyriar** [comment]
It's debounced by the sash and will resize when you pause briefly even without releasing. I think this is ideal since resizing a terminal so often is both slow since it's an expensive operation for a large buffer and could cause strange wrapping.

**Comment by eamodio** [comment]
That's not the behavior I am seeing -- it never changes while I'm dragging. The terminals resize, but the tabs don't.
![tabs](https://user-images.githubusercontent.com/641685/114808119-a59a0100-9d75-11eb-965a-5f6e94476951.gif)

**Comment by Tyriar** [comment]
Oh if you mean the tabs then this is a dupe of https://github.com/microsoft/vscode/issues/121235
