### ISSUE TITLE
Error Loading Webview

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#121302]
Issue Type: <b>Bug</b>

When trying to load a page that shows a web view (HexEditor, "Change Log" page of an extension), an error is shown:

![image](https://user-images.githubusercontent.com/13488/114742179-76ee3d00-9d19-11eb-8c78-54034fa96d14.png)

![image](https://user-images.githubusercontent.com/13488/114742199-7ce41e00-9d19-11eb-9baf-493840ab6618.png)

VS Code version: Code - Exploration 1.56.0-exploration (37dee411c81abf7d8ecb28ffe218475c328578b8, 2021-04-09T10:48:12.625Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|11.2.10
path-intellisense|chr|2.3.0
vscode-eslint|dba|2.1.20
output-colorizer|IBM|0.1.2
git-graph|mhu|1.30.0
mads|mir|0.0.5
csharp|ms-|1.23.11
cpptools|ms-|1.3.0
hexeditor|ms-|1.5.0
js-debug-companion|ms-|1.0.9
js-debug-nightly|ms-|2021.4.1317
vscode-typescript-next|ms-|4.3.20210413
vscode-typescript-tslint-plugin|ms-|1.3.3
debugger-for-chrome|msj|4.12.12
mvbasic|mve|2.1.2
ossaction|pga|1.0.0
material-icon-theme|PKi|4.6.0
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.3.15
pick|Tra|1.1.2
flatuscode|Vin|1.1.1
vscodeintellicode|Vis|1.2.12

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by mjbvz** [comment]
Closing as this is specific to the exploration build. The official insiders seems to work fine
