### ISSUE TITLE
Markdown text referring to markdown filetypes wrongly generates unsafe links in markdown preview

### ISSUE THREAD

**Issue by rnickle** [microsoft/vscode#121309]
- VS Code Version: 1.55.2 (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1.Open a new file and give it an '.md' extension (example, save-as X.md)
2.Ctrl-K V to "open a preview to the side"
3.Type XYZZY.md or README.md or TEST.md and preview will generate links to http://XYZZY.md, http://README.md and http://TEST.md respectively.

Version 1.55.2 (user setup)

Does this issue occur when all extensions are disabled?: Yes, I ran it with code --disable-extensions.

![image](https://user-images.githubusercontent.com/32749826/114754778-f1718980-9d26-11eb-8e80-58c3028750e0.png)

Took another screenshot to more strongly indicate that other 'file-like' text is not interpreted as links:

![image](https://user-images.githubusercontent.com/32749826/114755133-53ca8a00-9d27-11eb-9674-05773311d2b5.png)

**Comment by mjbvz** [comment]
This is the markdown linkifier:

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22README.md%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

You can disable `markdown.preview.linkify` if it is causing problems
