### ISSUE TITLE
Add support for onDidDispose event in NotebookCommunication

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121331]
Would be good to enable this:
```typescript
    /**
     * Communication object passed to the {@link NotebookContentProvider} and
     * {@link NotebookOutputRenderer} to communicate with the webview.
     */
    export interface NotebookCommunication {

        // @rebornix
        // readonly onDidDispose: Event<void>;
    }

```

Today its possible user has opened a notebook multiple times, and Jupyter extension ends up creating a lot of event handlers (tracking messages that needs to be dispatched to each view for ipywidgets) & the like for each of these.
If a user closes a split view, it would be good to clear the associated resources.

@rebornix /cc

**Comment by rebornix** [comment]
This will be replaced by `NotebookController`.

**Comment by jrieken** [comment]
Yes - the communication is now bound to the notebook controller and its lifecycle. It's extensions that control that.

**Comment by jrieken** [comment]
@DonJayamanne please keep me updated how the new API works for you and if this is still a desire

**Comment by DonJayamanne** [comment]
> please keep me updated how the new API works for you and if this is still a desire

Working on this today, after taking a whole week off Notebooks.
Will be hooking up IPyWidgets with the new push model.
Closing this issue as we'll be moving to the new API.
Thanks
