### ISSUE TITLE
Notebook renderer receiving internal messages

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121441]
* have a renderer like below
* notice how receives internal messages

<img width="718" alt="Screenshot 2021-04-16 at 10 54 16" src="https://user-images.githubusercontent.com/1794099/114999381-18a09600-9ea2-11eb-8db2-6d4a3cff8db1.png">

```ts


console.log('LOADED foo.renderer!')

const vscode = acquireVsCodeApi();
window.addEventListener('message', event => {
    console.log('received message in RENDERER', event.data)
})
vscode.postMessage('Did render!')

const api = acquireNotebookRendererApi('foo.renderer');
api.onDidCreateOutput(event => {
    event.element.innerHTML = `<i>Foo-Foo-Foo</i><pre>${JSON.stringify(event.value)}</pre><i>Foo-Foo-Foo</i>`;
    vscode.postMessage('Did render!')
});

```

**Comment by rebornix** [comment]
@mjbvz what's the best way to handle this? Any way to sanitize `window.addEventListener('message')`?

**Comment by mjbvz** [comment]
We could delete `window.addEventListener`. I don't think being able to listen to these message is a real concern though

**Comment by mjbvz** [comment]
I'm going to close this since I'm not sure it is an issue

If we can come up with a good fix,  we should be able to patch this after shipping  since we have an official api for receiving messages
