### ISSUE TITLE
Git SCM not detecting git repo in subfolders

### ISSUE THREAD

**Issue by jajcayn** [microsoft/vscode#121426]
- VS Code Version: 
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:39:47.234Z (2 days ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

Steps to Reproduce:

1. open a folder (not a workspace) with 4 subfolders
2. 2 of those subfolders are git repo, i.e.

main folder (not a git repo)
--- subfolder 1 (<-- **git repo**)
--- subfolder 2 (<-- **git repo**)
--- subfolder 3 (not a git repo)
...

3.  open file from any of the two repos (subfolder 1 or 2)
4. git tab should show something? but for me is just giving: "The folder currently open doesn't have a git repository..."

I searched for this issue and got the feeling from responses, this should work. VS Code should be able to recognise git repo from the open file and open the appropriate repo in the SCM tab.

Note, that it is working as it should when I open a workspace. It does not, however, in my situation when I simply open a folder and git repos are inside the subfolders.

Thanks for looking into it! 

Does this issue occur when all extensions are disabled?: Yes

**Comment by lszomoru** [comment]
@jajcayn, sorry for not getting back to you on this until now. Have you made any changes to your `git.autoRepositoryDetection` setting. By default we should be able to detect that git repositories in subfolder 1 and subfolder 2 using the default setting of this setting.

**Comment by jajcayn** [comment]
Hey @lszomoru 
So a weird thing: I didn't make any changes (at least not that I recall), but the setting was set to false for some reason... Anyway, when I put them to true, nothing happened, but after restarting VSCode, the source control panel appears to work as expected.

Thanks for pointing me in the right direction:)
