### ISSUE TITLE
Add WYSIWYG HTML Editing similar to MS Expresison Web/FrontPage

### ISSUE THREAD

**Issue by bobcozzi** [Microsoft/vscode#12148]
- VSCode Version: any
- OS Version: mac os x

Steps to Reproduce:
1. The need for WYSIWYG editing in addition to preview is badly needed.
2.

**Comment by mjbvz** [comment]
Thank you for the suggestion, but this is beyond VSCode's scope as a code editor focused on the edit-build-debug cycle. I recommend checking out other tools that are focused on WYSIWYG type experiences.

Thanks.
