### ISSUE TITLE
No hover background change for show search details

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121499]
Issue Type: <b>Bug</b>

![Screenshot (465)](https://user-images.githubusercontent.com/9638156/115075514-db6cf000-9f03-11eb-9ffd-d31d3c068e63.png)

![Screenshot (468)](https://user-images.githubusercontent.com/9638156/115079924-94cec400-9f0a-11eb-803a-0815716943a6.png)

![Screenshot (466)](https://user-images.githubusercontent.com/9638156/115077353-94ccc500-9f06-11eb-95af-646881456f63.png)

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.18363

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. PRs are welcome so you can create a PR that fixes this if you are passionate about getting this feature across the finish line. Thanks!
