### ISSUE TITLE
Show a bigger commit message text input

### ISSUE THREAD

**Issue by ffissore** [microsoft/vscode#121452]
In our company, the team is split pretty much in two: those using pycharm and those using vscode. The commits pushed by those using vscode are 1-word commits like "fix", "logging", while those using pycharm put more effort in describing what their commits are about.

I personally believe this problem is due to vscode showing users a tiny input text field for their message, but I'm no UX expert. Still, this difference is a problem, it creates friction.

Please consider showing users a bigger text area, which will implicitly invite them to be more descriptive.

**Comment by eamodio** [comment]
When you say bigger text area -- do you just mean show multiple empty lines by default?

**Comment by ffissore** [comment]
In essence, yes. FYI this is what it looks like on pycharm
![image](https://user-images.githubusercontent.com/510465/115074288-cbe8a980-9ef9-11eb-80cc-6f28a7a64602.png)

**Comment by lszomoru** [comment]
Starting with VS Code 1.86 this can be done using the `scm.inputMinLineCount` setting.
