### ISSUE TITLE
Notify fail when release insiders is build and posted.

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#121486]
- VS Code Version: code-insiders_1.56.0-1618572971_amd64.deb
- OS Version: Debian Buster 10

Steps to Reproduce:

0. use very small computer performance
1. install
2. observer for 14 days
3. note than is show less notify than builds posted.

Does this issue occur when all extensions are disabled?: Yes/No -> To do Steps to Reproduce with disable extensions if func return true

TODO
By default, a notification will show in VS Code insiders to let you know there's a new build to install.

_Originally posted by @alexr00 in https://github.com/microsoft/vscode/issues/121468#issuecomment-821260407_

But to have more than 7 days than i have insiders but i receive only one notifications.

**Comment by AlexandroGonSan** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [TO Microsoft: Notify when release insiders is posted. (#121468)](https://www.github.com/microsoft/vscode/issues/121468)

You should post two messages, one with search in issues without me and other in my issues.

**Comment by joaomoreno** [comment]
Olá Alexandro. Não consigo perceber qual é o problema, consegues explicar-me em Português?

**Comment by AlexandroGonSan** [comment]
Olá Joao. Eu não estou recebendo as notificações de novas versões insider quando abro ou quando estou com o mscode aberto.

**Comment by joaomoreno** [comment]
Alexandro, não há notificações dentro do product na distribuição .deb. Quando se instala o .deb, os updates são feitos pelo APT.

**Comment by AlexandroGonSan** [comment]
Yes, there is notification.
