### ISSUE TITLE
replaceEditors does not properly await open editors

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#121410]
A bug @rebornix discovered while fixing the integration tests for notebooks. When something calls `await group.replaceEditors` there is no guarantee that the active editor will be the one which you are replacing with. To test this you can add a return after replaceEditors in `extensionContributedEditorService` and see that the notebook integration test fails once again. To get around this, I'm explicitly calling open after a replace.

**Comment by bpasero** [comment]
All integration tests run fine for me when I add a `return` before the editor override service calls `openEditor`.

In addition, the `replaceEditors` method does await the opening:

https://github.com/microsoft/vscode/blob/b5dfdbe00f1bf40d079555f5848a51dbcbbe6a6e/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1692-L1692

**Comment by lramos15** [comment]
I was placing the return in the wrong place changing the behavior of the code. `replaceEditors` does in fact await.
