### ISSUE TITLE
Automatic click on right click button in Explorer menu

### ISSUE THREAD

**Issue by fakhamatia** [microsoft/vscode#121424]
- VS Code Version: 1.55.2
- OS Version: Ubuntu 20.04

I had [this](73474) problem before, but I think there is only in Explorer now

Steps to Reproduce:

1. Open Explorer menu
2. Click on file/folder 
3. If the menu doesn't fit in windows and the menu placed under mouse and click automatic

![Peek 2021-04-16 02-20](https://user-images.githubusercontent.com/20030910/114943622-82498180-9e5b-11eb-9886-4c400fcd112b.gif)

**Comment by isidorn** [comment]
Dup of some issue assigned to @sbatten
