### ISSUE TITLE
Terminal Tabs: Resizing window changes layout but does not cause titles to appear

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121405]
Enable terminal tabs, get in state like this:
![image](https://user-images.githubusercontent.com/8586769/114918298-c6953d00-9ddb-11eb-9c6f-dbc027fac1c0.png)

Resize the entire vscode window:
![image](https://user-images.githubusercontent.com/8586769/114918338-d44ac280-9ddb-11eb-81c0-d63ed8dc2df6.png)
See that the tabs section has left-justified, but the titles are still missing

bonus bug: the tabs section doesn't forfeit any space when the window is resized, causing the terminal itself to become too small. 

Then go and resize the tabs by moving the divider between tabs and terminal:
![image](https://user-images.githubusercontent.com/8586769/114918610-1c69e500-9ddc-11eb-9a4f-e0a63708a560.png)
title now appears

**Comment by Tyriar** [comment]
Did you have any errors in the console? The centering thing and this might be related to an uncaught exception?

**Comment by JacksonKearl** [comment]
Nothing in the console

**Comment by Tyriar** [comment]
I set a max size of 500, the tabs not giving width to terminals on window resize is by design. Also I think the other issues captured here are fixed.
