### ISSUE TITLE
Tooltips completely cover code I'm trying to write

### ISSUE THREAD

**Issue by distinctdan** [microsoft/vscode#121422]
Issue Type: <b>Bug</b>

I'm trying to write code, but the tooltips are completely covering the code I'm trying to write. This is obnoxious and dumb. Please see screenshots.

Obnoxious tooltips:
![Screen Shot 2021-04-15 at 5 35 27 PM](https://user-images.githubusercontent.com/10030156/114941588-5acdc700-9e11-11eb-9ab6-326f628cb31c.png)

After pressing escape several times:
![Screen Shot 2021-04-15 at 5 36 07 PM](https://user-images.githubusercontent.com/10030156/114941610-615c3e80-9e11-11eb-8c84-1b2565028470.png)

I'm writing a react typescript file, and the specific function `produce` is from the library Immer.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (2.09GB free)|
|Process Argv|--crash-reporter-id 656c6348-b102-4b6b-8ade-e7f56a3faa5f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.1.20
go|gol|0.24.1
vscode-scss|mrm|0.9.0
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.0
remote-containers|ms-|0.166.1
cpptools|ms-|1.3.0
vscode-yaml|red|0.18.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by jrieken** [comment]
You toggle the suggest details window by pressing `Ctrl+Space` and/or turn this setting to "on" `editor.suggest.showStatusBar` and show/hide details form the suggest status line

**Comment by distinctdan** [comment]
I'm not asking about toggling the window, the issue is that the tooltip is positioned incorrectly. It's completely covering the code I'm typing in this case, which is not the desired behavior. It's supposed to be off to the side.
