### ISSUE TITLE
Terminal tabs rendered centered not left alligned

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#121443]
<img width="462" alt="capture" src="https://user-images.githubusercontent.com/1931590/115001165-bd6fa300-9ea3-11eb-860b-bf5b34fcaced.png">

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? 

Please reopen this if that's not the case
