### ISSUE TITLE
Workbench reloading intermittently fails on Windows with process reuse enabled

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#121491]
Testing #120431

**Repro steps**

On Windows:

1. Enable process reuse
2. Open Devtools in OSS
3. Start reloading the workbench multiple times
4. 🐛 Sometimes, only the script files seem to load

**Example**

![recording](https://user-images.githubusercontent.com/7199958/115067783-3d970800-9ea6-11eb-98b1-e7206001bbbc.gif)

To figure out:

- Does this issue still occur when process reuse is disabled? 

**Edit**: It seems this issue goes away when process reuse is disabled.

**Comment by rzhao271** [comment]
Even weirder: sometimes the css files load, but not the js ones.
This still results in a blank workbench.

@alexdima I tried looking through some code in https://github.com/microsoft/vscode-loader. I'm wondering whether you have any idea what could be happening here? Is there some callback that's not being called?

![nojs](https://user-images.githubusercontent.com/7199958/116145982-d1c95200-a692-11eb-862b-e21bc2f5221d.PNG)

**Comment by alexdima** [comment]
I'm sorry, I have no idea what could be wrong. 🤷

**Comment by rzhao271** [comment]
@deepak1556 the part where the file is read still ends up hitting this line, which changes the format of the path URL: https://github.com/nodejs/node/blob/09c97b813890f6f1465ebd149831bed07682d496/lib/path.js#L647

**Context**
I noticed that on Windows, with process reuse enabled and while debugging, that the following callback body is sometimes not being run during a reload:
https://github.com/microsoft/vscode-loader/blob/main/src/loader.js#L832

However, the line before that _is_ run, and that line calls into https://github.com/microsoft/vscode-loader/blob/cbe8f639e7e2ae8a0ede5da411555815158bd13e/src/core/scriptLoader.ts#L538, which reads the file.

In more detail:

1. The `NodeScriptLoader` calls `_readSourceAndCachedData`
2. `_readSourceAndCachedData` calls into `fs-wrapper` https://github.com/electron/electron/blob/master/lib/asar/fs-wrapper.ts#L496
3. That line calls https://github.com/nodejs/node/blob/master/lib/fs.js#L329, passing the arguments, including the callback, into the `fs` call
4. The callback isn't run

**Comment by alexdima** [comment]
CC @jrieken who wrote `_readSourceAndCachedData`. I've also looked at `_readSourceAndCachedData` and the function appears to me to be fine.

**Comment by jrieken** [comment]
Given its age and importance I'd be surprised to find major issues with `_readSourceAndCachedData`. Tho, never say never. It this happen with rapid reloading only? Is the callback function still from a previous (before reload) state?

Also, one thing to consider is that all of it will be away when switching to node-free renderers. Tho, also the performance it guarantess 😢

**Comment by deepak1556** [comment]
I haven't tried to repro this yet, additional to above when this issue happens can you run some generic `fs.readFile` calls and see if they succeed. If they don't, then the problem is deep in the event loop layer and not related to the `vscode-loader`

**Comment by bpasero** [comment]
At least from devtools I seem to be able to use node.js just fine when the workbench hangs:

![image](https://user-images.githubusercontent.com/900690/116717250-fa29b700-a9d8-11eb-9617-4ee8504436c5.png)

Also, the fact that we show a bit of the workbench UI ("rapid rendering") means the window is not entirely dead.

**Comment by deepak1556** [comment]
@bpasero can you try the async version of fs apis.

**Comment by bpasero** [comment]
@deepak1556 oh yeah, the `async` variant never returns!

**Comment by deepak1556** [comment]
Thanks Ben, that indicates a problem in the event loop after reload. Will look into it.

**Comment by bpasero** [comment]
Need to verify whether this still applies now that ext host etc. moved to shared process.

**Comment by rzhao271** [comment]
> Need to verify whether this still applies now that ext host etc. moved to shared process.

It does not apply!
