### ISSUE TITLE
In the Explorer filetree, near the top, please include a filename filter box

### ISSUE THREAD

**Issue by NickVH-MS** [microsoft/vscode#121432]
In the Explorer UI, when looking at a filetree, near the top, please include a filename filter box. In a way, it'd be sort of a search box but limited in scope only to filenames (which are likely cached in memory anyway), so it should be ultra-snappy.

**Comment by gjsjohnmurray** [comment]
Are you aware that you can already search / filter the Explorer tree by typing characters when focused on it?

**Comment by IllusionMH** [comment]
I think it's duplicate of #70646

**Comment by NickVH-MS** [comment]
I see, I wasn't aware. I agree this is more or less a duplicate of #70646.
