### ISSUE TITLE
Allow to Shift+scroll to change tabs

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#121484]
- VS Code Version: code-insiders_1.56.0-1618572971_amd64.deb
- OS Version: Debian Buster 10 with XFCE
- Machine: STi IS1412 with 2GB and SSD 120GB with more 50% used and processor running in 1.20 Ghz

Does this issue occur when all extensions are disabled?: Yes/No -> To do Steps to Reproduce with disable extensions if func return true then if return No to do auto/bot to report.

**Comment by AlexandroGonSan** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Tabbing into terminal needs 2 tabs (#117353)](https://www.github.com/microsoft/vscode/issues/117353)
> * [Dragging tabs should show an insertion target, not a replacement target (#118419)](https://www.github.com/microsoft/vscode/issues/118419)
> * [Allow to close multiple tabs without moving the mouse after closing one (#40290)](https://www.github.com/microsoft/vscode/issues/40290)
> * [wrap tabs to multi-line: don't expand single tab to whole width (#119760)](https://www.github.com/microsoft/vscode/issues/119760)
> * [Theme is not updated in web when opened  in two tabs on same browser (#107854)](https://www.github.com/microsoft/vscode/issues/107854)

This not is duplicated!

**Comment by bpasero** [comment]
Try `Shift-Scroll`.

**Comment by AlexandroGonSan** [comment]
> Try `Shift-Scroll`.

Sorry, ALT+SCROLL in xfce debian buster 10 change zoom of all screen.

**Comment by AlexandroGonSan** [comment]
I need than Microsoft implements!
