### ISSUE TITLE
Smoke tests are failing

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#121446]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=113839&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=2912d057-d0f3-5270-1d09-777eeaba2eea

**Comment by lszomoru** [comment]
Pushed a temporary fix. Will discuss with @sbatten what the right fix should be.

**Comment by sbatten** [comment]
Sorry the dialog was showing even if trust wasn't enabled. Is there a testing environment variable I can use to disable this?

**Comment by sandy081** [comment]
Not sure if we have such variable for test (or smoke test). @joaomoreno might know.

**Comment by lszomoru** [comment]
Could we just set the setting never to show the introduction dialog in the `setup` method before running the tests?

**Comment by sbatten** [comment]
@lszomoru is there a single setup function for all tests to do that? sounds like a good idea, happy to add it

**Comment by lszomoru** [comment]
@sbatten, maybe here - https://github.com/microsoft/vscode/blob/main/test/smoke/src/main.ts

**Comment by lszomoru** [comment]
This issue has been resolved.
