### ISSUE TITLE
Any way to store extension configuration in vscode configuration

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#12142]
Is there any way that i can store my extension settings that are in the JSon format and store in vscode own configuration rather then own file ?
and retrieve from there instead of my own JSON extension setting file ?

**Comment by bpasero** [comment]
@shanalikhan you are asking for API from an extension to write to the settings.json file?

**Comment by shanalikhan** [comment]
Actually my extension code setting sync uses simple extension own json file and write in that file and get all the information syncsettings.json 

I just to know is there a possible way that i remove my own json file and instead write in vscode settings json file or any other code local storage and retrive that information to manage my extension rather then using my own json file

**Comment by bpasero** [comment]
If you are providing configuration settings, you would benefit from https://github.com/Microsoft/vscode/issues/1396

If your JSON file is agnostic to the VS Code configuration story, then you can only use node.js APIs.
