### ISSUE TITLE
Identifier Expected Problem (False Positive)

### ISSUE THREAD

**Issue by dnairns-arch** [microsoft/vscode#121418]
- VS Code Version: 1.52.1
- OS Version: Darwin x64 20.3.0 (MacOS BigSur 11.2.3)

Steps to Reproduce:

1. Code builds and tests fine. Just a syntax/error chcking issue. 
2. Paste code into your version and watch the error....

``const values = array.map(a => a.[`VAR${numArr[j]}`]).filter(Boolean);``

The editor doesn't like that I am "injecting" in the identifier name in the above manner. It thinks there is no identifier, but the code compiles and runs perfectly without warnings or any other messages. (Javascript/React/Node)

If other details are needed let me know, Im happy to assist. (Seems pretty straightforward...)

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
You have `.` between `a` and `[` which is invalid JS syntax so error is correct - as you can see for non "compiled" code
![image](https://user-images.githubusercontent.com/1312662/114993304-5a324080-9ea4-11eb-9afa-299751629b41.png)

Removing `.` should fix problem if by "injecting" you mean using regular element access expression where expression is template literal.

**Comment by dnairns-arch** [comment]
Thats super interesting. Thank you.  I didn't know it would still work without the dot to access the VAR0 or VARn property. My apologies to have "Bugged" you about it, but thanks for the tip. I'll fix my code.
