### ISSUE TITLE
ALT selct multiple lines

### ISSUE THREAD

**Issue by finBitorg** [microsoft/vscode#121415]
Issue Type: <b>Feature Request</b>

Unable to select multiple lines like in most other editors by using "alt+hold left mouse" for easy multiple line spacing. 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64

**Comment by alexdima** [comment]
This has to do with a VS Code feature called multicursor which uses by default the <kbd>Alt</kbd> modifier. You can configure `"editor.multiCursorModifier": "ctrlCmd"` and then use <kbd>Alt</kbd> and left mouse to do column selection, like in other editors.
