### ISSUE TITLE
Restore functionality: auto-select the next search result after dismissing one

### ISSUE THREAD

**Issue by aramando** [microsoft/vscode#121453]
Until very recently, dismissing a result in the sidebar search that had been clicked on to select it and bring the result up in the relevant file in the editor would auto-select the next result below it in the list; in this way you could very efficiently work through a list of results, and by simply dismissing them bring up the next result in the editor to view it in context. This is no longer working for me; dismissing a result will outline the next result, but not fully highlight/select it, nor bring that line up in the editor, whether or not the dismissed result or any other had previously been clicked. This means that working through a list of results involves twice as many clicks and feels very laborious. It would be great to reinstate the previous auto-selection behaviour.

Tested in current latest version, v1.55.2 for Linux (on Ubuntu 20.04.2), with all extensions disabled

**Comment by aramando** [comment]
^^^ Confirmed this is not a duplicate

**Comment by JacksonKearl** [comment]
Unable to reproduce, checked back to vscode 1.40 and the behavior seems to not have changed. This is what I'm seeing:
![recording (9)](https://user-images.githubusercontent.com/8586769/115051925-2fd78780-9e92-11eb-9b96-c2c589739ea8.gif)

Can you include a gif of what you see? 

/gifPlease

**Comment by JacksonKearl** [comment]
cc @roblourens if you know of any changes

**Comment by aramando** [comment]
![vscode_search](https://user-images.githubusercontent.com/414215/115054691-6f28c700-9ed8-11eb-9b51-8a7bcf5612be.gif)

**Comment by roblourens** [comment]
I think this was https://github.com/microsoft/vscode/issues/120637, should be fixed in Insiders

**Comment by aramando** [comment]
Just installed Insiders and can confirm it is working again. Thanks both.
