### ISSUE TITLE
Terminal closes as soon as it is opened.

### ISSUE THREAD

**Issue by prateeshreddy** [microsoft/vscode#121414]
Issue Type: <b>Bug</b>

Terminal colapses when opened tried reinstalling reboot. I'm using M1 Macbook although I have VS Code Universal on my system.

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin arm64 20.3.0

https://user-images.githubusercontent.com/60734422/114928485-a5931300-9e00-11eb-8fb5-fdcf5c167335.mp4

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
