### ISSUE TITLE
Highlighting breaks on Handlebars language when you put a Handlebars comment inside a <script> tag

### ISSUE THREAD

**Issue by jp06** [microsoft/vscode#121478]
- VS Code Version: 1.55.2
- OS Version: Windows 10 Version 2004

Steps to Reproduce:

1. Put a Handlebars comment inside a <script> tag. 
![handlebars-bug](https://user-images.githubusercontent.com/30029476/115042938-854d7c00-9f06-11eb-8900-f9502f4d8842.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Can you please share a full copy/pastable example that I can test with?

**Comment by jp06** [comment]
Hi @alexr00, sorry I haven't been able to get back much earlier to you. Like I said it happens when you put a Handlebars comment inside a `<script>` tag. 

To reproduce, I think you can just clone the [BigCommerce Cornerstone repo](https://github.com/bigcommerce/cornerstone) and then look into the HTML templates inside the `template` folder. The GIF above is this file in the repo:

https://github.com/bigcommerce/cornerstone/blob/31ac15abe093c8f0c3712157a9e83128f0601b68/templates/layout/base.html#L14

**Comment by jp06** [comment]
And also set the language to Handlebars when opening the template .html files.
