### ISSUE TITLE
Enabling terminal tabs for the first time has strange layout

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121403]
This seems to be laid out for the narrow case, but it also takes 50% of my terminal. I think it should both be laid out for the expanded case and be much narrower

![image](https://user-images.githubusercontent.com/8586769/114918021-74ecb280-9ddb-11eb-9eb5-a857e00e88f6.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
