### ISSUE TITLE
no device

### ISSUE THREAD

**Issue by FJ58000** [microsoft/vscode#121404]
Issue Type: <b>Bug</b>

j'ai la dernière version de Flutter et de VS Code, je n'ai pas de device, "no device" en bas dans la barre, et pas moyen d'en sélectionnner un… Y a-t-il un moyen d'ajouter un device ? 

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3235 CPU @ 3.30GHz (24 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|48.00GB (1.96GB free)|
|Process Argv|--crash-reporter-id 905a153a-ff1c-412d-8858-4771481c6056|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-internationalize|api|0.2.0
ccs-flutter-color|cir|1.0.1
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
flutter-intl|loc|1.14.0
flutter-tree|mar|1.0.0
vscode-language-pack-fr|MS-|1.55.2
dart-syntax-highlighting-only|osc|1.0.1
vscode-versionlens|pfl|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30288035
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

**Comment by Manoj-Paramsetti** [comment]
Can I know in which way you're trying to connect, and can you please share your output for `flutter doctor`?
