### ISSUE TITLE
[scss] timing functions in variables break syntax highlighting

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#12143]
- VSCode Version: 1.5.2

![image](https://cloud.githubusercontent.com/assets/2827047/18583972/3489ce06-7c0e-11e6-8a04-8b4e8c3b9883.png)

The snippet:

``` scss
// OTHER

$ease: cubic-bezier(0.4, 0, 0.2, 1);
$ease-out: cubic-bezier(0, 0, 0.2, 1);
$ease-in: cubic-bezier(0.4, 0, 1, 1);
```

**Comment by mrmlnc** [comment]
IMO, also related to:

![2016-10-27_00-43-21](https://cloud.githubusercontent.com/assets/7034281/19746286/64532fde-9bde-11e6-9356-9c2975181f9c.gif)

**Comment by aeschli** [comment]
Most of the issues reported got fixed in the meantime. I created https://github.com/atom/language-sass/issues/196 for the remaining issue with fractional numbers.
