### ISSUE TITLE
Source control detect active repository after clicking commit button 

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vscode#121459]
- VS Code Version: 1.55.2
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Multiple git repository in the current folder
2. Enable Source Control Repositories list view
3. Select only one repository
4. Write commit message
5. Click on Commit (tick mark) icon on Source Control group

![Screenshot from 2021-04-16 14-07-45_crop](https://user-images.githubusercontent.com/2698569/115022915-59a6a380-9ebe-11eb-93c0-eb75022fb3b2.png)

If you have multiple repositories, then you have to select, on which repo you want to commit. But in the Source Control Repositories group only one is selected. If multiple repositories are selected, than each one has it's own commit button. Which is fine, but I have multiple and it's easier to select only one. If I press Ctrl+Enter, then the correct one is committed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by AlexandroGonSan** [comment]
WARNING: Keep performance for all users.
Should be create configuration with current default for enable users personalize.

**Comment by csorvagep** [comment]
Sorry for the late response, I thought it is obvious. None of the mentioned other issues seems to be related to this.
@AlexandroGonSan I don't think there is any performance issue here. Other buttons and action similar to this works, like the commit message textbox or the Git Graph extension button. If I press Ctrl+Enter inside the commit message box, the correct repository is chosen, but if I click on the commit button, a "Choose repository" dialog opens.

Here's what I see if there is multiple repositories are selected:
![image](https://user-images.githubusercontent.com/2698569/119042649-6a17d580-b9b8-11eb-9076-9c00e3a14495.png)

And if only one is selected:
![image](https://user-images.githubusercontent.com/2698569/119042699-7dc33c00-b9b8-11eb-8279-df0763b8e14b.png)

The old and expected behavior is that the commit and refresh buttons work as if they were related to the only selected repo, and no "Choose repository" dialog opens.

**Comment by csorvagep** [comment]
@eamodio Should I add more information? This issue is still annoying with multiple repositories.
