### ISSUE TITLE
Hide dropdown when showing terminal tabs 

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121449]
I am surprised how much I like the terminal tabs UI 🙊 For more tidiness I would suggest to hide the dropdown and `+` button from the title

<img width="829" alt="Screenshot 2021-04-16 at 12 13 36" src="https://user-images.githubusercontent.com/1794099/115010226-725a8d80-9ead-11eb-93a5-571a4b29dbf3.png">

**Comment by Tyriar** [comment]
This is fixed in today's build
