### ISSUE TITLE
Add existing file to solution folder.

### ISSUE THREAD

**Issue by rodeo22** [microsoft/vscode#121435]
Issue Type: <b>Feature Request</b>

I am not getting any option to add existing file to my .NET solution in explorer. One way is to copy the file in folder from file explorer but is there any way to do so from VS code explorer itself. Am I missing something very easy?

VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:35:47.374Z)
OS version: Windows_NT ia32 10.0.19042

**Comment by isidorn** [comment]
This is not possible in vscode core. I suggest that you try to find an extension that does it.
I know there is one "Solution Explorer"

**Comment by rodeo22** [comment]
Thanks @isidorn for your response. I found one such extension,
![image](https://user-images.githubusercontent.com/56561647/115012139-143da280-9ecd-11eb-8d4a-f2b862ae29d5.png)

Although, so far I could find this suitable for new solution and adding existing project for solution, could not open my exiting repo folder not having any vs project. May be I am missing something, will dig more. 
Let me know if you already know the solution. :)

**Comment by isidorn** [comment]
I do not know the solution, I think ti would be best if you open an issue in the repository of that extension. Thank you
