### ISSUE TITLE
ResourceNotFound Error: Microsoft Edge Tools for VSCode extension fails on latest insiders

### ISSUE THREAD

**Issue by bgoddar** [microsoft/vscode#121479]
Issue Type: <b>Bug</b>

The Microsoft Edge Tools for VS Code extension fails to load resources into webviews on the latest version of insiders.

Repro Steps:
1. Install Microsoft Edge Tools for VS Code on insiders
2. Select the extension
3. Launch an instance of edge by hitting the '+' above the list of targets

Expected: Tools are able to load resource containing the devtools code
Actual: Fails with message: ResourceNotFoundThe specified resource does not exist. RequestId:ae0e3a57-901e-0027-70d8-329043000000 Time:2021-04-16T15:50:20.3285496Z

VS Code version: Code - Insiders 1.56.0-insider (25785b97e533b15ae3b12e48aaf4187416437e62, 2021-04-15T05:14:21.699Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (18.64GB free)|
|Process Argv|--crash-reporter-id 739e6bbd-3941-443e-9e6b-c06f1ebf9837|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-edge-devtools|ms-|1.1.7
debugger-for-edge|msj|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30278404
vspre833:30267464
vscnewfiletext:30288477
vshan820:30276952
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by bgoddar** [comment]
This looks related to the these recent changes:
https://github.com/microsoft/vscode/commit/de9887d9e0eaf402250d2735b3db5dc340184b74
https://github.com/microsoft/vscode/pull/120654
(the github mentioning isn't autopopulating for me for some reason)
@mjbvz FYI

Dug into the failing request. The url that works on stable VSCode: vscode-webview-resource://6c97c27e-d935-47e2-83a9-8c5580b69436/file///c%3A/Users/milia/vscode-edge-devtools/out/tools/front_end/inspector.html?ws=trueD&experiments=true&edgeThemes=true

same request failing on insiders: https://021f42a4-cec4-468d-ad69-06a54760f951.vscode-webview-test.com/vscode-resource/file///c%3A/Users/milia/vscode-edge-devtools/out/tools/front_end/inspector.html?ws=trueD&experiments=true&edgeThemes=true


For reference, our code that creates these Uri's to load can be seen here: https://github.com/microsoft/vscode-edge-devtools/blob/master/src/devtoolsPanel.ts#L301

**Comment by bgoddar** [comment]
``` 
private getHtmlForWebview() {
        const htmlPath = vscode.Uri.file(path.join(this.extensionPath, 'out/tools/front_end', 'inspector.html'));
        const htmlUri = this.panel.webview.asWebviewUri(htmlPath);

        const scriptPath = vscode.Uri.file(path.join(this.extensionPath, 'out', 'host', 'messaging.bundle.js'));
        const scriptUri = this.panel.webview.asWebviewUri(scriptPath);

        const stylesPath = vscode.Uri.file(path.join(this.extensionPath, 'out', 'common', 'styles.css'));
        const stylesUri = this.panel.webview.asWebviewUri(stylesPath);

        return `
            <!doctype html>
            <html>
            <head>
                <meta http-equiv="content-type" content="text/html; charset=utf-8">
                <meta http-equiv="Content-Security-Policy"
                    content="default-src 'none';
                    frame-src ${this.panel.webview.cspSource};
                    script-src ${this.panel.webview.cspSource};
                    style-src ${this.panel.webview.cspSource};
                    ">
                <link href="${stylesUri}" rel="stylesheet"/>
                <script src="${scriptUri}"></script>
            </head>
            <body>
                <iframe id="host" frameBorder="0" src="${htmlUri}?ws=trueD&experiments=true&edgeThemes=true"></iframe>
            </body>
            </html>
            `;
    }

**Comment by mjbvz** [comment]
Yes we have migrated to use service workers for loading all webview content. Service workers were already being used for this on web, so we are trying to make the two environments consistent

As far as I know, service worker do not see requests for top level iframe pages (`inspector.html` in your example). If you are loading local content into an iframe inside a webview, chances are that you should probably just load that content into the webview itself and skip the iframe (and all of the extra stumbling blocks it adds)

Please try updating your extension to use a different approach that does not rely on loading iframe content with as a webview resource (content inside iframes that are on the same origin as the host webview should still go through the service worker)

**Comment by pbaksa** [comment]
Is there a way to just show a pre-generated html with inner links between them without needing to modify the html?
