### ISSUE TITLE
Open with VS Code from right click in Windows Explorer

### ISSUE THREAD

**Issue by pumano** [Microsoft/vscode#12147]
Feature request

**Description:**

Add possibility to open folder/file/group of selected files from windows explorer using right click menu with "Open with VS Code".
It's perfectly works with Atom, and Notepad++

**Why this feature needed:**
- Very useful
- Speed of opening project is increased

**OS:**
- Windows
- Mac OS (If it can be added to mac version - it's will be good to)

**Comment by mrmlnc** [comment]
You talk about it? It's works fine in in a stable branch.

![image](https://cloud.githubusercontent.com/assets/7034281/18586589/081f335c-7c26-11e6-92d1-20daaeec40aa.png)

**Comment by bpasero** [comment]
Yes, make sure to install VS Code with the installer to get it 👍

**Comment by aasf86** [comment]
your answer is here [Right click on Windows folder and open with Visual Studio Code](http://thisdavej.com/right-click-on-windows-folder-and-open-with-visual-studio-code/)

**Comment by Noitidart** [comment]
If I forgot to check that during install, is there any way to get it now rather then reinstalling?

**Comment by Deilan** [comment]
@Noitidart yes, @aasf86 gived a link for that above.

**Comment by Noitidart** [comment]
Thanks @Deilan very much I was still struggling with this, I will check out his link.

**Comment by sir-Higgins** [comment]
When you install with an admin account that isn't your main account.
the "Open with code" action  are applied on the account which install vscode.

![image](https://cloud.githubusercontent.com/assets/24956907/25698735/5c140fce-30c0-11e7-95a7-45e9f4834fb5.png)

My main account is not the admin account that installed vscode

Can you add a menu entry in vscode for setting the following actions for the current user that is running vscode and is not the installer account.

- "Open with code" action to Windows Explorer file context menu
- "Open with code" action to Windows Explorer directory context menu
- Add code to PATH

**Comment by vmvmpvm** [comment]
Visual Studio Code portable (zip) should also provide this option in settings or somewhere, so user can do this post downloading.

**Comment by IRCraziestTaxi** [comment]
But no, really, is there a way to enable these options WITHOUT reinstalling?

**Comment by johnkors** [comment]
If I really need to re-install to get this feature : will uninstalling remove my user settings and all my installed extensions? Is there a way to keep these?

**Comment by Noitidart** [comment]
You can use the extension Settings Sync to restore htem.

**Comment by rianadon** [comment]
Yes there should be some way to enable this in the application. For example with Atom there is a checkbox in the settings page that toggles the right click menu option on and off. Maybe VS Code could do something similar.

**Comment by johnkors** [comment]
@Noitidart thanks!

**Comment by josevimlet** [comment]
VSCode installer fails to add context menu on standard user accounts

Add this to a text file and rename it to .reg, then double click on it and enjoy open with VSCode.
(Note: this will only work on default install location, you can convert the hex to string and edit paths if you wish to fix this)

`
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\*\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,69,00,74,00,68,00,20,00,43,00,26,\
  00,6f,00,64,00,65,00,00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,00,00

[HKEY_CURRENT_USER\Software\Classes\*\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,22,00,20,00,22,00,25,00,31,00,\
  22,00,00,00

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,69,00,74,00,68,00,20,00,43,00,26,\
  00,6f,00,64,00,65,00,00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,00,00

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,\
  22,00,00,00

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\VSCode]
@=hex(2):4f,00,70,00,65,00,6e,00,20,00,77,00,69,00,74,00,68,00,20,00,43,00,26,\
  00,6f,00,64,00,65,00,00,00
"Icon"=hex(2):43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,00,00

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\VSCode\command]
@=hex(2):22,00,43,00,3a,00,5c,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,\
  00,46,00,69,00,6c,00,65,00,73,00,5c,00,4d,00,69,00,63,00,72,00,6f,00,73,00,\
  6f,00,66,00,74,00,20,00,56,00,53,00,20,00,43,00,6f,00,64,00,65,00,5c,00,43,\
  00,6f,00,64,00,65,00,2e,00,65,00,78,00,65,00,22,00,20,00,22,00,25,00,56,00,\
  22,00,00,00
`
