### ISSUE TITLE
Choosing that you trust a workspace should automatically close the workspace trust view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121439]
1. Open a new workspace - you get a workspace trust editor
2. Click on YES

The workspace trust is still there.

I suggest to automatically close the workspace trust dialog if the user has chosen YES.
Reason for this is that we should require the minimal amount of user interaction to keep this flow smooth. And there is a big difference between one click, or one click + editor close.

If we decide to auto close the editor as I suggest we should have an easy way to bring it back. Due to that I suggest to think about always having a very small status bar entry, that a user can click on to open this editor.

**Comment by sbatten** [comment]
we are adding a keyboard model for trusting quickly which should make this smaller. for the mouse flow, I find it awkward that it closes upon trust
