### ISSUE TITLE
Review Ctrl+Enter gesture in Notebooks

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121444]
Another huge annoyance I have in our Notebooks is the fact that the core <kbd>Ctrl Enter</kbd> keybinding does two things, depending on the currently focused cell's state:

- It finishes editing an input cell, if you're currently editing.
- It creates a new cell, otherwise.

This is very annoying since the first op is a view operation, while the second one is a model change. And I often mishit and happen to do the wrong thing. I expect it to only be a view operation and never a model one. This is especially problematic if you double press it while you're editing a cell: it creates a new cell, which is never what I intend to do.

Should we have a different keybinding for creating a new cell? And should we just have <kbd>Ctrl Enter</kbd> go into input mode if the user isn't already, ie. it would simply toggle input mode.

**Comment by rebornix** [comment]
This looks like an oversight on Windows.

**Comment by rebornix** [comment]
We will visit this this month.

**Comment by rebornix** [comment]
On windows, ctrl+enter should always execute the cell.
