### ISSUE TITLE
Sometimes notification buttons are squished vertically

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121425]
I haven't figured out when this happens, but I've seen it quite a few times lately.

![image](https://user-images.githubusercontent.com/641685/114944301-51def480-9e15-11eb-8295-4b596daa93cf.png)

Update: It seems to happen anytime there is more than 3 lines of text.

**Comment by bpasero** [comment]
i cannot reproduce:

![image](https://user-images.githubusercontent.com/900690/115052023-be252b00-9edd-11eb-8d2c-51bf582cbf8d.png)

Code:

```ts
vscode.window.showInformationMessage('Hello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!\nHello World from test-ts!', 'Pull', 'Sync (Pull & Push)');
```

**Comment by bpasero** [comment]
Reproduces for me with this code:

```ts
this.notificationService.notify({
	message: 'Using npm as the preferred package manager. Found multiple lockfiles for /Users/bpasero/Development/Microsoft/vscode-extension-samples/fsprovider-sample.',
	source: 'Source: NPM support for VS Code (Extension)',
	severity: Severity.Info,
	actions: {
		primary: [
			toAction({ id: 'id', label: 'Learn more', run: () => { } }),
			toAction({ id: 'id', label: 'Do not show again', run: () => { } }),
		],
		secondary: [
			toAction({ id: 'id', label: 'Learn more', run: () => { } }),
			toAction({ id: 'id', label: 'Do not show again', run: () => { } }),
		]
	}
});
```

**Comment by bpasero** [comment]
A regression from the work we did to have hover feedback on toolbar actions I would say. I cannot reproduce in `1.54` and one difference I see is that the width of the toolbar has changed:

From
![image](https://user-images.githubusercontent.com/900690/116211607-48725800-a744-11eb-8e6b-0b2b805a5b60.png)

To
![image](https://user-images.githubusercontent.com/900690/116211673-57f1a100-a744-11eb-9123-082c60fb2477.png)

**Comment by eamodio** [comment]
I had this happen again and looked into it more myself -- it looks like the manual height we are setting on `monaco-list-rows` and `monaco-list-row` isn't enough.

In the case below they are both set to `106px`:

![image](https://user-images.githubusercontent.com/641685/116339277-24962d00-a7ab-11eb-85bd-aa5bbed3ade8.png)

And if I take `overflow: hidden` off of `notification-list-item-details-row`, then I see:

![image](https://user-images.githubusercontent.com/641685/116339396-59a27f80-a7ab-11eb-9098-f0dbc1b02dc5.png)

So it looks like it should be ~`118px` instead of `106px`

**Comment by bpasero** [comment]
Notifications are sensitive to how large the contents are because of wrapping I need to manually compute the height of the message and I think that is where the problem rises from:

https://github.com/microsoft/vscode/blob/731402dce225ce25d42a7b173361650a54bf52ad/src/vs/workbench/browser/parts/notifications/notificationsViewer.ts#L88-L88

I take 24px per action but I think now it is 30px. I leave it up to @joaomoreno to either fix that assumption or change the actions width back to how it was (which I think I would prefer).

**Comment by joaomoreno** [comment]
Real fix: https://github.com/microsoft/vscode/issues/122667
