### ISSUE TITLE
Don't use images in trusted workspace dialog

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121489]
It could look a bit nicer if we used real HTML elements with real styles/etc. As-is the colors are off, and the text is a but blurry.

![image](https://user-images.githubusercontent.com/8586769/115065403-efccd080-9ea2-11eb-8613-6b1896ebf408.png)

**Comment by sbatten** [comment]
Dialogs don't allow arbitrary HTML because of their layering. This is done via markdown and styling. We could inject arbitrary elements and use css to put in svgs though

**Comment by JacksonKearl** [comment]
Hmm. I just feel like if we're showing an annoying pop up to everyone, at least make it pretty 😉

Also bonus bug that the link doesn't meet contrast requirements in HC mode. (2.14)

**Comment by AlexandroGonSan** [comment]
1. Change default for request of the user and pull request.
2. Create configuration with default for request of the user and pull request.
3. Develop for enable users personalize for this and according with this request.

**Comment by sbatten** [comment]
@JacksonKearl yea I need to apply link styles properly

**Comment by sbatten** [comment]
outdated
