### ISSUE TITLE
Does not support vue.js code hints

### ISSUE THREAD

**Issue by ruyan2016** [Microsoft/vscode#12149]
- VSCode Version:1.5.2
- OS Version: windows 10
Visual Studio Code does not support vue.js code hints

**Comment by bpasero** [comment]
@ruyan2016 can you explain what you expect in more detail?

**Comment by bpasero** [comment]
Suspect this is an issue with intellisense in JS.

**Comment by waderyan** [comment]
@ruyan2016 thank you for opening this issue. Can you provide me with a code sample I can test on my own machine to see what you are seeing?

**Comment by waderyan** [comment]
Closing until more info is provided.

**Comment by gluons** [comment]
[Vue Single File Components](http://vue-loader.vuejs.org/en/start/spec.html) contains 3 parts.

- **Template** contains HTML and Vue Component tag.  
   (It can also contains other template engine, such as [Pug](https://github.com/pugjs/pug), etc. , by specifying the `lang` attribute.)
- **Script** contains JavaScript (ES2015 support by default).  
   (It can also use CoffeeScript by specifying the `lang` attribute.)
- **Style** contains stylesheet CSS.  
   (It can also contains other CSS Preprocessors, such as [SASS](http://sass-lang.com/), [LESS](http://lesscss.org/), etc. , by specifying the `lang` attribute)
