### ISSUE TITLE
Quick import statements

### ISSUE THREAD

**Issue by shammelburg** [Microsoft/vscode#12140]
- VSCode Version: 1.5.2
- OS Version: Win 10

I have watched an Angular 2 video where the instructor imports 'import statements' by typing "NgModule" for example and then it pastes in "import { NgModule } from '@angular/core'" at the top of the page.

Very similar VS (IDE) when pressing (CRTL + .) and selecting add 'using System.Web.Http' for example.

This would safe a lot of time when creating components in Angular 2.

**Comment by waderyan** [comment]
@shammelburg thanks for opening this up. This seems like a valid feature request. However is it different than snippets? 

https://code.visualstudio.com/docs/customization/userdefinedsnippets

**Comment by waderyan** [comment]
Closing until more context can be given.
