### ISSUE TITLE
Submitting issue from vscode once but it sends 4 issues to the GitHub

### ISSUE THREAD

**Issue by kimlimjustin** [microsoft/vscode#121476]
Issue Type: <b>Bug</b>

I opened an issue from vscode, but since it's my first time opening issue, I clicked the button more than one (since I think it doesn't work xd). Here's all the issues I opened: #121472, #121473, #121474, #121475

To avoid this, I think it's better to give an animation or just disable the button after clicked once. 

Hope being fixed soon :)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.8.0-48-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx (4 x 1581)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|14.67GB (10.23GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id faba7d7b-2fa9-4f50-9547-77949d63445b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.4.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.0
es6-css-minify|olb|3.3.2
LiveServer|rit|5.6.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by AlexandroGonSan** [comment]
Where do I click to send feedback to github directly through vscode insider?

**Comment by kimlimjustin** [comment]
> Where do I click to send feedback to github directly through vscode insider?

Help > Report Issue

**Comment by gjsjohnmurray** [comment]
Similar to #115857

**Comment by RMacfarlane** [comment]
Thanks @gjsjohnmurray! Closing this as a duplicate
