### ISSUE TITLE
ts/js feature loading never completes

### ISSUE THREAD

**Issue by adjenks** [microsoft/vscode#121430]
- VS Code Version: 1.54.3
- OS Version: Windows 10

Steps to Reproduce:

1. Open tsx or ts file.
2. Done.

Does this issue occur when all extensions are disabled?: Yes

This issue was previously reported here: https://github.com/microsoft/vscode/issues/68896
but it was closed for some reason.

A log was requested in the previous ticket. Here is my log:

> Info 0    [16:53:39.872] Starting TS Server
> Info 1    [16:53:39.874] Version: 4.2.3
> Info 2    [16:53:39.874] Arguments: C:\Program Files\Microsoft VS Code\Code.exe c:\Program Files\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\[[[REDACTED]]]\AppData\Local\Temp\vscode-typescript\5a5cde3911a20d31c8d3\tscancellation-8b10ba0ed8708001e957.tmp* --logVerbosity verbose --logFile c:\Users\[[[REDACTED]]]\AppData\Roaming\Code\logs\20210415T164710\exthost3\vscode.typescript-language-features\tsserver-log-84BFeT\tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
> Info 3    [16:53:39.874] Platform: win32 NodeVersion: 12 CaseSensitive: false
> Info 4    [16:53:39.874] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
> Info 5    [16:53:39.879] Binding...
> Info 6    [16:53:42.406] event:
>     {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":19404}}
> Info 7    [16:53:42.408] request:
>     {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
> Info 8    [16:53:42.409] Host information vscode
> Info 9    [16:53:42.409] Host watch options changed to undefined, it will be take effect for next watches.
> Info 10   [16:53:42.409] response:
>     {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
> Perf 11   [16:53:42.409] 0::configure: async elapsed time (in milliseconds) 0.9560
> Info 12   [16:53:42.410] request:
>     {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2016","jsx":"preserve","strictFunctionTypes":true,"sourceMap":true,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"resolveJsonModule":true}}}
> Perf 13   [16:53:42.410] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.3705
> Info 14   [16:53:42.410] response:
>     {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
> Info 15   [16:53:42.410] request:
>     {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"[[[REDACTED]]]/example/example-app.tsx","fileContent":"import * as React from 'react';\r\nimport ReactDOM from \"react-dom\";\r\nimport ClickCounter from '../components/ClickCounter.jsx';\r\n\r\nvar mountNode = document.getElementById(\"root\");\r\nReactDOM.render(<ClickCounter/>, mountNode);\r\n","projectRootPath":"\\\\[[[REDACTED]]]\\[[[REDACTED]]]","scriptKindName":"TSX"}]}}
> Info 16   [16:53:42.411] Search path: [[[REDACTED]]]/example
> Info 17   [16:53:42.413] ConfigFilePresence:: Current Watches: :: File: [[[REDACTED]]]/example/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: [[[REDACTED]]]/example/example-app.tsx Status: File added to open files impacted by this config file
> Info 18   [16:53:42.413] ConfigFilePresence:: Current Watches: :: File: [[[REDACTED]]]/example/jsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: [[[REDACTED]]]/example/example-app.tsx Status: File added to open files impacted by this config file
> Info 19   [16:53:42.414] ConfigFilePresence:: Current Watches: :: File: [[[REDACTED]]]/tsconfig.json Currently impacted open files: RootsOfInferredProjects:  OtherOpenFiles: [[[REDACTED]]]/example/example-app.tsx Status: File added to open files impacted by this config file
> Info 20   [16:53:42.414] For info: [[[REDACTED]]]/example/example-app.tsx :: Config file name: [[[REDACTED]]]/tsconfig.json
> Info 21   [16:53:42.414] Opened configuration file [[[REDACTED]]]/tsconfig.json
> Info 22   [16:53:42.415] FileWatcher:: Added:: WatchInfo: [[[REDACTED]]]/tsconfig.json 2000 undefined Project: [[[REDACTED]]]/tsconfig.json WatchType: Config file
> Info 23   [16:53:42.417] event:
>     {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"[[[REDACTED]]]/tsconfig.json","reason":"Creating possible configured project for [[[REDACTED]]]/example/example-app.tsx to open"}}
> Info 24   [16:53:51.503] Config: [[[REDACTED]]]/tsconfig.json : {
>  "rootNames": [
>   "[[[REDACTED]]]/main.ts",
>   "[[[REDACTED]]]/example/example-app.tsx"
>  ],
>  "options": {
>   "jsx": 2,
>   "configFilePath": "[[[REDACTED]]]/tsconfig.json"
>  }
> }
> Info 25   [16:53:51.504] DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]] 1 undefined Project: [[[REDACTED]]]/tsconfig.json WatchType: Wild card directory
> Info 26   [16:53:51.504] //[[[REDACTED]]] for path [[[REDACTED]]] not found in cache...
> Info 27   [16:53:51.504] Starting C:\Program Files\Microsoft VS Code\Code.exe with args:
>     ["c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/watchGuard.js","[[[REDACTED]]]"]
> Info 28   [16:53:51.994] WatchGuard for path [[[REDACTED]]] returned: OK
> Info 29   [16:53:52.331] Elapsed:: 826.823399066925ms DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]] 1 undefined Project: [[[REDACTED]]]/tsconfig.json WatchType: Wild card directory
> Info 30   [16:53:52.331] Loading global plugin typescript-vscode-sh-plugin
> Info 31   [16:53:52.331] Enabling plugin typescript-vscode-sh-plugin from candidate paths: c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features,c:/Program Files/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
> Info 32   [16:53:52.331] Loading typescript-vscode-sh-plugin from c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features (resolved to c:/Program Files/Microsoft VS Code/resources/app/extensions/typescript-language-features/node_modules)
> Info 33   [16:53:52.337] typescript-vscode-sh-plugin initialized. Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
> Info 34   [16:53:52.337] Plugin validation succeded
> Info 35   [16:53:52.338] FileWatcher:: Added:: WatchInfo: [[[REDACTED]]]/main.ts 500 undefined Project:  WatchType: Closed Script info
> Info 36   [16:55:49.885] Starting updateGraphWorker: Project: [[[REDACTED]]]/tsconfig.json
> Info 37   [16:55:52.191] DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]]/components 1 undefined Project: [[[REDACTED]]]/tsconfig.json WatchType: Failed Lookup Locations
> Info 38   [16:55:52.191] watchDirectory for [[[REDACTED]]]/components uses cached drive information.
> Info 39   [16:55:53.678] Elapsed:: 1486.9540011882782ms DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]]/components 1 undefined Project: [[[REDACTED]]]/tsconfig.json WatchType: Failed Lookup Locations
> Info 40   [16:56:18.313] DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]]/node_modules 1 undefined Project:  WatchType: node_modules for closed script infos in them
> Info 41   [16:56:18.313] watchDirectory for [[[REDACTED]]]/node_modules uses cached drive information.
> Info 42   [16:56:19.914] Elapsed:: 1600.9341011047363ms DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]]/node_modules 1 undefined Project:  WatchType: node_modules for closed script infos in them
>

**Comment by adjenks** [comment]
Additionally, running `tsc` in the folder takes only a few seconds and outputs a reasonable error report.

**Comment by Daijobou** [comment]
I have this too and its never finished. (statusbar)
![image](https://user-images.githubusercontent.com/260343/114999893-8cdb3980-9ea2-11eb-8874-ba4211513344.png)

**Comment by adjenks** [comment]
It would be an improvement if the js/ts feature loading process would simply alert the user about what problems it has encountered, but it doesn't inform me of any errors. Perhaps the logs are not supposed to be readable by a user, but this leaves me with nothing, because I can barely understand what this line means, particularly the last bunch of words:

> Info 42 [16:56:19.914] Elapsed:: 1600.9341011047363ms DirectoryWatcher:: Added:: WatchInfo: [[[REDACTED]]]/node_modules 1 undefined Project: WatchType: node_modules for closed script infos in them

**Comment by adjenks** [comment]
I'm sorry, the tone in my previous message sounded ungrateful. That wasn't my intent, I'm just sharing my experience. I appreciate the effort that goes into this project. Thank you for looking into this issue.

**Comment by adjenks** [comment]
This issue is reported many times:
https://github.com/microsoft/vscode/issues/109847
https://github.com/microsoft/vscode/issues/120058
https://github.com/microsoft/vscode/issues/119268
https://github.com/microsoft/vscode/issues/118643

**Comment by adjenks** [comment]
I think it has to do with a slow network connection. I have a file server that I'm connected to, and when I'm connecting remotely there is a very large latency of about 5 seconds to interact with the server. If I right click a file and click "reveal in explorer" it takes about 5 seconds before the window will pop up for example. I do not have the same issue in my other work environment inside the network with faster file access.

**Comment by adjenks** [comment]
This issue is reported many times:
https://github.com/microsoft/vscode/issues/109847
https://github.com/microsoft/vscode/issues/120058
https://github.com/microsoft/vscode/issues/119268
https://github.com/microsoft/vscode/issues/118643
https://github.com/microsoft/vscode/issues/97657
https://github.com/microsoft/vscode/issues/101500
https://github.com/microsoft/vscode/issues/76667

**Comment by mjbvz** [comment]
@adjenks If you are on a very slow network,  it sounds like the progress indicator is doing it's job. It is telling you that VS Code is still trying to process all the JS files in your workspace so you will not have project wide IntelliSense

If you believe this is incorrect and there is a bug, please share details about your project setup

**Comment by adjenks** [comment]
@mjbvz The "progress indicator" does not actually indicate how much progress there is, and based on how many tickets have been opened about it users seem to think its broken when it takes such a long time to load. @Daijobou said that it "never" finished, so it might be nice if they were able to know if it really would never finish, or if it might finish after several hours.

So perhaps it's in need of a better progress indicator. At least a counter of how many files it's processed would be nice. Then we would be aware if it's actually a latency problem or a real error. It would also be nice to know if my tsconfig file has any impact on what gets parsed as well.

**Comment by mjbvz** [comment]
This is by-design. It is not possible to know how many files a project includes without looking at all the files in the project

There are a lot of tickets around this because it's a super generic symptom that can be caused by everything from actual bugs with specific project setups to trying, to misconfigurations that cause an  entire node_modules directory to be loaded

**Comment by adjenks** [comment]
@mjbvz Yes I understand it's not possible without looking at them all, which would waste time, which is why I suggested "a counter of how many files it's processed", not a percent complete indicator.
It doesn't need to say how many are left, just show a counter, so you can see that it's actually still doing something or not.
