### ISSUE TITLE
Splitting the preview of an image does not duplicate the view

### ISSUE THREAD

**Issue by j-marcon** [microsoft/vscode#121429]
Issue Type: <b>Bug</b>

Hi, I'm trying to open a PNG and split the preview right so I have two copies of the same image preview side by side. When I do so, the image preview transfers to the newly created tab on the right and the preview on the left just disappears.

It used to work fine before issue #120879 appeared. The latter issue got fixed but, now, I'm having this new issue where I lose the original preview. Any thoughts?

VS Code version: Code - Insiders 1.56.0-insider (25785b97e533b15ae3b12e48aaf4187416437e62, 2021-04-15T05:12:50.817Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.12.14-122.63.1.20210309-nasa

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.5
remote-containers|ms-|0.167.0
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
remote-wsl|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
vsonline|ms-|1.0.3076
githistory|don|0.6.16
latex-workshop|Jam|8.16.1
svg|joc|1.4.5
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.6.751425733
cpptools|ms-|1.3.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
hide-gitignored|npx|1.1.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.12
gitblame|wad|6.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30278404
vsc_aa:30263845
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfiletextcf:30288478
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by lramos15** [comment]
@mjbvz My guess is that this issue sprung up when we moved the overrides into the editor service and not the editorGroup. It appears that just calling copy on a custom editor input doesn't work as the webview isn't copied and therefore you can't have two CustomEditorInputs for the same resource. Any suggestions?

**Comment by lramos15** [comment]
After discussion with @bpasero it seems like we will have to introduce a copy function of sorts into the `IEditorInput` this was previously working due to the overrides being in the `groupView`. This still works for notebooks however.

**Comment by lramos15** [comment]
@bpasero If you have some time and would like to give feedback on the above commit please do as I just introduced a copy method.

**Comment by bpasero** [comment]
@lramos15 given we have a default implementation in `EditorInput`, I would think that `copy` does not need to be optional in the interface:

https://github.com/microsoft/vscode/blob/c2041ceed35f55d4b8efd247d9eb8d188ee3f3a8/src/vs/workbench/common/editor.ts#L543-L543

I also wonder if the name is a bit misleading because we seem to be calling this method either when moving or when copying the editor? Do we need to make that clearer?

https://github.com/microsoft/vscode/blob/3418b95ac34d25d4865292c202623948f38c3351/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L1215-L1215

**Comment by lramos15** [comment]
@bpasero I have cleaned it up here https://github.com/microsoft/vscode/commit/b57a9d16c936d6b061ce96a807534906a25768a8
it being triggered when moving was a bug.

**Comment by j-marcon** [comment]
As of right now, it's working again in the Insiders version. Thanks for the fix!
