### ISSUE TITLE
VSCode fails to recognize URLs containing the characters 【】

### ISSUE THREAD

**Issue by BettyJJ** [microsoft/vscode#121438]
- VS Code Version: 1.55.2
- OS Version: Windows 10 18363.1440

Steps to Reproduce:

1. enter a URL containing 【 or 】, for example: https://zh.wikipedia.org/wiki/【我推的孩子】

VSCode usually can recognize URLs with non-alphanumeric characters, for example, the URL https://zh.wikipedia.org/wiki/新加坡 can be properly recognized and you can ctrl+click to open it. 

However, URLs containing 【 or 】, like the above example I gave, cannot be properly recognized in VSCode.

I assume this is a bug or an oversight rather than a design decision, as I can't see any reason to exclude 【 or 】 in URLs. While I write this issue I notice that Github actually recognizes such URLs with no problem, so I guess it's not outrageous to ask VSCode to support them too.

Does this issue occur when all extensions are disabled?: Yes

**Comment by hediet** [comment]
@alexdima in [this commit](https://github.com/microsoft/vscode/commit/7018ffce0bf2873bfd71ead5612b974b475bcffc#diff-47ef45cdeef86c6a54aa67b5c25a970fea5fa4e134160e377aefe0e589906ca9R51) "【" was explicitly marked as url termination character. I don't know why though. Shall I just remove it?

**Comment by BettyJJ** [comment]
@hediet Thanks for pointing out the place! This list seems to contain a lot of punctuation marks and many of them may be a little questionable. For instance `‘“〈《「『【〔（［｛｢｣｝］）〕】』」》〉”’` are all just variations of parentheses or quotation marks. They are often used as part of an URL rather than to terminate an URL. But since there are so many of them I don't know what is the best way to handle it. Some people may have been relying on this behavior and removing some characters could break it. Maybe you can make it customizable but then that would add to your workload.

**Comment by alexdima** [comment]
I think it's fine to change things and remove "【" / "】" as force termination characters. Especially if there are things like wikipedia links with them. Actually, the best change would be to do some logic similar as we do for "(" / ")", where we actually tweak behavior for ")" based on the presence of "(" inside the link or not.

**Comment by hediet** [comment]
> 《 》 https://zh.wikipedia.org/wiki/《新青年》编辑部旧址
> “ ” https://zh.wikipedia.org/wiki/“常凯申”误译事件

These links should work now too!
