### ISSUE TITLE
Support more properties for markdown hover span styling

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121497]
```js
const markdown = new MarkdownString(undefined, true);
markdown.isTrusted = true;
markdown.appendMarkdown(`<span style="color:#7cc54b;">$(pass)</span> `);
```

Currently markdown hover supports only `color` & `background-color`. It would be great to expand that list to:

`padding`
`border`
`border-radius`
`font-size`

Since `color` and `background-color` support only a subset of possible values (6digit hex color) - it would make sense to also only support a limited number of values (6digit hex + px for size)

**Comment by alexr00** [comment]
Given that we want to have markdown hovers have a somewhat unified look, I don't think that we'll be expanding the set of allowed style properties. 

This is also a game of whack-a-mole. There will always be more properties that extension developers want. If we do decide to support additional values, the solution probably isn't to handpick more values to support, but instead to use an iframe and allow html.
