### ISSUE TITLE
Editor hint in untitled file does not scale with editor font zoom

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#121427]
Version: 1.56.0-insider
Commit: 94d369e27d19f598228961e9feb0413f2edabe5d
Date: 2021-04-14T12:11:28.196Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

1. Enable the setting "editor.mouseWheelZoom"
2. Open new untitled file
3. Use mouse + control to zoom in and zoom out, the editor hint doesn't scale.

![recording (11)](https://user-images.githubusercontent.com/9721254/114945193-ded67d80-9e16-11eb-992c-5b9688030e2f.gif)

**Comment by isidorn** [comment]
@sana-ajani great catch, thanks for filling this. Also feel free to assign issues to me directly if you know I am the owner.

Apart from changing the size to respect the editor font size I also decided to respect the editor font. Because imho it looks better.

**Comment by isidorn** [comment]
@sana-ajani can you please verify this? Thank you
