### ISSUE TITLE
Sync settings.json on wsl2

### ISSUE THREAD

**Issue by cool-delete** [microsoft/vscode#121434]
Can the remote setting.json of wsl2 be synchronized?
![image](https://user-images.githubusercontent.com/13638610/114962978-57cce800-9e9e-11eb-8aff-87d7fbd8cdc8.png)
This setting file is too old

😃most of my settings are on the wsl server

**Comment by cool-delete** [comment]
@sandy081  
Which issue is it duplicated? I can't find related issues.

**Comment by cool-delete** [comment]
Sync vscod-server setting.json
![image](https://user-images.githubusercontent.com/13638610/115023376-4bbe4600-9ef1-11eb-9286-866647ccdd17.png)

**Comment by sandy081** [comment]
https://github.com/microsoft/vscode/issues/90968

**Comment by cool-delete** [comment]
ok..i see
