### ISSUE TITLE
Hover widget doesn't use link hover color

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121536]
1.
```js
"workbench.colorCustomizations": {
	"textLink.foreground": "#ffae00",
	"textLink.activeForeground": "#00a2ff",
}
```
2. Open editor hover
3. Hover over any link
4. It correctly uses `textLink.foreground` and ignores `textLink.activeForeground`

![Screenshot (476)](https://user-images.githubusercontent.com/9638156/115106142-cf1c7d80-9f6b-11eb-8c16-1d6fcc1c25f9.png)

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.18363

**Comment by nrayburn-tech** [comment]
@usernamehw can you explain the issue/feature to me a bit more?  The way I am understanding it right now, is the behavior I am seeing, so I think I am misunderstanding something.

I have this in my settings.
```
"workbench.colorCustomizations": {
      "textLink.foreground": "#ff0000", // red
      "textLink.activeForeground": "#0000ff" // blue
}
```

This is what I see.  Where/when am I expected to see the blue text?
<img width="939" alt="Screen Shot 2021-05-07 at 6 43 02 PM" src="https://user-images.githubusercontent.com/52075362/117518088-0f1bc280-af64-11eb-8993-932260103428.png">

**Comment by usernamehw** [comment]
@nrayburn-tech when you mouseover the link, like here:

![hover_over_lnk_in_welcome](https://user-images.githubusercontent.com/9638156/117526970-090ffb00-afd1-11eb-9775-063b350612f6.gif)

**Comment by nrayburn-tech** [comment]
@usernamehw thanks for clarifying, submitted a PR for this.
