### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mpr119** [microsoft/vscode#121544]
- Issue Type: `Bug`
- Extension Name: `emmet`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by rzhao271** [comment]
@mpr119 what issue are you having with the extension? Can you paste some steps to help me reproduce the issue?
