### ISSUE TITLE
feature request: list of ready for sync remote/local commits

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#12159]
- VSCode Version: 1.5.2
- OS Version: Win10

Before sync changes some time need to recheck what changes will go to remote server.
Currently in status bar we can see only number of sync remote/local commits on "Synchronize changes" button.
Can you split git-sidebar and in bottom part output names of remote/local commits? You can make combobox to choose which unsync commits to show: local or remote.

thank you.

**Comment by joaomoreno** [comment]
Merging into #8655
