### ISSUE TITLE
"stty: stdin isn't a terminal" when --[un]install-extension from cli

### ISSUE THREAD

**Issue by kbd** [microsoft/vscode#121526]
Issue Type: <b>Bug</b>

When installing or uninstalling an extension from the commandline, I'm getting:

```
stty: stdin isn't a terminal
(eval):1: can't change option: zle
```

in zsh, and:

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
stty: stdin isn't a terminal
```

in bash.

Here's a full session in zsh:

```
$ code --install-extension rust-lang.rust
Installing extensions...
stty: stdin isn't a terminal
(eval):1: can't change option: zle
Installing extension 'rust-lang.rust' v0.7.8...
(node:67856) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'rust-lang.rust' v0.7.8 was successfully installed.

$ code --uninstall-extension rust-lang.rust
Uninstalling rust-lang.rust...
stty: stdin isn't a terminal
(eval):1: can't change option: zle
Extension 'rust-lang.rust' was successfully uninstalled!

$ code --version                           
1.55.1
08a217c4d27a02a5bcde898fd7981bda5b49391b
x64
```

and in bash:

```
$ code --install-extension rust-lang.rust
Installing extensions...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
stty: stdin isn't a terminal
Installing extension 'rust-lang.rust' v0.7.8...
(node:69265) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'rust-lang.rust' v0.7.8 was successfully installed.

$ code --uninstall-extension rust-lang.rust
Uninstalling rust-lang.rust...
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
stty: stdin isn't a terminal
Extension 'rust-lang.rust' was successfully uninstalled!
```

I've tested it in both iTerm2 and Kitty terminals, and on different machines as well.

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T18:22:52.186Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id a45c906b-fd2d-458e-b78c-95e8a1d51689|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
zls-vscode|Aug|1.0.4
better-toml|bun|0.3.2
bracket-pair-colorizer-2|Coe|0.2.0
crystal-lang|cry|0.8.2
vscode-eslint|dba|2.1.20
vscode-dash|dee|2.4.0
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
code-runner|for|0.11.3
go|gol|0.24.1
todo-tree|Gru|0.0.211
terraform|has|2.10.0
elixir-ls|Jak|0.7.0
vscode-peacock|joh|3.9.1
chat|kar|0.35.0
nim|kos|0.6.6
rust-analyzer|mat|0.2.554
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.12.1
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.0
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
polacode|pnp|0.3.4
vscode-coverage-gutters|rya|2.7.2
rewrap|stk|1.14.0
zig|tie|0.2.5
shellcheck|tim|0.14.0
errorlens|use|3.2.5
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by deepak1556** [comment]
Refs https://github.com/microsoft/vscode/issues/119660#issuecomment-809332973

Can you check if the issue exists in our insiders https://code.visualstudio.com/insiders/, will be fixed in next stable release.
