### ISSUE TITLE
Cannot center window in notebooks

### ISSUE THREAD

**Issue by jackos** [microsoft/vscode#121531]
- VS Code Version: 1.55.1
- OS Version: Arch Linux

Steps to Reproduce:

1. Create a Jupyter notebook .ipynb
2. Make a few cells that fill up more than a screen
3. Try to center the window using extensions, vims 'zz' hotkey or the inbuilt 'Center Active Cell' shortcut, nothing works

Does this issue occur when all extensions are disabled?: Yes

This is very annoying as it's the only time I have to take my hand off the keyboard, ideally I want to be able to use vims 'zz' and 'zt' like I can in any other document than a Jupyter notebook.

**Comment by jackos** [comment]
Hi @rebornix I'm very sorry for the delay, I missed your response.

See VSCode locking out the ability to use Vim keybindings that recenter the window, I demonstrate how it works on a normal file, then show it not working in a notebook:
https://user-images.githubusercontent.com/77730378/119074735-222d9880-ba22-11eb-9129-7b90394ca907.mp4
 This is the same for any extensions such as [Center window extenstion](https://marketplace.visualstudio.com/items?itemName=kaiwood.center-editor-window)

Here I show using the notebook with keyboard shortcuts that are available:

https://user-images.githubusercontent.com/77730378/119074930-82243f00-ba22-11eb-8e13-fd04a2446860.mp4

Notice that none of them do what I need, which is to display the graph fullscreen by moving the view so that the cursor is at the top.

There are three ways that this could be fixed:
1) Add the ability to use the old style of having a split window, so the output is on the right and the input is on the left
2) Stop notebooks from blocking extensions that recenter the window
3) Add keyboard shortcuts that mimic notebook.centerActiveCell, except that move the view to the top and bottom eg. notebook.viewActiveCellBottom and notebook.viewActiveCellTop

Just want to add that I sincerely love VSCode especially the recent improvements to notebooks, and that this is the only part that stops me from having a fully Modal Jupyter experience.

**Comment by rebornix** [comment]
Thanks, the Vim extension should handle this special case.

**Comment by Kevin-Delnoije** [comment]
@rebornix  option 3  of jackos seems necessary for people to move view to top or bottom or is there some other way to do it?
if so i would love to know so i can edit my keybindings/settings.json
