### ISSUE TITLE
March release notes include incorrect link

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode#121565]
There appears to be a minor issue with the [release notes](https://github.com/microsoft/vscode/releases).

Version [1.55.2](https://github.com/microsoft/vscode/releases/tag/1.55.2) and [1.55.1](https://github.com/microsoft/vscode/releases/tag/1.55.1) include an ["Updates"](https://code.visualstudio.com/updates/v1_39) link that links to 2019 releases.

**Comment by gjsjohnmurray** [comment]
/confirm
![image](https://user-images.githubusercontent.com/6726799/115133071-49491280-9ffd-11eb-8884-9946235213d9.png)

/assign @TylerLeonhardt

**Comment by dnicolson** [comment]
The links in the release notes for version 1.55.0 also do not work.

**Comment by TylerLeonhardt** [comment]
Fixed! Thanks everyone!
