### ISSUE TITLE
Ugly miniature with Open with... on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by Excelssior** [microsoft/vscode#121589]
Issue Type: <b>Bug</b>

I have an ugly icon when I right-click and choose Open with... on macOS Big Sur 11.2.3

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 6b054934-a909-4262-af64-8dd7cf45b4f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
javadoc-tools|mad|1.4.0
mssql|ms-|1.10.1
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
java|red|0.77.0
scala|sca|0.5.3
metals|sca|1.10.2
indent-one-space|use|0.2.6
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

![VSCode_issue](https://user-images.githubusercontent.com/76174883/115146650-af628380-a057-11eb-8694-5dca23daf949.png)

**Comment by Excelssior** [comment]
Hello,

Thank you for your return. Unfortunately, the command doesn't work on my
terminal.

**Comment by deepak1556** [comment]
Can you paste the output you get.

**Comment by Excelssior** [comment]
Yes, I attached a picture in my precedent mail but here it is :

Visual Studio Code.app/Contents/Resources/Code.icns:ICNS file not found.

**Comment by deepak1556** [comment]
Which directory are you running the command from ? Make sure you are under the directory where vscode application is installed.

**Comment by Excelssior** [comment]
I'm running the command from Mims@MacBook-Air-de-Jeremy Visual Studio
Code.app %
where Mims@MacBook-Air-de-Jeremy is the name of my computer.

**Comment by deepak1556** [comment]
If you are running from `Visual Studio Code.app` directory, then change the command to

```
iconutil -c iconset -o ~/Desktop/code-temp.iconset Contents/Resources/Code.icns
```

**Comment by Excelssior** [comment]
IT WORKS !
But now I have no idea how to attach code-temp.iconset in the directory. Do
I have to us the link command in the same directory terminal ?

**Comment by deepak1556** [comment]
You can zip it and attach to the issue.

**Comment by Excelssior** [comment]
In the Visual Studio Code directory ?
Thank you for your answer !

**Comment by deepak1556** [comment]
`code-temp.iconset` should be generated in the Desktop folder, you can make it a zip and then attach the file to this issue.

**Comment by Excelssior** [comment]
I'm sorry I do not understand what "issue" mean here... Do I have to do
that with a command on the terminal ?

**Comment by deepak1556** [comment]
![recording](https://user-images.githubusercontent.com/964386/115761092-cf938a80-a356-11eb-9bf6-9605bbd645b1.gif)

**Comment by Excelssior** [comment]
Thank you for your answer.
I did exactly as you did and It is still ugly.
Here is what I typed on my terminal :

Mims@MacBook-Air-de-Jeremy Visual Studio Code.app % iconutil -c iconset -o
~/Desktop/code-temp.iconset Contents/Resources/Code.icns

Mims@MacBook-Air-de-Jeremy Visual Studio Code.app % zip
~/Desktop/iconset.zip ~/Desktop/code-temp.iconset

  adding: Users/Mims/Desktop/code-temp.iconset/ (stored 0%)

**Comment by deepak1556** [comment]
The above command will not fix the issue. We would like to inspect the contents of the zip file to identify where the issue lies in. So please provide the zip file as shown in the screencast.

**Comment by Excelssior** [comment]
Ok, I get it !
[iconset.zip](https://github.com/microsoft/vscode/files/6361057/iconset.zip)

**Comment by Excelssior** [comment]
It changes ! 
Thank you for your answers and your patience ! 
![Capture d’écran 2021-04-25 à 13 58 01](https://user-images.githubusercontent.com/76174883/115992521-6cac2880-a5ce-11eb-92f2-3bbe6edc2d6b.png)

**Comment by deepak1556** [comment]
Closing per above comment as resolved.
