### ISSUE TITLE
Simple Browser address bar does not update

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#121570]
Issue Type: <b>Bug</b>

1. Open Simple Browser from Command Palette.
2. Enter the address of a page that contains links to other pages.
3. Click on one of those links in page 1.

Navigation occurs but the address entered in step 2 remains unchanged.

4. On page 2, click a link to a third page.

The address bar continues to show the page 1 adddress but the content is now page 3.

5. Use the Back button. Page 2 content displays but address bar still shows that of page 1.

/assign @mjbvz

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.19042

**Comment by mjbvz** [comment]
This is a known limitation. For security reasons, can't track what actually happens in the iframe that is rendering the content. This means we can't know which page a user is on, or even if a page failed to load
