### ISSUE TITLE
Update TypeScript to v4.2.4 for VSCode 1.55.X

### ISSUE THREAD

**Issue by Julien-Marcou** [microsoft/vscode#121583]
Issue Type: <b>Bug</b>

TypeScript 4.2.4 has been released 10 days ago and fixes an issue about DocTags being incorrectly reported for documentation popups on some method signatures, which was leading to unexpected deprecation warnings when using extensions such as TSLint or ESLint.

While this issue has been fixed on the main branch of VSCode, it hasn't been fixed on the 1.55 branch yet.

[Issue closed by TypeScript 4.2.4](https://github.com/Microsoft/TypeScript/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22TypeScript+4.2.4%22)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

**Comment by mjbvz** [comment]
This already happened in mai and is scheduled to ship in VS Code 1.56
