### ISSUE TITLE
Not need going out from ZMode when push escape button on keyboard

### ISSUE THREAD

**Issue by andrejs82git** [microsoft/vscode#121574]
Issue Type: <b>Feature Request</b>

I going ot ZMode by push Ctrl+K then Z.
Ok. I am in ZMode.
Then I working in Zmode working working.
And then I push ESC button on keyboard for some reasons. I can push many times ESC button - I think it normal. But if I push ESC to many times I am going out from ZMode. 
That bad behavior.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
Jackson now owns Zen mode thus forwarding to him.
