### ISSUE TITLE
VS Code Mac update will not download

### ISSUE THREAD

**Issue by animado31** [microsoft/vscode#121555]
Just installed VSC on a new mac. Downloaded python and was given the prompt below for command line developer tools. Try to download them and the download gets stuck about halfway through. I'm online, no issues with the connection. I'm on an admin account so no worries with permissions. I can download files from the web, it's just this file for VSC that doesn't work.

The prompt: "The "python3" command requires the command line developer tools. Would you like to install the tools now?"

**Comment by tymsai** [comment]
reinstall the VSCode again, and try

**Comment by sunhongfan** [comment]
> 刚在新的Mac上安装了VSC。下载了python，并在提示符下显示了命令行开发人员工具。尝试下载它们，下载将在大约一半时卡住。我在线，连接没有问题。我使用的是管理员帐户，因此无需担心权限。我可以从网上下载文件，仅此文件对于VSC不起作用。
> 
> 提示：““ python3”命令需要命令行开发人员工具。您现在要安装这些工具吗？”

Is it too CPU intensive to close VS code when you're running Python

**Comment by animado31** [comment]
> reinstall the VSCode again, and try

I have. Several times. Didn't work.

**Comment by animado31** [comment]
> > 刚在新的Mac上安装了VSC。下载了python，并在提示符下显示了命令行开发人员工具。尝试下载它们，下载将在大约一半时卡住。我在线，连接没有问题。我使用的是管理员帐户，因此无需担心权限。我可以从网上下载文件，仅此文件对于VSC不起作用。
> > 提示：““ python3”命令需要命令行开发人员工具。您现在要安装这些工具吗？”
> 
> Is it too CPU intensive to close VS code when you're running Python

No, the CPU isn't really running anything other than a couple firefox windows.
