### ISSUE TITLE
Less variables should be colored as the value color

### ISSUE THREAD

**Issue by elkebirmed** [Microsoft/vscode#12155]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

- I think **Less** variables should be colored as the value and not as the variable name:

    ![screenshot from 2016-09-16 15-40-45](https://cloud.githubusercontent.com/assets/3056412/18590344/598450ce-7c26-11e6-9927-7f30def9298a.png)

- **Intellisense** is not suggesting variables that are in an *imported* **Less** files

**Comment by Tyriar** [comment]
I can't reproduce on 1.6.0-insiders?

![image](https://cloud.githubusercontent.com/assets/2193314/18603701/d1043ca2-7c28-11e6-8f7f-09dcf9cf3c47.png)

**Comment by elkebirmed** [comment]
This's good @Tyriar but what about coloring the variable when assigned to a CSS property, even from an imported Less file *(as a new feature)*

```css
p {
  color: $foo; /* $foo should be colored */
}
```

**Comment by elkebirmed** [comment]
The feature i'm looking is like Atom package: **Pigments**

**Comment by Tyriar** [comment]
I tacked on pre-processor variables to the feature request here https://github.com/Microsoft/vscode/issues/6823, cross-file variable resolution is captured in https://github.com/Microsoft/vscode/issues/6820
