### ISSUE TITLE
VSCode “fileName” not found

### ISSUE THREAD

**Issue by salda** [Microsoft/vscode#12151]
- VSCode Version: 1.5.2
- OS Version: 7

Steps to Reproduce:

1. Set up VSCode, C/C++ package, g++, Clang and GDB hopefully correctly. 
2. Include some file. 

See http://stackoverflow.com/questions/39512079/vscode-filename-not-found. 
![image](https://cloud.githubusercontent.com/assets/3855627/18587305/9f90dd1c-7c21-11e6-8cdd-b0ce887a73ed.png)

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!

**Comment by salda** [comment]
Thanks for feedback, but the problem is that I can't find what extension is causing it, because there isn't the disable extension option yet and when I remove the extensions, another problems appear. Is there a way to guess what extension writes into Problems window output? Maybe I can somehow guess from the icon, what extension it is, but I don't know for now.

**Comment by bpasero** [comment]
@salda since you are editing C++ maybe we try the C++ extension first?

**Comment by salda** [comment]
Ok, thanks a lot, but I really don't want to uninstall it, because I am afraid that it can mess my configurations or something. I will wait for the disable extension option, because setting everything correctly was very complex for me. 

You wrote "it seems that the issue originates from an extension and not VS Code itself", but it seems that the issue originates from VS Code itself, because after the cross in the red circle in the Problems window output, there isn't any extension name and when I checked other issues, there was a name of the extension after it, like "[eslint] 'iostream' file not found" instead just "'iostream' file not found".

**Comment by bpasero** [comment]
@salda I was not suggesting to uninstall the extension, but rather to move this discussion to the C++ extension and ask why your import cannot be resolved.
