### ISSUE TITLE
Find widget in Release Notes only highlights first typed character

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#121568]
Issue Type: <b>Bug</b>

1. Open Release Notes from the Help menu.
2. Open its Find in Page widget (Ctrl/Cmd+F)
3. Type `v` then `s`

Occurrences of the first character are highlighted correctly, but :bug: the highlighting doesn't change when I type the second character. It only updates when I press Enter, which also jumps me to the first occurrence of the character pair.

![junk](https://user-images.githubusercontent.com/6726799/115134657-f3c73280-a009-11eb-897b-c38001b4bba5.gif)

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
pinging @mjbvz for webview and @deepak1556 since I have a hunch this could be an upstream Electron issue

**Comment by IllusionMH** [comment]
Looks like duplicate of #120158

**Comment by gjsjohnmurray** [comment]
Thanks @IllusionMH. Closing as duplicate.
