### ISSUE TITLE
Add new version number in extenstions tab

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#12154]
add new version number in extensions tab

<img width="1119" alt="screen shot 2016-09-16 at 7 24 16 pm" src="https://cloud.githubusercontent.com/assets/1549069/18590326/a576a924-7c43-11e6-88b9-ce0cf2533aa2.png">

**Comment by rozzzly** [comment]
Some link to the github/project homepage would be awesome too.

**Comment by uxitten** [comment]
@rozzzly +1

**Comment by ffes** [comment]
The additional feature request for repository and homepage has it's own issue #19718

**Comment by joaomoreno** [comment]
This is fixed.

**Comment by uxitten** [comment]
thank you
