### ISSUE TITLE
Live Server 

### ISSUE THREAD

**Issue by Barot-sam** [microsoft/vscode#121582]
Issue Type: <b>Bug</b>

My live server in VS Code is not Working and  Showing Following Error 
"Cannot GET /Css%20Grid%20%20"
Please Help Me With This issue

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.12GB free)|
|Process Argv|--crash-reporter-id b8fa8836-5977-4aba-ba8b-20e3dbd74c03|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (116)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
aessoft-class-autocomplete|AES|0.1.0
include-autocomplete|ajs|0.0.4
vscode-javascript-snippet-pack|aka|0.1.6
cppincludeguard|aki|1.3.1
project-manager|ale|12.1.0
html-class-suggestions|And|1.1.1
vscode-django|bat|1.6.0
bootstrap-snippets-vscode|bha|0.3.0
htmlplay|bia|0.0.5
git-easy|bib|1.11.0
lit-html|bie|1.11.1
exe-runner|bra|0.1.0
c-compiler|bra|0.0.4
htmlenterpp|chi|1.0.0
html-entities|chr|1.1.2
html-biscuits|Cod|0.0.12
gitignore|cod|0.6.0
compulim-vscode-closetag|Com|1.2.0
the-powerful-bootstrap|Cro|1.2.4
doxdocgen|csc|1.1.0
quick-html-previewer|dai|1.0.1
c-cpp-compile-run|dan|1.0.14
c-cpp-project-generator|dan|1.2.4
angular2-snippets|dan|1.0.21
git-extension-pack|don|0.1.3
githistory|don|0.6.16
python-extension-pack|don|1.6.0
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
bootstrap-4-cdn-snippet|eve|1.11.1
html-to-javascript-string|evi|0.0.6
git-commits|Exe|3.7.14
cshtml|fir|0.1.3
cshtml-tm|fir|1.0.0
code-runner|for|0.11.3
html-preview-vscode|geo|0.2.5
html-snippets|gey|0.2.3
vscode-angular-html|gha|1.7.0
vscode-pull-request-github|Git|0.25.1
CppSnippets|har|0.0.15
live-html-previewer|hdg|0.3.0
angular-bootstrap|her|4.0.9
html-tag-wrapper|hwe|0.2.3
vscode-gnu-global|jay|0.3.3
c-cpp-flylint|jbe|1.9.0
better-cpp-syntax|jef|1.15.5
kite|kit|0.142.0
git-indicators|lam|2.1.2
ccpp-extension-pack|Leo|1.1.0
git-tree-compare|let|1.10.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
MagicPython|mag|1.1.0
start-git-bash|McC|1.2.1
Angular-BeastCode|Mik|10.0.3
bootstrap4-snippets|Min|1.0.0
vscode-clang|mit|0.2.3
HTMLHint|mka|0.10.0
vscode-html-format|moh|0.0.4
vscode-attrs-sorter|mrm|2.1.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
remote-wsl|ms-|0.54.6
azure-account|ms-|0.9.8
cmake-tools|ms-|1.6.0
cpptools|ms-|1.3.0
cpptools-extension-pack|ms-|1.0.0
js-debug-nightly|ms-|2021.4.1317
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsonline|ms-|1.0.3076
vs-html-to-css|nep|1.0.0
html-fmt-vscode|Nik|0.7.0
git-semantic-commit|nit|2.0.0
vscode-html-scss|P-d|0.0.42
jade-bootstrap|pac|0.2.7
vscode-cpptest|Par|2020.2.0
open-php-html-js-in-browser|Pri|2.0.1
htmlescape-vscode-extension|ray|0.0.7
java|red|0.77.0
html-to-jsx|ria|0.0.1
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
gcl|rix|0.2.0
html5-boilerplate|sid|1.1.1
html-to-css-autocompletion|sol|1.1.2
tabnine-vscode|Tab|3.4.2
cmantic|tde|0.7.1
eco|th7|0.0.2
bootstrap4-vscode|the|6.1.0
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
es6-string-html|Tob|2.2.0
html-validate-vscode|Tob|0.2.0
cmake|twx|0.0.17
usql-vscode-ext|usq|0.2.15
Angular2|UVB|0.4.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
Bootstrap-extension-pack|wal|0.0.3
bootstrap-3-snippets|wcw|0.1.0
prettify|whi|0.0.3
jinja|who|0.0.8
html-snippets|wsc|1.0.6
JavaScriptSnippets|xab|1.8.0
commandlist|yam|1.0.3
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by Barot-sam** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [live server (#118409)](https://www.github.com/microsoft/vscode/issues/118409)
> * [live server extension missing (#120038)](https://www.github.com/microsoft/vscode/issues/120038)
> * [live server fail to install (#117962)](https://www.github.com/microsoft/vscode/issues/117962)
> * [live server fail to install (#117963)](https://www.github.com/microsoft/vscode/issues/117963)
> * [live server un responsive (#119810)](https://www.github.com/microsoft/vscode/issues/119810)

None of the above cover my topic

**Comment by tymsai** [comment]
> Issue Type: Bug
> 
> My live server in VS Code is not Working and Showing Following Error
> "Cannot GET /Css%20Grid%20%20"
> Please Help Me With This issue
> 
> VS Code version: Code 1.55.2 ([3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d), 2021-04-13T09:35:57.887Z)
> OS version: Windows_NT x64 10.0.19042
> 
> System Info
> Item	Value
> CPUs	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
> GPU Status	2d_canvas: enabled
> gpu_compositing: enabled
> multiple_raster_threads: enabled_on
> oop_rasterization: enabled
> opengl: enabled_on
> protected_video_decode: enabled
> rasterization: enabled
> skia_renderer: enabled_on
> video_decode: enabled
> vulkan: disabled_off
> webgl: enabled
> webgl2: enabled
> Load (avg)	undefined
> Memory (System)	7.91GB (3.12GB free)
> Process Argv	--crash-reporter-id b8fa8836-5977-4aba-ba8b-20e3dbd74c03
> Screen Reader	no
> VM	0%
> Extensions (116)
> A/B Experiments

try to uninsatall and install again

**Comment by Barot-sam** [comment]
> > Issue Type: Bug
> > My live server in VS Code is not Working and Showing Following Error
> > "Cannot GET /Css%20Grid%20%20"
> > Please Help Me With This issue
> > VS Code version: Code 1.55.2 ([3c4e3df](https://github.com/microsoft/vscode/commit/3c4e3df9e89829dce27b7b5c24508306b151f30d), 2021-04-13T09:35:57.887Z)
> > OS version: Windows_NT x64 10.0.19042
> > System Info
> > Item	Value
> > CPUs	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)
> > GPU Status	2d_canvas: enabled
> > gpu_compositing: enabled
> > multiple_raster_threads: enabled_on
> > oop_rasterization: enabled
> > opengl: enabled_on
> > protected_video_decode: enabled
> > rasterization: enabled
> > skia_renderer: enabled_on
> > video_decode: enabled
> > vulkan: disabled_off
> > webgl: enabled
> > webgl2: enabled
> > Load (avg)	undefined
> > Memory (System)	7.91GB (3.12GB free)
> > Process Argv	--crash-reporter-id b8fa8836-5977-4aba-ba8b-20e3dbd74c03
> > Screen Reader	no
> > VM	0%
> > Extensions (116)
> > A/B Experiments
> 
> try to uninsatall and install again

I have Already tried It's not Working

**Comment by IllusionMH** [comment]
/causedByExtension

This is issue tracker for VS Code editor itself.
Please check that you have proper configuration and paths supported by the extension. If you still think it is bug in extension - report in extension repo.
