### ISSUE TITLE
Tree/list sends open-event on double clicking twisty

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121503]
Issue Type: <b>Bug</b>

I've never used them, so it might be expected?:

`.eslintrc.json`

```js
{
	"root": true,
	"parserOptions": {
		"ecmaVersion": 2018,
		"sourceType": "module",
		"project": "./tsconfig.json"
	}
}
```

![demo](https://user-images.githubusercontent.com/9638156/115078777-cb0b4400-9f08-11eb-8dfc-f223e8a9b931.gif)

Only closes for document symbols, directory tree work as expected.

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.18363

**Comment by AlexandroGonSan** [comment]
It should to be create configuration with current default set for enable users personalize.

**Comment by jrieken** [comment]
It looks like the tree is emitting a selection/open event when the twisty is double-clicked
