### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by UtkarshCoder-2209** [microsoft/vscode#121585]
Issue Type: <b>Feature Request</b>

I am getting an error:
command 'extension.executeAREPLBlock' not found. When ever I am using ctrl+enter shortcut.
I want to fix it...

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Maybe you have a keybinding that refers to a command on an extension you have disabled or uninstalled.

**Comment by UtkarshCoder-2209** [comment]
> Maybe you have a keybinding that refers to a command on an extension you have disabled or uninstalled.

How can I fix it?

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/getstarted/keybindings in general, and https://code.visualstudio.com/docs/getstarted/keybindings#_viewing-modified-keybindings in particular.

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+enter`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`ctrl+enter`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
