### ISSUE TITLE
window.onDidChangeNotebookEditorSelection doesn't fire when cells are 'unselected'

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#121505]
Version: 1.56.0-insider (user setup)
Commit: ce791d27dc9889a392f4d29abefe9c53eb0b5129
Date: 2021-04-16T11:25:09.662Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open a notebook
2. Select any cell (onDidChangeNotebookEditorSelection is fired as expected)
3. Click on the editor, but not on a cell (onDidChangeNotebookEditorSelection is not fired)

The problem is that if we want to have a ContextKey to place a button on the cell toolbar, only when the cell is selected, this event should tell us accurately which cells are selected.

Right now if we click anywhere else, the event won't fire and we can't update that the cells are no longer selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
@DavidKutu good catch!

**Comment by rebornix** [comment]
I no longer see this issue anymore on latest Insiders, here is the code I tried 

```
	vscode.window.onDidChangeNotebookEditorSelection(e => {
		console.log(e);
	}
```

* Click on a cell, the event is fired
* Escape, there is no selection anymore, the event is also fired

**Comment by roblourens** [comment]
Looks good, although the event is fired twice for each change
