### ISSUE TITLE
Hotkeys binding error

### ISSUE THREAD

**Issue by antirius** [Microsoft/vscode#1215]
Macbook. After selecting the text, if it is just trying to copy - move to a specific object. Very uncomfortable!

1. Select the text
2. Releasing tochpad
3. Immediately press cmd + c

Do not copy and jumped up

Video https://cloud.mail.ru/public/5874/ibzQNYA72

**Comment by egamma** [comment]
@jrieken can you repro this behaviour on OS X?

**Comment by antirius** [comment]
Yes, this error is permanent on OS X.

Removing and installing VScode again did not help

**Comment by antirius** [comment]
Just select the text and right click command. If the selection was completed over an object, the cursor will jump to the definition of the object.

**Comment by antirius** [comment]
https://cloud.mail.ru/public/Dg3L/oAxeRaqVy

**Comment by alexandrudima** [comment]
@bpasero I think this is the eager go to def

**Comment by bpasero** [comment]
Yeah i think so.
