### ISSUE TITLE
TreeItem `getChildren` shouldn't be called unless the item is expanded

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121567]
If you "refresh" an item (with children) by calling `this._onDidChangeTreeData.fire(<item>)` and the item is not expanded, the `getChildren` method still gets called. `getChildren` should not be called until the item is expanded, otherwise potentially expensive operations can be run for no visible reason (since the children are hidden).

**Comment by alexr00** [comment]
This could result in unexpected behavior. If an extension currently relies on `this._onDidChangeTreeData.fire(<item>)` to always update the children then there would be out-of-date tree items.

**Comment by eamodio** [comment]
@alexr00 How would this result in unexpected behavior? If the tree item has not loaded its children, why should calling refresh on it force its children to load?

**Comment by alexr00** [comment]
@joaomoreno I think a change like this would need to happen in the `AsyncDataTree`, as at the custom tree view level we have no knowledge of whether a node is currently expanded or not. Is this something you'd be interested in doing?

**Comment by joaomoreno** [comment]
@alexr00 Not sure I follow. What @eamodio describes is exactly how the AsyncDataTree works: children aren't resolved until the user expands the parent the first time.

**Comment by alexr00** [comment]
@joaomoreno I am looking for a way to call `updateChildren` on the AsyncDataTree such that if the tree item passed in to `updateChildren` is collapsed, it will:
- "invalidate" the children or the tree item and not actually call `getChildren` on that tree item
- rerender the tree item
instead of:
- calling `getChildren` for the tree item
- rerendering the tree item

**Comment by joaomoreno** [comment]
Oh I guess I was wrong, what I said only applies to the next level. But the first node `updateChilren` is called with will always have its `getChildren` be called.

We can maybe add an option here, or even change the default behavior as I see no reason for collapsed tree nodes to need a `getChildren` call.

**Comment by eamodio** [comment]
@joaomoreno @alexr00 any update here? This issue causes GitLens to request way more data than desired in multiple cases (before the user expands them that is).

**Comment by joaomoreno** [comment]
@eamodio Thanks for the nudge!

**Comment by joaomoreno** [comment]
@alexr00 Maybe it's easier if you verify this one.

**Comment by alexr00** [comment]
👍 will verify.
