### ISSUE TITLE
Setting Sync doesn't work on SolusOS

### ISSUE THREAD

**Issue by ehsanghorbani190** [microsoft/vscode#121579]
Issue Type: <b>Bug</b>

Hi :D
So i was testing this new linux distro SolusOS, and there's a problem with VSCode on it. The Setting Sync doens't work. I cannot even log in into my account! I log in through github(or microsoft) , i even get the github gist , and i paste it into vscode(i mean in the part that appears for login). but nothing happens. no errors , no warnings , just nothing. Any ideas?
sorry for bad english :D

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-09T20:33:19+03:00)
OS version: Linux x64 5.10.12-171.current

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|5.70GB (0.20GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|budgie-desktop|
|XDG_CURRENT_DESKTOP|Budgie:GNOME|
|XDG_SESSION_DESKTOP|budgie-desktop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
lit-html|bie|1.11.1
vscode-intelephense-client|bme|1.6.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
vscode-html-css|ecm|1.10.2
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
sass-lint|gle|1.0.7
vscode-atom-sass-snippet|glu|0.0.3
CppSnippets|har|0.0.15
ftp-simple|hum|0.7.6
java-properties|ith|0.0.2
css-snippets|joy|1.0.2
php-cs-fixer|jun|0.1.158
vscode-phpfmt|kok|1.0.30
fxml-viewer|lzw|1.0.1
twig-language-2|mbl|0.9.2
code-beautifier|mic|2.3.3
vscode-autoprefixer|mrm|3.0.1
vscode-duplicate|mrm|1.2.1
cpptools|ms-|1.3.0
color-highlight|nau|2.3.0
deepdark-material|Nim|3.3.0
es6-css-minify|olb|3.3.2
material-icon-theme|PKi|4.6.0
vscode-css-navigation|puc|1.10.6
java|red|0.77.0
vscode-checkstyle|she|1.4.0
javafx-support|shr|0.0.1
html5-boilerplate|sid|1.1.1
swdc-vscode|sof|2.5.11
sass-indented|syl|1.8.16
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
debug|web|0.25.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.13
html-css-class-completion|Zig|1.20.0
js-runner|Zol|3.2.0

(3 theme extensions excluded)

</details>

**Comment by sandy081** [comment]
> I cannot even log in into my account

Seems auth issue

**Comment by RMacfarlane** [comment]
Hey @ehsanghorbani190, can you report what is in the output panel for "GitHub Authentication" when you try this?

**Comment by ehsanghorbani190** [comment]
Hi again :D
the problem was fixed in new update! thanks!
