### ISSUE TITLE
 cpu is full 

### ISSUE THREAD

**Issue by sunhongfan** [microsoft/vscode#121573]
macos bigsur 
vscode up to date

When I open vscode, install the python extension, write the code and run it, everything is fine. When I close vscode, my fan keeps spinning. When I open the activity monitor of the system, two python processes appear. When I open vscode again, it will There are two more python processes, but I close them without killing these processes, and when I close vscode, these unclosed python processes cpu>100, they will not automatically exit.

**Comment by tymsai** [comment]
try the insiders build once for python with its extensions and tell if the problem persists.

**Comment by sunhongfan** [comment]
> 尝试内部人员使用扩展名为python构建一次，并判断问题是否仍然存在。

The problem still exists. When I open vscode to execute the python project, it runs well, and I see 2 processes named python on the activity monitor. The cpu occupancy is stable. When I close vscode completely, these 2 processes occupy a lot of cpu, again Turn it on and become 4 python processes, which can only be manually killed

**Comment by sunhongfan** [comment]
> 尝试内部人员使用扩展名为python构建一次，并判断问题是否仍然存在。

I run well on iterm2 locally, and also on pycharm.

**Comment by tymsai** [comment]
what is the version of python installed ?

**Comment by sunhongfan** [comment]
> 安装的python是什么版本？

3.8.2 and 3.9.4

**Comment by sunhongfan** [comment]
> 安装的python是什么版本？
Vscode does not recycle processes. I am using Venv's virtual environment

**Comment by tymsai** [comment]
is the problem only with python ? 
did you try c++ ? or any  other languages ?

**Comment by sunhongfan** [comment]
> python是唯一的问题吗？
> 你尝试过c ++吗？或任何其他语言？

No, because all I need to do is build Python  

Could you please repeat this question? I want to know what caused it, is it a Bug in the software itself

**Comment by sunhongfan** [comment]
https://github.com/microsoft/vscode-python/issues/13102   This is a clearer description of my problem

**Comment by tymsai** [comment]
as @fredrikaverpil said he had no spike in CPU core usage after changing the path/directory of python.venvPath, 
so you should also try the solution given by him.
