### ISSUE TITLE
Add drag and drop support to terminal tabs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121500]
Part of https://github.com/microsoft/vscode/issues/120241

**Comment by miclejackson12** [comment]
Just want to clarify one thing, I need drag and rearrange of terminal tabs like how it is possible for project files. Does "Drag and drop" mean  "Drag and Rearrange terminal tabs" or something else like dragging a file to terminal and running on terminal etc.?

**Comment by Tyriar** [comment]
@miclejackson12 this is covering rearranging within the list, so you will be able to order them and join/unsplit
