### ISSUE TITLE
Cannot step caret across a ligature if its components are assigned different colours by the colour scheme

### ISSUE THREAD

**Issue by Krantz-XRF** [microsoft/vscode#121591]
- VS Code Version: `1.55.2`
- OS Version: `Windows_NT x64 10.0.19042`

Steps to Reproduce:

(The steps below can be altered/simplified, but I am listing my very settings for 100% reproducing.)

1. Use a modified version of JetBrains Mono from [vbcpascal/CoqBrainsMono](https://github.com/vbcpascal/CoqBrainsMono);
2. Use colour scheme `Brackets Light Pro`(`eryouhao.brackets-light-pro`);
3. Install `vscoq` extension (`maximedenes.vscoq`);
4. Open a `.v` file (Coq source file);
5. Type `=[]=>` in the editor, note how ligature `=[` becomes blue and `]=>` remains black;
6. Try step the caret across these two ligatures by hitting the arrow keys (they don't appear within those ligatures);
7. Change colour scheme to `Light+` (default light theme), note how all these two ligatures become black, and how we are suddenly able to step across them;

My reasoning:
- `=` is assigned blue with both `vscoq` and `Brackets Light Pro` enabled;
- `[` is not assigned to any colour, so it remains black;
- now `=[` is a ligature introduced by the custom font above;
- Clearly something is happening exactly here, for either (a) disabling `vscoq` or (b) change to `Light+` colour scheme (thus making all characters black) immediately solves the problem;

Below is a screen recording using a slightly different approach to reproduce the problem:

https://user-images.githubusercontent.com/17098235/115146928-4d237600-a08b-11eb-87b4-fd6594afcc64.mp4

Does this issue occur when all extensions are disabled?: No and Yes

- apparently no, for colour schemes and language extensions are disabled, and I cannot come up with a simple method (without utilising any extensions) to assign different colours to char components of a ligature
- but a capital YES for this issue definitely emerges from the rendering engine of VSCode instead of some specific colour schemes/language extensions

**Comment by alexdima** [comment]
I have tried with the official JetBrains Mono font, but I cannot reproduce. I think this might have to do with the customized font at https://github.com/vbcpascal/CoqBrainsMono

**Comment by Krantz-XRF** [comment]
Yes, it sure is related to the customised font: the original `JetBrains Mono` uses `ChainedContextSubstitution` for ligatures, while the custom font uses plain old `Ligatures`. 

However, even if there is a workaround from the font side, I still think this reflects a bug in VSCode's rendering engine: it cannot always correctly handle `Ligatures`.

**Comment by alexdima** [comment]
@Krantz-XRF The editor component in VS Code delegates all font rendering to the browser engine, which in the case of VS Code is Chromium. I have tried yesterday to create a JSFiddle at https://jsfiddle.net/ in Chrome that loads the font and reproduces the problem, but the custom font did not come in a `.woff` format that could be straight-forward loaded.

IMHO the same problem will definitely reproduce in Chrome or any Chromium based browser.
