### ISSUE TITLE
Terminal is not working.

### ISSUE THREAD

**Issue by kaif-khan2000** [microsoft/vscode#121533]
Issue Type: <b>Bug</b>

When i press on new terinal. Its stuck. Its not showing the prompt

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.3.0-59-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3612QM CPU @ 2.10GHz (8 x 2403)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 1, 1|
|Memory (System)|7.48GB (0.30GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id ba7323ad-ae2c-4c2c-9f1f-db6504abdc63|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
android-emulator-launcher|343|0.9.0
vscode-django|bat|1.6.0
django|big|1.0.2
simple-react-snippets|bur|1.2.3
unity-code-snippets|cem|0.1.0
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
emulate|Die|1.4.0
unity-code-snippets|kle|1.3.0
csharp|ms-|1.23.11
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.0
awesome-flutter-snippets|Nas|2.0.4
java|red|0.77.0
LiveServer|rit|5.6.1
python|tht|0.2.3
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
eno|Wsc|2.3.53
unity-snippets|Ycl|0.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
openwsldoc:30282072
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30288035
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30286881

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo does the problem also happen after you run the command to reload with all extensions disabled?
