### ISSUE TITLE
HTML Semantic Highlight with <script> tag

### ISSUE THREAD

**Issue by oscard0m** [microsoft/vscode#121577]
Issue Type: <b>Bug</b>

Create an HTML file with a script tag, i.e.:

```html
<html>
  <title>Title</title>
  <lang>en</lang>
  <body></body>
  <script>
    const rootElement = document.createElement('div')
    rootElement.id = 'root'
    document.body.append(rootElement)

    const helloWorldElement = document.createElement('div')
    helloWorldElement.textContent = 'Hello World'
    rootElement.append(helloWorldElement)
  </script>
</html>
```

# Details
In VS Code (not Insiders it is properly highlighted)

### VS Code
![image](https://user-images.githubusercontent.com/2574275/115141435-749f2200-a03c-11eb-9f10-fa9c69c3b99f.png)

**VS Code Version:** 1.55.2
**Commit:** 3c4e3df9e89829dce27b7b5c24508306b151f30d
**Date:** 2021-04-13T09:36:32.643Z (5 days ago)
**Electron:** 11.3.0
**Chrome:** 87.0.4280.141
**Node.js:** 12.18.3
**V8:** 8.7.220.31-electron.0
**OS:** Darwin x64 20.3.0

### VS Code Insiders
![image](https://user-images.githubusercontent.com/2574275/115141448-87195b80-a03c-11eb-9aaa-6b20ee196702.png)

**Version:** 1.56.0-insider
**Commit:** ce791d27dc9889a392f4d29abefe9c53eb0b5129
**Date:** 2021-04-16T11:23:31.851Z (1 day ago)
**Electron:** 11.4.2
**Chrome:** 87.0.4280.141
**Node.js:** 12.18.3
**V8:** 8.7.220.31-electron.0
**OS:** Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id b54103d4-0a6f-412b-b7b6-40d67203fe86|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.3.0
vscode-markdownlint|Dav|0.40.3
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.20
prettier-vscode|esb|6.3.2
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.1
go|gol|0.24.1
vscode-gutter-preview|kis|0.27.1
vscode-github-actions|me-|3.0.1
vscode-language-babel|mgm|0.0.31
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.168.0
material-icon-theme|PKi|4.6.0
vscode-yaml|red|0.18.0
vscode-sort-json|ric|1.20.0
code-spell-checker|str|1.10.2
vscode-open-in-github|sys|1.15.0
ayu|tea|0.20.1
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
vscode-wakatime|Wak|5.0.1
vscode-webhint|web|1.5.11

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vsc_aacf:30263846
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820cf:30276953
vscoreces:30285483
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by kentcdodds** [comment]
I think it has something to do with the lack of semicolons 😅

**Comment by oscard0m** [comment]
> I think it has something to do with the lack of semicolons 😅

But... same code without semicolons is being highlighted correctly in VSCode not Insider right?

**Comment by kentcdodds** [comment]
I'm not sure. I've just noticed any time this is a problem, it's because of the semicolons 🤷‍♂️

**Comment by pyr0gan** [comment]
I believe it has to do with how the tokenizing works for syntax highlighting. Without the semicolons, it doesn't know to apply new rules for the following lines. It seems a similar issue happened with SublimeText and Babel a while back: https://github.com/babel/babel-sublime/issues/309

Just when you thought you were done with semicolons, hey? ;) This is the second time in a week for me, where trying to ditch semicolons caused an issue. To me this is minor, and I can live with improper syntax highlighting for a few minutes. It's an interesting technical question to dig into, though. Extra extra credit!

**Comment by aeschli** [comment]
I think the difference between the first (stable) and second (insiders) screenshot is that the second also has semantic highlighting:
![image](https://user-images.githubusercontent.com/6461412/115228226-cc5b8d00-a111-11eb-885e-12bb2ff94d29.png)


Can it be that you disabled semantic highlighting? Check the setting "editor.semanticHighlighting.enabled".
It's default value is `"configuredByTheme"`, that means each theme can define if it allows semantic highlighting, so you need to check with the theme or if it's overwritten in the settings

To see where the colors come from  put the cursor on `document` and run `Developer: Inspect Tokens and Scopes`

**Comment by oscard0m** [comment]
Thanks for the detailed answer @aeschli 

I checked my settings and there were no overwritten settings in my `Insiders` nor `Stable` VSCode for `editor.semanticHighlighting.enabled` option.

I tried to overwrite them in both to `true` to force semantic highlighting and still got the same result. Also, tried to apply a VSCode default color theme (Dark+) since it seems they use semantic highlighting [according to docs](https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting) and still the same result.

Here you can see a screenshot of Inspecting tokens and scopes using `Dark+`:
Stable
![image](https://user-images.githubusercontent.com/2574275/115360743-33d01600-a1c0-11eb-8de6-d8d2b3fbc663.png)

Insiders
![image](https://user-images.githubusercontent.com/2574275/115360816-477b7c80-a1c0-11eb-861f-04a5c66a73db.png)

According to the screenshots, looks like I'm still not getting the semantic highlighting enabled right?

---

@pyr0gan yes! with semicolon `;` it works but I'm curious why in VSCode stable I got a different coloring than in Insiders. I would like to:
- Get same behaviour in both
- To semantic highlight script code under `<script>` tag in an HTML document without `;` if possible, and try to PR a fix if not 💅🏽  .

**Comment by aeschli** [comment]
Can you check that the editor mode is `HTML` ? You can see this in the status bar. 
Maybe some extension has associated the `html file extension with a different language id.

**Comment by oscard0m** [comment]
> Can you check that the editor mode is `HTML` ? You can see this in the status bar.
> Maybe some extension has associated the `html file extension with a different language id.

It's getting `HTML` as mode:

![image](https://user-images.githubusercontent.com/2574275/117966012-b95c6700-b323-11eb-94a3-5768b8a1f29c.png)

**Comment by Rahulkhinchi03** [comment]
no, it is .c only

**Comment by oscard0m** [comment]
> Hey @aeschli, this issue might need further attention.
> 
> @oscard0m, you can help us out by closing this issue if the problem no longer exists, or adding more information.

I do not know what information to add. Since it's not a major issue I can understand this is not a priority and we can close the issue if you want :)

**Comment by kentcdodds** [comment]
To be clear, the issue does still exist

**Comment by aeschli** [comment]
Can you put the cursor in the middle of the word `document` and run `Developer: Inspect Tokens and Scopes`
The top line should say `document` and you should see the semantic token type info.

![image](https://user-images.githubusercontent.com/6461412/129788487-09f61715-679a-45fc-bbeb-089caf77d780.png)

**Comment by kentcdodds** [comment]
![image](https://user-images.githubusercontent.com/1500684/129803693-ba0a65d7-ce21-4167-a59d-b1b702820216.png)

The `foreground` and `textmate scopes` values are different. And mine doesn't show a `semantic token type`.

**Comment by aeschli** [comment]
You have a different code sample. Let's focus on the snippet given in the description.

**Comment by kentcdodds** [comment]
My apologies. Here:

![image](https://user-images.githubusercontent.com/1500684/129922122-ba2cd7fe-3fcb-4cb6-a2c7-4fef9e523832.png)

Looks like it's exactly the same as my other screenshot.

What I find interesting is when I put my cursor on the closing `</script>` html tag or even the `</html>`, it incorrectly identifies language as "JavaScript"

![image](https://user-images.githubusercontent.com/1500684/129922483-2998bae0-4203-40cb-84ed-0508471a0981.png)

However, if I add a semicolon, it correctly identifies it as HTML:

![image](https://user-images.githubusercontent.com/1500684/129922505-024934a2-d12e-4758-9999-ad9e964b0179.png)

I would expect it to be able to identify it as the correct language regardless of the presence of the semicolon.

**Comment by aeschli** [comment]
It's strange that you get slightly different scopes. Your language mode is HTML and you have all extensions disabled?
Also, can you try with built-in Dark theme. Whether you get semantic highlighting depend on the theme. The theme can allow/disallow semantic highlighting.

The semicolon issue is a known problem with our embedded grammar.

**Comment by kentcdodds** [comment]
Ah, yeah, looks like one of my extensions is causing the scope difference!

![image](https://user-images.githubusercontent.com/1500684/129976931-c4ca8e25-fefc-489f-a833-c09592c59ff4.png)

![image](https://user-images.githubusercontent.com/1500684/129976935-337bd9ec-f71d-4045-946b-b636130f72ed.png)

I guess I'll have to figure out which extension is causing this and uninstall it/open an issue on it 😅

**Comment by oscard0m** [comment]
Not happening to me anymore (a few VSCode Insiders version above). I think we can close this issue @kentcdodds ?

```
Version: 1.60.0-insider
Commit: 89bbd372f459ce72e9c0b60eb3b26b924f64f62d
Date: 2021-08-20T17:51:40.521Z (2 days ago)
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

**Comment by kentcdodds** [comment]
Yup, I found the plugin that's causing this issue for me: https://github.com/michaelgmcd/vscode-language-babel

I'll open an issue there.
