### ISSUE TITLE
Native Notebooks - Run shortcut is hard coded

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121558]
Native Notebooks currently displays "Ctrl + Alt + Enter" to run. 

![image](https://user-images.githubusercontent.com/19276747/115124973-2aee0300-9f7a-11eb-82a0-5cc9c6725e30.png)

The Jupyter extension shortcut for run is Ctrl + Enter. I commented on PR a while back requesting if instead of having this shortcut be hard coded into the cell status bar, if it could be dynamic and display the shortcut of the extension if one is available but I cannot seem to find it... Could this be done so we can expose the correct shortcut for run for our extension?

**Comment by rebornix** [comment]
yup, already fixed in Insiders.
