### ISSUE TITLE
Custom trees items with codicons with `~spin` in look bad

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121518]
![spin](https://user-images.githubusercontent.com/641685/115088278-d85f0900-9edd-11eb-85c8-c489ea7acaf6.gif)

**Comment by alexr00** [comment]
@misolori in case you know exactly how to fix this already :)

**Comment by misolori** [comment]
I think @joaomoreno mentioned that the dimensions are not square which is causing this. I believe the recommendation was to use the tree api for loading items that handles this? Ideally we'd want to make the codicons the same dimensions but i'm not familiar enough with the tree code to update this. The status bar items handle this fine btw.

**Comment by misolori** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/117859 which was fixed this week:

>Made a fix that adds padding to the loading spinning icon to make it square and offsets it via margin (not a pretty fix but haven't found an alternate solution):
>
><img width="400" src="https://user-images.githubusercontent.com/35271042/116902980-aee9f100-abf0-11eb-9311-53acbf280dba.gif">
>
><img width="400" src="https://user-images.githubusercontent.com/35271042/116902954-a7c2e300-abf0-11eb-94c4-496d24407bf5.png">
