### ISSUE TITLE
Hide explorer tab when user inside extensions

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#12157]
don't show explorer file tab when user inside extensions

<img width="1119" alt="screen shot 2016-09-16 at 7 31 38 pm" src="https://cloud.githubusercontent.com/assets/1549069/18590698/180d81f0-7c45-11e6-8f39-3b309c20e821.png">

**Comment by bpasero** [comment]
@joaomoreno fyi

**Comment by joaomoreno** [comment]
Closing as designed.
