### ISSUE TITLE
Active tab after copying a file

### ISSUE THREAD

**Issue by ojoven** [microsoft/vscode#121594]
Issue Type: <b>Feature Request</b>

Previously when copy pasting a new file it would get open and become the active one; it had a lot of sense cause after copy pasting a file if you're going to edit one, the most probable  file to edit would be the new / copypasted one, not the original.

I wasn't sure if you already had changed this and I saw that you recently did; it's making me update things in the file I think I just copy pasted but everytime I realize after some time that the file that I'm editing is the original one.
https://github.com/microsoft/vscode/issues/117967

I hope I'm not the only one and to revert to the previous approach; or, if possible, to have it as a setting. In any case I'm super grateful for all the work you're doing to this IDE, that is magnificent. Just wanted you to be aware that this is happening to me and I believe it'll happen to many others as well.

Thanks.

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.4.0-72-generic

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/120882
We might introduce a setting
Thanks for feedback
