### ISSUE TITLE
More Actions ... does not have Disable All Extensions / Enable All Extensions

### ISSUE THREAD

**Issue by mrmsbarnes** [microsoft/vscode#121596]
This page
https://code.visualstudio.com/docs/editor/extension-gallery
says "If you want to quickly disable all installed extensions, there is a Disable All Installed Extensions command in the Command Palette and More Actions (...) dropdown menu." and "There is also an Enable All Extensions command in the More Actions (...) dropdown menu".
This is not true about More Actions when I am editing a .txt file on:
Version: 1.56.0-insider (system setup)
Commit: ce791d27dc9889a392f4d29abefe9c53eb0b5129
Date: 2021-04-16T11:25:09.662Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sandy081** [comment]
I have it here

![image](https://user-images.githubusercontent.com/10746682/115253504-bad3ae80-a12c-11eb-9bfb-435331c0e9d5.png)

Can you please let me know where you are looking at?

**Comment by mrmsbarnes** [comment]
I didn't know you had to View > Extensions to see this menu.  I am closing.  Thanks, Sandeep.
