### ISSUE TITLE
Floating button doesn't use all button colors

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121512]
1. `settings.json`

```js
"workbench.colorCustomizations": {
	"button.background": "#ffee00",
	"button.foreground": "#000",
	"button.border": "#ffbb00",
	"button.hoverBackground": "#ffbb00",
}
```

2. Open `launch.json`

Floating button <kbd>**Add Configuration...**</kbd> uses `button.background` & `button.foreground` and ignores `button.border` & `button.hoverBackground`.

**Comment by AlexandroGonSan** [comment]
@stevencl @bgashler1 Can I please get your opinion on this proposal?

**Comment by isidorn** [comment]
I think this is simply not implemented.
Code pointer and I think we would be open to a concise PR which fixes this
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/codeeditor.ts#L134
