### ISSUE TITLE
Add file icon in file editors section

### ISSUE THREAD

**Issue by uxitten** [Microsoft/vscode#12153]
Add File Icon in File Editors Section
for good sense (UX)

<img width="443" alt="screen shot 2016-09-16 at 7 15 15 pm" src="https://cloud.githubusercontent.com/assets/1549069/18590033/8d4559b4-7c42-11e6-99ad-36696839d0a9.png">

**Comment by bpasero** [comment]
See https://github.com/Microsoft/vscode/issues/11751
