### ISSUE TITLE
VSCode repeatedly prompts to install extensions on remote host (SSH)

### ISSUE THREAD

**Issue by CaninoDev** [microsoft/vscode#121563]
- VS Code Version: 1.55.2 (Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d)
- OS Version: 11.2.3

Steps to Reproduce:

1. Start an new instance of VSCode. 
2. Click on lower left corner (the codicon) and open a remote-ssh session (remote in this instance runs Manjaro (latest version).
3. Get prompted to install each missing extensions on remote "Would you like to install and synchronize '<extension>' extension across your devices?"
4. Confirm installation for each.
5. Completely close/quit and start a new remote ssh with same host. 
6. Get prompted again.
7. Repeat ad verbatim. 
8. Or just simply cancel and not get prompted again during current session only to be prompted again at the next session.

Does this issue occur when all extensions are disabled?: No (since all extensions are disabled, this include remote ssh sessions.

**Comment by sandy081** [comment]
Seems like some extension is auto installing extensions - can you please disable your installed extensions and try again ?

**Comment by CaninoDev** [comment]
I did that. But in so doing, no extensions gets prompts to get installed understandably.

**Comment by sandy081** [comment]
So you have not seen any prompts after disabling installed extensions (except Remote SSH extension) ?

**Comment by CaninoDev** [comment]
I ran `code --disable-extensions`, then attempted to just enable  `Remote SSH`. It prompts to restart that instance of VSCode. Upon restart, the extensions remained disabled but still prompts me to reload that instance of VSCode, ad infinitum..

**Comment by sandy081** [comment]
Ok, sorry about that. It seems `--disable-extensions` is not working well to just try with one extension. Can you please use Extensions view to disable all installed extensions except Remote SSH?

**Comment by CaninoDev** [comment]
Is there a way to batch disable them (I have quite a few.) Also, should I also disable local extensions or just the remote ones?

**Comment by sandy081** [comment]
You can use the action - disable all installed extensions after that enable the remote ssh extension. I would recommend to disable all local and remote ones.

**Comment by CaninoDev** [comment]
@sandy081 Ultimately, I deleted all of the local preferences/extensions (MacOS) and started a-fresh. I installed each extension as needed when using Remote-SSH and now do not encounter the above problem. I suspect there was a corruption of a config some where. 

Anyhow, thanks for your help and time. I am going to close this issue.
