### ISSUE TITLE
Terminal section has new section which consumes space.

### ISSUE THREAD

**Issue by nippyin** [microsoft/vscode#121566]
Issue Type: <b>Performance Issue</b>

Terminal section has new section to left which gives all terminals active and option to add new or rename. How do i get rid of it?

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:23:31.851Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	   131	 51337	code-insiders main
    0	    49	 51345	   gpu-process
    0	    16	 51347	   utility
    0	    82	 51371	   shared-process
    0	    16	 51374	     ptyHost
    0	     0	 52315	       /bin/zsh -l
    0	     0	 52342	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   246	 52286	   window (Untitled-1)
    1	   131	 52287	     extensionHost
    0	    49	 52340	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
azurepolicyextension|Azu|0.1.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
ansible-vault|dho|0.1.3
xml|Dot|2.5.1
LogFileHighlighter|emi|2.11.0
opensslutils|ffa|1.1.1
gc-excelviewer|Gra|3.0.41
ansible|haa|0.2.8
terraform|has|2.10.0
vscode-drawio|hed|1.4.0
rest-client|hum|0.24.5
rainbow-csv|mec|1.8.1
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.3.0
vscode-docker|ms-|1.12.1
vscode-dotnet-runtime|ms-|1.0.0
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.6.755784270
remote-containers|ms-|0.168.0
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
remote-wsl|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell-preview|ms-|2021.4.1
azurerm-vscode-tools|msa|0.15.1
material-icon-theme|PKi|4.6.0
code-settings-sync|Sha|3.4.3
vscode-autohide|sir|1.0.7
best-light-themes-pack|the|1.0.2
material-theme|zhu|3.10.13

(2 theme extensions excluded)

</details>

**Comment by nippyin** [comment]
[
![Screen Shot 2021-04-17 at 11 52 41 PM](https://user-images.githubusercontent.com/41337248/115133692-13ddfe00-9fd8-11eb-8d3f-ef2f6a794fb9.jpg)
](url)

**Comment by gjsjohnmurray** [comment]
This is where the upcoming tabs feature renders. It's an alternative to the dropdown in the panel titlebar (observe that's absent in the screenshot above), and it's turned on by default in Insiders.

That vertical line is draggable, so you can make the tabs take up less space.

Switch them off off in Settings:

`"terminal.integrated.showTabs": false`

**Comment by nippyin** [comment]
Thank you very much, I missed this settings when I was checking in config.
