### ISSUE TITLE
Majority of extensions not functional after reinstalling the operating system and text editor

### ISSUE THREAD

**Issue by GavHern** [microsoft/vscode#121559]
I've just had to reinstall Windows 10 on my computer and I've reinstalled VS Code to the latest version (1.55.2). The majority of my extensions are no longer functional and are throwing errors in some cases. Here are some examples:

vscode icons
![image](https://user-images.githubusercontent.com/47736824/115125147-283fdd80-9f7b-11eb-8950-3917537565e4.png)

vim for vscode
![image](https://user-images.githubusercontent.com/47736824/115125163-3f7ecb00-9f7b-11eb-93e1-96a2a2a48403.png)

discord rich presence
![image](https://user-images.githubusercontent.com/47736824/115125221-77860e00-9f7b-11eb-9466-d04e2cbd93d9.png)

I have tried reinstalling the extensions and changing their versions, as well as reinstalling the editor several times with no luck. I have also made sure that all the extensions are enabled properly. A few extensions work fine (such as Auto Rename Tag, Better Comments, and any editor theme), but most are not functioning properly...

I think its also worth mentioning that my windows user path changed when I reinstalled windows. for example `C:/users/Bob` to `C:\users\John` could have been the issue?

**Comment by GavHern** [comment]
I have resolved this issue by removing `Code` from my `appdata` folder and removing the `.vscode` folder from my User folder. These folders were not removed by the uninstaller.

**Comment by alexdima** [comment]
The uninstaller does not user data such as settings, keybindings, caches, installed extensions. Not sure, @joaomoreno do you have a feature request for that somewhere?

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/66837
