### ISSUE TITLE
All hotkey actions must be duplicated in the interface.

### ISSUE THREAD

**Issue by Sn-a-ke** [microsoft/vscode#121532]
Issue Type: <b>Feature Request</b>

hotkeys are archaic and should not be used as the only access mechanism for default program functions.
The average user uses, to varying degrees, a huge number of different programs, remembering the key combinations from all of them is crazy.
this also applies to plugin hotkeys.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by gjsjohnmurray** [comment]
Have you seen the Command Palette? Hotkeys trigger commands, and many commands appear in the palette. Those that don't are typically ones that need context, in which case they are surfaced on context menus or action buttons.

**Comment by alexdima** [comment]
As @gjsjohnmurray mentions, actions can also be invoked via the mouse (e.g. via the command palette or via the menus), so there is no need to learn all the keybindings.
