### ISSUE TITLE
[scss] `Ctrl+Click` is not working when file name has a suffix with a dot

### ISSUE THREAD

**Issue by ihodex** [microsoft/vscode#121586]
- VS Code Version: 1.55.2
- OS Version: Windows 10 x64 10.0.19042

Steps to Reproduce:

1. Create 3 empty files: `index.scss`, `theme.scss` and `component.theme.scss`
2. Paste next snippet to `index.scss`
   ```
   @use './theme' as *;
   @import './theme';
   
   @use './component.theme' as *;
   @import './component.theme';
   ```
3. Try open `./component.theme` via `Ctrl+Click`
4. Note, `Ctrl+Click` on `./theme` is working

**Comment by tymsai** [comment]
yeah I also got a error of a non existing file;
The problem is in the naming of the file
use the below given code it's working : 

@use './theme' as *;
@import './theme';

@use './component.theme.scss' as *;
@import './component.theme';

**Comment by ihodex** [comment]
@tymsai Thanks, yes, I saw that it works with `.scss`, but it should also work without it, like other examples

**Comment by tymsai** [comment]
> @tymsai Thanks, yes, I saw that it works with `.scss`, but it should also work without it, like other examples

as I said there should be only one dot " . " in the file name.

**Comment by aeschli** [comment]
If someone is interested in looking into i:. The logic to resolve the file name is in https://github.com/microsoft/vscode-css-languageservice/blob/3ab3d91a81bcebd9e8566e2cf7cad454188e8324/src/services/scssNavigation.ts#L27

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode-css-languageservice/pull/241 fixing this
