### ISSUE TITLE
restore zoom

### ISSUE THREAD

**Issue by mcanepa** [microsoft/vscode#121587]
Right now, I have this setting `"editor.mouseWheelZoom": true`, which enables me to zoom only the editor and not the explorer, but there isn't a way to restore the zoom unless I go to the command palette and type `>Editor Font Zoom Reset`

Since in order to manipulate the zoom what I do is `CTRL + MOUSEWHEELMOVE`,  I would like to suggest the use of `CTRL + MOUSEWHEELCLICK` to restore it

**Comment by tymsai** [comment]
In my VSCode 32bit version Win7 Ultimate,
I use   "  ctrl + -  " for zoomout and "  ctrl + + " for zooming in;
I think editing in json only effects the editor , i.e. whatever you type in json it only applies for editor part.

**Comment by mcanepa** [comment]
@tymsai what you are doing with those keybindings is zooming in/out the whole window (editor, explorer, icons, tabs, etc) and that zoom can be reset by doing `CTRL + 0`

There's an option in settings, `Editor: Mouse Wheel Zoom`. I you check that (`"editor.mouseWheelZoom": true`) you can zoom only the editor without afecting the rest of the window.

But there isn't a shortcut to reset that zoom, hence my proposal

**Comment by hediet** [comment]
I think #3130 could solve this.

**Comment by alexdima** [comment]
Let's track in #3130
