### ISSUE TITLE
Built-in extension link to release notes doesn't work

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121507]
Issue Type: <b>Bug</b>

1. Open built-in extension `@builtin npm` changelog (any built-in extension, it looks like)
2. The link is not working

![Screenshot (473)](https://user-images.githubusercontent.com/9638156/115082752-0f99de00-9f0f-11eb-9aa0-b7fc243b2035.png)

VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.662Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Assigning to @mjbvz as this is rendered as markdown editor.
