### ISSUE TITLE
White version of the debug-restart icon for usage in extensions

### ISSUE THREAD

**Issue by qcz** [microsoft/vscode#121534]
I've created an [extension](https://marketplace.visualstudio.com/items?itemName=qcz.restart-ts-server-button) which puts a restart button on the status bar. The best icon from the [procuct icons](https://code.visualstudio.com/api/references/icons-in-labels) is `debug-restart` for this, however it is green by default, and I see no option to change that for a status bar item, so it stands out:
![2021-04-16_18-38-21](https://user-images.githubusercontent.com/304384/115104642-2d406500-9f5a-11eb-9eb8-c5b6648da284.png)

If I set the `statusBarItem.color` property, the icon is still green.

Please add a white version of this icon , or example with the name `restart`.

**Comment by gjsjohnmurray** [comment]
/duplicate of #120429

The issue is not that the debug codicons contain colour (they can't as they are font glyphs), but that CSS styling gets applied to them everywhere.

I submitted a PR but it hasn't yet been approved.

**Comment by qcz** [comment]
@gjsjohnmurray Nice, thanks!
