### ISSUE TITLE
Hide the terminal profiles dropdown. It wastes space in column mode

### ISSUE THREAD

**Issue by gotofritz** [microsoft/vscode#121572]
Since the latest Insider Release VS Code automatically displays a dropdown with the terminal profiles. If the Terminal is in column mode, that wastes almost half of the screen space. Please let us remove it. 
I don't need terminal profiles. Never asked for it, will never use it. 
Please don't ruin the UI for the sake of the few users who may need the feature. Thanks

**Comment by Taswen** [comment]
+1

**Comment by karlhorky** [comment]
@gotofritz can you provide a screenshot of the suboptimal organization of the UI (eg. in column mode, like you mention)?

**Comment by gotofritz** [comment]
Sure, here it is

![vscode-bug](https://user-images.githubusercontent.com/604900/115141206-571d8880-a03b-11eb-8926-1363a37e6324.png)

**Comment by Taswen** [comment]
I found an option to turn it off. 
![image](https://user-images.githubusercontent.com/30777327/115151323-f758c900-a09e-11eb-96c5-3a803d330f1a.png)

**Comment by Tyriar** [comment]
This is tabs not profiles, which is the second most voted feature request in the whole project so there were many who did ask for it.

It is still a work in progress though, right now you can drag the sash to the right to get a collapsed view, but you can also turn off tabs all together to go back to the dropdown via that setting.

I'll keep this open until we improve the panel on the side mode though, the thinking is to show the narrow view by default to minimize the amount of space used.

**Comment by gotofritz** [comment]
When you click on the "v"  it says "Select profile ..." and there is no mention of 'tabs' anywhere.... 🤷  
OK, fine, tabs then. 

> the second most voted feature request in the whole project

My understanding was that 'tabs' would replace the awkward pulldown menu next to '... / Debug Console / Terminal' and basically work the same as it does for files - in which case I'm also for it. But your execution does nothing of the sort, it _adds_ a space-wasting menu... so now I have a menu that says 'bash' above the terminal and another one that also says 'bash' on the left of it .... aaaargghh ....

> the thinking is to show the narrow view by default

But why? Why waste screen estate like that for a column that has useful information for 10% of its height and the rest is wasted? Have you considered instead a second toolbar, below the one with 'problems / output / ... / terminal console' with your tabs? That would make the best use of the screen space (many of us use laptops!) and would fit in with the existing way tabs are shown for files

**Comment by gotofritz** [comment]
Oh well done @Taswen.. I didn't realise this feature was called "Tabs", I was looking for "profiles" in the preferences! That solves my issue thanks!

**Comment by zzjin** [comment]
Maybe we can have settings to move those "Tabs" set to sub-top or bottom when in column mode?

**Comment by Tyriar** [comment]
> so now I have a menu that says 'bash' above the terminal and another one that also says 'bash' on the left of it .... aaaargghh

The dropdown will go away when you have tabs showing as of today's insiders.

FYI this is the narrow view, you can resize the list to get it:

![image](https://user-images.githubusercontent.com/2193314/115204765-b4522200-a0ad-11eb-8f5a-279c3cd8ed5a.png)

> Maybe we can have settings to move those "Tabs" set to sub-top or bottom when in column mode?

It's a choice between the narrow view or the dropdown when the terminal is on the side, unless we invest a bunch of effort doing a horizontal design. We may end up doing that but probably not this month.

**Comment by meganrogge** [comment]
Now by default when you move the panel to the side, the tabs view is minimized. If you still don't want to see it, right click and select `Hide Tabs`

**Comment by gotofritz** [comment]
Great, just got the update and it works very well. Thanks for you efforts @meganrogge @Tyriar and everyone else involved!
