### ISSUE TITLE
Bind numpad_add and numpad_subtract as alternates for zoom commands

### ISSUE THREAD

**Issue by tkelman** [Microsoft/vscode#12152]
- VSCode Version: 1.6.0-insider
  ![vscodeversion](https://cloud.githubusercontent.com/assets/5934628/18589550/1a05ef7a-7be0-11e6-9bdf-5b21f303947b.png)
- OS Version: Windows 10 Insider build 14915

Steps to Reproduce:
1. Using a keyboard that has a keypad (large laptop in my case), try zooming with ctrl and the keypad plus/minus. This works in Firefox and many other applications as an alternative to the -/= keys between 0 and backspace on a US keyboard.
2. I think this should be doable with custom keybindings ala https://code.visualstudio.com/docs/customization/keybindings but I haven't quite managed to get that working. This might be a standard and useful enough binding for these keys that it would be worth making default though? Opinions?

edit: #983 is somewhat related

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
