### ISSUE TITLE
Add installed extension version after installing from vsix

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121548]
After installing extension from `.vsix` file there's a notification:

> Completed installing Contributions extension from VSIX. Please reload Visual Studio Code to enable it.

It would be great to know the version at the same time:

> Completed installing Contributions [**0.0.3**] extension from VSIX. Please reload Visual Studio Code to enable it.

**Comment by sandy081** [comment]
@usernamehw why is it necessary to know the version when installing from VSIX? You can see it in extensions view right?

**Comment by usernamehw** [comment]
This notification shows in different cases, 2 of which:

- Context menu in explorer (can misclick)
- Executing from extension api: `await commands.executeCommand('workbench.extensions.command.installFromVSIX', [vscode.Uri.file(vsixPath)])` (can choose wrong extension version)

Maybe it also shows after dragging `.vsix` file to install? Can drag the wrong version of extension.

**Comment by sandy081** [comment]
I see but it is not very convincing.
