### ISSUE TITLE
Markdown preview of table with inline code with pipes

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#121547]
```md
| 1     | 2     |
| ----- | ----- |
| `||3` | `4||` |
```

| 1     | 2     |
| ----- | ----- |
| `||3` | `4||` |

GitHub doesn't render them correctly either...

**Comment by usernamehw** [comment]
Example of it working: https://jbt.github.io/markdown-editor/#q1EwVACBGgUjCM1Vo6ALAgpwGiiSUFNjnAAUSTCpqQHSAA==

**Comment by mjbvz** [comment]
Also not rendered by markdown-it, which the built-in markdown extension uses: https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%201%20%20%20%20%20%7C%202%20%20%20%20%20%7C%5Cn%7C%20-----%20%7C%20-----%20%7C%5Cn%7C%20%60%7C%7C3%60%20%7C%20%604%7C%7C%60%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D

Please file this issue upstream [against markdown-it](https://github.com/markdown-it/markdown-it)
