### ISSUE TITLE
cannot open folders on ssh devices

### ISSUE THREAD

**Issue by JohnJim0816** [microsoft/vscode#121537]
I use the ssh extensions on MacBookPro(catalina 10.15.7) to connnect the server, when I move the local files onto server through vscode, then I cannot open the folders on the server, every time it jumps to open the folders on the local computer before I restart the vscode. I think it is a bug or anyone could help me?

**Comment by roblourens** [comment]
> every time it jumps to open the folders on the local computer before I restart the vscod

I don't understand the problem, please explain it step-by-step in detail

**Comment by JohnJim0816** [comment]
ah, I think I can solve it now ,thx.
