### ISSUE TITLE
Cursor Style still in Block mode

### ISSUE THREAD

**Issue by EstherKpetemey** [microsoft/vscode#121599]
Issue Type: <b>Bug</b>

Even after I changed the settings from block to line-thin, my cursor is still in block mode. That's simply crazy.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.8.0-49-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 3880)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.33GB (5.48GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 8dc833eb-8ca4-4951-8feb-4ccb26d641f2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
overtype|ada|0.2.0
project-manager|ale|12.1.0
flutter-snippets|ale|2.0.0
troff|ban|1.0.22
path-intellisense|chr|2.3.0
vscode-postgres|cko|1.1.17
gitignore|cod|0.6.0
bracket-pair-colorizer|Coe|1.0.61
flask-snippets|cst|0.1.1
c-cpp-compile-run|dan|1.0.14
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
vscode-eslint|dba|2.1.20
jekyll-run|Ded|1.5.0
git-extension-pack|don|0.1.3
githistory|don|0.6.16
javadebugger|don|0.1.5
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.1
prettier-vscode|esb|6.3.2
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
vscode-jekyll-snippets|gin|0.9.3
beautify|Hoo|1.5.0
icon-fonts|idl|2.4.0
vue|jcb|0.1.5
better-line-select|kai|1.1.1
vsc-python-indent|Kev|1.14.0
kite|kit|0.142.0
Kotlin|mat|1.7.1
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
python|ms-|2021.3.680753044
jupyter|ms-|2021.5.745244803
remote-wsl|ms-|0.54.6
azure-account|ms-|0.9.8
cpptools|ms-|1.3.0
debugger-for-chrome|msj|4.12.12
sqltools|mtx|0.23.0
vuejs-extension-pack|mub|1.2.1
color-highlight|nau|2.3.0
live-server-preview|neg|0.1.4
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
vscode-css-peek|pra|4.1.3
java|red|0.77.0
vscode-yaml|red|0.18.0
prettier-now|rem|1.4.9
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.0
code-spell-checker|str|1.10.2
python|tht|0.2.3
vscode-status-bar-format-toggle|tom|2.0.0
pygame-snippets|tus|0.0.1
tensorflow-snippets|vah|0.3.3
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.13.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
vscode-icons|vsc|11.4.0
vim|vsc|1.20.0
JavaScriptSnippets|xab|1.8.0
vscode-open-in-github|ziy|1.3.6

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by alexdima** [comment]
The vim extension is dynamically changing the cursor type based on the vim mode. You can disable the vim extension if you do not want vim input.

**Comment by EstherKpetemey** [comment]
Thank you very much. This resolves my issue.
