### ISSUE TITLE
Put a title in prompt text for each viewlet focusabled, thike the language selector.

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#121650]
I want title for this viewlet.
![image](https://user-images.githubusercontent.com/38570195/115259996-5bf84000-a100-11eb-840d-df1c1f1fddbb.png)

**Comment by gjsjohnmurray** [comment]
I don't understand what you mean. And your screenshot is the same one that you posted at #121649

**Comment by AlexandroGonSan** [comment]
Oh! Sorry! I hope you understand, I thank you for your efforts.

[en][Bing/me Translate]
In this open viewlet (popup) by pressing the green button in the lower left corner according to the image for Open a Remote Window. It should have a title like Open a Remote Window in viewlet and in window.

[pt-br][Original]
Nessa viewlet (popup) aberto ao pressionar o botão verde no canto inferior esquerdo de acordo com a imagem para Open a Remote Window. Devia ter um title like Open a Remote Window na viewlet and na window.

![simplescreenrecorder-2021-04-19_12 42 51](https://user-images.githubusercontent.com/38570195/115273285-59e8ae00-a10d-11eb-9b3b-ff5c4eb8b434.gif)

**Comment by gjsjohnmurray** [comment]
pinging @aeschli because #121180 also relates to this quickpick. Personally I don't think it needs a title. Perhaps some prompt text, thike the language selector has?

**Comment by AlexandroGonSan** [comment]
> pinging @aeschli because #121180 also relates to this quickpick. Personally I don't think it needs a title. Perhaps some prompt text, thike the language selector has?

Your idea is interesting! We can get on with it!

A sua ideia é interessante! Podemos prosseguir com ela!

**Comment by aeschli** [comment]
No sure what the title would be to be helpful. `Select a remote window command.` ?
Also, the regular command palette also has no title.

**Comment by gjsjohnmurray** [comment]
I agree with @aeschli . When the Command Palette quickpick appears it doesn't tell me to "Enter a command", probably because it assumes I know that I invoked it for the purpose of doing exactly that.

**Comment by AlexandroGonSan** [comment]
> No sure what the title would be to be helpful. `Select a remote window command.` ?
> Also, the regular command palette also has no title.

[pt-br][Original]
O título deve pegar o atributo title do botão que foi clicado antes de abrir e deve-se deixar implementado para no futuro permitir encapsular esse título como em uma concatenação.

Se o título na barra de status já existir, faz-se um join dos títulos com '>', caso o resultado do título final vá quebrar o layout então deve-se mostrar o primeiro e o último título separados por " > ... > ".

Esse é um recurso de acessibilidade.

[en][Bing Translate]
The title must take the title attribute of the button that was clicked before opening, and it must be left implemented to allow you to encapsulate that title as in a concatenation.

If the title in the status bar already exists, you join the titles with '>', if the final title result is going to break the layout then you must show the first and last heading separated by " > ... > ".

This is an accessibility feature.

**Comment by AlexandroGonSan** [comment]
I need than Microsoft implements.
