### ISSUE TITLE
Cannot create launch.json due to some errors in extensions

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#121676]
Issue Type: <b>Bug</b>

I have go lang extension installed purely for syntax highlighting. When I click "Create launch.json" I get error that `gopls` is not installed and nothing happens

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.11.13-arch1-1
![Peek 2021-04-19 23-55](https://user-images.githubusercontent.com/7345761/115302161-cba31500-a16a-11eb-8587-0cc704a15665.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 4036)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.30GB (21.53GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 98f069a3-5d5e-458a-99b1-94af3373729b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
language-gas-x86|bas|0.0.2
better-toml|bun|0.3.2
ccls|ccl|0.1.29
vscode-eslint|dba|2.1.20
vscode-dash|dee|2.4.0
java-decompiler|dgi|0.0.2
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
file-icons|fil|1.0.29
code-runner|for|0.11.3
shell-format|fox|7.1.0
kotlin|fwc|0.2.22
godot-tools|gee|1.1.2
go|gol|0.24.1
haskell|has|1.2.0
perl-outline|hit|0.0.7
hoogle-vscode|jca|0.0.7
vscode-peacock|joh|3.9.1
svn-scm|joh|2.13.5
language-haskell|jus|3.4.0
Lua|key|0.0.9
saltstack|kor|0.0.8
bash-ide-vscode|mad|1.11.0
Lisp|mat|0.1.11
vscode-docker|ms-|1.12.1
vscode-language-pack-ru|MS-|1.55.2
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.1
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
cpptools|ms-|1.3.0
vsliveshare|ms-|1.0.4131
gradle-language|nac|0.2.3
vscode-subword-navigation|ow|1.2.0
phoityne-vscode|pho|0.0.26
java|red|0.77.0
vscode-commons|red|0.0.4
vscode-xml|red|0.16.0
vscode-yaml|red|0.18.0
bash-debug|rog|0.3.9
rust|rus|0.7.8
vscode-hexdump|sle|1.8.1
shellcheck|tim|0.14.0
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
debug|web|0.25.0
jinja|who|0.0.8
clang-format|xav|1.9.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vscnewfiletext:30288035
vshan820:30276952
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by Yanpas** [comment]
Go extension here is just an example how I've extension breaks UI. The issue is that I can't create launch json

**Comment by weinand** [comment]
@isidorn VS Code should protect itself against crashing extensions preventing the launch.json creation from succeeding.

**Comment by isidorn** [comment]
Makes sense. However I have no immediate plans to fix this, assigning to backlog for now.
Disable invalid extensions in the meantime
