### ISSUE TITLE
Notebook diff shows false information

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121622]
* (I have changed the GHI notebook to not persist editable anymore)
* run a GHI notebook
* open in notebook diff -> no change, esp editable is still there
* open in text diff -> changes are shows correctly

<img width="1377" alt="Screenshot 2021-04-19 at 09 17 22" src="https://user-images.githubusercontent.com/1794099/115196349-192e6c00-a0f0-11eb-9453-92a726e86a5a.png">

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/b7d27a057d1b8172f308a3a46e0cf0e2eef2bcf9

**Comment by rebornix** [comment]
This is actually a different issue. The left notebook had `editable` as persistent but the right side have the `editable` as transient. Our diff editor currently doesn't handle this case.

**Comment by rebornix** [comment]
@claudiaregio I lableled https://github.com/microsoft/vscode/issues/133554 as nb-golden

**Comment by claudiaregio** [comment]
@rebornix Thank you! good catch, missed it since it was closed

**Comment by DonJayamanne** [comment]
>  The left notebook had editable as persistent but the right side have the editable as transient. Our diff editor currently doesn't handle this case.

Closing this as not planned.
This happened as some of the data related to notebook serialization changed and this is not something that happens on a day to day basis.
Also given the fact that no one else reported this for over 3 years, its safe to close this.
