### ISSUE TITLE
Toggling terminal tabs position creates wide sidebar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#121653]
![CleanShot 2021-04-19 at 08 24 28](https://user-images.githubusercontent.com/35271042/115261924-e8970400-a0e8-11eb-89a6-d36c03c08d27.gif)

When going from left => right for the terminal tabs position, the sidebar (not sure what else to call this) that has the list of tabs gets into a very wide state and the terminal window gets smaller. I assume they are inheriting the previous item's width or close to, we should match the sidebar when it is toggled and persist the current size.

**Comment by meganrogge** [comment]
Fixed yesterday
