### ISSUE TITLE
Open a C file

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [microsoft/vscode#121614]
vscode Open a C file，
![Snipaste_2021-04-19_11-44-15](https://user-images.githubusercontent.com/57666259/115178967-e5aa0c80-a104-11eb-9284-7b185a859f53.png)
I want to know how to open the.c file without messy code
![Snipaste_2021-04-19_11-48-03](https://user-images.githubusercontent.com/57666259/115179080-1e49e600-a105-11eb-8c9b-d30a87031d93.png)

**Comment by IllusionMH** [comment]
/needsMoreInfo

What is file encoding? Have you tried to reopen with different encodings as described in https://code.visualstudio.com/docs/editor/codebasics#_file-encoding-support ?

Does it produce expected content in different editors?
