### ISSUE TITLE
VSCode crashed on startup.

### ISSUE THREAD

**Issue by tymsai** [microsoft/vscode#121617]
![github](https://user-images.githubusercontent.com/76956612/115190742-20f90b00-a106-11eb-9e97-8aa3c94042dd.PNG)
![dfg](https://user-images.githubusercontent.com/76956612/115190869-48e86e80-a106-11eb-8b6d-a793bda099ac.PNG)

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by tymsai** [comment]
![2](https://user-images.githubusercontent.com/76956612/115244972-165c6700-a142-11eb-8b0a-1b667bfe19d8.PNG)
terminal is also failing to launch

**Comment by bpasero** [comment]
You need to make `code` available on the command line, e.g. by using an installer for VSCode.

**Comment by tymsai** [comment]
my vscode crashed again on startup but the folder which I made is still empty there's no  ` *.dmp ` file in it.
I entered this code in cmd  ` code --crash-reporter-directory G:\dump  ` .

**Comment by deepak1556** [comment]
What is the output of `code --verbose` ?

**Comment by tymsai** [comment]
it simply opened the vscode & some script was generating in cmd.
![hjk](https://user-images.githubusercontent.com/76956612/115330816-6bd05c80-a1b2-11eb-8779-b462748b1e5d.PNG)

**Comment by deepak1556** [comment]
Okay that looks correct, the empty directory in https://github.com/microsoft/vscode/issues/121617#issuecomment-822554987 is incorrect though.

Can you record a screencast for the following scenario, you can use https://gifcap.dev/ to help with it

* Close all running instances of vscode
* code --crash-reporter-directory G:\dump
* Once the `window has crashed` dialog pops up
* Close the application
* Display the contents of `G:\dump`

**Comment by tymsai** [comment]
I found a dump file created at the same time of crashing vs code on startup but it's **totally at a different Folder path**;

If you need that dmp file I will send it but it's at a **different location**. The folder `G:\dump` is still empty.

![Capture1](https://user-images.githubusercontent.com/76956612/115345100-ebb6f080-a1cb-11eb-800d-f69ba3267039.PNG)

**Comment by deepak1556** [comment]
> I found a dump file created at the same time of crashing vs code on startup but it's totally at a different Folder path;

Which path is it ? The one under Chrome is unrelated.

Please share the screencast from https://github.com/microsoft/vscode/issues/121617#issuecomment-822978773

**Comment by tymsai** [comment]
![vid](https://user-images.githubusercontent.com/76956612/115359449-507a4700-a1dc-11eb-97b6-2487da0ece0a.gif)

**Comment by deepak1556** [comment]
Thanks for the screencast, that looks correct. Only reason it didn't generate the dumps might be because of permissions to the target directory. Can you set the crash directory to `C:\Users\Public\Documents\VSCode-Crash`


Do you see the crash with our insiders version https://code.visualstudio.com/insiders ?

**Comment by tymsai** [comment]
did you mean instead of `G:\dump` in cmd I should type this : `C:\Users\Public\Documents\VSCode-Crash`.

Yes the insiders build is crashed .

![vsc insider](https://user-images.githubusercontent.com/76956612/115429928-85f55380-a221-11eb-8121-755f105164c0.PNG)

**Comment by tymsai** [comment]
I wrote this code in cmd : `code --crash-reporter-directory C:\Users\Public\Documents\VSCode-Crash`.
After closing the VSCode the directory is empty.
![vsc normal public](https://user-images.githubusercontent.com/76956612/115432566-277da480-a224-11eb-9ca7-f0f375908250.PNG)

**Comment by deepak1556** [comment]
Will have to check back on why the crash handler does not generate reports, please follow the below steps as an alternative way to get the memory dump while the window crashed.

* Download and install latest vscode insiders https://code.visualstudio.com/insiders
* Download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
* Find the workbench process id by following command in powershell
```
Get-WmiObject win32_process -Filter "name='Code - Insiders.exe'" | where CommandLine -like '*--type=renderer*' | Select-Object ProcessId, CommandLine
```
* Once the window crashed, open process explorer and find the processes with above ProcessId
* Right Click on the Process -> Create Dump -> Full Dump
* Send the files to Deepak.Mohan@microsoft.com

![Screenshot (11)](https://user-images.githubusercontent.com/964386/111221389-aa616e80-8597-11eb-936d-423e6c0dbd02.png)

**Comment by tymsai** [comment]
dump file generated at the same time of crash : 
![crash-live](https://user-images.githubusercontent.com/76956612/115434694-9cea7480-a226-11eb-8775-89bea535726c.gif)

**Comment by deepak1556** [comment]
Can you attach that dump file, I find it weird that it is generated under `Chrome`, won't hurt to check.

**Comment by tymsai** [comment]
Does the dump file under chrome contain sensitive information ?

**Comment by tymsai** [comment]
?

**Comment by deepak1556** [comment]
> Does the dump file under chrome contain sensitive information ?

what kind of sensitive information are you asking about ? The dump file will contain some PII. You can also send the dump file to Deepak.Mohan@microsoft.com

**Comment by tymsai** [comment]
what kind of sensitive information are you asking about ? 

things like passwords

**Comment by deepak1556** [comment]
Nope it does not.

**Comment by tymsai** [comment]
But I am afraid to give it to you , as my PC contains some sensitive information;
PLEASE don't think any bad of you,
you are trying to solve my problem,
thanks for that.
