### ISSUE TITLE
Fix issues when notebook applyEdits fails

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#121687]
From https://github.com/microsoft/vscode-jupyter/issues/5446

- We should not throw exceptions out of the execution task to extensions when an output with the given ID is missing - it should just be a no-op
- Need to still push onto the undo stack and emit events when this happens, otherwise we stop emitting events forever

**Comment by rebornix** [comment]
> Need to still push onto the undo stack and emit events when this happens, otherwise we stop emitting events forever

@roblourens what will be pushed into undo stack then? There is no such output anymore, meaning there will be no change on text model at all.

**Comment by roblourens** [comment]
If it throws for some reason (assertIndex or some other reason) we don't know whether or not changes were made before something broke
