### ISSUE TITLE
Debugger breakpoint need uncheck/check to make it work.

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#121611]
Hi, the debugger seem have strange behavior, it not work the first time if we refresh, but if we uncheck/check again break point it starting work.
See here 
Debugger connect correctly (thanks all for this crazy magics)
But it will not work as long you `uncheck/check` breakpoint in left panel activity ! 
![a3rfa3fa3fa3](https://user-images.githubusercontent.com/24865815/115170747-662e2600-a08f-11eb-8d35-eb49e15dbcab.gif)

---

Version : 1.55.2 (user setup)
Commit : 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date : 2021-04-13T09:35:57.887Z
Electron : 11.3.0
Chrome : 87.0.4280.141
Node.js : 12.18.3
V8 : 8.7.220.31-electron.0
OS : Windows_NT x64 10.0.19042

**Comment by connor4312** [comment]
What debugger are you using? That doesn't look like it's the built-in JavaScript debugger. If not, please open an issue on the repo for that debugger.

**Comment by djmisterjon** [comment]
> What debugger are you using? That doesn't look like it's the built-in JavaScript debugger. If not, please open an issue on the repo for that debugger.

ho oki! , I thought that was kind of a shortcut !
Like a easy shortcut to make bridge between port of a chromium devtool and Vscode managing the rest.
![image](https://user-images.githubusercontent.com/24865815/115262796-dc1fa500-a102-11eb-8b82-314bc675fed6.png)

i currently using this one 
https://marketplace.visualstudio.com/items?itemName=ruakr.vsc-nwjs
But support seem death  ! 
If you think it not related to internal Vscode behavior , i can close, but it strange that's everything work, but need check/uncheck vscode breakpoint for make work, i have no clue why !

**Comment by connor4312** [comment]
> Like a easy shortcut to make bridge between port of a chromium devtool and Vscode managing the rest

It looks like it's using an implementation of our old debugger that we don't support any longer.

Please open an issue on https://github.com/karikera/vscode-nwjs-debug. This is something they'll have to resolver.
