### ISSUE TITLE
Native Notebooks - Collapse All Notebook Cells

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121647]
Using the "Notebook: Collapse All Notebook Cells" command makes the notebook look broken. 

![image](https://user-images.githubusercontent.com/19276747/115254449-352b1100-a0e2-11eb-8d2a-717645e8b35b.png)

+1 from customer email 

![vscode-jupyter-plot-broken](https://user-images.githubusercontent.com/19276747/115254620-60156500-a0e2-11eb-98a5-078ef60ce8f2.png)

**Comment by rebornix** [comment]
cc @mjbvz . It seems the offset updates events are not properly sent to the webview.
