### ISSUE TITLE
Doesn't work right anymore

### ISSUE THREAD

**Issue by tdiprima** [microsoft/vscode#121656]
Issue Type: <b>Bug</b>

The latest version of Code isn't working right for me anymore (Code 1.55.2, and I'm using MacBook Air 10.15.5).
Let's say I close an editor.  Or I close the app by clicking the X . Now I go to the command line and do `code .` to open the current folder in code.  When Code opens, there's no explorer, editor, or anything.  Completely blank window.  Even if I try to do View... or File... none of those functions work.  I have to completely exit out of Code and restart it, in order for it to work.

Thanks in advance.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 913dc1bd-bb1e-4ec4-820a-71c6bad4526c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.61
vscode-great-icons|emm|2.1.73
go|gol|0.24.1
beautify|Hoo|1.5.0
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.3
remote-ssh-edit|ms-|0.65.3
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
vscodeintellicode|Vis|1.2.12

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
When you run `code --open-devtools` from the command line and the window shows empty, is anything printed in the console portion at the bottom of VSCode below?

**Comment by tdiprima** [comment]
The problem has been occurring for the past week.  Now when I run `code --open-devtools` to see if anything is printed, nothing is printed in the console portion at the bottom of VSCode.  And I am now having trouble reproducing the error, after having run `code --open-devtools`.

**Comment by bpasero** [comment]
Ok 👍
