### ISSUE TITLE
npm err!

### ISSUE THREAD

**Issue by RicardoKerr** [microsoft/vscode#121669]
Issue Type: <b>Bug</b>

npm ERR! code ERESOLVE

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.97GB free)|
|Process Argv|--crash-reporter-id d8eaea8a-07c9-4c37-a429-a0d7bd9812ef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
vscode-eslint|dba|2.1.20
live-html-previewer|hdg|0.3.0
kite|kit|0.142.0
Kotlin|mat|1.7.1
vscode-language-pack-pt-BR|MS-|1.55.2
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vetur|oct|0.33.1
LiveServer|rit|5.6.1
preview-vscode|sea|2.2.5
ms-teams-vscode-extension|Tea|1.2.2
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
pythontb:30283811
wslfolderdoc:30282074
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30288035
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify how this issue is related to VS Code editor itself.
Looks like issue with npm
