### ISSUE TITLE
Crashes with multibytes characters and backspace key

### ISSUE THREAD

**Issue by romligCH** [Microsoft/vscode#12165]
- VSCode Version: 1.5.2
- OS Version: Windows 10 

Steps to Reproduce:

1. Open a blank file
2. Set the language mode to JSON (seems to works with other languages too)
3. Type "😄😄😄😄😄😄😄😄😄😄", with quotes
4. Place cursor before the last quote
5. Press the backspace key multiple times

Following dialog appears:

> [Window Title]
> Visual Studio Code
> [Main Instruction]
> The window has crashed
> [Content]
> We are sorry for the inconvenience! You can reopen the window to continue where you left off.
> [Reopen] [Close]

Debug console contains following error one or multiple times:

> D:\Applications\Microsoft VS Code\resources\app\node_modules\getmac\out\lib\getmac.js:1216[1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancing
> scanNext @ D:\Applications\Microsoft VS Code\resources\app\node_modules\getmac\out\lib\getmac.js:1216
> _tokenizeString @ D:\Applications\Microsoft VS Code\resources\app\node_modules\getmac\out\lib\getmac.js:1191
> Grammar.tokenizeLine @ D:\Applications\Microsoft VS Code\resources\app\node_modules\getmac\out\lib\getmac.js:1028
> e.tokenize @ index.html?config={"_"%3A[]%2C"disable-extensions"%3Atrue%2C"disableExtensions"%3Atrue%2C"locale"%3…:119
> tokenize @ index.html?config={"_"%3A[]%2C"disable-extensions"%3Atrue%2C"disableExtensions"%3Atrue%2C"locale"%3…:119
> t._updateTokensUntilLine @ index.html?config={"_"%3A[]%2C"disable-extensions"%3Atrue%2C"disableExtensions"%3Atrue%2C"locale"%3…:56
> t._revalidateTokensNow @ index.html?config={"_"%3A[]%2C"disable-extensions"%3Atrue%2C"disableExtensions"%3Atrue%2C"locale"%3…:56
> (anonymous function) @ index.html?config={"_"%3A[]%2C"disable-extensions"%3Atrue%2C"disableExtensions"%3Atrue%2C"locale"%3…:56

**Comment by Tyriar** [comment]
Grammar exception is here: https://github.com/Microsoft/vscode-textmate/blob/7970025675f264d204c34b10e81fdd0fa8ce3e17/src/grammar.ts

**Comment by rozzzly** [comment]
I don't experience slowdown/freeze. I get a different behavior.

  1. Open any file
  2. Type some text like, `bug test text`
  3. I insert a multibyte character like 😵
  4. Place cursor just after the emoji/Unicode then hit backspace.
  5. Emoji disappears, in its place is a weird question mark on top of a diamond symbol, one of the ascii broken character symbols you've seen before in older versions of MS DOS and the like
  6. Hitting backspace again removes the ASCII error character, the space taken up by the Emoji is now gone and subsequent backspace remove `bug test text` as expected 

Seems like hitting backspace directly after a multibyte character only deletes the rightmost byte leaving a broken character. I would assume the desired behavior would be to treat multibyte chars as a single unit.

> ( Btw I run the nightly/insiders build on arch Linux)

**Comment by alexandrudima** [comment]
long story, sorry I missed this issue:
* oniguruma got a PR
* it got accepted
* they shipped a new npm version
* we adopted it
* today I made some changes to prevent us from creating invalid UTF16 to begin with.

**Comment by alexandrudima** [comment]
Relevant #12329 #10945
