### ISSUE TITLE
"Open with..." does not open a picker when there is no custom editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121637]
I would expect the picker even when there is just 1 custom editor.

**Comment by lramos15** [comment]
I'm not seeing this, I see a picker with just text editor in it.

**Comment by bpasero** [comment]
While testing this, have we ever asked ourselves if the "gear" icon is the right one to associate the editor as default?

![image](https://user-images.githubusercontent.com/900690/115898007-5b8fda00-a45d-11eb-90e8-e232c3e6ed01.png)

I somehow would have expected settings editor to open when I click, not that the association changes by default.

//cc @misolori

**Comment by misolori** [comment]
I gave this feedback before as well that the gear does not communicate that action. I'd expect a similar "Change default" item at the bottom of the quick pick like the Formatter option as that is more clear/explicit:

![image](https://user-images.githubusercontent.com/35271042/116126659-c1f24380-a67b-11eb-9d3c-f7a3976f4d12.png)
