### ISSUE TITLE
Terminal excessive space on top

### ISSUE THREAD

**Issue by J-Siu** [microsoft/vscode#121696]
- VS Code Version: 1.55.2
- OS Version: Darwin x64 20.3.0 / macOS 11.2.3

Steps to Reproduce:

1. Start VSCode (`code --disable-extensions`)
2. Start a terminal
3. Try following:
    - move terminal to the side, split them, them move the spliter up/down
    - resize vscode

Does this issue occur when all extensions are disabled?: Yes

Terminal may have excessive space on top that cannot be clicked (to get focus). It is very inconsistent. Sometime it does not happen, sometimes bigger, sometimes smaller, sometimes happen to bottom also. Following are 3 screenshots with non-clickable space highlighted by green rectangle:

![Screen Shot 2021-04-19 at 9 09 44 PM](https://user-images.githubusercontent.com/3171920/115323108-67298b00-a155-11eb-8b6e-0f93d00a1049.png)
![Screen Shot 2021-04-19 at 9 09 49 PM](https://user-images.githubusercontent.com/3171920/115323115-6b55a880-a155-11eb-8118-d7d1749f5fd7.png)
![Screen Shot 2021-04-19 at 9 19 54 PM](https://user-images.githubusercontent.com/3171920/115323120-6db80280-a155-11eb-9936-f25ce2783e05.png)

**Comment by meganrogge** [comment]
Without steps to reproduce this, we can't investigate it. Please update this if you identify a way we can

**Comment by Tyriar** [comment]
I don't have a monitor large enough to check this but I believe we made some improvements recently here, could you check if it still happens in the Insiders build? https://code.visualstudio.com/insiders

Also the first 2 could just be 1px too small and working by design.

**Comment by J-Siu** [comment]
@meganrogge Add a bit more, but really not much to add to reproduce. 
It happen by just starting/resizing the terminal or vscode.

**Comment by J-Siu** [comment]
@Tyriar
Not sure what mean by "1px too small". Those empty space highlighted by green rectangle are higher than 1 text line within the terminal, cannot be clicked and won't go away unless I resize vscode, or the spliter. And it extents to the scroll bar too.

It doesn't need big monitor to see, but it is a bit by chance:
![Screen Shot 2021-04-22 at 7 08 51 PM](https://user-images.githubusercontent.com/3171920/115795915-d6de8680-a39e-11eb-8665-2a2ab2b978cd.png)

It is not just about the visual. It actually become quiet annoying when changing focus to terminal by clicking the window, and end up clicking those empty space, it does nothing(focus didn't change), then you start typing and suddenly realize you are still typing in the editor.

**Comment by J-Siu** [comment]
I discover the issue is caused by zoom. I had it on 3 for screen sharing session sometime ago and forget to switch back. Once I change it back to 1, the issue is almost gone and don't affect work flow anymore.
