### ISSUE TITLE
Specify which extension provides a specific keyboard shortcut

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode#121673]
Version: 1.56.0-insider (user setup)
Commit: ce791d27dc9889a392f4d29abefe9c53eb0b5129
Date: 2021-04-16T11:25:09.662Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Go to `File -> Preferences -> Keyboard shortcuts`
2. The Source column only states that an extension is the source

![image](https://user-images.githubusercontent.com/20347396/115298331-3116e780-a112-11eb-86f5-3d426d0efffb.png)

It'll be helpful to tell which extension provides it so that I can disable it if it interferes with my workflow.

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
Does https://github.com/microsoft/vscode/wiki/Keybinding-Issues help in this case? I don't recall if the information it produces reveals which extension is involved in a keybinding that fires.

**Comment by DavidKutu** [comment]
It technically does, with the basic troubleshooting we can tell what command got executed, and knowing that, we could go through our list of extensions to see the commands they contribute and find it that way.

But it would be easier for a user to be able to look at the `Keyboard shortcuts` page and tell which extension is using the key binding.
