### ISSUE TITLE
Terminal: Double actions

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121604]
1. Open Terminal
1. Toggle `terminal.integrated.showTabs` off an on

![image](https://user-images.githubusercontent.com/22350/115155924-db214180-a036-11eb-98b8-5e396c30da6b.png)

**Comment by hkennyv** [comment]
To add on to this, each time you toggle `terminal.integrated.showTabs`, another "new terminal" row appears 🤔
