### ISSUE TITLE
Show problems badge on terminal task tabs

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#121658]
It would be nice to be able to quickly see how many "problems" were found in a terminal task tab (assuming there is a problem matcher).

**Comment by Tyriar** [comment]
Seems to duplicate the badge on the problems panel? The plan is to show an x icon or similar when the task fails (generates problems).

**Comment by meganrogge** [comment]
Agreed w @Tyriar, what would you imagine the difference would be as compared with the problems panel badge @eamodio ?

**Comment by eamodio** [comment]
I think what @Tyriar mentioned, just showing an indicator on a failure/errors is more what I'm after than the actual count or anything like that.

**Comment by Tyriar** [comment]
Ah k, this is covered by the tasks issue that you created then, unfortunately that'll probably be pushed to May.
