### ISSUE TITLE
FileDecorationProvider not rendering decorations in Insiders

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#121684]
Issue Type: <b>Bug</b>

The GitHub Pull Requests and Issues extension registers several `FileDecorationProviders` that add status and commenting decorations to the PR tree. In today's insiders I'm not seeing any of these decorations get rendered:
![Screen Shot 2021-04-19 at 2 57 56 PM](https://user-images.githubusercontent.com/3672607/115308687-f6b44700-a11f-11eb-97f0-0b8fedc6f03e.png)

But I do see them in the latest stable:
![Screen Shot 2021-04-19 at 2 59 34 PM](https://user-images.githubusercontent.com/3672607/115308678-f0be6600-a11f-11eb-8b37-18e6bc790177.png)

VS Code version: Code - Insiders 1.56.0-insider (8aff878db2542eea2dfb571c8bb485118bbb3113, 2021-04-19T05:13:43.644Z)
OS version: Darwin x64 19.6.0

**Comment by eamodio** [comment]
@alexr00 It looks like [this change](https://github.com/microsoft/vscode/commit/bbc5a53ac5b912ee8c7bcb41864f72132de50589) broke this: 

https://github.com/microsoft/vscode/blob/bbc5a53ac5b912ee8c7bcb41864f72132de50589/src/vs/workbench/browser/parts/views/media/views.css#L134-L137

**Comment by alexr00** [comment]
Thanks for root-causing it!
