### ISSUE TITLE
Hope vscode can set the extended installation location

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode#121632]
I hope vscode can set the extended installation location. Although we can manually change the connection location of extensions using the console, this is usually a bit more troublesome. If we change the relevant files in vscode, the code added to it will be replaced when vscode is updated. Therefore, it is hoped that vscode can directly bring the function of custom extension installation location, reducing the trouble of manual change every time.

**Comment by Vincent0706** [comment]
I want vscode to customize the extended installation location. Although you can manually change the connection location of extensions using the console, this is usually a bit more troublesome. If you change the relevant files in vscode, the code added to it will be replaced when vscode is updated. Therefore, it is hoped that vscode can directly bring the function of custom extension installation location, reducing the trouble of manual change every time.

**Comment by sasial-dev** [comment]
Hey @Vincent0706,
Thanks for changing the description to English, can you also change the title?

**Comment by joaomoreno** [comment]
What exactly is the _extended installation location_?

**Comment by joaomoreno** [comment]
Apart from `--extensions-dir`, there is the env variable `VSCODE_EXTENSIONS`. This is enough for you to create tools around to make that change permanent.

**Comment by Vincent0706** [comment]
Could you tell me where is the env variable `VSCODE_EXTENSIONS`? I can't find that on my computer.
