### ISSUE TITLE
Dialog informing the user what is workspace trust should be a part of the Trust Editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121636]
Currently we show the workspace trust dialog the first time user open vscode.
After the workspace trust dialog we would show the workspace trust editor.

I really do believe that these two experience should be merged into one, since having two dialogs is a believe a bad user experience.
So

* If a user sees the workspace trust editor for the first time it should contain all the explanations
* If a users see the workspace trust editor after that there are no explanations and it would look like it does today

**Comment by lszomoru** [comment]
Closing this issue as we are not currently showing the workspace trust editor anymore when the user opens vscode.
