### ISSUE TITLE
Crash when debugging extension and you close the dev tools too quickly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#12160]
VSCode Version: `Version 1.6.0-insider (1.6.0-insider)` 50bb7aad57cbf1924e28472de52734be49645558
OS Version: `OS X El Capitan Version 10.11.6 (15G1004)`

Steps to Reproduce:

1. Start debugging an extension
2. After the new instance of code starts, click the restart button in the main code instance
3. When the new instance starts again its dev tools seems to open (for some reason) and if you click its close button too quickly both instances of code crash

It might take a couple of times to get it to happen, but I can reproduce it quite reliably.

**Comment by bpasero** [comment]
@eamodio does the dev tools show any contents? can you share the extension you debugged?

**Comment by eamodio** [comment]
@bpasero I'm working on [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens). The dev tools is starting to show content, but it needs to be closed quite quickly to exhibit the issue.

**Comment by eamodio** [comment]
@bpasero I'm not sure what I can show -- you need to close the dev tools before they really finished rendering for it to crash. I can record of a gif of it and post it here later today.

**Comment by bpasero** [comment]
@eamodio yes please 👍

**Comment by eamodio** [comment]
@bpasero not the best capture, but here:
> ![vscode-crash](https://cloud.githubusercontent.com/assets/641685/18655303/ac87dd7c-7eb5-11e6-8bde-c565d3899bcb.gif)

Offscreen I had clicked the restart button in the main instance to cause the extension host to reset.

**Comment by bpasero** [comment]
Known issue: https://github.com/Microsoft/vscode/issues/4430
