### ISSUE TITLE
Ctrl+enter to run status bar item disappears after execution

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121661]
Issue Type: <b>Bug</b>

* Open github issue notebook
* Focus a cell editor
* Notice that the "Ctrl+Enter to run" status bar item is there
* Run the cell, it went away and never came back

VS Code version: Code - OSS Dev 1.56.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (1.35GB free)|
|Process Argv|. --no-sandbox --enable-proposed-api ms-vsliveshare.vsliveshare|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Actually did that by design. You only need it when you haven't run the cell and there is no checkmark in the status bar right?

**Comment by rebornix** [comment]
> You only need it when you haven't run the cell and there is no checkmark in the status bar right?

I'm not sure, it feels weird that its visibility is tied to the check mark visually. cc @misolori
