### ISSUE TITLE
Activity bar hover is brighter than titlebar hover (?)

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121600]
Feels brighter:

![recording (7)](https://user-images.githubusercontent.com/22350/115155630-bb3d4e00-a035-11eb-96c0-18d452441f55.gif)

**Comment by sandy081** [comment]
I am using `toolbarHoverBackgroundColor`. 

@misolori May I know if titlebar uses different hover background?

**Comment by misolori** [comment]
looks like it's using `menubar.selectionBackground` cc @sbatten who worked on the menu

**Comment by sbatten** [comment]
menus and menubar have there own theme keys, in this case matching can make sense because of the same background color is used but titlebar might be a different color than the activity bar hence the separate keys

**Comment by sandy081** [comment]
Since I have removed hover background color on activity bar actions, I am closing this as no action needed.
