### ISSUE TITLE
How to avoid jumping to other places in Find All References?

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#12162]
- VSCode Version: 1.5.2
- OS Version: OS X 10.11.6

![jump](https://cloud.githubusercontent.com/assets/4033249/18595351/28859708-7bf9-11e6-9adb-a521ec81b2b1.gif)

When I'm doing Find All References I hope I can just stay in the window. Jumping to random places loses me all context I've been working with.

I think Single click -> Show reference in the inline window, Double Click -> Go to the reference in file would be a better approach.

It also wouldn't hurt to add some decoration to the symbol that you are jumping to, and let it fade out after jumping there.

**Comment by jrieken** [comment]
> I think Single click -> Show reference in the inline window, Double Click -> Go to the reference in file would be a better approach.

That's how it works for me. A single click (or selection with arrow keys) preview the references in the peek window and a double click (or enter) jump to the reference. @octref Is there more that would allow me to reproduce? Any special single/double click configurations you are running with?

**Comment by octref** [comment]
@jrieken 
When the references are in the same file as the place where you open "Find All References".

For example, try it on `FileStat` in this line https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/common/explorerViewModel.ts#L21. Click the references under `explorerViewModel` (not the first few, the ones in the latter part).

**Comment by jrieken** [comment]
Nope

![sep-20-2016 09-33-32](https://cloud.githubusercontent.com/assets/1794099/18661307/54d131cc-7f15-11e6-9075-2b4d2fd0cefb.gif)

**Comment by octref** [comment]
The culprit is VSCodeVim. This behavior is gone when I disable it.
/cc @johnfn @rebornix

**Comment by rebornix** [comment]
@octref I thought I was the only one who ran into this issue. Yes it's VSCodeVim indeed, we had a hard time tracking cursors.

**Comment by octref** [comment]
@rebornix Do we have an issue on VSCodeVim tracking it?

**Comment by rebornix** [comment]
not yet, feel free to move this issue there or I can do it later.

**Comment by octref** [comment]
Tracking in https://github.com/VSCodeVim/Vim/issues/790
