### ISSUE TITLE
Checkmarks background for transparent images missing for certain themes

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#12168]
- VSCode Version: 1.5.2
- OS Version: OS X

An image with transparent parts should be obvious. Adding checkmarks as default background of images is common in a lot of other applications.

**Comment by bpasero** [comment]
@mohsen1 we do have a checkmark pattern as background, are you not seeing it? can you attach a screenshot?

**Comment by mohsen1** [comment]
Screenshot:
![screen shot 2016-09-19 at 10 36 50 am](https://cloud.githubusercontent.com/assets/543633/18642301/04521dee-7e55-11e6-947a-7b957fc42f41.png)

Image:
![pin_bottom 3x](https://cloud.githubusercontent.com/assets/543633/18642309/09549f42-7e55-11e6-852d-c0c127c0b55b.png)

**Comment by bpasero** [comment]
@mohsen1 looks like this for me:

![image](https://cloud.githubusercontent.com/assets/900690/18642701/ffc483d2-7ea1-11e6-90c7-2a7928923f35.png)

**Comment by mohsen1** [comment]
I see. It depends on your theme. Mine is Monokai. I had a few theme extensions. Even after removing them I'm still seeing this issue.

**Comment by bpasero** [comment]
@mohsen1 oh yeah indeed an issue with the theme 👍

**Comment by Tyriar** [comment]
High contrast theme:

![image](https://cloud.githubusercontent.com/assets/2193314/18966694/0d522058-8637-11e6-92fc-089164e0c366.png)

Contrast is too low for me to notice on Tyriar.theme-glacier-0.0.10:

![image](https://cloud.githubusercontent.com/assets/2193314/18966708/1ee3d7bc-8637-11e6-8cc1-fb88242afc7d.png)

- VSCode Version: Code - Insiders 1.6.0-insider (0f7880d7a490ba9aee2b053f3f2e46c19423e7e4, 2016-09-29T14:13:08.930Z)
- OS Version: Linux x64 4.4.0-38-generic, Ubuntu 16.04

**Comment by bpasero** [comment]
I would like to keep this for high contrast theme because we ship like this from day 1 and it could well be that the way it is now actually works better for people that need high contrast. 

Let's wait until a user with HC theme actually complains.

**Comment by Tyriar** [comment]
I'm complaining right now with Tyriar.theme-glacier, it's a dark theme and the grid is barely visible unless zoomed in

![image](https://cloud.githubusercontent.com/assets/2193314/18998823/328dc8b4-86ef-11e6-959d-2d5ac678b403.png)

Why wouldn't it work on a dark theme with a dark background?

**Comment by bpasero** [comment]
@Tyriar feel free to play with https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceviewer.css#L25
