### ISSUE TITLE
Not able to select code

### ISSUE THREAD

**Issue by prachi14-techved** [microsoft/vscode#121643]
open vs code and try selecting the code it gives you multiple cursors

**Comment by tymsai** [comment]
need more info

**Comment by tymsai** [comment]
see if the alt button is pressed, 
" alt+left click  " gives you multiple cursors.

**Comment by Zachinquarantine** [comment]
a screenshot would be nice for context too...

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please fill in issue template with all necessary info.

Also check if you are using any actions that provide multicursor/box selection as described in https://code.visualstudio.com/docs/editor/codebasics

Also: Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`
