### ISSUE TITLE
Terminal: List actions don't save save for scrollbar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121605]
![recording (8)](https://user-images.githubusercontent.com/22350/115156286-5f27f900-a038-11eb-902c-46ad5d004710.gif)

**Comment by Tyriar** [comment]
Looks fixed in today's build

![image](https://user-images.githubusercontent.com/2193314/115208519-7fe06500-a0b1-11eb-8f28-2c2a89c0be8f.png)
