### ISSUE TITLE
Terminal doesn't work (insiders, vscode remote Mac to Windows)

### ISSUE THREAD

**Issue by knopp** [microsoft/vscode#121685]
- VS Code Version: 1.56.0-insider (Universal) 8aff878db2542eea2dfb571c8bb485118bbb3113
- OS Version: MacOS 11.3

Steps to Reproduce:

1. Connect to a remote workspace running on Windows (SSH)
2. Try to type anything in terminal (regardless of selected shell)

There is no feedback in the terminal

**Comment by knopp** [comment]
This is not a duplicate of https://github.com/microsoft/vscode/issues/121691. There is no JS error, the terminal is there, it sows output but doesn't respond to any input. And it only happens when connecting to remote windows machine through the **Remote SSH Extension**. It also doesn't happen with older VSCode versions so it is clearly a regression.

**Comment by Tyriar** [comment]
Same issue reported for local git bash: https://twitter.com/muzurvelet/status/1384519403920936963

**Comment by zachabarnes** [comment]
Have the same issue as well with mac remote into windows. I can open as many integrated terminals as I want (cmd, powershell, etc) but in all I cant type/enter anything.

**Comment by Tyriar** [comment]
Could someone try enabling escape sequence logging https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging and type into the terminal and see if something gets logged?

**Comment by incastea** [comment]
> Could someone try enabling escape sequence logging https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging and type into the terminal and see if something gets logged?

I ran the "Terminal: Toggle Escape Sequence Logging" command. Set the Keybinding to ALT + H. And yes the Console registers correct keystrokes from the Terminal Window.
![termissue](https://user-images.githubusercontent.com/63691040/115607589-d4702400-a2ed-11eb-92e2-ae05afec7805.jpg)

**Comment by incastea** [comment]
Also I'm leaving a Console Log after a fresh loading of VS Code and Terminal window in case it may help.
[console_out.txt](https://github.com/microsoft/vscode/files/6353416/console_out.txt)

**Comment by zachabarnes** [comment]
Can also confirm chars are logged. 
![Screen Shot 2021-04-21 at 4 00 41 PM](https://user-images.githubusercontent.com/7801667/115631638-0e740280-a2bb-11eb-96f7-627b703e117b.png)

**Comment by incastea** [comment]
@knopp @zachabarnes do any of you happen use Vivaldi browser in your setups? It’s also Chromium-based like VS Code. Maybe (a wild guess) Vivaldi can be interfering with VS Code’s operation.

**Comment by Tyriar** [comment]
@deepak1556 after exhausting all the other options we realized this is almost certainly due to the Electron update. Reports started coming in on April 19th and the build after the Electron update happened was the 18th https://github.com/microsoft/vscode/commit/3fb483e7fff42559b5f93e8aa92d0354021ee5ff
