### ISSUE TITLE
Add security and versioning dependency alerts

### ISSUE THREAD

**Issue by szlatkow** [microsoft/vscode#121633]
- [Dependabot](https://dependabot.com/) alerts on updates for the project's dated and vulnerable dependencies and automatically creates PRs to easily update them

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by joaomoreno** [comment]
Thanks @szlatkow. We already have Dependabot alerts and PRs working for us.
