### ISSUE TITLE
VS Code unresponsive upon startup after installation - CPU Usage at 100%

### ISSUE THREAD

**Issue by kfwalther** [microsoft/vscode#121642]
- VS Code Version: code-1.54.3-1615806453.el7.x86_64
- OS Version: CentOS Linux release 7.6.1810 (Core)

Steps to Reproduce:

1. Download the **code-1.54.3-1615806453.el7.x86_64.rpm** file from the VS Code downloads page.
2. Install VS Code using the downloaded RPM via yum: **sudo yum install ./code-1.54.3-1615806453.el7.x86_64.rpm**
3. After installation completes, launch VS Code from terminal: **code &**
4. VS Code starts normally (can see all the normal tabs/buttons) but the window is unresponsive, and remains so indefinitely. Two VS Code threads are causing 100% CPU usage (see attached images):

![image](https://user-images.githubusercontent.com/20177495/115234769-6a862d80-a0e7-11eb-925c-0872efe88161.png)

![image](https://user-images.githubusercontent.com/20177495/115234976-a1f4da00-a0e7-11eb-889a-bdfb1eedb102.png)

These threads appear to have the following command line parameters:
 * /usr/share/code/code --inspect-port=0 /usr/share/code/resources/app/out/bootstrap-fork --type=extensionHost
 * /usr/share/code/code --disable-extensions --no-sandbox

Running the **code --status** command after starting VS Code similarly does not respond nor return a result. Starting VS Code using the command **code --prof-startup** produces one profile-file in my home directory (also attached). 

The same symptoms occur with later version: **code-1.55.2-1618307357.el8.x86_64** so I had to rollback to **code-1.52.1-1608137084.el7.x86_64** to avoid this issue.

This appears to be the same issue as https://github.com/microsoft/vscode/issues/119279. That issue is **not** resolved.

Does this issue occur when all extensions are disabled?: Yes

[prof-1736.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/6336117/prof-1736.main.cpuprofile.txt)

**Comment by tobypeschel** [comment]
I'm having this exact issue with `code-1.55.2-1618307357.el8.x86_64`, and only downgrading (to any prior version) resolved it for me.

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/115784

Please install gcc-5 or higher toolchain to fix the CXXABI issue.

**Comment by kfwalther** [comment]
@deepak1556 Thanks, that work-around resolved the issue, although I would expect this dependency to be enforced by the package manager.

**Comment by deepak1556** [comment]
> I would expect this dependency to be enforced by the package manager.

Yup that is the work being tracked in the above linked issue.
