### ISSUE TITLE
Terminal: Can't find setting to toggle list of terminals view

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121602]
Because of https://github.com/microsoft/vscode/issues/121601, I'm trying to find the setting to switch it off:

- `terminal` returns 65 results
- `terminalside`: 0
- `terminalpanel`: 0
- `terminallist`: 0

Seriously... what's the setting name?

**Comment by joaomoreno** [comment]
Found it: `terminal.integrated.showTabs`

Maybe let's not call them tabs, since they aren't tabs.

**Comment by wardy3** [comment]
this has been driving me mad this morning. i couldn't work out if i'd changed a setting or installed an extension or something. unticked "showTabs" and now i'm happy but it would be a good option to have a right-click -> hide option or something more obvious please

**Comment by Tyriar** [comment]
Internal poll saw "tabs" winning as what to call this list, I'll improve the keywords used in the setting though.
