### ISSUE TITLE
Min width of terminal tab is too wide

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121677]
Issue Type: <b>Bug</b>

As video shown below, the default min width seems too wide. I tried to shrink the tab column to make the icons look centered but it doesn't allow me to do so.

https://user-images.githubusercontent.com/876920/115303723-d5039180-a118-11eb-991b-a71755efb198.mov

VS Code version: Code - Insiders 1.56.0-insider (Universal) (8aff878db2542eea2dfb571c8bb485118bbb3113, 2021-04-19T05:13:43.644Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.80GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
This is to allow space for the status icons

**Comment by Tyriar** [comment]
I think you just need to drag it a little more to the left? There is a mid point of the text and no text versions and we snap to the closest.

**Comment by rebornix** [comment]
@Tyriar if I drag a bit to the left, it hides the labels then

<img width="106" alt="image" src="https://user-images.githubusercontent.com/876920/115439818-d9d14f80-a1c3-11eb-857b-43a59fe47772.png">

So I'm either label-less, or having a tab bar with label, but not centered.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/876920/115439850-e2298a80-a1c3-11eb-8c1f-8ceeafdb482f.png">

**Comment by Tyriar** [comment]
This is by design, centered doesn't really work when decorations and hover actions come on.
