### ISSUE TITLE
Conditional breakpoints sometimes stop working

### ISSUE THREAD

**Issue by DoomUnicorn** [Microsoft/vscode#12167]
- VSCode Version: 1.5.2
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:
1. Set a conditional breakpoint in a Nodejs project
2. Use it for a while
3. Get frustrated because the breakpoint stopped working, spend a lot of time thinking it's your code.
4. Restart application, hope it fixes the breakpoint -- it doesn't
5. Go back to using archaic breakpoint without conditions, inspect variable, see condition is met, wonder why isn't this working. 
6. Restart Visual Studio Code, jump for joy as the conditional breakpoint works again!
7. Write ticket on this website and hope super cool Microsoft developer notices my plebeian ticket.
8. Microsoft developer fixes issue!
9. Profit.
   Further detail:
   I am using conditional breakpoints to stop execution of my software once a condition has been reached such as the following:

txBuff[17] == 24

The breakpoint works for a little while, and then stops working. Restarting Visual Studio Code appears to fix the problem temporarily.

**Comment by weinand** [comment]
Seems to work fine in recent versions.
