### ISSUE TITLE
Terminal: Terminals list should not appear by default

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121601]
I got an update for Insiders and the terminal appears with the list. This should be behind a setting.

**Comment by Tyriar** [comment]
The plan was to make it the new default?

**Comment by joaomoreno** [comment]
No sure if that was a question for me. 😄

I am strongly opposed taking up screen real estate for all users, just because a subset of them use multiple terminals sometimes. But I would not be so opposed to it if the list only shows up if you have more than one terminal at a time, and would hide if you have just a single terminal. Let's call that `auto` mode.

**Comment by Tyriar** [comment]
> I would not be so opposed to it if the list only shows up if you have more than one terminal at a time, and would hide if you have just a single terminal. Let's call that auto mode.

If we did go this route, what do you think about this design?

1 terminal:

![image](https://user-images.githubusercontent.com/2193314/115206326-54f51180-a0af-11eb-9ba3-fb81dd6ae0dd.png)


2 terminal (notice the +v icon in the panel):

![image](https://user-images.githubusercontent.com/2193314/115206443-72c27680-a0af-11eb-862e-10894ae5bad2.png)

**Comment by joaomoreno** [comment]
Love it, of course! 👏

**Comment by isidorn** [comment]
@Tyriar I think this is great improvement and going in the right direction.
