### ISSUE TITLE
Unknown Debug Option "Run Script: start"

### ISSUE THREAD

**Issue by partoneplay** [microsoft/vscode#121624]
Issue Type: <b>Bug</b>

Where does the "Run Script: start" come from?

VS Code version: Code 1.55.2 (Universal) (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

Here is my `launch.json`
<img width="912" alt="launch" src="https://user-images.githubusercontent.com/5189132/115199434-c8d20100-a125-11eb-9b54-971f9954d46e.png">

**Comment by weinand** [comment]
@partoneplay this is a dynamic launch configuration which is automatically created for script entries in the package.json. Your   package.json seems to have a "start" script.
