### ISSUE TITLE
Adopt new editorOverrideService

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#121668]
The use of `overrideOpenEditor` is being removed this iteration due to the confusing nature of it and the increasingly duplicated code. It is being replaced with the `editorOverrideService` which consumers should call `registerContributionPoint` on (this name will change). I have adopted this for custom editors and notebooks and as more code moves there it becomes harder to maintain both the editor service implementation and this one. So for that reason I need help moving the last use cases of `overrideOpenEditor` to the new service so that it may be removed.

The following cases are:

- [x] `searchEditor.contribution.ts` @JacksonKearl 
- [ ] `webviewPanel.contribution.ts` @mjbvz (or @jeanp413 if you're feeling up for it since you wrote the original one :p)
- [x] `fileAction.ts` @bpasero 
- [x] `preferencesContribution.ts` @roblourens 

Please let me know if you have any questions. Thanks for the help!

**Comment by roblourens** [comment]
- You could make `ContributedEditorPriority` a numeric enum and get rid of `priorityToRank`
- Why do I have to give the priority twice?
- Can 'detail' be optional?
- Does `IEditorOverrideService` have to be in `/browser/`?

**Comment by lramos15** [comment]
- The string representation is needed as that was the package.json has for extensions. I will just ask for the string and instead call `priorityToRank` internally as you are correct it is silly to pass it twice.
- See above, you shouldn't. I'll remove that
- Probably, I don't think anyone uses it for anything but repeating the title
- No, I placed it there because the `IEditorService` implementation was there but @bpasero have discussed moving where it lies if that makes it easier for you.

**Comment by roblourens** [comment]
Anything that can go in common should.  I'm trying to use this from a contribution file which is in common

**Comment by bpasero** [comment]
Yeah I think it can easily move, the editor service though cannot because it depends on some browser components.

**Comment by bpasero** [comment]
@lramos15 work in progress for my area is in https://github.com/microsoft/vscode/compare/ben/121668 but I am facing an issue: it looks like we always call `replaceEditors` when an editor gets overridden and this results in the following experience:

![recording](https://user-images.githubusercontent.com/900690/115387914-8f5bcd00-a1db-11eb-8192-c2d151898290.gif)

Probably related: https://github.com/microsoft/vscode/issues/121708

**Comment by lramos15** [comment]
@roblourens I have moved the editorOverrideService into common and made many of your suggestions let me know if you have any questions

**Comment by roblourens** [comment]
Would still prefer to nuke the split json editor but I'll pick it up again

**Comment by JacksonKearl** [comment]
Can the `EditorInputFactoryFunction` return a promise of an `IEditorInputWithOptions`? The old model allowed for an async `override` function, which the search editor employed.

**Comment by lramos15** [comment]
I'm going to defer to @bpasero for this one. The idea of not letting it return a promise is we really shouldn't be having IEditorInputs that are async in creation. There are a few issues we hit with CustomEditor and NotebookEditor input factories being async and we want to heavily avoid that pattern.

**Comment by bpasero** [comment]
Yeah best to return sync and leave `async` stuff to the `IEditorInput#resolve` method if possible.

**Comment by roblourens** [comment]
One thing I'm not sure about, currently if user settings is open in the split editor, and then I try to open workspace settings, I find that user settings editor and use `group.replaceEditors` to replace it with a split editor for workspace settings. In the new paradigm, I can only return an editor input for someone else to open. Is there some way to get the same behavior? Would it be safe to close the existing editor and assume that the new one will be opened right away? I think I would be ok with just not having this behavior too. Or I could delete the split json editor.

**Comment by lramos15** [comment]
@roblourens Once you register your contribution if you were to call `this.editorService.replaceEditors` yourself with an override option of your settings editor ID it would do the same behavior by triggering your contribution. The override service just registers handlers, it doesn't actually trigger the opening, the opening pathways are through their respective editorService methods

**Comment by roblourens** [comment]
I mean that we are trying to do "replaceEditors" when the override contribution is called

**Comment by lramos15** [comment]
I think I'm still confused @roblourens. The contribution is opening agnostic, are you saying you want the settings editor to always replace? There is the option `singlePerResource`, but I'm not sure if that's what you want as that wouldn't close all settings.json and open your split json editor regardless of grouping. If you know when this flow is being triggered and could call close couldn't you call replaceEditors too? I might be misunderstanding though.

**Comment by bpasero** [comment]
Compare action is adopted via https://github.com/microsoft/vscode/commit/c50ab1e89f665466cc3001a4574f82d2d54d6d49

**Comment by roblourens** [comment]
> If you know when this flow is being triggered and could call close couldn't you call replaceEditors too?

I don't think so, the contribution is supposed to return an editor input, and I assume you then call openEditor with it, and I get the sense that the contribution should act like a pure factory, not something that has side effects. Maybe I'm wrong and it's ok to call replaceEditors then return the EditorInput that I just opened.

To explain more, you have `<userDataDir>/settings.json` already open in the editor, then you click on `.vscode/settings.json`, and I need to override the second open and replace that first editor with the new one.

**Comment by lramos15** [comment]
Just following up on our offline discussion here. It's a very odd case and something we don't want to support in the new service, so for now just don't do the replace and allow multiple instances.

**Comment by bpasero** [comment]
@JacksonKearl I just came across this code and think it needs a revisit as well as part of this issue:

https://github.com/microsoft/vscode/blob/cb6e7b383bb7a2d76848162bd5897e1a04bd5b9a/src/vs/workbench/contrib/searchEditor/browser/searchEditorInput.ts#L220-L222

It looks like the search editor indicates it `matches` a file editor input if the resources are the same, but if we keep that code, a user would not be able to open a search in both text editor and search editor.

**Comment by lramos15** [comment]
Might be the cause of this issue then https://github.com/microsoft/vscode/issues/120221

**Comment by bpasero** [comment]
Yeah sounds like it.

**Comment by JacksonKearl** [comment]
Yeah I actually came across that line yesterday, I was unable to see the effects of removing it as it seems editors which have not adopted `editorOverrideService` can no longer participate in "Reopen With..."

**Comment by JacksonKearl** [comment]
Adopted in search editor, but I still see that when I go to "Reopen With...", the text editor is marked as default, even though my contribution is at `ContributedEditorPriority.exclusive` level (same holds for `ContributedEditorPriority.default`), and clicking on a *.code-search file in the explorer opens search editor by default.

**Comment by lramos15** [comment]
@JacksonKearl I will investigate this. Thanks for adopting the service.

**Comment by lramos15** [comment]
Update. I don't see this, but I would also recommend against exclusive as then the user can't set a setting to be anything else even if they want to. 
<img width="616" alt="Screen Shot 2021-05-06 at 4 04 48 PM" src="https://user-images.githubusercontent.com/4544166/117359149-02746d00-ae85-11eb-929a-862a3888b854.png">

**Comment by JacksonKearl** [comment]
Moved to default but I still see this. Another oddity: if I click the file in the explorer once, it opens in search editor. If I click it again, it reopens in text editor, as I click more and more it keeps alternating, or even opening new editors.

**Comment by mjbvz** [comment]
The `webviewPanel.contribution.ts` override was added to prevent a single webview created by an extension from being opened in two groups at once. 

@lramos15 Is this something that we could specify on the editor input instead and let VS Code handle this? The current code doesn't fit the `EditorOverrideService` very well

**Comment by lramos15** [comment]
Hmm, that's a tough one @mjbvz. It sounds like the single resource option we have on custom editors but I would assume webviews don't really fit into a specific globPattern which makes it difficult to support.

**Comment by lramos15** [comment]
After discussion with @bpasero it seems like the best idea is to add this to the Webview Editor Inputs and then place the protection logic in the `editorGrouopView` as right now the consumer could just call `group.openEditor(webview)` and break this again.
