### ISSUE TITLE
Case sensitive on macOS

### ISSUE THREAD

**Issue by khoa-io** [microsoft/vscode#121663]
Issue Type: <b>Bug</b>

When open a project folder with a folder named `build` and a file named `BUILD`, the folder is not shown in Explorer. Moreover, I can't go to files in that folder.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 10, 14|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|test --crash-reporter-id 49df4056-5573-4c48-a82e-27f5821f7c30|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/
I can not reproduce. If you can with insiders can you attach a picture please?

**Comment by isidorn** [comment]
Aaa you have both the BUILD and build, dup of https://github.com/microsoft/vscode/issues/94307
