### ISSUE TITLE
Menus flicker then close when hovering items whilst using 4K screen.

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#121616]
Issue Type: <b>Bug</b>

On a 4K screen, open any of the top menus or context menus. Hoever over the menu options, especially those within submenus, and you will see random menu items being highlighted and flickering. It can even magically close the menu on you from just hovering over different items.

This does not happen when I work on my laptop's integration FHD screen.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.11.0-7612-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|31.09GB (12.43GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id eb1c688b-c4e3-4232-85a1-c01025d91995|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-apollo|apo|1.18.2
bracket-pair-colorizer-2|Coe|0.2.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
restore-terminals|Eth|1.1.5
vscode-firefox-debug|fir|2.9.4
gauge|get|0.0.19
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.33.1
indenticator|Sir|0.7.0
language-stylus|sys|1.11.0
vscodeintellicode|Vis|1.2.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/119829
