### ISSUE TITLE
AutoHotkey

### ISSUE THREAD

**Issue by brentarias** [Microsoft/vscode#12166]
I've programmed AutoHotkey to rewire my "home" and "end" keys which works great, but with the latest Visual Studio Code it does not work.  Here are my AutoHotkey mappings:

```
PrintScreen::Home
Insert::End
RCtrl::PrintScreen
```

The above script worked correctly with prior versions of Visual Studio Code.  And to reiterate, those mappings still work correctly elsewhere (such as the Sublime editor or in notepad).
- VSCode Version: 1.5.2
- OS Version: Windows 10 Enterprise, 64bit

Steps to Reproduce:
1. Open Visual Studio Code.  
2. Open any file with text in it.
3. Try using AutoHotkey shortcuts / hotkeys.

The AutoHotkey hotkeys will not work.

**Comment by brentarias** [comment]
I've now upgraded to VSCode 1.5.3, and this problem has been resolved!

**Comment by brentarias** [comment]
Unfortunately, the problem has returned. I am now using VSCode 1.11.2.  This is the same problem, with the same autohotkey mapping.

I saw in another thread someone suggesting a change to vscode configuration:

"keyboard.dispatch": "keyCode"

A "keyboard.dispatch" is not a valid "user settings" or "workspace settings" option for me.

**Comment by alexandrudima** [comment]
@brentarias 

So this AutoHotkey script worked in VSCode 1.10.2 -- https://az764295.vo.msecnd.net/stable/8076a19fdcab7e1fc1707952d652f0bb6c6db331/VSCode-win32-1.10.2.zip

But does not work anymore in VSCode 1.11.2 ?

On Windows, we are always dispatching on `keyCode`, that's why the setting is invalid and the keybindings changes should have no impact on dispatching on Windows.

**Comment by brentarias** [comment]
Yes is works correctly on the 1.10.2 version (as you provided in the link) but does not work on 1.11.2.

**Comment by brentarias** [comment]
I just updated to vscode 1.12.0.  The problem is fixed (again)!

**Comment by brentarias** [comment]
I just updated to vscode 1.12.1.  The problem is back again!

**Comment by alexandrudima** [comment]
@brentarias This makes no sense to me. There was no code change between 1.12.0 and 1.12.1 except for fixing a packaging issue.

**Comment by brentarias** [comment]
I am now using version 1.12.2.  The problem is resolved (fixed) again.

I can't explain this either.  I'm simply reporting what I see.

**Comment by alexandrudima** [comment]
@brentarias Could there be something else on your system (unrelated to VS Code) that might make an impact. Or perhaps this works / stops working only under certain circumstances? (e.g. using it at the beginning of a line, at the end of a line, in the middle of text, etc.)

**Comment by brentarias** [comment]
I've tried experimenting with when and where this works or does not work.  It *always* works in OneNote, as well as Skype, Discord, and Slack desktop clients.  It *always* works in (browser window) gmail, notepad, git bash prompt, Windows Subsystem for Linux (WSL) bash prompt, and the cmd.exe prompt. It works inside this markdown / form input that I'm typing in right now.

It does *not* work at the powershell prompt, in SSMS, or in Visual Studio 2015.  

VSCode is the only place it sometimes does or does not work...all determined by changing versions of VSCode (as my reports have indicated).  Re-loading VSCode or rebooting the machine does not change the behavior.

It does not matter where in a line I use the command: beginning, end, middle...if it works it works completely correctly.  If it does not work, it simply does not work at all.

The behavior is not "flaky".  For example, I said that it started to work again in 1.12.2.  It has continued to work successfully in 1.12.2 all day long (I give VSCode a huge beating all day) and is working right now in VSCode.  Only changing versions of VSCode has influenced the behavior.

**Comment by charlietran** [comment]
On StackOverflow, I've found the solution to this problem: https://stackoverflow.com/questions/1890351/why-is-visual-studio-catching-key-events-before-autohotkey

> If ahk and the target app are not running under the same privileges (or user) ahk won't intercept/simulate keyboard events properly. In my case, visual studio was run with administrator (elevated) privileges while the ahk script was run as the currently logged on user.
> Either of the following solved the problem:
> * Running both vs and ahk as the current user
> * Compiling the script and running both vs and the compiled app as administrator

For me, running AHK as administrator fixed the issue!

**Comment by alexandrudima** [comment]
Closing for now, as there appears to be no changes to be done in VS Code.
