### ISSUE TITLE
Problem Matcher is not localized

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/vscode#121672]
*the problem exists in vscode build task for extension development*
the problem matcher `$tsc-watch` is not localized.
it cannot detect the end of `tsc --watch` when my pc locale is set to `Persian`

locale: English - works✔
```
[11:41:46 AM] Starting compilation in watch mode...

[11:41:49 AM] Found 0 errors. Watching for file changes.
```

locale: Persian - doesn't work❌
```
[۱۱:۴۳:۲۲] Starting compilation in watch mode...

[۱۱:۴۳:۲۵] Found 0 errors. Watching for file changes.
```

**Comment by alexr00** [comment]
I tried to improve this with https://github.com/microsoft/vscode/issues/46373, but it looks like there are still some cases where that regex isn't good enough.

**Comment by alexr00** [comment]
@mjbvz FYI, I made the typescript problem matcher match times that don't use numbers.

**Comment by roblourens** [comment]
If you need something stricter, and if we run task matcher regexes with the unicode `u` flag, you can use this character class to do a real generic number check

![image](https://user-images.githubusercontent.com/323878/116744286-f719d100-a9ae-11eb-89d6-147d19e9f05c.png)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes
