### ISSUE TITLE
Visual studio code hangs when Commiting to git source control

### ISSUE THREAD

**Issue by Ib01** [microsoft/vscode#121699]
Whenever I go to the "Source Control" tab on the left of the ide and do a commit, visual studio code hangs, ie the progress indicator never completes. 

If I try to commit from the command line after this happens I get a message saying that code could  not be committed because of a lock file in the .git directory :/. after deleting said lock file I can commit again ... looks like some sort of race condition here?

**Comment by gjsjohnmurray** [comment]
Any clues in the Git channel of the Output view on the panel?

**Comment by Ib01** [comment]
I had a look but it wasn't very informative. What I did do though is disable the "Debugger for Chrome" plugin. since then it has been working normally again. go figure :/
