### ISSUE TITLE
blank lines in the terminal

### ISSUE THREAD

**Issue by cafeed28** [microsoft/vscode#121752]
- VS Code Version: 1.55.2
- OS Version: Windows 10 LTSC 1809

Steps to Reproduce:

1. Select "Command Prompt" as default terminal and open it in default panel size
![image](https://user-images.githubusercontent.com/62172116/115432335-b0dea800-a21f-11eb-9338-cb6c6f9e7039.png)

2. If you start the terminal in maximized panel, everything is fine
![image](https://user-images.githubusercontent.com/62172116/115432537-eb484500-a21f-11eb-82f0-44779b746835.png)

It appears in VSCodium and Visual Studio Code

Does this issue occur when all extensions are disabled?: Yes
![image](https://user-images.githubusercontent.com/62172116/115433033-7fb2a780-a220-11eb-80ee-15ba6c230d72.png)

**Comment by meganrogge** [comment]
I can't reproduce this. Does it only happen w command prompt or other shells? Are there any errors when you go to `Help -> Open Developer Tools -> Console`?

**Comment by cafeed28** [comment]
It happens only on cmd, powershell and git bash works normally. In console no any errors

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by cafeed28** [comment]
can't reproduce in code - insiders
