### ISSUE TITLE
Chrome doesn't work sometimes when debugging a file

### ISSUE THREAD

**Issue by Dust-trust** [microsoft/vscode#121773]
Issue Type: <b>Bug</b>

1. Open a file with Chrome; Sometimes works, sometimes doesn't.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.39GB free)|
|Process Argv|--crash-reporter-id e869ff49-9481-4108-abb9-029814b70225|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.25.1
debugger-for-chrome|msj|4.12.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by Dust-trust** [comment]
I can provide more info if needed.

**Comment by weinand** [comment]
Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions to learn how to write bug reports.

**Comment by Dust-trust** [comment]
Werid, it fixed itself. I'll close this now.
