### ISSUE TITLE
How to set the extensions path?

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode#121719]
I'm sorry that I ask the question again, but I still don't know the way to set the extensions path according to th last answer.
https://github.com/microsoft/vscode/issues/121632#issuecomment-822443078
This is the last answer. He says we can use "env variable VSCODE_EXTENSIONS". But I don't know how to use it. If you can, please tell me the specific process. 
Thank you sincerely.

**Comment by sandy081** [comment]
Please google for **How to Set env variable** in the platform you are using and please follow the steps.
