### ISSUE TITLE
Editor override: add test coverage for editor service using editor override service

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121792]
Seeing the changes e.g. from https://github.com/microsoft/vscode/pull/121666, just a reminder that there should be tests for the editor service that verify the editor override service is being used properly from the methods that consume it:
* `openEditor`
* `openEditors`
* probably soon: `replaceEditors` (related https://github.com/microsoft/vscode/issues/121793)

**Comment by lramos15** [comment]
Will do 👍. Notebooks luckily have integration tests so this is being tested in some way but we should definitely add the editor service end of things

**Comment by lramos15** [comment]
Added a few simple test cases just to ensure that the override settings are respected and that glob matching is working. Leaving this open for now in case we want to tackle future cases.

**Comment by bpasero** [comment]
Thanks, I think this is what I had in mind, so feel free to close.
