### ISSUE TITLE
Find In Files fails to find text in file where lines end in LF only

### ISSUE THREAD

**Issue by garychapman** [microsoft/vscode#121789]
- VS Code Version: 1.55.2
- OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a file where lines are separated by LF only (0x0A) without a preceeding CR (0x0D)
2. Use Find In Files and try to search for any text after the first LF

Does this issue occur when all extensions are disabled?: Yes. Also with Insiders commit b4816cfd1f4161a3bb272354d181a9947760ee26

**Comment by roblourens** [comment]
This is a normal scenario. I use LF line endings. Can you share the file or some more details?

**Comment by garychapman** [comment]
It turns out the LF-only line endings were a red herring. The files where Find was failing also contained NUL bytes halfway through them, which is [known](https://github.com/BurntSushi/ripgrep/issues/306) to make ripgrep stop searching. My bad!
