### ISSUE TITLE
CSS style in extension readme.md file not work after installation

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#121784]
- VS Code Version: 1.54.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. New a VS Code extension and add some css style in readme.md markdown file
2. Preview in VSC, works well
3. Package the VSIX using vsce
4. Install the VSIX and check the extension in  VSC sidebar 'Extensions'
5. The landing page(displayed from readme.md) didn't apply the css styles
(Not sure if this is a bug or by design)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
This sounds like the expected behavior: extension pages strip custom css from your html security reasons and to match how these pages are rendered in the marketplace. The markdown preview allows custom css
