### ISSUE TITLE
Some editorOverrideService usage feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121727]
From my working on https://github.com/microsoft/vscode/issues/121668:
* `options` in `registerContributionPoint` should be optional
* the methods `active` and `instanceof` feel like a workaround for not being able to figure this out internally
* there is a `editorID` passed into `createEditorInput` and `createDiffEditorInput` but it is entirely not clear what this is or what I am supposed to do with it [1]

[1] looking at where this originates from this seems to be the `selectedContribution`, but what is the idea behind passing this on?

https://github.com/microsoft/vscode/blob/7c7c83e5644bc51c870eef7f55afa554c2bd5fdc/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L229-L229

**Comment by lramos15** [comment]
- I can do that
- I think I'm able to remove instanceof, but yes there is no way to tell if the current editor input is you. We could get rid of the idea of active if you don't think it's important to show the `Currently Active` text.
- `editorID` is needed to be passed back because that's how `CustomEditorInput` and `NotebookEditorInput` differentiate their editor inputs based on extension type. So here we tell them which one is being opened so they can create the correct input.

**Comment by bpasero** [comment]
> I think I'm able to remove instanceof, but yes there is no way to tell if the current editor input is you. We could get rid of the idea of active if you don't think it's important to show the Currently Active text.

No I think we can keep it, but the name is weird. Now that I understand the motivation, how about `describes(editor: IEditorInput)` instead? Because this is not about the editor being active or not but figuring out if the editor info is related to a certain editor input. And then you just pass in the active editor to figure it out.

> editorID is needed to be passed back because that's how CustomEditorInput and NotebookEditorInput differentiate their editor inputs based on extension type

I still do not understand it. This is the ID of an editor from where?

**Comment by lramos15** [comment]
> No I think we can keep it, but the name is weird. Now that I understand the motivation, how about describes(editor: IEditorInput) instead? Because this is not about the editor being active or not but figuring out if the editor info is related to a certain editor input. And then you just pass in the active editor to figure it out.

Well this is about whether the current editor passed in (which is the active one) belongs to your contribution

> I still do not understand it. This is the ID of an editor from where?

From the contribution, let me play around with, you might always be able to use the one that you passed in. The reason it's used is we're about to open that editorID and want to make sure your input is able to handle it. Custom Editors + Notebooks are the ones that really specialize in the same input type for different editor Ids.

**Comment by bpasero** [comment]
> Well this is about whether the current editor passed in (which is the active one) belongs to your contribution

Yeah, I understand. So I think the name `active` is misleading, because it is about figuring out whether the info belongs to the editor passed in. So I suggested `describes` or something similar.

> From the contribution, let me play around with, you might always be able to use the one that you passed in

I slowly start to understand what this is, it is the `ContributedEditorInfo.ID` that was picked to open? But why does this need to be passed in, isn't that literally the object I am in that provides `createEditorInput`?

**Comment by lramos15** [comment]
Renamed and removed. Options is optional now too.
