### ISSUE TITLE
Can't remove the terminal profiles panel

### ISSUE THREAD

**Issue by bolinocroustibat** [microsoft/vscode#121711]
Since recently, VS Code terminal pane started to display a profiles sub-panel. There is no option to remove/hide it.

<img width="1031" alt="Screen Shot 2021-04-20 at 09 39 33" src="https://user-images.githubusercontent.com/4353767/115349898-604f5680-a1ef-11eb-99df-72ac425f3cfa.png">

- VS Code version: 1.56.0-insider
- OS Version: MacOS 11.2.3
Does this issue occur when all extensions are disabled?: Yes

**Comment by yume-chan** [comment]
`"terminal.integrated.showTabs": false`

**Comment by bolinocroustibat** [comment]
Thanks @yume-chan. Is this a new feature from latest version? A recent change of default behaviour? A bug?

**Comment by yume-chan** [comment]
It's a new feature (see #10546) and expected to be on by default in next version (see #121601)
