### ISSUE TITLE
Translation Fix for Korean

### ISSUE THREAD

**Issue by chongkong** [Microsoft/vscode#12171]
| Key | English | Korean |
| ----- | ----- | ----- |
| `indentationToSpaces` | Convert Indentation to Spaces | 들여쓰기를 공백으로 변환 |
| `indentationToTabs` | Convert Indentation to Tabs | 들여쓰기를 탭으로 변환 |

**Comment by chongkong** [comment]
You can find them in https://github.com/Microsoft/vscode/blob/master/i18n/kor/src/vs/editor/contrib/indentation/common/indentation.i18n.json

**Comment by johnliu2016** [comment]
@lukaschal Please send above 2 strings to linguistic review

[/Localize/kor/vscode/src/vs/editor/contrib/indentation/common/indentation.nls.resx.lcl](
https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization?path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Feditor%2Fcontrib%2Findentation%2Fcommon%2Findentation.nls.resx.lcl&version=GBmaster&_a=contents)

**Comment by lukaschal** [comment]
@chongkong Please is it possible to add some ENU/KOR screenshots or some suggestion what exactly is wrong with current translation ?

**Comment by chongkong** [comment]
current Korean translation for `indentationToSpaces` is:

> ID를 공백으로 변환

This is mistranslation that translated `indentation` as `identification` (as you can see, there's `ID` in Korean string 😄)

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\editor\contrib\indentation\common\indentation.nls.resx
ID: ".resx", 0; "indentationToSpaces"
SRC: Convert Indentation to Spaces
TGT: 들여쓰기를 공백으로 변환

File: src\vs\editor\contrib\indentation\common\indentation.nls.resx
ID: ".resx", 0; "indentationToTabs"
SRC: Convert Indentation to Tabs
TGT: 들여쓰기를 탭으로 변환
