### ISSUE TITLE
Completion sorts different depending on whether it was filtered client-side or invoked after typing a prefix

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#121743]
- VS Code Version: 1.55.2
- OS Version: macOS Big Sur 11.2.3

Steps to Reproduce:

1. Create a completion provider that returns the following:
  ```
   [
      CompletionItem(label: 'Foo.one', sortText: 'aaa'),
      CompletionItem(label: 'OSError.noErrorCode', sortText: 'zzz'),
    ]
  ```
2. Invoke completion and type `on` and note the ordering of the results
3. Re-invoke completion with `on` already typed

Results if invoking completion and then typing "on":

<img width="503" alt="Screenshot 2021-04-20 at 16 38 56" src="https://user-images.githubusercontent.com/1078012/115424816-f0dd6500-a1f6-11eb-9216-0483f8a20052.png">

Results if invoking with "on" already typed:

<img width="365" alt="Screenshot 2021-04-20 at 16 39 30" src="https://user-images.githubusercontent.com/1078012/115424863-ff2b8100-a1f6-11eb-8525-d2dc302f1d83.png">

This may be by design, but it doesn't seem consistent with the description of `sortText`:

https://github.com/microsoft/vscode/blob/08f9bbc2394cf319cdffdf2b7d8fd19aef65345b/src/vs/vscode.d.ts#L4052-L4055

I suspect it could also behave strangely with `isIncomplete=true` as that can fetch new lists from the server after keypresses. If the server-provided ranking will be used even with a prefix if the client has done no filtering, I think that should be documented.

**Comment by jrieken** [comment]
Please enable explain mode via `Cmd+/` to see the ranking for each item

**Comment by DanTup** [comment]
Ah, I wondered how to enable that - I'd searched the command palette and not found it!

Here's after I typed "on" and it was filtered client-side:

<img width="581" alt="Screenshot 2021-04-21 at 16 18 39" src="https://user-images.githubusercontent.com/1078012/115578572-51cf7080-a2bd-11eb-81fc-69937f3f2e07.png">

<img width="574" alt="Screenshot 2021-04-21 at 16 19 58" src="https://user-images.githubusercontent.com/1078012/115578731-70356c00-a2bd-11eb-985c-fb3fa498d09a.png">


And here's when I re-invoke the completion manually after "on" has already been typed (note: screenshots are in the displayed order, so the first one here is the second one above):

<img width="535" alt="Screenshot 2021-04-21 at 16 18 49" src="https://user-images.githubusercontent.com/1078012/115578610-5b58d880-a2bd-11eb-8a29-63d35c933aa7.png">

<img width="581" alt="Screenshot 2021-04-21 at 16 20 13" src="https://user-images.githubusercontent.com/1078012/115578772-79bed400-a2bd-11eb-81be-db5530da571c.png">

Strangely they seem to show the same score, but the order is different (if they should fall back to the sortText in that case, it seems like they'd be consistent - although whether it's correct they both get the same score I'm unsure).

**Comment by jrieken** [comment]
> Strangely they seem to show the same score, but the order is different (if they should fall back to the sortText in that case, it seems like they'd be consistent

When you typed the `o` the score for `OSError...` was stronger than for for `Foo.one` and therefore the item got sorted atop. Since sorting is stable it doesn't restore the order after score equalize.

**Comment by DanTup** [comment]
@jrieken but if the scores are equal, shouldn't it be sorting by sortText? The text above says "the initial ordering is only used when completions match equally well" which seems to match here?

If it's deemed this is working as intended, can you confirm what the intended behaviour is when using `isIncomplete=true`? If VS Code triggers a new request and filters client side while it's pending, then the request completes with the same results that VS Code had filtered to, would it retain VS Code's sorting, or would it overwrite them with the servers?

If the latter, it seems like `inIncomplete=true` may allow us to override VS Code's sorting (which would make me happy, although I expect is not intended).

**Comment by jrieken** [comment]
> the initial ordering is only used when completions match equally well

The initial ordering is after the results are retrieved and before scoring against a prefix.
