### ISSUE TITLE
Open a terminal in vscode cause crash when folder 's path contain chinese character

### ISSUE THREAD

**Issue by NKUCodingCat** [Microsoft/vscode#12175]
- VSCode Version: 1.5.2
- OS Version: Windows 10 Pro 14383.187 

Steps to Reproduce:

1.  Open a folder which contain any chinese character in VSCode 
2.  Press `Ctrl+``
3. Terminal will exit with code 1

I don't know why, however, I think it may caused by encoding .....

**Comment by ZCShou** [comment]
This issue exists for a long time.

**Comment by Tyriar** [comment]
Duplicates #7727, thanks @ZCShou
