### ISSUE TITLE
Open with: allow to open the same file in different editors

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#121708]
I find it confusing today that an editor is being replaced when I select "Open with...". I would expect that the original editor remains when I open with another editor.

Maybe there is a limitation I am not aware of but I think this should be supported. This is especially weird when the file to reopen is dirty and I am being asked to save it.

//cc @mjbvz

**Comment by bpasero** [comment]
Especially in cases where a custom editor is text based, this works pretty cool actually because the same model is shared:

![image](https://user-images.githubusercontent.com/900690/115345264-d67f9900-a1ae-11eb-9bc4-c5c111181641.png)

**Comment by lramos15** [comment]
The general conversation has been `Reopen with....` is opening the current file in a different editor and therefore it's replaced. Where if you right click in the explorer and do `Open With....` it should keep the current tab.

**Comment by bpasero** [comment]
Yes I do agree about that statement.

**Comment by bpasero** [comment]
Related code (I think): https://github.com/microsoft/vscode/blob/fc191749834ceea13e1be76c81c14430ce152dc6/src/vs/workbench/services/editor/browser/editorOverrideService.ts#L299-L311

**Comment by lramos15** [comment]
I believe this was fixed when I fixed https://github.com/microsoft/vscode/issues/121793. If you can still reproduce this issue please feel free to reopen it.

**Comment by bpasero** [comment]
👏 

![recording](https://user-images.githubusercontent.com/900690/116105950-16b0b100-a6b2-11eb-841c-ce53ed5984cc.gif)

**Comment by IllusionMH** [comment]
Any chances to have "Open with..." as alternative action for "Reopen Editor with..." in context menu?

So I'll be able to open custom editor for current tab side by side instead of looking for same file in Explorer to open it again.

Or is there a command to open current editor in new tab with different custom editor?

**Comment by lramos15** [comment]
@IllusionMH I don't believe there is anything right now besides the explorer context menu and extension APIs that allow for `Open With...`. However, when you focus a tab it should focus the respective explorer item so you don't have to go looking for it.
