### ISSUE TITLE
Win 10 ARM32 support

### ISSUE THREAD

**Issue by Qiangong2** [microsoft/vscode#121753]
I see that there is a linux ARM32 build, is it possible to get a Win 10 ARM32 build? If not, why?

**Comment by deepak1556** [comment]
Why is this build needed ? We do provide ARM64 version of the application https://code.visualstudio.com/#alt-downloads

**Comment by deepak1556** [comment]
Thanks for the context, this requires relevant binaries from the runtime https://www.electronjs.org/ and its components. Closing as this is not actionable at the moment from VSCode.
