### ISSUE TITLE
Incorrect syntax highlighting python code with type hints

### ISSUE THREAD

**Issue by rwijtvliet** [microsoft/vscode#121754]
Issue Type: <b>Bug</b>

1. Typ
```python
def a(value) -> bool:
    return True
```

2. Observe syntax highlighting
![grafik](https://user-images.githubusercontent.com/4106013/115435377-0dcf6380-a20a-11eb-873e-e72713be4b1f.png)

May be related to #121700 and/or #121370.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (3.77GB free)|
|Process Argv|--crash-reporter-id eceffb98-354f-4cae-ba07-105eaf5a9834|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pytest|Cam|0.1.1
cornflakes-linter|kev|0.5.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
autodocstring|njp|0.5.4
material-icon-theme|PKi|4.6.0
vscode-paste-and-indent|Rub|0.0.8
markdown-preview-enhanced|shd|0.5.18
python|tht|0.2.3
pdf|tom|1.1.0
vscodeintellicode|Vis|1.2.12
vscode-jumpy|wma|0.3.1
material-theme|zhu|3.10.13

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30283811
wslfolderdoccf:30282075
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by alexr00** [comment]
I'm not able to repro this issue. It is likely caused by one of the extension you have installed.

**Comment by rwijtvliet** [comment]
Thanks for the speedy answer. Disabling extensions one-by-one I found that [Python for VsCode](https://marketplace.visualstudio.com/items?itemName=tht13.python) was causing the issue.
