### ISSUE TITLE
Find widget has empty space

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121798]
![image](https://user-images.githubusercontent.com/22350/115519697-4a1cb700-a23e-11eb-9bd9-73fd2e1d939f.png)

**Comment by rebornix** [comment]
@joaomoreno are you using English local?

**Comment by joaomoreno** [comment]
Yeah.

**Comment by rebornix** [comment]
This one looks like a regression.

**Comment by rebornix** [comment]
Fixed.
