### ISSUE TITLE
Test: tab opening blocked dialog

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121763]
Refs: https://github.com/microsoft/vscode/issues/118731

- [x] macOS @bpasero
- [x] macOS @Tyriar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23121763%0A%0A)

---

Safari automatically blocks opening of new tabs, when we detect that a new tab or window opening has been blocked we now show a dialog on which the user can react and allow for the tab or window to get opened.
Do the following:

1. Use VSCode and verify opening new windows or clicking on links in editor does not show any unexpected dialog and everything works as before
2. Open our web bits in Safari or use codespaces and verify:

* Open a starter VS Code extension and verify you can debug it. Once you start debugging it you see the newly introduced dialog and clicking on `"Continue"` properly opens a new tab and you can debug
* Clicking on a link in the editor also shows this new dialog, clicking on `"continue"` properly opens a new tab
* Do an action that results in a folder, workspace or file to open in a new window
* Try to be creative with commands that open new tabs or new windows and verify that you see this dialog any time Safari blocks opening. Verify you do not see this dialog when it is not expected

**Comment by bpasero** [comment]
Brilliant 👍
