### ISSUE TITLE
The window has crashed (reason 'launch-failed')

### ISSUE THREAD

**Issue by NPUlrk** [microsoft/vscode#121729]
- VS Code Version: VSCodeUserSetup-x64-1.55.2
- OS Version: Windows 10 Professional 1903 18362.1256

Steps to Reproduce:

1.Launch the vscode.
2.Crash dialog show.
 
![image](https://user-images.githubusercontent.com/21106497/115393343-2775a880-a214-11eb-8fd3-e3d88127f89f.png)

Does this issue occur when all extensions are disabled?: Yes/No  
I have already delete all files associate with vscode，and reinstall it，didn't works for me, the crash dialog still shows.

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose --vmodule=*/base/process/*=4`
