### ISSUE TITLE
Invalid string length during large file find/replace

### ISSUE THREAD

**Issue by fiendish** [microsoft/vscode#121759]
Issue Type: <b>Bug</b>

In a ~600MB tsv file, find&replace from `"\t"` to `"\t\\x"` produces "invalid string length" error.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|hashes.tsv --crash-reporter-id 9fb8dc35-5051-4a4d-b716-e8088d84cf73|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
emojisense|bie|0.8.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.1.0
bracket-pair-colorizer-2|Coe|0.2.0
vscode-markdownlint|Dav|0.40.3
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
gc-excelviewer|Gra|3.0.41
output-colorizer|IBM|0.1.2
bridlensis|idl|1.2.2
nsis|idl|3.40.1
nsis-plugins|idl|1.3.0
nsl-assembler|idl|1.2.1
restructuredtext|lex|148.0.0
rainbow-csv|mec|1.8.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
hexeditor|ms-|1.5.0
autodocstring|njp|0.5.4
fix-json|oli|0.1.2
vscode-luaformatter|sta|0.0.4
rewrap|stk|1.14.0
vscode-lua|tri|0.12.4
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554:30281908
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by ericrbg** [comment]
Can confirm, also with changing CRLF ↔ LF

**Comment by rebornix** [comment]
sorry for reaching out late, @fiendish @ericrbg do you still see the issue on latest VS Code? Also do you have minimal reproduce for this issue?

**Comment by fiendish** [comment]
@rebornix In fact, now it's worse. Now vscode chronically does _nothing_ _at_ _all_ when asked to perform big operations and just literally ignores the request with zero feedback. This is an outcome that nobody ever wants, I promise.


Test for you to run:

1. `$ bash -c "printf 'asdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\tasdf\n%.0s' {1..4000000} > testfile.tsv"`  (testfile.tsv should be 560000000 bytes)
1. `$ code testfile.tsv`
1. Wait for file to open.
1. Cmd+Option+F (or whatever Find+Replace is on your platform)
1. Replace all instances of `a` with `Z`.
1. Go make a sandwich. Or some coffee. Or a pilgrimage. It actually doesn't matter, because vscode isn't  doing the replace anyway.

Current Platform: 
MacBook Pro (15-inch, 2019)
macOS Big Sur 11.6.1

**Comment by fiendish** [comment]
Ugh, that was with the previous version. 
The _new_ version won't even open the file now.
![Screen Shot 2021-11-04 at 9 16 21 PM](https://user-images.githubusercontent.com/201996/140442047-23c2da3c-d10d-4bb5-a753-4c034c8b6251.png)

**Comment by rebornix** [comment]
@fiendish thank you for the reproduce steps, they are really helpful. 

The underlining issue is we attempt to do a big find/replace on the whole text buffer as we found that the search results are beyond the limit (20k). Doing such regex replace on a 600MB file hits the size limit of V8 string. We would need some careful design for find replace on large files, e.g., paging but cover cases where a search result is on top of the page boundary.

**Comment by fiendish** [comment]
What if vscode came with a copy of sed and asked it to do the find/replace on vscode's behalf? :)
