### ISSUE TITLE
[Getting Started] Provide when clauses for workspace tags

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#121778]
To make walkthroughs more contextual to the currently open project, they should to be aware what kind of files/packages are in the project.

One of the best (there might be others) existing signals VS Code offers are [workspace tags](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/tags/electron-sandbox/workspaceTagsService.ts). If they would be available in `when` clause context, walkthroughs (and other UI elements) could adapt to that to show additional extensions, settings or specialized features.

cc @jureid @JacksonKearl

**Comment by digitarald** [comment]
Via @chrisdias: Workspace tagging happens in `LifecyclePhase.Eventually`, so the information would only be available after some delay. The other risk is that it would be adding a dependency workspace tags, making later changes harder.

The way [config](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/extensions/browser/configBasedRecommendations.ts)/file extension recommendations work, using file patterns, could be more generic.

**Comment by JacksonKearl** [comment]
Discussed w/ @kieferrm, considering modifying this to instead give priority to walkthroughs based on files present in workspace. So a TS walkthrough might be top-of-list when `./tsconfig.json` exists, and a Java walkthrough is top-of-list when `./Ant.xml` exists.

**Comment by digitarald** [comment]
> considering modifying this to instead give priority to walkthroughs based on files present in workspace.

For many cases we would duplicate the signals that extensions use to get activated. This could also the existing signal for when a language extension activated because of files in a workspace – combining the `workspaceContains` and `onLanguage` _activationEvents_. Or are there cases when these activation reason could be misleading?

**Comment by JacksonKearl** [comment]
Scoped this down to be getting started specific. With next insiders, walkthroughs will be able to declare a `featuredFor` array of globs, when one matches the walkthrough will be promoted to "featured" status, meaning it ranks higher in the list of walkthroughs, has a star on its tile, and renders its description directly on the welcome page.

**Comment by jureid** [comment]
@JacksonKearl - for C++, our scenario is that we would change the steps within the walkthrough depending on workspace files (example: if CMakeLists.txt is present, we show the step to install CMake Tools). Should we achieve this by creating separate walkthroughs (one that has the Install CMake Tools step, one that doesn't) and using the featuredFor property?

**Comment by JacksonKearl** [comment]
Yes, they would both show up with different ranks. Would it be possible to note in the step's description that the step is only relevant to folks using CMake?

**Comment by digitarald** [comment]
@JacksonKearl the featuring is a nice feature to highlight walkthroughs. Could we also address the need for C++ and for other walkthroughs that need to hide/show steps based on workspace/environment in the same issue, or should I file a new one?

**Comment by jureid** [comment]
> Yes, they would both show up with different ranks. Would it be possible to note in the step's description that the step is only relevant to folks using CMake?

I think it would be a much better experience to hide/show steps based on if there's a CMakeLists.txt rather than showing all steps and updating the descriptions. The fewer steps in a walkthrough, the better. It's not just that we'd add a step if CMakeLists.txt is present, there are a few steps we'd hide.

**Comment by alexr00** [comment]
What's the best way to verify this?

**Comment by jureid** [comment]
@JacksonKearl - I'm just catching up on this. Is the featuredFor property available?
