### ISSUE TITLE
Task Terminals (i.e. "Ensure Prelaunch Dependencies") now always visible

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#121762]
When running vs code, it's long been the case that you get an extra "task terminal" sticking around with some "Terminal will be reused by tasks, press any key to close it." text in it. This was generally fine as it was tucked away in the select box, but now it's always visible in the terminal tabs view:

![image](https://user-images.githubusercontent.com/8586769/115443013-8fea6880-a1c7-11eb-82e8-04bd79b73096.png)

Wondering if we should maybe revisit this, as it's a bit more noisy now?

**Comment by alexr00** [comment]
Sounds like https://github.com/microsoft/vscode/issues/112230. 
Now that we have terminal tabs, it does seem needed.
