### ISSUE TITLE
[themes] change the file icon or theme in API

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#12178]
**Themes** :
1. Where does code store current applied theme ?
2. Where does code store all installed themes ?
3. How to get them via API in extension ?

**File Icons** :
1. Where does code store current applied file icon ?
2. Where does code store all installed file icons ?
3. How to get them via API in extension ?

_P.S : I need it for my Code Settings Sync extension_

**Comment by shanalikhan** [comment]
ok thanks, i hope its in backlog to allow extensions to change the Icons or themes

**Comment by Jonatino** [comment]
+1

**Comment by shanalikhan** [comment]
There are above 150 votes for this feature.
Any update when it will be done, i wish to have this on March mildstone

**Comment by aeschli** [comment]
#7358 will solve your problem. You can already try it in the [insiders](https://code.visualstudio.com/insiders) build.

To get a list of all installed theme, iterate over the packageJSON of all extensions (vscode.extension.all.forEach(e => e.packageJSON.contributes ....)
