### ISSUE TITLE
Add Ubuntu icon as default for detected WSL Ubuntu profile

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121737]
Blocked on https://github.com/microsoft/vscode-codicons/issues/61

**Comment by misolori** [comment]
Added `terminal-ubuntu` to Codicons via 1e6315f7059c803d17e12ee35938ecec5aedf06b

<img width="133" alt="CleanShot 2021-04-20 at 10 02 07" src="https://user-images.githubusercontent.com/35271042/115436189-91179780-a1bf-11eb-98c6-0bbe8578c344.png">
