### ISSUE TITLE
[themes] Different icons for Java files: Class, Interface, Enum etc.

### ISSUE THREAD

**Issue by danikgan** [microsoft/vscode#121731]
Currently, all Java files have the same icon (red cup). VS Code only changes icons based on filename extension and not content. It would be beneficial to distinguish between an interface or a class in Java, however. Of course, VS Code is a generic application suitable for many languages, primarily, JavaScript and C++. However, if VS Code were to compete with IntelliJ, then such a feature is a must-have, because, otherwise, the plugin can pretty much cover most of the feature set.

Possible duplicate of https://github.com/redhat-developer/vscode-java/issues/1750

**Comment by aeschli** [comment]
We currently have no plans for such a feature.

**Comment by Noctumsempra** [comment]
So this will never be a feature?

**Comment by jarhuba** [comment]
Please, implement this feature. It's really missing thing.

**Comment by MarlonDevio** [comment]
At the moment, as strange as it may sound, the only thing that's making me not use vscode instead of jetbrains is the file icons for java... I bet I'm not the only one
