### ISSUE TITLE
Move DropdownWithPrimaryActionViewItem IE ButtonDropdownSplitActionViewItem into base 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#121785]
For reuse by other code areas

**Comment by meganrogge** [comment]
Also polish styling including a hover over the joint buttons

**Comment by Tyriar** [comment]
Mockup:

![image](https://user-images.githubusercontent.com/2193314/115575823-c7185280-a277-11eb-9d13-6d97062b57f6.png)

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/121836
