### ISSUE TITLE
C# syntax coloring bug with top-level statements

### ISSUE THREAD

**Issue by sandyarmstrong** [microsoft/vscode#121770]
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Write a program using [C# 9 top-level statements](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#top-level-statements).
2. Put `else` clause's statement on same line as the `else`.

Both the `else` and the statement will be colored incorrectly. In this example, you can see `else`, `Console`, and the string are all wrong. Put them inside the context of a method and everything colors correctly again.

My 10 year old noticed this while he was learning a little C# this weekend. It made him think his code was wrong.

![image](https://user-images.githubusercontent.com/155076/115458133-317ab580-a1da-11eb-995b-ead715e46694.png)

https://microsoft.github.io/monaco-editor/index.html does not seem to have the same bug, if that's helpful. It's also not present here on GitHub.

```csharp
using System;

// Bug only seems to occur when using C# 9 top-level statements
// https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#top-level-statements
if (true) {
    Console.WriteLine("normal syntax coloring");
}
else Console.WriteLine("buggy syntax coloring");

if (true) Console.WriteLine("normal syntax coloring");
else Console.WriteLine ("buggy syntax coloring");

// It looks correct if it's wrapped in a method
static void Foo()
{
    if (true) {
        Console.WriteLine("normal syntax coloring");
    }
    else Console.WriteLine("buggy syntax coloring");

    if (true) Console.WriteLine("normal syntax coloring");
    else Console.WriteLine ("buggy syntax coloring");
}
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandyarmstrong** [comment]
Another example:

![image](https://user-images.githubusercontent.com/155076/115458864-2d02cc80-a1db-11eb-874b-95ad864ae7b9.png)

Every word on the `else if` line is colored incorrectly.

**Comment by sandyarmstrong** [comment]
@JoeRobich should these sorts of bugs be filed in https://github.com/dotnet/csharp-tmLanguage instead?

**Comment by abock** [comment]
Have you tried with C# semantic highlighting enabled? That should use the actual language service (and thus Roslyn) to richly color your document. Unfortunately it defaults to `false`.

```json
…
"editor.semanticHighlighting.enabled": true,
…
```

<img width="694" alt="image" src="https://user-images.githubusercontent.com/49539/115464898-c510ae00-a1fb-11eb-83e3-b940e605c456.png">

**Comment by sandyarmstrong** [comment]
@abock with semantic highlighting enabled, the bug goes away, and behavior is more consistent with Visual Studio. This is why I assume the issue is with the tmLanguage file.

**Comment by JoeRobich** [comment]
> @JoeRobich should these sorts of bugs be filed in https://github.com/dotnet/csharp-tmLanguage instead?

That is the right place.

**Comment by sandyarmstrong** [comment]
@gjsjohnmurray how is this a C# extension bug if I can reproduce with the C# extension disabled?

**Comment by gjsjohnmurray** [comment]
@sandyarmstrong sorry, I misunderstood the exchange you had with @JoeRobich

@alexr00 please reopen if appropriate and remove incorrect label.

**Comment by alexr00** [comment]
@sandyarmstrong thanks for filing the issue in https://github.com/dotnet/csharp-tmLanguage/issues/203. I usually pull grammar updates from the upstream repos once per month, so if/when the issue gets fixed it will get pulled into VS Code soon.

To track grammar issues like this I usually link to the upstream issue then close the issue in Microsoft/vscode, so I'll just set the labels on this issue.
