### ISSUE TITLE
vscode tries to restore packages evert 1 minute

### ISSUE THREAD

**Issue by r105m** [Microsoft/vscode#12173]
after updating to 
Версия 1.5.2
something with restoring packages of aspnet project was broken
vscode tries to restore packages even if i restored packages before by command line. and c# plugin intellisence is not working.

please stop broking vscode

**Comment by bpasero** [comment]
Reading your description it seems that the issue originates from an extension and not VS Code itself. Thereby I will close this issue and kindly ask you to report this issue against the extension repository. 

Most extensions are on GitHub as well so it should be easy to file it against the extension. If you open an extension on the market place, click on the **Support** link to find out more.

<img width="196" alt="screen shot 2016-05-05 at 12 51 17" src="https://cloud.githubusercontent.com/assets/900690/15041943/263e2282-12c0-11e6-9a33-d2b3b500d61b.png">

Thanks again for your feedback!
