### ISSUE TITLE
Allow engines.vscode to target Insiders versions more precisely

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#121749]
At the moment, the `engines` only targets a generic "insiders". This can cause issues when developing extensions that are in-use against evolving APIs in Insiders. I've hit this when dealing with testing APIs, and I know the Python people have hit this dealing with notebooks. In some cases it's possible to feature-detect on APIs, but this can be messy and is not always straightforward.

Optimizing for a case where updated extensions are released before the Insiders build is available, I propose adding an RFC3339 date tag that would -- in absence of other good markers -- specify the minimum build timestamp the extension is compatible with.  For example, this would match any >=1.56.0 Insiders or Stable builds that happen after the current time:

```
"engines": {
  "vscode": "^1.56.0-2021-04-20T16:25:37.971Z",
},
```

(this is not cosmetically very nice, but it appears to be valid semver. A unix timestamp would be more compact, but is not human readable)

A nicer way would be to use git commits, but unless we embed commit history in builds we can't say "any build after a certain hash".

**Comment by connor4312** [comment]
Actually, we can follow TypeScript's style. They have versions like `4.3.0-dev.20210428`, so we could do `^1.56.0-insider.20210428`

**Comment by connor4312** [comment]
fyi @DonJayamanne since your team may want to use this

**Comment by DonJayamanne** [comment]
Not sure what this buys extension users. If a user has the latest VS Code insiders installed, & the extension targets the previous days build, then the extension doesn't load.
Isn't it the same as extension not loading due to errors?
