### ISSUE TITLE
UI : confused about difference between view, sidebar, and panel

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121764]
@isidorn

 Perhaps these references make sense to someone who can see, but as a totally blind screen reader user, seeing references to sidebar, view, and panel confuse me.

Sidebar and panel seem to be presentational references, view seems to be a more semantic reference.

For instance, the view menu has a "run" entry and when I activate it, focus lands on UI items having to do with running / debugging (makes sense). However, if I disable sidebar, this goes away. Is this a view, or a sidebar, or a view that's contained in a sidebar rather than a view not contained in a sidebar.

control+tab moves through views. Does it also move through sidebars, panels, etc?

Seems better separation between presentation and semantics might be helpful.

**Comment by isidorn** [comment]
@RichCaloggero I think these docs could help https://code.visualstudio.com/docs/getstarted/userinterface
If they do not please let us know and we will improve the docs. Also I can answer any questions if you have after reading that.

After you read that, let me know if you have any precise advice on what we should change in VS Code and I would be open for ideas. Thanks a lot!

**Comment by isidorn** [comment]
No actionable plans for this issue, thus closing.
