### ISSUE TITLE
[settingssync] [error] TypeError: Cannot read property 'configurationSync.store' of undefined

### ISSUE THREAD

**Issue by sharathdaniel** [microsoft/vscode#121709]
- VS Code Version: 1.55.2
- OS Version: Windows 10

Steps to Reproduce:

1. Turn on settings sync and sign in to github.
2. Merge or Replace: Replace local

Does this issue occur when all extensions are disabled?: Yes

When i try to merge manually (Accept Remote), ` settings.json` is not getting merged, no idea why. `extensions.json` doesn't have any issues.

`settings.json` contains 2 entries related to custom theme i have installed, would that be the reason since i haven't installed the theme?

**Comment by sandy081** [comment]
Is there an error trace available from settings sync or shared process logs available in Output panel?
