### ISSUE TITLE
Exploritory keyboard mode?

### ISSUE THREAD

**Issue by RichCaloggero** [microsoft/vscode#121740]
@isidorn

Is there a keyboard mode similar to the NVDA explore keyboard mode which will tell me the function / command bound to any key that I press?

In NVDA, press NVDAKey+1 to toggle keyboard explore mode.

**Comment by isidorn** [comment]
@RichCaloggero you can File > Preferences > keyboard shortcuts
There you can type the keybinding combination you would like to do and we should filter to commands that are bound to that keybinding.
Try it out and let me know how it goes. Thanks

**Comment by RichCaloggero** [comment]
OK, but not exactly easy or quick to use.

- you need to type the symbolic keyname (control+t)
- you then need to press tab a couple times to find the list
- you then need to explore the list
I see why you may need to do things this way -- shortcuts are context sensative.

- is there a "current context" variable / indicator you can use to filter on
- if so, allow typing the actual key and write command name / description to live region
Have no idea if this is possible / feasible.

**Comment by RichCaloggero** [comment]
OK, this is sort of implemented, but very much oddly.

- focus shortcut list
- focus on a list item (default is nothing selected / focused)
- press spacebar or enter
   + focus lands on "type desired key and press enter"
   + pressing keys now reports their definition and context
   + pressing enter redefined, escape gets you out

One oddity is that until you actually press space or enter on a shortcut item, there is no UI control to bind / rebind a key. After you press space / enter on a shortcut, then escape back to the list, pressing tab gets you a button with label "change key binding"

**Comment by isidorn** [comment]
Thanks for the feedback. So let's try to make this concise :)
Can we try to make a list of things we could improve here?

Also here are docs regarding keybindings https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by isidorn** [comment]
We have no actionable plans for this item, thus closing.
