### ISSUE TITLE
File name indentation is confusing when File Icon Theme is enabled

### ISSUE THREAD

**Issue by bemartin** [Microsoft/vscode#12170]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Enable File Icon Theme
2. Browse files

When icons are enabled, file names are pushed right and make it look like directories are expanded:
![snip_20160916161817](https://cloud.githubusercontent.com/assets/6611598/18603764/33b8d362-7c29-11e6-815c-38d19e113ab4.png)

I believe that the file icons should line up with the directory expansion arrow icon

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11762
