### ISSUE TITLE
Edit the preview image size in gutter and in the code

### ISSUE THREAD

**Issue by pepeu93** [microsoft/vscode#121724]
Im using this extension: `mushan.vscode-paste-image` to show a preview of images when you hover the mouse on its path.

In the extension docs theres nothing about the width/height of the preview thumbnail, so i assume its a vscode default option?

Is possible to edit its size? theres also a preview in the gutter, its also possible to change its size?

![image](https://user-images.githubusercontent.com/82878129/115384118-09c12880-a1ad-11eb-9af9-f807d481ec28.png)

**Comment by ccaioccesar** [comment]
> /causedByExtension

So the size of the thumbnail is generated by the extension?
