### ISSUE TITLE
The specified item could not be found in the keychain

### ISSUE THREAD

**Issue by john-aws** [microsoft/vscode#121742]
- VS Code Version: 1.55.2 (2021-04-13)
- OS Version: Mac OS X Mojave 10.14.6

Steps to Reproduce:

1. enable preferences sync
2. authenticate to hotmail and github
3. problem doesn't occur immediately, but I see this error message in every VS Code window, every morning. Often it appears multiple times (see image).

![image](https://user-images.githubusercontent.com/3178883/115414121-c625e900-a1c3-11eb-924d-dbda6bbabc3a.png)

This was also raised as https://github.com/microsoft/vscode/issues/95701 and closed as no repro. I'm here to provide evidence that it reproduces with v1.55.2. (I was unable to update the original bug report as it's locked).

PS the referenced [Troubleshooting Guide](https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues) does not mention this error.

**Comment by TylerLeonhardt** [comment]
Hi @john-aws 👋 I'm the new owner of the Auth stack. Just to do some bookkeeping, I'm wondering if you are still seeing this issue?
