### ISSUE TITLE
Remove multiple or all forwarded ports 

### ISSUE THREAD

**Issue by renkun-ken** [microsoft/vscode#121780]
If a process creates an http server at a random port and I need to forward the port each time, there will be a lot of forwarded ports along the time. I wonder if it makes sense to add a button or command to clear all forwarded ports, or remove multiple selected ports in the ports view?

<img width="921" alt="image" src="https://user-images.githubusercontent.com/4662568/115483707-e2895a80-a283-11eb-93dc-8f9ce718fa76.png">

**Comment by alexr00** [comment]
If you turn on port auto forwarding with the setting `remote.autoForwardPorts`, and set the port source (`remote.autoForwardPortsSource`) to `process`, you should get some better behavior here. The ports will be automatically forwarded and unforwarded when the process that listens on the port start/stops.

**Comment by renkun-ken** [comment]
I set `remote.autoForwardPortsSource` to `process` but it still does not remove the ports when the process stops.
The ports are forwarded by `vscode.env.asExternalUri` (https://github.com/microsoft/vscode/issues/102449#issuecomment-744405611). When the process is ended, the ports are still there.

**Comment by alexr00** [comment]
Ah. That makes sense then, thanks for the explanation. The manual forwarding through `asExternalUri` probably happens first (the auto forwarding is on a slight delay), so then they count as manually forwarded and don't get removed.

**Comment by alexr00** [comment]
@joaomoreno, how would you feel about allowing a column label to be more than just a string? It seems like an "x" in the column header would be a nice UX for remove all.

**Comment by renkun-ken** [comment]
![image](https://user-images.githubusercontent.com/4662568/115534203-21420380-a2ca-11eb-999b-1c60c7593481.png)

Adding a button next to "Add Port", or adding a menu item to the context menu, or as you suggest, adding an "x" to the column header, all seem to make good sense to me.

**Comment by dtasev** [comment]
Closing a port seems to take a few seconds (~5s) for me. Unsure if that's the case for everyone but if so it might be worth adding some kind of a progress bar otherwise it looks like the whole app is frozen.

**Comment by renkun-ken** [comment]
>Closing a port seems to take a few seconds (~5s) for me

Also takes me ~2s most of the time. I wonder if dropping all forwarded ports would take tens of seconds?

>In the meantime - is there a non-UI way of closing all ports?

Does it make sense to have an option not to recover forwarded ports when a remote session is recovered. In my use case, I don't really need those forwarded ports in history.

**Comment by alexr00** [comment]
You can disable port restore with the setting `remote.restoreForwardedPorts`

**Comment by dtasev** [comment]
Wish I had checked here a few minutes ago as I just manually deleted all the 280 ports I've acquired over time 😄 It seems that you can continue clicking the X for deleting even while the UI is frozen - and the ports get deleted after a bit. 

The deletion massively sped up as the port count went down, seems like there may be some excessive work being done when the port count is 100+

**Comment by alexr00** [comment]
@dtasev there was a perf issue with the view, but it should be fixed in insiders. What version of VS Code are you on?

**Comment by renkun-ken** [comment]
> You can disable port restore with the setting `remote.restoreForwardedPorts`

Thanks! That's exactly what I'm looking for.

**Comment by dtasev** [comment]
@alexr00 I wouldn't have that yet, but great to know it's already been addressed, I stay on the main releases :) From the About:

```
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by joaomoreno** [comment]
> @joaomoreno, how would you feel about allowing a column label to be more than just a string? It seems like an "x" in the column header would be a nice UX for remove all.

I don't mind augmenting the column rendering feature, but I'm not so sure that would be a good place for it. Why not enabling multiple selection and pressing <kbd>Delete</kbd>?

**Comment by alexr00** [comment]
It's less discoverable, but simple, and <kbd>Delete</kbd> is already supported for individual . I'll look into multiselect.

**Comment by alexr00** [comment]
To verify, use the Ports view to:
1. Forward some ports.
2. Multi select some ports.
3. Right click and "Stop Forwarding Port"
4. Multi select some more ports.
5. Use the "delete" key to stop forwarding the ports.

**Comment by renkun-ken** [comment]
I could confirm that the Ports view in the latest insider build work quite well. Thanks!

**Comment by alexr00** [comment]
@renkun-ken thanks for verifying!
