### ISSUE TITLE
Tab width detection unreliable

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#121739]
Issue Type: <b>Bug</b>

Switching back and forth between documents with different indentation confused VS Code and breaks indentation.

In my showcase scenario, I have a `.py` file, with 4 spaces as indentation. Next to it, I have a `Dockerfile` with tabs as indentation.

When I open the `.py` file, the tab indicator will incorrectly show "Tab Size: 4". I click on it and select "Detect indentation from Content". The tab size indicator changes to "Spaces: 4".

I now open the `Dockerfile`. The tab size indicator switches correctly to "Tab Size: 4".

I switch back to the `.py` file. The tab size indicator now incorrectly shows "Tab Size: 4".

Newly added lines will use tabs for indentation. Even though the entire file uses spaces.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (31.91GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/oliver/fairmanager/fairmanager/core-web3 --remote=wsl+Ubuntu --crash-reporter-id 05565d81-cfc4-40de-88df-1c479bbe1bcd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (32.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (32.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (32.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (32.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3591)|
|Memory (System)|50.11GB (32.79GB free)|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
eslint-disable-snippets|drK|1.3.0
tsl-problem-matcher|eam|0.4.0
output-colorizer|IBM|0.1.2
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
vscode-icons|vsc|11.4.0
vscode-zipfs|arc|2.3.0
vsc-prolog|art|0.8.23
better-toml|bun|0.3.2
vscode-eslint|dba|2.1.20
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
generateuuid|Fir|0.0.5
shell-format|fox|7.1.0
vscode-graphql|Gra|0.3.15
terraform|has|2.10.0
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
template-string-converter|meg|0.4.7
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
vscode-paste-image|mus|1.0.4
monolit|Oli|0.0.29
vscode-yaml|red|0.18.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
Regarding the suggested duplicate, I also have Prettier installed, but this reproduces with Prettier disabled.

**Comment by alexdima** [comment]
VS Code extensions can change the indentation settings of a text document. I see you have it installed, it is very likely that the `EditorConfig` extension is changing your indentation based on its rules.

**Comment by oliversalzburg** [comment]
It seems like you're right. I'll try to keep this in mind.
