### ISSUE TITLE
Codefolding independent from indents 

### ISSUE THREAD

**Issue by daslicht** [microsoft/vscode#121794]
Please make codefolding independent from the indents like it is possible in Dreamweaver:

```
     <div>
<?
echo "the enclosing div is NOT foldable";
?>
     </div>
```

**Comment by aeschli** [comment]
Our HTML support already support language aware folding, but it only can do this if the syntax is proper HTML.
`<?` is not a valid HTML tag.

Likely you are using a templating language. Is it PHP? You need to look out for a language extension that supports the templating syntax.

**Comment by daslicht** [comment]
Thank you for the suggestion , I found a extension to suit my application , yeh !
