### ISSUE TITLE
Electron 12 is buggy with `Page.waitForDebugger`

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#121775]
js-debug issues `Page.waitForDebugger` when it first attaches so that it can make sure all breakpoints are set correctly before execution happens. However this seems to be hit and miss in Electron 12. Often I'm seeing that the renderer never responds to their request, even after we issue `Runtime.runIfWaitingForDebugger`.

I hit this most often in unit tests, and can reproduce it pretty consistently on both my OSX and Windows machine if I set breakpoints before running tests. If I make a build that doesn't issue this command, the issue goes away.

**Comment by deepak1556** [comment]
Haven't seen this issue with recent versions, closing for now.
