### ISSUE TITLE
Version 2021.6.755784270 does not install on latest VSC release 1.55.1

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121757]
@rjl9 commented on [Mon Apr 19 2021](https://github.com/microsoft/vscode-jupyter/issues/5561)

Version 2021.6.755784270 does not install on latest VSC release 1.55.1. Currently version 2021.6.755784270 is pushed "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter" as the latest stable release. This renders other extension like Pylance unusable for VSC installations that are offline (without access to preview versions). The latest working version for the stable release of VSC 1.55.1 is 2021.5.745244803. Why is 2021.6.755784270 pushed as the latest supported version when it breaks on the latest stable version of VSC? I would have expected 2021.5.745244803 to have been the latest on "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter" and the 2021.6.755784270 (which requires a non-stable insider VSC) to remain in a dev channel until ready for stable/production release of VSC to match it.

---

@hancockjt commented on [Tue Apr 20 2021](https://github.com/microsoft/vscode-jupyter/issues/5561#issuecomment-823354812)

And how do we obtain the .vsix (compiled) version that works on the released VS Code 2021.5.745244803? I tried downloading the source. Build attempt came up with 9500+ build errors. The devcontainer workspace in the source didn't help.

This latest "release" has rendered the python extension dead and useless on my offline (closed network) VS Code instances.

---

@DonJayamanne commented on [Tue Apr 20 2021](https://github.com/microsoft/vscode-jupyter/issues/5561#issuecomment-823398338)

Thanks for filing this issue.

> Why is 2021.6.755784270 pushed as the latest supported version when it breaks on the latest stable version of VSC? I would have expected 2021.5.745244803 to have been the latest on

This vsix targets 1.56.0-insiders. Hence VS Code should not download this. This is a feature supported by VS Code where one can publish multiple VSIX each targeting different VS Code versions.

I am cetain this is a problem with VS Code, possibly another variation of https://github.com/microsoft/vscode/issues/119073

To be better able to assist you ( @hancockjt, @rjl9) , please could you provide the following information:

* OS
* Environment - Remote Containers/SSH/WSL?
* How are you installing this?
	* Are you in VS Code and just downloading Python from the VSCode maretplace?
	* Or are you downloading Python extension manually and then attempting to install it in VS Code?

---

@DonJayamanne commented on [Tue Apr 20 2021](https://github.com/microsoft/vscode-jupyter/issues/5561#issuecomment-823469716)

> s the latest stable release. This renders other extension like Pylance unusable for VSC installations that are offline (without access to preview versions)

Ok, i think i understand the issue now.
I believe you are going into the marketplace and downloading this from the browser.
I believe this is an issue for VS Code to address, they need to provide some information about the VS Code engine the extension is associated with.

**Comment by DonJayamanne** [comment]
I believe this is an issue for VS Code to address, we need to provide some information about the VS Code engine the extension is associated with.

@sandy081 /cc

**Comment by rjl9** [comment]
@hancockjt:
I just modified the url from the marketplace download file to get the version that works with the 1.55.1 release. this is what I used to get our shop back up and running. https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.5.745255803/vspackage .  I just manually installed the vsix using code --install-extension <path to downloaded vsix file>

@DonJayamanne : 
we are on a closed network detached from the internet, running Windows 10 20h2 Enterprise, (non container/WSL). Because it is a closed network, we are manually installing all extensions via vscode cli (code --install-extension). When we decide to upgrade versions, we download the latest vscode at that time (zip), along with all of the latest required extensions (from the marketplace) to minimize the possibility of having a vscode extension that is unsupported by latest version.

**Comment by VerbF** [comment]
> @hancockjt:
> I just modified the url from the marketplace download file to get the version that works with the 1.55.1 release. this is what I used to get our shop back up and running. https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.5.745255803/vspackage . I just manually installed the vsix using code --install-extension
> 
> @DonJayamanne :
> we are on a closed network detached from the internet, running Windows 10 20h2 Enterprise, (non container/WSL). Because it is a closed network, we are manually installing all extensions via vscode cli (code --install-extension). When we decide to upgrade versions, we download the latest vscode at that time (zip), along with all of the latest required extensions (from the marketplace) to minimize the possibility of having a vscode extension that is unsupported by latest version.

The version: v2021.5.745244803. could be useful.

**Comment by Stephanevg** [comment]
Hi,

I posted this already [here](https://github.com/microsoft/vscode/issues/119073#issuecomment-825560211), but the ticket was actually closed.

here it is again: 

Hi guys, I do have the same issue as @bjayakumar 

In my case, I am not even remote. This is a fresh VSCode installation, followed immediatley by the installation of my-python.python extension.

I wanted to run a python debugger, and had a message saying i needed ``ms-toolsai.jupyter`` exension. 

I went ahead with that, and it said that it is not compatible with vscode '1.55.2'. 

(I have done all the installation offline, as i need this on a server that doesn't have internet access).

I am blocked, as I cannot run a debug mode for any pythong script. Please advice on how to fix this.


ms-python.python

![image](https://user-images.githubusercontent.com/6302961/115857586-26b85e80-a42e-11eb-9367-fadae7782cf9.png)


![image](https://user-images.githubusercontent.com/6302961/115857096-8f530b80-a42d-11eb-9625-476db899605e.png)

![image](https://user-images.githubusercontent.com/6302961/115857162-a3970880-a42d-11eb-8327-d45b49ffd829.png)

ms-toolsai.jupyter --> 2021.6.777186939

**Comment by rjl9** [comment]
@Stephanevg I had the same as you, with no internet access to install. Inorder to get the required jupyter package installed in 1.55.2 I grabbed an earlier version from here `https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.5.745255803/vspackage` and manually installed the vsix on the box without internet access. That should get your python working again.

**Comment by Stephanevg** [comment]
Thanks @rjl9 for sharing this! :)
Your link actually points to a just a json file. Nothing i can really download.

> I have tried downloading one or two from here -> https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter (Click on version history, and just the second last one, and than a random one). none of it actually worked.

Is there maybe an exact version I should use? (have a direct link perhaps?

**Comment by rjl9** [comment]
@Stephanevg Im really sorry about that, that was a copy paste error. 

give this url a try it should give you the vsix for the version that worked for me:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.5.745244803/vspackage

**Comment by Stephanevg** [comment]
Awesome! that actually worked for me!
I could install the ms-toolsai.jupyter, restart vscode, and could (finally) start debugging my python script.
Thank you SO much for you guidance @rjl9 👍 👍

**Comment by rjl9** [comment]
@Stephanevg the problem with the marketplace is they only offer the last 5 versions. Unfortunately, the version that works is older then the 5 latest ones that are on the marketplace website. I kept rolling back the version of the plugin until i found one that worked with 1.55.2 ( which is 2021.5.745244803) and then used the marketplace api to download the vsicx file.

you can do this same thing for any package in the marketplace using the api with this url:
`https://marketplace.visualstudio.com/_apis/public/gallery/publishers/$publisher/vsextensions/$package/$version/vspackage`

**Comment by rjl9** [comment]
@Stephanevg Glad I could help! 👍🏻

**Comment by hancockjt** [comment]
I actually dealt with this by copying the entire (extracted) extension folder from a working, Internet-connected VS Code instance to a removable media, then pasting it to the target instance on the closed network.

**Comment by sandy081** [comment]
@DonJayamanne Sorry for getting on to this late. Can you please help me in understanding the issue here? Is it that users are downloading the extension vsix from marketplace and trying to install on VS Code stable which fails as the vsix is not compatible?

**Comment by DonJayamanne** [comment]
> downloading the extension vsix from marketplace and trying to

Yes that's right.
Fyi, Jupyter extension releases extensions that target vscode insiders, and these are pushed every weekday.

**Comment by sandy081** [comment]
Then it seems VSC (stable and insiders) is working as expected. 

May I know what is expected here?

**Comment by hancockjt** [comment]
IMHO the "download extension" link should only download a vsix that will run in a stable, released version of VSC. The latest dev branch build could be downloadable from the source repo in GitHub.

**Comment by sandy081** [comment]
@hancockjt May I know the link you are mentioning about is the one from Marketplace website?
