### ISSUE TITLE
The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 4294967295).

### ISSUE THREAD

**Issue by aquawolf6** [microsoft/vscode#121720]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Please help me when I try and run my python code in vs code this message pops up: The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 4294967295).

**Comment by aquawolf6** [comment]
now my vs coder says The terminal process failed to launch: Path to shell executable "C:\WINDOWS\System32\wsl.exe" does not exist. when i am trying to use windows not linux

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by atrantan** [comment]
Got the same issue.

**Comment by aquawolf6** [comment]
now it is saying The terminal process failed to launch: Path to shell executable "C:\WINDOWS\System32\wsl.exe" does not exist.

**Comment by tymsai** [comment]
does " wdl.exe " exist in that path?

**Comment by aquawolf6** [comment]
How do I check it

**Comment by tymsai** [comment]
`C:\WINDOWS\System32\wsl.exe` ;

Goto ` C Drive ` then `WINDOWS` then `System32` , in the `system32` folder you should find `wsl.exe` ;
See & tell if it exists or not in that path.

**Comment by aquawolf6** [comment]
I could not find it in there

**Comment by aquawolf6** [comment]
What?

**Comment by tymsai** [comment]
> I could not find it in there
> their was no wsl.exe
> the thing is i am trying to use it on windows not linux so why does it say windows subsystem linux
> ![problem](https://user-images.githubusercontent.com/75192484/115979343-c0b40e80-a5c8-11eb-90d2-1d5fe83f9491.PNG)

did you search in start menu also ? for `wsl.exe`

**Comment by aquawolf6** [comment]
how do i search start menu, sorry i don't really know much it is for school

**Comment by tymsai** [comment]
> how do i search start menu, sorry i don't really know much it is for school

download it from a TRUSTED source and put it in that folder

**Comment by aquawolf6** [comment]
download what
sorry again

**Comment by tymsai** [comment]
wsl.exe

**Comment by tymsai** [comment]
did you configure environment variable

**Comment by aquawolf6** [comment]
what is that

**Comment by tymsai** [comment]
Please refer to these links :
1.https://github.com/microsoft/WSL/issues/5415
2.https://www.gitmemory.com/issue/microsoft/WSL/5415/644555955
3.https://www.programmersought.com/article/62718109901

**Comment by aquawolf6** [comment]
Thanks for you help but I just reset my laptop and it worked
