### ISSUE TITLE
Keys J and K are invalid in container

### ISSUE THREAD

**Issue by wschin** [microsoft/vscode#121771]
Issue Type: <b>Bug</b>

VSCode terminal cannot browse result of "git diff" using keys "J/K" in container.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.15.0-1103-azure
Remote OS version: Linux x64 4.15.0-1103-azure
Remote OS version: Linux x64 4.15.0-1103-azure
Remote OS version: Linux x64 4.15.0-1103-azure
Remote OS version: Linux x64 4.15.0-1111-azure

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
