### ISSUE TITLE
Hold ⌘-Q to Quit

### ISSUE THREAD

**Issue by jsoref** [microsoft/vscode#121730]
It's a bit too easy to accidentally trigger cmd-q (instead of cmd-tab). Chrome protects against this with:
http://googlemac.blogspot.com/2011/06/q-i-didnt-mean-to-do-that.html
![image](https://user-images.githubusercontent.com/2119212/115393445-b3a1b480-a1af-11eb-93f7-d5d98e7a02a3.png)

It'd be nice if VSCode offered the same feature.

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by DarioBosco** [comment]
How does this not have 20 upvotes already? This could be so useful...
