### ISSUE TITLE
Terminal tabs inconsistent behavior with multi-folder workspaces

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#121748]
Version: 1.56.0-insider
Commit: 8aff878db2542eea2dfb571c8bb485118bbb3113
Date: 2021-04-19T05:13:43.644Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:

Click the `+` to create a new tab. You get this quick pick to pick which workspace:
![image](https://user-images.githubusercontent.com/2644648/115428005-d1264c80-a1b6-11eb-8cc0-c4f6ac082c5d.png)

Now click the `v`. You get this quick pick (which makes sense!):
![image](https://user-images.githubusercontent.com/2644648/115428122-eb602a80-a1b6-11eb-9b2e-ae200c15aee6.png)

But clicking on one of those does not give me the multi-workspace quick pick, it just starts a terminal with that shell in the active workspace:
![image](https://user-images.githubusercontent.com/2644648/115428238-0af75300-a1b7-11eb-8c6e-b393067c693d.png)

I think the second action needs to also provide the multi-root quick pick.

**Comment by meganrogge** [comment]
Thanks, the quick pick was a temporary thing. Try in tomorrow's insiders and let me know if you still see a problem
