### ISSUE TITLE
Feature Usability and Discoverability in vscode/Jupyter Notebooks: Menu Items

### ISSUE THREAD

**Issue by cassieview** [microsoft/vscode#121766]
## Environment data

Version: 1.56.0-insider (user setup)
Commit: b4816cfd1f4161a3bb272354d181a9947760ee26
Date: 2021-04-20T07:23:51.425Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behaviour

A consistent menu navigation in classic Jupiter notebooks to notebooks in vscode, or an option to use a classic jupyter navigation menu.

## Actual behaviour

The Jupyter nav menu is hard to find and the icons are not ubiquitous making it difficult to know what the menu item is without hovering over it.  This obfuscates the additional and useful tooling that running notebooks in vs code provides. It can cause users to go back to classic notebooks because their natural dev flow is fragmented.  The tooling in the vscode notebooks is amazing but it will not fully get adopted from the community if you have to drastically change your dev flow to use it. 

Current vscode menu:
![image](https://user-images.githubusercontent.com/46505951/115447891-9f28e080-a1de-11eb-997b-56c63ae80f4e.png)

Current jupyter classic menu:
![image](https://user-images.githubusercontent.com/46505951/115447972-bc5daf00-a1de-11eb-9e0c-8a7283767564.png)

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

</p>
</details>

**Comment by chenlomis** [comment]
I had similar struggles while I was trying out the VSC experience as well
It took me some time to realize where the toolbar is 
![image](https://user-images.githubusercontent.com/30876406/115467143-e49cdc00-a1e5-11eb-909d-67acacbc7e85.png)

**Comment by siva-msft** [comment]
I agree, it was pretty hard to find the tool tray. More so, because it is in the right corner of the screen (where at least my eyes never go to naturally).

The icons themselves at first, seemed like they were too few (given that Jupyter has the conventional tool tray with all possible options); users who are accustomed to classic notebooks tool tray would certainly complain about VS code's tool-tray.

A few more points: 
- The order of the icons also look random - like, Run cell and restart should be placed adjacent; wondering why they are separated by "clear cell output".
- Also, the icon for "Export as" is not intuitive - I was checking out all the places before I finally figured out where it is.

**Comment by siva-msft** [comment]
Another suggestion that might work is adding an option "Jupyter" on the Menu bar (adjacent to "Help") which could contain many of the options that are available in the classic Jupyter tool-tray. At least it would take off a lot of cognitive tax of having to move the mouse around, hover over the icons and figure things out, is what I feel.

**Comment by misolori** [comment]
We've introduced `notebook.globalToolbar` which allows you to show the toolbar inside of the editor:

<img width="585" alt="CleanShot 2021-06-28 at 12 36 03@2x" src="https://user-images.githubusercontent.com/35271042/123693822-6aa05900-d80d-11eb-9d05-f41e30d04943.png">


<img width="1153" alt="CleanShot 2021-06-28 at 12 35 41@2x" src="https://user-images.githubusercontent.com/35271042/123693787-5d836a00-d80d-11eb-8217-a8c654f686a6.png">

So I think it's safe to close this issue. Thanks for the feedback!
