### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by pbasgowin** [microsoft/vscode#121806]
Hi, VS doesn't show the terminal, says: The terminal process "C:\WINDOWS\System32\wsl.exe" failed to launch (exit code: 4294967295).

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal
