### ISSUE TITLE
Please take a look at the latest terminal function improvement suggestions! Thank you!

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#121801]
Of course, this is not a bug, it is a suggestion, but I can't find the entry to send the suggestion, so I sent you this suggestion in the name of a bug. If you can't handle it, I hope you can help forward it to the relevant person. Thank you!
Description:
![vacode20210421](https://user-images.githubusercontent.com/54253524/115529189-45e7ac80-a2c5-11eb-8853-aa862e839668.png)

Changing the display mode in the lower right corner to the display mode of the flat tab will display more beautiful and reasonable display, and it can also keep the previous user habits and UI style without major changes, and it will not affect the code writing of the terminal editor. The space also looks more comfortable and natural.
       vscode development: contributors, I hope you can seriously consider and adopt this plan. It took me a lot of time to draw this sketch and send it to you. Thank you!

**Comment by Tyriar** [comment]
We've gone through several iterations of this over years and this is what we landed on. I'm not saying a horizontal layout won't happen at some point but the vertical tabs is what we're going with initially. You might also be interested in pulling the terminal's into the editor area when we support this.

More info in https://github.com/microsoft/vscode/issues/10546
