### ISSUE TITLE
When terminal.integrated.showTabs===true the new drop down menu options do not include the old terminal options

### ISSUE THREAD

**Issue by acotty** [microsoft/vscode#121881]
Issue Type: <b>Bug</b>

If you set "terminal.integrated.showTabs": false then the old drop down shows the following in windows 10 (same as release build 1.55.2):
 - New PowerShell
 - New Command Prompt
 - Javascript Debug Terminal

BUT the showtab new drop down shows the following:
  - Configure Terminal Settings
  - Select Default Profile

The new showtab dropdown IMHO should include all of the old options otherwise users will spend like me this morning an hour to find the  terminal.integrated.showTabs setting and set it to false and never enable it, which is not what you want going forward.

VS Code version: Code - Insiders 1.56.0-insider (23a2409675bc1bde94f3532bc7c5826a6e99e4b6, 2021-04-21T05:13:42.491Z)
OS version: Windows_NT x64 10.0.19042

**Comment by meganrogge** [comment]
Yep thanks they will be there in tomorrow's Insider's :)
