### ISSUE TITLE
Notebook Kernel Preloads don't seem to work anymore in latest insiders

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121869]
Version: 1.56.0-insider (Universal)
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:59:06.814Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.3.0

Steps to Reproduce:

1. Was using yesterdays insiders and had IpyWidgets working partially.
2. Just udpated to todays insiders, & now nothing is working.
3. Doesn't looks like the preload scripts are working either.

FYI - I added a preload script for the NotebookController and added a `console.error` in the preload script & tha'ts not working either. Ideally we should see a message logged in the console window, but tha'ts not the case.

@jrieken @rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
With @rebornix change (306f32b) this is working for me: I see console-messages, I receive messages and now renderer can also successful send messages. 

This is my renderer preload script

```ts
// preload
console.log('loaded PRELOAD script')
declare function acquireVsCodeApi(): { postMessage(message: any): void }
const vscode = acquireVsCodeApi();
window.addEventListener('message', event => {
    console.log('[receieve in renderer]', event.data)
    vscode.postMessage('ECHO: ' + event.data)
})
vscode.postMessage('preload loaded')
```

and this is my extension side snippet 

```ts
const rundam = vscode.notebook.createNotebookController(
    'linesKernel2',
    { viewType: 'lines' },
    'Rundam',
    executeHandler,
    [{ uri: vscode.Uri.joinPath(context.extensionUri, 'out/renderer.preload.js') }]
);
rundam.description = 'description';
rundam.detail = 'detail';
rundam.hasExecutionOrder = true;

rundam.onDidReceiveMessage(e => {
    console.log('[receive in ext_host]', e)
});

vscode.commands.registerCommand('extension.helloCell', async (args: vscode.NotebookCell) => {
    rundam.postMessage('Hello from ExtHost', vscode.window.activeNotebookEditor);
});
```

**Comment by jrieken** [comment]
The only known issue on my end is https://github.com/microsoft/vscode/issues/121441

**Comment by DonJayamanne** [comment]
I think you need to try with a notebook and multiple kernels/notebook controllers (as that could be what's different when you test at your end).

Here's what I'm seeing:
* Create notebook controller with a simple preload script that has `console.error('Hello');`
* Register approx 5 notebook controllers (1 per kernelspec in Jupyter).
* Run the cell & it works successfully, however theres no output in console log.
* Switch the kernel, bingo - now we get to see `Hello` in console low.

So switching the kernel displays the message.
I.e. there's definitely something not right here.

**Comment by jrieken** [comment]
> So switching the kernel displays the message.

You mean kernel A has a preload and you switch from A to A, or do you switch from B (no preloads) to A? We only load the preloads for the selected kernel and the latter case would be expected.

**Comment by DonJayamanne** [comment]
Both A & B have preloads.
And I'm switching from A to B.
I run against A, preloads doesn't work (even though A has preloads).
Run switch to B, now preloads work (by work i mean it gets preloaded - evidenced by message in console window).

**Comment by jrieken** [comment]
> I run against A, preloads doesn't work (even though A has preloads).

This might because of the bug that a remembered selected kernel didn't fire the selection event again. Internally we rely on the same logic and when that event doesn't fire the preloads are ignore. This is working from source and should be good tomorrow.

**Comment by DonJayamanne** [comment]
Lets close this for now.
