### ISSUE TITLE
Allow keybindings to override chord keys when there is a when condition

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#12187]
- VSCode Version: Code - Insiders 1.6.0-insider (0619ede1e469ed23fbb214eaa0377625a402ca87, 2016-09-16T08:03:24.238Z)
- OS Version: Linux x64 4.4.0-31-generic, Ubuntu 16.04

Based on my testing at least on Linux, I cannot bind ctrl+k as a keybinding due to the chord keybindings. This blocks #6603 in allowing a ⌘K keybinding to clear the terminal (`"when": "terminalFocus"`). I think it's reasonable to allow overriding of the chords at the very least when there is a `"when"` condition.

Steps to Reproduce:
1. Define a keybinding as ctrl/cmd+k with a `"when"` condition
2. Try using it

**Comment by Tyriar** [comment]
@alexandrudima I can implement this if you find the proposal reasonable. `KeybindingResolver.resolve` looks like the place to do it.

**Comment by alexandrudima** [comment]
I think it is doable, all the relevant logic is in `KeybindingResolver`. There are two maps involved, `_map` and `_chords`. When registering a chord `ctrl+k ctrl+d`, the `_map` gets an entry for `ctrl+k` that lets the logic know that it is a chord, plus `_chords[ctrl+k]` gets an entry for `ctrl+d`.

So far, the code assumes that if a keybinding is the beginning of a chord it cannot be a "direct" keybinding. I have found this consistent with Visual Studio, for example.

PR + tests welcome.

**Comment by Tyriar** [comment]
We're not actually going forward with this, instead we're making the cmd+k keybinding for the terminal weight more as doing it the way proposed in the issue would be a pretty radical change in how it works.

**Comment by Novack-** [comment]
For context, I use CTRL+K for toggle comment line, and I had to manually remove ALL chord keybindings of in order to be able to use CTRL+K in editor, for my desired purpose.

**Comment by Tyriar** [comment]
@Novack- after discussing with @alexandrudima, you should not need to remove the chord keybindings as your custom keybindings should "weight more".

**Comment by Novack-** [comment]
Woot! I just tried andd it works, thank you @Tyriar!

Is this a recent change? With Code 1.6, CTRL+K keybinding did not worked until I added new rules removing the default chords which start with CTRL+K. I can remove a lot of rules from there now :)

**Comment by Tyriar** [comment]
I think it's always worked like this
