### ISSUE TITLE
Enable regular expression case changing

### ISSUE THREAD

**Issue by elkebirmed** [microsoft/vscode#12185]
- VSCode Version: 1.4.0
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. `Ctrl+H`
2. Find camelCase strings `([a-z])([A-Z])`
3. Change it to lowercase `$1-\L$1\E`

expected `fooBar` to be `foo-bar`

**Comment by sandy081** [comment]
@elkebirmed May I know what are the standards/definitions for using \L and \E in your example?

**Comment by elkebirmed** [comment]
@sandy081 [Take a look](http://www.regular-expressions.info/replacecase.html)

**Comment by elkebirmed** [comment]
Let's say that we've this string:

```
Hello World
```

Capturing it with this RegEx: `(Hello) (World)`

Replacement is: `\U1 \L2` will give us -> `HELLO world`

```
\U1 = $1 to Uppercase
\L2 = $2 to Lowercase
```

**Comment by sandy081** [comment]
@elkebirmed Thanks for the documentation. This is cool to have. This is beyond the scope of what is currently supported by javascript. 

We need to come up with our own advanced replace engine to support these cases.

Thanks

**Comment by elkebirmed** [comment]
You're welcome @sandy081

**Comment by kdar** [comment]
It would be nice to have a way to supply a javascript function to the capture groups, so we can choose how to transform them and do more things than just upper/lower case. Since javascript already provides this, we just need an interface for it.

```javascript
"some_VAR".replace(/([a-z]+)_([A-Z]+)/, function(match, p1, p2) { 
  return [p1.toUpperCase(), p2.toLowerCase()].join("_");
})
// "SOME_var"
```

**Comment by alystair** [comment]
Ran into this today, seems regex replacement still isn't quite there yet.

**Comment by brianlowe** [comment]
Ran into this today. Anyone know of an online tool which supports case conversion in regex replacement - just to save me having to install SublimeText just for this tas, while waiting for VSCode to catch up?

**Comment by retNull** [comment]
@brianlowe Notepad++ will do what you need.

**Comment by brianlowe** [comment]
@retNull Thanks. Notepad++ does the casing transformation. (Now I just need to work up a suitably selective expression and corresponding substitution to complete my task.

**Comment by freman** [comment]
I miss this from sublime :(

**Comment by Ugotsta** [comment]
As a temporary workaround, you can use a workflow like so:
- Press <kbd>CTRL-H</kbd>.
- Press <kbd>ALT-R</kbd>.
- Type `_([a-zA-Z])`.
- Press <kbd>TAB</kbd> and type `$1`.
- Press <kbd>ALT-ENTER</kbd>.
- Press <kbd>F1</kbd> and type `u`, then press <kbd>ENTER</kbd>.
- Press <kbd>CTRL-ALT-ENTER</kbd>.

A bit of explanation added here:
https://gist.github.com/2a271f6440f1ac7e028df55e94035e40

**Comment by jpike88** [comment]
@Ugotsta that workaround makes sense only to Windows users.

**Comment by jpike88** [comment]
A more general 

- Open find and enter the regex `_[A-Za-z]`
- Open from top menu bar, Selection > Select all occurrences
- Open command menu (COMMAND + SHIFT + P on Mac, Ctrl+Shift+P on Windows/Linux), then type 'Transform to Uppercase', hit enter.
- Then press Left Arrow once, then Backspace once

**Comment by vbullinger** [comment]
This issue is over two years old and sounds really easy to fix and useful. Can we get an update or roadmap on this, please?

**Comment by ashclarke** [comment]
Is this possible, i.e. worth roadmapping, now that PCRE2 is an option, as of [v1.29.0](https://code.visualstudio.com/updates/v1_29#_backreferences-and-lookahead-in-search)?

> PCRE2's Replacement String Case Conversion
PCRE2 supports case conversion in replacement strings when using PCRE2_SUBSTITUTE_EXTENDED. \U converts everything that follows to uppercase. \L converts everything that follows to lowercase. \u converts the next character to uppercase. \l converts the next character to lowercase. \E turns off case conversion. As in Perl, the case conversion affects both literal text in your replacement string and the text inserted by backreferences.

> Unlike in Perl, in PCRE2 \U, \L, \u, and \l all stop any preceding case conversion. So you cannot combine \L and \u, for example, to make the first character uppercase and the remainder lowercase. \L\u makes the first character uppercase and leaves the rest unchanged, just like \u. \u\L makes all characters lowercase, just like \L.

> In PCRE2, case conversion runs through conditionals. Any case conversion in effect before the conditional also applies to the conditional. If the conditional contains its own case conversion escapes in the part of the conditional that is actually used, then those remain in effect after the conditional. So you could use ${1:+\U:\L}${2} to insert the text matched by the second capturing group in uppercase if the first group participated, and in lowercase if it didn't.

https://www.regular-expressions.info/replacecase.html#pcre2

**Comment by narrative1st** [comment]
Really surprised to find out that this isn't supported in VSCode...this regex works great in Sublime Text for converting selected text to lowercase and converting spaces to dashes (slugify):

`${TM_SELECTED_TEXT/([a-zA-Z]+)(?:(s+?)|\b)/?1:L$1(?2:-)E/g}`

But doesn't work in VSCode?

Is this going to be something that is supported, or is there something I'm missing?

**Comment by bobmagicii** [comment]
one of those features that you don't use much, but darn if it isn't obvious when not there.

**Comment by fultonm** [comment]
+1 wanted this feature today

**Comment by fultonm** [comment]
Just open sublime and edit what u need to edit there I guess 🤷‍♂️

**Comment by sandy081** [comment]
@roblourens Does the ripgrep search support this capturing?

**Comment by roblourens** [comment]
The replace still has to be executed on the front end.

**Comment by sandy081** [comment]
Agreed

**Comment by janosh** [comment]
@sandy081 As @vbullinger said, a short note on when this might be added would be great.

**Comment by sandy081** [comment]
Sorry, no particular time frame yet. But will update the milestone when it is planned.

**Comment by AllanPinheiroDeLima** [comment]
This feature would be great mainly when importing lots of data from another source.
I've imported my database schema to make graphql schemas and needed this feature. I've use workarounds like the one proposed by @Ugotsta and worked, but it was as consuming as putting one by one there

**Comment by briancrink** [comment]
@jpike88 your solution worked perfectly. I agree this case conversion command from the command palette isn't well known. 

Spent a considerable amount of time trying to get \u$1 or \u1 to work for case conversion to figure out it's not even supported lol.

**Comment by ianqueue** [comment]
needed.

**Comment by joo** [comment]
needed.

**Comment by jmoutray** [comment]
Me too

**Comment by jimpriest** [comment]
Frustrating because oddly enough this does seem to work on Windows VSCode.  Was a bit surprised to hop over to Linux and find it failing. :(

**Comment by nemchik** [comment]
@jimpriest I have not been able to get this working on Windows, so I'm curious what you've done?

**Comment by jimpriest** [comment]
> @jimpriest I have not been able to get this working on Windows, so I'm curious what you've done?

Well I'm pretty sure it used to work - I took notes in Jira ticket of what I used so I wouldn't forget. 

find: var="(.*?)"
replace: var="\L$1\E"

Trying it now on my work PC (Windows) it doesn't work.  :(   I get the same results as I was seeing in Linux yesterday.  My note was from Aug 2018 so maybe it's a version issue?

**Comment by nemchik** [comment]
I'm not a `+1` kind of commenter, but now I kind of wish I had on this thread just to see when I started tracking it. Earliest email I have on this thread was [April 5th](https://github.com/microsoft/vscode/issues/12185#issuecomment-480463158), but I know I've been using VSCode longer than that (at least since  Oct 4, 2018, when generated a GitHub token to start using [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) which was day 1 with VSCode for me I believe) and it's never been able to change case for me.

**Comment by Paerhati** [comment]
I would really appreciate if this feature was implemented as well.😊

**Comment by johnkoehn** [comment]
^ Would be an awesome feature

**Comment by MRamonLeon** [comment]
I will also love this feature

**Comment by ericadams** [comment]
I need this feature today, so I guess I'll have to install sublime or notepad++ 🤷‍♂

**Comment by briancrink** [comment]
> I need this feature today, so I guess I'll have to install sublime or notepad++ 🤷‍♂

There are existing solutions in the form of extensions in the marketplace

**Comment by nemchik** [comment]
Would you be able to provide a link?

**Comment by briancrink** [comment]
> Would you be able to provide a link?

[Text Transformer For VS Code](https://marketplace.visualstudio.com/items?itemName=jackytsu.text-transformer)
[uppercase](https://marketplace.visualstudio.com/items?itemName=ruiquelhas.vscode-uppercase)
[change case](https://marketplace.visualstudio.com/items?itemName=mostafa.change-case)
[TextTransform](https://marketplace.visualstudio.com/items?itemName=florianloch.text-transform)

I don't remember remember which extension I use or if it's a feature now, the command I use from the command palette is 'Transform to'

**Comment by nemchik** [comment]
Those extensions don't quite meet the need. Vscode already has case transformation natively, but something you can't do is regex find across multiple files and replace the found items with upper or lower case all at once.

**Comment by freman** [comment]
Eg:

Search: ```\s+private final (\w+) (\w+);```
Replace ```\t\u$2 \l$1 `json:"$2"` ```

Use case: Converting structures to go

**Comment by liudonghua123** [comment]
I like this awesome feature, and sometimes I need to use this feature like replace all the tag name of html to lowercase if possible.

**Comment by bitbytebit1** [comment]
Also looking for this functionality

**Comment by inoyakaigor** [comment]
Is any updates for this issue?

**Comment by shotlom** [comment]
That MS are not attending to this basic and important feature suggests that VSCode may be deprecated soon in favor of some other code editor. Shame, I quite liked VSCode.

**Comment by janosh** [comment]
> suggests that VSCode may be deprecated soon in favor of some other code editor.

Somehow I doubt it. 😉

**Comment by roblourens** [comment]
We could take a PR for this if anyone wants to work on it. I think we would want something basically consistent with another implementation: https://www.regular-expressions.info/replacecase.html but we can only support it for 'replace', not for searching with backreferences like Perl apparently supports. If someone wants to work on it, please let's talk about how it would work first 😁

**Comment by shotlom** [comment]
Do you have a cost code we can invoice against?

With Regards,
Mr Sholto Maud

**Comment by matheo** [comment]
`Alt+Enter` + `F1` worked on my Ubuntu. Thanks to https://github.com/microsoft/vscode/issues/12185#issuecomment-414411370

**Comment by blueray453** [comment]
@elkebirmed It seems like not being able to change case using regex seems to be an upstream issue. I hope by going through https://github.com/chmln/sd/issues/72#issue-596532078 & https://github.com/BurntSushi/ripgrep/issues/1546#issue-596389367 you will be able to understand what is the problem and what might be the solution.

**Comment by roblourens** [comment]
It's not upstream, replacement is implemented in VS Code, not ripgrep.

**Comment by blueray453** [comment]
@roblourens which regex flavour are you using for replacement?

**Comment by irridia** [comment]
@roblorens Search and replace is implemented differently in at least three places in VSCode.

As @blueray453 mentions, the global S&R seems to be implemented with ripgrep, which only "accidentally" supports replace and has no plans to add replacement features. So even if someone wanted to contribute the time to ripgrep, it likely wouldn't get merged. And the cost of revamping and unifying VSCode's various search implementations is a bit larger than most third-party PRs. And I'm not holding my breath. ;)

That said, I do have a [draft PR #96128 (!)](https://github.com/microsoft/vscode/pull/96128) that I may spend more time on if there's interest (I'm not a Node guy). In my case I had mostly a single very long file I wanted to S&R, so "at least I'm okay". ;-)

**Comment by roblourens** [comment]
Merged this for the find widget - work to do this for search is still ongoing.
