### ISSUE TITLE
I will not report any issues or provide feedback

### ISSUE THREAD

**Issue by tgucci** [microsoft/vscode#121840]
Issue Type: <b>Bug</b>

I will not provide any feedback on bugs or issues nor any other kind of feedback because you force me to post an Issue to GitHub for it. I'm not interested in contributing to the project, therefore, i'm not interested in GitHub at all, and certainly won't create a GitHub account just for helping you improve your product.

Do it like you do it with Edge, and i'm happy to provide you with lots of feedback.

**Comment by kieferrm** [comment]
I hear you, and thank you for taking the time and sharing with us.

It's like Russell's paradox though
