### ISSUE TITLE
system hangs when using regex search on m1

### ISSUE THREAD

**Issue by arpanEnbake** [microsoft/vscode#121889]
there are 100 files in folder. on entering the regex search, results are shown that 25 matches found in 32 files.

import (.*)+ data'

System: Macbook air m1 2020, 8gb

The usage of code helper goes to 100% and it hangs. 

![Screenshot 2021-04-22 at 8 33 52 AM](https://user-images.githubusercontent.com/397626/115649953-f1d0dc80-a345-11eb-913c-9113021109a9.png)
![Screenshot 2021-04-22 at 8 35 36 AM](https://user-images.githubusercontent.com/397626/115649957-f4cbcd00-a345-11eb-8733-5a2ca1c94057.png)

**Comment by roblourens** [comment]
Does it happen for any query/folder? Could it be returning a result in a very long line of text?
