### ISSUE TITLE
Terminal Split not working

### ISSUE THREAD

**Issue by cranticumar** [microsoft/vscode#121880]
Just click split and no action is being taken

Version: 1.56.0-insider (system setup)
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:13:42.491Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by cranticumar** [comment]
https://github.com/microsoft/vscode/issues/121809 seems to be related

**Comment by cranticumar** [comment]
assigning key binding to {
  "key": "tab s",
  "command": "workbench.action.terminal.splitInActiveWorkspace"
}

is allowing the splitting

**Comment by meganrogge** [comment]
This will be fixed in tomorrow's insider's
