### ISSUE TITLE
Stopped at breakpoint but debug controls don't work as expected

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#121898]
Issue Type: <b>Bug</b>

After building from source I am debugging an issue and have set a breakpoint. Once OSS has hit my breakpoint the line is correctly decorated and the Call Stack panel states PAUSED AT BREAKPOINT but the inline Continue button does nothing, and the debug toolbar's state implies I am not at a breakpoint.

I can sort it out by changing the value in the debug toolbar's dropdown, then setting it back again. Now the Continue button works.

![junk](https://user-images.githubusercontent.com/6726799/115665541-589cc880-a33b-11eb-8e1a-994f96a3f855.gif)

VS Code version: Code - Insiders 1.56.0-insider (23a2409675bc1bde94f3532bc7c5826a6e99e4b6, 2021-04-21T05:13:42.491Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
I acknowledge this issue. The problem here is that we do not properly auto focus the sub session which the js-debug provides.

**Comment by Vitalii4as** [comment]
I am experiencing similar issue on versions 1.56 and later, but on 1.55.2 it works fine.

**Comment by isidorn** [comment]
This should be fixed with latest.
@gjsjohnmurray please let me know if you can still hit this with VS Code insiders and if yes I will reopen this. Though a bit more precise steps would help. Thanks!
