### ISSUE TITLE
Make the settings sync log less scary when an extension cannot be installed in a particular context

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#121856]
Pls see the screenshot below. It is expected that the extension cannot be installed in this particular context and therefore this should only be an info and not an error.

![image](https://user-images.githubusercontent.com/172399/115603755-d2539880-a2e0-11eb-908a-60c3a91bc08f.png)

**Comment by kien161632** [comment]
https://user-images.githubusercontent.com/172399/115603755-d2539880-a2e0-11eb-908a-60c3a91bc08f.png0 #121720

**Comment by tymsai** [comment]
`#121720` is incorrect I think.
