### ISSUE TITLE
Restrict tab title width for very long filenames

### ISSUE THREAD

**Issue by LinqLover** [microsoft/vscode#121849]
Look at this:
![image](https://user-images.githubusercontent.com/38782922/115592662-c8776880-a2d3-11eb-9267-8f3caffeb4ca.png)

This is not really scaled well IMHO. I think it would be useful if one could configure a maximum tab title width to avoid unnecessary scrolling in the horizontal tab bar.

If there is already a similar issue, I apologize for not finding it.

**Comment by bpasero** [comment]
Is this literally a file on disk or some extension?

**Comment by LinqLover** [comment]
> Is this literally a file on disk or some extension?

It is a file.
