### ISSUE TITLE
Executing tasks inside Bash on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by isaacDaly** [Microsoft/vscode#12189]
- VSCode Version: 1.5.2
- OS Version: Windows 10 build 14926

I've set the Integrated Terminal so that it runs Bash on Ubuntu on Windows, which works fine. However, is there a way to run a task in Bash? For example, running a Python file so that it is the equivalent of `python3 <filename>.py` in Bash, as opposed to running in Windows CMD?

**Comment by Tyriar** [comment]
An extension can now do this trivially by calling `Terminal.sendText`, this could be implemented to send to the default shell or a one defined by the extension (in v1.6). If you're interested in Python I recommend filing this against the Python extension's repo https://github.com/DonJayamanne/pythonVSCode
