### ISSUE TITLE
Removing showTabs terminal setting while true (default) will create another split pane

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121817]
Repro:

1. Close all terminals
2. Set terminal.integrated.showTabs to true
3. Open a terminal
4. Delete the setting

<img width="1341" alt="Screen Shot 2021-04-21 at 5 29 35 AM" src="https://user-images.githubusercontent.com/2193314/115553803-af829f00-a262-11eb-86ad-a090a823b24e.png">

**Comment by meganrogge** [comment]
can't repro this

**Comment by Tyriar** [comment]
Still happens here:

<img width="1230" alt="Screen Shot 2021-04-23 at 5 44 54 AM" src="https://user-images.githubusercontent.com/2193314/115872770-091bd280-a3f7-11eb-8af5-bf2f73b0b90f.png">
