### ISSUE TITLE
Kernel picker not displayed in statusbar

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121867]
- VS Code Version: Insiders
- OS Version: Mac

Steps to Reproduce:

1.Install Jupyter Extension
2.Open a notebook
Sometimes the kernel picker is there, sometimes no
No errors in the console window.
3. Selecting a kernel using the command doesn't make any difference. Been seeing this for at least 3 days now
.
<img width="459" alt="Screen Shot 2021-04-21 at 13 29 22" src="https://user-images.githubusercontent.com/1948812/115617008-b8e12b00-a2a5-11eb-9462-d17ac89d2c31.png">

@roblourens @rebornix /cc

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jrieken** [comment]
> Sometimes the kernel picker is there, sometimes no

Sorry, but I need repo steps or a simple extension sample. Generally, the picker should show as soon as controllers have been created

**Comment by DonJayamanne** [comment]
> need repo steps or a simple extension sample. Generally, the picker should show as soon as controllers have been created

Easy, just open an ipynb file in insiders. I can repro this consistently.
Peng too came across this a few days ago.

**Comment by jrieken** [comment]
> Easy, just open an ipynb file in insiders. I can repro this consistently.

I don't repo this with any of my test notebooks, so this is maybe an issue with Jupyter. The status bar is no magic: when a notebook has focus show all notebook controllers...

**Comment by DonJayamanne** [comment]
here you go:
* Run cells
* Change kernels
* Still no kernel in statusbar.
No logs, no errors.

![recording](https://user-images.githubusercontent.com/1948812/115743219-4f652900-a346-11eb-8a50-a2a38839b6a6.gif)

**Comment by jrieken** [comment]
Funny... I am seeing one with latest insiders and latest jupyter... I cannot debug/test in main because of the latest API changes.


<img width="1027" alt="Screenshot 2021-04-22 at 18 36 53" src="https://user-images.githubusercontent.com/1794099/115751749-c4158300-a399-11eb-840a-7d80eb81f988.png">

**Comment by jrieken** [comment]
The status bar entry hasn't been hidden, right?

<img width="711" alt="Screenshot 2021-04-22 at 18 39 26" src="https://user-images.githubusercontent.com/1794099/115752094-122a8680-a39a-11eb-8a91-f8295e58d1f8.png">

**Comment by jrieken** [comment]
@roblourens and I have seen this in the meanwhile and it must be some kind of context key issue, tho we don't know what...

**Comment by jrieken** [comment]
> @roblourens and I have seen this in the meanwhile and it must be some kind of context key issue, tho we don't know what...

Sorry, we have actually not seen that. We sometimes see run-buttons missing due to bad context keys but I haven't seen/heard of missing status bar items
