### ISSUE TITLE
Search View: Closing a search entry does not longer select the next entry

### ISSUE THREAD

**Issue by pmneo** [microsoft/vscode#121899]
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Enter a search term with multiple matches
2. Select any result, the match is displayed in the editor
3. Close this match - The editor stays on the last match and the next entry is just highlighted

Expected and previous behavior: 
The next result is selected AND displayed. 

The new behavior is very annoying and disrupts productivity.

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Fixed in Insiders https://github.com/microsoft/vscode/issues/120637
