### ISSUE TITLE
Notebooks using serializer not turning dirty when adding/remove output

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121807]
* have a note serializer
* have a notebook that persists output
* clear a non empty cell or run a cell
* notebook isn't dirty

This is because the notebook cell's alternative version id doesn't honour metadata, cell-language, and output

**Comment by jrieken** [comment]
Still reproducing this

**Comment by rebornix** [comment]
I'll revisit this next week. Currently outputs are not part of any undo/redo, thus it doesn't make the document dirty. But the right behavior should be that outputs are part of undo/redo?

**Comment by jrieken** [comment]
> But the right behavior should be that outputs are part of undo/redo?

Unsure... Output is (usually) the result of an execution and you cannot undo an execution because output is only one of its results. Like there is also variables that have changed etc. So, from that point of view I believe that output shouldn't be on the undo/redo stack but yet the notebook needs to be dirty when receiving/clearing output. Not easy, lets discuss in the sync

**Comment by DonJayamanne** [comment]
Lol, landed a PR to fix this issue and realized and issue existed & its under discussion https://github.com/microsoft/vscode/pull/126518

**Comment by DonJayamanne** [comment]
>  So, from that point of view I believe that output shouldn't be on th

Agreed.

**Comment by rebornix** [comment]
We will now turn the notebook to dirty if the change is not transient, and it will not change undo/redo stack.
