### ISSUE TITLE
 Add the ability to remove unnecessary built-in extensions.

### ISSUE THREAD

**Issue by AlexDev2020** [microsoft/vscode#121803]
Out of the box vscode has support for such languages ​​as: html, js, php, etc (using built-in extensions). I don't need these extensions, and I would gladly get rid of them, since I want to have the minimum functionality I need. If I need support for a specific language, I can always install the required extension. The vs code command, please add the ability to remove optional built-in extensions, this will allow the user to get a light version of the editor with the functionality that is needed without any superfluous.

**Comment by tymsai** [comment]
I little bit agree with your word " light version " ,

but people who are **new** to VSCode or recently **migrated from any other editor** might know how to intall an extension So in this case a built-in extension is important ,
VSCode is known for its built-in features & removing them might not be a good thing ,
Just by removing some extensions won't make your VSCode light or faster ,
VSCode is already very much light on device's resources and is also compatible with most of the devices out there ,
VSCode already has a disable option for extensions.

**Comment by AlexDev2020** [comment]
> Немного согласен с вашим словом "облегченная версия",
> 
> но люди , которые **новые** для VSCode или недавно **мигрировали из любого другого редактора** могли бы знать , как intall расширения Так что в этом случае встроенного расширения имеет важное значение,
> VSCode известен свои встроенные функции и их удаление не может быть хорошими Дело в том,
> что простое удаление некоторых расширений не сделает ваш VSCode легким или быстрым,
> VSCode уже очень сильно расходует ресурсы устройства и также совместим с большинством устройств,
> VSCode уже имеет параметр отключения для расширений.

I'm not talking about allowing users to remove any built-in extensions. I'm talking about allowing users to remove optional embedded extensions (e.g. html, js, php). By deleting these extensions, nothing terrible will happen to the editor, and if I ever need support for these languages, then I can simply install the desired extension. This will allow users to make vscode cleaner.

**Comment by AlexDev2020** [comment]
Just why such specific extensions are built-in. According to this logic, we can make the python, C ++ extension built-in, but there are users who do not need support for these languages.

**Comment by AlexDev2020** [comment]
Here is a list of the extensions I would get rid of since I don't use them. They are intended for web developers.
CSS Language Features
Emmet
Grunt
Gulp
HTML Language Features
Jake support for VS Code
JavaScript Debugger
JavaScript Debugger Companion Extension
Node Debug
Node Debug (legacy)
Node Debug Auto-attach
NPM support for VS Code
PHP Language Features
TypeScript and JavaScript Language Feature
vscode-js-profile-table

Extension Authoring (I'm not sure about this extension, because I don't understand what it does)

Allow to remove the Git extension in case I am not using a version control system or use a different one (for example svn)

Other optional built-in extensions should also be allowed to be removed.

**Comment by AlexDev2020** [comment]
@tymsai
Removing built-in extensions may not speed up the editor, but it will make it cleaner. You will install what you really need, for that is the concept of extensions. Most of the built-in extensions are specific and aimed more at web developers, and I am not a web developer and these extensions are simply imposed on me. Yes, I don’t argue that I can disable them, but I would just like to delete them, why keep on my computer something that you will not use and something that is disabled forever. According to this logic, you can make a bunch of specific extensions inline and say that vs code supports a lot of things, and you users live with it, and if you don't like inline extensions, you just disable them, but they will live on yours. computer. There are also users who have little disk space, of course, removing built-in extensions will not add a couple of gigabytes, but the free space is enough, for example, to accommodate a small project. In any case, the user should not pay for what he does not use, even if the price is not high.

**Comment by tymsai** [comment]
but because of this built-in feature it stands up against the other editors in market. If you remove them then the game is almost over.

**Comment by AlexDev2020** [comment]
@tymsai
If I remove code extensions such as PHP Language Features from my vs, then this editor will not get any worse. Let's add a bunch of other specific extensions in the built-in ones and according to your logic vs the code will become even cooler, but some users will pay for what they don't use.

**Comment by sandy081** [comment]
You can disable those built in extensions if not wanted. Not sure if you tried that?

**Comment by AlexDev2020** [comment]
@sandy081 
Yes, I know that built-in extensions can be disabled, but I would like to remove the built-in extensions that I don't need

Why doesn't vscode allow deleting extension data?
