### ISSUE TITLE
Forward language count to CES survey to allow contextual questions

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#121883]
If the [CES survey](https://github.com/microsoft/vscode/pull/119377) knows which languages a user tried in their first day, it could unlock more specific questions to further improve the language onboarding experience.

How though. [languageSurveys.contribution.ts](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/surveys/browser/languageSurveys.contribution.ts#L42) tracks the edited count for languages that run surveys; which are the languages we care most about right now. Only issue is that the storage key isn't exported, so the [ces survey](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/surveys/browser/ces.contribution.ts) doesn't know about it.

@joaomoreno any general thoughts on the idea, and best practices on how to make the storage keys known to the ces survey code; so they can be read and attached as params to the survey URL?

**Comment by joaomoreno** [comment]
@digitarald The CES code already has access to the same `storageService`. Can't you copy the [code](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/surveys/browser/languageSurveys.contribution.ts#L146-L148) [which](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/surveys/browser/languageSurveys.contribution.ts#L42) maps the surveys to storage service keys over to CES and read them from there?

**Comment by digitarald** [comment]
> Can't you copy the code which maps the surveys to storage service keys over to CES and read them from there?

Sure, was mainly worried that this creates some copy/pasta. Will take that approach for an initial pull request draft and gather feedback.

**Comment by joaomoreno** [comment]
No worries. We can also extract the common code to a new `.ts` file, sibling to those two.

**Comment by connor4312** [comment]
@digitarald are there verification steps for this?

**Comment by digitarald** [comment]
Sorry that they are so complex and time-intensive. I can

1. Open a fresh VS Code Insiders instance
2. Check `telemetry.log`, ensure that you are in the treatment group `telemetry/tasClientReadTreatmentComplete {"properties":{"treatmentName":"CESSurvey","treatmentValue":"true"`
3. Open a Java file and save it.
4. Keep VS Code open for _1 hour_ to trigger the new-user survey popup and click to open the survey
5. Validate that the URL it opened contains `javaLang=1`

**Comment by connor4312** [comment]
Ok, see you in an hour! 🙂

**Comment by connor4312** [comment]
The treatment service does not seem to like me, for some reason. Unmarking as verified for someone else to give it a shot. Note that you need to repeatedly open VS Code windows with new user-data-dir's until you get into the treatment.

**Comment by JacksonKearl** [comment]
Also attempted this but no survey after an hour. Confirmed I did get an initial `{"properties":{"treatmentName":"CESSurvey","treatmentValue":"true"`

**Comment by digitarald** [comment]
@JacksonKearl when the experiment enables the survey you should also get a `cesSurvey:schedule` event? Did that work?

**Comment by JacksonKearl** [comment]
Testing again

**Comment by JacksonKearl** [comment]
Worked! https://www.research.net/r/new-to-vscode?o=darwin&v=1.57.0-insider&m=cebe1f037f09baad9c8317f6e3ddbee4f3359944eb3ce8c2e3fe6f988e70c9be&javaLang=1
