### ISSUE TITLE
Review package.json notebook contribution

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121819]
We have the `notebookProvider` and `notebookOutputRenderer` contribution points and we shouldn't forget that those are API as well. Ideas/questions

* Should `notebookProvider` be called `notebooks` instead? We don't really contribute a provider anymore?
* Should `viewType` be just `id` (similar to languages-contributions) and in the API should it be `notebookType` or `notebookKind`?
* Should `notebookOutputRenderer` be called `notebookRenderer`?

**Comment by jrieken** [comment]
fyi @mjbvz

**Comment by mjbvz** [comment]
- I like `notebooks`. It is similar to `languages` and `customEditors`

- `customEditors` use `viewType`

-  `notebookRenderers` is good if we want to try unify output renderers and markup renderers. If we want to instead have separate contribution points for the two, then I think we should keep `output` in the name

**Comment by jrieken** [comment]
Done... That change was to rename `viewType` to just `type`
