### ISSUE TITLE
Environment variables no longer resolved in settings.json 

### ISSUE THREAD

**Issue by daniel-liuzzi** [microsoft/vscode#121847]
Type: <b>Bug</b>

This regression occurred some time after the 2021-04-16 nightly. That's what I was running before updating to 2021-04-21, and variables resolved just fine then.

Steps to Reproduce:

1. Use an environment variable in `settings.json`. For example:

    ```json
    {
        "terminal.integrated.shell.windows": "${env:ProgramFiles}/PowerShell/7/pwsh.exe",
    }
    ````

2. Press <kbd>Ctrl</kbd> + <kbd>`</kbd> to open the terminal

Expected result:

The terminal opens up.

Actual result:

The following toast pops up:

![image](https://user-images.githubusercontent.com/143884/115589105-c27f8880-a2cf-11eb-854a-382e1eeae69a.png)

VS Code version: Code - Insiders 1.56.0-insider (23a2409675bc1bde94f3532bc7c5826a6e99e4b6, 2021-04-21T05:13:42.491Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
Pretty sure we're calling the resolver service correctly (before and after https://github.com/microsoft/vscode/pull/121918), it seems to be a regression there.

**Comment by alexr00** [comment]
With the new `resolveWithEnvironment`, the environment that is passed in can have different casing than the old environment that was used, which caused this bug.
