### ISSUE TITLE
Webview post messages are not posted to the notebook controller

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#121895]
Version: 1.56.0-insider (user setup)
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:13:42.491Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Clone pr dotnet/interactive#1286
2. Go to folder `src/dotnet-interactive-vscode/nsiders` adn open with VSCode insiders
3. Launch debugger
4. set breakpoint in `src/dotnet-interactive-vscode/insiders/src/notebookControllers.ts` at line 89
4. Open a `.dib` or `.ipynb` notebook

The breakpoint is never hit despite the preloads are posting the messages (the developer tools for the web view will show it in console)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by colombod** [comment]
cc: @brettfo, @jrieken

**Comment by jrieken** [comment]
this should be fixed with 306f32b

**Comment by jrieken** [comment]
related/dupe (?) of https://github.com/microsoft/vscode/issues/121869

**Comment by colombod** [comment]
Perfect, when can we test this fix?

**Comment by jrieken** [comment]
Should be in latest insiders

**Comment by colombod** [comment]
Perfect!
