### ISSUE TITLE
Provide the Notebook Uri in NotebookSerializer methods

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121894]
Today the Uri of the notebook is not provided in the serialize & de-serialize methods.
We need this information to enable the `Notebook Trust` feature.

Jupyter extensions trusts notebooks based on the Uri of the document (whether we've seen this Uri before or not).
Similarly when a user saves a notebook, we keep track of the data along with the Uri. This way if the contents of the Uri do not match the last saved information, we then know the user has edited this file out side of VS Code (e.g. re-downloaded it/overwritten it from some other location) deeming the notebook as no longer trusted.

@jrieken /cc

**Comment by jrieken** [comment]
> Today the Uri of the notebook is not provided in the serialize & de-serialize methods.

I am not sure that we can provide this information. We use the serialize/deserialize also for untitled files, backups etc and a URI doesn't always make sense there. 

I would like to clarify notebooks and trust first and then make a decision. I find it fishy that extensions remember trust states and not us doing that

**Comment by DonJayamanne** [comment]
> untitled files, backups etc and a URI doesn't always make sense there.

Another scenario is for untitled files.
We have a command to create untitled files with specific default cells.
Eg create untiled with typescript cell as the default.
What we do is, create a dummy uri with scheme untitled, and keep track of the cell language for that generated uri. Next week tell vscode to open that uri. When we get the method invoked from vscode to load the notebook data for that uri, we now know that it's an untitled (from uri) and that it was generated by us (we cached this) and that it's supposed to have some defaults.

**Comment by DonJayamanne** [comment]
> fishy that extensions remember trust states and not us doing that

Well that's how we implement trust today. It's per notebook (not necessarily just the content). I wish it were per content, but for a number of reasons it isn't.

**Comment by DonJayamanne** [comment]
FYI - we're unable to use the serializer due to the limitation mentioned here (we need to be able to create untitled files with some default content).
Perhaps we can create a new issue with that requirement.

**Comment by jrieken** [comment]
We have https://github.com/microsoft/vscode/issues/121974#issuecomment-826668767 for that. Closing this issue
