### ISSUE TITLE
Unable to debug any nodejs in Ubuntu

### ISSUE THREAD

**Issue by isamudaison** [microsoft/vscode#121877]
- VS Code Version:
- Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-72-generic snap

- OS Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

Steps to Reproduce:

1. Fresh VS code install (either snap or apt)
2. Create a simple `index.js` file, containing `console.log("Hello World");
3. Open terminal, type `node --inspect-brk index.js`
4. Press ctrl+shift+P and select "Debug attach to Node process"

Does this issue occur when all extensions are disabled?: Yes

Note: The breakpoint set on the console.log line goes gray while trying to attach as well.

**Comment by isamudaison** [comment]
Interesting, I have another machine running:

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-50-generic snap

```
```

Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

Linux isamudaison-THINN-15 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

And it's working fine. What differences could there be aside from kernel version?

**Comment by isamudaison** [comment]
Here's the `uname -a` on the non-working machine:
`Linux ws-isamudaison 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by connor4312** [comment]
/jsDebugLogs

You can set up an "attach" configuration to capture these: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_setting-up-an-attach-configuration

**Comment by isamudaison** [comment]
[vscode-debugadapter-2f69bcdf.json.gz](https://github.com/microsoft/vscode/files/6354478/vscode-debugadapter-2f69bcdf.json.gz)

**Comment by isamudaison** [comment]
Added logs gathered form this launch.json config:

`{
            "name": "Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command:PickProcess}",
            "trace": true
          }`

**Comment by connor4312** [comment]
Thanks, it looks like Node isn't responding to the messages we send to it. Which version of Node are you using? We recommend 12.x or newer (16 is the latest).

**Comment by isamudaison** [comment]
The project this is using is stuck on v8.17.0 currently.

**Comment by connor4312** [comment]
Okay, that is probably why. Node 8 is fairly buggy and has been end of life since the end of 2019. Some basic debugging works there, but I am not making fixes for it.

**Comment by isamudaison** [comment]
D'oh! OK Connor, thanks so much for the eyes-on and troubleshooting!
