### ISSUE TITLE
VSCode Intellisense not working

### ISSUE THREAD

**Issue by weizhang2525** [microsoft/vscode#121879]
Issue Type: <b>Bug</b>

When trying to ctrl + click on a component in React or import a file, it will load until eternity 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 8|
|Memory (System)|16.00GB (2.67GB free)|
|Process Argv|--crash-reporter-id 5aad2f6b-fb55-4f78-8cbf-c7b89c19701d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
html-snippets|abu|0.2.1
vscode-django|bat|1.6.0
vscode-intelephense-client|bme|1.6.3
simple-react-snippets|bur|1.2.3
path-intellisense|chr|2.3.0
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
python-extension-pack|don|1.6.0
es7-react-js-snippets|dsz|3.1.1
vscode-babel-coloring|dza|0.0.4
vscode-html-css|ecm|1.10.2
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
jenkins-status-fork|era|3.1.4
prettier-vscode|esb|6.3.2
javac-linter|fau|1.3.1
php-intellisense|fel|2.3.14
vscode-ionic-snippets|fiv|2.2.2
auto-close-tag|for|0.5.10
code-runner|for|0.11.3
beautify|Hoo|1.5.0
ftp-simple|hum|0.7.6
vscode-peacock|joh|3.9.1
graphql-for-vscode|kum|1.15.3
MagicPython|mag|1.1.0
vscode-language-babel|mgm|0.0.31
dotenv|mik|1.0.1
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.3.1
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
prisma|Pri|2.21.2
java|red|0.77.0
text-marker|ryu|1.11.0
vscode-open-in-gitfork|spa|1.0.3
open-in-browser|tec|2.0.0
python|tht|0.2.3
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
jinja|who|0.0.8
ReactSnippets|xab|2.4.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by mjbvz** [comment]
Please share stets to reproduce and example code

/needsMoreInfo
