### ISSUE TITLE
terminal  not work please help

### ISSUE THREAD

**Issue by piyushdwivedi8358** [microsoft/vscode#121842]
Issue Type: <b>Feature Request</b>

my terminal not work i have tried many time

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 6.0.6002

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please specify what are your terminal configuration? What error or behavior do you see?

**Comment by piyushdwivedi8358** [comment]
> /needsMoreInfo
> 
> Please specify what are your terminal configuration? What error or behavior do you
terminal completely blank no any configuration shows

**Comment by Tyriar** [comment]
Likely /duplicate https://github.com/microsoft/vscode/issues/121685
