### ISSUE TITLE
Support git --push-option

### ISSUE THREAD

**Issue by bondsb** [microsoft/vscode#121845]
Custom options can be passed to the remote git server for various tasks, such as controlling CI variables or automatically creating merge requests, via the `--push-option` command line parameter.

This request is to provide two new types of choices in the Push submenu for setting these parameters:

1. `Push: <custom text>`
   - Zero or more of these options will display based on custom configuration settings
2. `Push with options...`
   - Pops up a textbox that requests the option value

As described at [git-scm.com](https://git-scm.com/docs/git-push#Documentation/git-push.txt--oltoptiongt):

> `-o <option>`
> `--push-option=<option>`
> 
>    Transmit the given string to the server, which passes them to the pre-receive as well as the post-receive hook. The given string must not contain a NUL or LF character. When multiple `--push-option=<option>` are given, they are all sent to the other side in the order listed on the command line. When no `--push-option=<option>` is given from the command line, the values of configuration variable `push.pushOption` are used instead.

# Example Settings

The following push options work in [GitLab](https://docs.gitlab.com/ee/user/project/push_options.html#push-options-for-gitlab-cicd).

In settings.json:
```json
  "git.pushOptions": {
    "Skip Pipeline" : [
      "ci.skip"
    ],
    "Merge When Pipeline Succeeds": [
      "merge_request.create",
      "merge_request.target=master",
      "merge_request.merge_when_pipeline_succeeds"
    ]
  }
```

The Push menu would include the following new entries:

- `Push: Skip Pipeline`
- `Push: Merge When Pipeline Succeeds`
- `Push with options...`

**Comment by AlexeySemigradsky** [comment]
That would be a really cool feature. We would be able to create merge requests on push.
