### ISSUE TITLE
Setting preferred default behavior for "Filter on type" when searching breadcrumbs

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#121832]
I'd like a setting that makes it so that the dropdown list gets filtered as I type in the breadcrumbs dropdown menu. The way it is now, any matches on your search query only gets highlighted, unless you click on the small 'Filter on Type' button in the corner of the dropdown.

**Comment by jrieken** [comment]
the `workbench.list.keyboardNavigation` setting is for that
