### ISSUE TITLE
The newly added file does not appear in explorer

### ISSUE THREAD

**Issue by springzero** [microsoft/vscode#121825]
- VS Code Version:1.55.2
- OS Version: macos 10.15.6 

Steps to Reproduce:

1.git clone https://github.com/mattermost/focalboard
2.code focalboard
3.make prebuild
4.make server-mac (bin folder will be generated here)

 You will find that there is no bin folder in the explorer on the left !
 I tried refreshing; exit and reopen vscode (all extensions are disabled);

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/9411683/115563149-cf10da80-a2e9-11eb-87c8-1c70dbbd5da1.png)

vscode is getting better!

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
You probably have a `files-exclude` setting to ignore bin files

**Comment by springzero** [comment]
> Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/
> You probably have a `files-exclude` setting to ignore bin files

yes You are right thank you very much, I found it in the workspace configuration file.  
Thank you
