### ISSUE TITLE
Weird Breakpoint markers (UI)

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode#121864]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

In a running Node application, in a JS `Class` definition (not TS), click on the breakpoint gutter outside a line number to set a breakpoint before the line runs, and the red dot appears both in the gutter and in the middle of a keyword somewhere inside the line.

<img width="246" alt="Screen Shot 2021-04-21 at 3 43 52 PM" src="https://user-images.githubusercontent.com/4670942/115612703-8c370e80-a2b9-11eb-91a7-3dbde7d298c6.png">

This issue doesn't seem to happen in POJS, i.e., not inside a `class X {...}`.  

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|--crash-reporter-id ccb59229-72a3-45b5-98f2-51e4c2d8a9ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vsc-scaffolding|alf|0.1.14
replacerules|bhu|0.4.1
xml|Dot|2.5.1
mssql|ms-|1.10.1
debugger-for-chrome|msj|4.12.12
vscodeintellicode|Vis|1.2.12

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by isidorn** [comment]
This is coming from the js-debug, thus forwarding to @connor4312 
Looks like the user might be using an old debugger (I see debugger from chrome in a list of extensions)

**Comment by connor4312** [comment]
This is either:

- The code running in the debugger is different than the code you have on disk (i.e. you made changes)
- There's something in your tooling which is creating invalid sourcemaps when compiling/preprocessing your code
- You're using some kind of loader in the application, such as the babel loader, which is changing locations and is not set up to create sourcemaps correctly

If you share a repro or more information about your setup, we can find out which one it is. Logs might also be enough:

/jsDebugLogs

**Comment by ChrisMiami** [comment]
OK - I will gather everything I can and send. I think the source is innocuous enough to share - nothing proprietary about it IIRC.

**Comment by connor4312** [comment]
Closing since there was no further info
