### ISSUE TITLE
See the command being executed for key binding

### ISSUE THREAD

**Issue by trajano** [microsoft/vscode#121821]
Issue Type: <b>Feature Request</b>

I would like to have a setting that would allow us to see the command being executed for key binding.  That way I can verify my customizations are actually working.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by IllusionMH** [comment]
There is existing `>Developer: Toggle Keyboard Shortcuts Troubleshooting` which logs received keys and resoled commands.
Have you tried it? Does it cover you use case?

**Comment by trajano** [comment]
Yes satisfies my need.
