### ISSUE TITLE
"Do you want to install the recommend extensions for this repository" should not show up on startup

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121802]
Refs: https://github.com/microsoft/vscode/issues/119463

Open the `vscode` repo using a new user data dir. Notice you get 3 notifications directly in your face.

I suggest the following:

* Add an entry to the welcome page / getting started view to install all recommended extensions for this repository
* Only show the "Do you want to install the recommended..." once a user opens a Code editor for the very first time

fyi @JacksonKearl for welcome view
@chrisdias for pm thoughts

![Screenshot 2021-04-21 at 11 21 36](https://user-images.githubusercontent.com/1926584/115530816-69463380-a294-11eb-9bae-e9afe594cc9f.png)

**Comment by isidorn** [comment]
Related usage https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/extensions/browser/extensionRecommendationNotificationService.ts#L167

Don't we have a don't show again button under the gear. Why is there a custom solution to use notification prompts to not show this again?

**Comment by JacksonKearl** [comment]
Lots of folks don't have welcome views enabled at all, so only placing it there seems insufficient. Could it be a badge on the extensions activity bar item?

**Comment by isidorn** [comment]
@JacksonKearl yup. But good idea, I think we need a combination of a couple of things.
So an extensions badge approach I really like

**Comment by sandy081** [comment]
Underlying problem is that we are lacking a better way to recommend extensions.

**Comment by isidorn** [comment]
I am not saying we have to change the approach but the timing at least. From above:
> Only show the "Do you want to install the recommended..." once a user opens a Code editor for the very first time

Or if you have a better idea for **when**.

Or we could think about this in the UX channel how to show a badge in the activity bar for the extensions viewlet if you like that idea...

**Comment by sandy081** [comment]
> Only show the "Do you want to install the recommended..." once a user opens a Code editor for the very first time

Sorry I missed this comment. Yeah I liked this idea and I also feel annoying seeing this every time I reload. But since recommendations are owned by PMs I would also take their opinion.

> Or we could think about this in the UX meeting how to show a badge in the activity bar for the extensions viewlet if you like that idea...

Sure, but hope this does not goes into over all recommendations UX discussion 😄

**Comment by isidorn** [comment]
@sandy081 great, then maybe let's start small and only improve **when** this is shown. Not on startup would be great!
Some ideas when we could do it:
* After some timeout. For example 10 minutes
* When first code editor is open
* Only when the user has no other notifications (so we do not show 3+ notifications like in my example)

@devinvalenciano can you be our PM support here. Can you please talk to the PM team and see if there are big objections if we change **when** we show workspace recommendations. Please keep in mind that this is only for workspace recommendations. We would not change the flow of you open a `.py` file and a python recommendation is shown.

**Comment by devinvalenciano** [comment]
Whatever path we take, I'd be interested in running this as an A/B experiment  - that way we can determine whether the changes are beneficial to the user experience.  I'll get this issue in front of the PMs now.

**Comment by isidorn** [comment]
@devinvalenciano makes sense, we can run an experiment. However let's first be creative and try to figure out what is the best `timing` to show the notification. Or if we want go do down the badge in extensions viewlet approach

**Comment by sana-ajani** [comment]
@digitarald @JacksonKearl also, similar to how some of the intermediate content is shown in Getting Started, could the "Limitless extensibility" entry be amended to show the workspace recommended extensions when the user is viewing Getting Started and has a folder open?

**Comment by digitarald** [comment]
I share @JacksonKearl's doubts that Getting Started is the right avenue. It is meant for the _first-time user scenario_, whereas Workspace recommendations are meant for first-time opening of a specific workspace.

I assume we could check how many notifications users see within the first seconds of using VS Code and if this triplet is representative?

> Only show the "Do you want to install the recommended..." once a user opens a Code editor for the very first time

That would work. It moves it off the initial notification storm, as installing extensions will trigger another burst of welcome pages and notifications (until we get those tamed).

Alternatively I had an older UX proposal that moved the notification to a hint on the extension activity bar icon and expanded the existing recommendation section in the extension viewlet. This could combine the various extension recommendations that VS Code does; but potentially lower the rate of users installing the important extensions.

![image](https://user-images.githubusercontent.com/8599/116188694-b6833480-a6dc-11eb-9b3c-e46aa3f6fcae.png)

**Comment by bamurtaugh** [comment]
> Alternatively I had an older UX proposal that moved the notification to a hint on the extension activity bar icon and expanded the existing recommendation section in the extension viewlet.

This reminds me of the badge model we were discussing in https://github.com/microsoft/vscode/issues/121805#issuecomment-825517926. If we shift user thinking to this badge model for a few different flows, they may still be inclined to explore it since they know badge recommendations are useful, but they won't be immediately overwhelmed by multiple notifications.

**Comment by isidorn** [comment]
Conclusion: can we show this notification not on startup but only when the user opens a code editor (not welcome page).
If a code editor is already open on startup then show it on startup.
