### ISSUE TITLE
Can not save because the settings file is dirty

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#121804]
Could we simply automatically save the file in this case and no need to show a notification?
Code pointer https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/workspaces/browser/abstractWorkspaceEditingService.ts#L300

That would make this a much smoother experience

Refs: https://github.com/microsoft/vscode/issues/119463

**Comment by isidorn** [comment]
Same use case here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/configuration/common/configurationEditingService.ts#L259

Could we automatically save those configuration files so we do not get "file is dirty" errors

**Comment by connor4312** [comment]
Are there steps for this? I tried making a conflicting dirty settings files, but I don't think this is what you were talking about...

<img width="464" alt="image" src="https://user-images.githubusercontent.com/2230985/214663199-42d36100-254d-42eb-a5b8-4affa0ce44e7.png">

**Comment by sandy081** [comment]
To verify

- Disable autosave
- Open settings.json file and make it dirty
- Open settings UI and change some settings
- Make sure setting is applied and file is saved.

**Comment by karthiknadig** [comment]
Thanks for the steps @sandy081 that worked.
