### ISSUE TITLE
Remote - SSH not working after 1.56.0-insiders release

### ISSUE THREAD

**Issue by CarlBoneri** [microsoft/vscode#121870]
- VS Code Version: 1.56.0-insider (user setup)
- OS Version: Win10 / Linux

Steps to Reproduce:
4-21-2021 It would appear that the latest insiders build update has broken the ssh remote extension. 
1.  ms-vscode-remote.remote-ssh version 0.65.4

Does this issue occur when all extensions are disabled?: Yes

**Comment by roblourens** [comment]
Please include more details and the log from the Remote-SSH extension. There was an issue in Insiders 2 days ago, please make sure everything is up to date
