### ISSUE TITLE
Terminal profile dropdown tooltip is wrong

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121820]
How about "New With Profile"?

<img width="164" alt="Screen Shot 2021-04-21 at 5 39 05 AM" src="https://user-images.githubusercontent.com/2193314/115555179-12c10100-a264-11eb-9930-4f49ba5aede1.png">

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
