### ISSUE TITLE
Code formatting for embedded Angular 2 template does not work.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#12181]
- VSCode Version: 1.5.2
- OS Version: Linux

Steps to Reproduce:

1.  Inside a angular 2 component, create non aligned template
2. press crtl+shift I, notice the template code doesn't get formatted like new structure html.
2a. selected the template code to be formated, press ctrl+shift I, no formatting is performed.

![format](https://cloud.githubusercontent.com/assets/439226/18607028/6caa56f4-7c8e-11e6-88d4-e277f354dab5.png)

**Comment by waderyan** [comment]
Thanks for opening this issue. Moving to TypeScript language service (powers JavaScript code formatting).

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11011
