### ISSUE TITLE
Can we use the async spdlog everywhere?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#121852]
Currently, the `OutputAppender` in `src/vs/workbench/api/node/extHostOutputService.ts` uses a synchronous logger within spdlog, whereas elsewhere, we use an asynchronous logger.
I'm wondering whether we can replace the call `createRotatingLogger()` with a call like `await createSpdLogLogger()`? The latter creates an asynchronous logger natively.

**Comment by sandy081** [comment]
Not sure if it is trivial to do this because Output API to create is async and this would need introducing buffering and might have unexpected issues as other output APIs are also sync.

**Comment by rzhao271** [comment]
I confirmed that the sync logger is being used in the extension host process, and the async logger is being used in the main process. I was originally thinking that the `setAsyncMode` call meant that the async logger was being used everywhere, but since the two spdlogs are in separate processes, this doesn't seem to be the case, now.

**Comment by sandy081** [comment]
Since I do not think this can be changed in ext host, can I close this?

**Comment by rzhao271** [comment]
Closing. I can just expose a sync logger for #121513, anyways.
