### ISSUE TITLE
exploration: everything feels slower

### ISSUE THREAD

**Issue by untra** [microsoft/vscode#121876]
Issue Type: <b>Bug</b>

The performance of vscode has dropped significantly.

It takes sometimes 2 seconds after hitting ctrl+s that the file will save. my iteration time is tanking with whatever updates have been made to vscode exploration recently.

the source control tab will sometimes show the loading indicator for minutes at a time, and will think long and hard before showing the changes preview.

everything feels slow and delayed in vscode. key presses are still fast, but hotkey commands take a moment and everything just _grinds_

VS Code version: Code - Exploration 1.56.0-exploration (37dee411c81abf7d8ecb28ffe218475c328578b8, 2021-04-09T10:48:12.625Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
json-schema-validation-tool|ama|0.0.1
cypress-snippets|and|1.2.0
vscode-github-actions|csc|0.17.0
vscode-eslint|dba|2.1.20
kotlin|fwc|0.2.22
go|gol|0.24.2
vscode-test-explorer|hbe|2.19.6
beautify|Hoo|1.5.0
ruby-linter|hoo|1.0.0
docthis|joe|0.7.1
vscode-styled-components|jpo|1.5.0
vscode-github|Kni|0.30.5
sort-typescript-imports|mic|1.4.1
ruby-rubocop|mis|0.8.5
vscode-docker|ms-|1.12.1
jupyter|ms-|2021.6.770905982
remote-containers|ms-|0.170.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.3.0
docthis|oou|0.8.2
vscode-yaml|red|0.18.0
code-snapshot|rob|0.2.1
vs-code-prettier-eslint|rve|3.0.2
vscode-cy-helper|She|1.2.2
patternplate-vscode|Sin|0.6.0
code-spell-checker|str|1.10.2
ms-teams-vscode-extension|Tea|1.2.3
shellcheck|tim|0.14.1
vscodeintellicode|Vis|1.2.12
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-maven|vsc|0.29.0
markdown-all-in-one|yzh|3.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
openwslfolder:30278404
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820cf:30276953
pythondataviewer:30285072
vscus158:30286553
vscgsv2:30286872

```

</details>

**Comment by deepak1556** [comment]
This is side-effect of missing fix for https://github.com/electron/electron/issues/26143 in the exploration builds. Please shift to use insiders or stable release that contains the fix.

**Comment by untra** [comment]
@deepak1556 I can confirm the next stable build has improved on this significantly 👍  Thank you!
