### ISSUE TITLE
Intellisense: wrong suggetions for node

### ISSUE THREAD

**Issue by nobil007** [Microsoft/vscode#12182]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:09:51.625Z)
- OS Version: Linux ia32 4.4.0-36-generic

Steps to Reproduce:

1.In my code I used __dirname. [Only 2 '_' as prefix]
2.When I type '_' next time, it will show suggestion. But the suggested string is ___dirname.[3 '_' as prefix]

**Comment by joaomoreno** [comment]
Can totally reproduce. Very strange. @jrieken any idea?

![image](https://cloud.githubusercontent.com/assets/22350/18626692/d67de9fa-7e56-11e6-8be9-b6fba3d465a4.png)

**Comment by jrieken** [comment]
@joaomoreno Unsure what your screen shot shows. But you mean this?
![screen shot 2016-09-19 at 10 58 08](https://cloud.githubusercontent.com/assets/1794099/18626881/f871aff0-7e57-11e6-8ee3-b78bde5cfb93.png)

**Comment by jrieken** [comment]
Iff so its from TypeScript/JavaScript as it's not a word based suggestion but a symbol suggestion from them

**Comment by joaomoreno** [comment]
Yeah. Moving to @waderyan then.

**Comment by nobil007** [comment]
Ya, My issue is same as @jrieken reported.
![vscode](https://cloud.githubusercontent.com/assets/20113351/18627285/cf585a86-7e77-11e6-8be8-fa190c1a03a2.PNG)

**Comment by nobil007** [comment]
The issue in vs code is fine. But the tool [GitHub] which you provided to report the issue have the same issue. One underscore is eliminated from all places in my comment. I had put a underscore in between the single quotes in " [Only 2 '' as prefix] ". But is not showing in the view. But it shows in the editing view.

**Comment by waderyan** [comment]
Thanks for opening this issue. As this falls under the TS language service moving to them.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#11015
