### ISSUE TITLE
terminal-debian icon went missing in today's build

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121834]
<img width="438" alt="Screen Shot 2021-04-21 at 7 26 45 AM" src="https://user-images.githubusercontent.com/2193314/115570488-03957f80-a273-11eb-9d44-c27698c5cefc.png">
<img width="154" alt="Screen Shot 2021-04-21 at 7 26 49 AM" src="https://user-images.githubusercontent.com/2193314/115570494-055f4300-a273-11eb-83e5-0df3afe20038.png">

**Comment by misolori** [comment]
Huh, not sure how this came up but looks like in the codicon source I mistyped the name (but that was two weeks ago):

<img width="491" alt="CleanShot 2021-04-21 at 09 49 11" src="https://user-images.githubusercontent.com/35271042/115591379-e23e8e80-a286-11eb-885a-a0b16ed37dcd.png">

Must've been related to the ubuntu change. Pushing a fix shortly.

**Comment by misolori** [comment]
Fixed via https://github.com/microsoft/vscode/commit/d97790d16248ed363f509117f51d9bc09cb08409

<img width="236" alt="CleanShot 2021-04-21 at 09 54 51" src="https://user-images.githubusercontent.com/35271042/115592216-cedff300-a287-11eb-81fd-eefa21c4e96a.png">
