### ISSUE TITLE
Visual Studion code does not keep the old search results in the search pane or provide a drop down list of previous search phrases.

### ISSUE THREAD

**Issue by thomas-anil** [Microsoft/vscode#12184]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Search for any symbol using the search option in VS code IDE. 
2. Search results will be shown in the search results pane.
3. Search for another symbol.
4. Search results for the second search will replace the search results of the first search.
5. It is very annoying because I, as a developer, at many times am interested in following more than one symbol.
Keeping the previous search results in the same search results pane is very much needed feature.  Newer search results may be listed at the top and previous search results may be listed below the newer results in chronological order.
6. Also please provide a dropdown menu for the search results listing the previous search strings.  Keeping all the search strings in some editor and copying them again and again for searching is very annoying and time consuming.

**Comment by sandy081** [comment]
Search history is implemented in this - #5508. You can try this by downloading our [insiders build](https://vscode-builds.azurewebsites.net/insider)
With this feature you can always navigate between previous and current results. IMO, showing search results of current and previous search would in the same view might be confusing.

@thomas-anil Let me know if this suffice your requirement?

**Comment by sandy081** [comment]
Closing this as there is no feedback from last 14 days.

**Comment by thomas-anil** [comment]
Hi Sandeep,


Thank you very much for the support.  I tried to download the insiders build. But I am not able to visit the page. the system says "

Sorry, but we’re having trouble signing you in.

We received a bad request."


I am able to login to my outlook mail account. Can you please check or help me fix this. Then I will checkout the build for the feature I requested.


or


Can you please send me a direct link to the build or some other way of accessing the build?


Thank you very much


regards

Anil Thomas



________________________________

**Comment by sandy081** [comment]
@thomas-anil Which link are you accessing for insiders?

**Comment by leup** [comment]
>  IMO, showing search results of current and previous search would in the same view might be confusing.

I would very much like to have search results history in different panes, as I was used to in Netbeans for example. May be as an option for people who don't want that.

**Comment by sandy081** [comment]
Duplicates #16488
