### ISSUE TITLE
[Terminal] Not able to close the terminal

### ISSUE THREAD

**Issue by stagefright5** [microsoft/vscode#121809]
### Steps to Reproduce:

1. Open VS Code
2. Try to delete the terminal

#### Video

https://user-images.githubusercontent.com/15051871/115546249-695d2800-a2c2-11eb-9496-e75f36e845c1.mp4

### Other Relevant Settings:

```json
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
```
### Env

- Version: 1.56.0-insider (user setup)
- Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
- Date: 2021-04-21T05:13:42.491Z
- Electron: 12.0.4
- Chrome: 89.0.4389.114
- Node.js: 14.16.0
- V8: 8.9.255.24-electron.0
- OS: Windows_NT x64 10.0.19043

Does this issue occur when all extensions are disabled?: Yes ~~/No~~

**Comment by stagefright5** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Terminal input does not work with NVDA (#121735)](https://www.github.com/microsoft/vscode/issues/121735)

This does not look like a related issue

**Comment by tymsai** [comment]
next time put a gif instead of a video,
thanks.

**Comment by stagefright5** [comment]
Well, It is hard to inspect gif than the video.
1. Video can be seek-ed.
2. Video can be paused.
These things matter especially when it is a bug report.

> next time put a gif instead of a video,
> thanks.

Unless there are more compelling reasons, I don't think so.

Regards

**Comment by meganrogge** [comment]
Thanks this should be working in tomorrow's insiders
