### ISSUE TITLE
Add a "sessionName" property to the "presentation" property of the launch config

### ISSUE THREAD

**Issue by gionapaolini** [microsoft/vscode#121824]
Context:
I have the following setup: https://stackoverflow.com/a/67188838/5647864 in which basically when I click on "Start debugging" on that specific configuration, i get asked which specific environment I want to debug, and the right port will be chosen.

The issue:
When running multiple debugging session on the same service but different environments, in the UI I get sessions name like "Service1", "Service1-2" ... etc. So you don't really know which environment you are debugging.

Feature request:
I would like to have a feature where you can set the name of the debugging session. And I would like this name to accept variable values. 

Something like 
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Service1",
      "sessionName": "${input:envType[0]}"   <-----------------
      "type": "python",
      "request": "attach",
      "connect": {
        "host": "127.0.0.1",
        "port": "${input:envType[1]}"
      }
    }
  ],
  "inputs": [
    {
      "id": "envType",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Which env do you want to debug?",
        "options": [
          ["development", "5000"],
          ["staging", "5100"],
          ["live", "5200"]
        ],
        "default": "5000"
      }
    }
  ]
}
```

**Comment by isidorn** [comment]
Fair feature request, but we do not have it on the plan right now, thus assigning to backlog.
