### ISSUE TITLE
Open terminal profile button is empty

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#121818]
No errors in console

<img width="272" alt="Screen Shot 2021-04-21 at 5 31 33 AM" src="https://user-images.githubusercontent.com/2193314/115553974-db058980-a262-11eb-8532-7d0ad9127bcc.png">
<img width="319" alt="Screen Shot 2021-04-21 at 5 32 08 AM" src="https://user-images.githubusercontent.com/2193314/115554044-ebb5ff80-a262-11eb-8e52-610d8a02e474.png">

**Comment by rzhao271** [comment]
What does it mean for the button to be empty?
I added the `verified` label because I now see a list of profiles to choose from, but feel free to mention if that's not what the bug was.

**Comment by meganrogge** [comment]
Yep @rzhao271 the bug was that the profiles weren't listed 👍🏼
