### ISSUE TITLE
Single editor no longer maximized

### ISSUE THREAD

**Issue by Norfeldt** [microsoft/vscode#121814]
Issue Type: <b>Bug</b>

When view a single editor it is no longer maximized and it's not possible to drag it to be.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.29GB free)|
|Process Argv|--crash-reporter-id da93cbf1-ab79-4dec-8a94-0adbb0b15daa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (93)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-color|ans|0.4.5
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-yaml-preamble|bie|0.0.4
turbo-console-log|Cha|2.1.6
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
vscode-css-modules|cli|0.2.3
vscode-github-actions|csc|0.17.0
vscode-svgviewer|css|2.0.0
hex-to-rgba|dak|1.0.0
vscode-markdownlint|Dav|0.40.3
open-in-sketch|dav|2.1.0
vscode-eslint|dba|2.1.20
css-flexbox-cheatsheet|dzh|3.2.2
git-cheatsheet|dzh|1.4.2
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
vscode-npm-script|eg2|0.3.21
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|6.3.2
auto-close-tag|for|0.5.10
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.6
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.25.1
pyformat|giy|1.0.2
vscode-git-tags|how|1.4.4
vscode-edit-csv|jan|0.5.8
vscode-peacock|joh|3.9.1
vscode-styled-components|jpo|1.5.0
color-the-tag-name|jzm|0.17.0
vscode-gutter-preview|kis|0.27.1
cortex-debug|mar|0.3.12
rainbow-csv|mec|1.8.1
render-crlf|med|1.5.17
template-string-converter|meg|0.4.7
vscode-language-babel|mgm|0.0.31
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
cpptools|ms-|1.3.1
node-debug2|ms-|1.42.6
vs-keybindings|ms-|0.2.1
vsliveshare|ms-|1.0.4131
debugger-for-chrome|msj|4.12.12
vscode-react-native|msj|1.4.1
indent-rainbow|ode|7.5.0
vscode-jest|Ort|3.2.0
particle-vscode-core|par|1.13.7
particle-vscode-pack|par|1.13.7
particle-vscode-snippets|par|1.13.7
vscode-versionlens|pfl|1.0.9
inline-html|pus|0.2.5
java|red|0.77.0
vscode-commons|red|0.0.4
vscode-xml|red|0.16.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
autoimport|ste|1.5.4
code-spell-checker|str|1.10.2
open-in-browser|tec|2.0.0
vsfire|tob|1.4.1
vscode-status-bar-format-toggle|tom|2.0.0
pdf|tom|1.1.0
selectline-statusbar|tom|0.0.2
lorem-ipsum|Tyr|1.2.0
alphabetical-sorter|ue|2.0.1
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
vscode-svg-previewer|vit|0.7.0
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
vscode-todo-highlight|way|1.0.4
highlight-bad-chars|wen|0.0.3
rtlcheatsheet|wil|1.0.0
glean|wix|5.2.2
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
cursorCharCode|zei|0.2.0
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553

```

</details>

![Apr-21-2021 14-15-29](https://user-images.githubusercontent.com/678806/115551979-0d87a480-a2ac-11eb-9553-4d6e898a1656.gif)

**Comment by isidorn** [comment]
F1 > toggle centered mode

**Comment by Norfeldt** [comment]
Thanks! It was driving me nuts 🤪
