### ISSUE TITLE
Cannot set breakpoint in assembly file

### ISSUE THREAD

**Issue by joeparis** [microsoft/vscode#121984]
Issue Type: <b>Bug</b>

1. Create a new folder.
1. Open folder in VS Code
1. Create a new assembler source file (with .asm extension)
1. Click in the margin to the left of line numbers

Expected result: a breakpoint would be set on the selected line

Actual result: sadness and depression as nothing happens

The exact same thing happens when using the Remote WSL extension to open a workspace there.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.68GB free)|
|Process Argv|--crash-reporter-id ba78d1dc-d701-4dc4-86d2-76d9a33d64d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (75)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|2.1.0
Bookmarks|ale|13.0.4
emojisense|bie|0.8.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
markdown-yaml-preamble|bie|0.0.4
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.2.0
vscode-autohotkey-plus|cwe|2.6.2
vscode-markdownlint|Dav|0.40.3
vscode-quick-select|dba|0.2.9
vscode-pandoc|Dou|0.0.8
gitlens|eam|11.4.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
vscode-firefox-debug|fir|2.9.4
codespaces|Git|0.9.4
vscode-pull-request-github|Git|0.25.1
mdmath|goe|2.5.1
vscode-test-explorer|hbe|2.19.6
vscode-guid|hea|1.4.20
latex-workshop|Jam|8.17.0
plantuml|jeb|2.14.5
better-cpp-syntax|jef|1.15.5
polacode-2019|jef|0.5.2
vscode-hacker-typer|jev|0.1.1
vscode-python-test-adapter|lit|0.6.8
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.19
vscode-autoprefixer|mrm|3.0.1
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
gather|ms-|2021.4.0
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.54.6
vscode-remote-extensionpack|ms-|0.20.0
cmake-tools|ms-|1.7.1
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.5.0
powershell|ms-|2021.2.2
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
autodocstring|njp|0.5.4
printcode|nob|3.0.0
indent-rainbow|ode|7.5.0
material-icon-theme|PKi|4.6.0
vscode-css-peek|pra|4.1.3
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
partial-diff|ryu|1.4.3
indenticator|Sir|0.7.0
code-spell-checker|str|1.10.2
vscode-status-bar-format-toggle|tom|2.0.0
vscode-pets|ton|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.6.2
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
x86|whi|0.3.3
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.13
html-css-class-completion|Zig|1.20.0

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by isidorn** [comment]
Please report against .asm extension, thank you
