### ISSUE TITLE
Make the app installation process easier on macOS

### ISSUE THREAD

**Issue by rakleed** [microsoft/vscode#121973]
Please make the process of installing the app on macOS more convenient either by making a DMG installer with the Applications folder and the app itself or immediately after launching, prompt the user to move the app to the Applications folder (if you determine that the app is not launched from the Applications folder).

**Comment by rakleed** [comment]
@joaomoreno please reconsider your decision about this feature request. Since almost all other apps for macOS have a DMG installer or offer to move the app to the Application folder. Accordingly, due to the fact that you do not support this feature, it is less convenient to use your app.

**Comment by yinhunfeixue** [comment]
@rakleed 

Hello, could you please tell me how to package an APP in MacOS?

The following command  is packed with
vscode-darwin-x64
vscode-darwin-x64-ci

thanks
