### ISSUE TITLE
Integrated terminal is slow/laggy

### ISSUE THREAD

**Issue by codec-abc** [Microsoft/vscode#12199]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open the integrated terminal
2. Type in the console

It works as expected but every character typed in the terminal appear after 0.5~1s. I have the same setup at work but the console is responsive. So there is probably something in my home setup that don't play nicely with the integrated terminal. Note, that if I open a command prompt (or a powershell prompt) outside VSCode the prompt is responsive like I expect it to be. by the way, my computer is more than capable of running VSCode fine. To sum up, the terminal is slow only in VSCode for a reason I don't understand.

**Comment by markschad** [comment]
I can confirm this behavior in version 1.5.2

There is a small chance that the terminal will operate smoothly, but I have no idea what causes this.

**Comment by Tyriar** [comment]
Duplicate #10328
