### ISSUE TITLE
Terminal stopped working under Windows

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#121900]
In the latest Insider Release 

Version: 1.56.0-insider (user setup)
Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
Date: 2021-04-22T05:13:14.711Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

the terminal stopped working under Windows when using PowerShell or CMD. WSL still works. The effect is that you can't type in the terminal at all. I tried to modify `terminal.integrated.windowsEnableConpty` without success.

Windows OS Details:

Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎13-‎May-‎20
OS build	19043.962
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by dbaeumer** [comment]
I tried stable and it still works. So doesn't seem to be related to the Windows version.

**Comment by Tyriar** [comment]
We're tracking this in https://github.com/microsoft/vscode/issues/121685 but yesterday (I thought) we narrowed this down to an issue with winpty specifically. Can you check your shared process log for any errors?

**Comment by soundoff** [comment]
Same experience here using GitBash in terminal.  Started after last update.  Official release is good.

Version: 1.56.0-insider (user setup)
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:13:42.491Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by Tyriar** [comment]
@soundoff do you have `windowsEnableConpty` set?

**Comment by soundoff** [comment]
> @soundoff do you have `windowsEnableConpty` set to false?

It is enabled.

**Comment by dbaeumer** [comment]
@Tyriar no exception in the shared process log but this:

[2021-04-22 19:57:37.107] [sharedprocess] [warning] No ptyHost heartbeat after 6 seconds
[2021-04-23 08:31:57.109] [sharedprocess] [warning] No ptyHost heartbeat after 6 seconds

**Comment by Tyriar** [comment]
This is a duplicate, it's caused by the electron update.
