### ISSUE TITLE
`code dir && exit` causes inifinite opening of vscode

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#121992]
- VS Code Version: v1.55.2
- OS Version: Windows 10

Steps to Reproduce:

Say we have a file structure like so:

```
current-dir
  └ dir
```

Use `code dir && exit`(bash) will cause infinite opening of vscode, what did I do wrong?

Does this issue occur when all extensions are disabled?: Yes

**Comment by wenfangdu** [comment]
@eamodio Sorry to bother you, is it caused by https://github.com/microsoft/vscode/issues/66750?

**Comment by eamodio** [comment]
Oh, possibly. @Tyriar?

**Comment by wenfangdu** [comment]
Can you please consider reopen this? @Tyriar

**Comment by wenfangdu** [comment]
@Tyriar Strange, it was broken in `v1.55.2` and works in `v1.56.0`.
