### ISSUE TITLE
Git remote and branch misparsed when remote contains a slash

### ISSUE THREAD

**Issue by Rua** [microsoft/vscode#121914]
- VS Code Version: 1.55.2
- OS Version: Linux Mint 20.1

Steps to Reproduce:

1. Make a git repository with a remote that has a slash in the name, e.g. `foo/origin`.
2. Try to pull or push in VSCode.
3. Resulting git output:
   ```
   > git pull --tags foo origin/master
   fatal: 'foo' does not appear to be a git repository
   fatal: Could not read from remote repository.
   ```

VSCode tries to pull from the wrong remote and branch. It appears to use only the part before the slash as the remote, and adds the part after the slash to the branch: `foo origin/master` instead of correct `foo/origin master`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by nbraud** [comment]
I can reproduce the bug.

**Comment by cdce8p** [comment]
The fix from https://github.com/microsoft/vscode/commit/6011bf7e7ad87a06908e9947fd5ccd948739f953 does break when the local branch name doesn't match the upstream one. I opened #144449 to address that.

**Comment by lszomoru** [comment]
I have reverted this fix as it has introduced a regression. Reopening the issue.
