### ISSUE TITLE
Replace selected doesn't put focus in the find edit field

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#12193]
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:22:54.636Z)
- OS Version: Linux x64 4.4.0-36-generic

Steps to Reproduce:

1. Selected a section of code.
2. Pressed ctrl+h to replace text

Notice the focus is put into "replace" edit window not "find" where it should be.

**Comment by alexandrudima** [comment]
The current behavior is:
* `ctrl+f` focuses the find input box
* `ctrl+h` focuses the replace input box

That would make `ctrl+h` be almost exactly as `ctrl+f`. You could in this case rebind `ctrl+h` to do what `ctrl+f` does by editing your keybindings.

**Comment by rajinder-yadav** [comment]
OK I got confused, when I enter this bug it was not selecting the text and putting it into the find window, everything seem to be working fine.
