### ISSUE TITLE
Native Notebooks - Language Picker Glitchy/Not Loading

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#121983]
- VS Code Version: 1.56.0 - insider
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open native notebook in insiders
2. Try to select language picker

![Language Picker Glitchy](https://user-images.githubusercontent.com/19276747/115819859-8f62f500-a3b4-11eb-82cf-ca569d26f656.gif)

**Comment by roblourens** [comment]
This one should be fixed already
