### ISSUE TITLE
comment not working , going live issue

### ISSUE THREAD

**Issue by Khush900** [microsoft/vscode#121944]
Issue Type: <b>Feature Request</b>

comments like '//' and /* not working in my vs code and also i am facing issue in going live

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by RMacfarlane** [comment]
Do you mean the colors aren't updating when you comment out code? Can you describe what's happening in more detail, and what programming language you're using?
