### ISSUE TITLE
Freezes or stops on Reload Window

### ISSUE THREAD

**Issue by pybash1** [microsoft/vscode#121915]
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:00.942Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT ia32 6.1.7601

Steps to Reproduce:
1. Open VS Code
2. Open Command Palette
3.  Select - "Developer: Reload Window"

Does this issue occur when all extensions are disabled?: Don't know, probably yes!

## Actual Problem
After Reloading the window, it doesn't reload, stays as it is! But, all extensions stop working. Search and Replace doesn't work! And many other things! Doesn't really freeze!

**Comment by pybash1** [comment]
> /gifPlease

There's no point in providing a gif! Beacuse after reloading nothing happens! so the gif will be like an image basically, only the extensions stop working!

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by pybash1** [comment]
Alright I'll try that.
