### ISSUE TITLE
Connection Session Ending Abruptively 

### ISSUE THREAD

**Issue by Miro8896** [microsoft/vscode#121906]
Hello,

Me and my team are trying to work on the same collaboration session but lately it keeps on kicking us out of the collaboration session after about one minute. We've tried everything, even changed the internet connection, but nothing seems to help. Any clues why this error pops up?

Regards,
Miro

![image](https://user-images.githubusercontent.com/73107396/115685322-69a80280-a358-11eb-89f6-8bee57cd2f2b.png)

**Comment by Miro8896** [comment]
There's also this log: 
![image](https://user-images.githubusercontent.com/73107396/115688213-3b77f200-a35b-11eb-83de-e91d6e6c997c.png)

**Comment by altechzilla** [comment]
All extensions other than Live Share have been removed from the host machine and **the Extension Host is still crashing.**

**Comment by altechzilla** [comment]
@eamodio

**Comment by eamodio** [comment]
Please open an issue for the Live Share team.

**Comment by altechzilla** [comment]
@Miro8896
