### ISSUE TITLE
What the shortcut to jump to error line shown in debug console?

### ISSUE THREAD

**Issue by CA10C3SAR** [microsoft/vscode#121976]
- VS Code Version: 1.55.2
- OS Version: win10

Hi, I'm debugging an AutoHotkey script, when there's an error like on the image below, if i press the shortcut F8 it does not jump to the line:
![image](https://user-images.githubusercontent.com/6724006/115793624-d7791c00-a3a2-11eb-9f3e-a793e628dbad.png)

Isn't the F8 key to jump to the error line?
![image](https://user-images.githubusercontent.com/6724006/115793761-1313e600-a3a3-11eb-8c99-1de196e29e8d.png)

Only goes to the line if i ctrl+click the message. There's any other shortcut for this action?

**Comment by isidorn** [comment]
No unfortunetly there is no shortcut for this. If you want to use the keyboard you have to move the focus on the debug console, find the link and press enter or space.

We currently do not plan to change this, thus closing this as designed
