### ISSUE TITLE
tab for list.focusDown command works not like DownArrow

### ISSUE THREAD

**Issue by aserowy** [microsoft/vscode#121985]
- VS Code Version:
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
- OS Version:
OS: Windows_NT x64 10.0.19042

Expected:

With tab bound to list.focusDown, my expectation was, that navigation behaves exactly like DownArrow with the same command.

Behaviour:

Tab navigates a line down. Tab again then focuses the quick fix icon in the list and does not select the next entry.
On fast tab presses or holding tab, the navigation stops completely (randomly).

Steps to Reproduce:

1. Create the following keybinding:   {
    "key": "tab",
    "command": "list.focusDown",
    "when": "listFocus && !inputFocus"
  }
2. Install a lsp for e.g. markdown 
3. Create multiple problems in two files which can be quick fixed
4. Focus the first problem in the list of your problems panel
5. Expand all problems
![image](https://user-images.githubusercontent.com/8199164/115821077-6701e780-a402-11eb-89aa-4ec7d1f3f033.png)
6. Hit tab to navigate through your problems
![image](https://user-images.githubusercontent.com/8199164/115821116-7c771180-a402-11eb-8e5d-1dce9825c12d.png)
![image](https://user-images.githubusercontent.com/8199164/115821151-8b5dc400-a402-11eb-9d84-d834824a3185.png)
7. Navigation gets stuck randomly while holding tab
![image](https://user-images.githubusercontent.com/8199164/115821278-cd870580-a402-11eb-970b-5bd750f41e28.png)

Does this issue occur when all extensions are disabled?: Yes/No

This is not possible, because without lsp support, no quick fixes are available. I replicated the behaviour with all extensions disabled and two different lsp (markdownlint & rust analyzer), one activated at a time.

**Comment by joaomoreno** [comment]
Due to accessibility features, Tab is a special key and I would avoid assigning it to commands. Closing this as a scenario which we can't support. cc @isidorn

**Comment by isidorn** [comment]
Yup, makes sense to not assign commands to `tab`

**Comment by aserowy** [comment]
hi,

dont want to reopen it. Just for further clarification: Why is it even possible to assign tab for commands?

king regards
