### ISSUE TITLE
Terminal always launches externally

### ISSUE THREAD

**Issue by halcwb** [microsoft/vscode#121998]
Issue Type: <b>Bug</b>

Read all the issues reports and stackoverflow solutions but I can't get VS to launch a git bash terminal as internal.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (26.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by yume-chan** [comment]
What's your `terminal.integrated.shell.windows` settiing?

See #7286

**Comment by halcwb** [comment]
That setting was set to the git bash path.

**Comment by halcwb** [comment]
By the way, it works Ok with using powershell (default), so I switched to PS.

**Comment by Tyriar** [comment]
This means you set the path to the git bash _terminal_, not _shell_. We pick up the correct path for you here:

![image](https://user-images.githubusercontent.com/2193314/116091275-834b9180-a659-11eb-8d23-b20bc923743d.png)

**Comment by halcwb** [comment]
@Tyriar Thanks. My bad didn't understand the difference between a terminal and a shell: https://www.hanselman.com/blog/whats-the-difference-between-a-console-a-terminal-and-a-shell.
