### ISSUE TITLE
Ordering of decorations from different extenstions

### ISSUE THREAD

**Issue by FredCoen** [microsoft/vscode#121930]
I have a vs code extension that uses the decoration api to set decoration at a given range  displaying markdown when hovering over that line. Intellisense a very popular vs code extension shows markdown when hovering over the same range as well. How can one order those markdowns? Currently, intellisense markdown is shown last. I want the markdown of my extension to be shown last instead because intellisense is more important. I don't think the api provides any way to order these markdowns from different extenstions. If that is true, how does vscode determine the order? Could we add an ordering option to the api?

**Comment by FredCoen** [comment]
@jrieken any update on this? Unfortunately its a blocking element in our VS code extension development

**Comment by jrieken** [comment]
Extensions cannot influence the order and we don't want to allow them to do that because, naturally, extension authors want their contribution to show at the most prominent place.

**Comment by FredCoen** [comment]
Thanks for your response. I would tend to disagree that extension authors want their contribution to show at the most prominent place in every scenario, especially when something like Intellisense is a vital feature for any developer using VS Code. Could you shed some light on how VS code prioritizes the ordering internally @jrieken ?

**Comment by jrieken** [comment]
> Could you shed some light on how VS code prioritizes the ordering internally @jrieken ?

It depends on each feature

**Comment by nbransby** [comment]
@jrieken since @FredCoenis in fact asking for his extension to show in a less prominent place that the built-in contributions perhaps you could reopen this ticket as bug that 3rd party extension contributions are showing at the most prominent place than Intellisense?
