### ISSUE TITLE
On Macbook mono process goes to 400% of the CPU at regular interval

### ISSUE THREAD

**Issue by seb999** [microsoft/vscode#121942]
- VS Code Version: 1.55
- OS Version: Catalina 10.15.7

Steps to Reproduce:

1. Open a dotnet core 5.0 / angular project
2. run project in debbug mode
3. the fan of the computer will become crazy / it is hard to work
4. solution is to kill mono process but then you loose the intellicente and it is simply not possible to work 

CPUs | Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (1.09GB free)
Process Argv | --crash-reporter-id ef0c5ab3-61ea-482a-9968-7dd422fe0185
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
ng-template | Ang | 11.2.11
npm-intellisense | chr | 1.3.1
es7-react-js-snippets | dsz | 3.1.1
vscode-npm-script | eg2 | 0.3.21
ionic2-vscode | jgw | 1.0.0
vscode-webpack | Kni | 1.1.0
csharp | ms- | 1.23.11
vscode-typescript-tslint-plugin | ms- | 1.3.3

vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551:30291414
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

Does this issue occur when all extensions are disabled?: Yes

**Comment by eamodio** [comment]
Please open an issue against the C# extension. Thanks!

**Comment by seb999** [comment]
Okay. Thank you for your reply.
Best regards

**Comment by seb999** [comment]
In fact the problem comes from C# for Visual Studio Code (powered by
OmniSharp) extension
Both are not a Microsoft product ? Don't you have to test Visual Studio
Code with Microsoft basic extension lille C# one?
Anyway I cannot use Visual Studio Code, great news.
Best Regards
