### ISSUE TITLE
NotebookController.interruptHandler to pass the notebook document

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#121912]
Please can we pass the `NotebookDocument` to this method.
This way we can use the same notebookcontroller for all documents.
Today we create multiple, one for each Document.
I'd prefer to create a single set of controllers.

 @jrieken  /cc

**Comment by jrieken** [comment]
Done, it's now 

```ts
	export interface NotebookInterruptHandler {
		/**
		 * @param notebook The notebook for which the interrupt handler is being called.
		 */
		(this: NotebookController, notebook: NotebookDocument): void | Thenable<void>;
	}
```
