### ISSUE TITLE
Use If statement

### ISSUE THREAD

**Issue by rupakswadesh** [microsoft/vscode#121929]
Issue Type: <b>Bug</b>

when i am using if statement and put condition which have already open and close bracket then if statement close bracket remove issue.
example-  if('abc'==test.getName()

in this case of typing, if statement remove close bracket at the end of statement, you can see above.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

**Comment by mjbvz** [comment]
I don't understand this issue. Please share:

1. A step by step explanation of how to reproduce the issue 
2. What you expected to happen
3. What actually happened

/needsMoreInfo
