### ISSUE TITLE
Can't delete terminal window after opening

### ISSUE THREAD

**Issue by ShubhamVerma1811** [microsoft/vscode#121901]
- VS Code Version:Version: 1.56.0-insider (user setup)
Commit: 23a2409675bc1bde94f3532bc7c5826a6e99e4b6
Date: 2021-04-21T05:13:42.491Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042
- 
- OS Version:
- Device name	Photon
Processor	AMD Ryzen 5 2600 Six-Core Processor               3.40 GHz
Installed RAM	16.0 GB
Device ID	XXX-XXX
Product ID	XX-XX
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Steps to Reproduce:

1.Click on the + button in the intergrated terminal
2.Click on the trash icon to delete

Expected : Terminal gets delete/closed
Result : Error msg (intermediate value)(intermediate value)(intermediate value).dispose is not a function

Does this issue occur when all extensions are disabled?: Yes/

Heres the image : 
![Screenshot (24)](https://user-images.githubusercontent.com/25576658/115674559-679b6f00-a36b-11eb-82ea-4072383cdd53.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by ShubhamVerma1811** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

I am on the insiders build when it occurred.
Anyways I tried to check the issue first but it's difficult to find it in 5K issues.
