### ISSUE TITLE
Terminal session hangs during commands

### ISSUE THREAD

**Issue by aravindspark** [microsoft/vscode#121909]
Steps to reproduce:

- Go to a directory where large list of files located. say 2500
- do ls on shell $ls , keep repeating it.
- Terminal session hangs at somepoint

vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

**Comment by RamiHg** [comment]
This is possible related to https://github.com/microsoft/vscode/issues/120300.
