### ISSUE TITLE
Node hangs without any message in the debug terminal

### ISSUE THREAD

**Issue by fredddy123** [microsoft/vscode#121950]
Issue Type: <b>Bug</b>

1. open the debug terminal
2. run: "node" or "node filename.js"

ER:
node CLI is opened or the filename.js is executed
AR:
nothing happens

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id fad26cbe-9844-4c39-aac3-dd62ded8685a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
beautify|Hoo|1.5.0
rainbow-csv|mec|1.8.1
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
js-debug-nightly|ms-|2021.4.2117

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

**Comment by fredddy123** [comment]
found a solution. still don't know what caused that, but deleting `/Users/<username>/Library/Application Support/Code` helped.

**Comment by isidorn** [comment]
Great, closing then
