### ISSUE TITLE
Vscode debbuger & ubunto, unabale to open ...

### ISSUE THREAD

**Issue by IsraelCohen54** [microsoft/vscode#121931]
Hello everyone!
How can I easily fix it without reinstallation? as from googling it, its sound comlicated...
(After changing something in my code I dont see it anymore, but its not the first time I saw that, and I wonder if there is a quick fix for it)

> Unable to open 'strcmp-avx2.S': Unable to read file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-ZN95T4/glibc-2.31/sysdeps/x86_64/multiarch/strcmp-avx2.S' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-ZN95T4/glibc-2.31/sysdeps/x86_64/multiarch/strcmp-avx2.S').

When trying to open whatever local folder or something it say its needing, it paste this:

> Unable to write file 'vscode-remote://wsl+ubuntu-20.04/build/glibc-ZN95T4/glibc-2.31/sysdeps/x86_64/multiarch/strcmp-avx2.S' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/build')

TERMINAL:

> [1] + Done                       "/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-mhnpm5ir.thc" 1>"/tmp/Microsoft-MIEngine-Out-zi4alcxx.sqx

**Comment by aeschli** [comment]
@IsraelCohen54 Can you give more informatoon. What kind of project is that, what are the actions you are performing?

Is this the same issue as https://github.com/microsoft/vscode-remote-release/issues/4929 ?

**Comment by IsraelCohen54** [comment]
Probably the same, but I didnt see there any simple way to solve it... thanks anyway, guess I will manage :)
The code is writing basic shell in C. (mark where's the prob with //~~~explaination~~~)
`int main(void) {
    char str[1024];
    int waited0, stat0; 
    char *args[64]={};
    int k=0;
        while(k==0) {
        printf("$ "); 
        fgets(str, 100, stdin);
        strip(str);
        parse (str, args);
        char text[100];
        sprintf(text,"/bin/%s",args[0]);
        int i=0;
        char *check[100]={};
        while (args[i]!=NULL) {
          check[i]=args[i];
         i++; }
        if (!strcmp(args[0],"exit")) //~~~here is the cause, when I change it from 'args' to 'check' it works good. ~~~ 
        {
          k=1;
          waited0=wait(&stat0);
          return 0; 
        }
        else 
        do_user_input(check);
        }
}`

**Comment by aeschli** [comment]
I still don't understand what's the issue about... Please give steps and describe what happens and what is expected.

**Comment by IsraelCohen54** [comment]
As I said its looks like a common prob, that I dont understand it exactly.
 The steps as described, change args =>check and it somehow solve the prob...
Even though their definitions are almost the same...
Thanks for trying, I guess I will manage. All the best :)
