### ISSUE TITLE
tmLanguage stopped working since 1.3.1

### ISSUE THREAD

**Issue by heartsekai** [Microsoft/vscode#12197]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:
1. install vs 1.2.1 tmLanguage work
2. install vs 1.3.1 tmLanguage doesn't work

You have a wms file to check it.
[brainwarecolumbus.zip](https://github.com/Microsoft/vscode/files/478376/brainwarecolumbus.zip)

**Comment by bpasero** [comment]
@heartsekai are you talking about an extension?

**Comment by heartsekai** [comment]
Hello Benjamin

Yes, well a language Packet.

_____________________________

**Comment by aeschli** [comment]
The problem is with your file: 
"Error parsing brainwarecolumbus/syntaxes/columbus.tmLanguage: Near offset 1095: too many <key> ~~~
                <string>^\s*([aA-zZ]+)\s*(=)\s*(~~~"


I created https://github.com/Microsoft/vscode-textmate/issues/34 to make the error visible in the console.
