### ISSUE TITLE
Allow to hide the activity view bar

### ISSUE THREAD

**Issue by LiPengfei19820619** [Microsoft/vscode#12191]
- VSCode Version:1.5.2
- OS Version:Windows 10 1607 64Bit

Steps to Reproduce:

1. Open the visual studio code

I hope I can control whether to show or hide the view bar area, because I like to use the whole screen to edit.

Thank you.

**Comment by LiPengfei19820619** [comment]
@bpasero        Thank you for your attention.

**Comment by Tyriar** [comment]
Duplicate #1105
