### ISSUE TITLE
"Accept Suggestion On Enter" not smart enough

### ISSUE THREAD

**Issue by jsh9** [microsoft/vscode#121995]
- VS Code Version: 1.53.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a blank Python script
2. Start typing: `import numpy as np`, and you will see this:

![image](https://user-images.githubusercontent.com/25124332/115831872-043f2a80-a3c7-11eb-99a8-976657393238.png)

If you set "Accept Suggestion On Enter" to "smart", and when you press enter, you'll get:

```python
import numpy as numpy
```

I only have one extension installed when reproducing this step.  This extension is the official "Python" extension.

Does this issue occur when all extensions are disabled?: N/A

**Comment by gjsjohnmurray** [comment]
It appears that you haven't set the language mode of your new file to be Python. The icon at the left end of the tab is the generic one used when language mode is Plan Text. Click on the panel at the right-hand end of the status bar:

![image](https://user-images.githubusercontent.com/6726799/115840084-35dde300-a413-11eb-825e-f70b9fcc5ac9.png)

**Comment by gjsjohnmurray** [comment]
If you want all new files to be Python, use this setting:

![image](https://user-images.githubusercontent.com/6726799/115840659-d207ea00-a413-11eb-8d90-74671f2a9b28.png)

**Comment by jsh9** [comment]
Hi @gjsjohnmurray , I set the language to Python manually, and then I set "Accept Suggestion On Enter" to "smart", but VSCode still replaced my `np` with `numpy`.

![image](https://user-images.githubusercontent.com/25124332/115945682-a0be0700-a471-11eb-95fd-ad9c2cb3f945.png)

![image](https://user-images.githubusercontent.com/25124332/115945689-ad425f80-a471-11eb-8f06-a1ecfd0ac898.png)

**Comment by jrieken** [comment]
@jsh9 your initial screen shot shows that you don't have the `np` suggestion, therefore it cannot be accepted or be smart about it. After changing the language to python, do you get that suggestion?
