### ISSUE TITLE
new terminal switcher no longer transfers keyboard focus to selected terminal

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#121954]
selecting a terminal in the new terminal pane no longer transfers the keyboard focus to the selected terminal.
As a result my keyboard input is always lost until I notice that the terminal pane has focus.

The old terminal switcher did not have this painful behavior.

**Comment by Tyriar** [comment]
Just like with the explorer and editor, it's double click or enter to focus the terminal. Without this it's not clear how you would focus the list via the mouse to navigate it with the keyboard.

@joaomoreno suggestions?

**Comment by joaomoreno** [comment]
Even though I feel @weinand's pain, I don't think we should change the behavior, to keep consistency.

**Comment by Tyriar** [comment]
If we did do that I wouldn't want it to be the default though as it felt good reducing the inline actions to 2 as it makes clicking the actual tab difficult.

**Comment by weinand** [comment]
It's a problem of muscle memory (and age ;-) 
I can deal with this focus behavior in the explorer without problems.
But after using the (old) terminal switcher for two years I'm not in the habit of double clicking or pressing enter when switching between terminals.

I'm still able to learn that, but I expect some users will complain...

**Comment by eamodio** [comment]
Yeah, to me this doesn't feel like a "list" -- it feels like tabs. So similar to editor tabs (where we focus the editor on click), I think we should focus the terminal upon click.

**Comment by Tyriar** [comment]
I think I'm convinced that we should be acting more like clicking on an editor tab here. As a compromise this only affects mouse clicks on actual tabs, the way to get keyboard focus in the tabs view is via the dedicated command or clicking in the empty space.

**Comment by joaomoreno** [comment]
Having played with this today, I am not convinced that this was a good decision, especially after having added multiple selection support. This feels weird, for example:

1. Click on a terminal
2. Press <kbd>Ctrl A</kbd> to select all 🐛

---

If we intend to keep this behavior I suggest to remove all UI/UX which makes the component look like a list (hover, focus and selection styles, multiple selection, keyboard navigation) and just create a UI/UX similar to actual tabs.

**Comment by Tyriar** [comment]
Yeah I get your concern and notice some weird stuff particularly after adding multi-select support, will add `'terminal.integrated.tabs.focusMode': 'singleClick' | 'doubleClick'` as a workaround for now, with double click as the default. I'd rather not add an inline action because it will make it harder to deal with the tabs when they're at their min width:

![image](https://user-images.githubusercontent.com/2193314/116088796-0cad9480-a657-11eb-9fbd-f1155eca51e4.png)

Will see what the community says.

> If we intend to keep this behavior I suggest to remove all UI/UX which makes the component look like a list (hover, focus and selection styles, multiple selection, keyboard navigation) and just create a UI/UX similar to actual tabs.

FWIW I think tabs should also support multi-select and keyboard nav.
