### ISSUE TITLE
cannot open untitled:URI , got URI but expected URI error in ubuntu and mac only

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#12192]
Console LOG shows : \Users\mklement\Library\Application Support\Code\User\summary.txt

as loop is using to replace the slashes

**its working fine in windows but doesnt work in ubuntu and mac, this is the example of OSX 10.11.6**

But when i try to parse URI using API i get the following error

>threadService.ts:217[Extension Host] cannot open untitled:%5CUsers%5Cjdoe%5CLibrary%5CApplication%20Support%5CCode%5CUser%5Csummary.txt. Detail: expected URI untitled:%5CUsers%5Cjdoet%5CLibrary%5CApplication%20Support%5CCode%5CUser%5Csummary.txt BUT GOT untitled:/Users/jdoe/Library/Application%20Support/Code/User/summary.txt(anonymous function) @ threadService.ts:217

Following is the code
```
 while (tempURI.indexOf("/") > -1) {
            tempURI = tempURI.replace("/", "\\");
    }
console.log("FILE URI For Summary Page : " + tempURI);
        
var setting: vscode.Uri = vscode.Uri.parse("untitled:" + tempURI);

vscode.workspace.openTextDocument(setting).then((a: vscode.TextDocument) => { ...
```
In the referenced issues same behavior found even after generating new extension.

I think this might be a bug in API, or i have to do anything more to parse to correct URI ?

**Comment by jrieken** [comment]
You should not use backslashes for the URI because that isn't seen a path separator but it will all be part of the authority. Also, note that there is `Uri.file` and `Uri.with` which help you a lot to construct a valid uri
