### ISSUE TITLE
Formatting causes removal of random texts in PowerShell script

### ISSUE THREAD

**Issue by ztrhgf** [microsoft/vscode#121932]
Issue Type: <b>Bug</b>

If I use in settings.json: "powershell.codeFormatting.whitespaceBetweenParameters": true

It will automatically delete random chunks of text on ps1 script format.

My settings.json and script where you can test is are here https://www.dropbox.com/s/p9w60jjayq4jtty/vsc_formatting_bug.zip?dl=0

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.49GB free)|
|Process Argv|--crash-reporter-id 257616c8-d4a1-4b1d-b637-c60bf4009459|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
autoit|Dam|1.0.5
xml|Dot|2.5.1
gitlens|eam|11.4.1
todo-tree|Gru|0.0.211
reg|ion|1.0.3
rainbow-csv|mec|1.8.1
powershell|ms-|2021.2.2
snippet-creator|rya|0.1.3
code-spell-checker|str|1.10.2
errorlens|use|3.2.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
vscoreces:30290705
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by aeschli** [comment]
Can you file this issue against the extension that contributes the Powershell formatter? From looking at the list of installed extension it looks like it's the Micorosoft Powershell extension: https://github.com/PowerShell/vscode-powershell/issues

**Comment by ztrhgf** [comment]
OK I have create another bug issue in PowerShell extension repository.

**Comment by aeschli** [comment]
Thanks a lot!
