### ISSUE TITLE
Terminal tabs is responsive on mouseup only

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#121962]
It's a very strange behavior that the tabs are responsive only on mouseup. This should be a very simple _if width < 100px, then hide some stuff with CSS_.

![recording (9)](https://user-images.githubusercontent.com/22350/115774094-002ef080-a366-11eb-804e-c3b9753f521c.gif)

**Comment by Tyriar** [comment]
Looks like your build is quite old

**Comment by Tyriar** [comment]
This was done a week or so ago
