### ISSUE TITLE
Terminal tabs don't show after restart with auto-task

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121903]
* have github-issue-notebooks cloned
* the repo uses a task which starts on folder open. make sure that works for you by starting the task manually once
* close the terminal
* close the window
* reopen that window
* wait ❗ for the task to start (check status bar)
* reveal terminal via `cmd+j`
* 🐛 no tabs

https://user-images.githubusercontent.com/1794099/115676516-f601f780-a34f-11eb-9fbc-172a024b2e89.mov

**Comment by meganrogge** [comment]
This is fixed in main and should be live tomorrow
![recording - 2021-04-23T100353 682](https://user-images.githubusercontent.com/29464607/115905799-75103200-a41b-11eb-91b0-0926b49e9688.gif)

**Comment by meganrogge** [comment]
to verify - when you clone the repo, run yarn before trying to run the build task. To manually run it and check that the task works, go to `Run Task -> npm: bundle watch`
