### ISSUE TITLE
breakpoints missed when on lines with await

### ISSUE THREAD

**Issue by guycnicholas** [microsoft/vscode#121968]
Issue Type: <b>Bug</b>

In my nodejs app, if I put a breakpoint on this line.
`const response = await makeCall();`
it will never get hit.  I have to put the BP on the line prior and then step to get to the line in question.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.86GB free)|
|Process Argv|--crash-reporter-id 8a8708a2-857f-4160-b1d7-75d09a14ed9d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
logcat|abh|0.0.7
android-dev-ext|ade|1.3.2
npm-intellisense|chr|1.3.1
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|2.1.20
vscode-npm-script|eg2|0.3.21
flow-for-vscode|flo|1.5.0
gc-excelviewer|Gra|3.0.41
todo-tree|Gru|0.0.211
duk-debug|Har|0.5.6
rest-client|hum|0.24.5
vscode-hexdump|ili|1.8.2
vscode-peacock|joh|3.9.1
mdhelper|jos|0.0.11
sublime-babel-vscode|jos|0.2.10
vscode-position|jtr|1.0.2
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-edge-devtools|ms-|1.1.7
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
remote-containers|ms-|0.166.1
azure-account|ms-|0.9.8
cpptools|ms-|1.3.1
vscode-js-profile-flame|ms-|0.0.16
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.12.12
debugger-for-edge|msj|1.0.15
vscode-code-outline|pat|0.2.1
java|red|0.77.0
json-to-js|ren|0.2.0
code-spell-checker|str|1.10.2
vscodeintellicode|Vis|1.2.12
vscode-java-debug|vsc|0.32.1
vscode-java-dependency|vsc|0.18.3
vscode-java-pack|vsc|0.14.0
vscode-java-test|vsc|0.28.1
vscode-maven|vsc|0.29.0
vscode-icons|vsc|11.4.0
vscode-import-cost|wix|2.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30286882

```

</details>

**Comment by yume-chan** [comment]
Are you using vanilla JS or some transpiler like TypeScript/Babel? Note that transpiled async functions are very messy and debuggers always have a tough time mapping them back to source code.

Also, can you share with us your Node.js version and `launch.json`?

**Comment by connor4312** [comment]
You may be hitting https://bugs.chromium.org/p/chromium/issues/detail?id=1081162&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&q=breakpoint%20await&can=4
