### ISSUE TITLE
Yellow light blub background not transparent

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#121956]
Issue Type: <b>Bug</b>

The yellow light blub background is not transparent

<img width="394" alt="image" src="https://user-images.githubusercontent.com/876920/115755013-b3d9b580-a351-11eb-804f-dd5fd52b3111.png">
 

VS Code version: Code - Insiders 1.56.0-insider (Universal) (7ce1499d9541ba2acf66cd30a9054bd7818a8f80, 2021-04-22T05:12:09.510Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api ms-vscode.vscode-notebook-history --enable-proposed-api vscode.notebook-editing --enable-proposed-api vscode.vscode-test-resolver --enable-proposed-api donjayamanne.kusto --crash-reporter-id 1a907bbd-fa02-4595-81e0-63e1648afb31|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
This was done to make sure the lightbulb has enough contrast, even if it is shown over text: #109043

/cc @misolori
