### ISSUE TITLE
Regarding Device in Bottom Right Corner

### ISSUE THREAD

**Issue by himanshu717171** [microsoft/vscode#121997]
Hello VS Code,
I am Flutter Developer using VS Code. I use to love it and it favorite. But when I updated the VS Code, it always shows "No Device" in bottom right corner. Earlier it was working fine and always shows the attached devices.
Due to this I am unable to debug my project using F5. I have attached the screen and highlighted the issue with red color.
So, please resolve .
![Screenshot (151)](https://user-images.githubusercontent.com/38049620/115836259-e3adb980-a434-11eb-98bf-efc1b2bb0f67.png)

**Comment by himanshu717171** [comment]
> 
> 
> /causedByExtension

Which Extension?

**Comment by gjsjohnmurray** [comment]
AFAIK VS Code doesn't ship with Flutter support. Which one(s) did you add?

**Comment by himanshu717171** [comment]
> 
> 
> AFAIK VS Code doesn't ship with Flutter support. Which one(s) did you add?

I have just added 2 Extentions i.e. Dart and Flutter.

**Comment by gjsjohnmurray** [comment]
So please report your issue to the extension author.

**Comment by himanshu717171** [comment]
Only I am getting this issue. My Colleagues have no issue
