### ISSUE TITLE
Bad error when using less mixins with passed-in rulesets

### ISSUE THREAD

**Issue by jjacode** [Microsoft/vscode#12195]
- VSCode Version: 1.5.2
- OS Version: Windows 10

Steps to Reproduce:
1. Try to follow example from less page: http://lesscss.org/features/#detached-rulesets-feature
2. Notice error highlighting:

![image](https://cloud.githubusercontent.com/assets/15765196/18609756/4875a35e-7cc7-11e6-9086-43b946835eda.png)
![image](https://cloud.githubusercontent.com/assets/15765196/18609769/91ecd6ba-7cc7-11e6-89f8-adb66e74d25a.png)
![image](https://cloud.githubusercontent.com/assets/15765196/18609771/99182ade-7cc7-11e6-865d-9983fc53e6e8.png)

**Comment by aeschli** [comment]
This got fixed in the meantime. Verified in the January build.
