### ISSUE TITLE
Multiline string autoselection

### ISSUE THREAD

**Issue by sandorvasas** [microsoft/vscode#121993]
Just recently, multiline strings get auto-highlighted like they were selected. It annoys me. How can I disable this, what is the feature's name to search for in settings?
[Please see this image](https://ibb.co/5sH7HQd)

**Comment by IllusionMH** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/43292

> Looks like it can be disabled by "editor.occurrencesHighlight": false ATM.

/assign mjbvz
