### ISSUE TITLE
Hover tooltip not showing Intellisense type information for non-named imports (Javascript)

### ISSUE THREAD

**Issue by rosyatrandom** [microsoft/vscode#121924]
Issue Type: <b>Bug</b>

- The hover tooltip for a symbol usually displays intellisense information on the type
- When displayed for a named import (ie, `import { foo } from 'path/to/foo'`), this displays above the line `import foo`
- When displayed for a default export (`import foo from 'path/to/bar'`) , or when importing the whole module (`import * as foo from 'path/to/bar`), there is nothing above the `import foo` line -- no type information at all
- If you use Intellisense for suggestions, though, (ie, type `foo.`), then the type info for its members is there in all cases

This holds true for whether `foo.js` exports using CJS or ES6 modules, and also when importing using CJS.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (3.89GB free)|
|Process Argv|--crash-reporter-id 4f96471e-dbc1-4ee1-8ccf-4f8f6e7aedd5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
vscorecescf:30290706
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by mjbvz** [comment]
I don't understand the description of the problem

Can you please share a small example project that demonstrates the issue. Also be sure to xplain the current behavior and the expected behavior using that project
