### ISSUE TITLE
Enter key has never worked

### ISSUE THREAD

**Issue by ddavis-mayo** [microsoft/vscode#121943]
Issue Type: <b>Bug</b>

I have reinstalled, tried different keybindings, cleared keybindings, but can not get the ENTER key to to do a CRLF.  I've had to resort to using CTRL+ENTER, but I can't split a line that way, just inserts a new one below.  It is making VS Code unusable and I need to use it.   Is there a command I can bind to the ENTER key to get the correct behavior?  Thank you.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.66GB free)|
|Process Argv|--crash-reporter-id 0f8e88a7-962b-4d0f-a657-9f5ae5d4e1f3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|has|2.10.0
powershell|ms-|2021.2.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553
vscgsv2ct:30286882

```

</details>

**Comment by ddavis-mayo** [comment]
[2021-04-22 08:33:24.957] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-04-22 08:33:40.122] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-04-22 08:43:18.005] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-04-22 08:52:41.913] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Enter, keyCode: 13, key: Enter
[2021-04-22 08:52:41.914] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Enter, keyCode: 3 ('Enter')
[2021-04-22 08:52:41.914] [renderer1] [info] [KeybindingService]: | Resolving Enter
[2021-04-22 08:52:41.914] [renderer1] [info] [KeybindingService]: \ From 21 keybinding entries, no when clauses matched the context.
[2021-04-22 08:52:42.671] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: Enter, keyCode: 13, key: Enter
[2021-04-22 08:52:42.671] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: Enter, keyCode: 3 ('Enter')
[2021-04-22 08:52:42.672] [renderer1] [info] [KeybindingService]: | Resolving Enter
[2021-04-22 08:52:42.672] [renderer1] [info] [KeybindingService]: \ From 21 keybinding entries, no when clauses matched the context.

**Comment by alexdima** [comment]
@ddavis-mayo The log looks good. No keybinding is matching `Enter`, so it should result in its default behavior, which is to insert a newline in the focused editor.

1. Are you pressing Enter at a physical keyboard or are you using an on-screen keyboard?
2. Are you sitting at the computer where you are running VS Code or are you using some remoting technology to connect to it?
3. Are you using the English US keyboard layout or another keyboard layout?
4. Does this reproduce in every file type? Even in `.txt` files?
5. What are your user settings?
6. Does this reproduce also in our Insiders version https://code.visualstudio.com/insiders/ ?

**Comment by ddavis-mayo** [comment]
1. Physical.  Tried onscreen just to test, same result
2. Sitting at
3. English US
4. Tested: json, tf, ps1, bat, txt
5. Hopefully this is what you are after
`{
    "terminal.integrated.scrollback": 3000,
    "git.defaultCloneDirectory": "c:/users/m050044/desktop/VSCode",
    "explorer.openEditors.visible": 0,
    "workbench.tree.indent": 20,
    "window.openFoldersInNewWindow": "on"
}`
6. I have not tried insiders, but I have had it chasing me through 3 version updates at this point, most recently updated this morning.  If you think this is worthwhile let me know.  Installing updates or reinstalling is a bit of a process with company policy.

**Comment by alexdima** [comment]
Thank you for your answers. Unfortunately there's nothing that stands out to me yet.

- Could you please try Insiders (https://code.visualstudio.com/insiders/), you can download the portable `.zip` version and unzip it anywhere without needing to install it.
- If you cannot try insiders, could you try with a fresh user data dir (close all instances of vscode and run `code --user-data-dir=C:\some\new\folder`)?

**Comment by ddavis-mayo** [comment]
Tried --user-data-dir to a different folder and did not work.  Will try insiders.

**Comment by ddavis-mayo** [comment]
Same issue in insiders

**Comment by alexdima** [comment]
Thank you for trying. Does pressing Enter work in the editor at https://microsoft.github.io/monaco-editor/ when you open it in Chrome or Edge?

I have to be honest, I don't really know what is going on. From the looks of it, we let the `Enter` keydown event fall through to Chromium and then Chromium is supposed to insert a `\n` in the `<textarea>` we use as an input. We then normally react to that input and detect that a newline was typed. But either Chromium is not inserting a `\n` for you or we don't detect it correctly.

I can offer a workaround to get you unstuck. You can manually make `Enter` insert `\n` if Chromium doesn't do it. But to allow all the other default `"enter"` keybindings, a lot of rules are needed. You can try the following in your `keybindings.json`:
```
[
{ "key": "enter", "command": "type", "args": {"text": "\n"},
                   "when": "textInputFocus && !editorReadonly" },
{ "key": "enter", "command": "breakpointWidget.action.acceptInput",
                   "when": "breakpointWidgetVisible && inBreakpointWidget" },
{ "key": "enter", "command": "repl.action.acceptInput",
                   "when": "inDebugRepl && textInputFocus" },
{ "key": "enter", "command": "settings.action.focusNextSetting",
                   "when": "inSettingsSearch" },
{ "key": "enter", "command": "acceptSelectedSuggestion",
                   "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus" },
]
```

**Comment by ddavis-mayo** [comment]
Works like a charm in Monaco.

Sweet!  I will try this, thank you!

**Comment by ddavis-mayo** [comment]
It's working!!!!  Thank you so much!  Let me know if there's any other info you would like to gather, but if you want to call it good we can close as well.  Thank you again for the help!

**Comment by alexdima** [comment]
I'm really sorry, I can't figure out what is going wrong on your machine... The next steps would be to checkout vscode and debug the input handling logic... I'm happy the workaround works.
