### ISSUE TITLE
Currently Active Notebook Controller

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121902]
### 1. Global even for when a NotebookController changes
Today we need to add an event on each notebook controller to determine whether its the active controller or not.
I could be wrong here, but based on my understanding this is what happens today:
* User opens a notebook a.ipynb
* Extension creates a notebook controller A, this is now the active notebook controller
* Extension creates a notebook controller B, C (this is preferred), D
* C is preferred but not the active controller.

**I prefer the previous implementation over this.**
Basically if the user executes a cell, then it cannot change regarless of ispreferred (as user has made a selection).

Right now there's no clear contract that tells us (extension authors) what the active/selected controller is when a notebook is opened.
Picking the first controller as the active doesn't seem right in the push model.

I'd prefer the following:
**Scenario 1**
* User opens a notebook a.ipynb
* Extension creates a notebook controller A
* No active notebook controllers/kernels.
* User sees a message in status bar `Select kernel`, when user attempts to run a cell, then they get the picker to select a kernel (this is how it worked previously with provider model)

**Scenario 2**
* User opens a notebook a.ipynb
* Extension creates a notebook controller A
* User sees a message in status bar `Select kernel`
* After a few seconds the extension pushes more controllers...
* Extension creates a notebook controller B, C (this is preferred), D
* C is active controller.
* The status bar will respect the `isPreferred` setting.

FYI - Such a model is crucial for us. Else picking the first controller as the active controller could break notebooks (e.g. .NET extension registering a controller before Jupyter extension could result in that getting picked over Python kernel for a Python Notebook or the like).

TLDR - I'd prefer to have an explicit contract that tells VS Code what should be used as the kernel (isPreferred & if not provided, then there's none).
Similarly if such a kernel is selected by VS Code, extension authors need to know about this (previously the event would be fired).
Though the down side was we didn't know whether the event was fired as a result of user changing the kernel or vs code automatically picking one.

_Originally posted by @DonJayamanne in https://github.com/microsoft/vscode/issues/121329#issuecomment-824214229_

**Comment by jrieken** [comment]
I can relate to both scenarios but there are two things to consider

* there are notebooks with a single kernel, like Github Issues or Restbook, and for them this means that they must use `isPreferred` or get a bad user experience (must pick/confirm lone kernel). I don't know if I want/like that
* VS Code remembers that kernel was picked (explicitly) per document and that should win. This is also the reason that we cannot generate ids - ids must be stable across sessions for remembering to work.

**Comment by DonJayamanne** [comment]
> there are notebooks with a single kernel, like Github Issues or Restbook, and for them this means that they must use

Ok, then how about, vscode change the active kernel if extension author provides a kernel with isPreferred set.

Here's my solution:
* When extension created a controller, that's used as active controller
* If user doesn't change this manually not run a cell then anytime extension creates another with isPreferred , then that will be the preferred/active kernel.
* that'll work for github issues and Jupyter.

> This is also the reason that we cannot generate ids - ids must be stable across sessions for remembering to work.

Ok then, vscode can internal prefix these with the extension I'd. Now it's unique globally. As the I'd is already unique per extension (expected, as it's as I'd)

**Comment by DonJayamanne** [comment]
Personally I'd prefer not to have isPreferred and just have a method on vscode when we can tell vscode to use the controller as the active controller.  I believe @rebornix introduced a command for this. We could instead use that (for notebook controller to be set as the active one).

However wed still need an event from vscode to tell us what the active controller is, else were leaving these things to chance (no concrete api).is we assume that the first controller is the default. Or sweet could have the command (the one that peng created) return a boolean indicating whether it was successfully set or not.

**Comment by jrieken** [comment]
Closing as all issues have been addressed now
