### ISSUE TITLE
Quotes and html?

### ISSUE THREAD

**Issue by alsong** [Microsoft/vscode#12198]
- VSCode Version: Code 1.5.1 (07d663dc1bd848161edf4cd4ce30cce410d3d877, 2016-09-08T21:33:49.307Z)
- OS Version: Windows_NT ia32 10.0.10240

Steps to Reproduce:

1.
2.

## Original Title

while typing scripts on the lastest vs code. there is a difficulty i face when i press eneter on an attribute that requires me to input text in between quotes and the cursor appears outside the quotes. Its stressing to bring it back, it would help if the cursor would appear in between the quotes

**Comment by bpasero** [comment]
@alsong can you please provide a shorter title and write the issue in the description field?

**Comment by alexandrudima** [comment]
@alsong this works for me, the cursor is placed between the quotes:

![quotes-html](https://cloud.githubusercontent.com/assets/5047891/18750886/a65e988c-80e5-11e6-89ea-359a98b181d1.gif)

**Comment by alsong** [comment]
The issue was later worked one and another release was published days after
we complained
