### ISSUE TITLE
Cannot execute code in VS code

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [microsoft/vscode#121908]
Issue Type: <b>Bug</b>

When trying to run code, with or without debugging, nothing happens in VS code. If debugging, error of runouttime error appears.

VS Code version: Code - Insiders 1.56.0-insider (7ce1499d9541ba2acf66cd30a9054bd7818a8f80, 2021-04-22T05:13:14.711Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.63GB free)|
|Process Argv|--crash-reporter-id f4ca618f-6553-48c9-abb5-cead36f66d6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
systemd-unit-file|coo|1.0.6
json-tools|eri|1.0.2
vscode-pull-request-github|Git|0.25.1
gc-excelviewer|Gra|3.0.41
jsonnet|hep|0.1.0
jsonnet-language|lia|1.0.0
python|ms-|2021.4.765268190
jupyter|ms-|2021.6.770905982
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
sourcery|sou|0.9.0
jsonnet-formatter|xrc|0.3.0
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletextcf:30288478
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2ct:30286873

```

</details>

**Comment by weinand** [comment]
Please read https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions to learn how to file bugs.
