### ISSUE TITLE
Untitled file service doesn't work with notebook view types

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#121974]
- VS Code Version: Insiders
- OS Version: Windows

Steps to Reproduce:

0. Currently developing the .NET Interactive Notebooks extension (ms-dotnettools.dotnet-interactive-vscode)
1. Our extension registers the notebook view type `dotnet-interactive` for files of type `*.dib`.
2. When we try to create a new untitled notebook, we get an error: `The file working copy resource untitled:Untitled-1.dib does not have an associated file system provider.`

The following all fail in similar ways and all have the following code immediately preceeding this failure:

``` typescript
const viewType = 'dotnet-interactive'; // this was registered in `package.json`
const fileName = 'Untitled-1.dib'; // note, there is no existing editor with this name
const newUri = vscode.Uri.file(fileName).with({ scheme: 'untitled', path: fileName });
```

1. `vscode.commands.executeCommand('vscode.openWith', newUri);`
2. `vscode.commands.executeCommand('vscode.openWith', newUri, viewType);`
3. `vscode.notebook.openNotebookDocument(newUri);`

This one just opens a text document, not a notebook:

- `vscode.commands.executeCommand('workbench.action.files.newUntitledFile', viewType);`

Does this issue occur when all extensions are disabled?: N/A

**Comment by brettfo** [comment]
cc @jrieken @bpasero

**Comment by bpasero** [comment]
File working copies require a scheme that has a registered file system provider. For untitled files, file working copies cannot be used.

**Comment by brettfo** [comment]
This is blocking a scenario for us, namely being able to open an untitled notebook with our viewType/serializer.  Is there any other workaround we can use until the scheduled work you mentioned?  Is there a way that our notebook deserializer can be called with an empty Uint8Array()?  Or maybe we can pass into something a Uint8Array() that our deserializer can parse?

**Comment by brettfo** [comment]
Also, I should point out that the scenario initially mentioned works for `Untitled-1.ipynb`/`jupyter-notebook`, but _doesn't_ work for `Untitled-1.dib`/`dotnet-interactive` and I don't know what the difference is or how we can get past it.

**Comment by jrieken** [comment]
I am reaching the notebook world when using `vscode.commands.executeCommand('workbench.action.files.newUntitledFile', { viewType })` (@brettfo  note that `viewType` in wrapped in an object, not passed as string). However, the notebook world quickly fails when creating a working copy for untitled files. 

@bpasero I need your help/consulting here. For text files we have `IUntitledTextEditorModelManager`. Should I invent something similar for notebooks or is untitled files something you are planning for the working copy world? 

Also /cc @lramos15 who is having a similar challenge when starting from the command line, like `code hello_new.dib`

**Comment by jrieken** [comment]
Independent on how we are going to implement the internals: on the API-level we should have something like `openNotebookDocument({viewType: string, content?: Unit8Array })` which then allows to create a new, untitled notebook for a given view type and with some content

**Comment by bpasero** [comment]
> Should I invent something similar for notebooks or is untitled files something you are planning for the working copy world?

I have https://github.com/microsoft/vscode/issues/118947 to investigate this because search editors have untitled support as well and for adopting file working copy would need similar support as notebooks. I am not sure yet how this will turn out in the end though, either a new type (untitled file working copy?) or as part of the file working copy thing. But I do think that there is chance of reuse here and that not everyone should come up with their own untitled support if possible.

**Comment by jrieken** [comment]
> If you need a fix for April though, then please go ahead with a custom solution.

Given it will be waste I am not so eager to do so ;-) @brettfo Unsure how much you depend on this? My understanding is that this works with the content provider API but not with the new serializer API. Is that correct? Can you stay on the "old" API for some time longer?

**Comment by brettfo** [comment]
> Can you stay on the "old" API for some time longer?

Not really, no, because my understanding is that the content provider API is getting removed in the next stable release in ~1 week and we'll be forced on to the serializer API.

**Comment by jrieken** [comment]
> Not really, no, because my understanding is that the content provider API is getting removed in the next stable release in ~1 week and we'll be forced on to the serializer API.

The old API will stay around but we aren't planning to finalize it any time soon and aren't planning to fix issues for it

**Comment by bpasero** [comment]
I will start to look into this for May and I am optimistic that it can be done for May too.

**Comment by jrieken** [comment]
API proposal for creating untitled notebooks:

```ts
export function openNotebookDocument(viewType: string, data: NotebookData | undefined): Thenable<NotebookDocument>
```

**Comment by bpasero** [comment]
I have pushed workbench API to support untitled file working copies via `FileWorkingCopyManager2` which is the successor of `FileWorkingCopyManager`. It provides methods to `resolve` file working copies and untitled file working copies. It provides access to the underlying "managers" via `.files` and `.untitled` property.

Once this is adopted by notebooks, I will do some renames:
* `FileWorkingCopyManager2` => `FileWorkingCopyManager`
* `FileWorkingCopyManager` => `TitledFileWorkingCopyManager` (?)

If someone has a better idea how to name `TitledFileWorkingCopyManager`, happy for ideas.

**Comment by jrieken** [comment]
Close as done
