### ISSUE TITLE
Keyboard shortcuts for macOS conflict with macOS system default keyboard shortcuts

### ISSUE THREAD

**Issue by Misaka13514** [microsoft/vscode#121920]
- VS Code Version: latest
- OS Version: macOS Big Sur

Steps to Reproduce:

1.
<img width="848" alt="Screenshot 2021-04-22 18 57 09" src="https://user-images.githubusercontent.com/54669781/115696689-e0b3ba00-a39d-11eb-9e2b-454d7735ed49.png">

2.`^Space` switches my input method.

Does this issue occur when all extensions are disabled?: Yes

**Comment by jrieken** [comment]
Out of the box we also support `option+esc` which is more typical macOS shortcut
