### ISSUE TITLE
Copying text from editor should not include formatting

### ISSUE THREAD

**Issue by ironyman** [microsoft/vscode#121977]
- VS Code Version: all
- OS Version: windows all

Steps to Reproduce:

1. copy some text from vscode
2. paste in outlook email editor

Does this issue occur when all extensions are disabled?: Yes/No
yes

![image](https://user-images.githubusercontent.com/502496/115799703-e5707200-a38d-11eb-87c7-a61c83c22cce.png)

**Comment by IllusionMH** [comment]
/question

If you prefer to copy without formatting you can turn it off with `"editor.copyWithSyntaxHighlighting": false`.
