### ISSUE TITLE
Integrated terminal freezes when ever a program goes to infinite loop.

### ISSUE THREAD

**Issue by tripsus** [Microsoft/vscode#12196]
Version 1.5.2
Commit 66f37fd2a99eb9d628dd374d81d78835b410c39b
- OS Version: Ubunutn 15.10

Steps to Reproduce:

1. Write a C program which outputs to integrated terminal in infinite loop. 
2. Run that program in integrated terminal, terminal freezes.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/11805
