### ISSUE TITLE
Cannot set cell language via ui

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode#121927]
Version: 1.56.0-insider (user setup)
Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
Date: 2021-04-22T05:13:14.711Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Clone pr dotnet/interactive#1286
2. Go to folder src/dotnet-interactive-vscode/nsiders adn open with VSCode insiders
3. Launch debugger
4. Open .ipynb notebook
5. Select a cell and try to change cell language using the mouse

The selector will flash on screen, can set the language for the selected cell only using the command palette

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by DonJayamanne** [comment]
Yup, I too can see this.
