### ISSUE TITLE
VS Code not responding (V>=1.54)

### ISSUE THREAD

**Issue by msabathi** [microsoft/vscode#121951]
Since version 1.54, VS Code does not respond after launching.

The welcome page comes up to the screen but no buttons are clickable or highlighted when the cursor moves over it. The only thing i can do is close the window and have the warning : "VS Code does not respond"

Please find attached the output from running "code --verbose" : [log.txt](https://github.com/microsoft/vscode/files/6359383/log.txt)

VS Code version : 1.54
No extensions installed

System Info :
OS : CentOS Linux 7 (64-bit)
Proc : Intel Xeon CPU E5-1603 0 @ 2.80GHz × 4
Graphics : Quadro 600/PCIe/SSE2
RAM : 8Go
GNOME Version 3.22.2

**Comment by JacksonKearl** [comment]
@deepak1556 I'm seeing 
```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /d/msabathi/TÃ©lÃ©chargements/VSCode-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
```
a lot in the log file

**Comment by deepak1556** [comment]
/duplicate https://github.com/microsoft/vscode/issues/115784

Please install gcc-5 or higher as a workaround.
