### ISSUE TITLE
terminal messy code

### ISSUE THREAD

**Issue by Yuliang-Lee** [microsoft/vscode#121949]
Issue Type: <b>Bug</b>

terminal stdin chinese show messy code

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:39:47.234Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.87GB free)|
|Process Argv|--crash-reporter-id 783fd764-f22f-4642-b3b6-86c092895c12|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
eggjs|ati|0.3.1
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
bracket-pair-colorizer-2|Coe|0.2.0
dart-code|Dar|3.21.1
flutter|Dar|3.21.0
vscode-eslint|dba|2.1.20
githistory|don|0.6.16
gitlens|eam|11.4.1
vscode-npm-script|eg2|0.3.21
vscode-element-helper|Ele|0.5.6
vscode-great-icons|emm|2.1.73
auto-close-tag|for|0.5.10
code-runner|for|0.11.3
extension-leaderboard|for|0.0.2
todo-tree|Gru|0.0.211
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
search-node-modules|jas|1.3.0
vscode-filesize|mkx|3.1.0
vscode-docker|ms-|1.12.1
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
prisma|Pri|2.21.2
psi-header|psi|1.15.1
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.12
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
JavaScriptSnippets|xab|1.8.0
vscode-proto3|zxh|0.5.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" integrated-terminal

**Comment by Yuliang-Lee** [comment]
I'm follow the wiki https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging but log file is empty

**Comment by Yuliang-Lee** [comment]
also try to change `terminal>integrated: Renderer Type` to `dom` or `canvas` but nothing changed

**Comment by Yuliang-Lee** [comment]
I'm use external terminal 'iTerm2'

**Comment by meganrogge** [comment]
You're using iTerm2?

**Comment by meganrogge** [comment]
try turning off `gpuAcceleration`

**Comment by Yuliang-Lee** [comment]
> try turning off `gpuAcceleration`

how to do this?

**Comment by Yuliang-Lee** [comment]
![QQ20210428-204334-HD](https://user-images.githubusercontent.com/6936358/116405745-8cf41580-a862-11eb-8500-bcf4d93d21ed.gif)

**Comment by meganrogge** [comment]
can you run extension bisect? Ctrl shift p to find it

**Comment by Yuliang-Lee** [comment]
![image](https://user-images.githubusercontent.com/6936358/116768745-90a6b880-aa6b-11eb-96b8-cfeb7a28eb16.png)

**Comment by Yuliang-Lee** [comment]
seems no help

**Comment by meganrogge** [comment]
Can you reproduce this issue in VS code insider's?

**Comment by Tyriar** [comment]
I think this is likely related to your `$LANG` environment variable, can you compare what it is in VS Code vs in iterm 2 (where it works?). This setting may help:

```
"terminal.integrated.detectLocale": "off"
```

**Comment by Yuliang-Lee** [comment]
this bug only occur in apple M1 laptop

**Comment by Yuliang-Lee** [comment]
problem solved when I unset the `LC_ALL` environment variable
