### ISSUE TITLE
mouse cursor get shifted when enabling wayland support

### ISSUE THREAD

**Issue by 500InternalError** [microsoft/vscode#121936]
- VS Code Version:code-insider 1.56.0
- OS Version:Arch Linux with latest updates

Steps to Reproduce:

1.Enable fractional scaling in Gnome(not sure if it works when fractional scaling is disabled)
2.Launch code-insiders with commandline:
`code-insiders --enable-features=UseOzonePlatform --ozone-platform=wayland`
3.Maximize the window

In my case my cursor could only go this far rightwards
![2021-04-22 20-59-44屏幕截图](https://user-images.githubusercontent.com/39024699/115719404-a272c680-a3ae-11eb-80d8-2316847a1999.png)

and when I opened the second tab the rightest position my cursor could go is here

![20210422_210117](https://user-images.githubusercontent.com/39024699/115719896-1d3be180-a3af-11eb-82f3-be0c6af56991.jpg)

For reference, the normal behavior on my system is

![2021-04-22 21-12-42屏幕截图](https://user-images.githubusercontent.com/39024699/115720385-9a675680-a3af-11eb-8f83-0a0670536135.png)

What's interesting is that switching to another window restores it to the first status(though still abnormal)

Does this issue occur when all extensions are disabled?: Yes

**Comment by 500InternalError** [comment]
Btw sometimes the UI elements(like the scrollbar and some button) are located lefter than they are displayed(meaning that I must move my cursor to a button's left side to interact with it)

**Comment by MalcolmMielle** [comment]
Smae problem here

**Comment by grigorig** [comment]
This sometimes happens even without fraction scaling for me.

**Comment by eternal-sorrow** [comment]
I have somewhat similar issue (I don't know if it's the same or not). Sometimes (not always) when I click to position the text cursor or to select some text, the real click happens in some offset from the mouse cursor, so I miss the place where I wanted to position the text cursor. This offset may have both vertical and horizontal components, so the text cursor may be placed one line higher and one character to the left from where the mouse cursor was positioned at the moment of click.

I use Fedora 34 and start vscode with ozone wayland.

**Comment by eternal-sorrow** [comment]
Here's the video illustrating the issue:

https://user-images.githubusercontent.com/4847726/123281134-f312b700-d4f8-11eb-9123-71b23a2a3f00.mp4

**Comment by stevennoyce** [comment]
I am seeing a similar issue on Windows 10, where the mouse interaction location gets offset from the actual mouse location. This behavior is accompanied by a black bar on the left hand side of the window. For me, this happens when I leave a window with an open folder focused for a while (hours). Here is a screenshot (the mouse was held over "Go", but you can see that the menu item "Terminal" is going to be selected if the mouse is clicked):

![image](https://user-images.githubusercontent.com/6486871/124484028-fc154b00-dd78-11eb-92a3-696e377dc0a9.png)

I have not enabled wayland. I am on version 1.57.1. Is what I am seeing a different issue, or could these be related?

**Comment by MalcolmMielle** [comment]
AFAIK, wayland is a linux only protocol. Are you running VSCode through WSL?

**Comment by stevennoyce** [comment]
No.  I use WSL, but VSCode is not running through WSL.  I suppose my issue must be different, then. In that case, it's strange that these two separate issues both lead to a mouse offset.

**Comment by grigorig** [comment]
I suppose this is an Electron issue? I couldn't find anything in the Electron issue tracker though. Anyone got any idea what's going on? Does Chrome/Chromium 89 (which Electron 12 is based on) have similar issues under Wayland?

**Comment by PfannenHans** [comment]
I also experience the big scaled cursor using Wayland and KDE Plasma 5.22.5. Additional drop down menus are only partially displayed.  
Interestingly the cursor reverts to its normal size when clicking these menus (but still not using the system cursor)
![Screenshot_20210902_142412](https://user-images.githubusercontent.com/28675788/131843346-35a89648-3c5f-4aa0-801d-5f0d2e9a78bf.png)

**Comment by RichardBaker3020** [comment]
Same problem confirmed on ubuntu 20 wayland,
