### ISSUE TITLE
Destructive sorting in _doApplyEdits

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#121994]
* have a execution that uses the clear/append sequence as shown below
* :bug: you have no output

The problem is that the sorting `_doApplyEdits` breaks the order. Instead doing a clearOutput and then appendOutput is does appendOutput and then clear. See the capture from the debugging: `rawEdits` is correct, but `edits` if wrong

<img width="618" alt="Screenshot 2021-04-23 at 08 57 10" src="https://user-images.githubusercontent.com/1794099/115831606-1eeac100-a412-11eb-9433-0074c2a6b85d.png">

```ts
        for (let cell of cells) {

            // shuffle text
            const rndOut = shuffle(cell.document.getText())
            const exec = controller.createNotebookCellExecutionTask(cell)

            exec.executionOrder = _execCount++
            exec.start();
            exec.clearOutput();

            exec.appendOutput(new vscode.NotebookCellOutput([
                new vscode.NotebookCellOutputItem('text/plain', rndOut),
                new vscode.NotebookCellOutputItem('application/foo', rndOut),
            ]));

            exec.end({ success: true });
        }
```

**Comment by jrieken** [comment]
I have pushed a [skipped test](https://github.com/microsoft/vscode/blob/a668bed63aefe7642201b9d4d472a3202448e1b6/src/vs/workbench/contrib/notebook/test/notebookTextModel.test.ts#L565-L598) that shows this. I am unsure to best fix this. I see how edits are reverse because that makes sense for cell adding/removing but for outputs this is rather bad.

**Comment by rebornix** [comment]
It was fixed now. To test you can write a controller for an existing notebook you have


```ts
	let _executionCount = 0;
	const controller = vscode.notebooks.createNotebookController(
		'test-kernel',
		'mimetype-test', // notebookType
		'Kernel TPI',
		(cells: vscode.NotebookCell[], document: vscode.NotebookDocument, controller: vscode.NotebookController) => {
			for (let cell of cells) {
				// shuffle text
				// const rndOut = shuffle(cell.document.getText())
				const exec = controller.createNotebookCellExecution(cell);
	
				exec.executionOrder = _executionCount++
				exec.start();
				exec.clearOutput();
				exec.appendOutput(new vscode.NotebookCellOutput([
					vscode.NotebookCellOutputItem.text('123')
				]));
	

				exec.end(true);
			}
		}
	);
```

**Comment by rzhao271** [comment]
Adding verified label, since Joh's skipped test was re-enabled two months ago.
