### ISSUE TITLE
Can't run shell scripts from devcontainer after latest insiders build

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/vscode#121969]
Issue Type: <b>Bug</b>

Now on every npm script that tries to run from w/in my dev container I'm met with

```
The terminal process failed to launch: Path to shell executable "C:\Program Files\PowerShell\7\pwsh.exe" does not exist.
```

It shouldn't be trying to use the host OS shell when I'm in a dev container. my settings has

```
    "terminal.integrated.shell.windows": "C:\\Program Files\\PowerShell\\7\\pwsh.exe",
```

in it which is where (I think?) this path is coming from. But `windows` is right there and my DC is, of course, based on Linux.

VS Code version: Code - Insiders 1.56.0-insider (8aff878db2542eea2dfb571c8bb485118bbb3113, 2021-04-19T05:24:23.901Z)
OS version: Windows_NT ia32 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.68GB free)|
|Process Argv|--crash-reporter-id 6de18187-3f83-4640-bee5-6844a434a1d7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Terraform & Node Az Functions|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|2.92GB (1.54GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.2
vscode-peacock|joh|3.9.1
remote-containers|ms-|0.171.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
vs-keybindings|ms-|0.2.1
terraform-advanced-syntax-highlighting|pjm|1.4.0
vscode-icons|vsc|11.4.0
vscode-markdownlint|Dav|0.40.3
vscode-eslint|dba|2.1.20
terraform|has|2.10.0
git-graph|mhu|1.30.0
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
azure-account|ms-|0.9.8
vscode-yaml|red|0.18.0
code-spell-checker|str|1.10.2
azure-event-hub-explorer|Sum|0.1.1
vscode-icons|vsc|11.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
vsc_aacf:30263846
vspre833cf:30267465
pythonptprofiler:30281269
vsdfh931cf:30280410
vscnewfiletext:30288477
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by jasonwilliams** [comment]
Im having the same issue, im in WSL but its failing i think its using windows terminal.

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/123159, https://github.com/microsoft/vscode/issues/123159
