### ISSUE TITLE
NotebookController asWebviewUri does not work for notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#121981]
Run a remote-ssh notebook that does something like this:

```ts
let remoteUri = controller.asWebviewUri(vscode.Uri.file('/datadrive/vscode-notebook-testbed/img.png'));
task.appendOutput(new vscode.NotebookCellOutput([ new vscode.NotebookCellOutputItem('text/html', `<html><img src=${remoteUri!.toString()} /></html>`) ]));
```

I get a uri `https://0.vscode-webview-test.com/vscode-resource/file///datadrive/vscode-notebook-testbed/img.png`, and it 404s

cc @mjbvz @rebornix @jrieken @DonJayamanne

**Comment by roblourens** [comment]
Problem 1 - `asWebviewUri` needs the webview ID here: https://github.com/microsoft/vscode/blob/f68a7e777881f41817dcb2cf63627e5de75138a7/src/vs/workbench/api/common/extHostNotebookKernels.ts#L173

Which makes me wonder whether NotebookController is the right place for this function now, since it's not tied to one editor. Or it needs to take a NotebookDocument from the extension too.

If I fix that, it fails here because extensionLocation is undefined: https://github.com/microsoft/vscode/blob/595c14a8d30f0056a24b95977e51ba6f742e9b96/src/vs/workbench/contrib/webview/browser/resourceLoading.ts#L133-L133

**Comment by jrieken** [comment]
> Which makes me wonder whether NotebookController is the right place for this function now, since it's not tied to one editor. Or it needs to take a NotebookDocument from the extension too.

Does the ID have a meaning? Is that matches against some implicit webview id that notebook editors assign? I only reviewed how the internal `asWebviewUri` function looks and then went with the simple approach - using the controller handle instead of the cumbersome editor id. I might have missed the crucial part here... Tho, the selected controller is likely playing into this as well, e.g when I have two controllers with each having preloads then I should likely reload the webview when switching controllers

**Comment by mjbvz** [comment]
@jrieken Yes the id in `asWebviewUri` must be the same id [that the webview itself uses](https://github.com/microsoft/vscode/blob/48387dfc3d691558404cff1ea2582e3862a40080/src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts#L105)

For webview panels, we create the webview id on the extension host side and then send this over to the main process before creating the webview. The confusing part is that the id we create on the extension host side is also used as the handle

For notebooks, I'm not sure if this same model will work or not since a notebookController can talk about multiple different notebook instances, correct?

**Comment by roblourens** [comment]
Talked to Matt offline, here's a summary

- Problem 1, the webview URI needs the webview ID
  - This ID is put into the URI domain, and the per-webview service worker checks it when deciding to handle a request - https://github.com/microsoft/vscode/blob/48387dfc3d691558404cff1ea2582e3862a40080/src/vs/workbench/contrib/webview/browser/pre/service-worker.js#L174
  - This is a problem when you would have the same notebook content in two split editors. Might just hack around it for notebooks for now but eventually we need to understand whether there are bad implications in security, caching, something else in not using this ID
- Problem 2
  - I will add an option for the notebook to set that tells the webview to assume the resource will be remote in a remote window
  - A real fix will involve having this information, like the real remote URI in the uri returned from `asWebviewUri`. Which is not how we normally do things but this is not content that the uri transformer can find

**Comment by roblourens** [comment]
Hey @mjbvz if you get a chance you could look at d5210de428a4ed692c52cc598573833ec8c60040. I went with adding a flag for the notebook service worker to ignore the first part of the domain for requests it's intercepting. I think this is ok. Will merge before Monday's build.

**Comment by DonJayamanne** [comment]
> ere should be nothing you have to do for this to work.

Great, I'm also mostly done with adding support for Widgets with the new notebook controller changes.
Thanks guys.

**Comment by roblourens** [comment]
@DonJayamanne if you want to test it, there's a windows build here, you could test with local or desktop remote at least, https://az764295.vo.msecnd.net/insider/d5210de428a4ed692c52cc598573833ec8c60040/VSCode-win32-x64-1.56.0-insider.zip lmk if you need a different platform

**Comment by DonJayamanne** [comment]
I'll need a mac build, thanks

**Comment by roblourens** [comment]
https://az764295.vo.msecnd.net/insider/d5210de428a4ed692c52cc598573833ec8c60040/VSCode-darwin.zip

**Comment by rebornix** [comment]
@DonJayamanne https://az764295.vo.msecnd.net/insider/d5210de428a4ed692c52cc598573833ec8c60040/VSCode-darwin.zip

**Comment by DonJayamanne** [comment]
Brilliant, works now, Please feel free to close this issue.

**Comment by roblourens** [comment]
Will keep it for the real fixes

**Comment by DonJayamanne** [comment]
Thanks, I've published the insider version of the Juypter exension to marketplace as well.

**Comment by DonJayamanne** [comment]
Will test on codespaces on monday.

**Comment by jrieken** [comment]
related unload discussion: https://github.com/microsoft/vscode/issues/120747

**Comment by ArtNow198** [comment]
> Run a remote-ssh notebook that does something like this:
> 
> ```ts
> let remoteUri = controller.asWebviewUri(vscode.Uri.file('/datadrive/vscode-notebook-testbed/img.png'));
> task.appendOutput(new vscode.NotebookCellOutput([ new vscode.NotebookCellOutputItem('text/html', `<html><img src=${remoteUri!.toString()} /></html>`) ]));
> ```
> 
> I get a URI `https://0.vscode-webview-test.com/vscode-resource/file///datadrive/vscode-notebook-testbed/img.png`, and it 404s
> 
> cc @mjbvz @rebornix @jrieken @DonJayamanne

**Comment by DonJayamanne** [comment]
Tested in codespaces & doesn't seem to work, getting errors, see here:
![Screen Shot 2021-04-26 at 09 13 26](https://user-images.githubusercontent.com/1948812/116116163-b3059400-a66f-11eb-9879-83abdfbf4192.png)

**Comment by roblourens** [comment]
Opened https://github.com/microsoft/vscode/issues/122221 (nice issue number) to continue
