### ISSUE TITLE
1.55.1 or 1.55.2 broke my extension sytnax highlighting (vscode-nushell-lang)

### ISSUE THREAD

**Issue by fdncred** [microsoft/vscode#121972]
Issue Type: <b>Bug</b>

1. Download my extension https://marketplace.visualstudio.com/items?itemName=TheNuProjectContributors.vscode-nushell-lang
2. Clone this small repo of nushell scripts https://github.com/nushell/nu_scripts
3. Load any nushell script with the .nu extension and notice that the syntax highlighting is not working because all text, except comments, are the same color.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.42GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/dschroeder/source/repos/forks/nu_scripts --crash-reporter-id ddcb1dc7-fe4e-4215-8298-fab582f96ff5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-color-pick|ada|0.6.2
codeswing|cod|0.0.16
excel-to-markdown-table|csh|1.2.2
vscode-eslint|dba|2.1.20
gitlens|eam|11.4.1
prettier-vscode|esb|6.3.2
shell-format|fox|7.1.0
rust-analyzer|mat|0.2.565
csharp|ms-|1.23.11
color-highlight|nau|2.3.0
even-better-toml|tam|0.12.1
vscode-nushell-lang|The|0.2.1
vscode-lldb|vad|1.6.2
vscode-icons|vsc|11.4.0
gistfs|vsl|0.2.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by yume-chan** [comment]
I tried with version 0.2.0 and it worked

![image](https://user-images.githubusercontent.com/1330321/115852007-2b930780-a45a-11eb-8cb8-7a9df694ba34.png)

version 0.2.1 doesn't work.

A quick git diff reveals that there is an extra `|` character that broken your grammar file:

![image](https://user-images.githubusercontent.com/1330321/115852170-5da46980-a45a-11eb-8500-70d137351b32.png)
(the first one, before `into`)

Removing it did recover your extension:

![image](https://user-images.githubusercontent.com/1330321/115852387-9b08f700-a45a-11eb-82fe-cef31b5673e7.png)

**Comment by fdncred** [comment]
@yume-chan wow! you're right! Thanks so much! I feel like such a fool now. That fixed it. I'm sorry I blamed vscode. :(
