### ISSUE TITLE
Settings search fails to find "C_Cpp.files.exclude" using "files.exclude" but works with "files.exclud"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#121964]
- VS Code Version: 1.55.2 and today's Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Install the C/C++ extension (version 1.3.0 or later).
2. Search for `files.exclud` in the Settings search and notice that C_Cpp.files.exclude is shown.
3. Search for `files.exclude`

Bug: C_Cpp.files.exclude is no longer found, but files.exclude is still found.

See the screenshot:

![image](https://user-images.githubusercontent.com/19859882/115776279-cc08ff00-a368-11eb-912a-38c6fc578972.png)

Does this issue occur when all extensions are disabled?: Yes (I have the C/C++ extension enabled)

**Comment by sean-mcmanus** [comment]
This is not a duplicate of https://www.github.com/microsoft/vscode/issues/1214 (which is completely unrelated).

**Comment by roblourens** [comment]
Yes, if there is an _exact_ setting match we don't show other matches. Is that a problem?

**Comment by sean-mcmanus** [comment]
Yes, it's a problem for our C_Cpp.files.exclude setting because we want it to appear when users search for files.exclude (our extension treats C_Cpp.files.exclude the same as files.exclude without it being excluded from VS Code itself).

**Comment by roblourens** [comment]
Honestly I don't know how often users type in a full exact setting key vs browsing or typing something like `files exclude`.
