### ISSUE TITLE
Cant type in the terminal after the change in the UI

### ISSUE THREAD

**Issue by ddieppa** [microsoft/vscode#121946]
Issue Type: <b>Bug</b>

This started happening after the update in the UI of the terminal where vscode introduce a panel where you can select what terminal you wanna create. After that update I cant type anything in the terminal, the keyboard works all over the places in vscode except in the terminal. 

VS Code version: Code - Insiders 1.56.0-insider (7ce1499d9541ba2acf66cd30a9054bd7818a8f80, 2021-04-22T05:13:14.711Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.88GB (1.49GB free)|
|Process Argv|--crash-reporter-id 8cb0cc68-59df-4322-bae4-0a9b22cf54e4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (107)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
vscode-profile-switcher|aar|0.3.3
Bookmarks|ale|13.0.4
copy-relative-path|ale|0.0.2
vscode-browser-preview|auc|0.7.1
tailwind-docs|aus|1.4.0
armview|ben|0.4.5
emojisense|bie|0.8.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-yaml-preamble|bie|0.0.4
vscode-tailwindcss|bra|0.5.10
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.1.20
vscode-faker|dee|1.5.0
docs-scaffolding|doc|0.0.7
githistory|don|0.6.16
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
prettier-vscode|esb|6.3.2
vscode-firefox-debug|fir|2.9.4
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
vscode-pull-request-github|Git|0.25.1
vscode-nginx-conf-hint|han|0.1.0
headwind|hey|1.7.0
vue-snippets|hol|1.0.4
rest-client|hum|0.24.5
output-colorizer|IBM|0.1.2
search-node-modules|jas|1.3.0
vscode-peacock|joh|3.9.1
vscode-random|jre|1.9.0
vscode-colorize|kam|0.11.0
chat|kar|0.35.0
graphql-for-vscode|kum|1.15.3
node-module-intellisense|lei|1.5.0
vsls-whiteboard|los|0.0.12
code-fragments|mar|1.2.0
markdown-shortcuts|mdi|0.12.0
vscode-language-babel|mgm|0.0.31
dotenv|mik|1.0.1
azure-pipelines|ms-|1.183.0
vscode-azureappservice|ms-|0.21.2
vscode-azurefunctions|ms-|1.3.0
vscode-azureresourcegroups|ms-|0.3.0
vscode-azurestorage|ms-|0.12.0
vscode-azurevirtualmachines|ms-|0.3.0
vscode-cosmosdb|ms-|0.16.0
vscode-docker|ms-|1.12.1
csharp|ms-|1.23.11
vscode-dotnet-runtime|ms-|1.0.0
mssql|ms-|1.10.1
remote-containers|ms-|0.170.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.0
vscode-remote-extensionpack|ms-|0.20.0
azure-account|ms-|0.9.8
azurecli|ms-|0.5.0
powershell-preview|ms-|2021.4.1
vscode-node-azure-pack|ms-|0.1.0
vscode-typescript-next|ms-|4.3.20210420
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
azurerm-vscode-tools|msa|0.15.1
debugger-for-chrome|msj|4.12.12
color-highlight|nau|2.3.0
vscode-gatsby-snippets|nic|1.1.2
vetur|oct|0.33.1
material-icon-theme|PKi|4.6.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.1.3
quicktype|qui|12.0.46
vscode-yaml|red|0.18.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.6.1
vue-vscode-snippets|sdr|2.2.0
code-settings-sync|Sha|3.4.3
vscode-fileutils|sle|3.4.5
vscode-autohotkey|sle|0.2.2
sass-indented|syl|1.8.16
vscode-status-bar-format-toggle|tom|2.0.0
lorem-ipsum|Tyr|1.2.0
shell-launcher|Tyr|0.4.1
terminal-tabs|Tyr|0.2.0
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
vscode-icons|vsc|11.4.0
gistfs|vsl|0.2.8
gitdoc|vsl|0.0.8
spaces|vsl|0.1.2
footsteps|Wat|0.1.0
vscode-import-cost|wix|2.15.0
vscode-jumpy|wma|0.3.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.10.13
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes516:30244333
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by meganrogge** [comment]
If you think the cause is the terminal tabs, try turning them off w the `terminal.integrated.showTabs` setting

**Comment by ddieppa** [comment]
@meganrogge that didn't work. same behavior
this is what I have right now as terminal settings:
```json
"terminal.integrated.showTabs": false,
  "terminal.integrated.fontFamily": "MesloLGM Nerd Font, Cascadia Mono PL",
  "terminal.integrated.shell.windows": "C:/Program Files/PowerShell/7/pwsh.exe",
  "terminal.integrated.shellArgs.windows": [
    "-NoLogo"
  ],
```
And does not work not only for powershell (like in my config), it is not working for any terminal. the terminal opens up, the I start typing and nothing happens, it is like the keyboard is disconnected

**Comment by meganrogge** [comment]
Thanks for that info. We're tracking this issue and its various manifestations here #121685
