### ISSUE TITLE
Alt-key does not toggle menu bar

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode#121913]
- VS Code Version:1.5.222
- OS Version:Windows 21359.1 (German Swiss)

Steps to Reproduce:

1.Install Visual Code
2.Hide menu bar and activity bar under View
3.Press Alt key
Nothing happens

Reproduced on two workstations with similar setup. One a newly created VM.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kingma-sbw** [comment]
@vscode-triage-bot although related this seems to be a different problem.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/85124

**Comment by kingma-sbw** [comment]
If corrected the documentation according current behaviour.
