### ISSUE TITLE
Regression: editor text is blurry on Linux with 125% text scaling

### ISSUE THREAD

**Issue by soren121** [Microsoft/vscode#122]
Using Arch Linux with Gnome/Gtk+ 3.18.

In versions 0.9.2 and below, VS Code ignored the text scaling factor in Gnome 3 and rendered its UI text at 100% scale instead of 125% as I had set. (The text scaling factor can be set with gnome-tweak-tool.) To compensate, I set the editor text size to 17, which worked fine.

As of 0.10.1, VS Code now seems to respect the text scaling factor. However, the editor text is noticeably blurry. Changing the editor text size or font does not help. The UI text, on the other hand, seems to be rendered correctly.

I've uploaded comparisons here: http://imgur.com/a/nPLUP
I recommend you view them at 1:1 scale to see the differences clearly.

**Comment by bpasero** [comment]
This is a known issue with the Electron update we did. We plan to fix this in the next update when Electron has advanced.

**Comment by soren121** [comment]
Great! Thanks for the response, I'm looking forward to the next update.

**Comment by zhengbli** [comment]
I have this as well. With windows 10 at 125%, fonts start off looking clear, then become blurry after several scrolling.

**Comment by Matthias247** [comment]
That's interesting. After installing the new version on **Windows** with a 4k 28" screen set to 175% scaling, I had the impression that the text rendering got **better** than with the 0.9.1 release (which was still slightly more blurry than rendering in native apps like normal Visual Studio or Sublime).

**Comment by stkb** [comment]
To those experiencing font blurriness, this is an issue I have with all chromium-based apps on Windows 8.1 (and will likely never be fixed). A workaround is to add the ```--force-device-scale-factor=1``` argument when launching vscode. The whole editor will then be very small, so you'll need to adjust the ```"editor.fontSize"``` user setting (I have it on 18) to make your code more readable.

I haven't found a way to adjust the size of UI-elements as well; vscode doesn't seem to have custom app theming or css like Atom, but for me the interface is still readable, though for a very high-dpi screen it might not be.

**Comment by soren121** [comment]
For reference, this bug tracks atom/electron#3349.

**Comment by bpasero** [comment]
To be clear: The bug I mentioned seems Linux only. If you see blurryness on Mac or Windows, it must be something else and likely unrelated to the Electron update we did. It would help if those people could try with our previous version 0.9.x to see if it makes any difference.

**Comment by soren121** [comment]
@bpasero There are reports on that Electron bug that Windows users are having a similar problem, although the devs are not sure why since the Chromium fix for this was Linux-only. I would not be so quick to blame your team ;)

-----Original Message-----

**Comment by bpasero** [comment]
Is anyone seeing this on windows too then for VS Code?

**Comment by kanreisa** [comment]
I have similar problem on Windows.
fonts are blurry.

![](https://yabumi.cc/15133ece61d27a8b120bd7f1.png)

**Comment by soren121** [comment]
Electron 0.34.4 and 0.35.1 are out, and both include the fix for Linux.
I rebuilt VS Code with 0.34.4 on Arch Linux and the text rendering is crystal clear again.

**Comment by bpasero** [comment]
We will update to Electron 0.34.5 which includes a fix for this.

**Comment by matevzg** [comment]
There is a workaround for high DPI blurriness in 0.10.3. Do a max zoom-in (ctrl+=) and max zoom out (ctrl+-).

**Comment by pdefreitas** [comment]
I have the very same problem on Windows 10 with 125%.

**Comment by Ciantic** [comment]
With Windows 10, Google Chrome can dynamically change the DPI when dragging it to desktop with different scaling factor. 

VSCode (stable branch) goes all blurry however.

**Comment by omani** [comment]
I had the same issue. solved it with the option "--disable-gpu" when launching `code`.
