### ISSUE TITLE
Using `code .` at terminal no longer opens folder in VS Code

### ISSUE THREAD

**Issue by kbmmdwork** [microsoft/vscode#122060]
Issue Type: <b>Bug</b>

1. cd into folder you want to open with VS Code editor
2. use `code .` at terminal
3. it opens some other old project folder instead of the folder you're in

If you instead use `code /some-path-to-folder` instead of just `.` that works but it is a pain.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 3|
|Memory (System)|32.00GB (7.85GB free)|
|Process Argv|. --crash-reporter-id 703d7cad-7bd8-4f97-b4a4-a24df477f4a9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
toggle-hidden|adr|1.0.2
Bookmarks|ale|13.0.4
touch-bar-display|bla|1.5.0
npm-intellisense|chr|1.3.1
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.1.20
vscode-deno|den|3.3.0
gitlens|eam|11.4.1
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|6.3.2
terraform|has|2.10.0
vscode-sort|hen|0.2.5
path-autocomplete|ion|1.17.1
plantuml|jeb|2.14.5
awesometypescriptproblemmatcher|Jua|0.3.0
vscode-cfn-lint|kdd|0.18.1
xml-format|mik|1.1.2
mongodb-vscode|mon|0.5.0
vscode-docker|ms-|1.12.1
remote-containers|ms-|0.166.1
vscode-typescript-tslint-plugin|ms-|1.3.3
vsliveshare|ms-|1.0.4131
debugger-for-chrome|msj|4.12.12
vetur|oct|0.33.1
vscode-jest|Ort|3.2.0
vscode-versionlens|pfl|1.0.9
text-power-tools|qcz|1.26.0
quicktype|qui|12.0.46
vscode-yaml|red|0.18.0
vscode-coverage-gutters|rya|2.7.2
jenkinsfile-support|sec|0.1.0
rewrap|stk|1.14.0
vscode-tidymarkdown|teh|0.0.5
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
vscode-import-cost|wix|2.15.0
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by kbmmdwork** [comment]
> (Experimental duplicate detection)
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Open Containing Folder opens in browser instead of file explorer in SNAP version of vscode (#115726)](https://www.github.com/microsoft/vscode/issues/115726)

Not the same issue at all ^^^ bad bot

**Comment by yume-chan** [comment]
Same as #126702, can you try with the latest insider version?
