### ISSUE TITLE
Failed at the oniguruma@6.1.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by nbapat43** [Microsoft/vscode#12202]
*Not sure if the title is correct
"name": "code-oss-dev",
- VSCode Version: 1.6.0
- OS Version: windows 10

Steps to Reproduce:
Trying to set up vscode for debugging to help with contributing.  [Followed instructions on VSCode how to Contribute](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source).
[Here is my enviroment variables](http://imgur.com/65bfhOT)

1. after completing the dependencies. 
2. I try to run the npm install line. The output below is from the message npm-debug.txt that showed with the [cmd install response](http://imgur.com/3HGA43N)

Output:
97304 verbose lifecycle oniguruma@6.1.0~install: CWD: c:\Users\User\vscode\node_modules\oniguruma
97305 silly lifecycle oniguruma@6.1.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
97306 silly lifecycle oniguruma@6.1.0~install: Returned: code: 1  signal: null
97307 info lifecycle oniguruma@6.1.0~install: Failed to exec install script
97308 verbose unlock done using C:\Users\User\AppData\Roaming\npm-cache\_locks\staging-5151d6a31ce70708.lock for c:\Users\User\vscode\node_modules\.staging
97309 silly rollbackFailedOptional Starting
97310 silly rollbackFailedOptional Finishing
97311 silly runTopLevelLifecycles Starting
97312 silly runTopLevelLifecycles Finishing
97313 silly install printInstalled
97314 warn optional Skipping failed optional dependency /chokidar/fsevents:
97315 warn notsup Not compatible with your operating system or architecture: fsevents@0.3.8
97316 verbose stack Error: oniguruma@6.1.0 install: `node-gyp rebuild`
97316 verbose stack Exit status 1
97316 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
97316 verbose stack     at emitTwo (events.js:106:13)
97316 verbose stack     at EventEmitter.emit (events.js:191:7)
97316 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
97316 verbose stack     at emitTwo (events.js:106:13)
97316 verbose stack     at ChildProcess.emit (events.js:191:7)
97316 verbose stack     at maybeClose (internal/child_process.js:852:16)
97316 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
97317 verbose pkgid oniguruma@6.1.0
97318 verbose cwd c:\Users\User\vscode
97319 error Windows_NT 10.0.14393
97320 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
97321 error node v6.3.1
97322 error npm  v3.10.3
97323 error code ELIFECYCLE
97324 error oniguruma@6.1.0 install: `node-gyp rebuild`
97324 error Exit status 1
97325 error Failed at the oniguruma@6.1.0 install script 'node-gyp rebuild'.
97325 error Make sure you have the latest version of node.js and npm installed.
97325 error If you do, this is most likely a problem with the oniguruma package,
97325 error not with npm itself.
97325 error Tell the author that this fails on your system:
97325 error     node-gyp rebuild
97325 error You can get information on how to open an issue for this project with:
97325 error     npm bugs oniguruma
97325 error Or if that isn't available, you can get their info via:
97325 error     npm owner ls oniguruma
97325 error There is likely additional logging output above.
97326 verbose exit [ 1, true ]

**Comment by bpasero** [comment]
@nbapat43 first of all please make sure you have at least npm >= 3.10.8 as outlined in the setup guidelines (`npm install -g npm@3.10.8`)

Do you have Visual Studio installed?

**Comment by nbapat43** [comment]
I do have Visual Studio 2015 installed

My version was not 3.10.8 but I upgraded it to 3.10.8. After upgrading I did rerun the npm install in the scripts folder and cmd spammed me with the message "Maximum setlocal recursion level reached." I have seen this message before when in past attempts to set up debugging.

**Comment by bpasero** [comment]
What helps me in those cases typically is to really start fresh via "`git clean -xfd`" and then "`scripts\npm.bat install`"

**Comment by nbapat43** [comment]
I ran both commands as you suggested. But it still returned "Maximum setlocal recursion level reached."

**Comment by bpasero** [comment]
@joaomoreno does that error ring a bell? seems to originate from batch setlocal command?

**Comment by joaomoreno** [comment]
@nbapat43 Don't `cd scripts`. Just run `.\scripts\npm.bat install` from the root of the repository.

**Comment by nbapat43** [comment]
@joaomoreno [after running your suggestion this was my cmd's response.](https://cloud.githubusercontent.com/assets/15665980/18654938/b1be77f4-7e99-11e6-84c6-db99f0f459f0.PNG)

**Comment by bpasero** [comment]
@nbapat43 looks like your issue is solved, the output looks good to me 👍

**Comment by nbapat43** [comment]
K thank you very much for your help
