### ISSUE TITLE
搜索希望得到优化

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#12206]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 有很多时候明明搜索到了，但是确无法替换，或者无法搜索到对应的字段。

2. 搜索框希望能拖动。因为很多时候其他消息推送都在右上角。遮住了很不方便。
<img width="1005" alt="1111" src="https://cloud.githubusercontent.com/assets/15888370/18612421/e74fafdc-7d8b-11e6-9cc1-69e167b7140d.png">

**Comment by cw19931024** [comment]
刚才尝试了下，过了几分钟才出来搜索的字符。

**Comment by shibang** [comment]
你这样直接用中文人家不一定看懂啊

**Comment by zhaohaixin** [comment]
哈哈！

**Comment by songxuangh** [comment]
哈哈，你得翻译成英文在来发表，我就是这么做的

**Comment by ZCShou** [comment]
@cw19931024   再者 你所说的搜不到估计是因为你是在选中内容中查找的，看你的图片 明显 是这样！（右边第二个图标被选中）。

至于 搜索框 移动 这个提议貌似不错的！

ps：VSCode项目组里有国人的！名字忘了

**Comment by cw19931024** [comment]
。。我英文太渣。

**Comment by songxuangh** [comment]
English is not good, you can use the translation ah.
英文不好，你可以用翻译啊。

**Comment by bpasero** [comment]
@cw19931024 please report the issue in english

**Comment by songxuangh** [comment]
@cw19931024 
look, the project leader has asked you to report the issue in english.
看，项目负责人要求你用英语报告这个问题。
