### ISSUE TITLE
When debugging using extensionHost can we set directory?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#122006]
Often when debugging extensions using the `extensionHost` option this will launch a new window. But the directory seems to be wherever i was previously.
Different extensions need to load different directories.

Can we have an option in the launch settings to choose what folder VSCode launches with?

**Comment by gjsjohnmurray** [comment]
You can use `args` for this. Here's what one of my extension development workspaces defines in launch.json

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "extensionHost",
			"request": "launch",
			"name": "Extension",
			"preLaunchTask": "npm: webpack",
			"runtimeExecutable": "${execPath}",
			"args": [
				"${workspaceFolder}/../test/testSerenji.code-workspace",
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"stopOnEntry": false,
			"outFiles": [ "${workspaceFolder}/dist/**/*.js" ]
		},
...
```
