### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by bckelley** [microsoft/vscode#122052]
- VS Code Version:
- OS Version:

Steps to Reproduce:

1. happens on update release
2.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

when vscode launches i get a windows prompt:
```
setup has detected that setup is currently running
please close all instances of it now then click ok to continue or cancel to exit
```
I don't know what it wants i have tried close vscode and clicking ok, it does nothing. i have tried ending the task in manager and clicking ok  then clicking update now, and nothing. so what in the hell does it want from me!

**Comment by joaomoreno** [comment]
Have you tried restarting your machine?
