### ISSUE TITLE
Focus terminal tabs view should focus the active terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122039]
Repro:

1. Open several terminals
2. Click one tab
3. Right click another
4. Click in the editor
5. Run focus terminal tabs view command

The active terminal should be selected, not the right clicked one

**Comment by rzhao271** [comment]
When I right-click on a tab, focus now goes to that tab, so it becomes the active terminal.
I'm not sure whether that's intended behaviour.

**Comment by meganrogge** [comment]
Yeah it seems like right now right clicking is focusing and selecting the item. I'm not sure if that's what we want, but think that could be as-designed for `singleClick` mode.

**Comment by meganrogge** [comment]
looks like the change responsible for this behavior is https://github.com/microsoft/vscode/commit/5bf77b350f19dc282e8b01a6799a4f235babc5fa

**Comment by Tyriar** [comment]
Yes I don't think right click should be changing the active terminal
