### ISSUE TITLE
Unable to udate VSCode insider

### ISSUE THREAD

**Issue by KikeVen** [microsoft/vscode#122066]
Issue Type: <b>Bug</b>

Unable to write file 'c:\Users\james\AppData\Local\Temp\vscode-update-user-x64\CodeSetup-insider-0310f02dc5d834bb3a7cc421ea5374aec8d011f1.exe.tmp' (Error: net::ERR_CONNECTION_RESET)

VS Code version: Code - Insiders 1.55.0-insider (26a60dbecacc8bdacc06f7681ebe95398878a1cd, 2021-03-29T10:27:14.607Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (4.14GB free)|
|Process Argv|--crash-reporter-id 6a6165db-ebea-41ec-bc3b-d3e6005bd2fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
google-search-ext|ade|0.2.1
markdown-toc|Ala|1.5.6
Bookmarks|ale|13.0.4
project-manager|ale|12.1.0
vscode-sqlite|ale|0.12.0
arepl|alm|2.0.2
speech|bie|0.0.3
bracket-pair-colorizer-2|Coe|0.2.0
vscode-svgviewer|css|2.0.0
markdown-table-prettify|dar|3.3.0
vscode-markdownlint|Dav|0.40.3
xml|Dot|2.5.1
vscode-todo-plus|fab|4.18.3
pythonsnippets|frh|1.0.2
vscode-drawio|hed|1.4.0
fontawesome-autocomplete|Jan|1.1.2
vsc-python-indent|Kev|1.13.1
sftp|lix|1.12.9
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|1.8.1
python-path|mge|0.0.11
python|ms-|2021.3.680753044
vscode-pylance|ms-|2021.4.0
jupyter|ms-|2021.5.697286501
vsliveshare|ms-|1.0.4018
autodocstring|njp|0.5.4
printcode|nob|3.0.0
indent-rainbow|ode|7.5.0
ngrok-for-vscode|phi|1.8.4
material-icon-theme|PKi|4.6.0
LiveServer|rit|5.6.1
text-marker|ryu|1.11.0
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.17
html5-boilerplate|sid|1.1.1
code-spell-checker|str|1.10.2
vscode-markdown-paste-image|tel|0.12.3
pdf|tom|1.1.0
vscode-icons|vsc|11.4.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
markdown-editor|zaa|0.0.6
material-theme|zhu|3.9.15

(6 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
Can you reproduce if you restart your machine?
