### ISSUE TITLE
The Connection to the terminal pty host process is unresponsive

### ISSUE THREAD

**Issue by MaxBayne** [microsoft/vscode#122015]
- VS Code Version:
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
- OS Version:
windows 10

Steps to Reproduce:

1.i use vsCode For Developing Arduino With Platform.IO
2.when upload code to Arduino first time its work 
3.after open serial monitor and watch the serial output from arduino and when i try to upload again i see this stupid message
4.if i want to be fix this i must to close vsCode and restart again

[https://i.ibb.co/Pc21wQf/Capture.png](url)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
