### ISSUE TITLE
could not load tslint

### ISSUE THREAD

**Issue by tingwu55** [Microsoft/vscode#12209]
- VSCode Version: Code 1.4.0 (6276dcb0ae497766056b4c09ea75be1d76a8b679, 2016-08-04T16:45:31.680Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
See https://github.com/Microsoft/vscode-tslint/issues/88

**Comment by bpasero** [comment]
Please file tslint issues against tslint repository.

**Comment by tingwu55** [comment]
I'm sorry, and I won't make the same mistake next time.Thanks!
