### ISSUE TITLE
Please implement search within imported libraries feature 

### ISSUE THREAD

**Issue by jaepil-choi** [microsoft/vscode#122082]
I want to request a feature to search within imported libraries to not have to go to each library's Github to find out its structure and code. 

Currently, the search is only performed within the workspace and there's no way to search non-project files, especially the files within imported libraries. 

I heard PyCharm has a feature called search everywhere that you can search out of the scope of the project. I googled for the equivalent feature in VSCode but couldn't find any. 

What's your thought about this feature suggestion?

**Comment by roblourens** [comment]
Text search? You can click the button in the "Files to exclude" box to disable file excludes.

We don't have an equivalent feature for file search but there is an open request for it.

**Comment by jaepil-choi** [comment]
@roblourens I am aware that there's a "files to exclude" box, but that only narrows the scope, not expands the scope to search libraries installed somewhere else. For example, if I'm using Anaconda environment (which is typically installed in `C:\User\username\anaconda3`) and set it as the interpreter for the current VSCode instance, I would like to be able to search the code of imported libraries (in conda environment) that I'm using in my project. 

Say, I'm using numpy and import it by `import numpy as np`. Sometimes I have to look into the structure of `numpy`'s code and I have to go to numpy's github repo every time to do that. Would have been much better if I could explore `numpy`'s code inside VSCode and that's what I was saying. 

So when you said "there's an open request for it", do you mean that this feature suggestion is duplicate? Have you closed it because it's already in VSCode dev's queue?

**Comment by roblourens** [comment]
The button expands the scope by disabling excludes. But actually it sounds like you want to search outside of the workspace in some other folders based on some language analysis of your project. I don't have an open request for that, I don't plan to add language smarts to search, it's just not a good fit for how language extensions and search work. But, you can put that other folder path in "files to include" to search it that way.
