### ISSUE TITLE
Test: Backup format changes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122029]
Refs: 

- [x] macOS @sbatten
- [x] linux @RMacfarlane
- [x] windows @isidorn

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122029%0A%0A)

---

Our backup service changed significantly in this release, specifically:
* backups are no longer identified by a resource alone, but also a `typeId: string` to allow multiple backups with the same resource
* backups used to persist the content strictly as text, but now it is buffer (byte) based

Because we obviously have a lot of existing backups with the previous format, we want to make sure to not loose these older backups when starting the newer version of VSCode.

**Bootstrap**
* use the `--user-data-dir <some empty folder>` CLI argument to ensure testing happens on a fresh data directory
* start VSCode stable `1.55.x` on that user data folder and open some files (also untitled) and make them dirty so that backups are created
* close VSCode stable

**Test**
* use insiders on the same user data folder directory as before
* verify the dirty files appear with their contents as you left them in all of the windows
* close and restart again
* verify again that the dirty files are still there
* close VSCode
* open a terminal and start VSCode on the folder with the untitled files but also specify a specific file to open in that folder (e.g. `code-insiders <path to folder> <path to file in folder>` (this way of launching is special because we do not restore the previous editors and only open the ones from the command line + any editor with backup)
* verify that again your backups are restored properly
* craft a very large dirty text file (>512KB) with non UTF-8 encoding (e.g.  UTF-16) and verify the contents are properly restored between restarts and displayed properly

**Comment by isidorn** [comment]
Works great for me on Windows 👏
