### ISSUE TITLE
ng插件焦点异常bug

### ISSUE THREAD

**Issue by cw19931024** [Microsoft/vscode#12208]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. angular插件焦点bug
<img width="630" alt="212" src="https://cloud.githubusercontent.com/assets/15888370/18614159/1b3d39ce-7dbc-11e6-8fbd-a56434f7fe62.png">
<img width="757" alt="323" src="https://cloud.githubusercontent.com/assets/15888370/18614161/20a624c0-7dbc-11e6-853e-e10875f6f60d.png">
大概是这样的，我在图片1中添加个ng-class,结果焦点却跑到后面去了。

**Comment by bpasero** [comment]
@cw19931024 can you please provide the issue in english?
