### ISSUE TITLE
Views should not automatically focus input boxes on the iPad

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122044]
Currently when the view is opened if the focus is automatically moved to the input box the iPad will open a On Screen Keyboard which is not a nice experience. Due to this I suggest that on view open we do not pass focus to the input box on the ipad. Here are the cases where we automatically focus the input:

* - [x] SCM @eamodio 
* - [x] Search @JacksonKearl 
* - [x] Extensions @sandy081 
* - [x] Keyboard shortcuts @sandy081 
* - [x] Settings @roblourens 
* - [x] Output @isidorn 

Here's the check which you can use 
https://github.com/microsoft/vscode/blob/main/src/vs/base/common/platform.ts#L164

Thanks for help!

We will also open regular editor in readonly, for reference here's the issue https://github.com/microsoft/vscode/issues/120943

**Comment by isidorn** [comment]
I have made the output readonly thus it no longer triggers the keyboard.
As for the other usages please let me know if you will not have time in May and I can help if needed.

**Comment by isidorn** [comment]
Assigning to myself for @sandy081 
@JacksonKearl @eamodio will you have time to look into yours?

**Comment by isidorn** [comment]
I have also pushed a change for the SCM.
@eamodio if you would like you can review this here https://github.com/microsoft/vscode/commit/063be236f34c2ef37322ae157366e52624b1faee

Thanks for help

**Comment by isidorn** [comment]
To verify: get an iPad and do not have an external keyboard connected to it. Make sure that opening the views above does not pop out the keyboard at the bottom. That the keyboard pops out only when you explicitly touch the input box.

**Comment by connor4312** [comment]
@rebornix this might be a good one for you since I know you have an ipad

**Comment by isidorn** [comment]
Also maybe @weinand for verification :)

**Comment by isidorn** [comment]
After discussing with @bpasero we agreed that ideally we would change the logic here. Not to behave differently when there is an iPad, but if the action was triggered using a Touch gesture. If it was triggered via a mouse it should behave as usual. More details here for those interested https://github.com/microsoft/vscode/issues/125470

However wiring down if the focus was triggered by a touch or mouse might be a bit ugly, but I can take a look and if it looks possible I will try to make the changes.

**Comment by isidorn** [comment]
Pushed a slightly nicer solution: that on tap we do not pass focus, but on mouse click we pass focus.
I could nicely remove the dependency to isIOS from all viewlets. The only remaining dependency was the settings ux since it is not a viewlet.
