### ISSUE TITLE
Possible to keep undo history after closing vscode?

### ISSUE THREAD

**Issue by pepeu93** [microsoft/vscode#122074]
If i close vscode and open again i lose all undo history , is possible to keep it even closing the editor?

**Comment by tymsai** [comment]
No

**Comment by pepeu93** [comment]
There's any extension that does it?

**Comment by tymsai** [comment]
maynot be

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/7536
