### ISSUE TITLE
VSCode is just eating CPU cycles

### ISSUE THREAD

**Issue by spierepf** [microsoft/vscode#122019]
- VS Code Version: code-1.55.2-1618307357.el8.x86_64.rpm
- OS Version: Linux xxx 3.10.0-1160.2.1.el7.x86_64 #1 SMP Mon Sep 21 21:00:09 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Install the rpm `$ sudo yum install ./Downloads/code-1.55.2-1618307357.el8.x86_64.rpm`
2. Start VSCode `$ code`

Does this issue occur when all extensions are disabled?: Yes

**Comment by spierepf** [comment]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                               
14782 peter     20   0 5008764  92876  52040 R 105.9  0.6   0:10.22 code                                                                                                                                                                                                                  
14878 peter     20   0 4666032  80420  32148 R  94.1  0.5   0:09.56 code    
```

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.

**Comment by spierepf** [comment]
I cannot open the help menu.

![image](https://user-images.githubusercontent.com/548990/115877399-c6212580-a41d-11eb-9093-537f5a96f4b3.png)

**Comment by spierepf** [comment]
Even if I disable extensions:
![image](https://user-images.githubusercontent.com/548990/115877696-1dbf9100-a41e-11eb-80d5-c3e83c324b4e.png)

**Comment by spierepf** [comment]
![image](https://user-images.githubusercontent.com/548990/115877751-2dd77080-a41e-11eb-968d-805f3fde6679.png)

**Comment by spierepf** [comment]
Where can I go for support?

**Comment by deepak1556** [comment]
Can you provide the output of `code --verbose`
