### ISSUE TITLE
Codicons fail to load on Windows

### ISSUE THREAD

**Issue by mhunterP965** [microsoft/vscode#122021]
Issue Type: <b>Bug</b>

Fresh Install 2019 Community // No Icons upon application start

Michael Hunter
315.877.1087
mhunterP965@gmail.com
mhunter@huntersolutions.us

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.23GB free)|
|Process Argv|--crash-reporter-id 40d021c2-6dc1-49ca-9ca7-2c3621fd25fc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|2.0.1
vim|vsc|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vscnewfiletext:30288035
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553

```

</details>

![VSCodeIssueMHunter20210423](https://user-images.githubusercontent.com/83076462/115878116-2c09af00-a416-11eb-9be6-947fbfadf7ed.jpg)

**Comment by mhunterP965** [comment]
The issue started upon removing VS2017 and adding VS2019, both community editions.  Since adding VS2019, I've removed and reinstalled the latest Visual Studio Code twice, with no change in results. :(

**Comment by misolori** [comment]
The VS installations have nothing to do with VS Code. Do you have any firewalls that may be blocking fonts from being loaded? Can you open the console (Command Palette > Toggle Developer Tools) and paste the results here? Have you also tried restarting your machine?

**Comment by mhunterP965** [comment]
Thanks, Misolori, I appreciate your help here.  

I have restarted my machine and reinstalled it.  I've also tried toggling off both the firewall and VPN, but the problem still persists.  Below is the capture from the console tab from "Toggle Developer Tools".
---------------------------------------------------------------------------------------------------------
Some messages have been moved to the Issues panel.
View issues
/C:/Users/mhunter/Ap….desktop.main.js:60 [6a6] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
/C:/Users/mhunter/Ap….desktop.main.js:60     at file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58492
    at file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60975
    at new Promise (<anonymous>)
    at Object.x [as toPromise] (file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60956)
    at k.whenInitialized (file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2720
    at f (file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:11213)
    at file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2710
    at new Promise (<anonymous>)
    at k.requestPromise (file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:2252)
    at Object.call (file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:1941)
    at file:///C:/Users/mhunter/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:7092
/C:/Users/mhunter/Ap….desktop.main.js:62 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open 'c:\Users\mhunter\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
/C:/Users/mhunter/Ap….desktop.main.js:62 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open 'c:\Users\mhunter\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'
/C:/Users/mhunter/Ap…desktop.main.js:626   ERR ENOENT: no such file or directory, open 'c:\Users\mhunter\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers': Error: ENOENT: no such file or directory, open 'c:\Users\mhunter\AppData\Roaming\Code\User\globalStorage\vscodevim.vim\.registers'

**Comment by misolori** [comment]
Ok, so this looks a similar issue to https://github.com/microsoft/vscode/issues/85872 and https://github.com/microsoft/vscode/issues/110288. 

Do you have any special font software installed (like [mactype](https://mactype.net/))? Anything that would disable fonts from loading? The workaround suggested in https://github.com/microsoft/vscode/issues/85872#issuecomment-674633829 is to manually install the icon font but would like to understand the issue more.

cc @deepak1556 @aeschli as this keeps coming up

**Comment by mhunterP965** [comment]
Yes, I do run mactype.  I tried downloading the fonts and adding them per the comment but the icons are still all missing.

**Comment by misolori** [comment]
@mhunterP965 can you try disabling VS Code from using mactype and see if that fixes it?

**Comment by mhunterP965** [comment]
I disabled mactype; but it made no difference.  I still don't see any icons.

**Comment by mhunterP965** [comment]
Hi, thank you for pointing me to #85872.  I downloaded codicon.ttf and installed it manually and the problem disappeared--I now have my icons back in the IDE, and I'm running mactype.  Any other thoughts on what may have caused the fonts not to have loaded?  Would NordVPN affect this during an install?

**Comment by misolori** [comment]
It has something to do with your local system blocking the icon font from loading and unsure why. Sometimes mactype is the issue other times it could be a system firewall. This is really a strange bug.

**Comment by mhunterP965** [comment]
I agree.  The good thing is that it's fixed and In can get back to coding.

Thank you for all the help.

Cheers,

-Mike


Michael Hunter
315-877-1087 | linkedin.com/in/michael-hunter-pmp

**Comment by misolori** [comment]
You'll likely see squares again in the future for when we add new icons to our library. I'll keep this issue open to point others here.

**Comment by misolori** [comment]
Haven't seen more issues related to this so closing out this issue. If it keeps happening we will revisit.
