### ISSUE TITLE
Get Rid of Menu Bar on Mac

### ISSUE THREAD

**Issue by lewisl** [microsoft/vscode#122042]
Issue Type: <b>Bug</b>

On Windows and Linux, there is a command on the view menu to get rid of the abhorrent UI ornament. It is IMPOSSIBLE on Mac. With 2 groups open and several tabs, often the close button of a tab is obscured. Make it toggle-able easily if you insist. But, please allow Mac users to get rid of this severe annoyance.

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:36:32.643Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 86176b33-be04-4bff-a88d-93ced48f9294|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.0.4
toml|be5|0.5.1
markdown-preview-github-styles|bie|0.2.0
xml2json|bui|1.2.4
bracket-pair-colorizer-2|Coe|0.2.0
docs-yaml|doc|0.2.6
githistory|don|0.6.16
go|gol|0.24.2
activitusbar|Gru|0.0.41
shortcut-menu-bar|jer|3.0.1
vscode-go-template|jin|0.2.1
diff-tool|jin|0.0.1
language-julia|jul|1.1.38
nim|kos|0.6.6
git-graph|mhu|1.30.0
code-beautifier|mic|2.3.3
python|ms-|2021.4.765268190
jupyter|ms-|2021.5.745244803
cpptools|ms-|1.3.1
sublime-keybindings|ms-|4.0.8
VSNotebooks|pav|1.4.4
subtle-brackets|raf|3.0.0
vscode-yaml|red|0.18.0
LiveServer|rit|5.6.1
guides|spy|0.9.3
prettier-plus|svi|4.2.2
even-better-toml|tam|0.12.1
go-to-method|tri|0.2.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by nobodyindustries** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80129636/115973266-52396700-a55c-11eb-872a-122a3488c04e.png">

I am not sure what is going on there, but maybe the screen cap can help, I don't have any "severe annoyance"
