### ISSUE TITLE
Outline view: hidden by default on iPad

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122046]
I think we could hide the outline view by default on the iPad. Reaons:
* iPad is more of a light weight experience and has less screen real estate
* Outline is the only view apart from Explorer in the Explorer viewlet. So if the explorer viewlet was the only one everything would be cleaner

@jrieken let me know if you do not mind this change and I can also do it.
Here's the ipad check we use https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/browser.ts#L118
I might need to introduce a context key for it

**Comment by jrieken** [comment]
> @jrieken let me know if you do not mind this change and I can also do it.

Outline was one of the top most requested features, being able to change the position of outline is still one of the most requested features. We (including me) don't use outline and have therefore trouble to understand that but I will not support any change like this without solid telemetry numbers.

**Comment by isidorn** [comment]
But I can not get telemetry numbers since we do not have ipad users.
And if I wait for numbers that means we have users and then hiding something might just piss them off.

If you prefer to have it shown feel free to close this issue.
But I think we can start by having it hidden and if we hear multiple requests from iPad users for the outline we can just bring it back.

**Comment by jrieken** [comment]
Well, I think your reasoning in totally arbitrary. Why outline and not timeline? Why not both? What about viewlet titles vs view titles? 

Please, don't get me wrong, I am not against iPad specific UI tweaks but picking on the outline seems totally random to me and given there is many outline-fans I am not willing to start like this. Also, let's not forget that the outline view is collapsed by default. So, out of the box it uses 22px which is 1 or 1,3% of the [iPad](https://www.apple.com/ipad-pro/specs/) screen hight (in landscape mode).

So, "yes" my suggestion is that VS Code on the iPad is as close as possible as VS Code on desktop and that we use feedback and telemetry to make sound decisions to specific tweaks

**Comment by digitarald** [comment]
Understanding use cases of iPad users would start at the root. One assumption could be that reading is a primary use case, so code navigation would be important and therefor the outline view?

If users need the space it seems easy to enough to toggle. Even if we kick off user research for iPad devs I am not sure if we can ever inform changes as small as hiding/showing specific panels. A proxy device that has more users, like laptops with small screens, could help to run experiments that get close enough; but potentially misleading.

@misolori might have more UX guided thoughts.
