### ISSUE TITLE
CTRL+SCROLL doesn't work like before

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode#122088]
- OS Version: Debian Buster 10 with XFCE
- Machine: STi IS1412 with 2GB and SSD 120GB with more 50% used and processor running in 1.20 Ghz

Steps to Reproduce:

1. open vscode
2. open two files
3. ctrl+page up or ctrl+page down should change between the files

Does this issue occur when all extensions are disabled?: Yes[x]/No

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+pagedown`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire (`ctrl+pagedown`)
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
