### ISSUE TITLE
Workspace trust should move closer to config service init

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122020]
I feel this code should move into the `createWorkspaceService`:

https://github.com/microsoft/vscode/blob/6779f85321456851940ea2b79233089d78596f1f/src/vs/workbench/electron-sandbox/shared.desktop.main.ts#L269-L271

https://github.com/microsoft/vscode/blob/6779f85321456851940ea2b79233089d78596f1f/src/vs/workbench/browser/web.main.ts#L210-L212

**Comment by sandy081** [comment]
`WorkspaceTrustManagementService` has a dependency on `StorageService` and `StorageService` is not available when `createWorkspaceService` is called - So I am not sure how we can move to `createWorkspaceService`

**Comment by bpasero** [comment]
I see. I think my confusion was that `WorkspaceTrustManagementService` seems to need both storage and config service to work. I would have probably expected that the configuration service gets the `WorkspaceTrustManagementService` passed in to handle the `updateWorkspaceTrust` from within instead of doing this from the outside.

**Comment by lszomoru** [comment]
The `WorkspaceTrustManagementService` needs the configuration service as it needs to check whether the feature is enabled or not by reading a user setting. Do we have a patten for reading the value of a setting without taking a dependency on the configuration service?

**Comment by bpasero** [comment]
No I don't think so. I don't have strong feelings so feel free to close.

**Comment by lszomoru** [comment]
Ok. Will close it for now, as in the future `WorkspaceTrustManagementService` will not need the configuration service any more.
