### ISSUE TITLE
Unknown Configuration Setting error for known setting

### ISSUE THREAD

**Issue by kirkbross** [microsoft/vscode#122070]
- VS Code Version: 
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0

OS: Windows_NT x64 10.0.19042
- OS Version:
Windows 10

Steps to Reproduce:

1. Add this line to your settings.json: `"javascript.updateImportsOnFileMove.enabled": "prompt",`
2. See error: Unknown Configuration Setting
3. If this has been rename a smarter error, or deprecated waring would be great.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
![image](https://user-images.githubusercontent.com/1312662/115972303-3763f400-a556-11eb-9dad-c58da6c6a975.png)
Unable to reproduce this issue in clean Stable install.

/needsMoreInfo

Are you sure that you haven't disablet extension `@builtin TypeScript and JavaScript Language Features`?
