### ISSUE TITLE
Hide New Terminal UI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#122068]
Thanks for the new feature for the terminal (UI - to manage terminals).
However I'm not a big fan of this, it takes up space I'd rather use for the terminal.
Is it possible to completely hide this or have it show upas a toolbar?

Apologies if this is a duplicate.

**Comment by DonJayamanne** [comment]
FYI - I'm referring to the following in VS Code Insiders.
![Screen Shot 2021-04-23 at 14 17 25](https://user-images.githubusercontent.com/1948812/115930619-a9491a00-a43e-11eb-874d-0f2cc44bd687.png)

**Comment by usernamehw** [comment]
```js
"terminal.integrated.showTabs": false,
```
