### ISSUE TITLE
Web startup waterfall

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#122018]
https://github.com/microsoft/vscode/blob/6779f85321456851940ea2b79233089d78596f1f/src/vs/workbench/browser/web.main.ts#L222-L237

This `await` should join the other `awaits` above if possibe:

https://github.com/microsoft/vscode/blob/6779f85321456851940ea2b79233089d78596f1f/src/vs/workbench/browser/web.main.ts#L184-L184

**Comment by sandy081** [comment]
User data initialization requires storage and configuration, so it cannot be merged with storage and configuration init.
