### ISSUE TITLE
Test: New EditorOverride Service

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#122030]
To reduce on duplicated custom editor and notebook debt we have moved the idea of editor override into its own service.

- [x] macOS @bpasero 
- [x] windows @meganrogge
- [x] linux @connor4312

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23122030%0A%0A)

---

To test please ensure there are no regressions in the custom editor and notebook experience. I recommend you install Markdown Notebooks, Luna Paint, Github-issue notebooks, and the Hex Editor to test editors of all priorities and types.  Please ensure that the following works as expected:

- Right click -> Open With
- Command Palette -> Reopen Editor With...
- Right click -> Open to the side
- Splitting and moving across groups 
- Setting your user setting by clicking the gear icon in the Reopen with quick pikc.
- Default editor conflict resolution (With no setting set open a .png file, you should see Luna paint and a notification to choose a default).

**Comment by bpasero** [comment]
👏
