### ISSUE TITLE
Adjust Font size for Find Widget and Auto-fit 

### ISSUE THREAD

**Issue by altimmons** [microsoft/vscode#122065]
I use reg-ex a lot, I take notes in markdown and its just easy for me at this point to change one format to another when things copy in weird. etc, etc,  Reason isnt all that relevant-  but here:  

![](https://i.imgur.com/iAZ6c38.png)

The font size is much to small for me.  I haven't yet found a setting that modifies it.  And changing everything (via zoom level) is not ideal either, as then I have to scale every other setting.  

If we can adjust CodeLens, this should also be adjustable.  As is- its quite difficult to do complicated regex sequences as common chars such as {[(, ,., li1 etc are difficult to discern.

In addition, long sequences are often out of scope, you have to manually stretch the bar or scroll with the cursor to see the rest.  It would be nice if that box automatically grew horizontally to say ~80% of the width of the editor.  It would also be nice - (in some use cases) if it grew vertically as well.  For multiline matches.

It grows vertically now, though in weird circumstances that dont seem consistent. 

2.) For regex matches it would be nice to "assume" the closing paren as default.  This helps when writing them on the fly and you are looking at the highlights and match counts to see you are going in the right direction.  It seems trivial to "assume" a closing paren if the current search string comes up invalid.  Its just an ease of life thing.  I dont think the auto close parentheses setting works in the box either.
- making auto-close parentheses in the search box an option might actually be the easier implementation.

3) there were a few regex features I noticed that VScode seems to lack.
 It would be nice to at least document the feature set that VSCode intends to support.  Things that are standard in MSFT documentation (for C/C++/C#) are missing here.  And though I am sure the correct place to look might be the javascript/typescript doc on the topic, I have yet to see that.

The relevant settings appear to be:

```css
.monaco-editor .find-widget .monaco-findInput .input {
    font-size: 13px
}
```

**Comment by ArturoDent** [comment]
See https://github.com/microsoft/vscode/issues/101064 for find widget font size.
