### ISSUE TITLE
User Snippets multiple same name variables maintain multiple cursor positions on completion

### ISSUE THREAD

**Issue by cpamp21** [Microsoft/vscode#12201]
- VSCode Version: 1.5.2
- OS Version: Win10

Steps to Reproduce:

1. Create user snippet with multiple variables of same name
2. Use the snippet
3. Press enter to complete while editing the variable that has multiple locations
4. VSCode maintains multiple cursor positions at all of the locations of the variable

After completing a user snippet there should only be one cursor position

**Comment by alexandrudima** [comment]
@cpamp21 Can you please include here the actual snippet you're using?

**Comment by cpamp21** [comment]
Javascript.json:
```
"IIFE": {
	"prefix": "jsiife",
	"body": [
		"(function(${params:params}) {",
		"",
		"})(${params:params});"
	]
}
```

**Comment by alexandrudima** [comment]
I see, this snippet does not contain an end cursor position, so at the end (when leaving snippet mode) the two cursors are still maintained and the only way to get rid of them is through `Escape`. 

@cpamp21 Usually snippets contain `$0` to indicate the end cursor position. Would using `$0` work for you or would you necessarily expect that we remove extra cursors also for such snippets (that lack a `$0`)? i.e. I would change your snippet to (which makes sure the cursor is in a good spot at the end):

```json
"IIFE": {
    "prefix": "jsiife",
    "body": [
        "(function(${params:params}) {",
        "\t$0",
        "})(${params:params});"
    ]
```

**Comment by cpamp21** [comment]
@alexandrudima Thank you. I would expect them to be removed but I think using `$0` is preferred here.
