### ISSUE TITLE
Extension search results triggered by debugging is very unspecific

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#122079]
Follow up from #119110, reviewing this with Java the search results are confusing.

Debugging a java file triggers the search for `tag:debuggers @sort:installs Java`:

<img width=200 src=https://user-images.githubusercontent.com/8599/115935410-f5e52300-a447-11eb-99f2-223b1ce60890.png>

_😢 Java Pack, the recommended extension for `java` files, the important one is all the way down._

Even the `ext:java` search triggered by the language switcher isn't putting Java ext pack very high:

<img width=200 src=https://user-images.githubusercontent.com/8599/115935661-8885c200-a448-11eb-858d-9249808bab39.png>

Trying different searches like `tag:debuggers ext:java` – doesn't seem to be a `or` search, as it shows Python first.

Potential solutions:

- Directly point users to a single extension if the current file type has an important recommendation
- Fix search to be smarter with combo searches like `tag:debuggers ext:java`

cc @fiveisprime @sana-ajani

**Comment by isidorn** [comment]
Please also file this against the marketplace team here https://github.com/microsoft/vsmarketplace

**Comment by digitarald** [comment]
Done https://github.com/microsoft/vsmarketplace/issues/68

**Comment by isidorn** [comment]
Great, thanks a lot.

**Comment by sana-ajani** [comment]
@isidorn The search results are a bit wonky based on the query, but I think changing the query slightly might help. 

Instead of `tag:debuggers @sort:installs java`, if we remove the `@sort:installs` from the query and just do the `tag:debuggers <language name>", the results are showing the correct extension. I've tried this for python, java, c++.

**Comment by isidorn** [comment]
@sana-ajani good point, I can do that, assigning this to April for that tweak. It is always surprising to me how strangely that search works.

**Comment by isidorn** [comment]
Search is further improved by removing `sort:installs`, also the query is more easily readable thus removing it.
@connor4312 thanks for changing `tags` to be `category`
