### ISSUE TITLE
I lost the Arrow to collapse line of code

### ISSUE THREAD

**Issue by alexPertise** [microsoft/vscode#122043]
Issue Type: <b>Bug</b>

I don't know why, but recently each time I open Vs Code the little arrow to the right of the line number just don't show up. I cant collapse/fold my code. Do you know why ? Thanks

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by aeschli** [comment]
@alexPertise Does it happen for type of files, or for files of a certain language?

**Comment by alexPertise** [comment]
Yes Only for .cshtml type of files

**Comment by alexPertise** [comment]
@aeschli   I found out why! When in **_aspnetcorerazor_**,  .cshtml element can't be fold. But when I switched to **_razor_** it worked. 
Is it the expected behavior or the collapse arrows should always be there?
![image](https://user-images.githubusercontent.com/83086032/116468824-5bb61e00-a83f-11eb-8db3-26f1269b14bd.png)
![image](https://user-images.githubusercontent.com/83086032/116468983-8d2ee980-a83f-11eb-9754-ef32f1155655.png)

**Comment by aeschli** [comment]
The folding ranges depend on the language extensions that you have installed.
If you think there's a bug with one of the languages, we need to find out which extension is to blame so you can file an issue against that language.
I believe aspnetcorerazor comes from https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
Can you file an issue with a small code sample here: https://github.com/OmniSharp/omnisharp-vscode/issues ?
