### ISSUE TITLE
vscode中文输入的问题

### ISSUE THREAD

**Issue by zhengshaobang** [microsoft/vscode#122092]
- VS Code Version: 1.55.2
- OS Version:window （*64）

Steps to Reproduce:
输入中文的时候遇到的问题。如视频所示。比如在原为“hello”的字节后继续输入中文“你好”结果会是这样的：“helln你好”（o被中文拼音第一个字母替代了）并且除了打字，中文状态下打符号也是如此。
再关闭所有拓展后似乎不会出现问题，但是前一段时间一个一个地试是哪个扩展出了问题也找不到，甚至出现了扩展不变但是问题有时出现有时没问题的情况。
今天用了这个扩展二等分去查，结果除了全部关闭的时候没问题外，都出现了问题，最后他给出的结论是可能是code出现了问题。
期盼得到大家的帮助，万分感谢。

https://user-images.githubusercontent.com/83111803/115954297-be977480-a522-11eb-8ac6-530346a9350d.mp4

（本来还有一个视频，但是怎么也上传不了。。。罢了）

Does this issue occur when all extensions are disabled?: No

**Comment by BettyJJ** [comment]
你这个会不会是输入法的问题？先换个输入法试试？

**Comment by zhengshaobang** [comment]
（不知道怎么评论别人的回答，可以的吗）应该不是输入法的问题，因为用电脑很久都没下过其他输入法，都是用的这次的微软输入法。而且在DW里面可以正常输入，包括在关闭所有插件的情况下也可以。

**Comment by zhengshaobang** [comment]
The problem seems to have been partially solved now. Typing is fine, but there are still errors in typing Chinese symbols。
这个问题似乎现在解决了一部分，打字没问题了，但是打中文符号仍存在错误
