### ISSUE TITLE
Folder added to workspace displays '!' warning in Explorer if folder is hosted by a FileSystemProvider implemented in an extension that is not yet activated

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#122004]
Issue Type: <b>Bug</b>

1. Install the MemFS extension from Marketplace, authored by @jrieken
2. Create an empty .code-workspace file with this content:
```
{
	"folders": [],
	"settings": {}
}
```
3. Open it as a workspace.
4. Edit the workspace file to add one folder that uses the memfs scheme with the MemFS extension implements.
```
{
	"folders": [
		{
			"name": "MemFS - Manually added",
			"uri": "memfs:/"
		}
	],
	"settings": {}
}
```
5. After saving the updated workspace file, observe that Explorer shows the added folder but decorates it with a warning exclamation point. Hover over the folder label to see the message `\ ● Unable to resolve workspace folder`

![image](https://user-images.githubusercontent.com/6726799/115852841-6c6e2a80-a420-11eb-878e-7a43a17a7327.png)

I think the problem occurs because even though the MemFS extension specifies "onFileSystem:memfs" as one of its activation events, when VS Code adds the new folder to the currently-open (though empty) workspace it apparently doesn't activate the extension in time before going looking for a .vscode folder within the new memfs root.

By running `Developer: Show Running Extensions` before doing this we can see that MemFS **does** get launched. I guess this just doesn't happen soon enough.

By contrast, if the memfs root is defined in the workspace at the point where the .code-workspace file is loaded the extension activates early enough and no warning indicator appears. This can be observed by running the `Developer: Reload Window` command. The memfs:/ root now displays normally.

VS Code version: Code - Insiders 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1, 2021-04-23T05:13:46.805Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
@gjsjohnmurray I see you are already deep down investigating this. If you have a good proposal for a PR how to fix this I would be open to review.
Thanks a lot for letting us know about this.

**Comment by gjsjohnmurray** [comment]
@isidorn is it true that the extension host won't be running at the time that this gets called?

https://github.com/microsoft/vscode/blob/66f0c29ddb32bdfc7084b77a34e0095e23f00889/src/vs/workbench/services/configuration/browser/configurationService.ts#L382-L403

The comments suggest that's true, in which case the line 400 call to checkAndMarkWorkspaceComplete goes via toValidWorkspaceFolders into FileService. Then resolve -> doResolveFile -> withProvider -> activateProvider which I think would normally be where the onFileSystem extension activation event would get the FSP extension activated. But if there's no EH then I assume this fails, so withProvider throws.

**Comment by isidorn** [comment]
@sandy081 might be better to answer this.

**Comment by gjsjohnmurray** [comment]
@sandy081 I began trying to enhance this in WorkspaceService:

https://github.com/microsoft/vscode/blob/8fa05403b6b8623f2b58fad718edf596b2b4058f/src/vs/workbench/services/configuration/browser/configurationService.ts#L823-L839

My idea was to gather the failures during the first (currently, the only) pass, then add a second pass which begins by awaiting `whenInstalledExtensionsRegistered` in the extension service. But the workspace service doesn't currently have access to the extension service, right?

**Comment by sandy081** [comment]
@gjsjohnmurray I do not think above validation is causing the warning in the explorer. Above validation is only to check if the entry is a directory or not. 

The warning in explorer is shown when it cannot resolve the workspace folder. I think following events are happening in this case

- A new folder is added to workspace file as first folder
- Workspace service triggers change event about this and there are following listeners which are prominent in this scenario
  - Extension host is restarted as first folder is changed
  - Explorer shows the folder

I think explorer is not recovering from extension host restart and hence warning is shown even after ext host is restarted. @isidorn Please check and confirm.

**Comment by gjsjohnmurray** [comment]
@sandy081 it's not the `!result.isDirectory` which is triggering. Rather, the resolve on line 829 is throwing, and the catch merely writes it to the console log and continues.

**Comment by sandy081** [comment]
>  Rather, the resolve on line 829 is throwing, and the catch merely writes it to the console log and continues.

Yeah that is intended and I think this is nothing to do with the warning in the explorer.

**Comment by isidorn** [comment]
@sandy081 ok, so it seems like the explorer needs a fresh start on et host restart... Thanks for investigating

**Comment by isidorn** [comment]
This should behave a bit better now with our aggressive explorer refresh when window gains focus again or explorer gets visible.
Closing as no other action planned for now
