### ISSUE TITLE
Ghost shadow in the terminal when hovering over a link in the Codespaces welcome message

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#122026]
pls see the screenshot below.
To reproduce:
- open a repository without a devcontainer.json, so that the kitchsink/universal image is used
- in the terminal welcome message hover over the link shown in the message

![image](https://user-images.githubusercontent.com/172399/115884719-82dfaa80-a44f-11eb-84e2-76140c8cc7e8.png)

**Comment by Tyriar** [comment]
Looks like this one https://github.com/microsoft/vscode/issues/118587

/duplicate
