### ISSUE TITLE
Shortcut "Ctrl + D" of Multi-select in new document can't work normally

### ISSUE THREAD

**Issue by yzpTsubasa** [Microsoft/vscode#12204]
- VSCode Version: 1.6.0 - insider
- OS Version: Windows 7

Steps to Reproduce:
1. create a new Document: A.example(Not saved locally)
2. Type "Hello World"
3. Select first "l" (3rd letter)
4. Use shortcut "Ctrl + D" to select second "l" (4th letter)
5. Use shortcut "Ctrl + D" to select third "l" (10th letter).
   But doesn't work, This make select target "ll"(Double l) but not "l"

**Comment by alexandrudima** [comment]
Currently, we collapsed multiple cursors that are touching each other. To revisit if this is still really needed.

**Comment by alexandrudima** [comment]
Duplicate of #6661
