### ISSUE TITLE
OutputChannel is stuck in a specific case

### ISSUE THREAD

**Issue by m417z** [microsoft/vscode#122047]
- VS Code Version: 1.55.2
- OS Version: Windows 10

Steps to Reproduce:

1. Run the code below.
2. Notice that the `OutputChannel` window is not interactable and contains no text, as in the gif below.

		let outputChannel = vscode.window.createOutputChannel('Test Log');
		outputChannel.show();
		outputChannel.appendLine('test1');
		
		setTimeout(() => {
			vscode.commands.executeCommand('workbench.action.closePanel').then(() => {
				outputChannel.dispose();
				setTimeout(() => {
					outputChannel = vscode.window.createOutputChannel('Test Log');
					outputChannel.show();
					outputChannel.appendLine('test2');
				}, 1000);
			});
		}, 1000);

![UXzLcxEkvz](https://user-images.githubusercontent.com/4129781/115906838-bd0d7400-a470-11eb-8d35-e2b69a03d04a.gif)

Does this issue occur when all extensions are disabled?: Yes (except the one running the snippet)

**Comment by sandy081** [comment]
Assigning to May for investigation

**Comment by m417z** [comment]
Seems to be fixed in 1.58.0.
