### ISSUE TITLE
Getting Started: Why do we need to specify the step type?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#122090]
I would think this could just be determined from the file extension?

<img width="442" alt="Screen Shot 2021-04-24 at 2 16 41 AM" src="https://user-images.githubusercontent.com/2193314/115953925-1d1d0e00-a4a3-11eb-9c1e-bd030661c61c.png">

**Comment by JacksonKearl** [comment]
Good point, removed in favor of `path.endsWith('.md')`
