### ISSUE TITLE
Editor context menu badly positioned

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#122035]
iPad, sometime I can get the editor to render the context menu is a wrong place -> top left corner.
Easy to reproduce: attach an external mouse and use the right click to trigger a menu in the editor

@rebornix might you have an idea what this is? You can also give me a code pointer so I investigate futher..

![851E6B1C-DA31-4FD5-A24C-D5BA121AAC6F](https://user-images.githubusercontent.com/1926584/115894772-ed95e380-a459-11eb-8b13-7618e1339f89.png)

**Comment by rebornix** [comment]
@isidorn I can investigate

**Comment by isidorn** [comment]
I have investigated into this and my finding is the following:
1. The context menu gets shown properly, however a keyboard wants to pop up from the button, causing a resize, causing a relayout of the context menu
2. The relayout of the context menu sets both `X` and `Y` coordinates to zero [here](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/contextview/contextview.ts#L327)
3. The reason for this seems to be that the Context Menu is living in the shadow dom, and thus when the relayout happens the coordinates are not properly fetched
4. If I change to not use the shadowDom [here](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/contextmenu/contextmenu.ts#L212) the bug is fixed

@sbatten  what is the benefit of using the shadowDom. Is it all right if we just do not use the shadow dom for the editor context menu on the iPad

**Comment by sbatten** [comment]
shadowDom preserves focus most closely with native dialogs by rendering the context menu as a child of the editor. trying to remember, but I think this is necessary for notebooks because focus in each cell is important. I do not recall clearly for this case.

**Comment by isidorn** [comment]
Okey. So I change that on iOS we do not use the shadowDom for the editor. Since without that the context menu positioning is broken on iOS.

**Comment by rebornix** [comment]
@isidorn @sbatten thanks for investigating into this, I didn't finish this in time. Having the context menu rendered in the shadow DOM avoid unnecessary `blur` and this pattern is used in multiple places, I wonder if we would run into similar issues in the future if we don't have it fixed properly in context menu. Also on iOS, right click in a notebook cell editor causes the notebook to lose focus, a left click followed by right click doesn't bring the focus back to the notebook/cell.

For this particular issue, the position of the context menu is correct.

**Comment by isidorn** [comment]
An alternative workaround fix is to not react on relayouts when we get x and y to be 0.
Though I am open for suggestions.

**Comment by isidorn** [comment]
To verify:

1. Open VS Code on the iPad
2. Have focus in the explorer
3. Right click in the editor -> make sure the context menu is nicely positioned
