### ISSUE TITLE
VS Code freezes after pasting inside a file, its file name copied from the Save as windows

### ISSUE THREAD

**Issue by Florian360** [microsoft/vscode#122001]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Create a new file or open an existing one
2. Go to File->Save As...
3. Copy the name of the file ( then close the windows by canceling or saving the file ).
4. Past the name inside the file -> VS Code is freezing for something like 10s, and then nothing is pasted

If I past inside an other text editor, things works fine.
This problem only happen recently, it was working fine before.

- VS Code Version: March 2021 (version 1.55) and also tried on Insider April 2021 (version 1.56)
- OS Version: Linux Ubuntu 20.04.2

VS Code version: Code - Insiders 1.56.0-insider (0310f02dc5d834bb3a7cc421ea5374aec8d011f1, 2021-04-23T05:13:20.010Z)
OS version: Linux x64 5.8.0-50-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 4078)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.31GB (20.53GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
vspre833:30267464
pythonptprofiler:30281269
vscnewfiletext:30288477
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by deepak1556** [comment]
Unable to repro with latest stable `1.73`
