### ISSUE TITLE
window background color stays the same after theme change (visual bug)

### ISSUE THREAD

**Issue by AhmetEsad** [microsoft/vscode#122063]
- VS Code Version: 1.55.2
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. change theme
2. try changing the size of the app window so you can see the actual window background color (see video)
https://user-images.githubusercontent.com/38183175/115924411-5a27d700-a488-11eb-8c70-d738a33fde80.mp4

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
It's a Electron issue. Duplicate of https://github.com/electron/electron/issues/9608
