### ISSUE TITLE
terminal.integrated.env.osx in workspace settings stopped working

### ISSUE THREAD

**Issue by farfromrefug** [microsoft/vscode#122104]
- VS Code Version: 1.56.0-insider (Universal) Commit: 7ce1499d9541ba2acf66cd30a9054bd7818a8f80
- OS Version: Macos Big Sur

Steps to Reproduce:

1. add `terminal.integrated.env.osx` to your workspace settings
2. look at the hover tip
<img width="456" alt="Screenshot 2021-04-24 at 17 51 09" src="https://user-images.githubusercontent.com/655344/115964679-ea682980-a525-11eb-8d1f-4e16e8c9da2c.png">

This is new in VScode Insiders.

Does this issue occur when all extensions are disabled?: Yes

**Comment by esakkik** [comment]
Any specific reason why this has been removed?

**Comment by farfromrefug** [comment]
@meganrogge could we have news on this? It broke my dev process for all my projects. I can go back on non insiders build, but i would rather this get fixed.

**Comment by psharm8** [comment]
This is not only for osx, I am facing the same problem on windows. 
I have multiple project workspaces that work with different terminals like pwsh, cmd and Cygwin.
Based on the workspace settings, I used to get the correct terminal as default, now since the workspace default doesn't work I have to add the correct terminal by picking the profile manually.

**Comment by Tyriar** [comment]
We disabled this in Insiders and it will also be disabled in the upcoming v1.56 until workspace trust lands. Details here: https://github.com/microsoft/vscode/issues/121470

**Comment by farfromrefug** [comment]
@Tyriar ok but pretty big deal to disable this "until" it lands. You broke a dev env for a lot of users using the insiders build.
Right now the only solution we have is to go back to the official build, migrate all of our plugins and settings... quite a big deal.
Any idea on when trust lands will be implemented?

**Comment by Tyriar** [comment]
You convinced me that this will probably cause a bunch of problems for people. I've been working this morning on bringing this back in the form of a setting, so you won't get notified about it but you will be able to set `"terminal.integrated.allowWorkspaceConfiguration": true` to workaround the problem in Insiders and in the upcoming stable build.

**Comment by farfromrefug** [comment]
@Tyriar thanks a lot for rolling back on this! really appreciated

**Comment by Tyriar** [comment]
@alexdima will verify this one

**Comment by farfromrefug** [comment]
@Tyriar it seems to be broken again. even with `"terminal.integrated.allowWorkspaceConfiguration": true` i dont have my env variables in the integrated terminal. any idea?

**Comment by esakkik** [comment]
@farfromrefug `"terminal.integrated.allowWorkspaceConfiguration": true` this config needs to be added to your user settings 
worked fine for me

**Comment by farfromrefug** [comment]
@esakkik thanks! thanks to you i found the issue. The reason is that you can have both `terminal.integrated.env.osx` in user settings and workspace settings ! and i just added it in user settings.
Without it it works
