### ISSUE TITLE
Allow right click context menu in webviews

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#12215]
- VSCode Version: 1.5.2
- OS Version: Windows 10 Anniversary update

Steps to Reproduce:
1. As title. And I think we need these features to make the `preview.html` function more useful in extension.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8794

**Comment by mjbvz** [comment]
Closing as this feature request was filed over a year ago and at this time only has one up vote
