### ISSUE TITLE
File explorer can be open in same window while the terminal is already open

### ISSUE THREAD

**Issue by navdeepghai1** [microsoft/vscode#122116]
I am having issue with opening file explorer.

## Scenario:
When I connect to ssh server before I open the file explorer, the terminal is getting disappear when I open the file explorer with terminal already opened.
It's creating issue when there's a terminal command already running and if the same time I open the file explorer terminal is getting disappear and there's no way to bring it back again.

Demo:
https://user-images.githubusercontent.com/30634335/115979189-8871e900-a552-11eb-8e16-bb43cdff4559.mov

**Comment by isidorn** [comment]
There is no problem here, this is behaving as designed. Thus closing.
