### ISSUE TITLE
文件关闭了，然后打开, 再按ctrl +z,会把以前修改的代码还原 

### ISSUE THREAD

**Issue by awhlmycn** [microsoft/vscode#122127]
1.编辑一个文件，保存，然后再关闭这个文件2.打开刚才编辑的文件，按ctrl+z 会还原上一次的修改3.怎么关闭还原上一次的修改这个功能 需求 ： 修改的文件，被关闭后,就不让再撤销了

**Comment by markkyaw** [comment]
I believe this is what OP meant:
1. Make changes to a file, save the file, then close it.
2. Reopen said file, hitting `ctrl + z` will undo the changes that was made before closing the file
3. How come it's possible to undo changes to a file that has been saved and closed previously?
4. Feature request: once a file have been closed, `ctrl + z` shouldn't undo the changes that was made before the file was closed

**Comment by awhlmycn** [comment]
Make changes to a file, save the file, then close it.
Reopen said file, hitting ctrl + z will undo the changes that was made before closing the file
How come it's possible to undo changes to a file that has been saved and closed previously?
Feature request: once a file have been closed, ctrl + z shouldn't undo the changes that was made before the file was closed

**Comment by alexdima** [comment]
Let's track in #122158
