### ISSUE TITLE
Right-click context menu closes with mouse release when some text is selected using double left-click

### ISSUE THREAD

**Issue by aditya18007** [microsoft/vscode#122160]
Issue Type: <b>Bug</b>

1) Usedouble left-mouse clicks to select some text, for example function name.

2) Right-click to open menu. It will close with mouse release. 

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 5.4.0-72-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|15.45GB (9.50GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5d089feb-ab71-4e4b-b43e-3caa5dc83735|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.4.765268190
vscode-pylance|ms-|2021.4.2
jupyter|ms-|2021.5.745244803
cmake-tools|ms-|1.7.1
cpptools|ms-|1.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820cf:30276953
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by Stig124** [comment]
Happens every single time for me 

VS Code version: Code - Insiders 1.56.0-insider (4e185d8986339717e593be19bc75288905ffbb51, 2021-04-30T23:20:18.681Z)
OS version: Linux x64 5.12.0-1-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 4134)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.28GB (1.46GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 637b518b-0295-4514-8b73-bb3d14e2cb16 --crash-reporter-id 637b518b-0295-4514-8b73-bb3d14e2cb16|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/default|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (243)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.1.0
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|12.1.0
arepl|alm|2.0.2
where-am-i|ant|0.1.4
ACF-Snippet|ant|1.9.0
asciidoctor-vscode|asc|2.8.9
code-gnu-global|aus|0.2.2
inf|bag|0.0.1
bat-snippets|bat|0.2.0
vscode-django|bat|1.6.0
Nix|bbe|1.0.1
vagrant|bbe|0.5.0
vscode-log-viewer|ber|0.12.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.1.0
markdown-preview-github-styles|bie|0.2.0
print-it|bma|0.1.4
vscode-intelephense-client|bme|1.7.1
mermaid-markdown-syntax-highlighting|bpr|1.2.0
vscode-tailwindcss|bra|0.5.10
split-lines|bra|1.0.2
xml2json|bui|1.2.4
multi-cursor-case-preserve|Car|1.0.5
vscode-opennewinstance|chr|0.0.7
npm-intellisense|chr|1.3.1
path-intellisense|chr|2.3.0
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
vscode-css-modules|cli|0.2.3
jsrefactor|cms|2.20.6
gitignore|cod|0.6.0
bracket-pair-colorizer-2|Coe|0.2.0
doxdocgen|csc|1.2.1
vscode-autohotkey-plus|cwe|2.6.2
yaml-key-viewer|cyb|0.2.2
dakara-foldplus|dak|1.5.1
css-variables-autocomplete|dan|0.0.3
split-html-attributes|dan|1.0.10
markdown-table-prettify|dar|3.4.0
vscode-markdownlint|Dav|0.40.4
redis-xplorer|Dav|1.2.7
jshint|dba|0.11.0
vscode-eslint|dba|2.1.20
vscode-quick-select|dba|0.2.9
vscode-faker|dee|1.5.0
vs-code-snippet-generator|dku|1.1.0
sync-env|don|1.0.6
git-extension-pack|don|0.1.3
githistory|don|0.6.16
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|11.4.1
vscode-html-css|ecm|1.10.2
replacequotes|eda|0.0.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.21
vscode-great-icons|emm|2.1.73
json-tools|eri|1.0.2
prettier-vscode|esb|6.3.2
font-switcher|eva|4.0.1
vscode-open-in-github|fab|1.3.0
git-project-manager|fel|1.7.1
php-debug|fel|1.14.12
php-intellisense|fel|2.3.14
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.4
stringtosql|flp|0.0.1
auto-close-tag|for|0.5.10
auto-rename-tag|for|0.1.6
code-runner|for|0.11.3
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
shell-format|fox|7.1.0
scs-script|Fra|0.0.2
duplicate|gee|1.0.1
chocolatey-vscode|gep|0.7.2
vscode-pull-request-github|Git|0.25.1
fast-snippet|giy|1.0.1
mdmath|goe|2.5.1
go-nightly|gol|2021.4.3016
json2ts|Gre|0.0.6
align-mode|Gru|0.0.21
todo-tree|Gru|0.0.213
editorenhancements|gur|1.0.1
javascript-essentials|Gyd|0.0.7
gitignore-templates|has|1.0.1
vscode-drawio|hed|1.4.0
randomeverything|hel|0.0.3
docker-linter|hen|0.5.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.5
output-colorizer|IBM|0.1.2
applescript|idl|0.20.0
phpcs|ika|1.0.5
vscode-placeholder-images|Jak|0.1.0
RelativePath|jak|1.4.0
vscode-requirements|jan|0.1.0
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.15.5
better-dockerfile-syntax|jef|1.0.2
vscode-todo-highlight|jgc|2.0.1
vscode-gnupg-tool|JHe|1.3.9
vscode-wordpress-hooks|joh|0.5.4
wordpress-vscode-extensionpack|jpa|1.2.0
vscode-colorize|kam|0.11.1
vscode-gist|ken|3.0.3
vsc-python-indent|Kev|1.14.2
plusplus|ksm|1.1.1
rpm-spec|Lau|0.3.2
vscord|Leo|3.2.3
sftp|lix|1.12.9
vscode-JS-CSS-HTML-formatter|lon|0.2.3
edge|luo|0.3.2
kconfig|luv|1.0.3
bash-ide-vscode|mad|1.11.0
autoconf|mae|0.1.0
MagicPython|mag|1.1.0
VS-code-vagrantfile|mar|0.0.7
vscode-simple-readme|mau|1.0.1
markdown-shortcuts|mdi|0.12.0
template-string-converter|meg|0.4.7
python-path|mge|0.0.11
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-filesize|mkx|3.1.0
select-part-of-word|mle|1.0.1
vscode-html-format|moh|0.0.4
compare-folders|mos|0.21.0
language-gettext|mro|0.2.0
vscode-docker|ms-|1.12.1
vscode-kubernetes-tools|ms-|1.3.2
python|ms-|2021.5.746022950-dev
vscode-pylance|ms-|2021.4.3
jupyter|ms-|2021.6.798918866
remote-containers|ms-|0.174.0
remote-ssh|ms-|0.65.4
remote-ssh-edit|ms-|0.65.4
remote-wsl|ms-|0.56.1
vscode-remote-extensionpack|ms-|0.20.0
brackets-pack|ms-|0.1.1
cpptools|ms-|1.3.1
cpptools-extension-pack|ms-|1.0.0
hexeditor|ms-|1.6.0
js-debug-companion|ms-|1.0.13
powershell-preview|ms-|2021.4.2
vsliveshare|ms-|1.0.4131
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.12.12
JavaScriptSnippets|nat|0.2.0
php-docblocker|nei|2.1.0
vscode-javascript-snippet|Nic|0.0.16
update-python-packages-and-requirements-txt|niz|1.1.3
autodocstring|njp|0.5.4
incrementor|nms|1.0.3
printcode|nob|3.0.0
favorites|ole|1.5.1
vscode-jest|Ort|3.2.0
vscode-html-scss|P-d|0.0.42
colorful-comments|Par|0.6.2
vscode-versionlens|pfl|1.0.9
vscode-gitignore-generator|pio|1.0.3
material-icon-theme|PKi|4.6.0
polacode|pnp|0.3.4
vscode-css-peek|pra|4.1.3
quicktype|qui|12.0.46
sass-helper|ram|0.0.2
ruby|reb|0.28.1
fabric8-analytics|red|0.3.2
java|red|0.79.0
vscode-commons|red|0.0.6
vscode-xml|red|0.16.0
vscode-yaml|red|0.18.0
base-development-extensions-pack|ric|1.43.0
perl|ric|2.2.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.6.1
snippets-ranger|rob|0.19.0
zsh-debug|rog|0.1.3
arduino-snippets|ron|1.0.2
color-manager|roy|0.6.2
partial-diff|ryu|1.4.3
copy-text|sal|0.4.9
vscode-javascript-booster|sbu|14.0.1
bash-beautify|sha|0.1.1
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.5.18
html5-boilerplate|sid|1.1.1
svg-preview|Sim|2.8.3
vscode-fileutils|sle|3.4.5
vscode-zipexplorer|sle|0.3.1
comment-divider|sta|0.3.0
vscode-asciidoc|sta|0.0.3
vscord|Str|0.5.3
ignore|Syl|0.0.4
open-in-browser|tec|2.0.0
hex-to-tailwind|Ted|1.1.0
vs-code-node-require|tgr|1.10.2
umlet|the|1.0.3
vscode-readme-pattern|tho|1.3.0
rmarkdown|Tia|0.0.14
shellcheck|tim|0.14.1
tizentv|tiz|1.2.3
pdf|tom|1.1.0
vscode-pets|ton|1.6.0
latex-support|tor|3.6.0
python-extended-snippets|tus|0.0.1
pypi-assistant|twi|1.0.4
sort-lines|Tyr|1.9.0
vscode-choosealicense|ult|0.4.0
errorlens|use|3.2.6
highlight-matching-tag|vin|0.10.0
vscodeintellicode|Vis|1.2.12
colonize|vms|2.2.2
vscode-arduino|vsc|0.4.2
vscode-java-debug|vsc|0.33.1
vscode-icons|vsc|11.4.0
vscode-todo-highlight|way|1.0.4
jinja|who|0.0.8
vscode-js-console-utils|wht|0.7.0
vscode-ruby|win|0.28.0
vscode-import-cost|wix|2.15.0
change-case|wma|1.0.0
vsc-jsonsnippets|wmo|0.9.3
vsc-meta-snippet|wmo|0.1.1
any-swap|wol|0.1.3
wordpress-toolbox|wor|1.3.9
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
livecode|xir|1.3.10
txt-syntax|xsh|0.1.5
vscode-surround|yat|1.1.2
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2
commentbars|zfz|0.0.10
html-css-class-completion|Zig|1.20.0
classnametocss|zit|0.0.5
vscode-open-in-github|ziy|1.3.6

(11 theme extensions excluded)

</details>
