### ISSUE TITLE
Extension different exectution in Debug Mode vs installed from package

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#122199]
Version: 1.56.0-insider (user setup)
Commit: 633562da380f9161ea2fd783e561eed508cfbbea
Date: 2021-04-26T05:14:38.204Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21364

Steps to Reproduce:

1. Run a Extension from Debug Mode `F5`
2. Package Extension, Install package and Restart VS Code

**Behavior:**
The extension works correct and as intended in Debug Mode `(F5)`, however if I package the extension and install it, it throws node errors, in our case the following (the node error is not the issue I am reporting here).
Both way use the same bundled code. This let me conclude that running from package has a different runtime than running in Debug Mode, which seems wrong to me. Debug Mode should mirror the final result completely with additional log access.
```
⚠ WARN: Invalid host defined options
⚠ WARN: TypeError: Invalid host defined options
```

**Comment by isidorn** [comment]
Sorry but I think you should consult with other extension authors and they might be able to help.
