### ISSUE TITLE
Listing previous Insiders version download link

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#122136]
When I'm checking for Visual Studio Code Insiders bugs, it's hard to build it myself and do a binary search...
It is possible to use the list yourself using the API for checking the latest version periodically, but I do not want to use this because it is not a generally known API.

**Comment by joaomoreno** [comment]
The following API already existed, which returns the last 200 released versions' commit ids:

```
https://update.code.visualstudio.com/api/commits/QUALITY/PLATFORM
```

Examples:

```
https://update.code.visualstudio.com/api/commits/insider/win32-x64
https://update.code.visualstudio.com/api/commits/insider/darwin
https://update.code.visualstudio.com/api/commits/stable/darwin
```

With https://github.com/microsoft/vscode/issues/122396, you can now fetch additional information per commit ID, namely the download URL.

**Comment by joaomoreno** [comment]
@yamachu, you can help us out by confirming things are working as expected. If things look good, please leave a comment with the text `/verified` to let us know.

**Comment by joaomoreno** [comment]
@yamachu Any chance you can confirm whether this works?

**Comment by yamachu** [comment]
I have missed this notification, sorry.
It seems to be good!
Thanks @joaomoreno !
